apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xrootd.fullname" $ }}-tls-cert
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "xrootd.labels" $ | nindent 4 }}
type: Opaque
stringData:
  hostcert.pem: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xrootd.fullname" $ }}-tls-key
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "xrootd.labels" $ | nindent 4 }}
type: Opaque
stringData:
  hostkey.pem: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xrootd.fullname" $ }}-ca-certs
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "xrootd.labels" $ | nindent 4 }}
data: {}
