var searchData=
[
  ['o_20and_20shared_20response_20chain_20builders_0',['aio — Thread-pool async file I/O and shared response-chain builders',['../md_src_2core_2aio_2README.html',1,'']]],
  ['o_20state_20machine_20for_20tt_20root_3a_20tt_1',['connection — TCP connection lifecycle, framing, and the async I/O state machine for &lt;tt&gt;root://&lt;/tt&gt;',['../md_src_2protocols_2root_2connection_2README.html',1,'']]],
  ['o_20verb_20layer_2',['src/fs/core — the shared &lt;tt&gt;vfs&lt;/tt&gt; I/O verb layer',['../md_src_2fs_2core_2README.html',1,'']]],
  ['object_3',['src/core/types — Core type definitions, tunables, and the canonical identity object',['../md_src_2core_2types_2README.html',1,'']]],
  ['observability_20—_20metrics_20packet_20marking_20dashboard_20and_20access_20logs_4',['observability — metrics, packet marking, dashboard, and access logs',['../md_src_2observability_2README.html',1,'']]],
  ['observation_20tap_5',['relay — transparent pass-through relay with a passive observation tap',['../md_src_2protocols_2root_2relay_2README.html',1,'']]],
  ['observation_20tap_20decode_20sink_20fan_20out_6',['tap — ngx-free protocol observation tap (decode + sink fan-out)',['../md_src_2net_2tap_2README.html',1,'']]],
  ['oci_20—_20the_20oci_20distribution_20plane_3a_20pull_20through_20mirror_20local_20registry_7',['oci — the OCI Distribution plane: pull-through mirror + local registry',['../md_src_2protocols_2oci_2README.html',1,'']]],
  ['one_20subdirectory_20per_20wire_20protocol_8',['protocols — one subdirectory per wire protocol',['../md_src_2protocols_2README.html',1,'']]],
  ['op_20implementations_9',['fs/vfs — the VFS facade (public API + per-op implementations)',['../md_src_2fs_2vfs_2README.html',1,'']]],
  ['opcode_20dispatcher_10',['handshake — XRootD stream request entry point and opcode dispatcher',['../md_src_2protocols_2root_2handshake_2README.html',1,'']]],
  ['opcode_20handlers_20the_20stream_20write_20path_11',['write — XRootD mutating-opcode handlers (the stream write path)',['../md_src_2protocols_2root_2write_2README.html',1,'']]],
  ['opcodes_20and_20the_20file_20handle_20lifecycle_12',['read — XRootD read-side opcodes and the file-handle lifecycle',['../md_src_2protocols_2root_2read_2README.html',1,'']]],
  ['openssl_20x_20509_20pki_20core_20for_20gsi_20and_20webdav_20certificate_20auth_13',['crypto — shared OpenSSL X.509 / PKI core for GSI and WebDAV certificate auth',['../md_src_2auth_2crypto_2README.html',1,'']]],
  ['operations_14',['fattr — XRootD &lt;tt&gt;kXR_fattr&lt;/tt&gt; extended-attribute operations',['../md_src_2protocols_2root_2fattr_2README.html',1,'']]],
  ['optional_20voms_20virtual_20organisation_20extraction_20from_20x_20509_20proxies_15',['voms — Optional VOMS virtual-organisation extraction from X.509 proxies',['../md_src_2auth_2voms_2README.html',1,'']]],
  ['organisation_20extraction_20from_20x_20509_20proxies_16',['voms — Optional VOMS virtual-organisation extraction from X.509 proxies',['../md_src_2auth_2voms_2README.html',1,'']]],
  ['origin_20mirroring_17',['&lt;tt&gt;src/fs/cache/&lt;/tt&gt; — XCache-style read-through cache and write-through origin mirroring',['../md_src_2fs_2cache_2README.html',1,'']]],
  ['origin_20tt_20—_20origin_20transport_20pelican_20advertisement_20for_20the_20read_20through_20cache_18',['&lt;tt&gt;src/fs/cache/origin/&lt;/tt&gt; — origin transport + Pelican advertisement for the read-through cache',['../md_src_2fs_2cache_2origin_2README.html',1,'']]],
  ['out_19',['tap — ngx-free protocol observation tap (decode + sink fan-out)',['../md_src_2net_2tap_2README.html',1,'']]],
  ['outbound_20—_20the_20blocking_20source_20session_20client_20for_20native_20tpc_20pulls_20',['outbound — the blocking source-session client for native TPC pulls',['../md_src_2tpc_2outbound_2README.html',1,'']]],
  ['outbound_20gsi_20authentication_20for_20the_20tpc_20pull_20socket_21',['gsi — outbound GSI authentication for the TPC pull socket',['../md_src_2tpc_2gsi_2README.html',1,'']]],
  ['outbound_20tt_20gsiftp_3a_20tt_20storage_20driver_22',['&lt;tt&gt;src/fs/backend/gsiftp/&lt;/tt&gt; — outbound &lt;tt&gt;gsiftp://&lt;/tt&gt; storage driver',['../md_src_2fs_2backend_2gsiftp_2README.html',1,'']]],
  ['outbound_20xrootd_20redirector_20proxy_20client_20manager_20side_20server_20to_20server_20query_23',['upstream — outbound XRootD redirector/proxy client (manager-side server-to-server query)',['../md_src_2net_2upstream_2README.html',1,'']]],
  ['over_20backends_24',['tier — composable storage tiers (cache/stage decorators over backends)',['../md_src_2fs_2tier_2README.html',1,'']]],
  ['over_20the_20export_20root_25',['webdav — HTTP/WebDAV/HTTPS gateway (&lt;tt&gt;davs://&lt;/tt&gt;, &lt;tt&gt;http://&lt;/tt&gt;) over the export root',['../md_src_2protocols_2webdav_2README.html',1,'']]],
  ['over_20the_20local_20export_20root_26',['s3 — S3-compatible REST endpoint over the local export root',['../md_src_2protocols_2s3_2README.html',1,'']]],
  ['over_20tt_20root_3a_20tt_27',['&lt;tt&gt;src/protocols/ssi/&lt;/tt&gt; — XrdSsi request/response service over &lt;tt&gt;root://&lt;/tt&gt;',['../md_src_2protocols_2ssi_2README.html',1,'']]],
  ['overflow_20safe_20size_20math_28',['shared — cross-protocol helper library (HTTP file serving + overflow-safe size math)',['../md_src_2protocols_2shared_2README.html',1,'']]]
];
