var searchData=
[
  ['table_0',['stream — &lt;tt&gt;ngx_stream_brix_module&lt;/tt&gt; descriptor &amp; directive table',['../md_src_2protocols_2root_2stream_2README.html',1,'']]],
  ['tap_1',['relay — transparent pass-through relay with a passive observation tap',['../md_src_2protocols_2root_2relay_2README.html',1,'']]],
  ['tap_20—_20ngx_20free_20protocol_20observation_20tap_20decode_20sink_20fan_20out_2',['tap — ngx-free protocol observation tap (decode + sink fan-out)',['../md_src_2net_2tap_2README.html',1,'']]],
  ['tape_20service_3',['&lt;tt&gt;src/protocols/ssi/svc_cta/&lt;/tt&gt; — flagship CTA tape service',['../md_src_2protocols_2ssi_2svc__cta_2README.html',1,'']]],
  ['tcp_20connection_20lifecycle_20framing_20and_20the_20async_20i_20o_20state_20machine_20for_20tt_20root_3a_20tt_4',['connection — TCP connection lifecycle, framing, and the async I/O state machine for &lt;tt&gt;root://&lt;/tt&gt;',['../md_src_2protocols_2root_2connection_2README.html',1,'']]],
  ['the_20async_20i_20o_20state_20machine_20for_20tt_20root_3a_20tt_5',['connection — TCP connection lifecycle, framing, and the async I/O state machine for &lt;tt&gt;root://&lt;/tt&gt;',['../md_src_2protocols_2root_2connection_2README.html',1,'']]],
  ['the_20auth_20gate_6',['authz — path-level authorization: ACL rules, authdb, and the auth gate',['../md_src_2auth_2authz_2README.html',1,'']]],
  ['the_20bad_20actor_20guard_7',['net/httpguard — HTTP adapter for the bad-actor guard',['../md_src_2net_2httpguard_2README.html',1,'']]],
  ['the_20blocking_20source_20session_20client_20for_20native_20tpc_20pulls_8',['outbound — the blocking source-session client for native TPC pulls',['../md_src_2tpc_2outbound_2README.html',1,'']]],
  ['the_20canonical_20identity_20object_9',['src/core/types — Core type definitions, tunables, and the canonical identity object',['../md_src_2core_2types_2README.html',1,'']]],
  ['the_20cvmfs_3a_20site_20cache_20experimental_20scvmfs_3a_20tls_20variant_10',['cvmfs — the cvmfs:// site cache (+ experimental scvmfs:// TLS variant)',['../md_src_2protocols_2cvmfs_2README.html',1,'']]],
  ['the_20export_20root_11',['webdav — HTTP/WebDAV/HTTPS gateway (&lt;tt&gt;davs://&lt;/tt&gt;, &lt;tt&gt;http://&lt;/tt&gt;) over the export root',['../md_src_2protocols_2webdav_2README.html',1,'']]],
  ['the_20file_20handle_20lifecycle_12',['read — XRootD read-side opcodes and the file-handle lifecycle',['../md_src_2protocols_2root_2read_2README.html',1,'']]],
  ['the_20local_20export_20root_13',['s3 — S3-compatible REST endpoint over the local export root',['../md_src_2protocols_2s3_2README.html',1,'']]],
  ['the_20oci_20distribution_20plane_3a_20pull_20through_20mirror_20local_20registry_14',['oci — the OCI Distribution plane: pull-through mirror + local registry',['../md_src_2protocols_2oci_2README.html',1,'']]],
  ['the_20prometheus_20tt_20metrics_20tt_20exporter_15',['metrics — shared-memory counters and the Prometheus &lt;tt&gt;/metrics&lt;/tt&gt; exporter',['../md_src_2observability_2metrics_2README.html',1,'']]],
  ['the_20read_20through_20cache_16',['&lt;tt&gt;src/fs/cache/origin/&lt;/tt&gt; — origin transport + Pelican advertisement for the read-through cache',['../md_src_2fs_2cache_2origin_2README.html',1,'']]],
  ['the_20rpm_20dnf_20pull_20through_20mirror_20phase_20104_20d11_20d15_209_17',['rpm — the RPM/dnf pull-through mirror (phase-104 D11 / D15.9)',['../md_src_2protocols_2rpm_2README.html',1,'']]],
  ['the_20shared_20tt_20vfs_20tt_20i_20o_20verb_20layer_18',['src/fs/core — the shared &lt;tt&gt;vfs&lt;/tt&gt; I/O verb layer',['../md_src_2fs_2core_2README.html',1,'']]],
  ['the_20single_20posix_20filesystem_20data_20plane_19',['fs — Unified VFS: the single POSIX-filesystem data plane',['../md_src_2fs_2README.html',1,'']]],
  ['the_20stream_20write_20path_20',['write — XRootD mutating-opcode handlers (the stream write path)',['../md_src_2protocols_2root_2write_2README.html',1,'']]],
  ['the_20stream_20xrootd_20listener_21',['handoff — single-port protocol handoff for the stream xrootd listener',['../md_src_2protocols_2root_2handoff_2README.html',1,'']]],
  ['the_20tpc_20pull_20socket_22',['gsi — outbound GSI authentication for the TPC pull socket',['../md_src_2tpc_2gsi_2README.html',1,'']]],
  ['the_20tt_20root_3a_20tt_20stream_20protocol_23',['the tt root: tt stream protocol',['../md_src_2auth_2host_2README.html',1,'host — host-based authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol'],['../md_src_2auth_2krb5_2README.html',1,'krb5 — Kerberos 5 authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol'],['../md_src_2auth_2pwd_2README.html',1,'pwd — password (&lt;tt&gt;XrdSecpwd&lt;/tt&gt;) authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol']]],
  ['the_20vfs_20facade_20public_20api_20per_20op_20implementations_24',['fs/vfs — the VFS facade (public API + per-op implementations)',['../md_src_2fs_2vfs_2README.html',1,'']]],
  ['the_20xrootd_20tt_20root_3a_20tt_20tt_20roots_3a_20tt_20protocol_20plane_25',['root — the XRootD (&lt;tt&gt;root://&lt;/tt&gt; / &lt;tt&gt;roots://&lt;/tt&gt;) protocol plane',['../md_src_2protocols_2root_2README.html',1,'']]],
  ['third_20party_20copy_20destination_20side_20pull_26',['tpc — Native XRootD third-party-copy (destination-side pull)',['../md_src_2tpc_2README.html',1,'']]],
  ['third_20party_20copy_20tpc_20core_27',['tpc/common — Protocol-neutral third-party-copy (TPC) core',['../md_src_2tpc_2common_2README.html',1,'']]],
  ['thread_20pool_20async_20file_20i_20o_20and_20shared_20response_20chain_20builders_28',['aio — Thread-pool async file I/O and shared response-chain builders',['../md_src_2core_2aio_2README.html',1,'']]],
  ['through_20cache_29',['&lt;tt&gt;src/fs/cache/origin/&lt;/tt&gt; — origin transport + Pelican advertisement for the read-through cache',['../md_src_2fs_2cache_2origin_2README.html',1,'']]],
  ['through_20cache_20and_20write_20through_20origin_20mirroring_30',['&lt;tt&gt;src/fs/cache/&lt;/tt&gt; — XCache-style read-through cache and write-through origin mirroring',['../md_src_2fs_2cache_2README.html',1,'']]],
  ['through_20mirror_20local_20registry_31',['oci — the OCI Distribution plane: pull-through mirror + local registry',['../md_src_2protocols_2oci_2README.html',1,'']]],
  ['through_20mirror_20phase_20104_20d11_20d15_209_32',['rpm — the RPM/dnf pull-through mirror (phase-104 D11 / D15.9)',['../md_src_2protocols_2rpm_2README.html',1,'']]],
  ['through_20relay_20with_20a_20passive_20observation_20tap_33',['relay — transparent pass-through relay with a passive observation tap',['../md_src_2protocols_2root_2relay_2README.html',1,'']]],
  ['tier_20—_20composable_20storage_20tiers_20cache_20stage_20decorators_20over_20backends_34',['tier — composable storage tiers (cache/stage decorators over backends)',['../md_src_2fs_2tier_2README.html',1,'']]],
  ['tiers_20cache_20stage_20decorators_20over_20backends_35',['tier — composable storage tiers (cache/stage decorators over backends)',['../md_src_2fs_2tier_2README.html',1,'']]],
  ['tls_20variant_36',['cvmfs — the cvmfs:// site cache (+ experimental scvmfs:// TLS variant)',['../md_src_2protocols_2cvmfs_2README.html',1,'']]],
  ['to_20server_20query_37',['upstream — outbound XRootD redirector/proxy client (manager-side server-to-server query)',['../md_src_2net_2upstream_2README.html',1,'']]],
  ['token_20—_20wlcg_20scitoken_20jwt_20and_20macaroon_20bearer_20token_20validation_38',['token — WLCG/SciToken JWT and macaroon bearer-token validation',['../md_src_2auth_2token_2README.html',1,'']]],
  ['token_20bucket_20rate_20limiter_20in_20nginx_20shared_20memory_39',['shm — generic cross-worker key/value store and token-bucket rate limiter in nginx shared memory',['../md_src_2core_2shm_2README.html',1,'']]],
  ['tools_40',['tools',['../md_client_2README.html',1,'&lt;tt&gt;client/&lt;/tt&gt; — native BriX client tools'],['../md_client_2apps_2README.html',1,'&lt;tt&gt;client/apps/&lt;/tt&gt; — native client CLI tools']]],
  ['tpc_20—_20native_20xrootd_20third_20party_20copy_20destination_20side_20pull_41',['tpc — Native XRootD third-party-copy (destination-side pull)',['../md_src_2tpc_2README.html',1,'']]],
  ['tpc_20common_20—_20protocol_20neutral_20third_20party_20copy_20tpc_20core_42',['tpc/common — Protocol-neutral third-party-copy (TPC) core',['../md_src_2tpc_2common_2README.html',1,'']]],
  ['tpc_20control_20plane_20destination_20side_43',['engine — native-TPC control plane (destination side)',['../md_src_2tpc_2engine_2README.html',1,'']]],
  ['tpc_20pull_20socket_44',['gsi — outbound GSI authentication for the TPC pull socket',['../md_src_2tpc_2gsi_2README.html',1,'']]],
  ['tpc_20pulls_45',['outbound — the blocking source-session client for native TPC pulls',['../md_src_2tpc_2outbound_2README.html',1,'']]],
  ['traffic_20mirroring_20shadow_20replay_20for_20xrootd_20and_20webdav_46',['mirror — fire-and-forget traffic mirroring (shadow replay) for XRootD and WebDAV',['../md_src_2net_2mirror_2README.html',1,'']]],
  ['transfer_20engine_47',['&lt;tt&gt;src/fs/xfer/&lt;/tt&gt; — unified durable-transfer engine',['../md_src_2fs_2xfer_2README.html',1,'']]],
  ['transfer_20monitor_20rest_20admin_20write_20api_48',['dashboard — live HTTPS transfer monitor + REST admin write API',['../md_src_2observability_2dashboard_2README.html',1,'']]],
  ['transparent_20pass_20through_20relay_20with_20a_20passive_20observation_20tap_49',['relay — transparent pass-through relay with a passive observation tap',['../md_src_2protocols_2root_2relay_2README.html',1,'']]],
  ['transparent_20xrootd_20reverse_20proxy_20tt_20brix_5fproxy_20tt_50',['proxy — Transparent XRootD reverse proxy (&lt;tt&gt;brix_proxy&lt;/tt&gt;)',['../md_src_2net_2proxy_2README.html',1,'']]],
  ['transport_20pelican_20advertisement_20for_20the_20read_20through_20cache_51',['&lt;tt&gt;src/fs/cache/origin/&lt;/tt&gt; — origin transport + Pelican advertisement for the read-through cache',['../md_src_2fs_2cache_2origin_2README.html',1,'']]],
  ['tree_52',['src — nginx-xrootd Source Tree',['../md_src_2README.html',1,'']]],
  ['tt_20brix_5fproxy_20tt_53',['proxy — Transparent XRootD reverse proxy (&lt;tt&gt;brix_proxy&lt;/tt&gt;)',['../md_src_2net_2proxy_2README.html',1,'']]],
  ['tt_20client_20apps_20tt_20—_20native_20client_20cli_20tools_54',['&lt;tt&gt;client/apps/&lt;/tt&gt; — native client CLI tools',['../md_client_2apps_2README.html',1,'']]],
  ['tt_20client_20lib_20sec_20tt_20—_20native_20client_20authentication_20modules_55',['&lt;tt&gt;client/lib/sec/&lt;/tt&gt; — native client authentication modules',['../md_client_2lib_2auth_2sec_2README.html',1,'']]],
  ['tt_20client_20lib_20tt_20—_20native_20xrootd_20client_20library_20tt_20libbrix_20tt_56',['&lt;tt&gt;client/lib/&lt;/tt&gt; — native XRootD client library (&lt;tt&gt;libbrix&lt;/tt&gt;)',['../md_client_2lib_2README.html',1,'']]],
  ['tt_20client_20preload_20tt_20—_20ld_5fpreload_20posix_20→_20xrootd_20shim_57',['&lt;tt&gt;client/preload/&lt;/tt&gt; — LD_PRELOAD POSIX → XRootD shim',['../md_client_2preload_2README.html',1,'']]],
  ['tt_20client_20tt_20—_20native_20brix_20client_20tools_58',['&lt;tt&gt;client/&lt;/tt&gt; — native BriX client tools',['../md_client_2README.html',1,'']]],
  ['tt_20davs_3a_20tt_20tt_20http_3a_20tt_20over_20the_20export_20root_59',['webdav — HTTP/WebDAV/HTTPS gateway (&lt;tt&gt;davs://&lt;/tt&gt;, &lt;tt&gt;http://&lt;/tt&gt;) over the export root',['../md_src_2protocols_2webdav_2README.html',1,'']]],
  ['tt_20kxr_5fauth_20tt_20dispatcher_20and_20gsi_20x509_20proxy_20certificate_20authentication_60',['gsi — XRootD &lt;tt&gt;kXR_auth&lt;/tt&gt; dispatcher and GSI/x509 proxy-certificate authentication',['../md_src_2auth_2gsi_2README.html',1,'']]],
  ['tt_20kxr_5fdirlist_20tt_20directory_20enumeration_20stream_20protocol_61',['dirlist — XRootD &lt;tt&gt;kXR_dirlist&lt;/tt&gt; directory enumeration (stream protocol)',['../md_src_2protocols_2root_2dirlist_2README.html',1,'']]],
  ['tt_20kxr_5ffattr_20tt_20extended_20attribute_20operations_62',['fattr — XRootD &lt;tt&gt;kXR_fattr&lt;/tt&gt; extended-attribute operations',['../md_src_2protocols_2root_2fattr_2README.html',1,'']]],
  ['tt_20kxr_5fquery_20tt_20sub_20protocol_20tt_20kxr_5fprepare_20tt_20staging_20and_20tt_20kxr_5fset_20tt_20hints_63',['query — XRootD &lt;tt&gt;kXR_query&lt;/tt&gt; sub-protocol, &lt;tt&gt;kXR_prepare&lt;/tt&gt; staging, and &lt;tt&gt;kXR_set&lt;/tt&gt; hints',['../md_src_2protocols_2root_2query_2README.html',1,'']]],
  ['tt_20metrics_20tt_20exporter_64',['metrics — shared-memory counters and the Prometheus &lt;tt&gt;/metrics&lt;/tt&gt; exporter',['../md_src_2observability_2metrics_2README.html',1,'']]],
  ['tt_20ngx_5fstream_5fbrix_5fmodule_20tt_20descriptor_20directive_20table_65',['stream — &lt;tt&gt;ngx_stream_brix_module&lt;/tt&gt; descriptor &amp; directive table',['../md_src_2protocols_2root_2stream_2README.html',1,'']]],
  ['tt_20root_3a_20tt_66',['connection — TCP connection lifecycle, framing, and the async I/O state machine for &lt;tt&gt;root://&lt;/tt&gt;',['../md_src_2protocols_2root_2connection_2README.html',1,'']]],
  ['tt_20root_3a_20tt_20stream_20protocol_67',['tt root: tt stream protocol',['../md_src_2auth_2host_2README.html',1,'host — host-based authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol'],['../md_src_2auth_2krb5_2README.html',1,'krb5 — Kerberos 5 authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol']]],
  ['tt_20root_3a_20tt_20tt_20roots_3a_20tt_20protocol_20plane_68',['root — the XRootD (&lt;tt&gt;root://&lt;/tt&gt; / &lt;tt&gt;roots://&lt;/tt&gt;) protocol plane',['../md_src_2protocols_2root_2README.html',1,'']]],
  ['tt_20root_3a_20tt_20wire_20format_20constants_20packed_20structs_69',['protocol — XRootD &lt;tt&gt;root://&lt;/tt&gt; wire-format constants &amp; packed structs',['../md_src_2protocols_2root_2protocol_2README.html',1,'']]],
  ['tt_20sec_20protbind_20tt_70',['protbind — per-host authentication-protocol binding (XRootD &lt;tt&gt;sec.protbind&lt;/tt&gt;)',['../md_src_2auth_2protbind_2README.html',1,'']]],
  ['tt_20src_20auth_20impersonate_20tt_20—_20per_20request_20unix_20impersonation_20phase_2040_71',['&lt;tt&gt;src/auth/impersonate/&lt;/tt&gt; — per-request UNIX impersonation (phase 40)',['../md_src_2auth_2impersonate_2README.html',1,'']]],
  ['tt_20src_20fs_20backend_20gsiftp_20tt_20—_20outbound_20tt_20gsiftp_3a_20tt_20storage_20driver_72',['&lt;tt&gt;src/fs/backend/gsiftp/&lt;/tt&gt; — outbound &lt;tt&gt;gsiftp://&lt;/tt&gt; storage driver',['../md_src_2fs_2backend_2gsiftp_2README.html',1,'']]],
  ['tt_20src_20fs_20cache_20origin_20tt_20—_20origin_20transport_20pelican_20advertisement_20for_20the_20read_20through_20cache_73',['&lt;tt&gt;src/fs/cache/origin/&lt;/tt&gt; — origin transport + Pelican advertisement for the read-through cache',['../md_src_2fs_2cache_2origin_2README.html',1,'']]],
  ['tt_20src_20fs_20cache_20tt_20—_20xcache_20style_20read_20through_20cache_20and_20write_20through_20origin_20mirroring_74',['&lt;tt&gt;src/fs/cache/&lt;/tt&gt; — XCache-style read-through cache and write-through origin mirroring',['../md_src_2fs_2cache_2README.html',1,'']]],
  ['tt_20src_20fs_20scan_20tt_20—_20bulk_20storage_20scan_20verify_20inventory_20engine_75',['&lt;tt&gt;src/fs/scan/&lt;/tt&gt; — bulk storage scan / verify / inventory engine',['../md_src_2fs_2scan_2README.html',1,'']]],
  ['tt_20src_20fs_20xfer_20tt_20—_20unified_20durable_20transfer_20engine_76',['&lt;tt&gt;src/fs/xfer/&lt;/tt&gt; — unified durable-transfer engine',['../md_src_2fs_2xfer_2README.html',1,'']]],
  ['tt_20src_20protocols_20dig_20tt_20—_20xrddig_20style_20remote_20diagnostics_77',['&lt;tt&gt;src/protocols/dig/&lt;/tt&gt; — XrdDig-style remote diagnostics',['../md_src_2protocols_2dig_2README.html',1,'']]],
  ['tt_20src_20protocols_20srr_20tt_20—_20wlcg_20storage_20resource_20reporting_20srr_20endpoint_78',['&lt;tt&gt;src/protocols/srr/&lt;/tt&gt; — WLCG Storage Resource Reporting (SRR) endpoint',['../md_src_2protocols_2srr_2README.html',1,'']]],
  ['tt_20src_20protocols_20ssi_20svc_5fcta_20tt_20—_20flagship_20cta_20tape_20service_79',['&lt;tt&gt;src/protocols/ssi/svc_cta/&lt;/tt&gt; — flagship CTA tape service',['../md_src_2protocols_2ssi_2svc__cta_2README.html',1,'']]],
  ['tt_20src_20protocols_20ssi_20tt_20—_20xrdssi_20request_20response_20service_20over_20tt_20root_3a_20tt_80',['&lt;tt&gt;src/protocols/ssi/&lt;/tt&gt; — XrdSsi request/response service over &lt;tt&gt;root://&lt;/tt&gt;',['../md_src_2protocols_2ssi_2README.html',1,'']]],
  ['tt_20unix_20tt_20unix_20name_20authentication_20handler_81',['unix — XRootD &lt;tt&gt;unix&lt;/tt&gt; (UNIX-name) authentication handler',['../md_src_2auth_2unix_2README.html',1,'']]],
  ['tt_20vfs_20tt_20i_20o_20verb_20layer_82',['src/fs/core — the shared &lt;tt&gt;vfs&lt;/tt&gt; I/O verb layer',['../md_src_2fs_2core_2README.html',1,'']]],
  ['tt_20xrdsecpwd_20tt_20authentication_20for_20the_20tt_20root_3a_20tt_20stream_20protocol_83',['pwd — password (&lt;tt&gt;XrdSecpwd&lt;/tt&gt;) authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol',['../md_src_2auth_2pwd_2README.html',1,'']]],
  ['tunables_20and_20the_20canonical_20identity_20object_84',['src/core/types — Core type definitions, tunables, and the canonical identity object',['../md_src_2core_2types_2README.html',1,'']]],
  ['type_20definitions_20tunables_20and_20the_20canonical_20identity_20object_85',['src/core/types — Core type definitions, tunables, and the canonical identity object',['../md_src_2core_2types_2README.html',1,'']]],
  ['types_20—_20core_20type_20definitions_20tunables_20and_20the_20canonical_20identity_20object_86',['src/core/types — Core type definitions, tunables, and the canonical identity object',['../md_src_2core_2types_2README.html',1,'']]]
];
