var searchData=
[
  ['packed_20structs_0',['protocol — XRootD &lt;tt&gt;root://&lt;/tt&gt; wire-format constants &amp; packed structs',['../md_src_2protocols_2root_2protocol_2README.html',1,'']]],
  ['packet_20marking_1',['pmark — SciTags packet marking',['../md_src_2observability_2pmark_2README.html',1,'']]],
  ['packet_20marking_20dashboard_20and_20access_20logs_2',['observability — metrics, packet marking, dashboard, and access logs',['../md_src_2observability_2README.html',1,'']]],
  ['parsers_3',['webdav/locks — WebDAV LOCK request-header &amp; body parsers',['../md_src_2protocols_2webdav_2locks_2README.html',1,'']]],
  ['party_20copy_20destination_20side_20pull_4',['tpc — Native XRootD third-party-copy (destination-side pull)',['../md_src_2tpc_2README.html',1,'']]],
  ['party_20copy_20tpc_20core_5',['tpc/common — Protocol-neutral third-party-copy (TPC) core',['../md_src_2tpc_2common_2README.html',1,'']]],
  ['pass_20through_20relay_20with_20a_20passive_20observation_20tap_6',['relay — transparent pass-through relay with a passive observation tap',['../md_src_2protocols_2root_2relay_2README.html',1,'']]],
  ['passive_20observation_20tap_7',['relay — transparent pass-through relay with a passive observation tap',['../md_src_2protocols_2root_2relay_2README.html',1,'']]],
  ['password_20tt_20xrdsecpwd_20tt_20authentication_20for_20the_20tt_20root_3a_20tt_20stream_20protocol_8',['pwd — password (&lt;tt&gt;XrdSecpwd&lt;/tt&gt;) authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol',['../md_src_2auth_2pwd_2README.html',1,'']]],
  ['path_9',['write — XRootD mutating-opcode handlers (the stream write path)',['../md_src_2protocols_2root_2write_2README.html',1,'']]],
  ['path_20—_20untrusted_20path_20confinement_20resolution_20acl_20auth_20gating_20and_20access_20logging_10',['path — untrusted-path confinement, resolution, ACL/auth gating, and access logging',['../md_src_2fs_2path_2README.html',1,'']]],
  ['path_20—_20wire_20path_20extraction_20sanitization_20and_20stat_20formatting_11',['path — wire-path extraction, sanitization, and stat formatting',['../md_src_2protocols_2root_2path_2README.html',1,'']]],
  ['path_20backoff_20negcache_12',['Negative-Path Backoff (negcache)',['../md_src_2core_2negcache_2README.html',1,'']]],
  ['path_20level_20authorization_3a_20acl_20rules_20authdb_20and_20the_20auth_20gate_13',['authz — path-level authorization: ACL rules, authdb, and the auth gate',['../md_src_2auth_2authz_2README.html',1,'']]],
  ['paths_20filesystem_20ssrf_14',['compat — Cross-protocol shared primitives (checksums, paths, filesystem, SSRF)',['../md_src_2core_2compat_2README.html',1,'']]],
  ['per_20file_20metadata_20sidecar_20xmeta_15',['meta — unified per-file metadata sidecar (xmeta)',['../md_src_2fs_2meta_2README.html',1,'']]],
  ['per_20method_20webdav_20precondition_20helpers_16',['webdav/methods — Per-method WebDAV precondition helpers',['../md_src_2protocols_2webdav_2methods_2README.html',1,'']]],
  ['per_20op_20implementations_17',['fs/vfs — the VFS facade (public API + per-op implementations)',['../md_src_2fs_2vfs_2README.html',1,'']]],
  ['per_20request_20unix_20impersonation_20phase_2040_18',['&lt;tt&gt;src/auth/impersonate/&lt;/tt&gt; — per-request UNIX impersonation (phase 40)',['../md_src_2auth_2impersonate_2README.html',1,'']]],
  ['per_20wire_20protocol_19',['protocols — one subdirectory per wire protocol',['../md_src_2protocols_2README.html',1,'']]],
  ['per_20worker_20resource_20init_20',['config — directive lifecycle, startup validation, and per-worker resource init',['../md_src_2core_2config_2README.html',1,'']]],
  ['phase_2025_21',['ratelimit — identity-aware leaky-bucket rate, bandwidth &amp; concurrency limiting (Phase 25)',['../md_src_2net_2ratelimit_2README.html',1,'']]],
  ['phase_2040_22',['&lt;tt&gt;src/auth/impersonate/&lt;/tt&gt; — per-request UNIX impersonation (phase 40)',['../md_src_2auth_2impersonate_2README.html',1,'']]],
  ['phase_2057_20w2_23',['src/protocols/root/zip — ZIP member access (phase-57 W2)',['../md_src_2protocols_2root_2zip_2README.html',1,'']]],
  ['pki_20core_20for_20gsi_20and_20webdav_20certificate_20auth_24',['crypto — shared OpenSSL X.509 / PKI core for GSI and WebDAV certificate auth',['../md_src_2auth_2crypto_2README.html',1,'']]],
  ['plane_25',['plane',['../md_src_2core_2README.html',1,'core — platform primitives shared by every plane'],['../md_src_2fs_2README.html',1,'fs — Unified VFS: the single POSIX-filesystem data plane'],['../md_src_2protocols_2root_2README.html',1,'root — the XRootD (&lt;tt&gt;root://&lt;/tt&gt; / &lt;tt&gt;roots://&lt;/tt&gt;) protocol plane']]],
  ['plane_20destination_20side_26',['engine — native-TPC control plane (destination side)',['../md_src_2tpc_2engine_2README.html',1,'']]],
  ['plane_20server_20registry_20redirect_20cache_20active_20health_20checks_27',['manager — Cluster / redirector control plane (server registry, redirect cache, active health checks)',['../md_src_2net_2manager_2README.html',1,'']]],
  ['platform_20primitives_20shared_20by_20every_20plane_28',['core — platform primitives shared by every plane',['../md_src_2core_2README.html',1,'']]],
  ['pluggable_20origin_20transports_20for_20the_20read_20through_20cache_29',['&lt;tt&gt;src/fs/cache/origin/&lt;/tt&gt; — pluggable origin transports for the read-through cache',['../md_src_2fs_2cache_2origin_2README.html',1,'']]],
  ['pmark_20—_20scitags_20packet_20marking_30',['pmark — SciTags packet marking',['../md_src_2observability_2pmark_2README.html',1,'']]],
  ['point_20and_20opcode_20dispatcher_31',['handshake — XRootD stream request entry point and opcode dispatcher',['../md_src_2protocols_2root_2handshake_2README.html',1,'']]],
  ['pool_20async_20file_20i_20o_20and_20shared_20response_20chain_20builders_32',['aio — Thread-pool async file I/O and shared response-chain builders',['../md_src_2core_2aio_2README.html',1,'']]],
  ['port_20protocol_20handoff_20for_20the_20stream_20xrootd_20listener_33',['handoff — single-port protocol handoff for the stream xrootd listener',['../md_src_2protocols_2root_2handoff_2README.html',1,'']]],
  ['posix_20→_20xrootd_20shim_34',['&lt;tt&gt;client/preload/&lt;/tt&gt; — LD_PRELOAD POSIX → XRootD shim',['../md_client_2preload_2README.html',1,'']]],
  ['posix_20filesystem_20data_20plane_35',['fs — Unified VFS: the single POSIX-filesystem data plane',['../md_src_2fs_2README.html',1,'']]],
  ['precondition_20helpers_36',['webdav/methods — Per-method WebDAV precondition helpers',['../md_src_2protocols_2webdav_2methods_2README.html',1,'']]],
  ['preload_20tt_20—_20ld_5fpreload_20posix_20→_20xrootd_20shim_37',['&lt;tt&gt;client/preload/&lt;/tt&gt; — LD_PRELOAD POSIX → XRootD shim',['../md_client_2preload_2README.html',1,'']]],
  ['primitives_20checksums_20paths_20filesystem_20ssrf_38',['compat — Cross-protocol shared primitives (checksums, paths, filesystem, SSRF)',['../md_src_2core_2compat_2README.html',1,'']]],
  ['primitives_20shared_20by_20every_20plane_39',['core — platform primitives shared by every plane',['../md_src_2core_2README.html',1,'']]],
  ['prometheus_20tt_20metrics_20tt_20exporter_40',['metrics — shared-memory counters and the Prometheus &lt;tt&gt;/metrics&lt;/tt&gt; exporter',['../md_src_2observability_2metrics_2README.html',1,'']]],
  ['protocol_41',['protocol',['../md_src_2protocols_2root_2dirlist_2README.html',1,'dirlist — XRootD &lt;tt&gt;kXR_dirlist&lt;/tt&gt; directory enumeration (stream protocol)'],['../md_src_2auth_2host_2README.html',1,'host — host-based authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol'],['../md_src_2auth_2krb5_2README.html',1,'krb5 — Kerberos 5 authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol'],['../md_src_2protocols_2README.html',1,'protocols — one subdirectory per wire protocol'],['../md_src_2auth_2pwd_2README.html',1,'pwd — password (&lt;tt&gt;XrdSecpwd&lt;/tt&gt;) authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol']]],
  ['protocol_20—_20xrootd_20tt_20root_3a_20tt_20wire_20format_20constants_20packed_20structs_42',['protocol — XRootD &lt;tt&gt;root://&lt;/tt&gt; wire-format constants &amp; packed structs',['../md_src_2protocols_2root_2protocol_2README.html',1,'']]],
  ['protocol_20agnostic_20bad_20actor_20classifier_43',['net/guard — protocol-agnostic bad-actor classifier',['../md_src_2net_2guard_2README.html',1,'']]],
  ['protocol_20handoff_20for_20the_20stream_20xrootd_20listener_44',['handoff — single-port protocol handoff for the stream xrootd listener',['../md_src_2protocols_2root_2handoff_2README.html',1,'']]],
  ['protocol_20helper_20library_20http_20file_20serving_20overflow_20safe_20size_20math_45',['shared — cross-protocol helper library (HTTP file serving + overflow-safe size math)',['../md_src_2protocols_2shared_2README.html',1,'']]],
  ['protocol_20neutral_20third_20party_20copy_20tpc_20core_46',['tpc/common — Protocol-neutral third-party-copy (TPC) core',['../md_src_2tpc_2common_2README.html',1,'']]],
  ['protocol_20observation_20tap_20decode_20sink_20fan_20out_47',['tap — ngx-free protocol observation tap (decode + sink fan-out)',['../md_src_2net_2tap_2README.html',1,'']]],
  ['protocol_20plane_48',['root — the XRootD (&lt;tt&gt;root://&lt;/tt&gt; / &lt;tt&gt;roots://&lt;/tt&gt;) protocol plane',['../md_src_2protocols_2root_2README.html',1,'']]],
  ['protocol_20shared_20primitives_20checksums_20paths_20filesystem_20ssrf_49',['compat — Cross-protocol shared primitives (checksums, paths, filesystem, SSRF)',['../md_src_2core_2compat_2README.html',1,'']]],
  ['protocol_20tt_20kxr_5fprepare_20tt_20staging_20and_20tt_20kxr_5fset_20tt_20hints_50',['query — XRootD &lt;tt&gt;kXR_query&lt;/tt&gt; sub-protocol, &lt;tt&gt;kXR_prepare&lt;/tt&gt; staging, and &lt;tt&gt;kXR_set&lt;/tt&gt; hints',['../md_src_2protocols_2root_2query_2README.html',1,'']]],
  ['protocols_20—_20one_20subdirectory_20per_20wire_20protocol_51',['protocols — one subdirectory per wire protocol',['../md_src_2protocols_2README.html',1,'']]],
  ['protocols_20dig_20tt_20—_20xrddig_20style_20remote_20diagnostics_52',['&lt;tt&gt;src/protocols/dig/&lt;/tt&gt; — XrdDig-style remote diagnostics',['../md_src_2protocols_2dig_2README.html',1,'']]],
  ['protocols_20root_20zip_20—_20zip_20member_20access_20phase_2057_20w2_53',['src/protocols/root/zip — ZIP member access (phase-57 W2)',['../md_src_2protocols_2root_2zip_2README.html',1,'']]],
  ['protocols_20srr_20tt_20—_20wlcg_20storage_20resource_20reporting_20srr_20endpoint_54',['&lt;tt&gt;src/protocols/srr/&lt;/tt&gt; — WLCG Storage Resource Reporting (SRR) endpoint',['../md_src_2protocols_2srr_2README.html',1,'']]],
  ['protocols_20ssi_20svc_5fcta_20tt_20—_20flagship_20cta_20tape_20service_55',['&lt;tt&gt;src/protocols/ssi/svc_cta/&lt;/tt&gt; — flagship CTA tape service',['../md_src_2protocols_2ssi_2svc__cta_2README.html',1,'']]],
  ['protocols_20ssi_20tt_20—_20xrdssi_20request_20response_20service_20over_20tt_20root_3a_20tt_56',['&lt;tt&gt;src/protocols/ssi/&lt;/tt&gt; — XrdSsi request/response service over &lt;tt&gt;root://&lt;/tt&gt;',['../md_src_2protocols_2ssi_2README.html',1,'']]],
  ['proxies_57',['voms — Optional VOMS virtual-organisation extraction from X.509 proxies',['../md_src_2auth_2voms_2README.html',1,'']]],
  ['proxy_20—_20transparent_20xrootd_20reverse_20proxy_20tt_20brix_5fproxy_20tt_58',['proxy — Transparent XRootD reverse proxy (&lt;tt&gt;brix_proxy&lt;/tt&gt;)',['../md_src_2net_2proxy_2README.html',1,'']]],
  ['proxy_20certificate_20authentication_59',['gsi — XRootD &lt;tt&gt;kXR_auth&lt;/tt&gt; dispatcher and GSI/x509 proxy-certificate authentication',['../md_src_2auth_2gsi_2README.html',1,'']]],
  ['proxy_20client_20manager_20side_20server_20to_20server_20query_60',['upstream — outbound XRootD redirector/proxy client (manager-side server-to-server query)',['../md_src_2net_2upstream_2README.html',1,'']]],
  ['proxying_20shadowing_20and_20connection_20defense_61',['net — clustering, proxying, shadowing, and connection defense',['../md_src_2net_2README.html',1,'']]],
  ['public_20api_20per_20op_20implementations_62',['fs/vfs — the VFS facade (public API + per-op implementations)',['../md_src_2fs_2vfs_2README.html',1,'']]],
  ['pull_63',['tpc — Native XRootD third-party-copy (destination-side pull)',['../md_src_2tpc_2README.html',1,'']]],
  ['pull_20socket_64',['gsi — outbound GSI authentication for the TPC pull socket',['../md_src_2tpc_2gsi_2README.html',1,'']]],
  ['pulls_65',['outbound — the blocking source-session client for native TPC pulls',['../md_src_2tpc_2outbound_2README.html',1,'']]],
  ['pwd_20—_20password_20tt_20xrdsecpwd_20tt_20authentication_20for_20the_20tt_20root_3a_20tt_20stream_20protocol_66',['pwd — password (&lt;tt&gt;XrdSecpwd&lt;/tt&gt;) authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol',['../md_src_2auth_2pwd_2README.html',1,'']]]
];
