var searchData=
[
  ['c_20reviewers_0',['nginx idioms for C++ reviewers',['../index.html',1,'']]],
  ['cache_20active_20health_20checks_1',['manager — Cluster / redirector control plane (server registry, redirect cache, active health checks)',['../md_src_2net_2manager_2README.html',1,'']]],
  ['cache_20experimental_20scvmfs_3a_20tls_20variant_2',['cvmfs — the cvmfs:// site cache (+ experimental scvmfs:// TLS variant)',['../md_src_2protocols_2cvmfs_2README.html',1,'']]],
  ['cache_20origin_20tt_20—_20pluggable_20origin_20transports_20for_20the_20read_20through_20cache_3',['&lt;tt&gt;src/fs/cache/origin/&lt;/tt&gt; — pluggable origin transports for the read-through cache',['../md_src_2fs_2cache_2origin_2README.html',1,'']]],
  ['cache_20stage_20decorators_20over_20backends_4',['tier — composable storage tiers (cache/stage decorators over backends)',['../md_src_2fs_2tier_2README.html',1,'']]],
  ['cache_20tt_20—_20xcache_20style_20read_20through_20cache_20and_20write_20through_20origin_20mirroring_5',['&lt;tt&gt;src/fs/cache/&lt;/tt&gt; — XCache-style read-through cache and write-through origin mirroring',['../md_src_2fs_2cache_2README.html',1,'']]],
  ['canonical_20identity_20object_6',['src/core/types — Core type definitions, tunables, and the canonical identity object',['../md_src_2core_2types_2README.html',1,'']]],
  ['certificate_20auth_7',['crypto — shared OpenSSL X.509 / PKI core for GSI and WebDAV certificate auth',['../md_src_2auth_2crypto_2README.html',1,'']]],
  ['certificate_20authentication_8',['gsi — XRootD &lt;tt&gt;kXR_auth&lt;/tt&gt; dispatcher and GSI/x509 proxy-certificate authentication',['../md_src_2auth_2gsi_2README.html',1,'']]],
  ['cfb64_20crc32_9',['sss — Simple Shared Secret authentication (Blowfish-CFB64 + CRC32)',['../md_src_2auth_2sss_2README.html',1,'']]],
  ['chain_20builders_10',['aio — Thread-pool async file I/O and shared response-chain builders',['../md_src_2core_2aio_2README.html',1,'']]],
  ['checks_11',['manager — Cluster / redirector control plane (server registry, redirect cache, active health checks)',['../md_src_2net_2manager_2README.html',1,'']]],
  ['checksums_20paths_20filesystem_20ssrf_12',['compat — Cross-protocol shared primitives (checksums, paths, filesystem, SSRF)',['../md_src_2core_2compat_2README.html',1,'']]],
  ['classifier_13',['net/guard — protocol-agnostic bad-actor classifier',['../md_src_2net_2guard_2README.html',1,'']]],
  ['cli_20tools_14',['&lt;tt&gt;client/apps/&lt;/tt&gt; — native client CLI tools',['../md_client_2apps_2README.html',1,'']]],
  ['client_20apps_20tt_20—_20native_20client_20cli_20tools_15',['&lt;tt&gt;client/apps/&lt;/tt&gt; — native client CLI tools',['../md_client_2apps_2README.html',1,'']]],
  ['client_20for_20native_20tpc_20pulls_16',['outbound — the blocking source-session client for native TPC pulls',['../md_src_2tpc_2outbound_2README.html',1,'']]],
  ['client_20lib_20sec_20tt_20—_20native_20client_20authentication_20modules_17',['&lt;tt&gt;client/lib/sec/&lt;/tt&gt; — native client authentication modules',['../md_client_2lib_2auth_2sec_2README.html',1,'']]],
  ['client_20lib_20tt_20—_20native_20xrootd_20client_20library_20tt_20libbrix_20tt_18',['&lt;tt&gt;client/lib/&lt;/tt&gt; — native XRootD client library (&lt;tt&gt;libbrix&lt;/tt&gt;)',['../md_client_2lib_2README.html',1,'']]],
  ['client_20manager_20side_20server_19',['cms — XRootD CMS cluster membership (heartbeat client + manager-side server)',['../md_src_2net_2cms_2README.html',1,'']]],
  ['client_20manager_20side_20server_20to_20server_20query_20',['upstream — outbound XRootD redirector/proxy client (manager-side server-to-server query)',['../md_src_2net_2upstream_2README.html',1,'']]],
  ['client_20preload_20tt_20—_20ld_5fpreload_20posix_20→_20xrootd_20shim_21',['&lt;tt&gt;client/preload/&lt;/tt&gt; — LD_PRELOAD POSIX → XRootD shim',['../md_client_2preload_2README.html',1,'']]],
  ['client_20tt_20—_20native_20brix_20client_20tools_22',['&lt;tt&gt;client/&lt;/tt&gt; — native BriX client tools',['../md_client_2README.html',1,'']]],
  ['cluster_20membership_20heartbeat_20client_20manager_20side_20server_23',['cms — XRootD CMS cluster membership (heartbeat client + manager-side server)',['../md_src_2net_2cms_2README.html',1,'']]],
  ['cluster_20redirector_20control_20plane_20server_20registry_20redirect_20cache_20active_20health_20checks_24',['manager — Cluster / redirector control plane (server registry, redirect cache, active health checks)',['../md_src_2net_2manager_2README.html',1,'']]],
  ['clustering_20proxying_20shadowing_20and_20connection_20defense_25',['net — clustering, proxying, shadowing, and connection defense',['../md_src_2net_2README.html',1,'']]],
  ['cms_20—_20xrootd_20cms_20cluster_20membership_20heartbeat_20client_20manager_20side_20server_26',['cms — XRootD CMS cluster membership (heartbeat client + manager-side server)',['../md_src_2net_2cms_2README.html',1,'']]],
  ['common_20—_20protocol_20neutral_20third_20party_20copy_20tpc_20core_27',['tpc/common — Protocol-neutral third-party-copy (TPC) core',['../md_src_2tpc_2common_2README.html',1,'']]],
  ['compat_20—_20cross_20protocol_20shared_20primitives_20checksums_20paths_20filesystem_20ssrf_28',['compat — Cross-protocol shared primitives (checksums, paths, filesystem, SSRF)',['../md_src_2core_2compat_2README.html',1,'']]],
  ['compatible_20authorization_20engine_29',['src/auth/authz/acc — XrdAcc-compatible authorization engine',['../md_src_2auth_2authz_2acc_2README.html',1,'']]],
  ['compatible_20rest_20endpoint_20over_20the_20local_20export_20root_30',['s3 — S3-compatible REST endpoint over the local export root',['../md_src_2protocols_2s3_2README.html',1,'']]],
  ['composable_20storage_20tiers_20cache_20stage_20decorators_20over_20backends_31',['tier — composable storage tiers (cache/stage decorators over backends)',['../md_src_2fs_2tier_2README.html',1,'']]],
  ['concurrency_20limiting_20phase_2025_32',['ratelimit — identity-aware leaky-bucket rate, bandwidth &amp; concurrency limiting (Phase 25)',['../md_src_2net_2ratelimit_2README.html',1,'']]],
  ['conditionals_20etag_33',['http — Shared HTTP request/response semantics (headers, body, conditionals, ETag)',['../md_src_2core_2http_2README.html',1,'']]],
  ['config_20—_20directive_20lifecycle_20startup_20validation_20and_20per_20worker_20resource_20init_34',['config — directive lifecycle, startup validation, and per-worker resource init',['../md_src_2core_2config_2README.html',1,'']]],
  ['confined_20local_20filesystem_20copy_20engine_20for_20webdav_20copy_20move_35',['webdav/fs — Confined local-filesystem copy engine for WebDAV COPY/MOVE',['../md_src_2protocols_2webdav_2fs_2README.html',1,'']]],
  ['confinement_20resolution_20acl_20auth_20gating_20and_20access_20logging_36',['path — untrusted-path confinement, resolution, ACL/auth gating, and access logging',['../md_src_2fs_2path_2README.html',1,'']]],
  ['connection_20—_20tcp_20connection_20lifecycle_20framing_20and_20the_20async_20i_20o_20state_20machine_20for_20tt_20root_3a_20tt_37',['connection — TCP connection lifecycle, framing, and the async I/O state machine for &lt;tt&gt;root://&lt;/tt&gt;',['../md_src_2protocols_2root_2connection_2README.html',1,'']]],
  ['connection_20defense_38',['net — clustering, proxying, shadowing, and connection defense',['../md_src_2net_2README.html',1,'']]],
  ['constants_20packed_20structs_39',['protocol — XRootD &lt;tt&gt;root://&lt;/tt&gt; wire-format constants &amp; packed structs',['../md_src_2protocols_2root_2protocol_2README.html',1,'']]],
  ['control_20plane_20destination_20side_40',['engine — native-TPC control plane (destination side)',['../md_src_2tpc_2engine_2README.html',1,'']]],
  ['control_20plane_20server_20registry_20redirect_20cache_20active_20health_20checks_41',['manager — Cluster / redirector control plane (server registry, redirect cache, active health checks)',['../md_src_2net_2manager_2README.html',1,'']]],
  ['copy_20destination_20side_20pull_42',['tpc — Native XRootD third-party-copy (destination-side pull)',['../md_src_2tpc_2README.html',1,'']]],
  ['copy_20engine_20for_20webdav_20copy_20move_43',['webdav/fs — Confined local-filesystem copy engine for WebDAV COPY/MOVE',['../md_src_2protocols_2webdav_2fs_2README.html',1,'']]],
  ['copy_20tpc_20core_44',['tpc/common — Protocol-neutral third-party-copy (TPC) core',['../md_src_2tpc_2common_2README.html',1,'']]],
  ['core_45',['tpc/common — Protocol-neutral third-party-copy (TPC) core',['../md_src_2tpc_2common_2README.html',1,'']]],
  ['core_20—_20platform_20primitives_20shared_20by_20every_20plane_46',['core — platform primitives shared by every plane',['../md_src_2core_2README.html',1,'']]],
  ['core_20—_20the_20shared_20tt_20vfs_20tt_20i_20o_20verb_20layer_47',['src/fs/core — the shared &lt;tt&gt;vfs&lt;/tt&gt; I/O verb layer',['../md_src_2fs_2core_2README.html',1,'']]],
  ['core_20for_20gsi_20and_20webdav_20certificate_20auth_48',['crypto — shared OpenSSL X.509 / PKI core for GSI and WebDAV certificate auth',['../md_src_2auth_2crypto_2README.html',1,'']]],
  ['core_20types_20—_20core_20type_20definitions_20tunables_20and_20the_20canonical_20identity_20object_49',['src/core/types — Core type definitions, tunables, and the canonical identity object',['../md_src_2core_2types_2README.html',1,'']]],
  ['counters_20and_20the_20prometheus_20tt_20metrics_20tt_20exporter_50',['metrics — shared-memory counters and the Prometheus &lt;tt&gt;/metrics&lt;/tt&gt; exporter',['../md_src_2observability_2metrics_2README.html',1,'']]],
  ['crc32_51',['sss — Simple Shared Secret authentication (Blowfish-CFB64 + CRC32)',['../md_src_2auth_2sss_2README.html',1,'']]],
  ['credential_20exchange_52',['S3 STS Credential Exchange',['../md_src_2auth_2s3_2README.html',1,'']]],
  ['cross_20protocol_20helper_20library_20http_20file_20serving_20overflow_20safe_20size_20math_53',['shared — cross-protocol helper library (HTTP file serving + overflow-safe size math)',['../md_src_2protocols_2shared_2README.html',1,'']]],
  ['cross_20protocol_20shared_20primitives_20checksums_20paths_20filesystem_20ssrf_54',['compat — Cross-protocol shared primitives (checksums, paths, filesystem, SSRF)',['../md_src_2core_2compat_2README.html',1,'']]],
  ['cross_20worker_20key_20value_20store_20and_20token_20bucket_20rate_20limiter_20in_20nginx_20shared_20memory_55',['shm — generic cross-worker key/value store and token-bucket rate limiter in nginx shared memory',['../md_src_2core_2shm_2README.html',1,'']]],
  ['cross_20worker_20registry_56',['session — XRootD session lifecycle, identity binding &amp; cross-worker registry',['../md_src_2protocols_2root_2session_2README.html',1,'']]],
  ['crypto_20—_20shared_20openssl_20x_20509_20pki_20core_20for_20gsi_20and_20webdav_20certificate_20auth_57',['crypto — shared OpenSSL X.509 / PKI core for GSI and WebDAV certificate auth',['../md_src_2auth_2crypto_2README.html',1,'']]],
  ['cta_20tape_20service_58',['&lt;tt&gt;src/protocols/ssi/svc_cta/&lt;/tt&gt; — flagship CTA tape service',['../md_src_2protocols_2ssi_2svc__cta_2README.html',1,'']]],
  ['cvmfs_20—_20the_20cvmfs_3a_20site_20cache_20experimental_20scvmfs_3a_20tls_20variant_59',['cvmfs — the cvmfs:// site cache (+ experimental scvmfs:// TLS variant)',['../md_src_2protocols_2cvmfs_2README.html',1,'']]],
  ['cvmfs_3a_20site_20cache_20experimental_20scvmfs_3a_20tls_20variant_60',['cvmfs — the cvmfs:// site cache (+ experimental scvmfs:// TLS variant)',['../md_src_2protocols_2cvmfs_2README.html',1,'']]]
];
