var searchData=
[
  ['rate_20bandwidth_20concurrency_20limiting_20phase_2025_0',['ratelimit — identity-aware leaky-bucket rate, bandwidth &amp; concurrency limiting (Phase 25)',['../md_src_2net_2ratelimit_2README.html',1,'']]],
  ['rate_20limiter_20in_20nginx_20shared_20memory_1',['shm — generic cross-worker key/value store and token-bucket rate limiter in nginx shared memory',['../md_src_2core_2shm_2README.html',1,'']]],
  ['ratelimit_20—_20identity_20aware_20leaky_20bucket_20rate_20bandwidth_20concurrency_20limiting_20phase_2025_2',['ratelimit — identity-aware leaky-bucket rate, bandwidth &amp; concurrency limiting (Phase 25)',['../md_src_2net_2ratelimit_2README.html',1,'']]],
  ['read_20—_20xrootd_20read_20side_20opcodes_20and_20the_20file_20handle_20lifecycle_3',['read — XRootD read-side opcodes and the file-handle lifecycle',['../md_src_2protocols_2root_2read_2README.html',1,'']]],
  ['read_20through_20cache_4',['&lt;tt&gt;src/fs/cache/origin/&lt;/tt&gt; — pluggable origin transports for the read-through cache',['../md_src_2fs_2cache_2origin_2README.html',1,'']]],
  ['read_20through_20cache_20and_20write_20through_20origin_20mirroring_5',['&lt;tt&gt;src/fs/cache/&lt;/tt&gt; — XCache-style read-through cache and write-through origin mirroring',['../md_src_2fs_2cache_2README.html',1,'']]],
  ['redirect_20cache_20active_20health_20checks_6',['manager — Cluster / redirector control plane (server registry, redirect cache, active health checks)',['../md_src_2net_2manager_2README.html',1,'']]],
  ['redirector_20control_20plane_20server_20registry_20redirect_20cache_20active_20health_20checks_7',['manager — Cluster / redirector control plane (server registry, redirect cache, active health checks)',['../md_src_2net_2manager_2README.html',1,'']]],
  ['redirector_20proxy_20client_20manager_20side_20server_20to_20server_20query_8',['upstream — outbound XRootD redirector/proxy client (manager-side server-to-server query)',['../md_src_2net_2upstream_2README.html',1,'']]],
  ['registry_9',['session — XRootD session lifecycle, identity binding &amp; cross-worker registry',['../md_src_2protocols_2root_2session_2README.html',1,'']]],
  ['registry_20redirect_20cache_20active_20health_20checks_10',['manager — Cluster / redirector control plane (server registry, redirect cache, active health checks)',['../md_src_2net_2manager_2README.html',1,'']]],
  ['relay_20—_20transparent_20pass_20through_20relay_20with_20a_20passive_20observation_20tap_11',['relay — transparent pass-through relay with a passive observation tap',['../md_src_2protocols_2root_2relay_2README.html',1,'']]],
  ['remote_20diagnostics_12',['&lt;tt&gt;src/protocols/dig/&lt;/tt&gt; — XrdDig-style remote diagnostics',['../md_src_2protocols_2dig_2README.html',1,'']]],
  ['replay_20for_20xrootd_20and_20webdav_13',['mirror — fire-and-forget traffic mirroring (shadow replay) for XRootD and WebDAV',['../md_src_2net_2mirror_2README.html',1,'']]],
  ['reporting_20srr_20endpoint_14',['&lt;tt&gt;src/protocols/srr/&lt;/tt&gt; — WLCG Storage Resource Reporting (SRR) endpoint',['../md_src_2protocols_2srr_2README.html',1,'']]],
  ['request_20entry_20point_20and_20opcode_20dispatcher_15',['handshake — XRootD stream request entry point and opcode dispatcher',['../md_src_2protocols_2root_2handshake_2README.html',1,'']]],
  ['request_20header_20body_20parsers_16',['webdav/locks — WebDAV LOCK request-header &amp; body parsers',['../md_src_2protocols_2webdav_2locks_2README.html',1,'']]],
  ['request_20response_20semantics_20headers_20body_20conditionals_20etag_17',['http — Shared HTTP request/response semantics (headers, body, conditionals, ETag)',['../md_src_2core_2http_2README.html',1,'']]],
  ['request_20response_20service_20over_20tt_20root_3a_20tt_18',['&lt;tt&gt;src/protocols/ssi/&lt;/tt&gt; — XrdSsi request/response service over &lt;tt&gt;root://&lt;/tt&gt;',['../md_src_2protocols_2ssi_2README.html',1,'']]],
  ['request_20unix_20impersonation_20phase_2040_19',['&lt;tt&gt;src/auth/impersonate/&lt;/tt&gt; — per-request UNIX impersonation (phase 40)',['../md_src_2auth_2impersonate_2README.html',1,'']]],
  ['resolution_20acl_20auth_20gating_20and_20access_20logging_20',['path — untrusted-path confinement, resolution, ACL/auth gating, and access logging',['../md_src_2fs_2path_2README.html',1,'']]],
  ['resource_20init_21',['config — directive lifecycle, startup validation, and per-worker resource init',['../md_src_2core_2config_2README.html',1,'']]],
  ['resource_20reporting_20srr_20endpoint_22',['&lt;tt&gt;src/protocols/srr/&lt;/tt&gt; — WLCG Storage Resource Reporting (SRR) endpoint',['../md_src_2protocols_2srr_2README.html',1,'']]],
  ['response_20—_20xrootd_20wire_20response_20framing_20helpers_23',['response — XRootD wire-response framing helpers',['../md_src_2protocols_2root_2response_2README.html',1,'']]],
  ['response_20chain_20builders_24',['aio — Thread-pool async file I/O and shared response-chain builders',['../md_src_2core_2aio_2README.html',1,'']]],
  ['response_20semantics_20headers_20body_20conditionals_20etag_25',['http — Shared HTTP request/response semantics (headers, body, conditionals, ETag)',['../md_src_2core_2http_2README.html',1,'']]],
  ['response_20service_20over_20tt_20root_3a_20tt_26',['&lt;tt&gt;src/protocols/ssi/&lt;/tt&gt; — XrdSsi request/response service over &lt;tt&gt;root://&lt;/tt&gt;',['../md_src_2protocols_2ssi_2README.html',1,'']]],
  ['rest_20admin_20write_20api_27',['dashboard — live HTTPS transfer monitor + REST admin write API',['../md_src_2observability_2dashboard_2README.html',1,'']]],
  ['rest_20endpoint_20over_20the_20local_20export_20root_28',['s3 — S3-compatible REST endpoint over the local export root',['../md_src_2protocols_2s3_2README.html',1,'']]],
  ['reverse_20proxy_20tt_20brix_5fproxy_20tt_29',['proxy — Transparent XRootD reverse proxy (&lt;tt&gt;brix_proxy&lt;/tt&gt;)',['../md_src_2net_2proxy_2README.html',1,'']]],
  ['reviewers_30',['nginx idioms for C++ reviewers',['../index.html',1,'']]],
  ['root_31',['root',['../md_src_2protocols_2s3_2README.html',1,'s3 — S3-compatible REST endpoint over the local export root'],['../md_src_2protocols_2webdav_2README.html',1,'webdav — HTTP/WebDAV/HTTPS gateway (&lt;tt&gt;davs://&lt;/tt&gt;, &lt;tt&gt;http://&lt;/tt&gt;) over the export root']]],
  ['root_20—_20the_20xrootd_20tt_20root_3a_20tt_20tt_20roots_3a_20tt_20protocol_20plane_32',['root — the XRootD (&lt;tt&gt;root://&lt;/tt&gt; / &lt;tt&gt;roots://&lt;/tt&gt;) protocol plane',['../md_src_2protocols_2root_2README.html',1,'']]],
  ['root_20zip_20—_20zip_20member_20access_20phase_2057_20w2_33',['src/protocols/root/zip — ZIP member access (phase-57 W2)',['../md_src_2protocols_2root_2zip_2README.html',1,'']]],
  ['root_3a_20tt_34',['root: tt',['../md_src_2protocols_2ssi_2README.html',1,'&lt;tt&gt;src/protocols/ssi/&lt;/tt&gt; — XrdSsi request/response service over &lt;tt&gt;root://&lt;/tt&gt;'],['../md_src_2protocols_2root_2connection_2README.html',1,'connection — TCP connection lifecycle, framing, and the async I/O state machine for &lt;tt&gt;root://&lt;/tt&gt;']]],
  ['root_3a_20tt_20stream_20protocol_35',['root: tt stream protocol',['../md_src_2auth_2host_2README.html',1,'host — host-based authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol'],['../md_src_2auth_2krb5_2README.html',1,'krb5 — Kerberos 5 authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol'],['../md_src_2auth_2pwd_2README.html',1,'pwd — password (&lt;tt&gt;XrdSecpwd&lt;/tt&gt;) authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol']]],
  ['root_3a_20tt_20tt_20roots_3a_20tt_20protocol_20plane_36',['root — the XRootD (&lt;tt&gt;root://&lt;/tt&gt; / &lt;tt&gt;roots://&lt;/tt&gt;) protocol plane',['../md_src_2protocols_2root_2README.html',1,'']]],
  ['root_3a_20tt_20wire_20format_20constants_20packed_20structs_37',['protocol — XRootD &lt;tt&gt;root://&lt;/tt&gt; wire-format constants &amp; packed structs',['../md_src_2protocols_2root_2protocol_2README.html',1,'']]],
  ['roots_3a_20tt_20protocol_20plane_38',['root — the XRootD (&lt;tt&gt;root://&lt;/tt&gt; / &lt;tt&gt;roots://&lt;/tt&gt;) protocol plane',['../md_src_2protocols_2root_2README.html',1,'']]],
  ['rules_20authdb_20and_20the_20auth_20gate_39',['authz — path-level authorization: ACL rules, authdb, and the auth gate',['../md_src_2auth_2authz_2README.html',1,'']]]
];
