var searchData=
[
  ['a_20passive_20observation_20tap_0',['relay — transparent pass-through relay with a passive observation tap',['../md_src_2protocols_2root_2relay_2README.html',1,'']]],
  ['acc_20—_20xrdacc_20compatible_20authorization_20engine_1',['src/auth/authz/acc — XrdAcc-compatible authorization engine',['../md_src_2auth_2authz_2acc_2README.html',1,'']]],
  ['accept_20engine_2',['GSI GSSAPI Accept Engine',['../md_src_2auth_2gssapi_2README.html',1,'']]],
  ['access_20logging_3',['access logging',['../md_src_2observability_2accesslog_2README.html',1,'Access Logging'],['../md_src_2fs_2path_2README.html',1,'path — untrusted-path confinement, resolution, ACL/auth gating, and access logging']]],
  ['access_20logs_4',['observability — metrics, packet marking, dashboard, and access logs',['../md_src_2observability_2README.html',1,'']]],
  ['access_20phase_2057_20w2_5',['src/protocols/root/zip — ZIP member access (phase-57 W2)',['../md_src_2protocols_2root_2zip_2README.html',1,'']]],
  ['acl_20auth_20gating_20and_20access_20logging_6',['path — untrusted-path confinement, resolution, ACL/auth gating, and access logging',['../md_src_2fs_2path_2README.html',1,'']]],
  ['acl_20rules_20authdb_20and_20the_20auth_20gate_7',['authz — path-level authorization: ACL rules, authdb, and the auth gate',['../md_src_2auth_2authz_2README.html',1,'']]],
  ['active_20health_20checks_8',['manager — Cluster / redirector control plane (server registry, redirect cache, active health checks)',['../md_src_2net_2manager_2README.html',1,'']]],
  ['actor_20classifier_9',['net/guard — protocol-agnostic bad-actor classifier',['../md_src_2net_2guard_2README.html',1,'']]],
  ['actor_20guard_10',['net/httpguard — HTTP adapter for the bad-actor guard',['../md_src_2net_2httpguard_2README.html',1,'']]],
  ['adapter_20for_20the_20bad_20actor_20guard_11',['net/httpguard — HTTP adapter for the bad-actor guard',['../md_src_2net_2httpguard_2README.html',1,'']]],
  ['admin_20write_20api_12',['dashboard — live HTTPS transfer monitor + REST admin write API',['../md_src_2observability_2dashboard_2README.html',1,'']]],
  ['agnostic_20bad_20actor_20classifier_13',['net/guard — protocol-agnostic bad-actor classifier',['../md_src_2net_2guard_2README.html',1,'']]],
  ['aio_20—_20thread_20pool_20async_20file_20i_20o_20and_20shared_20response_20chain_20builders_14',['aio — Thread-pool async file I/O and shared response-chain builders',['../md_src_2core_2aio_2README.html',1,'']]],
  ['and_20access_20logging_15',['path — untrusted-path confinement, resolution, ACL/auth gating, and access logging',['../md_src_2fs_2path_2README.html',1,'']]],
  ['and_20access_20logs_16',['observability — metrics, packet marking, dashboard, and access logs',['../md_src_2observability_2README.html',1,'']]],
  ['and_20authorization_17',['auth — identity and authorization',['../md_src_2auth_2README.html',1,'']]],
  ['and_20connection_20defense_18',['net — clustering, proxying, shadowing, and connection defense',['../md_src_2net_2README.html',1,'']]],
  ['and_20forget_20traffic_20mirroring_20shadow_20replay_20for_20xrootd_20and_20webdav_19',['mirror — fire-and-forget traffic mirroring (shadow replay) for XRootD and WebDAV',['../md_src_2net_2mirror_2README.html',1,'']]],
  ['and_20gsi_20x509_20proxy_20certificate_20authentication_20',['gsi — XRootD &lt;tt&gt;kXR_auth&lt;/tt&gt; dispatcher and GSI/x509 proxy-certificate authentication',['../md_src_2auth_2gsi_2README.html',1,'']]],
  ['and_20macaroon_20bearer_20token_20validation_21',['token — WLCG/SciToken JWT and macaroon bearer-token validation',['../md_src_2auth_2token_2README.html',1,'']]],
  ['and_20opcode_20dispatcher_22',['handshake — XRootD stream request entry point and opcode dispatcher',['../md_src_2protocols_2root_2handshake_2README.html',1,'']]],
  ['and_20per_20worker_20resource_20init_23',['config — directive lifecycle, startup validation, and per-worker resource init',['../md_src_2core_2config_2README.html',1,'']]],
  ['and_20shared_20response_20chain_20builders_24',['aio — Thread-pool async file I/O and shared response-chain builders',['../md_src_2core_2aio_2README.html',1,'']]],
  ['and_20stat_20formatting_25',['path — wire-path extraction, sanitization, and stat formatting',['../md_src_2protocols_2root_2path_2README.html',1,'']]],
  ['and_20the_20async_20i_20o_20state_20machine_20for_20tt_20root_3a_20tt_26',['connection — TCP connection lifecycle, framing, and the async I/O state machine for &lt;tt&gt;root://&lt;/tt&gt;',['../md_src_2protocols_2root_2connection_2README.html',1,'']]],
  ['and_20the_20auth_20gate_27',['authz — path-level authorization: ACL rules, authdb, and the auth gate',['../md_src_2auth_2authz_2README.html',1,'']]],
  ['and_20the_20canonical_20identity_20object_28',['src/core/types — Core type definitions, tunables, and the canonical identity object',['../md_src_2core_2types_2README.html',1,'']]],
  ['and_20the_20file_20handle_20lifecycle_29',['read — XRootD read-side opcodes and the file-handle lifecycle',['../md_src_2protocols_2root_2read_2README.html',1,'']]],
  ['and_20the_20prometheus_20tt_20metrics_20tt_20exporter_30',['metrics — shared-memory counters and the Prometheus &lt;tt&gt;/metrics&lt;/tt&gt; exporter',['../md_src_2observability_2metrics_2README.html',1,'']]],
  ['and_20token_20bucket_20rate_20limiter_20in_20nginx_20shared_20memory_31',['shm — generic cross-worker key/value store and token-bucket rate limiter in nginx shared memory',['../md_src_2core_2shm_2README.html',1,'']]],
  ['and_20tt_20kxr_5fset_20tt_20hints_32',['query — XRootD &lt;tt&gt;kXR_query&lt;/tt&gt; sub-protocol, &lt;tt&gt;kXR_prepare&lt;/tt&gt; staging, and &lt;tt&gt;kXR_set&lt;/tt&gt; hints',['../md_src_2protocols_2root_2query_2README.html',1,'']]],
  ['and_20webdav_20certificate_20auth_33',['crypto — shared OpenSSL X.509 / PKI core for GSI and WebDAV certificate auth',['../md_src_2auth_2crypto_2README.html',1,'']]],
  ['and_20write_20through_20origin_20mirroring_34',['&lt;tt&gt;src/fs/cache/&lt;/tt&gt; — XCache-style read-through cache and write-through origin mirroring',['../md_src_2fs_2cache_2README.html',1,'']]],
  ['and_20xml_20escaping_20helpers_35',['webdav/util — WebDAV URI decoding and XML escaping helpers',['../md_src_2protocols_2webdav_2util_2README.html',1,'']]],
  ['api_36',['dashboard — live HTTPS transfer monitor + REST admin write API',['../md_src_2observability_2dashboard_2README.html',1,'']]],
  ['api_20per_20op_20implementations_37',['fs/vfs — the VFS facade (public API + per-op implementations)',['../md_src_2fs_2vfs_2README.html',1,'']]],
  ['apps_20tt_20—_20native_20client_20cli_20tools_38',['&lt;tt&gt;client/apps/&lt;/tt&gt; — native client CLI tools',['../md_client_2apps_2README.html',1,'']]],
  ['async_20file_20i_20o_20and_20shared_20response_20chain_20builders_39',['aio — Thread-pool async file I/O and shared response-chain builders',['../md_src_2core_2aio_2README.html',1,'']]],
  ['async_20i_20o_20state_20machine_20for_20tt_20root_3a_20tt_40',['connection — TCP connection lifecycle, framing, and the async I/O state machine for &lt;tt&gt;root://&lt;/tt&gt;',['../md_src_2protocols_2root_2connection_2README.html',1,'']]],
  ['attribute_20operations_41',['fattr — XRootD &lt;tt&gt;kXR_fattr&lt;/tt&gt; extended-attribute operations',['../md_src_2protocols_2root_2fattr_2README.html',1,'']]],
  ['auth_42',['crypto — shared OpenSSL X.509 / PKI core for GSI and WebDAV certificate auth',['../md_src_2auth_2crypto_2README.html',1,'']]],
  ['auth_20—_20identity_20and_20authorization_43',['auth — identity and authorization',['../md_src_2auth_2README.html',1,'']]],
  ['auth_20authz_20acc_20—_20xrdacc_20compatible_20authorization_20engine_44',['src/auth/authz/acc — XrdAcc-compatible authorization engine',['../md_src_2auth_2authz_2acc_2README.html',1,'']]],
  ['auth_20gate_45',['authz — path-level authorization: ACL rules, authdb, and the auth gate',['../md_src_2auth_2authz_2README.html',1,'']]],
  ['auth_20gating_20and_20access_20logging_46',['path — untrusted-path confinement, resolution, ACL/auth gating, and access logging',['../md_src_2fs_2path_2README.html',1,'']]],
  ['auth_20impersonate_20tt_20—_20per_20request_20unix_20impersonation_20phase_2040_47',['&lt;tt&gt;src/auth/impersonate/&lt;/tt&gt; — per-request UNIX impersonation (phase 40)',['../md_src_2auth_2impersonate_2README.html',1,'']]],
  ['authdb_20and_20the_20auth_20gate_48',['authz — path-level authorization: ACL rules, authdb, and the auth gate',['../md_src_2auth_2authz_2README.html',1,'']]],
  ['authentication_49',['gsi — XRootD &lt;tt&gt;kXR_auth&lt;/tt&gt; dispatcher and GSI/x509 proxy-certificate authentication',['../md_src_2auth_2gsi_2README.html',1,'']]],
  ['authentication_20blowfish_20cfb64_20crc32_50',['sss — Simple Shared Secret authentication (Blowfish-CFB64 + CRC32)',['../md_src_2auth_2sss_2README.html',1,'']]],
  ['authentication_20for_20the_20tpc_20pull_20socket_51',['gsi — outbound GSI authentication for the TPC pull socket',['../md_src_2tpc_2gsi_2README.html',1,'']]],
  ['authentication_20for_20the_20tt_20root_3a_20tt_20stream_20protocol_52',['authentication for the tt root: tt stream protocol',['../md_src_2auth_2host_2README.html',1,'host — host-based authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol'],['../md_src_2auth_2krb5_2README.html',1,'krb5 — Kerberos 5 authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol'],['../md_src_2auth_2pwd_2README.html',1,'pwd — password (&lt;tt&gt;XrdSecpwd&lt;/tt&gt;) authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol']]],
  ['authentication_20handler_53',['unix — XRootD &lt;tt&gt;unix&lt;/tt&gt; (UNIX-name) authentication handler',['../md_src_2auth_2unix_2README.html',1,'']]],
  ['authentication_20modules_54',['&lt;tt&gt;client/lib/sec/&lt;/tt&gt; — native client authentication modules',['../md_client_2lib_2auth_2sec_2README.html',1,'']]],
  ['authorization_55',['auth — identity and authorization',['../md_src_2auth_2README.html',1,'']]],
  ['authorization_20engine_56',['src/auth/authz/acc — XrdAcc-compatible authorization engine',['../md_src_2auth_2authz_2acc_2README.html',1,'']]],
  ['authorization_3a_20acl_20rules_20authdb_20and_20the_20auth_20gate_57',['authz — path-level authorization: ACL rules, authdb, and the auth gate',['../md_src_2auth_2authz_2README.html',1,'']]],
  ['authz_20—_20path_20level_20authorization_3a_20acl_20rules_20authdb_20and_20the_20auth_20gate_58',['authz — path-level authorization: ACL rules, authdb, and the auth gate',['../md_src_2auth_2authz_2README.html',1,'']]],
  ['authz_20acc_20—_20xrdacc_20compatible_20authorization_20engine_59',['src/auth/authz/acc — XrdAcc-compatible authorization engine',['../md_src_2auth_2authz_2acc_2README.html',1,'']]],
  ['aware_20leaky_20bucket_20rate_20bandwidth_20concurrency_20limiting_20phase_2025_60',['ratelimit — identity-aware leaky-bucket rate, bandwidth &amp; concurrency limiting (Phase 25)',['../md_src_2net_2ratelimit_2README.html',1,'']]]
];
