var searchData=
[
  ['s3_20—_20s3_20compatible_20rest_20endpoint_20over_20the_20local_20export_20root_0',['s3 — S3-compatible REST endpoint over the local export root',['../md_src_2protocols_2s3_2README.html',1,'']]],
  ['safe_20size_20math_1',['shared — cross-protocol helper library (HTTP file serving + overflow-safe size math)',['../md_src_2protocols_2shared_2README.html',1,'']]],
  ['sanitization_20and_20stat_20formatting_2',['path — wire-path extraction, sanitization, and stat formatting',['../md_src_2protocols_2root_2path_2README.html',1,'']]],
  ['scan_20tt_20—_20bulk_20storage_20scan_20verify_20inventory_20engine_3',['&lt;tt&gt;src/fs/scan/&lt;/tt&gt; — bulk storage scan / verify / inventory engine',['../md_src_2fs_2scan_2README.html',1,'']]],
  ['scitags_20packet_20marking_4',['pmark — SciTags packet marking',['../md_src_2observability_2pmark_2README.html',1,'']]],
  ['scitoken_20jwt_20and_20macaroon_20bearer_20token_20validation_5',['token — WLCG/SciToken JWT and macaroon bearer-token validation',['../md_src_2auth_2token_2README.html',1,'']]],
  ['scvmfs_3a_20tls_20variant_6',['cvmfs — the cvmfs:// site cache (+ experimental scvmfs:// TLS variant)',['../md_src_2protocols_2cvmfs_2README.html',1,'']]],
  ['sd_20layer_7',['fs/backend — Storage Driver (SD) layer',['../md_src_2fs_2backend_2README.html',1,'']]],
  ['sec_20tt_20—_20native_20client_20authentication_20modules_8',['&lt;tt&gt;client/lib/sec/&lt;/tt&gt; — native client authentication modules',['../md_client_2lib_2auth_2sec_2README.html',1,'']]],
  ['secret_20authentication_20blowfish_20cfb64_20crc32_9',['sss — Simple Shared Secret authentication (Blowfish-CFB64 + CRC32)',['../md_src_2auth_2sss_2README.html',1,'']]],
  ['semantics_20headers_20body_20conditionals_20etag_10',['http — Shared HTTP request/response semantics (headers, body, conditionals, ETag)',['../md_src_2core_2http_2README.html',1,'']]],
  ['server_11',['cms — XRootD CMS cluster membership (heartbeat client + manager-side server)',['../md_src_2net_2cms_2README.html',1,'']]],
  ['server_20registry_20redirect_20cache_20active_20health_20checks_12',['manager — Cluster / redirector control plane (server registry, redirect cache, active health checks)',['../md_src_2net_2manager_2README.html',1,'']]],
  ['server_20to_20server_20query_13',['upstream — outbound XRootD redirector/proxy client (manager-side server-to-server query)',['../md_src_2net_2upstream_2README.html',1,'']]],
  ['service_14',['&lt;tt&gt;src/protocols/ssi/svc_cta/&lt;/tt&gt; — flagship CTA tape service',['../md_src_2protocols_2ssi_2svc__cta_2README.html',1,'']]],
  ['service_20over_20tt_20root_3a_20tt_15',['&lt;tt&gt;src/protocols/ssi/&lt;/tt&gt; — XrdSsi request/response service over &lt;tt&gt;root://&lt;/tt&gt;',['../md_src_2protocols_2ssi_2README.html',1,'']]],
  ['serving_20overflow_20safe_20size_20math_16',['shared — cross-protocol helper library (HTTP file serving + overflow-safe size math)',['../md_src_2protocols_2shared_2README.html',1,'']]],
  ['session_20—_20xrootd_20session_20lifecycle_20identity_20binding_20cross_20worker_20registry_17',['session — XRootD session lifecycle, identity binding &amp; cross-worker registry',['../md_src_2protocols_2root_2session_2README.html',1,'']]],
  ['session_20client_20for_20native_20tpc_20pulls_18',['outbound — the blocking source-session client for native TPC pulls',['../md_src_2tpc_2outbound_2README.html',1,'']]],
  ['session_20lifecycle_20logging_19',['Session Lifecycle Logging',['../md_src_2observability_2sesslog_2README.html',1,'']]],
  ['shadow_20replay_20for_20xrootd_20and_20webdav_20',['mirror — fire-and-forget traffic mirroring (shadow replay) for XRootD and WebDAV',['../md_src_2net_2mirror_2README.html',1,'']]],
  ['shadowing_20and_20connection_20defense_21',['net — clustering, proxying, shadowing, and connection defense',['../md_src_2net_2README.html',1,'']]],
  ['shared_20—_20cross_20protocol_20helper_20library_20http_20file_20serving_20overflow_20safe_20size_20math_22',['shared — cross-protocol helper library (HTTP file serving + overflow-safe size math)',['../md_src_2protocols_2shared_2README.html',1,'']]],
  ['shared_20by_20every_20plane_23',['core — platform primitives shared by every plane',['../md_src_2core_2README.html',1,'']]],
  ['shared_20http_20request_20response_20semantics_20headers_20body_20conditionals_20etag_24',['http — Shared HTTP request/response semantics (headers, body, conditionals, ETag)',['../md_src_2core_2http_2README.html',1,'']]],
  ['shared_20memory_25',['shm — generic cross-worker key/value store and token-bucket rate limiter in nginx shared memory',['../md_src_2core_2shm_2README.html',1,'']]],
  ['shared_20memory_20counters_20and_20the_20prometheus_20tt_20metrics_20tt_20exporter_26',['metrics — shared-memory counters and the Prometheus &lt;tt&gt;/metrics&lt;/tt&gt; exporter',['../md_src_2observability_2metrics_2README.html',1,'']]],
  ['shared_20openssl_20x_20509_20pki_20core_20for_20gsi_20and_20webdav_20certificate_20auth_27',['crypto — shared OpenSSL X.509 / PKI core for GSI and WebDAV certificate auth',['../md_src_2auth_2crypto_2README.html',1,'']]],
  ['shared_20primitives_20checksums_20paths_20filesystem_20ssrf_28',['compat — Cross-protocol shared primitives (checksums, paths, filesystem, SSRF)',['../md_src_2core_2compat_2README.html',1,'']]],
  ['shared_20response_20chain_20builders_29',['aio — Thread-pool async file I/O and shared response-chain builders',['../md_src_2core_2aio_2README.html',1,'']]],
  ['shared_20secret_20authentication_20blowfish_20cfb64_20crc32_30',['sss — Simple Shared Secret authentication (Blowfish-CFB64 + CRC32)',['../md_src_2auth_2sss_2README.html',1,'']]],
  ['shared_20tt_20vfs_20tt_20i_20o_20verb_20layer_31',['src/fs/core — the shared &lt;tt&gt;vfs&lt;/tt&gt; I/O verb layer',['../md_src_2fs_2core_2README.html',1,'']]],
  ['shim_32',['&lt;tt&gt;client/preload/&lt;/tt&gt; — LD_PRELOAD POSIX → XRootD shim',['../md_client_2preload_2README.html',1,'']]],
  ['shm_20—_20generic_20cross_20worker_20key_20value_20store_20and_20token_20bucket_20rate_20limiter_20in_20nginx_20shared_20memory_33',['shm — generic cross-worker key/value store and token-bucket rate limiter in nginx shared memory',['../md_src_2core_2shm_2README.html',1,'']]],
  ['side_34',['engine — native-TPC control plane (destination side)',['../md_src_2tpc_2engine_2README.html',1,'']]],
  ['side_20opcodes_20and_20the_20file_20handle_20lifecycle_35',['read — XRootD read-side opcodes and the file-handle lifecycle',['../md_src_2protocols_2root_2read_2README.html',1,'']]],
  ['side_20pull_36',['tpc — Native XRootD third-party-copy (destination-side pull)',['../md_src_2tpc_2README.html',1,'']]],
  ['side_20server_37',['cms — XRootD CMS cluster membership (heartbeat client + manager-side server)',['../md_src_2net_2cms_2README.html',1,'']]],
  ['side_20server_20to_20server_20query_38',['upstream — outbound XRootD redirector/proxy client (manager-side server-to-server query)',['../md_src_2net_2upstream_2README.html',1,'']]],
  ['sidecar_20xmeta_39',['meta — unified per-file metadata sidecar (xmeta)',['../md_src_2fs_2meta_2README.html',1,'']]],
  ['simple_20shared_20secret_20authentication_20blowfish_20cfb64_20crc32_40',['sss — Simple Shared Secret authentication (Blowfish-CFB64 + CRC32)',['../md_src_2auth_2sss_2README.html',1,'']]],
  ['single_20port_20protocol_20handoff_20for_20the_20stream_20xrootd_20listener_41',['handoff — single-port protocol handoff for the stream xrootd listener',['../md_src_2protocols_2root_2handoff_2README.html',1,'']]],
  ['single_20posix_20filesystem_20data_20plane_42',['fs — Unified VFS: the single POSIX-filesystem data plane',['../md_src_2fs_2README.html',1,'']]],
  ['sink_20fan_20out_43',['tap — ngx-free protocol observation tap (decode + sink fan-out)',['../md_src_2net_2tap_2README.html',1,'']]],
  ['site_20cache_20experimental_20scvmfs_3a_20tls_20variant_44',['cvmfs — the cvmfs:// site cache (+ experimental scvmfs:// TLS variant)',['../md_src_2protocols_2cvmfs_2README.html',1,'']]],
  ['size_20math_45',['shared — cross-protocol helper library (HTTP file serving + overflow-safe size math)',['../md_src_2protocols_2shared_2README.html',1,'']]],
  ['socket_46',['gsi — outbound GSI authentication for the TPC pull socket',['../md_src_2tpc_2gsi_2README.html',1,'']]],
  ['source_20session_20client_20for_20native_20tpc_20pulls_47',['outbound — the blocking source-session client for native TPC pulls',['../md_src_2tpc_2outbound_2README.html',1,'']]],
  ['source_20tree_48',['src — nginx-xrootd Source Tree',['../md_src_2README.html',1,'']]],
  ['src_20—_20nginx_20xrootd_20source_20tree_49',['src — nginx-xrootd Source Tree',['../md_src_2README.html',1,'']]],
  ['src_20auth_20authz_20acc_20—_20xrdacc_20compatible_20authorization_20engine_50',['src/auth/authz/acc — XrdAcc-compatible authorization engine',['../md_src_2auth_2authz_2acc_2README.html',1,'']]],
  ['src_20auth_20impersonate_20tt_20—_20per_20request_20unix_20impersonation_20phase_2040_51',['&lt;tt&gt;src/auth/impersonate/&lt;/tt&gt; — per-request UNIX impersonation (phase 40)',['../md_src_2auth_2impersonate_2README.html',1,'']]],
  ['src_20core_20types_20—_20core_20type_20definitions_20tunables_20and_20the_20canonical_20identity_20object_52',['src/core/types — Core type definitions, tunables, and the canonical identity object',['../md_src_2core_2types_2README.html',1,'']]],
  ['src_20fs_20cache_20origin_20tt_20—_20pluggable_20origin_20transports_20for_20the_20read_20through_20cache_53',['&lt;tt&gt;src/fs/cache/origin/&lt;/tt&gt; — pluggable origin transports for the read-through cache',['../md_src_2fs_2cache_2origin_2README.html',1,'']]],
  ['src_20fs_20cache_20tt_20—_20xcache_20style_20read_20through_20cache_20and_20write_20through_20origin_20mirroring_54',['&lt;tt&gt;src/fs/cache/&lt;/tt&gt; — XCache-style read-through cache and write-through origin mirroring',['../md_src_2fs_2cache_2README.html',1,'']]],
  ['src_20fs_20core_20—_20the_20shared_20tt_20vfs_20tt_20i_20o_20verb_20layer_55',['src/fs/core — the shared &lt;tt&gt;vfs&lt;/tt&gt; I/O verb layer',['../md_src_2fs_2core_2README.html',1,'']]],
  ['src_20fs_20scan_20tt_20—_20bulk_20storage_20scan_20verify_20inventory_20engine_56',['&lt;tt&gt;src/fs/scan/&lt;/tt&gt; — bulk storage scan / verify / inventory engine',['../md_src_2fs_2scan_2README.html',1,'']]],
  ['src_20fs_20xfer_20tt_20—_20unified_20durable_20transfer_20engine_57',['&lt;tt&gt;src/fs/xfer/&lt;/tt&gt; — unified durable-transfer engine',['../md_src_2fs_2xfer_2README.html',1,'']]],
  ['src_20protocols_20dig_20tt_20—_20xrddig_20style_20remote_20diagnostics_58',['&lt;tt&gt;src/protocols/dig/&lt;/tt&gt; — XrdDig-style remote diagnostics',['../md_src_2protocols_2dig_2README.html',1,'']]],
  ['src_20protocols_20root_20zip_20—_20zip_20member_20access_20phase_2057_20w2_59',['src/protocols/root/zip — ZIP member access (phase-57 W2)',['../md_src_2protocols_2root_2zip_2README.html',1,'']]],
  ['src_20protocols_20srr_20tt_20—_20wlcg_20storage_20resource_20reporting_20srr_20endpoint_60',['&lt;tt&gt;src/protocols/srr/&lt;/tt&gt; — WLCG Storage Resource Reporting (SRR) endpoint',['../md_src_2protocols_2srr_2README.html',1,'']]],
  ['src_20protocols_20ssi_20svc_5fcta_20tt_20—_20flagship_20cta_20tape_20service_61',['&lt;tt&gt;src/protocols/ssi/svc_cta/&lt;/tt&gt; — flagship CTA tape service',['../md_src_2protocols_2ssi_2svc__cta_2README.html',1,'']]],
  ['src_20protocols_20ssi_20tt_20—_20xrdssi_20request_20response_20service_20over_20tt_20root_3a_20tt_62',['&lt;tt&gt;src/protocols/ssi/&lt;/tt&gt; — XrdSsi request/response service over &lt;tt&gt;root://&lt;/tt&gt;',['../md_src_2protocols_2ssi_2README.html',1,'']]],
  ['srr_20tt_20—_20wlcg_20storage_20resource_20reporting_20srr_20endpoint_63',['&lt;tt&gt;src/protocols/srr/&lt;/tt&gt; — WLCG Storage Resource Reporting (SRR) endpoint',['../md_src_2protocols_2srr_2README.html',1,'']]],
  ['ssi_20svc_5fcta_20tt_20—_20flagship_20cta_20tape_20service_64',['&lt;tt&gt;src/protocols/ssi/svc_cta/&lt;/tt&gt; — flagship CTA tape service',['../md_src_2protocols_2ssi_2svc__cta_2README.html',1,'']]],
  ['ssi_20tt_20—_20xrdssi_20request_20response_20service_20over_20tt_20root_3a_20tt_65',['&lt;tt&gt;src/protocols/ssi/&lt;/tt&gt; — XrdSsi request/response service over &lt;tt&gt;root://&lt;/tt&gt;',['../md_src_2protocols_2ssi_2README.html',1,'']]],
  ['ssrf_66',['compat — Cross-protocol shared primitives (checksums, paths, filesystem, SSRF)',['../md_src_2core_2compat_2README.html',1,'']]],
  ['sss_20—_20simple_20shared_20secret_20authentication_20blowfish_20cfb64_20crc32_67',['sss — Simple Shared Secret authentication (Blowfish-CFB64 + CRC32)',['../md_src_2auth_2sss_2README.html',1,'']]],
  ['stage_20decorators_20over_20backends_68',['tier — composable storage tiers (cache/stage decorators over backends)',['../md_src_2fs_2tier_2README.html',1,'']]],
  ['staging_20and_20tt_20kxr_5fset_20tt_20hints_69',['query — XRootD &lt;tt&gt;kXR_query&lt;/tt&gt; sub-protocol, &lt;tt&gt;kXR_prepare&lt;/tt&gt; staging, and &lt;tt&gt;kXR_set&lt;/tt&gt; hints',['../md_src_2protocols_2root_2query_2README.html',1,'']]],
  ['startup_20validation_20and_20per_20worker_20resource_20init_70',['config — directive lifecycle, startup validation, and per-worker resource init',['../md_src_2core_2config_2README.html',1,'']]],
  ['stat_20formatting_71',['path — wire-path extraction, sanitization, and stat formatting',['../md_src_2protocols_2root_2path_2README.html',1,'']]],
  ['state_20machine_20for_20tt_20root_3a_20tt_72',['connection — TCP connection lifecycle, framing, and the async I/O state machine for &lt;tt&gt;root://&lt;/tt&gt;',['../md_src_2protocols_2root_2connection_2README.html',1,'']]],
  ['storage_20driver_20sd_20layer_73',['fs/backend — Storage Driver (SD) layer',['../md_src_2fs_2backend_2README.html',1,'']]],
  ['storage_20resource_20reporting_20srr_20endpoint_74',['&lt;tt&gt;src/protocols/srr/&lt;/tt&gt; — WLCG Storage Resource Reporting (SRR) endpoint',['../md_src_2protocols_2srr_2README.html',1,'']]],
  ['storage_20scan_20verify_20inventory_20engine_75',['&lt;tt&gt;src/fs/scan/&lt;/tt&gt; — bulk storage scan / verify / inventory engine',['../md_src_2fs_2scan_2README.html',1,'']]],
  ['storage_20tiers_20cache_20stage_20decorators_20over_20backends_76',['tier — composable storage tiers (cache/stage decorators over backends)',['../md_src_2fs_2tier_2README.html',1,'']]],
  ['store_20and_20token_20bucket_20rate_20limiter_20in_20nginx_20shared_20memory_77',['shm — generic cross-worker key/value store and token-bucket rate limiter in nginx shared memory',['../md_src_2core_2shm_2README.html',1,'']]],
  ['stream_20—_20tt_20ngx_5fstream_5fbrix_5fmodule_20tt_20descriptor_20directive_20table_78',['stream — &lt;tt&gt;ngx_stream_brix_module&lt;/tt&gt; descriptor &amp; directive table',['../md_src_2protocols_2root_2stream_2README.html',1,'']]],
  ['stream_20protocol_79',['stream protocol',['../md_src_2protocols_2root_2dirlist_2README.html',1,'dirlist — XRootD &lt;tt&gt;kXR_dirlist&lt;/tt&gt; directory enumeration (stream protocol)'],['../md_src_2auth_2host_2README.html',1,'host — host-based authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol'],['../md_src_2auth_2krb5_2README.html',1,'krb5 — Kerberos 5 authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol'],['../md_src_2auth_2pwd_2README.html',1,'pwd — password (&lt;tt&gt;XrdSecpwd&lt;/tt&gt;) authentication for the &lt;tt&gt;root://&lt;/tt&gt; stream protocol']]],
  ['stream_20request_20entry_20point_20and_20opcode_20dispatcher_80',['handshake — XRootD stream request entry point and opcode dispatcher',['../md_src_2protocols_2root_2handshake_2README.html',1,'']]],
  ['stream_20write_20path_81',['write — XRootD mutating-opcode handlers (the stream write path)',['../md_src_2protocols_2root_2write_2README.html',1,'']]],
  ['stream_20xrootd_20listener_82',['handoff — single-port protocol handoff for the stream xrootd listener',['../md_src_2protocols_2root_2handoff_2README.html',1,'']]],
  ['structs_83',['protocol — XRootD &lt;tt&gt;root://&lt;/tt&gt; wire-format constants &amp; packed structs',['../md_src_2protocols_2root_2protocol_2README.html',1,'']]],
  ['style_20read_20through_20cache_20and_20write_20through_20origin_20mirroring_84',['&lt;tt&gt;src/fs/cache/&lt;/tt&gt; — XCache-style read-through cache and write-through origin mirroring',['../md_src_2fs_2cache_2README.html',1,'']]],
  ['style_20remote_20diagnostics_85',['&lt;tt&gt;src/protocols/dig/&lt;/tt&gt; — XrdDig-style remote diagnostics',['../md_src_2protocols_2dig_2README.html',1,'']]],
  ['sub_20protocol_20tt_20kxr_5fprepare_20tt_20staging_20and_20tt_20kxr_5fset_20tt_20hints_86',['query — XRootD &lt;tt&gt;kXR_query&lt;/tt&gt; sub-protocol, &lt;tt&gt;kXR_prepare&lt;/tt&gt; staging, and &lt;tt&gt;kXR_set&lt;/tt&gt; hints',['../md_src_2protocols_2root_2query_2README.html',1,'']]],
  ['subdirectory_20per_20wire_20protocol_87',['protocols — one subdirectory per wire protocol',['../md_src_2protocols_2README.html',1,'']]],
  ['svc_5fcta_20tt_20—_20flagship_20cta_20tape_20service_88',['&lt;tt&gt;src/protocols/ssi/svc_cta/&lt;/tt&gt; — flagship CTA tape service',['../md_src_2protocols_2ssi_2svc__cta_2README.html',1,'']]]
];
