#!/usr/bin/env python3
"""Generate a short-lived WLCG-compatible JWT bearer token for integration testing.

The signing key must be the RSA private key whose public half was registered as
the JWKS endpoint (generated by pki-scripts/generate-jwt-keys.py).

Usage:
    xrd-gen-token --key /etc/xrootd-client/jwt-signing-key.pem \\
                  --issuer https://test.xrootd.local \\
                  --audience xrootd-test \\
                  --scope "storage.read:/ storage.write:/" \\
                  [--subject testuser] \\
                  [--lifetime-minutes 60] \\
                  [--out /tmp/xrd-token.txt]

Outputs the raw JWT to stdout (and optionally to --out file).

Environment variable XRD_BEARER_TOKEN is also set when --export is given, but
since this script runs in a subprocess you must source the eval output:
    eval "$(xrd-gen-token --export ...)"
"""
import argparse
import base64
import json
import os
import sys
import time
from pathlib import Path

try:
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import padding
    from cryptography.hazmat.backends import default_backend
except ImportError:
    print("ERROR: cryptography library required — pip3 install cryptography", file=sys.stderr)
    sys.exit(1)


def b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def sign_jwt(private_key, header: dict, payload: dict) -> str:
    h = b64url(json.dumps(header, separators=(",", ":")).encode())
    p = b64url(json.dumps(payload, separators=(",", ":")).encode())
    signing_input = f"{h}.{p}".encode()
    signature = private_key.sign(signing_input, padding.PKCS1v15(), hashes.SHA256())
    return f"{h}.{p}.{b64url(signature)}"


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--key", default="/etc/xrootd-client/jwt-signing-key.pem",
                    help="RSA private key PEM file used to sign the token")
    ap.add_argument("--kid", default="test-key-1", help="Key ID to embed in the JWT header")
    ap.add_argument("--issuer", default="https://test.xrootd.local")
    ap.add_argument("--audience", default="xrootd-test")
    ap.add_argument("--subject", default="testuser")
    ap.add_argument("--scope", default="storage.read:/ storage.write:/",
                    help="Space-separated list of storage scopes")
    ap.add_argument("--lifetime-minutes", type=int, default=60)
    ap.add_argument("--groups", default="/test-vo", help="wlcg.groups claim value (space-separated)")
    ap.add_argument("--out", help="Write token to this file in addition to stdout")
    ap.add_argument("--export", action="store_true",
                    help="Print 'export BEARER_TOKEN=…' so the caller can eval it")
    return ap.parse_args()


def main() -> None:
    args = parse_args()

    key_path = Path(args.key)
    if not key_path.exists():
        print(f"ERROR: signing key not found at {key_path}", file=sys.stderr)
        sys.exit(1)

    with key_path.open("rb") as fh:
        private_key = serialization.load_pem_private_key(
            fh.read(), password=None, backend=default_backend()
        )

    now = int(time.time())
    payload = {
        "iss": args.issuer,
        "sub": args.subject,
        "aud": args.audience,
        "iat": now,
        "nbf": now - 5,
        "exp": now + args.lifetime_minutes * 60,
        "scope": args.scope,
        "wlcg.ver": "1.0",
        "wlcg.groups": args.groups.split(),
    }
    header = {"alg": "RS256", "typ": "JWT", "kid": args.kid}

    token = sign_jwt(private_key, header, payload)

    print(token)
    if args.out:
        Path(args.out).write_text(token + "\n")
    if args.export:
        print(f"export BEARER_TOKEN={token}")


if __name__ == "__main__":
    main()
