apiVersion: v1
kind: Service
metadata:
  name: xrootd-reference
  namespace: xrootd-integration
  labels:
    app.kubernetes.io/name: xrootd-reference
    app.kubernetes.io/component: server
spec:
  selector:
    app.kubernetes.io/name: xrootd-reference
  type: ClusterIP
  ports:
    - name: xrootd
      port: 1094
      targetPort: 1094
      protocol: TCP
    - name: xrootd-tls
      port: 1095
      targetPort: 1095
      nodePort: 31095
    ---
    # NodePort service for direct access from the host when using minikube.
    apiVersion: v1

kind: Service
metadata:
  name: xrootd-reference-nodeport
  namespace: xrootd-integration
  labels:
    app.kubernetes.io/name: xrootd-reference
    app.kubernetes.io/component: server-nodeport
spec:
  selector:
    app.kubernetes.io/name: xrootd-reference
  type: NodePort
  ports:
    - name: xrootd
      port: 1094
      targetPort: 1094
      nodePort: 31094
      protocol: TCP
