"""Calibrated catalogue snapshot: label-key schema per family.

Generated from a live matrix-stack scrape (scratchpad/gen_catalog_data.py).
CONDITIONAL lists the traffic-gated families whose sample rows appear
only once their subsystem is exercised (cvmfs, VOMS, cache-enabled
planes, authenticated identities); their key sets are pinned from the
C emitters and verified whenever rows do materialize.
"""

LABEL_KEYS = {
    'brix_acc_dns_breaker_open_total': (),
    'brix_acc_nss_breaker_open_total': (),
    'brix_auth_l1_hits_total': (),
    'brix_auth_l1_misses_total': (),
    'brix_auth_total': ('method', 'proto', 'status'),
    'brix_budget_waits_total': ('auth', 'port'),
    'brix_bytes_rx_ipv4_total': ('auth', 'port'),
    'brix_bytes_rx_ipv6_total': ('auth', 'port'),
    'brix_bytes_tx_ipv4_total': ('auth', 'port'),
    'brix_bytes_tx_ipv6_total': ('auth', 'port'),
    'brix_cache_bytes': ('auth', 'port', 'state'),
    'brix_cache_bytes_evicted_total': ('proto',),
    'brix_cache_dirty_reaped_total': ('auth', 'port', 'reason'),
    'brix_cache_evicted_bytes_total': ('auth', 'port'),
    'brix_cache_eviction_errors_total': ('auth', 'port'),
    'brix_cache_eviction_threshold_ratio': ('auth', 'port'),
    'brix_cache_evictions_total': ('auth', 'port'),
    'brix_cache_requests_total': ('cache_status', 'proto'),
    'brix_cache_occupancy_ratio': ('auth', 'port'),
    'brix_cache_prefetch_blocks_total': (),
    'brix_cache_prefetch_failures_total': (),
    'brix_cache_prefetch_jobs_total': (),
    'brix_cache_usage_ratio': (),
    'brix_cache_watermark_evicted_bytes_total': (),
    'brix_cache_watermark_evicted_files_total': (),
    'brix_cache_watermark_purges_total': (),
    'brix_cluster_servers_registered': (),
    'brix_cms_cap_rejections_total': (),
    'brix_cms_frame_yields_total': (),
    'brix_cms_idle_closes_total': (),
    'brix_cms_login_timeouts_total': (),
    'brix_cms_logins_total': (),
    'brix_cms_connect_failures_total': (),
    'brix_cms_registered_links': (),
    'brix_cms_read_timeouts_total': (),
    'brix_config_generation': (),
    'brix_connections_active': ('auth', 'port'),
    'brix_connections_total': ('auth', 'port'),
    'brix_cred_deleg_fail_total': ('proto', 'reason'),
    'brix_cred_deleg_total': ('mode', 'outcome', 'proto'),
    'brix_cred_select_deny_total': ('proto',),
    'brix_cred_select_fallback_total': ('proto',),
    'brix_cred_select_user_total': ('proto',),
    'brix_csi_scrub_mismatch_total': ('auth', 'port'),
    'brix_cvmfs_bytes_served_total': ('source',),
    'brix_cvmfs_fill_failures_total': (),
    'brix_cvmfs_fills_total': (),
    'brix_cvmfs_negative_hits_total': (),
    'brix_cvmfs_origin_bytes_total': (),
    'brix_cvmfs_origin_failovers_total': (),
    'brix_cvmfs_repo_bytes_served_total': ('repo', 'source'),
    'brix_cvmfs_repo_cache_hits_total': ('repo',),
    'brix_cvmfs_repo_cache_misses_total': ('repo',),
    'brix_cvmfs_repo_files_accessed_total': ('repo',),
    'brix_cvmfs_repo_fill_failures_total': ('repo',),
    'brix_cvmfs_repo_fills_total': ('repo',),
    'brix_cvmfs_repo_negative_hits_total': ('repo',),
    'brix_cvmfs_repo_origin_bytes_total': ('repo',),
    'brix_cvmfs_repo_requests_total': ('class', 'repo'),
    'brix_cvmfs_repo_verify_failures_total': ('repo',),
    'brix_cvmfs_requests_total': ('class',),
    'brix_cvmfs_upstream_failovers_total': ('upstream',),
    'brix_cvmfs_upstream_fill_duration_seconds': ('upstream',),
    'brix_cvmfs_upstream_fill_failures_total': ('upstream',),
    'brix_cvmfs_upstream_fills_total': ('upstream',),
    'brix_cvmfs_upstream_origin_bytes_total': ('upstream',),
    'brix_cvmfs_upstream_requests_total': ('upstream',),
    'brix_cvmfs_verify_failures_total': (),
    'brix_frm_asynresp_total': (),
    'brix_frm_cmsd_have_total': (),
    'brix_frm_dedup_hits_total': (),
    'brix_frm_evict_total': (),
    'brix_frm_in_flight': (),
    'brix_frm_migrate_total': (),
    'brix_frm_purge_total': (),
    'brix_frm_reject_inflight_total': (),
    'brix_frm_requests_total': (),
    'brix_frm_stage_fail_total': ('reason',),
    'brix_frm_stage_latency_seconds': (),
    'brix_frm_stage_success_total': (),
    'brix_frm_waitresp_total': (),
    'brix_io_bytes_read': ('proto',),
    'brix_io_bytes_written': ('proto',),
    'brix_io_latency_seconds': ('op', 'proto'),
    'brix_io_offload_total': ('proto',),
    'brix_io_ops_total': ('op', 'proto', 'status'),
    'brix_io_slowop_threshold_usec': (),
    'brix_io_slowop_total': ('op', 'proto'),
    'brix_mirror_divergence_total': ('surface',),
    'brix_mirror_dropped_total': ('surface',),
    'brix_mirror_errors_total': ('surface',),
    'brix_mirror_requests_total': ('surface',),
    'brix_oci_delegate_total': ('outcome',),
    'brix_oci_fill_bytes_total': ('surface',),
    'brix_oci_requests_total': ('class', 'outcome', 'surface'),
    'brix_oci_token_fetch_total': ('outcome',),
    'brix_oci_upstream_errors_total': ('status',),
    'brix_oci_verify_fail_total': (),
    'brix_ocsp_timeouts_total': (),
    'brix_path_depth_violations_total': ('auth', 'port'),
    'brix_pmark_firefly_dropped_total': (),
    'brix_pmark_firefly_sent_total': (),
    'brix_pmark_flowlabel_failed_total': (),
    'brix_pmark_flowlabel_set_total': (),
    'brix_pmark_flows_ended_total': (),
    'brix_pmark_flows_started_total': (),
    'brix_pmark_map_unresolved_total': (),
    'brix_proxy_abandoned_handles_total': ('auth', 'port'),
    'brix_proxy_closes_total': ('auth', 'port'),
    'brix_proxy_open_errors_total': ('auth', 'port'),
    'brix_proxy_opens_total': ('auth', 'port'),
    'brix_proxy_path_op_errors_total': ('auth', 'port'),
    'brix_proxy_path_ops_total': ('auth', 'port'),
    'brix_proxy_read_bytes_total': ('auth', 'port'),
    'brix_proxy_reads_total': ('auth', 'port'),
    'brix_proxy_reconnects_total': ('auth', 'port'),
    'brix_proxy_upstream_auth_errors_total': ('auth', 'port'),
    'brix_proxy_upstream_connect_errors_total': ('auth', 'port'),
    'brix_proxy_upstream_connects_total': ('auth', 'port'),
    'brix_proxy_wait_responses_total': ('auth', 'port'),
    'brix_proxy_write_bytes_total': ('auth', 'port'),
    'brix_proxy_writes_total': ('auth', 'port'),
    'brix_rate_limit_eviction_total': (),
    'brix_rate_limit_throttled_total': ('plane',),
    'brix_rate_limit_zone_full_errors_total': (),
    'brix_registry_full_total': (),
    'brix_requests_total': ('auth', 'op', 'port', 'status'),
    'brix_rpm_prefetch_fail_total': (),
    'brix_rpm_prefetch_total': (),
    'brix_rpm_requests_total': ('class', 'outcome'),
    'brix_rpm_verify_fail_total': (),
    'brix_s3_auth_total': ('result',),
    'brix_s3_bytes_rx_ipv4_total': (),
    'brix_s3_bytes_rx_ipv6_total': (),
    'brix_s3_bytes_tx_ipv4_total': (),
    'brix_s3_bytes_tx_ipv6_total': (),
    'brix_s3_events_total': ('event',),
    'brix_s3_list_common_prefixes_total': (),
    'brix_s3_list_contents_total': (),
    'brix_s3_list_truncated_total': (),
    'brix_s3_put_bodies_total': ('mode',),
    'brix_s3_range_requests_total': ('result',),
    'brix_s3_requests_total': ('method',),
    'brix_s3_responses_total': ('method', 'status_class'),
    'brix_scvmfs_requests_total': (),
    'brix_session_evict_total': (),
    'brix_session_registry_full_total': (),
    'brix_session_src_cap_evict_total': (),
    'brix_ssi_alerts_pushed_total': ('auth', 'port'),
    'brix_ssi_attn_push_failures_total': ('auth', 'port'),
    'brix_ssi_errors_total': ('auth', 'port'),
    'brix_ssi_requests_total': ('auth', 'port'),
    'brix_storage_backend_info': ('auth', 'backend', 'export', 'origin', 'staging'),
    'brix_storage_bytes_available': ('backend', 'export'),
    'brix_storage_bytes_total': ('backend', 'export'),
    'brix_storage_bytes_used': ('backend', 'export'),
    'brix_storage_io_bytes_read': ('backend',),
    'brix_storage_io_bytes_written': ('backend',),
    'brix_storage_occupancy_ratio': ('backend', 'export'),
    'brix_stream_connections_rejected_total': ('auth', 'port'),
    'brix_stream_handshake_timeouts_total': ('auth', 'port'),
    'brix_stream_io_uring_active': ('auth', 'port'),
    'brix_stream_io_uring_fallback_total': ('auth', 'port'),
    'brix_stream_io_uring_ops_total': ('auth', 'port'),
    'brix_stream_oversized_payloads_total': ('auth', 'port'),
    'brix_stream_read_pdu_timeouts_total': ('auth', 'port'),
    'brix_stream_request_frames_total': ('auth', 'port'),
    'brix_stream_request_payload_bytes_total': ('auth', 'port'),
    'brix_stream_response_frames_total': ('auth', 'port'),
    'brix_stream_response_write_errors_total': ('auth', 'port'),
    'brix_stream_response_write_stalls_total': ('auth', 'port'),
    'brix_stream_send_drain_timeouts_total': ('auth', 'port'),
    'brix_stream_tpc_egress_refused_total': ('auth', 'port'),
    'brix_tpc_bytes_total': ('direction', 'proto'),
    'brix_tpc_gsi_delegated_total': ('result',),
    'brix_tpc_transfers_total': ('direction', 'proto', 'status'),
    'brix_unique_users_current': (),
    'brix_unique_users_total': (),
    'brix_user_evictions_total': (),
    'brix_user_sessions_total': ('hash',),
    'brix_vfs_bulk_delete_batches_total': ('driver',),
    'brix_vfs_bulk_delete_keys_total': ('driver',),
    'brix_vfs_authz_backstop_total': ('proto', 'result'),
    'brix_vfs_domain_mutation_total': ('domain', 'op'),
    'brix_vfs_evict_bytes_total': ('driver',),
    'brix_vfs_lock_refused_total': ('proto',),
    'brix_vfs_mutation_denied_total': ('op', 'proto', 'reason'),
    'brix_vfs_precond_advisory_total': ('driver',),
    'brix_vfs_precond_failed_total': ('kind',),
    'brix_vfs_recall_total': ('result',),
    'brix_vfs_spill_active': (),
    'brix_vfs_spill_bytes_total': ('proto',),
    'brix_vfs_spill_refused_total': ('proto',),
    'brix_vo_bytes_rx_total': ('vo',),
    'brix_vo_bytes_tx_total': ('vo',),
    'brix_vo_overflow_total': (),
    'brix_vo_requests_total': ('vo',),
    'brix_webdav_auth_total': ('result',),
    'brix_webdav_bytes_rx_ipv4_total': (),
    'brix_webdav_bytes_rx_ipv6_total': (),
    'brix_webdav_bytes_tx_ipv4_total': (),
    'brix_webdav_bytes_tx_ipv6_total': (),
    'brix_webdav_cors_total': ('event',),
    'brix_webdav_propfind_depth_total': ('depth',),
    'brix_webdav_propfind_entries_total': (),
    'brix_webdav_put_bodies_total': ('mode',),
    'brix_webdav_range_requests_total': ('result',),
    'brix_webdav_requests_total': ('method',),
    'brix_webdav_responses_total': ('method', 'status_class'),
    'brix_webdav_tpc_cred_total': ('event',),
    'brix_webdav_tpc_total': ('event',),
    'brix_wire_bytes_rx_total': ('auth', 'port'),
    'brix_wire_bytes_tx_total': ('auth', 'port'),
    'brix_wt_dirty_handles': ('auth', 'port'),
    'brix_wt_flush_bytes_total': ('auth', 'port'),
    'brix_wt_flush_pending': ('auth', 'port'),
    'brix_wt_flushes_total': ('auth', 'port', 'result'),
    'brix_wt_stage_throttled_total': ('action',),
    'brix_wt_stage_usage_ratio': (),
    'brix_xfer_heap_bytes': ('auth', 'port'),
    'brix_xfer_heap_high_water_bytes': ('auth', 'port'),
}

CONDITIONAL = frozenset({
    'brix_cache_bytes',
    # zero-suppressed families: the exporter skips v==0 rows, and the label
    # matrix stack drives no offloaded reads or slow ops.
    'brix_io_offload_total',
    'brix_io_slowop_total',
    'brix_cache_evicted_bytes_total',
    'brix_cache_eviction_errors_total',
    'brix_cache_eviction_threshold_ratio',
    'brix_cache_evictions_total',
    'brix_cache_occupancy_ratio',
    'brix_cvmfs_repo_bytes_served_total',
    'brix_cvmfs_repo_cache_hits_total',
    'brix_cvmfs_repo_cache_misses_total',
    'brix_cvmfs_repo_files_accessed_total',
    'brix_cvmfs_repo_fill_failures_total',
    'brix_cvmfs_repo_fills_total',
    'brix_cvmfs_repo_negative_hits_total',
    'brix_cvmfs_repo_origin_bytes_total',
    'brix_cvmfs_repo_requests_total',
    'brix_cvmfs_repo_verify_failures_total',
    'brix_cvmfs_upstream_failovers_total',
    'brix_cvmfs_upstream_fill_duration_seconds',
    'brix_cvmfs_upstream_fill_failures_total',
    'brix_cvmfs_upstream_fills_total',
    'brix_cvmfs_upstream_origin_bytes_total',
    'brix_cvmfs_upstream_requests_total',
    'brix_user_sessions_total',
    'brix_vo_bytes_rx_total',
    'brix_vo_bytes_tx_total',
    'brix_vo_requests_total',
})
