"""Call signatures for public author functions."""

from __future__ import annotations

# Compact signature ABI: ``?`` means optional, ``*`` begins keyword-only
# parameters, and ``*name``/``**name`` are variadic. Tests compare this with
# ``inspect.signature`` so a seemingly harmless edit cannot break test authors.
PUBLIC_CALL_SHAPES = {
    "api_contract": (),
    "artifact": ("name", "kind", "*", "filename?", "**options"),
    "artifact_ref": ("value", "*", "directory?"),
    "binary": (
        "name", "path?", "*", "libraries?", "discover_libraries?", "image?",
        "image_path?", "runtime_files?",
    ),
    "binary_ref": ("value", "*", "directory?"),
    "case": (
        "*declared_resources",
        "resources?",
        "servers?",
        "clients?",
        "artifacts?",
        "binaries?",
        "credentials?",
        "auth?",
        "hosts?",
        "environments?",
        "volumes?",
        "identities?",
        "tasks?",
        "managed_resources?",
        "observe?",
        "trials?",
        "warmup?",
        "timeout?",
        "backend?",
        "isolation?",
        "keep?",
    ),
    "checksum_credential": (
        "name",
        "artifact",
        "*",
        "algorithm?",
        "destination?",
        "env?",
        "env_value?",
        "targets?",
        "mode?",
    ),
    "client": (
        "name",
        "*",
        "command?",
        "execution?",
        "binary?",
        "args?",
        "env?",
        "timeout?",
        "binaries?",
        "cwd?",
        "input?",
        "expected_exit_codes?",
        "output_limit?",
        "mode?",
        "retries?",
        "encoding?",
        "mounts?",
        "logs?",
        "placement?",
        "metadata?",
    ),
    "command": (
        "*argv",
        "env?",
        "cwd?",
        "input?",
        "encoding?",
        "timeout?",
        "expected_exit_codes?",
        "output_limit?",
        "mode?",
        "retries?",
    ),
    "configs": ("*files", "primary?"),
    "config_ref": ("value",),
    "collector": ("name", "**options"),
    "credential": (
        "name",
        "value?",
        "*",
        "source?",
        "destination?",
        "env?",
        "env_value?",
        "targets?",
        "mode?",
    ),
    "credential_ref": ("value", "*", "directory?"),
    "decode_token": ("token",),
    "docker": ("image", "*", "python?", "extra_args?", "allow_mutable?"),
    "endpoint": ("name?", "*", "protocol?", "port?", "scheme?", "metadata?", "family?", "exposure?"),
    "environment": ("name", "*", "backend?", "context?", "namespace?", "family?", "dns_domain?", "isolated?", "options?"),
    "exec_probe": ("*argv", "endpoint?", "timeout?", "interval?"),
    "execution": (
        "*argv",
        "env?",
        "cwd?",
        "input?",
        "encoding?",
        "timeout?",
        "expected_exit_codes?",
        "output_limit?",
        "mode?",
        "retries?",
    ),
    "file_artifact": ("name", "path", "*", "filename?"),
    "get_case": ("value",),
    "get_extension": ("kind", "name"),
    "host_mapping": ("name", "hostname", "*", "address?", "aliases?", "reverse?", "libc?", "targets?"),
    "http_endpoint": ("name?", "*", "port?", "tls?", "metadata?", "family?", "exposure?"),
    "http_probe": ("endpoint?", "*", "path?", "tls?", "statuses?", "timeout?", "interval?"),
    "immediate": (),
    "identity": ("name", "*", "uid?", "gid?", "groups?", "user_namespace?", "uid_map?", "gid_map?", "capabilities?", "permissions?", "service_account?"),
    "is_case": ("value",),
    "issue_token": (
        "*",
        "secret?",
        "issuer",
        "audience",
        "subject",
        "scopes?",
        "claims?",
        "lifetime?",
        "now?",
        "algorithm?",
        "private_key?",
        "key_id?",
    ),
    "installed_extensions": ("kind?",),
    "kerberos_auth": (
        "name?",
        "*",
        "realm?",
        "domain?",
        "hostname?",
        "user?",
        "service?",
        "password?",
        "master_password?",
        "port?",
        "start_kdc?",
    ),
    "kubernetes": (
        "image", "*", "context?", "namespace?", "service_account?", "python?",
    ),
    "kubernetes_events": ("*", "interval?", "name?"),
    "load_template": ("path",),
    "mount": ("source", "target", "*", "read_only?", "kind?", "propagation?"),
    "noise": ("name", "*", "size", "seed?", "filename?"),
    "nsenter": ("target_pid", "*", "namespaces?"),
    "param": ("name",),
    "podman": ("image", "*", "python?", "extra_args?", "allow_mutable?"),
    "process": (),
    "process_tree": ("*", "interval?", "name?"),
    "probe": (
        "kind?",
        "*",
        "endpoint?",
        "timeout?",
        "interval?",
        "path?",
        "command?",
        "statuses?",
        "pattern?",
    ),
    "prometheus": ("url", "*", "interval?", "name?", "allow?", "timeout?"),
    "runc": ("bundle", "*", "python?", "extra_args?"),
    "resource": ("name", "kind", "*", "depends_on?", "**options"),
    "run_root_ref": (),
    "register_extension": (
        "kind",
        "name",
        "target",
        "*",
        "replace?",
        "api_version?",
        "capabilities?",
        "origin?",
    ),
    "ref": ("kind", "name?", "*", "attribute?", "role?"),
    "server": (
        "name",
        "*",
        "command?",
        "execution?",
        "binary?",
        "args?",
        "config?",
        "configs?",
        "ports?",
        "env?",
        "readiness?",
        "depends_on?",
        "binaries?",
        "image?",
        "scope?",
        "endpoints?",
        "probe?",
        "mounts?",
        "lifecycle?",
        "placement?",
        "logs?",
        "cwd?",
        "metadata?",
        "replicas?",
    ),
    "server_ref": ("value", "*", "attribute?", "role?"),
    "server_config": ("content", "filename?", "*", "template?"),
    "signed_credential": (
        "name",
        "payload",
        "*",
        "secret",
        "algorithm?",
        "destination?",
        "env?",
        "env_value?",
        "targets?",
        "mode?",
    ),
    "static_config": ("path", "*", "destination?"),
    "structured_logs": ("*paths", "name?", "max_line_bytes?"),
    "task": ("name", "*", "command", "phase?", "depends_on?", "env?", "outputs?", "timeout?", "binaries?", "mounts?", "placement?", "metadata?"),
    "tcp": ("port?", "*", "timeout?"),
    "template_config": ("path", "*", "destination?", "values?"),
    "text_artifact": ("name", "text", "*", "filename?"),
    "tls_auth": ("name?", "*", "hostname?", "aliases?", "client_name?", "days?", "key_bits?"),
    "token_auth": (
        "name?",
        "*",
        "issuer?",
        "audience?",
        "subject?",
        "scopes?",
        "claims?",
        "secret?",
        "lifetime?",
        "algorithm?",
        "key_bits?",
        "key_id?",
        "managed?",
        "rotate_on_restart?",
    ),
    "tool": (
        "name",
        "*",
        "execution?",
        "command?",
        "binary?",
        "args?",
        "env?",
        "timeout?",
        "binaries?",
        "cwd?",
        "input?",
        "expected_exit_codes?",
        "output_limit?",
        "mode?",
        "retries?",
        "encoding?",
        "mounts?",
        "logs?",
        "placement?",
        "metadata?",
    ),
    "volume": ("name", "*", "kind?", "size?", "source?", "access?", "persistent?", "provider?", "options?"),
    "verify_token": (
        "token", "*", "secret?", "issuer?", "audience?", "now?",
        "public_key?", "algorithms?",
    ),
    "voms_auth": (
        "name?",
        "*",
        "vo?",
        "hostname?",
        "user_name?",
        "fqans?",
        "port?",
        "days?",
        "key_bits?",
    ),
    "workspace_ref": (),
}

# Every callable or property intentionally visible on a top-level public class.
# Keeping this beside the export and signature manifests makes the whole author
# contract available to tests, documentation generators, IDE helpers, and the
# CLI without importing test code.
