"""Member-level ABI metadata for the stable author API."""

from typing import Mapping

PUBLIC_MEMBER_CALL_SHAPES: Mapping[str, tuple[str, ...]] = {
    "Artifact.ref": ("*", "directory?"),
    "BackendContext.backend": (),
    "BackendContext.definition": (),
    "BackendContext.evidence": (),
    "BackendContext.metrics": (),
    "BackendContext.nodeid": (),
    "BackendContext.publish_service": ("service",),
    "BackendContext.root": (),
    "BackendContext.run": (),
    "BackendContext.services": (),
    "BackendContext.start_kubernetes": (),
    "BackendContext.start_local": (),
    "BackendContext.stop_kubernetes": (),
    "BackendContext.stop_local": (),
    "BackendContext.set_kubernetes_context": ("context",),
    "BackendContext.workspace": (),
    "BriXTestError.details": (),
    "Binary.ref": ("*", "directory?"),
    "CapturedBinary.as_dict": (),
    "CapturedBinary.verify": (),
    "CaseDefinition.as_dict": (),
    "CaseDefinition.resource_names": (),
    "CaseDefinition.tools": (),
    "CaseManager.client": ("name",),
    "CaseManager.close": (),
    "CaseManager.service": ("name",),
    "CaseManager.set_outcome": ("outcome",),
    "CaseManager.start": (),
    "CaseRunError.details": (),
    "Client.execution": (),
    "Client.resource_kind": (),
    "CommandResult.args": (),
    "CommandResult.as_dict": (),
    "CommandResult.check": (),
    "CommandResult.check_returncode": (),
    "CommandResult.json": (),
    "CommandResult.ok": (),
    "CommandResult.output": (),
    "CommandResult.stderr_lines": (),
    "CommandResult.stdout_lines": (),
    "ConfigFile.filename": (),
    "ConfigSet.get": ("destination",),
    "ConfigSet.primary_file": (),
    "ConfigTemplate.fill": ("*", "filename?", "**values"),
    "ConfiguredClient.as_dict": (),
    "ConfiguredClient.command": (),
    "ConfiguredClient.cwd": (),
    "ConfiguredClient.name": (),
    "ConfiguredClient.run": ("*args", "check?", "timeout?", "input?", "env?", "cwd?", "expected_exit_codes?", "output_limit?", "mode?", "retries?", "encoding?"),
    "ConfiguredClient.timeout": (),
    "ConfiguredTool.as_dict": (),
    "ConfiguredTool.command": (),
    "ConfiguredTool.cwd": (),
    "ConfiguredTool.name": (),
    "ConfiguredTool.run": ("*args", "check?", "timeout?", "input?", "env?", "cwd?", "expected_exit_codes?", "output_limit?", "mode?", "retries?", "encoding?"),
    "ConfiguredTool.timeout": (),
    "Credential.ref": ("*", "directory?"),
    "Environment.resource_kind": (),
    "HelperProcessError.details": (),
    "HostMapping.hostnames": (),
    "Identity.resource_kind": (),
    "ExtensionRegistry.clear": (),
    "ExtensionRegistry.describe": ("kind?",),
    "ExtensionRegistry.discover": ("*", "refresh?"),
    "ExtensionRegistry.load": ("kind", "name"),
    "ExtensionRegistry.names": ("kind?",),
    "ExtensionRegistry.register": ("kind", "name", "target", "*", "replace?", "api_version?", "capabilities?", "origin?"),
    "Isolation.cli_args": (),
    "Isolation.resolved": ("source_root",),
    "MaterializedArtifact.as_dict": (),
    "MaterializedArtifact.open": ("mode?", "*", "encoding?"),
    "MaterializedArtifact.read_bytes": (),
    "MaterializedArtifact.read_json": ("*", "encoding?"),
    "MaterializedArtifact.read_text": ("encoding?", "errors?"),
    "MaterializedArtifact.verify": (),
    "MaterializedAuth.as_dict": (),
    "MaterializedAuth.available": (),
    "MaterializedAuth.environment": ("target?",),
    "MaterializedAuth.issue": ("*", "subject?", "scopes?"),
    "MaterializedAuth.path": ("name",),
    "MaterializedAuth.revoke": ("certificate?",),
    "MaterializedAuth.rotate": ("*", "key_id?"),
    "MaterializedAuth.start": (),
    "MaterializedAuth.stop": (),
    "MaterializedCredential.as_dict": (),
    "MaterializedCredential.content": (),
    "MaterializedCredential.open": ("mode?", "*", "encoding?"),
    "MaterializedCredential.read_bytes": (),
    "MaterializedCredential.read_text": ("encoding?", "errors?"),
    "MaterializedCredential.verify": (),
    "MetricRecorder.count": ("name", "value?", "*", "unit?", "labels?"),
    "MetricRecorder.gauge": ("name", "value", "*", "unit?", "labels?"),
    "MetricRecorder.observe": ("name", "value", "*", "unit?", "labels?"),
    "MetricRecorder.record": ("name", "value", "*", "unit?", "kind?", "labels?"),
    "MetricRecorder.set_sink": ("sink", "*", "replay?"),
    "MetricRecorder.snapshot": (),
    "MetricRecorder.tag": ("name", "value"),
    "MetricRecorder.timer": ("name", "*", "labels?"),
    "MetricSample.as_dict": (),
    "ProviderContext.resource_root": ("name",),
    "ProviderContext.kubernetes": (),
    "ProviderInstance.as_dict": (),
    "ProviderPlan.as_dict": (),
    "Run.artifact": ("value",),
    "Run.artifact_bytes": ("value",),
    "Run.artifact_file": ("value",),
    "Run.artifact_json": ("value", "*", "encoding?"),
    "Run.artifact_path": ("value",),
    "Run.artifact_text": ("value", "*", "encoding?", "errors?"),
    "Run.artifacts": (),
    "Run.as_dict": (),
    "Run.attach": ("path", "**metadata"),
    "Run.attach_json": ("name", "value", "**metadata"),
    "Run.attach_text": ("name", "text", "**metadata"),
    "Run.auth": ("value",),
    "Run.auth_stacks": (),
    "Run.binaries": (),
    "Run.binary": ("value",),
    "Run.client": ("value",),
    "Run.clients": (),
    "Run.command": ("*argv", "check?", "timeout?", "input?", "env?", "cwd?", "encoding?", "expected_exit_codes?", "output_limit?", "mode?", "retries?"),
    "Run.credential": ("value",),
    "Run.credentials": (),
    "Run.execute": ("declaration", "*args", "check?", "env?", "cwd?"),
    "Run.open_artifact": ("value", "mode?", "*", "encoding?"),
    "Run.resolve": ("hostname",),
    "Run.resource": ("value",),
    "Run.resources": (),
    "Run.reverse": ("address",),
    "Run.server": ("value",),
    "Run.servers": (),
    "Run.step": ("name", "**attributes"),
    "Run.task": ("value",),
    "Run.task_output": ("value", "name"),
    "Run.tasks": (),
    "Run.tool": ("declaration", "*args", "check?", "env?", "cwd?"),
    "Run.tools": (),
    "Run.volume": ("value",),
    "Run.volumes": (),
    "Reference.key": (),
    "Replica.address": ("role?",),
    "Replica.as_dict": (),
    "Replica.endpoint": ("role?",),
    "Replica.port": ("role?",),
    "Resource.ref": ("output?",),
    "Resource.resource_kind": (),
    "Server.config_path": (),
    "Server.execution": (),
    "Server.host": (),
    "Server.log_path": (),
    "Server.port": ("role?",),
    "Server.url": ("role?",),
    "Service.address": ("role?",),
    "Service.as_dict": (),
    "Service.command": ("*argv", "timeout?", "check?"),
    "Service.endpoint": ("role?",),
    "Service.follow_log": ("*", "timeout?", "interval?", "encoding?", "errors?"),
    "Service.fs": (),
    "Service.is_ready": ("role?", "*", "timeout?"),
    "Service.port": ("role?",),
    "Service.read_config": ("destination?", "*", "encoding?", "errors?"),
    "Service.read_log": ("*", "encoding?", "errors?"),
    "Service.restart": (),
    "Service.signal": ("signal_name?",),
    "Service.tail_log": ("lines?", "*", "encoding?", "errors?"),
    "Service.url": ("scheme?", "*", "role?", "path?"),
    "Service.wait": ("*", "timeout?"),
    "Service.wait_ready": ("role?", "*", "timeout?", "interval?"),
    "ServiceFilesystem.chmod": ("path", "mode"),
    "ServiceFilesystem.chown": ("path", "uid?", "gid?"),
    "ServiceFilesystem.getxattr": ("path", "name"),
    "ServiceFilesystem.list": ("path?",),
    "ServiceFilesystem.listxattr": ("path",),
    "ServiceFilesystem.mkdir": ("path", "*", "parents?", "exist_ok?"),
    "ServiceFilesystem.read_bytes": ("path",),
    "ServiceFilesystem.read_text": ("path", "*", "encoding?", "errors?"),
    "ServiceFilesystem.remove": ("path", "*", "recursive?"),
    "ServiceFilesystem.removexattr": ("path", "name"),
    "ServiceFilesystem.setxattr": ("path", "name", "value"),
    "ServiceFilesystem.stat": ("path", "*", "follow_symlinks?"),
    "ServiceFilesystem.symlink": ("target", "path"),
    "ServiceFilesystem.write_bytes": ("path", "value"),
    "ServiceFilesystem.write_text": ("path", "value", "*", "encoding?"),
    "SpecError.details": (),
    "TemplateError.details": (),
    "Task.output": ("name",),
    "Task.resource_kind": (),
    "Tool.execution": (),
    "Tool.resource_kind": (),
    "ToolExecutionContext.execute_local": ("request",),
    "Volume.ref": ("*", "attribute?"),
    "Volume.resource_kind": (),
}

PUBLIC_PROPERTIES: Mapping[str, tuple[str, ...]] = {
    "BackendContext": (
        "backend", "definition", "evidence", "metrics", "nodeid", "root", "run",
        "services", "workspace",
    ),
    "CaseDefinition": ("resource_names", "tools"),
    "Client": ("execution", "resource_kind"),
    "CommandResult": ("args", "ok", "output", "stderr_lines", "stdout_lines"),
    "ConfigFile": ("filename",),
    "ConfigSet": ("primary_file",),
    "ConfiguredClient": ("command", "cwd", "name", "timeout"),
    "ConfiguredTool": ("command", "cwd", "name", "timeout"),
    "HostMapping": ("hostnames",),
    "Environment": ("resource_kind",),
    "Identity": ("resource_kind",),
    "MaterializedCredential": ("content",),
    "Reference": ("key",),
    "Resource": ("resource_kind",),
    "Run": (
        "artifacts", "auth_stacks", "binaries", "clients", "credentials",
        "resources", "servers", "tasks", "tools", "volumes",
    ),
    "Server": ("config_path", "execution", "host", "log_path"),
    "Service": ("fs",),
    "Tool": ("execution", "resource_kind"),
    "Task": ("resource_kind",),
    "Volume": ("resource_kind",),
}

# Stable, directly readable instance data. Properties stay in
# ``PUBLIC_PROPERTIES``; these names cover dataclass fields and intentionally
# public state on the few non-dataclass facade/manager objects.
PUBLIC_ATTRIBUTES: Mapping[str, tuple[str, ...]] = {
    "Artifact": ("name", "kind", "size", "seed", "source", "text", "filename", "options"),
    "ArtifactProviderContext": ("root", "source_root"),
    "AuthRecipe": ("name", "kind"),
    "Binary": (
        "name", "path", "libraries", "discover_libraries", "image", "image_path",
        "runtime_files",
    ),
    "BackendContext": (),
    "BriXTestError": (),
    "CapturedBinary": (
        "name", "path", "library_dir", "sha256", "libraries", "image", "image_path",
        "source", "overridden", "runtime_files",
    ),
    "CaseDefinition": ("servers", "clients", "artifacts", "binaries", "credentials", "auth", "hosts", "observe", "trials", "warmup", "timeout", "backend", "isolation", "keep", "source", "parameters", "environments", "volumes", "identities", "tasks", "managed_resources"),
    "CaseManager": ("definition", "nodeid", "root", "workspace", "source_root", "parameters", "backend_name", "kubernetes_context", "binary_store", "artifact_store", "config_store", "security", "registry", "metrics", "commands", "evidence", "backend_context"),
    "CaseRunError": ("nodeid", "phase", "cause"),
    "Client": ("name", "command", "env", "timeout", "binaries", "cwd", "input", "expected_exit_codes", "output_limit", "mode", "retries", "encoding", "mounts", "logs", "placement", "metadata"),
    "CollectorSpec": ("kind", "name", "interval", "options"),
    "Command": ("argv", "env", "cwd", "input", "encoding", "timeout", "expected_exit_codes", "output_limit", "mode", "retries"),
    "Execution": ("argv", "env", "cwd", "input", "encoding", "timeout", "expected_exit_codes", "output_limit", "mode", "retries"),
    "CommandResult": ("argv", "returncode", "stdout", "stderr", "elapsed_seconds", "attempts", "stdout_truncated", "stderr_truncated"),
    "ConfigFile": ("path", "template", "destination", "content", "values"),
    "ConfigSet": ("files", "primary"),
    "ConfigTemplate": ("path",),
    "ConfiguredClient": ("spec",),
    "ConfiguredTool": ("spec",),
    "Credential": ("name", "kind", "value", "source", "artifact", "secret", "algorithm", "destination", "env", "env_value", "targets", "mode"),
    "Endpoint": ("name", "protocol", "port", "scheme", "metadata", "family", "exposure"),
    "Environment": ("name", "backend", "context", "namespace", "family", "dns_domain", "isolated", "options"),
    "ExtensionInfo": ("kind", "name", "api_version", "capabilities", "origin", "loaded"),
    "ExtensionRegistry": (),
    "HelperProcessError": ("nodeid", "timeout", "returncode", "output", "run_path"),
    "HostMapping": ("name", "hostname", "address", "aliases", "reverse", "libc", "targets"),
    "Identity": ("name", "uid", "gid", "groups", "user_namespace", "uid_map", "gid_map", "capabilities", "permissions", "service_account"),
    "Isolation": (
        "kind", "image", "target_pid", "namespaces", "bundle", "python",
        "extra_args", "allow_mutable_image", "context", "namespace",
        "service_account",
    ),
    "KerberosAuth": ("name", "kind", "realm", "domain", "hostname", "user", "service", "password", "master_password", "port", "start_kdc"),
    "Lifecycle": ("background", "shutdown_signal", "shutdown_command", "stop_timeout", "expected_exit"),
    "LogPolicy": ("capture", "max_bytes", "tail_lines", "redact"),
    "MaterializedArtifact": ("name", "path", "size", "sha256", "kind", "seed"),
    "MaterializedAuth": ("name", "kind", "root", "files", "test_env", "server_env", "client_env", "metadata"),
    "MaterializedCredential": ("name", "path", "sha256", "kind", "destination", "env", "env_value", "targets"),
    "MetricRecorder": (),
    "MetricSample": ("name", "value", "unit", "kind", "labels", "at_seconds"),
    "MetricTimer": ("elapsed",),
    "Mount": ("source", "target", "read_only", "kind", "propagation"),
    "Placement": ("backend", "image", "namespace", "labels", "node_selector", "security_context", "resources", "options", "allow_mutable_image", "environment", "group", "identity", "network_policy"),
    "Probe": ("kind", "endpoint", "timeout", "interval", "path", "command", "statuses", "pattern"),
    "ProviderContext": ("nodeid", "root", "backend", "evidence", "metrics"),
    "ProviderInstance": ("name", "provider", "ownership", "outputs", "metadata"),
    "ProviderPlan": ("name", "provider", "fragment", "fingerprint"),
    "Reference": ("kind", "name", "attribute", "role"),
    "Readiness": ("kind", "port", "timeout"),
    "Replica": ("name", "host", "ports", "uid", "phase", "ready", "restarts", "started_at", "metadata"),
    "Resource": ("name", "kind", "options", "depends_on"),
    "Run": ("root", "workspace", "backend", "metrics"),
    "ResourceLimits": ("cpu", "memory_bytes", "pids"),
    "Server": ("name", "command", "config", "ports", "env", "readiness", "depends_on", "binaries", "image", "scope", "configs", "endpoints", "probe", "mounts", "lifecycle", "placement", "logs", "cwd", "metadata", "replicas"),
    "ServerLaunchContext": ("nodeid", "root", "workspace"),
    "ServerLaunchPlan": ("argv", "env", "cwd", "launcher", "cleanup_argv", "metadata"),
    "ServerLaunchRequest": (
        "declaration", "argv", "env", "cwd", "mounts", "identity", "host_aliases",
    ),
    "Service": ("name", "host", "ports", "config", "log", "workdir", "instance_id", "scope", "started_at", "pool_id", "config_filename", "config_sha256", "config_source_sha256", "config_declared_sha256", "config_artifact", "configs", "schemes", "protocols", "hosts", "metadata", "replicas"),
    "ServiceFilesystem": (),
    "SpecError": ("field", "value", "rule"),
    "TLSAuth": ("name", "kind", "hostname", "aliases", "client_name", "days", "key_bits"),
    "Task": ("name", "command", "phase", "depends_on", "env", "outputs", "timeout", "binaries", "mounts", "placement", "metadata"),
    "Tool": ("name", "command", "env", "timeout", "binaries", "cwd", "input", "expected_exit_codes", "output_limit", "mode", "retries", "encoding", "mounts", "logs", "placement", "metadata"),
    "ToolExecutionContext": ("nodeid", "root", "workspace", "backend", "namespace", "metadata", "local_execute", "identities"),
    "ToolExecutionRequest": ("name", "argv", "env", "cwd", "timeout", "input", "expected_exit_codes", "output_limit", "mode", "retries", "encoding", "check", "placement", "image", "metadata"),
    "TemplateError": ("template", "missing_keys"),
    "TokenAuth": (
        "name", "kind", "issuer", "audience", "subject", "scopes", "claims",
        "secret", "lifetime", "algorithm", "key_bits", "key_id",
        "managed", "rotate_on_restart",
    ),
    "VOMSAuth": ("name", "kind", "vo", "hostname", "user_name", "fqans", "port", "days", "key_bits"),
    "Volume": ("name", "kind", "size", "source", "access", "persistent", "provider", "options"),
}
