"""Constructor signatures for public classes."""

from __future__ import annotations

from typing import Mapping

PUBLIC_CLASS_CALL_SHAPES: Mapping[str, tuple[str, ...]] = {
    "Artifact": ("name", "kind", "size?", "seed?", "source?", "text?", "filename?", "options?"),
    "ArtifactProviderContext": ("root", "source_root"),
    "AuthRecipe": ("name", "kind"),
    "Binary": ("name", "path?", "libraries?", "discover_libraries?", "image?", "image_path?"),
    "BackendContext": ("manager",),
    "BriXTestError": ("message?",),
    "CapturedBinary": (
        "name",
        "path",
        "library_dir",
        "sha256",
        "libraries",
        "image?",
        "image_path?",
        "source?",
        "overridden?",
    ),
    "CaseDefinition": (
        "servers",
        "clients",
        "artifacts",
        "binaries",
        "credentials",
        "auth",
        "hosts",
        "observe",
        "trials",
        "warmup",
        "timeout",
        "backend",
        "isolation",
        "keep",
        "source",
        "parameters?",
        "environments?",
        "volumes?",
        "identities?",
        "tasks?",
        "managed_resources?",
    ),
    "CaseManager": ("definition", "nodeid", "*", "root?"),
    "CaseRunError": ("nodeid", "phase", "cause"),
    "Client": (
        "name",
        "command",
        "env?",
        "timeout?",
        "binaries?",
        "cwd?",
        "input?",
        "expected_exit_codes?",
        "output_limit?",
        "mode?",
        "retries?",
        "encoding?",
        "mounts?",
        "logs?",
        "placement?",
        "metadata?",
    ),
    "CollectorSpec": ("kind", "name", "interval?", "options?"),
    "Command": (
        "argv",
        "env?",
        "cwd?",
        "input?",
        "encoding?",
        "timeout?",
        "expected_exit_codes?",
        "output_limit?",
        "mode?",
        "retries?",
    ),
    "Execution": (
        "argv",
        "env?",
        "cwd?",
        "input?",
        "encoding?",
        "timeout?",
        "expected_exit_codes?",
        "output_limit?",
        "mode?",
        "retries?",
    ),
    "CommandResult": (
        "argv",
        "returncode",
        "stdout",
        "stderr",
        "elapsed_seconds",
        "attempts?",
        "stdout_truncated?",
        "stderr_truncated?",
    ),
    "ConfigFile": ("path?", "template?", "destination?", "content?", "values?"),
    "ConfigSet": ("files", "primary?"),
    "ConfigTemplate": ("path",),
    "ConfiguredClient": (
        "spec",
        "values",
        "*",
        "observer?",
        "archive_dir?",
        "executor?",
        "execution_context?",
        "executor_metadata?",
        "result_observer?",
    ),
    "ConfiguredTool": (
        "spec",
        "values",
        "*",
        "observer?",
        "archive_dir?",
        "executor?",
        "execution_context?",
        "executor_metadata?",
        "result_observer?",
    ),
    "Credential": (
        "name",
        "kind",
        "value?",
        "source?",
        "artifact?",
        "secret?",
        "algorithm?",
        "destination?",
        "env?",
        "env_value?",
        "targets?",
        "mode?",
    ),
    "Endpoint": ("name?", "protocol?", "port?", "scheme?", "metadata?", "family?", "exposure?"),
    "Environment": ("name", "backend?", "context?", "namespace?", "family?", "dns_domain?", "isolated?", "options?"),
    "ExtensionInfo": ("kind", "name", "api_version?", "capabilities?", "origin?", "loaded?"),
    "ExtensionRegistry": (),
    "HelperProcessError": ("nodeid", "*", "timeout?", "returncode?", "output?", "run_path?"),
    "HostMapping": ("name", "hostname", "address?", "aliases?", "reverse?"),
    "Identity": ("name", "uid?", "gid?", "groups?", "user_namespace?", "uid_map?", "gid_map?", "capabilities?", "permissions?", "service_account?"),
    "Isolation": (
        "kind?",
        "image?",
        "target_pid?",
        "namespaces?",
        "bundle?",
        "python?",
        "extra_args?",
        "allow_mutable_image?",
    ),
    "KerberosAuth": (
        "name",
        "kind",
        "realm?",
        "domain?",
        "hostname?",
        "user?",
        "service?",
        "password?",
        "master_password?",
        "port?",
        "start_kdc?",
    ),
    "Lifecycle": (
        "background?",
        "shutdown_signal?",
        "shutdown_command?",
        "stop_timeout?",
        "expected_exit?",
    ),
    "LogPolicy": ("capture?", "max_bytes?", "tail_lines?", "redact?"),
    "MaterializedArtifact": ("name", "path", "size", "sha256", "kind", "seed?"),
    "MaterializedAuth": (
        "name",
        "kind",
        "root",
        "files",
        "test_env",
        "server_env",
        "client_env",
        "metadata",
    ),
    "MaterializedCredential": (
        "name",
        "path",
        "sha256",
        "kind",
        "destination",
        "env",
        "env_value",
        "targets",
    ),
    "MetricRecorder": ("sink?",),
    "MetricSample": ("name", "value", "unit", "kind", "labels", "at_seconds"),
    "MetricTimer": ("recorder", "name", "labels"),
    "Mount": ("source", "target", "read_only?", "kind?", "propagation?"),
    "Placement": (
        "backend?",
        "image?",
        "namespace?",
        "labels?",
        "node_selector?",
        "security_context?",
        "resources?",
        "options?",
        "allow_mutable_image?",
        "environment?",
        "group?",
        "identity?",
        "network_policy?",
    ),
    "Probe": (
        "kind?",
        "endpoint?",
        "timeout?",
        "interval?",
        "path?",
        "command?",
        "statuses?",
        "pattern?",
    ),
    "Reference": ("kind", "name?", "attribute?", "role?"),
    "Readiness": ("kind?", "port?", "timeout?"),
    "Resource": ("name", "kind", "options?", "depends_on?"),
    "Run": ("manager",),
    "ResourceLimits": ("cpu?", "memory_bytes?", "pids?"),
    "Server": (
        "name",
        "command",
        "config?",
        "ports?",
        "env?",
        "readiness?",
        "depends_on?",
        "binaries?",
        "image?",
        "scope?",
        "configs?",
        "endpoints?",
        "probe?",
        "mounts?",
        "lifecycle?",
        "placement?",
        "logs?",
        "cwd?",
        "metadata?",
        "replicas?",
    ),
    "ServerLaunchContext": ("nodeid", "root", "workspace"),
    "ServerLaunchPlan": ("argv", "env", "cwd", "launcher", "cleanup_argv?", "metadata?"),
    "ServerLaunchRequest": ("declaration", "argv", "env", "cwd"),
    "Service": (
        "name",
        "host",
        "ports",
        "config",
        "log",
        "workdir",
        "instance_id?",
        "scope?",
        "started_at?",
        "pool_id?",
        "config_filename?",
        "config_sha256?",
        "config_source_sha256?",
        "config_declared_sha256?",
        "config_artifact?",
        "configs?",
        "schemes?",
        "protocols?",
        "hosts?",
        "metadata?",
    ),
    "ServiceFilesystem": ("transport",),
    "SpecError": ("field", "value", "rule"),
    "TLSAuth": ("name", "kind", "hostname?", "aliases?", "client_name?", "days?", "key_bits?"),
    "Task": ("name", "command", "phase?", "depends_on?", "env?", "outputs?", "timeout?", "binaries?", "mounts?", "placement?", "metadata?"),
    "Tool": (
        "name",
        "command",
        "env?",
        "timeout?",
        "binaries?",
        "cwd?",
        "input?",
        "expected_exit_codes?",
        "output_limit?",
        "mode?",
        "retries?",
        "encoding?",
        "mounts?",
        "logs?",
        "placement?",
        "metadata?",
    ),
    "ToolExecutionContext": (
        "nodeid",
        "root",
        "workspace",
        "backend",
        "namespace?",
        "metadata?",
        "local_execute?",
    ),
    "ToolExecutionRequest": (
        "name",
        "argv",
        "env",
        "cwd",
        "timeout",
        "input",
        "expected_exit_codes",
        "output_limit",
        "mode",
        "retries",
        "encoding",
        "check",
        "placement",
        "image?",
        "metadata?",
    ),
    "TemplateError": ("template", "missing_keys"),
    "TokenAuth": (
        "name",
        "kind",
        "issuer?",
        "audience?",
        "subject?",
        "scopes?",
        "claims?",
        "secret?",
        "lifetime?",
    ),
    "VOMSAuth": (
        "name",
        "kind",
        "vo?",
        "hostname?",
        "user_name?",
        "fqans?",
        "port?",
        "days?",
        "key_bits?",
    ),
    "Volume": ("name", "kind?", "size?", "source?", "access?", "persistent?", "provider?", "options?"),
}
