"""Python declarations for BriXTest server/client cases.

The implementation is split by declaration responsibility; this module remains
the stable import surface used by tests and third-party extensions.
"""

from brixtest._design_cases import CaseDefinition, case, get_case, is_case
from brixtest._design_clients import Client, Tool, client, tool
from brixtest._design_managed import (
    Environment,
    Identity,
    Resource,
    Task,
    Volume,
    environment,
    identity,
    resource,
    task,
    volume,
)
from brixtest._design_inputs import (
    GB,
    KB,
    MB,
    Artifact,
    Binary,
    ConfigFile,
    ConfigSet,
    ConfigTemplate,
    GiB,
    KiB,
    MiB,
    Readiness,
    artifact,
    binary,
    configs,
    file_artifact,
    immediate,
    load_template,
    noise,
    server_config,
    static_config,
    tcp,
    template_config,
    text_artifact,
)
from brixtest._design_inputs import (
    _name as _name,
)
from brixtest._design_servers import Server, server

__all__ = [
    "GB",
    "KB",
    "MB",
    "Artifact",
    "Binary",
    "CaseDefinition",
    "Client",
    "ConfigFile",
    "ConfigSet",
    "ConfigTemplate",
    "Environment",
    "GiB",
    "KiB",
    "MiB",
    "Identity",
    "Readiness",
    "Resource",
    "Server",
    "Task",
    "Tool",
    "Volume",
    "artifact",
    "binary",
    "case",
    "client",
    "configs",
    "file_artifact",
    "environment",
    "get_case",
    "immediate",
    "identity",
    "is_case",
    "load_template",
    "noise",
    "resource",
    "server",
    "server_config",
    "static_config",
    "task",
    "tcp",
    "template_config",
    "text_artifact",
    "tool",
    "volume",
]
