nginx-xrootd: src/auth/authz/acc/acc.h File Reference
acc.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_event.h>
#include "privs.h"
Data Structures
struct brix_acc_cap_t
struct brix_acc_named_t
struct brix_acc_idrule_t
struct brix_acc_tables_t
struct brix_acc_attr_t
struct brix_acc_entity_t
struct brix_acc_http_t
Typedefs
typedef ngx_array_t *(* brix_acc_unixgrp_fn) (ngx_pool_t *pool, const char *user)
typedef int(* brix_acc_netgrp_fn) (const char *netgroup, const char *user, const char *host)
Functions
void brix_acc_set_group_resolvers (brix_acc_unixgrp_fn ug, brix_acc_netgrp_fn ng)
void brix_acc_groups_init (void)
void brix_acc_groups_set_gidlifetime (time_t secs)
void brix_acc_groups_set_primary_only (ngx_int_t on)
void brix_acc_groups_set_nisdomain (const char *domain)
void brix_acc_groups_set_gidretran (const char *gidlist)
brix_acc_tables_t * brix_acc_build (const char *authdb_path, ngx_int_t gidlifetime, ngx_int_t pgo, const char *nisdomain, const char *gidretran, char spacechar, ngx_int_t encoding, ngx_log_t *log)
void brix_acc_audit (ngx_log_t *log, ngx_uint_t level, int granted, const char *op, const char *id, const char *host, const char *path)
const char * brix_acc_resolve_peer (struct sockaddr *sa, socklen_t salen, char *buf, size_t buflen)
ngx_int_t brix_acc_http_authorize (ngx_pool_t *pool, ngx_log_t *log, brix_acc_http_t *acc, const char *name, const char *host, const char *vorg, const char *role, const char *grp, brix_acc_op_t op, const char *path)
void brix_acc_http_init_conf (brix_acc_http_t *acc)
void brix_acc_http_merge_conf (brix_acc_http_t *conf, brix_acc_http_t *prev)
int brix_acc_cap_privs (brix_acc_cap_t *cap, brix_acc_priv_caps_t *out, const char *path, int plen, const char *pathsub)
brix_acc_cap_t * brix_acc_named_find (brix_acc_named_t *list, const char *name)
brix_acc_cap_t * brix_acc_domain_find (brix_acc_named_t *dlist, const char *host)
brix_acc_tables_t * brix_acc_authfile_parse (ngx_log_t *log, const char *file, char spacechar, ngx_int_t uri_decode)
void brix_acc_tables_free (brix_acc_tables_t *tabs)
brix_acc_entity_t * brix_acc_entity_build (ngx_pool_t *pool, const char *name, const char *host, int isuser, const char *vorg_csv, const char *role_csv, const char *grp_csv)
brix_acc_privs_t brix_acc_access (brix_acc_tables_t *tabs, const brix_acc_entity_t *ent, const char *path, brix_acc_op_t op)
Variables
ngx_conf_enum_t brix_acc_format_modes []
ngx_conf_enum_t brix_acc_audit_modes []
Typedef Documentation
brix_acc_netgrp_fn
typedef int(* brix_acc_netgrp_fn) (const char *netgroup, const char *user, const char *host)
Definition at line 148 of file acc.h.
brix_acc_unixgrp_fn
typedef ngx_array_t *(* brix_acc_unixgrp_fn) (ngx_pool_t *pool, const char *user)
Definition at line 147 of file acc.h.
Function Documentation
brix_acc_access()
brix_acc_privs_t brix_acc_access (brix_acc_tables_t * tabs, const brix_acc_entity_t * ent, const char * path, brix_acc_op_t op)
Definition at line 345 of file access.c.
References acc_access2(), acc_grant_host(), acc_grant_tuples(), acc_grant_user(), acc_match_exclusive(), BRIX_ACC_PRIV_NONE, acc_eval_t::caps, acc_eval_t::ent, op, acc_eval_t::path, acc_eval_t::plen, acc_eval_t::tabs, brix_acc_entity_t::tuples, and acc_eval_t::tuples.
Referenced by brix_acc_gate_engine(), and brix_acc_http_authorize().
brix_acc_audit()
void brix_acc_audit (ngx_log_t * log, ngx_uint_t level, int granted, const char * op, const char * id, const char * host, const char * path)
Definition at line 44 of file audit.c.
References acc_audit_sanitize(), BRIX_ACC_AUDIT_DENY, BRIX_ACC_AUDIT_GRANT, log, and op.
Referenced by brix_acc_gate_engine(), and brix_acc_http_authorize().
brix_acc_authfile_parse()
brix_acc_tables_t * brix_acc_authfile_parse (ngx_log_t * log, const char * file, char spacechar, ngx_int_t uri_decode)
Definition at line 242 of file authfile.c.
References acc_finalize_rules(), acc_load_authfile(), ACC_LOAD_EMPTY, ACC_LOAD_ERROR, acc_tokenize_and_dispatch(), acc_loaded_t::buf, acc_parse_ctx_t::excl_seq, acc_loaded_t::fsize, acc_parse_ctx_t::id_tail, acc_parse_ctx_t::log, log, brix_acc_tables_t::mtime, acc_loaded_t::mtime, ngx_pcalloc(), brix_acc_tables_t::parse_spacechar, brix_acc_tables_t::parse_uridecode, brix_acc_tables_t::pool, and acc_parse_ctx_t::tabs.
Referenced by brix_acc_build().
brix_acc_build()
brix_acc_tables_t * brix_acc_build (const char * authdb_path, ngx_int_t gidlifetime, ngx_int_t pgo, const char * nisdomain, const char * gidretran, char spacechar, ngx_int_t encoding, ngx_log_t * log)
Definition at line 40 of file config.c.
References brix_acc_authfile_parse(), brix_acc_groups_init(), brix_acc_groups_set_gidlifetime(), brix_acc_groups_set_gidretran(), brix_acc_groups_set_nisdomain(), brix_acc_groups_set_primary_only(), and log.
Referenced by brix_acc_http_build(), brix_acc_init_server(), and brix_acc_refresh_handler().
brix_acc_cap_privs()
int brix_acc_cap_privs (brix_acc_cap_t * cap, brix_acc_priv_caps_t * out, const char * path, int plen, const char * pathsub)
Definition at line 61 of file capability.c.
References brix_acc_cap_privs(), brix_acc_cap_subcomp(), brix_acc_cap_t::caps, brix_acc_cap_t::next, brix_acc_priv_caps_t::nprivs, brix_acc_cap_t::path, brix_acc_cap_t::plen, brix_acc_priv_caps_t::pprivs, and brix_acc_cap_t::tmpl.
Referenced by acc_grant_host(), acc_grant_tuples(), acc_grant_user(), acc_match_exclusive(), and brix_acc_cap_privs().
brix_acc_domain_find()
brix_acc_cap_t * brix_acc_domain_find (brix_acc_named_t * dlist, const char * host)
Definition at line 37 of file tables.c.
References brix_acc_named_t::caps, brix_acc_named_t::name, brix_acc_named_t::next, and brix_acc_named_t::nlen.
Referenced by acc_grant_host().
brix_acc_entity_build()
brix_acc_entity_t * brix_acc_entity_build (ngx_pool_t * pool, const char * name, const char * host, int isuser, const char * vorg_csv, const char * role_csv, const char * grp_csv)
Definition at line 237 of file entity.c.
References acc_entity_fill_tuples(), acc_entity_init_scalars(), acc_entity_tuple_count(), acc_split_csv(), BRIX_PCALLOC_OR_RETURN, and name.
Referenced by brix_acc_gate_engine(), and brix_acc_http_authorize().
brix_acc_groups_init()
void brix_acc_groups_init (void)
Definition at line 392 of file groups.c.
References brix_acc_in_netgroup(), brix_acc_set_group_resolvers(), and brix_acc_unix_groups().
Referenced by brix_acc_build().
brix_acc_groups_set_gidlifetime()
void brix_acc_groups_set_gidlifetime (time_t secs)
Definition at line 42 of file groups.c.
References acc_gidlifetime.
Referenced by brix_acc_build().
brix_acc_groups_set_gidretran()
void brix_acc_groups_set_gidretran (const char * gidlist)
Definition at line 48 of file groups.c.
References acc_retrancnt, acc_retrangid, and BRIX_ACC_MAX_RETRAN.
Referenced by brix_acc_build().
brix_acc_groups_set_nisdomain()
void brix_acc_groups_set_nisdomain (const char * domain)
Definition at line 86 of file groups.c.
References acc_nisdomain, and ngx_memcpy.
Referenced by brix_acc_build().
brix_acc_groups_set_primary_only()
void brix_acc_groups_set_primary_only (ngx_int_t on)
Definition at line 43 of file groups.c.
References acc_primary_only.
Referenced by brix_acc_build().
brix_acc_http_authorize()
ngx_int_t brix_acc_http_authorize (ngx_pool_t * pool, ngx_log_t * log, brix_acc_http_t * acc, const char * name, const char * host, const char * vorg, const char * role, const char * grp, brix_acc_op_t op, const char * path)
Definition at line 195 of file config.c.
References brix_acc_http_t::audit, brix_acc_http_t::authdb, brix_acc_access(), brix_acc_audit(), brix_acc_entity_build(), brix_acc_http_arm_timer(), brix_acc_http_build(), brix_acc_op_name(), BRIX_ACC_PRIV_NONE, BRIX_AUTHDB_FORMAT_XRDACC, brix_acc_http_t::format, log, name, op, and brix_acc_http_t::tables.
Referenced by s3_acc_check(), and webdav_acc_check().
brix_acc_http_init_conf()
void brix_acc_http_init_conf (brix_acc_http_t * acc)
Definition at line 163 of file config.c.
References brix_acc_http_t::audit, brix_acc_http_t::encoding, brix_acc_http_t::format, brix_acc_http_t::gidlifetime, brix_acc_http_t::pgo, brix_acc_http_t::refresh, and brix_acc_http_t::resolve_hosts.
Referenced by ngx_http_brix_webdav_create_loc_conf(), and ngx_http_s3_create_loc_conf().
brix_acc_http_merge_conf()
void brix_acc_http_merge_conf (brix_acc_http_t * conf, brix_acc_http_t * prev)
Definition at line 177 of file config.c.
References brix_acc_http_t::audit, brix_acc_http_t::authdb, BRIX_AUTHDB_AUDIT_NONE, BRIX_AUTHDB_FORMAT_NATIVE, brix_acc_http_t::encoding, brix_acc_http_t::format, brix_acc_http_t::gidlifetime, brix_acc_http_t::gidretran, brix_acc_http_t::nisdomain, brix_acc_http_t::pgo, brix_acc_http_t::refresh, brix_acc_http_t::resolve_hosts, and brix_acc_http_t::spacechar.
Referenced by s3_merge_scalars(), and webdav_merge_base_conf().
brix_acc_named_find()
brix_acc_cap_t * brix_acc_named_find (brix_acc_named_t * list, const char * name)
Definition at line 23 of file tables.c.
References brix_acc_named_t::caps, brix_acc_named_t::name, name, and brix_acc_named_t::next.
Referenced by acc_build_caps(), acc_grant_host(), acc_grant_tuples(), acc_grant_user(), and acc_named_is_dup().
brix_acc_resolve_peer()
const char * brix_acc_resolve_peer (struct sockaddr * sa, socklen_t salen, char * buf, size_t buflen)
Definition at line 58 of file resolve.c.
References acc_dns_breaker, ACC_DNS_COOLDOWN_SECS, acc_dns_monotonic_ms(), ACC_DNS_SLOW_MS, ACC_DNS_TRIP_COUNT, and BRIX_RESIL_METRIC_INC.
Referenced by brix_acc_gate_host(), brix_handle_host_auth(), s3_acc_check(), and webdav_acc_check().
brix_acc_set_group_resolvers()
void brix_acc_set_group_resolvers (brix_acc_unixgrp_fn ug, brix_acc_netgrp_fn ng)
Definition at line 29 of file access.c.
References acc_netgrp_member, and acc_unixgrp_resolver.
Referenced by brix_acc_groups_init().
brix_acc_tables_free()
void brix_acc_tables_free (brix_acc_tables_t * tabs)
Definition at line 59 of file tables.c.
References brix_acc_tables_t::pool.
Referenced by brix_acc_http_refresh_handler(), and brix_acc_refresh_handler().
Variable Documentation
brix_acc_audit_modes
ngx_conf_enum_t brix_acc_audit_modes[] extern
Definition at line 31 of file config.c.
Referenced by brix_acc_http_set_audit().
brix_acc_format_modes
ngx_conf_enum_t brix_acc_format_modes[] extern
Definition at line 25 of file config.c.
Referenced by brix_acc_http_set_format().