nginx-xrootd: src/observability/accesslog/access_log.c File Reference
access_log.c File Reference
#include "core/ngx_brix_module.h"
#include "core/compat/cstr.h"
#include "observability/accesslog/access_log.h"
#include "observability/accesslog/access_log_internal.h"
#include "observability/sesslog/sesslog_ngx.h"
#include <arpa/inet.h>
#include <string.h>
#include <time.h>
Data Structures
struct brix_access_authlabel_t
struct brix_alog_record_t
struct brix_access_raw_t
Macros
#define BRIX_ALOG_BUF_SIZE (64 * 1024)
Functions
void brix_access_log_flush (void)
static void brix_alog_timer_handler (ngx_event_t *ev)
size_t brix_access_log_time_prefix (char *dst, size_t dst_size)
void brix_alog_emit (ngx_fd_t fd, const char *line, size_t n)
static void brix_access_resolve_identity (brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *conf, const char **authmethod, const char **identity)
static void brix_access_format_time (char *dst, size_t dst_size)
static void brix_access_sanitize_fields (brix_alog_record_t *rec, const brix_access_raw_t *raw)
static int brix_access_format_line (const brix_alog_record_t *rec, char *line, size_t line_size)
void brix_log_access (brix_ctx_t *ctx, ngx_connection_t *c, const char *verb, const char *path, const char *detail, ngx_uint_t xrd_ok, uint16_t errcode, const char *errmsg, size_t bytes)
Variables
static u_char brix_alog_buf [(64 *1024)]
static size_t brix_alog_len
static ngx_fd_t brix_alog_fd = NGX_INVALID_FILE
static ngx_event_t brix_alog_timer
static ngx_uint_t brix_alog_timer_set
static const brix_access_authlabel_t brix_access_authlabels []
Macro Definition Documentation
BRIX_ALOG_BUF_SIZE
#define BRIX_ALOG_BUF_SIZE (64 * 1024)
Definition at line 47 of file access_log.c.
Function Documentation
brix_access_format_line()
static int brix_access_format_line (const brix_alog_record_t * rec, char * line, size_t line_size) static
Definition at line 297 of file access_log.c.
References brix_alog_record_t::authmethod, brix_alog_record_t::bytes, brix_alog_record_t::duration_ms, brix_alog_record_t::safe_client_ip, brix_alog_record_t::safe_detail, brix_alog_record_t::safe_errmsg, brix_alog_record_t::safe_identity, brix_alog_record_t::safe_path, brix_alog_record_t::safe_verb, brix_alog_record_t::timebuf, and brix_alog_record_t::xrd_ok.
Referenced by brix_log_access().
brix_access_format_time()
static void brix_access_format_time (char * dst, size_t dst_size) static
Definition at line 232 of file access_log.c.
Referenced by brix_log_access().
brix_access_log_flush()
void brix_access_log_flush (void)
Definition at line 56 of file access_log.c.
References brix_alog_buf, brix_alog_fd, and brix_alog_len.
Referenced by brix_alog_emit(), brix_alog_timer_handler(), brix_on_disconnect(), and brix_sesslog_shutdown_flush().
brix_access_log_time_prefix()
size_t brix_access_log_time_prefix (char * dst, size_t dst_size)
Definition at line 80 of file access_log.c.
Referenced by brix_sess_emit().
brix_access_resolve_identity()
static void brix_access_resolve_identity (brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * conf, const char ** authmethod, const char ** identity) static
Definition at line 205 of file access_log.c.
References brix_access_authlabel_t::auth, brix_access_authlabels, brix_ctx_login_t::dn, brix_access_authlabel_t::label, and brix_ctx_t::login.
Referenced by brix_log_access().
brix_access_sanitize_fields()
static void brix_access_sanitize_fields (brix_alog_record_t * rec, const brix_access_raw_t * raw) static
Definition at line 272 of file access_log.c.
References brix_sanitize_log_string(), brix_access_raw_t::client_ip, brix_access_raw_t::detail, brix_access_raw_t::errmsg, brix_access_raw_t::identity, brix_access_raw_t::path, brix_alog_record_t::safe_client_ip, brix_alog_record_t::safe_detail, brix_alog_record_t::safe_errmsg, brix_alog_record_t::safe_identity, brix_alog_record_t::safe_path, brix_alog_record_t::safe_verb, and brix_access_raw_t::verb.
Referenced by brix_log_access().
brix_alog_emit()
void brix_alog_emit (ngx_fd_t fd, const char * line, size_t n)
Definition at line 110 of file access_log.c.
References brix_access_log_flush(), brix_alog_buf, BRIX_ALOG_BUF_SIZE, brix_alog_fd, brix_alog_len, brix_alog_timer, brix_alog_timer_handler(), brix_alog_timer_set, brix_maint_timer_conn, and ngx_memcpy.
Referenced by brix_log_access(), and brix_sess_emit().
brix_alog_timer_handler()
static void brix_alog_timer_handler (ngx_event_t * ev) static
Definition at line 65 of file access_log.c.
References brix_access_log_flush(), and brix_alog_timer_set.
Referenced by brix_alog_emit().
brix_log_access()
void brix_log_access (brix_ctx_t * ctx, ngx_connection_t * c, const char * verb, const char * path, const char * detail, ngx_uint_t xrd_ok, uint16_t errcode, const char * errmsg, size_t bytes)
Definition at line 318 of file access_log.c.
References brix_alog_record_t::authmethod, brix_access_format_line(), brix_access_format_time(), brix_access_maybe_sesslog(), brix_access_resolve_identity(), brix_access_sanitize_fields(), brix_alog_emit(), brix_str_cbuf(), brix_alog_record_t::bytes, c, brix_access_raw_t::client_ip, brix_alog_record_t::duration_ms, ngx_stream_brix_module, brix_ctx_t::req_start, brix_ctx_t::session, brix_alog_record_t::timebuf, brix_access_event_t::verb, and brix_alog_record_t::xrd_ok.
Referenced by baq_root_done(), brix_auth_gate_deny(), brix_auth_gate_op(), brix_cache_fill_composed_done(), brix_cache_fill_done(), brix_ckscan_aio_done(), brix_ckscan_sync(), brix_cksum_aio_done(), brix_close_log_access(), brix_compressed_account(), brix_dirlist_aio_done(), brix_dirlist_check_redirect(), brix_dirlist_send_final(), brix_disconnect_log_open_files(), brix_handle_bind(), brix_handle_locate(), brix_handle_prepare(), brix_handle_readlink(), brix_handle_sigver(), brix_handle_stat(), brix_handle_statx(), brix_handle_token_auth(), brix_handle_truncate(), brix_handle_writev(), brix_login_respond_anon(), brix_login_respond_authenticated(), brix_on_disconnect(), brix_open_map_open_error(), brix_open_mode_guard(), brix_open_read_resolve(), brix_open_residency_gate(), brix_open_send_response(), brix_open_stage_backpressure(), brix_pgread_aio_done(), brix_pgread_send_response(), brix_prepare_handle_cancel(), brix_prepare_send_fail(), brix_qcksum_compute_sync(), brix_qcksum_manager_bounce(), brix_qcksum_open(), brix_query_cksum_handle(), brix_query_finfo(), brix_query_fsinfo(), brix_query_prep_status(), brix_query_space(), brix_query_stats(), brix_query_xattr(), brix_read_serve_sendfile(), brix_readv_execute_sync(), brix_reject_bound_nonread_file_op(), brix_reject_dotdot_path(), brix_resolve_op_path(), brix_staged_append(), brix_tpc_prepare_pull(), brix_tpc_start_pull(), brix_write_aio_log(), brix_write_compressed(), brix_write_require_pgwrite(), brix_writev_write_aio_done(), ckp_query(), ckp_xeq_pgwrite(), ckp_xeq_pgwrite_drain(), ckp_xeq_writev(), gsi_cert_deny(), locate_check_data_server(), locate_try_dynamic(), locate_try_manager(), locate_try_manager_map(), mv_fail(), pgwrite_execute_sync(), pgwrite_parse_validate(), pgwrite_register_bad_pages(), prepare_dispatch_special(), read_finish_buffered(), read_serve_windowed(), read_validate_req(), stat_manager_route(), tokenauth_extract(), tpc_done_reply_open(), tpc_done_reply_sync(), tpc_done_sync_fail(), tpc_handle_dest(), tpc_prepare_check_preconditions(), writev_reply(), zip_open_error(), and zip_send_open_reply().
Variable Documentation
brix_access_authlabels
const brix_access_authlabel_t brix_access_authlabels[] static
Initial value:
= {
    {  1  ,  "gsi" },
    {  4  ,  "sss" },
    {  5  , "unix" },
    {  6  , "krb5" },
}
Definition at line 165 of file access_log.c.
Referenced by brix_access_resolve_identity().
brix_alog_buf
u_char brix_alog_buf[(64 *1024)] static
Definition at line 49 of file access_log.c.
Referenced by brix_access_log_flush(), and brix_alog_emit().
brix_alog_fd
ngx_fd_t brix_alog_fd = NGX_INVALID_FILE static
Definition at line 51 of file access_log.c.
Referenced by brix_access_log_flush(), and brix_alog_emit().
brix_alog_len
size_t brix_alog_len static
Definition at line 50 of file access_log.c.
Referenced by brix_access_log_flush(), and brix_alog_emit().
brix_alog_timer
ngx_event_t brix_alog_timer static
Definition at line 52 of file access_log.c.
Referenced by brix_alog_emit().
brix_alog_timer_set
ngx_uint_t brix_alog_timer_set static
Definition at line 53 of file access_log.c.
Referenced by brix_alog_emit(), and brix_alog_timer_handler().