nginx-xrootd: src/observability/accesslog/access_log_internal.h File Reference
access_log_internal.h File Reference
#include "core/ngx_brix_module.h"
Data Structures
struct brix_access_event_t
Functions
void brix_access_maybe_sesslog (brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *conf, const brix_access_event_t *ev)
Function Documentation
brix_access_maybe_sesslog()
void brix_access_maybe_sesslog (brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * conf, const brix_access_event_t * ev)
Definition at line 257 of file access_log_sesslog.c.
References brix_access_sesslog_auth(), brix_access_sesslog_namespace(), brix_access_streq(), brix_ctx_t::sess, and brix_access_event_t::verb.
Referenced by brix_log_access().