nginx-xrootd: src/observability/accesslog/access_log_sesslog.c File Reference
access_log_sesslog.c File Reference
#include "core/ngx_brix_module.h"
#include "core/compat/cstr.h"
#include "observability/accesslog/access_log.h"
#include "observability/accesslog/access_log_internal.h"
#include "observability/sesslog/sesslog_ngx.h"
#include <string.h>
Data Structures
struct brix_access_verb_mode_t
Functions
static ngx_flag_t brix_access_streq (const char *a, const char *b)
static ngx_flag_t brix_access_contains (const char *s, const char *needle)
static brix_sess_am_t brix_access_sess_auth_method (brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *conf, const char *detail)
static const char * brix_access_sess_auth_err (uint16_t errcode, const char *errmsg, char *scratch, size_t scratch_size)
static brix_sess_mode_t brix_access_open_mode (const char *detail)
static ngx_flag_t brix_access_sess_mode (const char *verb, const char *detail, brix_sess_mode_t *mode)
static void brix_access_sesslog_auth (brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *conf, const brix_access_event_t *ev)
static void brix_access_sesslog_namespace (brix_ctx_t *ctx, const brix_access_event_t *ev)
void brix_access_maybe_sesslog (brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *conf, const brix_access_event_t *ev)
Variables
static const brix_access_verb_mode_t brix_access_verb_modes []
Function Documentation
brix_access_contains()
static ngx_flag_t brix_access_contains (const char * s, const char * needle) static
Definition at line 28 of file access_log_sesslog.c.
References s.
Referenced by brix_access_open_mode(), and brix_access_sess_auth_err().
brix_access_maybe_sesslog()
void brix_access_maybe_sesslog (brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * conf, const brix_access_event_t * ev)
Definition at line 257 of file access_log_sesslog.c.
References brix_access_sesslog_auth(), brix_access_sesslog_namespace(), brix_access_streq(), brix_ctx_t::sess, and brix_access_event_t::verb.
Referenced by brix_log_access().
brix_access_open_mode()
static brix_sess_mode_t brix_access_open_mode (const char * detail) static
Definition at line 150 of file access_log_sesslog.c.
References brix_access_contains(), BRIX_SESS_MODE_READ, and BRIX_SESS_MODE_WRITE.
Referenced by brix_access_sess_mode().
brix_access_sess_auth_err()
static const char * brix_access_sess_auth_err (uint16_t errcode, const char * errmsg, char * scratch, size_t scratch_size) static
Definition at line 80 of file access_log_sesslog.c.
References brix_access_contains(), and brix_sesslog_err_from_kxr().
Referenced by brix_access_sesslog_auth().
brix_access_sess_auth_method()
static brix_sess_am_t brix_access_sess_auth_method (brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * conf, const char * detail) static
Definition at line 41 of file access_log_sesslog.c.
References brix_ctx_token_t::auth, brix_access_streq(), BRIX_AUTH_NONE, brix_sess_am_from_stream_auth(), BRIX_SESS_AM_GSI, BRIX_SESS_AM_HOST, BRIX_SESS_AM_KRB5, BRIX_SESS_AM_PWD, BRIX_SESS_AM_SSS, BRIX_SESS_AM_TOKEN, BRIX_SESS_AM_UNIX, and brix_ctx_t::token.
Referenced by brix_access_sesslog_auth().
brix_access_sess_mode()
static ngx_flag_t brix_access_sess_mode (const char * verb, const char * detail, brix_sess_mode_t * mode) static
Definition at line 171 of file access_log_sesslog.c.
References brix_access_open_mode(), brix_access_streq(), brix_access_verb_modes, and brix_access_verb_mode_t::mode.
Referenced by brix_access_sesslog_namespace().
brix_access_sesslog_auth()
static void brix_access_sesslog_auth (brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * conf, const brix_access_event_t * ev) static
Definition at line 204 of file access_log_sesslog.c.
References brix_access_sess_auth_err(), brix_access_sess_auth_method(), brix_sess_auth(), brix_access_event_t::detail, brix_ctx_login_t::dn, brix_access_event_t::errcode, brix_access_event_t::errmsg, brix_ctx_t::login, brix_ctx_login_t::primary_vo, brix_ctx_t::sess, and brix_access_event_t::xrd_ok.
Referenced by brix_access_maybe_sesslog().
brix_access_sesslog_namespace()
static void brix_access_sesslog_namespace (brix_ctx_t * ctx, const brix_access_event_t * ev) static
Definition at line 230 of file access_log_sesslog.c.
References brix_access_sess_mode(), brix_sess_attempt(), brix_sess_result(), brix_sesslog_err_from_kxr(), brix_access_event_t::detail, brix_access_event_t::errcode, brix_access_event_t::path, brix_ctx_t::sess, brix_access_event_t::verb, and brix_access_event_t::xrd_ok.
Referenced by brix_access_maybe_sesslog().
brix_access_streq()
static ngx_flag_t brix_access_streq (const char * a, const char * b) static
Definition at line 22 of file access_log_sesslog.c.
Referenced by brix_access_maybe_sesslog(), brix_access_sess_auth_method(), and brix_access_sess_mode().
Variable Documentation
brix_access_verb_modes
const brix_access_verb_mode_t brix_access_verb_modes[] static
Initial value:
= {
    { "STAT",     BRIX_SESS_MODE_META },
    { "STATX",    BRIX_SESS_MODE_META },
    { "LOCATE",   BRIX_SESS_MODE_META },
    { "QUERY",    BRIX_SESS_MODE_META },
    { "SET",      BRIX_SESS_MODE_META },
    { "READLINK", BRIX_SESS_MODE_META },
    { "DIRLIST",  BRIX_SESS_MODE_LIST },
    { "RM",       BRIX_SESS_MODE_DELETE },
    { "RMDIR",    BRIX_SESS_MODE_DELETE },
    { "DELETE",   BRIX_SESS_MODE_DELETE },
    { "MKDIR",    BRIX_SESS_MODE_WRITE },
    { "MV",       BRIX_SESS_MODE_WRITE },
    { "TRUNCATE", BRIX_SESS_MODE_WRITE },
    { "CHMOD",    BRIX_SESS_MODE_WRITE },
    { "SETATTR",  BRIX_SESS_MODE_WRITE },
    { "LINK",     BRIX_SESS_MODE_WRITE },
    { "SYMLINK",  BRIX_SESS_MODE_WRITE },
}
Definition at line 121 of file access_log_sesslog.c.
Referenced by brix_access_sess_mode().