nginx-xrootd: src/observability/accesslog/access_log.h File Reference
access_log.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
Functions
void brix_alog_emit (ngx_fd_t fd, const char *line, size_t n)
void brix_access_log_flush (void)
size_t brix_access_log_time_prefix (char *dst, size_t dst_size)
Function Documentation
brix_access_log_flush()
void brix_access_log_flush (void)
Definition at line 55 of file access_log.c.
Referenced by brix_alog_emit(), and brix_alog_timer_handler().
brix_access_log_time_prefix()
size_t brix_access_log_time_prefix (char * dst, size_t dst_size)
Definition at line 79 of file access_log.c.
Referenced by brix_sess_emit().
brix_alog_emit()
void brix_alog_emit (ngx_fd_t fd, const char * line, size_t n)
Definition at line 105 of file access_log.c.
References brix_access_log_flush(), brix_alog_buf, BRIX_ALOG_BUF_SIZE, brix_alog_fd, brix_alog_len, brix_alog_timer, brix_alog_timer_handler(), brix_alog_timer_set, and ngx_memcpy.
Referenced by brix_log_access(), and brix_sess_emit().