nginx-xrootd: src/net/cms/action_log.h File Reference
action_log.h File Reference
Functions
static void brix_cms_log_action (ngx_log_t *log, const char *op, const char *peer, const char *dir, const char *path, ngx_int_t ok, const char *detail)
static void brix_cms_log_action_hp (ngx_log_t *log, const char *op, const char *host, int port, const char *dir, const char *path, ngx_int_t ok, const char *detail)
Function Documentation
brix_cms_log_action()
static void brix_cms_log_action (ngx_log_t * log, const char * op, const char * peer, const char * dir, const char * path, ngx_int_t ok, const char * detail) inline static
Definition at line 28 of file action_log.h.
References log, and op.
Referenced by brix_cms_log_action_hp(), cms_frame_disc(), cms_frame_forward(), cms_frame_redirect(), cms_frame_state(), cms_frame_status(), ngx_brix_cms_timer(), and ngx_brix_cms_write_handler().
brix_cms_log_action_hp()
static void brix_cms_log_action_hp (ngx_log_t * log, const char * op, const char * host, int port, const char * dir, const char * path, ngx_int_t ok, const char * detail) inline static
Definition at line 43 of file action_log.h.
References brix_cms_log_action(), host, log, op, and port.
Referenced by cms_srv_complete_login(), cms_srv_frame_avail(), cms_srv_frame_disc(), cms_srv_frame_gone(), cms_srv_frame_have(), cms_srv_frame_load(), cms_srv_frame_login(), and cms_srv_frame_status().