nginx-xrootd: client/lib/core/aio/aio.c File Reference
aio.c File Reference
#include "aio_internal.h"
Functions
void * rc_worker_main (void *arg)
void loop_push_cmd (brix_loop *l, cmd *c)
void loop_run_control (brix_loop *l, cmd_type type, brix_aconn *ac)
void loop_drain_commands (brix_loop *l)
int loop_process_timeouts (brix_loop *l)
void * loop_thread (void *arg)
brix_loop * brix_loop_create_fail (brix_loop *l)
int brix_loop_want_uring (void)
brix_loop * brix_loop_create (brix_status *st)
void brix_loop_destroy (brix_loop *l)
brix_aconn * brix_aconn_attach (brix_loop *l, brix_conn *conn, brix_status *st)
void brix_aconn_close (brix_aconn *ac)
void brix_aconn_set_resilience (brix_aconn *ac, int max_stall_ms, int keepalive_ms, int max_retries)
int brix_aio_submit_ex (brix_aconn *ac, const void *hdr24, const void *payload, uint32_t plen, const brix_aio_opts *opts, brix_aio_cb cb, void *ctx, brix_status *st)
int brix_aio_submit (brix_aconn *ac, const void *hdr24, const void *payload, uint32_t plen, brix_aio_cb cb, void *ctx, int deadline_ms, brix_status *st)
void call_cb (void *ctx, int rc, uint16_t kxr, uint8_t *body, uint32_t blen, const brix_status *st)
int brix_aio_call_ex (brix_aconn *ac, const void *hdr24, const void *payload, uint32_t plen, const brix_aio_opts *opts, uint16_t *kxr, uint8_t **body, uint32_t *blen, brix_status *st)
int brix_aio_call (brix_aconn *ac, const void *hdr24, const void *payload, uint32_t plen, uint16_t *kxr, uint8_t **body, uint32_t *blen, int deadline_ms, brix_status *st)
Function Documentation
brix_aconn_attach()
brix_aconn * brix_aconn_attach (brix_loop * l, brix_conn * conn, brix_status * st)
Definition at line 375 of file aio.c.
References ACONN_ALIVE, brix_mono_ns(), brix_status_set(), CMD_ADD_ACONN, brix_aconn::conn, brix_aconn::dead, brix_aconn::def_retries, brix_io::fd, brix_aconn::fd, brix_aconn::inflight, brix_conn::io, brix_aconn::keepalive_ms, brix_aconn::last_activity_ns, brix_aconn::loop, loop_run_control(), brix_aconn::max_stall_ms, brix_aconn::next_sid, brix_conn::signing_active, reqmap::slots, brix_io::ssl, brix_aconn::ssl, brix_aconn::state, brix_aconn::uring_slot, XRDC_EAUTH, XRDC_EPROTO, XRDC_ESOCK, and XRDC_EUSAGE.
Referenced by brix_mgr_create(), and mgr_ensure_slot().
brix_aconn_close()
void brix_aconn_close (brix_aconn * ac)
Definition at line 426 of file aio.c.
References CMD_CLOSE_ACONN, brix_aconn::loop, and loop_run_control().
Referenced by mgr_free().
brix_aconn_set_resilience()
void brix_aconn_set_resilience (brix_aconn * ac, int max_stall_ms, int keepalive_ms, int max_retries)
Definition at line 437 of file aio.c.
References brix_aconn::def_retries, brix_aconn::keepalive_ms, and brix_aconn::max_stall_ms.
Referenced by brix_mgr_create(), and mgr_ensure_slot().
brix_aio_call()
int brix_aio_call (brix_aconn * ac, const void * hdr24, const void * payload, uint32_t plen, uint16_t * kxr, uint8_t ** body, uint32_t * blen, int deadline_ms, brix_status * st)
Definition at line 572 of file aio.c.
References brix_aio_call_ex().
Referenced by brix_mfile_close(), and brix_mfile_sync().
brix_aio_call_ex()
int brix_aio_call_ex (brix_aconn * ac, const void * hdr24, const void * payload, uint32_t plen, const brix_aio_opts * opts, uint16_t * kxr, uint8_t ** body, uint32_t * blen, brix_status * st)
Definition at line 524 of file aio.c.
References call_wait::blen, call_wait::body, brix_aio_submit_ex(), call_cb(), call_wait::cv, call_wait::done, call_wait::kxr, call_wait::mx, call_wait::rc, and call_wait::st.
Referenced by brix_aio_call(), brix_mfile_pread(), brix_mfile_pwrite(), brix_mgr_call(), and mfile_do_open().
brix_aio_submit()
int brix_aio_submit (brix_aconn * ac, const void * hdr24, const void * payload, uint32_t plen, brix_aio_cb cb, void * ctx, int deadline_ms, brix_status * st)
Definition at line 493 of file aio.c.
References brix_aio_submit_ex().
brix_aio_submit_ex()
int brix_aio_submit_ex (brix_aconn * ac, const void * hdr24, const void * payload, uint32_t plen, const brix_aio_opts * opts, brix_aio_cb cb, void * ctx, brix_status * st)
Definition at line 453 of file aio.c.
References brix_status_set(), c, CMD_SUBMIT, brix_aio_opts::deadline_ms, brix_aconn::loop, loop_push_cmd(), brix_aio_opts::max_retries, brix_aio_opts::retry_safe, XRD_REQUEST_HDR_LEN, XRDC_EPROTO, and XRDC_EUSAGE.
Referenced by brix_aio_call_ex(), and brix_aio_submit().
brix_loop_create()
brix_loop * brix_loop_create (brix_status * st)
Definition at line 325 of file aio.c.
References brix_loop_create_fail(), brix_loop_want_uring(), brix_status_set(), brix_loop::cq_lock, brix_loop::epfd, brix_loop::evfd, io_engine_setup(), loop_thread(), brix_loop::thread, brix_loop::thread_ok, brix_loop::use_uring, XRDC_EPROTO, and XRDC_ESOCK.
Referenced by brix_mgr_create().
brix_loop_create_fail()
brix_loop * brix_loop_create_fail (brix_loop * l)
Definition at line 296 of file aio.c.
References brix_loop::cq_lock, and io_engine_teardown().
Referenced by brix_loop_create().
brix_loop_destroy()
void brix_loop_destroy (brix_loop * l)
Definition at line 350 of file aio.c.
References c, CMD_STOP, brix_loop::cq_lock, brix_loop::evfd, io_engine_teardown(), loop_push_cmd(), brix_loop::stop, brix_loop::thread, brix_loop::thread_ok, and cmd::type.
Referenced by mgr_free().
brix_loop_want_uring()
int brix_loop_want_uring (void)
Definition at line 310 of file aio.c.
References brix_uring_available().
Referenced by brix_loop_create().
call_cb()
void call_cb (void * ctx, int rc, uint16_t kxr, uint8_t * body, uint32_t blen, const brix_status * st)
Definition at line 505 of file aio.c.
References call_wait::blen, call_wait::body, call_wait::cv, call_wait::done, call_wait::kxr, call_wait::mx, call_wait::rc, and call_wait::st.
Referenced by brix_aio_call_ex().
loop_drain_commands()
void loop_drain_commands (brix_loop * l)
Definition at line 120 of file aio.c.
References aconn_destroy(), aconn_submit_cmd(), brix_loop::aconns, c, CMD_ADD_ACONN, CMD_CLOSE_ACONN, CMD_STOP, CMD_SUBMIT, brix_loop::cq_head, brix_loop::cq_lock, brix_loop::cq_tail, brix_aconn::dead, io_engine_arm(), brix_aconn::next, cmd::next, and brix_loop::stop.
Referenced by loop_thread().
loop_process_timeouts()
int loop_process_timeouts (brix_loop * l)
Definition at line 169 of file aio.c.
References ACONN_ALIVE, aconn_on_transport_error(), ACONN_RECONNECTING, brix_loop::aconns, AIO_TICK_MS, areq_complete(), brix_mono_ns(), brix_status_set(), brix_areq::deadline_ns, brix_areq::is_ping, brix_areq::pend_next, REQMAP_TOMB, and XRDC_ESOCK.
Referenced by loop_thread().
loop_push_cmd()
void loop_push_cmd (brix_loop * l, cmd * c)
Definition at line 73 of file aio.c.
References c, brix_loop::cq_head, brix_loop::cq_lock, brix_loop::cq_tail, brix_loop::evfd, and cmd::next.
Referenced by brix_aio_submit_ex(), brix_loop_destroy(), and loop_run_control().
loop_run_control()
void loop_run_control (brix_loop * l, cmd_type type, brix_aconn * ac)
Definition at line 93 of file aio.c.
References c, loop_push_cmd(), and cmd::type.
Referenced by brix_aconn_attach(), and brix_aconn_close().
loop_thread()
void * loop_thread (void * arg)
Definition at line 244 of file aio.c.
References aconn_destroy(), aconn_handle_io(), aconn_maybe_ping(), aconn_poll_reconnect(), brix_loop::aconns, AIO_MAXEV, AIO_TICK_MS, brix_loop::evfd, io_engine_wait(), loop_drain_commands(), loop_process_timeouts(), read(), and brix_loop::stop.
Referenced by brix_loop_create().
rc_worker_main()
void * rc_worker_main (void * arg)
Definition at line 13 of file aio.c.
References brix_mono_ns(), brix_reconnect(), brix_status_set(), brix_aconn::conn, brix_loop::evfd, brix_conn::host, brix_aconn::loop, brix_conn::port, brix_aconn::rc_finished, brix_aconn::rc_result, brix_aconn::rc_st, brix_aconn::reconnect_deadline_ns, and XRDC_ESOCK.
Referenced by aconn_on_transport_error().