nginx-xrootd: client/lib/core/aio/aio_conn.c File Reference
aio_conn.c File Reference
#include "aio_internal.h"
Functions
void aconn_update_epoll (brix_aconn *ac)
void aconn_drain_inflight (brix_aconn *ac, const brix_status *st)
void aconn_pending_fail_all (brix_aconn *ac, const brix_status *st)
void aconn_on_transport_error (brix_aconn *ac, const brix_status *st)
void aconn_reconnect_succeeded (brix_aconn *ac)
void aconn_poll_reconnect (brix_aconn *ac)
void aconn_ping_cb (void *ctx, int rc, uint16_t kxr, uint8_t *body, uint32_t blen, const brix_status *st)
void aconn_maybe_ping (brix_aconn *ac)
void aconn_destroy (brix_aconn *ac)
uint16_t aconn_alloc_sid (brix_aconn *ac)
void aconn_issue_areq (brix_aconn *ac, brix_areq *r)
uint64_t aconn_deadline_ns (brix_aconn *ac, int deadline_ms)
void aconn_submit_cmd (brix_aconn *ac, cmd *c)
Function Documentation
aconn_alloc_sid()
uint16_t aconn_alloc_sid (brix_aconn * ac)
Definition at line 264 of file aio_conn.c.
References brix_aconn::inflight, brix_aconn::next_sid, reqmap_get(), and s.
Referenced by aconn_issue_areq().
aconn_deadline_ns()
uint64_t aconn_deadline_ns (brix_aconn * ac, int deadline_ms)
Definition at line 316 of file aio_conn.c.
References aconn_rto_ns(), brix_mono_ns(), and brix_aconn::max_stall_ms.
Referenced by aconn_submit_cmd().
aconn_destroy()
void aconn_destroy (brix_aconn * ac)
Definition at line 232 of file aio_conn.c.
References aconn_drain_inflight(), aconn_pending_fail_all(), brix_loop::aconns, brix_status_set(), brix_aconn::dead, brix_aconn::inflight, io_engine_del(), brix_aconn::loop, brix_aconn::next, brix_aconn::rbuf, brix_aconn::rc_thread, brix_aconn::rc_thread_live, reqmap::slots, brix_aconn::wbuf, xbuf_free(), and XRDC_ESOCK.
Referenced by loop_drain_commands(), and loop_thread().
aconn_drain_inflight()
void aconn_drain_inflight (brix_aconn * ac, const brix_status * st)
Definition at line 26 of file aio_conn.c.
References areq_complete(), reqmap::cap, reqmap::count, brix_aconn::inflight, brix_status::kxr, REQMAP_TOMB, reqmap::slots, and reqmap::tomb.
Referenced by aconn_destroy(), and aconn_on_transport_error().
aconn_issue_areq()
void aconn_issue_areq (brix_aconn * ac, brix_areq * r)
Definition at line 287 of file aio_conn.c.
References aconn_alloc_sid(), aconn_do_write(), aconn_update_epoll(), areq_complete(), brix_mono_ns(), brix_status_set(), brix_aconn::dead, brix_areq::hdr, brix_aconn::inflight, brix_areq::payload, brix_areq::plen, reqmap_put(), brix_areq::sid, brix_areq::submit_ns, brix_aconn::wbuf, xbuf_append(), XRD_REQUEST_HDR_LEN, and XRDC_EPROTO.
Referenced by aconn_maybe_ping(), aconn_reconnect_succeeded(), and aconn_submit_cmd().
aconn_maybe_ping()
void aconn_maybe_ping (brix_aconn * ac)
Definition at line 200 of file aio_conn.c.
References ACONN_ALIVE, aconn_issue_areq(), aconn_ping_cb(), aconn_rto_ns(), brix_mono_ns(), brix_areq::cb, brix_areq::ctx, brix_areq::deadline_ns, brix_aconn::def_retries, brix_areq::hdr, brix_areq::is_ping, brix_aconn::keepalive_ms, kXR_ping, brix_aconn::last_activity_ns, brix_aconn::ping_inflight, brix_areq::retries_left, brix_areq::retry_safe, and brix_aconn::state.
Referenced by loop_thread().
aconn_on_transport_error()
void aconn_on_transport_error (brix_aconn * ac, const brix_status * st)
Definition at line 68 of file aio_conn.c.
References ACONN_ALIVE, ACONN_DEAD, aconn_drain_inflight(), aconn_pending_fail_all(), ACONN_RECONNECTING, areq_complete(), brix_mono_ns(), reqmap::cap, reqmap::count, brix_aconn::dead, brix_areq::deadline_ns, brix_aconn::inflight, io_engine_del(), brix_status::kxr, xbuf::len, brix_aconn::loop, brix_aconn::max_stall_ms, brix_areq::pend_next, brix_aconn::pending, brix_aconn::ping_inflight, brix_aconn::rbuf, brix_aconn::rc_thread, brix_aconn::rc_thread_live, rc_worker_main(), brix_aconn::reconnect_deadline_ns, REQMAP_TOMB, brix_areq::retries_left, brix_areq::retry_safe, reqmap::slots, xbuf::start, brix_aconn::state, brix_aconn::tls_want_read_on_write, brix_aconn::tls_want_write_on_read, reqmap::tomb, and brix_aconn::wbuf.
Referenced by aconn_do_read(), aconn_do_write(), aconn_handle_io(), aconn_parse(), aconn_read_plain(), aconn_read_tls(), and timeouts_scan_conn().
aconn_pending_fail_all()
void aconn_pending_fail_all (brix_aconn * ac, const brix_status * st)
Definition at line 52 of file aio_conn.c.
References areq_complete(), brix_status::kxr, brix_areq::pend_next, and brix_aconn::pending.
Referenced by aconn_destroy(), aconn_on_transport_error(), aconn_poll_reconnect(), and aconn_reconnect_succeeded().
aconn_ping_cb()
void aconn_ping_cb (void * ctx, int rc, uint16_t kxr, uint8_t * body, uint32_t blen, const brix_status * st)
Definition at line 188 of file aio_conn.c.
References brix_aconn::ping_inflight.
Referenced by aconn_maybe_ping().
aconn_poll_reconnect()
void aconn_poll_reconnect (brix_aconn * ac)
Definition at line 162 of file aio_conn.c.
References ACONN_DEAD, aconn_pending_fail_all(), aconn_reconnect_succeeded(), ACONN_RECONNECTING, brix_aconn::rc_finished, brix_aconn::rc_result, brix_aconn::rc_st, brix_aconn::rc_thread, brix_aconn::rc_thread_live, and brix_aconn::state.
Referenced by loop_thread().
aconn_reconnect_succeeded()
void aconn_reconnect_succeeded (brix_aconn * ac)
Definition at line 121 of file aio_conn.c.
References ACONN_ALIVE, ACONN_DEAD, aconn_issue_areq(), aconn_pending_fail_all(), brix_mono_ns(), brix_status_set(), brix_aconn::conn, brix_aconn::dead, brix_io::fd, brix_aconn::fd, brix_conn::io, io_engine_arm(), brix_aconn::last_activity_ns, brix_aconn::loop, brix_areq::pend_next, brix_aconn::pending, brix_aconn::reconnect_deadline_ns, brix_io::ssl, brix_aconn::ssl, brix_aconn::state, and XRDC_ESOCK.
Referenced by aconn_poll_reconnect().
aconn_submit_cmd()
void aconn_submit_cmd (brix_aconn * ac, cmd * c)
Definition at line 340 of file aio_conn.c.
References ACONN_DEAD, aconn_deadline_ns(), aconn_issue_areq(), ACONN_RECONNECTING, brix_mono_ns(), brix_status_set(), c, brix_areq::cb, brix_areq::ctx, brix_areq::deadline_ns, brix_aconn::def_retries, brix_areq::hdr, brix_aconn::max_stall_ms, brix_areq::payload, brix_areq::pend_next, brix_aconn::pending, brix_areq::plen, brix_areq::retries_left, brix_areq::retry_safe, brix_aconn::state, XRD_REQUEST_HDR_LEN, XRDC_EPROTO, and XRDC_ESOCK.
Referenced by loop_drain_commands().
aconn_update_epoll()
void aconn_update_epoll (brix_aconn * ac)
Definition at line 10 of file aio_conn.c.
References brix_aconn::epoll_events, io_engine_arm(), xbuf::len, brix_aconn::loop, xbuf::start, brix_aconn::tls_want_write_on_read, and brix_aconn::wbuf.
Referenced by aconn_handle_io(), and aconn_issue_areq().