nginx-xrootd: client/lib/core/aio/aio_io.c File Reference
aio_io.c File Reference
#include "aio_internal.h"
Macros
#define AIO_RD_CONTINUE 0 /* bytes appended (or benign EINTR): keep pulling */
#define AIO_RD_BREAK 1 /* would-block: stop the loop and parse what we have */
#define AIO_RD_RETURN 2 /* terminal (peer close / error): fully handled, return */
Functions
void aconn_do_write (brix_aconn *ac)
void aconn_note_rtt (brix_aconn *ac, const brix_areq *r)
uint64_t aconn_rto_ns (const brix_aconn *ac)
static void areq_note_deferral (brix_areq *r, const uint8_t *body, uint32_t dlen)
static void aconn_dispatch_response (brix_aconn *ac, uint16_t sid, uint16_t stat, const uint8_t *body, uint32_t dlen)
static void aconn_handle_attn (brix_aconn *ac, const uint8_t *body, uint32_t dlen)
void aconn_dispatch_frame (brix_aconn *ac, uint16_t sid, uint16_t stat, const uint8_t *body, uint32_t dlen)
void aconn_parse (brix_aconn *ac)
static int aconn_read_tls (brix_aconn *ac, uint8_t *dst, size_t room)
static int aconn_read_plain (brix_aconn *ac, uint8_t *dst, size_t room)
void aconn_do_read (brix_aconn *ac)
void aconn_handle_io (brix_aconn *ac, uint32_t events)
Macro Definition Documentation
AIO_RD_BREAK
#define AIO_RD_BREAK 1 /* would-block: stop the loop and parse what we have */
Definition at line 296 of file aio_io.c.
AIO_RD_CONTINUE
#define AIO_RD_CONTINUE 0 /* bytes appended (or benign EINTR): keep pulling */
Definition at line 295 of file aio_io.c.
AIO_RD_RETURN
#define AIO_RD_RETURN 2 /* terminal (peer close / error): fully handled, return */
Definition at line 297 of file aio_io.c.
Function Documentation
aconn_dispatch_frame()
void aconn_dispatch_frame (brix_aconn * ac, uint16_t sid, uint16_t stat, const uint8_t * body, uint32_t dlen)
Definition at line 246 of file aio_io.c.
References aconn_dispatch_response(), aconn_handle_attn(), brix_mono_ns(), kXR_attn, brix_aconn::last_activity_ns, and stat().
Referenced by aconn_parse().
aconn_dispatch_response()
static void aconn_dispatch_response (brix_aconn * ac, uint16_t sid, uint16_t stat, const uint8_t * body, uint32_t dlen) static
Definition at line 158 of file aio_io.c.
References aconn_note_rtt(), areq_accumulate(), areq_complete(), areq_note_deferral(), brix_kxr_name(), brix_status_set(), brix_areq::deferred, brix_aconn::inflight, kXR_authmore, kXR_error, kXR_ok, kXR_oksofar, kXR_redirect, kXR_wait, kXR_waitresp, reqmap_del(), reqmap_get(), stat(), xrd_error_body_decode(), and XRDC_EPROTO.
Referenced by aconn_dispatch_frame(), and aconn_handle_attn().
aconn_do_read()
void aconn_do_read (brix_aconn * ac)
Definition at line 404 of file aio_io.c.
References aconn_on_transport_error(), aconn_parse(), aconn_read_plain(), aconn_read_tls(), AIO_RD_CONTINUE, AIO_RD_RETURN, AIO_READ_CHUNK, brix_status_set(), xbuf::buf, xbuf::cap, xbuf::len, brix_aconn::rbuf, brix_aconn::ssl, brix_aconn::tls_want_write_on_read, xbuf_reserve(), and XRDC_EPROTO.
Referenced by aconn_handle_io().
aconn_do_write()
void aconn_do_write (brix_aconn * ac)
Definition at line 25 of file aio_io.c.
References aconn_on_transport_error(), brix_status_set(), xbuf::buf, brix_aconn::fd, xbuf::len, brix_aconn::ssl, xbuf::start, brix_aconn::tls_want_read_on_write, brix_aconn::wbuf, and XRDC_ESOCK.
Referenced by aconn_handle_io(), and aconn_issue_areq().
aconn_handle_attn()
static void aconn_handle_attn (brix_aconn * ac, const uint8_t * body, uint32_t dlen) static
Definition at line 223 of file aio_io.c.
References aconn_dispatch_response(), kXR_asynresp, xrd_get_u32_be(), and xrd_resp_hdr_unpack().
Referenced by aconn_dispatch_frame().
aconn_handle_io()
void aconn_handle_io (brix_aconn * ac, uint32_t events)
Definition at line 435 of file aio_io.c.
References aconn_do_read(), aconn_do_write(), aconn_on_transport_error(), aconn_update_epoll(), brix_status_set(), brix_aconn::dead, brix_aconn::tls_want_read_on_write, brix_aconn::tls_want_write_on_read, and XRDC_ESOCK.
Referenced by loop_thread().
aconn_note_rtt()
void aconn_note_rtt (brix_aconn * ac, const brix_areq * r)
Definition at line 90 of file aio_io.c.
References brix_mono_ns(), brix_aconn::have_rtt, brix_aconn::rttvar_ns, brix_aconn::srtt_ns, and brix_areq::submit_ns.
Referenced by aconn_dispatch_response().
aconn_parse()
void aconn_parse (brix_aconn * ac)
Definition at line 261 of file aio_io.c.
References aconn_dispatch_frame(), aconn_on_transport_error(), brix_status_set(), xbuf::buf, brix_aconn::dead, xbuf::len, brix_aconn::rbuf, xbuf::start, stat(), xbuf_compact(), xrd_resp_hdr_unpack(), XRD_RESPONSE_HDR_LEN, XRDC_DLEN_MAX, and XRDC_EPROTO.
Referenced by aconn_do_read(), aconn_read_plain(), and aconn_read_tls().
aconn_read_plain()
static int aconn_read_plain (brix_aconn * ac, uint8_t * dst, size_t room) static
Definition at line 372 of file aio_io.c.
References aconn_on_transport_error(), aconn_parse(), AIO_RD_BREAK, AIO_RD_CONTINUE, AIO_RD_RETURN, brix_status_set(), brix_aconn::dead, brix_aconn::fd, xbuf::len, brix_aconn::rbuf, read(), and XRDC_ESOCK.
Referenced by aconn_do_read().
aconn_read_tls()
static int aconn_read_tls (brix_aconn * ac, uint8_t * dst, size_t room) static
Definition at line 321 of file aio_io.c.
References aconn_on_transport_error(), aconn_parse(), AIO_RD_BREAK, AIO_RD_CONTINUE, AIO_RD_RETURN, brix_status_set(), brix_aconn::dead, xbuf::len, brix_aconn::rbuf, brix_aconn::ssl, brix_aconn::tls_want_write_on_read, and XRDC_ESOCK.
Referenced by aconn_do_read().
aconn_rto_ns()
uint64_t aconn_rto_ns (const brix_aconn * ac)
Definition at line 114 of file aio_io.c.
References brix_aconn::have_rtt, brix_aconn::rttvar_ns, and brix_aconn::srtt_ns.
Referenced by aconn_deadline_ns(), and aconn_maybe_ping().
areq_note_deferral()
static void areq_note_deferral (brix_areq * r, const uint8_t * body, uint32_t dlen) static
Definition at line 138 of file aio_io.c.
References brix_mono_ns(), brix_areq::deadline_ns, brix_areq::deferred, and xrd_wait_secs_parse().
Referenced by aconn_dispatch_response().