nginx-xrootd: client/lib/core/aio/aio_mgr.c File Reference
aio_mgr.c File Reference
#include "aio.h"
#include "brix.h"
#include "protocols/root/protocol/protocol.h"
#include "core/compat/codec_core.h"
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <time.h>
#include <arpa/inet.h>
#include <endian.h>
Data Structures
struct brix_mgr
struct mgr_connect_job
struct brix_mfile
Functions
static void * mgr_connect_worker (void *arg)
static void mgr_connect_parallel (mgr_connect_job *jobs, int count)
static void mgr_free (brix_mgr *m)
brix_mgr * brix_mgr_create (const brix_url *u, const brix_opts *o, int nconns, int eager, int max_stall_ms, int keepalive_ms, int max_retries, brix_status *st)
void brix_mgr_destroy (brix_mgr *m)
static brix_aconn * mgr_ensure_slot (brix_mgr *m, int i)
brix_aconn * brix_mgr_pick (brix_mgr *m)
int brix_mgr_call (brix_mgr *m, const void *hdr24, const void *payload, uint32_t plen, int retry_safe, uint16_t *kxr, uint8_t **body, uint32_t *blen, brix_status *st)
static uint64_t now_ns (void)
static int mfile_do_open (brix_mfile *mf, int force, brix_status *st)
brix_mfile * brix_mfile_open (brix_aconn *ac, const char *path, int writable, int force, int posc, const char *opaque, int max_stall_ms, int max_retries, brix_status *st)
static int mfile_should_reopen (const brix_status *st)
static int mfile_reopen (brix_mfile *mf, uint64_t expected_gen, brix_status *st)
static int mfile_snapshot (brix_mfile *mf, uint8_t fh[4], uint64_t *gen, uint8_t *rcodec, uint8_t *wcodec)
ssize_t brix_mfile_pread (brix_mfile *mf, int64_t off, void *buf, size_t len, brix_status *st)
int brix_mfile_pwrite (brix_mfile *mf, int64_t off, const void *buf, size_t len, brix_status *st)
int brix_mfile_sync (brix_mfile *mf, brix_status *st)
int brix_mfile_close (brix_mfile *mf, brix_status *st)
Function Documentation
brix_mfile_close()
int brix_mfile_close (brix_mfile * mf, brix_status * st)
Definition at line 646 of file aio_mgr.c.
References brix_mfile::ac, brix_aio_call(), brix_mfile::fhandle, xrdw_close_req_t::fhandle, brix_mfile::have_handle, kXR_close, brix_mfile::lock, ClientCloseRequest::requestid, XRD_FHANDLE_LEN, and xrdw_close_req_pack().
Referenced by xfs_release().
brix_mfile_open()
brix_mfile * brix_mfile_open (brix_aconn * ac, const char * path, int writable, int force, int posc, const char * opaque, int max_stall_ms, int max_retries, brix_status * st)
Definition at line 411 of file aio_mgr.c.
References brix_mfile::ac, brix_status_set(), brix_mfile::gen, brix_mfile::have_handle, brix_mfile::have_opaque, brix_mfile::lock, brix_mfile::max_retries, brix_mfile::max_stall_ms, mfile_do_open(), brix_mfile::opaque, brix_mfile::path, brix_mfile::posc, brix_mfile::writable, and XRDC_EPROTO.
Referenced by afh_open().
brix_mfile_pread()
ssize_t brix_mfile_pread (brix_mfile * mf, int64_t off, void * buf, size_t len, brix_status * st)
Definition at line 493 of file aio_mgr.c.
References brix_mfile::ac, brix_aio_call_ex(), brix_backoff_sleep_fast(), brix_inflate_frame(), xrdw_read_req_t::fhandle, kXR_read, brix_mfile::max_stall_ms, mfile_reopen(), mfile_should_reopen(), mfile_snapshot(), now_ns(), xrdw_read_req_t::offset, ClientReadRequest::requestid, XRD_FHANDLE_LEN, and xrdw_read_req_pack().
Referenced by afh_pread().
brix_mfile_pwrite()
int brix_mfile_pwrite (brix_mfile * mf, int64_t off, const void * buf, size_t len, brix_status * st)
Definition at line 557 of file aio_mgr.c.
References brix_mfile::ac, brix_aio_call_ex(), brix_backoff_sleep_fast(), brix_deflate_frame(), xrdw_write_req_t::fhandle, kXR_write, brix_mfile::max_stall_ms, mfile_reopen(), mfile_should_reopen(), mfile_snapshot(), now_ns(), xrdw_write_req_t::offset, ClientWriteRequest::requestid, XRD_FHANDLE_LEN, and xrdw_write_req_pack().
Referenced by afh_io_pwrite().
brix_mfile_sync()
int brix_mfile_sync (brix_mfile * mf, brix_status * st)
Definition at line 620 of file aio_mgr.c.
References brix_mfile::ac, brix_aio_call(), xrdw_sync_req_t::fhandle, kXR_sync, brix_mfile::max_stall_ms, mfile_reopen(), mfile_snapshot(), ClientSyncRequest::requestid, XRD_FHANDLE_LEN, and xrdw_sync_req_pack().
Referenced by xfs_fsync().
brix_mgr_call()
int brix_mgr_call (brix_mgr * m, const void * hdr24, const void * payload, uint32_t plen, int retry_safe, uint16_t * kxr, uint8_t ** body, uint32_t * blen, brix_status * st)
Definition at line 273 of file aio_mgr.c.
References brix_aio_call_ex(), brix_mgr_pick(), and brix_mgr::max_retries.
brix_mgr_create()
brix_mgr * brix_mgr_create (const brix_url * u, const brix_opts * o, int nconns, int eager, int max_stall_ms, int keepalive_ms, int max_retries, brix_status * st)
Definition at line 120 of file aio_mgr.c.
References brix_mgr::acs, brix_aconn_attach(), brix_aconn_set_resilience(), brix_close(), brix_loop_create(), brix_status_set(), mgr_connect_job::conn, brix_mgr::conns, brix_mgr::have_opts, brix_mgr::keepalive_ms, brix_mgr::lazy_lock, brix_mgr::loop, brix_mgr::max_retries, brix_mgr::max_stall_ms, mgr_connect_parallel(), mgr_free(), brix_mgr::n, mgr_connect_job::o, brix_mgr::opts, mgr_connect_job::rc, mgr_connect_job::st, mgr_connect_job::u, brix_mgr::url, and XRDC_EPROTO.
Referenced by xrootdfs_aio_main().
brix_mgr_destroy()
void brix_mgr_destroy (brix_mgr * m)
Definition at line 205 of file aio_mgr.c.
References mgr_free().
Referenced by xrootdfs_aio_main().
brix_mgr_pick()
brix_aconn * brix_mgr_pick (brix_mgr * m)
Definition at line 246 of file aio_mgr.c.
References brix_mgr::acs, mgr_ensure_slot(), brix_mgr::n, and brix_mgr::rr.
Referenced by afh_open(), and brix_mgr_call().
mfile_do_open()
static int mfile_do_open (brix_mfile * mf, int force, brix_status * st) static
Definition at line 316 of file aio_mgr.c.
References brix_mfile::ac, brix_aio_call_ex(), brix_codec_available(), BRIX_CODEC_MAX, BRIX_INLINE_CMP_MAGIC, brix_status_set(), brix_mfile::fhandle, brix_mfile::have_opaque, kXR_delete, kXR_mkpath, kXR_new, kXR_open, kXR_open_read, kXR_open_updt, kXR_posc, brix_mfile::max_retries, brix_mfile::max_stall_ms, xrdw_open_req_t::mode, brix_mfile::opaque, brix_mfile::path, brix_mfile::posc, brix_mfile::read_codec, ClientOpenRequest::requestid, brix_mfile::writable, brix_mfile::write_codec, XRD_FHANDLE_LEN, XRDC_EPROTO, XRDC_EUNSUPPORTED, and xrdw_open_req_pack().
Referenced by brix_mfile_open(), and mfile_reopen().
mfile_reopen()
static int mfile_reopen (brix_mfile * mf, uint64_t expected_gen, brix_status * st) static
Definition at line 453 of file aio_mgr.c.
References brix_mfile::gen, brix_mfile::have_handle, brix_mfile::lock, mfile_do_open(), and brix_mfile::writable.
Referenced by brix_mfile_pread(), brix_mfile_pwrite(), and brix_mfile_sync().
mfile_should_reopen()
static int mfile_should_reopen (const brix_status * st) static
Definition at line 445 of file aio_mgr.c.
References brix_status_retryable(), brix_status::kxr, and kXR_FileNotOpen.
Referenced by brix_mfile_pread(), and brix_mfile_pwrite().
mfile_snapshot()
static int mfile_snapshot (brix_mfile * mf, uint8_t fh[4], uint64_t * gen, uint8_t * rcodec, uint8_t * wcodec) static
Definition at line 473 of file aio_mgr.c.
References brix_mfile::fhandle, brix_mfile::gen, brix_mfile::have_handle, brix_mfile::lock, brix_mfile::read_codec, brix_mfile::write_codec, and XRD_FHANDLE_LEN.
Referenced by brix_mfile_pread(), brix_mfile_pwrite(), and brix_mfile_sync().
mgr_connect_parallel()
static void mgr_connect_parallel (mgr_connect_job * jobs, int count) static
Definition at line 81 of file aio_mgr.c.
References mgr_connect_worker().
Referenced by brix_mgr_create().
mgr_connect_worker()
static void * mgr_connect_worker (void * arg) static
Definition at line 70 of file aio_mgr.c.
References brix_connect(), mgr_connect_job::conn, mgr_connect_job::o, mgr_connect_job::rc, mgr_connect_job::st, and mgr_connect_job::u.
Referenced by mgr_connect_parallel().
mgr_ensure_slot()
static brix_aconn * mgr_ensure_slot (brix_mgr * m, int i) static
Definition at line 218 of file aio_mgr.c.
References brix_mgr::acs, brix_aconn_attach(), brix_aconn_set_resilience(), brix_close(), brix_connect(), brix_mgr::conns, brix_mgr::have_opts, brix_mgr::keepalive_ms, brix_mgr::lazy_lock, brix_mgr::loop, brix_mgr::max_retries, brix_mgr::max_stall_ms, brix_mgr::opts, and brix_mgr::url.
Referenced by brix_mgr_pick().
mgr_free()
static void mgr_free (brix_mgr * m) static
Definition at line 103 of file aio_mgr.c.
References brix_mgr::acs, brix_aconn_close(), brix_close(), brix_loop_destroy(), brix_mgr::conns, brix_mgr::lazy_lock, brix_mgr::loop, and brix_mgr::n.
Referenced by brix_mgr_create(), and brix_mgr_destroy().
now_ns()
static uint64_t now_ns (void) static
Definition at line 308 of file aio_mgr.c.
References brix_mono_ns().
Referenced by brix_mfile_pread(), brix_mfile_pwrite(), brix_phase_mark(), brix_scan_tb_init(), brix_scan_tb_refill(), brix_scan_tb_wait_ns(), brix_vfs_elapsed_usec(), and us_since().