nginx-xrootd: client/lib/core/aio/aio_engine.c File Reference
aio_engine.c File Reference
#include "aio_internal.h"
Functions
unsigned uring_pollmask (int want)
int uring_slot_alloc (brix_loop *l, brix_aconn *ac)
int uring_poll_submit (brix_loop *l, brix_aconn *ac, int want)
void uring_poll_cancel (brix_loop *l, brix_aconn *ac, int freeing)
int io_engine_setup (brix_loop *l, brix_status *st)
void io_engine_teardown (brix_loop *l)
int io_engine_arm (brix_loop *l, brix_aconn *ac, int want)
void io_engine_del (brix_loop *l, brix_aconn *ac)
int io_engine_wait (brix_loop *l, struct epoll_event *evs, int max, int timeout_ms)
Function Documentation
io_engine_arm()
int io_engine_arm (brix_loop * l, brix_aconn * ac, int want)
Definition at line 176 of file aio_engine.c.
References brix_loop::epfd, brix_aconn::epoll_events, brix_aconn::fd, brix_aconn::fd_gen, uring_poll_cancel(), uring_poll_submit(), brix_aconn::uring_slot, uring_slot_alloc(), and brix_loop::use_uring.
Referenced by aconn_reconnect_succeeded(), aconn_update_epoll(), and loop_drain_commands().
io_engine_del()
void io_engine_del (brix_loop * l, brix_aconn * ac)
Definition at line 207 of file aio_engine.c.
References brix_loop::epfd, brix_aconn::epoll_events, brix_aconn::fd, uring_poll_cancel(), and brix_loop::use_uring.
Referenced by aconn_destroy(), and aconn_on_transport_error().
io_engine_setup()
int io_engine_setup (brix_loop * l, brix_status * st)
Definition at line 103 of file aio_engine.c.
References brix_status_set(), brix_loop::epfd, brix_loop::evfd, brix_loop::use_uring, and XRDC_ESOCK.
Referenced by brix_loop_create().
io_engine_teardown()
void io_engine_teardown (brix_loop * l)
Definition at line 156 of file aio_engine.c.
References close(), brix_loop::epfd, brix_loop::evfd, and brix_loop::use_uring.
Referenced by brix_loop_create_fail(), and brix_loop_destroy().
io_engine_wait()
int io_engine_wait (brix_loop * l, struct epoll_event * evs, int max, int timeout_ms)
Definition at line 227 of file aio_engine.c.
References brix_loop::epfd, brix_aconn::epoll_events, in_use, uring_poll_submit(), and brix_loop::use_uring.
Referenced by loop_thread().
uring_poll_cancel()
void uring_poll_cancel (brix_loop * l, brix_aconn * ac, int freeing)
Definition at line 75 of file aio_engine.c.
References brix_aconn::uring_slot.
Referenced by io_engine_arm(), and io_engine_del().
uring_poll_submit()
int uring_poll_submit (brix_loop * l, brix_aconn * ac, int want)
Definition at line 57 of file aio_engine.c.
References brix_aconn::fd, uring_pollmask(), and brix_aconn::uring_slot.
Referenced by io_engine_arm(), and io_engine_wait().
uring_pollmask()
unsigned uring_pollmask (int want)
Definition at line 29 of file aio_engine.c.
Referenced by uring_poll_submit().
uring_slot_alloc()
int uring_slot_alloc (brix_loop * l, brix_aconn * ac)
Definition at line 40 of file aio_engine.c.
References AIO_URING_SLOTS, and brix_aconn::uring_slot.
Referenced by io_engine_arm().