nginx-xrootd: client/lib/core/aio/aio_internal.h File Reference
aio_internal.h File Reference
#include "aio.h"
#include "uring.h"
#include "protocols/root/protocol/frame_hdr.h"
#include <sys/epoll.h>
#include <sys/eventfd.h>
#include <sys/socket.h>
#include <pthread.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <arpa/inet.h>
#include <poll.h>
#include <openssl/ssl.h>
#include <openssl/err.h>
Data Structures
struct xbuf
struct brix_areq
struct reqmap
struct brix_aconn
struct cmd
struct brix_poll_slot
struct brix_loop
struct call_wait
Macros
#define AIO_MAXEV 64
#define AIO_URING_SLOTS 128
#define AIO_READ_CHUNK 65536u
#define AIO_TICK_MS 1000
#define REQMAP_TOMB ((brix_areq *) -1)
Enumerations
enum aconn_state { ACONN_ALIVE = 0 , ACONN_RECONNECTING , ACONN_DEAD }
enum cmd_type { CMD_ADD_ACONN , CMD_SUBMIT , CMD_CLOSE_ACONN , CMD_STOP }
Functions
int xbuf_reserve (xbuf *b, size_t need)
int xbuf_append (xbuf *b, const void *data, size_t n)
void xbuf_compact (xbuf *b)
void xbuf_free (xbuf *b)
void areq_free (brix_areq *r)
int areq_accumulate (brix_areq *r, const uint8_t *body, uint32_t n)
void areq_complete (brix_areq *r, int rc, uint16_t kxr, const brix_status *st)
int reqmap_rehash (reqmap *m, uint32_t newcap)
int reqmap_put (reqmap *m, brix_areq *r)
brix_areq * reqmap_get (reqmap *m, uint16_t sid)
void reqmap_del (reqmap *m, uint16_t sid)
void aconn_do_write (brix_aconn *ac)
void aconn_note_rtt (brix_aconn *ac, const brix_areq *r)
uint64_t aconn_rto_ns (const brix_aconn *ac)
void aconn_dispatch_frame (brix_aconn *ac, uint16_t sid, uint16_t stat, const uint8_t *body, uint32_t dlen)
void aconn_parse (brix_aconn *ac)
void aconn_do_read (brix_aconn *ac)
void aconn_handle_io (brix_aconn *ac, uint32_t events)
int io_engine_setup (brix_loop *l, brix_status *st)
void io_engine_teardown (brix_loop *l)
int io_engine_arm (brix_loop *l, brix_aconn *ac, int want)
void io_engine_del (brix_loop *l, brix_aconn *ac)
int io_engine_wait (brix_loop *l, struct epoll_event *evs, int max, int timeout_ms)
void aconn_update_epoll (brix_aconn *ac)
void aconn_drain_inflight (brix_aconn *ac, const brix_status *st)
void aconn_pending_fail_all (brix_aconn *ac, const brix_status *st)
void * rc_worker_main (void *arg)
void aconn_on_transport_error (brix_aconn *ac, const brix_status *st)
void aconn_reconnect_succeeded (brix_aconn *ac)
void aconn_poll_reconnect (brix_aconn *ac)
void aconn_ping_cb (void *ctx, int rc, uint16_t kxr, uint8_t *body, uint32_t blen, const brix_status *st)
void aconn_maybe_ping (brix_aconn *ac)
void aconn_destroy (brix_aconn *ac)
uint16_t aconn_alloc_sid (brix_aconn *ac)
void aconn_issue_areq (brix_aconn *ac, brix_areq *r)
uint64_t aconn_deadline_ns (brix_aconn *ac, int deadline_ms)
void aconn_submit_cmd (brix_aconn *ac, cmd *c)
void loop_push_cmd (brix_loop *l, cmd *c)
void loop_run_control (brix_loop *l, cmd_type type, brix_aconn *ac)
void loop_drain_commands (brix_loop *l)
int loop_process_timeouts (brix_loop *l)
void * loop_thread (void *arg)
brix_loop * brix_loop_create_fail (brix_loop *l)
int brix_loop_want_uring (void)
void call_cb (void *ctx, int rc, uint16_t kxr, uint8_t *body, uint32_t blen, const brix_status *st)
Macro Definition Documentation
AIO_MAXEV
#define AIO_MAXEV 64
Definition at line 28 of file aio_internal.h.
AIO_READ_CHUNK
#define AIO_READ_CHUNK 65536u
Definition at line 30 of file aio_internal.h.
AIO_TICK_MS
#define AIO_TICK_MS 1000
Definition at line 31 of file aio_internal.h.
AIO_URING_SLOTS
#define AIO_URING_SLOTS 128
Definition at line 29 of file aio_internal.h.
REQMAP_TOMB
#define REQMAP_TOMB ((brix_areq *) -1)
Definition at line 64 of file aio_internal.h.
Enumeration Type Documentation
aconn_state
enum aconn_state
Enumerator
ACONN_ALIVE
ACONN_RECONNECTING
ACONN_DEAD
Definition at line 72 of file aio_internal.h.
cmd_type
enum cmd_type
Enumerator
CMD_ADD_ACONN
CMD_SUBMIT
CMD_CLOSE_ACONN
CMD_STOP
Definition at line 118 of file aio_internal.h.
Function Documentation
aconn_alloc_sid()
uint16_t aconn_alloc_sid (brix_aconn * ac)
Definition at line 264 of file aio_conn.c.
References brix_aconn::inflight, brix_aconn::next_sid, reqmap_get(), and s.
Referenced by aconn_issue_areq().
aconn_deadline_ns()
uint64_t aconn_deadline_ns (brix_aconn * ac, int deadline_ms)
Definition at line 316 of file aio_conn.c.
References aconn_rto_ns(), brix_mono_ns(), and brix_aconn::max_stall_ms.
Referenced by aconn_submit_cmd().
aconn_destroy()
void aconn_destroy (brix_aconn * ac)
Definition at line 232 of file aio_conn.c.
References aconn_drain_inflight(), aconn_pending_fail_all(), brix_loop::aconns, brix_status_set(), brix_aconn::dead, brix_aconn::inflight, io_engine_del(), brix_aconn::loop, brix_aconn::next, brix_aconn::rbuf, brix_aconn::rc_thread, brix_aconn::rc_thread_live, reqmap::slots, brix_aconn::wbuf, xbuf_free(), and XRDC_ESOCK.
Referenced by loop_drain_commands(), and loop_thread().
aconn_dispatch_frame()
void aconn_dispatch_frame (brix_aconn * ac, uint16_t sid, uint16_t stat, const uint8_t * body, uint32_t dlen)
Definition at line 246 of file aio_io.c.
References aconn_dispatch_response(), aconn_handle_attn(), brix_mono_ns(), kXR_attn, brix_aconn::last_activity_ns, and stat().
Referenced by aconn_parse().
aconn_do_read()
void aconn_do_read (brix_aconn * ac)
Definition at line 404 of file aio_io.c.
References aconn_on_transport_error(), aconn_parse(), aconn_read_plain(), aconn_read_tls(), AIO_RD_CONTINUE, AIO_RD_RETURN, AIO_READ_CHUNK, brix_status_set(), xbuf::buf, xbuf::cap, xbuf::len, brix_aconn::rbuf, brix_aconn::ssl, brix_aconn::tls_want_write_on_read, xbuf_reserve(), and XRDC_EPROTO.
Referenced by aconn_handle_io().
aconn_do_write()
void aconn_do_write (brix_aconn * ac)
Definition at line 25 of file aio_io.c.
References aconn_on_transport_error(), brix_status_set(), xbuf::buf, brix_aconn::fd, xbuf::len, brix_aconn::ssl, xbuf::start, brix_aconn::tls_want_read_on_write, brix_aconn::wbuf, and XRDC_ESOCK.
Referenced by aconn_handle_io(), and aconn_issue_areq().
aconn_drain_inflight()
void aconn_drain_inflight (brix_aconn * ac, const brix_status * st)
Definition at line 26 of file aio_conn.c.
References areq_complete(), reqmap::cap, reqmap::count, brix_aconn::inflight, brix_status::kxr, REQMAP_TOMB, reqmap::slots, and reqmap::tomb.
Referenced by aconn_destroy(), and aconn_on_transport_error().
aconn_handle_io()
void aconn_handle_io (brix_aconn * ac, uint32_t events)
Definition at line 435 of file aio_io.c.
References aconn_do_read(), aconn_do_write(), aconn_on_transport_error(), aconn_update_epoll(), brix_status_set(), brix_aconn::dead, brix_aconn::tls_want_read_on_write, brix_aconn::tls_want_write_on_read, and XRDC_ESOCK.
Referenced by loop_thread().
aconn_issue_areq()
void aconn_issue_areq (brix_aconn * ac, brix_areq * r)
Definition at line 287 of file aio_conn.c.
References aconn_alloc_sid(), aconn_do_write(), aconn_update_epoll(), areq_complete(), brix_mono_ns(), brix_status_set(), brix_aconn::dead, brix_areq::hdr, brix_aconn::inflight, brix_areq::payload, brix_areq::plen, reqmap_put(), brix_areq::sid, brix_areq::submit_ns, brix_aconn::wbuf, xbuf_append(), XRD_REQUEST_HDR_LEN, and XRDC_EPROTO.
Referenced by aconn_maybe_ping(), aconn_reconnect_succeeded(), and aconn_submit_cmd().
aconn_maybe_ping()
void aconn_maybe_ping (brix_aconn * ac)
Definition at line 200 of file aio_conn.c.
References ACONN_ALIVE, aconn_issue_areq(), aconn_ping_cb(), aconn_rto_ns(), brix_mono_ns(), brix_areq::cb, brix_areq::ctx, brix_areq::deadline_ns, brix_aconn::def_retries, brix_areq::hdr, brix_areq::is_ping, brix_aconn::keepalive_ms, kXR_ping, brix_aconn::last_activity_ns, brix_aconn::ping_inflight, brix_areq::retries_left, brix_areq::retry_safe, and brix_aconn::state.
Referenced by loop_thread().
aconn_note_rtt()
void aconn_note_rtt (brix_aconn * ac, const brix_areq * r)
Definition at line 90 of file aio_io.c.
References brix_mono_ns(), brix_aconn::have_rtt, brix_aconn::rttvar_ns, brix_aconn::srtt_ns, and brix_areq::submit_ns.
Referenced by aconn_dispatch_response().
aconn_on_transport_error()
void aconn_on_transport_error (brix_aconn * ac, const brix_status * st)
Definition at line 68 of file aio_conn.c.
References ACONN_ALIVE, ACONN_DEAD, aconn_drain_inflight(), aconn_pending_fail_all(), ACONN_RECONNECTING, areq_complete(), brix_mono_ns(), reqmap::cap, reqmap::count, brix_aconn::dead, brix_areq::deadline_ns, brix_aconn::inflight, io_engine_del(), brix_status::kxr, xbuf::len, brix_aconn::loop, brix_aconn::max_stall_ms, brix_areq::pend_next, brix_aconn::pending, brix_aconn::ping_inflight, brix_aconn::rbuf, brix_aconn::rc_thread, brix_aconn::rc_thread_live, rc_worker_main(), brix_aconn::reconnect_deadline_ns, REQMAP_TOMB, brix_areq::retries_left, brix_areq::retry_safe, reqmap::slots, xbuf::start, brix_aconn::state, brix_aconn::tls_want_read_on_write, brix_aconn::tls_want_write_on_read, reqmap::tomb, and brix_aconn::wbuf.
Referenced by aconn_do_read(), aconn_do_write(), aconn_handle_io(), aconn_parse(), aconn_read_plain(), aconn_read_tls(), and timeouts_scan_conn().
aconn_parse()
void aconn_parse (brix_aconn * ac)
Definition at line 261 of file aio_io.c.
References aconn_dispatch_frame(), aconn_on_transport_error(), brix_status_set(), xbuf::buf, brix_aconn::dead, xbuf::len, brix_aconn::rbuf, xbuf::start, stat(), xbuf_compact(), xrd_resp_hdr_unpack(), XRD_RESPONSE_HDR_LEN, XRDC_DLEN_MAX, and XRDC_EPROTO.
Referenced by aconn_do_read(), aconn_read_plain(), and aconn_read_tls().
aconn_pending_fail_all()
void aconn_pending_fail_all (brix_aconn * ac, const brix_status * st)
Definition at line 52 of file aio_conn.c.
References areq_complete(), brix_status::kxr, brix_areq::pend_next, and brix_aconn::pending.
Referenced by aconn_destroy(), aconn_on_transport_error(), aconn_poll_reconnect(), and aconn_reconnect_succeeded().
aconn_ping_cb()
void aconn_ping_cb (void * ctx, int rc, uint16_t kxr, uint8_t * body, uint32_t blen, const brix_status * st)
Definition at line 188 of file aio_conn.c.
References brix_aconn::ping_inflight.
Referenced by aconn_maybe_ping().
aconn_poll_reconnect()
void aconn_poll_reconnect (brix_aconn * ac)
Definition at line 162 of file aio_conn.c.
References ACONN_DEAD, aconn_pending_fail_all(), aconn_reconnect_succeeded(), ACONN_RECONNECTING, brix_aconn::rc_finished, brix_aconn::rc_result, brix_aconn::rc_st, brix_aconn::rc_thread, brix_aconn::rc_thread_live, and brix_aconn::state.
Referenced by loop_thread().
aconn_reconnect_succeeded()
void aconn_reconnect_succeeded (brix_aconn * ac)
Definition at line 121 of file aio_conn.c.
References ACONN_ALIVE, ACONN_DEAD, aconn_issue_areq(), aconn_pending_fail_all(), brix_mono_ns(), brix_status_set(), brix_aconn::conn, brix_aconn::dead, brix_io::fd, brix_aconn::fd, brix_conn::io, io_engine_arm(), brix_aconn::last_activity_ns, brix_aconn::loop, brix_areq::pend_next, brix_aconn::pending, brix_aconn::reconnect_deadline_ns, brix_io::ssl, brix_aconn::ssl, brix_aconn::state, and XRDC_ESOCK.
Referenced by aconn_poll_reconnect().
aconn_rto_ns()
uint64_t aconn_rto_ns (const brix_aconn * ac)
Definition at line 114 of file aio_io.c.
References brix_aconn::have_rtt, brix_aconn::rttvar_ns, and brix_aconn::srtt_ns.
Referenced by aconn_deadline_ns(), and aconn_maybe_ping().
aconn_submit_cmd()
void aconn_submit_cmd (brix_aconn * ac, cmd * c)
Definition at line 340 of file aio_conn.c.
References ACONN_DEAD, aconn_deadline_ns(), aconn_issue_areq(), ACONN_RECONNECTING, brix_mono_ns(), brix_status_set(), c, brix_areq::cb, brix_areq::ctx, brix_areq::deadline_ns, brix_aconn::def_retries, brix_areq::hdr, brix_aconn::max_stall_ms, brix_areq::payload, brix_areq::pend_next, brix_aconn::pending, brix_areq::plen, brix_areq::retries_left, brix_areq::retry_safe, brix_aconn::state, XRD_REQUEST_HDR_LEN, XRDC_EPROTO, and XRDC_ESOCK.
Referenced by loop_drain_commands().
aconn_update_epoll()
void aconn_update_epoll (brix_aconn * ac)
Definition at line 10 of file aio_conn.c.
References brix_aconn::epoll_events, io_engine_arm(), xbuf::len, brix_aconn::loop, xbuf::start, brix_aconn::tls_want_write_on_read, and brix_aconn::wbuf.
Referenced by aconn_handle_io(), and aconn_issue_areq().
areq_accumulate()
int areq_accumulate (brix_areq * r, const uint8_t * body, uint32_t n)
Definition at line 88 of file aio_buffers.c.
References brix_areq::acc, brix_areq::acc_cap, and brix_areq::acc_len.
Referenced by aconn_dispatch_response().
areq_complete()
void areq_complete (brix_areq * r, int rc, uint16_t kxr, const brix_status * st)
Definition at line 114 of file aio_buffers.c.
References brix_areq::acc, brix_areq::acc_len, areq_free(), brix_areq::cb, and brix_areq::ctx.
Referenced by aconn_dispatch_response(), aconn_drain_inflight(), aconn_issue_areq(), aconn_on_transport_error(), aconn_pending_fail_all(), timeouts_expire_inflight(), and timeouts_expire_parked().
areq_free()
void areq_free (brix_areq * r)
Definition at line 76 of file aio_buffers.c.
References brix_areq::acc, and brix_areq::payload.
Referenced by areq_complete().
brix_loop_create_fail()
brix_loop * brix_loop_create_fail (brix_loop * l)
Definition at line 367 of file aio.c.
References brix_loop::cq_lock, and io_engine_teardown().
Referenced by brix_loop_create().
brix_loop_want_uring()
int brix_loop_want_uring (void)
Definition at line 381 of file aio.c.
References brix_uring_available().
Referenced by brix_loop_create().
call_cb()
void call_cb (void * ctx, int rc, uint16_t kxr, uint8_t * body, uint32_t blen, const brix_status * st)
Definition at line 576 of file aio.c.
References call_wait::blen, call_wait::body, call_wait::cv, call_wait::done, call_wait::kxr, call_wait::mx, call_wait::rc, and call_wait::st.
Referenced by brix_aio_call_ex().
io_engine_arm()
int io_engine_arm (brix_loop * l, brix_aconn * ac, int want)
Definition at line 180 of file aio_engine.c.
References brix_loop::epfd, brix_aconn::epoll_events, brix_aconn::fd, brix_aconn::fd_gen, op, brix_aconn::uring_slot, and brix_loop::use_uring.
Referenced by aconn_reconnect_succeeded(), aconn_update_epoll(), and loop_drain_commands().
io_engine_del()
void io_engine_del (brix_loop * l, brix_aconn * ac)
Definition at line 211 of file aio_engine.c.
References brix_loop::epfd, brix_aconn::epoll_events, brix_aconn::fd, and brix_loop::use_uring.
Referenced by aconn_destroy(), and aconn_on_transport_error().
io_engine_setup()
int io_engine_setup (brix_loop * l, brix_status * st)
Definition at line 107 of file aio_engine.c.
References brix_status_set(), brix_loop::epfd, brix_loop::evfd, brix_loop::use_uring, and XRDC_ESOCK.
Referenced by brix_loop_create().
io_engine_teardown()
void io_engine_teardown (brix_loop * l)
Definition at line 160 of file aio_engine.c.
References close(), brix_loop::epfd, brix_loop::evfd, and brix_loop::use_uring.
Referenced by brix_loop_create_fail(), and brix_loop_destroy().
io_engine_wait()
int io_engine_wait (brix_loop * l, struct epoll_event * evs, int max, int timeout_ms)
Definition at line 366 of file aio_engine.c.
References brix_loop::epfd, and brix_loop::use_uring.
Referenced by loop_thread().
loop_drain_commands()
void loop_drain_commands (brix_loop * l)
Definition at line 120 of file aio.c.
References aconn_destroy(), aconn_submit_cmd(), brix_loop::aconns, c, CMD_ADD_ACONN, CMD_CLOSE_ACONN, CMD_STOP, CMD_SUBMIT, brix_loop::cq_head, brix_loop::cq_lock, brix_loop::cq_tail, brix_aconn::dead, io_engine_arm(), brix_aconn::next, cmd::next, and brix_loop::stop.
Referenced by loop_thread().
loop_process_timeouts()
int loop_process_timeouts (brix_loop * l)
Definition at line 300 of file aio.c.
References brix_loop::aconns, brix_mono_ns(), timeouts_next_wait_ms(), and timeouts_scan_conn().
Referenced by loop_thread().
loop_push_cmd()
void loop_push_cmd (brix_loop * l, cmd * c)
Definition at line 73 of file aio.c.
References c, brix_loop::cq_head, brix_loop::cq_lock, brix_loop::cq_tail, brix_loop::evfd, and cmd::next.
Referenced by brix_aio_submit_ex(), brix_loop_destroy(), and loop_run_control().
loop_run_control()
void loop_run_control (brix_loop * l, cmd_type type, brix_aconn * ac)
Definition at line 93 of file aio.c.
References c, loop_push_cmd(), and cmd::type.
Referenced by brix_aconn_attach(), and brix_aconn_close().
loop_thread()
void * loop_thread (void * arg)
Definition at line 315 of file aio.c.
References aconn_destroy(), aconn_handle_io(), aconn_maybe_ping(), aconn_poll_reconnect(), brix_loop::aconns, AIO_MAXEV, AIO_TICK_MS, brix_loop::evfd, io_engine_wait(), loop_drain_commands(), loop_process_timeouts(), read(), and brix_loop::stop.
Referenced by brix_loop_create().
rc_worker_main()
void * rc_worker_main (void * arg)
Definition at line 13 of file aio.c.
References brix_mono_ns(), brix_reconnect(), brix_status_set(), brix_aconn::conn, brix_loop::evfd, host, brix_conn::host, brix_aconn::loop, port, brix_conn::port, brix_aconn::rc_finished, brix_aconn::rc_result, brix_aconn::rc_st, brix_aconn::reconnect_deadline_ns, and XRDC_ESOCK.
Referenced by aconn_on_transport_error().
reqmap_del()
void reqmap_del (reqmap * m, uint16_t sid)
Definition at line 214 of file aio_buffers.c.
References reqmap::cap, reqmap::count, REQMAP_TOMB, brix_areq::sid, reqmap::slots, and reqmap::tomb.
Referenced by aconn_dispatch_response().
reqmap_get()
brix_areq * reqmap_get (reqmap * m, uint16_t sid)
Definition at line 193 of file aio_buffers.c.
References reqmap::cap, REQMAP_TOMB, brix_areq::sid, and reqmap::slots.
Referenced by aconn_alloc_sid(), and aconn_dispatch_response().
reqmap_put()
int reqmap_put (reqmap * m, brix_areq * r)
Definition at line 163 of file aio_buffers.c.
References reqmap::cap, reqmap::count, reqmap_rehash(), REQMAP_TOMB, brix_areq::sid, reqmap::slots, and reqmap::tomb.
Referenced by aconn_issue_areq().
reqmap_rehash()
int reqmap_rehash (reqmap * m, uint32_t newcap)
Definition at line 137 of file aio_buffers.c.
References reqmap::cap, REQMAP_TOMB, brix_areq::sid, reqmap::slots, and reqmap::tomb.
Referenced by reqmap_put().
xbuf_append()
int xbuf_append (xbuf * b, const void * data, size_t n)
Definition at line 28 of file aio_buffers.c.
References xbuf::buf, xbuf::len, and xbuf_reserve().
Referenced by aconn_issue_areq().
xbuf_compact()
void xbuf_compact (xbuf * b)
Definition at line 44 of file aio_buffers.c.
References xbuf::buf, xbuf::len, and xbuf::start.
Referenced by aconn_parse().
xbuf_free()
void xbuf_free (xbuf * b)
Definition at line 60 of file aio_buffers.c.
References xbuf::buf, xbuf::cap, xbuf::len, and xbuf::start.
Referenced by aconn_destroy().
xbuf_reserve()
int xbuf_reserve (xbuf * b, size_t need)
Definition at line 8 of file aio_buffers.c.
References xbuf::buf, xbuf::cap, and xbuf::len.
Referenced by aconn_do_read(), and xbuf_append().