nginx-xrootd: client/lib/core/aio/aio_buffers.c File Reference
aio_buffers.c File Reference
#include "aio_internal.h"
Functions
int xbuf_reserve (xbuf *b, size_t need)
int xbuf_append (xbuf *b, const void *data, size_t n)
void xbuf_compact (xbuf *b)
void xbuf_free (xbuf *b)
void areq_free (brix_areq *r)
int areq_accumulate (brix_areq *r, const uint8_t *body, uint32_t n)
void areq_complete (brix_areq *r, int rc, uint16_t kxr, const brix_status *st)
int reqmap_rehash (reqmap *m, uint32_t newcap)
int reqmap_put (reqmap *m, brix_areq *r)
brix_areq * reqmap_get (reqmap *m, uint16_t sid)
void reqmap_del (reqmap *m, uint16_t sid)
Function Documentation
areq_accumulate()
int areq_accumulate (brix_areq * r, const uint8_t * body, uint32_t n)
Definition at line 88 of file aio_buffers.c.
References brix_areq::acc, brix_areq::acc_cap, and brix_areq::acc_len.
Referenced by aconn_dispatch_response().
areq_complete()
void areq_complete (brix_areq * r, int rc, uint16_t kxr, const brix_status * st)
Definition at line 114 of file aio_buffers.c.
References brix_areq::acc, brix_areq::acc_len, areq_free(), brix_areq::cb, and brix_areq::ctx.
Referenced by aconn_dispatch_response(), aconn_drain_inflight(), aconn_issue_areq(), aconn_on_transport_error(), aconn_pending_fail_all(), and loop_process_timeouts().
areq_free()
void areq_free (brix_areq * r)
Definition at line 76 of file aio_buffers.c.
References brix_areq::acc, and brix_areq::payload.
Referenced by areq_complete().
reqmap_del()
void reqmap_del (reqmap * m, uint16_t sid)
Definition at line 214 of file aio_buffers.c.
References reqmap::cap, reqmap::count, REQMAP_TOMB, brix_areq::sid, reqmap::slots, and reqmap::tomb.
Referenced by aconn_dispatch_response().
reqmap_get()
brix_areq * reqmap_get (reqmap * m, uint16_t sid)
Definition at line 193 of file aio_buffers.c.
References reqmap::cap, REQMAP_TOMB, brix_areq::sid, and reqmap::slots.
Referenced by aconn_alloc_sid(), and aconn_dispatch_response().
reqmap_put()
int reqmap_put (reqmap * m, brix_areq * r)
Definition at line 163 of file aio_buffers.c.
References reqmap::cap, reqmap::count, reqmap_rehash(), REQMAP_TOMB, brix_areq::sid, reqmap::slots, and reqmap::tomb.
Referenced by aconn_issue_areq().
reqmap_rehash()
int reqmap_rehash (reqmap * m, uint32_t newcap)
Definition at line 137 of file aio_buffers.c.
References reqmap::cap, REQMAP_TOMB, brix_areq::sid, reqmap::slots, and reqmap::tomb.
Referenced by reqmap_put().
xbuf_append()
int xbuf_append (xbuf * b, const void * data, size_t n)
Definition at line 28 of file aio_buffers.c.
References xbuf::buf, xbuf::len, and xbuf_reserve().
Referenced by aconn_issue_areq().
xbuf_compact()
void xbuf_compact (xbuf * b)
Definition at line 44 of file aio_buffers.c.
References xbuf::buf, xbuf::len, and xbuf::start.
Referenced by aconn_parse().
xbuf_free()
void xbuf_free (xbuf * b)
Definition at line 60 of file aio_buffers.c.
References xbuf::buf, xbuf::cap, xbuf::len, and xbuf::start.
Referenced by aconn_destroy().
xbuf_reserve()
int xbuf_reserve (xbuf * b, size_t need)
Definition at line 8 of file aio_buffers.c.
References xbuf::buf, xbuf::cap, and xbuf::len.
Referenced by aconn_do_read(), and xbuf_append().