nginx-xrootd: src/observability/dashboard/api_admin_proxy.c File Reference
api_admin_proxy.c File Reference
#include "dashboard_api_admin_internal.h"
Functions
ngx_int_t admin_parse_proxy_uri (ngx_http_request_t *r, uint32_t *id_out, char *action_out, size_t action_size)
json_t * admin_proxy_backend_json (const brix_proxy_be_snapshot_t *e)
int admin_url_host_allowed (ngx_http_brix_dashboard_loc_conf_t *conf, const char *url)
ngx_int_t admin_proxy_add (ngx_http_request_t *r, json_t *body)
ngx_int_t admin_proxy_list (ngx_http_request_t *r)
ngx_int_t admin_proxy_one (ngx_http_request_t *r, const char *action, uint32_t id)
char * brix_admin_set_proxy_allow (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Function Documentation
admin_parse_proxy_uri()
ngx_int_t admin_parse_proxy_uri (ngx_http_request_t * r, uint32_t * id_out, char * action_out, size_t action_size)
Definition at line 10 of file api_admin_proxy.c.
References ADMIN_PREFIX.
Referenced by brix_admin_dispatch().
admin_proxy_add()
ngx_int_t admin_proxy_add (ngx_http_request_t * r, json_t * body)
Definition at line 131 of file api_admin_proxy.c.
References admin_audit(), admin_send_error(), admin_url_host_allowed(), admin_validate_url(), BRIX_DASH_EVENT_NAMESPACE, brix_dashboard_event_add(), brix_proxy_pool_add(), dashboard_json_send(), dashboard_json_set_schema(), and ngx_http_brix_dashboard_module.
Referenced by brix_admin_dispatch().
admin_proxy_backend_json()
json_t * admin_proxy_backend_json (const brix_proxy_be_snapshot_t * e)
Definition at line 57 of file api_admin_proxy.c.
References BRIX_PROXY_BE_DEAD, BRIX_PROXY_BE_DRAINING, brix_proxy_be_snapshot_t::host, brix_proxy_be_snapshot_t::id, brix_proxy_be_snapshot_t::in_flight, brix_proxy_be_snapshot_t::port, brix_proxy_be_snapshot_t::ssl, brix_proxy_be_snapshot_t::state, and brix_proxy_be_snapshot_t::weight.
Referenced by admin_proxy_list().
admin_proxy_list()
ngx_int_t admin_proxy_list (ngx_http_request_t * r)
Definition at line 186 of file api_admin_proxy.c.
References admin_proxy_backend_json(), BRIX_PROXY_POOL_SLOTS, brix_proxy_pool_snapshot(), dashboard_json_send(), and dashboard_json_set_schema().
Referenced by brix_admin_dispatch().
admin_proxy_one()
ngx_int_t admin_proxy_one (ngx_http_request_t * r, const char * action, uint32_t id)
Definition at line 221 of file api_admin_proxy.c.
References admin_audit(), admin_send_error(), admin_send_ok(), brix_proxy_pool_drain(), brix_proxy_pool_in_flight(), brix_proxy_pool_remove(), brix_proxy_pool_undrain(), dashboard_json_send(), and dashboard_json_set_schema().
Referenced by brix_admin_dispatch().
admin_url_host_allowed()
int admin_url_host_allowed (ngx_http_brix_dashboard_loc_conf_t * conf, const char * url)
Definition at line 91 of file api_admin_proxy.c.
References ngx_http_brix_dashboard_loc_conf_t::admin_proxy_allow.
Referenced by admin_proxy_add().
brix_admin_set_proxy_allow()
char * brix_admin_set_proxy_allow (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 282 of file api_admin_proxy.c.
References ngx_http_brix_dashboard_loc_conf_t::admin_proxy_allow.