nginx-xrootd: src/observability/dashboard/api_ratelimit.c File Reference
api_ratelimit.c File Reference
#include "dashboard_api_internal.h"
Functions
json_t * dashboard_build_v1_ratelimit (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t redact)
json_t * dashboard_build_v1_not_found (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t redact)
json_t * dashboard_build_v1_truncated (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf)
Function Documentation
dashboard_build_v1_not_found()
json_t * dashboard_build_v1_not_found (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t redact)
Definition at line 77 of file api_ratelimit.c.
References dashboard_new_v1_root().
Referenced by ngx_http_brix_dashboard_api_handler().
dashboard_build_v1_ratelimit()
json_t * dashboard_build_v1_ratelimit (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t redact)
Definition at line 10 of file api_ratelimit.c.
References brix_rl_snapshot(), brix_rl_zones_all(), dashboard_new_v1_root(), brix_rl_zone_t::name, and name.
Referenced by ngx_http_brix_dashboard_api_handler().
dashboard_build_v1_truncated()
json_t * dashboard_build_v1_truncated (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf)
Definition at line 89 of file api_ratelimit.c.
References dashboard_new_v1_root().
Referenced by ngx_http_brix_dashboard_api_handler().