nginx-xrootd: src/observability/dashboard/api_snapshot.c File Reference
api_snapshot.c File Reference
#include "dashboard_api_internal.h"
Macros
#define X(ID, metric_label, dash_name, http_plane) dash_name,
#define X(ID, metric_label, dash_name, http_plane) http_plane,
Functions
void dashboard_collect_totals (brix_dashboard_totals_t *totals)
void dashboard_collect_protocols (brix_dashboard_protocols_t *out, int64_t now_ms)
json_t * dashboard_build_limits (const ngx_http_brix_dashboard_loc_conf_t *conf)
json_t * dashboard_build_totals (const brix_dashboard_totals_t *totals)
json_t * dashboard_build_proto_summary (const brix_dashboard_proto_summary_t *s, uint64_t bytes_rx, uint64_t bytes_tx)
json_t * dashboard_build_protocols (int64_t now_ms, const brix_dashboard_totals_t *totals)
json_t * dashboard_build_events (ngx_pool_t *pool, ngx_uint_t redact)
void dashboard_fill_history (json_t *target, ngx_pool_t *pool)
json_t * dashboard_new_v1_root (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf)
json_t * dashboard_build_v1_snapshot (ngx_http_request_t *r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, const brix_dashboard_totals_t *totals, ngx_uint_t redact)
json_t * dashboard_build_v1_events (ngx_http_request_t *r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t redact)
json_t * dashboard_build_v1_history (ngx_http_request_t *r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t redact)
json_t * dashboard_build_v1_cluster (ngx_http_request_t *r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t redact)
json_t * dashboard_build_v1_cache (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t redact)
Macro Definition Documentation
X [1/2]
#define X (ID, metric_label, dash_name, http_plane) dash_name,
X [2/2]
#define X (ID, metric_label, dash_name, http_plane) http_plane,
Function Documentation
dashboard_build_events()
json_t * dashboard_build_events (ngx_pool_t * pool, ngx_uint_t redact)
Definition at line 272 of file api_snapshot.c.
References brix_dashboard_events_snapshot(), BRIX_DASHBOARD_MAX_EVENTS, dashboard_event_class_name(), dashboard_proto_name(), brix_dashboard_event_t::message, ngx_pcalloc(), and brix_dashboard_event_t::path_hint.
Referenced by dashboard_build_v1_events(), and dashboard_build_v1_snapshot().
dashboard_build_limits()
json_t * dashboard_build_limits (const ngx_http_brix_dashboard_loc_conf_t * conf)
Definition at line 142 of file api_snapshot.c.
References BRIX_DASHBOARD_HISTORY_INTERVAL_MS, BRIX_DASHBOARD_MAX_EVENTS, BRIX_DASHBOARD_MAX_TRANSFERS, BRIX_TPC_REGISTRY_SLOTS, ngx_http_brix_dashboard_loc_conf_t::idle_threshold_ms, ngx_http_brix_dashboard_loc_conf_t::stalled_threshold_ms, and TPC_REGISTRY_JSON_LIMIT.
Referenced by dashboard_new_v1_root().
dashboard_build_proto_summary()
json_t * dashboard_build_proto_summary (const brix_dashboard_proto_summary_t * s, uint64_t bytes_rx, uint64_t bytes_tx)
Definition at line 214 of file api_snapshot.c.
References s.
Referenced by dashboard_build_protocols().
dashboard_build_protocols()
json_t * dashboard_build_protocols (int64_t now_ms, const brix_dashboard_totals_t * totals)
Definition at line 231 of file api_snapshot.c.
References brix_dashboard_proto_summary_t::active, BRIX_XFER_NPROTOS, BRIX_XFER_PROTO_ROOT, brix_dashboard_totals_t::bytes_rx, brix_dashboard_totals_t::bytes_tx, dashboard_build_proto_summary(), dashboard_collect_protocols(), dashboard_proto_name(), brix_dashboard_proto_summary_t::egress_bps, brix_dashboard_proto_summary_t::ingress_bps, brix_dashboard_protocols_t::per, brix_dashboard_totals_t::proto_rx, brix_dashboard_totals_t::proto_tx, and brix_dashboard_protocols_t::tpc.
Referenced by dashboard_build_v1_snapshot().
dashboard_build_totals()
json_t * dashboard_build_totals (const brix_dashboard_totals_t * totals)
Definition at line 158 of file api_snapshot.c.
References BRIX_PROTO_LIST, BRIX_XFER_NPROTOS, brix_dashboard_totals_t::bytes_rx, brix_dashboard_totals_t::bytes_tx, brix_dashboard_totals_t::conn_active, brix_dashboard_totals_t::conn_total, key, brix_dashboard_totals_t::proto_errors, brix_dashboard_totals_t::proto_rx, brix_dashboard_totals_t::proto_tx, brix_dashboard_totals_t::stream_errors, and X.
Referenced by dashboard_build_compat_transfers(), dashboard_build_v1_snapshot(), and dashboard_build_v1_transfers().
dashboard_build_v1_cache()
json_t * dashboard_build_v1_cache (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t redact)
Definition at line 466 of file api_snapshot.c.
References dashboard_fill_cache(), and dashboard_new_v1_root().
Referenced by dashboard_dispatch_builder().
dashboard_build_v1_cluster()
json_t * dashboard_build_v1_cluster (ngx_http_request_t * r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t redact)
Definition at line 453 of file api_snapshot.c.
References dashboard_fill_cluster(), and dashboard_new_v1_root().
Referenced by dashboard_dispatch_builder().
dashboard_build_v1_events()
json_t * dashboard_build_v1_events (ngx_http_request_t * r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t redact)
Definition at line 427 of file api_snapshot.c.
References dashboard_build_events(), and dashboard_new_v1_root().
Referenced by dashboard_dispatch_builder().
dashboard_build_v1_history()
json_t * dashboard_build_v1_history (ngx_http_request_t * r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t redact)
Definition at line 440 of file api_snapshot.c.
References dashboard_fill_history(), and dashboard_new_v1_root().
Referenced by dashboard_dispatch_builder().
dashboard_build_v1_snapshot()
json_t * dashboard_build_v1_snapshot (ngx_http_request_t * r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, const brix_dashboard_totals_t * totals, ngx_uint_t redact)
Definition at line 373 of file api_snapshot.c.
References dashboard_build_events(), dashboard_build_protocols(), dashboard_build_totals(), dashboard_build_tpc_registry(), dashboard_build_transfer_rows(), dashboard_fill_cache(), dashboard_fill_cluster(), dashboard_fill_cvmfs(), dashboard_fill_history(), dashboard_fill_storage(), and dashboard_new_v1_root().
Referenced by dashboard_dispatch_builder().
dashboard_collect_protocols()
void dashboard_collect_protocols (brix_dashboard_protocols_t * out, int64_t now_ms)
Definition at line 94 of file api_snapshot.c.
References brix_dashboard_proto_summary_t::active, BRIX_DASHBOARD_MAX_TRANSFERS, BRIX_XFER_DIR_TPC, BRIX_XFER_DIR_WRITE, BRIX_XFER_NPROTOS, BRIX_XFER_PROTO_ROOT, brix_transfer_slot_t::bytes, dashboard_avg_bps(), brix_transfer_slot_t::direction, brix_dashboard_proto_summary_t::egress_bps, brix_transfer_slot_t::in_use, brix_dashboard_proto_summary_t::ingress_bps, ngx_brix_dashboard_shm_zone, brix_dashboard_protocols_t::per, brix_transfer_slot_t::proto, brix_transfer_table_t::slots, brix_transfer_slot_t::start_ms, and brix_dashboard_protocols_t::tpc.
Referenced by dashboard_build_protocols().
dashboard_collect_totals()
void dashboard_collect_totals (brix_dashboard_totals_t * totals)
Definition at line 19 of file api_snapshot.c.
References BRIX_HTTP_STATUS_4XX, BRIX_HTTP_STATUS_5XX, BRIX_METRICS_MAX_SERVERS, BRIX_NOPS, BRIX_S3_NMETHODS, BRIX_WEBDAV_NMETHODS, BRIX_XFER_PROTO_CVMFS, BRIX_XFER_PROTO_S3, BRIX_XFER_PROTO_WEBDAV, brix_dashboard_totals_t::bytes_rx, ngx_brix_srv_metrics_t::bytes_rx_total, ngx_brix_s3_metrics_t::bytes_rx_total, ngx_brix_webdav_metrics_t::bytes_rx_total, ngx_brix_cvmfs_metrics_t::bytes_served_fill_total, ngx_brix_cvmfs_metrics_t::bytes_served_hit_total, brix_dashboard_totals_t::bytes_tx, ngx_brix_srv_metrics_t::bytes_tx_total, ngx_brix_s3_metrics_t::bytes_tx_total, ngx_brix_webdav_metrics_t::bytes_tx_total, brix_dashboard_totals_t::conn_active, brix_dashboard_totals_t::conn_total, ngx_brix_srv_metrics_t::connections_active, ngx_brix_srv_metrics_t::connections_total, ngx_brix_metrics_t::cvmfs, ngx_brix_cvmfs_metrics_t::fill_failures_total, ngx_brix_shm_zone, ngx_brix_srv_metrics_t::op_err, ngx_brix_cvmfs_metrics_t::origin_bytes_total, brix_dashboard_totals_t::proto_errors, brix_dashboard_totals_t::proto_rx, brix_dashboard_totals_t::proto_tx, ngx_brix_s3_metrics_t::responses_total, ngx_brix_webdav_metrics_t::responses_total, ngx_brix_metrics_t::s3, ngx_brix_metrics_t::servers, brix_dashboard_totals_t::stream_errors, ngx_brix_cvmfs_metrics_t::verify_failures_total, and ngx_brix_metrics_t::webdav.
Referenced by ngx_http_brix_dashboard_api_handler().
dashboard_fill_history()
void dashboard_fill_history (json_t * target, ngx_pool_t * pool)
Definition at line 308 of file api_snapshot.c.
References BRIX_DASHBOARD_HISTORY_BUCKETS, BRIX_DASHBOARD_HISTORY_INTERVAL_MS, brix_dashboard_history_snapshot(), BRIX_XFER_NPROTOS, dashboard_proto_name(), and ngx_pcalloc().
Referenced by dashboard_build_v1_history(), and dashboard_build_v1_snapshot().
dashboard_new_v1_root()
json_t * dashboard_new_v1_root (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf)
Definition at line 360 of file api_snapshot.c.
References dashboard_build_limits(), and dashboard_json_set_schema().
Referenced by dashboard_build_v1_cache(), dashboard_build_v1_cluster(), dashboard_build_v1_cvmfs(), dashboard_build_v1_events(), dashboard_build_v1_history(), dashboard_build_v1_not_found(), dashboard_build_v1_ratelimit(), dashboard_build_v1_snapshot(), dashboard_build_v1_transfer_detail(), dashboard_build_v1_transfers(), and dashboard_build_v1_truncated().