nginx-xrootd: src/observability/dashboard/api_admin.c File Reference
api_admin.c File Reference
#include "dashboard_api_admin_internal.h"
Typedefs
typedef ngx_int_t(* admin_route_fn) (ngx_http_request_t *r, int *matched)
Functions
ngx_int_t admin_send_ok (ngx_http_request_t *r, const char *result)
ngx_int_t admin_send_error (ngx_http_request_t *r, ngx_int_t status, const char *code)
int admin_validate_hostname (const char *host)
static int admin_char_is_alnum (unsigned char c)
static int admin_path_char_ok (unsigned char c)
int admin_validate_paths (const char *paths)
static int admin_auth_cidr_ok (ngx_http_request_t *r, const ngx_http_brix_dashboard_loc_conf_t *conf)
static int admin_auth_secret_ok (ngx_http_request_t *r, const ngx_http_brix_dashboard_loc_conf_t *conf)
static brix_admin_auth_result_t admin_auth_combine (const ngx_http_brix_dashboard_loc_conf_t *conf, int has_allow, int cidr_ok, int has_secret, int secret_ok)
brix_admin_auth_result_t brix_admin_check_auth (ngx_http_request_t *r, const ngx_http_brix_dashboard_loc_conf_t *conf)
void admin_audit (ngx_http_request_t *r, const char *action, const char *target, const char *result)
void brix_admin_body_callback (ngx_http_request_t *r)
ngx_int_t brix_admin_read_body (ngx_http_request_t *r, brix_admin_body_handler_t handler)
static int admin_url_char_ok (unsigned char c)
static int admin_url_scheme_off (const char *url, size_t *off)
int admin_validate_url (const char *url)
int admin_uri_eq (ngx_http_request_t *r, const char *s)
int admin_uri_has_action (ngx_http_request_t *r, const char *action)
static int admin_uri_under (ngx_http_request_t *r, const char *pfx, size_t plen)
static ngx_int_t admin_route_io_uring (ngx_http_request_t *r, int *matched)
static ngx_int_t admin_route_cluster_server (ngx_http_request_t *r, int *matched)
static ngx_int_t admin_route_cluster (ngx_http_request_t *r, int *matched)
static ngx_int_t admin_route_proxy (ngx_http_request_t *r, int *matched)
static ngx_int_t admin_rate_gate (ngx_http_request_t *r, ngx_http_brix_dashboard_loc_conf_t *conf, int *throttled)
ngx_int_t brix_admin_dispatch (ngx_http_request_t *r)
Typedef Documentation
admin_route_fn
typedef ngx_int_t(* admin_route_fn) (ngx_http_request_t *r, int *matched)
Definition at line 586 of file api_admin.c.
Function Documentation
admin_audit()
void admin_audit (ngx_http_request_t * r, const char * action, const char * target, const char * result)
Definition at line 220 of file api_admin.c.
Referenced by admin_cluster_delete(), admin_cluster_drain(), admin_cluster_register(), admin_cluster_undrain(), admin_io_uring_set(), admin_proxy_add(), admin_proxy_one(), admin_rate_gate(), and brix_admin_dispatch().
admin_auth_cidr_ok()
static int admin_auth_cidr_ok (ngx_http_request_t * r, const ngx_http_brix_dashboard_loc_conf_t * conf) static
Definition at line 136 of file api_admin.c.
References ngx_http_brix_dashboard_loc_conf_t::admin_allow.
Referenced by brix_admin_check_auth().
admin_auth_combine()
static brix_admin_auth_result_t admin_auth_combine (const ngx_http_brix_dashboard_loc_conf_t * conf, int has_allow, int cidr_ok, int has_secret, int secret_ok) static
Definition at line 181 of file api_admin.c.
References ngx_http_brix_dashboard_loc_conf_t::admin_require_both, BRIX_ADMIN_AUTH_DENIED, and BRIX_ADMIN_AUTH_OK.
Referenced by brix_admin_check_auth().
admin_auth_secret_ok()
static int admin_auth_secret_ok (ngx_http_request_t * r, const ngx_http_brix_dashboard_loc_conf_t * conf) static
Definition at line 155 of file api_admin.c.
References ngx_http_brix_dashboard_loc_conf_t::admin_secret, and brix_http_extract_bearer().
Referenced by brix_admin_check_auth().
admin_char_is_alnum()
static int admin_char_is_alnum (unsigned char c) static
Definition at line 70 of file api_admin.c.
References c.
Referenced by admin_path_char_ok(), and admin_url_char_ok().
admin_path_char_ok()
static int admin_path_char_ok (unsigned char c) static
Definition at line 85 of file api_admin.c.
References admin_char_is_alnum(), and c.
Referenced by admin_validate_paths().
admin_rate_gate()
static ngx_int_t admin_rate_gate (ngx_http_request_t * r, ngx_http_brix_dashboard_loc_conf_t * conf, int * throttled) static
Definition at line 614 of file api_admin.c.
References admin_audit(), ngx_http_brix_dashboard_loc_conf_t::admin_rl_enable, ngx_http_brix_dashboard_loc_conf_t::admin_rl_read, ngx_http_brix_dashboard_loc_conf_t::admin_rl_write, admin_send_error(), brix_http_set_header(), brix_rl_check(), BRIX_RL_KEY_LEN, key, and brix_rl_rule_t::zone.
Referenced by brix_admin_dispatch().
admin_route_cluster()
static ngx_int_t admin_route_cluster (ngx_http_request_t * r, int * matched) static
Definition at line 528 of file api_admin.c.
References admin_cluster_register(), ADMIN_PREFIX, admin_route_cluster_server(), admin_send_error(), admin_uri_eq(), and brix_admin_read_body().
Referenced by brix_admin_dispatch().
admin_route_cluster_server()
static ngx_int_t admin_route_cluster_server (ngx_http_request_t * r, int * matched) static
Definition at line 485 of file api_admin.c.
References admin_cluster_delete(), admin_cluster_drain(), admin_cluster_register(), admin_cluster_undrain(), ADMIN_PREFIX, admin_send_error(), admin_uri_has_action(), admin_uri_under(), and brix_admin_read_body().
Referenced by admin_route_cluster().
admin_route_io_uring()
static ngx_int_t admin_route_io_uring (ngx_http_request_t * r, int * matched) static
Definition at line 454 of file api_admin.c.
References admin_io_uring_get(), admin_io_uring_set(), ADMIN_PREFIX, admin_send_error(), admin_uri_eq(), brix_admin_read_body(), and brix_uring_admin_enabled().
Referenced by brix_admin_dispatch().
admin_route_proxy()
static ngx_int_t admin_route_proxy (ngx_http_request_t * r, int * matched) static
Definition at line 549 of file api_admin.c.
References admin_parse_proxy_uri(), ADMIN_PREFIX, admin_proxy_add(), admin_proxy_list(), admin_proxy_one(), admin_send_error(), admin_uri_eq(), admin_uri_under(), and brix_admin_read_body().
Referenced by brix_admin_dispatch().
admin_send_error()
ngx_int_t admin_send_error (ngx_http_request_t * r, ngx_int_t status, const char * code)
Definition at line 21 of file api_admin.c.
References code, dashboard_json_send(), and dashboard_json_set_schema().
Referenced by admin_cluster_delete(), admin_cluster_drain(), admin_cluster_register(), admin_cluster_undrain(), admin_io_uring_set(), admin_proxy_add(), admin_proxy_one(), admin_rate_gate(), admin_route_cluster(), admin_route_cluster_server(), admin_route_io_uring(), admin_route_proxy(), brix_admin_body_callback(), and brix_admin_dispatch().
admin_send_ok()
ngx_int_t admin_send_ok (ngx_http_request_t * r, const char * result)
Definition at line 8 of file api_admin.c.
References dashboard_json_send(), and dashboard_json_set_schema().
Referenced by admin_cluster_delete(), admin_cluster_drain(), admin_cluster_register(), admin_cluster_undrain(), and admin_proxy_one().
admin_uri_eq()
int admin_uri_eq (ngx_http_request_t * r, const char * s)
Definition at line 408 of file api_admin.c.
References s.
Referenced by admin_route_cluster(), admin_route_io_uring(), and admin_route_proxy().
admin_uri_has_action()
int admin_uri_has_action (ngx_http_request_t * r, const char * action)
Definition at line 418 of file api_admin.c.
Referenced by admin_route_cluster_server().
admin_uri_under()
static int admin_uri_under (ngx_http_request_t * r, const char * pfx, size_t plen) static
Definition at line 437 of file api_admin.c.
Referenced by admin_route_cluster_server(), and admin_route_proxy().
admin_url_char_ok()
static int admin_url_char_ok (unsigned char c) static
Definition at line 343 of file api_admin.c.
References admin_char_is_alnum(), and c.
Referenced by admin_validate_url().
admin_url_scheme_off()
static int admin_url_scheme_off (const char * url, size_t * off) static
Definition at line 359 of file api_admin.c.
Referenced by admin_validate_url().
admin_validate_hostname()
int admin_validate_hostname (const char * host)
Definition at line 38 of file api_admin.c.
References c, and host.
Referenced by admin_cluster_register().
admin_validate_paths()
int admin_validate_paths (const char * paths)
Definition at line 95 of file api_admin.c.
References admin_path_char_ok(), and BRIX_SRV_MAX_PATHS.
Referenced by admin_cluster_register().
admin_validate_url()
int admin_validate_url (const char * url)
Definition at line 379 of file api_admin.c.
References admin_url_char_ok(), admin_url_scheme_off(), and host.
Referenced by admin_proxy_add().
brix_admin_body_callback()
void brix_admin_body_callback (ngx_http_request_t * r)
Definition at line 245 of file api_admin.c.
References ADMIN_MAX_BODY, admin_send_error(), brix_admin_body_ctx_t::handler, ngx_http_brix_dashboard_module, and ngx_memcpy.
Referenced by brix_admin_read_body().
brix_admin_check_auth()
brix_admin_auth_result_t brix_admin_check_auth (ngx_http_request_t * r, const ngx_http_brix_dashboard_loc_conf_t * conf)
Definition at line 195 of file api_admin.c.
References ngx_http_brix_dashboard_loc_conf_t::admin_allow, admin_auth_cidr_ok(), admin_auth_combine(), admin_auth_secret_ok(), ngx_http_brix_dashboard_loc_conf_t::admin_secret, and BRIX_ADMIN_AUTH_DENIED.
Referenced by brix_admin_dispatch().
brix_admin_dispatch()
ngx_int_t brix_admin_dispatch (ngx_http_request_t * r)
Definition at line 652 of file api_admin.c.
References admin_audit(), admin_rate_gate(), admin_route_cluster(), admin_route_io_uring(), admin_route_proxy(), admin_send_error(), BRIX_ADMIN_AUTH_OK, brix_admin_check_auth(), and ngx_http_brix_dashboard_module.
Referenced by ngx_http_brix_dashboard_main_handler().
brix_admin_read_body()
ngx_int_t brix_admin_read_body (ngx_http_request_t * r, brix_admin_body_handler_t handler)
Definition at line 314 of file api_admin.c.
References brix_admin_body_callback(), handler, brix_admin_body_ctx_t::handler, and ngx_http_brix_dashboard_module.
Referenced by admin_route_cluster(), admin_route_cluster_server(), admin_route_io_uring(), and admin_route_proxy().