nginx-xrootd: src/observability/dashboard/api_admin_config.c File Reference
api_admin_config.c File Reference
#include "dashboard_api_admin_internal.h"
Functions
ngx_int_t admin_io_uring_set (ngx_http_request_t *r, json_t *body)
ngx_int_t admin_io_uring_get (ngx_http_request_t *r)
char * brix_admin_set_allow (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_admin_set_secret (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Function Documentation
admin_io_uring_get()
ngx_int_t admin_io_uring_get (ngx_http_request_t * r)
Definition at line 54 of file api_admin_config.c.
References brix_uring_killswitch_get(), dashboard_json_send(), and dashboard_json_set_schema().
Referenced by brix_admin_dispatch().
admin_io_uring_set()
ngx_int_t admin_io_uring_set (ngx_http_request_t * r, json_t * body)
Definition at line 22 of file api_admin_config.c.
References admin_audit(), admin_send_error(), brix_uring_killswitch_set(), dashboard_json_send(), and dashboard_json_set_schema().
Referenced by brix_admin_dispatch().
brix_admin_set_allow()
char * brix_admin_set_allow (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 72 of file api_admin_config.c.
References ngx_http_brix_dashboard_loc_conf_t::admin_allow.
brix_admin_set_secret()
char * brix_admin_set_secret (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 122 of file api_admin_config.c.
References ngx_http_brix_dashboard_loc_conf_t::admin_secret, ADMIN_SECRET_MAX, and ADMIN_SECRET_MIN.