nginx-xrootd: src/observability/dashboard/api_transfers.c File Reference
api_transfers.c File Reference
#include "dashboard_api_internal.h"
Data Structures
struct dashboard_xfer_snapshot_t
Functions
static uint64_t dashboard_decay_instant_bps (const brix_transfer_slot_t *slot, int64_t now_ms)
static void dashboard_snap_str (char *dst, const char *src, size_t size)
static void dashboard_snapshot_slot (dashboard_xfer_snapshot_t *snap, const brix_transfer_slot_t *slot, int64_t now_ms)
static void dashboard_emit_base_fields (json_t *obj, const brix_transfer_slot_t *slot, const dashboard_xfer_snapshot_t *snap, ngx_uint_t redact)
static void dashboard_emit_v1_fields (json_t *obj, const ngx_http_brix_dashboard_loc_conf_t *conf, const brix_transfer_slot_t *slot, const dashboard_xfer_snapshot_t *snap, ngx_uint_t redact)
static void dashboard_emit_tpc_object (json_t *obj, const brix_transfer_slot_t *slot, const dashboard_xfer_snapshot_t *snap, ngx_uint_t redact)
static void dashboard_emit_detail_fields (json_t *obj, const brix_transfer_slot_t *slot)
json_t * dashboard_build_transfer_object (const ngx_http_brix_dashboard_loc_conf_t *conf, const brix_transfer_slot_t *slot, int64_t now_ms, ngx_uint_t v1_fields, ngx_uint_t detail_fields, ngx_uint_t redact)
json_t * dashboard_build_transfer_rows (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t v1_fields, ngx_uint_t redact)
json_t * dashboard_build_tpc_registry (ngx_pool_t *pool, ngx_uint_t redact)
json_t * dashboard_build_compat_transfers (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, const brix_dashboard_totals_t *totals, ngx_uint_t redact)
json_t * dashboard_build_v1_transfers (ngx_http_request_t *r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, const brix_dashboard_totals_t *totals, ngx_uint_t redact)
ngx_int_t dashboard_parse_detail_id (ngx_http_request_t *r, uint32_t *id)
json_t * dashboard_build_v1_transfer_detail (ngx_http_request_t *r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_int_t *status)
Function Documentation
dashboard_build_compat_transfers()
json_t * dashboard_build_compat_transfers (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, const brix_dashboard_totals_t * totals, ngx_uint_t redact)
Definition at line 336 of file api_transfers.c.
References dashboard_build_totals(), and dashboard_build_transfer_rows().
Referenced by dashboard_dispatch_builder().
dashboard_build_tpc_registry()
json_t * dashboard_build_tpc_registry (ngx_pool_t * pool, ngx_uint_t redact)
Definition at line 303 of file api_transfers.c.
References brix_tpc_registry_snapshot(), dashboard_tpc_direction_name(), dashboard_tpc_protocol_name(), dashboard_tpc_state_name(), brix_tpc_transfer_snapshot_t::dst_path, ngx_pcalloc(), brix_tpc_transfer_snapshot_t::src_url, and TPC_REGISTRY_JSON_LIMIT.
Referenced by dashboard_build_v1_snapshot(), and dashboard_build_v1_transfers().
dashboard_build_transfer_object()
json_t * dashboard_build_transfer_object (const ngx_http_brix_dashboard_loc_conf_t * conf, const brix_transfer_slot_t * slot, int64_t now_ms, ngx_uint_t v1_fields, ngx_uint_t detail_fields, ngx_uint_t redact)
Definition at line 224 of file api_transfers.c.
References dashboard_emit_base_fields(), dashboard_emit_detail_fields(), dashboard_emit_tpc_object(), dashboard_emit_v1_fields(), and dashboard_snapshot_slot().
Referenced by dashboard_build_transfer_rows(), and dashboard_build_v1_transfer_detail().
dashboard_build_transfer_rows()
json_t * dashboard_build_transfer_rows (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t v1_fields, ngx_uint_t redact)
Definition at line 255 of file api_transfers.c.
References BRIX_DASH_EVENT_DASHBOARD, brix_dashboard_event_add(), BRIX_DASHBOARD_MAX_TRANSFERS, brix_transfer_slot_free(), dashboard_build_transfer_object(), brix_transfer_slot_t::in_use, brix_transfer_slot_t::last_ms, ngx_brix_dashboard_shm_zone, brix_transfer_slot_t::path, brix_transfer_slot_t::proto, brix_transfer_table_t::slots, and STALE_GC_MS.
Referenced by dashboard_build_compat_transfers(), dashboard_build_v1_snapshot(), and dashboard_build_v1_transfers().
dashboard_build_v1_transfer_detail()
json_t * dashboard_build_v1_transfer_detail (ngx_http_request_t * r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_int_t * status)
Definition at line 398 of file api_transfers.c.
References BRIX_DASHBOARD_MAX_TRANSFERS, dashboard_build_transfer_object(), dashboard_new_v1_root(), dashboard_parse_detail_id(), brix_transfer_slot_t::in_use, ngx_brix_dashboard_shm_zone, brix_transfer_slot_t::serial, and brix_transfer_table_t::slots.
Referenced by dashboard_dispatch_builder().
dashboard_build_v1_transfers()
json_t * dashboard_build_v1_transfers (ngx_http_request_t * r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, const brix_dashboard_totals_t * totals, ngx_uint_t redact)
Definition at line 351 of file api_transfers.c.
References dashboard_build_totals(), dashboard_build_tpc_registry(), dashboard_build_transfer_rows(), and dashboard_new_v1_root().
Referenced by dashboard_dispatch_builder().
dashboard_decay_instant_bps()
static uint64_t dashboard_decay_instant_bps (const brix_transfer_slot_t * slot, int64_t now_ms) static
Definition at line 49 of file api_transfers.c.
References BRIX_XFER_SAMPLE_MS, brix_transfer_slot_t::instant_bps, and brix_transfer_slot_t::last_sample_ms.
Referenced by dashboard_snapshot_slot().
dashboard_emit_base_fields()
static void dashboard_emit_base_fields (json_t * obj, const brix_transfer_slot_t * slot, const dashboard_xfer_snapshot_t * snap, ngx_uint_t redact) static
Definition at line 118 of file api_transfers.c.
References dashboard_xfer_snapshot_t::bytes, dashboard_xfer_snapshot_t::client_ip, dashboard_direction_name(), dashboard_proto_name(), brix_transfer_slot_t::direction, dashboard_xfer_snapshot_t::identity, dashboard_xfer_snapshot_t::last_ms, dashboard_xfer_snapshot_t::path, brix_transfer_slot_t::proto, brix_transfer_slot_t::serial, and dashboard_xfer_snapshot_t::start_ms.
Referenced by dashboard_build_transfer_object().
dashboard_emit_detail_fields()
static void dashboard_emit_detail_fields (json_t * obj, const brix_transfer_slot_t * slot) static
Definition at line 194 of file api_transfers.c.
References brix_transfer_slot_t::close_ops, dashboard_session_hash(), brix_transfer_slot_t::read_ops, brix_transfer_slot_t::sessid, brix_transfer_slot_t::sync_ops, and brix_transfer_slot_t::write_ops.
Referenced by dashboard_build_transfer_object().
dashboard_emit_tpc_object()
static void dashboard_emit_tpc_object (json_t * obj, const brix_transfer_slot_t * slot, const dashboard_xfer_snapshot_t * snap, ngx_uint_t redact) static
Definition at line 166 of file api_transfers.c.
References BRIX_XFER_DIR_TPC, brix_transfer_slot_t::direction, dashboard_xfer_snapshot_t::remote_host, dashboard_xfer_snapshot_t::remote_path, brix_transfer_slot_t::tpc_curl_exit, and brix_transfer_slot_t::tpc_remote_status.
Referenced by dashboard_build_transfer_object().
dashboard_emit_v1_fields()
static void dashboard_emit_v1_fields (json_t * obj, const ngx_http_brix_dashboard_loc_conf_t * conf, const brix_transfer_slot_t * slot, const dashboard_xfer_snapshot_t * snap, ngx_uint_t redact) static
Definition at line 140 of file api_transfers.c.
References dashboard_xfer_snapshot_t::avg_bps, dashboard_state_name(), brix_transfer_slot_t::expected_bytes, dashboard_xfer_snapshot_t::idle_ms, dashboard_xfer_snapshot_t::instant_bps, dashboard_xfer_snapshot_t::last_error, dashboard_xfer_snapshot_t::op, brix_transfer_slot_t::state, brix_transfer_slot_t::state_since_ms, dashboard_xfer_snapshot_t::vo, and brix_transfer_slot_t::worker_pid.
Referenced by dashboard_build_transfer_object().
dashboard_parse_detail_id()
ngx_int_t dashboard_parse_detail_id (ngx_http_request_t * r, uint32_t * id)
Definition at line 372 of file api_transfers.c.
References c.
Referenced by dashboard_build_v1_transfer_detail().
dashboard_snap_str()
static void dashboard_snap_str (char * dst, const char * src, size_t size) static
Definition at line 69 of file api_transfers.c.
References ngx_memcpy.
Referenced by dashboard_snapshot_slot().
dashboard_snapshot_slot()
static void dashboard_snapshot_slot (dashboard_xfer_snapshot_t * snap, const brix_transfer_slot_t * slot, int64_t now_ms) static
Definition at line 84 of file api_transfers.c.
References dashboard_xfer_snapshot_t::avg_bps, dashboard_xfer_snapshot_t::bytes, brix_transfer_slot_t::bytes, dashboard_xfer_snapshot_t::client_ip, brix_transfer_slot_t::client_ip, dashboard_avg_bps(), dashboard_decay_instant_bps(), dashboard_snap_str(), dashboard_xfer_snapshot_t::identity, brix_transfer_slot_t::identity, dashboard_xfer_snapshot_t::idle_ms, dashboard_xfer_snapshot_t::instant_bps, dashboard_xfer_snapshot_t::last_error, brix_transfer_slot_t::last_error, dashboard_xfer_snapshot_t::last_ms, brix_transfer_slot_t::last_ms, dashboard_xfer_snapshot_t::op, brix_transfer_slot_t::op, dashboard_xfer_snapshot_t::path, brix_transfer_slot_t::path, dashboard_xfer_snapshot_t::remote_host, dashboard_xfer_snapshot_t::remote_path, dashboard_xfer_snapshot_t::start_ms, brix_transfer_slot_t::start_ms, brix_transfer_slot_t::tpc_remote_host, brix_transfer_slot_t::tpc_remote_path_hint, dashboard_xfer_snapshot_t::vo, and brix_transfer_slot_t::vo.
Referenced by dashboard_build_transfer_object().