nginx-xrootd: src/observability/dashboard/api_admin_cluster.c File Reference
api_admin_cluster.c File Reference
#include "dashboard_api_admin_internal.h"
Functions
static ngx_int_t admin_copy_server_tail (ngx_http_request_t *r, char *tail, size_t tail_size)
static ngx_uint_t admin_split_server_segments (char *tail, char *seg[3])
static ngx_int_t admin_extract_host (const char *seg0, char *host_out, size_t host_size)
static ngx_int_t admin_parse_port (const char *seg1, uint16_t *port_out)
ngx_int_t admin_parse_server_uri (ngx_http_request_t *r, char *host_out, size_t host_size, uint16_t *port_out, char *action_out, size_t action_size)
ngx_int_t admin_cluster_register (ngx_http_request_t *r, json_t *body)
ngx_int_t admin_cluster_drain (ngx_http_request_t *r, json_t *body)
ngx_int_t admin_cluster_delete (ngx_http_request_t *r)
ngx_int_t admin_cluster_undrain (ngx_http_request_t *r)
Function Documentation
admin_cluster_delete()
ngx_int_t admin_cluster_delete (ngx_http_request_t * r)
Definition at line 235 of file api_admin_cluster.c.
References admin_audit(), admin_parse_server_uri(), admin_send_error(), admin_send_ok(), BRIX_DASH_EVENT_NAMESPACE, brix_dashboard_event_add(), brix_srv_unregister(), host, and port.
Referenced by admin_route_cluster_server().
admin_cluster_drain()
ngx_int_t admin_cluster_drain (ngx_http_request_t * r, json_t * body)
Definition at line 209 of file api_admin_cluster.c.
References admin_audit(), admin_parse_server_uri(), admin_send_error(), admin_send_ok(), BRIX_DASH_EVENT_NAMESPACE, brix_dashboard_event_add(), brix_srv_blacklist(), host, and port.
Referenced by admin_route_cluster_server().
admin_cluster_register()
ngx_int_t admin_cluster_register (ngx_http_request_t * r, json_t * body)
Definition at line 177 of file api_admin_cluster.c.
References admin_audit(), admin_send_error(), admin_send_ok(), admin_validate_hostname(), admin_validate_paths(), BRIX_DASH_EVENT_NAMESPACE, brix_dashboard_event_add(), brix_srv_register(), host, and port.
Referenced by admin_route_cluster(), and admin_route_cluster_server().
admin_cluster_undrain()
ngx_int_t admin_cluster_undrain (ngx_http_request_t * r)
Definition at line 257 of file api_admin_cluster.c.
References admin_audit(), admin_parse_server_uri(), admin_send_error(), admin_send_ok(), BRIX_DASH_EVENT_NAMESPACE, brix_dashboard_event_add(), brix_srv_undrain(), host, and port.
Referenced by admin_route_cluster_server().
admin_copy_server_tail()
static ngx_int_t admin_copy_server_tail (ngx_http_request_t * r, char * tail, size_t tail_size) static
Definition at line 20 of file api_admin_cluster.c.
References ngx_memcpy.
Referenced by admin_parse_server_uri().
admin_extract_host()
static ngx_int_t admin_extract_host (const char * seg0, char * host_out, size_t host_size) static
Definition at line 89 of file api_admin_cluster.c.
References ngx_memcpy.
Referenced by admin_parse_server_uri().
admin_parse_port()
static ngx_int_t admin_parse_port (const char * seg1, uint16_t * port_out) static
Definition at line 123 of file api_admin_cluster.c.
References port.
Referenced by admin_parse_server_uri().
admin_parse_server_uri()
ngx_int_t admin_parse_server_uri (ngx_http_request_t * r, char * host_out, size_t host_size, uint16_t * port_out, char * action_out, size_t action_size)
Definition at line 142 of file api_admin_cluster.c.
References admin_copy_server_tail(), admin_extract_host(), admin_parse_port(), and admin_split_server_segments().
Referenced by admin_cluster_delete(), admin_cluster_drain(), and admin_cluster_undrain().
admin_split_server_segments()
static ngx_uint_t admin_split_server_segments (char * tail, char * seg[3]) static
Definition at line 54 of file api_admin_cluster.c.
Referenced by admin_parse_server_uri().