nginx-xrootd: src/observability/dashboard/api_snapshot_panels.c File Reference
api_snapshot_panels.c File Reference
#include "dashboard_api_internal.h"
#include "fs/vfs/vfs_backend_registry.h"
Data Structures
struct dashboard_wt_totals_t
Functions
static json_t * dashboard_build_write_through (const dashboard_wt_totals_t *wt_t)
static void dashboard_fill_cache_empty (json_t *target)
static json_t * dashboard_build_cache_listener (const ngx_brix_srv_metrics_t *srv, ngx_uint_t redact)
static json_t * dashboard_build_cache_listeners (const ngx_brix_metrics_t *met, ngx_uint_t redact)
void dashboard_fill_cache (json_t *target, ngx_uint_t redact)
static json_t * dashboard_build_storage_export (const brix_vfs_backend_info_t *info, ngx_uint_t redact)
static json_t * dashboard_build_storage_exports (ngx_uint_t redact)
static json_t * dashboard_build_storage_io (void)
void dashboard_fill_storage (json_t *target, ngx_uint_t redact)
void dashboard_fill_cluster (json_t *target, ngx_pool_t *pool, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t redact)
Function Documentation
dashboard_build_cache_listener()
static json_t * dashboard_build_cache_listener (const ngx_brix_srv_metrics_t * srv, ngx_uint_t redact) static
Definition at line 93 of file api_snapshot_panels.c.
References ngx_brix_srv_metrics_t::auth, brix_fs_usage_t::available_bytes, brix_fs_usage_stat(), ngx_brix_srv_metrics_t::cache_evicted_bytes_total, ngx_brix_srv_metrics_t::cache_eviction_errors_total, ngx_brix_srv_metrics_t::cache_eviction_threshold, ngx_brix_srv_metrics_t::cache_evictions_total, ngx_brix_srv_metrics_t::cache_root, brix_fs_usage_t::occupancy_bytes, brix_fs_usage_t::occupancy_ppm, ngx_brix_srv_metrics_t::port, and brix_fs_usage_t::total_bytes.
Referenced by dashboard_build_cache_listeners().
dashboard_build_cache_listeners()
static json_t * dashboard_build_cache_listeners (const ngx_brix_metrics_t * met, ngx_uint_t redact) static
Definition at line 134 of file api_snapshot_panels.c.
References BRIX_METRICS_MAX_SERVERS, ngx_brix_srv_metrics_t::cache_enabled, dashboard_build_cache_listener(), ngx_brix_srv_metrics_t::in_use, and ngx_brix_metrics_t::servers.
Referenced by dashboard_fill_cache().
dashboard_build_storage_export()
static json_t * dashboard_build_storage_export (const brix_vfs_backend_info_t * info, ngx_uint_t redact) static
Definition at line 208 of file api_snapshot_panels.c.
References brix_fs_usage_t::available_bytes, brix_vfs_backend_info_t::backend, brix_fs_usage_stat(), brix_vfs_backend_info_t::host, brix_fs_usage_t::occupancy_bytes, brix_fs_usage_t::occupancy_ppm, brix_vfs_backend_info_t::port, brix_vfs_backend_info_t::root_canon, brix_vfs_backend_info_t::staging, and brix_fs_usage_t::total_bytes.
Referenced by dashboard_build_storage_exports().
dashboard_build_storage_exports()
static json_t * dashboard_build_storage_exports (ngx_uint_t redact) static
Definition at line 255 of file api_snapshot_panels.c.
References brix_vfs_backend_export_count(), brix_vfs_backend_export_info(), and dashboard_build_storage_export().
Referenced by dashboard_fill_storage().
dashboard_build_storage_io()
static json_t * dashboard_build_storage_io (void) static
Definition at line 286 of file api_snapshot_panels.c.
References BRIX_FS_ID_COUNT, brix_fs_id_name(), ngx_brix_unified_metrics_t::io_bytes_read_backend, ngx_brix_unified_metrics_t::io_bytes_written_backend, ngx_brix_shm_zone, and ngx_brix_metrics_t::unified.
Referenced by dashboard_fill_storage().
dashboard_build_write_through()
static json_t * dashboard_build_write_through (const dashboard_wt_totals_t * wt_t) static
Definition at line 48 of file api_snapshot_panels.c.
References dashboard_wt_totals_t::bytes, dashboard_wt_totals_t::dirty, dashboard_wt_totals_t::errors, dashboard_wt_totals_t::pending, and dashboard_wt_totals_t::success.
Referenced by dashboard_fill_cache(), and dashboard_fill_cache_empty().
dashboard_fill_cache()
void dashboard_fill_cache (json_t * target, ngx_uint_t redact)
Definition at line 159 of file api_snapshot_panels.c.
References BRIX_METRICS_MAX_SERVERS, dashboard_wt_totals_t::bytes, ngx_brix_srv_metrics_t::cache_enabled, dashboard_build_cache_listeners(), dashboard_build_write_through(), dashboard_fill_cache_empty(), dashboard_wt_totals_t::dirty, dashboard_wt_totals_t::errors, ngx_brix_srv_metrics_t::in_use, ngx_brix_shm_zone, dashboard_wt_totals_t::pending, ngx_brix_metrics_t::servers, dashboard_wt_totals_t::success, ngx_brix_srv_metrics_t::wt_dirty_handles, ngx_brix_srv_metrics_t::wt_flush_bytes_total, ngx_brix_srv_metrics_t::wt_flush_error_total, ngx_brix_srv_metrics_t::wt_flush_pending, and ngx_brix_srv_metrics_t::wt_flush_success_total.
Referenced by dashboard_build_v1_cache(), and dashboard_build_v1_snapshot().
dashboard_fill_cache_empty()
static void dashboard_fill_cache_empty (json_t * target) static
Definition at line 73 of file api_snapshot_panels.c.
References dashboard_build_write_through().
Referenced by dashboard_fill_cache().
dashboard_fill_cluster()
void dashboard_fill_cluster (json_t * target, ngx_pool_t * pool, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t redact)
Definition at line 349 of file api_snapshot_panels.c.
References BRIX_SRV_REGISTRY_SLOTS, brix_srv_snapshot(), ngx_http_brix_dashboard_loc_conf_t::cluster_stale_after_ms, brix_srv_snapshot_entry_t::host, brix_srv_snapshot_entry_t::last_seen, ngx_pcalloc(), and port.
Referenced by dashboard_build_v1_cluster(), and dashboard_build_v1_snapshot().
dashboard_fill_storage()
void dashboard_fill_storage (json_t * target, ngx_uint_t redact)
Definition at line 329 of file api_snapshot_panels.c.
References dashboard_build_storage_exports(), and dashboard_build_storage_io().
Referenced by dashboard_build_v1_snapshot().