nginx-xrootd: src/observability/dashboard/api_cvmfs.c File Reference
api_cvmfs.c File Reference
#include "dashboard_api_internal.h"
Functions
static int cvmfs_json_repo_is_dup (const ngx_brix_cvmfs_repo_metrics_t *repos, ngx_uint_t i)
static int cvmfs_json_upstream_is_dup (const ngx_brix_cvmfs_upstream_metrics_t *ups, ngx_uint_t i)
static json_t * cvmfs_json_requests (const ngx_atomic_t counts[BRIX_CVMFS_CLASS_COUNT])
static json_t * cvmfs_json_repo (const ngx_brix_cvmfs_repo_metrics_t *rm, ngx_uint_t redact)
static json_t * cvmfs_json_upstream (const ngx_brix_cvmfs_upstream_metrics_t *u, ngx_uint_t redact)
void dashboard_fill_cvmfs (json_t *target, ngx_uint_t redact)
json_t * dashboard_build_v1_cvmfs (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t redact)
Variables
static const char * cvmfs_json_class_names [BRIX_CVMFS_CLASS_COUNT]
Function Documentation
cvmfs_json_repo()
static json_t * cvmfs_json_repo (const ngx_brix_cvmfs_repo_metrics_t * rm, ngx_uint_t redact) static
Definition at line 93 of file api_cvmfs.c.
References ngx_brix_cvmfs_repo_metrics_t::bytes_served_fill_total, ngx_brix_cvmfs_repo_metrics_t::bytes_served_hit_total, ngx_brix_cvmfs_repo_metrics_t::cache_hits_total, ngx_brix_cvmfs_repo_metrics_t::cache_misses_total, cvmfs_json_requests(), ngx_brix_cvmfs_repo_metrics_t::files_accessed_total, ngx_brix_cvmfs_repo_metrics_t::fill_failures_total, ngx_brix_cvmfs_repo_metrics_t::fills_total, ngx_brix_cvmfs_repo_metrics_t::name, ngx_brix_cvmfs_repo_metrics_t::negative_hits_total, ngx_brix_cvmfs_repo_metrics_t::origin_bytes_total, ngx_brix_cvmfs_repo_metrics_t::requests_total, and ngx_brix_cvmfs_repo_metrics_t::verify_failures_total.
Referenced by dashboard_fill_cvmfs().
cvmfs_json_repo_is_dup()
static int cvmfs_json_repo_is_dup (const ngx_brix_cvmfs_repo_metrics_t * repos, ngx_uint_t i) static
Definition at line 34 of file api_cvmfs.c.
References BRIX_CVMFS_REPO_READY, and name.
Referenced by dashboard_fill_cvmfs().
cvmfs_json_requests()
static json_t * cvmfs_json_requests (const ngx_atomic_t counts[BRIX_CVMFS_CLASS_COUNT]) static
Definition at line 74 of file api_cvmfs.c.
References BRIX_CVMFS_CLASS_COUNT, cls(), and cvmfs_json_class_names.
Referenced by cvmfs_json_repo(), and dashboard_fill_cvmfs().
cvmfs_json_upstream()
static json_t * cvmfs_json_upstream (const ngx_brix_cvmfs_upstream_metrics_t * u, ngx_uint_t redact) static
Definition at line 131 of file api_cvmfs.c.
References ngx_brix_cvmfs_upstream_metrics_t::dur_count, ngx_brix_cvmfs_upstream_metrics_t::dur_sum_ms, ngx_brix_cvmfs_upstream_metrics_t::failovers_total, ngx_brix_cvmfs_upstream_metrics_t::fill_failures_total, ngx_brix_cvmfs_upstream_metrics_t::fills_total, ngx_brix_cvmfs_upstream_metrics_t::name, ngx_brix_cvmfs_upstream_metrics_t::origin_bytes_total, and ngx_brix_cvmfs_upstream_metrics_t::requests_total.
Referenced by dashboard_fill_cvmfs().
cvmfs_json_upstream_is_dup()
static int cvmfs_json_upstream_is_dup (const ngx_brix_cvmfs_upstream_metrics_t * ups, ngx_uint_t i) static
Definition at line 52 of file api_cvmfs.c.
References BRIX_CVMFS_REPO_READY, and name.
Referenced by dashboard_fill_cvmfs().
dashboard_build_v1_cvmfs()
json_t * dashboard_build_v1_cvmfs (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t redact)
Definition at line 252 of file api_cvmfs.c.
References dashboard_fill_cvmfs(), and dashboard_new_v1_root().
Referenced by ngx_http_brix_dashboard_api_handler().
dashboard_fill_cvmfs()
void dashboard_fill_cvmfs (json_t * target, ngx_uint_t redact)
Definition at line 166 of file api_cvmfs.c.
References BRIX_CVMFS_CLASS_COUNT, BRIX_CVMFS_REPO_READY, BRIX_CVMFS_REPO_SLOTS, BRIX_CVMFS_UPSTREAM_SLOTS, c, ngx_brix_metrics_t::cvmfs, cvmfs_json_repo(), cvmfs_json_repo_is_dup(), cvmfs_json_requests(), cvmfs_json_upstream(), cvmfs_json_upstream_is_dup(), ngx_brix_shm_zone, ngx_brix_cvmfs_repo_metrics_t::state, and ngx_brix_cvmfs_upstream_metrics_t::state.
Referenced by dashboard_build_v1_cvmfs(), and dashboard_build_v1_snapshot().
Variable Documentation
cvmfs_json_class_names
const char* cvmfs_json_class_names[BRIX_CVMFS_CLASS_COUNT] static
Initial value:
= {
    "cas",
    "manifest",
    "geo",
    "reject",
}
Definition at line 23 of file api_cvmfs.c.
Referenced by cvmfs_json_requests().