nginx-xrootd: src/observability/dashboard/api_admin.h File Reference
api_admin.h File Reference
#include "dashboard_http.h"
Functions
ngx_int_t brix_admin_dispatch (ngx_http_request_t *r)
char * brix_admin_set_allow (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_admin_set_secret (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_admin_set_proxy_allow (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Function Documentation
brix_admin_dispatch()
ngx_int_t brix_admin_dispatch (ngx_http_request_t * r)
Definition at line 590 of file api_admin.c.
References admin_audit(), admin_route_cluster(), admin_route_io_uring(), admin_route_proxy(), admin_send_error(), BRIX_ADMIN_AUTH_OK, brix_admin_check_auth(), and ngx_http_brix_dashboard_module.
Referenced by ngx_http_brix_dashboard_main_handler().
brix_admin_set_allow()
char * brix_admin_set_allow (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 72 of file api_admin_config.c.
References ngx_http_brix_dashboard_loc_conf_t::admin_allow.
brix_admin_set_proxy_allow()
char * brix_admin_set_proxy_allow (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 282 of file api_admin_proxy.c.
References ngx_http_brix_dashboard_loc_conf_t::admin_proxy_allow.
brix_admin_set_secret()
char * brix_admin_set_secret (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 122 of file api_admin_config.c.
References ngx_http_brix_dashboard_loc_conf_t::admin_secret, ADMIN_SECRET_MAX, ADMIN_SECRET_MIN, ngx_memcpy, and ngx_pnalloc().