nginx-xrootd: src/observability/dashboard/api.c File Reference
api.c File Reference
#include "dashboard_api_internal.h"
Macros
#define X(ID, metric_label, dash_name, http_plane) dash_name,
Functions
const char * dashboard_direction_name (uint8_t direction)
const char * dashboard_proto_name (uint8_t proto)
const char * dashboard_state_name (const ngx_http_brix_dashboard_loc_conf_t *conf, uint8_t state, int64_t idle_ms, int moving)
const char * dashboard_tpc_protocol_name (ngx_uint_t protocol)
const char * dashboard_tpc_direction_name (ngx_uint_t direction)
const char * dashboard_tpc_state_name (ngx_uint_t state)
const char * dashboard_event_class_name (uint8_t class_id)
uint32_t dashboard_session_hash (const u_char sessid[16])
uint64_t dashboard_avg_bps (int64_t bytes, int64_t start_ms, int64_t now_ms)
ngx_uint_t dashboard_endpoint_is_anon_allowed (brix_dashboard_api_endpoint_e e)
static json_t * dashboard_dispatch_builder (ngx_http_request_t *r, brix_dashboard_api_endpoint_e endpoint, int64_t now_ms, ngx_http_brix_dashboard_loc_conf_t *conf, brix_dashboard_totals_t *totals, ngx_uint_t redact, ngx_int_t *status)
ngx_int_t ngx_http_brix_dashboard_api_handler (ngx_http_request_t *r, brix_dashboard_api_endpoint_e endpoint)
Macro Definition Documentation
X
#define X (ID, metric_label, dash_name, http_plane) dash_name,
Function Documentation
dashboard_avg_bps()
uint64_t dashboard_avg_bps (int64_t bytes, int64_t start_ms, int64_t now_ms)
Definition at line 134 of file api.c.
Referenced by dashboard_collect_protocols(), and dashboard_snapshot_slot().
dashboard_direction_name()
const char * dashboard_direction_name (uint8_t direction)
Definition at line 8 of file api.c.
References BRIX_XFER_DIR_TPC, and BRIX_XFER_DIR_WRITE.
Referenced by dashboard_emit_base_fields().
dashboard_dispatch_builder()
static json_t * dashboard_dispatch_builder (ngx_http_request_t * r, brix_dashboard_api_endpoint_e endpoint, int64_t now_ms, ngx_http_brix_dashboard_loc_conf_t * conf, brix_dashboard_totals_t * totals, ngx_uint_t redact, ngx_int_t * status) static
Definition at line 197 of file api.c.
References BRIX_DASHBOARD_API_COMPAT_TRANSFERS, BRIX_DASHBOARD_API_V1_CACHE, BRIX_DASHBOARD_API_V1_CLUSTER, BRIX_DASHBOARD_API_V1_CVMFS, BRIX_DASHBOARD_API_V1_EVENTS, BRIX_DASHBOARD_API_V1_HISTORY, BRIX_DASHBOARD_API_V1_NOT_FOUND, BRIX_DASHBOARD_API_V1_RATELIMIT, BRIX_DASHBOARD_API_V1_SNAPSHOT, BRIX_DASHBOARD_API_V1_TRANSFER_DETAIL, BRIX_DASHBOARD_API_V1_TRANSFERS, dashboard_build_compat_transfers(), dashboard_build_v1_cache(), dashboard_build_v1_cluster(), dashboard_build_v1_cvmfs(), dashboard_build_v1_events(), dashboard_build_v1_history(), dashboard_build_v1_not_found(), dashboard_build_v1_ratelimit(), dashboard_build_v1_snapshot(), dashboard_build_v1_transfer_detail(), and dashboard_build_v1_transfers().
Referenced by ngx_http_brix_dashboard_api_handler().
dashboard_endpoint_is_anon_allowed()
ngx_uint_t dashboard_endpoint_is_anon_allowed (brix_dashboard_api_endpoint_e e)
Definition at line 159 of file api.c.
References BRIX_DASHBOARD_API_COMPAT_TRANSFERS, BRIX_DASHBOARD_API_V1_CACHE, BRIX_DASHBOARD_API_V1_CLUSTER, BRIX_DASHBOARD_API_V1_CVMFS, BRIX_DASHBOARD_API_V1_EVENTS, BRIX_DASHBOARD_API_V1_HISTORY, BRIX_DASHBOARD_API_V1_NOT_FOUND, BRIX_DASHBOARD_API_V1_RATELIMIT, BRIX_DASHBOARD_API_V1_SNAPSHOT, BRIX_DASHBOARD_API_V1_TRANSFER_DETAIL, and BRIX_DASHBOARD_API_V1_TRANSFERS.
Referenced by ngx_http_brix_dashboard_api_handler().
dashboard_event_class_name()
const char * dashboard_event_class_name (uint8_t class_id)
Definition at line 96 of file api.c.
References BRIX_DASH_EVENT_AUTH, BRIX_DASH_EVENT_DASHBOARD, BRIX_DASH_EVENT_IO, BRIX_DASH_EVENT_NAMESPACE, and BRIX_DASH_EVENT_TPC.
Referenced by dashboard_build_events().
dashboard_proto_name()
const char * dashboard_proto_name (uint8_t proto)
Definition at line 19 of file api.c.
References BRIX_PROTO_LIST, BRIX_XFER_NPROTOS, and X.
Referenced by dashboard_build_events(), dashboard_build_protocols(), dashboard_emit_base_fields(), and dashboard_fill_history().
dashboard_session_hash()
uint32_t dashboard_session_hash (const u_char sessid[16])
Definition at line 117 of file api.c.
Referenced by dashboard_emit_detail_fields().
dashboard_state_name()
const char * dashboard_state_name (const ngx_http_brix_dashboard_loc_conf_t * conf, uint8_t state, int64_t idle_ms, int moving)
Definition at line 37 of file api.c.
References BRIX_XFER_STATE_CLOSING, BRIX_XFER_STATE_ERROR, ngx_http_brix_dashboard_loc_conf_t::idle_threshold_ms, and ngx_http_brix_dashboard_loc_conf_t::stalled_threshold_ms.
Referenced by dashboard_emit_v1_fields().
dashboard_tpc_direction_name()
const char * dashboard_tpc_direction_name (ngx_uint_t direction)
Definition at line 72 of file api.c.
References BRIX_TPC_DIR_PULL, and BRIX_TPC_DIR_PUSH.
Referenced by dashboard_build_tpc_registry().
dashboard_tpc_protocol_name()
const char * dashboard_tpc_protocol_name (ngx_uint_t protocol)
Definition at line 61 of file api.c.
References BRIX_TPC_PROTO_STREAM, and BRIX_TPC_PROTO_WEBDAV.
Referenced by dashboard_build_tpc_registry().
dashboard_tpc_state_name()
const char * dashboard_tpc_state_name (ngx_uint_t state)
Definition at line 83 of file api.c.
References BRIX_TPC_STATE_ACTIVE, BRIX_TPC_STATE_DONE, BRIX_TPC_STATE_ERROR, and BRIX_TPC_STATE_PENDING.
Referenced by dashboard_build_tpc_registry().
ngx_http_brix_dashboard_api_handler()
ngx_int_t ngx_http_brix_dashboard_api_handler (ngx_http_request_t * r, brix_dashboard_api_endpoint_e endpoint)
Definition at line 232 of file api.c.
References ngx_http_brix_dashboard_loc_conf_t::anonymous, BRIX_DASH_EVENT_DASHBOARD, brix_dashboard_event_add(), brix_dashboard_history_sample(), dashboard_build_v1_truncated(), dashboard_collect_totals(), dashboard_dispatch_builder(), dashboard_endpoint_is_anon_allowed(), dashboard_json_send(), ngx_http_brix_dashboard_check_auth(), and ngx_http_brix_dashboard_module.
Referenced by dashboard_dispatch_api_route(), and ngx_http_brix_dashboard_main_handler().