nginx-xrootd: src/protocols/root/response/async.c File Reference
async.c File Reference
#include "core/ngx_brix_module.h"
#include "async.h"
#include "core/compat/alloc_guard.h"
Macros
#define ATTN_BODY_OVERHEAD 16
Functions
size_t brix_attn_asyncms_frame_len (size_t msglen)
void brix_build_attn_asyncms_frame (u_char *buf, const char *msg, size_t msglen)
ngx_int_t brix_send_attn_asyncms (brix_ctx_t *ctx, ngx_connection_t *c, const char *msg, size_t msglen)
ngx_int_t brix_send_attn_asynresp (brix_ctx_t *ctx, ngx_connection_t *c, const u_char *deferred_streamid, uint16_t resp_status, const void *body, uint32_t bodylen)
ngx_int_t brix_send_attn (brix_ctx_t *ctx, ngx_connection_t *c, int actnum, const char *msg, size_t msglen)
ngx_int_t brix_handle_async_ab (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_handle_async_di (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_handle_async_ms (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_handle_async_rd (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_handle_async_wt (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_handle_async_av (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_handle_async_unav (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_handle_async_go (brix_ctx_t *ctx, ngx_connection_t *c)
Variables
static const u_char kAttnZeroStreamid [2] = {0, 0}
Macro Definition Documentation
ATTN_BODY_OVERHEAD
#define ATTN_BODY_OVERHEAD 16
Definition at line 41 of file async.c.
Function Documentation
brix_attn_asyncms_frame_len()
size_t brix_attn_asyncms_frame_len (size_t msglen)
Definition at line 45 of file async.c.
References ATTN_BODY_OVERHEAD, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_send_attn_asyncms(), and prepare_emit_stage().
brix_build_attn_asyncms_frame()
void brix_build_attn_asyncms_frame (u_char * buf, const char * msg, size_t msglen)
Definition at line 51 of file async.c.
References ATTN_BODY_OVERHEAD, brix_build_resp_hdr(), kAttnZeroStreamid, kXR_asyncms, kXR_attn, kXR_ok, ngx_memcpy, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_send_attn_asyncms(), and prepare_emit_stage().
brix_handle_async_ab()
ngx_int_t brix_handle_async_ab (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 169 of file async.c.
References brix_send_error(), c, and kXR_Unsupported.
brix_handle_async_av()
ngx_int_t brix_handle_async_av (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 204 of file async.c.
References brix_send_error(), c, and kXR_Unsupported.
brix_handle_async_di()
ngx_int_t brix_handle_async_di (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 176 of file async.c.
References brix_send_error(), c, and kXR_Unsupported.
brix_handle_async_go()
ngx_int_t brix_handle_async_go (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 218 of file async.c.
References brix_send_error(), c, and kXR_Unsupported.
brix_handle_async_ms()
ngx_int_t brix_handle_async_ms (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 183 of file async.c.
References brix_send_error(), c, and kXR_Unsupported.
brix_handle_async_rd()
ngx_int_t brix_handle_async_rd (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 190 of file async.c.
References brix_send_error(), c, and kXR_Unsupported.
brix_handle_async_unav()
ngx_int_t brix_handle_async_unav (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 211 of file async.c.
References brix_send_error(), c, and kXR_Unsupported.
brix_handle_async_wt()
ngx_int_t brix_handle_async_wt (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 197 of file async.c.
References brix_send_error(), c, and kXR_Unsupported.
brix_send_attn()
ngx_int_t brix_send_attn (brix_ctx_t * ctx, ngx_connection_t * c, int actnum, const char * msg, size_t msglen)
Definition at line 146 of file async.c.
References brix_build_resp_hdr(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), c, brix_ctx_recv_t::cur_streamid, kXR_attn, ngx_memcpy, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
brix_send_attn_asyncms()
ngx_int_t brix_send_attn_asyncms (brix_ctx_t * ctx, ngx_connection_t * c, const char * msg, size_t msglen)
Definition at line 83 of file async.c.
References brix_attn_asyncms_frame_len(), brix_build_attn_asyncms_frame(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), and c.
brix_send_attn_asynresp()
ngx_int_t brix_send_attn_asynresp (brix_ctx_t * ctx, ngx_connection_t * c, const u_char * deferred_streamid, uint16_t resp_status, const void * body, uint32_t bodylen)
Definition at line 101 of file async.c.
References ATTN_BODY_OVERHEAD, brix_build_resp_hdr(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), c, kXR_asynresp, kXR_attn, ngx_memcpy, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_open_send_response(), brix_ssi_deliver_alert(), ssi_push_error(), ssi_push_reply(), and stage_waiter_deliver_one().
Variable Documentation
kAttnZeroStreamid
const u_char kAttnZeroStreamid[2] = {0, 0} static
Definition at line 37 of file async.c.
Referenced by brix_build_attn_asyncms_frame().