nginx-xrootd: src/net/httpguard/audit_handler.c File Reference
audit_handler.c File Reference
#include "guard_http.h"
Functions
static guard_outcome_t status_to_outcome (ngx_uint_t status)
ngx_int_t ngx_http_brix_guard_log_handler (ngx_http_request_t *r)
Function Documentation
ngx_http_brix_guard_log_handler()
ngx_int_t ngx_http_brix_guard_log_handler (ngx_http_request_t * r)
Definition at line 55 of file audit_handler.c.
References ngx_http_brix_guard_ctx_t::bounced, BRIX_GUARD_IP_BUF, BRIX_GUARD_PATH_BUF, ngx_http_brix_guard_loc_conf_t::enable, guard_classify_post(), GUARD_R_NONE, ngx_http_brix_guard_build_request(), ngx_http_brix_guard_module, ngx_http_brix_guard_write_audit(), guard_request_t::outcome, ngx_http_brix_guard_loc_conf_t::ruleset, guard_request_t::status_code, and status_to_outcome().
Referenced by ngx_http_brix_guard_postconf().
status_to_outcome()
static guard_outcome_t status_to_outcome (ngx_uint_t status) static
Definition at line 27 of file audit_handler.c.
References OUTCOME_AUTHFAIL, OUTCOME_ERROR, OUTCOME_NOTFOUND, and OUTCOME_OK.
Referenced by ngx_http_brix_guard_log_handler().