nginx-xrootd: src/auth/authz/acc/audit.c File Reference
audit.c File Reference
#include "acc.h"
Macros
#define BRIX_ACC_AUDIT_DENY 0x1
#define BRIX_ACC_AUDIT_GRANT 0x2
Functions
static void acc_audit_sanitize (u_char *dst, size_t cap, const char *src)
void brix_acc_audit (ngx_log_t *log, ngx_uint_t level, int granted, const char *op, const char *id, const char *host, const char *path)
Macro Definition Documentation
BRIX_ACC_AUDIT_DENY
#define BRIX_ACC_AUDIT_DENY 0x1
Definition at line 18 of file audit.c.
BRIX_ACC_AUDIT_GRANT
#define BRIX_ACC_AUDIT_GRANT 0x2
Definition at line 19 of file audit.c.
Function Documentation
acc_audit_sanitize()
static void acc_audit_sanitize (u_char * dst, size_t cap, const char * src) static
Definition at line 24 of file audit.c.
References c.
Referenced by brix_acc_audit().
brix_acc_audit()
void brix_acc_audit (ngx_log_t * log, ngx_uint_t level, int granted, const char * op, const char * id, const char * host, const char * path)
Definition at line 44 of file audit.c.
References acc_audit_sanitize(), BRIX_ACC_AUDIT_DENY, BRIX_ACC_AUDIT_GRANT, host, log, and op.
Referenced by brix_acc_gate_engine(), and brix_acc_http_authorize().