nginx-xrootd: src/auth/gsi/delegation.c File Reference
delegation.c File Reference
#include "gsi_internal.h"
#include "gsi_core.h"
#include "delegation.h"
#include "proxy_req.h"
#include "protocols/root/protocol/gsi.h"
#include "protocols/root/response/response.h"
#include "protocols/root/connection/write_helpers.h"
#include "core/compat/alloc_guard.h"
#include <string.h>
#include <stdlib.h>
#include <openssl/x509.h>
#include <openssl/pem.h>
#include <openssl/bio.h>
Data Structures
struct bdg_ctx
Functions
static u_char * gsi_pem_export (X509 *one, STACK_OF(X509) *chain, size_t *len)
static u_char * gsi_req_der_to_pem (const u_char *der, size_t der_len, size_t *pem_len)
static int gsi_session_cipher (brix_ctx_t *ctx, brix_gsi_cipher_t *cipher)
void brix_gsi_delegation_cleanup (brix_ctx_t *ctx)
static ngx_int_t bdg_fail (bdg_ctx *b)
ngx_int_t brix_gsi_begin_delegation (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, X509 *leaf, STACK_OF(X509) *chain)
ngx_int_t brix_gsi_handle_sigpxy (brix_ctx_t *ctx, ngx_connection_t *c)
Function Documentation
bdg_fail()
static ngx_int_t bdg_fail (bdg_ctx * b) static
Definition at line 169 of file delegation.c.
References brix_gbuf_free(), bdg_ctx::chain_pem, bdg_ctx::enc, bdg_ctx::inner, bdg_ctx::leaf_pem, bdg_ctx::outer, bdg_ctx::req_der, bdg_ctx::req_pem, and bdg_ctx::reqkey.
Referenced by brix_gsi_begin_delegation().
brix_gsi_begin_delegation()
ngx_int_t brix_gsi_begin_delegation (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, X509 * leaf, STACK_OF(X509) * chain)
Definition at line 183 of file delegation.c.
References bdg_fail(), brix_build_resp_hdr(), brix_gbuf_bucket(), brix_gbuf_end(), brix_gbuf_init(), brix_gbuf_start(), brix_gsi_build_pxyreq(), brix_gsi_cipher_encrypt(), brix_gsi_rand(), brix_gsi_rsa_encrypt_private(), brix_queue_response(), c, bdg_ctx::chain_len, bdg_ctx::chain_pem, brix_ctx_recv_t::cur_streamid, brix_gsi_buf_t::data, brix_ctx_gsi_t::deleg_await, brix_ctx_gsi_t::deleg_chain_len, brix_ctx_gsi_t::deleg_chain_pem, brix_ctx_gsi_t::deleg_client_rtag, brix_ctx_gsi_t::deleg_client_rtag_len, brix_ctx_gsi_t::deleg_reqkey, bdg_ctx::enc, bdg_ctx::enc_len, brix_gbuf::err, brix_ctx_t::gsi, gsi_pem_export(), gsi_req_der_to_pem(), gsi_session_cipher(), bdg_ctx::inner, kXGS_pxyreq, kXR_authmore, kXRS_cipher_alg, kXRS_main, kXRS_rtag, kXRS_signed_rtag, kXRS_x509_req, bdg_ctx::leaf_pem, brix_gbuf::len, brix_gsi_buf_t::len, ngx_memcpy, bdg_ctx::outer, brix_gbuf::p, brix_ctx_t::recv, bdg_ctx::req_der, bdg_ctx::req_len, bdg_ctx::req_pem, bdg_ctx::req_pem_len, bdg_ctx::reqkey, brix_ctx_gsi_t::sess_cipher, brix_ctx_gsi_t::sess_key, brix_ctx_gsi_t::sess_use_iv, and XRD_RESPONSE_HDR_LEN.
Referenced by gsi_auth_step_cert().
brix_gsi_delegation_cleanup()
void brix_gsi_delegation_cleanup (brix_ctx_t * ctx)
Definition at line 121 of file delegation.c.
References brix_ctx_gsi_t::client_fullproxy_len, brix_ctx_gsi_t::client_fullproxy_pem, brix_ctx_gsi_t::deleg_await, brix_ctx_gsi_t::deleg_chain_len, brix_ctx_gsi_t::deleg_chain_pem, brix_ctx_gsi_t::deleg_proxy_len, brix_ctx_gsi_t::deleg_proxy_pem, brix_ctx_gsi_t::deleg_reqkey, brix_ctx_t::gsi, brix_ctx_gsi_t::sess_key, and brix_ctx_gsi_t::sess_keylen.
Referenced by brix_release_disconnect_crypto_state().
brix_gsi_handle_sigpxy()
ngx_int_t brix_gsi_handle_sigpxy (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 312 of file delegation.c.
References brix_gsi_assemble_proxy(), brix_gsi_cipher_decrypt(), brix_gsi_find_bucket(), c, brix_ctx_recv_t::cur_dlen, brix_gsi_buf_t::data, brix_ctx_gsi_t::deleg_await, brix_ctx_gsi_t::deleg_chain_len, brix_ctx_gsi_t::deleg_chain_pem, brix_ctx_gsi_t::deleg_proxy_len, brix_ctx_gsi_t::deleg_proxy_pem, brix_ctx_gsi_t::deleg_reqkey, brix_ctx_login_t::dn, brix_ctx_t::gsi, gsi_session_cipher(), kXRS_main, kXRS_x509, brix_ctx_t::login, ngx_memcpy, brix_ctx_recv_t::payload, plain_len, brix_ctx_t::recv, brix_ctx_gsi_t::sess_key, brix_ctx_gsi_t::sess_keylen, and brix_ctx_gsi_t::sess_use_iv.
Referenced by gsi_auth_step_sigpxy().
gsi_pem_export()
static u_char * gsi_pem_export (X509 * one, STACK_OF(X509) * chain, size_t * len) static
Definition at line 35 of file delegation.c.
Referenced by brix_gsi_begin_delegation().
gsi_req_der_to_pem()
static u_char * gsi_req_der_to_pem (const u_char * der, size_t der_len, size_t * pem_len) static
Definition at line 79 of file delegation.c.
Referenced by brix_gsi_begin_delegation().
gsi_session_cipher()
static int gsi_session_cipher (brix_ctx_t * ctx, brix_gsi_cipher_t * cipher) static
Definition at line 108 of file delegation.c.
References brix_gsi_cipher_lookup(), brix_ctx_t::gsi, brix_ctx_gsi_t::sess_cipher, and brix_ctx_gsi_t::sess_keylen.
Referenced by brix_gsi_begin_delegation(), and brix_gsi_handle_sigpxy().