nginx-xrootd: src/auth/authz/authdb.c File Reference
authdb.c File Reference
#include "core/ngx_brix_module.h"
#include <stddef.h>
#include <string.h>
#include <ctype.h>
#include <stdlib.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include "fs/path/path_internal.h"
Functions
ngx_int_t brix_finalize_authdb_rules (ngx_log_t *log, const ngx_str_t *root, ngx_array_t *rules)
static uint32_t brix_parse_privs (const char *p, size_t len)
ngx_int_t brix_parse_authdb (ngx_conf_t *cf, ngx_str_t *filename, ngx_array_t *rules)
static ngx_flag_t brix_path_prefix_match (const char *prefix, const char *path)
static ngx_flag_t brix_authdb_addr_prefix_match (const u_char *a, const u_char *b, ngx_uint_t bits)
static ngx_flag_t brix_authdb_host_cidr_match (const char *rule_id, const char *peer_ip)
static ngx_flag_t brix_authdb_host_match (const ngx_str_t *rule_id, const char *peer_ip)
const brix_authdb_rule_t * brix_find_authdb_rule_identity (const char *resolved_path, ngx_array_t *rules, const brix_identity_t *identity, const char *peer_ip, uint32_t needed_privs)
const brix_authdb_rule_t * brix_find_authdb_rule (const char *resolved_path, ngx_array_t *rules, brix_ctx_t *ctx, uint32_t needed_privs)
ngx_int_t brix_check_authdb_identity (ngx_log_t *log, ngx_array_t *rules, const brix_identity_t *identity, const char *peer_ip, const char *resolved_path, uint32_t needed_privs)
ngx_int_t brix_check_authdb (brix_ctx_t *ctx, const char *resolved_path, uint32_t needed_privs)
Function Documentation
brix_authdb_addr_prefix_match()
static ngx_flag_t brix_authdb_addr_prefix_match (const u_char * a, const u_char * b, ngx_uint_t bits) static
Definition at line 241 of file authdb.c.
Referenced by brix_authdb_host_cidr_match().
brix_authdb_host_cidr_match()
static ngx_flag_t brix_authdb_host_cidr_match (const char * rule_id, const char * peer_ip) static
Definition at line 271 of file authdb.c.
References brix_authdb_addr_prefix_match().
Referenced by brix_authdb_host_match().
brix_authdb_host_match()
static ngx_flag_t brix_authdb_host_match (const ngx_str_t * rule_id, const char * peer_ip) static
Definition at line 333 of file authdb.c.
References brix_authdb_host_cidr_match().
Referenced by brix_find_authdb_rule_identity().
brix_check_authdb()
ngx_int_t brix_check_authdb (brix_ctx_t * ctx, const char * resolved_path, uint32_t needed_privs)
Definition at line 499 of file authdb.c.
References ngx_stream_brix_srv_conf_t::authdb_rules, brix_check_authdb_identity(), brix_ctx_login_t::dn, brix_identity_t::dn, brix_ctx_t::identity, brix_ctx_t::login, ngx_stream_brix_module, brix_ctx_login_t::peer_ip, brix_ctx_t::session, brix_identity_t::vo_csv, and brix_ctx_login_t::vo_list.
Referenced by brix_auth_gate_op(), brix_authz_check(), and brix_handle_statx().
brix_check_authdb_identity()
ngx_int_t brix_check_authdb_identity (ngx_log_t * log, ngx_array_t * rules, const brix_identity_t * identity, const char * peer_ip, const char * resolved_path, uint32_t needed_privs)
Definition at line 462 of file authdb.c.
References brix_find_authdb_rule_identity(), brix_identity_dn_cstr(), brix_identity_vo_csv_cstr(), brix_sanitize_log_string(), and log.
Referenced by brix_check_authdb(), and ngx_http_brix_webdav_access_handler().
brix_finalize_authdb_rules()
ngx_int_t brix_finalize_authdb_rules (ngx_log_t * log, const ngx_str_t * root, ngx_array_t * rules)
Definition at line 15 of file authdb.c.
References brix_finalize_path_rules(), and log.
Referenced by brix_config_finalize_policy(), and ngx_http_brix_webdav_merge_loc_conf().
brix_find_authdb_rule()
const brix_authdb_rule_t * brix_find_authdb_rule (const char * resolved_path, ngx_array_t * rules, brix_ctx_t * ctx, uint32_t needed_privs)
Definition at line 432 of file authdb.c.
References brix_find_authdb_rule_identity(), brix_ctx_login_t::dn, brix_identity_t::dn, brix_ctx_t::identity, brix_ctx_t::login, brix_ctx_login_t::peer_ip, brix_identity_t::vo_csv, and brix_ctx_login_t::vo_list.
brix_find_authdb_rule_identity()
const brix_authdb_rule_t * brix_find_authdb_rule_identity (const char * resolved_path, ngx_array_t * rules, const brix_identity_t * identity, const char * peer_ip, uint32_t needed_privs)
Definition at line 349 of file authdb.c.
References BRIX_AUTH_ALL, BRIX_AUTH_GROUP, BRIX_AUTH_USER, BRIX_AUTHDB_HOST, brix_authdb_host_match(), brix_identity_dn_cstr(), brix_identity_vo_csv_cstr(), brix_path_prefix_match(), and brix_vo_list_contains().
Referenced by brix_check_authdb_identity(), and brix_find_authdb_rule().
brix_parse_authdb()
ngx_int_t brix_parse_authdb (ngx_conf_t * cf, ngx_str_t * filename, ngx_array_t * rules)
Definition at line 53 of file authdb.c.
References brix_parse_privs(), brix_authdb_rule_t::id, ngx_memcpy, ngx_stream_brix_module, brix_authdb_rule_t::path, brix_authdb_rule_t::privs, brix_authdb_rule_t::resolved, and brix_authdb_rule_t::type.
Referenced by brix_conf_set_authdb(), and webdav_conf_authdb().
brix_parse_privs()
static uint32_t brix_parse_privs (const char * p, size_t len) static
Definition at line 26 of file authdb.c.
References BRIX_AUTH_ADMIN, BRIX_AUTH_DELETE, BRIX_AUTH_LOOKUP, BRIX_AUTH_MKDIR, BRIX_AUTH_READ, and BRIX_AUTH_UPDATE.
Referenced by brix_parse_authdb().
brix_path_prefix_match()
static ngx_flag_t brix_path_prefix_match (const char * prefix, const char * path) static
Definition at line 220 of file authdb.c.
Referenced by brix_find_authdb_rule_identity().