nginx-xrootd: src/auth/authz/auth_gate.h File Reference
auth_gate.h File Reference
#include "core/ngx_brix_module.h"
Functions
ngx_int_t brix_auth_gate (brix_ctx_t *ctx, ngx_connection_t *c, ngx_uint_t op_id, const char *op_name, const char *reqpath, const char *resolved, ngx_stream_brix_srv_conf_t *conf, int auth_level, int need_write)
ngx_int_t brix_auth_gate_op (brix_ctx_t *ctx, ngx_connection_t *c, ngx_uint_t op_id, const char *op_name, const char *reqpath, const char *resolved, ngx_stream_brix_srv_conf_t *conf, int auth_level, int need_write, brix_acc_op_t aop)
ngx_int_t brix_authz_check (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *reqpath, const char *resolved, const char *op_name, int auth_level, brix_acc_op_t aop)
Function Documentation
brix_auth_gate()
ngx_int_t brix_auth_gate (brix_ctx_t * ctx, ngx_connection_t * c, ngx_uint_t op_id, const char * op_name, const char * reqpath, const char * resolved, ngx_stream_brix_srv_conf_t * conf, int auth_level, int need_write)
Definition at line 331 of file auth_gate.c.
References BRIX_AOP_ANY, brix_auth_gate_op(), and c.
Referenced by brix_dispatch_op(), brix_handle_dirlist(), brix_handle_fattr(), brix_handle_link(), brix_handle_locate(), brix_handle_mkdir(), brix_handle_open(), brix_handle_readlink(), brix_handle_setattr(), brix_handle_stat(), brix_handle_symlink(), brix_handle_truncate(), brix_open_cached_read(), brix_query_ckscan(), brix_query_cksum_path(), brix_query_opaquf(), and brix_query_xattr().
brix_auth_gate_op()
ngx_int_t brix_auth_gate_op (brix_ctx_t * ctx, ngx_connection_t * c, ngx_uint_t op_id, const char * op_name, const char * reqpath, const char * resolved, ngx_stream_brix_srv_conf_t * conf, int auth_level, int need_write, brix_acc_op_t aop)
Definition at line 213 of file auth_gate.c.
References ngx_stream_brix_srv_conf_t::acc, brix_auth_cache_val_t::allowed, ngx_stream_brix_srv_conf_t::auth_cache, ngx_stream_brix_srv_conf_t::auth_l1, brix_acc_gate_engine(), BRIX_AOP_ANY, brix_auth_gate_cache_key(), brix_auth_gate_cache_put(), brix_auth_l1_create(), brix_auth_l1_lookup(), brix_auth_l1_store(), BRIX_AUTHDB_FORMAT_XRDACC, brix_check_authdb(), brix_check_token_scope(), brix_check_vo_acl_identity(), brix_kv_get(), brix_log_access(), BRIX_OP_ERR, BRIX_RESIL_METRIC_INC, brix_send_error(), c, brix_acc_conf_t::format, brix_ctx_t::identity, brix_auth_cache_conf_t::kv, kXR_NotAuthorized, brix_ctx_t::login, brix_ctx_login_t::peer_ip, brix_auth_cache_conf_t::ttl_secs, ngx_stream_brix_srv_conf_t::vo_rules, and brix_ctx_t::write_rc.
Referenced by brix_auth_gate(), brix_handle_mv(), and brix_handle_open().
brix_authz_check()
ngx_int_t brix_authz_check (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * reqpath, const char * resolved, const char * op_name, int auth_level, brix_acc_op_t aop)
Definition at line 118 of file auth_gate.c.
References ngx_stream_brix_srv_conf_t::acc, brix_acc_gate_engine(), BRIX_AUTHDB_FORMAT_XRDACC, brix_check_authdb(), c, and brix_acc_conf_t::format.
Referenced by brix_handle_open(), brix_prepare_check_path(), and brix_query_prep_status().