nginx-xrootd: src/protocols/s3/auth_sigv4_verify.c File Reference
auth_sigv4_verify.c File Reference
#include "s3.h"
#include "auth_bearer.h"
#include "s3_auth_internal.h"
#include "auth_sigv4_verify_internal.h"
#include "observability/metrics/unified.h"
#include <string.h>
#include <openssl/crypto.h>
Functions
void s3_record_auth_result (ngx_uint_t result)
static ngx_flag_t s3_signed_headers_contains (const char *signed_hdrs, const char *name)
static ngx_flag_t s3_request_has_session_token (ngx_http_request_t *r, ngx_flag_t presigned)
static ngx_int_t s3_sigv4_bearer_intercept (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, brix_identity_t *identity)
static ngx_int_t s3_sigv4_parse_authz_header (ngx_http_request_t *r, sigv4_components_t *comp)
static ngx_int_t s3_sigv4_check_session_token (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const sigv4_components_t *comp)
static ngx_int_t s3_sigv4_finish (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const sigv4_components_t *comp, brix_identity_t *identity, const u_char k4[32], const char *amz_date)
ngx_int_t s3_verify_sigv4 (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, brix_identity_t *identity)
Function Documentation
s3_record_auth_result()
void s3_record_auth_result (ngx_uint_t result)
Definition at line 44 of file auth_sigv4_verify.c.
References BRIX_AUTHN_NONE, BRIX_AUTHN_S3KEY, brix_metric_auth(), BRIX_PROTO_S3, BRIX_S3_AUTH_ANONYMOUS, BRIX_S3_AUTH_MISSING, BRIX_S3_AUTH_SIGV4_OK, and BRIX_S3_METRIC_INC.
Referenced by s3_reject_bad_amz_date(), s3_reject_clock_skew(), s3_sigv4_bearer_intercept(), s3_sigv4_check_session_token(), s3_sigv4_compare(), s3_sigv4_compute_signature(), s3_sigv4_finish(), s3_sigv4_parse_authz_header(), s3_sigv4_resolve_request_time(), and s3_verify_sigv4().
s3_request_has_session_token()
static ngx_flag_t s3_request_has_session_token (ngx_http_request_t * r, ngx_flag_t presigned) static
Definition at line 121 of file auth_sigv4_verify.c.
References get_header().
Referenced by s3_sigv4_check_session_token().
s3_signed_headers_contains()
static ngx_flag_t s3_signed_headers_contains (const char * signed_hdrs, const char * name) static
Definition at line 75 of file auth_sigv4_verify.c.
References name.
Referenced by s3_sigv4_check_session_token().
s3_sigv4_bearer_intercept()
static ngx_int_t s3_sigv4_bearer_intercept (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, brix_identity_t * identity) static
Definition at line 159 of file auth_sigv4_verify.c.
References BRIX_S3_AUTH_MALFORMED, BRIX_S3_AUTH_MISSING, get_header(), s3_bearer_present(), s3_record_auth_result(), s3_send_xml_error(), s3_verify_bearer(), and ngx_http_s3_loc_conf_t::token_enable.
Referenced by s3_verify_sigv4().
s3_sigv4_check_session_token()
static ngx_int_t s3_sigv4_check_session_token (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const sigv4_components_t * comp) static
Definition at line 263 of file auth_sigv4_verify.c.
References ngx_http_s3_loc_conf_t::allow_unsigned_session_token, BRIX_S3_AUTH_MALFORMED, sigv4_components_t::presigned, s3_record_auth_result(), s3_request_has_session_token(), s3_send_xml_error(), s3_signed_headers_contains(), and sigv4_components_t::signed_hdrs.
Referenced by s3_verify_sigv4().
s3_sigv4_finish()
static ngx_int_t s3_sigv4_finish (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const sigv4_components_t * comp, brix_identity_t * identity, const u_char k4[32], const char * amz_date) static
Definition at line 305 of file auth_sigv4_verify.c.
References sigv4_components_t::akid, BRIX_AUTHN_S3KEY, brix_identity_set_subject(), BRIX_S3_AUTH_INTERNAL_ERROR, BRIX_S3_AUTH_SIGV4_OK, sigv4_components_t::date, ngx_http_s3_req_ctx_t::have_sigv4, ngx_http_brix_s3_module, ngx_memcpy, sigv4_components_t::presigned, sigv4_components_t::region, s3_record_auth_result(), sigv4_components_t::signature, ngx_http_s3_req_ctx_t::sigv4_amz_date, ngx_http_s3_req_ctx_t::sigv4_scope, ngx_http_s3_req_ctx_t::sigv4_seed_signature, ngx_http_s3_req_ctx_t::sigv4_signing_key, and ngx_http_s3_loc_conf_t::verify_chunk_signatures.
Referenced by s3_verify_sigv4().
s3_sigv4_parse_authz_header()
static ngx_int_t s3_sigv4_parse_authz_header (ngx_http_request_t * r, sigv4_components_t * comp) static
Definition at line 213 of file auth_sigv4_verify.c.
References BRIX_S3_AUTH_MALFORMED, BRIX_S3_AUTH_MISSING, get_header(), parse_authorization(), parse_presigned_authorization(), s3_record_auth_result(), and s3_send_xml_error().
Referenced by s3_verify_sigv4().
s3_verify_sigv4()
ngx_int_t s3_verify_sigv4 (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, brix_identity_t * identity)
Definition at line 379 of file auth_sigv4_verify.c.
References ngx_http_s3_loc_conf_t::access_key, sigv4_components_t::akid, brix_identity_t::auth_method, BRIX_AUTHN_NONE, BRIX_S3_AUTH_ANONYMOUS, s3_sigv4_sig_out_t::computed_hex, s3_amz_date_out_t::date, s3_sigv4_sig_out_t::k4, s3_record_auth_result(), s3_sigv4_bearer_intercept(), s3_sigv4_check_session_token(), s3_sigv4_compare(), s3_sigv4_compute_signature(), s3_sigv4_finish(), s3_sigv4_parse_authz_header(), and s3_sigv4_resolve_request_time().
Referenced by ngx_http_s3_handler().