nginx-xrootd: src/auth/authz/acc/config.c File Reference
config.c File Reference
#include "core/ngx_brix_module.h"
#include "acc.h"
#include "core/compat/log_diag.h"
#include <sys/stat.h>
Functions
brix_acc_tables_t * brix_acc_build (const char *authdb_path, ngx_int_t gidlifetime, ngx_int_t pgo, const char *nisdomain, const char *gidretran, char spacechar, ngx_int_t encoding, ngx_log_t *log)
static void brix_acc_refresh_handler (ngx_event_t *ev)
static brix_acc_tables_t * brix_acc_http_build (brix_acc_http_t *acc, ngx_log_t *log)
static void brix_acc_http_refresh_handler (ngx_event_t *ev)
static void brix_acc_http_arm_timer (brix_acc_http_t *acc)
void brix_acc_http_init_conf (brix_acc_http_t *acc)
void brix_acc_http_merge_conf (brix_acc_http_t *conf, brix_acc_http_t *prev)
ngx_int_t brix_acc_http_authorize (ngx_pool_t *pool, ngx_log_t *log, brix_acc_http_t *acc, const char *name, const char *host, const char *vorg, const char *role, const char *grp, brix_acc_op_t op, const char *path)
ngx_int_t brix_acc_init_server (ngx_stream_brix_srv_conf_t *xcf, ngx_cycle_t *cycle)
Variables
ngx_conf_enum_t brix_acc_format_modes []
ngx_conf_enum_t brix_acc_audit_modes []
Function Documentation
brix_acc_build()
brix_acc_tables_t * brix_acc_build (const char * authdb_path, ngx_int_t gidlifetime, ngx_int_t pgo, const char * nisdomain, const char * gidretran, char spacechar, ngx_int_t encoding, ngx_log_t * log)
Definition at line 40 of file config.c.
References brix_acc_authfile_parse(), brix_acc_groups_init(), brix_acc_groups_set_gidlifetime(), brix_acc_groups_set_gidretran(), brix_acc_groups_set_nisdomain(), brix_acc_groups_set_primary_only(), and log.
Referenced by brix_acc_http_build(), brix_acc_init_server(), and brix_acc_refresh_handler().
brix_acc_http_arm_timer()
static void brix_acc_http_arm_timer (brix_acc_http_t * acc) static
Definition at line 150 of file config.c.
References brix_acc_http_refresh_handler(), brix_acc_http_t::refresh, brix_acc_http_t::timer, and brix_acc_http_t::timer_armed.
Referenced by brix_acc_http_authorize().
brix_acc_http_authorize()
ngx_int_t brix_acc_http_authorize (ngx_pool_t * pool, ngx_log_t * log, brix_acc_http_t * acc, const char * name, const char * host, const char * vorg, const char * role, const char * grp, brix_acc_op_t op, const char * path)
Definition at line 195 of file config.c.
References brix_acc_http_t::audit, brix_acc_http_t::authdb, brix_acc_access(), brix_acc_audit(), brix_acc_entity_build(), brix_acc_http_arm_timer(), brix_acc_http_build(), brix_acc_op_name(), BRIX_ACC_PRIV_NONE, BRIX_AUTHDB_FORMAT_XRDACC, brix_acc_http_t::format, log, name, and brix_acc_http_t::tables.
Referenced by s3_acc_check(), and webdav_acc_check().
brix_acc_http_build()
static brix_acc_tables_t * brix_acc_http_build (brix_acc_http_t * acc, ngx_log_t * log) static
Definition at line 99 of file config.c.
References brix_acc_http_t::authdb, brix_acc_build(), brix_acc_http_t::encoding, brix_acc_http_t::gidlifetime, brix_acc_http_t::gidretran, log, brix_acc_http_t::nisdomain, brix_acc_http_t::pgo, and brix_acc_http_t::spacechar.
Referenced by brix_acc_http_authorize(), and brix_acc_http_refresh_handler().
brix_acc_http_init_conf()
void brix_acc_http_init_conf (brix_acc_http_t * acc)
Definition at line 163 of file config.c.
References brix_acc_http_t::audit, brix_acc_http_t::encoding, brix_acc_http_t::format, brix_acc_http_t::gidlifetime, brix_acc_http_t::pgo, brix_acc_http_t::refresh, and brix_acc_http_t::resolve_hosts.
Referenced by ngx_http_brix_webdav_create_loc_conf(), and ngx_http_s3_create_loc_conf().
brix_acc_http_merge_conf()
void brix_acc_http_merge_conf (brix_acc_http_t * conf, brix_acc_http_t * prev)
Definition at line 177 of file config.c.
References brix_acc_http_t::audit, brix_acc_http_t::authdb, BRIX_AUTHDB_AUDIT_NONE, BRIX_AUTHDB_FORMAT_NATIVE, brix_acc_http_t::encoding, brix_acc_http_t::format, brix_acc_http_t::gidlifetime, brix_acc_http_t::gidretran, brix_acc_http_t::nisdomain, brix_acc_http_t::pgo, brix_acc_http_t::refresh, brix_acc_http_t::resolve_hosts, and brix_acc_http_t::spacechar.
Referenced by ngx_http_brix_webdav_merge_loc_conf(), and ngx_http_s3_merge_loc_conf().
brix_acc_http_refresh_handler()
static void brix_acc_http_refresh_handler (ngx_event_t * ev) static
Definition at line 119 of file config.c.
References brix_acc_http_t::authdb, brix_acc_http_build(), brix_acc_tables_free(), brix_acc_http_t::refresh, and brix_acc_http_t::tables.
Referenced by brix_acc_http_arm_timer().
brix_acc_init_server()
ngx_int_t brix_acc_init_server (ngx_stream_brix_srv_conf_t * xcf, ngx_cycle_t * cycle)
Definition at line 239 of file config.c.
References ngx_stream_brix_srv_conf_t::acc, ngx_stream_brix_srv_conf_t::authdb, brix_acc_build(), brix_acc_refresh_handler(), BRIX_AUTHDB_FORMAT_XRDACC, BRIX_DIAG_EMERG, brix_acc_conf_t::encoding, brix_acc_conf_t::format, brix_acc_conf_t::gidlifetime, brix_acc_conf_t::gidretran, ngx_pcalloc(), brix_acc_conf_t::nisdomain, brix_acc_conf_t::pgo, brix_acc_conf_t::refresh, brix_acc_conf_t::spacechar, brix_acc_conf_t::tables, and brix_acc_conf_t::timer.
Referenced by ngx_stream_brix_init_process().
brix_acc_refresh_handler()
static void brix_acc_refresh_handler (ngx_event_t * ev) static
Definition at line 57 of file config.c.
References ngx_stream_brix_srv_conf_t::acc, ngx_stream_brix_srv_conf_t::authdb, brix_acc_build(), brix_acc_tables_free(), brix_acc_conf_t::encoding, brix_acc_conf_t::gidlifetime, brix_acc_conf_t::gidretran, brix_acc_conf_t::nisdomain, brix_acc_conf_t::pgo, brix_acc_conf_t::refresh, brix_acc_conf_t::spacechar, and brix_acc_conf_t::tables.
Referenced by brix_acc_init_server().
Variable Documentation
brix_acc_audit_modes
ngx_conf_enum_t brix_acc_audit_modes[]
Initial value:
= {
    { ngx_string("none"),   0   },
    { ngx_string("deny"),   1   },
    { ngx_string("grant"),  2  },
    { ngx_string("all"),    3    },
    { ngx_null_string,     0                         }
}
Definition at line 31 of file config.c.
Referenced by brix_acc_http_set_audit().
brix_acc_format_modes
ngx_conf_enum_t brix_acc_format_modes[]
Initial value:
= {
    { ngx_string("native"),  0   },
    { ngx_string("xrdacc"),  1   },
    { ngx_null_string,      0                            }
}
Definition at line 25 of file config.c.
Referenced by brix_acc_http_set_format().