nginx-xrootd: src/auth/token/file.h File Reference
file.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
Functions
ngx_int_t brix_token_read_file (const ngx_str_t *path, u_char *buf, size_t buf_sz, size_t *out_len, ngx_log_t *log, const char *label)
Function Documentation
brix_token_read_file()
ngx_int_t brix_token_read_file (const ngx_str_t * path, u_char * buf, size_t buf_sz, size_t * out_len, ngx_log_t * log, const char * label)
Definition at line 164 of file file.c.
References brix_token_label(), brix_token_slurp(), brix_token_trim(), brix_token_validate_args(), brix_token_diag_t::label, log, and brix_token_diag_t::log.
Referenced by brix_upstream_send_token_auth(), proxy_bs_auth_token_file(), proxy_bs_login_sec_ztn(), tpc_read_bearer_token(), and tpc_rfc8693_read_subject().