nginx-xrootd: src/auth/authz/acl.c File Reference
acl.c File Reference
#include "core/ngx_brix_module.h"
#include <stddef.h>
#include <string.h>
#include "fs/path/path_internal.h"
Functions
ngx_int_t brix_finalize_vo_rules (ngx_log_t *log, const ngx_str_t *root, ngx_array_t *rules)
ngx_flag_t brix_vo_list_contains (const char *vo_list, const char *required_vo)
ngx_int_t brix_check_vo_acl (ngx_log_t *log, const char *resolved_path, ngx_array_t *vo_rules, const char *vo_list)
ngx_int_t brix_check_vo_acl_identity (ngx_log_t *log, const char *resolved_path, ngx_array_t *vo_rules, const brix_identity_t *identity)
Function Documentation
brix_check_vo_acl()
ngx_int_t brix_check_vo_acl (ngx_log_t * log, const char * resolved_path, ngx_array_t * vo_rules, const char * vo_list)
Definition at line 60 of file acl.c.
References brix_find_vo_rule(), brix_sanitize_log_string(), brix_vo_list_contains(), log, and brix_vo_rule_t::vo.
Referenced by brix_check_vo_acl_identity().
brix_check_vo_acl_identity()
ngx_int_t brix_check_vo_acl_identity (ngx_log_t * log, const char * resolved_path, ngx_array_t * vo_rules, const brix_identity_t * identity)
Definition at line 94 of file acl.c.
References brix_check_vo_acl(), brix_identity_vo_csv_cstr(), and log.
Referenced by access_apply_authdb(), brix_auth_gate_evaluate(), brix_statx_path_authorized(), prepare_path_authz(), qprep_path_authorized(), and tpc_handle_dest().
brix_finalize_vo_rules()
ngx_int_t brix_finalize_vo_rules (ngx_log_t * log, const ngx_str_t * root, ngx_array_t * rules)
Definition at line 11 of file acl.c.
References brix_finalize_path_rules(), and log.
Referenced by brix_config_finalize_policy(), and webdav_finalize_authz_rules().
brix_vo_list_contains()
ngx_flag_t brix_vo_list_contains (const char * vo_list, const char * required_vo)
Definition at line 22 of file acl.c.
Referenced by adb_group_matches(), brix_append_vo_token(), and brix_check_vo_acl().