nginx-xrootd: src/auth/sss/config.c File Reference
config.c File Reference
#include "core/config/config.h"
#include "core/compat/log_diag.h"
#include "sss_keytab_kernel.h"
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Functions
static ngx_int_t brix_sss_parse_key_line (ngx_conf_t *cf, ngx_array_t *keys, char *line, ngx_uint_t line_no)
ngx_int_t brix_sss_load_keytab (ngx_conf_t *cf, ngx_str_t *path, ngx_array_t **out_keys)
static int brix_sss_upstream_needed (ngx_stream_brix_srv_conf_t *xcf)
ngx_int_t brix_configure_sss_auth (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
Function Documentation
brix_configure_sss_auth()
ngx_int_t brix_configure_sss_auth (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf)
Definition at line 225 of file config.c.
References ngx_stream_brix_srv_conf_t::auth, BRIX_AUTH_SSS, brix_sss_load_keytab(), brix_sss_upstream_needed(), ngx_stream_brix_srv_conf_t::sss_keys, and ngx_stream_brix_srv_conf_t::sss_keytab.
Referenced by ngx_stream_brix_postconfiguration().
brix_sss_load_keytab()
ngx_int_t brix_sss_load_keytab (ngx_conf_t * cf, ngx_str_t * path, ngx_array_t ** out_keys)
Definition at line 92 of file config.c.
References BRIX_DIAG_CONF, BRIX_PATH_REGULAR_FILE, brix_sss_parse_key_line(), brix_validate_path(), close(), fstat(), open(), sss_keytab_mode_ok(), and stat().
Referenced by brix_cms_srv_set_sss_keytab(), and brix_configure_sss_auth().
brix_sss_parse_key_line()
static ngx_int_t brix_sss_parse_key_line (ngx_conf_t * cf, ngx_array_t * keys, char * line, ngx_uint_t line_no) static
Definition at line 33 of file config.c.
References BRIX_SSS_OPT_ALLUSR, BRIX_SSS_OPT_ANYGRP, BRIX_SSS_OPT_ANYUSR, BRIX_SSS_OPT_NOIPCK, BRIX_SSS_OPT_USRGRP, sss_keytab_entry_t::exp, sss_keytab_entry_t::group, sss_keytab_entry_t::id, sss_keytab_entry_t::key, key, sss_keytab_entry_t::key_len, sss_keytab_entry_t::name, sss_keytab_parse_line(), and sss_keytab_entry_t::user.
Referenced by brix_sss_load_keytab().
brix_sss_upstream_needed()
static int brix_sss_upstream_needed (ngx_stream_brix_srv_conf_t * xcf) static
Definition at line 203 of file config.c.
References brix_proxy_conf_t::auth, BRIX_PROXY_AUTH_SSS, brix_proxy_conf_t::enable, ngx_stream_brix_srv_conf_t::proxy, and brix_proxy_conf_t::upstreams.
Referenced by brix_configure_sss_auth().