nginx-xrootd: src/auth/sss/auth_crypto_helpers.c File Reference
auth_crypto_helpers.c File Reference
#include "sss_internal.h"
#include "auth/gsi/gsi_internal.h"
#include "protocols/root/session/registry.h"
#include "core/compat/crc32_ieee.h"
#include "core/compat/sss_bf.h"
#include <errno.h>
#include <openssl/crypto.h>
#include <openssl/evp.h>
#include <openssl/opensslv.h>
#include <string.h>
Functions
uint32_t brix_sss_read_be32 (const u_char *p)
uint64_t brix_sss_read_be64 (const u_char *p)
void brix_sss_write_be32 (u_char *p, uint32_t v)
uint32_t brix_sss_crc32 (const u_char *p, size_t len)
ngx_int_t brix_sss_bf32_crypt (int encrypt, const u_char *key, size_t key_len, const u_char *src, size_t src_len, u_char *dst, size_t dst_len, size_t *out_len)
const brix_sss_key_t * brix_sss_find_key_arr (ngx_array_t *keys_arr, int64_t id)
const brix_sss_key_t * brix_sss_find_key (ngx_stream_brix_srv_conf_t *conf, int64_t id)
ngx_int_t brix_sss_verify_blob (ngx_array_t *keys, time_t lifetime, const u_char *blob, size_t blob_len, brix_sss_identity_t *id_out, const brix_sss_key_t **key_out, char *err, size_t errsz)
Function Documentation
brix_sss_bf32_crypt()
ngx_int_t brix_sss_bf32_crypt (int encrypt, const u_char * key, size_t key_len, const u_char * src, size_t src_len, u_char * dst, size_t dst_len, size_t * out_len)
Definition at line 78 of file auth_crypto_helpers.c.
References brix_sss_bf_crypt(), and key.
Referenced by brix_handle_sss_auth(), brix_sss_send_authmore(), and brix_sss_verify_blob().
brix_sss_crc32()
uint32_t brix_sss_crc32 (const u_char * p, size_t len)
Definition at line 67 of file auth_crypto_helpers.c.
References brix_crc32_ieee().
Referenced by brix_handle_sss_auth(), brix_sss_send_authmore(), and brix_sss_verify_blob().
brix_sss_find_key()
const brix_sss_key_t * brix_sss_find_key (ngx_stream_brix_srv_conf_t * conf, int64_t id)
Definition at line 110 of file auth_crypto_helpers.c.
References brix_sss_find_key_arr(), and ngx_stream_brix_srv_conf_t::sss_keys.
Referenced by brix_handle_sss_auth().
brix_sss_find_key_arr()
const brix_sss_key_t * brix_sss_find_key_arr (ngx_array_t * keys_arr, int64_t id)
Definition at line 90 of file auth_crypto_helpers.c.
Referenced by brix_sss_find_key(), and brix_sss_verify_blob().
brix_sss_read_be32()
uint32_t brix_sss_read_be32 (const u_char * p)
Definition at line 34 of file auth_crypto_helpers.c.
Referenced by brix_handle_sss_auth(), brix_sss_read_be64(), and brix_sss_verify_blob().
brix_sss_read_be64()
uint64_t brix_sss_read_be64 (const u_char * p)
Definition at line 43 of file auth_crypto_helpers.c.
References brix_sss_read_be32().
Referenced by brix_handle_sss_auth(), and brix_sss_verify_blob().
brix_sss_verify_blob()
ngx_int_t brix_sss_verify_blob (ngx_array_t * keys, time_t lifetime, const u_char * blob, size_t blob_len, brix_sss_identity_t * id_out, const brix_sss_key_t ** key_out, char * err, size_t errsz)
Definition at line 119 of file auth_crypto_helpers.c.
References BRIX_SSS_BASE_TIME, brix_sss_bf32_crypt(), brix_sss_crc32(), BRIX_SSS_DATA_HDR_LEN, BRIX_SSS_ENC_BF32, brix_sss_find_key_arr(), BRIX_SSS_HDR_LEN, BRIX_SSS_NAME_MAX, BRIX_SSS_OPT_SNDLID, brix_sss_parse_identity(), brix_sss_read_be32(), brix_sss_read_be64(), and key.
Referenced by brix_cms_srv_verify_xauth().
brix_sss_write_be32()
void brix_sss_write_be32 (u_char * p, uint32_t v)
Definition at line 53 of file auth_crypto_helpers.c.
Referenced by brix_sss_send_authmore().