nginx-xrootd: src/protocols/s3/auth_sigv4_parse.c File Reference
auth_sigv4_parse.c File Reference
#include "s3.h"
#include "s3_auth_internal.h"
#include "core/http/http_headers.h"
#include "core/compat/cstr.h"
#include <string.h>
#include <errno.h>
#include <stdlib.h>
Functions
ngx_str_t get_header (ngx_http_request_t *r, const char *name)
static const char * sigv4_find_auth_pair (const char *start, const char *end, const char *name)
static int sigv4_copy_component (const char *value_start, const char *value_end, char *dst, size_t dst_size)
static int sigv4_extract_auth_value (const char *start, const char *end, const char *name, char *dst, size_t dst_size)
static int sigv4_parse_credential_scope (const char *credential, sigv4_components_t *out)
static int sigv4_copy_arg_decoded (ngx_http_request_t *r, const char *name, char *dst, size_t dst_size)
static int sigv4_parse_expires (const char *value, ngx_uint_t *out)
int parse_authorization (const ngx_str_t *auth, sigv4_components_t *out)
int parse_presigned_authorization (ngx_http_request_t *r, sigv4_components_t *out)
Function Documentation
get_header()
ngx_str_t get_header (ngx_http_request_t * r, const char * name)
Definition at line 21 of file auth_sigv4_parse.c.
References brix_http_get_header(), and name.
Referenced by build_canonical_headers(), s3_bearer_present(), s3_request_has_session_token(), s3_verify_bearer(), and s3_verify_sigv4().
parse_authorization()
int parse_authorization (const ngx_str_t * auth, sigv4_components_t * out)
Definition at line 240 of file auth_sigv4_parse.c.
References sigv4_components_t::signature, sigv4_components_t::signed_hdrs, sigv4_extract_auth_value(), and sigv4_parse_credential_scope().
Referenced by s3_verify_sigv4().
parse_presigned_authorization()
int parse_presigned_authorization (ngx_http_request_t * r, sigv4_components_t * out)
Definition at line 294 of file auth_sigv4_parse.c.
References sigv4_components_t::amz_date, sigv4_components_t::amz_expires, brix_str_cbuf(), sigv4_components_t::presigned, sigv4_components_t::signature, sigv4_components_t::signed_hdrs, sigv4_copy_arg_decoded(), sigv4_parse_credential_scope(), and sigv4_parse_expires().
Referenced by s3_verify_sigv4().
sigv4_copy_arg_decoded()
static int sigv4_copy_arg_decoded (ngx_http_request_t * r, const char * name, char * dst, size_t dst_size) static
Definition at line 197 of file auth_sigv4_parse.c.
References brix_http_urldecode(), BRIX_URLDECODE_OK, BRIX_URLDECODE_PLUS_TO_SPACE, BRIX_URLDECODE_REJECT_NUL, and name.
Referenced by parse_presigned_authorization().
sigv4_copy_component()
static int sigv4_copy_component (const char * value_start, const char * value_end, char * dst, size_t dst_size) static
Definition at line 82 of file auth_sigv4_parse.c.
Referenced by sigv4_extract_auth_value(), and sigv4_parse_credential_scope().
sigv4_extract_auth_value()
static int sigv4_extract_auth_value (const char * start, const char * end, const char * name, char * dst, size_t dst_size) static
Definition at line 104 of file auth_sigv4_parse.c.
References name, sigv4_copy_component(), and sigv4_find_auth_pair().
Referenced by parse_authorization().
sigv4_find_auth_pair()
static const char * sigv4_find_auth_pair (const char * start, const char * end, const char * name) static
Definition at line 46 of file auth_sigv4_parse.c.
References name.
Referenced by sigv4_extract_auth_value().
sigv4_parse_credential_scope()
static int sigv4_parse_credential_scope (const char * credential, sigv4_components_t * out) static
Definition at line 143 of file auth_sigv4_parse.c.
References sigv4_components_t::akid, sigv4_components_t::date, sigv4_components_t::region, and sigv4_copy_component().
Referenced by parse_authorization(), and parse_presigned_authorization().
sigv4_parse_expires()
static int sigv4_parse_expires (const char * value, ngx_uint_t * out) static
Definition at line 222 of file auth_sigv4_parse.c.
Referenced by parse_presigned_authorization().