nginx-xrootd: src/auth/sss/auth_identity_challenge.c File Reference
auth_identity_challenge.c File Reference
#include "sss_internal.h"
#include "fs/path/path.h"
#include "protocols/root/response/response.h"
#include <openssl/rand.h>
#include <string.h>
#include "core/compat/alloc_guard.h"
Functions
static void brix_sss_copy_packed_string (char *dst, size_t dst_len, const u_char *src, size_t len)
ngx_int_t brix_sss_parse_identity (const u_char *data, size_t len, brix_sss_identity_t *id)
ngx_int_t brix_sss_auth_failed (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_sss_send_authmore (brix_ctx_t *ctx, ngx_connection_t *c, const brix_sss_key_t *key, const u_char *hdr, size_t hdr_len)
Function Documentation
brix_sss_auth_failed()
ngx_int_t brix_sss_auth_failed (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 127 of file auth_identity_challenge.c.
References BRIX_OP_AUTH, BRIX_RETURN_ERR, c, and kXR_NotAuthorized.
Referenced by brix_handle_sss_auth().
brix_sss_copy_packed_string()
static void brix_sss_copy_packed_string (char * dst, size_t dst_len, const u_char * src, size_t len) static
Definition at line 19 of file auth_identity_challenge.c.
Referenced by brix_sss_parse_identity().
brix_sss_parse_identity()
ngx_int_t brix_sss_parse_identity (const u_char * data, size_t len, brix_sss_identity_t * id)
Definition at line 56 of file auth_identity_challenge.c.
References brix_sss_copy_packed_string(), BRIX_SSS_TYPE_GRPS, BRIX_SSS_TYPE_HOST, BRIX_SSS_TYPE_NAME, BRIX_SSS_TYPE_RAND, brix_sss_identity_t::grps, brix_sss_identity_t::host, brix_sss_identity_t::ip, and brix_sss_identity_t::name.
Referenced by brix_handle_sss_auth(), and brix_sss_verify_blob().
brix_sss_send_authmore()
ngx_int_t brix_sss_send_authmore (brix_ctx_t * ctx, ngx_connection_t * c, const brix_sss_key_t * key, const u_char * hdr, size_t hdr_len)
Definition at line 134 of file auth_identity_challenge.c.
References brix_build_resp_hdr(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), BRIX_SSS_BASE_TIME, brix_sss_bf32_crypt(), brix_sss_crc32(), BRIX_SSS_DATA_HDR_LEN, BRIX_SSS_OPT_USEDATA, BRIX_SSS_TYPE_LGID, brix_sss_write_be32(), c, brix_ctx_recv_t::cur_streamid, key, kXR_authmore, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_handle_sss_auth().