nginx-xrootd: src/protocols/webdav/auth_cert.c File Reference
auth_cert.c File Reference
#include "webdav.h"
#include "auth/crypto/gsi_verify.h"
#include "core/ngx_brix_module.h"
#include <ngx_http_ssl_module.h>
#include <openssl/crypto.h>
#include <openssl/ssl.h>
#include <openssl/x509.h>
#include <openssl/x509_vfy.h>
#include "core/compat/alloc_guard.h"
Data Structures
struct ngx_http_brix_webdav_tls_auth_cache_t
Functions
static void webdav_tls_auth_cache_free (void *parent, void *ptr, CRYPTO_EX_DATA *ad, int idx, long argl, void *argp)
ngx_int_t webdav_auth_init_ssl_indices (ngx_log_t *log)
static ngx_int_t webdav_str_equal (const ngx_str_t *a, const ngx_str_t *b)
static void webdav_free_verify_resources (X509_STORE_CTX *vctx, X509 *leaf)
static ngx_int_t webdav_cache_matches (ngx_http_brix_webdav_tls_auth_cache_t *cache, ngx_http_brix_webdav_loc_conf_t *conf)
static brix_identity_t * webdav_ensure_identity (ngx_http_request_t *r, ngx_http_brix_webdav_req_ctx_t *ctx)
static ngx_int_t webdav_mark_req_verified (ngx_http_request_t *r, ngx_http_brix_webdav_req_ctx_t *ctx, const char *dn, const char *source)
static void webdav_log_auth_cache_reuse (ngx_http_request_t *r, ngx_http_brix_webdav_tls_auth_cache_t *cache, const char *cache_name)
static ngx_int_t webdav_store_tls_auth_cache (ngx_http_request_t *r, SSL *ssl, ngx_http_brix_webdav_loc_conf_t *conf, const char *dn)
static ngx_int_t webdav_extract_and_set_voms_identity (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *ctx, SSL *ssl)
static ngx_int_t webdav_try_cached_tls_auth (ngx_http_request_t *r, SSL *ssl, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *ctx)
static ngx_int_t webdav_nginx_verify_compatible (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t webdav_finish_verified_cert (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *ctx, SSL *ssl, X509 *leaf, const char *source)
ngx_int_t webdav_verify_proxy_cert (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
Variables
static int webdav_ssl_auth_cache_index = -1
static int webdav_ssl_session_auth_cache_index = -1
Function Documentation
webdav_auth_init_ssl_indices()
ngx_int_t webdav_auth_init_ssl_indices (ngx_log_t * log)
Definition at line 70 of file auth_cert.c.
References log, webdav_ssl_auth_cache_index, webdav_ssl_session_auth_cache_index, and webdav_tls_auth_cache_free().
Referenced by ngx_http_brix_webdav_postconfiguration().
webdav_cache_matches()
static ngx_int_t webdav_cache_matches (ngx_http_brix_webdav_tls_auth_cache_t * cache, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 137 of file auth_cert.c.
References ngx_http_brix_webdav_loc_conf_t::ca_store, ngx_http_brix_webdav_tls_auth_cache_t::conf, ngx_http_brix_webdav_tls_auth_cache_t::dn, ngx_http_brix_webdav_tls_auth_cache_t::store, ngx_http_brix_webdav_tls_auth_cache_t::verify_depth, and ngx_http_brix_webdav_loc_conf_t::verify_depth.
Referenced by webdav_store_tls_auth_cache(), and webdav_try_cached_tls_auth().
webdav_ensure_identity()
static brix_identity_t * webdav_ensure_identity (ngx_http_request_t * r, ngx_http_brix_webdav_req_ctx_t * ctx) static
Definition at line 153 of file auth_cert.c.
References brix_identity_alloc(), and ngx_http_brix_webdav_req_ctx_t::identity.
Referenced by webdav_mark_req_verified().
webdav_extract_and_set_voms_identity()
static ngx_int_t webdav_extract_and_set_voms_identity (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * ctx, SSL * ssl) static
Definition at line 295 of file auth_cert.c.
References brix_extract_voms_info(), brix_identity_set_vos_csv(), brix_voms_available(), ngx_http_brix_webdav_req_ctx_t::identity, STACK_OF(), ngx_http_brix_webdav_loc_conf_t::voms_cert_dir, and ngx_http_brix_webdav_loc_conf_t::vomsdir.
Referenced by webdav_finish_verified_cert(), and webdav_try_cached_tls_auth().
webdav_finish_verified_cert()
static ngx_int_t webdav_finish_verified_cert (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * ctx, SSL * ssl, X509 * leaf, const char * source) static
Definition at line 423 of file auth_cert.c.
References brix_sanitize_log_string(), ngx_http_brix_webdav_req_ctx_t::dn, webdav_extract_and_set_voms_identity(), webdav_mark_req_verified(), and webdav_store_tls_auth_cache().
Referenced by webdav_verify_proxy_cert().
webdav_free_verify_resources()
static void webdav_free_verify_resources (X509_STORE_CTX * vctx, X509 * leaf) static
Definition at line 121 of file auth_cert.c.
Referenced by webdav_verify_proxy_cert().
webdav_log_auth_cache_reuse()
static void webdav_log_auth_cache_reuse (ngx_http_request_t * r, ngx_http_brix_webdav_tls_auth_cache_t * cache, const char * cache_name) static
Definition at line 193 of file auth_cert.c.
References ngx_http_brix_webdav_tls_auth_cache_t::reuse_logged.
Referenced by webdav_try_cached_tls_auth().
webdav_mark_req_verified()
static ngx_int_t webdav_mark_req_verified (ngx_http_request_t * r, ngx_http_brix_webdav_req_ctx_t * ctx, const char * dn, const char * source) static
Definition at line 164 of file auth_cert.c.
References ngx_http_brix_webdav_req_ctx_t::auth_source, BRIX_AUTHN_GSI, brix_identity_set_dn(), ngx_http_brix_webdav_req_ctx_t::dn, ngx_http_brix_webdav_req_ctx_t::verified, and webdav_ensure_identity().
Referenced by webdav_finish_verified_cert(), and webdav_try_cached_tls_auth().
webdav_nginx_verify_compatible()
static ngx_int_t webdav_nginx_verify_compatible (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 395 of file auth_cert.c.
References ngx_http_brix_webdav_loc_conf_t::cadir, ngx_http_brix_webdav_loc_conf_t::cafile, ngx_http_brix_webdav_loc_conf_t::crl, and webdav_str_equal().
Referenced by webdav_verify_proxy_cert().
webdav_store_tls_auth_cache()
static ngx_int_t webdav_store_tls_auth_cache (ngx_http_request_t * r, SSL * ssl, ngx_http_brix_webdav_loc_conf_t * conf, const char * dn) static
Definition at line 213 of file auth_cert.c.
References BRIX_PCALLOC_OR_RETURN, ngx_http_brix_webdav_loc_conf_t::ca_store, ngx_http_brix_webdav_tls_auth_cache_t::conf, ngx_http_brix_webdav_tls_auth_cache_t::dn, ngx_http_brix_webdav_tls_auth_cache_t::store, ngx_http_brix_webdav_tls_auth_cache_t::verify_depth, ngx_http_brix_webdav_loc_conf_t::verify_depth, webdav_cache_matches(), webdav_ssl_auth_cache_index, and webdav_ssl_session_auth_cache_index.
Referenced by webdav_finish_verified_cert(), and webdav_try_cached_tls_auth().
webdav_str_equal()
static ngx_int_t webdav_str_equal (const ngx_str_t * a, const ngx_str_t * b) static
Definition at line 102 of file auth_cert.c.
Referenced by webdav_nginx_verify_compatible().
webdav_tls_auth_cache_free()
static void webdav_tls_auth_cache_free (void * parent, void * ptr, CRYPTO_EX_DATA * ad, int idx, long argl, void * argp) static
Definition at line 50 of file auth_cert.c.
Referenced by webdav_auth_init_ssl_indices().
webdav_try_cached_tls_auth()
static ngx_int_t webdav_try_cached_tls_auth (ngx_http_request_t * r, SSL * ssl, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * ctx) static
Definition at line 337 of file auth_cert.c.
References ngx_http_brix_webdav_tls_auth_cache_t::dn, webdav_cache_matches(), webdav_extract_and_set_voms_identity(), webdav_log_auth_cache_reuse(), webdav_mark_req_verified(), webdav_ssl_auth_cache_index, webdav_ssl_session_auth_cache_index, and webdav_store_tls_auth_cache().
Referenced by webdav_verify_proxy_cert().
webdav_verify_proxy_cert()
ngx_int_t webdav_verify_proxy_cert (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 461 of file auth_cert.c.
References brix_gsi_verify_chain(), BRIX_PCALLOC_OR_RETURN, ngx_http_brix_webdav_loc_conf_t::ca_store, ngx_http_brix_webdav_module, STACK_OF(), ngx_http_brix_webdav_req_ctx_t::verified, ngx_http_brix_webdav_loc_conf_t::verify_depth, webdav_finish_verified_cert(), webdav_free_verify_resources(), webdav_nginx_verify_compatible(), and webdav_try_cached_tls_auth().
Referenced by access_try_cert().
Variable Documentation
webdav_ssl_auth_cache_index
int webdav_ssl_auth_cache_index = -1 static
Definition at line 41 of file auth_cert.c.
Referenced by webdav_auth_init_ssl_indices(), webdav_store_tls_auth_cache(), and webdav_try_cached_tls_auth().
webdav_ssl_session_auth_cache_index
int webdav_ssl_session_auth_cache_index = -1 static
Definition at line 42 of file auth_cert.c.
Referenced by webdav_auth_init_ssl_indices(), webdav_store_tls_auth_cache(), and webdav_try_cached_tls_auth().