nginx-xrootd: src/protocols/s3/auth_sigv4_verify_time.c File Reference
auth_sigv4_verify_time.c File Reference
#include "s3.h"
#include "s3_auth_internal.h"
#include "auth_sigv4_verify_internal.h"
#include "core/compat/cstr.h"
#include <string.h>
#include <time.h>
Macros
#define S3_SIGV4_MAX_HEADER_SKEW_SEC 900
#define S3_SIGV4_MAX_FUTURE_SKEW_SEC 900
Functions
static int s3_digit (u_char c)
static int s3_parse_2digits (const char *s)
static int s3_parse_4digits (const char *s)
static ngx_int_t s3_parse_amz_datetime (const char *s, time_t *out)
static ngx_int_t s3_reject_bad_amz_date (ngx_http_request_t *r, const char *message)
static ngx_int_t s3_reject_clock_skew (ngx_http_request_t *r)
static ngx_int_t s3_check_header_clock_skew (ngx_http_request_t *r, time_t request_time)
static ngx_int_t s3_check_presigned_future_skew (ngx_http_request_t *r, time_t request_time)
ngx_int_t s3_sigv4_resolve_request_time (ngx_http_request_t *r, const sigv4_components_t *comp, s3_amz_date_out_t *out)
Macro Definition Documentation
S3_SIGV4_MAX_FUTURE_SKEW_SEC
#define S3_SIGV4_MAX_FUTURE_SKEW_SEC 900
Definition at line 33 of file auth_sigv4_verify_time.c.
S3_SIGV4_MAX_HEADER_SKEW_SEC
#define S3_SIGV4_MAX_HEADER_SKEW_SEC 900
Definition at line 32 of file auth_sigv4_verify_time.c.
Function Documentation
s3_check_header_clock_skew()
static ngx_int_t s3_check_header_clock_skew (ngx_http_request_t * r, time_t request_time) static
Definition at line 185 of file auth_sigv4_verify_time.c.
References s3_reject_clock_skew(), and S3_SIGV4_MAX_HEADER_SKEW_SEC.
Referenced by s3_sigv4_resolve_request_time().
s3_check_presigned_future_skew()
static ngx_int_t s3_check_presigned_future_skew (ngx_http_request_t * r, time_t request_time) static
Definition at line 211 of file auth_sigv4_verify_time.c.
References s3_reject_clock_skew(), and S3_SIGV4_MAX_FUTURE_SKEW_SEC.
Referenced by s3_sigv4_resolve_request_time().
s3_digit()
static int s3_digit (u_char c) static
Definition at line 44 of file auth_sigv4_verify_time.c.
References c.
Referenced by s3_parse_2digits(), and s3_parse_4digits().
s3_parse_2digits()
static int s3_parse_2digits (const char * s) static
Definition at line 59 of file auth_sigv4_verify_time.c.
References s, and s3_digit().
Referenced by s3_parse_amz_datetime().
s3_parse_4digits()
static int s3_parse_4digits (const char * s) static
Definition at line 81 of file auth_sigv4_verify_time.c.
References c, s, and s3_digit().
Referenced by s3_parse_amz_datetime().
s3_parse_amz_datetime()
static ngx_int_t s3_parse_amz_datetime (const char * s, time_t * out) static
Definition at line 106 of file auth_sigv4_verify_time.c.
References s, s3_parse_2digits(), and s3_parse_4digits().
Referenced by s3_sigv4_resolve_request_time().
s3_reject_bad_amz_date()
static ngx_int_t s3_reject_bad_amz_date (ngx_http_request_t * r, const char * message) static
Definition at line 150 of file auth_sigv4_verify_time.c.
References BRIX_S3_AUTH_BAD_DATE, s3_record_auth_result(), and s3_send_xml_error().
Referenced by s3_sigv4_resolve_request_time().
s3_reject_clock_skew()
static ngx_int_t s3_reject_clock_skew (ngx_http_request_t * r) static
Definition at line 166 of file auth_sigv4_verify_time.c.
References BRIX_S3_AUTH_BAD_DATE, s3_record_auth_result(), and s3_send_xml_error().
Referenced by s3_check_header_clock_skew(), and s3_check_presigned_future_skew().
s3_sigv4_resolve_request_time()
ngx_int_t s3_sigv4_resolve_request_time (ngx_http_request_t * r, const sigv4_components_t * comp, s3_amz_date_out_t * out)
Definition at line 244 of file auth_sigv4_verify_time.c.
References sigv4_components_t::amz_date, sigv4_components_t::amz_expires, BRIX_S3_AUTH_BAD_DATE, brix_str_cbuf(), s3_amz_date_out_t::buf, s3_amz_date_out_t::date, get_header(), s3_amz_date_out_t::len, sigv4_components_t::presigned, s3_check_header_clock_skew(), s3_check_presigned_future_skew(), s3_parse_amz_datetime(), s3_record_auth_result(), s3_reject_bad_amz_date(), and s3_send_xml_error().
Referenced by s3_verify_sigv4().