nginx-xrootd: src/auth/authz/authdb_parse.c File Reference
authdb_parse.c File Reference
#include "core/ngx_brix_module.h"
#include <stddef.h>
#include <string.h>
#include <ctype.h>
#include <stdlib.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include "fs/path/path_internal.h"
Data Structures
struct adb_line_t
Functions
ngx_int_t brix_finalize_authdb_rules (ngx_log_t *log, const ngx_str_t *root, ngx_array_t *rules)
static uint32_t brix_parse_privs (const char *p, size_t len)
static ngx_int_t adb_read_file (ngx_conf_t *cf, ngx_str_t *filename, u_char **out_buf, size_t *out_len)
static void adb_next_line (u_char **cursor, u_char *end, u_char **line_start_out, u_char **line_end_out)
static ngx_flag_t adb_scan_field (u_char **p, u_char *line_end, u_char **field_p)
static void adb_tokenize_line (u_char **cursor, u_char *end, adb_line_t *out)
static ngx_int_t adb_append (ngx_conf_t *cf, ngx_array_t *rules, const adb_line_t *line)
ngx_int_t brix_parse_authdb (ngx_conf_t *cf, ngx_str_t *filename, ngx_array_t *rules)
Function Documentation
adb_append()
static ngx_int_t adb_append (ngx_conf_t * cf, ngx_array_t * rules, const adb_line_t * line) static
Definition at line 234 of file authdb_parse.c.
References brix_parse_privs(), brix_authdb_rule_t::id, adb_line_t::id_end, adb_line_t::id_p, ngx_memcpy, brix_authdb_rule_t::path, adb_line_t::path_end, adb_line_t::path_p, brix_authdb_rule_t::privs, adb_line_t::privs_end, adb_line_t::privs_p, brix_authdb_rule_t::resolved, brix_authdb_rule_t::type, and adb_line_t::type_p.
Referenced by brix_parse_authdb().
adb_next_line()
static void adb_next_line (u_char ** cursor, u_char * end, u_char ** line_start_out, u_char ** line_end_out) static
Definition at line 141 of file authdb_parse.c.
Referenced by adb_tokenize_line().
adb_read_file()
static ngx_int_t adb_read_file (ngx_conf_t * cf, ngx_str_t * filename, u_char ** out_buf, size_t * out_len) static
Definition at line 69 of file authdb_parse.c.
Referenced by brix_parse_authdb().
adb_scan_field()
static ngx_flag_t adb_scan_field (u_char ** p, u_char * line_end, u_char ** field_p) static
Definition at line 173 of file authdb_parse.c.
Referenced by adb_tokenize_line().
adb_tokenize_line()
static void adb_tokenize_line (u_char ** cursor, u_char * end, adb_line_t * out) static
Definition at line 191 of file authdb_parse.c.
References adb_next_line(), adb_scan_field(), adb_line_t::id_end, adb_line_t::id_p, adb_line_t::path_end, adb_line_t::path_p, adb_line_t::privs_end, adb_line_t::privs_p, adb_line_t::type_p, and adb_line_t::valid.
Referenced by brix_parse_authdb().
brix_finalize_authdb_rules()
ngx_int_t brix_finalize_authdb_rules (ngx_log_t * log, const ngx_str_t * root, ngx_array_t * rules)
Definition at line 15 of file authdb_parse.c.
References brix_finalize_path_rules(), and log.
Referenced by brix_config_finalize_policy(), and webdav_finalize_authz_rules().
brix_parse_authdb()
ngx_int_t brix_parse_authdb (ngx_conf_t * cf, ngx_str_t * filename, ngx_array_t * rules)
Definition at line 266 of file authdb_parse.c.
References adb_append(), adb_read_file(), adb_tokenize_line(), ngx_stream_brix_module, and adb_line_t::valid.
Referenced by brix_conf_set_authdb(), and webdav_conf_authdb().
brix_parse_privs()
static uint32_t brix_parse_privs (const char * p, size_t len) static
Definition at line 26 of file authdb_parse.c.
References BRIX_AUTH_ADMIN, BRIX_AUTH_DELETE, BRIX_AUTH_LOOKUP, BRIX_AUTH_MKDIR, BRIX_AUTH_READ, and BRIX_AUTH_UPDATE.
Referenced by adb_append().