nginx-xrootd: src/auth/authz/auth_gate.c File Reference
auth_gate.c File Reference
#include "core/ngx_brix_module.h"
#include "auth_gate.h"
#include "auth_cache.h"
#include "auth_gate_l1.h"
#include "core/compat/crypto.h"
#include "auth/authz/acc/acc.h"
#include "observability/metrics/metrics_macros.h"
Data Structures
struct auth_gate_ctx_t
Functions
static brix_acc_op_t brix_acc_gate_select_op (brix_acc_op_t op_in, int auth_level)
static void brix_acc_gate_identity (brix_ctx_t *ctx, const char **name, const char **vorg, const char **role, const char **grp)
static const char * brix_acc_gate_host (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
static ngx_int_t brix_acc_gate_engine (const auth_gate_ctx_t *g, const char *path)
ngx_int_t brix_authz_check (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *reqpath, const char *resolved, const char *op_name, int auth_level, brix_acc_op_t aop)
static int brix_auth_gate_cache_key (u_char key[32], const auth_gate_ctx_t *g, brix_acc_op_t key_aop, const char *host)
static void brix_auth_gate_cache_put (ngx_stream_brix_srv_conf_t *conf, const u_char key[32], int have_key, int allowed, int auth_level)
static ngx_int_t brix_auth_gate_deny (const auth_gate_ctx_t *g, const u_char ac_key[32], int ac_have_key, const char *log_path, const char *msg)
static int brix_auth_gate_cache_probe (const auth_gate_ctx_t *g, u_char out_key[32], int *out_have_key, int *out_verdict)
static ngx_int_t brix_auth_gate_evaluate (const auth_gate_ctx_t *g, const u_char ac_key[32], int ac_have_key)
ngx_int_t brix_auth_gate_op (brix_ctx_t *ctx, ngx_connection_t *c, ngx_uint_t op_id, const char *op_name, const char *reqpath, const char *resolved, ngx_stream_brix_srv_conf_t *conf, int auth_level, int need_write, brix_acc_op_t aop)
ngx_int_t brix_auth_gate (brix_ctx_t *ctx, ngx_connection_t *c, ngx_uint_t op_id, const char *op_name, const char *reqpath, const char *resolved, ngx_stream_brix_srv_conf_t *conf, int auth_level, int need_write)
Function Documentation
brix_acc_gate_engine()
static ngx_int_t brix_acc_gate_engine (const auth_gate_ctx_t * g, const char * path) static
Definition at line 140 of file auth_gate.c.
References auth_gate_ctx_t::aop, auth_gate_ctx_t::auth_level, brix_acc_access(), brix_acc_audit(), brix_acc_entity_build(), brix_acc_gate_host(), brix_acc_gate_identity(), brix_acc_gate_select_op(), BRIX_ACC_PRIV_NONE, auth_gate_ctx_t::c, c, auth_gate_ctx_t::conf, auth_gate_ctx_t::ctx, host, name, op, and auth_gate_ctx_t::op_name.
Referenced by brix_auth_gate_evaluate(), and brix_authz_check().
brix_acc_gate_host()
static const char * brix_acc_gate_host (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf) static
Definition at line 103 of file auth_gate.c.
References brix_ctx_login_t::acc_host, brix_ctx_login_t::acc_host_done, brix_acc_resolve_peer(), c, host, brix_ctx_t::login, ngx_memcpy, ngx_pnalloc(), and brix_ctx_login_t::peer_ip.
Referenced by brix_acc_gate_engine().
brix_acc_gate_identity()
static void brix_acc_gate_identity (brix_ctx_t * ctx, const char ** name, const char ** vorg, const char ** role, const char ** grp) static
Definition at line 77 of file auth_gate.c.
References brix_identity_acc_group_cstr(), brix_identity_acc_role_cstr(), brix_identity_acc_vorg_cstr(), brix_identity_dn_cstr(), brix_ctx_login_t::dn, brix_ctx_t::identity, brix_ctx_t::login, name, and brix_ctx_login_t::vo_list.
Referenced by brix_acc_gate_engine().
brix_acc_gate_select_op()
static brix_acc_op_t brix_acc_gate_select_op (brix_acc_op_t op_in, int auth_level) static
Definition at line 56 of file auth_gate.c.
References BRIX_AOP_ANY, BRIX_AOP_CHMOD, BRIX_AOP_DELETE, BRIX_AOP_MKDIR, BRIX_AOP_READ, BRIX_AOP_STAT, BRIX_AOP_UPDATE, BRIX_AUTH_ADMIN, BRIX_AUTH_DELETE, BRIX_AUTH_MKDIR, BRIX_AUTH_READ, and BRIX_AUTH_UPDATE.
Referenced by brix_acc_gate_engine().
brix_auth_gate()
ngx_int_t brix_auth_gate (brix_ctx_t * ctx, ngx_connection_t * c, ngx_uint_t op_id, const char * op_name, const char * reqpath, const char * resolved, ngx_stream_brix_srv_conf_t * conf, int auth_level, int need_write)
Definition at line 482 of file auth_gate.c.
References BRIX_AOP_ANY, brix_auth_gate_op(), and c.
Referenced by brix_dirlist_open_dir(), brix_dispatch_op(), brix_handle_link(), brix_handle_mkdir(), brix_handle_readlink(), brix_handle_setattr(), brix_handle_symlink(), brix_handle_truncate(), brix_open_cached_read(), brix_open_read_resolve(), brix_qcksum_resolve(), brix_query_ckscan(), brix_query_opaquf(), brix_query_xattr(), fattr_path_target(), locate_check_data_server(), and stat_query_path().
brix_auth_gate_cache_key()
static int brix_auth_gate_cache_key (u_char key[32], const auth_gate_ctx_t * g, brix_acc_op_t key_aop, const char * host) static
Definition at line 230 of file auth_gate.c.
References auth_gate_ctx_t::auth_level, brix_sha256(), auth_gate_ctx_t::ctx, brix_ctx_login_t::dn, host, brix_ctx_t::identity, key, brix_ctx_t::login, auth_gate_ctx_t::need_write, ngx_memcpy, PATH_MAX, auth_gate_ctx_t::reqpath, auth_gate_ctx_t::resolved, scope, brix_identity_t::scope_raw, and brix_ctx_login_t::vo_list.
Referenced by brix_auth_gate_cache_probe().
brix_auth_gate_cache_probe()
static int brix_auth_gate_cache_probe (const auth_gate_ctx_t * g, u_char out_key[32], int * out_have_key, int * out_verdict) static
Definition at line 336 of file auth_gate.c.
References brix_auth_cache_val_t::allowed, auth_gate_ctx_t::aop, BRIX_AOP_ANY, brix_auth_gate_cache_key(), brix_auth_l1_create(), brix_auth_l1_lookup(), brix_auth_l1_store(), BRIX_AUTHDB_FORMAT_XRDACC, brix_kv_get(), BRIX_RESIL_METRIC_INC, auth_gate_ctx_t::conf, auth_gate_ctx_t::ctx, brix_ctx_t::login, and brix_ctx_login_t::peer_ip.
Referenced by brix_auth_gate_op().
brix_auth_gate_cache_put()
static void brix_auth_gate_cache_put (ngx_stream_brix_srv_conf_t * conf, const u_char key[32], int have_key, int allowed, int auth_level) static
Definition at line 277 of file auth_gate.c.
References brix_auth_cache_val_t::allowed, brix_auth_cache_val_t::auth_level, brix_auth_l1_store(), brix_kv_set(), key, and brix_auth_cache_val_t::pad.
Referenced by brix_auth_gate_deny(), and brix_auth_gate_op().
brix_auth_gate_deny()
static ngx_int_t brix_auth_gate_deny (const auth_gate_ctx_t * g, const u_char ac_key[32], int ac_have_key, const char * log_path, const char * msg) static
Definition at line 309 of file auth_gate.c.
References auth_gate_ctx_t::auth_level, brix_auth_gate_cache_put(), brix_log_access(), BRIX_OP_ERR, brix_send_error(), auth_gate_ctx_t::c, auth_gate_ctx_t::conf, auth_gate_ctx_t::ctx, kXR_NotAuthorized, auth_gate_ctx_t::op_id, auth_gate_ctx_t::op_name, and brix_ctx_t::write_rc.
Referenced by brix_auth_gate_evaluate().
brix_auth_gate_evaluate()
static ngx_int_t brix_auth_gate_evaluate (const auth_gate_ctx_t * g, const u_char ac_key[32], int ac_have_key) static
Definition at line 396 of file auth_gate.c.
References auth_gate_ctx_t::auth_level, brix_acc_gate_engine(), brix_auth_gate_deny(), BRIX_AUTHDB_FORMAT_XRDACC, brix_check_authdb(), brix_check_token_scope(), brix_check_vo_acl_identity(), auth_gate_ctx_t::c, auth_gate_ctx_t::conf, auth_gate_ctx_t::ctx, brix_ctx_t::identity, auth_gate_ctx_t::need_write, auth_gate_ctx_t::reqpath, and auth_gate_ctx_t::resolved.
Referenced by brix_auth_gate_op().
brix_auth_gate_op()
ngx_int_t brix_auth_gate_op (brix_ctx_t * ctx, ngx_connection_t * c, ngx_uint_t op_id, const char * op_name, const char * reqpath, const char * resolved, ngx_stream_brix_srv_conf_t * conf, int auth_level, int need_write, brix_acc_op_t aop)
Definition at line 429 of file auth_gate.c.
References auth_gate_ctx_t::aop, auth_gate_ctx_t::auth_level, brix_auth_gate_cache_probe(), brix_auth_gate_cache_put(), brix_auth_gate_evaluate(), brix_log_access(), BRIX_OP_ERR, brix_send_error(), auth_gate_ctx_t::c, c, auth_gate_ctx_t::conf, auth_gate_ctx_t::ctx, kXR_NotAuthorized, auth_gate_ctx_t::need_write, auth_gate_ctx_t::op_id, auth_gate_ctx_t::op_name, auth_gate_ctx_t::reqpath, auth_gate_ctx_t::resolved, and brix_ctx_t::write_rc.
Referenced by brix_auth_gate(), brix_handle_mv(), and brix_open_write_resolve().
brix_authz_check()
ngx_int_t brix_authz_check (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * reqpath, const char * resolved, const char * op_name, int auth_level, brix_acc_op_t aop)
Definition at line 192 of file auth_gate.c.
References auth_gate_ctx_t::aop, auth_gate_ctx_t::auth_level, brix_acc_gate_engine(), BRIX_AUTHDB_FORMAT_XRDACC, brix_check_authdb(), auth_gate_ctx_t::c, c, auth_gate_ctx_t::conf, auth_gate_ctx_t::ctx, auth_gate_ctx_t::op_name, auth_gate_ctx_t::reqpath, and auth_gate_ctx_t::resolved.
Referenced by brix_statx_path_authorized(), prepare_path_authz(), qprep_path_authorized(), and tpc_handle_dest().