nginx-xrootd: src/protocols/webdav/auth_token.c File Reference
auth_token.c File Reference
#include "webdav.h"
#include "core/http/http_headers.h"
#include "auth/token/macaroon.h"
#include "auth/token/token_cache.h"
#include "auth/token/worker_cache.h"
#include "auth/token/issuer_registry.h"
#include <string.h>
Data Structures
struct wt_validate_ctx_t
Macros
#define WEBDAV_QUERY_TOKEN_MAX 8192
Functions
static brix_token_op_e webdav_token_op_class (ngx_http_request_t *r)
ngx_int_t webdav_check_token_scope (ngx_http_request_t *r, const char *method_name)
static ngx_int_t webdav_bearer_from_query (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_str_t *out)
static ngx_int_t wt_ensure_ctx (ngx_http_request_t *r, ngx_http_brix_webdav_req_ctx_t **out)
static ngx_int_t wt_parse_header (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_str_t *bearer)
static int wt_validate_registry (const wt_validate_ctx_t *v)
static int wt_validate_jwks (const wt_validate_ctx_t *v, const u_char *secret, ssize_t slen)
static int wt_grace_retry (const wt_validate_ctx_t *v, int via_registry, int prev_rc)
static int wt_check_issuer_keys (const wt_validate_ctx_t *v, int *cache_hit, int *via_registry)
static ngx_int_t wt_check_claims (ngx_http_request_t *r, ngx_http_brix_webdav_req_ctx_t *ctx, const char *token, size_t token_len, brix_token_claims_t *claims)
ngx_int_t webdav_verify_bearer_token (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
Macro Definition Documentation
WEBDAV_QUERY_TOKEN_MAX
#define WEBDAV_QUERY_TOKEN_MAX 8192
Definition at line 111 of file auth_token.c.
Function Documentation
webdav_bearer_from_query()
static ngx_int_t webdav_bearer_from_query (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_str_t * out) static
Definition at line 142 of file auth_token.c.
References brix_http_arg(), brix_urldecode_inplace(), ngx_http_brix_webdav_loc_conf_t::http_query_token, and WEBDAV_QUERY_TOKEN_MAX.
Referenced by wt_parse_header().
webdav_check_token_scope()
ngx_int_t webdav_check_token_scope (ngx_http_request_t * r, const char * method_name)
Definition at line 69 of file auth_token.c.
References brix_identity_check_token_scope(), brix_token_check_read(), brix_token_check_write(), BRIX_TOKEN_OP_WRITE, ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, ngx_memcpy, ngx_http_brix_webdav_req_ctx_t::token_auth, ngx_http_brix_webdav_req_ctx_t::token_scope_count, ngx_http_brix_webdav_req_ctx_t::token_scopes, WEBDAV_MAX_PATH, and webdav_token_op_class().
Referenced by access_check_scope().
webdav_token_op_class()
static brix_token_op_e webdav_token_op_class (ngx_http_request_t * r) static
Definition at line 17 of file auth_token.c.
References BRIX_TOKEN_OP_READ, and BRIX_TOKEN_OP_WRITE.
Referenced by webdav_check_token_scope(), and wt_validate_registry().
webdav_verify_bearer_token()
ngx_int_t webdav_verify_bearer_token (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 521 of file auth_token.c.
References brix_macaroon_secret_parse(), brix_token_cache_store(), brix_token_l1_store(), wt_validate_ctx_t::claims, wt_validate_ctx_t::conf, ngx_http_brix_webdav_loc_conf_t::jwks_key_count, wt_validate_ctx_t::r, wt_validate_ctx_t::secret, wt_validate_ctx_t::slen, wt_validate_ctx_t::token, ngx_http_brix_webdav_req_ctx_t::token_auth, ngx_http_brix_webdav_loc_conf_t::token_cache_kv, ngx_http_brix_webdav_loc_conf_t::token_l1, wt_validate_ctx_t::token_len, ngx_http_brix_webdav_loc_conf_t::token_macaroon_secret, ngx_http_brix_webdav_loc_conf_t::token_registry, wt_check_claims(), wt_check_issuer_keys(), wt_ensure_ctx(), and wt_parse_header().
Referenced by access_try_token().
wt_check_claims()
static ngx_int_t wt_check_claims (ngx_http_request_t * r, ngx_http_brix_webdav_req_ctx_t * ctx, const char * token, size_t token_len, brix_token_claims_t * claims) static
Definition at line 473 of file auth_token.c.
References ngx_http_brix_webdav_req_ctx_t::auth_source, ngx_http_brix_webdav_req_ctx_t::bearer_token, brix_identity_set_token_claims(), BRIX_MAX_TOKEN_SCOPES, ngx_http_brix_webdav_req_ctx_t::dn, ngx_http_brix_webdav_req_ctx_t::identity, ngx_memcpy, ngx_pnalloc(), brix_token_claims_t::scope_count, brix_token_claims_t::scopes, brix_token_claims_t::sub, ngx_http_brix_webdav_req_ctx_t::token_auth, ngx_http_brix_webdav_req_ctx_t::token_scope_count, ngx_http_brix_webdav_req_ctx_t::token_scopes, and ngx_http_brix_webdav_req_ctx_t::verified.
Referenced by webdav_verify_bearer_token().
wt_check_issuer_keys()
static int wt_check_issuer_keys (const wt_validate_ctx_t * v, int * cache_hit, int * via_registry) static
Definition at line 405 of file auth_token.c.
References brix_token_cache_lookup(), brix_token_l1_create(), brix_token_l1_lookup(), BRIX_TOKEN_L1_SLOTS, brix_token_l1_store(), wt_validate_ctx_t::claims, wt_validate_ctx_t::conf, wt_validate_ctx_t::secret, wt_validate_ctx_t::slen, wt_validate_ctx_t::token, ngx_http_brix_webdav_loc_conf_t::token_cache_kv, ngx_http_brix_webdav_loc_conf_t::token_l1, wt_validate_ctx_t::token_len, ngx_http_brix_webdav_loc_conf_t::token_registry, wt_grace_retry(), wt_validate_jwks(), and wt_validate_registry().
Referenced by webdav_verify_bearer_token().
wt_ensure_ctx()
static ngx_int_t wt_ensure_ctx (ngx_http_request_t * r, ngx_http_brix_webdav_req_ctx_t ** out) static
Definition at line 184 of file auth_token.c.
References brix_identity_alloc(), ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, and ngx_pcalloc().
Referenced by webdav_verify_bearer_token().
wt_grace_retry()
static int wt_grace_retry (const wt_validate_ctx_t * v, int via_registry, int prev_rc) static
Definition at line 357 of file auth_token.c.
References brix_macaroon_secret_parse(), wt_validate_ctx_t::conf, wt_validate_ctx_t::r, ngx_http_brix_webdav_loc_conf_t::token_macaroon_secret_old, and wt_validate_jwks().
Referenced by wt_check_issuer_keys().
wt_parse_header()
static ngx_int_t wt_parse_header (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_str_t * bearer) static
Definition at line 228 of file auth_token.c.
References brix_http_extract_bearer(), brix_http_redact_query_token(), and webdav_bearer_from_query().
Referenced by webdav_verify_bearer_token().
wt_validate_jwks()
static int wt_validate_jwks (const wt_validate_ctx_t * v, const u_char * secret, ssize_t slen) static
Definition at line 321 of file auth_token.c.
References brix_token_validate(), brix_token_validate_args_t::claims, wt_validate_ctx_t::claims, brix_token_validate_args_t::clock_skew, wt_validate_ctx_t::conf, brix_token_validate_args_t::expected_audience, brix_token_validate_args_t::expected_issuer, ngx_http_brix_webdav_loc_conf_t::jwks_key_count, ngx_http_brix_webdav_loc_conf_t::jwks_keys, brix_token_validate_args_t::key_count, brix_token_validate_args_t::keys, brix_token_validate_args_t::log, brix_token_validate_args_t::macaroon_secret, wt_validate_ctx_t::r, brix_token_validate_args_t::secret_len, brix_token_validate_args_t::token, wt_validate_ctx_t::token, ngx_http_brix_webdav_loc_conf_t::token_audience, ngx_http_brix_webdav_loc_conf_t::token_clock_skew, ngx_http_brix_webdav_loc_conf_t::token_issuer, brix_token_validate_args_t::token_len, and wt_validate_ctx_t::token_len.
Referenced by wt_check_issuer_keys(), and wt_grace_retry().
wt_validate_registry()
static int wt_validate_registry (const wt_validate_ctx_t * v) static
Definition at line 280 of file auth_token.c.
References brix_token_validate_registry(), brix_token_registry_args_t::claims, wt_validate_ctx_t::claims, brix_token_registry_args_t::clock_skew, wt_validate_ctx_t::conf, brix_token_registry_args_t::log, brix_token_registry_args_t::macaroon_secret, ngx_memcpy, wt_validate_ctx_t::r, brix_token_registry_args_t::reg, wt_validate_ctx_t::secret, brix_token_registry_args_t::secret_len, wt_validate_ctx_t::slen, brix_token_registry_args_t::token, wt_validate_ctx_t::token, ngx_http_brix_webdav_loc_conf_t::token_clock_skew, brix_token_registry_args_t::token_len, wt_validate_ctx_t::token_len, ngx_http_brix_webdav_loc_conf_t::token_registry, and webdav_token_op_class().
Referenced by wt_check_issuer_keys().