nginx-xrootd: src/protocols/webdav/auth_store.c File Reference
auth_store.c File Reference
#include "webdav.h"
#include "auth/crypto/pki_build.h"
#include "core/compat/cstr.h"
#include <limits.h>
Functions
X509_STORE * webdav_build_ca_store (ngx_log_t *log, ngx_http_brix_webdav_loc_conf_t *conf, int *crl_count_out)
Function Documentation
webdav_build_ca_store()
X509_STORE * webdav_build_ca_store (ngx_log_t * log, ngx_http_brix_webdav_loc_conf_t * conf, int * crl_count_out)
Definition at line 19 of file auth_store.c.
References brix_build_ca_store(), brix_str_cbuf(), ngx_http_brix_webdav_loc_conf_t::cadir, ngx_http_brix_webdav_loc_conf_t::cafile, ngx_http_brix_webdav_loc_conf_t::crl, ngx_http_brix_webdav_loc_conf_t::crl_mode, log, PATH_MAX, and ngx_http_brix_webdav_loc_conf_t::signing_policy_mode.
Referenced by ngx_http_brix_webdav_merge_loc_conf().