nginx-xrootd: src/auth/gsi/auth_cert.c File Reference
auth_cert.c File Reference
#include "gsi_internal.h"
#include "delegation.h"
#include "protocols/root/session/registry.h"
#include "auth/crypto/ocsp.h"
#include "auth/crypto/gsi_verify.h"
#include <openssl/err.h>
#include <openssl/pem.h>
Functions
static ngx_int_t gsi_promote_fullproxy (brix_ctx_t *ctx, ngx_connection_t *c)
static ngx_int_t gsi_cert_deny (brix_ctx_t *ctx, ngx_connection_t *c, STACK_OF(X509) *chain, const char *log_msg, const char *err_msg)
static ngx_int_t gsi_cert_verify (ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, STACK_OF(X509) *chain, X509 *leaf, brix_gsi_verify_result_t *verify_res)
static void gsi_cert_capture_dn (brix_ctx_t *ctx, ngx_connection_t *c, const brix_gsi_verify_result_t *verify_res)
static void gsi_cert_extract_voms (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, X509 *leaf, STACK_OF(X509) *chain)
ngx_int_t gsi_auth_step_cert (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
gsi_auth_step_cert()
ngx_int_t gsi_auth_step_cert (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 249 of file auth_cert.c.
References brix_gsi_begin_delegation(), brix_gsi_complete_auth(), brix_ocsp_check_cert(), BRIX_OP_AUTH, BRIX_RETURN_ERR, c, brix_ctx_gsi_t::deleg_await, brix_ctx_gsi_t::dh_key, brix_ctx_t::gsi, gsi_cert_capture_dn(), gsi_cert_deny(), gsi_cert_extract_voms(), gsi_cert_verify(), gsi_promote_fullproxy(), kXR_NotAuthorized, brix_ctx_gsi_t::sess_keylen, and STACK_OF().
Referenced by brix_handle_auth_inner().
gsi_cert_capture_dn()
static void gsi_cert_capture_dn (brix_ctx_t * ctx, ngx_connection_t * c, const brix_gsi_verify_result_t * verify_res) static
Definition at line 180 of file auth_cert.c.
References c, brix_ctx_login_t::dn, brix_gsi_verify_result_t::dn_buf, and brix_ctx_t::login.
Referenced by gsi_auth_step_cert().
gsi_cert_deny()
static ngx_int_t gsi_cert_deny (brix_ctx_t * ctx, ngx_connection_t * c, STACK_OF(X509) * chain, const char * log_msg, const char * err_msg) static
Definition at line 123 of file auth_cert.c.
References brix_log_access(), BRIX_OP_AUTH, BRIX_OP_ERR, brix_send_error(), c, and kXR_NotAuthorized.
Referenced by gsi_auth_step_cert().
gsi_cert_extract_voms()
static void gsi_cert_extract_voms (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, X509 * leaf, STACK_OF(X509) * chain) static
Definition at line 205 of file auth_cert.c.
References brix_extract_voms_info(), brix_sanitize_log_string(), brix_voms_available(), c, brix_ctx_t::login, brix_ctx_login_t::primary_vo, and brix_ctx_login_t::vo_list.
Referenced by gsi_auth_step_cert().
gsi_cert_verify()
static ngx_int_t gsi_cert_verify (ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, STACK_OF(X509) * chain, X509 * leaf, brix_gsi_verify_result_t * verify_res) static
Definition at line 146 of file auth_cert.c.
References brix_gsi_verify_chain(), c, and STACK_OF().
Referenced by gsi_auth_step_cert().
gsi_promote_fullproxy()
static ngx_int_t gsi_promote_fullproxy (brix_ctx_t * ctx, ngx_connection_t * c) static
Definition at line 30 of file auth_cert.c.
References c, brix_ctx_gsi_t::client_fullproxy_len, brix_ctx_gsi_t::client_fullproxy_pem, brix_ctx_t::deleg_proxy_pem, brix_ctx_login_t::dn, brix_ctx_t::gsi, key, brix_ctx_t::login, ngx_memcpy, and ngx_pnalloc().
Referenced by gsi_auth_step_cert().