nginx-xrootd: src/protocols/s3/auth_sigv4_canonical.c File Reference
auth_sigv4_canonical.c File Reference
#include "s3.h"
#include "core/compat/uri.h"
#include <string.h>
#include <stdlib.h>
Data Structures
struct qparam_t
Functions
static int qparam_cmp (const void *a, const void *b)
static size_t uriencode_param (const u_char *src, size_t slen, u_char *out, size_t outsz)
static int sigv4_store_param (qparam_t *p, const u_char *segment_start, const u_char *segment_end, const u_char *equals, ngx_flag_t skip_signature)
static const u_char * sigv4_scan_segment (const u_char *segment_start, const u_char *end, const u_char **equals_out)
static int sigv4_parse_qs (const u_char *qs, size_t qslen, ngx_flag_t skip_signature, qparam_t *params, int max_params)
static size_t sigv4_append_encoded (u_char *out, size_t oi, size_t outsz, const u_char *src, size_t slen)
static size_t sigv4_emit_canonical_qs (const qparam_t *params, int param_count, u_char *out, size_t outsz)
size_t build_canonical_qs (const u_char *qs, size_t qslen, ngx_flag_t skip_signature, u_char *out, size_t outsz)
Function Documentation
build_canonical_qs()
size_t build_canonical_qs (const u_char * qs, size_t qslen, ngx_flag_t skip_signature, u_char * out, size_t outsz)
Definition at line 294 of file auth_sigv4_canonical.c.
References qparam_cmp(), sigv4_emit_canonical_qs(), and sigv4_parse_qs().
Referenced by s3_sigv4_compute_signature().
qparam_cmp()
static int qparam_cmp (const void * a, const void * b) static
Definition at line 47 of file auth_sigv4_canonical.c.
References qparam_t::name, qparam_t::name_len, qparam_t::value, and qparam_t::value_len.
Referenced by build_canonical_qs().
sigv4_append_encoded()
static size_t sigv4_append_encoded (u_char * out, size_t oi, size_t outsz, const u_char * src, size_t slen) static
Definition at line 225 of file auth_sigv4_canonical.c.
References ngx_memcpy, and uriencode_param().
Referenced by sigv4_emit_canonical_qs().
sigv4_emit_canonical_qs()
static size_t sigv4_emit_canonical_qs (const qparam_t * params, int param_count, u_char * out, size_t outsz) static
Definition at line 255 of file auth_sigv4_canonical.c.
References name, and sigv4_append_encoded().
Referenced by build_canonical_qs().
sigv4_parse_qs()
static int sigv4_parse_qs (const u_char * qs, size_t qslen, ngx_flag_t skip_signature, qparam_t * params, int max_params) static
Definition at line 180 of file auth_sigv4_canonical.c.
References sigv4_scan_segment(), and sigv4_store_param().
Referenced by build_canonical_qs().
sigv4_scan_segment()
static const u_char * sigv4_scan_segment (const u_char * segment_start, const u_char * end, const u_char ** equals_out) static
Definition at line 144 of file auth_sigv4_canonical.c.
Referenced by sigv4_parse_qs().
sigv4_store_param()
static int sigv4_store_param (qparam_t * p, const u_char * segment_start, const u_char * segment_end, const u_char * equals, ngx_flag_t skip_signature) static
Definition at line 83 of file auth_sigv4_canonical.c.
References brix_http_urldecode(), BRIX_URLDECODE_OK, BRIX_URLDECODE_PLUS_TO_SPACE, BRIX_URLDECODE_REJECT_NUL, qparam_t::name, qparam_t::name_len, qparam_t::value, and qparam_t::value_len.
Referenced by sigv4_parse_qs().
uriencode_param()
static size_t uriencode_param (const u_char * src, size_t slen, u_char * out, size_t outsz) static
Definition at line 68 of file auth_sigv4_canonical.c.
References brix_http_urlencode().
Referenced by sigv4_append_encoded().