nginx-xrootd: src/protocols/s3/auth_sigv4_verify_internal.h File Reference
auth_sigv4_verify_internal.h File Reference
#include "s3.h"
#include "s3_auth_internal.h"
Data Structures
struct s3_amz_date_out_t
struct s3_sigv4_sig_out_t
Functions
void s3_record_auth_result (ngx_uint_t result)
ngx_int_t s3_sigv4_resolve_request_time (ngx_http_request_t *r, const sigv4_components_t *comp, s3_amz_date_out_t *out)
ngx_int_t s3_sigv4_compute_signature (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const sigv4_components_t *comp, const s3_amz_date_out_t *amz, s3_sigv4_sig_out_t *out)
ngx_int_t s3_sigv4_compare (ngx_http_request_t *r, const sigv4_components_t *comp, const char computed_hex[65], int key_ok)
size_t build_canonical_qs (const u_char *qs, size_t qslen, ngx_flag_t skip_signature, u_char *out, size_t outsz)
ngx_str_t get_header (ngx_http_request_t *r, const char *name)
Function Documentation
build_canonical_qs()
size_t build_canonical_qs (const u_char * qs, size_t qslen, ngx_flag_t skip_signature, u_char * out, size_t outsz)
Definition at line 294 of file auth_sigv4_canonical.c.
References qparam_cmp(), sigv4_emit_canonical_qs(), and sigv4_parse_qs().
Referenced by s3_sigv4_compute_signature().
get_header()
ngx_str_t get_header (ngx_http_request_t * r, const char * name)
Definition at line 21 of file auth_sigv4_parse.c.
s3_record_auth_result()
void s3_record_auth_result (ngx_uint_t result)
Definition at line 44 of file auth_sigv4_verify.c.
References BRIX_AUTHN_NONE, BRIX_AUTHN_S3KEY, brix_metric_auth(), BRIX_PROTO_S3, BRIX_S3_AUTH_ANONYMOUS, BRIX_S3_AUTH_MISSING, BRIX_S3_AUTH_SIGV4_OK, and BRIX_S3_METRIC_INC.
Referenced by s3_reject_bad_amz_date(), s3_reject_clock_skew(), s3_sigv4_bearer_intercept(), s3_sigv4_check_session_token(), s3_sigv4_compare(), s3_sigv4_compute_signature(), s3_sigv4_finish(), s3_sigv4_parse_authz_header(), s3_sigv4_resolve_request_time(), and s3_verify_sigv4().
s3_sigv4_compare()
ngx_int_t s3_sigv4_compare (ngx_http_request_t * r, const sigv4_components_t * comp, const char computed_hex[65], int key_ok)
Definition at line 272 of file auth_sigv4_verify_crypto.c.
References sigv4_components_t::akid, BRIX_S3_AUTH_BAD_KEY, BRIX_S3_AUTH_MALFORMED, BRIX_S3_AUTH_SIG_MISMATCH, s3_record_auth_result(), s3_send_xml_error(), and sigv4_components_t::signature.
Referenced by s3_verify_sigv4().
s3_sigv4_compute_signature()
ngx_int_t s3_sigv4_compute_signature (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const sigv4_components_t * comp, const s3_amz_date_out_t * amz, s3_sigv4_sig_out_t * out)
Definition at line 183 of file auth_sigv4_verify_crypto.c.
References brix_hex_encode(), brix_hmac_sha256(), brix_http_urlencode(), BRIX_S3_AUTH_INTERNAL_ERROR, brix_sha256(), build_canonical_headers(), build_canonical_qs(), s3_sigv4_sig_out_t::computed_hex, s3_amz_date_out_t::date, sigv4_components_t::date, s3_sigv4_sig_out_t::k4, s3_amz_date_out_t::len, sigv4_components_t::presigned, sigv4_components_t::region, S3_MAX_KEY, s3_record_auth_result(), s3_sigv4_derive_signing_key_cached(), ngx_http_s3_loc_conf_t::secret_key, and sigv4_components_t::signed_hdrs.
Referenced by s3_verify_sigv4().
s3_sigv4_resolve_request_time()
ngx_int_t s3_sigv4_resolve_request_time (ngx_http_request_t * r, const sigv4_components_t * comp, s3_amz_date_out_t * out)
Definition at line 244 of file auth_sigv4_verify_time.c.
References sigv4_components_t::amz_date, sigv4_components_t::amz_expires, BRIX_S3_AUTH_BAD_DATE, brix_str_cbuf(), s3_amz_date_out_t::buf, s3_amz_date_out_t::date, get_header(), s3_amz_date_out_t::len, sigv4_components_t::presigned, s3_check_header_clock_skew(), s3_check_presigned_future_skew(), s3_parse_amz_datetime(), s3_record_auth_result(), s3_reject_bad_amz_date(), and s3_send_xml_error().
Referenced by s3_verify_sigv4().