nginx-xrootd: src/auth/sss/auth_request.c File Reference
auth_request.c File Reference
#include "sss_internal.h"
#include "fs/path/path.h"
#include "protocols/root/response/response.h"
#include "protocols/root/session/registry.h"
#include <openssl/crypto.h>
#include <string.h>
#include "core/compat/alloc_guard.h"
Data Structures
struct sss_cred_t
Functions
static int sss_header_framing_ok (const u_char *payload, size_t dlen, size_t *hdr_len)
static ngx_int_t sss_deny (brix_ctx_t *ctx, ngx_connection_t *c, sss_cred_t *out)
static ngx_int_t sss_parse_header (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, sss_cred_t *out)
static ngx_int_t sss_verify_keytab (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, sss_cred_t *out)
static ngx_int_t sss_recv_cred (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, sss_cred_t *out)
static void sss_map_identity (const brix_sss_key_t *key, const brix_sss_identity_t *id, const char **user, const char **group)
static void sss_track_metrics (brix_ctx_t *ctx)
static ngx_int_t sss_reply (brix_ctx_t *ctx, ngx_connection_t *c, const char *user, const char *group)
ngx_int_t brix_handle_sss_auth (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_handle_sss_auth()
ngx_int_t brix_handle_sss_auth (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 356 of file auth_request.c.
References c, sss_cred_t::clear, sss_cred_t::clear_span, sss_cred_t::id, sss_cred_t::key, sss_cred_t::replied_rc, sss_map_identity(), sss_recv_cred(), and sss_reply().
sss_deny()
static ngx_int_t sss_deny (brix_ctx_t * ctx, ngx_connection_t * c, sss_cred_t * out) static
Definition at line 88 of file auth_request.c.
References brix_sss_auth_failed(), c, and sss_cred_t::replied_rc.
Referenced by sss_parse_header(), and sss_verify_keytab().
sss_header_framing_ok()
static int sss_header_framing_ok (const u_char * payload, size_t dlen, size_t * hdr_len) static
Definition at line 42 of file auth_request.c.
References BRIX_SSS_DATA_HDR_LEN, BRIX_SSS_ENC_BF32, BRIX_SSS_HDR_LEN, and BRIX_SSS_NAME_MAX.
Referenced by sss_parse_header().
sss_map_identity()
static void sss_map_identity (const brix_sss_key_t * key, const brix_sss_identity_t * id, const char ** user, const char ** group) static
Definition at line 250 of file auth_request.c.
References BRIX_SSS_OPT_ALLUSR, BRIX_SSS_OPT_ANYGRP, BRIX_SSS_OPT_ANYUSR, BRIX_SSS_OPT_USRGRP, and key.
Referenced by brix_handle_sss_auth().
sss_parse_header()
static ngx_int_t sss_parse_header (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, sss_cred_t * out) static
Definition at line 107 of file auth_request.c.
References brix_sss_find_key(), brix_sss_read_be64(), c, sss_cred_t::cipher, sss_cred_t::cipher_len, brix_ctx_recv_t::cur_dlen, sss_cred_t::hdr_len, sss_cred_t::key, brix_ctx_recv_t::payload, brix_ctx_t::recv, sss_deny(), and sss_header_framing_ok().
Referenced by sss_recv_cred().
sss_recv_cred()
static ngx_int_t sss_recv_cred (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, sss_cred_t * out) static
Definition at line 226 of file auth_request.c.
References c, sss_parse_header(), and sss_verify_keytab().
Referenced by brix_handle_sss_auth().
sss_reply()
static ngx_int_t sss_reply (brix_ctx_t * ctx, ngx_connection_t * c, const char * user, const char * group) static
Definition at line 312 of file auth_request.c.
References brix_ctx_token_t::auth, brix_ctx_login_t::auth_done, BRIX_AUTHN_SSS, brix_identity_set_dn(), brix_identity_set_vos_csv(), BRIX_OP_AUTH, BRIX_RETURN_OK, brix_sanitize_log_string(), brix_send_error(), brix_session_register(), c, brix_ctx_login_t::dn, brix_ctx_t::identity, kXR_NoMemory, brix_ctx_t::login, brix_ctx_login_t::primary_vo, brix_ctx_login_t::sessid, sss_track_metrics(), brix_ctx_t::token, and brix_ctx_login_t::vo_list.
Referenced by brix_handle_sss_auth().
sss_track_metrics()
static void sss_track_metrics (brix_ctx_t * ctx) static
Definition at line 278 of file auth_request.c.
References BRIX_ATOMIC_INC, brix_metrics_shared(), brix_track_unique_user(), brix_track_vo_activity(), BRIX_VO_MAX_TRACKED, BRIX_VO_NAME_LEN, brix_ctx_login_t::dn, brix_ctx_t::login, ngx_brix_vo_slot_t::name, brix_ctx_login_t::primary_vo, ngx_brix_vo_slot_t::requests_total, ngx_brix_vo_global_t::slots, and ngx_brix_metrics_t::vo_global.
Referenced by sss_reply().
sss_verify_keytab()
static ngx_int_t sss_verify_keytab (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, sss_cred_t * out) static
Definition at line 149 of file auth_request.c.
References BRIX_PALLOC_OR_RETURN, BRIX_SSS_BASE_TIME, brix_sss_bf32_crypt(), brix_sss_crc32(), BRIX_SSS_DATA_HDR_LEN, BRIX_SSS_OPT_SNDLID, brix_sss_parse_identity(), brix_sss_read_be32(), brix_sss_send_authmore(), c, sss_cred_t::cipher, sss_cred_t::cipher_len, sss_cred_t::clear, sss_cred_t::clear_span, sss_cred_t::hdr_len, sss_cred_t::id, sss_cred_t::key, brix_sss_key_t::key, brix_sss_key_t::key_len, brix_ctx_recv_t::payload, brix_ctx_t::recv, sss_cred_t::replied_rc, and sss_deny().
Referenced by sss_recv_cred().