nginx-xrootd: src/auth/gsi/config.c File Reference
config.c File Reference
#include "core/config/config.h"
#include "auth/crypto/pki_build.h"
#include "core/compat/lifecycle_timing.h"
Functions
ngx_int_t brix_rebuild_gsi_store (ngx_stream_brix_srv_conf_t *xcf, ngx_log_t *log, void *cache_scope)
static void brix_gsi_compute_ca_hashes (ngx_stream_brix_srv_conf_t *xcf)
static ngx_int_t brix_gsi_require_trust_inputs (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
static ngx_int_t brix_gsi_load_certificate (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
static ngx_int_t brix_gsi_cache_cert_pem (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
static ngx_int_t brix_gsi_load_private_key (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
static ngx_int_t brix_gsi_build_trust_store (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
ngx_int_t brix_configure_gsi (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
Function Documentation
brix_configure_gsi()
ngx_int_t brix_configure_gsi (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf)
Definition at line 359 of file config.c.
References BRIX_AUTH_BOTH, BRIX_AUTH_GSI, brix_gsi_build_trust_store(), brix_gsi_cache_cert_pem(), brix_gsi_compute_ca_hashes(), brix_gsi_load_certificate(), brix_gsi_load_private_key(), and brix_gsi_require_trust_inputs().
Referenced by postconf_prepare_servers().
brix_gsi_build_trust_store()
static ngx_int_t brix_gsi_build_trust_store (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf) static
Definition at line 320 of file config.c.
References brix_check_pki_consistency_stream(), brix_phase_now_ns(), and brix_rebuild_gsi_store().
Referenced by brix_configure_gsi().
brix_gsi_cache_cert_pem()
static ngx_int_t brix_gsi_cache_cert_pem (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf) static
Definition at line 230 of file config.c.
References ngx_memcpy, and ngx_pnalloc().
Referenced by brix_configure_gsi().
brix_gsi_compute_ca_hashes()
static void brix_gsi_compute_ca_hashes (ngx_stream_brix_srv_conf_t * xcf) static
Definition at line 81 of file config.c.
References STACK_OF().
Referenced by brix_configure_gsi().
brix_gsi_load_certificate()
static ngx_int_t brix_gsi_load_certificate (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf) static
Definition at line 191 of file config.c.
Referenced by brix_configure_gsi().
brix_gsi_load_private_key()
static ngx_int_t brix_gsi_load_private_key (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf) static
Definition at line 278 of file config.c.
Referenced by brix_configure_gsi().
brix_gsi_require_trust_inputs()
static ngx_int_t brix_gsi_require_trust_inputs (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf) static
Definition at line 148 of file config.c.
References BRIX_PATH_FILE_OR_DIRECTORY, BRIX_PATH_REGULAR_FILE, and brix_validate_path().
Referenced by brix_configure_gsi().
brix_rebuild_gsi_store()
ngx_int_t brix_rebuild_gsi_store (ngx_stream_brix_srv_conf_t * xcf, ngx_log_t * log, void * cache_scope)
Definition at line 16 of file config.c.
References brix_build_ca_store_cached(), log, and stat().
Referenced by brix_crl_reload_handler(), and brix_gsi_build_trust_store().