nginx-xrootd: src/auth/authz/acc/authfile_internal.h File Reference
authfile_internal.h File Reference
#include "acc.h"
Data Structures
struct acc_tok_t
struct acc_parse_ctx_t
Enumerations
enum { ACC_TOK_EOF = -1 , ACC_TOK_EOR = 0 , ACC_TOK_WORD = 1 }
Functions
int acc_tok_next (acc_tok_t *t, char **word)
ngx_int_t acc_record_iddef (acc_parse_ctx_t *pc, char **w, ngx_uint_t n)
ngx_int_t acc_record_rule (acc_parse_ctx_t *pc, char **w, ngx_uint_t n, int exclusive)
ngx_int_t acc_record_named (acc_parse_ctx_t *pc, char rtype, char **w, ngx_uint_t n)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ACC_TOK_EOF
ACC_TOK_EOR
ACC_TOK_WORD
Definition at line 39 of file authfile_internal.h.
Function Documentation
acc_record_iddef()
ngx_int_t acc_record_iddef (acc_parse_ctx_t * pc, char ** w, ngx_uint_t n)
Definition at line 269 of file authfile_record.c.
References acc_iddef_bind_selector(), BRIX_PCALLOC_OR_RETURN, brix_acc_tables_t::id_defs, acc_parse_ctx_t::id_tail, acc_parse_ctx_t::log, brix_acc_idrule_t::name, brix_acc_idrule_t::next, brix_acc_tables_t::pool, and acc_parse_ctx_t::tabs.
Referenced by acc_dispatch_record().
acc_record_named()
ngx_int_t acc_record_named (acc_parse_ctx_t * pc, char rtype, char ** w, ngx_uint_t n)
Definition at line 422 of file authfile_record.c.
References acc_build_caps(), acc_named_is_dup(), acc_named_resolve(), acc_named_store(), acc_subspace(), acc_named_t::alluser, acc_named_t::anyuser, acc_parse_ctx_t::log, name, brix_acc_tables_t::parse_spacechar, and acc_parse_ctx_t::tabs.
Referenced by acc_dispatch_record().
acc_record_rule()
ngx_int_t acc_record_rule (acc_parse_ctx_t * pc, char ** w, ngx_uint_t n, int exclusive)
Definition at line 311 of file authfile_record.c.
References acc_build_caps(), brix_acc_idrule_t::caps, acc_parse_ctx_t::excl_seq, brix_acc_tables_t::id_defs, acc_parse_ctx_t::log, brix_acc_idrule_t::name, and acc_parse_ctx_t::tabs.
Referenced by acc_dispatch_record().
acc_tok_next()
int acc_tok_next (acc_tok_t * t, char ** word)
Definition at line 110 of file authfile_tokenize.c.
References ACC_GAP_EOF, ACC_GAP_EOR, acc_pstrdup(), ACC_TOK_EOF, ACC_TOK_EOR, acc_tok_skip_gap(), ACC_TOK_WORD, acc_tok_t::end, acc_tok_t::p, and acc_tok_t::pool.
Referenced by acc_tokenize_and_dispatch().