nginx-xrootd: src/auth/voms/extract.c File Reference
extract.c File Reference
#include "voms_internal.h"
#include <limits.h>
Data Structures
struct brix_voms_out_t
Functions
static ngx_int_t brix_voms_precheck (X509 *leaf, const ngx_str_t *vomsdir, const ngx_str_t *cert_dir, size_t buf_sz)
static void brix_voms_path_to_buf (const ngx_str_t *src, char *dst)
static void brix_voms_reset_outputs (const brix_voms_out_t *out)
static STACK_OF (X509)
static ngx_int_t brix_voms_retrieve_and_collect (ngx_log_t *log, X509 *leaf, STACK_OF(X509) *voms_chain, struct voms_data *vd, const brix_voms_out_t *out)
ngx_int_t brix_extract_voms_info (ngx_log_t *log, X509 *leaf, STACK_OF(X509) *chain, const ngx_str_t *vomsdir, const ngx_str_t *cert_dir, char *primary_vo, size_t primary_vo_sz, char *vo_list, size_t vo_list_sz)
Function Documentation
brix_extract_voms_info()
ngx_int_t brix_extract_voms_info (ngx_log_t * log, X509 * leaf, STACK_OF(X509) * chain, const ngx_str_t * vomsdir, const ngx_str_t * cert_dir, char * primary_vo, size_t primary_vo_sz, char * vo_list, size_t vo_list_sz)
Definition at line 198 of file extract.c.
References brix_voms_api, brix_voms_path_to_buf(), brix_voms_precheck(), brix_voms_reset_outputs(), brix_voms_retrieve_and_collect(), brix_voms_api_t::destroy, brix_voms_api_t::init, log, PATH_MAX, brix_voms_out_t::primary_vo, brix_voms_out_t::primary_vo_sz, STACK_OF(), brix_voms_out_t::vo_list, and brix_voms_out_t::vo_list_sz.
Referenced by gsi_cert_extract_voms(), and webdav_extract_and_set_voms_identity().
brix_voms_path_to_buf()
static void brix_voms_path_to_buf (const ngx_str_t * src, char * dst) static
Definition at line 94 of file extract.c.
References ngx_memcpy.
Referenced by brix_extract_voms_info().
brix_voms_precheck()
static ngx_int_t brix_voms_precheck (X509 * leaf, const ngx_str_t * vomsdir, const ngx_str_t * cert_dir, size_t buf_sz) static
Definition at line 64 of file extract.c.
References brix_voms_loaded.
Referenced by brix_extract_voms_info().
brix_voms_reset_outputs()
static void brix_voms_reset_outputs (const brix_voms_out_t * out) static
Definition at line 109 of file extract.c.
References brix_voms_out_t::primary_vo, brix_voms_out_t::primary_vo_sz, brix_voms_out_t::vo_list, and brix_voms_out_t::vo_list_sz.
Referenced by brix_extract_voms_info().
brix_voms_retrieve_and_collect()
static ngx_int_t brix_voms_retrieve_and_collect (ngx_log_t * log, X509 * leaf, STACK_OF(X509) * voms_chain, struct voms_data * vd, const brix_voms_out_t * out) static
Definition at line 172 of file extract.c.
References brix_collect_voms_vos(), brix_voms_api, brix_voms_api_t::error_message, log, brix_voms_out_t::primary_vo, brix_voms_out_t::primary_vo_sz, brix_voms_api_t::retrieve, brix_voms_out_t::vo_list, brix_voms_out_t::vo_list_sz, VOMS_RECURSE_CHAIN, VOMS_VERR_NODATA, and VOMS_VERR_NOEXT.
Referenced by brix_extract_voms_info().
STACK_OF()
static STACK_OF (X509) static
Definition at line 132 of file extract.c.
References STACK_OF().
Referenced by brix_extract_voms_info(), and STACK_OF().