nginx-xrootd: src/protocols/s3/auth_bearer.c File Reference
auth_bearer.c File Reference
#include "s3.h"
#include "auth_bearer.h"
#include "auth/token/token.h"
#include "core/types/identity.h"
#include "observability/metrics/unified.h"
#include <string.h>
Macros
#define S3_BEARER_MAX_TOKEN_LEN 8192
#define S3_BEARER_PREFIX_LEN 7
Functions
ngx_str_t get_header (ngx_http_request_t *r, const char *name)
int s3_bearer_present (ngx_http_request_t *r)
ngx_int_t s3_verify_bearer (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, brix_identity_t *identity)
Macro Definition Documentation
S3_BEARER_MAX_TOKEN_LEN
#define S3_BEARER_MAX_TOKEN_LEN 8192
Definition at line 39 of file auth_bearer.c.
S3_BEARER_PREFIX_LEN
#define S3_BEARER_PREFIX_LEN 7
Definition at line 42 of file auth_bearer.c.
Function Documentation
get_header()
ngx_str_t get_header (ngx_http_request_t * r, const char * name) extern
Definition at line 21 of file auth_sigv4_parse.c.
References brix_http_get_header(), and name.
Referenced by s3_bearer_present(), and s3_verify_bearer().
s3_bearer_present()
int s3_bearer_present (ngx_http_request_t * r)
Definition at line 55 of file auth_bearer.c.
References get_header(), and S3_BEARER_PREFIX_LEN.
Referenced by s3_verify_sigv4().
s3_verify_bearer()
ngx_int_t s3_verify_bearer (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, brix_identity_t * identity)
Definition at line 88 of file auth_bearer.c.
References BRIX_AUTHN_TOKEN, brix_identity_set_token_claims(), brix_metric_auth(), BRIX_PROTO_S3, brix_token_validate(), get_header(), ngx_http_s3_loc_conf_t::jwks_key_count, ngx_http_s3_loc_conf_t::jwks_keys, S3_BEARER_MAX_TOKEN_LEN, S3_BEARER_PREFIX_LEN, s3_send_xml_error(), ngx_http_s3_loc_conf_t::token_audience, ngx_http_s3_loc_conf_t::token_clock_skew, and ngx_http_s3_loc_conf_t::token_issuer.
Referenced by s3_verify_sigv4().