nginx-xrootd: src/auth/token/config.c File Reference
config.c File Reference
#include "core/config/config.h"
#include "issuer_registry.h"
#include <sys/stat.h>
Functions
static ngx_int_t brix_token_configure_registry (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
static ngx_int_t brix_token_require_single_issuer_fields (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
static ngx_int_t brix_token_load_and_register_jwks (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
static void brix_token_log_summary (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
ngx_int_t brix_configure_token_auth (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
Function Documentation
brix_configure_token_auth()
ngx_int_t brix_configure_token_auth (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf)
Definition at line 192 of file config.c.
References BRIX_AUTH_BOTH, BRIX_AUTH_TOKEN, brix_token_configure_registry(), brix_token_load_and_register_jwks(), brix_token_log_summary(), and brix_token_require_single_issuer_fields().
Referenced by postconf_prepare_servers().
brix_token_configure_registry()
static ngx_int_t brix_token_configure_registry (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf) static
Definition at line 25 of file config.c.
References BRIX_AUTHZ_CAPABILITY, and brix_token_registry_build().
Referenced by brix_configure_token_auth().
brix_token_load_and_register_jwks()
static ngx_int_t brix_token_load_and_register_jwks (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf) static
Definition at line 107 of file config.c.
References brix_jwks_load(), brix_jwks_register_cleanup(), BRIX_MAX_JWKS_KEYS, BRIX_PATH_REGULAR_FILE, brix_validate_path(), and stat().
Referenced by brix_configure_token_auth().
brix_token_log_summary()
static void brix_token_log_summary (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf) static
Definition at line 158 of file config.c.
Referenced by brix_configure_token_auth().
brix_token_require_single_issuer_fields()
static ngx_int_t brix_token_require_single_issuer_fields (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf) static
Definition at line 66 of file config.c.
Referenced by brix_configure_token_auth().