nginx-xrootd: src/protocols/webdav/auth_basic.c File Reference
auth_basic.c File Reference
#include "webdav.h"
#include "webdav_auth.h"
#include "auth/pwd/pwd.h"
#include <limits.h>
#include <string.h>
Functions
static ngx_int_t wb_parse_basic_userpass (ngx_http_request_t *r, ngx_str_t *user, ngx_str_t *pass)
static ngx_http_brix_webdav_req_ctx_t * wb_ensure_ctx (ngx_http_request_t *r)
ngx_int_t webdav_verify_basic_pwd (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
Function Documentation
wb_ensure_ctx()
static ngx_http_brix_webdav_req_ctx_t * wb_ensure_ctx (ngx_http_request_t * r) static
Definition at line 107 of file auth_basic.c.
References brix_identity_alloc(), ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, and ngx_pcalloc().
Referenced by webdav_verify_basic_pwd().
wb_parse_basic_userpass()
static ngx_int_t wb_parse_basic_userpass (ngx_http_request_t * r, ngx_str_t * user, ngx_str_t * pass) static
Definition at line 49 of file auth_basic.c.
References b64, and ngx_pnalloc().
Referenced by webdav_verify_basic_pwd().
webdav_verify_basic_pwd()
ngx_int_t webdav_verify_basic_pwd (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 144 of file auth_basic.c.
References ngx_http_brix_webdav_req_ctx_t::auth_source, BRIX_AUTHN_PWD, brix_identity_set_dn(), brix_identity_set_vos_csv(), brix_metric_auth(), BRIX_PROTO_WEBDAV, brix_pwd_file_lookup(), BRIX_PWD_HASH_LEN, BRIX_PWD_MAX_SALT, brix_pwd_verify(), ngx_http_brix_webdav_req_ctx_t::dn, ngx_http_brix_webdav_req_ctx_t::identity, ngx_memcpy, PATH_MAX, ngx_http_brix_webdav_loc_conf_t::pwd_file, ngx_http_brix_webdav_req_ctx_t::verified, wb_ensure_ctx(), and wb_parse_basic_userpass().
Referenced by access_try_basic().