nginx-xrootd: src/auth/authz/acc/authfile.c File Reference
authfile.c File Reference
#include "acc.h"
#include <limits.h>
#include "core/compat/alloc_guard.h"
#include "core/compat/log_diag.h"
Data Structures
struct acc_tok_t
Macros
#define BRIX_ACC_AUTHDB_MAX (1024 * 1024)
Enumerations
enum { ACC_TOK_EOF = -1 , ACC_TOK_EOR = 0 , ACC_TOK_WORD = 1 }
Functions
static char * acc_pstrdup (ngx_pool_t *pool, const u_char *s, size_t len)
static int acc_tok_next (acc_tok_t *t, char **word)
static void acc_subspace (char *id, char sc)
static const char * acc_uri_decode (ngx_pool_t *pool, const char *s)
static brix_acc_named_t * acc_named_prepend (ngx_pool_t *pool, brix_acc_named_t **head, const char *name, brix_acc_cap_t *caps)
static brix_acc_cap_t * acc_cap_path (ngx_pool_t *pool, const char *path, const char *privs, ngx_log_t *log)
static ngx_int_t acc_build_caps (ngx_pool_t *pool, brix_acc_tables_t *tabs, char **words, ngx_uint_t start, ngx_uint_t n, brix_acc_cap_t **out, ngx_log_t *log)
static int acc_selector_ok (char c)
static ngx_int_t acc_iddef_set (char **slot, char *val, char sel, const char *defname, char spacechar, ngx_log_t *log)
static ngx_int_t acc_record_iddef (brix_acc_tables_t *tabs, char **w, ngx_uint_t n, brix_acc_idrule_t **id_tail, ngx_log_t *log)
static ngx_int_t acc_record_rule (brix_acc_tables_t *tabs, char **w, ngx_uint_t n, int exclusive, int *excl_seq, ngx_log_t *log)
static ngx_int_t acc_record_named (brix_acc_tables_t *tabs, char rtype, char **w, ngx_uint_t n, ngx_log_t *log)
static void acc_finalize_rules (brix_acc_tables_t *tabs, ngx_log_t *log)
static ngx_int_t acc_dispatch_record (brix_acc_tables_t *tabs, char **w, ngx_uint_t n, brix_acc_idrule_t **id_tail, int *excl_seq, ngx_log_t *log)
brix_acc_tables_t * brix_acc_authfile_parse (ngx_log_t *log, const char *file, char spacechar, ngx_int_t uri_decode)
Macro Definition Documentation
BRIX_ACC_AUTHDB_MAX
#define BRIX_ACC_AUTHDB_MAX (1024 * 1024)
Definition at line 27 of file authfile.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ACC_TOK_EOF
ACC_TOK_EOR
ACC_TOK_WORD
Definition at line 36 of file authfile.c.
Function Documentation
acc_build_caps()
static ngx_int_t acc_build_caps (ngx_pool_t * pool, brix_acc_tables_t * tabs, char ** words, ngx_uint_t start, ngx_uint_t n, brix_acc_cap_t ** out, ngx_log_t * log) static
Definition at line 215 of file authfile.c.
References acc_cap_path(), acc_uri_decode(), brix_acc_named_find(), BRIX_PCALLOC_OR_RETURN, log, brix_acc_cap_t::next, brix_acc_tables_t::parse_uridecode, and brix_acc_tables_t::t_list.
Referenced by acc_record_named(), and acc_record_rule().
acc_cap_path()
static brix_acc_cap_t * acc_cap_path (ngx_pool_t * pool, const char * path, const char * privs, ngx_log_t * log) static
Definition at line 175 of file authfile.c.
References brix_acc_parse_privs(), BRIX_DIAG_EMERG, BRIX_PCALLOC_OR_RETURN, brix_acc_cap_t::caps, log, brix_acc_cap_t::path, brix_acc_cap_t::pins, brix_acc_cap_t::plen, and brix_acc_cap_t::prem.
Referenced by acc_build_caps().
acc_dispatch_record()
static ngx_int_t acc_dispatch_record (brix_acc_tables_t * tabs, char ** w, ngx_uint_t n, brix_acc_idrule_t ** id_tail, int * excl_seq, ngx_log_t * log) static
Definition at line 501 of file authfile.c.
References acc_record_iddef(), acc_record_named(), acc_record_rule(), BRIX_DIAG_EMERG, log, and brix_acc_tables_t::rule_count.
Referenced by brix_acc_authfile_parse().
acc_finalize_rules()
static void acc_finalize_rules (brix_acc_tables_t * tabs, ngx_log_t * log) static
Definition at line 466 of file authfile.c.
References brix_acc_idrule_t::caps, brix_acc_tables_t::id_defs, log, brix_acc_idrule_t::name, brix_acc_idrule_t::next, brix_acc_idrule_t::rule, brix_acc_tables_t::sx_list, and brix_acc_tables_t::sy_list.
Referenced by brix_acc_authfile_parse().
acc_iddef_set()
static ngx_int_t acc_iddef_set (char ** slot, char * val, char sel, const char * defname, char spacechar, ngx_log_t * log) static
Definition at line 293 of file authfile.c.
References acc_subspace(), and log.
Referenced by acc_record_iddef().
acc_named_prepend()
static brix_acc_named_t * acc_named_prepend (ngx_pool_t * pool, brix_acc_named_t ** head, const char * name, brix_acc_cap_t * caps) static
Definition at line 158 of file authfile.c.
References brix_acc_named_t::caps, brix_acc_named_t::name, name, brix_acc_named_t::next, ngx_pcalloc(), and brix_acc_named_t::nlen.
Referenced by acc_record_named().
acc_pstrdup()
static char * acc_pstrdup (ngx_pool_t * pool, const u_char * s, size_t len) static
Definition at line 39 of file authfile.c.
References ngx_memcpy, ngx_pnalloc(), and s.
Referenced by acc_tok_next().
acc_record_iddef()
static ngx_int_t acc_record_iddef (brix_acc_tables_t * tabs, char ** w, ngx_uint_t n, brix_acc_idrule_t ** id_tail, ngx_log_t * log) static
Definition at line 311 of file authfile.c.
References acc_iddef_set(), acc_selector_ok(), BRIX_PCALLOC_OR_RETURN, brix_acc_idrule_t::grp, brix_acc_idrule_t::host, brix_acc_tables_t::id_defs, log, brix_acc_idrule_t::name, brix_acc_idrule_t::next, brix_acc_idrule_t::org, brix_acc_tables_t::parse_spacechar, brix_acc_tables_t::pool, brix_acc_idrule_t::role, and brix_acc_idrule_t::user.
Referenced by acc_dispatch_record().
acc_record_named()
static ngx_int_t acc_record_named (brix_acc_tables_t * tabs, char rtype, char ** w, ngx_uint_t n, ngx_log_t * log) static
Definition at line 402 of file authfile.c.
References acc_build_caps(), acc_named_prepend(), acc_subspace(), brix_acc_named_find(), brix_acc_tables_t::d_list, brix_acc_tables_t::g_list, brix_acc_tables_t::h_list, log, brix_acc_tables_t::n_list, name, brix_acc_tables_t::o_list, brix_acc_tables_t::parse_spacechar, brix_acc_tables_t::pool, brix_acc_tables_t::r_list, brix_acc_tables_t::t_list, brix_acc_tables_t::u_list, brix_acc_tables_t::x_list, and brix_acc_tables_t::z_list.
Referenced by acc_dispatch_record().
acc_record_rule()
static ngx_int_t acc_record_rule (brix_acc_tables_t * tabs, char ** w, ngx_uint_t n, int exclusive, int * excl_seq, ngx_log_t * log) static
Definition at line 373 of file authfile.c.
References acc_build_caps(), brix_acc_idrule_t::caps, brix_acc_tables_t::id_defs, log, brix_acc_idrule_t::name, and brix_acc_tables_t::pool.
Referenced by acc_dispatch_record().
acc_selector_ok()
static int acc_selector_ok (char c) static
Definition at line 282 of file authfile.c.
References c.
Referenced by acc_record_iddef().
acc_subspace()
static void acc_subspace (char * id, char sc) static
Definition at line 113 of file authfile.c.
Referenced by acc_iddef_set(), and acc_record_named().
acc_tok_next()
static int acc_tok_next (acc_tok_t * t, char ** word) static
Definition at line 57 of file authfile.c.
References acc_pstrdup(), ACC_TOK_EOF, ACC_TOK_EOR, ACC_TOK_WORD, acc_tok_t::end, acc_tok_t::p, and acc_tok_t::pool.
Referenced by brix_acc_authfile_parse().
acc_uri_decode()
static const char * acc_uri_decode (ngx_pool_t * pool, const char * s) static
Definition at line 131 of file authfile.c.
References ngx_pnalloc(), and s.
Referenced by acc_build_caps().
brix_acc_authfile_parse()
brix_acc_tables_t * brix_acc_authfile_parse (ngx_log_t * log, const char * file, char spacechar, ngx_int_t uri_decode)
Definition at line 540 of file authfile.c.
References acc_dispatch_record(), acc_finalize_rules(), ACC_TOK_EOF, acc_tok_next(), ACC_TOK_WORD, BRIX_ACC_AUTHDB_MAX, BRIX_DIAG_EMERG, acc_tok_t::end, log, brix_acc_tables_t::mtime, ngx_pcalloc(), ngx_pnalloc(), acc_tok_t::p, brix_acc_tables_t::parse_spacechar, brix_acc_tables_t::parse_uridecode, brix_acc_tables_t::pool, and acc_tok_t::pool.
Referenced by brix_acc_build().