nginx-xrootd: src/auth/authz/acc/access.c File Reference
access.c File Reference
#include "acc.h"
Data Structures
struct acc_sel_ctx_t
struct acc_eval_t
Typedefs
typedef int(* acc_sel_fn) (const acc_sel_ctx_t *s)
Functions
void brix_acc_set_group_resolvers (brix_acc_unixgrp_fn ug, brix_acc_netgrp_fn ng)
static int acc_sel_org (const acc_sel_ctx_t *s)
static int acc_sel_role (const acc_sel_ctx_t *s)
static int acc_sel_group (const acc_sel_ctx_t *s)
static int acc_sel_user (const acc_sel_ctx_t *s)
static int acc_sel_host (const acc_sel_ctx_t *s)
static int acc_applies (const brix_acc_idrule_t *r, const brix_acc_attr_t *attr, const char *name, const char *host)
static brix_acc_privs_t acc_access2 (const brix_acc_priv_caps_t *caps, brix_acc_op_t op)
static int acc_match_exclusive (const acc_eval_t *e)
static void acc_grant_host (const acc_eval_t *e)
static void acc_grant_user (const acc_eval_t *e)
static void acc_grant_tuples (const acc_eval_t *e)
brix_acc_privs_t brix_acc_access (brix_acc_tables_t *tabs, const brix_acc_entity_t *ent, const char *path, brix_acc_op_t op)
Variables
static brix_acc_unixgrp_fn acc_unixgrp_resolver = NULL
static brix_acc_netgrp_fn acc_netgrp_member = NULL
static const acc_sel_fn acc_sel_predicates []
Typedef Documentation
acc_sel_fn
typedef int(* acc_sel_fn) (const acc_sel_ctx_t *s)
Definition at line 127 of file access.c.
Function Documentation
acc_access2()
static brix_acc_privs_t acc_access2 (const brix_acc_priv_caps_t * caps, brix_acc_op_t op) static
Definition at line 162 of file access.c.
References BRIX_ACC_PRIV_NONE, brix_acc_test(), BRIX_AOP_ANY, brix_acc_priv_caps_t::nprivs, op, and brix_acc_priv_caps_t::pprivs.
Referenced by brix_acc_access().
acc_applies()
static int acc_applies (const brix_acc_idrule_t * r, const brix_acc_attr_t * attr, const char * name, const char * host) static
Definition at line 146 of file access.c.
References acc_sel_predicates, host, name, and s.
Referenced by acc_grant_tuples(), and acc_match_exclusive().
acc_grant_host()
static void acc_grant_host (const acc_eval_t * e) static
Definition at line 224 of file access.c.
References acc_netgrp_member, brix_acc_cap_privs(), brix_acc_domain_find(), brix_acc_named_find(), brix_acc_named_t::caps, acc_eval_t::caps, brix_acc_tables_t::d_list, acc_eval_t::ent, brix_acc_tables_t::h_list, brix_acc_entity_t::host, brix_acc_tables_t::n_list, brix_acc_named_t::name, brix_acc_entity_t::name, brix_acc_named_t::next, acc_eval_t::path, acc_eval_t::plen, acc_eval_t::tabs, and brix_acc_tables_t::z_list.
Referenced by brix_acc_access().
acc_grant_tuples()
static void acc_grant_tuples (const acc_eval_t * e) static
Definition at line 300 of file access.c.
References acc_applies(), brix_acc_cap_privs(), brix_acc_named_find(), brix_acc_idrule_t::caps, acc_eval_t::caps, acc_eval_t::ent, brix_acc_tables_t::g_list, brix_acc_attr_t::grup, brix_acc_entity_t::host, brix_acc_entity_t::name, brix_acc_idrule_t::next, brix_acc_tables_t::o_list, acc_eval_t::path, acc_eval_t::plen, brix_acc_tables_t::r_list, brix_acc_attr_t::role, brix_acc_tables_t::sy_list, acc_eval_t::tabs, brix_acc_entity_t::tuples, acc_eval_t::tuples, and brix_acc_attr_t::vorg.
Referenced by brix_acc_access().
acc_grant_user()
static void acc_grant_user (const acc_eval_t * e) static
Definition at line 261 of file access.c.
References acc_unixgrp_resolver, brix_acc_cap_privs(), brix_acc_named_find(), acc_eval_t::caps, acc_eval_t::ent, brix_acc_tables_t::g_list, brix_acc_entity_t::isuser, brix_acc_entity_t::name, acc_eval_t::path, acc_eval_t::plen, brix_acc_entity_t::pool, acc_eval_t::tabs, brix_acc_tables_t::u_list, and brix_acc_tables_t::x_list.
Referenced by brix_acc_access().
acc_match_exclusive()
static int acc_match_exclusive (const acc_eval_t * e) static
Definition at line 199 of file access.c.
References acc_applies(), brix_acc_cap_privs(), brix_acc_idrule_t::caps, acc_eval_t::caps, acc_eval_t::ent, brix_acc_entity_t::host, brix_acc_entity_t::name, brix_acc_idrule_t::next, acc_eval_t::path, acc_eval_t::plen, brix_acc_tables_t::sx_list, acc_eval_t::tabs, brix_acc_entity_t::tuples, and acc_eval_t::tuples.
Referenced by brix_acc_access().
acc_sel_group()
static int acc_sel_group (const acc_sel_ctx_t * s) static
Definition at line 77 of file access.c.
References s.
acc_sel_host()
static int acc_sel_host (const acc_sel_ctx_t * s) static
Definition at line 103 of file access.c.
References s.
acc_sel_org()
static int acc_sel_org (const acc_sel_ctx_t * s) static
Definition at line 55 of file access.c.
References s.
acc_sel_role()
static int acc_sel_role (const acc_sel_ctx_t * s) static
Definition at line 66 of file access.c.
References s.
acc_sel_user()
static int acc_sel_user (const acc_sel_ctx_t * s) static
Definition at line 88 of file access.c.
References s.
brix_acc_access()
brix_acc_privs_t brix_acc_access (brix_acc_tables_t * tabs, const brix_acc_entity_t * ent, const char * path, brix_acc_op_t op)
Definition at line 345 of file access.c.
References acc_access2(), acc_grant_host(), acc_grant_tuples(), acc_grant_user(), acc_match_exclusive(), BRIX_ACC_PRIV_NONE, acc_eval_t::caps, acc_eval_t::ent, op, acc_eval_t::path, acc_eval_t::plen, acc_eval_t::tabs, brix_acc_entity_t::tuples, and acc_eval_t::tuples.
Referenced by brix_acc_gate_engine(), and brix_acc_http_authorize().
brix_acc_set_group_resolvers()
void brix_acc_set_group_resolvers (brix_acc_unixgrp_fn ug, brix_acc_netgrp_fn ng)
Definition at line 29 of file access.c.
References acc_netgrp_member, and acc_unixgrp_resolver.
Referenced by brix_acc_groups_init().
Variable Documentation
acc_netgrp_member
brix_acc_netgrp_fn acc_netgrp_member = NULL static
Definition at line 26 of file access.c.
Referenced by acc_grant_host(), and brix_acc_set_group_resolvers().
acc_sel_predicates
const acc_sel_fn acc_sel_predicates[] static
Initial value:
= {
    acc_sel_org,
    acc_sel_role,
    acc_sel_group,
    acc_sel_user,
    acc_sel_host,
}
Definition at line 129 of file access.c.
Referenced by acc_applies().
acc_unixgrp_resolver
brix_acc_unixgrp_fn acc_unixgrp_resolver = NULL static
Definition at line 25 of file access.c.
Referenced by acc_grant_user(), and brix_acc_set_group_resolvers().