nginx-xrootd: src/protocols/s3/aws_chunked_internal.h File Reference
aws_chunked_internal.h File Reference
#include "aws_chunked.h"
Data Structures
struct s3_chunk_ctx_t
Macros
#define S3_CHUNK_MAX_LINE 512 /* size line / trailer line cap */
#define S3_CHUNK_EXT_MAX 128 /* chunk-signature extension cap */
Enumerations
enum s3_chunk_state_t {
ST_SIZE = 0 , ST_EXT , ST_SIZE_LF , ST_DATA ,
ST_DATA_CR , ST_DATA_LF , ST_TRAILER , ST_DONE ,
ST_ERROR
}
Functions
void s3_chunk_fail (s3_chunk_ctx_t *c, int status)
int s3_chunk_feed (s3_chunk_ctx_t *c, const u_char *p, const u_char *end)
Macro Definition Documentation
S3_CHUNK_EXT_MAX
#define S3_CHUNK_EXT_MAX 128 /* chunk-signature extension cap */
Definition at line 34 of file aws_chunked_internal.h.
S3_CHUNK_MAX_LINE
#define S3_CHUNK_MAX_LINE 512 /* size line / trailer line cap */
Definition at line 33 of file aws_chunked_internal.h.
Enumeration Type Documentation
s3_chunk_state_t
enum s3_chunk_state_t
Enumerator
ST_SIZE
ST_EXT
ST_SIZE_LF
ST_DATA
ST_DATA_CR
ST_DATA_LF
ST_TRAILER
ST_DONE
ST_ERROR
Definition at line 37 of file aws_chunked_internal.h.
Function Documentation
s3_chunk_fail()
void s3_chunk_fail (s3_chunk_ctx_t * c, int status)
Definition at line 147 of file aws_chunked_parse.c.
References c, and ST_ERROR.
Referenced by chunk_consume_data(), chunk_scan_data_crlf(), chunk_scan_size_lf(), chunk_scan_size_line(), s3_chunk_emit(), s3_chunk_feed_buf(), and s3_chunk_verify().
s3_chunk_feed()
int s3_chunk_feed (s3_chunk_ctx_t * c, const u_char * p, const u_char * end)
Definition at line 453 of file aws_chunked_parse.c.
References c, chunk_feed_step(), ST_DONE, ST_ERROR, and STEP_ERROR.
Referenced by s3_chunk_feed_buf().