nginx-xrootd: src/protocols/s3/aws_chunked.h File Reference
aws_chunked.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
Data Structures
struct s3_chunk_trailer_t
struct s3_chunk_verify_t
Macros
#define S3_CHUNK_READ_WINDOW (64 * 1024)
Functions
int s3_body_is_aws_chunked (ngx_http_request_t *r)
int s3_aws_chunked_has_inner_coding (ngx_http_request_t *r)
ngx_int_t s3_aws_chunked_decode_to_fd (ngx_http_request_t *r, ngx_fd_t dst_fd, const char *log_path, uint64_t decoded_len_expected, s3_chunk_trailer_t *trailer, int *http_status_out, u_char *window, const s3_chunk_verify_t *verify)
Macro Definition Documentation
S3_CHUNK_READ_WINDOW
#define S3_CHUNK_READ_WINDOW (64 * 1024)
Definition at line 67 of file aws_chunked.h.
Function Documentation
s3_aws_chunked_decode_to_fd()
ngx_int_t s3_aws_chunked_decode_to_fd (ngx_http_request_t * r, ngx_fd_t dst_fd, const char * log_path, uint64_t decoded_len_expected, s3_chunk_trailer_t * trailer, int * http_status_out, u_char * window, const s3_chunk_verify_t * verify)
Definition at line 199 of file aws_chunked.c.
References brix_sha256_stream_free(), c, s3_chunk_dec_t::r, s3_chunk_dec_init(), and s3_chunk_dec_run().
Referenced by s3_chunk_aio_thread(), and s3_put_streaming().
s3_aws_chunked_has_inner_coding()
int s3_aws_chunked_has_inner_coding (ngx_http_request_t * r)
Definition at line 107 of file aws_chunked_encoding.c.
References brix_http_find_header(), inner_coding_is_passthrough(), inner_coding_next_token(), and tok.
Referenced by s3put_stream_aws_chunked().
s3_body_is_aws_chunked()
int s3_body_is_aws_chunked (ngx_http_request_t * r)
Definition at line 29 of file aws_chunked_encoding.c.
References brix_http_find_header().
Referenced by s3put_stream_body().