nginx-xrootd: src/protocols/s3/aws_chunked_parse.c File Reference
aws_chunked_parse.c File Reference
#include "aws_chunked.h"
#include "aws_chunked_internal.h"
#include "fs/vfs/vfs.h"
#include "s3.h"
#include "core/http/http_headers.h"
#include "core/compat/crypto.h"
#include "core/compat/hex.h"
#include <errno.h>
#include <string.h>
#include <unistd.h>
Enumerations
enum s3_chunk_step_t { STEP_CONT = 0 , STEP_ERROR }
Functions
static int s3_ct_eq (const char *a, const char *b, size_t n)
static int s3_chunk_ext_signature (const char *ext, size_t len, char out[65])
static int s3_chunk_verify (s3_chunk_ctx_t *c)
static int s3_hexdigit (unsigned char c, unsigned *out)
void s3_chunk_fail (s3_chunk_ctx_t *c, int status)
static int s3_chunk_emit (s3_chunk_ctx_t *c, const u_char *p, size_t n)
static void s3_chunk_trailer_line (s3_chunk_ctx_t *c)
static s3_chunk_step_t chunk_scan_size_line (s3_chunk_ctx_t *c, u_char ch, const u_char **pp)
static s3_chunk_step_t chunk_scan_ext_sig (s3_chunk_ctx_t *c, u_char ch, const u_char **pp)
static s3_chunk_step_t chunk_scan_size_lf (s3_chunk_ctx_t *c, u_char ch, const u_char **pp)
static s3_chunk_step_t chunk_consume_data (s3_chunk_ctx_t *c, const u_char **pp, const u_char *end)
static s3_chunk_step_t chunk_scan_data_crlf (s3_chunk_ctx_t *c, u_char ch, const u_char **pp)
static s3_chunk_step_t chunk_scan_trailer (s3_chunk_ctx_t *c, u_char ch, const u_char **pp)
static s3_chunk_step_t chunk_feed_step (s3_chunk_ctx_t *c, const u_char **pp, const u_char *end)
int s3_chunk_feed (s3_chunk_ctx_t *c, const u_char *p, const u_char *end)
Variables
static const char S3_EMPTY_SHA256_HEX []
Enumeration Type Documentation
s3_chunk_step_t
enum s3_chunk_step_t
Enumerator
STEP_CONT
STEP_ERROR
Definition at line 220 of file aws_chunked_parse.c.
Function Documentation
chunk_consume_data()
static s3_chunk_step_t chunk_consume_data (s3_chunk_ctx_t * c, const u_char ** pp, const u_char * end) static
Definition at line 326 of file aws_chunked_parse.c.
References brix_sha256_stream_update(), c, s3_chunk_emit(), s3_chunk_fail(), s3_chunk_verify(), ST_DATA_CR, STEP_CONT, and STEP_ERROR.
Referenced by chunk_feed_step().
chunk_feed_step()
static s3_chunk_step_t chunk_feed_step (s3_chunk_ctx_t * c, const u_char ** pp, const u_char * end) static
Definition at line 427 of file aws_chunked_parse.c.
References c, chunk_consume_data(), chunk_scan_data_crlf(), chunk_scan_ext_sig(), chunk_scan_size_lf(), chunk_scan_size_line(), chunk_scan_trailer(), ST_DATA, ST_DATA_CR, ST_DATA_LF, ST_EXT, ST_SIZE, ST_SIZE_LF, ST_TRAILER, and STEP_CONT.
Referenced by s3_chunk_feed().
chunk_scan_data_crlf()
static s3_chunk_step_t chunk_scan_data_crlf (s3_chunk_ctx_t * c, u_char ch, const u_char ** pp) static
Definition at line 364 of file aws_chunked_parse.c.
References c, s3_chunk_fail(), ST_DATA_CR, ST_DATA_LF, ST_SIZE, STEP_CONT, and STEP_ERROR.
Referenced by chunk_feed_step().
chunk_scan_ext_sig()
static s3_chunk_step_t chunk_scan_ext_sig (s3_chunk_ctx_t * c, u_char ch, const u_char ** pp) static
Definition at line 274 of file aws_chunked_parse.c.
References c, ST_SIZE_LF, and STEP_CONT.
Referenced by chunk_feed_step().
chunk_scan_size_lf()
static s3_chunk_step_t chunk_scan_size_lf (s3_chunk_ctx_t * c, u_char ch, const u_char ** pp) static
Definition at line 294 of file aws_chunked_parse.c.
References c, s3_chunk_fail(), s3_chunk_verify(), ST_DATA, ST_TRAILER, STEP_CONT, and STEP_ERROR.
Referenced by chunk_feed_step().
chunk_scan_size_line()
static s3_chunk_step_t chunk_scan_size_line (s3_chunk_ctx_t * c, u_char ch, const u_char ** pp) static
Definition at line 234 of file aws_chunked_parse.c.
References c, s3_chunk_fail(), s3_hexdigit(), ST_EXT, ST_SIZE_LF, STEP_CONT, and STEP_ERROR.
Referenced by chunk_feed_step().
chunk_scan_trailer()
static s3_chunk_step_t chunk_scan_trailer (s3_chunk_ctx_t * c, u_char ch, const u_char ** pp) static
Definition at line 396 of file aws_chunked_parse.c.
References c, s3_chunk_trailer_line(), ST_DONE, and STEP_CONT.
Referenced by chunk_feed_step().
s3_chunk_emit()
static int s3_chunk_emit (s3_chunk_ctx_t * c, const u_char * p, size_t n) static
Definition at line 156 of file aws_chunked_parse.c.
References brix_vfs_pwrite_full(), c, and s3_chunk_fail().
Referenced by chunk_consume_data().
s3_chunk_ext_signature()
static int s3_chunk_ext_signature (const char * ext, size_t len, char out[65]) static
Definition at line 60 of file aws_chunked_parse.c.
References hex(), and key.
Referenced by s3_chunk_verify().
s3_chunk_fail()
void s3_chunk_fail (s3_chunk_ctx_t * c, int status)
Definition at line 147 of file aws_chunked_parse.c.
References c, and ST_ERROR.
Referenced by chunk_consume_data(), chunk_scan_data_crlf(), chunk_scan_size_lf(), chunk_scan_size_line(), s3_chunk_emit(), s3_chunk_feed_buf(), and s3_chunk_verify().
s3_chunk_feed()
int s3_chunk_feed (s3_chunk_ctx_t * c, const u_char * p, const u_char * end)
Definition at line 453 of file aws_chunked_parse.c.
References c, chunk_feed_step(), ST_DONE, ST_ERROR, and STEP_ERROR.
Referenced by s3_chunk_feed_buf().
s3_chunk_trailer_line()
static void s3_chunk_trailer_line (s3_chunk_ctx_t * c) static
Definition at line 175 of file aws_chunked_parse.c.
References c, and ngx_memcpy.
Referenced by chunk_scan_trailer().
s3_chunk_verify()
static int s3_chunk_verify (s3_chunk_ctx_t * c) static
Definition at line 96 of file aws_chunked_parse.c.
References brix_hex_encode(), brix_hmac_sha256(), brix_sha256_stream_final(), c, ngx_memcpy, s3_chunk_ext_signature(), s3_chunk_fail(), s3_ct_eq(), and S3_EMPTY_SHA256_HEX.
Referenced by chunk_consume_data(), and chunk_scan_size_lf().
s3_ct_eq()
static int s3_ct_eq (const char * a, const char * b, size_t n) static
Definition at line 47 of file aws_chunked_parse.c.
Referenced by s3_chunk_verify().
s3_hexdigit()
static int s3_hexdigit (unsigned char c, unsigned * out) static
Definition at line 138 of file aws_chunked_parse.c.
References c.
Referenced by chunk_scan_size_line().
Variable Documentation
S3_EMPTY_SHA256_HEX
const char S3_EMPTY_SHA256_HEX[] static
Initial value:
=
    "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
Definition at line 42 of file aws_chunked_parse.c.
Referenced by s3_chunk_verify().