nginx-xrootd: src/protocols/s3/aws_chunked.c File Reference
aws_chunked.c File Reference
#include "aws_chunked.h"
#include "fs/vfs/vfs.h"
#include "s3.h"
#include "core/http/http_headers.h"
#include "core/compat/crypto.h"
#include "core/compat/hex.h"
#include <errno.h>
#include <string.h>
#include <unistd.h>
Data Structures
struct s3_chunk_ctx_t
Macros
#define S3_CHUNK_MAX_LINE 512 /* size line / trailer line cap */
#define S3_CHUNK_EXT_MAX 128 /* chunk-signature extension cap */
Enumerations
enum s3_chunk_state_t {
ST_SIZE = 0 , ST_EXT , ST_SIZE_LF , ST_DATA ,
ST_DATA_CR , ST_DATA_LF , ST_TRAILER , ST_DONE ,
ST_ERROR
}
Functions
static void s3_chunk_fail (s3_chunk_ctx_t *c, int status)
static int s3_ct_eq (const char *a, const char *b, size_t n)
static int s3_chunk_ext_signature (const char *ext, size_t len, char out[65])
static int s3_chunk_verify (s3_chunk_ctx_t *c)
static int s3_hexdigit (unsigned char c, unsigned *out)
static int s3_chunk_emit (s3_chunk_ctx_t *c, const u_char *p, size_t n)
static void s3_chunk_trailer_line (s3_chunk_ctx_t *c)
static int s3_chunk_feed (s3_chunk_ctx_t *c, const u_char *p, const u_char *end)
int s3_body_is_aws_chunked (ngx_http_request_t *r)
int s3_aws_chunked_has_inner_coding (ngx_http_request_t *r)
static int s3_chunk_feed_buf (s3_chunk_ctx_t *c, ngx_buf_t *b, u_char *window)
ngx_int_t s3_aws_chunked_decode_to_fd (ngx_http_request_t *r, ngx_fd_t dst_fd, const char *log_path, uint64_t decoded_len_expected, s3_chunk_trailer_t *trailer, int *http_status_out, u_char *window, const s3_chunk_verify_t *verify)
Variables
static const char S3_EMPTY_SHA256_HEX []
Macro Definition Documentation
S3_CHUNK_EXT_MAX
#define S3_CHUNK_EXT_MAX 128 /* chunk-signature extension cap */
Definition at line 23 of file aws_chunked.c.
S3_CHUNK_MAX_LINE
#define S3_CHUNK_MAX_LINE 512 /* size line / trailer line cap */
Definition at line 22 of file aws_chunked.c.
Enumeration Type Documentation
s3_chunk_state_t
enum s3_chunk_state_t
Enumerator
ST_SIZE
ST_EXT
ST_SIZE_LF
ST_DATA
ST_DATA_CR
ST_DATA_LF
ST_TRAILER
ST_DONE
ST_ERROR
Definition at line 31 of file aws_chunked.c.
Function Documentation
s3_aws_chunked_decode_to_fd()
ngx_int_t s3_aws_chunked_decode_to_fd (ngx_http_request_t * r, ngx_fd_t dst_fd, const char * log_path, uint64_t decoded_len_expected, s3_chunk_trailer_t * trailer, int * http_status_out, u_char * window, const s3_chunk_verify_t * verify)
Definition at line 472 of file aws_chunked.c.
References s3_chunk_trailer_t::algo_token, brix_sha256_stream_free(), brix_sha256_stream_new(), c, s3_chunk_verify_t::enabled, s3_chunk_feed_buf(), S3_CHUNK_READ_WINDOW, s3_chunk_verify_t::seed_signature, ST_DONE, ST_SIZE, and s3_chunk_trailer_t::value.
Referenced by s3_chunk_aio_thread(), and s3_put_streaming().
s3_aws_chunked_has_inner_coding()
int s3_aws_chunked_has_inner_coding (ngx_http_request_t * r)
Definition at line 392 of file aws_chunked.c.
References brix_http_find_header().
Referenced by s3_put_body_inner().
s3_body_is_aws_chunked()
int s3_body_is_aws_chunked (ngx_http_request_t * r)
Definition at line 362 of file aws_chunked.c.
References brix_http_find_header().
Referenced by s3_put_body_inner().
s3_chunk_emit()
static int s3_chunk_emit (s3_chunk_ctx_t * c, const u_char * p, size_t n) static
Definition at line 184 of file aws_chunked.c.
References brix_vfs_pwrite_full(), c, and s3_chunk_fail().
Referenced by s3_chunk_feed().
s3_chunk_ext_signature()
static int s3_chunk_ext_signature (const char * ext, size_t len, char out[65]) static
Definition at line 88 of file aws_chunked.c.
References hex(), and key.
Referenced by s3_chunk_verify().
s3_chunk_fail()
static void s3_chunk_fail (s3_chunk_ctx_t * c, int status) static
Definition at line 175 of file aws_chunked.c.
References c, and ST_ERROR.
Referenced by s3_chunk_emit(), s3_chunk_feed(), s3_chunk_feed_buf(), and s3_chunk_verify().
s3_chunk_feed()
static int s3_chunk_feed (s3_chunk_ctx_t * c, const u_char * p, const u_char * end) static
Definition at line 244 of file aws_chunked.c.
References brix_sha256_stream_update(), c, s3_chunk_emit(), s3_chunk_fail(), s3_chunk_trailer_line(), s3_chunk_verify(), s3_hexdigit(), ST_DATA, ST_DATA_CR, ST_DATA_LF, ST_DONE, ST_ERROR, ST_EXT, ST_SIZE, ST_SIZE_LF, and ST_TRAILER.
Referenced by s3_chunk_feed_buf().
s3_chunk_feed_buf()
static int s3_chunk_feed_buf (s3_chunk_ctx_t * c, ngx_buf_t * b, u_char * window) static
Definition at line 435 of file aws_chunked.c.
References brix_vfs_pread_full(), c, s3_chunk_fail(), s3_chunk_feed(), S3_CHUNK_READ_WINDOW, ST_DONE, and ST_ERROR.
Referenced by s3_aws_chunked_decode_to_fd().
s3_chunk_trailer_line()
static void s3_chunk_trailer_line (s3_chunk_ctx_t * c) static
Definition at line 203 of file aws_chunked.c.
References c, and ngx_memcpy.
Referenced by s3_chunk_feed().
s3_chunk_verify()
static int s3_chunk_verify (s3_chunk_ctx_t * c) static
Definition at line 124 of file aws_chunked.c.
References brix_hex_encode(), brix_hmac_sha256(), brix_sha256_stream_final(), c, ngx_memcpy, s3_chunk_ext_signature(), s3_chunk_fail(), s3_ct_eq(), and S3_EMPTY_SHA256_HEX.
Referenced by s3_chunk_feed().
s3_ct_eq()
static int s3_ct_eq (const char * a, const char * b, size_t n) static
Definition at line 75 of file aws_chunked.c.
Referenced by s3_chunk_verify().
s3_hexdigit()
static int s3_hexdigit (unsigned char c, unsigned * out) static
Definition at line 166 of file aws_chunked.c.
References c.
Referenced by s3_chunk_feed().
Variable Documentation
S3_EMPTY_SHA256_HEX
const char S3_EMPTY_SHA256_HEX[] static
Initial value:
=
    "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
Definition at line 27 of file aws_chunked.c.
Referenced by s3_chunk_verify().