nginx-xrootd: src/auth/token/b64url.c File Reference
b64url.c File Reference
#include "b64url.h"
#include <openssl/evp.h>
#include <string.h>
Functions
int xrdjwt_split (const char *tok, size_t len, xrdjwt_seg seg[3])
ssize_t b64url_decode (const char *in, size_t in_len, uint8_t *out, size_t out_max)
void b64url_encode (const char *src, size_t slen, char *dst, size_t dsz)
Function Documentation
b64url_decode()
ssize_t b64url_decode (const char * in, size_t in_len, uint8_t * out, size_t out_max)
Definition at line 42 of file b64url.c.
Referenced by brix_macaroon_validate_bundle(), brix_token_ec_pubkey_from_xy(), brix_token_peek_iss(), brix_token_rsa_pubkey_from_ne(), brix_token_validate(), decode_payload_json(), and s3_handle_list().
b64url_encode()
void b64url_encode (const char * src, size_t slen, char * dst, size_t dsz)
Definition at line 84 of file b64url.c.
Referenced by brix_jwt_sign_es256(), brix_macaroon_issue(), and s3_handle_list().
xrdjwt_split()
int xrdjwt_split (const char * tok, size_t len, xrdjwt_seg seg[3])
Definition at line 20 of file b64url.c.
References xrdjwt_seg::n, and xrdjwt_seg::p.
Referenced by brix_token_peek_iss(), brix_token_validate(), and decode_payload_json().