nginx-xrootd: src/fs/xfer/backend_async_queue.c File Reference
backend_async_queue.c File Reference
#include "backend_async_queue.h"
#include <ngx_event.h>
#include "stage_engine.h"
#include "stage_engine_internal.h"
#include "fs/vfs/vfs.h"
#include "fs/vfs/vfs_backend_registry.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct brix_baq_pending_t
Macros
#define BRIX_BAQ_MAX_PENDING 4096
Functions
void brix_baq_init (void)
static void baq_reqid_mint (char out[40])
static void baq_journal_write (const brix_baq_rec_t *rec)
static void baq_journal_remove (const char *reqid)
static int baq_apply (const brix_baq_rec_t *rec, ngx_log_t *log)
static int baq_apply_idempotent (const brix_baq_rec_t *rec, ngx_log_t *log)
static void baq_drain_all (void)
static void baq_drain_event_handler (ngx_event_t *ev)
static void baq_post_drain (void)
static ngx_uint_t baq_size_triggered (void)
static ngx_uint_t baq_time_triggered (void)
ngx_int_t brix_baq_enqueue (brix_baq_op_t op, const char *root_canon, const char *src_key, const char *dst_key, uint32_t mode, ngx_uint_t batch, ngx_msec_t wait_ms, brix_baq_done_pt done, void *client)
void brix_baq_tick (void)
void brix_baq_drop_client (void *client)
static int baq_reconcile_one (const char *path, ngx_log_t *log)
void brix_baq_reconcile (void)
Variables
static brix_baq_pending_t baq_pending [4096]
static ngx_uint_t baq_count
static char baq_journal_dir [1100]
static uint64_t baq_reqid_seq
static ngx_event_t baq_drain_ev
Macro Definition Documentation
BRIX_BAQ_MAX_PENDING
#define BRIX_BAQ_MAX_PENDING 4096
Definition at line 39 of file backend_async_queue.c.
Function Documentation
baq_apply()
static int baq_apply (const brix_baq_rec_t * rec, ngx_log_t * log) static
Definition at line 145 of file backend_async_queue.c.
References BRIX_BAQ_MKDIR, BRIX_BAQ_RENAME, BRIX_BAQ_RMDIR, BRIX_BAQ_UNLINK, brix_vfs_backend_resolve(), brix_vfs_mkdir_path(), brix_vfs_rename_path(), brix_vfs_rmdir_path(), brix_vfs_unlink_path(), brix_baq_rec_t::dst_key, log, brix_baq_rec_t::mode, brix_baq_rec_t::op, brix_baq_rec_t::root_canon, and brix_baq_rec_t::src_key.
Referenced by baq_apply_idempotent(), and baq_drain_all().
baq_apply_idempotent()
static int baq_apply_idempotent (const brix_baq_rec_t * rec, ngx_log_t * log) static
Definition at line 196 of file backend_async_queue.c.
References baq_apply(), BRIX_BAQ_MKDIR, BRIX_BAQ_RENAME, BRIX_BAQ_RMDIR, BRIX_BAQ_UNLINK, log, and brix_baq_rec_t::op.
Referenced by baq_reconcile_one().
baq_drain_all()
static void baq_drain_all (void) static
Definition at line 218 of file backend_async_queue.c.
References baq_apply(), baq_count, baq_journal_remove(), baq_pending, brix_baq_pending_t::client, brix_baq_pending_t::done, log, brix_baq_pending_t::rec, and brix_baq_rec_t::reqid.
Referenced by baq_drain_event_handler(), brix_baq_enqueue(), and brix_baq_tick().
baq_drain_event_handler()
static void baq_drain_event_handler (ngx_event_t * ev) static
Definition at line 251 of file backend_async_queue.c.
References baq_drain_all().
Referenced by baq_post_drain().
baq_journal_remove()
static void baq_journal_remove (const char * reqid) static
Definition at line 114 of file backend_async_queue.c.
References baq_journal_dir.
Referenced by baq_drain_all().
baq_journal_write()
static void baq_journal_write (const brix_baq_rec_t * rec) static
Definition at line 90 of file backend_async_queue.c.
References baq_journal_dir, close(), open(), and brix_baq_rec_t::reqid.
Referenced by brix_baq_enqueue().
baq_post_drain()
static void baq_post_drain (void) static
Definition at line 258 of file backend_async_queue.c.
References baq_drain_ev, and baq_drain_event_handler().
Referenced by brix_baq_enqueue().
baq_reconcile_one()
static int baq_reconcile_one (const char * path, ngx_log_t * log) static
Definition at line 402 of file backend_async_queue.c.
References baq_apply_idempotent(), BRIX_BAQ_MKDIR, close(), log, ngx_memcpy, brix_baq_rec_t::op, open(), read(), brix_baq_rec_t::root_canon, and brix_baq_rec_t::src_key.
Referenced by brix_baq_reconcile().
baq_reqid_mint()
static void baq_reqid_mint (char out[40]) static
Definition at line 81 of file backend_async_queue.c.
References baq_reqid_seq.
Referenced by brix_baq_enqueue().
baq_size_triggered()
static ngx_uint_t baq_size_triggered (void) static
Definition at line 272 of file backend_async_queue.c.
References baq_count, baq_pending, and brix_baq_pending_t::batch.
Referenced by brix_baq_enqueue().
baq_time_triggered()
static ngx_uint_t baq_time_triggered (void) static
Definition at line 290 of file backend_async_queue.c.
References baq_count, and baq_pending.
Referenced by brix_baq_tick().
brix_baq_drop_client()
void brix_baq_drop_client (void * client)
Definition at line 381 of file backend_async_queue.c.
References baq_count, and baq_pending.
Referenced by brix_on_disconnect().
brix_baq_enqueue()
ngx_int_t brix_baq_enqueue (brix_baq_op_t op, const char * root_canon, const char * src_key, const char * dst_key, uint32_t mode, ngx_uint_t batch, ngx_msec_t wait_ms, brix_baq_done_pt done, void * client)
Definition at line 310 of file backend_async_queue.c.
References baq_count, baq_drain_all(), baq_journal_write(), baq_pending, baq_post_drain(), baq_reqid_mint(), baq_size_triggered(), brix_baq_pending_t::batch, BRIX_BAQ_MAX_PENDING, brix_baq_pending_t::client, brix_baq_pending_t::done, brix_baq_rec_t::dst_key, brix_baq_rec_t::enqueued_at, brix_baq_pending_t::enqueued_ms, brix_baq_rec_t::mode, op, brix_baq_rec_t::op, brix_baq_pending_t::rec, brix_baq_rec_t::reqid, brix_baq_rec_t::root_canon, brix_baq_rec_t::src_key, and brix_baq_pending_t::wait_ms.
Referenced by brix_baq_http_try(), brix_root_backend_async_mv_try(), and brix_root_backend_async_try().
brix_baq_init()
void brix_baq_init (void)
Definition at line 59 of file backend_async_queue.c.
References baq_journal_dir, and stage_journal_dir.
Referenced by brix_init_stage_engine_worker().
brix_baq_reconcile()
void brix_baq_reconcile (void)
Definition at line 438 of file backend_async_queue.c.
References baq_journal_dir, baq_reconcile_one(), and log.
Referenced by brix_init_stage_engine_worker().
brix_baq_tick()
void brix_baq_tick (void)
Definition at line 373 of file backend_async_queue.c.
References baq_count, baq_drain_all(), and baq_time_triggered().
Referenced by brix_stage_sched_handler().
Variable Documentation
baq_count
ngx_uint_t baq_count static
Definition at line 51 of file backend_async_queue.c.
Referenced by baq_drain_all(), baq_size_triggered(), baq_time_triggered(), brix_baq_drop_client(), brix_baq_enqueue(), and brix_baq_tick().
baq_drain_ev
ngx_event_t baq_drain_ev static
Definition at line 54 of file backend_async_queue.c.
Referenced by baq_post_drain().
baq_journal_dir
char baq_journal_dir[1100] static
Definition at line 52 of file backend_async_queue.c.
Referenced by baq_journal_remove(), baq_journal_write(), brix_baq_init(), and brix_baq_reconcile().
baq_pending
brix_baq_pending_t baq_pending[4096] static
Definition at line 50 of file backend_async_queue.c.
Referenced by baq_drain_all(), baq_size_triggered(), baq_time_triggered(), brix_baq_drop_client(), and brix_baq_enqueue().
baq_reqid_seq
uint64_t baq_reqid_seq static
Definition at line 53 of file backend_async_queue.c.
Referenced by baq_reqid_mint().