nginx-xrootd: src/protocols/shared/backend_async_http.h File Reference
backend_async_http.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include "core/config/shared_conf.h"
#include "fs/xfer/backend_async_queue.h"
Typedefs
typedef void(* brix_baq_http_render_pt) (ngx_http_request_t *r, void *ctx, int op_errno)
Functions
ngx_int_t brix_baq_http_try (ngx_http_request_t *r, ngx_http_brix_shared_conf_t *common, brix_baq_op_t op, const char *root_canon, const char *src_key, const char *dst_key, uint32_t mode, brix_baq_http_render_pt render, void *ctx)
Typedef Documentation
brix_baq_http_render_pt
typedef void(* brix_baq_http_render_pt) (ngx_http_request_t *r, void *ctx, int op_errno)
Definition at line 37 of file backend_async_http.h.
Function Documentation
brix_baq_http_try()
ngx_int_t brix_baq_http_try (ngx_http_request_t * r, ngx_http_brix_shared_conf_t * common, brix_baq_op_t op, const char * root_canon, const char * src_key, const char * dst_key, uint32_t mode, brix_baq_http_render_pt render, void * ctx)
Definition at line 30 of file backend_async_http.c.
References ngx_http_brix_shared_conf_t::backend_async, ngx_http_brix_shared_conf_t::backend_async_batch, ngx_http_brix_shared_conf_t::backend_async_wait, baq_http_wake(), brix_baq_enqueue(), brix_baq_http_park_t::ctx, ngx_pcalloc(), op, brix_baq_http_park_t::r, and brix_baq_http_park_t::render.
Referenced by s3_dispatch_object_delete(), webdav_handle_delete(), and webdav_handle_move().