nginx-xrootd: src/protocols/root/write/backend_async_root.c File Reference
backend_async_root.c File Reference
#include "backend_async_root.h"
#include "protocols/root/response/response.h"
#include "protocols/root/connection/event_sched.h"
#include "core/compat/error_mapping.h"
#include "core/compat/err_strings.h"
#include "fs/xfer/backend_async_queue.h"
#include "fs/path/path.h"
#include <errno.h>
#include <limits.h>
#include <stdio.h>
Data Structures
struct brix_baq_root_park_t
Functions
static void baq_root_done (void *client, int op_errno)
int brix_root_backend_async_try (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const brix_op_desc_t *d, const char *resolved)
int brix_root_backend_async_mv_try (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *src_resolved, const char *dst_resolved)
Function Documentation
baq_root_done()
static void baq_root_done (void * client, int op_errno) static
Definition at line 65 of file backend_async_root.c.
References brix_baq_root_park_t::baq_op, BRIX_BAQ_RMDIR, brix_kxr_err_string(), brix_kxr_from_errno(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OK, brix_schedule_read_resume(), brix_send_error(), brix_send_ok(), c, brix_baq_root_park_t::c, code, brix_baq_root_park_t::ctx, brix_baq_root_park_t::detail, kXR_ok, brix_baq_root_park_t::op_id, brix_baq_root_park_t::resolved, brix_ctx_t::state, brix_baq_root_park_t::verb, and XRD_ST_REQ_HEADER.
Referenced by brix_root_backend_async_mv_try(), and brix_root_backend_async_try().
brix_root_backend_async_mv_try()
int brix_root_backend_async_mv_try (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * src_resolved, const char * dst_resolved)
Definition at line 158 of file backend_async_root.c.
References brix_baq_root_park_t::baq_op, brix_ctx_t::baq_park, baq_root_done(), brix_baq_enqueue(), BRIX_BAQ_RENAME, BRIX_OP_MV, c, brix_baq_root_park_t::c, brix_baq_root_park_t::ctx, brix_baq_root_park_t::detail, ngx_pcalloc(), brix_baq_root_park_t::op_id, brix_baq_root_park_t::resolved, brix_ctx_t::state, brix_baq_root_park_t::verb, XRD_ST_REQ_HEADER, and XRD_ST_WAITING_BAQ.
Referenced by brix_handle_mv().
brix_root_backend_async_try()
int brix_root_backend_async_try (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const brix_op_desc_t * d, const char * resolved)
Definition at line 102 of file backend_async_root.c.
References brix_baq_root_park_t::baq_op, brix_ctx_t::baq_park, baq_root_done(), brix_baq_enqueue(), BRIX_BAQ_RMDIR, BRIX_BAQ_UNLINK, c, brix_baq_root_park_t::c, brix_baq_root_park_t::ctx, brix_baq_root_park_t::detail, kXR_rm, kXR_rmdir, brix_op_desc_t::name, ngx_pcalloc(), brix_baq_root_park_t::op_id, brix_op_desc_t::op_id, brix_op_desc_t::opcode, brix_baq_root_park_t::resolved, brix_ctx_t::state, brix_baq_root_park_t::verb, XRD_ST_REQ_HEADER, and XRD_ST_WAITING_BAQ.
Referenced by brix_dispatch_op().