nginx-xrootd: src/fs/xfer/backend_async_queue.h File Reference
backend_async_queue.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <stdint.h>
Data Structures
struct brix_baq_rec_t
Typedefs
typedef void(* brix_baq_done_pt) (void *client, int op_errno)
Enumerations
enum brix_baq_op_t { BRIX_BAQ_UNLINK = 0 , BRIX_BAQ_RMDIR = 1 , BRIX_BAQ_RENAME = 2 , BRIX_BAQ_MKDIR = 3 }
Functions
void brix_baq_init (void)
ngx_int_t brix_baq_enqueue (brix_baq_op_t op, const char *root_canon, const char *src_key, const char *dst_key, uint32_t mode, ngx_uint_t batch, ngx_msec_t wait_ms, brix_baq_done_pt done, void *client)
void brix_baq_tick (void)
void brix_baq_drop_client (void *client)
void brix_baq_reconcile (void)
Typedef Documentation
brix_baq_done_pt
typedef void(* brix_baq_done_pt) (void *client, int op_errno)
Definition at line 76 of file backend_async_queue.h.
Enumeration Type Documentation
brix_baq_op_t
enum brix_baq_op_t
Enumerator
BRIX_BAQ_UNLINK
BRIX_BAQ_RMDIR
BRIX_BAQ_RENAME
BRIX_BAQ_MKDIR
Definition at line 45 of file backend_async_queue.h.
Function Documentation
brix_baq_drop_client()
void brix_baq_drop_client (void * client)
Definition at line 381 of file backend_async_queue.c.
References baq_count, and baq_pending.
Referenced by brix_on_disconnect().
brix_baq_enqueue()
ngx_int_t brix_baq_enqueue (brix_baq_op_t op, const char * root_canon, const char * src_key, const char * dst_key, uint32_t mode, ngx_uint_t batch, ngx_msec_t wait_ms, brix_baq_done_pt done, void * client)
Definition at line 310 of file backend_async_queue.c.
References baq_count, baq_drain_all(), baq_journal_write(), baq_pending, baq_post_drain(), baq_reqid_mint(), baq_size_triggered(), brix_baq_pending_t::batch, BRIX_BAQ_MAX_PENDING, brix_baq_pending_t::client, brix_baq_pending_t::done, brix_baq_rec_t::dst_key, brix_baq_rec_t::enqueued_at, brix_baq_pending_t::enqueued_ms, brix_baq_rec_t::mode, op, brix_baq_rec_t::op, brix_baq_pending_t::rec, brix_baq_rec_t::reqid, brix_baq_rec_t::root_canon, brix_baq_rec_t::src_key, and brix_baq_pending_t::wait_ms.
Referenced by brix_baq_http_try(), brix_root_backend_async_mv_try(), and brix_root_backend_async_try().
brix_baq_init()
void brix_baq_init (void)
Definition at line 59 of file backend_async_queue.c.
References baq_journal_dir, and stage_journal_dir.
Referenced by brix_init_stage_engine_worker().
brix_baq_reconcile()
void brix_baq_reconcile (void)
Definition at line 438 of file backend_async_queue.c.
References baq_journal_dir, baq_reconcile_one(), dropped, log, and replayed.
Referenced by brix_init_stage_engine_worker().
brix_baq_tick()
void brix_baq_tick (void)
Definition at line 373 of file backend_async_queue.c.
References baq_count, baq_drain_all(), and baq_time_triggered().
Referenced by brix_stage_sched_handler().