nginx-xrootd: src/protocols/root/response/basic.c File Reference
basic.c File Reference
#include "core/ngx_brix_module.h"
#include "core/compat/alloc_guard.h"
Functions
void brix_build_resp_hdr (const u_char *streamid, uint16_t status, uint32_t dlen, ServerResponseHdr *out)
ngx_int_t brix_send_ok (brix_ctx_t *ctx, ngx_connection_t *c, const void *body, uint32_t bodylen)
ngx_int_t brix_send_error (brix_ctx_t *ctx, ngx_connection_t *c, uint16_t errcode, const char *msg)
Function Documentation
brix_build_resp_hdr()
void brix_build_resp_hdr (const u_char * streamid, uint16_t status, uint32_t dlen, ServerResponseHdr * out)
Definition at line 33 of file basic.c.
References ServerResponseHdr::dlen, ServerResponseHdr::status, and ServerResponseHdr::streamid.
Referenced by brix_build_attn_asyncms_frame(), brix_build_chunked_chain(), brix_build_sendfile_chain(), brix_build_single_memory_chain(), brix_build_single_sendfile_chain(), brix_build_window_chain(), brix_dirlist_flush_chunk(), brix_dirlist_send_final(), brix_gsi_begin_delegation(), brix_handle_bind(), brix_handle_protocol(), brix_login_respond_anon(), brix_login_respond_authenticated(), brix_open_build_response(), brix_proxy_build_relay_buffer(), brix_send_attn(), brix_send_attn_asynresp(), brix_send_error(), brix_send_ok(), brix_send_redirect(), brix_send_redirect_tpc(), brix_send_wait(), brix_send_waitresp(), brix_sss_send_authmore(), brix_upstream_forward_response(), brix_vfs_io_dirlist_flush_chunk(), brix_vfs_io_execute_opendir(), gsi_frame_cert_response(), prepare_emit_stage(), pwd_send_credsreq(), ssi_open_send_reply(), tpc_done_send_open_ok(), tpc_send_open_response(), and zip_send_open_reply().
brix_send_error()
ngx_int_t brix_send_error (brix_ctx_t * ctx, ngx_connection_t * c, uint16_t errcode, const char * msg)
Definition at line 67 of file basic.c.
References brix_build_resp_hdr(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), c, brix_ctx_recv_t::cur_streamid, kXR_error, ngx_memcpy, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_auth_gate_deny(), brix_auth_gate_op(), brix_cache_fill_composed_done(), brix_cache_fill_done(), brix_cache_open_or_fill(), brix_ckscan_aio_done(), brix_ckscan_send_error(), brix_ckscan_sync(), brix_cksum_aio_done(), brix_close_pgw_gate(), brix_close_posc_commit(), brix_close_staged_commit(), brix_dirlist_aio_done(), brix_dirlist_alloc_chunk(), brix_dirlist_check_redirect(), brix_dispatch(), brix_dispatch_op(), brix_dispatch_require_auth(), brix_dispatch_require_login(), brix_dispatch_require_write(), brix_gsi_complete_auth(), brix_handle_async_ab(), brix_handle_async_av(), brix_handle_async_di(), brix_handle_async_go(), brix_handle_async_ms(), brix_handle_async_rd(), brix_handle_async_unav(), brix_handle_async_wt(), brix_handle_auth(), brix_handle_auth_inner(), brix_handle_bind(), brix_handle_chkpoint(), brix_handle_fattr(), brix_handle_host_auth(), brix_handle_krb5_auth(), brix_handle_link(), brix_handle_protocol(), brix_handle_query(), brix_handle_readv(), brix_handle_setattr(), brix_handle_sigver(), brix_handle_statx(), brix_handle_symlink(), brix_handle_token_auth(), brix_handle_unix_auth(), brix_login_check_username(), brix_login_precheck_and_parse(), brix_login_respond_authenticated(), brix_open_mode_guard(), brix_pgread_aio_done(), brix_pgread_parse_validate(), brix_prepare_send_fail(), brix_proxy_abort(), brix_proxy_dispatch(), brix_proxy_forward_request(), brix_proxy_lazy_open(), brix_proxy_lazy_open_failed(), brix_qcksum_handle_try_async(), brix_qcksum_manager_bounce(), brix_qcksum_open(), brix_qcksum_resolve(), brix_qcksum_select_algo(), brix_qcksum_try_async(), brix_query_ckscan(), brix_query_cksum_handle(), brix_query_cksum_send_error(), brix_query_config(), brix_query_fsinfo(), brix_query_prep_status(), brix_query_space(), brix_query_xattr(), brix_read_aio_done(), brix_read_window_emit(), brix_read_window_pump(), brix_readv_aio_done(), brix_readv_execute_sync(), brix_readv_validate_and_size(), brix_reject_bound_nonread_file_op(), brix_reject_dotdot_path(), brix_resolve_op_path(), brix_signing_enforce_level(), brix_ssi_open(), brix_ssi_query(), brix_ssi_write(), brix_staged_append(), brix_tpc_prepare_pull(), brix_tpc_start_pull(), brix_upstream_abort(), brix_upstream_forward_response(), brix_verify_pending_sigver(), brix_verify_sigver_hmac(), brix_write_aio_done_pipelined(), brix_write_aio_done_serial(), brix_writev_write_aio_done(), brix_zip_read(), ckp_begin(), ckp_rollback(), ckp_xeq(), ckp_xeq_dispatch(), ckp_xeq_pgwrite(), ckp_xeq_pgwrite_drain(), ckp_xeq_truncate(), ckp_xeq_validate_frame(), ckp_xeq_write(), ckp_xeq_writev(), fattr_check_request(), fattr_decode_names(), fattr_dispatch_named(), fattr_fhandle_target(), fattr_get(), fattr_list(), fattr_list_read_names(), fattr_list_recurse(), fattr_path_target(), fattr_select_target(), fattr_send_vector_status(), fattr_set(), gsi_auth_route_credtype(), gsi_cert_deny(), locate_check_data_server(), locate_resolve_reqpath(), manager_redirect_mutation(), mv_fail(), mv_parse_paths(), pgwrite_execute_sync(), pgwrite_parse_validate(), pgwrite_register_bad_pages(), proxy_reject_request(), pwd_round1(), pwd_round2(), pwd_send_credsreq(), read_validate_req(), ssi_open_cta_gate(), ssi_open_send_reply(), ssi_write_accumulate(), ssi_write_maybe_dispatch(), sss_reply(), tokenauth_extract(), tokenauth_map_identity(), tpc_done_reply_open(), tpc_done_send_open_ok(), tpc_done_sync_fail(), tpc_handle_dest(), tpc_prepare_check_preconditions(), writev_validate_framing(), writev_validate_handles(), and zip_open_error().
brix_send_ok()
ngx_int_t brix_send_ok (brix_ctx_t * ctx, ngx_connection_t * c, const void * body, uint32_t bodylen)
Definition at line 43 of file basic.c.
References brix_build_resp_hdr(), brix_queue_response(), c, brix_ctx_recv_t::cur_streamid, kXR_ok, ngx_memcpy, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_ckscan_aio_done(), brix_ckscan_sync(), brix_cksum_aio_done(), brix_handle_auth_inner(), brix_handle_close(), brix_handle_endsess(), brix_handle_locate(), brix_handle_prepare(), brix_handle_readlink(), brix_handle_stat(), brix_handle_statx(), brix_handle_truncate(), brix_prepare_handle_cancel(), brix_qcksum_compute_sync(), brix_query_cksum_handle(), brix_query_config(), brix_query_finfo(), brix_query_fsinfo(), brix_query_prep_status(), brix_query_space(), brix_query_stats(), brix_query_xattr(), brix_read_compressed(), brix_ssi_query(), brix_ssi_read(), brix_ssi_write(), brix_write_aio_done_pipelined(), brix_write_aio_serial_reply_ok(), brix_write_compressed(), brix_write_route_special(), brix_writev_write_aio_done(), brix_zip_read(), ckp_query(), ckp_xeq_truncate(), ckp_xeq_write(), ckp_xeq_writev(), fattr_get(), fattr_list(), fattr_list_read_names(), fattr_list_recurse(), fattr_send_vector_status(), prepare_dispatch_special(), prepare_emit_stage(), qprep_resolve_src(), read_validate_req(), stat_manager_route(), tpc_done_reply_sync(), writev_reply(), and writev_validate_framing().