nginx-xrootd: src/fs/path/beneath.c File Reference
beneath.c File Reference
#include "core/ngx_brix_module.h"
#include "beneath.h"
#include "auth/impersonate/impersonate.h"
#include <sys/syscall.h>
#include <linux/openat2.h>
#include <unistd.h>
#include <errno.h>
#include <limits.h>
#include <string.h>
Macros
#define RENAME_NOREPLACE
Functions
int brix_beneath_open_root (const char *root_canon)
static int do_openat2_resolve (int rootfd, const char *rel, int flags, mode_t mode, uint64_t resolve)
static int do_openat2 (int rootfd, const char *rel, int flags, mode_t mode)
int brix_open_beneath (int rootfd, const char *reqpath, int flags, mode_t mode)
int brix_stat_beneath (int rootfd, const char *reqpath, struct stat *st)
int brix_lstat_beneath (int rootfd, const char *reqpath, struct stat *st)
DIR * brix_opendir_beneath (int rootfd, const char *reqpath)
static int beneath_open_parent (int rootfd, const char *reqpath, char *pbuf, size_t pbufsz, const char **base)
int brix_unlink_beneath (int rootfd, const char *reqpath, int is_dir)
int brix_mkdir_beneath (int rootfd, const char *reqpath, mode_t mode)
int brix_rename_beneath (int rootfd, const char *src, const char *dst)
int brix_rename_beneath_excl (int rootfd, const char *src, const char *dst)
int brix_link_beneath (int rootfd, const char *src, const char *dst)
Macro Definition Documentation
RENAME_NOREPLACE
#define RENAME_NOREPLACE
Value:
                                      (1u << 0)   /* <linux/fs.h>; defined here to avoid the
                                      * header's struct collisions */
Definition at line 45 of file beneath.c.
Function Documentation
beneath_open_parent()
static int beneath_open_parent (int rootfd, const char * reqpath, char * pbuf, size_t pbufsz, const char ** base) static
Definition at line 230 of file beneath.c.
References brix_beneath_rel(), do_openat2(), and O_PATH.
Referenced by brix_link_beneath(), brix_mkdir_beneath(), brix_rename_beneath(), brix_rename_beneath_excl(), and brix_unlink_beneath().
brix_beneath_open_root()
int brix_beneath_open_root (const char * root_canon)
Definition at line 78 of file beneath.c.
References O_PATH, and open().
Referenced by brix_fs_remove_tree_at(), brix_staged_abort(), brix_staged_open(), brix_staged_open_resume(), dashboard_download_open(), dashboard_files_opendir(), ns_rel(), scan_run_walk(), sd_posix_init(), and staged_commit_internal().
brix_link_beneath()
int brix_link_beneath (int rootfd, const char * src, const char * dst)
Definition at line 363 of file beneath.c.
References beneath_open_parent(), brix_imp_client_active(), brix_imp_link(), close(), and PATH_MAX.
brix_lstat_beneath()
int brix_lstat_beneath (int rootfd, const char * reqpath, struct stat * st)
Definition at line 172 of file beneath.c.
References brix_beneath_rel(), brix_imp_client_active(), brix_imp_stat(), close(), do_openat2_resolve(), fstat(), and O_PATH.
Referenced by brix_fs_remove_tree_entry(), brix_lstat_confined_canon(), ns_delete_probe(), sd_posix_server_copy(), and sd_posix_stat().
brix_mkdir_beneath()
int brix_mkdir_beneath (int rootfd, const char * reqpath, mode_t mode)
Definition at line 274 of file beneath.c.
References beneath_open_parent(), brix_imp_client_active(), brix_imp_mkdir(), close(), and PATH_MAX.
Referenced by brix_mkdir_level_beneath(), brix_ns_mkdir(), and cms_posix_apply().
brix_open_beneath()
int brix_open_beneath (int rootfd, const char * reqpath, int flags, mode_t mode)
Definition at line 141 of file beneath.c.
References brix_beneath_rel(), brix_imp_client_active(), brix_imp_open(), and do_openat2().
Referenced by brix_ns_local_copy(), brix_staged_open(), brix_staged_open_resume(), brix_vfs_open_confined_fd(), brix_vfs_open_fd_at(), dashboard_download_open(), dashboard_files_opendir(), ns_copy_open_dst(), sd_posix_open(), sd_posix_opendir(), vfs_walk_emit_file(), and vfs_walk_opendir().
brix_opendir_beneath()
DIR * brix_opendir_beneath (int rootfd, const char * reqpath)
Definition at line 194 of file beneath.c.
References brix_beneath_rel(), close(), and do_openat2_resolve().
Referenced by brix_opendir_confined_canon().
brix_rename_beneath()
int brix_rename_beneath (int rootfd, const char * src, const char * dst)
Definition at line 293 of file beneath.c.
References beneath_open_parent(), brix_imp_client_active(), brix_imp_rename(), close(), and PATH_MAX.
Referenced by brix_ns_rename(), cms_posix_apply(), and staged_commit_internal().
brix_rename_beneath_excl()
int brix_rename_beneath_excl (int rootfd, const char * src, const char * dst)
Definition at line 327 of file beneath.c.
References beneath_open_parent(), brix_imp_client_active(), brix_imp_rename_noreplace(), close(), PATH_MAX, and RENAME_NOREPLACE.
Referenced by staged_commit_internal().
brix_stat_beneath()
int brix_stat_beneath (int rootfd, const char * reqpath, struct stat * st)
Definition at line 150 of file beneath.c.
References brix_beneath_rel(), brix_imp_client_active(), brix_imp_stat(), close(), do_openat2_resolve(), fstat(), and O_PATH.
Referenced by brix_lstat_confined_canon(), brix_ns_rename(), brix_open_read_probe(), brix_prepare_check_path(), brix_statx_process_path(), brix_vfs_walk(), cms_frame_state(), locate_check_data_server(), ns_copy_validate(), and qprep_status_for_path().
brix_unlink_beneath()
int brix_unlink_beneath (int rootfd, const char * reqpath, int is_dir)
Definition at line 255 of file beneath.c.
References beneath_open_parent(), brix_imp_client_active(), brix_imp_unlink(), close(), and PATH_MAX.
Referenced by brix_fs_remove_tree_at(), brix_fs_remove_tree_entry(), brix_staged_abort(), brix_vfs_unlink_at(), ns_delete_remove(), and staged_commit_internal().
do_openat2()
static int do_openat2 (int rootfd, const char * rel, int flags, mode_t mode) static
Definition at line 134 of file beneath.c.
References do_openat2_resolve().
Referenced by beneath_open_parent(), and brix_open_beneath().
do_openat2_resolve()
static int do_openat2_resolve (int rootfd, const char * rel, int flags, mode_t mode, uint64_t resolve) static
Definition at line 93 of file beneath.c.
References O_PATH.
Referenced by brix_lstat_beneath(), brix_opendir_beneath(), brix_stat_beneath(), and do_openat2().