nginx-xrootd: src/fs/path/beneath.h File Reference
beneath.h File Reference
#include <fcntl.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <dirent.h>
#include <string.h>
#include <stddef.h>
Functions
int brix_beneath_open_root (const char *root_canon)
int brix_open_beneath (int rootfd, const char *reqpath, int flags, mode_t mode)
int brix_stat_beneath (int rootfd, const char *reqpath, struct stat *st)
int brix_lstat_beneath (int rootfd, const char *reqpath, struct stat *st)
DIR * brix_opendir_beneath (int rootfd, const char *reqpath)
int brix_unlink_beneath (int rootfd, const char *reqpath, int is_dir)
int brix_mkdir_beneath (int rootfd, const char *reqpath, mode_t mode)
int brix_rename_beneath (int rootfd, const char *src, const char *dst)
int brix_rename_beneath_excl (int rootfd, const char *src, const char *dst)
int brix_link_beneath (int rootfd, const char *src, const char *dst)
static const char * brix_beneath_rel (const char *reqpath)
static const char * brix_beneath_strip_root (const char *root_canon, const char *abspath)
static int brix_beneath_full_path (const char *root_canon, const char *reqpath, char *buf, size_t bufsz)
Function Documentation
brix_beneath_full_path()
static int brix_beneath_full_path (const char * root_canon, const char * reqpath, char * buf, size_t bufsz) inline static
Definition at line 114 of file beneath.h.
References brix_beneath_rel().
Referenced by brix_dirlist_open_dir(), brix_http_resolve_path_ex(), brix_open_cached_read(), brix_open_read_resolve(), brix_open_write_resolve(), brix_path_resolve_beneath(), brix_prepare_check_path(), brix_qcksum_resolve(), brix_query_ckscan(), brix_query_opaquf(), brix_query_xattr(), brix_statx_process_path(), cms_posix_apply(), fattr_path_target(), locate_check_data_server(), mv_make_dst_parents(), op_path_probe(), qprep_emit_all(), stat_query_path(), and tpc_handle_dest().
brix_beneath_open_root()
int brix_beneath_open_root (const char * root_canon)
Definition at line 78 of file beneath.c.
References O_PATH, and open().
Referenced by brix_fs_remove_tree_at(), brix_staged_abort(), brix_staged_open(), brix_staged_open_resume(), dashboard_download_open(), dashboard_files_opendir(), ns_rel(), scan_run_walk(), sd_posix_init(), and staged_commit_internal().
brix_beneath_rel()
static const char * brix_beneath_rel (const char * reqpath) inline static
Definition at line 73 of file beneath.h.
Referenced by beneath_open_parent(), brix_beneath_full_path(), brix_lstat_beneath(), brix_open_beneath(), brix_open_cached_read(), brix_opendir_beneath(), and brix_stat_beneath().
brix_beneath_strip_root()
static const char * brix_beneath_strip_root (const char * root_canon, const char * abspath) inline static
Definition at line 97 of file beneath.h.
Referenced by brix_assert_dir_outside_export(), brix_fs_remove_tree_at(), brix_fs_remove_tree_entry(), brix_ns_local_copy(), brix_ns_rename(), brix_staged_abort(), brix_staged_open(), brix_staged_open_resume(), ns_rel(), and staged_commit_internal().
brix_link_beneath()
int brix_link_beneath (int rootfd, const char * src, const char * dst)
Definition at line 363 of file beneath.c.
References beneath_open_parent(), brix_imp_client_active(), brix_imp_link(), close(), and PATH_MAX.
brix_lstat_beneath()
int brix_lstat_beneath (int rootfd, const char * reqpath, struct stat * st)
Definition at line 172 of file beneath.c.
References brix_beneath_rel(), brix_imp_client_active(), brix_imp_stat(), close(), do_openat2_resolve(), fstat(), and O_PATH.
Referenced by brix_fs_remove_tree_entry(), brix_lstat_confined_canon(), ns_delete_probe(), sd_posix_server_copy(), and sd_posix_stat().
brix_mkdir_beneath()
int brix_mkdir_beneath (int rootfd, const char * reqpath, mode_t mode)
Definition at line 274 of file beneath.c.
References beneath_open_parent(), brix_imp_client_active(), brix_imp_mkdir(), close(), and PATH_MAX.
Referenced by brix_mkdir_level_beneath(), brix_ns_mkdir(), and cms_posix_apply().
brix_open_beneath()
int brix_open_beneath (int rootfd, const char * reqpath, int flags, mode_t mode)
Definition at line 141 of file beneath.c.
References brix_beneath_rel(), brix_imp_client_active(), brix_imp_open(), and do_openat2().
Referenced by brix_ns_local_copy(), brix_staged_open(), brix_staged_open_resume(), brix_vfs_open_confined_fd(), brix_vfs_open_fd_at(), dashboard_download_open(), dashboard_files_opendir(), ns_copy_open_dst(), sd_posix_open(), sd_posix_opendir(), vfs_walk_emit_file(), and vfs_walk_opendir().
brix_opendir_beneath()
DIR * brix_opendir_beneath (int rootfd, const char * reqpath)
Definition at line 194 of file beneath.c.
References brix_beneath_rel(), close(), and do_openat2_resolve().
Referenced by brix_opendir_confined_canon().
brix_rename_beneath()
int brix_rename_beneath (int rootfd, const char * src, const char * dst)
Definition at line 293 of file beneath.c.
References beneath_open_parent(), brix_imp_client_active(), brix_imp_rename(), close(), and PATH_MAX.
Referenced by brix_ns_rename(), cms_posix_apply(), and staged_commit_internal().
brix_rename_beneath_excl()
int brix_rename_beneath_excl (int rootfd, const char * src, const char * dst)
Definition at line 327 of file beneath.c.
References beneath_open_parent(), brix_imp_client_active(), brix_imp_rename_noreplace(), close(), PATH_MAX, and RENAME_NOREPLACE.
Referenced by staged_commit_internal().
brix_stat_beneath()
int brix_stat_beneath (int rootfd, const char * reqpath, struct stat * st)
Definition at line 150 of file beneath.c.
References brix_beneath_rel(), brix_imp_client_active(), brix_imp_stat(), close(), do_openat2_resolve(), fstat(), and O_PATH.
Referenced by brix_lstat_confined_canon(), brix_ns_rename(), brix_open_read_probe(), brix_prepare_check_path(), brix_statx_process_path(), brix_vfs_walk(), cms_frame_state(), locate_check_data_server(), ns_copy_validate(), and qprep_status_for_path().
brix_unlink_beneath()
int brix_unlink_beneath (int rootfd, const char * reqpath, int is_dir)
Definition at line 255 of file beneath.c.
References beneath_open_parent(), brix_imp_client_active(), brix_imp_unlink(), close(), and PATH_MAX.
Referenced by brix_fs_remove_tree_at(), brix_fs_remove_tree_entry(), brix_staged_abort(), brix_vfs_unlink_at(), ns_delete_remove(), and staged_commit_internal().