nginx-xrootd: src/protocols/root/session/bind.c File Reference
bind.c File Reference
#include "core/ngx_brix_module.h"
#include "registry.h"
#include "core/compat/alloc_guard.h"
Functions
ngx_int_t brix_handle_bind (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Variables
static ngx_uint_t brix_next_pathid = 0
Function Documentation
brix_handle_bind()
ngx_int_t brix_handle_bind (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 35 of file bind.c.
References brix_ctx_token_t::auth, brix_ctx_login_t::auth_done, brix_ctx_t::bound_sessid, BRIX_AUTHN_GSI, BRIX_AUTHN_TOKEN, brix_build_resp_hdr(), brix_identity_set_cstr(), brix_identity_set_dn(), brix_identity_set_subject(), brix_identity_set_vos_csv(), brix_log_access(), brix_next_pathid, BRIX_PALLOC_OR_RETURN, brix_queue_response(), brix_send_error(), BRIX_SESSION_ID_LEN, brix_session_lookup(), c, brix_ctx_recv_t::cur_streamid, brix_ctx_login_t::dn, brix_identity_t::dn, brix_ctx_recv_t::hdr_buf, brix_ctx_t::identity, brix_ctx_t::is_bound, kXR_NotAuthorized, kXR_ok, brix_ctx_login_t::logged_in, brix_ctx_t::login, ngx_memcpy, brix_ctx_t::pathid, brix_ctx_t::recv, xrdw_sessid_req_t::sessid, brix_ctx_t::token, brix_ctx_login_t::vo_list, XRD_RESPONSE_HDR_LEN, and xrdw_sessid_req_unpack().
Referenced by brix_dispatch_session_opcode().
Variable Documentation
brix_next_pathid
ngx_uint_t brix_next_pathid = 0 static
Definition at line 28 of file bind.c.
Referenced by brix_handle_bind().