nginx-xrootd: src/net/cms/blacklist_file.h File Reference
blacklist_file.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
Data Structures
struct brix_cms_blfile_entry_t
struct brix_cms_blfile_t
Macros
#define BRIX_CMS_BLFILE_MAX_ENTRIES 128
#define BRIX_CMS_BLFILE_MAX_BYTES 65536 /* re-read cap: admin file, tiny */
#define BRIX_CMS_BLFILE_POLL_MS 1000 /* min gap between stat() polls */
Functions
int brix_cms_blfile_parse_line (const char *line, size_t len, brix_cms_blfile_entry_t *out)
int brix_cms_blfile_entry_matches (const brix_cms_blfile_entry_t *e, const char *host, uint16_t port)
void brix_cms_blfile_poll (brix_cms_blfile_t *bl, const ngx_str_t *path, ngx_msec_t blacklist_ms, ngx_uint_t force, ngx_log_t *log)
Macro Definition Documentation
BRIX_CMS_BLFILE_MAX_BYTES
#define BRIX_CMS_BLFILE_MAX_BYTES 65536 /* re-read cap: admin file, tiny */
Definition at line 32 of file blacklist_file.h.
BRIX_CMS_BLFILE_MAX_ENTRIES
#define BRIX_CMS_BLFILE_MAX_ENTRIES 128
Definition at line 31 of file blacklist_file.h.
BRIX_CMS_BLFILE_POLL_MS
#define BRIX_CMS_BLFILE_POLL_MS 1000 /* min gap between stat() polls */
Definition at line 33 of file blacklist_file.h.
Function Documentation
brix_cms_blfile_entry_matches()
int brix_cms_blfile_entry_matches (const brix_cms_blfile_entry_t * e, const char * host, uint16_t port)
Definition at line 163 of file blacklist_file.c.
References blfile_parse_ipv4(), host, brix_cms_blfile_entry_t::host, brix_cms_blfile_entry_t::is_cidr, brix_cms_blfile_entry_t::mask, brix_cms_blfile_entry_t::net, port, and brix_cms_blfile_entry_t::port.
Referenced by brix_cms_blfile_poll().
brix_cms_blfile_parse_line()
int brix_cms_blfile_parse_line (const char * line, size_t len, brix_cms_blfile_entry_t * out)
Definition at line 120 of file blacklist_file.c.
References blfile_find_port_colon(), blfile_parse_cidr(), blfile_parse_uint(), brix_cms_blfile_entry_t::host, and brix_cms_blfile_entry_t::port.
Referenced by blfile_reload().
brix_cms_blfile_poll()
void brix_cms_blfile_poll (brix_cms_blfile_t * bl, const ngx_str_t * path, ngx_msec_t blacklist_ms, ngx_uint_t force, ngx_log_t * log)
Definition at line 272 of file blacklist_file.c.
References blfile_reload(), brix_cms_blfile_entry_matches(), BRIX_CMS_BLFILE_POLL_MS, brix_srv_blacklist(), BRIX_SRV_REGISTRY_SLOTS, brix_srv_snapshot(), brix_cms_blfile_t::entries, host, brix_srv_snapshot_entry_t::host, log, brix_cms_blfile_t::mtime, brix_cms_blfile_t::nentries, brix_cms_blfile_t::next_poll, port, brix_srv_snapshot_entry_t::port, s, and stat().
Referenced by cms_srv_blfile_tick().