nginx-xrootd: src/net/cms/blacklist_file.c File Reference
blacklist_file.c File Reference
#include "blacklist_file.h"
#include "net/manager/registry.h"
#include <stdio.h>
#include <string.h>
#include <arpa/inet.h>
#include <sys/stat.h>
Functions
static int blfile_parse_ipv4 (const char *s, size_t len, uint32_t *out)
static long blfile_parse_uint (const char *s, size_t len, long max)
static int blfile_parse_cidr (const char *line, size_t len, const char *slash, brix_cms_blfile_entry_t *out)
static int blfile_find_port_colon (const char *line, size_t len, const char **colon)
int brix_cms_blfile_parse_line (const char *line, size_t len, brix_cms_blfile_entry_t *out)
int brix_cms_blfile_entry_matches (const brix_cms_blfile_entry_t *e, const char *host, uint16_t port)
static void blfile_scan_line (const char *buf, size_t got, size_t *pos, size_t *start, size_t *end)
static void blfile_reload (brix_cms_blfile_t *bl, const char *path, ngx_log_t *log)
void brix_cms_blfile_poll (brix_cms_blfile_t *bl, const ngx_str_t *path, ngx_msec_t blacklist_ms, ngx_uint_t force, ngx_log_t *log)
Function Documentation
blfile_find_port_colon()
static int blfile_find_port_colon (const char * line, size_t len, const char ** colon) static
Definition at line 92 of file blacklist_file.c.
Referenced by brix_cms_blfile_parse_line().
blfile_parse_cidr()
static int blfile_parse_cidr (const char * line, size_t len, const char * slash, brix_cms_blfile_entry_t * out) static
Definition at line 66 of file blacklist_file.c.
References blfile_parse_ipv4(), blfile_parse_uint(), brix_cms_blfile_entry_t::is_cidr, brix_cms_blfile_entry_t::mask, and brix_cms_blfile_entry_t::net.
Referenced by brix_cms_blfile_parse_line().
blfile_parse_ipv4()
static int blfile_parse_ipv4 (const char * s, size_t len, uint32_t * out) static
Definition at line 23 of file blacklist_file.c.
References s.
Referenced by blfile_parse_cidr(), and brix_cms_blfile_entry_matches().
blfile_parse_uint()
static long blfile_parse_uint (const char * s, size_t len, long max) static
Definition at line 43 of file blacklist_file.c.
References s.
Referenced by blfile_parse_cidr(), and brix_cms_blfile_parse_line().
blfile_reload()
static void blfile_reload (brix_cms_blfile_t * bl, const char * path, ngx_log_t * log) static
Definition at line 218 of file blacklist_file.c.
References blfile_scan_line(), BRIX_CMS_BLFILE_MAX_BYTES, BRIX_CMS_BLFILE_MAX_ENTRIES, brix_cms_blfile_parse_line(), brix_cms_blfile_t::entries, log, and brix_cms_blfile_t::nentries.
Referenced by brix_cms_blfile_poll().
blfile_scan_line()
static void blfile_scan_line (const char * buf, size_t got, size_t * pos, size_t * start, size_t * end) static
Definition at line 191 of file blacklist_file.c.
Referenced by blfile_reload().
brix_cms_blfile_entry_matches()
int brix_cms_blfile_entry_matches (const brix_cms_blfile_entry_t * e, const char * host, uint16_t port)
Definition at line 163 of file blacklist_file.c.
References blfile_parse_ipv4(), host, brix_cms_blfile_entry_t::host, brix_cms_blfile_entry_t::is_cidr, brix_cms_blfile_entry_t::mask, brix_cms_blfile_entry_t::net, port, and brix_cms_blfile_entry_t::port.
Referenced by brix_cms_blfile_poll().
brix_cms_blfile_parse_line()
int brix_cms_blfile_parse_line (const char * line, size_t len, brix_cms_blfile_entry_t * out)
Definition at line 120 of file blacklist_file.c.
References blfile_find_port_colon(), blfile_parse_cidr(), blfile_parse_uint(), brix_cms_blfile_entry_t::host, and brix_cms_blfile_entry_t::port.
Referenced by blfile_reload().
brix_cms_blfile_poll()
void brix_cms_blfile_poll (brix_cms_blfile_t * bl, const ngx_str_t * path, ngx_msec_t blacklist_ms, ngx_uint_t force, ngx_log_t * log)
Definition at line 272 of file blacklist_file.c.
References blfile_reload(), brix_cms_blfile_entry_matches(), BRIX_CMS_BLFILE_POLL_MS, brix_srv_blacklist(), BRIX_SRV_REGISTRY_SLOTS, brix_srv_snapshot(), brix_cms_blfile_t::entries, host, brix_srv_snapshot_entry_t::host, log, brix_cms_blfile_t::mtime, brix_cms_blfile_t::nentries, brix_cms_blfile_t::next_poll, port, brix_srv_snapshot_entry_t::port, s, and stat().
Referenced by cms_srv_blfile_tick().