nginx-xrootd: src/protocols/root/protocol/bootstrap_pack.h File Reference
bootstrap_pack.h File Reference
#include <stdint.h>
#include <string.h>
#include <arpa/inet.h>
#include "wire_core_requests.h"
#include "flags.h"
#include "protocols/root/protocol/codec/wire_codec.h"
Functions
static void xrd_pack_handshake (ClientInitHandShake *hs)
static void xrd_pack_protocol_request (ClientProtocolRequest *pr, const uint8_t streamid[2], uint8_t flags)
static void xrd_pack_login_request (ClientLoginRequest *lr, const uint8_t streamid[2], int32_t pid, const char *username, uint8_t capver)
Function Documentation
xrd_pack_handshake()
static void xrd_pack_handshake (ClientInitHandShake * hs) inline static
Definition at line 45 of file bootstrap_pack.h.
References ClientInitHandShake::fifth, ClientInitHandShake::fourth, and ROOTD_PQ.
Referenced by brix_upstream_build_bootstrap(), do_handshake(), origin_bs_handshake(), and tpc_bootstrap_handshake().
xrd_pack_login_request()
static void xrd_pack_login_request (ClientLoginRequest * lr, const uint8_t streamid[2], int32_t pid, const char * username, uint8_t capver) inline static
Definition at line 84 of file bootstrap_pack.h.
References ClientLoginRequest::dlen, kXR_login, xrdw_login_req_t::pid, ClientLoginRequest::requestid, ClientLoginRequest::streamid, xrdw_login_req_t::username, and xrdw_login_req_pack().
Referenced by brix_upstream_build_bootstrap(), brix_upstream_build_login(), do_login(), origin_bs_login(), and tpc_bootstrap_login().
xrd_pack_protocol_request()
static void xrd_pack_protocol_request (ClientProtocolRequest * pr, const uint8_t streamid[2], uint8_t flags) inline static
Definition at line 61 of file bootstrap_pack.h.
References xrdw_protocol_req_t::clientpv, ClientProtocolRequest::dlen, kXR_ExpLogin, kXR_protocol, kXR_PROTOCOLVERSION, ClientProtocolRequest::requestid, ClientProtocolRequest::streamid, and xrdw_protocol_req_pack().
Referenced by brix_upstream_build_bootstrap(), do_handshake(), origin_bs_protocol(), and tpc_bootstrap_protocol().