nginx-xrootd: client/apps/fs/brixmount_unittest.c File Reference
brixmount_unittest.c File Reference
#include <stdio.h>
#include <string.h>
Data Structures
struct brix_driver_t
Macros
#define CHECK(c, n)
Typedefs
typedef int(* brix_driver_fn) (int, char **)
Functions
int brixmount_dispatch (int argc, char **argv, const brix_driver_t *drv, size_t ndrv)
int brixmount_overlay_route (int argc, char **argv, int(*list_fn)(const char *, FILE *), int(*reset_fn)(const char *))
static int mock_ok (int argc, char **argv)
static int mock_list (const char *dir, FILE *out)
static int mock_reset (const char *dir)
int main (void)
Variables
static int g_checks
static int g_failed
static char g_last_brand [64]
static char g_last_ep [128]
static char g_last_mnt [128]
static int g_last_argc
static int g_last_opt_seen
static char g_cli_dir [128]
static char g_cli_which
Macro Definition Documentation
CHECK
#define CHECK (c, n)
Value:
    do{ g_checks++; if(c){printf("  ok   %s\n",n);} \
    else{printf("  FAIL %s (line %d)\n",n,__LINE__); g_failed++;} }while(0)
Definition at line 19 of file brixmount_unittest.c.
Typedef Documentation
brix_driver_fn
typedef int(* brix_driver_fn) (int, char **)
Definition at line 11 of file brixmount_unittest.c.
Function Documentation
brixmount_dispatch()
int brixmount_dispatch (int argc, char ** argv, const brix_driver_t * drv, size_t ndrv)
Definition at line 73 of file brixmount.c.
References brix_driver_t::brand, brix_cli_hint(), brix_suggest(), BRIXMOUNT_MAX_ARGS, brixmount_usage(), brix_driver_t::fn, and brix_driver_t::type.
Referenced by main(), and main().
brixmount_overlay_route()
int brixmount_overlay_route (int argc, char ** argv, int(*)(const char *, FILE *) list_fn, int(*)(const char *) reset_fn)
Definition at line 56 of file brixmount.c.
Referenced by main(), and main().
main()
int main (void)
Definition at line 50 of file brixmount_unittest.c.
References brixmount_dispatch(), brixmount_overlay_route(), CHECK, g_checks, g_cli_dir, g_cli_which, g_failed, g_last_brand, g_last_ep, g_last_mnt, g_last_opt_seen, mock_list(), mock_ok(), and mock_reset().
mock_list()
static int mock_list (const char * dir, FILE * out) static
Definition at line 38 of file brixmount_unittest.c.
References g_cli_dir, and g_cli_which.
Referenced by main().
mock_ok()
static int mock_ok (int argc, char ** argv) static
Definition at line 25 of file brixmount_unittest.c.
References g_last_argc, g_last_brand, g_last_ep, g_last_mnt, and g_last_opt_seen.
Referenced by main().
mock_reset()
static int mock_reset (const char * dir) static
Definition at line 44 of file brixmount_unittest.c.
References g_cli_dir, and g_cli_which.
Referenced by main().
Variable Documentation
g_checks
int g_checks static
Definition at line 18 of file brixmount_unittest.c.
Referenced by main().
g_cli_dir
char g_cli_dir[128] static
Definition at line 36 of file brixmount_unittest.c.
Referenced by main(), mock_list(), and mock_reset().
g_cli_which
char g_cli_which static
Definition at line 37 of file brixmount_unittest.c.
Referenced by main(), mock_list(), and mock_reset().
g_failed
int g_failed static
Definition at line 18 of file brixmount_unittest.c.
Referenced by main().
g_last_argc
int g_last_argc static
Definition at line 24 of file brixmount_unittest.c.
Referenced by mock_ok().
g_last_brand
char g_last_brand[64] static
Definition at line 23 of file brixmount_unittest.c.
Referenced by main(), and mock_ok().
g_last_ep
char g_last_ep[128] static
Definition at line 23 of file brixmount_unittest.c.
Referenced by main(), and mock_ok().
g_last_mnt
char g_last_mnt[128] static
Definition at line 23 of file brixmount_unittest.c.
Referenced by main(), and mock_ok().
g_last_opt_seen
int g_last_opt_seen static
Definition at line 24 of file brixmount_unittest.c.
Referenced by main(), and mock_ok().