nginx-xrootd: client/lib/brix_ops.h File Reference
brix_ops.h File Reference
Data Structures
struct brix_file
struct brix_readv_seg
struct brix_writev_seg
struct brix_rfile
struct brix_ckv_report
struct brix_proxy_opts
struct brix_copy_opts
Macros
#define XRDC_VEC_MAXSEGS 1024
#define XRDC_VEC_MAXBYTES (256u << 20) /* aggregate readv/writev payload cap */
#define XRDC_CKV_HEX_MAX 129
#define XRDC_EXIT_USAGE 50
#define XRDC_EXIT_IO 51
#define XRDC_EXIT_AUTH 53
#define BRIX_RMTREE_DRYRUN 0x1
#define XRDC_IO_URING_AUTO 0
#define XRDC_IO_URING_ON 1
#define XRDC_IO_URING_OFF 2
#define XRDC_TPC_OFF 0
#define XRDC_TPC_FIRST 1 /* try TPC, fall back to client-mediated on failure */
#define XRDC_TPC_ONLY 2 /* TPC or hard fail */
#define XRDC_TPC_DELEGATE 3 /* TPC with credential delegation (tpc.token_mode) */
#define XRDC_SYNC_SIZE 0 /* skip when sizes match (legacy --sync) */
#define XRDC_SYNC_MTIME 1 /* sizes match AND dst mtime >= src mtime */
#define XRDC_SYNC_CKSUM 2 /* sizes match AND checksums match (caller does I/O) */
Typedefs
typedef int(* brix_op_fn) (brix_conn *c, void *arg, brix_status *st)
typedef int(* brix_walk_fn) (const char *path, const brix_dirent *e, int depth, void *u)
typedef int(* brix_rmtree_report) (const char *path, int is_dir, void *u)
typedef void(* brix_progress_cb) (void *arg, long long done, long long total)
Enumerations
enum brix_op_class { XRDC_OP_READONLY , XRDC_OP_IDEMPOTENT , XRDC_OP_MUTATION_NORMALIZE , XRDC_OP_UNSAFE }
enum brix_cksum_algo {
XRDC_CK_ADLER32 = 0 , XRDC_CK_CRC32C , XRDC_CK_MD5 , XRDC_CK_CRC64 ,
XRDC_CK_CRC64NVME , XRDC_CK_ZCRC32
}
enum brix_ckv_mode { XRDC_CKV_AUTO = 0 , XRDC_CKV_CACHE , XRDC_CKV_STORAGE }
enum brix_ckv_result {
XRDC_CKV_OK = 0 , XRDC_CKV_MISMATCH , XRDC_CKV_NO_RECORD , XRDC_CKV_UNSUPPORTED ,
XRDC_CKV_ERROR
}
Functions
int brix_stat (brix_conn *c, const char *path, brix_statinfo *out, brix_status *st)
int brix_lstat (brix_conn *c, const char *path, brix_statinfo *out, brix_status *st)
int brix_dirlist (brix_conn *c, const char *path, int want_stat, brix_dirent **ents, size_t *count, brix_status *st)
int brix_file_open_read (brix_conn *c, const char *path, brix_file *f, brix_status *st)
int brix_file_open_write (brix_conn *c, const char *path, int force, int posc, brix_file *f, brix_status *st)
int brix_file_open_update (brix_conn *c, const char *path, int posc, brix_file *f, brix_status *st)
ssize_t brix_inflate_frame (uint8_t codec, const uint8_t *comp, size_t comp_len, void *out, size_t out_cap, brix_status *st)
uint8_t * brix_deflate_frame (uint8_t codec, const void *in, size_t in_len, size_t *out_len, brix_status *st)
ssize_t brix_file_read (brix_conn *c, brix_file *f, int64_t offset, void *buf, size_t len, brix_status *st)
int brix_file_write (brix_conn *c, brix_file *f, int64_t offset, const void *buf, size_t len, brix_status *st)
int brix_file_close (brix_conn *c, brix_file *f, brix_status *st)
ssize_t brix_file_readv (brix_conn *c, brix_file *f, brix_readv_seg *segs, size_t nseg, brix_status *st)
int brix_file_writev (brix_conn *c, brix_file *f, const brix_writev_seg *segs, size_t nseg, int do_sync, brix_status *st)
int brix_file_open_opaque (brix_conn *c, const char *path, const char *opaque, int write, int force, int posc, brix_file *f, brix_status *st)
int brix_file_sync (brix_conn *c, brix_file *f, brix_status *st)
ssize_t brix_file_pgread (brix_conn *c, brix_file *f, int64_t offset, void *buf, size_t len, brix_status *st)
int brix_file_pgwrite (brix_conn *c, brix_file *f, int64_t offset, const void *buf, size_t len, brix_status *st)
int brix_resilient_window_ms (const brix_conn *c)
int brix_reconnect_home (brix_conn *c, brix_status *st)
int brix_connect_resilient (brix_conn *c, const brix_url *u, const brix_opts *o, brix_status *st)
int brix_with_resilience (brix_conn *c, int max_stall_ms, brix_op_class cls, int benign_errno, brix_op_fn op, void *arg, brix_status *st)
int brix_roundtrip_resilient (brix_conn *c, void *hdr24, const void *payload, uint32_t plen, brix_op_class cls, int benign_errno, uint16_t *status, uint8_t **body, uint32_t *blen, brix_status *st)
int brix_rfile_open_read (brix_conn *c, const char *path, const char *opaque, int pgrw, int max_stall_ms, brix_rfile *rf, brix_status *st)
int brix_rfile_open_write (brix_conn *c, const char *path, int force, int posc, int pgrw, int max_stall_ms, brix_rfile *rf, brix_status *st)
ssize_t brix_rfile_pread (brix_rfile *rf, int64_t off, void *buf, size_t len, brix_status *st)
int brix_rfile_pwrite (brix_rfile *rf, int64_t off, const void *buf, size_t len, brix_status *st)
int brix_rfile_close (brix_rfile *rf, brix_status *st)
int brix_ckmf_parse_line (const char *line, char *hex, size_t hexsz, char *rel, size_t relsz)
int brix_cksum_algo_parse (const char *name, brix_cksum_algo *out)
int brix_cksum_fd (int fd, brix_cksum_algo algo, char *hex, size_t hexsz, brix_status *st)
int brix_query_cksum (brix_conn *c, const char *path, const char *algo_name, char *hex, size_t hexsz, brix_status *st)
brix_ckv_result brix_cks_verify_file (const char *path, const char *want_algo, brix_ckv_mode mode, brix_ckv_report *rep, brix_status *st)
int brix_cli_cksum_main (const char *prog, const char *algo_name, brix_cksum_algo algo, const char *arg, int err_exit)
void brix_opts_init (brix_opts *o)
struct brix_cred_store * brix_cli_cred_store_build (const char *proxy, const char *bearer, const char *bearer_file, const char *s3_access, const char *s3_secret, const char *oidc_account, int auto_refresh)
void brix_cred_store_free (struct brix_cred_store *s)
int brix_opts_parse_arg (brix_opts *o, int argc, char **argv, int *i)
int brix_cli_parse_io_uring (const char *s)
int brix_cli_connect (const char *endpoint, const brix_opts *o, brix_conn *c, const char *prog, brix_status *st)
int brix_report_err (FILE *out, const char *tool, const char *op, const char *path, const brix_status *st, int want_write, const brix_url *url)
void brix_path_resolve (const char *cwd, const char *arg, char *out, size_t outsz)
int brix_open_credfile (const char *path, int secret, brix_status *st)
struct bio_st * brix_credfile_bio (const char *path, int secret)
void brix_fmt_size (int64_t n, char *out, size_t sz, int human)
int64_t brix_parse_bytes (const char *s)
void brix_rate_pace (const struct timespec *start, int64_t sent, double rate)
int brix_mkdir (brix_conn *c, const char *path, int mode, int parents, brix_status *st)
int brix_rm (brix_conn *c, const char *path, brix_status *st)
int brix_rmdir (brix_conn *c, const char *path, brix_status *st)
int brix_mv (brix_conn *c, const char *src, const char *dst, brix_status *st)
int brix_chmod (brix_conn *c, const char *path, int mode, brix_status *st)
int brix_truncate (brix_conn *c, const char *path, int64_t size, brix_status *st)
int brix_tree_walk (brix_conn *c, const char *path, brix_walk_fn fn, void *u, brix_status *st)
int brix_rmtree (brix_conn *c, const char *path, unsigned flags, brix_rmtree_report report, void *u, brix_status *st)
int brix_rel_is_unsafe (const char *rel)
int brix_ext_probe (brix_conn *c, int *has_setattr, int *has_symlink, int *has_readlink, int *has_link, brix_status *st)
int brix_setattr (brix_conn *c, const char *path, int set_times, const struct timespec times[2], int set_owner, uint32_t uid, uint32_t gid, brix_status *st)
int brix_symlink (brix_conn *c, const char *target, const char *linkpath, brix_status *st)
int brix_link (brix_conn *c, const char *oldpath, const char *newpath, brix_status *st)
ssize_t brix_readlink (brix_conn *c, const char *path, char *out, size_t outsz, brix_status *st)
int brix_fattr_get (brix_conn *c, const char *path, const char *name, void *value, size_t bufsz, size_t *out_vlen, brix_status *st)
int brix_fattr_set (brix_conn *c, const char *path, const char *name, const void *value, size_t vlen, int create_only, brix_status *st)
int brix_fattr_del (brix_conn *c, const char *path, const char *name, brix_status *st)
int brix_fattr_list (brix_conn *c, const char *path, char *out, size_t bufsz, size_t *out_len, brix_status *st)
int brix_query (brix_conn *c, int infotype, const char *args, char *out, size_t outsz, brix_status *st)
int brix_statvfs (brix_conn *c, const char *path, char *out, size_t outsz, brix_status *st)
int brix_locate (brix_conn *c, const char *path, char *out, size_t outsz, brix_status *st)
int brix_prepare (brix_conn *c, const char *const *paths, int npaths, int options, int optionX, int prty, char *out, size_t outsz, brix_status *st)
int brix_proxy_create (const brix_proxy_opts *o, brix_status *st)
int brix_proxy_info (const char *path, FILE *out, brix_status *st)
int brix_proxy_destroy (const char *path, brix_status *st)
void brix_proxy_default_path (char *out, size_t outsz)
int brix_proxy_remaining (const char *path, long *secs_left)
int brix_copy_filter_match (const brix_copy_opts *o, const char *rel)
int brix_sync_should_skip (int cmp, long long ssz, long long smt, long long dsz, long long dmt)
int brix_copy (const char *src, const char *dst, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
void brix_copy_install_signal_handlers (void)
int brix_copy_quit_requested (void)
Macro Definition Documentation
BRIX_RMTREE_DRYRUN
#define BRIX_RMTREE_DRYRUN 0x1
Definition at line 365 of file brix_ops.h.
XRDC_CKV_HEX_MAX
#define XRDC_CKV_HEX_MAX 129
Definition at line 225 of file brix_ops.h.
XRDC_EXIT_AUTH
#define XRDC_EXIT_AUTH 53
Definition at line 266 of file brix_ops.h.
XRDC_EXIT_IO
#define XRDC_EXIT_IO 51
Definition at line 265 of file brix_ops.h.
XRDC_EXIT_USAGE
#define XRDC_EXIT_USAGE 50
Definition at line 264 of file brix_ops.h.
XRDC_IO_URING_AUTO
#define XRDC_IO_URING_AUTO 0
Definition at line 515 of file brix_ops.h.
XRDC_IO_URING_OFF
#define XRDC_IO_URING_OFF 2
Definition at line 517 of file brix_ops.h.
XRDC_IO_URING_ON
#define XRDC_IO_URING_ON 1
Definition at line 516 of file brix_ops.h.
XRDC_SYNC_CKSUM
#define XRDC_SYNC_CKSUM 2 /* sizes match AND checksums match (caller does I/O) */
Definition at line 527 of file brix_ops.h.
XRDC_SYNC_MTIME
#define XRDC_SYNC_MTIME 1 /* sizes match AND dst mtime >= src mtime */
Definition at line 526 of file brix_ops.h.
XRDC_SYNC_SIZE
#define XRDC_SYNC_SIZE 0 /* skip when sizes match (legacy --sync) */
Definition at line 525 of file brix_ops.h.
XRDC_TPC_DELEGATE
#define XRDC_TPC_DELEGATE 3 /* TPC with credential delegation (tpc.token_mode) */
Definition at line 523 of file brix_ops.h.
XRDC_TPC_FIRST
#define XRDC_TPC_FIRST 1 /* try TPC, fall back to client-mediated on failure */
Definition at line 521 of file brix_ops.h.
XRDC_TPC_OFF
#define XRDC_TPC_OFF 0
Definition at line 520 of file brix_ops.h.
XRDC_TPC_ONLY
#define XRDC_TPC_ONLY 2 /* TPC or hard fail */
Definition at line 522 of file brix_ops.h.
XRDC_VEC_MAXBYTES
#define XRDC_VEC_MAXBYTES (256u << 20) /* aggregate readv/writev payload cap */
Definition at line 67 of file brix_ops.h.
XRDC_VEC_MAXSEGS
#define XRDC_VEC_MAXSEGS 1024
Definition at line 66 of file brix_ops.h.
Typedef Documentation
brix_op_fn
typedef int(* brix_op_fn) (brix_conn *c, void *arg, brix_status *st)
Definition at line 130 of file brix_ops.h.
brix_progress_cb
typedef void(* brix_progress_cb) (void *arg, long long done, long long total)
Definition at line 460 of file brix_ops.h.
brix_rmtree_report
typedef int(* brix_rmtree_report) (const char *path, int is_dir, void *u)
Definition at line 370 of file brix_ops.h.
brix_walk_fn
typedef int(* brix_walk_fn) (const char *path, const brix_dirent *e, int depth, void *u)
Definition at line 354 of file brix_ops.h.
Enumeration Type Documentation
brix_cksum_algo
enum brix_cksum_algo
Enumerator
XRDC_CK_ADLER32
XRDC_CK_CRC32C
XRDC_CK_MD5
XRDC_CK_CRC64
XRDC_CK_CRC64NVME
XRDC_CK_ZCRC32
Definition at line 204 of file brix_ops.h.
brix_ckv_mode
enum brix_ckv_mode
Enumerator
XRDC_CKV_AUTO
XRDC_CKV_CACHE
XRDC_CKV_STORAGE
Definition at line 228 of file brix_ops.h.
brix_ckv_result
enum brix_ckv_result
Enumerator
XRDC_CKV_OK
XRDC_CKV_MISMATCH
XRDC_CKV_NO_RECORD
XRDC_CKV_UNSUPPORTED
XRDC_CKV_ERROR
Definition at line 235 of file brix_ops.h.
brix_op_class
enum brix_op_class
Enumerator
XRDC_OP_READONLY
XRDC_OP_IDEMPOTENT
XRDC_OP_MUTATION_NORMALIZE
XRDC_OP_UNSAFE
Definition at line 120 of file brix_ops.h.
Function Documentation
brix_chmod()
int brix_chmod (brix_conn * c, const char * path, int mode, brix_status * st)
Definition at line 147 of file ops_fs.c.
References c, fs_simple(), kXR_chmod, xrdw_chmod_req_t::mode, ClientChmodRequest::requestid, XRDC_OP_IDEMPOTENT, and xrdw_chmod_req_pack().
Referenced by brix_fuse_op_chmod(), chmod_visit(), do_chmod(), and mb_create().
brix_ckmf_parse_line()
int brix_ckmf_parse_line (const char * line, char * hex, size_t hexsz, char * rel, size_t relsz)
Definition at line 39 of file cksum_manifest.c.
References brix_rel_is_unsafe(), and hex().
Referenced by ckcheck_process_line().
brix_cks_verify_file()
brix_ckv_result brix_cks_verify_file (const char * path, const char * want_algo, brix_ckv_mode mode, brix_ckv_report * rep, brix_status * st)
Definition at line 527 of file cks_verify.c.
References brix_status_set(), ckv_collect_records(), CKV_MAX_RECORDS, ckv_verify_one(), close(), open(), XRDC_CK_ZCRC32, XRDC_CKV_ERROR, XRDC_CKV_HEX_MAX, XRDC_CKV_NO_RECORD, XRDC_CKV_OK, XRDC_CKV_UNSUPPORTED, XRDC_ESOCK, and XRDC_EUSAGE.
Referenced by brix_xrdckverify_main().
brix_cksum_algo_parse()
int brix_cksum_algo_parse (const char * name, brix_cksum_algo * out)
Definition at line 29 of file checksum.c.
References name, XRDC_CK_ADLER32, XRDC_CK_CRC32C, XRDC_CK_CRC64, XRDC_CK_CRC64NVME, XRDC_CK_MD5, and XRDC_CK_ZCRC32.
Referenced by brix_xrdcktree_main(), ckcheck_parse_args(), cksum_parse_spec(), ckv_verify_one(), cmd_verify(), entry_cksum(), and sync_cksum_match().
brix_cksum_fd()
int brix_cksum_fd (int fd, brix_cksum_algo algo, char * hex, size_t hexsz, brix_status * st)
Definition at line 45 of file checksum.c.
References BRIX_CK_ADLER32, BRIX_CK_CRC32C, BRIX_CK_CRC64, BRIX_CK_CRC64NVME, BRIX_CK_MD5, BRIX_CK_ZCRC32, brix_cksum_digest_fd(), brix_cksum_u32_fd(), brix_cksum_u64_fd(), brix_hex_encode(), brix_status_set(), hex(), XRDC_CK_ADLER32, XRDC_CK_CRC64, XRDC_CK_CRC64NVME, XRDC_CK_MD5, XRDC_CK_ZCRC32, XRDC_ESOCK, and XRDC_EUSAGE.
Referenced by brix_cli_cksum_main(), chk_probe_checksum(), ckcheck_digest_local(), cksum_compute_local(), ckv_verify_one(), do_compare_davs(), dx_probe_checksum(), entry_cksum(), remote_md5(), sync_cksum_match(), tree_emit_file(), verify_compute_wire_hex(), and write_checksum().
brix_cli_cksum_main()
int brix_cli_cksum_main (const char * prog, const char * algo_name, brix_cksum_algo algo, const char * arg, int err_exit)
Definition at line 30 of file cli_cksum.c.
References brix_cksum_fd(), brix_client_version(), brix_close(), brix_connect(), brix_crypto_init(), brix_query_cksum(), brix_status_clear(), brix_url_parse(), BRIX_USAGE_FOOTER, c, close(), hex(), brix_status::msg, open(), brix_url::path, brix_url::scheme, XRDC_EXIT_USAGE, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by dispatch().
brix_cli_connect()
int brix_cli_connect (const char * endpoint, const brix_opts * o, brix_conn * c, const char * prog, brix_status * st)
Definition at line 25 of file cli_conn.c.
References brix_connect_resilient(), brix_endpoint_parse(), brix_shellcode(), brix_status_clear(), c, brix_status::msg, and XRDC_EXIT_USAGE.
Referenced by brix_qstats_main(), and xrdprep_run().
brix_cli_cred_store_build()
struct brix_cred_store * brix_cli_cred_store_build (const char * proxy, const char * bearer, const char * bearer_file, const char * s3_access, const char * s3_secret, const char * oidc_account, int auto_refresh)
Definition at line 63 of file cli_cred.c.
References brix_cred_config::auto_refresh, brix_cred_config::bearer_literal, brix_cred_config::bearer_path, brix_cred_store_new(), brix_cred_store::cfg, brix_cred_config::oidc_account, brix_cred_config::proxy_path, brix_cred_config::s3_access, and brix_cred_config::s3_secret.
Referenced by build_and_preflight_credentials().
brix_cli_parse_io_uring()
int brix_cli_parse_io_uring (const char * s)
Definition at line 217 of file cli_opts.c.
References s, XRDC_IO_URING_AUTO, XRDC_IO_URING_OFF, and XRDC_IO_URING_ON.
Referenced by xfer_common_arg(), and xrdcp_parse_transport_option().
brix_connect_resilient()
int brix_connect_resilient (brix_conn * c, const brix_url * u, const brix_opts * o, brix_status * st)
Definition at line 70 of file resilient.c.
References brix_backoff_sleep_fast(), brix_connect(), brix_mono_ns(), brix_status_retryable(), c, brix_status::kxr, opts_window_ms(), brix_status::sys_errno, and XRDC_ESOCK.
Referenced by brix_cli_connect(), do_map(), main(), run_root_endpoint(), and upload_stream_body().
brix_copy()
int brix_copy (const char * src, const char * dst, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 433 of file copy.c.
References brix_copy_classify(), brix_copy_route(), brix_is_block_url(), brix_is_web_url(), copy_block(), copy_web(), brix_opts::no_retry, and brix_opts::verify_host.
Referenced by copy_one_with_retry(), and do_bench().
brix_copy_filter_match()
int brix_copy_filter_match (const brix_copy_opts * o, const char * rel)
Definition at line 20 of file copy_filter.c.
References brix_copy_opts::excludes, brix_copy_opts::includes, brix_copy_opts::n_excludes, brix_copy_opts::n_includes, and rel_basename().
Referenced by mirror_delete_local(), mirror_delete_remote(), recursive_place(), transfer_filter_check(), tree_dl_file(), tree_ul_file(), and walk_handle_file().
brix_copy_install_signal_handlers()
void brix_copy_install_signal_handlers (void)
Definition at line 37 of file copy.c.
References copy_signal_handler().
Referenced by main().
brix_copy_quit_requested()
int brix_copy_quit_requested (void)
Definition at line 30 of file copy.c.
References g_brix_copy_quit.
Referenced by brix_tls_read(), brix_tls_write(), csctx_retry_gate(), plain_read_full(), plain_write_full(), pump_sink_remote(), pump_src_remote(), resilient_setup(), sleep_ms_cancelable(), upload_close_commit_resilient(), and wait_io().
brix_cred_store_free()
void brix_cred_store_free (struct brix_cred_store * s)
Definition at line 303 of file cred.c.
References cfg_copy_free(), s, slot_clear_owned(), and XRDC_CRED_KIND_COUNT.
Referenced by main().
brix_credfile_bio()
struct bio_st * brix_credfile_bio (const char * path, int secret)
Definition at line 50 of file proxy.c.
References brix_open_credfile(), and close().
Referenced by brix_gsi_cert_explain(), brix_proxy_info(), and brix_proxy_remaining().
brix_deflate_frame()
uint8_t * brix_deflate_frame (uint8_t codec, const void * in, size_t in_len, size_t * out_len, brix_status * st)
Definition at line 178 of file ops_file_rw.c.
References brix_codec_close(), BRIX_CODEC_DIR_COMPRESS, BRIX_CODEC_END, BRIX_CODEC_OK, brix_codec_open(), brix_codec_step(), brix_status_set(), s, and XRDC_EPROTO.
Referenced by brix_file_write(), and brix_mfile_pwrite().
brix_dirlist()
int brix_dirlist (brix_conn * c, const char * path, int want_stat, brix_dirent ** ents, size_t * count, brix_status * st)
Definition at line 380 of file ops_meta.c.
References brix_resilient_window_ms(), brix_with_resilience(), c, dirlist_args::count_out, dirlist_op(), dirlist_args::ents_out, dirlist_args::path, dirlist_args::want_stat, and XRDC_OP_READONLY.
Referenced by brix_fuse_op_dirlist(), brix_glob(), chk_probe_dirlist(), compare_dirs(), copy_tree_download(), dx_probe_namespace(), ls_json_dir(), ls_print_dir(), mirror_delete_remote(), probe_root_read_suite(), resolve_target(), rmtree_depth(), tree_recurse(), tree_walk_depth(), and walk_dir().
brix_ext_probe()
int brix_ext_probe (brix_conn * c, int * has_setattr, int * has_symlink, int * has_readlink, int * has_link, brix_status * st)
Definition at line 188 of file ops_ext.c.
References brix_query(), c, and kXR_Qconfig.
Referenced by aio_probe_ext(), and battery_root().
brix_fattr_del()
int brix_fattr_del (brix_conn * c, const char * path, const char * name, brix_status * st)
Definition at line 200 of file fattr.c.
References c, fattr_set_or_del(), kXR_fattrDel, and name.
Referenced by op_fadel(), write_xattr_ops(), xattr_rm(), and xfs_removexattr().
brix_fattr_get()
int brix_fattr_get (brix_conn * c, const char * path, const char * name, void * value, size_t bufsz, size_t * out_vlen, brix_status * st)
Definition at line 86 of file fattr.c.
References brix_roundtrip(), brix_status_set(), c, fattr_build_payload(), fattr_parse_status(), kXR_fattr, kXR_fattrGet, name, ClientFattrRequest::requestid, xrdw_fattr_req_t::subcode, XRDC_EPROTO, XRDC_ESOCK, and xrdw_fattr_req_pack().
Referenced by op_faget(), write_xattr_ops(), xattr_get(), and xfs_getxattr().
brix_fattr_list()
int brix_fattr_list (brix_conn * c, const char * path, char * out, size_t bufsz, size_t * out_len, brix_status * st)
Definition at line 206 of file fattr.c.
References brix_roundtrip(), brix_status_set(), c, kXR_fattr, kXR_fattrList, ClientFattrRequest::requestid, xrdw_fattr_req_t::subcode, XRDC_ESOCK, and xrdw_fattr_req_pack().
Referenced by op_falist(), xattr_ls(), and xfs_listxattr().
brix_fattr_set()
int brix_fattr_set (brix_conn * c, const char * path, const char * name, const void * value, size_t vlen, int create_only, brix_status * st)
Definition at line 192 of file fattr.c.
References c, fattr_set_or_del(), kXR_fa_isNew, kXR_fattrSet, and name.
Referenced by op_faset(), write_xattr_ops(), xattr_set(), and xfs_setxattr().
brix_file_close()
int brix_file_close (brix_conn * c, brix_file * f, brix_status * st)
Definition at line 33 of file ops_file.c.
References brix_recv(), brix_send(), c, xrdw_close_req_t::fhandle, brix_file::fhandle, kXR_close, ClientCloseRequest::requestid, XRD_FHANDLE_LEN, and xrdw_close_req_pack().
Referenced by bench_run(), bench_sweep(), brix_rfile_close(), chk_probe_handle_limits(), chk_probe_pgread(), copy_one_l2r(), copy_one_r2l(), copy_unzip(), copy_zip_store_remote(), do_readv(), do_writev(), doctor_xfer(), download_stream_body(), download_to_fd(), dx_authz_anon(), dx_probe_read(), dx_probe_write(), main(), mb_create(), probe_write_suite(), r2r_teardown(), touch_ensure_file(), tpc_teardown(), upload_close_commit_resilient(), verify_download_tmp(), watch_probe_once(), write_readv(), write_verify(), and xrd_clockskew_root().
brix_file_open_opaque()
int brix_file_open_opaque (brix_conn * c, const char * path, const char * opaque, int write, int force, int posc, brix_file * f, brix_status * st)
Definition at line 132 of file ops_file.c.
References brix_open_apply_inline_codec(), brix_open_options_build(), brix_roundtrip(), brix_status_set(), c, brix_file::fhandle, kXR_open, kXR_waitresp, xrdw_open_req_t::mode, brix_file::read_codec, ClientOpenRequest::requestid, brix_file::write_codec, XRD_FHANDLE_LEN, XRDC_EPROTO, and xrdw_open_req_pack().
Referenced by brix_file_open_read(), brix_file_open_update(), brix_file_open_write(), download_open_resilient(), pump_remote_reopen(), rfile_do_open(), tpc_run_rendezvous(), and upload_open_resilient().
brix_file_open_read()
int brix_file_open_read (brix_conn * c, const char * path, brix_file * f, brix_status * st)
Definition at line 8 of file ops_file.c.
References brix_file_open_opaque(), and c.
Referenced by bench_run(), bench_sweep(), chk_probe_handle_limits(), chk_probe_pgread(), copy_one_r2l(), copy_remote_to_remote(), copy_unzip(), do_readv(), doctor_xfer(), download_open_resilient(), download_to_fd(), dx_authz_anon(), dx_probe_read(), dx_probe_write(), main(), probe_write_suite(), pump_remote_reopen(), rfile_do_open(), verify_download_tmp(), watch_probe_once(), and write_readv().
brix_file_open_update()
int brix_file_open_update (brix_conn * c, const char * path, int posc, brix_file * f, brix_status * st)
Definition at line 23 of file ops_file.c.
References brix_file_open_opaque(), and c.
Referenced by copy_zip_store_remote(), pump_sink_reopen(), and rfile_do_open().
brix_file_open_write()
int brix_file_open_write (brix_conn * c, const char * path, int force, int posc, brix_file * f, brix_status * st)
Definition at line 15 of file ops_file.c.
References brix_file_open_opaque(), and c.
Referenced by brix_rfile_open_write(), chk_probe_posc(), copy_one_l2r(), copy_remote_to_remote(), copy_zip_store_remote(), do_writev(), dx_probe_write(), mb_create(), touch_ensure_file(), upload_open_resilient(), write_verify(), and xrd_clockskew_root().
brix_file_pgread()
ssize_t brix_file_pgread (brix_conn * c, brix_file * f, int64_t offset, void * buf, size_t len, brix_status * st)
Definition at line 186 of file ops_file_pg.c.
References brix_io_stall_arm(), brix_io_stall_disarm(), c, and file_pgread_frames().
Referenced by brix_rfile_pread(), chk_probe_pgread(), and pump_src_remote().
brix_file_pgwrite()
int brix_file_pgwrite (brix_conn * c, brix_file * f, int64_t offset, const void * buf, size_t len, brix_status * st)
Definition at line 364 of file ops_file_pg.c.
References brix_send(), brix_status_set(), c, xrdw_pgwrite_req_t::fhandle, brix_file::fhandle, kXR_pgPageSZ, kXR_pgwrite, xrdw_pgwrite_req_t::offset, pgwrite_handle_cse(), read_status_frame(), ClientPgWriteRequest::requestid, XRD_FHANDLE_LEN, XRDC_EPROTO, xrdp_pg_encode(), and xrdw_pgwrite_req_pack().
Referenced by brix_rfile_pwrite(), and pump_sink_remote().
brix_file_read()
ssize_t brix_file_read (brix_conn * c, brix_file * f, int64_t offset, void * buf, size_t len, brix_status * st)
Definition at line 161 of file ops_file_rw.c.
References brix_io_stall_arm(), brix_io_stall_disarm(), c, and file_read_frames().
Referenced by bench_run(), bench_sweep(), brix_rfile_pread(), doctor_xfer(), download_to_fd(), dx_probe_read(), dx_probe_write(), probe_write_suite(), pump_src_remote(), verify_download_tmp(), watch_probe_once(), and zip_remote_pread().
brix_file_readv()
ssize_t brix_file_readv (brix_conn * c, brix_file * f, brix_readv_seg * segs, size_t nseg, brix_status * st)
Definition at line 463 of file ops_file_rw.c.
References brix_io_stall_arm(), brix_io_stall_disarm(), c, and file_readv_frames().
Referenced by do_readv(), main(), and write_readv().
brix_file_sync()
int brix_file_sync (brix_conn * c, brix_file * f, brix_status * st)
Definition at line 216 of file ops_file.c.
References brix_recv(), brix_send(), c, xrdw_sync_req_t::fhandle, brix_file::fhandle, kXR_sync, ClientSyncRequest::requestid, XRD_FHANDLE_LEN, and xrdw_sync_req_pack().
Referenced by copy_tpc(), tpc_run_rendezvous(), and xfs_fsync().
brix_file_write()
int brix_file_write (brix_conn * c, brix_file * f, int64_t offset, const void * buf, size_t len, brix_status * st)
Definition at line 239 of file ops_file_rw.c.
References brix_deflate_frame(), brix_recv(), brix_send(), c, xrdw_write_req_t::fhandle, brix_file::fhandle, kXR_write, xrdw_write_req_t::offset, ClientWriteRequest::requestid, brix_file::write_codec, XRD_FHANDLE_LEN, and xrdw_write_req_pack().
Referenced by brix_rfile_pwrite(), chk_probe_posc(), dx_probe_write(), pump_sink_remote(), write_verify(), and zipw_remote_write().
brix_file_writev()
int brix_file_writev (brix_conn * c, brix_file * f, const brix_writev_seg * segs, size_t nseg, int do_sync, brix_status * st)
Definition at line 485 of file ops_file_rw.c.
References brix_recv(), brix_send_ext(), brix_status_set(), c, brix_file::fhandle, kXR_writev, kXR_wv_doSync, brix_writev_seg::len, xrdw_writev_req_t::options, ClientWriteVRequest::requestid, XRD_FHANDLE_LEN, XRDC_EPROTO, XRDC_EUSAGE, XRDC_VEC_MAXBYTES, XRDC_VEC_MAXSEGS, and xrdw_writev_req_pack().
Referenced by do_writev().
brix_fmt_size()
void brix_fmt_size (int64_t n, char * out, size_t sz, int human)
Definition at line 17 of file units.c.
Referenced by fmt_size().
brix_inflate_frame()
ssize_t brix_inflate_frame (uint8_t codec, const uint8_t * comp, size_t comp_len, void * out, size_t out_cap, brix_status * st)
Definition at line 16 of file ops_file_rw.c.
References brix_codec_close(), BRIX_CODEC_DIR_DECOMPRESS, BRIX_CODEC_END, BRIX_CODEC_OK, brix_codec_open(), brix_codec_step(), brix_status_set(), brix_codec_guard_t::max_ratio, brix_codec_guard_t::out_cap, s, and XRDC_EPROTO.
Referenced by brix_mfile_pread(), and file_read_frames().
brix_link()
int brix_link (brix_conn * c, const char * oldpath, const char * newpath, brix_status * st)
Definition at line 125 of file ops_ext.c.
References xrdw_twopath_req_t::arg1len, brix_status_set(), c, ext_simple(), kXR_link, ClientLinkRequest::requestid, XRDC_EPROTO, XRDC_EUSAGE, and xrdw_twopath_req_pack().
Referenced by brix_fuse_op_link(), and do_ln().
brix_locate()
int brix_locate (brix_conn * c, const char * path, char * out, size_t outsz, brix_status * st)
Definition at line 206 of file ops_fs.c.
References c, fs_text(), kXR_locate, xrdw_locate_req_t::options, ClientLocateRequest::requestid, and xrdw_locate_req_pack().
Referenced by do_locate(), do_map(), doctor_cms(), doctor_diagnose(), topo_probe_locate(), and watch_probe_once().
brix_lstat()
int brix_lstat (brix_conn * c, const char * path, brix_statinfo * out, brix_status * st)
Definition at line 93 of file ops_meta.c.
References c, kXR_statNoFollow, and stat_opt().
Referenced by brix_fuse_op_lstat(), and rmtree_handle_dir_entry().
brix_mkdir()
int brix_mkdir (brix_conn * c, const char * path, int mode, int parents, brix_status * st)
Definition at line 71 of file ops_fs.c.
References c, fs_simple(), kXR_mkdir, kXR_mkdirpath, xrdw_mkdir_req_t::options, ClientMkdirRequest::requestid, XRDC_OP_MUTATION_NORMALIZE, and xrdw_mkdir_req_pack().
Referenced by brix_fuse_op_mkdir(), copy_tree_upload(), do_mkdir(), dx_authz_scope(), dx_probe_write(), mb_create(), and probe_write_suite().
brix_mv()
int brix_mv (brix_conn * c, const char * src, const char * dst, brix_status * st)
Definition at line 110 of file ops_fs.c.
References xrdw_twopath_req_t::arg1len, brix_status_set(), c, fs_simple(), kXR_mv, ClientMvRequest::requestid, XRDC_EPROTO, XRDC_EUSAGE, XRDC_OP_MUTATION_NORMALIZE, and xrdw_twopath_req_pack().
Referenced by brix_fuse_op_mv(), do_mv(), and write_rename_truncate_rm().
brix_open_credfile()
int brix_open_credfile (const char * path, int secret, brix_status * st)
Definition at line 76 of file path.c.
References brix_status_set(), close(), fstat(), open(), stat(), and XRDC_EAUTH.
Referenced by brix_credfile_bio(), slurp(), and slurp_credfile().
brix_opts_init()
void brix_opts_init (brix_opts * o)
Definition at line 46 of file cli_opts.c.
References brix_opts::max_stall_ms, brix_opts::no_retry, and brix_opts::verify_host.
Referenced by main().
brix_opts_parse_arg()
int brix_opts_parse_arg (brix_opts * o, int argc, char ** argv, int * i)
Definition at line 179 of file cli_opts.c.
References opts_parse_toggle(), opts_parse_universal(), and opts_parse_valued().
Referenced by dx_parse_argv(), main(), and xrdcp_parse_option().
brix_parse_bytes()
int64_t brix_parse_bytes (const char * s)
Definition at line 62 of file units.c.
References brix_bytes_suffix_multiplier(), and s.
Referenced by parse_bytes(), and parse_list().
brix_path_resolve()
void brix_path_resolve (const char * cwd, const char * arg, char * out, size_t outsz)
Definition at line 19 of file path.c.
References tok, and XRDC_PATH_MAX.
Referenced by build_path().
brix_prepare()
int brix_prepare (brix_conn * c, const char *const * paths, int npaths, int options, int optionX, int prty, char * out, size_t outsz, brix_status * st)
Definition at line 220 of file ops_fs.c.
References brix_status_set(), c, fs_text(), kXR_prepare, kXR_stage, xrdw_prepare_req_t::options, port, ClientPrepareRequest::requestid, XRDC_EPROTO, XRDC_EUSAGE, and xrdw_prepare_req_pack().
Referenced by do_evict(), do_prepare(), do_stage(), dx_probe_stage(), and xrdprep_run().
brix_proxy_create()
int brix_proxy_create (const brix_proxy_opts * o, brix_status * st)
Definition at line 309 of file proxy.c.
References brix_proxy_opts::bits, brix_proxy_default_path(), c, default_cred(), proxy_build_ctx::fd, brix_proxy_opts::out_path, proxy_build_cleanup(), pxy_assemble_pem(), pxy_build_request(), pxy_load_issuer(), pxy_sign(), brix_proxy_opts::user_cert, brix_proxy_opts::user_key, and brix_proxy_opts::valid_hours.
Referenced by cmd_init(), and refresh_gsi_proxy().
brix_proxy_default_path()
void brix_proxy_default_path (char * out, size_t outsz)
Definition at line 72 of file proxy.c.
Referenced by brix_proxy_create(), brix_proxy_destroy(), brix_proxy_info(), brix_proxy_remaining(), diagnose_proxy(), doctor_discover_creds(), refresh_gsi_proxy(), and xrd_whoami().
brix_proxy_destroy()
int brix_proxy_destroy (const char * path, brix_status * st)
Definition at line 428 of file proxy.c.
References brix_proxy_default_path(), brix_status_set(), close(), open(), stat(), and XRDC_EUSAGE.
Referenced by cmd_destroy().
brix_proxy_info()
int brix_proxy_info (const char * path, FILE * out, brix_status * st)
Definition at line 340 of file proxy.c.
References brix_credfile_bio(), brix_proxy_default_path(), brix_status_set(), ssl_fail(), and XRDC_ENOENT.
Referenced by cmd_info(), and cmd_init().
brix_proxy_remaining()
int brix_proxy_remaining (const char * path, long * secs_left)
Definition at line 395 of file proxy.c.
References brix_credfile_bio(), and brix_proxy_default_path().
Referenced by diagnose_proxy(), and proxy_is_stale().
brix_query()
int brix_query (brix_conn * c, int infotype, const char * args, char * out, size_t outsz, brix_status * st)
Definition at line 177 of file ops_fs.c.
References c, fs_text(), xrdw_query_req_t::infotype, kXR_query, ClientQueryRequest::requestid, and xrdw_query_req_pack().
Referenced by brix_ext_probe(), brix_qstats_main(), do_df(), do_query(), op_qspace(), print_space(), probe_root_read_suite(), xfs_statfs(), and xrd_probe_caps().
brix_query_cksum()
int brix_query_cksum (brix_conn * c, const char * path, const char * algo_name, char * hex, size_t hexsz, brix_status * st)
Definition at line 103 of file checksum.c.
References brix_roundtrip_resilient(), brix_status_set(), c, hex(), xrdw_query_req_t::infotype, kXR_Qcksum, kXR_query, ClientQueryRequest::requestid, XRDC_EPROTO, XRDC_EUSAGE, XRDC_OP_READONLY, XRDC_PATH_MAX, and xrdw_query_req_pack().
brix_rate_pace()
void brix_rate_pace (const struct timespec * start, int64_t sent, double rate)
Definition at line 81 of file units.c.
Referenced by rate_pace().
brix_readlink()
ssize_t brix_readlink (brix_conn * c, const char * path, char * out, size_t outsz, brix_status * st)
Definition at line 160 of file ops_ext.c.
References brix_roundtrip(), c, kXR_readlink, ClientReadlinkRequest::requestid, and xrdw_empty_req_pack().
Referenced by do_readlink(), write_symlink_ops(), and xfs_readlink_one_attempt().
brix_reconnect_home()
int brix_reconnect_home (brix_conn * c, brix_status * st)
Definition at line 102 of file resilient.c.
References brix_reconnect(), c, host, and port.
Referenced by brix_rfile_open_read(), brix_rfile_open_write(), brix_roundtrip_resilient(), brix_with_resilience(), rfile_reopen(), and tail_follow().
brix_rel_is_unsafe()
int brix_rel_is_unsafe (const char * rel)
Definition at line 120 of file path.c.
Referenced by brix_ckmf_parse_line(), and rel_is_unsafe().
brix_report_err()
int brix_report_err (FILE * out, const char * tool, const char * op, const char * path, const brix_status * st, int want_write, const brix_url * url)
Definition at line 67 of file cli_conn.c.
References brix_cred_hint_for_status_url(), brix_hint_url_double_slash(), brix_shellcode(), brix_status::msg, op, and report_err_endpoint().
brix_resilient_window_ms()
int brix_resilient_window_ms (const brix_conn * c)
Definition at line 64 of file resilient.c.
References c, and opts_window_ms().
Referenced by brix_dirlist(), brix_roundtrip_resilient(), rfile_init(), and tail_follow().
brix_rfile_close()
int brix_rfile_close (brix_rfile * rf, brix_status * st)
Definition at line 370 of file resilient.c.
References brix_file_close(), brix_rfile::c, and brix_rfile::f.
Referenced by close(), do_dd(), do_download(), do_grep(), do_hexdump(), do_upload(), head_lines(), slurp_file(), stream_file(), tail_follow(), tail_follow_drain(), tail_start_for_lines(), wc_count_stream(), and xfs_release().
brix_rfile_open_read()
int brix_rfile_open_read (brix_conn * c, const char * path, const char * opaque, int pgrw, int max_stall_ms, brix_rfile * rf, brix_status * st)
Definition at line 261 of file resilient.c.
References brix_backoff_sleep_fast(), brix_mono_ns(), brix_reconnect_home(), brix_status_retryable(), brix_rfile::c, c, brix_rfile::max_stall_ms, brix_rfile::opaque, rfile_canceled(), rfile_do_open(), rfile_init(), and brix_rfile::writable.
Referenced by do_dd(), do_download(), do_grep(), do_hexdump(), head_lines(), remote_open(), slurp_file(), stream_file(), tail_follow(), tail_follow_drain(), tail_start_for_lines(), wc_count_stream(), and xfs_open().
brix_rfile_open_write()
int brix_rfile_open_write (brix_conn * c, const char * path, int force, int posc, int pgrw, int max_stall_ms, brix_rfile * rf, brix_status * st)
Definition at line 286 of file resilient.c.
References brix_backoff_sleep_fast(), brix_file_open_write(), brix_mono_ns(), brix_reconnect_home(), brix_status_retryable(), brix_rfile::c, c, brix_rfile::f, brix_rfile::max_stall_ms, brix_rfile::path, brix_rfile::posc, rfile_canceled(), rfile_init(), and brix_rfile::writable.
Referenced by do_upload(), xfs_create(), and xfs_open().
brix_rfile_pread()
ssize_t brix_rfile_pread (brix_rfile * rf, int64_t off, void * buf, size_t len, brix_status * st)
Definition at line 312 of file resilient.c.
References brix_backoff_sleep_fast(), brix_file_pgread(), brix_file_read(), brix_mono_ns(), brix_status_retryable(), brix_status_set(), brix_rfile::c, brix_rfile::cur_chunk, brix_rfile::f, brix_rfile::max_stall_ms, brix_rfile::pgrw, rfile_canceled(), rfile_reopen(), XRDC_EUSAGE, and XRDC_RFILE_FLOOR.
Referenced by do_dd(), do_grep(), download_copy_loop(), head_lines(), hexdump_stream(), pread(), read(), slurp_file(), stream_file(), tail_follow_drain(), tail_start_for_lines(), wc_count_stream(), and xfs_io_pread().
brix_rfile_pwrite()
int brix_rfile_pwrite (brix_rfile * rf, int64_t off, const void * buf, size_t len, brix_status * st)
Definition at line 343 of file resilient.c.
References brix_backoff_sleep_fast(), brix_file_pgwrite(), brix_file_write(), brix_mono_ns(), brix_status_retryable(), brix_status_set(), brix_rfile::c, brix_rfile::f, brix_rfile::max_stall_ms, brix_rfile::pgrw, rfile_canceled(), rfile_reopen(), and XRDC_EUSAGE.
Referenced by upload_copy_loop(), and xfs_io_pwrite().
brix_rm()
int brix_rm (brix_conn * c, const char * path, brix_status * st)
Definition at line 87 of file ops_fs.c.
References c, fs_simple(), kXR_rm, ClientRmRequest::requestid, XRDC_OP_MUTATION_NORMALIZE, and xrdw_empty_req_pack().
Referenced by brix_fuse_op_rm(), chk_probe_posc(), do_ln(), do_rm(), dx_probe_write(), mb_remove(), mirror_remote_remove(), remove_source_entry(), rmtree_remove_leaf(), tree_dl_file(), write_rename_truncate_rm(), write_symlink_ops(), and xrd_clockskew_root().
brix_rmdir()
int brix_rmdir (brix_conn * c, const char * path, brix_status * st)
Definition at line 99 of file ops_fs.c.
References c, fs_simple(), kXR_rmdir, ClientRmdirRequest::requestid, XRDC_OP_MUTATION_NORMALIZE, and xrdw_empty_req_pack().
Referenced by brix_fuse_op_rmdir(), copy_recursive(), do_rmdir(), dx_authz_scope(), dx_probe_write(), mb_remove(), rmtree_depth(), tree_dl_entry(), and write_rename_truncate_rm().
brix_rmtree()
int brix_rmtree (brix_conn * c, const char * path, unsigned flags, brix_rmtree_report report, void * u, brix_status * st)
Definition at line 214 of file rmtree.c.
References brix_status_set(), c, report(), rmtree_depth(), and XRDC_EUSAGE.
Referenced by do_rm(), and mirror_remote_remove().
brix_roundtrip_resilient()
int brix_roundtrip_resilient (brix_conn * c, void * hdr24, const void * payload, uint32_t plen, brix_op_class cls, int benign_errno, uint16_t * status, uint8_t ** body, uint32_t * blen, brix_status * st)
Definition at line 164 of file resilient.c.
References brix_backoff_sleep_fast(), brix_kxr_to_errno(), brix_mono_ns(), brix_reconnect_home(), brix_resilient_window_ms(), brix_roundtrip(), brix_status_clear(), brix_status_retryable(), c, cls(), XRDC_OP_MUTATION_NORMALIZE, and XRDC_OP_UNSAFE.
Referenced by brix_query_cksum(), fs_simple(), fs_text(), and stat_opt().
brix_setattr()
int brix_setattr (brix_conn * c, const char * path, int set_times, const struct timespec times[2], int set_owner, uint32_t uid, uint32_t gid, brix_status * st)
Definition at line 44 of file ops_ext.c.
References xrdp_setattr_t::atime_nsec, xrdp_setattr_t::atime_sec, BRIX_SETATTR_PREFIX_LEN, brix_status_set(), c, ext_simple(), xrdp_setattr_t::flags, xrdp_setattr_t::gid, kXR_sa_owner, kXR_sa_times, kXR_setattr, xrdp_setattr_t::mtime_nsec, xrdp_setattr_t::mtime_sec, ClientSetattrRequest::requestid, xrdp_setattr_t::uid, XRDC_EPROTO, xrdp_setattr_prefix_pack(), and xrdw_empty_req_pack().
Referenced by brix_fuse_op_setattr(), do_touch(), and probe_write_suite().
brix_stat()
int brix_stat (brix_conn * c, const char * path, brix_statinfo * out, brix_status * st)
Definition at line 87 of file ops_meta.c.
References c, and stat_opt().
Referenced by brix_fuse_op_stat(), chk_probe_confinement(), chk_probe_dirlist(), chk_probe_handle_limits(), chk_probe_posc(), cmd_bench(), compare_probe(), copy_remote_to_remote(), copy_unzip(), copy_zip_store_remote(), dest_is_dir(), do_rm(), do_stat(), do_tail(), do_wc(), doctor_cms(), dx_authz_anon(), dx_probe_namespace(), dx_probe_read(), entry_meta(), main(), mb_create(), probe_holder(), probe_p1_path_escape(), probe_path_confinement(), probe_root_read_suite(), probe_server_survives(), remote_entry_is_dir(), remote_open(), remote_stat(), resilient_setup(), resolve_target(), slurp_file(), statx(), tail_follow(), topo_probe_redirect(), touch_ensure_file(), tpc_setup_source(), ul_sync_skip(), upload_close_commit_resilient(), wait_online(), xfs_access(), xrd_clockskew_root(), and xrd_ping().
brix_statvfs()
int brix_statvfs (brix_conn * c, const char * path, char * out, size_t outsz, brix_status * st)
Definition at line 192 of file ops_fs.c.
References c, fs_text(), kXR_stat, kXR_vfs, xrdw_stat_req_t::options, ClientStatRequest::requestid, and xrdw_stat_req_pack().
Referenced by do_statvfs(), and probe_root_read_suite().
brix_symlink()
int brix_symlink (brix_conn * c, const char * target, const char * linkpath, brix_status * st)
Definition at line 90 of file ops_ext.c.
References xrdw_twopath_req_t::arg1len, brix_status_set(), c, ext_simple(), kXR_symlink, ClientSymlinkRequest::requestid, XRDC_EPROTO, XRDC_EUSAGE, and xrdw_twopath_req_pack().
Referenced by brix_fuse_op_symlink(), do_ln(), and write_symlink_ops().
brix_sync_should_skip()
int brix_sync_should_skip (int cmp, long long ssz, long long smt, long long dsz, long long dmt)
Definition at line 46 of file copy_filter.c.
References XRDC_SYNC_MTIME.
Referenced by dl_sync_skip(), transfer_sync_check(), and ul_sync_skip().
brix_tree_walk()
int brix_tree_walk (brix_conn * c, const char * path, brix_walk_fn fn, void * u, brix_status * st)
Definition at line 71 of file walk.c.
References c, fn, and tree_walk_depth().
Referenced by cktree_run_remote().
brix_truncate()
int brix_truncate (brix_conn * c, const char * path, int64_t size, brix_status * st)
Definition at line 162 of file ops_fs.c.
References c, fs_simple(), kXR_truncate, xrdw_truncate_req_t::offset, ClientTruncateRequest::requestid, XRDC_OP_IDEMPOTENT, and xrdw_truncate_req_pack().
Referenced by brix_fuse_op_trunc(), do_truncate(), and write_rename_truncate_rm().
brix_with_resilience()
int brix_with_resilience (brix_conn * c, int max_stall_ms, brix_op_class cls, int benign_errno, brix_op_fn op, void * arg, brix_status * st)
Definition at line 111 of file resilient.c.
References brix_backoff_sleep_fast(), brix_kxr_to_errno(), brix_mono_ns(), brix_reconnect_home(), brix_status_clear(), brix_status_retryable(), c, cls(), op, XRDC_OP_MUTATION_NORMALIZE, and XRDC_OP_UNSAFE.
Referenced by brix_dirlist().