nginx-xrootd: client/lib/brix.h File Reference
brix.h File Reference
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <time.h>
#include <sys/types.h>
#include "protocols/root/protocol/protocol.h"
#include "protocols/root/protocol/codec/wire_codec.h"
#include "brix_net.h"
#include "brix_auth.h"
#include "brix_ops.h"
Data Structures
struct brix_status
struct brix_url
struct brix_weburl
Macros
#define XRDC_FHANDLE_LEN XRD_FHANDLE_LEN
#define XRDC_SESSION_ID_LEN BRIX_SESSION_ID_LEN
#define XRDC_MSG_MAX 512
#define XRDC_PATH_MAX 2048
#define XRDC_DLEN_MAX (64u * 1024u * 1024u) /* sanity cap on a response body */
#define XRDC_NAME_MAX 256
#define XRDC_ESOCK (-1) /* connect/socket/timeout failure */
#define XRDC_EPROTO (-2) /* malformed/unexpected server frame */
#define XRDC_EUSAGE (-3) /* CLI / argument error */
#define XRDC_EAUTH (-4) /* server demanded auth we don't (yet) speak */
#define XRDC_EINTEGRITY
#define XRDC_EUNSUPPORTED
#define XRDC_ERESOLVE
#define XRDC_EREDIRECT
#define XRDC_EIO (-9) /* local filesystem I/O error (open/read/write/rename/fstat/truncate/alloc) — permanent, NOT retryable */
#define XRDC_ENOENT (-10) /* object/path does not exist (HTTP 404 / ENOENT) — permanent, NOT retryable */
Enumerations
enum brix_scheme { XRDC_SCHEME_ROOT = 0 , XRDC_SCHEME_ROOTS , XRDC_SCHEME_LOCAL , XRDC_SCHEME_STDIO }
enum brix_web_proto {
XRDC_WEB_HTTP = 0 , XRDC_WEB_HTTPS , XRDC_WEB_DAV , XRDC_WEB_DAVS ,
XRDC_WEB_S3 , XRDC_WEB_S3S
}
Functions
int brix_is_web_url (const char *s)
int brix_is_block_url (const char *s)
int brix_weburl_parse (const char *s, brix_weburl *out)
Macro Definition Documentation
XRDC_DLEN_MAX
#define XRDC_DLEN_MAX (64u * 1024u * 1024u) /* sanity cap on a response body */
Definition at line 44 of file brix.h.
XRDC_EAUTH
#define XRDC_EAUTH (-4) /* server demanded auth we don't (yet) speak */
Definition at line 58 of file brix.h.
XRDC_EINTEGRITY
#define XRDC_EINTEGRITY
Value:
                             (-5)/* data corruption (CRC/checksum mismatch) — NOT
                             * retryable: a re-read yields the same bad bytes, so
                             * the resilient loop MUST fail fast, not spin. */
Definition at line 59 of file brix.h.
XRDC_EIO
#define XRDC_EIO (-9) /* local filesystem I/O error (open/read/write/rename/fstat/truncate/alloc) — permanent, NOT retryable */
Definition at line 63 of file brix.h.
XRDC_ENOENT
#define XRDC_ENOENT (-10) /* object/path does not exist (HTTP 404 / ENOENT) — permanent, NOT retryable */
Definition at line 64 of file brix.h.
XRDC_EPROTO
#define XRDC_EPROTO (-2) /* malformed/unexpected server frame */
Definition at line 56 of file brix.h.
XRDC_EREDIRECT
#define XRDC_EREDIRECT
Value:
                             (-8) /* redirect loop / budget exhausted (self-redirect,
                             * bounce to an already-tried target, too many hops)
                             * — NOT retryable: re-issuing the op just walks into
                             * the same loop, so the resilient wrapper must fail
                             * fast rather than chase it for the whole window. */
Definition at line 62 of file brix.h.
XRDC_ERESOLVE
#define XRDC_ERESOLVE
Value:
                             (-7)  /* permanent name-resolution failure (NXDOMAIN / no
                             * address) — NOT retryable: the name will not
                             * resolve on a retry, so the resilient loop must
                             * fail fast instead of burning its stall window.
                             * A *transient* resolver failure (EAI_AGAIN) keeps
                             * XRDC_ESOCK so it is still retried. */
Definition at line 61 of file brix.h.
XRDC_ESOCK
#define XRDC_ESOCK (-1) /* connect/socket/timeout failure */
Definition at line 55 of file brix.h.
XRDC_EUNSUPPORTED
#define XRDC_EUNSUPPORTED
Value:
                                (-6) /* valid protocol feature this client build lacks;
                                * fatal, because reconnecting cannot add support. */
Definition at line 60 of file brix.h.
XRDC_EUSAGE
#define XRDC_EUSAGE (-3) /* CLI / argument error */
Definition at line 57 of file brix.h.
XRDC_FHANDLE_LEN
#define XRDC_FHANDLE_LEN XRD_FHANDLE_LEN
Definition at line 32 of file brix.h.
XRDC_MSG_MAX
#define XRDC_MSG_MAX 512
Definition at line 42 of file brix.h.
XRDC_NAME_MAX
#define XRDC_NAME_MAX 256
Definition at line 45 of file brix.h.
XRDC_PATH_MAX
#define XRDC_PATH_MAX 2048
Definition at line 43 of file brix.h.
XRDC_SESSION_ID_LEN
#define XRDC_SESSION_ID_LEN BRIX_SESSION_ID_LEN
Definition at line 35 of file brix.h.
Enumeration Type Documentation
brix_scheme
enum brix_scheme
Enumerator
XRDC_SCHEME_ROOT
XRDC_SCHEME_ROOTS
XRDC_SCHEME_LOCAL
XRDC_SCHEME_STDIO
Definition at line 66 of file brix.h.
brix_web_proto
enum brix_web_proto
Enumerator
XRDC_WEB_HTTP
XRDC_WEB_HTTPS
XRDC_WEB_DAV
XRDC_WEB_DAVS
XRDC_WEB_S3
XRDC_WEB_S3S
Definition at line 85 of file brix.h.
Function Documentation
brix_is_block_url()
int brix_is_block_url (const char * s)
Definition at line 271 of file url.c.
References s.
Referenced by brix_copy(), and copy_block().
brix_is_web_url()
int brix_is_web_url (const char * s)
Definition at line 246 of file url.c.
References s, starts_with(), and WEB_SCHEMES.
Referenced by both_web(), brix_copy(), build_and_preflight_credentials(), copy_web(), dest_is_dir(), ensure_web_dst_base(), entry_cksum(), entry_meta(), expand_source(), main(), recursive_place(), uses_cred_auth(), vfs_url_to_scheme(), xrd_measure_clock_skew(), xrd_run_battery(), xrdcp_dispatch_recursive_web_download(), xrdcp_hint_failed_source(), xrdcp_try_recursive_web(), and xrootdfs_aio_main().
brix_weburl_parse()
int brix_weburl_parse (const char * s, brix_weburl * out)
Definition at line 395 of file url.c.
References web_scheme::defport, brix_weburl::is_s3, web_scheme::is_s3, brix_weburl::port, web_scheme::prefix, brix_weburl::proto, web_scheme::proto, s, brix_weburl::tls, web_scheme::tls, weburl_copy_path(), weburl_match_scheme(), weburl_parse_bracket_host(), and weburl_parse_plain_host().
Referenced by aio_web_mount(), copy_web(), ensure_web_dst_base(), place_to_web(), recursive_web_download(), recursive_web_upload(), run_web_endpoint(), s3_be_open(), s3_be_stat(), vfs_url_to_scheme(), xrd_clockskew_http(), and xrd_run_battery().