nginx-xrootd: client/apps/diag/brix_fault_oracle.c File Reference
brix_fault_oracle.c File Reference
#include "brix_fault_oracle.h"
#include <fcntl.h>
#include <signal.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>
Functions
void fp_oracle_enable (void)
int fp_oracle_enabled (void)
int fp_oracle_run (const char *cmd, int timeout_ms)
Variables
static int g_exec_enabled = 0
Function Documentation
fp_oracle_enable()
void fp_oracle_enable (void)
Definition at line 18 of file brix_fault_oracle.c.
References g_exec_enabled.
Referenced by fp_apply_core_opt().
fp_oracle_enabled()
int fp_oracle_enabled (void)
Definition at line 24 of file brix_fault_oracle.c.
References g_exec_enabled.
Referenced by cmd_set_oracle(), cmd_status_json(), and cmd_status_report().
fp_oracle_run()
int fp_oracle_run (const char * cmd, int timeout_ms)
Definition at line 30 of file brix_fault_oracle.c.
References close(), and g_exec_enabled.
Referenced by bisect_thread(), and recovery_thread().
Variable Documentation
g_exec_enabled
int g_exec_enabled = 0 static
Definition at line 15 of file brix_fault_oracle.c.
Referenced by fp_oracle_enable(), fp_oracle_enabled(), and fp_oracle_run().