nginx-xrootd: client/apps/diag/brix_fault_priv.h File Reference
brix_fault_priv.h File Reference
#include <stddef.h>
#include <sys/socket.h>
Functions
int fp_priv_enable (const char *iface, int listen_port, const int *target_ports, int nports, const char **err)
int fp_priv_enabled (void)
int fp_priv_command (char *args, char *reply, size_t rsz)
void fp_priv_usage (void *out)
void fp_priv_teardown (void)
Function Documentation
fp_priv_command()
int fp_priv_command (char * args, char * reply, size_t rsz)
Definition at line 623 of file brix_fault_priv.c.
References cmd_mtu(), cmd_netem(), cut_apply(), cut_clear(), g_iface, g_lock, g_mtu_saved, g_ne, g_nft_on, g_on, mtu_set(), NE_N, and netem_apply().
Referenced by apply_command().
fp_priv_enable()
int fp_priv_enable (const char * iface, int listen_port, const int * target_ports, int nports, const char ** err)
Definition at line 589 of file brix_fault_priv.c.
References g_iface, g_listen_port, g_lock, g_ntports, g_on, g_tports, and valid_iface().
Referenced by fp_arm_privileged().
fp_priv_enabled()
int fp_priv_enabled (void)
Definition at line 617 of file brix_fault_priv.c.
References g_on.
fp_priv_teardown()
void fp_priv_teardown (void)
Definition at line 685 of file brix_fault_priv.c.
References cut_clear(), g_iface, g_mtu_saved, g_ne, g_on, mtu_set(), NE_N, and netem_apply().
Referenced by fp_arm_privileged(), and fp_on_signal().
fp_priv_usage()
void fp_priv_usage (void * out)
Definition at line 704 of file brix_fault_priv.c.
Referenced by usage().