nginx-xrootd: client/lib/brix_net.h File Reference
brix_net.h File Reference
Data Structures
struct brix_io
struct brix_opts
struct brix_diag
struct brix_conn
struct brix_statinfo
struct brix_dirent
struct brix_cert_info
struct brix_http_resp
struct brix_alias_info
struct brix_netfacts
struct brix_payload
struct brix_payload_ext
struct brix_resp_out
struct brix_streamset
Macros
#define XRDC_DEFAULT_MAX_STALL_MS 30000
#define XRDC_NOP 64 /* per-opcode RTT table size; reqid-kXR_1stRequest indexes it */
#define XRDC_REDIR_MAX 16 /* max kXR_redirect hops before giving up (loop/SSRF guard) */
#define XRDC_HOSTPORT_MAX 288 /* "host:port" key: host[256] + ':' + port + NUL, padded */
#define XRDC_MAX_STREAMS 16
Typedefs
typedef ssize_t(* brix_http_body_src_fn) (void *ctx, uint8_t *buf, int64_t off, size_t cap, brix_status *st)
Functions
int brix_has_glob (const char *s)
int brix_tcp_connect (const char *host, int port, int timeout_ms, brix_status *st)
void brix_sock_tune (int fd)
int brix_read_full (brix_io *io, void *buf, size_t n, brix_status *st)
int brix_write_full (brix_io *io, const void *buf, size_t n, brix_status *st)
void brix_io_stall_arm (brix_io *io)
void brix_io_stall_disarm (brix_io *io)
int brix_netpref_family (void)
int brix_netpref_demoted (void)
void brix_netpref_demote_ipv6 (const char *host)
void brix_netpref_note_wire_error (int family)
void brix_netpref_undo_demote (const char *why)
void brix_netpref_disable (void)
int brix_tmo_connect_ms (void)
int brix_tmo_io_ms (void)
int brix_tmo_stall_ms (void)
void brix_tmo_set_connect_ms (int ms)
void brix_tmo_set_io_ms (int ms)
void brix_tmo_set_stall_ms (int ms)
unsigned brix_backoff_delay_ms (unsigned attempt, uint64_t *seed)
unsigned brix_backoff_delay_fast_ms (unsigned attempt, uint64_t *seed)
void brix_backoff_sleep (unsigned attempt)
void brix_backoff_sleep_fast (unsigned attempt)
int brix_tls_upgrade (brix_conn *c, int verify_peer, int verify_host, const char *ca_dir, brix_status *st)
void brix_tls_free (brix_conn *c)
const char * brix_resolve_ca_dir (const char *opt_ca_dir)
int brix_tls_read (brix_io *io, void *buf, size_t n, brix_status *st)
int brix_tls_write (brix_io *io, const void *buf, size_t n, brix_status *st)
int brix_tls_read_some (brix_io *io, void *buf, size_t n, size_t *got, brix_status *st)
int brix_tls_info (const brix_conn *c, const char **ver, const char **cipher)
int brix_tls_peer_cert_info (const brix_conn *c, brix_cert_info *out)
int brix_connect_no_login (brix_conn *c, const brix_url *u, const brix_opts *o, brix_status *st)
int brix_tls_client (brix_io *io, const char *host, int verify_peer, int verify_host, const char *ca_dir, void **out_ctx, brix_status *st)
void brix_tls_client_free (brix_io *io, void *ctx)
void brix_tls_client_info (const brix_io *io, const char **ver, const char **cipher)
int brix_http_req (const char *host, int port, int tls, const char *method, const char *path, const char *extra_headers, const void *body, size_t blen, int timeout_ms, int verify, const char *ca_dir, brix_http_resp *resp, brix_status *st)
void brix_http_resp_free (brix_http_resp *resp)
int brix_http_header (const brix_http_resp *resp, const char *name, char *out, size_t outsz)
int brix_http_download (const char *host, int port, int tls, const char *path, const char *extra_headers, int verify, const char *ca_dir, int out_fd, int timeout_ms, int *http_status, long long *body_len, brix_status *st)
int brix_http_upload (const char *host, int port, int tls, const char *path, const char *extra_headers, brix_http_body_src_fn src, void *src_ctx, long long clen, int verify, const char *ca_dir, int timeout_ms, int *http_status, brix_status *st)
int brix_http_upload_resumable (const char *host, int port, int tls, const char *path, const char *extra_headers, brix_http_body_src_fn src, void *src_ctx, long long clen, int verify, const char *ca_dir, int timeout_ms, int max_stall_ms, int *http_status, brix_status *st)
void brix_s3_sha256_hex (const void *data, size_t len, char *out)
int brix_s3_sign_v4 (const char *method, const char *host, const char *uri, const char *ak, const char *sk, const char *region, const char *payload_hex, char *hdrs, size_t hdrsz)
int brix_s3_sign_v4_q (const char *method, const char *host, const char *uri, const char *canon_qs, const char *ak, const char *sk, const char *region, const char *payload_hex, char *hdrs, size_t hdrsz)
int brix_url_parse (const char *s, brix_url *out, brix_status *st)
int brix_glob (const char *url, const brix_opts *co, char ***out, size_t *n_out, brix_status *st)
void brix_glob_free (char **arr, size_t n)
int brix_webdav_list (const brix_weburl *u, const char *bearer, int verify, const char *ca_dir, char ***paths, size_t *n_out, brix_status *st)
int brix_webdav_mkcol (const brix_weburl *u, const char *path, const char *bearer, int verify, const char *ca_dir, brix_status *st)
int brix_s3_list (const brix_weburl *u, const char *ak, const char *sk, const char *region, int verify, const char *ca_dir, char ***keys, size_t *n_out, brix_status *st)
void brix_strv_free (char **arr, size_t n)
int brix_web_stat (const brix_weburl *u, const char *path, const char *bearer, int verify, const char *ca_dir, brix_statinfo *si, brix_status *st)
int brix_web_readdir (const brix_weburl *u, const char *path, const char *bearer, int verify, const char *ca_dir, brix_dirent **ents, size_t *n, brix_status *st)
int brix_web_stat_pooled (struct brix_cpool *pool, const char *path, brix_statinfo *si, brix_status *st)
int brix_web_readdir_pooled (struct brix_cpool *pool, const char *path, brix_dirent **ents, size_t *n, brix_status *st)
brix_webfile * brix_webfile_open (const brix_weburl *u, const char *path, const char *bearer, int verify, const char *ca_dir, int timeout_ms, brix_statinfo *si_out, brix_status *st)
int64_t brix_webfile_size (const brix_webfile *wf)
ssize_t brix_webfile_pread (brix_webfile *wf, int64_t off, void *buf, size_t len, brix_status *st)
void brix_webfile_close (brix_webfile *wf, brix_status *st)
int brix_alias_resolve (const char *arg, char *out, size_t outsz)
int brix_alias_lookup (const char *name, brix_alias_info *info)
int brix_endpoint_parse (const char *ep, brix_url *out, brix_status *st)
int brix_xrdrc_default_ms (const char *key, int *out_ms)
void brix_status_clear (brix_status *st)
void brix_status_set (brix_status *st, int kxr, int sys_errno, const char *fmt,...)
const char * brix_kxr_name (int kxr)
int brix_shellcode (const brix_status *st)
int brix_status_retryable (const brix_status *st)
int brix_kxr_to_errno (const brix_status *st)
void brix_explain_conn (brix_conn *c, const brix_opts *opts, FILE *out)
void brix_netdiag_facts (const brix_conn *c, brix_netfacts *f)
void brix_netdiag_report (const brix_conn *c, FILE *out)
struct brix_capture * brix_capture_open (const char *path)
void brix_capture_meta (struct brix_capture *cap, const char *key, const char *val)
void brix_capture_frame (struct brix_capture *cap, int dir, uint16_t sid, int code, int is_request, const void *hdr, uint32_t hdrlen, const void *body, uint32_t blen)
void brix_capture_close (struct brix_capture *cap)
int brix_capture_replay (const char *path, int verbose, FILE *out, brix_status *st)
int brix_capture_playback (const char *path, const char *url, const brix_opts *co, FILE *out, brix_status *st)
int brix_http_get (const char *host, int port, const char *path, int timeout_ms, int *http_status, char *out, size_t outsz, size_t *outlen, brix_status *st)
const char * brix_reqid_name (int reqid)
const char * brix_status_name (int status)
uint64_t brix_mono_ns (void)
unsigned brix_jitter_ms (unsigned span_ms)
void brix_trace_frame (brix_conn *c, int dir, uint16_t sid, int code, int is_request, uint32_t dlen, const void *body, uint32_t blen)
void brix_timing_report (const brix_conn *c)
int brix_send (brix_conn *c, void *hdr24, const brix_payload *pl, uint16_t *out_sid, brix_status *st)
int brix_send_ext (brix_conn *c, void *hdr24, const brix_payload_ext *pl, uint16_t *out_sid, brix_status *st)
int brix_recv (brix_conn *c, uint16_t want_sid, brix_resp_out *out, brix_status *st)
int brix_roundtrip (brix_conn *c, void *hdr24, const brix_payload *pl, brix_resp_out *out, brix_status *st)
int brix_connect (brix_conn *c, const brix_url *u, const brix_opts *o, brix_status *st)
int brix_reconnect (brix_conn *c, const char *host, int port, brix_status *st)
void brix_close (brix_conn *c)
brix_pool * brix_pool_create (const brix_url *u, const brix_opts *o, int n, brix_status *st)
brix_conn * brix_pool_checkout (brix_pool *p, brix_status *st)
void brix_pool_checkin (brix_pool *p, brix_conn *c, int healthy)
void brix_pool_destroy (brix_pool *p)
int brix_bind (brix_conn *sec, const brix_conn *primary, brix_status *st)
int brix_streams_open (brix_streamset *ss, brix_conn *primary, int streams, brix_status *st)
void brix_streams_close (brix_streamset *ss)
Macro Definition Documentation
XRDC_DEFAULT_MAX_STALL_MS
#define XRDC_DEFAULT_MAX_STALL_MS 30000
Definition at line 79 of file brix_net.h.
XRDC_HOSTPORT_MAX
#define XRDC_HOSTPORT_MAX 288 /* "host:port" key: host[256] + ':' + port + NUL, padded */
Definition at line 102 of file brix_net.h.
XRDC_MAX_STREAMS
#define XRDC_MAX_STREAMS 16
Definition at line 658 of file brix_net.h.
XRDC_NOP
#define XRDC_NOP 64 /* per-opcode RTT table size; reqid-kXR_1stRequest indexes it */
Definition at line 86 of file brix_net.h.
XRDC_REDIR_MAX
#define XRDC_REDIR_MAX 16 /* max kXR_redirect hops before giving up (loop/SSRF guard) */
Definition at line 101 of file brix_net.h.
Typedef Documentation
brix_http_body_src_fn
typedef ssize_t(* brix_http_body_src_fn) (void *ctx, uint8_t *buf, int64_t off, size_t cap, brix_status *st)
Definition at line 342 of file brix_net.h.
Function Documentation
brix_alias_lookup()
int brix_alias_lookup (const char * name, brix_alias_info * info)
Definition at line 380 of file xrdrc.c.
References brix_alias_info::bearer, brix_alias_info::found, g_aliases, g_loaded, g_nalias, name, brix_alias_info::proxy, xrdrc_alias::proxy, read_first_line(), brix_alias_info::s3_access, xrdrc_alias::s3_access, brix_alias_info::s3_region, xrdrc_alias::s3_region, brix_alias_info::s3_secret, xrdrc_alias::s3_secret, xrdrc_alias::token, brix_alias_info::token_file, xrdrc_alias::token_file, brix_alias_info::token_file_failed, and xrdrc_load().
Referenced by merge_alias_auth().
brix_alias_resolve()
int brix_alias_resolve (const char * arg, char * out, size_t outsz)
Definition at line 309 of file xrdrc.c.
References g_aliases, g_loaded, g_nalias, name, xrdrc_alias::url, xrdrc_load(), and XRDRC_NAME_MAX.
Referenced by endpoint_to_url(), expand_source(), fs_find_endpoint(), map_fs_arg(), validate_and_finalize_args(), and xrd_mount_build_argv().
brix_backoff_delay_fast_ms()
unsigned brix_backoff_delay_fast_ms (unsigned attempt, uint64_t * seed)
Definition at line 191 of file nettmo.c.
References backoff_base_ms(), and s.
Referenced by brix_backoff_sleep_fast().
brix_backoff_delay_ms()
unsigned brix_backoff_delay_ms (unsigned attempt, uint64_t * seed)
Definition at line 128 of file nettmo.c.
References s.
Referenced by brix_backoff_sleep().
brix_backoff_sleep()
void brix_backoff_sleep (unsigned attempt)
Definition at line 232 of file nettmo.c.
References brix_backoff_delay_ms(), brix_mono_ns(), and sleep_ms_cancelable().
brix_backoff_sleep_fast()
void brix_backoff_sleep_fast (unsigned attempt)
Definition at line 242 of file nettmo.c.
References brix_backoff_delay_fast_ms(), brix_mono_ns(), and sleep_ms_cancelable().
Referenced by brix_connect_resilient(), brix_fuse_run(), brix_http_download(), brix_http_upload_resumable(), brix_mfile_pread(), brix_mfile_pwrite(), brix_rfile_open_read(), brix_rfile_open_write(), brix_rfile_pread(), brix_rfile_pwrite(), brix_roundtrip_resilient(), brix_webfile_pread(), brix_webmeta_propfind(), brix_with_resilience(), csctx_retry_gate(), pump_sink_remote(), pump_src_remote(), resilient_setup(), upload_close_commit_resilient(), and xfs_readlink().
brix_bind()
int brix_bind (brix_conn * sec, const brix_conn * primary, brix_status * st)
Definition at line 358 of file conn.c.
References brix_bringup_ex(), brix_recv(), brix_send(), BRIX_SESSION_ID_LEN, brix_tls_free(), close(), brix_io::fd, brix_conn::host, brix_conn::io, kXR_bind, brix_conn::opts, brix_conn::port, ClientBindRequest::requestid, xrdw_sessid_req_t::sessid, brix_conn::sessid, brix_io::stall_deadline_ms, brix_io::timeout_ms, brix_conn::tls_strict, brix_conn::want_tls, and xrdw_sessid_req_pack().
Referenced by brix_streams_open().
brix_capture_close()
void brix_capture_close (struct brix_capture * cap)
Definition at line 108 of file capture.c.
References brix_capture::fp.
Referenced by brix_close().
brix_capture_frame()
void brix_capture_frame (struct brix_capture * cap, int dir, uint16_t sid, int code, int is_request, const void * hdr, uint32_t hdrlen, const void * body, uint32_t blen)
Definition at line 86 of file capture.c.
References code, brix_capture::fp, put_u16(), and put_u32().
Referenced by brix_send_ext(), and recv_note_diag().
brix_capture_meta()
void brix_capture_meta (struct brix_capture * cap, const char * key, const char * val)
Definition at line 67 of file capture.c.
References brix_capture::fp, key, and put_u16().
Referenced by brix_connect().
brix_capture_open()
struct brix_capture * brix_capture_open (const char * path)
Definition at line 51 of file capture.c.
References brix_capture::fp, XRDCAP_MAGIC, and XRDCAP_MAGIC_LEN.
Referenced by brix_connect().
brix_capture_playback()
int brix_capture_playback (const char * path, const char * url, const brix_opts * co, FILE * out, brix_status * st)
Definition at line 430 of file capture.c.
References brix_close(), brix_connect(), brix_endpoint_parse(), brix_status_set(), c, playback_ctx::conn, brix_url::host, playback_ctx::issued, playback_ctx::ok, playback_ctx::out, playback_frame_record(), playback_skip_meta(), brix_url::port, read_magic(), XRDC_EPROTO, XRDC_EUSAGE, XRDCAP_REC_OK, and XRDCAP_REC_TRUNC.
Referenced by do_replay().
brix_capture_replay()
int brix_capture_replay (const char * path, int verbose, FILE * out, brix_status * st)
Definition at line 279 of file capture.c.
References brix_status_set(), brix_capture::fp, read_magic(), replay_frame_record(), replay_meta_record(), XRDC_EPROTO, XRDC_EUSAGE, XRDCAP_REC_OK, and XRDCAP_REC_TRUNC.
Referenced by do_replay().
brix_close()
void brix_close (brix_conn * c)
Definition at line 543 of file conn.c.
References brix_capture_close(), brix_send(), BRIX_SESSION_ID_LEN, brix_status_clear(), brix_timing_report(), brix_tls_free(), c, close(), kXR_endsess, xrdw_sessid_req_t::sessid, sessid_is_zero(), XRD_REQUEST_HDR_LEN, and xrdw_sessid_req_pack().
Referenced by battery_root(), bench_run(), brix_bringup_ex(), brix_capture_playback(), brix_cli_cksum_main(), brix_glob(), brix_qstats_main(), brix_wait41_main(), brix_xrdckcheck_main(), chk_probe_posc(), cktree_run_remote(), cmd_bench(), cmd_verify(), compare_setup(), copy_download(), copy_recursive(), copy_remote_to_block(), copy_unzip(), copy_zip_store_remote(), dest_is_dir(), do_bench(), do_check(), do_compare(), do_compare_davs(), do_map(), do_topology(), doctor_cms(), doctor_one(), dx_authz_anon(), dx_authz_expired(), dx_authz_forged(), dx_authz_scope(), entry_cksum(), entry_meta(), main(), mb_thread(), mgr_attach_eager(), mgr_connect_eager(), mgr_ensure_slot(), mgr_free(), pool_conn_close(), probe_holder(), probe_p1_path_escape(), probe_p2_bad_opcode(), probe_p3_oversized_dlen(), probe_p4_oob_read(), probe_p5_partial_frame(), probe_server_survives(), r2r_teardown(), remove_source_entry(), resilient_setup(), run_root_endpoint(), tpc_teardown(), upload_stream_body(), watch_probe_once(), xfs_handle_free(), xrd_caps(), xrd_certinfo(), xrd_clockskew_root(), xrd_doctor_probe(), xrd_ping(), xrd_whoami(), and xrdprep_run().
brix_connect()
int brix_connect (brix_conn * c, const brix_url * u, const brix_opts * o, brix_status * st)
Definition at line 422 of file conn.c.
References brix_bringup(), brix_capture_meta(), brix_capture_open(), brix_crypto_once(), brix_format_host_port(), BRIX_SESSION_ID_LEN, brix_status_set(), brix_tmo_io_ms(), c, brix_url::host, brix_url::port, brix_url::scheme, brix_url::single_slash_path, brix_opts::verify_host, XRDC_EUSAGE, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by battery_root(), bench_run(), brix_capture_playback(), brix_cli_cksum_main(), brix_connect_resilient(), brix_glob(), brix_wait41_main(), chk_probe_posc(), ckcheck_connect(), cktree_run_remote(), compare_setup(), copy_recursive(), copy_remote_to_remote(), copy_unzip(), copy_zip_store_remote(), dest_is_dir(), do_bench(), do_check(), do_compare_davs(), do_topology(), doctor_cms(), doctor_one(), dx_connect_as(), ensure_conn(), entry_cksum(), entry_meta(), main(), mb_thread(), mgr_connect_worker(), mgr_ensure_slot(), pool_conn_connect(), probe_holder(), probe_open(), remove_source_entry(), resilient_setup(), storascan_connect(), tpc_run_rendezvous(), tpc_setup_source(), watch_probe_once(), xfs_handle_new(), xrd_caps(), xrd_clockskew_root(), xrd_doctor_probe(), xrd_ping(), and xrd_whoami().
brix_connect_no_login()
int brix_connect_no_login (brix_conn * c, const brix_url * u, const brix_opts * o, brix_status * st)
Definition at line 484 of file conn.c.
References brix_bringup_ex(), brix_crypto_once(), brix_status_set(), brix_tmo_io_ms(), c, brix_url::host, brix_url::port, brix_url::scheme, brix_url::single_slash_path, brix_opts::verify_host, XRDC_EUSAGE, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by xrd_certinfo(), and xrd_doctor_probe().
brix_endpoint_parse()
int brix_endpoint_parse (const char * ep, brix_url * out, brix_status * st)
Definition at line 177 of file url.c.
References BRIX_DEFAULT_PORT_LOCAL, brix_status_set(), brix_url_parse(), brix_url::host, brix_url::port, brix_url::scheme, XRDC_EUSAGE, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by aio_root_mount(), brix_capture_playback(), brix_cli_connect(), brix_wait41_main(), compare_setup(), do_bench(), do_check(), do_compare_davs(), do_map(), do_metabench(), do_probe_robustness(), do_status(), do_topology(), doctor_one(), endpoint_to_url(), main(), parse_vmp(), probe_holder(), probe_open(), storascan_connect(), topo_report_cluster(), watch_probe_once(), xfs_root_mount(), xrd_caps(), xrd_certinfo(), xrd_clockskew_root(), xrd_doctor_probe(), xrd_ping(), xrd_run_battery(), and xrd_whoami().
brix_explain_conn()
void brix_explain_conn (brix_conn * c, const brix_opts * opts, FILE * out)
Definition at line 728 of file conn.c.
References brix_auth_explain(), c, explain_caps(), explain_env_credentials(), explain_roles(), explain_session_id(), and explain_tls().
Referenced by do_check(), do_explain(), and main().
brix_glob()
int brix_glob (const char * url, const brix_opts * co, char *** out, size_t * n_out, brix_status * st)
Definition at line 198 of file glob.c.
References glob_acc::arr, brix_close(), brix_connect(), brix_dirlist(), brix_glob_free(), brix_status_set(), brix_url_parse(), c, glob_spec::dir, glob_collect(), glob_parse_spec(), glob_acc::n, and XRDC_EPROTO.
Referenced by expand_source().
brix_glob_free()
void brix_glob_free (char ** arr, size_t n)
Definition at line 239 of file glob.c.
Referenced by brix_glob(), and expand_source().
brix_has_glob()
int brix_has_glob (const char * s)
Definition at line 24 of file glob.c.
References s.
Referenced by glob_parse_spec(), and source_has_glob().
brix_http_download()
int brix_http_download (const char * host, int port, int tls, const char * path, const char * extra_headers, int verify, const char * ca_dir, int out_fd, int timeout_ms, int * http_status, long long * body_len, brix_status * st)
Definition at line 336 of file http_download.c.
References brix_backoff_sleep_fast(), brix_mono_ns(), fstat(), host, http_download_attempt(), http_download_should_retry(), httpx_window_ms(), port, stat(), and tls.
Referenced by s3_get_verify(), web_dl_fetch(), and web_put_get_verify().
brix_http_get()
int brix_http_get (const char * host, int port, const char * path, int timeout_ms, int * http_status, char * out, size_t outsz, size_t * outlen, brix_status * st)
Definition at line 151 of file http.c.
References brix_status_set(), brix_tcp_connect(), c, close(), host, http_get_extract(), http_get_read_response(), http_get_send_request(), port, XRDC_EPROTO, XRDC_EUSAGE, and XRDC_HTTP_MAX.
Referenced by brix_mpxstats_main(), do_compare_davs(), do_status(), doctor_metrics(), and topo_report_cluster().
brix_http_header()
int brix_http_header (const brix_http_resp * resp, const char * name, char * out, size_t outsz)
Definition at line 249 of file http.c.
References brix_http_resp::headers, name, and raw_header().
Referenced by http_check_common_headers(), http_davs_extras(), s3t_resp_header(), scan_login(), web_read_suite(), and xrd_clockskew_http().
brix_http_req()
int brix_http_req (const char * host, int port, int tls, const char * method, const char * path, const char * extra_headers, const void * body, size_t blen, int timeout_ms, int verify, const char * ca_dir, brix_http_resp * resp, brix_status * st)
Definition at line 316 of file http_req.c.
References brix_http_resp_free(), brix_tls_client_free(), brix_tls_client_info(), c, close(), brix_io::fd, host, httpx_connect(), httpx_exchange(), port, brix_http_resp::tls, tls, brix_http_resp::tls_cipher, and brix_http_resp::tls_ver.
Referenced by brix_s3_list(), brix_web_readdir(), brix_web_stat(), brix_webdav_list(), brix_webdav_mkcol(), do_srr(), do_tape(), doctor_http(), doctor_s3(), http_davs_extras(), s3_delete(), s3_sigv4_probe(), s3t_request(), scan_fetch(), scan_login(), tape_poll_status(), web_move_delete(), web_read_suite(), web_write_suite(), and xrd_clockskew_http().
brix_http_resp_free()
void brix_http_resp_free (brix_http_resp * resp)
Definition at line 236 of file http.c.
References brix_http_resp::body.
Referenced by brix_http_req(), brix_s3_list(), brix_web_readdir(), brix_web_stat(), brix_webdav_list(), brix_webdav_mkcol(), cmd_scan(), do_srr(), do_tape(), doctor_http(), doctor_s3(), http_davs_extras(), s3_delete(), s3_sigv4_probe(), s3t_resp_free(), scan_fetch(), scan_login(), tape_poll_status(), web_move_delete(), web_read_suite(), web_write_suite(), and xrd_clockskew_http().
brix_http_upload()
int brix_http_upload (const char * host, int port, int tls, const char * path, const char * extra_headers, brix_http_body_src_fn src, void * src_ctx, long long clen, int verify, const char * ca_dir, int timeout_ms, int * http_status, brix_status * st)
Definition at line 449 of file http_upload.c.
References brix_tls_client_free(), c, close(), brix_io::fd, host, httpx_upload_ctx_t::host, httpx_connect(), httpx_exchange_core(), port, and tls.
Referenced by s3_put(), and web_put_get_verify().
brix_http_upload_resumable()
int brix_http_upload_resumable (const char * host, int port, int tls, const char * path, const char * extra_headers, brix_http_body_src_fn src, void * src_ctx, long long clen, int verify, const char * ca_dir, int timeout_ms, int max_stall_ms, int * http_status, brix_status * st)
Definition at line 388 of file http_upload.c.
References brix_backoff_sleep_fast(), brix_mono_ns(), brix_status_set(), c, host, httpx_upload_ctx_t::host, httpx_resumable_attempt(), httpx_resumable_may_retry(), httpx_chunk_range_t::off, port, tls, and XRDC_EPROTO.
Referenced by copy_web_upload().
brix_io_stall_arm()
void brix_io_stall_arm (brix_io * io)
Definition at line 440 of file sock.c.
References brix_mono_ns(), brix_io::stall_deadline_ms, and brix_io::stall_deadline_ns.
Referenced by brix_file_pgread(), brix_file_read(), and brix_file_readv().
brix_io_stall_disarm()
void brix_io_stall_disarm (brix_io * io)
Definition at line 452 of file sock.c.
References brix_io::stall_deadline_ns.
Referenced by brix_file_pgread(), brix_file_read(), and brix_file_readv().
brix_jitter_ms()
unsigned brix_jitter_ms (unsigned span_ms)
Definition at line 57 of file trace.c.
References brix_mono_ns().
Referenced by copy_one_with_retry(), and rt_handle_wait().
brix_kxr_name()
const char * brix_kxr_name (int kxr)
Definition at line 50 of file status.c.
References brix_kxr_error_name().
Referenced by aconn_dispatch_response(), brix_trace_error(), chk_probe_confinement(), chk_probe_handle_limits(), chk_probe_posc(), dx_record_status(), probe_holder(), probe_p1_path_escape(), read_status_frame(), set_kxr_error_status(), and topo_probe_redirect().
brix_kxr_to_errno()
int brix_kxr_to_errno (const brix_status * st)
Definition at line 114 of file status.c.
References brix_errno_from_kxr(), brix_status::kxr, brix_status::sys_errno, XRDC_EAUTH, XRDC_EINTEGRITY, XRDC_EPROTO, XRDC_ESOCK, XRDC_EUNSUPPORTED, and XRDC_EUSAGE.
Referenced by brix_fuse_errno(), brix_fuse_run(), brix_roundtrip_resilient(), brix_with_resilience(), pread(), read(), remote_open(), remote_stat(), and statx().
brix_mono_ns()
uint64_t brix_mono_ns (void)
Definition at line 41 of file trace.c.
Referenced by aconn_deadline_ns(), aconn_dispatch_frame(), aconn_issue_areq(), aconn_maybe_ping(), aconn_note_rtt(), aconn_on_transport_error(), aconn_reconnect_succeeded(), aconn_submit_cmd(), areq_note_deferral(), bench_one(), bench_run(), bench_sweep(), bench_workers_init(), bench_workers_run(), brix_aconn_attach(), brix_backoff_sleep(), brix_backoff_sleep_fast(), brix_bringup_ex(), brix_connect_resilient(), brix_fuse_run(), brix_http_download(), brix_http_upload_resumable(), brix_io_stall_arm(), brix_jitter_ms(), brix_rfile_open_read(), brix_rfile_open_write(), brix_rfile_pread(), brix_rfile_pwrite(), brix_roundtrip_resilient(), brix_send_ext(), brix_tls_read(), brix_webfile_pread(), brix_webmeta_propfind(), brix_with_resilience(), csctx_retry_gate(), do_bench(), doctor_xfer(), download_stream_body(), dx_authz_scope(), dx_probe_write(), fuse_run_done(), http_download_should_retry(), httpx_resumable_may_retry(), loop_process_timeouts(), mb_create(), mb_record(), mb_remove(), mb_run_workers(), now_ns(), plain_read_full(), pump_sink_remote(), pump_src_remote(), rc_worker_main(), read_wait_ms(), recv_note_diag(), resilient_setup(), tail_follow(), tls_read_wait_ms(), upload_close_commit_resilient(), upload_stream_body(), watch_probe_once(), xfs_readlink(), xrdcp_enable_progress_if_needed(), and xrdcp_progress().
brix_netdiag_facts()
void brix_netdiag_facts (const brix_conn * c, brix_netfacts * f)
Definition at line 34 of file netdiag.c.
References brix_netfacts::auth_ms, c, brix_netfacts::family, brix_netfacts::flow_label, brix_netfacts::have_tcpinfo, ms_between(), brix_netfacts::retrans, brix_netfacts::rtt_us, brix_netfacts::rttvar_us, brix_netfacts::tcp_ms, brix_netfacts::tls_ms, and brix_netfacts::total_ms.
Referenced by brix_netdiag_report(), doctor_one_session_facts(), and watch_probe_once().
brix_netdiag_report()
void brix_netdiag_report (const brix_conn * c, FILE * out)
Definition at line 82 of file netdiag.c.
References brix_netfacts::auth_ms, brix_netdiag_facts(), c, brix_netfacts::family, brix_netfacts::flow_label, brix_netfacts::have_tcpinfo, brix_netfacts::retrans, brix_netfacts::rtt_us, brix_netfacts::rttvar_us, brix_netfacts::tcp_ms, brix_netfacts::tls_ms, and brix_netfacts::total_ms.
Referenced by do_bench().
brix_netpref_demote_ipv6()
void brix_netpref_demote_ipv6 (const char * host)
Definition at line 105 of file netpref.c.
References do_demote(), fallback_enabled(), and host.
Referenced by connect_resolved().
brix_netpref_demoted()
int brix_netpref_demoted (void)
Definition at line 74 of file netpref.c.
References g_demoted.
brix_netpref_disable()
void brix_netpref_disable (void)
Definition at line 80 of file netpref.c.
References g_enabled.
brix_netpref_family()
int brix_netpref_family (void)
Definition at line 67 of file netpref.c.
References g_demoted.
Referenced by brix_tcp_connect(), and resolve_once().
brix_netpref_note_wire_error()
void brix_netpref_note_wire_error (int family)
Definition at line 117 of file netpref.c.
References do_demote(), fallback_enabled(), and g_demoted.
Referenced by note_io_failure().
brix_netpref_undo_demote()
void brix_netpref_undo_demote (const char * why)
Definition at line 134 of file netpref.c.
References g_demoted, and g_revert_logged.
Referenced by brix_tcp_connect().
brix_pool_checkin()
void brix_pool_checkin (brix_pool * p, brix_conn * c, int healthy)
Definition at line 80 of file pool.c.
References brix_cpool_checkin(), c, and brix_pool::cp.
Referenced by aio_probe_ext(), brix_fuse_run(), xfs_access(), xfs_getxattr(), xfs_listxattr(), xfs_readlink_one_attempt(), xfs_removexattr(), xfs_setxattr(), and xfs_statfs().
brix_pool_checkout()
brix_conn * brix_pool_checkout (brix_pool * p, brix_status * st)
Definition at line 70 of file pool.c.
References brix_cpool_checkout(), brix_status_set(), brix_pool::cp, and XRDC_EUSAGE.
Referenced by aio_probe_ext(), brix_fuse_run(), xfs_access(), xfs_getxattr(), xfs_listxattr(), xfs_readlink_one_attempt(), xfs_removexattr(), xfs_setxattr(), and xfs_statfs().
brix_pool_create()
brix_pool * brix_pool_create (const brix_url * u, const brix_opts * o, int n, brix_status * st)
Definition at line 44 of file pool.c.
References brix_cpool_create(), brix_status_set(), brix_pool::cp, brix_pool::ctx, pool_ctx::opts, POOL_VT, pool_ctx::url, XRDC_ESOCK, and XRDC_EUSAGE.
Referenced by aio_root_mount(), and xfs_root_mount().
brix_pool_destroy()
void brix_pool_destroy (brix_pool * p)
Definition at line 88 of file pool.c.
References brix_cpool_destroy(), and brix_pool::cp.
Referenced by aio_root_mount(), and xfs_root_mount().
brix_read_full()
int brix_read_full (brix_io * io, void * buf, size_t n, brix_status * st)
Definition at line 458 of file sock.c.
References brix_tls_read(), note_io_failure(), plain_read_full(), and brix_io::ssl.
Referenced by brix_kaconn_read_body(), file_pgread_frames(), frame_read_body(), frame_read_header(), pgwrite_handle_cse(), pgwrite_retry_one(), read_status_frame(), recv_raw(), and web_range_stream_body().
brix_reconnect()
int brix_reconnect (brix_conn * c, const char * host, int port, brix_status * st)
Definition at line 514 of file conn.c.
References brix_bringup(), brix_tls_free(), c, close(), host, and port.
Referenced by brix_reconnect_home(), csctx_reopen_home(), follow_redirect(), pump_remote_reopen(), pump_sink_reopen(), and rc_worker_main().
brix_recv()
int brix_recv (brix_conn * c, uint16_t want_sid, brix_resp_out * out, brix_status * st)
Definition at line 425 of file frame.c.
References brix_resp_out::blen, brix_resp_out::body, brix_status_set(), c, frame_read_body(), frame_read_header(), recv_dispatch(), recv_note_diag(), rx_frame_t::sid, XRD_RESPONSE_HDR_LEN, and XRDC_EPROTO.
Referenced by brix_bind(), brix_file_close(), brix_file_sync(), brix_file_write(), brix_file_writev(), brix_readv_accumulate(), dirlist_accumulate(), do_login(), file_read_frames(), playback_reissue_wire(), raw_send_expect_reject(), roundtrip_loop(), and run_module().
brix_reqid_name()
const char * brix_reqid_name (int reqid)
Definition at line 29 of file trace.c.
References brix_kxr_request_name().
Referenced by brix_timing_report(), brix_trace_frame(), playback_reissue_wire(), and replay_frame_record().
brix_resolve_ca_dir()
const char * brix_resolve_ca_dir (const char * opt_ca_dir)
Definition at line 53 of file conn.c.
References access(), and XRDC_GRID_CA_DIR.
Referenced by aio_web_mount(), battery_s3(), battery_web(), brix_bringup_ex(), and run_web_endpoint().
brix_roundtrip()
int brix_roundtrip (brix_conn * c, void * hdr24, const brix_payload * pl, brix_resp_out * out, brix_status * st)
Definition at line 765 of file frame.c.
References c, rt_req_t::cur_len, rt_req_t::cur_pl, brix_payload::data, brix_payload::len, rt_req_t::orig_len, rt_req_t::orig_pl, rt_req_t::rebuilt, rt_req_t::reqid, roundtrip_loop(), and xrd_get_u16_be().
Referenced by brix_fattr_get(), brix_fattr_list(), brix_file_open_opaque(), brix_readlink(), brix_roundtrip_resilient(), dirlist_accumulate(), ext_simple(), and fattr_set_or_del().
brix_s3_list()
int brix_s3_list (const brix_weburl * u, const char * ak, const char * sk, const char * region, int verify, const char * ca_dir, char *** keys, size_t * n_out, brix_status * st)
Definition at line 313 of file weblist.c.
References s3_list_req_t::ak, weblist_acc_t::arr, brix_format_host_port(), brix_http_req(), brix_http_resp_free(), brix_http_urlencode(), brix_status_set(), brix_strv_free(), s3_list_req_t::encp, s3_list_req_t::have_prefix, brix_weburl::host, s3_list_req_t::hostport, weblist_acc_t::n, brix_weburl::port, s3_list_req_t::region, region, s3_list_build_request(), s3_list_next_token(), s3_list_scan_keys(), s3_list_split_path(), s3_list_req_t::sk, brix_http_resp::status, brix_weburl::tls, XRDC_EPROTO, XRDC_EUSAGE, XRDC_PATH_MAX, and XRDC_WEBLIST_TIMEOUT.
Referenced by battery_s3(), and recursive_s3_download().
brix_s3_sha256_hex()
void brix_s3_sha256_hex (const void * data, size_t len, char * out)
Definition at line 28 of file s3.c.
References brix_hex_encode(), and brix_sha256().
Referenced by brix_s3_sigv4_build_canon_hash(), s3_delete(), s3_get_verify(), and s3_put().
brix_s3_sign_v4()
int brix_s3_sign_v4 (const char * method, const char * host, const char * uri, const char * ak, const char * sk, const char * region, const char * payload_hex, char * hdrs, size_t hdrsz)
Definition at line 204 of file s3.c.
References brix_s3_sign_v4_q(), host, and region.
Referenced by auth_hdr_s3(), s3_delete(), s3_get_verify(), s3_put(), and s3_sign().
brix_s3_sign_v4_q()
int brix_s3_sign_v4_q (const char * method, const char * host, const char * uri, const char * canon_qs, const char * ak, const char * sk, const char * region, const char * payload_hex, char * hdrs, size_t hdrsz)
Definition at line 170 of file s3.c.
References brix_s3_sigv4_build_canon_hash(), brix_s3_sigv4_build_sts(), brix_s3_sigv4_sign_and_emit(), host, region, and scope.
Referenced by brix_s3_sign_v4(), and s3_list_build_request().
brix_send()
int brix_send (brix_conn * c, void * hdr24, const brix_payload * pl, uint16_t * out_sid, brix_status * st)
Definition at line 81 of file frame.c.
References brix_send_ext(), c, brix_payload::data, and brix_payload::len.
Referenced by brix_bind(), brix_close(), brix_file_close(), brix_file_pgwrite(), brix_file_sync(), brix_file_write(), do_login(), file_pgread_frames(), file_read_frames(), file_readv_frames(), pgwrite_retry_one(), roundtrip_loop(), and send_auth().
brix_send_ext()
int brix_send_ext (brix_conn * c, void * hdr24, const brix_payload_ext * pl, uint16_t * out_sid, brix_status * st)
Definition at line 27 of file frame.c.
References brix_capture_frame(), brix_mono_ns(), brix_sigver_maybe(), brix_trace_frame(), brix_write_full(), c, brix_payload_ext::data, brix_payload_ext::dlen, brix_payload_ext::len, xrd_get_u16_be(), and XRD_REQUEST_HDR_LEN.
Referenced by brix_file_writev(), and brix_send().
brix_shellcode()
int brix_shellcode (const brix_status * st)
Definition at line 88 of file status.c.
References brix_status::kxr, XRDC_EAUTH, XRDC_EINTEGRITY, XRDC_EPROTO, XRDC_EREDIRECT, XRDC_ERESOLVE, XRDC_ESOCK, XRDC_EUNSUPPORTED, and XRDC_EUSAGE.
Referenced by aio_root_mount(), aio_web_mount(), brix_cli_connect(), brix_qstats_main(), brix_report_err(), cmd_bench(), cmd_destroy(), cmd_info(), cmd_init(), cmd_scan(), cmd_verify(), compare_setup(), do_bench(), do_cat(), do_check(), do_chmod(), do_cksum(), do_cmp(), do_compare_davs(), do_dd(), do_df(), do_download(), do_evict(), do_find(), do_grep(), do_head(), do_hexdump(), do_ln(), do_locate(), do_ls(), do_map(), do_mkdir(), do_mv(), do_prepare(), do_query(), do_readlink(), do_readv(), do_replay(), do_rm(), do_rmdir(), do_stage(), do_stat(), do_statvfs(), do_tail(), do_topology(), do_touch(), do_tree(), do_truncate(), do_upload(), do_wc(), do_writev(), download_copy_loop(), du_one_path(), main(), run_root_endpoint(), scan_fetch(), storascan_connect(), upload_copy_loop(), verify_compute_wire_hex(), wc_count_stream(), web_ls(), web_stat(), xattr_get(), xattr_ls(), xattr_rm(), xattr_set(), xfs_root_mount(), xrd_caps(), xrd_certinfo(), xrd_ping(), xrd_whoami(), xrdcp_dispatch_single(), and xrdprep_run().
brix_sock_tune()
void brix_sock_tune (int fd)
Definition at line 51 of file sock.c.
Referenced by brix_tcp_connect(), and connect_one().
brix_status_clear()
void brix_status_clear (brix_status * st)
Definition at line 22 of file status.c.
References brix_status::kxr, brix_status::msg, and brix_status::sys_errno.
Referenced by afh_open(), aio_root_mount(), aio_web_mount(), auth_hdr_bearer(), batch_worker(), battery_root(), battery_s3(), bench_run(), bench_sweep(), block_ring_select(), brix_cli_cksum_main(), brix_cli_connect(), brix_close(), brix_fuse_run(), brix_mpxstats_main(), brix_roundtrip_resilient(), brix_streams_open(), brix_wait41_main(), brix_with_resilience(), brix_xrdckverify_main(), brixcvmfs_open(), brixcvmfs_transport(), chk_probe_checksum(), chk_probe_confinement(), chk_probe_dirlist(), chk_probe_handle_limits(), chk_probe_pgread(), chk_probe_posc(), chmod_visit(), ckcheck_connect(), ckcheck_digest_local(), ckcheck_digest_remote(), cktree_run_remote(), close(), cmd_add(), cmd_del(), cmd_list(), cmd_scan(), compare_dirs(), compare_files(), compare_probe(), compare_setup(), copy_block(), copy_block_to_remote(), copy_one_with_retry(), copy_recursive(), copy_tree_upload(), copy_upload(), copy_vfs_to_vfs(), copy_zip_store_remote(), dest_is_dir(), do_bench(), do_cat(), do_check(), do_chmod(), do_cksum(), do_cmp(), do_compare_davs(), do_dd(), do_df(), do_download(), do_evict(), do_find(), do_grep(), do_head(), do_hexdump(), do_ln(), do_locate(), do_ls(), do_map(), do_metabench(), do_mkdir(), do_mv(), do_prepare(), do_probe_robustness(), do_query(), do_readlink(), do_readv(), do_replay(), do_rm(), do_rmdir(), do_srr(), do_stage(), do_stat(), do_status(), do_statvfs(), do_tail(), do_tape(), do_topology(), do_touch(), do_tree(), do_truncate(), do_upload(), do_watch(), do_wc(), do_writev(), doctor_cms(), doctor_diagnose(), doctor_http(), doctor_metrics(), doctor_one(), doctor_one_xfer_probe(), doctor_s3(), doctor_xfer(), download_open_local(), download_reconcile_cksum(), download_stream_body(), du_one_path(), dx_authz_anon(), dx_authz_scope(), dx_connect_as(), dx_probe_checksum(), dx_probe_namespace(), dx_probe_read(), dx_probe_stage(), dx_probe_write(), ensure_conn(), ensure_web_dst_base(), entry_cksum(), entry_meta(), expand_source(), fs_find_endpoint(), gsi_resolve_proxy(), head_lines(), http_davs_extras(), keytab_probe(), load_or_empty(), main(), map_fs_arg(), mb_thread(), mirror_delete_remote(), mirror_remote_remove(), parse_vmp(), playback_reissue_wire(), posix_ring_select(), pread(), print_space(), probe_holder(), probe_p1_path_escape(), probe_p2_bad_opcode(), probe_p3_oversized_dlen(), probe_p4_oob_read(), probe_p5_partial_frame(), probe_path_confinement(), probe_root_read_suite(), probe_server_survives(), probe_write_suite(), r2r_teardown(), raw_send_expect_reject(), read(), recdl_transfer_one(), recursive_s3_download(), recursive_web_download(), recursive_web_upload(), refresh_bearer_token(), refresh_gsi_proxy(), remote_entry_is_dir(), remote_open(), remote_stat(), remote_tree_visitor(), remove_source_entry(), run_root_endpoint(), s3_be_stat(), s3_delete(), s3_get_verify(), s3_put(), s3_resolve_keys(), s3_sigv4_probe(), s3t_request(), scan_fetch(), sss_first(), sss_have(), statx(), storascan_connect(), stream_file(), sync_cksum_match(), tail_follow(), tail_follow_drain(), tail_start_for_lines(), tape_poll_status(), test_contention_unique_issue(), test_create_fails_on_bad_endpoint(), test_destroy_closes_connected(), test_health_drop_reconnects(), test_reuse(), token_first(), topo_probe_locate(), topo_probe_redirect(), topo_report_cluster(), touch_ensure_file(), tpc_teardown(), tree_dl_entry(), tree_dl_file(), tree_emit_file(), ul_sync_skip(), upload_close_commit_resilient(), upload_reconcile_cksum(), verify_compute_wire_hex(), wait_online(), walk_handle_dir(), walk_handle_file(), watch_probe_once(), web_ls(), web_move_delete(), web_put_get_verify(), web_read_suite(), web_stat(), web_write_suite(), worker(), write_checksum(), write_readv(), write_rename_truncate_rm(), write_symlink_ops(), write_verify(), write_xattr_ops(), xattr_get(), xattr_ls(), xattr_rm(), xattr_set(), xfs_access(), xfs_access(), xfs_chmod(), xfs_chmod(), xfs_chown(), xfs_create(), xfs_flush(), xfs_flush(), xfs_fsync(), xfs_fsync(), xfs_getattr(), xfs_getattr(), xfs_getxattr(), xfs_getxattr(), xfs_handle_new(), xfs_link(), xfs_listxattr(), xfs_listxattr(), xfs_mkdir(), xfs_mkdir(), xfs_open(), xfs_read(), xfs_read(), xfs_readdir(), xfs_readdir(), xfs_readlink(), xfs_release(), xfs_release(), xfs_removexattr(), xfs_removexattr(), xfs_rename(), xfs_rename(), xfs_rmdir(), xfs_rmdir(), xfs_root_mount(), xfs_setxattr(), xfs_setxattr(), xfs_statfs(), xfs_statfs(), xfs_symlink(), xfs_truncate(), xfs_truncate(), xfs_unlink(), xfs_unlink(), xfs_utimens(), xfs_write(), xfs_write(), xrd_caps(), xrd_certinfo(), xrd_clockskew_http(), xrd_clockskew_root(), xrd_doctor_probe(), xrd_ping(), xrd_probe_caps(), xrd_run_battery(), xrd_whoami(), xrdcp_dispatch_batch(), xrdcp_dispatch_recursive_web_download(), xrdcp_dispatch_recursive_web_upload(), xrdcp_dispatch_single(), xrdcp_hint_failed_source(), and xrdcp_open_batch_journal().
brix_status_name()
const char * brix_status_name (int status)
Definition at line 35 of file trace.c.
References brix_kxr_response_status_name().
Referenced by brix_trace_response(), playback_reissue_wire(), and replay_frame_record().
brix_status_retryable()
int brix_status_retryable (const brix_status * st)
Definition at line 69 of file status.c.
References brix_status::kxr, kXR_inProgress, kXR_noserver, kXR_Overloaded, kXR_ServerError, XRDC_EPROTO, and XRDC_ESOCK.
Referenced by brix_connect_resilient(), brix_fuse_run(), brix_rfile_open_read(), brix_rfile_open_write(), brix_rfile_pread(), brix_rfile_pwrite(), brix_roundtrip_resilient(), brix_webfile_pread(), brix_webmeta_propfind(), brix_with_resilience(), csctx_retry_gate(), http_download_should_retry(), httpx_resumable_may_retry(), mfile_should_reopen(), pump_sink_remote(), pump_src_remote(), resilient_setup(), tail_follow(), upload_close_commit_resilient(), and xfs_readlink_one_attempt().
brix_status_set()
void brix_status_set (brix_status * st, int kxr, int sys_errno, const char * fmt, ...)
Definition at line 32 of file status.c.
References brix_status::kxr, brix_status::msg, and brix_status::sys_errno.
Referenced by aconn_destroy(), aconn_dispatch_response(), aconn_do_read(), aconn_do_write(), aconn_handle_io(), aconn_issue_areq(), aconn_parse(), aconn_read_plain(), aconn_read_tls(), aconn_reconnect_succeeded(), aconn_submit_cmd(), asynresp_deliver(), atomic_dest_finish(), auth_hdr_bearer(), auth_hdr_s3(), bat_upload_src_fd(), batch_copy_one(), bearer_acquire(), bench_one(), block_be_open(), block_be_stat(), block_commit(), block_fstat(), block_pread(), block_pwrite(), block_ring_select(), block_sync(), block_truncate(), brix_aconn_attach(), brix_aio_submit_ex(), brix_authenticate(), brix_bringup_ex(), brix_capture_playback(), brix_capture_replay(), brix_cks_verify_file(), brix_cksum_fd(), brix_connect(), brix_connect_no_login(), brix_copy_dispatch_recursive(), brix_copy_route(), brix_cpool_checkout(), brix_cpool_create(), brix_cred_acquire(), brix_deflate_frame(), brix_disk_ring_create(), brix_endpoint_parse(), brix_fattr_get(), brix_fattr_list(), brix_file_open_opaque(), brix_file_pgwrite(), brix_file_writev(), brix_glob(), brix_http_get(), brix_http_upload_resumable(), brix_inflate_frame(), brix_journal_open(), brix_kaconn_read_body(), brix_kaconn_read_headers(), brix_link(), brix_loop_create(), brix_mfile_open(), brix_mv(), brix_open_apply_inline_codec(), brix_open_credfile(), brix_pool_checkout(), brix_pool_create(), brix_prepare(), brix_proxy_destroy(), brix_proxy_info(), brix_query_cksum(), brix_readv_accumulate(), brix_readv_scatter(), brix_recv(), brix_rfile_pread(), brix_rfile_pwrite(), brix_rmtree(), brix_s3_list(), brix_setattr(), brix_sigver_maybe(), brix_sss_bf32_encrypt(), brix_sss_keytab_read(), brix_sss_keytab_write(), brix_symlink(), brix_tcp_connect(), brix_tls_read(), brix_tls_read_some(), brix_tls_write(), brix_url_parse(), brix_vfs_open(), brix_vfs_stat_url(), brix_web_readdir(), brix_web_stat(), brix_webdav_list(), brix_webdav_mkcol(), brix_webfile_open(), brix_webmeta_propfind(), cksum_compute_local(), cksum_parse_spec(), cksum_verify_literal(), cksum_verify_source(), ckv_verify_one(), connect_resolved(), copy_block(), copy_download(), copy_recursive(), copy_remote_to_block(), copy_remote_to_remote(), copy_tree_download(), copy_tree_upload(), copy_unzip_extract_member(), copy_unzip_finalize(), copy_unzip_open_dest(), copy_web(), copy_web_download(), copy_web_upload(), copy_zip_store(), copy_zip_store_local(), curl_slot_connect(), decode_pages(), dirlist_accumulate(), dirlist_parse_entries(), do_acquire(), do_dd(), do_handshake(), do_login(), download_to_fd(), fake_connect(), fattr_parse_status(), fattr_set_or_del(), file_pgread_frames(), file_read_frames(), file_readv_frames(), follow_redirect(), frame_read_body(), frame_read_header(), glob_parse_spec(), gsi_first(), gsi_more(), gsi_sigpxy(), head_lines(), host_first(), http_get_read_response(), http_get_send_request(), httpx_build_request(), httpx_chunk_read_status(), httpx_download_body(), httpx_download_exchange(), httpx_fmt_chunk_request(), httpx_fmt_put_request(), httpx_read_response(), httpx_read_some(), httpx_upload_body(), httpx_upload_response(), io_engine_setup(), kaconn_read_some(), mfile_do_open(), mfile_learn_codec(), mgr_alloc_and_init(), mgr_connect_eager(), open_download_temp(), open_payload_with_opaque(), parse_authority(), parse_remote(), pgwrite_correct_one_page(), pgwrite_handle_cse(), pgwrite_retry_one(), place_to_local(), place_to_web(), plain_read_full(), plain_write_full(), posix_be_open(), posix_be_stat(), posix_commit(), posix_fstat(), posix_pread(), posix_pwrite(), posix_ring_select(), posix_sync(), posix_truncate(), pump_src_local(), pwd_first(), pwd_more(), pxy_assemble_pem(), pxy_load_issuer(), rc_worker_main(), read_magic(), read_resp_headers(), read_status_frame(), recv_after_waitresp(), recv_dispatch(), recv_raw(), relay_web_to_web(), remote_md5(), resolve_once(), resolve_target(), rmtree_depth(), rmtree_one_entry(), rmtree_remove_leaf(), rt_handle_redirect(), rt_handle_wait(), run_module(), run_oidc_token(), s3_be_open(), s3_be_stat(), s3_commit(), s3_list_build_request(), s3_list_next_token(), s3_list_scan_keys(), s3_list_split_path(), s3_load_size(), s3_open_read(), s3_pread(), s3_pwrite(), s3_truncate(), s3keys_acquire(), scan_login(), set_kxr_error_status(), slurp_file(), ssl_fail(), sss_acquire(), sss_first(), sss_load_first_key(), stat_opt(), stream_chunked(), stream_clen(), stream_file(), tail_follow(), tail_start_for_lines(), timeouts_expire_inflight(), timeouts_expire_parked(), timeouts_scan_conn(), tls_do_connect(), tls_err(), token_first(), tpc_run_rendezvous(), tpc_setup_source(), transfer_pump(), tree_dl_entry(), tree_recurse(), tree_ul_entry(), tree_walk_depth(), unix_first(), verify_download_tmp(), watch_write_prom_atomic(), web_range_read_headers(), web_range_send_req(), web_range_stream_body(), web_read_some(), webdav_list_emit_block(), webdav_parse_multi(), webdav_parse_single(), webmeta_send_req(), webmeta_status_map(), write_all(), write_all_fd(), x509_acquire(), zip_emit_member(), and zip_read_seed().
brix_streams_close()
void brix_streams_close (brix_streamset * ss)
Definition at line 52 of file streams.c.
References brix_tls_free(), close(), brix_io::fd, brix_conn::io, brix_streamset::n, and brix_streamset::sec.
Referenced by copy_download(), copy_remote_to_block(), and upload_stream_body().
brix_streams_open()
int brix_streams_open (brix_streamset * ss, brix_conn * primary, int streams, brix_status * st)
Definition at line 24 of file streams.c.
References brix_bind(), brix_status_clear(), brix_streamset::n, brix_streamset::sec, and XRDC_MAX_STREAMS.
Referenced by download_stream_body(), and upload_stream_body().
brix_strv_free()
void brix_strv_free (char ** arr, size_t n)
Definition at line 98 of file weblist.c.
Referenced by battery_s3(), brix_s3_list(), brix_webdav_list(), recursive_s3_download(), and recursive_web_download().
brix_tcp_connect()
int brix_tcp_connect (const char * host, int port, int timeout_ms, brix_status * st)
Definition at line 220 of file sock.c.
References brix_netpref_family(), brix_netpref_undo_demote(), brix_sock_tune(), brix_status_set(), close(), connect_resolved(), host, port, and XRDC_ESOCK.
Referenced by brix_bringup_ex(), brix_http_get(), brix_kaconn_connect(), brix_wait41_main(), httpx_connect(), and web_connect().
brix_timing_report()
void brix_timing_report (const brix_conn * c)
Definition at line 212 of file trace.c.
References brix_reqid_name(), c, kXR_1stRequest, and XRDC_NOP.
Referenced by brix_close(), and do_bench().
brix_tls_client()
int brix_tls_client (brix_io * io, const char * host, int verify_peer, int verify_host, const char * ca_dir, void ** out_ctx, brix_status * st)
Definition at line 371 of file tls.c.
References brix_io::fd, host, brix_io::ssl, tls_do_connect(), tls_err(), XRDC_EAUTH, and XRDC_ESOCK.
Referenced by brix_kaconn_connect(), httpx_connect(), and web_connect().
brix_tls_client_free()
void brix_tls_client_free (brix_io * io, void * ctx)
Definition at line 434 of file tls.c.
References brix_io::ssl.
Referenced by brix_http_req(), brix_http_upload(), brix_kaconn_disconnect(), http_download_attempt(), httpx_resumable_attempt(), and web_disconnect().
brix_tls_client_info()
void brix_tls_client_info (const brix_io * io, const char ** ver, const char ** cipher)
Definition at line 448 of file tls.c.
References brix_io::ssl.
Referenced by brix_http_req().
brix_tls_free()
void brix_tls_free (brix_conn * c)
Definition at line 460 of file tls.c.
References c.
Referenced by brix_bind(), brix_close(), brix_reconnect(), and brix_streams_close().
brix_tls_info()
int brix_tls_info (const brix_conn * c, const char ** ver, const char ** cipher)
Definition at line 474 of file tls.c.
References c.
Referenced by chk_probe_tls(), doctor_one_session_facts(), explain_tls(), watch_probe_once(), xrd_caps(), and xrd_doctor_probe().
brix_tls_peer_cert_info()
int brix_tls_peer_cert_info (const brix_conn * c, brix_cert_info * out)
Definition at line 523 of file tls.c.
References c, brix_cert_info::days_left, brix_cert_info::expired, brix_cert_info::have, brix_cert_info::host_match, brix_cert_info::issuer, brix_cert_info::not_after, brix_cert_info::not_before, brix_cert_info::not_yet_valid, peer_collect_sans(), brix_cert_info::sans, brix_cert_info::self_signed, and brix_cert_info::subject.
Referenced by xrd_certinfo(), and xrd_doctor_probe().
brix_tls_read()
int brix_tls_read (brix_io * io, void * buf, size_t n, brix_status * st)
Definition at line 84 of file tls.c.
References brix_copy_quit_requested(), brix_mono_ns(), brix_status_set(), brix_io::fd, brix_io::ssl, brix_io::stall_deadline_ms, brix_io::stall_deadline_ns, brix_io::timeout_ms, tls_err(), tls_read_wait_ms(), wait_io(), and XRDC_ESOCK.
Referenced by brix_read_full().
brix_tls_read_some()
int brix_tls_read_some (brix_io * io, void * buf, size_t n, size_t * got, brix_status * st)
Definition at line 324 of file tls.c.
References brix_status_set(), brix_io::fd, brix_io::ssl, brix_io::timeout_ms, tls_err(), wait_io(), and XRDC_ESOCK.
Referenced by httpx_read_some(), kaconn_read_some(), and web_read_some().
brix_tls_upgrade()
int brix_tls_upgrade (brix_conn * c, int verify_peer, int verify_host, const char * ca_dir, brix_status * st)
Definition at line 256 of file tls.c.
References c, tls_do_connect(), tls_err(), XRDC_EAUTH, and XRDC_ESOCK.
Referenced by brix_bringup_ex().
brix_tls_write()
int brix_tls_write (brix_io * io, const void * buf, size_t n, brix_status * st)
Definition at line 161 of file tls.c.
References brix_copy_quit_requested(), brix_status_set(), brix_io::fd, brix_io::ssl, brix_io::timeout_ms, tls_err(), wait_io(), and XRDC_ESOCK.
Referenced by brix_write_full().
brix_tmo_connect_ms()
int brix_tmo_connect_ms (void)
Definition at line 78 of file nettmo.c.
References g_connect_ms, resolve_ms(), and XRDC_TMO_CONNECT_DEFAULT_MS.
Referenced by brix_bringup_ex().
brix_tmo_io_ms()
int brix_tmo_io_ms (void)
Definition at line 85 of file nettmo.c.
References g_io_ms, resolve_ms(), and XRDC_TMO_IO_DEFAULT_MS.
Referenced by brix_bringup_ex(), brix_connect(), and brix_connect_no_login().
brix_tmo_set_connect_ms()
void brix_tmo_set_connect_ms (int ms)
Definition at line 112 of file nettmo.c.
References g_connect_ms.
Referenced by aio_opt_conn_value(), and xfs_opt_value().
brix_tmo_set_io_ms()
void brix_tmo_set_io_ms (int ms)
Definition at line 120 of file nettmo.c.
References g_io_ms.
Referenced by aio_opt_conn_value(), and xfs_opt_value().
brix_tmo_set_stall_ms()
void brix_tmo_set_stall_ms (int ms)
Definition at line 104 of file nettmo.c.
References g_stall_ms.
brix_tmo_stall_ms()
int brix_tmo_stall_ms (void)
Definition at line 97 of file nettmo.c.
References g_stall_ms, and resolve_ms().
Referenced by brix_bringup_ex().
brix_trace_frame()
void brix_trace_frame (brix_conn * c, int dir, uint16_t sid, int code, int is_request, uint32_t dlen, const void * body, uint32_t blen)
Definition at line 194 of file trace.c.
References brix_reqid_name(), brix_trace_response(), c, code, and hexdump().
Referenced by brix_send_ext(), recv_note_diag(), recv_raw(), and recv_raw_frame().
brix_url_parse()
int brix_url_parse (const char * s, brix_url * out, brix_status * st)
Definition at line 112 of file url.c.
References brix_status_set(), parse_remote(), brix_url::path, s, brix_url::scheme, starts_with(), XRDC_EUSAGE, XRDC_SCHEME_LOCAL, XRDC_SCHEME_ROOT, XRDC_SCHEME_ROOTS, and XRDC_SCHEME_STDIO.
Referenced by brix_cli_cksum_main(), brix_copy_classify(), brix_endpoint_parse(), brix_glob(), ckcheck_connect(), cktree_run_remote(), copy_block(), copy_block_to_remote(), copy_remote_to_block(), copy_web(), dest_is_dir(), entry_cksum(), entry_meta(), fs_find_endpoint(), main(), map_fs_arg(), remove_source_entry(), and xrdcp_hint_failed_source().
brix_web_readdir()
int brix_web_readdir (const brix_weburl * u, const char * path, const char * bearer, int verify, const char * ca_dir, brix_dirent ** ents, size_t * n, brix_status * st)
Definition at line 436 of file webfile.c.
References brix_http_resp::body, brix_http_resp::body_len, brix_http_req(), brix_http_resp_free(), brix_status_set(), brix_weburl::host, path_basename(), brix_weburl::port, brix_http_resp::status, brix_weburl::tls, web_auth(), WEB_TIMEOUT_MS, webdav_parse_multi(), XRDC_EPROTO, and XRDC_PATH_MAX.
Referenced by web_ls_print_dir().
brix_web_readdir_pooled()
int brix_web_readdir_pooled (struct brix_cpool * pool, const char * path, brix_dirent ** ents, size_t * n, brix_status * st)
Definition at line 468 of file webfile.c.
References brix_cpool_checkin(), brix_cpool_checkout(), brix_fuse_conn_healthy(), brix_webmeta_propfind(), path_basename(), webdav_parse_multi(), and XRDC_PATH_MAX.
Referenced by xfs_readdir().
brix_web_stat()
int brix_web_stat (const brix_weburl * u, const char * path, const char * bearer, int verify, const char * ca_dir, brix_statinfo * si, brix_status * st)
Definition at line 153 of file webfile.c.
References brix_http_resp::body, brix_http_resp::body_len, brix_http_req(), brix_http_resp_free(), brix_status_set(), brix_weburl::host, kXR_NotFound, brix_weburl::port, brix_http_resp::status, brix_weburl::tls, web_auth(), WEB_TIMEOUT_MS, webdav_parse_single(), and XRDC_EPROTO.
Referenced by aio_web_mount(), brix_webfile_open(), and web_stat().
brix_web_stat_pooled()
int brix_web_stat_pooled (struct brix_cpool * pool, const char * path, brix_statinfo * si, brix_status * st)
Definition at line 186 of file webfile.c.
References brix_cpool_checkin(), brix_cpool_checkout(), brix_fuse_conn_healthy(), brix_webmeta_propfind(), and webdav_parse_single().
Referenced by xfs_getattr().
brix_webdav_list()
int brix_webdav_list (const brix_weburl * u, const char * bearer, int verify, const char * ca_dir, char *** paths, size_t * n_out, brix_status * st)
Definition at line 523 of file weblist.c.
References weblist_acc_t::arr, brix_http_resp::body, brix_http_req(), brix_http_resp_free(), brix_status_set(), brix_strv_free(), brix_weburl::host, brix_weburl::is_s3, weblist_acc_t::n, brix_weburl::path, brix_weburl::port, brix_http_resp::status, brix_weburl::tls, webdav_list_build_headers(), webdav_list_scan_body(), XRDC_EPROTO, XRDC_EUSAGE, and XRDC_WEBLIST_TIMEOUT.
Referenced by recursive_web_download().
brix_webdav_mkcol()
int brix_webdav_mkcol (const brix_weburl * u, const char * path, const char * bearer, int verify, const char * ca_dir, brix_status * st)
Definition at line 391 of file weblist.c.
References brix_http_req(), brix_http_resp_free(), brix_status_set(), brix_weburl::host, brix_weburl::port, brix_http_resp::status, brix_weburl::tls, XRDC_EPROTO, and XRDC_WEBLIST_TIMEOUT.
Referenced by ensure_web_dst_base(), mkcol_parents(), recursive_web_upload(), and walk_handle_dir().
brix_webfile_close()
void brix_webfile_close (brix_webfile * wf, brix_status * st)
Definition at line 463 of file webfile_io.c.
References web_disconnect().
Referenced by xfs_release().
brix_webfile_open()
brix_webfile * brix_webfile_open (const brix_weburl * u, const char * path, const char * bearer, int verify, const char * ca_dir, int timeout_ms, brix_statinfo * si_out, brix_status * st)
Definition at line 334 of file webfile_io.c.
References brix_webfile::auth, brix_format_host_port(), brix_status_set(), brix_web_stat(), brix_webfile::ca_dir, brix_io::fd, brix_statinfo::flags, brix_weburl::host, brix_webfile::host, brix_webfile::hostport, brix_webfile::io, kXR_isDir, brix_webfile::path, brix_weburl::port, brix_webfile::port, brix_statinfo::size, brix_webfile::size, brix_webfile::timeout_ms, brix_weburl::tls, brix_webfile::tls, brix_webfile::verify, web_auth(), WEB_TIMEOUT_MS, XRDC_EPROTO, and XRDC_EUSAGE.
Referenced by afh_open().
brix_webfile_pread()
ssize_t brix_webfile_pread (brix_webfile * wf, int64_t off, void * buf, size_t len, brix_status * st)
Definition at line 400 of file webfile_io.c.
References brix_backoff_sleep_fast(), brix_mono_ns(), brix_status_retryable(), brix_webfile::connected, brix_webfile::size, web_connect(), web_get_range(), and webfile_window_ms().
Referenced by afh_pread().
brix_webfile_size()
int64_t brix_webfile_size (const brix_webfile * wf)
Definition at line 376 of file webfile_io.c.
References brix_webfile::size.
brix_write_full()
int brix_write_full (brix_io * io, const void * buf, size_t n, brix_status * st)
Definition at line 467 of file sock.c.
References brix_tls_write(), note_io_failure(), plain_write_full(), and brix_io::ssl.
Referenced by brix_send_ext(), brix_sigver_maybe(), do_handshake(), httpx_chunk_core(), httpx_download_exchange(), httpx_exchange_core(), httpx_send_request(), httpx_upload_body(), playback_reissue_wire(), probe_p5_partial_frame(), raw_send_expect_reject(), web_range_send_req(), and webmeta_send_req().
brix_xrdrc_default_ms()
int brix_xrdrc_default_ms (const char * key, int * out_ms)
Definition at line 428 of file xrdrc.c.
References g_def_backoff_ms, g_def_connect_ms, g_def_io_ms, g_def_stall_ms, g_loaded, key, and xrdrc_load().
Referenced by backoff_base_ms(), httpx_window_ms(), opts_window_ms(), resolve_ms(), and webfile_window_ms().