nginx-xrootd: client/apps/diag/brix_fault_tls.c File Reference
brix_fault_tls.c File Reference
#include "brix_fault_tls.h"
#include "brix_fault_buf.h"
Functions
void fp_tls_cfg_init (fp_tls_cfg *c)
int fp_tls_active (const fp_tls_cfg *c)
static void emit_record (unsigned char *out, size_t cap, size_t *o, unsigned char type, unsigned char v0, unsigned char v1, int declared_len, const unsigned char *body, size_t blen, int flip_first)
size_t fp_tls_rewrite (const unsigned char *in, size_t n, unsigned char *out, size_t outcap, fp_tls_cfg *c, fp_tls_stats *st)
Function Documentation
emit_record()
static void emit_record (unsigned char * out, size_t cap, size_t * o, unsigned char type, unsigned char v0, unsigned char v1, int declared_len, const unsigned char * body, size_t blen, int flip_first) static
Definition at line 32 of file brix_fault_tls.c.
References fp_bufcat().
Referenced by fp_tls_rewrite().
fp_tls_active()
int fp_tls_active (const fp_tls_cfg * c)
Definition at line 22 of file brix_fault_tls.c.
References c.
Referenced by cmd_status_report(), and relay_pump_dir().
fp_tls_cfg_init()
void fp_tls_cfg_init (fp_tls_cfg * c)
Definition at line 8 of file brix_fault_tls.c.
References c.
Referenced by clear_all(), cmd_set_tls(), and main().
fp_tls_rewrite()
size_t fp_tls_rewrite (const unsigned char * in, size_t n, unsigned char * out, size_t outcap, fp_tls_cfg * c, fp_tls_stats * st)
Definition at line 60 of file brix_fault_tls.c.
References fp_tls_stats::alerts, c, fp_tls_stats::dropped, emit_record(), fp_tls_stats::flipped, fp_bufcat(), fp_tls_stats::fragmented, fp_tls_stats::records, and fp_tls_stats::retyped.
Referenced by apply_tls().