nginx-xrootd: client/apps/diag/brix_fault_ext.c File Reference
brix_fault_ext.c File Reference
#include "brix_fault_ext.h"
#include <arpa/inet.h>
#include <ctype.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct fp_hostpair
Functions
int fp_ext_mut_active (const fp_ext_mut *m)
static int emit (unsigned char *out, size_t outcap, size_t *o, unsigned char b)
size_t fp_ext_mutate (const unsigned char *in, size_t n, unsigned char *out, size_t outcap, const fp_ext_mut *m, unsigned *seed, fp_ext_stats *st)
static int hexbyte (const char *s)
static int parse_hex (const char *p, unsigned char *out, size_t cap)
static int parse_literal (const char *p, unsigned char *out, size_t cap)
int fp_ext_parse_payload (const char *tok, unsigned char *out, size_t cap)
static int split_hostport (const char *hp, char *ip, size_t ipcap, int *port)
static int parse_pair (const char *src, const char *dst, fp_hostpair *hp)
int fp_ext_proxy_v1 (char *out, size_t cap, const char *src, const char *dst)
int fp_ext_proxy_v2 (unsigned char *out, size_t cap, const char *src, const char *dst)
Function Documentation
emit()
static int emit (unsigned char * out, size_t outcap, size_t * o, unsigned char b) static
Definition at line 24 of file brix_fault_ext.c.
Referenced by fp_ext_mutate().
fp_ext_mut_active()
int fp_ext_mut_active (const fp_ext_mut * m)
Definition at line 16 of file brix_fault_ext.c.
References fp_ext_mut::drop_ppm, fp_ext_mut::find_len, fp_ext_mut::inject_len, and fp_ext_mut::repeat_ppm.
Referenced by ext_snapshot().
fp_ext_mutate()
size_t fp_ext_mutate (const unsigned char * in, size_t n, unsigned char * out, size_t outcap, const fp_ext_mut * m, unsigned * seed, fp_ext_stats * st)
Definition at line 34 of file brix_fault_ext.c.
References fp_ext_mut::drop_ppm, fp_ext_stats::dropped, emit(), fp_ext_mut::find, fp_ext_mut::find_len, fp_ext_mut::inject, fp_ext_mut::inject_len, fp_ext_stats::injected, fp_ext_mut::repeat_ppm, fp_ext_stats::repeated, fp_ext_mut::repl, fp_ext_mut::repl_len, and fp_ext_stats::replaced.
Referenced by relay_pump_dir().
fp_ext_parse_payload()
int fp_ext_parse_payload (const char * tok, unsigned char * out, size_t cap)
Definition at line 147 of file brix_fault_ext.c.
References parse_hex(), parse_literal(), and tok.
Referenced by cmd_set_http(), cmd_trigger(), ext_set_inject(), and ext_set_replace().
fp_ext_proxy_v1()
int fp_ext_proxy_v1 (char * out, size_t cap, const char * src, const char * dst)
Definition at line 232 of file brix_fault_ext.c.
References fp_hostpair::dip, fp_hostpair::dport, fp_hostpair::fam, parse_pair(), fp_hostpair::sip, and fp_hostpair::sport.
Referenced by send_proxy_header().
fp_ext_proxy_v2()
int fp_ext_proxy_v2 (unsigned char * out, size_t cap, const char * src, const char * dst)
Definition at line 248 of file brix_fault_ext.c.
References fp_hostpair::dip, fp_hostpair::dport, fp_hostpair::fam, parse_pair(), fp_hostpair::sip, and fp_hostpair::sport.
Referenced by send_proxy_header().
hexbyte()
static int hexbyte (const char * s) static
Definition at line 78 of file brix_fault_ext.c.
References c, and s.
Referenced by parse_hex(), and parse_literal().
parse_hex()
static int parse_hex (const char * p, unsigned char * out, size_t cap) static
Definition at line 94 of file brix_fault_ext.c.
References hexbyte().
Referenced by fp_ext_parse_payload().
parse_literal()
static int parse_literal (const char * p, unsigned char * out, size_t cap) static
Definition at line 113 of file brix_fault_ext.c.
References c, and hexbyte().
Referenced by fp_ext_parse_payload().
parse_pair()
static int parse_pair (const char * src, const char * dst, fp_hostpair * hp) static
Definition at line 220 of file brix_fault_ext.c.
References fp_hostpair::dip, fp_hostpair::dport, fp_hostpair::fam, fp_hostpair::sip, split_hostport(), and fp_hostpair::sport.
Referenced by fp_ext_proxy_v1(), and fp_ext_proxy_v2().
split_hostport()
static int split_hostport (const char * hp, char * ip, size_t ipcap, int * port) static
Definition at line 164 of file brix_fault_ext.c.
References close(), and port.
Referenced by parse_pair().