nginx-xrootd: client/apps/fs/brixmount.c File Reference
brixmount.c File Reference
#include "cvmfs/client/client.h"
#include "core/version.h"
#include "cli/suggest.h"
#include "cli/cli_hint.h"
#include <stdio.h>
#include <string.h>
Data Structures
struct brix_driver_t
Macros
#define BRIXMOUNT_MAX_ARGS 64
Typedefs
typedef int(* brix_driver_fn) (int argc, char **argv)
Functions
static void brixmount_usage (FILE *out, const brix_driver_t *drv, size_t n)
int brixmount_overlay_route (int argc, char **argv, int(*list_fn)(const char *, FILE *), int(*reset_fn)(const char *))
int brixmount_dispatch (int argc, char **argv, const brix_driver_t *drv, size_t ndrv)
int brixcvmfs_main (int argc, char **argv)
int brixcvmfs_rw_main (int argc, char **argv)
int brixautofs_main (int argc, char **argv)
int xrootdfs_aio_main (int argc, char **argv)
int brix_overlay_cli_list (const char *mountdir, FILE *out)
int brix_overlay_cli_reset (const char *mountdir)
int main (int argc, char **argv)
Macro Definition Documentation
BRIXMOUNT_MAX_ARGS
#define BRIXMOUNT_MAX_ARGS 64
Definition at line 34 of file brixmount.c.
Typedef Documentation
brix_driver_fn
typedef int(* brix_driver_fn) (int argc, char **argv)
Definition at line 26 of file brixmount.c.
Function Documentation
brix_overlay_cli_list()
int brix_overlay_cli_list (const char * mountdir, FILE * out)
Definition at line 706 of file overlay.c.
References ov_cli_guard(), and ov_cli_list_dir().
Referenced by main(), and test_cli().
brix_overlay_cli_reset()
int brix_overlay_cli_reset (const char * mountdir)
Definition at line 743 of file overlay.c.
References close(), open(), ov_cli_guard(), and ov_cli_reset_contents().
Referenced by main(), and test_cli().
brixautofs_main()
int brixautofs_main (int argc, char ** argv)
Definition at line 643 of file brixautofs.c.
References af_control_thread(), af_idle_thread(), af_log(), af_mkdir_p(), af_ops, af_parse_opts(), af_scan_configured(), af_signal(), af_teardown_children(), autofs_opts_t::allow_other, brixautofs_table_init(), autofs_opts_t::cache_base, close(), autofs_opts_t::debug, autofs_state_t::etc, autofs_state_t::farm, autofs_opts_t::foreground, autofs_state_t::fuse, autofs_opts_t::fuse_extra, g_af, autofs_opts_t::idle_s, autofs_state_t::mnt, autofs_opts_t::mnt_base, autofs_state_t::o, PATH_MAX, autofs_opts_t::repos, autofs_state_t::repos, autofs_state_t::sigpipe, autofs_state_t::strict, and autofs_state_t::tab.
Referenced by main().
brixcvmfs_main()
int brixcvmfs_main (int argc, char ** argv)
Definition at line 1056 of file brixcvmfs.c.
References brixcvmfs_check(), brixcvmfs_mount_run(), brixcvmfs_prewarm(), and parse_opts().
Referenced by main().
brixcvmfs_rw_main()
int brixcvmfs_rw_main (int argc, char ** argv)
Definition at line 875 of file brixcvmfs_rw.c.
Referenced by main().
brixmount_dispatch()
int brixmount_dispatch (int argc, char ** argv, const brix_driver_t * drv, size_t ndrv)
Definition at line 74 of file brixmount.c.
References brix_driver_t::brand, brix_cli_hint(), brix_suggest(), BRIXMOUNT_MAX_ARGS, brixmount_usage(), brix_driver_t::fn, and brix_driver_t::type.
Referenced by main(), and main().
brixmount_overlay_route()
int brixmount_overlay_route (int argc, char ** argv, int(*)(const char *, FILE *) list_fn, int(*)(const char *) reset_fn)
Definition at line 57 of file brixmount.c.
Referenced by main(), and main().
brixmount_usage()
static void brixmount_usage (FILE * out, const brix_driver_t * drv, size_t n) static
Definition at line 36 of file brixmount.c.
References BRIX_USAGE_FOOTER, and fn.
Referenced by brixmount_dispatch().
main()
int main (int argc, char ** argv)
Definition at line 144 of file brixmount.c.
References brix_client_version(), brix_overlay_cli_list(), brix_overlay_cli_reset(), BRIX_USAGE_FOOTER, brixautofs_main(), brixcvmfs_main(), brixcvmfs_rw_main(), brixmount_dispatch(), brixmount_overlay_route(), brix_driver_t::fn, fn, and xrootdfs_aio_main().
xrootdfs_aio_main()
int xrootdfs_aio_main (int argc, char ** argv) extern
Definition at line 560 of file xrootdfs.c.
References aio_parse_args(), aio_root_mount(), aio_web_mount(), brix_client_version(), brix_crypto_init(), brix_is_web_url(), g_opts, usage(), usage_fp(), and brix_opts::verify_host.
Referenced by main().