nginx-xrootd: client/apps/diag/brix_fault_buf.h File Reference
brix_fault_buf.h File Reference
#include <stddef.h>
#include <string.h>
Functions
static size_t fp_bufcat (unsigned char *out, size_t cap, size_t *o, const void *src, size_t n)
static int fp_bufputc (unsigned char *out, size_t cap, size_t *o, unsigned char b)
static void fp_buf_eol (unsigned char *out, size_t cap, size_t *o, int lf)
Function Documentation
fp_buf_eol()
static void fp_buf_eol (unsigned char * out, size_t cap, size_t * o, int lf) inline static
Definition at line 44 of file brix_fault_buf.h.
References fp_bufcat(), and fp_bufputc().
Referenced by emit_added_headers(), emit_line(), emit_te_obfuscated(), and fp_http_rewrite().
fp_bufcat()
static size_t fp_bufcat (unsigned char * out, size_t cap, size_t * o, const void * src, size_t n) inline static
Definition at line 17 of file brix_fault_buf.h.
Referenced by emit_added_headers(), emit_line(), emit_record(), emit_te_obfuscated(), fp_buf_eol(), fp_http_rewrite(), and fp_tls_rewrite().
fp_bufputc()
static int fp_bufputc (unsigned char * out, size_t cap, size_t * o, unsigned char b) inline static
Definition at line 33 of file brix_fault_buf.h.
Referenced by emit_te_obfuscated(), and fp_buf_eol().