nginx-xrootd: client/apps/fs/brixautofs.c File Reference
brixautofs.c File Reference
#include "brixautofs.h"
#include <stdio.h>
#include <string.h>
#include <fuse3/fuse.h>
#include "cvmfs/config/cvmfs_conf.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <signal.h>
#include <stdarg.h>
#include <stdlib.h>
#include <sys/mount.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct autofs_opts_t
struct autofs_state_t
Macros
#define FUSE_USE_VERSION 31
Functions
int brixautofs_valid_fqrn (const char *name)
int brixautofs_repo_listed (const char *list, const char *fqrn)
void brixautofs_table_init (brixautofs_table_t *t)
int brixautofs_find_locked (brixautofs_table_t *t, const char *fqrn)
int brixautofs_claim_locked (brixautofs_table_t *t, const char *fqrn)
void brixautofs_commit_locked (brixautofs_table_t *t, int idx, pid_t pid)
void brixautofs_release_locked (brixautofs_table_t *t, int idx)
int brixautofs_find_pid_locked (brixautofs_table_t *t, pid_t pid)
static void af_log (const char *fmt,...)
static int af_is_mounted (const char *path)
static void af_child_path (const char *fqrn, char *out, size_t cap)
static int af_mkdir_p (const char *path)
static int af_umount_path (const char *path)
static void af_child_opts (const char *fqrn, char *out, size_t cap)
static pid_t af_spawn_child (const char *fqrn)
static int af_admit (const char *name)
static int af_ensure_repo (const char *name)
static void af_fill_dir_stat (struct stat *st)
static void af_fill_link_stat (struct stat *st, const char *name)
static int af_getattr (const char *path, struct stat *st, struct fuse_file_info *fi)
static int af_readlink (const char *path, char *buf, size_t cap)
static int af_opendir (const char *path, struct fuse_file_info *fi)
static int af_repos_nth_token (const char *list, int idx, char *out, size_t outsz)
static int af_ghost_name (int src, int idx, char *out, size_t outsz)
static int af_seen_has (char seen[][256], int nseen, const char *name)
static void af_fill_mounted (void *buf, fuse_fill_dir_t fill, char seen[][256], int *nseen)
static int af_readdir (const char *path, void *buf, fuse_fill_dir_t fill, off_t off, struct fuse_file_info *fi, enum fuse_readdir_flags flags)
static void af_signal (int sig)
static void af_reap_children (void)
static void af_teardown_children (void)
static void * af_control_thread (void *arg)
static void * af_idle_thread (void *arg)
static void af_opts_o_list (char *list, autofs_opts_t *o)
static void af_parse_opts (int argc, char **argv, int start, autofs_opts_t *o)
static void af_scan_configured (const char *etc_root)
static int af_setup_mount_farm (void)
static void af_load_repo_config (void)
static int af_fuse_bringup (char *argv0)
static int af_install_signals (void)
static int af_run (void)
int brixautofs_main (int argc, char **argv)
Variables
static autofs_state_t g_af
static const struct fuse_operations af_ops
Macro Definition Documentation
FUSE_USE_VERSION
#define FUSE_USE_VERSION 31
Definition at line 116 of file brixautofs.c.
Function Documentation
af_admit()
static int af_admit (const char * name) static
Definition at line 303 of file brixautofs.c.
References brixautofs_repo_listed(), brixautofs_valid_fqrn(), g_af, name, autofs_state_t::repos, autofs_state_t::shutting_down, and autofs_state_t::strict.
Referenced by af_ensure_repo(), and af_getattr().
af_child_opts()
static void af_child_opts (const char * fqrn, char * out, size_t cap) static
Definition at line 242 of file brixautofs.c.
References autofs_opts_t::allow_other, autofs_opts_t::cache_base, g_af, and autofs_state_t::o.
Referenced by af_spawn_child().
af_child_path()
static void af_child_path (const char * fqrn, char * out, size_t cap) static
Definition at line 193 of file brixautofs.c.
References BRIXAUTOFS_FQRN_MAX, autofs_state_t::farm, and g_af.
Referenced by af_fill_link_stat(), af_idle_thread(), af_readlink(), af_reap_children(), af_spawn_child(), and af_teardown_children().
af_control_thread()
static void * af_control_thread (void * arg) static
Definition at line 551 of file brixautofs.c.
References af_reap_children(), af_teardown_children(), af_umount_path(), c, autofs_state_t::fuse, g_af, autofs_state_t::mnt, read(), and autofs_state_t::sigpipe.
Referenced by af_run().
af_ensure_repo()
static int af_ensure_repo (const char * name) static
Definition at line 314 of file brixautofs.c.
References af_admit(), af_log(), af_spawn_child(), brixautofs_claim_locked(), brixautofs_commit_locked(), brixautofs_find_locked(), BRIXAUTOFS_MAX_REPOS, brixautofs_release_locked(), g_af, brixautofs_table_t::mu, name, and autofs_state_t::tab.
Referenced by af_readlink().
af_fill_dir_stat()
static void af_fill_dir_stat (struct stat * st) static
Definition at line 343 of file brixautofs.c.
Referenced by af_getattr().
af_fill_link_stat()
static void af_fill_link_stat (struct stat * st, const char * name) static
Definition at line 352 of file brixautofs.c.
References af_child_path(), and name.
Referenced by af_getattr().
af_fill_mounted()
static void af_fill_mounted (void * buf, fuse_fill_dir_t fill, char seen[][256], int * nseen) static
Definition at line 436 of file brixautofs.c.
References BRIXAUTOFS_FQRN_MAX, BRIXAUTOFS_FREE, BRIXAUTOFS_MAX_REPOS, brixautofs_slot_t::fqrn, g_af, brixautofs_table_t::mu, brixautofs_table_t::slot, brixautofs_slot_t::st, and autofs_state_t::tab.
Referenced by af_readdir().
af_fuse_bringup()
static int af_fuse_bringup (char * argv0) static
Definition at line 727 of file brixautofs.c.
References af_log(), af_ops, autofs_opts_t::allow_other, autofs_opts_t::debug, autofs_opts_t::foreground, autofs_state_t::fuse, autofs_opts_t::fuse_extra, g_af, autofs_state_t::mnt, and autofs_state_t::o.
Referenced by brixautofs_main().
af_getattr()
static int af_getattr (const char * path, struct stat * st, struct fuse_file_info * fi) static
Definition at line 367 of file brixautofs.c.
References af_admit(), af_fill_dir_stat(), af_fill_link_stat(), and name.
af_ghost_name()
static int af_ghost_name (int src, int idx, char * out, size_t outsz) static
Definition at line 418 of file brixautofs.c.
References af_repos_nth_token(), g_af, autofs_state_t::ghost, autofs_state_t::nghost, and autofs_state_t::repos.
Referenced by af_readdir().
af_idle_thread()
static void * af_idle_thread (void * arg) static
Definition at line 572 of file brixautofs.c.
References af_child_path(), af_log(), BRIXAUTOFS_FQRN_MAX, BRIXAUTOFS_MAX_REPOS, BRIXAUTOFS_MOUNTED, brixautofs_slot_t::fqrn, g_af, autofs_opts_t::idle_s, brixautofs_table_t::mu, autofs_state_t::o, autofs_state_t::shutting_down, brixautofs_table_t::slot, brixautofs_slot_t::st, and autofs_state_t::tab.
Referenced by af_run().
af_install_signals()
static int af_install_signals (void) static
Definition at line 762 of file brixautofs.c.
References af_log(), af_signal(), autofs_state_t::fuse, g_af, and autofs_state_t::sigpipe.
Referenced by brixautofs_main().
af_is_mounted()
static int af_is_mounted (const char * path) static
Definition at line 176 of file brixautofs.c.
References tok.
Referenced by af_reap_children(), af_spawn_child(), and af_umount_path().
af_load_repo_config()
static void af_load_repo_config (void) static
Definition at line 704 of file brixautofs.c.
References af_log(), af_scan_configured(), autofs_state_t::etc, g_af, autofs_state_t::o, autofs_opts_t::repos, autofs_state_t::repos, and autofs_state_t::strict.
Referenced by brixautofs_main().
af_log()
static void af_log (const char * fmt, ...) static
Definition at line 165 of file brixautofs.c.
Referenced by af_ensure_repo(), af_fuse_bringup(), af_idle_thread(), af_install_signals(), af_load_repo_config(), af_reap_children(), af_run(), af_setup_mount_farm(), and af_spawn_child().
af_mkdir_p()
static int af_mkdir_p (const char * path) static
Definition at line 198 of file brixautofs.c.
Referenced by af_setup_mount_farm(), and af_spawn_child().
af_opendir()
static int af_opendir (const char * path, struct fuse_file_info * fi) static
Definition at line 390 of file brixautofs.c.
af_opts_o_list()
static void af_opts_o_list (char * list, autofs_opts_t * o) static
Definition at line 602 of file brixautofs.c.
References autofs_opts_t::allow_other, autofs_opts_t::cache_base, autofs_opts_t::fuse_extra, autofs_opts_t::idle_s, autofs_opts_t::mnt_base, autofs_opts_t::repos, and autofs_opts_t::spawn_timeout_s.
Referenced by af_parse_opts().
af_parse_opts()
static void af_parse_opts (int argc, char ** argv, int start, autofs_opts_t * o) static
Definition at line 622 of file brixautofs.c.
References af_opts_o_list(), autofs_opts_t::cache_base, autofs_opts_t::debug, autofs_opts_t::foreground, autofs_opts_t::idle_s, and autofs_opts_t::spawn_timeout_s.
Referenced by brixautofs_main().
af_readdir()
static int af_readdir (const char * path, void * buf, fuse_fill_dir_t fill, off_t off, struct fuse_file_info * fi, enum fuse_readdir_flags flags) static
Definition at line 447 of file brixautofs.c.
References af_fill_mounted(), af_ghost_name(), af_seen_has(), BRIXAUTOFS_FQRN_MAX, BRIXAUTOFS_MAX_REPOS, brixautofs_valid_fqrn(), and name.
af_readlink()
static int af_readlink (const char * path, char * buf, size_t cap) static
Definition at line 379 of file brixautofs.c.
References af_child_path(), af_ensure_repo(), and name.
af_reap_children()
static void af_reap_children (void) static
Definition at line 492 of file brixautofs.c.
References af_child_path(), af_is_mounted(), af_log(), af_umount_path(), brixautofs_find_pid_locked(), BRIXAUTOFS_FQRN_MAX, brixautofs_release_locked(), brixautofs_slot_t::fqrn, g_af, brixautofs_table_t::mu, autofs_state_t::shutting_down, brixautofs_table_t::slot, and autofs_state_t::tab.
Referenced by af_control_thread().
af_repos_nth_token()
static int af_repos_nth_token (const char * list, int idx, char * out, size_t outsz) static
Definition at line 400 of file brixautofs.c.
References s, and tok.
Referenced by af_ghost_name().
af_run()
static int af_run (void) static
Definition at line 786 of file brixautofs.c.
References af_control_thread(), af_idle_thread(), af_log(), af_teardown_children(), close(), autofs_state_t::etc, autofs_state_t::fuse, g_af, autofs_opts_t::idle_s, autofs_state_t::mnt, autofs_state_t::o, autofs_state_t::sigpipe, and autofs_state_t::strict.
Referenced by brixautofs_main().
af_scan_configured()
static void af_scan_configured (const char * etc_root) static
Definition at line 647 of file brixautofs.c.
References BRIXAUTOFS_FQRN_MAX, BRIXAUTOFS_MAX_REPOS, brixautofs_valid_fqrn(), g_af, autofs_state_t::ghost, name, and autofs_state_t::nghost.
Referenced by af_load_repo_config().
af_seen_has()
static int af_seen_has (char seen[][256], int nseen, const char * name) static
Definition at line 428 of file brixautofs.c.
References name.
Referenced by af_readdir().
af_setup_mount_farm()
static int af_setup_mount_farm (void) static
Definition at line 670 of file brixautofs.c.
References af_log(), af_mkdir_p(), autofs_opts_t::cache_base, autofs_state_t::farm, g_af, autofs_state_t::mnt, autofs_opts_t::mnt_base, autofs_state_t::o, and PATH_MAX.
Referenced by brixautofs_main().
af_signal()
static void af_signal (int sig) static
Definition at line 484 of file brixautofs.c.
References c, g_af, and autofs_state_t::sigpipe.
Referenced by af_install_signals().
af_spawn_child()
static pid_t af_spawn_child (const char * fqrn) static
Definition at line 254 of file brixautofs.c.
References af_child_opts(), af_child_path(), af_is_mounted(), af_log(), af_mkdir_p(), af_umount_path(), g_af, autofs_state_t::o, open(), and autofs_opts_t::spawn_timeout_s.
Referenced by af_ensure_repo().
af_teardown_children()
static void af_teardown_children (void) static
Definition at line 516 of file brixautofs.c.
References af_child_path(), af_umount_path(), BRIXAUTOFS_FQRN_MAX, BRIXAUTOFS_FREE, BRIXAUTOFS_MAX_REPOS, brixautofs_release_locked(), brixautofs_slot_t::fqrn, g_af, brixautofs_table_t::mu, brixautofs_slot_t::pid, autofs_state_t::shutting_down, brixautofs_table_t::slot, brixautofs_slot_t::st, and autofs_state_t::tab.
Referenced by af_control_thread(), and af_run().
af_umount_path()
static int af_umount_path (const char * path) static
Definition at line 213 of file brixautofs.c.
References af_is_mounted(), and open().
Referenced by af_control_thread(), af_reap_children(), af_spawn_child(), and af_teardown_children().
brixautofs_claim_locked()
int brixautofs_claim_locked (brixautofs_table_t * t, const char * fqrn)
Definition at line 86 of file brixautofs.c.
References BRIXAUTOFS_FREE, BRIXAUTOFS_MAX_REPOS, BRIXAUTOFS_MOUNTING, brixautofs_slot_t::fqrn, brixautofs_slot_t::pid, brixautofs_table_t::slot, and brixautofs_slot_t::st.
Referenced by af_ensure_repo(), and test_table().
brixautofs_commit_locked()
void brixautofs_commit_locked (brixautofs_table_t * t, int idx, pid_t pid)
Definition at line 97 of file brixautofs.c.
References BRIXAUTOFS_MOUNTED, brixautofs_slot_t::pid, brixautofs_table_t::slot, and brixautofs_slot_t::st.
Referenced by af_ensure_repo(), and test_table().
brixautofs_find_locked()
int brixautofs_find_locked (brixautofs_table_t * t, const char * fqrn)
Definition at line 79 of file brixautofs.c.
References BRIXAUTOFS_FREE, BRIXAUTOFS_MAX_REPOS, brixautofs_slot_t::fqrn, brixautofs_table_t::slot, and brixautofs_slot_t::st.
Referenced by af_ensure_repo(), and test_table().
brixautofs_find_pid_locked()
int brixautofs_find_pid_locked (brixautofs_table_t * t, pid_t pid)
Definition at line 106 of file brixautofs.c.
References BRIXAUTOFS_FREE, BRIXAUTOFS_MAX_REPOS, brixautofs_slot_t::pid, brixautofs_table_t::slot, and brixautofs_slot_t::st.
Referenced by af_reap_children(), and test_table().
brixautofs_main()
int brixautofs_main (int argc, char ** argv)
Definition at line 807 of file brixautofs.c.
References af_fuse_bringup(), af_install_signals(), af_load_repo_config(), af_parse_opts(), af_run(), af_setup_mount_farm(), brixautofs_table_init(), autofs_state_t::etc, g_af, autofs_state_t::mnt, autofs_state_t::o, and autofs_state_t::tab.
Referenced by main().
brixautofs_release_locked()
void brixautofs_release_locked (brixautofs_table_t * t, int idx)
Definition at line 102 of file brixautofs.c.
References brixautofs_table_t::slot.
Referenced by af_ensure_repo(), af_reap_children(), af_teardown_children(), and test_table().
brixautofs_repo_listed()
int brixautofs_repo_listed (const char * list, const char * fqrn)
Definition at line 61 of file brixautofs.c.
References tok.
Referenced by af_admit(), and test_repo_listed().
brixautofs_table_init()
void brixautofs_table_init (brixautofs_table_t * t)
Definition at line 74 of file brixautofs.c.
References brixautofs_table_t::mu, and brixautofs_table_t::slot.
Referenced by brixautofs_main(), and test_table().
brixautofs_valid_fqrn()
int brixautofs_valid_fqrn (const char * name)
Definition at line 37 of file brixautofs.c.
References BRIXAUTOFS_FQRN_MAX, c, and name.
Referenced by af_admit(), af_readdir(), af_scan_configured(), and test_valid_fqrn().
Variable Documentation
af_ops
const struct fuse_operations af_ops static
Initial value:
= {
    .getattr  = af_getattr,
    .readlink = af_readlink,
    .opendir  = af_opendir,
    .readdir  = af_readdir,
}
Definition at line 475 of file brixautofs.c.
Referenced by af_fuse_bringup().
g_af
autofs_state_t g_af static
Definition at line 163 of file brixautofs.c.
Referenced by af_admit(), af_child_opts(), af_child_path(), af_control_thread(), af_ensure_repo(), af_fill_mounted(), af_fuse_bringup(), af_ghost_name(), af_idle_thread(), af_install_signals(), af_load_repo_config(), af_reap_children(), af_run(), af_scan_configured(), af_setup_mount_farm(), af_signal(), af_spawn_child(), af_teardown_children(), and brixautofs_main().