nginx-xrootd: client/lib/brix_auth.h File Reference
brix_auth.h File Reference
Data Structures
struct brix_token_meta
Functions
int brix_authenticate (brix_conn *c, const char *seclist, const brix_opts *o, brix_status *st)
void brix_auth_explain (brix_conn *c, const brix_opts *o, FILE *out)
char * brix_token_discover (void)
void brix_token_explain (const char *jwt, FILE *out)
void brix_gsi_cert_explain (const char *proxy_path, FILE *out)
void brix_token_meta_get (const char *jwt, brix_token_meta *m)
int brix_cred_diagnose (int want_write, const char *prefix, FILE *out)
void brix_cred_hint_for_status (const brix_status *st, int want_write, FILE *out)
void brix_cred_hint_for_status_url (const brix_status *st, int want_write, FILE *out, const char *url_str)
int brix_cred_autorefresh (int want_write, const char *oidc_account, int verbose, FILE *out)
int brix_sigver_maybe (brix_conn *c, const uint8_t *hdr24, const void *payload, uint32_t plen, brix_status *st)
Function Documentation
brix_auth_explain()
void brix_auth_explain (brix_conn * c, const brix_opts * o, FILE * out)
Definition at line 241 of file auth.c.
References brix_opts::auth_force, brix_sec_proto_advertised(), build_module_list(), c, brix_sec_module::have_creds, and brix_sec_module::name.
Referenced by brix_explain_conn().
brix_authenticate()
int brix_authenticate (brix_conn * c, const char * seclist, const brix_opts * o, brix_status * st)
Definition at line 198 of file auth.c.
References brix_opts::auth_force, auth_warn_fallback(), brix_status_set(), build_module_list(), c, brix_opts::force_anon, module_candidate(), brix_sec_module::name, run_module(), and XRDC_EAUTH.
Referenced by do_login().
brix_cred_autorefresh()
int brix_cred_autorefresh (int want_write, const char * oidc_account, int verbose, FILE * out)
Definition at line 252 of file credrefresh.c.
References refresh_bearer_token(), and refresh_gsi_proxy().
Referenced by build_and_preflight_credentials(), and xrd_login().
brix_cred_diagnose()
int brix_cred_diagnose (int want_write, const char * prefix, FILE * out)
Definition at line 437 of file credinfo.c.
References diagnose_proxy(), and diagnose_token().
Referenced by brix_cred_hint_for_status_url(), build_and_preflight_credentials(), doctor_report_creds(), and xrd_login().
brix_cred_hint_for_status()
void brix_cred_hint_for_status (const brix_status * st, int want_write, FILE * out)
Definition at line 487 of file credinfo.c.
References brix_cred_hint_for_status_url().
Referenced by do_rm().
brix_cred_hint_for_status_url()
void brix_cred_hint_for_status_url (const brix_status * st, int want_write, FILE * out, const char * url_str)
Definition at line 473 of file credinfo.c.
References brix_cred_diagnose(), brix_hint_doctor_referral(), brix_status::kxr, kXR_AuthFailed, and kXR_NotAuthorized.
Referenced by brix_cred_hint_for_status(), brix_report_err(), xrdcp_hint_failed_source(), xrdfs_op_hints(), and xrdfs_web_hints().
brix_gsi_cert_explain()
void brix_gsi_cert_explain (const char * proxy_path, FILE * out)
Definition at line 267 of file credinfo.c.
References brix_credfile_bio(), proxy_path(), VOMS_AC_OID, and voms_scan().
Referenced by chk_probe_cred_validity(), doctor_report_creds(), explain_env_credentials(), remote_doctor_report_creds(), and xrd_whoami().
brix_sigver_maybe()
int brix_sigver_maybe (brix_conn * c, const uint8_t * hdr24, const void * payload, uint32_t plen, brix_status * st)
Definition at line 31 of file sigver.c.
References brix_gsi_sigver_hmac(), brix_gsi_sigver_required(), brix_status_set(), brix_write_full(), c, ClientSigverRequest::dlen, xrdw_sigver_req_t::expectrid, kXR_SHA256_sig, kXR_sigver, ClientSigverRequest::requestid, ClientSigverRequest::streamid, xrd_get_u16_be(), XRDC_EAUTH, and xrdw_sigver_req_pack().
Referenced by brix_send_ext().
brix_token_discover()
char * brix_token_discover (void)
Definition at line 81 of file sec_token.c.
References rstrip(), and slurp().
Referenced by auth_suite_token_probes(), chk_probe_cred_validity(), diagnose_token(), doctor_discover_creds(), explain_env_credentials(), obtain_token(), remote_doctor_report_creds(), token_first(), token_have(), token_needs_refresh(), xrd_run_battery(), and xrd_whoami().
brix_token_explain()
void brix_token_explain (const char * jwt, FILE * out)
Definition at line 73 of file credinfo.c.
References decode_payload_json(), and json_str().
Referenced by chk_probe_cred_validity(), doctor_report_creds(), explain_env_credentials(), remote_doctor_report_creds(), and xrd_whoami().
brix_token_meta_get()
void brix_token_meta_get (const char * jwt, brix_token_meta * m)
Definition at line 213 of file credinfo.c.
References decode_payload_json(), token_meta_apply_exp(), token_meta_apply_scope(), and brix_token_meta::valid.
Referenced by auth_suite_token_probes(), bearer_acquire(), diagnose_token(), and token_needs_refresh().