nginx-xrootd: client/apps/fs/brixautofs.h File Reference
brixautofs.h File Reference
#include <pthread.h>
#include <sys/types.h>
Data Structures
struct brixautofs_slot_t
struct brixautofs_table_t
Macros
#define BRIXAUTOFS_MAX_REPOS 128
#define BRIXAUTOFS_FQRN_MAX 256 /* fqrn buffer incl. NUL (name <= 255) */
Enumerations
enum brixautofs_state_t { BRIXAUTOFS_FREE = 0 , BRIXAUTOFS_MOUNTING , BRIXAUTOFS_MOUNTED }
Functions
int brixautofs_valid_fqrn (const char *name)
int brixautofs_repo_listed (const char *list, const char *fqrn)
void brixautofs_table_init (brixautofs_table_t *t)
int brixautofs_find_locked (brixautofs_table_t *t, const char *fqrn)
int brixautofs_claim_locked (brixautofs_table_t *t, const char *fqrn)
void brixautofs_commit_locked (brixautofs_table_t *t, int idx, pid_t pid)
void brixautofs_release_locked (brixautofs_table_t *t, int idx)
int brixautofs_find_pid_locked (brixautofs_table_t *t, pid_t pid)
Macro Definition Documentation
BRIXAUTOFS_FQRN_MAX
#define BRIXAUTOFS_FQRN_MAX 256 /* fqrn buffer incl. NUL (name <= 255) */
Definition at line 17 of file brixautofs.h.
BRIXAUTOFS_MAX_REPOS
#define BRIXAUTOFS_MAX_REPOS 128
Definition at line 16 of file brixautofs.h.
Enumeration Type Documentation
brixautofs_state_t
enum brixautofs_state_t
Enumerator
BRIXAUTOFS_FREE
BRIXAUTOFS_MOUNTING
BRIXAUTOFS_MOUNTED
Definition at line 19 of file brixautofs.h.
Function Documentation
brixautofs_claim_locked()
int brixautofs_claim_locked (brixautofs_table_t * t, const char * fqrn)
Definition at line 86 of file brixautofs.c.
References BRIXAUTOFS_FREE, BRIXAUTOFS_MAX_REPOS, BRIXAUTOFS_MOUNTING, brixautofs_slot_t::fqrn, brixautofs_slot_t::pid, brixautofs_table_t::slot, and brixautofs_slot_t::st.
Referenced by af_ensure_repo(), and test_table().
brixautofs_commit_locked()
void brixautofs_commit_locked (brixautofs_table_t * t, int idx, pid_t pid)
Definition at line 97 of file brixautofs.c.
References BRIXAUTOFS_MOUNTED, brixautofs_slot_t::pid, brixautofs_table_t::slot, and brixautofs_slot_t::st.
Referenced by af_ensure_repo(), and test_table().
brixautofs_find_locked()
int brixautofs_find_locked (brixautofs_table_t * t, const char * fqrn)
Definition at line 79 of file brixautofs.c.
References BRIXAUTOFS_FREE, BRIXAUTOFS_MAX_REPOS, brixautofs_slot_t::fqrn, brixautofs_table_t::slot, and brixautofs_slot_t::st.
Referenced by af_ensure_repo(), and test_table().
brixautofs_find_pid_locked()
int brixautofs_find_pid_locked (brixautofs_table_t * t, pid_t pid)
Definition at line 106 of file brixautofs.c.
References BRIXAUTOFS_FREE, BRIXAUTOFS_MAX_REPOS, brixautofs_slot_t::pid, brixautofs_table_t::slot, and brixautofs_slot_t::st.
Referenced by af_reap_children(), and test_table().
brixautofs_release_locked()
void brixautofs_release_locked (brixautofs_table_t * t, int idx)
Definition at line 102 of file brixautofs.c.
References brixautofs_table_t::slot.
Referenced by af_ensure_repo(), af_reap_children(), af_teardown_children(), and test_table().
brixautofs_repo_listed()
int brixautofs_repo_listed (const char * list, const char * fqrn)
Definition at line 61 of file brixautofs.c.
References tok.
Referenced by af_admit(), and test_repo_listed().
brixautofs_table_init()
void brixautofs_table_init (brixautofs_table_t * t)
Definition at line 74 of file brixautofs.c.
References brixautofs_table_t::mu, and brixautofs_table_t::slot.
Referenced by brixautofs_main(), and test_table().
brixautofs_valid_fqrn()
int brixautofs_valid_fqrn (const char * name)
Definition at line 37 of file brixautofs.c.
References BRIXAUTOFS_FQRN_MAX, c, and name.
Referenced by af_admit(), af_readdir(), af_scan_configured(), and test_valid_fqrn().