nginx-xrootd: client/apps/fs/brixcvmfs_rw.c File Reference
brixcvmfs_rw.c File Reference
#include "brixcvmfs_internal.h"
#include "fs/overlay.h"
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <dirent.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
Data Structures
struct ov_loc_t
struct rw_lowdir_t
struct rw_lowcount_t
Macros
#define _GNU_SOURCE
Typedefs
typedef int(* rw_meta_fn) (const char *rel, void *arg)
Functions
static const char * ov_rel (const char *path)
static const char * pt_rel (const char *path)
static const char * pt_at (const char *pr)
static const char * path_leaf (const char *path)
static int rw_reserved (const char *path)
static int lower_resolve (const char *path, cvmfs_dirent_t *e)
static int lower_is_dir (const cvmfs_dirent_t *e)
static int lower_is_file (const cvmfs_dirent_t *e)
static int rw_classify (const char *path, struct stat *st, brix_ov_state *s)
static int merged_exists (const char *path)
static int ov_locate (const char *path, ov_loc_t *l)
static int ov_locate_visible (const char *path, ov_loc_t *l)
static int rw_read_lower (void *ud, const char *rel, uint64_t off, size_t len, unsigned char *buf, size_t *outlen)
static mode_t rw_lower_dir_mode (void *ud, const char *rel_dir)
static int rw_ensure_parents (const char *path)
static int rw_copyup (const char *path, const cvmfs_dirent_t *e)
static int fh_store (struct fuse_file_info *fi, int fd)
static int rw_want_write (int oflags)
static int rw_open_upper (const char *path, const struct stat *st, int oflags, mode_t mode, struct fuse_file_info *fi)
static int rw_open_create (const char *path, int oflags, mode_t mode, struct fuse_file_info *fi)
static int rw_open_lower (const char *path, const cvmfs_dirent_t *e, int oflags, mode_t mode, struct fuse_file_info *fi)
static int rw_open_common (const char *path, int oflags, mode_t mode, struct fuse_file_info *fi)
static int rw_open (const char *path, struct fuse_file_info *fi)
static int rw_create (const char *path, mode_t mode, struct fuse_file_info *fi)
static int rw_mknod (const char *path, mode_t mode, dev_t dev)
static int rw_read (const char *path, char *buf, size_t size, off_t off, struct fuse_file_info *fi)
static int rw_write (const char *path, const char *buf, size_t size, off_t off, struct fuse_file_info *fi)
static int rw_release (const char *path, struct fuse_file_info *fi)
static int rw_fsync (const char *path, int datasync, struct fuse_file_info *fi)
static int rw_truncate (const char *path, off_t len, struct fuse_file_info *fi)
static int rw_getattr (const char *path, struct stat *st, struct fuse_file_info *fi)
static int pt_readdir (const char *pr, void *buf, fuse_fill_dir_t filler)
static void rw_lowdir_emit (const cvmfs_dirent_t *e, void *ud)
static int rw_readdir (const char *path, void *buf, fuse_fill_dir_t filler, off_t off, struct fuse_file_info *fi, enum fuse_readdir_flags fl)
static int rw_mkdir (const char *path, mode_t mode)
static int rw_unlink (const char *path)
static void rw_lowcount_cb (const cvmfs_dirent_t *e, void *ud)
static int rw_rmdir_shape (const char *path, ov_loc_t *l, int *lower_dir)
static int rw_dir_merged_nonempty (const char *path, int lower_dir, int *nonempty)
static int rw_rmdir (const char *path)
static int rw_rename_preflight (const char *from, const char *to, unsigned int flags)
static int rw_rename_target_ok (const char *to)
static int rw_rename_commit (const char *from, const char *to, int mask_from)
static int rw_rename_dir (const char *from, const char *to, int from_upper_dir, int from_lower_dir)
static int rw_rename_file (const char *from, const char *to, const ov_loc_t *f)
static int rw_rename (const char *from, const char *to, unsigned int flags)
static int rw_symlink (const char *target, const char *path)
static int rw_readlink (const char *path, char *buf, size_t size)
static int rw_meta_apply (const char *path, rw_meta_fn apply, void *arg)
static int rw_apply_chmod (const char *rel, void *arg)
static int rw_chmod (const char *path, mode_t mode, struct fuse_file_info *fi)
static int rw_chown (const char *path, uid_t uid, gid_t gid, struct fuse_file_info *fi)
static int rw_apply_utimens (const char *rel, void *arg)
static int rw_utimens (const char *path, const struct timespec tv[2], struct fuse_file_info *fi)
static int rw_statfs (const char *path, struct statvfs *sv)
static const char * rw_overlay_xattr (const char *path)
static int rw_getxattr (const char *path, const char *name, char *value, size_t size)
static int rw_listxattr (const char *path, char *list, size_t size)
int brixcvmfs_setup_rw (const char *mnt, const char *writes_override)
void brixcvmfs_teardown_rw (void)
int brixcvmfs_main (int argc, char **argv)
int brixcvmfs_rw_main (int argc, char **argv)
Variables
static brix_overlay g_ov
static int g_writes_fd = -1
const struct fuse_operations brixcvmfs_rw_ops
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 21 of file brixcvmfs_rw.c.
Typedef Documentation
rw_meta_fn
typedef int(* rw_meta_fn) (const char *rel, void *arg)
Definition at line 706 of file brixcvmfs_rw.c.
Function Documentation
brixcvmfs_main()
int brixcvmfs_main (int argc, char ** argv)
Definition at line 1056 of file brixcvmfs.c.
Referenced by brixcvmfs_rw_main().
brixcvmfs_rw_main()
int brixcvmfs_rw_main (int argc, char ** argv)
Definition at line 875 of file brixcvmfs_rw.c.
References brixcvmfs_main(), and brixcvmfs_rw.
Referenced by main().
brixcvmfs_setup_rw()
int brixcvmfs_setup_rw (const char * mnt, const char * writes_override)
Definition at line 845 of file brixcvmfs_rw.c.
References BRIX_OV_DIRNAME, brix_overlay_init(), close(), g_ov, g_writes_fd, and open().
Referenced by brixcvmfs_setup_rw_overlay().
brixcvmfs_teardown_rw()
void brixcvmfs_teardown_rw (void)
Definition at line 866 of file brixcvmfs_rw.c.
References brix_overlay_close(), close(), g_ov, and g_writes_fd.
Referenced by brixcvmfs_mount_run().
fh_store()
static int fh_store (struct fuse_file_info * fi, int fd) static
Definition at line 199 of file brixcvmfs_rw.c.
Referenced by rw_open_common(), rw_open_create(), rw_open_lower(), and rw_open_upper().
lower_is_dir()
static int lower_is_dir (const cvmfs_dirent_t * e) static
Definition at line 81 of file brixcvmfs_rw.c.
Referenced by rw_lower_dir_mode(), rw_meta_apply(), rw_mkdir(), rw_open_lower(), rw_rename(), rw_rename_target_ok(), rw_rmdir_shape(), rw_truncate(), and rw_unlink().
lower_is_file()
static int lower_is_file (const cvmfs_dirent_t * e) static
Definition at line 82 of file brixcvmfs_rw.c.
Referenced by rw_meta_apply(), rw_open_lower(), and rw_rename_file().
lower_resolve()
static int lower_resolve (const char * path, cvmfs_dirent_t * e) static
Definition at line 76 of file brixcvmfs_rw.c.
References brixcvmfs_cat_path(), brixcvmfs_client(), and brixcvmfs_mono_now().
Referenced by merged_exists(), ov_locate(), ov_locate_visible(), rw_lower_dir_mode(), rw_meta_apply(), rw_mkdir(), rw_overlay_xattr(), rw_rmdir_shape(), and rw_truncate().
merged_exists()
static int merged_exists (const char * path) static
Definition at line 90 of file brixcvmfs_rw.c.
References BRIX_OV_MASKED, BRIX_OV_UPPER, lower_resolve(), rw_classify(), s, and stat().
Referenced by rw_mkdir(), rw_rename_preflight(), and rw_symlink().
ov_locate()
static int ov_locate (const char * path, ov_loc_t * l) static
Definition at line 124 of file brixcvmfs_rw.c.
References BRIX_OV_MASKED, ov_loc_t::e, ov_loc_t::lower, lower_resolve(), rw_classify(), ov_loc_t::s, and ov_loc_t::st.
Referenced by rw_rename(), and rw_unlink().
ov_locate_visible()
static int ov_locate_visible (const char * path, ov_loc_t * l) static
Definition at line 141 of file brixcvmfs_rw.c.
References BRIX_OV_NONE, ov_loc_t::e, ov_loc_t::lower, lower_resolve(), rw_classify(), ov_loc_t::s, and ov_loc_t::st.
Referenced by rw_open_common(), and rw_rename_target_ok().
ov_rel()
static const char * ov_rel (const char * path) static
Definition at line 44 of file brixcvmfs_rw.c.
Referenced by rw_classify(), rw_copyup(), rw_dir_merged_nonempty(), rw_ensure_parents(), rw_meta_apply(), rw_mkdir(), rw_open_create(), rw_open_lower(), rw_open_upper(), rw_readdir(), rw_readlink(), rw_rename_commit(), rw_rename_dir(), rw_rmdir(), rw_symlink(), rw_truncate(), and rw_unlink().
path_leaf()
static const char * path_leaf (const char * path) static
Definition at line 63 of file brixcvmfs_rw.c.
References s.
Referenced by rw_reserved().
pt_at()
static const char * pt_at (const char * pr) static
Definition at line 60 of file brixcvmfs_rw.c.
Referenced by pt_readdir(), rw_chmod(), rw_getattr(), rw_open_common(), rw_readlink(), rw_truncate(), and rw_utimens().
pt_readdir()
static int pt_readdir (const char * pr, void * buf, fuse_fill_dir_t filler) static
Definition at line 379 of file brixcvmfs_rw.c.
References close(), g_writes_fd, openat(), and pt_at().
Referenced by rw_readdir().
pt_rel()
static const char * pt_rel (const char * path) static
Definition at line 50 of file brixcvmfs_rw.c.
References BRIX_OV_DIRNAME.
Referenced by rw_chmod(), rw_getattr(), rw_getxattr(), rw_mkdir(), rw_open_common(), rw_readdir(), rw_readlink(), rw_rename(), rw_rmdir(), rw_symlink(), rw_truncate(), rw_unlink(), and rw_utimens().
rw_apply_chmod()
static int rw_apply_chmod (const char * rel, void * arg) static
Definition at line 734 of file brixcvmfs_rw.c.
References brix_overlay_chmod(), and g_ov.
Referenced by rw_chmod().
rw_apply_utimens()
static int rw_apply_utimens (const char * rel, void * arg) static
Definition at line 751 of file brixcvmfs_rw.c.
References brix_overlay_utimens(), and g_ov.
Referenced by rw_utimens().
rw_chmod()
static int rw_chmod (const char * path, mode_t mode, struct fuse_file_info * fi) static
Definition at line 738 of file brixcvmfs_rw.c.
References g_writes_fd, pt_at(), pt_rel(), rw_apply_chmod(), and rw_meta_apply().
rw_chown()
static int rw_chown (const char * path, uid_t uid, gid_t gid, struct fuse_file_info * fi) static
Definition at line 745 of file brixcvmfs_rw.c.
rw_classify()
static int rw_classify (const char * path, struct stat * st, brix_ov_state * s) static
Definition at line 85 of file brixcvmfs_rw.c.
References brix_overlay_classify(), g_ov, ov_rel(), and s.
Referenced by merged_exists(), ov_locate(), ov_locate_visible(), rw_getattr(), rw_getxattr(), rw_meta_apply(), rw_overlay_xattr(), rw_readdir(), rw_readlink(), rw_rmdir_shape(), and rw_truncate().
rw_copyup()
static int rw_copyup (const char * path, const cvmfs_dirent_t * e) static
Definition at line 186 of file brixcvmfs_rw.c.
References brix_overlay_copyup(), g_ov, ov_rel(), rw_ensure_parents(), rw_read_lower(), and stat().
Referenced by rw_meta_apply(), rw_open_lower(), rw_rename_file(), and rw_truncate().
rw_create()
static int rw_create (const char * path, mode_t mode, struct fuse_file_info * fi) static
Definition at line 289 of file brixcvmfs_rw.c.
References rw_open_common().
rw_dir_merged_nonempty()
static int rw_dir_merged_nonempty (const char * path, int lower_dir, int * nonempty) static
Definition at line 531 of file brixcvmfs_rw.c.
References brix_ov_nameset_at(), brix_ov_nameset_free(), brix_overlay_read_upper(), brixcvmfs_cat_path(), brixcvmfs_client(), c, g_ov, name, ov_rel(), and rw_lowcount_cb().
Referenced by rw_rmdir().
rw_ensure_parents()
static int rw_ensure_parents (const char * path) static
Definition at line 173 of file brixcvmfs_rw.c.
References brix_overlay_mkdirs(), g_ov, ov_rel(), and rw_lower_dir_mode().
Referenced by rw_copyup(), rw_meta_apply(), rw_mkdir(), rw_open_create(), rw_rename_commit(), and rw_symlink().
rw_fsync()
static int rw_fsync (const char * path, int datasync, struct fuse_file_info * fi) static
Definition at line 326 of file brixcvmfs_rw.c.
rw_getattr()
static int rw_getattr (const char * path, struct stat * st, struct fuse_file_info * fi) static
Definition at line 365 of file brixcvmfs_rw.c.
References BRIX_OV_MASKED, BRIX_OV_UPPER, brixcvmfs_op_getattr(), fstatat(), g_writes_fd, pt_at(), pt_rel(), rw_classify(), and s.
rw_getxattr()
static int rw_getxattr (const char * path, const char * name, char * value, size_t size) static
Definition at line 787 of file brixcvmfs_rw.c.
References BRIX_OV_MASKED, BRIX_OV_UPPER, brixcvmfs_op_getxattr(), name, pt_rel(), rw_classify(), rw_overlay_xattr(), s, and stat().
rw_listxattr()
static int rw_listxattr (const char * path, char * list, size_t size) static
Definition at line 806 of file brixcvmfs_rw.c.
References brixcvmfs_op_listxattr().
rw_lowcount_cb()
static void rw_lowcount_cb (const cvmfs_dirent_t * e, void * ud) static
Definition at line 495 of file brixcvmfs_rw.c.
References brix_ov_nameset_flag(), c, and rw_lowcount_t::nonempty.
Referenced by rw_dir_merged_nonempty().
rw_lowdir_emit()
static void rw_lowdir_emit (const cvmfs_dirent_t * e, void * ud) static
Definition at line 401 of file brixcvmfs_rw.c.
References brix_ov_nameset_flag(), c, and rw_lowdir_t::filler.
Referenced by rw_readdir().
rw_lower_dir_mode()
static mode_t rw_lower_dir_mode (void * ud, const char * rel_dir) static
Definition at line 162 of file brixcvmfs_rw.c.
References lower_is_dir(), and lower_resolve().
Referenced by rw_ensure_parents(), and rw_meta_apply().
rw_meta_apply()
static int rw_meta_apply (const char * path, rw_meta_fn apply, void * arg) static
Definition at line 708 of file brixcvmfs_rw.c.
References BRIX_OV_MASKED, BRIX_OV_UPPER, brix_overlay_mkdirs(), g_ov, lower_is_dir(), lower_is_file(), lower_resolve(), ov_rel(), rw_classify(), rw_copyup(), rw_ensure_parents(), rw_lower_dir_mode(), rw_reserved(), s, and stat().
Referenced by rw_chmod(), and rw_utimens().
rw_mkdir()
static int rw_mkdir (const char * path, mode_t mode) static
Definition at line 451 of file brixcvmfs_rw.c.
References brix_overlay_mkdir(), brix_overlay_set_opaque(), brix_overlay_whiteout_clear(), g_ov, g_writes_fd, lower_is_dir(), lower_resolve(), merged_exists(), ov_rel(), pt_rel(), rw_ensure_parents(), and rw_reserved().
rw_mknod()
static int rw_mknod (const char * path, mode_t mode, dev_t dev) static
Definition at line 293 of file brixcvmfs_rw.c.
References close(), and rw_open_common().
rw_open()
static int rw_open (const char * path, struct fuse_file_info * fi) static
Definition at line 285 of file brixcvmfs_rw.c.
References rw_open_common().
rw_open_common()
static int rw_open_common (const char * path, int oflags, mode_t mode, struct fuse_file_info * fi) static
Definition at line 267 of file brixcvmfs_rw.c.
References BRIX_OV_UPPER, ov_loc_t::e, fh_store(), g_writes_fd, ov_loc_t::lower, openat(), ov_locate_visible(), pt_at(), pt_rel(), rw_open_create(), rw_open_lower(), rw_open_upper(), rw_reserved(), rw_want_write(), ov_loc_t::s, and ov_loc_t::st.
Referenced by rw_create(), rw_mknod(), and rw_open().
rw_open_create()
static int rw_open_create (const char * path, int oflags, mode_t mode, struct fuse_file_info * fi) static
Definition at line 229 of file brixcvmfs_rw.c.
References brix_overlay_open(), brix_overlay_whiteout_clear(), fh_store(), g_ov, ov_rel(), and rw_ensure_parents().
Referenced by rw_open_common().
rw_open_lower()
static int rw_open_lower (const char * path, const cvmfs_dirent_t * e, int oflags, mode_t mode, struct fuse_file_info * fi) static
Definition at line 247 of file brixcvmfs_rw.c.
References brix_overlay_open(), brixcvmfs_op_open(), fh_store(), g_ov, lower_is_dir(), lower_is_file(), ov_rel(), rw_copyup(), and rw_want_write().
Referenced by rw_open_common().
rw_open_upper()
static int rw_open_upper (const char * path, const struct stat * st, int oflags, mode_t mode, struct fuse_file_info * fi) static
Definition at line 215 of file brixcvmfs_rw.c.
References brix_overlay_open(), fh_store(), g_ov, and ov_rel().
Referenced by rw_open_common().
rw_overlay_xattr()
static const char * rw_overlay_xattr (const char * path) static
Definition at line 776 of file brixcvmfs_rw.c.
References BRIX_OV_MASKED, BRIX_OV_UPPER, lower_resolve(), rw_classify(), s, and stat().
Referenced by rw_getxattr().
rw_read()
static int rw_read (const char * path, char * buf, size_t size, off_t off, struct fuse_file_info * fi) static
Definition at line 303 of file brixcvmfs_rw.c.
References brixcvmfs_op_read(), and pread().
rw_read_lower()
static int rw_read_lower (void * ud, const char * rel, uint64_t off, size_t len, unsigned char * buf, size_t * outlen) static
Definition at line 151 of file brixcvmfs_rw.c.
References brixcvmfs_client(), and brixcvmfs_mono_now().
Referenced by rw_copyup().
rw_readdir()
static int rw_readdir (const char * path, void * buf, fuse_fill_dir_t filler, off_t off, struct fuse_file_info * fi, enum fuse_readdir_flags fl) static
Definition at line 408 of file brixcvmfs_rw.c.
References BRIX_OV_DIRNAME, BRIX_OV_MASKED, brix_ov_nameset_at(), brix_ov_nameset_free(), BRIX_OV_UPPER, brix_overlay_read_upper(), brixcvmfs_cat_path(), brixcvmfs_client(), brixcvmfs_mono_now(), c, g_ov, name, ov_rel(), pt_readdir(), pt_rel(), rw_classify(), rw_lowdir_emit(), s, and stat().
rw_readlink()
static int rw_readlink (const char * path, char * buf, size_t size) static
Definition at line 685 of file brixcvmfs_rw.c.
References BRIX_OV_MASKED, BRIX_OV_UPPER, brix_overlay_readlink(), brixcvmfs_op_readlink(), g_ov, g_writes_fd, ov_rel(), pt_at(), pt_rel(), rw_classify(), s, and stat().
rw_release()
static int rw_release (const char * path, struct fuse_file_info * fi) static
Definition at line 320 of file brixcvmfs_rw.c.
References close().
rw_rename()
static int rw_rename (const char * from, const char * to, unsigned int flags) static
Definition at line 649 of file brixcvmfs_rw.c.
References BRIX_OV_MASKED, BRIX_OV_UPPER, ov_loc_t::e, g_writes_fd, ov_loc_t::lower, lower_is_dir(), ov_locate(), pt_rel(), rw_rename_dir(), rw_rename_file(), rw_rename_preflight(), rw_rename_target_ok(), ov_loc_t::s, and ov_loc_t::st.
rw_rename_commit()
static int rw_rename_commit (const char * from, const char * to, int mask_from) static
Definition at line 605 of file brixcvmfs_rw.c.
References brix_overlay_rename_upper(), brix_overlay_whiteout_clear(), brix_overlay_whiteout_set(), g_ov, ov_rel(), and rw_ensure_parents().
Referenced by rw_rename_dir(), and rw_rename_file().
rw_rename_dir()
static int rw_rename_dir (const char * from, const char * to, int from_upper_dir, int from_lower_dir) static
Definition at line 621 of file brixcvmfs_rw.c.
References brix_ov_nameset_free(), brix_overlay_read_upper(), g_ov, ov_rel(), and rw_rename_commit().
Referenced by rw_rename().
rw_rename_file()
static int rw_rename_file (const char * from, const char * to, const ov_loc_t * f) static
Definition at line 639 of file brixcvmfs_rw.c.
References BRIX_OV_NONE, ov_loc_t::e, ov_loc_t::lower, lower_is_file(), rw_copyup(), rw_rename_commit(), and ov_loc_t::s.
Referenced by rw_rename().
rw_rename_preflight()
static int rw_rename_preflight (const char * from, const char * to, unsigned int flags) static
Definition at line 581 of file brixcvmfs_rw.c.
References merged_exists(), RENAME_NOREPLACE, and rw_reserved().
Referenced by rw_rename().
rw_rename_target_ok()
static int rw_rename_target_ok (const char * to) static
Definition at line 589 of file brixcvmfs_rw.c.
References BRIX_OV_UPPER, ov_loc_t::e, ov_loc_t::lower, lower_is_dir(), ov_locate_visible(), ov_loc_t::s, and ov_loc_t::st.
Referenced by rw_rename().
rw_reserved()
static int rw_reserved (const char * path) static
Definition at line 69 of file brixcvmfs_rw.c.
References brix_ov_name_reserved(), and path_leaf().
Referenced by rw_meta_apply(), rw_mkdir(), rw_open_common(), rw_rename_preflight(), rw_rmdir(), rw_symlink(), rw_truncate(), and rw_unlink().
rw_rmdir()
static int rw_rmdir (const char * path) static
Definition at line 553 of file brixcvmfs_rw.c.
References BRIX_OV_UPPER, brix_overlay_rmdir_upper(), brix_overlay_whiteout_set(), g_ov, g_writes_fd, ov_rel(), pt_rel(), rw_dir_merged_nonempty(), rw_reserved(), rw_rmdir_shape(), and ov_loc_t::s.
rw_rmdir_shape()
static int rw_rmdir_shape (const char * path, ov_loc_t * l, int * lower_dir) static
Definition at line 510 of file brixcvmfs_rw.c.
References BRIX_OV_MASKED, BRIX_OV_NONE, BRIX_OV_UPPER, ov_loc_t::e, ov_loc_t::lower, lower_is_dir(), lower_resolve(), rw_classify(), ov_loc_t::s, and ov_loc_t::st.
Referenced by rw_rmdir().
rw_statfs()
static int rw_statfs (const char * path, struct statvfs * sv) static
Definition at line 767 of file brixcvmfs_rw.c.
References brixcvmfs_op_statfs(), and g_writes_fd.
rw_symlink()
static int rw_symlink (const char * target, const char * path) static
Definition at line 673 of file brixcvmfs_rw.c.
References brix_overlay_symlink(), brix_overlay_whiteout_clear(), g_ov, g_writes_fd, merged_exists(), ov_rel(), pt_rel(), rw_ensure_parents(), and rw_reserved().
rw_truncate()
static int rw_truncate (const char * path, off_t len, struct fuse_file_info * fi) static
Definition at line 333 of file brixcvmfs_rw.c.
References BRIX_OV_MASKED, BRIX_OV_UPPER, brix_overlay_truncate(), close(), g_ov, g_writes_fd, lower_is_dir(), lower_resolve(), openat(), ov_rel(), pt_at(), pt_rel(), rw_classify(), rw_copyup(), rw_reserved(), s, and stat().
rw_unlink()
static int rw_unlink (const char * path) static
Definition at line 469 of file brixcvmfs_rw.c.
References BRIX_OV_MASKED, BRIX_OV_UPPER, brix_overlay_unlink_upper(), brix_overlay_whiteout_set(), ov_loc_t::e, g_ov, g_writes_fd, ov_loc_t::lower, lower_is_dir(), ov_locate(), ov_rel(), pt_rel(), rw_reserved(), ov_loc_t::s, and ov_loc_t::st.
rw_utimens()
static int rw_utimens (const char * path, const struct timespec tv[2], struct fuse_file_info * fi) static
Definition at line 755 of file brixcvmfs_rw.c.
References g_writes_fd, pt_at(), pt_rel(), rw_apply_utimens(), and rw_meta_apply().
rw_want_write()
static int rw_want_write (int oflags) static
Definition at line 205 of file brixcvmfs_rw.c.
Referenced by rw_open_common(), and rw_open_lower().
rw_write()
static int rw_write (const char * path, const char * buf, size_t size, off_t off, struct fuse_file_info * fi) static
Definition at line 312 of file brixcvmfs_rw.c.
Variable Documentation
brixcvmfs_rw_ops
const struct fuse_operations brixcvmfs_rw_ops
Initial value:
= {
    .getattr   = rw_getattr,
    .readdir   = rw_readdir,
    .open      = rw_open,
    .create    = rw_create,
    .mknod     = rw_mknod,
    .read      = rw_read,
    .write     = rw_write,
    .release   = rw_release,
    .fsync     = rw_fsync,
    .truncate  = rw_truncate,
    .mkdir     = rw_mkdir,
    .unlink    = rw_unlink,
    .rmdir     = rw_rmdir,
    .rename    = rw_rename,
    .symlink   = rw_symlink,
    .readlink  = rw_readlink,
    .chmod     = rw_chmod,
    .chown     = rw_chown,
    .utimens   = rw_utimens,
    .statfs    = rw_statfs,
    .getxattr  = rw_getxattr,
    .listxattr = rw_listxattr,
}
Definition at line 820 of file brixcvmfs_rw.c.
Referenced by brixcvmfs_run_fuse(), and brixcvmfs_setup_rw_overlay().
g_ov
brix_overlay g_ov static
Definition at line 38 of file brixcvmfs_rw.c.
Referenced by brixcvmfs_setup_rw(), brixcvmfs_teardown_rw(), rw_apply_chmod(), rw_apply_utimens(), rw_classify(), rw_copyup(), rw_dir_merged_nonempty(), rw_ensure_parents(), rw_meta_apply(), rw_mkdir(), rw_open_create(), rw_open_lower(), rw_open_upper(), rw_readdir(), rw_readlink(), rw_rename_commit(), rw_rename_dir(), rw_rmdir(), rw_symlink(), rw_truncate(), and rw_unlink().
g_writes_fd
int g_writes_fd = -1 static
Definition at line 39 of file brixcvmfs_rw.c.
Referenced by brixcvmfs_setup_rw(), brixcvmfs_teardown_rw(), pt_readdir(), rw_chmod(), rw_getattr(), rw_mkdir(), rw_open_common(), rw_readlink(), rw_rename(), rw_rmdir(), rw_statfs(), rw_symlink(), rw_truncate(), rw_unlink(), and rw_utimens().