nginx-xrootd: client/apps/diag/brix_fault_replay.h File Reference
brix_fault_replay.h File Reference
#include <stddef.h>
Data Structures
struct fp_replay_rec
struct fp_replay_store
Functions
int fp_replay_record_start (const char *path)
void fp_replay_record_stop (void)
int fp_replay_recording (void)
void fp_replay_record (int is_up, unsigned long long ts_ms, const unsigned char *b, size_t n)
int fp_replay_load (const char *path, fp_replay_store *s)
void fp_replay_free (fp_replay_store *s)
Function Documentation
fp_replay_free()
void fp_replay_free (fp_replay_store * s)
Definition at line 143 of file brix_fault_replay.c.
References s.
Referenced by cmd_set_replay().
fp_replay_load()
int fp_replay_load (const char * path, fp_replay_store * s)
Definition at line 94 of file brix_fault_replay.c.
References get_be(), REC_MAGIC, and s.
Referenced by cmd_set_replay().
fp_replay_record()
void fp_replay_record (int is_up, unsigned long long ts_ms, const unsigned char * b, size_t n)
Definition at line 76 of file brix_fault_replay.c.
References g_rec_fd, g_rec_lock, and put_be().
Referenced by relay_pump_dir().
fp_replay_record_start()
int fp_replay_record_start (const char * path)
Definition at line 38 of file brix_fault_replay.c.
References close(), g_rec_fd, g_rec_lock, open(), and REC_MAGIC.
Referenced by cmd_set_replay().
fp_replay_record_stop()
void fp_replay_record_stop (void)
Definition at line 59 of file brix_fault_replay.c.
References close(), g_rec_fd, and g_rec_lock.
Referenced by cmd_set_replay().
fp_replay_recording()
int fp_replay_recording (void)
Definition at line 70 of file brix_fault_replay.c.
References g_rec_fd.
Referenced by cmd_status_json(), cmd_status_report(), and relay_pump_dir().