nginx-xrootd: client/apps/fs/brixautofs_unittest.c File Reference
brixautofs_unittest.c File Reference
#include "brixautofs.h"
#include <stdio.h>
#include <string.h>
Macros
#define CHECK(c, n)
Functions
static void test_valid_fqrn (void)
static void test_repo_listed (void)
static void test_table (void)
int main (void)
Variables
static int g_checks
static int g_failed
Macro Definition Documentation
CHECK
#define CHECK (c, n)
Value:
    do{ g_checks++; if(c){printf("  ok   %s\n",n);} \
    else{printf("  FAIL %s (line %d)\n",n,__LINE__); g_failed++;} }while(0)
Definition at line 16 of file brixautofs_unittest.c.
Function Documentation
main()
int main (void)
Definition at line 104 of file brixautofs_unittest.c.
References g_checks, g_failed, test_repo_listed(), test_table(), and test_valid_fqrn().
test_repo_listed()
static void test_repo_listed (void) static
Definition at line 59 of file brixautofs_unittest.c.
References brixautofs_repo_listed(), and CHECK.
Referenced by main().
test_table()
static void test_table (void) static
Definition at line 76 of file brixautofs_unittest.c.
References brixautofs_claim_locked(), brixautofs_commit_locked(), brixautofs_find_locked(), brixautofs_find_pid_locked(), BRIXAUTOFS_MAX_REPOS, BRIXAUTOFS_MOUNTED, BRIXAUTOFS_MOUNTING, brixautofs_release_locked(), brixautofs_table_init(), CHECK, name, brixautofs_slot_t::pid, brixautofs_table_t::slot, and brixautofs_slot_t::st.
Referenced by main().
test_valid_fqrn()
static void test_valid_fqrn (void) static
Definition at line 19 of file brixautofs_unittest.c.
References brixautofs_valid_fqrn(), and CHECK.
Referenced by main().
Variable Documentation
g_checks
int g_checks static
Definition at line 15 of file brixautofs_unittest.c.
Referenced by main().
g_failed
int g_failed static
Definition at line 15 of file brixautofs_unittest.c.
Referenced by main().