nginx-xrootd: client/apps/fs/brixcvmfs_internal.h File Reference
brixcvmfs_internal.h File Reference
#include <fuse3/fuse.h>
#include "cvmfs/client/client.h"
Macros
#define FUSE_USE_VERSION 31
Functions
cvmfs_client_t * brixcvmfs_client (void)
const char * brixcvmfs_cat_path (const char *p)
long brixcvmfs_mono_now (void)
int brixcvmfs_op_getattr (const char *path, struct stat *st, struct fuse_file_info *fi)
int brixcvmfs_op_readdir (const char *path, void *buf, fuse_fill_dir_t filler, off_t off, struct fuse_file_info *fi, enum fuse_readdir_flags fl)
int brixcvmfs_op_open (const char *path, struct fuse_file_info *fi)
int brixcvmfs_op_read (const char *path, char *buf, size_t size, off_t off, struct fuse_file_info *fi)
int brixcvmfs_op_readlink (const char *path, char *buf, size_t size)
int brixcvmfs_op_statfs (const char *path, struct statvfs *sv)
int brixcvmfs_op_getxattr (const char *path, const char *name, char *value, size_t size)
int brixcvmfs_op_listxattr (const char *path, char *list, size_t size)
int brixcvmfs_setup_rw (const char *mnt, const char *writes_override)
void brixcvmfs_teardown_rw (void)
int brixcvmfs_rw_main (int argc, char **argv)
Variables
int brixcvmfs_rw
const struct fuse_operations brixcvmfs_rw_ops
Macro Definition Documentation
FUSE_USE_VERSION
#define FUSE_USE_VERSION 31
Definition at line 18 of file brixcvmfs_internal.h.
Function Documentation
brixcvmfs_cat_path()
const char * brixcvmfs_cat_path (const char * p)
Definition at line 261 of file brixcvmfs.c.
References cat_path().
Referenced by lower_resolve(), rw_dir_merged_nonempty(), and rw_readdir().
brixcvmfs_client()
cvmfs_client_t * brixcvmfs_client (void)
Definition at line 260 of file brixcvmfs.c.
References g_cl.
Referenced by lower_resolve(), rw_dir_merged_nonempty(), rw_read_lower(), and rw_readdir().
brixcvmfs_mono_now()
long brixcvmfs_mono_now (void)
Definition at line 262 of file brixcvmfs.c.
References mono_now().
Referenced by lower_resolve(), rw_read_lower(), and rw_readdir().
brixcvmfs_op_getattr()
int brixcvmfs_op_getattr (const char * path, struct stat * st, struct fuse_file_info * fi)
Definition at line 438 of file brixcvmfs.c.
References brix_refresh(), cat_path(), g_cl, and mono_now().
Referenced by rw_getattr().
brixcvmfs_op_getxattr()
int brixcvmfs_op_getxattr (const char * path, const char * name, char * value, size_t size)
Definition at line 513 of file brixcvmfs.c.
References cat_path(), g_cl, mono_now(), and name.
Referenced by rw_getxattr().
brixcvmfs_op_listxattr()
int brixcvmfs_op_listxattr (const char * path, char * list, size_t size)
Definition at line 521 of file brixcvmfs.c.
References cat_path(), g_cl, and mono_now().
Referenced by rw_listxattr().
brixcvmfs_op_open()
int brixcvmfs_op_open (const char * path, struct fuse_file_info * fi)
Definition at line 477 of file brixcvmfs.c.
References cat_path(), g_cl, and mono_now().
Referenced by rw_open_lower().
brixcvmfs_op_read()
int brixcvmfs_op_read (const char * path, char * buf, size_t size, off_t off, struct fuse_file_info * fi)
Definition at line 487 of file brixcvmfs.c.
References cat_path(), g_cl, and mono_now().
Referenced by rw_read().
brixcvmfs_op_readdir()
int brixcvmfs_op_readdir (const char * path, void * buf, fuse_fill_dir_t filler, off_t off, struct fuse_file_info * fi, enum fuse_readdir_flags fl)
Definition at line 465 of file brixcvmfs.c.
References brix_refresh(), cat_path(), g_cl, mono_now(), pf_enqueue(), and readdir_emit().
brixcvmfs_op_readlink()
int brixcvmfs_op_readlink (const char * path, char * buf, size_t size)
Definition at line 496 of file brixcvmfs.c.
References cat_path(), g_cl, and mono_now().
Referenced by rw_readlink().
brixcvmfs_op_statfs()
int brixcvmfs_op_statfs (const char * path, struct statvfs * sv)
Definition at line 505 of file brixcvmfs.c.
Referenced by rw_statfs().
brixcvmfs_rw_main()
int brixcvmfs_rw_main (int argc, char ** argv)
Definition at line 875 of file brixcvmfs_rw.c.
References brixcvmfs_main(), and brixcvmfs_rw.
Referenced by main().
brixcvmfs_setup_rw()
int brixcvmfs_setup_rw (const char * mnt, const char * writes_override)
Definition at line 845 of file brixcvmfs_rw.c.
References BRIX_OV_DIRNAME, brix_overlay_init(), close(), g_ov, g_writes_fd, and open().
Referenced by brixcvmfs_setup_rw_overlay().
brixcvmfs_teardown_rw()
void brixcvmfs_teardown_rw (void)
Definition at line 866 of file brixcvmfs_rw.c.
References brix_overlay_close(), close(), g_ov, and g_writes_fd.
Referenced by brixcvmfs_mount_run().
Variable Documentation
brixcvmfs_rw
int brixcvmfs_rw extern
Definition at line 258 of file brixcvmfs.c.
Referenced by brixcvmfs_mount_run(), brixcvmfs_run_fuse(), brixcvmfs_rw_main(), and brixcvmfs_setup_rw_overlay().
brixcvmfs_rw_ops
const struct fuse_operations brixcvmfs_rw_ops extern
Definition at line 820 of file brixcvmfs_rw.c.
Referenced by brixcvmfs_run_fuse(), and brixcvmfs_setup_rw_overlay().