nginx-xrootd: client/apps/fs/brixcvmfs.c File Reference
brixcvmfs.c File Reference
#include <fuse3/fuse.h>
#include <curl/curl.h>
#include "cvmfs/client/client.h"
#include "cvmfs/config/cvmfs_conf.h"
#include "cvmfs/walk/walk.h"
#include "net/proxy_env.h"
#include "net/cpool.h"
#include "brixcvmfs_internal.h"
#include <errno.h>
#include <fcntl.h>
#include <pthread.h>
#include <stdio.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct brixcvmfs_transport_cfg_t
struct curl_sink_t
struct brix_prefetch_t
struct pf_walk_ud_t
struct readdir_ctx_t
struct brix_opts_t
struct prewarm_ud_t
Macros
#define FUSE_USE_VERSION 31
#define BRIX_CURL_POOL_SLOTS 4 /* foreground (-s serialized) + prefetch + slack */
#define BRIX_PF_QCAP 32
#define BRIX_PF_SEENCAP 512
#define BRIX_PF_OBJCAP (32u * 1024u * 1024u)
Functions
static size_t curl_write_cb (char *ptr, size_t sz, size_t nm, void *ud)
static void url_host (const char *url, char *sch, size_t sl, char *host, size_t hl, int *port)
static int curl_slot_connect (void *conn, void *ctx, brix_status *st)
static void curl_slot_close (void *conn)
static void transport_cleanup (void)
static CURLcode http_get_range (CURL **slot, const char *proxy, const char *url, unsigned char *out, size_t outcap, size_t *got)
static int to_https (const char *url, char *buf, size_t n)
static int brixcvmfs_transport (const char *proxy, const char *host, const char *rel, unsigned char *out, size_t outcap, size_t *outlen, void *ud)
static const char * cat_path (const char *p)
static long mono_now (void)
cvmfs_client_t * brixcvmfs_client (void)
const char * brixcvmfs_cat_path (const char *p)
long brixcvmfs_mono_now (void)
static void brix_refresh (void)
static uint64_t pf_fnv1a (const char *s)
static int pf_visit (const cvmfs_walk_item_t *it, void *ud)
static void * pf_main (void *arg)
static void pf_enqueue (const char *path)
static void pf_start (int depth, long budget, const char *tmp_dir, const char *cache_dir, int cache_dirfd, long quota)
int brixcvmfs_op_getattr (const char *path, struct stat *st, struct fuse_file_info *fi)
static void readdir_emit (const cvmfs_dirent_t *e, void *ud)
int brixcvmfs_op_readdir (const char *path, void *buf, fuse_fill_dir_t filler, off_t off, struct fuse_file_info *fi, enum fuse_readdir_flags fl)
int brixcvmfs_op_open (const char *path, struct fuse_file_info *fi)
int brixcvmfs_op_read (const char *path, char *buf, size_t size, off_t off, struct fuse_file_info *fi)
int brixcvmfs_op_readlink (const char *path, char *buf, size_t size)
int brixcvmfs_op_statfs (const char *path, struct statvfs *sv)
int brixcvmfs_op_getxattr (const char *path, const char *name, char *value, size_t size)
int brixcvmfs_op_listxattr (const char *path, char *list, size_t size)
int brixcvmfs_op_access (const char *path, int mask)
static int ro_erofs (void)
static int op_mkdir (const char *p, mode_t m)
static int op_unlink (const char *p)
static int op_write (const char *p, const char *b, size_t s, off_t o, struct fuse_file_info *fi)
static int op_rmdir (const char *p)
static int op_rename (const char *f, const char *t, unsigned int fl)
static int op_symlink (const char *tgt, const char *p)
static int op_link (const char *f, const char *t)
static int op_chmod (const char *p, mode_t m, struct fuse_file_info *fi)
static int op_chown (const char *p, uid_t u, gid_t g, struct fuse_file_info *fi)
static int op_truncate (const char *p, off_t o, struct fuse_file_info *fi)
static int op_utimens (const char *p, const struct timespec tv[2], struct fuse_file_info *fi)
static int op_setxattr (const char *p, const char *n, const char *v, size_t s, int f)
static int op_removexattr (const char *p, const char *n)
static int op_mknod (const char *p, mode_t m, dev_t d)
static unsigned char * read_file (const char *path, size_t *len)
static unsigned char * load_master_key (const char *path, size_t *len)
static void opts_o_list (char *list, brix_opts_t *o)
static void parse_opts (int argc, char **argv, int start, brix_opts_t *o)
static void brixcvmfs_build_failover (cvmfs_client_t *cl, const cvmfs_conf_t *cf, const char *repo)
static void brixcvmfs_build_transport_cfg (const cvmfs_client_t *cl, const cvmfs_conf_t *cf, const char *repo, int retries_override)
static long brixcvmfs_resolve_quota (const cvmfs_conf_t *cf, long quota_override)
static unsigned char * brixcvmfs_load_repo_key (const cvmfs_client_t *cl, size_t *klen)
static void brixcvmfs_prepare_tmp_dir (const char *repo, char *tmp_dir, size_t cap)
static void brixcvmfs_prepare_cache_dir (const char *repo, const char *cache_dir_override, int cache_dirfd, char *cache_dir, size_t cap)
static cvmfs_client_t * brixcvmfs_open (const char *repo, const char *cache_dir_override, int cache_dirfd, long quota_override, int retries_override, const char *pin_opt)
static int brixcvmfs_check (const char *repo)
static int prewarm_visit (const cvmfs_walk_item_t *it, void *ud)
static int brixcvmfs_prewarm (const char *repo)
static int brixcvmfs_open_clever_cache (const char *mnt, const brix_opts_t *o, const char **cache_override)
static int brixcvmfs_setup_rw_overlay (const char *mnt, const brix_opts_t *o)
static int brixcvmfs_run_fuse (char *arg0, const char *mnt, const brix_opts_t *o)
static int brixcvmfs_mount_run (char *arg0, const char *repo, const char *mnt, const brix_opts_t *o)
int brixcvmfs_main (int argc, char **argv)
int main (int argc, char **argv)
Variables
static cvmfs_client_t * g_cl
static brixcvmfs_transport_cfg_t g_tcfg
static brix_cpool * g_curl_pool
static const brix_cpool_vtbl CURL_VT = { sizeof(CURL *), curl_slot_connect, curl_slot_close }
int brixcvmfs_rw = 0
static brix_prefetch_t g_pf = { .cache_dirfd = -1 }
static const struct fuse_operations brixcvmfs_ops
Macro Definition Documentation
BRIX_CURL_POOL_SLOTS
#define BRIX_CURL_POOL_SLOTS 4 /* foreground (-s serialized) + prefetch + slack */
Definition at line 92 of file brixcvmfs.c.
BRIX_PF_OBJCAP
#define BRIX_PF_OBJCAP (32u * 1024u * 1024u)
Definition at line 297 of file brixcvmfs.c.
BRIX_PF_QCAP
#define BRIX_PF_QCAP 32
Definition at line 295 of file brixcvmfs.c.
BRIX_PF_SEENCAP
#define BRIX_PF_SEENCAP 512
Definition at line 296 of file brixcvmfs.c.
FUSE_USE_VERSION
#define FUSE_USE_VERSION 31
Definition at line 17 of file brixcvmfs.c.
Function Documentation
brix_refresh()
static void brix_refresh (void) static
Definition at line 267 of file brixcvmfs.c.
References g_cl, and mono_now().
Referenced by brixcvmfs_op_getattr(), and brixcvmfs_op_readdir().
brixcvmfs_build_failover()
static void brixcvmfs_build_failover (cvmfs_client_t * cl, const cvmfs_conf_t * cf, const char * repo) static
Definition at line 699 of file brixcvmfs.c.
Referenced by brixcvmfs_open().
brixcvmfs_build_transport_cfg()
static void brixcvmfs_build_transport_cfg (const cvmfs_client_t * cl, const cvmfs_conf_t * cf, const char * repo, int retries_override) static
Definition at line 719 of file brixcvmfs.c.
References brixcvmfs_transport_cfg_t::connect_timeout_s, g_tcfg, brixcvmfs_transport_cfg_t::low_speed_bytes, brixcvmfs_transport_cfg_t::low_speed_time_s, brixcvmfs_transport_cfg_t::max_retries, and brixcvmfs_transport_cfg_t::repo.
Referenced by brixcvmfs_open().
brixcvmfs_cat_path()
const char * brixcvmfs_cat_path (const char * p)
Definition at line 261 of file brixcvmfs.c.
References cat_path().
Referenced by lower_resolve(), rw_dir_merged_nonempty(), and rw_readdir().
brixcvmfs_check()
static int brixcvmfs_check (const char * repo) static
Definition at line 855 of file brixcvmfs.c.
References brixcvmfs_open(), host, mono_now(), and transport_cleanup().
Referenced by brixcvmfs_main().
brixcvmfs_client()
cvmfs_client_t * brixcvmfs_client (void)
Definition at line 260 of file brixcvmfs.c.
References g_cl.
Referenced by lower_resolve(), rw_dir_merged_nonempty(), rw_read_lower(), and rw_readdir().
brixcvmfs_load_repo_key()
static unsigned char * brixcvmfs_load_repo_key (const cvmfs_client_t * cl, size_t * klen) static
Definition at line 745 of file brixcvmfs.c.
References load_master_key().
Referenced by brixcvmfs_open().
brixcvmfs_main()
int brixcvmfs_main (int argc, char ** argv)
Definition at line 1056 of file brixcvmfs.c.
References brixcvmfs_check(), brixcvmfs_mount_run(), brixcvmfs_prewarm(), and parse_opts().
Referenced by brixcvmfs_rw_main(), and main().
brixcvmfs_mono_now()
long brixcvmfs_mono_now (void)
Definition at line 262 of file brixcvmfs.c.
References mono_now().
Referenced by lower_resolve(), rw_read_lower(), and rw_readdir().
brixcvmfs_mount_run()
static int brixcvmfs_mount_run (char * arg0, const char * repo, const char * mnt, const brix_opts_t * o) static
Definition at line 1012 of file brixcvmfs.c.
References brixcvmfs_open(), brixcvmfs_open_clever_cache(), brixcvmfs_prepare_cache_dir(), brixcvmfs_run_fuse(), brixcvmfs_rw, brixcvmfs_setup_rw_overlay(), brixcvmfs_teardown_rw(), close(), brix_opts_t::fresh, brixcvmfs_transport_cfg_t::fresh_connect, g_cl, g_tcfg, pf_start(), brix_opts_t::pin, brixcvmfs_transport_cfg_t::prefer_tls, brix_opts_t::prefetch, brix_opts_t::prefetch_budget, brix_opts_t::quota_mb, brix_opts_t::retries, brix_opts_t::tls, and transport_cleanup().
Referenced by brixcvmfs_main().
brixcvmfs_op_access()
int brixcvmfs_op_access (const char * path, int mask)
Definition at line 531 of file brixcvmfs.c.
References cat_path(), g_cl, and mono_now().
brixcvmfs_op_getattr()
int brixcvmfs_op_getattr (const char * path, struct stat * st, struct fuse_file_info * fi)
Definition at line 438 of file brixcvmfs.c.
References brix_refresh(), cat_path(), g_cl, and mono_now().
Referenced by rw_getattr().
brixcvmfs_op_getxattr()
int brixcvmfs_op_getxattr (const char * path, const char * name, char * value, size_t size)
Definition at line 513 of file brixcvmfs.c.
References cat_path(), g_cl, mono_now(), and name.
Referenced by rw_getxattr().
brixcvmfs_op_listxattr()
int brixcvmfs_op_listxattr (const char * path, char * list, size_t size)
Definition at line 521 of file brixcvmfs.c.
References cat_path(), g_cl, and mono_now().
Referenced by rw_listxattr().
brixcvmfs_op_open()
int brixcvmfs_op_open (const char * path, struct fuse_file_info * fi)
Definition at line 477 of file brixcvmfs.c.
References cat_path(), g_cl, and mono_now().
Referenced by rw_open_lower().
brixcvmfs_op_read()
int brixcvmfs_op_read (const char * path, char * buf, size_t size, off_t off, struct fuse_file_info * fi)
Definition at line 487 of file brixcvmfs.c.
References cat_path(), g_cl, and mono_now().
Referenced by rw_read().
brixcvmfs_op_readdir()
int brixcvmfs_op_readdir (const char * path, void * buf, fuse_fill_dir_t filler, off_t off, struct fuse_file_info * fi, enum fuse_readdir_flags fl)
Definition at line 465 of file brixcvmfs.c.
References brix_refresh(), cat_path(), g_cl, mono_now(), pf_enqueue(), and readdir_emit().
brixcvmfs_op_readlink()
int brixcvmfs_op_readlink (const char * path, char * buf, size_t size)
Definition at line 496 of file brixcvmfs.c.
References cat_path(), g_cl, and mono_now().
Referenced by rw_readlink().
brixcvmfs_op_statfs()
int brixcvmfs_op_statfs (const char * path, struct statvfs * sv)
Definition at line 505 of file brixcvmfs.c.
Referenced by rw_statfs().
brixcvmfs_open()
static cvmfs_client_t * brixcvmfs_open (const char * repo, const char * cache_dir_override, int cache_dirfd, long quota_override, int retries_override, const char * pin_opt) static
Definition at line 794 of file brixcvmfs.c.
References brix_cpool_create(), BRIX_CURL_POOL_SLOTS, brix_status_clear(), brixcvmfs_build_failover(), brixcvmfs_build_transport_cfg(), brixcvmfs_load_repo_key(), brixcvmfs_prepare_cache_dir(), brixcvmfs_prepare_tmp_dir(), brixcvmfs_resolve_quota(), brixcvmfs_transport(), CURL_VT, g_curl_pool, mono_now(), brix_status::msg, and transport_cleanup().
Referenced by brixcvmfs_check(), brixcvmfs_mount_run(), and brixcvmfs_prewarm().
brixcvmfs_open_clever_cache()
static int brixcvmfs_open_clever_cache (const char * mnt, const brix_opts_t * o, const char ** cache_override) static
Definition at line 957 of file brixcvmfs.c.
References brix_opts_t::cache_dir, brix_opts_t::clever, and open().
Referenced by brixcvmfs_mount_run().
brixcvmfs_prepare_cache_dir()
static void brixcvmfs_prepare_cache_dir (const char * repo, const char * cache_dir_override, int cache_dirfd, char * cache_dir, size_t cap) static
Definition at line 778 of file brixcvmfs.c.
References mk().
Referenced by brixcvmfs_mount_run(), and brixcvmfs_open().
brixcvmfs_prepare_tmp_dir()
static void brixcvmfs_prepare_tmp_dir (const char * repo, char * tmp_dir, size_t cap) static
Definition at line 766 of file brixcvmfs.c.
References mk().
Referenced by brixcvmfs_open().
brixcvmfs_prewarm()
static int brixcvmfs_prewarm (const char * repo) static
Definition at line 922 of file brixcvmfs.c.
References BRIX_PF_OBJCAP, brixcvmfs_open(), prewarm_ud_t::bytes, prewarm_ud_t::errs, hex(), mono_now(), prewarm_ud_t::objs, prewarm_ud_t::out, prewarm_visit(), and transport_cleanup().
Referenced by brixcvmfs_main().
brixcvmfs_resolve_quota()
static long brixcvmfs_resolve_quota (const cvmfs_conf_t * cf, long quota_override) static
Definition at line 732 of file brixcvmfs.c.
Referenced by brixcvmfs_open().
brixcvmfs_run_fuse()
static int brixcvmfs_run_fuse (char * arg0, const char * mnt, const brix_opts_t * o) static
Definition at line 994 of file brixcvmfs.c.
References brixcvmfs_ops, brixcvmfs_rw, brixcvmfs_rw_ops, brix_opts_t::flags, brix_opts_t::fuse_extra, and brix_opts_t::nflags.
Referenced by brixcvmfs_mount_run().
brixcvmfs_setup_rw_overlay()
static int brixcvmfs_setup_rw_overlay (const char * mnt, const brix_opts_t * o) static
Definition at line 980 of file brixcvmfs.c.
References brixcvmfs_rw, brixcvmfs_rw_ops, brixcvmfs_setup_rw(), and brix_opts_t::writes_dir.
Referenced by brixcvmfs_mount_run().
brixcvmfs_transport()
static int brixcvmfs_transport (const char * proxy, const char * host, const char * rel, unsigned char * out, size_t outcap, size_t * outlen, void * ud) static
Definition at line 198 of file brixcvmfs.c.
References brix_cpool_checkin(), brix_cpool_checkout(), brix_status_clear(), g_curl_pool, g_tcfg, host, http_get_range(), brixcvmfs_transport_cfg_t::max_retries, brixcvmfs_transport_cfg_t::prefer_tls, and to_https().
Referenced by brixcvmfs_open(), and pf_main().
cat_path()
static const char * cat_path (const char * p) static
Definition at line 248 of file brixcvmfs.c.
Referenced by brixcvmfs_cat_path(), brixcvmfs_op_access(), brixcvmfs_op_getattr(), brixcvmfs_op_getxattr(), brixcvmfs_op_listxattr(), brixcvmfs_op_open(), brixcvmfs_op_read(), brixcvmfs_op_readdir(), and brixcvmfs_op_readlink().
curl_slot_close()
static void curl_slot_close (void * conn) static
Definition at line 103 of file brixcvmfs.c.
References c.
curl_slot_connect()
static int curl_slot_connect (void * conn, void * ctx, brix_status * st) static
Definition at line 96 of file brixcvmfs.c.
References brix_status_set(), c, and XRDC_EIO.
curl_write_cb()
static size_t curl_write_cb (char * ptr, size_t sz, size_t nm, void * ud) static
Definition at line 60 of file brixcvmfs.c.
References s.
Referenced by http_get_range().
http_get_range()
static CURLcode http_get_range (CURL ** slot, const char * proxy, const char * url, unsigned char * out, size_t outcap, size_t * got) static
Definition at line 117 of file brixcvmfs.c.
References c, code, brixcvmfs_transport_cfg_t::connect_timeout_s, curl_write_cb(), brixcvmfs_transport_cfg_t::fresh_connect, g_tcfg, curl_sink_t::len, brixcvmfs_transport_cfg_t::low_speed_bytes, brixcvmfs_transport_cfg_t::low_speed_time_s, and url_host().
Referenced by brixcvmfs_transport().
load_master_key()
static unsigned char * load_master_key (const char * path, size_t * len) static
Definition at line 610 of file brixcvmfs.c.
References read_file(), and stat().
Referenced by brixcvmfs_load_repo_key().
main()
int main (int argc, char ** argv)
Definition at line 1076 of file brixcvmfs.c.
References brixcvmfs_main(), and brixcvmfs_rw_main().
mono_now()
static long mono_now (void) static
Definition at line 250 of file brixcvmfs.c.
Referenced by brix_refresh(), brixcvmfs_check(), brixcvmfs_mono_now(), brixcvmfs_op_access(), brixcvmfs_op_getattr(), brixcvmfs_op_getxattr(), brixcvmfs_op_listxattr(), brixcvmfs_op_open(), brixcvmfs_op_read(), brixcvmfs_op_readdir(), brixcvmfs_op_readlink(), brixcvmfs_open(), brixcvmfs_prewarm(), pf_main(), pf_visit(), and prewarm_visit().
op_chmod()
static int op_chmod (const char * p, mode_t m, struct fuse_file_info * fi) static
Definition at line 553 of file brixcvmfs.c.
References ro_erofs().
op_chown()
static int op_chown (const char * p, uid_t u, gid_t g, struct fuse_file_info * fi) static
Definition at line 555 of file brixcvmfs.c.
References ro_erofs().
op_link()
static int op_link (const char * f, const char * t) static
Definition at line 552 of file brixcvmfs.c.
References ro_erofs().
op_mkdir()
static int op_mkdir (const char * p, mode_t m) static
Definition at line 544 of file brixcvmfs.c.
References ro_erofs().
op_mknod()
static int op_mknod (const char * p, mode_t m, dev_t d) static
Definition at line 564 of file brixcvmfs.c.
References ro_erofs().
op_removexattr()
static int op_removexattr (const char * p, const char * n) static
Definition at line 563 of file brixcvmfs.c.
References ro_erofs().
op_rename()
static int op_rename (const char * f, const char * t, unsigned int fl) static
Definition at line 549 of file brixcvmfs.c.
References ro_erofs().
op_rmdir()
static int op_rmdir (const char * p) static
Definition at line 548 of file brixcvmfs.c.
References ro_erofs().
op_setxattr()
static int op_setxattr (const char * p, const char * n, const char * v, size_t s, int f) static
Definition at line 561 of file brixcvmfs.c.
References ro_erofs(), and s.
op_symlink()
static int op_symlink (const char * tgt, const char * p) static
Definition at line 551 of file brixcvmfs.c.
References ro_erofs().
op_truncate()
static int op_truncate (const char * p, off_t o, struct fuse_file_info * fi) static
Definition at line 557 of file brixcvmfs.c.
References ro_erofs().
op_unlink()
static int op_unlink (const char * p) static
Definition at line 545 of file brixcvmfs.c.
References ro_erofs().
op_utimens()
static int op_utimens (const char * p, const struct timespec tv[2], struct fuse_file_info * fi) static
Definition at line 559 of file brixcvmfs.c.
References ro_erofs().
op_write()
static int op_write (const char * p, const char * b, size_t s, off_t o, struct fuse_file_info * fi) static
Definition at line 546 of file brixcvmfs.c.
References ro_erofs(), and s.
opts_o_list()
static void opts_o_list (char * list, brix_opts_t * o) static
Definition at line 654 of file brixcvmfs.c.
References brix_opts_t::cache_dir, brix_opts_t::clever, brix_opts_t::fresh, brix_opts_t::fuse_extra, brix_opts_t::pin, brix_opts_t::prefetch, brix_opts_t::prefetch_budget, brix_opts_t::quota_mb, brix_opts_t::retries, brix_opts_t::tls, and brix_opts_t::writes_dir.
Referenced by parse_opts().
parse_opts()
static void parse_opts (int argc, char ** argv, int start, brix_opts_t * o) static
Definition at line 679 of file brixcvmfs.c.
References brix_opts_t::clever, brix_opts_t::flags, brix_opts_t::nflags, opts_o_list(), brix_opts_t::prefetch, and brix_opts_t::retries.
Referenced by brixcvmfs_main().
pf_enqueue()
static void pf_enqueue (const char * path) static
Definition at line 398 of file brixcvmfs.c.
References BRIX_PF_QCAP, BRIX_PF_SEENCAP, brix_prefetch_t::cv, brix_prefetch_t::enabled, g_cl, g_pf, brix_prefetch_t::mu, brix_prefetch_t::nseen, brix_prefetch_t::path, pf_fnv1a(), brix_prefetch_t::q, brix_prefetch_t::qh, brix_prefetch_t::qn, brix_prefetch_t::root, and brix_prefetch_t::seen.
Referenced by brixcvmfs_op_readdir().
pf_fnv1a()
static uint64_t pf_fnv1a (const char * s) static
Definition at line 322 of file brixcvmfs.c.
References s.
Referenced by pf_enqueue().
pf_main()
static void * pf_main (void * arg) static
Definition at line 355 of file brixcvmfs.c.
References BRIX_PF_OBJCAP, BRIX_PF_QCAP, brixcvmfs_transport(), brix_prefetch_t::cache_dir, brix_prefetch_t::cache_dirfd, brix_prefetch_t::capped, brix_prefetch_t::cv, brix_prefetch_t::depth, brix_prefetch_t::fo, g_pf, mono_now(), brix_prefetch_t::mu, brix_prefetch_t::path, pf_visit(), brix_prefetch_t::q, brix_prefetch_t::qh, brix_prefetch_t::qn, brix_prefetch_t::quota, brix_prefetch_t::root, and brix_prefetch_t::tmp_dir.
Referenced by pf_start().
pf_start()
static void pf_start (int depth, long budget, const char * tmp_dir, const char * cache_dir, int cache_dirfd, long quota) static
Definition at line 419 of file brixcvmfs.c.
References brix_prefetch_t::budget, brix_prefetch_t::cache_dir, brix_prefetch_t::cache_dirfd, brix_prefetch_t::cv, brix_prefetch_t::depth, brix_prefetch_t::enabled, brix_prefetch_t::fo, brix_prefetch_t::fo0, g_cl, g_pf, brix_prefetch_t::mu, pf_main(), brix_prefetch_t::quota, brix_prefetch_t::tid, and brix_prefetch_t::tmp_dir.
Referenced by brixcvmfs_mount_run().
pf_visit()
static int pf_visit (const cvmfs_walk_item_t * it, void * ud) static
Definition at line 333 of file brixcvmfs.c.
References BRIX_PF_OBJCAP, brix_prefetch_t::budget, brix_prefetch_t::capped, brix_prefetch_t::fo, brix_prefetch_t::fo0, pf_walk_ud_t::fx, g_cl, g_pf, mono_now(), pf_walk_ud_t::out, and brix_prefetch_t::spent.
Referenced by pf_main().
prewarm_visit()
static int prewarm_visit (const cvmfs_walk_item_t * it, void * ud) static
Definition at line 906 of file brixcvmfs.c.
References BRIX_PF_OBJCAP, prewarm_ud_t::bytes, prewarm_ud_t::errs, prewarm_ud_t::fo0, prewarm_ud_t::fx, mono_now(), prewarm_ud_t::objs, and prewarm_ud_t::out.
Referenced by brixcvmfs_prewarm().
read_file()
static unsigned char * read_file (const char * path, size_t * len) static
Definition at line 594 of file brixcvmfs.c.
Referenced by load_master_key().
readdir_emit()
static void readdir_emit (const cvmfs_dirent_t * e, void * ud) static
Definition at line 459 of file brixcvmfs.c.
References readdir_ctx_t::buf, and readdir_ctx_t::filler.
Referenced by brixcvmfs_op_readdir().
ro_erofs()
static int ro_erofs (void) static
Definition at line 543 of file brixcvmfs.c.
Referenced by op_chmod(), op_chown(), op_link(), op_mkdir(), op_mknod(), op_removexattr(), op_rename(), op_rmdir(), op_setxattr(), op_symlink(), op_truncate(), op_unlink(), op_utimens(), and op_write().
to_https()
static int to_https (const char * url, char * buf, size_t n) static
Definition at line 186 of file brixcvmfs.c.
Referenced by brixcvmfs_transport().
transport_cleanup()
static void transport_cleanup (void) static
Definition at line 109 of file brixcvmfs.c.
References brix_cpool_destroy(), and g_curl_pool.
Referenced by brixcvmfs_check(), brixcvmfs_mount_run(), brixcvmfs_open(), and brixcvmfs_prewarm().
url_host()
static void url_host (const char * url, char * sch, size_t sl, char * host, size_t hl, int * port) static
Definition at line 70 of file brixcvmfs.c.
References host, and port.
Referenced by http_get_range().
Variable Documentation
brixcvmfs_ops
const struct fuse_operations brixcvmfs_ops static
Initial value:
= {
    .getattr  = brixcvmfs_op_getattr,
    .readdir  = brixcvmfs_op_readdir,
    .open     = brixcvmfs_op_open,
    .read     = brixcvmfs_op_read,
    .readlink = brixcvmfs_op_readlink,
    .statfs   = brixcvmfs_op_statfs,
    .getxattr  = brixcvmfs_op_getxattr,
    .listxattr = brixcvmfs_op_listxattr,
    .access   = brixcvmfs_op_access,
    .mkdir    = op_mkdir,
    .unlink   = op_unlink,
    .write    = op_write,
    .rmdir       = op_rmdir,
    .rename      = op_rename,
    .symlink     = op_symlink,
    .link        = op_link,
    .chmod       = op_chmod,
    .chown       = op_chown,
    .truncate    = op_truncate,
    .utimens     = op_utimens,
    .setxattr    = op_setxattr,
    .removexattr = op_removexattr,
    .mknod       = op_mknod,
}
Definition at line 566 of file brixcvmfs.c.
Referenced by brixcvmfs_run_fuse().
brixcvmfs_rw
int brixcvmfs_rw = 0
Definition at line 258 of file brixcvmfs.c.
Referenced by brixcvmfs_mount_run(), brixcvmfs_run_fuse(), brixcvmfs_rw_main(), and brixcvmfs_setup_rw_overlay().
CURL_VT
const brix_cpool_vtbl CURL_VT = { sizeof(CURL *), curl_slot_connect, curl_slot_close } static
Definition at line 107 of file brixcvmfs.c.
Referenced by brixcvmfs_open().
g_cl
cvmfs_client_t* g_cl static
Definition at line 42 of file brixcvmfs.c.
Referenced by brix_refresh(), brixcvmfs_client(), brixcvmfs_mount_run(), brixcvmfs_op_access(), brixcvmfs_op_getattr(), brixcvmfs_op_getxattr(), brixcvmfs_op_listxattr(), brixcvmfs_op_open(), brixcvmfs_op_read(), brixcvmfs_op_readdir(), brixcvmfs_op_readlink(), pf_enqueue(), pf_start(), and pf_visit().
g_curl_pool
brix_cpool* g_curl_pool static
Definition at line 93 of file brixcvmfs.c.
Referenced by brixcvmfs_open(), brixcvmfs_transport(), and transport_cleanup().
g_pf
brix_prefetch_t g_pf = { .cache_dirfd = -1 } static
Definition at line 320 of file brixcvmfs.c.
Referenced by pf_enqueue(), pf_main(), pf_start(), and pf_visit().
g_tcfg
brixcvmfs_transport_cfg_t g_tcfg static
Definition at line 54 of file brixcvmfs.c.
Referenced by brixcvmfs_build_transport_cfg(), brixcvmfs_mount_run(), brixcvmfs_transport(), and http_get_range().