nginx-xrootd: client/apps/diag/brix_fault_priv.c File Reference
brix_fault_priv.c File Reference
#include "brix_fault_priv.h"
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <net/if.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>
Macros
#define _GNU_SOURCE
Enumerations
enum {
NE_DELAY , NE_LOSS , NE_CORRUPT , NE_DUP ,
NE_REORDER , NE_RATE , NE_LIMIT , NE_N
}
Functions
static int priv_run (char *const argv[])
static int priv_run_stdin (char *const argv[], const char *input)
static int valid_iface (const char *s)
static int fmt_pct (const char *s, char *out, size_t osz)
static int fmt_uint (const char *s, char *out, size_t osz, long max)
static int valid_rate (const char *s)
static int netem_apply (void)
static int netem_set_delay (char *args, char *reply, size_t rsz)
static int netem_set_pct (int slot, const char *verb, char *args, char *reply, size_t rsz)
static int netem_set_gemodel (char *args, char *reply, size_t rsz)
static int cmd_netem (char *args, char *reply, size_t rsz)
static const char * cut_verdict (const char *mode)
static int cut_apply (const char *mode, int dir, char *reply, size_t rsz)
static int cut_clear (void)
static int mtu_current (void)
static int mtu_set (int bytes)
static int cmd_mtu (char *args, char *reply, size_t rsz)
int fp_priv_enable (const char *iface, int listen_port, const int *target_ports, int nports, const char **err)
int fp_priv_enabled (void)
int fp_priv_command (char *args, char *reply, size_t rsz)
void fp_priv_teardown (void)
void fp_priv_usage (void *out)
Variables
static int g_on = 0
static char g_iface [IFNAMSIZ]
static int g_listen_port
static int g_tports [8]
static int g_ntports
static char g_ne [NE_N][96]
static int g_mtu_saved = -1
static int g_nft_on = 0
static int g_netem_on = 0
static pthread_mutex_t g_lock = PTHREAD_MUTEX_INITIALIZER
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 35 of file brix_fault_priv.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NE_DELAY
NE_LOSS
NE_CORRUPT
NE_DUP
NE_REORDER
NE_RATE
NE_LIMIT
NE_N
Definition at line 56 of file brix_fault_priv.c.
Function Documentation
cmd_mtu()
static int cmd_mtu (char * args, char * reply, size_t rsz) static
Definition at line 547 of file brix_fault_priv.c.
References g_iface, g_mtu_saved, mtu_current(), mtu_set(), and tok.
Referenced by fp_priv_command().
cmd_netem()
static int cmd_netem (char * args, char * reply, size_t rsz) static
Definition at line 363 of file brix_fault_priv.c.
References fmt_uint(), g_iface, g_ne, NE_CORRUPT, NE_DELAY, NE_DUP, NE_LIMIT, NE_LOSS, NE_N, NE_RATE, NE_REORDER, netem_apply(), netem_set_delay(), netem_set_gemodel(), netem_set_pct(), and valid_rate().
Referenced by fp_priv_command().
cut_apply()
static int cut_apply (const char * mode, int dir, char * reply, size_t rsz) static
Definition at line 461 of file brix_fault_priv.c.
References cut_verdict(), g_listen_port, g_nft_on, g_ntports, g_tports, and priv_run_stdin().
Referenced by fp_priv_command().
cut_clear()
static int cut_clear (void) static
Definition at line 506 of file brix_fault_priv.c.
References g_nft_on, and priv_run().
Referenced by fp_priv_command(), and fp_priv_teardown().
cut_verdict()
static const char * cut_verdict (const char * mode) static
Definition at line 446 of file brix_fault_priv.c.
Referenced by cut_apply().
fmt_pct()
static int fmt_pct (const char * s, char * out, size_t osz) static
Definition at line 173 of file brix_fault_priv.c.
References s.
Referenced by netem_set_delay(), netem_set_gemodel(), and netem_set_pct().
fmt_uint()
static int fmt_uint (const char * s, char * out, size_t osz, long max) static
Definition at line 186 of file brix_fault_priv.c.
References s.
Referenced by cmd_netem(), and netem_set_delay().
fp_priv_command()
int fp_priv_command (char * args, char * reply, size_t rsz)
Definition at line 623 of file brix_fault_priv.c.
References cmd_mtu(), cmd_netem(), cut_apply(), cut_clear(), g_iface, g_lock, g_mtu_saved, g_ne, g_nft_on, g_on, mtu_set(), NE_N, and netem_apply().
Referenced by apply_command().
fp_priv_enable()
int fp_priv_enable (const char * iface, int listen_port, const int * target_ports, int nports, const char ** err)
Definition at line 589 of file brix_fault_priv.c.
References g_iface, g_listen_port, g_lock, g_ntports, g_on, g_tports, and valid_iface().
Referenced by fp_arm_privileged().
fp_priv_enabled()
int fp_priv_enabled (void)
Definition at line 617 of file brix_fault_priv.c.
References g_on.
fp_priv_teardown()
void fp_priv_teardown (void)
Definition at line 685 of file brix_fault_priv.c.
References cut_clear(), g_iface, g_mtu_saved, g_ne, g_on, mtu_set(), NE_N, and netem_apply().
Referenced by fp_arm_privileged(), and fp_on_signal().
fp_priv_usage()
void fp_priv_usage (void * out)
Definition at line 704 of file brix_fault_priv.c.
Referenced by usage().
mtu_current()
static int mtu_current (void) static
Definition at line 520 of file brix_fault_priv.c.
References g_iface.
Referenced by cmd_mtu().
mtu_set()
static int mtu_set (int bytes) static
Definition at line 537 of file brix_fault_priv.c.
References g_iface, and priv_run().
Referenced by cmd_mtu(), fp_priv_command(), and fp_priv_teardown().
netem_apply()
static int netem_apply (void) static
Definition at line 223 of file brix_fault_priv.c.
References g_iface, g_ne, g_netem_on, NE_N, and priv_run().
Referenced by cmd_netem(), fp_priv_command(), fp_priv_teardown(), netem_set_delay(), netem_set_gemodel(), and netem_set_pct().
netem_set_delay()
static int netem_set_delay (char * args, char * reply, size_t rsz) static
Definition at line 280 of file brix_fault_priv.c.
References fmt_pct(), fmt_uint(), g_ne, NE_DELAY, and netem_apply().
Referenced by cmd_netem().
netem_set_gemodel()
static int netem_set_gemodel (char * args, char * reply, size_t rsz) static
Definition at line 336 of file brix_fault_priv.c.
References fmt_pct(), g_ne, NE_LOSS, netem_apply(), and tok.
Referenced by cmd_netem().
netem_set_pct()
static int netem_set_pct (int slot, const char * verb, char * args, char * reply, size_t rsz) static
Definition at line 313 of file brix_fault_priv.c.
References fmt_pct(), g_ne, and netem_apply().
Referenced by cmd_netem().
priv_run()
static int priv_run (char *const argv[]) static
Definition at line 75 of file brix_fault_priv.c.
References close(), and open().
Referenced by cut_clear(), mtu_set(), and netem_apply().
priv_run_stdin()
static int priv_run_stdin (char *const argv[], const char * input) static
Definition at line 103 of file brix_fault_priv.c.
References close(), and open().
Referenced by cut_apply().
valid_iface()
static int valid_iface (const char * s) static
Definition at line 152 of file brix_fault_priv.c.
References c, s, and stat().
Referenced by fp_priv_enable().
valid_rate()
static int valid_rate (const char * s) static
Definition at line 199 of file brix_fault_priv.c.
References s.
Referenced by cmd_netem().
Variable Documentation
g_iface
char g_iface[IFNAMSIZ] static
Definition at line 59 of file brix_fault_priv.c.
Referenced by cmd_mtu(), cmd_netem(), fp_priv_command(), fp_priv_enable(), fp_priv_teardown(), mtu_current(), mtu_set(), and netem_apply().
g_listen_port
int g_listen_port static
Definition at line 60 of file brix_fault_priv.c.
Referenced by cut_apply(), and fp_priv_enable().
g_lock
pthread_mutex_t g_lock = PTHREAD_MUTEX_INITIALIZER static
Definition at line 67 of file brix_fault_priv.c.
Referenced by fp_priv_command(), and fp_priv_enable().
g_mtu_saved
int g_mtu_saved = -1 static
Definition at line 64 of file brix_fault_priv.c.
Referenced by cmd_mtu(), fp_priv_command(), and fp_priv_teardown().
g_ne
char g_ne[NE_N][96] static
Definition at line 63 of file brix_fault_priv.c.
Referenced by cmd_netem(), fp_priv_command(), fp_priv_teardown(), netem_apply(), netem_set_delay(), netem_set_gemodel(), and netem_set_pct().
g_netem_on
int g_netem_on = 0 static
Definition at line 66 of file brix_fault_priv.c.
Referenced by netem_apply().
g_nft_on
int g_nft_on = 0 static
Definition at line 65 of file brix_fault_priv.c.
Referenced by cut_apply(), cut_clear(), and fp_priv_command().
g_ntports
int g_ntports static
Definition at line 62 of file brix_fault_priv.c.
Referenced by cut_apply(), and fp_priv_enable().
g_on
int g_on = 0 static
Definition at line 58 of file brix_fault_priv.c.
Referenced by fp_priv_command(), fp_priv_enable(), fp_priv_enabled(), and fp_priv_teardown().
g_tports
int g_tports[8] static
Definition at line 61 of file brix_fault_priv.c.
Referenced by cut_apply(), and fp_priv_enable().