nginx-xrootd: client/preload/brixposix_preload.c File Reference
brixposix_preload.c File Reference
#include "brix.h"
#include <dlfcn.h>
#include <errno.h>
#include <fcntl.h>
#include <pthread.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
struct xfs_slot
Macros
#define _GNU_SOURCE /* RTLD_NEXT, *64 variants (the build also passes -D_GNU_SOURCE) */
#define XFS_FD_BASE 0x40000000
#define XFS_FD_MAX 1024
#define REAL(name)
Functions
static void parse_vmp (void)
static int map_path (const char *path, char *out, size_t outsz)
static int ensure_conn (void)
static int slot_alloc (void)
static xfs_slot * slot_of (int fd)
static void fill_stat (const brix_statinfo *si, struct stat *stbuf)
static int remote_open (const char *remote)
int open (const char *path, int flags,...)
int open64 (const char *path, int flags,...)
int openat (int dirfd, const char *path, int flags,...)
int openat64 (int dirfd, const char *path, int flags,...)
ssize_t read (int fd, void *buf, size_t count)
ssize_t pread (int fd, void *buf, size_t count, off_t offset)
ssize_t pread64 (int fd, void *buf, size_t count, off_t offset)
off_t lseek (int fd, off_t offset, int whence)
off_t lseek64 (int fd, off_t offset, int whence)
int close (int fd)
static int remote_stat (const char *remote, struct stat *stbuf)
int stat (const char *path, struct stat *stbuf)
int lstat (const char *path, struct stat *stbuf)
int fstat (int fd, struct stat *stbuf)
int fstatat (int dirfd, const char *path, struct stat *stbuf, int flags)
int access (const char *path, int mode)
int stat64 (const char *path, struct stat64 *stbuf)
int lstat64 (const char *path, struct stat64 *stbuf)
int fstat64 (int fd, struct stat64 *stbuf)
int fstatat64 (int dirfd, const char *path, struct stat64 *stbuf, int flags)
int statx (int dirfd, const char *path, int flags, unsigned int mask, struct statx *stxbuf)
Variables
static pthread_once_t g_once = PTHREAD_ONCE_INIT
static pthread_mutex_t g_lock = PTHREAD_MUTEX_INITIALIZER
static int g_enabled
static char g_prefix [256]
static size_t g_prefix_len
static brix_url g_url
static char g_base [XRDC_PATH_MAX]
static brix_conn g_conn
static int g_connected
static xfs_slot g_slots [1024]
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE /* RTLD_NEXT, *64 variants (the build also passes -D_GNU_SOURCE) */
Definition at line 28 of file brixposix_preload.c.
REAL
#define REAL (name)
Value:
    static __typeof__(name) *real_##name = NULL;                        \
    if (real_##name == NULL) {                                          \
        real_##name = (__typeof__(name) *) dlsym(RTLD_NEXT, #name);     \
    }
Definition at line 206 of file brixposix_preload.c.
XFS_FD_BASE
#define XFS_FD_BASE 0x40000000
Definition at line 149 of file brixposix_preload.c.
XFS_FD_MAX
#define XFS_FD_MAX 1024
Definition at line 150 of file brixposix_preload.c.
Function Documentation
access()
int access (const char * path, int mode)
Definition at line 470 of file brixposix_preload.c.
References access(), map_path(), REAL, remote_stat(), stat(), and XRDC_PATH_MAX.
Referenced by access(), brix_pmark_defsfile_load(), brix_resolve_ca_dir(), brix_tier_default_stage_store(), brix_validate_path(), copy_download(), copy_unzip_open_dest(), copy_web_download(), diagnose_proxy(), doctor_discover_creds(), exec_recall_begin(), exec_recall_poll(), gsi_cert_available(), gsi_have(), load_or_empty(), oidc_resolve_helper_path(), posix_be_open(), proxy_is_stale(), resolve_oidc_token_binary(), resolve_oidc_token_binary(), s3keys_available(), stub_recall_begin(), stub_recall_poll(), test_stock_fixture(), try_exec_dir(), x509_acquire(), x509_available(), and xrd_whoami().
close()
int close (int fd)
Definition at line 374 of file brixposix_preload.c.
References brix_rfile_close(), brix_status_clear(), close(), g_lock, REAL, s, and slot_of().
Referenced by af_run(), baq_journal_write(), baq_reconcile_one(), bench_one(), block_be_open(), block_be_stat(), block_close(), brix_bind(), brix_cache_lock_is_stale(), brix_cache_origin_close(), brix_cache_origin_connect_addr(), brix_cache_storage_cleanup(), brix_cache_try_evict_lock(), brix_cache_try_lock(), brix_cache_verify_cvmfs_cas(), brix_cache_verify_part(), brix_chmod_confined_canon(), brix_cks_verify_file(), brix_cksum_aio_done(), brix_cli_cksum_main(), brix_close(), brix_cred_stage_write(), brix_credential_bearer(), brix_credfile_bio(), brix_csi_flush(), brix_cstore_partial_open(), brix_cvmfs_connect_rtt_us(), brix_dirlist_access_ok(), brix_dirlist_aio_thread(), brix_dirlist_checksum_token(), brix_exit_process(), brix_fs_remove_tree_at(), brix_ftp_ev_data_open(), brix_ftp_ev_eb_accept(), brix_ftp_ev_finalize(), brix_handle_fattr(), brix_http_get(), brix_http_open_rootfd(), brix_http_req(), brix_http_rootfd_cleanup(), brix_http_upload(), brix_imp_open(), brix_imp_readlink(), brix_imp_removexattr(), brix_imp_setattr(), brix_imp_setxattr(), brix_imp_stat(), brix_kaconn_connect(), brix_kaconn_disconnect(), brix_link_beneath(), brix_link_confined_canon(), brix_lstat_beneath(), brix_lstat_confined_canon(), brix_mkdir_beneath(), brix_mkdir_confined_canon(), brix_ns_delete(), brix_ns_local_copy(), brix_ns_mkdir(), brix_ns_rename(), brix_open_apply_throttle(), brix_open_attach_csi(), brix_open_confined_canon(), brix_open_confined_parent_canon(), brix_open_confined_parent_fallback(), brix_open_credfile(), brix_open_validate_fd(), brix_openat2_runtime_available(), brix_opendir_beneath(), brix_opendir_confined_canon(), brix_overlay_chmod(), brix_overlay_classify(), brix_overlay_cli_reset(), brix_overlay_close(), brix_overlay_copyup(), brix_overlay_mkdir(), brix_overlay_mkdirs(), brix_overlay_open(), brix_overlay_read_upper(), brix_overlay_readlink(), brix_overlay_rename_upper(), brix_overlay_rmdir_upper(), brix_overlay_set_opaque(), brix_overlay_symlink(), brix_overlay_truncate(), brix_overlay_unlink_upper(), brix_overlay_utimens(), brix_overlay_whiteout(), brix_overlay_whiteout_clear(), brix_overlay_whiteout_set(), brix_prepare_close_inherited_fds(), brix_proxy_cleanup_splice(), brix_proxy_destroy(), brix_query_adler32_file(), brix_query_crc32_file(), brix_query_digest_file(), brix_readlink_confined_canon(), brix_reconnect(), brix_rename_beneath(), brix_rename_beneath_excl(), brix_reopen_bound_read_handle(), brix_setattr_confined_canon(), brix_ssi_open(), brix_sss_keytab_read(), brix_sss_keytab_write(), brix_sss_load_keytab(), brix_stage_mark_pending(), brix_stage_registry_init(), brix_staged_abort(), brix_staged_open(), brix_staged_open_resume(), brix_stat_beneath(), brix_streams_close(), brix_subprocess_capture(), brix_subprocess_child(), brix_symlink_confined_canon(), brix_tcp_connect(), brix_tier_load_master_key(), brix_tpc_prepare_pull(), brix_tpc_pull_thread(), brix_unlink_beneath(), brix_unlink_confined_canon(), brix_vfs_io_execute_opendir(), brix_wait41_main(), brix_xfer_agent_attach(), brix_xfer_run_reparented(), brix_xmeta_path_load(), brix_xmeta_path_lock(), brix_xmeta_path_unlock(), brix_zip_open_member(), brixcvmfs_mount_run(), brixcvmfs_setup_rw(), brixcvmfs_teardown_rw(), cache_fill_verify_origin(), cache_meta_read_legacy(), cache_origin_load_proxy_key(), cache_origin_load_proxy_pem(), cache_origin_load_sss_key(), chk_probe_checksum(), chk_probe_posc(), ckcheck_digest_local(), ckp_begin(), ckp_rollback(), cksum_compute_local(), ckv_read_sidecar_blob(), ckv_read_xmeta(), close(), cms_posix_apply(), commit_cross_device(), commit_staged_to_backend(), connect_one(), control_thread(), copy_unzip(), copy_web_download(), copy_zip_store(), copy_zip_store_local(), cs_root_lazy_posix(), csi_flush_open_file(), dashboard_download_body(), dashboard_download_open(), dashboard_files_opendir(), dashboard_read_config_file(), delegation_store_pem(), dial(), dig_authorize(), dig_register_fd_cleanup(), do_bench(), do_compare_davs(), dx_probe_checksum(), entry_cksum(), ev_accept_handler(), ev_do_pasv(), ev_do_port(), ev_grp_ctl(), fattr_dispatch_named(), fhandle_release_descriptors(), fix_down(), fp_accept_loop(), fp_oracle_run(), fp_replay_record_start(), fp_replay_record_stop(), gen_tpc_key(), http_download_attempt(), httpx_connect(), httpx_resumable_attempt(), imp_broker_accept(), imp_broker_reap(), imp_call_status(), imp_dial(), imp_drop_conn(), imp_get_or_list(), imp_make_listen(), imp_op_open(), imp_op_readlink(), imp_op_removexattr(), imp_op_rename_link(), imp_op_setattr(), imp_op_setxattr(), imp_op_stat(), imp_op_symlink(), imp_op_truncate(), imp_op_xattr_read(), imp_open_broker_fds(), imp_open_parent(), imp_serve_one(), imp_spawn_broker(), imp_with_parent(), io_engine_teardown(), listen_sa(), main(), main(), meta_read_part(), mint_write_tmp(), ngx_http_brix_dashboard_download_handler(), ns_copy_finalize(), oidc_drain_pipe(), oidc_run_child(), ov_clear_markers(), ov_cli_reset_contents(), ov_descend_child(), ov_open_dir(), ov_walk_parent_mk(), pblock_copy_one_block(), pblock_read_blocks(), pblock_write_blocks(), posix_be_open(), posix_close(), priv_run(), priv_run_stdin(), proxy_build_cleanup(), pt_readdir(), reap_read_marker_target(), relay_predial(), relay_pump(), relay_thread(), relay_web_to_web(), remote_md5(), rename_confined_canon_impl(), rw_mknod(), rw_release(), rw_truncate(), s3_get_verify(), s3_handle_upload_part_copy(), s3_mpu_assemble(), s3_put(), s3_put_try_sentinel(), scan_run_walk(), sd_cache_close(), sd_cache_partial_open(), sd_frm_close(), sd_frm_open(), sd_frm_staged_abort(), sd_frm_staged_commit(), sd_frm_staged_open(), sd_posix_cleanup(), sd_posix_close(), sd_posix_open(), sd_posix_opendir(), sever(), slurp(), slurp_credfile(), sp_read_file(), split_hostport(), stage_complete(), stage_journal_mark_failed(), stage_journal_move_to_deadletter(), stage_journal_update_rec(), stage_journal_write(), stage_reconcile_one(), staged_commit_internal(), stub_copyfile(), stub_recall_begin(), sync_cksum_match(), test_copyup(), test_mut_mkdirs_create(), tpc_connect(), tpc_core_open_local(), tpc_cred_oidc_agent_fetch(), tpc_done_sync_fail(), tpc_done_teardown_dst(), tpc_ms_prepare_output(), tpc_oidc_child_run(), tpc_token_oidc_agent(), tree_emit_file(), ucred_read_keyring(), ucred_read_s3(), ucred_read_token(), verify_compute_wire_hex(), verify_download_tmp(), watch_write_prom_atomic(), web_connect(), web_disconnect(), web_put_get_verify(), webdav_parse_multi(), webdav_put_persist_checksums(), webdav_put_verify_ingest_digest(), webdav_tpc_pmark_closesocket(), webdav_tpc_run_curl_multi_finish(), webdav_tpc_run_curl_pull_multi(), write_checksum(), write_file(), xfer_agent_spawn(), xfer_spawn_agent(), xmeta_path_write_sidecar(), xvfs_stage_fd(), zip_find_member_mapped(), zip_http_close_fd(), zip_http_stage_stored(), zip_open_archive_fd(), and zip_stage_archive_maybe().
ensure_conn()
static int ensure_conn (void) static
Definition at line 133 of file brixposix_preload.c.
References brix_connect(), brix_status_clear(), g_conn, g_connected, and g_url.
Referenced by remote_open(), remote_stat(), and statx().
fill_stat()
static void fill_stat (const brix_statinfo * si, struct stat * stbuf) static
Definition at line 190 of file brixposix_preload.c.
References brix_statinfo::flags, kXR_isDir, brix_statinfo::mtime, and brix_statinfo::size.
Referenced by remote_stat().
fstat()
int fstat (int fd, struct stat * stbuf)
Definition at line 443 of file brixposix_preload.c.
References fstat(), REAL, s, and slot_of().
Referenced by brix_cache_lock_is_stale(), brix_close_posc_commit(), brix_cns_emit_close(), brix_compressed_extent(), brix_cstore_partial_open(), brix_fd_kind(), brix_http_download(), brix_lstat_beneath(), brix_open_build_retstat(), brix_open_credfile(), brix_open_resolved_via_driver(), brix_open_validate_fd(), brix_read_serve_sendfile(), brix_reopen_bound_read_handle(), brix_sss_keytab_read(), brix_sss_load_keytab(), brix_stage_registry_init(), brix_staged_open_resume(), brix_stat_beneath(), brix_stat_child(), brix_tier_status(), brix_tpc_prepare_pull(), brix_zip_writer_add_fd(), ckp_begin(), ckp_recover_one(), commit_cross_device(), copy_zip_store_local(), csi_flush_open_file(), cstb_open_source(), dashboard_download_open(), dashboard_read_config_file(), fstat(), imp_op_open(), integrity_is_nonregular(), integrity_xattr_read(), integrity_xattr_write_rc(), main(), ov_classify_root(), s3_handle_upload_part_copy(), s3_mpu_assemble(), sd_block_fstat(), sd_frm_fstat(), sd_frm_open(), sd_posix_fstat(), sp_read_file(), srq_file_size(), stat_query_handle(), tpc_core_open_local(), tpc_done_reply_sync(), tpc_done_stat_trailer(), tpc_send_open_response(), xmeta_path_read_sidecar_fd(), zip_http_open_archive(), and zip_open_archive_fd().
fstat64()
int fstat64 (int fd, struct stat64 * stbuf)
Definition at line 514 of file brixposix_preload.c.
References fstat64(), REAL, s, and slot_of().
Referenced by fstat64().
fstatat()
int fstatat (int dirfd, const char * path, struct stat * stbuf, int flags)
Definition at line 459 of file brixposix_preload.c.
References fstatat(), map_path(), REAL, remote_stat(), and XRDC_PATH_MAX.
Referenced by brix_overlay_chmod(), brix_overlay_classify(), brix_overlay_mkdirs(), brix_vfs_io_dirlist_stat_entry(), ckp_recover_scan(), fstatat(), imp_op_stat(), ov_cli_reset_contents(), ov_marker_at(), rw_getattr(), test_classify(), vfs_walk_entry(), and xfer_resume_sweep_run().
fstatat64()
int fstatat64 (int dirfd, const char * path, struct stat64 * stbuf, int flags)
Definition at line 530 of file brixposix_preload.c.
References fstatat64(), map_path(), REAL, remote_stat(), stat(), and XRDC_PATH_MAX.
Referenced by fstatat64().
lseek()
off_t lseek (int fd, off_t offset, int whence)
Definition at line 353 of file brixposix_preload.c.
References lseek(), REAL, s, and slot_of().
Referenced by brix_vfs_memfile_materialize(), ckv_verify_one(), http_download_attempt(), lseek(), s3_get_verify(), tmpfile_with(), verify_compute_wire_hex(), and web_put_get_verify().
lseek64()
off_t lseek64 (int fd, off_t offset, int whence)
lstat()
int lstat (const char * path, struct stat * stbuf)
Definition at line 432 of file brixposix_preload.c.
References lstat(), map_path(), REAL, remote_stat(), and XRDC_PATH_MAX.
Referenced by brix_cred_stage_dir(), brix_fs_walk_handle_entry(), cktree_walk(), local_rmtree(), lstat(), mirror_delete_remote(), mirror_local_remove(), ov_cli_guard(), ov_cli_list_entry(), reap_entry_candidate(), test_cli(), tree_ul_entry(), and web_upload_walk().
lstat64()
int lstat64 (const char * path, struct stat64 * stbuf)
Definition at line 503 of file brixposix_preload.c.
References lstat64(), map_path(), REAL, remote_stat(), stat(), and XRDC_PATH_MAX.
Referenced by lstat64().
map_path()
static int map_path (const char * path, char * out, size_t outsz) static
Definition at line 101 of file brixposix_preload.c.
References g_base, g_enabled, g_once, g_prefix, g_prefix_len, and parse_vmp().
Referenced by access(), fstatat(), fstatat64(), lstat(), lstat64(), open(), openat(), stat(), stat64(), and statx().
open()
int open (const char * path, int flags, ...)
Definition at line 252 of file brixposix_preload.c.
References map_path(), open(), REAL, remote_open(), and XRDC_PATH_MAX.
Referenced by af_spawn_child(), af_umount_path(), baq_journal_write(), baq_reconcile_one(), brix_beneath_open_root(), brix_cache_lock_is_stale(), brix_cache_try_evict_lock(), brix_cache_try_lock(), brix_cache_verify_cvmfs_cas(), brix_cache_verify_part(), brix_chkpoint_recover_root(), brix_cks_verify_file(), brix_cli_cksum_main(), brix_credential_bearer(), brix_cstore_partial_open(), brix_http_open_rootfd(), brix_init_server_rootfd(), brix_open_credfile(), brix_open_posix_dispatch(), brix_open_root_fd(), brix_overlay_cli_reset(), brix_proxy_destroy(), brix_reopen_bound_read_handle(), brix_sd_posix_open_unconfined(), brix_ssi_open(), brix_sss_keytab_read(), brix_sss_keytab_write(), brix_sss_load_keytab(), brix_stage_mark_pending(), brix_stage_registry_init(), brix_staged_open_resume(), brix_tier_load_master_key(), brix_tier_status(), brix_vfs_open_confined_fd(), brix_xmeta_path_load(), brix_xmeta_path_lock(), brixcvmfs_open_clever_cache(), brixcvmfs_setup_rw(), cache_build_wt_stage(), cache_fill_verify_origin(), cache_meta_read_legacy(), cache_open_rootfd(), cache_origin_load_proxy_key(), cache_origin_load_proxy_pem(), cache_origin_load_sss_key(), ckcheck_digest_local(), ckp_begin(), ckp_rollback(), cksum_compute_local(), ckv_read_sidecar_blob(), ckv_read_xmeta(), commit_cross_device(), copy_zip_store(), copy_zip_store_local(), cs_root_lazy_posix(), csi_flush_open_file(), cstb_open_source(), dashboard_read_config_file(), delegation_store_pem(), dig_authorize(), entry_cksum(), exec_create_online(), exec_open_online(), fix_up(), fp_replay_record_start(), gen_tpc_key(), imp_open_broker_fds(), main(), meta_read_part(), mint_write_tmp(), open(), open_download_temp(), pblock_copy_one_block(), pblock_read_blocks(), pblock_write_blocks(), priv_run(), priv_run_stdin(), pxy_assemble_pem(), reap_read_marker_target(), sp_read_file(), stage_complete(), stage_journal_mark_failed(), stage_journal_move_to_deadletter(), stage_journal_update_rec(), stage_journal_write(), stage_reconcile_one(), stub_copyfile(), stub_create_online(), stub_open_online(), stub_recall_begin(), sync_cksum_match(), tpc_ms_prepare_output(), tree_emit_file(), ucred_read_keyring(), ucred_read_s3(), ucred_read_token(), webdav_parse_multi(), webdav_put_verify_ingest_digest(), write_file(), xfer_audit_try_open(), xmeta_path_write_sidecar(), and xvfs_stage_fd().
open64()
int open64 (const char * path, int flags, ...)
openat()
int openat (int dirfd, const char * path, int flags, ...)
Definition at line 274 of file brixposix_preload.c.
References map_path(), openat(), REAL, remote_open(), and XRDC_PATH_MAX.
Referenced by brix_dirlist_checksum_token(), brix_open_confined_canon(), brix_open_dir_no_symlink(), brix_overlay_classify(), brix_overlay_copyup(), brix_overlay_init(), brix_overlay_open(), brix_overlay_set_opaque(), brix_overlay_whiteout_set(), openat(), ov_clear_markers(), ov_cli_reset_contents(), ov_descend_child(), ov_descend_dir(), ov_open_dir(), ov_walk_parent_mk(), pt_readdir(), rw_open_common(), and rw_truncate().
openat64()
int openat64 (int dirfd, const char * path, int flags, ...)
parse_vmp()
static void parse_vmp (void) static
Definition at line 59 of file brixposix_preload.c.
References brix_endpoint_parse(), brix_status_clear(), g_base, g_enabled, g_prefix, g_prefix_len, g_url, and brix_url::path.
Referenced by map_path().
pread()
ssize_t pread (int fd, void * buf, size_t count, off_t offset)
Definition at line 326 of file brixposix_preload.c.
References brix_kxr_to_errno(), brix_rfile_pread(), brix_status_clear(), g_lock, pread(), REAL, s, and slot_of().
Referenced by bat_upload_src_fd(), brix_handle_clone(), brix_http_body_staged_spooled_buf(), brix_tier_status(), brix_zip_member_extract(), brix_zip_open(), ckv_read_sidecar_blob(), ckv_read_xmeta(), csi_flush_recompute_block(), find_eocd(), member_data_offset(), pblock_copy_one_block(), pblock_read_blocks(), pread(), read_exact(), rw_read(), sd_frm_pread(), sd_posix_pread(), test_copyup(), verify_content(), writer_ingest_bounce(), xmeta_path_read_sidecar_fd(), zip_locate_cd(), zip_promote_zip64(), zip_read_at(), zip_read_central_dir(), zip_resolve_data_off(), zipw_local_pread(), zw_crc_pass(), and zw_stream_deflate().
pread64()
ssize_t pread64 (int fd, void * buf, size_t count, off_t offset)
read()
ssize_t read (int fd, void * buf, size_t count)
Definition at line 299 of file brixposix_preload.c.
References brix_kxr_to_errno(), brix_rfile_pread(), brix_status_clear(), g_lock, read(), REAL, s, and slot_of().
Referenced by aconn_read_plain(), af_control_thread(), baq_reconcile_one(), brix_cache_lock_is_stale(), brix_credential_bearer(), brix_subprocess_drain(), brix_tier_load_master_key(), brix_token_check_read(), cache_meta_read_legacy(), control_thread(), dashboard_read_config_file(), gen_tpc_key(), http_get_read_response(), httpx_read_some(), imp_read_full(), kaconn_read_some(), loop_thread(), meta_read_part(), oidc_drain_pipe(), plain_read_full(), pump_src_local(), read(), reap_read_marker_target(), relay_pump_dir(), s3_get_verify(), sp_read_file(), stage_complete(), stage_journal_mark_failed(), stage_journal_move_to_deadletter(), stage_reconcile_one(), stub_copyfile(), token_scope_from_parsed(), tpc_oidc_read_all(), ucred_read_keyring(), ucred_read_s3(), ucred_read_token(), upload_copy_loop(), web_put_get_verify(), web_read_some(), xfer_read_exact(), and xfer_read_full().
remote_open()
static int remote_open (const char * remote) static
Definition at line 215 of file brixposix_preload.c.
References brix_kxr_to_errno(), brix_rfile_open_read(), brix_stat(), brix_status_clear(), ensure_conn(), g_conn, g_lock, g_slots, s, brix_statinfo::size, slot_alloc(), and XFS_FD_BASE.
Referenced by open(), and openat().
remote_stat()
static int remote_stat (const char * remote, struct stat * stbuf) static
Definition at line 397 of file brixposix_preload.c.
References brix_kxr_to_errno(), brix_stat(), brix_status_clear(), ensure_conn(), fill_stat(), g_conn, and g_lock.
Referenced by access(), fstatat(), fstatat64(), lstat(), lstat64(), stat(), and stat64().
slot_alloc()
static int slot_alloc (void) static
Definition at line 162 of file brixposix_preload.c.
References g_slots, xfs_slot::used, and XFS_FD_MAX.
Referenced by remote_open().
slot_of()
static xfs_slot * slot_of (int fd) static
Definition at line 176 of file brixposix_preload.c.
References g_slots, XFS_FD_BASE, and XFS_FD_MAX.
Referenced by close(), fstat(), fstat64(), lseek(), pread(), and read().
stat()
int stat (const char * path, struct stat * stbuf)
Definition at line 421 of file brixposix_preload.c.
References map_path(), REAL, remote_stat(), stat(), and XRDC_PATH_MAX.
Referenced by access(), aconn_dispatch_frame(), aconn_dispatch_response(), aconn_parse(), block_be_stat(), brix_apply_parent_group_policy_impl(), brix_cache_commit_staged(), brix_cache_file_ready(), brix_cache_hit_fresh(), brix_cache_lock_is_stale(), brix_cache_path_flag(), brix_cache_purge_setup(), brix_cache_reap_dirty(), brix_cache_try_evict_lock(), brix_close_posc_commit(), brix_cms_blfile_poll(), brix_cns_emit_close(), brix_compressed_extent(), brix_cred_stage_dir(), brix_crl_reload_handler(), brix_csi_flush(), brix_cstore_partial_open(), brix_dirlist_entry_meta(), brix_fd_kind(), brix_fs_remove_tree_entry(), brix_fs_walk_handle_entry(), brix_ftp_build_gsi(), brix_handle_stat(), brix_http_download(), brix_ns_local_copy(), brix_ns_rename(), brix_open_attach_csi(), brix_open_build_retstat(), brix_open_cached_read(), brix_open_credfile(), brix_open_init_handle(), brix_open_read_probe(), brix_open_resolved_file(), brix_open_resolved_via_driver(), brix_open_resume_inplace_decide(), brix_open_validate_fd(), brix_overlay_chmod(), brix_overlay_classify(), brix_overlay_mkdirs(), brix_pki_is_regular_file(), brix_prepare_check_path(), brix_proxy_destroy(), brix_read_serve_sendfile(), brix_rebuild_gsi_store(), brix_reopen_bound_read_handle(), brix_shared_credential_dir_ensure(), brix_sss_keytab_read(), brix_sss_load_keytab(), brix_stage_registry_init(), brix_staged_open_resume(), brix_stat_child(), brix_stat_type_cstr(), brix_statx_process_path(), brix_tier_default_stage_store(), brix_tier_status(), brix_token_jwks_try_reload(), brix_token_load_and_register_jwks(), brix_token_registry_load(), brix_tpc_prepare_pull(), brix_uring_panic_handler(), brix_validate_path(), brix_vfs_copy_ns_bytes(), brix_vfs_copyfile(), brix_vfs_io_dirlist_stat_entry(), brix_vfs_probe(), brix_vfs_staged_commit(), brix_vfs_stat_impl(), brix_vfs_walk(), brix_wt_default_decide(), brix_zip_open_member(), brix_zip_writer_add_fd(), ckp_begin(), ckp_query(), ckp_recover_one(), ckp_recover_scan(), cktree_walk(), cls(), cms_frame_state(), commit_cross_device(), copy_zip_store_local(), cstb_open_source(), dashboard_read_config_file(), dest_is_dir(), dl_sync_skip(), entry_meta(), evict_collect_visit(), exec_residency(), fstatat64(), imp_op_open(), imp_op_stat(), integrity_is_nonregular(), integrity_record_read(), integrity_record_write(), integrity_xattr_read(), integrity_xattr_write_rc(), is_local_dir(), load_master_key(), local_rmtree(), locate_check_data_server(), lstat64(), main(), merged_exists(), migrate_one_object(), mirror_delete_remote(), mirror_local_remove(), ngx_http_brix_dashboard_download_handler(), ngx_http_brix_webdav_tpc_handle_copy(), ns_copy_validate(), ns_delete_probe(), origin_tls_load_verify(), ov_cli_guard(), ov_cli_list_entry(), ov_cli_reset_contents(), ov_marker_at(), pki_load_crls(), pki_load_crls_from_dirent(), posix_be_stat(), propfind_do(), propfind_walk_emit(), qprep_status_for_path(), read_status_frame(), reap_entry_candidate(), reap_one_marker(), resp_deliver(), rw_copyup(), rw_getxattr(), rw_meta_apply(), rw_overlay_xattr(), rw_readdir(), rw_readlink(), rw_truncate(), s3_chunk_finalize(), s3_entry_fill_stat(), s3_get_serve_multirange(), s3_handle_copy_object(), s3_handle_head_bucket(), s3_handle_upload_part_copy(), s3_list_collect_sorted(), s3_mpu_assemble(), s3_multipart_complete_body_handler_inner(), s3_post_write_object(), s3_put_aio_done(), s3o_apply_ca(), s3put_emit_etag(), sd_block_fstat(), sd_frm_fstat(), sd_frm_open(), sd_posix_fstat(), sd_posix_server_copy(), sd_posix_stat(), sd_xroot_origin_build_ca_store(), sp_read_file(), srq_file_size(), STACK_OF(), STACK_OF(), stat(), stat64(), stat_manager_route(), stat_query_handle(), stub_migrate(), stub_recall_begin(), stub_recall_poll(), stub_residency(), test_classify(), test_cli(), test_copyup(), test_mut_attrs(), test_mut_mkdirs_create(), tpc_core_open_local(), tpc_done_reply_sync(), tpc_done_stat_trailer(), tpc_marker_build_ctx(), tpc_marker_final_bytes(), tpc_marker_send_all(), tpc_send_open_response(), tpc_thread_record_size(), tree_ul_entry(), valid_iface(), vfs_copytree_entry(), vfs_readdir_stat_child(), vfs_walk_entry(), web_upload_walk(), webdav_get_add_xrdhttp_headers(), webdav_handle_delete(), webdav_handle_head(), webdav_handle_move(), webdav_proppatch_do(), webdav_put_precheck(), webdav_search_do(), webdav_tpc_finish_pull_success(), webdav_tpc_handle_push(), webdav_tpc_prepare_pull_target(), xfer_resume_sweep_run(), xfs_readdir(), xfs_readdir(), xmeta_path_read_sidecar_fd(), and zip_http_open_archive().
stat64()
int stat64 (const char * path, struct stat64 * stbuf)
Definition at line 492 of file brixposix_preload.c.
References map_path(), REAL, remote_stat(), stat(), stat64(), and XRDC_PATH_MAX.
Referenced by stat64().
statx()
int statx (int dirfd, const char * path, int flags, unsigned int mask, struct statx * stxbuf)
Definition at line 547 of file brixposix_preload.c.
References brix_kxr_to_errno(), brix_stat(), brix_status_clear(), ensure_conn(), brix_statinfo::flags, g_conn, g_lock, kXR_isDir, map_path(), brix_statinfo::mtime, REAL, brix_statinfo::size, statx(), and XRDC_PATH_MAX.
Referenced by dashboard_files_scan(), and statx().
Variable Documentation
g_base
char g_base[XRDC_PATH_MAX] static
Definition at line 53 of file brixposix_preload.c.
Referenced by map_path(), and parse_vmp().
g_conn
brix_conn g_conn static
Definition at line 55 of file brixposix_preload.c.
Referenced by ensure_conn(), remote_open(), remote_stat(), and statx().
g_connected
int g_connected static
Definition at line 56 of file brixposix_preload.c.
Referenced by ensure_conn().
g_enabled
int g_enabled static
Definition at line 49 of file brixposix_preload.c.
Referenced by map_path(), and parse_vmp().
g_lock
pthread_mutex_t g_lock = PTHREAD_MUTEX_INITIALIZER static
Definition at line 47 of file brixposix_preload.c.
Referenced by close(), pread(), read(), remote_open(), remote_stat(), and statx().
g_once
pthread_once_t g_once = PTHREAD_ONCE_INIT static
Definition at line 46 of file brixposix_preload.c.
Referenced by map_path().
g_prefix
char g_prefix[256] static
Definition at line 50 of file brixposix_preload.c.
Referenced by map_path(), and parse_vmp().
g_prefix_len
size_t g_prefix_len static
Definition at line 51 of file brixposix_preload.c.
Referenced by map_path(), and parse_vmp().
g_slots
xfs_slot g_slots[1024] static
Definition at line 159 of file brixposix_preload.c.
Referenced by remote_open(), slot_alloc(), and slot_of().
g_url
brix_url g_url static
Definition at line 52 of file brixposix_preload.c.
Referenced by ensure_conn(), and parse_vmp().