nginx-xrootd: src/auth/impersonate/broker_internal.h File Reference
broker_internal.h File Reference
#include "impersonate.h"
#include "impersonate_proto.h"
#include "core/compat/log_diag.h"
#include <errno.h>
#include <fcntl.h>
#include <grp.h>
#include <poll.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/fsuid.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/xattr.h>
#include <linux/openat2.h>
#include <linux/capability.h>
#include <sys/prctl.h>
Macros
#define IMP_BROKER_MAXCONN 1024
#define IMP_REFUSE_PRIV (-2)
#define RENAME_NOREPLACE (1u << 0)
Functions
int imp_peer_allowed (int conn_fd)
int imp_capset_setuid_setgid (int with_effective, ngx_log_t *log)
int imp_drop_to_service_user (ngx_log_t *log)
int imp_become (const brix_idmap_creds_t *cr)
void imp_restore (void)
const char * imp_rel (const char *path)
int imp_openat2 (int rootfd, const char *rel, uint32_t flags, uint32_t mode)
int imp_open_parent (int rootfd, const char *rel, char *scratch, const char **base)
void imp_fill_stat (imp_stat_t *o, const struct stat *s)
int imp_xattr_open (int rootfd, const char *rel)
int imp_xattr_name_ok (const char *name)
size_t imp_xattr_filter_user (char *list, size_t len)
int imp_do_rename (int sfd, const char *sbase, int dfd, const char *dbase, int noreplace)
int imp_do_op (int rootfd, const imp_req_t *req, imp_rep_t *rep, int *out_fd, char *data_out, size_t data_max, const char *data_in, size_t data_in_len)
int imp_read_full (int fd, void *buf, size_t n)
int imp_send_reply (int conn_fd, const imp_rep_t *rep, int fd, const void *data, size_t data_len)
int imp_serve_one (int conn_fd, int rootfd, ngx_log_t *log)
Variables
uid_t imp_base_uid
gid_t imp_base_gid
gid_t imp_base_groups [32]
int imp_base_ngroups
uid_t imp_self_uid
Macro Definition Documentation
IMP_BROKER_MAXCONN
#define IMP_BROKER_MAXCONN 1024
Definition at line 27 of file broker_internal.h.
IMP_REFUSE_PRIV
#define IMP_REFUSE_PRIV (-2)
Definition at line 28 of file broker_internal.h.
RENAME_NOREPLACE
#define RENAME_NOREPLACE (1u << 0)
Definition at line 36 of file broker_internal.h.
Function Documentation
imp_become()
int imp_become (const brix_idmap_creds_t * cr)
Definition at line 203 of file broker_creds.c.
References brix_imp_broker_allow_uid, brix_imp_creds_privileged(), BRIX_IMP_HARD_MIN_ID, brix_idmap_creds_t::gid, brix_idmap_creds_t::groups, IMP_REFUSE_PRIV, imp_self_uid, brix_idmap_creds_t::ngroups, and brix_idmap_creds_t::uid.
Referenced by imp_serve_one().
imp_capset_setuid_setgid()
int imp_capset_setuid_setgid (int with_effective, ngx_log_t * log)
Definition at line 28 of file broker_creds.c.
References log.
Referenced by brix_imp_broker_drop_caps(), and imp_drop_to_service_user().
imp_do_op()
int imp_do_op (int rootfd, const imp_req_t * req, imp_rep_t * rep, int * out_fd, char * data_out, size_t data_max, const char * data_in, size_t data_in_len)
Definition at line 192 of file broker_ops.c.
References imp_req_t::atime_nsec, imp_req_t::atime_sec, imp_req_t::attr_flags, BRIX_IMP_HARD_MIN_ID, close(), imp_rep_t::data_len, fstat(), fstatat(), IMP_ATTR_OWNER, IMP_ATTR_TIMES, imp_do_rename(), imp_fill_stat(), IMP_OP_CHMOD, IMP_OP_CHOWN, IMP_OP_GETXATTR, IMP_OP_LINK, IMP_OP_LISTXATTR, IMP_OP_LSTAT, IMP_OP_MKDIR, IMP_OP_OPEN, IMP_OP_READLINK, IMP_OP_REMOVEXATTR, IMP_OP_RENAME, IMP_OP_RENAME_NOREPLACE, IMP_OP_RMDIR, IMP_OP_SETATTR, IMP_OP_SETXATTR, IMP_OP_STAT, IMP_OP_SYMLINK, IMP_OP_TRUNCATE, IMP_OP_UNLINK, imp_open_parent(), imp_openat2(), IMP_PATH_MAX, imp_rel(), IMP_REP_HAS_DATA, IMP_REP_HAS_FD, IMP_REP_HAS_STAT, imp_xattr_filter_user(), imp_xattr_name_ok(), imp_xattr_open(), imp_req_t::length, imp_req_t::mode, imp_req_t::mtime_nsec, imp_req_t::mtime_sec, O_PATH, imp_req_t::op, imp_req_t::open_flags, imp_req_t::path, imp_req_t::path2, imp_rep_t::rep_flags, imp_req_t::set_gid, imp_req_t::set_uid, imp_rep_t::st, and stat().
Referenced by imp_serve_one().
imp_do_rename()
int imp_do_rename (int sfd, const char * sbase, int dfd, const char * dbase, int noreplace)
Definition at line 167 of file broker_ops.c.
References RENAME_NOREPLACE.
Referenced by imp_do_op().
imp_drop_to_service_user()
int imp_drop_to_service_user (ngx_log_t * log)
Definition at line 59 of file broker_creds.c.
References BRIX_DIAG_EMERG, brix_imp_broker_user_gid, brix_imp_broker_user_uid, imp_capset_setuid_setgid(), and log.
Referenced by brix_imp_broker_drop_caps().
imp_fill_stat()
void imp_fill_stat (imp_stat_t * o, const struct stat * s)
Definition at line 73 of file broker_ops.c.
References imp_stat_t::atime, imp_stat_t::blksize, imp_stat_t::blocks, imp_stat_t::ctime, imp_stat_t::dev, imp_stat_t::gid, imp_stat_t::ino, imp_stat_t::mode, imp_stat_t::mtime, imp_stat_t::nlink, s, imp_stat_t::size, and imp_stat_t::uid.
Referenced by imp_do_op().
imp_open_parent()
int imp_open_parent (int rootfd, const char * rel, char * scratch, const char ** base)
Definition at line 41 of file broker_ops.c.
References close(), imp_openat2(), IMP_PATH_MAX, imp_rel(), and O_PATH.
Referenced by imp_do_op().
imp_openat2()
int imp_openat2 (int rootfd, const char * rel, uint32_t flags, uint32_t mode)
Definition at line 10 of file broker_ops.c.
References mode.
Referenced by imp_do_op(), imp_open_parent(), and imp_xattr_open().
imp_peer_allowed()
int imp_peer_allowed (int conn_fd)
Definition at line 20 of file broker.c.
References brix_imp_broker_allow_uid.
Referenced by brix_imp_broker_run().
imp_read_full()
int imp_read_full (int fd, void * buf, size_t n)
Definition at line 38 of file broker.c.
References read().
Referenced by imp_serve_one().
imp_rel()
const char * imp_rel (const char * path)
Definition at line 263 of file broker_creds.c.
Referenced by imp_do_op(), and imp_open_parent().
imp_restore()
void imp_restore (void)
Definition at line 252 of file broker_creds.c.
References imp_base_gid, imp_base_groups, imp_base_ngroups, and imp_base_uid.
Referenced by imp_serve_one().
imp_send_reply()
int imp_send_reply (int conn_fd, const imp_rep_t * rep, int fd, const void * data, size_t data_len)
Definition at line 61 of file broker.c.
References c.
Referenced by imp_serve_one().
imp_serve_one()
int imp_serve_one (int conn_fd, int rootfd, ngx_log_t * log)
Definition at line 106 of file broker.c.
References BRIX_IDMAP_OK, brix_idmap_resolve(), BRIX_IDMAP_SQUASH, BRIX_IMP_HARD_MIN_ID, close(), imp_rep_t::data_len, brix_idmap_creds_t::gid, imp_become(), imp_do_op(), IMP_OP_PING, IMP_OP_SETXATTR, IMP_PATH_MAX, IMP_PRINC_MAX, IMP_PROTO_VERSION, imp_read_full(), IMP_REFUSE_PRIV, imp_restore(), imp_send_reply(), IMP_STATUS_BADREQ, IMP_STATUS_DENY, IMP_STATUS_OK, IMP_STATUS_PRIV_REFUSED, IMP_XATTR_MAX, log, imp_req_t::op, imp_req_t::path, imp_req_t::path2, imp_req_t::principal, imp_req_t::req_data_len, imp_rep_t::status, brix_idmap_creds_t::uid, and imp_req_t::version.
Referenced by brix_imp_broker_run().
imp_xattr_filter_user()
size_t imp_xattr_filter_user (char * list, size_t len)
Definition at line 132 of file broker_ops.c.
References imp_xattr_name_ok().
Referenced by imp_do_op().
imp_xattr_name_ok()
int imp_xattr_name_ok (const char * name)
Definition at line 116 of file broker_ops.c.
References name.
Referenced by imp_do_op(), and imp_xattr_filter_user().
imp_xattr_open()
int imp_xattr_open (int rootfd, const char * rel)
Definition at line 102 of file broker_ops.c.
References imp_openat2().
Referenced by imp_do_op().
Variable Documentation
imp_base_gid
gid_t imp_base_gid extern
Definition at line 10 of file broker.c.
Referenced by brix_imp_broker_run(), and imp_restore().
imp_base_groups
gid_t imp_base_groups[32] extern
Definition at line 12 of file broker.c.
Referenced by brix_imp_broker_run(), and imp_restore().
imp_base_ngroups
int imp_base_ngroups extern
Definition at line 14 of file broker.c.
Referenced by brix_imp_broker_run(), and imp_restore().
imp_base_uid
uid_t imp_base_uid extern
Definition at line 8 of file broker.c.
Referenced by brix_imp_broker_run(), and imp_restore().
imp_self_uid
uid_t imp_self_uid extern
Definition at line 16 of file broker.c.
Referenced by brix_imp_broker_run(), and imp_become().