nginx-xrootd: src/auth/impersonate/broker_ops_ns.c File Reference
broker_ops_ns.c File Reference
#include "broker_internal.h"
#include "broker_ops_internal.h"
Typedefs
typedef int(* imp_parent_fn_t) (int pfd, const char *base, const imp_op_ctx_t *c)
Functions
static int imp_with_parent (const imp_op_ctx_t *c, imp_parent_fn_t step)
static int imp_step_mkdir (int pfd, const char *base, const imp_op_ctx_t *c)
int imp_op_mkdir (const imp_op_ctx_t *c)
static int imp_step_unlink (int pfd, const char *base, const imp_op_ctx_t *c)
int imp_op_unlink (const imp_op_ctx_t *c)
static int imp_step_chmod (int pfd, const char *base, const imp_op_ctx_t *c)
int imp_op_chmod (const imp_op_ctx_t *c)
static int imp_step_chown (int pfd, const char *base, const imp_op_ctx_t *c)
int imp_op_chown (const imp_op_ctx_t *c)
int imp_op_rename_link (const imp_op_ctx_t *c)
int imp_op_setattr (const imp_op_ctx_t *c)
int imp_op_symlink (const imp_op_ctx_t *c)
int imp_op_readlink (const imp_op_ctx_t *c)
Typedef Documentation
imp_parent_fn_t
typedef int(* imp_parent_fn_t) (int pfd, const char *base, const imp_op_ctx_t *c)
Definition at line 33 of file broker_ops_ns.c.
Function Documentation
imp_op_chmod()
int imp_op_chmod (const imp_op_ctx_t * c)
Definition at line 124 of file broker_ops_ns.c.
References c, imp_step_chmod(), and imp_with_parent().
imp_op_chown()
int imp_op_chown (const imp_op_ctx_t * c)
Definition at line 144 of file broker_ops_ns.c.
References c, imp_step_chown(), and imp_with_parent().
imp_op_mkdir()
int imp_op_mkdir (const imp_op_ctx_t * c)
Definition at line 84 of file broker_ops_ns.c.
References c, imp_step_mkdir(), and imp_with_parent().
imp_op_readlink()
int imp_op_readlink (const imp_op_ctx_t * c)
Definition at line 255 of file broker_ops_ns.c.
References c, close(), imp_open_parent(), IMP_PATH_MAX, and IMP_REP_HAS_DATA.
imp_op_rename_link()
int imp_op_rename_link (const imp_op_ctx_t * c)
Definition at line 156 of file broker_ops_ns.c.
References c, close(), imp_do_rename(), IMP_OP_LINK, IMP_OP_RENAME_NOREPLACE, imp_open_parent(), IMP_PATH_MAX, and imp_rel().
imp_op_setattr()
int imp_op_setattr (const imp_op_ctx_t * c)
Definition at line 192 of file broker_ops_ns.c.
References c, close(), IMP_ATTR_OWNER, IMP_ATTR_TIMES, imp_open_parent(), and IMP_PATH_MAX.
imp_op_symlink()
int imp_op_symlink (const imp_op_ctx_t * c)
Definition at line 234 of file broker_ops_ns.c.
References c, close(), imp_open_parent(), and IMP_PATH_MAX.
imp_op_unlink()
int imp_op_unlink (const imp_op_ctx_t * c)
Definition at line 105 of file broker_ops_ns.c.
References c, imp_step_unlink(), and imp_with_parent().
imp_step_chmod()
static int imp_step_chmod (int pfd, const char * base, const imp_op_ctx_t * c) static
Definition at line 113 of file broker_ops_ns.c.
References c.
Referenced by imp_op_chmod().
imp_step_chown()
static int imp_step_chown (int pfd, const char * base, const imp_op_ctx_t * c) static
Definition at line 132 of file broker_ops_ns.c.
References c.
Referenced by imp_op_chown().
imp_step_mkdir()
static int imp_step_mkdir (int pfd, const char * base, const imp_op_ctx_t * c) static
Definition at line 72 of file broker_ops_ns.c.
References c.
Referenced by imp_op_mkdir().
imp_step_unlink()
static int imp_step_unlink (int pfd, const char * base, const imp_op_ctx_t * c) static
Definition at line 92 of file broker_ops_ns.c.
References c, and IMP_OP_RMDIR.
Referenced by imp_op_unlink().
imp_with_parent()
static int imp_with_parent (const imp_op_ctx_t * c, imp_parent_fn_t step) static
Definition at line 54 of file broker_ops_ns.c.
References c, close(), imp_open_parent(), and IMP_PATH_MAX.
Referenced by imp_op_chmod(), imp_op_chown(), imp_op_mkdir(), and imp_op_unlink().