nginx-xrootd: src/auth/impersonate/broker.c File Reference
broker.c File Reference
#include "broker_internal.h"
Functions
int imp_peer_allowed (int conn_fd)
int imp_read_full (int fd, void *buf, size_t n)
int imp_send_reply (int conn_fd, const imp_rep_t *rep, int fd, const void *data, size_t data_len)
static int imp_recv_request (int conn_fd, imp_req_t *req, imp_rep_t *rep, char *data_in, size_t *in_len)
static void imp_fatal_priv_refused (int conn_fd, imp_rep_t *rep, const brix_idmap_creds_t *creds, ngx_log_t *log)
static int imp_dispatch_op (int conn_fd, imp_op_ctx_t *op_ctx, const brix_idmap_creds_t *creds, ngx_log_t *log)
int imp_serve_one (int conn_fd, int rootfd, ngx_log_t *log)
static int imp_broker_init_creds (ngx_log_t *log)
static void imp_broker_accept (int listen_fd, struct pollfd *pfds, nfds_t *nfds, ngx_log_t *log)
static void imp_broker_reap (struct pollfd *pfds, nfds_t *nfds, int rootfd, ngx_log_t *log)
int brix_imp_broker_run (int listen_fd, int rootfd, const volatile sig_atomic_t *stop, ngx_log_t *log)
Variables
uid_t brix_imp_broker_allow_uid = 0
uid_t imp_base_uid
gid_t imp_base_gid
gid_t imp_base_groups [32]
int imp_base_ngroups
uid_t imp_self_uid
Function Documentation
brix_imp_broker_run()
int brix_imp_broker_run (int listen_fd, int rootfd, const volatile sig_atomic_t * stop, ngx_log_t * log)
Definition at line 413 of file broker.c.
References imp_broker_accept(), imp_broker_init_creds(), IMP_BROKER_MAXCONN, imp_broker_reap(), and log.
Referenced by imp_broker_child().
imp_broker_accept()
static void imp_broker_accept (int listen_fd, struct pollfd * pfds, nfds_t * nfds, ngx_log_t * log) static
Definition at line 344 of file broker.c.
References c, close(), IMP_BROKER_MAXCONN, imp_peer_allowed(), and log.
Referenced by brix_imp_broker_run().
imp_broker_init_creds()
static int imp_broker_init_creds (ngx_log_t * log) static
Definition at line 314 of file broker.c.
References BRIX_IDMAP_MAXGROUPS, brix_imp_broker_drop_caps(), imp_base_gid, imp_base_groups, imp_base_ngroups, imp_base_uid, imp_self_uid, and log.
Referenced by brix_imp_broker_run().
imp_broker_reap()
static void imp_broker_reap (struct pollfd * pfds, nfds_t * nfds, int rootfd, ngx_log_t * log) static
Definition at line 387 of file broker.c.
References close(), imp_serve_one(), and log.
Referenced by brix_imp_broker_run().
imp_dispatch_op()
static int imp_dispatch_op (int conn_fd, imp_op_ctx_t * op_ctx, const brix_idmap_creds_t * creds, ngx_log_t * log) static
Definition at line 211 of file broker.c.
References imp_become(), imp_do_op(), imp_fatal_priv_refused(), IMP_REFUSE_PRIV, imp_restore(), log, imp_op_ctx_t::rel, imp_op_ctx_t::rep, and brix_idmap_creds_t::uid.
Referenced by imp_serve_one().
imp_fatal_priv_refused()
static void imp_fatal_priv_refused (int conn_fd, imp_rep_t * rep, const brix_idmap_creds_t * creds, ngx_log_t * log) static
Definition at line 177 of file broker.c.
References BRIX_IMP_HARD_MIN_ID, brix_idmap_creds_t::gid, imp_send_reply(), IMP_STATUS_PRIV_REFUSED, log, imp_rep_t::status, and brix_idmap_creds_t::uid.
Referenced by imp_dispatch_op().
imp_peer_allowed()
int imp_peer_allowed (int conn_fd)
Definition at line 20 of file broker.c.
References brix_imp_broker_allow_uid.
Referenced by imp_broker_accept().
imp_read_full()
int imp_read_full (int fd, void * buf, size_t n)
Definition at line 38 of file broker.c.
References read().
Referenced by imp_recv_request().
imp_recv_request()
static int imp_recv_request (int conn_fd, imp_req_t * req, imp_rep_t * rep, char * data_in, size_t * in_len) static
Definition at line 118 of file broker.c.
References IMP_OP_SETXATTR, IMP_PATH_MAX, IMP_PRINC_MAX, IMP_PROTO_VERSION, imp_read_full(), imp_send_reply(), IMP_STATUS_BADREQ, IMP_XATTR_MAX, imp_req_t::op, imp_req_t::path, imp_req_t::path2, imp_req_t::principal, imp_req_t::req_data_len, imp_rep_t::status, and imp_req_t::version.
Referenced by imp_serve_one().
imp_send_reply()
int imp_send_reply (int conn_fd, const imp_rep_t * rep, int fd, const void * data, size_t data_len)
Definition at line 61 of file broker.c.
References c, and ngx_memcpy.
Referenced by imp_fatal_priv_refused(), imp_recv_request(), and imp_serve_one().
imp_serve_one()
int imp_serve_one (int conn_fd, int rootfd, ngx_log_t * log)
Definition at line 240 of file broker.c.
References BRIX_IDMAP_OK, brix_idmap_resolve(), BRIX_IDMAP_SQUASH, close(), imp_op_ctx_t::data_in, imp_op_ctx_t::data_in_len, imp_rep_t::data_len, imp_op_ctx_t::data_max, imp_op_ctx_t::data_out, imp_dispatch_op(), IMP_OP_PING, imp_recv_request(), imp_send_reply(), IMP_STATUS_BADREQ, IMP_STATUS_DENY, IMP_STATUS_OK, IMP_XATTR_MAX, log, imp_req_t::op, imp_op_ctx_t::out_fd, imp_req_t::principal, imp_op_ctx_t::rel, imp_op_ctx_t::rep, imp_op_ctx_t::req, imp_op_ctx_t::rootfd, and imp_rep_t::status.
Referenced by imp_broker_reap().
Variable Documentation
brix_imp_broker_allow_uid
uid_t brix_imp_broker_allow_uid = 0
Definition at line 7 of file broker.c.
Referenced by brix_imp_init_module(), imp_become(), and imp_peer_allowed().
imp_base_gid
gid_t imp_base_gid
Definition at line 10 of file broker.c.
Referenced by imp_broker_init_creds(), and imp_restore().
imp_base_groups
gid_t imp_base_groups[32]
Definition at line 12 of file broker.c.
Referenced by imp_broker_init_creds(), and imp_restore().
imp_base_ngroups
int imp_base_ngroups
Definition at line 14 of file broker.c.
Referenced by imp_broker_init_creds(), and imp_restore().
imp_base_uid
uid_t imp_base_uid
Definition at line 8 of file broker.c.
Referenced by imp_broker_init_creds(), and imp_restore().
imp_self_uid
uid_t imp_self_uid
Definition at line 16 of file broker.c.
Referenced by imp_become(), and imp_broker_init_creds().