nginx-xrootd: src/auth/impersonate/broker_ops.c File Reference
broker_ops.c File Reference
#include "broker_internal.h"
#include "broker_ops_internal.h"
Typedefs
typedef int(* imp_op_fn_t) (const imp_op_ctx_t *c)
Functions
int imp_openat2 (int rootfd, const char *rel, uint32_t flags, uint32_t mode)
int imp_open_parent (int rootfd, const char *rel, char *scratch, const char **base)
void imp_fill_stat (imp_stat_t *o, const struct stat *s)
int imp_xattr_open (int rootfd, const char *rel)
int imp_xattr_name_ok (const char *name)
size_t imp_xattr_filter_user (char *list, size_t len)
int imp_do_rename (int sfd, const char *sbase, int dfd, const char *dbase, int noreplace)
static int imp_op_open (const imp_op_ctx_t *c)
static int imp_op_stat (const imp_op_ctx_t *c)
static int imp_op_truncate (const imp_op_ctx_t *c)
static int imp_op_xattr_read (const imp_op_ctx_t *c)
static int imp_op_setxattr (const imp_op_ctx_t *c)
static int imp_op_removexattr (const imp_op_ctx_t *c)
int imp_do_op (imp_op_ctx_t *c)
Variables
struct {
uint32_t op
imp_op_fn_t fn
} imp_op_table []
Typedef Documentation
imp_op_fn_t
typedef int(* imp_op_fn_t) (const imp_op_ctx_t *c)
Definition at line 389 of file broker_ops.c.
Function Documentation
imp_do_op()
int imp_do_op (imp_op_ctx_t * c)
Definition at line 429 of file broker_ops.c.
References BRIX_IMP_HARD_MIN_ID, c, imp_op_table, imp_rel(), and op.
Referenced by imp_dispatch_op().
imp_do_rename()
int imp_do_rename (int sfd, const char * sbase, int dfd, const char * dbase, int noreplace)
Definition at line 177 of file broker_ops.c.
References RENAME_NOREPLACE.
Referenced by imp_op_rename_link().
imp_fill_stat()
void imp_fill_stat (imp_stat_t * o, const struct stat * s)
Definition at line 83 of file broker_ops.c.
References imp_stat_t::atime, imp_stat_t::blksize, imp_stat_t::blocks, imp_stat_t::ctime, imp_stat_t::dev, imp_stat_t::gid, imp_stat_t::ino, imp_stat_t::mode, imp_stat_t::mtime, imp_stat_t::nlink, s, imp_stat_t::size, and imp_stat_t::uid.
Referenced by imp_op_stat().
imp_op_open()
static int imp_op_open (const imp_op_ctx_t * c) static
Definition at line 208 of file broker_ops.c.
References c, close(), fstat(), imp_openat2(), IMP_REP_HAS_FD, and stat().
imp_op_removexattr()
static int imp_op_removexattr (const imp_op_ctx_t * c) static
Definition at line 366 of file broker_ops.c.
References c, close(), imp_xattr_name_ok(), and imp_xattr_open().
imp_op_setxattr()
static int imp_op_setxattr (const imp_op_ctx_t * c) static
Definition at line 343 of file broker_ops.c.
References c, close(), imp_xattr_name_ok(), and imp_xattr_open().
imp_op_stat()
static int imp_op_stat (const imp_op_ctx_t * c) static
Definition at line 258 of file broker_ops.c.
References c, close(), fstatat(), imp_fill_stat(), IMP_OP_LSTAT, imp_openat2(), IMP_REP_HAS_STAT, O_PATH, and stat().
imp_op_truncate()
static int imp_op_truncate (const imp_op_ctx_t * c) static
Definition at line 285 of file broker_ops.c.
References c, close(), and imp_openat2().
imp_op_xattr_read()
static int imp_op_xattr_read (const imp_op_ctx_t * c) static
Definition at line 307 of file broker_ops.c.
References c, close(), IMP_OP_GETXATTR, IMP_OP_LISTXATTR, IMP_REP_HAS_DATA, imp_xattr_filter_user(), imp_xattr_name_ok(), and imp_xattr_open().
imp_open_parent()
int imp_open_parent (int rootfd, const char * rel, char * scratch, const char ** base)
Definition at line 51 of file broker_ops.c.
References close(), imp_openat2(), IMP_PATH_MAX, imp_rel(), ngx_memcpy, and O_PATH.
Referenced by imp_op_readlink(), imp_op_rename_link(), imp_op_setattr(), imp_op_symlink(), and imp_with_parent().
imp_openat2()
int imp_openat2 (int rootfd, const char * rel, uint32_t flags, uint32_t mode)
Definition at line 20 of file broker_ops.c.
Referenced by imp_op_open(), imp_op_stat(), imp_op_truncate(), imp_open_parent(), and imp_xattr_open().
imp_xattr_filter_user()
size_t imp_xattr_filter_user (char * list, size_t len)
Definition at line 142 of file broker_ops.c.
References imp_xattr_name_ok().
Referenced by imp_op_xattr_read().
imp_xattr_name_ok()
int imp_xattr_name_ok (const char * name)
Definition at line 126 of file broker_ops.c.
References name.
Referenced by imp_op_removexattr(), imp_op_setxattr(), imp_op_xattr_read(), and imp_xattr_filter_user().
imp_xattr_open()
int imp_xattr_open (int rootfd, const char * rel)
Definition at line 112 of file broker_ops.c.
References imp_openat2().
Referenced by imp_op_removexattr(), imp_op_setxattr(), and imp_op_xattr_read().
Variable Documentation
fn
imp_op_fn_t fn
Definition at line 393 of file broker_ops.c.
Referenced by brix_ssi_provider_lookup(), brix_tap_register_sink(), brix_tree_walk(), brixmount_usage(), main(), sp_log(), test_echo_service(), tree_walk_depth(), webdav_proxy_build_host(), xfs_meta(), and xfs_meta_idem().
[struct]
const struct { ... } imp_op_table[]
Initial value:
= {
    { IMP_OP_OPEN,             imp_op_open        },
    { IMP_OP_STAT,             imp_op_stat        },
    { IMP_OP_LSTAT,            imp_op_stat        },
    { IMP_OP_TRUNCATE,         imp_op_truncate    },
    { IMP_OP_MKDIR,            imp_op_mkdir       },
    { IMP_OP_UNLINK,           imp_op_unlink      },
    { IMP_OP_RMDIR,            imp_op_unlink      },
    { IMP_OP_CHMOD,            imp_op_chmod       },
    { IMP_OP_CHOWN,            imp_op_chown       },
    { IMP_OP_RENAME,           imp_op_rename_link },
    { IMP_OP_RENAME_NOREPLACE, imp_op_rename_link },
    { IMP_OP_LINK,             imp_op_rename_link },
    { IMP_OP_SETATTR,          imp_op_setattr     },
    { IMP_OP_SYMLINK,          imp_op_symlink     },
    { IMP_OP_READLINK,         imp_op_readlink    },
    { IMP_OP_GETXATTR,         imp_op_xattr_read  },
    { IMP_OP_LISTXATTR,        imp_op_xattr_read  },
    { IMP_OP_SETXATTR,         imp_op_setxattr    },
    { IMP_OP_REMOVEXATTR,      imp_op_removexattr },
}
Referenced by imp_do_op().
op
uint32_t op
Definition at line 392 of file broker_ops.c.
Referenced by acc_access2(), access_check_scope(), brix_acc_access(), brix_acc_audit(), brix_acc_gate_engine(), brix_acc_http_authorize(), brix_acc_op_name(), brix_acc_op_needs(), brix_acc_test(), brix_access_log_emit(), brix_aio_post_task(), brix_cns_apply(), brix_cns_event_decode(), brix_cns_event_encode(), brix_dashboard_http_start(), brix_dashboard_http_start_identity(), brix_fuse_run(), brix_gsi_sigver_required(), brix_identity_check_token_scope(), brix_metric_backend_bytes(), brix_metric_op_done(), brix_metric_op_name(), brix_open_manager_redirect(), brix_open_precheck(), brix_open_validate_fd(), brix_query_arg_missing(), brix_query_fctl_unsupported(), brix_query_fsctl_unsupported(), brix_report_err(), brix_tap_opcode_has_path(), brix_token_authz_strategy(), brix_token_validate_registry(), brix_transfer_slot_alloc_ex(), brix_transfer_slot_count_op(), brix_unified_legacy_stream_op(), brix_validate_file_handle(), brix_validate_read_handle(), brix_validate_write_handle(), brix_vfs_observe_ctx_op(), brix_vfs_observe_file_op(), brix_with_resilience(), brix_write_aio_done(), brix_write_aio_done_pipelined(), brix_write_aio_done_serial(), cms_srv_frame_cns(), codec_feed(), compress_drain_chunk(), cta_queue_open_journal(), dashboard_http_bind_slot(), guard_grammar_ok(), guard_op_str(), imp_build_req(), imp_call_status(), imp_do_op(), imp_get_or_list(), io_engine_arm(), method_name_to_op(), metrics_emit_request_ops(), mk(), ngx_http_brix_guard_build_ruleset(), s3_metrics_method_slot(), s3_post_cond_array(), s3_post_cond_length_range_adapter(), s3_post_cond_string_op(), sd_s3_status_err(), submit(), tap_opcode_name(), unified_emit_io_latency(), unified_emit_io_latency_series(), unified_emit_io_ops(), webdav_is_write_method(), and webdav_metrics_method().