nginx-xrootd: src/auth/impersonate/broker_creds.c File Reference
broker_creds.c File Reference
#include "broker_internal.h"
#include "core/seccomp/seccomp_core.h"
#include <unistd.h>
Functions
int imp_capset_setuid_setgid (int with_effective, ngx_log_t *log)
static int imp_resolve_service_ids (ngx_log_t *log, uid_t *svc_uid, gid_t *svc_gid)
static int imp_apply_service_drop (ngx_log_t *log, uid_t svc_uid, gid_t svc_gid)
static int imp_verify_service_drop (ngx_log_t *log, uid_t svc_uid, gid_t svc_gid)
int imp_drop_to_service_user (ngx_log_t *log)
int brix_imp_broker_drop_caps (ngx_log_t *log)
int imp_become (const brix_idmap_creds_t *cr)
void imp_restore (void)
const char * imp_rel (const char *path)
Variables
uid_t brix_imp_broker_user_uid = (uid_t) -1
gid_t brix_imp_broker_user_gid = (gid_t) -1
Function Documentation
brix_imp_broker_drop_caps()
int brix_imp_broker_drop_caps (ngx_log_t * log)
Definition at line 206 of file broker_creds.c.
References brix_seccomp_broker_apply(), BRIX_SECCOMP_CORE_ERR, BRIX_SECCOMP_CORE_OK, imp_capset_setuid_setgid(), imp_drop_to_service_user(), and log.
Referenced by imp_broker_init_creds().
imp_apply_service_drop()
static int imp_apply_service_drop (ngx_log_t * log, uid_t svc_uid, gid_t svc_gid) static
Definition at line 101 of file broker_creds.c.
References BRIX_DIAG_EMERG, imp_capset_setuid_setgid(), and log.
Referenced by imp_drop_to_service_user().
imp_become()
int imp_become (const brix_idmap_creds_t * cr)
Definition at line 303 of file broker_creds.c.
References brix_imp_broker_allow_uid, brix_imp_creds_privileged(), BRIX_IMP_HARD_MIN_ID, brix_idmap_creds_t::gid, brix_idmap_creds_t::groups, IMP_REFUSE_PRIV, imp_self_uid, brix_idmap_creds_t::ngroups, and brix_idmap_creds_t::uid.
Referenced by imp_dispatch_op().
imp_capset_setuid_setgid()
int imp_capset_setuid_setgid (int with_effective, ngx_log_t * log)
Definition at line 31 of file broker_creds.c.
References log.
Referenced by brix_imp_broker_drop_caps(), and imp_apply_service_drop().
imp_drop_to_service_user()
int imp_drop_to_service_user (ngx_log_t * log)
Definition at line 180 of file broker_creds.c.
References imp_apply_service_drop(), imp_resolve_service_ids(), imp_verify_service_drop(), and log.
Referenced by brix_imp_broker_drop_caps().
imp_rel()
const char * imp_rel (const char * path)
Definition at line 367 of file broker_creds.c.
Referenced by imp_do_op(), imp_op_rename_link(), and imp_open_parent().
imp_resolve_service_ids()
static int imp_resolve_service_ids (ngx_log_t * log, uid_t * svc_uid, gid_t * svc_gid) static
Definition at line 64 of file broker_creds.c.
References BRIX_DIAG_EMERG, brix_imp_broker_user_gid, brix_imp_broker_user_uid, and log.
Referenced by imp_drop_to_service_user().
imp_restore()
void imp_restore (void)
Definition at line 356 of file broker_creds.c.
References imp_base_gid, imp_base_groups, imp_base_ngroups, and imp_base_uid.
Referenced by imp_dispatch_op().
imp_verify_service_drop()
static int imp_verify_service_drop (ngx_log_t * log, uid_t svc_uid, gid_t svc_gid) static
Definition at line 150 of file broker_creds.c.
References log.
Referenced by imp_drop_to_service_user().
Variable Documentation
brix_imp_broker_user_gid
gid_t brix_imp_broker_user_gid = (gid_t) -1
Definition at line 27 of file broker_creds.c.
Referenced by imp_resolve_broker_user(), and imp_resolve_service_ids().
brix_imp_broker_user_uid
uid_t brix_imp_broker_user_uid = (uid_t) -1
Definition at line 26 of file broker_creds.c.
Referenced by imp_resolve_broker_user(), and imp_resolve_service_ids().