nginx-xrootd: src/protocols/root/connection/budget.h File Reference
budget.h File Reference
#include "core/ngx_brix_module.h"
Functions
static size_t brix_budget_ctx_footprint (brix_ctx_t *ctx)
static void brix_budget_sync (brix_ctx_t *ctx)
static void brix_budget_release (brix_ctx_t *ctx)
static ngx_int_t brix_budget_admit (brix_ctx_t *ctx, off_t budget, size_t want)
Function Documentation
brix_budget_admit()
static ngx_int_t brix_budget_admit (brix_ctx_t * ctx, off_t budget, size_t want) inline static
Definition at line 102 of file budget.h.
References brix_ctx_t::budget_charged, ngx_brix_srv_metrics_t::budget_waits_total, in_use, brix_ctx_t::metrics, and ngx_brix_srv_metrics_t::xfer_heap_in_use.
Referenced by brix_handle_readv(), read_serve_buffered(), and read_serve_windowed().
brix_budget_ctx_footprint()
static size_t brix_budget_ctx_footprint (brix_ctx_t * ctx) inline static
Definition at line 26 of file budget.h.
References brix_ctx_rd_t::cmp_scratch_size, brix_ctx_t::out, brix_ctx_recv_t::payload_buf_size, brix_ctx_out_t::pipeline_depth, brix_ctx_rd_t::pool, brix_ctx_t::rd, brix_ctx_rd_t::read_hdr_scratch_size, brix_ctx_rd_t::read_scratch_size, brix_ctx_t::recv, brix_read_slot_t::size, and brix_ctx_rd_t::write_scratch_size.
Referenced by brix_budget_sync().
brix_budget_release()
static void brix_budget_release (brix_ctx_t * ctx) inline static
Definition at line 82 of file budget.h.
References brix_ctx_t::budget_charged, brix_ctx_t::metrics, and ngx_brix_srv_metrics_t::xfer_heap_in_use.
Referenced by brix_on_disconnect().
brix_budget_sync()
static void brix_budget_sync (brix_ctx_t * ctx) inline static
Definition at line 49 of file budget.h.
References brix_budget_ctx_footprint(), brix_ctx_t::budget_charged, brix_ctx_t::metrics, ngx_brix_srv_metrics_t::xfer_heap_high_water, and ngx_brix_srv_metrics_t::xfer_heap_in_use.
Referenced by brix_handle_readv(), brix_read_window_pump(), brix_recv_header_prep(), and read_serve_buffered().