nginx-xrootd: src/core/aio/buffers_scratch.c File Reference
buffers_scratch.c File Reference
#include "core/ngx_brix_module.h"
Functions
u_char * brix_get_pool_scratch (ngx_pool_t *pool, u_char **slot, size_t *slot_size, size_t need)
void brix_release_read_buffer (brix_ctx_t *ctx, ngx_connection_t *c, u_char *buf)
u_char * brix_acquire_read_buffer (brix_ctx_t *ctx, ngx_connection_t *c, size_t need)
static void brix_trim_one (ngx_pool_t *pool, u_char **slot, size_t *slot_size)
void brix_trim_scratch (brix_ctx_t *ctx, ngx_connection_t *c)
Function Documentation
brix_acquire_read_buffer()
u_char * brix_acquire_read_buffer (brix_ctx_t * ctx, ngx_connection_t * c, size_t need)
Definition at line 134 of file buffers_scratch.c.
References brix_read_slot_t::buf, c, brix_read_slot_t::in_use, brix_ctx_rd_t::inflight, brix_ctx_t::out, brix_ctx_out_t::pipeline_depth, brix_ctx_rd_t::pool, brix_ctx_t::rd, and brix_read_slot_t::size.
Referenced by read_serve_buffered().
brix_get_pool_scratch()
u_char * brix_get_pool_scratch (ngx_pool_t * pool, u_char ** slot, size_t * slot_size, size_t need)
Definition at line 31 of file buffers_scratch.c.
brix_release_read_buffer()
void brix_release_read_buffer (brix_ctx_t * ctx, ngx_connection_t * c, u_char * buf)
Definition at line 83 of file buffers_scratch.c.
References brix_read_slot_t::buf, c, brix_ctx_rd_t::cmp_scratch, brix_read_slot_t::in_use, brix_ctx_rd_t::inflight, brix_ctx_t::out, brix_ctx_out_t::pipeline_depth, brix_ctx_rd_t::pool, brix_ctx_t::rd, brix_ctx_rd_t::read_hdr_scratch, brix_ctx_rd_t::read_scratch, and brix_ctx_rd_t::write_scratch.
Referenced by brix_dirlist_aio_done(), brix_handle_readv(), brix_pgread_aio_done(), brix_pgread_send_response(), brix_read_aio_done(), brix_read_compressed(), brix_read_serve_sendfile(), brix_read_window_emit(), brix_readv_aio_done(), brix_readv_execute_sync(), brix_readv_try_post_async(), brix_release_pending_buffer(), read_finish_buffered(), and read_post_aio().
brix_trim_one()
static void brix_trim_one (ngx_pool_t * pool, u_char ** slot, size_t * slot_size) static
Definition at line 186 of file buffers_scratch.c.
References BRIX_READ_WINDOW, and BRIX_SCRATCH_TRIM_THRESHOLD.
Referenced by brix_trim_scratch().
brix_trim_scratch()
void brix_trim_scratch (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 212 of file buffers_scratch.c.
References brix_trim_one(), c, brix_ctx_t::rd, brix_ctx_rd_t::read_scratch, brix_ctx_rd_t::read_scratch_size, brix_ctx_rd_t::write_scratch, and brix_ctx_rd_t::write_scratch_size.
Referenced by brix_recv_header_prep().