nginx-xrootd: src/core/aio/buffers.c File Reference
buffers.c File Reference
#include "core/ngx_brix_module.h"
Functions
u_char * brix_get_pool_scratch (ngx_pool_t *pool, u_char **slot, size_t *slot_size, size_t need)
void brix_release_read_buffer (brix_ctx_t *ctx, ngx_connection_t *c, u_char *buf)
u_char * brix_acquire_read_buffer (brix_ctx_t *ctx, ngx_connection_t *c, size_t need)
static void brix_trim_one (ngx_pool_t *pool, u_char **slot, size_t *slot_size)
void brix_trim_scratch (brix_ctx_t *ctx, ngx_connection_t *c)
static ngx_chain_t * brix_build_single_memory_chain (brix_ctx_t *ctx, ngx_connection_t *c, u_char *databuf, size_t data_total)
ngx_chain_t * brix_build_window_chain (brix_ctx_t *ctx, ngx_connection_t *c, u_char *databuf, size_t data_total, uint16_t status)
static ngx_chain_t * brix_build_single_sendfile_chain (brix_ctx_t *ctx, ngx_connection_t *c, int fd, const char *path, off_t offset, size_t data_total, u_char **base_out)
ngx_chain_t * brix_build_chunked_chain (brix_ctx_t *ctx, ngx_connection_t *c, u_char *databuf, size_t data_total)
ngx_chain_t * brix_build_sendfile_chain (brix_ctx_t *ctx, ngx_connection_t *c, int fd, const char *path, off_t offset, size_t data_total, u_char **base_out)
ngx_chain_t * brix_build_pgread_chain (brix_ctx_t *ctx, ngx_connection_t *c, int64_t offset, u_char *data, uint32_t out_size)
Function Documentation
brix_acquire_read_buffer()
u_char * brix_acquire_read_buffer (brix_ctx_t * ctx, ngx_connection_t * c, size_t need)
Definition at line 127 of file buffers.c.
References brix_read_slot_t::buf, c, brix_read_slot_t::in_use, brix_ctx_rd_t::inflight, brix_ctx_t::out, brix_ctx_out_t::pipeline_depth, brix_ctx_rd_t::pool, brix_ctx_t::rd, and brix_read_slot_t::size.
Referenced by brix_handle_read().
brix_build_chunked_chain()
ngx_chain_t * brix_build_chunked_chain (brix_ctx_t * ctx, ngx_connection_t * c, u_char * databuf, size_t data_total)
Definition at line 456 of file buffers.c.
References brix_build_resp_hdr(), brix_build_single_memory_chain(), BRIX_GET_SCRATCH, BRIX_READ_CHUNK_MAX, c, brix_ctx_recv_t::cur_streamid, kXR_ok, kXR_oksofar, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_handle_read(), brix_handle_readv(), brix_read_aio_done(), brix_read_compressed(), and brix_readv_aio_done().
brix_build_pgread_chain()
ngx_chain_t * brix_build_pgread_chain (brix_ctx_t * ctx, ngx_connection_t * c, int64_t offset, u_char * data, uint32_t out_size)
Definition at line 745 of file buffers.c.
References brix_build_pgread_status(), and c.
Referenced by brix_handle_pgread(), and brix_pgread_aio_done().
brix_build_sendfile_chain()
ngx_chain_t * brix_build_sendfile_chain (brix_ctx_t * ctx, ngx_connection_t * c, int fd, const char * path, off_t offset, size_t data_total, u_char ** base_out)
Definition at line 598 of file buffers.c.
References brix_build_resp_hdr(), brix_build_single_sendfile_chain(), BRIX_READ_CHUNK_MAX, BRIX_SLOT_HDR_MAX, c, brix_ctx_recv_t::cur_streamid, brix_resp_slot_t::hdr_bytes, kXR_ok, kXR_oksofar, ngx_pcalloc(), brix_ctx_t::out, brix_ctx_t::recv, brix_ctx_out_t::resp_pipelinable, brix_ctx_out_t::ring, brix_ctx_out_t::tail, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_read_serve_sendfile().
brix_build_single_memory_chain()
static ngx_chain_t * brix_build_single_memory_chain (brix_ctx_t * ctx, ngx_connection_t * c, u_char * databuf, size_t data_total) static
Definition at line 237 of file buffers.c.
References brix_build_resp_hdr(), c, brix_ctx_recv_t::cur_streamid, brix_resp_slot_t::hdr_bytes, kXR_ok, brix_ctx_t::out, brix_resp_slot_t::read_fast_body_buf, brix_resp_slot_t::read_fast_body_chain, brix_resp_slot_t::read_fast_hdr_buf, brix_resp_slot_t::read_fast_hdr_chain, brix_ctx_t::recv, brix_ctx_out_t::ring, brix_ctx_out_t::tail, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_build_chunked_chain().
brix_build_single_sendfile_chain()
static ngx_chain_t * brix_build_single_sendfile_chain (brix_ctx_t * ctx, ngx_connection_t * c, int fd, const char * path, off_t offset, size_t data_total, u_char ** base_out) static
Definition at line 380 of file buffers.c.
References brix_build_resp_hdr(), c, brix_ctx_recv_t::cur_streamid, brix_resp_slot_t::hdr_bytes, kXR_ok, brix_ctx_t::out, brix_resp_slot_t::read_fast_body_buf, brix_resp_slot_t::read_fast_body_chain, brix_resp_slot_t::read_fast_file, brix_resp_slot_t::read_fast_hdr_buf, brix_resp_slot_t::read_fast_hdr_chain, brix_ctx_t::recv, brix_ctx_out_t::resp_pipelinable, brix_ctx_out_t::ring, brix_ctx_out_t::tail, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_build_sendfile_chain().
brix_build_window_chain()
ngx_chain_t * brix_build_window_chain (brix_ctx_t * ctx, ngx_connection_t * c, u_char * databuf, size_t data_total, uint16_t status)
Definition at line 301 of file buffers.c.
References brix_build_resp_hdr(), BRIX_GET_SCRATCH, c, brix_ctx_recv_t::cur_streamid, brix_ctx_t::out, brix_resp_slot_t::read_fast_body_buf, brix_resp_slot_t::read_fast_body_chain, brix_resp_slot_t::read_fast_hdr_buf, brix_resp_slot_t::read_fast_hdr_chain, brix_ctx_t::recv, brix_ctx_out_t::ring, brix_ctx_out_t::tail, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_read_window_emit().
brix_get_pool_scratch()
u_char * brix_get_pool_scratch (ngx_pool_t * pool, u_char ** slot, size_t * slot_size, size_t need)
Definition at line 24 of file buffers.c.
brix_release_read_buffer()
void brix_release_read_buffer (brix_ctx_t * ctx, ngx_connection_t * c, u_char * buf)
Definition at line 76 of file buffers.c.
References brix_read_slot_t::buf, c, brix_ctx_rd_t::cmp_scratch, brix_read_slot_t::in_use, brix_ctx_rd_t::inflight, brix_ctx_t::out, brix_ctx_out_t::pipeline_depth, brix_ctx_rd_t::pool, brix_ctx_t::rd, brix_ctx_rd_t::read_hdr_scratch, brix_ctx_rd_t::read_scratch, and brix_ctx_rd_t::write_scratch.
Referenced by brix_dirlist_aio_done(), brix_handle_pgread(), brix_handle_read(), brix_handle_readv(), brix_pgread_aio_done(), brix_read_aio_done(), brix_read_compressed(), brix_read_serve_sendfile(), brix_read_window_emit(), brix_readv_aio_done(), and brix_release_pending_buffer().
brix_trim_one()
static void brix_trim_one (ngx_pool_t * pool, u_char ** slot, size_t * slot_size) static
Definition at line 179 of file buffers.c.
References BRIX_READ_WINDOW, and BRIX_SCRATCH_TRIM_THRESHOLD.
Referenced by brix_trim_scratch().
brix_trim_scratch()
void brix_trim_scratch (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 205 of file buffers.c.
References brix_trim_one(), c, brix_ctx_t::rd, brix_ctx_rd_t::read_scratch, brix_ctx_rd_t::read_scratch_size, brix_ctx_rd_t::write_scratch, and brix_ctx_rd_t::write_scratch_size.
Referenced by ngx_stream_brix_recv().