nginx-xrootd: src/core/aio/buffers_sendfile.c File Reference
buffers_sendfile.c File Reference
#include "core/ngx_brix_module.h"
#include "core/aio/buffers_internal.h"
Functions
static ngx_chain_t * brix_build_single_sendfile_chain (brix_ctx_t *ctx, ngx_connection_t *c, int fd, const char *path, off_t offset, size_t data_total, u_char **base_out)
ngx_chain_t * brix_build_sendfile_chain (brix_ctx_t *ctx, ngx_connection_t *c, int fd, const char *path, off_t offset, size_t data_total, u_char **base_out)
ngx_chain_t * brix_build_pgread_chain (brix_ctx_t *ctx, ngx_connection_t *c, int64_t offset, u_char *data, uint32_t out_size)
Function Documentation
brix_build_pgread_chain()
ngx_chain_t * brix_build_pgread_chain (brix_ctx_t * ctx, ngx_connection_t * c, int64_t offset, u_char * data, uint32_t out_size)
Definition at line 237 of file buffers_sendfile.c.
References brix_build_pgread_status(), and c.
Referenced by brix_pgread_aio_done(), and brix_pgread_send_response().
brix_build_sendfile_chain()
ngx_chain_t * brix_build_sendfile_chain (brix_ctx_t * ctx, ngx_connection_t * c, int fd, const char * path, off_t offset, size_t data_total, u_char ** base_out)
Definition at line 130 of file buffers_sendfile.c.
References brix_build_resp_hdr(), brix_build_single_sendfile_chain(), brix_chain_append_file(), brix_chain_append_mem(), brix_chunk_geometry(), BRIX_READ_CHUNK_MAX, BRIX_SLOT_HDR_MAX, c, brix_ctx_recv_t::cur_streamid, brix_resp_slot_t::hdr_bytes, kXR_ok, kXR_oksofar, brix_ctx_t::out, brix_ctx_t::recv, brix_ctx_out_t::resp_pipelinable, brix_ctx_out_t::ring, brix_ctx_out_t::tail, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_read_serve_sendfile().
brix_build_single_sendfile_chain()
static ngx_chain_t * brix_build_single_sendfile_chain (brix_ctx_t * ctx, ngx_connection_t * c, int fd, const char * path, off_t offset, size_t data_total, u_char ** base_out) static
Definition at line 44 of file buffers_sendfile.c.
References brix_build_resp_hdr(), c, brix_ctx_recv_t::cur_streamid, brix_resp_slot_t::hdr_bytes, kXR_ok, brix_ctx_t::out, brix_resp_slot_t::read_fast_body_buf, brix_resp_slot_t::read_fast_body_chain, brix_resp_slot_t::read_fast_file, brix_resp_slot_t::read_fast_hdr_buf, brix_resp_slot_t::read_fast_hdr_chain, brix_ctx_t::recv, brix_ctx_out_t::resp_pipelinable, brix_ctx_out_t::ring, brix_ctx_out_t::tail, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_build_sendfile_chain().