nginx-xrootd: src/protocols/srr/builder.c File Reference
builder.c File Reference
#include "srr.h"
#include "core/compat/fs_usage.h"
#include "core/ident.h"
#include "core/compat/cstr.h"
#include <jansson.h>
#include <stdint.h>
#include <time.h>
Data Structures
struct srr_cap_t
Macros
#define SRR_JSTR(s) json_stringn((const char *) (s).data, (s).len)
Functions
static json_int_t srr_clamp_size (uint64_t v)
static json_t * srr_vos_array (const ngx_str_t *vos)
static json_t * srr_share_names (ngx_http_brix_srr_loc_conf_t *lcf)
static json_t * srr_endpoint_names (ngx_http_brix_srr_loc_conf_t *lcf)
static void srr_emit_identity (json_t *svc, ngx_http_brix_srr_loc_conf_t *lcf, time_t now)
static ngx_int_t srr_share_usage (ngx_http_request_t *r, brix_srr_share_t *sh, srr_cap_t *share_cap, srr_cap_t *site_cap)
static ngx_int_t srr_emit_share (ngx_http_brix_srr_loc_conf_t *lcf, json_t *shares, brix_srr_share_t *sh, const srr_cap_t *cap, time_t now)
static ngx_int_t srr_emit_shares (ngx_http_request_t *r, ngx_http_brix_srr_loc_conf_t *lcf, json_t *svc, time_t now, srr_cap_t *site_cap)
static ngx_int_t srr_emit_capacity (json_t *svc, uint64_t cap_total, uint64_t cap_used)
static ngx_int_t srr_emit_endpoints (ngx_http_brix_srr_loc_conf_t *lcf, json_t *svc)
static ngx_int_t srr_serialise (ngx_http_request_t *r, json_t *root, u_char **out, size_t *len)
ngx_int_t ngx_http_brix_srr_build_json (ngx_http_request_t *r, ngx_http_brix_srr_loc_conf_t *lcf, u_char **out, size_t *len)
Macro Definition Documentation
SRR_JSTR
#define SRR_JSTR (s) json_stringn((const char *) (s).data, (s).len)
Definition at line 43 of file builder.c.
Function Documentation
ngx_http_brix_srr_build_json()
ngx_int_t ngx_http_brix_srr_build_json (ngx_http_request_t * r, ngx_http_brix_srr_loc_conf_t * lcf, u_char ** out, size_t * len)
Definition at line 467 of file builder.c.
References srr_emit_capacity(), srr_emit_endpoints(), srr_emit_identity(), srr_emit_shares(), srr_serialise(), srr_cap_t::total, and srr_cap_t::used.
Referenced by ngx_http_brix_srr_handler().
srr_clamp_size()
static json_int_t srr_clamp_size (uint64_t v) static
Definition at line 60 of file builder.c.
Referenced by srr_emit_capacity(), and srr_emit_share().
srr_emit_capacity()
static ngx_int_t srr_emit_capacity (json_t * svc, uint64_t cap_total, uint64_t cap_used) static
Definition at line 356 of file builder.c.
References srr_clamp_size().
Referenced by ngx_http_brix_srr_build_json().
srr_emit_endpoints()
static ngx_int_t srr_emit_endpoints (ngx_http_brix_srr_loc_conf_t * lcf, json_t * svc) static
Definition at line 391 of file builder.c.
References ngx_http_brix_srr_loc_conf_t::endpoints, name, ngx_http_brix_srr_loc_conf_t::quality, SRR_JSTR, and srr_share_names().
Referenced by ngx_http_brix_srr_build_json().
srr_emit_identity()
static void srr_emit_identity (json_t * svc, ngx_http_brix_srr_loc_conf_t * lcf, time_t now) static
Definition at line 172 of file builder.c.
References BRIX_SERVER_NAME, BRIX_SERVER_VERSION_BARE, ngx_http_brix_srr_loc_conf_t::id, ngx_http_brix_srr_loc_conf_t::name, ngx_http_brix_srr_loc_conf_t::quality, SRR_JSTR, and ngx_http_brix_srr_loc_conf_t::version.
Referenced by ngx_http_brix_srr_build_json().
srr_emit_share()
static ngx_int_t srr_emit_share (ngx_http_brix_srr_loc_conf_t * lcf, json_t * shares, brix_srr_share_t * sh, const srr_cap_t * cap, time_t now) static
Definition at line 257 of file builder.c.
References brix_srr_share_t::name, brix_srr_share_t::path, srr_clamp_size(), srr_endpoint_names(), SRR_JSTR, srr_vos_array(), srr_cap_t::total, srr_cap_t::used, and brix_srr_share_t::vos.
Referenced by srr_emit_shares().
srr_emit_shares()
static ngx_int_t srr_emit_shares (ngx_http_request_t * r, ngx_http_brix_srr_loc_conf_t * lcf, json_t * svc, time_t now, srr_cap_t * site_cap) static
Definition at line 312 of file builder.c.
References ngx_http_brix_srr_loc_conf_t::shares, srr_emit_share(), and srr_share_usage().
Referenced by ngx_http_brix_srr_build_json().
srr_endpoint_names()
static json_t * srr_endpoint_names (ngx_http_brix_srr_loc_conf_t * lcf) static
Definition at line 137 of file builder.c.
References ngx_http_brix_srr_loc_conf_t::endpoints, name, and SRR_JSTR.
Referenced by srr_emit_share().
srr_serialise()
static ngx_int_t srr_serialise (ngx_http_request_t * r, json_t * root, u_char ** out, size_t * len) static
Definition at line 445 of file builder.c.
References ngx_pnalloc().
Referenced by ngx_http_brix_srr_build_json().
srr_share_names()
static json_t * srr_share_names (ngx_http_brix_srr_loc_conf_t * lcf) static
Definition at line 115 of file builder.c.
References name, ngx_http_brix_srr_loc_conf_t::shares, and SRR_JSTR.
Referenced by srr_emit_endpoints().
srr_share_usage()
static ngx_int_t srr_share_usage (ngx_http_request_t * r, brix_srr_share_t * sh, srr_cap_t * share_cap, srr_cap_t * site_cap) static
Definition at line 207 of file builder.c.
References brix_fs_usage_stat(), brix_pstrdup_z(), brix_srr_share_t::name, brix_srr_share_t::path, srr_cap_t::total, usage(), and srr_cap_t::used.
Referenced by srr_emit_shares().
srr_vos_array()
static json_t * srr_vos_array (const ngx_str_t * vos) static
Definition at line 74 of file builder.c.
References toklen.
Referenced by srr_emit_share().