nginx-xrootd: src/fs/cache/cache_admit.c File Reference
cache_admit.c File Reference
#include "cache_admit.h"
#include <string.h>
Functions
static int admit_prefix_match (const char *path, const ngx_str_t *p)
static int admit_any_prefix (const char *path, ngx_array_t *a)
brix_cache_admit_e brix_cache_admit (const brix_cache_admit_cfg_t *cfg, const char *path, off_t size, int is_new)
Function Documentation
admit_any_prefix()
static int admit_any_prefix (const char * path, ngx_array_t * a) static
Definition at line 25 of file cache_admit.c.
References admit_prefix_match().
Referenced by brix_cache_admit().
admit_prefix_match()
static int admit_prefix_match (const char * path, const ngx_str_t * p) static
Definition at line 13 of file cache_admit.c.
Referenced by admit_any_prefix().
brix_cache_admit()
brix_cache_admit_e brix_cache_admit (const brix_cache_admit_cfg_t * cfg, const char * path, off_t size, int is_new)
Definition at line 43 of file cache_admit.c.
References admit_any_prefix(), brix_cache_admit_cfg_t::allow_prefixes, BRIX_CACHE_ADMIT, BRIX_CACHE_DECLINE, brix_cache_admit_cfg_t::deny_prefixes, brix_cache_admit_cfg_t::include_regex, and brix_cache_admit_cfg_t::size_limit.
Referenced by brix_cache_fill_admitted(), and brix_wt_default_decide().