nginx-xrootd: src/fs/cache/cache_storage.h File Reference
cache_storage.h File Reference
#include "cache_internal.h"
#include "cstore.h"
#include "fs/backend/sd.h"
Functions
ngx_int_t brix_cache_storage_init (ngx_stream_brix_srv_conf_t *conf, ngx_cycle_t *cycle)
void brix_cache_storage_cleanup (ngx_stream_brix_srv_conf_t *conf)
brix_sd_instance_t * brix_cache_storage (const ngx_stream_brix_srv_conf_t *conf)
brix_sd_instance_t * brix_cache_storage_decorator (const ngx_stream_brix_srv_conf_t *conf)
brix_cstore_t * brix_cache_storage_cstore (const ngx_stream_brix_srv_conf_t *conf)
brix_sd_instance_t * brix_cache_source_inst (const ngx_stream_brix_srv_conf_t *conf)
brix_sd_instance_t * brix_cache_wt_stage_sd_inst (const ngx_stream_brix_srv_conf_t *conf)
brix_sd_instance_t * brix_cache_state_storage (const ngx_stream_brix_srv_conf_t *conf)
brix_sd_instance_t * brix_cache_wt_stage (const ngx_stream_brix_srv_conf_t *conf)
brix_sd_instance_t * brix_cache_storage_by_root (const char *cache_root_canon)
brix_sd_instance_t * brix_cache_state_by_root (const char *cache_root_canon)
const char * brix_cache_state_root_by_root (const char *cache_root_canon)
int brix_cache_sidecar_path (const char *cache_root, const char *state_root, const char *cache_path, char *dst, size_t dstsz)
int brix_cache_ready (const ngx_stream_brix_srv_conf_t *conf, const char *cache_path)
const char * brix_cache_key_under_root (const ngx_stream_brix_srv_conf_t *conf, const char *cache_path)
int brix_cache_key (const ngx_stream_brix_srv_conf_t *conf, const char *resolved, char *dst, size_t dstsz)
int brix_cache_key_from (const char *cache_root_canon, const char *root_canon, const char *resolved, char *dst, size_t dstsz)
Function Documentation
brix_cache_key()
int brix_cache_key (const ngx_stream_brix_srv_conf_t * conf, const char * resolved, char * dst, size_t dstsz)
Definition at line 22 of file cache_storage.c.
References brix_cache_key_from().
brix_cache_key_from()
int brix_cache_key_from (const char * cache_root_canon, const char * root_canon, const char * resolved, char * dst, size_t dstsz)
Definition at line 16 of file cache_key.c.
Referenced by brix_cache_key().
brix_cache_key_under_root()
const char * brix_cache_key_under_root (const ngx_stream_brix_srv_conf_t * conf, const char * cache_path)
Definition at line 35 of file cache_storage.c.
References key.
brix_cache_ready()
int brix_cache_ready (const ngx_stream_brix_srv_conf_t * conf, const char * cache_path)
Definition at line 54 of file cache_storage.c.
References brix_cache_file_ready().
Referenced by brix_cache_fill_thread(), and brix_cache_open_or_fill().
brix_cache_sidecar_path()
int brix_cache_sidecar_path (const char * cache_root, const char * state_root, const char * cache_path, char * dst, size_t dstsz)
Definition at line 119 of file cache_storage.c.
Referenced by brix_cache_commit_staged(), brix_cache_evict_remove_sidecars(), brix_cache_hit_fresh(), and evict_collect_visit().
brix_cache_source_inst()
brix_sd_instance_t * brix_cache_source_inst (const ngx_stream_brix_srv_conf_t * conf)
Definition at line 247 of file cache_storage.c.
brix_cache_state_by_root()
brix_sd_instance_t * brix_cache_state_by_root (const char * cache_root_canon)
Definition at line 189 of file cache_storage.c.
References cs_root_find(), and cs_root_entry_t::state_inst.
brix_cache_state_root_by_root()
const char * brix_cache_state_root_by_root (const char * cache_root_canon)
Definition at line 109 of file cache_storage.c.
References cs_root_find(), and cs_root_entry_t::state_root.
Referenced by brix_cache_hit_fresh().
brix_cache_state_storage()
brix_sd_instance_t * brix_cache_state_storage (const ngx_stream_brix_srv_conf_t * conf)
Definition at line 259 of file cache_storage.c.
brix_cache_storage()
brix_sd_instance_t * brix_cache_storage (const ngx_stream_brix_srv_conf_t * conf)
Definition at line 203 of file cache_storage.c.
References brix_sd_cache_instance_is(), brix_sd_cache_store_instance(), brix_vfs_backend_resolve(), and c.
Referenced by brix_cache_fill_from_source(), and brix_cache_purge_setup().
brix_cache_storage_by_root()
brix_sd_instance_t * brix_cache_storage_by_root (const char * cache_root_canon)
Definition at line 182 of file cache_storage.c.
References cs_root_find(), cs_root_lazy_posix(), and cs_root_entry_t::read_inst.
Referenced by brix_cache_open().
brix_cache_storage_cleanup()
void brix_cache_storage_cleanup (ngx_stream_brix_srv_conf_t * conf)
Definition at line 454 of file cache_storage.c.
References brix_cstore_cleanup(), brix_sd_stage_destroy(), brix_sd_stage_source_instance(), brix_sd_xroot_destroy(), and close().
Referenced by brix_exit_process().
brix_cache_storage_cstore()
brix_cstore_t * brix_cache_storage_cstore (const ngx_stream_brix_srv_conf_t * conf)
Definition at line 234 of file cache_storage.c.
References brix_sd_cache_cstore(), brix_sd_cache_instance_is(), brix_vfs_backend_resolve(), and c.
Referenced by brix_cache_evict_if_needed(), brix_cache_purge_setup(), brix_cache_reap_dirty(), and brix_cache_state_root().
brix_cache_storage_decorator()
brix_sd_instance_t * brix_cache_storage_decorator (const ngx_stream_brix_srv_conf_t * conf)
Definition at line 221 of file cache_storage.c.
References brix_sd_cache_instance_is(), brix_vfs_backend_resolve(), and c.
Referenced by brix_cache_purge_setup(), and brix_open_stage_preflight().
brix_cache_storage_init()
ngx_int_t brix_cache_storage_init (ngx_stream_brix_srv_conf_t * conf, ngx_cycle_t * cycle)
Definition at line 357 of file cache_storage.c.
References BRIX_CMETA_AUTO, brix_cstore_init(), cache_build_instance(), cache_build_wt_stage(), cache_open_rootfd(), cs_root_register(), log, and ngx_pcalloc().
Referenced by brix_init_one_server().
brix_cache_wt_stage()
brix_sd_instance_t * brix_cache_wt_stage (const ngx_stream_brix_srv_conf_t * conf)
Definition at line 265 of file cache_storage.c.
brix_cache_wt_stage_sd_inst()
brix_sd_instance_t * brix_cache_wt_stage_sd_inst (const ngx_stream_brix_srv_conf_t * conf)
Definition at line 253 of file cache_storage.c.
Referenced by brix_open_select_sd_inst().