nginx-xrootd: src/fs/cache/cache_fs_sampler.c File Reference
cache_fs_sampler.c File Reference
#include "evict_internal.h"
#include "cache_fs_sampler.h"
#include <limits.h>
#include <string.h>
Data Structures
struct fs_usage_slot_t
Macros
#define BRIX_FS_USAGE_SLOTS 8
Functions
static fs_usage_slot_t * fs_usage_lookup (const char *root, fs_usage_slot_t **free_out)
ngx_int_t brix_cache_fs_usage_sampled (const char *root, ngx_msec_t ttl_ms, brix_cache_fs_usage_t *out)
Variables
static fs_usage_slot_t fs_usage_cache [8]
Macro Definition Documentation
BRIX_FS_USAGE_SLOTS
#define BRIX_FS_USAGE_SLOTS 8
Definition at line 28 of file cache_fs_sampler.c.
Function Documentation
brix_cache_fs_usage_sampled()
ngx_int_t brix_cache_fs_usage_sampled (const char * root, ngx_msec_t ttl_ms, brix_cache_fs_usage_t * out)
Definition at line 61 of file cache_fs_sampler.c.
References brix_cache_fs_usage(), brix_cache_sample_fresh(), fs_usage_cache, fs_usage_lookup(), fs_usage_slot_t::last_ms, fs_usage_slot_t::root, and fs_usage_slot_t::usage.
Referenced by brix_cache_watermark_purge(), and brix_wt_stage_admit().
fs_usage_lookup()
static fs_usage_slot_t * fs_usage_lookup (const char * root, fs_usage_slot_t ** free_out) static
Definition at line 41 of file cache_fs_sampler.c.
References BRIX_FS_USAGE_SLOTS, and fs_usage_cache.
Referenced by brix_cache_fs_usage_sampled().
Variable Documentation
fs_usage_cache
fs_usage_slot_t fs_usage_cache[8] static
Definition at line 36 of file cache_fs_sampler.c.
Referenced by brix_cache_fs_usage_sampled(), and fs_usage_lookup().