nginx-xrootd: src/fs/cache/cache_storage.c File Reference
cache_storage.c File Reference
#include "cache_storage.h"
#include "cache_internal.h"
#include "cstore.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "fs/backend/xroot/sd_xroot.h"
#include "fs/backend/cache/sd_cache.h"
#include "fs/backend/stage/sd_stage.h"
#include "fs/tier/tier.h"
#include <fcntl.h>
#include <string.h>
#include <unistd.h>
Data Structures
struct cs_root_entry_t
Macros
#define BRIX_CACHE_STORAGE_MAX 64
Functions
int brix_cache_key (const ngx_stream_brix_srv_conf_t *conf, const char *resolved, char *dst, size_t dstsz)
const char * brix_cache_key_under_root (const ngx_stream_brix_srv_conf_t *conf, const char *cache_path)
int brix_cache_ready (const ngx_stream_brix_srv_conf_t *conf, const char *cache_path)
static cs_root_entry_t * cs_root_find (const char *root)
static void cs_root_register (const char *root, const char *state_root, brix_sd_instance_t *read_inst, brix_sd_instance_t *state_inst)
const char * brix_cache_state_root_by_root (const char *cache_root_canon)
int brix_cache_sidecar_path (const char *cache_root, const char *state_root, const char *cache_path, char *dst, size_t dstsz)
static brix_sd_instance_t * cs_root_lazy_posix (const char *root)
brix_sd_instance_t * brix_cache_storage_by_root (const char *cache_root_canon)
brix_sd_instance_t * brix_cache_state_by_root (const char *cache_root_canon)
brix_sd_instance_t * brix_cache_storage (const ngx_stream_brix_srv_conf_t *conf)
brix_cstore_t * brix_cache_storage_cstore (const ngx_stream_brix_srv_conf_t *conf)
brix_sd_instance_t * brix_cache_source_inst (const ngx_stream_brix_srv_conf_t *conf)
brix_sd_instance_t * brix_cache_wt_stage_sd_inst (const ngx_stream_brix_srv_conf_t *conf)
brix_sd_instance_t * brix_cache_state_storage (const ngx_stream_brix_srv_conf_t *conf)
brix_sd_instance_t * brix_cache_wt_stage (const ngx_stream_brix_srv_conf_t *conf)
static int cache_open_rootfd (const ngx_str_t *root, ngx_log_t *log)
static brix_sd_instance_t * cache_build_instance (ngx_pool_t *pool, ngx_log_t *log, const ngx_str_t *root, const ngx_str_t *backend, int rootfd)
static void cache_build_wt_stage (ngx_pool_t *pool, ngx_log_t *log, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_cache_storage_init (ngx_stream_brix_srv_conf_t *conf, ngx_cycle_t *cycle)
void brix_cache_storage_cleanup (ngx_stream_brix_srv_conf_t *conf)
Variables
static cs_root_entry_t cs_root_table [64]
static ngx_uint_t cs_root_count
Macro Definition Documentation
BRIX_CACHE_STORAGE_MAX
#define BRIX_CACHE_STORAGE_MAX 64
Definition at line 66 of file cache_storage.c.
Function Documentation
brix_cache_key()
int brix_cache_key (const ngx_stream_brix_srv_conf_t * conf, const char * resolved, char * dst, size_t dstsz)
Definition at line 22 of file cache_storage.c.
References brix_cache_key_from(), ngx_stream_brix_srv_conf_t::cache_root, ngx_stream_brix_srv_conf_t::common, and ngx_http_brix_shared_conf_t::root_canon.
brix_cache_key_under_root()
const char * brix_cache_key_under_root (const ngx_stream_brix_srv_conf_t * conf, const char * cache_path)
Definition at line 35 of file cache_storage.c.
References ngx_stream_brix_srv_conf_t::cache_root, and key.
brix_cache_ready()
int brix_cache_ready (const ngx_stream_brix_srv_conf_t * conf, const char * cache_path)
Definition at line 54 of file cache_storage.c.
References brix_cache_file_ready().
Referenced by brix_cache_fill_thread(), and brix_cache_open_or_fill().
brix_cache_sidecar_path()
int brix_cache_sidecar_path (const char * cache_root, const char * state_root, const char * cache_path, char * dst, size_t dstsz)
Definition at line 119 of file cache_storage.c.
Referenced by brix_cache_commit_staged(), brix_cache_evict_one(), brix_cache_open(), and evict_collect_visit().
brix_cache_source_inst()
brix_sd_instance_t * brix_cache_source_inst (const ngx_stream_brix_srv_conf_t * conf)
Definition at line 229 of file cache_storage.c.
References ngx_stream_brix_srv_conf_t::cache_source_inst.
brix_cache_state_by_root()
brix_sd_instance_t * brix_cache_state_by_root (const char * cache_root_canon)
Definition at line 189 of file cache_storage.c.
References cs_root_find(), and cs_root_entry_t::state_inst.
brix_cache_state_root_by_root()
const char * brix_cache_state_root_by_root (const char * cache_root_canon)
Definition at line 109 of file cache_storage.c.
References cs_root_find(), and cs_root_entry_t::state_root.
Referenced by brix_cache_open().
brix_cache_state_storage()
brix_sd_instance_t * brix_cache_state_storage (const ngx_stream_brix_srv_conf_t * conf)
Definition at line 241 of file cache_storage.c.
References ngx_stream_brix_srv_conf_t::cache_state_inst.
brix_cache_storage()
brix_sd_instance_t * brix_cache_storage (const ngx_stream_brix_srv_conf_t * conf)
Definition at line 203 of file cache_storage.c.
References brix_sd_cache_instance_is(), brix_sd_cache_store_instance(), brix_vfs_backend_resolve(), c, ngx_stream_brix_srv_conf_t::cache_storage_inst, ngx_http_brix_shared_conf_t::cache_store, ngx_stream_brix_srv_conf_t::common, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by brix_cache_fill_from_source(), and brix_cache_purge_to_target().
brix_cache_storage_by_root()
brix_sd_instance_t * brix_cache_storage_by_root (const char * cache_root_canon)
Definition at line 182 of file cache_storage.c.
References cs_root_find(), cs_root_lazy_posix(), and cs_root_entry_t::read_inst.
Referenced by brix_cache_open().
brix_cache_storage_cleanup()
void brix_cache_storage_cleanup (ngx_stream_brix_srv_conf_t * conf)
Definition at line 436 of file cache_storage.c.
References brix_cstore_cleanup(), brix_sd_stage_destroy(), brix_sd_stage_source_instance(), brix_sd_xroot_destroy(), ngx_stream_brix_srv_conf_t::cache_rootfd, ngx_stream_brix_srv_conf_t::cache_state_inst, ngx_stream_brix_srv_conf_t::cache_state_rootfd, ngx_stream_brix_srv_conf_t::cache_storage_cstore, ngx_stream_brix_srv_conf_t::cache_storage_inst, ngx_stream_brix_srv_conf_t::cache_wt_stage_inst, ngx_stream_brix_srv_conf_t::cache_wt_stage_rootfd, ngx_stream_brix_srv_conf_t::cache_wt_stage_sd_inst, ngx_stream_brix_srv_conf_t::cache_wt_store_rootfd, and close().
Referenced by brix_exit_process().
brix_cache_storage_cstore()
brix_cstore_t * brix_cache_storage_cstore (const ngx_stream_brix_srv_conf_t * conf)
Definition at line 216 of file cache_storage.c.
References brix_sd_cache_cstore(), brix_sd_cache_instance_is(), brix_vfs_backend_resolve(), c, ngx_stream_brix_srv_conf_t::cache_storage_cstore, ngx_http_brix_shared_conf_t::cache_store, ngx_stream_brix_srv_conf_t::common, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by brix_cache_evict_if_needed(), brix_cache_purge_to_target(), brix_cache_reap_dirty(), and brix_cache_state_root().
brix_cache_storage_init()
ngx_int_t brix_cache_storage_init (ngx_stream_brix_srv_conf_t * conf, ngx_cycle_t * cycle)
Definition at line 339 of file cache_storage.c.
References BRIX_CMETA_AUTO, brix_cstore_init(), cache_build_instance(), cache_build_wt_stage(), ngx_http_brix_shared_conf_t::cache_index_cache, cache_open_rootfd(), ngx_stream_brix_srv_conf_t::cache_root, ngx_stream_brix_srv_conf_t::cache_rootfd, ngx_stream_brix_srv_conf_t::cache_source_inst, ngx_stream_brix_srv_conf_t::cache_state_inst, ngx_stream_brix_srv_conf_t::cache_state_root, ngx_stream_brix_srv_conf_t::cache_state_rootfd, ngx_stream_brix_srv_conf_t::cache_storage_cstore, ngx_stream_brix_srv_conf_t::cache_storage_inst, ngx_stream_brix_srv_conf_t::cache_wt_stage_backend, ngx_stream_brix_srv_conf_t::cache_wt_stage_inst, ngx_stream_brix_srv_conf_t::cache_wt_stage_root, ngx_stream_brix_srv_conf_t::cache_wt_stage_rootfd, ngx_stream_brix_srv_conf_t::cache_wt_stage_sd_inst, ngx_stream_brix_srv_conf_t::cache_wt_store_rootfd, ngx_stream_brix_srv_conf_t::common, cs_root_register(), log, and ngx_pcalloc().
Referenced by ngx_stream_brix_init_process().
brix_cache_wt_stage()
brix_sd_instance_t * brix_cache_wt_stage (const ngx_stream_brix_srv_conf_t * conf)
Definition at line 247 of file cache_storage.c.
References ngx_stream_brix_srv_conf_t::cache_wt_stage_inst.
brix_cache_wt_stage_sd_inst()
brix_sd_instance_t * brix_cache_wt_stage_sd_inst (const ngx_stream_brix_srv_conf_t * conf)
Definition at line 235 of file cache_storage.c.
References ngx_stream_brix_srv_conf_t::cache_wt_stage_sd_inst.
Referenced by brix_open_resolved_file().
cache_build_instance()
static brix_sd_instance_t * cache_build_instance (ngx_pool_t * pool, ngx_log_t * log, const ngx_str_t * root, const ngx_str_t * backend, int rootfd) static
Definition at line 276 of file cache_storage.c.
References brix_sd_posix_borrow_instance(), brix_vfs_backend_resolve(), and log.
Referenced by brix_cache_storage_init().
cache_build_wt_stage()
static void cache_build_wt_stage (ngx_pool_t * pool, ngx_log_t * log, ngx_stream_brix_srv_conf_t * conf) static
Definition at line 297 of file cache_storage.c.
References brix_cache_build_wt_origin(), brix_sd_posix_borrow_instance(), brix_sd_stage_create(), brix_sd_xroot_destroy(), brix_vfs_backend_resolve(), BRIX_WT_MODE_ASYNC, BRIX_WT_MODE_SYNC, ngx_stream_brix_srv_conf_t::cache_origin_host, ngx_stream_brix_srv_conf_t::cache_wt_stage_sd_inst, ngx_stream_brix_srv_conf_t::cache_wt_store_rootfd, ngx_stream_brix_srv_conf_t::common, brix_wt_conf_t::enable, brix_stage_policy_t::flush_mode, log, brix_wt_conf_t::mode, O_PATH, open(), brix_wt_conf_t::origin_host, ngx_http_brix_shared_conf_t::root_canon, and ngx_stream_brix_srv_conf_t::wt.
Referenced by brix_cache_storage_init().
cache_open_rootfd()
static int cache_open_rootfd (const ngx_str_t * root, ngx_log_t * log) static
Definition at line 256 of file cache_storage.c.
References log, O_PATH, and open().
Referenced by brix_cache_storage_init().
cs_root_find()
static cs_root_entry_t * cs_root_find (const char * root) static
Definition at line 136 of file cache_storage.c.
References cs_root_count, and cs_root_table.
Referenced by brix_cache_state_by_root(), brix_cache_state_root_by_root(), and brix_cache_storage_by_root().
cs_root_lazy_posix()
static brix_sd_instance_t * cs_root_lazy_posix (const char * root) static
Definition at line 159 of file cache_storage.c.
References brix_sd_posix_borrow_instance(), close(), cs_root_register(), O_PATH, and open().
Referenced by brix_cache_storage_by_root().
cs_root_register()
static void cs_root_register (const char * root, const char * state_root, brix_sd_instance_t * read_inst, brix_sd_instance_t * state_inst) static
Definition at line 78 of file cache_storage.c.
References BRIX_CACHE_STORAGE_MAX, cs_root_count, cs_root_table, cs_root_entry_t::read_inst, cs_root_entry_t::root, cs_root_entry_t::state_inst, and cs_root_entry_t::state_root.
Referenced by brix_cache_storage_init(), and cs_root_lazy_posix().
Variable Documentation
cs_root_count
ngx_uint_t cs_root_count static
Definition at line 74 of file cache_storage.c.
Referenced by cs_root_find(), and cs_root_register().
cs_root_table
cs_root_entry_t cs_root_table[64] static
Definition at line 73 of file cache_storage.c.
Referenced by cs_root_find(), and cs_root_register().