nginx-xrootd: src/fs/cache/cache_internal.h File Reference
cache_internal.h File Reference
#include "core/ngx_brix_module.h"
#include "fs/backend/sd.h"
#include "stage_admit.h"
Data Structures
struct brix_cache_origin_conn_t
struct brix_cache_fill_t
struct brix_wt_flush_t
struct brix_cache_cksum_out_t
struct brix_cache_dirlist_t
struct brix_cache_sink_t
struct brix_cache_read_range_t
Macros
#define BRIX_CACHE_FETCH_CHUNK (1024 * 1024)
#define BRIX_CACHE_IO_TIMEOUT 30
#define BRIX_CACHE_LOCK_POLL_USEC 200000
#define BRIX_CACHE_PART_SUFFIX ".ngx-xrootd-part"
#define BRIX_CACHE_LOCK_SUFFIX ".ngx-xrootd-lock"
#define BRIX_CACHE_EVICT_LOCK_NAME ".ngx-xrootd-evict-lock"
#define BRIX_CACHE_PPM_FULL_SCALE 1000000
Functions
brix_wt_admit_t brix_wt_stage_admit (const ngx_stream_brix_srv_conf_t *conf)
const char * brix_cache_state_root (const ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_cache_state_path (const ngx_stream_brix_srv_conf_t *conf, const char *resolved, char *dst, size_t dstsz)
void brix_cache_set_error (brix_cache_fill_t *t, int xrd_error, int sys_errno, const char *msg)
void brix_cache_set_syserror (brix_cache_fill_t *t, int xrd_error, const char *prefix)
int brix_cache_io_send (brix_cache_origin_conn_t *oc, const void *buf, size_t len)
int brix_cache_io_recv_exact (brix_cache_origin_conn_t *oc, void *buf, size_t len)
int brix_cache_fd_write_all (int fd, const void *buf, size_t len, off_t offset)
int brix_cache_append_suffix (char *dst, size_t dstsz, const char *path, const char *suffix)
int brix_cache_ensure_parent (const char *path)
int brix_cache_file_ready (const char *path)
int brix_cache_wait_or_lock (brix_cache_fill_t *t, int *owned)
void brix_cache_origin_close (brix_cache_origin_conn_t *oc)
int brix_cache_origin_connect (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc)
int brix_cache_origin_connect_addr (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const ngx_str_t *host, uint16_t port)
int brix_cache_origin_tls_upgrade (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const ngx_str_t *host)
int brix_cache_read_response (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, uint16_t *status, u_char **body, uint32_t *dlen, uint32_t max_body)
void brix_cache_set_origin_error (brix_cache_fill_t *t, u_char *body, uint32_t dlen, const char *fallback)
int brix_cache_origin_bootstrap (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc)
int brix_cache_origin_auth_ztn (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const ngx_str_t *token)
int brix_cache_origin_auth_gsi (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *gsi_parms, const char *proxy_path)
int brix_cache_origin_auth_sss (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *keytab_path)
int brix_cache_origin_open (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, u_char fhandle[4])
int brix_cache_origin_query_checksum (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const brix_cache_cksum_out_t *out)
int brix_cache_origin_rename (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *src, const char *dst)
int brix_cache_origin_rm (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *path)
int brix_cache_origin_rmdir (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *path)
ssize_t brix_cache_origin_getfattr (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *path, const char *name, void *buf, size_t cap)
ssize_t brix_cache_origin_listfattr (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *path, void *buf, size_t cap)
int brix_cache_origin_setfattr (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *path, const char *name, const void *val, size_t vlen)
int brix_cache_origin_delfattr (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *path, const char *name)
void brix_cache_dirlist_init (brix_cache_dirlist_t *dl)
void brix_cache_dirlist_free (brix_cache_dirlist_t *dl)
int brix_cache_origin_dirlist (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *path, brix_cache_dirlist_t *dl)
int brix_cache_origin_open_write (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *path, uint16_t mode_bits, u_char fhandle[4])
void brix_cache_origin_close_file (brix_cache_origin_conn_t *oc, const u_char fhandle[4])
int brix_cache_sink_pwrite (brix_cache_sink_t *sink, const void *buf, size_t len, off_t off)
int brix_cache_origin_read_chunk (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const u_char fhandle[4], brix_cache_sink_t *sink, brix_cache_read_range_t *rng)
int brix_cache_origin_write_chunk (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const u_char fhandle[4], uint64_t offset, const u_char *data, size_t len)
int brix_cache_origin_truncate (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const u_char fhandle[4], uint64_t length)
int brix_cache_origin_sync (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const u_char fhandle[4])
int brix_cache_fetch_origin (brix_cache_fill_t *t)
brix_sd_instance_t * brix_cache_build_wt_origin (const ngx_stream_brix_srv_conf_t *conf, ngx_log_t *log)
void brix_cache_evict_if_needed (brix_cache_fill_t *t, const char *protect_path, ngx_log_t *log)
void brix_cache_fill_thread (void *data, ngx_log_t *log)
void brix_cache_fill_done (ngx_event_t *ev)
Macro Definition Documentation
BRIX_CACHE_EVICT_LOCK_NAME
#define BRIX_CACHE_EVICT_LOCK_NAME ".ngx-xrootd-evict-lock"
Definition at line 51 of file cache_internal.h.
BRIX_CACHE_FETCH_CHUNK
#define BRIX_CACHE_FETCH_CHUNK (1024 * 1024)
Definition at line 46 of file cache_internal.h.
BRIX_CACHE_IO_TIMEOUT
#define BRIX_CACHE_IO_TIMEOUT 30
Definition at line 47 of file cache_internal.h.
BRIX_CACHE_LOCK_POLL_USEC
#define BRIX_CACHE_LOCK_POLL_USEC 200000
Definition at line 48 of file cache_internal.h.
BRIX_CACHE_LOCK_SUFFIX
#define BRIX_CACHE_LOCK_SUFFIX ".ngx-xrootd-lock"
Definition at line 50 of file cache_internal.h.
BRIX_CACHE_PART_SUFFIX
#define BRIX_CACHE_PART_SUFFIX ".ngx-xrootd-part"
Definition at line 49 of file cache_internal.h.
BRIX_CACHE_PPM_FULL_SCALE
#define BRIX_CACHE_PPM_FULL_SCALE 1000000
Definition at line 54 of file cache_internal.h.
Function Documentation
brix_cache_append_suffix()
int brix_cache_append_suffix (char * dst, size_t dstsz, const char * path, const char * suffix)
Definition at line 24 of file paths.c.
Referenced by brix_cache_meta_path(), and brix_cache_open_or_fill().
brix_cache_build_wt_origin()
brix_sd_instance_t * brix_cache_build_wt_origin (const ngx_stream_brix_srv_conf_t * conf, ngx_log_t * log)
Definition at line 134 of file fetch.c.
References brix_sd_xroot_create_origin(), brix_sd_xroot_origin_cfg_t::host, and log.
Referenced by cache_build_wt_stage().
brix_cache_dirlist_free()
void brix_cache_dirlist_free (brix_cache_dirlist_t * dl)
Definition at line 398 of file origin_ns.c.
References brix_cache_dirlist_t::count, and brix_cache_dirlist_t::names.
Referenced by sd_xroot_closedir(), and sd_xroot_opendir_common().
brix_cache_dirlist_init()
void brix_cache_dirlist_init (brix_cache_dirlist_t * dl)
Definition at line 389 of file origin_ns.c.
Referenced by sd_xroot_opendir_common().
brix_cache_ensure_parent()
int brix_cache_ensure_parent (const char * path)
Definition at line 44 of file paths.c.
References brix_mkdir_recursive(), and PATH_MAX.
Referenced by brix_cache_fill_thread().
brix_cache_evict_if_needed()
void brix_cache_evict_if_needed (brix_cache_fill_t * t, const char * protect_path, ngx_log_t * log)
Definition at line 479 of file evict_policy.c.
References brix_cache_evict_unlock(), brix_cache_metric_add, BRIX_CACHE_PPM_FULL_SCALE, brix_cache_purge_to_target(), brix_cache_storage_cstore(), brix_cache_try_evict_lock(), brix_cache_usage_measure(), brix_cache_fill_t::c, brix_cache_fill_t::conf, brix_cache_fill_t::ctx, log, PATH_MAX, and usage().
Referenced by brix_cache_fill_thread().
brix_cache_fd_write_all()
int brix_cache_fd_write_all (int fd, const void * buf, size_t len, off_t offset)
Definition at line 122 of file io.c.
References brix_sd_posix_wrap().
Referenced by brix_cache_sink_pwrite().
brix_cache_fetch_origin()
int brix_cache_fetch_origin (brix_cache_fill_t * t)
Definition at line 347 of file fetch.c.
References brix_cache_fill_from_source(), brix_cache_set_error(), kXR_ServerError, and brix_cache_fill_t::source_inst.
Referenced by brix_cache_fill_thread().
brix_cache_file_ready()
int brix_cache_file_ready (const char * path)
Definition at line 73 of file paths.c.
brix_cache_fill_done()
void brix_cache_fill_done (ngx_event_t * ev)
Definition at line 67 of file thread.c.
References brix_aio_restore_request(), brix_aio_resume(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OPEN_RD, brix_open_resolved_file(), brix_send_error(), brix_send_redirect(), brix_srv_register(), c, brix_cache_fill_t::c, brix_cache_fill_t::cache_path, brix_cache_fill_t::clean_path, brix_cache_fill_t::conf, brix_cache_fill_t::ctx, brix_cache_fill_t::err_msg, kXR_ServerError, kXR_Unsupported, brix_cache_fill_t::mode_bits, brix_cache_fill_t::options, brix_open_request_t::resolved, brix_cache_fill_t::result, brix_ctx_t::state, brix_cache_fill_t::streamid, brix_cache_fill_t::xrd_error, and XRD_ST_SENDING.
Referenced by brix_cache_open_or_fill().
brix_cache_fill_thread()
void brix_cache_fill_thread (void * data, ngx_log_t * log)
Definition at line 14 of file thread.c.
References brix_cache_ensure_parent(), brix_cache_evict_if_needed(), brix_cache_fetch_origin(), brix_cache_ready(), brix_cache_set_syserror(), brix_cache_wait_or_lock(), brix_cache_fill_t::cache_path, brix_cache_fill_t::conf, brix_cache_fill_t::err_msg, kXR_IOError, brix_cache_fill_t::lock_path, log, brix_cache_fill_t::result, brix_cache_fill_t::sys_errno, and brix_cache_fill_t::xrd_error.
Referenced by brix_cache_open_or_fill().
brix_cache_io_recv_exact()
int brix_cache_io_recv_exact (brix_cache_origin_conn_t * oc, void * buf, size_t len)
Definition at line 69 of file io.c.
References brix_cache_origin_conn_t::fd, and brix_cache_origin_conn_t::ssl.
Referenced by brix_cache_read_response().
brix_cache_io_send()
int brix_cache_io_send (brix_cache_origin_conn_t * oc, const void * buf, size_t len)
Definition at line 15 of file io.c.
References brix_cache_origin_conn_t::fd, and brix_cache_origin_conn_t::ssl.
Referenced by brix_cache_origin_close_file(), brix_cache_origin_dirlist(), brix_cache_origin_open(), brix_cache_origin_open_write(), brix_cache_origin_read_chunk(), brix_cache_origin_sync(), brix_cache_origin_truncate(), brix_cache_origin_write_chunk(), cache_origin_send_kxr_auth(), origin_bs_handshake(), origin_bs_login(), origin_bs_protocol(), origin_cksum_send_query(), and origin_request().
brix_cache_origin_auth_gsi()
int brix_cache_origin_auth_gsi (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * gsi_parms, const char * proxy_path)
Definition at line 545 of file origin_auth.c.
References originauth_gsi_certreq(), originauth_gsi_load_credential(), originauth_gsi_read_cert(), originauth_gsi_read_final(), originauth_gsi_send_response(), originauth_gsi_verify_srv_cert(), originauth_gsi_warn_bare_cert(), originauth_gsi_cred_t::pem, originauth_gsi_cred_t::pem_len, and proxy_path().
Referenced by origin_bs_auth_dispatch().
brix_cache_origin_auth_sss()
int brix_cache_origin_auth_sss (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * keytab_path)
Definition at line 641 of file origin_auth.c.
References brix_cache_read_response(), brix_cache_set_error(), brix_cache_set_origin_error(), brix_sss_build_proxy_credential(), cache_origin_load_sss_key(), cache_origin_send_kxr_auth(), key, kXR_AuthFailed, kXR_error, kXR_ok, and kXR_ServerError.
Referenced by origin_bs_auth_dispatch().
brix_cache_origin_auth_ztn()
int brix_cache_origin_auth_ztn (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const ngx_str_t * token)
Definition at line 132 of file origin_auth.c.
References brix_cache_read_response(), brix_cache_set_error(), brix_cache_set_origin_error(), cache_origin_build_ztn_credential(), cache_origin_send_kxr_auth(), kXR_AuthFailed, kXR_error, kXR_NoMemory, kXR_ok, and kXR_ServerError.
Referenced by origin_bs_auth_dispatch(), and origin_bs_authmore_fallback().
brix_cache_origin_bootstrap()
int brix_cache_origin_bootstrap (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc)
Definition at line 355 of file origin_protocol.c.
References origin_frame_t::body, brix_cache_set_error(), BRIX_SESSION_ID_LEN, origin_frame_t::dlen, kXR_authmore, kXR_ok, kXR_ServerError, origin_auth_advert_t::needs_auth, origin_bs_auth_dispatch(), origin_bs_authmore_fallback(), origin_bs_handshake(), origin_bs_login(), origin_bs_parse_advert(), origin_bs_protocol(), and origin_frame_t::status.
Referenced by proxy_gsi_login_thread(), sd_xroot_origin_open(), sd_xroot_session(), and sd_xroot_staged_connect_open().
brix_cache_origin_close()
void brix_cache_origin_close (brix_cache_origin_conn_t * oc)
Definition at line 23 of file origin_connection.c.
References close(), brix_cache_origin_conn_t::fd, brix_cache_origin_conn_t::ssl, and brix_cache_origin_conn_t::ssl_ctx.
Referenced by proxy_gsi_login_thread(), sd_xroot_getxattr(), sd_xroot_getxattr_cred(), sd_xroot_listxattr(), sd_xroot_listxattr_cred(), sd_xroot_obj_teardown(), sd_xroot_opendir_common(), sd_xroot_removexattr(), sd_xroot_removexattr_cred(), sd_xroot_rename(), sd_xroot_rename_cred(), sd_xroot_server_copy(), sd_xroot_server_copy_cred(), sd_xroot_session(), sd_xroot_setxattr(), sd_xroot_setxattr_cred(), sd_xroot_staged_connect_open(), sd_xroot_staged_teardown(), sd_xroot_unlink(), and sd_xroot_unlink_cred().
brix_cache_origin_close_file()
void brix_cache_origin_close_file (brix_cache_origin_conn_t * oc, const u_char fhandle[4])
Definition at line 123 of file origin_write.c.
References brix_cache_io_send(), brix_cache_read_response(), ClientCloseRequest::dlen, ClientCloseRequest::fhandle, kXR_close, ngx_memcpy, ClientCloseRequest::requestid, brix_cache_fill_t::result, ClientCloseRequest::streamid, and XRD_FHANDLE_LEN.
Referenced by sd_xroot_obj_teardown(), sd_xroot_server_copy(), sd_xroot_server_copy_cred(), and sd_xroot_staged_teardown().
brix_cache_origin_connect()
int brix_cache_origin_connect (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc)
Definition at line 243 of file origin_connection.c.
References brix_cache_origin_connect_addr(), and brix_cache_fill_t::conf.
Referenced by proxy_gsi_login_thread(), sd_xroot_origin_open(), sd_xroot_session(), and sd_xroot_staged_connect_open().
brix_cache_origin_connect_addr()
int brix_cache_origin_connect_addr (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const ngx_str_t * host, uint16_t port)
Definition at line 164 of file origin_connection.c.
References BRIX_AF_AUTO, brix_apply_socket_io_timeouts(), BRIX_CACHE_IO_TIMEOUT, brix_cache_set_error(), brix_cache_set_syserror(), brix_connect_fd_deadline(), close(), brix_cache_fill_t::conf, brix_cache_origin_conn_t::fd, host, kXR_ServerError, port, brix_cache_origin_conn_t::ssl, and brix_cache_origin_conn_t::ssl_ctx.
Referenced by brix_cache_origin_connect().
brix_cache_origin_delfattr()
int brix_cache_origin_delfattr (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * path, const char * name)
Definition at line 378 of file origin_ns.c.
References kXR_fattrDel, name, and origin_fattr_set_or_del().
Referenced by sd_xroot_removexattr(), and sd_xroot_removexattr_cred().
brix_cache_origin_dirlist()
int brix_cache_origin_dirlist (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * path, brix_cache_dirlist_t * dl)
Definition at line 515 of file origin_ns.c.
References ClientRequestHdr::body, brix_cache_dirlist_split(), BRIX_CACHE_FETCH_CHUNK, brix_cache_io_send(), brix_cache_read_response(), brix_cache_set_error(), ClientRequestHdr::dlen, kXR_dirlist, kXR_error, kXR_ok, kXR_oksofar, kXR_ServerError, ngx_memcpy, xrdw_dirlist_req_t::options, origin_status_errno(), ClientRequestHdr::requestid, ClientRequestHdr::streamid, XRDW_BODY_LEN, and xrdw_dirlist_req_pack().
Referenced by sd_xroot_opendir_common().
brix_cache_origin_getfattr()
ssize_t brix_cache_origin_getfattr (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * path, const char * name, void * buf, size_t cap)
Definition at line 231 of file origin_ns.c.
References kXR_fattr, kXR_fattrGet, kXR_ok, name, ngx_memcpy, origin_fattr_payload(), origin_request(), origin_status_errno(), xrdw_fattr_req_t::subcode, xrdp_fattr_nvec_parse(), XRDW_BODY_LEN, and xrdw_fattr_req_pack().
Referenced by sd_xroot_getxattr(), and sd_xroot_getxattr_cred().
brix_cache_origin_listfattr()
ssize_t brix_cache_origin_listfattr (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * path, void * buf, size_t cap)
Definition at line 286 of file origin_ns.c.
References kXR_fattr, kXR_fattrList, kXR_ok, ngx_memcpy, origin_request(), origin_status_errno(), xrdw_fattr_req_t::subcode, XRDW_BODY_LEN, and xrdw_fattr_req_pack().
Referenced by sd_xroot_listxattr(), and sd_xroot_listxattr_cred().
brix_cache_origin_open()
int brix_cache_origin_open (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, u_char fhandle[4])
Definition at line 408 of file origin_protocol.c.
References brix_cache_io_send(), brix_cache_read_response(), brix_cache_set_error(), brix_cache_set_origin_error(), BRIX_MAX_PATH, brix_cache_fill_t::clean_path, ClientOpenRequest::dlen, brix_cache_fill_t::file_size, kXR_error, kXR_NoMemory, kXR_ok, kXR_open, kXR_open_read, kXR_redirect, kXR_retstat, kXR_ServerError, kXR_Unsupported, ngx_memcpy, xrdw_open_req_t::options, ClientOpenRequest::requestid, ClientOpenRequest::streamid, XRD_FHANDLE_LEN, and xrdw_open_req_pack().
Referenced by sd_xroot_origin_do_open(), sd_xroot_server_copy(), and sd_xroot_server_copy_cred().
brix_cache_origin_open_write()
int brix_cache_origin_open_write (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * path, uint16_t mode_bits, u_char fhandle[4])
Definition at line 28 of file origin_write.c.
References brix_cache_io_send(), brix_cache_read_response(), brix_cache_set_error(), brix_cache_set_origin_error(), BRIX_MAX_PATH, ClientOpenRequest::dlen, kXR_ArgInvalid, kXR_delete, kXR_error, kXR_mkpath, kXR_NoMemory, kXR_ok, kXR_open, kXR_open_updt, kXR_redirect, kXR_ServerError, kXR_Unsupported, xrdw_open_req_t::mode, ngx_memcpy, ClientOpenRequest::requestid, ClientOpenRequest::streamid, XRD_FHANDLE_LEN, and xrdw_open_req_pack().
Referenced by sd_xroot_origin_do_open(), sd_xroot_server_copy(), sd_xroot_server_copy_cred(), and sd_xroot_staged_connect_open().
brix_cache_origin_query_checksum()
int brix_cache_origin_query_checksum (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const brix_cache_cksum_out_t * out)
Definition at line 594 of file origin_protocol.c.
References brix_cache_cksum_out_t::alg, brix_cache_cksum_out_t::alg_sz, brix_cache_read_response(), brix_cache_cksum_out_t::hex, brix_cache_cksum_out_t::hex_sz, kXR_asynresp, kXR_attn, kXR_ok, kXR_waitresp, origin_cksum_send_query(), origin_cksum_split(), brix_cache_fill_t::result, brix_cache_fill_t::xrd_error, xrd_get_u32_be(), and xrd_resp_hdr_unpack().
Referenced by brix_sd_xroot_query_checksum().
brix_cache_origin_read_chunk()
int brix_cache_origin_read_chunk (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const u_char fhandle[4], brix_cache_sink_t * sink, brix_cache_read_range_t * rng)
Definition at line 692 of file origin_protocol.c.
References BRIX_CACHE_FETCH_CHUNK, brix_cache_io_send(), brix_cache_read_response(), brix_cache_set_error(), brix_cache_set_origin_error(), brix_cache_set_syserror(), brix_cache_sink_pwrite(), ClientReadRequest::dlen, brix_cache_read_range_t::dst_off, ClientReadRequest::fhandle, brix_cache_read_range_t::got, kXR_error, kXR_IOError, kXR_ok, kXR_oksofar, kXR_read, kXR_ServerError, ngx_memcpy, ClientReadRequest::offset, brix_cache_read_range_t::read_off, ClientReadRequest::requestid, ClientReadRequest::rlen, ClientReadRequest::streamid, brix_cache_read_range_t::want, and XRD_FHANDLE_LEN.
Referenced by sd_xroot_copy_body(), and sd_xroot_pread().
brix_cache_origin_rename()
int brix_cache_origin_rename (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * src, const char * dst)
Definition at line 86 of file origin_ns.c.
References xrdw_twopath_req_t::arg1len, kXR_mv, kXR_ok, ngx_memcpy, origin_request(), origin_status_errno(), XRDW_BODY_LEN, and xrdw_twopath_req_pack().
Referenced by sd_xroot_rename(), and sd_xroot_rename_cred().
brix_cache_origin_rm()
int brix_cache_origin_rm (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * path)
Definition at line 135 of file origin_ns.c.
References kXR_ok, kXR_rm, origin_request(), origin_status_errno(), and XRDW_BODY_LEN.
Referenced by sd_xroot_unlink(), and sd_xroot_unlink_cred().
brix_cache_origin_rmdir()
int brix_cache_origin_rmdir (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * path)
Definition at line 171 of file origin_ns.c.
References kXR_ok, kXR_rmdir, origin_request(), origin_status_errno(), and XRDW_BODY_LEN.
Referenced by sd_xroot_unlink(), and sd_xroot_unlink_cred().
brix_cache_origin_setfattr()
int brix_cache_origin_setfattr (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * path, const char * name, const void * val, size_t vlen)
Definition at line 369 of file origin_ns.c.
References kXR_fattrSet, name, and origin_fattr_set_or_del().
Referenced by sd_xroot_setxattr(), and sd_xroot_setxattr_cred().
brix_cache_origin_sync()
int brix_cache_origin_sync (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const u_char fhandle[4])
Definition at line 259 of file origin_write.c.
References brix_cache_io_send(), brix_cache_read_response(), brix_cache_set_error(), brix_cache_set_origin_error(), ClientSyncRequest::dlen, ClientSyncRequest::fhandle, kXR_error, kXR_ok, kXR_ServerError, kXR_sync, ngx_memcpy, ClientSyncRequest::requestid, ClientSyncRequest::streamid, and XRD_FHANDLE_LEN.
Referenced by sd_xroot_copy_body(), sd_xroot_fsync(), and sd_xroot_staged_commit().
brix_cache_origin_tls_upgrade()
int brix_cache_origin_tls_upgrade (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const ngx_str_t * host)
Definition at line 93 of file origin_connection.c.
References brix_cache_set_error(), brix_cache_fill_t::conf, brix_cache_origin_conn_t::fd, host, kXR_ServerError, kXR_TLSRequired, ngx_memcpy, origin_tls_load_verify(), brix_cache_origin_conn_t::ssl, and brix_cache_origin_conn_t::ssl_ctx.
Referenced by origin_bs_protocol().
brix_cache_origin_truncate()
int brix_cache_origin_truncate (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const u_char fhandle[4], uint64_t length)
Definition at line 210 of file origin_write.c.
References brix_cache_io_send(), brix_cache_read_response(), brix_cache_set_error(), brix_cache_set_origin_error(), ClientTruncateRequest::dlen, ClientTruncateRequest::fhandle, kXR_error, kXR_ok, kXR_ServerError, kXR_truncate, ngx_memcpy, ClientTruncateRequest::offset, ClientTruncateRequest::requestid, ClientTruncateRequest::streamid, and XRD_FHANDLE_LEN.
Referenced by sd_xroot_copy_body(), and sd_xroot_ftruncate().
brix_cache_origin_write_chunk()
int brix_cache_origin_write_chunk (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const u_char fhandle[4], uint64_t offset, const u_char * data, size_t len)
Definition at line 153 of file origin_write.c.
References brix_cache_io_send(), brix_cache_read_response(), brix_cache_set_error(), brix_cache_set_origin_error(), ClientWriteRequest::dlen, ClientWriteRequest::fhandle, kXR_ArgTooLong, kXR_error, kXR_ok, kXR_ServerError, kXR_write, ngx_memcpy, ClientWriteRequest::offset, ClientWriteRequest::requestid, ClientWriteRequest::streamid, and XRD_FHANDLE_LEN.
Referenced by sd_xroot_copy_body(), sd_xroot_pwrite(), and sd_xroot_staged_write().
brix_cache_read_response()
int brix_cache_read_response (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, uint16_t * status, u_char ** body, uint32_t * dlen, uint32_t max_body)
Definition at line 31 of file origin_response.c.
References brix_cache_io_recv_exact(), brix_cache_set_error(), ServerResponseHdr::dlen, kXR_NoMemory, kXR_ServerError, and ServerResponseHdr::status.
Referenced by brix_cache_origin_auth_sss(), brix_cache_origin_auth_ztn(), brix_cache_origin_close_file(), brix_cache_origin_dirlist(), brix_cache_origin_open(), brix_cache_origin_open_write(), brix_cache_origin_query_checksum(), brix_cache_origin_read_chunk(), brix_cache_origin_sync(), brix_cache_origin_truncate(), brix_cache_origin_write_chunk(), origin_bs_login(), origin_expect_frame(), origin_request(), originauth_gsi_read_cert(), and originauth_gsi_read_final().
brix_cache_set_error()
void brix_cache_set_error (brix_cache_fill_t * t, int xrd_error, int sys_errno, const char * msg)
Definition at line 12 of file errors.c.
References brix_cache_fill_t::err_msg, brix_cache_fill_t::result, brix_cache_fill_t::sys_errno, and brix_cache_fill_t::xrd_error.
Referenced by brix_cache_commit_staged(), brix_cache_fetch_origin(), brix_cache_fill_body(), brix_cache_fill_from_source(), brix_cache_origin_auth_sss(), brix_cache_origin_auth_ztn(), brix_cache_origin_bootstrap(), brix_cache_origin_connect_addr(), brix_cache_origin_dirlist(), brix_cache_origin_open(), brix_cache_origin_open_write(), brix_cache_origin_read_chunk(), brix_cache_origin_sync(), brix_cache_origin_tls_upgrade(), brix_cache_origin_truncate(), brix_cache_origin_write_chunk(), brix_cache_read_response(), brix_cache_set_origin_error(), brix_cache_set_syserror(), brix_cache_verify_no_origin(), brix_cache_verify_report_mismatch(), brix_cache_verify_unsupported(), brix_cache_wait_or_lock(), origin_bs_auth_dispatch(), origin_bs_authmore_fallback(), origin_bs_handshake(), origin_bs_login(), origin_bs_protocol(), origin_expect_frame(), originauth_gsi_certreq(), originauth_gsi_load_credential(), originauth_gsi_read_cert(), originauth_gsi_read_final(), originauth_gsi_send_response(), and originauth_gsi_verify_srv_cert().
brix_cache_set_origin_error()
void brix_cache_set_origin_error (brix_cache_fill_t * t, u_char * body, uint32_t dlen, const char * fallback)
Definition at line 79 of file origin_response.c.
References brix_cache_set_error(), kXR_ServerError, ngx_memcpy, and xrd_error_body_decode().
Referenced by brix_cache_origin_auth_sss(), brix_cache_origin_auth_ztn(), brix_cache_origin_open(), brix_cache_origin_open_write(), brix_cache_origin_read_chunk(), brix_cache_origin_sync(), brix_cache_origin_truncate(), brix_cache_origin_write_chunk(), originauth_gsi_read_cert(), and originauth_gsi_read_final().
brix_cache_set_syserror()
void brix_cache_set_syserror (brix_cache_fill_t * t, int xrd_error, const char * prefix)
Definition at line 30 of file errors.c.
References brix_cache_set_error().
Referenced by brix_cache_commit_staged(), brix_cache_fill_thread(), brix_cache_origin_connect_addr(), brix_cache_origin_read_chunk(), brix_cache_verify_part(), and brix_cache_wait_or_lock().
brix_cache_sink_pwrite()
int brix_cache_sink_pwrite (brix_cache_sink_t * sink, const void * buf, size_t len, off_t off)
Definition at line 305 of file origin_write.c.
References brix_cache_fd_write_all(), brix_cache_sink_t::fd, brix_cache_sink_t::mem, brix_cache_sink_t::mem_cap, ngx_memcpy, and brix_cache_sink_t::staged.
Referenced by brix_cache_fill_copy(), and brix_cache_origin_read_chunk().
brix_cache_state_path()
ngx_int_t brix_cache_state_path (const ngx_stream_brix_srv_conf_t * conf, const char * resolved, char * dst, size_t dstsz)
Definition at line 124 of file paths.c.
References brix_cache_path_for_resolved(), and brix_cache_state_root().
brix_cache_state_root()
const char * brix_cache_state_root (const ngx_stream_brix_srv_conf_t * conf)
Definition at line 93 of file paths.c.
References brix_cache_storage_cstore(), and brix_cstore_local_root().
Referenced by brix_cache_purge_setup(), brix_cache_reap_dirty(), brix_cache_state_path(), brix_cache_try_evict_lock(), brix_cache_watermark_purge(), brix_init_server_cache_reap_timer(), brix_init_server_watermark_timer(), and brix_server_setup_export().
brix_cache_wait_or_lock()
int brix_cache_wait_or_lock (brix_cache_fill_t * t, int * owned)
Definition at line 134 of file lock.c.
References brix_cache_file_ready(), brix_cache_lock_is_stale(), BRIX_CACHE_LOCK_POLL_USEC, brix_cache_set_error(), brix_cache_set_syserror(), brix_cache_try_lock(), brix_cache_fill_t::c, brix_cache_fill_t::cache_path, brix_cache_fill_t::conf, kXR_FileLocked, kXR_IOError, and brix_cache_fill_t::lock_path.
Referenced by brix_cache_fill_thread().
brix_wt_stage_admit()
brix_wt_admit_t brix_wt_stage_admit (const ngx_stream_brix_srv_conf_t * conf)
Definition at line 19 of file stage_admit.c.
References brix_cache_fs_usage_sampled(), brix_metric_wt_stage_usage_ratio(), BRIX_WT_ADMIT_ALLOW, brix_wt_stage_decide(), and usage().
Referenced by brix_open_stage_backpressure().