nginx-xrootd: src/fs/cache/cache_reap.c File Reference
cache_reap.c File Reference
#include "cache_reap.h"
#include "cinfo.h"
#include "cache_storage.h"
#include <dirent.h>
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct reap_ctx_t
Functions
static int reap_is_sidecar (const char *name)
static void reap_unlink_sidecars (const char *data_path)
static ngx_brix_srv_metrics_t * reap_metrics_slot (const ngx_stream_brix_srv_conf_t *conf)
static int reap_entry_candidate (const char *dir, const struct dirent *de, const reap_ctx_t *rc, char *child, int *is_dir)
static int reap_classify (const char *child, const reap_ctx_t *rc, brix_cache_cinfo_state_t *cs, brix_cache_reap_reason_t *reason)
static void reap_remove (const char *child, const reap_ctx_t *rc, const brix_cache_cinfo_state_t *cs, brix_cache_reap_reason_t reason)
static ngx_uint_t reap_dir (const char *dir, const reap_ctx_t *rc)
ngx_uint_t brix_cache_reap_dirty (const ngx_stream_brix_srv_conf_t *conf, ngx_log_t *log)
Function Documentation
brix_cache_reap_dirty()
ngx_uint_t brix_cache_reap_dirty (const ngx_stream_brix_srv_conf_t * conf, ngx_log_t * log)
Definition at line 256 of file cache_reap.c.
References brix_cache_state_root(), brix_cache_storage_cstore(), log, reap_dir(), reap_metrics_slot(), and stat().
Referenced by brix_cache_reap_handler().
reap_classify()
static int reap_classify (const char * child, const reap_ctx_t * rc, brix_cache_cinfo_state_t * cs, brix_cache_reap_reason_t * reason) static
Definition at line 134 of file cache_reap.c.
References brix_cache_cinfo_state(), BRIX_CACHE_REAP_ABANDONED, BRIX_CACHE_REAP_COMPLETED, BRIX_CACHE_REAP_INCOMPLETE, reap_ctx_t::cutoff, brix_cache_cinfo_state_t::dirty_since, brix_cache_cinfo_state_t::flush_gen, brix_cache_cinfo_state_t::is_dirty, and brix_cache_cinfo_state_t::last_flush.
Referenced by reap_dir().
reap_dir()
static ngx_uint_t reap_dir (const char * dir, const reap_ctx_t * rc) static
Definition at line 221 of file cache_reap.c.
References BRIX_CACHE_REAP_ABANDONED, PATH_MAX, reap_classify(), reap_dir(), reap_entry_candidate(), and reap_remove().
Referenced by brix_cache_reap_dirty(), and reap_dir().
reap_entry_candidate()
static int reap_entry_candidate (const char * dir, const struct dirent * de, const reap_ctx_t * rc, char * child, int * is_dir) static
Definition at line 97 of file cache_reap.c.
References reap_ctx_t::dev, lstat(), PATH_MAX, reap_is_sidecar(), and stat().
Referenced by reap_dir().
reap_is_sidecar()
static int reap_is_sidecar (const char * name) static
Definition at line 20 of file cache_reap.c.
References name.
Referenced by reap_entry_candidate().
reap_metrics_slot()
static ngx_brix_srv_metrics_t * reap_metrics_slot (const ngx_stream_brix_srv_conf_t * conf) static
Definition at line 50 of file cache_reap.c.
References BRIX_METRICS_MAX_SERVERS, ngx_brix_shm_zone, and ngx_brix_metrics_t::servers.
Referenced by brix_cache_reap_dirty().
reap_remove()
static void reap_remove (const char * child, const reap_ctx_t * rc, const brix_cache_cinfo_state_t * cs, brix_cache_reap_reason_t reason) static
Definition at line 179 of file cache_reap.c.
References BRIX_CACHE_REAP_COMPLETED, BRIX_CACHE_REAP_INCOMPLETE, brix_cstore_evict(), ngx_brix_srv_metrics_t::cache_dirty_reaped, reap_ctx_t::cstore, reap_ctx_t::data_root, brix_cache_cinfo_state_t::dirty_hi, brix_cache_cinfo_state_t::dirty_lo, reap_ctx_t::log, reap_unlink_sidecars(), and reap_ctx_t::slot.
Referenced by reap_dir().
reap_unlink_sidecars()
static void reap_unlink_sidecars (const char * data_path) static
Definition at line 34 of file cache_reap.c.
References brix_cache_cinfo_path(), and PATH_MAX.
Referenced by reap_remove().