nginx-xrootd: src/auth/authz/acc/capability.c File Reference
capability.c File Reference
#include "acc.h"
Functions
static int brix_acc_cap_subcomp (const brix_acc_cap_t *cap, const char *path, int plen, const char *pathsub, int sublen)
int brix_acc_cap_privs (brix_acc_cap_t *cap, brix_acc_priv_caps_t *out, const char *path, int plen, const char *pathsub)
Function Documentation
brix_acc_cap_privs()
int brix_acc_cap_privs (brix_acc_cap_t * cap, brix_acc_priv_caps_t * out, const char * path, int plen, const char * pathsub)
Definition at line 61 of file capability.c.
References brix_acc_cap_privs(), brix_acc_cap_subcomp(), brix_acc_cap_t::caps, brix_acc_cap_t::next, brix_acc_priv_caps_t::nprivs, brix_acc_cap_t::path, brix_acc_cap_t::plen, brix_acc_priv_caps_t::pprivs, and brix_acc_cap_t::tmpl.
Referenced by brix_acc_access(), and brix_acc_cap_privs().
brix_acc_cap_subcomp()
static int brix_acc_cap_subcomp (const brix_acc_cap_t * cap, const char * path, int plen, const char * pathsub, int sublen) static
Definition at line 31 of file capability.c.
References brix_acc_cap_t::path, brix_acc_cap_t::pins, and brix_acc_cap_t::prem.
Referenced by brix_acc_cap_privs().