nginx-xrootd: client/lib/observability/capture.c File Reference
capture.c File Reference
#include "brix.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct brix_capture
struct playback_ctx
Macros
#define XRDCAP_MAGIC "XRDCAP1\n"
#define XRDCAP_MAGIC_LEN 8
#define XRDCAP_WIRE_MAX (XRDC_DLEN_MAX + 64u)
Enumerations
enum xrdcap_rec_t { XRDCAP_REC_OK = 0 , XRDCAP_REC_END , XRDCAP_REC_TRUNC }
Functions
static void put_u16 (FILE *fp, uint16_t v)
static void put_u32 (FILE *fp, uint32_t v)
struct brix_capture * brix_capture_open (const char *path)
void brix_capture_meta (struct brix_capture *cap, const char *key, const char *val)
void brix_capture_frame (struct brix_capture *cap, int dir, uint16_t sid, int code, int is_request, const void *hdr, uint32_t hdrlen, const void *body, uint32_t blen)
void brix_capture_close (struct brix_capture *cap)
static int read_magic (FILE *fp, brix_status *st)
static int skip_bytes (FILE *fp, size_t n)
static uint16_t rd_u16 (FILE *fp)
static uint32_t rd_u32 (FILE *fp)
static xrdcap_rec_t replay_meta_record (FILE *fp, FILE *out, int *metas)
static void replay_hexdump_wire (FILE *out, const uint8_t *w, uint32_t wlen)
static xrdcap_rec_t replay_frame_record (FILE *fp, int verbose, FILE *out, int *frames)
int brix_capture_replay (const char *path, int verbose, FILE *out, brix_status *st)
static int is_session_op (int reqid)
static xrdcap_rec_t playback_skip_meta (FILE *fp)
static void playback_reissue_wire (playback_ctx *pc, uint16_t code, const uint8_t *w, uint32_t wlen)
static xrdcap_rec_t playback_frame_record (FILE *fp, playback_ctx *pc)
int brix_capture_playback (const char *path, const char *url, const brix_opts *co, FILE *out, brix_status *st)
Macro Definition Documentation
XRDCAP_MAGIC
#define XRDCAP_MAGIC "XRDCAP1\n"
Definition at line 25 of file capture.c.
XRDCAP_MAGIC_LEN
#define XRDCAP_MAGIC_LEN 8
Definition at line 26 of file capture.c.
XRDCAP_WIRE_MAX
#define XRDCAP_WIRE_MAX (XRDC_DLEN_MAX + 64u)
Definition at line 27 of file capture.c.
Enumeration Type Documentation
xrdcap_rec_t
enum xrdcap_rec_t
Enumerator
XRDCAP_REC_OK
XRDCAP_REC_END
XRDCAP_REC_TRUNC
Definition at line 175 of file capture.c.
Function Documentation
brix_capture_close()
void brix_capture_close (struct brix_capture * cap)
Definition at line 108 of file capture.c.
References brix_capture::fp.
Referenced by brix_close().
brix_capture_frame()
void brix_capture_frame (struct brix_capture * cap, int dir, uint16_t sid, int code, int is_request, const void * hdr, uint32_t hdrlen, const void * body, uint32_t blen)
Definition at line 86 of file capture.c.
References code, brix_capture::fp, put_u16(), and put_u32().
Referenced by brix_send_ext(), and recv_note_diag().
brix_capture_meta()
void brix_capture_meta (struct brix_capture * cap, const char * key, const char * val)
Definition at line 67 of file capture.c.
References brix_capture::fp, key, and put_u16().
Referenced by brix_connect().
brix_capture_open()
struct brix_capture * brix_capture_open (const char * path)
Definition at line 51 of file capture.c.
References brix_capture::fp, XRDCAP_MAGIC, and XRDCAP_MAGIC_LEN.
Referenced by brix_connect().
brix_capture_playback()
int brix_capture_playback (const char * path, const char * url, const brix_opts * co, FILE * out, brix_status * st)
Definition at line 430 of file capture.c.
References brix_close(), brix_connect(), brix_endpoint_parse(), brix_status_set(), c, playback_ctx::conn, brix_url::host, playback_ctx::issued, playback_ctx::ok, playback_ctx::out, playback_frame_record(), playback_skip_meta(), brix_url::port, read_magic(), XRDC_EPROTO, XRDC_EUSAGE, XRDCAP_REC_OK, and XRDCAP_REC_TRUNC.
Referenced by do_replay().
brix_capture_replay()
int brix_capture_replay (const char * path, int verbose, FILE * out, brix_status * st)
Definition at line 279 of file capture.c.
References brix_status_set(), brix_capture::fp, read_magic(), replay_frame_record(), replay_meta_record(), XRDC_EPROTO, XRDC_EUSAGE, XRDCAP_REC_OK, and XRDCAP_REC_TRUNC.
Referenced by do_replay().
is_session_op()
static int is_session_op (int reqid) static
Definition at line 319 of file capture.c.
References kXR_auth, kXR_bind, kXR_endsess, kXR_login, kXR_protocol, and kXR_sigver.
Referenced by playback_frame_record().
playback_frame_record()
static xrdcap_rec_t playback_frame_record (FILE * fp, playback_ctx * pc) static
Definition at line 406 of file capture.c.
References code, is_session_op(), playback_reissue_wire(), rd_u16(), rd_u32(), XRDCAP_REC_OK, XRDCAP_REC_TRUNC, and XRDCAP_WIRE_MAX.
Referenced by brix_capture_playback().
playback_reissue_wire()
static void playback_reissue_wire (playback_ctx * pc, uint16_t code, const uint8_t * w, uint32_t wlen) static
Definition at line 374 of file capture.c.
References brix_recv(), brix_reqid_name(), brix_status_clear(), brix_status_name(), brix_write_full(), code, playback_ctx::conn, brix_conn::io, playback_ctx::issued, brix_status::msg, playback_ctx::ok, and playback_ctx::out.
Referenced by playback_frame_record().
playback_skip_meta()
static xrdcap_rec_t playback_skip_meta (FILE * fp) static
Definition at line 335 of file capture.c.
References brix_capture::fp, rd_u16(), skip_bytes(), XRDCAP_REC_OK, and XRDCAP_REC_TRUNC.
Referenced by brix_capture_playback().
put_u16()
static void put_u16 (FILE * fp, uint16_t v) static
Definition at line 34 of file capture.c.
Referenced by brix_capture_frame(), and brix_capture_meta().
put_u32()
static void put_u32 (FILE * fp, uint32_t v) static
Definition at line 41 of file capture.c.
Referenced by brix_capture_frame().
rd_u16()
static uint16_t rd_u16 (FILE * fp) static
Definition at line 158 of file capture.c.
References brix_capture::fp.
Referenced by playback_frame_record(), playback_skip_meta(), replay_frame_record(), and replay_meta_record().
rd_u32()
static uint32_t rd_u32 (FILE * fp) static
Definition at line 159 of file capture.c.
References c, and brix_capture::fp.
Referenced by playback_frame_record(), and replay_frame_record().
read_magic()
static int read_magic (FILE * fp, brix_status * st) static
Definition at line 121 of file capture.c.
References brix_status_set(), brix_capture::fp, XRDC_EPROTO, XRDCAP_MAGIC, and XRDCAP_MAGIC_LEN.
Referenced by brix_capture_playback(), and brix_capture_replay().
replay_frame_record()
static xrdcap_rec_t replay_frame_record (FILE * fp, int verbose, FILE * out, int * frames) static
Definition at line 242 of file capture.c.
References brix_reqid_name(), brix_status_name(), code, brix_capture::fp, rd_u16(), rd_u32(), replay_hexdump_wire(), XRDCAP_REC_OK, XRDCAP_REC_TRUNC, and XRDCAP_WIRE_MAX.
Referenced by brix_capture_replay().
replay_hexdump_wire()
static void replay_hexdump_wire (FILE * out, const uint8_t * w, uint32_t wlen) static
Definition at line 222 of file capture.c.
Referenced by replay_frame_record().
replay_meta_record()
static xrdcap_rec_t replay_meta_record (FILE * fp, FILE * out, int * metas) static
Definition at line 190 of file capture.c.
References brix_capture::fp, key, rd_u16(), XRDCAP_REC_OK, and XRDCAP_REC_TRUNC.
Referenced by brix_capture_replay().
skip_bytes()
static int skip_bytes (FILE * fp, size_t n) static
Definition at line 145 of file capture.c.
References brix_capture::fp.
Referenced by playback_skip_meta().