nginx-xrootd: src/fs/backend/rados/cephfs_layout.c File Reference
cephfs_layout.c File Reference
#include "cephfs_layout.h"
Data Structures
struct cephfs_frag_split_t
Functions
static void decode_utime (cephfs_denc_t *d, int64_t *sec, uint32_t *nsec)
int cephfs_decode_file_layout (cephfs_denc_t *d, cephfs_layout_t *out)
int cephfs_decode_inode (cephfs_denc_t *d, cephfs_inode_t *out)
static uint32_t frag_bits (uint32_t enc)
static uint32_t frag_value (uint32_t enc)
static uint32_t frag_make_child (uint32_t enc, uint32_t nbits, uint32_t i)
static int cephfs_read_frag_splits (cephfs_denc_t *d, cephfs_frag_split_t *splits, uint32_t *nsplit_out)
static int32_t cephfs_frag_lookup_nway (const cephfs_frag_split_t *splits, uint32_t nsplit, uint32_t f)
static void cephfs_frag_push_children (uint32_t f, int32_t nb, uint32_t *stack, uint32_t *sp, int *trunc)
int cephfs_decode_fragtree (cephfs_denc_t *d, uint32_t *leaves, uint32_t max, uint32_t *count, int *truncated)
int cephfs_decode_xattrs (cephfs_denc_t *d, cephfs_xattr_t *out, uint32_t max, uint32_t *count, int *truncated)
static int decode_primary_body (cephfs_denc_t *d, cephfs_dentry_t *out)
int cephfs_decode_dentry (const void *buf, size_t len, cephfs_dentry_t *out)
Function Documentation
cephfs_decode_dentry()
int cephfs_decode_dentry (const void * buf, size_t len, cephfs_dentry_t * out)
Definition at line 306 of file cephfs_layout.c.
References cephfs_denc_finish(), cephfs_denc_init(), cephfs_denc_ok(), cephfs_denc_start(), cephfs_denc_str(), cephfs_denc_u64(), cephfs_denc_u8(), CEPHFS_DENTRY_REMOTE, decode_primary_body(), cephfs_dentry_t::kind, cephfs_dentry_t::remote_d_type, cephfs_dentry_t::remote_ino, and cephfs_denc_frame_t::struct_v.
cephfs_decode_file_layout()
int cephfs_decode_file_layout (cephfs_denc_t * d, cephfs_layout_t * out)
Definition at line 26 of file cephfs_layout.c.
References cephfs_denc_finish(), cephfs_denc_ok(), cephfs_denc_s64(), cephfs_denc_start(), cephfs_denc_u32(), cephfs_layout_t::object_size, cephfs_layout_t::pool_id, cephfs_layout_t::stripe_count, and cephfs_layout_t::stripe_unit.
Referenced by cephfs_decode_inode().
cephfs_decode_fragtree()
int cephfs_decode_fragtree (cephfs_denc_t * d, uint32_t * leaves, uint32_t max, uint32_t * count, int * truncated)
Definition at line 212 of file cephfs_layout.c.
References cephfs_denc_ok(), cephfs_frag_lookup_nway(), cephfs_frag_push_children(), CEPHFS_MAX_FRAGS, and cephfs_read_frag_splits().
Referenced by decode_primary_body().
cephfs_decode_inode()
int cephfs_decode_inode (cephfs_denc_t * d, cephfs_inode_t * out)
Definition at line 47 of file cephfs_layout.c.
References cephfs_decode_file_layout(), cephfs_denc_finish(), cephfs_denc_ok(), cephfs_denc_skip(), cephfs_denc_start(), cephfs_denc_u32(), cephfs_denc_u64(), cephfs_denc_u8(), cephfs_inode_t::ctime_nsec, cephfs_inode_t::ctime_sec, decode_utime(), cephfs_inode_t::gid, cephfs_inode_t::ino, cephfs_inode_t::layout, cephfs_inode_t::mode, cephfs_inode_t::mtime_nsec, cephfs_inode_t::mtime_sec, cephfs_inode_t::nlink, cephfs_inode_t::size, cephfs_inode_t::struct_v, and cephfs_inode_t::uid.
Referenced by decode_primary_body().
cephfs_decode_xattrs()
int cephfs_decode_xattrs (cephfs_denc_t * d, cephfs_xattr_t * out, uint32_t max, uint32_t * count, int * truncated)
Definition at line 245 of file cephfs_layout.c.
References cephfs_denc_ok(), cephfs_denc_str(), cephfs_denc_u32(), cephfs_xattr_t::name, cephfs_xattr_t::name_len, cephfs_xattr_t::val, and cephfs_xattr_t::val_len.
Referenced by decode_primary_body().
cephfs_frag_lookup_nway()
static int32_t cephfs_frag_lookup_nway (const cephfs_frag_split_t * splits, uint32_t nsplit, uint32_t f) static
Definition at line 148 of file cephfs_layout.c.
References cephfs_frag_split_t::nway.
Referenced by cephfs_decode_fragtree().
cephfs_frag_push_children()
static void cephfs_frag_push_children (uint32_t f, int32_t nb, uint32_t * stack, uint32_t * sp, int * trunc) static
Definition at line 176 of file cephfs_layout.c.
References c, CEPHFS_MAX_FRAGS, and frag_make_child().
Referenced by cephfs_decode_fragtree().
cephfs_read_frag_splits()
static int cephfs_read_frag_splits (cephfs_denc_t * d, cephfs_frag_split_t * splits, uint32_t * nsplit_out) static
Definition at line 117 of file cephfs_layout.c.
References cephfs_denc_ok(), cephfs_denc_u32(), CEPHFS_MAX_FRAGS, cephfs_frag_split_t::enc, cephfs_denc_t::err, and cephfs_frag_split_t::nway.
Referenced by cephfs_decode_fragtree().
decode_primary_body()
static int decode_primary_body (cephfs_denc_t * d, cephfs_dentry_t * out) static
Definition at line 282 of file cephfs_layout.c.
References cephfs_decode_fragtree(), cephfs_decode_inode(), cephfs_decode_xattrs(), cephfs_denc_ok(), cephfs_denc_str(), CEPHFS_DENTRY_PRIMARY, CEPHFS_MAX_FRAGS, CEPHFS_MAX_XATTRS, cephfs_mode_is_link(), cephfs_dentry_t::frag_enc, cephfs_dentry_t::frags_truncated, cephfs_dentry_t::inode, cephfs_dentry_t::kind, cephfs_inode_t::mode, cephfs_dentry_t::nfrags, cephfs_dentry_t::nxattrs, cephfs_dentry_t::symlink, cephfs_dentry_t::symlink_len, cephfs_dentry_t::xattrs, and cephfs_dentry_t::xattrs_truncated.
Referenced by cephfs_decode_dentry().
decode_utime()
static void decode_utime (cephfs_denc_t * d, int64_t * sec, uint32_t * nsec) static
Definition at line 17 of file cephfs_layout.c.
References cephfs_denc_u32(), and s.
Referenced by cephfs_decode_inode().
frag_bits()
static uint32_t frag_bits (uint32_t enc) static
Definition at line 86 of file cephfs_layout.c.
Referenced by frag_make_child().
frag_make_child()
static uint32_t frag_make_child (uint32_t enc, uint32_t nbits, uint32_t i) static
Definition at line 89 of file cephfs_layout.c.
References frag_bits(), and frag_value().
Referenced by cephfs_frag_push_children().
frag_value()
static uint32_t frag_value (uint32_t enc) static
Definition at line 87 of file cephfs_layout.c.
Referenced by frag_make_child().