nginx-xrootd: src/fs/backend/rados/cephfs_layout.h File Reference
cephfs_layout.h File Reference
#include "cephfs_denc.h"
Data Structures
struct cephfs_layout_t
struct cephfs_inode_t
struct cephfs_xattr_t
struct cephfs_dentry_t
Macros
#define CEPHFS_MAX_FRAGS 256
#define CEPHFS_MAX_XATTRS 64
#define CEPHFS_S_IFMT 0170000u
#define CEPHFS_S_IFDIR 0040000u
#define CEPHFS_S_IFREG 0100000u
#define CEPHFS_S_IFLNK 0120000u
Enumerations
enum cephfs_dentry_kind_t { CEPHFS_DENTRY_PRIMARY = 1 , CEPHFS_DENTRY_REMOTE = 2 }
Functions
static int cephfs_mode_is_dir (uint32_t m)
static int cephfs_mode_is_reg (uint32_t m)
static int cephfs_mode_is_link (uint32_t m)
int cephfs_decode_file_layout (cephfs_denc_t *d, cephfs_layout_t *out)
int cephfs_decode_inode (cephfs_denc_t *d, cephfs_inode_t *out)
int cephfs_decode_fragtree (cephfs_denc_t *d, uint32_t *leaves, uint32_t max, uint32_t *count, int *truncated)
int cephfs_decode_xattrs (cephfs_denc_t *d, cephfs_xattr_t *out, uint32_t max, uint32_t *count, int *truncated)
int cephfs_decode_dentry (const void *buf, size_t len, cephfs_dentry_t *out)
Macro Definition Documentation
CEPHFS_MAX_FRAGS
#define CEPHFS_MAX_FRAGS 256
Definition at line 43 of file cephfs_layout.h.
CEPHFS_MAX_XATTRS
#define CEPHFS_MAX_XATTRS 64
Definition at line 44 of file cephfs_layout.h.
CEPHFS_S_IFDIR
#define CEPHFS_S_IFDIR 0040000u
Definition at line 49 of file cephfs_layout.h.
CEPHFS_S_IFLNK
#define CEPHFS_S_IFLNK 0120000u
Definition at line 51 of file cephfs_layout.h.
CEPHFS_S_IFMT
#define CEPHFS_S_IFMT 0170000u
Definition at line 48 of file cephfs_layout.h.
CEPHFS_S_IFREG
#define CEPHFS_S_IFREG 0100000u
Definition at line 50 of file cephfs_layout.h.
Enumeration Type Documentation
cephfs_dentry_kind_t
enum cephfs_dentry_kind_t
Enumerator
CEPHFS_DENTRY_PRIMARY
CEPHFS_DENTRY_REMOTE
Definition at line 92 of file cephfs_layout.h.
Function Documentation
cephfs_decode_dentry()
int cephfs_decode_dentry (const void * buf, size_t len, cephfs_dentry_t * out)
Definition at line 306 of file cephfs_layout.c.
References cephfs_denc_finish(), cephfs_denc_init(), cephfs_denc_ok(), cephfs_denc_start(), cephfs_denc_str(), cephfs_denc_u64(), cephfs_denc_u8(), CEPHFS_DENTRY_REMOTE, decode_primary_body(), cephfs_dentry_t::kind, cephfs_dentry_t::remote_d_type, cephfs_dentry_t::remote_ino, and cephfs_denc_frame_t::struct_v.
cephfs_decode_file_layout()
int cephfs_decode_file_layout (cephfs_denc_t * d, cephfs_layout_t * out)
Definition at line 26 of file cephfs_layout.c.
References cephfs_denc_finish(), cephfs_denc_ok(), cephfs_denc_s64(), cephfs_denc_start(), cephfs_denc_u32(), cephfs_layout_t::object_size, cephfs_layout_t::pool_id, cephfs_layout_t::stripe_count, and cephfs_layout_t::stripe_unit.
Referenced by cephfs_decode_inode().
cephfs_decode_fragtree()
int cephfs_decode_fragtree (cephfs_denc_t * d, uint32_t * leaves, uint32_t max, uint32_t * count, int * truncated)
Definition at line 212 of file cephfs_layout.c.
References cephfs_denc_ok(), cephfs_frag_lookup_nway(), cephfs_frag_push_children(), CEPHFS_MAX_FRAGS, and cephfs_read_frag_splits().
Referenced by decode_primary_body().
cephfs_decode_inode()
int cephfs_decode_inode (cephfs_denc_t * d, cephfs_inode_t * out)
Definition at line 47 of file cephfs_layout.c.
References cephfs_decode_file_layout(), cephfs_denc_finish(), cephfs_denc_ok(), cephfs_denc_skip(), cephfs_denc_start(), cephfs_denc_u32(), cephfs_denc_u64(), cephfs_denc_u8(), cephfs_inode_t::ctime_nsec, cephfs_inode_t::ctime_sec, decode_utime(), cephfs_inode_t::gid, cephfs_inode_t::ino, cephfs_inode_t::layout, cephfs_inode_t::mode, cephfs_inode_t::mtime_nsec, cephfs_inode_t::mtime_sec, cephfs_inode_t::nlink, cephfs_inode_t::size, cephfs_inode_t::struct_v, and cephfs_inode_t::uid.
Referenced by decode_primary_body().
cephfs_decode_xattrs()
int cephfs_decode_xattrs (cephfs_denc_t * d, cephfs_xattr_t * out, uint32_t max, uint32_t * count, int * truncated)
Definition at line 245 of file cephfs_layout.c.
References cephfs_denc_ok(), cephfs_denc_str(), cephfs_denc_u32(), cephfs_xattr_t::name, cephfs_xattr_t::name_len, cephfs_xattr_t::val, and cephfs_xattr_t::val_len.
Referenced by decode_primary_body().
cephfs_mode_is_dir()
static int cephfs_mode_is_dir (uint32_t m) inline static
Definition at line 53 of file cephfs_layout.h.
References CEPHFS_S_IFDIR, and CEPHFS_S_IFMT.
cephfs_mode_is_link()
static int cephfs_mode_is_link (uint32_t m) inline static
Definition at line 55 of file cephfs_layout.h.
References CEPHFS_S_IFLNK, and CEPHFS_S_IFMT.
Referenced by decode_primary_body().
cephfs_mode_is_reg()
static int cephfs_mode_is_reg (uint32_t m) inline static
Definition at line 54 of file cephfs_layout.h.
References CEPHFS_S_IFMT, and CEPHFS_S_IFREG.