nginx-xrootd: src/fs/backend/rados/cephfs_denc.c File Reference
cephfs_denc.c File Reference
#include "cephfs_denc.h"
#include <string.h>
Functions
void cephfs_denc_init (cephfs_denc_t *d, const void *buf, size_t len)
int cephfs_denc_ok (const cephfs_denc_t *d)
size_t cephfs_denc_remaining (const cephfs_denc_t *d)
static int have (cephfs_denc_t *d, size_t n)
uint8_t cephfs_denc_u8 (cephfs_denc_t *d)
uint16_t cephfs_denc_u16 (cephfs_denc_t *d)
uint32_t cephfs_denc_u32 (cephfs_denc_t *d)
uint64_t cephfs_denc_u64 (cephfs_denc_t *d)
int64_t cephfs_denc_s64 (cephfs_denc_t *d)
const uint8_t * cephfs_denc_bytes (cephfs_denc_t *d, size_t n)
void cephfs_denc_skip (cephfs_denc_t *d, size_t n)
int cephfs_denc_str (cephfs_denc_t *d, const char **s, uint32_t *len)
uint8_t cephfs_denc_start (cephfs_denc_t *d, cephfs_denc_frame_t *f)
void cephfs_denc_finish (cephfs_denc_t *d, const cephfs_denc_frame_t *f)
Function Documentation
cephfs_denc_bytes()
const uint8_t * cephfs_denc_bytes (cephfs_denc_t * d, size_t n)
Definition at line 115 of file cephfs_denc.c.
References have(), and cephfs_denc_t::p.
Referenced by cephfs_denc_str().
cephfs_denc_finish()
void cephfs_denc_finish (cephfs_denc_t * d, const cephfs_denc_frame_t * f)
Definition at line 179 of file cephfs_denc.c.
References cephfs_denc_t::err, cephfs_denc_t::p, and cephfs_denc_frame_t::payload_end.
Referenced by cephfs_decode_dentry(), cephfs_decode_file_layout(), and cephfs_decode_inode().
cephfs_denc_init()
void cephfs_denc_init (cephfs_denc_t * d, const void * buf, size_t len)
Definition at line 15 of file cephfs_denc.c.
References cephfs_denc_t::end, cephfs_denc_t::err, and cephfs_denc_t::p.
Referenced by cephfs_decode_dentry().
cephfs_denc_ok()
int cephfs_denc_ok (const cephfs_denc_t * d)
Definition at line 23 of file cephfs_denc.c.
References cephfs_denc_t::err.
Referenced by cephfs_decode_dentry(), cephfs_decode_file_layout(), cephfs_decode_fragtree(), cephfs_decode_inode(), cephfs_decode_xattrs(), cephfs_denc_start(), cephfs_denc_str(), and decode_primary_body().
cephfs_denc_remaining()
size_t cephfs_denc_remaining (const cephfs_denc_t * d)
Definition at line 29 of file cephfs_denc.c.
References cephfs_denc_t::end, cephfs_denc_t::err, and cephfs_denc_t::p.
cephfs_denc_s64()
int64_t cephfs_denc_s64 (cephfs_denc_t * d)
Definition at line 109 of file cephfs_denc.c.
References cephfs_denc_u64().
Referenced by cephfs_decode_file_layout().
cephfs_denc_skip()
void cephfs_denc_skip (cephfs_denc_t * d, size_t n)
Definition at line 128 of file cephfs_denc.c.
References have(), and cephfs_denc_t::p.
Referenced by cephfs_decode_inode().
cephfs_denc_start()
uint8_t cephfs_denc_start (cephfs_denc_t * d, cephfs_denc_frame_t * f)
Definition at line 156 of file cephfs_denc.c.
References cephfs_denc_ok(), cephfs_denc_u32(), cephfs_denc_u8(), cephfs_denc_t::end, cephfs_denc_t::err, cephfs_denc_t::p, cephfs_denc_frame_t::payload_end, cephfs_denc_frame_t::struct_compat, and cephfs_denc_frame_t::struct_v.
Referenced by cephfs_decode_dentry(), cephfs_decode_file_layout(), and cephfs_decode_inode().
cephfs_denc_str()
int cephfs_denc_str (cephfs_denc_t * d, const char ** s, uint32_t * len)
Definition at line 136 of file cephfs_denc.c.
References cephfs_denc_bytes(), cephfs_denc_ok(), cephfs_denc_u32(), and s.
Referenced by cephfs_decode_dentry(), cephfs_decode_xattrs(), and decode_primary_body().
cephfs_denc_u16()
uint16_t cephfs_denc_u16 (cephfs_denc_t * d)
Definition at line 62 of file cephfs_denc.c.
References have(), and cephfs_denc_t::p.
cephfs_denc_u32()
uint32_t cephfs_denc_u32 (cephfs_denc_t * d)
Definition at line 76 of file cephfs_denc.c.
References have(), and cephfs_denc_t::p.
Referenced by cephfs_decode_file_layout(), cephfs_decode_fragtree(), cephfs_decode_inode(), cephfs_decode_xattrs(), cephfs_denc_start(), cephfs_denc_str(), and decode_utime().
cephfs_denc_u64()
uint64_t cephfs_denc_u64 (cephfs_denc_t * d)
Definition at line 92 of file cephfs_denc.c.
References have(), and cephfs_denc_t::p.
Referenced by cephfs_decode_dentry(), cephfs_decode_inode(), and cephfs_denc_s64().
cephfs_denc_u8()
uint8_t cephfs_denc_u8 (cephfs_denc_t * d)
Definition at line 53 of file cephfs_denc.c.
References have(), and cephfs_denc_t::p.
Referenced by cephfs_decode_dentry(), cephfs_decode_inode(), and cephfs_denc_start().
have()
static int have (cephfs_denc_t * d, size_t n) static
Definition at line 40 of file cephfs_denc.c.
References cephfs_denc_t::end, cephfs_denc_t::err, and cephfs_denc_t::p.
Referenced by brix_ckpxeq_body_extra(), brix_cred_autorefresh(), cephfs_denc_bytes(), cephfs_denc_skip(), cephfs_denc_u16(), cephfs_denc_u32(), cephfs_denc_u64(), cephfs_denc_u8(), and web_get_range().