nginx-xrootd: src/auth/gsi/cert_response.c File Reference
cert_response.c File Reference
#include "gsi_internal.h"
#include "gsi_core.h"
#include "keypool.h"
#include "core/compat/alloc_guard.h"
Data Structures
struct gsi_cert_chunks_t
Functions
static uint32_t gsi_certreq_version (const u_char *payload, size_t plen)
static uint32_t gsi_certreq_clnt_opts (const u_char *payload, size_t plen)
static int gsi_use_signed_dh (ngx_uint_t policy, uint32_t client_version)
static void gsi_build_cipher_alg_list (const ngx_stream_brix_srv_conf_t *conf, char *out, size_t outsz)
static int gsi_record_handshake_opts (brix_ctx_t *ctx, ngx_connection_t *c, const ngx_stream_brix_srv_conf_t *conf)
static ngx_int_t gsi_build_dh_public (brix_ctx_t *ctx, ngx_connection_t *c, const ngx_stream_brix_srv_conf_t *conf, u_char **puk_out, size_t *puk_len_out)
static ngx_int_t gsi_select_dh_public_bucket (ngx_connection_t *c, const ngx_stream_brix_srv_conf_t *conf, int signed_dh, gsi_cert_chunks_t *ch)
static void gsi_sign_client_rtag (brix_ctx_t *ctx, ngx_connection_t *c, const ngx_stream_brix_srv_conf_t *conf, u_char **rtag_out, size_t *rtag_len_out)
static ngx_int_t gsi_build_main_container (ngx_connection_t *c, const u_char *signed_rtag, size_t signed_rtag_len, u_char **buf_out, size_t *len_out)
static ngx_int_t gsi_frame_cert_response (brix_ctx_t *ctx, ngx_connection_t *c, const gsi_cert_chunks_t *ch)
ngx_int_t brix_gsi_send_cert (brix_ctx_t *ctx, ngx_connection_t *c)
Function Documentation
brix_gsi_send_cert()
ngx_int_t brix_gsi_send_cert (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 509 of file cert_response.c.
References c, gsi_cert_chunks_t::calg_len, gsi_cert_chunks_t::cert_len, gsi_cert_chunks_t::cert_pem, gsi_cert_chunks_t::cipher_alg, gsi_build_cipher_alg_list(), gsi_build_dh_public(), gsi_build_main_container(), gsi_frame_cert_response(), gsi_record_handshake_opts(), gsi_select_dh_public_bucket(), gsi_sign_client_rtag(), gsi_cert_chunks_t::main_buf, gsi_cert_chunks_t::main_len, gsi_cert_chunks_t::malg_len, gsi_cert_chunks_t::md_alg, ngx_stream_brix_module, gsi_cert_chunks_t::pub_data, gsi_cert_chunks_t::pub_len, gsi_cert_chunks_t::puk_len, and brix_ctx_t::session.
Referenced by gsi_auth_step_certreq().
gsi_build_cipher_alg_list()
static void gsi_build_cipher_alg_list (const ngx_stream_brix_srv_conf_t * conf, char * out, size_t outsz) static
Definition at line 102 of file cert_response.c.
References brix_gsi_cipher_default_list(), brix_gsi_cipher_lookup(), name, and ngx_memcpy.
Referenced by brix_gsi_send_cert().
gsi_build_dh_public()
static ngx_int_t gsi_build_dh_public (brix_ctx_t * ctx, ngx_connection_t * c, const ngx_stream_brix_srv_conf_t * conf, u_char ** puk_out, size_t * puk_len_out) static
Definition at line 211 of file cert_response.c.
References brix_gsi_dh_keygen(), brix_gsi_keypool_pop(), BRIX_PALLOC_OR_RETURN, c, brix_ctx_gsi_t::dh_key, brix_ctx_t::gsi, and ngx_memcpy.
Referenced by brix_gsi_send_cert().
gsi_build_main_container()
static ngx_int_t gsi_build_main_container (ngx_connection_t * c, const u_char * signed_rtag, size_t signed_rtag_len, u_char ** buf_out, size_t * len_out) static
Definition at line 376 of file cert_response.c.
References BRIX_PALLOC_OR_RETURN, c, kXGS_cert, kXRS_none, kXRS_signed_rtag, and ngx_memcpy.
Referenced by brix_gsi_send_cert().
gsi_certreq_clnt_opts()
static uint32_t gsi_certreq_clnt_opts (const u_char * payload, size_t plen) static
Definition at line 54 of file cert_response.c.
References gsi_find_bucket(), kXRS_clnt_opts, and ngx_memcpy.
Referenced by gsi_record_handshake_opts().
gsi_certreq_version()
static uint32_t gsi_certreq_version (const u_char * payload, size_t plen) static
Definition at line 25 of file cert_response.c.
References gsi_find_bucket(), kXRS_version, and ngx_memcpy.
Referenced by gsi_record_handshake_opts().
gsi_frame_cert_response()
static ngx_int_t gsi_frame_cert_response (brix_ctx_t * ctx, ngx_connection_t * c, const gsi_cert_chunks_t * ch) static
Definition at line 428 of file cert_response.c.
References brix_build_resp_hdr(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), c, gsi_cert_chunks_t::calg_len, gsi_cert_chunks_t::cert_len, gsi_cert_chunks_t::cert_pem, gsi_cert_chunks_t::cipher_alg, brix_ctx_recv_t::cur_streamid, kXGS_cert, kXR_authmore, kXRS_cipher_alg, kXRS_main, kXRS_md_alg, kXRS_none, kXRS_x509, gsi_cert_chunks_t::main_buf, gsi_cert_chunks_t::main_len, gsi_cert_chunks_t::malg_len, gsi_cert_chunks_t::md_alg, ngx_memcpy, gsi_cert_chunks_t::pub_data, gsi_cert_chunks_t::pub_len, gsi_cert_chunks_t::pub_type, gsi_cert_chunks_t::puk_len, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_gsi_send_cert().
gsi_record_handshake_opts()
static int gsi_record_handshake_opts (brix_ctx_t * ctx, ngx_connection_t * c, const ngx_stream_brix_srv_conf_t * conf) static
Definition at line 173 of file cert_response.c.
References c, brix_ctx_gsi_t::clnt_opts, brix_ctx_recv_t::cur_dlen, brix_ctx_t::gsi, gsi_certreq_clnt_opts(), gsi_certreq_version(), gsi_use_signed_dh(), brix_ctx_recv_t::payload, brix_ctx_t::recv, and brix_ctx_gsi_t::signed_dh.
Referenced by brix_gsi_send_cert().
gsi_select_dh_public_bucket()
static ngx_int_t gsi_select_dh_public_bucket (ngx_connection_t * c, const ngx_stream_brix_srv_conf_t * conf, int signed_dh, gsi_cert_chunks_t * ch) static
Definition at line 286 of file cert_response.c.
References brix_gsi_rsa_encrypt_private(), c, kXRS_cipher, kXRS_puk, gsi_cert_chunks_t::pub_data, gsi_cert_chunks_t::pub_len, and gsi_cert_chunks_t::pub_type.
Referenced by brix_gsi_send_cert().
gsi_sign_client_rtag()
static void gsi_sign_client_rtag (brix_ctx_t * ctx, ngx_connection_t * c, const ngx_stream_brix_srv_conf_t * conf, u_char ** rtag_out, size_t * rtag_len_out) static
Definition at line 323 of file cert_response.c.
References c, brix_ctx_recv_t::cur_dlen, gsi_find_bucket(), kXRS_main, kXRS_rtag, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by brix_gsi_send_cert().
gsi_use_signed_dh()
static int gsi_use_signed_dh (ngx_uint_t policy, uint32_t client_version) static
Definition at line 83 of file cert_response.c.
References BRIX_GSI_SDH_AUTO, BRIX_GSI_SDH_REQUIRE, and BRIX_GSI_VERS_DHSIGNED.
Referenced by gsi_record_handshake_opts().