nginx-xrootd: src/protocols/root/query/checksum_ckscan_async.c File Reference
checksum_ckscan_async.c File Reference
#include "query_internal.h"
#include "protocols/root/response/response.h"
#include "core/aio/aio.h"
#include "core/compat/checksum.h"
#include "fs/path/beneath.h"
#include <dirent.h>
#include <sys/stat.h>
Functions
void brix_ckscan_aio_thread (void *data, ngx_log_t *log)
void brix_ckscan_aio_done (ngx_event_t *ev)
Function Documentation
brix_ckscan_aio_done()
void brix_ckscan_aio_done (ngx_event_t * ev)
Definition at line 88 of file checksum_ckscan_async.c.
References brix_aio_restore_request(), brix_aio_resume(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_QUERY_CKSCAN, brix_send_error(), brix_send_ok(), c, brix_ckscan_aio_t::c, brix_ckscan_aio_t::ctx, brix_ckscan_aio_t::error_code, brix_ckscan_aio_t::error_msg, brix_ckscan_aio_t::resp, brix_ckscan_aio_t::resp_len, brix_ckscan_aio_t::scan_logical, and brix_ckscan_aio_t::streamid.
Referenced by brix_query_ckscan().
brix_ckscan_aio_thread()
void brix_ckscan_aio_thread (void * data, ngx_log_t * log)
Definition at line 33 of file checksum_ckscan_async.c.
References brix_ckscan_aio_t::algo, BRIX_CKSCAN_INIT_CAP, brix_ckscan_run(), brix_ckscan_aio_t::error_code, brix_ckscan_aio_t::error_msg, kXR_NoMemory, log, brix_ckscan_aio_t::max_depth, brix_ckscan_aio_t::max_files, brix_ckscan_aio_t::resp, brix_ckscan_aio_t::resp_len, brix_ckscan_aio_t::rootfd, and brix_ckscan_aio_t::scan_logical.
Referenced by brix_query_ckscan().