nginx-xrootd: src/core/compat/checksum.h File Reference
checksum.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <openssl/evp.h>
#include <stdint.h>
#include "fs/backend/sd.h"
Enumerations
enum brix_checksum_alg_t {
BRIX_CHECKSUM_ADLER32 = 0 , BRIX_CHECKSUM_CRC32 , BRIX_CHECKSUM_CRC32C , BRIX_CHECKSUM_MD5 ,
BRIX_CHECKSUM_SHA1 , BRIX_CHECKSUM_SHA256 , BRIX_CHECKSUM_CRC64 , BRIX_CHECKSUM_CRC64NVME ,
BRIX_CHECKSUM_ZCRC32
}
Functions
ngx_int_t brix_checksum_parse (const char *name, size_t len, brix_checksum_alg_t *alg, char *normalized, size_t normalized_sz)
const char * brix_checksum_name (brix_checksum_alg_t alg)
ngx_flag_t brix_checksum_is_u32 (brix_checksum_alg_t alg)
ngx_flag_t brix_checksum_is_u64 (brix_checksum_alg_t alg)
ngx_int_t brix_checksum_u32_fd (brix_checksum_alg_t alg, int fd, const char *path, ngx_log_t *log, uint32_t *out)
ngx_int_t brix_checksum_u64_fd (brix_checksum_alg_t alg, int fd, const char *path, ngx_log_t *log, uint64_t *out)
ngx_int_t brix_checksum_digest_fd (brix_checksum_alg_t alg, int fd, const char *path, ngx_log_t *log, unsigned char *out, unsigned int *outlen)
ngx_int_t brix_checksum_hex_fd (brix_checksum_alg_t alg, int fd, const char *path, ngx_log_t *log, char *hex, size_t hexsz)
ngx_int_t brix_checksum_hex_obj (brix_checksum_alg_t alg, brix_sd_obj_t *obj, const char *path, ngx_log_t *log, char *hex, size_t hexsz)
ngx_int_t brix_checksum_hex_name_fd (const char *name, int fd, const char *path, ngx_log_t *log, char *hex, size_t hexsz, char *normalized, size_t normalized_sz)
void brix_checksum_hex_encode (const unsigned char *digest, unsigned int digest_len, char *hex)
Enumeration Type Documentation
brix_checksum_alg_t
enum brix_checksum_alg_t
Enumerator
BRIX_CHECKSUM_ADLER32
BRIX_CHECKSUM_CRC32
BRIX_CHECKSUM_CRC32C
BRIX_CHECKSUM_MD5
BRIX_CHECKSUM_SHA1
BRIX_CHECKSUM_SHA256
BRIX_CHECKSUM_CRC64
BRIX_CHECKSUM_CRC64NVME
BRIX_CHECKSUM_ZCRC32
Definition at line 11 of file checksum.h.
Function Documentation
brix_checksum_digest_fd()
ngx_int_t brix_checksum_digest_fd (brix_checksum_alg_t alg, int fd, const char * path, ngx_log_t * log, unsigned char * out, unsigned int * outlen)
Definition at line 293 of file checksum.c.
References alg, brix_checksum_is_u32(), brix_checksum_is_u64(), brix_checksum_log_read_error(), brix_checksum_name(), brix_cksum_digest_fd(), and log.
Referenced by brix_checksum_hex_fd(), and brix_query_digest_fd().
brix_checksum_hex_encode()
void brix_checksum_hex_encode (const unsigned char * digest, unsigned int digest_len, char * hex)
Definition at line 320 of file checksum.c.
References brix_hex_encode(), and hex().
Referenced by brix_checksum_hex_fd(), and brix_checksum_hex_obj().
brix_checksum_hex_fd()
ngx_int_t brix_checksum_hex_fd (brix_checksum_alg_t alg, int fd, const char * path, ngx_log_t * log, char * hex, size_t hexsz)
Definition at line 339 of file checksum.c.
References alg, brix_checksum_digest_fd(), brix_checksum_hex_encode(), brix_checksum_is_u32(), brix_checksum_is_u64(), brix_checksum_u32_fd(), brix_checksum_u64_fd(), hex(), and log.
Referenced by brix_checksum_hex_name_fd(), and integrity_compute_hex().
brix_checksum_hex_name_fd()
ngx_int_t brix_checksum_hex_name_fd (const char * name, int fd, const char * path, ngx_log_t * log, char * hex, size_t hexsz, char * normalized, size_t normalized_sz)
Definition at line 460 of file checksum.c.
References alg, brix_checksum_hex_fd(), brix_checksum_parse(), hex(), log, and name.
Referenced by brix_cache_verify_cvmfs_cas(), brix_cache_verify_part(), cache_fill_verify_origin(), ckscan_walk_file(), and tpc_verify_source_checksum().
brix_checksum_hex_obj()
ngx_int_t brix_checksum_hex_obj (brix_checksum_alg_t alg, brix_sd_obj_t * obj, const char * path, ngx_log_t * log, char * hex, size_t hexsz)
Definition at line 402 of file checksum.c.
References alg, brix_checksum_hex_encode(), brix_checksum_is_u32(), brix_checksum_is_u64(), brix_checksum_log_read_error(), brix_checksum_name(), brix_cksum_digest_obj(), brix_cksum_u32_obj(), brix_cksum_u64_obj(), hex(), and log.
Referenced by brix_cache_commit_staged(), and integrity_compute_hex().
brix_checksum_is_u32()
ngx_flag_t brix_checksum_is_u32 (brix_checksum_alg_t alg)
Definition at line 94 of file checksum.c.
References alg, BRIX_CHECKSUM_ADLER32, BRIX_CHECKSUM_CRC32, BRIX_CHECKSUM_CRC32C, and BRIX_CHECKSUM_ZCRC32.
Referenced by brix_checksum_digest_fd(), brix_checksum_hex_fd(), brix_checksum_hex_obj(), and brix_checksum_u32_fd().
brix_checksum_is_u64()
ngx_flag_t brix_checksum_is_u64 (brix_checksum_alg_t alg)
Definition at line 78 of file checksum.c.
References alg, BRIX_CHECKSUM_CRC64, and BRIX_CHECKSUM_CRC64NVME.
Referenced by brix_checksum_digest_fd(), brix_checksum_hex_fd(), brix_checksum_hex_obj(), and brix_checksum_u64_fd().
brix_checksum_name()
const char * brix_checksum_name (brix_checksum_alg_t alg)
Definition at line 42 of file checksum.c.
References alg, BRIX_CHECKSUM_ADLER32, BRIX_CHECKSUM_CRC32, BRIX_CHECKSUM_CRC32C, BRIX_CHECKSUM_CRC64, BRIX_CHECKSUM_CRC64NVME, BRIX_CHECKSUM_MD5, BRIX_CHECKSUM_SHA1, BRIX_CHECKSUM_SHA256, and BRIX_CHECKSUM_ZCRC32.
Referenced by brix_checksum_digest_fd(), brix_checksum_hex_obj(), brix_checksum_parse(), brix_checksum_u32_fd(), and brix_checksum_u64_fd().
brix_checksum_parse()
ngx_int_t brix_checksum_parse (const char * name, size_t len, brix_checksum_alg_t * alg, char * normalized, size_t normalized_sz)
Definition at line 187 of file checksum.c.
References alg, brix_checksum_lookup_alg(), brix_checksum_name(), brix_checksum_normalize_name(), and name.
Referenced by brix_cache_commit_staged(), brix_checksum_hex_name_fd(), brix_ckscan_algorithm_supported(), brix_ckscan_select_payload(), brix_conf_set_cache_verify_digest(), brix_dirlist_parse_algorithm(), brix_integrity_get_fd(), brix_query_parse_algorithm(), and xrdhttp_add_checksum_header().
brix_checksum_u32_fd()
ngx_int_t brix_checksum_u32_fd (brix_checksum_alg_t alg, int fd, const char * path, ngx_log_t * log, uint32_t * out)
Definition at line 254 of file checksum.c.
References alg, brix_checksum_is_u32(), brix_checksum_log_read_error(), brix_checksum_name(), brix_cksum_u32_fd(), and log.
Referenced by brix_checksum_hex_fd(), brix_crc32c_file(), brix_query_adler32_fd(), and brix_query_crc32_fd().
brix_checksum_u64_fd()
ngx_int_t brix_checksum_u64_fd (brix_checksum_alg_t alg, int fd, const char * path, ngx_log_t * log, uint64_t * out)
Definition at line 279 of file checksum.c.
References alg, brix_checksum_is_u64(), brix_checksum_log_read_error(), brix_checksum_name(), brix_cksum_u64_fd(), and log.
Referenced by brix_checksum_hex_fd().