nginx-xrootd: src/protocols/root/query/checksum_ckscan_common.c File Reference
checksum_ckscan_common.c File Reference
#include "query_internal.h"
#include "protocols/root/response/response.h"
#include "core/aio/aio.h"
#include "core/compat/checksum.h"
#include "fs/vfs/vfs.h"
#include <dirent.h>
#include <sys/stat.h>
Data Structures
struct ckscan_walk_ctx_t
Functions
int brix_ckscan_append (u_char **buf, size_t *cap, size_t *used, const char *algo, const char *hex, const char *logical)
static ngx_int_t ckscan_walk_file (void *cookie, const char *logical, const brix_vfs_stat_t *st, int fd)
ngx_int_t brix_ckscan_run (ngx_log_t *log, int rootfd, const char *logical, const char *algo, u_char **buf, size_t *cap, size_t *used, ngx_uint_t max_depth, ngx_uint_t max_files, uint16_t *err_code, char *err_msg, size_t err_sz)
Function Documentation
brix_ckscan_append()
int brix_ckscan_append (u_char ** buf, size_t * cap, size_t * used, const char * algo, const char * hex, const char * logical)
Definition at line 21 of file checksum_ckscan_common.c.
References BRIX_MAX_PATH, hex(), and ngx_memcpy.
Referenced by ckscan_walk_file().
brix_ckscan_run()
ngx_int_t brix_ckscan_run (ngx_log_t * log, int rootfd, const char * logical, const char * algo, u_char ** buf, size_t * cap, size_t * used, ngx_uint_t max_depth, ngx_uint_t max_files, uint16_t * err_code, char * err_msg, size_t err_sz)
Definition at line 125 of file checksum_ckscan_common.c.
References ckscan_walk_ctx_t::algo, brix_vfs_walk(), BRIX_VFS_WALK_FILE, BRIX_VFS_WALK_NONE, BRIX_VFS_WALK_OTHER, ckscan_walk_ctx_t::buf, ckscan_walk_ctx_t::cap, ckscan_walk_file(), kXR_ArgInvalid, kXR_IOError, kXR_NoMemory, kXR_NotFound, log, ckscan_walk_ctx_t::log, brix_vfs_walk_opts_t::max_depth, brix_vfs_walk_opts_t::max_files, ckscan_walk_ctx_t::oom, brix_vfs_walk_opts_t::open_files, and ckscan_walk_ctx_t::used.
Referenced by brix_ckscan_aio_thread(), and brix_ckscan_sync().
ckscan_walk_file()
static ngx_int_t ckscan_walk_file (void * cookie, const char * logical, const brix_vfs_stat_t * st, int fd) static
Definition at line 98 of file checksum_ckscan_common.c.
References ckscan_walk_ctx_t::algo, brix_checksum_hex_name_fd(), brix_ckscan_append(), ckscan_walk_ctx_t::buf, ckscan_walk_ctx_t::cap, hex(), ckscan_walk_ctx_t::log, ckscan_walk_ctx_t::oom, and ckscan_walk_ctx_t::used.
Referenced by brix_ckscan_run().