nginx-xrootd: src/core/compat/checksum_core.c File Reference
checksum_core.c File Reference
#include "checksum_core.h"
#include "fs/backend/sd.h"
#include "crc32c.h"
#include "crc64.h"
#include <errno.h>
#include <unistd.h>
#include <zlib.h>
#include <openssl/evp.h>
Macros
#define BRIX_CK_BUFSZ (64 * 1024)
Functions
static int u32_kind_ok (int kind)
static uLong u32_seed (int kind)
static void u32_update (int kind, const unsigned char *buf, size_t n, uLong *zcrc, uint32_t *crc32c)
static size_t range_want (off_t len, off_t remaining, size_t bufsz)
int brix_cksum_u32_obj_range (int kind, brix_sd_obj_t *obj, off_t start, off_t len, uint32_t *out)
int brix_cksum_u32_obj (int kind, brix_sd_obj_t *obj, uint32_t *out)
int brix_cksum_u32_fd (int kind, int fd, uint32_t *out)
int brix_cksum_u64_obj_range (int kind, brix_sd_obj_t *obj, off_t start, off_t len, uint64_t *out)
int brix_cksum_u64_obj (int kind, brix_sd_obj_t *obj, uint64_t *out)
int brix_cksum_u64_fd (int kind, int fd, uint64_t *out)
static const EVP_MD * md_for (int kind)
static int digest_drive (EVP_MD_CTX *ctx, const EVP_MD *md, brix_sd_obj_t *obj, off_t start, off_t len, unsigned char *out, unsigned int *outlen)
int brix_cksum_digest_obj_range (int kind, brix_sd_obj_t *obj, off_t start, off_t len, unsigned char *out, unsigned int *outlen)
int brix_cksum_digest_obj (int kind, brix_sd_obj_t *obj, unsigned char *out, unsigned int *outlen)
int brix_cksum_digest_fd (int kind, int fd, unsigned char *out, unsigned int *outlen)
Macro Definition Documentation
BRIX_CK_BUFSZ
#define BRIX_CK_BUFSZ (64 * 1024)
Definition at line 26 of file checksum_core.c.
Function Documentation
brix_cksum_digest_fd()
int brix_cksum_digest_fd (int kind, int fd, unsigned char * out, unsigned int * outlen)
Definition at line 322 of file checksum_core.c.
References brix_cksum_digest_obj(), and brix_sd_posix_wrap().
Referenced by brix_checksum_digest_fd(), and brix_cksum_fd().
brix_cksum_digest_obj()
int brix_cksum_digest_obj (int kind, brix_sd_obj_t * obj, unsigned char * out, unsigned int * outlen)
Definition at line 315 of file checksum_core.c.
References brix_cksum_digest_obj_range().
Referenced by brix_checksum_hex_obj(), and brix_cksum_digest_fd().
brix_cksum_digest_obj_range()
int brix_cksum_digest_obj_range (int kind, brix_sd_obj_t * obj, off_t start, off_t len, unsigned char * out, unsigned int * outlen)
Definition at line 294 of file checksum_core.c.
References digest_drive(), and md_for().
Referenced by brix_cksum_digest_obj(), and brix_ftp_ev_cmd_cksm().
brix_cksum_u32_fd()
int brix_cksum_u32_fd (int kind, int fd, uint32_t * out)
Definition at line 177 of file checksum_core.c.
References brix_cksum_u32_obj(), and brix_sd_posix_wrap().
Referenced by brix_checksum_u32_fd(), and brix_cksum_fd().
brix_cksum_u32_obj()
int brix_cksum_u32_obj (int kind, brix_sd_obj_t * obj, uint32_t * out)
Definition at line 171 of file checksum_core.c.
References brix_cksum_u32_obj_range().
Referenced by brix_checksum_hex_obj(), brix_cksum_u32_fd(), and brix_vfs_wverify_check().
brix_cksum_u32_obj_range()
int brix_cksum_u32_obj_range (int kind, brix_sd_obj_t * obj, off_t start, off_t len, uint32_t * out)
Definition at line 124 of file checksum_core.c.
References BRIX_CK_BUFSZ, BRIX_CK_CRC32, BRIX_CK_CRC32C, BRIX_CK_ZCRC32, range_want(), u32_kind_ok(), u32_seed(), and u32_update().
Referenced by brix_cksum_u32_obj(), and brix_ftp_ev_cmd_cksm().
brix_cksum_u64_fd()
int brix_cksum_u64_fd (int kind, int fd, uint64_t * out)
Definition at line 238 of file checksum_core.c.
References brix_cksum_u64_obj(), and brix_sd_posix_wrap().
Referenced by brix_checksum_u64_fd(), and brix_cksum_fd().
brix_cksum_u64_obj()
int brix_cksum_u64_obj (int kind, brix_sd_obj_t * obj, uint64_t * out)
Definition at line 232 of file checksum_core.c.
References brix_cksum_u64_obj_range().
Referenced by brix_checksum_hex_obj(), and brix_cksum_u64_fd().
brix_cksum_u64_obj_range()
int brix_cksum_u64_obj_range (int kind, brix_sd_obj_t * obj, off_t start, off_t len, uint64_t * out)
Definition at line 186 of file checksum_core.c.
References BRIX_CK_BUFSZ, BRIX_CK_CRC64, BRIX_CK_CRC64NVME, brix_crc64_extend(), BRIX_CRC64_NVME, BRIX_CRC64_XZ, and range_want().
Referenced by brix_cksum_u64_obj().
digest_drive()
static int digest_drive (EVP_MD_CTX * ctx, const EVP_MD * md, brix_sd_obj_t * obj, off_t start, off_t len, unsigned char * out, unsigned int * outlen) static
Definition at line 260 of file checksum_core.c.
References BRIX_CK_BUFSZ, and range_want().
Referenced by brix_cksum_digest_obj_range().
md_for()
static const EVP_MD * md_for (int kind) static
Definition at line 247 of file checksum_core.c.
References BRIX_CK_MD5, BRIX_CK_SHA1, and BRIX_CK_SHA256.
Referenced by brix_cksum_digest_obj_range().
range_want()
static size_t range_want (off_t len, off_t remaining, size_t bufsz) static
Definition at line 112 of file checksum_core.c.
Referenced by brix_cksum_u32_obj_range(), brix_cksum_u64_obj_range(), and digest_drive().
u32_kind_ok()
static int u32_kind_ok (int kind) static
Definition at line 41 of file checksum_core.c.
References BRIX_CK_ADLER32, BRIX_CK_CRC32, and BRIX_CK_CRC32C.
Referenced by brix_cksum_u32_obj_range().
u32_seed()
static uLong u32_seed (int kind) static
Definition at line 62 of file checksum_core.c.
References BRIX_CK_ADLER32, and BRIX_CK_CRC32.
Referenced by brix_cksum_u32_obj_range().
u32_update()
static void u32_update (int kind, const unsigned char * buf, size_t n, uLong * zcrc, uint32_t * crc32c) static
Definition at line 88 of file checksum_core.c.
References BRIX_CK_ADLER32, BRIX_CK_CRC32, and brix_crc32c_extend().
Referenced by brix_cksum_u32_obj_range().