nginx-xrootd: src/protocols/root/query/checksum_ckscan_dispatch.c File Reference
checksum_ckscan_dispatch.c File Reference
#include "query_internal.h"
#include "protocols/root/response/response.h"
#include "core/aio/aio.h"
#include "core/compat/checksum.h"
#include "fs/path/beneath.h"
#include <dirent.h>
#include <sys/stat.h>
Functions
void brix_ckscan_aio_thread (void *data, ngx_log_t *log)
void brix_ckscan_aio_done (ngx_event_t *ev)
static ngx_flag_t brix_ckscan_algorithm_supported (const char *algo)
static ngx_int_t brix_ckscan_send_error (brix_ctx_t *ctx, ngx_connection_t *c, uint16_t errcode, const char *errmsg)
static ngx_int_t brix_ckscan_select_payload (brix_ctx_t *ctx, ngx_connection_t *c, const u_char **path_payload, size_t *path_payload_len, char *algo, size_t algo_sz)
static ngx_int_t brix_ckscan_sync (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, int rootfd, const char *logical, const char *algo)
ngx_int_t brix_query_ckscan (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_ckscan_aio_done()
void brix_ckscan_aio_done (ngx_event_t * ev) extern
Definition at line 88 of file checksum_ckscan_async.c.
References brix_aio_restore_request(), brix_aio_resume(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_QUERY_CKSCAN, brix_send_error(), brix_send_ok(), c, brix_ckscan_aio_t::c, brix_ckscan_aio_t::ctx, brix_ckscan_aio_t::error_code, brix_ckscan_aio_t::error_msg, brix_ckscan_aio_t::resp, brix_ckscan_aio_t::resp_len, brix_ckscan_aio_t::scan_logical, and brix_ckscan_aio_t::streamid.
Referenced by brix_query_ckscan().
brix_ckscan_aio_thread()
void brix_ckscan_aio_thread (void * data, ngx_log_t * log) extern
Definition at line 33 of file checksum_ckscan_async.c.
References brix_ckscan_aio_t::algo, BRIX_CKSCAN_INIT_CAP, brix_ckscan_run(), brix_ckscan_aio_t::error_code, brix_ckscan_aio_t::error_msg, kXR_NoMemory, log, brix_ckscan_aio_t::max_depth, brix_ckscan_aio_t::max_files, brix_ckscan_aio_t::resp, brix_ckscan_aio_t::resp_len, brix_ckscan_aio_t::rootfd, and brix_ckscan_aio_t::scan_logical.
Referenced by brix_query_ckscan().
brix_ckscan_algorithm_supported()
static ngx_flag_t brix_ckscan_algorithm_supported (const char * algo) static
Definition at line 35 of file checksum_ckscan_dispatch.c.
References alg, BRIX_CHECKSUM_ADLER32, BRIX_CHECKSUM_CRC32C, BRIX_CHECKSUM_CRC64, BRIX_CHECKSUM_CRC64NVME, and brix_checksum_parse().
Referenced by brix_ckscan_select_payload().
brix_ckscan_select_payload()
static ngx_int_t brix_ckscan_select_payload (brix_ctx_t * ctx, ngx_connection_t * c, const u_char ** path_payload, size_t * path_payload_len, char * algo, size_t algo_sz) static
Definition at line 68 of file checksum_ckscan_dispatch.c.
References alg, brix_checksum_parse(), brix_ckscan_algorithm_supported(), brix_ckscan_send_error(), c, brix_ctx_recv_t::cur_dlen, kXR_ArgInvalid, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by brix_query_ckscan().
brix_ckscan_send_error()
static ngx_int_t brix_ckscan_send_error (brix_ctx_t * ctx, ngx_connection_t * c, uint16_t errcode, const char * errmsg) static
Definition at line 53 of file checksum_ckscan_dispatch.c.
References brix_send_error(), and c.
Referenced by brix_ckscan_select_payload().
brix_ckscan_sync()
static ngx_int_t brix_ckscan_sync (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, int rootfd, const char * logical, const char * algo) static
Definition at line 116 of file checksum_ckscan_dispatch.c.
References BRIX_CKSCAN_INIT_CAP, brix_ckscan_run(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_QUERY_CKSCAN, brix_send_error(), brix_send_ok(), c, and kXR_NoMemory.
Referenced by brix_query_ckscan().
brix_query_ckscan()
ngx_int_t brix_query_ckscan (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 158 of file checksum_ckscan_dispatch.c.
References brix_ckscan_aio_t::algo, brix_aio_post_task(), brix_auth_gate(), BRIX_AUTH_READ, brix_beneath_full_path(), brix_ckscan_aio_done(), brix_ckscan_aio_thread(), brix_ckscan_select_payload(), brix_ckscan_sync(), brix_extract_path(), BRIX_MAX_PATH, BRIX_OP_ERR, BRIX_OP_QUERY_CKSCAN, BRIX_RETURN_ERR, brix_send_error(), c, brix_ckscan_aio_t::c, brix_ckscan_aio_t::conf, brix_ckscan_aio_t::ctx, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_streamid, brix_ckscan_aio_t::error_code, kXR_ArgInvalid, kXR_ArgMissing, kXR_NoMemory, brix_ckscan_aio_t::max_depth, brix_ckscan_aio_t::max_files, ngx_memcpy, PATH_MAX, brix_ctx_recv_t::payload, brix_ctx_t::recv, brix_ckscan_aio_t::resp, brix_ckscan_aio_t::resp_len, brix_ckscan_aio_t::rootfd, brix_ckscan_aio_t::scan_logical, brix_ckscan_aio_t::streamid, and brix_ctx_t::write_rc.
Referenced by brix_query_route_common().