nginx-xrootd: src/protocols/root/query/checksum_qcksum.c File Reference
checksum_qcksum.c File Reference
#include "query_internal.h"
#include "core/compat/checksum.h"
#include "core/compat/integrity_info.h"
#include "protocols/root/response/response.h"
#include "core/aio/aio.h"
#include "fs/vfs/vfs.h"
#include "protocols/root/path/op_path.h"
#include "net/manager/registry.h"
#include "net/manager/pending.h"
#include "net/cms/cms_internal.h"
#include <ctype.h>
#include <dirent.h>
#include <sys/stat.h>
Data Structures
struct brix_qcksum_req_t
Macros
#define BRIX_QCKSUM_DEFAULT_ALGO "adler32"
#define BRIX_QCKSUM_ALGO_SZ 32
Functions
void brix_cksum_aio_thread (void *data, ngx_log_t *log)
void brix_cksum_aio_done (ngx_event_t *ev)
static ngx_flag_t brix_query_parse_algorithm (const u_char *src, size_t len, char *algo, size_t algo_sz)
static ngx_int_t brix_query_cksum_send_error (brix_ctx_t *ctx, ngx_connection_t *c, uint16_t errcode, const char *errmsg)
static ngx_int_t brix_query_build_checksum (brix_ctx_t *ctx, ngx_connection_t *c, int fd, brix_sd_obj_t *obj, const char *resolved, const char *algo, char *resp, size_t resp_sz)
static ngx_flag_t brix_qcksum_find_algo_sep (const u_char *payload, size_t payload_len, size_t *sep_off, size_t *alg_len)
static void brix_qcksum_apply_cks_type_cgi (const u_char *path_payload, size_t path_payload_len, char *algo, size_t algo_sz, ngx_flag_t *bad_algo)
static ngx_int_t brix_qcksum_select_algo (brix_qcksum_req_t *rq, const u_char **path_payload, size_t *path_payload_len, ngx_int_t *out_rc)
static ngx_int_t brix_qcksum_manager_bounce (brix_qcksum_req_t *rq, ngx_int_t *out_rc)
static ngx_int_t brix_qcksum_resolve (brix_qcksum_req_t *rq, ngx_int_t *out_rc)
static brix_vfs_file_t * brix_qcksum_open (brix_qcksum_req_t *rq, ngx_int_t *out_rc)
static ngx_int_t brix_qcksum_try_async (brix_qcksum_req_t *rq, brix_vfs_file_t *fh, int fd, ngx_flag_t *handled)
static ngx_int_t brix_qcksum_compute_sync (brix_qcksum_req_t *rq, brix_vfs_file_t *fh, int fd)
static ngx_int_t brix_query_cksum_path (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
static void brix_qcksum_handle_extract_algo (brix_ctx_t *ctx, char *algo, size_t algo_sz)
static ngx_int_t brix_qcksum_handle_try_async (brix_qcksum_req_t *rq, int idx, const char *resolved, ngx_flag_t *handled)
static ngx_int_t brix_query_cksum_handle (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const xrdw_query_req_t *req)
ngx_int_t brix_query_cksum (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const xrdw_query_req_t *req)
Macro Definition Documentation
BRIX_QCKSUM_ALGO_SZ
#define BRIX_QCKSUM_ALGO_SZ 32
Definition at line 38 of file checksum_qcksum.c.
BRIX_QCKSUM_DEFAULT_ALGO
#define BRIX_QCKSUM_DEFAULT_ALGO "adler32"
Definition at line 37 of file checksum_qcksum.c.
Function Documentation
brix_cksum_aio_done()
void brix_cksum_aio_done (ngx_event_t * ev) extern
Definition at line 69 of file checksum_qcksum_async.c.
References brix_aio_restore_request(), brix_aio_resume(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_QUERY_CKSUM, brix_send_error(), brix_send_ok(), brix_vfs_close(), c, brix_cksum_aio_t::c, close(), brix_cksum_aio_t::close_fd, brix_cksum_aio_t::ctx, brix_cksum_aio_t::error_code, brix_cksum_aio_t::error_msg, brix_cksum_aio_t::fd, brix_cksum_aio_t::fh, brix_vfs_file_t::log, brix_cksum_aio_t::resolved, brix_cksum_aio_t::resp, and brix_cksum_aio_t::streamid.
Referenced by brix_qcksum_handle_try_async(), and brix_qcksum_try_async().
brix_cksum_aio_thread()
void brix_cksum_aio_thread (void * data, ngx_log_t * log) extern
Definition at line 33 of file checksum_qcksum_async.c.
References brix_integrity_info_t::alg_name, brix_cksum_aio_t::algo, brix_integrity_opts_t::allow_xattr_cache, brix_integrity_get_fd(), brix_cksum_aio_t::error_code, brix_cksum_aio_t::error_msg, brix_cksum_aio_t::fd, brix_integrity_info_t::hex, kXR_IOError, log, brix_cksum_aio_t::obj, brix_cksum_aio_t::resolved, brix_cksum_aio_t::resp, and brix_integrity_opts_t::update_xattr_cache.
Referenced by brix_qcksum_handle_try_async(), and brix_qcksum_try_async().
brix_qcksum_apply_cks_type_cgi()
static void brix_qcksum_apply_cks_type_cgi (const u_char * path_payload, size_t path_payload_len, char * algo, size_t algo_sz, ngx_flag_t * bad_algo) static
Definition at line 162 of file checksum_qcksum.c.
References brix_query_parse_algorithm(), and key.
Referenced by brix_qcksum_select_algo().
brix_qcksum_compute_sync()
static ngx_int_t brix_qcksum_compute_sync (brix_qcksum_req_t * rq, brix_vfs_file_t * fh, int fd) static
Definition at line 549 of file checksum_qcksum.c.
References brix_qcksum_req_t::algo, brix_log_access(), BRIX_OP_OK, BRIX_OP_QUERY_CKSUM, brix_query_build_checksum(), brix_send_ok(), brix_vfs_close(), brix_vfs_file_sd_obj(), c, brix_qcksum_req_t::c, brix_qcksum_req_t::ctx, and brix_qcksum_req_t::full_path.
Referenced by brix_query_cksum_path().
brix_qcksum_find_algo_sep()
static ngx_flag_t brix_qcksum_find_algo_sep (const u_char * payload, size_t payload_len, size_t * sep_off, size_t * alg_len) static
Definition at line 131 of file checksum_qcksum.c.
Referenced by brix_qcksum_select_algo().
brix_qcksum_handle_extract_algo()
static void brix_qcksum_handle_extract_algo (brix_ctx_t * ctx, char * algo, size_t algo_sz) static
Definition at line 626 of file checksum_qcksum.c.
References brix_query_parse_algorithm(), brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by brix_query_cksum_handle().
brix_qcksum_handle_try_async()
static ngx_int_t brix_qcksum_handle_try_async (brix_qcksum_req_t * rq, int idx, const char * resolved, ngx_flag_t * handled) static
Definition at line 656 of file checksum_qcksum.c.
References brix_qcksum_req_t::algo, brix_cksum_aio_t::algo, brix_aio_post_task(), brix_cksum_aio_done(), brix_cksum_aio_thread(), BRIX_OP_ERR, BRIX_OP_QUERY_CKSUM, brix_send_error(), c, brix_qcksum_req_t::c, brix_cksum_aio_t::c, brix_cksum_aio_t::close_fd, brix_qcksum_req_t::conf, brix_cksum_aio_t::conf, brix_qcksum_req_t::ctx, brix_cksum_aio_t::ctx, brix_ctx_recv_t::cur_streamid, brix_cksum_aio_t::error_code, brix_file_t::fd, brix_cksum_aio_t::fd, brix_ctx_t::files, kXR_NoMemory, ngx_memcpy, brix_cksum_aio_t::obj, brix_ctx_t::recv, brix_cksum_aio_t::resolved, brix_file_t::sd_obj, and brix_cksum_aio_t::streamid.
Referenced by brix_query_cksum_handle().
brix_qcksum_manager_bounce()
static ngx_int_t brix_qcksum_manager_bounce (brix_qcksum_req_t * rq, ngx_int_t * out_rc) static
Definition at line 266 of file checksum_qcksum.c.
References brix_log_access(), brix_manager_tried_exhausted(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_QUERY_CKSUM, brix_pending_insert(), brix_pending_remove(), brix_send_error(), brix_send_redirect(), brix_srv_select(), c, brix_qcksum_req_t::c, brix_ctx_t::cms_wait_streamid, brix_qcksum_req_t::conf, brix_qcksum_req_t::ctx, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_streamid, kXR_NotFound, kXR_ok, ngx_brix_cms_next_streamid(), ngx_brix_cms_send_locate(), brix_qcksum_req_t::pathbuf, brix_ctx_recv_t::payload, brix_ctx_t::recv, brix_ctx_t::state, XRD_ST_REQ_HEADER, and XRD_ST_WAITING_CMS.
Referenced by brix_qcksum_resolve().
brix_qcksum_open()
static brix_vfs_file_t * brix_qcksum_open (brix_qcksum_req_t * rq, ngx_int_t * out_rc) static
Definition at line 401 of file checksum_qcksum.c.
References brix_kxr_from_errno(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_QUERY_CKSUM, BRIX_PROTO_ROOT, brix_root_vfs_bind_deleg(), brix_send_error(), brix_send_redirect(), brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_bind_backend_mint(), brix_vfs_ctx_init(), BRIX_VFS_O_READ, brix_vfs_open(), c, brix_qcksum_req_t::c, code, brix_qcksum_req_t::conf, brix_qcksum_req_t::ctx, brix_qcksum_req_t::full_path, brix_ctx_t::identity, kXR_ok, ngx_memcpy, brix_qcksum_req_t::pathbuf, and brix_vfs_ctx_t::pool.
Referenced by brix_query_cksum_path().
brix_qcksum_resolve()
static ngx_int_t brix_qcksum_resolve (brix_qcksum_req_t * rq, ngx_int_t * out_rc) static
Definition at line 344 of file checksum_qcksum.c.
References brix_auth_gate(), BRIX_AUTH_READ, brix_beneath_full_path(), brix_extract_path(), BRIX_OP_ERR, BRIX_OP_QUERY_CKSUM, brix_qcksum_manager_bounce(), brix_qcksum_select_algo(), brix_send_error(), c, brix_qcksum_req_t::c, brix_qcksum_req_t::conf, brix_qcksum_req_t::ctx, brix_qcksum_req_t::full_path, kXR_ArgInvalid, brix_qcksum_req_t::pathbuf, and brix_ctx_t::write_rc.
Referenced by brix_query_cksum_path().
brix_qcksum_select_algo()
static ngx_int_t brix_qcksum_select_algo (brix_qcksum_req_t * rq, const u_char ** path_payload, size_t * path_payload_len, ngx_int_t * out_rc) static
Definition at line 217 of file checksum_qcksum.c.
References brix_qcksum_req_t::algo, BRIX_OP_ERR, BRIX_OP_QUERY_CKSUM, brix_qcksum_apply_cks_type_cgi(), brix_qcksum_find_algo_sep(), brix_query_parse_algorithm(), brix_send_error(), brix_qcksum_req_t::c, brix_qcksum_req_t::ctx, brix_ctx_recv_t::cur_dlen, kXR_ArgInvalid, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by brix_qcksum_resolve().
brix_qcksum_try_async()
static ngx_int_t brix_qcksum_try_async (brix_qcksum_req_t * rq, brix_vfs_file_t * fh, int fd, ngx_flag_t * handled) static
Definition at line 482 of file checksum_qcksum.c.
References brix_qcksum_req_t::algo, brix_cksum_aio_t::algo, brix_aio_post_task(), brix_cksum_aio_done(), brix_cksum_aio_thread(), BRIX_OP_ERR, BRIX_OP_QUERY_CKSUM, brix_send_error(), brix_vfs_close(), brix_vfs_file_sd_obj(), c, brix_qcksum_req_t::c, brix_cksum_aio_t::c, brix_cksum_aio_t::close_fd, brix_qcksum_req_t::conf, brix_cksum_aio_t::conf, brix_qcksum_req_t::ctx, brix_cksum_aio_t::ctx, brix_ctx_recv_t::cur_streamid, brix_cksum_aio_t::error_code, brix_cksum_aio_t::fd, brix_cksum_aio_t::fh, brix_qcksum_req_t::full_path, kXR_NoMemory, ngx_memcpy, brix_cksum_aio_t::obj, brix_ctx_t::recv, brix_cksum_aio_t::resolved, and brix_cksum_aio_t::streamid.
Referenced by brix_query_cksum_path().
brix_query_build_checksum()
static ngx_int_t brix_query_build_checksum (brix_ctx_t * ctx, ngx_connection_t * c, int fd, brix_sd_obj_t * obj, const char * resolved, const char * algo, char * resp, size_t resp_sz) static
Definition at line 94 of file checksum_qcksum.c.
References brix_integrity_info_t::alg_name, brix_integrity_opts_t::allow_xattr_cache, brix_integrity_get_fd(), BRIX_OP_ERR, BRIX_OP_QUERY_CKSUM, brix_query_cksum_send_error(), c, brix_integrity_info_t::hex, kXR_IOError, and brix_integrity_opts_t::update_xattr_cache.
Referenced by brix_qcksum_compute_sync(), and brix_query_cksum_handle().
brix_query_cksum()
ngx_int_t brix_query_cksum (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const xrdw_query_req_t * req)
Definition at line 770 of file checksum_qcksum.c.
References brix_query_cksum_handle(), brix_query_cksum_path(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by brix_cli_cksum_main(), brix_query_route_common(), chk_probe_checksum(), ckcheck_digest_remote(), cksum_verify_source(), cmd_verify(), do_cksum(), do_cmp(), dx_probe_checksum(), entry_cksum(), op_cks(), remote_tree_visitor(), sync_cksum_match(), write_checksum(), and xfs_getxattr().
brix_query_cksum_handle()
static ngx_int_t brix_query_cksum_handle (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const xrdw_query_req_t * req) static
Definition at line 717 of file checksum_qcksum.c.
References brix_qcksum_req_t::algo, brix_log_access(), BRIX_MAX_FILES, BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_QUERY_CKSUM, BRIX_QCKSUM_DEFAULT_ALGO, brix_qcksum_handle_extract_algo(), brix_qcksum_handle_try_async(), brix_query_build_checksum(), brix_send_error(), brix_send_ok(), c, brix_qcksum_req_t::c, brix_qcksum_req_t::conf, brix_qcksum_req_t::ctx, brix_file_t::fd, xrdw_query_req_t::fhandle, brix_ctx_t::files, kXR_FileNotOpen, brix_file_t::path, PATH_MAX, and brix_file_t::sd_obj.
Referenced by brix_query_cksum().
brix_query_cksum_path()
static ngx_int_t brix_query_cksum_path (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf) static
Definition at line 581 of file checksum_qcksum.c.
References brix_qcksum_req_t::algo, brix_qcksum_compute_sync(), BRIX_QCKSUM_DEFAULT_ALGO, brix_qcksum_open(), brix_qcksum_resolve(), brix_qcksum_try_async(), brix_vfs_file_fd(), c, brix_qcksum_req_t::c, brix_qcksum_req_t::conf, and brix_qcksum_req_t::ctx.
Referenced by brix_query_cksum().
brix_query_cksum_send_error()
static ngx_int_t brix_query_cksum_send_error (brix_ctx_t * ctx, ngx_connection_t * c, uint16_t errcode, const char * errmsg) static
Definition at line 78 of file checksum_qcksum.c.
References brix_send_error(), and c.
Referenced by brix_query_build_checksum().
brix_query_parse_algorithm()
static ngx_flag_t brix_query_parse_algorithm (const u_char * src, size_t len, char * algo, size_t algo_sz) static
Definition at line 61 of file checksum_qcksum.c.
References brix_checksum_parse().
Referenced by brix_qcksum_apply_cks_type_cgi(), brix_qcksum_handle_extract_algo(), and brix_qcksum_select_algo().