nginx-xrootd: src/protocols/root/query/checksum_qcksum_internal.h File Reference
checksum_qcksum_internal.h File Reference
#include "query_internal.h"
Data Structures
struct brix_qcksum_req_t
Macros
#define BRIX_QCKSUM_DEFAULT_ALGO "adler32"
#define BRIX_QCKSUM_ALGO_SZ 32
Functions
ngx_flag_t brix_query_parse_algorithm (const u_char *src, size_t len, char *algo, size_t algo_sz)
ngx_int_t brix_query_build_checksum (brix_ctx_t *ctx, ngx_connection_t *c, int fd, brix_sd_obj_t *obj, const char *resolved, const char *algo, char *resp, size_t resp_sz)
ngx_int_t brix_query_cksum_path (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Macro Definition Documentation
BRIX_QCKSUM_ALGO_SZ
#define BRIX_QCKSUM_ALGO_SZ 32
Definition at line 23 of file checksum_qcksum_internal.h.
BRIX_QCKSUM_DEFAULT_ALGO
#define BRIX_QCKSUM_DEFAULT_ALGO "adler32"
Definition at line 22 of file checksum_qcksum_internal.h.
Function Documentation
brix_query_build_checksum()
ngx_int_t brix_query_build_checksum (brix_ctx_t * ctx, ngx_connection_t * c, int fd, brix_sd_obj_t * obj, const char * resolved, const char * algo, char * resp, size_t resp_sz)
Definition at line 74 of file checksum_qcksum.c.
References brix_integrity_info_t::alg_name, brix_integrity_opts_t::allow_xattr_cache, brix_integrity_get_fd(), BRIX_OP_ERR, BRIX_OP_QUERY_CKSUM, brix_query_cksum_send_error(), c, brix_integrity_info_t::hex, kXR_IOError, and brix_integrity_opts_t::update_xattr_cache.
Referenced by brix_qcksum_compute_sync(), and brix_query_cksum_handle().
brix_query_cksum_path()
ngx_int_t brix_query_cksum_path (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 501 of file checksum_qcksum_path.c.
References brix_qcksum_req_t::algo, brix_qcksum_compute_sync(), BRIX_QCKSUM_DEFAULT_ALGO, brix_qcksum_open(), brix_qcksum_resolve(), brix_qcksum_try_async(), brix_vfs_file_fd(), c, brix_qcksum_req_t::c, brix_qcksum_req_t::conf, and brix_qcksum_req_t::ctx.
Referenced by brix_query_cksum().
brix_query_parse_algorithm()
ngx_flag_t brix_query_parse_algorithm (const u_char * src, size_t len, char * algo, size_t algo_sz)
Definition at line 41 of file checksum_qcksum.c.
References alg, and brix_checksum_parse().
Referenced by brix_qcksum_apply_cks_type_cgi(), brix_qcksum_handle_extract_algo(), and brix_qcksum_select_algo().