nginx-xrootd: src/core/compat/checksum_core.h File Reference
checksum_core.h File Reference
#include <stdint.h>
#include "fs/backend/sd.h"
Macros
#define BRIX_CK_ADLER32 0
#define BRIX_CK_CRC32 1
#define BRIX_CK_CRC32C 2
#define BRIX_CK_MD5 3
#define BRIX_CK_SHA1 4
#define BRIX_CK_SHA256 5
#define BRIX_CK_CRC64 6 /* CRC-64/XZ */
#define BRIX_CK_CRC64NVME 7 /* CRC-64/NVME */
#define BRIX_CK_ZCRC32
Functions
int brix_cksum_u32_obj (int kind, brix_sd_obj_t *obj, uint32_t *out)
int brix_cksum_u64_obj (int kind, brix_sd_obj_t *obj, uint64_t *out)
int brix_cksum_digest_obj (int kind, brix_sd_obj_t *obj, unsigned char *out, unsigned int *outlen)
int brix_cksum_u32_obj_range (int kind, brix_sd_obj_t *obj, off_t start, off_t len, uint32_t *out)
int brix_cksum_u64_obj_range (int kind, brix_sd_obj_t *obj, off_t start, off_t len, uint64_t *out)
int brix_cksum_digest_obj_range (int kind, brix_sd_obj_t *obj, off_t start, off_t len, unsigned char *out, unsigned int *outlen)
int brix_cksum_u32_fd (int kind, int fd, uint32_t *out)
int brix_cksum_u64_fd (int kind, int fd, uint64_t *out)
int brix_cksum_digest_fd (int kind, int fd, unsigned char *out, unsigned int *outlen)
Macro Definition Documentation
BRIX_CK_ADLER32
#define BRIX_CK_ADLER32 0
Definition at line 25 of file checksum_core.h.
BRIX_CK_CRC32
#define BRIX_CK_CRC32 1
Definition at line 26 of file checksum_core.h.
BRIX_CK_CRC32C
#define BRIX_CK_CRC32C 2
Definition at line 27 of file checksum_core.h.
BRIX_CK_CRC64
#define BRIX_CK_CRC64 6 /* CRC-64/XZ */
Definition at line 31 of file checksum_core.h.
BRIX_CK_CRC64NVME
#define BRIX_CK_CRC64NVME 7 /* CRC-64/NVME */
Definition at line 32 of file checksum_core.h.
BRIX_CK_MD5
#define BRIX_CK_MD5 3
Definition at line 28 of file checksum_core.h.
BRIX_CK_SHA1
#define BRIX_CK_SHA1 4
Definition at line 29 of file checksum_core.h.
BRIX_CK_SHA256
#define BRIX_CK_SHA256 5
Definition at line 30 of file checksum_core.h.
BRIX_CK_ZCRC32
#define BRIX_CK_ZCRC32
Value:
                                 8   /* zlib CRC-32 — XRootD "zcrc32" (same algorithm
                                 * as CRC32/ISO-HDLC; a distinct registered name) */
Definition at line 33 of file checksum_core.h.
Function Documentation
brix_cksum_digest_fd()
int brix_cksum_digest_fd (int kind, int fd, unsigned char * out, unsigned int * outlen)
Definition at line 322 of file checksum_core.c.
References brix_cksum_digest_obj(), and brix_sd_posix_wrap().
Referenced by brix_checksum_digest_fd(), and brix_cksum_fd().
brix_cksum_digest_obj()
int brix_cksum_digest_obj (int kind, brix_sd_obj_t * obj, unsigned char * out, unsigned int * outlen)
Definition at line 315 of file checksum_core.c.
References brix_cksum_digest_obj_range().
Referenced by brix_checksum_hex_obj(), and brix_cksum_digest_fd().
brix_cksum_digest_obj_range()
int brix_cksum_digest_obj_range (int kind, brix_sd_obj_t * obj, off_t start, off_t len, unsigned char * out, unsigned int * outlen)
Definition at line 294 of file checksum_core.c.
References digest_drive(), and md_for().
Referenced by brix_cksum_digest_obj(), and brix_ftp_ev_cmd_cksm().
brix_cksum_u32_fd()
int brix_cksum_u32_fd (int kind, int fd, uint32_t * out)
Definition at line 177 of file checksum_core.c.
References brix_cksum_u32_obj(), and brix_sd_posix_wrap().
Referenced by brix_checksum_u32_fd(), and brix_cksum_fd().
brix_cksum_u32_obj()
int brix_cksum_u32_obj (int kind, brix_sd_obj_t * obj, uint32_t * out)
Definition at line 171 of file checksum_core.c.
References brix_cksum_u32_obj_range().
Referenced by brix_checksum_hex_obj(), brix_cksum_u32_fd(), and brix_vfs_wverify_check().
brix_cksum_u32_obj_range()
int brix_cksum_u32_obj_range (int kind, brix_sd_obj_t * obj, off_t start, off_t len, uint32_t * out)
Definition at line 124 of file checksum_core.c.
References BRIX_CK_BUFSZ, BRIX_CK_CRC32, BRIX_CK_CRC32C, BRIX_CK_ZCRC32, range_want(), u32_kind_ok(), u32_seed(), and u32_update().
Referenced by brix_cksum_u32_obj(), and brix_ftp_ev_cmd_cksm().
brix_cksum_u64_fd()
int brix_cksum_u64_fd (int kind, int fd, uint64_t * out)
Definition at line 238 of file checksum_core.c.
References brix_cksum_u64_obj(), and brix_sd_posix_wrap().
Referenced by brix_checksum_u64_fd(), and brix_cksum_fd().
brix_cksum_u64_obj()
int brix_cksum_u64_obj (int kind, brix_sd_obj_t * obj, uint64_t * out)
Definition at line 232 of file checksum_core.c.
References brix_cksum_u64_obj_range().
Referenced by brix_checksum_hex_obj(), and brix_cksum_u64_fd().
brix_cksum_u64_obj_range()
int brix_cksum_u64_obj_range (int kind, brix_sd_obj_t * obj, off_t start, off_t len, uint64_t * out)
Definition at line 186 of file checksum_core.c.
References BRIX_CK_BUFSZ, BRIX_CK_CRC64, BRIX_CK_CRC64NVME, brix_crc64_extend(), BRIX_CRC64_NVME, BRIX_CRC64_XZ, and range_want().
Referenced by brix_cksum_u64_obj().