nginx-xrootd: src/protocols/root/write/chkpoint.h File Reference
chkpoint.h File Reference
#include "core/ngx_brix_module.h"
Functions
ngx_int_t brix_handle_chkpoint (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_chkpoint_recover_root (ngx_log_t *log, const char *root_canon)
Function Documentation
brix_chkpoint_recover_root()
ngx_int_t brix_chkpoint_recover_root (ngx_log_t * log, const char * root_canon)
Definition at line 275 of file chkpoint_recover.c.
References brix_log_safe_path(), ckp_recover_scan(), log, ngx_memcpy, open(), and PATH_MAX.
Referenced by brix_init_one_server().
brix_handle_chkpoint()
ngx_int_t brix_handle_chkpoint (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 232 of file chkpoint.c.
References BRIX_OP_CHKPOINT, BRIX_OP_ERR, brix_send_error(), brix_validate_write_handle(), c, ckp_begin(), ckp_commit(), ckp_query(), ckp_rollback(), ckp_xeq(), xrdw_chkpoint_req_t::fhandle, brix_ctx_t::files, brix_ctx_recv_t::hdr_buf, kXR_ArgInvalid, kXR_ckpBegin, kXR_ckpCommit, kXR_ckpQuery, kXR_ckpRollback, kXR_ckpXeq, xrdw_chkpoint_req_t::opcode, brix_file_t::path, brix_ctx_t::recv, brix_file_t::ssi, and xrdw_chkpoint_req_unpack().