nginx-xrootd: src/protocols/root/write/chkpoint_xeq_internal.h File Reference
chkpoint_xeq_internal.h File Reference
#include "chkpoint_xeq.h"
Data Structures
struct ckp_write_desc_t
Functions
ngx_int_t ckp_xeq_write (brix_ctx_t *ctx, ngx_connection_t *c, int idx, const ckp_write_desc_t *d)
ngx_int_t ckp_xeq_pgwrite (brix_ctx_t *ctx, ngx_connection_t *c, int idx, const ckp_write_desc_t *d)
ngx_int_t ckp_xeq_truncate (brix_ctx_t *ctx, ngx_connection_t *c, int idx, const u_char *sub_hdr)
ngx_int_t ckp_xeq_writev (brix_ctx_t *ctx, ngx_connection_t *c, int idx, const ckp_write_desc_t *d, uint32_t data_len)
Function Documentation
ckp_xeq_pgwrite()
ngx_int_t ckp_xeq_pgwrite (brix_ctx_t * ctx, ngx_connection_t * c, int idx, const ckp_write_desc_t * d)
Definition at line 196 of file chkpoint_xeq_write.c.
References brix_csi_write_update(), brix_log_access(), BRIX_OP_CHKPOINT, BRIX_OP_ERR, brix_pgwrite_decode_payload(), BRIX_RETURN_ERR, brix_send_error(), brix_send_pgwrite_status(), brix_ctx_totals_t::bytes_written, brix_file_t::bytes_written, c, ckp_xeq_pgwrite_drain(), brix_file_t::csi, ckp_pgwrite_drain_t::end_offset, xrdw_pgwrite_req_t::fhandle, brix_ctx_t::files, ckp_pgwrite_drain_t::flat, ckp_pgwrite_drain_t::flat_sz, kXR_ArgInvalid, kXR_ChkSumErr, kXR_InvalidRequest, kXR_ok, xrdw_pgwrite_req_t::offset, ckp_pgwrite_drain_t::offset, brix_file_t::path, ckp_write_desc_t::sub_dlen, ckp_write_desc_t::sub_hdr, ckp_write_desc_t::sub_payload, ckp_pgwrite_drain_t::total, brix_ctx_t::totals, XRD_PGWRITE_CKSZ, and xrdw_pgwrite_req_unpack().
Referenced by ckp_xeq_dispatch().
ckp_xeq_truncate()
ngx_int_t ckp_xeq_truncate (brix_ctx_t * ctx, ngx_connection_t * c, int idx, const u_char * sub_hdr)
Definition at line 298 of file chkpoint_xeq_write.c.
References BRIX_OP_CHKPOINT, BRIX_RETURN_ERR, brix_send_error(), brix_send_ok(), brix_vfs_io_execute(), brix_vfs_job_truncate_init(), c, brix_file_t::fd, xrdw_truncate_req_t::fhandle, brix_ctx_t::files, brix_vfs_job_t::io_errno, kXR_InvalidRequest, kXR_IOError, xrdw_truncate_req_t::offset, brix_file_t::path, and xrdw_truncate_req_unpack().
Referenced by ckp_xeq_dispatch().
ckp_xeq_write()
ngx_int_t ckp_xeq_write (brix_ctx_t * ctx, ngx_connection_t * c, int idx, const ckp_write_desc_t * d)
Definition at line 65 of file chkpoint_xeq_write.c.
References brix_csi_write_update(), BRIX_OP_CHKPOINT, BRIX_RETURN_ERR, brix_send_error(), brix_send_ok(), brix_ctx_totals_t::bytes_written, brix_file_t::bytes_written, c, ckp_xeq_vfs_write_full(), brix_file_t::csi, brix_file_t::fd, xrdw_write_req_t::fhandle, brix_ctx_t::files, ckp_write_result_t::io_errno, kXR_InvalidRequest, kXR_IOError, xrdw_write_req_t::offset, brix_file_t::path, ckp_write_result_t::short_io, ckp_write_desc_t::sub_dlen, ckp_write_desc_t::sub_hdr, ckp_write_desc_t::sub_payload, brix_ctx_t::totals, ckp_write_result_t::written, and xrdw_write_req_unpack().
Referenced by ckp_xeq_dispatch().
ckp_xeq_writev()
ngx_int_t ckp_xeq_writev (brix_ctx_t * ctx, ngx_connection_t * c, int idx, const ckp_write_desc_t * d, uint32_t data_len)
Definition at line 347 of file chkpoint_xeq_write.c.
References brix_log_access(), BRIX_OP_CHKPOINT, BRIX_OP_ERR, BRIX_RETURN_ERR, brix_send_error(), brix_send_ok(), BRIX_WRITEV_MAXSEGS, BRIX_WRITEV_SEGSIZE, brix_ctx_totals_t::bytes_written, brix_file_t::bytes_written, c, ckp_xeq_vfs_write_full(), brix_file_t::fd, brix_ctx_t::files, ckp_write_result_t::io_errno, kXR_ArgInvalid, kXR_ArgTooLong, kXR_IOError, kXR_ok, kXR_Unsupported, write_list::offset, brix_file_t::path, ckp_write_result_t::short_io, ckp_write_desc_t::sub_dlen, ckp_write_desc_t::sub_payload, brix_ctx_t::totals, write_list::wlen, and ckp_write_result_t::written.
Referenced by ckp_xeq_dispatch().