nginx-xrootd: src/protocols/root/write/chkpoint_recover.c File Reference
chkpoint_recover.c File Reference
#include "core/ngx_brix_module.h"
#include "fs/vfs/vfs.h"
#include "chkpoint_xeq.h"
#include "core/compat/log.h"
#include "core/compat/copy_range.h"
#include "core/compat/staged_file.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <sys/file.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
struct ckp_scan_dir_t
Functions
static ngx_flag_t ckp_name_has_suffix (const char *name)
static ngx_int_t ckp_recover_one (ngx_log_t *log, const char *root_canon, const char *ckp_path)
static ngx_int_t ckp_recover_open_dir (ngx_log_t *log, const char *root_canon, const char *dir, ngx_uint_t depth, ckp_scan_dir_t *out)
static ngx_int_t ckp_recover_scan (ngx_log_t *log, const char *root_canon, const char *dir, ngx_uint_t depth)
ngx_int_t brix_chkpoint_recover_root (ngx_log_t *log, const char *root_canon)
Function Documentation
brix_chkpoint_recover_root()
ngx_int_t brix_chkpoint_recover_root (ngx_log_t * log, const char * root_canon)
Definition at line 275 of file chkpoint_recover.c.
References brix_log_safe_path(), ckp_recover_scan(), log, ngx_memcpy, open(), and PATH_MAX.
Referenced by brix_init_one_server().
ckp_name_has_suffix()
static ngx_flag_t ckp_name_has_suffix (const char * name) static
Definition at line 26 of file chkpoint_recover.c.
References name.
Referenced by ckp_recover_scan().
ckp_recover_one()
static ngx_int_t ckp_recover_one (ngx_log_t * log, const char * root_canon, const char * ckp_path) static
Definition at line 35 of file chkpoint_recover.c.
References brix_copy_range(), brix_log_safe_path(), brix_staged_abort(), brix_staged_commit(), brix_staged_open(), brix_vfs_io_execute(), brix_vfs_job_sync_init(), brix_vfs_open_fd(), brix_vfs_unlink_path(), brix_staged_file_t::fd, fstat(), log, ngx_memcpy, PATH_MAX, brix_staged_open_req_t::root_canon, stat(), and brix_staged_file_t::tmp_path.
Referenced by ckp_recover_scan().
ckp_recover_open_dir()
static ngx_int_t ckp_recover_open_dir (ngx_log_t * log, const char * root_canon, const char * dir, ngx_uint_t depth, ckp_scan_dir_t * out) static
Definition at line 145 of file chkpoint_recover.c.
References brix_log_safe_path(), brix_vfs_open_fd(), ckp_scan_dir_t::dp, log, and ckp_scan_dir_t::scan_fd.
Referenced by ckp_recover_scan().
ckp_recover_scan()
static ngx_int_t ckp_recover_scan (ngx_log_t * log, const char * root_canon, const char * dir, ngx_uint_t depth) static
Definition at line 203 of file chkpoint_recover.c.
References brix_log_safe_path(), ckp_name_has_suffix(), ckp_recover_one(), ckp_recover_open_dir(), ckp_recover_scan(), ckp_scan_dir_t::dp, fstatat(), log, ngx_memcpy, PATH_MAX, ckp_scan_dir_t::scan_fd, and stat().
Referenced by brix_chkpoint_recover_root(), and ckp_recover_scan().