nginx-xrootd: src/protocols/root/write/chkpoint_xeq.c File Reference
chkpoint_xeq.c File Reference
#include "chkpoint_xeq.h"
#include "chkpoint_xeq_internal.h"
#include <string.h>
Functions
ngx_int_t brix_ckpxeq_body_extra (const u_char *body, uint32_t have, uint32_t *extra, unsigned *final)
static ngx_int_t ckp_xeq_validate_frame (brix_ctx_t *ctx, ngx_connection_t *c, uint16_t sub_reqid, uint32_t sub_dlen)
static ngx_int_t ckp_xeq_dispatch (brix_ctx_t *ctx, ngx_connection_t *c, int idx, uint16_t sub_reqid, const ckp_write_desc_t *d)
ngx_int_t ckp_xeq (brix_ctx_t *ctx, ngx_connection_t *c, int idx)
Function Documentation
brix_ckpxeq_body_extra()
ngx_int_t brix_ckpxeq_body_extra (const u_char * body, uint32_t have, uint32_t * extra, unsigned * final)
Definition at line 24 of file chkpoint_xeq.c.
References BRIX_MAX_WRITE_PAYLOAD, brix_writev_body_extra(), BRIX_WRITEV_MAXSEGS, BRIX_WRITEV_SEGSIZE, have(), kXR_pgwrite, kXR_write, and kXR_writev.
Referenced by brix_recv_extend_body().
ckp_xeq()
ngx_int_t ckp_xeq (brix_ctx_t * ctx, ngx_connection_t * c, int idx)
Definition at line 191 of file chkpoint_xeq.c.
References BRIX_OP_CHKPOINT, BRIX_OP_ERR, BRIX_RETURN_ERR, brix_send_error(), c, brix_file_t::ckp_path, ckp_xeq_dispatch(), ckp_xeq_validate_frame(), brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_streamid, brix_ctx_t::files, kXR_ArgInvalid, kXR_InvalidRequest, brix_file_t::path, brix_ctx_recv_t::payload, brix_ctx_t::recv, ckp_write_desc_t::sub_dlen, ckp_write_desc_t::sub_hdr, and ckp_write_desc_t::sub_payload.
Referenced by brix_handle_chkpoint().
ckp_xeq_dispatch()
static ngx_int_t ckp_xeq_dispatch (brix_ctx_t * ctx, ngx_connection_t * c, int idx, uint16_t sub_reqid, const ckp_write_desc_t * d) static
Definition at line 160 of file chkpoint_xeq.c.
References BRIX_OP_CHKPOINT, BRIX_OP_ERR, brix_send_error(), c, ckp_xeq_pgwrite(), ckp_xeq_truncate(), ckp_xeq_write(), ckp_xeq_writev(), brix_ctx_recv_t::cur_body_extra, kXR_ArgInvalid, kXR_pgwrite, kXR_truncate, kXR_write, kXR_writev, brix_ctx_t::recv, ckp_write_desc_t::sub_dlen, and ckp_write_desc_t::sub_hdr.
Referenced by ckp_xeq().
ckp_xeq_validate_frame()
static ngx_int_t ckp_xeq_validate_frame (brix_ctx_t * ctx, ngx_connection_t * c, uint16_t sub_reqid, uint32_t sub_dlen) static
Definition at line 119 of file chkpoint_xeq.c.
References BRIX_OP_CHKPOINT, BRIX_OP_ERR, brix_send_error(), c, brix_ctx_recv_t::cur_body_extra, kXR_ArgInvalid, kXR_chkpoint, kXR_pgwrite, kXR_truncate, kXR_write, kXR_writev, and brix_ctx_t::recv.
Referenced by ckp_xeq().