nginx-xrootd: src/protocols/root/write/chkpoint.c File Reference
chkpoint.c File Reference
#include "core/ngx_brix_module.h"
#include "fs/vfs/vfs.h"
#include "chkpoint_xeq.h"
#include "core/compat/log.h"
#include "core/compat/copy_range.h"
#include "core/compat/staged_file.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <sys/file.h>
#include <sys/stat.h>
#include <unistd.h>
Functions
static void ckp_clear_path (brix_file_t *f)
static ngx_int_t ckp_begin (brix_ctx_t *ctx, ngx_connection_t *c, int idx)
static ngx_int_t ckp_commit (brix_ctx_t *ctx, ngx_connection_t *c, int idx)
static ngx_int_t ckp_rollback (brix_ctx_t *ctx, ngx_connection_t *c, int idx)
static ngx_int_t ckp_query (brix_ctx_t *ctx, ngx_connection_t *c, int idx)
ngx_int_t brix_handle_chkpoint (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
static ngx_flag_t ckp_name_has_suffix (const char *name)
static ngx_int_t ckp_recover_one (ngx_log_t *log, const char *root_canon, const char *ckp_path)
static ngx_int_t ckp_recover_scan (ngx_log_t *log, const char *root_canon, const char *dir, ngx_uint_t depth)
ngx_int_t brix_chkpoint_recover_root (ngx_log_t *log, const char *root_canon)
Function Documentation
brix_chkpoint_recover_root()
ngx_int_t brix_chkpoint_recover_root (ngx_log_t * log, const char * root_canon)
Definition at line 488 of file chkpoint.c.
References brix_log_safe_path(), ckp_recover_scan(), log, ngx_memcpy, open(), and PATH_MAX.
Referenced by ngx_stream_brix_init_process().
brix_handle_chkpoint()
ngx_int_t brix_handle_chkpoint (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 232 of file chkpoint.c.
References BRIX_OP_CHKPOINT, BRIX_OP_ERR, brix_send_error(), brix_validate_write_handle(), c, ckp_begin(), ckp_commit(), ckp_query(), ckp_rollback(), ckp_xeq(), xrdw_chkpoint_req_t::fhandle, brix_ctx_t::files, brix_ctx_recv_t::hdr_buf, kXR_ArgInvalid, kXR_ckpBegin, kXR_ckpCommit, kXR_ckpQuery, kXR_ckpRollback, kXR_ckpXeq, xrdw_chkpoint_req_t::opcode, brix_file_t::path, brix_ctx_t::recv, brix_file_t::ssi, and xrdw_chkpoint_req_unpack().
Referenced by brix_dispatch_write_opcode().
ckp_begin()
static ngx_int_t ckp_begin (brix_ctx_t * ctx, ngx_connection_t * c, int idx) static
Definition at line 51 of file chkpoint.c.
References brix_copy_range(), BRIX_OP_CHKPOINT, BRIX_OP_ERR, BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_send_error(), c, ckp_clear_path(), brix_file_t::ckp_path, brix_file_t::ckp_size, close(), brix_file_t::fd, brix_ctx_t::files, fstat(), kXR_ArgTooLong, kXR_ckpMinMax, kXR_inProgress, kXR_IOError, kXR_NoMemory, kXR_overQuota, ngx_memcpy, open(), brix_file_t::path, PATH_MAX, and stat().
Referenced by brix_handle_chkpoint().
ckp_clear_path()
static void ckp_clear_path (brix_file_t * f) static
Definition at line 32 of file chkpoint.c.
References brix_file_t::ckp_path, and brix_file_t::ckp_size.
Referenced by ckp_begin(), ckp_commit(), and ckp_rollback().
ckp_commit()
static ngx_int_t ckp_commit (brix_ctx_t * ctx, ngx_connection_t * c, int idx) static
Definition at line 146 of file chkpoint.c.
References BRIX_OP_CHKPOINT, BRIX_RETURN_ERR, BRIX_RETURN_OK, c, ckp_clear_path(), brix_file_t::ckp_path, brix_ctx_t::files, kXR_InvalidRequest, and brix_file_t::path.
Referenced by brix_handle_chkpoint().
ckp_name_has_suffix()
static ngx_flag_t ckp_name_has_suffix (const char * name) static
Definition at line 290 of file chkpoint.c.
References name.
Referenced by ckp_recover_scan().
ckp_query()
static ngx_int_t ckp_query (brix_ctx_t * ctx, ngx_connection_t * c, int idx) static
Definition at line 208 of file chkpoint.c.
References brix_log_access(), BRIX_OP_CHKPOINT, BRIX_OP_OK, brix_send_ok(), c, brix_file_t::ckp_path, brix_ctx_t::files, kXR_ckpMinMax, kXR_ok, ServerResponseBody_ChkPoint::maxCkpSize, brix_file_t::path, stat(), and ServerResponseBody_ChkPoint::useCkpSize.
Referenced by brix_handle_chkpoint().
ckp_recover_one()
static ngx_int_t ckp_recover_one (ngx_log_t * log, const char * root_canon, const char * ckp_path) static
Definition at line 299 of file chkpoint.c.
References brix_copy_range(), brix_log_safe_path(), brix_staged_abort(), brix_staged_commit(), brix_staged_open(), brix_vfs_io_execute(), brix_vfs_job_sync_init(), brix_vfs_open_fd(), brix_vfs_unlink_path(), brix_staged_file_t::fd, fstat(), log, ngx_memcpy, PATH_MAX, stat(), and brix_staged_file_t::tmp_path.
Referenced by ckp_recover_scan().
ckp_recover_scan()
static ngx_int_t ckp_recover_scan (ngx_log_t * log, const char * root_canon, const char * dir, ngx_uint_t depth) static
Definition at line 389 of file chkpoint.c.
References brix_log_safe_path(), brix_vfs_open_fd(), ckp_name_has_suffix(), ckp_recover_one(), ckp_recover_scan(), fstatat(), log, ngx_memcpy, PATH_MAX, and stat().
Referenced by brix_chkpoint_recover_root(), and ckp_recover_scan().
ckp_rollback()
static ngx_int_t ckp_rollback (brix_ctx_t * ctx, ngx_connection_t * c, int idx) static
Definition at line 163 of file chkpoint.c.
References brix_copy_range(), BRIX_OP_CHKPOINT, BRIX_OP_ERR, BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_send_error(), brix_vfs_io_execute(), brix_vfs_job_truncate_init(), c, ckp_clear_path(), brix_file_t::ckp_path, brix_file_t::ckp_size, close(), brix_file_t::fd, brix_ctx_t::files, brix_vfs_job_t::io_errno, kXR_InvalidRequest, kXR_IOError, open(), and brix_file_t::path.
Referenced by brix_handle_chkpoint().