nginx-xrootd: src/fs/cache/cinfo.c File Reference
cinfo.c File Reference
#include "cinfo.h"
#include "fs/meta/xmeta_path.h"
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/file.h>
#include <sys/stat.h>
#include <sys/xattr.h>
#include <time.h>
#include <unistd.h>
Functions
uint64_t brix_cache_cinfo_nblocks (uint64_t size, uint32_t block_size)
size_t brix_cache_cinfo_bitmap_len (uint64_t nblocks)
void brix_cache_cinfo_mark_block (uint8_t *bitmap, uint64_t blk)
int brix_cache_cinfo_block_present (const uint8_t *bitmap, uint64_t blk)
uint64_t brix_cache_cinfo_present_count (const uint8_t *bitmap, uint64_t nblocks)
void brix_cache_cinfo_refresh_flags (brix_cache_cinfo_t *hdr, const uint8_t *bitmap)
int brix_cache_cinfo_path (char *dst, size_t dstsz, const char *cache_path)
ngx_int_t brix_cache_cinfo_to_xmeta (const brix_cache_cinfo_t *hdr, const uint8_t *bitmap, size_t bitmap_len, brix_xmeta_t *m)
void brix_cache_cinfo_from_xmeta (const brix_xmeta_t *m, brix_cache_cinfo_t *hdr)
static ngx_int_t cinfo_xmeta_read (const char *cache_path, brix_xmeta_t *xm)
static ngx_int_t cinfo_xmeta_write (const char *cache_path, const brix_xmeta_t *xm)
static int cinfo_rmw_lock (const char *cache_path)
static void cinfo_rmw_unlock (int fd)
ngx_int_t brix_cache_cinfo_load (const char *cache_path, brix_cache_cinfo_t *hdr, uint8_t **bitmap, size_t *bitmap_len)
ngx_int_t brix_cache_cinfo_store (const char *cache_path, const brix_cache_cinfo_t *hdr, const uint8_t *bitmap, size_t bitmap_len)
ngx_int_t brix_cache_cinfo_from_meta (const brix_cache_meta_t *m, uint32_t block_size, brix_cache_cinfo_t *out)
static void cinfo_init (brix_cache_cinfo_t *out, uint64_t size, uint32_t block_size, uint64_t mtime)
ngx_int_t brix_cache_cinfo_record_block (const char *cache_path, uint64_t size, uint32_t block_size, uint64_t mtime, uint32_t mode, uint64_t blk, ngx_log_t *log)
static ngx_int_t cinfo_rmw_load (const char *cache_path, uint64_t size, uint32_t block_size, uint64_t mtime, brix_xmeta_t *xm)
ngx_int_t brix_cache_cinfo_mark_dirty (const char *cache_path, uint64_t size, uint32_t block_size, uint64_t mtime, uint64_t off, uint64_t len, ngx_log_t *log)
ngx_int_t brix_cache_cinfo_mark_clean (const char *cache_path, uint64_t bytes, ngx_log_t *log)
ngx_int_t brix_cache_cinfo_dirty_extent (const char *cache_path, uint64_t *lo, uint64_t *hi, uint64_t *dirty_since)
ngx_int_t brix_cache_cinfo_state (const char *cache_path, brix_cache_cinfo_state_t *out)
void brix_cache_cinfo_set_expires (brix_cache_cinfo_t *ci, time_t when)
int brix_cache_cinfo_expired (const brix_cache_cinfo_t *ci, time_t now)
Function Documentation
brix_cache_cinfo_bitmap_len()
size_t brix_cache_cinfo_bitmap_len (uint64_t nblocks)
Definition at line 38 of file cinfo.c.
Referenced by brix_cache_cinfo_load(), brix_cache_cinfo_to_xmeta(), brix_cstore_cinfo_store(), and sd_cache_partial_open().
brix_cache_cinfo_block_present()
int brix_cache_cinfo_block_present (const uint8_t * bitmap, uint64_t blk)
Definition at line 50 of file cinfo.c.
Referenced by brix_cache_cinfo_present_count(), and brix_cstore_serve_pread().
brix_cache_cinfo_dirty_extent()
ngx_int_t brix_cache_cinfo_dirty_extent (const char * cache_path, uint64_t * lo, uint64_t * hi, uint64_t * dirty_since)
Definition at line 508 of file cinfo.c.
References brix_cache_cinfo_load(), BRIX_CINFO_F_DIRTY, brix_cache_cinfo_t::dirty_hi, brix_cache_cinfo_t::dirty_lo, brix_cache_cinfo_t::dirty_since, and brix_cache_cinfo_t::flags.
Referenced by evict_collect_visit().
brix_cache_cinfo_expired()
int brix_cache_cinfo_expired (const brix_cache_cinfo_t * ci, time_t now)
Definition at line 576 of file cinfo.c.
References BRIX_CINFO_F_EXPIRES, brix_cache_cinfo_t::expires_at, and brix_cache_cinfo_t::flags.
Referenced by brix_sd_cache_fill_needs_offload(), and sd_cache_stale_serve_ok().
brix_cache_cinfo_from_meta()
ngx_int_t brix_cache_cinfo_from_meta (const brix_cache_meta_t * m, uint32_t block_size, brix_cache_cinfo_t * out)
Definition at line 293 of file cinfo.c.
References brix_cache_cinfo_t::access_count, brix_cache_meta_t::access_count, brix_cache_cinfo_t::block_size, BRIX_CACHE_CINFO_MAGIC, brix_cache_cinfo_nblocks(), BRIX_CACHE_CINFO_VERSION, BRIX_CINFO_F_COMPLETE, brix_cache_cinfo_t::bytes_served, brix_cache_meta_t::bytes_served, brix_cache_cinfo_t::cks_alg, brix_cache_meta_t::cks_alg, brix_cache_cinfo_t::cks_alg_len, brix_cache_meta_t::cks_alg_len, brix_cache_cinfo_t::cks_hex, brix_cache_meta_t::cks_hex, brix_cache_cinfo_t::cks_len, brix_cache_meta_t::cks_len, brix_cache_cinfo_t::etag, brix_cache_meta_t::etag, brix_cache_cinfo_t::etag_len, brix_cache_meta_t::etag_len, brix_cache_cinfo_t::flags, brix_cache_cinfo_t::last_access, brix_cache_meta_t::last_access, brix_cache_cinfo_t::magic, brix_cache_cinfo_t::mtime, brix_cache_meta_t::mtime, brix_cache_cinfo_t::nblocks, ngx_memcpy, brix_cache_cinfo_t::size, brix_cache_meta_t::size, and brix_cache_cinfo_t::version.
brix_cache_cinfo_from_xmeta()
void brix_cache_cinfo_from_xmeta (const brix_xmeta_t * m, brix_cache_cinfo_t * hdr)
Definition at line 153 of file cinfo.c.
References brix_xmeta_t::access_cnt, brix_cache_cinfo_t::access_count, brix_xmeta_t::astat, brix_xmeta_t::bitmap, brix_cache_cinfo_t::block_size, BRIX_CACHE_CINFO_MAGIC, brix_cache_cinfo_refresh_flags(), BRIX_CACHE_CINFO_VERSION, BRIX_CINFO_F_DIRTY, BRIX_CINFO_F_EXPIRES, BRIX_CINFO_F_VERIFIED, BRIX_XMETA_F_EXPIRES, BRIX_XMETA_F_VERIFIED, brix_xmeta_t::buffer_size, brix_cache_cinfo_t::bytes_flushed, brix_xmeta_t::bytes_flushed, brix_xmeta_astat_t::bytes_hit, brix_cache_cinfo_t::bytes_served, brix_cache_cinfo_t::cks_alg, brix_xmeta_t::cks_alg, brix_cache_cinfo_t::cks_alg_len, brix_xmeta_t::cks_alg_len, brix_cache_cinfo_t::cks_hex, brix_xmeta_t::cks_hex, brix_cache_cinfo_t::cks_len, brix_xmeta_t::cks_len, brix_xmeta_astat_t::detach_time, brix_cache_cinfo_t::dirty_hi, brix_xmeta_t::dirty_hi, brix_cache_cinfo_t::dirty_lo, brix_xmeta_t::dirty_lo, brix_cache_cinfo_t::dirty_since, brix_xmeta_t::dirty_since, brix_xmeta_t::etag, brix_cache_cinfo_t::etag, brix_cache_cinfo_t::etag_len, brix_xmeta_t::etag_len, brix_cache_cinfo_t::expires_at, brix_xmeta_t::expires_at, brix_xmeta_t::file_size, brix_cache_cinfo_t::filled_at, brix_xmeta_t::filled_at, brix_cache_cinfo_t::flags, brix_cache_cinfo_t::flush_gen, brix_xmeta_t::flush_gen, brix_cache_cinfo_t::last_access, brix_cache_cinfo_t::last_flush, brix_xmeta_t::last_flush, brix_cache_cinfo_t::magic, brix_cache_cinfo_t::mode, brix_xmeta_t::mode, brix_cache_cinfo_t::mtime, brix_cache_cinfo_t::nblocks, brix_xmeta_t::nblocks, ngx_memcpy, brix_xmeta_t::origin_mtime, brix_cache_cinfo_t::size, brix_xmeta_t::state_flags, and brix_cache_cinfo_t::version.
Referenced by brix_cache_cinfo_load(), brix_cache_cinfo_record_block(), and brix_cstore_cinfo_load().
brix_cache_cinfo_load()
ngx_int_t brix_cache_cinfo_load (const char * cache_path, brix_cache_cinfo_t * hdr, uint8_t ** bitmap, size_t * bitmap_len)
Definition at line 234 of file cinfo.c.
References brix_xmeta_t::bitmap, brix_cache_cinfo_bitmap_len(), brix_cache_cinfo_from_xmeta(), brix_xmeta_free(), cinfo_xmeta_read(), brix_cache_cinfo_t::nblocks, and ngx_memcpy.
Referenced by brix_cache_cinfo_dirty_extent(), brix_cache_cinfo_state(), brix_cstore_cinfo_load(), brix_cstore_cinfo_store(), and sd_cache_partial_open().
brix_cache_cinfo_mark_block()
void brix_cache_cinfo_mark_block (uint8_t * bitmap, uint64_t blk)
Definition at line 44 of file cinfo.c.
Referenced by sd_cache_fill_block().
brix_cache_cinfo_mark_clean()
ngx_int_t brix_cache_cinfo_mark_clean (const char * cache_path, uint64_t bytes, ngx_log_t * log)
Definition at line 471 of file cinfo.c.
References brix_xmeta_free(), brix_xmeta_t::bytes_flushed, cinfo_rmw_lock(), cinfo_rmw_unlock(), cinfo_xmeta_read(), cinfo_xmeta_write(), brix_xmeta_t::dirty_hi, brix_xmeta_t::dirty_lo, brix_xmeta_t::dirty_since, brix_xmeta_t::flush_gen, brix_xmeta_t::last_flush, and log.
brix_cache_cinfo_mark_dirty()
ngx_int_t brix_cache_cinfo_mark_dirty (const char * cache_path, uint64_t size, uint32_t block_size, uint64_t mtime, uint64_t off, uint64_t len, ngx_log_t * log)
Definition at line 428 of file cinfo.c.
References brix_xmeta_free(), cinfo_rmw_load(), cinfo_rmw_lock(), cinfo_rmw_unlock(), cinfo_xmeta_write(), brix_xmeta_t::dirty_hi, brix_xmeta_t::dirty_lo, brix_xmeta_t::dirty_since, and log.
brix_cache_cinfo_nblocks()
uint64_t brix_cache_cinfo_nblocks (uint64_t size, uint32_t block_size)
Definition at line 29 of file cinfo.c.
Referenced by brix_cache_cinfo_from_meta(), brix_cache_cinfo_record_block(), cinfo_init(), sd_cache_fill(), and sd_cache_partial_open().
brix_cache_cinfo_path()
int brix_cache_cinfo_path (char * dst, size_t dstsz, const char * cache_path)
Definition at line 90 of file cinfo.c.
Referenced by brix_cstore_evict(), and reap_unlink_sidecars().
brix_cache_cinfo_present_count()
uint64_t brix_cache_cinfo_present_count (const uint8_t * bitmap, uint64_t nblocks)
Definition at line 56 of file cinfo.c.
References brix_cache_cinfo_block_present().
Referenced by brix_cache_cinfo_refresh_flags().
brix_cache_cinfo_record_block()
ngx_int_t brix_cache_cinfo_record_block (const char * cache_path, uint64_t size, uint32_t block_size, uint64_t mtime, uint32_t mode, uint64_t blk, ngx_log_t * log)
Definition at line 341 of file cinfo.c.
References brix_cache_cinfo_from_xmeta(), brix_cache_cinfo_nblocks(), brix_cache_cinfo_to_xmeta(), brix_xmeta_block_set(), brix_xmeta_free(), brix_xmeta_t::buffer_size, cinfo_init(), cinfo_rmw_lock(), cinfo_rmw_unlock(), cinfo_xmeta_read(), cinfo_xmeta_write(), brix_xmeta_t::file_size, log, mode, brix_xmeta_t::mode, and brix_xmeta_t::origin_mtime.
Referenced by sd_cache_fill_block().
brix_cache_cinfo_refresh_flags()
void brix_cache_cinfo_refresh_flags (brix_cache_cinfo_t * hdr, const uint8_t * bitmap)
Definition at line 70 of file cinfo.c.
References brix_cache_cinfo_present_count(), BRIX_CINFO_F_COMPLETE, BRIX_CINFO_F_PARTIAL, brix_cache_cinfo_t::flags, and brix_cache_cinfo_t::nblocks.
Referenced by brix_cache_cinfo_from_xmeta().
brix_cache_cinfo_set_expires()
void brix_cache_cinfo_set_expires (brix_cache_cinfo_t * ci, time_t when)
Definition at line 569 of file cinfo.c.
References BRIX_CINFO_F_EXPIRES, brix_cache_cinfo_t::expires_at, and brix_cache_cinfo_t::flags.
Referenced by sd_cache_fill(), and sd_cache_stale_serve_ok().
brix_cache_cinfo_state()
ngx_int_t brix_cache_cinfo_state (const char * cache_path, brix_cache_cinfo_state_t * out)
Definition at line 538 of file cinfo.c.
References brix_cache_cinfo_load(), BRIX_CINFO_F_DIRTY, brix_cache_cinfo_t::dirty_hi, brix_cache_cinfo_state_t::dirty_hi, brix_cache_cinfo_t::dirty_lo, brix_cache_cinfo_state_t::dirty_lo, brix_cache_cinfo_t::dirty_since, brix_cache_cinfo_state_t::dirty_since, brix_cache_cinfo_t::flags, brix_cache_cinfo_t::flush_gen, brix_cache_cinfo_state_t::flush_gen, brix_cache_cinfo_state_t::is_dirty, brix_cache_cinfo_t::last_flush, and brix_cache_cinfo_state_t::last_flush.
Referenced by reap_dir().
brix_cache_cinfo_store()
ngx_int_t brix_cache_cinfo_store (const char * cache_path, const brix_cache_cinfo_t * hdr, const uint8_t * bitmap, size_t bitmap_len)
Definition at line 274 of file cinfo.c.
References brix_cache_cinfo_to_xmeta(), brix_xmeta_free(), and cinfo_xmeta_write().
Referenced by brix_cstore_cinfo_store().
brix_cache_cinfo_to_xmeta()
ngx_int_t brix_cache_cinfo_to_xmeta (const brix_cache_cinfo_t * hdr, const uint8_t * bitmap, size_t bitmap_len, brix_xmeta_t * m)
Definition at line 99 of file cinfo.c.
References brix_xmeta_t::access_cnt, brix_cache_cinfo_t::access_count, brix_xmeta_t::astat, brix_xmeta_t::astat_count, brix_xmeta_astat_t::attach_time, brix_xmeta_t::bitmap, brix_cache_cinfo_t::block_size, brix_cache_cinfo_bitmap_len(), BRIX_CACHE_DIRTY_BLOCK, BRIX_CINFO_F_COMPLETE, BRIX_CINFO_F_EXPIRES, BRIX_CINFO_F_VERIFIED, BRIX_XMETA_F_EXPIRES, BRIX_XMETA_F_VERIFIED, brix_xmeta_init(), BRIX_XMETA_OK, brix_cache_cinfo_t::bytes_flushed, brix_xmeta_t::bytes_flushed, brix_xmeta_astat_t::bytes_hit, brix_cache_cinfo_t::bytes_served, brix_cache_cinfo_t::cks_alg, brix_xmeta_t::cks_alg, brix_cache_cinfo_t::cks_alg_len, brix_xmeta_t::cks_alg_len, brix_cache_cinfo_t::cks_hex, brix_xmeta_t::cks_hex, brix_cache_cinfo_t::cks_len, brix_xmeta_t::cks_len, brix_xmeta_astat_t::detach_time, brix_cache_cinfo_t::dirty_hi, brix_xmeta_t::dirty_hi, brix_cache_cinfo_t::dirty_lo, brix_xmeta_t::dirty_lo, brix_cache_cinfo_t::dirty_since, brix_xmeta_t::dirty_since, brix_xmeta_t::etag, brix_cache_cinfo_t::etag, brix_cache_cinfo_t::etag_len, brix_xmeta_t::etag_len, brix_cache_cinfo_t::expires_at, brix_xmeta_t::expires_at, brix_cache_cinfo_t::filled_at, brix_xmeta_t::filled_at, brix_cache_cinfo_t::flags, brix_cache_cinfo_t::flush_gen, brix_xmeta_t::flush_gen, brix_xmeta_t::have_blockcrc, brix_cache_cinfo_t::last_access, brix_cache_cinfo_t::last_flush, brix_xmeta_t::last_flush, brix_cache_cinfo_t::mode, brix_xmeta_t::mode, brix_cache_cinfo_t::mtime, brix_xmeta_t::nblocks, ngx_memcpy, brix_xmeta_t::origin_mtime, brix_cache_cinfo_t::size, and brix_xmeta_t::state_flags.
Referenced by brix_cache_cinfo_record_block(), brix_cache_cinfo_store(), brix_cstore_cinfo_store(), and cinfo_rmw_load().
cinfo_init()
static void cinfo_init (brix_cache_cinfo_t * out, uint64_t size, uint32_t block_size, uint64_t mtime) static
Definition at line 328 of file cinfo.c.
References brix_cache_cinfo_t::block_size, BRIX_CACHE_CINFO_MAGIC, brix_cache_cinfo_nblocks(), BRIX_CACHE_CINFO_VERSION, brix_cache_cinfo_t::magic, brix_cache_cinfo_t::mtime, brix_cache_cinfo_t::nblocks, brix_cache_cinfo_t::size, and brix_cache_cinfo_t::version.
Referenced by brix_cache_cinfo_record_block(), and cinfo_rmw_load().
cinfo_rmw_load()
static ngx_int_t cinfo_rmw_load (const char * cache_path, uint64_t size, uint32_t block_size, uint64_t mtime, brix_xmeta_t * xm) static
Definition at line 409 of file cinfo.c.
References brix_cache_cinfo_to_xmeta(), brix_xmeta_free(), brix_xmeta_t::buffer_size, cinfo_init(), cinfo_xmeta_read(), brix_xmeta_t::file_size, and brix_xmeta_t::origin_mtime.
Referenced by brix_cache_cinfo_mark_dirty().
cinfo_rmw_lock()
static int cinfo_rmw_lock (const char * cache_path) static
Definition at line 222 of file cinfo.c.
References brix_xmeta_path_lock().
Referenced by brix_cache_cinfo_mark_clean(), brix_cache_cinfo_mark_dirty(), and brix_cache_cinfo_record_block().
cinfo_rmw_unlock()
static void cinfo_rmw_unlock (int fd) static
Definition at line 228 of file cinfo.c.
References brix_xmeta_path_unlock().
Referenced by brix_cache_cinfo_mark_clean(), brix_cache_cinfo_mark_dirty(), and brix_cache_cinfo_record_block().
cinfo_xmeta_read()
static ngx_int_t cinfo_xmeta_read (const char * cache_path, brix_xmeta_t * xm) static
Definition at line 204 of file cinfo.c.
References BRIX_XMETA_FOREIGN, BRIX_XMETA_OK, and brix_xmeta_path_load().
Referenced by brix_cache_cinfo_load(), brix_cache_cinfo_mark_clean(), brix_cache_cinfo_record_block(), and cinfo_rmw_load().
cinfo_xmeta_write()
static ngx_int_t cinfo_xmeta_write (const char * cache_path, const brix_xmeta_t * xm) static
Definition at line 215 of file cinfo.c.
References BRIX_XMETA_OK, and brix_xmeta_path_save().
Referenced by brix_cache_cinfo_mark_clean(), brix_cache_cinfo_mark_dirty(), brix_cache_cinfo_record_block(), and brix_cache_cinfo_store().