nginx-xrootd: src/fs/cache/cinfo_l1.h File Reference
cinfo_l1.h File Reference
#include <ngx_core.h>
#include "cinfo.h"
Data Structures
struct brix_cinfo_l1_t
Functions
brix_cinfo_l1_t * brix_cinfo_l1_create (size_t max_entries, ngx_log_t *log)
void brix_cinfo_l1_destroy (brix_cinfo_l1_t *l1)
ngx_int_t brix_cinfo_l1_get (brix_cinfo_l1_t *l1, const char *key, brix_cache_cinfo_t *out)
void brix_cinfo_l1_put (brix_cinfo_l1_t *l1, const char *key, const brix_cache_cinfo_t *hdr)
void brix_cinfo_l1_drop (brix_cinfo_l1_t *l1, const char *key)
Function Documentation
brix_cinfo_l1_create()
brix_cinfo_l1_t * brix_cinfo_l1_create (size_t max_entries, ngx_log_t * log)
Definition at line 165 of file cinfo_l1.c.
References cinfo_l1_impl_t::buckets, CINFO_L1_DEFAULT_ENTRIES, cinfo_l1_pow2_ceil(), log, cinfo_l1_impl_t::log, cinfo_l1_impl_t::mask, cinfo_l1_impl_t::max, cinfo_l1_impl_t::mtx, cinfo_l1_impl_t::nbuckets, and brix_cinfo_l1_t::opaque.
Referenced by brix_cstore_init().
brix_cinfo_l1_destroy()
void brix_cinfo_l1_destroy (brix_cinfo_l1_t * l1)
Definition at line 204 of file cinfo_l1.c.
References cinfo_l1_impl_t::buckets, cinfo_l1_entry_t::key, cinfo_l1_impl_t::lru_head, cinfo_l1_entry_t::lru_next, cinfo_l1_impl_t::mtx, and brix_cinfo_l1_t::opaque.
Referenced by brix_cstore_cleanup().
brix_cinfo_l1_drop()
void brix_cinfo_l1_drop (brix_cinfo_l1_t * l1, const char * key)
Definition at line 300 of file cinfo_l1.c.
References cinfo_l1_bucket_remove(), cinfo_l1_find(), cinfo_l1_hash(), cinfo_l1_lru_unlink(), cinfo_l1_impl_t::count, cinfo_l1_entry_t::key, key, cinfo_l1_impl_t::mask, cinfo_l1_impl_t::mtx, and brix_cinfo_l1_t::opaque.
Referenced by brix_cstore_evict().
brix_cinfo_l1_get()
ngx_int_t brix_cinfo_l1_get (brix_cinfo_l1_t * l1, const char * key, brix_cache_cinfo_t * out)
Definition at line 229 of file cinfo_l1.c.
References cinfo_l1_find(), cinfo_l1_hash(), cinfo_l1_touch(), cinfo_l1_entry_t::hdr, key, cinfo_l1_impl_t::mask, cinfo_l1_impl_t::mtx, and brix_cinfo_l1_t::opaque.
Referenced by brix_cstore_cinfo_load().
brix_cinfo_l1_put()
void brix_cinfo_l1_put (brix_cinfo_l1_t * l1, const char * key, const brix_cache_cinfo_t * hdr)
Definition at line 254 of file cinfo_l1.c.
References cinfo_l1_impl_t::buckets, cinfo_l1_evict_tail(), cinfo_l1_find(), cinfo_l1_hash(), cinfo_l1_lru_push_front(), cinfo_l1_touch(), cinfo_l1_impl_t::count, cinfo_l1_entry_t::hdr, cinfo_l1_entry_t::hnext, cinfo_l1_entry_t::key, key, cinfo_l1_impl_t::mask, cinfo_l1_impl_t::max, cinfo_l1_impl_t::mtx, and brix_cinfo_l1_t::opaque.
Referenced by brix_cstore_cinfo_load(), and brix_cstore_cinfo_store().