nginx-xrootd: src/fs/cache/cinfo_l1.c File Reference
cinfo_l1.c File Reference
#include "cinfo_l1.h"
#include <errno.h>
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct cinfo_l1_entry_t
struct cinfo_l1_impl_t
Macros
#define CINFO_L1_DEFAULT_ENTRIES 4096
Functions
static size_t cinfo_l1_pow2_ceil (size_t n)
static uint64_t cinfo_l1_hash (const char *key)
static void cinfo_l1_lru_unlink (cinfo_l1_impl_t *t, cinfo_l1_entry_t *e)
static void cinfo_l1_lru_push_front (cinfo_l1_impl_t *t, cinfo_l1_entry_t *e)
static void cinfo_l1_touch (cinfo_l1_impl_t *t, cinfo_l1_entry_t *e)
static cinfo_l1_entry_t * cinfo_l1_find (cinfo_l1_impl_t *t, const char *key, size_t bucket)
static void cinfo_l1_bucket_remove (cinfo_l1_impl_t *t, cinfo_l1_entry_t *e, size_t bucket)
static void cinfo_l1_evict_tail (cinfo_l1_impl_t *t)
brix_cinfo_l1_t * brix_cinfo_l1_create (size_t max_entries, ngx_log_t *log)
void brix_cinfo_l1_destroy (brix_cinfo_l1_t *l1)
ngx_int_t brix_cinfo_l1_get (brix_cinfo_l1_t *l1, const char *key, brix_cache_cinfo_t *out)
void brix_cinfo_l1_put (brix_cinfo_l1_t *l1, const char *key, const brix_cache_cinfo_t *hdr)
void brix_cinfo_l1_drop (brix_cinfo_l1_t *l1, const char *key)
Macro Definition Documentation
CINFO_L1_DEFAULT_ENTRIES
#define CINFO_L1_DEFAULT_ENTRIES 4096
Definition at line 16 of file cinfo_l1.c.
Function Documentation
brix_cinfo_l1_create()
brix_cinfo_l1_t * brix_cinfo_l1_create (size_t max_entries, ngx_log_t * log)
Definition at line 165 of file cinfo_l1.c.
References cinfo_l1_impl_t::buckets, CINFO_L1_DEFAULT_ENTRIES, cinfo_l1_pow2_ceil(), log, cinfo_l1_impl_t::log, cinfo_l1_impl_t::mask, cinfo_l1_impl_t::max, cinfo_l1_impl_t::mtx, cinfo_l1_impl_t::nbuckets, and brix_cinfo_l1_t::opaque.
Referenced by brix_cstore_init().
brix_cinfo_l1_destroy()
void brix_cinfo_l1_destroy (brix_cinfo_l1_t * l1)
Definition at line 204 of file cinfo_l1.c.
References cinfo_l1_impl_t::buckets, cinfo_l1_entry_t::key, cinfo_l1_impl_t::lru_head, cinfo_l1_entry_t::lru_next, cinfo_l1_impl_t::mtx, and brix_cinfo_l1_t::opaque.
Referenced by brix_cstore_cleanup().
brix_cinfo_l1_drop()
void brix_cinfo_l1_drop (brix_cinfo_l1_t * l1, const char * key)
Definition at line 300 of file cinfo_l1.c.
References cinfo_l1_bucket_remove(), cinfo_l1_find(), cinfo_l1_hash(), cinfo_l1_lru_unlink(), cinfo_l1_impl_t::count, cinfo_l1_entry_t::key, key, cinfo_l1_impl_t::mask, cinfo_l1_impl_t::mtx, and brix_cinfo_l1_t::opaque.
Referenced by brix_cstore_evict().
brix_cinfo_l1_get()
ngx_int_t brix_cinfo_l1_get (brix_cinfo_l1_t * l1, const char * key, brix_cache_cinfo_t * out)
Definition at line 229 of file cinfo_l1.c.
References cinfo_l1_find(), cinfo_l1_hash(), cinfo_l1_touch(), cinfo_l1_entry_t::hdr, key, cinfo_l1_impl_t::mask, cinfo_l1_impl_t::mtx, and brix_cinfo_l1_t::opaque.
Referenced by brix_cstore_cinfo_load().
brix_cinfo_l1_put()
void brix_cinfo_l1_put (brix_cinfo_l1_t * l1, const char * key, const brix_cache_cinfo_t * hdr)
Definition at line 254 of file cinfo_l1.c.
References cinfo_l1_impl_t::buckets, cinfo_l1_evict_tail(), cinfo_l1_find(), cinfo_l1_hash(), cinfo_l1_lru_push_front(), cinfo_l1_touch(), cinfo_l1_impl_t::count, cinfo_l1_entry_t::hdr, cinfo_l1_entry_t::hnext, cinfo_l1_entry_t::key, key, cinfo_l1_impl_t::mask, cinfo_l1_impl_t::max, cinfo_l1_impl_t::mtx, and brix_cinfo_l1_t::opaque.
Referenced by brix_cstore_cinfo_load(), and brix_cstore_cinfo_store().
cinfo_l1_bucket_remove()
static void cinfo_l1_bucket_remove (cinfo_l1_impl_t * t, cinfo_l1_entry_t * e, size_t bucket) static
Definition at line 132 of file cinfo_l1.c.
References cinfo_l1_impl_t::buckets, and cinfo_l1_entry_t::hnext.
Referenced by brix_cinfo_l1_drop(), and cinfo_l1_evict_tail().
cinfo_l1_evict_tail()
static void cinfo_l1_evict_tail (cinfo_l1_impl_t * t) static
Definition at line 146 of file cinfo_l1.c.
References cinfo_l1_bucket_remove(), cinfo_l1_hash(), cinfo_l1_lru_unlink(), cinfo_l1_impl_t::count, cinfo_l1_entry_t::key, cinfo_l1_impl_t::lru_tail, and cinfo_l1_impl_t::mask.
Referenced by brix_cinfo_l1_put().
cinfo_l1_find()
static cinfo_l1_entry_t * cinfo_l1_find (cinfo_l1_impl_t * t, const char * key, size_t bucket) static
Definition at line 118 of file cinfo_l1.c.
References cinfo_l1_impl_t::buckets, cinfo_l1_entry_t::hnext, cinfo_l1_entry_t::key, and key.
Referenced by brix_cinfo_l1_drop(), brix_cinfo_l1_get(), and brix_cinfo_l1_put().
cinfo_l1_hash()
static uint64_t cinfo_l1_hash (const char * key) static
Definition at line 59 of file cinfo_l1.c.
References key.
Referenced by brix_cinfo_l1_drop(), brix_cinfo_l1_get(), brix_cinfo_l1_put(), and cinfo_l1_evict_tail().
cinfo_l1_lru_push_front()
static void cinfo_l1_lru_push_front (cinfo_l1_impl_t * t, cinfo_l1_entry_t * e) static
Definition at line 91 of file cinfo_l1.c.
References cinfo_l1_impl_t::lru_head, cinfo_l1_entry_t::lru_next, cinfo_l1_entry_t::lru_prev, and cinfo_l1_impl_t::lru_tail.
Referenced by brix_cinfo_l1_put(), and cinfo_l1_touch().
cinfo_l1_lru_unlink()
static void cinfo_l1_lru_unlink (cinfo_l1_impl_t * t, cinfo_l1_entry_t * e) static
Definition at line 74 of file cinfo_l1.c.
References cinfo_l1_impl_t::lru_head, cinfo_l1_entry_t::lru_next, cinfo_l1_entry_t::lru_prev, and cinfo_l1_impl_t::lru_tail.
Referenced by brix_cinfo_l1_drop(), cinfo_l1_evict_tail(), and cinfo_l1_touch().
cinfo_l1_pow2_ceil()
static size_t cinfo_l1_pow2_ceil (size_t n) static
Definition at line 47 of file cinfo_l1.c.
Referenced by brix_cinfo_l1_create().
cinfo_l1_touch()
static void cinfo_l1_touch (cinfo_l1_impl_t * t, cinfo_l1_entry_t * e) static
Definition at line 106 of file cinfo_l1.c.
References cinfo_l1_lru_push_front(), cinfo_l1_lru_unlink(), and cinfo_l1_impl_t::lru_head.
Referenced by brix_cinfo_l1_get(), and brix_cinfo_l1_put().