nginx-xrootd: client/lib/protocols/shared/cks_verify.c File Reference
cks_verify.c File Reference
#include "brix.h"
#include <errno.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/xattr.h>
#include <unistd.h>
Data Structures
struct ckv_cksdata
struct ckv_meta
struct ckv_record
Macros
#define CKV_XATTR_PREFIX "user.XrdCks."
#define CKV_MAX_RECORDS 16
#define CKV_XMETA_XATTR "user.xrd.cinfo"
#define CKV_XMETA_VERSION 4
#define CKV_XMETA_EXT_MAGIC 0x31584358u /* "XCX1" */
#define CKV_XMETA_SEC_ORIGIN 0x0004u
#define CKV_XMETA_MAX (64 * 1024)
Functions
static void ckv_bin_to_hex (const unsigned char *bin, int len, char *out, size_t outsz)
static int ckv_decode_xattr_value (const char *algo, const char *val, size_t vlen, ckv_record *rec)
static void ckv_collect_xattr (const char *path, ckv_record *recs, size_t max, size_t *n)
static void ckv_collect_sidecar (const char *path, ckv_record *recs, size_t max, size_t *n)
static int ckv_read_sidecar_blob (const char *path, const char *suffix, void *buf, size_t sz)
static void ckv_add_cache_record (const char *src, const char *cks_alg, uint8_t cks_alg_len, const char *cks_hex, uint8_t cks_len, ckv_record *recs, size_t max, size_t *n)
static uint16_t ckv_rd_u16 (const uint8_t *b, size_t off)
static uint32_t ckv_rd_u32 (const uint8_t *b, size_t off)
static uint64_t ckv_rd_u64 (const uint8_t *b, size_t off)
static int ckv_xmeta_origin (const uint8_t *buf, size_t n, ckv_record *rec)
static ssize_t ckv_read_xmeta (const char *path, uint8_t *buf, size_t cap)
static void ckv_collect_cache (const char *path, ckv_record *recs, size_t max, size_t *n)
static void ckv_collect_records (const char *path, brix_ckv_mode mode, ckv_record *recs, size_t max, size_t *n)
static int ckv_verify_one (int fd, const ckv_record *rec, const char *path, const char *want_algo, char comp[][XRDC_CKV_HEX_MAX], int *comp_done, brix_ckv_report *rep, brix_status *st, int *matched, int *unsupported, brix_ckv_result *out)
brix_ckv_result brix_cks_verify_file (const char *path, const char *want_algo, brix_ckv_mode mode, brix_ckv_report *rep, brix_status *st)
Macro Definition Documentation
CKV_MAX_RECORDS
#define CKV_MAX_RECORDS 16
Definition at line 41 of file cks_verify.c.
CKV_XATTR_PREFIX
#define CKV_XATTR_PREFIX "user.XrdCks."
Definition at line 40 of file cks_verify.c.
CKV_XMETA_EXT_MAGIC
#define CKV_XMETA_EXT_MAGIC 0x31584358u /* "XCX1" */
Definition at line 80 of file cks_verify.c.
CKV_XMETA_MAX
#define CKV_XMETA_MAX (64 * 1024)
Definition at line 82 of file cks_verify.c.
CKV_XMETA_SEC_ORIGIN
#define CKV_XMETA_SEC_ORIGIN 0x0004u
Definition at line 81 of file cks_verify.c.
CKV_XMETA_VERSION
#define CKV_XMETA_VERSION 4
Definition at line 79 of file cks_verify.c.
CKV_XMETA_XATTR
#define CKV_XMETA_XATTR "user.xrd.cinfo"
Definition at line 78 of file cks_verify.c.
Function Documentation
brix_cks_verify_file()
brix_ckv_result brix_cks_verify_file (const char * path, const char * want_algo, brix_ckv_mode mode, brix_ckv_report * rep, brix_status * st)
Definition at line 474 of file cks_verify.c.
References brix_status_set(), ckv_collect_records(), CKV_MAX_RECORDS, ckv_verify_one(), close(), open(), XRDC_CK_ZCRC32, XRDC_CKV_ERROR, XRDC_CKV_HEX_MAX, XRDC_CKV_NO_RECORD, XRDC_CKV_OK, XRDC_CKV_UNSUPPORTED, XRDC_ESOCK, and XRDC_EUSAGE.
Referenced by brix_xrdckverify_main().
ckv_add_cache_record()
static void ckv_add_cache_record (const char * src, const char * cks_alg, uint8_t cks_alg_len, const char * cks_hex, uint8_t cks_len, ckv_record * recs, size_t max, size_t * n) static
Definition at line 220 of file cks_verify.c.
References hex().
Referenced by ckv_collect_cache().
ckv_bin_to_hex()
static void ckv_bin_to_hex (const unsigned char * bin, int len, char * out, size_t outsz) static
Definition at line 92 of file cks_verify.c.
Referenced by ckv_decode_xattr_value().
ckv_collect_cache()
static void ckv_collect_cache (const char * path, ckv_record * recs, size_t max, size_t * n) static
Definition at line 350 of file cks_verify.c.
References ckv_meta::cks_alg, ckv_meta::cks_alg_len, ckv_meta::cks_hex, ckv_meta::cks_len, ckv_add_cache_record(), ckv_read_sidecar_blob(), ckv_read_xmeta(), CKV_XMETA_MAX, ckv_xmeta_origin(), and ckv_meta::version.
Referenced by ckv_collect_records().
ckv_collect_records()
static void ckv_collect_records (const char * path, brix_ckv_mode mode, ckv_record * recs, size_t max, size_t * n) static
Definition at line 393 of file cks_verify.c.
References ckv_collect_cache(), ckv_collect_sidecar(), ckv_collect_xattr(), XRDC_CKV_AUTO, XRDC_CKV_CACHE, and XRDC_CKV_STORAGE.
Referenced by brix_cks_verify_file().
ckv_collect_sidecar()
static void ckv_collect_sidecar (const char * path, ckv_record * recs, size_t max, size_t * n) static
Definition at line 169 of file cks_verify.c.
References hex(), XRDC_CKV_HEX_MAX, and XRDC_PATH_MAX.
Referenced by ckv_collect_records().
ckv_collect_xattr()
static void ckv_collect_xattr (const char * path, ckv_record * recs, size_t max, size_t * n) static
Definition at line 139 of file cks_verify.c.
References ckv_decode_xattr_value(), CKV_XATTR_PREFIX, and key.
Referenced by ckv_collect_records().
ckv_decode_xattr_value()
static int ckv_decode_xattr_value (const char * algo, const char * val, size_t vlen, ckv_record * rec) static
Definition at line 110 of file cks_verify.c.
References ckv_record::algo, ckv_bin_to_hex(), hex(), ckv_record::hex, ckv_cksdata::Length, ckv_record::src, ckv_cksdata::Value, and XRDC_CKV_HEX_MAX.
Referenced by ckv_collect_xattr().
ckv_rd_u16()
static uint16_t ckv_rd_u16 (const uint8_t * b, size_t off) static
Definition at line 236 of file cks_verify.c.
Referenced by ckv_xmeta_origin().
ckv_rd_u32()
static uint32_t ckv_rd_u32 (const uint8_t * b, size_t off) static
Definition at line 242 of file cks_verify.c.
Referenced by ckv_xmeta_origin().
ckv_rd_u64()
static uint64_t ckv_rd_u64 (const uint8_t * b, size_t off) static
Definition at line 249 of file cks_verify.c.
Referenced by ckv_xmeta_origin().
ckv_read_sidecar_blob()
static int ckv_read_sidecar_blob (const char * path, const char * suffix, void * buf, size_t sz) static
Definition at line 199 of file cks_verify.c.
References close(), open(), pread(), and XRDC_PATH_MAX.
Referenced by ckv_collect_cache().
ckv_read_xmeta()
static ssize_t ckv_read_xmeta (const char * path, uint8_t * buf, size_t cap) static
Definition at line 325 of file cks_verify.c.
References CKV_XMETA_XATTR, close(), open(), pread(), and XRDC_PATH_MAX.
Referenced by ckv_collect_cache().
ckv_verify_one()
static int ckv_verify_one (int fd, const ckv_record * rec, const char * path, const char * want_algo, char comp[][XRDC_CKV_HEX_MAX], int * comp_done, brix_ckv_report * rep, brix_status * st, int * matched, int * unsupported, brix_ckv_result * out) static
Definition at line 431 of file cks_verify.c.
References alg, brix_ckv_report::algo, ckv_record::algo, brix_cksum_algo_parse(), brix_cksum_fd(), brix_status_set(), brix_ckv_report::computed, ckv_record::hex, lseek(), brix_ckv_report::recorded, brix_ckv_report::source, ckv_record::src, XRDC_CK_ZCRC32, XRDC_CKV_ERROR, XRDC_CKV_HEX_MAX, XRDC_CKV_MISMATCH, and XRDC_EINTEGRITY.
Referenced by brix_cks_verify_file().
ckv_xmeta_origin()
static int ckv_xmeta_origin (const uint8_t * buf, size_t n, ckv_record * rec) static
Definition at line 266 of file cks_verify.c.
References ckv_record::algo, ckv_rd_u16(), ckv_rd_u32(), ckv_rd_u64(), CKV_XMETA_EXT_MAGIC, CKV_XMETA_SEC_ORIGIN, CKV_XMETA_VERSION, ckv_record::hex, and ckv_record::src.
Referenced by ckv_collect_cache().