nginx-xrootd: client/lib/protocols/shared/cksum_manifest.c File Reference
cksum_manifest.c File Reference
#include "brix.h"
#include "brix_ops.h"
#include <ctype.h>
#include <string.h>
Functions
int brix_ckmf_parse_line (const char *line, char *hex, size_t hexsz, char *rel, size_t relsz)
Function Documentation
brix_ckmf_parse_line()
int brix_ckmf_parse_line (const char * line, char * hex, size_t hexsz, char * rel, size_t relsz)
Definition at line 39 of file cksum_manifest.c.
References brix_rel_is_unsafe(), and hex().
Referenced by ckcheck_process_line().