nginx-xrootd: client/lib/cli/cli_opts.c File Reference
cli_opts.c File Reference
#include "brix.h"
#include "brix_ops.h"
#include "core/version.h"
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct opts_toggle_t
Functions
static const char * opts_basename (const char *path)
void brix_opts_init (brix_opts *o)
static int opts_parse_universal (const char *a, char **argv)
static int opts_parse_toggle (brix_opts *o, const char *a)
static int opts_parse_valued (brix_opts *o, int argc, char **argv, int *i)
int brix_opts_parse_arg (brix_opts *o, int argc, char **argv, int *i)
int brix_cli_parse_io_uring (const char *s)
Variables
static const opts_toggle_t opts_toggles []
Function Documentation
brix_cli_parse_io_uring()
int brix_cli_parse_io_uring (const char * s)
Definition at line 217 of file cli_opts.c.
References s, XRDC_IO_URING_AUTO, XRDC_IO_URING_OFF, and XRDC_IO_URING_ON.
Referenced by xfer_common_arg(), and xrdcp_parse_transport_option().
brix_opts_init()
void brix_opts_init (brix_opts * o)
Definition at line 46 of file cli_opts.c.
References brix_opts::max_stall_ms, brix_opts::no_retry, and brix_opts::verify_host.
Referenced by main().
brix_opts_parse_arg()
int brix_opts_parse_arg (brix_opts * o, int argc, char ** argv, int * i)
Definition at line 179 of file cli_opts.c.
References opts_parse_toggle(), opts_parse_universal(), and opts_parse_valued().
Referenced by dx_parse_argv(), main(), and xrdcp_parse_option().
opts_basename()
static const char * opts_basename (const char * path) static
Definition at line 39 of file cli_opts.c.
References s.
Referenced by opts_parse_universal().
opts_parse_toggle()
static int opts_parse_toggle (brix_opts * o, const char * a) static
Definition at line 124 of file cli_opts.c.
References opts_toggle_t::field_off, name, and opts_toggles.
Referenced by brix_opts_parse_arg().
opts_parse_universal()
static int opts_parse_universal (const char * a, char ** argv) static
Definition at line 77 of file cli_opts.c.
References brix_client_version(), and opts_basename().
Referenced by brix_opts_parse_arg().
opts_parse_valued()
static int opts_parse_valued (brix_opts * o, int argc, char ** argv, int * i) static
Definition at line 149 of file cli_opts.c.
References brix_opts::auth_force, brix_opts::capture, brix_opts::max_stall_ms, brix_opts::no_retry, and brix_opts::wire_trace.
Referenced by brix_opts_parse_arg().
Variable Documentation
opts_toggles
const opts_toggle_t opts_toggles[] static
Initial value:
= {
    { "--tls",            offsetof(brix_opts, want_tls),    1 },
    { "--notlsok",        offsetof(brix_opts, notlsok),     1 },
    { "--noverifyhost",   offsetof(brix_opts, verify_host), 0 },
    { "--timing",         offsetof(brix_opts, timing),      1 },
    { "--redirect-trace", offsetof(brix_opts, redir_trace), 1 },
    { "--wire-trace",     offsetof(brix_opts, wire_trace),  1 },
    { "--no-retry",       offsetof(brix_opts, no_retry),    1 },
}
Definition at line 103 of file cli_opts.c.
Referenced by opts_parse_toggle().