nginx-xrootd: client/lib/cli/cli_hint.c File Reference
cli_hint.c File Reference
#include "cli/cli_hint.h"
#include "brix.h"
#include <errno.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Macros
#define HINT_URL_MAX 128
#define HINT_ONCE_MAX 16
Functions
static int no_hints_env (void)
int brix_cli_hints_enabled (void)
void brix_cli_hint (const char *fmt,...)
void brix_cli_hint_once (const char *key, const char *fmt,...)
void brix_hint_sanitize_url (const char *url_str, char *out, size_t outsz)
void brix_hint_url_double_slash (const brix_status *st, const brix_url *url)
void brix_hint_doctor_referral (const brix_status *st, const char *url_str)
Macro Definition Documentation
HINT_ONCE_MAX
#define HINT_ONCE_MAX 16
Definition at line 33 of file cli_hint.c.
HINT_URL_MAX
#define HINT_URL_MAX 128
Definition at line 30 of file cli_hint.c.
Function Documentation
brix_cli_hint()
void brix_cli_hint (const char * fmt, ...)
Definition at line 74 of file cli_hint.c.
References brix_cli_hints_enabled().
Referenced by brixmount_dispatch(), dispatch_unknown(), dx_unknown_sub(), main(), and report_unknown_command().
brix_cli_hint_once()
void brix_cli_hint_once (const char * key, const char * fmt, ...)
Definition at line 92 of file cli_hint.c.
References brix_cli_hints_enabled(), HINT_ONCE_MAX, and key.
Referenced by brix_env_resolve(), brix_hint_doctor_referral(), and brix_hint_url_double_slash().
brix_cli_hints_enabled()
int brix_cli_hints_enabled (void)
Definition at line 56 of file cli_hint.c.
References no_hints_env().
Referenced by brix_cli_hint(), and brix_cli_hint_once().
brix_hint_doctor_referral()
void brix_hint_doctor_referral (const brix_status * st, const char * url_str)
Definition at line 211 of file cli_hint.c.
References brix_cli_hint_once(), brix_hint_sanitize_url(), HINT_URL_MAX, brix_status::kxr, kXR_AuthFailed, kXR_NotAuthorized, and XRDC_EAUTH.
Referenced by brix_cred_hint_for_status_url().
brix_hint_sanitize_url()
void brix_hint_sanitize_url (const char * url_str, char * out, size_t outsz)
Definition at line 130 of file cli_hint.c.
References c, and HINT_URL_MAX.
Referenced by brix_hint_doctor_referral().
brix_hint_url_double_slash()
void brix_hint_url_double_slash (const brix_status * st, const brix_url * url)
Definition at line 178 of file cli_hint.c.
References brix_cli_hint_once(), brix_status::kxr, kXR_NotFound, brix_url::single_slash_path, and brix_status::sys_errno.
Referenced by brix_report_err(), xrdcp_hint_failed_source(), and xrdfs_op_hints().
no_hints_env()
static int no_hints_env (void) static
Definition at line 43 of file cli_hint.c.
Referenced by brix_cli_hints_enabled().