nginx-xrootd: client/lib/cli/cli_conn.c File Reference
cli_conn.c File Reference
#include "brix.h"
#include "cli/cli_hint.h"
#include <stdio.h>
Functions
int brix_cli_connect (const char *endpoint, const brix_opts *o, brix_conn *c, const char *prog, brix_status *st)
static const char * report_err_endpoint (const brix_url *url, char *buf, size_t bufsz)
int brix_report_err (FILE *out, const char *tool, const char *op, const char *path, const brix_status *st, int want_write, const brix_url *url)
Function Documentation
brix_cli_connect()
int brix_cli_connect (const char * endpoint, const brix_opts * o, brix_conn * c, const char * prog, brix_status * st)
Definition at line 25 of file cli_conn.c.
References brix_connect_resilient(), brix_endpoint_parse(), brix_shellcode(), brix_status_clear(), c, brix_status::msg, and XRDC_EXIT_USAGE.
Referenced by brix_qstats_main(), and main().
brix_report_err()
int brix_report_err (FILE * out, const char * tool, const char * op, const char * path, const brix_status * st, int want_write, const brix_url * url)
Definition at line 67 of file cli_conn.c.
References brix_cred_hint_for_status_url(), brix_hint_url_double_slash(), brix_shellcode(), brix_status::msg, and report_err_endpoint().
report_err_endpoint()
static const char * report_err_endpoint (const brix_url * url, char * buf, size_t bufsz) static
Definition at line 53 of file cli_conn.c.
References brix_url::host, and brix_url::port.
Referenced by brix_report_err().