nginx-xrootd: client/lib/auth/sigver.c File Reference
sigver.c File Reference
#include "brix.h"
#include "core/compat/crypto.h"
#include "auth/gsi/gsi_core.h"
#include "protocols/root/protocol/frame_hdr.h"
#include <arpa/inet.h>
#include <endian.h>
#include <stdlib.h>
#include <string.h>
Functions
int brix_sigver_maybe (brix_conn *c, const uint8_t *hdr24, const void *payload, uint32_t plen, brix_status *st)
Function Documentation
brix_sigver_maybe()
int brix_sigver_maybe (brix_conn * c, const uint8_t * hdr24, const void * payload, uint32_t plen, brix_status * st)
Definition at line 31 of file sigver.c.
References brix_gsi_sigver_hmac(), brix_gsi_sigver_required(), brix_status_set(), brix_write_full(), c, ClientSigverRequest::dlen, xrdw_sigver_req_t::expectrid, kXR_SHA256_sig, kXR_sigver, ClientSigverRequest::requestid, ClientSigverRequest::streamid, xrd_get_u16_be(), XRDC_EAUTH, and xrdw_sigver_req_pack().
Referenced by brix_send_ext().