nginx-xrootd: client/lib/net/tls.c File Reference
tls.c File Reference
#include "brix.h"
#include <openssl/ssl.h>
#include <openssl/err.h>
#include <openssl/x509v3.h>
#include <poll.h>
#include <fcntl.h>
#include <errno.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
Functions
static void tls_err (brix_status *st, int kxr, const char *what)
static int wait_io (int fd, short events, int timeout_ms)
int brix_tls_read (brix_io *io, void *buf, size_t n, brix_status *st)
int brix_tls_write (brix_io *io, const void *buf, size_t n, brix_status *st)
static int tls_do_connect (SSL *ssl, brix_io *io, int verify_peer, brix_status *st)
int brix_tls_upgrade (brix_conn *c, int verify_peer, int verify_host, const char *ca_dir, brix_status *st)
int brix_tls_read_some (brix_io *io, void *buf, size_t n, size_t *got, brix_status *st)
int brix_tls_client (brix_io *io, const char *host, int verify_peer, int verify_host, const char *ca_dir, void **out_ctx, brix_status *st)
void brix_tls_client_free (brix_io *io, void *ctx)
void brix_tls_client_info (const brix_io *io, const char **ver, const char **cipher)
void brix_tls_free (brix_conn *c)
int brix_tls_info (const brix_conn *c, const char **ver, const char **cipher)
static void peer_collect_sans (X509 *cert, char *out, size_t outsz)
int brix_tls_peer_cert_info (const brix_conn *c, brix_cert_info *out)
Function Documentation
brix_tls_client()
int brix_tls_client (brix_io * io, const char * host, int verify_peer, int verify_host, const char * ca_dir, void ** out_ctx, brix_status * st)
Definition at line 324 of file tls.c.
References brix_io::fd, brix_io::ssl, tls_do_connect(), tls_err(), XRDC_EAUTH, and XRDC_ESOCK.
Referenced by brix_kaconn_connect(), httpx_connect(), and web_connect().
brix_tls_client_free()
void brix_tls_client_free (brix_io * io, void * ctx)
Definition at line 387 of file tls.c.
References brix_io::ssl.
Referenced by brix_http_req(), brix_http_upload(), brix_kaconn_disconnect(), http_download_attempt(), httpx_resumable_attempt(), and web_disconnect().
brix_tls_client_info()
void brix_tls_client_info (const brix_io * io, const char ** ver, const char ** cipher)
Definition at line 401 of file tls.c.
References brix_io::ssl.
Referenced by brix_http_req().
brix_tls_free()
void brix_tls_free (brix_conn * c)
Definition at line 413 of file tls.c.
References c.
Referenced by brix_bind(), brix_close(), brix_reconnect(), and brix_streams_close().
brix_tls_info()
int brix_tls_info (const brix_conn * c, const char ** ver, const char ** cipher)
Definition at line 427 of file tls.c.
References c.
Referenced by chk_probe_tls(), doctor_one_session_facts(), explain_tls(), watch_probe_once(), xrd_caps(), and xrd_doctor_probe().
brix_tls_peer_cert_info()
int brix_tls_peer_cert_info (const brix_conn * c, brix_cert_info * out)
Definition at line 476 of file tls.c.
References c, brix_cert_info::days_left, brix_cert_info::expired, brix_cert_info::have, brix_cert_info::host_match, brix_cert_info::issuer, brix_cert_info::not_after, brix_cert_info::not_before, brix_cert_info::not_yet_valid, peer_collect_sans(), brix_cert_info::sans, brix_cert_info::self_signed, and brix_cert_info::subject.
Referenced by xrd_certinfo(), and xrd_doctor_probe().
brix_tls_read()
int brix_tls_read (brix_io * io, void * buf, size_t n, brix_status * st)
Definition at line 58 of file tls.c.
References brix_copy_quit_requested(), brix_status_set(), brix_io::fd, brix_io::ssl, brix_io::timeout_ms, tls_err(), wait_io(), and XRDC_ESOCK.
Referenced by brix_read_full().
brix_tls_read_some()
int brix_tls_read_some (brix_io * io, void * buf, size_t n, size_t * got, brix_status * st)
Definition at line 277 of file tls.c.
References brix_status_set(), brix_io::fd, brix_io::ssl, brix_io::timeout_ms, tls_err(), wait_io(), and XRDC_ESOCK.
Referenced by httpx_read_some(), kaconn_read_some(), and web_read_some().
brix_tls_upgrade()
int brix_tls_upgrade (brix_conn * c, int verify_peer, int verify_host, const char * ca_dir, brix_status * st)
Definition at line 209 of file tls.c.
References c, tls_do_connect(), tls_err(), XRDC_EAUTH, and XRDC_ESOCK.
Referenced by brix_bringup_ex().
brix_tls_write()
int brix_tls_write (brix_io * io, const void * buf, size_t n, brix_status * st)
Definition at line 114 of file tls.c.
References brix_copy_quit_requested(), brix_status_set(), brix_io::fd, brix_io::ssl, brix_io::timeout_ms, tls_err(), wait_io(), and XRDC_ESOCK.
Referenced by brix_write_full().
peer_collect_sans()
static void peer_collect_sans (X509 * cert, char * out, size_t outsz) static
Definition at line 443 of file tls.c.
Referenced by brix_tls_peer_cert_info().
tls_do_connect()
static int tls_do_connect (SSL * ssl, brix_io * io, int verify_peer, brix_status * st) static
Definition at line 166 of file tls.c.
References brix_status_set(), brix_io::fd, brix_io::timeout_ms, tls_err(), wait_io(), XRDC_EAUTH, and XRDC_ESOCK.
Referenced by brix_tls_client(), and brix_tls_upgrade().
tls_err()
static void tls_err (brix_status * st, int kxr, const char * what) static
Definition at line 29 of file tls.c.
References brix_status_set().
Referenced by brix_tls_client(), brix_tls_read(), brix_tls_read_some(), brix_tls_upgrade(), brix_tls_write(), and tls_do_connect().
wait_io()
static int wait_io (int fd, short events, int timeout_ms) static
Definition at line 44 of file tls.c.
References brix_copy_quit_requested().
Referenced by brix_tls_read(), brix_tls_read_some(), brix_tls_write(), and tls_do_connect().