nginx-xrootd: client/lib/net/pool.c File Reference
pool.c File Reference
#include "brix.h"
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct brix_pool_slot
struct brix_pool
Functions
static int pool_slot_connect (brix_pool *p, brix_pool_slot *s, brix_status *st)
brix_pool * brix_pool_create (const brix_url *u, const brix_opts *o, int n, brix_status *st)
brix_conn * brix_pool_checkout (brix_pool *p, brix_status *st)
void brix_pool_checkin (brix_pool *p, brix_conn *c, int healthy)
void brix_pool_destroy (brix_pool *p)
Function Documentation
brix_pool_checkin()
void brix_pool_checkin (brix_pool * p, brix_conn * c, int healthy)
Definition at line 139 of file pool.c.
References brix_pool::avail, brix_close(), c, brix_pool_slot::conn, brix_pool_slot::connected, brix_pool_slot::in_use, brix_pool::lock, brix_pool::n, and brix_pool::slots.
Referenced by brix_fuse_run(), xfs_access(), xfs_getxattr(), xfs_listxattr(), xfs_readlink(), xfs_removexattr(), xfs_setxattr(), xfs_statfs(), and xrootdfs_aio_main().
brix_pool_checkout()
brix_conn * brix_pool_checkout (brix_pool * p, brix_status * st)
Definition at line 101 of file pool.c.
References brix_pool::avail, brix_status_set(), brix_pool_slot::in_use, brix_pool::lock, brix_pool::n, pool_slot_connect(), s, brix_pool::slots, and XRDC_EUSAGE.
Referenced by brix_fuse_run(), xfs_access(), xfs_getxattr(), xfs_listxattr(), xfs_readlink(), xfs_removexattr(), xfs_setxattr(), xfs_statfs(), and xrootdfs_aio_main().
brix_pool_create()
brix_pool * brix_pool_create (const brix_url * u, const brix_opts * o, int n, brix_status * st)
Definition at line 57 of file pool.c.
References brix_pool::avail, brix_pool_destroy(), brix_status_set(), brix_pool_slot::in_use, brix_pool::lock, brix_pool::n, brix_pool::opts, pool_slot_connect(), brix_pool::slots, brix_pool::url, XRDC_ESOCK, and XRDC_EUSAGE.
Referenced by xrootdfs_aio_main(), and xrootdfs_legacy_main().
brix_pool_destroy()
void brix_pool_destroy (brix_pool * p)
Definition at line 174 of file pool.c.
References brix_pool::avail, brix_close(), brix_pool_slot::conn, brix_pool_slot::connected, brix_pool::lock, brix_pool::n, and brix_pool::slots.
Referenced by brix_pool_create(), xrootdfs_aio_main(), and xrootdfs_legacy_main().
pool_slot_connect()
static int pool_slot_connect (brix_pool * p, brix_pool_slot * s, brix_status * st) static
Definition at line 44 of file pool.c.
References brix_connect(), brix_pool::opts, s, and brix_pool::url.
Referenced by brix_pool_checkout(), and brix_pool_create().