nginx-xrootd: client/lib/core/aio/uring.h File Reference
uring.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>
#include "brix.h"
Typedefs
typedef struct brix_disk_ring brix_disk_ring
Functions
int brix_uring_available (void)
brix_disk_ring * brix_disk_ring_create (int fd, unsigned depth, size_t bufsz, int direct, brix_status *st)
void brix_disk_ring_destroy (brix_disk_ring *r)
int brix_disk_ring_pwrite (brix_disk_ring *r, int64_t off, const uint8_t *buf, size_t n, brix_status *st)
int brix_disk_ring_flush (brix_disk_ring *r, brix_status *st)
ssize_t brix_disk_ring_pread (brix_disk_ring *r, int64_t off, uint8_t *out, size_t cap, brix_status *st)
size_t brix_disk_ring_bufsz (const brix_disk_ring *r)
Typedef Documentation
brix_disk_ring
typedef struct brix_disk_ring brix_disk_ring
Definition at line 35 of file uring.h.
Function Documentation
brix_disk_ring_bufsz()
size_t brix_disk_ring_bufsz (const brix_disk_ring * r)
Definition at line 479 of file uring.c.
Referenced by block_pwrite(), and posix_pwrite().
brix_disk_ring_create()
brix_disk_ring * brix_disk_ring_create (int fd, unsigned depth, size_t bufsz, int direct, brix_status * st)
Definition at line 440 of file uring.c.
References brix_status_set(), and XRDC_EUNSUPPORTED.
Referenced by block_ring_select(), and posix_ring_select().
brix_disk_ring_destroy()
void brix_disk_ring_destroy (brix_disk_ring * r)
Definition at line 450 of file uring.c.
Referenced by block_close(), and posix_close().
brix_disk_ring_flush()
int brix_disk_ring_flush (brix_disk_ring * r, brix_status * st)
Definition at line 464 of file uring.c.
Referenced by block_commit(), block_sync(), posix_commit(), and posix_sync().
brix_disk_ring_pread()
ssize_t brix_disk_ring_pread (brix_disk_ring * r, int64_t off, uint8_t * out, size_t cap, brix_status * st)
Definition at line 471 of file uring.c.
Referenced by block_pread(), and posix_pread().
brix_disk_ring_pwrite()
int brix_disk_ring_pwrite (brix_disk_ring * r, int64_t off, const uint8_t * buf, size_t n, brix_status * st)
Definition at line 456 of file uring.c.
Referenced by block_pwrite(), and posix_pwrite().
brix_uring_available()
int brix_uring_available (void)
Definition at line 434 of file uring.c.
Referenced by block_ring_select(), brix_loop_want_uring(), and posix_ring_select().