nginx-xrootd: src/auth/impersonate/client_ops.c File Reference
client_ops.c File Reference
#include "impersonate.h"
#include "impersonate_proto.h"
#include "client_internal.h"
#include <errno.h>
#include <string.h>
#include <unistd.h>
Functions
static int imp_status_errno (int status)
static int imp_call_status (uint32_t op, const char *path, const char *path2, uint32_t mode, int64_t length)
int brix_imp_open (const char *reqpath, int flags, mode_t mode)
static void imp_unpack_stat (struct stat *st, const imp_stat_t *s)
int brix_imp_stat (const char *reqpath, struct stat *st, int nofollow)
int brix_imp_mkdir (const char *reqpath, mode_t mode)
int brix_imp_unlink (const char *reqpath, int is_dir)
int brix_imp_rmdir (const char *reqpath)
int brix_imp_rename (const char *src, const char *dst)
int brix_imp_rename_noreplace (const char *src, const char *dst)
int brix_imp_link (const char *src, const char *dst)
int brix_imp_truncate (const char *reqpath, off_t length)
int brix_imp_chmod (const char *reqpath, mode_t mode)
int brix_imp_chown_gid (const char *reqpath, gid_t gid)
int brix_imp_setattr (const char *reqpath, int set_times, const struct timespec times[2], int set_owner, uid_t uid, gid_t gid)
int brix_imp_symlink (const char *target, const char *linkpath)
ssize_t brix_imp_readlink (const char *reqpath, char *buf, size_t bufsz)
static ssize_t imp_get_or_list (uint32_t op, const char *reqpath, const char *name, void *buf, size_t bufsz)
ssize_t brix_imp_getxattr (const char *reqpath, const char *name, void *buf, size_t bufsz)
ssize_t brix_imp_listxattr (const char *reqpath, void *buf, size_t bufsz)
int brix_imp_setxattr (const char *reqpath, const char *name, const void *value, size_t len, int flags)
int brix_imp_removexattr (const char *reqpath, const char *name)
Function Documentation
brix_imp_chmod()
int brix_imp_chmod (const char * reqpath, mode_t mode)
Definition at line 184 of file client_ops.c.
References imp_call_status(), and IMP_OP_CHMOD.
Referenced by brix_chmod_confined_canon().
brix_imp_chown_gid()
int brix_imp_chown_gid (const char * reqpath, gid_t gid)
Definition at line 190 of file client_ops.c.
References imp_call_status(), and IMP_OP_CHOWN.
brix_imp_getxattr()
ssize_t brix_imp_getxattr (const char * reqpath, const char * name, void * buf, size_t bufsz)
Definition at line 303 of file client_ops.c.
References imp_get_or_list(), IMP_OP_GETXATTR, and name.
Referenced by brix_getxattr_confined_canon().
brix_imp_link()
int brix_imp_link (const char * src, const char * dst)
Definition at line 172 of file client_ops.c.
References imp_call_status(), and IMP_OP_LINK.
Referenced by brix_link_beneath(), and brix_link_confined_canon().
brix_imp_listxattr()
ssize_t brix_imp_listxattr (const char * reqpath, void * buf, size_t bufsz)
Definition at line 310 of file client_ops.c.
References imp_get_or_list(), and IMP_OP_LISTXATTR.
Referenced by brix_listxattr_confined_canon().
brix_imp_mkdir()
int brix_imp_mkdir (const char * reqpath, mode_t mode)
Definition at line 141 of file client_ops.c.
References imp_call_status(), and IMP_OP_MKDIR.
Referenced by brix_mkdir_beneath(), and brix_mkdir_confined_canon().
brix_imp_open()
int brix_imp_open (const char * reqpath, int flags, mode_t mode)
Definition at line 73 of file client_ops.c.
References close(), imp_build_req(), imp_exchange(), IMP_OP_OPEN, IMP_REP_HAS_FD, imp_status_errno(), IMP_STATUS_INTERNAL, imp_rep_t::rep_flags, and imp_rep_t::status.
Referenced by brix_dirlist_access_ok(), brix_open_beneath(), brix_open_confined_canon(), and brix_opendir_confined_canon().
brix_imp_readlink()
ssize_t brix_imp_readlink (const char * reqpath, char * buf, size_t bufsz)
Definition at line 236 of file client_ops.c.
References close(), imp_rep_t::data_len, imp_build_req(), imp_exchange(), IMP_OP_READLINK, IMP_PATH_MAX, IMP_REP_HAS_DATA, imp_status_errno(), IMP_STATUS_INTERNAL, ngx_memcpy, imp_rep_t::rep_flags, and imp_rep_t::status.
Referenced by brix_readlink_confined_canon().
brix_imp_removexattr()
int brix_imp_removexattr (const char * reqpath, const char * name)
Definition at line 342 of file client_ops.c.
References close(), imp_build_req(), imp_exchange(), IMP_OP_REMOVEXATTR, imp_status_errno(), name, and imp_rep_t::status.
Referenced by brix_removexattr_confined_canon().
brix_imp_rename()
int brix_imp_rename (const char * src, const char * dst)
Definition at line 160 of file client_ops.c.
References imp_call_status(), and IMP_OP_RENAME.
Referenced by brix_rename_beneath(), and rename_confined_canon_impl().
brix_imp_rename_noreplace()
int brix_imp_rename_noreplace (const char * src, const char * dst)
Definition at line 166 of file client_ops.c.
References imp_call_status(), and IMP_OP_RENAME_NOREPLACE.
Referenced by brix_rename_beneath_excl(), and rename_confined_canon_impl().
brix_imp_rmdir()
int brix_imp_rmdir (const char * reqpath)
Definition at line 154 of file client_ops.c.
References imp_call_status(), and IMP_OP_RMDIR.
brix_imp_setattr()
int brix_imp_setattr (const char * reqpath, int set_times, const struct timespec times[2], int set_owner, uid_t uid, gid_t gid)
Definition at line 197 of file client_ops.c.
References imp_req_t::atime_nsec, imp_req_t::atime_sec, imp_req_t::attr_flags, close(), IMP_ATTR_OWNER, IMP_ATTR_TIMES, imp_build_req(), imp_exchange(), IMP_OP_SETATTR, imp_status_errno(), imp_req_t::mtime_nsec, imp_req_t::mtime_sec, imp_req_t::set_gid, imp_req_t::set_uid, and imp_rep_t::status.
Referenced by brix_setattr_confined_canon().
brix_imp_setxattr()
int brix_imp_setxattr (const char * reqpath, const char * name, const void * value, size_t len, int flags)
Definition at line 316 of file client_ops.c.
References close(), imp_build_req(), imp_exchange(), IMP_OP_SETXATTR, imp_status_errno(), IMP_XATTR_MAX, name, imp_req_t::req_data_len, and imp_rep_t::status.
Referenced by brix_setxattr_confined_canon().
brix_imp_stat()
int brix_imp_stat (const char * reqpath, struct stat * st, int nofollow)
Definition at line 116 of file client_ops.c.
References close(), imp_build_req(), imp_exchange(), IMP_OP_LSTAT, IMP_OP_STAT, IMP_REP_HAS_STAT, imp_status_errno(), IMP_STATUS_INTERNAL, imp_unpack_stat(), imp_rep_t::rep_flags, imp_rep_t::st, and imp_rep_t::status.
Referenced by brix_lstat_beneath(), brix_lstat_confined_canon(), and brix_stat_beneath().
brix_imp_symlink()
int brix_imp_symlink (const char * target, const char * linkpath)
Definition at line 229 of file client_ops.c.
References imp_call_status(), and IMP_OP_SYMLINK.
Referenced by brix_symlink_confined_canon().
brix_imp_truncate()
int brix_imp_truncate (const char * reqpath, off_t length)
Definition at line 178 of file client_ops.c.
References imp_call_status(), and IMP_OP_TRUNCATE.
brix_imp_unlink()
int brix_imp_unlink (const char * reqpath, int is_dir)
Definition at line 147 of file client_ops.c.
References imp_call_status(), IMP_OP_RMDIR, and IMP_OP_UNLINK.
Referenced by brix_unlink_beneath(), and brix_unlink_confined_canon().
imp_call_status()
static int imp_call_status (uint32_t op, const char * path, const char * path2, uint32_t mode, int64_t length) static
Definition at line 50 of file client_ops.c.
References close(), imp_build_req(), imp_exchange(), imp_status_errno(), op, and imp_rep_t::status.
Referenced by brix_imp_chmod(), brix_imp_chown_gid(), brix_imp_link(), brix_imp_mkdir(), brix_imp_rename(), brix_imp_rename_noreplace(), brix_imp_rmdir(), brix_imp_symlink(), brix_imp_truncate(), and brix_imp_unlink().
imp_get_or_list()
static ssize_t imp_get_or_list (uint32_t op, const char * reqpath, const char * name, void * buf, size_t bufsz) static
Definition at line 272 of file client_ops.c.
References close(), imp_rep_t::data_len, imp_build_req(), imp_exchange(), IMP_REP_HAS_DATA, imp_status_errno(), IMP_XATTR_MAX, name, ngx_memcpy, op, imp_rep_t::rep_flags, and imp_rep_t::status.
Referenced by brix_imp_getxattr(), and brix_imp_listxattr().
imp_status_errno()
static int imp_status_errno (int status) static
Definition at line 33 of file client_ops.c.
References IMP_STATUS_BADREQ, IMP_STATUS_DENY, IMP_STATUS_INTERNAL, and IMP_STATUS_PRIV_REFUSED.
Referenced by brix_imp_open(), brix_imp_readlink(), brix_imp_removexattr(), brix_imp_setattr(), brix_imp_setxattr(), brix_imp_stat(), imp_call_status(), and imp_get_or_list().
imp_unpack_stat()
static void imp_unpack_stat (struct stat * st, const imp_stat_t * s) static
Definition at line 98 of file client_ops.c.
References s.
Referenced by brix_imp_stat().