nginx-xrootd: client/lib/core/types/status.c File Reference
status.c File Reference
#include "brix.h"
#include "core/compat/kxr_names.h"
#include "core/compat/error_mapping.h"
#include <errno.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
Functions
void brix_status_clear (brix_status *st)
void brix_status_set (brix_status *st, int kxr, int sys_errno, const char *fmt,...)
const char * brix_kxr_name (int kxr)
int brix_status_retryable (const brix_status *st)
int brix_shellcode (const brix_status *st)
int brix_kxr_to_errno (const brix_status *st)
Function Documentation
brix_kxr_name()
const char * brix_kxr_name (int kxr)
Definition at line 50 of file status.c.
References brix_kxr_error_name().
Referenced by aconn_dispatch_response(), brix_trace_error(), chk_probe_confinement(), chk_probe_handle_limits(), chk_probe_posc(), dx_record_status(), probe_holder(), probe_p1_path_escape(), read_status_frame(), set_kxr_error_status(), and topo_probe_redirect().
brix_kxr_to_errno()
int brix_kxr_to_errno (const brix_status * st)
Definition at line 114 of file status.c.
References brix_errno_from_kxr(), brix_status::kxr, brix_status::sys_errno, XRDC_EAUTH, XRDC_EINTEGRITY, XRDC_EPROTO, XRDC_ESOCK, XRDC_EUNSUPPORTED, and XRDC_EUSAGE.
Referenced by brix_fuse_errno(), brix_fuse_run(), brix_roundtrip_resilient(), brix_with_resilience(), pread(), read(), remote_open(), remote_stat(), and statx().
brix_shellcode()
int brix_shellcode (const brix_status * st)
Definition at line 88 of file status.c.
References brix_status::kxr, XRDC_EAUTH, XRDC_EINTEGRITY, XRDC_EPROTO, XRDC_EREDIRECT, XRDC_ERESOLVE, XRDC_ESOCK, XRDC_EUNSUPPORTED, and XRDC_EUSAGE.
Referenced by aio_root_mount(), aio_web_mount(), brix_cli_connect(), brix_qstats_main(), brix_report_err(), cmd_bench(), cmd_destroy(), cmd_info(), cmd_init(), cmd_scan(), cmd_verify(), compare_setup(), do_bench(), do_cat(), do_check(), do_chmod(), do_cksum(), do_cmp(), do_compare_davs(), do_dd(), do_df(), do_download(), do_evict(), do_find(), do_grep(), do_head(), do_hexdump(), do_ln(), do_locate(), do_ls(), do_map(), do_mkdir(), do_mv(), do_prepare(), do_query(), do_readlink(), do_readv(), do_replay(), do_rm(), do_rmdir(), do_stage(), do_stat(), do_statvfs(), do_tail(), do_topology(), do_touch(), do_tree(), do_truncate(), do_upload(), do_wc(), do_writev(), download_copy_loop(), du_one_path(), main(), run_root_endpoint(), scan_fetch(), storascan_connect(), upload_copy_loop(), verify_compute_wire_hex(), wc_count_stream(), web_ls(), web_stat(), xattr_get(), xattr_ls(), xattr_rm(), xattr_set(), xfs_root_mount(), xrd_caps(), xrd_certinfo(), xrd_ping(), xrd_whoami(), xrdcp_dispatch_single(), and xrdprep_run().
brix_status_clear()
void brix_status_clear (brix_status * st)
Definition at line 22 of file status.c.
References brix_status::kxr, brix_status::msg, and brix_status::sys_errno.
Referenced by afh_open(), aio_root_mount(), aio_web_mount(), auth_hdr_bearer(), batch_worker(), battery_root(), battery_s3(), bench_run(), bench_sweep(), block_ring_select(), brix_cli_cksum_main(), brix_cli_connect(), brix_close(), brix_fuse_run(), brix_mpxstats_main(), brix_roundtrip_resilient(), brix_streams_open(), brix_wait41_main(), brix_with_resilience(), brix_xrdckverify_main(), brixcvmfs_open(), brixcvmfs_transport(), chk_probe_checksum(), chk_probe_confinement(), chk_probe_dirlist(), chk_probe_handle_limits(), chk_probe_pgread(), chk_probe_posc(), chmod_visit(), ckcheck_connect(), ckcheck_digest_local(), ckcheck_digest_remote(), cktree_run_remote(), close(), cmd_add(), cmd_del(), cmd_list(), cmd_scan(), compare_dirs(), compare_files(), compare_probe(), compare_setup(), copy_block(), copy_block_to_remote(), copy_one_with_retry(), copy_recursive(), copy_tree_upload(), copy_upload(), copy_vfs_to_vfs(), copy_zip_store_remote(), dest_is_dir(), do_bench(), do_cat(), do_check(), do_chmod(), do_cksum(), do_cmp(), do_compare_davs(), do_dd(), do_df(), do_download(), do_evict(), do_find(), do_grep(), do_head(), do_hexdump(), do_ln(), do_locate(), do_ls(), do_map(), do_metabench(), do_mkdir(), do_mv(), do_prepare(), do_probe_robustness(), do_query(), do_readlink(), do_readv(), do_replay(), do_rm(), do_rmdir(), do_srr(), do_stage(), do_stat(), do_status(), do_statvfs(), do_tail(), do_tape(), do_topology(), do_touch(), do_tree(), do_truncate(), do_upload(), do_watch(), do_wc(), do_writev(), doctor_cms(), doctor_diagnose(), doctor_http(), doctor_metrics(), doctor_one(), doctor_one_xfer_probe(), doctor_s3(), doctor_xfer(), download_open_local(), download_reconcile_cksum(), download_stream_body(), du_one_path(), dx_authz_anon(), dx_authz_scope(), dx_connect_as(), dx_probe_checksum(), dx_probe_namespace(), dx_probe_read(), dx_probe_stage(), dx_probe_write(), ensure_conn(), ensure_web_dst_base(), entry_cksum(), entry_meta(), expand_source(), fs_find_endpoint(), gsi_resolve_proxy(), head_lines(), http_davs_extras(), keytab_probe(), load_or_empty(), main(), map_fs_arg(), mb_thread(), mirror_delete_remote(), mirror_remote_remove(), parse_vmp(), playback_reissue_wire(), posix_ring_select(), pread(), print_space(), probe_holder(), probe_p1_path_escape(), probe_p2_bad_opcode(), probe_p3_oversized_dlen(), probe_p4_oob_read(), probe_p5_partial_frame(), probe_path_confinement(), probe_root_read_suite(), probe_server_survives(), probe_write_suite(), r2r_teardown(), raw_send_expect_reject(), read(), recdl_transfer_one(), recursive_s3_download(), recursive_web_download(), recursive_web_upload(), refresh_bearer_token(), refresh_gsi_proxy(), remote_entry_is_dir(), remote_open(), remote_stat(), remote_tree_visitor(), remove_source_entry(), run_root_endpoint(), s3_be_stat(), s3_delete(), s3_get_verify(), s3_put(), s3_resolve_keys(), s3_sigv4_probe(), s3t_request(), scan_fetch(), sss_first(), sss_have(), statx(), storascan_connect(), stream_file(), sync_cksum_match(), tail_follow(), tail_follow_drain(), tail_start_for_lines(), tape_poll_status(), test_contention_unique_issue(), test_create_fails_on_bad_endpoint(), test_destroy_closes_connected(), test_health_drop_reconnects(), test_reuse(), token_first(), topo_probe_locate(), topo_probe_redirect(), topo_report_cluster(), touch_ensure_file(), tpc_teardown(), tree_dl_entry(), tree_dl_file(), tree_emit_file(), ul_sync_skip(), upload_close_commit_resilient(), upload_reconcile_cksum(), verify_compute_wire_hex(), wait_online(), walk_handle_dir(), walk_handle_file(), watch_probe_once(), web_ls(), web_move_delete(), web_put_get_verify(), web_read_suite(), web_stat(), web_write_suite(), worker(), write_checksum(), write_readv(), write_rename_truncate_rm(), write_symlink_ops(), write_verify(), write_xattr_ops(), xattr_get(), xattr_ls(), xattr_rm(), xattr_set(), xfs_access(), xfs_access(), xfs_chmod(), xfs_chmod(), xfs_chown(), xfs_create(), xfs_flush(), xfs_flush(), xfs_fsync(), xfs_fsync(), xfs_getattr(), xfs_getattr(), xfs_getxattr(), xfs_getxattr(), xfs_handle_new(), xfs_link(), xfs_listxattr(), xfs_listxattr(), xfs_mkdir(), xfs_mkdir(), xfs_open(), xfs_read(), xfs_read(), xfs_readdir(), xfs_readdir(), xfs_readlink(), xfs_release(), xfs_release(), xfs_removexattr(), xfs_removexattr(), xfs_rename(), xfs_rename(), xfs_rmdir(), xfs_rmdir(), xfs_root_mount(), xfs_setxattr(), xfs_setxattr(), xfs_statfs(), xfs_statfs(), xfs_symlink(), xfs_truncate(), xfs_truncate(), xfs_unlink(), xfs_unlink(), xfs_utimens(), xfs_write(), xfs_write(), xrd_caps(), xrd_certinfo(), xrd_clockskew_http(), xrd_clockskew_root(), xrd_doctor_probe(), xrd_ping(), xrd_probe_caps(), xrd_run_battery(), xrd_whoami(), xrdcp_dispatch_batch(), xrdcp_dispatch_recursive_web_download(), xrdcp_dispatch_recursive_web_upload(), xrdcp_dispatch_single(), xrdcp_hint_failed_source(), and xrdcp_open_batch_journal().
brix_status_retryable()
int brix_status_retryable (const brix_status * st)
Definition at line 69 of file status.c.
References brix_status::kxr, kXR_inProgress, kXR_noserver, kXR_Overloaded, kXR_ServerError, XRDC_EPROTO, and XRDC_ESOCK.
Referenced by brix_connect_resilient(), brix_fuse_run(), brix_rfile_open_read(), brix_rfile_open_write(), brix_rfile_pread(), brix_rfile_pwrite(), brix_roundtrip_resilient(), brix_webfile_pread(), brix_webmeta_propfind(), brix_with_resilience(), csctx_retry_gate(), http_download_should_retry(), httpx_resumable_may_retry(), mfile_should_reopen(), pump_sink_remote(), pump_src_remote(), resilient_setup(), tail_follow(), upload_close_commit_resilient(), and xfs_readlink_one_attempt().
brix_status_set()
void brix_status_set (brix_status * st, int kxr, int sys_errno, const char * fmt, ...)
Definition at line 32 of file status.c.
References brix_status::kxr, brix_status::msg, and brix_status::sys_errno.
Referenced by aconn_destroy(), aconn_dispatch_response(), aconn_do_read(), aconn_do_write(), aconn_handle_io(), aconn_issue_areq(), aconn_parse(), aconn_read_plain(), aconn_read_tls(), aconn_reconnect_succeeded(), aconn_submit_cmd(), asynresp_deliver(), atomic_dest_finish(), auth_hdr_bearer(), auth_hdr_s3(), bat_upload_src_fd(), batch_copy_one(), bearer_acquire(), bench_one(), block_be_open(), block_be_stat(), block_commit(), block_fstat(), block_pread(), block_pwrite(), block_ring_select(), block_sync(), block_truncate(), brix_aconn_attach(), brix_aio_submit_ex(), brix_authenticate(), brix_bringup_ex(), brix_capture_playback(), brix_capture_replay(), brix_cks_verify_file(), brix_cksum_fd(), brix_connect(), brix_connect_no_login(), brix_copy_dispatch_recursive(), brix_copy_route(), brix_cpool_checkout(), brix_cpool_create(), brix_cred_acquire(), brix_deflate_frame(), brix_disk_ring_create(), brix_endpoint_parse(), brix_fattr_get(), brix_fattr_list(), brix_file_open_opaque(), brix_file_pgread(), brix_file_pgwrite(), brix_file_read(), brix_file_readv(), brix_file_writev(), brix_glob(), brix_http_get(), brix_http_upload_resumable(), brix_inflate_frame(), brix_journal_open(), brix_kaconn_read_body(), brix_kaconn_read_headers(), brix_link(), brix_loop_create(), brix_mfile_open(), brix_mv(), brix_open_apply_inline_codec(), brix_open_credfile(), brix_pool_checkout(), brix_pool_create(), brix_prepare(), brix_proxy_destroy(), brix_proxy_info(), brix_query_cksum(), brix_readv_accumulate(), brix_readv_scatter(), brix_recv(), brix_rfile_pread(), brix_rfile_pwrite(), brix_rmtree(), brix_s3_list(), brix_setattr(), brix_sigver_maybe(), brix_sss_bf32_encrypt(), brix_sss_keytab_read(), brix_sss_keytab_write(), brix_symlink(), brix_tcp_connect(), brix_tls_read(), brix_tls_read_some(), brix_tls_write(), brix_url_parse(), brix_vfs_open(), brix_vfs_stat_url(), brix_web_readdir(), brix_web_stat(), brix_webdav_list(), brix_webdav_mkcol(), brix_webfile_open(), brix_webmeta_propfind(), cksum_compute_local(), cksum_parse_spec(), cksum_verify_literal(), cksum_verify_source(), ckv_verify_one(), connect_resolved(), copy_block(), copy_download(), copy_recursive(), copy_remote_to_block(), copy_remote_to_remote(), copy_tree_download(), copy_tree_upload(), copy_unzip_extract_member(), copy_unzip_finalize(), copy_unzip_open_dest(), copy_web(), copy_web_download(), copy_web_upload(), copy_zip_store(), copy_zip_store_local(), curl_slot_connect(), decode_pages(), dirlist_accumulate(), dirlist_parse_entries(), do_acquire(), do_dd(), do_handshake(), do_login(), download_to_fd(), fake_connect(), fattr_parse_status(), fattr_set_or_del(), follow_redirect(), frame_read_body(), frame_read_header(), glob_parse_spec(), gsi_first(), gsi_more(), gsi_sigpxy(), head_lines(), host_first(), http_get_read_response(), http_get_send_request(), httpx_build_request(), httpx_chunk_read_status(), httpx_download_body(), httpx_download_exchange(), httpx_fmt_chunk_request(), httpx_fmt_put_request(), httpx_read_response(), httpx_read_some(), httpx_upload_body(), httpx_upload_response(), io_engine_setup(), kaconn_read_some(), mfile_do_open(), mfile_learn_codec(), mgr_alloc_and_init(), mgr_connect_eager(), open_download_temp(), open_payload_with_opaque(), parse_authority(), parse_remote(), pgwrite_correct_one_page(), pgwrite_handle_cse(), pgwrite_retry_one(), place_to_local(), place_to_web(), plain_read_full(), plain_write_full(), posix_be_open(), posix_be_stat(), posix_commit(), posix_fstat(), posix_pread(), posix_pwrite(), posix_ring_select(), posix_sync(), posix_truncate(), pump_src_local(), pwd_first(), pwd_more(), pxy_assemble_pem(), pxy_load_issuer(), rc_worker_main(), read_magic(), read_resp_headers(), read_status_frame(), recv_after_waitresp(), recv_dispatch(), recv_raw(), relay_web_to_web(), remote_md5(), resolve_once(), resolve_target(), rmtree_depth(), rmtree_one_entry(), rmtree_remove_leaf(), rt_handle_redirect(), rt_handle_wait(), run_module(), run_oidc_token(), s3_be_open(), s3_be_stat(), s3_commit(), s3_list_build_request(), s3_list_next_token(), s3_list_scan_keys(), s3_list_split_path(), s3_load_size(), s3_open_read(), s3_pread(), s3_pwrite(), s3_truncate(), s3keys_acquire(), scan_login(), set_kxr_error_status(), slurp_file(), ssl_fail(), sss_acquire(), sss_first(), sss_load_first_key(), stat_opt(), stream_chunked(), stream_clen(), stream_file(), tail_follow(), tail_start_for_lines(), timeouts_expire_inflight(), timeouts_expire_parked(), timeouts_scan_conn(), tls_do_connect(), tls_err(), token_first(), tpc_run_rendezvous(), tpc_setup_source(), transfer_pump(), tree_dl_entry(), tree_recurse(), tree_ul_entry(), tree_walk_depth(), unix_first(), verify_download_tmp(), watch_write_prom_atomic(), web_range_read_headers(), web_range_send_req(), web_range_stream_body(), web_read_some(), webdav_list_emit_block(), webdav_parse_multi(), webdav_parse_single(), webmeta_send_req(), webmeta_status_map(), write_all(), write_all_fd(), x509_acquire(), zip_emit_member(), and zip_read_seed().