nginx-xrootd: client/lib/auth/gsi/proxy.c File Reference
proxy.c File Reference
#include "brix.h"
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/pem.h>
#include <openssl/evp.h>
#include <openssl/rsa.h>
#include <openssl/bio.h>
#include <openssl/err.h>
#include <fcntl.h>
#include <pwd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct proxy_build_ctx
Macros
#define PROXY_CERT_INFO_OID "1.3.6.1.5.5.7.1.14"
Functions
struct bio_st * brix_credfile_bio (const char *path, int secret)
void brix_proxy_default_path (char *out, size_t outsz)
static void default_cred (const char *envname, const char *globus_leaf, char *out, size_t outsz)
static int ssl_fail (brix_status *st, const char *what)
static int proxy_build_cleanup (proxy_build_ctx *c, int rc)
int brix_proxy_create (const brix_proxy_opts *o, brix_status *st)
int brix_proxy_info (const char *path, FILE *out, brix_status *st)
int brix_proxy_remaining (const char *path, long *secs_left)
int brix_proxy_destroy (const char *path, brix_status *st)
Variables
static const unsigned char PROXY_CERT_INFO_DER []
Macro Definition Documentation
PROXY_CERT_INFO_OID
#define PROXY_CERT_INFO_OID "1.3.6.1.5.5.7.1.14"
Definition at line 43 of file proxy.c.
Function Documentation
brix_credfile_bio()
struct bio_st * brix_credfile_bio (const char * path, int secret)
Definition at line 50 of file proxy.c.
References brix_open_credfile(), and close().
Referenced by brix_gsi_cert_explain(), brix_proxy_info(), and brix_proxy_remaining().
brix_proxy_create()
int brix_proxy_create (const brix_proxy_opts * o, brix_status * st)
Definition at line 151 of file proxy.c.
References brix_proxy_opts::bits, brix_proxy_default_path(), brix_status_set(), c, default_cred(), proxy_build_ctx::fd, open(), brix_proxy_opts::out_path, proxy_build_cleanup(), PROXY_CERT_INFO_DER, PROXY_CERT_INFO_OID, ssl_fail(), brix_proxy_opts::user_cert, brix_proxy_opts::user_key, brix_proxy_opts::valid_hours, and XRDC_EUSAGE.
Referenced by brix_cred_autorefresh(), and main().
brix_proxy_default_path()
void brix_proxy_default_path (char * out, size_t outsz)
Definition at line 72 of file proxy.c.
Referenced by brix_cred_autorefresh(), brix_cred_diagnose(), brix_proxy_create(), brix_proxy_destroy(), brix_proxy_info(), brix_proxy_remaining(), xrd_doctor(), and xrd_whoami().
brix_proxy_destroy()
int brix_proxy_destroy (const char * path, brix_status * st)
Definition at line 351 of file proxy.c.
References brix_proxy_default_path(), brix_status_set(), close(), open(), stat(), and XRDC_EUSAGE.
Referenced by main().
brix_proxy_info()
int brix_proxy_info (const char * path, FILE * out, brix_status * st)
Definition at line 263 of file proxy.c.
References brix_credfile_bio(), brix_proxy_default_path(), brix_status_set(), ssl_fail(), and XRDC_ENOENT.
Referenced by main().
brix_proxy_remaining()
int brix_proxy_remaining (const char * path, long * secs_left)
Definition at line 318 of file proxy.c.
References brix_credfile_bio(), and brix_proxy_default_path().
Referenced by brix_cred_autorefresh(), and brix_cred_diagnose().
default_cred()
static void default_cred (const char * envname, const char * globus_leaf, char * out, size_t outsz) static
Definition at line 83 of file proxy.c.
Referenced by brix_proxy_create().
proxy_build_cleanup()
static int proxy_build_cleanup (proxy_build_ctx * c, int rc) static
Definition at line 135 of file proxy.c.
References c, and close().
Referenced by brix_proxy_create().
ssl_fail()
static int ssl_fail (brix_status * st, const char * what) static
Definition at line 98 of file proxy.c.
References brix_status_set(), and XRDC_EAUTH.
Referenced by brix_proxy_create(), and brix_proxy_info().
Variable Documentation
PROXY_CERT_INFO_DER
const unsigned char PROXY_CERT_INFO_DER[] static
Initial value:
= {
    0x30, 0x0c, 0x30, 0x0a, 0x06, 0x08,
    0x2b, 0x06, 0x01, 0x05, 0x05, 0x07, 0x15, 0x01
}
Definition at line 39 of file proxy.c.
Referenced by brix_proxy_create().