nginx-xrootd: client/lib/xfer/copy_internal.h File Reference
copy_internal.h File Reference
#include "brix.h"
#include "auth/cred/cred.h"
#include "fs/vfs.h"
#include "protocols/shared/zip.h"
#include "core/compat/host_format.h"
#include "core/compat/hex.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <dirent.h>
#include <sys/stat.h>
#include <signal.h>
#include <stdatomic.h>
Data Structures
struct pump_remote_t
struct pump_local_t
struct zip_remote_ctx
struct unzip_sink_ctx
struct zipw_local_sink
struct zipw_remote_sink
struct download_body_ctx
struct upload_body_ctx
struct copy_walk_ctx
struct copy_recurse_req
struct web_auth_ctx
struct web_dl_req
Macros
#define XRDC_COPY_CHUNK (8u * 1024u * 1024u)
#define XRDC_CK_OK 0
#define XRDC_CK_MISMATCH (-1)
#define XRDC_CK_UNVERIFIED 1
#define XRDC_RESILIENT_FLOOR (256u * 1024u)
#define XRDC_WEB_TIMEOUT_MS 300000 /* 5 min per-read ceiling for big files */
Typedefs
typedef ssize_t(* pump_src_fn) (void *ctx, uint8_t *buf, int64_t off, size_t cap, brix_status *st)
typedef int(* pump_sink_fn) (void *ctx, const uint8_t *buf, int64_t off, size_t n, brix_status *st)
Functions
void copy_signal_handler (int sig)
int make_temp_path (const char *dst, char *out, size_t outsz)
int open_download_temp (const char *dst, char *tmp, size_t tmpsz, brix_status *st)
int atomic_dest_finish (const char *tmp, const char *dest, int rc, brix_status *st)
int write_all (int fd, const uint8_t *buf, size_t n, brix_status *st)
int copy_stall_ms (const brix_copy_opts *o, int dflt)
int pump_remote_reopen (pump_remote_t *r, brix_status *st)
ssize_t pump_src_remote (void *ctx, uint8_t *buf, int64_t off, size_t cap, brix_status *st)
int pump_sink_reopen (pump_remote_t *r, brix_status *st)
int pump_sink_remote (void *ctx, const uint8_t *buf, int64_t off, size_t n, brix_status *st)
ssize_t pump_src_local (void *ctx, uint8_t *buf, int64_t off, size_t cap, brix_status *st)
int pump_sink_local (void *ctx, const uint8_t *buf, int64_t off, size_t n, brix_status *st)
ssize_t pump_src_local_vfs (void *ctx, uint8_t *buf, int64_t off, size_t cap, brix_status *st)
int pump_sink_local_vfs (void *ctx, const uint8_t *buf, int64_t off, size_t n, brix_status *st)
int transfer_pump (pump_src_fn src, void *sctx, pump_sink_fn sink, void *kctx, int64_t expected, const brix_copy_opts *o, int64_t progress_total, brix_status *st)
int download_stream_body (const download_body_ctx *j, pump_sink_fn sink, void *sinkctx, brix_status *st)
int resilient_setup (brix_conn *c, const brix_url *su, const brix_opts *co, brix_statinfo *si, int max_stall_ms, brix_status *st)
int copy_download (const brix_url *su, const brix_url *du, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
int upload_stream_body (const upload_body_ctx *j, pump_src_fn src, void *srcctx, brix_status *st)
int copy_upload (const brix_url *su, const brix_url *du, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
int r2r_teardown (brix_conn *sc, brix_conn *dc, brix_file *sf, brix_file *df, int src_up, int dst_up, int sopen, int dopen, int rc, brix_status *st)
int r2r_stream_body (brix_conn *sc, brix_conn *dc, brix_file *sf, brix_file *df, const brix_statinfo *si, const brix_copy_opts *o, brix_status *st)
int copy_remote_to_remote (const brix_url *su, const brix_url *du, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
int cksum_verify (brix_conn *c, const char *remote_path, const char *local_path, const char *spec, int silent, brix_status *st)
int gen_tpc_key (char *out, size_t outsz)
int tpc_teardown (brix_conn *sc, brix_conn *dc, brix_file *sf, brix_file *df, char *src_opaque, char *dst_opaque, int su_up, int du_up, int sopen, int dopen, int rc, brix_status *st)
int copy_tpc (const brix_url *su, const brix_url *du, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
int copy_one_r2l (brix_conn *c, const char *rpath, const char *lpath, int64_t expected_size, brix_status *st)
int copy_one_l2r (brix_conn *c, const char *lpath, const char *rpath, const brix_copy_opts *o, brix_status *st)
int copy_tree_download (const copy_walk_ctx *w)
int copy_tree_upload (const copy_walk_ctx *w)
int recursive_dest_root (const char *dstdir, const char *srcpath, char *out, size_t outsz)
int copy_recursive (const copy_recurse_req *rq, brix_status *st)
int web_auth_headers (const web_auth_ctx *a, char *hdrs, size_t hdrsz)
int copy_web_download (const web_dl_req *rq, brix_status *st)
int copy_web_upload (const brix_url *su, const brix_weburl *du, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
int copy_web (const char *src, const char *dst, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
ssize_t zip_remote_pread (void *vctx, uint64_t off, void *buf, size_t len)
int unzip_sink_write (void *sc, const uint8_t *d, size_t l)
int copy_unzip (const brix_url *su, const char *archive_path, const char *member, const brix_url *du, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
int unzip_member_from_src (const char *src, const brix_url *su, char *member, size_t member_sz, char *arch, size_t arch_sz)
int zipw_local_write (void *cx, const void *d, size_t n)
int zipw_remote_write (void *cx, const void *d, size_t n)
ssize_t zipw_local_pread (void *cx, uint64_t off, void *buf, size_t len)
const char * zip_member_basename (const char *p)
int zip_read_seed (brix_zip_pread_fn pr, void *ctx, uint64_t size, uint64_t *base, uint8_t **seed_cd, size_t *seed_len, size_t *seed_n, brix_status *st)
int zip_emit_member (brix_zip_writer *w, const char *member, int srcfd, brix_status *st)
int copy_zip_store_local (const char *member, int srcfd, const brix_url *du, int append, brix_status *st)
int copy_zip_store_remote (const char *member, int srcfd, const brix_url *du, int append, const brix_opts *co, brix_status *st)
int copy_remote_to_block (const char *src_url, const char *dst_url, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
int copy_block_to_remote (const char *src_url, const char *dst_url, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
int copy_vfs_to_vfs (const char *src_url, const char *dst_url, const brix_copy_opts *o, brix_status *st)
int copy_block (const char *src, const char *dst, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
int copy_zip_store (const brix_url *su, const brix_url *du, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
Variables
volatile sig_atomic_t g_brix_copy_quit
Macro Definition Documentation
XRDC_CK_MISMATCH
#define XRDC_CK_MISMATCH (-1)
Definition at line 28 of file copy_internal.h.
XRDC_CK_OK
#define XRDC_CK_OK 0
Definition at line 27 of file copy_internal.h.
XRDC_CK_UNVERIFIED
#define XRDC_CK_UNVERIFIED 1
Definition at line 29 of file copy_internal.h.
XRDC_COPY_CHUNK
#define XRDC_COPY_CHUNK (8u * 1024u * 1024u)
Definition at line 26 of file copy_internal.h.
XRDC_RESILIENT_FLOOR
#define XRDC_RESILIENT_FLOOR (256u * 1024u)
Definition at line 38 of file copy_internal.h.
XRDC_WEB_TIMEOUT_MS
#define XRDC_WEB_TIMEOUT_MS 300000 /* 5 min per-read ceiling for big files */
Definition at line 56 of file copy_internal.h.
Typedef Documentation
pump_sink_fn
typedef int(* pump_sink_fn) (void *ctx, const uint8_t *buf, int64_t off, size_t n, brix_status *st)
Definition at line 35 of file copy_internal.h.
pump_src_fn
typedef ssize_t(* pump_src_fn) (void *ctx, uint8_t *buf, int64_t off, size_t cap, brix_status *st)
Definition at line 32 of file copy_internal.h.
Function Documentation
atomic_dest_finish()
int atomic_dest_finish (const char * tmp, const char * dest, int rc, brix_status * st)
Definition at line 77 of file copy_local.c.
References brix_status_set(), and XRDC_ESOCK.
Referenced by copy_web_download().
cksum_verify()
int cksum_verify (brix_conn * c, const char * remote_path, const char * local_path, const char * spec, int silent, brix_status * st)
Definition at line 269 of file copy_remote.c.
References c, cksum_compute_local(), cksum_parse_spec(), cksum_verify_literal(), cksum_verify_source(), cksum_spec_t::mode, cksum_spec_t::name, cksum_spec_t::silent, XRDC_CK_OK, and XRDC_CK_UNVERIFIED.
Referenced by download_reconcile_cksum(), and upload_reconcile_cksum().
copy_block()
int copy_block (const char * src, const char * dst, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 226 of file copy_block.c.
References brix_is_block_url(), brix_status_clear(), brix_status_set(), brix_url_parse(), copy_block_to_remote(), copy_remote_to_block(), copy_vfs_to_vfs(), brix_copy_opts::recursive, brix_url::scheme, XRDC_EUSAGE, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by brix_copy().
copy_block_to_remote()
int copy_block_to_remote (const char * src_url, const char * dst_url, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 96 of file copy_block.c.
References brix_status_clear(), brix_url_parse(), brix_vfs_close(), brix_vfs_fstat(), brix_vfs_open(), brix_vfs_open_opts::cred, brix_vfs_open_opts::expected_size, brix_copy_opts::io_uring, brix_vfs_open_opts::io_uring, brix_url::path, pump_src_local_vfs(), brix_url::scheme, brix_vfs_stat::size, upload_stream_body(), pump_local_t::vf, XRDC_IO_URING_AUTO, XRDC_SCHEME_LOCAL, and XRDC_VFS_READ.
Referenced by copy_block().
copy_download()
int copy_download (const brix_url * su, const brix_url * du, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 412 of file copy_local.c.
References access(), brix_close(), brix_status_set(), brix_streams_close(), download_job_t::c, c, copy_stall_ms(), download_to_local_file(), download_to_stdout(), download_job_t::du, brix_statinfo::flags, brix_copy_opts::force, kXR_isDir, brix_streamset::n, download_job_t::o, brix_url::path, resilient_setup(), brix_url::scheme, download_job_t::si, download_job_t::ss, download_job_t::su, XRDC_EUSAGE, and XRDC_SCHEME_STDIO.
Referenced by brix_copy_dispatch_r2l().
copy_one_l2r()
int copy_one_l2r (brix_conn * c, const char * lpath, const char * rpath, const brix_copy_opts * o, brix_status * st)
Definition at line 196 of file copy.c.
References brix_file_close(), brix_file_open_write(), brix_vfs_close(), brix_vfs_open(), pump_remote_t::c, c, brix_vfs_open_opts::cred, brix_vfs_open_opts::expected_size, pump_remote_t::f, brix_copy_opts::io_uring, brix_vfs_open_opts::io_uring, pump_remote_t::pgrw, brix_copy_opts::posc, pump_sink_remote(), pump_src_local_vfs(), transfer_pump(), pump_local_t::vf, XRDC_IO_URING_AUTO, and XRDC_VFS_READ.
Referenced by tree_ul_file().
copy_one_r2l()
int copy_one_r2l (brix_conn * c, const char * rpath, const char * lpath, int64_t expected_size, brix_status * st)
Definition at line 149 of file copy.c.
References brix_file_close(), brix_file_open_read(), brix_vfs_abort(), brix_vfs_close(), brix_vfs_commit(), brix_vfs_open(), pump_remote_t::c, c, brix_vfs_open_opts::cred, brix_vfs_open_opts::expected_size, pump_remote_t::f, brix_vfs_open_opts::io_uring, pump_remote_t::pgrw, pump_sink_local_vfs(), pump_src_remote(), transfer_pump(), pump_local_t::vf, XRDC_IO_URING_AUTO, XRDC_VFS_FORCE, and XRDC_VFS_WRITE.
Referenced by tree_dl_file().
copy_recursive()
int copy_recursive (const copy_recurse_req * rq, brix_status * st)
Definition at line 730 of file copy_recursive.c.
References brix_close(), brix_connect(), brix_rmdir(), brix_status_clear(), brix_status_set(), c, copy_recurse_req::co, copy_tree_download(), copy_tree_upload(), copy_recurse_req::download, brix_copy_opts::dry_run, copy_recurse_req::du, copy_recurse_req::o, brix_url::path, recursive_dest_root(), brix_copy_opts::remove_source, copy_recurse_req::su, XRDC_EUSAGE, and XRDC_PATH_MAX.
Referenced by brix_copy_dispatch_recursive().
copy_remote_to_block()
int copy_remote_to_block (const char * src_url, const char * dst_url, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 23 of file copy_block.c.
References brix_close(), brix_status_set(), brix_streams_close(), brix_url_parse(), brix_vfs_abort(), brix_vfs_close(), brix_vfs_commit(), brix_vfs_open(), c, copy_stall_ms(), brix_vfs_open_opts::cred, download_stream_body(), brix_vfs_open_opts::expected_size, brix_statinfo::flags, brix_copy_opts::io_uring, brix_vfs_open_opts::io_uring, kXR_isDir, brix_streamset::n, pump_sink_local_vfs(), resilient_setup(), brix_statinfo::size, pump_local_t::vf, XRDC_EUSAGE, XRDC_IO_URING_AUTO, XRDC_VFS_FORCE, and XRDC_VFS_WRITE.
Referenced by copy_block().
copy_remote_to_remote()
int copy_remote_to_remote (const brix_url * su, const brix_url * du, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 74 of file copy_remote.c.
References brix_connect(), brix_file_open_read(), brix_file_open_write(), brix_stat(), brix_status_set(), brix_statinfo::flags, brix_copy_opts::force, kXR_isDir, brix_url::path, brix_copy_opts::posc, r2r_stream_body(), r2r_teardown(), and XRDC_EUSAGE.
Referenced by brix_copy_dispatch_r2r().
copy_signal_handler()
void copy_signal_handler (int sig)
Definition at line 22 of file copy.c.
References g_brix_copy_quit.
Referenced by brix_copy_install_signal_handlers().
copy_stall_ms()
int copy_stall_ms (const brix_copy_opts * o, int dflt)
Definition at line 87 of file copy.c.
References brix_copy_opts::max_stall_ms, and brix_copy_opts::no_retry.
Referenced by copy_download(), copy_remote_to_block(), copy_web_upload(), download_stream_body(), and upload_stream_body().
copy_tpc()
int copy_tpc (const brix_url * su, const brix_url * du, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 587 of file copy_remote.c.
References brix_file_sync(), s, tpc_params_t::su, tpc_run_rendezvous(), tpc_setup_source(), tpc_state_teardown(), and brix_copy_opts::tpc_token_mode.
Referenced by brix_copy_dispatch_r2r().
copy_tree_download()
int copy_tree_download (const copy_walk_ctx * w)
Definition at line 500 of file copy_recursive.c.
References brix_dirlist(), brix_status_set(), copy_walk_ctx::c, brix_copy_opts::dry_run, local_mkdirs(), copy_walk_ctx::lpath, mirror_delete_local(), copy_walk_ctx::o, copy_walk_ctx::rel, copy_walk_ctx::rpath, copy_walk_ctx::st, brix_copy_opts::sync_delete, tree_dl_entry(), and XRDC_ESOCK.
Referenced by copy_recursive(), and tree_dl_entry().
copy_tree_upload()
int copy_tree_upload (const copy_walk_ctx * w)
Definition at line 651 of file copy_recursive.c.
References brix_mkdir(), brix_status_clear(), brix_status_set(), copy_walk_ctx::c, brix_copy_opts::dry_run, copy_walk_ctx::lpath, mirror_delete_remote(), copy_walk_ctx::o, copy_walk_ctx::rel, copy_walk_ctx::rpath, copy_walk_ctx::st, brix_copy_opts::sync_delete, tree_ul_entry(), and XRDC_ESOCK.
Referenced by copy_recursive(), and tree_ul_entry().
copy_unzip()
int copy_unzip (const brix_url * su, const char * archive_path, const char * member, const brix_url * du, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 173 of file copy_zip.c.
References brix_close(), brix_connect(), brix_file_close(), brix_file_open_read(), brix_stat(), zip_remote_ctx::c, c, close(), copy_unzip_extract_member(), copy_unzip_finalize(), copy_unzip_open_dest(), zip_remote_ctx::f, brix_url::scheme, brix_statinfo::size, zip_remote_ctx::st, XRDC_PATH_MAX, and XRDC_SCHEME_STDIO.
Referenced by brix_copy_dispatch_r2l().
copy_upload()
int copy_upload (const brix_url * su, const brix_url * du, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 690 of file copy_local.c.
References brix_status_clear(), brix_vfs_close(), brix_vfs_fstat(), brix_vfs_open(), brix_vfs_open_opts::cred, brix_vfs_open_opts::expected_size, brix_copy_opts::io_uring, brix_vfs_open_opts::io_uring, brix_url::path, pump_src_local(), pump_src_local_vfs(), brix_url::scheme, brix_vfs_stat::size, upload_stream_body(), pump_local_t::vf, XRDC_SCHEME_STDIO, and XRDC_VFS_READ.
Referenced by brix_copy_route().
copy_vfs_to_vfs()
int copy_vfs_to_vfs (const char * src_url, const char * dst_url, const brix_copy_opts * o, brix_status * st)
Definition at line 161 of file copy_block.c.
References brix_status_clear(), brix_vfs_abort(), brix_vfs_close(), brix_vfs_commit(), brix_vfs_fstat(), brix_vfs_open(), brix_vfs_open_opts::cred, brix_vfs_open_opts::expected_size, brix_copy_opts::io_uring, brix_vfs_open_opts::io_uring, pump_sink_local_vfs(), pump_src_local_vfs(), brix_vfs_stat::size, transfer_pump(), pump_local_t::vf, XRDC_IO_URING_AUTO, XRDC_VFS_FORCE, XRDC_VFS_READ, and XRDC_VFS_WRITE.
Referenced by copy_block().
copy_web()
int copy_web (const char * src, const char * dst, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 809 of file copy_local.c.
References brix_is_web_url(), brix_status_set(), brix_url_parse(), brix_weburl_parse(), copy_web_download(), copy_web_upload(), brix_copy_opts::recursive, brix_url::scheme, XRDC_EUSAGE, XRDC_SCHEME_LOCAL, and XRDC_SCHEME_STDIO.
Referenced by brix_copy().
copy_web_download()
int copy_web_download (const web_dl_req * rq, brix_status * st)
Definition at line 932 of file copy_recursive.c.
References access(), atomic_dest_finish(), web_dl_io::blen, brix_status_set(), close(), web_dl_req::co, web_dl_req::du, brix_copy_opts::force, web_dl_req::o, open_download_temp(), web_dl_io::outfd, brix_url::path, brix_copy_opts::silent, web_dl_io::status, web_dl_req::su, web_dl_req::to_stdout, web_auth_headers(), web_dl_fetch(), XRDC_EUSAGE, and XRDC_PATH_MAX.
Referenced by copy_web().
copy_web_upload()
int copy_web_upload (const brix_url * su, const brix_weburl * du, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 744 of file copy_local.c.
References brix_http_upload_resumable(), brix_status_set(), brix_vfs_close(), brix_vfs_fstat(), brix_vfs_open(), brix_opts::ca_dir, copy_stall_ms(), brix_vfs_open_opts::cred, brix_vfs_open_opts::expected_size, brix_weburl::host, brix_copy_opts::io_uring, brix_vfs_open_opts::io_uring, brix_vfs_stat::is_dir, brix_url::path, brix_weburl::path, brix_weburl::port, brix_url::scheme, brix_copy_opts::silent, brix_vfs_stat::size, brix_weburl::tls, brix_opts::verify_host, web_auth_headers(), web_upload_src_vfs(), XRDC_DEFAULT_MAX_STALL_MS, XRDC_EUSAGE, XRDC_SCHEME_STDIO, XRDC_VFS_READ, and XRDC_WEB_TIMEOUT_MS.
Referenced by copy_web().
copy_zip_store()
int copy_zip_store (const brix_url * su, const brix_url * du, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 465 of file copy_zip.c.
References brix_status_set(), close(), copy_zip_store_local(), copy_zip_store_remote(), open(), brix_url::path, brix_url::scheme, XRDC_EUSAGE, XRDC_SCHEME_ROOT, XRDC_SCHEME_ROOTS, XRDC_SCHEME_STDIO, brix_copy_opts::zip_append, and zip_member_basename().
Referenced by brix_copy_route().
copy_zip_store_local()
int copy_zip_store_local (const char * member, int srcfd, const brix_url * du, int append, brix_status * st)
Definition at line 360 of file copy_zip.c.
References brix_status_set(), brix_zip_writer_free(), brix_zip_writer_new(), brix_zip_writer_new_append(), close(), zipw_local_sink::fd, fstat(), zipw_local_sink::off, open(), brix_url::path, stat(), XRDC_EUSAGE, zip_emit_member(), zip_read_seed(), zipw_local_pread(), and zipw_local_write().
Referenced by copy_zip_store().
copy_zip_store_remote()
int copy_zip_store_remote (const char * member, int srcfd, const brix_url * du, int append, const brix_opts * co, brix_status * st)
Definition at line 403 of file copy_zip.c.
References brix_close(), brix_connect(), brix_file_close(), brix_file_open_update(), brix_file_open_write(), brix_stat(), brix_status_clear(), brix_zip_writer_free(), brix_zip_writer_new(), brix_zip_writer_new_append(), zipw_remote_sink::c, c, zipw_remote_sink::f, zipw_remote_sink::off, brix_url::path, brix_statinfo::size, zipw_remote_sink::st, zip_emit_member(), zip_read_seed(), zip_remote_pread(), and zipw_remote_write().
Referenced by copy_zip_store().
download_stream_body()
int download_stream_body (const download_body_ctx * j, pump_sink_fn sink, void * sinkctx, brix_status * st)
Definition at line 212 of file copy_local.c.
References brix_file_close(), brix_mono_ns(), brix_status_clear(), brix_streams_open(), pump_remote_t::c, download_body_ctx::c, copy_stream_ctx_t::c, c, brix_copy_opts::compress, copy_stall_ms(), pump_remote_t::cur_chunk, copy_stream_ctx_t::deadline_ns, download_open_resilient(), pump_remote_t::f, pump_remote_t::max_stall_ms, download_body_ctx::o, pump_remote_t::opaque, copy_stream_ctx_t::opaque, brix_url::path, pump_remote_t::path, copy_stream_ctx_t::path, brix_copy_opts::pgrw, pump_remote_t::pgrw, pump_src_remote(), pump_remote_t::resilient, download_body_ctx::si, brix_statinfo::size, download_body_ctx::ss, brix_copy_opts::streams, download_body_ctx::su, transfer_pump(), and XRDC_COPY_CHUNK.
Referenced by copy_remote_to_block(), download_to_local_file(), and download_to_stdout().
gen_tpc_key()
int gen_tpc_key (char * out, size_t outsz)
Definition at line 313 of file copy_remote.c.
References brix_hex_encode(), close(), open(), and read().
Referenced by tpc_setup_source().
make_temp_path()
int make_temp_path (const char * dst, char * out, size_t outsz)
Definition at line 19 of file copy_local.c.
References s.
Referenced by open_download_temp().
open_download_temp()
int open_download_temp (const char * dst, char * tmp, size_t tmpsz, brix_status * st)
Definition at line 44 of file copy_local.c.
References brix_status_set(), make_temp_path(), open(), and XRDC_EUSAGE.
Referenced by copy_unzip_open_dest(), and copy_web_download().
pump_remote_reopen()
int pump_remote_reopen (pump_remote_t * r, brix_status * st)
Definition at line 41 of file copy_pump.c.
References brix_file_open_opaque(), brix_file_open_read(), brix_reconnect(), pump_remote_t::c, pump_remote_t::f, brix_conn::home_host, brix_conn::home_port, host, brix_conn::host, pump_remote_t::opaque, pump_remote_t::path, port, and brix_conn::port.
Referenced by pump_src_remote().
pump_sink_local()
int pump_sink_local (void * ctx, const uint8_t * buf, int64_t off, size_t n, brix_status * st)
Definition at line 169 of file copy_pump.c.
References write_all().
Referenced by download_to_stdout().
pump_sink_local_vfs()
int pump_sink_local_vfs (void * ctx, const uint8_t * buf, int64_t off, size_t n, brix_status * st)
Definition at line 195 of file copy_pump.c.
References brix_vfs_pwrite(), and pump_local_t::vf.
Referenced by copy_one_r2l(), copy_remote_to_block(), copy_vfs_to_vfs(), and download_to_local_file().
pump_sink_remote()
int pump_sink_remote (void * ctx, const uint8_t * buf, int64_t off, size_t n, brix_status * st)
Definition at line 114 of file copy_pump.c.
References brix_backoff_sleep_fast(), brix_copy_quit_requested(), brix_file_pgwrite(), brix_file_write(), brix_mono_ns(), brix_status_retryable(), pump_remote_t::c, pump_remote_t::f, pump_remote_t::max_stall_ms, pump_remote_t::pgrw, pump_sink_reopen(), and pump_remote_t::resilient.
Referenced by copy_one_l2r(), r2r_stream_body(), and upload_stream_body().
pump_sink_reopen()
int pump_sink_reopen (pump_remote_t * r, brix_status * st)
Definition at line 97 of file copy_pump.c.
References brix_file_open_update(), brix_reconnect(), pump_remote_t::c, pump_remote_t::f, brix_conn::home_host, brix_conn::home_port, host, brix_conn::host, pump_remote_t::path, port, brix_conn::port, and pump_remote_t::posc.
Referenced by pump_sink_remote(), and upload_close_commit_resilient().
pump_src_local()
ssize_t pump_src_local (void * ctx, uint8_t * buf, int64_t off, size_t cap, brix_status * st)
Definition at line 150 of file copy_pump.c.
References brix_status_set(), read(), and XRDC_ESOCK.
Referenced by copy_upload().
pump_src_local_vfs()
ssize_t pump_src_local_vfs (void * ctx, uint8_t * buf, int64_t off, size_t cap, brix_status * st)
Definition at line 186 of file copy_pump.c.
References brix_vfs_pread(), and pump_local_t::vf.
Referenced by copy_block_to_remote(), copy_one_l2r(), copy_upload(), and copy_vfs_to_vfs().
pump_src_remote()
ssize_t pump_src_remote (void * ctx, uint8_t * buf, int64_t off, size_t cap, brix_status * st)
Definition at line 61 of file copy_pump.c.
References brix_backoff_sleep_fast(), brix_copy_quit_requested(), brix_file_pgread(), brix_file_read(), brix_mono_ns(), brix_status_retryable(), pump_remote_t::c, pump_remote_t::cur_chunk, pump_remote_t::f, pump_remote_t::max_stall_ms, pump_remote_t::pgrw, pump_remote_reopen(), pump_remote_t::resilient, and XRDC_RESILIENT_FLOOR.
Referenced by copy_one_r2l(), download_stream_body(), and r2r_stream_body().
r2r_stream_body()
int r2r_stream_body (brix_conn * sc, brix_conn * dc, brix_file * sf, brix_file * df, const brix_statinfo * si, const brix_copy_opts * o, brix_status * st)
Definition at line 61 of file copy_remote.c.
References pump_remote_t::c, brix_copy_opts::pgrw, pump_sink_remote(), pump_src_remote(), brix_statinfo::size, and transfer_pump().
Referenced by copy_remote_to_remote().
r2r_teardown()
int r2r_teardown (brix_conn * sc, brix_conn * dc, brix_file * sf, brix_file * df, int src_up, int dst_up, int sopen, int dopen, int rc, brix_status * st)
Definition at line 27 of file copy_remote.c.
References brix_close(), brix_file_close(), and brix_status_clear().
Referenced by copy_remote_to_remote().
recursive_dest_root()
int recursive_dest_root (const char * dstdir, const char * srcpath, char * out, size_t outsz)
Definition at line 699 of file copy_recursive.c.
Referenced by copy_recursive().
resilient_setup()
int resilient_setup (brix_conn * c, const brix_url * su, const brix_opts * co, brix_statinfo * si, int max_stall_ms, brix_status * st)
Definition at line 107 of file copy.c.
References brix_backoff_sleep_fast(), brix_close(), brix_connect(), brix_copy_quit_requested(), brix_mono_ns(), brix_stat(), brix_status_retryable(), c, brix_status::kxr, brix_url::path, brix_status::sys_errno, and XRDC_ESOCK.
Referenced by copy_download(), and copy_remote_to_block().
tpc_teardown()
int tpc_teardown (brix_conn * sc, brix_conn * dc, brix_file * sf, brix_file * df, char * src_opaque, char * dst_opaque, int su_up, int du_up, int sopen, int dopen, int rc, brix_status * st)
Definition at line 377 of file copy_remote.c.
References brix_close(), brix_file_close(), and brix_status_clear().
Referenced by tpc_state_teardown().
transfer_pump()
int transfer_pump (pump_src_fn src, void * sctx, pump_sink_fn sink, void * kctx, int64_t expected, const brix_copy_opts * o, int64_t progress_total, brix_status * st)
Definition at line 237 of file copy_pump.c.
References brix_status_set(), g_brix_copy_quit, pump_emit_progress(), XRDC_COPY_CHUNK, XRDC_EPROTO, and XRDC_ESOCK.
Referenced by copy_one_l2r(), copy_one_r2l(), copy_vfs_to_vfs(), download_stream_body(), r2r_stream_body(), and upload_stream_body().
unzip_member_from_src()
int unzip_member_from_src (const char * src, const brix_url * su, char * member, size_t member_sz, char * arch, size_t arch_sz)
Definition at line 222 of file copy_zip.c.
References brix_url::path.
Referenced by brix_copy_dispatch_r2l().
unzip_sink_write()
int unzip_sink_write (void * sc, const uint8_t * d, size_t l)
Definition at line 20 of file copy_zip.c.
References s.
Referenced by copy_unzip_extract_member().
upload_stream_body()
int upload_stream_body (const upload_body_ctx * j, pump_src_fn src, void * srcctx, brix_status * st)
Definition at line 607 of file copy_local.c.
References brix_close(), brix_connect_resilient(), brix_mono_ns(), brix_streams_close(), brix_streams_open(), pump_remote_t::c, copy_stream_ctx_t::c, c, brix_copy_opts::cksum, upload_body_ctx::co, brix_copy_opts::compress, copy_stall_ms(), copy_stream_ctx_t::deadline_ns, upload_body_ctx::du, pump_remote_t::f, brix_copy_opts::force, pump_remote_t::max_stall_ms, brix_streamset::n, upload_body_ctx::o, copy_stream_ctx_t::opaque, brix_url::path, pump_remote_t::path, copy_stream_ctx_t::path, brix_copy_opts::pgrw, pump_remote_t::pgrw, brix_copy_opts::posc, pump_remote_t::posc, pump_sink_remote(), pump_remote_t::resilient, brix_copy_opts::streams, upload_body_ctx::su, upload_body_ctx::total, transfer_pump(), upload_close_commit_resilient(), upload_open_resilient(), upload_reconcile_cksum(), and brix_file::write_codec.
Referenced by copy_block_to_remote(), and copy_upload().
web_auth_headers()
int web_auth_headers (const web_auth_ctx * a, char * hdrs, size_t hdrsz)
Definition at line 897 of file copy_recursive.c.
References auth_hdr_bearer(), auth_hdr_s3(), web_auth_ctx::co, brix_weburl::is_s3, web_auth_ctx::o, web_auth_ctx::st, and web_auth_ctx::u.
Referenced by copy_web_download(), and copy_web_upload().
write_all()
int write_all (int fd, const uint8_t * buf, size_t n, brix_status * st)
Definition at line 9 of file copy_pump.c.
References brix_status_set(), and XRDC_ESOCK.
Referenced by pump_sink_local().
zip_emit_member()
int zip_emit_member (brix_zip_writer * w, const char * member, int srcfd, brix_status * st)
Definition at line 343 of file copy_zip.c.
References brix_status_set(), brix_zip_writer_add_fd(), brix_zip_writer_finish(), XRDC_EPROTO, XRDC_ESOCK, and XRDC_ZIP_OK.
Referenced by copy_zip_store_local(), and copy_zip_store_remote().
zip_member_basename()
const char * zip_member_basename (const char * p)
Definition at line 293 of file copy_zip.c.
References s.
Referenced by copy_zip_store().
zip_read_seed()
int zip_read_seed (brix_zip_pread_fn pr, void * ctx, uint64_t size, uint64_t * base, uint8_t ** seed_cd, size_t * seed_len, size_t * seed_n, brix_status * st)
Definition at line 304 of file copy_zip.c.
References brix_status_set(), brix_zip_read_eocd(), XRDC_EPROTO, XRDC_ESOCK, XRDC_EUSAGE, and XRDC_ZIP_OK.
Referenced by copy_zip_store_local(), and copy_zip_store_remote().
zip_remote_pread()
ssize_t zip_remote_pread (void * vctx, uint64_t off, void * buf, size_t len)
Definition at line 11 of file copy_zip.c.
References brix_file_read(), zip_remote_ctx::c, zip_remote_ctx::f, and zip_remote_ctx::st.
Referenced by copy_unzip_extract_member(), and copy_zip_store_remote().
zipw_local_pread()
ssize_t zipw_local_pread (void * cx, uint64_t off, void * buf, size_t len)
Definition at line 286 of file copy_zip.c.
References pread().
Referenced by copy_zip_store_local().
zipw_local_write()
int zipw_local_write (void * cx, const void * d, size_t n)
Definition at line 261 of file copy_zip.c.
References s.
Referenced by copy_zip_store_local().
zipw_remote_write()
int zipw_remote_write (void * cx, const void * d, size_t n)
Definition at line 274 of file copy_zip.c.
References brix_file_write(), and s.
Referenced by copy_zip_store_remote().
Variable Documentation
g_brix_copy_quit
volatile sig_atomic_t g_brix_copy_quit extern
Definition at line 18 of file copy.c.
Referenced by brix_copy_quit_requested(), copy_signal_handler(), and transfer_pump().