nginx-xrootd: client/lib/xfer/copy.c File Reference
copy.c File Reference
#include "copy_internal.h"
Functions
const brix_vfs_backend * brix_vfs_posix_backend (void)
const brix_vfs_backend * brix_vfs_block_backend (void)
void copy_signal_handler (int sig)
int brix_copy_quit_requested (void)
void brix_copy_install_signal_handlers (void)
int copy_stall_ms (const brix_copy_opts *o, int dflt)
int resilient_setup (brix_conn *c, const brix_url *su, const brix_opts *co, brix_statinfo *si, int max_stall_ms, brix_status *st)
int copy_one_r2l (brix_conn *c, const char *rpath, const char *lpath, int64_t expected_size, brix_status *st)
int copy_one_l2r (brix_conn *c, const char *lpath, const char *rpath, const brix_copy_opts *o, brix_status *st)
int brix_copy (const char *src, const char *dst, const brix_copy_opts *o, const brix_opts *co_in, brix_status *st)
Variables
static const brix_vfs_backend *(*const s_vfs_posix_anchor)(void)
static const brix_vfs_backend *(*const s_vfs_block_anchor)(void)
volatile sig_atomic_t g_brix_copy_quit
Function Documentation
brix_copy()
int brix_copy (const char * src, const char * dst, const brix_copy_opts * o, const brix_opts * co_in, brix_status * st)
Definition at line 237 of file copy.c.
References brix_is_block_url(), brix_is_web_url(), brix_status_set(), brix_url_parse(), copy_block(), copy_download(), copy_recursive(), copy_remote_to_remote(), copy_tpc(), copy_unzip(), copy_upload(), copy_web(), copy_zip_store(), brix_status::msg, brix_opts::no_retry, brix_copy_opts::recursive, brix_url::scheme, brix_copy_opts::silent, brix_copy_opts::tpc_mode, unzip_member_from_src(), brix_opts::verify_host, XRDC_EUSAGE, XRDC_PATH_MAX, XRDC_SCHEME_LOCAL, XRDC_SCHEME_ROOT, XRDC_SCHEME_ROOTS, XRDC_SCHEME_STDIO, XRDC_TPC_DELEGATE, XRDC_TPC_FIRST, XRDC_TPC_ONLY, brix_copy_opts::zip, and brix_copy_opts::zip_append.
Referenced by copy_one_with_retry(), and do_bench().
brix_copy_install_signal_handlers()
void brix_copy_install_signal_handlers (void)
Definition at line 37 of file copy.c.
References copy_signal_handler().
Referenced by main().
brix_copy_quit_requested()
int brix_copy_quit_requested (void)
Definition at line 30 of file copy.c.
References g_brix_copy_quit.
Referenced by brix_tls_read(), brix_tls_write(), download_stream_body(), plain_read_full(), plain_write_full(), pump_sink_remote(), pump_src_remote(), resilient_setup(), sleep_ms_cancelable(), upload_stream_body(), and wait_io().
brix_vfs_block_backend()
const brix_vfs_backend * brix_vfs_block_backend (void) extern
Definition at line 510 of file vfs_block.c.
brix_vfs_posix_backend()
const brix_vfs_backend * brix_vfs_posix_backend (void) extern
Definition at line 557 of file vfs_posix.c.
copy_one_l2r()
int copy_one_l2r (brix_conn * c, const char * lpath, const char * rpath, const brix_copy_opts * o, brix_status * st)
Definition at line 196 of file copy.c.
References brix_file_close(), brix_file_open_write(), brix_vfs_close(), brix_vfs_open(), pump_remote_t::c, c, brix_vfs_open_opts::cred, brix_vfs_open_opts::expected_size, pump_remote_t::f, brix_copy_opts::io_uring, brix_vfs_open_opts::io_uring, pump_remote_t::pgrw, brix_copy_opts::posc, pump_sink_remote(), pump_src_local_vfs(), transfer_pump(), pump_local_t::vf, XRDC_IO_URING_AUTO, and XRDC_VFS_READ.
Referenced by copy_tree_upload().
copy_one_r2l()
int copy_one_r2l (brix_conn * c, const char * rpath, const char * lpath, int64_t expected_size, brix_status * st)
Definition at line 149 of file copy.c.
References brix_file_close(), brix_file_open_read(), brix_vfs_abort(), brix_vfs_close(), brix_vfs_commit(), brix_vfs_open(), pump_remote_t::c, c, brix_vfs_open_opts::cred, brix_vfs_open_opts::expected_size, pump_remote_t::f, brix_vfs_open_opts::io_uring, pump_remote_t::pgrw, pump_sink_local_vfs(), pump_src_remote(), transfer_pump(), pump_local_t::vf, XRDC_IO_URING_AUTO, XRDC_VFS_FORCE, and XRDC_VFS_WRITE.
Referenced by copy_tree_download().
copy_signal_handler()
void copy_signal_handler (int sig)
Definition at line 22 of file copy.c.
References g_brix_copy_quit.
Referenced by brix_copy_install_signal_handlers().
copy_stall_ms()
int copy_stall_ms (const brix_copy_opts * o, int dflt)
Definition at line 87 of file copy.c.
References brix_copy_opts::max_stall_ms, and brix_copy_opts::no_retry.
Referenced by copy_download(), copy_remote_to_block(), copy_web_upload(), download_stream_body(), and upload_stream_body().
resilient_setup()
int resilient_setup (brix_conn * c, const brix_url * su, const brix_opts * co, brix_statinfo * si, int max_stall_ms, brix_status * st)
Definition at line 107 of file copy.c.
References brix_backoff_sleep_fast(), brix_close(), brix_connect(), brix_copy_quit_requested(), brix_mono_ns(), brix_stat(), brix_status_retryable(), c, brix_status::kxr, brix_url::path, brix_status::sys_errno, and XRDC_ESOCK.
Referenced by copy_download(), and copy_remote_to_block().
Variable Documentation
g_brix_copy_quit
volatile sig_atomic_t g_brix_copy_quit
Definition at line 18 of file copy.c.
Referenced by brix_copy_quit_requested(), copy_signal_handler(), and transfer_pump().
s_vfs_block_anchor
const brix_vfs_backend *(*const s_vfs_block_anchor) (void) (void) static
Initial value:
=
    brix_vfs_block_backend
Definition at line 15 of file copy.c.
s_vfs_posix_anchor
const brix_vfs_backend *(*const s_vfs_posix_anchor) (void) (void) static
Initial value:
=
    brix_vfs_posix_backend
Definition at line 11 of file copy.c.