nginx-xrootd: client/lib/protocols/shared/checksum.c File Reference
checksum.c File Reference
#include "brix.h"
#include "core/compat/checksum_core.h"
#include "core/compat/hex.h"
#include <arpa/inet.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
int brix_cksum_algo_parse (const char *name, brix_cksum_algo *out)
int brix_cksum_fd (int fd, brix_cksum_algo algo, char *hex, size_t hexsz, brix_status *st)
int brix_query_cksum (brix_conn *c, const char *path, const char *algo_name, char *hex, size_t hexsz, brix_status *st)
Function Documentation
brix_cksum_algo_parse()
int brix_cksum_algo_parse (const char * name, brix_cksum_algo * out)
Definition at line 29 of file checksum.c.
References name, XRDC_CK_ADLER32, XRDC_CK_CRC32C, XRDC_CK_CRC64, XRDC_CK_CRC64NVME, XRDC_CK_MD5, and XRDC_CK_ZCRC32.
Referenced by brix_cks_verify_file(), brix_xrdckcheck_main(), brix_xrdcktree_main(), cksum_verify(), cmd_verify(), entry_cksum(), and sync_cksum_match().
brix_cksum_fd()
int brix_cksum_fd (int fd, brix_cksum_algo algo, char * hex, size_t hexsz, brix_status * st)
Definition at line 45 of file checksum.c.
References BRIX_CK_ADLER32, BRIX_CK_CRC32C, BRIX_CK_CRC64, BRIX_CK_CRC64NVME, BRIX_CK_MD5, BRIX_CK_ZCRC32, brix_cksum_digest_fd(), brix_cksum_u32_fd(), brix_cksum_u64_fd(), brix_hex_encode(), brix_status_set(), hex(), XRDC_CK_ADLER32, XRDC_CK_CRC64, XRDC_CK_CRC64NVME, XRDC_CK_MD5, XRDC_CK_ZCRC32, XRDC_ESOCK, and XRDC_EUSAGE.
Referenced by battery_root(), brix_cks_verify_file(), brix_cli_cksum_main(), brix_xrdckcheck_main(), cksum_verify(), cmd_verify(), do_check(), do_compare_davs(), dx_probe_checksum(), entry_cksum(), remote_md5(), sync_cksum_match(), and walk_local_tree().
brix_query_cksum()
int brix_query_cksum (brix_conn * c, const char * path, const char * algo_name, char * hex, size_t hexsz, brix_status * st)
Definition at line 103 of file checksum.c.
References brix_roundtrip_resilient(), brix_status_set(), c, hex(), xrdw_query_req_t::infotype, kXR_Qcksum, kXR_query, ClientQueryRequest::requestid, XRDC_EPROTO, XRDC_EUSAGE, XRDC_OP_READONLY, XRDC_PATH_MAX, and xrdw_query_req_pack().