nginx-xrootd: client/lib/auth/auth.c File Reference
auth.c File Reference
#include "sec/sec.h"
#include "protocols/root/protocol/sec_protocol.h"
#include "protocols/root/protocol/codec/wire_codec.h"
#include <arpa/inet.h>
#include <stdlib.h>
#include <string.h>
Macros
#define XRDC_AUTH_MAX_ROUNDS 8
Functions
static int send_auth (brix_conn *c, const char credtype[4], const uint8_t *payload, uint32_t plen, uint16_t *sid, brix_status *st)
static int run_module (brix_conn *c, const brix_sec_module *m, const char *parms, brix_status *st)
static int build_module_list (const brix_sec_module *mods[7])
static int module_candidate (brix_conn *c, const brix_sec_module *m, const brix_opts *o, const char *seclist, char *parms, size_t parmslen)
static void auth_warn_fallback (const brix_sec_module *m, const brix_status *st)
int brix_authenticate (brix_conn *c, const char *seclist, const brix_opts *o, brix_status *st)
void brix_auth_explain (brix_conn *c, const brix_opts *o, FILE *out)
Macro Definition Documentation
XRDC_AUTH_MAX_ROUNDS
#define XRDC_AUTH_MAX_ROUNDS 8
Definition at line 21 of file auth.c.
Function Documentation
auth_warn_fallback()
static void auth_warn_fallback (const brix_sec_module * m, const brix_status * st) static
Definition at line 189 of file auth.c.
References brix_status::msg, and brix_sec_module::name.
Referenced by brix_authenticate().
brix_auth_explain()
void brix_auth_explain (brix_conn * c, const brix_opts * o, FILE * out)
Definition at line 241 of file auth.c.
References brix_opts::auth_force, brix_sec_proto_advertised(), build_module_list(), c, brix_sec_module::have_creds, and brix_sec_module::name.
Referenced by brix_explain_conn().
brix_authenticate()
int brix_authenticate (brix_conn * c, const char * seclist, const brix_opts * o, brix_status * st)
Definition at line 198 of file auth.c.
References brix_opts::auth_force, auth_warn_fallback(), brix_status_set(), build_module_list(), c, brix_opts::force_anon, module_candidate(), brix_sec_module::name, run_module(), and XRDC_EAUTH.
Referenced by do_login().
build_module_list()
static int build_module_list (const brix_sec_module * mods[7]) static
Definition at line 123 of file auth.c.
References brix_sec_gsi(), brix_sec_host(), brix_sec_krb5(), brix_sec_pwd(), brix_sec_sss(), brix_sec_token(), and brix_sec_unix().
Referenced by brix_auth_explain(), and brix_authenticate().
module_candidate()
static int module_candidate (brix_conn * c, const brix_sec_module * m, const brix_opts * o, const char * seclist, char * parms, size_t parmslen) static
Definition at line 156 of file auth.c.
References brix_opts::auth_force, brix_sec_proto_advertised(), c, brix_sec_module::have_creds, and brix_sec_module::name.
Referenced by brix_authenticate().
run_module()
static int run_module (brix_conn * c, const brix_sec_module * m, const char * parms, brix_status * st) static
Definition at line 42 of file auth.c.
References brix_recv(), brix_status_set(), c, brix_sec_module::cleanup, brix_sec_module::credtype, brix_sec_module::first, kXR_authmore, kXR_ok, brix_sec_module::more, brix_sec_module::name, send_auth(), XRDC_AUTH_MAX_ROUNDS, and XRDC_EAUTH.
Referenced by brix_authenticate().
send_auth()
static int send_auth (brix_conn * c, const char credtype[4], const uint8_t * payload, uint32_t plen, uint16_t * sid, brix_status * st) static
Definition at line 24 of file auth.c.
References brix_send(), c, xrdw_auth_req_t::credtype, kXR_auth, ClientAuthRequest::requestid, and xrdw_auth_req_pack().
Referenced by run_module().