nginx-xrootd: src/auth/impersonate/client.c File Reference
client.c File Reference
#include "impersonate.h"
#include "impersonate_proto.h"
#include <errno.h>
#include <string.h>
#include <unistd.h>
#include <sys/socket.h>
#include <sys/un.h>
Functions
static int imp_dial (void)
static int imp_ensure_conn (void)
static void imp_drop_conn (void)
ngx_int_t brix_imp_client_connect (const char *path, ngx_log_t *log)
int brix_imp_client_active (void)
int brix_imp_enabled (void)
void brix_imp_mark_in_request (int on)
void brix_imp_set_principal (const char *principal)
void brix_imp_clear_principal (void)
static int imp_write_full (int fd, const void *buf, size_t n)
static int imp_recv_reply (int fd, imp_rep_t *rep, int *out_fd, char *data_buf, size_t data_bufsz)
static void imp_build_req (imp_req_t *req, uint32_t op, const char *path, const char *path2, uint32_t flags, uint32_t mode, int64_t length)
static int imp_status_errno (int status)
static int imp_exchange (const imp_req_t *req, imp_rep_t *rep, int *out_fd, char *data_buf, size_t data_bufsz, const void *data_in, size_t data_in_len)
static int imp_call_status (uint32_t op, const char *path, const char *path2, uint32_t mode, int64_t length)
int brix_imp_open (const char *reqpath, int flags, mode_t mode)
static void imp_unpack_stat (struct stat *st, const imp_stat_t *s)
int brix_imp_stat (const char *reqpath, struct stat *st, int nofollow)
int brix_imp_mkdir (const char *reqpath, mode_t mode)
int brix_imp_unlink (const char *reqpath, int is_dir)
int brix_imp_rmdir (const char *reqpath)
int brix_imp_rename (const char *src, const char *dst)
int brix_imp_rename_noreplace (const char *src, const char *dst)
int brix_imp_link (const char *src, const char *dst)
int brix_imp_truncate (const char *reqpath, off_t length)
int brix_imp_chmod (const char *reqpath, mode_t mode)
int brix_imp_chown_gid (const char *reqpath, gid_t gid)
int brix_imp_setattr (const char *reqpath, int set_times, const struct timespec times[2], int set_owner, uid_t uid, gid_t gid)
int brix_imp_symlink (const char *target, const char *linkpath)
ssize_t brix_imp_readlink (const char *reqpath, char *buf, size_t bufsz)
static ssize_t imp_get_or_list (uint32_t op, const char *reqpath, const char *name, void *buf, size_t bufsz)
ssize_t brix_imp_getxattr (const char *reqpath, const char *name, void *buf, size_t bufsz)
ssize_t brix_imp_listxattr (const char *reqpath, void *buf, size_t bufsz)
int brix_imp_setxattr (const char *reqpath, const char *name, const void *value, size_t len, int flags)
int brix_imp_removexattr (const char *reqpath, const char *name)
Variables
static int imp_enabled
static int imp_conn_fd = -1
static char imp_sock_path [108]
static ngx_log_t * imp_log
static char imp_principal [512]
static int imp_in_request
Function Documentation
brix_imp_chmod()
int brix_imp_chmod (const char * reqpath, mode_t mode)
Definition at line 477 of file client.c.
References imp_call_status(), IMP_OP_CHMOD, and mode.
Referenced by brix_chmod_confined_canon().
brix_imp_chown_gid()
int brix_imp_chown_gid (const char * reqpath, gid_t gid)
Definition at line 483 of file client.c.
References imp_call_status(), and IMP_OP_CHOWN.
brix_imp_clear_principal()
void brix_imp_clear_principal (void)
Definition at line 165 of file client.c.
References imp_principal.
Referenced by brix_imp_request_end().
brix_imp_client_active()
int brix_imp_client_active (void)
Definition at line 119 of file client.c.
References imp_enabled, imp_in_request, and imp_principal.
Referenced by brix_chmod_confined_canon(), brix_dirlist_access_ok(), brix_getxattr_confined_canon(), brix_link_beneath(), brix_link_confined_canon(), brix_listxattr_confined_canon(), brix_lstat_beneath(), brix_lstat_confined_canon(), brix_mkdir_beneath(), brix_mkdir_confined_canon(), brix_open_beneath(), brix_open_confined_canon(), brix_opendir_confined_canon(), brix_readlink_confined_canon(), brix_removexattr_confined_canon(), brix_rename_beneath(), brix_rename_beneath_excl(), brix_setattr_confined_canon(), brix_setxattr_confined_canon(), brix_stat_beneath(), brix_symlink_confined_canon(), brix_unlink_beneath(), brix_unlink_confined_canon(), and rename_confined_canon_impl().
brix_imp_client_connect()
ngx_int_t brix_imp_client_connect (const char * path, ngx_log_t * log)
Definition at line 93 of file client.c.
References imp_drop_conn(), imp_enabled, imp_ensure_conn(), imp_log, imp_sock_path, and log.
Referenced by brix_imp_init_worker().
brix_imp_enabled()
int brix_imp_enabled (void)
Definition at line 136 of file client.c.
References imp_enabled.
Referenced by brix_dirlist_access_ok(), webdav_copy_collection_post_task(), and webdav_move_collection_post_task().
brix_imp_getxattr()
ssize_t brix_imp_getxattr (const char * reqpath, const char * name, void * buf, size_t bufsz)
Definition at line 596 of file client.c.
References imp_get_or_list(), IMP_OP_GETXATTR, and name.
Referenced by brix_getxattr_confined_canon().
brix_imp_link()
int brix_imp_link (const char * src, const char * dst)
Definition at line 465 of file client.c.
References imp_call_status(), and IMP_OP_LINK.
Referenced by brix_link_beneath(), and brix_link_confined_canon().
brix_imp_listxattr()
ssize_t brix_imp_listxattr (const char * reqpath, void * buf, size_t bufsz)
Definition at line 603 of file client.c.
References imp_get_or_list(), and IMP_OP_LISTXATTR.
Referenced by brix_listxattr_confined_canon().
brix_imp_mark_in_request()
void brix_imp_mark_in_request (int on)
Definition at line 142 of file client.c.
References imp_in_request.
Referenced by brix_imp_request_begin(), and brix_imp_request_end().
brix_imp_mkdir()
int brix_imp_mkdir (const char * reqpath, mode_t mode)
Definition at line 434 of file client.c.
References imp_call_status(), IMP_OP_MKDIR, and mode.
Referenced by brix_mkdir_beneath(), and brix_mkdir_confined_canon().
brix_imp_open()
int brix_imp_open (const char * reqpath, int flags, mode_t mode)
Definition at line 366 of file client.c.
References close(), imp_build_req(), imp_exchange(), IMP_OP_OPEN, IMP_REP_HAS_FD, imp_status_errno(), IMP_STATUS_INTERNAL, mode, imp_rep_t::rep_flags, and imp_rep_t::status.
Referenced by brix_dirlist_access_ok(), brix_open_beneath(), brix_open_confined_canon(), and brix_opendir_confined_canon().
brix_imp_readlink()
ssize_t brix_imp_readlink (const char * reqpath, char * buf, size_t bufsz)
Definition at line 529 of file client.c.
References close(), imp_rep_t::data_len, imp_build_req(), imp_exchange(), IMP_OP_READLINK, IMP_PATH_MAX, IMP_REP_HAS_DATA, imp_status_errno(), IMP_STATUS_INTERNAL, imp_rep_t::rep_flags, and imp_rep_t::status.
Referenced by brix_readlink_confined_canon().
brix_imp_removexattr()
int brix_imp_removexattr (const char * reqpath, const char * name)
Definition at line 635 of file client.c.
References close(), imp_build_req(), imp_exchange(), IMP_OP_REMOVEXATTR, imp_status_errno(), name, and imp_rep_t::status.
Referenced by brix_removexattr_confined_canon().
brix_imp_rename()
int brix_imp_rename (const char * src, const char * dst)
Definition at line 453 of file client.c.
References imp_call_status(), and IMP_OP_RENAME.
Referenced by brix_rename_beneath(), and rename_confined_canon_impl().
brix_imp_rename_noreplace()
int brix_imp_rename_noreplace (const char * src, const char * dst)
Definition at line 459 of file client.c.
References imp_call_status(), and IMP_OP_RENAME_NOREPLACE.
Referenced by brix_rename_beneath_excl(), and rename_confined_canon_impl().
brix_imp_rmdir()
int brix_imp_rmdir (const char * reqpath)
Definition at line 447 of file client.c.
References imp_call_status(), and IMP_OP_RMDIR.
brix_imp_set_principal()
void brix_imp_set_principal (const char * principal)
Definition at line 148 of file client.c.
References imp_principal.
Referenced by brix_imp_request_begin().
brix_imp_setattr()
int brix_imp_setattr (const char * reqpath, int set_times, const struct timespec times[2], int set_owner, uid_t uid, gid_t gid)
Definition at line 490 of file client.c.
References imp_req_t::atime_nsec, imp_req_t::atime_sec, imp_req_t::attr_flags, close(), IMP_ATTR_OWNER, IMP_ATTR_TIMES, imp_build_req(), imp_exchange(), IMP_OP_SETATTR, imp_status_errno(), imp_req_t::mtime_nsec, imp_req_t::mtime_sec, imp_req_t::set_gid, imp_req_t::set_uid, and imp_rep_t::status.
Referenced by brix_setattr_confined_canon().
brix_imp_setxattr()
int brix_imp_setxattr (const char * reqpath, const char * name, const void * value, size_t len, int flags)
Definition at line 609 of file client.c.
References close(), imp_build_req(), imp_exchange(), IMP_OP_SETXATTR, imp_status_errno(), IMP_XATTR_MAX, name, imp_req_t::req_data_len, and imp_rep_t::status.
Referenced by brix_setxattr_confined_canon().
brix_imp_stat()
int brix_imp_stat (const char * reqpath, struct stat * st, int nofollow)
Definition at line 409 of file client.c.
References close(), imp_build_req(), imp_exchange(), IMP_OP_LSTAT, IMP_OP_STAT, IMP_REP_HAS_STAT, imp_status_errno(), IMP_STATUS_INTERNAL, imp_unpack_stat(), imp_rep_t::rep_flags, imp_rep_t::st, and imp_rep_t::status.
Referenced by brix_lstat_beneath(), brix_lstat_confined_canon(), and brix_stat_beneath().
brix_imp_symlink()
int brix_imp_symlink (const char * target, const char * linkpath)
Definition at line 522 of file client.c.
References imp_call_status(), and IMP_OP_SYMLINK.
Referenced by brix_symlink_confined_canon().
brix_imp_truncate()
int brix_imp_truncate (const char * reqpath, off_t length)
Definition at line 471 of file client.c.
References imp_call_status(), and IMP_OP_TRUNCATE.
brix_imp_unlink()
int brix_imp_unlink (const char * reqpath, int is_dir)
Definition at line 440 of file client.c.
References imp_call_status(), IMP_OP_RMDIR, and IMP_OP_UNLINK.
Referenced by brix_unlink_beneath(), and brix_unlink_confined_canon().
imp_build_req()
static void imp_build_req (imp_req_t * req, uint32_t op, const char * path, const char * path2, uint32_t flags, uint32_t mode, int64_t length) static
Definition at line 261 of file client.c.
References IMP_PATH_MAX, IMP_PRINC_MAX, imp_principal, IMP_PROTO_VERSION, imp_req_t::length, imp_req_t::mode, mode, imp_req_t::op, imp_req_t::open_flags, imp_req_t::path, imp_req_t::path2, imp_req_t::principal, and imp_req_t::version.
Referenced by brix_imp_open(), brix_imp_readlink(), brix_imp_removexattr(), brix_imp_setattr(), brix_imp_setxattr(), brix_imp_stat(), imp_call_status(), and imp_get_or_list().
imp_call_status()
static int imp_call_status (uint32_t op, const char * path, const char * path2, uint32_t mode, int64_t length) static
Definition at line 343 of file client.c.
References close(), imp_build_req(), imp_exchange(), imp_status_errno(), mode, and imp_rep_t::status.
Referenced by brix_imp_chmod(), brix_imp_chown_gid(), brix_imp_link(), brix_imp_mkdir(), brix_imp_rename(), brix_imp_rename_noreplace(), brix_imp_rmdir(), brix_imp_symlink(), brix_imp_truncate(), and brix_imp_unlink().
imp_dial()
static int imp_dial (void) static
Definition at line 45 of file client.c.
References close(), imp_sock_path, and socket.
Referenced by imp_ensure_conn().
imp_drop_conn()
static void imp_drop_conn (void) static
Definition at line 84 of file client.c.
References close(), and imp_conn_fd.
Referenced by brix_imp_client_connect(), and imp_exchange().
imp_ensure_conn()
static int imp_ensure_conn (void) static
Definition at line 73 of file client.c.
References imp_conn_fd, and imp_dial().
Referenced by brix_imp_client_connect(), and imp_exchange().
imp_exchange()
static int imp_exchange (const imp_req_t * req, imp_rep_t * rep, int * out_fd, char * data_buf, size_t data_bufsz, const void * data_in, size_t data_in_len) static
Definition at line 307 of file client.c.
References imp_drop_conn(), imp_ensure_conn(), imp_log, imp_recv_reply(), imp_write_full(), and imp_req_t::op.
Referenced by brix_imp_open(), brix_imp_readlink(), brix_imp_removexattr(), brix_imp_setattr(), brix_imp_setxattr(), brix_imp_stat(), imp_call_status(), and imp_get_or_list().
imp_get_or_list()
static ssize_t imp_get_or_list (uint32_t op, const char * reqpath, const char * name, void * buf, size_t bufsz) static
Definition at line 565 of file client.c.
References close(), imp_rep_t::data_len, imp_build_req(), imp_exchange(), IMP_REP_HAS_DATA, imp_status_errno(), IMP_XATTR_MAX, name, imp_rep_t::rep_flags, and imp_rep_t::status.
Referenced by brix_imp_getxattr(), and brix_imp_listxattr().
imp_recv_reply()
static int imp_recv_reply (int fd, imp_rep_t * rep, int * out_fd, char * data_buf, size_t data_bufsz) static
Definition at line 195 of file client.c.
References c, and imp_rep_t::data_len.
Referenced by imp_exchange().
imp_status_errno()
static int imp_status_errno (int status) static
Definition at line 282 of file client.c.
References IMP_STATUS_BADREQ, IMP_STATUS_DENY, IMP_STATUS_INTERNAL, and IMP_STATUS_PRIV_REFUSED.
Referenced by brix_imp_open(), brix_imp_readlink(), brix_imp_removexattr(), brix_imp_setattr(), brix_imp_setxattr(), brix_imp_stat(), imp_call_status(), and imp_get_or_list().
imp_unpack_stat()
static void imp_unpack_stat (struct stat * st, const imp_stat_t * s) static
Definition at line 391 of file client.c.
References s.
Referenced by brix_imp_stat().
imp_write_full()
static int imp_write_full (int fd, const void * buf, size_t n) static
Definition at line 173 of file client.c.
Referenced by imp_exchange().
Variable Documentation
imp_conn_fd
int imp_conn_fd = -1 static
Definition at line 36 of file client.c.
Referenced by imp_drop_conn(), and imp_ensure_conn().
imp_enabled
int imp_enabled static
Definition at line 35 of file client.c.
Referenced by brix_imp_client_active(), brix_imp_client_connect(), and brix_imp_enabled().
imp_in_request
int imp_in_request static
Definition at line 40 of file client.c.
Referenced by brix_imp_client_active(), and brix_imp_mark_in_request().
imp_log
ngx_log_t* imp_log static
Definition at line 38 of file client.c.
Referenced by brix_imp_client_connect(), and imp_exchange().
imp_principal
char imp_principal[512] static
Definition at line 39 of file client.c.
Referenced by brix_imp_clear_principal(), brix_imp_client_active(), brix_imp_set_principal(), and imp_build_req().
imp_sock_path
char imp_sock_path[108] static
Definition at line 37 of file client.c.
Referenced by brix_imp_client_connect(), and imp_dial().