nginx-xrootd: client/lib/fs/vfs.h File Reference
vfs.h File Reference
#include "brix.h"
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>
Data Structures
struct brix_vfs_stat
struct brix_vfs_open_opts
struct brix_vfs_ops
struct brix_vfs_file
struct brix_vfs_backend
Enumerations
enum brix_vfs_oflags { XRDC_VFS_READ = 0x01 , XRDC_VFS_WRITE = 0x02 , XRDC_VFS_RESUME = 0x04 , XRDC_VFS_FORCE = 0x08 }
enum brix_vfs_caps { XRDC_VFS_CAP_RANDOM_WRITE = 0x01 , XRDC_VFS_CAP_TRUNCATE = 0x02 , XRDC_VFS_CAP_ATOMIC_TEMP = 0x04 , XRDC_VFS_CAP_FADVISE = 0x08 }
Functions
int brix_vfs_open (const char *url, int flags, const brix_vfs_open_opts *opts, brix_vfs_file **out, brix_status *st)
int brix_vfs_stat_url (const char *url, const brix_vfs_open_opts *opts, brix_vfs_stat *out, brix_status *st)
ssize_t brix_vfs_pread (brix_vfs_file *f, int64_t off, void *buf, size_t n, brix_status *st)
int brix_vfs_pwrite (brix_vfs_file *f, int64_t off, const void *buf, size_t n, brix_status *st)
int brix_vfs_fstat (brix_vfs_file *f, brix_vfs_stat *out, brix_status *st)
int brix_vfs_truncate (brix_vfs_file *f, int64_t size, brix_status *st)
int brix_vfs_sync (brix_vfs_file *f, brix_status *st)
int brix_vfs_commit (brix_vfs_file *f, brix_status *st)
void brix_vfs_abort (brix_vfs_file *f)
void brix_vfs_close (brix_vfs_file *f)
uint32_t brix_vfs_get_caps (const brix_vfs_file *f)
Enumeration Type Documentation
brix_vfs_caps
enum brix_vfs_caps
Enumerator
XRDC_VFS_CAP_RANDOM_WRITE
XRDC_VFS_CAP_TRUNCATE
XRDC_VFS_CAP_ATOMIC_TEMP
XRDC_VFS_CAP_FADVISE
Definition at line 42 of file vfs.h.
brix_vfs_oflags
enum brix_vfs_oflags
Enumerator
XRDC_VFS_READ
XRDC_VFS_WRITE
XRDC_VFS_RESUME
XRDC_VFS_FORCE
Definition at line 35 of file vfs.h.
Function Documentation
brix_vfs_abort()
void brix_vfs_abort (brix_vfs_file * f)
Definition at line 313 of file vfs.c.
References brix_vfs_ops::abort, and brix_vfs_file::ops.
Referenced by copy_download(), copy_one_r2l(), copy_remote_to_block(), copy_vfs_to_vfs(), and do_download().
brix_vfs_close()
void brix_vfs_close (brix_vfs_file * f)
Definition at line 326 of file vfs.c.
References brix_vfs_ops::close, and brix_vfs_file::ops.
brix_vfs_commit()
int brix_vfs_commit (brix_vfs_file * f, brix_status * st)
Definition at line 300 of file vfs.c.
References brix_vfs_ops::commit, and brix_vfs_file::ops.
Referenced by copy_download(), copy_one_r2l(), copy_remote_to_block(), copy_vfs_to_vfs(), and do_download().
brix_vfs_fstat()
int brix_vfs_fstat (brix_vfs_file * f, brix_vfs_stat * out, brix_status * st)
Definition at line 261 of file vfs.c.
References brix_vfs_ops::fstat, and brix_vfs_file::ops.
Referenced by copy_block_to_remote(), copy_upload(), copy_vfs_to_vfs(), and copy_web_upload().
brix_vfs_get_caps()
uint32_t brix_vfs_get_caps (const brix_vfs_file * f)
Definition at line 340 of file vfs.c.
References brix_vfs_file::caps.
brix_vfs_open()
int brix_vfs_open (const char * url, int flags, const brix_vfs_open_opts * opts, brix_vfs_file ** out, brix_status * st)
Definition at line 161 of file vfs.c.
References brix_status_set(), g_init_once, brix_vfs_backend::open, scheme, vfs_find_backend(), vfs_init_backends(), vfs_url_to_scheme(), and XRDC_EUSAGE.
brix_vfs_pread()
ssize_t brix_vfs_pread (brix_vfs_file * f, int64_t off, void * buf, size_t n, brix_status * st)
Definition at line 233 of file vfs.c.
References brix_vfs_file::ops, and brix_vfs_ops::pread.
Referenced by do_upload(), pump_src_local_vfs(), and web_upload_src_vfs().
brix_vfs_pwrite()
int brix_vfs_pwrite (brix_vfs_file * f, int64_t off, const void * buf, size_t n, brix_status * st)
Definition at line 247 of file vfs.c.
References brix_vfs_file::ops, and brix_vfs_ops::pwrite.
Referenced by do_download(), and pump_sink_local_vfs().
brix_vfs_stat_url()
int brix_vfs_stat_url (const char * url, const brix_vfs_open_opts * opts, brix_vfs_stat * out, brix_status * st)
Definition at line 196 of file vfs.c.
References brix_status_set(), g_init_once, scheme, brix_vfs_backend::stat, vfs_find_backend(), vfs_init_backends(), vfs_url_to_scheme(), and XRDC_EUSAGE.
brix_vfs_sync()
int brix_vfs_sync (brix_vfs_file * f, brix_status * st)
Definition at line 287 of file vfs.c.
References brix_vfs_file::ops, and brix_vfs_ops::sync.
brix_vfs_truncate()
int brix_vfs_truncate (brix_vfs_file * f, int64_t size, brix_status * st)
Definition at line 274 of file vfs.c.
References brix_vfs_file::ops, and brix_vfs_ops::truncate.