nginx-xrootd: client/lib/core/aio/aio.h File Reference
aio.h File Reference
#include "brix.h"
Data Structures
struct brix_aio_opts
Typedefs
typedef void(* brix_aio_cb) (void *ctx, int rc, uint16_t kxr, uint8_t *body, uint32_t blen, const brix_status *st)
Functions
brix_loop * brix_loop_create (brix_status *st)
void brix_loop_destroy (brix_loop *l)
brix_aconn * brix_aconn_attach (brix_loop *l, brix_conn *conn, brix_status *st)
void brix_aconn_close (brix_aconn *ac)
void brix_aconn_set_resilience (brix_aconn *ac, int max_stall_ms, int keepalive_ms, int max_retries)
int brix_aio_submit_ex (brix_aconn *ac, const void *hdr24, const void *payload, uint32_t plen, const brix_aio_opts *opts, brix_aio_cb cb, void *ctx, brix_status *st)
int brix_aio_submit (brix_aconn *ac, const void *hdr24, const void *payload, uint32_t plen, brix_aio_cb cb, void *ctx, int deadline_ms, brix_status *st)
int brix_aio_call (brix_aconn *ac, const void *hdr24, const void *payload, uint32_t plen, uint16_t *kxr, uint8_t **body, uint32_t *blen, int deadline_ms, brix_status *st)
int brix_aio_call_ex (brix_aconn *ac, const void *hdr24, const void *payload, uint32_t plen, const brix_aio_opts *opts, uint16_t *kxr, uint8_t **body, uint32_t *blen, brix_status *st)
brix_mgr * brix_mgr_create (const brix_url *u, const brix_opts *o, int nconns, int eager, int max_stall_ms, int keepalive_ms, int max_retries, brix_status *st)
void brix_mgr_destroy (brix_mgr *m)
brix_aconn * brix_mgr_pick (brix_mgr *m)
int brix_mgr_call (brix_mgr *m, const void *hdr24, const void *payload, uint32_t plen, int retry_safe, uint16_t *kxr, uint8_t **body, uint32_t *blen, brix_status *st)
brix_mfile * brix_mfile_open (brix_aconn *ac, const char *path, int writable, int force, int posc, const char *opaque, int max_stall_ms, int max_retries, brix_status *st)
ssize_t brix_mfile_pread (brix_mfile *mf, int64_t off, void *buf, size_t len, brix_status *st)
int brix_mfile_pwrite (brix_mfile *mf, int64_t off, const void *buf, size_t len, brix_status *st)
int brix_mfile_sync (brix_mfile *mf, brix_status *st)
int brix_mfile_close (brix_mfile *mf, brix_status *st)
Typedef Documentation
brix_aio_cb
typedef void(* brix_aio_cb) (void *ctx, int rc, uint16_t kxr, uint8_t *body, uint32_t blen, const brix_status *st)
Definition at line 52 of file aio.h.
Function Documentation
brix_aconn_attach()
brix_aconn * brix_aconn_attach (brix_loop * l, brix_conn * conn, brix_status * st)
Definition at line 446 of file aio.c.
References ACONN_ALIVE, brix_mono_ns(), brix_status_set(), CMD_ADD_ACONN, brix_aconn::conn, brix_aconn::dead, brix_aconn::def_retries, brix_io::fd, brix_aconn::fd, brix_aconn::inflight, brix_conn::io, brix_aconn::keepalive_ms, brix_aconn::last_activity_ns, brix_aconn::loop, loop_run_control(), brix_aconn::max_stall_ms, brix_aconn::next_sid, brix_conn::signing_active, reqmap::slots, brix_io::ssl, brix_aconn::ssl, brix_aconn::state, brix_aconn::uring_slot, XRDC_EAUTH, XRDC_EPROTO, XRDC_ESOCK, and XRDC_EUSAGE.
Referenced by mgr_attach_eager(), and mgr_ensure_slot().
brix_aconn_close()
void brix_aconn_close (brix_aconn * ac)
Definition at line 497 of file aio.c.
References CMD_CLOSE_ACONN, brix_aconn::loop, and loop_run_control().
Referenced by mgr_free().
brix_aconn_set_resilience()
void brix_aconn_set_resilience (brix_aconn * ac, int max_stall_ms, int keepalive_ms, int max_retries)
Definition at line 508 of file aio.c.
References brix_aconn::def_retries, brix_aconn::keepalive_ms, and brix_aconn::max_stall_ms.
Referenced by mgr_attach_eager(), and mgr_ensure_slot().
brix_aio_call()
int brix_aio_call (brix_aconn * ac, const void * hdr24, const void * payload, uint32_t plen, uint16_t * kxr, uint8_t ** body, uint32_t * blen, int deadline_ms, brix_status * st)
Definition at line 643 of file aio.c.
References brix_aio_call_ex().
Referenced by brix_mfile_close(), and brix_mfile_sync().
brix_aio_call_ex()
int brix_aio_call_ex (brix_aconn * ac, const void * hdr24, const void * payload, uint32_t plen, const brix_aio_opts * opts, uint16_t * kxr, uint8_t ** body, uint32_t * blen, brix_status * st)
Definition at line 595 of file aio.c.
References call_wait::blen, call_wait::body, brix_aio_submit_ex(), call_cb(), call_wait::cv, call_wait::done, call_wait::kxr, call_wait::mx, call_wait::rc, and call_wait::st.
Referenced by brix_aio_call(), brix_mfile_pread(), brix_mfile_pwrite(), brix_mgr_call(), and mfile_do_open().
brix_aio_submit()
int brix_aio_submit (brix_aconn * ac, const void * hdr24, const void * payload, uint32_t plen, brix_aio_cb cb, void * ctx, int deadline_ms, brix_status * st)
Definition at line 564 of file aio.c.
References brix_aio_submit_ex().
brix_aio_submit_ex()
int brix_aio_submit_ex (brix_aconn * ac, const void * hdr24, const void * payload, uint32_t plen, const brix_aio_opts * opts, brix_aio_cb cb, void * ctx, brix_status * st)
Definition at line 524 of file aio.c.
References brix_status_set(), c, CMD_SUBMIT, brix_aio_opts::deadline_ms, brix_aconn::loop, loop_push_cmd(), brix_aio_opts::max_retries, brix_aio_opts::retry_safe, XRD_REQUEST_HDR_LEN, XRDC_EPROTO, and XRDC_EUSAGE.
Referenced by brix_aio_call_ex(), and brix_aio_submit().
brix_loop_create()
brix_loop * brix_loop_create (brix_status * st)
Definition at line 396 of file aio.c.
References brix_loop_create_fail(), brix_loop_want_uring(), brix_status_set(), brix_loop::cq_lock, brix_loop::epfd, brix_loop::evfd, io_engine_setup(), loop_thread(), brix_loop::thread, brix_loop::thread_ok, brix_loop::use_uring, XRDC_EPROTO, and XRDC_ESOCK.
Referenced by mgr_alloc_and_init().
brix_loop_destroy()
void brix_loop_destroy (brix_loop * l)
Definition at line 421 of file aio.c.
References c, CMD_STOP, brix_loop::cq_lock, brix_loop::evfd, io_engine_teardown(), loop_push_cmd(), brix_loop::stop, brix_loop::thread, brix_loop::thread_ok, and cmd::type.
Referenced by mgr_free().
brix_mfile_close()
int brix_mfile_close (brix_mfile * mf, brix_status * st)
Definition at line 757 of file aio_mgr.c.
References brix_mfile::ac, brix_aio_call(), brix_mfile::fhandle, xrdw_close_req_t::fhandle, brix_mfile::have_handle, kXR_close, brix_mfile::lock, ClientCloseRequest::requestid, XRD_FHANDLE_LEN, and xrdw_close_req_pack().
Referenced by xfs_release().
brix_mfile_open()
brix_mfile * brix_mfile_open (brix_aconn * ac, const char * path, int writable, int force, int posc, const char * opaque, int max_stall_ms, int max_retries, brix_status * st)
Definition at line 522 of file aio_mgr.c.
References brix_mfile::ac, brix_status_set(), brix_mfile::gen, brix_mfile::have_handle, brix_mfile::have_opaque, brix_mfile::lock, brix_mfile::max_retries, brix_mfile::max_stall_ms, mfile_do_open(), brix_mfile::opaque, brix_mfile::path, brix_mfile::posc, brix_mfile::writable, and XRDC_EPROTO.
Referenced by afh_open().
brix_mfile_pread()
ssize_t brix_mfile_pread (brix_mfile * mf, int64_t off, void * buf, size_t len, brix_status * st)
Definition at line 604 of file aio_mgr.c.
References brix_mfile::ac, brix_aio_call_ex(), brix_backoff_sleep_fast(), brix_inflate_frame(), xrdw_read_req_t::fhandle, kXR_read, brix_mfile::max_stall_ms, mfile_reopen(), mfile_should_reopen(), mfile_snapshot(), now_ns(), xrdw_read_req_t::offset, ClientReadRequest::requestid, XRD_FHANDLE_LEN, and xrdw_read_req_pack().
Referenced by afh_pread().
brix_mfile_pwrite()
int brix_mfile_pwrite (brix_mfile * mf, int64_t off, const void * buf, size_t len, brix_status * st)
Definition at line 668 of file aio_mgr.c.
References brix_mfile::ac, brix_aio_call_ex(), brix_backoff_sleep_fast(), brix_deflate_frame(), xrdw_write_req_t::fhandle, kXR_write, brix_mfile::max_stall_ms, mfile_reopen(), mfile_should_reopen(), mfile_snapshot(), now_ns(), xrdw_write_req_t::offset, ClientWriteRequest::requestid, XRD_FHANDLE_LEN, and xrdw_write_req_pack().
Referenced by afh_io_pwrite().
brix_mfile_sync()
int brix_mfile_sync (brix_mfile * mf, brix_status * st)
Definition at line 731 of file aio_mgr.c.
References brix_mfile::ac, brix_aio_call(), xrdw_sync_req_t::fhandle, kXR_sync, brix_mfile::max_stall_ms, mfile_reopen(), mfile_snapshot(), ClientSyncRequest::requestid, XRD_FHANDLE_LEN, and xrdw_sync_req_pack().
Referenced by xfs_fsync().
brix_mgr_call()
int brix_mgr_call (brix_mgr * m, const void * hdr24, const void * payload, uint32_t plen, int retry_safe, uint16_t * kxr, uint8_t ** body, uint32_t * blen, brix_status * st)
Definition at line 347 of file aio_mgr.c.
References brix_aio_call_ex(), brix_mgr_pick(), and brix_mgr::max_retries.
brix_mgr_create()
brix_mgr * brix_mgr_create (const brix_url * u, const brix_opts * o, int nconns, int eager, int max_stall_ms, int keepalive_ms, int max_retries, brix_status * st)
Definition at line 245 of file aio_mgr.c.
References mgr_alloc_and_init(), mgr_attach_eager(), mgr_connect_eager(), and mgr_free().
Referenced by aio_root_mount().
brix_mgr_destroy()
void brix_mgr_destroy (brix_mgr * m)
Definition at line 279 of file aio_mgr.c.
References mgr_free().
Referenced by aio_root_mount().
brix_mgr_pick()
brix_aconn * brix_mgr_pick (brix_mgr * m)
Definition at line 320 of file aio_mgr.c.
References brix_mgr::acs, mgr_ensure_slot(), brix_mgr::n, and brix_mgr::rr.
Referenced by afh_open(), and brix_mgr_call().