nginx-xrootd: client/lib/protocols/s3/s3.c File Reference
s3.c File Reference
#include "brix.h"
#include "core/compat/crypto.h"
#include "core/compat/hex.h"
#include "core/compat/uri.h"
#include "core/compat/sigv4.h"
#include <stdio.h>
#include <string.h>
#include <time.h>
Functions
void brix_s3_sha256_hex (const void *data, size_t len, char *out)
int brix_s3_sign_v4_q (const char *method, const char *host, const char *uri, const char *canon_qs, const char *ak, const char *sk, const char *region, const char *payload_hex, char *hdrs, size_t hdrsz)
int brix_s3_sign_v4 (const char *method, const char *host, const char *uri, const char *ak, const char *sk, const char *region, const char *payload_hex, char *hdrs, size_t hdrsz)
Function Documentation
brix_s3_sha256_hex()
void brix_s3_sha256_hex (const void * data, size_t len, char * out)
Definition at line 28 of file s3.c.
References brix_hex_encode(), and brix_sha256().
Referenced by battery_s3(), and brix_s3_sign_v4_q().
brix_s3_sign_v4()
int brix_s3_sign_v4 (const char * method, const char * host, const char * uri, const char * ak, const char * sk, const char * region, const char * payload_hex, char * hdrs, size_t hdrsz)
Definition at line 114 of file s3.c.
References brix_s3_sign_v4_q(), and region.
Referenced by battery_s3(), s3_sign(), and web_auth_headers().
brix_s3_sign_v4_q()
int brix_s3_sign_v4_q (const char * method, const char * host, const char * uri, const char * canon_qs, const char * ak, const char * sk, const char * region, const char * payload_hex, char * hdrs, size_t hdrsz)
Definition at line 36 of file s3.c.
References brix_hex_encode(), brix_hmac_sha256(), brix_http_urlencode(), brix_s3_sha256_hex(), brix_sigv4_signing_key(), and region.
Referenced by brix_s3_list(), and brix_s3_sign_v4().