nginx-xrootd: src/protocols/root/read/clone.h File Reference
clone.h File Reference
#include "core/ngx_brix_module.h"
Functions
ngx_int_t brix_handle_clone (brix_ctx_t *ctx, ngx_connection_t *c)
Function Documentation
brix_handle_clone()
ngx_int_t brix_handle_clone (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 40 of file clone.c.
References brix_copy_range(), brix_csi_write_update(), BRIX_OP_CLONE, BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_validate_read_handle(), brix_validate_write_handle(), brix_ctx_totals_t::bytes, brix_file_t::bytes_written, c, CLONE_ITEM_LEN, CLONE_MAX_ITEMS, brix_file_t::csi, brix_ctx_recv_t::cur_dlen, xrdw_clone_req_t::dst_fhandle, clone_item::dst_offset, brix_file_t::fd, brix_ctx_t::files, brix_ctx_recv_t::hdr_buf, kXR_ArgInvalid, kXR_ArgMissing, kXR_ArgTooLong, kXR_IOError, ngx_memcpy, brix_file_t::path, brix_ctx_recv_t::payload, pread(), brix_ctx_t::recv, clone_item::src_fhandle, clone_item::src_len, clone_item::src_offset, brix_ctx_t::totals, and xrdw_clone_req_unpack().
Referenced by brix_dispatch_read_opcode().