nginx-xrootd: src/protocols/root/read/close.h File Reference
close.h File Reference
#include "core/ngx_brix_module.h"
Functions
ngx_int_t brix_handle_close (brix_ctx_t *ctx, ngx_connection_t *c)
Function Documentation
brix_handle_close()
ngx_int_t brix_handle_close (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 362 of file close.c.
References brix_close_finish_sess_xfer(), brix_close_log_access(), brix_close_pgw_gate(), brix_close_posc_commit(), brix_close_release_slots(), brix_close_release_throttle(), brix_close_staged_commit(), brix_cns_emit_close(), brix_free_fhandle(), BRIX_OP_CLOSE, BRIX_OP_OK, brix_send_ok(), BRIX_SESS_XFER_COMPLETE, brix_validate_file_handle(), c, xrdw_close_req_t::fhandle, brix_ctx_recv_t::hdr_buf, ngx_stream_brix_module, brix_ctx_t::recv, brix_ctx_t::session, and xrdw_close_req_unpack().
Referenced by brix_dispatch_read_opcode().