nginx-xrootd: src/protocols/root/read/close.c File Reference
close.c File Reference
#include "close.h"
#include "core/ngx_brix_module.h"
#include "net/ratelimit/throttle_compat.h"
#include "fs/cache/cache_internal.h"
#include "core/compat/staged_file.h"
#include "fs/xfer/xfer.h"
#include "protocols/root/write/wrts_journal.h"
#include "protocols/root/write/pgw_fob.h"
#include "net/cms/cns.h"
#include "net/cms/cms_internal.h"
#include "net/cms/frame_io.h"
#include "observability/sesslog/sesslog_ngx.h"
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Functions
static void brix_cns_emit_close (brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *conf, int idx)
static void brix_close_finish_sess_xfer (brix_ctx_t *ctx, int idx, brix_sess_xfer_status_t status)
static ngx_int_t brix_close_pgw_gate (brix_ctx_t *ctx, ngx_connection_t *c, int idx, ngx_int_t *rc)
static ngx_int_t brix_close_staged_commit (brix_ctx_t *ctx, ngx_connection_t *c, int idx, ngx_int_t *rc)
static void brix_close_log_access (brix_ctx_t *ctx, ngx_connection_t *c, int idx)
static ngx_int_t brix_close_posc_commit (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, int idx, ngx_int_t *rc)
static void brix_close_release_slots (brix_ctx_t *ctx, int idx)
static void brix_close_release_throttle (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_handle_close (brix_ctx_t *ctx, ngx_connection_t *c)
Function Documentation
brix_close_finish_sess_xfer()
static void brix_close_finish_sess_xfer (brix_ctx_t * ctx, int idx, brix_sess_xfer_status_t status) static
Definition at line 112 of file close.c.
References brix_sess_xfer_t::active, brix_sess_xfer_add(), brix_sess_xfer_end(), brix_sess_xfer_t::bytes, brix_file_t::bytes_read, brix_file_t::bytes_written, brix_ctx_t::files, brix_ctx_t::sess, and brix_file_t::sess_xfer.
Referenced by brix_close_posc_commit(), brix_close_staged_commit(), and brix_handle_close().
brix_close_log_access()
static void brix_close_log_access (brix_ctx_t * ctx, ngx_connection_t * c, int idx) static
Definition at line 194 of file close.c.
References brix_log_access(), brix_file_t::bytes_read, brix_file_t::bytes_written, c, brix_ctx_t::files, brix_file_t::open_time, brix_file_t::path, and brix_file_t::posc_final_path.
Referenced by brix_handle_close().
brix_close_pgw_gate()
static ngx_int_t brix_close_pgw_gate (brix_ctx_t * ctx, ngx_connection_t * c, int idx, ngx_int_t * rc) static
Definition at line 137 of file close.c.
References BRIX_OP_CLOSE, BRIX_OP_ERR, brix_pgw_fob_count(), brix_send_error(), c, brix_ctx_t::files, kXR_ChkSumErr, and brix_file_t::pgw_fob_enabled.
Referenced by brix_handle_close().
brix_close_posc_commit()
static ngx_int_t brix_close_posc_commit (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, int idx, ngx_int_t * rc) static
Definition at line 231 of file close.c.
References brix_close_finish_sess_xfer(), brix_commit_staged(), brix_free_fhandle(), BRIX_OP_CLOSE, BRIX_OP_ERR, brix_send_error(), BRIX_SESS_XFER_ABORTED, brix_stage_mark_pending(), brix_stage_unmark_pending(), BRIX_XFER_COMMIT_ERR, brix_xfer_finish(), BRIX_XFER_OK, BRIX_XFER_STAGE, c, brix_ctx_login_t::dn, brix_file_t::fd, brix_ctx_t::files, fstat(), brix_file_t::is_resume, kXR_IOError, brix_ctx_t::login, brix_file_t::path, brix_file_t::posc_final_path, and stat().
Referenced by brix_handle_close().
brix_close_release_slots()
static void brix_close_release_slots (brix_ctx_t * ctx, int idx) static
Definition at line 312 of file close.c.
References brix_transfer_slot_count_op(), brix_transfer_slot_free(), brix_wrts_flush(), brix_file_t::dashboard_slot, brix_ctx_t::files, ngx_brix_dashboard_shm_zone, and brix_file_t::posc_final_path.
Referenced by brix_handle_close().
brix_close_release_throttle()
static void brix_close_release_throttle (brix_ctx_t * ctx, ngx_connection_t * c) static
Definition at line 346 of file close.c.
References brix_throttle_open_dec(), c, brix_ctx_login_t::dn, brix_ctx_t::login, ngx_stream_brix_module, brix_ctx_throttle_t::open_held, and brix_ctx_t::throttle.
Referenced by brix_handle_close().
brix_close_staged_commit()
static ngx_int_t brix_close_staged_commit (brix_ctx_t * ctx, ngx_connection_t * c, int idx, ngx_int_t * rc) static
Definition at line 168 of file close.c.
References brix_close_finish_sess_xfer(), brix_free_fhandle(), BRIX_OP_CLOSE, BRIX_OP_ERR, brix_send_error(), BRIX_SESS_XFER_ABORTED, brix_staged_commit_handle(), c, brix_ctx_t::files, kXR_IOError, brix_file_t::staged_committed, and brix_file_t::writer.
Referenced by brix_handle_close().
brix_cns_emit_close()
static void brix_cns_emit_close (brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * conf, int idx) static
Definition at line 59 of file close.c.
References brix_cms_send_frame(), BRIX_CNS_ADD, BRIX_CNS_EMIT, brix_cns_event_encode(), BRIX_CNS_HDR_LEN, BRIX_CNS_PATH_MAX, CMS_MOD_RAW, CMS_RR_CNS, brix_file_t::fd, brix_ctx_t::files, fstat(), brix_file_t::path, brix_file_t::posc_final_path, stat(), and brix_file_t::writable.
Referenced by brix_handle_close().
brix_handle_close()
ngx_int_t brix_handle_close (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 362 of file close.c.
References brix_close_finish_sess_xfer(), brix_close_log_access(), brix_close_pgw_gate(), brix_close_posc_commit(), brix_close_release_slots(), brix_close_release_throttle(), brix_close_staged_commit(), brix_cns_emit_close(), brix_free_fhandle(), BRIX_OP_CLOSE, BRIX_OP_OK, brix_send_ok(), BRIX_SESS_XFER_COMPLETE, brix_validate_file_handle(), c, xrdw_close_req_t::fhandle, brix_ctx_recv_t::hdr_buf, ngx_stream_brix_module, brix_ctx_t::recv, brix_ctx_t::session, and xrdw_close_req_unpack().
Referenced by brix_dispatch_read_opcode().