nginx-xrootd: src/observability/metrics/cluster.c File Reference
cluster.c File Reference
#include "metrics_internal.h"
#include "metrics_macros.h"
#include "net/manager/registry.h"
Macros
#define CLUSTER_LABEL(idx)
Functions
void brix_export_cluster_metrics (metrics_writer_t *mw)
Macro Definition Documentation
CLUSTER_LABEL
#define CLUSTER_LABEL (idx)
Value:
    snprintf(srv_label, sizeof(srv_label), "%.255s:%u", \
             entries[(idx)].host, (unsigned int) entries[(idx)].port)
Function Documentation
brix_export_cluster_metrics()
void brix_export_cluster_metrics (metrics_writer_t * mw)
Definition at line 30 of file cluster.c.
References brix_srv_snapshot_entry_t::blacklisted_until, brix_metrics_shared(), BRIX_SRV_REGISTRY_SLOTS, brix_srv_shm_zone, brix_srv_snapshot(), CLUSTER_LABEL, ngx_brix_metrics_t::hc_blacklist_total, ngx_brix_metrics_t::hc_fail_total, ngx_brix_metrics_t::hc_pass_total, ngx_brix_metrics_t::hc_probes_total, brix_srv_snapshot_entry_t::last_seen, and mw_printf().
Referenced by brix_export_prometheus_metrics().