nginx-xrootd: src/net/cms/cms_internal.h File Reference
cms_internal.h File Reference
#include "core/ngx_brix_module.h"
#include "meter.h"
Data Structures
struct ngx_brix_cms_ctx_t
Macros
#define NGX_BRIX_CMS_INITIAL_DELAY 1000
#define NGX_BRIX_CMS_BACKOFF_INITIAL 6000
#define NGX_BRIX_CMS_BACKOFF_MAX 60000
#define NGX_BRIX_CMS_CONNECT_TIMEOUT 5000
#define NGX_BRIX_CMS_SRV_DROP_BLACKLIST_MS 30000
#define NGX_BRIX_CMS_INITDELAY_LOOPBACK 0 /* loopback: connect immediately */
#define NGX_BRIX_CMS_INITDELAY_REMOTE 10 /* remote: tiny settle margin */
#define NGX_BRIX_CMS_FASTRETRY_LOOPBACK 10 /* loopback retry interval (ms) */
#define NGX_BRIX_CMS_FASTRETRY_REMOTE 75 /* remote retry interval (ms) */
#define NGX_BRIX_CMS_FASTRETRY_FLOOR 10 /* never retry faster than this */
#define NGX_BRIX_CMS_FASTWIN_LOOPBACK 2000 /* loopback fast-retry window (ms)*/
#define NGX_BRIX_CMS_FASTWIN_REMOTE 3000 /* remote fast-retry window (ms) */
#define NGX_BRIX_CMS_HDR_LEN 8
#define NGX_BRIX_CMS_MAX_FRAME 4096
#define NGX_BRIX_CMS_MAX_FRAMES_PER_WAKEUP 64
#define NGX_BRIX_CMS_MIN_FREE_MB 100
#define CMS_RR_LOGIN 0 /* kYR_login: announce server identity to manager */
#define CMS_RR_CHMOD 1 /* kYR_chmod: forwarded mode change */
#define CMS_RR_LOCATE 2 /* kYR_locate: ask manager which server has a path */
#define CMS_RR_MKDIR 3 /* kYR_mkdir: forwarded directory create */
#define CMS_RR_MKPATH 4 /* kYR_mkpath: forwarded recursive directory create */
#define CMS_RR_MV 5 /* kYR_mv: forwarded rename */
#define CMS_RR_PREPADD 6 /* kYR_prepadd: forwarded stage-in request */
#define CMS_RR_PREPDEL 7 /* kYR_prepdel: forwarded stage cancel */
#define CMS_RR_RM 8 /* kYR_rm: forwarded file unlink */
#define CMS_RR_RMDIR 9 /* kYR_rmdir: forwarded directory remove */
#define CMS_RR_STATS 11 /* kYR_stats: cluster stats query */
#define CMS_RR_DISC 13 /* kYR_disc: graceful disconnect notification */
#define CMS_RR_STATFS 21 /* kYR_statfs: space query for a path */
#define CMS_RR_TRUNC 23 /* kYR_trunc: forwarded truncate */
#define CMS_RR_UPDATE 25 /* kYR_update: request peer resend its state */
#define CMS_RR_USAGE 26 /* kYR_usage: load/usage query */
#define CMS_RSP_DATA 0 /* kYR_data: reply carries data */
#define CMS_RSP_ERROR 1 /* kYR_error: reply carries [4B ecode][text] */
#define CMS_RSP_WAIT 3 /* kYR_wait: reply carries [4B delay-seconds] */
#define CMS_ERR_EINVAL 4 /* kYR_EINVAL */
#define CMS_RR_AVAIL 12 /* kYR_avail: report available files for a path */
#define CMS_RR_GONE 14 /* kYR_gone: data server path-level deregister */
#define CMS_RR_HAVE 15 /* kYR_have: server tells manager it holds a path */
#define CMS_RR_LOAD 16 /* kYR_load: periodic load/space heartbeat */
#define CMS_RR_SELECT 10 /* kYR_select: manager redirect reply (single host) */
#define CMS_RR_PING 17 /* kYR_ping: manager liveness probe */
#define CMS_RR_PONG 18 /* kYR_pong: reply to kYR_ping */
#define CMS_RR_SPACE 19 /* kYR_space: request available disk space stats */
#define CMS_RR_STATE 20 /* kYR_state: manager asks "do you have <path>?" */
#define CMS_RR_STATUS 22 /* kYR_status: suspend/resume traffic control */
#define CMS_RR_TRY 24 /* kYR_try: manager redirect reply (ordered list) */
#define CMS_RR_XAUTH 27 /* kYR_xauth: security handshake (sss credential) */
#define CMS_ST_STAGE 0x01 /* staging available */
#define CMS_ST_NOSTAGE 0x02 /* staging unavailable (disk-only node) */
#define CMS_ST_RESUME 0x04 /* resume accepting requests */
#define CMS_ST_SUSPEND 0x08 /* stop accepting new requests */
#define CMS_ST_RESET 0x10 /* reset state */
#define CMS_MOD_RAW 0x20 /* payload is raw (not Pup-encoded) */
#define CMS_HAVE_ONLINE 0x01 /* kYR_have modifier: file is online/resident */
#define CMS_PT_SHORT 0x80 /* 2-byte big-endian value follows */
#define CMS_PT_INT 0xa0 /* 4-byte big-endian value follows */
#define CMS_TRY_MISS 0x00000000 /* kYR_tryMISS: file not found */
#define CMS_TRY_IOER 0x00010000 /* kYR_tryIOER: I/O error on the server */
#define CMS_TRY_FSER 0x00020000 /* kYR_tryFSER: filesystem error */
#define CMS_TRY_SVER 0x00030000 /* kYR_trySVER: server error */
#define CMS_TRY_MASK 0x00030000 /* mask over the reason bits */
#define CMS_TRY_SHFT 16 /* shift to extract the reason value */
#define CMS_TRY_RSEL 0x00040000 /* kYR_tryRSEL: retry the selection */
#define CMS_TRY_RSEG 0x00080000 /* kYR_tryRSEG: retry within the segment */
#define CMS_LOGIN_VERSION 3
#define CMS_LOGIN_MODE 0x00000008 /* kYR_server: this node exports data */
#define CMS_LOGIN_MODE_MANAGER
Functions
uint16_t ngx_brix_cms_get16 (const u_char *p)
uint32_t ngx_brix_cms_get32 (const u_char *p)
void ngx_brix_cms_put16 (u_char *p, uint16_t value)
void ngx_brix_cms_put32 (u_char *p, uint32_t value)
u_char * ngx_brix_cms_put_short (u_char *p, uint16_t value)
u_char * ngx_brix_cms_put_int (u_char *p, uint32_t value)
u_char * ngx_brix_cms_put_string (u_char *p, const u_char *data, size_t len)
ngx_str_t ngx_brix_cms_export_paths (ngx_stream_brix_srv_conf_t *conf)
ngx_int_t ngx_brix_cms_stat_space (ngx_stream_brix_srv_conf_t *conf, uint32_t *total_gb, uint32_t *free_mb, uint32_t *util_pct)
ngx_int_t ngx_brix_cms_send_login (ngx_brix_cms_ctx_t *ctx)
ngx_int_t ngx_brix_cms_send_load (ngx_brix_cms_ctx_t *ctx)
ngx_int_t ngx_brix_cms_send_avail (ngx_brix_cms_ctx_t *ctx, uint32_t streamid)
ngx_int_t ngx_brix_cms_send_pong (ngx_brix_cms_ctx_t *ctx, uint32_t streamid)
ngx_int_t ngx_brix_cms_send_status (ngx_brix_cms_ctx_t *ctx)
ngx_int_t ngx_brix_cms_send_have (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, const char *path, size_t path_len)
ngx_int_t ngx_brix_cms_send_locate (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, const char *path)
uint32_t ngx_brix_cms_next_streamid (ngx_brix_cms_ctx_t *ctx)
ngx_int_t ngx_brix_cms_send_error (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, uint32_t ecode, const char *text)
void ngx_brix_cms_read_handler (ngx_event_t *ev)
void ngx_brix_cms_set_end_hint (ngx_brix_cms_ctx_t *ctx, brix_sess_end_t why)
void ngx_brix_cms_disconnect (ngx_brix_cms_ctx_t *ctx)
void ngx_brix_cms_schedule (ngx_brix_cms_ctx_t *ctx, ngx_msec_t delay)
void ngx_brix_cms_schedule_retry (ngx_brix_cms_ctx_t *ctx)
void ngx_brix_cms_arm_read_deadline (ngx_brix_cms_ctx_t *ctx)
Macro Definition Documentation
CMS_ERR_EINVAL
#define CMS_ERR_EINVAL 4 /* kYR_EINVAL */
Definition at line 94 of file cms_internal.h.
CMS_HAVE_ONLINE
#define CMS_HAVE_ONLINE 0x01 /* kYR_have modifier: file is online/resident */
Definition at line 125 of file cms_internal.h.
CMS_LOGIN_MODE
#define CMS_LOGIN_MODE 0x00000008 /* kYR_server: this node exports data */
Definition at line 161 of file cms_internal.h.
CMS_LOGIN_MODE_MANAGER
#define CMS_LOGIN_MODE_MANAGER
Value:
                                             0x00000002  /* kYR_manager: also manages servers
                                             * (real LoginMode bit; 0x10 is proxy) */
Definition at line 162 of file cms_internal.h.
CMS_LOGIN_VERSION
#define CMS_LOGIN_VERSION 3
Definition at line 160 of file cms_internal.h.
CMS_MOD_RAW
#define CMS_MOD_RAW 0x20 /* payload is raw (not Pup-encoded) */
Definition at line 124 of file cms_internal.h.
CMS_PT_INT
#define CMS_PT_INT 0xa0 /* 4-byte big-endian value follows */
Definition at line 133 of file cms_internal.h.
CMS_PT_SHORT
#define CMS_PT_SHORT 0x80 /* 2-byte big-endian value follows */
Definition at line 132 of file cms_internal.h.
CMS_RR_AVAIL
#define CMS_RR_AVAIL 12 /* kYR_avail: report available files for a path */
Definition at line 95 of file cms_internal.h.
CMS_RR_CHMOD
#define CMS_RR_CHMOD 1 /* kYR_chmod: forwarded mode change */
Definition at line 63 of file cms_internal.h.
CMS_RR_DISC
#define CMS_RR_DISC 13 /* kYR_disc: graceful disconnect notification */
Definition at line 73 of file cms_internal.h.
CMS_RR_GONE
#define CMS_RR_GONE 14 /* kYR_gone: data server path-level deregister */
Definition at line 96 of file cms_internal.h.
CMS_RR_HAVE
#define CMS_RR_HAVE 15 /* kYR_have: server tells manager it holds a path */
Definition at line 97 of file cms_internal.h.
CMS_RR_LOAD
#define CMS_RR_LOAD 16 /* kYR_load: periodic load/space heartbeat */
Definition at line 98 of file cms_internal.h.
CMS_RR_LOCATE
#define CMS_RR_LOCATE 2 /* kYR_locate: ask manager which server has a path */
Definition at line 64 of file cms_internal.h.
CMS_RR_LOGIN
#define CMS_RR_LOGIN 0 /* kYR_login: announce server identity to manager */
Definition at line 62 of file cms_internal.h.
CMS_RR_MKDIR
#define CMS_RR_MKDIR 3 /* kYR_mkdir: forwarded directory create */
Definition at line 65 of file cms_internal.h.
CMS_RR_MKPATH
#define CMS_RR_MKPATH 4 /* kYR_mkpath: forwarded recursive directory create */
Definition at line 66 of file cms_internal.h.
CMS_RR_MV
#define CMS_RR_MV 5 /* kYR_mv: forwarded rename */
Definition at line 67 of file cms_internal.h.
CMS_RR_PING
#define CMS_RR_PING 17 /* kYR_ping: manager liveness probe */
Definition at line 100 of file cms_internal.h.
CMS_RR_PONG
#define CMS_RR_PONG 18 /* kYR_pong: reply to kYR_ping */
Definition at line 101 of file cms_internal.h.
CMS_RR_PREPADD
#define CMS_RR_PREPADD 6 /* kYR_prepadd: forwarded stage-in request */
Definition at line 68 of file cms_internal.h.
CMS_RR_PREPDEL
#define CMS_RR_PREPDEL 7 /* kYR_prepdel: forwarded stage cancel */
Definition at line 69 of file cms_internal.h.
CMS_RR_RM
#define CMS_RR_RM 8 /* kYR_rm: forwarded file unlink */
Definition at line 70 of file cms_internal.h.
CMS_RR_RMDIR
#define CMS_RR_RMDIR 9 /* kYR_rmdir: forwarded directory remove */
Definition at line 71 of file cms_internal.h.
CMS_RR_SELECT
#define CMS_RR_SELECT 10 /* kYR_select: manager redirect reply (single host) */
Definition at line 99 of file cms_internal.h.
CMS_RR_SPACE
#define CMS_RR_SPACE 19 /* kYR_space: request available disk space stats */
Definition at line 102 of file cms_internal.h.
CMS_RR_STATE
#define CMS_RR_STATE 20 /* kYR_state: manager asks "do you have <path>?" */
Definition at line 103 of file cms_internal.h.
CMS_RR_STATFS
#define CMS_RR_STATFS 21 /* kYR_statfs: space query for a path */
Definition at line 74 of file cms_internal.h.
CMS_RR_STATS
#define CMS_RR_STATS 11 /* kYR_stats: cluster stats query */
Definition at line 72 of file cms_internal.h.
CMS_RR_STATUS
#define CMS_RR_STATUS 22 /* kYR_status: suspend/resume traffic control */
Definition at line 104 of file cms_internal.h.
CMS_RR_TRUNC
#define CMS_RR_TRUNC 23 /* kYR_trunc: forwarded truncate */
Definition at line 75 of file cms_internal.h.
CMS_RR_TRY
#define CMS_RR_TRY 24 /* kYR_try: manager redirect reply (ordered list) */
Definition at line 105 of file cms_internal.h.
CMS_RR_UPDATE
#define CMS_RR_UPDATE 25 /* kYR_update: request peer resend its state */
Definition at line 76 of file cms_internal.h.
CMS_RR_USAGE
#define CMS_RR_USAGE 26 /* kYR_usage: load/usage query */
Definition at line 77 of file cms_internal.h.
CMS_RR_XAUTH
#define CMS_RR_XAUTH 27 /* kYR_xauth: security handshake (sss credential) */
Definition at line 106 of file cms_internal.h.
CMS_RSP_DATA
#define CMS_RSP_DATA 0 /* kYR_data: reply carries data */
Definition at line 84 of file cms_internal.h.
CMS_RSP_ERROR
#define CMS_RSP_ERROR 1 /* kYR_error: reply carries [4B ecode][text] */
Definition at line 85 of file cms_internal.h.
CMS_RSP_WAIT
#define CMS_RSP_WAIT 3 /* kYR_wait: reply carries [4B delay-seconds] */
Definition at line 86 of file cms_internal.h.
CMS_ST_NOSTAGE
#define CMS_ST_NOSTAGE 0x02 /* staging unavailable (disk-only node) */
Definition at line 114 of file cms_internal.h.
CMS_ST_RESET
#define CMS_ST_RESET 0x10 /* reset state */
Definition at line 117 of file cms_internal.h.
CMS_ST_RESUME
#define CMS_ST_RESUME 0x04 /* resume accepting requests */
Definition at line 115 of file cms_internal.h.
CMS_ST_STAGE
#define CMS_ST_STAGE 0x01 /* staging available */
Definition at line 113 of file cms_internal.h.
CMS_ST_SUSPEND
#define CMS_ST_SUSPEND 0x08 /* stop accepting new requests */
Definition at line 116 of file cms_internal.h.
CMS_TRY_FSER
#define CMS_TRY_FSER 0x00020000 /* kYR_tryFSER: filesystem error */
Definition at line 147 of file cms_internal.h.
CMS_TRY_IOER
#define CMS_TRY_IOER 0x00010000 /* kYR_tryIOER: I/O error on the server */
Definition at line 146 of file cms_internal.h.
CMS_TRY_MASK
#define CMS_TRY_MASK 0x00030000 /* mask over the reason bits */
Definition at line 149 of file cms_internal.h.
CMS_TRY_MISS
#define CMS_TRY_MISS 0x00000000 /* kYR_tryMISS: file not found */
Definition at line 145 of file cms_internal.h.
CMS_TRY_RSEG
#define CMS_TRY_RSEG 0x00080000 /* kYR_tryRSEG: retry within the segment */
Definition at line 152 of file cms_internal.h.
CMS_TRY_RSEL
#define CMS_TRY_RSEL 0x00040000 /* kYR_tryRSEL: retry the selection */
Definition at line 151 of file cms_internal.h.
CMS_TRY_SHFT
#define CMS_TRY_SHFT 16 /* shift to extract the reason value */
Definition at line 150 of file cms_internal.h.
CMS_TRY_SVER
#define CMS_TRY_SVER 0x00030000 /* kYR_trySVER: server error */
Definition at line 148 of file cms_internal.h.
NGX_BRIX_CMS_BACKOFF_INITIAL
#define NGX_BRIX_CMS_BACKOFF_INITIAL 6000
Definition at line 20 of file cms_internal.h.
NGX_BRIX_CMS_BACKOFF_MAX
#define NGX_BRIX_CMS_BACKOFF_MAX 60000
Definition at line 21 of file cms_internal.h.
NGX_BRIX_CMS_CONNECT_TIMEOUT
#define NGX_BRIX_CMS_CONNECT_TIMEOUT 5000
Definition at line 22 of file cms_internal.h.
NGX_BRIX_CMS_FASTRETRY_FLOOR
#define NGX_BRIX_CMS_FASTRETRY_FLOOR 10 /* never retry faster than this */
Definition at line 44 of file cms_internal.h.
NGX_BRIX_CMS_FASTRETRY_LOOPBACK
#define NGX_BRIX_CMS_FASTRETRY_LOOPBACK 10 /* loopback retry interval (ms) */
Definition at line 42 of file cms_internal.h.
NGX_BRIX_CMS_FASTRETRY_REMOTE
#define NGX_BRIX_CMS_FASTRETRY_REMOTE 75 /* remote retry interval (ms) */
Definition at line 43 of file cms_internal.h.
NGX_BRIX_CMS_FASTWIN_LOOPBACK
#define NGX_BRIX_CMS_FASTWIN_LOOPBACK 2000 /* loopback fast-retry window (ms)*/
Definition at line 45 of file cms_internal.h.
NGX_BRIX_CMS_FASTWIN_REMOTE
#define NGX_BRIX_CMS_FASTWIN_REMOTE 3000 /* remote fast-retry window (ms) */
Definition at line 46 of file cms_internal.h.
NGX_BRIX_CMS_HDR_LEN
#define NGX_BRIX_CMS_HDR_LEN 8
Definition at line 47 of file cms_internal.h.
NGX_BRIX_CMS_INITDELAY_LOOPBACK
#define NGX_BRIX_CMS_INITDELAY_LOOPBACK 0 /* loopback: connect immediately */
Definition at line 40 of file cms_internal.h.
NGX_BRIX_CMS_INITDELAY_REMOTE
#define NGX_BRIX_CMS_INITDELAY_REMOTE 10 /* remote: tiny settle margin */
Definition at line 41 of file cms_internal.h.
NGX_BRIX_CMS_INITIAL_DELAY
#define NGX_BRIX_CMS_INITIAL_DELAY 1000
Definition at line 19 of file cms_internal.h.
NGX_BRIX_CMS_MAX_FRAME
#define NGX_BRIX_CMS_MAX_FRAME 4096
Definition at line 48 of file cms_internal.h.
NGX_BRIX_CMS_MAX_FRAMES_PER_WAKEUP
#define NGX_BRIX_CMS_MAX_FRAMES_PER_WAKEUP 64
Definition at line 55 of file cms_internal.h.
NGX_BRIX_CMS_MIN_FREE_MB
#define NGX_BRIX_CMS_MIN_FREE_MB 100
Definition at line 56 of file cms_internal.h.
NGX_BRIX_CMS_SRV_DROP_BLACKLIST_MS
#define NGX_BRIX_CMS_SRV_DROP_BLACKLIST_MS 30000
Definition at line 38 of file cms_internal.h.
Function Documentation
ngx_brix_cms_arm_read_deadline()
void ngx_brix_cms_arm_read_deadline (ngx_brix_cms_ctx_t * ctx)
Definition at line 134 of file connect.c.
References c.
Referenced by ngx_brix_cms_read_handler(), and ngx_brix_cms_write_handler().
ngx_brix_cms_disconnect()
void ngx_brix_cms_disconnect (ngx_brix_cms_ctx_t * ctx)
Definition at line 255 of file connect.c.
References brix_sess_end(), c, ngx_brix_cms_end_reason(), and NGX_BRIX_CMS_HDR_LEN.
Referenced by cms_conn_fail(), cms_frame_disc(), ngx_brix_cms_timer(), and ngx_brix_cms_write_handler().
ngx_brix_cms_export_paths()
ngx_str_t ngx_brix_cms_export_paths (ngx_stream_brix_srv_conf_t * conf)
Definition at line 7 of file space.c.
Referenced by ngx_brix_cms_send_login().
ngx_brix_cms_get16()
uint16_t ngx_brix_cms_get16 (const u_char * p)
Definition at line 27 of file wire.c.
Referenced by cms_frame_redirect(), cms_recv_accumulate(), cms_srv_dispatch_frame(), cms_srv_read_accumulate(), cms_srv_read_string(), and tlv_read_next().
ngx_brix_cms_get32()
uint32_t ngx_brix_cms_get32 (const u_char * p)
Definition at line 34 of file wire.c.
Referenced by cms_srv_dispatch_frame(), ngx_brix_cms_process_frame(), and tlv_read_next().
ngx_brix_cms_next_streamid()
uint32_t ngx_brix_cms_next_streamid (ngx_brix_cms_ctx_t * ctx)
Definition at line 355 of file send.c.
Referenced by brix_open_cms_locate(), brix_qcksum_manager_bounce(), locate_try_cms_parent(), and stat_manager_route().
ngx_brix_cms_put16()
void ngx_brix_cms_put16 (u_char * p, uint16_t value)
Definition at line 44 of file wire.c.
Referenced by brix_cms_send_frame(), brix_cms_srv_send_load(), ngx_brix_cms_put_short(), ngx_brix_cms_put_string(), and ngx_brix_cms_send_load().
ngx_brix_cms_put32()
void ngx_brix_cms_put32 (u_char * p, uint32_t value)
Definition at line 52 of file wire.c.
Referenced by brix_cms_send_frame(), ngx_brix_cms_put_int(), and ngx_brix_cms_send_error().
ngx_brix_cms_put_int()
u_char * ngx_brix_cms_put_int (u_char * p, uint32_t value)
Definition at line 77 of file wire.c.
References CMS_PT_INT, and ngx_brix_cms_put32().
Referenced by brix_cms_srv_send_load(), ngx_brix_cms_send_avail(), ngx_brix_cms_send_load(), and ngx_brix_cms_send_login().
ngx_brix_cms_put_short()
u_char * ngx_brix_cms_put_short (u_char * p, uint16_t value)
Definition at line 64 of file wire.c.
References CMS_PT_SHORT, and ngx_brix_cms_put16().
Referenced by ngx_brix_cms_send_login().
ngx_brix_cms_put_string()
u_char * ngx_brix_cms_put_string (u_char * p, const u_char * data, size_t len)
Definition at line 92 of file wire.c.
References ngx_brix_cms_put16(), and ngx_memcpy.
Referenced by ngx_brix_cms_send_login().
ngx_brix_cms_read_handler()
void ngx_brix_cms_read_handler (ngx_event_t * ev)
Definition at line 107 of file recv.c.
References BRIX_RESIL_METRIC_INC, BRIX_SESS_END_ERROR, BRIX_SESS_END_TIMEOUT, c, cms_conn_fail(), cms_recv_accumulate(), ngx_brix_cms_arm_read_deadline(), NGX_BRIX_CMS_HDR_LEN, NGX_BRIX_CMS_MAX_FRAMES_PER_WAKEUP, and ngx_brix_cms_process_frame().
Referenced by ngx_brix_cms_connect().
ngx_brix_cms_schedule()
void ngx_brix_cms_schedule (ngx_brix_cms_ctx_t * ctx, ngx_msec_t delay)
Definition at line 151 of file connect.c.
Referenced by ngx_brix_cms_schedule_retry(), ngx_brix_cms_start(), ngx_brix_cms_timer(), and ngx_brix_cms_write_handler().
ngx_brix_cms_schedule_retry()
void ngx_brix_cms_schedule_retry (ngx_brix_cms_ctx_t * ctx)
Definition at line 180 of file connect.c.
References BRIX_DIAG_WARN, NGX_BRIX_CMS_BACKOFF_MAX, and ngx_brix_cms_schedule().
Referenced by cms_conn_fail(), cms_frame_disc(), ngx_brix_cms_connect(), ngx_brix_cms_timer(), and ngx_brix_cms_write_handler().
ngx_brix_cms_send_avail()
ngx_int_t ngx_brix_cms_send_avail (ngx_brix_cms_ctx_t * ctx, uint32_t streamid)
Definition at line 303 of file send.c.
References brix_srv_aggregate_space(), CMS_RR_AVAIL, ngx_brix_cms_put_int(), ngx_brix_cms_send_frame(), and ngx_brix_cms_stat_space().
Referenced by cms_frame_space().
ngx_brix_cms_send_error()
ngx_int_t ngx_brix_cms_send_error (ngx_brix_cms_ctx_t * ctx, uint32_t streamid, uint32_t ecode, const char * text)
Definition at line 32 of file send.c.
References CMS_RSP_ERROR, ngx_brix_cms_put32(), ngx_brix_cms_send_frame(), and ngx_memcpy.
Referenced by cms_forward_via_driver(), cms_forward_via_posix(), cms_node_exec_forward(), cms_node_exec_prepare(), and cms_prep_add().
ngx_brix_cms_send_have()
ngx_int_t ngx_brix_cms_send_have (ngx_brix_cms_ctx_t * ctx, uint32_t streamid, const char * path, size_t path_len)
Definition at line 403 of file send.c.
References BRIX_SRV_MAX_PATHS, CMS_HAVE_ONLINE, CMS_MOD_RAW, CMS_RR_HAVE, ngx_brix_cms_send_frame(), and ngx_memcpy.
Referenced by cms_frame_state().
ngx_brix_cms_send_load()
ngx_int_t ngx_brix_cms_send_load (ngx_brix_cms_ctx_t * ctx)
Definition at line 239 of file send.c.
References brix_cms_meter_sample(), brix_srv_aggregate_space(), CMS_RR_LOAD, ngx_brix_cms_put16(), ngx_brix_cms_put_int(), ngx_brix_cms_send_frame(), ngx_brix_cms_stat_space(), and ngx_memcpy.
Referenced by ngx_brix_cms_timer(), and ngx_brix_cms_write_handler().
ngx_brix_cms_send_locate()
ngx_int_t ngx_brix_cms_send_locate (ngx_brix_cms_ctx_t * ctx, uint32_t streamid, const char * path)
Definition at line 375 of file send.c.
References BRIX_SRV_MAX_PATHS, CMS_RR_LOCATE, ngx_brix_cms_send_frame(), and ngx_memcpy.
Referenced by brix_open_cms_locate(), brix_qcksum_manager_bounce(), locate_try_cms_parent(), and stat_manager_route().
ngx_brix_cms_send_login()
ngx_int_t ngx_brix_cms_send_login (ngx_brix_cms_ctx_t * ctx)
Definition at line 64 of file send.c.
References brix_srv_aggregate_space(), CMS_LOGIN_MODE, CMS_LOGIN_MODE_MANAGER, CMS_LOGIN_VERSION, CMS_RR_LOGIN, ngx_brix_cms_export_paths(), NGX_BRIX_CMS_MIN_FREE_MB, ngx_brix_cms_put_int(), ngx_brix_cms_put_short(), ngx_brix_cms_put_string(), ngx_brix_cms_send_frame(), ngx_brix_cms_stat_space(), and ngx_memcpy.
Referenced by ngx_brix_cms_write_handler().
ngx_brix_cms_send_pong()
ngx_int_t ngx_brix_cms_send_pong (ngx_brix_cms_ctx_t * ctx, uint32_t streamid)
Definition at line 340 of file send.c.
References CMS_RR_PONG, and ngx_brix_cms_send_frame().
Referenced by cms_frame_ping().
ngx_brix_cms_send_status()
ngx_int_t ngx_brix_cms_send_status (ngx_brix_cms_ctx_t * ctx)
Definition at line 221 of file send.c.
References CMS_RR_STATUS, CMS_ST_NOSTAGE, CMS_ST_RESUME, and ngx_brix_cms_send_frame().
Referenced by cms_frame_update(), and ngx_brix_cms_write_handler().
ngx_brix_cms_set_end_hint()
void ngx_brix_cms_set_end_hint (ngx_brix_cms_ctx_t * ctx, brix_sess_end_t why)
Definition at line 36 of file connect.c.
Referenced by cms_conn_fail(), cms_frame_disc(), ngx_brix_cms_timer(), and ngx_brix_cms_write_handler().
ngx_brix_cms_stat_space()
ngx_int_t ngx_brix_cms_stat_space (ngx_stream_brix_srv_conf_t * conf, uint32_t * total_gb, uint32_t * free_mb, uint32_t * util_pct)
Definition at line 20 of file space.c.
Referenced by ngx_brix_cms_send_avail(), ngx_brix_cms_send_load(), and ngx_brix_cms_send_login().