nginx-xrootd: src/net/cms/cns.c File Reference
cns.c File Reference
#include "cns.h"
#include <stdlib.h>
#include <string.h>
Data Structures
struct cns_entry_t
Macros
#define CNS_CAP 8192
Functions
static void put_u64 (uint8_t *p, uint64_t v)
static uint64_t get_u64 (const uint8_t *p)
size_t brix_cns_event_encode (uint8_t op, const char *path, uint64_t size, uint64_t mtime, uint8_t *buf, size_t bufsz)
ngx_int_t brix_cns_event_decode (const uint8_t *buf, size_t len, uint8_t *op, uint64_t *size, uint64_t *mtime, char *path, size_t pathsz)
static cns_entry_t * cns_find (const char *path)
static cns_entry_t * cns_free_slot (void)
ngx_int_t brix_cns_apply (uint8_t op, const char *path, uint64_t size, uint64_t mtime, uint32_t server_id)
ngx_int_t brix_cns_stat (const char *path, struct stat *out)
ngx_uint_t brix_cns_count (void)
void brix_cns_set_collect (ngx_flag_t on)
ngx_flag_t brix_cns_collecting (void)
Variables
static cns_entry_t * s_inv
static ngx_uint_t s_count
static ngx_flag_t s_collect
Macro Definition Documentation
CNS_CAP
#define CNS_CAP 8192
Definition at line 88 of file cns.c.
Function Documentation
brix_cns_apply()
ngx_int_t brix_cns_apply (uint8_t op, const char * path, uint64_t size, uint64_t mtime, uint32_t server_id)
Definition at line 121 of file cns.c.
References BRIX_CNS_ADD, BRIX_CNS_DEL, BRIX_CNS_MKDIR, BRIX_CNS_PATH_MAX, BRIX_CNS_RMDIR, CNS_CAP, cns_find(), cns_free_slot(), cns_entry_t::is_dir, cns_entry_t::mtime, op, cns_entry_t::path, s_count, s_inv, cns_entry_t::server_id, cns_entry_t::size, and cns_entry_t::used.
Referenced by cms_srv_frame_cns().
brix_cns_collecting()
ngx_flag_t brix_cns_collecting (void)
Definition at line 210 of file cns.c.
References s_collect.
Referenced by cms_srv_frame_cns().
brix_cns_count()
ngx_uint_t brix_cns_count (void)
Definition at line 194 of file cns.c.
References s_count.
brix_cns_event_decode()
ngx_int_t brix_cns_event_decode (const uint8_t * buf, size_t len, uint8_t * op, uint64_t * size, uint64_t * mtime, char * path, size_t pathsz)
Definition at line 55 of file cns.c.
References BRIX_CNS_HDR_LEN, BRIX_CNS_PATH_MAX, get_u64(), and op.
Referenced by cms_srv_frame_cns().
brix_cns_event_encode()
size_t brix_cns_event_encode (uint8_t op, const char * path, uint64_t size, uint64_t mtime, uint8_t * buf, size_t bufsz)
Definition at line 34 of file cns.c.
References BRIX_CNS_HDR_LEN, BRIX_CNS_PATH_MAX, op, and put_u64().
Referenced by brix_cns_emit_close().
brix_cns_set_collect()
void brix_cns_set_collect (ngx_flag_t on)
Definition at line 202 of file cns.c.
References s_collect.
Referenced by brix_merge_srv_tpc().
brix_cns_stat()
ngx_int_t brix_cns_stat (const char * path, struct stat * out)
Definition at line 174 of file cns.c.
References cns_find(), cns_entry_t::is_dir, cns_entry_t::mtime, and cns_entry_t::size.
Referenced by stat_manager_route().
cns_find()
static cns_entry_t * cns_find (const char * path) static
Definition at line 94 of file cns.c.
References CNS_CAP, and s_inv.
Referenced by brix_cns_apply(), and brix_cns_stat().
cns_free_slot()
static cns_entry_t * cns_free_slot (void) static
Definition at line 109 of file cns.c.
References CNS_CAP, and s_inv.
Referenced by brix_cns_apply().
get_u64()
static uint64_t get_u64 (const uint8_t * p) static
Definition at line 25 of file cns.c.
Referenced by brix_cns_event_decode().
put_u64()
static void put_u64 (uint8_t * p, uint64_t v) static
Definition at line 16 of file cns.c.
Referenced by brix_cns_event_encode().
Variable Documentation
s_collect
ngx_flag_t s_collect static
Definition at line 199 of file cns.c.
Referenced by brix_cns_collecting(), and brix_cns_set_collect().
s_count
ngx_uint_t s_count static
Definition at line 91 of file cns.c.
Referenced by brix_cns_apply(), and brix_cns_count().
s_inv
cns_entry_t* s_inv static
Definition at line 90 of file cns.c.
Referenced by brix_cns_apply(), cns_find(), and cns_free_slot().