nginx-xrootd: src/net/cms/cns.h File Reference
cns.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <stdint.h>
#include <sys/stat.h>
Macros
#define CMS_RR_CNS 40
#define BRIX_CNS_ADD 1 /* file created / closed-after-write (size known) */
#define BRIX_CNS_DEL 2 /* file unlinked */
#define BRIX_CNS_MKDIR 3
#define BRIX_CNS_RMDIR 4
#define BRIX_CNS_OFF 0
#define BRIX_CNS_EMIT 1 /* data server: report mutations to the manager */
#define BRIX_CNS_COLLECT 2 /* manager: maintain the inventory + answer stat */
#define BRIX_CNS_PATH_MAX 512
#define BRIX_CNS_HDR_LEN 22
Functions
size_t brix_cns_event_encode (uint8_t op, const char *path, uint64_t size, uint64_t mtime, uint8_t *buf, size_t bufsz)
ngx_int_t brix_cns_event_decode (const uint8_t *buf, size_t len, uint8_t *op, uint64_t *size, uint64_t *mtime, char *path, size_t pathsz)
ngx_int_t brix_cns_apply (uint8_t op, const char *path, uint64_t size, uint64_t mtime, uint32_t server_id)
ngx_int_t brix_cns_stat (const char *path, struct stat *out)
ngx_uint_t brix_cns_count (void)
void brix_cns_set_collect (ngx_flag_t on)
ngx_flag_t brix_cns_collecting (void)
Macro Definition Documentation
BRIX_CNS_ADD
#define BRIX_CNS_ADD 1 /* file created / closed-after-write (size known) */
Definition at line 35 of file cns.h.
BRIX_CNS_COLLECT
#define BRIX_CNS_COLLECT 2 /* manager: maintain the inventory + answer stat */
Definition at line 43 of file cns.h.
BRIX_CNS_DEL
#define BRIX_CNS_DEL 2 /* file unlinked */
Definition at line 36 of file cns.h.
BRIX_CNS_EMIT
#define BRIX_CNS_EMIT 1 /* data server: report mutations to the manager */
Definition at line 42 of file cns.h.
BRIX_CNS_HDR_LEN
#define BRIX_CNS_HDR_LEN 22
Definition at line 51 of file cns.h.
BRIX_CNS_MKDIR
#define BRIX_CNS_MKDIR 3
Definition at line 37 of file cns.h.
BRIX_CNS_OFF
#define BRIX_CNS_OFF 0
Definition at line 41 of file cns.h.
BRIX_CNS_PATH_MAX
#define BRIX_CNS_PATH_MAX 512
Definition at line 45 of file cns.h.
BRIX_CNS_RMDIR
#define BRIX_CNS_RMDIR 4
Definition at line 38 of file cns.h.
CMS_RR_CNS
#define CMS_RR_CNS 40
Definition at line 32 of file cns.h.
Function Documentation
brix_cns_apply()
ngx_int_t brix_cns_apply (uint8_t op, const char * path, uint64_t size, uint64_t mtime, uint32_t server_id)
Definition at line 121 of file cns.c.
References BRIX_CNS_ADD, BRIX_CNS_DEL, BRIX_CNS_MKDIR, BRIX_CNS_PATH_MAX, BRIX_CNS_RMDIR, CNS_CAP, cns_find(), cns_free_slot(), cns_entry_t::is_dir, cns_entry_t::mtime, op, cns_entry_t::path, s_count, s_inv, cns_entry_t::server_id, cns_entry_t::size, and cns_entry_t::used.
Referenced by cms_srv_frame_cns().
brix_cns_collecting()
ngx_flag_t brix_cns_collecting (void)
Definition at line 210 of file cns.c.
References s_collect.
Referenced by cms_srv_frame_cns().
brix_cns_count()
ngx_uint_t brix_cns_count (void)
Definition at line 194 of file cns.c.
References s_count.
brix_cns_event_decode()
ngx_int_t brix_cns_event_decode (const uint8_t * buf, size_t len, uint8_t * op, uint64_t * size, uint64_t * mtime, char * path, size_t pathsz)
Definition at line 55 of file cns.c.
References BRIX_CNS_HDR_LEN, BRIX_CNS_PATH_MAX, get_u64(), and op.
Referenced by cms_srv_frame_cns().
brix_cns_event_encode()
size_t brix_cns_event_encode (uint8_t op, const char * path, uint64_t size, uint64_t mtime, uint8_t * buf, size_t bufsz)
Definition at line 34 of file cns.c.
References BRIX_CNS_HDR_LEN, BRIX_CNS_PATH_MAX, op, and put_u64().
Referenced by brix_cns_emit_close().
brix_cns_set_collect()
void brix_cns_set_collect (ngx_flag_t on)
Definition at line 202 of file cns.c.
References s_collect.
Referenced by brix_merge_srv_tpc().
brix_cns_stat()
ngx_int_t brix_cns_stat (const char * path, struct stat * out)
Definition at line 174 of file cns.c.
References cns_find(), cns_entry_t::is_dir, cns_entry_t::mtime, and cns_entry_t::size.
Referenced by stat_manager_route().