nginx-xrootd: src/core/compat/codec_core.h File Reference
codec_core.h File Reference
#include <stddef.h>
#include <stdint.h>
Data Structures
struct brix_codec_guard_t
struct brix_codec_backend_t
struct brix_codec_desc_t
Macros
#define BRIX_CODEC_RATIO_FLOOR (64u * 1024u)
#define BRIX_INLINE_CMP_MAGIC 0x5A /* 'Z'; nonzero, fits kXR_int32 cpsize */
Enumerations
enum brix_codec_id_t {
BRIX_CODEC_IDENTITY = 0 , BRIX_CODEC_GZIP = 1 , BRIX_CODEC_DEFLATE = 2 , BRIX_CODEC_ZSTD = 3 ,
BRIX_CODEC_BROTLI = 4 , BRIX_CODEC_XZ = 5 , BRIX_CODEC_BZIP2 = 6 , BRIX_CODEC_LZ4 = 7 ,
BRIX_CODEC_MAX
}
enum brix_codec_dir_t { BRIX_CODEC_DIR_COMPRESS = 0 , BRIX_CODEC_DIR_DECOMPRESS = 1 }
enum brix_codec_rc_t {
BRIX_CODEC_OK = 0 , BRIX_CODEC_END = 1 , BRIX_CODEC_ERR_DATA = -1 , BRIX_CODEC_ERR_MEM = -2 ,
BRIX_CODEC_ERR_BOMB = -3 , BRIX_CODEC_ERR_PARAM = -4 , BRIX_CODEC_ERR_INTERNAL = -5
}
Functions
const brix_codec_desc_t * brix_codec_by_id (brix_codec_id_t id)
const brix_codec_desc_t * brix_codec_by_name (const char *name, size_t len)
const brix_codec_desc_t * brix_codec_by_http_token (const char *tok, size_t len)
int brix_codec_available (brix_codec_id_t id)
brix_codec_stream_t * brix_codec_open (brix_codec_id_t id, brix_codec_dir_t dir, int level, const brix_codec_guard_t *guard)
brix_codec_rc_t brix_codec_step (brix_codec_stream_t *s, const uint8_t *in, size_t in_len, size_t *in_pos, uint8_t *out, size_t out_size, size_t *out_pos, int finish)
void brix_codec_close (brix_codec_stream_t *s)
Macro Definition Documentation
BRIX_CODEC_RATIO_FLOOR
#define BRIX_CODEC_RATIO_FLOOR (64u * 1024u)
Definition at line 79 of file codec_core.h.
BRIX_INLINE_CMP_MAGIC
#define BRIX_INLINE_CMP_MAGIC 0x5A /* 'Z'; nonzero, fits kXR_int32 cpsize */
Definition at line 99 of file codec_core.h.
Enumeration Type Documentation
brix_codec_dir_t
enum brix_codec_dir_t
Enumerator
BRIX_CODEC_DIR_COMPRESS
BRIX_CODEC_DIR_DECOMPRESS
Definition at line 45 of file codec_core.h.
brix_codec_id_t
enum brix_codec_id_t
Enumerator
BRIX_CODEC_IDENTITY
BRIX_CODEC_GZIP
BRIX_CODEC_DEFLATE
BRIX_CODEC_ZSTD
BRIX_CODEC_BROTLI
BRIX_CODEC_XZ
BRIX_CODEC_BZIP2
BRIX_CODEC_LZ4
BRIX_CODEC_MAX
Definition at line 33 of file codec_core.h.
brix_codec_rc_t
enum brix_codec_rc_t
Enumerator
BRIX_CODEC_OK
BRIX_CODEC_END
BRIX_CODEC_ERR_DATA
BRIX_CODEC_ERR_MEM
BRIX_CODEC_ERR_BOMB
BRIX_CODEC_ERR_PARAM
BRIX_CODEC_ERR_INTERNAL
Definition at line 51 of file codec_core.h.
Function Documentation
brix_codec_available()
int brix_codec_available (brix_codec_id_t id)
Definition at line 151 of file codec_core.c.
References brix_codec_desc_t::available, brix_codec_desc_t::backend, and brix_codec_by_id().
Referenced by brix_open_apply_inline_codec(), and mfile_learn_codec().
brix_codec_by_http_token()
const brix_codec_desc_t * brix_codec_by_http_token (const char * tok, size_t len)
Definition at line 145 of file codec_core.c.
References codec_match().
Referenced by open_negotiate_compress_codec(), s3put_select_codec(), and webdav_put_select_codec().
brix_codec_by_id()
const brix_codec_desc_t * brix_codec_by_id (brix_codec_id_t id)
Definition at line 92 of file codec_core.c.
References BRIX_CODEC_MAX, and codec_table.
Referenced by brix_codec_available(), brix_codec_open(), brix_http_compress_negotiate(), brix_http_send_file_compressed(), and brix_qconfig_codec_list().
brix_codec_by_name()
const brix_codec_desc_t * brix_codec_by_name (const char * name, size_t len)
Definition at line 139 of file codec_core.c.
References codec_match(), and name.
Referenced by open_negotiate_compress_codec().
brix_codec_close()
void brix_codec_close (brix_codec_stream_t * s)
Definition at line 229 of file codec_core.c.
References s.
Referenced by brix_compress_frame(), brix_deflate_frame(), brix_http_body_decode_to_fd(), brix_http_send_file_compressed(), brix_inflate_frame(), brix_write_compressed(), and codec_ctx_setup().
brix_codec_open()
brix_codec_stream_t * brix_codec_open (brix_codec_id_t id, brix_codec_dir_t dir, int level, const brix_codec_guard_t * guard)
Definition at line 159 of file codec_core.c.
References brix_codec_desc_t::available, brix_codec_desc_t::backend, brix_codec_by_id(), brix_codec_backend_t::init, brix_codec_desc_t::level_default, brix_codec_desc_t::level_max, brix_codec_desc_t::level_min, and s.
Referenced by brix_compress_frame(), brix_deflate_frame(), brix_http_send_file_compressed(), brix_inflate_frame(), brix_write_compressed(), and codec_ctx_setup().
brix_codec_step()
brix_codec_rc_t brix_codec_step (brix_codec_stream_t * s, const uint8_t * in, size_t in_len, size_t * in_pos, uint8_t * out, size_t out_size, size_t * out_pos, int finish)
Definition at line 191 of file codec_core.c.
References BRIX_CODEC_DIR_DECOMPRESS, BRIX_CODEC_ERR_BOMB, BRIX_CODEC_ERR_PARAM, BRIX_CODEC_RATIO_FLOOR, and s.
Referenced by brix_compress_frame(), brix_deflate_frame(), brix_inflate_frame(), brix_wcmp_decompress_stream(), codec_feed(), and compress_drain_chunk().