nginx-xrootd: src/core/compat/codec_core.c File Reference
codec_core.c File Reference
#include "codec_core.h"
#include <stdlib.h>
#include <string.h>
Data Structures
struct brix_codec_stream_t
Functions
static int identity_init (void **state, brix_codec_id_t id, brix_codec_dir_t dir, int level)
static brix_codec_rc_t identity_step (void *state, const uint8_t *in, size_t in_len, size_t *in_pos, uint8_t *out, size_t out_size, size_t *out_pos, int finish)
static void identity_end (void *state)
const brix_codec_desc_t * brix_codec_by_id (brix_codec_id_t id)
static int codec_ci_eq (const char *a, const char *b, size_t n)
static const brix_codec_desc_t * codec_match (const char *s, size_t len, int by_token)
const brix_codec_desc_t * brix_codec_by_name (const char *name, size_t len)
const brix_codec_desc_t * brix_codec_by_http_token (const char *tok, size_t len)
int brix_codec_available (brix_codec_id_t id)
brix_codec_stream_t * brix_codec_open (brix_codec_id_t id, brix_codec_dir_t dir, int level, const brix_codec_guard_t *guard)
brix_codec_rc_t brix_codec_step (brix_codec_stream_t *s, const uint8_t *in, size_t in_len, size_t *in_pos, uint8_t *out, size_t out_size, size_t *out_pos, int finish)
void brix_codec_close (brix_codec_stream_t *s)
Variables
static const brix_codec_backend_t identity_backend
const brix_codec_desc_t brix_codec_identity_desc
const brix_codec_desc_t brix_codec_gzip_desc
const brix_codec_desc_t brix_codec_deflate_desc
const brix_codec_desc_t brix_codec_zstd_desc
const brix_codec_desc_t brix_codec_brotli_desc
const brix_codec_desc_t brix_codec_xz_desc
const brix_codec_desc_t brix_codec_bzip2_desc
const brix_codec_desc_t brix_codec_lz4_desc
static const brix_codec_desc_t *const codec_table [BRIX_CODEC_MAX]
Function Documentation
brix_codec_available()
int brix_codec_available (brix_codec_id_t id)
Definition at line 151 of file codec_core.c.
References brix_codec_desc_t::available, brix_codec_desc_t::backend, and brix_codec_by_id().
Referenced by brix_open_apply_inline_codec(), and mfile_learn_codec().
brix_codec_by_http_token()
const brix_codec_desc_t * brix_codec_by_http_token (const char * tok, size_t len)
Definition at line 145 of file codec_core.c.
References codec_match().
Referenced by open_negotiate_compress_codec(), s3put_select_codec(), and webdav_put_select_codec().
brix_codec_by_id()
const brix_codec_desc_t * brix_codec_by_id (brix_codec_id_t id)
Definition at line 92 of file codec_core.c.
References BRIX_CODEC_MAX, and codec_table.
Referenced by brix_codec_available(), brix_codec_open(), brix_http_compress_negotiate(), brix_http_send_file_compressed(), and brix_qconfig_codec_list().
brix_codec_by_name()
const brix_codec_desc_t * brix_codec_by_name (const char * name, size_t len)
Definition at line 139 of file codec_core.c.
References codec_match(), and name.
Referenced by open_negotiate_compress_codec().
brix_codec_close()
void brix_codec_close (brix_codec_stream_t * s)
Definition at line 229 of file codec_core.c.
References s.
Referenced by brix_compress_frame(), brix_deflate_frame(), brix_http_body_decode_to_fd(), brix_http_send_file_compressed(), brix_inflate_frame(), brix_write_compressed(), and codec_ctx_setup().
brix_codec_open()
brix_codec_stream_t * brix_codec_open (brix_codec_id_t id, brix_codec_dir_t dir, int level, const brix_codec_guard_t * guard)
Definition at line 159 of file codec_core.c.
References brix_codec_desc_t::available, brix_codec_desc_t::backend, brix_codec_by_id(), brix_codec_backend_t::init, brix_codec_desc_t::level_default, brix_codec_desc_t::level_max, brix_codec_desc_t::level_min, and s.
Referenced by brix_compress_frame(), brix_deflate_frame(), brix_http_send_file_compressed(), brix_inflate_frame(), brix_write_compressed(), and codec_ctx_setup().
brix_codec_step()
brix_codec_rc_t brix_codec_step (brix_codec_stream_t * s, const uint8_t * in, size_t in_len, size_t * in_pos, uint8_t * out, size_t out_size, size_t * out_pos, int finish)
Definition at line 191 of file codec_core.c.
References BRIX_CODEC_DIR_DECOMPRESS, BRIX_CODEC_ERR_BOMB, BRIX_CODEC_ERR_PARAM, BRIX_CODEC_RATIO_FLOOR, and s.
Referenced by brix_compress_frame(), brix_deflate_frame(), brix_inflate_frame(), brix_wcmp_decompress_stream(), codec_feed(), and compress_drain_chunk().
codec_ci_eq()
static int codec_ci_eq (const char * a, const char * b, size_t n) static
Definition at line 101 of file codec_core.c.
Referenced by codec_match().
codec_match()
static const brix_codec_desc_t * codec_match (const char * s, size_t len, int by_token) static
Definition at line 118 of file codec_core.c.
References BRIX_CODEC_MAX, codec_ci_eq(), codec_table, brix_codec_desc_t::http_token, key, brix_codec_desc_t::name, and s.
Referenced by brix_codec_by_http_token(), and brix_codec_by_name().
identity_end()
static void identity_end (void * state) static
Definition at line 57 of file codec_core.c.
identity_init()
static int identity_init (void ** state, brix_codec_id_t id, brix_codec_dir_t dir, int level) static
Definition at line 29 of file codec_core.c.
identity_step()
static brix_codec_rc_t identity_step (void * state, const uint8_t * in, size_t in_len, size_t * in_pos, uint8_t * out, size_t out_size, size_t * out_pos, int finish) static
Definition at line 37 of file codec_core.c.
References BRIX_CODEC_END, and BRIX_CODEC_OK.
Variable Documentation
brix_codec_brotli_desc
const brix_codec_desc_t brix_codec_brotli_desc extern
Definition at line 110 of file codec_brotli.c.
brix_codec_bzip2_desc
const brix_codec_desc_t brix_codec_bzip2_desc extern
Definition at line 121 of file codec_bzip2.c.
brix_codec_deflate_desc
const brix_codec_desc_t brix_codec_deflate_desc extern
Definition at line 135 of file codec_zlib.c.
brix_codec_gzip_desc
const brix_codec_desc_t brix_codec_gzip_desc extern
Definition at line 132 of file codec_zlib.c.
brix_codec_identity_desc
const brix_codec_desc_t brix_codec_identity_desc
Initial value:
= {
    BRIX_CODEC_IDENTITY, "identity", "identity", 1, 0, 0, 0, &identity_backend
}
Definition at line 66 of file codec_core.c.
brix_codec_lz4_desc
const brix_codec_desc_t brix_codec_lz4_desc extern
Definition at line 351 of file codec_lz4.c.
brix_codec_xz_desc
const brix_codec_desc_t brix_codec_xz_desc extern
Definition at line 107 of file codec_lzma.c.
brix_codec_zstd_desc
const brix_codec_desc_t brix_codec_zstd_desc extern
Definition at line 107 of file codec_zstd.c.
codec_table
const brix_codec_desc_t* const codec_table[BRIX_CODEC_MAX] static
Initial value:
= {
    [BRIX_CODEC_IDENTITY] = &brix_codec_identity_desc,
    [BRIX_CODEC_GZIP]     = &brix_codec_gzip_desc,
    [BRIX_CODEC_DEFLATE]  = &brix_codec_deflate_desc,
    [BRIX_CODEC_ZSTD]     = &brix_codec_zstd_desc,
    [BRIX_CODEC_BROTLI]   = &brix_codec_brotli_desc,
    [BRIX_CODEC_XZ]       = &brix_codec_xz_desc,
    [BRIX_CODEC_BZIP2]    = &brix_codec_bzip2_desc,
    [BRIX_CODEC_LZ4]      = &brix_codec_lz4_desc,
}
Definition at line 79 of file codec_core.c.
Referenced by brix_codec_by_id(), and codec_match().
identity_backend
const brix_codec_backend_t identity_backend static
Initial value:
= {
    identity_init, identity_step, identity_end
}
Definition at line 62 of file codec_core.c.