nginx-xrootd: src/auth/voms/collect.c File Reference
collect.c File Reference
#include "voms_internal.h"
#include "auth/voms/vo_token.h"
#include <string.h>
Functions
static ngx_flag_t brix_vo_token_safe (const char *vo, size_t vo_len)
static ngx_flag_t brix_append_vo_token (char *primary_vo, size_t primary_vo_sz, char *vo_list, size_t vo_list_sz, const char *vo)
static ngx_flag_t brix_fqan_to_vo (const char *fqan, char *vo, size_t vo_sz)
ngx_int_t brix_collect_voms_vos (struct voms_data *vd, char *primary_vo, size_t primary_vo_sz, char *vo_list, size_t vo_list_sz)
Function Documentation
brix_append_vo_token()
static ngx_flag_t brix_append_vo_token (char * primary_vo, size_t primary_vo_sz, char * vo_list, size_t vo_list_sz, const char * vo) static
Definition at line 29 of file collect.c.
References brix_vo_list_contains(), brix_vo_token_safe(), and ngx_memcpy.
Referenced by brix_collect_voms_vos().
brix_collect_voms_vos()
ngx_int_t brix_collect_voms_vos (struct voms_data * vd, char * primary_vo, size_t primary_vo_sz, char * vo_list, size_t vo_list_sz)
Definition at line 119 of file collect.c.
References brix_append_vo_token(), brix_fqan_to_vo(), brix_voms_init_pt::data, and voms_entry::fqan.
Referenced by brix_voms_retrieve_and_collect().
brix_fqan_to_vo()
static ngx_flag_t brix_fqan_to_vo (const char * fqan, char * vo, size_t vo_sz) static
Definition at line 81 of file collect.c.
References brix_vo_token_safe(), and ngx_memcpy.
Referenced by brix_collect_voms_vos().
brix_vo_token_safe()
static ngx_flag_t brix_vo_token_safe (const char * vo, size_t vo_len) static
Definition at line 23 of file collect.c.
References brix_vo_token_is_safe().
Referenced by brix_append_vo_token(), and brix_fqan_to_vo().