nginx-xrootd: src/protocols/root/write/common.c File Reference
common.c File Reference
#include "core/ngx_brix_module.h"
Functions
ngx_int_t brix_try_post_write_aio (brix_ctx_t *ctx, ngx_connection_t *c, int idx, off_t offset, const u_char *data, size_t len, int64_t req_offset, ngx_uint_t is_pgwrite, u_char *payload_to_free, const xrdp_pg_bad_t *bad, size_t bad_count, const char *fallback_log, ngx_flag_t *posted)
Function Documentation
brix_try_post_write_aio()
ngx_int_t brix_try_post_write_aio (brix_ctx_t * ctx, ngx_connection_t * c, int idx, off_t offset, const u_char * data, size_t len, int64_t req_offset, ngx_uint_t is_pgwrite, u_char * payload_to_free, const xrdp_pg_bad_t * bad, size_t bad_count, const char * fallback_log, ngx_flag_t * posted)
Definition at line 17 of file common.c.
References brix_write_aio_t::bad_page_count, brix_write_aio_t::bad_pages, brix_aio_post_task(), brix_write_aio_done(), brix_write_aio_thread(), brix_write_aio_t::c, c, ngx_stream_brix_srv_conf_t::common, brix_write_aio_t::conf, brix_write_aio_t::csi, brix_file_t::csi, brix_write_aio_t::ctx, brix_ctx_recv_t::cur_streamid, brix_write_aio_t::data, brix_write_aio_t::fd, brix_file_t::fd, brix_ctx_t::files, brix_write_aio_t::handle_idx, brix_write_aio_t::io_errno, brix_write_aio_t::is_pgwrite, kXR_pgMaxEpr, brix_write_aio_t::len, ngx_stream_brix_module, brix_write_aio_t::nwritten, brix_write_aio_t::obj, brix_write_aio_t::offset, brix_write_aio_t::path, brix_file_t::path, brix_write_aio_t::payload_to_free, brix_ctx_t::recv, brix_write_aio_t::req_offset, brix_file_t::sd_obj, brix_write_aio_t::streamid, and ngx_http_brix_shared_conf_t::thread_pool.
Referenced by brix_handle_pgwrite(), and brix_handle_write().