nginx-xrootd: src/protocols/s3/conditional.c File Reference
conditional.c File Reference
#include "s3.h"
#include "core/http/etag.h"
#include "core/http/http_conditionals.h"
#include "core/http/http_headers.h"
#include "core/http/http_query.h"
#include "fs/vfs/vfs.h"
#include <fcntl.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Macros
#define S3_OVERRIDE_QUERY_FLAGS
Functions
ngx_int_t s3_send_not_modified (ngx_http_request_t *r, const char *etag, time_t mtime)
ngx_int_t s3_send_precondition_failed (ngx_http_request_t *r)
ngx_int_t s3_handle_conditional (ngx_http_request_t *r, time_t mtime, off_t size)
ngx_int_t s3_put_precondition (ngx_http_request_t *r, const char *root_canon, const char *fs_path)
int s3_put_is_exclusive_create (ngx_http_request_t *r)
static void s3_override_header (ngx_http_request_t *r, const char *param, const char *header)
void s3_apply_response_overrides (ngx_http_request_t *r)
void s3_get_pre_header (ngx_http_request_t *r, ngx_fd_t fd, off_t file_size, void *userdata)
Macro Definition Documentation
S3_OVERRIDE_QUERY_FLAGS
#define S3_OVERRIDE_QUERY_FLAGS
Value:
    (BRIX_HTTP_QUERY_DECODE_VALUE | BRIX_HTTP_QUERY_PLUS_TO_SPACE \
     | BRIX_HTTP_QUERY_REJECT_NUL | BRIX_HTTP_QUERY_ALLOW_EMPTY)
Definition at line 48 of file conditional.c.
Function Documentation
s3_apply_response_overrides()
void s3_apply_response_overrides (ngx_http_request_t * r)
Definition at line 233 of file conditional.c.
References brix_http_query_get(), brix_http_str_has_ctl(), ngx_memcpy, ngx_pnalloc(), s3_override_header(), and S3_OVERRIDE_QUERY_FLAGS.
Referenced by s3_get_pre_header().
s3_get_pre_header()
void s3_get_pre_header (ngx_http_request_t * r, ngx_fd_t fd, off_t file_size, void * userdata)
Definition at line 271 of file conditional.c.
References s3_apply_response_overrides().
Referenced by s3_handle_get().
s3_handle_conditional()
ngx_int_t s3_handle_conditional (ngx_http_request_t * r, time_t mtime, off_t size)
Definition at line 86 of file conditional.c.
References BRIX_HTTP_COND_READ, BRIX_HTTP_COND_TIME, BRIX_HTTP_COND_WEAK_EQUIV, brix_http_etag_str(), brix_http_eval_preconditions(), s3_send_not_modified(), and s3_send_precondition_failed().
Referenced by s3_handle_get(), and s3_handle_head().
s3_override_header()
static void s3_override_header (ngx_http_request_t * r, const char * param, const char * header) static
Definition at line 213 of file conditional.c.
References brix_http_query_get(), brix_http_set_header(), brix_http_str_has_ctl(), and S3_OVERRIDE_QUERY_FLAGS.
Referenced by s3_apply_response_overrides().
s3_put_is_exclusive_create()
int s3_put_is_exclusive_create (ngx_http_request_t * r)
Definition at line 197 of file conditional.c.
Referenced by s3_dispatch_after_auth().
s3_put_precondition()
ngx_int_t s3_put_precondition (ngx_http_request_t * r, const char * root_canon, const char * fs_path)
Definition at line 144 of file conditional.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_HTTP_COND_WEAK_EQUIV, brix_http_eval_preconditions(), BRIX_PROTO_S3, brix_vfs_ctx_init(), ngx_http_s3_loc_conf_t::cache_root_canon, ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::identity, brix_vfs_stat_t::is_regular, brix_vfs_stat_t::mtime, ngx_http_brix_s3_module, brix_vfs_ctx_t::pool, s3_send_precondition_failed(), and brix_vfs_stat_t::size.
Referenced by s3_dispatch_after_auth().
s3_send_not_modified()
ngx_int_t s3_send_not_modified (ngx_http_request_t * r, const char * etag, time_t mtime)
Definition at line 57 of file conditional.c.
References s3_set_header().
Referenced by s3_handle_conditional().
s3_send_precondition_failed()
ngx_int_t s3_send_precondition_failed (ngx_http_request_t * r)
Definition at line 71 of file conditional.c.
References s3_send_xml_error().
Referenced by s3_handle_conditional(), and s3_put_precondition().