nginx-xrootd: src/observability/dashboard/config_download_classify.c File Reference
config_download_classify.c File Reference
#include "dashboard_http.h"
#include "core/http/http_headers.h"
#include "core/compat/cstr.h"
#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>
#include "config_download_internal.h"
Functions
static u_char dashboard_lc (u_char c)
ngx_uint_t dashboard_name_eq (const u_char *name, size_t len, const char *lit)
static ngx_uint_t dashboard_name_in (const u_char *name, size_t len, const char *const *set)
static ngx_uint_t dashboard_name_contains (const u_char *name, size_t len, const char *sub)
static ngx_uint_t dashboard_name_is_secret (const u_char *name, size_t len)
ngx_uint_t dashboard_keep_value (const u_char *name, size_t len)
Variables
static const char *const dashboard_secret_directives []
static const char *const dashboard_secret_name_substrings []
static const char *const dashboard_secret_exceptions []
static const char *const dashboard_safe_stock_directives []
Function Documentation
dashboard_keep_value()
ngx_uint_t dashboard_keep_value (const u_char * name, size_t len)
Definition at line 217 of file config_download_classify.c.
References dashboard_name_eq(), dashboard_name_in(), dashboard_name_is_secret(), dashboard_safe_stock_directives, and name.
Referenced by dashboard_redact_line().
dashboard_lc()
static u_char dashboard_lc (u_char c) static
Definition at line 127 of file config_download_classify.c.
References c.
Referenced by dashboard_name_contains(), and dashboard_name_eq().
dashboard_name_contains()
static ngx_uint_t dashboard_name_contains (const u_char * name, size_t len, const char * sub) static
Definition at line 162 of file config_download_classify.c.
References dashboard_lc(), and name.
Referenced by dashboard_name_is_secret().
dashboard_name_eq()
ngx_uint_t dashboard_name_eq (const u_char * name, size_t len, const char * lit)
Definition at line 134 of file config_download_classify.c.
References dashboard_lc(), and name.
Referenced by dashboard_keep_value(), dashboard_name_in(), dashboard_name_is_secret(), and dashboard_scrub_query_param().
dashboard_name_in()
static ngx_uint_t dashboard_name_in (const u_char * name, size_t len, const char *const * set) static
Definition at line 148 of file config_download_classify.c.
References dashboard_name_eq(), and name.
Referenced by dashboard_keep_value(), and dashboard_name_is_secret().
dashboard_name_is_secret()
static ngx_uint_t dashboard_name_is_secret (const u_char * name, size_t len) static
Definition at line 186 of file config_download_classify.c.
References dashboard_name_contains(), dashboard_name_eq(), dashboard_name_in(), dashboard_secret_directives, dashboard_secret_exceptions, dashboard_secret_name_substrings, and name.
Referenced by dashboard_keep_value().
Variable Documentation
dashboard_safe_stock_directives
const char* const dashboard_safe_stock_directives[] static
Initial value:
= {
    "user", "worker_processes", "worker_connections", "worker_rlimit_nofile",
    "pid", "daemon", "master_process", "events", "use", "multi_accept",
    "http", "stream", "server", "location", "upstream", "types", "include_off",
    "default_type", "server_name", "listen", "root", "alias", "index",
    "sendfile", "tcp_nopush", "tcp_nodelay", "keepalive_timeout",
    "keepalive_requests", "client_max_body_size", "client_body_buffer_size",
    "client_body_temp_path", "proxy_temp_path", "fastcgi_temp_path",
    "uwsgi_temp_path", "scgi_temp_path", "output_buffers", "thread_pool",
    "access_log", "error_log", "log_format", "log_not_found", "autoindex",
    "gzip", "gzip_types", "gzip_min_length", "dav_methods", "dav_ext_methods",
    "ssl_certificate", "ssl_protocols", "ssl_ciphers",
    "ssl_prefer_server_ciphers", "ssl_verify_client", "ssl_verify_depth",
    "ssl_buffer_size", "ssl_session_cache", "ssl_session_timeout",
    "ssl_conf_command", "ssl_ecdh_curve", "ssl_dhparam", "ssl_trusted_certificate",
    "ssl_client_certificate", "ssl_crl", "resolver", "resolver_timeout",
    "limit_rate", "limit_conn", "limit_req", "expires", "etag", "charset",
    "merge_slashes", "server_tokens", "reset_timedout_connection",
    "send_timeout", "proxy_connect_timeout", "proxy_read_timeout",
    "proxy_send_timeout", "proxy_buffering", "proxy_request_buffering",
    "underscores_in_headers", "large_client_header_buffers",
    NULL
}
Definition at line 102 of file config_download_classify.c.
Referenced by dashboard_keep_value().
dashboard_secret_directives
const char* const dashboard_secret_directives[] static
Definition at line 28 of file config_download_classify.c.
Referenced by dashboard_name_is_secret().
dashboard_secret_exceptions
const char* const dashboard_secret_exceptions[] static
Initial value:
= {
    "brix_token_issuer",
    "brix_token_audience",
    "brix_token_jwks_refresh_interval",
    "brix_token_cache",
    "brix_webdav_token_issuer",
    "brix_webdav_token_audience",
    "brix_webdav_token_introspect_ttl",
    "brix_webdav_token_introspect_loc",
    "brix_webdav_token_introspect_fail_open",
    NULL
}
Definition at line 84 of file config_download_classify.c.
Referenced by dashboard_name_is_secret().
dashboard_secret_name_substrings
const char* const dashboard_secret_name_substrings[] static
Initial value:
= {
    "secret", "passwd", "password", "passphrase", "keytab", "privatekey",
    "private_key", "accesskey", "access_key", "secretkey", "secret_key",
    "apikey", "api_key", "client_secret", "credential", "bearer", "macaroon",
    "hmac", "jwks",
    NULL
}
Definition at line 70 of file config_download_classify.c.
Referenced by dashboard_name_is_secret().