nginx-xrootd: src/core/config/config.h File Reference
config.h File Reference
#include "core/ngx_brix_module.h"
Enumerations
enum brix_path_kind_t { BRIX_PATH_REGULAR_FILE , BRIX_PATH_DIRECTORY , BRIX_PATH_FILE_OR_DIRECTORY }
Functions
ngx_int_t brix_validate_path (ngx_conf_t *cf, const char *label, const ngx_str_t *path, brix_path_kind_t kind, int access_mode)
char * brix_copy_conf_string (ngx_conf_t *cf, const ngx_str_t *src, ngx_str_t *dst)
ngx_int_t brix_config_prepare_server (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
ngx_int_t brix_configure_gsi (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
ngx_int_t brix_configure_tls (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
ngx_int_t brix_configure_token_auth (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
void brix_token_jwks_schedule_refresh (ngx_cycle_t *cycle, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_configure_sss_auth (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
ngx_int_t brix_sss_load_keytab (ngx_conf_t *cf, ngx_str_t *path, ngx_array_t **out_keys)
ngx_int_t brix_configure_krb5_auth (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
ngx_int_t brix_config_finalize_policy (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
ngx_int_t brix_metrics_ensure_zone (ngx_conf_t *cf)
ngx_int_t brix_configure_metrics (ngx_conf_t *cf, ngx_stream_core_main_conf_t *cmcf)
ngx_int_t brix_configure_session_registry (ngx_conf_t *cf, ngx_uint_t slots)
ngx_int_t brix_srv_configure_registry (ngx_conf_t *cf, ngx_uint_t slots)
ngx_int_t brix_pending_configure (ngx_conf_t *cf)
WHAT: Configure the pending-locate shared-memory zone during nginx startup.
ngx_int_t brix_configure_dashboard (ngx_conf_t *cf)
ngx_int_t brix_tpc_registry_configure (ngx_conf_t *cf)
ngx_int_t brix_configure_thread_pools (ngx_conf_t *cf, ngx_stream_core_main_conf_t *cmcf)
Enumeration Type Documentation
brix_path_kind_t
enum brix_path_kind_t
Enumerator
BRIX_PATH_REGULAR_FILE
BRIX_PATH_DIRECTORY
BRIX_PATH_FILE_OR_DIRECTORY
Definition at line 18 of file config.h.
Function Documentation
brix_config_finalize_policy()
ngx_int_t brix_config_finalize_policy (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf)
Definition at line 122 of file policy.c.
References BRIX_AUTH_BOTH, BRIX_AUTH_GSI, BRIX_AUTH_TOKEN, brix_finalize_authdb_rules(), brix_finalize_group_rules(), brix_finalize_vo_rules(), BRIX_PATH_DIRECTORY, brix_validate_path(), and brix_voms_available().
Referenced by postconf_finalize_policies().
brix_config_prepare_server()
ngx_int_t brix_config_prepare_server (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf)
Definition at line 434 of file runtime_server.c.
References BRIX_PROXY_AUTH_GSI, brix_server_guard_remote_authz(), brix_server_setup_export(), brix_server_setup_logging(), brix_server_setup_tls(), brix_server_validate_cache(), brix_server_validate_wt_stage(), and brix_shared_apply_read_only().
Referenced by postconf_prepare_servers().
brix_configure_dashboard()
ngx_int_t brix_configure_dashboard (ngx_conf_t * cf)
Definition at line 24 of file config.c.
References brix_shm_zone_size(), ngx_brix_dashboard_events_shm_init(), ngx_brix_dashboard_events_shm_zone, ngx_brix_dashboard_history_shm_init(), ngx_brix_dashboard_history_shm_zone, ngx_brix_dashboard_shm_init(), ngx_brix_dashboard_shm_zone, and ngx_stream_brix_module.
Referenced by ngx_http_brix_cvmfs_postconfiguration(), and ngx_stream_brix_postconfiguration().
brix_configure_gsi()
ngx_int_t brix_configure_gsi (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf)
Definition at line 359 of file config.c.
References BRIX_AUTH_BOTH, BRIX_AUTH_GSI, brix_gsi_build_trust_store(), brix_gsi_cache_cert_pem(), brix_gsi_compute_ca_hashes(), brix_gsi_load_certificate(), brix_gsi_load_private_key(), and brix_gsi_require_trust_inputs().
Referenced by postconf_prepare_servers().
brix_configure_krb5_auth()
ngx_int_t brix_configure_krb5_auth (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf)
Definition at line 281 of file config.c.
References BRIX_AUTH_KRB5.
Referenced by postconf_prepare_servers().
brix_configure_metrics()
ngx_int_t brix_configure_metrics (ngx_conf_t * cf, ngx_stream_core_main_conf_t * cmcf)
Definition at line 43 of file config.c.
References brix_metrics_ensure_zone(), BRIX_METRICS_MAX_SERVERS, and ngx_stream_brix_module.
Referenced by ngx_stream_brix_postconfiguration().
brix_configure_session_registry()
ngx_int_t brix_configure_session_registry (ngx_conf_t * cf, ngx_uint_t slots)
Definition at line 74 of file registry.c.
References brix_handle_shm_init_zone(), brix_handle_shm_zone, brix_session_registry_nslots, BRIX_SESSION_REGISTRY_SLOTS, brix_session_shm_init_zone(), brix_session_shm_zone, brix_shm_zone_size(), brix_shm_zone_warn_on_resize(), and ngx_stream_brix_module.
Referenced by postconf_session_registry().
brix_configure_sss_auth()
ngx_int_t brix_configure_sss_auth (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf)
Definition at line 225 of file config.c.
References BRIX_AUTH_SSS, brix_sss_load_keytab(), and brix_sss_upstream_needed().
Referenced by postconf_prepare_servers().
brix_configure_thread_pools()
ngx_int_t brix_configure_thread_pools (ngx_conf_t * cf, ngx_stream_core_main_conf_t * cmcf)
Definition at line 19 of file config.c.
References ngx_stream_brix_module.
Referenced by ngx_stream_brix_postconfiguration().
brix_configure_tls()
ngx_int_t brix_configure_tls (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf)
Definition at line 62 of file tls_config.c.
References brix_ocsp_stapling_cb(), and ngx_pcalloc().
Referenced by postconf_prepare_servers().
brix_configure_token_auth()
ngx_int_t brix_configure_token_auth (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf)
Definition at line 192 of file config.c.
References BRIX_AUTH_BOTH, BRIX_AUTH_TOKEN, brix_token_configure_registry(), brix_token_load_and_register_jwks(), brix_token_log_summary(), and brix_token_require_single_issuer_fields().
Referenced by postconf_prepare_servers().
brix_copy_conf_string()
char * brix_copy_conf_string (ngx_conf_t * cf, const ngx_str_t * src, ngx_str_t * dst)
Definition at line 72 of file helpers.c.
References ngx_memcpy, and ngx_pnalloc().
Referenced by brix_conf_set_cms_manager(), brix_conf_set_require_vo(), and webdav_conf_require_vo().
brix_metrics_ensure_zone()
ngx_int_t brix_metrics_ensure_zone (ngx_conf_t * cf)
Definition at line 24 of file config.c.
References brix_shm_zone_size(), ngx_brix_metrics_shm_init(), ngx_brix_shm_zone, and ngx_stream_brix_module.
Referenced by brix_configure_metrics(), and ngx_http_brix_cvmfs_postconfiguration().
brix_pending_configure()
ngx_int_t brix_pending_configure (ngx_conf_t * cf)
WHAT: Configure the pending-locate shared-memory zone during nginx startup.
WHY: Creates a dedicated SHM region named "brix_pending_locate" that stores up to BRIX_PENDING_LOCATE_SLOTS (32) in-flight kXR_locate entries. Each entry tracks a worker's locate request until the CMS manager responds with a redirect host/port via kXR_select. HOW: Adds a shared memory zone sized via brix_shm_zone_size() so the table can be slab-allocated alongside the slab-pool header (see brix_pending_shm_init_zone), registers brix_pending_shm_init_zone as the init callback (called after allocation), and sets data=(void *) 1 as an initialization sentinel so accessors know the zone is not yet ready. Returns NGX_OK or NGX_ERROR.
Definition at line 77 of file pending.c.
References brix_pending_shm_init_zone(), brix_pending_shm_zone, brix_shm_zone_size(), and ngx_stream_brix_module.
Referenced by postconf_shared_registries().
brix_srv_configure_registry()
ngx_int_t brix_srv_configure_registry (ngx_conf_t * cf, ngx_uint_t slots)
Definition at line 113 of file registry.c.
References brix_shm_zone_size(), brix_shm_zone_warn_on_resize(), brix_srv_registry_nslots, brix_srv_shm_init_zone(), brix_srv_shm_zone, and ngx_stream_brix_module.
Referenced by postconf_server_registry().
brix_sss_load_keytab()
ngx_int_t brix_sss_load_keytab (ngx_conf_t * cf, ngx_str_t * path, ngx_array_t ** out_keys)
Definition at line 92 of file config.c.
References BRIX_DIAG_CONF, BRIX_PATH_REGULAR_FILE, brix_sss_parse_key_line(), brix_validate_path(), close(), fstat(), open(), sss_keytab_mode_ok(), and stat().
Referenced by brix_cms_srv_set_sss_keytab(), and brix_configure_sss_auth().
brix_token_jwks_schedule_refresh()
void brix_token_jwks_schedule_refresh (ngx_cycle_t * cycle, ngx_stream_brix_srv_conf_t * conf)
Definition at line 110 of file refresh.c.
References brix_token_jwks_refresh_handler(), and ngx_pcalloc().
Referenced by brix_init_server_crl_jwks().
brix_tpc_registry_configure()
ngx_int_t brix_tpc_registry_configure (ngx_conf_t * cf)
Definition at line 117 of file registry.c.
References brix_shm_zone_size(), brix_tpc_registry_shm_init(), brix_tpc_registry_shm_zone, and ngx_stream_brix_module.
Referenced by ngx_http_brix_webdav_postconfiguration(), and postconf_shared_registries().
brix_validate_path()
ngx_int_t brix_validate_path (ngx_conf_t * cf, const char * label, const ngx_str_t * path, brix_path_kind_t kind, int access_mode)
Definition at line 13 of file helpers.c.
References access(), BRIX_PATH_DIRECTORY, BRIX_PATH_FILE_OR_DIRECTORY, BRIX_PATH_REGULAR_FILE, and stat().
Referenced by brix_config_finalize_policy(), brix_gsi_require_trust_inputs(), brix_prepare_export_root(), brix_server_validate_cache(), brix_sss_load_keytab(), and brix_token_load_and_register_jwks().