nginx-xrootd: src/protocols/webdav/config_internal.h File Reference
config_internal.h File Reference
#include "webdav.h"
Functions
void webdav_x509_store_cleanup (void *data)
ngx_int_t webdav_validate_cors_origins (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
ngx_uint_t webdav_summary_is_new (ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_loc_conf_t *prev)
void webdav_log_endpoint_summary (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
char * webdav_merge_base_conf (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *prev, ngx_http_brix_webdav_loc_conf_t *conf)
char * webdav_validate_webdav_enabled (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *prev, ngx_http_brix_webdav_loc_conf_t *conf)
char * webdav_merge_auth_token_conf (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *prev, ngx_http_brix_webdav_loc_conf_t *conf)
char * webdav_merge_mirror_and_summary (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *prev, ngx_http_brix_webdav_loc_conf_t *conf)
Function Documentation
webdav_log_endpoint_summary()
void webdav_log_endpoint_summary (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 240 of file config.c.
References ngx_http_brix_shared_conf_t::allow_write, ngx_http_brix_webdav_loc_conf_t::auth, ngx_http_brix_webdav_loc_conf_t::cadir, ngx_http_brix_webdav_loc_conf_t::cafile, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_loc_conf_t::crl, ngx_http_brix_webdav_loc_conf_t::jwks_key_count, ngx_http_brix_webdav_loc_conf_t::proxy_certs, ngx_http_brix_webdav_loc_conf_t::pwd_file, ngx_http_brix_shared_conf_t::root, ngx_http_brix_webdav_loc_conf_t::tpc, webdav_auth_name(), and webdav_log_endpoint_warnings().
Referenced by webdav_merge_mirror_and_summary().
webdav_merge_auth_token_conf()
char * webdav_merge_auth_token_conf (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * prev, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 48 of file config_proxy.c.
References BRIX_AUTHZ_CAPABILITY, brix_jwks_load(), brix_jwks_register_cleanup(), BRIX_MAX_JWKS_KEYS, brix_token_registry_build(), ngx_http_brix_webdav_loc_conf_t::jwks_key_count, ngx_http_brix_webdav_loc_conf_t::jwks_keys, ngx_http_brix_webdav_loc_conf_t::token_config, ngx_http_brix_webdav_loc_conf_t::token_jwks, and ngx_http_brix_webdav_loc_conf_t::token_registry.
Referenced by ngx_http_brix_webdav_merge_loc_conf().
webdav_merge_base_conf()
char * webdav_merge_base_conf (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * prev, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 48 of file config_merge.c.
References ngx_http_brix_webdav_loc_conf_t::acc, ngx_http_brix_webdav_loc_conf_t::auth, ngx_http_brix_webdav_loc_conf_t::authdb_rules, brix_acc_http_merge_conf(), BRIX_CKS_FMT_TEXT, BRIX_CRL_MODE_TRY, brix_http_common_adopt(), brix_integrity_set_xattr_format(), BRIX_MERGE_PTR, BRIX_SP_MODE_ON, BRIX_TOKEN_CLOCK_SKEW_SECS, ngx_http_brix_webdav_loc_conf_t::cache_root, ngx_http_brix_webdav_loc_conf_t::cadir, ngx_http_brix_webdav_loc_conf_t::cafile, ngx_http_brix_webdav_loc_conf_t::checksum_on_write, ngx_http_brix_webdav_loc_conf_t::checksum_xattr_format, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_loc_conf_t::cors_credentials, ngx_http_brix_webdav_loc_conf_t::cors_max_age, ngx_http_brix_webdav_loc_conf_t::crl, ngx_http_brix_webdav_loc_conf_t::crl_mode, ngx_http_brix_webdav_loc_conf_t::delegation_endpoint, ngx_http_brix_webdav_loc_conf_t::dig_auth_file, ngx_http_brix_webdav_loc_conf_t::dig_enable, ngx_http_brix_webdav_loc_conf_t::dig_exports, ngx_http_brix_webdav_loc_conf_t::http_query_token, ngx_http_brix_webdav_loc_conf_t::introspect_fail_open, ngx_http_brix_webdav_loc_conf_t::introspect_loc, ngx_http_brix_webdav_loc_conf_t::introspect_ttl, ngx_http_brix_webdav_loc_conf_t::introspect_url, brix_rate_limit_conf_t::kv, ngx_http_brix_webdav_loc_conf_t::lock_startup_sweep, ngx_http_brix_webdav_loc_conf_t::lock_timeout, ngx_http_brix_webdav_loc_conf_t::macaroon_location, ngx_http_brix_webdav_loc_conf_t::macaroon_max_validity, ngx_http_brix_shared_merge(), ngx_http_brix_webdav_tpc_merge_loc_conf(), ngx_http_brix_webdav_loc_conf_t::open_file_cache, ngx_http_brix_webdav_loc_conf_t::open_file_cache_errors, ngx_http_brix_webdav_loc_conf_t::open_file_cache_events, ngx_http_brix_webdav_loc_conf_t::open_file_cache_min_uses, ngx_http_brix_webdav_loc_conf_t::open_file_cache_valid, ngx_http_brix_webdav_loc_conf_t::proxy_certs, ngx_http_brix_webdav_loc_conf_t::pwd_file, ngx_http_brix_webdav_loc_conf_t::rate_limit, ngx_http_brix_webdav_loc_conf_t::require_digest, ngx_http_brix_webdav_loc_conf_t::revoke_kv, ngx_http_brix_webdav_loc_conf_t::signing_policy_mode, ngx_http_brix_webdav_loc_conf_t::ssl_client_capath, ngx_http_brix_webdav_loc_conf_t::tape_rest, ngx_http_brix_webdav_loc_conf_t::tcp_congestion, ngx_http_brix_webdav_loc_conf_t::token_audience, ngx_http_brix_webdav_loc_conf_t::token_cache_kv, ngx_http_brix_webdav_loc_conf_t::token_clock_skew, ngx_http_brix_webdav_loc_conf_t::token_config, ngx_http_brix_webdav_loc_conf_t::token_issuer, ngx_http_brix_webdav_loc_conf_t::token_jwks, ngx_http_brix_webdav_loc_conf_t::token_macaroon_secret, ngx_http_brix_webdav_loc_conf_t::token_macaroon_secret_old, ngx_http_brix_webdav_loc_conf_t::token_registry, ngx_http_brix_webdav_loc_conf_t::upload_resume, ngx_http_brix_webdav_loc_conf_t::upload_stage_dir, ngx_http_brix_webdav_loc_conf_t::verify_depth, ngx_http_brix_webdav_loc_conf_t::vo_rules, ngx_http_brix_webdav_loc_conf_t::voms_cert_dir, ngx_http_brix_webdav_loc_conf_t::vomsdir, WEBDAV_AUTH_OPTIONAL, ngx_http_brix_webdav_loc_conf_t::zip_access, and ngx_http_brix_webdav_loc_conf_t::zip_cd_max_bytes.
Referenced by ngx_http_brix_webdav_merge_loc_conf().
webdav_merge_mirror_and_summary()
char * webdav_merge_mirror_and_summary (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * prev, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 93 of file config_proxy.c.
References brix_http_mirror_setup(), BRIX_MIRROR_M_DEFAULT, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::enable, brix_mirror_conf_t::enabled, brix_mirror_conf_t::log_diverge, brix_mirror_conf_t::method_mask, ngx_http_brix_webdav_loc_conf_t::mirror, ngx_http_brix_webdav_loc_conf_t::mirror_upstream_conf, brix_mirror_conf_t::mirror_writes, brix_mirror_conf_t::sample_pct, brix_mirror_conf_t::strip_auth, brix_mirror_conf_t::targets, brix_mirror_conf_t::timeout_ms, brix_mirror_conf_t::token, webdav_log_endpoint_summary(), and webdav_summary_is_new().
Referenced by ngx_http_brix_webdav_merge_loc_conf().
webdav_summary_is_new()
ngx_uint_t webdav_summary_is_new (ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_loc_conf_t * prev)
Definition at line 214 of file config.c.
References ngx_http_brix_shared_conf_t::allow_write, ngx_http_brix_webdav_loc_conf_t::auth, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::enable, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by webdav_merge_mirror_and_summary().
webdav_validate_cors_origins()
ngx_int_t webdav_validate_cors_origins (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 64 of file config.c.
References ngx_http_brix_webdav_loc_conf_t::cors_origins, and webdav_tpc_str_has_ctl.
Referenced by webdav_validate_auth_paths().
webdav_validate_webdav_enabled()
char * webdav_validate_webdav_enabled (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * prev, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 464 of file config_merge.c.
References brix_http_open_rootfd(), brix_tier_register_stores(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::enable, webdav_build_ca_store_once(), webdav_configure_storage_backend(), webdav_finalize_authz_rules(), webdav_prepare_export_root(), webdav_prepare_stage_and_cache(), webdav_run_lock_startup_sweep(), webdav_validate_auth_paths(), webdav_validate_pwd_file_path(), webdav_validate_token_jwks_path(), and webdav_validate_tpc_paths().
Referenced by ngx_http_brix_webdav_merge_loc_conf().
webdav_x509_store_cleanup()
void webdav_x509_store_cleanup (void * data)
Definition at line 48 of file config.c.
Referenced by webdav_build_ca_store_once().