nginx-xrootd: src/protocols/webdav/config_merge.c File Reference
config_merge.c File Reference
#include "webdav.h"
#include "auth/crypto/store_policy.h"
#include "core/compat/integrity_info.h"
#include "core/compat/tmp_path.h"
#include "auth/token/issuer_registry.h"
#include "proxy_internal.h"
#include "net/mirror/http_mirror.h"
#include "core/config/config.h"
#include "fs/path/path.h"
#include "core/config/root_prepare.h"
#include "core/config/http_rootfd.h"
#include "core/config/http_common.h"
#include "core/config/export_guard.h"
#include "core/compat/staged_file.h"
#include "fs/backend/sd.h"
#include "fs/vfs/vfs_backend_registry.h"
#include <openssl/x509.h>
#include <limits.h>
#include <sys/stat.h>
#include <unistd.h>
#include "core/compat/alloc_guard.h"
#include "core/config/credential_block.h"
#include "config_internal.h"
Macros
#define webdav_validate_path brix_validate_path
#define WEBDAV_PATH_REGULAR_FILE BRIX_PATH_REGULAR_FILE
#define WEBDAV_PATH_DIRECTORY BRIX_PATH_DIRECTORY
#define WEBDAV_PATH_FILE_OR_DIRECTORY BRIX_PATH_FILE_OR_DIRECTORY
Functions
char * webdav_merge_base_conf (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *prev, ngx_http_brix_webdav_loc_conf_t *conf)
static char * webdav_prepare_export_root (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
static char * webdav_finalize_authz_rules (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
static char * webdav_set_storage_credential (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
static char * webdav_configure_storage_backend (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
static char * webdav_prepare_stage_and_cache (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
static void webdav_run_lock_startup_sweep (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
static char * webdav_validate_auth_paths (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
static char * webdav_build_ca_store_once (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
static char * webdav_validate_token_jwks_path (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
static char * webdav_validate_pwd_file_path (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
static char * webdav_validate_tpc_paths (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
char * webdav_validate_webdav_enabled (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *prev, ngx_http_brix_webdav_loc_conf_t *conf)
Macro Definition Documentation
WEBDAV_PATH_DIRECTORY
#define WEBDAV_PATH_DIRECTORY BRIX_PATH_DIRECTORY
Definition at line 45 of file config_merge.c.
WEBDAV_PATH_FILE_OR_DIRECTORY
#define WEBDAV_PATH_FILE_OR_DIRECTORY BRIX_PATH_FILE_OR_DIRECTORY
Definition at line 46 of file config_merge.c.
WEBDAV_PATH_REGULAR_FILE
#define WEBDAV_PATH_REGULAR_FILE BRIX_PATH_REGULAR_FILE
Definition at line 44 of file config_merge.c.
webdav_validate_path
#define webdav_validate_path brix_validate_path
Definition at line 43 of file config_merge.c.
Function Documentation
webdav_build_ca_store_once()
static char * webdav_build_ca_store_once (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 365 of file config_merge.c.
References ngx_http_brix_webdav_loc_conf_t::auth, ngx_http_brix_webdav_loc_conf_t::ca_store, ngx_http_brix_webdav_loc_conf_t::cadir, ngx_http_brix_webdav_loc_conf_t::cafile, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::root, WEBDAV_AUTH_OPTIONAL, WEBDAV_AUTH_REQUIRED, webdav_build_ca_store(), webdav_check_pki_consistency(), and webdav_x509_store_cleanup().
Referenced by webdav_validate_webdav_enabled().
webdav_configure_storage_backend()
static char * webdav_configure_storage_backend (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 246 of file config_merge.c.
References BRIX_AF_AUTO, brix_vfs_backend_config_str(), brix_vfs_backend_set_staging(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::pblock_block_size, ngx_http_brix_shared_conf_t::root_canon, ngx_http_brix_shared_conf_t::storage_backend, ngx_http_brix_shared_conf_t::storage_staging, and webdav_set_storage_credential().
Referenced by webdav_validate_webdav_enabled().
webdav_finalize_authz_rules()
static char * webdav_finalize_authz_rules (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 187 of file config_merge.c.
References ngx_http_brix_webdav_loc_conf_t::authdb_rules, brix_finalize_authdb_rules(), brix_finalize_vo_rules(), brix_voms_init(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::root, ngx_http_brix_webdav_loc_conf_t::vo_rules, and ngx_http_brix_webdav_loc_conf_t::vomsdir.
Referenced by webdav_validate_webdav_enabled().
webdav_merge_base_conf()
char * webdav_merge_base_conf (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * prev, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 49 of file config_merge.c.
References ngx_http_brix_webdav_loc_conf_t::acc, ngx_http_brix_webdav_loc_conf_t::auth, ngx_http_brix_webdav_loc_conf_t::authdb_rules, brix_acc_http_merge_conf(), BRIX_CKS_FMT_TEXT, BRIX_CRL_MODE_TRY, brix_http_common_adopt(), brix_integrity_set_xattr_format(), BRIX_MERGE_PTR, BRIX_SP_MODE_ON, BRIX_TOKEN_CLOCK_SKEW_SECS, ngx_http_brix_webdav_loc_conf_t::cache_root, ngx_http_brix_webdav_loc_conf_t::cadir, ngx_http_brix_webdav_loc_conf_t::cafile, ngx_http_brix_webdav_loc_conf_t::checksum_on_write, ngx_http_brix_webdav_loc_conf_t::checksum_xattr_format, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_loc_conf_t::cors_credentials, ngx_http_brix_webdav_loc_conf_t::cors_max_age, ngx_http_brix_webdav_loc_conf_t::crl, ngx_http_brix_webdav_loc_conf_t::crl_mode, ngx_http_brix_webdav_loc_conf_t::delegation_endpoint, ngx_http_brix_webdav_loc_conf_t::dig_auth_file, ngx_http_brix_webdav_loc_conf_t::dig_enable, ngx_http_brix_webdav_loc_conf_t::dig_exports, ngx_http_brix_webdav_loc_conf_t::http_query_token, ngx_http_brix_webdav_loc_conf_t::introspect_fail_open, ngx_http_brix_webdav_loc_conf_t::introspect_loc, ngx_http_brix_webdav_loc_conf_t::introspect_ttl, ngx_http_brix_webdav_loc_conf_t::introspect_url, brix_rate_limit_conf_t::kv, ngx_http_brix_webdav_loc_conf_t::lock_startup_sweep, ngx_http_brix_webdav_loc_conf_t::lock_timeout, ngx_http_brix_webdav_loc_conf_t::macaroon_location, ngx_http_brix_webdav_loc_conf_t::macaroon_max_validity, ngx_http_brix_shared_merge(), ngx_http_brix_webdav_tpc_merge_loc_conf(), ngx_http_brix_webdav_loc_conf_t::open_file_cache, ngx_http_brix_webdav_loc_conf_t::open_file_cache_errors, ngx_http_brix_webdav_loc_conf_t::open_file_cache_events, ngx_http_brix_webdav_loc_conf_t::open_file_cache_min_uses, ngx_http_brix_webdav_loc_conf_t::open_file_cache_valid, ngx_http_brix_webdav_loc_conf_t::proxy_certs, ngx_http_brix_webdav_loc_conf_t::pwd_file, ngx_http_brix_webdav_loc_conf_t::rate_limit, ngx_http_brix_webdav_loc_conf_t::revoke_kv, ngx_http_brix_webdav_loc_conf_t::signing_policy_mode, ngx_http_brix_webdav_loc_conf_t::ssl_client_capath, ngx_http_brix_webdav_loc_conf_t::tape_rest, ngx_http_brix_webdav_loc_conf_t::tcp_congestion, ngx_http_brix_webdav_loc_conf_t::token_audience, ngx_http_brix_webdav_loc_conf_t::token_cache_kv, ngx_http_brix_webdav_loc_conf_t::token_clock_skew, ngx_http_brix_webdav_loc_conf_t::token_config, ngx_http_brix_webdav_loc_conf_t::token_issuer, ngx_http_brix_webdav_loc_conf_t::token_jwks, ngx_http_brix_webdav_loc_conf_t::token_macaroon_secret, ngx_http_brix_webdav_loc_conf_t::token_macaroon_secret_old, ngx_http_brix_webdav_loc_conf_t::token_registry, ngx_http_brix_webdav_loc_conf_t::upload_resume, ngx_http_brix_webdav_loc_conf_t::upload_stage_dir, ngx_http_brix_webdav_loc_conf_t::verify_depth, ngx_http_brix_webdav_loc_conf_t::vo_rules, ngx_http_brix_webdav_loc_conf_t::voms_cert_dir, ngx_http_brix_webdav_loc_conf_t::vomsdir, WEBDAV_AUTH_OPTIONAL, ngx_http_brix_webdav_loc_conf_t::zip_access, and ngx_http_brix_webdav_loc_conf_t::zip_cd_max_bytes.
Referenced by ngx_http_brix_webdav_merge_loc_conf().
webdav_prepare_export_root()
static char * webdav_prepare_export_root (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 166 of file config_merge.c.
References brix_export_root_opts_t::allow_write, ngx_http_brix_shared_conf_t::allow_write, brix_prepare_export_root(), brix_storage_backend_is_remote(), brix_storage_backend_posix_root(), brix_tmp_reap_register(), brix_export_root_opts_t::canon_size, ngx_http_brix_webdav_loc_conf_t::common, brix_export_root_opts_t::directive_name, brix_export_root_opts_t::required, ngx_http_brix_shared_conf_t::root, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by webdav_validate_webdav_enabled().
webdav_prepare_stage_and_cache()
static char * webdav_prepare_stage_and_cache (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 262 of file config_merge.c.
References brix_export_root_opts_t::allow_write, brix_assert_dir_outside_export(), brix_prepare_export_root(), brix_stage_dir_register(), ngx_http_brix_webdav_loc_conf_t::cache_root, ngx_http_brix_webdav_loc_conf_t::cache_root_canon, brix_export_root_opts_t::canon_size, ngx_http_brix_webdav_loc_conf_t::common, brix_export_root_opts_t::directive_name, brix_export_root_opts_t::required, ngx_http_brix_shared_conf_t::root_canon, ngx_http_brix_webdav_loc_conf_t::upload_stage_dir, and ngx_http_brix_webdav_loc_conf_t::upload_stage_dir_canon.
Referenced by webdav_validate_webdav_enabled().
webdav_run_lock_startup_sweep()
static void webdav_run_lock_startup_sweep (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 304 of file config_merge.c.
References ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_loc_conf_t::lock_startup_sweep, ngx_test_config, ngx_http_brix_shared_conf_t::root_canon, and webdav_lock_startup_sweep().
Referenced by webdav_validate_webdav_enabled().
webdav_set_storage_credential()
static char * webdav_set_storage_credential (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 215 of file config_merge.c.
References brix_credential_lookup(), brix_credential_to_backend_cred(), brix_vfs_backend_set_credential(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::root_canon, and ngx_http_brix_shared_conf_t::storage_credential.
Referenced by webdav_configure_storage_backend().
webdav_validate_auth_paths()
static char * webdav_validate_auth_paths (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 319 of file config_merge.c.
References ngx_http_brix_shared_conf_t::allow_write, ngx_http_brix_webdav_loc_conf_t::auth, brix_shared_security_gate(), ngx_http_brix_webdav_loc_conf_t::cadir, ngx_http_brix_webdav_loc_conf_t::cafile, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_loc_conf_t::crl, ngx_http_brix_webdav_loc_conf_t::pwd_file, ngx_http_brix_shared_conf_t::strict_security, ngx_http_brix_webdav_loc_conf_t::token_config, ngx_http_brix_webdav_loc_conf_t::token_jwks, ngx_http_brix_webdav_loc_conf_t::token_macaroon_secret, WEBDAV_AUTH_OPTIONAL, WEBDAV_AUTH_REQUIRED, WEBDAV_PATH_DIRECTORY, WEBDAV_PATH_FILE_OR_DIRECTORY, WEBDAV_PATH_REGULAR_FILE, webdav_validate_cors_origins(), and webdav_validate_path.
Referenced by webdav_validate_webdav_enabled().
webdav_validate_pwd_file_path()
static char * webdav_validate_pwd_file_path (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 426 of file config_merge.c.
References ngx_http_brix_webdav_loc_conf_t::pwd_file, WEBDAV_PATH_REGULAR_FILE, and webdav_validate_path.
Referenced by webdav_validate_webdav_enabled().
webdav_validate_token_jwks_path()
static char * webdav_validate_token_jwks_path (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 404 of file config_merge.c.
References ngx_http_brix_webdav_loc_conf_t::token_audience, ngx_http_brix_webdav_loc_conf_t::token_issuer, ngx_http_brix_webdav_loc_conf_t::token_jwks, WEBDAV_PATH_REGULAR_FILE, and webdav_validate_path.
Referenced by webdav_validate_webdav_enabled().
webdav_validate_tpc_paths()
static char * webdav_validate_tpc_paths (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 441 of file config_merge.c.
References ngx_http_brix_webdav_loc_conf_t::tpc, ngx_http_brix_webdav_loc_conf_t::tpc_cadir, ngx_http_brix_webdav_loc_conf_t::tpc_cafile, ngx_http_brix_webdav_loc_conf_t::tpc_cert, ngx_http_brix_webdav_loc_conf_t::tpc_curl, ngx_http_brix_webdav_loc_conf_t::tpc_key, WEBDAV_PATH_DIRECTORY, WEBDAV_PATH_REGULAR_FILE, and webdav_validate_path.
Referenced by webdav_validate_webdav_enabled().
webdav_validate_webdav_enabled()
char * webdav_validate_webdav_enabled (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * prev, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 464 of file config_merge.c.
References brix_http_open_rootfd(), brix_tier_register_stores(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::enable, webdav_build_ca_store_once(), webdav_configure_storage_backend(), webdav_finalize_authz_rules(), webdav_prepare_export_root(), webdav_prepare_stage_and_cache(), webdav_run_lock_startup_sweep(), webdav_validate_auth_paths(), webdav_validate_pwd_file_path(), webdav_validate_token_jwks_path(), and webdav_validate_tpc_paths().
Referenced by ngx_http_brix_webdav_merge_loc_conf().