nginx-xrootd: src/observability/dashboard/config_download.c File Reference
config_download.c File Reference
#include "dashboard_http.h"
#include "core/http/http_headers.h"
#include "core/compat/cstr.h"
#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>
Macros
#define DASHBOARD_CONFIG_MAX_BYTES (1 << 20) /* 1 MiB cap (fail-safe) */
#define DASHBOARD_REDACTED "[redacted]"
Functions
static u_char dashboard_lc (u_char c)
static ngx_uint_t dashboard_name_eq (const u_char *name, size_t len, const char *lit)
static ngx_uint_t dashboard_name_in (const u_char *name, size_t len, const char *const *set)
static ngx_uint_t dashboard_name_contains (const u_char *name, size_t len, const char *sub)
static ngx_uint_t dashboard_name_is_secret (const u_char *name, size_t len)
static ngx_uint_t dashboard_keep_value (const u_char *name, size_t len)
static u_char * dashboard_scrub_value_creds (u_char *p, u_char *end)
static u_char * dashboard_emit_masked (u_char *out, const u_char *line, const u_char *line_end, const u_char *name, const u_char *name_end)
static ngx_int_t dashboard_redact_config (ngx_http_request_t *r, const u_char *in, size_t in_len, u_char **out_buf, size_t *out_len)
static ngx_int_t dashboard_read_config_file (ngx_http_request_t *r, u_char **buf, size_t *len)
static ngx_int_t dashboard_send_config (ngx_http_request_t *r, u_char *body, size_t len)
ngx_int_t ngx_http_brix_dashboard_config_download_handler (ngx_http_request_t *r)
Variables
static const char *const dashboard_secret_directives []
static const char *const dashboard_secret_name_substrings []
static const char *const dashboard_secret_exceptions []
static const char *const dashboard_safe_stock_directives []
Macro Definition Documentation
DASHBOARD_CONFIG_MAX_BYTES
#define DASHBOARD_CONFIG_MAX_BYTES (1 << 20) /* 1 MiB cap (fail-safe) */
Definition at line 44 of file config_download.c.
DASHBOARD_REDACTED
#define DASHBOARD_REDACTED "[redacted]"
Definition at line 45 of file config_download.c.
Function Documentation
dashboard_emit_masked()
static u_char * dashboard_emit_masked (u_char * out, const u_char * line, const u_char * line_end, const u_char * name, const u_char * name_end) static
Definition at line 347 of file config_download.c.
References DASHBOARD_REDACTED.
Referenced by dashboard_redact_config().
dashboard_keep_value()
static ngx_uint_t dashboard_keep_value (const u_char * name, size_t len) static
Definition at line 243 of file config_download.c.
References dashboard_name_eq(), dashboard_name_in(), dashboard_name_is_secret(), dashboard_safe_stock_directives, and name.
Referenced by dashboard_redact_config().
dashboard_lc()
static u_char dashboard_lc (u_char c) static
Definition at line 153 of file config_download.c.
References c.
Referenced by dashboard_name_contains(), and dashboard_name_eq().
dashboard_name_contains()
static ngx_uint_t dashboard_name_contains (const u_char * name, size_t len, const char * sub) static
Definition at line 188 of file config_download.c.
References dashboard_lc(), and name.
Referenced by dashboard_name_is_secret().
dashboard_name_eq()
static ngx_uint_t dashboard_name_eq (const u_char * name, size_t len, const char * lit) static
Definition at line 160 of file config_download.c.
References dashboard_lc(), and name.
Referenced by dashboard_keep_value(), dashboard_name_in(), dashboard_name_is_secret(), and dashboard_scrub_value_creds().
dashboard_name_in()
static ngx_uint_t dashboard_name_in (const u_char * name, size_t len, const char *const * set) static
Definition at line 174 of file config_download.c.
References dashboard_name_eq(), and name.
Referenced by dashboard_keep_value(), and dashboard_name_is_secret().
dashboard_name_is_secret()
static ngx_uint_t dashboard_name_is_secret (const u_char * name, size_t len) static
Definition at line 212 of file config_download.c.
References dashboard_name_contains(), dashboard_name_eq(), dashboard_name_in(), dashboard_secret_directives, dashboard_secret_exceptions, dashboard_secret_name_substrings, and name.
Referenced by dashboard_keep_value().
dashboard_read_config_file()
static ngx_int_t dashboard_read_config_file (ngx_http_request_t * r, u_char ** buf, size_t * len) static
Definition at line 481 of file config_download.c.
References brix_str_cbuf(), close(), DASHBOARD_CONFIG_MAX_BYTES, fstat(), open(), read(), and stat().
Referenced by ngx_http_brix_dashboard_config_download_handler().
dashboard_redact_config()
static ngx_int_t dashboard_redact_config (ngx_http_request_t * r, const u_char * in, size_t in_len, u_char ** out_buf, size_t * out_len) static
Definition at line 393 of file config_download.c.
References dashboard_emit_masked(), dashboard_keep_value(), dashboard_scrub_value_creds(), and name.
Referenced by ngx_http_brix_dashboard_config_download_handler().
dashboard_scrub_value_creds()
static u_char * dashboard_scrub_value_creds (u_char * p, u_char * end) static
Definition at line 265 of file config_download.c.
References dashboard_name_eq(), DASHBOARD_REDACTED, and s.
Referenced by dashboard_redact_config().
dashboard_send_config()
static ngx_int_t dashboard_send_config (ngx_http_request_t * r, u_char * body, size_t len) static
Definition at line 535 of file config_download.c.
Referenced by ngx_http_brix_dashboard_config_download_handler().
ngx_http_brix_dashboard_config_download_handler()
ngx_int_t ngx_http_brix_dashboard_config_download_handler (ngx_http_request_t * r)
Definition at line 577 of file config_download.c.
References brix_http_source_offer(), dashboard_read_config_file(), dashboard_redact_config(), dashboard_send_config(), ngx_http_brix_dashboard_check_auth(), and ngx_http_brix_dashboard_module.
Referenced by ngx_http_brix_dashboard_main_handler().
Variable Documentation
dashboard_safe_stock_directives
const char* const dashboard_safe_stock_directives[] static
Initial value:
= {
    "user", "worker_processes", "worker_connections", "worker_rlimit_nofile",
    "pid", "daemon", "master_process", "events", "use", "multi_accept",
    "http", "stream", "server", "location", "upstream", "types", "include_off",
    "default_type", "server_name", "listen", "root", "alias", "index",
    "sendfile", "tcp_nopush", "tcp_nodelay", "keepalive_timeout",
    "keepalive_requests", "client_max_body_size", "client_body_buffer_size",
    "client_body_temp_path", "proxy_temp_path", "fastcgi_temp_path",
    "uwsgi_temp_path", "scgi_temp_path", "output_buffers", "thread_pool",
    "access_log", "error_log", "log_format", "log_not_found", "autoindex",
    "gzip", "gzip_types", "gzip_min_length", "dav_methods", "dav_ext_methods",
    "ssl_certificate", "ssl_protocols", "ssl_ciphers",
    "ssl_prefer_server_ciphers", "ssl_verify_client", "ssl_verify_depth",
    "ssl_buffer_size", "ssl_session_cache", "ssl_session_timeout",
    "ssl_conf_command", "ssl_ecdh_curve", "ssl_dhparam", "ssl_trusted_certificate",
    "ssl_client_certificate", "ssl_crl", "resolver", "resolver_timeout",
    "limit_rate", "limit_conn", "limit_req", "expires", "etag", "charset",
    "merge_slashes", "server_tokens", "reset_timedout_connection",
    "send_timeout", "proxy_connect_timeout", "proxy_read_timeout",
    "proxy_send_timeout", "proxy_buffering", "proxy_request_buffering",
    "underscores_in_headers", "large_client_header_buffers",
    NULL
}
Definition at line 128 of file config_download.c.
Referenced by dashboard_keep_value().
dashboard_secret_directives
const char* const dashboard_secret_directives[] static
Definition at line 54 of file config_download.c.
Referenced by dashboard_name_is_secret().
dashboard_secret_exceptions
const char* const dashboard_secret_exceptions[] static
Initial value:
= {
    "brix_token_issuer",
    "brix_token_audience",
    "brix_token_jwks_refresh_interval",
    "brix_token_cache",
    "brix_webdav_token_issuer",
    "brix_webdav_token_audience",
    "brix_webdav_token_introspect_ttl",
    "brix_webdav_token_introspect_loc",
    "brix_webdav_token_introspect_fail_open",
    NULL
}
Definition at line 110 of file config_download.c.
Referenced by dashboard_name_is_secret().
dashboard_secret_name_substrings
const char* const dashboard_secret_name_substrings[] static
Initial value:
= {
    "secret", "passwd", "password", "passphrase", "keytab", "privatekey",
    "private_key", "accesskey", "access_key", "secretkey", "secret_key",
    "apikey", "api_key", "client_secret", "credential", "bearer", "macaroon",
    "hmac", "jwks",
    NULL
}
Definition at line 96 of file config_download.c.
Referenced by dashboard_name_is_secret().