nginx-xrootd: src/core/types/conf_structs.h File Reference
conf_structs.h File Reference
Data Structures
struct brix_ocsp_conf_t
struct brix_krb5_conf_t
struct brix_wt_conf_t
struct brix_cms_conf_t
struct brix_hc_conf_t
struct brix_node_caps_conf_t
struct brix_proxy_conf_t
struct brix_throttle_conf_t
struct brix_csi_conf_t
struct brix_acc_conf_t
struct brix_cache_advertise_conf_t
struct brix_cache_reaper_conf_t
struct brix_cache_include_regex_conf_t
Macros
#define BRIX_WT_MODE_SYNC 0
#define BRIX_WT_MODE_ASYNC 1
#define BRIX_WT_MODE_UNSET 255
#define BRIX_PROXY_AUTH_ANONYMOUS 0
#define BRIX_PROXY_AUTH_FORWARD 1
#define BRIX_PROXY_AUTH_SSS 2
#define BRIX_PROXY_AUTH_GSI
#define BRIX_PROXY_LOGIN_ANONYMOUS 0 /* default: "xrd" */
#define BRIX_PROXY_LOGIN_PASSTHROUGH 1 /* copy client's authenticated username */
#define BRIX_PROXY_LOGIN_FIXED 2 /* literal name from proxy.login_user_name */
Functions
static void brix_ocsp_conf_init (brix_ocsp_conf_t *c)
static void brix_krb5_conf_init (brix_krb5_conf_t *c)
static void brix_wt_conf_init (brix_wt_conf_t *c)
static void brix_cms_conf_init (brix_cms_conf_t *c)
static void brix_hc_conf_init (brix_hc_conf_t *c)
static void brix_node_caps_conf_init (brix_node_caps_conf_t *c)
static void brix_proxy_conf_init (brix_proxy_conf_t *c)
static void brix_csi_conf_init (brix_csi_conf_t *c)
static void brix_acc_conf_init (brix_acc_conf_t *c)
static void brix_cache_reaper_conf_init (brix_cache_reaper_conf_t *c)
static void brix_ocsp_conf_merge (brix_ocsp_conf_t *c, brix_ocsp_conf_t *p)
static void brix_node_caps_conf_merge (brix_node_caps_conf_t *c, brix_node_caps_conf_t *p)
static void brix_csi_conf_merge (brix_csi_conf_t *c, brix_csi_conf_t *p)
Macro Definition Documentation
BRIX_PROXY_AUTH_ANONYMOUS
#define BRIX_PROXY_AUTH_ANONYMOUS 0
Definition at line 139 of file conf_structs.h.
BRIX_PROXY_AUTH_FORWARD
#define BRIX_PROXY_AUTH_FORWARD 1
Definition at line 140 of file conf_structs.h.
BRIX_PROXY_AUTH_GSI
#define BRIX_PROXY_AUTH_GSI
Value:
                                          3   /* phase-4b: present the user's delegated
                                          * X.509 proxy to the upstream GSI auth */
Definition at line 142 of file conf_structs.h.
BRIX_PROXY_AUTH_SSS
#define BRIX_PROXY_AUTH_SSS 2
Definition at line 141 of file conf_structs.h.
BRIX_PROXY_LOGIN_ANONYMOUS
#define BRIX_PROXY_LOGIN_ANONYMOUS 0 /* default: "xrd" */
Definition at line 143 of file conf_structs.h.
BRIX_PROXY_LOGIN_FIXED
#define BRIX_PROXY_LOGIN_FIXED 2 /* literal name from proxy.login_user_name */
Definition at line 145 of file conf_structs.h.
BRIX_PROXY_LOGIN_PASSTHROUGH
#define BRIX_PROXY_LOGIN_PASSTHROUGH 1 /* copy client's authenticated username */
Definition at line 144 of file conf_structs.h.
BRIX_WT_MODE_ASYNC
#define BRIX_WT_MODE_ASYNC 1
Definition at line 65 of file conf_structs.h.
BRIX_WT_MODE_SYNC
#define BRIX_WT_MODE_SYNC 0
Definition at line 64 of file conf_structs.h.
BRIX_WT_MODE_UNSET
#define BRIX_WT_MODE_UNSET 255
Definition at line 66 of file conf_structs.h.
Function Documentation
brix_acc_conf_init()
static void brix_acc_conf_init (brix_acc_conf_t * c) inline static
Definition at line 345 of file conf_structs.h.
References c.
Referenced by brix_create_srv_security().
brix_cache_reaper_conf_init()
static void brix_cache_reaper_conf_init (brix_cache_reaper_conf_t * c) inline static
Definition at line 357 of file conf_structs.h.
References c.
Referenced by brix_create_srv_storage().
brix_cms_conf_init()
static void brix_cms_conf_init (brix_cms_conf_t * c) inline static
Definition at line 283 of file conf_structs.h.
References c.
Referenced by brix_create_srv_cluster().
brix_csi_conf_init()
static void brix_csi_conf_init (brix_csi_conf_t * c) inline static
Definition at line 336 of file conf_structs.h.
References c.
Referenced by brix_create_srv_security().
brix_csi_conf_merge()
static void brix_csi_conf_merge (brix_csi_conf_t * c, brix_csi_conf_t * p) inline static
Definition at line 392 of file conf_structs.h.
References brix_csi_conf_t::block, c, brix_csi_conf_t::enable, brix_csi_conf_t::require, and brix_csi_conf_t::trust_fs.
Referenced by brix_merge_srv_authtail().
brix_hc_conf_init()
static void brix_hc_conf_init (brix_hc_conf_t * c) inline static
Definition at line 296 of file conf_structs.h.
References c.
Referenced by brix_create_srv_cluster().
brix_krb5_conf_init()
static void brix_krb5_conf_init (brix_krb5_conf_t * c) inline static
Definition at line 269 of file conf_structs.h.
References c.
Referenced by brix_create_srv_security().
brix_node_caps_conf_init()
static void brix_node_caps_conf_init (brix_node_caps_conf_t * c) inline static
Definition at line 307 of file conf_structs.h.
References c.
Referenced by brix_create_srv_cluster().
brix_node_caps_conf_merge()
static void brix_node_caps_conf_merge (brix_node_caps_conf_t * c, brix_node_caps_conf_t * p) inline static
Definition at line 381 of file conf_structs.h.
References c, brix_node_caps_conf_t::collapse_redir, brix_node_caps_conf_t::collapse_redir_ttl, brix_node_caps_conf_t::metadata_only, brix_node_caps_conf_t::recover_writes, brix_node_caps_conf_t::supervisor, and brix_node_caps_conf_t::virtual_redirector.
Referenced by brix_merge_srv_cluster_sizing().
brix_ocsp_conf_init()
static void brix_ocsp_conf_init (brix_ocsp_conf_t * c) inline static
Definition at line 260 of file conf_structs.h.
References c.
Referenced by brix_create_srv_security().
brix_ocsp_conf_merge()
static void brix_ocsp_conf_merge (brix_ocsp_conf_t * c, brix_ocsp_conf_t * p) inline static
Definition at line 372 of file conf_structs.h.
References c, brix_ocsp_conf_t::enable, brix_ocsp_conf_t::require_nonce, brix_ocsp_conf_t::soft_fail, and brix_ocsp_conf_t::stapling.
Referenced by brix_merge_srv_net_fault().
brix_proxy_conf_init()
static void brix_proxy_conf_init (brix_proxy_conf_t * c) inline static
Definition at line 318 of file conf_structs.h.
References c.
Referenced by brix_create_srv_proxy_net().
brix_wt_conf_init()
static void brix_wt_conf_init (brix_wt_conf_t * c) inline static
Definition at line 275 of file conf_structs.h.
References BRIX_WT_MODE_UNSET, and c.
Referenced by brix_create_srv_storage().