nginx-xrootd: src/protocols/webdav/config_proxy.c File Reference
config_proxy.c File Reference
#include "webdav.h"
#include "auth/crypto/store_policy.h"
#include "core/compat/integrity_info.h"
#include "core/compat/tmp_path.h"
#include "auth/token/issuer_registry.h"
#include "proxy_internal.h"
#include "net/mirror/http_mirror.h"
#include "core/config/config.h"
#include "fs/path/path.h"
#include "core/config/root_prepare.h"
#include "core/config/http_rootfd.h"
#include "core/config/http_common.h"
#include "core/config/export_guard.h"
#include "core/compat/staged_file.h"
#include "fs/backend/sd.h"
#include "fs/vfs/vfs_backend_registry.h"
#include <openssl/x509.h>
#include <limits.h>
#include <sys/stat.h>
#include <unistd.h>
#include "core/compat/alloc_guard.h"
#include "core/config/credential_block.h"
#include "config_internal.h"
Macros
#define webdav_validate_path brix_validate_path
#define WEBDAV_PATH_REGULAR_FILE BRIX_PATH_REGULAR_FILE
#define WEBDAV_PATH_DIRECTORY BRIX_PATH_DIRECTORY
#define WEBDAV_PATH_FILE_OR_DIRECTORY BRIX_PATH_FILE_OR_DIRECTORY
Functions
char * webdav_merge_auth_token_conf (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *prev, ngx_http_brix_webdav_loc_conf_t *conf)
static char * webdav_validate_proxy_token (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
static char * webdav_setup_dynamic_proxy_pool (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *prev, ngx_http_brix_webdav_loc_conf_t *conf)
static void webdav_try_inherit_static_backends (ngx_http_brix_webdav_loc_conf_t *prev, ngx_http_brix_webdav_loc_conf_t *conf)
static char * webdav_build_static_proxy_backends (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *prev, ngx_http_brix_webdav_loc_conf_t *conf)
char * webdav_merge_upstream_conf (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *prev, ngx_http_brix_webdav_loc_conf_t *conf)
char * webdav_merge_mirror_and_summary (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *prev, ngx_http_brix_webdav_loc_conf_t *conf)
Macro Definition Documentation
WEBDAV_PATH_DIRECTORY
#define WEBDAV_PATH_DIRECTORY BRIX_PATH_DIRECTORY
Definition at line 47 of file config_proxy.c.
WEBDAV_PATH_FILE_OR_DIRECTORY
#define WEBDAV_PATH_FILE_OR_DIRECTORY BRIX_PATH_FILE_OR_DIRECTORY
Definition at line 48 of file config_proxy.c.
WEBDAV_PATH_REGULAR_FILE
#define WEBDAV_PATH_REGULAR_FILE BRIX_PATH_REGULAR_FILE
Definition at line 46 of file config_proxy.c.
webdav_validate_path
#define webdav_validate_path brix_validate_path
Definition at line 45 of file config_proxy.c.
Function Documentation
webdav_build_static_proxy_backends()
static char * webdav_build_static_proxy_backends (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * prev, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 152 of file config_proxy.c.
References ngx_http_brix_webdav_loc_conf_t::upstream_backends, ngx_http_brix_webdav_loc_conf_t::upstream_conf, webdav_proxy_build_backends(), webdav_try_inherit_static_backends(), and webdav_validate_proxy_token().
Referenced by webdav_merge_upstream_conf().
webdav_merge_auth_token_conf()
char * webdav_merge_auth_token_conf (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * prev, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 51 of file config_proxy.c.
References BRIX_AUTHZ_CAPABILITY, brix_jwks_load(), brix_jwks_register_cleanup(), BRIX_MAX_JWKS_KEYS, brix_token_registry_build(), ngx_http_brix_webdav_loc_conf_t::jwks_key_count, ngx_http_brix_webdav_loc_conf_t::jwks_keys, ngx_http_brix_webdav_loc_conf_t::token_config, ngx_http_brix_webdav_loc_conf_t::token_jwks, and ngx_http_brix_webdav_loc_conf_t::token_registry.
Referenced by ngx_http_brix_webdav_merge_loc_conf().
webdav_merge_mirror_and_summary()
char * webdav_merge_mirror_and_summary (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * prev, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 218 of file config_proxy.c.
References brix_http_mirror_setup(), BRIX_MIRROR_M_DEFAULT, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::enable, brix_mirror_conf_t::enabled, brix_mirror_conf_t::log_diverge, brix_mirror_conf_t::method_mask, ngx_http_brix_webdav_loc_conf_t::mirror, ngx_http_brix_webdav_loc_conf_t::mirror_upstream_conf, brix_mirror_conf_t::mirror_writes, brix_mirror_conf_t::sample_pct, brix_mirror_conf_t::strip_auth, brix_mirror_conf_t::targets, brix_mirror_conf_t::timeout_ms, brix_mirror_conf_t::token, webdav_log_endpoint_summary(), and webdav_summary_is_new().
Referenced by ngx_http_brix_webdav_merge_loc_conf().
webdav_merge_upstream_conf()
char * webdav_merge_upstream_conf (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * prev, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 184 of file config_proxy.c.
References ngx_http_brix_webdav_loc_conf_t::proxy_pool_enabled, ngx_http_brix_webdav_loc_conf_t::upstream_auth, ngx_http_brix_webdav_loc_conf_t::upstream_auth_token, ngx_http_brix_webdav_loc_conf_t::upstream_backends, ngx_http_brix_webdav_loc_conf_t::upstream_conf, ngx_http_brix_webdav_loc_conf_t::upstream_fail_timeout, ngx_http_brix_webdav_loc_conf_t::upstream_max_fails, ngx_http_brix_webdav_loc_conf_t::upstream_proxy, ngx_http_brix_webdav_loc_conf_t::upstream_url, webdav_build_static_proxy_backends(), WEBDAV_PROXY_AUTH_ANONYMOUS, and webdav_setup_dynamic_proxy_pool().
Referenced by ngx_http_brix_webdav_merge_loc_conf().
webdav_setup_dynamic_proxy_pool()
static char * webdav_setup_dynamic_proxy_pool (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * prev, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 111 of file config_proxy.c.
References webdav_proxy_pool_setup(), and webdav_validate_proxy_token().
Referenced by webdav_merge_upstream_conf().
webdav_try_inherit_static_backends()
static void webdav_try_inherit_static_backends (ngx_http_brix_webdav_loc_conf_t * prev, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 122 of file config_proxy.c.
References ngx_http_brix_webdav_loc_conf_t::upstream_backends, ngx_http_brix_webdav_loc_conf_t::upstream_conf, ngx_http_brix_webdav_loc_conf_t::upstream_host, ngx_http_brix_webdav_loc_conf_t::upstream_resolved, ngx_http_brix_webdav_loc_conf_t::upstream_ssl, ngx_http_brix_webdav_loc_conf_t::upstream_url, ngx_http_brix_webdav_loc_conf_t::upstream_url_base, and ngx_http_brix_webdav_loc_conf_t::upstream_urls.
Referenced by webdav_build_static_proxy_backends().
webdav_validate_proxy_token()
static char * webdav_validate_proxy_token (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 96 of file config_proxy.c.
References ngx_http_brix_webdav_loc_conf_t::upstream_auth, ngx_http_brix_webdav_loc_conf_t::upstream_auth_token, and WEBDAV_PROXY_AUTH_TOKEN.
Referenced by webdav_build_static_proxy_backends(), and webdav_setup_dynamic_proxy_pool().