nginx-xrootd: src/observability/dashboard/config_download_scrub.c File Reference
config_download_scrub.c File Reference
#include "dashboard_http.h"
#include "core/http/http_headers.h"
#include "core/compat/cstr.h"
#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>
#include "config_download_internal.h"
Functions
static u_char * dashboard_redact_region (u_char *vs, u_char *ve, u_char *end)
static u_char * dashboard_userinfo_at (u_char *auth, u_char *end, u_char **colon)
static u_char * dashboard_scrub_userinfo (u_char *s, u_char **endp)
static u_char * dashboard_query_value_end (u_char *vs, u_char *end)
static u_char * dashboard_scrub_query_param (u_char *kv, u_char *end)
u_char * dashboard_scrub_value_creds (u_char *p, u_char *end)
Variables
static const char *const dashboard_cred_query_keys []
Function Documentation
dashboard_query_value_end()
static u_char * dashboard_query_value_end (u_char * vs, u_char * end) static
Definition at line 104 of file config_download_scrub.c.
Referenced by dashboard_scrub_query_param().
dashboard_redact_region()
static u_char * dashboard_redact_region (u_char * vs, u_char * ve, u_char * end) static
Definition at line 39 of file config_download_scrub.c.
References DASHBOARD_REDACTED, and ngx_memcpy.
Referenced by dashboard_scrub_query_param(), and dashboard_scrub_userinfo().
dashboard_scrub_query_param()
static u_char * dashboard_scrub_query_param (u_char * kv, u_char * end) static
Definition at line 122 of file config_download_scrub.c.
References dashboard_cred_query_keys, dashboard_name_eq(), dashboard_query_value_end(), and dashboard_redact_region().
Referenced by dashboard_scrub_value_creds().
dashboard_scrub_userinfo()
static u_char * dashboard_scrub_userinfo (u_char * s, u_char ** endp) static
Definition at line 85 of file config_download_scrub.c.
References dashboard_redact_region(), dashboard_userinfo_at(), and s.
Referenced by dashboard_scrub_value_creds().
dashboard_scrub_value_creds()
u_char * dashboard_scrub_value_creds (u_char * p, u_char * end)
Definition at line 152 of file config_download_scrub.c.
References dashboard_scrub_query_param(), dashboard_scrub_userinfo(), and s.
Referenced by dashboard_emit_scrubbed().
dashboard_userinfo_at()
static u_char * dashboard_userinfo_at (u_char * auth, u_char * end, u_char ** colon) static
Definition at line 61 of file config_download_scrub.c.
Referenced by dashboard_scrub_userinfo().
Variable Documentation
dashboard_cred_query_keys
const char* const dashboard_cred_query_keys[] static
Initial value:
= {
    "token=", "access_token=", "secret=", "client_secret=", "password=",
    "passwd=", "apikey=", "api_key=", "key=", "sig=", "signature=",
    "x-amz-credential=", "x-amz-signature=", "x-amz-security-token=", NULL
}
Definition at line 26 of file config_download_scrub.c.
Referenced by dashboard_scrub_query_param().