nginx-xrootd: src/net/proxy/connect_upstream.c File Reference
connect_upstream.c File Reference
#include "proxy_internal.h"
#include "protocols/root/connection/netconnect.h"
#include <netdb.h>
#include <sys/socket.h>
Data Structures
struct pc_target_t
Functions
static size_t brix_proxy_build_bootstrap (u_char *buf, const char *username)
static ngx_int_t pc_pick_healthy_upstream (ngx_stream_brix_srv_conf_t *conf, ngx_uint_t *idx_out)
static ngx_int_t pc_select_endpoint (brix_proxy_ctx_t *proxy, ngx_connection_t *client_conn, ngx_stream_brix_srv_conf_t *conf, pc_target_t *tgt)
static ngx_int_t pc_resolve_target (brix_proxy_ctx_t *proxy, ngx_connection_t *client_conn, pc_target_t *tgt)
static void pc_resolve_login_user (brix_proxy_ctx_t *proxy, ngx_stream_brix_srv_conf_t *conf, char *user_out)
static ngx_connection_t * pc_open_socket (brix_proxy_ctx_t *proxy, ngx_connection_t *client_conn, ngx_stream_brix_srv_conf_t *conf, int fd)
static ngx_int_t pc_arm_events (brix_proxy_ctx_t *proxy, ngx_connection_t *client_conn, ngx_stream_brix_srv_conf_t *conf, ngx_connection_t *uconn, pc_target_t *tgt)
ngx_int_t brix_proxy_connect (brix_proxy_ctx_t *proxy, ngx_connection_t *client_conn, ngx_stream_brix_srv_conf_t *conf)
Variables
static ngx_atomic_t proxy_upstream_seq
static ngx_atomic_t proxy_upstream_rr
Function Documentation
brix_proxy_build_bootstrap()
static size_t brix_proxy_build_bootstrap (u_char * buf, const char * username) static
Definition at line 49 of file connect_upstream.c.
References xrdw_login_req_t::capver, xrdw_protocol_req_t::clientpv, kXR_login, kXR_protocol, kXR_PROTOCOLVERSION, kXR_ver005, ngx_memcpy, xrdw_login_req_t::pid, proxy_upstream_seq, ClientProtocolRequest::requestid, ClientLoginRequest::requestid, ROOTD_PQ, ClientProtocolRequest::streamid, ClientLoginRequest::streamid, xrdw_login_req_t::username, xrdw_login_req_pack(), and xrdw_protocol_req_pack().
Referenced by pc_open_socket().
brix_proxy_connect()
ngx_int_t brix_proxy_connect (brix_proxy_ctx_t * proxy, ngx_connection_t * client_conn, ngx_stream_brix_srv_conf_t * conf)
Definition at line 605 of file connect_upstream.c.
References BRIX_PROXY_AUTH_GSI, brix_proxy_gsi_connect_async(), pc_target_t::fd, pc_target_t::host, pc_arm_events(), pc_open_socket(), pc_resolve_target(), pc_select_endpoint(), and pc_target_t::port.
Referenced by brix_proxy_abort(), brix_proxy_dispatch(), and brix_proxy_relay_try_redirect().
pc_arm_events()
static ngx_int_t pc_arm_events (brix_proxy_ctx_t * proxy, ngx_connection_t * client_conn, ngx_stream_brix_srv_conf_t * conf, ngx_connection_t * uconn, pc_target_t * tgt) static
Definition at line 544 of file connect_upstream.c.
References pc_target_t::addr, pc_target_t::addrlen, brix_proxy_cleanup(), brix_proxy_flush(), BRIX_PROXY_METRIC_INC, BRIX_PROXY_UP_INC, pc_target_t::fd, pc_target_t::host, pc_target_t::port, XRD_PX_BOOTSTRAP, and XRD_PX_BS_HANDSHAKE.
Referenced by brix_proxy_connect().
pc_open_socket()
static ngx_connection_t * pc_open_socket (brix_proxy_ctx_t * proxy, ngx_connection_t * client_conn, ngx_stream_brix_srv_conf_t * conf, int fd) static
Definition at line 430 of file connect_upstream.c.
References brix_proxy_build_bootstrap(), brix_proxy_read_handler(), brix_proxy_write_handler(), pc_resolve_login_user(), XRD_HANDSHAKE_LEN, and XRD_PX_CONNECTING.
Referenced by brix_proxy_connect().
pc_pick_healthy_upstream()
static ngx_int_t pc_pick_healthy_upstream (ngx_stream_brix_srv_conf_t * conf, ngx_uint_t * idx_out) static
Definition at line 225 of file connect_upstream.c.
References BRIX_PROXY_FAIL_TIMEOUT, brix_proxy_up_status_t::checked, proxy_up_status, and proxy_upstream_rr.
Referenced by pc_select_endpoint().
pc_resolve_login_user()
static void pc_resolve_login_user (brix_proxy_ctx_t * proxy, ngx_stream_brix_srv_conf_t * conf, char * user_out) static
Definition at line 392 of file connect_upstream.c.
References BRIX_PROXY_LOGIN_FIXED, and BRIX_PROXY_LOGIN_PASSTHROUGH.
Referenced by pc_open_socket().
pc_resolve_target()
static ngx_int_t pc_resolve_target (brix_proxy_ctx_t * proxy, ngx_connection_t * client_conn, pc_target_t * tgt) static
Definition at line 352 of file connect_upstream.c.
References pc_target_t::addr, pc_target_t::addrlen, BRIX_AF_AUTO, BRIX_PROXY_METRIC_INC, BRIX_PROXY_UP_INC, brix_resolve_connect_socket(), BRIX_RESOLVE_ERR_DNS, BRIX_RESOLVE_OK, pc_target_t::fd, pc_target_t::host, and pc_target_t::port.
Referenced by brix_proxy_connect().
pc_select_endpoint()
static ngx_int_t pc_select_endpoint (brix_proxy_ctx_t * proxy, ngx_connection_t * client_conn, ngx_stream_brix_srv_conf_t * conf, pc_target_t * tgt) static
Definition at line 278 of file connect_upstream.c.
References BRIX_PROXY_AUTH_GSI, brix_proxy_dispatch_pending(), brix_proxy_pool_get(), brix_schedule_read_resume(), brix_proxy_upstream_t::host, pc_target_t::host, pc_pick_healthy_upstream(), pc_target_t::port, XRD_PX_IDLE, and XRD_ST_REQ_HEADER.
Referenced by brix_proxy_connect().
Variable Documentation
proxy_upstream_rr
ngx_atomic_t proxy_upstream_rr static
Definition at line 37 of file connect_upstream.c.
Referenced by pc_pick_healthy_upstream().
proxy_upstream_seq
ngx_atomic_t proxy_upstream_seq static
Definition at line 34 of file connect_upstream.c.
Referenced by brix_proxy_build_bootstrap().