nginx-xrootd: src/net/proxy/connect_lifecycle.c File Reference
connect_lifecycle.c File Reference
#include "proxy_internal.h"
#include <netdb.h>
#include <sys/socket.h>
Functions
ngx_int_t brix_proxy_flush (brix_proxy_ctx_t *proxy)
void brix_proxy_abort (brix_proxy_ctx_t *proxy, const char *reason)
static void brix_proxy_cleanup_audit_handles (brix_proxy_ctx_t *proxy)
static void brix_proxy_cleanup_free_buffers (brix_proxy_ctx_t *proxy)
static void brix_proxy_cleanup_timers (brix_proxy_ctx_t *proxy)
static void brix_proxy_cleanup_redirect (brix_proxy_ctx_t *proxy)
static void brix_proxy_cleanup_splice (brix_proxy_ctx_t *proxy)
static void brix_proxy_cleanup_conn (brix_proxy_ctx_t *proxy)
void brix_proxy_cleanup (brix_proxy_ctx_t *proxy)
Function Documentation
brix_proxy_abort()
void brix_proxy_abort (brix_proxy_ctx_t * proxy, const char * reason)
Definition at line 46 of file connect_lifecycle.c.
References BRIX_MAX_FILES, brix_proxy_cleanup(), brix_proxy_connect(), BRIX_PROXY_FH_FREE, BRIX_PROXY_METRIC_INC, BRIX_PROXY_UP_INC, brix_proxy_up_mark_failed(), brix_schedule_read_resume(), brix_send_error(), c, brix_ctx_t::destroyed, kXR_IOError, brix_ctx_t::proxy, brix_ctx_t::proxy_fail_count, brix_ctx_t::state, XRD_PX_BS_HANDSHAKE, XRD_PX_CONNECTING, XRD_PX_IDLE, and XRD_ST_REQ_HEADER.
Referenced by brix_proxy_build_relay_buffer(), brix_proxy_check_connect(), brix_proxy_dispatch_saved_read(), brix_proxy_flush_buffered(), brix_proxy_handle_bootstrap(), brix_proxy_lazy_open(), brix_proxy_pending_flush(), brix_proxy_queue_and_flush(), brix_proxy_read_handler(), brix_proxy_wait_handler(), brix_proxy_write_complete(), brix_proxy_write_handler(), proxy_bs_auth_error(), proxy_bs_check_protocol_reply(), proxy_gsi_login_done(), proxy_read_arm(), proxy_read_dispatch(), proxy_read_expand_status(), proxy_read_fill_body(), proxy_read_fill_hdr(), and proxy_read_hdr_complete().
brix_proxy_cleanup()
void brix_proxy_cleanup (brix_proxy_ctx_t * proxy)
Definition at line 332 of file connect_lifecycle.c.
References brix_proxy_cleanup_audit_handles(), brix_proxy_cleanup_conn(), brix_proxy_cleanup_free_buffers(), brix_proxy_cleanup_redirect(), brix_proxy_cleanup_splice(), and brix_proxy_cleanup_timers().
Referenced by brix_on_disconnect(), brix_proxy_abort(), brix_proxy_read_handler(), brix_proxy_wait_handler(), brix_proxy_write_handler(), and pc_arm_events().
brix_proxy_cleanup_audit_handles()
static void brix_proxy_cleanup_audit_handles (brix_proxy_ctx_t * proxy) static
Definition at line 159 of file connect_lifecycle.c.
References BRIX_MAX_FILES, BRIX_PROXY_FH_FREE, BRIX_PROXY_METRIC_INC, BRIX_PROXY_UP_INC, and proxy_write_audit().
Referenced by brix_proxy_cleanup().
brix_proxy_cleanup_conn()
static void brix_proxy_cleanup_conn (brix_proxy_ctx_t * proxy) static
Definition at line 293 of file connect_lifecycle.c.
References BRIX_MAX_FILES, BRIX_PROXY_FH_FREE, brix_proxy_pool_put(), and XRD_PX_IDLE.
Referenced by brix_proxy_cleanup().
brix_proxy_cleanup_free_buffers()
static void brix_proxy_cleanup_free_buffers (brix_proxy_ctx_t * proxy) static
Definition at line 194 of file connect_lifecycle.c.
References brix_proxy_wbuf_release().
Referenced by brix_proxy_cleanup().
brix_proxy_cleanup_redirect()
static void brix_proxy_cleanup_redirect (brix_proxy_ctx_t * proxy) static
Definition at line 245 of file connect_lifecycle.c.
Referenced by brix_proxy_cleanup().
brix_proxy_cleanup_splice()
static void brix_proxy_cleanup_splice (brix_proxy_ctx_t * proxy) static
Definition at line 266 of file connect_lifecycle.c.
References close().
Referenced by brix_proxy_cleanup().
brix_proxy_cleanup_timers()
static void brix_proxy_cleanup_timers (brix_proxy_ctx_t * proxy) static
Definition at line 224 of file connect_lifecycle.c.
Referenced by brix_proxy_cleanup().
brix_proxy_flush()
ngx_int_t brix_proxy_flush (brix_proxy_ctx_t * proxy)
Definition at line 20 of file connect_lifecycle.c.
Referenced by brix_proxy_dispatch_saved_read(), brix_proxy_flush_buffered(), brix_proxy_lazy_open(), brix_proxy_pending_flush(), brix_proxy_queue_and_flush(), brix_proxy_wait_handler(), pc_arm_events(), and proxy_bs_queue_auth_frame().