nginx-xrootd: src/net/proxy/connect_upstream_bootstrap.c File Reference
connect_upstream_bootstrap.c File Reference
#include "proxy_internal.h"
Functions
size_t brix_proxy_build_bootstrap (u_char *buf, const char *username)
Variables
static ngx_atomic_t proxy_upstream_seq
Function Documentation
brix_proxy_build_bootstrap()
size_t brix_proxy_build_bootstrap (u_char * buf, const char * username)
Definition at line 34 of file connect_upstream_bootstrap.c.
References xrdw_login_req_t::capver, xrdw_protocol_req_t::clientpv, kXR_login, kXR_protocol, kXR_PROTOCOLVERSION, kXR_ver005, ngx_memcpy, xrdw_login_req_t::pid, proxy_upstream_seq, ClientProtocolRequest::requestid, ClientLoginRequest::requestid, ROOTD_PQ, ClientProtocolRequest::streamid, ClientLoginRequest::streamid, xrdw_login_req_t::username, xrdw_login_req_pack(), and xrdw_protocol_req_pack().
Referenced by pc_open_socket().
Variable Documentation
proxy_upstream_seq
ngx_atomic_t proxy_upstream_seq static
Definition at line 22 of file connect_upstream_bootstrap.c.
Referenced by brix_proxy_build_bootstrap().