nginx-xrootd: client/lib/net/conn.c File Reference
conn.c File Reference
#include "brix.h"
#include "protocols/root/protocol/frame_hdr.h"
#include "protocols/root/protocol/bootstrap_pack.h"
#include "core/compat/host_format.h"
#include "core/compat/crypto.h"
#include <pthread.h>
#include <arpa/inet.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <pwd.h>
#include <openssl/crypto.h>
Macros
#define XRDC_DEFAULT_TIMEOUT_MS 30000
#define XRDC_GRID_CA_DIR "/etc/grid-security/certificates"
Functions
const char * brix_resolve_ca_dir (const char *opt_ca_dir)
static void fill_username (char out[9])
static int recv_raw (brix_conn *c, uint16_t *sid, uint16_t *status, uint8_t *body, uint32_t bodycap, uint32_t *blen, brix_status *st)
static int do_handshake (brix_conn *c, uint16_t proto_sid, int want_tls, brix_status *st)
static int do_login (brix_conn *c, const brix_opts *o, brix_status *st)
static int brix_bringup_ex (brix_conn *c, int want_login, brix_status *st)
static int brix_bringup (brix_conn *c, brix_status *st)
int brix_bind (brix_conn *sec, const brix_conn *primary, brix_status *st)
static void brix_crypto_init_void (void)
static void brix_crypto_once (void)
int brix_connect (brix_conn *c, const brix_url *u, const brix_opts *o, brix_status *st)
int brix_connect_no_login (brix_conn *c, const brix_url *u, const brix_opts *o, brix_status *st)
int brix_reconnect (brix_conn *c, const char *host, int port, brix_status *st)
static int sessid_is_zero (const uint8_t *s)
void brix_close (brix_conn *c)
static void explain_roles (unsigned f, FILE *out)
static void explain_caps (unsigned f, FILE *out)
static void explain_tls (brix_conn *c, unsigned f, FILE *out)
static void explain_env_credentials (FILE *out)
static void explain_session_id (brix_conn *c, FILE *out)
void brix_explain_conn (brix_conn *c, const brix_opts *opts, FILE *out)
Macro Definition Documentation
XRDC_DEFAULT_TIMEOUT_MS
#define XRDC_DEFAULT_TIMEOUT_MS 30000
Definition at line 35 of file conn.c.
XRDC_GRID_CA_DIR
#define XRDC_GRID_CA_DIR "/etc/grid-security/certificates"
Definition at line 41 of file conn.c.
Function Documentation
brix_bind()
int brix_bind (brix_conn * sec, const brix_conn * primary, brix_status * st)
Definition at line 355 of file conn.c.
References brix_bringup_ex(), brix_recv(), brix_send(), BRIX_SESSION_ID_LEN, brix_tls_free(), close(), brix_io::fd, brix_conn::host, brix_conn::io, kXR_bind, brix_conn::opts, brix_conn::port, ClientBindRequest::requestid, xrdw_sessid_req_t::sessid, brix_conn::sessid, brix_io::timeout_ms, brix_conn::tls_strict, brix_conn::want_tls, and xrdw_sessid_req_pack().
Referenced by brix_streams_open().
brix_bringup()
static int brix_bringup (brix_conn * c, brix_status * st) static
Definition at line 349 of file conn.c.
References brix_bringup_ex(), and c.
Referenced by brix_connect(), and brix_reconnect().
brix_bringup_ex()
static int brix_bringup_ex (brix_conn * c, int want_login, brix_status * st) static
Definition at line 274 of file conn.c.
References brix_close(), brix_mono_ns(), brix_resolve_ca_dir(), brix_status_set(), brix_tcp_connect(), brix_tls_upgrade(), brix_tmo_connect_ms(), brix_tmo_io_ms(), c, do_handshake(), do_login(), kXR_gotoTLS, kXR_haveTLS, and XRDC_EAUTH.
Referenced by brix_bind(), brix_bringup(), and brix_connect_no_login().
brix_close()
void brix_close (brix_conn * c)
Definition at line 539 of file conn.c.
References brix_capture_close(), brix_send(), BRIX_SESSION_ID_LEN, brix_status_clear(), brix_timing_report(), brix_tls_free(), c, close(), kXR_endsess, xrdw_sessid_req_t::sessid, sessid_is_zero(), XRD_REQUEST_HDR_LEN, and xrdw_sessid_req_pack().
Referenced by battery_root(), bench_run(), brix_bringup_ex(), brix_capture_playback(), brix_cli_cksum_main(), brix_glob(), brix_pool_checkin(), brix_pool_destroy(), brix_qstats_main(), brix_wait41_main(), brix_xrdckcheck_main(), chk_probe_posc(), cktree_run_remote(), cmd_bench(), cmd_verify(), compare_setup(), copy_download(), copy_recursive(), copy_remote_to_block(), copy_unzip(), copy_zip_store_remote(), dest_is_dir(), do_bench(), do_check(), do_compare(), do_compare_davs(), do_map(), do_topology(), doctor_cms(), doctor_one(), dx_authz_anon(), dx_authz_expired(), dx_authz_forged(), dx_authz_scope(), entry_cksum(), entry_meta(), main(), mb_thread(), mgr_attach_eager(), mgr_connect_eager(), mgr_ensure_slot(), mgr_free(), probe_holder(), probe_p1_path_escape(), probe_p2_bad_opcode(), probe_p3_oversized_dlen(), probe_p4_oob_read(), probe_p5_partial_frame(), probe_server_survives(), r2r_teardown(), remove_source_entry(), resilient_setup(), run_root_endpoint(), tpc_teardown(), upload_stream_body(), watch_probe_once(), xfs_handle_free(), xrd_caps(), xrd_certinfo(), xrd_clockskew_root(), xrd_doctor_probe(), xrd_ping(), xrd_whoami(), and xrdprep_run().
brix_connect()
int brix_connect (brix_conn * c, const brix_url * u, const brix_opts * o, brix_status * st)
Definition at line 418 of file conn.c.
References brix_bringup(), brix_capture_meta(), brix_capture_open(), brix_crypto_once(), brix_format_host_port(), BRIX_SESSION_ID_LEN, brix_status_set(), brix_tmo_io_ms(), c, brix_url::host, brix_url::port, brix_url::scheme, brix_url::single_slash_path, brix_opts::verify_host, XRDC_EUSAGE, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by battery_root(), bench_run(), brix_capture_playback(), brix_cli_cksum_main(), brix_connect_resilient(), brix_glob(), brix_wait41_main(), chk_probe_posc(), ckcheck_connect(), cktree_run_remote(), compare_setup(), copy_recursive(), copy_remote_to_remote(), copy_unzip(), copy_zip_store_remote(), dest_is_dir(), do_bench(), do_check(), do_compare_davs(), do_topology(), doctor_cms(), doctor_one(), dx_connect_as(), ensure_conn(), entry_cksum(), entry_meta(), main(), mb_thread(), mgr_connect_worker(), mgr_ensure_slot(), pool_slot_connect(), probe_holder(), probe_open(), remove_source_entry(), resilient_setup(), storascan_connect(), tpc_run_rendezvous(), tpc_setup_source(), watch_probe_once(), xfs_handle_new(), xrd_caps(), xrd_clockskew_root(), xrd_doctor_probe(), xrd_ping(), and xrd_whoami().
brix_connect_no_login()
int brix_connect_no_login (brix_conn * c, const brix_url * u, const brix_opts * o, brix_status * st)
Definition at line 480 of file conn.c.
References brix_bringup_ex(), brix_crypto_once(), brix_status_set(), brix_tmo_io_ms(), c, brix_url::host, brix_url::port, brix_url::scheme, brix_url::single_slash_path, brix_opts::verify_host, XRDC_EUSAGE, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by xrd_certinfo(), and xrd_doctor_probe().
brix_crypto_init_void()
static void brix_crypto_init_void (void) static
Definition at line 405 of file conn.c.
References brix_crypto_init().
Referenced by brix_crypto_once().
brix_crypto_once()
static void brix_crypto_once (void) static
Definition at line 411 of file conn.c.
References brix_crypto_init_void().
Referenced by brix_connect(), and brix_connect_no_login().
brix_explain_conn()
void brix_explain_conn (brix_conn * c, const brix_opts * opts, FILE * out)
Definition at line 724 of file conn.c.
References brix_auth_explain(), c, explain_caps(), explain_env_credentials(), explain_roles(), explain_session_id(), and explain_tls().
Referenced by do_check(), do_explain(), and main().
brix_reconnect()
int brix_reconnect (brix_conn * c, const char * host, int port, brix_status * st)
Definition at line 510 of file conn.c.
References brix_bringup(), brix_tls_free(), c, and close().
Referenced by brix_reconnect_home(), csctx_reopen_home(), follow_redirect(), pump_remote_reopen(), pump_sink_reopen(), and rc_worker_main().
brix_resolve_ca_dir()
const char * brix_resolve_ca_dir (const char * opt_ca_dir)
Definition at line 53 of file conn.c.
References access(), and XRDC_GRID_CA_DIR.
Referenced by aio_web_mount(), battery_s3(), battery_web(), brix_bringup_ex(), and run_web_endpoint().
do_handshake()
static int do_handshake (brix_conn * c, uint16_t proto_sid, int want_tls, brix_status * st) static
Definition at line 128 of file conn.c.
References brix_status_set(), brix_write_full(), c, kXR_ableTLS, kXR_ok, kXR_secreqs, kXR_wantTLS, recv_raw(), xrd_get_u32_be(), XRD_HANDSHAKE_LEN, xrd_pack_handshake(), xrd_pack_protocol_request(), XRD_REQUEST_HDR_LEN, and XRDC_EPROTO.
Referenced by brix_bringup_ex().
do_login()
static int do_login (brix_conn * c, const brix_opts * o, brix_status * st) static
Definition at line 213 of file conn.c.
References brix_authenticate(), brix_recv(), brix_send(), BRIX_SESSION_ID_LEN, brix_status_set(), c, fill_username(), kXR_asyncap, kXR_ok, kXR_ver005, xrd_pack_login_request(), and XRDC_EPROTO.
Referenced by brix_bringup_ex().
explain_caps()
static void explain_caps (unsigned f, FILE * out) static
Definition at line 619 of file conn.c.
References kXR_gotoTLS, kXR_haveTLS, kXR_suppgrw, and kXR_supposc.
Referenced by brix_explain_conn().
explain_env_credentials()
static void explain_env_credentials (FILE * out) static
Definition at line 673 of file conn.c.
References brix_gsi_cert_explain(), brix_token_discover(), and brix_token_explain().
Referenced by brix_explain_conn().
explain_roles()
static void explain_roles (unsigned f, FILE * out) static
Definition at line 598 of file conn.c.
References kXR_attrProxy, kXR_isManager, and kXR_isServer.
Referenced by brix_explain_conn().
explain_session_id()
static void explain_session_id (brix_conn * c, FILE * out) static
Definition at line 701 of file conn.c.
References c.
Referenced by brix_explain_conn().
explain_tls()
static void explain_tls (brix_conn * c, unsigned f, FILE * out) static
Definition at line 643 of file conn.c.
References brix_tls_info(), c, and kXR_gotoTLS.
Referenced by brix_explain_conn().
fill_username()
static void fill_username (char out[9]) static
Definition at line 74 of file conn.c.
References name.
Referenced by do_login().
recv_raw()
static int recv_raw (brix_conn * c, uint16_t * sid, uint16_t * status, uint8_t * body, uint32_t bodycap, uint32_t * blen, brix_status * st) static
Definition at line 101 of file conn.c.
References brix_read_full(), brix_status_set(), brix_trace_frame(), c, xrd_resp_hdr_unpack(), XRD_RESPONSE_HDR_LEN, and XRDC_EPROTO.
Referenced by do_handshake().
sessid_is_zero()
static int sessid_is_zero (const uint8_t * s) static
Definition at line 527 of file conn.c.
References BRIX_SESSION_ID_LEN, and s.
Referenced by brix_close().