nginx-xrootd: src/protocols/root/response/control.c File Reference
control.c File Reference
#include "core/ngx_brix_module.h"
#include "core/compat/host_format.h"
#include "core/compat/alloc_guard.h"
Functions
ngx_int_t brix_send_redirect (brix_ctx_t *ctx, ngx_connection_t *c, const char *host, uint16_t port)
ngx_int_t brix_send_redirect_tpc (brix_ctx_t *ctx, ngx_connection_t *c, const char *host, uint16_t port, const char *tpc_key)
ngx_int_t brix_send_wait (brix_ctx_t *ctx, ngx_connection_t *c, uint32_t seconds)
ngx_int_t brix_send_waitresp (brix_ctx_t *ctx, ngx_connection_t *c)
Function Documentation
brix_send_redirect()
ngx_int_t brix_send_redirect (brix_ctx_t * ctx, ngx_connection_t * c, const char * host, uint16_t port)
Definition at line 10 of file control.c.
References brix_build_resp_hdr(), brix_format_host(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), c, brix_ctx_recv_t::cur_streamid, kXR_redirect, ngx_memcpy, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_cache_fill_done(), brix_dirlist_check_redirect(), brix_qcksum_manager_bounce(), brix_qcksum_open(), brix_send_redirect_tpc(), cms_wake_pending_session(), locate_try_manager(), locate_try_manager_map(), manager_redirect_mutation(), and stat_manager_route().
brix_send_redirect_tpc()
ngx_int_t brix_send_redirect_tpc (brix_ctx_t * ctx, ngx_connection_t * c, const char * host, uint16_t port, const char * tpc_key)
Definition at line 51 of file control.c.
References brix_build_resp_hdr(), brix_format_host(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), brix_send_redirect(), c, brix_ctx_recv_t::cur_streamid, kXR_redirect, ngx_memcpy, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by tpc_handle_dest().
brix_send_wait()
ngx_int_t brix_send_wait (brix_ctx_t * ctx, ngx_connection_t * c, uint32_t seconds)
Definition at line 96 of file control.c.
References brix_build_resp_hdr(), brix_queue_response(), c, brix_ctx_recv_t::cur_streamid, kXR_wait, ngx_memcpy, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_handle_readv(), brix_open_map_open_error(), brix_open_residency_gate(), brix_open_stage_backpressure(), brix_recv_pre_loop(), brix_tpc_start_pull(), gsi_auth_step_certreq(), locate_check_data_server(), read_serve_buffered(), read_serve_windowed(), rl_enforce_bw_rate(), rl_enforce_conc(), rl_enforce_req_rate(), and stat_query_path().
brix_send_waitresp()
ngx_int_t brix_send_waitresp (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 124 of file control.c.
References brix_build_resp_hdr(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), c, brix_ctx_recv_t::cur_streamid, kXR_waitresp, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_open_residency_gate(), brix_upstream_forward_response(), and ssi_write_maybe_dispatch().