nginx-xrootd: client/lib/xfer/copy_recursive.c File Reference
copy_recursive.c File Reference
#include "copy_internal.h"
Data Structures
struct web_dl_io
Functions
static int local_mkdirs (const char *lpath, mode_t mode)
static int dirent_is_dot (const char *name)
static int rel_join (const char *rel, const char *name, char *out, size_t outsz)
static int path_join (const char *dir, const char *name, char *out, size_t outsz)
static int sync_cksum_match (brix_conn *c, const char *rpath, const char *lpath, const brix_copy_opts *o)
static int local_rmtree (const char *path)
static int name_in_ents (const brix_dirent *ents, size_t nents, const char *name)
static void mirror_local_remove (const char *lchild, const brix_copy_opts *o)
static void mirror_delete_local (const char *lpath, const brix_dirent *ents, size_t nents, const char *rel, const brix_copy_opts *o)
static int remote_entry_is_dir (brix_conn *c, const brix_dirent *e, const char *rchild, int *is_dir)
static void mirror_remote_remove (brix_conn *c, const char *rchild, int is_dir, const brix_copy_opts *o)
static void mirror_delete_remote (brix_conn *c, const char *rpath, const char *lpath, const char *rel, const brix_copy_opts *o)
static int dl_sync_skip (const copy_walk_ctx *w, const brix_dirent *e, const char *rc, const char *lc)
static int tree_dl_file (const copy_walk_ctx *w, const brix_dirent *e, const char *relc, const char *rc, const char *lc)
static int tree_dl_entry (const copy_walk_ctx *w, const brix_dirent *e)
int copy_tree_download (const copy_walk_ctx *w)
static int ul_sync_skip (const copy_walk_ctx *w, const char *rc, const char *lc, const struct stat *sb)
static int tree_ul_file (const copy_walk_ctx *w, const char *relc, const char *lc, const char *rc, const struct stat *sb)
static int tree_ul_entry (const copy_walk_ctx *w, const char *name)
int copy_tree_upload (const copy_walk_ctx *w)
int recursive_dest_root (const char *dstdir, const char *srcpath, char *out, size_t outsz)
int copy_recursive (const copy_recurse_req *rq, brix_status *st)
static void s3_resolve_keys (const brix_copy_opts *o, const brix_opts *co, const char **ak, const char **sk, brix_status *st)
static int auth_hdr_s3 (const web_auth_ctx *a, char *hdrs, size_t hdrsz)
static int auth_hdr_bearer (const brix_copy_opts *o, const brix_opts *co, char *hdrs, size_t hdrsz, brix_status *st)
int web_auth_headers (const web_auth_ctx *a, char *hdrs, size_t hdrsz)
static int web_dl_fetch (const brix_weburl *su, const brix_opts *co, const char *hdrs, web_dl_io *io, brix_status *st)
int copy_web_download (const web_dl_req *rq, brix_status *st)
Function Documentation
auth_hdr_bearer()
static int auth_hdr_bearer (const brix_copy_opts * o, const brix_opts * co, char * hdrs, size_t hdrsz, brix_status * st) static
Definition at line 860 of file copy_recursive.c.
References brix_copy_opts::bearer, brix_cred_acquire(), brix_status_clear(), brix_status_set(), brix_opts::cred, tok, brix_cred_view::token, XRDC_CRED_BEARER, and XRDC_EUSAGE.
Referenced by web_auth_headers().
auth_hdr_s3()
static int auth_hdr_s3 (const web_auth_ctx * a, char * hdrs, size_t hdrsz) static
Definition at line 816 of file copy_recursive.c.
References brix_format_host_port(), brix_s3_sign_v4(), brix_status_set(), web_auth_ctx::co, host, brix_weburl::host, web_auth_ctx::method, web_auth_ctx::o, brix_weburl::path, brix_weburl::port, brix_copy_opts::s3_region, s3_resolve_keys(), web_auth_ctx::st, web_auth_ctx::u, XRDC_EAUTH, and XRDC_EUSAGE.
Referenced by web_auth_headers().
copy_recursive()
int copy_recursive (const copy_recurse_req * rq, brix_status * st)
Definition at line 730 of file copy_recursive.c.
References brix_close(), brix_connect(), brix_rmdir(), brix_status_clear(), brix_status_set(), c, copy_recurse_req::co, copy_tree_download(), copy_tree_upload(), copy_recurse_req::download, brix_copy_opts::dry_run, copy_recurse_req::du, copy_recurse_req::o, brix_url::path, recursive_dest_root(), brix_copy_opts::remove_source, copy_recurse_req::su, XRDC_EUSAGE, and XRDC_PATH_MAX.
Referenced by brix_copy_dispatch_recursive().
copy_tree_download()
int copy_tree_download (const copy_walk_ctx * w)
Definition at line 500 of file copy_recursive.c.
References brix_dirlist(), brix_status_set(), copy_walk_ctx::c, brix_copy_opts::dry_run, local_mkdirs(), copy_walk_ctx::lpath, mirror_delete_local(), copy_walk_ctx::o, copy_walk_ctx::rel, copy_walk_ctx::rpath, copy_walk_ctx::st, brix_copy_opts::sync_delete, tree_dl_entry(), and XRDC_ESOCK.
Referenced by copy_recursive(), and tree_dl_entry().
copy_tree_upload()
int copy_tree_upload (const copy_walk_ctx * w)
Definition at line 651 of file copy_recursive.c.
References brix_mkdir(), brix_status_clear(), brix_status_set(), copy_walk_ctx::c, brix_copy_opts::dry_run, copy_walk_ctx::lpath, mirror_delete_remote(), copy_walk_ctx::o, copy_walk_ctx::rel, copy_walk_ctx::rpath, copy_walk_ctx::st, brix_copy_opts::sync_delete, tree_ul_entry(), and XRDC_ESOCK.
Referenced by copy_recursive(), and tree_ul_entry().
copy_web_download()
int copy_web_download (const web_dl_req * rq, brix_status * st)
Definition at line 932 of file copy_recursive.c.
References access(), atomic_dest_finish(), web_dl_io::blen, brix_status_set(), close(), web_dl_req::co, web_dl_req::du, brix_copy_opts::force, web_dl_req::o, open_download_temp(), web_dl_io::outfd, brix_url::path, brix_copy_opts::silent, web_dl_io::status, web_dl_req::su, web_dl_req::to_stdout, web_auth_headers(), web_dl_fetch(), XRDC_EUSAGE, and XRDC_PATH_MAX.
Referenced by copy_web().
dirent_is_dot()
static int dirent_is_dot (const char * name) static
Definition at line 51 of file copy_recursive.c.
References name.
Referenced by local_rmtree(), mirror_delete_local(), mirror_delete_remote(), tree_dl_entry(), and tree_ul_entry().
dl_sync_skip()
static int dl_sync_skip (const copy_walk_ctx * w, const brix_dirent * e, const char * rc, const char * lc) static
Definition at line 384 of file copy_recursive.c.
References brix_sync_should_skip(), copy_walk_ctx::c, brix_statinfo::flags, brix_dirent::have_stat, kXR_other, brix_statinfo::mtime, copy_walk_ctx::o, brix_statinfo::size, brix_dirent::st, stat(), brix_copy_opts::sync, sync_cksum_match(), brix_copy_opts::sync_cmp, and XRDC_SYNC_CKSUM.
Referenced by tree_dl_file().
local_mkdirs()
static int local_mkdirs (const char * lpath, mode_t mode) static
Definition at line 19 of file copy_recursive.c.
References XRDC_PATH_MAX.
Referenced by copy_tree_download().
local_rmtree()
static int local_rmtree (const char * path) static
Definition at line 131 of file copy_recursive.c.
References dirent_is_dot(), local_rmtree(), lstat(), path_join(), stat(), and XRDC_PATH_MAX.
Referenced by local_rmtree(), and mirror_local_remove().
mirror_delete_local()
static void mirror_delete_local (const char * lpath, const brix_dirent * ents, size_t nents, const char * rel, const brix_copy_opts * o) static
Definition at line 216 of file copy_recursive.c.
References brix_copy_filter_match(), dirent_is_dot(), mirror_local_remove(), name_in_ents(), path_join(), rel_join(), and XRDC_PATH_MAX.
Referenced by copy_tree_download().
mirror_delete_remote()
static void mirror_delete_remote (brix_conn * c, const char * rpath, const char * lpath, const char * rel, const brix_copy_opts * o) static
Definition at line 329 of file copy_recursive.c.
References brix_copy_filter_match(), brix_dirlist(), brix_status_clear(), c, dirent_is_dot(), lstat(), mirror_remote_remove(), brix_status::msg, name, path_join(), rel_join(), remote_entry_is_dir(), stat(), and XRDC_PATH_MAX.
Referenced by copy_tree_upload().
mirror_local_remove()
static void mirror_local_remove (const char * lchild, const brix_copy_opts * o) static
Definition at line 184 of file copy_recursive.c.
References brix_copy_opts::dry_run, local_rmtree(), lstat(), and stat().
Referenced by mirror_delete_local().
mirror_remote_remove()
static void mirror_remote_remove (brix_conn * c, const char * rchild, int is_dir, const brix_copy_opts * o) static
Definition at line 289 of file copy_recursive.c.
References brix_rm(), brix_rmtree(), brix_status_clear(), c, brix_copy_opts::dry_run, and brix_status::msg.
Referenced by mirror_delete_remote().
name_in_ents()
static int name_in_ents (const brix_dirent * ents, size_t nents, const char * name) static
Definition at line 164 of file copy_recursive.c.
References name.
Referenced by mirror_delete_local().
path_join()
static int path_join (const char * dir, const char * name, char * out, size_t outsz) static
Definition at line 73 of file copy_recursive.c.
References name.
Referenced by local_rmtree(), mirror_delete_local(), mirror_delete_remote(), tree_dl_entry(), and tree_ul_entry().
recursive_dest_root()
int recursive_dest_root (const char * dstdir, const char * srcpath, char * out, size_t outsz)
Definition at line 699 of file copy_recursive.c.
Referenced by copy_recursive().
rel_join()
static int rel_join (const char * rel, const char * name, char * out, size_t outsz) static
Definition at line 63 of file copy_recursive.c.
References name.
Referenced by mirror_delete_local(), mirror_delete_remote(), tree_dl_entry(), and tree_ul_entry().
remote_entry_is_dir()
static int remote_entry_is_dir (brix_conn * c, const brix_dirent * e, const char * rchild, int * is_dir) static
Definition at line 262 of file copy_recursive.c.
References brix_stat(), brix_status_clear(), c, brix_statinfo::flags, brix_dirent::have_stat, kXR_isDir, and brix_dirent::st.
Referenced by mirror_delete_remote().
s3_resolve_keys()
static void s3_resolve_keys (const brix_copy_opts * o, const brix_opts * co, const char ** ak, const char ** sk, brix_status * st) static
Definition at line 785 of file copy_recursive.c.
References brix_cred_acquire(), brix_status_clear(), brix_opts::cred, brix_cred_view::s3_access, brix_copy_opts::s3_access, brix_cred_view::s3_secret, brix_copy_opts::s3_secret, and XRDC_CRED_S3KEYS.
Referenced by auth_hdr_s3().
sync_cksum_match()
static int sync_cksum_match (brix_conn * c, const char * rpath, const char * lpath, const brix_copy_opts * o) static
Definition at line 92 of file copy_recursive.c.
References brix_cksum_algo_parse(), brix_cksum_fd(), brix_query_cksum(), brix_status_clear(), c, close(), open(), and brix_copy_opts::sync_cksum_algo.
Referenced by dl_sync_skip(), and ul_sync_skip().
tree_dl_entry()
static int tree_dl_entry (const copy_walk_ctx * w, const brix_dirent * e) static
Definition at line 449 of file copy_recursive.c.
References brix_rmdir(), brix_status_clear(), brix_status_set(), copy_walk_ctx::c, copy_tree_download(), dirent_is_dot(), brix_copy_opts::dry_run, brix_statinfo::flags, brix_dirent::have_stat, kXR_isDir, copy_walk_ctx::lpath, brix_dirent::name, copy_walk_ctx::o, path_join(), copy_walk_ctx::rel, rel_join(), brix_copy_opts::remove_source, copy_walk_ctx::rpath, brix_dirent::st, copy_walk_ctx::st, tree_dl_file(), XRDC_EUSAGE, and XRDC_PATH_MAX.
Referenced by copy_tree_download().
tree_dl_file()
static int tree_dl_file (const copy_walk_ctx * w, const brix_dirent * e, const char * relc, const char * rc, const char * lc) static
Definition at line 414 of file copy_recursive.c.
References brix_copy_filter_match(), brix_rm(), brix_status_clear(), copy_walk_ctx::c, copy_one_r2l(), dl_sync_skip(), brix_copy_opts::dry_run, brix_statinfo::flags, brix_dirent::have_stat, kXR_other, copy_walk_ctx::o, brix_copy_opts::remove_source, brix_statinfo::size, brix_dirent::st, and copy_walk_ctx::st.
Referenced by tree_dl_entry().
tree_ul_entry()
static int tree_ul_entry (const copy_walk_ctx * w, const char * name) static
Definition at line 598 of file copy_recursive.c.
References brix_status_set(), copy_walk_ctx::c, copy_tree_upload(), dirent_is_dot(), brix_copy_opts::dry_run, copy_walk_ctx::lpath, lstat(), name, copy_walk_ctx::o, path_join(), copy_walk_ctx::rel, rel_join(), brix_copy_opts::remove_source, copy_walk_ctx::rpath, copy_walk_ctx::st, stat(), tree_ul_file(), XRDC_EUSAGE, and XRDC_PATH_MAX.
Referenced by copy_tree_upload().
tree_ul_file()
static int tree_ul_file (const copy_walk_ctx * w, const char * relc, const char * lc, const char * rc, const struct stat * sb) static
Definition at line 565 of file copy_recursive.c.
References brix_copy_filter_match(), copy_walk_ctx::c, copy_one_l2r(), brix_copy_opts::dry_run, copy_walk_ctx::o, brix_copy_opts::remove_source, copy_walk_ctx::st, and ul_sync_skip().
Referenced by tree_ul_entry().
ul_sync_skip()
static int ul_sync_skip (const copy_walk_ctx * w, const char * rc, const char * lc, const struct stat * sb) static
Definition at line 538 of file copy_recursive.c.
References brix_stat(), brix_status_clear(), brix_sync_should_skip(), copy_walk_ctx::c, brix_statinfo::flags, kXR_isDir, brix_statinfo::mtime, copy_walk_ctx::o, brix_statinfo::size, brix_copy_opts::sync, sync_cksum_match(), brix_copy_opts::sync_cmp, and XRDC_SYNC_CKSUM.
Referenced by tree_ul_file().
web_auth_headers()
int web_auth_headers (const web_auth_ctx * a, char * hdrs, size_t hdrsz)
Definition at line 897 of file copy_recursive.c.
References auth_hdr_bearer(), auth_hdr_s3(), web_auth_ctx::co, brix_weburl::is_s3, web_auth_ctx::o, web_auth_ctx::st, and web_auth_ctx::u.
Referenced by copy_web_download(), and copy_web_upload().
web_dl_fetch()
static int web_dl_fetch (const brix_weburl * su, const brix_opts * co, const char * hdrs, web_dl_io * io, brix_status * st) static
Definition at line 921 of file copy_recursive.c.
References web_dl_io::blen, brix_http_download(), brix_opts::ca_dir, brix_weburl::host, web_dl_io::outfd, brix_weburl::path, brix_weburl::port, web_dl_io::status, brix_weburl::tls, brix_opts::verify_host, and XRDC_WEB_TIMEOUT_MS.
Referenced by copy_web_download().