nginx-xrootd: client/lib/xfer/copy_pump.c File Reference
copy_pump.c File Reference
#include "copy_internal.h"
Functions
int write_all (int fd, const uint8_t *buf, size_t n, brix_status *st)
int pump_remote_reopen (pump_remote_t *r, brix_status *st)
ssize_t pump_src_remote (void *ctx, uint8_t *buf, int64_t off, size_t cap, brix_status *st)
int pump_sink_reopen (pump_remote_t *r, brix_status *st)
int pump_sink_remote (void *ctx, const uint8_t *buf, int64_t off, size_t n, brix_status *st)
ssize_t pump_src_local (void *ctx, uint8_t *buf, int64_t off, size_t cap, brix_status *st)
int pump_sink_local (void *ctx, const uint8_t *buf, int64_t off, size_t n, brix_status *st)
ssize_t pump_src_local_vfs (void *ctx, uint8_t *buf, int64_t off, size_t cap, brix_status *st)
int pump_sink_local_vfs (void *ctx, const uint8_t *buf, int64_t off, size_t n, brix_status *st)
static void pump_emit_progress (const brix_copy_opts *o, int64_t cur, int64_t total)
int transfer_pump (pump_src_fn src, void *sctx, pump_sink_fn sink, void *kctx, int64_t expected, const brix_copy_opts *o, int64_t progress_total, brix_status *st)
Function Documentation
pump_emit_progress()
static void pump_emit_progress (const brix_copy_opts * o, int64_t cur, int64_t total) static
Definition at line 220 of file copy_pump.c.
References brix_copy_opts::progress, and brix_copy_opts::progress_arg.
Referenced by transfer_pump().
pump_remote_reopen()
int pump_remote_reopen (pump_remote_t * r, brix_status * st)
Definition at line 41 of file copy_pump.c.
References brix_file_open_opaque(), brix_file_open_read(), brix_reconnect(), pump_remote_t::c, pump_remote_t::f, brix_conn::home_host, brix_conn::home_port, host, brix_conn::host, pump_remote_t::opaque, pump_remote_t::path, port, and brix_conn::port.
Referenced by pump_src_remote().
pump_sink_local()
int pump_sink_local (void * ctx, const uint8_t * buf, int64_t off, size_t n, brix_status * st)
Definition at line 169 of file copy_pump.c.
References write_all().
Referenced by download_to_stdout().
pump_sink_local_vfs()
int pump_sink_local_vfs (void * ctx, const uint8_t * buf, int64_t off, size_t n, brix_status * st)
Definition at line 195 of file copy_pump.c.
References brix_vfs_pwrite(), and pump_local_t::vf.
Referenced by copy_one_r2l(), copy_remote_to_block(), copy_vfs_to_vfs(), and download_to_local_file().
pump_sink_remote()
int pump_sink_remote (void * ctx, const uint8_t * buf, int64_t off, size_t n, brix_status * st)
Definition at line 114 of file copy_pump.c.
References brix_backoff_sleep_fast(), brix_copy_quit_requested(), brix_file_pgwrite(), brix_file_write(), brix_mono_ns(), brix_status_retryable(), pump_remote_t::c, pump_remote_t::f, pump_remote_t::max_stall_ms, pump_remote_t::pgrw, pump_sink_reopen(), and pump_remote_t::resilient.
Referenced by copy_one_l2r(), r2r_stream_body(), and upload_stream_body().
pump_sink_reopen()
int pump_sink_reopen (pump_remote_t * r, brix_status * st)
Definition at line 97 of file copy_pump.c.
References brix_file_open_update(), brix_reconnect(), pump_remote_t::c, pump_remote_t::f, brix_conn::home_host, brix_conn::home_port, host, brix_conn::host, pump_remote_t::path, port, brix_conn::port, and pump_remote_t::posc.
Referenced by pump_sink_remote(), and upload_close_commit_resilient().
pump_src_local()
ssize_t pump_src_local (void * ctx, uint8_t * buf, int64_t off, size_t cap, brix_status * st)
Definition at line 150 of file copy_pump.c.
References brix_status_set(), read(), and XRDC_ESOCK.
Referenced by copy_upload().
pump_src_local_vfs()
ssize_t pump_src_local_vfs (void * ctx, uint8_t * buf, int64_t off, size_t cap, brix_status * st)
Definition at line 186 of file copy_pump.c.
References brix_vfs_pread(), and pump_local_t::vf.
Referenced by copy_block_to_remote(), copy_one_l2r(), copy_upload(), and copy_vfs_to_vfs().
pump_src_remote()
ssize_t pump_src_remote (void * ctx, uint8_t * buf, int64_t off, size_t cap, brix_status * st)
Definition at line 61 of file copy_pump.c.
References brix_backoff_sleep_fast(), brix_copy_quit_requested(), brix_file_pgread(), brix_file_read(), brix_mono_ns(), brix_status_retryable(), pump_remote_t::c, pump_remote_t::cur_chunk, pump_remote_t::f, pump_remote_t::max_stall_ms, pump_remote_t::pgrw, pump_remote_reopen(), pump_remote_t::resilient, and XRDC_RESILIENT_FLOOR.
Referenced by copy_one_r2l(), download_stream_body(), and r2r_stream_body().
transfer_pump()
int transfer_pump (pump_src_fn src, void * sctx, pump_sink_fn sink, void * kctx, int64_t expected, const brix_copy_opts * o, int64_t progress_total, brix_status * st)
Definition at line 237 of file copy_pump.c.
References brix_status_set(), g_brix_copy_quit, pump_emit_progress(), XRDC_COPY_CHUNK, XRDC_EPROTO, and XRDC_ESOCK.
Referenced by copy_one_l2r(), copy_one_r2l(), copy_vfs_to_vfs(), download_stream_body(), r2r_stream_body(), and upload_stream_body().
write_all()
int write_all (int fd, const uint8_t * buf, size_t n, brix_status * st)
Definition at line 9 of file copy_pump.c.
References brix_status_set(), and XRDC_ESOCK.
Referenced by pump_sink_local().