nginx-xrootd: client/lib/xfer/copy_local.c File Reference
copy_local.c File Reference
#include "copy_internal.h"
Data Structures
struct copy_stream_ctx_t
struct download_job_t
Functions
int make_temp_path (const char *dst, char *out, size_t outsz)
int open_download_temp (const char *dst, char *tmp, size_t tmpsz, brix_status *st)
int atomic_dest_finish (const char *tmp, const char *dest, int rc, brix_status *st)
static void csctx_reopen_home (brix_conn *c, brix_status *st)
static int csctx_retry_gate (const brix_status *st, uint64_t deadline_ns, unsigned *attempt)
static int download_open_resilient (const copy_stream_ctx_t *ctx, brix_file *f, brix_status *st)
int download_stream_body (const download_body_ctx *j, pump_sink_fn sink, void *sinkctx, brix_status *st)
static int download_reconcile_cksum (const download_job_t *job, const char *local_path, brix_status *st)
static int download_to_stdout (const download_job_t *job, brix_status *st)
static int download_to_local_file (const download_job_t *job, brix_status *st)
int copy_download (const brix_url *su, const brix_url *du, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
static int upload_open_resilient (const copy_stream_ctx_t *ctx, int force, int posc, brix_file *f, brix_status *st)
static int upload_close_commit_resilient (pump_remote_t *sink, int64_t total, brix_status *st)
static int upload_reconcile_cksum (brix_conn *c, const brix_url *su, const brix_url *du, const brix_copy_opts *o, brix_status *st)
int upload_stream_body (const upload_body_ctx *j, pump_src_fn src, void *srcctx, brix_status *st)
int copy_upload (const brix_url *su, const brix_url *du, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
static ssize_t web_upload_src_vfs (void *ctx, uint8_t *buf, int64_t off, size_t cap, brix_status *st)
int copy_web_upload (const brix_url *su, const brix_weburl *du, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
int copy_web (const char *src, const char *dst, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
Function Documentation
atomic_dest_finish()
int atomic_dest_finish (const char * tmp, const char * dest, int rc, brix_status * st)
Definition at line 77 of file copy_local.c.
References brix_status_set(), and XRDC_ESOCK.
Referenced by copy_web_download().
copy_download()
int copy_download (const brix_url * su, const brix_url * du, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 412 of file copy_local.c.
References access(), brix_close(), brix_status_set(), brix_streams_close(), download_job_t::c, c, copy_stall_ms(), download_to_local_file(), download_to_stdout(), download_job_t::du, brix_statinfo::flags, brix_copy_opts::force, kXR_isDir, brix_streamset::n, download_job_t::o, brix_url::path, resilient_setup(), brix_url::scheme, download_job_t::si, download_job_t::ss, download_job_t::su, XRDC_EUSAGE, and XRDC_SCHEME_STDIO.
Referenced by brix_copy_dispatch_r2l().
copy_upload()
int copy_upload (const brix_url * su, const brix_url * du, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 690 of file copy_local.c.
References brix_status_clear(), brix_vfs_close(), brix_vfs_fstat(), brix_vfs_open(), brix_vfs_open_opts::cred, brix_vfs_open_opts::expected_size, brix_copy_opts::io_uring, brix_vfs_open_opts::io_uring, brix_url::path, pump_src_local(), pump_src_local_vfs(), brix_url::scheme, brix_vfs_stat::size, upload_stream_body(), pump_local_t::vf, XRDC_SCHEME_STDIO, and XRDC_VFS_READ.
Referenced by brix_copy_route().
copy_web()
int copy_web (const char * src, const char * dst, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 809 of file copy_local.c.
References brix_is_web_url(), brix_status_set(), brix_url_parse(), brix_weburl_parse(), copy_web_download(), copy_web_upload(), brix_copy_opts::recursive, brix_url::scheme, XRDC_EUSAGE, XRDC_SCHEME_LOCAL, and XRDC_SCHEME_STDIO.
Referenced by brix_copy().
copy_web_upload()
int copy_web_upload (const brix_url * su, const brix_weburl * du, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 744 of file copy_local.c.
References brix_http_upload_resumable(), brix_status_set(), brix_vfs_close(), brix_vfs_fstat(), brix_vfs_open(), brix_opts::ca_dir, copy_stall_ms(), brix_vfs_open_opts::cred, brix_vfs_open_opts::expected_size, brix_weburl::host, brix_copy_opts::io_uring, brix_vfs_open_opts::io_uring, brix_vfs_stat::is_dir, brix_url::path, brix_weburl::path, brix_weburl::port, brix_url::scheme, brix_copy_opts::silent, brix_vfs_stat::size, brix_weburl::tls, brix_opts::verify_host, web_auth_headers(), web_upload_src_vfs(), XRDC_DEFAULT_MAX_STALL_MS, XRDC_EUSAGE, XRDC_SCHEME_STDIO, XRDC_VFS_READ, and XRDC_WEB_TIMEOUT_MS.
Referenced by copy_web().
csctx_reopen_home()
static void csctx_reopen_home (brix_conn * c, brix_status * st) static
Definition at line 130 of file copy_local.c.
References brix_reconnect(), and c.
Referenced by download_open_resilient(), and upload_open_resilient().
csctx_retry_gate()
static int csctx_retry_gate (const brix_status * st, uint64_t deadline_ns, unsigned * attempt) static
Definition at line 151 of file copy_local.c.
References brix_backoff_sleep_fast(), brix_copy_quit_requested(), brix_mono_ns(), and brix_status_retryable().
Referenced by download_open_resilient(), and upload_open_resilient().
download_open_resilient()
static int download_open_resilient (const copy_stream_ctx_t * ctx, brix_file * f, brix_status * st) static
Definition at line 174 of file copy_local.c.
References brix_file_open_opaque(), brix_file_open_read(), copy_stream_ctx_t::c, csctx_reopen_home(), csctx_retry_gate(), copy_stream_ctx_t::deadline_ns, copy_stream_ctx_t::opaque, and copy_stream_ctx_t::path.
Referenced by download_stream_body().
download_reconcile_cksum()
static int download_reconcile_cksum (const download_job_t * job, const char * local_path, brix_status * st) static
Definition at line 306 of file copy_local.c.
References brix_status_clear(), download_job_t::c, brix_copy_opts::cksum, cksum_verify(), download_job_t::du, brix_status::msg, download_job_t::o, brix_url::path, brix_copy_opts::silent, download_job_t::su, XRDC_CK_MISMATCH, and XRDC_CK_UNVERIFIED.
Referenced by download_to_local_file(), and download_to_stdout().
download_stream_body()
int download_stream_body (const download_body_ctx * j, pump_sink_fn sink, void * sinkctx, brix_status * st)
Definition at line 212 of file copy_local.c.
References brix_file_close(), brix_mono_ns(), brix_status_clear(), brix_streams_open(), pump_remote_t::c, download_body_ctx::c, copy_stream_ctx_t::c, c, brix_copy_opts::compress, copy_stall_ms(), pump_remote_t::cur_chunk, copy_stream_ctx_t::deadline_ns, download_open_resilient(), pump_remote_t::f, pump_remote_t::max_stall_ms, download_body_ctx::o, pump_remote_t::opaque, copy_stream_ctx_t::opaque, brix_url::path, pump_remote_t::path, copy_stream_ctx_t::path, brix_copy_opts::pgrw, pump_remote_t::pgrw, pump_src_remote(), pump_remote_t::resilient, download_body_ctx::si, brix_statinfo::size, download_body_ctx::ss, brix_copy_opts::streams, download_body_ctx::su, transfer_pump(), and XRDC_COPY_CHUNK.
Referenced by copy_remote_to_block(), download_to_local_file(), and download_to_stdout().
download_to_local_file()
static int download_to_local_file (const download_job_t * job, brix_status * st) static
Definition at line 362 of file copy_local.c.
References brix_vfs_abort(), brix_vfs_close(), brix_vfs_commit(), brix_vfs_open(), download_job_t::c, brix_copy_opts::cksum, brix_vfs_open_opts::cred, download_reconcile_cksum(), download_stream_body(), download_job_t::du, brix_vfs_open_opts::expected_size, brix_copy_opts::force, brix_copy_opts::io_uring, brix_vfs_open_opts::io_uring, download_job_t::o, brix_url::path, pump_sink_local_vfs(), download_job_t::si, brix_statinfo::size, download_job_t::ss, download_job_t::su, pump_local_t::vf, XRDC_VFS_FORCE, and XRDC_VFS_WRITE.
Referenced by copy_download().
download_to_stdout()
static int download_to_stdout (const download_job_t * job, brix_status * st) static
Definition at line 337 of file copy_local.c.
References download_job_t::c, brix_copy_opts::cksum, download_reconcile_cksum(), download_stream_body(), download_job_t::o, pump_sink_local(), download_job_t::si, download_job_t::ss, and download_job_t::su.
Referenced by copy_download().
make_temp_path()
int make_temp_path (const char * dst, char * out, size_t outsz)
Definition at line 19 of file copy_local.c.
References s.
Referenced by open_download_temp().
open_download_temp()
int open_download_temp (const char * dst, char * tmp, size_t tmpsz, brix_status * st)
Definition at line 44 of file copy_local.c.
References brix_status_set(), make_temp_path(), open(), and XRDC_EUSAGE.
Referenced by copy_unzip_open_dest(), and copy_web_download().
upload_close_commit_resilient()
static int upload_close_commit_resilient (pump_remote_t * sink, int64_t total, brix_status * st) static
Definition at line 520 of file copy_local.c.
References brix_backoff_sleep_fast(), brix_copy_quit_requested(), brix_file_close(), brix_mono_ns(), brix_stat(), brix_status_clear(), brix_status_retryable(), pump_remote_t::c, pump_remote_t::f, pump_remote_t::max_stall_ms, pump_remote_t::path, pump_sink_reopen(), and brix_statinfo::size.
Referenced by upload_stream_body().
upload_open_resilient()
static int upload_open_resilient (const copy_stream_ctx_t * ctx, int force, int posc, brix_file * f, brix_status * st) static
Definition at line 482 of file copy_local.c.
References brix_file_open_opaque(), brix_file_open_write(), copy_stream_ctx_t::c, csctx_reopen_home(), csctx_retry_gate(), copy_stream_ctx_t::deadline_ns, copy_stream_ctx_t::opaque, and copy_stream_ctx_t::path.
Referenced by upload_stream_body().
upload_reconcile_cksum()
static int upload_reconcile_cksum (brix_conn * c, const brix_url * su, const brix_url * du, const brix_copy_opts * o, brix_status * st) static
Definition at line 570 of file copy_local.c.
References brix_status_clear(), c, brix_copy_opts::cksum, cksum_verify(), brix_status::msg, brix_url::path, brix_url::scheme, brix_copy_opts::silent, XRDC_CK_MISMATCH, XRDC_CK_UNVERIFIED, and XRDC_SCHEME_STDIO.
Referenced by upload_stream_body().
upload_stream_body()
int upload_stream_body (const upload_body_ctx * j, pump_src_fn src, void * srcctx, brix_status * st)
Definition at line 607 of file copy_local.c.
References brix_close(), brix_connect_resilient(), brix_mono_ns(), brix_streams_close(), brix_streams_open(), pump_remote_t::c, copy_stream_ctx_t::c, c, brix_copy_opts::cksum, upload_body_ctx::co, brix_copy_opts::compress, copy_stall_ms(), copy_stream_ctx_t::deadline_ns, upload_body_ctx::du, pump_remote_t::f, brix_copy_opts::force, pump_remote_t::max_stall_ms, brix_streamset::n, upload_body_ctx::o, copy_stream_ctx_t::opaque, brix_url::path, pump_remote_t::path, copy_stream_ctx_t::path, brix_copy_opts::pgrw, pump_remote_t::pgrw, brix_copy_opts::posc, pump_remote_t::posc, pump_sink_remote(), pump_remote_t::resilient, brix_copy_opts::streams, upload_body_ctx::su, upload_body_ctx::total, transfer_pump(), upload_close_commit_resilient(), upload_open_resilient(), upload_reconcile_cksum(), and brix_file::write_codec.
Referenced by copy_block_to_remote(), and copy_upload().
web_upload_src_vfs()
static ssize_t web_upload_src_vfs (void * ctx, uint8_t * buf, int64_t off, size_t cap, brix_status * st) static
Definition at line 736 of file copy_local.c.
References brix_vfs_pread().
Referenced by copy_web_upload().