nginx-xrootd: client/lib/xfer/copy_zip.c File Reference
copy_zip.c File Reference
#include "copy_internal.h"
Functions
ssize_t zip_remote_pread (void *vctx, uint64_t off, void *buf, size_t len)
int unzip_sink_write (void *sc, const uint8_t *d, size_t l)
int copy_unzip (const brix_url *su, const char *archive_path, const char *member, const brix_url *du, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
int unzip_member_from_src (const char *src, const brix_url *su, char *member, size_t member_sz, char *arch, size_t arch_sz)
int zipw_local_write (void *cx, const void *d, size_t n)
int zipw_remote_write (void *cx, const void *d, size_t n)
ssize_t zipw_local_pread (void *cx, uint64_t off, void *buf, size_t len)
const char * zip_member_basename (const char *p)
int zip_read_seed (brix_zip_pread_fn pr, void *ctx, uint64_t size, uint64_t *base, uint8_t **seed_cd, size_t *seed_len, size_t *seed_n, brix_status *st)
int zip_emit_member (brix_zip_writer *w, const char *member, int srcfd, brix_status *st)
int copy_zip_store_local (const char *member, int srcfd, const brix_url *du, int append, brix_status *st)
int copy_zip_store_remote (const char *member, int srcfd, const brix_url *du, int append, const brix_opts *co, brix_status *st)
int copy_zip_store (const brix_url *su, const brix_url *du, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
Function Documentation
copy_unzip()
int copy_unzip (const brix_url * su, const char * archive_path, const char * member, const brix_url * du, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 40 of file copy_zip.c.
References access(), brix_close(), brix_connect(), brix_file_close(), brix_file_open_read(), brix_stat(), brix_status_set(), brix_zip_dir_free(), brix_zip_find(), brix_zip_member_extract(), brix_zip_open(), zip_remote_ctx::c, c, close(), zip_remote_ctx::f, brix_copy_opts::force, open_download_temp(), brix_url::path, brix_url::scheme, brix_statinfo::size, zip_remote_ctx::st, unzip_sink_write(), XRDC_EUSAGE, XRDC_PATH_MAX, XRDC_SCHEME_STDIO, XRDC_ZIP_OK, and zip_remote_pread().
Referenced by brix_copy().
copy_zip_store()
int copy_zip_store (const brix_url * su, const brix_url * du, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 372 of file copy_zip.c.
References brix_status_set(), close(), copy_zip_store_local(), copy_zip_store_remote(), open(), brix_url::path, brix_url::scheme, XRDC_EUSAGE, XRDC_SCHEME_ROOT, XRDC_SCHEME_ROOTS, XRDC_SCHEME_STDIO, brix_copy_opts::zip_append, and zip_member_basename().
Referenced by brix_copy().
copy_zip_store_local()
int copy_zip_store_local (const char * member, int srcfd, const brix_url * du, int append, brix_status * st)
Definition at line 267 of file copy_zip.c.
References brix_status_set(), brix_zip_writer_free(), brix_zip_writer_new(), brix_zip_writer_new_append(), close(), zipw_local_sink::fd, fstat(), zipw_local_sink::off, open(), brix_url::path, stat(), XRDC_EUSAGE, zip_emit_member(), zip_read_seed(), zipw_local_pread(), and zipw_local_write().
Referenced by copy_zip_store().
copy_zip_store_remote()
int copy_zip_store_remote (const char * member, int srcfd, const brix_url * du, int append, const brix_opts * co, brix_status * st)
Definition at line 310 of file copy_zip.c.
References brix_close(), brix_connect(), brix_file_close(), brix_file_open_update(), brix_file_open_write(), brix_stat(), brix_status_clear(), brix_zip_writer_free(), brix_zip_writer_new(), brix_zip_writer_new_append(), zipw_remote_sink::c, c, zipw_remote_sink::f, zipw_remote_sink::off, brix_url::path, brix_statinfo::size, zipw_remote_sink::st, zip_emit_member(), zip_read_seed(), zip_remote_pread(), and zipw_remote_write().
Referenced by copy_zip_store().
unzip_member_from_src()
int unzip_member_from_src (const char * src, const brix_url * su, char * member, size_t member_sz, char * arch, size_t arch_sz)
Definition at line 129 of file copy_zip.c.
References brix_url::path.
Referenced by brix_copy().
unzip_sink_write()
int unzip_sink_write (void * sc, const uint8_t * d, size_t l)
Definition at line 20 of file copy_zip.c.
References s.
Referenced by copy_unzip().
zip_emit_member()
int zip_emit_member (brix_zip_writer * w, const char * member, int srcfd, brix_status * st)
Definition at line 250 of file copy_zip.c.
References brix_status_set(), brix_zip_writer_add_fd(), brix_zip_writer_finish(), XRDC_EPROTO, XRDC_ESOCK, and XRDC_ZIP_OK.
Referenced by copy_zip_store_local(), and copy_zip_store_remote().
zip_member_basename()
const char * zip_member_basename (const char * p)
Definition at line 200 of file copy_zip.c.
References s.
Referenced by copy_zip_store().
zip_read_seed()
int zip_read_seed (brix_zip_pread_fn pr, void * ctx, uint64_t size, uint64_t * base, uint8_t ** seed_cd, size_t * seed_len, size_t * seed_n, brix_status * st)
Definition at line 211 of file copy_zip.c.
References brix_status_set(), brix_zip_read_eocd(), XRDC_EPROTO, XRDC_ESOCK, XRDC_EUSAGE, and XRDC_ZIP_OK.
Referenced by copy_zip_store_local(), and copy_zip_store_remote().
zip_remote_pread()
ssize_t zip_remote_pread (void * vctx, uint64_t off, void * buf, size_t len)
Definition at line 11 of file copy_zip.c.
References brix_file_read(), zip_remote_ctx::c, zip_remote_ctx::f, and zip_remote_ctx::st.
Referenced by copy_unzip(), and copy_zip_store_remote().
zipw_local_pread()
ssize_t zipw_local_pread (void * cx, uint64_t off, void * buf, size_t len)
Definition at line 193 of file copy_zip.c.
References pread().
Referenced by copy_zip_store_local().
zipw_local_write()
int zipw_local_write (void * cx, const void * d, size_t n)
Definition at line 168 of file copy_zip.c.
References s.
Referenced by copy_zip_store_local().
zipw_remote_write()
int zipw_remote_write (void * cx, const void * d, size_t n)
Definition at line 181 of file copy_zip.c.
References brix_file_write(), and s.
Referenced by copy_zip_store_remote().