nginx-xrootd: client/lib/xfer/copy_filter.c File Reference
copy_filter.c File Reference
#include "copy_internal.h"
#include <fnmatch.h>
Functions
static const char * rel_basename (const char *rel)
int brix_copy_filter_match (const brix_copy_opts *o, const char *rel)
int brix_sync_should_skip (int cmp, long long ssz, long long smt, long long dsz, long long dmt)
Function Documentation
brix_copy_filter_match()
int brix_copy_filter_match (const brix_copy_opts * o, const char * rel)
Definition at line 20 of file copy_filter.c.
References brix_copy_opts::excludes, brix_copy_opts::includes, brix_copy_opts::n_excludes, brix_copy_opts::n_includes, and rel_basename().
Referenced by mirror_delete_local(), mirror_delete_remote(), recursive_place(), transfer_filter_check(), tree_dl_file(), tree_ul_file(), and walk_handle_file().
brix_sync_should_skip()
int brix_sync_should_skip (int cmp, long long ssz, long long smt, long long dsz, long long dmt)
Definition at line 46 of file copy_filter.c.
References XRDC_SYNC_MTIME.
Referenced by dl_sync_skip(), transfer_sync_check(), and ul_sync_skip().
rel_basename()
static const char * rel_basename (const char * rel) static
Definition at line 13 of file copy_filter.c.
Referenced by brix_copy_filter_match().