nginx-xrootd: src/protocols/webdav/fs/copy_engine.c File Reference
copy_engine.c File Reference
#include "copy_engine.h"
#include "fs/vfs/vfs.h"
Functions
static ngx_int_t webdav_copy_meta_cb (void *cookie, const char *src, const char *dst, int is_dir)
ngx_int_t webdav_copy_file (ngx_log_t *log, const char *root_canon, const char *src, const char *dst)
ngx_int_t webdav_copy_dir_recursive (ngx_log_t *log, const char *root_canon, const char *src, const char *dst)
Function Documentation
webdav_copy_dir_recursive()
ngx_int_t webdav_copy_dir_recursive (ngx_log_t * log, const char * root_canon, const char * src, const char * dst)
Definition at line 52 of file copy_engine.c.
References brix_vfs_copytree(), log, and webdav_copy_meta_cb().
Referenced by webdav_copy_collection_execute().
webdav_copy_file()
ngx_int_t webdav_copy_file (ngx_log_t * log, const char * root_canon, const char * src, const char * dst)
Definition at line 44 of file copy_engine.c.
References brix_vfs_copyfile(), log, and webdav_copy_meta_cb().
webdav_copy_meta_cb()
static ngx_int_t webdav_copy_meta_cb (void * cookie, const char * src, const char * dst, int is_dir) static
Definition at line 29 of file copy_engine.c.
References webdav_dead_props_copy().
Referenced by webdav_copy_dir_recursive(), and webdav_copy_file().