nginx-xrootd: client/lib/xfer/copy_remote.c File Reference
copy_remote.c File Reference
#include "copy_internal.h"
Data Structures
struct cksum_spec_t
struct tpc_state_t
struct tpc_params_t
Functions
int r2r_teardown (brix_conn *sc, brix_conn *dc, brix_file *sf, brix_file *df, int src_up, int dst_up, int sopen, int dopen, int rc, brix_status *st)
int r2r_stream_body (brix_conn *sc, brix_conn *dc, brix_file *sf, brix_file *df, const brix_statinfo *si, const brix_copy_opts *o, brix_status *st)
int copy_remote_to_remote (const brix_url *su, const brix_url *du, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
static int cksum_parse_spec (const char *spec, cksum_spec_t *out, brix_status *st)
static int cksum_compute_local (const char *local_path, const cksum_spec_t *spec, char *hex, size_t hexsz, brix_status *st)
static int cksum_verify_source (brix_conn *c, const char *remote_path, const char *local_hex, const cksum_spec_t *spec, brix_status *st)
static int cksum_verify_literal (const char *local_hex, const cksum_spec_t *spec, brix_status *st)
int cksum_verify (brix_conn *c, const char *remote_path, const char *local_path, const char *spec, int silent, brix_status *st)
int gen_tpc_key (char *out, size_t outsz)
int tpc_teardown (brix_conn *sc, brix_conn *dc, brix_file *sf, brix_file *df, char *src_opaque, char *dst_opaque, int su_up, int du_up, int sopen, int dopen, int rc, brix_status *st)
static int tpc_state_teardown (tpc_state_t *s, int rc, brix_status *st)
static int tpc_setup_source (tpc_state_t *s, tpc_params_t *p, brix_status *st)
static void tpc_build_dst_opaque (char *dst_opaque, size_t need, const tpc_params_t *p)
static int tpc_run_rendezvous (tpc_state_t *s, const tpc_params_t *p, brix_status *st)
int copy_tpc (const brix_url *su, const brix_url *du, const brix_copy_opts *o, const brix_opts *co, brix_status *st)
Function Documentation
cksum_compute_local()
static int cksum_compute_local (const char * local_path, const cksum_spec_t * spec, char * hex, size_t hexsz, brix_status * st) static
Definition at line 171 of file copy_remote.c.
References cksum_spec_t::algo, brix_cksum_fd(), brix_status_set(), close(), hex(), open(), and XRDC_EUSAGE.
Referenced by cksum_verify().
cksum_parse_spec()
static int cksum_parse_spec (const char * spec, cksum_spec_t * out, brix_status * st) static
Definition at line 140 of file copy_remote.c.
References cksum_spec_t::algo, brix_cksum_algo_parse(), brix_status_set(), cksum_spec_t::mode, cksum_spec_t::name, and XRDC_EUSAGE.
Referenced by cksum_verify().
cksum_verify()
int cksum_verify (brix_conn * c, const char * remote_path, const char * local_path, const char * spec, int silent, brix_status * st)
Definition at line 269 of file copy_remote.c.
References c, cksum_compute_local(), cksum_parse_spec(), cksum_verify_literal(), cksum_verify_source(), cksum_spec_t::mode, cksum_spec_t::name, cksum_spec_t::silent, XRDC_CK_OK, and XRDC_CK_UNVERIFIED.
Referenced by download_reconcile_cksum(), and upload_reconcile_cksum().
cksum_verify_literal()
static int cksum_verify_literal (const char * local_hex, const cksum_spec_t * spec, brix_status * st) static
Definition at line 238 of file copy_remote.c.
References brix_status_set(), cksum_spec_t::mode, cksum_spec_t::name, cksum_spec_t::silent, XRDC_CK_MISMATCH, XRDC_CK_OK, and XRDC_EINTEGRITY.
Referenced by cksum_verify().
cksum_verify_source()
static int cksum_verify_source (brix_conn * c, const char * remote_path, const char * local_hex, const cksum_spec_t * spec, brix_status * st) static
Definition at line 201 of file copy_remote.c.
References brix_query_cksum(), brix_status_set(), c, cksum_spec_t::name, cksum_spec_t::silent, XRDC_CK_MISMATCH, XRDC_CK_OK, XRDC_CK_UNVERIFIED, XRDC_EINTEGRITY, and XRDC_EUSAGE.
Referenced by cksum_verify().
copy_remote_to_remote()
int copy_remote_to_remote (const brix_url * su, const brix_url * du, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 74 of file copy_remote.c.
References brix_connect(), brix_file_open_read(), brix_file_open_write(), brix_stat(), brix_status_set(), brix_statinfo::flags, brix_copy_opts::force, kXR_isDir, brix_url::path, brix_copy_opts::posc, r2r_stream_body(), r2r_teardown(), and XRDC_EUSAGE.
Referenced by brix_copy_dispatch_r2r().
copy_tpc()
int copy_tpc (const brix_url * su, const brix_url * du, const brix_copy_opts * o, const brix_opts * co, brix_status * st)
Definition at line 587 of file copy_remote.c.
References brix_file_sync(), s, tpc_params_t::su, tpc_run_rendezvous(), tpc_setup_source(), tpc_state_teardown(), and brix_copy_opts::tpc_token_mode.
Referenced by brix_copy_dispatch_r2r().
gen_tpc_key()
int gen_tpc_key (char * out, size_t outsz)
Definition at line 313 of file copy_remote.c.
References brix_hex_encode(), close(), open(), and read().
Referenced by tpc_setup_source().
r2r_stream_body()
int r2r_stream_body (brix_conn * sc, brix_conn * dc, brix_file * sf, brix_file * df, const brix_statinfo * si, const brix_copy_opts * o, brix_status * st)
Definition at line 61 of file copy_remote.c.
References pump_remote_t::c, brix_copy_opts::pgrw, pump_sink_remote(), pump_src_remote(), brix_statinfo::size, and transfer_pump().
Referenced by copy_remote_to_remote().
r2r_teardown()
int r2r_teardown (brix_conn * sc, brix_conn * dc, brix_file * sf, brix_file * df, int src_up, int dst_up, int sopen, int dopen, int rc, brix_status * st)
Definition at line 27 of file copy_remote.c.
References brix_close(), brix_file_close(), and brix_status_clear().
Referenced by copy_remote_to_remote().
tpc_build_dst_opaque()
static void tpc_build_dst_opaque (char * dst_opaque, size_t need, const tpc_params_t * p) static
Definition at line 512 of file copy_remote.c.
References brix_url::host, tpc_params_t::key, brix_url::path, brix_url::port, tpc_params_t::size, tpc_params_t::src_hp, tpc_params_t::su, and tpc_params_t::tok.
Referenced by tpc_run_rendezvous().
tpc_run_rendezvous()
static int tpc_run_rendezvous (tpc_state_t * s, const tpc_params_t * p, brix_status * st) static
Definition at line 543 of file copy_remote.c.
References brix_connect(), brix_file_open_opaque(), brix_file_sync(), brix_status_set(), tpc_params_t::co, tpc_params_t::du, brix_copy_opts::force, brix_url::host, tpc_params_t::key, tpc_params_t::o, brix_url::path, brix_copy_opts::posc, s, tpc_params_t::su, tpc_params_t::tok, tpc_build_dst_opaque(), tpc_state_teardown(), XRDC_EPROTO, and XRDC_HOSTPORT_MAX.
Referenced by copy_tpc().
tpc_setup_source()
static int tpc_setup_source (tpc_state_t * s, tpc_params_t * p, brix_status * st) static
Definition at line 470 of file copy_remote.c.
References brix_connect(), brix_format_host_port(), brix_stat(), brix_status_set(), tpc_params_t::co, gen_tpc_key(), tpc_params_t::key, brix_status::kxr, kXR_NotFound, brix_url::path, s, brix_statinfo::size, tpc_params_t::size, tpc_params_t::src_hp, tpc_params_t::su, tpc_state_teardown(), and XRDC_ESOCK.
Referenced by copy_tpc().
tpc_state_teardown()
static int tpc_state_teardown (tpc_state_t * s, int rc, brix_status * st) static
Definition at line 448 of file copy_remote.c.
References s, and tpc_teardown().
Referenced by copy_tpc(), tpc_run_rendezvous(), and tpc_setup_source().
tpc_teardown()
int tpc_teardown (brix_conn * sc, brix_conn * dc, brix_file * sf, brix_file * df, char * src_opaque, char * dst_opaque, int su_up, int du_up, int sopen, int dopen, int rc, brix_status * st)
Definition at line 377 of file copy_remote.c.
References brix_close(), brix_file_close(), and brix_status_clear().
Referenced by tpc_state_teardown().