nginx-xrootd: src/protocols/webdav/copy_collection.c File Reference
copy_collection.c File Reference
#include "webdav.h"
#include "copy_internal.h"
#include "protocols/webdav/fs/copy_engine.h"
#include "protocols/webdav/methods/copy_conditionals.h"
#include "core/http/http_conditionals.h"
#include "core/compat/error_mapping.h"
#include "core/compat/namespace_ops.h"
#include "core/compat/tmp_path.h"
#include "fs/vfs/vfs.h"
#include "auth/impersonate/impersonate.h"
#include "fs/path/path.h"
#include <errno.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
struct webdav_copy_job_t
struct webdav_copy_collection_task_t
Functions
static void webdav_copy_job_init (webdav_copy_job_t *job, ngx_log_t *log, const char *root_canon, const webdav_copy_req_t *req)
static ngx_int_t webdav_copy_collection_stage (const webdav_copy_job_t *job, char *tmp_path, size_t tmp_path_size)
static ngx_int_t webdav_copy_collection_commit (const webdav_copy_job_t *job, const char *tmp_path)
static ngx_int_t webdav_copy_collection_execute (const webdav_copy_job_t *job)
static void webdav_copy_collection_thread (void *data, ngx_log_t *log)
static void webdav_copy_collection_done (ngx_event_t *ev)
static ngx_thread_pool_t * webdav_copy_thread_pool (ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t webdav_copy_collection_post_task (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const webdav_copy_job_t *job)
ngx_int_t webdav_copy_do_collection (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const webdav_copy_req_t *req)
Function Documentation
webdav_copy_collection_commit()
static ngx_int_t webdav_copy_collection_commit (const webdav_copy_job_t * job, const char * tmp_path) static
Definition at line 145 of file copy_collection.c.
References brix_log_safe_path(), brix_rename_confined_canon(), webdav_copy_job_t::dst_existed, webdav_copy_job_t::dst_path, webdav_copy_job_t::dst_was_dir, webdav_copy_job_t::log, webdav_copy_job_t::root_canon, and webdav_delete_path_recursive().
Referenced by webdav_copy_collection_execute().
webdav_copy_collection_done()
static void webdav_copy_collection_done (ngx_event_t * ev) static
Definition at line 215 of file copy_collection.c.
References webdav_copy_collection_task_t::http_status, webdav_copy_collection_task_t::r, webdav_metrics_finalize_request(), and webdav_send_status_only().
Referenced by webdav_copy_collection_post_task().
webdav_copy_collection_execute()
static ngx_int_t webdav_copy_collection_execute (const webdav_copy_job_t * job) static
Definition at line 181 of file copy_collection.c.
References webdav_copy_collection_commit(), webdav_copy_collection_stage(), and WEBDAV_MAX_PATH.
Referenced by webdav_copy_collection_thread(), and webdav_copy_do_collection().
webdav_copy_collection_post_task()
static ngx_int_t webdav_copy_collection_post_task (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const webdav_copy_job_t * job) static
Definition at line 268 of file copy_collection.c.
References brix_imp_enabled(), webdav_copy_collection_task_t::http_status, webdav_copy_collection_task_t::job, webdav_copy_job_t::log, webdav_copy_collection_task_t::r, webdav_copy_collection_done(), webdav_copy_collection_thread(), and webdav_copy_thread_pool().
Referenced by webdav_copy_do_collection().
webdav_copy_collection_stage()
static ngx_int_t webdav_copy_collection_stage (const webdav_copy_job_t * job, char * tmp_path, size_t tmp_path_size) static
Definition at line 101 of file copy_collection.c.
References brix_make_tmp_path(), brix_ns_copy_fattrs(), brix_vfs_mkdir_path(), webdav_copy_job_t::depth_infinity, webdav_copy_job_t::dst_path, webdav_copy_job_t::log, webdav_copy_job_t::root_canon, webdav_copy_job_t::src_mode, webdav_copy_job_t::src_path, webdav_copy_dir_recursive(), webdav_dead_props_copy(), and webdav_delete_path_recursive().
Referenced by webdav_copy_collection_execute().
webdav_copy_collection_thread()
static void webdav_copy_collection_thread (void * data, ngx_log_t * log) static
Definition at line 200 of file copy_collection.c.
References webdav_copy_collection_task_t::http_status, webdav_copy_collection_task_t::job, log, and webdav_copy_collection_execute().
Referenced by webdav_copy_collection_post_task().
webdav_copy_do_collection()
ngx_int_t webdav_copy_do_collection (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const webdav_copy_req_t * req)
Definition at line 333 of file copy_collection.c.
References ngx_http_brix_webdav_loc_conf_t::common, webdav_copy_req_t::depth_infinity, webdav_copy_job_t::log, ngx_http_brix_shared_conf_t::root_canon, webdav_copy_collection_execute(), webdav_copy_collection_post_task(), and webdav_copy_job_init().
Referenced by webdav_handle_copy().
webdav_copy_job_init()
static void webdav_copy_job_init (webdav_copy_job_t * job, ngx_log_t * log, const char * root_canon, const webdav_copy_req_t * req) static
Definition at line 71 of file copy_collection.c.
References webdav_copy_job_t::depth_infinity, webdav_copy_req_t::depth_infinity, webdav_copy_job_t::dst_existed, webdav_copy_req_t::dst_existed, webdav_copy_job_t::dst_path, webdav_copy_req_t::dst_path, webdav_copy_req_t::dst_sb, webdav_copy_job_t::dst_was_dir, log, webdav_copy_job_t::log, webdav_copy_job_t::root_canon, webdav_copy_job_t::src_mode, webdav_copy_job_t::src_path, webdav_copy_req_t::src_path, and webdav_copy_req_t::src_sb.
Referenced by webdav_copy_do_collection().
webdav_copy_thread_pool()
static ngx_thread_pool_t * webdav_copy_thread_pool (ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 243 of file copy_collection.c.
References ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::thread_pool, and ngx_http_brix_shared_conf_t::thread_pool_name.
Referenced by webdav_copy_collection_post_task().