nginx-xrootd: src/core/compat/copy_range.h File Reference
copy_range.h File Reference
#include <ngx_core.h>
#include <sys/types.h>
Functions
ngx_int_t brix_copy_range (ngx_log_t *log, int src_fd, off_t src_off, int dst_fd, off_t dst_off, size_t len, const char *src_path, const char *dst_path)
Function Documentation
brix_copy_range()
ngx_int_t brix_copy_range (ngx_log_t * log, int src_fd, off_t src_off, int dst_fd, off_t dst_off, size_t len, const char * src_path, const char * dst_path)
Definition at line 95 of file copy_range.c.
References brix_copy_range_fallback(), brix_sd_posix_wrap(), and log.
Referenced by brix_handle_clone(), brix_http_body_write_buf(), brix_ns_local_copy(), brix_vfs_copyfile(), ckp_begin(), ckp_recover_one(), ckp_rollback(), and s3_mpu_assemble().