nginx-xrootd: src/core/compat/uri.c File Reference
uri.c File Reference
#include "uri.h"
#include "hex.h"
#include <string.h>
Functions
int brix_http_urldecode (const unsigned char *src, size_t src_len, char *dst, size_t dst_sz, unsigned flags)
ssize_t brix_http_urlencode (const unsigned char *src, size_t srclen, char *dst, size_t dstsz, const char *safe_extra)
Function Documentation
brix_http_urldecode()
int brix_http_urldecode (const unsigned char * src, size_t src_len, char * dst, size_t dst_sz, unsigned flags)
Definition at line 14 of file uri.c.
References brix_hex_from_char(), BRIX_URLDECODE_BADARG, BRIX_URLDECODE_NUL_BYTE, BRIX_URLDECODE_OK, BRIX_URLDECODE_OVERFLOW, BRIX_URLDECODE_PLUS_TO_SPACE, and BRIX_URLDECODE_REJECT_NUL.
Referenced by brix_http_query_copy_value(), brix_webdav_list(), parse_response(), s3_echo_user_metadata(), s3_handle_get_object_tagging(), s3_parse_uri(), sigv4_copy_arg_decoded(), sigv4_store_param(), and webdav_urldecode().
brix_http_urlencode()
ssize_t brix_http_urlencode (const unsigned char * src, size_t srclen, char * dst, size_t dstsz, const char * safe_extra)
Definition at line 75 of file uri.c.
References c.
Referenced by brix_s3_list(), brix_s3_sign_v4_q(), s3_canon_qs(), s3_list_emit_entries(), s3_tag_blob_from_xml(), s3_user_meta_blob_from_headers(), s3_verify_sigv4(), sd_s3_sign(), sd_s3_sign_ext(), and uriencode_param().