nginx-xrootd: src/core/config/policy.c File Reference
policy.c File Reference
#include "config.h"
Functions
char * brix_conf_set_authdb (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_require_vo (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_inherit_parent_group (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
ngx_int_t brix_config_finalize_policy (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
Function Documentation
brix_conf_set_authdb()
char * brix_conf_set_authdb (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 13 of file policy.c.
References brix_parse_authdb().
brix_conf_set_inherit_parent_group()
char * brix_conf_set_inherit_parent_group (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 85 of file policy.c.
References brix_normalize_policy_path(), and brix_group_rule_t::path.
brix_conf_set_require_vo()
char * brix_conf_set_require_vo (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 46 of file policy.c.
References brix_copy_conf_string(), brix_normalize_policy_path(), brix_vo_rule_t::path, and brix_vo_rule_t::vo.
brix_config_finalize_policy()
ngx_int_t brix_config_finalize_policy (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf)
Definition at line 122 of file policy.c.
References BRIX_AUTH_BOTH, BRIX_AUTH_GSI, BRIX_AUTH_TOKEN, brix_finalize_authdb_rules(), brix_finalize_group_rules(), brix_finalize_vo_rules(), BRIX_PATH_DIRECTORY, brix_validate_path(), and brix_voms_available().
Referenced by postconf_finalize_policies().