nginx-xrootd: src/core/compat/crc32c.c File Reference
crc32c.c File Reference
#include "crc32c.h"
#include <string.h>
Macros
#define BRIX_CRC32C_POLY 0x82F63B78u
Functions
static uint32_t brix_crc32c_sw_extend (uint32_t crc, const unsigned char *p, size_t len)
static uint32_t brix_crc32c_copy_sw (const unsigned char *src, unsigned char *dst, size_t len)
uint32_t brix_crc32c_extend (uint32_t crc, const void *buf, size_t len)
uint32_t brix_crc32c_value (const void *buf, size_t len)
uint32_t brix_crc32c_copy_value (const unsigned char *src, unsigned char *dst, size_t len)
Macro Definition Documentation
BRIX_CRC32C_POLY
#define BRIX_CRC32C_POLY 0x82F63B78u
Definition at line 25 of file crc32c.c.
Function Documentation
brix_crc32c_copy_sw()
static uint32_t brix_crc32c_copy_sw (const unsigned char * src, unsigned char * dst, size_t len) static
Definition at line 74 of file crc32c.c.
References BRIX_CRC32C_POLY.
Referenced by brix_crc32c_copy_value().
brix_crc32c_copy_value()
uint32_t brix_crc32c_copy_value (const unsigned char * src, unsigned char * dst, size_t len)
Definition at line 591 of file crc32c.c.
References brix_crc32c_copy_sw().
Referenced by brix_crc32c_copy(), xrdp_pg_decode(), xrdp_pg_decode_collect(), and xrdp_pg_encode().
brix_crc32c_extend()
uint32_t brix_crc32c_extend (uint32_t crc, const void * buf, size_t len)
Definition at line 556 of file crc32c.c.
References brix_crc32c_sw_extend().
Referenced by brix_crc32c_value(), u32_update(), xmeta_decode_bitmap_astat(), and xmeta_encode_stock_prefix().
brix_crc32c_sw_extend()
static uint32_t brix_crc32c_sw_extend (uint32_t crc, const unsigned char * p, size_t len) static
Definition at line 44 of file crc32c.c.
References BRIX_CRC32C_POLY.
Referenced by brix_crc32c_extend().
brix_crc32c_value()
uint32_t brix_crc32c_value (const void * buf, size_t len)
Definition at line 585 of file crc32c.c.
References brix_crc32c_extend().
Referenced by brix_crc32c(), brix_csi_write_update(), brix_pgread_crc_batch(), brix_vfs_io_execute_read(), csi_flush_recompute_block(), csi_verify_against(), read_status_frame(), srq_hdr_compute_crc(), srq_rec_compute_crc(), test_unknown_section(), xmeta_decode_bitmap_astat(), xmeta_decode_ext_sections(), xmeta_decode_stock_store(), xmeta_encode_blockcrc_section(), xmeta_encode_stock_prefix(), and xmeta_put_section().