nginx-xrootd: src/core/compat/xml.c File Reference
xml.c File Reference
#include "xml.h"
#include "hex.h"
#include <string.h>
#include <libxml/parser.h>
#include <libxml/tree.h>
Macros
#define BRIX_XML_MAX_LOCKINFO_BODY 65536u
Functions
size_t brix_xml_escaped_len (const unsigned char *src, size_t len, unsigned flags)
static unsigned char * brix_xml_escape_char (unsigned char c, unsigned flags, unsigned char *out)
int brix_xml_escape (const unsigned char *src, size_t len, unsigned flags, unsigned char *dst, size_t dst_size, size_t *written)
static int brix_xml_element_name_valid (const char *name)
size_t brix_xml_text_element_len (const char *name, const unsigned char *text, size_t text_len, unsigned flags)
int brix_xml_write_text_element (const char *name, const unsigned char *text, size_t text_len, unsigned flags, unsigned char *dst, size_t dst_size, size_t *written)
static int brix_xml_name_is (const char *name, const char *want)
static xmlNodePtr brix_xml_find_child (xmlNodePtr node, const char *name)
static xmlNodePtr brix_xml_find_descendant (xmlNodePtr node, const char *name)
static void brix_xml_copy_content (xmlNodePtr node, char *dst, size_t dst_len)
static void brix_xml_lockinfo_extract (xmlNodePtr root, char *owner, size_t owner_len, int *exclusive)
int brix_xml_parse_lockinfo (const char *xml, size_t xml_len, char *owner, size_t owner_len, int *exclusive)
const char * brix_xml_backend_name (void)
Macro Definition Documentation
BRIX_XML_MAX_LOCKINFO_BODY
#define BRIX_XML_MAX_LOCKINFO_BODY 65536u
Definition at line 28 of file xml.c.
Function Documentation
brix_xml_backend_name()
const char * brix_xml_backend_name (void)
Definition at line 482 of file xml.c.
brix_xml_copy_content()
static void brix_xml_copy_content (xmlNodePtr node, char * dst, size_t dst_len) static
Definition at line 353 of file xml.c.
Referenced by brix_xml_lockinfo_extract().
brix_xml_element_name_valid()
static int brix_xml_element_name_valid (const char * name) static
Definition at line 191 of file xml.c.
References name.
Referenced by brix_xml_text_element_len(), and brix_xml_write_text_element().
brix_xml_escape()
int brix_xml_escape (const unsigned char * src, size_t len, unsigned flags, unsigned char * dst, size_t dst_size, size_t * written)
Definition at line 145 of file xml.c.
References brix_xml_escape_char(), and brix_xml_escaped_len().
Referenced by brix_xml_write_text_element(), and webdav_escape_xml_text().
brix_xml_escape_char()
static unsigned char * brix_xml_escape_char (unsigned char c, unsigned flags, unsigned char * out) static
Definition at line 101 of file xml.c.
References brix_hex_nibble(), BRIX_XML_ESCAPE_APOS_ENTITY, BRIX_XML_ESCAPE_CONTROL_PERCENT, and c.
Referenced by brix_xml_escape().
brix_xml_escaped_len()
size_t brix_xml_escaped_len (const unsigned char * src, size_t len, unsigned flags)
Definition at line 43 of file xml.c.
References BRIX_XML_ESCAPE_APOS_ENTITY, and BRIX_XML_ESCAPE_CONTROL_PERCENT.
Referenced by brix_xml_escape(), brix_xml_text_element_len(), brix_xml_write_text_element(), and webdav_escape_xml_text().
brix_xml_find_child()
static xmlNodePtr brix_xml_find_child (xmlNodePtr node, const char * name) static
Definition at line 305 of file xml.c.
References brix_xml_name_is(), and name.
Referenced by brix_xml_lockinfo_extract().
brix_xml_find_descendant()
static xmlNodePtr brix_xml_find_descendant (xmlNodePtr node, const char * name) static
Definition at line 324 of file xml.c.
References brix_xml_find_descendant(), brix_xml_name_is(), and name.
Referenced by brix_xml_find_descendant(), and brix_xml_lockinfo_extract().
brix_xml_lockinfo_extract()
static void brix_xml_lockinfo_extract (xmlNodePtr root, char * owner, size_t owner_len, int * exclusive) static
Definition at line 393 of file xml.c.
References brix_xml_copy_content(), brix_xml_find_child(), and brix_xml_find_descendant().
Referenced by brix_xml_parse_lockinfo().
brix_xml_name_is()
static int brix_xml_name_is (const char * name, const char * want) static
Definition at line 297 of file xml.c.
References name.
Referenced by brix_xml_find_child(), brix_xml_find_descendant(), and brix_xml_parse_lockinfo().
brix_xml_parse_lockinfo()
int brix_xml_parse_lockinfo (const char * xml, size_t xml_len, char * owner, size_t owner_len, int * exclusive)
Definition at line 433 of file xml.c.
References brix_xml_lockinfo_extract(), BRIX_XML_MAX_LOCKINFO_BODY, and brix_xml_name_is().
Referenced by webdav_lock_parse_body().
brix_xml_text_element_len()
size_t brix_xml_text_element_len (const char * name, const unsigned char * text, size_t text_len, unsigned flags)
Definition at line 220 of file xml.c.
References brix_xml_element_name_valid(), brix_xml_escaped_len(), and name.
Referenced by brix_http_send_xml_error().
brix_xml_write_text_element()
int brix_xml_write_text_element (const char * name, const unsigned char * text, size_t text_len, unsigned flags, unsigned char * dst, size_t dst_size, size_t * written)
Definition at line 250 of file xml.c.
References brix_xml_element_name_valid(), brix_xml_escape(), brix_xml_escaped_len(), and name.
Referenced by brix_http_send_xml_error(), and s3_delete_xml_append_elem().