nginx-xrootd: src/core/config/helpers.c File Reference
helpers.c File Reference
#include "config.h"
Functions
ngx_int_t brix_validate_path (ngx_conf_t *cf, const char *label, const ngx_str_t *path, brix_path_kind_t kind, int access_mode)
char * brix_copy_conf_string (ngx_conf_t *cf, const ngx_str_t *src, ngx_str_t *dst)
Function Documentation
brix_copy_conf_string()
char * brix_copy_conf_string (ngx_conf_t * cf, const ngx_str_t * src, ngx_str_t * dst)
Definition at line 72 of file helpers.c.
Referenced by brix_conf_set_cms_manager(), brix_conf_set_require_vo(), and webdav_conf_require_vo().
brix_validate_path()
ngx_int_t brix_validate_path (ngx_conf_t * cf, const char * label, const ngx_str_t * path, brix_path_kind_t kind, int access_mode)
Definition at line 13 of file helpers.c.
References access(), BRIX_PATH_DIRECTORY, BRIX_PATH_FILE_OR_DIRECTORY, BRIX_PATH_REGULAR_FILE, and stat().
Referenced by brix_config_finalize_policy(), brix_config_prepare_server(), brix_configure_gsi(), brix_configure_token_auth(), brix_prepare_export_root(), and brix_sss_load_keytab().