nginx-xrootd: src/core/compat/xml.h File Reference
xml.h File Reference
#include <stddef.h>
Macros
#define BRIX_XML_ESCAPE_APOS_ENTITY 0x0001u /* encode ' as &apos; instead of &#39; */
#define BRIX_XML_ESCAPE_CONTROL_PERCENT 0x0002u /* encode control chars (<0x20, 0x7f) as %XX */
Functions
size_t brix_xml_escaped_len (const unsigned char *src, size_t len, unsigned flags)
int brix_xml_escape (const unsigned char *src, size_t len, unsigned flags, unsigned char *dst, size_t dst_size, size_t *written)
size_t brix_xml_text_element_len (const char *name, const unsigned char *text, size_t text_len, unsigned flags)
int brix_xml_write_text_element (const char *name, const unsigned char *text, size_t text_len, unsigned flags, unsigned char *dst, size_t dst_size, size_t *written)
int brix_xml_parse_lockinfo (const char *xml, size_t xml_len, char *owner, size_t owner_len, int *exclusive)
const char * brix_xml_backend_name (void)
Macro Definition Documentation
BRIX_XML_ESCAPE_APOS_ENTITY
#define BRIX_XML_ESCAPE_APOS_ENTITY 0x0001u /* encode ' as &apos; instead of &#39; */
Definition at line 27 of file xml.h.
BRIX_XML_ESCAPE_CONTROL_PERCENT
#define BRIX_XML_ESCAPE_CONTROL_PERCENT 0x0002u /* encode control chars (<0x20, 0x7f) as %XX */
Definition at line 28 of file xml.h.
Function Documentation
brix_xml_backend_name()
const char * brix_xml_backend_name (void)
Definition at line 482 of file xml.c.
brix_xml_escape()
int brix_xml_escape (const unsigned char * src, size_t len, unsigned flags, unsigned char * dst, size_t dst_size, size_t * written)
Definition at line 145 of file xml.c.
References brix_xml_escape_char(), and brix_xml_escaped_len().
Referenced by brix_xml_write_text_element(), and webdav_escape_xml_text().
brix_xml_escaped_len()
size_t brix_xml_escaped_len (const unsigned char * src, size_t len, unsigned flags)
Definition at line 43 of file xml.c.
References BRIX_XML_ESCAPE_APOS_ENTITY, and BRIX_XML_ESCAPE_CONTROL_PERCENT.
Referenced by brix_xml_escape(), brix_xml_text_element_len(), brix_xml_write_text_element(), and webdav_escape_xml_text().
brix_xml_parse_lockinfo()
int brix_xml_parse_lockinfo (const char * xml, size_t xml_len, char * owner, size_t owner_len, int * exclusive)
Definition at line 433 of file xml.c.
References brix_xml_lockinfo_extract(), BRIX_XML_MAX_LOCKINFO_BODY, and brix_xml_name_is().
Referenced by webdav_lock_parse_body().
brix_xml_text_element_len()
size_t brix_xml_text_element_len (const char * name, const unsigned char * text, size_t text_len, unsigned flags)
Definition at line 220 of file xml.c.
References brix_xml_element_name_valid(), brix_xml_escaped_len(), and name.
Referenced by brix_http_send_xml_error().
brix_xml_write_text_element()
int brix_xml_write_text_element (const char * name, const unsigned char * text, size_t text_len, unsigned flags, unsigned char * dst, size_t dst_size, size_t * written)
Definition at line 250 of file xml.c.
References brix_xml_element_name_valid(), brix_xml_escape(), brix_xml_escaped_len(), and name.
Referenced by brix_http_send_xml_error(), and s3_delete_xml_append_elem().