nginx-xrootd: src/core/aio/readv.c File Reference
readv.c File Reference
#include "core/ngx_brix_module.h"
Functions
void brix_readv_aio_thread (void *data, ngx_log_t *log)
void brix_readv_aio_done (ngx_event_t *ev)
Function Documentation
brix_readv_aio_done()
void brix_readv_aio_done (ngx_event_t * ev)
Definition at line 91 of file readv.c.
References brix_aio_restore_request(), brix_aio_resume(), brix_build_chunked_chain(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_READV, brix_queue_response_chain(), brix_release_read_buffer(), brix_send_error(), brix_ctx_totals_t::bytes, brix_file_t::bytes_read, brix_readv_aio_t::bytes_read_total, brix_readv_aio_t::c, c, brix_readv_aio_t::ctx, brix_readv_aio_t::err_msg, brix_ctx_t::files, brix_vfs_readv_seg_t::handle_index, brix_readv_aio_t::io_error, kXR_IOError, brix_vfs_readv_seg_t::read_length, brix_readv_aio_t::response_buffer, brix_readv_aio_t::response_bytes, brix_readv_aio_t::segment_count, brix_readv_aio_t::segments, brix_ctx_t::state, brix_readv_aio_t::streamid, brix_ctx_t::totals, and XRD_ST_SENDING.
Referenced by brix_handle_readv().
brix_readv_aio_thread()
void brix_readv_aio_thread (void * data, ngx_log_t * log)
Definition at line 34 of file readv.c.
References brix_vfs_io_execute(), BRIX_VFS_IO_READV, brix_readv_aio_t::bytes_read_total, brix_readv_aio_t::err_msg, brix_vfs_job_t::err_msg, brix_vfs_job_t::err_msg_cap, brix_vfs_job_t::io_errno, brix_readv_aio_t::io_error, brix_vfs_job_t::nio, brix_vfs_job_t::nsegs, brix_vfs_job_t::op, brix_vfs_job_t::out_size, brix_readv_aio_t::response_bytes, brix_readv_aio_t::segment_count, brix_readv_aio_t::segments, and brix_vfs_job_t::segs.
Referenced by brix_handle_readv().