nginx-xrootd: src/core/aio/write.c File Reference
write.c File Reference
#include "core/ngx_brix_module.h"
#include "fs/cache/writethrough_metrics.h"
#include "protocols/root/write/wrts_journal.h"
#include "protocols/root/connection/disconnect.h"
#include "protocols/root/connection/event_sched.h"
Data Structures
struct brix_write_aio_logrec_t
Functions
void brix_write_aio_thread (void *data, ngx_log_t *log)
static void brix_write_aio_log (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf, brix_write_aio_t *t, const brix_write_aio_logrec_t *rec)
static void brix_write_aio_commit (brix_ctx_t *ctx, brix_write_aio_t *t)
static void brix_write_aio_done_pipelined (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf, brix_write_aio_t *t, ngx_int_t op)
static void brix_write_aio_serial_reply_ok (brix_ctx_t *ctx, ngx_connection_t *c, brix_write_aio_t *t)
static void brix_write_aio_done_serial (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf, brix_write_aio_t *t, ngx_int_t op)
void brix_write_aio_done (ngx_event_t *ev)
void brix_writev_write_aio_thread (void *data, ngx_log_t *log)
void brix_writev_write_aio_done (ngx_event_t *ev)
Function Documentation
brix_write_aio_commit()
static void brix_write_aio_commit (brix_ctx_t * ctx, brix_write_aio_t * t) static
Definition at line 88 of file write.c.
References brix_wrts_record(), brix_wt_mark_dirty(), brix_ctx_totals_t::bytes_written, brix_file_t::bytes_written, brix_ctx_t::files, brix_write_aio_t::handle_idx, brix_write_aio_t::nwritten, brix_write_aio_t::req_offset, brix_ctx_t::totals, brix_file_t::wrts_enabled, and brix_file_t::wt_enabled.
Referenced by brix_write_aio_done_pipelined(), and brix_write_aio_done_serial().
brix_write_aio_done()
void brix_write_aio_done (ngx_event_t * ev)
Definition at line 273 of file write.c.
References BRIX_OP_WRITE, brix_run_deferred_teardown(), brix_write_aio_done_pipelined(), brix_write_aio_done_serial(), c, brix_write_aio_t::c, brix_write_aio_t::ctx, brix_ctx_t::destroyed, brix_ctx_out_t::finalize_pending, brix_write_aio_t::is_pgwrite, ngx_stream_brix_module, op, brix_ctx_t::out, brix_write_aio_t::payload_to_free, and brix_ctx_out_t::wr_inflight.
Referenced by brix_try_post_write_aio().
brix_write_aio_done_pipelined()
static void brix_write_aio_done_pipelined (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf, brix_write_aio_t * t, ngx_int_t op) static
Definition at line 121 of file write.c.
References brix_aio_restore_stream(), BRIX_OP_ERR, BRIX_OP_OK, brix_run_deferred_teardown(), brix_schedule_read_resume(), brix_send_error(), brix_send_ok(), brix_write_aio_commit(), brix_write_aio_log(), c, brix_ctx_out_t::finalize_pending, brix_write_aio_t::io_errno, kXR_IOError, brix_write_aio_t::len, brix_write_aio_t::nwritten, op, brix_ctx_t::out, brix_ctx_out_t::resp_async, brix_write_aio_t::streamid, and brix_ctx_out_t::wr_inflight.
Referenced by brix_write_aio_done().
brix_write_aio_done_serial()
static void brix_write_aio_done_serial (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf, brix_write_aio_t * t, ngx_int_t op) static
Definition at line 211 of file write.c.
References brix_aio_restore_request(), brix_aio_resume(), BRIX_OP_ERR, BRIX_OP_OK, brix_send_error(), brix_write_aio_commit(), brix_write_aio_log(), brix_write_aio_serial_reply_ok(), c, brix_write_aio_t::io_errno, kXR_IOError, brix_write_aio_t::len, brix_write_aio_t::nwritten, op, and brix_write_aio_t::streamid.
Referenced by brix_write_aio_done().
brix_write_aio_log()
static void brix_write_aio_log (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf, brix_write_aio_t * t, const brix_write_aio_logrec_t * rec) static
Definition at line 58 of file write.c.
References brix_log_access(), c, brix_write_aio_logrec_t::errmsg, brix_write_aio_t::len, brix_write_aio_logrec_t::nbytes, brix_write_aio_logrec_t::ok, brix_write_aio_t::path, brix_write_aio_t::req_offset, and brix_write_aio_logrec_t::xrd_error.
Referenced by brix_write_aio_done_pipelined(), and brix_write_aio_done_serial().
brix_write_aio_serial_reply_ok()
static void brix_write_aio_serial_reply_ok (brix_ctx_t * ctx, ngx_connection_t * c, brix_write_aio_t * t) static
Definition at line 178 of file write.c.
References brix_write_aio_t::bad_page_count, brix_write_aio_t::bad_pages, brix_aio_resume(), brix_send_ok(), brix_send_pgwrite_cse(), brix_send_pgwrite_status(), c, brix_write_aio_t::is_pgwrite, and brix_write_aio_t::req_offset.
Referenced by brix_write_aio_done_serial().
brix_write_aio_thread()
void brix_write_aio_thread (void * data, ngx_log_t * log)
Definition at line 14 of file write.c.
References brix_vfs_io_execute(), brix_vfs_job_set_obj(), brix_vfs_job_write_init(), brix_write_aio_t::csi, brix_vfs_job_t::csi, brix_write_aio_t::data, brix_write_aio_t::fd, brix_write_aio_t::io_errno, brix_vfs_job_t::io_errno, brix_write_aio_t::len, brix_vfs_job_t::nio, brix_write_aio_t::nwritten, brix_write_aio_t::obj, and brix_write_aio_t::offset.
Referenced by brix_try_post_write_aio().
brix_writev_write_aio_done()
void brix_writev_write_aio_done (ngx_event_t * ev)
Definition at line 375 of file write.c.
References brix_aio_restore_request(), brix_aio_resume(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_WRITEV, brix_send_error(), brix_send_ok(), brix_wrts_record(), brix_wt_mark_dirty(), brix_writev_aio_t::bytes_total, brix_ctx_totals_t::bytes_written, brix_file_t::bytes_written, c, brix_writev_aio_t::c, brix_writev_aio_t::ctx, brix_writev_aio_t::err_msg, brix_ctx_t::files, brix_vfs_writev_seg_t::handle_idx, brix_writev_aio_t::io_error, kXR_IOError, brix_writev_aio_t::n_segs, ngx_stream_brix_module, brix_vfs_writev_seg_t::offset, brix_writev_aio_t::payload_buf, brix_writev_aio_t::segs, brix_writev_aio_t::streamid, brix_ctx_t::totals, brix_vfs_writev_seg_t::wlen, brix_file_t::wrts_enabled, and brix_file_t::wt_enabled.
Referenced by writev_try_aio().
brix_writev_write_aio_thread()
void brix_writev_write_aio_thread (void * data, ngx_log_t * log)
Definition at line 335 of file write.c.
References brix_vfs_io_execute(), BRIX_VFS_IO_WRITEV, brix_writev_aio_t::bytes_total, brix_writev_aio_t::do_sync, brix_vfs_job_t::do_sync, brix_writev_aio_t::err_msg, brix_vfs_job_t::err_msg, brix_vfs_job_t::err_msg_cap, brix_vfs_job_t::io_errno, brix_writev_aio_t::io_error, brix_writev_aio_t::n_segs, brix_vfs_job_t::nsegs, brix_vfs_job_t::op, brix_vfs_job_t::out_size, brix_writev_aio_t::segs, brix_vfs_job_t::segs, and brix_vfs_job_t::short_io.
Referenced by writev_try_aio().