nginx-xrootd: src/protocols/webdav/cors.c File Reference
cors.c File Reference
#include "webdav.h"
Data Structures
struct brix_cors_conf_t
Functions
static ngx_int_t origin_allowed (const brix_cors_conf_t *cors, const ngx_str_t *origin, ngx_flag_t *wildcard)
static ngx_int_t brix_http_add_cors_headers (ngx_http_request_t *r, const brix_cors_conf_t *cors)
ngx_int_t webdav_add_cors_headers (ngx_http_request_t *r)
Function Documentation
brix_http_add_cors_headers()
static ngx_int_t brix_http_add_cors_headers (ngx_http_request_t * r, const brix_cors_conf_t * cors) static
Definition at line 58 of file cors.c.
References brix_cors_conf_t::allow_methods, brix_http_find_header(), brix_http_set_header(), brix_http_set_header_str(), brix_http_str_has_ctl(), brix_cors_conf_t::credentials, brix_cors_conf_t::max_age, and origin_allowed().
Referenced by webdav_add_cors_headers().
origin_allowed()
static ngx_int_t origin_allowed (const brix_cors_conf_t * cors, const ngx_str_t * origin, ngx_flag_t * wildcard) static
Definition at line 23 of file cors.c.
References brix_cors_conf_t::origins.
Referenced by brix_http_add_cors_headers().
webdav_add_cors_headers()
ngx_int_t webdav_add_cors_headers (ngx_http_request_t * r)
Definition at line 181 of file cors.c.
References brix_cors_conf_t::allow_methods, brix_http_add_cors_headers(), brix_http_find_header(), brix_http_operation_allow_header(), BRIX_WEBDAV_ALLOW_FLAGS, BRIX_WEBDAV_CORS_ALLOWED, BRIX_WEBDAV_CORS_DENIED, BRIX_WEBDAV_CORS_NO_ORIGIN, BRIX_WEBDAV_METRIC_INC, brix_webdav_operations, brix_webdav_operations_count, ngx_http_brix_webdav_loc_conf_t::cors_credentials, ngx_http_brix_webdav_loc_conf_t::cors_max_age, ngx_http_brix_webdav_loc_conf_t::cors_origins, brix_cors_conf_t::credentials, brix_cors_conf_t::max_age, ngx_http_brix_webdav_module, and brix_cors_conf_t::origins.
Referenced by ngx_http_brix_webdav_access_handler().