nginx-xrootd: client/lib/net/cpool_unittest.c File Reference
cpool_unittest.c File Reference
#include "brix.h"
#include "net/cpool.h"
#include <assert.h>
#include <pthread.h>
#include <stdatomic.h>
#include <stdio.h>
#include <string.h>
Data Structures
struct fake_conn
struct fake_ctx
Macros
#define NSLOT 3
#define NTHR (NSLOT + 1)
Functions
static int fake_connect (void *conn, void *ctx, brix_status *st)
static void fake_close (void *conn)
static void fake_close_counting (void *conn)
static void test_reuse (void)
static void test_health_drop_reconnects (void)
static void test_create_fails_on_bad_endpoint (void)
static void * worker (void *arg)
static void test_contention_unique_issue (void)
static void test_destroy_closes_connected (void)
int main (void)
Variables
static fake_ctx * g_close_ctx
static const brix_cpool_vtbl VT = { sizeof(fake_conn), fake_connect, fake_close }
static brix_cpool * g_p
static atomic_int g_inflight [64]
Macro Definition Documentation
NSLOT
#define NSLOT 3
Definition at line 90 of file cpool_unittest.c.
NTHR
#define NTHR (NSLOT + 1)
Definition at line 91 of file cpool_unittest.c.
Function Documentation
fake_close()
static void fake_close (void * conn) static
Definition at line 33 of file cpool_unittest.c.
fake_close_counting()
static void fake_close_counting (void * conn) static
Definition at line 36 of file cpool_unittest.c.
References fake_ctx::closes, and g_close_ctx.
Referenced by test_destroy_closes_connected().
fake_connect()
static int fake_connect (void * conn, void * ctx, brix_status * st) static
Definition at line 22 of file cpool_unittest.c.
References brix_status_set(), c, fake_conn::id, and XRDC_ESOCK.
Referenced by test_destroy_closes_connected().
main()
int main (void)
Definition at line 146 of file cpool_unittest.c.
References test_contention_unique_issue(), test_create_fails_on_bad_endpoint(), test_destroy_closes_connected(), test_health_drop_reconnects(), and test_reuse().
test_contention_unique_issue()
static void test_contention_unique_issue (void) static
Definition at line 110 of file cpool_unittest.c.
References brix_cpool_create(), brix_cpool_destroy(), brix_status_clear(), fake_ctx::connects, g_inflight, g_p, NSLOT, NTHR, VT, and worker().
Referenced by main().
test_create_fails_on_bad_endpoint()
static void test_create_fails_on_bad_endpoint (void) static
Definition at line 78 of file cpool_unittest.c.
References brix_cpool_create(), brix_status_clear(), fake_ctx::fail_slot0, brix_status::kxr, VT, and XRDC_ESOCK.
Referenced by main().
test_destroy_closes_connected()
static void test_destroy_closes_connected (void) static
Definition at line 127 of file cpool_unittest.c.
References brix_cpool_checkin(), brix_cpool_checkout(), brix_cpool_create(), brix_cpool_destroy(), brix_status_clear(), fake_ctx::closes, fake_ctx::connects, fake_close_counting(), fake_connect(), and g_close_ctx.
Referenced by main().
test_health_drop_reconnects()
static void test_health_drop_reconnects (void) static
Definition at line 61 of file cpool_unittest.c.
References brix_cpool_checkin(), brix_cpool_checkout(), brix_cpool_create(), brix_cpool_destroy(), brix_status_clear(), c, fake_ctx::connects, and VT.
Referenced by main().
test_reuse()
static void test_reuse (void) static
Definition at line 41 of file cpool_unittest.c.
References brix_cpool_checkin(), brix_cpool_checkout(), brix_cpool_create(), brix_cpool_destroy(), brix_status_clear(), c, fake_ctx::connects, and VT.
Referenced by main().
worker()
static void * worker (void * arg) static
Definition at line 95 of file cpool_unittest.c.
References brix_cpool_checkin(), brix_cpool_checkout(), brix_status_clear(), c, g_inflight, and g_p.
Referenced by test_contention_unique_issue().
Variable Documentation
g_close_ctx
fake_ctx* g_close_ctx static
Definition at line 35 of file cpool_unittest.c.
Referenced by fake_close_counting(), and test_destroy_closes_connected().
g_inflight
atomic_int g_inflight[64] static
Definition at line 93 of file cpool_unittest.c.
Referenced by test_contention_unique_issue(), and worker().
g_p
brix_cpool* g_p static
Definition at line 92 of file cpool_unittest.c.
Referenced by test_contention_unique_issue(), and worker().
VT
const brix_cpool_vtbl VT = { sizeof(fake_conn), fake_connect, fake_close } static
Definition at line 38 of file cpool_unittest.c.
Referenced by test_contention_unique_issue(), test_create_fails_on_bad_endpoint(), test_health_drop_reconnects(), and test_reuse().