nginx-xrootd: client/lib/net/cpool.c File Reference
cpool.c File Reference
#include "brix.h"
#include "net/cpool.h"
#include <pthread.h>
#include <stdlib.h>
Data Structures
struct cpool_slot
struct brix_cpool
Functions
static int cpool_slot_connect (brix_cpool *p, cpool_slot *s, brix_status *st)
brix_cpool * brix_cpool_create (const brix_cpool_vtbl *vt, void *ctx, int n, brix_status *st)
void * brix_cpool_checkout (brix_cpool *p, brix_status *st)
void brix_cpool_checkin (brix_cpool *p, void *conn, int healthy)
void brix_cpool_destroy (brix_cpool *p)
Function Documentation
brix_cpool_checkin()
void brix_cpool_checkin (brix_cpool * p, void * conn, int healthy)
Definition at line 143 of file cpool.c.
References brix_cpool::avail, brix_cpool_vtbl::close, cpool_slot::conn, cpool_slot::connected, cpool_slot::in_use, brix_cpool::lock, brix_cpool::n, brix_cpool::slots, and brix_cpool::vt.
Referenced by brix_pool_checkin(), brix_web_readdir_pooled(), brix_web_stat_pooled(), brixcvmfs_transport(), test_destroy_closes_connected(), test_health_drop_reconnects(), test_reuse(), and worker().
brix_cpool_checkout()
void * brix_cpool_checkout (brix_cpool * p, brix_status * st)
Definition at line 106 of file cpool.c.
References brix_cpool::avail, brix_status_set(), cpool_slot_connect(), cpool_slot::in_use, brix_cpool::lock, brix_cpool::n, s, brix_cpool::slots, and XRDC_EUSAGE.
Referenced by brix_pool_checkout(), brix_web_readdir_pooled(), brix_web_stat_pooled(), brixcvmfs_transport(), test_destroy_closes_connected(), test_health_drop_reconnects(), test_reuse(), and worker().
brix_cpool_create()
brix_cpool * brix_cpool_create (const brix_cpool_vtbl * vt, void * ctx, int n, brix_status * st)
Definition at line 51 of file cpool.c.
References brix_cpool::avail, brix_cpool_destroy(), brix_status_set(), brix_cpool_vtbl::close, cpool_slot::conn, brix_cpool_vtbl::conn_size, brix_cpool_vtbl::connect, cpool_slot_connect(), brix_cpool::ctx, cpool_slot::in_use, brix_cpool::lock, brix_cpool::n, brix_cpool::slots, brix_cpool::vt, XRDC_ESOCK, and XRDC_EUSAGE.
Referenced by aio_web_mount(), brix_pool_create(), brixcvmfs_open(), test_contention_unique_issue(), test_create_fails_on_bad_endpoint(), test_destroy_closes_connected(), test_health_drop_reconnects(), and test_reuse().
brix_cpool_destroy()
void brix_cpool_destroy (brix_cpool * p)
Definition at line 176 of file cpool.c.
References brix_cpool::avail, brix_cpool_vtbl::close, cpool_slot::conn, cpool_slot::connected, brix_cpool::lock, brix_cpool::n, brix_cpool::slots, and brix_cpool::vt.
Referenced by aio_web_mount(), brix_cpool_create(), brix_pool_destroy(), test_contention_unique_issue(), test_destroy_closes_connected(), test_health_drop_reconnects(), test_reuse(), and transport_cleanup().
cpool_slot_connect()
static int cpool_slot_connect (brix_cpool * p, cpool_slot * s, brix_status * st) static
Definition at line 38 of file cpool.c.
References brix_cpool_vtbl::connect, brix_cpool::ctx, s, and brix_cpool::vt.
Referenced by brix_cpool_checkout(), and brix_cpool_create().