nginx-xrootd: src/core/compat/crc64.c File Reference
crc64.c File Reference
#include "crc64.h"
Macros
#define BRIX_CRC64_XZ_POLY_REFL 0xC96C5795D7870F42ULL
#define BRIX_CRC64_NVME_POLY_REFL 0x9A6C9329AC4BC9B5ULL
#define BRIX_CRC64_TABLE_SIZE 256
#define BRIX_CRC64_GF2_DIM 64
Functions
static void brix_crc64_build_table (uint64_t *tab, uint64_t poly_refl)
static void brix_crc64_tables_init (void)
static const uint64_t * brix_crc64_table_for (brix_crc64_variant_t variant)
static uint64_t brix_crc64_poly_for (brix_crc64_variant_t variant)
uint64_t brix_crc64_extend (brix_crc64_variant_t variant, uint64_t crc, const void *buf, size_t len)
uint64_t brix_crc64_value (brix_crc64_variant_t variant, const void *buf, size_t len)
static uint64_t brix_crc64_gf2_times (const uint64_t *mat, uint64_t vec)
static void brix_crc64_gf2_square (uint64_t *square, const uint64_t *mat)
uint64_t brix_crc64_combine (brix_crc64_variant_t variant, uint64_t crc1, uint64_t crc2, uint64_t len2)
Variables
static uint64_t brix_crc64_xz_tab [256]
static uint64_t brix_crc64_nvme_tab [256]
Macro Definition Documentation
BRIX_CRC64_GF2_DIM
#define BRIX_CRC64_GF2_DIM 64
Definition at line 31 of file crc64.c.
BRIX_CRC64_NVME_POLY_REFL
#define BRIX_CRC64_NVME_POLY_REFL 0x9A6C9329AC4BC9B5ULL
Definition at line 28 of file crc64.c.
BRIX_CRC64_TABLE_SIZE
#define BRIX_CRC64_TABLE_SIZE 256
Definition at line 30 of file crc64.c.
BRIX_CRC64_XZ_POLY_REFL
#define BRIX_CRC64_XZ_POLY_REFL 0xC96C5795D7870F42ULL
Definition at line 27 of file crc64.c.
Function Documentation
brix_crc64_build_table()
static void brix_crc64_build_table (uint64_t * tab, uint64_t poly_refl) static
Definition at line 38 of file crc64.c.
References BRIX_CRC64_TABLE_SIZE.
Referenced by brix_crc64_tables_init().
brix_crc64_combine()
uint64_t brix_crc64_combine (brix_crc64_variant_t variant, uint64_t crc1, uint64_t crc2, uint64_t len2)
Definition at line 144 of file crc64.c.
References BRIX_CRC64_GF2_DIM, brix_crc64_gf2_square(), brix_crc64_gf2_times(), and brix_crc64_poly_for().
brix_crc64_extend()
uint64_t brix_crc64_extend (brix_crc64_variant_t variant, uint64_t crc, const void * buf, size_t len)
Definition at line 81 of file crc64.c.
References brix_crc64_table_for().
Referenced by brix_cksum_u64_obj(), and brix_crc64_value().
brix_crc64_gf2_square()
static void brix_crc64_gf2_square (uint64_t * square, const uint64_t * mat) static
Definition at line 134 of file crc64.c.
References BRIX_CRC64_GF2_DIM, and brix_crc64_gf2_times().
Referenced by brix_crc64_combine().
brix_crc64_gf2_times()
static uint64_t brix_crc64_gf2_times (const uint64_t * mat, uint64_t vec) static
Definition at line 118 of file crc64.c.
Referenced by brix_crc64_combine(), and brix_crc64_gf2_square().
brix_crc64_poly_for()
static uint64_t brix_crc64_poly_for (brix_crc64_variant_t variant) static
Definition at line 71 of file crc64.c.
References BRIX_CRC64_NVME, BRIX_CRC64_NVME_POLY_REFL, BRIX_CRC64_XZ, and BRIX_CRC64_XZ_POLY_REFL.
Referenced by brix_crc64_combine().
brix_crc64_table_for()
static const uint64_t * brix_crc64_table_for (brix_crc64_variant_t variant) static
Definition at line 61 of file crc64.c.
References BRIX_CRC64_NVME, brix_crc64_nvme_tab, BRIX_CRC64_XZ, and brix_crc64_xz_tab.
Referenced by brix_crc64_extend().
brix_crc64_tables_init()
static void brix_crc64_tables_init (void) static
Definition at line 54 of file crc64.c.
References brix_crc64_build_table(), BRIX_CRC64_NVME_POLY_REFL, brix_crc64_nvme_tab, BRIX_CRC64_XZ_POLY_REFL, and brix_crc64_xz_tab.
brix_crc64_value()
uint64_t brix_crc64_value (brix_crc64_variant_t variant, const void * buf, size_t len)
Definition at line 105 of file crc64.c.
References brix_crc64_extend().
Variable Documentation
brix_crc64_nvme_tab
uint64_t brix_crc64_nvme_tab[256] static
Definition at line 34 of file crc64.c.
Referenced by brix_crc64_table_for(), and brix_crc64_tables_init().
brix_crc64_xz_tab
uint64_t brix_crc64_xz_tab[256] static
Definition at line 33 of file crc64.c.
Referenced by brix_crc64_table_for(), and brix_crc64_tables_init().