nginx-xrootd: src/core/compat/crc64.h File Reference
crc64.h File Reference
#include <stddef.h>
#include <stdint.h>
Enumerations
enum brix_crc64_variant_t { BRIX_CRC64_XZ = 0 , BRIX_CRC64_NVME = 1 }
Functions
uint64_t brix_crc64_extend (brix_crc64_variant_t variant, uint64_t crc, const void *buf, size_t len)
uint64_t brix_crc64_value (brix_crc64_variant_t variant, const void *buf, size_t len)
uint64_t brix_crc64_combine (brix_crc64_variant_t variant, uint64_t crc1, uint64_t crc2, uint64_t len2)
Enumeration Type Documentation
brix_crc64_variant_t
enum brix_crc64_variant_t
Enumerator
BRIX_CRC64_XZ
BRIX_CRC64_NVME
Definition at line 38 of file crc64.h.
Function Documentation
brix_crc64_combine()
uint64_t brix_crc64_combine (brix_crc64_variant_t variant, uint64_t crc1, uint64_t crc2, uint64_t len2)
Definition at line 144 of file crc64.c.
References BRIX_CRC64_GF2_DIM, brix_crc64_gf2_square(), brix_crc64_gf2_times(), and brix_crc64_poly_for().
brix_crc64_extend()
uint64_t brix_crc64_extend (brix_crc64_variant_t variant, uint64_t crc, const void * buf, size_t len)
Definition at line 81 of file crc64.c.
References brix_crc64_table_for().
Referenced by brix_cksum_u64_obj_range(), and brix_crc64_value().
brix_crc64_value()
uint64_t brix_crc64_value (brix_crc64_variant_t variant, const void * buf, size_t len)
Definition at line 105 of file crc64.c.
References brix_crc64_extend().