nginx-xrootd: src/core/config/credential_block.h File Reference
credential_block.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
Data Structures
struct brix_credential_t
Functions
char * brix_conf_credential_block (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
const brix_credential_t * brix_credential_lookup (const char *name)
ngx_int_t brix_credential_bearer (const brix_credential_t *cred, char *out, size_t cap, ngx_log_t *log)
Function Documentation
brix_conf_credential_block()
char * brix_conf_credential_block (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 124 of file credential_block.c.
References brix_credential_count, brix_credential_line(), brix_credential_lookup(), BRIX_CREDENTIAL_MAX, brix_credentials, brix_pstrdup_z(), brix_credential_t::last_def_cycle, and brix_credential_t::name.
brix_credential_bearer()
ngx_int_t brix_credential_bearer (const brix_credential_t * cred, char * out, size_t cap, ngx_log_t * log)
Definition at line 194 of file credential_block.c.
References close(), log, open(), read(), brix_credential_t::token, and brix_credential_t::token_file.
Referenced by brix_server_set_storage_credential(), brix_server_set_wt_credential(), s3_export_attach_credential(), tier_resolve_creds(), and webdav_set_storage_credential().
brix_credential_lookup()
const brix_credential_t * brix_credential_lookup (const char * name)
Definition at line 20 of file credential_block.c.
References brix_credential_count, brix_credentials, brix_credential_t::name, and name.
Referenced by brix_conf_credential_block(), brix_init_server_backend_credential(), brix_server_set_storage_credential(), brix_server_set_wt_credential(), s3_export_attach_credential(), tier_parse_args(), and webdav_set_storage_credential().