nginx-xrootd: src/core/config/credential_block.c File Reference
credential_block.c File Reference
#include "credential_block.h"
#include "core/compat/cstr.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "fs/backend/sd.h"
#include <fcntl.h>
#include <string.h>
#include <unistd.h>
Data Structures
struct brix_credential_field_t
Macros
#define BRIX_CREDENTIAL_MAX 32
#define CRED_STR(k, f) { k, offsetof(brix_credential_t, f), (size_t) -1 }
#define CRED_FLAG(k, f) { k, (size_t) -1, offsetof(brix_credential_t, f) }
Functions
const brix_credential_t * brix_credential_lookup (const char *name)
static ngx_int_t brix_credential_mode_token (const ngx_str_t *tok)
static char * brix_credential_line (ngx_conf_t *cf, ngx_command_t *dummy, void *conf)
char * brix_conf_credential_block (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static const char * brix_credential_str_or_null (const ngx_str_t *s)
ngx_int_t brix_credential_to_backend_cred (const brix_credential_t *cred, char *bearer_buf, size_t bearer_cap, struct brix_vfs_backend_cred_s *out, ngx_log_t *log)
ngx_int_t brix_credential_bearer (const brix_credential_t *cred, char *out, size_t cap, ngx_log_t *log)
Variables
static brix_credential_t brix_credentials [32]
static ngx_uint_t brix_credential_count
static const brix_credential_field_t brix_credential_fields []
Macro Definition Documentation
BRIX_CREDENTIAL_MAX
#define BRIX_CREDENTIAL_MAX 32
Definition at line 17 of file credential_block.c.
CRED_FLAG
#define CRED_FLAG (k, f) { k, (size_t) -1, offsetof(brix_credential_t, f) }
Definition at line 52 of file credential_block.c.
CRED_STR
#define CRED_STR (k, f) { k, offsetof(brix_credential_t, f), (size_t) -1 }
Definition at line 51 of file credential_block.c.
Function Documentation
brix_conf_credential_block()
char * brix_conf_credential_block (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 177 of file credential_block.c.
References brix_credential_count, brix_credential_line(), brix_credential_lookup(), BRIX_CREDENTIAL_MAX, brix_credentials, brix_pstrdup_z(), brix_credential_t::last_def_cycle, brix_credential_t::mode, and brix_credential_t::name.
brix_credential_bearer()
ngx_int_t brix_credential_bearer (const brix_credential_t * cred, char * out, size_t cap, ngx_log_t * log)
Definition at line 313 of file credential_block.c.
References close(), log, open(), read(), brix_credential_t::token, and brix_credential_t::token_file.
Referenced by brix_credential_to_backend_cred(), brix_server_set_wt_credential(), and tier_resolve_creds().
brix_credential_line()
static char * brix_credential_line (ngx_conf_t * cf, ngx_command_t * dummy, void * conf) static
Definition at line 103 of file credential_block.c.
References brix_credential_fields, brix_credential_mode_token(), brix_pstrdup_z(), brix_credential_field_t::flag_off, brix_credential_field_t::key, brix_credential_t::mode, and brix_credential_field_t::str_off.
Referenced by brix_conf_credential_block().
brix_credential_lookup()
const brix_credential_t * brix_credential_lookup (const char * name)
Definition at line 22 of file credential_block.c.
References brix_credential_count, brix_credentials, brix_credential_t::name, and name.
Referenced by brix_conf_credential_block(), brix_ftp_init_process(), brix_ftp_install_backend_credential(), brix_init_server_backend_credential(), brix_server_set_storage_credential(), brix_server_set_wt_credential(), s3_export_attach_credential(), tier_parse_args(), and webdav_set_storage_credential().
brix_credential_mode_token()
static ngx_int_t brix_credential_mode_token (const ngx_str_t * tok) static
Definition at line 80 of file credential_block.c.
References BRIX_CRED_AUTO, BRIX_CRED_DELEGATE, BRIX_CRED_EXCHANGE, BRIX_CRED_MINT, BRIX_CRED_PASSTHROUGH, BRIX_CRED_SELECT, and tok.
Referenced by brix_credential_line().
brix_credential_str_or_null()
static const char * brix_credential_str_or_null (const ngx_str_t * s) static
Definition at line 258 of file credential_block.c.
References s.
Referenced by brix_credential_to_backend_cred().
brix_credential_to_backend_cred()
ngx_int_t brix_credential_to_backend_cred (const brix_credential_t * cred, char * bearer_buf, size_t bearer_cap, struct brix_vfs_backend_cred_s * out, ngx_log_t * log)
Definition at line 284 of file credential_block.c.
References brix_credential_bearer(), brix_credential_str_or_null(), brix_credential_t::ca_dir, log, brix_credential_t::s3_access_key, brix_credential_t::s3_region, brix_credential_t::s3_secret_key, brix_credential_t::sss_keytab, brix_credential_t::x509_cert, brix_credential_t::x509_key, and brix_credential_t::x509_proxy.
Referenced by brix_ftp_init_process(), brix_ftp_install_backend_credential(), brix_init_server_backend_credential(), brix_server_set_storage_credential(), s3_export_attach_credential(), and webdav_set_storage_credential().
Variable Documentation
brix_credential_count
ngx_uint_t brix_credential_count static
Definition at line 19 of file credential_block.c.
Referenced by brix_conf_credential_block(), and brix_credential_lookup().
brix_credential_fields
const brix_credential_field_t brix_credential_fields[] static
Initial value:
= {
    {  "x509_proxy" , offsetof(brix_credential_t,  x509_proxy ), (size_t) -1 },
    {  "x509_cert" , offsetof(brix_credential_t,  x509_cert ), (size_t) -1 },
    {  "x509_key" , offsetof(brix_credential_t,  x509_key ), (size_t) -1 },
    {  "ca_dir" , offsetof(brix_credential_t,  ca_dir ), (size_t) -1 },
    {  "token" , offsetof(brix_credential_t,  token ), (size_t) -1 },
    {  "token_file" , offsetof(brix_credential_t,  token_file ), (size_t) -1 },
    {  "vo" , offsetof(brix_credential_t,  vo ), (size_t) -1 },
    {  "s3_access_key" , offsetof(brix_credential_t,  s3_access_key ), (size_t) -1 },
    {  "s3_secret_key" , offsetof(brix_credential_t,  s3_secret_key ), (size_t) -1 },
    {  "s3_region" , offsetof(brix_credential_t,  s3_region ), (size_t) -1 },
    {  "sss_keytab" , offsetof(brix_credential_t,  sss_keytab ), (size_t) -1 },
    {  "token_forward" , (size_t) -1, offsetof(brix_credential_t,  token_forward ) },
    {  "tls" , (size_t) -1, offsetof(brix_credential_t,  tls ) },
    { NULL, 0, 0 },
}
Definition at line 54 of file credential_block.c.
Referenced by brix_credential_line().
brix_credentials
brix_credential_t brix_credentials[32] static
Definition at line 18 of file credential_block.c.
Referenced by brix_conf_credential_block(), and brix_credential_lookup().