nginx-xrootd: src/tpc/common/credential.h File Reference
credential.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include "core/types/identity.h"
Data Structures
struct brix_tpc_credential_t
Enumerations
enum brix_tpc_credential_type_t { BRIX_TPC_CREDENTIAL_NONE = 0 , BRIX_TPC_CREDENTIAL_PROXY = 1 , BRIX_TPC_CREDENTIAL_TOKEN = 2 }
Functions
ngx_int_t brix_tpc_credential_parse (const ngx_str_t *raw_credential, brix_tpc_credential_type_t hint, brix_tpc_credential_t *cred, ngx_pool_t *pool, ngx_log_t *log)
ngx_int_t brix_tpc_credential_validate (const brix_tpc_credential_t *cred, ngx_log_t *log)
const char * brix_tpc_credential_type_name (brix_tpc_credential_type_t type)
Enumeration Type Documentation
brix_tpc_credential_type_t
enum brix_tpc_credential_type_t
Enumerator
BRIX_TPC_CREDENTIAL_NONE
BRIX_TPC_CREDENTIAL_PROXY
BRIX_TPC_CREDENTIAL_TOKEN
Definition at line 31 of file credential.h.
Function Documentation
brix_tpc_credential_parse()
ngx_int_t brix_tpc_credential_parse (const ngx_str_t * raw_credential, brix_tpc_credential_type_t hint, brix_tpc_credential_t * cred, ngx_pool_t * pool, ngx_log_t * log)
Definition at line 117 of file credential.c.
References brix_tpc_credential_t::bearer, brix_tpc_copy_credential_str(), BRIX_TPC_CREDENTIAL_NONE, BRIX_TPC_CREDENTIAL_PROXY, BRIX_TPC_CREDENTIAL_TOKEN, brix_tpc_starts_with(), brix_tpc_str_equals(), log, brix_tpc_credential_t::proxy_pem, and brix_tpc_credential_t::type.
Referenced by tpc_token_validate_delegated(), and webdav_tpc_cred_validate_token().
brix_tpc_credential_type_name()
const char * brix_tpc_credential_type_name (brix_tpc_credential_type_t type)
Definition at line 94 of file credential.c.
References BRIX_TPC_CREDENTIAL_NONE, BRIX_TPC_CREDENTIAL_PROXY, and BRIX_TPC_CREDENTIAL_TOKEN.
Referenced by brix_tpc_credential_validate().
brix_tpc_credential_validate()
ngx_int_t brix_tpc_credential_validate (const brix_tpc_credential_t * cred, ngx_log_t * log)
Definition at line 195 of file credential.c.
References brix_tpc_credential_t::bearer, BRIX_TPC_CREDENTIAL_NONE, BRIX_TPC_CREDENTIAL_PROXY, BRIX_TPC_CREDENTIAL_TOKEN, brix_tpc_credential_type_name(), brix_tpc_credential_t::expires_at, log, brix_tpc_credential_t::proxy_pem, and brix_tpc_credential_t::type.
Referenced by tpc_outbound_gsi(), tpc_token_validate_delegated(), and webdav_tpc_cred_validate_token().