nginx-xrootd: client/lib/auth/cred/cred.h File Reference
cred.h File Reference
#include "brix.h"
#include <stdint.h>
Data Structures
struct brix_cred_view
struct brix_cred_config
struct brix_cred_handler
Enumerations
enum brix_cred_kind {
XRDC_CRED_X509_PROXY = 0 , XRDC_CRED_BEARER , XRDC_CRED_KRB5 , XRDC_CRED_SSS ,
XRDC_CRED_S3KEYS , XRDC_CRED_KIND_COUNT
}
Functions
brix_cred_store * brix_cred_store_new (const brix_cred_config *cfg)
void brix_cred_store_free (brix_cred_store *s)
int brix_cred_acquire (brix_cred_store *s, brix_cred_kind kind, int min_remaining_s, brix_cred_view *view, brix_status *st)
int brix_cred_available (brix_cred_store *s, brix_cred_kind kind)
const brix_cred_handler * brix_cred_x509 (void)
const brix_cred_handler * brix_cred_bearer (void)
const brix_cred_handler * brix_cred_krb5 (void)
const brix_cred_handler * brix_cred_sss (void)
const brix_cred_handler * brix_cred_s3keys (void)
Enumeration Type Documentation
brix_cred_kind
enum brix_cred_kind
Enumerator
XRDC_CRED_X509_PROXY
XRDC_CRED_BEARER
XRDC_CRED_KRB5
XRDC_CRED_SSS
XRDC_CRED_S3KEYS
XRDC_CRED_KIND_COUNT
Definition at line 23 of file cred.h.
Function Documentation
brix_cred_acquire()
int brix_cred_acquire (brix_cred_store * s, brix_cred_kind kind, int min_remaining_s, brix_cred_view * view, brix_status * st)
Definition at line 414 of file cred.c.
References brix_status_set(), do_acquire(), kind_name(), cred_slot::loaded, brix_cred_handler::refresh, s, should_refresh(), cred_slot::view, XRDC_CRED_KIND_COUNT, XRDC_EAUTH, and XRDC_EUSAGE.
Referenced by auth_hdr_bearer(), gsi_resolve_proxy(), s3_resolve_keys(), sss_first(), and token_first().
brix_cred_available()
int brix_cred_available (brix_cred_store * s, brix_cred_kind kind)
Definition at line 326 of file cred.c.
References brix_cred_handler::available, s, and XRDC_CRED_KIND_COUNT.
Referenced by gsi_have(), sss_have(), and token_have().
brix_cred_bearer()
const brix_cred_handler * brix_cred_bearer (void)
Definition at line 241 of file cred_bearer.c.
brix_cred_krb5()
const brix_cred_handler * brix_cred_krb5 (void)
Definition at line 264 of file cred_krb5.c.
brix_cred_s3keys()
const brix_cred_handler * brix_cred_s3keys (void)
Definition at line 358 of file cred_s3.c.
brix_cred_sss()
const brix_cred_handler * brix_cred_sss (void)
Definition at line 152 of file cred_sss.c.
brix_cred_store_free()
void brix_cred_store_free (brix_cred_store * s)
Definition at line 303 of file cred.c.
brix_cred_store_new()
brix_cred_store * brix_cred_store_new (const brix_cred_config * cfg)
Definition at line 261 of file cred.c.
References brix_cred_bearer(), brix_cred_krb5(), brix_cred_s3keys(), brix_cred_sss(), brix_cred_x509(), cfg_copy_alloc(), s, XRDC_CRED_BEARER, XRDC_CRED_KRB5, XRDC_CRED_S3KEYS, XRDC_CRED_SSS, and XRDC_CRED_X509_PROXY.
Referenced by brix_cli_cred_store_build().
brix_cred_x509()
const brix_cred_handler * brix_cred_x509 (void)
Definition at line 232 of file cred_x509.c.