nginx-xrootd: client/lib/auth/cred/cred_bearer.c File Reference
cred_bearer.c File Reference
#include "cred.h"
#include "brix.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Macros
#define _GNU_SOURCE
Functions
static char * slurp_credfile (const char *path)
static char * obtain_token (const brix_cred_config *cfg)
static int bearer_available (const brix_cred_config *cfg)
static int bearer_acquire (const brix_cred_config *cfg, brix_cred_view *out, int64_t *not_after, brix_status *st)
static int bearer_refresh (const brix_cred_config *cfg, brix_status *st)
const brix_cred_handler * brix_cred_bearer (void)
Variables
static char * g_tok = NULL
static const brix_cred_handler s_bearer_handler
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 27 of file cred_bearer.c.
Function Documentation
bearer_acquire()
static int bearer_acquire (const brix_cred_config * cfg, brix_cred_view * out, int64_t * not_after, brix_status * st) static
Definition at line 173 of file cred_bearer.c.
References brix_status_set(), brix_token_meta_get(), brix_token_meta::exp, g_tok, brix_cred_view::kind, brix_cred_view::not_after, obtain_token(), brix_cred_view::path, brix_cred_view::s3_access, brix_cred_view::s3_secret, brix_cred_view::token, XRDC_CRED_BEARER, and XRDC_EAUTH.
bearer_available()
static int bearer_available (const brix_cred_config * cfg) static
Definition at line 149 of file cred_bearer.c.
References obtain_token().
bearer_refresh()
static int bearer_refresh (const brix_cred_config * cfg, brix_status * st) static
Definition at line 217 of file cred_bearer.c.
brix_cred_bearer()
const brix_cred_handler * brix_cred_bearer (void)
Definition at line 241 of file cred_bearer.c.
References s_bearer_handler.
Referenced by brix_cred_store_new().
obtain_token()
static char * obtain_token (const brix_cred_config * cfg) static
Definition at line 128 of file cred_bearer.c.
References brix_cred_config::bearer_literal, brix_cred_config::bearer_path, brix_token_discover(), and slurp_credfile().
Referenced by bearer_acquire(), and bearer_available().
slurp_credfile()
static char * slurp_credfile (const char * path) static
Definition at line 67 of file cred_bearer.c.
References brix_open_credfile(), and close().
Referenced by obtain_token().
Variable Documentation
g_tok
char* g_tok = NULL static
Definition at line 52 of file cred_bearer.c.
Referenced by bearer_acquire().
s_bearer_handler
const brix_cred_handler s_bearer_handler static
Initial value:
= {
    .kind      = XRDC_CRED_BEARER,
    .available = bearer_available,
    .acquire   = bearer_acquire,
    .refresh   = bearer_refresh,
}
Definition at line 225 of file cred_bearer.c.
Referenced by brix_cred_bearer().