nginx-xrootd: client/lib/auth/cred/credinfo.c File Reference
credinfo.c File Reference
#include "brix.h"
#include "auth/token/b64url.h"
#include "auth/token/scopes.h"
#include "core/compat/json_min.h"
#include "cli/cli_hint.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <openssl/bio.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
Macros
#define VOMS_AC_OID "1.3.6.1.4.1.8005.100.100.5"
Functions
static ssize_t decode_payload_json (const char *jwt, char *out, size_t outsz)
static int json_str (const char *json, const char *key, char *out, size_t outsz)
void brix_token_explain (const char *jwt, FILE *out)
static void token_meta_apply_exp (const char *json, brix_token_meta *m)
static void token_scope_from_parsed (const brix_token_scope_t *sc, int nsc, brix_token_meta *m)
static void token_scope_from_heuristic (const char *scope, brix_token_meta *m)
static void token_meta_apply_scope (const char *json, brix_token_meta *m)
void brix_token_meta_get (const char *jwt, brix_token_meta *m)
static void voms_scan (const unsigned char *der, int len, FILE *out)
void brix_gsi_cert_explain (const char *proxy_path, FILE *out)
static int diagnose_token (int want_write, const char *prefix, FILE *out)
static int diagnose_proxy (const char *prefix, FILE *out)
int brix_cred_diagnose (int want_write, const char *prefix, FILE *out)
void brix_cred_hint_for_status_url (const brix_status *st, int want_write, FILE *out, const char *url_str)
void brix_cred_hint_for_status (const brix_status *st, int want_write, FILE *out)
Macro Definition Documentation
VOMS_AC_OID
#define VOMS_AC_OID "1.3.6.1.4.1.8005.100.100.5"
Definition at line 235 of file credinfo.c.
Function Documentation
brix_cred_diagnose()
int brix_cred_diagnose (int want_write, const char * prefix, FILE * out)
Definition at line 437 of file credinfo.c.
References diagnose_proxy(), and diagnose_token().
Referenced by brix_cred_hint_for_status_url(), build_and_preflight_credentials(), doctor_report_creds(), and xrd_login().
brix_cred_hint_for_status()
void brix_cred_hint_for_status (const brix_status * st, int want_write, FILE * out)
Definition at line 487 of file credinfo.c.
References brix_cred_hint_for_status_url().
Referenced by do_rm().
brix_cred_hint_for_status_url()
void brix_cred_hint_for_status_url (const brix_status * st, int want_write, FILE * out, const char * url_str)
Definition at line 473 of file credinfo.c.
References brix_cred_diagnose(), brix_hint_doctor_referral(), brix_status::kxr, kXR_AuthFailed, and kXR_NotAuthorized.
Referenced by brix_cred_hint_for_status(), brix_report_err(), xrdcp_hint_failed_source(), xrdfs_op_hints(), and xrdfs_web_hints().
brix_gsi_cert_explain()
void brix_gsi_cert_explain (const char * proxy_path, FILE * out)
Definition at line 267 of file credinfo.c.
References brix_credfile_bio(), proxy_path(), VOMS_AC_OID, and voms_scan().
Referenced by chk_probe_cred_validity(), doctor_report_creds(), explain_env_credentials(), remote_doctor_report_creds(), and xrd_whoami().
brix_token_explain()
void brix_token_explain (const char * jwt, FILE * out)
Definition at line 73 of file credinfo.c.
References decode_payload_json(), and json_str().
Referenced by chk_probe_cred_validity(), doctor_report_creds(), explain_env_credentials(), remote_doctor_report_creds(), and xrd_whoami().
brix_token_meta_get()
void brix_token_meta_get (const char * jwt, brix_token_meta * m)
Definition at line 213 of file credinfo.c.
References decode_payload_json(), token_meta_apply_exp(), token_meta_apply_scope(), and brix_token_meta::valid.
Referenced by auth_suite_token_probes(), bearer_acquire(), diagnose_token(), and token_needs_refresh().
decode_payload_json()
static ssize_t decode_payload_json (const char * jwt, char * out, size_t outsz) static
Definition at line 44 of file credinfo.c.
References b64url_decode(), and xrdjwt_split().
Referenced by brix_token_explain(), and brix_token_meta_get().
diagnose_proxy()
static int diagnose_proxy (const char * prefix, FILE * out) static
Definition at line 402 of file credinfo.c.
References access(), brix_proxy_default_path(), and brix_proxy_remaining().
Referenced by brix_cred_diagnose().
diagnose_token()
static int diagnose_token (int want_write, const char * prefix, FILE * out) static
Definition at line 353 of file credinfo.c.
References brix_token_discover(), brix_token_meta_get(), brix_token_meta::exp, brix_token_meta::expired, brix_token_meta::has_scope, brix_token_meta::has_write, and brix_token_meta::valid.
Referenced by brix_cred_diagnose().
json_str()
static int json_str (const char * json, const char * key, char * out, size_t outsz) static
Definition at line 67 of file credinfo.c.
References brix_json_get_str(), and key.
Referenced by brix_token_explain(), token_meta_apply_exp(), and token_meta_apply_scope().
token_meta_apply_exp()
static void token_meta_apply_exp (const char * json, brix_token_meta * m) static
Definition at line 112 of file credinfo.c.
References brix_token_meta::exp, brix_token_meta::expired, and json_str().
Referenced by brix_token_meta_get().
token_meta_apply_scope()
static void token_meta_apply_scope (const char * json, brix_token_meta * m) static
Definition at line 180 of file credinfo.c.
References brix_token_parse_scopes(), brix_token_meta::has_scope, json_str(), scope, token_scope_from_heuristic(), and token_scope_from_parsed().
Referenced by brix_token_meta_get().
token_scope_from_heuristic()
static void token_scope_from_heuristic (const char * scope, brix_token_meta * m) static
Definition at line 157 of file credinfo.c.
References brix_token_meta::has_read, brix_token_meta::has_write, and scope.
Referenced by token_meta_apply_scope().
token_scope_from_parsed()
static void token_scope_from_parsed (const brix_token_scope_t * sc, int nsc, brix_token_meta * m) static
Definition at line 135 of file credinfo.c.
References brix_token_meta::has_read, brix_token_meta::has_write, and read().
Referenced by token_meta_apply_scope().
voms_scan()
static void voms_scan (const unsigned char * der, int len, FILE * out) static
Definition at line 240 of file credinfo.c.
Referenced by brix_gsi_cert_explain().