nginx-xrootd: client/lib/auth/cred/cred_s3.c File Reference
cred_s3.c File Reference
#include "cred.h"
#include "brix.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
Macros
#define _GNU_SOURCE
#define S3KEY_BUFSZ 512
Functions
static char * trim_inplace (char *s)
static int parse_ini_key_value (char *buf, const char *key, char *out, size_t outsz)
static int parse_aws_credentials_default (const char *path, char *access_out, size_t access_sz, char *secret_out, size_t secret_sz)
static int try_credentials_file (char *access_out, size_t access_sz, char *secret_out, size_t secret_sz)
static int discover_s3_keys (const brix_cred_config *cfg, char *access_out, size_t access_sz, char *secret_out, size_t secret_sz)
static int s3keys_available (const brix_cred_config *cfg)
static int s3keys_acquire (const brix_cred_config *cfg, brix_cred_view *out, int64_t *not_after, brix_status *st)
const brix_cred_handler * brix_cred_s3keys (void)
Variables
static const brix_cred_handler s_s3keys_handler
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 36 of file cred_s3.c.
S3KEY_BUFSZ
#define S3KEY_BUFSZ 512
Definition at line 47 of file cred_s3.c.
Function Documentation
brix_cred_s3keys()
const brix_cred_handler * brix_cred_s3keys (void)
Definition at line 332 of file cred_s3.c.
References s_s3keys_handler.
Referenced by brix_cred_store_new().
discover_s3_keys()
static int discover_s3_keys (const brix_cred_config * cfg, char * access_out, size_t access_sz, char * secret_out, size_t secret_sz) static
Definition at line 226 of file cred_s3.c.
References brix_cred_config::s3_access, brix_cred_config::s3_secret, and try_credentials_file().
Referenced by s3keys_acquire(), and s3keys_available().
parse_aws_credentials_default()
static int parse_aws_credentials_default (const char * path, char * access_out, size_t access_sz, char * secret_out, size_t secret_sz) static
Definition at line 126 of file cred_s3.c.
References parse_ini_key_value(), S3KEY_BUFSZ, and trim_inplace().
Referenced by try_credentials_file().
parse_ini_key_value()
static int parse_ini_key_value (char * buf, const char * key, char * out, size_t outsz) static
Definition at line 89 of file cred_s3.c.
References key, and trim_inplace().
Referenced by parse_aws_credentials_default().
s3keys_acquire()
static int s3keys_acquire (const brix_cred_config * cfg, brix_cred_view * out, int64_t * not_after, brix_status * st) static
Definition at line 289 of file cred_s3.c.
References brix_status_set(), discover_s3_keys(), brix_cred_view::kind, brix_cred_view::path, brix_cred_view::s3_access, brix_cred_view::s3_secret, S3KEY_BUFSZ, brix_cred_view::token, XRDC_CRED_S3KEYS, and XRDC_EAUTH.
s3keys_available()
static int s3keys_available (const brix_cred_config * cfg) static
Definition at line 265 of file cred_s3.c.
References access(), discover_s3_keys(), and S3KEY_BUFSZ.
trim_inplace()
static char * trim_inplace (char * s) static
Definition at line 60 of file cred_s3.c.
References s.
Referenced by parse_aws_credentials_default(), and parse_ini_key_value().
try_credentials_file()
static int try_credentials_file (char * access_out, size_t access_sz, char * secret_out, size_t secret_sz) static
Definition at line 199 of file cred_s3.c.
References parse_aws_credentials_default(), and XRDC_PATH_MAX.
Referenced by discover_s3_keys().
Variable Documentation
s_s3keys_handler
const brix_cred_handler s_s3keys_handler static
Initial value:
= {
    .kind      = XRDC_CRED_S3KEYS,
    .available = s3keys_available,
    .acquire   = s3keys_acquire,
    .refresh   = NULL,
}
Definition at line 316 of file cred_s3.c.
Referenced by brix_cred_s3keys().