nginx-xrootd: src/fs/backend/cred_mint_internal.h File Reference
cred_mint_internal.h File Reference
#include "cred_mint.h"
#include <openssl/evp.h>
#include <openssl/x509.h>
Data Structures
struct mint_ca_t
struct mint_material_t
Macros
#define MINT_LOG(level, log, err, ...) do { if ((log) != NULL) { ngx_log_error(level, log, err, __VA_ARGS__); } } while (0)
Functions
int mint_build_cert (const mint_ca_t *ca, const char *principal, int ttl_secs, mint_material_t *out, ngx_log_t *log)
Macro Definition Documentation
MINT_LOG
#define MINT_LOG (level, log, err, ...) do { if ((log) != NULL) { ngx_log_error(level, log, err, __VA_ARGS__); } } while (0)
Definition at line 37 of file cred_mint_internal.h.
Function Documentation
mint_build_cert()
int mint_build_cert (const mint_ca_t * ca, const char * principal, int ttl_secs, mint_material_t * out, ngx_log_t * log)
Definition at line 172 of file cred_mint_cert.c.
References mint_ca_t::cert, mint_material_t::cert, mint_ca_t::key, mint_material_t::key, key, log, MINT_LOG, mint_make_subject(), mint_populate_cert(), mint_sanitize_cn(), mint_serial_from_rand(), and mint_cert_spec_t::subj.
Referenced by mint_generate().