nginx-xrootd: src/core/compat/cred_stage.h File Reference
cred_stage.h File Reference
#include <stddef.h>
Functions
int brix_cred_stage_dir (char *out, size_t outsz)
int brix_cred_stage_write (const char *prefix, const void *bytes, size_t len, char *path_out, size_t path_outsz)
Function Documentation
brix_cred_stage_dir()
int brix_cred_stage_dir (char * out, size_t outsz)
Definition at line 27 of file cred_stage.c.
References BRIX_CRED_STAGE_BASE, lstat(), and stat().
Referenced by brix_cred_stage_write().
brix_cred_stage_write()
int brix_cred_stage_write (const char * prefix, const void * bytes, size_t len, char * path_out, size_t path_outsz)
Definition at line 67 of file cred_stage.c.
References brix_cred_stage_dir(), and close().
Referenced by brix_proxy_gsi_write_pem_temp(), tpc_cred_rfc8693_exchange(), and tpc_rfc8693_stage_body().