nginx-xrootd: src/tpc/common/credential.c File Reference
credential.c File Reference
#include "credential.h"
#include <string.h>
Functions
static ngx_int_t brix_tpc_copy_credential_str (ngx_str_t *dst, const u_char *data, size_t len, ngx_pool_t *pool)
static ngx_flag_t brix_tpc_str_equals (const u_char *data, size_t len, const char *literal)
static ngx_flag_t brix_tpc_starts_with (const u_char *data, size_t len, const char *prefix)
const char * brix_tpc_credential_type_name (brix_tpc_credential_type_t type)
ngx_int_t brix_tpc_credential_parse (const ngx_str_t *raw_credential, brix_tpc_credential_type_t hint, brix_tpc_credential_t *cred, ngx_pool_t *pool, ngx_log_t *log)
ngx_int_t brix_tpc_credential_validate (const brix_tpc_credential_t *cred, ngx_log_t *log)
Function Documentation
brix_tpc_copy_credential_str()
static ngx_int_t brix_tpc_copy_credential_str (ngx_str_t * dst, const u_char * data, size_t len, ngx_pool_t * pool) static
Definition at line 30 of file credential.c.
Referenced by brix_tpc_credential_parse().
brix_tpc_credential_parse()
ngx_int_t brix_tpc_credential_parse (const ngx_str_t * raw_credential, brix_tpc_credential_type_t hint, brix_tpc_credential_t * cred, ngx_pool_t * pool, ngx_log_t * log)
Definition at line 117 of file credential.c.
References brix_tpc_credential_t::bearer, brix_tpc_copy_credential_str(), BRIX_TPC_CREDENTIAL_NONE, BRIX_TPC_CREDENTIAL_PROXY, BRIX_TPC_CREDENTIAL_TOKEN, brix_tpc_starts_with(), brix_tpc_str_equals(), log, brix_tpc_credential_t::proxy_pem, and brix_tpc_credential_t::type.
Referenced by tpc_token_validate_delegated(), and webdav_tpc_cred_validate_token().
brix_tpc_credential_type_name()
const char * brix_tpc_credential_type_name (brix_tpc_credential_type_t type)
Definition at line 94 of file credential.c.
References BRIX_TPC_CREDENTIAL_NONE, BRIX_TPC_CREDENTIAL_PROXY, and BRIX_TPC_CREDENTIAL_TOKEN.
Referenced by brix_tpc_credential_validate().
brix_tpc_credential_validate()
ngx_int_t brix_tpc_credential_validate (const brix_tpc_credential_t * cred, ngx_log_t * log)
Definition at line 195 of file credential.c.
References brix_tpc_credential_t::bearer, BRIX_TPC_CREDENTIAL_NONE, BRIX_TPC_CREDENTIAL_PROXY, BRIX_TPC_CREDENTIAL_TOKEN, brix_tpc_credential_type_name(), brix_tpc_credential_t::expires_at, log, brix_tpc_credential_t::proxy_pem, and brix_tpc_credential_t::type.
Referenced by tpc_outbound_gsi(), tpc_token_validate_delegated(), and webdav_tpc_cred_validate_token().
brix_tpc_starts_with()
static ngx_flag_t brix_tpc_starts_with (const u_char * data, size_t len, const char * prefix) static
Definition at line 78 of file credential.c.
Referenced by brix_tpc_credential_parse().
brix_tpc_str_equals()
static ngx_flag_t brix_tpc_str_equals (const u_char * data, size_t len, const char * literal) static
Definition at line 63 of file credential.c.
Referenced by brix_tpc_credential_parse().