nginx-xrootd: client/lib/auth/cred/credrefresh.c File Reference
credrefresh.c File Reference
#include "brix.h"
#include "core/compat/subprocess.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <sys/wait.h>
#include <sys/types.h>
Macros
#define XRDC_CRED_MARGIN_SECS 300
Functions
static int run_oidc_token (const char *account, char *out, size_t outsz, brix_status *st)
static int gsi_cert_available (void)
static int token_needs_refresh (void)
static int refresh_bearer_token (const char *account, int verbose, FILE *out)
static int proxy_is_stale (const char *pxp)
static int refresh_gsi_proxy (int verbose, FILE *out)
int brix_cred_autorefresh (int want_write, const char *oidc_account, int verbose, FILE *out)
Macro Definition Documentation
XRDC_CRED_MARGIN_SECS
#define XRDC_CRED_MARGIN_SECS 300
Definition at line 36 of file credrefresh.c.
Function Documentation
brix_cred_autorefresh()
int brix_cred_autorefresh (int want_write, const char * oidc_account, int verbose, FILE * out)
Definition at line 252 of file credrefresh.c.
References refresh_bearer_token(), and refresh_gsi_proxy().
Referenced by build_and_preflight_credentials(), and xrd_login().
gsi_cert_available()
static int gsi_cert_available (void) static
Definition at line 85 of file credrefresh.c.
References access().
Referenced by refresh_gsi_proxy().
proxy_is_stale()
static int proxy_is_stale (const char * pxp) static
Definition at line 183 of file credrefresh.c.
References access(), brix_proxy_remaining(), and XRDC_CRED_MARGIN_SECS.
Referenced by refresh_gsi_proxy().
refresh_bearer_token()
static int refresh_bearer_token (const char * account, int verbose, FILE * out) static
Definition at line 143 of file credrefresh.c.
References brix_status_clear(), brix_status::msg, run_oidc_token(), tok, and token_needs_refresh().
Referenced by brix_cred_autorefresh().
refresh_gsi_proxy()
static int refresh_gsi_proxy (int verbose, FILE * out) static
Definition at line 213 of file credrefresh.c.
References brix_proxy_create(), brix_proxy_default_path(), brix_status_clear(), gsi_cert_available(), brix_status::msg, and proxy_is_stale().
Referenced by brix_cred_autorefresh().
run_oidc_token()
static int run_oidc_token (const char * account, char * out, size_t outsz, brix_status * st) static
Definition at line 45 of file credrefresh.c.
References brix_rstrip(), brix_status_set(), brix_subprocess_capture(), XRDC_EAUTH, and XRDC_ESOCK.
Referenced by refresh_bearer_token().
token_needs_refresh()
static int token_needs_refresh (void) static
Definition at line 104 of file credrefresh.c.
References brix_token_discover(), brix_token_meta_get(), brix_token_meta::exp, brix_token_meta::expired, tok, brix_token_meta::valid, and XRDC_CRED_MARGIN_SECS.
Referenced by refresh_bearer_token().