nginx-xrootd: client/lib/auth/cred/cred_sss.c File Reference
cred_sss.c File Reference
#include "cred.h"
#include "brix.h"
#include "auth/sss/sss_keytab.h"
#include <string.h>
Macros
#define _GNU_SOURCE
Functions
static void resolve_keytab_path (const brix_cred_config *cfg, char *out, size_t outsz)
static int keytab_probe (const brix_cred_config *cfg, char *path_out, size_t outsz)
static int sss_available (const brix_cred_config *cfg)
static int sss_acquire (const brix_cred_config *cfg, brix_cred_view *out, int64_t *not_after, brix_status *st)
const brix_cred_handler * brix_cred_sss (void)
Variables
static const brix_cred_handler s_sss_handler
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 29 of file cred_sss.c.
Function Documentation
brix_cred_sss()
const brix_cred_handler * brix_cred_sss (void)
Definition at line 152 of file cred_sss.c.
References s_sss_handler.
Referenced by brix_cred_store_new().
keytab_probe()
static int keytab_probe (const brix_cred_config * cfg, char * path_out, size_t outsz) static
Definition at line 71 of file cred_sss.c.
References brix_sss_keytab_read(), brix_status_clear(), resolve_keytab_path(), and XRDC_SSS_KEYS_MAX.
Referenced by sss_acquire(), and sss_available().
resolve_keytab_path()
static void resolve_keytab_path (const brix_cred_config * cfg, char * out, size_t outsz) static
Definition at line 49 of file cred_sss.c.
References brix_sss_keytab_default(), and brix_cred_config::keytab_path.
Referenced by keytab_probe().
sss_acquire()
static int sss_acquire (const brix_cred_config * cfg, brix_cred_view * out, int64_t * not_after, brix_status * st) static
Definition at line 112 of file cred_sss.c.
References brix_status_set(), keytab_probe(), brix_cred_view::kind, brix_cred_view::path, brix_cred_view::s3_access, brix_cred_view::s3_secret, brix_cred_view::token, XRDC_CRED_SSS, XRDC_EAUTH, and XRDC_PATH_MAX.
sss_available()
static int sss_available (const brix_cred_config * cfg) static
Definition at line 92 of file cred_sss.c.
References keytab_probe(), and XRDC_PATH_MAX.
Variable Documentation
s_sss_handler
const brix_cred_handler s_sss_handler static
Initial value:
= {
    .kind      = XRDC_CRED_SSS,
    .available = sss_available,
    .acquire   = sss_acquire,
    .refresh   = NULL,
}
Definition at line 136 of file cred_sss.c.
Referenced by brix_cred_sss().