nginx-xrootd: src/fs/backend/cred_mint.c File Reference
cred_mint.c File Reference
#include "cred_mint.h"
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <openssl/bio.h>
#include <openssl/bn.h>
#include <openssl/evp.h>
#include <openssl/pem.h>
#include <openssl/rand.h>
#include <openssl/x509.h>
Data Structures
struct mint_cert_spec_t
struct mint_ca_t
struct mint_material_t
Macros
#define MINT_PATH_MAX 1024
#define MINT_LOG(level, log, err, ...) do { if ((log) != NULL) { ngx_log_error(level, log, err, __VA_ARGS__); } } while (0)
Functions
static int mint_load_ca (const char *ca_cert_path, const char *ca_key_path, X509 **out_cert, EVP_PKEY **out_key, ngx_log_t *log)
static int mint_cached_pem_ok (const char *path)
static int mint_cn_char_ok (unsigned char c)
static void mint_sanitize_cn (const char *principal, char *out, size_t cap)
static X509_NAME * mint_make_subject (const char *cn, ngx_log_t *log)
static uint64_t mint_serial_from_rand (const unsigned char rnd[8])
static int mint_populate_cert (X509 *cert, const mint_cert_spec_t *spec, ngx_log_t *log)
static int mint_build_cert (const mint_ca_t *ca, const char *principal, int ttl_secs, mint_material_t *out, ngx_log_t *log)
static BIO * mint_serialize_pem (X509 *cert, EVP_PKEY *key, X509 *ca_cert, ngx_log_t *log)
static int mint_write_tmp (const char *tmp_path, const char *data, long len, ngx_log_t *log)
static int mint_build_paths (const char *dir, const char *key_stem, char final_path[1024], char tmp_path[1024], ngx_log_t *log)
static int mint_write_pem (const char *dir, const char *key_stem, const mint_material_t *mat, ngx_log_t *log)
static int mint_args_valid (const char *cred_dir, const char *ca_cert_path, const char *ca_key_path, const char *principal, const char *key)
static ngx_int_t mint_generate (const char *cred_dir, const char *ca_cert_path, const char *ca_key_path, const char *principal, const char *key, int ttl_secs, ngx_log_t *log)
ngx_int_t brix_cred_mint (const char *cred_dir, const char *ca_cert_path, const char *ca_key_path, const char *principal, const char *key, int ttl_secs, ngx_log_t *log)
Macro Definition Documentation
MINT_LOG
#define MINT_LOG (level, log, err, ...) do { if ((log) != NULL) { ngx_log_error(level, log, err, __VA_ARGS__); } } while (0)
Definition at line 52 of file cred_mint.c.
MINT_PATH_MAX
#define MINT_PATH_MAX 1024
Definition at line 42 of file cred_mint.c.
Function Documentation
brix_cred_mint()
ngx_int_t brix_cred_mint (const char * cred_dir, const char * ca_cert_path, const char * ca_key_path, const char * principal, const char * key, int ttl_secs, ngx_log_t * log)
Definition at line 597 of file cred_mint.c.
References key, log, mint_args_valid(), mint_cached_pem_ok(), mint_generate(), MINT_LOG, and MINT_PATH_MAX.
Referenced by vfs_cred_maybe_mint().
mint_args_valid()
static int mint_args_valid (const char * cred_dir, const char * ca_cert_path, const char * ca_key_path, const char * principal, const char * key) static
Definition at line 534 of file cred_mint.c.
References key.
Referenced by brix_cred_mint().
mint_build_cert()
static int mint_build_cert (const mint_ca_t * ca, const char * principal, int ttl_secs, mint_material_t * out, ngx_log_t * log) static
Definition at line 302 of file cred_mint.c.
References mint_ca_t::cert, mint_material_t::cert, mint_ca_t::key, mint_material_t::key, key, log, MINT_LOG, mint_make_subject(), mint_populate_cert(), mint_sanitize_cn(), mint_serial_from_rand(), and mint_cert_spec_t::subj.
Referenced by mint_generate().
mint_build_paths()
static int mint_build_paths (const char * dir, const char * key_stem, char final_path[1024], char tmp_path[1024], ngx_log_t * log) static
Definition at line 451 of file cred_mint.c.
References log, MINT_LOG, and MINT_PATH_MAX.
Referenced by mint_write_pem().
mint_cached_pem_ok()
static int mint_cached_pem_ok (const char * path) static
Definition at line 111 of file cred_mint.c.
References BRIX_CRED_MINT_REFRESH_WINDOW.
Referenced by brix_cred_mint().
mint_cn_char_ok()
static int mint_cn_char_ok (unsigned char c) static
Definition at line 148 of file cred_mint.c.
References c.
Referenced by mint_sanitize_cn().
mint_generate()
static ngx_int_t mint_generate (const char * cred_dir, const char * ca_cert_path, const char * ca_key_path, const char * principal, const char * key, int ttl_secs, ngx_log_t * log) static
Definition at line 557 of file cred_mint.c.
References mint_material_t::ca_cert, mint_ca_t::cert, mint_material_t::cert, mint_ca_t::key, mint_material_t::key, key, log, mint_build_cert(), mint_load_ca(), MINT_LOG, and mint_write_pem().
Referenced by brix_cred_mint().
mint_load_ca()
static int mint_load_ca (const char * ca_cert_path, const char * ca_key_path, X509 ** out_cert, EVP_PKEY ** out_key, ngx_log_t * log) static
Definition at line 62 of file cred_mint.c.
References key, log, and MINT_LOG.
Referenced by mint_generate().
mint_make_subject()
static X509_NAME * mint_make_subject (const char * cn, ngx_log_t * log) static
Definition at line 187 of file cred_mint.c.
References log, and MINT_LOG.
Referenced by mint_build_cert().
mint_populate_cert()
static int mint_populate_cert (X509 * cert, const mint_cert_spec_t * spec, ngx_log_t * log) static
Definition at line 269 of file cred_mint.c.
References mint_cert_spec_t::ca_cert, mint_cert_spec_t::ca_key, mint_cert_spec_t::key, log, MINT_LOG, mint_cert_spec_t::serial, mint_cert_spec_t::subj, and mint_cert_spec_t::ttl_secs.
Referenced by mint_build_cert().
mint_sanitize_cn()
static void mint_sanitize_cn (const char * principal, char * out, size_t cap) static
Definition at line 164 of file cred_mint.c.
References c, and mint_cn_char_ok().
Referenced by mint_build_cert().
mint_serial_from_rand()
static uint64_t mint_serial_from_rand (const unsigned char rnd[8]) static
Definition at line 211 of file cred_mint.c.
Referenced by mint_build_cert().
mint_serialize_pem()
static BIO * mint_serialize_pem (X509 * cert, EVP_PKEY * key, X509 * ca_cert, ngx_log_t * log) static
Definition at line 375 of file cred_mint.c.
References key, log, and MINT_LOG.
Referenced by mint_write_pem().
mint_write_pem()
static int mint_write_pem (const char * dir, const char * key_stem, const mint_material_t * mat, ngx_log_t * log) static
Definition at line 490 of file cred_mint.c.
References mint_material_t::ca_cert, mint_material_t::cert, mint_material_t::key, log, mint_build_paths(), MINT_LOG, MINT_PATH_MAX, mint_serialize_pem(), and mint_write_tmp().
Referenced by mint_generate().
mint_write_tmp()
static int mint_write_tmp (const char * tmp_path, const char * data, long len, ngx_log_t * log) static
Definition at line 410 of file cred_mint.c.
References close(), log, MINT_LOG, and open().
Referenced by mint_write_pem().