nginx-xrootd: client/lib/auth/cred/cred_x509.c File Reference
cred_x509.c File Reference
#include "cred.h"
#include "brix.h"
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <openssl/bio.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
Macros
#define _GNU_SOURCE
Functions
static void resolve_proxy_path (const brix_cred_config *cfg, char *out, size_t outsz)
static int parse_notafter (const char *path, int64_t *result)
static int x509_available (const brix_cred_config *cfg)
static int x509_acquire (const brix_cred_config *cfg, brix_cred_view *out, int64_t *not_after, brix_status *st)
static int x509_refresh (const brix_cred_config *cfg, brix_status *st)
const brix_cred_handler * brix_cred_x509 (void)
Variables
static const brix_cred_handler s_x509_handler
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 26 of file cred_x509.c.
Function Documentation
brix_cred_x509()
const brix_cred_handler * brix_cred_x509 (void)
Definition at line 232 of file cred_x509.c.
References s_x509_handler.
Referenced by brix_cred_store_new().
parse_notafter()
static int parse_notafter (const char * path, int64_t * result) static
Definition at line 85 of file cred_x509.c.
Referenced by x509_acquire().
resolve_proxy_path()
static void resolve_proxy_path (const brix_cred_config * cfg, char * out, size_t outsz) static
Definition at line 52 of file cred_x509.c.
References brix_cred_config::proxy_path.
Referenced by x509_acquire(), and x509_available().
x509_acquire()
static int x509_acquire (const brix_cred_config * cfg, brix_cred_view * out, int64_t * not_after, brix_status * st) static
Definition at line 165 of file cred_x509.c.
References access(), brix_status_set(), brix_cred_view::kind, parse_notafter(), brix_cred_view::path, resolve_proxy_path(), brix_cred_view::s3_access, brix_cred_view::s3_secret, brix_cred_view::token, XRDC_CRED_X509_PROXY, and XRDC_ENOENT.
x509_available()
static int x509_available (const brix_cred_config * cfg) static
Definition at line 140 of file cred_x509.c.
References access(), and resolve_proxy_path().
x509_refresh()
static int x509_refresh (const brix_cred_config * cfg, brix_status * st) static
Definition at line 208 of file cred_x509.c.
Variable Documentation
s_x509_handler
const brix_cred_handler s_x509_handler static
Initial value:
= {
    .kind      = XRDC_CRED_X509_PROXY,
    .available = x509_available,
    .acquire   = x509_acquire,
    .refresh   = x509_refresh,
}
Definition at line 216 of file cred_x509.c.
Referenced by brix_cred_x509().