nginx-xrootd: client/lib/auth/cred/cred.c File Reference
cred.c File Reference
#include "cred.h"
#include "brix.h"
#include <stdlib.h>
#include <string.h>
#include <time.h>
Data Structures
struct cred_slot
struct brix_cred_store
Macros
#define _GNU_SOURCE
#define DUP_FIELD(field)
Functions
static void cfg_copy_free (brix_cred_config *c)
const brix_cred_handler * brix_cred_x509 (void)
const brix_cred_handler * brix_cred_bearer (void)
const brix_cred_handler * brix_cred_krb5 (void)
const brix_cred_handler * brix_cred_sss (void)
const brix_cred_handler * brix_cred_s3keys (void)
static brix_cred_config * cfg_copy_alloc (const brix_cred_config *src)
static void slot_clear_owned (cred_slot *sl)
static int slot_store_view (cred_slot *sl, const brix_cred_view *v, int64_t not_after)
static const char * kind_name (brix_cred_kind k)
brix_cred_store * brix_cred_store_new (const brix_cred_config *cfg)
void brix_cred_store_free (brix_cred_store *s)
int brix_cred_available (brix_cred_store *s, brix_cred_kind kind)
static int should_refresh (const brix_cred_store *s, const cred_slot *sl, int min_remaining_s)
static int do_acquire (brix_cred_store *s, brix_cred_kind kind, const brix_cred_handler *h, cred_slot *sl, brix_status *st)
int brix_cred_acquire (brix_cred_store *s, brix_cred_kind kind, int min_remaining_s, brix_cred_view *view, brix_status *st)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 24 of file cred.c.
DUP_FIELD
#define DUP_FIELD (field)
Value:
    do {                                                                    \
        if (src->field != NULL) {                                           \
            c->field = strdup(src->field);                                  \
            if (c->field == NULL) {                                         \
                cfg_copy_free(c);                                           \
                return NULL;                                                \
            }                                                               \
        }                                                                   \
    } while (0)
Function Documentation
brix_cred_acquire()
int brix_cred_acquire (brix_cred_store * s, brix_cred_kind kind, int min_remaining_s, brix_cred_view * view, brix_status * st)
Definition at line 414 of file cred.c.
References brix_status_set(), do_acquire(), kind_name(), cred_slot::loaded, brix_cred_handler::refresh, s, should_refresh(), cred_slot::view, XRDC_CRED_KIND_COUNT, XRDC_EAUTH, and XRDC_EUSAGE.
Referenced by auth_hdr_bearer(), gsi_resolve_proxy(), s3_resolve_keys(), sss_first(), and token_first().
brix_cred_available()
int brix_cred_available (brix_cred_store * s, brix_cred_kind kind)
Definition at line 326 of file cred.c.
References brix_cred_handler::available, s, and XRDC_CRED_KIND_COUNT.
Referenced by gsi_have(), sss_have(), and token_have().
brix_cred_bearer()
const brix_cred_handler * brix_cred_bearer (void) extern
Definition at line 241 of file cred_bearer.c.
References s_bearer_handler.
Referenced by brix_cred_store_new().
brix_cred_krb5()
const brix_cred_handler * brix_cred_krb5 (void) extern
Definition at line 264 of file cred_krb5.c.
Referenced by brix_cred_store_new().
brix_cred_s3keys()
const brix_cred_handler * brix_cred_s3keys (void) extern
Definition at line 358 of file cred_s3.c.
References s_s3keys_handler.
Referenced by brix_cred_store_new().
brix_cred_sss()
const brix_cred_handler * brix_cred_sss (void) extern
Definition at line 152 of file cred_sss.c.
References s_sss_handler.
Referenced by brix_cred_store_new().
brix_cred_store_free()
void brix_cred_store_free (brix_cred_store * s)
Definition at line 303 of file cred.c.
References cfg_copy_free(), s, slot_clear_owned(), and XRDC_CRED_KIND_COUNT.
Referenced by main().
brix_cred_store_new()
brix_cred_store * brix_cred_store_new (const brix_cred_config * cfg)
Definition at line 261 of file cred.c.
References brix_cred_bearer(), brix_cred_krb5(), brix_cred_s3keys(), brix_cred_sss(), brix_cred_x509(), cfg_copy_alloc(), s, XRDC_CRED_BEARER, XRDC_CRED_KRB5, XRDC_CRED_S3KEYS, XRDC_CRED_SSS, and XRDC_CRED_X509_PROXY.
Referenced by brix_cli_cred_store_build().
brix_cred_x509()
const brix_cred_handler * brix_cred_x509 (void) extern
Definition at line 232 of file cred_x509.c.
References s_x509_handler.
Referenced by brix_cred_store_new().
cfg_copy_alloc()
static brix_cred_config * cfg_copy_alloc (const brix_cred_config * src) static
Definition at line 65 of file cred.c.
References brix_cred_config::auto_refresh, c, DUP_FIELD, and proxy_path().
Referenced by brix_cred_store_new().
cfg_copy_free()
static void cfg_copy_free (brix_cred_config * c) static
Definition at line 107 of file cred.c.
References c.
Referenced by brix_cred_store_free().
do_acquire()
static int do_acquire (brix_cred_store * s, brix_cred_kind kind, const brix_cred_handler * h, cred_slot * sl, brix_status * st) static
Definition at line 379 of file cred.c.
References brix_cred_handler::acquire, brix_status_set(), kind_name(), s, slot_store_view(), and XRDC_EAUTH.
Referenced by brix_cred_acquire().
kind_name()
static const char * kind_name (brix_cred_kind k) static
Definition at line 237 of file cred.c.
References XRDC_CRED_BEARER, XRDC_CRED_KRB5, XRDC_CRED_S3KEYS, XRDC_CRED_SSS, and XRDC_CRED_X509_PROXY.
Referenced by brix_cred_acquire(), and do_acquire().
should_refresh()
static int should_refresh (const brix_cred_store * s, const cred_slot * sl, int min_remaining_s) static
Definition at line 351 of file cred.c.
References cred_slot::not_after, and s.
Referenced by brix_cred_acquire().
slot_clear_owned()
static void slot_clear_owned (cred_slot * sl) static
Definition at line 161 of file cred.c.
References cred_slot::owned_path, cred_slot::owned_s3_access, cred_slot::owned_s3_secret, and cred_slot::owned_token.
Referenced by brix_cred_store_free(), and slot_store_view().
slot_store_view()
static int slot_store_view (cred_slot * sl, const brix_cred_view * v, int64_t not_after) static
Definition at line 184 of file cred.c.
References brix_cred_view::kind, cred_slot::loaded, cred_slot::not_after, brix_cred_view::not_after, cred_slot::owned_path, cred_slot::owned_s3_access, cred_slot::owned_s3_secret, cred_slot::owned_token, brix_cred_view::path, brix_cred_view::s3_access, brix_cred_view::s3_secret, slot_clear_owned(), brix_cred_view::token, and cred_slot::view.
Referenced by do_acquire().