nginx-xrootd: src/core/compat/crypto.h File Reference
crypto.h File Reference
#include <stddef.h>
#include <stdint.h>
Functions
int brix_crypto_init (void)
void brix_crypto_cleanup (void)
int brix_hmac_sha256 (const uint8_t *key, size_t keylen, const uint8_t *data, size_t datalen, uint8_t out[32])
int brix_sha256 (const uint8_t *data, size_t len, uint8_t out[32])
void * brix_sha256_stream_new (void)
int brix_sha256_stream_update (void *s, const uint8_t *data, size_t len)
int brix_sha256_stream_final (void *s, uint8_t out[32])
void brix_sha256_stream_free (void *s)
Function Documentation
brix_crypto_cleanup()
void brix_crypto_cleanup (void)
Definition at line 30 of file crypto.c.
References s_hmac_mac, and s_sha256_md.
Referenced by brix_exit_process().
brix_crypto_init()
int brix_crypto_init (void)
Definition at line 22 of file crypto.c.
References s_hmac_mac, and s_sha256_md.
Referenced by brix_cli_cksum_main(), brix_crypto_init_void(), brix_wait41_main(), main(), ngx_stream_brix_init_process(), xrd_caps(), xrd_certinfo(), xrd_clockskew(), xrd_doctor(), xrd_login(), xrd_ping(), xrd_whoami(), xrootdfs_aio_main(), and xrootdfs_legacy_main().
brix_hmac_sha256()
int brix_hmac_sha256 (const uint8_t * key, size_t keylen, const uint8_t * data, size_t datalen, uint8_t out[32])
Definition at line 39 of file crypto.c.
References key, and s_hmac_mac.
Referenced by brix_gsi_sigver_hmac(), brix_s3_sign_v4_q(), brix_sigv4_signing_key(), s3_chunk_verify(), s3_post_verify_policy(), s3_verify_sigv4(), sd_s3_sign(), and sd_s3_sign_ext().
brix_sha256()
int brix_sha256 (const uint8_t * data, size_t len, uint8_t out[32])
Definition at line 67 of file crypto.c.
References s_sha256_md.
Referenced by brix_auth_gate_cache_key(), brix_make_resume_path(), brix_s3_sha256_hex(), brix_token_cache_lookup(), brix_token_cache_store(), brix_token_l1_locate(), s3_verify_sigv4(), sd_s3_sha256_hex(), and webdav_introspect_access_handler().
brix_sha256_stream_final()
int brix_sha256_stream_final (void * s, uint8_t out[32])
Definition at line 111 of file crypto.c.
References s, and s_sha256_md.
Referenced by s3_chunk_verify().
brix_sha256_stream_free()
void brix_sha256_stream_free (void * s)
Definition at line 125 of file crypto.c.
References s.
Referenced by s3_aws_chunked_decode_to_fd().
brix_sha256_stream_new()
void * brix_sha256_stream_new (void)
Definition at line 90 of file crypto.c.
References s_sha256_md.
Referenced by s3_aws_chunked_decode_to_fd().
brix_sha256_stream_update()
int brix_sha256_stream_update (void * s, const uint8_t * data, size_t len)
Definition at line 105 of file crypto.c.
References s.
Referenced by s3_chunk_feed().