nginx-xrootd: src/core/compat/crypto.c File Reference
crypto.c File Reference
#include "crypto.h"
#include <openssl/evp.h>
#include <openssl/core_names.h>
Functions
int brix_crypto_init (void)
void brix_crypto_cleanup (void)
int brix_hmac_sha256 (const uint8_t *key, size_t keylen, const uint8_t *data, size_t datalen, uint8_t out[32])
int brix_sha256 (const uint8_t *data, size_t len, uint8_t out[32])
void * brix_sha256_stream_new (void)
int brix_sha256_stream_update (void *s, const uint8_t *data, size_t len)
int brix_sha256_stream_final (void *s, uint8_t out[32])
void brix_sha256_stream_free (void *s)
Variables
static EVP_MAC * s_hmac_mac
static EVP_MD * s_sha256_md
Function Documentation
brix_crypto_cleanup()
void brix_crypto_cleanup (void)
Definition at line 30 of file crypto.c.
References s_hmac_mac, and s_sha256_md.
Referenced by brix_exit_process().
brix_crypto_init()
int brix_crypto_init (void)
Definition at line 22 of file crypto.c.
References s_hmac_mac, and s_sha256_md.
Referenced by brix_cli_cksum_main(), brix_crypto_init_void(), brix_wait41_main(), main(), ngx_stream_brix_init_process(), xrd_caps(), xrd_certinfo(), xrd_clockskew(), xrd_doctor(), xrd_login(), xrd_ping(), xrd_whoami(), xrootdfs_aio_main(), and xrootdfs_legacy_main().
brix_hmac_sha256()
int brix_hmac_sha256 (const uint8_t * key, size_t keylen, const uint8_t * data, size_t datalen, uint8_t out[32])
Definition at line 39 of file crypto.c.
References key, and s_hmac_mac.
Referenced by brix_gsi_sigver_hmac(), brix_s3_sigv4_sign_and_emit(), brix_sigv4_signing_key(), s3_chunk_verify(), s3_post_verify_signature(), s3_sigv4_compute_signature(), sd_s3_derive_key_and_sign(), sd_s3_sign_ex(), and sts_sign_query().
brix_sha256()
int brix_sha256 (const uint8_t * data, size_t len, uint8_t out[32])
Definition at line 67 of file crypto.c.
References s_sha256_md.
Referenced by brix_auth_gate_cache_key(), brix_make_resume_path(), brix_s3_sha256_hex(), brix_token_cache_lookup(), brix_token_cache_store(), brix_token_l1_locate(), s3_sigv4_compute_signature(), sd_s3_sha256_hex(), sts_sign_query(), and webdav_introspect_access_handler().
brix_sha256_stream_final()
int brix_sha256_stream_final (void * s, uint8_t out[32])
Definition at line 111 of file crypto.c.
References s, and s_sha256_md.
Referenced by s3_chunk_verify().
brix_sha256_stream_free()
void brix_sha256_stream_free (void * s)
Definition at line 125 of file crypto.c.
References s.
Referenced by s3_aws_chunked_decode_to_fd().
brix_sha256_stream_new()
void * brix_sha256_stream_new (void)
Definition at line 90 of file crypto.c.
References s_sha256_md.
Referenced by s3_chunk_dec_init().
brix_sha256_stream_update()
int brix_sha256_stream_update (void * s, const uint8_t * data, size_t len)
Definition at line 105 of file crypto.c.
References s.
Referenced by chunk_consume_data().
Variable Documentation
s_hmac_mac
EVP_MAC* s_hmac_mac static
Definition at line 18 of file crypto.c.
Referenced by brix_crypto_cleanup(), brix_crypto_init(), and brix_hmac_sha256().
s_sha256_md
EVP_MD* s_sha256_md static
Definition at line 19 of file crypto.c.
Referenced by brix_crypto_cleanup(), brix_crypto_init(), brix_sha256(), brix_sha256_stream_final(), and brix_sha256_stream_new().