nginx-xrootd: src/fs/backend/csi_unittest.c File Reference
csi_unittest.c File Reference
#include "csi_tagstore.h"
#include "fs/meta/xmeta_path.h"
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Macros
#define CHECK(cond, name)
#define G 4096u /* small granule so the test file stays tiny */
Functions
static void write_file (const char *path, const unsigned char *data, size_t len)
int main (void)
Variables
static int g_checks
static int g_failed
Macro Definition Documentation
CHECK
#define CHECK (cond, name)
Value:
    do { \
    g_checks++; \
    if (cond) { printf("  ok   %s\n", name); } \
    else      { printf("  FAIL %s (line %d)\n", name, __LINE__); g_failed++; } \
} while (0)
Definition at line 27 of file csi_unittest.c.
G
#define G 4096u /* small granule so the test file stays tiny */
Definition at line 33 of file csi_unittest.c.
Function Documentation
main()
int main (void)
Definition at line 48 of file csi_unittest.c.
References brix_xmeta_t::blockcrc, brix_csi_close(), brix_csi_flush(), BRIX_CSI_MISMATCH, BRIX_CSI_NOTAGS, BRIX_CSI_OK, brix_csi_open(), brix_csi_verify_read(), brix_csi_write_update(), brix_xmeta_free(), BRIX_XMETA_OK, brix_xmeta_path_load(), brix_xmeta_path_remove(), brix_xmeta_t::buffer_size, CHECK, brix_xmeta_t::file_size, G, g_checks, g_failed, brix_xmeta_t::have_blockcrc, brix_xmeta_t::nblocks, brix_xmeta_t::no_cksum_time, brix_csi_t::trust_fs, and write_file().
write_file()
static void write_file (const char * path, const unsigned char * data, size_t len) static
Definition at line 36 of file csi_unittest.c.
References close(), and open().
Referenced by main().
Variable Documentation
g_checks
int g_checks static
Definition at line 25 of file csi_unittest.c.
Referenced by main().
g_failed
int g_failed static
Definition at line 25 of file csi_unittest.c.
Referenced by main().