nginx-xrootd: src/fs/backend/csi_verify.c File Reference
csi_verify.c File Reference
#include "csi_tagstore.h"
#include "fs/meta/xmeta_path.h"
#include "core/compat/crc32c.h"
#include <errno.h>
#include <fcntl.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Functions
static int csi_verify_against (const brix_csi_t *c, const brix_xmeta_t *xm, const unsigned char *buf, off_t off, size_t len)
int brix_csi_verify_read (brix_csi_t *c, const unsigned char *buf, off_t off, size_t len)
static int csi_local_reserve (brix_csi_t *c, uint64_t b)
int brix_csi_write_update (brix_csi_t *c, const unsigned char *buf, off_t off, size_t len)
static int csi_record_regeom (brix_xmeta_t *xm, int64_t new_size, int64_t granule)
static int csi_flush_open_file (const brix_csi_t *c, struct stat *st)
static int csi_flush_load_record (const brix_csi_t *c, const struct stat *st, brix_xmeta_t *xm)
static int csi_flush_recompute_block (int fd, brix_xmeta_t *xm, int64_t g, uint64_t b, unsigned char **blockbuf)
static void csi_flush_rebuild_crcs (brix_csi_t *c, brix_xmeta_t *xm, int fd, int64_t g)
static void csi_flush_mark_coverage (brix_xmeta_t *xm)
int brix_csi_flush (brix_csi_t *c)
Function Documentation
brix_csi_flush()
int brix_csi_flush (brix_csi_t * c)
Definition at line 428 of file csi_verify.c.
References BRIX_CSI_ERR, BRIX_CSI_OK, brix_xmeta_free(), BRIX_XMETA_OK, brix_xmeta_path_lock(), brix_xmeta_path_save(), brix_xmeta_path_unlock(), brix_xmeta_t::buffer_size, c, close(), csi_flush_load_record(), csi_flush_mark_coverage(), csi_flush_open_file(), csi_flush_rebuild_crcs(), and stat().
Referenced by brix_csi_close(), and main().
brix_csi_verify_read()
int brix_csi_verify_read (brix_csi_t * c, const unsigned char * buf, off_t off, size_t len)
Definition at line 80 of file csi_verify.c.
References BRIX_CSI_ERR, BRIX_CSI_NOTAGS, BRIX_CSI_OK, BRIX_XMETA_FOREIGN, brix_xmeta_free(), BRIX_XMETA_OK, brix_xmeta_path_load(), c, and csi_verify_against().
Referenced by brix_vfs_io_execute_read(), main(), and read_try_warm().
brix_csi_write_update()
int brix_csi_write_update (brix_csi_t * c, const unsigned char * buf, off_t off, size_t len)
Definition at line 153 of file csi_verify.c.
References brix_crc32c_value(), BRIX_CSI_ERR, BRIX_CSI_OK, c, and csi_local_reserve().
Referenced by brix_handle_clone(), brix_vfs_io_execute_write(), ckp_xeq_pgwrite(), ckp_xeq_write(), and main().
csi_flush_load_record()
static int csi_flush_load_record (const brix_csi_t * c, const struct stat * st, brix_xmeta_t * xm) static
Definition at line 277 of file csi_verify.c.
References brix_xmeta_t::bitmap, brix_xmeta_t::blockcrc, BRIX_CSI_ERR, BRIX_CSI_OK, BRIX_XMETA_ERR, BRIX_XMETA_FOREIGN, brix_xmeta_free(), brix_xmeta_init(), BRIX_XMETA_OK, brix_xmeta_path_load(), brix_xmeta_t::buffer_size, c, csi_record_regeom(), brix_xmeta_t::file_size, brix_xmeta_t::have_blockcrc, brix_xmeta_t::nblocks, and brix_xmeta_t::origin_mtime.
Referenced by brix_csi_flush().
csi_flush_mark_coverage()
static void csi_flush_mark_coverage (brix_xmeta_t * xm) static
Definition at line 407 of file csi_verify.c.
References brix_xmeta_t::blockcrc, BRIX_XMETA_CRC_UNSET, brix_xmeta_t::nblocks, and brix_xmeta_t::no_cksum_time.
Referenced by brix_csi_flush().
csi_flush_open_file()
static int csi_flush_open_file (const brix_csi_t * c, struct stat * st) static
Definition at line 253 of file csi_verify.c.
References c, close(), fstat(), and open().
Referenced by brix_csi_flush().
csi_flush_rebuild_crcs()
static void csi_flush_rebuild_crcs (brix_csi_t * c, brix_xmeta_t * xm, int fd, int64_t g) static
Definition at line 370 of file csi_verify.c.
References brix_xmeta_t::blockcrc, BRIX_CSI_FLUSH_READ, BRIX_XMETA_CRC_UNSET, c, csi_flush_recompute_block(), and brix_xmeta_t::nblocks.
Referenced by brix_csi_flush().
csi_flush_recompute_block()
static int csi_flush_recompute_block (int fd, brix_xmeta_t * xm, int64_t g, uint64_t b, unsigned char ** blockbuf) static
Definition at line 328 of file csi_verify.c.
References brix_xmeta_t::blockcrc, brix_crc32c_value(), brix_xmeta_t::file_size, and pread().
Referenced by csi_flush_rebuild_crcs().
csi_local_reserve()
static int csi_local_reserve (brix_csi_t * c, uint64_t b) static
Definition at line 121 of file csi_verify.c.
References BRIX_CSI_LOCAL_MAX, and c.
Referenced by brix_csi_write_update().
csi_record_regeom()
static int csi_record_regeom (brix_xmeta_t * xm, int64_t new_size, int64_t granule) static
Definition at line 205 of file csi_verify.c.
References brix_xmeta_t::access_cnt, brix_xmeta_t::astat, brix_xmeta_t::astat_count, brix_xmeta_t::bitmap, brix_xmeta_free(), brix_xmeta_init(), BRIX_XMETA_OK, brix_xmeta_t::bytes_flushed, brix_xmeta_t::cks_alg, brix_xmeta_t::cks_alg_len, brix_xmeta_t::cks_hex, brix_xmeta_t::cks_len, brix_xmeta_t::creation_time, brix_xmeta_t::dirty_hi, brix_xmeta_t::dirty_lo, brix_xmeta_t::dirty_since, brix_xmeta_t::etag, brix_xmeta_t::etag_len, brix_xmeta_t::expires_at, brix_xmeta_t::filled_at, brix_xmeta_t::flush_gen, brix_xmeta_t::have_state, brix_xmeta_t::last_flush, brix_xmeta_t::mode, brix_xmeta_t::nblocks, brix_xmeta_t::origin_mtime, brix_xmeta_t::state_flags, and brix_xmeta_t::status_raw.
Referenced by csi_flush_load_record().
csi_verify_against()
static int csi_verify_against (const brix_csi_t * c, const brix_xmeta_t * xm, const unsigned char * buf, off_t off, size_t len) static
Definition at line 34 of file csi_verify.c.
References brix_xmeta_t::blockcrc, brix_crc32c_value(), BRIX_CSI_MISMATCH, BRIX_CSI_NOTAGS, BRIX_CSI_OK, BRIX_XMETA_CRC_UNSET, brix_xmeta_t::buffer_size, c, brix_xmeta_t::file_size, brix_xmeta_t::have_blockcrc, and brix_xmeta_t::nblocks.
Referenced by brix_csi_verify_read().