nginx-xrootd: src/fs/backend/csi_tagstore.h File Reference
csi_tagstore.h File Reference
#include <limits.h>
#include <stdint.h>
#include <sys/types.h>
#include "fs/meta/xmeta.h"
Data Structures
struct brix_csi_t
Macros
#define BRIX_CSI_OK 0
#define BRIX_CSI_MISMATCH (-1)
#define BRIX_CSI_NOTAGS (-2)
#define BRIX_CSI_ERR (-3)
#define BRIX_CSI_FLUSH_READ 32
#define BRIX_CSI_LOCAL_MAX (1u << 20)
Functions
int brix_csi_open (brix_csi_t *c, const char *abs_path, uint32_t granule, int writable)
void brix_csi_close (brix_csi_t *c)
int brix_csi_verify_read (brix_csi_t *c, const unsigned char *buf, off_t off, size_t len)
int brix_csi_write_update (brix_csi_t *c, const unsigned char *buf, off_t off, size_t len)
int brix_csi_flush (brix_csi_t *c)
Macro Definition Documentation
BRIX_CSI_ERR
#define BRIX_CSI_ERR (-3)
Definition at line 37 of file csi_tagstore.h.
BRIX_CSI_FLUSH_READ
#define BRIX_CSI_FLUSH_READ 32
Definition at line 41 of file csi_tagstore.h.
BRIX_CSI_LOCAL_MAX
#define BRIX_CSI_LOCAL_MAX (1u << 20)
Definition at line 44 of file csi_tagstore.h.
BRIX_CSI_MISMATCH
#define BRIX_CSI_MISMATCH (-1)
Definition at line 35 of file csi_tagstore.h.
BRIX_CSI_NOTAGS
#define BRIX_CSI_NOTAGS (-2)
Definition at line 36 of file csi_tagstore.h.
BRIX_CSI_OK
#define BRIX_CSI_OK 0
Definition at line 34 of file csi_tagstore.h.
Function Documentation
brix_csi_close()
void brix_csi_close (brix_csi_t * c)
Definition at line 71 of file csi_tagstore.c.
References brix_csi_flush(), brix_xmeta_free(), and c.
Referenced by brix_open_apply_throttle(), brix_open_attach_csi(), fhandle_release_descriptors(), and main().
brix_csi_flush()
int brix_csi_flush (brix_csi_t * c)
Definition at line 428 of file csi_verify.c.
References BRIX_CSI_ERR, BRIX_CSI_OK, brix_xmeta_free(), BRIX_XMETA_OK, brix_xmeta_path_lock(), brix_xmeta_path_save(), brix_xmeta_path_unlock(), brix_xmeta_t::buffer_size, c, close(), csi_flush_load_record(), csi_flush_mark_coverage(), csi_flush_open_file(), csi_flush_rebuild_crcs(), and stat().
Referenced by brix_csi_close(), and main().
brix_csi_open()
int brix_csi_open (brix_csi_t * c, const char * abs_path, uint32_t granule, int writable)
Definition at line 15 of file csi_tagstore.c.
References brix_xmeta_t::blockcrc, BRIX_CSI_ERR, BRIX_CSI_NOTAGS, BRIX_CSI_OK, BRIX_XMETA_ERR, BRIX_XMETA_FOREIGN, brix_xmeta_free(), brix_xmeta_path_load(), c, and brix_xmeta_t::have_blockcrc.
Referenced by brix_open_attach_csi(), and main().
brix_csi_verify_read()
int brix_csi_verify_read (brix_csi_t * c, const unsigned char * buf, off_t off, size_t len)
Definition at line 80 of file csi_verify.c.
References BRIX_CSI_ERR, BRIX_CSI_NOTAGS, BRIX_CSI_OK, BRIX_XMETA_FOREIGN, brix_xmeta_free(), BRIX_XMETA_OK, brix_xmeta_path_load(), c, and csi_verify_against().
Referenced by brix_vfs_io_execute_read(), main(), and read_try_warm().
brix_csi_write_update()
int brix_csi_write_update (brix_csi_t * c, const unsigned char * buf, off_t off, size_t len)
Definition at line 153 of file csi_verify.c.
References brix_crc32c_value(), BRIX_CSI_ERR, BRIX_CSI_OK, c, and csi_local_reserve().
Referenced by brix_handle_clone(), brix_vfs_io_execute_write(), ckp_xeq_pgwrite(), ckp_xeq_write(), and main().