nginx-xrootd: src/fs/cache/cstore_scan.c File Reference
cstore_scan.c File Reference
#include "cstore.h"
#include "fs/meta/xmeta_carrier.h"
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <unistd.h>
Functions
static int cstore_is_sidecar (const char *name)
static int cstore_scan_skip (const char *name)
static int cstore_scan_child_key (const char *dirkey, size_t dklen, const char *name, char *out, size_t cap)
static ngx_int_t cstore_scan_dir (brix_cstore_t *cs, const char *dirkey, brix_cstore_visit_fn visit, void *ctx)
static ngx_int_t cstore_scan_child (brix_cstore_t *cs, const char *childkey, brix_cstore_visit_fn visit, void *ctx)
ngx_int_t brix_cstore_scan (brix_cstore_t *cs, brix_cstore_visit_fn visit, void *ctx)
Function Documentation
brix_cstore_scan()
ngx_int_t brix_cstore_scan (brix_cstore_t * cs, brix_cstore_visit_fn visit, void * ctx)
Definition at line 148 of file cstore_scan.c.
References cstore_scan_dir(), and brix_cstore_t::store.
Referenced by brix_cache_collect_dir().
cstore_is_sidecar()
static int cstore_is_sidecar (const char * name) static
Definition at line 27 of file cstore_scan.c.
References name.
Referenced by cstore_scan_skip().
cstore_scan_child()
static ngx_int_t cstore_scan_child (brix_cstore_t * cs, const char * childkey, brix_cstore_visit_fn visit, void * ctx) static
Definition at line 81 of file cstore_scan.c.
References brix_cstore_cinfo_load(), cstore_scan_dir(), brix_sd_stat_t::is_dir, brix_sd_stat_t::is_reg, and brix_cstore_t::store.
Referenced by cstore_scan_dir().
cstore_scan_child_key()
static int cstore_scan_child_key (const char * dirkey, size_t dklen, const char * name, char * out, size_t cap) static
Definition at line 57 of file cstore_scan.c.
References name.
Referenced by cstore_scan_dir().
cstore_scan_dir()
static ngx_int_t cstore_scan_dir (brix_cstore_t * cs, const char * dirkey, brix_cstore_visit_fn visit, void * ctx) static
Definition at line 112 of file cstore_scan.c.
References cstore_scan_child(), cstore_scan_child_key(), cstore_scan_skip(), brix_sd_dirent_t::name, PATH_MAX, and brix_cstore_t::store.
Referenced by brix_cstore_scan(), and cstore_scan_child().
cstore_scan_skip()
static int cstore_scan_skip (const char * name) static
Definition at line 43 of file cstore_scan.c.
References cstore_is_sidecar(), and name.
Referenced by cstore_scan_dir().