nginx-xrootd: src/fs/cache/cstore.c File Reference
cstore.c File Reference
#include "cstore.h"
#include "fs/meta/xmeta_carrier.h"
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <unistd.h>
Functions
static int cstore_local_path (const brix_cstore_t *cs, const char *key, char *out, size_t cap)
ngx_int_t brix_cstore_init (brix_cstore_t *cs, brix_sd_instance_t *store, const char *local_root, int meta_mode, size_t l1_entries, int batch_cinfo, ngx_log_t *log)
void brix_cstore_cleanup (brix_cstore_t *cs)
static void cstore_make_parents (brix_cstore_t *cs, const char *key)
brix_sd_staged_t * brix_cstore_fill_open (brix_cstore_t *cs, const char *key, mode_t mode)
ssize_t brix_cstore_fill_write (brix_sd_staged_t *st, const void *buf, size_t len, off_t off)
ngx_int_t brix_cstore_fill_commit (brix_sd_staged_t *st)
void brix_cstore_fill_abort (brix_sd_staged_t *st)
brix_sd_obj_t * brix_cstore_serve_open (brix_cstore_t *cs, const char *key, int *err)
ssize_t brix_cstore_serve_pread (int cache_fd, const uint8_t *bitmap, uint64_t nblocks, uint32_t block_size, off_t size, void *buf, size_t len, off_t off, brix_cstore_fill_block_fn fill, void *ctx)
int brix_cstore_partial_open (brix_cstore_t *cs, const char *key, mode_t mode, off_t size, char *path_out, size_t path_cap)
ngx_int_t brix_cstore_evict (brix_cstore_t *cs, const char *key)
ngx_int_t brix_cstore_cinfo_load (brix_cstore_t *cs, const char *key, brix_cache_cinfo_t *ci)
ngx_int_t brix_cstore_cinfo_store (brix_cstore_t *cs, const char *key, const brix_cache_cinfo_t *ci)
const char * brix_cstore_local_root (const brix_cstore_t *cs)
ngx_int_t brix_cstore_freespace (brix_cstore_t *cs, uint64_t *total, uint64_t *avail)
Function Documentation
brix_cstore_cinfo_load()
ngx_int_t brix_cstore_cinfo_load (brix_cstore_t * cs, const char * key, brix_cache_cinfo_t * ci)
Definition at line 299 of file cstore.c.
References brix_cache_cinfo_from_xmeta(), brix_cache_cinfo_load(), brix_cinfo_l1_get(), brix_cinfo_l1_put(), BRIX_CMETA_LOCAL, brix_xmeta_free(), brix_xmeta_load(), cstore_local_path(), key, brix_cstore_t::l1, brix_cstore_t::meta_mode, PATH_MAX, and brix_cstore_t::store.
Referenced by brix_sd_cache_fill_needs_offload(), cache_open_serve_hit(), cstore_scan_child(), sd_cache_stale_serve_ok(), and sd_cache_stat().
brix_cstore_cinfo_store()
ngx_int_t brix_cstore_cinfo_store (brix_cstore_t * cs, const char * key, const brix_cache_cinfo_t * ci)
Definition at line 343 of file cstore.c.
References brix_cache_cinfo_bitmap_len(), brix_cache_cinfo_load(), brix_cache_cinfo_store(), brix_cache_cinfo_to_xmeta(), brix_cinfo_l1_put(), BRIX_CMETA_LOCAL, brix_xmeta_free(), brix_xmeta_save(), cstore_local_path(), key, brix_cstore_t::l1, brix_cstore_t::meta_mode, brix_cache_cinfo_t::nblocks, PATH_MAX, and brix_cstore_t::store.
Referenced by cache_fill_commit(), and sd_cache_stale_serve_ok().
brix_cstore_cleanup()
void brix_cstore_cleanup (brix_cstore_t * cs)
Definition at line 91 of file cstore.c.
References brix_cinfo_l1_destroy(), and brix_cstore_t::l1.
Referenced by brix_cache_storage_cleanup(), and brix_sd_cache_destroy().
brix_cstore_evict()
ngx_int_t brix_cstore_evict (brix_cstore_t * cs, const char * key)
Definition at line 266 of file cstore.c.
References brix_cache_cinfo_path(), brix_cinfo_l1_drop(), BRIX_CMETA_LOCAL, brix_xmeta_remove(), cstore_local_path(), key, brix_cstore_t::l1, brix_cstore_t::meta_mode, PATH_MAX, and brix_cstore_t::store.
Referenced by brix_cache_evict_remove_object(), reap_remove(), sd_cache_open_common(), sd_cache_rename(), sd_cache_staged_open(), sd_cache_staged_open_cred(), and sd_cache_unlink().
brix_cstore_fill_abort()
void brix_cstore_fill_abort (brix_sd_staged_t * st)
Definition at line 165 of file cstore.c.
Referenced by cache_fill_acquire(), cache_fill_pump(), and cache_fill_verify().
brix_cstore_fill_commit()
ngx_int_t brix_cstore_fill_commit (brix_sd_staged_t * st)
Definition at line 155 of file cstore.c.
Referenced by cache_fill_commit().
brix_cstore_fill_open()
brix_sd_staged_t * brix_cstore_fill_open (brix_cstore_t * cs, const char * key, mode_t mode)
Definition at line 126 of file cstore.c.
References cstore_make_parents(), key, and brix_cstore_t::store.
Referenced by cache_fill_acquire().
brix_cstore_fill_write()
ssize_t brix_cstore_fill_write (brix_sd_staged_t * st, const void * buf, size_t len, off_t off)
Definition at line 144 of file cstore.c.
Referenced by cache_fill_pump().
brix_cstore_freespace()
ngx_int_t brix_cstore_freespace (brix_cstore_t * cs, uint64_t * total, uint64_t * avail)
Definition at line 416 of file cstore.c.
References BRIX_CMETA_LOCAL, brix_cstore_t::local_root, and brix_cstore_t::meta_mode.
Referenced by brix_cache_usage_measure().
brix_cstore_init()
ngx_int_t brix_cstore_init (brix_cstore_t * cs, brix_sd_instance_t * store, const char * local_root, int meta_mode, size_t l1_entries, int batch_cinfo, ngx_log_t * log)
Definition at line 45 of file cstore.c.
References brix_cstore_t::batch_cinfo, brix_cinfo_l1_create(), BRIX_CMETA_AUTO, BRIX_CMETA_LOCAL, BRIX_CMETA_SIDECAR, BRIX_CMETA_XATTR, BRIX_SD_CAP_XATTR, brix_sd_caps(), brix_cstore_t::l1, brix_cstore_t::local_root, log, brix_cstore_t::log, brix_cstore_t::meta_mode, and brix_cstore_t::store.
Referenced by brix_cache_storage_init(), and brix_sd_cache_create().
brix_cstore_local_root()
const char * brix_cstore_local_root (const brix_cstore_t * cs)
Definition at line 403 of file cstore.c.
References BRIX_CMETA_LOCAL, brix_cstore_t::local_root, and brix_cstore_t::meta_mode.
Referenced by brix_cache_state_root().
brix_cstore_partial_open()
int brix_cstore_partial_open (brix_cstore_t * cs, const char * key, mode_t mode, off_t size, char * path_out, size_t path_cap)
Definition at line 229 of file cstore.c.
References BRIX_CMETA_LOCAL, close(), cstore_local_path(), cstore_make_parents(), fstat(), key, brix_cstore_t::meta_mode, open(), PATH_MAX, and stat().
Referenced by sd_cache_partial_open().
brix_cstore_serve_open()
brix_sd_obj_t * brix_cstore_serve_open (brix_cstore_t * cs, const char * key, int * err)
Definition at line 177 of file cstore.c.
References BRIX_SD_O_READ, key, and brix_cstore_t::store.
Referenced by cache_open_miss_serve(), and cache_open_serve_hit().
brix_cstore_serve_pread()
ssize_t brix_cstore_serve_pread (int cache_fd, const uint8_t * bitmap, uint64_t nblocks, uint32_t block_size, off_t size, void * buf, size_t len, off_t off, brix_cstore_fill_block_fn fill, void * ctx)
Definition at line 189 of file cstore.c.
References brix_cache_cinfo_block_present(), and brix_sd_posix_wrap().
Referenced by sd_cache_pread().
cstore_local_path()
static int cstore_local_path (const brix_cstore_t * cs, const char * key, char * out, size_t cap) static
Definition at line 28 of file cstore.c.
References key, and brix_cstore_t::local_root.
Referenced by brix_cstore_cinfo_load(), brix_cstore_cinfo_store(), brix_cstore_evict(), and brix_cstore_partial_open().
cstore_make_parents()
static void cstore_make_parents (brix_cstore_t * cs, const char * key) static
Definition at line 106 of file cstore.c.
References key, PATH_MAX, and brix_cstore_t::store.
Referenced by brix_cstore_fill_open(), and brix_cstore_partial_open().