nginx-xrootd: src/core/compat/cstr.h File Reference
cstr.h File Reference
#include <stddef.h>
#include <string.h>
Functions
static const char * brix_cbuf_copy (char *buf, size_t bufsize, const void *data, size_t len)
static const char * brix_str_cbuf (char *buf, size_t bufsize, const ngx_str_t *s)
static char * brix_pstrdup_z (ngx_pool_t *pool, const ngx_str_t *s)
Function Documentation
brix_cbuf_copy()
static const char * brix_cbuf_copy (char * buf, size_t bufsize, const void * data, size_t len) inline static
Definition at line 27 of file cstr.h.
Referenced by brix_proxy_relay_try_redirect(), and brix_str_cbuf().
brix_pstrdup_z()
static char * brix_pstrdup_z (ngx_pool_t * pool, const ngx_str_t * s) inline static
Definition at line 51 of file cstr.h.
References ngx_memcpy, ngx_pnalloc(), and s.
Referenced by brix_conf_credential_block(), brix_conf_push_prefix(), brix_conf_set_cache_eviction_threshold(), brix_conf_set_cache_include_regex(), brix_conf_set_cache_watermark(), brix_conf_set_manager_map(), brix_conf_set_proxy_upstream(), brix_conf_set_upstream(), brix_credential_line(), brix_http_arg(), s3_find_request_header_value(), and srr_share_usage().
brix_str_cbuf()
static const char * brix_str_cbuf (char * buf, size_t bufsize, const ngx_str_t * s) inline static
Definition at line 43 of file cstr.h.
References brix_cbuf_copy(), and s.
Referenced by brix_conf_set_cache_max_file_size(), brix_idmap_init(), brix_init_server_stage_registry(), brix_log_access(), brix_net_target_check_dns(), brix_net_target_check_dns_pin(), cvmfs_build_fs_path(), dashboard_merge_canon_root(), dashboard_read_config_file(), dig_open_confined(), idmap_init_denylists(), parse_presigned_authorization(), pmark_load_defs(), s3_sigv4_resolve_request_time(), scvmfs_check_bearer(), tier_resolve_creds(), tpc_certreq_open_creds(), tpc_pull_attach_creds(), tpc_start_tls(), webdav_build_ca_store(), and webdav_put_persist_checksums().