nginx-xrootd: src/protocols/ssi/svc_cta/cta_exec_unittest.c File Reference
cta_exec_unittest.c File Reference
#include "cta_exec.h"
#include <stdio.h>
#include <string.h>
Macros
#define CHECK(cond)
Functions
static void rec_alert (void *ctx, const char *msg)
static cta_req_t * submit (brix_cta_queue_t *q, cta_op_t op)
static void test_archive_completes_with_alerts (void)
static void test_retrieve_completes (void)
static void test_cancel_transitions (void)
static void test_query_not_an_exec_op (void)
static void test_prod_archive_fails_without_backend (void)
int main (void)
Variables
static int g_fail
static char g_alerts [8][64]
static int g_nalerts
Macro Definition Documentation
CHECK
#define CHECK (cond)
Value:
    do { \
    if (!(cond)) { printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
                   g_fail++; } \
} while (0)
Definition at line 13 of file cta_exec_unittest.c.
Function Documentation
main()
int main (void)
Definition at line 93 of file cta_exec_unittest.c.
References g_fail, test_archive_completes_with_alerts(), test_cancel_transitions(), test_prod_archive_fails_without_backend(), test_query_not_an_exec_op(), and test_retrieve_completes().
rec_alert()
static void rec_alert (void * ctx, const char * msg) static
Definition at line 21 of file cta_exec_unittest.c.
References g_alerts, and g_nalerts.
Referenced by test_archive_completes_with_alerts(), test_cancel_transitions(), test_prod_archive_fails_without_backend(), test_query_not_an_exec_op(), and test_retrieve_completes().
submit()
static cta_req_t * submit (brix_cta_queue_t * q, cta_op_t op) static
Definition at line 33 of file cta_exec_unittest.c.
References cta_queue_submit(), and cta_request_t::op.
Referenced by test_archive_completes_with_alerts(), test_cancel_transitions(), test_prod_archive_fails_without_backend(), test_query_not_an_exec_op(), and test_retrieve_completes().
test_archive_completes_with_alerts()
static void test_archive_completes_with_alerts (void) static
Definition at line 41 of file cta_exec_unittest.c.
References CHECK, cta_exec_run(), cta_exec_test_vtbl(), CTA_OP_ARCHIVE, cta_queue_create(), cta_queue_destroy(), CTA_ST_COMPLETE, g_nalerts, rec_alert(), cta_req_t::state, and submit().
Referenced by main().
test_cancel_transitions()
static void test_cancel_transitions (void) static
Definition at line 64 of file cta_exec_unittest.c.
References CHECK, cta_exec_run(), cta_exec_test_vtbl(), CTA_OP_CANCEL, cta_queue_create(), cta_queue_destroy(), CTA_ST_CANCELED, rec_alert(), cta_req_t::state, and submit().
Referenced by main().
test_prod_archive_fails_without_backend()
static void test_prod_archive_fails_without_backend (void) static
Definition at line 83 of file cta_exec_unittest.c.
References CHECK, cta_exec_prod_vtbl(), cta_exec_run(), CTA_OP_ARCHIVE, cta_queue_create(), cta_queue_destroy(), rec_alert(), and submit().
Referenced by main().
test_query_not_an_exec_op()
static void test_query_not_an_exec_op (void) static
Definition at line 74 of file cta_exec_unittest.c.
References CHECK, cta_exec_run(), cta_exec_test_vtbl(), CTA_OP_QUERY, cta_queue_create(), cta_queue_destroy(), rec_alert(), and submit().
Referenced by main().
test_retrieve_completes()
static void test_retrieve_completes (void) static
Definition at line 53 of file cta_exec_unittest.c.
References CHECK, cta_exec_run(), cta_exec_test_vtbl(), CTA_OP_RETRIEVE, cta_queue_create(), cta_queue_destroy(), CTA_ST_COMPLETE, g_nalerts, rec_alert(), cta_req_t::state, and submit().
Referenced by main().
Variable Documentation
g_alerts
char g_alerts[8][64] static
Definition at line 19 of file cta_exec_unittest.c.
Referenced by rec_alert().
g_fail
int g_fail static
Definition at line 12 of file cta_exec_unittest.c.
Referenced by main().
g_nalerts
int g_nalerts static
Definition at line 20 of file cta_exec_unittest.c.
Referenced by rec_alert(), test_archive_completes_with_alerts(), and test_retrieve_completes().