nginx-xrootd: src/protocols/ssi/svc_cta/cta_exec.h File Reference
cta_exec.h File Reference
#include "cta_queue.h"
Data Structures
struct cta_progress_t
struct cta_exec_vtbl_t
Functions
const cta_exec_vtbl_t * cta_exec_test_vtbl (void)
const cta_exec_vtbl_t * cta_exec_prod_vtbl (void)
int cta_exec_run (const cta_exec_vtbl_t *vt, cta_req_t *e, cta_progress_t *p)
Function Documentation
cta_exec_prod_vtbl()
const cta_exec_vtbl_t * cta_exec_prod_vtbl (void)
Definition at line 96 of file cta_exec.c.
References prod_vtbl.
Referenced by cta_exec_vtbl(), and test_prod_archive_fails_without_backend().
cta_exec_run()
int cta_exec_run (const cta_exec_vtbl_t * vt, cta_req_t * e, cta_progress_t * p)
Definition at line 102 of file cta_exec.c.
References cta_exec_vtbl_t::archive, cta_exec_vtbl_t::cancel, CTA_OP_ARCHIVE, CTA_OP_CANCEL, CTA_OP_QUERY, CTA_OP_RETRIEVE, CTA_OP_UNKNOWN, cta_request_t::op, cta_req_t::req, and cta_exec_vtbl_t::retrieve.
Referenced by brix_ssi_cta_process(), test_archive_completes_with_alerts(), test_cancel_transitions(), test_prod_archive_fails_without_backend(), test_query_not_an_exec_op(), and test_retrieve_completes().
cta_exec_test_vtbl()
const cta_exec_vtbl_t * cta_exec_test_vtbl (void)
Definition at line 63 of file cta_exec.c.
References test_vtbl.
Referenced by cta_exec_vtbl(), test_archive_completes_with_alerts(), test_cancel_transitions(), test_query_not_an_exec_op(), and test_retrieve_completes().