nginx-xrootd: src/protocols/ssi/svc_cta/cta_pb.h File Reference
cta_pb.h File Reference
#include <stddef.h>
#include <stdint.h>
Data Structures
struct cta_request_t
Enumerations
enum cta_op_t {
CTA_OP_ARCHIVE , CTA_OP_RETRIEVE , CTA_OP_CANCEL , CTA_OP_QUERY ,
CTA_OP_UNKNOWN
}
enum cta_rsp_type_t {
CTA_RSP_INVALID = 0 , CTA_RSP_SUCCESS = 1 , CTA_RSP_ERR_PROTOBUF = 2 , CTA_RSP_ERR_CTA = 3 ,
CTA_RSP_ERR_USER = 4
}
Functions
int cta_pb_decode_request (const unsigned char *buf, size_t len, cta_request_t *out)
int cta_pb_encode_response (cta_rsp_type_t type, const char *message_txt, uint64_t archive_id, unsigned char *out, size_t cap, size_t *out_len)
int cta_pb_encode_stream_header (const unsigned char *response, size_t response_len, unsigned char *out, size_t cap, size_t *out_len)
Enumeration Type Documentation
cta_op_t
enum cta_op_t
Enumerator
CTA_OP_ARCHIVE
CTA_OP_RETRIEVE
CTA_OP_CANCEL
CTA_OP_QUERY
CTA_OP_UNKNOWN
Definition at line 21 of file cta_pb.h.
cta_rsp_type_t
enum cta_rsp_type_t
Enumerator
CTA_RSP_INVALID
CTA_RSP_SUCCESS
CTA_RSP_ERR_PROTOBUF
CTA_RSP_ERR_CTA
CTA_RSP_ERR_USER
Definition at line 45 of file cta_pb.h.
Function Documentation
cta_pb_decode_request()
int cta_pb_decode_request (const unsigned char * buf, size_t len, cta_request_t * out)
Definition at line 249 of file cta_pb.c.
References CTA_OP_QUERY, CTA_OP_UNKNOWN, decode_notification(), pb_reader::end, F_REQ_ADMINCMD, F_REQ_NOTIFICATION, cta_request_t::op, pb_reader::p, pb_read_len_delim(), pb_read_tag(), pb_skip_field(), and PB_WT_LEN.
Referenced by brix_ssi_cta_process(), test_decode_archive(), test_decode_cancel(), test_decode_retrieve(), test_truncated_rejected(), and test_unknown_field_skipped().
cta_pb_encode_response()
int cta_pb_encode_response (cta_rsp_type_t type, const char * message_txt, uint64_t archive_id, unsigned char * out, size_t cap, size_t * out_len)
Definition at line 288 of file cta_pb.c.
References F_RSP_ARCHIVE_ID, F_RSP_MESSAGE_TXT, F_RSP_TYPE, pb_writer::len, pb_write_string(), and pb_write_varint_field().
Referenced by cta_respond(), test_encode_error_response(), test_encode_response(), and test_encode_stream_header().
cta_pb_encode_stream_header()
int cta_pb_encode_stream_header (const unsigned char * response, size_t response_len, unsigned char * out, size_t cap, size_t * out_len)
Definition at line 321 of file cta_pb.c.
References F_STREAM_HEADER, pb_writer::len, and pb_write_len_delim().
Referenced by test_encode_stream_header().