nginx-xrootd: src/protocols/ssi/svc_cta/cta_pb_unittest.c File Reference
cta_pb_unittest.c File Reference
#include "cta_pb.h"
#include "pb_wire.h"
#include <stdio.h>
#include <string.h>
Macros
#define CHECK(cond)
Functions
static size_t build_request (uint64_t event, const char *inst, const char *user, const char *grp, const char *lpath, uint64_t afid, unsigned char *out, size_t cap)
static void test_decode_archive (void)
static void test_decode_retrieve (void)
static void test_decode_cancel (void)
static void test_unknown_field_skipped (void)
static void test_truncated_rejected (void)
static void test_encode_response (void)
static void test_encode_error_response (void)
static void test_encode_stream_header (void)
int main (void)
Variables
static int g_fail
Macro Definition Documentation
CHECK
#define CHECK (cond)
Value:
    do { \
    if (!(cond)) { printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
                   g_fail++; } \
} while (0)
Definition at line 18 of file cta_pb_unittest.c.
Function Documentation
build_request()
static size_t build_request (uint64_t event, const char * inst, const char * user, const char * grp, const char * lpath, uint64_t afid, unsigned char * out, size_t cap) static
Definition at line 26 of file cta_pb_unittest.c.
References pb_writer::len, pb_write_len_delim(), pb_write_string(), and pb_write_varint_field().
Referenced by test_decode_archive(), test_decode_cancel(), test_decode_retrieve(), test_truncated_rejected(), and test_unknown_field_skipped().
main()
int main (void)
Definition at line 181 of file cta_pb_unittest.c.
References g_fail, test_decode_archive(), test_decode_cancel(), test_decode_retrieve(), test_encode_error_response(), test_encode_response(), test_encode_stream_header(), test_truncated_rejected(), and test_unknown_field_skipped().
test_decode_archive()
static void test_decode_archive (void) static
Definition at line 61 of file cta_pb_unittest.c.
References cta_request_t::archive_id, build_request(), CHECK, CTA_OP_ARCHIVE, cta_pb_decode_request(), cta_request_t::instance, cta_request_t::op, cta_request_t::owner_group, cta_request_t::owner_user, and cta_request_t::path.
Referenced by main().
test_decode_cancel()
static void test_decode_cancel (void) static
Definition at line 87 of file cta_pb_unittest.c.
References build_request(), CHECK, CTA_OP_CANCEL, cta_pb_decode_request(), and cta_request_t::op.
Referenced by main().
test_decode_retrieve()
static void test_decode_retrieve (void) static
Definition at line 76 of file cta_pb_unittest.c.
References build_request(), CHECK, CTA_OP_RETRIEVE, cta_pb_decode_request(), cta_request_t::op, and cta_request_t::path.
Referenced by main().
test_encode_error_response()
static void test_encode_error_response (void) static
Definition at line 148 of file cta_pb_unittest.c.
References CHECK, cta_pb_encode_response(), CTA_RSP_ERR_USER, pb_reader::end, pb_reader::p, pb_read_tag(), pb_read_varint(), and PB_WT_VARINT.
Referenced by main().
test_encode_response()
static void test_encode_response (void) static
Definition at line 120 of file cta_pb_unittest.c.
References CHECK, cta_pb_encode_response(), CTA_RSP_SUCCESS, pb_reader::end, pb_reader::p, pb_read_len_delim(), pb_read_tag(), pb_read_varint(), pb_skip_field(), PB_WT_LEN, and PB_WT_VARINT.
Referenced by main().
test_encode_stream_header()
static void test_encode_stream_header (void) static
Definition at line 164 of file cta_pb_unittest.c.
References CHECK, cta_pb_encode_response(), cta_pb_encode_stream_header(), CTA_RSP_SUCCESS, pb_reader::end, pb_reader::p, pb_read_len_delim(), pb_read_tag(), and PB_WT_LEN.
Referenced by main().
test_truncated_rejected()
static void test_truncated_rejected (void) static
Definition at line 111 of file cta_pb_unittest.c.
References build_request(), CHECK, and cta_pb_decode_request().
Referenced by main().
test_unknown_field_skipped()
static void test_unknown_field_skipped (void) static
Definition at line 97 of file cta_pb_unittest.c.
References build_request(), CHECK, CTA_OP_ARCHIVE, cta_pb_decode_request(), pb_writer::len, cta_request_t::op, cta_request_t::path, and pb_write_varint_field().
Referenced by main().
Variable Documentation
g_fail
int g_fail static
Definition at line 17 of file cta_pb_unittest.c.
Referenced by main().