nginx-xrootd: src/protocols/ssi/svc_cta/cta_queue.h File Reference
cta_queue.h File Reference
#include "cta_pb.h"
Data Structures
struct cta_req_t
struct brix_cta_queue_t
Macros
#define CTA_QUEUE_MAX 256
#define CTA_QUEUE_EACCES (-13) /* mirrors EACCES */
#define CTA_QUEUE_ENOENT (-2) /* mirrors ENOENT */
Enumerations
enum cta_state_t {
CTA_ST_SUBMITTED , CTA_ST_QUEUED , CTA_ST_ACTIVE , CTA_ST_COMPLETE ,
CTA_ST_FAILED , CTA_ST_CANCELED
}
Functions
brix_cta_queue_t * cta_queue_create (void)
void cta_queue_destroy (brix_cta_queue_t *q)
cta_req_t * cta_queue_submit (brix_cta_queue_t *q, const cta_request_t *r, const char *owner)
cta_req_t * cta_queue_find (brix_cta_queue_t *q, uint64_t id)
int cta_queue_transition (cta_req_t *e, cta_state_t to)
int cta_queue_cancel (brix_cta_queue_t *q, uint64_t id, const char *requester, int is_admin)
int cta_queue_active_count (const brix_cta_queue_t *q)
int cta_queue_open_journal (brix_cta_queue_t *q, const char *path)
Macro Definition Documentation
CTA_QUEUE_EACCES
#define CTA_QUEUE_EACCES (-13) /* mirrors EACCES */
Definition at line 62 of file cta_queue.h.
CTA_QUEUE_ENOENT
#define CTA_QUEUE_ENOENT (-2) /* mirrors ENOENT */
Definition at line 63 of file cta_queue.h.
CTA_QUEUE_MAX
#define CTA_QUEUE_MAX 256
Definition at line 18 of file cta_queue.h.
Enumeration Type Documentation
cta_state_t
enum cta_state_t
Enumerator
CTA_ST_SUBMITTED
CTA_ST_QUEUED
CTA_ST_ACTIVE
CTA_ST_COMPLETE
CTA_ST_FAILED
CTA_ST_CANCELED
Definition at line 20 of file cta_queue.h.
Function Documentation
cta_queue_active_count()
int cta_queue_active_count (const brix_cta_queue_t * q)
Definition at line 209 of file cta_queue.c.
References CTA_QUEUE_MAX, cta_req_t::in_use, is_terminal(), brix_cta_queue_t::slots, and cta_req_t::state.
Referenced by brix_ssi_cta_process(), and test_active_count().
cta_queue_cancel()
int cta_queue_cancel (brix_cta_queue_t * q, uint64_t id, const char * requester, int is_admin)
Definition at line 194 of file cta_queue.c.
References CTA_QUEUE_EACCES, CTA_QUEUE_ENOENT, cta_queue_find(), cta_queue_transition(), CTA_ST_CANCELED, and cta_req_t::owner.
Referenced by test_cancel_owner_admin_gate(), and test_owner_can_cancel().
cta_queue_create()
brix_cta_queue_t * cta_queue_create (void)
Definition at line 57 of file cta_queue.c.
References brix_cta_queue_t::next_id.
Referenced by cta_queue(), test_active_count(), test_archive_completes_with_alerts(), test_cancel_owner_admin_gate(), test_cancel_transitions(), test_journal_round_trip(), test_legal_and_illegal_transitions(), test_owner_can_cancel(), test_prod_archive_fails_without_backend(), test_query_not_an_exec_op(), test_retrieve_completes(), and test_submit_and_find().
cta_queue_destroy()
void cta_queue_destroy (brix_cta_queue_t * q)
Definition at line 67 of file cta_queue.c.
References brix_cta_queue_t::journal.
Referenced by test_active_count(), test_archive_completes_with_alerts(), test_cancel_owner_admin_gate(), test_cancel_transitions(), test_journal_round_trip(), test_legal_and_illegal_transitions(), test_owner_can_cancel(), test_prod_archive_fails_without_backend(), test_query_not_an_exec_op(), test_retrieve_completes(), and test_submit_and_find().
cta_queue_find()
cta_req_t * cta_queue_find (brix_cta_queue_t * q, uint64_t id)
Definition at line 168 of file cta_queue.c.
References CTA_QUEUE_MAX, cta_req_t::id, cta_req_t::in_use, and brix_cta_queue_t::slots.
Referenced by cta_queue_cancel(), test_journal_round_trip(), and test_submit_and_find().
cta_queue_open_journal()
int cta_queue_open_journal (brix_cta_queue_t * q, const char * path)
Definition at line 102 of file cta_queue.c.
References brix_cta_queue_t::journal, brix_cta_queue_t::next_id, op, cta_request_t::op, cta_req_t::owner, cta_request_t::path, replay_slot(), cta_req_t::req, and cta_req_t::state.
Referenced by cta_queue(), and test_journal_round_trip().
cta_queue_submit()
cta_req_t * cta_queue_submit (brix_cta_queue_t * q, const cta_request_t * r, const char * owner)
Definition at line 139 of file cta_queue.c.
References CTA_QUEUE_MAX, CTA_ST_SUBMITTED, cta_req_t::id, cta_req_t::in_use, journal_append(), brix_cta_queue_t::next_id, cta_req_t::owner, cta_req_t::queue, cta_req_t::req, brix_cta_queue_t::slots, and cta_req_t::state.
Referenced by brix_ssi_cta_process(), submit(), test_active_count(), test_cancel_owner_admin_gate(), test_journal_round_trip(), test_legal_and_illegal_transitions(), test_owner_can_cancel(), and test_submit_and_find().
cta_queue_transition()
int cta_queue_transition (cta_req_t * e, cta_state_t to)
Definition at line 181 of file cta_queue.c.
References journal_append(), cta_req_t::queue, cta_req_t::state, and transition_ok().
Referenced by cta_queue_cancel(), sim_lifecycle(), test_active_count(), test_cancel(), test_journal_round_trip(), and test_legal_and_illegal_transitions().