nginx-xrootd: src/protocols/ssi/svc_cta/cta_exec.c File Reference
cta_exec.c File Reference
#include "cta_exec.h"
#include <stddef.h>
Functions
static void emit (cta_progress_t *p, const char *msg)
static int sim_lifecycle (cta_req_t *e, cta_progress_t *p, const char *queued_msg, const char *active_msg)
static int test_archive (cta_req_t *e, cta_progress_t *p)
static int test_retrieve (cta_req_t *e, cta_progress_t *p)
static int test_cancel (cta_req_t *e)
const cta_exec_vtbl_t * cta_exec_test_vtbl (void)
static int prod_archive (cta_req_t *e, cta_progress_t *p)
static int prod_retrieve (cta_req_t *e, cta_progress_t *p)
const cta_exec_vtbl_t * cta_exec_prod_vtbl (void)
int cta_exec_run (const cta_exec_vtbl_t *vt, cta_req_t *e, cta_progress_t *p)
Variables
static const cta_exec_vtbl_t test_vtbl
static const cta_exec_vtbl_t prod_vtbl
Function Documentation
cta_exec_prod_vtbl()
const cta_exec_vtbl_t * cta_exec_prod_vtbl (void)
Definition at line 96 of file cta_exec.c.
References prod_vtbl.
Referenced by cta_exec_vtbl(), and test_prod_archive_fails_without_backend().
cta_exec_run()
int cta_exec_run (const cta_exec_vtbl_t * vt, cta_req_t * e, cta_progress_t * p)
Definition at line 102 of file cta_exec.c.
References cta_exec_vtbl_t::archive, cta_exec_vtbl_t::cancel, CTA_OP_ARCHIVE, CTA_OP_CANCEL, CTA_OP_QUERY, CTA_OP_RETRIEVE, CTA_OP_UNKNOWN, cta_request_t::op, cta_req_t::req, and cta_exec_vtbl_t::retrieve.
Referenced by brix_ssi_cta_process(), test_archive_completes_with_alerts(), test_cancel_transitions(), test_prod_archive_fails_without_backend(), test_query_not_an_exec_op(), and test_retrieve_completes().
cta_exec_test_vtbl()
const cta_exec_vtbl_t * cta_exec_test_vtbl (void)
Definition at line 63 of file cta_exec.c.
References test_vtbl.
Referenced by cta_exec_vtbl(), test_archive_completes_with_alerts(), test_cancel_transitions(), test_query_not_an_exec_op(), and test_retrieve_completes().
emit()
static void emit (cta_progress_t * p, const char * msg) static
Definition at line 14 of file cta_exec.c.
References cta_progress_t::alert, and cta_progress_t::ctx.
Referenced by head_lines(), prod_archive(), prod_retrieve(), and sim_lifecycle().
prod_archive()
static int prod_archive (cta_req_t * e, cta_progress_t * p) static
Definition at line 76 of file cta_exec.c.
References emit().
prod_retrieve()
static int prod_retrieve (cta_req_t * e, cta_progress_t * p) static
Definition at line 84 of file cta_exec.c.
References emit().
sim_lifecycle()
static int sim_lifecycle (cta_req_t * e, cta_progress_t * p, const char * queued_msg, const char * active_msg) static
Definition at line 23 of file cta_exec.c.
References cta_queue_transition(), CTA_ST_ACTIVE, CTA_ST_COMPLETE, CTA_ST_QUEUED, and emit().
Referenced by test_archive(), and test_retrieve().
test_archive()
static int test_archive (cta_req_t * e, cta_progress_t * p) static
Definition at line 41 of file cta_exec.c.
References sim_lifecycle().
test_cancel()
static int test_cancel (cta_req_t * e) static
Definition at line 53 of file cta_exec.c.
References cta_queue_transition(), and CTA_ST_CANCELED.
test_retrieve()
static int test_retrieve (cta_req_t * e, cta_progress_t * p) static
Definition at line 47 of file cta_exec.c.
References sim_lifecycle().
Variable Documentation
prod_vtbl
const cta_exec_vtbl_t prod_vtbl static
Initial value:
= {
    prod_archive, prod_retrieve, test_cancel
}
Definition at line 91 of file cta_exec.c.
Referenced by cta_exec_prod_vtbl().
test_vtbl
const cta_exec_vtbl_t test_vtbl static
Initial value:
= {
    test_archive, test_retrieve, test_cancel
}
Definition at line 58 of file cta_exec.c.
Referenced by cta_exec_test_vtbl().