nginx-xrootd: src/protocols/ssi/svc_cta/cta_queue_unittest.c File Reference
cta_queue_unittest.c File Reference
#include "cta_queue.h"
#include <stdio.h>
#include <string.h>
Macros
#define CHECK(cond)
Functions
static cta_request_t mk (cta_op_t op)
static void test_submit_and_find (void)
static void test_legal_and_illegal_transitions (void)
static void test_cancel_owner_admin_gate (void)
static void test_owner_can_cancel (void)
static void test_active_count (void)
static void test_journal_round_trip (void)
int main (void)
Variables
static int g_fail
Macro Definition Documentation
CHECK
#define CHECK (cond)
Value:
    do { \
    if (!(cond)) { printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
                   g_fail++; } \
} while (0)
Definition at line 13 of file cta_queue_unittest.c.
Function Documentation
main()
int main (void)
Definition at line 133 of file cta_queue_unittest.c.
References g_fail, test_active_count(), test_cancel_owner_admin_gate(), test_journal_round_trip(), test_legal_and_illegal_transitions(), test_owner_can_cancel(), and test_submit_and_find().
mk()
static cta_request_t mk (cta_op_t op) static
Definition at line 18 of file cta_queue_unittest.c.
References op, and cta_request_t::op.
Referenced by brixcvmfs_prepare_cache_dir(), brixcvmfs_prepare_tmp_dir(), ov_descend_dir(), ov_walk_parent_mk(), s3_list_parse_max_keys(), test_active_count(), test_cancel_owner_admin_gate(), test_journal_round_trip(), test_legal_and_illegal_transitions(), test_owner_can_cancel(), and test_submit_and_find().
test_active_count()
static void test_active_count (void) static
Definition at line 81 of file cta_queue_unittest.c.
References CHECK, CTA_OP_ARCHIVE, cta_queue_active_count(), cta_queue_create(), cta_queue_destroy(), cta_queue_submit(), cta_queue_transition(), CTA_ST_ACTIVE, CTA_ST_COMPLETE, CTA_ST_QUEUED, and mk().
Referenced by main().
test_cancel_owner_admin_gate()
static void test_cancel_owner_admin_gate (void) static
Definition at line 53 of file cta_queue_unittest.c.
References CHECK, CTA_OP_RETRIEVE, cta_queue_cancel(), cta_queue_create(), cta_queue_destroy(), CTA_QUEUE_EACCES, CTA_QUEUE_ENOENT, cta_queue_submit(), CTA_ST_CANCELED, cta_req_t::id, mk(), and cta_req_t::state.
Referenced by main().
test_journal_round_trip()
static void test_journal_round_trip (void) static
Definition at line 96 of file cta_queue_unittest.c.
References CHECK, CTA_OP_ARCHIVE, cta_queue_create(), cta_queue_destroy(), cta_queue_find(), cta_queue_open_journal(), cta_queue_submit(), cta_queue_transition(), CTA_ST_ACTIVE, CTA_ST_COMPLETE, CTA_ST_QUEUED, CTA_ST_SUBMITTED, cta_req_t::id, mk(), cta_req_t::owner, and cta_req_t::state.
Referenced by main().
test_legal_and_illegal_transitions()
static void test_legal_and_illegal_transitions (void) static
Definition at line 39 of file cta_queue_unittest.c.
References CHECK, CTA_OP_ARCHIVE, cta_queue_create(), cta_queue_destroy(), cta_queue_submit(), cta_queue_transition(), CTA_ST_ACTIVE, CTA_ST_COMPLETE, CTA_ST_QUEUED, mk(), and cta_req_t::state.
Referenced by main().
test_owner_can_cancel()
static void test_owner_can_cancel (void) static
Definition at line 71 of file cta_queue_unittest.c.
References CHECK, CTA_OP_ARCHIVE, cta_queue_cancel(), cta_queue_create(), cta_queue_destroy(), cta_queue_submit(), CTA_ST_CANCELED, cta_req_t::id, mk(), and cta_req_t::state.
Referenced by main().
test_submit_and_find()
static void test_submit_and_find (void) static
Definition at line 26 of file cta_queue_unittest.c.
References CHECK, CTA_OP_ARCHIVE, cta_queue_create(), cta_queue_destroy(), cta_queue_find(), cta_queue_submit(), CTA_ST_SUBMITTED, cta_req_t::id, mk(), cta_req_t::owner, and cta_req_t::state.
Referenced by main().
Variable Documentation
g_fail
int g_fail static
Definition at line 12 of file cta_queue_unittest.c.
Referenced by main().