nginx-xrootd: src/protocols/ssi/svc_cta/cta_queue.c File Reference
cta_queue.c File Reference
#include "cta_queue.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
static void journal_append (brix_cta_queue_t *q, const cta_req_t *e)
static int transition_ok (cta_state_t from, cta_state_t to)
static int is_terminal (cta_state_t s)
brix_cta_queue_t * cta_queue_create (void)
void cta_queue_destroy (brix_cta_queue_t *q)
static cta_req_t * replay_slot (brix_cta_queue_t *q, uint64_t id)
int cta_queue_open_journal (brix_cta_queue_t *q, const char *path)
cta_req_t * cta_queue_submit (brix_cta_queue_t *q, const cta_request_t *r, const char *owner)
cta_req_t * cta_queue_find (brix_cta_queue_t *q, uint64_t id)
int cta_queue_transition (cta_req_t *e, cta_state_t to)
int cta_queue_cancel (brix_cta_queue_t *q, uint64_t id, const char *requester, int is_admin)
int cta_queue_active_count (const brix_cta_queue_t *q)
Function Documentation
cta_queue_active_count()
int cta_queue_active_count (const brix_cta_queue_t * q)
Definition at line 204 of file cta_queue.c.
References CTA_QUEUE_MAX, cta_req_t::in_use, is_terminal(), brix_cta_queue_t::slots, and cta_req_t::state.
Referenced by brix_ssi_cta_process(), and test_active_count().
cta_queue_cancel()
int cta_queue_cancel (brix_cta_queue_t * q, uint64_t id, const char * requester, int is_admin)
Definition at line 189 of file cta_queue.c.
References CTA_QUEUE_EACCES, CTA_QUEUE_ENOENT, cta_queue_find(), cta_queue_transition(), CTA_ST_CANCELED, and cta_req_t::owner.
Referenced by test_cancel_owner_admin_gate(), and test_owner_can_cancel().
cta_queue_create()
brix_cta_queue_t * cta_queue_create (void)
Definition at line 54 of file cta_queue.c.
References brix_cta_queue_t::next_id.
Referenced by cta_queue(), test_active_count(), test_archive_completes_with_alerts(), test_cancel_owner_admin_gate(), test_cancel_transitions(), test_journal_round_trip(), test_legal_and_illegal_transitions(), test_owner_can_cancel(), test_prod_archive_fails_without_backend(), test_query_not_an_exec_op(), test_retrieve_completes(), and test_submit_and_find().
cta_queue_destroy()
void cta_queue_destroy (brix_cta_queue_t * q)
Definition at line 64 of file cta_queue.c.
References brix_cta_queue_t::journal.
Referenced by test_active_count(), test_archive_completes_with_alerts(), test_cancel_owner_admin_gate(), test_cancel_transitions(), test_journal_round_trip(), test_legal_and_illegal_transitions(), test_owner_can_cancel(), test_prod_archive_fails_without_backend(), test_query_not_an_exec_op(), test_retrieve_completes(), and test_submit_and_find().
cta_queue_find()
cta_req_t * cta_queue_find (brix_cta_queue_t * q, uint64_t id)
Definition at line 163 of file cta_queue.c.
References CTA_QUEUE_MAX, cta_req_t::id, cta_req_t::in_use, and brix_cta_queue_t::slots.
Referenced by cta_queue_cancel(), test_journal_round_trip(), and test_submit_and_find().
cta_queue_open_journal()
int cta_queue_open_journal (brix_cta_queue_t * q, const char * path)
Definition at line 97 of file cta_queue.c.
References brix_cta_queue_t::journal, brix_cta_queue_t::next_id, cta_request_t::op, cta_req_t::owner, cta_request_t::path, replay_slot(), cta_req_t::req, and cta_req_t::state.
Referenced by cta_queue(), and test_journal_round_trip().
cta_queue_submit()
cta_req_t * cta_queue_submit (brix_cta_queue_t * q, const cta_request_t * r, const char * owner)
Definition at line 134 of file cta_queue.c.
References CTA_QUEUE_MAX, CTA_ST_SUBMITTED, cta_req_t::id, cta_req_t::in_use, journal_append(), brix_cta_queue_t::next_id, cta_req_t::owner, cta_req_t::queue, cta_req_t::req, brix_cta_queue_t::slots, and cta_req_t::state.
Referenced by brix_ssi_cta_process(), submit(), test_active_count(), test_cancel_owner_admin_gate(), test_journal_round_trip(), test_legal_and_illegal_transitions(), test_owner_can_cancel(), and test_submit_and_find().
cta_queue_transition()
int cta_queue_transition (cta_req_t * e, cta_state_t to)
Definition at line 176 of file cta_queue.c.
References journal_append(), cta_req_t::queue, cta_req_t::state, and transition_ok().
Referenced by cta_queue_cancel(), sim_lifecycle(), test_active_count(), test_cancel(), test_journal_round_trip(), and test_legal_and_illegal_transitions().
is_terminal()
static int is_terminal (cta_state_t s) static
Definition at line 48 of file cta_queue.c.
References CTA_ST_CANCELED, CTA_ST_COMPLETE, CTA_ST_FAILED, and s.
Referenced by cta_queue_active_count().
journal_append()
static void journal_append (brix_cta_queue_t * q, const cta_req_t * e) static
Definition at line 12 of file cta_queue.c.
References cta_req_t::id, brix_cta_queue_t::journal, cta_request_t::op, cta_req_t::owner, cta_request_t::path, cta_req_t::req, and cta_req_t::state.
Referenced by cta_queue_submit(), and cta_queue_transition().
replay_slot()
static cta_req_t * replay_slot (brix_cta_queue_t * q, uint64_t id) static
Definition at line 74 of file cta_queue.c.
References CTA_QUEUE_MAX, cta_req_t::id, cta_req_t::in_use, cta_req_t::queue, and brix_cta_queue_t::slots.
Referenced by cta_queue_open_journal().
transition_ok()
static int transition_ok (cta_state_t from, cta_state_t to) static
Definition at line 28 of file cta_queue.c.
References CTA_ST_ACTIVE, CTA_ST_CANCELED, CTA_ST_COMPLETE, CTA_ST_FAILED, CTA_ST_QUEUED, and CTA_ST_SUBMITTED.
Referenced by cta_queue_transition().