nginx-xrootd: src/protocols/ssi/svc_cta/cta_service.c File Reference
cta_service.c File Reference
#include "cta_service.h"
#include "cta_pb.h"
#include "cta_queue.h"
#include "cta_exec.h"
#include <stdio.h>
#include <string.h>
Functions
void brix_ssi_cta_configure (const char *journal_path, int use_prod_executor)
static brix_cta_queue_t * cta_queue (void)
static const cta_exec_vtbl_t * cta_exec_vtbl (void)
static void cta_prog_alert (void *ctx, const char *msg)
static void cta_respond (brix_ssi_responder_t *r, cta_rsp_type_t type, const char *msg, uint64_t archive_id)
int brix_ssi_cta_process (const unsigned char *req, size_t req_len, brix_ssi_responder_t *r)
Variables
static brix_cta_queue_t * g_cta_queue
static char g_cta_journal [1024]
static int g_cta_use_prod
Function Documentation
brix_ssi_cta_configure()
void brix_ssi_cta_configure (const char * journal_path, int use_prod_executor)
Definition at line 25 of file cta_service.c.
References g_cta_journal, and g_cta_use_prod.
Referenced by ssi_open_cta_gate().
brix_ssi_cta_process()
int brix_ssi_cta_process (const unsigned char * req, size_t req_len, brix_ssi_responder_t * r)
Definition at line 79 of file cta_service.c.
References cta_request_t::archive_id, cta_exec_run(), cta_exec_vtbl(), CTA_OP_QUERY, CTA_OP_UNKNOWN, cta_pb_decode_request(), cta_prog_alert(), cta_queue(), cta_queue_active_count(), cta_queue_submit(), cta_respond(), CTA_RSP_ERR_CTA, CTA_RSP_ERR_PROTOBUF, CTA_RSP_ERR_USER, CTA_RSP_SUCCESS, cta_request_t::op, cta_request_t::owner_user, and cta_req_t::req.
Referenced by brix_ssi_provider_lookup().
cta_exec_vtbl()
static const cta_exec_vtbl_t * cta_exec_vtbl (void) static
Definition at line 50 of file cta_service.c.
References cta_exec_prod_vtbl(), cta_exec_test_vtbl(), and g_cta_use_prod.
Referenced by brix_ssi_cta_process().
cta_prog_alert()
static void cta_prog_alert (void * ctx, const char * msg) static
Definition at line 57 of file cta_service.c.
Referenced by brix_ssi_cta_process().
cta_queue()
static brix_cta_queue_t * cta_queue (void) static
Definition at line 36 of file cta_service.c.
References cta_queue_create(), cta_queue_open_journal(), g_cta_journal, and g_cta_queue.
Referenced by brix_ssi_cta_process().
cta_respond()
static void cta_respond (brix_ssi_responder_t * r, cta_rsp_type_t type, const char * msg, uint64_t archive_id) static
Definition at line 65 of file cta_service.c.
References cta_pb_encode_response().
Referenced by brix_ssi_cta_process().
Variable Documentation
g_cta_journal
char g_cta_journal[1024] static
Definition at line 21 of file cta_service.c.
Referenced by brix_ssi_cta_configure(), and cta_queue().
g_cta_queue
brix_cta_queue_t* g_cta_queue static
Definition at line 20 of file cta_service.c.
Referenced by cta_queue().
g_cta_use_prod
int g_cta_use_prod static
Definition at line 22 of file cta_service.c.
Referenced by brix_ssi_cta_configure(), and cta_exec_vtbl().