nginx-xrootd: src/protocols/ssi/svc_cta/cta_pb.c File Reference
cta_pb.c File Reference
#include "cta_pb.h"
#include "pb_wire.h"
#include <string.h>
Macros
#define F_REQ_NOTIFICATION 1
#define F_REQ_ADMINCMD 2
#define F_NOTIF_WF 1
#define F_NOTIF_CLI 2
#define F_NOTIF_FILE 4
#define F_WF_EVENT 1
#define F_WF_INSTANCE 5
#define F_CLIENT_USER 1
#define F_META_LPATH 11
#define F_META_ARCHIVE_ID 15
#define F_META_REQUEST_ID 999
#define F_SERVICE_NAME 1
#define F_REQUESTER_USERNAME 1
#define F_REQUESTER_GROUPNAME 2
#define F_RSP_TYPE 1
#define F_RSP_MESSAGE_TXT 3
#define F_RSP_ARCHIVE_ID 5
#define F_STREAM_HEADER 1
#define EV_CLOSEW 4
#define EV_PREPARE 6
#define EV_ABORT_PREPARE 8
Functions
static void copy_str (char *dst, size_t dst_sz, const unsigned char *src, size_t n)
static int decode_service (pb_reader *r, cta_request_t *out)
static int decode_workflow (pb_reader *r, cta_request_t *out)
static int decode_requester (pb_reader *r, cta_request_t *out)
static int decode_client (pb_reader *r, cta_request_t *out)
static int decode_metadata (pb_reader *r, cta_request_t *out)
static int decode_notification (pb_reader *r, cta_request_t *out)
int cta_pb_decode_request (const unsigned char *buf, size_t len, cta_request_t *out)
int cta_pb_encode_response (cta_rsp_type_t type, const char *message_txt, uint64_t archive_id, unsigned char *out, size_t cap, size_t *out_len)
int cta_pb_encode_stream_header (const unsigned char *response, size_t response_len, unsigned char *out, size_t cap, size_t *out_len)
Macro Definition Documentation
EV_ABORT_PREPARE
#define EV_ABORT_PREPARE 8
Definition at line 59 of file cta_pb.c.
EV_CLOSEW
#define EV_CLOSEW 4
Definition at line 57 of file cta_pb.c.
EV_PREPARE
#define EV_PREPARE 6
Definition at line 58 of file cta_pb.c.
F_CLIENT_USER
#define F_CLIENT_USER 1
Definition at line 44 of file cta_pb.c.
F_META_ARCHIVE_ID
#define F_META_ARCHIVE_ID 15
Definition at line 46 of file cta_pb.c.
F_META_LPATH
#define F_META_LPATH 11
Definition at line 45 of file cta_pb.c.
F_META_REQUEST_ID
#define F_META_REQUEST_ID 999
Definition at line 47 of file cta_pb.c.
F_NOTIF_CLI
#define F_NOTIF_CLI 2
Definition at line 40 of file cta_pb.c.
F_NOTIF_FILE
#define F_NOTIF_FILE 4
Definition at line 41 of file cta_pb.c.
F_NOTIF_WF
#define F_NOTIF_WF 1
Definition at line 39 of file cta_pb.c.
F_REQ_ADMINCMD
#define F_REQ_ADMINCMD 2
Definition at line 38 of file cta_pb.c.
F_REQ_NOTIFICATION
#define F_REQ_NOTIFICATION 1
Definition at line 37 of file cta_pb.c.
F_REQUESTER_GROUPNAME
#define F_REQUESTER_GROUPNAME 2
Definition at line 50 of file cta_pb.c.
F_REQUESTER_USERNAME
#define F_REQUESTER_USERNAME 1
Definition at line 49 of file cta_pb.c.
F_RSP_ARCHIVE_ID
#define F_RSP_ARCHIVE_ID 5
Definition at line 53 of file cta_pb.c.
F_RSP_MESSAGE_TXT
#define F_RSP_MESSAGE_TXT 3
Definition at line 52 of file cta_pb.c.
F_RSP_TYPE
#define F_RSP_TYPE 1
Definition at line 51 of file cta_pb.c.
F_SERVICE_NAME
#define F_SERVICE_NAME 1
Definition at line 48 of file cta_pb.c.
F_STREAM_HEADER
#define F_STREAM_HEADER 1
Definition at line 54 of file cta_pb.c.
F_WF_EVENT
#define F_WF_EVENT 1
Definition at line 42 of file cta_pb.c.
F_WF_INSTANCE
#define F_WF_INSTANCE 5
Definition at line 43 of file cta_pb.c.
Function Documentation
copy_str()
static void copy_str (char * dst, size_t dst_sz, const unsigned char * src, size_t n) static
Definition at line 63 of file cta_pb.c.
Referenced by decode_metadata(), decode_requester(), and decode_service().
cta_pb_decode_request()
int cta_pb_decode_request (const unsigned char * buf, size_t len, cta_request_t * out)
Definition at line 249 of file cta_pb.c.
References CTA_OP_QUERY, CTA_OP_UNKNOWN, decode_notification(), pb_reader::end, F_REQ_ADMINCMD, F_REQ_NOTIFICATION, cta_request_t::op, pb_reader::p, pb_read_len_delim(), pb_read_tag(), pb_skip_field(), and PB_WT_LEN.
Referenced by brix_ssi_cta_process(), test_decode_archive(), test_decode_cancel(), test_decode_retrieve(), test_truncated_rejected(), and test_unknown_field_skipped().
cta_pb_encode_response()
int cta_pb_encode_response (cta_rsp_type_t type, const char * message_txt, uint64_t archive_id, unsigned char * out, size_t cap, size_t * out_len)
Definition at line 288 of file cta_pb.c.
References F_RSP_ARCHIVE_ID, F_RSP_MESSAGE_TXT, F_RSP_TYPE, pb_writer::len, pb_write_string(), and pb_write_varint_field().
Referenced by cta_respond(), test_encode_error_response(), test_encode_response(), and test_encode_stream_header().
cta_pb_encode_stream_header()
int cta_pb_encode_stream_header (const unsigned char * response, size_t response_len, unsigned char * out, size_t cap, size_t * out_len)
Definition at line 321 of file cta_pb.c.
References F_STREAM_HEADER, pb_writer::len, and pb_write_len_delim().
Referenced by test_encode_stream_header().
decode_client()
static int decode_client (pb_reader * r, cta_request_t * out) static
Definition at line 160 of file cta_pb.c.
References decode_requester(), pb_reader::end, F_CLIENT_USER, pb_reader::p, pb_read_len_delim(), pb_read_tag(), pb_skip_field(), and PB_WT_LEN.
Referenced by decode_notification().
decode_metadata()
static int decode_metadata (pb_reader * r, cta_request_t * out) static
Definition at line 186 of file cta_pb.c.
References cta_request_t::archive_id, copy_str(), pb_reader::end, F_META_ARCHIVE_ID, F_META_LPATH, F_META_REQUEST_ID, pb_reader::p, cta_request_t::path, pb_read_len_delim(), pb_read_tag(), pb_read_varint(), pb_skip_field(), PB_WT_LEN, PB_WT_VARINT, and cta_request_t::request_id.
Referenced by decode_notification().
decode_notification()
static int decode_notification (pb_reader * r, cta_request_t * out) static
Definition at line 219 of file cta_pb.c.
References decode_client(), decode_metadata(), decode_workflow(), pb_reader::end, F_NOTIF_CLI, F_NOTIF_FILE, F_NOTIF_WF, pb_reader::p, pb_read_len_delim(), pb_read_tag(), pb_skip_field(), and PB_WT_LEN.
Referenced by cta_pb_decode_request().
decode_requester()
static int decode_requester (pb_reader * r, cta_request_t * out) static
Definition at line 132 of file cta_pb.c.
References copy_str(), pb_reader::end, F_REQUESTER_GROUPNAME, F_REQUESTER_USERNAME, cta_request_t::owner_group, cta_request_t::owner_user, pb_reader::p, pb_read_len_delim(), pb_read_tag(), pb_skip_field(), and PB_WT_LEN.
Referenced by decode_client().
decode_service()
static int decode_service (pb_reader * r, cta_request_t * out) static
Definition at line 74 of file cta_pb.c.
References copy_str(), pb_reader::end, F_SERVICE_NAME, cta_request_t::instance, pb_reader::p, pb_read_len_delim(), pb_read_tag(), pb_skip_field(), and PB_WT_LEN.
Referenced by decode_workflow().
decode_workflow()
static int decode_workflow (pb_reader * r, cta_request_t * out) static
Definition at line 97 of file cta_pb.c.
References CTA_OP_ARCHIVE, CTA_OP_CANCEL, CTA_OP_RETRIEVE, CTA_OP_UNKNOWN, decode_service(), pb_reader::end, EV_ABORT_PREPARE, EV_CLOSEW, EV_PREPARE, F_WF_EVENT, F_WF_INSTANCE, cta_request_t::op, pb_reader::p, pb_read_len_delim(), pb_read_tag(), pb_read_varint(), pb_skip_field(), PB_WT_LEN, and PB_WT_VARINT.
Referenced by decode_notification().