nginx-xrootd: src/protocols/cvmfs/cvmfs_module_internal.h File Reference
cvmfs_module_internal.h File Reference
#include "cvmfs.h"
Functions
char * cvmfs_conf_upstream_allow (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * cvmfs_conf_repo_authz (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * cvmfs_conf_qos (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * ngx_http_brix_cvmfs_set_coords (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * cvmfs_geo_rank_config (ngx_conf_t *cf, ngx_http_brix_cvmfs_loc_conf_t *conf)
char * cvmfs_merge_cache (ngx_conf_t *cf, ngx_http_brix_cvmfs_loc_conf_t *conf)
char * ngx_http_brix_cvmfs_merge_loc_conf (ngx_conf_t *cf, void *parent, void *child)
Function Documentation
cvmfs_conf_qos()
char * cvmfs_conf_qos (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 299 of file secure.c.
References c, brix_cvmfs_qos_t::fills, brix_cvmfs_qos_t::name, and brix_cvmfs_qos_t::sub.
cvmfs_conf_repo_authz()
char * cvmfs_conf_repo_authz (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 125 of file secure.c.
References c, brix_cvmfs_repo_authz_t::issuers, brix_cvmfs_repo_authz_t::registry, and brix_cvmfs_repo_authz_t::repo.
cvmfs_conf_upstream_allow()
char * cvmfs_conf_upstream_allow (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 84 of file cvmfs_module_georank.c.
References c.
cvmfs_geo_rank_config()
char * cvmfs_geo_rank_config (ngx_conf_t * cf, ngx_http_brix_cvmfs_loc_conf_t * conf)
Definition at line 282 of file cvmfs_module_georank.c.
References cvmfs_geo_apply_ranks(), and cvmfs_geo_compute_metrics().
Referenced by cvmfs_merge_cache().
cvmfs_merge_cache()
char * cvmfs_merge_cache (ngx_conf_t * cf, ngx_http_brix_cvmfs_loc_conf_t * conf)
Definition at line 124 of file cvmfs_module_build.c.
References brix_export_root_opts_t::allow_write, ngx_http_brix_shared_conf_t::allow_write, BRIX_AF_AUTO, brix_cvmfs_reject_unsupported(), brix_cvmfs_rtt_register(), BRIX_CVMFS_SELECT_GEO, BRIX_CVMFS_SELECT_RTT, brix_http_open_rootfd(), brix_prepare_export_root(), brix_storage_backend_posix_root(), brix_tier_register_stores(), brix_vfs_backend_config_str(), ngx_http_brix_shared_conf_t::cache_client_hold, ngx_http_brix_shared_conf_t::cache_cvmfs_master_key, ngx_http_brix_shared_conf_t::cache_fill_max_life, ngx_http_brix_shared_conf_t::cache_manifest_ttl, ngx_http_brix_shared_conf_t::cache_offline_ttl, ngx_http_brix_shared_conf_t::cache_quarantine_dir, brix_export_root_opts_t::canon_size, brix_cvmfs_conf_t::client_hold, ngx_http_brix_cvmfs_loc_conf_t::common, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, cvmfs_geo_rank_config(), brix_export_root_opts_t::directive_name, brix_cvmfs_conf_t::fill_max_life, brix_cvmfs_conf_t::manifest_ttl, brix_cvmfs_conf_t::master_key, brix_cvmfs_conf_t::offline_ttl, brix_cvmfs_conf_t::origin_coords, brix_cvmfs_conf_t::origin_select, ngx_http_brix_shared_conf_t::pblock_block_size, brix_cvmfs_conf_t::quarantine_dir, brix_export_root_opts_t::required, ngx_http_brix_shared_conf_t::root, ngx_http_brix_shared_conf_t::root_canon, brix_cvmfs_conf_t::rtt_interval, ngx_http_brix_shared_conf_t::storage_backend, and ngx_http_brix_shared_conf_t::thread_pool_name.
Referenced by ngx_http_brix_cvmfs_merge_loc_conf().
ngx_http_brix_cvmfs_merge_loc_conf()
char * ngx_http_brix_cvmfs_merge_loc_conf (ngx_conf_t * cf, void * parent, void * child)
Definition at line 383 of file cvmfs_module_merge.c.
References ngx_http_brix_cvmfs_loc_conf_t::cvmfs, cvmfs_merge_cache(), cvmfs_merge_preamble(), cvmfs_merge_resilience(), cvmfs_merge_secure(), cvmfs_merge_upstreams(), and brix_cvmfs_conf_t::enable.
ngx_http_brix_cvmfs_set_coords()
char * ngx_http_brix_cvmfs_set_coords (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 297 of file cvmfs_module_georank.c.
References c, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, cvmfs_parse_latlon(), and brix_cvmfs_conf_t::origin_coords.