nginx-xrootd: src/protocols/cvmfs/cvmfs_module_build.c File Reference
cvmfs_module_build.c File Reference
#include "cvmfs.h"
#include "cvmfs_module_internal.h"
#include "core/config/config.h"
#include "core/config/root_prepare.h"
#include "core/config/http_rootfd.h"
#include "core/config/http_common.h"
#include "core/compat/alloc_guard.h"
#include "fs/cache/verify.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "origin_geo.h"
#include "fs/backend/http/sd_http.h"
#include "auth/token/issuer_registry.h"
#include "fs/backend/cache/sd_cache.h"
#include "fs/cache/origin/s3_transport.h"
#include <stdlib.h>
Functions
static char * brix_cvmfs_reject_unsupported (ngx_conf_t *cf, ngx_http_brix_cvmfs_loc_conf_t *conf)
char * cvmfs_merge_cache (ngx_conf_t *cf, ngx_http_brix_cvmfs_loc_conf_t *conf)
Function Documentation
brix_cvmfs_reject_unsupported()
static char * brix_cvmfs_reject_unsupported (ngx_conf_t * cf, ngx_http_brix_cvmfs_loc_conf_t * conf) static
Definition at line 70 of file cvmfs_module_build.c.
References ngx_http_brix_shared_conf_t::allow_write, ngx_http_brix_shared_conf_t::cache_slice_size, ngx_http_brix_cvmfs_loc_conf_t::common, ngx_http_brix_shared_conf_t::stage_enable, and ngx_http_brix_shared_conf_t::stage_store.
Referenced by cvmfs_merge_cache().
cvmfs_merge_cache()
char * cvmfs_merge_cache (ngx_conf_t * cf, ngx_http_brix_cvmfs_loc_conf_t * conf)
Definition at line 124 of file cvmfs_module_build.c.
References brix_export_root_opts_t::allow_write, ngx_http_brix_shared_conf_t::allow_write, BRIX_AF_AUTO, brix_cvmfs_reject_unsupported(), brix_cvmfs_rtt_register(), BRIX_CVMFS_SELECT_GEO, BRIX_CVMFS_SELECT_RTT, brix_http_open_rootfd(), brix_prepare_export_root(), brix_storage_backend_posix_root(), brix_tier_register_stores(), brix_vfs_backend_config_str(), ngx_http_brix_shared_conf_t::cache_client_hold, ngx_http_brix_shared_conf_t::cache_fill_max_life, ngx_http_brix_shared_conf_t::cache_manifest_ttl, ngx_http_brix_shared_conf_t::cache_quarantine_dir, brix_export_root_opts_t::canon_size, brix_cvmfs_conf_t::client_hold, ngx_http_brix_cvmfs_loc_conf_t::common, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, cvmfs_geo_rank_config(), brix_export_root_opts_t::directive_name, brix_cvmfs_conf_t::fill_max_life, brix_cvmfs_conf_t::manifest_ttl, brix_cvmfs_conf_t::origin_coords, brix_cvmfs_conf_t::origin_select, ngx_http_brix_shared_conf_t::pblock_block_size, brix_cvmfs_conf_t::quarantine_dir, brix_export_root_opts_t::required, ngx_http_brix_shared_conf_t::root, ngx_http_brix_shared_conf_t::root_canon, brix_cvmfs_conf_t::rtt_interval, ngx_http_brix_shared_conf_t::storage_backend, and ngx_http_brix_shared_conf_t::thread_pool_name.
Referenced by ngx_http_brix_cvmfs_merge_loc_conf().