nginx-xrootd: src/protocols/cvmfs/cvmfs_module_georank.c File Reference
cvmfs_module_georank.c File Reference
#include "cvmfs.h"
#include "cvmfs_module_internal.h"
#include "core/config/config.h"
#include "core/config/root_prepare.h"
#include "core/config/http_rootfd.h"
#include "core/config/http_common.h"
#include "core/compat/alloc_guard.h"
#include "fs/cache/verify.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "origin_geo.h"
#include "fs/backend/http/sd_http.h"
#include "auth/token/issuer_registry.h"
#include "fs/backend/cache/sd_cache.h"
#include "fs/cache/origin/s3_transport.h"
#include <stdlib.h>
Data Structures
struct cvmfs_geo_calc_t
Functions
static int cvmfs_parse_latlon (const ngx_str_t *v, double *lat, double *lon)
char * cvmfs_conf_upstream_allow (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static char * cvmfs_geo_compute_metrics (ngx_conf_t *cf, ngx_http_brix_cvmfs_loc_conf_t *conf, cvmfs_geo_calc_t *calc)
static void cvmfs_geo_apply_ranks (ngx_conf_t *cf, ngx_http_brix_cvmfs_loc_conf_t *conf, const cvmfs_geo_calc_t *calc)
char * cvmfs_geo_rank_config (ngx_conf_t *cf, ngx_http_brix_cvmfs_loc_conf_t *conf)
char * ngx_http_brix_cvmfs_set_coords (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Function Documentation
cvmfs_conf_upstream_allow()
char * cvmfs_conf_upstream_allow (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 84 of file cvmfs_module_georank.c.
References c.
cvmfs_geo_apply_ranks()
static void cvmfs_geo_apply_ranks (ngx_conf_t * cf, ngx_http_brix_cvmfs_loc_conf_t * conf, const cvmfs_geo_calc_t * calc) static
Definition at line 238 of file cvmfs_module_georank.c.
References brix_cvmfs_rank_by_metric(), brix_vfs_backend_http_endpoint_at(), brix_vfs_backend_set_http_ranks(), ngx_http_brix_cvmfs_loc_conf_t::common, cvmfs_geo_calc_t::here_lat, cvmfs_geo_calc_t::here_lon, host, cvmfs_geo_calc_t::metric, cvmfs_geo_calc_t::n, port, ngx_http_brix_shared_conf_t::root_canon, and SD_HTTP_EP_MAX.
Referenced by cvmfs_geo_rank_config().
cvmfs_geo_compute_metrics()
static char * cvmfs_geo_compute_metrics (ngx_conf_t * cf, ngx_http_brix_cvmfs_loc_conf_t * conf, cvmfs_geo_calc_t * calc) static
Definition at line 149 of file cvmfs_module_georank.c.
References brix_cvmfs_haversine_km(), brix_vfs_backend_http_endpoint_at(), ngx_http_brix_cvmfs_loc_conf_t::common, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, cvmfs_parse_latlon(), brix_cvmfs_conf_t::here, cvmfs_geo_calc_t::here_lat, cvmfs_geo_calc_t::here_lon, host, cvmfs_geo_calc_t::metric, cvmfs_geo_calc_t::n, brix_cvmfs_conf_t::origin_coords, port, ngx_http_brix_shared_conf_t::root_canon, and SD_HTTP_EP_MAX.
Referenced by cvmfs_geo_rank_config().
cvmfs_geo_rank_config()
char * cvmfs_geo_rank_config (ngx_conf_t * cf, ngx_http_brix_cvmfs_loc_conf_t * conf)
Definition at line 282 of file cvmfs_module_georank.c.
References cvmfs_geo_apply_ranks(), and cvmfs_geo_compute_metrics().
Referenced by cvmfs_merge_cache().
cvmfs_parse_latlon()
static int cvmfs_parse_latlon (const ngx_str_t * v, double * lat, double * lon) static
Definition at line 51 of file cvmfs_module_georank.c.
References ngx_memcpy.
Referenced by cvmfs_geo_compute_metrics(), and ngx_http_brix_cvmfs_set_coords().
ngx_http_brix_cvmfs_set_coords()
char * ngx_http_brix_cvmfs_set_coords (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 297 of file cvmfs_module_georank.c.
References c, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, cvmfs_parse_latlon(), and brix_cvmfs_conf_t::origin_coords.