nginx-xrootd: src/protocols/cvmfs/cvmfs_module_merge.c File Reference
cvmfs_module_merge.c File Reference
#include "cvmfs.h"
#include "cvmfs_module_internal.h"
#include "core/config/config.h"
#include "core/config/root_prepare.h"
#include "core/config/http_rootfd.h"
#include "core/config/http_common.h"
#include "core/compat/alloc_guard.h"
#include "fs/cache/verify.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "origin_geo.h"
#include "fs/backend/http/sd_http.h"
#include "auth/token/issuer_registry.h"
#include "fs/backend/cache/sd_cache.h"
#include "fs/cache/origin/s3_transport.h"
#include <stdlib.h>
Functions
static char * cvmfs_merge_preamble (ngx_conf_t *cf, ngx_http_brix_cvmfs_loc_conf_t *prev, ngx_http_brix_cvmfs_loc_conf_t *conf)
static void cvmfs_merge_upstreams (ngx_conf_t *cf, ngx_http_brix_cvmfs_loc_conf_t *prev, ngx_http_brix_cvmfs_loc_conf_t *conf)
static char * cvmfs_merge_resilience (ngx_conf_t *cf, ngx_http_brix_cvmfs_loc_conf_t *prev, ngx_http_brix_cvmfs_loc_conf_t *conf)
static char * cvmfs_merge_secure (ngx_conf_t *cf, ngx_http_brix_cvmfs_loc_conf_t *prev, ngx_http_brix_cvmfs_loc_conf_t *conf)
char * ngx_http_brix_cvmfs_merge_loc_conf (ngx_conf_t *cf, void *parent, void *child)
Function Documentation
cvmfs_merge_preamble()
static char * cvmfs_merge_preamble (ngx_conf_t * cf, ngx_http_brix_cvmfs_loc_conf_t * prev, ngx_http_brix_cvmfs_loc_conf_t * conf) static
Definition at line 67 of file cvmfs_module_merge.c.
References BRIX_CACHE_VERIFY_CVMFS_CAS, brix_http_common_adopt(), ngx_http_brix_shared_conf_t::cache_verify_mode, ngx_http_brix_cvmfs_loc_conf_t::common, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, brix_cvmfs_conf_t::enable, and ngx_http_brix_shared_merge().
Referenced by ngx_http_brix_cvmfs_merge_loc_conf().
cvmfs_merge_resilience()
static char * cvmfs_merge_resilience (ngx_conf_t * cf, ngx_http_brix_cvmfs_loc_conf_t * prev, ngx_http_brix_cvmfs_loc_conf_t * conf) static
Definition at line 192 of file cvmfs_module_merge.c.
References BRIX_CVMFS_ORIGIN_HTTP_UNSET, BRIX_CVMFS_RETRY_FAILOVER, BRIX_CVMFS_RETRY_FORCE_PRIMARY, brix_s3_origin_http_version_set(), brix_s3_origin_http_version_supported(), brix_s3_origin_reuse_set(), brix_s3_origin_timeouts_set(), ngx_http_brix_cvmfs_loc_conf_t::common, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, brix_cvmfs_conf_t::enable, brix_cvmfs_conf_t::fill_retry_policy, brix_cvmfs_conf_t::origin_attempt_timeout, brix_cvmfs_conf_t::origin_connect_timeout, brix_cvmfs_conf_t::origin_http_version, brix_cvmfs_conf_t::origin_reuse_conn, brix_cvmfs_conf_t::origin_stall_bytes, brix_cvmfs_conf_t::origin_stall_timeout, sd_http_force_primary_set(), brix_cvmfs_conf_t::shared_cache, ngx_http_brix_shared_conf_t::storage_backend, and brix_cvmfs_conf_t::unified_origin.
Referenced by ngx_http_brix_cvmfs_merge_loc_conf().
cvmfs_merge_secure()
static char * cvmfs_merge_secure (ngx_conf_t * cf, ngx_http_brix_cvmfs_loc_conf_t * prev, ngx_http_brix_cvmfs_loc_conf_t * conf) static
Definition at line 282 of file cvmfs_module_merge.c.
References BRIX_AUTHZ_CAPABILITY, BRIX_CVMFS_GEO_PASSTHROUGH, BRIX_SCVMFS_AUTHZ_BEARER, BRIX_SCVMFS_AUTHZ_NONE, brix_token_registry_build(), ngx_http_brix_cvmfs_loc_conf_t::cvmfs, brix_cvmfs_conf_t::enable, brix_cvmfs_conf_t::geo_answer, brix_cvmfs_conf_t::geo_cache_ttl, brix_cvmfs_conf_t::geo_max_servers, ngx_http_brix_cvmfs_loc_conf_t::qos, brix_cvmfs_repo_authz_t::registry, ngx_http_brix_cvmfs_loc_conf_t::repo_authz, ngx_http_brix_cvmfs_loc_conf_t::scvmfs, ngx_http_brix_cvmfs_loc_conf_t::scvmfs_authz, ngx_http_brix_cvmfs_loc_conf_t::scvmfs_registry, and ngx_http_brix_cvmfs_loc_conf_t::scvmfs_token_issuers.
Referenced by ngx_http_brix_cvmfs_merge_loc_conf().
cvmfs_merge_upstreams()
static void cvmfs_merge_upstreams (ngx_conf_t * cf, ngx_http_brix_cvmfs_loc_conf_t * prev, ngx_http_brix_cvmfs_loc_conf_t * conf) static
Definition at line 134 of file cvmfs_module_merge.c.
References BRIX_CVMFS_SELECT_RTT, brix_origin_trace_set(), brix_cvmfs_conf_t::client_hold, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, brix_cvmfs_conf_t::fill_max_life, brix_cvmfs_conf_t::here, brix_cvmfs_conf_t::manifest_ttl, brix_cvmfs_conf_t::master_key, brix_cvmfs_conf_t::negative_ttl, brix_cvmfs_conf_t::offline_ttl, brix_cvmfs_conf_t::origin_coords, brix_cvmfs_conf_t::origin_select, brix_cvmfs_conf_t::quarantine_dir, brix_cvmfs_conf_t::rtt_interval, brix_cvmfs_conf_t::trace, brix_cvmfs_conf_t::upstream_allow, and brix_cvmfs_conf_t::upstream_max.
Referenced by ngx_http_brix_cvmfs_merge_loc_conf().
ngx_http_brix_cvmfs_merge_loc_conf()
char * ngx_http_brix_cvmfs_merge_loc_conf (ngx_conf_t * cf, void * parent, void * child)
Definition at line 383 of file cvmfs_module_merge.c.
References ngx_http_brix_cvmfs_loc_conf_t::cvmfs, cvmfs_merge_cache(), cvmfs_merge_preamble(), cvmfs_merge_resilience(), cvmfs_merge_secure(), cvmfs_merge_upstreams(), and brix_cvmfs_conf_t::enable.