nginx-xrootd: src/protocols/cvmfs/cvmfs.h File Reference
cvmfs.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include "classify.h"
#include "core/config/shared_conf.h"
#include "fs/backend/sd.h"
#include "observability/metrics/metrics.h"
#include "observability/metrics/metrics_macros.h"
#include "observability/sesslog/sesslog.h"
Data Structures
struct brix_cvmfs_coord_t
struct brix_cvmfs_conf_t
struct brix_cvmfs_repo_authz_t
struct brix_cvmfs_qos_t
struct ngx_http_brix_cvmfs_loc_conf_t
struct ngx_http_brix_cvmfs_ctx_t
Macros
#define BRIX_CVMFS_CACHE_NONE 0u
#define BRIX_CVMFS_CACHE_HIT 1u
#define BRIX_CVMFS_CACHE_FILL 2u
#define BRIX_CVMFS_CACHE_NEG 3u
Enumerations
enum brix_cvmfs_select_e { BRIX_CVMFS_SELECT_STATIC = 0 , BRIX_CVMFS_SELECT_GEO , BRIX_CVMFS_SELECT_RTT }
enum brix_cvmfs_retry_policy_e { BRIX_CVMFS_RETRY_FAILOVER = 0 , BRIX_CVMFS_RETRY_FORCE_PRIMARY }
enum brix_cvmfs_origin_http_e {
BRIX_CVMFS_ORIGIN_HTTP_UNSET = 0 , BRIX_CVMFS_ORIGIN_HTTP_11 = 11 , BRIX_CVMFS_ORIGIN_HTTP_2 = 20 , BRIX_CVMFS_ORIGIN_HTTP_2D = 21 ,
BRIX_CVMFS_ORIGIN_HTTP_3 = 30
}
enum brix_cvmfs_geo_answer_e { BRIX_CVMFS_GEO_PASSTHROUGH = 0 , BRIX_CVMFS_GEO_RTT }
enum brix_scvmfs_authz_e { BRIX_SCVMFS_AUTHZ_NONE = 0 , BRIX_SCVMFS_AUTHZ_BEARER }
Functions
ngx_int_t ngx_http_brix_cvmfs_handler (ngx_http_request_t *r)
ngx_int_t brix_cvmfs_gate (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf)
ngx_int_t brix_cvmfs_geo_passthrough (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf)
ngx_int_t brix_cvmfs_geo_answer (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf)
long brix_cvmfs_connect_rtt_us (const char *host, int port, int timeout_ms)
ngx_int_t brix_cvmfs_proxy_target (ngx_http_request_t *r, const brix_cvmfs_conf_t *cc, ngx_str_t *host, in_port_t *port)
brix_sd_instance_t * brix_cvmfs_upstream_get (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf, const ngx_str_t *host, in_port_t port, const char **up_root_out, ngx_uint_t *status)
void brix_cvmfs_notify_status (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf, ngx_uint_t status)
ngx_int_t brix_scvmfs_preamble (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf)
ngx_int_t brix_cvmfs_repo_authz_eval (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf)
ngx_int_t brix_cvmfs_qos_check (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf)
void brix_cvmfs_rtt_register (const char *root_canon, time_t interval, const ngx_str_t *pool_name)
ngx_int_t brix_cvmfs_rtt_init_worker (ngx_cycle_t *cycle)
Variables
ngx_module_t ngx_http_brix_cvmfs_module
Macro Definition Documentation
BRIX_CVMFS_CACHE_FILL
#define BRIX_CVMFS_CACHE_FILL 2u
Definition at line 284 of file cvmfs.h.
BRIX_CVMFS_CACHE_HIT
#define BRIX_CVMFS_CACHE_HIT 1u
Definition at line 283 of file cvmfs.h.
BRIX_CVMFS_CACHE_NEG
#define BRIX_CVMFS_CACHE_NEG 3u
Definition at line 285 of file cvmfs.h.
BRIX_CVMFS_CACHE_NONE
#define BRIX_CVMFS_CACHE_NONE 0u
Definition at line 282 of file cvmfs.h.
Enumeration Type Documentation
brix_cvmfs_geo_answer_e
enum brix_cvmfs_geo_answer_e
Enumerator
BRIX_CVMFS_GEO_PASSTHROUGH
BRIX_CVMFS_GEO_RTT
Definition at line 52 of file cvmfs.h.
brix_cvmfs_origin_http_e
enum brix_cvmfs_origin_http_e
Enumerator
BRIX_CVMFS_ORIGIN_HTTP_UNSET
BRIX_CVMFS_ORIGIN_HTTP_11
BRIX_CVMFS_ORIGIN_HTTP_2
BRIX_CVMFS_ORIGIN_HTTP_2D
BRIX_CVMFS_ORIGIN_HTTP_3
Definition at line 43 of file cvmfs.h.
brix_cvmfs_retry_policy_e
enum brix_cvmfs_retry_policy_e
Enumerator
BRIX_CVMFS_RETRY_FAILOVER
BRIX_CVMFS_RETRY_FORCE_PRIMARY
Definition at line 35 of file cvmfs.h.
brix_cvmfs_select_e
enum brix_cvmfs_select_e
Enumerator
BRIX_CVMFS_SELECT_STATIC
BRIX_CVMFS_SELECT_GEO
BRIX_CVMFS_SELECT_RTT
Definition at line 28 of file cvmfs.h.
brix_scvmfs_authz_e
enum brix_scvmfs_authz_e
Enumerator
BRIX_SCVMFS_AUTHZ_NONE
BRIX_SCVMFS_AUTHZ_BEARER
Definition at line 179 of file cvmfs.h.
Function Documentation
brix_cvmfs_connect_rtt_us()
long brix_cvmfs_connect_rtt_us (const char * host, int port, int timeout_ms)
Definition at line 99 of file origin_probe.c.
References close(), host, and port.
Referenced by cvmfs_geo_thread(), and cvmfs_probe_thread().
brix_cvmfs_gate()
ngx_int_t brix_cvmfs_gate (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf)
Definition at line 264 of file gate.c.
References BRIX_ATOMIC_INC, BRIX_CVMFS_CLASS_GEO, BRIX_CVMFS_CLASS_MANIFEST, brix_cvmfs_geo_answer(), brix_cvmfs_geo_passthrough(), BRIX_CVMFS_GEO_RTT, BRIX_CVMFS_METRIC_INC, brix_cvmfs_repo_authz_eval(), brix_cvmfs_repo_slot(), ngx_http_brix_cvmfs_loc_conf_t::cvmfs, cvmfs_gate_cas(), cvmfs_gate_proxy_bind(), cvmfs_guard_emit(), cvmfs_reject(), brix_cvmfs_conf_t::geo_answer, GUARD_R_AUTHFAIL, ngx_http_brix_cvmfs_module, ngx_http_brix_cvmfs_ctx_t::repo, ngx_http_brix_cvmfs_loc_conf_t::repo_authz, ngx_brix_cvmfs_repo_metrics_t::requests_total, and ngx_http_brix_cvmfs_ctx_t::url.
Referenced by ngx_http_brix_cvmfs_handler().
brix_cvmfs_geo_answer()
ngx_int_t brix_cvmfs_geo_answer (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf)
Definition at line 415 of file geo_answer.c.
References cvmfs_geo_task_t::body, brix_cvmfs_geo_passthrough(), ngx_http_brix_cvmfs_loc_conf_t::common, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, cvmfs_geo_cache_read(), cvmfs_geo_done(), cvmfs_geo_parse(), cvmfs_geo_thread(), brix_cvmfs_conf_t::geo_cache_ttl, brix_cvmfs_conf_t::geo_max_servers, cvmfs_geo_task_t::n, cvmfs_geo_task_t::r, ngx_http_brix_shared_conf_t::thread_pool, ngx_http_brix_shared_conf_t::thread_pool_name, and cvmfs_geo_task_t::ttl.
Referenced by brix_cvmfs_gate().
brix_cvmfs_geo_passthrough()
ngx_int_t brix_cvmfs_geo_passthrough (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf)
Definition at line 111 of file geo.c.
References cvmfs_pt_task_t::body, brix_vfs_backend_http_endpoint(), ngx_http_brix_cvmfs_loc_conf_t::common, cvmfs_pt_done(), CVMFS_PT_RESP_MAX, cvmfs_pt_thread(), host, cvmfs_pt_task_t::host, ngx_http_brix_cvmfs_module, cvmfs_pt_task_t::path, port, cvmfs_pt_task_t::port, cvmfs_pt_task_t::r, ngx_http_brix_shared_conf_t::root_canon, ngx_http_brix_shared_conf_t::thread_pool, ngx_http_brix_shared_conf_t::thread_pool_name, tls, cvmfs_pt_task_t::tls, and ngx_http_brix_cvmfs_ctx_t::up_root.
Referenced by brix_cvmfs_gate(), and brix_cvmfs_geo_answer().
brix_cvmfs_notify_status()
void brix_cvmfs_notify_status (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf, ngx_uint_t status)
Definition at line 73 of file gate.c.
References ngx_http_brix_cvmfs_loc_conf_t::cvmfs, cvmfs_neg_store(), and brix_cvmfs_conf_t::negative_ttl.
Referenced by cvmfs_finalize_observe().
brix_cvmfs_proxy_target()
ngx_int_t brix_cvmfs_proxy_target (ngx_http_request_t * r, const brix_cvmfs_conf_t * cc, ngx_str_t * host, in_port_t * port)
Definition at line 135 of file request.c.
References brix_cvmfs_proxy_host_allowed(), brix_cvmfs_proxy_parse_port(), brix_cvmfs_proxy_scheme_check(), host, and port.
Referenced by cvmfs_gate_proxy_bind().
brix_cvmfs_qos_check()
ngx_int_t brix_cvmfs_qos_check (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf)
Definition at line 382 of file secure.c.
References cls(), cvmfs_qos_class(), ngx_http_brix_cvmfs_module, ngx_http_brix_cvmfs_loc_conf_t::qos, and ngx_http_brix_cvmfs_ctx_t::token_sub.
Referenced by cvmfs_tier_serve_or_fill().
brix_cvmfs_repo_authz_eval()
ngx_int_t brix_cvmfs_repo_authz_eval (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf)
Definition at line 181 of file secure.c.
References brix_str_cbuf(), BRIX_TOKEN_CLOCK_SKEW_SECS, BRIX_TOKEN_OP_READ, brix_token_validate_registry(), brix_token_registry_args_t::claims, brix_token_registry_args_t::clock_skew, cvmfs_repo_authz_match(), brix_token_registry_args_t::log, brix_token_registry_args_t::macaroon_secret, ngx_http_brix_cvmfs_module, PATH_MAX, brix_token_registry_args_t::reg, brix_cvmfs_repo_authz_t::registry, ngx_http_brix_cvmfs_loc_conf_t::repo_authz, scvmfs_bearer_token(), brix_token_registry_args_t::secret_len, brix_token_claims_t::sub, brix_token_registry_args_t::token, brix_token_registry_args_t::token_len, ngx_http_brix_cvmfs_ctx_t::token_sub, and ngx_http_brix_cvmfs_ctx_t::url.
Referenced by brix_cvmfs_gate().
brix_cvmfs_rtt_init_worker()
ngx_int_t brix_cvmfs_rtt_init_worker (ngx_cycle_t * cycle)
Definition at line 333 of file origin_probe.c.
References brix_vfs_backend_http_endpoint_at(), cvmfs_probe_done(), cvmfs_probe_fire(), cvmfs_probe_thread(), cvmfs_rtt_regs, cvmfs_rtt_regs_n, host, cvmfs_probe_ctx_t::hosts, cvmfs_probe_ctx_t::n, port, cvmfs_probe_ctx_t::ports, cvmfs_probe_ctx_t::prev_ranks, cvmfs_probe_ctx_t::reg, cvmfs_rtt_reg_t::root, SD_HTTP_EP_MAX, cvmfs_probe_ctx_t::task, and cvmfs_probe_ctx_t::timer.
Referenced by ngx_http_brix_cvmfs_init_process().
brix_cvmfs_rtt_register()
void brix_cvmfs_rtt_register (const char * root_canon, time_t interval, const ngx_str_t * pool_name)
Definition at line 44 of file origin_probe.c.
References CVMFS_PROBE_MAX_EXPORTS, cvmfs_rtt_regs, cvmfs_rtt_regs_n, cvmfs_rtt_reg_t::interval, ngx_memcpy, cvmfs_rtt_reg_t::pool, and cvmfs_rtt_reg_t::root.
Referenced by cvmfs_merge_cache().
brix_cvmfs_upstream_get()
brix_sd_instance_t * brix_cvmfs_upstream_get (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf, const ngx_str_t * host, in_port_t port, const char ** up_root_out, ngx_uint_t * status)
Definition at line 34 of file upstreams.c.
References brix_vfs_backend_register_http_upstream(), brix_vfs_backend_resolve(), ngx_http_brix_cvmfs_loc_conf_t::common, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, CVMFS_UP_MAX, cvmfs_ups, cvmfs_ups_n, cvmfs_upstream_slot::host, host, ngx_memcpy, port, ngx_http_brix_shared_conf_t::root_canon, s, brix_cvmfs_conf_t::shared_cache, and brix_cvmfs_conf_t::upstream_max.
Referenced by cvmfs_gate_proxy_bind().
brix_scvmfs_preamble()
ngx_int_t brix_scvmfs_preamble (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf)
Definition at line 256 of file secure.c.
References BRIX_CVMFS_CLASS_REJECT, BRIX_CVMFS_METRIC_INC, BRIX_SCVMFS_AUTHZ_BEARER, BRIX_SCVMFS_AUTHZ_NONE, ngx_http_brix_cvmfs_module, ngx_http_brix_cvmfs_loc_conf_t::scvmfs_authz, scvmfs_check_bearer(), and ngx_http_brix_cvmfs_ctx_t::secure.
Referenced by ngx_http_brix_cvmfs_handler().
ngx_http_brix_cvmfs_handler()
ngx_int_t ngx_http_brix_cvmfs_handler (ngx_http_request_t * r)
Definition at line 519 of file handler.c.
References brix_sess_xfer_t::active, brix_cvmfs_gate(), brix_http_sess(), brix_http_sess_uri(), brix_scvmfs_preamble(), BRIX_SESS_AM_ANON, brix_sess_attempt(), brix_sess_auth_once(), BRIX_SESS_MODE_READ, BRIX_SESS_PROTO_CVMFS, brix_sess_xfer_start(), BRIX_SESSLOG_PATH_MAX, ngx_http_brix_cvmfs_loc_conf_t::common, cvmfs_finalize_observe(), cvmfs_tier_get(), ngx_http_brix_cvmfs_module, ngx_pcalloc(), ngx_http_brix_cvmfs_loc_conf_t::scvmfs, ngx_http_brix_cvmfs_ctx_t::sess_attempt_logged, ngx_http_brix_cvmfs_ctx_t::sess_xfer, and ngx_http_brix_cvmfs_ctx_t::sess_xfer_started.
Referenced by cvmfs_reenter(), and ngx_http_brix_cvmfs_set().
Variable Documentation
ngx_http_brix_cvmfs_module
ngx_module_t ngx_http_brix_cvmfs_module extern
Definition at line 351 of file module.c.
Referenced by brix_cvmfs_gate(), brix_cvmfs_geo_passthrough(), brix_cvmfs_proxy_scheme_check(), brix_cvmfs_qos_check(), brix_cvmfs_repo_authz_eval(), brix_http_protocol_variable(), brix_scvmfs_preamble(), cvmfs_finalize_observe(), cvmfs_resolve_sd(), cvmfs_tier_get(), cvmfs_tier_serve_or_fill(), cvmfs_var_cache(), cvmfs_var_class(), cvmfs_var_origin(), ngx_http_brix_cvmfs_handler(), ngx_http_brix_cvmfs_postconfiguration(), proto_cvmfs_enabled(), and scvmfs_check_bearer().