nginx-xrootd: src/observability/metrics/cvmfs.c File Reference
cvmfs.c File Reference
#include "metrics_internal.h"
#include <string.h>
Functions
static int cvmfs_repo_slot_is (const ngx_brix_cvmfs_repo_metrics_t *r, const char *name, size_t len)
ngx_brix_cvmfs_repo_metrics_t * brix_cvmfs_repo_slot (const char *name, size_t len)
static int cvmfs_repo_slot_is_dup (const ngx_brix_cvmfs_repo_metrics_t *repos, ngx_uint_t i)
static int cvmfs_up_slot_is (const ngx_brix_cvmfs_upstream_metrics_t *u, const char *host)
static ngx_brix_cvmfs_upstream_metrics_t * cvmfs_upstream_slot (const char *host)
void brix_cvmfs_upstream_record (const char *host, int ok, off_t bytes, long dur_ms, int failover)
static int cvmfs_up_slot_is_dup (const ngx_brix_cvmfs_upstream_metrics_t *ups, ngx_uint_t i)
static void cvmfs_export_upstreams (metrics_writer_t *mw, ngx_brix_cvmfs_metrics_t *c)
void brix_export_cvmfs_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
Variables
static const char * brix_cvmfs_class_names [BRIX_CVMFS_CLASS_COUNT]
Function Documentation
brix_cvmfs_repo_slot()
ngx_brix_cvmfs_repo_metrics_t * brix_cvmfs_repo_slot (const char * name, size_t len)
Definition at line 35 of file cvmfs.c.
References BRIX_CVMFS_REPO_CLAIMED, BRIX_CVMFS_REPO_EMPTY, BRIX_CVMFS_REPO_NAME_MAX, BRIX_CVMFS_REPO_READY, BRIX_CVMFS_REPO_SLOTS, brix_metrics_shared(), ngx_brix_metrics_t::cvmfs, cvmfs_repo_slot_is(), ngx_brix_cvmfs_repo_metrics_t::name, name, ngx_brix_cvmfs_metrics_t::repos, and ngx_brix_cvmfs_repo_metrics_t::state.
Referenced by brix_cvmfs_gate(), and sd_cache_repo_metrics().
brix_cvmfs_upstream_record()
void brix_cvmfs_upstream_record (const char * host, int ok, off_t bytes, long dur_ms, int failover)
Definition at line 180 of file cvmfs.c.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, brix_cvmfs_up_bucket_ms, BRIX_CVMFS_UP_HBUCKETS, ngx_brix_cvmfs_upstream_metrics_t::dur_bucket, ngx_brix_cvmfs_upstream_metrics_t::dur_count, ngx_brix_cvmfs_upstream_metrics_t::dur_sum_ms, ngx_brix_cvmfs_upstream_metrics_t::failovers_total, ngx_brix_cvmfs_upstream_metrics_t::fill_failures_total, ngx_brix_cvmfs_upstream_metrics_t::fills_total, host, ngx_brix_cvmfs_upstream_metrics_t::origin_bytes_total, and ngx_brix_cvmfs_upstream_metrics_t::requests_total.
Referenced by sd_cache_note_upstream().
brix_export_cvmfs_metrics()
void brix_export_cvmfs_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 305 of file cvmfs.c.
References BRIX_CVMFS_CLASS_COUNT, brix_cvmfs_class_names, BRIX_CVMFS_REPO_READY, BRIX_CVMFS_REPO_SLOTS, ngx_brix_cvmfs_repo_metrics_t::bytes_served_fill_total, ngx_brix_cvmfs_repo_metrics_t::bytes_served_hit_total, c, cls(), ngx_brix_metrics_t::cvmfs, cvmfs_export_upstreams(), cvmfs_repo_slot_is_dup(), mw_emit_labeled(), mw_emit_scalar(), mw_printf(), ngx_brix_cvmfs_repo_metrics_t::name, name, ngx_brix_cvmfs_repo_metrics_t::requests_total, and ngx_brix_cvmfs_repo_metrics_t::state.
Referenced by brix_export_prometheus_metrics().
cvmfs_export_upstreams()
static void cvmfs_export_upstreams (metrics_writer_t * mw, ngx_brix_cvmfs_metrics_t * c) static
Definition at line 232 of file cvmfs.c.
References BRIX_CVMFS_REPO_READY, brix_cvmfs_up_bucket_ms, BRIX_CVMFS_UP_HBUCKETS, BRIX_CVMFS_UPSTREAM_SLOTS, c, cvmfs_up_slot_is_dup(), ngx_brix_cvmfs_upstream_metrics_t::dur_bucket, ngx_brix_cvmfs_upstream_metrics_t::dur_count, ngx_brix_cvmfs_upstream_metrics_t::dur_sum_ms, mw_printf(), ngx_brix_cvmfs_upstream_metrics_t::name, name, and ngx_brix_cvmfs_upstream_metrics_t::state.
Referenced by brix_export_cvmfs_metrics().
cvmfs_repo_slot_is()
static int cvmfs_repo_slot_is (const ngx_brix_cvmfs_repo_metrics_t * r, const char * name, size_t len) static
Definition at line 26 of file cvmfs.c.
References BRIX_CVMFS_REPO_READY, ngx_brix_cvmfs_repo_metrics_t::name, name, and ngx_brix_cvmfs_repo_metrics_t::state.
Referenced by brix_cvmfs_repo_slot().
cvmfs_repo_slot_is_dup()
static int cvmfs_repo_slot_is_dup (const ngx_brix_cvmfs_repo_metrics_t * repos, ngx_uint_t i) static
Definition at line 99 of file cvmfs.c.
References BRIX_CVMFS_REPO_READY, and name.
Referenced by brix_export_cvmfs_metrics().
cvmfs_up_slot_is()
static int cvmfs_up_slot_is (const ngx_brix_cvmfs_upstream_metrics_t * u, const char * host) static
Definition at line 119 of file cvmfs.c.
References BRIX_CVMFS_REPO_READY, host, ngx_brix_cvmfs_upstream_metrics_t::name, and ngx_brix_cvmfs_upstream_metrics_t::state.
Referenced by cvmfs_upstream_slot().
cvmfs_up_slot_is_dup()
static int cvmfs_up_slot_is_dup (const ngx_brix_cvmfs_upstream_metrics_t * ups, ngx_uint_t i) static
Definition at line 216 of file cvmfs.c.
References BRIX_CVMFS_REPO_READY, and name.
Referenced by cvmfs_export_upstreams().
cvmfs_upstream_slot()
static ngx_brix_cvmfs_upstream_metrics_t * cvmfs_upstream_slot (const char * host) static
Definition at line 125 of file cvmfs.c.
References BRIX_CVMFS_REPO_CLAIMED, BRIX_CVMFS_REPO_EMPTY, BRIX_CVMFS_REPO_READY, BRIX_CVMFS_UPSTREAM_NAME_MAX, BRIX_CVMFS_UPSTREAM_SLOTS, brix_metrics_shared(), ngx_brix_metrics_t::cvmfs, cvmfs_up_slot_is(), host, ngx_brix_cvmfs_upstream_metrics_t::name, name, ngx_brix_cvmfs_upstream_metrics_t::state, and ngx_brix_cvmfs_metrics_t::upstreams.
Variable Documentation
brix_cvmfs_class_names
const char* brix_cvmfs_class_names[BRIX_CVMFS_CLASS_COUNT] static
Initial value:
= {
    "cas",
    "manifest",
    "geo",
    "reject",
}
Definition at line 15 of file cvmfs.c.
Referenced by brix_export_cvmfs_metrics().