nginx-xrootd: src/observability/dashboard/dashboard_api_internal.h File Reference
dashboard_api_internal.h File Reference
#include "dashboard_http.h"
#include "dashboard_json.h"
#include "core/compat/fs_usage.h"
#include "net/manager/registry.h"
#include "tpc/common/registry.h"
#include "net/ratelimit/ratelimit.h"
#include <stdio.h>
#include <string.h>
#include <jansson.h>
Data Structures
struct brix_dashboard_totals_t
struct brix_dashboard_proto_summary_t
struct brix_dashboard_protocols_t
Macros
#define STALE_GC_MS 600000
#define TPC_REGISTRY_JSON_LIMIT 64
Functions
const char * dashboard_direction_name (uint8_t direction)
const char * dashboard_proto_name (uint8_t proto)
const char * dashboard_state_name (const ngx_http_brix_dashboard_loc_conf_t *conf, uint8_t state, int64_t idle_ms, int moving)
const char * dashboard_tpc_protocol_name (ngx_uint_t protocol)
const char * dashboard_tpc_direction_name (ngx_uint_t direction)
const char * dashboard_tpc_state_name (ngx_uint_t state)
const char * dashboard_event_class_name (uint8_t class_id)
uint32_t dashboard_session_hash (const u_char sessid[16])
void dashboard_collect_totals (brix_dashboard_totals_t *totals)
uint64_t dashboard_avg_bps (int64_t bytes, int64_t start_ms, int64_t now_ms)
void dashboard_collect_protocols (brix_dashboard_protocols_t *out, int64_t now_ms)
json_t * dashboard_build_limits (const ngx_http_brix_dashboard_loc_conf_t *conf)
json_t * dashboard_build_totals (const brix_dashboard_totals_t *totals)
json_t * dashboard_build_transfer_object (const ngx_http_brix_dashboard_loc_conf_t *conf, const brix_transfer_slot_t *slot, int64_t now_ms, ngx_uint_t v1_fields, ngx_uint_t detail_fields, ngx_uint_t redact)
json_t * dashboard_build_transfer_rows (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t v1_fields, ngx_uint_t redact)
json_t * dashboard_build_tpc_registry (ngx_pool_t *pool, ngx_uint_t redact)
json_t * dashboard_build_proto_summary (const brix_dashboard_proto_summary_t *s, uint64_t bytes_rx, uint64_t bytes_tx)
json_t * dashboard_build_protocols (int64_t now_ms, const brix_dashboard_totals_t *totals)
json_t * dashboard_build_events (ngx_pool_t *pool, ngx_uint_t redact)
void dashboard_fill_history (json_t *target, ngx_pool_t *pool)
void dashboard_fill_cache (json_t *target, ngx_uint_t redact)
void dashboard_fill_storage (json_t *target, ngx_uint_t redact)
void dashboard_fill_cluster (json_t *target, ngx_pool_t *pool, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t redact)
json_t * dashboard_new_v1_root (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf)
json_t * dashboard_build_compat_transfers (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, const brix_dashboard_totals_t *totals, ngx_uint_t redact)
json_t * dashboard_build_v1_transfers (ngx_http_request_t *r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, const brix_dashboard_totals_t *totals, ngx_uint_t redact)
ngx_int_t dashboard_parse_detail_id (ngx_http_request_t *r, uint32_t *id)
json_t * dashboard_build_v1_transfer_detail (ngx_http_request_t *r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_int_t *status)
json_t * dashboard_build_v1_snapshot (ngx_http_request_t *r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, const brix_dashboard_totals_t *totals, ngx_uint_t redact)
json_t * dashboard_build_v1_events (ngx_http_request_t *r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t redact)
json_t * dashboard_build_v1_history (ngx_http_request_t *r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t redact)
json_t * dashboard_build_v1_cluster (ngx_http_request_t *r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t redact)
json_t * dashboard_build_v1_cache (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t redact)
void dashboard_fill_cvmfs (json_t *target, ngx_uint_t redact)
json_t * dashboard_build_v1_cvmfs (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t redact)
json_t * dashboard_build_v1_ratelimit (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t redact)
json_t * dashboard_build_v1_not_found (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t redact)
json_t * dashboard_build_v1_truncated (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t *conf)
ngx_uint_t dashboard_endpoint_is_anon_allowed (brix_dashboard_api_endpoint_e e)
Macro Definition Documentation
STALE_GC_MS
#define STALE_GC_MS 600000
Definition at line 17 of file dashboard_api_internal.h.
TPC_REGISTRY_JSON_LIMIT
#define TPC_REGISTRY_JSON_LIMIT 64
Definition at line 18 of file dashboard_api_internal.h.
Function Documentation
dashboard_avg_bps()
uint64_t dashboard_avg_bps (int64_t bytes, int64_t start_ms, int64_t now_ms)
Definition at line 135 of file api.c.
Referenced by dashboard_collect_protocols(), and dashboard_snapshot_slot().
dashboard_build_compat_transfers()
json_t * dashboard_build_compat_transfers (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, const brix_dashboard_totals_t * totals, ngx_uint_t redact)
Definition at line 336 of file api_transfers.c.
References dashboard_build_totals(), and dashboard_build_transfer_rows().
Referenced by dashboard_dispatch_builder().
dashboard_build_events()
json_t * dashboard_build_events (ngx_pool_t * pool, ngx_uint_t redact)
Definition at line 272 of file api_snapshot.c.
References brix_dashboard_events_snapshot(), BRIX_DASHBOARD_MAX_EVENTS, dashboard_event_class_name(), dashboard_proto_name(), brix_dashboard_event_t::message, ngx_pcalloc(), and brix_dashboard_event_t::path_hint.
Referenced by dashboard_build_v1_events(), and dashboard_build_v1_snapshot().
dashboard_build_limits()
json_t * dashboard_build_limits (const ngx_http_brix_dashboard_loc_conf_t * conf)
Definition at line 142 of file api_snapshot.c.
References BRIX_DASHBOARD_HISTORY_INTERVAL_MS, BRIX_DASHBOARD_MAX_EVENTS, BRIX_DASHBOARD_MAX_TRANSFERS, BRIX_TPC_REGISTRY_SLOTS, ngx_http_brix_dashboard_loc_conf_t::idle_threshold_ms, ngx_http_brix_dashboard_loc_conf_t::stalled_threshold_ms, and TPC_REGISTRY_JSON_LIMIT.
Referenced by dashboard_new_v1_root().
dashboard_build_proto_summary()
json_t * dashboard_build_proto_summary (const brix_dashboard_proto_summary_t * s, uint64_t bytes_rx, uint64_t bytes_tx)
Definition at line 214 of file api_snapshot.c.
References s.
Referenced by dashboard_build_protocols().
dashboard_build_protocols()
json_t * dashboard_build_protocols (int64_t now_ms, const brix_dashboard_totals_t * totals)
Definition at line 231 of file api_snapshot.c.
References brix_dashboard_proto_summary_t::active, BRIX_XFER_NPROTOS, BRIX_XFER_PROTO_ROOT, brix_dashboard_totals_t::bytes_rx, brix_dashboard_totals_t::bytes_tx, dashboard_build_proto_summary(), dashboard_collect_protocols(), dashboard_proto_name(), brix_dashboard_proto_summary_t::egress_bps, brix_dashboard_proto_summary_t::ingress_bps, brix_dashboard_protocols_t::per, brix_dashboard_totals_t::proto_rx, brix_dashboard_totals_t::proto_tx, and brix_dashboard_protocols_t::tpc.
Referenced by dashboard_build_v1_snapshot().
dashboard_build_totals()
json_t * dashboard_build_totals (const brix_dashboard_totals_t * totals)
Definition at line 158 of file api_snapshot.c.
References BRIX_PROTO_LIST, BRIX_XFER_NPROTOS, brix_dashboard_totals_t::bytes_rx, brix_dashboard_totals_t::bytes_tx, brix_dashboard_totals_t::conn_active, brix_dashboard_totals_t::conn_total, key, brix_dashboard_totals_t::proto_errors, brix_dashboard_totals_t::proto_rx, brix_dashboard_totals_t::proto_tx, brix_dashboard_totals_t::stream_errors, and X.
Referenced by dashboard_build_compat_transfers(), dashboard_build_v1_snapshot(), and dashboard_build_v1_transfers().
dashboard_build_tpc_registry()
json_t * dashboard_build_tpc_registry (ngx_pool_t * pool, ngx_uint_t redact)
Definition at line 303 of file api_transfers.c.
References brix_tpc_registry_snapshot(), dashboard_tpc_direction_name(), dashboard_tpc_protocol_name(), dashboard_tpc_state_name(), brix_tpc_transfer_snapshot_t::dst_path, ngx_pcalloc(), brix_tpc_transfer_snapshot_t::src_url, and TPC_REGISTRY_JSON_LIMIT.
Referenced by dashboard_build_v1_snapshot(), and dashboard_build_v1_transfers().
dashboard_build_transfer_object()
json_t * dashboard_build_transfer_object (const ngx_http_brix_dashboard_loc_conf_t * conf, const brix_transfer_slot_t * slot, int64_t now_ms, ngx_uint_t v1_fields, ngx_uint_t detail_fields, ngx_uint_t redact)
Definition at line 224 of file api_transfers.c.
References dashboard_emit_base_fields(), dashboard_emit_detail_fields(), dashboard_emit_tpc_object(), dashboard_emit_v1_fields(), and dashboard_snapshot_slot().
Referenced by dashboard_build_transfer_rows(), and dashboard_build_v1_transfer_detail().
dashboard_build_transfer_rows()
json_t * dashboard_build_transfer_rows (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t v1_fields, ngx_uint_t redact)
Definition at line 255 of file api_transfers.c.
References BRIX_DASH_EVENT_DASHBOARD, brix_dashboard_event_add(), BRIX_DASHBOARD_MAX_TRANSFERS, brix_transfer_slot_free(), dashboard_build_transfer_object(), brix_transfer_slot_t::in_use, brix_transfer_slot_t::last_ms, ngx_brix_dashboard_shm_zone, brix_transfer_slot_t::path, brix_transfer_slot_t::proto, brix_transfer_table_t::slots, and STALE_GC_MS.
Referenced by dashboard_build_compat_transfers(), dashboard_build_v1_snapshot(), and dashboard_build_v1_transfers().
dashboard_build_v1_cache()
json_t * dashboard_build_v1_cache (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t redact)
Definition at line 466 of file api_snapshot.c.
References dashboard_fill_cache(), and dashboard_new_v1_root().
Referenced by dashboard_dispatch_builder().
dashboard_build_v1_cluster()
json_t * dashboard_build_v1_cluster (ngx_http_request_t * r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t redact)
Definition at line 453 of file api_snapshot.c.
References dashboard_fill_cluster(), and dashboard_new_v1_root().
Referenced by dashboard_dispatch_builder().
dashboard_build_v1_cvmfs()
json_t * dashboard_build_v1_cvmfs (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t redact)
Definition at line 252 of file api_cvmfs.c.
References dashboard_fill_cvmfs(), and dashboard_new_v1_root().
Referenced by dashboard_dispatch_builder().
dashboard_build_v1_events()
json_t * dashboard_build_v1_events (ngx_http_request_t * r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t redact)
Definition at line 427 of file api_snapshot.c.
References dashboard_build_events(), and dashboard_new_v1_root().
Referenced by dashboard_dispatch_builder().
dashboard_build_v1_history()
json_t * dashboard_build_v1_history (ngx_http_request_t * r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t redact)
Definition at line 440 of file api_snapshot.c.
References dashboard_fill_history(), and dashboard_new_v1_root().
Referenced by dashboard_dispatch_builder().
dashboard_build_v1_not_found()
json_t * dashboard_build_v1_not_found (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t redact)
Definition at line 77 of file api_ratelimit.c.
References dashboard_new_v1_root().
Referenced by dashboard_dispatch_builder().
dashboard_build_v1_ratelimit()
json_t * dashboard_build_v1_ratelimit (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t redact)
Definition at line 10 of file api_ratelimit.c.
References brix_rl_snapshot(), brix_rl_zones_all(), dashboard_new_v1_root(), brix_rl_zone_t::name, and name.
Referenced by dashboard_dispatch_builder().
dashboard_build_v1_snapshot()
json_t * dashboard_build_v1_snapshot (ngx_http_request_t * r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, const brix_dashboard_totals_t * totals, ngx_uint_t redact)
Definition at line 373 of file api_snapshot.c.
References dashboard_build_events(), dashboard_build_protocols(), dashboard_build_totals(), dashboard_build_tpc_registry(), dashboard_build_transfer_rows(), dashboard_fill_cache(), dashboard_fill_cluster(), dashboard_fill_cvmfs(), dashboard_fill_history(), dashboard_fill_storage(), and dashboard_new_v1_root().
Referenced by dashboard_dispatch_builder().
dashboard_build_v1_transfer_detail()
json_t * dashboard_build_v1_transfer_detail (ngx_http_request_t * r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_int_t * status)
Definition at line 398 of file api_transfers.c.
References BRIX_DASHBOARD_MAX_TRANSFERS, dashboard_build_transfer_object(), dashboard_new_v1_root(), dashboard_parse_detail_id(), brix_transfer_slot_t::in_use, ngx_brix_dashboard_shm_zone, brix_transfer_slot_t::serial, and brix_transfer_table_t::slots.
Referenced by dashboard_dispatch_builder().
dashboard_build_v1_transfers()
json_t * dashboard_build_v1_transfers (ngx_http_request_t * r, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, const brix_dashboard_totals_t * totals, ngx_uint_t redact)
Definition at line 351 of file api_transfers.c.
References dashboard_build_totals(), dashboard_build_tpc_registry(), dashboard_build_transfer_rows(), and dashboard_new_v1_root().
Referenced by dashboard_dispatch_builder().
dashboard_build_v1_truncated()
json_t * dashboard_build_v1_truncated (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf)
Definition at line 89 of file api_ratelimit.c.
References dashboard_new_v1_root().
Referenced by ngx_http_brix_dashboard_api_handler().
dashboard_collect_protocols()
void dashboard_collect_protocols (brix_dashboard_protocols_t * out, int64_t now_ms)
Definition at line 94 of file api_snapshot.c.
References brix_dashboard_proto_summary_t::active, BRIX_DASHBOARD_MAX_TRANSFERS, BRIX_XFER_DIR_TPC, BRIX_XFER_DIR_WRITE, BRIX_XFER_NPROTOS, BRIX_XFER_PROTO_ROOT, brix_transfer_slot_t::bytes, dashboard_avg_bps(), brix_transfer_slot_t::direction, brix_dashboard_proto_summary_t::egress_bps, brix_transfer_slot_t::in_use, brix_dashboard_proto_summary_t::ingress_bps, ngx_brix_dashboard_shm_zone, brix_dashboard_protocols_t::per, brix_transfer_slot_t::proto, brix_transfer_table_t::slots, brix_transfer_slot_t::start_ms, and brix_dashboard_protocols_t::tpc.
Referenced by dashboard_build_protocols().
dashboard_collect_totals()
void dashboard_collect_totals (brix_dashboard_totals_t * totals)
Definition at line 19 of file api_snapshot.c.
References BRIX_HTTP_STATUS_4XX, BRIX_HTTP_STATUS_5XX, BRIX_METRICS_MAX_SERVERS, BRIX_NOPS, BRIX_S3_NMETHODS, BRIX_WEBDAV_NMETHODS, BRIX_XFER_PROTO_CVMFS, BRIX_XFER_PROTO_S3, BRIX_XFER_PROTO_WEBDAV, brix_dashboard_totals_t::bytes_rx, ngx_brix_srv_metrics_t::bytes_rx_total, ngx_brix_s3_metrics_t::bytes_rx_total, ngx_brix_webdav_metrics_t::bytes_rx_total, ngx_brix_cvmfs_metrics_t::bytes_served_fill_total, ngx_brix_cvmfs_metrics_t::bytes_served_hit_total, brix_dashboard_totals_t::bytes_tx, ngx_brix_srv_metrics_t::bytes_tx_total, ngx_brix_s3_metrics_t::bytes_tx_total, ngx_brix_webdav_metrics_t::bytes_tx_total, brix_dashboard_totals_t::conn_active, brix_dashboard_totals_t::conn_total, ngx_brix_srv_metrics_t::connections_active, ngx_brix_srv_metrics_t::connections_total, ngx_brix_metrics_t::cvmfs, ngx_brix_cvmfs_metrics_t::fill_failures_total, ngx_brix_shm_zone, ngx_brix_srv_metrics_t::op_err, ngx_brix_cvmfs_metrics_t::origin_bytes_total, brix_dashboard_totals_t::proto_errors, brix_dashboard_totals_t::proto_rx, brix_dashboard_totals_t::proto_tx, ngx_brix_s3_metrics_t::responses_total, ngx_brix_webdav_metrics_t::responses_total, ngx_brix_metrics_t::s3, ngx_brix_metrics_t::servers, brix_dashboard_totals_t::stream_errors, ngx_brix_cvmfs_metrics_t::verify_failures_total, and ngx_brix_metrics_t::webdav.
Referenced by ngx_http_brix_dashboard_api_handler().
dashboard_direction_name()
const char * dashboard_direction_name (uint8_t direction)
Definition at line 9 of file api.c.
References BRIX_XFER_DIR_TPC, and BRIX_XFER_DIR_WRITE.
Referenced by dashboard_emit_base_fields().
dashboard_endpoint_is_anon_allowed()
ngx_uint_t dashboard_endpoint_is_anon_allowed (brix_dashboard_api_endpoint_e e)
Definition at line 160 of file api.c.
References BRIX_DASHBOARD_API_COMPAT_TRANSFERS, BRIX_DASHBOARD_API_V1_CACHE, BRIX_DASHBOARD_API_V1_CLUSTER, BRIX_DASHBOARD_API_V1_CVMFS, BRIX_DASHBOARD_API_V1_EVENTS, BRIX_DASHBOARD_API_V1_HISTORY, BRIX_DASHBOARD_API_V1_NOT_FOUND, BRIX_DASHBOARD_API_V1_RATELIMIT, BRIX_DASHBOARD_API_V1_SNAPSHOT, BRIX_DASHBOARD_API_V1_TRANSFER_DETAIL, and BRIX_DASHBOARD_API_V1_TRANSFERS.
Referenced by ngx_http_brix_dashboard_api_handler().
dashboard_event_class_name()
const char * dashboard_event_class_name (uint8_t class_id)
Definition at line 97 of file api.c.
References BRIX_DASH_EVENT_AUTH, BRIX_DASH_EVENT_DASHBOARD, BRIX_DASH_EVENT_IO, BRIX_DASH_EVENT_NAMESPACE, and BRIX_DASH_EVENT_TPC.
Referenced by dashboard_build_events().
dashboard_fill_cache()
void dashboard_fill_cache (json_t * target, ngx_uint_t redact)
Definition at line 159 of file api_snapshot_panels.c.
References BRIX_METRICS_MAX_SERVERS, dashboard_wt_totals_t::bytes, ngx_brix_srv_metrics_t::cache_enabled, dashboard_build_cache_listeners(), dashboard_build_write_through(), dashboard_fill_cache_empty(), dashboard_wt_totals_t::dirty, dashboard_wt_totals_t::errors, ngx_brix_srv_metrics_t::in_use, ngx_brix_shm_zone, dashboard_wt_totals_t::pending, ngx_brix_metrics_t::servers, dashboard_wt_totals_t::success, ngx_brix_srv_metrics_t::wt_dirty_handles, ngx_brix_srv_metrics_t::wt_flush_bytes_total, ngx_brix_srv_metrics_t::wt_flush_error_total, ngx_brix_srv_metrics_t::wt_flush_pending, and ngx_brix_srv_metrics_t::wt_flush_success_total.
Referenced by dashboard_build_v1_cache(), and dashboard_build_v1_snapshot().
dashboard_fill_cluster()
void dashboard_fill_cluster (json_t * target, ngx_pool_t * pool, int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t redact)
Definition at line 349 of file api_snapshot_panels.c.
References BRIX_SRV_REGISTRY_SLOTS, brix_srv_snapshot(), ngx_http_brix_dashboard_loc_conf_t::cluster_stale_after_ms, brix_srv_snapshot_entry_t::host, brix_srv_snapshot_entry_t::last_seen, ngx_pcalloc(), and port.
Referenced by dashboard_build_v1_cluster(), and dashboard_build_v1_snapshot().
dashboard_fill_cvmfs()
void dashboard_fill_cvmfs (json_t * target, ngx_uint_t redact)
Definition at line 166 of file api_cvmfs.c.
References BRIX_CVMFS_CLASS_COUNT, BRIX_CVMFS_REPO_READY, BRIX_CVMFS_REPO_SLOTS, BRIX_CVMFS_UPSTREAM_SLOTS, c, ngx_brix_metrics_t::cvmfs, cvmfs_json_repo(), cvmfs_json_repo_is_dup(), cvmfs_json_requests(), cvmfs_json_upstream(), cvmfs_json_upstream_is_dup(), ngx_brix_shm_zone, ngx_brix_cvmfs_repo_metrics_t::state, and ngx_brix_cvmfs_upstream_metrics_t::state.
Referenced by dashboard_build_v1_cvmfs(), and dashboard_build_v1_snapshot().
dashboard_fill_history()
void dashboard_fill_history (json_t * target, ngx_pool_t * pool)
Definition at line 308 of file api_snapshot.c.
References active, BRIX_DASHBOARD_HISTORY_BUCKETS, BRIX_DASHBOARD_HISTORY_INTERVAL_MS, brix_dashboard_history_snapshot(), BRIX_XFER_NPROTOS, dashboard_proto_name(), and ngx_pcalloc().
Referenced by dashboard_build_v1_history(), and dashboard_build_v1_snapshot().
dashboard_fill_storage()
void dashboard_fill_storage (json_t * target, ngx_uint_t redact)
Definition at line 329 of file api_snapshot_panels.c.
References dashboard_build_storage_exports(), and dashboard_build_storage_io().
Referenced by dashboard_build_v1_snapshot().
dashboard_new_v1_root()
json_t * dashboard_new_v1_root (int64_t now_ms, const ngx_http_brix_dashboard_loc_conf_t * conf)
Definition at line 360 of file api_snapshot.c.
References dashboard_build_limits(), and dashboard_json_set_schema().
Referenced by dashboard_build_v1_cache(), dashboard_build_v1_cluster(), dashboard_build_v1_cvmfs(), dashboard_build_v1_events(), dashboard_build_v1_history(), dashboard_build_v1_not_found(), dashboard_build_v1_ratelimit(), dashboard_build_v1_snapshot(), dashboard_build_v1_transfer_detail(), dashboard_build_v1_transfers(), and dashboard_build_v1_truncated().
dashboard_parse_detail_id()
ngx_int_t dashboard_parse_detail_id (ngx_http_request_t * r, uint32_t * id)
Definition at line 372 of file api_transfers.c.
References c.
Referenced by dashboard_build_v1_transfer_detail().
dashboard_proto_name()
const char * dashboard_proto_name (uint8_t proto)
Definition at line 20 of file api.c.
References BRIX_PROTO_LIST, BRIX_XFER_NPROTOS, and X.
Referenced by dashboard_build_events(), dashboard_build_protocols(), dashboard_emit_base_fields(), and dashboard_fill_history().
dashboard_session_hash()
uint32_t dashboard_session_hash (const u_char sessid[16])
Definition at line 118 of file api.c.
References BRIX_FNV1A32_OFFSET_BASIS, and BRIX_FNV1A32_PRIME.
Referenced by dashboard_emit_detail_fields().
dashboard_state_name()
const char * dashboard_state_name (const ngx_http_brix_dashboard_loc_conf_t * conf, uint8_t state, int64_t idle_ms, int moving)
Definition at line 38 of file api.c.
References BRIX_XFER_STATE_CLOSING, BRIX_XFER_STATE_ERROR, ngx_http_brix_dashboard_loc_conf_t::idle_threshold_ms, and ngx_http_brix_dashboard_loc_conf_t::stalled_threshold_ms.
Referenced by dashboard_emit_v1_fields().
dashboard_tpc_direction_name()
const char * dashboard_tpc_direction_name (ngx_uint_t direction)
Definition at line 73 of file api.c.
References BRIX_TPC_DIR_PULL, and BRIX_TPC_DIR_PUSH.
Referenced by dashboard_build_tpc_registry().
dashboard_tpc_protocol_name()
const char * dashboard_tpc_protocol_name (ngx_uint_t protocol)
Definition at line 62 of file api.c.
References BRIX_TPC_PROTO_STREAM, and BRIX_TPC_PROTO_WEBDAV.
Referenced by dashboard_build_tpc_registry().
dashboard_tpc_state_name()
const char * dashboard_tpc_state_name (ngx_uint_t state)
Definition at line 84 of file api.c.
References BRIX_TPC_STATE_ACTIVE, BRIX_TPC_STATE_DONE, BRIX_TPC_STATE_ERROR, and BRIX_TPC_STATE_PENDING.
Referenced by dashboard_build_tpc_registry().