nginx-xrootd: src/observability/dashboard/dashboard_http.h File Reference
dashboard_http.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include "dashboard.h"
#include "observability/metrics/metrics.h"
#include "net/ratelimit/ratelimit.h"
Data Structures
struct ngx_http_brix_dashboard_user_t
struct ngx_http_brix_dashboard_loc_conf_t
Enumerations
enum brix_dashboard_api_endpoint_e {
BRIX_DASHBOARD_API_COMPAT_TRANSFERS = 0 , BRIX_DASHBOARD_API_V1_TRANSFERS , BRIX_DASHBOARD_API_V1_TRANSFER_DETAIL , BRIX_DASHBOARD_API_V1_SNAPSHOT ,
BRIX_DASHBOARD_API_V1_EVENTS , BRIX_DASHBOARD_API_V1_HISTORY , BRIX_DASHBOARD_API_V1_CLUSTER , BRIX_DASHBOARD_API_V1_CACHE ,
BRIX_DASHBOARD_API_V1_RATELIMIT , BRIX_DASHBOARD_API_V1_CVMFS , BRIX_DASHBOARD_API_V1_NOT_FOUND
}
Functions
ngx_int_t ngx_http_brix_dashboard_files_handler (ngx_http_request_t *r)
ngx_int_t ngx_http_brix_dashboard_vfs_exports_handler (ngx_http_request_t *r)
ngx_int_t ngx_http_brix_dashboard_vfs_files_handler (ngx_http_request_t *r)
ngx_int_t ngx_http_brix_dashboard_vfs_download_handler (ngx_http_request_t *r)
ngx_int_t ngx_http_brix_dashboard_download_handler (ngx_http_request_t *r)
ngx_int_t ngx_http_brix_dashboard_scan_handler (ngx_http_request_t *r)
ngx_int_t ngx_http_brix_dashboard_main_handler (ngx_http_request_t *r)
ngx_int_t ngx_http_brix_dashboard_api_handler (ngx_http_request_t *r, brix_dashboard_api_endpoint_e endpoint)
ngx_int_t ngx_http_brix_dashboard_page_handler (ngx_http_request_t *r)
ngx_int_t ngx_http_brix_dashboard_config_download_handler (ngx_http_request_t *r)
ngx_int_t ngx_http_brix_dashboard_login_handler (ngx_http_request_t *r)
ngx_int_t ngx_http_brix_dashboard_check_auth (ngx_http_request_t *r, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t suppress_missing_cookie)
Variables
ngx_module_t ngx_http_brix_dashboard_module
Enumeration Type Documentation
brix_dashboard_api_endpoint_e
enum brix_dashboard_api_endpoint_e
Enumerator
BRIX_DASHBOARD_API_COMPAT_TRANSFERS
BRIX_DASHBOARD_API_V1_TRANSFERS
BRIX_DASHBOARD_API_V1_TRANSFER_DETAIL
BRIX_DASHBOARD_API_V1_SNAPSHOT
BRIX_DASHBOARD_API_V1_EVENTS
BRIX_DASHBOARD_API_V1_HISTORY
BRIX_DASHBOARD_API_V1_CLUSTER
BRIX_DASHBOARD_API_V1_CACHE
BRIX_DASHBOARD_API_V1_RATELIMIT
BRIX_DASHBOARD_API_V1_CVMFS
BRIX_DASHBOARD_API_V1_NOT_FOUND
Definition at line 102 of file dashboard_http.h.
Function Documentation
ngx_http_brix_dashboard_api_handler()
ngx_int_t ngx_http_brix_dashboard_api_handler (ngx_http_request_t * r, brix_dashboard_api_endpoint_e endpoint)
Definition at line 232 of file api.c.
References ngx_http_brix_dashboard_loc_conf_t::anonymous, BRIX_DASH_EVENT_DASHBOARD, brix_dashboard_event_add(), brix_dashboard_history_sample(), dashboard_build_v1_truncated(), dashboard_collect_totals(), dashboard_dispatch_builder(), dashboard_endpoint_is_anon_allowed(), dashboard_json_send(), ngx_http_brix_dashboard_check_auth(), and ngx_http_brix_dashboard_module.
Referenced by dashboard_dispatch_api_route(), and ngx_http_brix_dashboard_main_handler().
ngx_http_brix_dashboard_check_auth()
ngx_int_t ngx_http_brix_dashboard_check_auth (ngx_http_request_t * r, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t suppress_missing_cookie)
Definition at line 221 of file auth.c.
References BRIX_DASH_EVENT_AUTH, brix_dashboard_event_add(), dash_auth_check_timestamp(), dash_auth_extract_hex(), dash_auth_resolve_key(), dash_auth_verify_hmac(), dashboard_find_cookie(), dashboard_users_enabled(), HMAC_HEX_LEN, ngx_http_brix_dashboard_loc_conf_t::password, ngx_http_brix_dashboard_loc_conf_t::session_ttl, TIMESTAMP_MAX, and dash_cookie_parse_t::ts_len.
Referenced by dashboard_files_gate(), ngx_http_brix_dashboard_api_handler(), ngx_http_brix_dashboard_config_download_handler(), ngx_http_brix_dashboard_page_handler(), ngx_http_brix_dashboard_scan_handler(), and vfs_browse_preamble().
ngx_http_brix_dashboard_config_download_handler()
ngx_int_t ngx_http_brix_dashboard_config_download_handler (ngx_http_request_t * r)
Definition at line 315 of file config_download.c.
References brix_http_source_offer(), dashboard_read_config_file(), dashboard_redact_config(), dashboard_send_config(), ngx_http_brix_dashboard_check_auth(), and ngx_http_brix_dashboard_module.
ngx_http_brix_dashboard_download_handler()
ngx_int_t ngx_http_brix_dashboard_download_handler (ngx_http_request_t * r)
Definition at line 473 of file files.c.
References close(), dashboard_download_body(), dashboard_download_open(), dashboard_download_set_headers(), dashboard_files_gate(), ngx_http_brix_dashboard_module, PATH_MAX, and stat().
ngx_http_brix_dashboard_files_handler()
ngx_int_t ngx_http_brix_dashboard_files_handler (ngx_http_request_t * r)
Definition at line 318 of file files.c.
References dashboard_files_gate(), dashboard_files_opendir(), dashboard_files_render(), ngx_http_brix_dashboard_module, and PATH_MAX.
ngx_http_brix_dashboard_login_handler()
ngx_int_t ngx_http_brix_dashboard_login_handler (ngx_http_request_t * r)
Definition at line 425 of file dashboard_auth_login.c.
References login_form_html, login_post_body_handler(), and send_html().
Referenced by ngx_http_brix_dashboard_main_handler().
ngx_http_brix_dashboard_main_handler()
ngx_int_t ngx_http_brix_dashboard_main_handler (ngx_http_request_t * r)
Definition at line 182 of file module_dispatch.c.
References brix_admin_dispatch(), BRIX_DASHBOARD_API_V1_NOT_FOUND, brix_http_source_offer(), dashboard_dispatch_api_route(), dashboard_dispatch_handler_route(), dashboard_uri_eq(), ngx_http_brix_dashboard_loc_conf_t::enable, ngx_http_brix_dashboard_api_handler(), ngx_http_brix_dashboard_login_handler(), ngx_http_brix_dashboard_module, and ngx_http_brix_dashboard_page_handler().
Referenced by ngx_http_brix_dashboard_set().
ngx_http_brix_dashboard_page_handler()
ngx_int_t ngx_http_brix_dashboard_page_handler (ngx_http_request_t * r)
Definition at line 164 of file page.c.
References ngx_http_brix_dashboard_loc_conf_t::anonymous, BRIX_PCALLOC_OR_RETURN, ngx_http_brix_dashboard_loc_conf_t::cookie_path, ngx_brix_dashboard_html, ngx_http_brix_dashboard_check_auth(), ngx_http_brix_dashboard_module, ngx_memcpy, and ngx_pnalloc().
Referenced by ngx_http_brix_dashboard_main_handler().
ngx_http_brix_dashboard_scan_handler()
ngx_int_t ngx_http_brix_dashboard_scan_handler (ngx_http_request_t * r)
Definition at line 392 of file scan_http.c.
References brix_http_source_offer(), scan_result_t::buf, scan_err_t::code, brix_scan_summary_t::elapsed_s, scan_request_t::mode_raw, scan_err_t::msg, ngx_http_brix_dashboard_check_auth(), ngx_http_brix_dashboard_module, scan_request_t::relpath, scan_err_http(), scan_health(), scan_parse_query(), scan_read_mode(), scan_render(), ngx_http_brix_dashboard_loc_conf_t::scan_root_canon, scan_run_walk(), and scan_result_t::summary.
ngx_http_brix_dashboard_vfs_download_handler()
ngx_int_t ngx_http_brix_dashboard_vfs_download_handler (ngx_http_request_t * r)
Definition at line 399 of file vfs_browse.c.
References BRIX_ETAG_WEAK, brix_http_serve_file_ranged(), brix_vfs_backend_export_info(), brix_vfs_close(), brix_vfs_file_stat(), BRIX_VFS_O_READ, brix_vfs_open(), BRIX_XFER_PROTO_WEBDAV, brix_http_serve_opts_t::etag_flags, brix_http_serve_opts_t::identity, brix_vfs_stat_t::is_regular, ngx_http_brix_dashboard_module, brix_http_serve_opts_t::op_name, PATH_MAX, brix_vfs_backend_info_t::root_canon, vfs_browse_abs_path(), vfs_browse_ctx(), vfs_browse_get_export(), vfs_browse_get_path(), vfs_browse_preamble(), vfs_browse_status(), and brix_http_serve_opts_t::xfer_proto.
ngx_http_brix_dashboard_vfs_exports_handler()
ngx_int_t ngx_http_brix_dashboard_vfs_exports_handler (ngx_http_request_t * r)
Definition at line 179 of file vfs_browse.c.
References brix_vfs_backend_info_t::backend, brix_vfs_backend_export_count(), brix_vfs_backend_export_info(), dashboard_json_send(), dashboard_json_set_schema(), brix_vfs_backend_info_t::host, ngx_http_brix_dashboard_module, brix_vfs_backend_info_t::port, brix_vfs_backend_info_t::root_canon, brix_vfs_backend_info_t::staging, and vfs_browse_preamble().
ngx_http_brix_dashboard_vfs_files_handler()
ngx_int_t ngx_http_brix_dashboard_vfs_files_handler (ngx_http_request_t * r)
Definition at line 338 of file vfs_browse.c.
References brix_vfs_backend_info_t::backend, brix_vfs_backend_export_info(), brix_vfs_closedir(), brix_vfs_opendir(), dashboard_json_send(), dashboard_json_set_schema(), ngx_http_brix_dashboard_module, PATH_MAX, brix_vfs_backend_info_t::root_canon, vfs_browse_abs_path(), vfs_browse_collect(), vfs_browse_ctx(), vfs_browse_get_export(), vfs_browse_get_path(), vfs_browse_preamble(), and vfs_browse_status().
Variable Documentation
ngx_http_brix_dashboard_module
ngx_module_t ngx_http_brix_dashboard_module extern
Definition at line 479 of file module.c.
Referenced by admin_proxy_add(), brix_admin_body_callback(), brix_admin_dispatch(), brix_admin_read_body(), dashboard_http_bind_slot(), dashboard_http_track(), login_post_body_handler(), ngx_http_brix_dashboard_api_handler(), ngx_http_brix_dashboard_config_download_handler(), ngx_http_brix_dashboard_download_handler(), ngx_http_brix_dashboard_files_handler(), ngx_http_brix_dashboard_main_handler(), ngx_http_brix_dashboard_page_handler(), ngx_http_brix_dashboard_scan_handler(), ngx_http_brix_dashboard_vfs_download_handler(), ngx_http_brix_dashboard_vfs_exports_handler(), and ngx_http_brix_dashboard_vfs_files_handler().