nginx-xrootd: src/observability/dashboard/dashboard_api_admin_internal.h File Reference
dashboard_api_admin_internal.h File Reference
#include "dashboard.h"
#include "api_admin.h"
#include "dashboard_json.h"
#include "net/manager/registry.h"
#include "protocols/webdav/proxy_pool.h"
#include "core/http/http_headers.h"
#include <jansson.h>
#include <openssl/crypto.h>
Data Structures
struct brix_admin_body_ctx_t
Macros
#define ADMIN_PREFIX "/brix/api/v1/admin/"
#define ADMIN_MAX_BODY 65536
#define ADMIN_SECRET_MAX 4096
#define ADMIN_SECRET_MIN 16
Typedefs
typedef ngx_int_t(* brix_admin_body_handler_t) (ngx_http_request_t *r, json_t *body)
Enumerations
enum brix_admin_auth_result_t { BRIX_ADMIN_AUTH_OK = 0 , BRIX_ADMIN_AUTH_DENIED }
Functions
ngx_int_t brix_uring_killswitch_set (ngx_uint_t disabled)
ngx_int_t brix_uring_killswitch_get (void)
ngx_int_t brix_uring_admin_enabled (void)
ngx_int_t admin_send_ok (ngx_http_request_t *r, const char *result)
ngx_int_t admin_send_error (ngx_http_request_t *r, ngx_int_t status, const char *code)
int admin_validate_hostname (const char *host)
int admin_validate_paths (const char *paths)
brix_admin_auth_result_t brix_admin_check_auth (ngx_http_request_t *r, const ngx_http_brix_dashboard_loc_conf_t *conf)
void admin_audit (ngx_http_request_t *r, const char *action, const char *target, const char *result)
void brix_admin_body_callback (ngx_http_request_t *r)
ngx_int_t brix_admin_read_body (ngx_http_request_t *r, brix_admin_body_handler_t handler)
ngx_int_t admin_parse_server_uri (ngx_http_request_t *r, char *host_out, size_t host_size, uint16_t *port_out, char *action_out, size_t action_size)
ngx_int_t admin_cluster_register (ngx_http_request_t *r, json_t *body)
ngx_int_t admin_cluster_drain (ngx_http_request_t *r, json_t *body)
ngx_int_t admin_cluster_delete (ngx_http_request_t *r)
ngx_int_t admin_cluster_undrain (ngx_http_request_t *r)
int admin_validate_url (const char *url)
ngx_int_t admin_parse_proxy_uri (ngx_http_request_t *r, uint32_t *id_out, char *action_out, size_t action_size)
json_t * admin_proxy_backend_json (const brix_proxy_be_snapshot_t *e)
int admin_url_host_allowed (ngx_http_brix_dashboard_loc_conf_t *conf, const char *url)
ngx_int_t admin_proxy_add (ngx_http_request_t *r, json_t *body)
ngx_int_t admin_proxy_list (ngx_http_request_t *r)
ngx_int_t admin_proxy_one (ngx_http_request_t *r, const char *action, uint32_t id)
int admin_uri_eq (ngx_http_request_t *r, const char *s)
int admin_uri_has_action (ngx_http_request_t *r, const char *action)
ngx_int_t admin_io_uring_set (ngx_http_request_t *r, json_t *body)
ngx_int_t admin_io_uring_get (ngx_http_request_t *r)
Macro Definition Documentation
ADMIN_MAX_BODY
#define ADMIN_MAX_BODY 65536
Definition at line 17 of file dashboard_api_admin_internal.h.
ADMIN_PREFIX
#define ADMIN_PREFIX "/brix/api/v1/admin/"
Definition at line 16 of file dashboard_api_admin_internal.h.
ADMIN_SECRET_MAX
#define ADMIN_SECRET_MAX 4096
Definition at line 18 of file dashboard_api_admin_internal.h.
ADMIN_SECRET_MIN
#define ADMIN_SECRET_MIN 16
Definition at line 19 of file dashboard_api_admin_internal.h.
Typedef Documentation
brix_admin_body_handler_t
typedef ngx_int_t(* brix_admin_body_handler_t) (ngx_http_request_t *r, json_t *body)
Definition at line 29 of file dashboard_api_admin_internal.h.
Enumeration Type Documentation
brix_admin_auth_result_t
enum brix_admin_auth_result_t
Enumerator
BRIX_ADMIN_AUTH_OK
BRIX_ADMIN_AUTH_DENIED
Definition at line 24 of file dashboard_api_admin_internal.h.
Function Documentation
admin_audit()
void admin_audit (ngx_http_request_t * r, const char * action, const char * target, const char * result)
Definition at line 220 of file api_admin.c.
Referenced by admin_cluster_delete(), admin_cluster_drain(), admin_cluster_register(), admin_cluster_undrain(), admin_io_uring_set(), admin_proxy_add(), admin_proxy_one(), admin_rate_gate(), and brix_admin_dispatch().
admin_cluster_delete()
ngx_int_t admin_cluster_delete (ngx_http_request_t * r)
Definition at line 235 of file api_admin_cluster.c.
References admin_audit(), admin_parse_server_uri(), admin_send_error(), admin_send_ok(), BRIX_DASH_EVENT_NAMESPACE, brix_dashboard_event_add(), brix_srv_unregister(), host, and port.
Referenced by admin_route_cluster_server().
admin_cluster_drain()
ngx_int_t admin_cluster_drain (ngx_http_request_t * r, json_t * body)
Definition at line 209 of file api_admin_cluster.c.
References admin_audit(), admin_parse_server_uri(), admin_send_error(), admin_send_ok(), BRIX_DASH_EVENT_NAMESPACE, brix_dashboard_event_add(), brix_srv_blacklist(), host, and port.
Referenced by admin_route_cluster_server().
admin_cluster_register()
ngx_int_t admin_cluster_register (ngx_http_request_t * r, json_t * body)
Definition at line 177 of file api_admin_cluster.c.
References admin_audit(), admin_send_error(), admin_send_ok(), admin_validate_hostname(), admin_validate_paths(), BRIX_DASH_EVENT_NAMESPACE, brix_dashboard_event_add(), brix_srv_register(), host, and port.
Referenced by admin_route_cluster(), and admin_route_cluster_server().
admin_cluster_undrain()
ngx_int_t admin_cluster_undrain (ngx_http_request_t * r)
Definition at line 257 of file api_admin_cluster.c.
References admin_audit(), admin_parse_server_uri(), admin_send_error(), admin_send_ok(), BRIX_DASH_EVENT_NAMESPACE, brix_dashboard_event_add(), brix_srv_undrain(), host, and port.
Referenced by admin_route_cluster_server().
admin_io_uring_get()
ngx_int_t admin_io_uring_get (ngx_http_request_t * r)
Definition at line 54 of file api_admin_config.c.
References brix_uring_killswitch_get(), dashboard_json_send(), and dashboard_json_set_schema().
Referenced by admin_route_io_uring().
admin_io_uring_set()
ngx_int_t admin_io_uring_set (ngx_http_request_t * r, json_t * body)
Definition at line 22 of file api_admin_config.c.
References admin_audit(), admin_send_error(), brix_uring_killswitch_set(), dashboard_json_send(), and dashboard_json_set_schema().
Referenced by admin_route_io_uring().
admin_parse_proxy_uri()
ngx_int_t admin_parse_proxy_uri (ngx_http_request_t * r, uint32_t * id_out, char * action_out, size_t action_size)
Definition at line 10 of file api_admin_proxy.c.
References ADMIN_PREFIX, and ngx_memcpy.
Referenced by admin_route_proxy().
admin_parse_server_uri()
ngx_int_t admin_parse_server_uri (ngx_http_request_t * r, char * host_out, size_t host_size, uint16_t * port_out, char * action_out, size_t action_size)
Definition at line 142 of file api_admin_cluster.c.
References admin_copy_server_tail(), admin_extract_host(), admin_parse_port(), and admin_split_server_segments().
Referenced by admin_cluster_delete(), admin_cluster_drain(), and admin_cluster_undrain().
admin_proxy_add()
ngx_int_t admin_proxy_add (ngx_http_request_t * r, json_t * body)
Definition at line 131 of file api_admin_proxy.c.
References admin_audit(), admin_send_error(), admin_url_host_allowed(), admin_validate_url(), BRIX_DASH_EVENT_NAMESPACE, brix_dashboard_event_add(), brix_proxy_pool_add(), dashboard_json_send(), dashboard_json_set_schema(), and ngx_http_brix_dashboard_module.
Referenced by admin_route_proxy().
admin_proxy_backend_json()
json_t * admin_proxy_backend_json (const brix_proxy_be_snapshot_t * e)
Definition at line 57 of file api_admin_proxy.c.
References BRIX_PROXY_BE_DEAD, BRIX_PROXY_BE_DRAINING, brix_proxy_be_snapshot_t::host, brix_proxy_be_snapshot_t::id, brix_proxy_be_snapshot_t::in_flight, brix_proxy_be_snapshot_t::port, brix_proxy_be_snapshot_t::ssl, brix_proxy_be_snapshot_t::state, and brix_proxy_be_snapshot_t::weight.
Referenced by admin_proxy_list().
admin_proxy_list()
ngx_int_t admin_proxy_list (ngx_http_request_t * r)
Definition at line 186 of file api_admin_proxy.c.
References admin_proxy_backend_json(), BRIX_PROXY_POOL_SLOTS, brix_proxy_pool_snapshot(), dashboard_json_send(), and dashboard_json_set_schema().
Referenced by admin_route_proxy().
admin_proxy_one()
ngx_int_t admin_proxy_one (ngx_http_request_t * r, const char * action, uint32_t id)
Definition at line 221 of file api_admin_proxy.c.
References admin_audit(), admin_send_error(), admin_send_ok(), brix_proxy_pool_drain(), brix_proxy_pool_in_flight(), brix_proxy_pool_remove(), brix_proxy_pool_undrain(), dashboard_json_send(), and dashboard_json_set_schema().
Referenced by admin_route_proxy().
admin_send_error()
ngx_int_t admin_send_error (ngx_http_request_t * r, ngx_int_t status, const char * code)
Definition at line 21 of file api_admin.c.
References code, dashboard_json_send(), and dashboard_json_set_schema().
Referenced by admin_cluster_delete(), admin_cluster_drain(), admin_cluster_register(), admin_cluster_undrain(), admin_io_uring_set(), admin_proxy_add(), admin_proxy_one(), admin_rate_gate(), admin_route_cluster(), admin_route_cluster_server(), admin_route_io_uring(), admin_route_proxy(), brix_admin_body_callback(), and brix_admin_dispatch().
admin_send_ok()
ngx_int_t admin_send_ok (ngx_http_request_t * r, const char * result)
Definition at line 8 of file api_admin.c.
References dashboard_json_send(), and dashboard_json_set_schema().
Referenced by admin_cluster_delete(), admin_cluster_drain(), admin_cluster_register(), admin_cluster_undrain(), and admin_proxy_one().
admin_uri_eq()
int admin_uri_eq (ngx_http_request_t * r, const char * s)
Definition at line 408 of file api_admin.c.
References s.
Referenced by admin_route_cluster(), admin_route_io_uring(), and admin_route_proxy().
admin_uri_has_action()
int admin_uri_has_action (ngx_http_request_t * r, const char * action)
Definition at line 418 of file api_admin.c.
Referenced by admin_route_cluster_server().
admin_url_host_allowed()
int admin_url_host_allowed (ngx_http_brix_dashboard_loc_conf_t * conf, const char * url)
Definition at line 91 of file api_admin_proxy.c.
References ngx_http_brix_dashboard_loc_conf_t::admin_proxy_allow, and host.
Referenced by admin_proxy_add().
admin_validate_hostname()
int admin_validate_hostname (const char * host)
Definition at line 38 of file api_admin.c.
References c, and host.
Referenced by admin_cluster_register().
admin_validate_paths()
int admin_validate_paths (const char * paths)
Definition at line 95 of file api_admin.c.
References admin_path_char_ok(), and BRIX_SRV_MAX_PATHS.
Referenced by admin_cluster_register().
admin_validate_url()
int admin_validate_url (const char * url)
Definition at line 379 of file api_admin.c.
References admin_url_char_ok(), admin_url_scheme_off(), and host.
Referenced by admin_proxy_add().
brix_admin_body_callback()
void brix_admin_body_callback (ngx_http_request_t * r)
Definition at line 245 of file api_admin.c.
References ADMIN_MAX_BODY, admin_send_error(), brix_admin_body_ctx_t::handler, ngx_http_brix_dashboard_module, and ngx_memcpy.
Referenced by brix_admin_read_body().
brix_admin_check_auth()
brix_admin_auth_result_t brix_admin_check_auth (ngx_http_request_t * r, const ngx_http_brix_dashboard_loc_conf_t * conf)
Definition at line 195 of file api_admin.c.
References ngx_http_brix_dashboard_loc_conf_t::admin_allow, admin_auth_cidr_ok(), admin_auth_combine(), admin_auth_secret_ok(), ngx_http_brix_dashboard_loc_conf_t::admin_secret, and BRIX_ADMIN_AUTH_DENIED.
Referenced by brix_admin_dispatch().
brix_admin_read_body()
ngx_int_t brix_admin_read_body (ngx_http_request_t * r, brix_admin_body_handler_t handler)
Definition at line 314 of file api_admin.c.
References brix_admin_body_callback(), handler, brix_admin_body_ctx_t::handler, and ngx_http_brix_dashboard_module.
Referenced by admin_route_cluster(), admin_route_cluster_server(), admin_route_io_uring(), and admin_route_proxy().
brix_uring_admin_enabled()
ngx_int_t brix_uring_admin_enabled (void)
Definition at line 128 of file uring_admin.c.
brix_uring_killswitch_get()
ngx_int_t brix_uring_killswitch_get (void)
Definition at line 114 of file uring_admin.c.
Referenced by brix_uring_panic_handler().
brix_uring_killswitch_set()
ngx_int_t brix_uring_killswitch_set (ngx_uint_t disabled)
Definition at line 102 of file uring_admin.c.
Referenced by brix_uring_panic_handler().