nginx-xrootd: src/observability/dashboard/dashboard_auth_internal.h File Reference
dashboard_auth_internal.h File Reference
#include "dashboard_http.h"
Data Structures
struct dash_form_out_t
Macros
#define HMAC_HEX_LEN 64 /* SHA-256 = 32 bytes = 64 hex chars */
#define TIMESTAMP_MAX 20 /* enough for a Unix timestamp string */
Functions
ngx_int_t dashboard_find_cookie (ngx_http_request_t *r, const char *name, size_t name_len, u_char **val, size_t *val_len)
ngx_int_t dashboard_form_value (const u_char *body, size_t body_len, const char *name, dash_form_out_t *out)
ngx_uint_t dashboard_users_enabled (const ngx_http_brix_dashboard_loc_conf_t *conf)
ngx_http_brix_dashboard_user_t * dashboard_find_user (const ngx_http_brix_dashboard_loc_conf_t *conf, const char *username, size_t username_len)
ngx_int_t dashboard_verify_user_password (ngx_pool_t *pool, ngx_http_brix_dashboard_user_t *user, const char *password, size_t password_len)
ngx_int_t dashboard_cookie_hmac (const ngx_str_t *key, const char *ts, size_t ts_len, const char *username, size_t username_len, char out_hex[64+1])
Macro Definition Documentation
HMAC_HEX_LEN
#define HMAC_HEX_LEN 64 /* SHA-256 = 32 bytes = 64 hex chars */
Definition at line 28 of file dashboard_auth_internal.h.
TIMESTAMP_MAX
#define TIMESTAMP_MAX 20 /* enough for a Unix timestamp string */
Definition at line 29 of file dashboard_auth_internal.h.
Function Documentation
dashboard_cookie_hmac()
ngx_int_t dashboard_cookie_hmac (const ngx_str_t * key, const char * ts, size_t ts_len, const char * username, size_t username_len, char out_hex[64+1])
Definition at line 167 of file dashboard_auth_creds.c.
References hmac_sha256_hex(), key, ngx_memcpy, and TIMESTAMP_MAX.
Referenced by dash_auth_verify_hmac(), and login_issue_cookie().
dashboard_find_cookie()
ngx_int_t dashboard_find_cookie (ngx_http_request_t * r, const char * name, size_t name_len, u_char ** val, size_t * val_len)
Definition at line 81 of file dashboard_auth_parse.c.
References dash_cookie_header(), dash_cookie_next_pair(), and name.
Referenced by ngx_http_brix_dashboard_check_auth().
dashboard_find_user()
ngx_http_brix_dashboard_user_t * dashboard_find_user (const ngx_http_brix_dashboard_loc_conf_t * conf, const char * username, size_t username_len)
Definition at line 61 of file dashboard_auth_creds.c.
References dashboard_users_enabled(), and ngx_http_brix_dashboard_loc_conf_t::users.
Referenced by dash_auth_resolve_key(), and login_verify_credentials().
dashboard_form_value()
ngx_int_t dashboard_form_value (const u_char * body, size_t body_len, const char * name, dash_form_out_t * out)
Definition at line 228 of file dashboard_auth_parse.c.
References dash_form_out_t::buf, dash_form_decode_value(), dash_form_next_pair(), dash_form_pair_t::key_len, dash_form_pair_t::key_start, dash_form_out_t::len, name, dash_form_out_t::size, dash_form_pair_t::val_end, and dash_form_pair_t::val_start.
Referenced by login_verify_credentials().
dashboard_users_enabled()
ngx_uint_t dashboard_users_enabled (const ngx_http_brix_dashboard_loc_conf_t * conf)
Definition at line 53 of file dashboard_auth_creds.c.
References ngx_http_brix_dashboard_loc_conf_t::users.
Referenced by dash_auth_resolve_key(), dashboard_find_user(), login_issue_cookie(), login_verify_credentials(), and ngx_http_brix_dashboard_check_auth().
dashboard_verify_user_password()
ngx_int_t dashboard_verify_user_password (ngx_pool_t * pool, ngx_http_brix_dashboard_user_t * user, const char * password, size_t password_len)
Definition at line 108 of file dashboard_auth_creds.c.
References BRIX_PNALLOC_OR_RETURN, dashboard_copy_str0(), ngx_memcpy, and ngx_http_brix_dashboard_user_t::password_hash.
Referenced by login_verify_credentials().