nginx-xrootd: src/observability/dashboard/dashboard_json.c File Reference
dashboard_json.c File Reference
#include "dashboard_json.h"
Macros
#define DASHBOARD_SCHEMA_VERSION "xrootd-dashboard.v1"
Functions
ngx_int_t dashboard_json_send (ngx_http_request_t *r, ngx_int_t status, json_t *root)
void dashboard_json_set_schema (json_t *root)
Macro Definition Documentation
DASHBOARD_SCHEMA_VERSION
#define DASHBOARD_SCHEMA_VERSION "xrootd-dashboard.v1"
Definition at line 71 of file dashboard_json.c.
Function Documentation
dashboard_json_send()
ngx_int_t dashboard_json_send (ngx_http_request_t * r, ngx_int_t status, json_t * root)
Definition at line 8 of file dashboard_json.c.
References ngx_pcalloc().
Referenced by admin_io_uring_get(), admin_io_uring_set(), admin_proxy_add(), admin_proxy_list(), admin_proxy_one(), admin_send_error(), admin_send_ok(), dashboard_files_render(), ngx_http_brix_dashboard_api_handler(), ngx_http_brix_dashboard_vfs_exports_handler(), and ngx_http_brix_dashboard_vfs_files_handler().
dashboard_json_set_schema()
void dashboard_json_set_schema (json_t * root)
Definition at line 74 of file dashboard_json.c.
References DASHBOARD_SCHEMA_VERSION.
Referenced by admin_io_uring_get(), admin_io_uring_set(), admin_proxy_add(), admin_proxy_list(), admin_proxy_one(), admin_send_error(), admin_send_ok(), dashboard_files_render(), dashboard_new_v1_root(), ngx_http_brix_dashboard_vfs_exports_handler(), and ngx_http_brix_dashboard_vfs_files_handler().