nginx-xrootd: src/observability/dashboard/dashboard_auth_login.c File Reference
dashboard_auth_login.c File Reference
#include "dashboard_auth_internal.h"
#include "core/ident.h"
#include <openssl/crypto.h>
#include <time.h>
#include <stdio.h>
#include <string.h>
Data Structures
struct ngx_http_dashboard_login_ctx_t
struct login_creds_t
Functions
static ngx_int_t send_html (ngx_http_request_t *r, ngx_int_t status, const char *html, size_t html_len)
static void login_fail_form (ngx_http_request_t *r)
static ngx_int_t login_collect_body (ngx_http_request_t *r, u_char **body_out, size_t *total_out)
static ngx_int_t login_verify_credentials (ngx_http_request_t *r, const ngx_http_brix_dashboard_loc_conf_t *conf, const u_char *body_buf, size_t total, login_creds_t *creds)
static ngx_int_t login_issue_cookie (ngx_http_request_t *r, const ngx_http_brix_dashboard_loc_conf_t *conf, const login_creds_t *creds)
static ngx_int_t login_set_redirect (ngx_http_request_t *r, const ngx_http_brix_dashboard_loc_conf_t *conf)
static void login_post_body_handler (ngx_http_request_t *r)
ngx_int_t ngx_http_brix_dashboard_login_handler (ngx_http_request_t *r)
Variables
static const char login_form_html []
static const char login_form_html_error []
Function Documentation
login_collect_body()
static ngx_int_t login_collect_body (ngx_http_request_t * r, u_char ** body_out, size_t * total_out) static
Definition at line 158 of file dashboard_auth_login.c.
References ngx_memcpy.
Referenced by login_post_body_handler().
login_fail_form()
static void login_fail_form (ngx_http_request_t * r) static
Definition at line 141 of file dashboard_auth_login.c.
References login_form_html_error, and send_html().
Referenced by login_post_body_handler().
login_issue_cookie()
static ngx_int_t login_issue_cookie (ngx_http_request_t * r, const ngx_http_brix_dashboard_loc_conf_t * conf, const login_creds_t * creds) static
Definition at line 273 of file dashboard_auth_login.c.
References BRIX_DASH_EVENT_AUTH, brix_dashboard_event_add(), ngx_http_brix_dashboard_loc_conf_t::cookie_path, dashboard_cookie_hmac(), dashboard_users_enabled(), HMAC_HEX_LEN, login_creds_t::hmac_key, TIMESTAMP_MAX, login_creds_t::username, and login_creds_t::username_len.
Referenced by login_post_body_handler().
login_post_body_handler()
static void login_post_body_handler (ngx_http_request_t * r) static
Definition at line 382 of file dashboard_auth_login.c.
References login_collect_body(), login_fail_form(), login_issue_cookie(), login_set_redirect(), login_verify_credentials(), and ngx_http_brix_dashboard_module.
Referenced by ngx_http_brix_dashboard_login_handler().
login_set_redirect()
static ngx_int_t login_set_redirect (ngx_http_request_t * r, const ngx_http_brix_dashboard_loc_conf_t * conf) static
Definition at line 343 of file dashboard_auth_login.c.
References ngx_http_brix_dashboard_loc_conf_t::cookie_path, ngx_memcpy, and ngx_pnalloc().
Referenced by login_post_body_handler().
login_verify_credentials()
static ngx_int_t login_verify_credentials (ngx_http_request_t * r, const ngx_http_brix_dashboard_loc_conf_t * conf, const u_char * body_buf, size_t total, login_creds_t * creds) static
Definition at line 206 of file dashboard_auth_login.c.
References BRIX_DASH_EVENT_AUTH, brix_dashboard_event_add(), dash_form_out_t::buf, dashboard_find_user(), dashboard_form_value(), dashboard_users_enabled(), dashboard_verify_user_password(), login_creds_t::hmac_key, dash_form_out_t::len, login_creds_t::password, ngx_http_brix_dashboard_loc_conf_t::password, ngx_http_brix_dashboard_user_t::password_hash, login_creds_t::pw_len, dash_form_out_t::size, login_creds_t::username, and login_creds_t::username_len.
Referenced by login_post_body_handler().
ngx_http_brix_dashboard_login_handler()
ngx_int_t ngx_http_brix_dashboard_login_handler (ngx_http_request_t * r)
Definition at line 425 of file dashboard_auth_login.c.
References login_form_html, login_post_body_handler(), and send_html().
Referenced by ngx_http_brix_dashboard_main_handler().
send_html()
static ngx_int_t send_html (ngx_http_request_t * r, ngx_int_t status, const char * html, size_t html_len) static
Definition at line 88 of file dashboard_auth_login.c.
References ngx_pcalloc().
Referenced by login_fail_form(), and ngx_http_brix_dashboard_login_handler().
Variable Documentation
login_form_html
const char login_form_html[] static
Initial value:
=
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head><meta charset=\"utf-8\">"
    "<title>"  "BriX-Cache"  " Monitor — Login</title>\n"
    "<style>\n"
    "body{background:#1a1a2e;color:#e0e0e0;font-family:monospace;"
    "display:flex;justify-content:center;align-items:center;height:100vh;margin:0}\n"
    ".box{background:#16213e;padding:2em 3em;border-radius:8px;"
    "border:1px solid #0f3460;min-width:320px}\n"
    "h2{color:#e94560;margin-bottom:1.5em;text-align:center}\n"
    "input[type=text],input[type=password]{width:100%;padding:.5em;background:#0f3460;"
    "border:1px solid #e94560;color:#e0e0e0;border-radius:4px;font-size:1em;box-sizing:border-box}\n"
    "input+input{margin-top:.75em}\n"
    "button{width:100%;padding:.6em;margin-top:1em;background:#e94560;"
    "border:none;color:#fff;font-size:1em;border-radius:4px;cursor:pointer}\n"
    "button:hover{background:#c73652}\n"
    ".err{color:#e94560;font-size:.85em;margin-top:.5em}\n"
    "</style></head>\n"
    "<body><div class=\"box\">\n"
    "<h2>Transfer Monitor</h2>\n"
    "<form method=\"post\">\n"
    "<input type=\"text\" name=\"username\" placeholder=\"Username\">\n"
    "<input type=\"password\" name=\"password\" placeholder=\"Admin password\" autofocus>\n"
    "<button type=\"submit\">Sign in</button>\n"
    "</form>\n"
    "</div></body></html>\n"
Definition at line 26 of file dashboard_auth_login.c.
Referenced by ngx_http_brix_dashboard_login_handler().
login_form_html_error
const char login_form_html_error[] static
Initial value:
=
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head><meta charset=\"utf-8\">"
    "<title>"  "BriX-Cache"  " Monitor — Login</title>\n"
    "<style>\n"
    "body{background:#1a1a2e;color:#e0e0e0;font-family:monospace;"
    "display:flex;justify-content:center;align-items:center;height:100vh;margin:0}\n"
    ".box{background:#16213e;padding:2em 3em;border-radius:8px;"
    "border:1px solid #0f3460;min-width:320px}\n"
    "h2{color:#e94560;margin-bottom:1.5em;text-align:center}\n"
    "input[type=text],input[type=password]{width:100%;padding:.5em;background:#0f3460;"
    "border:1px solid #e94560;color:#e0e0e0;border-radius:4px;font-size:1em;box-sizing:border-box}\n"
    "input+input{margin-top:.75em}\n"
    "button{width:100%;padding:.6em;margin-top:1em;background:#e94560;"
    "border:none;color:#fff;font-size:1em;border-radius:4px;cursor:pointer}\n"
    "button:hover{background:#c73652}\n"
    ".err{color:#e94560;font-size:.85em;margin-top:.5em}\n"
    "</style></head>\n"
    "<body><div class=\"box\">\n"
    "<h2>Transfer Monitor</h2>\n"
    "<form method=\"post\">\n"
    "<input type=\"text\" name=\"username\" placeholder=\"Username\">\n"
    "<input type=\"password\" name=\"password\" placeholder=\"Admin password\" autofocus>\n"
    "<button type=\"submit\">Sign in</button>\n"
    "</form>\n"
    "<p class=\"err\">Incorrect password.</p>\n"
    "</div></body></html>\n"
Definition at line 54 of file dashboard_auth_login.c.
Referenced by login_fail_form().