nginx-xrootd: src/observability/dashboard/dashboard_auth_parse.c File Reference
dashboard_auth_parse.c File Reference
#include "dashboard_auth_internal.h"
#include <string.h>
#include <ctype.h>
Data Structures
struct dash_form_pair_t
Functions
static ngx_table_elt_t * dash_cookie_header (ngx_http_request_t *r)
static void dash_cookie_next_pair (u_char **pp, u_char *end, u_char **start, u_char **eq)
ngx_int_t dashboard_find_cookie (ngx_http_request_t *r, const char *name, size_t name_len, u_char **val, size_t *val_len)
static ngx_int_t dash_form_next_pair (const u_char *body, size_t body_len, size_t *pos, dash_form_pair_t *pair)
static void dash_form_decode_value (const u_char *body, size_t val_start, size_t val_end, dash_form_out_t *out)
ngx_int_t dashboard_form_value (const u_char *body, size_t body_len, const char *name, dash_form_out_t *out)
Function Documentation
dash_cookie_header()
static ngx_table_elt_t * dash_cookie_header (ngx_http_request_t * r) static
Definition at line 33 of file dashboard_auth_parse.c.
Referenced by dashboard_find_cookie().
dash_cookie_next_pair()
static void dash_cookie_next_pair (u_char ** pp, u_char * end, u_char ** start, u_char ** eq) static
Definition at line 58 of file dashboard_auth_parse.c.
Referenced by dashboard_find_cookie().
dash_form_decode_value()
static void dash_form_decode_value (const u_char * body, size_t val_start, size_t val_end, dash_form_out_t * out) static
Definition at line 189 of file dashboard_auth_parse.c.
References dash_form_out_t::buf, dash_form_out_t::len, and dash_form_out_t::size.
Referenced by dashboard_form_value().
dash_form_next_pair()
static ngx_int_t dash_form_next_pair (const u_char * body, size_t body_len, size_t * pos, dash_form_pair_t * pair) static
Definition at line 135 of file dashboard_auth_parse.c.
References dash_form_pair_t::key_len, dash_form_pair_t::key_start, dash_form_pair_t::val_end, and dash_form_pair_t::val_start.
Referenced by dashboard_form_value().
dashboard_find_cookie()
ngx_int_t dashboard_find_cookie (ngx_http_request_t * r, const char * name, size_t name_len, u_char ** val, size_t * val_len)
Definition at line 81 of file dashboard_auth_parse.c.
References dash_cookie_header(), dash_cookie_next_pair(), and name.
Referenced by ngx_http_brix_dashboard_check_auth().
dashboard_form_value()
ngx_int_t dashboard_form_value (const u_char * body, size_t body_len, const char * name, dash_form_out_t * out)
Definition at line 228 of file dashboard_auth_parse.c.
References dash_form_out_t::buf, dash_form_decode_value(), dash_form_next_pair(), dash_form_pair_t::key_len, dash_form_pair_t::key_start, dash_form_out_t::len, name, dash_form_out_t::size, dash_form_pair_t::val_end, and dash_form_pair_t::val_start.
Referenced by login_verify_credentials().