nginx-xrootd: src/observability/dashboard/dashboard_tracking.h File Reference
dashboard_tracking.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include "dashboard.h"
Functions
int brix_dashboard_http_start (ngx_http_request_t *r, const char *path, uint8_t proto, uint8_t direction, const char *op, int64_t expected_bytes)
int brix_dashboard_http_start_identity (ngx_http_request_t *r, const char *path, const char *identity, const char *vo, uint8_t proto, uint8_t direction, const char *op, int64_t expected_bytes)
void brix_dashboard_http_add (ngx_http_request_t *r, ngx_atomic_int_t bytes)
void brix_dashboard_http_state (ngx_http_request_t *r, uint8_t state)
void brix_dashboard_http_error (ngx_http_request_t *r, const char *reason)
void brix_dashboard_http_tpc_remote (ngx_http_request_t *r, const char *remote_url, int remote_status, int curl_exit)
void brix_dashboard_http_finish (ngx_http_request_t *r)
Function Documentation
brix_dashboard_http_add()
void brix_dashboard_http_add (ngx_http_request_t * r, ngx_atomic_int_t bytes)
Definition at line 244 of file http_tracking.c.
References brix_transfer_slot_update_bytes(), dashboard_http_track(), brix_dashboard_http_track_t::slot, and brix_dashboard_http_track_t::table.
Referenced by s3_put_aio_done(), s3_put_finalize_ok(), serve_record_body_accounting(), tpc_marker_record_result(), tpc_thread_done(), webdav_put_aio_done(), webdav_put_write_sync(), webdav_tpc_finish_pull_success(), and webdav_tpc_push_sync_exec().
brix_dashboard_http_error()
void brix_dashboard_http_error (ngx_http_request_t * r, const char * reason)
Definition at line 270 of file http_tracking.c.
References brix_transfer_slot_set_error(), dashboard_http_track(), brix_dashboard_http_track_t::slot, and brix_dashboard_http_track_t::table.
Referenced by s3_put_finalize_bad_digest(), s3_put_finalize_client_error(), s3_put_finalize_codec_error(), s3_put_finalize_error(), s3_put_finalize_fs_error(), s3_put_finalize_invalid_request(), serve_send_memory_backed(), serve_send_sendfile(), serve_try_compressed(), tpc_marker_record_result(), tpc_thread_done(), webdav_put_aio_done(), webdav_put_select_codec(), webdav_put_try_threaded(), webdav_put_write_sync(), webdav_tpc_commit_pulled_file(), webdav_tpc_pull_marker_exec(), webdav_tpc_pull_sync_exec(), webdav_tpc_pull_thread_exec(), webdav_tpc_push_post_thread(), webdav_tpc_push_sync_error(), and webdav_tpc_push_sync_exec().
brix_dashboard_http_finish()
void brix_dashboard_http_finish (ngx_http_request_t * r)
Definition at line 473 of file http_tracking.c.
References brix_transfer_slot_free(), brix_transfer_slot_set_state(), BRIX_XFER_STATE_CLOSING, dashboard_http_track(), brix_dashboard_http_track_t::slot, and brix_dashboard_http_track_t::table.
Referenced by s3_put_finalize_bad_digest(), s3_put_finalize_client_error(), s3_put_finalize_codec_error(), s3_put_finalize_empty_ok(), s3_put_finalize_error(), s3_put_finalize_fs_error(), s3_put_finalize_invalid_request(), serve_send_memory_backed(), serve_send_sendfile(), serve_try_compressed(), tpc_marker_record_result(), tpc_thread_done(), webdav_put_aio_done(), webdav_put_commit(), webdav_put_select_codec(), webdav_put_try_threaded(), webdav_put_write_sync(), webdav_tpc_commit_pulled_file(), webdav_tpc_finish_pull_success(), webdav_tpc_pull_marker_exec(), webdav_tpc_pull_sync_exec(), webdav_tpc_pull_thread_exec(), webdav_tpc_push_post_thread(), webdav_tpc_push_sync_error(), and webdav_tpc_push_sync_exec().
brix_dashboard_http_start()
int brix_dashboard_http_start (ngx_http_request_t * r, const char * path, uint8_t proto, uint8_t direction, const char * op, int64_t expected_bytes)
Definition at line 234 of file http_tracking.c.
References brix_dashboard_http_start_identity(), and op.
brix_dashboard_http_start_identity()
int brix_dashboard_http_start_identity (ngx_http_request_t * r, const char * path, const char * identity, const char * vo, uint8_t proto, uint8_t direction, const char * op, int64_t expected_bytes)
Definition at line 199 of file http_tracking.c.
References dashboard_http_bind_slot(), dashboard_http_reserve_slot(), dashboard_http_track(), dashboard_shm_ready(), brix_dashboard_http_meta_t::direction, brix_dashboard_http_meta_t::expected_bytes, brix_dashboard_http_meta_t::identity, op, brix_dashboard_http_meta_t::op, brix_dashboard_http_meta_t::path, brix_dashboard_http_meta_t::proto, brix_dashboard_http_track_t::slot, and brix_dashboard_http_meta_t::vo.
Referenced by brix_dashboard_http_start(), brix_http_serve_file_ranged(), cvmfs_tier_get(), s3_put_try_sentinel(), s3put_stream_body(), serve_try_compressed(), webdav_put_start_dashboard(), webdav_tpc_handle_push(), and webdav_tpc_pull_start_accounting().
brix_dashboard_http_state()
void brix_dashboard_http_state (ngx_http_request_t * r, uint8_t state)
Definition at line 257 of file http_tracking.c.
References brix_transfer_slot_set_state(), dashboard_http_track(), brix_dashboard_http_track_t::slot, and brix_dashboard_http_track_t::table.
brix_dashboard_http_tpc_remote()
void brix_dashboard_http_tpc_remote (ngx_http_request_t * r, const char * remote_url, int remote_status, int curl_exit)
Definition at line 455 of file http_tracking.c.
References BRIX_DASHBOARD_HOST_LEN, BRIX_DASHBOARD_PATH_LEN, brix_transfer_slot_set_tpc_remote(), dashboard_http_track(), dashboard_redact_url(), brix_dashboard_http_track_t::slot, and brix_dashboard_http_track_t::table.
Referenced by webdav_tpc_handle_push(), and webdav_tpc_pull_start_accounting().