nginx-xrootd: src/observability/dashboard/dashboard.h File Reference
dashboard.h File Reference
#include <stdint.h>
#include <ngx_core.h>
#include "core/types/proto_list.h"
Data Structures
struct brix_transfer_slot_t
struct brix_transfer_table_t
struct brix_dashboard_event_t
struct brix_dashboard_event_table_t
struct brix_dashboard_history_bucket_t
struct brix_dashboard_history_t
Macros
#define BRIX_DASHBOARD_MAX_TRANSFERS 512
#define BRIX_DASHBOARD_PATH_LEN 512
#define BRIX_DASHBOARD_IDENTITY_LEN 128
#define BRIX_DASHBOARD_IP_LEN 64
#define BRIX_DASHBOARD_OP_LEN 32
#define BRIX_DASHBOARD_REASON_LEN 96
#define BRIX_DASHBOARD_HOST_LEN 128
#define BRIX_DASHBOARD_VO_LEN 32
#define X(ID, metric_label, dash_name, http_plane) BRIX_XFER_PROTO_##ID,
#define BRIX_XFER_NPROTOS (BRIX_XFER_PROTO__END - 1)
#define BRIX_XFER_DIR_READ 1 /* client downloading (egress) */
#define BRIX_XFER_DIR_WRITE 2 /* client uploading (ingress) */
#define BRIX_XFER_DIR_TPC 3 /* third-party copy (no client data) */
#define BRIX_XFER_STATE_ACTIVE 1
#define BRIX_XFER_STATE_IDLE 2
#define BRIX_XFER_STATE_STALLED 3
#define BRIX_XFER_STATE_CLOSING 4
#define BRIX_XFER_STATE_ERROR 5
#define BRIX_XFER_STATE_THROTTLED 6
#define BRIX_XFER_SAMPLE_MS 1000
#define BRIX_DASHBOARD_MAX_EVENTS 512
#define BRIX_DASHBOARD_EVENT_MSG_LEN 160
#define BRIX_DASHBOARD_HISTORY_BUCKETS 360
#define BRIX_DASHBOARD_HISTORY_INTERVAL_MS 5000
Enumerations
enum {
BRIX_XFER_PROTO_NONE = 0 , BRIX_XFER_PROTO_ROOT , BRIX_XFER_PROTO_WEBDAV , BRIX_XFER_PROTO_S3 ,
BRIX_XFER_PROTO_CVMFS , BRIX_XFER_PROTO__END
}
enum brix_dashboard_event_class_e {
BRIX_DASH_EVENT_AUTH = 1 , BRIX_DASH_EVENT_NAMESPACE , BRIX_DASH_EVENT_IO , BRIX_DASH_EVENT_TPC ,
BRIX_DASH_EVENT_DASHBOARD
}
Functions
ngx_int_t brix_configure_dashboard (ngx_conf_t *cf)
ngx_int_t ngx_brix_dashboard_shm_init (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t ngx_brix_dashboard_events_shm_init (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t ngx_brix_dashboard_history_shm_init (ngx_shm_zone_t *shm_zone, void *data)
int brix_transfer_slot_alloc (brix_transfer_table_t *t, const u_char sessid[16], const char *client_ip, const char *identity, const char *path, uint8_t direction, uint8_t proto, int64_t now_ms)
int brix_transfer_slot_alloc_ex (brix_transfer_table_t *t, const u_char sessid[16], const char *client_ip, const char *identity, const char *vo, const char *path, const char *op, uint8_t direction, uint8_t proto, int64_t expected_bytes, int64_t now_ms)
void brix_transfer_slot_update (brix_transfer_table_t *t, int slot_idx, ngx_atomic_int_t nbytes, int64_t now_ms)
void brix_transfer_slot_update_bytes (brix_transfer_table_t *t, int slot_idx, ngx_atomic_int_t nbytes, int64_t now_ms)
void brix_transfer_slot_set_state (brix_transfer_table_t *t, int slot_idx, uint8_t state, int64_t now_ms)
void brix_transfer_slot_set_error (brix_transfer_table_t *t, int slot_idx, const char *reason, int64_t now_ms)
void brix_transfer_slot_set_tpc_remote (brix_transfer_table_t *t, int slot_idx, const char *remote_host, const char *path_hint, int remote_status, int curl_exit)
void brix_transfer_slot_count_op (brix_transfer_table_t *t, int slot_idx, const char *op)
void brix_transfer_slot_free (brix_transfer_table_t *t, int slot_idx)
void brix_transfer_slot_free_all_for_session (brix_transfer_table_t *t, const u_char sessid[16])
void brix_dashboard_event_add (uint8_t class_id, uint8_t proto, uint16_t status, const char *message, const char *path_hint)
ngx_uint_t brix_dashboard_events_snapshot (brix_dashboard_event_t *out, ngx_uint_t max_events)
void brix_dashboard_history_sample (int64_t now_ms)
ngx_uint_t brix_dashboard_history_snapshot (brix_dashboard_history_bucket_t *out, ngx_uint_t max_buckets)
Variables
ngx_shm_zone_t * ngx_brix_dashboard_shm_zone
ngx_shm_zone_t * ngx_brix_dashboard_events_shm_zone
ngx_shm_zone_t * ngx_brix_dashboard_history_shm_zone
Macro Definition Documentation
BRIX_DASHBOARD_EVENT_MSG_LEN
#define BRIX_DASHBOARD_EVENT_MSG_LEN 160
Definition at line 89 of file dashboard.h.
BRIX_DASHBOARD_HISTORY_BUCKETS
#define BRIX_DASHBOARD_HISTORY_BUCKETS 360
Definition at line 90 of file dashboard.h.
BRIX_DASHBOARD_HISTORY_INTERVAL_MS
#define BRIX_DASHBOARD_HISTORY_INTERVAL_MS 5000
Definition at line 91 of file dashboard.h.
BRIX_DASHBOARD_HOST_LEN
#define BRIX_DASHBOARD_HOST_LEN 128
Definition at line 44 of file dashboard.h.
BRIX_DASHBOARD_IDENTITY_LEN
#define BRIX_DASHBOARD_IDENTITY_LEN 128
Definition at line 40 of file dashboard.h.
BRIX_DASHBOARD_IP_LEN
#define BRIX_DASHBOARD_IP_LEN 64
Definition at line 41 of file dashboard.h.
BRIX_DASHBOARD_MAX_EVENTS
#define BRIX_DASHBOARD_MAX_EVENTS 512
Definition at line 88 of file dashboard.h.
BRIX_DASHBOARD_MAX_TRANSFERS
#define BRIX_DASHBOARD_MAX_TRANSFERS 512
Definition at line 36 of file dashboard.h.
BRIX_DASHBOARD_OP_LEN
#define BRIX_DASHBOARD_OP_LEN 32
Definition at line 42 of file dashboard.h.
BRIX_DASHBOARD_PATH_LEN
#define BRIX_DASHBOARD_PATH_LEN 512
Definition at line 39 of file dashboard.h.
BRIX_DASHBOARD_REASON_LEN
#define BRIX_DASHBOARD_REASON_LEN 96
Definition at line 43 of file dashboard.h.
BRIX_DASHBOARD_VO_LEN
#define BRIX_DASHBOARD_VO_LEN 32
Definition at line 45 of file dashboard.h.
BRIX_XFER_DIR_READ
#define BRIX_XFER_DIR_READ 1 /* client downloading (egress) */
Definition at line 61 of file dashboard.h.
BRIX_XFER_DIR_TPC
#define BRIX_XFER_DIR_TPC 3 /* third-party copy (no client data) */
Definition at line 63 of file dashboard.h.
BRIX_XFER_DIR_WRITE
#define BRIX_XFER_DIR_WRITE 2 /* client uploading (ingress) */
Definition at line 62 of file dashboard.h.
BRIX_XFER_NPROTOS
#define BRIX_XFER_NPROTOS (BRIX_XFER_PROTO__END - 1)
Definition at line 58 of file dashboard.h.
BRIX_XFER_SAMPLE_MS
#define BRIX_XFER_SAMPLE_MS 1000
Definition at line 86 of file dashboard.h.
BRIX_XFER_STATE_ACTIVE
#define BRIX_XFER_STATE_ACTIVE 1
Definition at line 66 of file dashboard.h.
BRIX_XFER_STATE_CLOSING
#define BRIX_XFER_STATE_CLOSING 4
Definition at line 69 of file dashboard.h.
BRIX_XFER_STATE_ERROR
#define BRIX_XFER_STATE_ERROR 5
Definition at line 70 of file dashboard.h.
BRIX_XFER_STATE_IDLE
#define BRIX_XFER_STATE_IDLE 2
Definition at line 67 of file dashboard.h.
BRIX_XFER_STATE_STALLED
#define BRIX_XFER_STATE_STALLED 3
Definition at line 68 of file dashboard.h.
BRIX_XFER_STATE_THROTTLED
#define BRIX_XFER_STATE_THROTTLED 6
Definition at line 78 of file dashboard.h.
X
#define X (ID, metric_label, dash_name, http_plane) BRIX_XFER_PROTO_##ID,
Definition at line 53 of file dashboard.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BRIX_XFER_PROTO_NONE
BRIX_XFER_PROTO_ROOT
BRIX_XFER_PROTO_WEBDAV
BRIX_XFER_PROTO_S3
BRIX_XFER_PROTO_CVMFS
BRIX_XFER_PROTO__END
Definition at line 51 of file dashboard.h.
brix_dashboard_event_class_e
enum brix_dashboard_event_class_e
Enumerator
BRIX_DASH_EVENT_AUTH
BRIX_DASH_EVENT_NAMESPACE
BRIX_DASH_EVENT_IO
BRIX_DASH_EVENT_TPC
BRIX_DASH_EVENT_DASHBOARD
Definition at line 93 of file dashboard.h.
Function Documentation
brix_configure_dashboard()
ngx_int_t brix_configure_dashboard (ngx_conf_t * cf)
Definition at line 24 of file config.c.
brix_dashboard_event_add()
void brix_dashboard_event_add (uint8_t class_id, uint8_t proto, uint16_t status, const char * message, const char * path_hint)
Definition at line 109 of file events.c.
References brix_dashboard_events_mutex, BRIX_DASHBOARD_MAX_EVENTS, brix_dashboard_event_t::class_id, dashboard_event_copy(), dashboard_events_table(), brix_dashboard_event_table_t::events, brix_dashboard_event_t::message, brix_dashboard_event_table_t::next_sequence, brix_dashboard_event_t::path_hint, brix_dashboard_event_t::proto, brix_dashboard_event_t::sequence, brix_dashboard_event_t::status, and brix_dashboard_event_t::time_ms.
Referenced by admin_cluster_delete(), admin_cluster_drain(), admin_cluster_register(), admin_cluster_undrain(), admin_proxy_add(), brix_transfer_slot_alloc_ex(), brix_transfer_slot_set_error(), dash_auth_check_timestamp(), dash_auth_extract_hex(), dash_auth_resolve_key(), dash_auth_verify_hmac(), dashboard_build_transfer_rows(), login_issue_cookie(), login_verify_credentials(), ngx_http_brix_dashboard_api_handler(), and ngx_http_brix_dashboard_check_auth().
brix_dashboard_events_snapshot()
ngx_uint_t brix_dashboard_events_snapshot (brix_dashboard_event_t * out, ngx_uint_t max_events)
Definition at line 141 of file events.c.
References brix_dashboard_events_mutex, BRIX_DASHBOARD_MAX_EVENTS, dashboard_events_table(), brix_dashboard_event_table_t::events, brix_dashboard_event_table_t::next_sequence, and brix_dashboard_event_t::sequence.
Referenced by dashboard_build_events().
brix_dashboard_history_sample()
void brix_dashboard_history_sample (int64_t now_ms)
Definition at line 249 of file history.c.
References brix_dashboard_history_bucket_t::active, brix_dashboard_history_bucket_t::active_tpc, brix_dashboard_history_bucket_t::auth_failures, BRIX_DASHBOARD_HISTORY_INTERVAL_MS, brix_dashboard_history_mutex, BRIX_XFER_NPROTOS, brix_dashboard_history_bucket_t::bytes_rx, brix_dashboard_history_bucket_t::bytes_tx, brix_dashboard_history_bucket_t::cache_occupancy_ppm, dashboard_history_count_active(), dashboard_history_select_bucket(), dashboard_history_sum_totals(), dashboard_history_table(), dashboard_history_zero_fill_gap(), brix_dashboard_history_bucket_t::errors, brix_dashboard_history_t::last_bucket_start_ms, and brix_dashboard_history_bucket_t::write_stalls.
Referenced by ngx_http_brix_dashboard_api_handler().
brix_dashboard_history_snapshot()
ngx_uint_t brix_dashboard_history_snapshot (brix_dashboard_history_bucket_t * out, ngx_uint_t max_buckets)
Definition at line 298 of file history.c.
References BRIX_DASHBOARD_HISTORY_BUCKETS, BRIX_DASHBOARD_HISTORY_INTERVAL_MS, brix_dashboard_history_mutex, brix_dashboard_history_bucket_t::bucket_start_ms, brix_dashboard_history_t::buckets, dashboard_history_bucket_index(), dashboard_history_table(), and brix_dashboard_history_t::last_bucket_start_ms.
Referenced by dashboard_fill_history().
brix_transfer_slot_alloc()
int brix_transfer_slot_alloc (brix_transfer_table_t * t, const u_char sessid[16], const char * client_ip, const char * identity, const char * path, uint8_t direction, uint8_t proto, int64_t now_ms)
Definition at line 62 of file noop.c.
References brix_transfer_slot_alloc_ex().
Referenced by brix_open_register_monitor().
brix_transfer_slot_alloc_ex()
int brix_transfer_slot_alloc_ex (brix_transfer_table_t * t, const u_char sessid[16], const char * client_ip, const char * identity, const char * vo, const char * path, const char * op, uint8_t direction, uint8_t proto, int64_t expected_bytes, int64_t now_ms)
Definition at line 79 of file noop.c.
References BRIX_DASH_EVENT_DASHBOARD, brix_dashboard_event_add(), BRIX_DASHBOARD_MAX_TRANSFERS, brix_dashboard_mutex, BRIX_XFER_STATE_ACTIVE, brix_transfer_slot_t::client_ip, dashboard_copy_field(), brix_transfer_slot_t::direction, brix_transfer_slot_t::expected_bytes, brix_transfer_slot_t::identity, brix_transfer_slot_t::in_use, brix_transfer_slot_t::last_ms, brix_transfer_table_t::next_serial, ngx_memcpy, op, brix_transfer_slot_t::op, brix_transfer_slot_t::path, brix_transfer_slot_t::proto, brix_transfer_slot_t::serial, brix_transfer_slot_t::sessid, brix_transfer_table_t::slots, brix_transfer_slot_t::start_ms, brix_transfer_slot_t::state, brix_transfer_slot_t::state_since_ms, brix_transfer_slot_t::vo, and brix_transfer_slot_t::worker_pid.
Referenced by brix_transfer_slot_alloc(), and dashboard_http_reserve_slot().
brix_transfer_slot_count_op()
void brix_transfer_slot_count_op (brix_transfer_table_t * t, int slot_idx, const char * op)
Definition at line 153 of file noop.c.
References BRIX_DASHBOARD_MAX_TRANSFERS, brix_transfer_slot_t::close_ops, brix_transfer_slot_t::in_use, op, brix_transfer_slot_t::read_ops, brix_transfer_table_t::slots, brix_transfer_slot_t::sync_ops, and brix_transfer_slot_t::write_ops.
Referenced by brix_close_release_slots(), brix_compressed_account(), brix_handle_sync(), brix_read_serve_sendfile(), brix_staged_append(), brix_write_compressed(), brix_write_finalize_sync(), dashboard_http_bind_slot(), and read_finish_buffered().
brix_transfer_slot_free()
void brix_transfer_slot_free (brix_transfer_table_t * t, int slot_idx)
Definition at line 162 of file noop.c.
References BRIX_DASHBOARD_MAX_TRANSFERS, BRIX_XFER_STATE_CLOSING, brix_transfer_slot_t::in_use, brix_transfer_table_t::slots, brix_transfer_slot_t::state, and brix_transfer_slot_t::state_since_ms.
Referenced by brix_close_release_slots(), brix_dashboard_http_finish(), dashboard_build_transfer_rows(), dashboard_http_bind_slot(), and dashboard_http_cleanup().
brix_transfer_slot_free_all_for_session()
void brix_transfer_slot_free_all_for_session (brix_transfer_table_t * t, const u_char sessid[16])
Definition at line 169 of file noop.c.
References BRIX_DASHBOARD_MAX_TRANSFERS, brix_dashboard_mutex, brix_transfer_slot_t::in_use, brix_transfer_slot_t::sessid, and brix_transfer_table_t::slots.
Referenced by brix_on_disconnect().
brix_transfer_slot_set_error()
void brix_transfer_slot_set_error (brix_transfer_table_t * t, int slot_idx, const char * reason, int64_t now_ms)
Definition at line 130 of file noop.c.
References BRIX_DASH_EVENT_IO, brix_dashboard_event_add(), BRIX_DASHBOARD_MAX_TRANSFERS, BRIX_XFER_STATE_ERROR, dashboard_copy_field(), brix_transfer_slot_t::in_use, brix_transfer_slot_t::last_error, brix_transfer_slot_t::last_ms, brix_transfer_slot_t::path, brix_transfer_slot_t::proto, brix_transfer_table_t::slots, brix_transfer_slot_t::state, and brix_transfer_slot_t::state_since_ms.
Referenced by brix_dashboard_http_error().
brix_transfer_slot_set_state()
void brix_transfer_slot_set_state (brix_transfer_table_t * t, int slot_idx, uint8_t state, int64_t now_ms)
Definition at line 120 of file noop.c.
References BRIX_DASHBOARD_MAX_TRANSFERS, brix_transfer_slot_t::in_use, brix_transfer_slot_t::last_ms, brix_transfer_table_t::slots, brix_transfer_slot_t::state, and brix_transfer_slot_t::state_since_ms.
Referenced by brix_dashboard_http_finish(), and brix_dashboard_http_state().
brix_transfer_slot_set_tpc_remote()
void brix_transfer_slot_set_tpc_remote (brix_transfer_table_t * t, int slot_idx, const char * remote_host, const char * path_hint, int remote_status, int curl_exit)
Definition at line 140 of file noop.c.
References BRIX_DASHBOARD_MAX_TRANSFERS, dashboard_copy_field(), brix_transfer_slot_t::in_use, brix_transfer_table_t::slots, brix_transfer_slot_t::tpc_curl_exit, brix_transfer_slot_t::tpc_remote_host, brix_transfer_slot_t::tpc_remote_path_hint, and brix_transfer_slot_t::tpc_remote_status.
Referenced by brix_dashboard_http_tpc_remote().
brix_transfer_slot_update()
void brix_transfer_slot_update (brix_transfer_table_t * t, int slot_idx, ngx_atomic_int_t nbytes, int64_t now_ms)
Definition at line 100 of file noop.c.
References brix_transfer_slot_update_bytes().
Referenced by brix_compressed_account(), brix_read_serve_sendfile(), brix_staged_append(), brix_write_compressed(), brix_write_finalize_sync(), and read_finish_buffered().
brix_transfer_slot_update_bytes()
void brix_transfer_slot_update_bytes (brix_transfer_table_t * t, int slot_idx, ngx_atomic_int_t nbytes, int64_t now_ms)
Definition at line 110 of file noop.c.
References BRIX_DASHBOARD_MAX_TRANSFERS, BRIX_XFER_SAMPLE_MS, BRIX_XFER_STATE_ACTIVE, brix_transfer_slot_t::bytes, brix_transfer_slot_t::bytes_last_sample, brix_transfer_slot_t::in_use, brix_transfer_slot_t::instant_bps, brix_transfer_slot_t::last_ms, brix_transfer_slot_t::last_sample_ms, brix_transfer_table_t::slots, and brix_transfer_slot_t::state.
Referenced by brix_dashboard_http_add(), and brix_transfer_slot_update().
ngx_brix_dashboard_events_shm_init()
ngx_int_t ngx_brix_dashboard_events_shm_init (ngx_shm_zone_t * shm_zone, void * data)
Definition at line 82 of file events.c.
References brix_dashboard_events_mutex, and brix_shm_table_alloc().
Referenced by brix_configure_dashboard().
ngx_brix_dashboard_history_shm_init()
ngx_int_t ngx_brix_dashboard_history_shm_init (ngx_shm_zone_t * shm_zone, void * data)
Definition at line 60 of file history.c.
References brix_dashboard_history_mutex, and brix_shm_table_alloc().
Referenced by brix_configure_dashboard().
ngx_brix_dashboard_shm_init()
ngx_int_t ngx_brix_dashboard_shm_init (ngx_shm_zone_t * shm_zone, void * data)
Definition at line 38 of file noop.c.
References brix_dashboard_mutex, and brix_shm_table_alloc().
Referenced by brix_configure_dashboard().
Variable Documentation
ngx_brix_dashboard_events_shm_zone
ngx_shm_zone_t* ngx_brix_dashboard_events_shm_zone extern
Definition at line 20 of file config.c.
Referenced by brix_configure_dashboard(), and dashboard_events_table().
ngx_brix_dashboard_history_shm_zone
ngx_shm_zone_t* ngx_brix_dashboard_history_shm_zone extern
Definition at line 21 of file config.c.
Referenced by brix_configure_dashboard(), and dashboard_history_table().
ngx_brix_dashboard_shm_zone
ngx_shm_zone_t* ngx_brix_dashboard_shm_zone extern
Definition at line 19 of file config.c.
Referenced by brix_close_release_slots(), brix_compressed_account(), brix_configure_dashboard(), brix_handle_sync(), brix_on_disconnect(), brix_open_register_monitor(), brix_read_serve_sendfile(), brix_staged_append(), brix_write_compressed(), brix_write_finalize_sync(), dashboard_build_transfer_rows(), dashboard_build_v1_transfer_detail(), dashboard_collect_protocols(), dashboard_history_count_active(), dashboard_http_bind_slot(), dashboard_http_reserve_slot(), dashboard_shm_ready(), and read_finish_buffered().