nginx-xrootd: src/observability/dashboard/dashboard_auth_creds.c File Reference
dashboard_auth_creds.c File Reference
#include "dashboard_auth_internal.h"
#include "core/compat/alloc_guard.h"
#include <openssl/hmac.h>
#include <openssl/evp.h>
#include <openssl/crypto.h>
#include <stdio.h>
#include <string.h>
#include <crypt.h>
Functions
static void hmac_sha256_hex (const u_char *key, size_t key_len, const char *msg, size_t msg_len, char out_hex[64+1])
ngx_uint_t dashboard_users_enabled (const ngx_http_brix_dashboard_loc_conf_t *conf)
ngx_http_brix_dashboard_user_t * dashboard_find_user (const ngx_http_brix_dashboard_loc_conf_t *conf, const char *username, size_t username_len)
static ngx_int_t dashboard_copy_str0 (ngx_pool_t *pool, ngx_str_t *src, char **out)
ngx_int_t dashboard_verify_user_password (ngx_pool_t *pool, ngx_http_brix_dashboard_user_t *user, const char *password, size_t password_len)
ngx_int_t dashboard_cookie_hmac (const ngx_str_t *key, const char *ts, size_t ts_len, const char *username, size_t username_len, char out_hex[64+1])
Function Documentation
dashboard_cookie_hmac()
ngx_int_t dashboard_cookie_hmac (const ngx_str_t * key, const char * ts, size_t ts_len, const char * username, size_t username_len, char out_hex[64+1])
Definition at line 167 of file dashboard_auth_creds.c.
References hmac_sha256_hex(), key, ngx_memcpy, and TIMESTAMP_MAX.
Referenced by dash_auth_verify_hmac(), and login_issue_cookie().
dashboard_copy_str0()
static ngx_int_t dashboard_copy_str0 (ngx_pool_t * pool, ngx_str_t * src, char ** out) static
Definition at line 86 of file dashboard_auth_creds.c.
References BRIX_PNALLOC_OR_RETURN, and ngx_memcpy.
Referenced by dashboard_verify_user_password().
dashboard_find_user()
ngx_http_brix_dashboard_user_t * dashboard_find_user (const ngx_http_brix_dashboard_loc_conf_t * conf, const char * username, size_t username_len)
Definition at line 61 of file dashboard_auth_creds.c.
References dashboard_users_enabled(), and ngx_http_brix_dashboard_loc_conf_t::users.
Referenced by dash_auth_resolve_key(), and login_verify_credentials().
dashboard_users_enabled()
ngx_uint_t dashboard_users_enabled (const ngx_http_brix_dashboard_loc_conf_t * conf)
Definition at line 53 of file dashboard_auth_creds.c.
References ngx_http_brix_dashboard_loc_conf_t::users.
Referenced by dash_auth_resolve_key(), dashboard_find_user(), login_issue_cookie(), login_verify_credentials(), and ngx_http_brix_dashboard_check_auth().
dashboard_verify_user_password()
ngx_int_t dashboard_verify_user_password (ngx_pool_t * pool, ngx_http_brix_dashboard_user_t * user, const char * password, size_t password_len)
Definition at line 108 of file dashboard_auth_creds.c.
References BRIX_PNALLOC_OR_RETURN, dashboard_copy_str0(), ngx_memcpy, and ngx_http_brix_dashboard_user_t::password_hash.
Referenced by login_verify_credentials().
hmac_sha256_hex()
static void hmac_sha256_hex (const u_char * key, size_t key_len, const char * msg, size_t msg_len, char out_hex[64+1]) static
Definition at line 33 of file dashboard_auth_creds.c.
References HMAC_HEX_LEN, and key.
Referenced by dashboard_cookie_hmac().