nginx-xrootd: src/protocols/root/dirlist/dcksm.h File Reference
dcksm.h File Reference
#include "core/ngx_brix_module.h"
#include <sys/stat.h>
Functions
ngx_int_t brix_dirlist_checksum_algorithm (const u_char *payload, size_t payload_len, char *algo, size_t algo_sz, char *bad_algo, size_t bad_algo_sz)
void brix_dirlist_checksum_token (ngx_log_t *log, int dfd, const char *name, const char *path, const struct stat *st, const char *algo, char *out, size_t outsz)
void brix_dirlist_make_dcksm_stat_body (const struct stat *st, char *out, size_t outsz)
Function Documentation
brix_dirlist_checksum_algorithm()
ngx_int_t brix_dirlist_checksum_algorithm (const u_char * payload, size_t payload_len, char * algo, size_t algo_sz, char * bad_algo, size_t bad_algo_sz)
Definition at line 42 of file dcksm.c.
References brix_dirlist_parse_algorithm(), key, and ngx_memcpy.
Referenced by brix_dirlist_parse_request().
brix_dirlist_checksum_token()
void brix_dirlist_checksum_token (ngx_log_t * log, int dfd, const char * name, const char * path, const struct stat * st, const char * algo, char * out, size_t outsz)
Definition at line 114 of file dcksm.c.
References brix_integrity_info_t::alg_name, brix_integrity_opts_t::allow_xattr_cache, brix_integrity_get_fd(), close(), brix_integrity_info_t::hex, log, name, openat(), and brix_integrity_opts_t::update_xattr_cache.
Referenced by brix_dirlist_entry_meta(), and brix_vfs_io_dirlist_stat_entry().
brix_dirlist_make_dcksm_stat_body()
void brix_dirlist_make_dcksm_stat_body (const struct stat * st, char * out, size_t outsz)
Definition at line 156 of file dcksm.c.
References kXR_isDir, kXR_other, kXR_readable, kXR_writable, and kXR_xset.
Referenced by brix_dirlist_entry_meta(), and brix_vfs_io_dirlist_stat_entry().