nginx-xrootd: src/protocols/webdav/dead_props_internal.h File Reference
dead_props_internal.h File Reference
#include "webdav.h"
Macros
#define ENOATTR ENODATA
#define WEBDAV_DEAD_PROP_PREFIX "user.nginx_xrootd.webdav."
#define WEBDAV_DEAD_PROP_PREFIX_LEN (sizeof(WEBDAV_DEAD_PROP_PREFIX) - 1)
#define WEBDAV_DEAD_PROP_NAME_MAX 255
#define WEBDAV_DEAD_PROP_VALUE_MAX 16384
#define WEBDAV_DEAD_PROP_LIST_MAX 65536
Functions
ngx_flag_t webdav_dead_prop_xml_name_ok (const char *name)
ngx_int_t webdav_dead_prop_attr_name (const char *ns, const char *local, char *out, size_t outsz)
ngx_int_t webdav_dead_prop_decode_attr (ngx_pool_t *pool, const char *attr, char **ns_out, char **local_out)
Macro Definition Documentation
ENOATTR
#define ENOATTR ENODATA
Definition at line 17 of file dead_props_internal.h.
WEBDAV_DEAD_PROP_LIST_MAX
#define WEBDAV_DEAD_PROP_LIST_MAX 65536
Definition at line 34 of file dead_props_internal.h.
WEBDAV_DEAD_PROP_NAME_MAX
#define WEBDAV_DEAD_PROP_NAME_MAX 255
Definition at line 32 of file dead_props_internal.h.
WEBDAV_DEAD_PROP_PREFIX
#define WEBDAV_DEAD_PROP_PREFIX "user.nginx_xrootd.webdav."
Definition at line 30 of file dead_props_internal.h.
WEBDAV_DEAD_PROP_PREFIX_LEN
#define WEBDAV_DEAD_PROP_PREFIX_LEN (sizeof(WEBDAV_DEAD_PROP_PREFIX) - 1)
Definition at line 31 of file dead_props_internal.h.
WEBDAV_DEAD_PROP_VALUE_MAX
#define WEBDAV_DEAD_PROP_VALUE_MAX 16384
Definition at line 33 of file dead_props_internal.h.
Function Documentation
webdav_dead_prop_attr_name()
ngx_int_t webdav_dead_prop_attr_name (const char * ns, const char * local, char * out, size_t outsz)
Definition at line 92 of file dead_props_keys.c.
References hex(), ngx_memcpy, WEBDAV_DEAD_PROP_PREFIX, and WEBDAV_DEAD_PROP_PREFIX_LEN.
Referenced by webdav_dead_prop_read_value(), webdav_dead_prop_remove(), and webdav_dead_prop_set_target().
webdav_dead_prop_decode_attr()
ngx_int_t webdav_dead_prop_decode_attr (ngx_pool_t * pool, const char * attr, char ** ns_out, char ** local_out)
Definition at line 180 of file dead_props_keys.c.
References webdav_dead_prop_decode_hex(), WEBDAV_DEAD_PROP_PREFIX, WEBDAV_DEAD_PROP_PREFIX_LEN, and webdav_dead_prop_xml_name_ok().
Referenced by webdav_dead_props_append_all().
webdav_dead_prop_xml_name_ok()
ngx_flag_t webdav_dead_prop_xml_name_ok (const char * name)
Definition at line 63 of file dead_props_keys.c.
References name, webdav_xml_name_char(), and webdav_xml_name_start_char().
Referenced by webdav_dead_prop_append_empty(), and webdav_dead_prop_decode_attr().