nginx-xrootd: src/protocols/webdav/dead_props.c File Reference
dead_props.c File Reference
#include "webdav.h"
#include "fs/path/path.h"
#include "fs/vfs/vfs.h"
#include "core/http/http_xml.h"
#include "core/compat/namespace_ops.h"
#include <errno.h>
#include <string.h>
#include <sys/xattr.h>
#include "core/compat/alloc_guard.h"
Macros
#define ENOATTR ENODATA
#define WEBDAV_DEAD_PROP_PREFIX "user.nginx_xrootd.webdav."
#define WEBDAV_DEAD_PROP_PREFIX_LEN (sizeof(WEBDAV_DEAD_PROP_PREFIX) - 1)
#define WEBDAV_DEAD_PROP_NAME_MAX 255
#define WEBDAV_DEAD_PROP_VALUE_MAX 16384
#define WEBDAV_DEAD_PROP_LIST_MAX 65536
Functions
static void webdav_dead_prop_vfs_ctx_init (ngx_http_request_t *r, const char *path, brix_vfs_ctx_t *vctx)
static int webdav_dead_prop_hexval (char c)
static ngx_flag_t webdav_dead_prop_xml_name_ok (const char *name)
static ngx_int_t webdav_dead_prop_attr_name (const char *ns, const char *local, char *out, size_t outsz)
static char * webdav_dead_prop_decode_hex (ngx_pool_t *pool, const char *hex, size_t len)
static ngx_int_t webdav_dead_prop_decode_attr (ngx_pool_t *pool, const char *attr, char **ns_out, char **local_out)
ngx_flag_t webdav_dead_prop_is_protected_dav (const char *local)
ngx_int_t webdav_dead_prop_append_empty (ngx_http_request_t *r, const char *ns, const char *local, ngx_chain_t **head, ngx_chain_t **tail)
ngx_int_t webdav_dead_prop_set (ngx_http_request_t *r, const char *path, const char *ns, const char *local, const char *xml, size_t xml_len)
ngx_int_t webdav_dead_prop_remove (ngx_http_request_t *r, const char *path, const char *ns, const char *local)
ngx_int_t webdav_dead_prop_append_value (ngx_http_request_t *r, const char *path, const char *ns, const char *local, ngx_chain_t **head, ngx_chain_t **tail, ngx_flag_t *found)
ngx_int_t webdav_dead_props_append_all (ngx_http_request_t *r, const char *path, ngx_chain_t **head, ngx_chain_t **tail, ngx_flag_t names_only)
void webdav_dead_props_copy (ngx_log_t *log, const char *src, const char *dst)
Macro Definition Documentation
ENOATTR
#define ENOATTR ENODATA
Definition at line 56 of file dead_props.c.
WEBDAV_DEAD_PROP_LIST_MAX
#define WEBDAV_DEAD_PROP_LIST_MAX 65536
Definition at line 73 of file dead_props.c.
WEBDAV_DEAD_PROP_NAME_MAX
#define WEBDAV_DEAD_PROP_NAME_MAX 255
Definition at line 71 of file dead_props.c.
WEBDAV_DEAD_PROP_PREFIX
#define WEBDAV_DEAD_PROP_PREFIX "user.nginx_xrootd.webdav."
Definition at line 69 of file dead_props.c.
WEBDAV_DEAD_PROP_PREFIX_LEN
#define WEBDAV_DEAD_PROP_PREFIX_LEN (sizeof(WEBDAV_DEAD_PROP_PREFIX) - 1)
Definition at line 70 of file dead_props.c.
WEBDAV_DEAD_PROP_VALUE_MAX
#define WEBDAV_DEAD_PROP_VALUE_MAX 16384
Definition at line 72 of file dead_props.c.
Function Documentation
webdav_dead_prop_append_empty()
ngx_int_t webdav_dead_prop_append_empty (ngx_http_request_t * r, const char * ns, const char * local, ngx_chain_t ** head, ngx_chain_t ** tail)
Definition at line 275 of file dead_props.c.
References brix_http_chain_appendf(), webdav_dead_prop_xml_name_ok(), and webdav_escape_xml_text().
Referenced by webdav_dead_props_append_all(), and webdav_proppatch_append_propstat().
webdav_dead_prop_append_value()
ngx_int_t webdav_dead_prop_append_value (ngx_http_request_t * r, const char * path, const char * ns, const char * local, ngx_chain_t ** head, ngx_chain_t ** tail, ngx_flag_t * found)
Definition at line 380 of file dead_props.c.
References brix_http_chain_appendf(), BRIX_PNALLOC_OR_RETURN, brix_vfs_getxattr(), ENOATTR, webdav_dead_prop_attr_name(), WEBDAV_DEAD_PROP_NAME_MAX, WEBDAV_DEAD_PROP_VALUE_MAX, and webdav_dead_prop_vfs_ctx_init().
Referenced by propfind_entry(), and webdav_dead_props_append_all().
webdav_dead_prop_attr_name()
static ngx_int_t webdav_dead_prop_attr_name (const char * ns, const char * local, char * out, size_t outsz) static
Definition at line 134 of file dead_props.c.
References hex(), WEBDAV_DEAD_PROP_PREFIX, and WEBDAV_DEAD_PROP_PREFIX_LEN.
Referenced by webdav_dead_prop_append_value(), webdav_dead_prop_remove(), and webdav_dead_prop_set().
webdav_dead_prop_decode_attr()
static ngx_int_t webdav_dead_prop_decode_attr (ngx_pool_t * pool, const char * attr, char ** ns_out, char ** local_out) static
Definition at line 222 of file dead_props.c.
References webdav_dead_prop_decode_hex(), WEBDAV_DEAD_PROP_PREFIX, WEBDAV_DEAD_PROP_PREFIX_LEN, and webdav_dead_prop_xml_name_ok().
Referenced by webdav_dead_props_append_all().
webdav_dead_prop_decode_hex()
static char * webdav_dead_prop_decode_hex (ngx_pool_t * pool, const char * hex, size_t len) static
Definition at line 192 of file dead_props.c.
References BRIX_PNALLOC_OR_RETURN, hex(), and webdav_dead_prop_hexval().
Referenced by webdav_dead_prop_decode_attr().
webdav_dead_prop_hexval()
static int webdav_dead_prop_hexval (char c) static
Definition at line 77 of file dead_props.c.
References c.
Referenced by webdav_dead_prop_decode_hex().
webdav_dead_prop_is_protected_dav()
ngx_flag_t webdav_dead_prop_is_protected_dav (const char * local)
Definition at line 261 of file dead_props.c.
Referenced by webdav_proppatch_do().
webdav_dead_prop_remove()
ngx_int_t webdav_dead_prop_remove (ngx_http_request_t * r, const char * path, const char * ns, const char * local)
Definition at line 344 of file dead_props.c.
References brix_vfs_removexattr(), ENOATTR, webdav_dead_prop_attr_name(), WEBDAV_DEAD_PROP_NAME_MAX, and webdav_dead_prop_vfs_ctx_init().
Referenced by webdav_proppatch_do().
webdav_dead_prop_set()
ngx_int_t webdav_dead_prop_set (ngx_http_request_t * r, const char * path, const char * ns, const char * local, const char * xml, size_t xml_len)
Definition at line 314 of file dead_props.c.
References brix_vfs_setxattr(), webdav_dead_prop_attr_name(), WEBDAV_DEAD_PROP_NAME_MAX, WEBDAV_DEAD_PROP_VALUE_MAX, and webdav_dead_prop_vfs_ctx_init().
Referenced by webdav_proppatch_do().
webdav_dead_prop_vfs_ctx_init()
static void webdav_dead_prop_vfs_ctx_init (ngx_http_request_t * r, const char * path, brix_vfs_ctx_t * vctx) static
Definition at line 36 of file dead_props.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_WEBDAV, brix_vfs_ctx_init(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, brix_vfs_ctx_t::pool, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by webdav_dead_prop_append_value(), webdav_dead_prop_remove(), webdav_dead_prop_set(), and webdav_dead_props_append_all().
webdav_dead_prop_xml_name_ok()
static ngx_flag_t webdav_dead_prop_xml_name_ok (const char * name) static
Definition at line 99 of file dead_props.c.
References name.
Referenced by webdav_dead_prop_append_empty(), and webdav_dead_prop_decode_attr().
webdav_dead_props_append_all()
ngx_int_t webdav_dead_props_append_all (ngx_http_request_t * r, const char * path, ngx_chain_t ** head, ngx_chain_t ** tail, ngx_flag_t names_only)
Definition at line 436 of file dead_props.c.
References BRIX_PNALLOC_OR_RETURN, brix_vfs_listxattr(), webdav_dead_prop_append_empty(), webdav_dead_prop_append_value(), webdav_dead_prop_decode_attr(), WEBDAV_DEAD_PROP_LIST_MAX, and webdav_dead_prop_vfs_ctx_init().
Referenced by propfind_entry().
webdav_dead_props_copy()
void webdav_dead_props_copy (ngx_log_t * log, const char * src, const char * dst)
Definition at line 498 of file dead_props.c.
References brix_xattr_copy_by_prefix(), log, WEBDAV_DEAD_PROP_PREFIX, WEBDAV_DEAD_PROP_PREFIX_LEN, and WEBDAV_DEAD_PROP_VALUE_MAX.
Referenced by webdav_copy_collection_execute(), webdav_copy_meta_cb(), and webdav_handle_copy().