nginx-xrootd: src/protocols/webdav/dead_props_keys.c File Reference
dead_props_keys.c File Reference
#include "webdav.h"
#include "fs/path/path.h"
#include "fs/vfs/vfs.h"
#include "core/http/http_xml.h"
#include "core/compat/hex.h"
#include "core/compat/namespace_ops.h"
#include <errno.h>
#include <string.h>
#include <sys/xattr.h>
#include "core/compat/alloc_guard.h"
#include "dead_props_internal.h"
Functions
static ngx_flag_t webdav_xml_name_start_char (unsigned char c)
static ngx_flag_t webdav_xml_name_char (unsigned char c)
ngx_flag_t webdav_dead_prop_xml_name_ok (const char *name)
ngx_int_t webdav_dead_prop_attr_name (const char *ns, const char *local, char *out, size_t outsz)
static char * webdav_dead_prop_decode_hex (ngx_pool_t *pool, const char *hex, size_t len)
ngx_int_t webdav_dead_prop_decode_attr (ngx_pool_t *pool, const char *attr, char **ns_out, char **local_out)
Function Documentation
webdav_dead_prop_attr_name()
ngx_int_t webdav_dead_prop_attr_name (const char * ns, const char * local, char * out, size_t outsz)
Definition at line 92 of file dead_props_keys.c.
References hex(), ngx_memcpy, WEBDAV_DEAD_PROP_PREFIX, and WEBDAV_DEAD_PROP_PREFIX_LEN.
Referenced by webdav_dead_prop_read_value(), webdav_dead_prop_remove(), and webdav_dead_prop_set_target().
webdav_dead_prop_decode_attr()
ngx_int_t webdav_dead_prop_decode_attr (ngx_pool_t * pool, const char * attr, char ** ns_out, char ** local_out)
Definition at line 180 of file dead_props_keys.c.
References webdav_dead_prop_decode_hex(), WEBDAV_DEAD_PROP_PREFIX, WEBDAV_DEAD_PROP_PREFIX_LEN, and webdav_dead_prop_xml_name_ok().
Referenced by webdav_dead_props_append_all().
webdav_dead_prop_decode_hex()
static char * webdav_dead_prop_decode_hex (ngx_pool_t * pool, const char * hex, size_t len) static
Definition at line 150 of file dead_props_keys.c.
References brix_hex_from_char(), BRIX_PNALLOC_OR_RETURN, and hex().
Referenced by webdav_dead_prop_decode_attr().
webdav_dead_prop_xml_name_ok()
ngx_flag_t webdav_dead_prop_xml_name_ok (const char * name)
Definition at line 63 of file dead_props_keys.c.
References name, webdav_xml_name_char(), and webdav_xml_name_start_char().
Referenced by webdav_dead_prop_append_empty(), and webdav_dead_prop_decode_attr().
webdav_xml_name_char()
static ngx_flag_t webdav_xml_name_char (unsigned char c) static
Definition at line 49 of file dead_props_keys.c.
References c, and webdav_xml_name_start_char().
Referenced by webdav_dead_prop_xml_name_ok().
webdav_xml_name_start_char()
static ngx_flag_t webdav_xml_name_start_char (unsigned char c) static
Definition at line 36 of file dead_props_keys.c.
References c.
Referenced by webdav_dead_prop_xml_name_ok(), and webdav_xml_name_char().