nginx-xrootd: src/protocols/root/connection/deadline.h File Reference
deadline.h File Reference
#include <ngx_core.h>
#include <ngx_event.h>
#include "core/types/context.h"
#include "core/types/state.h"
Functions
static void brix_arm_read_deadline (ngx_connection_t *c, brix_ctx_t *ctx)
static void brix_disarm_read_deadline (ngx_connection_t *c, brix_ctx_t *ctx)
static void brix_arm_send_deadline (ngx_connection_t *c, brix_ctx_t *ctx)
static void brix_disarm_send_deadline (ngx_connection_t *c, brix_ctx_t *ctx)
Function Documentation
brix_arm_read_deadline()
static void brix_arm_read_deadline (ngx_connection_t * c, brix_ctx_t * ctx) inline static
Definition at line 50 of file deadline.h.
References brix_ctx_login_t::auth_done, c, brix_ctx_t::deadline, brix_ctx_deadline_t::handshake_ms, brix_ctx_recv_t::hdr_pos, brix_ctx_t::login, brix_ctx_deadline_t::read_armed, brix_ctx_deadline_t::read_ms, brix_ctx_t::recv, brix_ctx_t::state, and XRD_ST_REQ_HEADER.
Referenced by brix_recv_read_frame().
brix_arm_send_deadline()
static void brix_arm_send_deadline (ngx_connection_t * c, brix_ctx_t * ctx) inline static
Definition at line 104 of file deadline.h.
References c, brix_ctx_t::deadline, brix_ctx_deadline_t::send_armed, and brix_ctx_deadline_t::send_ms.
Referenced by brix_ensure_write_event(), and brix_schedule_write_resume().
brix_disarm_read_deadline()
static void brix_disarm_read_deadline (ngx_connection_t * c, brix_ctx_t * ctx) inline static
Definition at line 78 of file deadline.h.
References c, brix_ctx_t::deadline, and brix_ctx_deadline_t::read_armed.
Referenced by ngx_stream_brix_recv().
brix_disarm_send_deadline()
static void brix_disarm_send_deadline (ngx_connection_t * c, brix_ctx_t * ctx) inline static
Definition at line 114 of file deadline.h.
References c, brix_ctx_t::deadline, and brix_ctx_deadline_t::send_armed.
Referenced by brix_flush_pending().