nginx-xrootd: src/observability/pmark/defsfile.c File Reference
defsfile.c File Reference
#include "pmark.h"
#include <jansson.h>
#include <unistd.h>
Functions
static ngx_int_t pmark_dup_json_str (ngx_pool_t *pool, json_t *js, ngx_str_t *out)
ngx_int_t brix_pmark_defsfile_load (const char *path, ngx_pool_t *pool, ngx_array_t **out, ngx_log_t *log)
ngx_uint_t brix_pmark_defs_exp_id (ngx_array_t *defs, ngx_str_t *name)
ngx_uint_t brix_pmark_defs_act_id (ngx_array_t *defs, ngx_uint_t exp_id, ngx_str_t *name)
Function Documentation
brix_pmark_defs_act_id()
ngx_uint_t brix_pmark_defs_act_id (ngx_array_t * defs, ngx_uint_t exp_id, ngx_str_t * name)
Definition at line 175 of file defsfile.c.
References brix_pmark_exp_def_t::activities, brix_pmark_named_t::id, and name.
Referenced by brix_pmark_runtime_ensure().
brix_pmark_defs_exp_id()
ngx_uint_t brix_pmark_defs_exp_id (ngx_array_t * defs, ngx_str_t * name)
Definition at line 154 of file defsfile.c.
References brix_pmark_exp_def_t::exp_id, and name.
Referenced by brix_pmark_runtime_ensure().
brix_pmark_defsfile_load()
ngx_int_t brix_pmark_defsfile_load (const char * path, ngx_pool_t * pool, ngx_array_t ** out, ngx_log_t * log)
Definition at line 51 of file defsfile.c.
References access(), brix_pmark_exp_def_t::activities, brix_pmark_exp_def_t::exp_id, brix_pmark_exp_def_t::exp_name, brix_pmark_named_t::id, log, brix_pmark_named_t::name, and pmark_dup_json_str().
Referenced by brix_pmark_runtime_ensure().
pmark_dup_json_str()
static ngx_int_t pmark_dup_json_str (ngx_pool_t * pool, json_t * js, ngx_str_t * out) static
Definition at line 28 of file defsfile.c.
References ngx_memcpy, ngx_pnalloc(), and s.
Referenced by brix_pmark_defsfile_load().