nginx-xrootd: src/protocols/root/fattr/del.c File Reference
del.c File Reference
#include "ngx_brix_fattr.h"
#include <errno.h>
#include <sys/types.h>
#include <arpa/inet.h>
Functions
ngx_int_t fattr_del (brix_ctx_t *ctx, ngx_connection_t *c, brix_vfs_ctx_t *vctx, const char *path, int fd, u_char *nvec_copy, size_t nvec_len, int numattr, brix_fattr_entry_t *attrs)
Function Documentation
fattr_del()
ngx_int_t fattr_del (brix_ctx_t * ctx, ngx_connection_t * c, brix_vfs_ctx_t * vctx, const char * path, int fd, u_char * nvec_copy, size_t nvec_len, int numattr, brix_fattr_entry_t * attrs)
Definition at line 13 of file del.c.
References brix_vfs_fremovexattr(), brix_vfs_removexattr(), c, fattr_errno_to_xrd(), fattr_send_vector_status(), and fattr_set_rc().
Referenced by brix_handle_fattr().