nginx-xrootd: src/protocols/webdav/delegation_gridsite_req.c File Reference
delegation_gridsite_req.c File Reference
#include "webdav.h"
#include "delegation.h"
#include "delegation_internal.h"
#include "auth/gsi/proxy_req.h"
#include <openssl/bio.h>
#include <openssl/pem.h>
#include <openssl/ssl.h>
#include <openssl/x509.h>
#include <stdlib.h>
#include <string.h>
Functions
static ngx_int_t delegation_get_peer_pem (ngx_http_request_t *r, u_char **pem, size_t *pem_len)
static u_char * delegation_req_der_to_pem (const uint8_t *der, size_t der_len, size_t *pem_len)
static ngx_int_t delegation_send_csr (ngx_http_request_t *r, const char *id, const u_char *pem, size_t pem_len)
static ngx_int_t delegation_request_reject (ngx_http_request_t *r, ngx_uint_t status, const char *msg)
ngx_int_t webdav_delegation_request_handle (ngx_http_request_t *r)
Function Documentation
delegation_get_peer_pem()
static ngx_int_t delegation_get_peer_pem (ngx_http_request_t * r, u_char ** pem, size_t * pem_len) static
Definition at line 125 of file delegation_gridsite_req.c.
References pem_len.
Referenced by webdav_delegation_request_handle().
delegation_req_der_to_pem()
static u_char * delegation_req_der_to_pem (const uint8_t * der, size_t der_len, size_t * pem_len) static
Definition at line 173 of file delegation_gridsite_req.c.
References pem_len.
Referenced by webdav_delegation_request_handle().
delegation_request_reject()
static ngx_int_t delegation_request_reject (ngx_http_request_t * r, ngx_uint_t status, const char * msg) static
Definition at line 280 of file delegation_gridsite_req.c.
References ngx_memcpy, ngx_pcalloc(), and ngx_pnalloc().
Referenced by webdav_delegation_request_handle().
delegation_send_csr()
static ngx_int_t delegation_send_csr (ngx_http_request_t * r, const char * id, const u_char * pem, size_t pem_len) static
Definition at line 218 of file delegation_gridsite_req.c.
References ngx_memcpy, ngx_pcalloc(), ngx_pnalloc(), and pem_len.
Referenced by webdav_delegation_request_handle().
webdav_delegation_request_handle()
ngx_int_t webdav_delegation_request_handle (ngx_http_request_t * r)
Definition at line 317 of file delegation_gridsite_req.c.
References BRIX_DELEG_ID_HEXLEN, brix_deleg_store(), brix_deleg_store_put(), brix_gsi_build_pxyreq(), brix_gsi_buf_t::data, delegation_client_authenticated(), delegation_get_peer_pem(), delegation_req_der_to_pem(), delegation_request_reject(), delegation_send_csr(), ngx_http_brix_webdav_req_ctx_t::dn, brix_gsi_buf_t::len, and ngx_http_brix_webdav_module.
Referenced by webdav_dispatch_delegation_gridsite().