nginx-xrootd: src/protocols/webdav/delegation_store.c File Reference
delegation_store.c File Reference
#include "webdav.h"
#include "delegation_internal.h"
#include "core/compat/hex.h"
#include <openssl/evp.h>
#include <openssl/rand.h>
#include <string.h>
#include <time.h>
Data Structures
struct brix_deleg_entry_t
struct brix_deleg_store_t
Macros
#define BRIX_DELEG_STORE_CAP 256
#define BRIX_DELEG_TTL_SEC 600
Functions
brix_deleg_store_t * brix_deleg_store (void)
static void brix_deleg_entry_free (brix_deleg_entry_t *e)
static void brix_deleg_store_sweep (brix_deleg_store_t *st, time_t now)
ngx_int_t brix_deleg_store_put (brix_deleg_store_t *st, EVP_PKEY *fresh_key, const char *client_dn, char *id_out, size_t id_out_cap)
brix_deleg_take_t brix_deleg_store_take (brix_deleg_store_t *st, const char *id, const char *want_dn, EVP_PKEY **key_out)
Variables
static brix_deleg_store_t * brix_deleg_store_singleton = NULL
Macro Definition Documentation
BRIX_DELEG_STORE_CAP
#define BRIX_DELEG_STORE_CAP 256
Definition at line 53 of file delegation_store.c.
BRIX_DELEG_TTL_SEC
#define BRIX_DELEG_TTL_SEC 600
Definition at line 58 of file delegation_store.c.
Function Documentation
brix_deleg_entry_free()
static void brix_deleg_entry_free (brix_deleg_entry_t * e) static
Definition at line 94 of file delegation_store.c.
References brix_deleg_entry_t::client_dn, brix_deleg_entry_t::created_at, brix_deleg_entry_t::expires_at, brix_deleg_entry_t::fresh_key, and brix_deleg_entry_t::id.
Referenced by brix_deleg_store_sweep(), and brix_deleg_store_take().
brix_deleg_store()
brix_deleg_store_t * brix_deleg_store (void)
Definition at line 78 of file delegation_store.c.
References brix_deleg_store_singleton, and ngx_pcalloc().
Referenced by delegation_put_take_key(), and webdav_delegation_request_handle().
brix_deleg_store_put()
ngx_int_t brix_deleg_store_put (brix_deleg_store_t * st, EVP_PKEY * fresh_key, const char * client_dn, char * id_out, size_t id_out_cap)
Definition at line 146 of file delegation_store.c.
References BRIX_DELEG_ID_BYTES, BRIX_DELEG_ID_HEXLEN, BRIX_DELEG_STORE_CAP, brix_deleg_store_sweep(), BRIX_DELEG_TTL_SEC, brix_hex_encode(), hex(), and ngx_memcpy.
Referenced by webdav_delegation_request_handle().
brix_deleg_store_sweep()
static void brix_deleg_store_sweep (brix_deleg_store_t * st, time_t now) static
Definition at line 113 of file delegation_store.c.
References brix_deleg_entry_free(), and BRIX_DELEG_STORE_CAP.
Referenced by brix_deleg_store_put(), and brix_deleg_store_take().
brix_deleg_store_take()
brix_deleg_take_t brix_deleg_store_take (brix_deleg_store_t * st, const char * id, const char * want_dn, EVP_PKEY ** key_out)
Definition at line 217 of file delegation_store.c.
References brix_deleg_entry_free(), BRIX_DELEG_STORE_CAP, brix_deleg_store_sweep(), BRIX_DELEG_TAKE_DN_MISMATCH, BRIX_DELEG_TAKE_EXPIRED, BRIX_DELEG_TAKE_NOT_FOUND, BRIX_DELEG_TAKE_OK, brix_deleg_entry_t::client_dn, brix_deleg_entry_t::expires_at, brix_deleg_entry_t::fresh_key, and brix_deleg_entry_t::id.
Referenced by delegation_put_take_key().
Variable Documentation
brix_deleg_store_singleton
brix_deleg_store_t* brix_deleg_store_singleton = NULL static
Definition at line 75 of file delegation_store.c.
Referenced by brix_deleg_store().