nginx-xrootd: src/protocols/webdav/delegation_gridsite_put.c File Reference
delegation_gridsite_put.c File Reference
#include "webdav.h"
#include "delegation.h"
#include "delegation_internal.h"
#include "fs/backend/ucred.h"
#include "auth/gsi/proxy_req.h"
#include "core/compat/log_diag.h"
#include "core/http/http_body.h"
#include <openssl/bio.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
#include <stdlib.h>
#include <string.h>
Functions
static u_char * gsi_pem_export_one (X509 *cert, size_t *len)
static u_char * gsi_pem_export_chain (STACK_OF(X509) *chain, size_t *len)
static ngx_int_t delegation_split_first_pem_block (const u_char *body, size_t body_len, u_char **proxy_pem, size_t *proxy_pem_len, u_char **chain_pem, size_t *chain_pem_len)
static ngx_int_t delegation_extract_id (ngx_http_request_t *r, const u_char **id, size_t *id_len)
static ngx_int_t delegation_put_take_key (ngx_http_request_t *r, const ngx_http_brix_webdav_req_ctx_t *ctx, const char *id, EVP_PKEY **reqkey)
static ngx_int_t delegation_put_assemble (ngx_http_request_t *r, const char *id, EVP_PKEY *reqkey, const u_char *body, size_t body_len, uint8_t **out_pem, size_t *out_len)
static ngx_int_t delegation_put_validate_chain (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const ngx_http_brix_webdav_req_ctx_t *ctx, const char *id, const uint8_t *out_pem, size_t out_len)
static ngx_int_t delegation_put_store (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const ngx_http_brix_webdav_req_ctx_t *ctx, const uint8_t *out_pem, size_t out_len, char *key, size_t key_len)
void webdav_delegation_put_handle (ngx_http_request_t *r)
Function Documentation
delegation_extract_id()
static ngx_int_t delegation_extract_id (ngx_http_request_t * r, const u_char ** id, size_t * id_len) static
Definition at line 163 of file delegation_gridsite_put.c.
References BRIX_DELEG_ID_HEXLEN.
Referenced by webdav_delegation_put_handle().
delegation_put_assemble()
static ngx_int_t delegation_put_assemble (ngx_http_request_t * r, const char * id, EVP_PKEY * reqkey, const u_char * body, size_t body_len, uint8_t ** out_pem, size_t * out_len) static
Definition at line 230 of file delegation_gridsite_put.c.
References brix_gsi_assemble_proxy(), brix_gsi_buf_t::data, delegation_reject(), delegation_split_first_pem_block(), and brix_gsi_buf_t::len.
Referenced by webdav_delegation_put_handle().
delegation_put_store()
static ngx_int_t delegation_put_store (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const ngx_http_brix_webdav_req_ctx_t * ctx, const uint8_t * out_pem, size_t out_len, char * key, size_t key_len) static
Definition at line 324 of file delegation_gridsite_put.c.
References brix_sd_ucred_key(), ngx_http_brix_webdav_loc_conf_t::common, delegation_reject(), delegation_store_pem(), ngx_http_brix_webdav_req_ctx_t::dn, key, and ngx_http_brix_shared_conf_t::storage_credential_dir.
Referenced by webdav_delegation_put_handle().
delegation_put_take_key()
static ngx_int_t delegation_put_take_key (ngx_http_request_t * r, const ngx_http_brix_webdav_req_ctx_t * ctx, const char * id, EVP_PKEY ** reqkey) static
Definition at line 196 of file delegation_gridsite_put.c.
References brix_deleg_store(), brix_deleg_store_take(), BRIX_DELEG_TAKE_EXPIRED, BRIX_DELEG_TAKE_NOT_FOUND, BRIX_DELEG_TAKE_OK, brix_sanitize_log_string(), delegation_reject(), and ngx_http_brix_webdav_req_ctx_t::dn.
Referenced by webdav_delegation_put_handle().
delegation_put_validate_chain()
static ngx_int_t delegation_put_validate_chain (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const ngx_http_brix_webdav_req_ctx_t * ctx, const char * id, const uint8_t * out_pem, size_t out_len) static
Definition at line 274 of file delegation_gridsite_put.c.
References delegation_chain_expired(), delegation_chain_trusted(), delegation_eec_dn_matches(), delegation_find_eec(), delegation_reject(), ngx_http_brix_webdav_req_ctx_t::dn, and STACK_OF().
Referenced by webdav_delegation_put_handle().
delegation_split_first_pem_block()
static ngx_int_t delegation_split_first_pem_block (const u_char * body, size_t body_len, u_char ** proxy_pem, size_t * proxy_pem_len, u_char ** chain_pem, size_t * chain_pem_len) static
Definition at line 103 of file delegation_gridsite_put.c.
References gsi_pem_export_chain(), gsi_pem_export_one(), and STACK_OF().
Referenced by delegation_put_assemble().
gsi_pem_export_chain()
static u_char * gsi_pem_export_chain (STACK_OF(X509) * chain, size_t * len) static
Definition at line 57 of file delegation_gridsite_put.c.
Referenced by delegation_split_first_pem_block().
gsi_pem_export_one()
static u_char * gsi_pem_export_one (X509 * cert, size_t * len) static
Definition at line 36 of file delegation_gridsite_put.c.
Referenced by delegation_split_first_pem_block().
webdav_delegation_put_handle()
void webdav_delegation_put_handle (ngx_http_request_t * r)
Definition at line 346 of file delegation_gridsite_put.c.
References BRIX_DELEG_ID_HEXLEN, BRIX_DELEGATION_BODY_MAX, brix_http_body_read_all(), BRIX_UCRED_KEY_MAX, delegation_client_authenticated(), delegation_extract_id(), delegation_put_assemble(), delegation_put_store(), delegation_put_take_key(), delegation_put_validate_chain(), delegation_reject(), key, ngx_http_brix_webdav_module, and ngx_memcpy.
Referenced by webdav_dispatch_delegation_gridsite().