nginx-xrootd: src/protocols/webdav/delegation_internal.h File Reference
delegation_internal.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
#include "webdav.h"
Macros
#define BRIX_DELEGATION_BODY_MAX (64 * 1024)
#define BRIX_DELEG_ID_BYTES 16
#define BRIX_DELEG_ID_HEXLEN (BRIX_DELEG_ID_BYTES * 2)
Enumerations
enum brix_deleg_take_t { BRIX_DELEG_TAKE_NOT_FOUND = 0 , BRIX_DELEG_TAKE_EXPIRED , BRIX_DELEG_TAKE_DN_MISMATCH , BRIX_DELEG_TAKE_OK }
Functions
int delegation_client_authenticated (const ngx_http_brix_webdav_req_ctx_t *ctx)
X509 * delegation_find_eec (STACK_OF(X509) *chain)
STACK_OF (X509) *delegation_parse_chain(const u_char *pem
int delegation_chain_expired (STACK_OF(X509) *chain)
int delegation_eec_dn_matches (X509 *eec, const char *want_dn)
ngx_int_t delegation_chain_trusted (ngx_http_request_t *r, const ngx_http_brix_webdav_loc_conf_t *conf, STACK_OF(X509) *chain)
ngx_int_t delegation_store_pem (ngx_log_t *log, const ngx_str_t *dir, const char *key, const u_char *pem, size_t pem_len)
void delegation_reject (ngx_http_request_t *r, ngx_uint_t status, const char *msg)
brix_deleg_store_t * brix_deleg_store (void)
ngx_int_t brix_deleg_store_put (brix_deleg_store_t *st, EVP_PKEY *fresh_key, const char *client_dn, char *id_out, size_t id_out_cap)
brix_deleg_take_t brix_deleg_store_take (brix_deleg_store_t *st, const char *id, const char *want_dn, EVP_PKEY **key_out)
Variables
size_t pem_len
Macro Definition Documentation
BRIX_DELEG_ID_BYTES
#define BRIX_DELEG_ID_BYTES 16
Definition at line 29 of file delegation_internal.h.
BRIX_DELEG_ID_HEXLEN
#define BRIX_DELEG_ID_HEXLEN (BRIX_DELEG_ID_BYTES * 2)
Definition at line 30 of file delegation_internal.h.
BRIX_DELEGATION_BODY_MAX
#define BRIX_DELEGATION_BODY_MAX (64 * 1024)
Definition at line 26 of file delegation_internal.h.
Enumeration Type Documentation
brix_deleg_take_t
enum brix_deleg_take_t
Enumerator
BRIX_DELEG_TAKE_NOT_FOUND
BRIX_DELEG_TAKE_EXPIRED
BRIX_DELEG_TAKE_DN_MISMATCH
BRIX_DELEG_TAKE_OK
Definition at line 58 of file delegation_internal.h.
Function Documentation
brix_deleg_store()
brix_deleg_store_t * brix_deleg_store (void)
Definition at line 78 of file delegation_store.c.
References brix_deleg_store_singleton, and ngx_pcalloc().
Referenced by delegation_put_take_key(), and webdav_delegation_request_handle().
brix_deleg_store_put()
ngx_int_t brix_deleg_store_put (brix_deleg_store_t * st, EVP_PKEY * fresh_key, const char * client_dn, char * id_out, size_t id_out_cap)
Definition at line 146 of file delegation_store.c.
References BRIX_DELEG_ID_BYTES, BRIX_DELEG_ID_HEXLEN, BRIX_DELEG_STORE_CAP, brix_deleg_store_sweep(), BRIX_DELEG_TTL_SEC, brix_hex_encode(), hex(), and ngx_memcpy.
Referenced by webdav_delegation_request_handle().
brix_deleg_store_take()
brix_deleg_take_t brix_deleg_store_take (brix_deleg_store_t * st, const char * id, const char * want_dn, EVP_PKEY ** key_out)
Definition at line 217 of file delegation_store.c.
References brix_deleg_entry_free(), BRIX_DELEG_STORE_CAP, brix_deleg_store_sweep(), BRIX_DELEG_TAKE_DN_MISMATCH, BRIX_DELEG_TAKE_EXPIRED, BRIX_DELEG_TAKE_NOT_FOUND, BRIX_DELEG_TAKE_OK, brix_deleg_entry_t::client_dn, brix_deleg_entry_t::expires_at, brix_deleg_entry_t::fresh_key, and brix_deleg_entry_t::id.
Referenced by delegation_put_take_key().
delegation_chain_expired()
int delegation_chain_expired (STACK_OF(X509) * chain)
Definition at line 158 of file delegation.c.
Referenced by delegation_put_validate_chain(), and delegation_validate_and_store().
delegation_chain_trusted()
ngx_int_t delegation_chain_trusted (ngx_http_request_t * r, const ngx_http_brix_webdav_loc_conf_t * conf, STACK_OF(X509) * chain)
Definition at line 215 of file delegation.c.
References brix_gsi_verify_chain(), ngx_http_brix_webdav_loc_conf_t::ca_store, and ngx_http_brix_webdav_loc_conf_t::verify_depth.
Referenced by delegation_put_validate_chain(), and delegation_validate_and_store().
delegation_client_authenticated()
int delegation_client_authenticated (const ngx_http_brix_webdav_req_ctx_t * ctx)
Definition at line 82 of file delegation.c.
References ngx_http_brix_webdav_req_ctx_t::dn, ngx_http_brix_webdav_req_ctx_t::token_auth, and ngx_http_brix_webdav_req_ctx_t::verified.
Referenced by webdav_delegation_handle(), webdav_delegation_put_handle(), and webdav_delegation_request_handle().
delegation_eec_dn_matches()
int delegation_eec_dn_matches (X509 * eec, const char * want_dn)
Definition at line 178 of file delegation.c.
References brix_x509_oneline().
Referenced by delegation_put_validate_chain(), and delegation_validate_and_store().
delegation_find_eec()
X509 * delegation_find_eec (STACK_OF(X509) * chain)
Definition at line 98 of file delegation.c.
References brix_px_classify(), and BRIX_PX_NONE.
Referenced by delegation_put_validate_chain(), and delegation_validate_and_store().
delegation_reject()
void delegation_reject (ngx_http_request_t * r, ngx_uint_t status, const char * msg)
Definition at line 327 of file delegation.c.
References ngx_memcpy, ngx_pcalloc(), ngx_pnalloc(), and webdav_metrics_finalize_request().
Referenced by delegation_put_assemble(), delegation_put_store(), delegation_put_take_key(), delegation_put_validate_chain(), delegation_validate_and_store(), webdav_delegation_handle(), and webdav_delegation_put_handle().
delegation_store_pem()
ngx_int_t delegation_store_pem (ngx_log_t * log, const ngx_str_t * dir, const char * key, const u_char * pem, size_t pem_len)
Definition at line 257 of file delegation.c.
References close(), key, log, open(), and pem_len.
Referenced by delegation_put_store(), and delegation_validate_and_store().
STACK_OF()
STACK_OF (X509) const
Variable Documentation
pem_len
size_t pem_len
Definition at line 39 of file delegation_internal.h.
Referenced by delegation_get_peer_pem(), delegation_req_der_to_pem(), delegation_send_csr(), delegation_store_pem(), gsi_req_der_to_pem(), STACK_OF(), and webdav_tpc_user_proxy_materialise().