nginx-xrootd: src/protocols/s3/delete_objects.c File Reference
delete_objects.c File Reference
#include "s3.h"
#include "core/http/http_body.h"
#include "auth/impersonate/lifecycle.h"
#include "fs/vfs/vfs.h"
#include <libxml/parser.h>
#include <libxml/tree.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <unistd.h>
#include <limits.h>
Macros
#define S3_DEL_MAX_KEYS 1000
#define S3_DEL_MAX_BODY (1024 * 1024) /* 1 MiB cap on XML body */
#define S3_DEL_XML_MAX (2 * 1024 * 1024) /* max output XML */
Functions
static ngx_int_t s3_delete_one (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const char *fs_path, const char **code, const char **msg)
static ngx_int_t s3_delete_xml_append_raw (ngx_buf_t *xml_buf, size_t *xml_len, const char *text)
static ngx_int_t s3_delete_xml_append_elem (ngx_buf_t *xml_buf, size_t *xml_len, const char *name, const u_char *value, size_t value_len)
static ngx_int_t s3_delete_xml_append_deleted (ngx_buf_t *xml_buf, size_t *xml_len, const u_char *key, size_t key_len)
static ngx_int_t s3_delete_xml_append_error (ngx_buf_t *xml_buf, size_t *xml_len, const u_char *key, size_t key_len, const char *code, const char *message)
static ngx_flag_t s3_delete_xml_name_is (xmlNodePtr node, const char *name)
static xmlNodePtr s3_delete_xml_find_child (xmlNodePtr node, const char *name)
static void s3_delete_objects_finish (ngx_http_request_t *r, ngx_uint_t method_slot, ngx_buf_t *xml_buf, size_t xml_len)
static void s3_delete_objects_body_handler_inner (ngx_http_request_t *r)
void s3_delete_objects_body_handler (ngx_http_request_t *r)
Macro Definition Documentation
S3_DEL_MAX_BODY
#define S3_DEL_MAX_BODY (1024 * 1024) /* 1 MiB cap on XML body */
Definition at line 35 of file delete_objects.c.
S3_DEL_MAX_KEYS
#define S3_DEL_MAX_KEYS 1000
Definition at line 34 of file delete_objects.c.
S3_DEL_XML_MAX
#define S3_DEL_XML_MAX (2 * 1024 * 1024) /* max output XML */
Definition at line 36 of file delete_objects.c.
Function Documentation
s3_delete_objects_body_handler()
void s3_delete_objects_body_handler (ngx_http_request_t * r)
Definition at line 267 of file delete_objects.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, and s3_delete_objects_body_handler_inner().
Referenced by s3_dispatch_after_auth().
s3_delete_objects_body_handler_inner()
static void s3_delete_objects_body_handler_inner (ngx_http_request_t * r) static
Definition at line 278 of file delete_objects.c.
References brix_http_body_read_all(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, ngx_http_s3_loc_conf_t::common, ngx_http_brix_s3_module, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, S3_DEL_MAX_BODY, S3_DEL_MAX_KEYS, S3_DEL_XML_MAX, s3_delete_objects_finish(), s3_delete_one(), s3_delete_xml_append_deleted(), s3_delete_xml_append_error(), s3_delete_xml_find_child(), s3_delete_xml_name_is(), S3_MAX_KEY, s3_metrics_finalize_request_method(), s3_metrics_method_slot(), s3_resolve_key(), and s3_send_xml_error().
Referenced by s3_delete_objects_body_handler().
s3_delete_objects_finish()
static void s3_delete_objects_finish (ngx_http_request_t * r, ngx_uint_t method_slot, ngx_buf_t * xml_buf, size_t xml_len) static
Definition at line 197 of file delete_objects.c.
References brix_http_send_xml_buffer(), s3_delete_xml_append_raw(), and s3_metrics_finalize_request_method().
Referenced by s3_delete_objects_body_handler_inner().
s3_delete_one()
static ngx_int_t s3_delete_one (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const char * fs_path, const char ** code, const char ** msg) static
Definition at line 53 of file delete_objects.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_S3, brix_vfs_ctx_init(), brix_vfs_unlink(), ngx_http_s3_loc_conf_t::cache_root_canon, ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, brix_vfs_ctx_t::pool, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by s3_delete_objects_body_handler_inner().
s3_delete_xml_append_deleted()
static ngx_int_t s3_delete_xml_append_deleted (ngx_buf_t * xml_buf, size_t * xml_len, const u_char * key, size_t key_len) static
Definition at line 127 of file delete_objects.c.
References key, s3_delete_xml_append_elem(), and s3_delete_xml_append_raw().
Referenced by s3_delete_objects_body_handler_inner().
s3_delete_xml_append_elem()
static ngx_int_t s3_delete_xml_append_elem (ngx_buf_t * xml_buf, size_t * xml_len, const char * name, const u_char * value, size_t value_len) static
Definition at line 104 of file delete_objects.c.
References BRIX_XML_ESCAPE_APOS_ENTITY, BRIX_XML_ESCAPE_CONTROL_PERCENT, brix_xml_write_text_element(), and name.
Referenced by s3_delete_xml_append_deleted(), and s3_delete_xml_append_error().
s3_delete_xml_append_error()
static ngx_int_t s3_delete_xml_append_error (ngx_buf_t * xml_buf, size_t * xml_len, const u_char * key, size_t key_len, const char * code, const char * message) static
Definition at line 139 of file delete_objects.c.
References key, s3_delete_xml_append_elem(), and s3_delete_xml_append_raw().
Referenced by s3_delete_objects_body_handler_inner().
s3_delete_xml_append_raw()
static ngx_int_t s3_delete_xml_append_raw (ngx_buf_t * xml_buf, size_t * xml_len, const char * text) static
Definition at line 87 of file delete_objects.c.
Referenced by s3_delete_objects_finish(), s3_delete_xml_append_deleted(), and s3_delete_xml_append_error().
s3_delete_xml_find_child()
static xmlNodePtr s3_delete_xml_find_child (xmlNodePtr node, const char * name) static
Definition at line 165 of file delete_objects.c.
References name, and s3_delete_xml_name_is().
Referenced by s3_delete_objects_body_handler_inner().
s3_delete_xml_name_is()
static ngx_flag_t s3_delete_xml_name_is (xmlNodePtr node, const char * name) static
Definition at line 157 of file delete_objects.c.
References name.
Referenced by s3_delete_objects_body_handler_inner(), and s3_delete_xml_find_child().