nginx-xrootd: src/protocols/s3/delete_objects_xml.c File Reference
delete_objects_xml.c File Reference
#include "s3.h"
#include <libxml/parser.h>
#include <libxml/tree.h>
#include <string.h>
#include "delete_objects_internal.h"
Functions
ngx_int_t s3_delete_xml_append_raw (ngx_buf_t *xml_buf, size_t *xml_len, const char *text)
ngx_int_t s3_delete_xml_append_elem (ngx_buf_t *xml_buf, size_t *xml_len, const char *name, const u_char *value, size_t value_len)
ngx_int_t s3_delete_xml_append_deleted (ngx_buf_t *xml_buf, size_t *xml_len, const u_char *key, size_t key_len)
ngx_int_t s3_delete_xml_append_error (ngx_buf_t *xml_buf, size_t *xml_len, const u_char *key, size_t key_len, const s3_del_err_t *err)
ngx_flag_t s3_delete_xml_name_is (xmlNodePtr node, const char *name)
xmlNodePtr s3_delete_xml_find_child (xmlNodePtr node, const char *name)
Function Documentation
s3_delete_xml_append_deleted()
ngx_int_t s3_delete_xml_append_deleted (ngx_buf_t * xml_buf, size_t * xml_len, const u_char * key, size_t key_len)
Definition at line 62 of file delete_objects_xml.c.
References key, s3_delete_xml_append_elem(), and s3_delete_xml_append_raw().
Referenced by s3_delete_dispose_key().
s3_delete_xml_append_elem()
ngx_int_t s3_delete_xml_append_elem (ngx_buf_t * xml_buf, size_t * xml_len, const char * name, const u_char * value, size_t value_len)
Definition at line 39 of file delete_objects_xml.c.
References BRIX_XML_ESCAPE_APOS_ENTITY, BRIX_XML_ESCAPE_CONTROL_PERCENT, brix_xml_write_text_element(), and name.
Referenced by s3_delete_xml_append_deleted(), and s3_delete_xml_append_error().
s3_delete_xml_append_error()
ngx_int_t s3_delete_xml_append_error (ngx_buf_t * xml_buf, size_t * xml_len, const u_char * key, size_t key_len, const s3_del_err_t * err)
Definition at line 85 of file delete_objects_xml.c.
References s3_del_err_t::code, key, s3_del_err_t::message, s3_delete_xml_append_elem(), and s3_delete_xml_append_raw().
Referenced by s3_delete_dispose_key(), and s3_delete_process_object().
s3_delete_xml_append_raw()
ngx_int_t s3_delete_xml_append_raw (ngx_buf_t * xml_buf, size_t * xml_len, const char * text)
Definition at line 22 of file delete_objects_xml.c.
References ngx_memcpy.
Referenced by s3_delete_objects_finish(), s3_delete_xml_append_deleted(), and s3_delete_xml_append_error().
s3_delete_xml_find_child()
xmlNodePtr s3_delete_xml_find_child (xmlNodePtr node, const char * name)
Definition at line 111 of file delete_objects_xml.c.
References name, and s3_delete_xml_name_is().
Referenced by s3_delete_process_object().
s3_delete_xml_name_is()
ngx_flag_t s3_delete_xml_name_is (xmlNodePtr node, const char * name)
Definition at line 103 of file delete_objects_xml.c.
References name.
Referenced by s3_delete_parse_body(), s3_delete_run_batch(), and s3_delete_xml_find_child().