nginx-xrootd: src/protocols/shared/deleg_capture.c File Reference
deleg_capture.c File Reference
#include "deleg_capture.h"
#include "core/http/http_headers.h"
#include "auth/crypto/store_policy.h"
#include <openssl/bio.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
#include <string.h>
Macros
#define BRIX_DELEG_PROXY_HEADER "X-Brix-Delegate-Proxy"
#define BRIX_DELEG_PROXY_HEADER_LEN (sizeof(BRIX_DELEG_PROXY_HEADER) - 1)
Functions
static int deleg_proxy_leaf_dn (const u_char *pem, size_t len, char *out, size_t outsz)
ngx_int_t brix_proto_deleg_capture_proxy_header (ngx_http_request_t *r, const brix_identity_t *identity, ngx_str_t *out)
Macro Definition Documentation
BRIX_DELEG_PROXY_HEADER
#define BRIX_DELEG_PROXY_HEADER "X-Brix-Delegate-Proxy"
Definition at line 16 of file deleg_capture.c.
BRIX_DELEG_PROXY_HEADER_LEN
#define BRIX_DELEG_PROXY_HEADER_LEN (sizeof(BRIX_DELEG_PROXY_HEADER) - 1)
Definition at line 17 of file deleg_capture.c.
Function Documentation
brix_proto_deleg_capture_proxy_header()
ngx_int_t brix_proto_deleg_capture_proxy_header (ngx_http_request_t * r, const brix_identity_t * identity, ngx_str_t * out)
Definition at line 58 of file deleg_capture.c.
References BRIX_DELEG_PROXY_HEADER, BRIX_DELEG_PROXY_HEADER_LEN, brix_http_find_header(), deleg_proxy_leaf_dn(), brix_identity_t::dn, and ngx_pnalloc().
Referenced by access_capture_deleg_proxy(), and s3_capture_delegate_proxy().
deleg_proxy_leaf_dn()
static int deleg_proxy_leaf_dn (const u_char * pem, size_t len, char * out, size_t outsz) static
Definition at line 35 of file deleg_capture.c.
References brix_x509_oneline().
Referenced by brix_proto_deleg_capture_proxy_header().