nginx-xrootd: client/apps/diag/diag_topology.c File Reference
diag_topology.c File Reference
#include "diag_internal.h"
#include "cli/jsonout.h"
Functions
int resolve_target (brix_conn *c, const brix_url *u, char *target, size_t tsz, brix_statinfo *sti, brix_status *st)
int do_topology (const diag_args *a)
void parse_http_hostport (const char *s, char *host, size_t hsz, int *port)
int resolve_once (const char *host, int port, char *ip, size_t ipsz, int *is_loop, brix_status *st)
int probe_open (brix_conn *c, const char *urlbuf, const diag_args *a, int tmo, brix_status *st)
int raw_send_expect_reject (brix_conn *c, const uint8_t hdr24[24], const uint8_t *body, uint32_t bodylen, int lie_dlen, uint32_t fake_dlen)
Function Documentation
do_topology()
int do_topology (const diag_args * a)
Definition at line 69 of file diag_topology.c.
References brix_close(), brix_connect(), brix_endpoint_parse(), brix_http_get(), brix_json_kv_str(), brix_kxr_name(), brix_locate(), brix_shellcode(), brix_stat(), brix_status_clear(), c, diag_args::cluster_url, diag_args::conn, g_fails, brix_url::host, diag_args::json, brix_status::kxr, kXR_NotFound, brix_status::msg, note(), brix_url::path, brix_url::port, probe(), s, and diag_args::url.
Referenced by main().
parse_http_hostport()
void parse_http_hostport (const char * s, char * host, size_t hsz, int * port)
Definition at line 180 of file diag_topology.c.
References s.
Referenced by do_compare_davs().
probe_open()
int probe_open (brix_conn * c, const char * urlbuf, const diag_args * a, int tmo, brix_status * st)
Definition at line 251 of file diag_topology.c.
References brix_connect(), brix_endpoint_parse(), c, and diag_args::conn.
Referenced by do_probe_robustness().
raw_send_expect_reject()
int raw_send_expect_reject (brix_conn * c, const uint8_t hdr24[24], const uint8_t * body, uint32_t bodylen, int lie_dlen, uint32_t fake_dlen)
Definition at line 274 of file diag_topology.c.
References brix_recv(), brix_status_clear(), brix_write_full(), c, kXR_ok, and kXR_oksofar.
Referenced by do_probe_robustness().
resolve_once()
int resolve_once (const char * host, int port, char * ip, size_t ipsz, int * is_loop, brix_status * st)
Definition at line 212 of file diag_topology.c.
References brix_netpref_family(), brix_status_set(), and XRDC_ESOCK.
Referenced by do_probe_robustness().
resolve_target()
int resolve_target (brix_conn * c, const brix_url * u, char * target, size_t tsz, brix_statinfo * sti, brix_status * st)
Definition at line 13 of file diag_topology.c.
References brix_dirlist(), brix_stat(), brix_status_set(), c, brix_statinfo::flags, kXR_isDir, name, brix_url::path, brix_statinfo::size, brix_dirent::st, and XRDC_EUSAGE.
Referenced by do_bench(), do_check(), doctor_one(), and watch_probe_once().