nginx-xrootd: client/apps/diag/diag_compare.c File Reference
diag_compare.c File Reference
#include "diag_internal.h"
Functions
void probe (const char *name, int ok, const char *fmt,...)
int remote_md5 (brix_conn *c, const char *path, char *hex, size_t hexsz, brix_status *st)
int do_compare_davs (const diag_args *a)
static int compare_setup (const diag_args *a, brix_url *ua, brix_url *ub, brix_conn *ca, brix_conn *cb)
static void compare_dirs (brix_conn *ca, brix_conn *cb, const char *pa, const char *pb)
static void compare_files (brix_conn *ca, brix_conn *cb, const char *pa, const char *pb)
static int compare_probe (brix_conn *ca, brix_conn *cb, const brix_url *ua, const brix_url *ub)
int do_compare (const diag_args *a)
Function Documentation
compare_dirs()
static void compare_dirs (brix_conn * ca, brix_conn * cb, const char * pa, const char * pb) static
Definition at line 185 of file diag_compare.c.
References brix_dirlist(), brix_status_clear(), name, and probe().
Referenced by compare_probe().
compare_files()
static void compare_files (brix_conn * ca, brix_conn * cb, const char * pa, const char * pb) static
Definition at line 224 of file diag_compare.c.
References brix_status_clear(), brix_status::kxr, brix_status::msg, probe(), and remote_md5().
Referenced by compare_probe().
compare_probe()
static int compare_probe (brix_conn * ca, brix_conn * cb, const brix_url * ua, const brix_url * ub) static
Definition at line 250 of file diag_compare.c.
References brix_stat(), brix_status_clear(), compare_dirs(), compare_files(), brix_statinfo::flags, kXR_isDir, brix_status::msg, brix_url::path, probe(), and brix_statinfo::size.
Referenced by do_compare().
compare_setup()
static int compare_setup (const diag_args * a, brix_url * ua, brix_url * ub, brix_conn * ca, brix_conn * cb) static
Definition at line 145 of file diag_compare.c.
References brix_close(), brix_connect(), brix_endpoint_parse(), brix_shellcode(), brix_status_clear(), diag_args::conn, brix_url::host, brix_status::msg, brix_url::path, brix_url::port, diag_args::ref_url, and diag_args::url.
Referenced by do_compare().
do_compare()
int do_compare (const diag_args * a)
Definition at line 278 of file diag_compare.c.
References brix_close(), compare_probe(), compare_setup(), diag_args::davs, do_compare_davs(), g_fails, diag_args::ref_url, and diag_args::url.
do_compare_davs()
int do_compare_davs (const diag_args * a)
Definition at line 57 of file diag_compare.c.
References brix_cksum_fd(), brix_close(), brix_connect(), brix_endpoint_parse(), brix_http_get(), brix_shellcode(), brix_status_clear(), close(), diag_args::conn, diag_args::davs, g_fails, brix_url::host, brix_status::msg, note(), parse_http_hostport(), brix_url::path, brix_url::port, probe(), remote_md5(), diag_args::url, and XRDC_CK_MD5.
Referenced by do_compare().
probe()
void probe (const char * name, int ok, const char * fmt, ...)
Definition at line 8 of file diag_compare.c.
References g_fails, and name.
Referenced by brix_redir_cache_insert(), brix_redir_cache_lookup(), brix_tier_status(), chk_probe_auth(), chk_probe_checksum(), chk_probe_confinement(), chk_probe_dirlist(), chk_probe_handle_limits(), chk_probe_pgread(), chk_probe_posc(), chk_probe_tls(), compare_dirs(), compare_files(), compare_probe(), do_compare_davs(), dx_authz_forged(), dx_http_status(), dx_record_status(), probe_p1_path_escape(), probe_p2_bad_opcode(), probe_p3_oversized_dlen(), probe_p4_oob_read(), probe_p5_partial_frame(), probe_server_survives(), sd_remote_staged_commit(), topo_probe_locate(), and topo_probe_redirect().
remote_md5()
int remote_md5 (brix_conn * c, const char * path, char * hex, size_t hexsz, brix_status * st)
Definition at line 28 of file diag_compare.c.
References brix_cksum_fd(), brix_status_set(), c, close(), download_to_fd(), hex(), XRDC_CK_MD5, and XRDC_ESOCK.
Referenced by compare_files(), and do_compare_davs().