nginx-xrootd: client/apps/diag/diag_misc.c File Reference
diag_misc.c File Reference
#include "diag_internal.h"
Functions
static void probe_p1_path_escape (const char *urlbuf, const diag_args *a, int tmo)
static void probe_p2_bad_opcode (const char *urlbuf, const diag_args *a, int tmo)
static void probe_p3_oversized_dlen (const char *urlbuf, const diag_args *a, int tmo)
static void probe_p4_oob_read (const char *urlbuf, const diag_args *a, int tmo)
static void probe_p5_partial_frame (const char *urlbuf, const diag_args *a, int tmo)
static void probe_server_survives (const char *urlbuf, const diag_args *a, int tmo)
int do_probe_robustness (const diag_args *a)
int do_replay (const diag_args *a)
int do_srr (const diag_args *a)
static void tape_poll_status (const dx_url_t *u, const diag_args *a, int tmo, const char *reqid, brix_http_resp *r, brix_status *st)
int do_tape (const diag_args *a)
Function Documentation
do_probe_robustness()
int do_probe_robustness (const diag_args * a)
Definition at line 252 of file diag_misc.c.
References diag_args::authorized, brix_endpoint_parse(), brix_status_clear(), diag_args::conn, g_fails, brix_url::host, brix_status::msg, brix_url::port, probe_p1_path_escape(), probe_p2_bad_opcode(), probe_p3_oversized_dlen(), probe_p4_oob_read(), probe_p5_partial_frame(), probe_server_survives(), diag_args::probe_timeout_ms, resolve_once(), diag_args::url, and brix_opts::want_tls.
do_replay()
int do_replay (const diag_args * a)
Definition at line 301 of file diag_misc.c.
References brix_capture_playback(), brix_capture_replay(), brix_shellcode(), brix_status_clear(), diag_args::conn, brix_status::msg, diag_args::playback_url, diag_args::url, and brix_opts::wire_trace.
do_srr()
int do_srr (const diag_args * a)
Definition at line 323 of file diag_misc.c.
References brix_http_resp::body, brix_http_resp::body_len, brix_http_req(), brix_http_resp_free(), brix_status_clear(), dx_url_parse(), DXP_ROOT, dx_url_t::host, js_count(), js_str(), js_sum(), diag_args::json, brix_status::msg, name, dx_url_t::path, dx_url_t::port, diag_args::probe_timeout_ms, dx_url_t::proto, brix_http_resp::status, dx_url_t::tls, diag_args::url, and diag_args::verify_tls.
do_tape()
int do_tape (const diag_args * a)
Definition at line 415 of file diag_misc.c.
References brix_http_resp::body, brix_http_req(), brix_http_resp_free(), brix_status_clear(), dx_url_parse(), DXP_ROOT, dx_url_t::host, js_str(), brix_status::msg, dx_url_t::path, dx_url_t::port, diag_args::probe_timeout_ms, dx_url_t::proto, brix_http_resp::status, tape_poll_status(), dx_url_t::tls, diag_args::url, and diag_args::verify_tls.
probe_p1_path_escape()
static void probe_p1_path_escape (const char * urlbuf, const diag_args * a, int tmo) static
Definition at line 24 of file diag_misc.c.
References brix_close(), brix_kxr_name(), brix_stat(), brix_status_clear(), c, brix_status::kxr, brix_status::msg, probe(), and probe_open().
Referenced by do_probe_robustness().
probe_p2_bad_opcode()
static void probe_p2_bad_opcode (const char * urlbuf, const diag_args * a, int tmo) static
Definition at line 67 of file diag_misc.c.
References brix_close(), brix_status_clear(), c, brix_status::msg, probe(), probe_open(), and raw_send_expect_reject().
Referenced by do_probe_robustness().
probe_p3_oversized_dlen()
static void probe_p3_oversized_dlen (const char * urlbuf, const diag_args * a, int tmo) static
Definition at line 103 of file diag_misc.c.
References brix_close(), brix_status_clear(), c, kXR_stat, brix_status::msg, probe(), probe_open(), and raw_send_expect_reject().
Referenced by do_probe_robustness().
probe_p4_oob_read()
static void probe_p4_oob_read (const char * urlbuf, const diag_args * a, int tmo) static
Definition at line 140 of file diag_misc.c.
References brix_close(), brix_status_clear(), c, kXR_read, brix_status::msg, probe(), probe_open(), and raw_send_expect_reject().
Referenced by do_probe_robustness().
probe_p5_partial_frame()
static void probe_p5_partial_frame (const char * urlbuf, const diag_args * a, int tmo) static
Definition at line 179 of file diag_misc.c.
References brix_close(), brix_status_clear(), brix_write_full(), c, kXR_stat, brix_status::msg, probe(), and probe_open().
Referenced by do_probe_robustness().
probe_server_survives()
static void probe_server_survives (const char * urlbuf, const diag_args * a, int tmo) static
Definition at line 212 of file diag_misc.c.
References brix_close(), brix_stat(), brix_status_clear(), c, brix_status::kxr, brix_status::msg, probe(), and probe_open().
Referenced by do_probe_robustness().
tape_poll_status()
static void tape_poll_status (const dx_url_t * u, const diag_args * a, int tmo, const char * reqid, brix_http_resp * r, brix_status * st) static
Definition at line 388 of file diag_misc.c.
References brix_http_resp::body, brix_http_req(), brix_http_resp_free(), brix_status_clear(), dx_url_t::host, js_str(), dx_url_t::port, brix_http_resp::status, dx_url_t::tls, and diag_args::verify_tls.
Referenced by do_tape().