nginx-xrootd: client/apps/diag/diag_check.c File Reference
diag_check.c File Reference
#include "diag_internal.h"
#include "cli/jsonout.h"
Data Structures
struct chk_acc
Functions
static void emit_json_bool_or_null (FILE *out, const char *k, int tested, int v, int comma)
static void chk_probe_auth (const diag_args *a, const brix_conn *c, chk_acc *acc)
static void chk_probe_tls (const diag_args *a, brix_conn *c, chk_acc *acc)
static void chk_probe_confinement (const diag_args *a, brix_conn *c, chk_acc *acc)
static void chk_probe_dirlist (const diag_args *a, brix_conn *c, chk_acc *acc)
static void chk_probe_checksum (const diag_args *a, brix_conn *c, const char *target, chk_acc *acc)
static void chk_probe_pgread (const diag_args *a, brix_conn *c, const char *target, chk_acc *acc)
static void chk_probe_posc (const diag_args *a, brix_conn *c, const brix_url *u, chk_acc *acc)
static void chk_probe_handle_limits (const diag_args *a, brix_conn *c, const char *target, chk_acc *acc)
static void chk_probe_cred_validity (void)
static int chk_emit_json (const diag_args *a, const chk_acc *acc)
int do_check (const diag_args *a)
void dx_probe_auth (const brix_conn *c, doctor_ep *e)
void dx_probe_namespace (brix_conn *c, doctor_ep *e)
void dx_probe_read (brix_conn *c, const char *target, doctor_ep *e)
void dx_probe_checksum (brix_conn *c, const char *target, doctor_ep *e)
void dx_probe_write (brix_conn *c, doctor_ep *e)
void dx_probe_stage (brix_conn *c, const char *target, doctor_ep *e)
int dx_authz_anon (const diag_args *a, const brix_url *u, const char *target, int have_target, char *sec_out, size_t sec_sz, doctor_ep *e)
void dx_authz_forged (const diag_args *a, const brix_url *u, const char *probe, const char *bad_token, doctor_ep *e)
void dx_authz_expired (const diag_args *a, const brix_url *u, const char *tok, doctor_ep *e)
void dx_authz_scope (const diag_args *a, const brix_url *u, const char *tok, doctor_ep *e)
Function Documentation
chk_emit_json()
static int chk_emit_json (const diag_args * a, const chk_acc * acc) static
Definition at line 367 of file diag_check.c.
References chk_acc::auth_ok, chk_acc::auth_proto, brix_json_kv_bool(), brix_json_kv_ll(), brix_json_kv_str(), chk_acc::cksum_ok, chk_acc::cksum_tested, chk_acc::confinement_ok, chk_acc::dirlist_count, chk_acc::dirlist_ok, chk_acc::dstat_ok, chk_acc::dstat_tested, emit_json_bool_or_null(), chk_acc::fails, chk_acc::hlim_ok, chk_acc::hlim_tested, chk_acc::pgread_ok, chk_acc::pgread_tested, chk_acc::posc_ok, chk_acc::posc_tested, chk_acc::tls_active, chk_acc::tls_required, chk_acc::tls_ver, and diag_args::url.
Referenced by do_check().
chk_probe_auth()
static void chk_probe_auth (const diag_args * a, const brix_conn * c, chk_acc * acc) static
Definition at line 59 of file diag_check.c.
References chk_acc::auth_ok, chk_acc::auth_proto, c, chk_acc::fails, diag_args::json, and probe().
Referenced by do_check().
chk_probe_checksum()
static void chk_probe_checksum (const diag_args * a, brix_conn * c, const char * target, chk_acc * acc) static
Definition at line 177 of file diag_check.c.
References brix_cksum_fd(), brix_query_cksum(), brix_status_clear(), c, chk_acc::cksum_ok, chk_acc::cksum_tested, close(), download_to_fd(), chk_acc::fails, diag_args::json, brix_status::msg, note(), probe(), and XRDC_CK_ADLER32.
Referenced by do_check().
chk_probe_confinement()
static void chk_probe_confinement (const diag_args * a, brix_conn * c, chk_acc * acc) static
Definition at line 115 of file diag_check.c.
References brix_kxr_name(), brix_stat(), brix_status_clear(), c, chk_acc::confinement_ok, chk_acc::fails, diag_args::json, brix_status::kxr, and probe().
Referenced by do_check().
chk_probe_cred_validity()
static void chk_probe_cred_validity (void) static
Definition at line 349 of file diag_check.c.
References brix_gsi_cert_explain(), brix_token_discover(), brix_token_explain(), note(), and tok.
Referenced by do_check().
chk_probe_dirlist()
static void chk_probe_dirlist (const diag_args * a, brix_conn * c, chk_acc * acc) static
Definition at line 134 of file diag_check.c.
References brix_dirlist(), brix_stat(), brix_status_clear(), c, chk_acc::dirlist_count, chk_acc::dirlist_ok, chk_acc::dstat_ok, chk_acc::dstat_tested, chk_acc::fails, diag_args::json, kXR_isDir, brix_status::msg, name, probe(), brix_statinfo::size, brix_dirent::st, and XRDC_PATH_MAX.
Referenced by do_check().
chk_probe_handle_limits()
static void chk_probe_handle_limits (const diag_args * a, brix_conn * c, const char * target, chk_acc * acc) static
Definition at line 304 of file diag_check.c.
References brix_file_close(), brix_file_open_read(), brix_kxr_name(), brix_stat(), brix_status_clear(), c, chk_acc::fails, chk_acc::hlim_ok, chk_acc::hlim_tested, diag_args::json, brix_status::kxr, note(), and probe().
Referenced by do_check().
chk_probe_pgread()
static void chk_probe_pgread (const diag_args * a, brix_conn * c, const char * target, chk_acc * acc) static
Definition at line 223 of file diag_check.c.
References brix_file_close(), brix_file_open_read(), brix_file_pgread(), brix_status_clear(), c, chk_acc::fails, diag_args::json, brix_status::msg, chk_acc::pgread_ok, chk_acc::pgread_tested, and probe().
Referenced by do_check().
chk_probe_posc()
static void chk_probe_posc (const diag_args * a, brix_conn * c, const brix_url * u, chk_acc * acc) static
Definition at line 255 of file diag_check.c.
References brix_close(), brix_connect(), brix_file_open_write(), brix_file_write(), brix_kxr_name(), brix_rm(), brix_stat(), brix_status_clear(), c, close(), diag_args::conn, chk_acc::fails, brix_io::fd, brix_conn::io, diag_args::json, brix_status::kxr, brix_status::msg, note(), chk_acc::posc_ok, chk_acc::posc_tested, and probe().
Referenced by do_check().
chk_probe_tls()
static void chk_probe_tls (const diag_args * a, brix_conn * c, chk_acc * acc) static
Definition at line 89 of file diag_check.c.
References brix_tls_info(), c, chk_acc::fails, diag_args::json, kXR_gotoTLS, note(), probe(), chk_acc::tls_active, chk_acc::tls_required, and chk_acc::tls_ver.
Referenced by do_check().
do_check()
int do_check (const diag_args * a)
Definition at line 403 of file diag_check.c.
References chk_acc::auth_proto, brix_close(), brix_connect(), brix_endpoint_parse(), brix_explain_conn(), brix_shellcode(), brix_status_clear(), c, chk_emit_json(), chk_probe_auth(), chk_probe_checksum(), chk_probe_confinement(), chk_probe_cred_validity(), chk_probe_dirlist(), chk_probe_handle_limits(), chk_probe_pgread(), chk_probe_posc(), chk_probe_tls(), diag_args::conn, g_fails, brix_url::host, diag_args::json, brix_status::msg, note(), brix_url::port, resolve_target(), diag_args::url, and XRDC_PATH_MAX.
dx_authz_anon()
int dx_authz_anon (const diag_args * a, const brix_url * u, const char * target, int have_target, char * sec_out, size_t sec_sz, doctor_ep * e)
Definition at line 716 of file diag_check.c.
References brix_close(), brix_file_close(), brix_file_open_read(), brix_stat(), brix_status_clear(), c, dx_connect_as(), DX_FAIL, DX_OK, dx_record(), DX_WARN, and brix_status::kxr.
Referenced by doctor_auth_suite().
dx_authz_expired()
void dx_authz_expired (const diag_args * a, const brix_url * u, const char * tok, doctor_ep * e)
Definition at line 805 of file diag_check.c.
References brix_close(), c, dx_connect_as(), DX_FAIL, DX_OK, dx_record(), DX_WARN, brix_status::kxr, kXR_AuthFailed, kXR_NotAuthorized, tok, and XRDC_EAUTH.
Referenced by auth_suite_token_probes().
dx_authz_forged()
void dx_authz_forged (const diag_args * a, const brix_url * u, const char * probe, const char * bad_token, doctor_ep * e)
Definition at line 773 of file diag_check.c.
References brix_close(), c, dx_connect_as(), DX_FAIL, DX_OK, dx_record(), DX_WARN, brix_status::kxr, kXR_AuthFailed, kXR_NotAuthorized, probe(), and XRDC_EAUTH.
Referenced by auth_suite_forged_probes().
dx_authz_scope()
void dx_authz_scope (const diag_args * a, const brix_url * u, const char * tok, doctor_ep * e)
Definition at line 835 of file diag_check.c.
References brix_close(), brix_mkdir(), brix_mono_ns(), brix_rmdir(), brix_status_clear(), c, dx_connect_as(), DX_FAIL, DX_OK, dx_record(), DX_WARN, brix_status::kxr, kXR_AuthFailed, kXR_fsReadOnly, kXR_NotAuthorized, tok, and XRDC_EAUTH.
Referenced by auth_suite_token_probes().
dx_probe_auth()
void dx_probe_auth (const brix_conn * c, doctor_ep * e)
Definition at line 466 of file diag_check.c.
References c, DX_OK, dx_record(), and DX_WARN.
Referenced by doctor_diagnose().
dx_probe_checksum()
void dx_probe_checksum (brix_conn * c, const char * target, doctor_ep * e)
Definition at line 569 of file diag_check.c.
References brix_cksum_fd(), brix_query_cksum(), brix_status_clear(), c, close(), download_to_fd(), DX_FAIL, DX_OK, dx_record(), dx_record_status(), brix_status::kxr, kXR_Unsupported, and XRDC_CK_ADLER32.
Referenced by doctor_diagnose().
dx_probe_namespace()
void dx_probe_namespace (brix_conn * c, doctor_ep * e)
Definition at line 482 of file diag_check.c.
References brix_dirlist(), brix_stat(), brix_status_clear(), c, DX_OK, dx_record(), dx_record_status(), DX_WARN, and name.
Referenced by doctor_diagnose().
dx_probe_read()
void dx_probe_read (brix_conn * c, const char * target, doctor_ep * e)
Definition at line 524 of file diag_check.c.
References brix_file_close(), brix_file_open_read(), brix_file_read(), brix_stat(), brix_status_clear(), c, DX_OK, dx_record(), dx_record_status(), DX_WARN, brix_statinfo::flags, kXR_offline, and doctor_ep::offline_seen.
Referenced by doctor_diagnose().
dx_probe_stage()
void dx_probe_stage (brix_conn * c, const char * target, doctor_ep * e)
Definition at line 691 of file diag_check.c.
References brix_prepare(), brix_status_clear(), c, DX_OK, dx_record(), and dx_record_status().
Referenced by doctor_diagnose().
dx_probe_write()
void dx_probe_write (brix_conn * c, doctor_ep * e)
Definition at line 613 of file diag_check.c.
References brix_file_close(), brix_file_open_read(), brix_file_open_write(), brix_file_read(), brix_file_write(), brix_mkdir(), brix_mono_ns(), brix_rm(), brix_rmdir(), brix_status_clear(), c, DX_FAIL, DX_OK, dx_record(), dx_record_status(), DX_WARN, and brix_status::kxr.
Referenced by doctor_diagnose().
emit_json_bool_or_null()
static void emit_json_bool_or_null (FILE * out, const char * k, int tested, int v, int comma) static
Definition at line 20 of file diag_check.c.
References brix_json_fputs().
Referenced by chk_emit_json().