nginx-xrootd: client/apps/diag/diag_doctor.c File Reference
diag_doctor.c File Reference
#include "diag_internal.h"
Data Structures
struct http_probe_ctx
Functions
int download_to_fd (brix_conn *c, const char *path, int fd, int64_t *out_bytes, brix_status *st)
void doc_issue (doctor_ep *e, int sev, const char *fmt,...)
int doctor_xfer (brix_conn *c, const char *path, double *ttfb_ms, double *mbps, int64_t *bytes)
void doctor_metrics (const char *host, int port, doctor_ep *e)
static void auth_suite_forged_probes (const diag_args *a, const brix_url *u, doctor_ep *e)
static void auth_suite_token_probes (const diag_args *a, const brix_url *u, int ztn_adv, doctor_ep *e)
void doctor_auth_suite (const diag_args *a, const brix_url *u, const char *target, int have_target, doctor_ep *e)
void doctor_diagnose (const diag_args *a, brix_conn *c, const brix_url *u, const dx_target *t, doctor_ep *e)
static void http_record_tls (int tls, const brix_http_resp *r, doctor_ep *e)
static void http_check_common_headers (doctor_ep *e, const brix_http_resp *r)
static void http_davs_extras (const http_probe_ctx *pc, doctor_ep *e)
void doctor_http (const diag_args *a, const dx_url_t *u, doctor_ep *e)
static void s3_classify_anon (doctor_ep *e, const brix_http_resp *r)
static void s3_classify_signed (doctor_ep *e, const brix_http_resp *r)
static void s3_sigv4_probe (const http_probe_ctx *pc, const char *ak, const char *sk, doctor_ep *e)
void doctor_s3 (const diag_args *a, const dx_url_t *u, doctor_ep *e)
void doctor_cms (const diag_args *a, const char *host, int port, const char *path, doctor_ep *e)
static void doctor_classify_conn_error (const brix_status *st, const char **cause, const char **remedy)
static void doctor_one_connect_fail (const diag_args *a, const brix_url *u, const brix_status *st, const char *target, doctor_ep *e)
static void doctor_one_session_facts (brix_conn *c, doctor_ep *e)
static int doctor_one_xfer_probe (brix_conn *c, const brix_url *u, char *target, size_t tsz, doctor_ep *e)
static void doctor_one_load_signals (const diag_args *a, doctor_ep *e)
void doctor_one (const diag_args *a, const char *url, doctor_ep *e)
const char * doc_color (int s)
static int cross_diff_pair (const doctor_ep *p, const doctor_ep *q, FILE *out)
int doctor_cross (const doctor_ep *eps, int n, FILE *out)
void doctor_emit_json (const doctor_ep *eps, int n, FILE *out)
void doctor_print_diagnosis (const doctor_ep *e)
void doctor_dispatch (const diag_args *a, const char *url, doctor_ep *e)
static void remote_doctor_report_ep (const doctor_ep *e)
static void remote_doctor_report_creds (void)
int do_remote_doctor (const diag_args *a)
Function Documentation
auth_suite_forged_probes()
static void auth_suite_forged_probes (const diag_args * a, const brix_url * u, doctor_ep * e) static
Definition at line 177 of file diag_doctor.c.
References dx_authz_forged(), and dx_make_jwt().
Referenced by doctor_auth_suite().
auth_suite_token_probes()
static void auth_suite_token_probes (const diag_args * a, const brix_url * u, int ztn_adv, doctor_ep * e) static
Definition at line 210 of file diag_doctor.c.
References diag_args::allow_write, diag_args::authorized, brix_token_discover(), brix_token_meta_get(), dx_authz_expired(), dx_authz_scope(), dx_is_loopback(), brix_token_meta::expired, brix_token_meta::has_read, brix_token_meta::has_scope, brix_token_meta::has_write, doctor_ep::host, tok, and brix_token_meta::valid.
Referenced by doctor_auth_suite().
cross_diff_pair()
static int cross_diff_pair (const doctor_ep * p, const doctor_ep * q, FILE * out) static
Definition at line 954 of file diag_doctor.c.
References doctor_ep::auth, doctor_ep::connected, brix_netfacts::family, doctor_ep::host, doctor_ep::nf, doctor_ep::port, and doctor_ep::tls_active.
Referenced by doctor_cross().
do_remote_doctor()
int do_remote_doctor (const diag_args * a)
Definition at line 1160 of file diag_doctor.c.
References doc_color(), DOC_GREEN, DOC_RED, doctor_cross(), doctor_dispatch(), doctor_emit_json(), diag_args::json, diag_args::nurls, remote_doctor_report_creds(), remote_doctor_report_ep(), doctor_ep::status, and diag_args::urls.
doc_color()
const char * doc_color (int s)
Definition at line 940 of file diag_doctor.c.
References DOC_RED, DOC_YELLOW, and s.
Referenced by do_remote_doctor(), doctor_emit_json(), and remote_doctor_report_ep().
doc_issue()
void doc_issue (doctor_ep * e, int sev, const char * fmt, ...)
Definition at line 73 of file diag_doctor.c.
References DOC_MAXISS, doctor_ep::issues, doctor_ep::nissues, and doctor_ep::status.
Referenced by doctor_cms(), doctor_one(), doctor_one_connect_fail(), doctor_one_load_signals(), doctor_one_session_facts(), and dx_http_fail().
doctor_auth_suite()
void doctor_auth_suite (const diag_args * a, const brix_url * u, const char * target, int have_target, doctor_ep * e)
Definition at line 239 of file diag_doctor.c.
References auth_suite_forged_probes(), auth_suite_token_probes(), dx_authz_anon(), DX_OK, and dx_record().
Referenced by doctor_diagnose(), and doctor_one_connect_fail().
doctor_classify_conn_error()
static void doctor_classify_conn_error (const brix_status * st, const char ** cause, const char ** remedy) static
Definition at line 755 of file diag_doctor.c.
References brix_status::msg, and brix_status::sys_errno.
Referenced by doctor_one_connect_fail().
doctor_cms()
void doctor_cms (const diag_args * a, const char * host, int port, const char * path, doctor_ep * e)
Definition at line 670 of file diag_doctor.c.
References brix_close(), brix_connect(), brix_locate(), brix_stat(), brix_status_clear(), c, diag_args::conn, doctor_ep::connected, DOC_GREEN, doc_issue(), DOC_RED, DX_FAIL, DX_OK, dx_record(), dx_record_status(), DX_WARN, DXP_CMS, doctor_ep::holders, host, doctor_ep::host, brix_url::host, brix_status::kxr, kXR_NotFound, brix_url::path, port, doctor_ep::port, brix_url::port, diag_args::probe_timeout_ms, doctor_ep::proto, brix_url::scheme, doctor_ep::status, and XRDC_SCHEME_ROOT.
Referenced by doctor_dispatch().
doctor_cross()
int doctor_cross (const doctor_ep * eps, int n, FILE * out)
Definition at line 985 of file diag_doctor.c.
References cross_diff_pair().
Referenced by do_remote_doctor().
doctor_diagnose()
void doctor_diagnose (const diag_args * a, brix_conn * c, const brix_url * u, const dx_target * t, doctor_ep * e)
Definition at line 269 of file diag_doctor.c.
References diag_args::allow_write, diag_args::auth_suite, diag_args::authorized, brix_locate(), brix_status_clear(), c, doctor_auth_suite(), dx_is_loopback(), DX_OK, dx_probe_auth(), dx_probe_checksum(), dx_probe_namespace(), dx_probe_read(), dx_probe_stage(), dx_probe_write(), dx_record(), dx_record_status(), DX_WARN, dx_target::have, doctor_ep::holders, doctor_ep::host, doctor_ep::offline_seen, dx_target::path, and brix_url::path.
Referenced by doctor_one().
doctor_dispatch()
void doctor_dispatch (const diag_args * a, const char * url, doctor_ep * e)
Definition at line 1077 of file diag_doctor.c.
References doctor_cms(), doctor_http(), doctor_one(), doctor_s3(), dx_url_parse(), DXP_CMS, DXP_DAVS, DXP_HTTP, DXP_HTTPS, DXP_ROOT, DXP_S3, dx_url_t::host, dx_url_t::path, dx_url_t::port, and dx_url_t::proto.
Referenced by do_remote_doctor().
doctor_emit_json()
void doctor_emit_json (const doctor_ep * eps, int n, FILE * out)
Definition at line 1006 of file diag_doctor.c.
References doctor_ep::auth, brix_netfacts::auth_ms, doctor_ep::caps, dx_finding::cause, doctor_ep::connected, doc_color(), doctor_ep::dx, dx_proto_name(), dx_verdict_name(), brix_netfacts::family, fjson_str(), doctor_ep::holders, doctor_ep::host, doctor_ep::issues, dx_finding::kxr, doctor_ep::mbps, doctor_ep::metrics_http, doctor_ep::ndx, doctor_ep::nf, doctor_ep::nissues, doctor_ep::port, dx_finding::probe, doctor_ep::proto, dx_finding::remedy, brix_netfacts::retrans, brix_netfacts::rtt_us, doctor_ep::shedding, doctor_ep::status, brix_netfacts::tcp_ms, doctor_ep::tls_active, brix_netfacts::tls_ms, doctor_ep::tls_ver, brix_netfacts::total_ms, doctor_ep::ttfb_ms, and dx_finding::verdict.
Referenced by do_remote_doctor().
doctor_http()
void doctor_http (const diag_args * a, const dx_url_t * u, doctor_ep * e)
Definition at line 456 of file diag_doctor.c.
References brix_http_req(), brix_http_resp_free(), brix_status_clear(), doctor_ep::connected, DOC_GREEN, dx_http_fail(), dx_http_status(), DXP_DAVS, http_probe_ctx::host, dx_url_t::host, doctor_ep::host, http_check_common_headers(), http_davs_extras(), http_record_tls(), http_probe_ctx::path, dx_url_t::path, http_probe_ctx::port, dx_url_t::port, doctor_ep::port, diag_args::probe_timeout_ms, dx_url_t::proto, doctor_ep::proto, doctor_ep::status, brix_http_resp::status, http_probe_ctx::tls, dx_url_t::tls, http_probe_ctx::tmo, http_probe_ctx::verify, and diag_args::verify_tls.
Referenced by doctor_dispatch().
doctor_metrics()
void doctor_metrics (const char * host, int port, doctor_ep * e)
Definition at line 133 of file diag_doctor.c.
References brix_http_get(), brix_status_clear(), host, doctor_ep::metrics_http, port, and doctor_ep::shedding.
Referenced by doctor_one_load_signals().
doctor_one()
void doctor_one (const diag_args * a, const char * url, doctor_ep * e)
Definition at line 897 of file diag_doctor.c.
References brix_close(), brix_connect(), brix_endpoint_parse(), brix_status_clear(), c, diag_args::conn, doctor_ep::connected, DOC_GREEN, doc_issue(), DOC_RED, doctor_diagnose(), doctor_one_connect_fail(), doctor_one_load_signals(), doctor_one_session_facts(), doctor_one_xfer_probe(), doctor_ep::host, brix_url::host, brix_url::path, doctor_ep::port, brix_url::port, diag_args::probe_timeout_ms, doctor_ep::status, and XRDC_PATH_MAX.
Referenced by doctor_dispatch().
doctor_one_connect_fail()
static void doctor_one_connect_fail (const diag_args * a, const brix_url * u, const brix_status * st, const char * target, doctor_ep * e) static
Definition at line 784 of file diag_doctor.c.
References diag_args::auth_suite, doc_issue(), DOC_RED, doctor_auth_suite(), doctor_classify_conn_error(), DX_FAIL, dx_record(), brix_status::kxr, kXR_AuthFailed, kXR_NotAuthorized, and XRDC_EAUTH.
Referenced by doctor_one().
doctor_one_load_signals()
static void doctor_one_load_signals (const diag_args * a, doctor_ep * e) static
Definition at line 874 of file diag_doctor.c.
References doc_issue(), DOC_YELLOW, doctor_metrics(), brix_netfacts::have_tcpinfo, doctor_ep::have_xfer, doctor_ep::host, doctor_ep::mbps, diag_args::metrics_port, doctor_ep::nf, brix_netfacts::retrans, brix_netfacts::rtt_us, doctor_ep::shedding, and doctor_ep::xfer_bytes.
Referenced by doctor_one().
doctor_one_session_facts()
static void doctor_one_session_facts (brix_conn * c, doctor_ep * e) static
Definition at line 818 of file diag_doctor.c.
References doctor_ep::auth, brix_netdiag_facts(), brix_tls_info(), c, doctor_ep::caps, doc_issue(), DOC_RED, doctor_ep::gototls, kXR_gotoTLS, doctor_ep::nf, doctor_ep::tls_active, doctor_ep::tls_cipher, and doctor_ep::tls_ver.
Referenced by doctor_one().
doctor_one_xfer_probe()
static int doctor_one_xfer_probe (brix_conn * c, const brix_url * u, char * target, size_t tsz, doctor_ep * e) static
Definition at line 849 of file diag_doctor.c.
References brix_status_clear(), c, doctor_xfer(), doctor_ep::have_xfer, doctor_ep::mbps, resolve_target(), doctor_ep::ttfb_ms, and doctor_ep::xfer_bytes.
Referenced by doctor_one().
doctor_print_diagnosis()
void doctor_print_diagnosis (const doctor_ep * e)
Definition at line 1054 of file diag_doctor.c.
References dx_finding::cause, doctor_ep::dx, DX_FAIL, DX_OK, DX_WARN, doctor_ep::ndx, dx_finding::probe, dx_finding::remedy, and dx_finding::verdict.
Referenced by remote_doctor_report_ep().
doctor_s3()
void doctor_s3 (const diag_args * a, const dx_url_t * u, doctor_ep * e)
Definition at line 618 of file diag_doctor.c.
References brix_http_req(), brix_http_resp_free(), brix_status_clear(), doctor_ep::connected, DOC_GREEN, dx_http_fail(), DX_OK, dx_record(), DXP_S3, http_probe_ctx::host, dx_url_t::host, doctor_ep::host, http_record_tls(), http_probe_ctx::path, dx_url_t::path, http_probe_ctx::port, dx_url_t::port, doctor_ep::port, diag_args::probe_timeout_ms, doctor_ep::proto, s3_classify_anon(), s3_sigv4_probe(), doctor_ep::status, http_probe_ctx::tls, dx_url_t::tls, http_probe_ctx::tmo, http_probe_ctx::verify, and diag_args::verify_tls.
Referenced by doctor_dispatch().
doctor_xfer()
int doctor_xfer (brix_conn * c, const char * path, double * ttfb_ms, double * mbps, int64_t * bytes)
Definition at line 91 of file diag_doctor.c.
References brix_file_close(), brix_file_open_read(), brix_file_read(), brix_mono_ns(), brix_status_clear(), and c.
Referenced by doctor_one_xfer_probe().
download_to_fd()
int download_to_fd (brix_conn * c, const char * path, int fd, int64_t * out_bytes, brix_status * st)
Definition at line 14 of file diag_doctor.c.
References brix_file_close(), brix_file_open_read(), brix_file_read(), brix_status_set(), c, XRDC_EPROTO, and XRDC_ESOCK.
Referenced by bench_one(), chk_probe_checksum(), dx_probe_checksum(), and remote_md5().
http_check_common_headers()
static void http_check_common_headers (doctor_ep * e, const brix_http_resp * r) static
Definition at line 362 of file diag_doctor.c.
References brix_http_header(), DX_OK, dx_record(), and DX_WARN.
Referenced by doctor_http().
http_davs_extras()
static void http_davs_extras (const http_probe_ctx * pc, doctor_ep * e) static
Definition at line 401 of file diag_doctor.c.
References brix_http_header(), brix_http_req(), brix_http_resp_free(), brix_status_clear(), DX_OK, dx_record(), DX_WARN, http_probe_ctx::host, brix_status::kxr, http_probe_ctx::path, http_probe_ctx::port, brix_http_resp::status, http_probe_ctx::tls, http_probe_ctx::tmo, and http_probe_ctx::verify.
Referenced by doctor_http().
http_record_tls()
static void http_record_tls (int tls, const brix_http_resp * r, doctor_ep * e) static
Definition at line 342 of file diag_doctor.c.
References DX_OK, dx_record(), tls, doctor_ep::tls_active, doctor_ep::tls_cipher, brix_http_resp::tls_cipher, doctor_ep::tls_ver, and brix_http_resp::tls_ver.
Referenced by doctor_http(), and doctor_s3().
remote_doctor_report_creds()
static void remote_doctor_report_creds (void) static
Definition at line 1145 of file diag_doctor.c.
References brix_gsi_cert_explain(), brix_token_discover(), brix_token_explain(), and tok.
Referenced by do_remote_doctor().
remote_doctor_report_ep()
static void remote_doctor_report_ep (const doctor_ep * e) static
Definition at line 1103 of file diag_doctor.c.
References doctor_ep::auth, brix_netfacts::auth_ms, doctor_ep::caps, doctor_ep::connected, doc_color(), doctor_print_diagnosis(), dx_proto_name(), DXP_ROOT, brix_netfacts::family, brix_netfacts::have_tcpinfo, doctor_ep::have_xfer, doctor_ep::holders, doctor_ep::host, doctor_ep::issues, doctor_ep::mbps, doctor_ep::metrics_http, doctor_ep::nf, doctor_ep::nissues, doctor_ep::port, doctor_ep::proto, brix_netfacts::retrans, brix_netfacts::rtt_us, doctor_ep::shedding, doctor_ep::status, brix_netfacts::tcp_ms, doctor_ep::tls_active, doctor_ep::tls_cipher, brix_netfacts::tls_ms, doctor_ep::tls_ver, and doctor_ep::ttfb_ms.
Referenced by do_remote_doctor().
s3_classify_anon()
static void s3_classify_anon (doctor_ep * e, const brix_http_resp * r) static
Definition at line 512 of file diag_doctor.c.
References dx_http_status(), DX_OK, dx_record(), DX_WARN, and brix_http_resp::status.
Referenced by doctor_s3().
s3_classify_signed()
static void s3_classify_signed (doctor_ep * e, const brix_http_resp * r) static
Definition at line 540 of file diag_doctor.c.
References brix_http_resp::body, DX_FAIL, dx_http_status(), DX_OK, dx_record(), DX_WARN, and brix_http_resp::status.
Referenced by s3_sigv4_probe().
s3_sigv4_probe()
static void s3_sigv4_probe (const http_probe_ctx * pc, const char * ak, const char * sk, doctor_ep * e) static
Definition at line 575 of file diag_doctor.c.
References s3_sign_req::ak, brix_http_req(), brix_http_resp_free(), brix_status_clear(), dx_record(), DX_WARN, http_probe_ctx::host, s3_sign_req::host, brix_status::kxr, s3_sign_req::method, http_probe_ctx::path, http_probe_ctx::port, s3_sign_req::region, region, s3_classify_signed(), s3_sign(), s3_sign_req::sk, http_probe_ctx::tls, http_probe_ctx::tmo, s3_sign_req::uri, and http_probe_ctx::verify.
Referenced by doctor_s3().