nginx-xrootd: client/apps/diag/diag_internal.h File Reference
diag_internal.h File Reference
#include "brix.h"
#include "core/compat/crypto.h"
#include "core/compat/hex.h"
#include <arpa/inet.h>
#include <errno.h>
#include <fcntl.h>
#include <netdb.h>
#include <netinet/in.h>
#include <signal.h>
#include <stdarg.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct diag_args
struct dx_finding
struct doctor_ep
struct dx_rule
struct watch_sample
Macros
#define DOC_GREEN 0
#define DOC_YELLOW 1
#define DOC_RED 2
#define DOC_MAXISS 8
#define DX_OK DOC_GREEN
#define DX_WARN DOC_YELLOW
#define DX_FAIL DOC_RED
#define DOC_MAXDX 20
#define DX_ANY (-9999)
Enumerations
enum dx_proto {
DXP_ROOT = 0 , DXP_HTTP , DXP_HTTPS , DXP_DAVS ,
DXP_S3 , DXP_CMS
}
Functions
void probe (const char *name, int ok, const char *fmt,...)
void note (const char *name, const char *fmt,...)
int download_to_fd (brix_conn *c, const char *path, int fd, int64_t *out_bytes, brix_status *st)
int resolve_target (brix_conn *c, const brix_url *u, char *target, size_t tsz, brix_statinfo *sti, brix_status *st)
int do_check (const diag_args *a)
double bench_one (brix_conn *c, const char *target, brix_status *st)
void bench_sweep (brix_conn *c, const char *target)
int do_bench (const diag_args *a)
int do_metabench (const diag_args *a)
int do_topology (const diag_args *a)
int do_status (const diag_args *a)
int remote_md5 (brix_conn *c, const char *path, char *hex, size_t hexsz, brix_status *st)
void parse_http_hostport (const char *s, char *host, size_t hsz, int *port)
int do_compare_davs (const diag_args *a)
int do_compare (const diag_args *a)
int resolve_once (const char *host, int port, char *ip, size_t ipsz, int *is_loop, brix_status *st)
int probe_open (brix_conn *c, const char *urlbuf, const diag_args *a, int tmo, brix_status *st)
int raw_send_expect_reject (brix_conn *c, const uint8_t hdr24[24], const uint8_t *body, uint32_t bodylen, int lie_dlen, uint32_t fake_dlen)
int do_probe_robustness (const diag_args *a)
int do_replay (const diag_args *a)
void doc_issue (doctor_ep *e, int sev, const char *fmt,...)
int doctor_xfer (brix_conn *c, const char *path, double *ttfb_ms, double *mbps, int64_t *bytes)
void doctor_metrics (const char *host, int port, doctor_ep *e)
void dx_record (doctor_ep *e, const char *probe, int verdict, int kxr, const char *cause, const char *remedy)
void dx_record_status (doctor_ep *e, const char *probe, const brix_status *st)
int dx_is_loopback (const char *host)
void dx_probe_auth (const brix_conn *c, doctor_ep *e)
void dx_probe_namespace (brix_conn *c, doctor_ep *e)
void dx_probe_read (brix_conn *c, const char *target, doctor_ep *e)
void dx_probe_checksum (brix_conn *c, const char *target, doctor_ep *e)
void dx_probe_write (brix_conn *c, doctor_ep *e)
void dx_probe_stage (brix_conn *c, const char *target, doctor_ep *e)
int dx_b64url_enc (const unsigned char *in, size_t n, char *out, size_t outsz)
int dx_make_jwt (const char *header, const char *payload, const char *sig, char *out, size_t outsz)
int dx_connect_as (const diag_args *a, const brix_url *u, int force_anon, const char *token_override, const char *auth_force, brix_conn *c, brix_status *st)
int dx_authz_anon (const diag_args *a, const brix_url *u, const char *target, int have_target, char *sec_out, size_t sec_sz, doctor_ep *e)
void dx_authz_forged (const diag_args *a, const brix_url *u, const char *probe, const char *bad_token, doctor_ep *e)
void dx_authz_expired (const diag_args *a, const brix_url *u, const char *tok, doctor_ep *e)
void dx_authz_scope (const diag_args *a, const brix_url *u, const char *tok, doctor_ep *e)
void doctor_auth_suite (const diag_args *a, const brix_url *u, const char *target, int have_target, doctor_ep *e)
void doctor_diagnose (const diag_args *a, brix_conn *c, const brix_url *u, const char *target, int have_target, doctor_ep *e)
const char * dx_proto_name (dx_proto p)
int dx_url_parse (const char *url, dx_proto *proto, int *tls, char *host, size_t hsz, int *port, char *path, size_t psz)
void dx_http_status (doctor_ep *e, const char *probe, int status)
void dx_http_fail (doctor_ep *e, int tls, const brix_status *st)
void doctor_http (const diag_args *a, dx_proto proto, int tls, const char *host, int port, const char *path, doctor_ep *e)
int s3_sign (const char *method, const char *host, const char *uri, const char *ak, const char *sk, const char *region, char *hdrs, size_t hdrsz)
void doctor_s3 (const diag_args *a, int tls, const char *host, int port, const char *uri, doctor_ep *e)
void doctor_cms (const diag_args *a, const char *host, int port, const char *path, doctor_ep *e)
void doctor_one (const diag_args *a, const char *url, doctor_ep *e)
const char * doc_color (int s)
int doctor_cross (const doctor_ep *eps, int n, FILE *out)
void fjson_str (FILE *out, const char *s)
const char * dx_verdict_name (int v)
void doctor_emit_json (const doctor_ep *eps, int n, FILE *out)
void doctor_print_diagnosis (const doctor_ep *e)
int js_str (const char *json, const char *key, char *out, size_t osz)
long long js_sum (const char *json, const char *key)
int js_count (const char *json, const char *key)
int do_srr (const diag_args *a)
int do_tape (const diag_args *a)
void doctor_dispatch (const diag_args *a, const char *url, doctor_ep *e)
int do_remote_doctor (const diag_args *a)
void watch_on_signal (int sig)
int watch_count_tokens (const char *s)
void watch_prom_label (const char *s, char *out, size_t osz)
int watch_probe_once (const diag_args *a, const char *url, watch_sample *out)
void watch_emit_human (const watch_sample *s, FILE *out)
void watch_emit_json (const watch_sample *s, FILE *out)
void watch_emit_prom (const watch_sample *samples, int n, FILE *out)
int watch_write_prom_atomic (const char *path, const watch_sample *samples, int n, brix_status *st)
void watch_sleep (int seconds)
int do_watch (const diag_args *a)
void usage (void)
int brix_qstats_main (int argc, char **argv)
int brix_wait41_main (int argc, char **argv)
int brix_mpxstats_main (int argc, char **argv)
Variables
int g_fails
const dx_rule DX_RULES []
volatile sig_atomic_t g_watch_stop
Macro Definition Documentation
DOC_GREEN
#define DOC_GREEN 0
Definition at line 52 of file diag_internal.h.
DOC_MAXDX
#define DOC_MAXDX 20
Definition at line 59 of file diag_internal.h.
DOC_MAXISS
#define DOC_MAXISS 8
Definition at line 55 of file diag_internal.h.
DOC_RED
#define DOC_RED 2
Definition at line 54 of file diag_internal.h.
DOC_YELLOW
#define DOC_YELLOW 1
Definition at line 53 of file diag_internal.h.
DX_ANY
#define DX_ANY (-9999)
Definition at line 103 of file diag_internal.h.
DX_FAIL
#define DX_FAIL DOC_RED
Definition at line 58 of file diag_internal.h.
DX_OK
#define DX_OK DOC_GREEN
Definition at line 56 of file diag_internal.h.
DX_WARN
#define DX_WARN DOC_YELLOW
Definition at line 57 of file diag_internal.h.
Enumeration Type Documentation
dx_proto
enum dx_proto
Enumerator
DXP_ROOT
DXP_HTTP
DXP_HTTPS
DXP_DAVS
DXP_S3
DXP_CMS
Definition at line 68 of file diag_internal.h.
Function Documentation
bench_one()
double bench_one (brix_conn * c, const char * target, brix_status * st)
Definition at line 11 of file diag_bench.c.
References brix_mono_ns(), brix_status_set(), c, close(), download_to_fd(), and XRDC_ESOCK.
Referenced by do_bench().
bench_sweep()
void bench_sweep (brix_conn * c, const char * target)
Definition at line 48 of file diag_bench.c.
References brix_file_close(), brix_file_open_read(), brix_file_read(), brix_mono_ns(), brix_status_clear(), c, and brix_status::msg.
Referenced by do_bench().
brix_mpxstats_main()
int brix_mpxstats_main (int argc, char ** argv)
Definition at line 125 of file mpxstats.c.
References brix_client_version(), brix_http_get(), brix_status_clear(), g_n, ingest_buffer(), brix_status::msg, report(), and usage_fp().
Referenced by main().
brix_qstats_main()
int brix_qstats_main (int argc, char ** argv)
Definition at line 18 of file xrdqstats.c.
References brix_cli_connect(), brix_client_version(), brix_close(), brix_query(), brix_shellcode(), BRIX_USAGE_FOOTER, c, kXR_Qconfig, kXR_Qspace, kXR_QStats, and brix_status::msg.
Referenced by main().
brix_wait41_main()
int brix_wait41_main (int argc, char ** argv)
Definition at line 23 of file wait41.c.
References brix_client_version(), brix_close(), brix_connect(), brix_crypto_init(), brix_endpoint_parse(), brix_status_clear(), brix_tcp_connect(), BRIX_USAGE_FOOTER, c, close(), brix_url::host, brix_status::msg, and brix_url::port.
Referenced by main().
do_bench()
int do_bench (const diag_args * a)
Definition at line 94 of file diag_bench.c.
References bench_one(), bench_sweep(), brix_close(), brix_connect(), brix_copy(), brix_endpoint_parse(), brix_mono_ns(), brix_netdiag_report(), brix_shellcode(), brix_status_clear(), brix_timing_report(), c, close(), diag_args::conn, brix_copy_opts::force, brix_url::host, brix_status::msg, brix_url::port, resolve_target(), brix_copy_opts::silent, brix_statinfo::size, diag_args::streams, brix_copy_opts::streams, diag_args::sweep, diag_args::url, brix_opts::want_tls, and XRDC_PATH_MAX.
Referenced by main().
do_check()
int do_check (const diag_args * a)
Definition at line 43 of file diag_check.c.
References brix_cksum_fd(), brix_close(), brix_connect(), brix_dirlist(), brix_endpoint_parse(), brix_explain_conn(), brix_file_close(), brix_file_open_read(), brix_file_open_write(), brix_file_pgread(), brix_file_write(), brix_gsi_cert_explain(), brix_json_kv_bool(), brix_json_kv_ll(), brix_json_kv_str(), brix_kxr_name(), brix_query_cksum(), brix_rm(), brix_shellcode(), brix_stat(), brix_status_clear(), brix_tls_info(), brix_token_discover(), brix_token_explain(), c, close(), diag_args::conn, download_to_fd(), emit_json_bool_or_null(), brix_io::fd, g_fails, brix_url::host, brix_conn::io, diag_args::json, brix_status::kxr, kXR_gotoTLS, kXR_isDir, brix_status::msg, name, note(), brix_url::port, probe(), resolve_target(), brix_statinfo::size, brix_dirent::st, diag_args::url, XRDC_CK_ADLER32, and XRDC_PATH_MAX.
Referenced by main().
do_compare()
int do_compare (const diag_args * a)
Definition at line 134 of file diag_compare.c.
References brix_close(), brix_connect(), brix_dirlist(), brix_endpoint_parse(), brix_shellcode(), brix_stat(), brix_status_clear(), diag_args::conn, diag_args::davs, do_compare_davs(), brix_statinfo::flags, g_fails, brix_url::host, brix_status::kxr, kXR_isDir, brix_status::msg, name, brix_url::path, brix_url::port, probe(), diag_args::ref_url, remote_md5(), brix_statinfo::size, and diag_args::url.
Referenced by main().
do_compare_davs()
int do_compare_davs (const diag_args * a)
Definition at line 57 of file diag_compare.c.
References brix_cksum_fd(), brix_close(), brix_connect(), brix_endpoint_parse(), brix_http_get(), brix_shellcode(), brix_status_clear(), close(), diag_args::conn, diag_args::davs, g_fails, brix_url::host, brix_status::msg, note(), parse_http_hostport(), brix_url::path, brix_url::port, probe(), remote_md5(), diag_args::url, and XRDC_CK_MD5.
Referenced by do_compare().
do_metabench()
int do_metabench (const diag_args * a)
Definition at line 19 of file diag_metabench.c.
References brix_endpoint_parse(), brix_status_clear(), diag_args::conn, diag_args::count, MB_CREATE, MB_REMOVE, metabench_plan_init(), metabench_result_print(), metabench_run(), diag_args::streams, and diag_args::url.
Referenced by main().
do_probe_robustness()
int do_probe_robustness (const diag_args * a)
Definition at line 9 of file diag_misc.c.
References diag_args::authorized, brix_close(), brix_endpoint_parse(), brix_kxr_name(), brix_stat(), brix_status_clear(), brix_write_full(), c, diag_args::conn, g_fails, brix_url::host, brix_status::kxr, kXR_read, kXR_stat, brix_status::msg, brix_url::port, probe(), probe_open(), diag_args::probe_timeout_ms, raw_send_expect_reject(), resolve_once(), diag_args::url, and brix_opts::want_tls.
Referenced by main().
do_remote_doctor()
int do_remote_doctor (const diag_args * a)
Definition at line 853 of file diag_doctor.c.
References doctor_ep::auth, brix_netfacts::auth_ms, brix_gsi_cert_explain(), brix_token_discover(), brix_token_explain(), doctor_ep::caps, doctor_ep::connected, doc_color(), DOC_GREEN, DOC_RED, doctor_cross(), doctor_dispatch(), doctor_emit_json(), doctor_print_diagnosis(), dx_proto_name(), DXP_ROOT, brix_netfacts::family, brix_netfacts::have_tcpinfo, doctor_ep::have_xfer, doctor_ep::holders, doctor_ep::host, doctor_ep::issues, diag_args::json, doctor_ep::mbps, doctor_ep::metrics_http, doctor_ep::nf, doctor_ep::nissues, diag_args::nurls, doctor_ep::port, doctor_ep::proto, brix_netfacts::retrans, brix_netfacts::rtt_us, doctor_ep::shedding, doctor_ep::status, brix_netfacts::tcp_ms, doctor_ep::tls_active, doctor_ep::tls_cipher, brix_netfacts::tls_ms, doctor_ep::tls_ver, doctor_ep::ttfb_ms, and diag_args::urls.
Referenced by main().
do_replay()
int do_replay (const diag_args * a)
Definition at line 178 of file diag_misc.c.
References brix_capture_playback(), brix_capture_replay(), brix_shellcode(), brix_status_clear(), diag_args::conn, brix_status::msg, diag_args::playback_url, diag_args::url, and brix_opts::wire_trace.
Referenced by main().
do_srr()
int do_srr (const diag_args * a)
Definition at line 200 of file diag_misc.c.
References brix_http_resp::body, brix_http_resp::body_len, brix_http_req(), brix_http_resp_free(), brix_status_clear(), dx_url_parse(), DXP_ROOT, js_count(), js_str(), js_sum(), diag_args::json, brix_status::msg, name, diag_args::probe_timeout_ms, brix_http_resp::status, tls, diag_args::url, diag_args::verify_tls, and XRDC_PATH_MAX.
Referenced by main().
do_status()
int do_status (const diag_args * a)
Definition at line 11 of file diag_watch.c.
References brix_endpoint_parse(), brix_http_get(), brix_status_clear(), brix_url::host, diag_args::metrics_port, brix_status::msg, and diag_args::url.
Referenced by main().
do_tape()
int do_tape (const diag_args * a)
Definition at line 254 of file diag_misc.c.
References brix_http_resp::body, brix_http_req(), brix_http_resp_free(), brix_status_clear(), dx_url_parse(), DXP_ROOT, js_str(), brix_status::msg, diag_args::probe_timeout_ms, brix_http_resp::status, tls, diag_args::url, diag_args::verify_tls, and XRDC_PATH_MAX.
Referenced by main().
do_topology()
int do_topology (const diag_args * a)
Definition at line 69 of file diag_topology.c.
References brix_close(), brix_connect(), brix_endpoint_parse(), brix_http_get(), brix_json_kv_str(), brix_kxr_name(), brix_locate(), brix_shellcode(), brix_stat(), brix_status_clear(), c, diag_args::cluster_url, diag_args::conn, g_fails, brix_url::host, diag_args::json, brix_status::kxr, kXR_NotFound, brix_status::msg, note(), brix_url::path, brix_url::port, probe(), s, and diag_args::url.
Referenced by main().
do_watch()
int do_watch (const diag_args * a)
Definition at line 307 of file diag_watch.c.
References brix_status_clear(), diag_args::count, g_watch_stop, diag_args::interval_s, diag_args::json, brix_status::msg, diag_args::nurls, diag_args::prom_path, diag_args::urls, watch_emit_human(), watch_emit_json(), watch_emit_prom(), watch_on_signal(), watch_probe_once(), diag_args::watch_prom, watch_sleep(), and watch_write_prom_atomic().
Referenced by main().
doc_color()
const char * doc_color (int s)
Definition at line 709 of file diag_doctor.c.
References DOC_RED, DOC_YELLOW, and s.
Referenced by do_remote_doctor(), and doctor_emit_json().
doc_issue()
void doc_issue (doctor_ep * e, int sev, const char * fmt, ...)
Definition at line 73 of file diag_doctor.c.
References DOC_MAXISS, doctor_ep::issues, doctor_ep::nissues, and doctor_ep::status.
Referenced by doctor_cms(), doctor_one(), and dx_http_fail().
doctor_auth_suite()
void doctor_auth_suite (const diag_args * a, const brix_url * u, const char * target, int have_target, doctor_ep * e)
Definition at line 176 of file diag_doctor.c.
References diag_args::allow_write, diag_args::authorized, brix_token_discover(), brix_token_meta_get(), dx_authz_anon(), dx_authz_expired(), dx_authz_forged(), dx_authz_scope(), dx_is_loopback(), dx_make_jwt(), DX_OK, dx_record(), brix_token_meta::expired, brix_token_meta::has_read, brix_token_meta::has_scope, brix_token_meta::has_write, doctor_ep::host, and brix_token_meta::valid.
Referenced by doctor_diagnose(), and doctor_one().
doctor_cms()
void doctor_cms (const diag_args * a, const char * host, int port, const char * path, doctor_ep * e)
Definition at line 513 of file diag_doctor.c.
References brix_close(), brix_connect(), brix_locate(), brix_stat(), brix_status_clear(), c, diag_args::conn, doctor_ep::connected, DOC_GREEN, doc_issue(), DOC_RED, DX_FAIL, DX_OK, dx_record(), dx_record_status(), DX_WARN, DXP_CMS, doctor_ep::holders, doctor_ep::host, brix_url::host, brix_status::kxr, kXR_NotFound, brix_url::path, doctor_ep::port, brix_url::port, diag_args::probe_timeout_ms, doctor_ep::proto, brix_url::scheme, doctor_ep::status, and XRDC_SCHEME_ROOT.
Referenced by doctor_dispatch().
doctor_cross()
int doctor_cross (const doctor_ep * eps, int n, FILE * out)
Definition at line 717 of file diag_doctor.c.
References doctor_ep::auth, doctor_ep::connected, brix_netfacts::family, doctor_ep::host, doctor_ep::nf, doctor_ep::port, and doctor_ep::tls_active.
Referenced by do_remote_doctor().
doctor_diagnose()
void doctor_diagnose (const diag_args * a, brix_conn * c, const brix_url * u, const char * target, int have_target, doctor_ep * e)
Definition at line 238 of file diag_doctor.c.
References diag_args::allow_write, diag_args::auth_suite, diag_args::authorized, brix_locate(), brix_status_clear(), c, doctor_auth_suite(), dx_is_loopback(), DX_OK, dx_probe_auth(), dx_probe_checksum(), dx_probe_namespace(), dx_probe_read(), dx_probe_stage(), dx_probe_write(), dx_record(), dx_record_status(), DX_WARN, doctor_ep::holders, doctor_ep::host, doctor_ep::offline_seen, and brix_url::path.
Referenced by doctor_one().
doctor_dispatch()
void doctor_dispatch (const diag_args * a, const char * url, doctor_ep * e)
Definition at line 830 of file diag_doctor.c.
References doctor_cms(), doctor_http(), doctor_one(), doctor_s3(), dx_url_parse(), DXP_CMS, DXP_DAVS, DXP_HTTP, DXP_HTTPS, DXP_ROOT, DXP_S3, tls, and XRDC_PATH_MAX.
Referenced by do_remote_doctor().
doctor_emit_json()
void doctor_emit_json (const doctor_ep * eps, int n, FILE * out)
Definition at line 759 of file diag_doctor.c.
References doctor_ep::auth, brix_netfacts::auth_ms, doctor_ep::caps, dx_finding::cause, doctor_ep::connected, doc_color(), doctor_ep::dx, dx_proto_name(), dx_verdict_name(), brix_netfacts::family, fjson_str(), doctor_ep::holders, doctor_ep::host, doctor_ep::issues, dx_finding::kxr, doctor_ep::mbps, doctor_ep::metrics_http, doctor_ep::ndx, doctor_ep::nf, doctor_ep::nissues, doctor_ep::port, dx_finding::probe, doctor_ep::proto, dx_finding::remedy, brix_netfacts::retrans, brix_netfacts::rtt_us, doctor_ep::shedding, doctor_ep::status, brix_netfacts::tcp_ms, doctor_ep::tls_active, brix_netfacts::tls_ms, doctor_ep::tls_ver, brix_netfacts::total_ms, doctor_ep::ttfb_ms, and dx_finding::verdict.
Referenced by do_remote_doctor().
doctor_http()
void doctor_http (const diag_args * a, dx_proto proto, int tls, const char * host, int port, const char * path, doctor_ep * e)
Definition at line 293 of file diag_doctor.c.
References brix_http_header(), brix_http_req(), brix_http_resp_free(), brix_status_clear(), doctor_ep::connected, DOC_GREEN, dx_http_fail(), dx_http_status(), DX_OK, dx_record(), DX_WARN, DXP_DAVS, doctor_ep::host, brix_status::kxr, doctor_ep::port, diag_args::probe_timeout_ms, doctor_ep::proto, doctor_ep::status, brix_http_resp::status, tls, doctor_ep::tls_active, doctor_ep::tls_cipher, brix_http_resp::tls_cipher, doctor_ep::tls_ver, brix_http_resp::tls_ver, and diag_args::verify_tls.
Referenced by doctor_dispatch().
doctor_metrics()
void doctor_metrics (const char * host, int port, doctor_ep * e)
Definition at line 133 of file diag_doctor.c.
References brix_http_get(), brix_status_clear(), doctor_ep::metrics_http, and doctor_ep::shedding.
Referenced by doctor_one().
doctor_one()
void doctor_one (const diag_args * a, const char * url, doctor_ep * e)
Definition at line 593 of file diag_doctor.c.
References doctor_ep::auth, diag_args::auth_suite, brix_close(), brix_connect(), brix_endpoint_parse(), brix_netdiag_facts(), brix_status_clear(), brix_tls_info(), c, doctor_ep::caps, diag_args::conn, doctor_ep::connected, DOC_GREEN, doc_issue(), DOC_RED, DOC_YELLOW, doctor_auth_suite(), doctor_diagnose(), doctor_metrics(), doctor_xfer(), DX_FAIL, dx_record(), doctor_ep::gototls, brix_netfacts::have_tcpinfo, doctor_ep::have_xfer, doctor_ep::host, brix_url::host, brix_status::kxr, kXR_AuthFailed, kXR_gotoTLS, kXR_NotAuthorized, doctor_ep::mbps, diag_args::metrics_port, brix_status::msg, doctor_ep::nf, doctor_ep::port, brix_url::port, diag_args::probe_timeout_ms, resolve_target(), brix_netfacts::retrans, brix_netfacts::rtt_us, doctor_ep::shedding, doctor_ep::status, brix_status::sys_errno, doctor_ep::tls_active, doctor_ep::tls_cipher, doctor_ep::tls_ver, doctor_ep::ttfb_ms, doctor_ep::xfer_bytes, XRDC_EAUTH, and XRDC_PATH_MAX.
Referenced by doctor_dispatch().
doctor_print_diagnosis()
void doctor_print_diagnosis (const doctor_ep * e)
Definition at line 807 of file diag_doctor.c.
References dx_finding::cause, doctor_ep::dx, DX_FAIL, DX_OK, DX_WARN, doctor_ep::ndx, dx_finding::probe, dx_finding::remedy, and dx_finding::verdict.
Referenced by do_remote_doctor().
doctor_s3()
void doctor_s3 (const diag_args * a, int tls, const char * host, int port, const char * uri, doctor_ep * e)
Definition at line 410 of file diag_doctor.c.
References brix_http_resp::body, brix_http_req(), brix_http_resp_free(), brix_status_clear(), doctor_ep::connected, DOC_GREEN, DX_FAIL, dx_http_fail(), dx_http_status(), DX_OK, dx_record(), DX_WARN, DXP_S3, doctor_ep::host, brix_status::kxr, doctor_ep::port, diag_args::probe_timeout_ms, doctor_ep::proto, region, s3_sign(), doctor_ep::status, brix_http_resp::status, tls, doctor_ep::tls_active, doctor_ep::tls_cipher, brix_http_resp::tls_cipher, doctor_ep::tls_ver, brix_http_resp::tls_ver, and diag_args::verify_tls.
Referenced by doctor_dispatch().
doctor_xfer()
int doctor_xfer (brix_conn * c, const char * path, double * ttfb_ms, double * mbps, int64_t * bytes)
Definition at line 91 of file diag_doctor.c.
References brix_file_close(), brix_file_open_read(), brix_file_read(), brix_mono_ns(), brix_status_clear(), and c.
Referenced by doctor_one().
download_to_fd()
int download_to_fd (brix_conn * c, const char * path, int fd, int64_t * out_bytes, brix_status * st)
Definition at line 14 of file diag_doctor.c.
References brix_file_close(), brix_file_open_read(), brix_file_read(), brix_status_set(), c, XRDC_EPROTO, and XRDC_ESOCK.
Referenced by bench_one(), do_check(), dx_probe_checksum(), and remote_md5().
dx_authz_anon()
int dx_authz_anon (const diag_args * a, const brix_url * u, const char * target, int have_target, char * sec_out, size_t sec_sz, doctor_ep * e)
Definition at line 641 of file diag_check.c.
References brix_close(), brix_file_close(), brix_file_open_read(), brix_stat(), brix_status_clear(), c, dx_connect_as(), DX_FAIL, DX_OK, dx_record(), DX_WARN, and brix_status::kxr.
Referenced by doctor_auth_suite().
dx_authz_expired()
void dx_authz_expired (const diag_args * a, const brix_url * u, const char * tok, doctor_ep * e)
Definition at line 729 of file diag_check.c.
References brix_close(), c, dx_connect_as(), DX_FAIL, DX_OK, dx_record(), DX_WARN, brix_status::kxr, kXR_AuthFailed, kXR_NotAuthorized, and XRDC_EAUTH.
Referenced by doctor_auth_suite().
dx_authz_forged()
void dx_authz_forged (const diag_args * a, const brix_url * u, const char * probe, const char * bad_token, doctor_ep * e)
Definition at line 698 of file diag_check.c.
References brix_close(), c, dx_connect_as(), DX_FAIL, DX_OK, dx_record(), DX_WARN, brix_status::kxr, kXR_AuthFailed, kXR_NotAuthorized, probe(), and XRDC_EAUTH.
Referenced by doctor_auth_suite().
dx_authz_scope()
void dx_authz_scope (const diag_args * a, const brix_url * u, const char * tok, doctor_ep * e)
Definition at line 758 of file diag_check.c.
References brix_close(), brix_mkdir(), brix_mono_ns(), brix_rmdir(), brix_status_clear(), c, dx_connect_as(), DX_FAIL, DX_OK, dx_record(), DX_WARN, brix_status::kxr, kXR_AuthFailed, kXR_fsReadOnly, kXR_NotAuthorized, and XRDC_EAUTH.
Referenced by doctor_auth_suite().
dx_b64url_enc()
int dx_b64url_enc (const unsigned char * in, size_t n, char * out, size_t outsz)
Definition at line 186 of file xrddiag.c.
Referenced by dx_make_jwt().
dx_connect_as()
int dx_connect_as (const diag_args * a, const brix_url * u, int force_anon, const char * token_override, const char * auth_force, brix_conn * c, brix_status * st)
Definition at line 237 of file xrddiag.c.
References brix_opts::auth_force, brix_connect(), brix_status_clear(), c, diag_args::conn, and brix_opts::force_anon.
Referenced by dx_authz_anon(), dx_authz_expired(), dx_authz_forged(), and dx_authz_scope().
dx_http_fail()
void dx_http_fail (doctor_ep * e, int tls, const brix_status * st)
Definition at line 372 of file xrddiag.c.
References doc_issue(), DOC_RED, DX_FAIL, dx_record(), brix_status::kxr, brix_status::sys_errno, tls, and XRDC_EAUTH.
Referenced by doctor_http(), and doctor_s3().
dx_http_status()
void dx_http_status (doctor_ep * e, const char * probe, int status)
Definition at line 344 of file xrddiag.c.
References DX_FAIL, DX_OK, dx_record(), DX_WARN, and probe().
Referenced by doctor_http(), and doctor_s3().
dx_is_loopback()
int dx_is_loopback (const char * host)
Definition at line 170 of file xrddiag.c.
Referenced by doctor_auth_suite(), and doctor_diagnose().
dx_make_jwt()
int dx_make_jwt (const char * header, const char * payload, const char * sig, char * out, size_t outsz)
Definition at line 214 of file xrddiag.c.
References dx_b64url_enc().
Referenced by doctor_auth_suite().
dx_probe_auth()
void dx_probe_auth (const brix_conn * c, doctor_ep * e)
Definition at line 391 of file diag_check.c.
References c, DX_OK, dx_record(), and DX_WARN.
Referenced by doctor_diagnose().
dx_probe_checksum()
void dx_probe_checksum (brix_conn * c, const char * target, doctor_ep * e)
Definition at line 494 of file diag_check.c.
References brix_cksum_fd(), brix_query_cksum(), brix_status_clear(), c, close(), download_to_fd(), DX_FAIL, DX_OK, dx_record(), dx_record_status(), brix_status::kxr, kXR_Unsupported, and XRDC_CK_ADLER32.
Referenced by doctor_diagnose().
dx_probe_namespace()
void dx_probe_namespace (brix_conn * c, doctor_ep * e)
Definition at line 407 of file diag_check.c.
References brix_dirlist(), brix_stat(), brix_status_clear(), c, DX_OK, dx_record(), dx_record_status(), DX_WARN, and name.
Referenced by doctor_diagnose().
dx_probe_read()
void dx_probe_read (brix_conn * c, const char * target, doctor_ep * e)
Definition at line 449 of file diag_check.c.
References brix_file_close(), brix_file_open_read(), brix_file_read(), brix_stat(), brix_status_clear(), c, DX_OK, dx_record(), dx_record_status(), DX_WARN, brix_statinfo::flags, kXR_offline, and doctor_ep::offline_seen.
Referenced by doctor_diagnose().
dx_probe_stage()
void dx_probe_stage (brix_conn * c, const char * target, doctor_ep * e)
Definition at line 616 of file diag_check.c.
References brix_prepare(), brix_status_clear(), c, DX_OK, dx_record(), and dx_record_status().
Referenced by doctor_diagnose().
dx_probe_write()
void dx_probe_write (brix_conn * c, doctor_ep * e)
Definition at line 538 of file diag_check.c.
References brix_file_close(), brix_file_open_read(), brix_file_open_write(), brix_file_read(), brix_file_write(), brix_mkdir(), brix_mono_ns(), brix_rm(), brix_rmdir(), brix_status_clear(), c, DX_FAIL, DX_OK, dx_record(), dx_record_status(), DX_WARN, and brix_status::kxr.
Referenced by doctor_diagnose().
dx_proto_name()
const char * dx_proto_name (dx_proto p)
Definition at line 270 of file xrddiag.c.
References DXP_CMS, DXP_DAVS, DXP_HTTP, DXP_HTTPS, and DXP_S3.
Referenced by do_remote_doctor(), and doctor_emit_json().
dx_record()
void dx_record (doctor_ep * e, const char * probe, int verdict, int kxr, const char * cause, const char * remedy)
Definition at line 110 of file xrddiag.c.
References dx_finding::cause, DOC_MAXDX, doctor_ep::dx, dx_finding::kxr, doctor_ep::ndx, probe(), dx_finding::probe, dx_finding::remedy, doctor_ep::status, and dx_finding::verdict.
Referenced by doctor_auth_suite(), doctor_cms(), doctor_diagnose(), doctor_http(), doctor_one(), doctor_s3(), dx_authz_anon(), dx_authz_expired(), dx_authz_forged(), dx_authz_scope(), dx_http_fail(), dx_http_status(), dx_probe_auth(), dx_probe_checksum(), dx_probe_namespace(), dx_probe_read(), dx_probe_stage(), dx_probe_write(), and dx_record_status().
dx_record_status()
void dx_record_status (doctor_ep * e, const char * probe, const brix_status * st)
Definition at line 135 of file xrddiag.c.
References brix_kxr_name(), dx_rule::cause, DX_ANY, DX_FAIL, dx_record(), DX_RULES, dx_rule::kxr, brix_status::kxr, probe(), dx_rule::probe, dx_rule::remedy, and dx_rule::sev.
Referenced by doctor_cms(), doctor_diagnose(), dx_probe_checksum(), dx_probe_namespace(), dx_probe_read(), dx_probe_stage(), and dx_probe_write().
dx_url_parse()
int dx_url_parse (const char * url, dx_proto * proto, int * tls, char * host, size_t hsz, int * port, char * path, size_t psz)
Definition at line 290 of file xrddiag.c.
References DXP_CMS, DXP_DAVS, DXP_HTTP, DXP_HTTPS, DXP_ROOT, DXP_S3, and tls.
Referenced by do_srr(), do_tape(), and doctor_dispatch().
dx_verdict_name()
const char * dx_verdict_name (int v)
Definition at line 416 of file xrddiag.c.
References DX_FAIL, and DX_WARN.
Referenced by doctor_emit_json().
fjson_str()
void fjson_str (FILE * out, const char * s)
Definition at line 409 of file xrddiag.c.
References brix_json_fputs(), and s.
Referenced by doctor_emit_json(), and watch_emit_json().
js_count()
int js_count (const char * json, const char * key)
Definition at line 494 of file xrddiag.c.
References key.
Referenced by do_srr().
js_str()
int js_str (const char * json, const char * key, char * out, size_t osz)
Definition at line 427 of file xrddiag.c.
References key.
Referenced by do_srr(), and do_tape().
js_sum()
long long js_sum (const char * json, const char * key)
Definition at line 466 of file xrddiag.c.
References c, and key.
Referenced by do_srr().
note()
void note (const char * name, const char * fmt, ...)
Definition at line 80 of file xrddiag.c.
References name.
Referenced by do_check(), do_compare_davs(), and do_topology().
parse_http_hostport()
void parse_http_hostport (const char * s, char * host, size_t hsz, int * port)
Definition at line 180 of file diag_topology.c.
References s.
Referenced by do_compare_davs().
probe()
void probe (const char * name, int ok, const char * fmt, ...)
Definition at line 8 of file diag_compare.c.
References g_fails, and name.
Referenced by brix_redir_cache_insert(), brix_redir_cache_lookup(), brix_tier_status(), do_check(), do_compare(), do_compare_davs(), do_probe_robustness(), do_topology(), dx_authz_forged(), dx_http_status(), dx_record(), and dx_record_status().
probe_open()
int probe_open (brix_conn * c, const char * urlbuf, const diag_args * a, int tmo, brix_status * st)
Definition at line 251 of file diag_topology.c.
References brix_connect(), brix_endpoint_parse(), c, and diag_args::conn.
Referenced by do_probe_robustness().
raw_send_expect_reject()
int raw_send_expect_reject (brix_conn * c, const uint8_t hdr24[24], const uint8_t * body, uint32_t bodylen, int lie_dlen, uint32_t fake_dlen)
Definition at line 274 of file diag_topology.c.
References brix_recv(), brix_status_clear(), brix_write_full(), c, kXR_ok, and kXR_oksofar.
Referenced by do_probe_robustness().
remote_md5()
int remote_md5 (brix_conn * c, const char * path, char * hex, size_t hexsz, brix_status * st)
Definition at line 28 of file diag_compare.c.
References brix_cksum_fd(), brix_status_set(), c, close(), download_to_fd(), hex(), XRDC_CK_MD5, and XRDC_ESOCK.
Referenced by do_compare(), and do_compare_davs().
resolve_once()
int resolve_once (const char * host, int port, char * ip, size_t ipsz, int * is_loop, brix_status * st)
Definition at line 212 of file diag_topology.c.
References brix_netpref_family(), brix_status_set(), and XRDC_ESOCK.
Referenced by do_probe_robustness().
resolve_target()
int resolve_target (brix_conn * c, const brix_url * u, char * target, size_t tsz, brix_statinfo * sti, brix_status * st)
Definition at line 13 of file diag_topology.c.
References brix_dirlist(), brix_stat(), brix_status_set(), c, brix_statinfo::flags, kXR_isDir, name, brix_url::path, brix_statinfo::size, brix_dirent::st, and XRDC_EUSAGE.
Referenced by do_bench(), do_check(), doctor_one(), and watch_probe_once().
s3_sign()
int s3_sign (const char * method, const char * host, const char * uri, const char * ak, const char * sk, const char * region, char * hdrs, size_t hdrsz)
Definition at line 397 of file xrddiag.c.
References brix_s3_sign_v4(), and region.
Referenced by doctor_s3().
usage()
void usage (void)
Definition at line 78 of file xrdcp.c.
watch_count_tokens()
int watch_count_tokens (const char * s)
Definition at line 75 of file diag_watch.c.
References s.
Referenced by watch_probe_once().
watch_emit_human()
void watch_emit_human (const watch_sample * s, FILE * out)
Definition at line 185 of file diag_watch.c.
References s.
Referenced by do_watch().
watch_emit_json()
void watch_emit_json (const watch_sample * s, FILE * out)
Definition at line 199 of file diag_watch.c.
References fjson_str(), and s.
Referenced by do_watch().
watch_emit_prom()
void watch_emit_prom (const watch_sample * samples, int n, FILE * out)
Definition at line 213 of file diag_watch.c.
References watch_prom_label().
Referenced by do_watch(), and watch_write_prom_atomic().
watch_on_signal()
void watch_on_signal (int sig)
Definition at line 65 of file diag_watch.c.
References g_watch_stop.
Referenced by do_watch().
watch_probe_once()
int watch_probe_once (const diag_args * a, const char * url, watch_sample * out)
Definition at line 109 of file diag_watch.c.
References watch_sample::auth_ms, brix_netfacts::auth_ms, brix_close(), brix_connect(), brix_endpoint_parse(), brix_file_close(), brix_file_open_read(), brix_file_read(), brix_locate(), brix_mono_ns(), brix_netdiag_facts(), brix_status_clear(), brix_tls_info(), c, diag_args::conn, watch_sample::connect_ms, watch_sample::endpoint, watch_sample::holders, brix_url::host, watch_sample::locate_ms, brix_url::port, diag_args::probe_timeout_ms, watch_sample::proto, watch_sample::read_ms, resolve_target(), brix_url::scheme, watch_sample::tcp_ms, brix_netfacts::tcp_ms, watch_sample::tls_active, watch_sample::tls_ms, brix_netfacts::tls_ms, watch_sample::up, watch_count_tokens(), XRDC_PATH_MAX, and XRDC_SCHEME_ROOTS.
Referenced by do_watch().
watch_prom_label()
void watch_prom_label (const char * s, char * out, size_t osz)
Definition at line 91 of file diag_watch.c.
References s.
Referenced by watch_emit_prom().
watch_sleep()
void watch_sleep (int seconds)
Definition at line 296 of file diag_watch.c.
References g_watch_stop.
Referenced by do_watch().
watch_write_prom_atomic()
int watch_write_prom_atomic (const char * path, const watch_sample * samples, int n, brix_status * st)
Definition at line 259 of file diag_watch.c.
References brix_status_set(), close(), watch_emit_prom(), XRDC_ESOCK, XRDC_EUSAGE, and XRDC_PATH_MAX.
Referenced by do_watch().
Variable Documentation
DX_RULES
const dx_rule DX_RULES[] extern
Definition at line 13 of file xrddiag.c.
Referenced by dx_record_status().
g_fails
int g_fails extern
Definition at line 11 of file xrddiag.c.
Referenced by do_check(), do_compare(), do_compare_davs(), do_probe_robustness(), do_topology(), and probe().
g_watch_stop
volatile sig_atomic_t g_watch_stop extern
Definition at line 75 of file xrddiag.c.
Referenced by do_watch(), watch_on_signal(), and watch_sleep().