nginx-xrootd: client/apps/diag/diag_bench.c File Reference
diag_bench.c File Reference
#include "diag_internal.h"
Functions
double bench_one (brix_conn *c, const char *target, brix_status *st)
void bench_sweep (brix_conn *c, const char *target)
int do_bench (const diag_args *a)
Function Documentation
bench_one()
double bench_one (brix_conn * c, const char * target, brix_status * st)
Definition at line 11 of file diag_bench.c.
References brix_mono_ns(), brix_status_set(), c, close(), download_to_fd(), and XRDC_ESOCK.
Referenced by do_bench().
bench_sweep()
void bench_sweep (brix_conn * c, const char * target)
Definition at line 48 of file diag_bench.c.
References brix_file_close(), brix_file_open_read(), brix_file_read(), brix_mono_ns(), brix_status_clear(), c, and brix_status::msg.
Referenced by do_bench().
do_bench()
int do_bench (const diag_args * a)
Definition at line 94 of file diag_bench.c.
References bench_one(), bench_sweep(), brix_close(), brix_connect(), brix_copy(), brix_endpoint_parse(), brix_mono_ns(), brix_netdiag_report(), brix_shellcode(), brix_status_clear(), brix_timing_report(), c, close(), diag_args::conn, brix_copy_opts::force, brix_url::host, brix_status::msg, brix_url::port, resolve_target(), brix_copy_opts::silent, brix_statinfo::size, diag_args::streams, brix_copy_opts::streams, diag_args::sweep, diag_args::url, brix_opts::want_tls, and XRDC_PATH_MAX.
Referenced by main().