nginx-xrootd: client/apps/diag/diag_watch.c File Reference
diag_watch.c File Reference
#include "diag_internal.h"
Functions
int do_status (const diag_args *a)
void watch_on_signal (int sig)
int watch_count_tokens (const char *s)
void watch_prom_label (const char *s, char *out, size_t osz)
int watch_probe_once (const diag_args *a, const char *url, watch_sample *out)
void watch_emit_human (const watch_sample *s, FILE *out)
void watch_emit_json (const watch_sample *s, FILE *out)
void watch_emit_prom (const watch_sample *samples, int n, FILE *out)
int watch_write_prom_atomic (const char *path, const watch_sample *samples, int n, brix_status *st)
void watch_sleep (int seconds)
int do_watch (const diag_args *a)
Function Documentation
do_status()
int do_status (const diag_args * a)
Definition at line 11 of file diag_watch.c.
References brix_endpoint_parse(), brix_http_get(), brix_status_clear(), brix_url::host, diag_args::metrics_port, brix_status::msg, and diag_args::url.
Referenced by main().
do_watch()
int do_watch (const diag_args * a)
Definition at line 307 of file diag_watch.c.
References brix_status_clear(), diag_args::count, g_watch_stop, diag_args::interval_s, diag_args::json, brix_status::msg, diag_args::nurls, diag_args::prom_path, diag_args::urls, watch_emit_human(), watch_emit_json(), watch_emit_prom(), watch_on_signal(), watch_probe_once(), diag_args::watch_prom, watch_sleep(), and watch_write_prom_atomic().
Referenced by main().
watch_count_tokens()
int watch_count_tokens (const char * s)
Definition at line 75 of file diag_watch.c.
References s.
Referenced by watch_probe_once().
watch_emit_human()
void watch_emit_human (const watch_sample * s, FILE * out)
Definition at line 185 of file diag_watch.c.
References s.
Referenced by do_watch().
watch_emit_json()
void watch_emit_json (const watch_sample * s, FILE * out)
Definition at line 199 of file diag_watch.c.
References fjson_str(), and s.
Referenced by do_watch().
watch_emit_prom()
void watch_emit_prom (const watch_sample * samples, int n, FILE * out)
Definition at line 213 of file diag_watch.c.
References watch_prom_label().
Referenced by do_watch(), and watch_write_prom_atomic().
watch_on_signal()
void watch_on_signal (int sig)
Definition at line 65 of file diag_watch.c.
References g_watch_stop.
Referenced by do_watch().
watch_probe_once()
int watch_probe_once (const diag_args * a, const char * url, watch_sample * out)
Definition at line 109 of file diag_watch.c.
References watch_sample::auth_ms, brix_netfacts::auth_ms, brix_close(), brix_connect(), brix_endpoint_parse(), brix_file_close(), brix_file_open_read(), brix_file_read(), brix_locate(), brix_mono_ns(), brix_netdiag_facts(), brix_status_clear(), brix_tls_info(), c, diag_args::conn, watch_sample::connect_ms, watch_sample::endpoint, watch_sample::holders, brix_url::host, watch_sample::locate_ms, brix_url::port, diag_args::probe_timeout_ms, watch_sample::proto, watch_sample::read_ms, resolve_target(), brix_url::scheme, watch_sample::tcp_ms, brix_netfacts::tcp_ms, watch_sample::tls_active, watch_sample::tls_ms, brix_netfacts::tls_ms, watch_sample::up, watch_count_tokens(), XRDC_PATH_MAX, and XRDC_SCHEME_ROOTS.
Referenced by do_watch().
watch_prom_label()
void watch_prom_label (const char * s, char * out, size_t osz)
Definition at line 91 of file diag_watch.c.
References s.
Referenced by watch_emit_prom().
watch_sleep()
void watch_sleep (int seconds)
Definition at line 296 of file diag_watch.c.
References g_watch_stop.
Referenced by do_watch().
watch_write_prom_atomic()
int watch_write_prom_atomic (const char * path, const watch_sample * samples, int n, brix_status * st)
Definition at line 259 of file diag_watch.c.
References brix_status_set(), close(), watch_emit_prom(), XRDC_ESOCK, XRDC_EUSAGE, and XRDC_PATH_MAX.
Referenced by do_watch().