nginx-xrootd: src/protocols/dig/dig.c File Reference
dig.c File Reference
#include "dig.h"
#include "protocols/webdav/webdav.h"
#include "fs/path/beneath.h"
#include "fs/vfs/vfs.h"
#include "core/compat/cstr.h"
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include <sys/stat.h>
Data Structures
struct dig_req_t
Functions
static const char * dig_principal (ngx_http_brix_webdav_req_ctx_t *ctx)
static ngx_int_t dig_authorize (const char *authfile, const char *principal, const char *export)
static ngx_int_t dig_open_status (int err)
static ngx_int_t dig_precheck (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t dig_parse_target (ngx_http_request_t *r, dig_req_t *req)
static ngx_int_t dig_match_export (ngx_http_brix_webdav_loc_conf_t *conf, dig_req_t *req)
static ngx_int_t dig_authz (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, dig_req_t *req)
static ngx_int_t dig_open_confined (ngx_http_request_t *r, dig_req_t *req)
static ngx_int_t dig_register_fd_cleanup (ngx_http_request_t *r, int fd)
static ngx_int_t dig_send_response (ngx_http_request_t *r, dig_req_t *req)
ngx_int_t brix_dig_handle (ngx_http_request_t *r)
Function Documentation
brix_dig_handle()
ngx_int_t brix_dig_handle (ngx_http_request_t * r)
Definition at line 425 of file dig.c.
References dig_authz(), dig_match_export(), dig_open_confined(), dig_parse_target(), dig_precheck(), dig_register_fd_cleanup(), dig_send_response(), dig_req_t::fd, and ngx_http_brix_webdav_module.
Referenced by webdav_dispatch_macaroon().
dig_authorize()
static ngx_int_t dig_authorize (const char * authfile, const char * principal, const char * export) static
Definition at line 58 of file dig.c.
References close(), and open().
Referenced by dig_authz().
dig_authz()
static ngx_int_t dig_authz (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, dig_req_t * req) static
Definition at line 255 of file dig.c.
References ngx_http_brix_webdav_loc_conf_t::dig_auth_file, dig_authorize(), dig_principal(), dig_req_t::export, and ngx_http_brix_webdav_module.
Referenced by brix_dig_handle().
dig_match_export()
static ngx_int_t dig_match_export (ngx_http_brix_webdav_loc_conf_t * conf, dig_req_t * req) static
Definition at line 222 of file dig.c.
References ngx_http_brix_webdav_loc_conf_t::dig_exports, dig_req_t::export, dig_req_t::match, and name.
Referenced by brix_dig_handle().
dig_open_confined()
static ngx_int_t dig_open_confined (ngx_http_request_t * r, dig_req_t * req) static
Definition at line 286 of file dig.c.
References BRIX_PROTO_WEBDAV, brix_str_cbuf(), brix_vfs_close(), brix_vfs_ctx_init(), brix_vfs_file_sendfile_fd(), brix_vfs_file_stat(), BRIX_VFS_O_READ, brix_vfs_open(), brix_dig_export_t::canon, dig_open_status(), dig_req_t::fd, dig_req_t::fh, brix_vfs_stat_t::is_regular, dig_req_t::match, PATH_MAX, brix_vfs_ctx_t::pool, dig_req_t::rel, and dig_req_t::vst.
Referenced by brix_dig_handle().
dig_open_status()
static ngx_int_t dig_open_status (int err) static
Definition at line 115 of file dig.c.
Referenced by dig_open_confined().
dig_parse_target()
static ngx_int_t dig_parse_target (ngx_http_request_t * r, dig_req_t * req) static
Definition at line 187 of file dig.c.
References BRIX_DIG_PREFIX_LEN, dig_req_t::export, ngx_memcpy, and dig_req_t::rel.
Referenced by brix_dig_handle().
dig_precheck()
static ngx_int_t dig_precheck (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 159 of file dig.c.
References BRIX_DIG_PREFIX, BRIX_DIG_PREFIX_LEN, and ngx_http_brix_webdav_loc_conf_t::dig_enable.
Referenced by brix_dig_handle().
dig_principal()
static const char * dig_principal (ngx_http_brix_webdav_req_ctx_t * ctx) static
Definition at line 31 of file dig.c.
References brix_identity_dn_cstr(), brix_identity_subject_cstr(), and ngx_http_brix_webdav_req_ctx_t::identity.
Referenced by dig_authz().
dig_register_fd_cleanup()
static ngx_int_t dig_register_fd_cleanup (ngx_http_request_t * r, int fd) static
Definition at line 343 of file dig.c.
References close().
Referenced by brix_dig_handle().
dig_send_response()
static ngx_int_t dig_send_response (ngx_http_request_t * r, dig_req_t * req) static
Definition at line 373 of file dig.c.
References dig_req_t::fd, brix_vfs_stat_t::mtime, ngx_pcalloc(), brix_vfs_stat_t::size, and dig_req_t::vst.
Referenced by brix_dig_handle().