var dir_20685cc71c68f4040201d94d3a392639 =
[
    [ "clone.c", "clone_8c.html", "clone_8c" ],
    [ "clone.h", "clone_8h.html", "clone_8h" ],
    [ "close.c", "close_8c.html", "close_8c" ],
    [ "close.h", "close_8h.html", "close_8h" ],
    [ "locate.c", "locate_8c.html", "locate_8c" ],
    [ "locate.h", "locate_8h.html", "locate_8h" ],
    [ "open.h", "protocols_2root_2read_2open_8h.html", "protocols_2root_2read_2open_8h" ],
    [ "open_cache.c", "open__cache_8c.html", "open__cache_8c" ],
    [ "open_overview.c", "open__overview_8c.html", "open__overview_8c" ],
    [ "open_request.c", "open__request_8c.html", "open__request_8c" ],
    [ "open_resolved_file.c", "open__resolved__file_8c.html", "open__resolved__file_8c" ],
    [ "pgread.c", "pgread_8c.html", "pgread_8c" ],
    [ "prefetch.c", "prefetch_8c.html", "prefetch_8c" ],
    [ "prefetch.h", "prefetch_8h.html", "prefetch_8h" ],
    [ "read.c", "read_8c.html", "read_8c" ],
    [ "read.h", "read_8h.html", "read_8h" ],
    [ "read_compress.c", "read__compress_8c.html", "read__compress_8c" ],
    [ "readv.c", "protocols_2root_2read_2readv_8c.html", "protocols_2root_2read_2readv_8c" ],
    [ "stat.c", "stat_8c.html", "stat_8c" ],
    [ "stat.h", "stat_8h.html", "stat_8h" ],
    [ "statx.c", "statx_8c.html", "statx_8c" ],
    [ "statx.h", "statx_8h.html", "statx_8h" ]
];