var dir_811f7f270fed05af692d0fe417b1df94 =
[
    [ "api.c", "api_8c.html", "api_8c" ],
    [ "api_admin.c", "api__admin_8c.html", "api__admin_8c" ],
    [ "api_admin.h", "api__admin_8h.html", "api__admin_8h" ],
    [ "api_admin_cluster.c", "api__admin__cluster_8c.html", "api__admin__cluster_8c" ],
    [ "api_admin_config.c", "api__admin__config_8c.html", "api__admin__config_8c" ],
    [ "api_admin_proxy.c", "api__admin__proxy_8c.html", "api__admin__proxy_8c" ],
    [ "api_cvmfs.c", "api__cvmfs_8c.html", "api__cvmfs_8c" ],
    [ "api_ratelimit.c", "api__ratelimit_8c.html", "api__ratelimit_8c" ],
    [ "api_snapshot.c", "api__snapshot_8c.html", "api__snapshot_8c" ],
    [ "api_transfers.c", "api__transfers_8c.html", "api__transfers_8c" ],
    [ "auth.c", "src_2observability_2dashboard_2auth_8c.html", "src_2observability_2dashboard_2auth_8c" ],
    [ "config.c", "observability_2dashboard_2config_8c.html", "observability_2dashboard_2config_8c" ],
    [ "config_download.c", "config__download_8c.html", "config__download_8c" ],
    [ "dashboard.h", "dashboard_8h.html", "dashboard_8h" ],
    [ "dashboard_api_admin_internal.h", "dashboard__api__admin__internal_8h.html", "dashboard__api__admin__internal_8h" ],
    [ "dashboard_api_internal.h", "dashboard__api__internal_8h.html", "dashboard__api__internal_8h" ],
    [ "dashboard_http.h", "dashboard__http_8h.html", "dashboard__http_8h" ],
    [ "dashboard_json.c", "dashboard__json_8c.html", "dashboard__json_8c" ],
    [ "dashboard_json.h", "dashboard__json_8h.html", "dashboard__json_8h" ],
    [ "dashboard_tracking.h", "dashboard__tracking_8h.html", "dashboard__tracking_8h" ],
    [ "events.c", "observability_2dashboard_2events_8c.html", "observability_2dashboard_2events_8c" ],
    [ "files.c", "files_8c.html", "files_8c" ],
    [ "history.c", "history_8c.html", "history_8c" ],
    [ "http_tracking.c", "http__tracking_8c.html", "http__tracking_8c" ],
    [ "module.c", "observability_2dashboard_2module_8c.html", "observability_2dashboard_2module_8c" ],
    [ "noop.c", "observability_2dashboard_2noop_8c.html", "observability_2dashboard_2noop_8c" ],
    [ "page.c", "page_8c.html", "page_8c" ],
    [ "transfer_table.c", "transfer__table_8c.html", "transfer__table_8c" ],
    [ "vfs_browse.c", "vfs__browse_8c.html", "vfs__browse_8c" ]
];