var dir_b332ff67b152d1acb2bc2582dbb3acda =
[
    [ "directives_mirror.h", "directives__mirror_8h.html", null ],
    [ "directives_registry.h", "directives__registry_8h.html", null ],
    [ "oci.h", "oci_8h.html", "oci_8h" ],
    [ "oci_authz.c", "oci__authz_8c.html", "oci__authz_8c" ],
    [ "oci_classify.c", "oci__classify_8c.html", "oci__classify_8c" ],
    [ "oci_classify.h", "oci__classify_8h.html", "oci__classify_8h" ],
    [ "oci_delegate.c", "oci__delegate_8c.html", "oci__delegate_8c" ],
    [ "oci_errors.c", "oci__errors_8c.html", "oci__errors_8c" ],
    [ "oci_gate.c", "oci__gate_8c.html", "oci__gate_8c" ],
    [ "oci_gc.c", "oci__gc_8c.html", "oci__gc_8c" ],
    [ "oci_key.c", "oci__key_8c.html", "oci__key_8c" ],
    [ "oci_manifest_put.c", "oci__manifest__put_8c.html", "oci__manifest__put_8c" ],
    [ "oci_merge.c", "oci__merge_8c.html", "oci__merge_8c" ],
    [ "oci_meta.c", "oci__meta_8c.html", "oci__meta_8c" ],
    [ "oci_mirror.c", "oci__mirror_8c.html", "oci__mirror_8c" ],
    [ "oci_module.c", "oci__module_8c.html", "oci__module_8c" ],
    [ "oci_module_internal.h", "oci__module__internal_8h.html", "oci__module__internal_8h" ],
    [ "oci_present.c", "oci__present_8c.html", "oci__present_8c" ],
    [ "oci_referrers.c", "oci__referrers_8c.html", "oci__referrers_8c" ],
    [ "oci_referrers.h", "oci__referrers_8h.html", "oci__referrers_8h" ],
    [ "oci_registry.c", "oci__registry_8c.html", "oci__registry_8c" ],
    [ "oci_registry.h", "oci__registry_8h.html", "oci__registry_8h" ],
    [ "oci_store.c", "oci__store_8c.html", "oci__store_8c" ],
    [ "oci_tags.c", "oci__tags_8c.html", "oci__tags_8c" ],
    [ "oci_token_cache.c", "oci__token__cache_8c.html", "oci__token__cache_8c" ],
    [ "oci_upload.c", "oci__upload_8c.html", "oci__upload_8c" ],
    [ "oci_upload_internal.h", "oci__upload__internal_8h.html", "oci__upload__internal_8h" ],
    [ "oci_upload_seal.c", "oci__upload__seal_8c.html", "oci__upload__seal_8c" ],
    [ "oci_upstream_auth.c", "oci__upstream__auth_8c.html", "oci__upstream__auth_8c" ]
];