var dir_f3332be28e8ee555e12d73d9c45578ed =
[
    [ "aio_wrapper.c", "darwin_2aio__wrapper_8c.html", "darwin_2aio__wrapper_8c" ],
    [ "apple_silicon.c", "apple__silicon_8c.html", null ],
    [ "checksum_accelerate.c", "checksum__accelerate_8c.html", null ],
    [ "clonefile_optimized.c", "clonefile__optimized_8c.html", null ],
    [ "copy_range.c", "platform_2darwin_2copy__range_8c.html", "platform_2darwin_2copy__range_8c" ],
    [ "cpu_cache.h", "cpu__cache_8h.html", "cpu__cache_8h" ],
    [ "cpu_topology.c", "cpu__topology_8c.html", null ],
    [ "cpu_topology_unittest.c", "cpu__topology__unittest_8c.html", "cpu__topology__unittest_8c" ],
    [ "event_wrapper.c", "darwin_2event__wrapper_8c.html", "darwin_2event__wrapper_8c" ],
    [ "fs_watcher.c", "darwin_2fs__watcher_8c.html", "darwin_2fs__watcher_8c" ],
    [ "host.h", "src_2platform_2darwin_2host_8h.html", "src_2platform_2darwin_2host_8h" ],
    [ "host_api.h", "darwin_2host__api_8h.html", null ],
    [ "host_endian.h", "darwin_2host__endian_8h.html", "darwin_2host__endian_8h" ],
    [ "host_info.c", "darwin_2host__info_8c.html", null ],
    [ "host_posix.h", "darwin_2host__posix_8h.html", "darwin_2host__posix_8h" ],
    [ "path_wrapper.c", "darwin_2path__wrapper_8c.html", null ],
    [ "posix_wrapper.c", "darwin_2posix__wrapper_8c.html", "darwin_2posix__wrapper_8c" ],
    [ "priv_wrapper.c", "darwin_2priv__wrapper_8c.html", null ],
    [ "process_wrapper.c", "darwin_2process__wrapper_8c.html", "darwin_2process__wrapper_8c" ],
    [ "security_wrapper.c", "darwin_2security__wrapper_8c.html", "darwin_2security__wrapper_8c" ],
    [ "storage_wrapper.c", "darwin_2storage__wrapper_8c.html", null ],
    [ "sysctl_value.h", "sysctl__value_8h.html", "sysctl__value_8h" ]
];