var dir_077ac7c5718cd11a37d5ae62d190a061 =
[
    [ "connect_lifecycle.c", "connect__lifecycle_8c.html", "connect__lifecycle_8c" ],
    [ "connect_upstream.c", "connect__upstream_8c.html", "connect__upstream_8c" ],
    [ "directives.c", "net_2proxy_2directives_8c.html", "net_2proxy_2directives_8c" ],
    [ "events_bootstrap.c", "events__bootstrap_8c.html", "events__bootstrap_8c" ],
    [ "events_bootstrap_auth.c", "events__bootstrap__auth_8c.html", "events__bootstrap__auth_8c" ],
    [ "events_bootstrap_internal.h", "events__bootstrap__internal_8h.html", "events__bootstrap__internal_8h" ],
    [ "events_read.c", "events__read_8c.html", "events__read_8c" ],
    [ "events_splice.c", "events__splice_8c.html", null ],
    [ "events_write.c", "events__write_8c.html", "events__write_8c" ],
    [ "forward_fh_translate.c", "forward__fh__translate_8c.html", "forward__fh__translate_8c" ],
    [ "forward_relay_audit.c", "forward__relay__audit_8c.html", "forward__relay__audit_8c" ],
    [ "forward_relay_dispatch.c", "forward__relay__dispatch_8c.html", "forward__relay__dispatch_8c" ],
    [ "forward_relay_response.c", "forward__relay__response_8c.html", "forward__relay__response_8c" ],
    [ "forward_relay_response_internal.h", "forward__relay__response__internal_8h.html", "forward__relay__response__internal_8h" ],
    [ "forward_relay_response_lazy.c", "forward__relay__response__lazy_8c.html", "forward__relay__response__lazy_8c" ],
    [ "forward_request.c", "forward__request_8c.html", "forward__request_8c" ],
    [ "forward_rewrite_helpers.c", "forward__rewrite__helpers_8c.html", "forward__rewrite__helpers_8c" ],
    [ "forward_session_helpers.c", "forward__session__helpers_8c.html", "forward__session__helpers_8c" ],
    [ "gsi_upstream.c", "gsi__upstream_8c.html", "gsi__upstream_8c" ],
    [ "gsi_upstream.h", "gsi__upstream_8h.html", "gsi__upstream_8h" ],
    [ "gsi_upstream_login.c", "gsi__upstream__login_8c.html", "gsi__upstream__login_8c" ],
    [ "pool.c", "src_2net_2proxy_2pool_8c.html", "src_2net_2proxy_2pool_8c" ],
    [ "proxy.h", "proxy_8h.html", "proxy_8h" ],
    [ "proxy_internal.h", "net_2proxy_2proxy__internal_8h.html", "net_2proxy_2proxy__internal_8h" ]
];