nginx-xrootd: src/fs/cache/directives_wt.c File Reference
directives_wt.c File Reference
#include "core/config/config.h"
#include <errno.h>
#include <regex.h>
#include <stdlib.h>
#include <string.h>
#include "core/compat/alloc_guard.h"
#include "core/compat/str_dup.h"
#include "core/compat/checksum.h"
#include "core/compat/af_policy.h"
#include "verify.h"
#include "core/compat/cstr.h"
#include "cache_internal.h"
Functions
char * brix_conf_set_wt_enable (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_wt_mode (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_wt_origin (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static char * brix_conf_add_wt_prefix (ngx_conf_t *cf, ngx_command_t *cmd, void *conf, int is_deny)
char * brix_conf_set_wt_deny_prefix (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_wt_allow_prefix (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Function Documentation
brix_conf_add_wt_prefix()
static char * brix_conf_add_wt_prefix (ngx_conf_t * cf, ngx_command_t * cmd, void * conf, int is_deny) static
Definition at line 171 of file directives_wt.c.
References brix_conf_push_prefix().
Referenced by brix_conf_set_wt_allow_prefix(), and brix_conf_set_wt_deny_prefix().
brix_conf_set_wt_allow_prefix()
char * brix_conf_set_wt_allow_prefix (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 193 of file directives_wt.c.
References brix_conf_add_wt_prefix().
brix_conf_set_wt_deny_prefix()
char * brix_conf_set_wt_deny_prefix (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 184 of file directives_wt.c.
References brix_conf_add_wt_prefix().
brix_conf_set_wt_enable()
char * brix_conf_set_wt_enable (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 28 of file directives_wt.c.
brix_conf_set_wt_mode()
char * brix_conf_set_wt_mode (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 59 of file directives_wt.c.
References BRIX_WT_MODE_ASYNC, and BRIX_WT_MODE_SYNC.
brix_conf_set_wt_origin()
char * brix_conf_set_wt_origin (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 88 of file directives_wt.c.
References BRIX_PNALLOC_OR_RETURN, brix_pstrdupz(), and ngx_memcpy.