nginx-xrootd: src/protocols/root/dirlist/dirlist.h File Reference
dirlist.h File Reference
#include "core/ngx_brix_module.h"
Functions
ngx_int_t brix_handle_dirlist (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_handle_dirlist()
ngx_int_t brix_handle_dirlist (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 71 of file handler.c.
References brix_vfs_stat_t::blocks, brix_auth_gate(), BRIX_AUTH_LOOKUP, brix_beneath_full_path(), brix_build_resp_hdr(), brix_dirlist_checksum_algorithm(), brix_dirlist_checksum_token(), brix_dirlist_make_dcksm_stat_body(), brix_dirlist_name_is_unsafe(), BRIX_DSTAT_LEADIN, BRIX_DSTAT_LEADIN_LEN, brix_extract_path(), brix_find_manager_map(), brix_is_internal_name(), brix_log_access(), brix_make_stat_body(), BRIX_MAX_CONN_POOL_BYTES, BRIX_MAX_PATH, BRIX_OP_DIRLIST, BRIX_OP_ERR, BRIX_OP_OK, BRIX_PROTO_ROOT, brix_queue_response(), brix_reject_dotdot_path(), BRIX_RETURN_ERR, BRIX_RETURN_REDIR, brix_sanitize_log_string(), brix_send_error(), brix_srv_select(), brix_vfs_closedir(), brix_vfs_ctx_init(), brix_vfs_dir_fd(), brix_vfs_opendir(), brix_vfs_readdir(), c, ngx_stream_brix_srv_conf_t::common, brix_vfs_stat_t::ctime, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_streamid, brix_vfs_stat_t::dev, brix_vfs_stat_t::gid, brix_ctx_recv_t::hdr_buf, brix_manager_map_t::host, brix_vfs_stat_t::ino, kXR_ArgInvalid, kXR_ArgMissing, kXR_dcksm, kXR_dstat, kXR_IOError, kXR_NoMemory, kXR_NotFile, kXR_NotFound, kXR_ok, kXR_oksofar, kXR_Overloaded, kXR_ServerError, brix_ctx_t::login, ngx_stream_brix_srv_conf_t::manager_map, ngx_stream_brix_srv_conf_t::manager_mode, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, name, ngx_memcpy, xrdw_dirlist_req_t::options, PATH_MAX, brix_ctx_recv_t::payload, brix_vfs_ctx_t::pool, brix_ctx_login_t::pool_bytes_used, brix_manager_map_t::port, brix_ctx_t::recv, ngx_http_brix_shared_conf_t::root_canon, brix_vfs_stat_t::size, stat(), brix_vfs_stat_t::uid, brix_ctx_t::write_rc, XRD_RESPONSE_HDR_LEN, and xrdw_dirlist_req_unpack().
Referenced by brix_dispatch_read_opcode().