nginx-xrootd: src/core/aio/dirlist.c File Reference
dirlist.c File Reference
#include "core/ngx_brix_module.h"
#include "protocols/root/dirlist/dcksm.h"
#include "fs/path/path.h"
#include "protocols/root/response/response.h"
#include "aio.h"
#include "core/compat/error_mapping.h"
#include <dirent.h>
#include <fcntl.h>
#include <string.h>
#include <errno.h>
#include <sys/stat.h>
#include <openssl/evp.h>
Macros
#define DIRLIST_CHUNK_CAP 65536UL
Functions
void brix_dirlist_aio_thread (void *data, ngx_log_t *log)
void brix_dirlist_aio_done (ngx_event_t *ev)
Macro Definition Documentation
DIRLIST_CHUNK_CAP
#define DIRLIST_CHUNK_CAP 65536UL
Definition at line 65 of file dirlist.c.
Function Documentation
brix_dirlist_aio_done()
void brix_dirlist_aio_done (ngx_event_t * ev)
Definition at line 114 of file dirlist.c.
References brix_aio_restore_request(), brix_aio_resume(), brix_kxr_from_errno(), brix_log_access(), BRIX_OP_DIRLIST, BRIX_OP_ERR, BRIX_OP_OK, brix_queue_response_base(), brix_release_read_buffer(), brix_send_error(), c, brix_dirlist_aio_t::c, brix_dirlist_aio_t::ctx, brix_dirlist_aio_t::err_msg, brix_dirlist_aio_t::io_errno, brix_dirlist_aio_t::resolved, brix_dirlist_aio_t::response, brix_dirlist_aio_t::response_len, brix_ctx_t::state, brix_dirlist_aio_t::streamid, brix_dirlist_aio_t::want_cksum, brix_dirlist_aio_t::want_stat, and XRD_ST_SENDING.
brix_dirlist_aio_thread()
void brix_dirlist_aio_thread (void * data, ngx_log_t * log)
Definition at line 76 of file dirlist.c.
References brix_vfs_io_execute(), brix_vfs_job_opendir_init(), brix_dirlist_aio_t::cksum_algo, close(), brix_dirlist_aio_t::ctx, brix_dirlist_aio_t::dirfd, brix_dirlist_aio_t::err_msg, brix_dirlist_aio_t::io_errno, brix_vfs_job_t::io_errno, log, brix_vfs_job_t::out_size, brix_dirlist_aio_t::resolved, brix_dirlist_aio_t::response, brix_dirlist_aio_t::response_cap, brix_dirlist_aio_t::response_len, brix_dirlist_aio_t::streamid, brix_dirlist_aio_t::want_cksum, and brix_dirlist_aio_t::want_stat.