nginx-xrootd: src/protocols/root/connection/disconnect.h File Reference
disconnect.h File Reference
#include "core/ngx_brix_module.h"
Functions
void brix_on_disconnect (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_flag_t brix_defer_teardown_if_writing (brix_ctx_t *ctx, ngx_connection_t *c, ngx_int_t status)
void brix_run_deferred_teardown (brix_ctx_t *ctx, ngx_connection_t *c)
Function Documentation
brix_defer_teardown_if_writing()
ngx_flag_t brix_defer_teardown_if_writing (brix_ctx_t * ctx, ngx_connection_t * c, ngx_int_t status)
Definition at line 314 of file disconnect.c.
References brix_disconnect_disarm_deadline_timers(), c, brix_ctx_t::destroyed, brix_ctx_out_t::finalize_pending, brix_ctx_out_t::finalize_status, brix_ctx_t::out, and brix_ctx_out_t::wr_inflight.
Referenced by brix_aio_resume_fail(), brix_recv_pre_loop(), brix_recv_read_frame(), ngx_stream_brix_recv(), and ngx_stream_brix_send().
brix_on_disconnect()
void brix_on_disconnect (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 201 of file disconnect.c.
References brix_ctx_login_t::auth_done, brix_access_log_flush(), brix_budget_release(), brix_disconnect_disarm_deadline_timers(), brix_disconnect_end_pmark(), brix_disconnect_format_session_detail(), brix_disconnect_log_open_files(), brix_disconnect_release_throttle_slots(), brix_disconnect_sess_reason(), brix_disconnect_update_metrics(), brix_gsi_inflight_release(), brix_log_access(), brix_proxy_cleanup(), brix_release_disconnect_crypto_state(), brix_release_disconnect_owned_buffers(), brix_rl_release_ctx(), brix_sess_end(), brix_session_unregister(), brix_transfer_slot_free_all_for_session(), brix_upstream_cleanup(), c, brix_ctx_t::destroyed, brix_ctx_t::is_bound, brix_ctx_login_t::logged_in, brix_ctx_t::login, ngx_brix_dashboard_shm_zone, brix_ctx_t::proxy, brix_ctx_t::req_start, brix_ctx_t::sess, brix_ctx_login_t::sessid, brix_ctx_totals_t::start, brix_ctx_t::totals, and brix_ctx_t::upstream.
Referenced by brix_aio_resume_fail(), brix_handle_endsess(), brix_recv_header_prep(), brix_recv_pre_loop(), brix_recv_read_frame(), brix_run_deferred_teardown(), brix_start_tls(), brix_tls_handshake_done(), ngx_stream_brix_recv(), and ngx_stream_brix_send().
brix_run_deferred_teardown()
void brix_run_deferred_teardown (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 341 of file disconnect.c.
References brix_close_all_files(), brix_on_disconnect(), c, brix_ctx_out_t::finalize_pending, brix_ctx_out_t::finalize_status, brix_ctx_t::out, and s.
Referenced by brix_write_aio_done(), and brix_write_aio_done_pipelined().