nginx-xrootd: src/protocols/root/connection/disconnect_report.c File Reference
disconnect_report.c File Reference
#include "disconnect.h"
#include "disconnect_internal.h"
#include "fd_table.h"
#include "budget.h"
#include "protocols/root/session/session.h"
#include "protocols/root/session/registry.h"
#include "net/upstream/upstream.h"
#include "net/proxy/proxy.h"
#include "net/ratelimit/ratelimit.h"
#include "net/ratelimit/throttle_compat.h"
#include "net/mirror/stream_wmirror.h"
#include "observability/sesslog/sesslog_ngx.h"
#include "core/aio/uring.h"
#include <ngx_event.h>
#include <ngx_stream.h>
#include <stdio.h>
#include <string.h>
Functions
void brix_disconnect_update_metrics (brix_ctx_t *ctx)
static size_t brix_disconnect_file_bytes (const brix_file_t *file)
brix_sess_end_t brix_disconnect_sess_reason (brix_ctx_t *ctx, ngx_connection_t *c)
void brix_disconnect_log_open_files (brix_ctx_t *ctx, ngx_connection_t *c, ngx_msec_t now)
void brix_disconnect_format_session_detail (brix_ctx_t *ctx, ngx_msec_t now, char *detail, size_t detail_size, size_t *total_bytes)
Function Documentation
brix_disconnect_file_bytes()
static size_t brix_disconnect_file_bytes (const brix_file_t * file) static
Definition at line 86 of file disconnect_report.c.
References brix_file_t::bytes_read, and brix_file_t::bytes_written.
Referenced by brix_disconnect_log_open_files().
brix_disconnect_format_session_detail()
void brix_disconnect_format_session_detail (brix_ctx_t * ctx, ngx_msec_t now, char * detail, size_t detail_size, size_t * total_bytes)
Definition at line 183 of file disconnect_report.c.
References brix_ctx_totals_t::bytes, brix_ctx_totals_t::bytes_written, brix_ctx_totals_t::start, and brix_ctx_t::totals.
Referenced by brix_on_disconnect().
brix_disconnect_log_open_files()
void brix_disconnect_log_open_files (brix_ctx_t * ctx, ngx_connection_t * c, ngx_msec_t now)
Definition at line 131 of file disconnect_report.c.
References brix_sess_xfer_t::active, brix_disconnect_file_bytes(), brix_log_access(), BRIX_MAX_FILES, BRIX_SESS_XFER_ABORTED, brix_sess_xfer_add(), brix_sess_xfer_end(), BRIX_SESS_XFER_SHUTDOWN, brix_sess_xfer_t::bytes, c, brix_file_t::fd, brix_ctx_t::files, kXR_Cancelled, brix_file_t::open_time, brix_file_t::path, brix_ctx_t::req_start, brix_ctx_t::sess, and brix_file_t::sess_xfer.
Referenced by brix_on_disconnect().
brix_disconnect_sess_reason()
brix_sess_end_t brix_disconnect_sess_reason (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 108 of file disconnect_report.c.
References BRIX_SESS_END_CLIENT, BRIX_SESS_END_ERROR, BRIX_SESS_END_SHUTDOWN, BRIX_SESS_END_TIMEOUT, c, brix_ctx_t::sess_end_hint, and brix_ctx_t::sess_end_hint_set.
Referenced by brix_on_disconnect().
brix_disconnect_update_metrics()
void brix_disconnect_update_metrics (brix_ctx_t * ctx)
Definition at line 46 of file disconnect_report.c.
References brix_ctx_totals_t::bytes, ngx_brix_srv_metrics_t::bytes_rx_ipv4_total, ngx_brix_srv_metrics_t::bytes_rx_ipv6_total, ngx_brix_srv_metrics_t::bytes_rx_total, ngx_brix_srv_metrics_t::bytes_tx_ipv4_total, ngx_brix_srv_metrics_t::bytes_tx_ipv6_total, ngx_brix_srv_metrics_t::bytes_tx_total, brix_ctx_totals_t::bytes_written, ngx_brix_srv_metrics_t::connections_active, brix_ctx_t::ip_version, brix_ctx_t::metrics, ngx_brix_srv_metrics_t::proto_root_bytes_rx_total, ngx_brix_srv_metrics_t::proto_root_bytes_tx_total, brix_ctx_t::protocol_label, and brix_ctx_t::totals.
Referenced by brix_on_disconnect().