nginx-xrootd: src/protocols/root/connection/disconnect.c File Reference
disconnect.c File Reference
#include "disconnect.h"
#include "fd_table.h"
#include "budget.h"
#include "protocols/root/session/session.h"
#include "protocols/root/session/registry.h"
#include "net/upstream/upstream.h"
#include "net/proxy/proxy.h"
#include "net/ratelimit/ratelimit.h"
#include "net/ratelimit/throttle_compat.h"
#include "net/mirror/stream_wmirror.h"
#include <ngx_event.h>
#include <ngx_stream.h>
#include <stdio.h>
#include <string.h>
Functions
void brix_gsi_delegation_cleanup (brix_ctx_t *ctx)
static void brix_release_disconnect_owned_buffers (brix_ctx_t *ctx)
static void brix_release_disconnect_crypto_state (brix_ctx_t *ctx)
static void brix_disconnect_update_metrics (brix_ctx_t *ctx)
static size_t brix_disconnect_file_bytes (const brix_file_t *file)
static void brix_disconnect_log_open_files (brix_ctx_t *ctx, ngx_connection_t *c, ngx_msec_t now)
static void brix_disconnect_format_session_detail (brix_ctx_t *ctx, ngx_msec_t now, char *detail, size_t detail_size, size_t *total_bytes)
void brix_on_disconnect (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_flag_t brix_defer_teardown_if_writing (brix_ctx_t *ctx, ngx_connection_t *c, ngx_int_t status)
void brix_run_deferred_teardown (brix_ctx_t *ctx, ngx_connection_t *c)
Function Documentation
brix_defer_teardown_if_writing()
ngx_flag_t brix_defer_teardown_if_writing (brix_ctx_t * ctx, ngx_connection_t * c, ngx_int_t status)
Definition at line 395 of file disconnect.c.
References c, brix_ctx_t::deadline, brix_ctx_t::destroyed, brix_ctx_out_t::finalize_pending, brix_ctx_out_t::finalize_status, brix_ctx_t::out, brix_ctx_deadline_t::read_armed, brix_ctx_deadline_t::send_armed, and brix_ctx_out_t::wr_inflight.
Referenced by brix_recv_pre_loop(), ngx_stream_brix_recv(), and ngx_stream_brix_send().
brix_disconnect_file_bytes()
static size_t brix_disconnect_file_bytes (const brix_file_t * file) static
Definition at line 161 of file disconnect.c.
References brix_file_t::bytes_read, and brix_file_t::bytes_written.
Referenced by brix_disconnect_log_open_files().
brix_disconnect_format_session_detail()
static void brix_disconnect_format_session_detail (brix_ctx_t * ctx, ngx_msec_t now, char * detail, size_t detail_size, size_t * total_bytes) static
Definition at line 224 of file disconnect.c.
References brix_ctx_totals_t::bytes, brix_ctx_totals_t::bytes_written, brix_ctx_totals_t::start, and brix_ctx_t::totals.
Referenced by brix_on_disconnect().
brix_disconnect_log_open_files()
static void brix_disconnect_log_open_files (brix_ctx_t * ctx, ngx_connection_t * c, ngx_msec_t now) static
Definition at line 180 of file disconnect.c.
References brix_disconnect_file_bytes(), brix_log_access(), BRIX_MAX_FILES, c, brix_file_t::fd, brix_ctx_t::files, kXR_Cancelled, brix_file_t::open_time, brix_file_t::path, and brix_ctx_t::req_start.
Referenced by brix_on_disconnect().
brix_disconnect_update_metrics()
static void brix_disconnect_update_metrics (brix_ctx_t * ctx) static
Definition at line 121 of file disconnect.c.
References brix_ctx_totals_t::bytes, ngx_brix_srv_metrics_t::bytes_rx_ipv4_total, ngx_brix_srv_metrics_t::bytes_rx_ipv6_total, ngx_brix_srv_metrics_t::bytes_rx_total, ngx_brix_srv_metrics_t::bytes_tx_ipv4_total, ngx_brix_srv_metrics_t::bytes_tx_ipv6_total, ngx_brix_srv_metrics_t::bytes_tx_total, brix_ctx_totals_t::bytes_written, ngx_brix_srv_metrics_t::connections_active, brix_ctx_t::ip_version, brix_ctx_t::metrics, ngx_brix_srv_metrics_t::proto_root_bytes_rx_total, ngx_brix_srv_metrics_t::proto_root_bytes_tx_total, brix_ctx_t::protocol_label, and brix_ctx_t::totals.
Referenced by brix_on_disconnect().
brix_gsi_delegation_cleanup()
void brix_gsi_delegation_cleanup (brix_ctx_t * ctx)
Definition at line 121 of file delegation.c.
References brix_ctx_gsi_t::deleg_await, brix_ctx_gsi_t::deleg_chain_len, brix_ctx_gsi_t::deleg_chain_pem, brix_ctx_gsi_t::deleg_proxy_len, brix_ctx_gsi_t::deleg_proxy_pem, brix_ctx_gsi_t::deleg_reqkey, brix_ctx_t::gsi, brix_ctx_gsi_t::sess_key, and brix_ctx_gsi_t::sess_keylen.
Referenced by brix_release_disconnect_crypto_state().
brix_on_disconnect()
void brix_on_disconnect (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 260 of file disconnect.c.
References brix_ctx_login_t::auth_done, brix_access_log_flush(), brix_budget_release(), brix_disconnect_format_session_detail(), brix_disconnect_log_open_files(), brix_disconnect_update_metrics(), brix_gsi_inflight_release(), brix_log_access(), brix_pmark_flow_end(), brix_proxy_cleanup(), brix_release_disconnect_crypto_state(), brix_release_disconnect_owned_buffers(), brix_rl_release_ctx(), brix_session_unregister(), brix_throttle_open_dec(), brix_transfer_slot_free_all_for_session(), brix_upstream_cleanup(), c, brix_ctx_t::deadline, brix_ctx_t::destroyed, brix_ctx_login_t::dn, brix_ctx_pmark_t::echo_ev, brix_ctx_pmark_t::flow, brix_ctx_t::is_bound, brix_ctx_login_t::logged_in, brix_ctx_t::login, ngx_brix_dashboard_shm_zone, ngx_stream_brix_module, brix_ctx_throttle_t::open_held, brix_ctx_t::pmark, brix_ctx_t::proxy, brix_ctx_deadline_t::read_armed, brix_ctx_t::req_start, brix_ctx_deadline_t::send_armed, brix_ctx_login_t::sessid, brix_ctx_totals_t::start, ngx_stream_brix_srv_conf_t::throttle, brix_ctx_t::throttle, brix_ctx_t::totals, brix_ctx_t::upstream, and brix_throttle_conf_t::zone.
Referenced by brix_handle_endsess(), brix_recv_pre_loop(), brix_run_deferred_teardown(), brix_start_tls(), brix_tls_handshake_done(), ngx_stream_brix_recv(), and ngx_stream_brix_send().
brix_release_disconnect_crypto_state()
static void brix_release_disconnect_crypto_state (brix_ctx_t * ctx) static
Definition at line 95 of file disconnect.c.
References brix_gsi_delegation_cleanup(), brix_ctx_gsi_t::dh_key, brix_ctx_t::gsi, brix_ctx_sigver_t::mac, brix_ctx_sigver_t::mac_ctx, and brix_ctx_t::sigver.
Referenced by brix_on_disconnect().
brix_release_disconnect_owned_buffers()
static void brix_release_disconnect_owned_buffers (brix_ctx_t * ctx) static
Definition at line 25 of file disconnect.c.
References brix_stream_wmirror_cleanup(), brix_read_slot_t::buf, brix_ctx_rd_t::cmp_scratch, brix_ctx_rd_t::cmp_scratch_size, brix_read_slot_t::in_use, brix_ctx_rd_t::inflight, brix_ctx_t::out, brix_ctx_prepare_t::paths, brix_ctx_prepare_t::paths_len, brix_ctx_recv_t::payload, brix_ctx_recv_t::payload_buf, brix_ctx_recv_t::payload_buf_size, brix_ctx_out_t::pipeline_depth, brix_ctx_rd_t::pool, brix_ctx_t::prepare, brix_ctx_t::rd, brix_ctx_rd_t::read_hdr_scratch, brix_ctx_rd_t::read_hdr_scratch_size, brix_ctx_rd_t::read_scratch, brix_ctx_rd_t::read_scratch_size, brix_ctx_t::recv, brix_read_slot_t::size, brix_ctx_rd_t::write_scratch, and brix_ctx_rd_t::write_scratch_size.
Referenced by brix_on_disconnect().
brix_run_deferred_teardown()
void brix_run_deferred_teardown (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 429 of file disconnect.c.
References brix_close_all_files(), brix_on_disconnect(), c, brix_ctx_out_t::finalize_pending, brix_ctx_out_t::finalize_status, brix_ctx_t::out, and s.
Referenced by brix_write_aio_done().