nginx-xrootd: src/protocols/root/handshake/dispatch_read.c File Reference
dispatch_read.c File Reference
#include "handshake.h"
#include "protocols/root/read/clone.h"
#include "protocols/root/write/ext_ops.h"
Macros
#define DISPATCH_RD(fn, ...)
#define DISPATCH_RD_BOUND(verb, fn, ...)
Functions
static ngx_int_t brix_reject_bound_nonread_file_op (brix_ctx_t *ctx, ngx_connection_t *c, const char *verb)
ngx_int_t brix_dispatch_read_opcode (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Macro Definition Documentation
DISPATCH_RD
#define DISPATCH_RD (fn, ...)
Value:
    rc = brix_dispatch_require_auth(ctx, c); \
    if (rc != BRIX_DISPATCH_CONTINUE) { return rc; } \
    return fn(ctx, c, ##__VA_ARGS__)
Definition at line 25 of file dispatch_read.c.
DISPATCH_RD_BOUND
#define DISPATCH_RD_BOUND (verb, fn, ...)
Value:
    rc = brix_dispatch_require_auth(ctx, c); \
    if (rc != BRIX_DISPATCH_CONTINUE) { return rc; } \
    rc = brix_reject_bound_nonread_file_op(ctx, c, verb); \
    if (rc != BRIX_DISPATCH_CONTINUE) { return rc; } \
    return fn(ctx, c, ##__VA_ARGS__)
Definition at line 30 of file dispatch_read.c.
Function Documentation
brix_dispatch_read_opcode()
ngx_int_t brix_dispatch_read_opcode (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 44 of file dispatch_read.c.
References BRIX_DISPATCH_CONTINUE, brix_handle_clone(), brix_handle_close(), brix_handle_dirlist(), brix_handle_fattr(), brix_handle_locate(), brix_handle_open(), brix_handle_pgread(), brix_handle_prepare(), brix_handle_query(), brix_handle_read(), brix_handle_readlink(), brix_handle_readv(), brix_handle_stat(), brix_handle_statx(), brix_ctx_recv_t::cur_reqid, DISPATCH_RD, DISPATCH_RD_BOUND, kXR_clone, kXR_close, kXR_dirlist, kXR_fattr, kXR_locate, kXR_open, kXR_pgread, kXR_prepare, kXR_query, kXR_read, kXR_readlink, kXR_readv, kXR_stat, kXR_statx, and brix_ctx_t::recv.
Referenced by brix_dispatch().
brix_reject_bound_nonread_file_op()
static ngx_int_t brix_reject_bound_nonread_file_op (brix_ctx_t * ctx, ngx_connection_t * c, const char * verb) static
Definition at line 9 of file dispatch_read.c.
References BRIX_DISPATCH_CONTINUE, brix_log_access(), brix_send_error(), c, brix_ctx_t::is_bound, and kXR_NotAuthorized.