nginx-xrootd: src/protocols/root/handshake/dispatch_write.c File Reference
dispatch_write.c File Reference
#include "handshake.h"
#include "protocols/root/write/chkpoint.h"
#include "protocols/root/write/ext_ops.h"
#include "net/manager/registry.h"
#include "fs/path/path.h"
#include "protocols/root/response/response.h"
Data Structures
struct brix_wr_route_t
Typedefs
typedef ngx_int_t(* brix_wr_fn2_pt) (brix_ctx_t *ctx, ngx_connection_t *c)
typedef ngx_int_t(* brix_wr_fn3_pt) (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Functions
static ngx_int_t manager_redirect_mutation (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_dispatch_write_opcode (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Variables
static const brix_wr_route_t brix_wr_routes []
Typedef Documentation
brix_wr_fn2_pt
typedef ngx_int_t(* brix_wr_fn2_pt) (brix_ctx_t *ctx, ngx_connection_t *c)
Definition at line 88 of file dispatch_write.c.
brix_wr_fn3_pt
typedef ngx_int_t(* brix_wr_fn3_pt) (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Definition at line 89 of file dispatch_write.c.
Function Documentation
brix_dispatch_write_opcode()
ngx_int_t brix_dispatch_write_opcode (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 127 of file dispatch_write.c.
References BRIX_DISPATCH_CONTINUE, brix_dispatch_require_write(), brix_wr_routes, c, brix_ctx_recv_t::cur_reqid, brix_wr_route_t::fn2, brix_wr_route_t::fn3, manager_redirect_mutation(), brix_wr_route_t::op, and brix_ctx_t::recv.
Referenced by brix_dispatch().
manager_redirect_mutation()
static ngx_int_t manager_redirect_mutation (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf) static
Definition at line 30 of file dispatch_write.c.
References BRIX_DISPATCH_CONTINUE, brix_extract_path(), BRIX_MAX_PATH, brix_send_error(), brix_send_redirect(), brix_srv_select_or_blacklisted(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, kXR_chmod, kXR_FSError, kXR_mkdir, kXR_mv, kXR_rm, kXR_rmdir, kXR_truncate, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by brix_dispatch_write_opcode().
Variable Documentation
brix_wr_routes
const brix_wr_route_t brix_wr_routes[] static
Initial value:
= {
    {  3019  ,    brix_handle_write,    NULL                 },
    {  3026  ,  brix_handle_pgwrite,  NULL                 },
    {  3016  ,     brix_handle_sync,     NULL                 },
    {  3028  , NULL,                 brix_handle_truncate },
    {  3008  ,    NULL,                 brix_handle_mkdir    },
    {  3014  ,       NULL,                 brix_handle_rm       },
    {  3031  ,   brix_handle_writev,   NULL                 },
    {  3015  ,    NULL,                 brix_handle_rmdir    },
    {  3009  ,       NULL,                 brix_handle_mv       },
    {  3002  ,    NULL,                 brix_handle_chmod    },
    {  3012  , NULL,                 brix_handle_chkpoint },
    {  3500  ,  NULL,                 brix_handle_setattr  },
    {  3501  ,  NULL,                 brix_handle_symlink  },
    {  3503  ,     NULL,                 brix_handle_link     },
}
Definition at line 98 of file dispatch_write.c.
Referenced by brix_dispatch_write_opcode().