nginx-xrootd: src/tpc/engine/done.c File Reference
done.c File Reference
#include "tpc_internal.h"
#include "fs/vfs/vfs.h"
#include "observability/sesslog/sesslog_ngx.h"
#include <string.h>
#include <unistd.h>
Functions
static void tpc_sess_finish_pull (brix_tpc_pull_t *t, int ok, brix_sess_end_t why)
static void tpc_done_account (brix_tpc_pull_t *t, int ok, ngx_log_t *log)
static void tpc_done_teardown_dst (brix_tpc_pull_t *t, brix_ctx_t *ctx, int idx, ngx_log_t *log)
static void tpc_done_sync_fail (brix_tpc_pull_t *t, brix_ctx_t *ctx, ngx_connection_t *c, int idx)
static void tpc_done_reply_sync (brix_tpc_pull_t *t, brix_ctx_t *ctx, ngx_connection_t *c, int idx)
static void tpc_done_stat_trailer (brix_tpc_pull_t *t, char *statbuf, size_t buflen)
static void tpc_done_send_open_ok (brix_tpc_pull_t *t, brix_ctx_t *ctx, ngx_connection_t *c, int idx)
static void tpc_done_reply_open (brix_tpc_pull_t *t, brix_ctx_t *ctx, ngx_connection_t *c, int idx)
void brix_tpc_pull_done (ngx_event_t *ev)
Function Documentation
brix_tpc_pull_done()
void brix_tpc_pull_done (ngx_event_t * ev)
Definition at line 323 of file done.c.
References brix_aio_restore_request(), BRIX_SESS_END_ERROR, BRIX_SESS_END_SERVER, BRIX_TPC_REPLY_SYNC, c, brix_tpc_pull_t::c, brix_tpc_pull_t::ctx, brix_tpc_pull_t::fhandle_idx, log, brix_tpc_pull_t::reply_kind, brix_tpc_pull_t::result, brix_tpc_pull_t::streamid, tpc_done_account(), tpc_done_reply_open(), tpc_done_reply_sync(), tpc_done_teardown_dst(), and tpc_sess_finish_pull().
Referenced by brix_tpc_start_pull().
tpc_done_account()
static void tpc_done_account (brix_tpc_pull_t * t, int ok, ngx_log_t * log) static
Definition at line 45 of file done.c.
References BRIX_TPC_DIR_PULL, BRIX_TPC_METRIC_ERROR, BRIX_TPC_METRIC_SUCCESS, brix_tpc_metric_transfer(), BRIX_TPC_PROTO_STREAM, brix_tpc_registry_remove(), brix_tpc_registry_update(), BRIX_TPC_STATE_DONE, BRIX_TPC_STATE_ERROR, brix_tpc_pull_t::bytes_written, log, and brix_tpc_pull_t::transfer_id.
Referenced by brix_tpc_pull_done(), tpc_done_reply_open(), tpc_done_reply_sync(), and tpc_done_sync_fail().
tpc_done_reply_open()
static void tpc_done_reply_open (brix_tpc_pull_t * t, brix_ctx_t * ctx, ngx_connection_t * c, int idx) static
Definition at line 285 of file done.c.
References brix_aio_resume(), brix_log_access(), BRIX_MAX_FILES, BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_OPEN_WR, brix_send_error(), BRIX_SESS_END_ERROR, BRIX_SESS_END_SERVER, c, brix_tpc_pull_t::dst_path, brix_tpc_pull_t::err_msg, brix_ctx_t::files, kXR_ServerError, brix_tpc_pull_t::result, tpc_done_account(), tpc_done_send_open_ok(), tpc_done_teardown_dst(), tpc_sess_finish_pull(), brix_file_t::tpc_transfer_id, and brix_tpc_pull_t::xrd_error.
Referenced by brix_tpc_pull_done().
tpc_done_reply_sync()
static void tpc_done_reply_sync (brix_tpc_pull_t * t, brix_ctx_t * ctx, ngx_connection_t * c, int idx) static
Definition at line 138 of file done.c.
References brix_aio_resume(), brix_log_access(), BRIX_MAX_FILES, BRIX_OP_OK, BRIX_OP_SYNC, brix_send_ok(), BRIX_SESS_END_SERVER, brix_file_t::bytes_written, brix_tpc_pull_t::bytes_written, c, brix_file_t::cached_size, brix_file_t::device, brix_tpc_pull_t::dst_path, brix_file_t::fd, brix_ctx_t::files, fstat(), brix_file_t::inode, brix_file_t::is_regular, brix_tpc_pull_t::result, stat(), brix_file_t::tpc_done, tpc_done_account(), tpc_done_sync_fail(), tpc_sess_finish_pull(), brix_file_t::tpc_started, and brix_file_t::tpc_transfer_id.
Referenced by brix_tpc_pull_done().
tpc_done_send_open_ok()
static void tpc_done_send_open_ok (brix_tpc_pull_t * t, brix_ctx_t * ctx, ngx_connection_t * c, int idx) static
Definition at line 234 of file done.c.
References brix_aio_resume(), brix_build_resp_hdr(), brix_queue_response(), brix_send_error(), c, ServerOpenBody::fhandle, kXR_NoMemory, kXR_ok, ngx_memcpy, brix_tpc_pull_t::streamid, tpc_done_stat_trailer(), and XRD_RESPONSE_HDR_LEN.
Referenced by tpc_done_reply_open().
tpc_done_stat_trailer()
static void tpc_done_stat_trailer (brix_tpc_pull_t * t, char * statbuf, size_t buflen) static
Definition at line 191 of file done.c.
References brix_tpc_pull_t::dst_fd, fstat(), kXR_readable, kXR_retstat, kXR_writable, brix_tpc_pull_t::options, stat(), and brix_tpc_pull_t::tpc_key.
Referenced by tpc_done_send_open_ok().
tpc_done_sync_fail()
static void tpc_done_sync_fail (brix_tpc_pull_t * t, brix_ctx_t * ctx, ngx_connection_t * c, int idx) static
Definition at line 92 of file done.c.
References brix_aio_resume(), brix_free_fhandle(), brix_log_access(), BRIX_MAX_FILES, BRIX_OP_ERR, BRIX_OP_SYNC, brix_send_error(), BRIX_SESS_END_ERROR, brix_vfs_unlink_path(), c, close(), brix_tpc_pull_t::conf, brix_tpc_pull_t::dst_fd, brix_tpc_pull_t::dst_path, brix_tpc_pull_t::err_msg, brix_file_t::fd, brix_ctx_t::files, kXR_ServerError, tpc_done_account(), tpc_sess_finish_pull(), brix_file_t::tpc_transfer_id, and brix_tpc_pull_t::xrd_error.
Referenced by tpc_done_reply_sync().
tpc_done_teardown_dst()
static void tpc_done_teardown_dst (brix_tpc_pull_t * t, brix_ctx_t * ctx, int idx, ngx_log_t * log) static
Definition at line 69 of file done.c.
References brix_free_fhandle(), BRIX_MAX_FILES, brix_vfs_unlink_path(), close(), brix_tpc_pull_t::conf, brix_tpc_pull_t::dst_fd, brix_tpc_pull_t::dst_path, brix_file_t::fd, brix_ctx_t::files, log, and brix_file_t::tpc_transfer_id.
Referenced by brix_tpc_pull_done(), and tpc_done_reply_open().
tpc_sess_finish_pull()
static void tpc_sess_finish_pull (brix_tpc_pull_t * t, int ok, brix_sess_end_t why) static
Definition at line 17 of file done.c.
References brix_sess_end(), BRIX_SESS_MODE_READ, brix_sess_result(), BRIX_SESS_XFER_ABORTED, brix_sess_xfer_add(), BRIX_SESS_XFER_COMPLETE, brix_sess_xfer_end(), brix_sesslog_err_from_kxr(), BRIX_SESSLOG_ERR_MAX, brix_tpc_pull_t::bytes_written, kXR_ServerError, brix_tpc_pull_t::sess, brix_tpc_pull_t::sess_xfer, brix_tpc_pull_t::src_path, and brix_tpc_pull_t::xrd_error.
Referenced by brix_tpc_pull_done(), tpc_done_reply_open(), tpc_done_reply_sync(), and tpc_done_sync_fail().