nginx-xrootd: src/auth/authz/acc/entity.c File Reference
entity.c File Reference
#include "acc.h"
#include "core/compat/alloc_guard.h"
Functions
static void acc_csv_trim (const char **s, size_t *len)
static ngx_int_t acc_csv_push_field (ngx_pool_t *pool, ngx_array_t *out, const char *field, size_t len)
static ngx_array_t * acc_split_csv (ngx_pool_t *pool, const char *csv)
static const char * acc_pick (ngx_array_t *a, ngx_uint_t i)
static void acc_entity_init_scalars (brix_acc_entity_t *ent, ngx_pool_t *pool, const char *name, const char *host, int isuser)
static ngx_uint_t acc_entity_tuple_count (ngx_array_t *vorgs, ngx_array_t *roles, ngx_array_t *grps)
static ngx_int_t acc_entity_fill_tuples (ngx_pool_t *pool, brix_acc_entity_t *ent, ngx_array_t *vorgs, ngx_array_t *roles, ngx_array_t *grps, ngx_uint_t n)
brix_acc_entity_t * brix_acc_entity_build (ngx_pool_t *pool, const char *name, const char *host, int isuser, const char *vorg_csv, const char *role_csv, const char *grp_csv)
Function Documentation
acc_csv_push_field()
static ngx_int_t acc_csv_push_field (ngx_pool_t * pool, ngx_array_t * out, const char * field, size_t len) static
Definition at line 64 of file entity.c.
References acc_csv_trim(), ngx_memcpy, ngx_pnalloc(), s, and tok.
Referenced by acc_split_csv().
acc_csv_trim()
static void acc_csv_trim (const char ** s, size_t * len) static
Definition at line 37 of file entity.c.
References s.
Referenced by acc_csv_push_field().
acc_entity_fill_tuples()
static ngx_int_t acc_entity_fill_tuples (ngx_pool_t * pool, brix_acc_entity_t * ent, ngx_array_t * vorgs, ngx_array_t * roles, ngx_array_t * grps, ngx_uint_t n) static
Definition at line 214 of file entity.c.
References acc_pick(), brix_acc_attr_t::grup, brix_acc_attr_t::role, brix_acc_entity_t::tuples, and brix_acc_attr_t::vorg.
Referenced by brix_acc_entity_build().
acc_entity_init_scalars()
static void acc_entity_init_scalars (brix_acc_entity_t * ent, ngx_pool_t * pool, const char * name, const char * host, int isuser) static
Definition at line 166 of file entity.c.
References host, brix_acc_entity_t::host, brix_acc_entity_t::isuser, brix_acc_entity_t::name, name, and brix_acc_entity_t::pool.
Referenced by brix_acc_entity_build().
acc_entity_tuple_count()
static ngx_uint_t acc_entity_tuple_count (ngx_array_t * vorgs, ngx_array_t * roles, ngx_array_t * grps) static
Definition at line 188 of file entity.c.
Referenced by brix_acc_entity_build().
acc_pick()
static const char * acc_pick (ngx_array_t * a, ngx_uint_t i) static
Definition at line 137 of file entity.c.
Referenced by acc_entity_fill_tuples().
acc_split_csv()
static ngx_array_t * acc_split_csv (ngx_pool_t * pool, const char * csv) static
Definition at line 106 of file entity.c.
References acc_csv_push_field().
Referenced by brix_acc_entity_build().
brix_acc_entity_build()
brix_acc_entity_t * brix_acc_entity_build (ngx_pool_t * pool, const char * name, const char * host, int isuser, const char * vorg_csv, const char * role_csv, const char * grp_csv)
Definition at line 237 of file entity.c.
References acc_entity_fill_tuples(), acc_entity_init_scalars(), acc_entity_tuple_count(), acc_split_csv(), BRIX_PCALLOC_OR_RETURN, host, and name.
Referenced by brix_acc_gate_engine(), and brix_acc_http_authorize().