nginx-xrootd: src/core/compat/error_mapping.c File Reference
error_mapping.c File Reference
#include "error_mapping.h"
#include <errno.h>
#include <stddef.h>
Data Structures
struct brix_kxr_errno_entry_t
Functions
uint16_t brix_kxr_from_errno (int err)
int brix_errno_from_kxr (uint16_t kxr)
uint16_t brix_kxr_map_ns_status (brix_ns_status_t status, int sys_errno)
int brix_http_errno_to_status (int err)
ngx_int_t brix_http_map_ns_status (brix_ns_status_t status)
ngx_int_t brix_http_map_errno (int err)
Variables
static const brix_kxr_errno_entry_t brix_kxr_errno_table []
Function Documentation
brix_errno_from_kxr()
int brix_errno_from_kxr (uint16_t kxr)
Definition at line 152 of file error_mapping.c.
References brix_kxr_errno_table, and brix_kxr_errno_entry_t::err.
Referenced by brix_kxr_to_errno().
brix_http_errno_to_status()
int brix_http_errno_to_status (int err)
Definition at line 205 of file error_mapping.c.
Referenced by brix_http_map_errno(), cvmfs_errno_status(), get_open_map_error(), s3_get_resolve(), s3_handle_head(), and s3_put_finalize_fs_error().
brix_http_map_errno()
ngx_int_t brix_http_map_errno (int err)
Definition at line 299 of file error_mapping.c.
References brix_http_errno_to_status().
Referenced by s3_post_object_body_handler_inner(), webdav_put_open_target(), and webdav_put_ranged_resume().
brix_http_map_ns_status()
ngx_int_t brix_http_map_ns_status (brix_ns_status_t status)
Definition at line 261 of file error_mapping.c.
References BRIX_NS_CONFLICT, BRIX_NS_DENIED, BRIX_NS_EXISTS, BRIX_NS_IO_ERROR, BRIX_NS_NO_SPACE, BRIX_NS_NOT_EMPTY, BRIX_NS_NOT_FOUND, BRIX_NS_OK, and BRIX_NS_TOO_LONG.
Referenced by webdav_copy_errno_to_status().
brix_kxr_from_errno()
uint16_t brix_kxr_from_errno (int err)
Definition at line 35 of file error_mapping.c.
References kXR_ArgInvalid, kXR_FileLocked, kXR_FSError, kXR_IOError, kXR_ItExists, kXR_NoMemory, kXR_NoSpace, kXR_NotAuthorized, kXR_NotFound, and kXR_Unsupported.
Referenced by brix_cache_fill_composed_done(), brix_dirlist_aio_done(), brix_dispatch_op(), brix_handle_link(), brix_handle_mkdir(), brix_handle_readlink(), brix_handle_setattr(), brix_handle_symlink(), brix_handle_truncate(), brix_kxr_map_ns_status(), brix_qcksum_open(), brix_query_xattr(), brix_statx_process_path(), fattr_errno_to_xrd(), fattr_path_target(), mv_dst_slash_precheck(), mv_execute(), ssi_resp_error(), and stat_query_path().
brix_kxr_map_ns_status()
uint16_t brix_kxr_map_ns_status (brix_ns_status_t status, int sys_errno)
Definition at line 170 of file error_mapping.c.
References brix_kxr_from_errno(), BRIX_NS_CONFLICT, BRIX_NS_DENIED, BRIX_NS_EXISTS, BRIX_NS_IO_ERROR, BRIX_NS_NO_SPACE, BRIX_NS_NOT_EMPTY, BRIX_NS_NOT_FOUND, BRIX_NS_OK, BRIX_NS_TOO_LONG, kXR_ArgTooLong, kXR_FSError, kXR_IOError, kXR_ItExists, kXR_NoSpace, kXR_NotAuthorized, kXR_NotFound, and kXR_ok.
Variable Documentation
brix_kxr_errno_table
const brix_kxr_errno_entry_t brix_kxr_errno_table[] static
Initial value:
= {
    {  3011  ,       ENOENT },
    {  3010  ,  EACCES },
    {  3030  ,     EACCES },
    {  3016  ,    EISDIR },
    {  3015  ,        EISDIR },
    {  3005  ,        EEXIST },
    {  3018  ,       EEXIST },
    {  3032  ,       EEXIST },
    {  3009  ,        ENOSPC },
    {  3021  ,      EDQUOT },
    {  3013  ,    ENOSYS },
    {  3025  ,     EROFS },
    {  3003  ,     EAGAIN },
    {  3020  ,     EINPROGRESS },
    {  3000  ,     EINVAL },
    {  3001  ,     EINVAL },
    {  3002  ,     ENAMETOOLONG },
    {  3006  , EINVAL },
    {  3004  ,    EBADF },
    {  3008  ,       ENOMEM },
    {  3019  ,      EIO },
    {  3007  ,        EIO },
    {  3027  ,   ENODATA },
    {  3028  ,    EACCES },
    {  3024  ,     EBUSY },
    {  3014  ,       EHOSTUNREACH },
}
Definition at line 122 of file error_mapping.c.
Referenced by brix_errno_from_kxr().