nginx-xrootd: src/fs/cache/errors.c File Reference
errors.c File Reference
#include "cache_internal.h"
#include <errno.h>
#include <stdio.h>
#include <string.h>
Functions
void brix_cache_set_error (brix_cache_fill_t *t, int xrd_error, int sys_errno, const char *msg)
void brix_cache_set_syserror (brix_cache_fill_t *t, int xrd_error, const char *prefix)
Function Documentation
brix_cache_set_error()
void brix_cache_set_error (brix_cache_fill_t * t, int xrd_error, int sys_errno, const char * msg)
Definition at line 12 of file errors.c.
References brix_cache_fill_t::err_msg, brix_cache_fill_t::result, brix_cache_fill_t::sys_errno, and brix_cache_fill_t::xrd_error.
Referenced by brix_cache_commit_staged(), brix_cache_fetch_origin(), brix_cache_fill_body(), brix_cache_fill_from_source(), brix_cache_origin_auth_sss(), brix_cache_origin_auth_ztn(), brix_cache_origin_bootstrap(), brix_cache_origin_connect_addr(), brix_cache_origin_dirlist(), brix_cache_origin_open(), brix_cache_origin_open_write(), brix_cache_origin_read_chunk(), brix_cache_origin_sync(), brix_cache_origin_tls_upgrade(), brix_cache_origin_truncate(), brix_cache_origin_write_chunk(), brix_cache_read_response(), brix_cache_set_origin_error(), brix_cache_set_syserror(), brix_cache_verify_no_origin(), brix_cache_verify_report_mismatch(), brix_cache_verify_unsupported(), brix_cache_wait_or_lock(), origin_bs_auth_dispatch(), origin_bs_authmore_fallback(), origin_bs_handshake(), origin_bs_login(), origin_bs_protocol(), origin_expect_frame(), originauth_gsi_certreq(), originauth_gsi_load_credential(), originauth_gsi_read_cert(), originauth_gsi_read_final(), originauth_gsi_send_response(), and originauth_gsi_verify_srv_cert().
brix_cache_set_syserror()
void brix_cache_set_syserror (brix_cache_fill_t * t, int xrd_error, const char * prefix)
Definition at line 30 of file errors.c.
References brix_cache_set_error().
Referenced by brix_cache_commit_staged(), brix_cache_fill_thread(), brix_cache_origin_connect_addr(), brix_cache_origin_read_chunk(), brix_cache_verify_part(), and brix_cache_wait_or_lock().