nginx-xrootd: src/net/proxy/events_read.c File Reference
events_read.c File Reference
#include "proxy_internal.h"
#include "protocols/root/connection/handler.h"
#include <sys/socket.h>
Enumerations
enum brix_pxr_verdict_t { BRIX_PXR_DONE , BRIX_PXR_CONTINUE , BRIX_PXR_PROCEED }
Functions
static brix_pxr_verdict_t proxy_read_arm (ngx_event_t *rev, brix_proxy_ctx_t *proxy, const char *abort_msg)
static brix_pxr_verdict_t proxy_read_hdr_complete (brix_proxy_ctx_t *proxy, ngx_connection_t *uconn)
static brix_pxr_verdict_t proxy_read_fill_hdr (brix_proxy_ctx_t *proxy, ngx_event_t *rev)
static brix_pxr_verdict_t proxy_read_fill_body (brix_proxy_ctx_t *proxy, ngx_event_t *rev)
static brix_pxr_verdict_t proxy_read_expand_status (brix_proxy_ctx_t *proxy, ngx_connection_t *uconn)
static brix_pxr_verdict_t proxy_read_relay_attn (brix_proxy_ctx_t *proxy)
static brix_pxr_verdict_t proxy_read_dispatch (brix_proxy_ctx_t *proxy, ngx_event_t *rev)
static brix_pxr_verdict_t proxy_read_step (brix_proxy_ctx_t *proxy, ngx_event_t *rev)
void brix_proxy_read_handler (ngx_event_t *rev)
Enumeration Type Documentation
brix_pxr_verdict_t
enum brix_pxr_verdict_t
Enumerator
BRIX_PXR_DONE
BRIX_PXR_CONTINUE
BRIX_PXR_PROCEED
Definition at line 19 of file events_read.c.
Function Documentation
brix_proxy_read_handler()
void brix_proxy_read_handler (ngx_event_t * rev)
Definition at line 423 of file events_read.c.
References brix_proxy_abort(), brix_proxy_cleanup(), BRIX_PXR_DONE, brix_ctx_t::destroyed, brix_ctx_t::proxy, and proxy_read_step().
Referenced by brix_proxy_pool_get(), pc_open_socket(), and proxy_gsi_promote_fd().
proxy_read_arm()
static brix_pxr_verdict_t proxy_read_arm (ngx_event_t * rev, brix_proxy_ctx_t * proxy, const char * abort_msg) static
Definition at line 34 of file events_read.c.
References brix_proxy_abort(), and BRIX_PXR_DONE.
Referenced by proxy_read_fill_body(), and proxy_read_fill_hdr().
proxy_read_dispatch()
static brix_pxr_verdict_t proxy_read_dispatch (brix_proxy_ctx_t * proxy, ngx_event_t * rev) static
Definition at line 321 of file events_read.c.
References brix_proxy_abort(), brix_proxy_handle_bootstrap(), brix_proxy_relay_to_client(), brix_proxy_splice_fallback_finish(), BRIX_PXR_CONTINUE, BRIX_PXR_DONE, XRD_PX_BOOTSTRAP, and XRD_PX_FORWARDING.
Referenced by proxy_read_step().
proxy_read_expand_status()
static brix_pxr_verdict_t proxy_read_expand_status (brix_proxy_ctx_t * proxy, ngx_connection_t * uconn) static
Definition at line 215 of file events_read.c.
References brix_proxy_abort(), BRIX_PROXY_MAX_BODY, BRIX_PXR_CONTINUE, BRIX_PXR_DONE, BRIX_PXR_PROCEED, kXR_status, and ngx_memcpy.
Referenced by proxy_read_step().
proxy_read_fill_body()
static brix_pxr_verdict_t proxy_read_fill_body (brix_proxy_ctx_t * proxy, ngx_event_t * rev) static
Definition at line 163 of file events_read.c.
References brix_proxy_abort(), brix_proxy_splice_pump(), BRIX_PXR_CONTINUE, BRIX_PXR_DONE, BRIX_PXR_PROCEED, and proxy_read_arm().
Referenced by proxy_read_step().
proxy_read_fill_hdr()
static brix_pxr_verdict_t proxy_read_fill_hdr (brix_proxy_ctx_t * proxy, ngx_event_t * rev) static
Definition at line 122 of file events_read.c.
References brix_proxy_abort(), BRIX_PXR_CONTINUE, BRIX_PXR_DONE, BRIX_PXR_PROCEED, proxy_read_arm(), proxy_read_hdr_complete(), and XRD_RESPONSE_HDR_LEN.
Referenced by proxy_read_step().
proxy_read_hdr_complete()
static brix_pxr_verdict_t proxy_read_hdr_complete (brix_proxy_ctx_t * proxy, ngx_connection_t * uconn) static
Definition at line 58 of file events_read.c.
References brix_proxy_abort(), BRIX_PROXY_MAX_BODY, brix_proxy_try_splice(), BRIX_PXR_DONE, BRIX_PXR_PROCEED, ServerResponseHdr::dlen, ServerResponseHdr::status, and XRD_PX_FORWARDING.
Referenced by proxy_read_fill_hdr().
proxy_read_relay_attn()
static brix_pxr_verdict_t proxy_read_relay_attn (brix_proxy_ctx_t * proxy) static
Definition at line 272 of file events_read.c.
References BRIX_PXR_CONTINUE, BRIX_PXR_PROCEED, brix_queue_response(), kXR_attn, ngx_memcpy, and XRD_RESPONSE_HDR_LEN.
Referenced by proxy_read_step().
proxy_read_step()
static brix_pxr_verdict_t proxy_read_step (brix_proxy_ctx_t * proxy, ngx_event_t * rev) static
Definition at line 389 of file events_read.c.
References BRIX_PXR_PROCEED, proxy_read_dispatch(), proxy_read_expand_status(), proxy_read_fill_body(), proxy_read_fill_hdr(), and proxy_read_relay_attn().
Referenced by brix_proxy_read_handler().