nginx-xrootd: src/net/proxy/events_bootstrap_auth.c File Reference
events_bootstrap_auth.c File Reference
#include "proxy_internal.h"
#include "protocols/root/connection/handler.h"
#include "auth/token/file.h"
#include <sys/socket.h>
#include "events_bootstrap_internal.h"
Data Structures
struct proxy_bs_auth_errs_t
Macros
#define PROXY_UPSTREAM_BEARER_MAX 65536
Functions
static size_t proxy_build_auth_ztn (u_char *buf, const char *token, size_t token_len)
static void proxy_resolve_upstream_auth (brix_proxy_ctx_t *proxy, ngx_uint_t *eff_auth, const brix_sss_key_t **eff_key)
void proxy_bs_auth_error (brix_proxy_ctx_t *proxy, unsigned up_inc, const char *msg)
void proxy_bs_reset_resp (brix_proxy_ctx_t *proxy)
static ngx_int_t proxy_bs_queue_auth_frame (brix_proxy_ctx_t *proxy, u_char *frame, size_t frame_len, const proxy_bs_auth_errs_t *errs)
static ngx_int_t proxy_bs_send_ztn (brix_proxy_ctx_t *proxy, const char *token, size_t token_len, const proxy_bs_auth_errs_t *errs)
static ngx_int_t proxy_send_sss_auth (brix_proxy_ctx_t *proxy, const brix_sss_key_t *key)
static void proxy_bs_auth_forward_bearer (brix_proxy_ctx_t *proxy)
static void proxy_bs_auth_token_file (brix_proxy_ctx_t *proxy)
int proxy_bs_do_auth (brix_proxy_ctx_t *proxy)
static int proxy_bs_login_sec_ztn (brix_proxy_ctx_t *proxy)
int proxy_bs_login_sec_hint (brix_proxy_ctx_t *proxy)
Macro Definition Documentation
PROXY_UPSTREAM_BEARER_MAX
#define PROXY_UPSTREAM_BEARER_MAX 65536
Definition at line 20 of file events_bootstrap_auth.c.
Function Documentation
proxy_bs_auth_error()
void proxy_bs_auth_error (brix_proxy_ctx_t * proxy, unsigned up_inc, const char * msg)
Definition at line 126 of file events_bootstrap_auth.c.
References brix_proxy_abort(), BRIX_PROXY_METRIC_INC, and BRIX_PROXY_UP_INC.
Referenced by brix_proxy_bs_login(), brix_proxy_handle_bootstrap(), proxy_bs_auth_token_file(), proxy_bs_do_auth(), proxy_bs_queue_auth_frame(), proxy_bs_send_ztn(), and proxy_send_sss_auth().
proxy_bs_auth_forward_bearer()
static void proxy_bs_auth_forward_bearer (brix_proxy_ctx_t * proxy) static
Definition at line 275 of file events_bootstrap_auth.c.
References proxy_bs_send_ztn().
Referenced by proxy_bs_do_auth().
proxy_bs_auth_token_file()
static void proxy_bs_auth_token_file (brix_proxy_ctx_t * proxy) static
Definition at line 300 of file events_bootstrap_auth.c.
References brix_token_read_file(), proxy_bs_auth_error(), proxy_bs_send_ztn(), and PROXY_UPSTREAM_BEARER_MAX.
Referenced by proxy_bs_do_auth().
proxy_bs_do_auth()
int proxy_bs_do_auth (brix_proxy_ctx_t * proxy)
Definition at line 336 of file events_bootstrap_auth.c.
References BRIX_PROXY_AUTH_FORWARD, BRIX_PROXY_AUTH_SSS, proxy_bs_auth_error(), proxy_bs_auth_forward_bearer(), proxy_bs_auth_token_file(), proxy_resolve_upstream_auth(), and proxy_send_sss_auth().
Referenced by brix_proxy_bs_login().
proxy_bs_login_sec_hint()
int proxy_bs_login_sec_hint (brix_proxy_ctx_t * proxy)
Definition at line 440 of file events_bootstrap_auth.c.
References BRIX_PROXY_AUTH_SSS, BRIX_SESSION_ID_LEN, proxy_bs_login_sec_ztn(), proxy_resolve_upstream_auth(), and proxy_send_sss_auth().
Referenced by brix_proxy_bs_login().
proxy_bs_login_sec_ztn()
static int proxy_bs_login_sec_ztn (brix_proxy_ctx_t * proxy) static
Definition at line 384 of file events_bootstrap_auth.c.
References brix_token_read_file(), proxy_bs_send_ztn(), and PROXY_UPSTREAM_BEARER_MAX.
Referenced by proxy_bs_login_sec_hint().
proxy_bs_queue_auth_frame()
static ngx_int_t proxy_bs_queue_auth_frame (brix_proxy_ctx_t * proxy, u_char * frame, size_t frame_len, const proxy_bs_auth_errs_t * errs) static
Definition at line 167 of file events_bootstrap_auth.c.
References proxy_bs_auth_errs_t::arm_msg, brix_proxy_flush(), proxy_bs_auth_error(), proxy_bs_reset_resp(), proxy_bs_auth_errs_t::send_msg, proxy_bs_auth_errs_t::up_inc, and XRD_PX_BS_AUTH.
Referenced by proxy_bs_send_ztn(), and proxy_send_sss_auth().
proxy_bs_reset_resp()
void proxy_bs_reset_resp (brix_proxy_ctx_t * proxy)
Definition at line 143 of file events_bootstrap_auth.c.
Referenced by brix_proxy_handle_bootstrap(), and proxy_bs_queue_auth_frame().
proxy_bs_send_ztn()
static ngx_int_t proxy_bs_send_ztn (brix_proxy_ctx_t * proxy, const char * token, size_t token_len, const proxy_bs_auth_errs_t * errs) static
Definition at line 202 of file events_bootstrap_auth.c.
References proxy_bs_auth_errs_t::oom_msg, proxy_bs_auth_error(), proxy_bs_queue_auth_frame(), proxy_build_auth_ztn(), and proxy_bs_auth_errs_t::up_inc.
Referenced by proxy_bs_auth_forward_bearer(), proxy_bs_auth_token_file(), and proxy_bs_login_sec_ztn().
proxy_build_auth_ztn()
static size_t proxy_build_auth_ztn (u_char * buf, const char * token, size_t token_len) static
Definition at line 36 of file events_bootstrap_auth.c.
References kXR_auth, and ngx_memcpy.
Referenced by proxy_bs_send_ztn().
proxy_resolve_upstream_auth()
static void proxy_resolve_upstream_auth (brix_proxy_ctx_t * proxy, ngx_uint_t * eff_auth, const brix_sss_key_t ** eff_key) static
Definition at line 61 of file events_bootstrap_auth.c.
References brix_proxy_upstream_t::auth, BRIX_PROXY_AUTH_ANONYMOUS, BRIX_PROXY_AUTH_SSS, name, and brix_proxy_upstream_t::sss_keyname.
Referenced by proxy_bs_do_auth(), and proxy_bs_login_sec_hint().
proxy_send_sss_auth()
static ngx_int_t proxy_send_sss_auth (brix_proxy_ctx_t * proxy, const brix_sss_key_t * key) static
Definition at line 223 of file events_bootstrap_auth.c.
References brix_sss_build_proxy_credential(), key, kXR_auth, ngx_memcpy, proxy_bs_auth_errs_t::oom_msg, proxy_bs_auth_error(), proxy_bs_queue_auth_frame(), and XRD_REQUEST_HDR_LEN.
Referenced by proxy_bs_do_auth(), and proxy_bs_login_sec_hint().