nginx-xrootd: src/net/proxy/events_bootstrap.c File Reference
events_bootstrap.c File Reference
#include "proxy_internal.h"
#include "protocols/root/connection/handler.h"
#include "auth/token/file.h"
#include <sys/socket.h>
#include "events_bootstrap_internal.h"
Functions
static int brix_proxy_bs_login (brix_proxy_ctx_t *proxy)
static ngx_int_t proxy_bs_check_protocol_reply (brix_proxy_ctx_t *proxy)
static void proxy_bs_adopt_conn (brix_proxy_ctx_t *proxy)
void brix_proxy_handle_bootstrap (brix_proxy_ctx_t *proxy)
Function Documentation
brix_proxy_bs_login()
static int brix_proxy_bs_login (brix_proxy_ctx_t * proxy) static
Definition at line 52 of file events_bootstrap.c.
References kXR_authmore, kXR_ok, proxy_bs_auth_error(), proxy_bs_do_auth(), proxy_bs_login_sec_hint(), and XRD_PX_BS_DONE.
Referenced by brix_proxy_handle_bootstrap().
brix_proxy_handle_bootstrap()
void brix_proxy_handle_bootstrap (brix_proxy_ctx_t * proxy)
Definition at line 162 of file events_bootstrap.c.
References brix_proxy_abort(), brix_proxy_bs_login(), kXR_ok, proxy_bs_adopt_conn(), proxy_bs_auth_error(), proxy_bs_check_protocol_reply(), proxy_bs_reset_resp(), XRD_PX_BS_AUTH, XRD_PX_BS_DONE, XRD_PX_BS_HANDSHAKE, XRD_PX_BS_LOGIN, and XRD_PX_BS_PROTOCOL.
Referenced by proxy_read_dispatch().
proxy_bs_adopt_conn()
static void proxy_bs_adopt_conn (brix_proxy_ctx_t * proxy) static
Definition at line 125 of file events_bootstrap.c.
References brix_proxy_dispatch_pending(), BRIX_PROXY_METRIC_INC, BRIX_PROXY_UP_INC, brix_proxy_up_mark_ok(), brix_schedule_read_resume(), brix_ctx_t::state, XRD_PX_IDLE, and XRD_ST_REQ_HEADER.
Referenced by brix_proxy_handle_bootstrap().
proxy_bs_check_protocol_reply()
static ngx_int_t proxy_bs_check_protocol_reply (brix_proxy_ctx_t * proxy) static
Definition at line 86 of file events_bootstrap.c.
References brix_proxy_abort(), kXR_gotoTLS, kXR_ok, and ngx_memcpy.
Referenced by brix_proxy_handle_bootstrap().