nginx-xrootd: src/net/proxy/events_write.c File Reference
events_write.c File Reference
#include "proxy_internal.h"
#include "protocols/root/connection/handler.h"
#include "core/compat/log_diag.h"
#include <sys/socket.h>
Enumerations
enum brix_pw_outcome_t { PW_CONTINUE = 0 , PW_DONE }
Functions
static brix_pw_outcome_t brix_proxy_check_connect (ngx_connection_t *uconn, brix_proxy_ctx_t *proxy, brix_ctx_t *ctx)
static brix_pw_outcome_t brix_proxy_handle_connecting (ngx_connection_t *uconn, brix_proxy_ctx_t *proxy, brix_ctx_t *ctx)
static brix_pw_outcome_t brix_proxy_flush_buffered (ngx_connection_t *uconn, brix_proxy_ctx_t *proxy)
static void brix_proxy_write_complete (ngx_connection_t *uconn, brix_proxy_ctx_t *proxy)
void brix_proxy_write_handler (ngx_event_t *wev)
Enumeration Type Documentation
brix_pw_outcome_t
enum brix_pw_outcome_t
Enumerator
PW_CONTINUE
PW_DONE
Definition at line 18 of file events_write.c.
Function Documentation
brix_proxy_check_connect()
static brix_pw_outcome_t brix_proxy_check_connect (ngx_connection_t * uconn, brix_proxy_ctx_t * proxy, brix_ctx_t * ctx) static
Definition at line 34 of file events_write.c.
References BRIX_DIAG_ERR, brix_proxy_abort(), BRIX_PROXY_METRIC_INC, BRIX_PROXY_UP_INC, PW_CONTINUE, and PW_DONE.
Referenced by brix_proxy_handle_connecting().
brix_proxy_flush_buffered()
static brix_pw_outcome_t brix_proxy_flush_buffered (ngx_connection_t * uconn, brix_proxy_ctx_t * proxy) static
Definition at line 171 of file events_write.c.
References brix_proxy_abort(), brix_proxy_flush(), PW_CONTINUE, and PW_DONE.
Referenced by brix_proxy_write_handler().
brix_proxy_handle_connecting()
static brix_pw_outcome_t brix_proxy_handle_connecting (ngx_connection_t * uconn, brix_proxy_ctx_t * proxy, brix_ctx_t * ctx) static
Definition at line 140 of file events_write.c.
References brix_proxy_check_connect(), PW_CONTINUE, PW_DONE, XRD_PX_BOOTSTRAP, and XRD_PX_BS_HANDSHAKE.
Referenced by brix_proxy_write_handler().
brix_proxy_write_complete()
static void brix_proxy_write_complete (ngx_connection_t * uconn, brix_proxy_ctx_t * proxy) static
Definition at line 209 of file events_write.c.
References brix_proxy_abort(), and brix_proxy_wbuf_release().
Referenced by brix_proxy_write_handler().
brix_proxy_write_handler()
void brix_proxy_write_handler (ngx_event_t * wev)
Definition at line 244 of file events_write.c.
References brix_proxy_abort(), brix_proxy_cleanup(), brix_proxy_flush_buffered(), brix_proxy_handle_connecting(), brix_proxy_write_complete(), brix_ctx_t::destroyed, PW_DONE, XRD_PX_CONNECTING, and XRD_PX_TLS_HANDSHAKE.
Referenced by brix_proxy_pool_get(), pc_open_socket(), and proxy_gsi_promote_fd().