nginx-xrootd: src/protocols/root/connection/event_sched.h File Reference
event_sched.h File Reference
#include "core/ngx_brix_module.h"
Functions
ngx_int_t brix_schedule_read_resume (ngx_connection_t *c)
ngx_int_t brix_schedule_write_resume (ngx_connection_t *c)
ngx_int_t brix_ensure_write_event (ngx_connection_t *c)
Function Documentation
brix_ensure_write_event()
ngx_int_t brix_ensure_write_event (ngx_connection_t * c)
Definition at line 55 of file event_sched.c.
References brix_arm_send_deadline(), c, ngx_stream_brix_module, and s.
Referenced by brix_aio_resume(), brix_queue_response_base(), and brix_queue_response_chain().
brix_schedule_read_resume()
ngx_int_t brix_schedule_read_resume (ngx_connection_t * c)
Definition at line 6 of file event_sched.c.
References c.
Referenced by brix_aio_resume(), brix_proxy_abort(), brix_proxy_lazy_open_failed(), brix_proxy_relay_finish_final(), brix_proxy_relay_lazy_open(), brix_recv_pre_loop(), brix_upstream_abort(), brix_upstream_forward_response(), brix_write_aio_done_pipelined(), cms_wake_pending_session(), pc_select_endpoint(), proxy_bs_adopt_conn(), proxy_gsi_login_done(), and stage_waiter_deliver_one().
brix_schedule_write_resume()
ngx_int_t brix_schedule_write_resume (ngx_connection_t * c)
Definition at line 22 of file event_sched.c.
References brix_arm_send_deadline(), c, ngx_stream_brix_module, and s.
Referenced by brix_flush_pending(), brix_queue_response_base(), and brix_queue_response_chain().