nginx-xrootd: src/net/proxy/events_bootstrap_internal.h File Reference
events_bootstrap_internal.h File Reference
#include "proxy_internal.h"
Functions
void proxy_bs_reset_resp (brix_proxy_ctx_t *proxy)
void proxy_bs_auth_error (brix_proxy_ctx_t *proxy, unsigned up_inc, const char *msg)
int proxy_bs_do_auth (brix_proxy_ctx_t *proxy)
int proxy_bs_login_sec_hint (brix_proxy_ctx_t *proxy)
Function Documentation
proxy_bs_auth_error()
void proxy_bs_auth_error (brix_proxy_ctx_t * proxy, unsigned up_inc, const char * msg)
Definition at line 126 of file events_bootstrap_auth.c.
References brix_proxy_abort(), BRIX_PROXY_METRIC_INC, and BRIX_PROXY_UP_INC.
Referenced by brix_proxy_bs_login(), brix_proxy_handle_bootstrap(), proxy_bs_auth_token_file(), proxy_bs_do_auth(), proxy_bs_queue_auth_frame(), proxy_bs_send_ztn(), and proxy_send_sss_auth().
proxy_bs_do_auth()
int proxy_bs_do_auth (brix_proxy_ctx_t * proxy)
Definition at line 336 of file events_bootstrap_auth.c.
References BRIX_PROXY_AUTH_FORWARD, BRIX_PROXY_AUTH_SSS, proxy_bs_auth_error(), proxy_bs_auth_forward_bearer(), proxy_bs_auth_token_file(), proxy_resolve_upstream_auth(), and proxy_send_sss_auth().
Referenced by brix_proxy_bs_login().
proxy_bs_login_sec_hint()
int proxy_bs_login_sec_hint (brix_proxy_ctx_t * proxy)
Definition at line 440 of file events_bootstrap_auth.c.
References BRIX_PROXY_AUTH_SSS, BRIX_SESSION_ID_LEN, proxy_bs_login_sec_ztn(), proxy_resolve_upstream_auth(), and proxy_send_sss_auth().
Referenced by brix_proxy_bs_login().
proxy_bs_reset_resp()
void proxy_bs_reset_resp (brix_proxy_ctx_t * proxy)
Definition at line 143 of file events_bootstrap_auth.c.
Referenced by brix_proxy_handle_bootstrap(), and proxy_bs_queue_auth_frame().