nginx-xrootd: src/fs/cache/evict_policy.c File Reference
evict_policy.c File Reference
#include "evict_internal.h"
#include "cache_storage.h"
#include "meta.h"
#include "fs/backend/cache/sd_cache.h"
Data Structures
struct brix_cache_evict_ctx_t
Functions
static void brix_cache_evict_remove_object (brix_cache_evict_list_t *list, size_t idx)
static void brix_cache_evict_remove_sidecars (brix_cache_evict_list_t *list, size_t idx)
static uint16_t brix_cache_local_self_port (ngx_connection_t *c)
static void brix_cache_evict_unregister (brix_cache_evict_ctx_t *ec, size_t idx)
static ngx_int_t brix_cache_evict_one (brix_cache_evict_ctx_t *ec, size_t idx)
static ngx_int_t brix_cache_purge_setup (brix_cache_evict_ctx_t *ec, const char *protect_path, ngx_uint_t target_ppm, int *proceed)
static ngx_int_t brix_cache_purge_large_pass (brix_cache_evict_ctx_t *ec, ngx_uint_t target_ppm)
static ngx_int_t brix_cache_purge_lru_pass (brix_cache_evict_ctx_t *ec, ngx_uint_t target_ppm)
ngx_int_t brix_cache_purge_to_target (ngx_stream_brix_srv_conf_t *conf, brix_ctx_t *ctx, ngx_connection_t *c, const char *protect_path, ngx_uint_t target_ppm, ngx_log_t *log, ngx_uint_t *evicted_files_out, uint64_t *evicted_bytes_out)
void brix_cache_evict_if_needed (brix_cache_fill_t *t, const char *protect_path, ngx_log_t *log)
Function Documentation
brix_cache_evict_if_needed()
void brix_cache_evict_if_needed (brix_cache_fill_t * t, const char * protect_path, ngx_log_t * log)
Definition at line 479 of file evict_policy.c.
References brix_cache_evict_unlock(), brix_cache_metric_add, BRIX_CACHE_PPM_FULL_SCALE, brix_cache_purge_to_target(), brix_cache_storage_cstore(), brix_cache_try_evict_lock(), brix_cache_usage_measure(), brix_cache_fill_t::c, brix_cache_fill_t::conf, brix_cache_fill_t::ctx, log, PATH_MAX, and usage().
Referenced by brix_cache_fill_thread().
brix_cache_evict_one()
static ngx_int_t brix_cache_evict_one (brix_cache_evict_ctx_t * ec, size_t idx) static
Definition at line 202 of file evict_policy.c.
References brix_cache_evict_remove_object(), brix_cache_evict_remove_sidecars(), brix_cache_evict_unregister(), brix_cache_metric_add, brix_cache_usage_measure(), brix_sd_cache_demote(), brix_cache_evict_list_t::cache_root, brix_cache_evict_ctx_t::conf, brix_cache_evict_list_t::cstore, brix_cache_evict_ctx_t::ctx, brix_cache_evict_ctx_t::decorator, brix_cache_evict_list_t::elts, brix_cache_evict_list_t::evicted, brix_cache_evict_ctx_t::evicted_bytes, brix_cache_evict_ctx_t::evicted_files, key, brix_cache_evict_ctx_t::list, brix_cache_evict_ctx_t::log, brix_cache_evict_candidate_t::path, brix_cache_evict_candidate_t::size, and brix_cache_evict_ctx_t::usage.
Referenced by brix_cache_purge_large_pass(), and brix_cache_purge_lru_pass().
brix_cache_evict_remove_object()
static void brix_cache_evict_remove_object (brix_cache_evict_list_t * list, size_t idx) static
Definition at line 78 of file evict_policy.c.
References brix_cstore_evict(), brix_cache_evict_list_t::cache_root, brix_cache_evict_list_t::cstore, brix_cache_evict_list_t::elts, key, and brix_cache_evict_candidate_t::path.
Referenced by brix_cache_evict_one().
brix_cache_evict_remove_sidecars()
static void brix_cache_evict_remove_sidecars (brix_cache_evict_list_t * list, size_t idx) static
Definition at line 100 of file evict_policy.c.
References brix_cache_meta_path(), brix_cache_sidecar_path(), brix_cache_evict_list_t::cache_root, brix_cache_evict_list_t::elts, brix_cache_evict_candidate_t::path, PATH_MAX, and brix_cache_evict_list_t::state_root.
Referenced by brix_cache_evict_one().
brix_cache_evict_unregister()
static void brix_cache_evict_unregister (brix_cache_evict_ctx_t * ec, size_t idx) static
Definition at line 156 of file evict_policy.c.
References brix_cache_local_self_port(), brix_srv_unregister_path(), c, brix_cache_evict_ctx_t::c, brix_cache_evict_ctx_t::conf, brix_cache_evict_list_t::elts, brix_cache_evict_ctx_t::list, and brix_cache_evict_candidate_t::path.
Referenced by brix_cache_evict_one().
brix_cache_local_self_port()
static uint16_t brix_cache_local_self_port (ngx_connection_t * c) static
Definition at line 133 of file evict_policy.c.
References c.
Referenced by brix_cache_evict_unregister().
brix_cache_purge_large_pass()
static ngx_int_t brix_cache_purge_large_pass (brix_cache_evict_ctx_t * ec, ngx_uint_t target_ppm) static
Definition at line 338 of file evict_policy.c.
References brix_cache_evict_one(), brix_cache_evict_ctx_t::conf, brix_cache_evict_list_t::elts, brix_cache_evict_ctx_t::list, brix_cache_evict_list_t::nelts, brix_cache_fs_usage_t::occupancy_ppm, brix_cache_evict_candidate_t::size, and brix_cache_evict_ctx_t::usage.
Referenced by brix_cache_purge_to_target().
brix_cache_purge_lru_pass()
static ngx_int_t brix_cache_purge_lru_pass (brix_cache_evict_ctx_t * ec, ngx_uint_t target_ppm) static
Definition at line 370 of file evict_policy.c.
References brix_cache_evict_one(), brix_cache_evict_list_t::evicted, brix_cache_evict_ctx_t::list, brix_cache_evict_list_t::nelts, brix_cache_fs_usage_t::occupancy_ppm, and brix_cache_evict_ctx_t::usage.
Referenced by brix_cache_purge_to_target().
brix_cache_purge_setup()
static ngx_int_t brix_cache_purge_setup (brix_cache_evict_ctx_t * ec, const char * protect_path, ngx_uint_t target_ppm, int * proceed) static
Definition at line 261 of file evict_policy.c.
References brix_cache_candidate_cmp(), brix_cache_collect_dir(), brix_cache_metric_add, brix_cache_state_root(), brix_cache_storage(), brix_cache_storage_cstore(), brix_cache_storage_decorator(), brix_cache_usage_measure(), brix_cache_evict_list_t::cache_root, brix_cache_evict_ctx_t::conf, brix_cache_evict_list_t::cstore, brix_cache_evict_ctx_t::ctx, brix_cache_evict_ctx_t::decorator, brix_cache_evict_list_t::elts, brix_cache_evict_list_t::inst, brix_cache_evict_ctx_t::list, log, brix_cache_evict_ctx_t::log, brix_cache_evict_list_t::nelts, brix_cache_evict_list_t::protect_path, brix_cache_evict_list_t::root_dev, stat(), brix_cache_evict_list_t::state_root, usage(), and brix_cache_evict_ctx_t::usage.
Referenced by brix_cache_purge_to_target().
brix_cache_purge_to_target()
ngx_int_t brix_cache_purge_to_target (ngx_stream_brix_srv_conf_t * conf, brix_ctx_t * ctx, ngx_connection_t * c, const char * protect_path, ngx_uint_t target_ppm, ngx_log_t * log, ngx_uint_t * evicted_files_out, uint64_t * evicted_bytes_out)
Definition at line 424 of file evict_policy.c.
References brix_cache_free_candidates(), brix_cache_purge_large_pass(), brix_cache_purge_lru_pass(), brix_cache_purge_setup(), c, brix_cache_evict_ctx_t::c, brix_cache_evict_ctx_t::conf, brix_cache_evict_ctx_t::ctx, brix_cache_evict_ctx_t::evicted_bytes, brix_cache_evict_ctx_t::evicted_files, brix_cache_evict_ctx_t::list, log, brix_cache_evict_ctx_t::log, usage(), and brix_cache_evict_ctx_t::usage.
Referenced by brix_cache_evict_if_needed(), and brix_cache_watermark_purge().