nginx-xrootd: src/fs/cache/evict_internal.h File Reference
evict_internal.h File Reference
#include "cache_internal.h"
#include "cstore.h"
#include "net/manager/registry.h"
#include <dirent.h>
#include <fcntl.h>
#include <limits.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct brix_cache_evict_candidate_t
struct brix_cache_evict_list_t
struct brix_cache_fs_usage_t
Macros
#define brix_cache_metric_add(ctx, member, value)
Functions
ngx_int_t brix_cache_fs_usage (const char *root, brix_cache_fs_usage_t *usage)
ngx_int_t brix_cache_usage_measure (brix_cstore_t *cs, const char *root, brix_cache_fs_usage_t *usage)
ngx_int_t brix_cache_fs_usage_sampled (const char *root, ngx_msec_t ttl_ms, brix_cache_fs_usage_t *out)
ngx_int_t brix_cache_try_evict_lock (ngx_stream_brix_srv_conf_t *conf, char *lock_path, size_t lock_pathsz, ngx_log_t *log)
void brix_cache_evict_unlock (const char *lock_path)
ngx_int_t brix_cache_collect_dir (brix_cache_evict_list_t *list, const char *dir, ngx_log_t *log)
ngx_int_t brix_cache_purge_to_target (ngx_stream_brix_srv_conf_t *conf, brix_ctx_t *ctx, ngx_connection_t *c, const char *protect_path, ngx_uint_t target_ppm, ngx_log_t *log, ngx_uint_t *evicted_files_out, uint64_t *evicted_bytes_out)
int brix_cache_candidate_cmp (const void *a, const void *b)
void brix_cache_free_candidates (brix_cache_evict_list_t *list)
Macro Definition Documentation
brix_cache_metric_add
#define brix_cache_metric_add (ctx, member, value)
Value:
    do {                                                                 \
        if ((ctx) != NULL && (ctx)->metrics != NULL) {                    \
            ngx_atomic_fetch_add(&(ctx)->metrics->member,                 \
                                 (ngx_atomic_int_t) (value));             \
        }                                                                \
    } while (0)
Definition at line 31 of file evict_internal.h.
Function Documentation
brix_cache_candidate_cmp()
int brix_cache_candidate_cmp (const void * a, const void * b)
Definition at line 446 of file evict_candidates.c.
References brix_cache_evict_candidate_t::atime, brix_cache_evict_candidate_t::mtime, and brix_cache_evict_candidate_t::path.
Referenced by brix_cache_purge_setup().
brix_cache_collect_dir()
ngx_int_t brix_cache_collect_dir (brix_cache_evict_list_t * list, const char * dir, ngx_log_t * log)
Definition at line 418 of file evict_candidates.c.
References brix_cstore_scan(), brix_cache_evict_list_t::cstore, evict_collect_visit(), and log.
Referenced by brix_cache_purge_setup().
brix_cache_evict_unlock()
void brix_cache_evict_unlock (const char * lock_path)
Definition at line 171 of file evict_candidates.c.
Referenced by brix_cache_evict_if_needed(), and brix_cache_watermark_purge().
brix_cache_free_candidates()
void brix_cache_free_candidates (brix_cache_evict_list_t * list)
Definition at line 459 of file evict_candidates.c.
References brix_cache_evict_list_t::cap, brix_cache_evict_list_t::elts, brix_cache_evict_list_t::evicted, brix_cache_evict_list_t::nelts, and brix_cache_evict_candidate_t::path.
Referenced by brix_cache_purge_to_target().
brix_cache_fs_usage()
ngx_int_t brix_cache_fs_usage (const char * root, brix_cache_fs_usage_t * usage)
Definition at line 39 of file evict_candidates.c.
References usage().
Referenced by brix_cache_fs_usage_sampled(), and brix_cache_usage_measure().
brix_cache_fs_usage_sampled()
ngx_int_t brix_cache_fs_usage_sampled (const char * root, ngx_msec_t ttl_ms, brix_cache_fs_usage_t * out)
Definition at line 61 of file cache_fs_sampler.c.
References brix_cache_fs_usage(), brix_cache_sample_fresh(), fs_usage_cache, fs_usage_lookup(), fs_usage_slot_t::last_ms, fs_usage_slot_t::root, and fs_usage_slot_t::usage.
Referenced by brix_cache_watermark_purge(), and brix_wt_stage_admit().
brix_cache_purge_to_target()
ngx_int_t brix_cache_purge_to_target (ngx_stream_brix_srv_conf_t * conf, brix_ctx_t * ctx, ngx_connection_t * c, const char * protect_path, ngx_uint_t target_ppm, ngx_log_t * log, ngx_uint_t * evicted_files_out, uint64_t * evicted_bytes_out)
Definition at line 424 of file evict_policy.c.
References brix_cache_free_candidates(), brix_cache_purge_large_pass(), brix_cache_purge_lru_pass(), brix_cache_purge_setup(), c, brix_cache_evict_ctx_t::c, brix_cache_evict_ctx_t::conf, brix_cache_evict_ctx_t::ctx, brix_cache_evict_ctx_t::evicted_bytes, brix_cache_evict_ctx_t::evicted_files, brix_cache_evict_ctx_t::list, log, brix_cache_evict_ctx_t::log, usage(), and brix_cache_evict_ctx_t::usage.
Referenced by brix_cache_evict_if_needed(), and brix_cache_watermark_purge().
brix_cache_try_evict_lock()
ngx_int_t brix_cache_try_evict_lock (ngx_stream_brix_srv_conf_t * conf, char * lock_path, size_t lock_pathsz, ngx_log_t * log)
Definition at line 106 of file evict_candidates.c.
References BRIX_CACHE_EVICT_LOCK_NAME, brix_cache_state_root(), close(), log, open(), and stat().
Referenced by brix_cache_evict_if_needed(), and brix_cache_watermark_purge().
brix_cache_usage_measure()
ngx_int_t brix_cache_usage_measure (brix_cstore_t * cs, const char * root, brix_cache_fs_usage_t * usage)
Definition at line 65 of file evict_candidates.c.
References brix_cache_fs_usage(), brix_cstore_freespace(), and usage().
Referenced by brix_cache_evict_if_needed(), brix_cache_evict_one(), and brix_cache_purge_setup().