nginx-xrootd: src/fs/cache/evict_candidates.c File Reference
evict_candidates.c File Reference
#include "evict_internal.h"
#include "cache_storage.h"
#include "cinfo.h"
#include "core/compat/safe_size.h"
#include <errno.h>
#include <netinet/in.h>
Macros
#define BRIX_EVICT_MAX_CANDIDATES (4u * 1024u * 1024u)
Functions
static ngx_int_t brix_cache_add_candidate (brix_cache_evict_list_t *list, const char *path, const struct stat *st)
static int brix_cache_skip_name (const char *name)
ngx_int_t brix_cache_fs_usage (const char *root, brix_cache_fs_usage_t *usage)
ngx_int_t brix_cache_usage_measure (brix_cstore_t *cs, const char *root, brix_cache_fs_usage_t *usage)
ngx_int_t brix_cache_try_evict_lock (ngx_stream_brix_srv_conf_t *conf, char *lock_path, size_t lock_pathsz, ngx_log_t *log)
void brix_cache_evict_unlock (const char *lock_path)
static ngx_int_t evict_collect_visit (const char *key, const brix_cache_cinfo_t *ci, const brix_sd_stat_t *stx, void *ctx)
ngx_int_t brix_cache_collect_dir (brix_cache_evict_list_t *list, const char *keydir, ngx_log_t *log)
int brix_cache_candidate_cmp (const void *a, const void *b)
void brix_cache_free_candidates (brix_cache_evict_list_t *list)
Macro Definition Documentation
BRIX_EVICT_MAX_CANDIDATES
#define BRIX_EVICT_MAX_CANDIDATES (4u * 1024u * 1024u)
Definition at line 8 of file evict_candidates.c.
Function Documentation
brix_cache_add_candidate()
static ngx_int_t brix_cache_add_candidate (brix_cache_evict_list_t * list, const char * path, const struct stat * st) static
Definition at line 260 of file evict_candidates.c.
References brix_cache_evict_candidate_t::atime, BRIX_EVICT_MAX_CANDIDATES, brix_size_mul(), brix_cache_evict_list_t::cap, brix_cache_evict_list_t::elts, brix_cache_evict_list_t::evicted, brix_cache_evict_candidate_t::mtime, brix_cache_evict_list_t::nelts, brix_cache_evict_candidate_t::path, brix_cache_evict_list_t::protect_path, and brix_cache_evict_candidate_t::size.
Referenced by evict_collect_visit().
brix_cache_candidate_cmp()
int brix_cache_candidate_cmp (const void * a, const void * b)
Definition at line 446 of file evict_candidates.c.
References brix_cache_evict_candidate_t::atime, brix_cache_evict_candidate_t::mtime, and brix_cache_evict_candidate_t::path.
Referenced by brix_cache_purge_setup().
brix_cache_collect_dir()
ngx_int_t brix_cache_collect_dir (brix_cache_evict_list_t * list, const char * keydir, ngx_log_t * log)
Definition at line 418 of file evict_candidates.c.
References brix_cstore_scan(), brix_cache_evict_list_t::cstore, evict_collect_visit(), and log.
Referenced by brix_cache_purge_setup().
brix_cache_evict_unlock()
void brix_cache_evict_unlock (const char * lock_path)
Definition at line 171 of file evict_candidates.c.
Referenced by brix_cache_evict_if_needed(), and brix_cache_watermark_purge().
brix_cache_free_candidates()
void brix_cache_free_candidates (brix_cache_evict_list_t * list)
Definition at line 459 of file evict_candidates.c.
References brix_cache_evict_list_t::cap, brix_cache_evict_list_t::elts, brix_cache_evict_list_t::evicted, brix_cache_evict_list_t::nelts, and brix_cache_evict_candidate_t::path.
Referenced by brix_cache_purge_to_target().
brix_cache_fs_usage()
ngx_int_t brix_cache_fs_usage (const char * root, brix_cache_fs_usage_t * usage)
Definition at line 39 of file evict_candidates.c.
References usage().
Referenced by brix_cache_fs_usage_sampled(), and brix_cache_usage_measure().
brix_cache_skip_name()
static int brix_cache_skip_name (const char * name) static
Definition at line 208 of file evict_candidates.c.
References BRIX_CACHE_EVICT_LOCK_NAME, BRIX_CACHE_LOCK_SUFFIX, BRIX_CACHE_PART_SUFFIX, and name.
Referenced by evict_collect_visit().
brix_cache_try_evict_lock()
ngx_int_t brix_cache_try_evict_lock (ngx_stream_brix_srv_conf_t * conf, char * lock_path, size_t lock_pathsz, ngx_log_t * log)
Definition at line 106 of file evict_candidates.c.
References BRIX_CACHE_EVICT_LOCK_NAME, brix_cache_state_root(), close(), log, open(), and stat().
Referenced by brix_cache_evict_if_needed(), and brix_cache_watermark_purge().
brix_cache_usage_measure()
ngx_int_t brix_cache_usage_measure (brix_cstore_t * cs, const char * root, brix_cache_fs_usage_t * usage)
Definition at line 65 of file evict_candidates.c.
References brix_cache_fs_usage(), brix_cstore_freespace(), and usage().
Referenced by brix_cache_evict_if_needed(), brix_cache_evict_one(), and brix_cache_purge_setup().
evict_collect_visit()
static ngx_int_t evict_collect_visit (const char * key, const brix_cache_cinfo_t * ci, const brix_sd_stat_t * stx, void * ctx) static
Definition at line 356 of file evict_candidates.c.
References brix_cache_add_candidate(), brix_cache_cinfo_dirty_extent(), brix_cache_sidecar_path(), brix_cache_skip_name(), brix_cache_evict_list_t::cache_root, key, brix_sd_stat_t::mtime, name, PATH_MAX, brix_sd_stat_t::size, stat(), and brix_cache_evict_list_t::state_root.
Referenced by brix_cache_collect_dir().