nginx-xrootd: src/auth/token/exchange.c File Reference
exchange.c File Reference
#include <ngx_core.h>
#include "auth/token/exchange.h"
#include <curl/curl.h>
Data Structures
struct brix_tx_sink_t
Macros
#define BRIX_TX_GRANT "urn:ietf:params:oauth:grant-type:token-exchange"
#define BRIX_TX_SUBJECT_TYPE "urn:ietf:params:oauth:token-type:access_token"
#define BRIX_TX_CONNECT_TIMEOUT 10L
#define BRIX_TX_TIMEOUT 30L
#define BRIX_TX_MAX_RESPONSE (64 * 1024)
Functions
static size_t brix_tx_write_cb (char *ptr, size_t size, size_t nmemb, void *userdata)
static char * brix_tx_cstr (ngx_pool_t *pool, const ngx_str_t *s)
static ngx_int_t brix_tx_append_field (CURL *curl, ngx_pool_t *pool, ngx_str_t *body, const char *name, const ngx_str_t *value)
static ngx_int_t brix_tx_build_body (CURL *curl, ngx_pool_t *pool, const ngx_str_t *subject_token, const ngx_str_t *audience, const ngx_str_t *scope, ngx_str_t *out_body)
static ngx_int_t brix_tx_parse_response (ngx_pool_t *pool, const u_char *doc, size_t len, ngx_str_t *out_token, ngx_log_t *log)
static ngx_int_t brix_tx_http_post (ngx_pool_t *pool, const char *endpoint, const ngx_str_t *body, const brix_token_exchange_conf_t *cf, brix_tx_sink_t *sink, ngx_log_t *log)
ngx_int_t brix_token_exchange (ngx_pool_t *pool, const ngx_str_t *subject_token, const ngx_str_t *audience, const ngx_str_t *scope, const brix_token_exchange_conf_t *cf, ngx_str_t *out_token, ngx_log_t *log)
Macro Definition Documentation
BRIX_TX_CONNECT_TIMEOUT
#define BRIX_TX_CONNECT_TIMEOUT 10L
Definition at line 34 of file exchange.c.
BRIX_TX_GRANT
#define BRIX_TX_GRANT "urn:ietf:params:oauth:grant-type:token-exchange"
Definition at line 32 of file exchange.c.
BRIX_TX_MAX_RESPONSE
#define BRIX_TX_MAX_RESPONSE (64 * 1024)
Definition at line 36 of file exchange.c.
BRIX_TX_SUBJECT_TYPE
#define BRIX_TX_SUBJECT_TYPE "urn:ietf:params:oauth:token-type:access_token"
Definition at line 33 of file exchange.c.
BRIX_TX_TIMEOUT
#define BRIX_TX_TIMEOUT 30L
Definition at line 35 of file exchange.c.
Function Documentation
brix_token_exchange()
ngx_int_t brix_token_exchange (ngx_pool_t * pool, const ngx_str_t * subject_token, const ngx_str_t * audience, const ngx_str_t * scope, const brix_token_exchange_conf_t * cf, ngx_str_t * out_token, ngx_log_t * log)
Definition at line 337 of file exchange.c.
References brix_tx_build_body(), brix_tx_cstr(), brix_tx_http_post(), BRIX_TX_MAX_RESPONSE, brix_tx_parse_response(), brix_tx_sink_t::buf, brix_tx_sink_t::cap, brix_token_exchange_conf_t::endpoint, brix_tx_sink_t::len, log, ngx_pnalloc(), and scope.
Referenced by brix_vfs_deleg_exchange().
brix_tx_append_field()
static ngx_int_t brix_tx_append_field (CURL * curl, ngx_pool_t * pool, ngx_str_t * body, const char * name, const ngx_str_t * value) static
Definition at line 108 of file exchange.c.
References brix_tx_cstr(), name, and ngx_pnalloc().
Referenced by brix_tx_build_body().
brix_tx_build_body()
static ngx_int_t brix_tx_build_body (CURL * curl, ngx_pool_t * pool, const ngx_str_t * subject_token, const ngx_str_t * audience, const ngx_str_t * scope, ngx_str_t * out_body) static
Definition at line 168 of file exchange.c.
References brix_tx_append_field(), BRIX_TX_GRANT, BRIX_TX_SUBJECT_TYPE, and scope.
Referenced by brix_token_exchange().
brix_tx_cstr()
static char * brix_tx_cstr (ngx_pool_t * pool, const ngx_str_t * s) static
Definition at line 80 of file exchange.c.
References ngx_memcpy, ngx_pnalloc(), and s.
Referenced by brix_token_exchange(), brix_tx_append_field(), and brix_tx_http_post().
brix_tx_http_post()
static ngx_int_t brix_tx_http_post (ngx_pool_t * pool, const char * endpoint, const ngx_str_t * body, const brix_token_exchange_conf_t * cf, brix_tx_sink_t * sink, ngx_log_t * log) static
Definition at line 267 of file exchange.c.
References BRIX_TX_CONNECT_TIMEOUT, brix_tx_cstr(), BRIX_TX_TIMEOUT, brix_tx_write_cb(), brix_token_exchange_conf_t::client_id, brix_token_exchange_conf_t::client_secret, code, and log.
Referenced by brix_token_exchange().
brix_tx_parse_response()
static ngx_int_t brix_tx_parse_response (ngx_pool_t * pool, const u_char * doc, size_t len, ngx_str_t * out_token, ngx_log_t * log) static
Definition at line 204 of file exchange.c.
References log, ngx_memcpy, and ngx_pnalloc().
Referenced by brix_token_exchange().
brix_tx_write_cb()
static size_t brix_tx_write_cb (char * ptr, size_t size, size_t nmemb, void * userdata) static
Definition at line 57 of file exchange.c.
References brix_tx_sink_t::buf, brix_tx_sink_t::cap, brix_tx_sink_t::len, and ngx_memcpy.
Referenced by brix_tx_http_post().