nginx-xrootd: src/core/config/export_guard.h File Reference
export_guard.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <stdlib.h>
#include <limits.h>
#include "fs/path/beneath.h"
Functions
static ngx_int_t brix_assert_dir_outside_export (ngx_conf_t *cf, const char *label, const char *export_canon, const char *dir)
Function Documentation
brix_assert_dir_outside_export()
static ngx_int_t brix_assert_dir_outside_export (ngx_conf_t * cf, const char * label, const char * export_canon, const char * dir) inline static
Definition at line 35 of file export_guard.h.
References brix_beneath_strip_root(), and PATH_MAX.
Referenced by brix_server_setup_export(), s3_merge_export(), and webdav_prepare_stage_and_cache().