nginx-xrootd: src/protocols/root/write/ext_ops.c File Reference
ext_ops.c File Reference
#include "core/ngx_brix_module.h"
#include "ext_ops.h"
#include "core/compat/error_mapping.h"
#include "core/compat/vendor_ext.h"
#include "protocols/root/path/op_path.h"
#include "auth/authz/auth_gate.h"
#include "fs/path/path.h"
#include "fs/vfs/vfs.h"
#include <arpa/inet.h>
#include <endian.h>
#include <errno.h>
#include <string.h>
#include <time.h>
Functions
ngx_int_t brix_handle_setattr (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_handle_symlink (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_handle_link (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_handle_readlink (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_handle_link()
ngx_int_t brix_handle_link (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 184 of file ext_ops.c.
References xrdw_twopath_req_t::arg1len, brix_auth_gate(), BRIX_AUTH_UPDATE, brix_extract_path(), brix_kxr_from_errno(), brix_link_confined_canon(), BRIX_MAX_PATH, BRIX_OP_MKDIR, BRIX_PATH_EXISTING, brix_path_resolve_beneath(), BRIX_PATH_WRITE, BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_send_error(), c, ngx_stream_brix_srv_conf_t::common, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::hdr_buf, kXR_ArgInvalid, kXR_ArgMissing, kXR_NotFound, PATH_MAX, brix_ctx_recv_t::payload, brix_ctx_t::recv, ngx_http_brix_shared_conf_t::root_canon, brix_ctx_t::write_rc, and xrdw_twopath_req_unpack().
Referenced by brix_dispatch_write_opcode().
brix_handle_readlink()
ngx_int_t brix_handle_readlink (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 250 of file ext_ops.c.
References brix_auth_gate(), BRIX_AUTH_READ, brix_kxr_from_errno(), brix_log_access(), BRIX_MAX_PATH, BRIX_OP_OK, BRIX_OP_STAT, BRIX_PATH_NOEXIST, brix_readlink_confined_canon(), brix_resolve_op_path(), BRIX_RETURN_ERR, brix_send_ok(), c, ngx_stream_brix_srv_conf_t::common, kXR_ok, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, and brix_ctx_t::write_rc.
Referenced by brix_dispatch_read_opcode().
brix_handle_setattr()
ngx_int_t brix_handle_setattr (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 41 of file ext_ops.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_sd_setattr_t::atime, xrdp_setattr_t::atime_nsec, xrdp_setattr_t::atime_sec, brix_auth_gate(), BRIX_AUTH_UPDATE, brix_extract_path(), brix_kxr_from_errno(), BRIX_MAX_PATH, BRIX_OP_CHMOD, BRIX_PATH_EXISTING, brix_path_resolve_beneath(), BRIX_PROTO_ROOT, BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_send_error(), BRIX_SETATTR_PREFIX_LEN, brix_vfs_ctx_init(), brix_vfs_setattr(), c, ngx_stream_brix_srv_conf_t::common, brix_ctx_recv_t::cur_dlen, xrdp_setattr_t::flags, xrdp_setattr_t::gid, brix_sd_setattr_t::gid, kXR_ArgInvalid, kXR_ArgMissing, kXR_NotFound, kXR_sa_owner, kXR_sa_times, brix_sd_setattr_t::mtime, xrdp_setattr_t::mtime_nsec, xrdp_setattr_t::mtime_sec, PATH_MAX, brix_ctx_recv_t::payload, brix_vfs_ctx_t::pool, brix_ctx_t::recv, ngx_http_brix_shared_conf_t::root_canon, brix_sd_setattr_t::set_owner, brix_sd_setattr_t::set_times, xrdp_setattr_t::uid, brix_sd_setattr_t::uid, brix_ctx_t::write_rc, and xrdp_setattr_prefix_unpack().
Referenced by brix_dispatch_write_opcode().
brix_handle_symlink()
ngx_int_t brix_handle_symlink (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 121 of file ext_ops.c.
References xrdw_twopath_req_t::arg1len, brix_auth_gate(), BRIX_AUTH_UPDATE, brix_extract_path(), brix_kxr_from_errno(), BRIX_MAX_PATH, BRIX_OP_MKDIR, brix_path_resolve_beneath(), BRIX_PATH_WRITE, BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_send_error(), brix_symlink_confined_canon(), c, ngx_stream_brix_srv_conf_t::common, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::hdr_buf, kXR_ArgInvalid, kXR_ArgMissing, kXR_NotFound, PATH_MAX, brix_ctx_recv_t::payload, brix_ctx_t::recv, ngx_http_brix_shared_conf_t::root_canon, brix_ctx_t::write_rc, and xrdw_twopath_req_unpack().
Referenced by brix_dispatch_write_opcode().