nginx-xrootd: src/net/cms/fanout.c File Reference
fanout.c File Reference
#include "fanout.h"
#include "cms_internal.h"
#include "server.h"
#include "forward.h"
#include "recv_internal.h"
#include "net/manager/pending.h"
#include "net/manager/registry.h"
#include "protocols/root/protocol/opcodes.h"
#include "protocols/root/response/response.h"
#include "protocols/root/connection/event_sched.h"
Data Structures
struct brix_cms_fanout_slot_t
Macros
#define BRIX_CMS_FANOUT_SLOTS 16 /* concurrent in-flight fan-outs / worker */
#define BRIX_CMS_FANOUT_NODES 32 /* holder connections per fan-out */
Functions
static void brix_cms_fanout_finalize (brix_cms_fanout_slot_t *slot, ngx_log_t *log)
static void brix_cms_fanout_deadline (ngx_event_t *ev)
static brix_cms_fanout_slot_t * brix_cms_fanout_slot_get (uint32_t sid)
static void brix_cms_fanout_slot_free (brix_cms_fanout_slot_t *slot)
static int brix_cms_fanout_op_code (uint16_t reqid, u_char *code)
static ngx_uint_t brix_cms_fanout_collect_eligible (const char *path, brix_cms_srv_ctx_t **elig)
static brix_cms_fanout_slot_t * brix_cms_fanout_slot_alloc (void)
static ngx_uint_t brix_cms_fanout_send_all (brix_cms_srv_ctx_t **elig, ngx_uint_t n_elig, u_char code, uint32_t sid, const char *ident, const char *path, ngx_log_t *log)
ngx_int_t brix_cms_fanout_mutation (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *path)
void brix_cms_fanout_note_error (uint32_t streamid, uint32_t ecode, const char *text, ngx_log_t *log)
Variables
static brix_cms_fanout_slot_t brix_fanout_slots [16]
Macro Definition Documentation
BRIX_CMS_FANOUT_NODES
#define BRIX_CMS_FANOUT_NODES 32 /* holder connections per fan-out */
Definition at line 39 of file fanout.c.
BRIX_CMS_FANOUT_SLOTS
#define BRIX_CMS_FANOUT_SLOTS 16 /* concurrent in-flight fan-outs / worker */
Definition at line 38 of file fanout.c.
Function Documentation
brix_cms_fanout_collect_eligible()
static ngx_uint_t brix_cms_fanout_collect_eligible (const char * path, brix_cms_srv_ctx_t ** elig) static
Definition at line 185 of file fanout.c.
References BRIX_CMS_FANOUT_NODES, brix_cms_srv_node_at(), brix_cms_srv_node_count(), brix_srv_is_blacklisted(), brix_srv_paths_cover(), brix_cms_srv_ctx_t::c, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, brix_cms_srv_ctx_t::paths, and brix_cms_srv_ctx_t::port.
Referenced by brix_cms_fanout_mutation().
brix_cms_fanout_deadline()
static void brix_cms_fanout_deadline (ngx_event_t * ev) static
Definition at line 59 of file fanout.c.
References brix_cms_fanout_finalize().
Referenced by brix_cms_fanout_mutation().
brix_cms_fanout_finalize()
static void brix_cms_fanout_finalize (brix_cms_fanout_slot_t * slot, ngx_log_t * log) static
Definition at line 94 of file fanout.c.
References brix_cms_client_conn_by_fd(), brix_cms_fanout_slot_free(), brix_pending_lookup(), brix_pending_remove(), brix_pending_unlock(), brix_schedule_read_resume(), brix_send_error(), brix_send_ok(), brix_pending_locate_t::client_streamid, brix_ctx_t::cms_wait_streamid, brix_pending_locate_t::conn_fd, brix_pending_locate_t::conn_number, brix_ctx_recv_t::cur_streamid, brix_cms_fanout_slot_t::errtext, brix_cms_fanout_slot_t::expected, brix_cms_fanout_slot_t::got_err, kXR_FSError, log, ngx_stream_brix_module, brix_ctx_t::recv, brix_cms_fanout_slot_t::sid, brix_ctx_t::state, brix_cms_fanout_slot_t::worst_err, XRD_ST_REQ_HEADER, and XRD_ST_WAITING_CMS.
Referenced by brix_cms_fanout_deadline(), and brix_cms_fanout_note_error().
brix_cms_fanout_mutation()
ngx_int_t brix_cms_fanout_mutation (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * path)
Definition at line 245 of file fanout.c.
References brix_cms_fanout_collect_eligible(), brix_cms_fanout_deadline(), BRIX_CMS_FANOUT_NODES, brix_cms_fanout_op_code(), brix_cms_fanout_send_all(), brix_cms_fanout_slot_alloc(), brix_cms_srv_next_streamid(), brix_pending_insert(), brix_pending_remove(), brix_srv_count_matching(), c, brix_ctx_t::cms_wait_streamid, code, brix_ctx_recv_t::cur_reqid, brix_ctx_recv_t::cur_streamid, brix_cms_fanout_slot_t::deadline, brix_cms_fanout_slot_t::expected, brix_cms_fanout_slot_t::in_use, brix_ctx_t::recv, brix_cms_fanout_slot_t::sid, brix_ctx_t::state, and XRD_ST_WAITING_CMS.
Referenced by manager_redirect_mutation().
brix_cms_fanout_note_error()
void brix_cms_fanout_note_error (uint32_t streamid, uint32_t ecode, const char * text, ngx_log_t * log)
Definition at line 323 of file fanout.c.
References brix_cms_fanout_finalize(), brix_cms_fanout_slot_get(), brix_cms_fanout_slot_t::errtext, brix_cms_fanout_slot_t::expected, brix_cms_fanout_slot_t::got_err, log, and brix_cms_fanout_slot_t::worst_err.
Referenced by cms_srv_frame_error().
brix_cms_fanout_op_code()
static int brix_cms_fanout_op_code (uint16_t reqid, u_char * code) static
Definition at line 168 of file fanout.c.
References CMS_RR_RM, CMS_RR_RMDIR, code, kXR_rm, and kXR_rmdir.
Referenced by brix_cms_fanout_mutation().
brix_cms_fanout_send_all()
static ngx_uint_t brix_cms_fanout_send_all (brix_cms_srv_ctx_t ** elig, ngx_uint_t n_elig, u_char code, uint32_t sid, const char * ident, const char * path, ngx_log_t * log) static
Definition at line 223 of file fanout.c.
References brix_cms_forward_to_node(), c, code, host, log, and port.
Referenced by brix_cms_fanout_mutation().
brix_cms_fanout_slot_alloc()
static brix_cms_fanout_slot_t * brix_cms_fanout_slot_alloc (void) static
Definition at line 208 of file fanout.c.
References BRIX_CMS_FANOUT_SLOTS, brix_fanout_slots, and in_use.
Referenced by brix_cms_fanout_mutation().
brix_cms_fanout_slot_free()
static void brix_cms_fanout_slot_free (brix_cms_fanout_slot_t * slot) static
Definition at line 78 of file fanout.c.
References brix_cms_fanout_slot_t::deadline, and brix_cms_fanout_slot_t::in_use.
Referenced by brix_cms_fanout_finalize().
brix_cms_fanout_slot_get()
static brix_cms_fanout_slot_t * brix_cms_fanout_slot_get (uint32_t sid) static
Definition at line 65 of file fanout.c.
References BRIX_CMS_FANOUT_SLOTS, brix_fanout_slots, and in_use.
Referenced by brix_cms_fanout_note_error().
Variable Documentation
brix_fanout_slots
brix_cms_fanout_slot_t brix_fanout_slots[16] static
Definition at line 51 of file fanout.c.
Referenced by brix_cms_fanout_slot_alloc(), and brix_cms_fanout_slot_get().