nginx-xrootd: src/net/cms/fanout.h File Reference
fanout.h File Reference
#include "core/ngx_brix_module.h"
Functions
ngx_int_t brix_cms_fanout_mutation (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *path)
void brix_cms_fanout_note_error (uint32_t streamid, uint32_t ecode, const char *text, ngx_log_t *log)
Function Documentation
brix_cms_fanout_mutation()
ngx_int_t brix_cms_fanout_mutation (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * path)
Definition at line 245 of file fanout.c.
References brix_cms_fanout_collect_eligible(), brix_cms_fanout_deadline(), BRIX_CMS_FANOUT_NODES, brix_cms_fanout_op_code(), brix_cms_fanout_send_all(), brix_cms_fanout_slot_alloc(), brix_cms_srv_next_streamid(), brix_pending_insert(), brix_pending_remove(), brix_srv_count_matching(), c, brix_ctx_t::cms_wait_streamid, code, brix_ctx_recv_t::cur_reqid, brix_ctx_recv_t::cur_streamid, brix_cms_fanout_slot_t::deadline, brix_cms_fanout_slot_t::expected, brix_cms_fanout_slot_t::in_use, brix_ctx_t::recv, brix_cms_fanout_slot_t::sid, brix_ctx_t::state, and XRD_ST_WAITING_CMS.
Referenced by manager_redirect_mutation().
brix_cms_fanout_note_error()
void brix_cms_fanout_note_error (uint32_t streamid, uint32_t ecode, const char * text, ngx_log_t * log)
Definition at line 323 of file fanout.c.
References brix_cms_fanout_finalize(), brix_cms_fanout_slot_get(), brix_cms_fanout_slot_t::errtext, brix_cms_fanout_slot_t::expected, brix_cms_fanout_slot_t::got_err, log, and brix_cms_fanout_slot_t::worst_err.
Referenced by cms_srv_frame_error().