nginx-xrootd: client/lib/fs/fattr.c File Reference
fattr.c File Reference
#include "brix.h"
#include "core/compat/fattr_codec.h"
#include <arpa/inet.h>
#include <stdlib.h>
#include <string.h>
Functions
static uint8_t * fattr_build_payload (const char *path, const char *name, const void *value, size_t vlen, int with_value, uint32_t *plen)
static int fattr_parse_status (uint8_t *body, uint32_t blen, uint16_t *rc, uint8_t **after, brix_status *st)
int brix_fattr_get (brix_conn *c, const char *path, const char *name, void *value, size_t bufsz, size_t *out_vlen, brix_status *st)
static int fattr_set_or_del (brix_conn *c, const char *path, const char *name, const void *value, size_t vlen, int with_value, int subcode, int options, brix_status *st)
int brix_fattr_set (brix_conn *c, const char *path, const char *name, const void *value, size_t vlen, int create_only, brix_status *st)
int brix_fattr_del (brix_conn *c, const char *path, const char *name, brix_status *st)
int brix_fattr_list (brix_conn *c, const char *path, char *out, size_t bufsz, size_t *out_len, brix_status *st)
Function Documentation
brix_fattr_del()
int brix_fattr_del (brix_conn * c, const char * path, const char * name, brix_status * st)
Definition at line 192 of file fattr.c.
References c, fattr_set_or_del(), kXR_fattrDel, and name.
Referenced by battery_root(), do_xattr(), op_fadel(), and xfs_removexattr().
brix_fattr_get()
int brix_fattr_get (brix_conn * c, const char * path, const char * name, void * value, size_t bufsz, size_t * out_vlen, brix_status * st)
Definition at line 86 of file fattr.c.
References brix_roundtrip(), brix_status_set(), c, fattr_build_payload(), fattr_parse_status(), kXR_fattr, kXR_fattrGet, name, ClientFattrRequest::requestid, xrdw_fattr_req_t::subcode, XRDC_EPROTO, XRDC_ESOCK, and xrdw_fattr_req_pack().
Referenced by battery_root(), do_xattr(), op_faget(), and xfs_getxattr().
brix_fattr_list()
int brix_fattr_list (brix_conn * c, const char * path, char * out, size_t bufsz, size_t * out_len, brix_status * st)
Definition at line 198 of file fattr.c.
References brix_roundtrip(), brix_status_set(), c, kXR_fattr, kXR_fattrList, ClientFattrRequest::requestid, xrdw_fattr_req_t::subcode, XRDC_ESOCK, and xrdw_fattr_req_pack().
Referenced by op_falist(), xattr_ls(), and xfs_listxattr().
brix_fattr_set()
int brix_fattr_set (brix_conn * c, const char * path, const char * name, const void * value, size_t vlen, int create_only, brix_status * st)
Definition at line 184 of file fattr.c.
References c, fattr_set_or_del(), kXR_fa_isNew, kXR_fattrSet, and name.
Referenced by battery_root(), do_xattr(), op_faset(), and xfs_setxattr().
fattr_build_payload()
static uint8_t * fattr_build_payload (const char * path, const char * name, const void * value, size_t vlen, int with_value, uint32_t * plen) static
Definition at line 29 of file fattr.c.
References name.
Referenced by brix_fattr_get(), and fattr_set_or_del().
fattr_parse_status()
static int fattr_parse_status (uint8_t * body, uint32_t blen, uint16_t * rc, uint8_t ** after, brix_status * st) static
Definition at line 64 of file fattr.c.
References brix_status_set(), XRDC_EPROTO, and xrdp_fattr_nvec_parse().
Referenced by brix_fattr_get(), and fattr_set_or_del().
fattr_set_or_del()
static int fattr_set_or_del (brix_conn * c, const char * path, const char * name, const void * value, size_t vlen, int with_value, int subcode, int options, brix_status * st) static
Definition at line 142 of file fattr.c.
References brix_roundtrip(), brix_status_set(), c, fattr_build_payload(), fattr_parse_status(), kXR_fattr, kXR_fattrSet, name, ClientFattrRequest::requestid, xrdw_fattr_req_t::subcode, XRDC_ESOCK, and xrdw_fattr_req_pack().
Referenced by brix_fattr_del(), and brix_fattr_set().