nginx-xrootd: src/core/compat/fattr_codec.h File Reference
fattr_codec.h File Reference
#include <stddef.h>
#include <stdint.h>
Functions
int xrdp_fattr_nvec_parse (const uint8_t *buf, size_t len, size_t off, uint16_t *rc, const uint8_t **name, size_t *nlen, size_t *next_off)
Function Documentation
xrdp_fattr_nvec_parse()
int xrdp_fattr_nvec_parse (const uint8_t * buf, size_t len, size_t off, uint16_t * rc, const uint8_t ** name, size_t * nlen, size_t * next_off)
Definition at line 10 of file fattr_codec.c.
References name.
Referenced by brix_cache_origin_getfattr(), fattr_parse_nvec(), fattr_parse_status(), and origin_fattr_set_or_del().