nginx-xrootd: src/protocols/root/connection/fd_table.h File Reference
fd_table.h File Reference
#include "core/ngx_brix_module.h"
Functions
int brix_alloc_fhandle (brix_ctx_t *ctx)
ngx_int_t brix_set_fhandle_path (brix_ctx_t *ctx, ngx_connection_t *c, int handle_index, const char *path)
void brix_free_fhandle (brix_ctx_t *ctx, int handle_index)
void brix_close_all_files (brix_ctx_t *ctx)
int brix_ctx_has_open_file (const brix_ctx_t *ctx)
ngx_int_t brix_ensure_read_handle (brix_ctx_t *ctx, ngx_connection_t *c, int handle_index)
ngx_flag_t brix_validate_file_handle (brix_ctx_t *ctx, ngx_connection_t *c, int handle_index, const char *verb, ngx_uint_t op, ngx_int_t *rc)
ngx_flag_t brix_validate_read_handle (brix_ctx_t *ctx, ngx_connection_t *c, int handle_index, const char *verb, ngx_uint_t op, ngx_int_t *rc)
ngx_flag_t brix_validate_write_handle (brix_ctx_t *ctx, ngx_connection_t *c, int handle_index, const char *verb, ngx_uint_t op, ngx_int_t *rc)
Function Documentation
brix_alloc_fhandle()
int brix_alloc_fhandle (brix_ctx_t * ctx)
Definition at line 19 of file fd_table.c.
References BRIX_MAX_FILES, brix_file_t::fd, and brix_ctx_t::files.
Referenced by brix_open_resolved_file(), brix_ssi_open(), brix_tpc_prepare_pull(), and brix_zip_open_member().
brix_close_all_files()
void brix_close_all_files (brix_ctx_t * ctx)
Definition at line 251 of file fd_table_teardown.c.
References brix_free_fhandle(), and BRIX_MAX_FILES.
Referenced by brix_aio_resume_fail(), brix_handle_endsess(), brix_recv_header_prep(), brix_recv_pre_loop(), brix_recv_read_frame(), brix_run_deferred_teardown(), brix_start_tls(), brix_tls_handshake_done(), ngx_stream_brix_recv(), and ngx_stream_brix_send().
brix_ctx_has_open_file()
int brix_ctx_has_open_file (const brix_ctx_t * ctx)
Definition at line 42 of file fd_table.c.
References BRIX_MAX_FILES, brix_file_t::fd, and brix_ctx_t::files.
Referenced by brix_recv_header_prep().
brix_ensure_read_handle()
ngx_int_t brix_ensure_read_handle (brix_ctx_t * ctx, ngx_connection_t * c, int handle_index)
Definition at line 214 of file fd_table.c.
References brix_ctx_t::bound_sessid, brix_free_fhandle(), brix_local_file_matches_shared_handle(), BRIX_MAX_FILES, brix_reopen_bound_read_handle(), brix_session_handle_lookup_hint(), c, brix_file_t::fd, brix_ctx_t::files, brix_ctx_t::is_bound, brix_file_t::path, brix_file_t::sd_obj, and brix_file_t::shared_handle_slot_hint.
Referenced by brix_validate_read_handle().
brix_free_fhandle()
void brix_free_fhandle (brix_ctx_t * ctx, int handle_index)
Definition at line 217 of file fd_table_teardown.c.
References BRIX_MAX_FILES, brix_session_handle_unpublish(), brix_wt_mark_clean(), brix_file_t::fd, fhandle_release_descriptors(), fhandle_release_staging_files(), fhandle_reset_slot(), brix_ctx_t::files, brix_ctx_t::is_bound, brix_ctx_t::login, ngx_stream_brix_module, brix_ctx_login_t::sessid, and brix_ctx_t::session.
Referenced by brix_close_all_files(), brix_close_posc_commit(), brix_close_staged_commit(), brix_ensure_read_handle(), brix_handle_close(), brix_open_build_response(), brix_open_set_handle_path(), brix_reopen_bound_read_handle(), brix_ssi_open(), brix_tpc_prepare_pull(), brix_zip_open_member(), tpc_done_sync_fail(), tpc_done_teardown_dst(), and zip_send_open_reply().
brix_set_fhandle_path()
ngx_int_t brix_set_fhandle_path (brix_ctx_t * ctx, ngx_connection_t * c, int handle_index, const char * path)
Definition at line 60 of file fd_table.c.
References BRIX_MAX_FILES, c, brix_ctx_t::files, ngx_memcpy, and brix_file_t::path.
Referenced by brix_open_set_handle_path(), brix_reopen_bound_read_handle(), brix_tpc_prepare_pull(), and brix_zip_open_member().
brix_validate_file_handle()
ngx_flag_t brix_validate_file_handle (brix_ctx_t * ctx, ngx_connection_t * c, int handle_index, const char * verb, ngx_uint_t op, ngx_int_t * rc)
Definition at line 270 of file fd_table.c.
References BRIX_BAIL_ERR, BRIX_MAX_FILES, c, brix_file_t::fd, brix_ctx_t::files, kXR_FileNotOpen, op, brix_file_t::sd_obj, and brix_file_t::writer.
Referenced by brix_handle_close(), brix_handle_sync(), brix_handle_truncate(), brix_query_opaqug(), brix_query_visa(), brix_validate_write_handle(), and stat_query_handle().
brix_validate_read_handle()
ngx_flag_t brix_validate_read_handle (brix_ctx_t * ctx, ngx_connection_t * c, int handle_index, const char * verb, ngx_uint_t op, ngx_int_t * rc)
Definition at line 295 of file fd_table.c.
References BRIX_BAIL_ERR, brix_ensure_read_handle(), c, brix_ctx_t::files, kXR_FileNotOpen, kXR_NotAuthorized, kXR_ServerError, op, brix_file_t::path, and brix_file_t::readable.
Referenced by brix_handle_clone(), brix_pgread_parse_validate(), brix_readv_validate_and_size(), and read_validate_req().
brix_validate_write_handle()
ngx_flag_t brix_validate_write_handle (brix_ctx_t * ctx, ngx_connection_t * c, int handle_index, const char * verb, ngx_uint_t op, ngx_int_t * rc)
Definition at line 329 of file fd_table.c.
References BRIX_BAIL_ERR, brix_validate_file_handle(), c, brix_ctx_t::files, kXR_NotAuthorized, op, brix_file_t::path, and brix_file_t::writable.
Referenced by brix_handle_chkpoint(), brix_handle_clone(), brix_handle_write(), and pgwrite_parse_validate().