nginx-xrootd: src/protocols/root/connection/fd_table_teardown.c File Reference
fd_table_teardown.c File Reference
#include "fd_table.h"
#include "fs/vfs/vfs.h"
#include "protocols/root/session/registry.h"
#include "fs/cache/writethrough_metrics.h"
#include "protocols/root/write/pgw_fob.h"
#include "fs/backend/csi_tagstore.h"
#include "protocols/root/zip/zip_member.h"
#include "protocols/ssi/ssi.h"
#include <errno.h>
#include <string.h>
#include <unistd.h>
Functions
static void fhandle_unlink_staging (const char *abs_path, const char *root_canon, ngx_log_t *log)
static void fhandle_release_descriptors (brix_file_t *file)
static void fhandle_release_staging_files (brix_file_t *file, const char *root_canon, ngx_log_t *tlog)
static void fhandle_reset_slot (brix_file_t *file)
void brix_free_fhandle (brix_ctx_t *ctx, int handle_index)
void brix_close_all_files (brix_ctx_t *ctx)
Function Documentation
brix_close_all_files()
void brix_close_all_files (brix_ctx_t * ctx)
Definition at line 251 of file fd_table_teardown.c.
References brix_free_fhandle(), and BRIX_MAX_FILES.
Referenced by brix_aio_resume_fail(), brix_handle_endsess(), brix_recv_header_prep(), brix_recv_pre_loop(), brix_recv_read_frame(), brix_run_deferred_teardown(), brix_start_tls(), brix_tls_handshake_done(), ngx_stream_brix_recv(), and ngx_stream_brix_send().
brix_free_fhandle()
void brix_free_fhandle (brix_ctx_t * ctx, int handle_index)
Definition at line 217 of file fd_table_teardown.c.
References BRIX_MAX_FILES, brix_session_handle_unpublish(), brix_wt_mark_clean(), brix_file_t::fd, fhandle_release_descriptors(), fhandle_release_staging_files(), fhandle_reset_slot(), brix_ctx_t::files, brix_ctx_t::is_bound, brix_ctx_t::login, ngx_stream_brix_module, brix_ctx_login_t::sessid, and brix_ctx_t::session.
Referenced by brix_close_all_files(), brix_close_posc_commit(), brix_close_staged_commit(), brix_ensure_read_handle(), brix_handle_close(), brix_open_build_response(), brix_open_set_handle_path(), brix_reopen_bound_read_handle(), brix_ssi_open(), brix_tpc_prepare_pull(), brix_zip_open_member(), tpc_done_sync_fail(), tpc_done_teardown_dst(), and zip_send_open_reply().
fhandle_release_descriptors()
static void fhandle_release_descriptors (brix_file_t * file) static
Definition at line 58 of file fd_table_teardown.c.
References brix_csi_close(), brix_vfs_writer_abort(), close(), brix_file_t::csi, brix_file_t::fd, brix_file_t::sd_obj, brix_file_t::staged_committed, and brix_file_t::writer.
Referenced by brix_free_fhandle().
fhandle_release_staging_files()
static void fhandle_release_staging_files (brix_file_t * file, const char * root_canon, ngx_log_t * tlog) static
Definition at line 100 of file fd_table_teardown.c.
References brix_tpc_registry_remove(), brix_file_t::ckp_path, fhandle_unlink_staging(), brix_file_t::is_resume, brix_file_t::path, brix_file_t::posc_final_path, and brix_file_t::tpc_transfer_id.
Referenced by brix_free_fhandle().
fhandle_reset_slot()
static void fhandle_reset_slot (brix_file_t * file) static
Definition at line 148 of file fd_table_teardown.c.
References brix_pgw_fob_reset(), brix_ssi_handle_cleanup(), brix_zip_handle_cleanup(), brix_file_t::bytes_read, brix_file_t::bytes_written, brix_file_t::cached_size, brix_file_t::ckp_path, brix_file_t::ckp_size, brix_file_t::device, brix_file_t::fd, brix_file_t::from_cache, brix_file_t::inode, brix_file_t::is_regular, brix_file_t::is_resume, brix_file_t::open_time, brix_file_t::path, brix_file_t::posc_final_path, brix_file_t::read_ahead_end, brix_file_t::read_last_end, brix_file_t::readable, brix_file_t::sd_obj, brix_file_t::shared_handle_slot_hint, brix_file_t::ssi, brix_file_t::tpc_armed, brix_file_t::tpc_destination, brix_file_t::tpc_done, brix_file_t::tpc_key, brix_file_t::tpc_org, brix_file_t::tpc_src_host, brix_file_t::tpc_src_path, brix_file_t::tpc_src_port, brix_file_t::tpc_started, brix_file_t::tpc_token_mode, brix_file_t::tpc_transfer_id, brix_file_t::writable, brix_file_t::wrts_count, brix_file_t::wrts_enabled, brix_file_t::wrts_gen, brix_file_t::wrts_head, brix_file_t::wt_bytes_written, brix_file_t::wt_dirty_offset, brix_file_t::wt_enabled, brix_file_t::wt_flush_pending, brix_file_t::wt_flush_task, brix_file_t::wt_mode_bits, brix_file_t::wt_policy, brix_file_t::zip_comp_pos, brix_file_t::zip_comp_size, brix_file_t::zip_crc32, brix_file_t::zip_data_off, brix_file_t::zip_logical_pos, brix_file_t::zip_method, brix_file_t::zip_mode, and brix_file_t::zip_uncomp_size.
Referenced by brix_free_fhandle().
fhandle_unlink_staging()
static void fhandle_unlink_staging (const char * abs_path, const char * root_canon, ngx_log_t * log) static
Definition at line 34 of file fd_table_teardown.c.
References brix_vfs_unlink_path(), and log.
Referenced by fhandle_release_staging_files().