nginx-xrootd: src/protocols/root/connection/fd_table.c File Reference
fd_table.c File Reference
#include "fd_table.h"
#include "fs/vfs/vfs.h"
#include "protocols/root/session/registry.h"
#include "fs/cache/writethrough_metrics.h"
#include "protocols/root/write/pgw_fob.h"
#include "fs/backend/csi_tagstore.h"
#include "protocols/root/zip/zip_member.h"
#include "protocols/ssi/ssi.h"
#include <errno.h>
#include <string.h>
#include <unistd.h>
Functions
int brix_alloc_fhandle (brix_ctx_t *ctx)
int brix_ctx_has_open_file (const brix_ctx_t *ctx)
ngx_int_t brix_set_fhandle_path (brix_ctx_t *ctx, ngx_connection_t *c, int handle_index, const char *path)
static ngx_flag_t brix_local_file_matches_shared_handle (const brix_file_t *file, const brix_shared_handle_entry_t *shared)
static ngx_int_t brix_reopen_bound_read_handle (brix_ctx_t *ctx, ngx_connection_t *c, int handle_index, const brix_shared_handle_entry_t *shared)
ngx_int_t brix_ensure_read_handle (brix_ctx_t *ctx, ngx_connection_t *c, int handle_index)
ngx_flag_t brix_validate_file_handle (brix_ctx_t *ctx, ngx_connection_t *c, int handle_index, const char *verb, ngx_uint_t op, ngx_int_t *rc)
ngx_flag_t brix_validate_read_handle (brix_ctx_t *ctx, ngx_connection_t *c, int handle_index, const char *verb, ngx_uint_t op, ngx_int_t *rc)
ngx_flag_t brix_validate_write_handle (brix_ctx_t *ctx, ngx_connection_t *c, int handle_index, const char *verb, ngx_uint_t op, ngx_int_t *rc)
Function Documentation
brix_alloc_fhandle()
int brix_alloc_fhandle (brix_ctx_t * ctx)
Definition at line 19 of file fd_table.c.
References BRIX_MAX_FILES, brix_file_t::fd, and brix_ctx_t::files.
Referenced by brix_open_resolved_file(), brix_ssi_open(), brix_tpc_prepare_pull(), and brix_zip_open_member().
brix_ctx_has_open_file()
int brix_ctx_has_open_file (const brix_ctx_t * ctx)
Definition at line 42 of file fd_table.c.
References BRIX_MAX_FILES, brix_file_t::fd, and brix_ctx_t::files.
Referenced by brix_recv_header_prep().
brix_ensure_read_handle()
ngx_int_t brix_ensure_read_handle (brix_ctx_t * ctx, ngx_connection_t * c, int handle_index)
Definition at line 214 of file fd_table.c.
References brix_ctx_t::bound_sessid, brix_free_fhandle(), brix_local_file_matches_shared_handle(), BRIX_MAX_FILES, brix_reopen_bound_read_handle(), brix_session_handle_lookup_hint(), c, brix_file_t::fd, brix_ctx_t::files, brix_ctx_t::is_bound, brix_file_t::path, brix_file_t::sd_obj, and brix_file_t::shared_handle_slot_hint.
Referenced by brix_validate_read_handle().
brix_local_file_matches_shared_handle()
static ngx_flag_t brix_local_file_matches_shared_handle (const brix_file_t * file, const brix_shared_handle_entry_t * shared) static
Definition at line 93 of file fd_table.c.
References brix_file_t::device, brix_shared_handle_entry_t::device, brix_file_t::fd, brix_file_t::inode, brix_shared_handle_entry_t::inode, brix_file_t::path, brix_shared_handle_entry_t::path, brix_file_t::readable, and brix_shared_handle_entry_t::readable.
Referenced by brix_ensure_read_handle().
brix_reopen_bound_read_handle()
static ngx_int_t brix_reopen_bound_read_handle (brix_ctx_t * ctx, ngx_connection_t * c, int handle_index, const brix_shared_handle_entry_t * shared) static
Definition at line 113 of file fd_table.c.
References brix_free_fhandle(), brix_set_fhandle_path(), brix_vfs_open_fd_at(), brix_file_t::bytes_read, brix_file_t::bytes_written, c, brix_file_t::cached_size, close(), brix_file_t::device, brix_shared_handle_entry_t::device, brix_file_t::fd, brix_ctx_t::files, brix_file_t::from_cache, brix_shared_handle_entry_t::from_cache, fstat(), brix_file_t::inode, brix_shared_handle_entry_t::inode, brix_file_t::is_regular, ngx_stream_brix_module, open(), brix_file_t::open_time, brix_shared_handle_entry_t::path, brix_file_t::read_ahead_end, brix_file_t::read_last_end, brix_file_t::readable, brix_shared_handle_entry_t::readable, brix_ctx_t::session, stat(), and brix_file_t::writable.
Referenced by brix_ensure_read_handle().
brix_set_fhandle_path()
ngx_int_t brix_set_fhandle_path (brix_ctx_t * ctx, ngx_connection_t * c, int handle_index, const char * path)
Definition at line 60 of file fd_table.c.
References BRIX_MAX_FILES, c, brix_ctx_t::files, ngx_memcpy, and brix_file_t::path.
Referenced by brix_open_set_handle_path(), brix_reopen_bound_read_handle(), brix_tpc_prepare_pull(), and brix_zip_open_member().
brix_validate_file_handle()
ngx_flag_t brix_validate_file_handle (brix_ctx_t * ctx, ngx_connection_t * c, int handle_index, const char * verb, ngx_uint_t op, ngx_int_t * rc)
Definition at line 270 of file fd_table.c.
References BRIX_BAIL_ERR, BRIX_MAX_FILES, c, brix_file_t::fd, brix_ctx_t::files, kXR_FileNotOpen, op, brix_file_t::sd_obj, and brix_file_t::writer.
Referenced by brix_handle_close(), brix_handle_sync(), brix_handle_truncate(), brix_query_opaqug(), brix_query_visa(), brix_validate_write_handle(), and stat_query_handle().
brix_validate_read_handle()
ngx_flag_t brix_validate_read_handle (brix_ctx_t * ctx, ngx_connection_t * c, int handle_index, const char * verb, ngx_uint_t op, ngx_int_t * rc)
Definition at line 295 of file fd_table.c.
References BRIX_BAIL_ERR, brix_ensure_read_handle(), c, brix_ctx_t::files, kXR_FileNotOpen, kXR_NotAuthorized, kXR_ServerError, op, brix_file_t::path, and brix_file_t::readable.
Referenced by brix_handle_clone(), brix_pgread_parse_validate(), brix_readv_validate_and_size(), and read_validate_req().
brix_validate_write_handle()
ngx_flag_t brix_validate_write_handle (brix_ctx_t * ctx, ngx_connection_t * c, int handle_index, const char * verb, ngx_uint_t op, ngx_int_t * rc)
Definition at line 329 of file fd_table.c.
References BRIX_BAIL_ERR, brix_validate_file_handle(), c, brix_ctx_t::files, kXR_NotAuthorized, op, brix_file_t::path, and brix_file_t::writable.
Referenced by brix_handle_chkpoint(), brix_handle_clone(), brix_handle_write(), and pgwrite_parse_validate().