nginx-xrootd: src/fs/cache/fetch.c File Reference
fetch.c File Reference
#include "cache_internal.h"
#include "cache_admit.h"
#include "cache_storage.h"
#include "meta.h"
#include "verify.h"
#include "core/compat/checksum.h"
#include "fs/cache/origin/s3_transport.h"
#include "fs/backend/remote/sd_remote.h"
#include "fs/backend/xroot/sd_xroot.h"
#include "fs/backend/http/sd_http.h"
#include <fcntl.h>
#include <regex.h>
#include <spawn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>
Functions
static const char * brix_cache_fill_key (const brix_cache_fill_t *t)
static int brix_cache_commit_staged (brix_cache_fill_t *t, brix_sd_instance_t *inst, const char *key)
static int brix_cache_fill_from_source (brix_cache_fill_t *t, brix_sd_instance_t *source)
brix_sd_instance_t * brix_cache_build_wt_origin (const ngx_stream_brix_srv_conf_t *conf, ngx_log_t *log)
int brix_cache_fetch_origin (brix_cache_fill_t *t)
Variables
char ** environ
Function Documentation
brix_cache_build_wt_origin()
brix_sd_instance_t * brix_cache_build_wt_origin (const ngx_stream_brix_srv_conf_t * conf, ngx_log_t * log)
Definition at line 134 of file fetch.c.
References brix_sd_xroot_create_origin(), ngx_stream_brix_srv_conf_t::cache_origin_bearer, ngx_stream_brix_srv_conf_t::cache_origin_ca_dir, ngx_stream_brix_srv_conf_t::cache_origin_family, ngx_stream_brix_srv_conf_t::cache_origin_x509_proxy, log, brix_wt_conf_t::origin_host, brix_wt_conf_t::origin_port, and ngx_stream_brix_srv_conf_t::wt.
Referenced by cache_build_wt_stage().
brix_cache_commit_staged()
static int brix_cache_commit_staged (brix_cache_fill_t * t, brix_sd_instance_t * inst, const char * key) static
Definition at line 47 of file fetch.c.
References brix_cache_meta_from_stat(), brix_cache_meta_write(), brix_cache_set_error(), brix_cache_set_syserror(), brix_cache_sidecar_path(), BRIX_CACHE_VERIFY_OFF, brix_checksum_hex_obj(), brix_checksum_parse(), BRIX_SD_O_READ, brix_cache_fill_t::c, brix_cache_fill_t::cache_path, ngx_stream_brix_srv_conf_t::cache_root, ngx_stream_brix_srv_conf_t::cache_state_root, ngx_stream_brix_srv_conf_t::cache_verify, brix_cache_fill_t::conf, brix_cache_fill_t::file_size, hex(), key, kXR_IOError, kXR_ServerError, log, brix_sd_stat_t::mtime, brix_cache_fill_t::origin_cks_alg, brix_cache_fill_t::origin_cks_hex, PATH_MAX, brix_sd_stat_t::size, and stat().
Referenced by brix_cache_fill_from_source().
brix_cache_fetch_origin()
int brix_cache_fetch_origin (brix_cache_fill_t * t)
Definition at line 286 of file fetch.c.
References brix_cache_fill_from_source(), brix_cache_set_error(), kXR_ServerError, and brix_cache_fill_t::source_inst.
Referenced by brix_cache_fill_thread().
brix_cache_fill_from_source()
static int brix_cache_fill_from_source (brix_cache_fill_t * t, brix_sd_instance_t * source) static
Definition at line 165 of file fetch.c.
References brix_cache_admit(), brix_cache_commit_staged(), BRIX_CACHE_DECLINE, BRIX_CACHE_FETCH_CHUNK, brix_cache_fill_key(), brix_cache_set_error(), brix_cache_sink_pwrite(), brix_cache_storage(), BRIX_CACHE_VERIFY_OFF, brix_sd_backend_name(), BRIX_SD_O_READ, brix_sd_xroot_query_checksum(), ngx_stream_brix_srv_conf_t::cache_allow_prefixes, ngx_stream_brix_srv_conf_t::cache_deny_prefixes, ngx_stream_brix_srv_conf_t::cache_max_file_size, ngx_stream_brix_srv_conf_t::cache_verify, brix_cache_fill_t::clean_path, brix_cache_fill_t::conf, brix_cache_admit_cfg_t::deny_prefixes, brix_cache_sink_t::fd, brix_cache_fill_t::file_size, ngx_stream_brix_srv_conf_t::include_regex, key, kXR_IOError, kXR_NoMemory, kXR_NotFound, kXR_ServerError, brix_cache_sink_t::mem, brix_cache_sink_t::mem_cap, brix_cache_fill_t::origin_cks_alg, brix_cache_fill_t::origin_cks_hex, brix_cache_include_regex_conf_t::re, brix_cache_fill_t::result, brix_cache_include_regex_conf_t::set, and brix_cache_sink_t::staged.
Referenced by brix_cache_fetch_origin().
brix_cache_fill_key()
static const char * brix_cache_fill_key (const brix_cache_fill_t * t) static
Definition at line 30 of file fetch.c.
References brix_cache_fill_t::cache_path, ngx_stream_brix_srv_conf_t::cache_root, and brix_cache_fill_t::conf.
Referenced by brix_cache_fill_from_source().
Variable Documentation
environ
char** environ extern