nginx-xrootd: src/protocols/shared/file_serve.h File Reference
file_serve.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include "fs/vfs/vfs.h"
Data Structures
struct brix_http_serve_opts_t
struct brix_http_serve_result_t
Macros
#define BRIX_SERVE_RANGE_FULL 0
#define BRIX_SERVE_RANGE_PARTIAL 1
#define BRIX_SERVE_RANGE_UNSATISFIED 2
Typedefs
typedef void(* brix_http_pre_header_fn) (ngx_http_request_t *r, ngx_fd_t fd, off_t file_size, void *userdata)
Functions
ngx_int_t brix_http_serve_file_ranged (ngx_http_request_t *r, brix_vfs_file_t *fh, const brix_vfs_stat_t *vst, const char *fs_path, const brix_http_serve_opts_t *opts, brix_http_serve_result_t *result)
Macro Definition Documentation
BRIX_SERVE_RANGE_FULL
#define BRIX_SERVE_RANGE_FULL 0
Definition at line 10 of file file_serve.h.
BRIX_SERVE_RANGE_PARTIAL
#define BRIX_SERVE_RANGE_PARTIAL 1
Definition at line 11 of file file_serve.h.
BRIX_SERVE_RANGE_UNSATISFIED
#define BRIX_SERVE_RANGE_UNSATISFIED 2
Definition at line 12 of file file_serve.h.
Typedef Documentation
brix_http_pre_header_fn
typedef void(* brix_http_pre_header_fn) (ngx_http_request_t *r, ngx_fd_t fd, off_t file_size, void *userdata)
Definition at line 19 of file file_serve.h.
Function Documentation
brix_http_serve_file_ranged()
ngx_int_t brix_http_serve_file_ranged (ngx_http_request_t * r, brix_vfs_file_t * fh, const brix_vfs_stat_t * vst, const char * fs_path, const brix_http_serve_opts_t * opts, brix_http_serve_result_t * result)
Definition at line 419 of file file_serve.c.
References serve_ctx_t::backend_name, brix_dashboard_http_start_identity(), brix_http_parse_range(), brix_http_set_file_headers(), BRIX_SERVE_RANGE_FULL, BRIX_SERVE_RANGE_PARTIAL, brix_vfs_close(), brix_vfs_file_backend_name(), brix_vfs_file_fd(), brix_vfs_file_from_cache(), brix_vfs_file_path(), brix_vfs_file_sendfile_fd(), BRIX_XFER_DIR_READ, serve_ctx_t::cache_path, brix_http_range_t::end, brix_http_serve_opts_t::etag_flags, serve_ctx_t::fh, serve_ctx_t::from_cache, serve_ctx_t::fs_path, brix_http_serve_opts_t::identity, brix_vfs_stat_t::mtime, brix_http_serve_opts_t::op_name, serve_ctx_t::opts, brix_http_serve_opts_t::pre_header_send, brix_http_serve_opts_t::pre_header_ud, brix_http_range_t::present, serve_ctx_t::r, brix_http_serve_result_t::range_result, serve_ctx_t::range_start, serve_ctx_t::result, brix_http_range_t::satisfiable, serve_ctx_t::send_len, serve_apply_tcp_congestion(), SERVE_DONE, serve_range_unsatisfiable(), serve_send_memory_backed(), serve_send_sendfile(), serve_try_compressed(), brix_vfs_stat_t::size, brix_http_range_t::start, serve_ctx_t::vst, and brix_http_serve_opts_t::xfer_proto.
Referenced by cvmfs_tier_open_respond(), get_serve_full(), ngx_http_brix_dashboard_vfs_download_handler(), and s3_get_serve().