nginx-xrootd: src/protocols/shared/file_serve.c File Reference
file_serve.c File Reference
#include "file_serve.h"
#include "core/http/http_file_response.h"
#include "core/http/http_compress.h"
#include "core/compat/range.h"
#include "observability/dashboard/dashboard_tracking.h"
#include "observability/metrics/unified.h"
#include "fs/cache/open.h"
#include "protocols/webdav/webdav.h"
#include "protocols/root/connection/netopt.h"
#include <unistd.h>
Data Structures
struct serve_ctx_t
Macros
#define BRIX_SERVE_MEM_CHUNK (256 * 1024)
Enumerations
enum serve_disposition_t { SERVE_CONTINUE = 0 , SERVE_DONE }
Functions
static ngx_int_t brix_serve_memory_backed (ngx_http_request_t *r, brix_vfs_file_t *fh, off_t start, off_t len)
static void serve_apply_tcp_congestion (ngx_http_request_t *r)
static ngx_int_t serve_range_unsatisfiable (ngx_http_request_t *r, brix_vfs_file_t *fh, brix_http_serve_result_t *result, off_t total)
static void serve_record_body_accounting (const serve_ctx_t *sc, off_t bytes, ngx_uint_t from_cache, const char *cache_path)
static serve_disposition_t serve_try_compressed (const serve_ctx_t *sc, ngx_uint_t range_present, ngx_int_t *rc)
static ngx_int_t serve_send_memory_backed (const serve_ctx_t *sc)
static ngx_int_t serve_send_sendfile (const serve_ctx_t *sc, ngx_fd_t fd)
ngx_int_t brix_http_serve_file_ranged (ngx_http_request_t *r, brix_vfs_file_t *fh, const brix_vfs_stat_t *vst, const char *fs_path, const brix_http_serve_opts_t *opts, brix_http_serve_result_t *result)
Macro Definition Documentation
BRIX_SERVE_MEM_CHUNK
#define BRIX_SERVE_MEM_CHUNK (256 * 1024)
Definition at line 108 of file file_serve.c.
Enumeration Type Documentation
serve_disposition_t
enum serve_disposition_t
Enumerator
SERVE_CONTINUE
SERVE_DONE
Definition at line 65 of file file_serve.c.
Function Documentation
brix_http_serve_file_ranged()
ngx_int_t brix_http_serve_file_ranged (ngx_http_request_t * r, brix_vfs_file_t * fh, const brix_vfs_stat_t * vst, const char * fs_path, const brix_http_serve_opts_t * opts, brix_http_serve_result_t * result)
Definition at line 427 of file file_serve.c.
References serve_ctx_t::backend_name, brix_dashboard_http_start_identity(), brix_http_parse_range(), brix_http_set_file_headers(), BRIX_SERVE_RANGE_FULL, BRIX_SERVE_RANGE_PARTIAL, brix_vfs_close(), brix_vfs_file_backend_name(), brix_vfs_file_fd(), brix_vfs_file_from_cache(), brix_vfs_file_path(), brix_vfs_file_sendfile_fd(), BRIX_XFER_DIR_READ, serve_ctx_t::cache_path, brix_http_range_t::end, brix_http_serve_opts_t::etag_flags, serve_ctx_t::fh, serve_ctx_t::from_cache, serve_ctx_t::fs_path, brix_http_serve_opts_t::identity, brix_vfs_stat_t::mtime, brix_http_serve_opts_t::op_name, serve_ctx_t::opts, brix_http_serve_opts_t::pre_header_send, brix_http_serve_opts_t::pre_header_ud, brix_http_range_t::present, serve_ctx_t::r, brix_http_serve_result_t::range_result, serve_ctx_t::range_start, serve_ctx_t::result, brix_http_range_t::satisfiable, serve_ctx_t::send_len, serve_apply_tcp_congestion(), SERVE_DONE, serve_range_unsatisfiable(), serve_send_memory_backed(), serve_send_sendfile(), serve_try_compressed(), brix_vfs_stat_t::size, brix_http_range_t::start, serve_ctx_t::vst, and brix_http_serve_opts_t::xfer_proto.
Referenced by cvmfs_tier_open_respond(), get_serve_full(), ngx_http_brix_dashboard_vfs_download_handler(), and s3_get_serve().
brix_serve_memory_backed()
static ngx_int_t brix_serve_memory_backed (ngx_http_request_t * r, brix_vfs_file_t * fh, off_t start, off_t len) static
Definition at line 111 of file file_serve.c.
References BRIX_SERVE_MEM_CHUNK, and brix_vfs_file_pread().
Referenced by serve_send_memory_backed().
serve_apply_tcp_congestion()
static void serve_apply_tcp_congestion (ngx_http_request_t * r) static
Definition at line 195 of file file_serve.c.
References brix_apply_tcp_congestion(), ngx_http_brix_webdav_module, and ngx_http_brix_webdav_loc_conf_t::tcp_congestion.
Referenced by brix_http_serve_file_ranged().
serve_range_unsatisfiable()
static ngx_int_t serve_range_unsatisfiable (ngx_http_request_t * r, brix_vfs_file_t * fh, brix_http_serve_result_t * result, off_t total) static
Definition at line 222 of file file_serve.c.
References brix_http_set_header(), BRIX_SERVE_RANGE_UNSATISFIED, brix_vfs_close(), and brix_http_serve_result_t::range_result.
Referenced by brix_http_serve_file_ranged().
serve_record_body_accounting()
static void serve_record_body_accounting (const serve_ctx_t * sc, off_t bytes, ngx_uint_t from_cache, const char * cache_path) static
Definition at line 252 of file file_serve.c.
References serve_ctx_t::backend_name, brix_cache_record_access(), brix_dashboard_http_add(), brix_metric_backend_bytes(), BRIX_METRIC_OP_READ, brix_http_serve_result_t::bytes_sent, serve_ctx_t::r, and serve_ctx_t::result.
Referenced by serve_send_memory_backed(), serve_send_sendfile(), and serve_try_compressed().
serve_send_memory_backed()
static ngx_int_t serve_send_memory_backed (const serve_ctx_t * sc) static
Definition at line 354 of file file_serve.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_serve_memory_backed(), brix_vfs_close(), serve_ctx_t::cache_path, serve_ctx_t::fh, serve_ctx_t::from_cache, serve_ctx_t::r, serve_ctx_t::range_start, serve_ctx_t::send_len, and serve_record_body_accounting().
Referenced by brix_http_serve_file_ranged().
serve_send_sendfile()
static ngx_int_t serve_send_sendfile (const serve_ctx_t * sc, ngx_fd_t fd) static
Definition at line 391 of file file_serve.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_http_send_file_range(), brix_vfs_close(), serve_ctx_t::cache_path, serve_ctx_t::fh, serve_ctx_t::from_cache, serve_ctx_t::fs_path, serve_ctx_t::r, serve_ctx_t::range_start, serve_ctx_t::send_len, and serve_record_body_accounting().
Referenced by brix_http_serve_file_ranged().
serve_try_compressed()
static serve_disposition_t serve_try_compressed (const serve_ctx_t * sc, ngx_uint_t range_present, ngx_int_t * rc) static
Definition at line 282 of file file_serve.c.
References BRIX_CODEC_IDENTITY, brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_dashboard_http_start_identity(), brix_http_compress_negotiate(), brix_http_send_file_compressed(), BRIX_SERVE_RANGE_FULL, brix_vfs_close(), brix_vfs_file_fd(), brix_vfs_file_from_cache(), brix_vfs_file_path(), BRIX_XFER_DIR_READ, brix_http_serve_opts_t::compress, brix_http_serve_opts_t::etag_flags, serve_ctx_t::fh, serve_ctx_t::fs_path, brix_http_serve_opts_t::identity, brix_vfs_stat_t::mtime, brix_http_serve_opts_t::op_name, serve_ctx_t::opts, serve_ctx_t::r, brix_http_serve_result_t::range_result, serve_ctx_t::result, SERVE_CONTINUE, SERVE_DONE, serve_record_body_accounting(), brix_vfs_stat_t::size, serve_ctx_t::vst, and brix_http_serve_opts_t::xfer_proto.
Referenced by brix_http_serve_file_ranged().