nginx-xrootd: src/auth/token/file.c File Reference
file.c File Reference
#include "file.h"
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
Data Structures
struct brix_token_diag_t
Functions
static const char * brix_token_label (const brix_token_diag_t *diag)
static ngx_int_t brix_token_validate_args (const ngx_str_t *path, const u_char *buf, size_t buf_sz, char *pathz, const brix_token_diag_t *diag)
static ngx_int_t brix_token_slurp (const char *pathz, u_char *buf, size_t buf_sz, size_t *n_out, const brix_token_diag_t *diag)
static size_t brix_token_trim (u_char *buf, size_t n)
ngx_int_t brix_token_read_file (const ngx_str_t *path, u_char *buf, size_t buf_sz, size_t *out_len, ngx_log_t *log, const char *label)
Function Documentation
brix_token_label()
static const char * brix_token_label (const brix_token_diag_t * diag) static
Definition at line 57 of file file.c.
References brix_token_diag_t::label.
Referenced by brix_token_read_file(), brix_token_slurp(), and brix_token_validate_args().
brix_token_read_file()
ngx_int_t brix_token_read_file (const ngx_str_t * path, u_char * buf, size_t buf_sz, size_t * out_len, ngx_log_t * log, const char * label)
Definition at line 164 of file file.c.
References brix_token_label(), brix_token_slurp(), brix_token_trim(), brix_token_validate_args(), brix_token_diag_t::label, log, and brix_token_diag_t::log.
Referenced by brix_upstream_send_token_auth(), proxy_bs_auth_token_file(), proxy_bs_login_sec_ztn(), tpc_read_bearer_token(), and tpc_rfc8693_read_subject().
brix_token_slurp()
static ngx_int_t brix_token_slurp (const char * pathz, u_char * buf, size_t buf_sz, size_t * n_out, const brix_token_diag_t * diag) static
Definition at line 108 of file file.c.
References brix_token_label(), and brix_token_diag_t::log.
Referenced by brix_token_read_file().
brix_token_trim()
static size_t brix_token_trim (u_char * buf, size_t n) static
Definition at line 154 of file file.c.
Referenced by brix_token_read_file().
brix_token_validate_args()
static ngx_int_t brix_token_validate_args (const ngx_str_t * path, const u_char * buf, size_t buf_sz, char * pathz, const brix_token_diag_t * diag) static
Definition at line 76 of file file.c.
References brix_token_label(), brix_token_diag_t::log, and ngx_memcpy.
Referenced by brix_token_read_file().