nginx-xrootd: src/observability/dashboard/files.c File Reference
files.c File Reference
#include "dashboard_http.h"
#include "dashboard_json.h"
#include "fs/path/beneath.h"
#include "core/http/http_file_response.h"
#include "core/http/http_headers.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <jansson.h>
#include <pwd.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Macros
#define DASHBOARD_FILES_MAX_ENTRIES 10000
Functions
static ngx_int_t dashboard_open_status (int e)
static void dashboard_owner_name (uid_t uid, char *out, size_t outsz)
static ngx_int_t dashboard_files_get_path (ngx_http_request_t *r, char *out, size_t outsz)
static json_t * dashboard_files_entry (const char *name, const struct statx *stx)
ngx_int_t ngx_http_brix_dashboard_files_handler (ngx_http_request_t *r)
static void dashboard_download_filename (const char *relpath, char *out, size_t outsz)
ngx_int_t ngx_http_brix_dashboard_download_handler (ngx_http_request_t *r)
Macro Definition Documentation
DASHBOARD_FILES_MAX_ENTRIES
#define DASHBOARD_FILES_MAX_ENTRIES 10000
Definition at line 37 of file files.c.
Function Documentation
dashboard_download_filename()
static void dashboard_download_filename (const char * relpath, char * out, size_t outsz) static
Definition at line 262 of file files.c.
References c.
Referenced by ngx_http_brix_dashboard_download_handler().
dashboard_files_entry()
static json_t * dashboard_files_entry (const char * name, const struct statx * stx) static
Definition at line 139 of file files.c.
References dashboard_owner_name(), and name.
Referenced by ngx_http_brix_dashboard_files_handler().
dashboard_files_get_path()
static ngx_int_t dashboard_files_get_path (ngx_http_request_t * r, char * out, size_t outsz) static
Definition at line 92 of file files.c.
Referenced by ngx_http_brix_dashboard_download_handler(), and ngx_http_brix_dashboard_files_handler().
dashboard_open_status()
static ngx_int_t dashboard_open_status (int e) static
Definition at line 42 of file files.c.
Referenced by ngx_http_brix_dashboard_download_handler(), and ngx_http_brix_dashboard_files_handler().
dashboard_owner_name()
static void dashboard_owner_name (uid_t uid, char * out, size_t outsz) static
Definition at line 57 of file files.c.
Referenced by dashboard_files_entry().
ngx_http_brix_dashboard_download_handler()
ngx_int_t ngx_http_brix_dashboard_download_handler (ngx_http_request_t * r)
Definition at line 280 of file files.c.
References brix_beneath_open_root(), brix_http_send_file_range(), brix_http_source_offer(), brix_open_beneath(), ngx_http_brix_dashboard_loc_conf_t::browse_root_canon, close(), dashboard_download_filename(), dashboard_files_get_path(), dashboard_open_status(), fstat(), ngx_http_brix_dashboard_check_auth(), ngx_http_brix_dashboard_module, PATH_MAX, and stat().
Referenced by ngx_http_brix_dashboard_main_handler().
ngx_http_brix_dashboard_files_handler()
ngx_int_t ngx_http_brix_dashboard_files_handler (ngx_http_request_t * r)
Definition at line 167 of file files.c.
References brix_beneath_open_root(), brix_http_source_offer(), brix_open_beneath(), ngx_http_brix_dashboard_loc_conf_t::browse_root_canon, close(), dashboard_files_entry(), dashboard_files_get_path(), DASHBOARD_FILES_MAX_ENTRIES, dashboard_json_send(), dashboard_json_set_schema(), dashboard_open_status(), ngx_http_brix_dashboard_check_auth(), ngx_http_brix_dashboard_module, PATH_MAX, and statx().
Referenced by ngx_http_brix_dashboard_main_handler().