nginx-xrootd: src/auth/authz/find_rule.c File Reference
find_rule.c File Reference
#include "core/ngx_brix_module.h"
#include <stddef.h>
#include <string.h>
Functions
static ngx_flag_t brix_path_prefix_match (const char *prefix, size_t prefix_len, const char *path)
static const void * brix_find_longest_rule (const char *resolved_path, const ngx_array_t *rules, size_t elt_size, size_t resolved_off)
const brix_vo_rule_t * brix_find_vo_rule (const char *resolved_path, ngx_array_t *rules)
const brix_group_rule_t * brix_find_group_rule (const char *resolved_path, ngx_array_t *rules)
const brix_manager_map_t * brix_find_manager_map (const char *reqpath, ngx_array_t *map)
Function Documentation
brix_find_group_rule()
const brix_group_rule_t * brix_find_group_rule (const char * resolved_path, ngx_array_t * rules)
Definition at line 118 of file find_rule.c.
References brix_find_longest_rule().
Referenced by brix_apply_parent_group_policy_impl().
brix_find_longest_rule()
static const void * brix_find_longest_rule (const char * resolved_path, const ngx_array_t * rules, size_t elt_size, size_t resolved_off) static
Definition at line 68 of file find_rule.c.
References brix_path_prefix_match().
Referenced by brix_find_group_rule(), and brix_find_vo_rule().
brix_find_manager_map()
const brix_manager_map_t * brix_find_manager_map (const char * reqpath, ngx_array_t * map)
Definition at line 130 of file find_rule.c.
References brix_path_prefix_match(), and brix_manager_map_t::prefix.
Referenced by brix_dirlist_check_redirect(), brix_open_manager_redirect(), locate_try_manager_map(), and stat_manager_route().
brix_find_vo_rule()
const brix_vo_rule_t * brix_find_vo_rule (const char * resolved_path, ngx_array_t * rules)
Definition at line 105 of file find_rule.c.
References brix_find_longest_rule().
Referenced by brix_check_vo_acl().
brix_path_prefix_match()
static ngx_flag_t brix_path_prefix_match (const char * prefix, size_t prefix_len, const char * path) static
Definition at line 24 of file find_rule.c.
Referenced by brix_find_longest_rule(), and brix_find_manager_map().