nginx-xrootd: src/observability/pmark/firefly.c File Reference
firefly.c File Reference
#include "pmark.h"
#include "observability/metrics/metrics.h"
#include "observability/metrics/metrics_macros.h"
#include <sys/socket.h>
#include <netinet/in.h>
#include <stdio.h>
#include <string.h>
#include "core/compat/alloc_guard.h"
Functions
static ngx_socket_t pmark_worker_socket (int family)
static size_t pmark_build (brix_pmark_flow_t *f, const char *state, int with_end, u_char *buf, size_t buflen)
static void pmark_emit (brix_pmark_flow_t *f, const char *state, int with_end, ngx_log_t *log)
brix_pmark_flow_t * brix_pmark_flow_begin (brix_pmark_conf_t *pm, ngx_pool_t *pool, ngx_connection_t *c, int is_write, const char *vo_csv, const char *user, const char *path, const char *cgi, ngx_log_t *log)
void brix_pmark_flow_end (brix_pmark_flow_t *flow, ngx_log_t *log)
void brix_pmark_flow_echo (brix_pmark_flow_t *flow, ngx_log_t *log)
void brix_pmark_flow_cleanup (void *data)
void brix_pmark_firefly_oneshot (brix_pmark_conf_t *pm, int fd, ngx_uint_t exp, ngx_uint_t act, int peer_is_src, const char *app, ngx_log_t *log)
void brix_pmark_http_mark (brix_pmark_conf_t *pm, ngx_pool_t *pool, ngx_connection_t *c, int is_write, const char *vo_csv, const char *user, const char *path, const char *cgi)
Variables
static ngx_socket_t pmark_fd4 = (ngx_socket_t) -1
static ngx_socket_t pmark_fd6 = (ngx_socket_t) -1
Function Documentation
brix_pmark_firefly_oneshot()
void brix_pmark_firefly_oneshot (brix_pmark_conf_t * pm, int fd, ngx_uint_t exp, ngx_uint_t act, int peer_is_src, const char * app, ngx_log_t * log)
Definition at line 283 of file firefly.c.
References brix_pmark_flow_t::act, brix_pmark_flow_t::afi, brix_pmark_flow_t::app, brix_pmark_endpoint(), brix_pmark_iso8601_now(), BRIX_PMARK_METRIC_INC, brix_pmark_flow_t::dst_ip, brix_pmark_flow_t::dst_port, brix_pmark_flow_t::exp, brix_pmark_flow_t::fd, brix_pmark_conf_t::firefly, brix_pmark_flow_t::firefly_started, brix_pmark_flow_t::is_put, log, ngx_memcpy, brix_pmark_flow_t::pm, pmark_emit(), brix_pmark_flow_t::src_ip, brix_pmark_flow_t::src_port, and brix_pmark_flow_t::start_iso.
Referenced by webdav_tpc_pmark_closesocket().
brix_pmark_flow_begin()
brix_pmark_flow_t * brix_pmark_flow_begin (brix_pmark_conf_t * pm, ngx_pool_t * pool, ngx_connection_t * c, int is_write, const char * vo_csv, const char * user, const char * path, const char * cgi, ngx_log_t * log)
Definition at line 168 of file firefly.c.
References brix_pmark_flow_t::act, brix_pmark_flow_t::afi, brix_pmark_flow_t::app, brix_pmark_conf_t::appname, BRIX_PCALLOC_OR_RETURN, brix_pmark_endpoint(), brix_pmark_flowlabel_apply(), brix_pmark_iso8601_now(), brix_pmark_map_codes(), BRIX_PMARK_METRIC_INC, brix_pmark_runtime_ensure(), c, brix_pmark_flow_t::dst_ip, brix_pmark_flow_t::dst_port, brix_pmark_conf_t::enable, brix_pmark_flow_t::exp, brix_pmark_flow_t::fd, brix_pmark_conf_t::firefly, brix_pmark_conf_t::firefly_origin, brix_pmark_flow_t::firefly_started, brix_pmark_conf_t::flowlabel, brix_pmark_flow_t::is_put, log, ngx_memcpy, brix_pmark_flow_t::peer_len, brix_pmark_flow_t::peer_ss, brix_pmark_flow_t::pm, pmark_emit(), brix_pmark_flow_t::src_ip, brix_pmark_flow_t::src_port, brix_pmark_flow_t::start_iso, brix_pmark_flow_id_t::vo_csv, and brix_pmark_flow_t::want_origin.
Referenced by brix_open_begin_pmark(), and brix_pmark_http_mark().
brix_pmark_flow_cleanup()
void brix_pmark_flow_cleanup (void * data)
Definition at line 276 of file firefly.c.
References brix_pmark_flow_end().
Referenced by brix_pmark_http_mark().
brix_pmark_flow_echo()
void brix_pmark_flow_echo (brix_pmark_flow_t * flow, ngx_log_t * log)
Definition at line 264 of file firefly.c.
References brix_pmark_conf_t::firefly, brix_pmark_flow_t::firefly_started, log, brix_pmark_flow_t::pm, and pmark_emit().
Referenced by brix_pmark_echo_timer().
brix_pmark_flow_end()
void brix_pmark_flow_end (brix_pmark_flow_t * flow, ngx_log_t * log)
Definition at line 251 of file firefly.c.
References BRIX_PMARK_METRIC_INC, brix_pmark_conf_t::firefly, brix_pmark_flow_t::firefly_started, log, brix_pmark_flow_t::pm, and pmark_emit().
Referenced by brix_disconnect_end_pmark(), and brix_pmark_flow_cleanup().
brix_pmark_http_mark()
void brix_pmark_http_mark (brix_pmark_conf_t * pm, ngx_pool_t * pool, ngx_connection_t * c, int is_write, const char * vo_csv, const char * user, const char * path, const char * cgi)
Definition at line 334 of file firefly.c.
References brix_pmark_flow_begin(), brix_pmark_flow_cleanup(), and c.
Referenced by s3_pmark_begin_if_enabled(), and webdav_dispatch_pmark().
pmark_build()
static size_t pmark_build (brix_pmark_flow_t * f, const char * state, int with_end, u_char * buf, size_t buflen) static
Definition at line 62 of file firefly.c.
References brix_pmark_flow_t::act, brix_pmark_flow_t::afi, brix_pmark_flow_t::app, brix_pmark_iso8601_now(), brix_pmark_sockstats(), brix_pmark_sockstats_t::bytes_recv, brix_pmark_sockstats_t::bytes_sent, brix_pmark_flow_t::dst_ip, brix_pmark_flow_t::dst_port, brix_pmark_flow_t::exp, brix_pmark_flow_t::fd, host, brix_pmark_flow_t::is_put, brix_pmark_sockstats_t::rtt_us, brix_pmark_flow_t::src_ip, brix_pmark_flow_t::src_port, and brix_pmark_flow_t::start_iso.
Referenced by pmark_emit().
pmark_emit()
static void pmark_emit (brix_pmark_flow_t * f, const char * state, int with_end, ngx_log_t * log) static
Definition at line 115 of file firefly.c.
References BRIX_PMARK_FF_PORT, BRIX_PMARK_METRIC_INC, brix_pmark_conf_t::dest_sa, log, ngx_memcpy, brix_pmark_flow_t::peer_len, brix_pmark_flow_t::peer_ss, brix_pmark_flow_t::pm, pmark_build(), pmark_worker_socket(), and brix_pmark_flow_t::want_origin.
Referenced by brix_pmark_firefly_oneshot(), brix_pmark_flow_begin(), brix_pmark_flow_echo(), and brix_pmark_flow_end().
pmark_worker_socket()
static ngx_socket_t pmark_worker_socket (int family) static
Definition at line 39 of file firefly.c.
References pmark_fd4, and pmark_fd6.
Referenced by pmark_emit().
Variable Documentation
pmark_fd4
ngx_socket_t pmark_fd4 = (ngx_socket_t) -1 static
Definition at line 34 of file firefly.c.
Referenced by pmark_worker_socket().
pmark_fd6
ngx_socket_t pmark_fd6 = (ngx_socket_t) -1 static
Definition at line 35 of file firefly.c.
Referenced by pmark_worker_socket().