nginx-xrootd: src/observability/pmark/flowlabel.c File Reference
flowlabel.c File Reference
#include "pmark.h"
#include "observability/metrics/metrics.h"
#include "observability/metrics/metrics_macros.h"
#include "core/compat/log_diag.h"
Functions
ngx_int_t brix_pmark_flowlabel_usable (ngx_log_t *log)
ngx_int_t brix_pmark_flowlabel_apply (ngx_connection_t *c, int fd, ngx_uint_t exp, ngx_uint_t act, ngx_log_t *log)
ngx_int_t brix_pmark_flowlabel_apply_addr (int fd, const struct sockaddr *dst, socklen_t dstlen, ngx_uint_t exp, ngx_uint_t act, ngx_log_t *log)
Function Documentation
brix_pmark_flowlabel_apply()
ngx_int_t brix_pmark_flowlabel_apply (ngx_connection_t * c, int fd, ngx_uint_t exp, ngx_uint_t act, ngx_log_t * log)
Definition at line 208 of file flowlabel.c.
References c, and log.
Referenced by brix_pmark_flow_begin().
brix_pmark_flowlabel_apply_addr()
ngx_int_t brix_pmark_flowlabel_apply_addr (int fd, const struct sockaddr * dst, socklen_t dstlen, ngx_uint_t exp, ngx_uint_t act, ngx_log_t * log)
Definition at line 216 of file flowlabel.c.
References log.
Referenced by tpc_connect(), and webdav_tpc_pmark_opensocket().
brix_pmark_flowlabel_usable()
ngx_int_t brix_pmark_flowlabel_usable (ngx_log_t * log)
Definition at line 201 of file flowlabel.c.
References log.