nginx-xrootd: src/net/proxy/forward_session_helpers.c File Reference
forward_session_helpers.c File Reference
#include "proxy_internal.h"
#include "protocols/root/session/registry.h"
Functions
void proxy_write_audit (brix_proxy_ctx_t *proxy, int local_fh)
void brix_proxy_wait_handler (ngx_event_t *ev)
int brix_proxy_alloc_local_fh (brix_proxy_ctx_t *proxy)
ngx_int_t brix_proxy_lazy_open (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, int local_fh, u_char *read_req, size_t read_req_len)
Function Documentation
brix_proxy_alloc_local_fh()
int brix_proxy_alloc_local_fh (brix_proxy_ctx_t * proxy)
Definition at line 135 of file forward_session_helpers.c.
References BRIX_MAX_FILES, and BRIX_PROXY_FH_FREE.
Referenced by brix_proxy_dispatch(), and brix_proxy_forward_open().
brix_proxy_lazy_open()
ngx_int_t brix_proxy_lazy_open (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, int local_fh, u_char * read_req, size_t read_req_len)
Definition at line 164 of file forward_session_helpers.c.
References brix_ctx_t::bound_sessid, brix_proxy_abort(), brix_proxy_flush(), brix_send_error(), brix_session_handle_lookup(), c, ClientOpenRequest::dlen, kXR_InvalidRequest, kXR_IOError, kXR_open, kXR_open_read, ngx_memcpy, xrdw_open_req_t::options, brix_shared_handle_entry_t::path, ClientOpenRequest::requestid, brix_ctx_t::state, ClientOpenRequest::streamid, XRD_PX_FORWARDING, XRD_ST_PROXY, and xrdw_open_req_pack().
Referenced by brix_proxy_dispatch_pending(), brix_proxy_lazy_open_next(), check_bound_secondary_lazy_open(), and initiate_readv_lazy_open_queue().
brix_proxy_wait_handler()
void brix_proxy_wait_handler (ngx_event_t * ev)
Definition at line 70 of file forward_session_helpers.c.
References brix_proxy_abort(), brix_proxy_cleanup(), brix_proxy_flush(), brix_ctx_t::destroyed, XRD_PX_FORWARDING, and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_relay_absorb_wait().
proxy_write_audit()
void proxy_write_audit (brix_proxy_ctx_t * proxy, int local_fh)
Definition at line 34 of file forward_session_helpers.c.
References BRIX_MAX_FILES, brix_proxy_fh_entry_t::bytes_read, brix_proxy_fh_entry_t::bytes_written, brix_proxy_fh_entry_t::open_msec, and brix_proxy_fh_entry_t::path.
Referenced by brix_proxy_cleanup_audit_handles(), and brix_proxy_relay_close_status().