nginx-xrootd: src/net/proxy/forward_fh_translate.c File Reference
forward_fh_translate.c File Reference
#include "proxy_internal.h"
#include "protocols/root/session/registry.h"
Functions
static ngx_int_t check_bound_secondary_lazy_open (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, u_char *req, size_t total, uint16_t reqid, int local_fh)
static ngx_int_t translate_ckpxeq_writev_fhandles (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, u_char *req, u_char *sub, size_t body_len)
static ngx_int_t translate_ckpxeq_sub_request (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, u_char *req, size_t body_len)
ngx_int_t brix_proxy_fh_translate_single (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, u_char *req, size_t total, uint16_t reqid, size_t body_len)
static int collect_unopened_readv_handles (brix_proxy_ctx_t *proxy, u_char *payload, uint32_t cur_dlen, int pending[16])
static ngx_int_t initiate_readv_lazy_open_queue (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, u_char *req, size_t total, u_char *payload, uint32_t cur_dlen)
ngx_int_t brix_proxy_fh_translate_vector (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, u_char *req, size_t total, uint16_t reqid, uint32_t cur_dlen)
Function Documentation
brix_proxy_fh_translate_single()
ngx_int_t brix_proxy_fh_translate_single (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, u_char * req, size_t total, uint16_t reqid, size_t body_len)
Definition at line 155 of file forward_fh_translate.c.
References c, check_bound_secondary_lazy_open(), kXR_chkpoint, kXR_ckpXeq, kXR_InvalidRequest, proxy_reject_request(), proxy_translate_fh(), and translate_ckpxeq_sub_request().
Referenced by brix_proxy_translate_fh_op().
brix_proxy_fh_translate_vector()
ngx_int_t brix_proxy_fh_translate_vector (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, u_char * req, size_t total, uint16_t reqid, uint32_t cur_dlen)
Definition at line 284 of file forward_fh_translate.c.
References c, initiate_readv_lazy_open_queue(), brix_ctx_t::is_bound, kXR_InvalidRequest, kXR_readv, proxy_reject_request(), proxy_translate_fh(), and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_translate_fh_op().
check_bound_secondary_lazy_open()
static ngx_int_t check_bound_secondary_lazy_open (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, u_char * req, size_t total, uint16_t reqid, int local_fh) static
Definition at line 41 of file forward_fh_translate.c.
References BRIX_MAX_FILES, BRIX_PROXY_FH_FREE, brix_proxy_lazy_open(), c, brix_ctx_t::is_bound, kXR_pgread, and kXR_read.
Referenced by brix_proxy_fh_translate_single().
collect_unopened_readv_handles()
static int collect_unopened_readv_handles (brix_proxy_ctx_t * proxy, u_char * payload, uint32_t cur_dlen, int pending[16]) static
Definition at line 202 of file forward_fh_translate.c.
References BRIX_MAX_FILES, and BRIX_PROXY_FH_FREE.
Referenced by initiate_readv_lazy_open_queue().
initiate_readv_lazy_open_queue()
static ngx_int_t initiate_readv_lazy_open_queue (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, u_char * req, size_t total, u_char * payload, uint32_t cur_dlen) static
Definition at line 243 of file forward_fh_translate.c.
References BRIX_MAX_FILES, brix_proxy_lazy_open(), c, and collect_unopened_readv_handles().
Referenced by brix_proxy_fh_translate_vector().
translate_ckpxeq_sub_request()
static ngx_int_t translate_ckpxeq_sub_request (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, u_char * req, size_t body_len) static
Definition at line 117 of file forward_fh_translate.c.
References c, kXR_InvalidRequest, kXR_writev, proxy_reject_request(), proxy_translate_fh(), translate_ckpxeq_writev_fhandles(), and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_fh_translate_single().
translate_ckpxeq_writev_fhandles()
static ngx_int_t translate_ckpxeq_writev_fhandles (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, u_char * req, u_char * sub, size_t body_len) static
Definition at line 78 of file forward_fh_translate.c.
References c, kXR_InvalidRequest, proxy_reject_request(), and proxy_translate_fh().
Referenced by translate_ckpxeq_sub_request().