nginx-xrootd: src/net/proxy/forward_rewrite_helpers.c File Reference
forward_rewrite_helpers.c File Reference
#include "proxy_internal.h"
#include "protocols/root/session/registry.h"
Data Structures
struct proxy_prepare_rewrite_t
Functions
u_char * proxy_rewrite_path (ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, u_char *req, size_t total, size_t path_off, size_t path_len, size_t *total_out)
static size_t proxy_prepare_line_len (const u_char *line_start, const u_char *p, const u_char *last)
static ngx_uint_t proxy_prepare_line_matches (const proxy_prepare_rewrite_t *rw, const u_char *line_start, size_t line_len)
static size_t proxy_prepare_measure (const proxy_prepare_rewrite_t *rw, ngx_uint_t *needs_rewrite)
static void proxy_prepare_emit (const proxy_prepare_rewrite_t *rw, u_char *dst)
u_char * proxy_rewrite_prepare_payload (ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, u_char *req, size_t total, size_t *total_out)
ngx_int_t proxy_reject_request (brix_ctx_t *ctx, ngx_connection_t *c, u_char *req, uint16_t errcode, const char *msg)
int proxy_translate_fh (brix_proxy_ctx_t *proxy, u_char *buf, size_t offset)
Function Documentation
proxy_prepare_emit()
static void proxy_prepare_emit (const proxy_prepare_rewrite_t * rw, u_char * dst) static
Definition at line 178 of file forward_rewrite_helpers.c.
References proxy_prepare_rewrite_t::add, proxy_prepare_rewrite_t::alen, ngx_memcpy, proxy_prepare_rewrite_t::payload, proxy_prepare_rewrite_t::plen, proxy_prepare_line_len(), proxy_prepare_line_matches(), and proxy_prepare_rewrite_t::slen.
Referenced by proxy_rewrite_prepare_payload().
proxy_prepare_line_len()
static size_t proxy_prepare_line_len (const u_char * line_start, const u_char * p, const u_char * last) static
Definition at line 105 of file forward_rewrite_helpers.c.
Referenced by proxy_prepare_emit(), and proxy_prepare_measure().
proxy_prepare_line_matches()
static ngx_uint_t proxy_prepare_line_matches (const proxy_prepare_rewrite_t * rw, const u_char * line_start, size_t line_len) static
Definition at line 121 of file forward_rewrite_helpers.c.
References proxy_prepare_rewrite_t::slen, and proxy_prepare_rewrite_t::strip.
Referenced by proxy_prepare_emit(), and proxy_prepare_measure().
proxy_prepare_measure()
static size_t proxy_prepare_measure (const proxy_prepare_rewrite_t * rw, ngx_uint_t * needs_rewrite) static
Definition at line 138 of file forward_rewrite_helpers.c.
References proxy_prepare_rewrite_t::alen, proxy_prepare_rewrite_t::payload, proxy_prepare_rewrite_t::plen, proxy_prepare_line_len(), proxy_prepare_line_matches(), proxy_prepare_rewrite_t::slen, and XRD_REQUEST_HDR_LEN.
Referenced by proxy_rewrite_prepare_payload().
proxy_reject_request()
ngx_int_t proxy_reject_request (brix_ctx_t * ctx, ngx_connection_t * c, u_char * req, uint16_t errcode, const char * msg)
Definition at line 274 of file forward_rewrite_helpers.c.
References brix_send_error(), and c.
Referenced by brix_proxy_fh_translate_single(), brix_proxy_fh_translate_vector(), brix_proxy_forward_clone(), brix_proxy_forward_open(), brix_proxy_forward_stat(), translate_ckpxeq_sub_request(), and translate_ckpxeq_writev_fhandles().
proxy_rewrite_path()
u_char * proxy_rewrite_path (ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, u_char * req, size_t total, size_t path_off, size_t path_len, size_t * total_out)
Definition at line 22 of file forward_rewrite_helpers.c.
References c, ngx_memcpy, and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_forward_open(), and brix_proxy_forward_pathop().
proxy_rewrite_prepare_payload()
u_char * proxy_rewrite_prepare_payload (ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, u_char * req, size_t total, size_t * total_out)
Definition at line 211 of file forward_rewrite_helpers.c.
References proxy_prepare_rewrite_t::add, proxy_prepare_rewrite_t::alen, c, ngx_memcpy, proxy_prepare_rewrite_t::payload, proxy_prepare_rewrite_t::plen, proxy_prepare_emit(), proxy_prepare_measure(), proxy_prepare_rewrite_t::slen, proxy_prepare_rewrite_t::strip, and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_forward_prepare().
proxy_translate_fh()
int proxy_translate_fh (brix_proxy_ctx_t * proxy, u_char * buf, size_t offset)
Definition at line 289 of file forward_rewrite_helpers.c.
References BRIX_MAX_FILES, and BRIX_PROXY_FH_FREE.
Referenced by brix_proxy_fh_translate_single(), brix_proxy_fh_translate_vector(), brix_proxy_forward_clone(), brix_proxy_forward_stat(), translate_ckpxeq_sub_request(), and translate_ckpxeq_writev_fhandles().