nginx-xrootd: src/net/proxy/forward_relay_response_lazy.c File Reference
forward_relay_response_lazy.c File Reference
#include "proxy_internal.h"
#include "protocols/root/session/registry.h"
#include "protocols/root/protocol/frame_hdr.h"
#include "core/compat/cstr.h"
#include "forward_relay_response_internal.h"
Functions
static void brix_proxy_lazy_release_body (brix_proxy_ctx_t *proxy)
static void brix_proxy_lazy_open_failed (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, int local_fh)
static void brix_proxy_lazy_record_open (brix_proxy_ctx_t *proxy, int local_fh)
static int brix_proxy_lazy_open_next (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c)
static int brix_proxy_translate_saved_readv (brix_proxy_ctx_t *proxy, u_char *rreq, size_t rlen)
static int brix_proxy_translate_saved_read (brix_proxy_ctx_t *proxy, u_char *rreq, size_t rlen, int local_fh)
static void brix_proxy_prepare_saved_forward (brix_proxy_ctx_t *proxy, u_char *rreq, size_t rlen, int local_fh)
static void brix_proxy_save_wait_retry (brix_proxy_ctx_t *proxy, ngx_connection_t *c, u_char *rreq, size_t rlen)
static int brix_proxy_dispatch_saved_read (brix_proxy_ctx_t *proxy, ngx_connection_t *c)
int brix_proxy_relay_lazy_open (brix_proxy_ctx_t *proxy)
Function Documentation
brix_proxy_dispatch_saved_read()
static int brix_proxy_dispatch_saved_read (brix_proxy_ctx_t * proxy, ngx_connection_t * c) static
Definition at line 173 of file forward_relay_response_lazy.c.
References brix_proxy_abort(), brix_proxy_flush(), brix_proxy_prepare_saved_forward(), brix_proxy_save_wait_retry(), brix_proxy_translate_saved_read(), c, and XRD_PX_FORWARDING.
Referenced by brix_proxy_relay_lazy_open().
brix_proxy_lazy_open_failed()
static void brix_proxy_lazy_open_failed (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, int local_fh) static
Definition at line 35 of file forward_relay_response_lazy.c.
References BRIX_MAX_FILES, BRIX_PROXY_FH_FREE, brix_proxy_lazy_release_body(), brix_schedule_read_resume(), brix_send_error(), c, kXR_IOError, brix_ctx_t::state, XRD_PX_IDLE, and XRD_ST_REQ_HEADER.
Referenced by brix_proxy_relay_lazy_open().
brix_proxy_lazy_open_next()
static int brix_proxy_lazy_open_next (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c) static
Definition at line 69 of file forward_relay_response_lazy.c.
References brix_proxy_lazy_open(), and c.
Referenced by brix_proxy_relay_lazy_open().
brix_proxy_lazy_record_open()
static void brix_proxy_lazy_record_open (brix_proxy_ctx_t * proxy, int local_fh) static
Definition at line 56 of file forward_relay_response_lazy.c.
References BRIX_MAX_FILES.
Referenced by brix_proxy_relay_lazy_open().
brix_proxy_lazy_release_body()
static void brix_proxy_lazy_release_body (brix_proxy_ctx_t * proxy) static
Definition at line 26 of file forward_relay_response_lazy.c.
Referenced by brix_proxy_lazy_open_failed(), and brix_proxy_relay_lazy_open().
brix_proxy_prepare_saved_forward()
static void brix_proxy_prepare_saved_forward (brix_proxy_ctx_t * proxy, u_char * rreq, size_t rlen, int local_fh) static
Definition at line 135 of file forward_relay_response_lazy.c.
References ClientRequestHdr::requestid, ClientRequestHdr::streamid, and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_dispatch_saved_read().
brix_proxy_relay_lazy_open()
int brix_proxy_relay_lazy_open (brix_proxy_ctx_t * proxy)
Definition at line 216 of file forward_relay_response_lazy.c.
References brix_proxy_dispatch_saved_read(), brix_proxy_lazy_open_failed(), brix_proxy_lazy_open_next(), brix_proxy_lazy_record_open(), brix_proxy_lazy_release_body(), brix_schedule_read_resume(), c, kXR_ok, brix_ctx_t::state, XRD_PX_IDLE, and XRD_ST_REQ_HEADER.
Referenced by brix_proxy_relay_to_client().
brix_proxy_save_wait_retry()
static void brix_proxy_save_wait_retry (brix_proxy_ctx_t * proxy, ngx_connection_t * c, u_char * rreq, size_t rlen) static
Definition at line 151 of file forward_relay_response_lazy.c.
References c, and ngx_memcpy.
Referenced by brix_proxy_dispatch_saved_read().
brix_proxy_translate_saved_read()
static int brix_proxy_translate_saved_read (brix_proxy_ctx_t * proxy, u_char * rreq, size_t rlen, int local_fh) static
Definition at line 113 of file forward_relay_response_lazy.c.
References BRIX_MAX_FILES, brix_proxy_translate_saved_readv(), kXR_pgread, kXR_read, and kXR_readv.
Referenced by brix_proxy_dispatch_saved_read().
brix_proxy_translate_saved_readv()
static int brix_proxy_translate_saved_readv (brix_proxy_ctx_t * proxy, u_char * rreq, size_t rlen) static
Definition at line 93 of file forward_relay_response_lazy.c.
References BRIX_MAX_FILES, and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_translate_saved_read().