nginx-xrootd: src/net/proxy/forward_request.c File Reference
forward_request.c File Reference
#include "proxy_internal.h"
#include "protocols/root/session/registry.h"
Functions
static ngx_int_t brix_proxy_forward_open (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, u_char **req, size_t *total)
static void brix_proxy_pathop_audit (brix_proxy_ctx_t *proxy, uint16_t reqid, u_char *req, size_t total)
static void brix_proxy_forward_pathop (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, uint16_t reqid, u_char **req, size_t *total)
static void brix_proxy_save_wait_retry (brix_proxy_ctx_t *proxy, ngx_connection_t *c, u_char *req, size_t total)
static ngx_int_t brix_proxy_queue_and_flush (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, u_char *req, size_t total)
static ngx_int_t brix_proxy_forward_stat (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, uint16_t reqid, u_char *req, size_t total)
static ngx_int_t brix_proxy_forward_clone (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, u_char *req)
static void brix_proxy_forward_prepare (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, u_char **req, size_t *total)
static ngx_int_t brix_proxy_translate_fh_op (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, uint16_t reqid, u_char **req, size_t *total)
static ngx_int_t brix_proxy_translate_dispatch (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, uint16_t reqid, u_char **req, size_t *total)
ngx_int_t brix_proxy_forward_request (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c)
Function Documentation
brix_proxy_forward_clone()
static ngx_int_t brix_proxy_forward_clone (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, u_char * req) static
Definition at line 298 of file forward_request.c.
References c, kXR_InvalidRequest, proxy_reject_request(), and proxy_translate_fh().
Referenced by brix_proxy_translate_fh_op().
brix_proxy_forward_open()
static ngx_int_t brix_proxy_forward_open (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, u_char ** req, size_t * total) static
Definition at line 44 of file forward_request.c.
References brix_proxy_alloc_local_fh(), BRIX_PROXY_PATH_MAX, c, brix_ctx_recv_t::cur_dlen, kXR_IOError, ngx_memcpy, proxy_reject_request(), proxy_rewrite_path(), brix_ctx_t::recv, and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_translate_fh_op().
brix_proxy_forward_pathop()
static void brix_proxy_forward_pathop (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, uint16_t reqid, u_char ** req, size_t * total) static
Definition at line 147 of file forward_request.c.
References brix_proxy_pathop_audit(), c, brix_ctx_recv_t::cur_dlen, proxy_rewrite_path(), brix_ctx_t::recv, and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_translate_dispatch().
brix_proxy_forward_prepare()
static void brix_proxy_forward_prepare (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, u_char ** req, size_t * total) static
Definition at line 319 of file forward_request.c.
References c, brix_ctx_recv_t::cur_dlen, proxy_rewrite_prepare_payload(), and brix_ctx_t::recv.
Referenced by brix_proxy_translate_dispatch().
brix_proxy_forward_request()
ngx_int_t brix_proxy_forward_request (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 417 of file forward_request.c.
References brix_proxy_queue_and_flush(), brix_proxy_save_wait_retry(), brix_proxy_translate_dispatch(), brix_send_error(), BRIX_TAP_C2U, brix_tap_decode_request(), brix_tap_emit(), c, brix_ctx_recv_t::cur_body_extra, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, brix_ctx_recv_t::cur_streamid, brix_ctx_recv_t::hdr_buf, kXR_IOError, ngx_memcpy, brix_ctx_recv_t::payload, brix_ctx_t::recv, and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_dispatch().
brix_proxy_forward_stat()
static ngx_int_t brix_proxy_forward_stat (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, uint16_t reqid, u_char * req, size_t total) static
Definition at line 264 of file forward_request.c.
References BRIX_PROXY_PATH_MAX, c, brix_ctx_recv_t::cur_dlen, kXR_InvalidRequest, kXR_truncate, ngx_memcpy, proxy_reject_request(), proxy_translate_fh(), brix_ctx_t::recv, and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_translate_fh_op().
brix_proxy_pathop_audit()
static void brix_proxy_pathop_audit (brix_proxy_ctx_t * proxy, uint16_t reqid, u_char * req, size_t total) static
Definition at line 90 of file forward_request.c.
References BRIX_PROXY_PATH_MAX, kXR_chmod, kXR_mkdir, kXR_mv, kXR_rm, kXR_rmdir, ngx_memcpy, and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_forward_pathop().
brix_proxy_queue_and_flush()
static ngx_int_t brix_proxy_queue_and_flush (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, u_char * req, size_t total) static
Definition at line 209 of file forward_request.c.
References brix_proxy_abort(), brix_proxy_flush(), brix_proxy_wbuf_release(), brix_ctx_t::state, XRD_PX_FORWARDING, and XRD_ST_PROXY.
Referenced by brix_proxy_forward_request().
brix_proxy_save_wait_retry()
static void brix_proxy_save_wait_retry (brix_proxy_ctx_t * proxy, ngx_connection_t * c, u_char * req, size_t total) static
Definition at line 179 of file forward_request.c.
References c, and ngx_memcpy.
Referenced by brix_proxy_forward_request().
brix_proxy_translate_dispatch()
static ngx_int_t brix_proxy_translate_dispatch (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, uint16_t reqid, u_char ** req, size_t * total) static
Definition at line 393 of file forward_request.c.
References brix_proxy_forward_pathop(), brix_proxy_forward_prepare(), brix_proxy_translate_fh_op(), c, and kXR_prepare.
Referenced by brix_proxy_forward_request().
brix_proxy_translate_fh_op()
static ngx_int_t brix_proxy_translate_fh_op (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, uint16_t reqid, u_char ** req, size_t * total) static
Definition at line 340 of file forward_request.c.
References brix_proxy_fh_translate_single(), brix_proxy_fh_translate_vector(), brix_proxy_forward_clone(), brix_proxy_forward_open(), brix_proxy_forward_stat(), c, brix_ctx_recv_t::cur_body_extra, brix_ctx_recv_t::cur_dlen, kXR_chkpoint, kXR_clone, kXR_close, kXR_fattr, kXR_open, kXR_pgread, kXR_pgwrite, kXR_read, kXR_readv, kXR_stat, kXR_sync, kXR_truncate, kXR_write, kXR_writev, and brix_ctx_t::recv.
Referenced by brix_proxy_translate_dispatch().