nginx-xrootd: src/net/proxy/forward_relay_dispatch.c File Reference
forward_relay_dispatch.c File Reference
#include "proxy_internal.h"
#include "protocols/root/session/registry.h"
Functions
void brix_proxy_tap_audit_sink (void *ctx, const brix_tap_frame_t *f, brix_tap_dir_t dir, const u_char *payload, size_t payload_len)
void brix_proxy_tap_init (brix_proxy_ctx_t *proxy, ngx_connection_t *c)
static int brix_proxy_pending_lazy_fh (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, const u_char *req, size_t len, uint16_t reqid)
static ngx_int_t brix_proxy_pending_flush (brix_proxy_ctx_t *proxy, u_char *req, size_t len)
ngx_int_t brix_proxy_dispatch_pending (brix_proxy_ctx_t *proxy)
ngx_int_t brix_proxy_dispatch (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_proxy_dispatch()
ngx_int_t brix_proxy_dispatch (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 199 of file forward_relay_dispatch.c.
References BRIX_MAX_FILES, brix_proxy_alloc_local_fh(), brix_proxy_connect(), BRIX_PROXY_FH_FREE, brix_proxy_forward_request(), BRIX_PROXY_MAX_CONN_FAILS, brix_proxy_tap_init(), brix_send_error(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, brix_ctx_recv_t::hdr_buf, kXR_IOError, kXR_open, ngx_memcpy, ngx_pcalloc(), brix_ctx_recv_t::payload, brix_ctx_t::proxy, brix_ctx_t::proxy_fail_count, brix_ctx_t::recv, brix_ctx_t::state, XRD_PX_IDLE, XRD_REQUEST_HDR_LEN, and XRD_ST_PROXY.
Referenced by brix_dispatch().
brix_proxy_dispatch_pending()
ngx_int_t brix_proxy_dispatch_pending (brix_proxy_ctx_t * proxy)
Definition at line 150 of file forward_relay_dispatch.c.
References brix_proxy_lazy_open(), brix_proxy_pending_flush(), brix_proxy_pending_lazy_fh(), BRIX_TAP_C2U, brix_tap_decode_request(), brix_tap_emit(), c, ClientRequestHdr::requestid, ClientRequestHdr::streamid, and XRD_REQUEST_HDR_LEN.
Referenced by pc_select_endpoint(), proxy_bs_adopt_conn(), and proxy_gsi_login_done().
brix_proxy_pending_flush()
static ngx_int_t brix_proxy_pending_flush (brix_proxy_ctx_t * proxy, u_char * req, size_t len) static
Definition at line 123 of file forward_relay_dispatch.c.
References brix_proxy_abort(), brix_proxy_flush(), and XRD_PX_FORWARDING.
Referenced by brix_proxy_dispatch_pending().
brix_proxy_pending_lazy_fh()
static int brix_proxy_pending_lazy_fh (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, const u_char * req, size_t len, uint16_t reqid) static
Definition at line 81 of file forward_relay_dispatch.c.
References BRIX_MAX_FILES, BRIX_PROXY_FH_FREE, brix_ctx_t::is_bound, kXR_pgread, kXR_read, kXR_readv, and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_dispatch_pending().
brix_proxy_tap_audit_sink()
void brix_proxy_tap_audit_sink (void * ctx, const brix_tap_frame_t * f, brix_tap_dir_t dir, const u_char * payload, size_t payload_len)
Definition at line 12 of file forward_relay_dispatch.c.
References brix_tap_audit_format(), and log.
Referenced by brix_proxy_tap_init().
brix_proxy_tap_init()
void brix_proxy_tap_init (brix_proxy_ctx_t * proxy, ngx_connection_t * c)
Definition at line 27 of file forward_relay_dispatch.c.
References brix_proxy_tap_audit_sink(), brix_tap_register_sink(), and c.
Referenced by brix_proxy_dispatch().