nginx-xrootd: src/net/proxy/forward_relay_response.c File Reference
forward_relay_response.c File Reference
#include "proxy_internal.h"
#include "protocols/root/session/registry.h"
#include "protocols/root/protocol/frame_hdr.h"
#include "core/compat/cstr.h"
#include "forward_relay_response_internal.h"
Functions
void proxy_write_path_audit (brix_proxy_ctx_t *proxy, uint16_t status)
static int brix_proxy_relay_try_redirect (brix_proxy_ctx_t *proxy, ngx_connection_t *c, uint16_t status, u_char *body, uint32_t dlen)
static void brix_proxy_relay_emit_tap (brix_proxy_ctx_t *proxy, uint16_t status, uint32_t dlen)
static void brix_proxy_reset_response_state (brix_proxy_ctx_t *proxy)
static int brix_proxy_relay_absorb_wait (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, uint16_t status, u_char *body, uint32_t dlen)
static void brix_proxy_relay_wait_exhausted (brix_proxy_ctx_t *proxy, uint16_t status)
static void brix_proxy_relay_path_audit (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, uint16_t status)
static void brix_proxy_free_wait_retry (brix_proxy_ctx_t *proxy)
static void brix_proxy_relay_open_status (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, uint16_t status, u_char *body, uint32_t dlen)
static void brix_proxy_relay_io_metrics (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, uint16_t status, uint32_t dlen)
static void brix_proxy_relay_close_status (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, uint16_t status)
static u_char * brix_proxy_build_relay_buffer (brix_proxy_ctx_t *proxy, ngx_connection_t *c, uint16_t status, u_char *body, uint32_t dlen, size_t *total)
static int brix_proxy_relay_streaming_frame (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, uint16_t status, u_char resptype, u_char *buf, size_t total)
static void brix_proxy_relay_finish_final (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, u_char *buf, size_t total)
void brix_proxy_relay_to_client (brix_proxy_ctx_t *proxy)
Function Documentation
brix_proxy_build_relay_buffer()
static u_char * brix_proxy_build_relay_buffer (brix_proxy_ctx_t * proxy, ngx_connection_t * c, uint16_t status, u_char * body, uint32_t dlen, size_t * total) static
Definition at line 312 of file forward_relay_response.c.
References brix_build_resp_hdr(), brix_proxy_abort(), c, kXR_status, ngx_memcpy, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_proxy_relay_to_client().
brix_proxy_free_wait_retry()
static void brix_proxy_free_wait_retry (brix_proxy_ctx_t * proxy) static
Definition at line 213 of file forward_relay_response.c.
Referenced by brix_proxy_relay_finish_final(), and brix_proxy_relay_open_status().
brix_proxy_relay_absorb_wait()
static int brix_proxy_relay_absorb_wait (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, uint16_t status, u_char * body, uint32_t dlen) static
Definition at line 140 of file forward_relay_response.c.
References BRIX_PROXY_MAX_WAIT_RETRIES, BRIX_PROXY_MAX_WAIT_SECS, BRIX_PROXY_METRIC_INC, brix_proxy_reset_response_state(), BRIX_PROXY_UP_INC, brix_proxy_wait_handler(), c, kXR_wait, and xrd_wait_secs_parse().
Referenced by brix_proxy_relay_to_client().
brix_proxy_relay_close_status()
static void brix_proxy_relay_close_status (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, uint16_t status) static
Definition at line 295 of file forward_relay_response.c.
References BRIX_MAX_FILES, BRIX_PROXY_FH_FREE, BRIX_PROXY_METRIC_INC, BRIX_PROXY_UP_INC, kXR_close, kXR_ok, and proxy_write_audit().
Referenced by brix_proxy_relay_to_client().
brix_proxy_relay_emit_tap()
static void brix_proxy_relay_emit_tap (brix_proxy_ctx_t * proxy, uint16_t status, uint32_t dlen) static
Definition at line 116 of file forward_relay_response.c.
References brix_tap_emit(), BRIX_TAP_U2C, brix_tap_frame_t::dlen, brix_tap_frame_t::is_request, brix_tap_frame_t::status, and brix_tap_frame_t::streamid.
Referenced by brix_proxy_relay_to_client().
brix_proxy_relay_finish_final()
static void brix_proxy_relay_finish_final (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, u_char * buf, size_t total) static
Definition at line 362 of file forward_relay_response.c.
References brix_proxy_free_wait_retry(), brix_queue_response(), brix_schedule_read_resume(), c, brix_ctx_t::state, XRD_PX_IDLE, and XRD_ST_REQ_HEADER.
Referenced by brix_proxy_relay_to_client().
brix_proxy_relay_io_metrics()
static void brix_proxy_relay_io_metrics (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, uint16_t status, uint32_t dlen) static
Definition at line 259 of file forward_relay_response.c.
References BRIX_MAX_FILES, BRIX_PROXY_METRIC_ADD, BRIX_PROXY_METRIC_INC, BRIX_PROXY_UP_ADD, BRIX_PROXY_UP_INC, kXR_ok, kXR_oksofar, kXR_pgread, kXR_pgwrite, kXR_read, kXR_readv, kXR_write, and kXR_writev.
Referenced by brix_proxy_relay_to_client().
brix_proxy_relay_open_status()
static void brix_proxy_relay_open_status (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, uint16_t status, u_char * body, uint32_t dlen) static
Definition at line 222 of file forward_relay_response.c.
References BRIX_MAX_FILES, BRIX_PROXY_FH_FREE, brix_proxy_free_wait_retry(), BRIX_PROXY_METRIC_INC, BRIX_PROXY_UP_INC, kXR_error, kXR_ok, and kXR_open.
Referenced by brix_proxy_relay_to_client().
brix_proxy_relay_path_audit()
static void brix_proxy_relay_path_audit (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, uint16_t status) static
Definition at line 195 of file forward_relay_response.c.
References BRIX_PROXY_METRIC_INC, BRIX_PROXY_UP_INC, kXR_error, kXR_ok, and proxy_write_path_audit().
Referenced by brix_proxy_relay_to_client().
brix_proxy_relay_streaming_frame()
static int brix_proxy_relay_streaming_frame (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, uint16_t status, u_char resptype, u_char * buf, size_t total) static
Definition at line 333 of file forward_relay_response.c.
References brix_proxy_reset_response_state(), brix_queue_response(), c, kXR_oksofar, kXR_status, kXR_wait, and kXR_waitresp.
Referenced by brix_proxy_relay_to_client().
brix_proxy_relay_to_client()
void brix_proxy_relay_to_client (brix_proxy_ctx_t * proxy)
Definition at line 376 of file forward_relay_response.c.
References brix_proxy_build_relay_buffer(), brix_proxy_relay_absorb_wait(), brix_proxy_relay_close_status(), brix_proxy_relay_emit_tap(), brix_proxy_relay_finish_final(), brix_proxy_relay_io_metrics(), brix_proxy_relay_lazy_open(), brix_proxy_relay_open_status(), brix_proxy_relay_path_audit(), brix_proxy_relay_streaming_frame(), brix_proxy_relay_try_redirect(), brix_proxy_relay_wait_exhausted(), c, and kXR_status.
Referenced by proxy_read_dispatch().
brix_proxy_relay_try_redirect()
static int brix_proxy_relay_try_redirect (brix_proxy_ctx_t * proxy, ngx_connection_t * c, uint16_t status, u_char * body, uint32_t dlen) static
Definition at line 39 of file forward_relay_response.c.
References brix_cbuf_copy(), brix_proxy_connect(), c, kXR_redirect, XRD_PX_BS_HANDSHAKE, and XRD_PX_CONNECTING.
Referenced by brix_proxy_relay_to_client().
brix_proxy_relay_wait_exhausted()
static void brix_proxy_relay_wait_exhausted (brix_proxy_ctx_t * proxy, uint16_t status) static
Definition at line 176 of file forward_relay_response.c.
References BRIX_MAX_FILES, BRIX_PROXY_FH_FREE, kXR_open, and kXR_wait.
Referenced by brix_proxy_relay_to_client().
brix_proxy_reset_response_state()
static void brix_proxy_reset_response_state (brix_proxy_ctx_t * proxy) static
Definition at line 131 of file forward_relay_response.c.
Referenced by brix_proxy_relay_absorb_wait(), and brix_proxy_relay_streaming_frame().
proxy_write_path_audit()
void proxy_write_path_audit (brix_proxy_ctx_t * proxy, uint16_t status) extern
Definition at line 12 of file forward_relay_audit.c.
References BRIX_PROXY_PATH_MAX, kXR_chmod, kXR_mkdir, kXR_mv, kXR_ok, kXR_rm, kXR_rmdir, and kXR_truncate.
Referenced by brix_proxy_relay_path_audit().