nginx-xrootd: src/protocols/root/protocol/frame_hdr.h File Reference
frame_hdr.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <arpa/inet.h>
Functions
static uint16_t xrd_get_u16_be (const void *p)
static uint32_t xrd_get_u32_be (const void *p)
static uint64_t xrd_get_u64_be (const void *p)
static void xrd_put_u16_be (void *p, uint16_t v)
static void xrd_put_u32_be (void *p, uint32_t v)
static void xrd_put_u64_be (void *p, uint64_t v)
static void xrd_resp_hdr_unpack (const uint8_t h[8], uint16_t *streamid, uint16_t *status, uint32_t *dlen)
static uint32_t xrd_wait_secs_parse (const uint8_t *body, uint32_t blen, uint32_t fallback, uint32_t cap)
static int xrd_error_body_decode (const uint8_t *body, uint32_t dlen, int *errnum, const char **msg, size_t *msglen)
Function Documentation
xrd_error_body_decode()
static int xrd_error_body_decode (const uint8_t * body, uint32_t dlen, int * errnum, const char ** msg, size_t * msglen) inline static
Definition at line 115 of file frame_hdr.h.
References xrd_get_u32_be().
Referenced by aconn_dispatch_response(), brix_cache_set_origin_error(), origin_status_errno(), read_status_frame(), and tpc_open_extract_fhandle().
xrd_get_u16_be()
static uint16_t xrd_get_u16_be (const void * p) inline static
Definition at line 30 of file frame_hdr.h.
Referenced by brix_roundtrip(), brix_send_ext(), brix_sigver_maybe(), brix_tap_decode_request(), and xrd_resp_hdr_unpack().
xrd_get_u32_be()
static uint32_t xrd_get_u32_be (const void * p) inline static
Definition at line 38 of file frame_hdr.h.
Referenced by aconn_handle_attn(), brix_cache_origin_query_checksum(), brix_readv_seg_rlen(), brix_tap_decode_request(), brix_tap_decode_response(), brix_trace_error(), brix_trace_redirect(), brix_trace_wait(), do_handshake(), parse_redirect(), read_status_frame(), recv_after_waitresp(), recv_dispatch(), set_kxr_error_status(), tpc_open_resolve_attn(), waitresp_extend_window(), xrd_error_body_decode(), xrd_resp_hdr_unpack(), and xrd_wait_secs_parse().
xrd_get_u64_be()
static uint64_t xrd_get_u64_be (const void * p) inline static
Definition at line 46 of file frame_hdr.h.
xrd_put_u16_be()
static void xrd_put_u16_be (void * p, uint16_t v) inline static
Definition at line 55 of file frame_hdr.h.
xrd_put_u32_be()
static void xrd_put_u32_be (void * p, uint32_t v) inline static
Definition at line 62 of file frame_hdr.h.
Referenced by brix_readv_seg_pack().
xrd_put_u64_be()
static void xrd_put_u64_be (void * p, uint64_t v) inline static
Definition at line 69 of file frame_hdr.h.
Referenced by brix_readv_seg_pack().
xrd_resp_hdr_unpack()
static void xrd_resp_hdr_unpack (const uint8_t h[8], uint16_t * streamid, uint16_t * status, uint32_t * dlen) inline static
Definition at line 83 of file frame_hdr.h.
References xrd_get_u16_be(), and xrd_get_u32_be().
Referenced by aconn_handle_attn(), aconn_parse(), asynresp_deliver(), brix_cache_origin_query_checksum(), brix_tap_decode_response(), frame_read_header(), read_status_frame(), and recv_raw().
xrd_wait_secs_parse()
static uint32_t xrd_wait_secs_parse (const uint8_t * body, uint32_t blen, uint32_t fallback, uint32_t cap) inline static
Definition at line 98 of file frame_hdr.h.
References s, and xrd_get_u32_be().
Referenced by areq_note_deferral(), brix_proxy_relay_absorb_wait(), brix_upstream_forward_response(), rt_handle_wait(), and tpc_open_wait_resend().