nginx-xrootd: src/net/cms/frame_io.c File Reference
frame_io.c File Reference
#include "frame_io.h"
Functions
ngx_int_t brix_cms_send_all (ngx_connection_t *c, const u_char *buf, size_t len)
ngx_int_t brix_cms_send_frame (ngx_connection_t *c, uint32_t streamid, u_char code, u_char modifier, const u_char *payload, size_t payload_len)
Function Documentation
brix_cms_send_all()
ngx_int_t brix_cms_send_all (ngx_connection_t * c, const u_char * buf, size_t len)
Definition at line 20 of file frame_io.c.
References c.
Referenced by brix_cms_send_frame().
brix_cms_send_frame()
ngx_int_t brix_cms_send_frame (ngx_connection_t * c, uint32_t streamid, u_char code, u_char modifier, const u_char * payload, size_t payload_len)
Definition at line 64 of file frame_io.c.
References brix_cms_send_all(), c, code, NGX_BRIX_CMS_HDR_LEN, ngx_brix_cms_put16(), and ngx_brix_cms_put32().
Referenced by brix_cms_forward_to_node(), brix_cms_srv_send_frame(), brix_cns_emit_close(), and ngx_brix_cms_send_frame().