nginx-xrootd: client/lib/protocols/root/frame.c File Reference
frame.c File Reference
#include "brix.h"
#include <arpa/inet.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <time.h>
#include "protocols/root/protocol/frame_hdr.h"
#include "core/compat/host_format.h"
Data Structures
struct rx_frame_t
struct redir_tgt_t
struct rt_req_t
Functions
int brix_send_ext (brix_conn *c, void *hdr24, const brix_payload_ext *pl, uint16_t *out_sid, brix_status *st)
int brix_send (brix_conn *c, void *hdr24, const brix_payload *pl, uint16_t *out_sid, brix_status *st)
static int frame_read_header (brix_conn *c, uint8_t *hdr, rx_frame_t *f, brix_status *st)
static int frame_read_body (brix_conn *c, rx_frame_t *f, brix_status *st)
static void set_kxr_error_status (const uint8_t *data, uint32_t dlen, brix_status *st)
static int recv_raw_frame (brix_conn *c, rx_frame_t *f, brix_status *st)
static void waitresp_extend_window (brix_conn *c, rx_frame_t *f)
static int asynresp_deliver (uint16_t want_sid, rx_frame_t *f, brix_resp_out *out, brix_status *st)
static int recv_after_waitresp (brix_conn *c, uint16_t want_sid, unsigned secs, brix_resp_out *out, brix_status *st)
static void recv_note_diag (brix_conn *c, const uint8_t *hdr, const rx_frame_t *f)
static int resp_deliver (brix_resp_out *out, uint16_t stat, uint8_t *buf, uint32_t dlen)
static int recv_dispatch (brix_conn *c, uint16_t want_sid, rx_frame_t *f, brix_resp_out *out, brix_status *st)
int brix_recv (brix_conn *c, uint16_t want_sid, brix_resp_out *out, brix_status *st)
static int parse_redirect (const uint8_t *body, uint32_t blen, redir_tgt_t *t)
static int tried_seen (brix_conn *c, const char *hostport)
static int follow_redirect (brix_conn *c, const char *rhost, int rport, brix_status *st)
static int open_payload_with_opaque (const char *opaque, rt_req_t *rq, brix_status *st)
static int rt_handle_redirect (brix_conn *c, rt_req_t *rq, uint8_t *bd, uint32_t bl, brix_status *st)
static int rt_handle_wait (brix_conn *c, uint8_t *bd, uint32_t bl, int *waits, brix_status *st)
static int roundtrip_loop (brix_conn *c, void *hdr24, rt_req_t *rq, brix_resp_out *out, brix_status *st)
int brix_roundtrip (brix_conn *c, void *hdr24, const brix_payload *pl, brix_resp_out *out, brix_status *st)
Function Documentation
asynresp_deliver()
static int asynresp_deliver (uint16_t want_sid, rx_frame_t * f, brix_resp_out * out, brix_status * st) static
Definition at line 227 of file frame.c.
References brix_resp_out::blen, brix_resp_out::body, brix_status_set(), rx_frame_t::buf, rx_frame_t::dlen, kXR_error, set_kxr_error_status(), brix_resp_out::status, xrd_resp_hdr_unpack(), and XRDC_EPROTO.
Referenced by recv_after_waitresp().
brix_recv()
int brix_recv (brix_conn * c, uint16_t want_sid, brix_resp_out * out, brix_status * st)
Definition at line 425 of file frame.c.
References brix_resp_out::blen, brix_resp_out::body, brix_status_set(), c, frame_read_body(), frame_read_header(), recv_dispatch(), recv_note_diag(), rx_frame_t::sid, XRD_RESPONSE_HDR_LEN, and XRDC_EPROTO.
Referenced by brix_bind(), brix_file_close(), brix_file_read(), brix_file_sync(), brix_file_write(), brix_file_writev(), brix_readv_accumulate(), dirlist_accumulate(), do_login(), playback_reissue_wire(), raw_send_expect_reject(), roundtrip_loop(), and run_module().
brix_roundtrip()
int brix_roundtrip (brix_conn * c, void * hdr24, const brix_payload * pl, brix_resp_out * out, brix_status * st)
Definition at line 765 of file frame.c.
References c, rt_req_t::cur_len, rt_req_t::cur_pl, brix_payload::data, brix_payload::len, rt_req_t::orig_len, rt_req_t::orig_pl, rt_req_t::rebuilt, rt_req_t::reqid, roundtrip_loop(), and xrd_get_u16_be().
Referenced by brix_fattr_get(), brix_fattr_list(), brix_file_open_opaque(), brix_readlink(), brix_roundtrip_resilient(), dirlist_accumulate(), ext_simple(), and fattr_set_or_del().
brix_send()
int brix_send (brix_conn * c, void * hdr24, const brix_payload * pl, uint16_t * out_sid, brix_status * st)
Definition at line 81 of file frame.c.
References brix_send_ext(), c, brix_payload::data, and brix_payload::len.
Referenced by brix_bind(), brix_close(), brix_file_close(), brix_file_pgread(), brix_file_pgwrite(), brix_file_read(), brix_file_readv(), brix_file_sync(), brix_file_write(), do_login(), pgwrite_retry_one(), roundtrip_loop(), and send_auth().
brix_send_ext()
int brix_send_ext (brix_conn * c, void * hdr24, const brix_payload_ext * pl, uint16_t * out_sid, brix_status * st)
Definition at line 27 of file frame.c.
References brix_capture_frame(), brix_mono_ns(), brix_sigver_maybe(), brix_trace_frame(), brix_write_full(), c, brix_payload_ext::data, brix_payload_ext::dlen, brix_payload_ext::len, xrd_get_u16_be(), and XRD_REQUEST_HDR_LEN.
Referenced by brix_file_writev(), and brix_send().
follow_redirect()
static int follow_redirect (brix_conn * c, const char * rhost, int rport, brix_status * st) static
Definition at line 544 of file frame.c.
References brix_reconnect(), brix_status_set(), c, brix_status::msg, XRDC_ESOCK, and XRDC_MSG_MAX.
Referenced by rt_handle_redirect().
frame_read_body()
static int frame_read_body (brix_conn * c, rx_frame_t * f, brix_status * st) static
Definition at line 137 of file frame.c.
References brix_read_full(), brix_status_set(), rx_frame_t::buf, c, rx_frame_t::dlen, and XRDC_EPROTO.
Referenced by brix_recv(), and recv_raw_frame().
frame_read_header()
static int frame_read_header (brix_conn * c, uint8_t * hdr, rx_frame_t * f, brix_status * st) static
Definition at line 114 of file frame.c.
References brix_read_full(), brix_status_set(), rx_frame_t::buf, c, rx_frame_t::dlen, rx_frame_t::sid, rx_frame_t::stat, xrd_resp_hdr_unpack(), XRD_RESPONSE_HDR_LEN, XRDC_DLEN_MAX, and XRDC_EPROTO.
Referenced by brix_recv(), and recv_raw_frame().
open_payload_with_opaque()
static int open_payload_with_opaque (const char * opaque, rt_req_t * rq, brix_status * st) static
Definition at line 590 of file frame.c.
References brix_status_set(), rt_req_t::cur_len, rt_req_t::cur_pl, rt_req_t::orig_len, rt_req_t::orig_pl, rt_req_t::rebuilt, and XRDC_EPROTO.
Referenced by rt_handle_redirect().
parse_redirect()
static int parse_redirect (const uint8_t * body, uint32_t blen, redir_tgt_t * t) static
Definition at line 467 of file frame.c.
References redir_tgt_t::host, redir_tgt_t::opaque, redir_tgt_t::port, and xrd_get_u32_be().
Referenced by rt_handle_redirect().
recv_after_waitresp()
static int recv_after_waitresp (brix_conn * c, uint16_t want_sid, unsigned secs, brix_resp_out * out, brix_status * st) static
Definition at line 278 of file frame.c.
References asynresp_deliver(), brix_status_set(), rx_frame_t::buf, c, rx_frame_t::dlen, kXR_asynresp, kXR_attn, kXR_waitresp, recv_raw_frame(), s, rx_frame_t::stat, waitresp_extend_window(), xrd_get_u32_be(), XRDC_EPROTO, and XRDC_REDIR_MAX.
Referenced by recv_dispatch().
recv_dispatch()
static int recv_dispatch (brix_conn * c, uint16_t want_sid, rx_frame_t * f, brix_resp_out * out, brix_status * st) static
Definition at line 382 of file frame.c.
References brix_status_set(), rx_frame_t::buf, c, rx_frame_t::dlen, kXR_authmore, kXR_error, kXR_ok, kXR_oksofar, kXR_redirect, kXR_wait, kXR_waitresp, recv_after_waitresp(), resp_deliver(), set_kxr_error_status(), rx_frame_t::stat, xrd_get_u32_be(), and XRDC_EPROTO.
Referenced by brix_recv().
recv_note_diag()
static void recv_note_diag (brix_conn * c, const uint8_t * hdr, const rx_frame_t * f) static
Definition at line 333 of file frame.c.
References brix_capture_frame(), brix_mono_ns(), brix_trace_frame(), rx_frame_t::buf, c, rx_frame_t::dlen, kXR_1stRequest, rx_frame_t::sid, rx_frame_t::stat, XRD_RESPONSE_HDR_LEN, and XRDC_NOP.
Referenced by brix_recv().
recv_raw_frame()
static int recv_raw_frame (brix_conn * c, rx_frame_t * f, brix_status * st) static
Definition at line 182 of file frame.c.
References brix_trace_frame(), rx_frame_t::buf, c, rx_frame_t::dlen, frame_read_body(), frame_read_header(), rx_frame_t::sid, rx_frame_t::stat, and XRD_RESPONSE_HDR_LEN.
Referenced by recv_after_waitresp().
resp_deliver()
static int resp_deliver (brix_resp_out * out, uint16_t stat, uint8_t * buf, uint32_t dlen) static
Definition at line 364 of file frame.c.
References brix_resp_out::blen, brix_resp_out::body, stat(), and brix_resp_out::status.
Referenced by recv_dispatch().
roundtrip_loop()
static int roundtrip_loop (brix_conn * c, void * hdr24, rt_req_t * rq, brix_resp_out * out, brix_status * st) static
Definition at line 720 of file frame.c.
References brix_resp_out::blen, brix_resp_out::body, brix_recv(), brix_send(), c, rt_req_t::cur_len, rt_req_t::cur_pl, kXR_redirect, kXR_wait, rr(), rt_handle_redirect(), rt_handle_wait(), and brix_resp_out::status.
Referenced by brix_roundtrip().
rt_handle_redirect()
static int rt_handle_redirect (brix_conn * c, rt_req_t * rq, uint8_t * bd, uint32_t bl, brix_status * st) static
Definition at line 622 of file frame.c.
References brix_format_host_port(), brix_status_set(), c, follow_redirect(), redir_tgt_t::host, kXR_open, redir_tgt_t::opaque, open_payload_with_opaque(), parse_redirect(), redir_tgt_t::port, rt_req_t::reqid, tried_seen(), XRDC_EPROTO, XRDC_EREDIRECT, XRDC_HOSTPORT_MAX, and XRDC_REDIR_MAX.
Referenced by roundtrip_loop().
rt_handle_wait()
static int rt_handle_wait (brix_conn * c, uint8_t * bd, uint32_t bl, int * waits, brix_status * st) static
Definition at line 692 of file frame.c.
References brix_jitter_ms(), brix_status_set(), c, xrd_wait_secs_parse(), XRDC_EPROTO, and XRDC_REDIR_MAX.
Referenced by roundtrip_loop().
set_kxr_error_status()
static void set_kxr_error_status (const uint8_t * data, uint32_t dlen, brix_status * st) static
Definition at line 166 of file frame.c.
References brix_kxr_name(), brix_status_set(), and xrd_get_u32_be().
Referenced by asynresp_deliver(), and recv_dispatch().
tried_seen()
static int tried_seen (brix_conn * c, const char * hostport) static
Definition at line 517 of file frame.c.
References c.
Referenced by rt_handle_redirect().
waitresp_extend_window()
static void waitresp_extend_window (brix_conn * c, rx_frame_t * f) static
Definition at line 206 of file frame.c.
References rx_frame_t::buf, c, rx_frame_t::dlen, and xrd_get_u32_be().
Referenced by recv_after_waitresp().