nginx-xrootd: src/observability/metrics/frm_metrics.c File Reference
frm_metrics.c File Reference
#include "metrics_internal.h"
Functions
void brix_export_frm_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
Variables
static const char * brix_frm_fail_names [5]
static const unsigned long brix_frm_latency_bounds [8 - 1]
Function Documentation
brix_export_frm_metrics()
void brix_export_frm_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 43 of file frm_metrics.c.
References ngx_brix_frm_metrics_t::asynresp_total, brix_frm_fail_names, brix_frm_latency_bounds, BRIX_FRM_LATENCY_BUCKETS, BRIX_FRM_NFAIL, ngx_brix_frm_metrics_t::cmsd_have_total, ngx_brix_frm_metrics_t::dedup_hits_total, ngx_brix_frm_metrics_t::evict_total, ngx_brix_metrics_t::frm, ngx_brix_frm_metrics_t::in_flight, ngx_brix_frm_metrics_t::migrate_total, mw_emit_labeled(), mw_emit_scalar(), mw_printf(), ngx_brix_frm_metrics_t::purge_total, ngx_brix_frm_metrics_t::reject_inflight_total, ngx_brix_frm_metrics_t::requests_total, ngx_brix_frm_metrics_t::stage_fail_total, ngx_brix_frm_metrics_t::stage_latency_bucket, ngx_brix_frm_metrics_t::stage_latency_count, ngx_brix_frm_metrics_t::stage_latency_sum_sec, ngx_brix_frm_metrics_t::stage_success_total, and ngx_brix_frm_metrics_t::waitresp_total.
Referenced by brix_export_prometheus_metrics().
Variable Documentation
brix_frm_fail_names
const char* brix_frm_fail_names[5] static
Initial value:
= {
    "copycmd",
    "dispatch",
    "timeout",
    "verify",
    "other",
}
Definition at line 28 of file frm_metrics.c.
Referenced by brix_export_frm_metrics().
brix_frm_latency_bounds
const unsigned long brix_frm_latency_bounds[8 - 1] static
Initial value:
= {
    1, 10, 30, 60, 300, 1800, 3600,
}
Definition at line 38 of file frm_metrics.c.
Referenced by brix_export_frm_metrics().