nginx-xrootd: src/fs/cache/directives.c File Reference
directives.c File Reference
#include "core/config/config.h"
#include <errno.h>
#include <regex.h>
#include <stdlib.h>
#include <string.h>
#include "core/compat/alloc_guard.h"
#include "core/compat/str_dup.h"
#include "core/compat/checksum.h"
#include "core/compat/af_policy.h"
#include "verify.h"
#include "core/compat/cstr.h"
#include "cache_internal.h"
Functions
char * brix_conf_set_cache_origin_family (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cache_eviction_threshold (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cache_watermark (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cache_max_file_size (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cache_include_regex (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cache_verify (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cache_verify_digest (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cache_advertise_ns (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_push_prefix (ngx_conf_t *cf, ngx_array_t **target, const char *log_label)
char * brix_conf_set_cache_deny_prefix (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cache_allow_prefix (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Function Documentation
brix_conf_push_prefix()
char * brix_conf_push_prefix (ngx_conf_t * cf, ngx_array_t ** target, const char * log_label)
Definition at line 402 of file directives.c.
References brix_pstrdup_z(), and brix_wt_prefix_entry_t::prefix.
Referenced by brix_conf_add_wt_prefix(), brix_conf_set_cache_allow_prefix(), and brix_conf_set_cache_deny_prefix().
brix_conf_set_cache_advertise_ns()
char * brix_conf_set_cache_advertise_ns (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 363 of file directives.c.
References BRIX_PNALLOC_OR_RETURN, and ngx_memcpy.
brix_conf_set_cache_allow_prefix()
char * brix_conf_set_cache_allow_prefix (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 442 of file directives.c.
References brix_conf_push_prefix().
brix_conf_set_cache_deny_prefix()
char * brix_conf_set_cache_deny_prefix (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 433 of file directives.c.
References brix_conf_push_prefix().
brix_conf_set_cache_eviction_threshold()
char * brix_conf_set_cache_eviction_threshold (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 47 of file directives.c.
References BRIX_CACHE_PPM_FULL_SCALE, and brix_pstrdup_z().
brix_conf_set_cache_include_regex()
char * brix_conf_set_cache_include_regex (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 243 of file directives.c.
References brix_pstrdup_z().
brix_conf_set_cache_max_file_size()
char * brix_conf_set_cache_max_file_size (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 169 of file directives.c.
References brix_str_cbuf().
brix_conf_set_cache_origin_family()
char * brix_conf_set_cache_origin_family (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 26 of file directives.c.
References brix_af_policy_parse().
brix_conf_set_cache_verify()
char * brix_conf_set_cache_verify (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 289 of file directives.c.
References BRIX_CACHE_VERIFY_BESTEFFORT, BRIX_CACHE_VERIFY_OFF, and BRIX_CACHE_VERIFY_REQUIRE.
brix_conf_set_cache_verify_digest()
char * brix_conf_set_cache_verify_digest (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 324 of file directives.c.
References alg, brix_checksum_parse(), and brix_pstrdupz().
brix_conf_set_cache_watermark()
char * brix_conf_set_cache_watermark (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 110 of file directives.c.
References BRIX_CACHE_PPM_FULL_SCALE, and brix_pstrdup_z().