nginx-xrootd: src/fs/path/unified.c File Reference
unified.c File Reference
#include "core/ngx_brix_module.h"
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "path_internal.h"
#include "unified.h"
Functions
static void brix_path_result_init (brix_path_result_t *result)
static void brix_path_warn (ngx_log_t *log, const char *prefix, const char *path)
static ngx_uint_t brix_count_components_cstr (const char *path)
static brix_path_status_t brix_validate_components_cstr (ngx_log_t *log, const char *path)
static ngx_flag_t brix_has_trailing_slash_cstr (const char *path)
static brix_path_status_t brix_copy_cstr (char *dst, size_t dstsz, const char *src)
static brix_path_status_t brix_append_component (char *path, size_t pathsz, size_t *len, const char *component, size_t component_len)
static brix_path_status_t brix_build_candidate (const char *root_canon, const char *req_path, brix_path_opts_t opts, char *candidate, size_t candidatesz, ngx_uint_t *depth_out)
static ngx_int_t brix_stat_type_cstr (const char *path)
static brix_path_status_t brix_finish_resolved (ngx_log_t *log, const char *root_canon, const char *resolved_path, brix_path_opts_t opts, char *resolved, size_t resolvsz, brix_path_result_t *result, ngx_uint_t depth)
static brix_path_status_t brix_resolve_missing_tail (ngx_log_t *log, const char *root_canon, const char *candidate, char *resolved, size_t resolvsz, brix_path_result_t *result, ngx_uint_t depth)
static brix_path_status_t brix_resolve_missing_parents (ngx_log_t *log, const char *root_canon, const char *candidate, char *resolved, size_t resolvsz, brix_path_result_t *result, ngx_uint_t depth)
brix_path_status_t brix_path_resolve_cstr (ngx_log_t *log, const char *root_canon, const char *req_path, brix_path_opts_t opts, char *resolved, size_t resolvsz, brix_path_result_t *result)
Function Documentation
brix_append_component()
static brix_path_status_t brix_append_component (char * path, size_t pathsz, size_t * len, const char * component, size_t component_len) static
Definition at line 176 of file unified.c.
References BRIX_PATH_STATUS_OK, and BRIX_PATH_STATUS_TOO_LONG.
Referenced by brix_build_candidate().
brix_build_candidate()
static brix_path_status_t brix_build_candidate (const char * root_canon, const char * req_path, brix_path_opts_t opts, char * candidate, size_t candidatesz, ngx_uint_t * depth_out) static
Definition at line 198 of file unified.c.
References brix_path_opts_t::allow_root, brix_append_component(), brix_count_components_cstr(), BRIX_PATH_STATUS_INVALID, BRIX_PATH_STATUS_OK, and BRIX_PATH_STATUS_TOO_LONG.
Referenced by brix_path_resolve_cstr().
brix_copy_cstr()
static brix_path_status_t brix_copy_cstr (char * dst, size_t dstsz, const char * src) static
Definition at line 158 of file unified.c.
References BRIX_PATH_STATUS_ERROR, BRIX_PATH_STATUS_OK, and BRIX_PATH_STATUS_TOO_LONG.
Referenced by brix_finish_resolved().
brix_count_components_cstr()
static ngx_uint_t brix_count_components_cstr (const char * path) static
Definition at line 66 of file unified.c.
Referenced by brix_build_candidate().
brix_finish_resolved()
static brix_path_status_t brix_finish_resolved (ngx_log_t * log, const char * root_canon, const char * resolved_path, brix_path_opts_t opts, char * resolved, size_t resolvsz, brix_path_result_t * result, ngx_uint_t depth) static
Definition at line 280 of file unified.c.
References brix_path_opts_t::allow_missing_parents, brix_path_opts_t::allow_missing_tail, brix_copy_cstr(), BRIX_PATH_STATUS_ERROR, BRIX_PATH_STATUS_INVALID, BRIX_PATH_STATUS_OK, BRIX_PATH_TYPE_NOT_FOUND, brix_path_warn(), brix_path_within_root(), brix_stat_type_cstr(), brix_path_result_t::depth, brix_path_result_t::is_confined, log, brix_path_opts_t::require_directory, brix_path_result_t::resolved, and brix_path_result_t::type.
Referenced by brix_path_resolve_cstr(), brix_resolve_missing_parents(), and brix_resolve_missing_tail().
brix_has_trailing_slash_cstr()
static ngx_flag_t brix_has_trailing_slash_cstr (const char * path) static
Definition at line 145 of file unified.c.
Referenced by brix_path_resolve_cstr().
brix_path_resolve_cstr()
brix_path_status_t brix_path_resolve_cstr (ngx_log_t * log, const char * root_canon, const char * req_path, brix_path_opts_t opts, char * resolved, size_t resolvsz, brix_path_result_t * result)
Definition at line 486 of file unified.c.
References brix_path_opts_t::allow_missing_parents, brix_path_opts_t::allow_missing_tail, brix_build_candidate(), brix_finish_resolved(), brix_has_trailing_slash_cstr(), brix_path_result_init(), BRIX_PATH_STATUS_ERROR, BRIX_PATH_STATUS_INVALID, BRIX_PATH_STATUS_NOT_FOUND, BRIX_PATH_STATUS_OK, brix_resolve_missing_parents(), brix_resolve_missing_tail(), brix_validate_components_cstr(), log, and PATH_MAX.
Referenced by brix_resolve_with_opts().
brix_path_result_init()
static void brix_path_result_init (brix_path_result_t * result) static
Definition at line 45 of file unified.c.
References BRIX_PATH_TYPE_NOT_FOUND, brix_path_result_t::depth, brix_path_result_t::is_confined, brix_path_result_t::resolved, and brix_path_result_t::type.
Referenced by brix_path_resolve_cstr().
brix_path_warn()
static void brix_path_warn (ngx_log_t * log, const char * prefix, const char * path) static
Definition at line 58 of file unified.c.
References brix_log_path_warning(), and log.
Referenced by brix_finish_resolved(), brix_resolve_missing_parents(), brix_resolve_missing_tail(), and brix_validate_components_cstr().
brix_resolve_missing_parents()
static brix_path_status_t brix_resolve_missing_parents (ngx_log_t * log, const char * root_canon, const char * candidate, char * resolved, size_t resolvsz, brix_path_result_t * result, ngx_uint_t depth) static
Definition at line 394 of file unified.c.
References brix_path_opts_t::allow_missing_parents, brix_finish_resolved(), BRIX_PATH_STATUS_ERROR, BRIX_PATH_STATUS_INVALID, BRIX_PATH_STATUS_NOT_FOUND, BRIX_PATH_STATUS_TOO_LONG, brix_path_warn(), brix_path_within_root(), log, and PATH_MAX.
Referenced by brix_path_resolve_cstr().
brix_resolve_missing_tail()
static brix_path_status_t brix_resolve_missing_tail (ngx_log_t * log, const char * root_canon, const char * candidate, char * resolved, size_t resolvsz, brix_path_result_t * result, ngx_uint_t depth) static
Definition at line 323 of file unified.c.
References brix_path_opts_t::allow_missing_tail, brix_finish_resolved(), BRIX_PATH_STATUS_ERROR, BRIX_PATH_STATUS_INVALID, BRIX_PATH_STATUS_NOT_FOUND, BRIX_PATH_STATUS_TOO_LONG, brix_path_warn(), brix_path_within_root(), brix_path_opts_t::is_write_operation, log, and PATH_MAX.
Referenced by brix_path_resolve_cstr().
brix_stat_type_cstr()
static ngx_int_t brix_stat_type_cstr (const char * path) static
Definition at line 265 of file unified.c.
References BRIX_PATH_TYPE_NOT_FOUND, and stat().
Referenced by brix_finish_resolved().
brix_validate_components_cstr()
static brix_path_status_t brix_validate_components_cstr (ngx_log_t * log, const char * path) static
Definition at line 99 of file unified.c.
References brix_count_path_depth(), BRIX_MAX_PATH, brix_path_component_forbidden(), BRIX_PATH_STATUS_INVALID, BRIX_PATH_STATUS_OK, BRIX_PATH_STATUS_TOO_LONG, brix_path_warn(), and log.
Referenced by brix_path_resolve_cstr().