nginx-xrootd: src/fs/cache/io.c File Reference
io.c File Reference
#include "cache_internal.h"
#include "fs/backend/sd.h"
#include <errno.h>
#include <sys/socket.h>
#include <unistd.h>
Functions
int brix_cache_io_send (brix_cache_origin_conn_t *oc, const void *buf, size_t len)
int brix_cache_io_recv_exact (brix_cache_origin_conn_t *oc, void *buf, size_t len)
int brix_cache_fd_write_all (int fd, const void *buf, size_t len, off_t offset)
Function Documentation
brix_cache_fd_write_all()
int brix_cache_fd_write_all (int fd, const void * buf, size_t len, off_t offset)
Definition at line 122 of file io.c.
References brix_sd_posix_wrap().
Referenced by brix_cache_sink_pwrite().
brix_cache_io_recv_exact()
int brix_cache_io_recv_exact (brix_cache_origin_conn_t * oc, void * buf, size_t len)
Definition at line 69 of file io.c.
References brix_cache_origin_conn_t::fd, and brix_cache_origin_conn_t::ssl.
Referenced by brix_cache_read_response().
brix_cache_io_send()
int brix_cache_io_send (brix_cache_origin_conn_t * oc, const void * buf, size_t len)
Definition at line 15 of file io.c.
References brix_cache_origin_conn_t::fd, and brix_cache_origin_conn_t::ssl.
Referenced by brix_cache_origin_close_file(), brix_cache_origin_dirlist(), brix_cache_origin_open(), brix_cache_origin_open_write(), brix_cache_origin_read_chunk(), brix_cache_origin_sync(), brix_cache_origin_truncate(), brix_cache_origin_write_chunk(), cache_origin_send_kxr_auth(), origin_bs_handshake(), origin_bs_login(), origin_bs_protocol(), origin_cksum_send_query(), and origin_request().