nginx-xrootd: src/fs/cache/lock.c File Reference
lock.c File Reference
#include "cache_internal.h"
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <stdio.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Functions
static int brix_cache_lock_is_stale (const char *lock_path, time_t timeout)
static int brix_cache_try_lock (brix_cache_fill_t *t)
int brix_cache_wait_or_lock (brix_cache_fill_t *t, int *owned)
Function Documentation
brix_cache_lock_is_stale()
static int brix_cache_lock_is_stale (const char * lock_path, time_t timeout) static
Definition at line 32 of file lock.c.
References close(), fstat(), open(), read(), and stat().
Referenced by brix_cache_wait_or_lock().
brix_cache_try_lock()
static int brix_cache_try_lock (brix_cache_fill_t * t) static
Definition at line 85 of file lock.c.
References close(), brix_cache_fill_t::lock_path, and open().
Referenced by brix_cache_wait_or_lock().
brix_cache_wait_or_lock()
int brix_cache_wait_or_lock (brix_cache_fill_t * t, int * owned)
Definition at line 134 of file lock.c.
References brix_cache_file_ready(), brix_cache_lock_is_stale(), BRIX_CACHE_LOCK_POLL_USEC, brix_cache_set_error(), brix_cache_set_syserror(), brix_cache_try_lock(), brix_cache_fill_t::c, ngx_stream_brix_srv_conf_t::cache_lock_timeout, brix_cache_fill_t::cache_path, brix_cache_fill_t::conf, kXR_FileLocked, kXR_IOError, and brix_cache_fill_t::lock_path.
Referenced by brix_cache_fill_thread().