nginx-xrootd: src/fs/path/unified.h File Reference
unified.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <sys/stat.h>
Data Structures
struct brix_path_opts_t
struct brix_path_result_t
Macros
#define BRIX_PATH_TYPE_NOT_FOUND ((ngx_int_t) -2)
Enumerations
enum brix_path_status_t {
BRIX_PATH_STATUS_OK = 0 , BRIX_PATH_STATUS_INVALID , BRIX_PATH_STATUS_NOT_FOUND , BRIX_PATH_STATUS_TOO_LONG ,
BRIX_PATH_STATUS_ERROR
}
Functions
brix_path_status_t brix_path_resolve_cstr (ngx_log_t *log, const char *root_canon, const char *req_path, brix_path_opts_t opts, char *resolved, size_t resolvsz, brix_path_result_t *result)
Macro Definition Documentation
BRIX_PATH_TYPE_NOT_FOUND
#define BRIX_PATH_TYPE_NOT_FOUND ((ngx_int_t) -2)
Definition at line 25 of file unified.h.
Enumeration Type Documentation
brix_path_status_t
enum brix_path_status_t
Enumerator
BRIX_PATH_STATUS_OK
BRIX_PATH_STATUS_INVALID
BRIX_PATH_STATUS_NOT_FOUND
BRIX_PATH_STATUS_TOO_LONG
BRIX_PATH_STATUS_ERROR
Definition at line 34 of file unified.h.
Function Documentation
brix_path_resolve_cstr()
brix_path_status_t brix_path_resolve_cstr (ngx_log_t * log, const char * root_canon, const char * req_path, brix_path_opts_t opts, char * resolved, size_t resolvsz, brix_path_result_t * result)
Definition at line 89 of file unified.c.
References brix_path_opts_t::allow_missing_parents, brix_path_opts_t::allow_missing_tail, brix_build_candidate(), brix_finish_resolved(), brix_has_trailing_slash_cstr(), brix_path_result_init(), BRIX_PATH_STATUS_ERROR, BRIX_PATH_STATUS_INVALID, BRIX_PATH_STATUS_NOT_FOUND, BRIX_PATH_STATUS_OK, brix_resolve_missing_parents(), brix_resolve_missing_tail(), brix_validate_components_cstr(), brix_candidate_out_t::buf, brix_candidate_out_t::bufsz, brix_resolve_ctx_t::depth, brix_candidate_out_t::depth_out, log, brix_resolve_ctx_t::log, PATH_MAX, brix_resolve_ctx_t::resolved, brix_resolve_ctx_t::resolvsz, brix_resolve_ctx_t::result, and brix_resolve_ctx_t::root_canon.
Referenced by brix_resolve_with_opts().