nginx-xrootd: src/fs/cache/open.h File Reference
open.h File Reference
#include "fs/vfs/vfs.h"
Functions
ngx_int_t brix_cache_open (brix_vfs_ctx_t *ctx, ngx_uint_t flags, brix_vfs_file_t **fh_out)
ngx_int_t brix_cache_record_access (const char *cache_path, size_t bytes, ngx_log_t *log)
ngx_int_t brix_cache_path_for_resolved (const char *cache_root_canon, const char *root_canon, const char *resolved, char *out, size_t outsz)
Function Documentation
brix_cache_open()
ngx_int_t brix_cache_open (brix_vfs_ctx_t * ctx, ngx_uint_t flags, brix_vfs_file_t ** fh_out)
Definition at line 284 of file open.c.
References brix_cache_hit_fresh(), brix_cache_open_adopt(), brix_cache_open_declined(), brix_cache_path_for_resolved(), brix_cache_storage_by_root(), brix_vfs_ctx_path(), brix_vfs_ctx_t::cache_root_canon, key, PATH_MAX, and brix_vfs_ctx_t::root_canon.
Referenced by brix_vfs_open_try_cache().
brix_cache_path_for_resolved()
ngx_int_t brix_cache_path_for_resolved (const char * cache_root_canon, const char * root_canon, const char * resolved, char * out, size_t outsz)
Definition at line 102 of file open.c.
References brix_cache_export_suffix(), brix_cache_path_args_valid(), and ngx_memcpy.
Referenced by brix_cache_open(), and brix_cache_state_path().
brix_cache_record_access()
ngx_int_t brix_cache_record_access (const char * cache_path, size_t bytes, ngx_log_t * log)
Definition at line 347 of file open.c.
References log.
Referenced by get_serve_range(), and serve_record_body_accounting().