nginx-xrootd: src/fs/path/path.h File Reference
path.h File Reference
#include "core/ngx_brix_module.h"
#include <dirent.h>
#include "protocols/root/path/opaque_validate.h"
Data Structures
struct brix_authdb_query_t
Functions
size_t brix_sanitize_log_string (const char *in, char *out, size_t outsz)
ngx_int_t brix_normalize_policy_path (ngx_pool_t *pool, const ngx_str_t *src, ngx_str_t *dst)
ngx_array_t * brix_merge_arrays (ngx_conf_t *cf, ngx_array_t *parent, ngx_array_t *child, size_t element_size)
ngx_int_t brix_finalize_vo_rules (ngx_log_t *log, const ngx_str_t *root, ngx_array_t *rules)
ngx_int_t brix_finalize_authdb_rules (ngx_log_t *log, const ngx_str_t *root, ngx_array_t *rules)
ngx_int_t brix_finalize_group_rules (ngx_log_t *log, const ngx_str_t *root, ngx_array_t *rules)
const brix_vo_rule_t * brix_find_vo_rule (const char *resolved_path, ngx_array_t *rules)
const brix_authdb_rule_t * brix_find_authdb_rule (const char *resolved_path, ngx_array_t *rules, brix_ctx_t *ctx, uint32_t needed_privs)
const brix_authdb_rule_t * brix_find_authdb_rule_identity (const char *resolved_path, ngx_array_t *rules, const brix_identity_t *identity, const char *peer_ip, uint32_t needed_privs)
const brix_group_rule_t * brix_find_group_rule (const char *resolved_path, ngx_array_t *rules)
ngx_flag_t brix_vo_list_contains (const char *vo_list, const char *required_vo)
ngx_int_t brix_check_vo_acl (ngx_log_t *log, const char *resolved_path, ngx_array_t *vo_rules, const char *vo_list)
ngx_int_t brix_check_vo_acl_identity (ngx_log_t *log, const char *resolved_path, ngx_array_t *vo_rules, const brix_identity_t *identity)
ngx_int_t brix_check_authdb (brix_ctx_t *ctx, const char *resolved_path, uint32_t needed_privs)
ngx_int_t brix_check_authdb_identity (ngx_log_t *log, const brix_authdb_query_t *query)
ngx_int_t brix_parse_authdb (ngx_conf_t *cf, ngx_str_t *filename, ngx_array_t *rules)
ngx_int_t brix_apply_parent_group_policy_fd (ngx_log_t *log, int fd, const char *path, ngx_array_t *rules)
ngx_int_t brix_apply_parent_group_policy_path (ngx_log_t *log, const char *path, ngx_array_t *rules)
int brix_resolve_path_noexist (ngx_log_t *log, const ngx_str_t *root, const char *reqpath, char *resolved, size_t resolvsz)
int brix_open_confined (ngx_log_t *log, const ngx_str_t *root, const char *resolved, int flags, mode_t mode)
int brix_open_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, int flags, mode_t mode)
int brix_unlink_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, int is_dir)
int brix_mkdir_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, mode_t mode)
int brix_rename_confined_canon (ngx_log_t *log, const char *root_canon, const char *src_resolved, const char *dst_resolved)
int brix_rename_confined_canon_excl (ngx_log_t *log, const char *root_canon, const char *src_resolved, const char *dst_resolved)
int brix_link_confined_canon (ngx_log_t *log, const char *root_canon, const char *src_resolved, const char *dst_resolved)
int brix_setattr_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, int set_times, const struct timespec times[2], int set_owner, uid_t uid, gid_t gid)
int brix_symlink_confined_canon (ngx_log_t *log, const char *root_canon, const char *target, const char *link_resolved)
ssize_t brix_readlink_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, char *buf, size_t bufsz)
int brix_chmod_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, mode_t mode)
int brix_setxattr_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, const char *name, const void *value, size_t len, int flags)
ssize_t brix_getxattr_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, const char *name, void *buf, size_t bufsz)
int brix_removexattr_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, const char *name)
ssize_t brix_listxattr_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, void *buf, size_t bufsz)
ngx_int_t brix_dirlist_access_ok (ngx_log_t *log, const char *root_canon, const char *resolved)
DIR * brix_opendir_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved)
int brix_lstat_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, struct stat *st, int nofollow)
int brix_openat2_runtime_available (void)
int brix_extract_path (ngx_log_t *log, const u_char *payload, size_t payload_len, char *out, size_t outsz, ngx_flag_t strip_cgi)
int brix_mkdir_recursive (const char *path, mode_t mode)
int brix_mkdir_recursive_policy (const char *path, mode_t mode, ngx_log_t *log, ngx_array_t *rules)
int brix_mkdir_recursive_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, mode_t mode, ngx_array_t *rules)
int brix_mkdir_recursive_beneath (ngx_log_t *log, int rootfd, const char *root_canon, const char *resolved, mode_t mode, ngx_array_t *rules)
void brix_strip_cgi (const char *in, char *out, size_t outsz)
ngx_int_t brix_count_path_depth (const char *path)
void brix_make_stat_body (const struct stat *st, ngx_flag_t is_vfs, int extra_flags, char *out, size_t outsz)
void brix_log_access (brix_ctx_t *ctx, ngx_connection_t *c, const char *verb, const char *path, const char *detail, ngx_uint_t xrd_ok, uint16_t errcode, const char *errmsg, size_t bytes)
void brix_access_log_flush (void)
Function Documentation
brix_access_log_flush()
void brix_access_log_flush (void)
Definition at line 55 of file access_log.c.
References brix_alog_buf, brix_alog_fd, and brix_alog_len.
Referenced by brix_on_disconnect(), and brix_sesslog_shutdown_flush().
brix_apply_parent_group_policy_fd()
ngx_int_t brix_apply_parent_group_policy_fd (ngx_log_t * log, int fd, const char * path, ngx_array_t * rules)
Definition at line 279 of file group_policy.c.
References brix_apply_parent_group_policy_impl(), and log.
Referenced by brix_open_finalize_handle().
brix_apply_parent_group_policy_path()
ngx_int_t brix_apply_parent_group_policy_path (ngx_log_t * log, const char * path, ngx_array_t * rules)
Definition at line 287 of file group_policy.c.
References brix_apply_parent_group_policy_impl(), and log.
Referenced by brix_handle_mkdir(), and brix_mkdir_apply_policy().
brix_check_authdb()
ngx_int_t brix_check_authdb (brix_ctx_t * ctx, const char * resolved_path, uint32_t needed_privs)
Definition at line 312 of file authdb.c.
References brix_check_authdb_identity(), brix_ctx_login_t::dn, brix_identity_t::dn, brix_ctx_t::identity, brix_ctx_t::login, ngx_stream_brix_module, brix_ctx_login_t::peer_ip, brix_authdb_query_t::rules, brix_ctx_t::session, brix_identity_t::vo_csv, and brix_ctx_login_t::vo_list.
Referenced by brix_auth_gate_evaluate(), and brix_authz_check().
brix_check_authdb_identity()
ngx_int_t brix_check_authdb_identity (ngx_log_t * log, const brix_authdb_query_t * query)
Definition at line 275 of file authdb.c.
References brix_find_authdb_rule_identity(), brix_identity_dn_cstr(), brix_identity_vo_csv_cstr(), brix_sanitize_log_string(), brix_authdb_query_t::identity, log, brix_authdb_query_t::needed_privs, brix_authdb_query_t::peer_ip, brix_authdb_query_t::resolved_path, and brix_authdb_query_t::rules.
Referenced by access_apply_authdb(), and brix_check_authdb().
brix_check_vo_acl()
ngx_int_t brix_check_vo_acl (ngx_log_t * log, const char * resolved_path, ngx_array_t * vo_rules, const char * vo_list)
Definition at line 60 of file acl.c.
References brix_find_vo_rule(), brix_sanitize_log_string(), brix_vo_list_contains(), log, and brix_vo_rule_t::vo.
Referenced by brix_check_vo_acl_identity().
brix_check_vo_acl_identity()
ngx_int_t brix_check_vo_acl_identity (ngx_log_t * log, const char * resolved_path, ngx_array_t * vo_rules, const brix_identity_t * identity)
Definition at line 94 of file acl.c.
References brix_check_vo_acl(), brix_identity_vo_csv_cstr(), and log.
Referenced by access_apply_authdb(), brix_auth_gate_evaluate(), brix_statx_path_authorized(), prepare_path_authz(), qprep_path_authorized(), and tpc_handle_dest().
brix_chmod_confined_canon()
int brix_chmod_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, mode_t mode)
Definition at line 444 of file resolve_confined_ops.c.
References brix_imp_chmod(), brix_imp_client_active(), brix_open_confined_parent_canon(), brix_resolved_relative_to_root(), close(), log, and PATH_MAX.
Referenced by brix_vfs_chmod(), brix_vfs_setattr(), and sd_posix_setattr().
brix_count_path_depth()
ngx_int_t brix_count_path_depth (const char * path)
Definition at line 92 of file helpers.c.
References BRIX_MAX_WALK_DEPTH.
Referenced by brix_http_resolve_path_ex(), brix_open_precheck(), brix_path_resolve_beneath(), brix_validate_components_cstr(), locate_resolve_reqpath(), and tpc_handle_dest().
brix_dirlist_access_ok()
ngx_int_t brix_dirlist_access_ok (ngx_log_t * log, const char * root_canon, const char * resolved)
Definition at line 47 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_enabled(), brix_imp_open(), brix_resolved_relative_to_root(), close(), log, and PATH_MAX.
Referenced by propfind_walk(), s3_walk_run(), and webdav_search_walk().
brix_extract_path()
int brix_extract_path (ngx_log_t * log, const u_char * payload, size_t payload_len, char * out, size_t outsz, ngx_flag_t strip_cgi)
Definition at line 12 of file extract.c.
References BRIX_MAX_PATH, log, and ngx_memcpy.
Referenced by brix_dirlist_parse_request(), brix_handle_link(), brix_handle_open(), brix_handle_setattr(), brix_handle_symlink(), brix_open_precheck(), brix_prepare_check_path(), brix_qcksum_resolve(), brix_query_ckscan(), brix_query_opaquf(), brix_query_xattr(), brix_resolve_op_path(), brix_upstream_start_snapshot_request(), fattr_path_target(), locate_resolve_reqpath(), manager_redirect_mutation(), mv_parse_paths(), qprep_emit_all(), stat_query_path(), and tpc_handle_dest().
brix_finalize_authdb_rules()
ngx_int_t brix_finalize_authdb_rules (ngx_log_t * log, const ngx_str_t * root, ngx_array_t * rules)
Definition at line 15 of file authdb_parse.c.
References brix_finalize_path_rules(), and log.
Referenced by brix_config_finalize_policy(), and webdav_finalize_authz_rules().
brix_finalize_group_rules()
ngx_int_t brix_finalize_group_rules (ngx_log_t * log, const ngx_str_t * root, ngx_array_t * rules)
Definition at line 18 of file group_policy.c.
References brix_finalize_path_rules(), and log.
Referenced by brix_config_finalize_policy().
brix_finalize_vo_rules()
ngx_int_t brix_finalize_vo_rules (ngx_log_t * log, const ngx_str_t * root, ngx_array_t * rules)
Definition at line 11 of file acl.c.
References brix_finalize_path_rules(), and log.
Referenced by brix_config_finalize_policy(), and webdav_finalize_authz_rules().
brix_find_authdb_rule()
const brix_authdb_rule_t * brix_find_authdb_rule (const char * resolved_path, ngx_array_t * rules, brix_ctx_t * ctx, uint32_t needed_privs)
Definition at line 245 of file authdb.c.
References brix_find_authdb_rule_identity(), brix_ctx_login_t::dn, brix_identity_t::dn, brix_ctx_t::identity, brix_ctx_t::login, brix_ctx_login_t::peer_ip, brix_identity_t::vo_csv, and brix_ctx_login_t::vo_list.
brix_find_authdb_rule_identity()
const brix_authdb_rule_t * brix_find_authdb_rule_identity (const char * resolved_path, ngx_array_t * rules, const brix_identity_t * identity, const char * peer_ip, uint32_t needed_privs)
Definition at line 196 of file authdb.c.
References adb_identity_matches(), brix_identity_dn_cstr(), brix_identity_vo_csv_cstr(), and brix_path_prefix_match().
Referenced by brix_check_authdb_identity(), and brix_find_authdb_rule().
brix_find_group_rule()
const brix_group_rule_t * brix_find_group_rule (const char * resolved_path, ngx_array_t * rules)
Definition at line 118 of file find_rule.c.
References brix_find_longest_rule().
Referenced by brix_apply_parent_group_policy_impl().
brix_find_vo_rule()
const brix_vo_rule_t * brix_find_vo_rule (const char * resolved_path, ngx_array_t * rules)
Definition at line 105 of file find_rule.c.
References brix_find_longest_rule().
Referenced by brix_check_vo_acl().
brix_getxattr_confined_canon()
ssize_t brix_getxattr_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, const char * name, void * buf, size_t bufsz)
Definition at line 597 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_getxattr(), brix_resolved_relative_to_root(), log, name, and PATH_MAX.
Referenced by brix_vfs_getxattr(), and sd_posix_getxattr().
brix_link_confined_canon()
int brix_link_confined_canon (ngx_log_t * log, const char * root_canon, const char * src_resolved, const char * dst_resolved)
Definition at line 341 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_link(), brix_open_confined_parent_canon(), brix_resolved_relative_to_root(), close(), log, and PATH_MAX.
Referenced by brix_handle_link(), tpc_marker_commit_pull(), tpc_thread_pull_commit(), and webdav_tpc_commit_pulled_file().
brix_listxattr_confined_canon()
ssize_t brix_listxattr_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, void * buf, size_t bufsz)
Definition at line 629 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_listxattr(), brix_resolved_relative_to_root(), log, and PATH_MAX.
Referenced by brix_vfs_listxattr(), and sd_posix_listxattr().
brix_log_access()
void brix_log_access (brix_ctx_t * ctx, ngx_connection_t * c, const char * verb, const char * path, const char * detail, ngx_uint_t xrd_ok, uint16_t errcode, const char * errmsg, size_t bytes)
Definition at line 586 of file access_log.c.
References brix_alog_record_t::authmethod, brix_access_format_line(), brix_access_format_time(), brix_access_maybe_sesslog(), brix_access_resolve_identity(), brix_access_sanitize_fields(), brix_alog_emit(), brix_str_cbuf(), brix_alog_record_t::bytes, c, brix_access_raw_t::client_ip, brix_alog_record_t::duration_ms, ngx_stream_brix_module, brix_ctx_t::req_start, brix_ctx_t::session, brix_alog_record_t::timebuf, brix_access_event_t::verb, and brix_alog_record_t::xrd_ok.
Referenced by brix_auth_gate_deny(), brix_auth_gate_op(), brix_cache_fill_composed_done(), brix_cache_fill_done(), brix_ckscan_aio_done(), brix_ckscan_sync(), brix_cksum_aio_done(), brix_close_log_access(), brix_compressed_account(), brix_dirlist_aio_done(), brix_dirlist_check_redirect(), brix_dirlist_send_final(), brix_disconnect_log_open_files(), brix_handle_bind(), brix_handle_locate(), brix_handle_prepare(), brix_handle_readlink(), brix_handle_sigver(), brix_handle_stat(), brix_handle_statx(), brix_handle_token_auth(), brix_handle_truncate(), brix_handle_writev(), brix_login_respond_anon(), brix_login_respond_authenticated(), brix_on_disconnect(), brix_open_map_open_error(), brix_open_mode_guard(), brix_open_read_resolve(), brix_open_residency_gate(), brix_open_send_response(), brix_open_stage_backpressure(), brix_pgread_aio_done(), brix_pgread_send_response(), brix_prepare_handle_cancel(), brix_prepare_send_fail(), brix_qcksum_compute_sync(), brix_qcksum_manager_bounce(), brix_qcksum_open(), brix_query_cksum_handle(), brix_query_finfo(), brix_query_fsinfo(), brix_query_prep_status(), brix_query_space(), brix_query_stats(), brix_query_xattr(), brix_read_serve_sendfile(), brix_readv_execute_sync(), brix_reject_bound_nonread_file_op(), brix_reject_dotdot_path(), brix_resolve_op_path(), brix_staged_append(), brix_tpc_prepare_pull(), brix_tpc_start_pull(), brix_write_aio_log(), brix_write_compressed(), brix_write_require_pgwrite(), brix_writev_write_aio_done(), ckp_query(), ckp_xeq_pgwrite(), ckp_xeq_pgwrite_drain(), ckp_xeq_writev(), gsi_cert_deny(), locate_check_data_server(), locate_try_manager(), locate_try_manager_map(), mv_fail(), pgwrite_execute_sync(), pgwrite_parse_validate(), pgwrite_register_bad_pages(), prepare_dispatch_special(), read_finish_buffered(), read_serve_windowed(), read_validate_req(), stat_manager_route(), tokenauth_extract(), tpc_done_reply_open(), tpc_done_reply_sync(), tpc_done_sync_fail(), tpc_handle_dest(), tpc_prepare_check_preconditions(), writev_reply(), zip_open_error(), and zip_send_open_reply().
brix_lstat_confined_canon()
int brix_lstat_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, struct stat * st, int nofollow)
Definition at line 712 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_stat(), brix_lstat_beneath(), brix_open_root_fd(), brix_resolved_relative_to_root(), brix_stat_beneath(), close(), log, and PATH_MAX.
Referenced by brix_vfs_copy_ns_bytes(), brix_vfs_copyfile(), brix_vfs_probe(), brix_vfs_staged_commit(), brix_vfs_stat_impl(), vfs_copytree_entry(), and vfs_readdir_stat_child().
brix_make_stat_body()
void brix_make_stat_body (const struct stat * st, ngx_flag_t is_vfs, int extra_flags, char * out, size_t outsz)
Definition at line 17 of file stat_body.c.
References brix_stat_flags_from_stat(), brix_statline_format(), and kXR_readable.
Referenced by brix_dirlist_entry_meta(), brix_handle_stat(), brix_vfs_io_dirlist_stat_entry(), and stat_manager_route().
brix_merge_arrays()
ngx_array_t * brix_merge_arrays (ngx_conf_t * cf, ngx_array_t * parent, ngx_array_t * child, size_t element_size)
Definition at line 10 of file merge.c.
References ngx_memcpy.
Referenced by brix_merge_srv_rules(), and brix_merge_srv_writethrough().
brix_mkdir_confined_canon()
int brix_mkdir_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, mode_t mode)
Definition at line 217 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_mkdir(), brix_open_confined_parent_canon(), brix_resolved_relative_to_root(), close(), log, and PATH_MAX.
Referenced by brix_mkdir_level_confined(), brix_vfs_mkdir_path(), s3_handle_multipart_initiate(), and vfs_copytree_subdir().
brix_mkdir_recursive()
int brix_mkdir_recursive (const char * path, mode_t mode)
Definition at line 286 of file mkdir.c.
References brix_mkdir_recursive_policy().
Referenced by brix_cache_ensure_parent(), brix_storage_backend_posix_root(), brix_tier_default_stage_store(), and brix_vfs_backend_register_http_upstream().
brix_mkdir_recursive_beneath()
int brix_mkdir_recursive_beneath (ngx_log_t * log, int rootfd, const char * root_canon, const char * resolved, mode_t mode, ngx_array_t * rules)
Definition at line 369 of file mkdir.c.
References brix_mkdir_confined_start(), brix_mkdir_copy_tmp(), brix_mkdir_level_beneath(), brix_mkdir_walk(), log, and PATH_MAX.
Referenced by brix_ns_mkdir(), and cms_posix_apply().
brix_mkdir_recursive_confined_canon()
int brix_mkdir_recursive_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, mode_t mode, ngx_array_t * rules)
Definition at line 330 of file mkdir.c.
References brix_mkdir_confined_start(), brix_mkdir_copy_tmp(), brix_mkdir_level_confined(), brix_mkdir_walk(), log, and PATH_MAX.
Referenced by brix_vfs_mkdir_parent_path().
brix_mkdir_recursive_policy()
int brix_mkdir_recursive_policy (const char * path, mode_t mode, ngx_log_t * log, ngx_array_t * rules)
Definition at line 300 of file mkdir.c.
References brix_mkdir_copy_tmp(), brix_mkdir_level_plain(), brix_mkdir_walk(), log, and PATH_MAX.
Referenced by brix_mkdir_recursive(), brix_open_write_resolve(), mv_make_dst_parents(), and tpc_handle_dest().
brix_normalize_policy_path()
ngx_int_t brix_normalize_policy_path (ngx_pool_t * pool, const ngx_str_t * src, ngx_str_t * dst)
Definition at line 19 of file normalize.c.
References brix_path_component_forbidden(), BRIX_PNALLOC_OR_RETURN, and ngx_memcpy.
Referenced by brix_conf_set_inherit_parent_group(), brix_conf_set_manager_map(), brix_conf_set_require_vo(), and webdav_conf_require_vo().
brix_open_confined()
int brix_open_confined (ngx_log_t * log, const ngx_str_t * root, const char * resolved, int flags, mode_t mode)
Definition at line 168 of file resolve_confined_ops.c.
References brix_get_canonical_root(), brix_open_confined_canon(), log, and PATH_MAX.
Referenced by brix_query_adler32_file(), brix_query_crc32_file(), and brix_query_digest_file().
brix_open_confined_canon()
int brix_open_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, int flags, mode_t mode)
Definition at line 95 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_open(), brix_open_confined_parent_fallback(), brix_open_root_fd(), brix_resolved_relative_to_root(), brix_split_relative_parent(), close(), log, openat(), and PATH_MAX.
Referenced by brix_vfs_copyfile(), brix_vfs_open_confined_fd(), and brix_vfs_open_fd().
brix_openat2_runtime_available()
int brix_openat2_runtime_available (void)
Definition at line 197 of file resolve_confined_helpers.c.
References close(), and O_PATH.
Referenced by brix_warn_openat2_unavailable().
brix_opendir_confined_canon()
DIR * brix_opendir_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved)
Definition at line 661 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_open(), brix_open_root_fd(), brix_opendir_beneath(), brix_resolved_relative_to_root(), close(), log, and PATH_MAX.
Referenced by brix_fs_remove_tree_at(), vfs_copytree_run(), and vfs_dir_open_confined().
brix_parse_authdb()
ngx_int_t brix_parse_authdb (ngx_conf_t * cf, ngx_str_t * filename, ngx_array_t * rules)
Definition at line 266 of file authdb_parse.c.
References adb_append(), adb_read_file(), adb_tokenize_line(), ngx_stream_brix_module, and adb_line_t::valid.
Referenced by brix_conf_set_authdb(), and webdav_conf_authdb().
brix_readlink_confined_canon()
ssize_t brix_readlink_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, char * buf, size_t bufsz)
Definition at line 528 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_readlink(), brix_open_confined_parent_canon(), brix_resolved_relative_to_root(), close(), log, and PATH_MAX.
Referenced by brix_handle_readlink().
brix_removexattr_confined_canon()
int brix_removexattr_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, const char * name)
Definition at line 613 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_removexattr(), brix_resolved_relative_to_root(), log, name, and PATH_MAX.
Referenced by brix_vfs_removexattr(), and sd_posix_removexattr().
brix_rename_confined_canon()
int brix_rename_confined_canon (ngx_log_t * log, const char * root_canon, const char * src_resolved, const char * dst_resolved)
Definition at line 323 of file resolve_confined_ops.c.
References log, and rename_confined_canon_impl().
Referenced by s3_mpu_assemble(), tpc_marker_commit_pull(), tpc_thread_pull_commit(), and webdav_copy_collection_commit().
brix_rename_confined_canon_excl()
int brix_rename_confined_canon_excl (ngx_log_t * log, const char * root_canon, const char * src_resolved, const char * dst_resolved)
Definition at line 331 of file resolve_confined_ops.c.
References log, and rename_confined_canon_impl().
brix_resolve_path_noexist()
int brix_resolve_path_noexist (ngx_log_t * log, const ngx_str_t * root, const char * reqpath, char * resolved, size_t resolvsz)
Definition at line 52 of file resolve_path_variants.c.
References brix_path_opts_t::allow_missing_parents, brix_resolve_with_opts(), brix_path_opts_t::is_write_operation, and log.
Referenced by brix_finalize_path_rules().
brix_sanitize_log_string()
size_t brix_sanitize_log_string (const char * in, char * out, size_t outsz)
Definition at line 46 of file helpers.c.
brix_setattr_confined_canon()
int brix_setattr_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, int set_times, const struct timespec times[2], int set_owner, uid_t uid, gid_t gid)
Definition at line 395 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_setattr(), brix_open_confined_parent_canon(), brix_resolved_relative_to_root(), close(), log, and PATH_MAX.
Referenced by brix_vfs_setattr(), and sd_posix_setattr().
brix_setxattr_confined_canon()
int brix_setxattr_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, const char * name, const void * value, size_t len, int flags)
Definition at line 580 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_setxattr(), brix_resolved_relative_to_root(), log, name, and PATH_MAX.
Referenced by brix_vfs_setxattr(), and sd_posix_setxattr().
brix_strip_cgi()
void brix_strip_cgi (const char * in, char * out, size_t outsz)
Definition at line 31 of file strip_cgi.c.
brix_symlink_confined_canon()
int brix_symlink_confined_canon (ngx_log_t * log, const char * root_canon, const char * target, const char * link_resolved)
Definition at line 489 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_symlink(), brix_open_confined_parent_canon(), brix_resolved_relative_to_root(), close(), log, and PATH_MAX.
Referenced by brix_handle_symlink().
brix_unlink_confined_canon()
int brix_unlink_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, int is_dir)
Definition at line 185 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_unlink(), brix_open_confined_parent_canon(), brix_resolved_relative_to_root(), close(), log, and PATH_MAX.
Referenced by brix_vfs_unlink_path(), tpc_marker_commit_pull(), tpc_marker_settle_temp(), tpc_thread_pull_commit(), and tpc_thread_pull_fetch().
brix_vo_list_contains()
ngx_flag_t brix_vo_list_contains (const char * vo_list, const char * required_vo)
Definition at line 22 of file acl.c.
Referenced by adb_group_matches(), brix_append_vo_token(), and brix_check_vo_acl().