nginx-xrootd: src/fs/path/helpers.c File Reference
helpers.c File Reference
#include "core/ngx_brix_module.h"
#include "core/compat/hex.h"
#include "path_internal.h"
Functions
int brix_path_component_forbidden (const char *comp, size_t comp_len)
int brix_path_has_dotdot (const char *path)
size_t brix_sanitize_log_string (const char *in, char *out, size_t outsz)
ngx_int_t brix_count_path_depth (const char *path)
ngx_int_t brix_finalize_path_rules (ngx_log_t *log, const ngx_str_t *root, ngx_array_t *rules, size_t element_size, size_t path_offset, size_t resolved_offset, size_t resolved_size)
Function Documentation
brix_count_path_depth()
ngx_int_t brix_count_path_depth (const char * path)
Definition at line 92 of file helpers.c.
References BRIX_MAX_WALK_DEPTH.
Referenced by brix_http_resolve_path_ex(), brix_open_precheck(), brix_path_resolve_beneath(), brix_validate_components_cstr(), locate_resolve_reqpath(), and tpc_handle_dest().
brix_finalize_path_rules()
ngx_int_t brix_finalize_path_rules (ngx_log_t * log, const ngx_str_t * root, ngx_array_t * rules, size_t element_size, size_t path_offset, size_t resolved_offset, size_t resolved_size)
Definition at line 122 of file helpers.c.
References brix_get_canonical_root(), brix_resolve_path_noexist(), log, and PATH_MAX.
Referenced by brix_finalize_authdb_rules(), brix_finalize_group_rules(), and brix_finalize_vo_rules().
brix_path_component_forbidden()
int brix_path_component_forbidden (const char * comp, size_t comp_len)
Definition at line 10 of file helpers.c.
Referenced by brix_normalize_policy_path(), brix_op_path_forbidden_component(), brix_open_confined_parent_fallback(), and brix_validate_components_cstr().
brix_path_has_dotdot()
int brix_path_has_dotdot (const char * path)
Definition at line 17 of file helpers.c.
Referenced by brix_reject_dotdot_path().
brix_sanitize_log_string()
size_t brix_sanitize_log_string (const char * in, char * out, size_t outsz)
Definition at line 46 of file helpers.c.
References brix_hex_nibble().
Referenced by brix_access_sanitize_fields(), brix_check_authdb_identity(), brix_check_vo_acl(), brix_checksum_log_read_error(), brix_cms_srv_verify_xauth(), brix_dirlist_entry_skip(), brix_gsi_complete_auth(), brix_handle_host_auth(), brix_log_path_warning(), brix_log_safe_path(), brix_login_precheck_and_parse(), brix_open_decide_writethrough(), brix_open_finalize_handle(), brix_query_adler32_file(), brix_query_crc32_file(), brix_query_digest_file(), brix_relay_guard_handshake(), brix_relay_guard_sink(), brix_sess_sanitize_ngx(), brix_unix_finalize(), brix_xfer_ledger_record(), cms_wake_pending_session(), cvmfs_finalize_trace(), cvmfs_gate_cas(), cvmfs_guard_emit(), cvmfs_reject(), delegation_put_take_key(), delegation_validate_and_store(), gsi_auth_route_credtype(), gsi_cert_extract_voms(), ngx_http_brix_guard_build_request(), s3o_trace(), sd_cache_guard_tamper(), sd_http_log_key(), sss_reply(), STACK_OF(), webdav_finish_verified_cert(), xrdhttp_add_checksum_header(), and xrdhttp_log_client_identity().