nginx-xrootd: src/fs/path/unified_internal.h File Reference
unified_internal.h File Reference
#include "core/ngx_brix_module.h"
#include "unified.h"
Data Structures
struct brix_resolve_ctx_t
struct brix_candidate_out_t
Functions
void brix_path_warn (ngx_log_t *log, const char *prefix, const char *path)
brix_path_status_t brix_copy_cstr (char *dst, size_t dstsz, const char *src)
brix_path_status_t brix_validate_components_cstr (ngx_log_t *log, const char *path)
ngx_flag_t brix_has_trailing_slash_cstr (const char *path)
brix_path_status_t brix_build_candidate (const char *root_canon, const char *req_path, brix_path_opts_t opts, brix_candidate_out_t *out)
brix_path_status_t brix_finish_resolved (const brix_resolve_ctx_t *ctx, const char *resolved_path, brix_path_opts_t opts)
brix_path_status_t brix_resolve_missing_tail (const brix_resolve_ctx_t *ctx, const char *candidate)
brix_path_status_t brix_resolve_missing_parents (const brix_resolve_ctx_t *ctx, const char *candidate)
Function Documentation
brix_build_candidate()
brix_path_status_t brix_build_candidate (const char * root_canon, const char * req_path, brix_path_opts_t opts, brix_candidate_out_t * out)
Definition at line 266 of file unified_build.c.
References brix_path_opts_t::allow_root, brix_candidate_append_req(), brix_candidate_init_root(), brix_count_components_cstr(), BRIX_PATH_STATUS_INVALID, BRIX_PATH_STATUS_OK, brix_candidate_out_t::buf, brix_candidate_out_t::bufsz, and brix_candidate_out_t::depth_out.
Referenced by brix_path_resolve_cstr().
brix_copy_cstr()
brix_path_status_t brix_copy_cstr (char * dst, size_t dstsz, const char * src)
Definition at line 125 of file unified_build.c.
References BRIX_PATH_STATUS_ERROR, BRIX_PATH_STATUS_OK, BRIX_PATH_STATUS_TOO_LONG, and ngx_memcpy.
Referenced by brix_finish_resolved().
brix_finish_resolved()
brix_path_status_t brix_finish_resolved (const brix_resolve_ctx_t * ctx, const char * resolved_path, brix_path_opts_t opts)
Definition at line 65 of file unified_resolve.c.
References brix_path_opts_t::allow_missing_parents, brix_path_opts_t::allow_missing_tail, brix_copy_cstr(), BRIX_PATH_STATUS_ERROR, BRIX_PATH_STATUS_INVALID, BRIX_PATH_STATUS_OK, BRIX_PATH_TYPE_NOT_FOUND, brix_path_warn(), brix_path_within_root(), brix_stat_type_cstr(), brix_path_result_t::depth, brix_resolve_ctx_t::depth, brix_path_result_t::is_confined, brix_resolve_ctx_t::log, brix_path_opts_t::require_directory, brix_path_result_t::resolved, brix_resolve_ctx_t::resolved, brix_resolve_ctx_t::resolvsz, brix_resolve_ctx_t::result, brix_resolve_ctx_t::root_canon, and brix_path_result_t::type.
Referenced by brix_path_resolve_cstr(), brix_resolve_missing_parents(), and brix_resolve_missing_tail().
brix_has_trailing_slash_cstr()
ngx_flag_t brix_has_trailing_slash_cstr (const char * path)
Definition at line 112 of file unified_build.c.
Referenced by brix_path_resolve_cstr().
brix_path_warn()
void brix_path_warn (ngx_log_t * log, const char * prefix, const char * path)
Definition at line 65 of file unified.c.
References brix_log_path_warning(), and log.
Referenced by brix_finish_resolved(), brix_resolve_missing_parents(), brix_resolve_missing_tail(), and brix_validate_components_cstr().
brix_resolve_missing_parents()
brix_path_status_t brix_resolve_missing_parents (const brix_resolve_ctx_t * ctx, const char * candidate)
Definition at line 255 of file unified_resolve.c.
References brix_path_opts_t::allow_missing_parents, brix_finish_resolved(), BRIX_PATH_STATUS_INVALID, BRIX_PATH_STATUS_OK, BRIX_PATH_STATUS_TOO_LONG, brix_path_warn(), brix_path_within_root(), brix_walk_to_existing_ancestor(), brix_resolve_ctx_t::log, ngx_memcpy, PATH_MAX, and brix_resolve_ctx_t::root_canon.
Referenced by brix_path_resolve_cstr().
brix_resolve_missing_tail()
brix_path_status_t brix_resolve_missing_tail (const brix_resolve_ctx_t * ctx, const char * candidate)
Definition at line 122 of file unified_resolve.c.
References brix_path_opts_t::allow_missing_tail, brix_finish_resolved(), BRIX_PATH_STATUS_ERROR, BRIX_PATH_STATUS_INVALID, BRIX_PATH_STATUS_NOT_FOUND, BRIX_PATH_STATUS_TOO_LONG, brix_path_warn(), brix_path_within_root(), brix_path_opts_t::is_write_operation, brix_resolve_ctx_t::log, ngx_memcpy, PATH_MAX, and brix_resolve_ctx_t::root_canon.
Referenced by brix_path_resolve_cstr().
brix_validate_components_cstr()
brix_path_status_t brix_validate_components_cstr (ngx_log_t * log, const char * path)
Definition at line 66 of file unified_build.c.
References brix_count_path_depth(), BRIX_MAX_PATH, brix_path_component_forbidden(), BRIX_PATH_STATUS_INVALID, BRIX_PATH_STATUS_OK, BRIX_PATH_STATUS_TOO_LONG, brix_path_warn(), and log.
Referenced by brix_path_resolve_cstr().