nginx-xrootd: src/fs/path/mkdir.c File Reference
mkdir.c File Reference
#include "core/ngx_brix_module.h"
#include <errno.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include "path_internal.h"
Data Structures
struct brix_mkdir_walk_t
Macros
#define BRIX_MKDIR_ERROR (-1)
#define BRIX_MKDIR_CREATED (0)
#define BRIX_MKDIR_EXISTED (1)
Functions
static int brix_mkdir_copy_tmp (char *tmp, const char *src, int *out_len)
static char * brix_mkdir_confined_start (char *tmp, const char *root_canon, size_t root_len)
static int brix_mkdir_apply_policy (const brix_mkdir_walk_t *w, const char *dir, int made)
static int brix_mkdir_one_level (const brix_mkdir_walk_t *w, const char *dir)
static int brix_mkdir_walk (const brix_mkdir_walk_t *w, char *tmp, char *p)
static int brix_mkdir_level_plain (const brix_mkdir_walk_t *w, const char *dir)
static int brix_mkdir_level_confined (const brix_mkdir_walk_t *w, const char *dir)
static int brix_mkdir_level_beneath (const brix_mkdir_walk_t *w, const char *dir)
int brix_mkdir_recursive (const char *path, mode_t mode)
int brix_mkdir_recursive_policy (const char *path, mode_t mode, ngx_log_t *log, ngx_array_t *rules)
int brix_mkdir_recursive_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, mode_t mode, ngx_array_t *rules)
int brix_mkdir_recursive_beneath (ngx_log_t *log, int rootfd, const char *root_canon, const char *resolved, mode_t mode, ngx_array_t *rules)
Macro Definition Documentation
BRIX_MKDIR_CREATED
#define BRIX_MKDIR_CREATED (0)
Definition at line 26 of file mkdir.c.
BRIX_MKDIR_ERROR
#define BRIX_MKDIR_ERROR (-1)
Definition at line 25 of file mkdir.c.
BRIX_MKDIR_EXISTED
#define BRIX_MKDIR_EXISTED (1)
Definition at line 27 of file mkdir.c.
Function Documentation
brix_mkdir_apply_policy()
static int brix_mkdir_apply_policy (const brix_mkdir_walk_t * w, const char * dir, int made) static
Definition at line 143 of file mkdir.c.
References brix_apply_parent_group_policy_path(), and BRIX_MKDIR_CREATED.
Referenced by brix_mkdir_one_level().
brix_mkdir_confined_start()
static char * brix_mkdir_confined_start (char * tmp, const char * root_canon, size_t root_len) static
Definition at line 106 of file mkdir.c.
Referenced by brix_mkdir_recursive_beneath(), and brix_mkdir_recursive_confined_canon().
brix_mkdir_copy_tmp()
static int brix_mkdir_copy_tmp (char * tmp, const char * src, int * out_len) static
Definition at line 71 of file mkdir.c.
References PATH_MAX.
Referenced by brix_mkdir_recursive_beneath(), brix_mkdir_recursive_confined_canon(), and brix_mkdir_recursive_policy().
brix_mkdir_level_beneath()
static int brix_mkdir_level_beneath (const brix_mkdir_walk_t * w, const char * dir) static
Definition at line 269 of file mkdir.c.
References brix_mkdir_beneath(), BRIX_MKDIR_CREATED, BRIX_MKDIR_ERROR, and BRIX_MKDIR_EXISTED.
Referenced by brix_mkdir_recursive_beneath().
brix_mkdir_level_confined()
static int brix_mkdir_level_confined (const brix_mkdir_walk_t * w, const char * dir) static
Definition at line 250 of file mkdir.c.
References brix_mkdir_confined_canon(), BRIX_MKDIR_CREATED, BRIX_MKDIR_ERROR, and BRIX_MKDIR_EXISTED.
Referenced by brix_mkdir_recursive_confined_canon().
brix_mkdir_level_plain()
static int brix_mkdir_level_plain (const brix_mkdir_walk_t * w, const char * dir) static
Definition at line 231 of file mkdir.c.
References BRIX_MKDIR_CREATED, BRIX_MKDIR_ERROR, and BRIX_MKDIR_EXISTED.
Referenced by brix_mkdir_recursive_policy().
brix_mkdir_one_level()
static int brix_mkdir_one_level (const brix_mkdir_walk_t * w, const char * dir) static
Definition at line 177 of file mkdir.c.
References brix_mkdir_apply_policy(), and BRIX_MKDIR_ERROR.
Referenced by brix_mkdir_walk().
brix_mkdir_recursive()
int brix_mkdir_recursive (const char * path, mode_t mode)
Definition at line 286 of file mkdir.c.
References brix_mkdir_recursive_policy().
Referenced by brix_cache_ensure_parent(), brix_storage_backend_posix_root(), brix_tier_default_stage_store(), and brix_vfs_backend_register_http_upstream().
brix_mkdir_recursive_beneath()
int brix_mkdir_recursive_beneath (ngx_log_t * log, int rootfd, const char * root_canon, const char * resolved, mode_t mode, ngx_array_t * rules)
Definition at line 369 of file mkdir.c.
References brix_mkdir_confined_start(), brix_mkdir_copy_tmp(), brix_mkdir_level_beneath(), brix_mkdir_walk(), log, and PATH_MAX.
Referenced by brix_ns_mkdir(), and cms_posix_apply().
brix_mkdir_recursive_confined_canon()
int brix_mkdir_recursive_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, mode_t mode, ngx_array_t * rules)
Definition at line 330 of file mkdir.c.
References brix_mkdir_confined_start(), brix_mkdir_copy_tmp(), brix_mkdir_level_confined(), brix_mkdir_walk(), log, and PATH_MAX.
Referenced by brix_vfs_mkdir_parent_path().
brix_mkdir_recursive_policy()
int brix_mkdir_recursive_policy (const char * path, mode_t mode, ngx_log_t * log, ngx_array_t * rules)
Definition at line 300 of file mkdir.c.
References brix_mkdir_copy_tmp(), brix_mkdir_level_plain(), brix_mkdir_walk(), log, and PATH_MAX.
Referenced by brix_mkdir_recursive(), brix_open_write_resolve(), mv_make_dst_parents(), and tpc_handle_dest().
brix_mkdir_walk()
static int brix_mkdir_walk (const brix_mkdir_walk_t * w, char * tmp, char * p) static
Definition at line 203 of file mkdir.c.
References brix_mkdir_one_level().
Referenced by brix_mkdir_recursive_beneath(), brix_mkdir_recursive_confined_canon(), and brix_mkdir_recursive_policy().