nginx-xrootd: src/fs/cache/thread.c File Reference
thread.c File Reference
#include "cache_internal.h"
#include "cache_storage.h"
#include "net/manager/registry.h"
#include <netinet/in.h>
#include <unistd.h>
Functions
void brix_cache_fill_thread (void *data, ngx_log_t *log)
void brix_cache_fill_done (ngx_event_t *ev)
Function Documentation
brix_cache_fill_done()
void brix_cache_fill_done (ngx_event_t * ev)
Definition at line 67 of file thread.c.
References brix_aio_restore_request(), brix_aio_resume(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OPEN_RD, brix_open_resolved_file(), brix_send_error(), brix_send_redirect(), brix_srv_register(), brix_cache_fill_t::c, c, ngx_stream_brix_srv_conf_t::cache_origin_host, ngx_stream_brix_srv_conf_t::cache_origin_port, brix_cache_fill_t::cache_path, brix_cache_fill_t::clean_path, brix_cache_fill_t::conf, brix_cache_fill_t::ctx, brix_cache_fill_t::err_msg, kXR_ServerError, kXR_Unsupported, ngx_stream_brix_srv_conf_t::manager_mode, brix_cache_fill_t::mode_bits, brix_cache_fill_t::options, brix_cache_fill_t::result, brix_ctx_t::state, brix_cache_fill_t::streamid, brix_cache_fill_t::xrd_error, and XRD_ST_SENDING.
Referenced by brix_cache_open_or_fill().
brix_cache_fill_thread()
void brix_cache_fill_thread (void * data, ngx_log_t * log)
Definition at line 14 of file thread.c.
References brix_cache_ensure_parent(), brix_cache_evict_if_needed(), brix_cache_fetch_origin(), brix_cache_ready(), brix_cache_set_syserror(), brix_cache_wait_or_lock(), brix_cache_fill_t::cache_path, brix_cache_fill_t::conf, brix_cache_fill_t::err_msg, kXR_IOError, brix_cache_fill_t::lock_path, log, brix_cache_fill_t::result, brix_cache_fill_t::sys_errno, and brix_cache_fill_t::xrd_error.
Referenced by brix_cache_open_or_fill().