nginx-xrootd: src/core/types/fs_list.h File Reference
fs_list.h File Reference
Macros
#define BRIX_FS_DRIVER_LIST_CORE(X)
#define BRIX_FS_DRIVER_LIST_CEPH(X)
#define BRIX_FS_DRIVER_LIST_SQLITE(X)
#define BRIX_FS_DRIVER_LIST(X)
#define BRIX_FS_ROW(ID, sym, name, kind) BRIX_FS_ROW_##kind(ID, sym, name)
#define BRIX_FS_SCHEME_LIST(S)
#define BRIX_FS_ROW_ENUM_ID(ID, sym, name, kind) BRIX_FS_ID_##ID,
Enumerations
enum brix_fs_id_t {
BRIX_FS_ID_POSIX , BRIX_FS_ID_BLOCK , BRIX_FS_ID_HTTP , BRIX_FS_ID_XROOT ,
BRIX_FS_ID_CACHE , BRIX_FS_ID_STAGE , BRIX_FS_ID_REMOTE , BRIX_FS_ID_FRM ,
BRIX_FS_ID_COUNT
}
Functions
const char * brix_fs_id_name (int id)
int brix_fs_id_from_name (const char *name)
Macro Definition Documentation
BRIX_FS_DRIVER_LIST
#define BRIX_FS_DRIVER_LIST (X)
Value:
    BRIX_FS_DRIVER_LIST_CORE(X)                                             \
    BRIX_FS_DRIVER_LIST_CEPH(X)                                             \
    BRIX_FS_DRIVER_LIST_SQLITE(X)
Definition at line 84 of file fs_list.h.
BRIX_FS_DRIVER_LIST_CEPH
#define BRIX_FS_DRIVER_LIST_CEPH (X)
Definition at line 74 of file fs_list.h.
BRIX_FS_DRIVER_LIST_CORE
#define BRIX_FS_DRIVER_LIST_CORE (X)
Value:
    X(POSIX,     posix,     "posix",    BACKEND)   /* reference store      */ \
    X(BLOCK,     block,     "block",    BACKEND)   /* fixed-extent blocks  */ \
    X(HTTP,      http,      "http",     ORIGIN)    /* HTTP(S) Stratum/DAV  */ \
    X(XROOT,     xroot,     "xroot",    ORIGIN)    /* root:// origin       */ \
    X(CACHE,     cache,     "cache",    DECORATOR) /* read-through cache   */ \
    X(STAGE,     stage,     "stage",    DECORATOR) /* write-back stage     */ \
    X(REMOTE,    remote,    "remote",   DECORATOR) /* broker/impersonate   */ \
    X(FRM,       frm,       "frm",      NEARLINE)  /* HSM/MSS recall plane */
Definition at line 58 of file fs_list.h.
BRIX_FS_DRIVER_LIST_SQLITE
#define BRIX_FS_DRIVER_LIST_SQLITE (X)
Definition at line 81 of file fs_list.h.
BRIX_FS_ROW
#define BRIX_FS_ROW (ID, sym, name, kind) BRIX_FS_ROW_##kind(ID, sym, name)
Definition at line 91 of file fs_list.h.
BRIX_FS_ROW_ENUM_ID
#define BRIX_FS_ROW_ENUM_ID (ID, sym, name, kind) BRIX_FS_ID_##ID,
Definition at line 122 of file fs_list.h.
BRIX_FS_SCHEME_LIST
#define BRIX_FS_SCHEME_LIST (S)
Value:
    S("posix",  "posix",  0, 0)                                               \
    S("pblock", "pblock", 0, 0)                                               \
    S("root",   "xroot",  0, 0)                                               \
    S("roots",  "xroot",  1, 0)                                               \
    S("http",   "http",   0, 0)                                               \
    S("https",  "http",   1, 0)                                               \
    S("webdav", "http",   0, 0)                                               \
    S("davs",   "http",   1, 0)                                               \
    S("s3",     "s3",     0, 0)                                               \
    S("rados",  "rados",  0, 0)                                               \
    S("ceph",   "ceph",   0, 0)                                               \
    S("tape",   "tape",   0, 1)                                               \
    S("frm",    "frm",    0, 1)
Definition at line 99 of file fs_list.h.
Enumeration Type Documentation
brix_fs_id_t
enum brix_fs_id_t
Enumerator
BRIX_FS_ID_POSIX
BRIX_FS_ID_BLOCK
BRIX_FS_ID_HTTP
BRIX_FS_ID_XROOT
BRIX_FS_ID_CACHE
BRIX_FS_ID_STAGE
BRIX_FS_ID_REMOTE
BRIX_FS_ID_FRM
BRIX_FS_ID_COUNT
Definition at line 121 of file fs_list.h.
Function Documentation
brix_fs_id_from_name()
int brix_fs_id_from_name (const char * name)
Definition at line 38 of file sd_fs_id.c.
References BRIX_FS_ID_COUNT, brix_fs_id_names, and name.
Referenced by brix_metric_backend_bytes().
brix_fs_id_name()
const char * brix_fs_id_name (int id)
Definition at line 28 of file sd_fs_id.c.
References BRIX_FS_ID_COUNT, and brix_fs_id_names.
Referenced by brix_storage_io_bytes_emit(), and dashboard_build_storage_io().