nginx-xrootd: src/core/compat/fs_walk.h File Reference
fs_walk.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <dirent.h>
#include <sys/stat.h>
#include <sys/types.h>
Data Structures
struct brix_fs_walk_entry_t
struct brix_fs_walk_options_t
Macros
#define BRIX_FS_TREE_MAX_DEPTH 512
Typedefs
typedef ngx_int_t(* brix_fs_walk_pt) (const brix_fs_walk_entry_t *entry, void *data)
Functions
ngx_flag_t brix_fs_is_dot_entry (const char *name)
ngx_int_t brix_fs_join_path (const char *dir, const char *name, char *out, size_t outsz)
ngx_int_t brix_fs_dir_is_empty (const char *path, ngx_flag_t *is_empty)
ngx_int_t brix_fs_walk (ngx_log_t *log, const char *start_path, const brix_fs_walk_options_t *opts, brix_fs_walk_pt cb, void *data)
ngx_int_t brix_fs_remove_tree_confined (ngx_log_t *log, const char *root_canon, const char *path)
Macro Definition Documentation
BRIX_FS_TREE_MAX_DEPTH
#define BRIX_FS_TREE_MAX_DEPTH 512
Definition at line 23 of file fs_walk.h.
Typedef Documentation
brix_fs_walk_pt
typedef ngx_int_t(* brix_fs_walk_pt) (const brix_fs_walk_entry_t *entry, void *data)
Definition at line 45 of file fs_walk.h.
Function Documentation
brix_fs_dir_is_empty()
ngx_int_t brix_fs_dir_is_empty (const char * path, ngx_flag_t * is_empty)
Definition at line 83 of file fs_walk.c.
References brix_fs_is_dot_entry().
Referenced by ns_delete_remove().
brix_fs_is_dot_entry()
ngx_flag_t brix_fs_is_dot_entry (const char * name)
Definition at line 36 of file fs_walk.c.
References name.
Referenced by brix_fs_dir_is_empty(), brix_fs_remove_tree_entry(), brix_fs_walk_skip_name(), vfs_copytree_entry(), and vfs_walk_entry().
brix_fs_join_path()
ngx_int_t brix_fs_join_path (const char * dir, const char * name, char * out, size_t outsz)
Definition at line 57 of file fs_walk.c.
References name.
Referenced by brix_fs_remove_tree_entry(), brix_fs_walk_handle_entry(), propfind_walk_emit(), and webdav_search_scan_dir().
brix_fs_remove_tree_confined()
ngx_int_t brix_fs_remove_tree_confined (ngx_log_t * log, const char * root_canon, const char * path)
Definition at line 206 of file fs_walk_remove.c.
References brix_fs_remove_tree_at(), and log.
Referenced by brix_ns_rename(), mpu_rmdir_recursive(), ns_delete_remove(), and webdav_delete_path_recursive().
brix_fs_walk()
ngx_int_t brix_fs_walk (ngx_log_t * log, const char * start_path, const brix_fs_walk_options_t * opts, brix_fs_walk_pt cb, void * data)
Definition at line 353 of file fs_walk.c.
References brix_fs_walk_dir(), and log.
Referenced by webdav_lock_startup_sweep().