nginx-xrootd: src/core/compat/fs_walk.c File Reference
fs_walk.c File Reference
#include "fs_walk.h"
#include <errno.h>
#include <stdio.h>
#include <unistd.h>
Enumerations
enum brix_fs_walk_action_e { BRIX_FS_WALK_CONTINUE = 0 , BRIX_FS_WALK_MARK_ERROR , BRIX_FS_WALK_STOP }
Functions
ngx_flag_t brix_fs_is_dot_entry (const char *name)
ngx_int_t brix_fs_join_path (const char *dir, const char *name, char *out, size_t outsz)
ngx_int_t brix_fs_dir_is_empty (const char *path, ngx_flag_t *is_empty)
static ngx_int_t brix_fs_walk_dir (ngx_log_t *log, const char *dir, const brix_fs_walk_options_t *opts, brix_fs_walk_pt cb, void *data, ngx_uint_t depth)
static ngx_flag_t brix_fs_walk_skip_name (const brix_fs_walk_options_t *opts, const char *name)
static ngx_flag_t brix_fs_walk_cb_wants (const brix_fs_walk_options_t *opts, ngx_flag_t is_dir)
static ngx_flag_t brix_fs_walk_should_recurse (const brix_fs_walk_options_t *opts, ngx_flag_t is_dir, ngx_uint_t depth)
static brix_fs_walk_action_e brix_fs_walk_handle_entry (ngx_log_t *log, const char *dir, const brix_fs_walk_options_t *opts, brix_fs_walk_pt cb, void *data, ngx_uint_t depth, const struct dirent *de)
ngx_int_t brix_fs_walk (ngx_log_t *log, const char *start_path, const brix_fs_walk_options_t *opts, brix_fs_walk_pt cb, void *data)
Enumeration Type Documentation
brix_fs_walk_action_e
enum brix_fs_walk_action_e
Enumerator
BRIX_FS_WALK_CONTINUE
BRIX_FS_WALK_MARK_ERROR
BRIX_FS_WALK_STOP
Definition at line 127 of file fs_walk.c.
Function Documentation
brix_fs_dir_is_empty()
ngx_int_t brix_fs_dir_is_empty (const char * path, ngx_flag_t * is_empty)
Definition at line 83 of file fs_walk.c.
References brix_fs_is_dot_entry().
Referenced by ns_delete_remove().
brix_fs_is_dot_entry()
ngx_flag_t brix_fs_is_dot_entry (const char * name)
Definition at line 36 of file fs_walk.c.
References name.
Referenced by brix_fs_dir_is_empty(), brix_fs_remove_tree_entry(), brix_fs_walk_skip_name(), vfs_copytree_entry(), and vfs_walk_entry().
brix_fs_join_path()
ngx_int_t brix_fs_join_path (const char * dir, const char * name, char * out, size_t outsz)
Definition at line 57 of file fs_walk.c.
References name.
Referenced by brix_fs_remove_tree_entry(), brix_fs_walk_handle_entry(), propfind_walk_emit(), and webdav_search_scan_dir().
brix_fs_walk()
ngx_int_t brix_fs_walk (ngx_log_t * log, const char * start_path, const brix_fs_walk_options_t * opts, brix_fs_walk_pt cb, void * data)
Definition at line 353 of file fs_walk.c.
References brix_fs_walk_dir(), and log.
Referenced by webdav_lock_startup_sweep().
brix_fs_walk_cb_wants()
static ngx_flag_t brix_fs_walk_cb_wants (const brix_fs_walk_options_t * opts, ngx_flag_t is_dir) static
Definition at line 180 of file fs_walk.c.
References brix_fs_walk_options_t::include_dirs, and brix_fs_walk_options_t::include_files.
Referenced by brix_fs_walk_handle_entry().
brix_fs_walk_dir()
static ngx_int_t brix_fs_walk_dir (ngx_log_t * log, const char * dir, const brix_fs_walk_options_t * opts, brix_fs_walk_pt cb, void * data, ngx_uint_t depth) static
Definition at line 303 of file fs_walk.c.
References brix_fs_walk_handle_entry(), BRIX_FS_WALK_MARK_ERROR, BRIX_FS_WALK_STOP, and log.
Referenced by brix_fs_walk(), and brix_fs_walk_handle_entry().
brix_fs_walk_handle_entry()
static brix_fs_walk_action_e brix_fs_walk_handle_entry (ngx_log_t * log, const char * dir, const brix_fs_walk_options_t * opts, brix_fs_walk_pt cb, void * data, ngx_uint_t depth, const struct dirent * de) static
Definition at line 234 of file fs_walk.c.
References brix_fs_join_path(), brix_fs_walk_cb_wants(), BRIX_FS_WALK_CONTINUE, brix_fs_walk_dir(), BRIX_FS_WALK_MARK_ERROR, brix_fs_walk_should_recurse(), brix_fs_walk_skip_name(), BRIX_FS_WALK_STOP, log, lstat(), PATH_MAX, brix_fs_walk_options_t::root_dev, stat(), and brix_fs_walk_options_t::stay_on_device.
Referenced by brix_fs_walk_dir().
brix_fs_walk_should_recurse()
static ngx_flag_t brix_fs_walk_should_recurse (const brix_fs_walk_options_t * opts, ngx_flag_t is_dir, ngx_uint_t depth) static
Definition at line 203 of file fs_walk.c.
References brix_fs_walk_options_t::max_depth.
Referenced by brix_fs_walk_handle_entry().
brix_fs_walk_skip_name()
static ngx_flag_t brix_fs_walk_skip_name (const brix_fs_walk_options_t * opts, const char * name) static
Definition at line 154 of file fs_walk.c.
References brix_fs_is_dot_entry(), name, and brix_fs_walk_options_t::skip_hidden.
Referenced by brix_fs_walk_handle_entry().