nginx-xrootd: src/core/compat/fs_walk_remove.c File Reference
fs_walk_remove.c File Reference
#include "fs_walk.h"
#include "fs/path/path.h"
#include "fs/path/beneath.h"
#include <errno.h>
#include <stdio.h>
#include <unistd.h>
Functions
static ngx_int_t brix_fs_remove_tree_at (ngx_log_t *log, const char *root_canon, const char *path, ngx_uint_t depth)
static ngx_int_t brix_fs_remove_tree_entry (ngx_log_t *log, const char *root_canon, int rootfd, const char *path, const struct dirent *de, ngx_uint_t depth)
ngx_int_t brix_fs_remove_tree_confined (ngx_log_t *log, const char *root_canon, const char *path)
Function Documentation
brix_fs_remove_tree_at()
static ngx_int_t brix_fs_remove_tree_at (ngx_log_t * log, const char * root_canon, const char * path, ngx_uint_t depth) static
Definition at line 121 of file fs_walk_remove.c.
References brix_beneath_open_root(), brix_beneath_strip_root(), brix_fs_remove_tree_entry(), BRIX_FS_TREE_MAX_DEPTH, brix_opendir_confined_canon(), brix_unlink_beneath(), close(), and log.
Referenced by brix_fs_remove_tree_confined(), and brix_fs_remove_tree_entry().
brix_fs_remove_tree_confined()
ngx_int_t brix_fs_remove_tree_confined (ngx_log_t * log, const char * root_canon, const char * path)
Definition at line 206 of file fs_walk_remove.c.
References brix_fs_remove_tree_at(), and log.
Referenced by brix_ns_rename(), mpu_rmdir_recursive(), ns_delete_remove(), and webdav_delete_path_recursive().
brix_fs_remove_tree_entry()
static ngx_int_t brix_fs_remove_tree_entry (ngx_log_t * log, const char * root_canon, int rootfd, const char * path, const struct dirent * de, ngx_uint_t depth) static
Definition at line 57 of file fs_walk_remove.c.
References brix_beneath_strip_root(), brix_fs_is_dot_entry(), brix_fs_join_path(), brix_fs_remove_tree_at(), brix_lstat_beneath(), brix_unlink_beneath(), log, PATH_MAX, and stat().
Referenced by brix_fs_remove_tree_at().