nginx-xrootd: src/protocols/gridftp/ev/ftp_ev_tls.c File Reference
ftp_ev_tls.c File Reference
#include "ftp_ev.h"
#include "protocols/gridftp/ftp_dc_sec.h"
Functions
static void ev_dc_sec_of (ftp_ev_t *fc, brix_ftp_dc_sec_t *sec)
ngx_int_t brix_ftp_ev_tls_verify (ftp_ev_t *fc, ngx_connection_t *c)
ngx_int_t brix_ftp_ev_tls_begin (ftp_ev_t *fc, ngx_connection_t *c, ngx_pool_t **poolp, int tls_client, void(*done)(ngx_connection_t *))
static void ev_dc_tls_done (ngx_connection_t *c)
void brix_ftp_ev_dc_start_tls (ftp_ev_dc_t *dc)
Function Documentation
brix_ftp_ev_dc_start_tls()
void brix_ftp_ev_dc_start_tls (ftp_ev_dc_t * dc)
Definition at line 140 of file ftp_ev_tls.c.
References brix_ftp_ev_data_finish(), brix_ftp_ev_tls_begin(), and ev_dc_tls_done().
Referenced by ev_accept_handler(), and ev_connect_handler().
brix_ftp_ev_tls_begin()
ngx_int_t brix_ftp_ev_tls_begin (ftp_ev_t * fc, ngx_connection_t * c, ngx_pool_t ** poolp, int tls_client, void(*)(ngx_connection_t *) done)
Definition at line 69 of file ftp_ev_tls.c.
References brix_ftp_dc_apply_policy(), brix_ftp_dc_load_deleg(), c, ftp_ev_t::c, ftp_ev_t::conf, ev_dc_sec_of(), and ngx_stream_brix_ftp_srv_conf_t::tls_ctx.
Referenced by brix_ftp_ev_dc_start_tls(), and brix_ftp_ev_eb_accept().
brix_ftp_ev_tls_verify()
ngx_int_t brix_ftp_ev_tls_verify (ftp_ev_t * fc, ngx_connection_t * c)
Definition at line 49 of file ftp_ev_tls.c.
References brix_ftp_dc_gsi_check(), c, ftp_ev_t::c, and ev_dc_sec_of().
Referenced by ev_dc_tls_done(), and ev_eb_child_tls_done().
ev_dc_sec_of()
static void ev_dc_sec_of (ftp_ev_t * fc, brix_ftp_dc_sec_t * sec) static
Definition at line 34 of file ftp_ev_tls.c.
References ftp_ev_t::c, brix_ftp_dc_sec_t::ca_store, ngx_stream_brix_ftp_srv_conf_t::ca_store, ftp_ev_t::conf, ftp_ev_t::ctrl_dn, brix_ftp_dc_sec_t::ctrl_dn, ftp_ev_t::ctrl_leaf_pem, brix_ftp_dc_sec_t::ctrl_leaf_pem, ftp_ev_t::deleg_proxy, brix_ftp_dc_sec_t::deleg_proxy, and brix_ftp_dc_sec_t::log.
Referenced by brix_ftp_ev_tls_begin(), and brix_ftp_ev_tls_verify().
ev_dc_tls_done()
static void ev_dc_tls_done (ngx_connection_t * c) static
Definition at line 124 of file ftp_ev_tls.c.
References brix_ftp_ev_data_finish(), brix_ftp_ev_data_ready(), brix_ftp_ev_tls_verify(), and c.
Referenced by brix_ftp_ev_dc_start_tls().