nginx-xrootd: src/protocols/gridftp/ev/ftp_ev_io.c File Reference
ftp_ev_io.c File Reference
#include "ftp_ev.h"
#include <unistd.h>
Functions
static char * ev_take_line (ftp_ev_t *fc, int *too_long)
ngx_int_t brix_ftp_ev_flush (ftp_ev_t *fc)
void brix_ftp_ev_finalize (ftp_ev_t *fc, ngx_int_t rc)
static void brix_ftp_ev_process (ftp_ev_t *fc)
void brix_ftp_ev_resume (ftp_ev_t *fc)
static void brix_ftp_ev_read_handler (ngx_event_t *rev)
static void brix_ftp_ev_write_handler (ngx_event_t *wev)
void brix_ftp_ev_handler (ngx_stream_session_t *s)
Function Documentation
brix_ftp_ev_finalize()
void brix_ftp_ev_finalize (ftp_ev_t * fc, ngx_int_t rc)
Definition at line 94 of file ftp_ev_io.c.
References ftp_ev_t::c, close(), ftp_ev_t::destroyed, ftp_ev_t::pasv_fd, and ftp_ev_t::s.
Referenced by brix_ftp_ev_handler(), brix_ftp_ev_process(), brix_ftp_ev_read_handler(), and brix_ftp_ev_write_handler().
brix_ftp_ev_flush()
ngx_int_t brix_ftp_ev_flush (ftp_ev_t * fc)
Definition at line 72 of file ftp_ev_io.c.
References c, ftp_ev_t::c, ftp_ev_t::ob, ftp_ev_t::ob_len, and ftp_ev_t::ob_pos.
Referenced by brix_ftp_ev_process(), ev_eb_marker_perf(), and ev_eb_marker_range().
brix_ftp_ev_handler()
void brix_ftp_ev_handler (ngx_stream_session_t * s)
Definition at line 258 of file ftp_ev_io.c.
References ftp_ev_t::allo_size, ngx_stream_brix_ftp_srv_conf_t::allow_write, brix_ftp_ev_finalize(), BRIX_FTP_EV_OB_CAP, brix_ftp_ev_process(), brix_ftp_ev_read_handler(), brix_ftp_ev_reply(), brix_ftp_ev_write_handler(), c, ftp_ev_t::c, ftp_ev_t::conf, ftp_ev_t::cwd, FTP_EV_ST_CMD, ftp_ev_t::greeted, ngx_pcalloc(), ngx_pnalloc(), ngx_stream_brix_ftp_module, ftp_ev_t::ob, ftp_ev_t::pasv_fd, ftp_ev_t::prot, ngx_stream_brix_ftp_srv_conf_t::root_canon, ftp_ev_t::s, s, and ftp_ev_t::state.
Referenced by brix_ftp_install_handler().
brix_ftp_ev_process()
static void brix_ftp_ev_process (ftp_ev_t * fc) static
Definition at line 115 of file ftp_ev_io.c.
References ftp_ev_t::blen, brix_ftp_ev_dispatch(), brix_ftp_ev_finalize(), brix_ftp_ev_flush(), BRIX_FTP_EV_IO_TIMEO, ftp_ev_t::buf, c, ftp_ev_t::c, ev_take_line(), FTP_EV_ST_CLOSING, FTP_EV_ST_XFER, ftp_ev_t::ob_len, ftp_ev_t::ob_pos, and ftp_ev_t::state.
Referenced by brix_ftp_ev_handler(), brix_ftp_ev_read_handler(), brix_ftp_ev_resume(), and brix_ftp_ev_write_handler().
brix_ftp_ev_read_handler()
static void brix_ftp_ev_read_handler (ngx_event_t * rev) static
Definition at line 210 of file ftp_ev_io.c.
References brix_ftp_ev_finalize(), brix_ftp_ev_process(), c, ngx_stream_brix_ftp_module, and s.
Referenced by brix_ftp_ev_handler().
brix_ftp_ev_resume()
void brix_ftp_ev_resume (ftp_ev_t * fc)
Definition at line 199 of file ftp_ev_io.c.
References brix_ftp_ev_process(), and ftp_ev_t::destroyed.
Referenced by brix_ftp_ev_data_finish().
brix_ftp_ev_write_handler()
static void brix_ftp_ev_write_handler (ngx_event_t * wev) static
Definition at line 234 of file ftp_ev_io.c.
References brix_ftp_ev_finalize(), brix_ftp_ev_process(), c, ngx_stream_brix_ftp_module, and s.
Referenced by brix_ftp_ev_handler().
ev_take_line()
static char * ev_take_line (ftp_ev_t * fc, int * too_long) static
Definition at line 32 of file ftp_ev_io.c.
References ftp_ev_t::blen, ftp_ev_t::bpos, and ftp_ev_t::buf.
Referenced by brix_ftp_ev_process().