nginx-xrootd: src/protocols/gridftp/ev/ftp_ev_cmd.c File Reference
ftp_ev_cmd.c File Reference
#include "ftp_ev.h"
#include "fs/vfs/vfs.h"
#include "fs/vfs/vfs_ops.h"
#include "core/compat/checksum_core.h"
#include <openssl/evp.h>
#include <stdio.h>
#include <strings.h>
#include <time.h>
Functions
static size_t ev_fmt_facts (char *out, size_t outsz, const brix_vfs_stat_t *st)
ngx_int_t brix_ftp_ev_cmd_cwd (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_size (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_mkd (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_dele (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_rmd (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_mdtm (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_mlst (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_stat (ftp_ev_t *fc, const char *arg)
static int ev_cksm_kind (const char *algo)
ngx_int_t brix_ftp_ev_cmd_cksm (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_rnfr (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_rnto (ftp_ev_t *fc, const char *arg)
Function Documentation
brix_ftp_ev_cmd_cksm()
ngx_int_t brix_ftp_ev_cmd_cksm (ftp_ev_t * fc, const char * arg)
Definition at line 247 of file ftp_ev_cmd.c.
References BRIX_CK_MD5, BRIX_CK_SHA1, BRIX_CK_SHA256, brix_cksum_digest_obj_range(), brix_cksum_u32_obj_range(), brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), brix_vfs_close(), brix_vfs_file_sd_obj(), BRIX_VFS_O_READ, brix_vfs_open(), ftp_ev_t::c, ev_cksm_kind(), hex(), and PATH_MAX.
Referenced by brix_ftp_ev_dispatch().
brix_ftp_ev_cmd_cwd()
ngx_int_t brix_ftp_ev_cmd_cwd (ftp_ev_t * fc, const char * arg)
Definition at line 52 of file ftp_ev_cmd.c.
References brix_ftp_ev_reply(), brix_ftp_ev_resolve(), ftp_ev_t::conf, ftp_ev_t::cwd, ngx_memcpy, PATH_MAX, and ngx_stream_brix_ftp_srv_conf_t::root_canon.
Referenced by brix_ftp_ev_dispatch().
brix_ftp_ev_cmd_dele()
ngx_int_t brix_ftp_ev_cmd_dele (ftp_ev_t * fc, const char * arg)
Definition at line 116 of file ftp_ev_cmd.c.
References ngx_stream_brix_ftp_srv_conf_t::allow_write, brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), brix_vfs_unlink(), ftp_ev_t::conf, and PATH_MAX.
Referenced by brix_ftp_ev_dispatch().
brix_ftp_ev_cmd_mdtm()
ngx_int_t brix_ftp_ev_cmd_mdtm (ftp_ev_t * fc, const char * arg)
Definition at line 156 of file ftp_ev_cmd.c.
References brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), brix_vfs_stat_t::is_directory, brix_vfs_stat_t::mtime, and PATH_MAX.
Referenced by brix_ftp_ev_dispatch().
brix_ftp_ev_cmd_mkd()
ngx_int_t brix_ftp_ev_cmd_mkd (ftp_ev_t * fc, const char * arg)
Definition at line 96 of file ftp_ev_cmd.c.
References ngx_stream_brix_ftp_srv_conf_t::allow_write, brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), brix_vfs_mkdir(), ftp_ev_t::conf, and PATH_MAX.
Referenced by brix_ftp_ev_dispatch().
brix_ftp_ev_cmd_mlst()
ngx_int_t brix_ftp_ev_cmd_mlst (ftp_ev_t * fc, const char * arg)
Definition at line 183 of file ftp_ev_cmd.c.
References brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), ftp_ev_t::cwd, ev_fmt_facts(), name, and PATH_MAX.
Referenced by brix_ftp_ev_dispatch().
brix_ftp_ev_cmd_rmd()
ngx_int_t brix_ftp_ev_cmd_rmd (ftp_ev_t * fc, const char * arg)
Definition at line 136 of file ftp_ev_cmd.c.
References ngx_stream_brix_ftp_srv_conf_t::allow_write, brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), brix_vfs_rmdir(), ftp_ev_t::conf, and PATH_MAX.
Referenced by brix_ftp_ev_dispatch().
brix_ftp_ev_cmd_rnfr()
ngx_int_t brix_ftp_ev_cmd_rnfr (ftp_ev_t * fc, const char * arg)
Definition at line 317 of file ftp_ev_cmd.c.
References ngx_stream_brix_ftp_srv_conf_t::allow_write, brix_ftp_ev_reply(), brix_ftp_ev_resolve(), ftp_ev_t::conf, ngx_memcpy, PATH_MAX, ftp_ev_t::rnfr, and ftp_ev_t::rnfr_set.
Referenced by brix_ftp_ev_dispatch().
brix_ftp_ev_cmd_rnto()
ngx_int_t brix_ftp_ev_cmd_rnto (ftp_ev_t * fc, const char * arg)
Definition at line 335 of file ftp_ev_cmd.c.
References ngx_stream_brix_ftp_srv_conf_t::allow_write, brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), brix_vfs_rename(), ftp_ev_t::conf, brix_path_result_t::is_confined, PATH_MAX, brix_path_result_t::resolved, ftp_ev_t::rnfr, and ftp_ev_t::rnfr_set.
Referenced by brix_ftp_ev_dispatch().
brix_ftp_ev_cmd_size()
ngx_int_t brix_ftp_ev_cmd_size (ftp_ev_t * fc, const char * arg)
Definition at line 78 of file ftp_ev_cmd.c.
References brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), brix_vfs_stat_t::is_directory, PATH_MAX, and brix_vfs_stat_t::size.
Referenced by brix_ftp_ev_dispatch().
brix_ftp_ev_cmd_stat()
ngx_int_t brix_ftp_ev_cmd_stat (ftp_ev_t * fc, const char * arg)
Definition at line 205 of file ftp_ev_cmd.c.
References brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), ftp_ev_t::cwd, ev_fmt_facts(), PATH_MAX, and ftp_ev_t::type_binary.
Referenced by brix_ftp_ev_dispatch().
ev_cksm_kind()
static int ev_cksm_kind (const char * algo) static
Definition at line 234 of file ftp_ev_cmd.c.
References BRIX_CK_ADLER32, BRIX_CK_CRC32, BRIX_CK_CRC32C, BRIX_CK_MD5, BRIX_CK_SHA1, and BRIX_CK_SHA256.
Referenced by brix_ftp_ev_cmd_cksm().
ev_fmt_facts()
static size_t ev_fmt_facts (char * out, size_t outsz, const brix_vfs_stat_t * st) static
Definition at line 33 of file ftp_ev_cmd.c.
References brix_vfs_stat_t::is_directory, brix_vfs_stat_t::mtime, and brix_vfs_stat_t::size.
Referenced by brix_ftp_ev_cmd_mlst(), and brix_ftp_ev_cmd_stat().