nginx-xrootd: src/protocols/gridftp/ev/ftp_ev.h File Reference
ftp_ev.h File Reference
#include "protocols/gridftp/ftp_gateway.h"
#include "protocols/gridftp/ftp_eblock.h"
#include "core/types/identity.h"
#include "auth/gssapi/gsi_mech.h"
#include <netinet/in.h>
Data Structures
struct ftp_ev_t
struct ftp_ev_dc_t
Macros
#define BRIX_FTP_EV_CMD_MAX (128 * 1024) /* inbound command / ADAT line cap */
#define BRIX_FTP_EV_OB_CAP (64 * 1024) /* outbound reply buffer (per conn) */
#define BRIX_FTP_EV_LINE_MAX 2048 /* fixed-buffer reply formatting */
#define BRIX_FTP_EV_IO_TIMEO 30000 /* ms: idle control-channel deadline */
#define BRIX_FTP_EV_XFER_BUF (64 * 1024) /* data-channel transfer chunk */
#define BRIX_FTP_EV_DATA_BACKLOG 64 /* passive listen backlog (MODE E) */
#define BRIX_FTP_EV_EB_MAX_CONNS 64 /* MODE E: concurrent passive streams */
#define BRIX_FTP_EV_EB_MAX_RANGES 8192 /* MODE E: committed-range table cap */
Enumerations
enum { FTP_EV_LS_NLST = 0 , FTP_EV_LS_LONG , FTP_EV_LS_MLSD }
enum ftp_ev_state_e { FTP_EV_ST_CMD = 0 , FTP_EV_ST_XFER , FTP_EV_ST_CLOSING }
enum {
FTP_EV_OP_RETR = 0 , FTP_EV_OP_STOR , FTP_EV_OP_LIST , FTP_EV_OP_NLST ,
FTP_EV_OP_MLSD , FTP_EV_OP_APPE
}
Functions
void brix_ftp_ev_handler (ngx_stream_session_t *s)
void brix_ftp_ev_finalize (ftp_ev_t *fc, ngx_int_t rc)
void brix_ftp_ev_resume (ftp_ev_t *fc)
ngx_int_t brix_ftp_ev_flush (ftp_ev_t *fc)
ngx_int_t brix_ftp_ev_reply (ftp_ev_t *fc, const char *fmt,...)
ngx_int_t brix_ftp_ev_send_adat (ftp_ev_t *fc, int code, ngx_str_t *tok)
ngx_int_t brix_ftp_ev_b64_decode (ngx_pool_t *pool, const char *b64, ngx_str_t *out)
char * brix_ftp_ev_split (char *line, char **verb_out)
int brix_ftp_ev_resolve (ftp_ev_t *fc, const char *arg, char *abs, size_t abssz)
void brix_ftp_ev_vfs_ctx (ftp_ev_t *fc, const char *abs, void *vctx)
ngx_int_t brix_ftp_ev_dispatch (ftp_ev_t *fc, char *line)
ngx_int_t brix_ftp_ev_cmd_cwd (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_size (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_mkd (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_dele (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_rmd (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_mdtm (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_mlst (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_stat (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_cksm (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_rnfr (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_rnto (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_auth (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_adat (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_protected (ftp_ev_t *fc, const char *code, const char *arg)
ngx_int_t brix_ftp_ev_do_transfer (ftp_ev_t *fc, int kind, const char *arg)
ngx_int_t brix_ftp_ev_data_setup (ftp_ev_t *fc, int kind, const char *arg)
ngx_int_t brix_ftp_ev_data_open (ftp_ev_dc_t *dc)
void brix_ftp_ev_data_finish (ftp_ev_dc_t *dc, ngx_int_t rc)
ngx_connection_t * brix_ftp_ev_wrap_conn (ftp_ev_t *fc, int fd)
void brix_ftp_ev_data_ready (ftp_ev_dc_t *dc)
void brix_ftp_ev_dc_start_tls (ftp_ev_dc_t *dc)
ngx_int_t brix_ftp_ev_tls_begin (ftp_ev_t *fc, ngx_connection_t *c, ngx_pool_t **poolp, int tls_client, void(*done)(ngx_connection_t *))
ngx_int_t brix_ftp_ev_tls_verify (ftp_ev_t *fc, ngx_connection_t *c)
void brix_ftp_ev_retr_mode_e_start (ftp_ev_dc_t *dc)
void brix_ftp_ev_eb_accept (ngx_event_t *rev)
void brix_ftp_ev_eb_teardown (ftp_ev_dc_t *dc)
Macro Definition Documentation
BRIX_FTP_EV_CMD_MAX
#define BRIX_FTP_EV_CMD_MAX (128 * 1024) /* inbound command / ADAT line cap */
Definition at line 41 of file ftp_ev.h.
BRIX_FTP_EV_DATA_BACKLOG
#define BRIX_FTP_EV_DATA_BACKLOG 64 /* passive listen backlog (MODE E) */
Definition at line 46 of file ftp_ev.h.
BRIX_FTP_EV_EB_MAX_CONNS
#define BRIX_FTP_EV_EB_MAX_CONNS 64 /* MODE E: concurrent passive streams */
Definition at line 47 of file ftp_ev.h.
BRIX_FTP_EV_EB_MAX_RANGES
#define BRIX_FTP_EV_EB_MAX_RANGES 8192 /* MODE E: committed-range table cap */
Definition at line 48 of file ftp_ev.h.
BRIX_FTP_EV_IO_TIMEO
#define BRIX_FTP_EV_IO_TIMEO 30000 /* ms: idle control-channel deadline */
Definition at line 44 of file ftp_ev.h.
BRIX_FTP_EV_LINE_MAX
#define BRIX_FTP_EV_LINE_MAX 2048 /* fixed-buffer reply formatting */
Definition at line 43 of file ftp_ev.h.
BRIX_FTP_EV_OB_CAP
#define BRIX_FTP_EV_OB_CAP (64 * 1024) /* outbound reply buffer (per conn) */
Definition at line 42 of file ftp_ev.h.
BRIX_FTP_EV_XFER_BUF
#define BRIX_FTP_EV_XFER_BUF (64 * 1024) /* data-channel transfer chunk */
Definition at line 45 of file ftp_ev.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FTP_EV_LS_NLST
FTP_EV_LS_LONG
FTP_EV_LS_MLSD
Definition at line 53 of file ftp_ev.h.
anonymous enum
anonymous enum
Enumerator
FTP_EV_OP_RETR
FTP_EV_OP_STOR
FTP_EV_OP_LIST
FTP_EV_OP_NLST
FTP_EV_OP_MLSD
FTP_EV_OP_APPE
Definition at line 131 of file ftp_ev.h.
ftp_ev_state_e
enum ftp_ev_state_e
Enumerator
FTP_EV_ST_CMD
FTP_EV_ST_XFER
FTP_EV_ST_CLOSING
Definition at line 67 of file ftp_ev.h.
Function Documentation
brix_ftp_ev_b64_decode()
ngx_int_t brix_ftp_ev_b64_decode (ngx_pool_t * pool, const char * b64, ngx_str_t * out)
Definition at line 60 of file ftp_ev_reply.c.
References b64, and ngx_pnalloc().
Referenced by brix_ftp_ev_cmd_adat(), and brix_ftp_ev_cmd_protected().
brix_ftp_ev_cmd_adat()
ngx_int_t brix_ftp_ev_cmd_adat (ftp_ev_t * fc, const char * arg)
Definition at line 101 of file ftp_ev_sec.c.
References brix_ftp_ev_b64_decode(), brix_ftp_ev_reply(), brix_ftp_ev_send_adat(), BRIX_GSS_CONTINUE, BRIX_GSS_FAILED, brix_gssapi_srv_step(), ftp_ev_t::c, ev_gss_finalize(), ftp_ev_t::gss, and tok.
Referenced by ev_grp_security().
brix_ftp_ev_cmd_auth()
ngx_int_t brix_ftp_ev_cmd_auth (ftp_ev_t * fc, const char * arg)
Definition at line 74 of file ftp_ev_sec.c.
References brix_ftp_ev_reply(), brix_gssapi_srv_create(), ftp_ev_t::c, ngx_stream_brix_ftp_srv_conf_t::ca_store, ftp_ev_t::conf, ngx_stream_brix_ftp_srv_conf_t::gsi, ftp_ev_t::gss, and ngx_stream_brix_ftp_srv_conf_t::tls_ctx.
Referenced by ev_grp_security().
brix_ftp_ev_cmd_cksm()
ngx_int_t brix_ftp_ev_cmd_cksm (ftp_ev_t * fc, const char * arg)
Definition at line 247 of file ftp_ev_cmd.c.
References BRIX_CK_MD5, BRIX_CK_SHA1, BRIX_CK_SHA256, brix_cksum_digest_obj_range(), brix_cksum_u32_obj_range(), brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), brix_vfs_close(), brix_vfs_file_sd_obj(), BRIX_VFS_O_READ, brix_vfs_open(), ftp_ev_t::c, ev_cksm_kind(), hex(), and PATH_MAX.
Referenced by ev_grp_namespace().
brix_ftp_ev_cmd_cwd()
ngx_int_t brix_ftp_ev_cmd_cwd (ftp_ev_t * fc, const char * arg)
Definition at line 52 of file ftp_ev_cmd.c.
References brix_ftp_ev_reply(), brix_ftp_ev_resolve(), ftp_ev_t::conf, ftp_ev_t::cwd, ngx_memcpy, PATH_MAX, and ngx_stream_brix_ftp_srv_conf_t::root_canon.
Referenced by ev_grp_navigation().
brix_ftp_ev_cmd_dele()
ngx_int_t brix_ftp_ev_cmd_dele (ftp_ev_t * fc, const char * arg)
Definition at line 116 of file ftp_ev_cmd.c.
References ngx_stream_brix_ftp_srv_conf_t::allow_write, brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), brix_vfs_unlink(), ftp_ev_t::conf, and PATH_MAX.
Referenced by ev_grp_namespace().
brix_ftp_ev_cmd_mdtm()
ngx_int_t brix_ftp_ev_cmd_mdtm (ftp_ev_t * fc, const char * arg)
Definition at line 156 of file ftp_ev_cmd.c.
References brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), brix_vfs_stat_t::is_directory, brix_vfs_stat_t::mtime, and PATH_MAX.
Referenced by ev_grp_namespace().
brix_ftp_ev_cmd_mkd()
ngx_int_t brix_ftp_ev_cmd_mkd (ftp_ev_t * fc, const char * arg)
Definition at line 96 of file ftp_ev_cmd.c.
References ngx_stream_brix_ftp_srv_conf_t::allow_write, brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), brix_vfs_mkdir(), ftp_ev_t::conf, and PATH_MAX.
Referenced by ev_grp_namespace().
brix_ftp_ev_cmd_mlst()
ngx_int_t brix_ftp_ev_cmd_mlst (ftp_ev_t * fc, const char * arg)
Definition at line 183 of file ftp_ev_cmd.c.
References brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), ftp_ev_t::cwd, ev_fmt_facts(), name, and PATH_MAX.
Referenced by ev_grp_namespace().
brix_ftp_ev_cmd_protected()
ngx_int_t brix_ftp_ev_cmd_protected (ftp_ev_t * fc, const char * code, const char * arg)
Definition at line 141 of file ftp_ev_sec.c.
References brix_ftp_ev_b64_decode(), BRIX_FTP_EV_CMD_MAX, brix_ftp_ev_dispatch(), brix_ftp_ev_reply(), brix_gssapi_unwrap(), ftp_ev_t::c, code, ftp_ev_t::gss, ngx_memcpy, ngx_pnalloc(), ftp_ev_t::sec_active, tok, and ftp_ev_t::wrap_code.
Referenced by ev_grp_security().
brix_ftp_ev_cmd_rmd()
ngx_int_t brix_ftp_ev_cmd_rmd (ftp_ev_t * fc, const char * arg)
Definition at line 136 of file ftp_ev_cmd.c.
References ngx_stream_brix_ftp_srv_conf_t::allow_write, brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), brix_vfs_rmdir(), ftp_ev_t::conf, and PATH_MAX.
Referenced by ev_grp_namespace().
brix_ftp_ev_cmd_rnfr()
ngx_int_t brix_ftp_ev_cmd_rnfr (ftp_ev_t * fc, const char * arg)
Definition at line 317 of file ftp_ev_cmd.c.
References ngx_stream_brix_ftp_srv_conf_t::allow_write, brix_ftp_ev_reply(), brix_ftp_ev_resolve(), ftp_ev_t::conf, ngx_memcpy, PATH_MAX, ftp_ev_t::rnfr, and ftp_ev_t::rnfr_set.
Referenced by ev_grp_namespace().
brix_ftp_ev_cmd_rnto()
ngx_int_t brix_ftp_ev_cmd_rnto (ftp_ev_t * fc, const char * arg)
Definition at line 335 of file ftp_ev_cmd.c.
References ngx_stream_brix_ftp_srv_conf_t::allow_write, brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), brix_vfs_rename(), ftp_ev_t::conf, brix_path_result_t::is_confined, PATH_MAX, brix_path_result_t::resolved, ftp_ev_t::rnfr, and ftp_ev_t::rnfr_set.
Referenced by ev_grp_namespace().
brix_ftp_ev_cmd_size()
ngx_int_t brix_ftp_ev_cmd_size (ftp_ev_t * fc, const char * arg)
Definition at line 78 of file ftp_ev_cmd.c.
References brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), brix_vfs_stat_t::is_directory, PATH_MAX, and brix_vfs_stat_t::size.
Referenced by ev_grp_namespace().
brix_ftp_ev_cmd_stat()
ngx_int_t brix_ftp_ev_cmd_stat (ftp_ev_t * fc, const char * arg)
Definition at line 205 of file ftp_ev_cmd.c.
References brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), ftp_ev_t::cwd, ev_fmt_facts(), PATH_MAX, and ftp_ev_t::type_binary.
Referenced by ev_grp_namespace().
brix_ftp_ev_data_finish()
void brix_ftp_ev_data_finish (ftp_ev_dc_t * dc, ngx_int_t rc)
Definition at line 478 of file ftp_ev_data.c.
References brix_ftp_ev_eb_teardown(), brix_ftp_ev_reply(), brix_ftp_ev_resume(), brix_vfs_close(), brix_vfs_closedir(), brix_vfs_writer_abort(), ftp_ev_t::c, ftp_ev_t::dc, FTP_EV_ST_CMD, ftp_ev_t::pasv_fd, and ftp_ev_t::state.
Referenced by brix_ftp_ev_data_ready(), brix_ftp_ev_dc_start_tls(), brix_ftp_ev_eb_accept(), ev_accept_handler(), ev_connect_handler(), ev_dc_tls_done(), ev_eb_child_done(), ev_eb_child_read(), ev_eb_child_tls_done(), ev_eb_drain_payload(), ev_eb_recv_header(), ev_eb_reserve_range(), ev_list_write(), ev_retr_mode_e_write(), ev_retr_write(), and ev_stor_read().
brix_ftp_ev_data_open()
ngx_int_t brix_ftp_ev_data_open (ftp_ev_dc_t * dc)
Definition at line 382 of file ftp_ev_data.c.
References ftp_ev_t::active, ftp_ev_t::active_sa, brix_ftp_ev_eb_accept(), BRIX_FTP_EV_IO_TIMEO, brix_ftp_ev_wrap_conn(), ftp_ev_t::c, close(), ev_accept_handler(), ev_connect_handler(), and ftp_ev_t::pasv_fd.
Referenced by ev_begin_transfer().
brix_ftp_ev_data_ready()
void brix_ftp_ev_data_ready (ftp_ev_dc_t * dc)
Definition at line 268 of file ftp_ev_xfer.c.
References brix_ftp_ev_data_finish(), brix_ftp_ev_retr_mode_e_start(), brix_ftp_ev_vfs_ctx(), brix_vfs_file_size(), BRIX_VFS_O_READ, brix_vfs_open(), brix_vfs_opendir(), brix_vfs_writer_open(), ev_data_idle(), ev_list_write(), ev_retr_write(), ev_stor_read(), FTP_EV_OP_APPE, FTP_EV_OP_RETR, and FTP_EV_OP_STOR.
Referenced by ev_accept_handler(), ev_connect_handler(), and ev_dc_tls_done().
brix_ftp_ev_data_setup()
ngx_int_t brix_ftp_ev_data_setup (ftp_ev_t * fc, int kind, const char * arg)
Definition at line 248 of file ftp_ev_data.c.
References ev_do_pasv(), and ev_do_port().
Referenced by brix_ftp_ev_do_transfer().
brix_ftp_ev_dc_start_tls()
void brix_ftp_ev_dc_start_tls (ftp_ev_dc_t * dc)
Definition at line 140 of file ftp_ev_tls.c.
References brix_ftp_ev_data_finish(), brix_ftp_ev_tls_begin(), and ev_dc_tls_done().
Referenced by ev_accept_handler(), and ev_connect_handler().
brix_ftp_ev_dispatch()
ngx_int_t brix_ftp_ev_dispatch (ftp_ev_t * fc, char * line)
Definition at line 388 of file ftp_ev_dispatch.c.
References ftp_ev_t::authed, brix_ftp_ev_reply(), brix_ftp_ev_split(), ev_grp_ctl(), ev_grp_dcprot(), ev_grp_login(), ev_grp_namespace(), ev_grp_navigation(), ev_grp_security(), ev_grp_session(), ev_grp_transfer(), ev_grp_xferparam(), and ev_verb_preauth().
Referenced by brix_ftp_ev_cmd_protected(), and brix_ftp_ev_process().
brix_ftp_ev_do_transfer()
ngx_int_t brix_ftp_ev_do_transfer (ftp_ev_t * fc, int kind, const char * arg)
Definition at line 482 of file ftp_ev_xfer.c.
References brix_ftp_ev_data_setup(), and ev_begin_transfer().
Referenced by ev_grp_transfer().
brix_ftp_ev_eb_accept()
void brix_ftp_ev_eb_accept (ngx_event_t * rev)
Definition at line 470 of file ftp_ev_mode_e_recv.c.
References brix_ftp_ev_data_finish(), BRIX_FTP_EV_EB_MAX_CONNS, BRIX_FTP_EV_IO_TIMEO, brix_ftp_ev_tls_begin(), brix_ftp_ev_wrap_conn(), c, ftp_ev_t::c, ftp_ev_eb_conn_t::c, close(), ftp_ev_eb_conn_t::dc, ev_eb_arm_read(), ev_eb_child_read(), ev_eb_child_tls_done(), ev_eb_receiver_open(), ev_eb_slot(), ftp_ev_eb_conn_t::in_use, ftp_ev_eb_conn_t::pool, and ftp_ev_t::prot.
Referenced by brix_ftp_ev_data_open().
brix_ftp_ev_eb_teardown()
void brix_ftp_ev_eb_teardown (ftp_ev_dc_t * dc)
Definition at line 128 of file ftp_ev_mode_e_recv.c.
References BRIX_FTP_EV_EB_MAX_CONNS, conns, ev_eb_child_close(), and in_use.
Referenced by brix_ftp_ev_data_finish().
brix_ftp_ev_finalize()
void brix_ftp_ev_finalize (ftp_ev_t * fc, ngx_int_t rc)
Definition at line 94 of file ftp_ev_io.c.
References ftp_ev_t::c, close(), ftp_ev_t::destroyed, ftp_ev_t::pasv_fd, and ftp_ev_t::s.
Referenced by brix_ftp_ev_handler(), brix_ftp_ev_process(), brix_ftp_ev_read_handler(), and brix_ftp_ev_write_handler().
brix_ftp_ev_flush()
ngx_int_t brix_ftp_ev_flush (ftp_ev_t * fc)
Definition at line 72 of file ftp_ev_io.c.
References c, ftp_ev_t::c, ftp_ev_t::ob, ftp_ev_t::ob_len, and ftp_ev_t::ob_pos.
Referenced by brix_ftp_ev_process(), ev_eb_marker_perf(), and ev_eb_marker_range().
brix_ftp_ev_handler()
void brix_ftp_ev_handler (ngx_stream_session_t * s)
Definition at line 258 of file ftp_ev_io.c.
References ftp_ev_t::allo_size, ngx_stream_brix_ftp_srv_conf_t::allow_write, brix_ftp_ev_finalize(), BRIX_FTP_EV_OB_CAP, brix_ftp_ev_process(), brix_ftp_ev_read_handler(), brix_ftp_ev_reply(), brix_ftp_ev_write_handler(), c, ftp_ev_t::c, ftp_ev_t::conf, ftp_ev_t::cwd, FTP_EV_ST_CMD, ftp_ev_t::greeted, ngx_pcalloc(), ngx_pnalloc(), ngx_stream_brix_ftp_module, ftp_ev_t::ob, ftp_ev_t::pasv_fd, ftp_ev_t::prot, ngx_stream_brix_ftp_srv_conf_t::root_canon, ftp_ev_t::s, s, and ftp_ev_t::state.
Referenced by brix_ftp_install_handler().
brix_ftp_ev_reply()
ngx_int_t brix_ftp_ev_reply (ftp_ev_t * fc, const char * fmt, ...)
Definition at line 100 of file ftp_ev_reply.c.
References BRIX_FTP_EV_LINE_MAX, ev_out_put(), ev_reply_wrapped(), and ftp_ev_t::sec_active.
Referenced by brix_ftp_ev_cmd_adat(), brix_ftp_ev_cmd_auth(), brix_ftp_ev_cmd_cksm(), brix_ftp_ev_cmd_cwd(), brix_ftp_ev_cmd_dele(), brix_ftp_ev_cmd_mdtm(), brix_ftp_ev_cmd_mkd(), brix_ftp_ev_cmd_mlst(), brix_ftp_ev_cmd_protected(), brix_ftp_ev_cmd_rmd(), brix_ftp_ev_cmd_rnfr(), brix_ftp_ev_cmd_rnto(), brix_ftp_ev_cmd_size(), brix_ftp_ev_cmd_stat(), brix_ftp_ev_data_finish(), brix_ftp_ev_dispatch(), brix_ftp_ev_handler(), ev_begin_transfer(), ev_cmd_allo(), ev_cmd_cdup(), ev_cmd_dcau(), ev_cmd_feat(), ev_cmd_mode(), ev_cmd_opts(), ev_cmd_prot(), ev_cmd_rest(), ev_do_pasv(), ev_do_port(), ev_eb_marker_perf(), ev_eb_marker_range(), ev_grp_ctl(), ev_grp_dcprot(), ev_grp_login(), ev_grp_navigation(), ev_grp_session(), ev_grp_xferparam(), ev_xfer_guards(), and ev_xfer_resolve_start().
brix_ftp_ev_resolve()
int brix_ftp_ev_resolve (ftp_ev_t * fc, const char * arg, char * abs, size_t abssz)
Definition at line 53 of file ftp_ev_path.c.
References brix_http_resolve_path(), ftp_ev_t::conf, ftp_ev_t::cwd, ngx_memcpy, PATH_MAX, and ngx_stream_brix_ftp_srv_conf_t::root_canon.
Referenced by brix_ftp_ev_cmd_cksm(), brix_ftp_ev_cmd_cwd(), brix_ftp_ev_cmd_dele(), brix_ftp_ev_cmd_mdtm(), brix_ftp_ev_cmd_mkd(), brix_ftp_ev_cmd_mlst(), brix_ftp_ev_cmd_rmd(), brix_ftp_ev_cmd_rnfr(), brix_ftp_ev_cmd_rnto(), brix_ftp_ev_cmd_size(), brix_ftp_ev_cmd_stat(), and ev_xfer_resolve_start().
brix_ftp_ev_resume()
void brix_ftp_ev_resume (ftp_ev_t * fc)
Definition at line 199 of file ftp_ev_io.c.
References brix_ftp_ev_process(), and ftp_ev_t::destroyed.
Referenced by brix_ftp_ev_data_finish().
brix_ftp_ev_retr_mode_e_start()
void brix_ftp_ev_retr_mode_e_start (ftp_ev_dc_t * dc)
Definition at line 134 of file ftp_ev_mode_e.c.
References ev_eb_send_idle(), and ev_retr_mode_e_write().
Referenced by brix_ftp_ev_data_ready().
brix_ftp_ev_send_adat()
ngx_int_t brix_ftp_ev_send_adat (ftp_ev_t * fc, int code, ngx_str_t * tok)
Definition at line 121 of file ftp_ev_reply.c.
References b64, ftp_ev_t::c, code, ev_b64_encode(), ev_out_put(), ngx_pnalloc(), and tok.
Referenced by brix_ftp_ev_cmd_adat().
brix_ftp_ev_split()
char * brix_ftp_ev_split (char * line, char ** verb_out)
Definition at line 35 of file ftp_ev_path.c.
Referenced by brix_ftp_ev_dispatch().
brix_ftp_ev_tls_begin()
ngx_int_t brix_ftp_ev_tls_begin (ftp_ev_t * fc, ngx_connection_t * c, ngx_pool_t ** poolp, int tls_client, void(*)(ngx_connection_t *) done)
Definition at line 69 of file ftp_ev_tls.c.
References brix_ftp_dc_apply_policy(), brix_ftp_dc_load_deleg(), c, ftp_ev_t::c, ftp_ev_t::conf, ev_dc_sec_of(), and ngx_stream_brix_ftp_srv_conf_t::tls_ctx.
Referenced by brix_ftp_ev_dc_start_tls(), and brix_ftp_ev_eb_accept().
brix_ftp_ev_tls_verify()
ngx_int_t brix_ftp_ev_tls_verify (ftp_ev_t * fc, ngx_connection_t * c)
Definition at line 49 of file ftp_ev_tls.c.
References brix_ftp_dc_gsi_check(), c, ftp_ev_t::c, and ev_dc_sec_of().
Referenced by ev_dc_tls_done(), and ev_eb_child_tls_done().
brix_ftp_ev_vfs_ctx()
void brix_ftp_ev_vfs_ctx (ftp_ev_t * fc, const char * abs, void * vctx)
Definition at line 298 of file ftp_ev_path.c.
References ngx_stream_brix_ftp_srv_conf_t::allow_write, BRIX_CRED_SELECT, brix_ftp_ev_forward_pem(), BRIX_PROTO_ROOT, brix_vfs_backend_accepts_proxy(), brix_vfs_ctx_init(), brix_vfs_deleg_bind(), ftp_ev_t::c, ftp_ev_t::conf, ftp_ev_t::ctrl_leaf_pem, ngx_stream_brix_ftp_srv_conf_t::deleg_mode, ftp_ev_t::deleg_proxy, ftp_ev_t::identity, ngx_stream_brix_ftp_srv_conf_t::root_canon, and ftp_ev_t::sec_active.
Referenced by brix_ftp_ev_cmd_cksm(), brix_ftp_ev_cmd_dele(), brix_ftp_ev_cmd_mdtm(), brix_ftp_ev_cmd_mkd(), brix_ftp_ev_cmd_mlst(), brix_ftp_ev_cmd_rmd(), brix_ftp_ev_cmd_rnto(), brix_ftp_ev_cmd_size(), brix_ftp_ev_cmd_stat(), brix_ftp_ev_data_ready(), ev_eb_child_done(), ev_eb_receiver_open(), and ev_xfer_resolve_start().
brix_ftp_ev_wrap_conn()
ngx_connection_t * brix_ftp_ev_wrap_conn (ftp_ev_t * fc, int fd)
Definition at line 265 of file ftp_ev_data.c.
References c, and ftp_ev_t::c.
Referenced by brix_ftp_ev_data_open(), brix_ftp_ev_eb_accept(), and ev_accept_handler().