nginx-xrootd: src/protocols/gridftp/ftp_dc_sec.h File Reference
ftp_dc_sec.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <openssl/ssl.h>
#include <openssl/x509.h>
Data Structures
struct brix_ftp_dc_sec_t
Functions
ngx_int_t brix_ftp_dc_load_deleg (const brix_ftp_dc_sec_t *sec, SSL *ssl)
void brix_ftp_dc_apply_policy (SSL *ssl)
ngx_int_t brix_ftp_dc_gsi_check (const brix_ftp_dc_sec_t *sec, SSL *ssl)
Function Documentation
brix_ftp_dc_apply_policy()
void brix_ftp_dc_apply_policy (SSL * ssl)
Definition at line 113 of file ftp_dc_sec.c.
References brix_ftp_dc_verify_cb().
Referenced by brix_ftp_ev_tls_begin().
brix_ftp_dc_gsi_check()
ngx_int_t brix_ftp_dc_gsi_check (const brix_ftp_dc_sec_t * sec, SSL * ssl)
Definition at line 166 of file ftp_dc_sec.c.
References brix_ftp_dc_dn_matches(), brix_gsi_verify_chain(), brix_ftp_dc_sec_t::ca_store, brix_ftp_dc_sec_t::ctrl_dn, brix_gsi_verify_result_t::dn_buf, brix_ftp_dc_sec_t::log, and STACK_OF().
Referenced by brix_ftp_ev_tls_verify().
brix_ftp_dc_load_deleg()
ngx_int_t brix_ftp_dc_load_deleg (const brix_ftp_dc_sec_t * sec, SSL * ssl)
Definition at line 30 of file ftp_dc_sec.c.
References brix_ftp_dc_sec_t::ctrl_leaf_pem, brix_ftp_dc_sec_t::deleg_proxy, key, and brix_ftp_dc_sec_t::log.
Referenced by brix_ftp_ev_tls_begin().