nginx-xrootd: src/protocols/gridftp/ev/ftp_ev_data.c File Reference
ftp_ev_data.c File Reference
#include "ftp_ev.h"
#include "fs/vfs/vfs.h"
#include "fs/vfs/vfs_ops.h"
#include "core/compat/net_target.h"
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
Functions
static ngx_int_t ev_do_pasv (ftp_ev_t *fc, int extended)
static ngx_int_t ev_do_port (ftp_ev_t *fc, const char *arg, int extended)
ngx_int_t brix_ftp_ev_data_setup (ftp_ev_t *fc, int kind, const char *arg)
ngx_connection_t * brix_ftp_ev_wrap_conn (ftp_ev_t *fc, int fd)
static void ev_accept_handler (ngx_event_t *rev)
static void ev_connect_handler (ngx_event_t *wev)
ngx_int_t brix_ftp_ev_data_open (ftp_ev_dc_t *dc)
void brix_ftp_ev_data_finish (ftp_ev_dc_t *dc, ngx_int_t rc)
Function Documentation
brix_ftp_ev_data_finish()
void brix_ftp_ev_data_finish (ftp_ev_dc_t * dc, ngx_int_t rc)
Definition at line 478 of file ftp_ev_data.c.
References brix_ftp_ev_eb_teardown(), brix_ftp_ev_reply(), brix_ftp_ev_resume(), brix_vfs_close(), brix_vfs_closedir(), brix_vfs_writer_abort(), ftp_ev_t::c, ftp_ev_t::dc, FTP_EV_ST_CMD, ftp_ev_t::pasv_fd, and ftp_ev_t::state.
Referenced by brix_ftp_ev_data_ready(), brix_ftp_ev_dc_start_tls(), brix_ftp_ev_eb_accept(), ev_accept_handler(), ev_connect_handler(), ev_dc_tls_done(), ev_eb_child_done(), ev_eb_child_read(), ev_eb_child_tls_done(), ev_eb_drain_payload(), ev_eb_recv_header(), ev_eb_reserve_range(), ev_list_write(), ev_retr_mode_e_write(), ev_retr_write(), and ev_stor_read().
brix_ftp_ev_data_open()
ngx_int_t brix_ftp_ev_data_open (ftp_ev_dc_t * dc)
Definition at line 382 of file ftp_ev_data.c.
References ftp_ev_t::active, ftp_ev_t::active_sa, brix_ftp_ev_eb_accept(), BRIX_FTP_EV_IO_TIMEO, brix_ftp_ev_wrap_conn(), ftp_ev_t::c, close(), ev_accept_handler(), ev_connect_handler(), and ftp_ev_t::pasv_fd.
Referenced by ev_begin_transfer().
brix_ftp_ev_data_setup()
ngx_int_t brix_ftp_ev_data_setup (ftp_ev_t * fc, int kind, const char * arg)
Definition at line 248 of file ftp_ev_data.c.
References ev_do_pasv(), and ev_do_port().
Referenced by brix_ftp_ev_do_transfer().
brix_ftp_ev_wrap_conn()
ngx_connection_t * brix_ftp_ev_wrap_conn (ftp_ev_t * fc, int fd)
Definition at line 265 of file ftp_ev_data.c.
References c, and ftp_ev_t::c.
Referenced by brix_ftp_ev_data_open(), brix_ftp_ev_eb_accept(), and ev_accept_handler().
ev_accept_handler()
static void ev_accept_handler (ngx_event_t * rev) static
Definition at line 286 of file ftp_ev_data.c.
References brix_ftp_ev_data_finish(), brix_ftp_ev_data_ready(), brix_ftp_ev_dc_start_tls(), brix_ftp_ev_wrap_conn(), ftp_ev_t::c, close(), ftp_ev_t::pasv_fd, and ftp_ev_t::prot.
Referenced by brix_ftp_ev_data_open().
ev_connect_handler()
static void ev_connect_handler (ngx_event_t * wev) static
Definition at line 343 of file ftp_ev_data.c.
References brix_ftp_ev_data_finish(), brix_ftp_ev_data_ready(), brix_ftp_ev_dc_start_tls(), c, ftp_ev_t::c, and ftp_ev_t::prot.
Referenced by brix_ftp_ev_data_open().
ev_do_pasv()
static ngx_int_t ev_do_pasv (ftp_ev_t * fc, int extended) static
Definition at line 48 of file ftp_ev_data.c.
References ftp_ev_t::active, BRIX_FTP_EV_DATA_BACKLOG, brix_ftp_ev_reply(), ftp_ev_t::c, close(), ftp_ev_t::conf, ngx_memcpy, ftp_ev_t::pasv_fd, ngx_stream_brix_ftp_srv_conf_t::pasv_port_hi, ngx_stream_brix_ftp_srv_conf_t::pasv_port_lo, and port.
Referenced by brix_ftp_ev_data_setup().
ev_do_port()
static ngx_int_t ev_do_port (ftp_ev_t * fc, const char * arg, int extended) static
Definition at line 149 of file ftp_ev_data.c.
References ftp_ev_t::active, ftp_ev_t::active_offpeer, ftp_ev_t::active_sa, brix_ftp_ev_reply(), brix_net_target_check_addr(), ftp_ev_t::c, close(), ftp_ev_t::dcau_a, ngx_memcpy, ftp_ev_t::pasv_fd, port, and ftp_ev_t::sec_active.
Referenced by brix_ftp_ev_data_setup().