nginx-xrootd: src/protocols/gridftp/ftp_module_gsi.c File Reference
ftp_module_gsi.c File Reference
#include "ftp_gateway.h"
#include "ftp_module_internal.h"
#include "auth/crypto/pki_build.h"
#include <sys/stat.h>
#include <openssl/ssl.h>
Functions
static void brix_ftp_ssl_ctx_cleanup (void *data)
char * brix_ftp_build_gsi (ngx_conf_t *cf, ngx_stream_brix_ftp_srv_conf_t *conf)
Function Documentation
brix_ftp_build_gsi()
char * brix_ftp_build_gsi (ngx_conf_t * cf, ngx_stream_brix_ftp_srv_conf_t * conf)
Definition at line 38 of file ftp_module_gsi.c.
References brix_build_ca_store_cached(), BRIX_CRL_MODE_OFF, brix_ftp_ssl_ctx_cleanup(), BRIX_SP_MODE_OFF, ngx_stream_brix_ftp_srv_conf_t::ca_store, ngx_stream_brix_ftp_srv_conf_t::certificate, ngx_stream_brix_ftp_srv_conf_t::certificate_key, ngx_memcpy, ngx_pcalloc(), PATH_MAX, stat(), ngx_stream_brix_ftp_srv_conf_t::tls_ctx, and ngx_stream_brix_ftp_srv_conf_t::trusted_ca.
Referenced by brix_ftp_merge_conf().
brix_ftp_ssl_ctx_cleanup()
static void brix_ftp_ssl_ctx_cleanup (void * data) static
Definition at line 20 of file ftp_module_gsi.c.
Referenced by brix_ftp_build_gsi().