nginx-xrootd: src/protocols/gridftp/ev/ftp_ev_mode_e_recv.c File Reference
ftp_ev_mode_e_recv.c File Reference
#include "ftp_ev.h"
#include "ftp_ev_mode_e_internal.h"
#include "fs/vfs/vfs.h"
#include "fs/vfs/vfs_ops.h"
#include <stdint.h>
Data Structures
struct ftp_ev_eb_conn_t
Macros
#define FTP_EV_EB_MARKER_MAX_RANGES 32 /* cap the 111 range-list length */
Enumerations
enum ev_eb_step_t { EV_EB_STEP_RET = 0 , EV_EB_STEP_MORE , EV_EB_STEP_OK }
Functions
static int ev_eb_range_cmp (const void *a, const void *b)
static void ev_eb_marker_range (ftp_ev_dc_t *dc)
static void ev_eb_child_close (ftp_ev_eb_conn_t *ch)
void brix_ftp_ev_eb_teardown (ftp_ev_dc_t *dc)
static int ev_eb_ranges_contiguous (ftp_ev_dc_t *dc)
static void ev_eb_child_done (ftp_ev_eb_conn_t *ch)
static ngx_int_t ev_eb_arm_read (ngx_connection_t *c)
static ev_eb_step_t ev_eb_reserve_range (ftp_ev_eb_conn_t *ch, ftp_ev_dc_t *dc, uint64_t count, uint64_t offset)
static ev_eb_step_t ev_eb_recv_header (ngx_connection_t *c, ftp_ev_eb_conn_t *ch, ftp_ev_dc_t *dc)
static ev_eb_step_t ev_eb_drain_payload (ngx_connection_t *c, ftp_ev_eb_conn_t *ch, ftp_ev_dc_t *dc)
static void ev_eb_child_read (ngx_event_t *rev)
static void ev_eb_child_tls_done (ngx_connection_t *c)
static ftp_ev_eb_conn_t * ev_eb_slot (ftp_ev_dc_t *dc)
static ngx_int_t ev_eb_receiver_open (ftp_ev_dc_t *dc)
void brix_ftp_ev_eb_accept (ngx_event_t *rev)
Macro Definition Documentation
FTP_EV_EB_MARKER_MAX_RANGES
#define FTP_EV_EB_MARKER_MAX_RANGES 32 /* cap the 111 range-list length */
Definition at line 28 of file ftp_ev_mode_e_recv.c.
Enumeration Type Documentation
ev_eb_step_t
enum ev_eb_step_t
Enumerator
EV_EB_STEP_RET
EV_EB_STEP_MORE
EV_EB_STEP_OK
Definition at line 232 of file ftp_ev_mode_e_recv.c.
Function Documentation
brix_ftp_ev_eb_accept()
void brix_ftp_ev_eb_accept (ngx_event_t * rev)
Definition at line 470 of file ftp_ev_mode_e_recv.c.
References brix_ftp_ev_data_finish(), BRIX_FTP_EV_EB_MAX_CONNS, BRIX_FTP_EV_IO_TIMEO, brix_ftp_ev_tls_begin(), brix_ftp_ev_wrap_conn(), c, ftp_ev_t::c, ftp_ev_eb_conn_t::c, close(), ftp_ev_eb_conn_t::dc, ev_eb_arm_read(), ev_eb_child_read(), ev_eb_child_tls_done(), ev_eb_receiver_open(), ev_eb_slot(), ftp_ev_eb_conn_t::in_use, ftp_ev_eb_conn_t::pool, and ftp_ev_t::prot.
Referenced by brix_ftp_ev_data_open().
brix_ftp_ev_eb_teardown()
void brix_ftp_ev_eb_teardown (ftp_ev_dc_t * dc)
Definition at line 128 of file ftp_ev_mode_e_recv.c.
References BRIX_FTP_EV_EB_MAX_CONNS, conns, ev_eb_child_close(), and in_use.
Referenced by brix_ftp_ev_data_finish().
ev_eb_arm_read()
static ngx_int_t ev_eb_arm_read (ngx_connection_t * c) static
Definition at line 219 of file ftp_ev_mode_e_recv.c.
References BRIX_FTP_EV_IO_TIMEO, and c.
Referenced by brix_ftp_ev_eb_accept(), ev_eb_child_tls_done(), ev_eb_drain_payload(), and ev_eb_recv_header().
ev_eb_child_close()
static void ev_eb_child_close (ftp_ev_eb_conn_t * ch) static
Definition at line 107 of file ftp_ev_mode_e_recv.c.
References ftp_ev_eb_conn_t::c, ftp_ev_eb_conn_t::dc, ftp_ev_eb_conn_t::in_use, and ftp_ev_eb_conn_t::pool.
Referenced by brix_ftp_ev_eb_teardown(), and ev_eb_child_done().
ev_eb_child_done()
static void ev_eb_child_done (ftp_ev_eb_conn_t * ch) static
Definition at line 185 of file ftp_ev_mode_e_recv.c.
References brix_ftp_ev_data_finish(), brix_ftp_ev_vfs_ctx(), brix_vfs_unlink(), brix_vfs_writer_abort(), brix_vfs_writer_commit(), ftp_ev_eb_conn_t::dc, ev_eb_child_close(), and ev_eb_ranges_contiguous().
Referenced by ev_eb_child_read(), and ev_eb_recv_header().
ev_eb_child_read()
static void ev_eb_child_read (ngx_event_t * rev) static
Definition at line 356 of file ftp_ev_mode_e_recv.c.
References brix_ftp_ev_data_finish(), c, ftp_ev_eb_conn_t::dc, ftp_ev_eb_conn_t::desc, ev_eb_child_done(), ev_eb_drain_payload(), ev_eb_marker_perf(), ev_eb_marker_range(), ev_eb_recv_header(), EV_EB_STEP_MORE, EV_EB_STEP_RET, FTP_EB_EOD, FTP_EV_EB_MARKER_BYTES, and ftp_ev_eb_conn_t::have_hdr.
Referenced by brix_ftp_ev_eb_accept(), and ev_eb_child_tls_done().
ev_eb_child_tls_done()
static void ev_eb_child_tls_done (ngx_connection_t * c) static
Definition at line 407 of file ftp_ev_mode_e_recv.c.
References brix_ftp_ev_data_finish(), brix_ftp_ev_tls_verify(), c, ftp_ev_eb_conn_t::dc, ev_eb_arm_read(), and ev_eb_child_read().
Referenced by brix_ftp_ev_eb_accept().
ev_eb_drain_payload()
static ev_eb_step_t ev_eb_drain_payload (ngx_connection_t * c, ftp_ev_eb_conn_t * ch, ftp_ev_dc_t * dc) static
Definition at line 322 of file ftp_ev_mode_e_recv.c.
References ftp_ev_eb_conn_t::at, brix_ftp_ev_data_finish(), BRIX_FTP_EV_XFER_BUF, brix_vfs_writer_write(), c, ftp_ev_eb_conn_t::count, ev_eb_arm_read(), EV_EB_STEP_OK, and EV_EB_STEP_RET.
Referenced by ev_eb_child_read().
ev_eb_marker_range()
static void ev_eb_marker_range (ftp_ev_dc_t * dc) static
Definition at line 64 of file ftp_ev_mode_e_recv.c.
References brix_ftp_ev_flush(), brix_ftp_ev_reply(), ev_eb_range_cmp(), FTP_EV_EB_MARKER_MAX_RANGES, and ngx_memcpy.
Referenced by ev_eb_child_read().
ev_eb_range_cmp()
static int ev_eb_range_cmp (const void * a, const void * b) static
Definition at line 51 of file ftp_ev_mode_e_recv.c.
References ftp_eb_range_t::lo.
Referenced by ev_eb_marker_range(), and ev_eb_ranges_contiguous().
ev_eb_ranges_contiguous()
static int ev_eb_ranges_contiguous (ftp_ev_dc_t * dc) static
Definition at line 154 of file ftp_ev_mode_e_recv.c.
References ev_eb_range_cmp(), and ngx_memcpy.
Referenced by ev_eb_child_done().
ev_eb_receiver_open()
static ngx_int_t ev_eb_receiver_open (ftp_ev_dc_t * dc) static
Definition at line 443 of file ftp_ev_mode_e_recv.c.
References BRIX_FTP_EV_EB_MAX_CONNS, BRIX_FTP_EV_EB_MAX_RANGES, brix_ftp_ev_vfs_ctx(), brix_vfs_writer_open(), ftp_ev_t::c, ngx_pcalloc(), and ngx_pnalloc().
Referenced by brix_ftp_ev_eb_accept().
ev_eb_recv_header()
static ev_eb_step_t ev_eb_recv_header (ngx_connection_t * c, ftp_ev_eb_conn_t * ch, ftp_ev_dc_t * dc) static
Definition at line 275 of file ftp_ev_mode_e_recv.c.
References brix_ftp_ev_data_finish(), c, ftp_ev_eb_conn_t::count, ftp_ev_eb_conn_t::desc, ev_eb_arm_read(), ev_eb_child_done(), ev_eb_reserve_range(), EV_EB_STEP_MORE, EV_EB_STEP_OK, EV_EB_STEP_RET, FTP_EB_EOF, FTP_EB_HDR, ftp_eb_unpack(), ftp_ev_eb_conn_t::have_hdr, ftp_ev_eb_conn_t::hdr, and ftp_ev_eb_conn_t::hdr_got.
Referenced by ev_eb_child_read().
ev_eb_reserve_range()
static ev_eb_step_t ev_eb_reserve_range (ftp_ev_eb_conn_t * ch, ftp_ev_dc_t * dc, uint64_t count, uint64_t offset) static
Definition at line 243 of file ftp_ev_mode_e_recv.c.
References ftp_ev_eb_conn_t::at, brix_ftp_ev_data_finish(), BRIX_FTP_EV_EB_MAX_RANGES, ftp_ev_eb_conn_t::count, EV_EB_STEP_OK, EV_EB_STEP_RET, and ftp_eb_range_overlaps().
Referenced by ev_eb_recv_header().
ev_eb_slot()
static ftp_ev_eb_conn_t * ev_eb_slot (ftp_ev_dc_t * dc) static
Definition at line 427 of file ftp_ev_mode_e_recv.c.
References BRIX_FTP_EV_EB_MAX_CONNS, conns, and in_use.
Referenced by brix_ftp_ev_eb_accept().