nginx-xrootd: src/protocols/gridftp/ev/ftp_ev_sec.c File Reference
ftp_ev_sec.c File Reference
#include "ftp_ev.h"
#include "core/types/identity.h"
#include "auth/gssapi/gsi_mech.h"
#include <strings.h>
Functions
static void ev_gss_finalize (ftp_ev_t *fc)
ngx_int_t brix_ftp_ev_cmd_auth (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_adat (ftp_ev_t *fc, const char *arg)
ngx_int_t brix_ftp_ev_cmd_protected (ftp_ev_t *fc, const char *code, const char *arg)
Function Documentation
brix_ftp_ev_cmd_adat()
ngx_int_t brix_ftp_ev_cmd_adat (ftp_ev_t * fc, const char * arg)
Definition at line 101 of file ftp_ev_sec.c.
References brix_ftp_ev_b64_decode(), brix_ftp_ev_reply(), brix_ftp_ev_send_adat(), BRIX_GSS_CONTINUE, BRIX_GSS_FAILED, brix_gssapi_srv_step(), ftp_ev_t::c, ev_gss_finalize(), ftp_ev_t::gss, and tok.
Referenced by ev_grp_security().
brix_ftp_ev_cmd_auth()
ngx_int_t brix_ftp_ev_cmd_auth (ftp_ev_t * fc, const char * arg)
Definition at line 74 of file ftp_ev_sec.c.
References brix_ftp_ev_reply(), brix_gssapi_srv_create(), ftp_ev_t::c, ngx_stream_brix_ftp_srv_conf_t::ca_store, ftp_ev_t::conf, ngx_stream_brix_ftp_srv_conf_t::gsi, ftp_ev_t::gss, and ngx_stream_brix_ftp_srv_conf_t::tls_ctx.
Referenced by ev_grp_security().
brix_ftp_ev_cmd_protected()
ngx_int_t brix_ftp_ev_cmd_protected (ftp_ev_t * fc, const char * code, const char * arg)
Definition at line 141 of file ftp_ev_sec.c.
References brix_ftp_ev_b64_decode(), BRIX_FTP_EV_CMD_MAX, brix_ftp_ev_dispatch(), brix_ftp_ev_reply(), brix_gssapi_unwrap(), ftp_ev_t::c, code, ftp_ev_t::gss, ngx_memcpy, ngx_pnalloc(), ftp_ev_t::sec_active, tok, and ftp_ev_t::wrap_code.
Referenced by ev_grp_security().
ev_gss_finalize()
static void ev_gss_finalize (ftp_ev_t * fc) static
Definition at line 35 of file ftp_ev_sec.c.
References ftp_ev_t::authed, BRIX_AUTHN_GSI, brix_gssapi_srv_peer(), brix_gssapi_srv_peer_cert_pem(), brix_identity_alloc(), brix_identity_set_dn(), ftp_ev_t::c, ftp_ev_t::ctrl_dn, ftp_ev_t::ctrl_leaf_pem, ftp_ev_t::deleg_proxy, ftp_ev_t::gss, ftp_ev_t::identity, ngx_memcpy, ngx_pnalloc(), ftp_ev_t::sec_active, and ftp_ev_t::wrap_code.
Referenced by brix_ftp_ev_cmd_adat().