nginx-xrootd: src/protocols/gridftp/ev/ftp_ev_path.c File Reference
ftp_ev_path.c File Reference
#include "ftp_ev.h"
#include "fs/vfs/vfs.h"
#include "fs/vfs/vfs_ops.h"
#include "core/compat/path.h"
#include <string.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
Functions
char * brix_ftp_ev_split (char *line, char **verb_out)
int brix_ftp_ev_resolve (ftp_ev_t *fc, const char *arg, char *abs, size_t abssz)
static void fwd_collect_certs (ngx_str_t *pem, STACK_OF(X509) *sink)
static X509 * fwd_find_leaf (STACK_OF(X509) *certs, EVP_PKEY *key)
static X509 * fwd_next_issuer (STACK_OF(X509) *certs, X509 *cur)
static int fwd_emit_chain (BIO *obio, X509 *leaf, STACK_OF(X509) *certs)
static void fwd_serialize (ngx_pool_t *pool, BIO *obio, EVP_PKEY *key, ngx_str_t *out)
static ngx_str_t brix_ftp_ev_forward_pem (ngx_pool_t *pool, ngx_str_t *deleg, ngx_str_t *issuer)
void brix_ftp_ev_vfs_ctx (ftp_ev_t *fc, const char *abs, void *vctx)
Function Documentation
brix_ftp_ev_forward_pem()
static ngx_str_t brix_ftp_ev_forward_pem (ngx_pool_t * pool, ngx_str_t * deleg, ngx_str_t * issuer) static
Definition at line 241 of file ftp_ev_path.c.
References fwd_collect_certs(), fwd_emit_chain(), fwd_find_leaf(), fwd_serialize(), key, and STACK_OF().
Referenced by brix_ftp_ev_vfs_ctx().
brix_ftp_ev_resolve()
int brix_ftp_ev_resolve (ftp_ev_t * fc, const char * arg, char * abs, size_t abssz)
Definition at line 53 of file ftp_ev_path.c.
References brix_http_resolve_path(), ftp_ev_t::conf, ftp_ev_t::cwd, ngx_memcpy, PATH_MAX, and ngx_stream_brix_ftp_srv_conf_t::root_canon.
Referenced by brix_ftp_ev_cmd_cksm(), brix_ftp_ev_cmd_cwd(), brix_ftp_ev_cmd_dele(), brix_ftp_ev_cmd_mdtm(), brix_ftp_ev_cmd_mkd(), brix_ftp_ev_cmd_mlst(), brix_ftp_ev_cmd_rmd(), brix_ftp_ev_cmd_rnfr(), brix_ftp_ev_cmd_rnto(), brix_ftp_ev_cmd_size(), brix_ftp_ev_cmd_stat(), and ev_xfer_resolve_start().
brix_ftp_ev_split()
char * brix_ftp_ev_split (char * line, char ** verb_out)
Definition at line 35 of file ftp_ev_path.c.
Referenced by brix_ftp_ev_dispatch().
brix_ftp_ev_vfs_ctx()
void brix_ftp_ev_vfs_ctx (ftp_ev_t * fc, const char * abs, void * vctx)
Definition at line 298 of file ftp_ev_path.c.
References ngx_stream_brix_ftp_srv_conf_t::allow_write, BRIX_CRED_SELECT, brix_ftp_ev_forward_pem(), BRIX_PROTO_ROOT, brix_vfs_backend_accepts_proxy(), brix_vfs_ctx_init(), brix_vfs_deleg_bind(), ftp_ev_t::c, ftp_ev_t::conf, ftp_ev_t::ctrl_leaf_pem, ngx_stream_brix_ftp_srv_conf_t::deleg_mode, ftp_ev_t::deleg_proxy, ftp_ev_t::identity, ngx_stream_brix_ftp_srv_conf_t::root_canon, and ftp_ev_t::sec_active.
Referenced by brix_ftp_ev_cmd_cksm(), brix_ftp_ev_cmd_dele(), brix_ftp_ev_cmd_mdtm(), brix_ftp_ev_cmd_mkd(), brix_ftp_ev_cmd_mlst(), brix_ftp_ev_cmd_rmd(), brix_ftp_ev_cmd_rnto(), brix_ftp_ev_cmd_size(), brix_ftp_ev_cmd_stat(), brix_ftp_ev_data_ready(), ev_eb_child_done(), ev_eb_receiver_open(), and ev_xfer_resolve_start().
fwd_collect_certs()
static void fwd_collect_certs (ngx_str_t * pem, STACK_OF(X509) * sink) static
Definition at line 86 of file ftp_ev_path.c.
Referenced by brix_ftp_ev_forward_pem().
fwd_emit_chain()
static int fwd_emit_chain (BIO * obio, X509 * leaf, STACK_OF(X509) * certs) static
Definition at line 176 of file ftp_ev_path.c.
References fwd_next_issuer().
Referenced by brix_ftp_ev_forward_pem().
fwd_find_leaf()
static X509 * fwd_find_leaf (STACK_OF(X509) * certs, EVP_PKEY * key) static
Definition at line 119 of file ftp_ev_path.c.
References c, and key.
Referenced by brix_ftp_ev_forward_pem().
fwd_next_issuer()
static X509 * fwd_next_issuer (STACK_OF(X509) * certs, X509 * cur) static
Definition at line 144 of file ftp_ev_path.c.
References c.
Referenced by fwd_emit_chain().
fwd_serialize()
static void fwd_serialize (ngx_pool_t * pool, BIO * obio, EVP_PKEY * key, ngx_str_t * out) static
Definition at line 200 of file ftp_ev_path.c.
References key, ngx_memcpy, and ngx_pnalloc().
Referenced by brix_ftp_ev_forward_pem().