nginx-xrootd: src/protocols/gridftp/ftp_eblock.h File Reference
ftp_eblock.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <stdint.h>
Data Structures
struct ftp_eb_range_t
Macros
#define FTP_EB_HDR 17
#define FTP_EB_EOF 0x40 /* no payload; offset field = total EOD count */
#define FTP_EB_EOD 0x08 /* last block on this data connection */
Functions
static void ftp_eb_pack (u_char *h, u_char desc, uint64_t count, uint64_t offset)
static void ftp_eb_unpack (const u_char *h, u_char *desc, uint64_t *count, uint64_t *offset)
static int ftp_eb_range_overlaps (const ftp_eb_range_t *r, size_t n, off_t lo, off_t hi)
Macro Definition Documentation
FTP_EB_EOD
#define FTP_EB_EOD 0x08 /* last block on this data connection */
Definition at line 38 of file ftp_eblock.h.
FTP_EB_EOF
#define FTP_EB_EOF 0x40 /* no payload; offset field = total EOD count */
Definition at line 37 of file ftp_eblock.h.
FTP_EB_HDR
#define FTP_EB_HDR 17
Definition at line 36 of file ftp_eblock.h.
Function Documentation
ftp_eb_pack()
static void ftp_eb_pack (u_char * h, u_char desc, uint64_t count, uint64_t offset) inline static
Definition at line 42 of file ftp_eblock.h.
Referenced by ev_retr_mode_e_write().
ftp_eb_range_overlaps()
static int ftp_eb_range_overlaps (const ftp_eb_range_t * r, size_t n, off_t lo, off_t hi) inline static
Definition at line 70 of file ftp_eblock.h.
Referenced by ev_eb_child_read().
ftp_eb_unpack()
static void ftp_eb_unpack (const u_char * h, u_char * desc, uint64_t * count, uint64_t * offset) inline static
Definition at line 52 of file ftp_eblock.h.
References c.
Referenced by ev_eb_child_read().