nginx-xrootd: src/protocols/gridftp/ev/ftp_ev_mode_e_internal.h File Reference
ftp_ev_mode_e_internal.h File Reference
#include "ftp_ev.h"
Macros
#define FTP_EV_EB_MARKER_BYTES (1 << 20) /* emit 111/112 each ~1 MiB moved */
Functions
void ev_eb_marker_perf (ftp_ev_t *fc, off_t bytes)
Macro Definition Documentation
FTP_EV_EB_MARKER_BYTES
#define FTP_EV_EB_MARKER_BYTES (1 << 20) /* emit 111/112 each ~1 MiB moved */
Definition at line 12 of file ftp_ev_mode_e_internal.h.
Function Documentation
ev_eb_marker_perf()
void ev_eb_marker_perf (ftp_ev_t * fc, off_t bytes)
Definition at line 33 of file ftp_ev_mode_e.c.
References brix_ftp_ev_flush(), and brix_ftp_ev_reply().
Referenced by ev_eb_child_read(), and ev_retr_mode_e_write().