nginx-xrootd: src/protocols/gridftp/ev/ftp_ev_mode_e.c File Reference
ftp_ev_mode_e.c File Reference
#include "ftp_ev.h"
#include "fs/vfs/vfs.h"
#include "fs/vfs/vfs_ops.h"
#include <stdint.h>
Data Structures
struct ftp_ev_eb_conn_t
Macros
#define FTP_EV_EB_MARKER_BYTES (1 << 20) /* emit 111/112 each ~1 MiB moved */
#define FTP_EV_EB_MARKER_MAX_RANGES 32 /* cap the 111 range-list length */
Functions
static void ev_eb_marker_perf (ftp_ev_t *fc, off_t bytes)
static int ev_eb_range_cmp (const void *a, const void *b)
static void ev_eb_marker_range (ftp_ev_dc_t *dc)
static void ev_eb_send_idle (ngx_event_t *ev)
static void ev_retr_mode_e_write (ngx_event_t *wev)
void brix_ftp_ev_retr_mode_e_start (ftp_ev_dc_t *dc)
static void ev_eb_child_close (ftp_ev_eb_conn_t *ch)
void brix_ftp_ev_eb_teardown (ftp_ev_dc_t *dc)
static void ev_eb_child_done (ftp_ev_eb_conn_t *ch)
static ngx_int_t ev_eb_arm_read (ngx_connection_t *c)
static void ev_eb_child_read (ngx_event_t *rev)
static void ev_eb_child_tls_done (ngx_connection_t *c)
static ftp_ev_eb_conn_t * ev_eb_slot (ftp_ev_dc_t *dc)
static ngx_int_t ev_eb_receiver_open (ftp_ev_dc_t *dc)
void brix_ftp_ev_eb_accept (ngx_event_t *rev)
Macro Definition Documentation
FTP_EV_EB_MARKER_BYTES
#define FTP_EV_EB_MARKER_BYTES (1 << 20) /* emit 111/112 each ~1 MiB moved */
Definition at line 38 of file ftp_ev_mode_e.c.
FTP_EV_EB_MARKER_MAX_RANGES
#define FTP_EV_EB_MARKER_MAX_RANGES 32 /* cap the 111 range-list length */
Definition at line 39 of file ftp_ev_mode_e.c.
Function Documentation
brix_ftp_ev_eb_accept()
void brix_ftp_ev_eb_accept (ngx_event_t * rev)
Definition at line 494 of file ftp_ev_mode_e.c.
References brix_ftp_ev_data_finish(), BRIX_FTP_EV_EB_MAX_CONNS, BRIX_FTP_EV_IO_TIMEO, brix_ftp_ev_tls_begin(), brix_ftp_ev_wrap_conn(), c, ftp_ev_t::c, ftp_ev_eb_conn_t::c, close(), ftp_ev_eb_conn_t::dc, ev_eb_arm_read(), ev_eb_child_read(), ev_eb_child_tls_done(), ev_eb_receiver_open(), ev_eb_slot(), ftp_ev_eb_conn_t::in_use, ftp_ev_eb_conn_t::pool, and ftp_ev_t::prot.
Referenced by brix_ftp_ev_data_open().
brix_ftp_ev_eb_teardown()
void brix_ftp_ev_eb_teardown (ftp_ev_dc_t * dc)
Definition at line 254 of file ftp_ev_mode_e.c.
References BRIX_FTP_EV_EB_MAX_CONNS, ev_eb_child_close(), and in_use.
Referenced by brix_ftp_ev_data_finish().
brix_ftp_ev_retr_mode_e_start()
void brix_ftp_ev_retr_mode_e_start (ftp_ev_dc_t * dc)
Definition at line 219 of file ftp_ev_mode_e.c.
References ev_eb_send_idle(), and ev_retr_mode_e_write().
Referenced by brix_ftp_ev_data_ready().
ev_eb_arm_read()
static ngx_int_t ev_eb_arm_read (ngx_connection_t * c) static
Definition at line 288 of file ftp_ev_mode_e.c.
References BRIX_FTP_EV_IO_TIMEO, and c.
Referenced by brix_ftp_ev_eb_accept(), ev_eb_child_read(), and ev_eb_child_tls_done().
ev_eb_child_close()
static void ev_eb_child_close (ftp_ev_eb_conn_t * ch) static
Definition at line 233 of file ftp_ev_mode_e.c.
References ftp_ev_eb_conn_t::c, ftp_ev_eb_conn_t::dc, ftp_ev_eb_conn_t::in_use, and ftp_ev_eb_conn_t::pool.
Referenced by brix_ftp_ev_eb_teardown(), and ev_eb_child_done().
ev_eb_child_done()
static void ev_eb_child_done (ftp_ev_eb_conn_t * ch) static
Definition at line 273 of file ftp_ev_mode_e.c.
References brix_ftp_ev_data_finish(), brix_vfs_writer_commit(), ftp_ev_eb_conn_t::dc, and ev_eb_child_close().
Referenced by ev_eb_child_read().
ev_eb_child_read()
static void ev_eb_child_read (ngx_event_t * rev) static
Definition at line 302 of file ftp_ev_mode_e.c.
References ftp_ev_eb_conn_t::at, brix_ftp_ev_data_finish(), BRIX_FTP_EV_EB_MAX_RANGES, BRIX_FTP_EV_XFER_BUF, brix_vfs_writer_write(), c, ftp_ev_eb_conn_t::count, ftp_ev_eb_conn_t::dc, ftp_ev_eb_conn_t::desc, ev_eb_arm_read(), ev_eb_child_done(), ev_eb_marker_perf(), ev_eb_marker_range(), FTP_EB_EOD, FTP_EB_EOF, FTP_EB_HDR, ftp_eb_range_overlaps(), ftp_eb_unpack(), FTP_EV_EB_MARKER_BYTES, ftp_ev_eb_conn_t::have_hdr, ftp_ev_eb_conn_t::hdr, and ftp_ev_eb_conn_t::hdr_got.
Referenced by brix_ftp_ev_eb_accept(), and ev_eb_child_tls_done().
ev_eb_child_tls_done()
static void ev_eb_child_tls_done (ngx_connection_t * c) static
Definition at line 431 of file ftp_ev_mode_e.c.
References brix_ftp_ev_data_finish(), brix_ftp_ev_tls_verify(), c, ftp_ev_eb_conn_t::dc, ev_eb_arm_read(), and ev_eb_child_read().
Referenced by brix_ftp_ev_eb_accept().
ev_eb_marker_perf()
static void ev_eb_marker_perf (ftp_ev_t * fc, off_t bytes) static
Definition at line 65 of file ftp_ev_mode_e.c.
References brix_ftp_ev_flush(), and brix_ftp_ev_reply().
Referenced by ev_eb_child_read(), and ev_retr_mode_e_write().
ev_eb_marker_range()
static void ev_eb_marker_range (ftp_ev_dc_t * dc) static
Definition at line 93 of file ftp_ev_mode_e.c.
References brix_ftp_ev_flush(), brix_ftp_ev_reply(), ev_eb_range_cmp(), FTP_EV_EB_MARKER_MAX_RANGES, and ngx_memcpy.
Referenced by ev_eb_child_read().
ev_eb_range_cmp()
static int ev_eb_range_cmp (const void * a, const void * b) static
Definition at line 80 of file ftp_ev_mode_e.c.
References ftp_eb_range_t::lo.
Referenced by ev_eb_marker_range().
ev_eb_receiver_open()
static ngx_int_t ev_eb_receiver_open (ftp_ev_dc_t * dc) static
Definition at line 467 of file ftp_ev_mode_e.c.
References BRIX_FTP_EV_EB_MAX_CONNS, BRIX_FTP_EV_EB_MAX_RANGES, brix_ftp_ev_vfs_ctx(), brix_vfs_writer_open(), ftp_ev_t::c, ngx_pcalloc(), and ngx_pnalloc().
Referenced by brix_ftp_ev_eb_accept().
ev_eb_send_idle()
static void ev_eb_send_idle (ngx_event_t * ev) static
Definition at line 137 of file ftp_ev_mode_e.c.
Referenced by brix_ftp_ev_retr_mode_e_start().
ev_eb_slot()
static ftp_ev_eb_conn_t * ev_eb_slot (ftp_ev_dc_t * dc) static
Definition at line 451 of file ftp_ev_mode_e.c.
References BRIX_FTP_EV_EB_MAX_CONNS, and in_use.
Referenced by brix_ftp_ev_eb_accept().
ev_retr_mode_e_write()
static void ev_retr_mode_e_write (ngx_event_t * wev) static
Definition at line 144 of file ftp_ev_mode_e.c.
References brix_ftp_ev_data_finish(), BRIX_FTP_EV_IO_TIMEO, BRIX_FTP_EV_XFER_BUF, brix_vfs_file_pread(), c, ev_eb_marker_perf(), FTP_EB_EOD, FTP_EB_EOF, FTP_EB_HDR, ftp_eb_pack(), and FTP_EV_EB_MARKER_BYTES.
Referenced by brix_ftp_ev_retr_mode_e_start().