nginx-xrootd: src/protocols/gridftp/ev/ftp_ev_reply.c File Reference
ftp_ev_reply.c File Reference
#include "ftp_ev.h"
Functions
static ngx_int_t ev_out_put (ftp_ev_t *fc, const u_char *data, size_t len)
static ngx_int_t ev_b64_encode (ngx_pool_t *pool, const u_char *data, size_t len, ngx_str_t *out)
ngx_int_t brix_ftp_ev_b64_decode (ngx_pool_t *pool, const char *b64, ngx_str_t *out)
static ngx_int_t ev_reply_wrapped (ftp_ev_t *fc, const u_char *plain, size_t n)
ngx_int_t brix_ftp_ev_reply (ftp_ev_t *fc, const char *fmt,...)
ngx_int_t brix_ftp_ev_send_adat (ftp_ev_t *fc, int code, ngx_str_t *tok)
Function Documentation
brix_ftp_ev_b64_decode()
ngx_int_t brix_ftp_ev_b64_decode (ngx_pool_t * pool, const char * b64, ngx_str_t * out)
Definition at line 60 of file ftp_ev_reply.c.
References b64, and ngx_pnalloc().
Referenced by brix_ftp_ev_cmd_adat(), and brix_ftp_ev_cmd_protected().
brix_ftp_ev_reply()
ngx_int_t brix_ftp_ev_reply (ftp_ev_t * fc, const char * fmt, ...)
Definition at line 100 of file ftp_ev_reply.c.
References BRIX_FTP_EV_LINE_MAX, ev_out_put(), ev_reply_wrapped(), and ftp_ev_t::sec_active.
Referenced by brix_ftp_ev_cmd_adat(), brix_ftp_ev_cmd_auth(), brix_ftp_ev_cmd_cksm(), brix_ftp_ev_cmd_cwd(), brix_ftp_ev_cmd_dele(), brix_ftp_ev_cmd_mdtm(), brix_ftp_ev_cmd_mkd(), brix_ftp_ev_cmd_mlst(), brix_ftp_ev_cmd_protected(), brix_ftp_ev_cmd_rmd(), brix_ftp_ev_cmd_rnfr(), brix_ftp_ev_cmd_rnto(), brix_ftp_ev_cmd_size(), brix_ftp_ev_cmd_stat(), brix_ftp_ev_data_finish(), brix_ftp_ev_dispatch(), brix_ftp_ev_handler(), ev_begin_transfer(), ev_cmd_feat(), ev_do_pasv(), ev_do_port(), ev_eb_marker_perf(), and ev_eb_marker_range().
brix_ftp_ev_send_adat()
ngx_int_t brix_ftp_ev_send_adat (ftp_ev_t * fc, int code, ngx_str_t * tok)
Definition at line 121 of file ftp_ev_reply.c.
References b64, ftp_ev_t::c, code, ev_b64_encode(), ev_out_put(), ngx_pnalloc(), and tok.
Referenced by brix_ftp_ev_cmd_adat().
ev_b64_encode()
static ngx_int_t ev_b64_encode (ngx_pool_t * pool, const u_char * data, size_t len, ngx_str_t * out) static
Definition at line 43 of file ftp_ev_reply.c.
References ngx_pnalloc().
Referenced by brix_ftp_ev_send_adat(), and ev_reply_wrapped().
ev_out_put()
static ngx_int_t ev_out_put (ftp_ev_t * fc, const u_char * data, size_t len) static
Definition at line 27 of file ftp_ev_reply.c.
References BRIX_FTP_EV_OB_CAP, ftp_ev_t::c, ngx_memcpy, ftp_ev_t::ob, and ftp_ev_t::ob_len.
Referenced by brix_ftp_ev_reply(), brix_ftp_ev_send_adat(), and ev_reply_wrapped().
ev_reply_wrapped()
static ngx_int_t ev_reply_wrapped (ftp_ev_t * fc, const u_char * plain, size_t n) static
Definition at line 77 of file ftp_ev_reply.c.
References b64, brix_gssapi_wrap(), ftp_ev_t::c, ev_b64_encode(), ev_out_put(), ftp_ev_t::gss, ngx_pnalloc(), tok, and ftp_ev_t::wrap_code.
Referenced by brix_ftp_ev_reply().