nginx-xrootd: src/protocols/gridftp/ev/ftp_ev_dispatch.c File Reference
ftp_ev_dispatch.c File Reference
#include "ftp_ev.h"
#include <strings.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
Functions
static int ev_verb_preauth (const char *verb)
static ngx_int_t ev_cmd_feat (ftp_ev_t *fc)
static ngx_int_t ev_cmd_prot (ftp_ev_t *fc, const char *arg)
static ngx_int_t ev_cmd_dcau (ftp_ev_t *fc, const char *arg)
static ngx_int_t ev_cmd_opts (ftp_ev_t *fc, const char *arg)
static ngx_int_t ev_cmd_mode (ftp_ev_t *fc, const char *arg)
static ngx_int_t ev_cmd_allo (ftp_ev_t *fc, const char *arg)
static ngx_int_t ev_cmd_rest (ftp_ev_t *fc, const char *arg)
static ngx_int_t ev_cmd_cdup (ftp_ev_t *fc)
static ngx_int_t ev_grp_security (ftp_ev_t *fc, const char *verb, const char *arg)
static ngx_int_t ev_grp_login (ftp_ev_t *fc, const char *verb, const char *arg)
static ngx_int_t ev_grp_dcprot (ftp_ev_t *fc, const char *verb, const char *arg)
static ngx_int_t ev_grp_session (ftp_ev_t *fc, const char *verb, const char *arg)
static ngx_int_t ev_grp_xferparam (ftp_ev_t *fc, const char *verb, const char *arg)
static ngx_int_t ev_grp_navigation (ftp_ev_t *fc, const char *verb, const char *arg)
static ngx_int_t ev_grp_namespace (ftp_ev_t *fc, const char *verb, const char *arg)
static ngx_int_t ev_grp_transfer (ftp_ev_t *fc, const char *verb, const char *arg)
static ngx_int_t ev_grp_ctl (ftp_ev_t *fc, const char *verb)
ngx_int_t brix_ftp_ev_dispatch (ftp_ev_t *fc, char *line)
Function Documentation
brix_ftp_ev_dispatch()
ngx_int_t brix_ftp_ev_dispatch (ftp_ev_t * fc, char * line)
Definition at line 388 of file ftp_ev_dispatch.c.
References ftp_ev_t::authed, brix_ftp_ev_reply(), brix_ftp_ev_split(), ev_grp_ctl(), ev_grp_dcprot(), ev_grp_login(), ev_grp_namespace(), ev_grp_navigation(), ev_grp_security(), ev_grp_session(), ev_grp_transfer(), ev_grp_xferparam(), and ev_verb_preauth().
Referenced by brix_ftp_ev_cmd_protected(), and brix_ftp_ev_process().
ev_cmd_allo()
static ngx_int_t ev_cmd_allo (ftp_ev_t * fc, const char * arg) static
Definition at line 154 of file ftp_ev_dispatch.c.
References ftp_ev_t::allo_size, and brix_ftp_ev_reply().
Referenced by ev_grp_xferparam().
ev_cmd_cdup()
static ngx_int_t ev_cmd_cdup (ftp_ev_t * fc) static
Definition at line 182 of file ftp_ev_dispatch.c.
References brix_ftp_ev_reply(), and ftp_ev_t::cwd.
Referenced by ev_grp_navigation().
ev_cmd_dcau()
static ngx_int_t ev_cmd_dcau (ftp_ev_t * fc, const char * arg) static
Definition at line 97 of file ftp_ev_dispatch.c.
References brix_ftp_ev_reply(), ftp_ev_t::dcau_a, and ftp_ev_t::sec_active.
Referenced by ev_grp_dcprot().
ev_cmd_feat()
static ngx_int_t ev_cmd_feat (ftp_ev_t * fc) static
Definition at line 61 of file ftp_ev_dispatch.c.
References brix_ftp_ev_reply(), ftp_ev_t::conf, ngx_stream_brix_ftp_srv_conf_t::gsi, and ngx_stream_brix_ftp_srv_conf_t::tls_ctx.
Referenced by ev_grp_session().
ev_cmd_mode()
static ngx_int_t ev_cmd_mode (ftp_ev_t * fc, const char * arg) static
Definition at line 131 of file ftp_ev_dispatch.c.
References brix_ftp_ev_reply(), and ftp_ev_t::mode_e.
Referenced by ev_grp_xferparam().
ev_cmd_opts()
static ngx_int_t ev_cmd_opts (ftp_ev_t * fc, const char * arg) static
Definition at line 115 of file ftp_ev_dispatch.c.
References brix_ftp_ev_reply(), and ftp_ev_t::parallelism.
Referenced by ev_grp_session().
ev_cmd_prot()
static ngx_int_t ev_cmd_prot (ftp_ev_t * fc, const char * arg) static
Definition at line 79 of file ftp_ev_dispatch.c.
References brix_ftp_ev_reply(), ftp_ev_t::prot, and ftp_ev_t::sec_active.
Referenced by ev_grp_dcprot().
ev_cmd_rest()
static ngx_int_t ev_cmd_rest (ftp_ev_t * fc, const char * arg) static
Definition at line 167 of file ftp_ev_dispatch.c.
References brix_ftp_ev_reply(), and ftp_ev_t::rest_off.
Referenced by ev_grp_xferparam().
ev_grp_ctl()
static ngx_int_t ev_grp_ctl (ftp_ev_t * fc, const char * verb) static
Definition at line 372 of file ftp_ev_dispatch.c.
References ftp_ev_t::active, brix_ftp_ev_reply(), close(), and ftp_ev_t::pasv_fd.
Referenced by brix_ftp_ev_dispatch().
ev_grp_dcprot()
static ngx_int_t ev_grp_dcprot (ftp_ev_t * fc, const char * verb, const char * arg) static
Definition at line 239 of file ftp_ev_dispatch.c.
References brix_ftp_ev_reply(), ev_cmd_dcau(), and ev_cmd_prot().
Referenced by brix_ftp_ev_dispatch().
ev_grp_login()
static ngx_int_t ev_grp_login (ftp_ev_t * fc, const char * verb, const char * arg) static
Definition at line 221 of file ftp_ev_dispatch.c.
References ftp_ev_t::authed, brix_ftp_ev_reply(), and ftp_ev_t::sec_active.
Referenced by brix_ftp_ev_dispatch().
ev_grp_namespace()
static ngx_int_t ev_grp_namespace (ftp_ev_t * fc, const char * verb, const char * arg) static
Definition at line 314 of file ftp_ev_dispatch.c.
References brix_ftp_ev_cmd_cksm(), brix_ftp_ev_cmd_dele(), brix_ftp_ev_cmd_mdtm(), brix_ftp_ev_cmd_mkd(), brix_ftp_ev_cmd_mlst(), brix_ftp_ev_cmd_rmd(), brix_ftp_ev_cmd_rnfr(), brix_ftp_ev_cmd_rnto(), brix_ftp_ev_cmd_size(), and brix_ftp_ev_cmd_stat().
Referenced by brix_ftp_ev_dispatch().
ev_grp_navigation()
static ngx_int_t ev_grp_navigation (ftp_ev_t * fc, const char * verb, const char * arg) static
Definition at line 298 of file ftp_ev_dispatch.c.
References brix_ftp_ev_cmd_cwd(), brix_ftp_ev_reply(), ftp_ev_t::cwd, and ev_cmd_cdup().
Referenced by brix_ftp_ev_dispatch().
ev_grp_security()
static ngx_int_t ev_grp_security (ftp_ev_t * fc, const char * verb, const char * arg) static
Definition at line 202 of file ftp_ev_dispatch.c.
References brix_ftp_ev_cmd_adat(), brix_ftp_ev_cmd_auth(), and brix_ftp_ev_cmd_protected().
Referenced by brix_ftp_ev_dispatch().
ev_grp_session()
static ngx_int_t ev_grp_session (ftp_ev_t * fc, const char * verb, const char * arg) static
Definition at line 254 of file ftp_ev_dispatch.c.
References brix_ftp_ev_reply(), ev_cmd_feat(), and ev_cmd_opts().
Referenced by brix_ftp_ev_dispatch().
ev_grp_transfer()
static ngx_int_t ev_grp_transfer (ftp_ev_t * fc, const char * verb, const char * arg) static
Definition at line 343 of file ftp_ev_dispatch.c.
References brix_ftp_ev_do_transfer(), FTP_EV_OP_APPE, FTP_EV_OP_LIST, FTP_EV_OP_MLSD, FTP_EV_OP_NLST, FTP_EV_OP_RETR, and FTP_EV_OP_STOR.
Referenced by brix_ftp_ev_dispatch().
ev_grp_xferparam()
static ngx_int_t ev_grp_xferparam (ftp_ev_t * fc, const char * verb, const char * arg) static
Definition at line 273 of file ftp_ev_dispatch.c.
References brix_ftp_ev_reply(), ev_cmd_allo(), ev_cmd_mode(), ev_cmd_rest(), and ftp_ev_t::type_binary.
Referenced by brix_ftp_ev_dispatch().
ev_verb_preauth()
static int ev_verb_preauth (const char * verb) static
Definition at line 40 of file ftp_ev_dispatch.c.
Referenced by brix_ftp_ev_dispatch().