nginx-xrootd: src/protocols/gridftp/ev/ftp_ev_xfer.c File Reference
ftp_ev_xfer.c File Reference
#include "ftp_ev.h"
#include "fs/vfs/vfs.h"
#include "fs/vfs/vfs_ops.h"
#include <string.h>
Functions
static void ev_data_idle (ngx_event_t *ev)
static void ev_retr_write (ngx_event_t *wev)
static void ev_stor_read (ngx_event_t *rev)
static void ev_list_fill (ftp_ev_dc_t *dc)
static void ev_list_write (ngx_event_t *wev)
void brix_ftp_ev_data_ready (ftp_ev_dc_t *dc)
static ngx_int_t ev_begin_transfer (ftp_ev_t *fc, int op, const char *arg)
ngx_int_t brix_ftp_ev_do_transfer (ftp_ev_t *fc, int kind, const char *arg)
Function Documentation
brix_ftp_ev_data_ready()
void brix_ftp_ev_data_ready (ftp_ev_dc_t * dc)
Definition at line 268 of file ftp_ev_xfer.c.
References brix_ftp_ev_data_finish(), brix_ftp_ev_retr_mode_e_start(), brix_ftp_ev_vfs_ctx(), brix_vfs_file_size(), BRIX_VFS_O_READ, brix_vfs_open(), brix_vfs_opendir(), brix_vfs_writer_open(), ev_data_idle(), ev_list_write(), ev_retr_write(), ev_stor_read(), FTP_EV_OP_APPE, FTP_EV_OP_RETR, and FTP_EV_OP_STOR.
Referenced by ev_accept_handler(), ev_connect_handler(), and ev_dc_tls_done().
brix_ftp_ev_do_transfer()
ngx_int_t brix_ftp_ev_do_transfer (ftp_ev_t * fc, int kind, const char * arg)
Definition at line 438 of file ftp_ev_xfer.c.
References brix_ftp_ev_data_setup(), and ev_begin_transfer().
Referenced by brix_ftp_ev_dispatch().
ev_begin_transfer()
static ngx_int_t ev_begin_transfer (ftp_ev_t * fc, int op, const char * arg) static
Definition at line 326 of file ftp_ev_xfer.c.
References ftp_ev_t::active, ftp_ev_t::allo_size, ngx_stream_brix_ftp_srv_conf_t::allow_write, brix_ftp_ev_data_open(), brix_ftp_ev_reply(), brix_ftp_ev_resolve(), brix_ftp_ev_vfs_ctx(), BRIX_FTP_EV_XFER_BUF, BRIX_VFS_O_TRUNC, ftp_ev_t::c, code, ftp_ev_t::conf, ftp_ev_t::dc, FTP_EB_HDR, FTP_EV_LS_LONG, FTP_EV_LS_MLSD, FTP_EV_LS_NLST, FTP_EV_OP_APPE, FTP_EV_OP_LIST, FTP_EV_OP_MLSD, FTP_EV_OP_RETR, FTP_EV_OP_STOR, FTP_EV_ST_CMD, FTP_EV_ST_XFER, brix_vfs_stat_t::is_directory, ftp_ev_t::mode_e, ngx_pcalloc(), ngx_pnalloc(), op, ftp_ev_t::pasv_fd, PATH_MAX, ftp_ev_t::rest_off, brix_vfs_stat_t::size, ftp_ev_t::state, ftp_ev_t::type_binary, and ngx_stream_brix_ftp_srv_conf_t::verify_write.
Referenced by brix_ftp_ev_do_transfer().
ev_data_idle()
static void ev_data_idle (ngx_event_t * ev) static
Definition at line 37 of file ftp_ev_xfer.c.
Referenced by brix_ftp_ev_data_ready().
ev_list_fill()
static void ev_list_fill (ftp_ev_dc_t * dc) static
Definition at line 177 of file ftp_ev_xfer.c.
References BRIX_FTP_EV_XFER_BUF, brix_vfs_readdir(), FTP_EV_LS_LONG, FTP_EV_LS_MLSD, brix_vfs_stat_t::is_directory, name, PATH_MAX, and brix_vfs_stat_t::size.
Referenced by ev_list_write().
ev_list_write()
static void ev_list_write (ngx_event_t * wev) static
Definition at line 222 of file ftp_ev_xfer.c.
References brix_ftp_ev_data_finish(), BRIX_FTP_EV_IO_TIMEO, c, and ev_list_fill().
Referenced by brix_ftp_ev_data_ready().
ev_retr_write()
static void ev_retr_write (ngx_event_t * wev) static
Definition at line 46 of file ftp_ev_xfer.c.
References brix_ftp_ev_data_finish(), BRIX_FTP_EV_IO_TIMEO, BRIX_FTP_EV_XFER_BUF, brix_vfs_file_pread(), and c.
Referenced by brix_ftp_ev_data_ready().
ev_stor_read()
static void ev_stor_read (ngx_event_t * rev) static
Definition at line 106 of file ftp_ev_xfer.c.
References brix_ftp_ev_data_finish(), BRIX_FTP_EV_IO_TIMEO, BRIX_FTP_EV_XFER_BUF, brix_vfs_writer_commit(), brix_vfs_writer_write(), and c.
Referenced by brix_ftp_ev_data_ready().