nginx-xrootd: client/lib/posix/fuse_ops.h File Reference
fuse_ops.h File Reference
#include "brix.h"
#include <stddef.h>
#include <stdint.h>
#include <time.h>
Data Structures
struct brix_fuse_ctx_stat
struct brix_fuse_ctx_dir
struct brix_fuse_ctx_mkdir
struct brix_fuse_ctx_mv
struct brix_fuse_ctx_chmod
struct brix_fuse_ctx_trunc
struct brix_fuse_ctx_setattr
struct brix_fuse_ctx_link2
Typedefs
typedef int(* brix_fuse_op_fn) (brix_conn *c, void *ctx, brix_status *st)
Functions
int brix_fuse_errno (const brix_status *st)
int brix_fuse_conn_healthy (const brix_status *st)
int brix_fuse_run (brix_pool *pool, int max_retries, int max_stall_ms, int benign_errno, brix_fuse_op_fn op, void *ctx, brix_status *st)
int brix_fuse_op_stat (brix_conn *c, void *ctx, brix_status *st)
int brix_fuse_op_lstat (brix_conn *c, void *ctx, brix_status *st)
int brix_fuse_op_dirlist (brix_conn *c, void *ctx, brix_status *st)
int brix_fuse_op_mkdir (brix_conn *c, void *ctx, brix_status *st)
int brix_fuse_op_rm (brix_conn *c, void *ctx, brix_status *st)
int brix_fuse_op_rmdir (brix_conn *c, void *ctx, brix_status *st)
int brix_fuse_op_mv (brix_conn *c, void *ctx, brix_status *st)
int brix_fuse_op_chmod (brix_conn *c, void *ctx, brix_status *st)
int brix_fuse_op_trunc (brix_conn *c, void *ctx, brix_status *st)
int brix_fuse_op_setattr (brix_conn *c, void *ctx, brix_status *st)
int brix_fuse_op_symlink (brix_conn *c, void *ctx, brix_status *st)
int brix_fuse_op_link (brix_conn *c, void *ctx, brix_status *st)
Typedef Documentation
brix_fuse_op_fn
typedef int(* brix_fuse_op_fn) (brix_conn *c, void *ctx, brix_status *st)
Definition at line 32 of file fuse_ops.h.
Function Documentation
brix_fuse_conn_healthy()
int brix_fuse_conn_healthy (const brix_status * st)
Definition at line 21 of file fuse_ops.c.
References brix_status::kxr, XRDC_EPROTO, and XRDC_ESOCK.
Referenced by brix_fuse_run(), xfs_conn_healthy(), and xfs_conn_healthy().
brix_fuse_errno()
int brix_fuse_errno (const brix_status * st)
Definition at line 14 of file fuse_ops.c.
References brix_kxr_to_errno().
Referenced by brix_fuse_run(), xfs_err(), and xfs_err().
brix_fuse_op_chmod()
int brix_fuse_op_chmod (brix_conn * c, void * ctx, brix_status * st)
Definition at line 137 of file fuse_ops.c.
References brix_chmod(), c, brix_fuse_ctx_chmod::mode, and brix_fuse_ctx_chmod::path.
Referenced by xfs_chmod(), and xfs_chmod().
brix_fuse_op_dirlist()
int brix_fuse_op_dirlist (brix_conn * c, void * ctx, brix_status * st)
Definition at line 104 of file fuse_ops.c.
References brix_dirlist(), c, brix_fuse_ctx_dir::ents, brix_fuse_ctx_dir::n, and brix_fuse_ctx_dir::path.
Referenced by xfs_readdir(), and xfs_readdir().
brix_fuse_op_link()
int brix_fuse_op_link (brix_conn * c, void * ctx, brix_status * st)
Definition at line 166 of file fuse_ops.c.
References brix_fuse_ctx_link2::a, brix_link(), and c.
Referenced by xfs_link().
brix_fuse_op_lstat()
int brix_fuse_op_lstat (brix_conn * c, void * ctx, brix_status * st)
Definition at line 97 of file fuse_ops.c.
References brix_lstat(), c, brix_fuse_ctx_stat::path, and brix_fuse_ctx_stat::si.
Referenced by xfs_getattr().
brix_fuse_op_mkdir()
int brix_fuse_op_mkdir (brix_conn * c, void * ctx, brix_status * st)
Definition at line 111 of file fuse_ops.c.
References brix_mkdir(), c, brix_fuse_ctx_mkdir::mode, and brix_fuse_ctx_mkdir::path.
Referenced by xfs_mkdir(), and xfs_mkdir().
brix_fuse_op_mv()
int brix_fuse_op_mv (brix_conn * c, void * ctx, brix_status * st)
Definition at line 130 of file fuse_ops.c.
References brix_mv(), c, brix_fuse_ctx_mv::from, and brix_fuse_ctx_mv::to.
Referenced by xfs_rename(), and xfs_rename().
brix_fuse_op_rm()
int brix_fuse_op_rm (brix_conn * c, void * ctx, brix_status * st)
Definition at line 118 of file fuse_ops.c.
References brix_rm(), and c.
Referenced by xfs_unlink(), and xfs_unlink().
brix_fuse_op_rmdir()
int brix_fuse_op_rmdir (brix_conn * c, void * ctx, brix_status * st)
Definition at line 124 of file fuse_ops.c.
References brix_rmdir(), and c.
Referenced by xfs_rmdir(), and xfs_rmdir().
brix_fuse_op_setattr()
int brix_fuse_op_setattr (brix_conn * c, void * ctx, brix_status * st)
Definition at line 151 of file fuse_ops.c.
References brix_setattr(), c, brix_fuse_ctx_setattr::gid, brix_fuse_ctx_setattr::path, brix_fuse_ctx_setattr::set_owner, brix_fuse_ctx_setattr::set_times, brix_fuse_ctx_setattr::times, and brix_fuse_ctx_setattr::uid.
Referenced by xfs_chown(), and xfs_utimens().
brix_fuse_op_stat()
int brix_fuse_op_stat (brix_conn * c, void * ctx, brix_status * st)
Definition at line 90 of file fuse_ops.c.
References brix_stat(), c, brix_fuse_ctx_stat::path, and brix_fuse_ctx_stat::si.
Referenced by xfs_access(), and xfs_getattr().
brix_fuse_op_symlink()
int brix_fuse_op_symlink (brix_conn * c, void * ctx, brix_status * st)
Definition at line 159 of file fuse_ops.c.
References brix_fuse_ctx_link2::a, brix_symlink(), and c.
Referenced by xfs_symlink().
brix_fuse_op_trunc()
int brix_fuse_op_trunc (brix_conn * c, void * ctx, brix_status * st)
Definition at line 144 of file fuse_ops.c.
References brix_truncate(), c, brix_fuse_ctx_trunc::path, and brix_fuse_ctx_trunc::size.
Referenced by xfs_truncate(), and xfs_truncate().
brix_fuse_run()
int brix_fuse_run (brix_pool * pool, int max_retries, int max_stall_ms, int benign_errno, brix_fuse_op_fn op, void * ctx, brix_status * st)
Definition at line 39 of file fuse_ops.c.
References brix_backoff_sleep_fast(), brix_fuse_conn_healthy(), brix_fuse_errno(), brix_kxr_to_errno(), brix_mono_ns(), brix_pool_checkin(), brix_pool_checkout(), brix_status_clear(), brix_status_retryable(), c, fuse_run_done(), and op.
Referenced by xfs_chmod(), xfs_getattr(), xfs_meta(), xfs_meta_idem(), xfs_mkdir(), xfs_readdir(), xfs_rename(), xfs_rmdir(), xfs_truncate(), and xfs_unlink().