nginx-xrootd: src/protocols/cvmfs/gate.c File Reference
gate.c File Reference
#include "cvmfs.h"
#include "fs/path/path.h"
Data Structures
struct cvmfs_neg_slot
Macros
#define CVMFS_NEG_SLOTS 512u /* power of two: mask, don't mod */
Functions
static uint64_t cvmfs_neg_hash (const ngx_str_t *uri)
static int cvmfs_neg_check (const ngx_str_t *uri, time_t now)
static void cvmfs_neg_store (const ngx_str_t *uri, time_t now, time_t ttl)
void brix_cvmfs_notify_status (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf, ngx_uint_t status)
static ngx_int_t cvmfs_reject (ngx_http_request_t *r, ngx_uint_t status, const char *cause)
ngx_int_t brix_cvmfs_gate (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf)
Variables
static cvmfs_neg_slot cvmfs_neg [512u]
Macro Definition Documentation
CVMFS_NEG_SLOTS
#define CVMFS_NEG_SLOTS 512u /* power of two: mask, don't mod */
Definition at line 28 of file gate.c.
Function Documentation
brix_cvmfs_gate()
ngx_int_t brix_cvmfs_gate (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf)
Definition at line 100 of file gate.c.
References BRIX_ATOMIC_INC, BRIX_CVMFS_CACHE_NEG, BRIX_CVMFS_CLASS_CAS, BRIX_CVMFS_CLASS_GEO, BRIX_CVMFS_CLASS_MANIFEST, brix_cvmfs_geo_answer(), brix_cvmfs_geo_passthrough(), BRIX_CVMFS_GEO_RTT, BRIX_CVMFS_METRIC_INC, brix_cvmfs_proxy_target(), brix_cvmfs_repo_slot(), brix_cvmfs_upstream_get(), brix_sanitize_log_string(), ngx_http_brix_cvmfs_ctx_t::cache_status, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, cvmfs_neg_check(), cvmfs_reject(), brix_cvmfs_conf_t::geo_answer, ngx_brix_cvmfs_repo_metrics_t::negative_hits_total, brix_cvmfs_conf_t::negative_ttl, ngx_http_brix_cvmfs_module, ngx_http_brix_cvmfs_ctx_t::repo, ngx_brix_cvmfs_repo_metrics_t::requests_total, ngx_http_brix_cvmfs_ctx_t::sd_override, brix_cvmfs_conf_t::unified_origin, ngx_http_brix_cvmfs_ctx_t::up_root, and ngx_http_brix_cvmfs_ctx_t::url.
Referenced by ngx_http_brix_cvmfs_handler().
brix_cvmfs_notify_status()
void brix_cvmfs_notify_status (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf, ngx_uint_t status)
Definition at line 71 of file gate.c.
References ngx_http_brix_cvmfs_loc_conf_t::cvmfs, cvmfs_neg_store(), and brix_cvmfs_conf_t::negative_ttl.
Referenced by cvmfs_finalize_observe().
cvmfs_neg_check()
static int cvmfs_neg_check (const ngx_str_t * uri, time_t now) static
Definition at line 50 of file gate.c.
References cvmfs_neg, cvmfs_neg_hash(), CVMFS_NEG_SLOTS, and s.
Referenced by brix_cvmfs_gate().
cvmfs_neg_hash()
static uint64_t cvmfs_neg_hash (const ngx_str_t * uri) static
Definition at line 38 of file gate.c.
Referenced by cvmfs_neg_check(), and cvmfs_neg_store().
cvmfs_neg_store()
static void cvmfs_neg_store (const ngx_str_t * uri, time_t now, time_t ttl) static
Definition at line 59 of file gate.c.
References cvmfs_neg, cvmfs_neg_hash(), CVMFS_NEG_SLOTS, and s.
Referenced by brix_cvmfs_notify_status().
cvmfs_reject()
static ngx_int_t cvmfs_reject (ngx_http_request_t * r, ngx_uint_t status, const char * cause) static
Definition at line 82 of file gate.c.
References BRIX_CVMFS_CLASS_REJECT, BRIX_CVMFS_METRIC_INC, and brix_sanitize_log_string().
Referenced by brix_cvmfs_gate().
Variable Documentation
cvmfs_neg
cvmfs_neg_slot cvmfs_neg[512u] static
Definition at line 35 of file gate.c.
Referenced by cvmfs_neg_check(), and cvmfs_neg_store().