nginx-xrootd: src/protocols/cvmfs/geo.c File Reference
geo.c File Reference
#include "cvmfs.h"
#include "core/aio/aio.h"
#include "fs/cache/origin/s3_transport.h"
#include "fs/vfs/vfs_backend_registry.h"
Data Structures
struct cvmfs_pt_task_t
Macros
#define CVMFS_PT_RESP_MAX (64 * 1024) /* geo lists + manifests are tiny */
#define CVMFS_PT_TIMEOUT_MS 5000
Functions
static void cvmfs_pt_thread (void *data, ngx_log_t *log)
static void cvmfs_pt_done (ngx_event_t *ev)
ngx_int_t brix_cvmfs_geo_passthrough (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf)
Macro Definition Documentation
CVMFS_PT_RESP_MAX
#define CVMFS_PT_RESP_MAX (64 * 1024) /* geo lists + manifests are tiny */
Definition at line 22 of file geo.c.
CVMFS_PT_TIMEOUT_MS
#define CVMFS_PT_TIMEOUT_MS 5000
Definition at line 23 of file geo.c.
Function Documentation
brix_cvmfs_geo_passthrough()
ngx_int_t brix_cvmfs_geo_passthrough (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf)
Definition at line 111 of file geo.c.
References cvmfs_pt_task_t::body, brix_vfs_backend_http_endpoint(), ngx_http_brix_cvmfs_loc_conf_t::common, cvmfs_pt_done(), CVMFS_PT_RESP_MAX, cvmfs_pt_thread(), host, cvmfs_pt_task_t::host, ngx_http_brix_cvmfs_module, cvmfs_pt_task_t::path, port, cvmfs_pt_task_t::port, cvmfs_pt_task_t::r, ngx_http_brix_shared_conf_t::root_canon, ngx_http_brix_shared_conf_t::thread_pool, ngx_http_brix_shared_conf_t::thread_pool_name, tls, cvmfs_pt_task_t::tls, and ngx_http_brix_cvmfs_ctx_t::up_root.
Referenced by brix_cvmfs_gate(), and brix_cvmfs_geo_answer().
cvmfs_pt_done()
static void cvmfs_pt_done (ngx_event_t * ev) static
Definition at line 66 of file geo.c.
References cvmfs_pt_task_t::body, cvmfs_pt_task_t::body_len, c, ngx_pcalloc(), cvmfs_pt_task_t::r, and cvmfs_pt_task_t::status.
Referenced by brix_cvmfs_geo_passthrough().
cvmfs_pt_thread()
static void cvmfs_pt_thread (void * data, ngx_log_t * log) static
Definition at line 38 of file geo.c.
References cvmfs_pt_task_t::body, cvmfs_pt_task_t::body_len, brix_s3_origin_curl_transport, CVMFS_PT_RESP_MAX, CVMFS_PT_TIMEOUT_MS, cvmfs_pt_task_t::host, log, ngx_memcpy, cvmfs_pt_task_t::path, cvmfs_pt_task_t::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_body, brix_s3_transport_t::resp_free, brix_s3_resp_t::status, cvmfs_pt_task_t::status, and cvmfs_pt_task_t::tls.
Referenced by brix_cvmfs_geo_passthrough().