nginx-xrootd: src/protocols/cvmfs/geo_answer.c File Reference
geo_answer.c File Reference
#include "cvmfs.h"
#include "origin_geo.h"
#include "core/aio/aio.h"
#include "core/fnv.h"
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
Data Structures
struct cvmfs_geo_entry_t
struct cvmfs_geo_task_t
struct cvmfs_geo_slot_t
Macros
#define CVMFS_GEO_MAX_ENTRIES 64 /* hard cap on the parsed list */
#define CVMFS_GEO_PROBE_TIMEOUT_MS 1000 /* per-server connect probe budget */
#define CVMFS_GEO_CACHE_SLOTS 256u /* per-worker EWMA cache (pow2 mask) */
#define CVMFS_GEO_M_UNREACHABLE 1.0e12
#define CVMFS_GEO_M_UNPROBED 2.0e12
Functions
static uint64_t cvmfs_geo_key (const char *host, int port)
static int cvmfs_geo_port_allowed (int port)
static size_t cvmfs_geo_scan_host (const u_char *tok, size_t len, char *host, size_t host_size)
static int cvmfs_geo_scan_port (const u_char *tok, size_t len, size_t pos)
static void cvmfs_geo_parse_entry (const u_char *tok, size_t len, cvmfs_geo_entry_t *e)
static int cvmfs_geo_parse (ngx_http_request_t *r, cvmfs_geo_task_t *t, ngx_uint_t max_probe)
static void cvmfs_geo_cache_read (cvmfs_geo_task_t *t, time_t now)
static double cvmfs_geo_cache_fold (const cvmfs_geo_entry_t *e, time_t now)
static void cvmfs_geo_thread (void *data, ngx_log_t *log)
static void cvmfs_geo_render (cvmfs_geo_task_t *t, time_t now)
static void cvmfs_geo_done (ngx_event_t *ev)
ngx_int_t brix_cvmfs_geo_answer (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf)
Variables
static cvmfs_geo_slot_t cvmfs_geo_cache [256u]
Macro Definition Documentation
CVMFS_GEO_CACHE_SLOTS
#define CVMFS_GEO_CACHE_SLOTS 256u /* per-worker EWMA cache (pow2 mask) */
Definition at line 37 of file geo_answer.c.
CVMFS_GEO_M_UNPROBED
#define CVMFS_GEO_M_UNPROBED 2.0e12
Definition at line 43 of file geo_answer.c.
CVMFS_GEO_M_UNREACHABLE
#define CVMFS_GEO_M_UNREACHABLE 1.0e12
Definition at line 42 of file geo_answer.c.
CVMFS_GEO_MAX_ENTRIES
#define CVMFS_GEO_MAX_ENTRIES 64 /* hard cap on the parsed list */
Definition at line 35 of file geo_answer.c.
CVMFS_GEO_PROBE_TIMEOUT_MS
#define CVMFS_GEO_PROBE_TIMEOUT_MS 1000 /* per-server connect probe budget */
Definition at line 36 of file geo_answer.c.
Function Documentation
brix_cvmfs_geo_answer()
ngx_int_t brix_cvmfs_geo_answer (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf)
Definition at line 415 of file geo_answer.c.
References cvmfs_geo_task_t::body, brix_cvmfs_geo_passthrough(), ngx_http_brix_cvmfs_loc_conf_t::common, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, cvmfs_geo_cache_read(), cvmfs_geo_done(), cvmfs_geo_parse(), cvmfs_geo_thread(), brix_cvmfs_conf_t::geo_cache_ttl, brix_cvmfs_conf_t::geo_max_servers, cvmfs_geo_task_t::n, cvmfs_geo_task_t::r, ngx_http_brix_shared_conf_t::thread_pool, ngx_http_brix_shared_conf_t::thread_pool_name, and cvmfs_geo_task_t::ttl.
Referenced by brix_cvmfs_gate().
cvmfs_geo_cache_fold()
static double cvmfs_geo_cache_fold (const cvmfs_geo_entry_t * e, time_t now) static
Definition at line 299 of file geo_answer.c.
References cvmfs_geo_cache, CVMFS_GEO_CACHE_SLOTS, cvmfs_geo_key(), cvmfs_geo_entry_t::host, cvmfs_geo_entry_t::port, s, and cvmfs_geo_entry_t::sample_us.
Referenced by cvmfs_geo_render().
cvmfs_geo_cache_read()
static void cvmfs_geo_cache_read (cvmfs_geo_task_t * t, time_t now) static
Definition at line 273 of file geo_answer.c.
References cvmfs_geo_entry_t::cached_ewma, cvmfs_geo_cache, CVMFS_GEO_CACHE_SLOTS, cvmfs_geo_key(), cvmfs_geo_task_t::e, cvmfs_geo_entry_t::host, cvmfs_geo_task_t::n, cvmfs_geo_entry_t::need_probe, cvmfs_geo_entry_t::port, s, cvmfs_geo_task_t::ttl, and cvmfs_geo_entry_t::valid.
Referenced by brix_cvmfs_geo_answer().
cvmfs_geo_done()
static void cvmfs_geo_done (ngx_event_t * ev) static
Definition at line 378 of file geo_answer.c.
References cvmfs_geo_task_t::body, cvmfs_geo_task_t::body_len, c, cvmfs_geo_render(), ngx_pcalloc(), and cvmfs_geo_task_t::r.
Referenced by brix_cvmfs_geo_answer().
cvmfs_geo_key()
static uint64_t cvmfs_geo_key (const char * host, int port) static
Definition at line 75 of file geo_answer.c.
References BRIX_FNV1A64_OFFSET_BASIS, BRIX_FNV1A64_PRIME, host, and port.
Referenced by cvmfs_geo_cache_fold(), and cvmfs_geo_cache_read().
cvmfs_geo_parse()
static int cvmfs_geo_parse (ngx_http_request_t * r, cvmfs_geo_task_t * t, ngx_uint_t max_probe) static
Definition at line 237 of file geo_answer.c.
References CVMFS_GEO_MAX_ENTRIES, cvmfs_geo_parse_entry(), cvmfs_geo_task_t::e, cvmfs_geo_task_t::n, tok, and cvmfs_geo_entry_t::valid.
Referenced by brix_cvmfs_geo_answer().
cvmfs_geo_parse_entry()
static void cvmfs_geo_parse_entry (const u_char * tok, size_t len, cvmfs_geo_entry_t * e) static
Definition at line 206 of file geo_answer.c.
References cvmfs_geo_entry_t::cached_ewma, cvmfs_geo_port_allowed(), cvmfs_geo_scan_host(), cvmfs_geo_scan_port(), cvmfs_geo_entry_t::host, cvmfs_geo_entry_t::need_probe, port, cvmfs_geo_entry_t::port, cvmfs_geo_entry_t::sample_us, tok, and cvmfs_geo_entry_t::valid.
Referenced by cvmfs_geo_parse().
cvmfs_geo_port_allowed()
static int cvmfs_geo_port_allowed (int port) static
Definition at line 93 of file geo_answer.c.
References port.
Referenced by cvmfs_geo_parse_entry().
cvmfs_geo_render()
static void cvmfs_geo_render (cvmfs_geo_task_t * t, time_t now) static
Definition at line 335 of file geo_answer.c.
References cvmfs_geo_task_t::body, cvmfs_geo_task_t::body_len, brix_cvmfs_rank_by_metric(), cvmfs_geo_entry_t::cached_ewma, cvmfs_geo_cache_fold(), CVMFS_GEO_M_UNPROBED, CVMFS_GEO_M_UNREACHABLE, CVMFS_GEO_MAX_ENTRIES, cvmfs_geo_task_t::e, cvmfs_geo_task_t::n, cvmfs_geo_entry_t::need_probe, cvmfs_geo_entry_t::sample_us, and cvmfs_geo_entry_t::valid.
Referenced by cvmfs_geo_done().
cvmfs_geo_scan_host()
static size_t cvmfs_geo_scan_host (const u_char * tok, size_t len, char * host, size_t host_size) static
Definition at line 119 of file geo_answer.c.
References c, host, and tok.
Referenced by cvmfs_geo_parse_entry().
cvmfs_geo_scan_port()
static int cvmfs_geo_scan_port (const u_char * tok, size_t len, size_t pos) static
Definition at line 162 of file geo_answer.c.
References port, and tok.
Referenced by cvmfs_geo_parse_entry().
cvmfs_geo_thread()
static void cvmfs_geo_thread (void * data, ngx_log_t * log) static
Definition at line 317 of file geo_answer.c.
References brix_cvmfs_connect_rtt_us(), CVMFS_GEO_PROBE_TIMEOUT_MS, cvmfs_geo_task_t::e, cvmfs_geo_entry_t::host, log, cvmfs_geo_task_t::n, cvmfs_geo_entry_t::need_probe, cvmfs_geo_entry_t::port, cvmfs_geo_entry_t::sample_us, and cvmfs_geo_entry_t::valid.
Referenced by brix_cvmfs_geo_answer().
Variable Documentation
cvmfs_geo_cache
cvmfs_geo_slot_t cvmfs_geo_cache[256u] static
Definition at line 72 of file geo_answer.c.
Referenced by cvmfs_geo_cache_fold(), and cvmfs_geo_cache_read().