nginx-xrootd: client/lib/fs/glob.c File Reference
glob.c File Reference
#include "brix.h"
#include <fnmatch.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct glob_spec
struct glob_acc
Functions
int brix_has_glob (const char *s)
static int glob_parse_spec (const brix_url *u, glob_spec *sp, brix_status *st)
static int glob_match_entry (const brix_url *u, const glob_spec *sp, const char *name, char *full, size_t fullsz)
static int glob_acc_append (glob_acc *ac, const char *s)
static int glob_collect (const brix_url *u, const glob_spec *sp, const brix_dirent *ents, size_t ne, glob_acc *ac)
int brix_glob (const char *url, const brix_opts *co, char ***out, size_t *n_out, brix_status *st)
void brix_glob_free (char **arr, size_t n)
Function Documentation
brix_glob()
int brix_glob (const char * url, const brix_opts * co, char *** out, size_t * n_out, brix_status * st)
Definition at line 198 of file glob.c.
References glob_acc::arr, brix_close(), brix_connect(), brix_dirlist(), brix_glob_free(), brix_status_set(), brix_url_parse(), c, glob_spec::dir, glob_collect(), glob_parse_spec(), glob_acc::n, and XRDC_EPROTO.
Referenced by expand_source().
brix_glob_free()
void brix_glob_free (char ** arr, size_t n)
Definition at line 239 of file glob.c.
Referenced by brix_glob(), and expand_source().
brix_has_glob()
int brix_has_glob (const char * s)
Definition at line 24 of file glob.c.
References s.
Referenced by glob_parse_spec(), and source_has_glob().
glob_acc_append()
static int glob_acc_append (glob_acc * ac, const char * s) static
Definition at line 150 of file glob.c.
References glob_acc::arr, glob_acc::cap, glob_acc::n, and s.
Referenced by glob_collect().
glob_collect()
static int glob_collect (const brix_url * u, const glob_spec * sp, const brix_dirent * ents, size_t ne, glob_acc * ac) static
Definition at line 180 of file glob.c.
References glob_acc_append(), glob_match_entry(), name, and XRDC_PATH_MAX.
Referenced by brix_glob().
glob_match_entry()
static int glob_match_entry (const brix_url * u, const glob_spec * sp, const char * name, char * full, size_t fullsz) static
Definition at line 110 of file glob.c.
References glob_spec::dir, glob_spec::dsep, glob_spec::hb, glob_spec::he, brix_url::host, name, glob_spec::pattern, brix_url::port, and glob_spec::scheme.
Referenced by glob_collect().
glob_parse_spec()
static int glob_parse_spec (const brix_url * u, glob_spec * sp, brix_status * st) static
Definition at line 53 of file glob.c.
References brix_has_glob(), brix_status_set(), glob_spec::dir, glob_spec::dsep, glob_spec::hb, glob_spec::he, brix_url::host, brix_url::path, glob_spec::pattern, brix_url::scheme, glob_spec::scheme, XRDC_EUSAGE, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by brix_glob().