nginx-xrootd: src/auth/authz/acc/groups.c File Reference
groups.c File Reference
#include "acc.h"
#include "observability/metrics/metrics.h"
#include "observability/metrics/metrics_macros.h"
#include <pwd.h>
#include <grp.h>
#include <netdb.h>
#include <time.h>
Data Structures
struct acc_grp_cache_t
Macros
#define BRIX_ACC_MAX_RETRAN 32
#define ACC_GRP_CACHE_SLOTS 256
#define ACC_DJB2_SEED 5381 /* djb2 hash initial basis */
#define ACC_GRP_USER_MAX 128
#define ACC_NSS_NEG_TTL_SECS 60 /* negative-cache lifetime */
#define ACC_NSS_SLOW_MS 2000 /* a resolve over this is "slow" */
#define ACC_NSS_TRIP_COUNT 5 /* consecutive slow resolves → open */
#define ACC_NSS_COOLDOWN_SECS 10 /* breaker stays open this long */
Functions
void brix_acc_groups_set_gidlifetime (time_t secs)
void brix_acc_groups_set_primary_only (ngx_int_t on)
void brix_acc_groups_set_gidretran (const char *gidlist)
static int acc_gid_retran (gid_t gid)
void brix_acc_groups_set_nisdomain (const char *domain)
static int64_t acc_monotonic_ms (void)
static unsigned acc_user_hash (const char *user)
static void acc_cache_free (acc_grp_cache_t *e)
static int acc_resolve_unix (const char *user, char ***namesp)
static void acc_nss_note_latency (int64_t elapsed, time_t now)
static ngx_int_t acc_cache_refresh (acc_grp_cache_t *e, const char *user, time_t now)
static ngx_array_t * acc_cache_to_array (ngx_pool_t *pool, acc_grp_cache_t *e)
static ngx_array_t * brix_acc_unix_groups (ngx_pool_t *pool, const char *user)
static int brix_acc_in_netgroup (const char *netgroup, const char *user, const char *host)
void brix_acc_groups_init (void)
Variables
static time_t acc_gidlifetime = 43200
static int acc_primary_only = 0
static char acc_nisdomain [256] = ""
static gid_t acc_retrangid [32]
static int acc_retrancnt = 0
static acc_grp_cache_t acc_grp_cache [256]
struct {
int consecutive_slow
time_t open_until
} acc_nss_breaker
Macro Definition Documentation
ACC_DJB2_SEED
#define ACC_DJB2_SEED 5381 /* djb2 hash initial basis */
Definition at line 97 of file groups.c.
ACC_GRP_CACHE_SLOTS
#define ACC_GRP_CACHE_SLOTS 256
Definition at line 96 of file groups.c.
ACC_GRP_USER_MAX
#define ACC_GRP_USER_MAX 128
Definition at line 98 of file groups.c.
ACC_NSS_COOLDOWN_SECS
#define ACC_NSS_COOLDOWN_SECS 10 /* breaker stays open this long */
Definition at line 123 of file groups.c.
ACC_NSS_NEG_TTL_SECS
#define ACC_NSS_NEG_TTL_SECS 60 /* negative-cache lifetime */
Definition at line 120 of file groups.c.
ACC_NSS_SLOW_MS
#define ACC_NSS_SLOW_MS 2000 /* a resolve over this is "slow" */
Definition at line 121 of file groups.c.
ACC_NSS_TRIP_COUNT
#define ACC_NSS_TRIP_COUNT 5 /* consecutive slow resolves → open */
Definition at line 122 of file groups.c.
BRIX_ACC_MAX_RETRAN
#define BRIX_ACC_MAX_RETRAN 32
Definition at line 38 of file groups.c.
Function Documentation
acc_cache_free()
static void acc_cache_free (acc_grp_cache_t * e) static
Definition at line 151 of file groups.c.
References acc_grp_cache_t::count, acc_grp_cache_t::names, and acc_grp_cache_t::user.
Referenced by acc_cache_refresh().
acc_cache_refresh()
static ngx_int_t acc_cache_refresh (acc_grp_cache_t * e, const char * user, time_t now) static
Definition at line 276 of file groups.c.
References acc_cache_free(), acc_gidlifetime, acc_monotonic_ms(), acc_nss_breaker, ACC_NSS_NEG_TTL_SECS, acc_nss_note_latency(), acc_resolve_unix(), acc_grp_cache_t::count, acc_grp_cache_t::expiry, acc_grp_cache_t::names, ngx_memcpy, and acc_grp_cache_t::user.
Referenced by brix_acc_unix_groups().
acc_cache_to_array()
static ngx_array_t * acc_cache_to_array (ngx_pool_t * pool, acc_grp_cache_t * e) static
Definition at line 329 of file groups.c.
References acc_grp_cache_t::count, acc_grp_cache_t::names, ngx_memcpy, and ngx_pnalloc().
Referenced by brix_acc_unix_groups().
acc_gid_retran()
static int acc_gid_retran (gid_t gid) static
Definition at line 74 of file groups.c.
References acc_retrancnt, and acc_retrangid.
Referenced by acc_resolve_unix().
acc_monotonic_ms()
static int64_t acc_monotonic_ms (void) static
Definition at line 133 of file groups.c.
Referenced by acc_cache_refresh().
acc_nss_note_latency()
static void acc_nss_note_latency (int64_t elapsed, time_t now) static
Definition at line 231 of file groups.c.
References acc_nss_breaker, ACC_NSS_COOLDOWN_SECS, ACC_NSS_SLOW_MS, ACC_NSS_TRIP_COUNT, and BRIX_RESIL_METRIC_INC.
Referenced by acc_cache_refresh().
acc_resolve_unix()
static int acc_resolve_unix (const char * user, char *** namesp) static
Definition at line 166 of file groups.c.
References acc_gid_retran(), and acc_primary_only.
Referenced by acc_cache_refresh().
acc_user_hash()
static unsigned acc_user_hash (const char * user) static
Definition at line 143 of file groups.c.
References ACC_DJB2_SEED, and ACC_GRP_CACHE_SLOTS.
Referenced by brix_acc_unix_groups().
brix_acc_groups_init()
void brix_acc_groups_init (void)
Definition at line 392 of file groups.c.
References brix_acc_in_netgroup(), brix_acc_set_group_resolvers(), and brix_acc_unix_groups().
Referenced by brix_acc_build().
brix_acc_groups_set_gidlifetime()
void brix_acc_groups_set_gidlifetime (time_t secs)
Definition at line 42 of file groups.c.
References acc_gidlifetime.
Referenced by brix_acc_build().
brix_acc_groups_set_gidretran()
void brix_acc_groups_set_gidretran (const char * gidlist)
Definition at line 48 of file groups.c.
References acc_retrancnt, acc_retrangid, and BRIX_ACC_MAX_RETRAN.
Referenced by brix_acc_build().
brix_acc_groups_set_nisdomain()
void brix_acc_groups_set_nisdomain (const char * domain)
Definition at line 86 of file groups.c.
References acc_nisdomain, and ngx_memcpy.
Referenced by brix_acc_build().
brix_acc_groups_set_primary_only()
void brix_acc_groups_set_primary_only (ngx_int_t on)
Definition at line 43 of file groups.c.
References acc_primary_only.
Referenced by brix_acc_build().
brix_acc_in_netgroup()
static int brix_acc_in_netgroup (const char * netgroup, const char * user, const char * host) static
Definition at line 382 of file groups.c.
References acc_nisdomain.
Referenced by brix_acc_groups_init().
brix_acc_unix_groups()
static ngx_array_t * brix_acc_unix_groups (ngx_pool_t * pool, const char * user) static
Definition at line 354 of file groups.c.
References acc_cache_refresh(), acc_cache_to_array(), acc_grp_cache, ACC_GRP_USER_MAX, acc_user_hash(), acc_grp_cache_t::count, acc_grp_cache_t::expiry, and acc_grp_cache_t::user.
Referenced by brix_acc_groups_init().
Variable Documentation
acc_gidlifetime
time_t acc_gidlifetime = 43200 static
Definition at line 32 of file groups.c.
Referenced by acc_cache_refresh(), and brix_acc_groups_set_gidlifetime().
acc_grp_cache
acc_grp_cache_t acc_grp_cache[256] static
Definition at line 107 of file groups.c.
Referenced by brix_acc_unix_groups().
acc_nisdomain
char acc_nisdomain[256] = "" static
Definition at line 34 of file groups.c.
Referenced by brix_acc_groups_set_nisdomain(), and brix_acc_in_netgroup().
[struct]
struct { ... } acc_nss_breaker
Referenced by acc_cache_refresh(), and acc_nss_note_latency().
acc_primary_only
int acc_primary_only = 0 static
Definition at line 33 of file groups.c.
Referenced by acc_resolve_unix(), and brix_acc_groups_set_primary_only().
acc_retrancnt
int acc_retrancnt = 0 static
Definition at line 40 of file groups.c.
Referenced by acc_gid_retran(), and brix_acc_groups_set_gidretran().
acc_retrangid
gid_t acc_retrangid[32] static
Definition at line 39 of file groups.c.
Referenced by acc_gid_retran(), and brix_acc_groups_set_gidretran().
consecutive_slow
int consecutive_slow
Definition at line 126 of file groups.c.
open_until
time_t open_until
Definition at line 127 of file groups.c.