nginx-xrootd: src/auth/authz/group_policy.c File Reference
group_policy.c File Reference
#include "core/ngx_brix_module.h"
#include <errno.h>
#include <stddef.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include "fs/path/path_internal.h"
Functions
ngx_int_t brix_finalize_group_rules (ngx_log_t *log, const ngx_str_t *root, ngx_array_t *rules)
static mode_t brix_parent_group_mode_bits (const struct stat *parent, const struct stat *child)
static ngx_int_t brix_apply_parent_group_policy_impl (ngx_log_t *log, int fd, const char *path, ngx_array_t *rules)
ngx_int_t brix_apply_parent_group_policy_fd (ngx_log_t *log, int fd, const char *path, ngx_array_t *rules)
ngx_int_t brix_apply_parent_group_policy_path (ngx_log_t *log, const char *path, ngx_array_t *rules)
Function Documentation
brix_apply_parent_group_policy_fd()
ngx_int_t brix_apply_parent_group_policy_fd (ngx_log_t * log, int fd, const char * path, ngx_array_t * rules)
Definition at line 149 of file group_policy.c.
References brix_apply_parent_group_policy_impl(), and log.
Referenced by brix_open_resolved_file().
brix_apply_parent_group_policy_impl()
static ngx_int_t brix_apply_parent_group_policy_impl (ngx_log_t * log, int fd, const char * path, ngx_array_t * rules) static
Definition at line 49 of file group_policy.c.
References brix_find_group_rule(), brix_parent_group_mode_bits(), fstat(), log, PATH_MAX, and stat().
Referenced by brix_apply_parent_group_policy_fd(), and brix_apply_parent_group_policy_path().
brix_apply_parent_group_policy_path()
ngx_int_t brix_apply_parent_group_policy_path (ngx_log_t * log, const char * path, ngx_array_t * rules)
Definition at line 157 of file group_policy.c.
References brix_apply_parent_group_policy_impl(), and log.
Referenced by brix_handle_mkdir(), brix_mkdir_recursive_beneath(), brix_mkdir_recursive_confined_canon(), and brix_mkdir_recursive_policy().
brix_finalize_group_rules()
ngx_int_t brix_finalize_group_rules (ngx_log_t * log, const ngx_str_t * root, ngx_array_t * rules)
Definition at line 18 of file group_policy.c.
References brix_finalize_path_rules(), and log.
Referenced by brix_config_finalize_policy().
brix_parent_group_mode_bits()
static mode_t brix_parent_group_mode_bits (const struct stat * parent, const struct stat * child) static
Definition at line 30 of file group_policy.c.
Referenced by brix_apply_parent_group_policy_impl().