nginx-xrootd: src/tpc/gsi/gsi_outbound_common.c File Reference
gsi_outbound_common.c File Reference
#include "tpc/engine/tpc_internal.h"
#include "protocols/root/session/session.h"
#include "protocols/root/protocol/gsi.h"
#include "auth/token/file.h"
#include <stdio.h>
#include <errno.h>
Macros
#define TPC_BEARER_MAX 65536
#define TPC_GSI_MAX_BODY (256 * 1024)
Functions
void tpc_put_u32 (u_char *p, uint32_t v)
int tpc_send_kxr_auth (brix_tpc_pull_t *t, int fd, u_char stream_seq, const u_char *cred_payload, uint32_t cred_len)
static int tpc_read_bearer_token (brix_tpc_pull_t *t, u_char *buf, size_t buf_sz, size_t *out_len)
int tpc_outbound_ztn (brix_tpc_pull_t *t, int fd)
Macro Definition Documentation
TPC_BEARER_MAX
#define TPC_BEARER_MAX 65536
Definition at line 29 of file gsi_outbound_common.c.
TPC_GSI_MAX_BODY
#define TPC_GSI_MAX_BODY (256 * 1024)
Definition at line 30 of file gsi_outbound_common.c.
Function Documentation
tpc_outbound_ztn()
int tpc_outbound_ztn (brix_tpc_pull_t * t, int fd)
Definition at line 132 of file gsi_outbound_common.c.
References brix_tpc_pull_t::delegated_token, brix_tpc_pull_t::err_msg, kXR_AuthFailed, kXR_NoMemory, kXR_ok, kXR_ServerError, ngx_memcpy, TPC_BEARER_MAX, tpc_read_bearer_token(), tpc_recv_response(), tpc_send_kxr_auth(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_outbound_finish_login().
tpc_put_u32()
void tpc_put_u32 (u_char * p, uint32_t v)
Definition at line 35 of file gsi_outbound_common.c.
References ngx_memcpy.
tpc_read_bearer_token()
static int tpc_read_bearer_token (brix_tpc_pull_t * t, u_char * buf, size_t buf_sz, size_t * out_len) static
Definition at line 103 of file gsi_outbound_common.c.
References brix_token_read_file(), brix_tpc_pull_t::conf, brix_tpc_pull_t::err_msg, kXR_ArgInvalid, kXR_IOError, ngx_stream_brix_srv_conf_t::tpc_outbound_bearer_file, and brix_tpc_pull_t::xrd_error.
Referenced by tpc_outbound_ztn().
tpc_send_kxr_auth()
int tpc_send_kxr_auth (brix_tpc_pull_t * t, int fd, u_char stream_seq, const u_char * cred_payload, uint32_t cred_len)
Definition at line 52 of file gsi_outbound_common.c.
References ClientRequestHdr::body, ClientRequestHdr::dlen, brix_tpc_pull_t::err_msg, kXR_auth, kXR_ServerError, ngx_memcpy, ClientRequestHdr::requestid, ClientRequestHdr::streamid, tpc_send_all(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_outbound_gsi(), tpc_outbound_gsi_exchange(), and tpc_outbound_ztn().