nginx-xrootd: src/tpc/gsi/gsi_outbound_certreq.c File Reference
gsi_outbound_certreq.c File Reference
#include "tpc/engine/tpc_internal.h"
#include "auth/gsi/gsi_core.h"
#include "protocols/root/session/session.h"
#include "core/compat/cstr.h"
Functions
void tpc_put_u32 (u_char *p, uint32_t v)
int tpc_send_kxr_auth (brix_tpc_pull_t *t, int fd, u_char seq, const u_char *cred, uint32_t len)
int tpc_recv_response (brix_tpc_pull_t *t, int fd, uint16_t *status, u_char **body, uint32_t *dlen)
static int tpc_outbound_gsi_finish (int rc, BIO *cbio, BIO *kbio, STACK_OF(X509) *chain, EVP_PKEY *pkey, u_char *certreq, u_char *body)
int tpc_outbound_gsi (brix_tpc_pull_t *t, int fd, const u_char *login_body, uint32_t login_dlen)
Function Documentation
tpc_outbound_gsi()
int tpc_outbound_gsi (brix_tpc_pull_t * t, int fd, const u_char * login_body, uint32_t login_dlen)
Definition at line 49 of file gsi_outbound_certreq.c.
References brix_gsi_build_certreq(), brix_gsi_parse_parms(), brix_gsi_rand(), BRIX_SESSION_ID_LEN, brix_str_cbuf(), BRIX_TPC_CREDENTIAL_PROXY, brix_tpc_credential_validate(), brix_tpc_pull_t::c, ngx_stream_brix_srv_conf_t::certificate, ngx_stream_brix_srv_conf_t::certificate_key, brix_tpc_pull_t::conf, brix_tpc_pull_t::deleg_cred_len, brix_tpc_pull_t::deleg_cred_pem, brix_tpc_pull_t::err_msg, brix_tpc_pull_t::gsi_rtag, kXR_ArgInvalid, kXR_AuthFailed, kXR_authmore, kXR_IOError, kXR_NoMemory, kXR_ServerError, ngx_memcpy, PATH_MAX, brix_tpc_credential_t::proxy_pem, STACK_OF(), tpc_outbound_gsi_exchange(), tpc_outbound_gsi_finish(), tpc_recv_response(), tpc_send_kxr_auth(), brix_tpc_credential_t::type, and brix_tpc_pull_t::xrd_error.
Referenced by tpc_outbound_finish_login().
tpc_outbound_gsi_finish()
static int tpc_outbound_gsi_finish (int rc, BIO * cbio, BIO * kbio, STACK_OF(X509) * chain, EVP_PKEY * pkey, u_char * certreq, u_char * body) static
Definition at line 35 of file gsi_outbound_certreq.c.
Referenced by tpc_outbound_gsi().
tpc_put_u32()
void tpc_put_u32 (u_char * p, uint32_t v) extern
Definition at line 35 of file gsi_outbound_common.c.
tpc_recv_response()
int tpc_recv_response (brix_tpc_pull_t * t, int fd, uint16_t * status, u_char ** body, uint32_t * dlen)
Definition at line 119 of file io.c.
Referenced by tpc_outbound_gsi().
tpc_send_kxr_auth()
int tpc_send_kxr_auth (brix_tpc_pull_t * t, int fd, u_char seq, const u_char * cred, uint32_t len) extern
Definition at line 52 of file gsi_outbound_common.c.
Referenced by tpc_outbound_gsi().