nginx-xrootd: src/auth/gsi/gsi_core.c File Reference
gsi_core.c File Reference
#include "gsi_core_internal.h"
Functions
void brix_gsi_parse_parms (const char *parms, uint32_t *version, char *crypto, size_t cryptosz, char *ca, size_t casz)
uint8_t * brix_gsi_build_certreq (const char *cryptomod, uint32_t version, const char *issuer_hash, uint32_t clnt_opts, const uint8_t *rtag, size_t rtaglen, size_t *outlen)
EVP_PKEY * gsi_cresp_cert_pubkey (const uint8_t *pem, size_t len)
char * gsi_cresp_export_pubkey_pem (EVP_PKEY *key, size_t *outlen)
size_t gsi_cresp_pick_md_alg (const uint8_t *sbody, uint32_t slen, char *out, size_t outcap)
int gsi_cresp_fail (gsi_cresp_ctx *x, char *err, size_t errcap, const char *msg)
int brix_gsi_build_cert_response_ex (const uint8_t *sbody, uint32_t slen, const uint8_t *proxy_pem, size_t proxy_pem_len, EVP_PKEY *proxy_key, uint8_t **payload, uint32_t *plen, uint8_t *out_key, size_t *out_keylen, char *out_cipher, size_t out_cipher_cap, int *out_use_iv, char *err, size_t errcap)
int brix_gsi_build_cert_response (const uint8_t *sbody, uint32_t slen, const uint8_t *proxy_pem, size_t proxy_pem_len, EVP_PKEY *proxy_key, uint8_t **payload, uint32_t *plen, char *err, size_t errcap)
int brix_gsi_sigver_required (uint16_t op, int level)
void brix_gsi_sigver_seqno_be (uint64_t seq, uint8_t out[8])
int brix_gsi_sigver_hmac (const uint8_t key[32], uint64_t seqno, const uint8_t hdr24[24], const uint8_t *payload, size_t plen, int nodata, uint8_t mac_out[32])
Variables
const char brix_gsi_dh_params_pem []
const char *const gsi_cipher_allow []
Function Documentation
brix_gsi_build_cert_response()
int brix_gsi_build_cert_response (const uint8_t * sbody, uint32_t slen, const uint8_t * proxy_pem, size_t proxy_pem_len, EVP_PKEY * proxy_key, uint8_t ** payload, uint32_t * plen, char * err, size_t errcap)
Definition at line 447 of file gsi_core.c.
References brix_gsi_build_cert_response_ex().
Referenced by brix_cache_origin_auth_gsi(), and tpc_outbound_gsi_exchange().
brix_gsi_build_cert_response_ex()
int brix_gsi_build_cert_response_ex (const uint8_t * sbody, uint32_t slen, const uint8_t * proxy_pem, size_t proxy_pem_len, EVP_PKEY * proxy_key, uint8_t ** payload, uint32_t * plen, uint8_t * out_key, size_t * out_keylen, char * out_cipher, size_t out_cipher_cap, int * out_use_iv, char * err, size_t errcap)
Definition at line 224 of file gsi_core.c.
References brix_gbuf_bucket(), brix_gbuf_end(), brix_gbuf_init(), brix_gbuf_start(), brix_gsi_cipher_encrypt(), brix_gsi_cipher_keygen_from(), brix_gsi_cipher_lookup(), brix_gsi_cipher_parse_peer(), brix_gsi_cipher_pick(), brix_gsi_cipher_public(), brix_gsi_cipher_session_key(), brix_gsi_find_bucket(), BRIX_GSI_MAX_KEY, brix_gsi_rand(), brix_gsi_rsa_decrypt_public(), brix_gsi_rsa_encrypt_private(), brix_gsi_rsa_sign_raw(), gsi_cresp_ctx::cpub, gsi_cresp_ctx::enc, brix_gbuf::err, gsi_cresp_cert_pubkey(), gsi_cresp_export_pubkey_pem(), gsi_cresp_fail(), gsi_cresp_pick_md_alg(), gsi_cresp_ctx::inner, brix_gsi_cipher_t::iv_len, brix_gsi_cipher_t::key_len, kXGC_cert, kXRS_cipher, kXRS_cipher_alg, kXRS_cryptomod, kXRS_main, kXRS_md_alg, kXRS_puk, kXRS_rtag, kXRS_signed_rtag, kXRS_x509, brix_gbuf::len, gsi_cresp_ctx::mine, gsi_cresp_ctx::outer, brix_gbuf::p, gsi_cresp_ctx::peer, gsi_cresp_ctx::peerblob, gsi_cresp_ctx::pubpem, gsi_cresp_ctx::servpub, gsi_cresp_ctx::signed_cpub, gsi_cresp_ctx::signed_cpub_len, gsi_cresp_ctx::signed_rtag, and gsi_cresp_ctx::signed_rtag_len.
Referenced by brix_gsi_build_cert_response(), and gsi_more().
brix_gsi_build_certreq()
uint8_t * brix_gsi_build_certreq (const char * cryptomod, uint32_t version, const char * issuer_hash, uint32_t clnt_opts, const uint8_t * rtag, size_t rtaglen, size_t * outlen)
Definition at line 80 of file gsi_core.c.
References brix_gbuf_bucket(), brix_gbuf_end(), brix_gbuf_free(), brix_gbuf_init(), brix_gbuf_start(), brix_gbuf::err, kXGC_certreq, kXRS_clnt_opts, kXRS_cryptomod, kXRS_issuer_hash, kXRS_main, kXRS_rtag, kXRS_version, brix_gbuf::len, and brix_gbuf::p.
Referenced by brix_cache_origin_auth_gsi(), gsi_first(), and tpc_outbound_gsi().
brix_gsi_parse_parms()
void brix_gsi_parse_parms (const char * parms, uint32_t * version, char * crypto, size_t cryptosz, char * ca, size_t casz)
Definition at line 29 of file gsi_core.c.
Referenced by brix_cache_origin_auth_gsi(), gsi_first(), and tpc_outbound_gsi().
brix_gsi_sigver_hmac()
int brix_gsi_sigver_hmac (const uint8_t key[32], uint64_t seqno, const uint8_t hdr24[24], const uint8_t * payload, size_t plen, int nodata, uint8_t mac_out[32])
Definition at line 500 of file gsi_core.c.
References brix_gsi_sigver_seqno_be(), brix_hmac_sha256(), and key.
Referenced by brix_sigver_maybe(), and brix_verify_sigver_hmac().
brix_gsi_sigver_required()
int brix_gsi_sigver_required (uint16_t op, int level)
Definition at line 462 of file gsi_core.c.
References kXR_auth, kXR_bind, kXR_chkpoint, kXR_chmod, kXR_clone, kXR_endsess, kXR_fattr, kXR_login, kXR_mkdir, kXR_mv, kXR_open, kXR_pgwrite, kXR_ping, kXR_protocol, kXR_rm, kXR_rmdir, kXR_sigver, kXR_truncate, kXR_write, and kXR_writev.
Referenced by brix_sigver_maybe(), and brix_sigver_opcode_requires().
brix_gsi_sigver_seqno_be()
void brix_gsi_sigver_seqno_be (uint64_t seq, uint8_t out[8])
Definition at line 486 of file gsi_core.c.
Referenced by brix_gsi_sigver_hmac().
gsi_cresp_cert_pubkey()
EVP_PKEY * gsi_cresp_cert_pubkey (const uint8_t * pem, size_t len)
Definition at line 124 of file gsi_core.c.
Referenced by brix_gsi_build_cert_response_ex().
gsi_cresp_export_pubkey_pem()
char * gsi_cresp_export_pubkey_pem (EVP_PKEY * key, size_t * outlen)
Definition at line 141 of file gsi_core.c.
References key.
Referenced by brix_gsi_build_cert_response_ex().
gsi_cresp_fail()
int gsi_cresp_fail (gsi_cresp_ctx * x, char * err, size_t errcap, const char * msg)
Definition at line 203 of file gsi_core.c.
References brix_gbuf_free(), gsi_cresp_ctx::cpub, gsi_cresp_ctx::enc, gsi_cresp_ctx::inner, gsi_cresp_ctx::mine, gsi_cresp_ctx::outer, gsi_cresp_ctx::peer, gsi_cresp_ctx::peerblob, gsi_cresp_ctx::pubpem, gsi_cresp_ctx::servpub, gsi_cresp_ctx::signed_cpub, and gsi_cresp_ctx::signed_rtag.
Referenced by brix_gsi_build_cert_response_ex().
gsi_cresp_pick_md_alg()
size_t gsi_cresp_pick_md_alg (const uint8_t * sbody, uint32_t slen, char * out, size_t outcap)
Definition at line 166 of file gsi_core.c.
References brix_gsi_find_bucket(), and kXRS_md_alg.
Referenced by brix_gsi_build_cert_response_ex().
Variable Documentation
brix_gsi_dh_params_pem
const char brix_gsi_dh_params_pem[]
Initial value:
=
"-----BEGIN DH PARAMETERS-----\n"
"MIIBiAKCAYEAzcEAf3ZCkm0FxJLgKd1YoT16Hietl7QV8VgJNc5CYKmRu/gKylxT\n"
"MVZJqtUmoh2IvFHCfbTGEmZM5LdVaZfMLQf7yXjecg0nSGklYZeQQ3P0qshFLbI9\n"
"u3z1XhEeCbEZPq84WWwXacSAAxwwRRrN5nshgAavqvyDiGNi+GqYpqGPb9JE38R3\n"
"GJ51FTPutZlvQvEycjCbjyajhpItBB+XvIjWj2GQyvi+cqB0WrPQAsxCOPrBTCZL\n"
"OjM0NfJ7PQfllw3RDQev2u1Q+Rt8QyScJQCFUj/SWoxpw2ydpWdgAkrqTmdVYrev\n"
"x5AoXE52cVIC8wfOxaaJ4cBpnJui3Y0jZcOQj0FtC0wf4WcBpHnLLBzKSOQwbxts\n"
"WE8LkskPnwwrup/HqWimFFg40bC9F5Lm3CTDCb45mtlBxi3DydIbRLFhGAjlKzV3\n"
"s9G3opHwwfgXpFf3+zg7NPV3g1//HLgWCvooOvMqaO+X7+lXczJJLMafEaarcAya\n"
"Kyo8PGKIAORrAgEF\n"
"-----END DH PARAMETERS-----\n"
Definition at line 7 of file gsi_core.c.
Referenced by gsi_fixed_dh_params().
gsi_cipher_allow
const char* const gsi_cipher_allow[]
Initial value:
= {
    "aes-128-cbc", "aes-256-cbc", "bf-cbc", "des-ede3-cbc", NULL
}
Definition at line 20 of file gsi_core.c.
Referenced by brix_gsi_cipher_lookup().