nginx-xrootd: src/auth/gsi/gsi_dh.c File Reference
gsi_dh.c File Reference
#include "gsi_core_internal.h"
Functions
EVP_PKEY * brix_gsi_dh_keygen (void)
BIGNUM * brix_gsi_dh_pub_decode (const uint8_t *blob, size_t len)
char * brix_gsi_dh_pub_encode (EVP_PKEY *dh)
EVP_PKEY * brix_gsi_dh_build_peer (EVP_PKEY *mine, BIGNUM *peer_pub)
uint8_t * brix_gsi_dh_derive (EVP_PKEY *mine, EVP_PKEY *peer, size_t *slen)
EVP_PKEY * gsi_fixed_dh_params (void)
EVP_PKEY * gsi_dh_keygen_with (EVP_PKEY *dhparams)
Function Documentation
brix_gsi_dh_build_peer()
EVP_PKEY * brix_gsi_dh_build_peer (EVP_PKEY * mine, BIGNUM * peer_pub)
Definition at line 91 of file gsi_dh.c.
Referenced by brix_gsi_build_peer_dh_key().
brix_gsi_dh_derive()
uint8_t * brix_gsi_dh_derive (EVP_PKEY * mine, EVP_PKEY * peer, size_t * slen)
Definition at line 128 of file gsi_dh.c.
brix_gsi_dh_keygen()
EVP_PKEY * brix_gsi_dh_keygen (void)
Definition at line 9 of file gsi_dh.c.
Referenced by brix_gsi_keypool_init(), brix_kp_refill_thread(), and gsi_build_dh_public().
brix_gsi_dh_pub_decode()
BIGNUM * brix_gsi_dh_pub_decode (const uint8_t * blob, size_t len)
Definition at line 34 of file gsi_dh.c.
References hex(), and s.
Referenced by brix_gsi_parse_client_dh_public_key().
brix_gsi_dh_pub_encode()
char * brix_gsi_dh_pub_encode (EVP_PKEY * dh)
Definition at line 66 of file gsi_dh.c.
References hex().
gsi_dh_keygen_with()
EVP_PKEY * gsi_dh_keygen_with (EVP_PKEY * dhparams)
Definition at line 177 of file gsi_dh.c.
References gsi_fixed_dh_params(), and key.
Referenced by brix_gsi_cipher_keygen(), and brix_gsi_cipher_keygen_from().
gsi_fixed_dh_params()
EVP_PKEY * gsi_fixed_dh_params (void)
Definition at line 161 of file gsi_dh.c.
References brix_gsi_dh_params_pem.
Referenced by gsi_dh_keygen_with().