nginx-xrootd: src/net/proxy/gsi_upstream_login.c File Reference
gsi_upstream_login.c File Reference
#include "proxy_internal.h"
#include "gsi_upstream.h"
#include "fs/cache/cache_internal.h"
#include "core/aio/aio.h"
#include "protocols/root/connection/event_sched.h"
#include "core/compat/af_policy.h"
#include <unistd.h>
Data Structures
struct proxy_gsi_login_t
Functions
static void proxy_gsi_login_thread (void *data, ngx_log_t *log)
static ngx_int_t proxy_gsi_promote_fd (brix_proxy_ctx_t *proxy, int fd)
static void proxy_gsi_login_done (ngx_event_t *ev)
ngx_int_t brix_proxy_gsi_connect_async (brix_proxy_ctx_t *proxy, ngx_stream_brix_srv_conf_t *conf, ngx_str_t *host, uint16_t port)
Function Documentation
brix_proxy_gsi_connect_async()
ngx_int_t brix_proxy_gsi_connect_async (brix_proxy_ctx_t * proxy, ngx_stream_brix_srv_conf_t * conf, ngx_str_t * host, uint16_t port)
Definition at line 182 of file gsi_upstream_login.c.
References BRIX_AF_AUTO, brix_proxy_gsi_write_pem_temp(), c, proxy_gsi_login_t::client_conn, proxy_gsi_login_t::deleg_path, brix_ctx_gsi_t::deleg_proxy_len, brix_ctx_gsi_t::deleg_proxy_pem, proxy_gsi_login_t::family, brix_ctx_t::gsi, proxy_gsi_login_t::gsi_store, host, proxy_gsi_login_t::host, proxy_gsi_login_t::log, port, proxy_gsi_login_t::port, proxy_gsi_login_t::proxy, proxy_gsi_login_done(), proxy_gsi_login_thread(), proxy_gsi_login_t::result_fd, and XRD_ST_PROXY.
Referenced by brix_proxy_connect().
proxy_gsi_login_done()
static void proxy_gsi_login_done (ngx_event_t * ev) static
Definition at line 143 of file gsi_upstream_login.c.
References brix_proxy_abort(), brix_proxy_dispatch_pending(), brix_schedule_read_resume(), proxy_gsi_login_t::deleg_path, proxy_gsi_login_t::proxy, proxy_gsi_promote_fd(), proxy_gsi_login_t::result_fd, and XRD_ST_REQ_HEADER.
Referenced by brix_proxy_gsi_connect_async().
proxy_gsi_login_thread()
static void proxy_gsi_login_thread (void * data, ngx_log_t * log) static
Definition at line 52 of file gsi_upstream_login.c.
References brix_cache_origin_bootstrap(), brix_cache_origin_close(), brix_cache_origin_connect(), brix_cache_fill_t::conf, proxy_gsi_login_t::deleg_path, proxy_gsi_login_t::family, brix_cache_origin_conn_t::fd, proxy_gsi_login_t::gsi_store, proxy_gsi_login_t::host, log, proxy_gsi_login_t::port, proxy_gsi_login_t::result_fd, brix_cache_origin_conn_t::ssl, and brix_cache_origin_conn_t::ssl_ctx.
Referenced by brix_proxy_gsi_connect_async().
proxy_gsi_promote_fd()
static ngx_int_t proxy_gsi_promote_fd (brix_proxy_ctx_t * proxy, int fd) static
Definition at line 98 of file gsi_upstream_login.c.
References brix_proxy_read_handler(), brix_proxy_write_handler(), and XRD_PX_IDLE.
Referenced by proxy_gsi_login_done().