nginx-xrootd: src/auth/gsi/gsi_rsa.c File Reference
gsi_rsa.c File Reference
#include "gsi_core_internal.h"
Functions
int brix_gsi_rand (uint8_t *out, size_t n)
size_t brix_gsi_rsa_sign_raw (EVP_PKEY *key, const uint8_t *in, size_t inlen, uint8_t *out)
size_t brix_gsi_rsa_encrypt_private (EVP_PKEY *key, const uint8_t *in, size_t inlen, uint8_t *out, size_t outmax)
size_t brix_gsi_rsa_decrypt_public (EVP_PKEY *key, const uint8_t *in, size_t inlen, uint8_t *out, size_t outmax)
Function Documentation
brix_gsi_rand()
int brix_gsi_rand (uint8_t * out, size_t n)
Definition at line 10 of file gsi_rsa.c.
Referenced by brix_cache_origin_auth_gsi(), brix_gsi_begin_delegation(), brix_gsi_build_cert_response_ex(), gsi_first(), and tpc_outbound_gsi().
brix_gsi_rsa_decrypt_public()
size_t brix_gsi_rsa_decrypt_public (EVP_PKEY * key, const uint8_t * in, size_t inlen, uint8_t * out, size_t outmax)
Definition at line 78 of file gsi_rsa.c.
References key.
Referenced by brix_gsi_build_cert_response_ex(), and gsi_recover_peer_signed().
brix_gsi_rsa_encrypt_private()
size_t brix_gsi_rsa_encrypt_private (EVP_PKEY * key, const uint8_t * in, size_t inlen, uint8_t * out, size_t outmax)
Definition at line 42 of file gsi_rsa.c.
References key.
Referenced by brix_gsi_begin_delegation(), brix_gsi_build_cert_response_ex(), brix_gsi_rsa_sign_raw(), and brix_gsi_send_cert().
brix_gsi_rsa_sign_raw()
size_t brix_gsi_rsa_sign_raw (EVP_PKEY * key, const uint8_t * in, size_t inlen, uint8_t * out)
Definition at line 26 of file gsi_rsa.c.
References brix_gsi_rsa_encrypt_private(), and key.
Referenced by brix_gsi_build_cert_response_ex().