nginx-xrootd: src/auth/crypto/gsi_verify.c File Reference
gsi_verify.c File Reference
#include "gsi_verify.h"
#include "auth/crypto/store_policy.h"
#include "core/compat/log_diag.h"
#include <openssl/x509v3.h>
#include <string.h>
Functions
static ngx_int_t brix_gsi_enforce_proxy_monotonicity (X509_STORE_CTX *vctx, ngx_log_t *log)
static ngx_int_t brix_gsi_enforce_signing_policy (X509_STORE_CTX *vctx, ngx_log_t *log)
static ngx_int_t brix_gsi_enforce_cert_policy (X509_STORE_CTX *vctx, X509 *leaf, ngx_log_t *log, int client_purpose)
ngx_int_t brix_gsi_verify_chain (ngx_log_t *log, X509_STORE *store, X509 *leaf, STACK_OF(X509) *untrusted, ngx_uint_t verify_depth, brix_gsi_verify_result_t *res, int client_purpose)
Function Documentation
brix_gsi_enforce_cert_policy()
static ngx_int_t brix_gsi_enforce_cert_policy (X509_STORE_CTX * vctx, X509 * leaf, ngx_log_t * log, int client_purpose) static
Definition at line 116 of file gsi_verify.c.
References brix_cert_policy_violation(), brix_leaf_purpose_violation(), brix_proxy_pci_ok(), log, and STACK_OF().
Referenced by brix_gsi_verify_chain().
brix_gsi_enforce_proxy_monotonicity()
static ngx_int_t brix_gsi_enforce_proxy_monotonicity (X509_STORE_CTX * vctx, ngx_log_t * log) static
Definition at line 40 of file gsi_verify.c.
References brix_proxy_chain_ok(), and log.
Referenced by brix_gsi_verify_chain().
brix_gsi_enforce_signing_policy()
static ngx_int_t brix_gsi_enforce_signing_policy (X509_STORE_CTX * vctx, ngx_log_t * log) static
Definition at line 64 of file gsi_verify.c.
References BRIX_SP_MODE_OFF, brix_sp_table_check(), brix_store_policy_mode(), brix_store_policy_table(), brix_x509_oneline(), log, mode, and STACK_OF().
Referenced by brix_gsi_verify_chain().
brix_gsi_verify_chain()
ngx_int_t brix_gsi_verify_chain (ngx_log_t * log, X509_STORE * store, X509 * leaf, STACK_OF(X509) * untrusted, ngx_uint_t verify_depth, brix_gsi_verify_result_t * res, int client_purpose)
Definition at line 163 of file gsi_verify.c.
References BRIX_DIAG_WARN, brix_gsi_enforce_cert_policy(), brix_gsi_enforce_proxy_monotonicity(), brix_gsi_enforce_signing_policy(), brix_gsi_verify_result_t::dn_buf, and log.
Referenced by brix_handle_auth_inner(), and webdav_verify_proxy_cert().