nginx-xrootd: src/tpc/gsi/gsi_outbound_exchange.c File Reference
gsi_outbound_exchange.c File Reference
#include "tpc/engine/tpc_internal.h"
#include "protocols/root/session/session.h"
#include "protocols/root/protocol/gsi.h"
#include "auth/gsi/gsi_core.h"
#include <stdio.h>
#include <ctype.h>
#include <errno.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <openssl/ssl.h>
#include <openssl/err.h>
#include <openssl/bio.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/dh.h>
#include <openssl/bn.h>
#include <openssl/evp.h>
#include <openssl/core_names.h>
#include <openssl/param_build.h>
Data Structures
struct tpc_gsi_round2_t
Functions
static int tpc_gsi_exchange_cleanup (int rc, u_char *body, BIO *chain_bio, u_char *payload)
static int tpc_gsi_verify_server_cert (brix_tpc_pull_t *t, const u_char *body, uint32_t dlen)
static int tpc_gsi_build_round2 (brix_tpc_pull_t *t, tpc_gsi_round2_t *r)
int tpc_outbound_gsi_exchange (brix_tpc_pull_t *t, int fd, u_char *body, uint32_t dlen, X509 *x, STACK_OF(X509) *chain, EVP_PKEY *pkey, u_char *certreq, BIO *cbio, BIO *kbio)
Function Documentation
tpc_gsi_build_round2()
static int tpc_gsi_build_round2 (brix_tpc_pull_t * t, tpc_gsi_round2_t * r) static
Definition at line 163 of file gsi_outbound_exchange.c.
References tpc_gsi_round2_t::body, brix_gsi_build_cert_response(), tpc_gsi_round2_t::dlen, brix_tpc_pull_t::err_msg, kXR_NoMemory, kXR_NotAuthorized, and brix_tpc_pull_t::xrd_error.
Referenced by tpc_outbound_gsi_exchange().
tpc_gsi_exchange_cleanup()
static int tpc_gsi_exchange_cleanup (int rc, u_char * body, BIO * chain_bio, u_char * payload) static
Definition at line 59 of file gsi_outbound_exchange.c.
Referenced by tpc_outbound_gsi_exchange().
tpc_gsi_verify_server_cert()
static int tpc_gsi_verify_server_cert (brix_tpc_pull_t * t, const u_char * body, uint32_t dlen) static
Definition at line 82 of file gsi_outbound_exchange.c.
References brix_tpc_pull_t::conf, brix_tpc_pull_t::err_msg, gsi_find_bucket(), kXR_NotAuthorized, kXRS_x509, and brix_tpc_pull_t::xrd_error.
Referenced by tpc_outbound_gsi_exchange().
tpc_outbound_gsi_exchange()
int tpc_outbound_gsi_exchange (brix_tpc_pull_t * t, int fd, u_char * body, uint32_t dlen, X509 * x, STACK_OF(X509) * chain, EVP_PKEY * pkey, u_char * certreq, BIO * cbio, BIO * kbio)
Definition at line 203 of file gsi_outbound_exchange.c.
References brix_tpc_pull_t::err_msg, kXR_AuthFailed, kXR_ok, kXR_ServerError, tpc_gsi_build_round2(), tpc_gsi_exchange_cleanup(), tpc_gsi_verify_server_cert(), tpc_recv_response(), tpc_send_kxr_auth(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_outbound_gsi().