nginx-xrootd: src/auth/gssapi/gsi_mech.c File Reference
gsi_mech.c File Reference
#include "gsi_mech.h"
#include "auth/gsi/proxy_req.h"
#include "auth/crypto/gsi_verify.h"
#include <openssl/bio.h>
#include <openssl/pem.h>
Data Structures
struct brix_gssapi_srv_t
Enumerations
enum {
ST_TLS = 0 , ST_WAIT_D , ST_WAIT_SIGNED , ST_DONE ,
ST_FAIL
}
Functions
static int gss_verify_cb (int preverify_ok, X509_STORE_CTX *ctx)
static void gss_cleanup (void *data)
static ngx_int_t gss_drain (brix_gssapi_srv_t *g, ngx_str_t *out)
static ngx_int_t gss_read_all (brix_gssapi_srv_t *g, size_t cap, ngx_str_t *out)
static ngx_int_t gss_x509_pem (brix_gssapi_srv_t *g, X509 *x, ngx_str_t *out)
static ngx_int_t gss_chain_pem (brix_gssapi_srv_t *g, STACK_OF(X509) *chain, ngx_str_t *out)
static ngx_int_t gss_verify_peer (brix_gssapi_srv_t *g)
static brix_gss_status_e gss_send_proxy_req (brix_gssapi_srv_t *g, ngx_str_t *out)
static brix_gss_status_e gss_recv_signed (brix_gssapi_srv_t *g, ngx_str_t *out)
brix_gssapi_srv_t * brix_gssapi_srv_create (ngx_pool_t *pool, ngx_log_t *log, SSL_CTX *ssl_ctx, X509_STORE *ca_store, unsigned accept_deleg)
brix_gss_status_e brix_gssapi_srv_step (brix_gssapi_srv_t *g, const u_char *in, size_t in_len, ngx_str_t *out)
ngx_int_t brix_gssapi_srv_peer (brix_gssapi_srv_t *g, ngx_str_t *dn_out, ngx_str_t *proxy_pem_out)
ngx_int_t brix_gssapi_srv_peer_cert_pem (brix_gssapi_srv_t *g, ngx_str_t *out)
ngx_int_t brix_gssapi_wrap (brix_gssapi_srv_t *g, const u_char *in, size_t in_len, ngx_str_t *out)
ngx_int_t brix_gssapi_unwrap (brix_gssapi_srv_t *g, const u_char *in, size_t in_len, ngx_str_t *out)
void brix_gssapi_srv_free (brix_gssapi_srv_t *g)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ST_TLS
ST_WAIT_D
ST_WAIT_SIGNED
ST_DONE
ST_FAIL
Definition at line 21 of file gsi_mech.c.
Function Documentation
brix_gssapi_srv_create()
brix_gssapi_srv_t * brix_gssapi_srv_create (ngx_pool_t * pool, ngx_log_t * log, SSL_CTX * ssl_ctx, X509_STORE * ca_store, unsigned accept_deleg)
Definition at line 347 of file gsi_mech.c.
References gss_cleanup(), gss_verify_cb(), log, ngx_pcalloc(), and ST_TLS.
Referenced by brix_ftp_ev_cmd_auth().
brix_gssapi_srv_free()
void brix_gssapi_srv_free (brix_gssapi_srv_t * g)
Definition at line 534 of file gsi_mech.c.
References gss_cleanup().
brix_gssapi_srv_peer()
ngx_int_t brix_gssapi_srv_peer (brix_gssapi_srv_t * g, ngx_str_t * dn_out, ngx_str_t * proxy_pem_out)
Definition at line 477 of file gsi_mech.c.
Referenced by ev_gss_finalize().
brix_gssapi_srv_peer_cert_pem()
ngx_int_t brix_gssapi_srv_peer_cert_pem (brix_gssapi_srv_t * g, ngx_str_t * out)
Definition at line 491 of file gsi_mech.c.
References gss_x509_pem().
Referenced by ev_gss_finalize().
brix_gssapi_srv_step()
brix_gss_status_e brix_gssapi_srv_step (brix_gssapi_srv_t * g, const u_char * in, size_t in_len, ngx_str_t * out)
Definition at line 397 of file gsi_mech.c.
References BRIX_GSS_COMPLETE, BRIX_GSS_CONTINUE, BRIX_GSS_FAILED, gss_drain(), gss_read_all(), gss_recv_signed(), gss_send_proxy_req(), gss_verify_peer(), s, ST_DONE, ST_FAIL, ST_TLS, ST_WAIT_D, and ST_WAIT_SIGNED.
Referenced by brix_ftp_ev_cmd_adat().
brix_gssapi_unwrap()
ngx_int_t brix_gssapi_unwrap (brix_gssapi_srv_t * g, const u_char * in, size_t in_len, ngx_str_t * out)
Definition at line 523 of file gsi_mech.c.
References gss_read_all().
Referenced by brix_ftp_ev_cmd_protected().
brix_gssapi_wrap()
ngx_int_t brix_gssapi_wrap (brix_gssapi_srv_t * g, const u_char * in, size_t in_len, ngx_str_t * out)
Definition at line 512 of file gsi_mech.c.
References gss_drain().
Referenced by ev_reply_wrapped().
gss_chain_pem()
static ngx_int_t gss_chain_pem (brix_gssapi_srv_t * g, STACK_OF(X509) * chain, ngx_str_t * out) static
Definition at line 173 of file gsi_mech.c.
References ngx_memcpy.
Referenced by gss_recv_signed().
gss_cleanup()
static void gss_cleanup (void * data) static
Definition at line 60 of file gsi_mech.c.
Referenced by brix_gssapi_srv_create(), and brix_gssapi_srv_free().
gss_drain()
static ngx_int_t gss_drain (brix_gssapi_srv_t * g, ngx_str_t * out) static
Definition at line 77 of file gsi_mech.c.
Referenced by brix_gssapi_srv_step(), brix_gssapi_wrap(), gss_recv_signed(), and gss_send_proxy_req().
gss_read_all()
static ngx_int_t gss_read_all (brix_gssapi_srv_t * g, size_t cap, ngx_str_t * out) static
Definition at line 107 of file gsi_mech.c.
Referenced by brix_gssapi_srv_step(), brix_gssapi_unwrap(), and gss_recv_signed().
gss_recv_signed()
static brix_gss_status_e gss_recv_signed (brix_gssapi_srv_t * g, ngx_str_t * out) static
Definition at line 289 of file gsi_mech.c.
References brix_gsi_assemble_proxy(), BRIX_GSS_COMPLETE, BRIX_GSS_FAILED, brix_gsi_blob_t::data, brix_gsi_buf_t::data, gss_chain_pem(), gss_drain(), gss_read_all(), gss_x509_pem(), brix_gsi_blob_t::len, brix_gsi_buf_t::len, ngx_memcpy, ngx_pnalloc(), and ST_DONE.
Referenced by brix_gssapi_srv_step().
gss_send_proxy_req()
static brix_gss_status_e gss_send_proxy_req (brix_gssapi_srv_t * g, ngx_str_t * out) static
Definition at line 249 of file gsi_mech.c.
References brix_gsi_build_pxyreq(), BRIX_GSS_CONTINUE, BRIX_GSS_FAILED, brix_gsi_blob_t::data, brix_gsi_buf_t::data, gss_drain(), gss_x509_pem(), brix_gsi_blob_t::len, brix_gsi_buf_t::len, and ST_WAIT_SIGNED.
Referenced by brix_gssapi_srv_step().
gss_verify_cb()
static int gss_verify_cb (int preverify_ok, X509_STORE_CTX * ctx) static
Definition at line 51 of file gsi_mech.c.
Referenced by brix_gssapi_srv_create().
gss_verify_peer()
static ngx_int_t gss_verify_peer (brix_gssapi_srv_t * g) static
Definition at line 214 of file gsi_mech.c.
References brix_gsi_verify_chain(), brix_gsi_verify_result_t::dn_buf, ngx_memcpy, ngx_pnalloc(), and STACK_OF().
Referenced by brix_gssapi_srv_step().
gss_x509_pem()
static ngx_int_t gss_x509_pem (brix_gssapi_srv_t * g, X509 * x, ngx_str_t * out) static
Definition at line 138 of file gsi_mech.c.
References ngx_memcpy.
Referenced by brix_gssapi_srv_peer_cert_pem(), gss_recv_signed(), and gss_send_proxy_req().