nginx-xrootd: src/auth/gsi/gsi_cipher.c File Reference
gsi_cipher.c File Reference
#include "gsi_core_internal.h"
#include "core/compat/openssl_auto.h"
Functions
EVP_PKEY * brix_gsi_cipher_keygen (void)
EVP_PKEY * brix_gsi_cipher_keygen_from (EVP_PKEY *peer)
char * brix_gsi_cipher_public (EVP_PKEY *dh, size_t *outlen)
EVP_PKEY * brix_gsi_cipher_parse_peer (const uint8_t *buf, size_t len)
const char * brix_gsi_cipher_default_list (void)
void gsi_load_legacy_once (void)
int brix_gsi_cipher_lookup (const char *name, brix_gsi_cipher_t *out)
int brix_gsi_cipher_pick (const char *offered, brix_gsi_cipher_t *out, char chosen[24])
int brix_gsi_cipher_session_key (EVP_PKEY *mine, EVP_PKEY *peer, int padded, uint8_t *key, int key_len)
uint8_t * brix_gsi_cipher_encrypt (const brix_gsi_cipher_t *c, const uint8_t *key, const uint8_t *in, size_t inlen, int use_iv, size_t *outlen)
uint8_t * brix_gsi_cipher_decrypt (const brix_gsi_cipher_t *c, const uint8_t *key, const uint8_t *in, size_t inlen, int use_iv, size_t *outlen)
Function Documentation
brix_gsi_cipher_decrypt()
uint8_t * brix_gsi_cipher_decrypt (const brix_gsi_cipher_t * c, const uint8_t * key, const uint8_t * in, size_t inlen, int use_iv, size_t * outlen)
Definition at line 300 of file gsi_cipher.c.
References BRIX_GSI_MAX_IV, c, key, and XRD_AUTO.
Referenced by brix_gsi_handle_sigpxy(), gsi_sigpxy(), pwd_round2(), and STACK_OF().
brix_gsi_cipher_default_list()
const char * brix_gsi_cipher_default_list (void)
Definition at line 134 of file gsi_cipher.c.
Referenced by gsi_build_cipher_alg_list().
brix_gsi_cipher_encrypt()
uint8_t * brix_gsi_cipher_encrypt (const brix_gsi_cipher_t * c, const uint8_t * key, const uint8_t * in, size_t inlen, int use_iv, size_t * outlen)
Definition at line 256 of file gsi_cipher.c.
References BRIX_GSI_MAX_IV, c, key, and XRD_AUTO.
Referenced by brix_gsi_begin_delegation(), brix_gsi_build_cert_response_ex(), gsi_sigpxy(), and pwd_more().
brix_gsi_cipher_keygen()
EVP_PKEY * brix_gsi_cipher_keygen (void)
Definition at line 10 of file gsi_cipher.c.
References gsi_dh_keygen_with().
Referenced by pwd_first().
brix_gsi_cipher_keygen_from()
EVP_PKEY * brix_gsi_cipher_keygen_from (EVP_PKEY * peer)
Definition at line 17 of file gsi_cipher.c.
References gsi_dh_keygen_with().
Referenced by brix_gsi_build_cert_response_ex(), and pwd_round1().
brix_gsi_cipher_lookup()
int brix_gsi_cipher_lookup (const char * name, brix_gsi_cipher_t * out)
Definition at line 155 of file gsi_cipher.c.
References BRIX_GSI_MAX_IV, BRIX_GSI_MAX_KEY, brix_gsi_cipher_t::evp, gsi_cipher_allow, gsi_load_legacy_once(), brix_gsi_cipher_t::iv_len, brix_gsi_cipher_t::key_len, and name.
Referenced by brix_gsi_build_cert_response_ex(), brix_gsi_cipher_pick(), gsi_build_cipher_alg_list(), gsi_session_cipher(), gsi_sigpxy(), pwd_more(), pwd_round2(), and STACK_OF().
brix_gsi_cipher_parse_peer()
EVP_PKEY * brix_gsi_cipher_parse_peer (const uint8_t * buf, size_t len)
Definition at line 66 of file gsi_cipher.c.
References hex().
Referenced by brix_gsi_build_cert_response_ex(), gsi_recover_peer_signed(), pwd_more(), and pwd_round1().
brix_gsi_cipher_pick()
int brix_gsi_cipher_pick (const char * offered, brix_gsi_cipher_t * out, char chosen[24])
Definition at line 188 of file gsi_cipher.c.
References brix_gsi_cipher_lookup(), and name.
Referenced by brix_gsi_build_cert_response_ex().
brix_gsi_cipher_public()
char * brix_gsi_cipher_public (EVP_PKEY * dh, size_t * outlen)
Definition at line 27 of file gsi_cipher.c.
Referenced by brix_gsi_build_cert_response_ex(), pwd_first(), and pwd_send_credsreq().
brix_gsi_cipher_session_key()
int brix_gsi_cipher_session_key (EVP_PKEY * mine, EVP_PKEY * peer, int padded, uint8_t * key, int key_len)
Definition at line 220 of file gsi_cipher.c.
References BRIX_GSI_MAX_KEY, and key.
Referenced by brix_gsi_build_cert_response_ex(), pwd_more(), and pwd_round1().
gsi_load_legacy_once()
void gsi_load_legacy_once (void)
Definition at line 143 of file gsi_cipher.c.
Referenced by brix_gsi_cipher_lookup().