nginx-xrootd: src/auth/gsi/gsi_core_internal.h File Reference
gsi_core_internal.h File Reference
#include "gsi_core.h"
#include <arpa/inet.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <openssl/core_names.h>
#include <openssl/param_build.h>
#include <openssl/dh.h>
#include <openssl/rand.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
#include <openssl/evp.h>
#include <openssl/rsa.h>
#include "protocols/root/protocol/gsi.h"
#include "protocols/root/protocol/opcodes.h"
#include "core/compat/crypto.h"
Data Structures
struct gsi_cresp_ctx
Functions
EVP_PKEY * gsi_fixed_dh_params (void)
EVP_PKEY * gsi_dh_keygen_with (EVP_PKEY *dhparams)
void gsi_load_legacy_once (void)
EVP_PKEY * gsi_cresp_cert_pubkey (const uint8_t *pem, size_t len)
char * gsi_cresp_export_pubkey_pem (EVP_PKEY *key, size_t *outlen)
size_t gsi_cresp_pick_md_alg (const uint8_t *sbody, uint32_t slen, char *out, size_t outcap)
int gsi_cresp_fail (gsi_cresp_ctx *x, char *err, size_t errcap, const char *msg)
Variables
const char brix_gsi_dh_params_pem []
const char *const gsi_cipher_allow []
Function Documentation
gsi_cresp_cert_pubkey()
EVP_PKEY * gsi_cresp_cert_pubkey (const uint8_t * pem, size_t len)
Definition at line 124 of file gsi_core.c.
Referenced by brix_gsi_build_cert_response_ex().
gsi_cresp_export_pubkey_pem()
char * gsi_cresp_export_pubkey_pem (EVP_PKEY * key, size_t * outlen)
Definition at line 141 of file gsi_core.c.
References key.
Referenced by brix_gsi_build_cert_response_ex().
gsi_cresp_fail()
int gsi_cresp_fail (gsi_cresp_ctx * x, char * err, size_t errcap, const char * msg)
Definition at line 203 of file gsi_core.c.
References brix_gbuf_free(), gsi_cresp_ctx::cpub, gsi_cresp_ctx::enc, gsi_cresp_ctx::inner, gsi_cresp_ctx::mine, gsi_cresp_ctx::outer, gsi_cresp_ctx::peer, gsi_cresp_ctx::peerblob, gsi_cresp_ctx::pubpem, gsi_cresp_ctx::servpub, gsi_cresp_ctx::signed_cpub, and gsi_cresp_ctx::signed_rtag.
Referenced by brix_gsi_build_cert_response_ex().
gsi_cresp_pick_md_alg()
size_t gsi_cresp_pick_md_alg (const uint8_t * sbody, uint32_t slen, char * out, size_t outcap)
Definition at line 166 of file gsi_core.c.
References brix_gsi_find_bucket(), and kXRS_md_alg.
Referenced by brix_gsi_build_cert_response_ex().
gsi_dh_keygen_with()
EVP_PKEY * gsi_dh_keygen_with (EVP_PKEY * dhparams)
Definition at line 177 of file gsi_dh.c.
References gsi_fixed_dh_params(), and key.
Referenced by brix_gsi_cipher_keygen(), and brix_gsi_cipher_keygen_from().
gsi_fixed_dh_params()
EVP_PKEY * gsi_fixed_dh_params (void)
Definition at line 161 of file gsi_dh.c.
References brix_gsi_dh_params_pem.
Referenced by gsi_dh_keygen_with().
gsi_load_legacy_once()
void gsi_load_legacy_once (void)
Definition at line 143 of file gsi_cipher.c.
Referenced by brix_gsi_cipher_lookup().
Variable Documentation
brix_gsi_dh_params_pem
const char brix_gsi_dh_params_pem[] extern
Definition at line 7 of file gsi_core.c.
Referenced by gsi_fixed_dh_params().
gsi_cipher_allow
const char* const gsi_cipher_allow[] extern
Definition at line 20 of file gsi_core.c.
Referenced by brix_gsi_cipher_lookup().