nginx-xrootd: src/auth/gsi/gsi_internal.h File Reference
gsi_internal.h File Reference
#include "core/ngx_brix_module.h"
Functions
ngx_int_t brix_gsi_send_cert (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_handle_token_auth (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_handle_sss_auth (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_gsi_complete_auth (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t gsi_auth_step_cert (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_gsi_complete_auth()
ngx_int_t brix_gsi_complete_auth (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 55 of file auth.c.
References brix_ctx_login_t::auth_done, BRIX_ATOMIC_INC, BRIX_AUTHN_GSI, brix_gsi_inflight_release(), brix_identity_set_dn(), brix_identity_set_vos_csv(), brix_metrics_shared(), BRIX_OP_AUTH, brix_rate_limit_check(), BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_sanitize_log_string(), brix_send_error(), brix_session_register(), brix_track_unique_user(), brix_track_vo_activity(), BRIX_VO_MAX_TRACKED, BRIX_VO_NAME_LEN, c, brix_ctx_login_t::dn, brix_ctx_t::identity, kXR_NoMemory, kXR_NotAuthorized, brix_ctx_t::login, ngx_brix_vo_slot_t::name, brix_ctx_login_t::peer_ip, brix_ctx_login_t::primary_vo, ngx_brix_vo_slot_t::requests_total, brix_ctx_login_t::sessid, ngx_brix_vo_global_t::slots, ngx_brix_metrics_t::vo_global, and brix_ctx_login_t::vo_list.
Referenced by gsi_auth_step_cert(), and gsi_auth_step_sigpxy().
brix_gsi_send_cert()
ngx_int_t brix_gsi_send_cert (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 509 of file cert_response.c.
References c, gsi_cert_chunks_t::calg_len, gsi_cert_chunks_t::cert_len, gsi_cert_chunks_t::cert_pem, gsi_cert_chunks_t::cipher_alg, gsi_build_cipher_alg_list(), gsi_build_dh_public(), gsi_build_main_container(), gsi_frame_cert_response(), gsi_record_handshake_opts(), gsi_select_dh_public_bucket(), gsi_sign_client_rtag(), gsi_cert_chunks_t::main_buf, gsi_cert_chunks_t::main_len, gsi_cert_chunks_t::malg_len, gsi_cert_chunks_t::md_alg, ngx_stream_brix_module, gsi_cert_chunks_t::pub_data, gsi_cert_chunks_t::pub_len, gsi_cert_chunks_t::puk_len, and brix_ctx_t::session.
Referenced by gsi_auth_step_certreq().
brix_handle_sss_auth()
ngx_int_t brix_handle_sss_auth (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 356 of file auth_request.c.
References c, sss_cred_t::clear, sss_cred_t::clear_span, sss_cred_t::id, sss_cred_t::key, sss_cred_t::replied_rc, sss_map_identity(), sss_recv_cred(), and sss_reply().
brix_handle_token_auth()
ngx_int_t brix_handle_token_auth (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 521 of file token.c.
References brix_log_access(), BRIX_OP_AUTH, BRIX_OP_ERR, BRIX_RETURN_OK, brix_send_error(), c, tokenauth_state_t::claims, kXR_NotAuthorized, brix_token_claims_t::sub, tokenauth_bind_session(), tokenauth_extract(), tokenauth_map_identity(), and tokenauth_validate().
gsi_auth_step_cert()
ngx_int_t gsi_auth_step_cert (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 249 of file auth_cert.c.
References brix_gsi_begin_delegation(), brix_gsi_complete_auth(), brix_ocsp_check_cert(), BRIX_OP_AUTH, BRIX_RETURN_ERR, c, brix_ctx_gsi_t::deleg_await, brix_ctx_gsi_t::dh_key, brix_ctx_t::gsi, gsi_cert_capture_dn(), gsi_cert_deny(), gsi_cert_extract_voms(), gsi_cert_verify(), gsi_promote_fullproxy(), kXR_NotAuthorized, brix_ctx_gsi_t::sess_keylen, and STACK_OF().
Referenced by brix_handle_auth_inner().