nginx-xrootd: src/auth/gsi/gsi_core.h File Reference
gsi_core.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <openssl/evp.h>
#include <openssl/bn.h>
Data Structures
struct brix_gbuf
struct brix_gsi_cipher_t
Macros
#define BRIX_GSI_MAX_KEY 32 /* largest session key (aes-256) */
#define BRIX_GSI_MAX_IV 16 /* largest IV (AES); bf/3des use 8 */
Functions
int brix_gsi_find_bucket (const uint8_t *buf, size_t len, uint32_t type, const uint8_t **out, size_t *outlen)
void brix_gbuf_init (brix_gbuf *g)
void brix_gbuf_free (brix_gbuf *g)
void brix_gbuf_raw (brix_gbuf *g, const void *data, size_t n)
void brix_gbuf_u32 (brix_gbuf *g, uint32_t v)
void brix_gbuf_start (brix_gbuf *g, uint32_t step)
void brix_gbuf_bucket (brix_gbuf *g, uint32_t type, const void *d, size_t n)
void brix_gbuf_end (brix_gbuf *g)
EVP_PKEY * brix_gsi_dh_keygen (void)
BIGNUM * brix_gsi_dh_pub_decode (const uint8_t *blob, size_t len)
char * brix_gsi_dh_pub_encode (EVP_PKEY *dh)
EVP_PKEY * brix_gsi_dh_build_peer (EVP_PKEY *mine, BIGNUM *peer_pub)
uint8_t * brix_gsi_dh_derive (EVP_PKEY *mine, EVP_PKEY *peer, size_t *slen)
EVP_PKEY * brix_gsi_cipher_keygen (void)
EVP_PKEY * brix_gsi_cipher_keygen_from (EVP_PKEY *peer)
char * brix_gsi_cipher_public (EVP_PKEY *dh, size_t *outlen)
EVP_PKEY * brix_gsi_cipher_parse_peer (const uint8_t *buf, size_t len)
const char * brix_gsi_cipher_default_list (void)
int brix_gsi_cipher_lookup (const char *name, brix_gsi_cipher_t *out)
int brix_gsi_cipher_pick (const char *offered, brix_gsi_cipher_t *out, char chosen[24])
int brix_gsi_cipher_session_key (EVP_PKEY *mine, EVP_PKEY *peer, int padded, uint8_t *key, int key_len)
uint8_t * brix_gsi_cipher_encrypt (const brix_gsi_cipher_t *c, const uint8_t *key, const uint8_t *in, size_t inlen, int use_iv, size_t *outlen)
uint8_t * brix_gsi_cipher_decrypt (const brix_gsi_cipher_t *c, const uint8_t *key, const uint8_t *in, size_t inlen, int use_iv, size_t *outlen)
int brix_gsi_rand (uint8_t *out, size_t n)
size_t brix_gsi_rsa_sign_raw (EVP_PKEY *key, const uint8_t *in, size_t inlen, uint8_t *out)
size_t brix_gsi_rsa_encrypt_private (EVP_PKEY *key, const uint8_t *in, size_t inlen, uint8_t *out, size_t outmax)
size_t brix_gsi_rsa_decrypt_public (EVP_PKEY *key, const uint8_t *in, size_t inlen, uint8_t *out, size_t outmax)
void brix_gsi_parse_parms (const char *parms, uint32_t *version, char *crypto, size_t cryptosz, char *ca, size_t casz)
uint8_t * brix_gsi_build_certreq (const char *cryptomod, uint32_t version, const char *issuer_hash, uint32_t clnt_opts, const uint8_t *rtag, size_t rtaglen, size_t *outlen)
int brix_gsi_build_cert_response (const uint8_t *sbody, uint32_t slen, const uint8_t *proxy_pem, size_t proxy_pem_len, EVP_PKEY *proxy_key, uint8_t **payload, uint32_t *plen, char *err, size_t errcap)
int brix_gsi_build_cert_response_ex (const uint8_t *sbody, uint32_t slen, const uint8_t *proxy_pem, size_t proxy_pem_len, EVP_PKEY *proxy_key, uint8_t **payload, uint32_t *plen, uint8_t *out_key, size_t *out_keylen, char *out_cipher, size_t out_cipher_cap, int *out_use_iv, char *err, size_t errcap)
int brix_gsi_sigver_required (uint16_t opcode, int level)
void brix_gsi_sigver_seqno_be (uint64_t seq, uint8_t out[8])
int brix_gsi_sigver_hmac (const uint8_t key[32], uint64_t seqno, const uint8_t hdr24[24], const uint8_t *payload, size_t plen, int nodata, uint8_t mac_out[32])
Macro Definition Documentation
BRIX_GSI_MAX_IV
#define BRIX_GSI_MAX_IV 16 /* largest IV (AES); bf/3des use 8 */
Definition at line 68 of file gsi_core.h.
BRIX_GSI_MAX_KEY
#define BRIX_GSI_MAX_KEY 32 /* largest session key (aes-256) */
Definition at line 67 of file gsi_core.h.
Function Documentation
brix_gbuf_bucket()
void brix_gbuf_bucket (brix_gbuf * g, uint32_t type, const void * d, size_t n)
Definition at line 113 of file gsi_buf.c.
References brix_gbuf_raw(), and brix_gbuf_u32().
Referenced by brix_gsi_begin_delegation(), brix_gsi_build_certreq(), gsi_add_fullproxy_bucket(), gsi_cresp_add_signed_public(), gsi_cresp_build_inner(), gsi_cresp_build_outer(), gsi_sigpxy(), pwd_first(), pwd_more(), and pwd_send_credsreq().
brix_gbuf_end()
void brix_gbuf_end (brix_gbuf * g)
Definition at line 122 of file gsi_buf.c.
References brix_gbuf_u32(), and kXRS_none.
Referenced by brix_gsi_begin_delegation(), brix_gsi_build_certreq(), gsi_cresp_build_inner(), gsi_cresp_build_outer(), gsi_sigpxy(), pwd_first(), pwd_more(), and pwd_send_credsreq().
brix_gbuf_free()
void brix_gbuf_free (brix_gbuf * g)
Definition at line 63 of file gsi_buf.c.
References brix_gbuf::cap, brix_gbuf::len, and brix_gbuf::p.
Referenced by bdg_fail(), brix_gsi_build_certreq(), gsi_cresp_fail(), gsi_sigpxy(), pwd_first(), pwd_more(), and pwd_send_credsreq().
brix_gbuf_init()
void brix_gbuf_init (brix_gbuf * g)
Definition at line 53 of file gsi_buf.c.
References brix_gbuf::cap, brix_gbuf::err, brix_gbuf::len, and brix_gbuf::p.
Referenced by brix_gsi_begin_delegation(), brix_gsi_build_cert_response_ex(), brix_gsi_build_certreq(), gsi_sigpxy(), pwd_first(), pwd_more(), and pwd_send_credsreq().
brix_gbuf_raw()
void brix_gbuf_raw (brix_gbuf * g, const void * data, size_t n)
Definition at line 72 of file gsi_buf.c.
References brix_gbuf::cap, brix_gbuf::err, brix_gbuf::len, and brix_gbuf::p.
Referenced by brix_gbuf_bucket(), brix_gbuf_start(), brix_gbuf_u32(), pwd_first(), pwd_more(), and pwd_send_credsreq().
brix_gbuf_start()
void brix_gbuf_start (brix_gbuf * g, uint32_t step)
Definition at line 105 of file gsi_buf.c.
References brix_gbuf_raw(), and brix_gbuf_u32().
Referenced by brix_gsi_begin_delegation(), brix_gsi_build_certreq(), gsi_cresp_build_inner(), gsi_cresp_build_outer(), and gsi_sigpxy().
brix_gbuf_u32()
void brix_gbuf_u32 (brix_gbuf * g, uint32_t v)
Definition at line 97 of file gsi_buf.c.
References brix_gbuf_raw().
Referenced by brix_gbuf_bucket(), brix_gbuf_end(), brix_gbuf_start(), pwd_first(), pwd_more(), and pwd_send_credsreq().
brix_gsi_build_cert_response()
int brix_gsi_build_cert_response (const uint8_t * sbody, uint32_t slen, const uint8_t * proxy_pem, size_t proxy_pem_len, EVP_PKEY * proxy_key, uint8_t ** payload, uint32_t * plen, char * err, size_t errcap)
Definition at line 493 of file gsi_core_cresp.c.
References brix_gsi_build_cert_response_ex().
Referenced by originauth_gsi_send_response(), and tpc_gsi_build_round2().
brix_gsi_build_cert_response_ex()
int brix_gsi_build_cert_response_ex (const uint8_t * sbody, uint32_t slen, const uint8_t * proxy_pem, size_t proxy_pem_len, EVP_PKEY * proxy_key, uint8_t ** payload, uint32_t * plen, uint8_t * out_key, size_t * out_keylen, char * out_cipher, size_t out_cipher_cap, int * out_use_iv, char * err, size_t errcap)
Definition at line 431 of file gsi_core_cresp.c.
References brix_gbuf_init(), gsi_cresp_state_t::err, gsi_cresp_state_t::errcap, gsi_cresp_agree_session_key(), gsi_cresp_build_inner(), gsi_cresp_build_outer(), gsi_cresp_choose_cipher(), gsi_cresp_extract_peer_pub(), gsi_cresp_fail(), gsi_cresp_sign_server_tag(), gsi_cresp_state_fail(), gsi_cresp_ctx::inner, brix_gbuf::len, gsi_cresp_state_t::out_cipher, gsi_cresp_state_t::out_cipher_cap, gsi_cresp_state_t::out_key, gsi_cresp_state_t::out_keylen, gsi_cresp_state_t::out_use_iv, gsi_cresp_ctx::outer, brix_gbuf::p, gsi_cresp_state_t::proxy_key, gsi_cresp_state_t::proxy_pem, gsi_cresp_state_t::proxy_pem_len, gsi_cresp_state_t::res, gsi_cresp_state_t::sbody, and gsi_cresp_state_t::slen.
Referenced by brix_gsi_build_cert_response(), and gsi_more().
brix_gsi_build_certreq()
uint8_t * brix_gsi_build_certreq (const char * cryptomod, uint32_t version, const char * issuer_hash, uint32_t clnt_opts, const uint8_t * rtag, size_t rtaglen, size_t * outlen)
Definition at line 120 of file gsi_core.c.
References brix_gbuf_bucket(), brix_gbuf_end(), brix_gbuf_free(), brix_gbuf_init(), brix_gbuf_start(), brix_gbuf::err, kXGC_certreq, kXRS_clnt_opts, kXRS_cryptomod, kXRS_issuer_hash, kXRS_main, kXRS_rtag, kXRS_version, brix_gbuf::len, and brix_gbuf::p.
Referenced by gsi_first(), originauth_gsi_certreq(), and tpc_certreq_build_send().
brix_gsi_cipher_decrypt()
uint8_t * brix_gsi_cipher_decrypt (const brix_gsi_cipher_t * c, const uint8_t * key, const uint8_t * in, size_t inlen, int use_iv, size_t * outlen)
Definition at line 303 of file gsi_cipher.c.
References BRIX_GSI_MAX_IV, c, key, and XRD_AUTO.
Referenced by brix_gsi_handle_sigpxy(), gsi_sigpxy(), pwd_round2(), and STACK_OF().
brix_gsi_cipher_default_list()
const char * brix_gsi_cipher_default_list (void)
Definition at line 137 of file gsi_cipher.c.
Referenced by gsi_build_cipher_alg_list().
brix_gsi_cipher_encrypt()
uint8_t * brix_gsi_cipher_encrypt (const brix_gsi_cipher_t * c, const uint8_t * key, const uint8_t * in, size_t inlen, int use_iv, size_t * outlen)
Definition at line 259 of file gsi_cipher.c.
References BRIX_GSI_MAX_IV, c, key, and XRD_AUTO.
Referenced by brix_gsi_begin_delegation(), gsi_cresp_build_inner(), gsi_sigpxy(), and pwd_more().
brix_gsi_cipher_keygen()
EVP_PKEY * brix_gsi_cipher_keygen (void)
Definition at line 10 of file gsi_cipher.c.
References gsi_dh_keygen_with().
Referenced by pwd_first().
brix_gsi_cipher_keygen_from()
EVP_PKEY * brix_gsi_cipher_keygen_from (EVP_PKEY * peer)
Definition at line 17 of file gsi_cipher.c.
References gsi_dh_keygen_with().
Referenced by gsi_cresp_agree_session_key(), and pwd_round1().
brix_gsi_cipher_lookup()
int brix_gsi_cipher_lookup (const char * name, brix_gsi_cipher_t * out)
Definition at line 158 of file gsi_cipher.c.
References BRIX_GSI_MAX_IV, BRIX_GSI_MAX_KEY, brix_gsi_cipher_t::evp, gsi_cipher_allow, gsi_load_legacy_once(), brix_gsi_cipher_t::iv_len, brix_gsi_cipher_t::key_len, and name.
Referenced by brix_gsi_cipher_pick(), gsi_build_cipher_alg_list(), gsi_cresp_choose_cipher(), gsi_session_cipher(), gsi_signed_select_key(), gsi_sigpxy(), pwd_more(), and pwd_round2().
brix_gsi_cipher_parse_peer()
EVP_PKEY * brix_gsi_cipher_parse_peer (const uint8_t * buf, size_t len)
Definition at line 69 of file gsi_cipher.c.
References hex().
Referenced by gsi_cresp_agree_session_key(), gsi_recover_peer_signed(), pwd_more(), and pwd_round1().
brix_gsi_cipher_pick()
int brix_gsi_cipher_pick (const char * offered, brix_gsi_cipher_t * out, char chosen[24])
Definition at line 191 of file gsi_cipher.c.
References brix_gsi_cipher_lookup(), and name.
Referenced by gsi_cresp_choose_cipher().
brix_gsi_cipher_public()
char * brix_gsi_cipher_public (EVP_PKEY * dh, size_t * outlen)
Definition at line 27 of file gsi_cipher.c.
Referenced by gsi_cresp_build_outer(), pwd_first(), and pwd_send_credsreq().
brix_gsi_cipher_session_key()
int brix_gsi_cipher_session_key (EVP_PKEY * mine, EVP_PKEY * peer, int padded, uint8_t * key, int key_len)
Definition at line 223 of file gsi_cipher.c.
References BRIX_GSI_MAX_KEY, and key.
Referenced by gsi_cresp_agree_session_key(), pwd_more(), and pwd_round1().
brix_gsi_dh_build_peer()
EVP_PKEY * brix_gsi_dh_build_peer (EVP_PKEY * mine, BIGNUM * peer_pub)
Definition at line 91 of file gsi_dh.c.
Referenced by brix_gsi_build_peer_dh_key().
brix_gsi_dh_derive()
uint8_t * brix_gsi_dh_derive (EVP_PKEY * mine, EVP_PKEY * peer, size_t * slen)
Definition at line 128 of file gsi_dh.c.
brix_gsi_dh_keygen()
EVP_PKEY * brix_gsi_dh_keygen (void)
Definition at line 9 of file gsi_dh.c.
Referenced by brix_gsi_keypool_init(), brix_kp_refill_thread(), and gsi_build_dh_public().
brix_gsi_dh_pub_decode()
BIGNUM * brix_gsi_dh_pub_decode (const uint8_t * blob, size_t len)
Definition at line 34 of file gsi_dh.c.
References hex(), and s.
Referenced by brix_gsi_parse_client_dh_public_key().
brix_gsi_dh_pub_encode()
char * brix_gsi_dh_pub_encode (EVP_PKEY * dh)
Definition at line 66 of file gsi_dh.c.
References hex().
brix_gsi_find_bucket()
int brix_gsi_find_bucket (const uint8_t * buf, size_t len, uint32_t type, const uint8_t ** out, size_t * outlen)
Definition at line 8 of file gsi_buf.c.
References kXRS_none.
Referenced by brix_gsi_handle_sigpxy(), gsi_capture_client_rtag(), gsi_cresp_agree_session_key(), gsi_cresp_choose_cipher(), gsi_cresp_extract_peer_pub(), gsi_cresp_pick_md_alg(), gsi_cresp_sign_server_tag(), gsi_find_bucket(), gsi_sigpxy(), originauth_gsi_verify_srv_cert(), pwd_more(), pwd_round1(), and pwd_round2().
brix_gsi_parse_parms()
void brix_gsi_parse_parms (const char * parms, uint32_t * version, char * crypto, size_t cryptosz, char * ca, size_t casz)
Definition at line 85 of file gsi_core.c.
References brix_gsi_parse_ca_parm(), and brix_gsi_parse_short_parm().
Referenced by gsi_first(), originauth_gsi_certreq(), and tpc_certreq_build_send().
brix_gsi_rand()
int brix_gsi_rand (uint8_t * out, size_t n)
Definition at line 10 of file gsi_rsa.c.
Referenced by brix_gsi_begin_delegation(), gsi_cresp_build_inner(), gsi_first(), originauth_gsi_certreq(), and tpc_certreq_build_send().
brix_gsi_rsa_decrypt_public()
size_t brix_gsi_rsa_decrypt_public (EVP_PKEY * key, const uint8_t * in, size_t inlen, uint8_t * out, size_t outmax)
Definition at line 78 of file gsi_rsa.c.
References key.
Referenced by gsi_cresp_extract_peer_pub(), and gsi_recover_peer_signed().
brix_gsi_rsa_encrypt_private()
size_t brix_gsi_rsa_encrypt_private (EVP_PKEY * key, const uint8_t * in, size_t inlen, uint8_t * out, size_t outmax)
Definition at line 42 of file gsi_rsa.c.
References key.
Referenced by brix_gsi_begin_delegation(), brix_gsi_rsa_sign_raw(), gsi_cresp_add_signed_public(), and gsi_select_dh_public_bucket().
brix_gsi_rsa_sign_raw()
size_t brix_gsi_rsa_sign_raw (EVP_PKEY * key, const uint8_t * in, size_t inlen, uint8_t * out)
Definition at line 26 of file gsi_rsa.c.
References brix_gsi_rsa_encrypt_private(), and key.
Referenced by gsi_cresp_sign_server_tag().
brix_gsi_sigver_hmac()
int brix_gsi_sigver_hmac (const uint8_t key[32], uint64_t seqno, const uint8_t hdr24[24], const uint8_t * payload, size_t plen, int nodata, uint8_t mac_out[32])
Definition at line 216 of file gsi_core.c.
References brix_gsi_sigver_seqno_be(), brix_hmac_sha256(), and key.
Referenced by brix_sigver_maybe(), and brix_verify_sigver_hmac().
brix_gsi_sigver_required()
int brix_gsi_sigver_required (uint16_t opcode, int level)
Definition at line 162 of file gsi_core.c.
References kXR_auth, kXR_bind, kXR_chkpoint, kXR_chmod, kXR_clone, kXR_endsess, kXR_fattr, kXR_login, kXR_mkdir, kXR_mv, kXR_open, kXR_pgwrite, kXR_ping, kXR_protocol, kXR_rm, kXR_rmdir, kXR_sigver, kXR_truncate, kXR_write, kXR_writev, and op.
Referenced by brix_sigver_maybe(), and brix_sigver_opcode_requires().
brix_gsi_sigver_seqno_be()
void brix_gsi_sigver_seqno_be (uint64_t seq, uint8_t out[8])
Definition at line 202 of file gsi_core.c.
Referenced by brix_gsi_sigver_hmac().