nginx-xrootd: src/auth/gsi/gsi_core_cresp.c File Reference
gsi_core_cresp.c File Reference
#include "gsi_core_internal.h"
Data Structures
struct gsi_cresp_state_t
Functions
static int gsi_cresp_state_fail (gsi_cresp_state_t *st, const char *msg)
static int gsi_cresp_extract_peer_pub (gsi_cresp_state_t *st)
static void gsi_cresp_choose_cipher (gsi_cresp_state_t *st)
static int gsi_cresp_agree_session_key (gsi_cresp_state_t *st)
static int gsi_cresp_sign_server_tag (gsi_cresp_state_t *st)
static int gsi_cresp_build_inner (gsi_cresp_state_t *st)
static int gsi_cresp_add_signed_public (gsi_cresp_state_t *st, size_t cpublen)
static int gsi_cresp_build_outer (gsi_cresp_state_t *st)
int brix_gsi_build_cert_response_ex (const uint8_t *sbody, uint32_t slen, const uint8_t *proxy_pem, size_t proxy_pem_len, EVP_PKEY *proxy_key, uint8_t **payload, uint32_t *plen, uint8_t *out_key, size_t *out_keylen, char *out_cipher, size_t out_cipher_cap, int *out_use_iv, char *err, size_t errcap)
int brix_gsi_build_cert_response (const uint8_t *sbody, uint32_t slen, const uint8_t *proxy_pem, size_t proxy_pem_len, EVP_PKEY *proxy_key, uint8_t **payload, uint32_t *plen, char *err, size_t errcap)
Function Documentation
brix_gsi_build_cert_response()
int brix_gsi_build_cert_response (const uint8_t * sbody, uint32_t slen, const uint8_t * proxy_pem, size_t proxy_pem_len, EVP_PKEY * proxy_key, uint8_t ** payload, uint32_t * plen, char * err, size_t errcap)
Definition at line 493 of file gsi_core_cresp.c.
References brix_gsi_build_cert_response_ex().
Referenced by originauth_gsi_send_response(), and tpc_gsi_build_round2().
brix_gsi_build_cert_response_ex()
int brix_gsi_build_cert_response_ex (const uint8_t * sbody, uint32_t slen, const uint8_t * proxy_pem, size_t proxy_pem_len, EVP_PKEY * proxy_key, uint8_t ** payload, uint32_t * plen, uint8_t * out_key, size_t * out_keylen, char * out_cipher, size_t out_cipher_cap, int * out_use_iv, char * err, size_t errcap)
Definition at line 431 of file gsi_core_cresp.c.
References brix_gbuf_init(), gsi_cresp_state_t::err, gsi_cresp_state_t::errcap, gsi_cresp_agree_session_key(), gsi_cresp_build_inner(), gsi_cresp_build_outer(), gsi_cresp_choose_cipher(), gsi_cresp_extract_peer_pub(), gsi_cresp_fail(), gsi_cresp_sign_server_tag(), gsi_cresp_state_fail(), gsi_cresp_ctx::inner, brix_gbuf::len, gsi_cresp_state_t::out_cipher, gsi_cresp_state_t::out_cipher_cap, gsi_cresp_state_t::out_key, gsi_cresp_state_t::out_keylen, gsi_cresp_state_t::out_use_iv, gsi_cresp_ctx::outer, brix_gbuf::p, gsi_cresp_state_t::proxy_key, gsi_cresp_state_t::proxy_pem, gsi_cresp_state_t::proxy_pem_len, gsi_cresp_state_t::res, gsi_cresp_state_t::sbody, and gsi_cresp_state_t::slen.
Referenced by brix_gsi_build_cert_response(), and gsi_more().
gsi_cresp_add_signed_public()
static int gsi_cresp_add_signed_public (gsi_cresp_state_t * st, size_t cpublen) static
Definition at line 348 of file gsi_core_cresp.c.
References brix_gbuf_bucket(), brix_gsi_rsa_encrypt_private(), gsi_cresp_ctx::cpub, gsi_cresp_export_pubkey_pem(), gsi_cresp_state_fail(), kXRS_cipher, kXRS_puk, gsi_cresp_ctx::outer, gsi_cresp_state_t::proxy_key, gsi_cresp_ctx::pubpem, gsi_cresp_state_t::res, gsi_cresp_ctx::signed_cpub, and gsi_cresp_ctx::signed_cpub_len.
Referenced by gsi_cresp_build_outer().
gsi_cresp_agree_session_key()
static int gsi_cresp_agree_session_key (gsi_cresp_state_t * st) static
Definition at line 199 of file gsi_core_cresp.c.
References gsi_cresp_state_t::aeskey, brix_gsi_cipher_keygen_from(), brix_gsi_cipher_parse_peer(), brix_gsi_cipher_session_key(), brix_gsi_find_bucket(), gsi_cresp_state_fail(), brix_gsi_cipher_t::key_len, kXRS_cryptomod, gsi_cresp_ctx::mine, gsi_cresp_ctx::peer, gsi_cresp_state_t::peerpub, gsi_cresp_state_t::peerpublen, gsi_cresp_state_t::res, gsi_cresp_state_t::sbody, gsi_cresp_state_t::sesscipher, gsi_cresp_state_t::signed_dh, and gsi_cresp_state_t::slen.
Referenced by brix_gsi_build_cert_response_ex().
gsi_cresp_build_inner()
static int gsi_cresp_build_inner (gsi_cresp_state_t * st) static
Definition at line 284 of file gsi_core_cresp.c.
References gsi_cresp_state_t::aeskey, brix_gbuf_bucket(), brix_gbuf_end(), brix_gbuf_start(), brix_gsi_cipher_encrypt(), BRIX_GSI_MAX_KEY, brix_gsi_rand(), gsi_cresp_state_t::chosen_cipher, gsi_cresp_ctx::enc, gsi_cresp_state_t::enclen, brix_gbuf::err, gsi_add_fullproxy_bucket(), gsi_cresp_state_fail(), gsi_cresp_ctx::inner, brix_gsi_cipher_t::key_len, kXGC_cert, kXRS_rtag, kXRS_signed_rtag, kXRS_x509, brix_gbuf::len, gsi_cresp_state_t::out_cipher, gsi_cresp_state_t::out_cipher_cap, gsi_cresp_state_t::out_key, gsi_cresp_state_t::out_keylen, gsi_cresp_state_t::out_use_iv, brix_gbuf::p, gsi_cresp_state_t::proxy_pem, gsi_cresp_state_t::proxy_pem_len, gsi_cresp_state_t::res, gsi_cresp_state_t::sesscipher, gsi_cresp_state_t::signed_dh, gsi_cresp_ctx::signed_rtag, gsi_cresp_ctx::signed_rtag_len, and gsi_cresp_state_t::use_iv.
Referenced by brix_gsi_build_cert_response_ex().
gsi_cresp_build_outer()
static int gsi_cresp_build_outer (gsi_cresp_state_t * st) static
Definition at line 386 of file gsi_core_cresp.c.
References brix_gbuf_bucket(), brix_gbuf_end(), brix_gbuf_start(), brix_gsi_cipher_public(), gsi_cresp_state_t::chosen_cipher, gsi_cresp_ctx::cpub, gsi_cresp_ctx::enc, gsi_cresp_state_t::enclen, brix_gbuf::err, gsi_cresp_add_signed_public(), gsi_cresp_pick_md_alg(), gsi_cresp_state_fail(), brix_gsi_cipher_t::iv_len, kXGC_cert, kXRS_cipher_alg, kXRS_cryptomod, kXRS_main, kXRS_md_alg, kXRS_puk, gsi_cresp_ctx::mine, gsi_cresp_ctx::outer, gsi_cresp_state_t::res, gsi_cresp_state_t::sbody, gsi_cresp_state_t::sesscipher, gsi_cresp_state_t::signed_dh, gsi_cresp_state_t::slen, and gsi_cresp_state_t::use_iv.
Referenced by brix_gsi_build_cert_response_ex().
gsi_cresp_choose_cipher()
static void gsi_cresp_choose_cipher (gsi_cresp_state_t * st) static
Definition at line 166 of file gsi_core_cresp.c.
References brix_gsi_cipher_lookup(), brix_gsi_cipher_pick(), brix_gsi_find_bucket(), gsi_cresp_state_t::chosen_cipher, kXRS_cipher_alg, gsi_cresp_state_t::sbody, gsi_cresp_state_t::sesscipher, and gsi_cresp_state_t::slen.
Referenced by brix_gsi_build_cert_response_ex().
gsi_cresp_extract_peer_pub()
static int gsi_cresp_extract_peer_pub (gsi_cresp_state_t * st) static
Definition at line 101 of file gsi_core_cresp.c.
References brix_gsi_find_bucket(), brix_gsi_rsa_decrypt_public(), gsi_cresp_cert_pubkey(), gsi_cresp_state_fail(), kXRS_cipher, kXRS_puk, kXRS_x509, gsi_cresp_ctx::peerblob, gsi_cresp_state_t::peerpub, gsi_cresp_state_t::peerpublen, gsi_cresp_state_t::res, gsi_cresp_state_t::sbody, gsi_cresp_ctx::servpub, gsi_cresp_state_t::signed_dh, and gsi_cresp_state_t::slen.
Referenced by brix_gsi_build_cert_response_ex().
gsi_cresp_sign_server_tag()
static int gsi_cresp_sign_server_tag (gsi_cresp_state_t * st) static
Definition at line 235 of file gsi_core_cresp.c.
References gsi_cresp_state_t::aeskey, brix_gsi_find_bucket(), BRIX_GSI_MAX_KEY, brix_gsi_rsa_sign_raw(), gsi_cresp_state_fail(), kXRS_main, kXRS_rtag, gsi_cresp_state_t::proxy_key, gsi_cresp_state_t::res, gsi_cresp_state_t::sbody, gsi_cresp_ctx::signed_rtag, gsi_cresp_ctx::signed_rtag_len, and gsi_cresp_state_t::slen.
Referenced by brix_gsi_build_cert_response_ex().
gsi_cresp_state_fail()
static int gsi_cresp_state_fail (gsi_cresp_state_t * st, const char * msg) static
Definition at line 84 of file gsi_core_cresp.c.
References gsi_cresp_state_t::err, gsi_cresp_state_t::errcap, gsi_cresp_fail(), and gsi_cresp_state_t::res.
Referenced by brix_gsi_build_cert_response_ex(), gsi_cresp_add_signed_public(), gsi_cresp_agree_session_key(), gsi_cresp_build_inner(), gsi_cresp_build_outer(), gsi_cresp_extract_peer_pub(), and gsi_cresp_sign_server_tag().