nginx-xrootd: src/auth/gssapi/gsi_mech.h File Reference
gsi_mech.h File Reference
#include <ngx_core.h>
#include <openssl/ssl.h>
#include <openssl/x509.h>
#include <openssl/x509_vfy.h>
Enumerations
enum brix_gss_status_e { BRIX_GSS_CONTINUE = 0 , BRIX_GSS_COMPLETE , BRIX_GSS_FAILED }
Functions
brix_gssapi_srv_t * brix_gssapi_srv_create (ngx_pool_t *pool, ngx_log_t *log, SSL_CTX *ssl_ctx, X509_STORE *ca_store, unsigned accept_deleg)
brix_gss_status_e brix_gssapi_srv_step (brix_gssapi_srv_t *g, const u_char *in, size_t in_len, ngx_str_t *out)
ngx_int_t brix_gssapi_srv_peer (brix_gssapi_srv_t *g, ngx_str_t *dn_out, ngx_str_t *proxy_pem_out)
ngx_int_t brix_gssapi_srv_peer_cert_pem (brix_gssapi_srv_t *g, ngx_str_t *out)
ngx_int_t brix_gssapi_wrap (brix_gssapi_srv_t *g, const u_char *in, size_t in_len, ngx_str_t *out)
ngx_int_t brix_gssapi_unwrap (brix_gssapi_srv_t *g, const u_char *in, size_t in_len, ngx_str_t *out)
void brix_gssapi_srv_free (brix_gssapi_srv_t *g)
Enumeration Type Documentation
brix_gss_status_e
enum brix_gss_status_e
Enumerator
BRIX_GSS_CONTINUE
BRIX_GSS_COMPLETE
BRIX_GSS_FAILED
Definition at line 33 of file gsi_mech.h.
Function Documentation
brix_gssapi_srv_create()
brix_gssapi_srv_t * brix_gssapi_srv_create (ngx_pool_t * pool, ngx_log_t * log, SSL_CTX * ssl_ctx, X509_STORE * ca_store, unsigned accept_deleg)
Definition at line 347 of file gsi_mech.c.
References gss_cleanup(), gss_verify_cb(), log, ngx_pcalloc(), and ST_TLS.
Referenced by brix_ftp_ev_cmd_auth().
brix_gssapi_srv_free()
void brix_gssapi_srv_free (brix_gssapi_srv_t * g)
Definition at line 534 of file gsi_mech.c.
References gss_cleanup().
brix_gssapi_srv_peer()
ngx_int_t brix_gssapi_srv_peer (brix_gssapi_srv_t * g, ngx_str_t * dn_out, ngx_str_t * proxy_pem_out)
Definition at line 477 of file gsi_mech.c.
Referenced by ev_gss_finalize().
brix_gssapi_srv_peer_cert_pem()
ngx_int_t brix_gssapi_srv_peer_cert_pem (brix_gssapi_srv_t * g, ngx_str_t * out)
Definition at line 491 of file gsi_mech.c.
References gss_x509_pem().
Referenced by ev_gss_finalize().
brix_gssapi_srv_step()
brix_gss_status_e brix_gssapi_srv_step (brix_gssapi_srv_t * g, const u_char * in, size_t in_len, ngx_str_t * out)
Definition at line 397 of file gsi_mech.c.
References BRIX_GSS_COMPLETE, BRIX_GSS_CONTINUE, BRIX_GSS_FAILED, gss_drain(), gss_read_all(), gss_recv_signed(), gss_send_proxy_req(), gss_verify_peer(), s, ST_DONE, ST_FAIL, ST_TLS, ST_WAIT_D, and ST_WAIT_SIGNED.
Referenced by brix_ftp_ev_cmd_adat().
brix_gssapi_unwrap()
ngx_int_t brix_gssapi_unwrap (brix_gssapi_srv_t * g, const u_char * in, size_t in_len, ngx_str_t * out)
Definition at line 523 of file gsi_mech.c.
References gss_read_all().
Referenced by brix_ftp_ev_cmd_protected().
brix_gssapi_wrap()
ngx_int_t brix_gssapi_wrap (brix_gssapi_srv_t * g, const u_char * in, size_t in_len, ngx_str_t * out)
Definition at line 512 of file gsi_mech.c.
References gss_drain().
Referenced by ev_reply_wrapped().