nginx-xrootd: src/tpc/gsi/gsi_outbound_finish.c File Reference
gsi_outbound_finish.c File Reference
#include "tpc/engine/tpc_internal.h"
#include "protocols/root/session/session.h"
#include "protocols/root/protocol/gsi.h"
#include "protocols/root/protocol/sec_protocol.h"
#include <stdio.h>
#include <ctype.h>
#include <errno.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
Functions
int tpc_outbound_finish_login (brix_tpc_pull_t *t, int fd, u_char *login_body, uint32_t login_dlen)
Function Documentation
tpc_outbound_finish_login()
int tpc_outbound_finish_login (brix_tpc_pull_t * t, int fd, u_char * login_body, uint32_t login_dlen)
Definition at line 27 of file gsi_outbound_finish.c.
References brix_sec_proto_advertised(), BRIX_SESSION_ID_LEN, brix_tpc_pull_t::conf, brix_tpc_pull_t::delegated_token, brix_tpc_pull_t::err_msg, kXR_ArgInvalid, kXR_AuthFailed, brix_tpc_pull_t::src_host, tpc_outbound_gsi(), tpc_outbound_ztn(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_bootstrap_login().