nginx-xrootd: src/auth/gsi/gsi_buf.c File Reference
gsi_buf.c File Reference
#include "gsi_core_internal.h"
Functions
int brix_gsi_find_bucket (const uint8_t *buf, size_t len, uint32_t type, const uint8_t **out, size_t *outlen)
void brix_gbuf_init (brix_gbuf *g)
void brix_gbuf_free (brix_gbuf *g)
void brix_gbuf_raw (brix_gbuf *g, const void *data, size_t n)
void brix_gbuf_u32 (brix_gbuf *g, uint32_t v)
void brix_gbuf_start (brix_gbuf *g, uint32_t step)
void brix_gbuf_bucket (brix_gbuf *g, uint32_t type, const void *d, size_t n)
void brix_gbuf_end (brix_gbuf *g)
Function Documentation
brix_gbuf_bucket()
void brix_gbuf_bucket (brix_gbuf * g, uint32_t type, const void * d, size_t n)
Definition at line 113 of file gsi_buf.c.
References brix_gbuf_raw(), and brix_gbuf_u32().
Referenced by brix_gsi_begin_delegation(), brix_gsi_build_cert_response_ex(), brix_gsi_build_certreq(), gsi_sigpxy(), pwd_first(), pwd_more(), and pwd_send_credsreq().
brix_gbuf_end()
void brix_gbuf_end (brix_gbuf * g)
Definition at line 122 of file gsi_buf.c.
References brix_gbuf_u32(), and kXRS_none.
Referenced by brix_gsi_begin_delegation(), brix_gsi_build_cert_response_ex(), brix_gsi_build_certreq(), gsi_sigpxy(), pwd_first(), pwd_more(), and pwd_send_credsreq().
brix_gbuf_free()
void brix_gbuf_free (brix_gbuf * g)
Definition at line 63 of file gsi_buf.c.
References brix_gbuf::cap, brix_gbuf::len, and brix_gbuf::p.
Referenced by bdg_fail(), brix_gsi_build_certreq(), gsi_cresp_fail(), gsi_sigpxy(), pwd_first(), pwd_more(), and pwd_send_credsreq().
brix_gbuf_init()
void brix_gbuf_init (brix_gbuf * g)
Definition at line 53 of file gsi_buf.c.
References brix_gbuf::cap, brix_gbuf::err, brix_gbuf::len, and brix_gbuf::p.
Referenced by brix_gsi_begin_delegation(), brix_gsi_build_cert_response_ex(), brix_gsi_build_certreq(), gsi_sigpxy(), pwd_first(), pwd_more(), and pwd_send_credsreq().
brix_gbuf_raw()
void brix_gbuf_raw (brix_gbuf * g, const void * data, size_t n)
Definition at line 72 of file gsi_buf.c.
References brix_gbuf::cap, brix_gbuf::err, brix_gbuf::len, and brix_gbuf::p.
Referenced by brix_gbuf_bucket(), brix_gbuf_start(), brix_gbuf_u32(), pwd_first(), pwd_more(), and pwd_send_credsreq().
brix_gbuf_start()
void brix_gbuf_start (brix_gbuf * g, uint32_t step)
Definition at line 105 of file gsi_buf.c.
References brix_gbuf_raw(), and brix_gbuf_u32().
Referenced by brix_gsi_begin_delegation(), brix_gsi_build_cert_response_ex(), brix_gsi_build_certreq(), and gsi_sigpxy().
brix_gbuf_u32()
void brix_gbuf_u32 (brix_gbuf * g, uint32_t v)
Definition at line 97 of file gsi_buf.c.
References brix_gbuf_raw().
Referenced by brix_gbuf_bucket(), brix_gbuf_end(), brix_gbuf_start(), pwd_first(), pwd_more(), and pwd_send_credsreq().
brix_gsi_find_bucket()
int brix_gsi_find_bucket (const uint8_t * buf, size_t len, uint32_t type, const uint8_t ** out, size_t * outlen)
Definition at line 8 of file gsi_buf.c.
References kXRS_none.
Referenced by brix_cache_origin_auth_gsi(), brix_gsi_build_cert_response_ex(), brix_gsi_handle_sigpxy(), gsi_capture_client_rtag(), gsi_cresp_pick_md_alg(), gsi_find_bucket(), gsi_sigpxy(), pwd_more(), pwd_round1(), and pwd_round2().