nginx-xrootd: src/net/guard/guard_ruleset.c File Reference
guard_ruleset.c File Reference
#include "guard.h"
#include <string.h>
Functions
void guard_ruleset_init (guard_ruleset_t *rs)
int guard_ruleset_add_signature (guard_ruleset_t *rs, guard_sig_kind_t kind, const char *pat, size_t pat_len)
void guard_ruleset_add_default_signatures (guard_ruleset_t *rs)
int guard_ruleset_add_prefix (guard_ruleset_t *rs, const char *pfx, size_t len)
static void allow_ops (guard_ruleset_t *rs, const guard_op_class_t *ops, int count)
void guard_ruleset_load_profile (guard_ruleset_t *rs, const char *profile)
Function Documentation
allow_ops()
static void allow_ops (guard_ruleset_t * rs, const guard_op_class_t * ops, int count) static
Definition at line 127 of file guard_ruleset.c.
References guard_ruleset_t::op_allowed.
Referenced by guard_ruleset_load_profile().
guard_ruleset_add_default_signatures()
void guard_ruleset_add_default_signatures (guard_ruleset_t * rs)
Definition at line 72 of file guard_ruleset.c.
References guard_ruleset_add_signature(), GUARD_SIG_PREFIX, GUARD_SIG_SUBSTR, and GUARD_SIG_SUFFIX.
Referenced by brix_relay_guard_init(), main(), and ngx_http_brix_guard_build_ruleset().
guard_ruleset_add_prefix()
int guard_ruleset_add_prefix (guard_ruleset_t * rs, const char * pfx, size_t len)
Definition at line 106 of file guard_ruleset.c.
References GUARD_MAX_PREFIXES, guard_ruleset_t::n_prefixes, guard_ruleset_t::prefix_len, and guard_ruleset_t::prefixes.
Referenced by guard_ruleset_load_profile(), main(), and ngx_http_brix_guard_build_ruleset().
guard_ruleset_add_signature()
int guard_ruleset_add_signature (guard_ruleset_t * rs, guard_sig_kind_t kind, const char * pat, size_t pat_len)
Definition at line 44 of file guard_ruleset.c.
References GUARD_MAX_SIGS, guard_sig_t::kind, guard_ruleset_t::n_sigs, guard_sig_t::pat, guard_sig_t::pat_len, and guard_ruleset_t::sigs.
Referenced by guard_ruleset_add_default_signatures(), main(), and ngx_http_brix_guard_build_ruleset().
guard_ruleset_init()
void guard_ruleset_init (guard_ruleset_t * rs)
Definition at line 27 of file guard_ruleset.c.
Referenced by brix_relay_guard_init(), main(), and ngx_http_brix_guard_build_ruleset().
guard_ruleset_load_profile()
void guard_ruleset_load_profile (guard_ruleset_t * rs, const char * profile)
Definition at line 153 of file guard_ruleset.c.
References allow_ops(), guard_ruleset_t::enforce_grammar, guard_ruleset_t::flag_authfail, guard_ruleset_t::flag_notfound, GUARD_OP_DELEG, GUARD_OP_DELETE, GUARD_OP_HANDSHAKE, GUARD_OP_INFO, GUARD_OP_JOBCTL, GUARD_OP_LIST, GUARD_OP_READ, GUARD_OP_STAGE, GUARD_OP_UNKNOWN, GUARD_OP_WRITE, guard_ruleset_add_prefix(), and guard_ruleset_t::op_allowed.
Referenced by brix_relay_guard_init(), main(), and ngx_http_brix_guard_build_ruleset().