nginx-xrootd: src/net/httpguard/guard_http.h File Reference
guard_http.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include "net/guard/guard.h"
Data Structures
struct ngx_http_brix_guard_loc_conf_t
struct ngx_http_brix_guard_ctx_t
Macros
#define BRIX_GUARD_PATH_BUF 1024
#define BRIX_GUARD_IP_BUF 64
Functions
ngx_int_t ngx_http_brix_guard_access_handler (ngx_http_request_t *r)
ngx_int_t ngx_http_brix_guard_log_handler (ngx_http_request_t *r)
void ngx_http_brix_guard_build_request (ngx_http_request_t *r, ngx_http_brix_guard_loc_conf_t *lcf, guard_request_t *out, char *pathbuf, size_t pathbuf_sz, char *ipbuf, size_t ipbuf_sz)
void ngx_http_brix_guard_write_audit (ngx_http_request_t *r, ngx_http_brix_guard_loc_conf_t *lcf, const guard_request_t *req, guard_reason_t reason)
size_t brix_sanitize_log_string (const char *in, char *out, size_t outsz)
Variables
ngx_module_t ngx_http_brix_guard_module
Macro Definition Documentation
BRIX_GUARD_IP_BUF
#define BRIX_GUARD_IP_BUF 64
Definition at line 57 of file guard_http.h.
BRIX_GUARD_PATH_BUF
#define BRIX_GUARD_PATH_BUF 1024
Definition at line 56 of file guard_http.h.
Function Documentation
brix_sanitize_log_string()
size_t brix_sanitize_log_string (const char * in, char * out, size_t outsz)
Definition at line 46 of file helpers.c.
ngx_http_brix_guard_access_handler()
ngx_int_t ngx_http_brix_guard_access_handler (ngx_http_request_t * r)
Definition at line 34 of file classify_handler.c.
References ngx_http_brix_guard_loc_conf_t::bounce_status, ngx_http_brix_guard_ctx_t::bounced, BRIX_GUARD_IP_BUF, BRIX_GUARD_PATH_BUF, ngx_http_brix_guard_loc_conf_t::enable, GUARD_BOUNCE, guard_classify_pre(), GUARD_R_NONE, ngx_http_brix_guard_build_request(), ngx_http_brix_guard_module, ngx_http_brix_guard_write_audit(), ngx_pcalloc(), ngx_http_brix_guard_ctx_t::pre_reason, ngx_http_brix_guard_loc_conf_t::ruleset, and guard_request_t::status_code.
Referenced by ngx_http_brix_guard_postconf().
ngx_http_brix_guard_build_request()
void ngx_http_brix_guard_build_request (ngx_http_request_t * r, ngx_http_brix_guard_loc_conf_t * lcf, guard_request_t * out, char * pathbuf, size_t pathbuf_sz, char * ipbuf, size_t ipbuf_sz)
Definition at line 114 of file guard_http_req.c.
References BRIX_GUARD_PATH_BUF, brix_sanitize_log_string(), copy_str_z(), guard_request_t::cred_present, cred_present(), guard_request_t::ip, method_to_op(), guard_request_t::op, guard_request_t::outcome, OUTCOME_PENDING, guard_request_t::path, guard_request_t::path_len, ngx_http_brix_guard_loc_conf_t::profile, guard_request_t::proto, and guard_request_t::status_code.
Referenced by ngx_http_brix_guard_access_handler(), and ngx_http_brix_guard_log_handler().
ngx_http_brix_guard_log_handler()
ngx_int_t ngx_http_brix_guard_log_handler (ngx_http_request_t * r)
Definition at line 55 of file audit_handler.c.
References ngx_http_brix_guard_ctx_t::bounced, BRIX_GUARD_IP_BUF, BRIX_GUARD_PATH_BUF, ngx_http_brix_guard_loc_conf_t::enable, guard_classify_post(), GUARD_R_NONE, ngx_http_brix_guard_build_request(), ngx_http_brix_guard_module, ngx_http_brix_guard_write_audit(), guard_request_t::outcome, ngx_http_brix_guard_loc_conf_t::ruleset, guard_request_t::status_code, and status_to_outcome().
Referenced by ngx_http_brix_guard_postconf().
ngx_http_brix_guard_write_audit()
void ngx_http_brix_guard_write_audit (ngx_http_request_t * r, ngx_http_brix_guard_loc_conf_t * lcf, const guard_request_t * req, guard_reason_t reason)
Definition at line 153 of file guard_http_req.c.
References ngx_http_brix_guard_loc_conf_t::audit_log, BRIX_GUARD_PATH_BUF, guard_audit_format(), and ngx_memcpy.
Referenced by ngx_http_brix_guard_access_handler(), and ngx_http_brix_guard_log_handler().
Variable Documentation
ngx_http_brix_guard_module
ngx_module_t ngx_http_brix_guard_module extern
Definition at line 101 of file module.c.
Referenced by ngx_http_brix_guard_access_handler(), and ngx_http_brix_guard_log_handler().