nginx-xrootd: src/net/guard/guard.h File Reference
guard.h File Reference
#include <stddef.h>
Data Structures
struct guard_request_t
struct guard_sig_t
struct guard_ruleset_t
Macros
#define GUARD_MAX_SIGS 64
#define GUARD_MAX_PREFIXES 32
Enumerations
enum guard_op_class_t {
GUARD_OP_READ , GUARD_OP_WRITE , GUARD_OP_LIST , GUARD_OP_DELETE ,
GUARD_OP_JOBCTL , GUARD_OP_STAGE , GUARD_OP_INFO , GUARD_OP_DELEG ,
GUARD_OP_HANDSHAKE , GUARD_OP_UNKNOWN
}
enum guard_outcome_t {
OUTCOME_PENDING , OUTCOME_OK , OUTCOME_NOTFOUND , OUTCOME_AUTHFAIL ,
OUTCOME_ERROR
}
enum guard_verdict_t { GUARD_ALLOW , GUARD_BOUNCE }
enum guard_reason_t {
GUARD_R_NONE , GUARD_R_SIGNATURE , GUARD_R_GRAMMAR , GUARD_R_NOTFOUND ,
GUARD_R_AUTHFAIL , GUARD_R_NOTROOT , GUARD_R_PROXYABUSE , GUARD_R_TAMPER
}
enum guard_wire_t {
GUARD_WIRE_ROOT , GUARD_WIRE_TLS , GUARD_WIRE_HTTP , GUARD_WIRE_SSH ,
GUARD_WIRE_EMPTY , GUARD_WIRE_JUNK
}
enum guard_sig_kind_t { GUARD_SIG_SUFFIX , GUARD_SIG_PREFIX , GUARD_SIG_SUBSTR }
Functions
guard_verdict_t guard_classify_pre (const guard_ruleset_t *rs, const guard_request_t *req, guard_reason_t *why)
guard_reason_t guard_classify_post (const guard_ruleset_t *rs, const guard_request_t *req)
int guard_signature_match (const guard_ruleset_t *rs, const char *path, size_t len)
int guard_grammar_ok (const guard_ruleset_t *rs, guard_op_class_t op, const char *path, size_t len)
guard_wire_t guard_classify_handshake (const unsigned char *buf, size_t len, int *need_more)
size_t guard_audit_format (const guard_request_t *req, guard_reason_t reason, const char *ts, char *out, size_t outsz)
const char * guard_reason_str (guard_reason_t r)
const char * guard_op_str (guard_op_class_t op)
const char * guard_wire_str (guard_wire_t w)
void guard_ruleset_init (guard_ruleset_t *rs)
void guard_ruleset_add_default_signatures (guard_ruleset_t *rs)
int guard_ruleset_add_signature (guard_ruleset_t *rs, guard_sig_kind_t kind, const char *pat, size_t pat_len)
int guard_ruleset_add_prefix (guard_ruleset_t *rs, const char *pfx, size_t len)
void guard_ruleset_load_profile (guard_ruleset_t *rs, const char *profile)
Macro Definition Documentation
GUARD_MAX_PREFIXES
#define GUARD_MAX_PREFIXES 32
Definition at line 75 of file guard.h.
GUARD_MAX_SIGS
#define GUARD_MAX_SIGS 64
Definition at line 74 of file guard.h.
Enumeration Type Documentation
guard_op_class_t
enum guard_op_class_t
Enumerator
GUARD_OP_READ
GUARD_OP_WRITE
GUARD_OP_LIST
GUARD_OP_DELETE
GUARD_OP_JOBCTL
GUARD_OP_STAGE
GUARD_OP_INFO
GUARD_OP_DELEG
GUARD_OP_HANDSHAKE
GUARD_OP_UNKNOWN
Definition at line 20 of file guard.h.
guard_outcome_t
enum guard_outcome_t
Enumerator
OUTCOME_PENDING
OUTCOME_OK
OUTCOME_NOTFOUND
OUTCOME_AUTHFAIL
OUTCOME_ERROR
Definition at line 26 of file guard.h.
guard_reason_t
enum guard_reason_t
Enumerator
GUARD_R_NONE
GUARD_R_SIGNATURE
GUARD_R_GRAMMAR
GUARD_R_NOTFOUND
GUARD_R_AUTHFAIL
GUARD_R_NOTROOT
GUARD_R_PROXYABUSE
GUARD_R_TAMPER
Definition at line 33 of file guard.h.
guard_sig_kind_t
enum guard_sig_kind_t
Enumerator
GUARD_SIG_SUFFIX
GUARD_SIG_PREFIX
GUARD_SIG_SUBSTR
Definition at line 68 of file guard.h.
guard_verdict_t
enum guard_verdict_t
Enumerator
GUARD_ALLOW
GUARD_BOUNCE
Definition at line 31 of file guard.h.
guard_wire_t
enum guard_wire_t
Enumerator
GUARD_WIRE_ROOT
GUARD_WIRE_TLS
GUARD_WIRE_HTTP
GUARD_WIRE_SSH
GUARD_WIRE_EMPTY
GUARD_WIRE_JUNK
Definition at line 47 of file guard.h.
Function Documentation
guard_audit_format()
size_t guard_audit_format (const guard_request_t * req, guard_reason_t reason, const char * ts, char * out, size_t outsz)
Definition at line 105 of file guard_audit.c.
References guard_op_str(), guard_reason_str(), guard_request_t::ip, guard_request_t::op, guard_request_t::path, guard_request_t::path_len, guard_request_t::proto, and guard_request_t::status_code.
Referenced by cvmfs_guard_emit(), main(), ngx_http_brix_guard_write_audit(), relay_guard_audit(), and sd_cache_guard_tamper().
guard_classify_handshake()
guard_wire_t guard_classify_handshake (const unsigned char * buf, size_t len, int * need_more)
Definition at line 168 of file guard_classify.c.
References GUARD_WIRE_EMPTY, GUARD_WIRE_HTTP, GUARD_WIRE_JUNK, GUARD_WIRE_ROOT, GUARD_WIRE_SSH, GUARD_WIRE_TLS, and is_http_line().
Referenced by brix_relay_guard_handshake(), and main().
guard_classify_post()
guard_reason_t guard_classify_post (const guard_ruleset_t * rs, const guard_request_t * req)
Definition at line 260 of file guard_classify.c.
References guard_ruleset_t::flag_authfail, guard_ruleset_t::flag_notfound, GUARD_R_AUTHFAIL, GUARD_R_NONE, GUARD_R_NOTFOUND, guard_request_t::outcome, OUTCOME_AUTHFAIL, and OUTCOME_NOTFOUND.
Referenced by brix_relay_guard_sink(), main(), and ngx_http_brix_guard_log_handler().
guard_classify_pre()
guard_verdict_t guard_classify_pre (const guard_ruleset_t * rs, const guard_request_t * req, guard_reason_t * why)
Definition at line 227 of file guard_classify.c.
References guard_ruleset_t::enforce_grammar, GUARD_ALLOW, GUARD_BOUNCE, guard_grammar_ok(), GUARD_R_GRAMMAR, GUARD_R_NONE, GUARD_R_SIGNATURE, guard_signature_match(), guard_request_t::op, guard_request_t::path, and guard_request_t::path_len.
Referenced by brix_relay_guard_sink(), main(), and ngx_http_brix_guard_access_handler().
guard_grammar_ok()
int guard_grammar_ok (const guard_ruleset_t * rs, guard_op_class_t op, const char * path, size_t len)
Definition at line 95 of file guard_classify.c.
References guard_ruleset_t::n_prefixes, op, guard_ruleset_t::op_allowed, guard_ruleset_t::prefix_len, and guard_ruleset_t::prefixes.
Referenced by guard_classify_pre().
guard_op_str()
const char * guard_op_str (guard_op_class_t op)
Definition at line 73 of file guard_audit.c.
References GUARD_OP_DELEG, GUARD_OP_DELETE, GUARD_OP_HANDSHAKE, GUARD_OP_INFO, GUARD_OP_JOBCTL, GUARD_OP_LIST, GUARD_OP_READ, GUARD_OP_STAGE, GUARD_OP_UNKNOWN, GUARD_OP_WRITE, and op.
Referenced by guard_audit_format(), and main().
guard_reason_str()
const char * guard_reason_str (guard_reason_t r)
Definition at line 26 of file guard_audit.c.
References GUARD_R_AUTHFAIL, GUARD_R_GRAMMAR, GUARD_R_NONE, GUARD_R_NOTFOUND, GUARD_R_NOTROOT, GUARD_R_PROXYABUSE, GUARD_R_SIGNATURE, and GUARD_R_TAMPER.
Referenced by guard_audit_format(), and main().
guard_ruleset_add_default_signatures()
void guard_ruleset_add_default_signatures (guard_ruleset_t * rs)
Definition at line 72 of file guard_ruleset.c.
References guard_ruleset_add_signature(), GUARD_SIG_PREFIX, GUARD_SIG_SUBSTR, and GUARD_SIG_SUFFIX.
Referenced by brix_relay_guard_init(), main(), and ngx_http_brix_guard_build_ruleset().
guard_ruleset_add_prefix()
int guard_ruleset_add_prefix (guard_ruleset_t * rs, const char * pfx, size_t len)
Definition at line 106 of file guard_ruleset.c.
References GUARD_MAX_PREFIXES, guard_ruleset_t::n_prefixes, guard_ruleset_t::prefix_len, and guard_ruleset_t::prefixes.
Referenced by guard_ruleset_load_profile(), main(), and ngx_http_brix_guard_build_ruleset().
guard_ruleset_add_signature()
int guard_ruleset_add_signature (guard_ruleset_t * rs, guard_sig_kind_t kind, const char * pat, size_t pat_len)
Definition at line 44 of file guard_ruleset.c.
References GUARD_MAX_SIGS, guard_sig_t::kind, guard_ruleset_t::n_sigs, guard_sig_t::pat, guard_sig_t::pat_len, and guard_ruleset_t::sigs.
Referenced by guard_ruleset_add_default_signatures(), main(), and ngx_http_brix_guard_build_ruleset().
guard_ruleset_init()
void guard_ruleset_init (guard_ruleset_t * rs)
Definition at line 27 of file guard_ruleset.c.
Referenced by brix_relay_guard_init(), main(), and ngx_http_brix_guard_build_ruleset().
guard_ruleset_load_profile()
void guard_ruleset_load_profile (guard_ruleset_t * rs, const char * profile)
Definition at line 153 of file guard_ruleset.c.
References allow_ops(), guard_ruleset_t::enforce_grammar, guard_ruleset_t::flag_authfail, guard_ruleset_t::flag_notfound, GUARD_OP_DELEG, GUARD_OP_DELETE, GUARD_OP_HANDSHAKE, GUARD_OP_INFO, GUARD_OP_JOBCTL, GUARD_OP_LIST, GUARD_OP_READ, GUARD_OP_STAGE, GUARD_OP_UNKNOWN, GUARD_OP_WRITE, guard_ruleset_add_prefix(), and guard_ruleset_t::op_allowed.
Referenced by brix_relay_guard_init(), main(), and ngx_http_brix_guard_build_ruleset().
guard_signature_match()
int guard_signature_match (const guard_ruleset_t * rs, const char * path, size_t len)
Definition at line 68 of file guard_classify.c.
References guard_ruleset_t::n_sigs, sig_hit(), and guard_ruleset_t::sigs.
Referenced by guard_classify_pre(), and main().
guard_wire_str()
const char * guard_wire_str (guard_wire_t w)
Definition at line 51 of file guard_audit.c.
References GUARD_WIRE_EMPTY, GUARD_WIRE_HTTP, GUARD_WIRE_JUNK, GUARD_WIRE_ROOT, GUARD_WIRE_SSH, and GUARD_WIRE_TLS.
Referenced by brix_relay_guard_handshake(), and main().