nginx-xrootd: src/net/guard/guard_classify.c File Reference
guard_classify.c File Reference
#include "guard.h"
#include <string.h>
Functions
static int sig_hit (const guard_sig_t *s, const char *path, size_t len)
int guard_signature_match (const guard_ruleset_t *rs, const char *path, size_t len)
int guard_grammar_ok (const guard_ruleset_t *rs, guard_op_class_t op, const char *path, size_t len)
guard_verdict_t guard_classify_pre (const guard_ruleset_t *rs, const guard_request_t *req, guard_reason_t *why)
guard_reason_t guard_classify_post (const guard_ruleset_t *rs, const guard_request_t *req)
Function Documentation
guard_classify_post()
guard_reason_t guard_classify_post (const guard_ruleset_t * rs, const guard_request_t * req)
Definition at line 166 of file guard_classify.c.
References guard_ruleset_t::flag_authfail, guard_ruleset_t::flag_notfound, GUARD_R_AUTHFAIL, GUARD_R_NONE, GUARD_R_NOTFOUND, guard_request_t::outcome, OUTCOME_AUTHFAIL, and OUTCOME_NOTFOUND.
Referenced by brix_relay_guard_sink(), main(), and ngx_http_brix_guard_log_handler().
guard_classify_pre()
guard_verdict_t guard_classify_pre (const guard_ruleset_t * rs, const guard_request_t * req, guard_reason_t * why)
Definition at line 133 of file guard_classify.c.
References guard_ruleset_t::enforce_grammar, GUARD_ALLOW, GUARD_BOUNCE, guard_grammar_ok(), GUARD_R_GRAMMAR, GUARD_R_NONE, GUARD_R_SIGNATURE, guard_signature_match(), guard_request_t::op, guard_request_t::path, and guard_request_t::path_len.
Referenced by brix_relay_guard_sink(), main(), and ngx_http_brix_guard_access_handler().
guard_grammar_ok()
int guard_grammar_ok (const guard_ruleset_t * rs, guard_op_class_t op, const char * path, size_t len)
Definition at line 95 of file guard_classify.c.
References guard_ruleset_t::n_prefixes, guard_ruleset_t::op_allowed, guard_ruleset_t::prefix_len, and guard_ruleset_t::prefixes.
Referenced by guard_classify_pre().
guard_signature_match()
int guard_signature_match (const guard_ruleset_t * rs, const char * path, size_t len)
Definition at line 68 of file guard_classify.c.
References guard_ruleset_t::n_sigs, sig_hit(), and guard_ruleset_t::sigs.
Referenced by guard_classify_pre(), and main().
sig_hit()
static int sig_hit (const guard_sig_t * s, const char * path, size_t len) static
Definition at line 31 of file guard_classify.c.
References GUARD_SIG_PREFIX, GUARD_SIG_SUBSTR, GUARD_SIG_SUFFIX, and s.
Referenced by guard_signature_match().