nginx-xrootd: src/net/httpguard/guard_http_req.c File Reference
guard_http_req.c File Reference
#include "guard_http.h"
Functions
static guard_op_class_t method_to_op (ngx_uint_t method)
static int cred_present (ngx_http_request_t *r)
static size_t copy_str_z (const ngx_str_t *src, char *buf, size_t bufsz)
void ngx_http_brix_guard_build_request (ngx_http_request_t *r, ngx_http_brix_guard_loc_conf_t *lcf, guard_request_t *out, char *pathbuf, size_t pathbuf_sz, char *ipbuf, size_t ipbuf_sz)
void ngx_http_brix_guard_write_audit (ngx_http_request_t *r, ngx_http_brix_guard_loc_conf_t *lcf, const guard_request_t *req, guard_reason_t reason)
Function Documentation
copy_str_z()
static size_t copy_str_z (const ngx_str_t * src, char * buf, size_t bufsz) static
Definition at line 87 of file guard_http_req.c.
References ngx_memcpy.
Referenced by ngx_http_brix_guard_build_request().
cred_present()
static int cred_present (ngx_http_request_t * r) static
Definition at line 57 of file guard_http_req.c.
Referenced by ngx_http_brix_guard_build_request().
method_to_op()
static guard_op_class_t method_to_op (ngx_uint_t method) static
Definition at line 28 of file guard_http_req.c.
References GUARD_OP_DELETE, GUARD_OP_INFO, GUARD_OP_LIST, GUARD_OP_READ, GUARD_OP_UNKNOWN, and GUARD_OP_WRITE.
Referenced by ngx_http_brix_guard_build_request().
ngx_http_brix_guard_build_request()
void ngx_http_brix_guard_build_request (ngx_http_request_t * r, ngx_http_brix_guard_loc_conf_t * lcf, guard_request_t * out, char * pathbuf, size_t pathbuf_sz, char * ipbuf, size_t ipbuf_sz)
Definition at line 114 of file guard_http_req.c.
References BRIX_GUARD_PATH_BUF, brix_sanitize_log_string(), copy_str_z(), guard_request_t::cred_present, cred_present(), guard_request_t::ip, method_to_op(), guard_request_t::op, guard_request_t::outcome, OUTCOME_PENDING, guard_request_t::path, guard_request_t::path_len, ngx_http_brix_guard_loc_conf_t::profile, guard_request_t::proto, and guard_request_t::status_code.
Referenced by ngx_http_brix_guard_access_handler(), and ngx_http_brix_guard_log_handler().
ngx_http_brix_guard_write_audit()
void ngx_http_brix_guard_write_audit (ngx_http_request_t * r, ngx_http_brix_guard_loc_conf_t * lcf, const guard_request_t * req, guard_reason_t reason)
Definition at line 153 of file guard_http_req.c.
References ngx_http_brix_guard_loc_conf_t::audit_log, BRIX_GUARD_PATH_BUF, guard_audit_format(), and ngx_memcpy.
Referenced by ngx_http_brix_guard_access_handler(), and ngx_http_brix_guard_log_handler().