nginx-xrootd: src/net/guard/guard_test.c File Reference
guard_test.c File Reference
#include "guard.h"
#include <stdio.h>
#include <string.h>
Macros
#define CHECK(cond)
Functions
int main (void)
Variables
static int fails
Macro Definition Documentation
CHECK
#define CHECK (cond)
Value:
    do { if (!(cond)) { \
    printf("FAIL %s:%d  %s\n", __FILE__, __LINE__, #cond); fails++; } } while (0)
Definition at line 17 of file guard_test.c.
Function Documentation
main()
int main (void)
Definition at line 20 of file guard_test.c.
References CHECK, guard_ruleset_t::enforce_grammar, fails, guard_ruleset_t::flag_authfail, guard_ruleset_t::flag_notfound, GUARD_ALLOW, guard_audit_format(), GUARD_BOUNCE, guard_classify_post(), guard_classify_pre(), GUARD_OP_READ, GUARD_OP_STAGE, guard_op_str(), GUARD_R_AUTHFAIL, GUARD_R_GRAMMAR, GUARD_R_NONE, GUARD_R_NOTFOUND, GUARD_R_SIGNATURE, guard_reason_str(), guard_ruleset_add_default_signatures(), guard_ruleset_add_prefix(), guard_ruleset_add_signature(), guard_ruleset_init(), guard_ruleset_load_profile(), GUARD_SIG_SUBSTR, guard_signature_match(), guard_ruleset_t::n_prefixes, guard_ruleset_t::n_sigs, OUTCOME_AUTHFAIL, OUTCOME_NOTFOUND, OUTCOME_OK, and OUTCOME_PENDING.
Variable Documentation
fails
int fails static
Definition at line 16 of file guard_test.c.
Referenced by main().