nginx-xrootd: src/net/guard/guard_audit.c File Reference
guard_audit.c File Reference
#include "guard.h"
#include <stdio.h>
Functions
const char * guard_reason_str (guard_reason_t r)
const char * guard_op_str (guard_op_class_t op)
size_t guard_audit_format (const guard_request_t *req, guard_reason_t reason, const char *ts, char *out, size_t outsz)
Function Documentation
guard_audit_format()
size_t guard_audit_format (const guard_request_t * req, guard_reason_t reason, const char * ts, char * out, size_t outsz)
Definition at line 79 of file guard_audit.c.
References guard_op_str(), guard_reason_str(), guard_request_t::ip, guard_request_t::op, guard_request_t::path, guard_request_t::path_len, guard_request_t::proto, and guard_request_t::status_code.
Referenced by main(), ngx_http_brix_guard_write_audit(), and relay_guard_audit().
guard_op_str()
const char * guard_op_str (guard_op_class_t op)
Definition at line 47 of file guard_audit.c.
References GUARD_OP_DELEG, GUARD_OP_DELETE, GUARD_OP_HANDSHAKE, GUARD_OP_INFO, GUARD_OP_JOBCTL, GUARD_OP_LIST, GUARD_OP_READ, GUARD_OP_STAGE, GUARD_OP_UNKNOWN, and GUARD_OP_WRITE.
Referenced by guard_audit_format(), and main().
guard_reason_str()
const char * guard_reason_str (guard_reason_t r)
Definition at line 26 of file guard_audit.c.
References GUARD_R_AUTHFAIL, GUARD_R_GRAMMAR, GUARD_R_NONE, GUARD_R_NOTFOUND, and GUARD_R_SIGNATURE.
Referenced by guard_audit_format(), and main().