nginx-xrootd: src/protocols/root/session/handles.c File Reference
handles.c File Reference
#include "registry.h"
#include "core/compat/shm_slots.h"
#include <ngx_shmtx.h>
#include <string.h>
Functions
static brix_shared_handle_table_t * handle_table (void)
ngx_int_t brix_handle_shm_init_zone (ngx_shm_zone_t *shm_zone, void *data)
static ngx_flag_t brix_shared_handle_same_key (const brix_shared_handle_entry_t *entry, const u_char sessid[16], int handle_index)
static void brix_shared_handle_find_slot (brix_shared_handle_table_t *tbl, const u_char sessid[16], int handle_index, brix_shared_handle_entry_t **entry, ngx_uint_t *free_slot)
static void brix_shared_handle_store (brix_shared_handle_entry_t *entry, const u_char sessid[16], int handle_index, const brix_file_t *file)
static ngx_flag_t brix_shared_handle_select_target (brix_shared_handle_table_t *tbl, const brix_file_t *file, ngx_uint_t free_slot, brix_shared_handle_entry_t **entry)
void brix_session_handle_publish (const u_char sessid[16], int handle_index, const brix_file_t *file)
int brix_session_handle_lookup_hint (const u_char sessid[16], int handle_index, int *inout_slot, brix_shared_handle_entry_t *out)
int brix_session_handle_lookup (const u_char sessid[16], int handle_index, brix_shared_handle_entry_t *out)
void brix_session_handle_unpublish (const u_char sessid[16], int handle_index)
void brix_session_handle_unpublish_all (const u_char sessid[16])
Variables
static ngx_shmtx_t brix_handle_mutex
Function Documentation
brix_handle_shm_init_zone()
ngx_int_t brix_handle_shm_init_zone (ngx_shm_zone_t * shm_zone, void * data)
Definition at line 35 of file handles.c.
References brix_handle_mutex, and brix_shm_table_alloc().
Referenced by brix_configure_session_registry().
brix_session_handle_lookup()
int brix_session_handle_lookup (const u_char sessid[16], int handle_index, brix_shared_handle_entry_t * out)
Definition at line 305 of file handles.c.
References brix_session_handle_lookup_hint().
Referenced by brix_proxy_lazy_open().
brix_session_handle_lookup_hint()
int brix_session_handle_lookup_hint (const u_char sessid[16], int handle_index, int * inout_slot, brix_shared_handle_entry_t * out)
Definition at line 248 of file handles.c.
References brix_handle_mutex, BRIX_MAX_FILES, BRIX_MAX_PATH, BRIX_SESSION_HANDLE_SLOTS, brix_shared_handle_same_key(), handle_table(), ngx_memcpy, brix_shared_handle_entry_t::path, and brix_shared_handle_table_t::slots.
Referenced by brix_ensure_read_handle(), and brix_session_handle_lookup().
brix_session_handle_publish()
void brix_session_handle_publish (const u_char sessid[16], int handle_index, const brix_file_t * file)
Definition at line 197 of file handles.c.
References brix_handle_mutex, BRIX_MAX_FILES, brix_shared_handle_find_slot(), brix_shared_handle_select_target(), brix_shared_handle_store(), brix_file_t::fd, and handle_table().
Referenced by brix_open_send_response(), brix_tpc_prepare_pull(), and brix_zip_open_member().
brix_session_handle_unpublish()
void brix_session_handle_unpublish (const u_char sessid[16], int handle_index)
Definition at line 319 of file handles.c.
References brix_handle_mutex, BRIX_MAX_FILES, BRIX_SESSION_HANDLE_SLOTS, brix_shared_handle_same_key(), handle_table(), and brix_shared_handle_table_t::slots.
Referenced by brix_free_fhandle().
brix_session_handle_unpublish_all()
void brix_session_handle_unpublish_all (const u_char sessid[16])
Definition at line 356 of file handles.c.
References brix_handle_mutex, BRIX_SESSION_HANDLE_SLOTS, BRIX_SESSION_ID_LEN, handle_table(), brix_shared_handle_entry_t::in_use, brix_shared_handle_entry_t::sessid, and brix_shared_handle_table_t::slots.
Referenced by brix_session_finish_eviction(), and brix_session_unregister().
brix_shared_handle_find_slot()
static void brix_shared_handle_find_slot (brix_shared_handle_table_t * tbl, const u_char sessid[16], int handle_index, brix_shared_handle_entry_t ** entry, ngx_uint_t * free_slot) static
Definition at line 87 of file handles.c.
References BRIX_SESSION_HANDLE_SLOTS, brix_shared_handle_same_key(), brix_shared_handle_entry_t::in_use, and brix_shared_handle_table_t::slots.
Referenced by brix_session_handle_publish().
brix_shared_handle_same_key()
static ngx_flag_t brix_shared_handle_same_key (const brix_shared_handle_entry_t * entry, const u_char sessid[16], int handle_index) static
Definition at line 65 of file handles.c.
References BRIX_SESSION_ID_LEN, brix_shared_handle_entry_t::handle_index, brix_shared_handle_entry_t::in_use, and brix_shared_handle_entry_t::sessid.
Referenced by brix_session_handle_lookup_hint(), brix_session_handle_unpublish(), and brix_shared_handle_find_slot().
brix_shared_handle_select_target()
static ngx_flag_t brix_shared_handle_select_target (brix_shared_handle_table_t * tbl, const brix_file_t * file, ngx_uint_t free_slot, brix_shared_handle_entry_t ** entry) static
Definition at line 158 of file handles.c.
References BRIX_MAX_PATH, BRIX_SESSION_HANDLE_SLOTS, brix_file_t::path, brix_file_t::readable, and brix_shared_handle_table_t::slots.
Referenced by brix_session_handle_publish().
brix_shared_handle_store()
static void brix_shared_handle_store (brix_shared_handle_entry_t * entry, const u_char sessid[16], int handle_index, const brix_file_t * file) static
Definition at line 124 of file handles.c.
References BRIX_SESSION_ID_LEN, brix_file_t::cached_size, brix_shared_handle_entry_t::cached_size, brix_file_t::device, brix_shared_handle_entry_t::device, brix_file_t::from_cache, brix_shared_handle_entry_t::from_cache, brix_shared_handle_entry_t::handle_index, brix_shared_handle_entry_t::in_use, brix_file_t::inode, brix_shared_handle_entry_t::inode, brix_file_t::is_regular, brix_shared_handle_entry_t::is_regular, ngx_memcpy, brix_file_t::path, brix_shared_handle_entry_t::path, brix_file_t::readable, brix_shared_handle_entry_t::readable, brix_shared_handle_entry_t::sessid, brix_file_t::writable, and brix_shared_handle_entry_t::writable.
Referenced by brix_session_handle_publish().
handle_table()
static brix_shared_handle_table_t * handle_table (void) static
Definition at line 23 of file handles.c.
References brix_handle_shm_zone.
Referenced by brix_session_handle_lookup_hint(), brix_session_handle_publish(), brix_session_handle_unpublish(), and brix_session_handle_unpublish_all().
Variable Documentation
brix_handle_mutex
ngx_shmtx_t brix_handle_mutex static
Definition at line 20 of file handles.c.
Referenced by brix_handle_shm_init_zone(), brix_session_handle_lookup_hint(), brix_session_handle_publish(), brix_session_handle_unpublish(), and brix_session_handle_unpublish_all().