nginx-xrootd: src/protocols/s3/handler_dispatch.c File Reference
handler_dispatch.c File Reference
#include "s3.h"
#include "s3_handler_internal.h"
#include "tagging.h"
#include "auth/impersonate/lifecycle.h"
#include "core/http/http_body.h"
#include "core/http/http_headers.h"
#include "core/http/http_query.h"
#include "protocols/shared/deleg_capture.h"
#include "fs/backend/sd.h"
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include "auth/authz/acc/acc.h"
#include "core/compat/alloc_guard.h"
Functions
static int s3_parse_uri (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, u_char *key_out, size_t key_sz)
static ngx_int_t s3_dispatch_parse_uri (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, ngx_uint_t method_slot, u_char *key, size_t key_cap)
static ngx_int_t s3_check_token_scope (ngx_http_request_t *r, ngx_http_s3_req_ctx_t *s3ctx, ngx_uint_t method_slot, const u_char *key)
ngx_int_t s3_reject_write_disabled (ngx_http_request_t *r, ngx_uint_t method_slot)
ngx_int_t s3_read_body_metric (ngx_http_request_t *r, ngx_uint_t method_slot, ngx_http_client_body_handler_pt handler)
static ngx_int_t s3_dispatch_empty_post (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, ngx_uint_t method_slot, ngx_flag_t is_post_object_form)
static ngx_int_t s3_dispatch_bucket_get (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, ngx_uint_t method_slot)
static ngx_int_t s3_dispatch_empty_key (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, ngx_uint_t method_slot, ngx_flag_t is_post_object_form)
static ngx_int_t s3_resolve_object_key (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, ngx_http_s3_req_ctx_t *s3ctx, ngx_uint_t method_slot, const u_char *key, char *fs_path, size_t fs_path_cap)
ngx_int_t s3_dispatch_after_auth (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, ngx_http_s3_req_ctx_t *s3ctx, ngx_uint_t method_slot, int is_list_request, ngx_flag_t is_post_object_form)
Function Documentation
s3_check_token_scope()
static ngx_int_t s3_check_token_scope (ngx_http_request_t * r, ngx_http_s3_req_ctx_t * s3ctx, ngx_uint_t method_slot, const u_char * key) static
Definition at line 161 of file handler_dispatch.c.
References brix_identity_t::auth_method, BRIX_AOP_CREATE, BRIX_AOP_DELETE, BRIX_AUTHN_TOKEN, brix_identity_check_token_scope(), BRIX_S3_EVENT_ACCESS_DENIED, BRIX_S3_METRIC_INC, ngx_http_s3_req_ctx_t::identity, key, PATH_MAX, s3_method_aop(), s3_metrics_return_method(), and s3_send_xml_error().
Referenced by s3_dispatch_after_auth().
s3_dispatch_after_auth()
ngx_int_t s3_dispatch_after_auth (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, ngx_http_s3_req_ctx_t * s3ctx, ngx_uint_t method_slot, int is_list_request, ngx_flag_t is_post_object_form)
Definition at line 311 of file handler_dispatch.c.
References key, PATH_MAX, s3_check_token_scope(), s3_dispatch_empty_key(), s3_dispatch_object_method(), s3_dispatch_parse_uri(), s3_handle_list(), S3_MAX_KEY, s3_metrics_return_method(), and s3_resolve_object_key().
Referenced by ngx_http_s3_handler().
s3_dispatch_bucket_get()
static ngx_int_t s3_dispatch_bucket_get (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, ngx_uint_t method_slot) static
Definition at line 231 of file handler_dispatch.c.
References s3_handle_get_acl(), s3_handle_get_bucket_location(), s3_handle_get_bucket_versioning(), s3_handle_get_cors(), s3_handle_list_multipart_uploads(), s3_handle_list_v1(), s3_has_query_flag(), and s3_metrics_return_method().
Referenced by s3_dispatch_empty_key().
s3_dispatch_empty_key()
static ngx_int_t s3_dispatch_empty_key (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, ngx_uint_t method_slot, ngx_flag_t is_post_object_form) static
Definition at line 258 of file handler_dispatch.c.
References BRIX_S3_EVENT_INVALID_URI, BRIX_S3_METRIC_INC, s3_dispatch_bucket_get(), s3_dispatch_empty_post(), s3_handle_head_bucket(), s3_metrics_return_method(), and s3_send_xml_error().
Referenced by s3_dispatch_after_auth().
s3_dispatch_empty_post()
static ngx_int_t s3_dispatch_empty_post (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, ngx_uint_t method_slot, ngx_flag_t is_post_object_form) static
Definition at line 211 of file handler_dispatch.c.
References ngx_http_brix_shared_conf_t::allow_write, ngx_http_s3_loc_conf_t::common, s3_delete_objects_body_handler(), s3_has_query_flag(), s3_post_object_body_handler(), s3_read_body_metric(), and s3_reject_write_disabled().
Referenced by s3_dispatch_empty_key().
s3_dispatch_parse_uri()
static ngx_int_t s3_dispatch_parse_uri (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, ngx_uint_t method_slot, u_char * key, size_t key_cap) static
Definition at line 131 of file handler_dispatch.c.
References BRIX_S3_EVENT_INVALID_URI, BRIX_S3_METRIC_INC, key, s3_metrics_return_method(), s3_parse_uri(), and s3_send_xml_error().
Referenced by s3_dispatch_after_auth().
s3_parse_uri()
static int s3_parse_uri (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, u_char * key_out, size_t key_sz) static
Definition at line 71 of file handler_dispatch.c.
References brix_http_urldecode(), BRIX_URLDECODE_OK, BRIX_URLDECODE_PLUS_TO_SPACE, BRIX_URLDECODE_REJECT_NUL, and ngx_http_s3_loc_conf_t::bucket.
Referenced by s3_dispatch_parse_uri().
s3_read_body_metric()
ngx_int_t s3_read_body_metric (ngx_http_request_t * r, ngx_uint_t method_slot, ngx_http_client_body_handler_pt handler)
Definition at line 200 of file handler_dispatch.c.
References brix_http_read_body(), handler, and s3_metrics_return_method().
Referenced by s3_dispatch_empty_post(), s3_dispatch_object_post(), and s3_dispatch_object_put().
s3_reject_write_disabled()
ngx_int_t s3_reject_write_disabled (ngx_http_request_t * r, ngx_uint_t method_slot)
Definition at line 190 of file handler_dispatch.c.
References BRIX_S3_EVENT_WRITE_DISABLED, BRIX_S3_METRIC_INC, s3_metrics_return_method(), and s3_send_xml_error().
Referenced by s3_dispatch_empty_post(), s3_dispatch_object_delete(), s3_dispatch_object_post(), and s3_dispatch_object_put().
s3_resolve_object_key()
static ngx_int_t s3_resolve_object_key (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, ngx_http_s3_req_ctx_t * s3ctx, ngx_uint_t method_slot, const u_char * key, char * fs_path, size_t fs_path_cap) static
Definition at line 288 of file handler_dispatch.c.
References BRIX_S3_EVENT_ACCESS_DENIED, BRIX_S3_METRIC_INC, ngx_http_brix_shared_conf_t::cache_store_endpoint, ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::fs_path, key, ngx_http_brix_shared_conf_t::root_canon, s3_metrics_return_method(), s3_resolve_key(), and s3_send_xml_error().
Referenced by s3_dispatch_after_auth().