nginx-xrootd: src/protocols/root/handshake/handshake.h File Reference
handshake.h File Reference
#include "core/ngx_brix_module.h"
Macros
#define BRIX_DISPATCH_CONTINUE NGX_DECLINED
#define BRIX_MIN_SEC_NONE 0
#define BRIX_MIN_SEC_COMPAT 1
#define BRIX_MIN_SEC_INTENSE 2
Functions
ngx_int_t brix_verify_pending_sigver (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_signing_enforce_level (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_min_sec_enforce (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_dispatch_require_login (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_dispatch_require_auth (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_dispatch_require_write (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_dispatch_session_opcode (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_dispatch_read_opcode (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_dispatch_write_opcode (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_dispatch_signing_opcode (brix_ctx_t *ctx, ngx_connection_t *c)
Macro Definition Documentation
BRIX_DISPATCH_CONTINUE
#define BRIX_DISPATCH_CONTINUE NGX_DECLINED
Definition at line 11 of file handshake.h.
BRIX_MIN_SEC_COMPAT
#define BRIX_MIN_SEC_COMPAT 1
Definition at line 47 of file handshake.h.
BRIX_MIN_SEC_INTENSE
#define BRIX_MIN_SEC_INTENSE 2
Definition at line 48 of file handshake.h.
BRIX_MIN_SEC_NONE
#define BRIX_MIN_SEC_NONE 0
Definition at line 46 of file handshake.h.
Function Documentation
brix_dispatch_read_opcode()
ngx_int_t brix_dispatch_read_opcode (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 44 of file dispatch_read.c.
References BRIX_DISPATCH_CONTINUE, brix_handle_clone(), brix_handle_close(), brix_handle_dirlist(), brix_handle_fattr(), brix_handle_locate(), brix_handle_open(), brix_handle_pgread(), brix_handle_prepare(), brix_handle_query(), brix_handle_read(), brix_handle_readlink(), brix_handle_readv(), brix_handle_stat(), brix_handle_statx(), brix_ctx_recv_t::cur_reqid, DISPATCH_RD, DISPATCH_RD_BOUND, kXR_clone, kXR_close, kXR_dirlist, kXR_fattr, kXR_locate, kXR_open, kXR_pgread, kXR_prepare, kXR_query, kXR_read, kXR_readlink, kXR_readv, kXR_stat, kXR_statx, and brix_ctx_t::recv.
Referenced by brix_dispatch().
brix_dispatch_require_auth()
ngx_int_t brix_dispatch_require_auth (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 96 of file policy.c.
References brix_ctx_login_t::auth_done, BRIX_DISPATCH_CONTINUE, brix_send_error(), c, kXR_NotAuthorized, brix_ctx_login_t::logged_in, and brix_ctx_t::login.
Referenced by brix_dispatch_require_write().
brix_dispatch_require_login()
ngx_int_t brix_dispatch_require_login (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 85 of file policy.c.
References BRIX_DISPATCH_CONTINUE, brix_send_error(), c, kXR_NotAuthorized, brix_ctx_login_t::logged_in, and brix_ctx_t::login.
Referenced by brix_dispatch_session_opcode(), and brix_dispatch_signing_opcode().
brix_dispatch_require_write()
ngx_int_t brix_dispatch_require_write (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 107 of file policy.c.
References BRIX_DISPATCH_CONTINUE, brix_dispatch_require_auth(), brix_send_error(), c, brix_ctx_t::is_bound, kXR_fsReadOnly, and kXR_NotAuthorized.
Referenced by brix_dispatch_write_opcode().
brix_dispatch_session_opcode()
ngx_int_t brix_dispatch_session_opcode (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 16 of file dispatch_session.c.
References BRIX_DISPATCH_CONTINUE, brix_dispatch_require_login(), brix_handle_auth(), brix_handle_bind(), brix_handle_endsess(), brix_handle_login(), brix_handle_ping(), brix_handle_protocol(), brix_handle_set(), c, brix_ctx_recv_t::cur_reqid, kXR_auth, kXR_bind, kXR_endsess, kXR_login, kXR_ping, kXR_protocol, kXR_set, and brix_ctx_t::recv.
Referenced by brix_dispatch().
brix_dispatch_signing_opcode()
ngx_int_t brix_dispatch_signing_opcode (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 9 of file dispatch_signing.c.
References BRIX_DISPATCH_CONTINUE, brix_dispatch_require_login(), brix_handle_sigver(), c, brix_ctx_recv_t::cur_reqid, kXR_sigver, and brix_ctx_t::recv.
Referenced by brix_dispatch().
brix_dispatch_write_opcode()
ngx_int_t brix_dispatch_write_opcode (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 138 of file dispatch_write.c.
References BRIX_DISPATCH_CONTINUE, brix_dispatch_require_write(), brix_wr_routes, c, brix_ctx_recv_t::cur_reqid, brix_wr_route_t::fn2, brix_wr_route_t::fn3, manager_redirect_mutation(), brix_wr_route_t::op, and brix_ctx_t::recv.
Referenced by brix_dispatch().
brix_min_sec_enforce()
ngx_int_t brix_min_sec_enforce (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 43 of file policy.c.
References BRIX_AUTH_NONE, BRIX_DISPATCH_CONTINUE, BRIX_MIN_SEC_INTENSE, BRIX_MIN_SEC_NONE, brix_send_error(), c, brix_ctx_recv_t::cur_reqid, kXR_NotAuthorized, kXR_TLSRequired, and brix_ctx_t::recv.
Referenced by brix_dispatch().
brix_signing_enforce_level()
ngx_int_t brix_signing_enforce_level (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 145 of file sigver.c.
References BRIX_DISPATCH_CONTINUE, brix_send_error(), brix_sigver_opcode_requires(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, kXR_NotAuthorized, brix_ctx_sigver_t::nodata, brix_ctx_t::recv, brix_ctx_sigver_t::signing_active, brix_ctx_t::sigver, and brix_ctx_sigver_t::verified.
Referenced by brix_dispatch().
brix_verify_pending_sigver()
ngx_int_t brix_verify_pending_sigver (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 87 of file sigver.c.
References BRIX_DISPATCH_CONTINUE, brix_send_error(), brix_verify_sigver_hmac(), c, brix_ctx_recv_t::cur_reqid, brix_ctx_sigver_t::expectrid, kXR_InvalidRequest, kXR_sigver, brix_ctx_sigver_t::pending, brix_ctx_t::recv, brix_ctx_sigver_t::signing_active, brix_ctx_t::sigver, and brix_ctx_sigver_t::verified.
Referenced by brix_dispatch().