nginx-xrootd: src/protocols/s3/handler_object_route.c File Reference
handler_object_route.c File Reference
#include "s3.h"
#include "s3_handler_internal.h"
#include "tagging.h"
#include "auth/impersonate/lifecycle.h"
#include "core/http/http_body.h"
#include "core/http/http_headers.h"
#include "core/http/http_query.h"
#include "protocols/shared/deleg_capture.h"
#include "fs/backend/sd.h"
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include "auth/authz/acc/acc.h"
#include "core/compat/alloc_guard.h"
Functions
static int s3_upload_id_is_hex (const char *upload_id)
static ngx_int_t s3_dispatch_object_get (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, ngx_uint_t method_slot, const u_char *key, char *fs_path)
static ngx_int_t s3_prepare_upload_part (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, ngx_http_s3_req_ctx_t *s3ctx, ngx_uint_t method_slot, char *fs_path)
static ngx_int_t s3_apply_put_precondition (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, ngx_http_s3_req_ctx_t *s3ctx, ngx_uint_t method_slot, const char *fs_path)
static ngx_int_t s3_dispatch_object_put (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, ngx_http_s3_req_ctx_t *s3ctx, ngx_uint_t method_slot, char *fs_path)
static ngx_int_t s3_dispatch_object_delete (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, ngx_uint_t method_slot, char *fs_path)
static ngx_int_t s3_dispatch_object_post (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, ngx_uint_t method_slot, const u_char *key, char *fs_path)
ngx_int_t s3_dispatch_object_method (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, ngx_http_s3_req_ctx_t *s3ctx, ngx_uint_t method_slot, const u_char *key, char *fs_path)
Function Documentation
s3_apply_put_precondition()
static ngx_int_t s3_apply_put_precondition (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, ngx_http_s3_req_ctx_t * s3ctx, ngx_uint_t method_slot, const char * fs_path) static
Definition at line 124 of file handler_object_route.c.
References ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::exclusive_create, ngx_http_brix_shared_conf_t::root_canon, s3_get_query_param(), s3_metrics_return_method(), s3_put_is_exclusive_create(), and s3_put_precondition().
Referenced by s3_dispatch_object_put().
s3_dispatch_object_delete()
static ngx_int_t s3_dispatch_object_delete (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, ngx_uint_t method_slot, char * fs_path) static
Definition at line 182 of file handler_object_route.c.
References ngx_http_brix_shared_conf_t::allow_write, ngx_http_s3_loc_conf_t::common, s3_get_query_param(), s3_handle_delete(), s3_handle_delete_object_tagging(), s3_handle_multipart_abort(), s3_has_query_flag(), s3_metrics_return_method(), and s3_reject_write_disabled().
Referenced by s3_dispatch_object_method().
s3_dispatch_object_get()
static ngx_int_t s3_dispatch_object_get (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, ngx_uint_t method_slot, const u_char * key, char * fs_path) static
Definition at line 58 of file handler_object_route.c.
References key, s3_get_query_param(), s3_handle_get(), s3_handle_get_acl(), s3_handle_get_object_tagging(), s3_handle_list_parts(), s3_has_query_flag(), and s3_metrics_return_method().
Referenced by s3_dispatch_object_method().
s3_dispatch_object_method()
ngx_int_t s3_dispatch_object_method (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, ngx_http_s3_req_ctx_t * s3ctx, ngx_uint_t method_slot, const u_char * key, char * fs_path)
Definition at line 227 of file handler_object_route.c.
References BRIX_S3_EVENT_METHOD_NOT_ALLOWED, BRIX_S3_METRIC_INC, key, s3_dispatch_object_delete(), s3_dispatch_object_get(), s3_dispatch_object_post(), s3_dispatch_object_put(), s3_handle_head(), and s3_metrics_return_method().
Referenced by s3_dispatch_after_auth().
s3_dispatch_object_post()
static ngx_int_t s3_dispatch_object_post (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, ngx_uint_t method_slot, const u_char * key, char * fs_path) static
Definition at line 203 of file handler_object_route.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_S3_EVENT_METHOD_NOT_ALLOWED, BRIX_S3_METRIC_INC, ngx_http_s3_loc_conf_t::common, key, s3_get_query_param(), s3_handle_multipart_initiate(), s3_has_query_flag(), s3_metrics_return_method(), s3_multipart_complete_body_handler(), s3_read_body_metric(), and s3_reject_write_disabled().
Referenced by s3_dispatch_object_method().
s3_dispatch_object_put()
static ngx_int_t s3_dispatch_object_put (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, ngx_http_s3_req_ctx_t * s3ctx, ngx_uint_t method_slot, char * fs_path) static
Definition at line 146 of file handler_object_route.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_http_find_header(), ngx_http_s3_loc_conf_t::common, s3_apply_put_precondition(), s3_handle_copy_object(), s3_has_query_flag(), s3_metrics_return_method(), s3_prepare_upload_part(), s3_put_body_handler(), s3_put_object_tagging_body_handler(), s3_read_body_metric(), s3_reject_write_disabled(), and s3_send_xml_error().
Referenced by s3_dispatch_object_method().
s3_prepare_upload_part()
static ngx_int_t s3_prepare_upload_part (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, ngx_http_s3_req_ctx_t * s3ctx, ngx_uint_t method_slot, char * fs_path) static
Definition at line 80 of file handler_object_route.c.
References brix_http_find_header(), ngx_http_s3_req_ctx_t::fs_path, PATH_MAX, s3_get_mpu_dir(), s3_get_query_param(), s3_handle_upload_part_copy(), s3_has_query_flag(), s3_metrics_return_method(), s3_send_xml_error(), and s3_upload_id_is_hex().
Referenced by s3_dispatch_object_put().
s3_upload_id_is_hex()
static int s3_upload_id_is_hex (const char * upload_id) static
Definition at line 45 of file handler_object_route.c.
References c.
Referenced by s3_prepare_upload_part().