nginx-xrootd: src/protocols/root/handoff/handoff.c File Reference
handoff.c File Reference
#include "core/ngx_brix_module.h"
#include "handoff.h"
Data Structures
struct brix_handoff_t
Macros
#define BRIX_HANDOFF_BUF (64 * 1024)
#define BRIX_HANDOFF_IDLE 75000 /* ms; drop a relay that stalls both ways */
Functions
char * brix_conf_set_http_handoff (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static ngx_int_t handoff_peer_get (ngx_peer_connection_t *pc, void *data)
static void handoff_peer_free (ngx_peer_connection_t *pc, void *data, ngx_uint_t state)
static void handoff_close (brix_handoff_t *h)
static ngx_int_t handoff_pump (ngx_connection_t *from, ngx_connection_t *to, u_char *buf, size_t *off, size_t *end)
static brix_handoff_t * handoff_from_client (ngx_event_t *ev)
static void handoff_cu (brix_handoff_t *h, ngx_event_t *ev)
static void handoff_uc (brix_handoff_t *h, ngx_event_t *ev)
static void handoff_client_read (ngx_event_t *ev)
static void handoff_client_write (ngx_event_t *ev)
static void handoff_upstream_read (ngx_event_t *ev)
static void handoff_upstream_write (ngx_event_t *ev)
static void handoff_begin_relay (brix_handoff_t *h)
static void handoff_connect_done (ngx_event_t *ev)
ngx_int_t brix_http_handoff_start (ngx_stream_session_t *s, ngx_connection_t *c, void *srv_conf, u_char *prefix, size_t prefix_len)
Macro Definition Documentation
BRIX_HANDOFF_BUF
#define BRIX_HANDOFF_BUF (64 * 1024)
Definition at line 12 of file handoff.c.
BRIX_HANDOFF_IDLE
#define BRIX_HANDOFF_IDLE 75000 /* ms; drop a relay that stalls both ways */
Definition at line 13 of file handoff.c.
Function Documentation
brix_conf_set_http_handoff()
char * brix_conf_set_http_handoff (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 37 of file handoff.c.
References ngx_memcpy, ngx_pcalloc(), and ngx_pnalloc().
brix_http_handoff_start()
ngx_int_t brix_http_handoff_start (ngx_stream_session_t * s, ngx_connection_t * c, void * srv_conf, u_char * prefix, size_t prefix_len)
Definition at line 279 of file handoff.c.
References BRIX_HANDOFF_BUF, BRIX_HANDOFF_IDLE, c, brix_handoff_t::client, brix_handoff_t::cu, brix_handoff_t::cu_end, brix_handoff_t::cu_off, brix_ctx_t::handoff, handoff_begin_relay(), handoff_connect_done(), handoff_peer_free(), handoff_peer_get(), handoff_upstream_read(), brix_ctx_t::metrics, brix_handoff_t::metrics, ngx_memcpy, ngx_pcalloc(), ngx_pnalloc(), ngx_stream_brix_module, brix_handoff_t::peer, brix_handoff_t::s, s, brix_ctx_t::state, brix_handoff_t::uc, brix_handoff_t::upstream, and XRD_ST_PROXY.
Referenced by brix_recv_handle_nonxrootd().
handoff_begin_relay()
static void handoff_begin_relay (brix_handoff_t * h) static
Definition at line 225 of file handoff.c.
References brix_handoff_t::client, brix_handoff_t::connected, brix_handoff_t::cu, brix_handoff_t::cu_end, brix_handoff_t::cu_off, handoff_client_read(), handoff_client_write(), handoff_close(), handoff_pump(), handoff_upstream_read(), handoff_upstream_write(), brix_handoff_t::uc, brix_handoff_t::uc_end, brix_handoff_t::uc_off, and brix_handoff_t::upstream.
Referenced by brix_http_handoff_start(), and handoff_connect_done().
handoff_client_read()
static void handoff_client_read (ngx_event_t * ev) static
Definition at line 208 of file handoff.c.
References handoff_cu(), and handoff_from_client().
Referenced by handoff_begin_relay().
handoff_client_write()
static void handoff_client_write (ngx_event_t * ev) static
Definition at line 211 of file handoff.c.
References handoff_from_client(), and handoff_uc().
Referenced by handoff_begin_relay().
handoff_close()
static void handoff_close (brix_handoff_t * h) static
Definition at line 98 of file handoff.c.
References brix_handoff_t::closed, ngx_brix_srv_metrics_t::connections_active, brix_handoff_t::metrics, brix_handoff_t::s, and brix_handoff_t::upstream.
Referenced by handoff_begin_relay(), handoff_connect_done(), handoff_cu(), and handoff_uc().
handoff_connect_done()
static void handoff_connect_done (ngx_event_t * ev) static
Definition at line 250 of file handoff.c.
References brix_handoff_t::client, handoff_begin_relay(), handoff_close(), and brix_handoff_t::peer.
Referenced by brix_http_handoff_start().
handoff_cu()
static void handoff_cu (brix_handoff_t * h, ngx_event_t * ev) static
Definition at line 180 of file handoff.c.
References brix_handoff_t::client, brix_handoff_t::cu, brix_handoff_t::cu_end, brix_handoff_t::cu_off, handoff_close(), handoff_pump(), and brix_handoff_t::upstream.
Referenced by handoff_client_read(), and handoff_upstream_write().
handoff_from_client()
static brix_handoff_t * handoff_from_client (ngx_event_t * ev) static
Definition at line 168 of file handoff.c.
References c, brix_ctx_t::handoff, ngx_stream_brix_module, and s.
Referenced by handoff_client_read(), and handoff_client_write().
handoff_peer_free()
static void handoff_peer_free (ngx_peer_connection_t * pc, void * data, ngx_uint_t state) static
Definition at line 90 of file handoff.c.
Referenced by brix_http_handoff_start().
handoff_peer_get()
static ngx_int_t handoff_peer_get (ngx_peer_connection_t * pc, void * data) static
Definition at line 87 of file handoff.c.
Referenced by brix_http_handoff_start().
handoff_pump()
static ngx_int_t handoff_pump (ngx_connection_t * from, ngx_connection_t * to, u_char * buf, size_t * off, size_t * end) static
Definition at line 125 of file handoff.c.
References BRIX_HANDOFF_BUF, and BRIX_HANDOFF_IDLE.
Referenced by handoff_begin_relay(), handoff_cu(), and handoff_uc().
handoff_uc()
static void handoff_uc (brix_handoff_t * h, ngx_event_t * ev) static
Definition at line 195 of file handoff.c.
References brix_handoff_t::client, handoff_close(), handoff_pump(), brix_handoff_t::uc, brix_handoff_t::uc_end, brix_handoff_t::uc_off, and brix_handoff_t::upstream.
Referenced by handoff_client_write(), and handoff_upstream_read().
handoff_upstream_read()
static void handoff_upstream_read (ngx_event_t * ev) static
Definition at line 214 of file handoff.c.
References handoff_uc().
Referenced by brix_http_handoff_start(), and handoff_begin_relay().
handoff_upstream_write()
static void handoff_upstream_write (ngx_event_t * ev) static
Definition at line 217 of file handoff.c.
References handoff_cu().
Referenced by handoff_begin_relay().