nginx-xrootd: src/protocols/root/connection/handler.h File Reference
handler.h File Reference
#include "core/ngx_brix_module.h"
Functions
void ngx_stream_brix_handler (ngx_stream_session_t *s)
void ngx_stream_brix_recv (ngx_event_t *rev)
void ngx_stream_brix_send (ngx_event_t *wev)
Function Documentation
ngx_stream_brix_handler()
void ngx_stream_brix_handler (ngx_stream_session_t * s)
Definition at line 7 of file handler.c.
References ngx_stream_brix_srv_conf_t::auth, ngx_brix_srv_metrics_t::auth, brix_apply_tcp_congestion(), brix_apply_tcp_deadpeer_opts(), BRIX_AUTH_GSI, BRIX_AUTH_KRB5, BRIX_AUTH_SSS, BRIX_AUTH_TOKEN, BRIX_AUTH_UNIX, brix_identity_alloc(), BRIX_MAX_FILES, BRIX_PROXY_MAX_UPSTREAMS, BRIX_PROXY_UPSTREAM_LABEL_LEN, brix_relay_start(), BRIX_SESSION_ID_LEN, c, ngx_stream_brix_srv_conf_t::cache, ngx_brix_srv_metrics_t::cache_enabled, ngx_stream_brix_srv_conf_t::cache_eviction_threshold, ngx_brix_srv_metrics_t::cache_eviction_threshold, ngx_stream_brix_srv_conf_t::cache_root, ngx_brix_srv_metrics_t::cache_root, ngx_brix_srv_metrics_t::connections_active, ngx_brix_srv_metrics_t::connections_rejected_total, ngx_brix_srv_metrics_t::connections_total, brix_ctx_t::deadline, brix_file_t::fd, brix_ctx_t::files, brix_ctx_deadline_t::handshake_ms, ngx_stream_brix_srv_conf_t::handshake_timeout, brix_ctx_recv_t::hdr_pos, brix_proxy_upstream_t::host, brix_ctx_t::identity, ngx_brix_srv_metrics_t::in_use, brix_ctx_t::ip_version, ngx_brix_proxy_upstream_metrics_t::label, brix_ctx_t::login, ngx_stream_brix_srv_conf_t::max_connections, brix_ctx_t::metrics, ngx_stream_brix_srv_conf_t::metrics_slot, ngx_brix_shm_zone, ngx_stream_brix_module, ngx_stream_brix_recv(), ngx_stream_brix_send(), brix_ctx_t::out, brix_ctx_login_t::peer_ip, ngx_stream_brix_srv_conf_t::pipeline_depth, brix_ctx_out_t::pipeline_depth, brix_ctx_rd_t::pool, brix_proxy_upstream_t::port, ngx_brix_srv_metrics_t::port, brix_ctx_t::protocol_label, ngx_stream_brix_srv_conf_t::proxy, ngx_brix_srv_metrics_t::proxy, brix_ctx_t::rd, brix_ctx_deadline_t::read_ms, ngx_stream_brix_srv_conf_t::read_timeout, brix_ctx_t::recv, ngx_stream_brix_srv_conf_t::relay_addr, brix_ctx_out_t::ring, s, brix_ctx_deadline_t::send_ms, ngx_stream_brix_srv_conf_t::send_timeout, ngx_brix_metrics_t::servers, brix_ctx_login_t::sessid, brix_ctx_t::session, brix_file_t::shared_handle_slot_hint, brix_ctx_t::state, ngx_stream_brix_srv_conf_t::tcp_congestion, ngx_stream_brix_srv_conf_t::tcp_keepalive, ngx_stream_brix_srv_conf_t::tcp_user_timeout, brix_proxy_conf_t::upstreams, ngx_brix_proxy_metrics_t::upstreams, and XRD_ST_HANDSHAKE.
Referenced by ngx_stream_brix_enable().
ngx_stream_brix_recv()
void ngx_stream_brix_recv (ngx_event_t * rev)
Definition at line 253 of file recv.c.
References ClientRequestHdr::body, brix_arm_read_deadline(), brix_budget_sync(), brix_ckpxeq_body_extra(), brix_close_all_files(), brix_ctx_has_open_file(), brix_defer_teardown_if_writing(), brix_disarm_read_deadline(), brix_dispatch(), brix_ensure_payload_buffer(), brix_grow_payload_buffer(), brix_http_handoff_start(), brix_max_payload_for_request(), brix_on_disconnect(), brix_process_handshake(), BRIX_RECV_BREAK, brix_recv_handoff_state(), brix_recv_pre_loop(), BRIX_RECV_RETURN, BRIX_SRV_METRIC_ADD, BRIX_SRV_METRIC_INC, brix_start_tls(), brix_trim_scratch(), brix_writev_body_extra(), c, brix_ctx_out_t::count, brix_ctx_recv_t::cur_body, brix_ctx_recv_t::cur_body_extended, brix_ctx_recv_t::cur_body_extra, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, brix_ctx_recv_t::cur_streamid, ClientRequestHdr::dlen, brix_ctx_recv_t::hdr_buf, brix_ctx_recv_t::hdr_pos, ngx_stream_brix_srv_conf_t::http_handoff_addr, kXR_chkpoint, kXR_ckpXeq, kXR_read, kXR_write, kXR_writev, ngx_stream_brix_module, brix_ctx_t::out, brix_ctx_recv_t::payload, brix_ctx_recv_t::payload_pos, brix_ctx_out_t::pipeline_depth, brix_ctx_t::rd, brix_ctx_t::recv, brix_ctx_out_t::recv_deferred, ClientRequestHdr::requestid, brix_ctx_out_t::resp_pipelinable, s, brix_ctx_t::state, ClientRequestHdr::streamid, brix_ctx_t::tls_pending, brix_ctx_rd_t::win_active, brix_ctx_out_t::wr_inflight, XRD_HANDSHAKE_LEN, XRD_REQUEST_HDR_LEN, XRD_ST_AIO, XRD_ST_HANDSHAKE, XRD_ST_REQ_HEADER, XRD_ST_REQ_PAYLOAD, and XRD_ST_SENDING.
Referenced by brix_tls_handshake_done(), ngx_stream_brix_handler(), and ngx_stream_brix_send().
ngx_stream_brix_send()
void ngx_stream_brix_send (ngx_event_t * wev)
Definition at line 22 of file send.c.
References brix_close_all_files(), brix_defer_teardown_if_writing(), brix_flush_pending(), brix_on_disconnect(), brix_read_window_pump(), BRIX_SRV_METRIC_INC, brix_start_tls(), c, brix_ctx_t::deadline, brix_ctx_recv_t::hdr_pos, ngx_stream_brix_module, ngx_stream_brix_recv(), brix_ctx_t::rd, brix_ctx_t::recv, s, brix_ctx_deadline_t::send_armed, brix_ctx_t::state, brix_ctx_t::tls_pending, brix_ctx_rd_t::win_active, XRD_ST_REQ_HEADER, and XRD_ST_SENDING.
Referenced by brix_tls_handshake_done(), and ngx_stream_brix_handler().