nginx-xrootd: src/net/manager/health_check.h File Reference
health_check.h File Reference
#include "core/ngx_brix_module.h"
Macros
#define BRIX_HC_TYPE_PING 0 /* kXR_ping — protocol-level liveness */
#define BRIX_HC_TYPE_STAT 1 /* kXR_stat "/" — exercises path/stat chain */
Functions
void brix_hc_manager_start (ngx_cycle_t *cycle, ngx_stream_brix_srv_conf_t *conf)
Macro Definition Documentation
BRIX_HC_TYPE_PING
#define BRIX_HC_TYPE_PING 0 /* kXR_ping — protocol-level liveness */
Definition at line 18 of file health_check.h.
BRIX_HC_TYPE_STAT
#define BRIX_HC_TYPE_STAT 1 /* kXR_stat "/" — exercises path/stat chain */
Definition at line 19 of file health_check.h.
Function Documentation
brix_hc_manager_start()
void brix_hc_manager_start (ngx_cycle_t * cycle, ngx_stream_brix_srv_conf_t * conf)
Definition at line 667 of file health_check.c.
References brix_hc_timer_handler(), BRIX_SRV_REGISTRY_SLOTS, brix_hc_mgr_t::conf, brix_hc_mgr_t::cycle, ngx_pcalloc(), brix_hc_mgr_t::scan_interval_ms, and brix_hc_mgr_t::timer.
Referenced by brix_init_one_server().