nginx-xrootd: src/net/manager/health_check.c File Reference
health_check.c File Reference
#include "health_check.h"
#include "registry.h"
#include "observability/metrics/metrics_macros.h"
#include "core/compat/log_diag.h"
#include <netdb.h>
#include <sys/socket.h>
Data Structures
struct brix_hc_ctx_t
struct brix_hc_mgr_t
Macros
#define BRIX_HC_METRIC_INC(field)
Enumerations
enum brix_hc_phase_t { XRD_HC_HANDSHAKE = 0 , XRD_HC_PROTOCOL , XRD_HC_LOGIN , XRD_HC_PROBE }
Functions
void brix_upstream_build_bootstrap_flags (u_char *buf, uint8_t protocol_flags)
void brix_upstream_build_login (ClientLoginRequest *req)
static void brix_hc_write_handler (ngx_event_t *wev)
static void brix_hc_read_handler (ngx_event_t *rev)
static void brix_hc_timeout_handler (ngx_event_t *ev)
static void brix_hc_finish (brix_hc_ctx_t *hc, int passed)
static ngx_int_t brix_hc_flush (brix_hc_ctx_t *hc)
static void brix_hc_send_probe (brix_hc_ctx_t *hc)
static ngx_int_t brix_hc_recv_frame (brix_hc_ctx_t *hc)
static ngx_int_t brix_hc_dispatch_protocol (brix_hc_ctx_t *hc)
static void brix_hc_dispatch (brix_hc_ctx_t *hc)
static void brix_hc_pre_connect_fail (struct addrinfo *res, const char *host, uint16_t port, ngx_stream_brix_srv_conf_t *conf, ngx_pool_t *pool)
static brix_hc_ctx_t * brix_hc_ctx_create (ngx_cycle_t *cycle, ngx_stream_brix_srv_conf_t *conf, const char *host, uint16_t port)
static struct addrinfo * brix_hc_resolve (brix_hc_ctx_t *hc, const char *host, uint16_t port)
static ngx_int_t brix_hc_open_conn (ngx_cycle_t *cycle, brix_hc_ctx_t *hc, struct addrinfo *res, const char *host, uint16_t port)
static ngx_int_t brix_hc_queue_bootstrap (brix_hc_ctx_t *hc)
static void brix_hc_begin_connect (brix_hc_ctx_t *hc, struct addrinfo *res)
static void brix_hc_start (ngx_cycle_t *cycle, ngx_stream_brix_srv_conf_t *conf, const char *host, uint16_t port)
static void brix_hc_timer_handler (ngx_event_t *ev)
void brix_hc_manager_start (ngx_cycle_t *cycle, ngx_stream_brix_srv_conf_t *conf)
Macro Definition Documentation
BRIX_HC_METRIC_INC
#define BRIX_HC_METRIC_INC (field)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_m = brix_metrics_shared();                  \
        if (_m != NULL) { (void) ngx_atomic_fetch_add(&_m->field, 1); }      \
    } while (0)
Definition at line 108 of file health_check.c.
Enumeration Type Documentation
brix_hc_phase_t
enum brix_hc_phase_t
Enumerator
XRD_HC_HANDSHAKE
XRD_HC_PROTOCOL
XRD_HC_LOGIN
XRD_HC_PROBE
Definition at line 42 of file health_check.c.
Function Documentation
brix_hc_begin_connect()
static void brix_hc_begin_connect (brix_hc_ctx_t * hc, struct addrinfo * res) static
Definition at line 767 of file health_check.c.
References brix_hc_finish(), brix_hc_flush(), brix_hc_ctx_t::conn, and brix_hc_ctx_t::connecting.
Referenced by brix_hc_start().
brix_hc_ctx_create()
static brix_hc_ctx_t * brix_hc_ctx_create (ngx_cycle_t * cycle, ngx_stream_brix_srv_conf_t * conf, const char * host, uint16_t port) static
Definition at line 620 of file health_check.c.
References brix_hc_ctx_t::blacklist_ms, brix_srv_hc_fail(), brix_hc_ctx_t::conf, host, brix_hc_ctx_t::host, brix_hc_ctx_t::log, ngx_pcalloc(), brix_hc_ctx_t::phase, brix_hc_ctx_t::pool, port, brix_hc_ctx_t::port, brix_hc_ctx_t::probe_type, brix_hc_ctx_t::threshold, and XRD_HC_HANDSHAKE.
Referenced by brix_hc_start().
brix_hc_dispatch()
static void brix_hc_dispatch (brix_hc_ctx_t * hc) static
Definition at line 450 of file health_check.c.
References brix_hc_dispatch_protocol(), brix_hc_finish(), brix_hc_send_probe(), brix_hc_ctx_t::conn, kXR_authmore, kXR_ok, brix_hc_ctx_t::phase, brix_hc_ctx_t::resp_body, brix_hc_ctx_t::resp_body_pos, brix_hc_ctx_t::resp_dlen, brix_hc_ctx_t::resp_status, brix_hc_ctx_t::rhdr_pos, XRD_HC_HANDSHAKE, XRD_HC_LOGIN, XRD_HC_PROBE, and XRD_HC_PROTOCOL.
Referenced by brix_hc_read_handler().
brix_hc_dispatch_protocol()
static ngx_int_t brix_hc_dispatch_protocol (brix_hc_ctx_t * hc) static
Definition at line 375 of file health_check.c.
References brix_hc_finish(), brix_hc_flush(), brix_upstream_build_login(), brix_hc_ctx_t::conf, brix_hc_ctx_t::conn, brix_hc_ctx_t::host, kXR_gotoTLS, kXR_ok, brix_hc_ctx_t::log, ngx_memcpy, brix_hc_ctx_t::phase, brix_hc_ctx_t::pool, brix_hc_ctx_t::port, brix_hc_ctx_t::resp_body, brix_hc_ctx_t::resp_body_pos, brix_hc_ctx_t::resp_dlen, brix_hc_ctx_t::resp_status, brix_hc_ctx_t::rhdr_pos, brix_hc_ctx_t::tls_capable, brix_hc_ctx_t::wbuf, brix_hc_ctx_t::wbuf_len, brix_hc_ctx_t::wbuf_pos, and XRD_HC_LOGIN.
Referenced by brix_hc_dispatch().
brix_hc_finish()
static void brix_hc_finish (brix_hc_ctx_t * hc, int passed) static
Definition at line 557 of file health_check.c.
References brix_hc_ctx_t::blacklist_ms, BRIX_HC_METRIC_INC, brix_srv_hc_fail(), brix_srv_hc_pass(), brix_hc_ctx_t::conn, brix_hc_ctx_t::host, brix_hc_ctx_t::log, brix_hc_ctx_t::pool, brix_hc_ctx_t::port, brix_hc_ctx_t::tev, and brix_hc_ctx_t::threshold.
Referenced by brix_hc_begin_connect(), brix_hc_dispatch(), brix_hc_dispatch_protocol(), brix_hc_read_handler(), brix_hc_send_probe(), brix_hc_start(), brix_hc_timeout_handler(), and brix_hc_write_handler().
brix_hc_flush()
static ngx_int_t brix_hc_flush (brix_hc_ctx_t * hc) static
Definition at line 131 of file health_check.c.
References c, brix_hc_ctx_t::conn, brix_hc_ctx_t::wbuf, brix_hc_ctx_t::wbuf_len, and brix_hc_ctx_t::wbuf_pos.
Referenced by brix_hc_begin_connect(), brix_hc_dispatch_protocol(), brix_hc_send_probe(), and brix_hc_write_handler().
brix_hc_manager_start()
void brix_hc_manager_start (ngx_cycle_t * cycle, ngx_stream_brix_srv_conf_t * conf)
Definition at line 900 of file health_check.c.
References brix_hc_timer_handler(), BRIX_SRV_REGISTRY_SLOTS, brix_hc_mgr_t::conf, brix_hc_mgr_t::cycle, ngx_pcalloc(), brix_hc_mgr_t::scan_interval_ms, and brix_hc_mgr_t::timer.
Referenced by brix_init_one_server().
brix_hc_open_conn()
static ngx_int_t brix_hc_open_conn (ngx_cycle_t * cycle, brix_hc_ctx_t * hc, struct addrinfo * res, const char * host, uint16_t port) static
Definition at line 685 of file health_check.c.
References brix_hc_pre_connect_fail(), brix_hc_read_handler(), brix_hc_write_handler(), c, brix_hc_ctx_t::conf, brix_hc_ctx_t::conn, host, brix_hc_ctx_t::log, brix_hc_ctx_t::pool, and port.
Referenced by brix_hc_start().
brix_hc_pre_connect_fail()
static void brix_hc_pre_connect_fail (struct addrinfo * res, const char * host, uint16_t port, ngx_stream_brix_srv_conf_t * conf, ngx_pool_t * pool) static
Definition at line 602 of file health_check.c.
References brix_srv_hc_fail(), host, and port.
Referenced by brix_hc_open_conn().
brix_hc_queue_bootstrap()
static ngx_int_t brix_hc_queue_bootstrap (brix_hc_ctx_t * hc) static
Definition at line 727 of file health_check.c.
References brix_upstream_build_bootstrap_flags(), brix_hc_ctx_t::conf, kXR_ableTLS, brix_hc_ctx_t::pool, brix_hc_ctx_t::tls_capable, brix_hc_ctx_t::wbuf, brix_hc_ctx_t::wbuf_len, brix_hc_ctx_t::wbuf_pos, and XRD_HANDSHAKE_LEN.
Referenced by brix_hc_start().
brix_hc_read_handler()
static void brix_hc_read_handler (ngx_event_t * rev) static
Definition at line 501 of file health_check.c.
References brix_hc_dispatch(), brix_hc_finish(), brix_hc_recv_frame(), and c.
Referenced by brix_hc_open_conn().
brix_hc_recv_frame()
static ngx_int_t brix_hc_recv_frame (brix_hc_ctx_t * hc) static
Definition at line 256 of file health_check.c.
References c, brix_hc_ctx_t::conn, ServerResponseHdr::dlen, brix_hc_ctx_t::resp_body, brix_hc_ctx_t::resp_body_pos, brix_hc_ctx_t::resp_dlen, brix_hc_ctx_t::resp_status, brix_hc_ctx_t::rhdr, brix_hc_ctx_t::rhdr_pos, ServerResponseHdr::status, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_hc_read_handler().
brix_hc_resolve()
static struct addrinfo * brix_hc_resolve (brix_hc_ctx_t * hc, const char * host, uint16_t port) static
Definition at line 655 of file health_check.c.
References brix_srv_hc_fail(), brix_hc_ctx_t::conf, host, brix_hc_ctx_t::log, brix_hc_ctx_t::pool, and port.
Referenced by brix_hc_start().
brix_hc_send_probe()
static void brix_hc_send_probe (brix_hc_ctx_t * hc) static
Definition at line 164 of file health_check.c.
References brix_hc_finish(), brix_hc_flush(), BRIX_HC_TYPE_STAT, ClientStatRequest::dlen, ClientPingRequest::dlen, kXR_ping, kXR_stat, brix_hc_ctx_t::phase, brix_hc_ctx_t::pool, brix_hc_ctx_t::probe_type, ClientStatRequest::requestid, ClientPingRequest::requestid, brix_hc_ctx_t::resp_body, brix_hc_ctx_t::resp_body_pos, brix_hc_ctx_t::resp_dlen, brix_hc_ctx_t::rhdr_pos, ClientStatRequest::streamid, ClientPingRequest::streamid, brix_hc_ctx_t::wbuf, brix_hc_ctx_t::wbuf_len, brix_hc_ctx_t::wbuf_pos, and XRD_HC_PROBE.
Referenced by brix_hc_dispatch().
brix_hc_start()
static void brix_hc_start (ngx_cycle_t * cycle, ngx_stream_brix_srv_conf_t * conf, const char * host, uint16_t port) static
Definition at line 814 of file health_check.c.
References brix_hc_begin_connect(), brix_hc_ctx_create(), brix_hc_finish(), BRIX_HC_METRIC_INC, brix_hc_open_conn(), brix_hc_queue_bootstrap(), brix_hc_resolve(), brix_hc_timeout_handler(), host, port, and brix_hc_ctx_t::tev.
Referenced by brix_hc_timer_handler().
brix_hc_timeout_handler()
static void brix_hc_timeout_handler (ngx_event_t * ev) static
Definition at line 536 of file health_check.c.
References BRIX_DIAG_WARN, brix_hc_finish(), brix_hc_ctx_t::host, brix_hc_ctx_t::log, and brix_hc_ctx_t::port.
Referenced by brix_hc_start().
brix_hc_timer_handler()
static void brix_hc_timer_handler (ngx_event_t * ev) static
Definition at line 859 of file health_check.c.
References brix_hc_start(), brix_srv_hc_claim(), brix_hc_mgr_t::conf, brix_hc_mgr_t::cycle, host, port, and brix_hc_mgr_t::scan_interval_ms.
Referenced by brix_hc_manager_start().
brix_hc_write_handler()
static void brix_hc_write_handler (ngx_event_t * wev) static
Definition at line 212 of file health_check.c.
References BRIX_DIAG_WARN, brix_hc_finish(), brix_hc_flush(), c, brix_hc_ctx_t::connecting, brix_hc_ctx_t::host, brix_hc_ctx_t::log, and brix_hc_ctx_t::port.
Referenced by brix_hc_open_conn().
brix_upstream_build_bootstrap_flags()
void brix_upstream_build_bootstrap_flags (u_char * buf, uint8_t protocol_flags) extern
Definition at line 36 of file bootstrap.c.
References brix_upstream_streamid, kXR_ver005, xrd_pack_handshake(), xrd_pack_login_request(), and xrd_pack_protocol_request().
Referenced by brix_hc_queue_bootstrap().
brix_upstream_build_login()
void brix_upstream_build_login (ClientLoginRequest * req) extern
Definition at line 65 of file bootstrap.c.
References brix_upstream_streamid, kXR_ver005, and xrd_pack_login_request().
Referenced by brix_hc_dispatch_protocol().