nginx-xrootd: src/observability/metrics/health.c File Reference
health.c File Reference
#include "metrics_internal.h"
#include "fs/backend/cache/sd_cache.h"
#include "fs/backend/http/sd_http.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "core/http/http_headers.h"
#include "core/compat/alloc_guard.h"
#include "core/ident.h"
Functions
static ngx_uint_t health_verbose_requested (ngx_http_request_t *r)
static u_char * health_build_json (ngx_http_request_t *r, ngx_uint_t verbose, size_t *len)
ngx_int_t ngx_http_brix_health_handler (ngx_http_request_t *r)
Function Documentation
health_build_json()
static u_char * health_build_json (ngx_http_request_t * r, ngx_uint_t verbose, size_t * len) static
Definition at line 51 of file health.c.
References brix_vfs_backend_info_t::backend, BRIX_PNALLOC_OR_RETURN, brix_sd_cache_source_instance(), BRIX_SERVER_NAME, BRIX_SERVER_VERSION, brix_vfs_backend_export_count(), brix_vfs_backend_export_info(), brix_vfs_backend_resolve(), ngx_brix_metrics_t::config_generation, ngx_brix_metrics_t::config_hash, generation, ngx_brix_shm_zone, brix_vfs_backend_info_t::root_canon, SD_HTTP_EP_MAX, and sd_http_health_snapshot().
Referenced by ngx_http_brix_health_handler().
health_verbose_requested()
static ngx_uint_t health_verbose_requested (ngx_http_request_t * r) static
Definition at line 36 of file health.c.
Referenced by ngx_http_brix_health_handler().
ngx_http_brix_health_handler()
ngx_int_t ngx_http_brix_health_handler (ngx_http_request_t * r)
Definition at line 146 of file health.c.
References brix_http_source_offer(), BRIX_PCALLOC_OR_RETURN, ngx_http_brix_metrics_loc_conf_t::health, health_build_json(), health_verbose_requested(), and ngx_http_brix_metrics_module.
Referenced by ngx_http_brix_health_set().