nginx-xrootd: src/net/manager/health_check_probe.c File Reference
health_check_probe.c File Reference
#include "health_check.h"
#include "registry.h"
#include "observability/metrics/metrics_macros.h"
#include "core/compat/log_diag.h"
#include "health_check_internal.h"
#include <netdb.h>
#include <sys/socket.h>
Functions
void brix_upstream_build_login (ClientLoginRequest *req)
ngx_int_t brix_hc_flush (brix_hc_ctx_t *hc)
static void brix_hc_send_probe (brix_hc_ctx_t *hc)
void brix_hc_write_handler (ngx_event_t *wev)
static ngx_int_t brix_hc_recv_frame (brix_hc_ctx_t *hc)
static ngx_int_t brix_hc_dispatch_protocol (brix_hc_ctx_t *hc)
static void brix_hc_dispatch (brix_hc_ctx_t *hc)
void brix_hc_read_handler (ngx_event_t *rev)
Function Documentation
brix_hc_dispatch()
static void brix_hc_dispatch (brix_hc_ctx_t * hc) static
Definition at line 364 of file health_check_probe.c.
References brix_hc_dispatch_protocol(), brix_hc_finish(), brix_hc_send_probe(), brix_hc_ctx_t::conn, kXR_authmore, kXR_ok, brix_hc_ctx_t::phase, brix_hc_ctx_t::resp_body, brix_hc_ctx_t::resp_body_pos, brix_hc_ctx_t::resp_dlen, brix_hc_ctx_t::resp_status, brix_hc_ctx_t::rhdr_pos, XRD_HC_HANDSHAKE, XRD_HC_LOGIN, XRD_HC_PROBE, and XRD_HC_PROTOCOL.
Referenced by brix_hc_read_handler().
brix_hc_dispatch_protocol()
static ngx_int_t brix_hc_dispatch_protocol (brix_hc_ctx_t * hc) static
Definition at line 289 of file health_check_probe.c.
References brix_hc_finish(), brix_hc_flush(), brix_upstream_build_login(), brix_hc_ctx_t::conf, brix_hc_ctx_t::conn, brix_hc_ctx_t::host, kXR_gotoTLS, kXR_ok, brix_hc_ctx_t::log, ngx_memcpy, brix_hc_ctx_t::phase, brix_hc_ctx_t::pool, brix_hc_ctx_t::port, brix_hc_ctx_t::resp_body, brix_hc_ctx_t::resp_body_pos, brix_hc_ctx_t::resp_dlen, brix_hc_ctx_t::resp_status, brix_hc_ctx_t::rhdr_pos, brix_hc_ctx_t::tls_capable, brix_hc_ctx_t::wbuf, brix_hc_ctx_t::wbuf_len, brix_hc_ctx_t::wbuf_pos, and XRD_HC_LOGIN.
Referenced by brix_hc_dispatch().
brix_hc_flush()
ngx_int_t brix_hc_flush (brix_hc_ctx_t * hc)
Definition at line 45 of file health_check_probe.c.
References c, brix_hc_ctx_t::conn, brix_hc_ctx_t::wbuf, brix_hc_ctx_t::wbuf_len, and brix_hc_ctx_t::wbuf_pos.
Referenced by brix_hc_begin_connect(), brix_hc_dispatch_protocol(), brix_hc_send_probe(), and brix_hc_write_handler().
brix_hc_read_handler()
void brix_hc_read_handler (ngx_event_t * rev)
Definition at line 415 of file health_check_probe.c.
References brix_hc_dispatch(), brix_hc_finish(), brix_hc_recv_frame(), and c.
Referenced by brix_hc_open_conn().
brix_hc_recv_frame()
static ngx_int_t brix_hc_recv_frame (brix_hc_ctx_t * hc) static
Definition at line 170 of file health_check_probe.c.
References c, brix_hc_ctx_t::conn, ServerResponseHdr::dlen, brix_hc_ctx_t::resp_body, brix_hc_ctx_t::resp_body_pos, brix_hc_ctx_t::resp_dlen, brix_hc_ctx_t::resp_status, brix_hc_ctx_t::rhdr, brix_hc_ctx_t::rhdr_pos, ServerResponseHdr::status, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_hc_read_handler().
brix_hc_send_probe()
static void brix_hc_send_probe (brix_hc_ctx_t * hc) static
Definition at line 78 of file health_check_probe.c.
References brix_hc_finish(), brix_hc_flush(), BRIX_HC_TYPE_STAT, ClientStatRequest::dlen, ClientPingRequest::dlen, kXR_ping, kXR_stat, brix_hc_ctx_t::phase, brix_hc_ctx_t::pool, brix_hc_ctx_t::probe_type, ClientStatRequest::requestid, ClientPingRequest::requestid, brix_hc_ctx_t::resp_body, brix_hc_ctx_t::resp_body_pos, brix_hc_ctx_t::resp_dlen, brix_hc_ctx_t::rhdr_pos, ClientStatRequest::streamid, ClientPingRequest::streamid, brix_hc_ctx_t::wbuf, brix_hc_ctx_t::wbuf_len, brix_hc_ctx_t::wbuf_pos, and XRD_HC_PROBE.
Referenced by brix_hc_dispatch().
brix_hc_write_handler()
void brix_hc_write_handler (ngx_event_t * wev)
Definition at line 126 of file health_check_probe.c.
References BRIX_DIAG_WARN, brix_hc_finish(), brix_hc_flush(), c, brix_hc_ctx_t::connecting, brix_hc_ctx_t::host, brix_hc_ctx_t::log, and brix_hc_ctx_t::port.
Referenced by brix_hc_open_conn().
brix_upstream_build_login()
void brix_upstream_build_login (ClientLoginRequest * req) extern
Definition at line 65 of file bootstrap.c.
References brix_upstream_streamid, kXR_ver005, and xrd_pack_login_request().
Referenced by brix_hc_dispatch_protocol().