nginx-xrootd: src/net/manager/health_check_internal.h File Reference
health_check_internal.h File Reference
Data Structures
struct brix_hc_ctx_t
Macros
#define BRIX_HC_METRIC_INC(field)
Enumerations
enum brix_hc_phase_t { XRD_HC_HANDSHAKE = 0 , XRD_HC_PROTOCOL , XRD_HC_LOGIN , XRD_HC_PROBE }
Functions
ngx_int_t brix_hc_flush (brix_hc_ctx_t *hc)
void brix_hc_write_handler (ngx_event_t *wev)
void brix_hc_read_handler (ngx_event_t *rev)
void brix_hc_finish (brix_hc_ctx_t *hc, int passed)
Macro Definition Documentation
BRIX_HC_METRIC_INC
#define BRIX_HC_METRIC_INC (field)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_m = brix_metrics_shared();                  \
        if (_m != NULL) { (void) ngx_atomic_fetch_add(&_m->field, 1); }      \
    } while (0)
Definition at line 93 of file health_check_internal.h.
Enumeration Type Documentation
brix_hc_phase_t
enum brix_hc_phase_t
Enumerator
XRD_HC_HANDSHAKE
XRD_HC_PROTOCOL
XRD_HC_LOGIN
XRD_HC_PROBE
Definition at line 39 of file health_check_internal.h.
Function Documentation
brix_hc_finish()
void brix_hc_finish (brix_hc_ctx_t * hc, int passed)
Definition at line 67 of file health_check.c.
References brix_hc_ctx_t::blacklist_ms, BRIX_HC_METRIC_INC, brix_srv_hc_fail(), brix_srv_hc_pass(), brix_hc_ctx_t::conn, brix_hc_ctx_t::host, brix_hc_ctx_t::log, brix_hc_ctx_t::pool, brix_hc_ctx_t::port, brix_hc_ctx_t::tev, and brix_hc_ctx_t::threshold.
Referenced by brix_hc_begin_connect(), brix_hc_dispatch(), brix_hc_dispatch_protocol(), brix_hc_read_handler(), brix_hc_send_probe(), brix_hc_start(), brix_hc_timeout_handler(), and brix_hc_write_handler().
brix_hc_flush()
ngx_int_t brix_hc_flush (brix_hc_ctx_t * hc)
Definition at line 45 of file health_check_probe.c.
References c, brix_hc_ctx_t::conn, brix_hc_ctx_t::wbuf, brix_hc_ctx_t::wbuf_len, and brix_hc_ctx_t::wbuf_pos.
Referenced by brix_hc_begin_connect(), brix_hc_dispatch_protocol(), brix_hc_send_probe(), and brix_hc_write_handler().
brix_hc_read_handler()
void brix_hc_read_handler (ngx_event_t * rev)
Definition at line 415 of file health_check_probe.c.
References brix_hc_dispatch(), brix_hc_finish(), brix_hc_recv_frame(), and c.
Referenced by brix_hc_open_conn().
brix_hc_write_handler()
void brix_hc_write_handler (ngx_event_t * wev)
Definition at line 126 of file health_check_probe.c.
References BRIX_DIAG_WARN, brix_hc_finish(), brix_hc_flush(), c, brix_hc_ctx_t::connecting, brix_hc_ctx_t::host, brix_hc_ctx_t::log, and brix_hc_ctx_t::port.
Referenced by brix_hc_open_conn().