nginx-xrootd: src/core/compat/hex.c File Reference
hex.c File Reference
#include "hex.h"
Functions
uint8_t brix_hex_nibble (uint8_t v)
int brix_hex_from_char (unsigned char c)
void brix_hex_encode (const uint8_t *in, size_t len, char *out)
Function Documentation
brix_hex_encode()
void brix_hex_encode (const uint8_t * in, size_t len, char * out)
Definition at line 59 of file hex.c.
References hex().
Referenced by brix_checksum_hex_encode(), brix_cksum_fd(), brix_deleg_store_put(), brix_make_resume_path(), brix_s3_sha256_hex(), brix_s3_sigv4_sign_and_emit(), brix_sss_keytab_write(), gen_tpc_key(), s3_chunk_verify(), s3_post_verify_signature(), s3_sigv4_compute_signature(), sd_s3_derive_key_and_sign(), sd_s3_sha256_hex(), and sd_s3_sign().
brix_hex_from_char()
int brix_hex_from_char (unsigned char c)
Definition at line 34 of file hex.c.
References c.
Referenced by brix_http_urldecode(), brix_macaroon_packet_len(), brix_macaroon_secret_parse(), s3_checksum_b64(), sss_decode_hex(), and webdav_dead_prop_decode_hex().
brix_hex_nibble()
uint8_t brix_hex_nibble (uint8_t v)
Definition at line 21 of file hex.c.
Referenced by brix_sanitize_log_string(), and brix_xml_escape_char().