nginx-xrootd: src/observability/dashboard/history.c File Reference
history.c File Reference
#include "dashboard.h"
#include "observability/metrics/metrics.h"
#include "core/compat/shm_slots.h"
#include <ngx_shmtx.h>
Functions
static brix_dashboard_history_t * dashboard_history_table (void)
static ngx_uint_t dashboard_history_bucket_index (int64_t bucket_start_ms)
ngx_int_t ngx_brix_dashboard_history_shm_init (ngx_shm_zone_t *shm_zone, void *data)
static void dashboard_history_zero_fill_gap (brix_dashboard_history_t *hist, int64_t bucket_start)
static brix_dashboard_history_bucket_t * dashboard_history_select_bucket (brix_dashboard_history_t *hist, int64_t bucket_start)
static void dashboard_history_count_active (ngx_uint_t active[(BRIX_XFER_PROTO__END - 1)], ngx_uint_t *active_tpc)
static void dashboard_history_sum_totals (uint64_t *bytes_rx, uint64_t *bytes_tx, uint64_t *errors, uint64_t *auth_failures)
void brix_dashboard_history_sample (int64_t now_ms)
ngx_uint_t brix_dashboard_history_snapshot (brix_dashboard_history_bucket_t *out, ngx_uint_t max_buckets)
Variables
static ngx_shmtx_t brix_dashboard_history_mutex
Function Documentation
brix_dashboard_history_sample()
void brix_dashboard_history_sample (int64_t now_ms)
Definition at line 249 of file history.c.
brix_dashboard_history_snapshot()
ngx_uint_t brix_dashboard_history_snapshot (brix_dashboard_history_bucket_t * out, ngx_uint_t max_buckets)
Definition at line 298 of file history.c.
dashboard_history_bucket_index()
static ngx_uint_t dashboard_history_bucket_index (int64_t bucket_start_ms) static
Definition at line 52 of file history.c.
References BRIX_DASHBOARD_HISTORY_BUCKETS, and BRIX_DASHBOARD_HISTORY_INTERVAL_MS.
Referenced by brix_dashboard_history_snapshot(), dashboard_history_select_bucket(), and dashboard_history_zero_fill_gap().
dashboard_history_count_active()
static void dashboard_history_count_active (ngx_uint_t active[(BRIX_XFER_PROTO__END - 1)], ngx_uint_t * active_tpc) static
Definition at line 162 of file history.c.
References active, BRIX_DASHBOARD_MAX_TRANSFERS, BRIX_XFER_DIR_TPC, BRIX_XFER_NPROTOS, BRIX_XFER_PROTO_ROOT, brix_transfer_slot_t::direction, brix_transfer_slot_t::in_use, ngx_brix_dashboard_shm_zone, brix_transfer_slot_t::proto, and brix_transfer_table_t::slots.
Referenced by brix_dashboard_history_sample().
dashboard_history_select_bucket()
static brix_dashboard_history_bucket_t * dashboard_history_select_bucket (brix_dashboard_history_t * hist, int64_t bucket_start) static
Definition at line 136 of file history.c.
References brix_dashboard_history_bucket_t::bucket_start_ms, brix_dashboard_history_t::buckets, and dashboard_history_bucket_index().
Referenced by brix_dashboard_history_sample().
dashboard_history_sum_totals()
static void dashboard_history_sum_totals (uint64_t * bytes_rx, uint64_t * bytes_tx, uint64_t * errors, uint64_t * auth_failures) static
Definition at line 211 of file history.c.
References ngx_brix_webdav_metrics_t::auth_total, ngx_brix_s3_metrics_t::auth_total, BRIX_METRICS_MAX_SERVERS, BRIX_NOPS, BRIX_OP_AUTH, BRIX_S3_AUTH_BAD_KEY, BRIX_S3_AUTH_MALFORMED, BRIX_S3_AUTH_SIG_MISMATCH, BRIX_WEBDAV_AUTH_RESULT_REJECTED, ngx_brix_srv_metrics_t::bytes_rx_total, ngx_brix_s3_metrics_t::bytes_rx_total, ngx_brix_webdav_metrics_t::bytes_rx_total, ngx_brix_srv_metrics_t::bytes_tx_total, ngx_brix_s3_metrics_t::bytes_tx_total, ngx_brix_webdav_metrics_t::bytes_tx_total, ngx_brix_shm_zone, ngx_brix_srv_metrics_t::op_err, ngx_brix_metrics_t::s3, ngx_brix_metrics_t::servers, and ngx_brix_metrics_t::webdav.
Referenced by brix_dashboard_history_sample().
dashboard_history_table()
static brix_dashboard_history_t * dashboard_history_table (void) static
Definition at line 38 of file history.c.
References ngx_brix_dashboard_history_shm_zone.
Referenced by brix_dashboard_history_sample(), and brix_dashboard_history_snapshot().
dashboard_history_zero_fill_gap()
static void dashboard_history_zero_fill_gap (brix_dashboard_history_t * hist, int64_t bucket_start) static
Definition at line 102 of file history.c.
References BRIX_DASHBOARD_HISTORY_INTERVAL_MS, brix_dashboard_history_bucket_t::bucket_start_ms, brix_dashboard_history_t::buckets, dashboard_history_bucket_index(), and brix_dashboard_history_t::last_bucket_start_ms.
Referenced by brix_dashboard_history_sample().
ngx_brix_dashboard_history_shm_init()
ngx_int_t ngx_brix_dashboard_history_shm_init (ngx_shm_zone_t * shm_zone, void * data)
Definition at line 60 of file history.c.
Variable Documentation
brix_dashboard_history_mutex
ngx_shmtx_t brix_dashboard_history_mutex static
Definition at line 35 of file history.c.
Referenced by brix_dashboard_history_sample(), brix_dashboard_history_snapshot(), and ngx_brix_dashboard_history_shm_init().