nginx-xrootd: src/core/compat/host_split.h File Reference
host_split.h File Reference
#include <stddef.h>
Functions
int brix_split_host_port (const char *in, char *host, size_t hsz, int *port, int default_port)
Function Documentation
brix_split_host_port()
int brix_split_host_port (const char * in, char * host, size_t hsz, int * port, int default_port)
Definition at line 151 of file host_split.c.
References brix_split_bracketed(), brix_split_plain(), host, and port.
Referenced by parse_authority(), parse_holder(), and tpc_parse_src_spec().