nginx-xrootd: src/core/compat/host_split.c File Reference
host_split.c File Reference
#include "host_split.h"
#include <string.h>
#include <stdlib.h>
Functions
static int brix_parse_port_str (const char *port_str, int *port)
static int brix_copy_host (char *host, size_t hsz, const char *src, size_t hlen)
static int brix_split_bracketed (const char *in, char *host, size_t hsz, int *port, int default_port)
static int brix_split_plain (const char *in, char *host, size_t hsz, int *port, int default_port)
int brix_split_host_port (const char *in, char *host, size_t hsz, int *port, int default_port)
Function Documentation
brix_copy_host()
static int brix_copy_host (char * host, size_t hsz, const char * src, size_t hlen) static
Definition at line 54 of file host_split.c.
References host.
Referenced by brix_split_bracketed(), and brix_split_plain().
brix_parse_port_str()
static int brix_parse_port_str (const char * port_str, int * port) static
Definition at line 28 of file host_split.c.
References port.
Referenced by brix_split_bracketed(), and brix_split_plain().
brix_split_bracketed()
static int brix_split_bracketed (const char * in, char * host, size_t hsz, int * port, int default_port) static
Definition at line 82 of file host_split.c.
References brix_copy_host(), brix_parse_port_str(), host, and port.
Referenced by brix_split_host_port().
brix_split_host_port()
int brix_split_host_port (const char * in, char * host, size_t hsz, int * port, int default_port)
Definition at line 151 of file host_split.c.
References brix_split_bracketed(), brix_split_plain(), host, and port.
Referenced by parse_authority(), parse_holder(), and tpc_parse_src_spec().
brix_split_plain()
static int brix_split_plain (const char * in, char * host, size_t hsz, int * port, int default_port) static
Definition at line 118 of file host_split.c.
References brix_copy_host(), brix_parse_port_str(), host, and port.
Referenced by brix_split_host_port().