nginx-xrootd: src/core/compat/host_format.c File Reference
host_format.c File Reference
#include "host_format.h"
#include <string.h>
#include <stdio.h>
Functions
int brix_host_is_ipv6_literal (const char *host)
size_t brix_format_host (const char *host, char *out, size_t sz)
size_t brix_format_host_port (const char *host, uint16_t port, char *out, size_t sz)
Function Documentation
brix_format_host()
size_t brix_format_host (const char * host, char * out, size_t sz)
Definition at line 25 of file host_format.c.
References brix_host_is_ipv6_literal(), and host.
Referenced by brix_send_redirect(), brix_send_redirect_tpc(), proxy_pool_resolve(), and tpc_curl_secure().
brix_format_host_port()
size_t brix_format_host_port (const char * host, uint16_t port, char * out, size_t sz)
Definition at line 53 of file host_format.c.
References brix_host_is_ipv6_literal(), host, and port.
Referenced by auth_hdr_s3(), brix_connect(), brix_kaconn_init(), brix_s3_list(), brix_srv_locate_all(), brix_webfile_open(), http_get_send_request(), httpx_build_request(), httpx_download_exchange(), httpx_fmt_chunk_request(), httpx_fmt_put_request(), proxy_pool_resolve(), rt_handle_redirect(), sd_s3_sign_ex(), sd_s3_sign_prepare(), tpc_register_stream_transfer(), tpc_sess_begin_pull(), and tpc_setup_source().
brix_host_is_ipv6_literal()
int brix_host_is_ipv6_literal (const char * host)
Definition at line 18 of file host_format.c.
References host.
Referenced by brix_format_host(), and brix_format_host_port().