nginx-xrootd: src/net/mirror/http_mirror.c File Reference
http_mirror.c File Reference
#include "http_mirror.h"
#include "core/http/http_body.h"
#include "core/http/http_headers.h"
Macros
#define MIR_HTTP_INC(field)
Functions
static ngx_uint_t brix_http_mirror_method_bit (ngx_http_request_t *r)
static ngx_int_t brix_http_mirror_method_has_body (ngx_uint_t method)
static ngx_str_t brix_http_mirror_rewrite_dest (ngx_pool_t *pool, ngx_str_t *dest, ngx_str_t *url_base)
static ngx_chain_t * brix_http_mirror_clone_body (ngx_http_request_t *r, ngx_http_request_t *parent, off_t *len_out)
static ngx_int_t mirror_create_request (ngx_http_request_t *r)
static ngx_int_t mirror_reinit_request (ngx_http_request_t *r)
static ngx_int_t mirror_process_header (ngx_http_request_t *r)
static ngx_int_t mirror_process_status_line (ngx_http_request_t *r)
static void mirror_abort_request (ngx_http_request_t *r)
static void mirror_finalize_request (ngx_http_request_t *r, ngx_int_t rc)
static ngx_int_t brix_http_mirror_proxy (ngx_http_request_t *r, ngx_http_brix_webdav_req_ctx_t *ctx)
static void mirror_fire_subrequests (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static void mirror_put_body_handler (ngx_http_request_t *r)
ngx_int_t brix_http_mirror_precontent_handler (ngx_http_request_t *r)
ngx_int_t brix_http_mirror_log_handler (ngx_http_request_t *r)
ngx_int_t brix_http_mirror_setup (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_loc_conf_t *prev)
char * brix_http_mirror_set_url (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_http_mirror_set_methods (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Macro Definition Documentation
MIR_HTTP_INC
#define MIR_HTTP_INC (field)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_m = brix_metrics_shared();                  \
        if (_m != NULL) { (void) ngx_atomic_fetch_add(&_m->field, 1); }      \
    } while (0)
Definition at line 25 of file http_mirror.c.
Function Documentation
brix_http_mirror_clone_body()
static ngx_chain_t * brix_http_mirror_clone_body (ngx_http_request_t * r, ngx_http_request_t * parent, off_t * len_out) static
Definition at line 103 of file http_mirror.c.
Referenced by mirror_create_request().
brix_http_mirror_log_handler()
ngx_int_t brix_http_mirror_log_handler (ngx_http_request_t * r)
Definition at line 617 of file http_mirror.c.
References ngx_http_brix_webdav_req_ctx_t::mirror_fired, ngx_http_brix_webdav_module, and ngx_http_brix_webdav_req_ctx_t::primary_status.
Referenced by ngx_http_brix_webdav_postconfiguration().
brix_http_mirror_method_bit()
static ngx_uint_t brix_http_mirror_method_bit (ngx_http_request_t * r) static
Definition at line 34 of file http_mirror.c.
References BRIX_MIRROR_M_COPY, BRIX_MIRROR_M_DELETE, BRIX_MIRROR_M_GET, BRIX_MIRROR_M_HEAD, BRIX_MIRROR_M_MKCOL, BRIX_MIRROR_M_MOVE, BRIX_MIRROR_M_OPTIONS, BRIX_MIRROR_M_PROPFIND, and BRIX_MIRROR_M_PUT.
Referenced by brix_http_mirror_precontent_handler().
brix_http_mirror_method_has_body()
static ngx_int_t brix_http_mirror_method_has_body (ngx_uint_t method) static
Definition at line 53 of file http_mirror.c.
Referenced by brix_http_mirror_precontent_handler(), and mirror_create_request().
brix_http_mirror_precontent_handler()
ngx_int_t brix_http_mirror_precontent_handler (ngx_http_request_t * r)
Definition at line 522 of file http_mirror.c.
References brix_http_mirror_method_bit(), brix_http_mirror_method_has_body(), brix_http_mirror_proxy(), BRIX_MIRROR_M_WRITE_ALL, brix_mirror_should_sample(), brix_mirror_conf_t::enabled, ngx_http_brix_webdav_req_ctx_t::is_mirror, key, brix_mirror_conf_t::method_mask, MIR_HTTP_INC, ngx_http_brix_webdav_loc_conf_t::mirror, mirror_fire_subrequests(), ngx_http_brix_webdav_req_ctx_t::mirror_fired, mirror_put_body_handler(), brix_mirror_conf_t::mirror_writes, ngx_http_brix_webdav_module, brix_mirror_conf_t::sample_pct, and brix_mirror_conf_t::targets.
Referenced by ngx_http_brix_webdav_postconfiguration().
brix_http_mirror_proxy()
static ngx_int_t brix_http_mirror_proxy (ngx_http_request_t * r, ngx_http_brix_webdav_req_ctx_t * ctx) static
Definition at line 408 of file http_mirror.c.
References brix_mirror_target_t::host, ngx_http_brix_webdav_loc_conf_t::mirror, mirror_abort_request(), mirror_create_request(), mirror_finalize_request(), mirror_process_status_line(), mirror_reinit_request(), ngx_http_brix_webdav_req_ctx_t::mirror_target_idx, ngx_http_brix_webdav_loc_conf_t::mirror_upstream_conf, ngx_http_brix_webdav_module, brix_mirror_target_t::port, brix_mirror_target_t::sockaddr, brix_mirror_target_t::socklen, brix_mirror_target_t::ssl, and brix_mirror_conf_t::targets.
Referenced by brix_http_mirror_precontent_handler().
brix_http_mirror_rewrite_dest()
static ngx_str_t brix_http_mirror_rewrite_dest (ngx_pool_t * pool, ngx_str_t * dest, ngx_str_t * url_base) static
Definition at line 65 of file http_mirror.c.
Referenced by mirror_create_request().
brix_http_mirror_set_methods()
char * brix_http_mirror_set_methods (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 783 of file http_mirror.c.
References BRIX_MIRROR_M_COPY, BRIX_MIRROR_M_DELETE, BRIX_MIRROR_M_GET, BRIX_MIRROR_M_HEAD, BRIX_MIRROR_M_MKCOL, BRIX_MIRROR_M_MOVE, BRIX_MIRROR_M_OPTIONS, BRIX_MIRROR_M_PROPFIND, BRIX_MIRROR_M_PUT, brix_mirror_conf_t::method_mask, and ngx_http_brix_webdav_loc_conf_t::mirror.
brix_http_mirror_set_url()
char * brix_http_mirror_set_url (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 696 of file http_mirror.c.
References BRIX_MIRROR_MAX_TARGETS, brix_mirror_target_t::host, ngx_http_brix_webdav_loc_conf_t::mirror, brix_mirror_target_t::port, brix_mirror_target_t::sockaddr, brix_mirror_target_t::socklen, brix_mirror_target_t::ssl, brix_mirror_conf_t::targets, brix_mirror_target_t::url, and brix_mirror_target_t::url_base.
brix_http_mirror_setup()
ngx_int_t brix_http_mirror_setup (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_loc_conf_t * prev)
Definition at line 634 of file http_mirror.c.
References ngx_http_brix_webdav_loc_conf_t::mirror, ngx_http_brix_webdav_loc_conf_t::mirror_upstream_conf, s, and brix_mirror_conf_t::timeout_ms.
Referenced by ngx_http_brix_webdav_merge_loc_conf().
mirror_abort_request()
static void mirror_abort_request (ngx_http_request_t * r) static
Definition at line 362 of file http_mirror.c.
Referenced by brix_http_mirror_proxy().
mirror_create_request()
static ngx_int_t mirror_create_request (ngx_http_request_t * r) static
Definition at line 136 of file http_mirror.c.
References brix_http_find_header(), brix_http_mirror_clone_body(), brix_http_mirror_method_has_body(), brix_http_mirror_rewrite_dest(), brix_mirror_target_t::host, ngx_http_brix_webdav_loc_conf_t::mirror, ngx_http_brix_webdav_req_ctx_t::mirror_target_idx, ngx_http_brix_webdav_module, brix_mirror_conf_t::strip_auth, brix_mirror_conf_t::targets, brix_mirror_conf_t::token, and brix_mirror_target_t::url_base.
Referenced by brix_http_mirror_proxy().
mirror_finalize_request()
static void mirror_finalize_request (ngx_http_request_t * r, ngx_int_t rc) static
Definition at line 368 of file http_mirror.c.
References brix_mirror_status_class(), brix_mirror_conf_t::log_diverge, MIR_HTTP_INC, ngx_http_brix_webdav_loc_conf_t::mirror, ngx_http_brix_webdav_module, and ngx_http_brix_webdav_req_ctx_t::primary_status.
Referenced by brix_http_mirror_proxy().
mirror_fire_subrequests()
static void mirror_fire_subrequests (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 468 of file http_mirror.c.
References ngx_http_brix_webdav_req_ctx_t::is_mirror, ngx_http_brix_webdav_loc_conf_t::mirror, ngx_http_brix_webdav_req_ctx_t::mirror_target_idx, ngx_http_brix_webdav_module, and brix_mirror_conf_t::targets.
Referenced by brix_http_mirror_precontent_handler(), and mirror_put_body_handler().
mirror_process_header()
static ngx_int_t mirror_process_header (ngx_http_request_t * r) static
Definition at line 341 of file http_mirror.c.
Referenced by mirror_process_status_line().
mirror_process_status_line()
static ngx_int_t mirror_process_status_line (ngx_http_request_t * r) static
Definition at line 317 of file http_mirror.c.
References mirror_process_header(), ngx_http_brix_webdav_req_ctx_t::mirror_status, and ngx_http_brix_webdav_module.
Referenced by brix_http_mirror_proxy().
mirror_put_body_handler()
static void mirror_put_body_handler (ngx_http_request_t * r) static
Definition at line 501 of file http_mirror.c.
References mirror_fire_subrequests(), and ngx_http_brix_webdav_module.
Referenced by brix_http_mirror_precontent_handler().
mirror_reinit_request()
static ngx_int_t mirror_reinit_request (ngx_http_request_t * r) static
Definition at line 304 of file http_mirror.c.
References ngx_http_brix_webdav_req_ctx_t::mirror_status, and ngx_http_brix_webdav_module.
Referenced by brix_http_mirror_proxy().