nginx-xrootd: src/observability/dashboard/http_tracking.c File Reference
http_tracking.c File Reference
#include "dashboard_tracking.h"
#include "dashboard_http.h"
#include <string.h>
Data Structures
struct brix_dashboard_http_track_t
struct brix_dashboard_http_meta_t
struct redact_parts_t
Functions
static void dashboard_http_cleanup (void *data)
static brix_dashboard_http_track_t * dashboard_http_track (ngx_http_request_t *r)
static const char * dashboard_http_client (ngx_http_request_t *r, char *buf, size_t bufsz)
static int dashboard_shm_ready (void)
static int dashboard_http_bind_slot (ngx_http_request_t *r, int slot, const char *op)
static int dashboard_http_reserve_slot (ngx_http_request_t *r, const brix_dashboard_http_meta_t *m)
int brix_dashboard_http_start_identity (ngx_http_request_t *r, const char *path, const char *identity, const char *vo, uint8_t proto, uint8_t direction, const char *op, int64_t expected_bytes)
int brix_dashboard_http_start (ngx_http_request_t *r, const char *path, uint8_t proto, uint8_t direction, const char *op, int64_t expected_bytes)
void brix_dashboard_http_add (ngx_http_request_t *r, ngx_atomic_int_t bytes)
void brix_dashboard_http_state (ngx_http_request_t *r, uint8_t state)
void brix_dashboard_http_error (ngx_http_request_t *r, const char *reason)
static void redact_split_authority (const char *url, redact_parts_t *p)
static void redact_write_host (const redact_parts_t *p, char *host, size_t hostsz)
static void redact_write_path_hint (const char *path, char *path_hint, size_t pathsz)
static void dashboard_redact_url (const char *url, char *host, size_t hostsz, char *path_hint, size_t pathsz)
void brix_dashboard_http_tpc_remote (ngx_http_request_t *r, const char *remote_url, int remote_status, int curl_exit)
void brix_dashboard_http_finish (ngx_http_request_t *r)
Function Documentation
brix_dashboard_http_add()
void brix_dashboard_http_add (ngx_http_request_t * r, ngx_atomic_int_t bytes)
Definition at line 244 of file http_tracking.c.
brix_dashboard_http_error()
void brix_dashboard_http_error (ngx_http_request_t * r, const char * reason)
Definition at line 270 of file http_tracking.c.
brix_dashboard_http_finish()
void brix_dashboard_http_finish (ngx_http_request_t * r)
Definition at line 473 of file http_tracking.c.
brix_dashboard_http_start()
int brix_dashboard_http_start (ngx_http_request_t * r, const char * path, uint8_t proto, uint8_t direction, const char * op, int64_t expected_bytes)
Definition at line 234 of file http_tracking.c.
brix_dashboard_http_start_identity()
int brix_dashboard_http_start_identity (ngx_http_request_t * r, const char * path, const char * identity, const char * vo, uint8_t proto, uint8_t direction, const char * op, int64_t expected_bytes)
Definition at line 199 of file http_tracking.c.
Referenced by brix_dashboard_http_start().
brix_dashboard_http_state()
void brix_dashboard_http_state (ngx_http_request_t * r, uint8_t state)
Definition at line 257 of file http_tracking.c.
brix_dashboard_http_tpc_remote()
void brix_dashboard_http_tpc_remote (ngx_http_request_t * r, const char * remote_url, int remote_status, int curl_exit)
Definition at line 455 of file http_tracking.c.
dashboard_http_bind_slot()
static int dashboard_http_bind_slot (ngx_http_request_t * r, int slot, const char * op) static
Definition at line 134 of file http_tracking.c.
References brix_transfer_slot_count_op(), brix_transfer_slot_free(), dashboard_http_cleanup(), ngx_brix_dashboard_shm_zone, ngx_http_brix_dashboard_module, op, brix_dashboard_http_track_t::r, brix_dashboard_http_track_t::slot, and brix_dashboard_http_track_t::table.
Referenced by brix_dashboard_http_start_identity().
dashboard_http_cleanup()
static void dashboard_http_cleanup (void * data) static
Definition at line 55 of file http_tracking.c.
References brix_transfer_slot_free(), brix_dashboard_http_track_t::slot, and brix_dashboard_http_track_t::table.
Referenced by dashboard_http_bind_slot().
dashboard_http_client()
static const char * dashboard_http_client (ngx_http_request_t * r, char * buf, size_t bufsz) static
Definition at line 83 of file http_tracking.c.
References ngx_memcpy.
Referenced by dashboard_http_reserve_slot().
dashboard_http_reserve_slot()
static int dashboard_http_reserve_slot (ngx_http_request_t * r, const brix_dashboard_http_meta_t * m) static
Definition at line 171 of file http_tracking.c.
References brix_transfer_slot_alloc_ex(), dashboard_http_client(), brix_dashboard_http_meta_t::direction, brix_dashboard_http_meta_t::expected_bytes, brix_dashboard_http_meta_t::identity, ngx_brix_dashboard_shm_zone, brix_dashboard_http_meta_t::op, brix_dashboard_http_meta_t::path, brix_dashboard_http_meta_t::proto, and brix_dashboard_http_meta_t::vo.
Referenced by brix_dashboard_http_start_identity().
dashboard_http_track()
static brix_dashboard_http_track_t * dashboard_http_track (ngx_http_request_t * r) static
Definition at line 68 of file http_tracking.c.
References ngx_http_brix_dashboard_module.
Referenced by brix_dashboard_http_add(), brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_dashboard_http_start_identity(), brix_dashboard_http_state(), and brix_dashboard_http_tpc_remote().
dashboard_redact_url()
static void dashboard_redact_url (const char * url, char * host, size_t hostsz, char * path_hint, size_t pathsz) static
Definition at line 428 of file http_tracking.c.
References host, redact_parts_t::path, redact_split_authority(), redact_write_host(), and redact_write_path_hint().
Referenced by brix_dashboard_http_tpc_remote().
dashboard_shm_ready()
static int dashboard_shm_ready (void) static
Definition at line 113 of file http_tracking.c.
References ngx_brix_dashboard_shm_zone.
Referenced by brix_dashboard_http_start_identity().
redact_split_authority()
static void redact_split_authority (const char * url, redact_parts_t * p) static
Definition at line 309 of file http_tracking.c.
References redact_parts_t::authority, redact_parts_t::end, redact_parts_t::path, redact_parts_t::scheme_end, and redact_parts_t::url.
Referenced by dashboard_redact_url().
redact_write_host()
static void redact_write_host (const redact_parts_t * p, char * host, size_t hostsz) static
Definition at line 341 of file http_tracking.c.
References redact_parts_t::authority, redact_parts_t::end, host, ngx_memcpy, redact_parts_t::scheme_end, and redact_parts_t::url.
Referenced by dashboard_redact_url().
redact_write_path_hint()
static void redact_write_path_hint (const char * path, char * path_hint, size_t pathsz) static
Definition at line 391 of file http_tracking.c.
References ngx_memcpy.
Referenced by dashboard_redact_url().