nginx-xrootd: src/core/config/http_rootfd.c File Reference
http_rootfd.c File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include <fcntl.h>
#include <unistd.h>
#include "shared_conf.h"
#include "http_rootfd.h"
Functions
static void brix_http_rootfd_cleanup (void *data)
char * brix_http_open_rootfd (ngx_conf_t *cf, ngx_http_brix_shared_conf_t *common)
Function Documentation
brix_http_open_rootfd()
char * brix_http_open_rootfd (ngx_conf_t * cf, ngx_http_brix_shared_conf_t * common)
Definition at line 29 of file http_rootfd.c.
References brix_http_rootfd_cleanup(), close(), ngx_http_brix_shared_conf_t::enable, O_PATH, open(), ngx_http_brix_shared_conf_t::root_canon, and ngx_http_brix_shared_conf_t::rootfd.
Referenced by cvmfs_merge_cache(), s3_merge_export(), and webdav_validate_webdav_enabled().
brix_http_rootfd_cleanup()
static void brix_http_rootfd_cleanup (void * data) static
Definition at line 18 of file http_rootfd.c.
References close(), and ngx_http_brix_shared_conf_t::rootfd.
Referenced by brix_http_open_rootfd().