nginx-xrootd: src/protocols/shared/http_cache_fill.h File Reference
http_cache_fill.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include "core/config/shared_conf.h"
#include "fs/backend/sd.h"
Typedefs
typedef ngx_int_t(* brix_http_cache_reenter_pt) (ngx_http_request_t *r, void *data)
Functions
ngx_int_t brix_http_cache_fill_if_needed (ngx_http_request_t *r, brix_sd_instance_t *inst, const char *key, ngx_http_brix_shared_conf_t *common, brix_http_cache_reenter_pt reenter, void *reenter_data)
Typedef Documentation
brix_http_cache_reenter_pt
typedef ngx_int_t(* brix_http_cache_reenter_pt) (ngx_http_request_t *r, void *data)
Definition at line 43 of file http_cache_fill.h.
Function Documentation
brix_http_cache_fill_if_needed()
ngx_int_t brix_http_cache_fill_if_needed (ngx_http_request_t * r, brix_sd_instance_t * inst, const char * key, ngx_http_brix_shared_conf_t * common, brix_http_cache_reenter_pt reenter, void * reenter_data)
Definition at line 159 of file http_cache_fill.c.
References key.
Referenced by cvmfs_tier_serve_or_fill(), get_offload_or_fill(), and s3_get_cache_fill().