nginx-xrootd: src/core/http/http_xml.h File Reference
http_xml.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include <stdarg.h>
Functions
ngx_buf_t * brix_http_chain_vappendf (ngx_pool_t *pool, ngx_chain_t **head, ngx_chain_t **tail, const char *fmt, va_list ap)
ngx_buf_t * brix_http_chain_appendf (ngx_pool_t *pool, ngx_chain_t **head, ngx_chain_t **tail, const char *fmt,...)
ngx_int_t brix_http_send_xml_buffer (ngx_http_request_t *r, ngx_uint_t status, ngx_str_t content_type, ngx_buf_t *b)
ngx_int_t brix_http_send_xml_error (ngx_http_request_t *r, ngx_uint_t status, const char *code, const char *message)
Function Documentation
brix_http_chain_appendf()
ngx_buf_t * brix_http_chain_appendf (ngx_pool_t * pool, ngx_chain_t ** head, ngx_chain_t ** tail, const char * fmt, ...)
Definition at line 117 of file http_xml.c.
References brix_http_chain_vappendf().
Referenced by propfind_append_acl_properties(), propfind_do(), propfind_entry(), webdav_dead_prop_append_empty(), webdav_dead_prop_append_value(), webdav_handle_acl(), webdav_lock_append_discovery(), webdav_lock_append_supported(), webdav_lock_xml_response(), webdav_proppatch_append_propstat(), webdav_proppatch_do(), webdav_search_append_response(), and webdav_search_do().
brix_http_chain_vappendf()
ngx_buf_t * brix_http_chain_vappendf (ngx_pool_t * pool, ngx_chain_t ** head, ngx_chain_t ** tail, const char * fmt, va_list ap)
Definition at line 45 of file http_xml.c.
Referenced by brix_http_chain_appendf().
brix_http_send_xml_buffer()
ngx_int_t brix_http_send_xml_buffer (ngx_http_request_t * r, ngx_uint_t status, ngx_str_t content_type, ngx_buf_t * b)
Definition at line 146 of file http_xml.c.
Referenced by brix_http_send_xml_error(), s3_delete_objects_finish(), s3_handle_copy_object(), s3_handle_get_acl(), s3_handle_get_bucket_location(), s3_handle_get_object_tagging(), s3_handle_list_multipart_uploads(), s3_handle_list_parts(), s3_handle_multipart_initiate(), s3_handle_upload_part_copy(), s3_list_finalize(), s3_mpu_send_result(), and s3_send_xml_literal().
brix_http_send_xml_error()
ngx_int_t brix_http_send_xml_error (ngx_http_request_t * r, ngx_uint_t status, const char * code, const char * message)
Definition at line 183 of file http_xml.c.
References brix_http_send_xml_buffer(), BRIX_XML_ESCAPE_APOS_ENTITY, brix_xml_text_element_len(), and brix_xml_write_text_element().
Referenced by s3_send_xml_error().