nginx-xrootd: src/core/http/http_file_response.c File Reference
http_file_response.c File Reference
#include "http_file_response.h"
#include "etag.h"
#include "http_headers.h"
#include <stdio.h>
#include <string.h>
#include "core/compat/alloc_guard.h"
Functions
ngx_int_t brix_http_chain_append_file_range (ngx_http_request_t *r, ngx_chain_t **tail, ngx_fd_t fd, const char *path, off_t start, off_t end, ngx_flag_t close_fd)
ngx_int_t brix_http_add_etag_header (ngx_http_request_t *r, time_t mtime, off_t size, unsigned etag_flags, ngx_flag_t register_not_modified)
ngx_int_t brix_http_add_content_range_header (ngx_http_request_t *r, off_t start, off_t end, off_t size)
ngx_int_t brix_http_set_file_headers (ngx_http_request_t *r, time_t mtime, off_t total_size, off_t send_len, const char *content_type, unsigned etag_flags, int has_range, off_t range_start, off_t range_end)
static ngx_buf_t * brix_http_build_range_buf (ngx_http_request_t *r, ngx_fd_t fd, const char *path, off_t start, off_t len)
static ngx_int_t brix_http_arm_fd_cleanup (ngx_http_request_t *r, ngx_fd_t fd, u_char *name, ngx_pool_cleanup_file_t **clnf_out)
static ngx_int_t brix_http_prepare_file_send (ngx_http_request_t *r, ngx_fd_t fd, const char *path, off_t start, off_t len, ngx_flag_t close_fd, ngx_buf_t **b_out, ngx_pool_cleanup_file_t **clnf_out)
ngx_int_t brix_http_send_file_range (ngx_http_request_t *r, ngx_fd_t fd, const char *path, off_t start, off_t len, ngx_flag_t close_fd)
Function Documentation
brix_http_add_content_range_header()
ngx_int_t brix_http_add_content_range_header (ngx_http_request_t * r, off_t start, off_t end, off_t size)
Definition at line 135 of file http_file_response.c.
References brix_http_set_header().
Referenced by brix_http_set_file_headers().
brix_http_add_etag_header()
ngx_int_t brix_http_add_etag_header (ngx_http_request_t * r, time_t mtime, off_t size, unsigned etag_flags, ngx_flag_t register_not_modified)
Definition at line 100 of file http_file_response.c.
References brix_http_etag_str(), and brix_http_set_header().
Referenced by brix_http_set_file_headers(), and webdav_handle_head().
brix_http_arm_fd_cleanup()
static ngx_int_t brix_http_arm_fd_cleanup (ngx_http_request_t * r, ngx_fd_t fd, u_char * name, ngx_pool_cleanup_file_t ** clnf_out) static
Definition at line 261 of file http_file_response.c.
References name.
Referenced by brix_http_prepare_file_send().
brix_http_build_range_buf()
static ngx_buf_t * brix_http_build_range_buf (ngx_http_request_t * r, ngx_fd_t fd, const char * path, off_t start, off_t len) static
Definition at line 210 of file http_file_response.c.
References ngx_pcalloc(), and ngx_pnalloc().
Referenced by brix_http_prepare_file_send().
brix_http_chain_append_file_range()
ngx_int_t brix_http_chain_append_file_range (ngx_http_request_t * r, ngx_chain_t ** tail, ngx_fd_t fd, const char * path, off_t start, off_t end, ngx_flag_t close_fd)
Definition at line 27 of file http_file_response.c.
References BRIX_PCALLOC_OR_RETURN, ngx_pcalloc(), and ngx_pnalloc().
Referenced by mp_append_part().
brix_http_prepare_file_send()
static ngx_int_t brix_http_prepare_file_send (ngx_http_request_t * r, ngx_fd_t fd, const char * path, off_t start, off_t len, ngx_flag_t close_fd, ngx_buf_t ** b_out, ngx_pool_cleanup_file_t ** clnf_out) static
Definition at line 299 of file http_file_response.c.
References brix_http_arm_fd_cleanup(), and brix_http_build_range_buf().
Referenced by brix_http_send_file_range().
brix_http_send_file_range()
ngx_int_t brix_http_send_file_range (ngx_http_request_t * r, ngx_fd_t fd, const char * path, off_t start, off_t len, ngx_flag_t close_fd)
Definition at line 345 of file http_file_response.c.
References brix_http_prepare_file_send().
Referenced by dashboard_download_body(), and serve_send_sendfile().
brix_http_set_file_headers()
ngx_int_t brix_http_set_file_headers (ngx_http_request_t * r, time_t mtime, off_t total_size, off_t send_len, const char * content_type, unsigned etag_flags, int has_range, off_t range_start, off_t range_end)
Definition at line 151 of file http_file_response.c.
References brix_http_add_content_range_header(), brix_http_add_etag_header(), and brix_http_set_header().
Referenced by brix_http_serve_file_ranged(), compress_set_headers(), and s3_handle_head().