nginx-xrootd: client/lib/protocols/http/http_download.c File Reference
http_download.c File Reference
#include "http_internal.h"
Functions
int stream_clen (body_src *src, long long remaining, int out_fd, long long *written, brix_status *st)
int stream_eof (body_src *src, int out_fd, long long *written, brix_status *st)
int stream_chunked (body_src *src, int out_fd, long long *written, brix_status *st)
int read_resp_headers (brix_io *io, char *hdr, size_t hdrcap, int timeout_ms, int *status, size_t *total, size_t *body_off, brix_status *st)
int raw_header (const char *hdr, const char *name, char *out, size_t outsz)
int httpx_download_body (brix_io *io, char *hdr, size_t total, size_t body_off, int out_fd, int timeout_ms, long long *body_len, brix_status *st)
int httpx_download_exchange (brix_io *io, const char *host, int port, const char *path, const char *extra_headers, long long start_off, int out_fd, int timeout_ms, int *http_status, long long *body_len, brix_status *st)
static int http_download_attempt (const char *host, int port, int tls, const char *path, const char *extra_headers, int verify, const char *ca_dir, int out_fd, int timeout_ms, long long total_got, int *http_status, long long *body_this, brix_status *st)
static int http_download_should_retry (int seekable, int window_ms, uint64_t deadline, brix_status *st)
int brix_http_download (const char *host, int port, int tls, const char *path, const char *extra_headers, int verify, const char *ca_dir, int out_fd, int timeout_ms, int *http_status, long long *body_len, brix_status *st)
Function Documentation
brix_http_download()
int brix_http_download (const char * host, int port, int tls, const char * path, const char * extra_headers, int verify, const char * ca_dir, int out_fd, int timeout_ms, int * http_status, long long * body_len, brix_status * st)
Definition at line 336 of file http_download.c.
References brix_backoff_sleep_fast(), brix_mono_ns(), fstat(), host, http_download_attempt(), http_download_should_retry(), httpx_window_ms(), port, stat(), and tls.
Referenced by s3_get_verify(), web_dl_fetch(), and web_put_get_verify().
http_download_attempt()
static int http_download_attempt (const char * host, int port, int tls, const char * path, const char * extra_headers, int verify, const char * ca_dir, int out_fd, int timeout_ms, long long total_got, int * http_status, long long * body_this, brix_status * st) static
Definition at line 281 of file http_download.c.
References brix_tls_client_free(), close(), brix_io::fd, host, httpx_connect(), httpx_download_exchange(), lseek(), port, and tls.
Referenced by brix_http_download().
http_download_should_retry()
static int http_download_should_retry (int seekable, int window_ms, uint64_t deadline, brix_status * st) static
Definition at line 322 of file http_download.c.
References brix_mono_ns(), and brix_status_retryable().
Referenced by brix_http_download().
httpx_download_body()
int httpx_download_body (brix_io * io, char * hdr, size_t total, size_t body_off, int out_fd, int timeout_ms, long long * body_len, brix_status * st)
Definition at line 154 of file http_download.c.
References brix_status_set(), body_src::io, body_src::lo, body_src::lo_len, body_src::lo_off, raw_header(), stream_chunked(), stream_clen(), stream_eof(), body_src::timeout_ms, and XRDC_EPROTO.
Referenced by httpx_download_exchange().
httpx_download_exchange()
int httpx_download_exchange (brix_io * io, const char * host, int port, const char * path, const char * extra_headers, long long start_off, int out_fd, int timeout_ms, int * http_status, long long * body_len, brix_status * st)
Definition at line 197 of file http_download.c.
References brix_format_host_port(), brix_status_set(), brix_write_full(), host, httpx_download_body(), port, read_resp_headers(), XRDC_EPROTO, XRDC_EUSAGE, and XRDC_HDR_CAP.
Referenced by http_download_attempt().
raw_header()
int raw_header (const char * hdr, const char * name, char * out, size_t outsz)
Definition at line 119 of file http_download.c.
References name.
Referenced by brix_http_header(), httpx_download_body(), and httpx_read_frame_headers().
read_resp_headers()
int read_resp_headers (brix_io * io, char * hdr, size_t hdrcap, int timeout_ms, int * status, size_t * total, size_t * body_off, brix_status * st)
Definition at line 87 of file http_download.c.
References brix_status_set(), httpx_read_some(), and XRDC_EPROTO.
Referenced by httpx_chunk_read_status(), httpx_download_exchange(), and httpx_upload_response().
stream_chunked()
int stream_chunked (body_src * src, int out_fd, long long * written, brix_status * st)
Definition at line 50 of file http_download.c.
References brix_status_set(), bsrc_getline(), bsrc_read(), write_all_fd(), XRDC_EPROTO, and XRDC_XFER_BUF.
Referenced by httpx_download_body().
stream_clen()
int stream_clen (body_src * src, long long remaining, int out_fd, long long * written, brix_status * st)
Definition at line 10 of file http_download.c.
References brix_status_set(), bsrc_read(), write_all_fd(), XRDC_EPROTO, and XRDC_XFER_BUF.
Referenced by httpx_download_body().
stream_eof()
int stream_eof (body_src * src, int out_fd, long long * written, brix_status * st)
Definition at line 34 of file http_download.c.
References bsrc_read(), write_all_fd(), and XRDC_XFER_BUF.
Referenced by httpx_download_body().