nginx-xrootd: src/net/mirror/http_mirror_request.c File Reference
http_mirror_request.c File Reference
#include "http_mirror.h"
#include "http_mirror_internal.h"
#include "core/http/http_body.h"
#include "core/http/http_headers.h"
Data Structures
struct mirror_req_plan_t
Functions
static ngx_str_t brix_http_mirror_rewrite_dest (ngx_pool_t *pool, ngx_str_t *dest, ngx_str_t *url_base)
static ngx_chain_t * brix_http_mirror_clone_body (ngx_http_request_t *r, ngx_http_request_t *parent, off_t *len_out)
static ngx_int_t mirror_build_subrequest (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *ctx, mirror_req_plan_t *plan)
static size_t mirror_headers_len (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const mirror_req_plan_t *plan)
static void mirror_copy_headers (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const mirror_req_plan_t *plan, ngx_buf_t *b)
static ngx_int_t mirror_set_body (ngx_http_request_t *r, const mirror_req_plan_t *plan, ngx_buf_t *b)
ngx_int_t mirror_create_request (ngx_http_request_t *r)
ngx_int_t mirror_reinit_request (ngx_http_request_t *r)
static ngx_int_t mirror_process_header (ngx_http_request_t *r)
ngx_int_t mirror_process_status_line (ngx_http_request_t *r)
void mirror_abort_request (ngx_http_request_t *r)
void mirror_finalize_request (ngx_http_request_t *r, ngx_int_t rc)
Function Documentation
brix_http_mirror_clone_body()
static ngx_chain_t * brix_http_mirror_clone_body (ngx_http_request_t * r, ngx_http_request_t * parent, off_t * len_out) static
Definition at line 68 of file http_mirror_request.c.
Referenced by mirror_build_subrequest().
brix_http_mirror_rewrite_dest()
static ngx_str_t brix_http_mirror_rewrite_dest (ngx_pool_t * pool, ngx_str_t * dest, ngx_str_t * url_base) static
Definition at line 30 of file http_mirror_request.c.
References ngx_pnalloc().
Referenced by mirror_build_subrequest().
mirror_abort_request()
void mirror_abort_request (ngx_http_request_t * r)
Definition at line 425 of file http_mirror_request.c.
Referenced by brix_http_mirror_proxy().
mirror_build_subrequest()
static ngx_int_t mirror_build_subrequest (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * ctx, mirror_req_plan_t * plan) static
Definition at line 136 of file http_mirror_request.c.
References mirror_req_plan_t::body, brix_http_find_header(), brix_http_mirror_clone_body(), brix_http_mirror_method_has_body(), brix_http_mirror_rewrite_dest(), mirror_req_plan_t::cl_digits, mirror_req_plan_t::clbuf, mirror_req_plan_t::depth_h, mirror_req_plan_t::dest, mirror_req_plan_t::has_body, mirror_req_plan_t::host, brix_mirror_target_t::host, mirror_req_plan_t::inject_token, ngx_http_brix_webdav_loc_conf_t::mirror, ngx_http_brix_webdav_req_ctx_t::mirror_target_idx, mirror_req_plan_t::over_h, mirror_req_plan_t::t, brix_mirror_conf_t::targets, brix_mirror_conf_t::token, and brix_mirror_target_t::url_base.
Referenced by mirror_create_request().
mirror_copy_headers()
static void mirror_copy_headers (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const mirror_req_plan_t * plan, ngx_buf_t * b) static
Definition at line 243 of file http_mirror_request.c.
References mirror_req_plan_t::cl_digits, mirror_req_plan_t::clbuf, mirror_req_plan_t::depth_h, mirror_req_plan_t::dest, mirror_req_plan_t::has_body, mirror_req_plan_t::host, mirror_req_plan_t::inject_token, ngx_http_brix_webdav_loc_conf_t::mirror, mirror_req_plan_t::over_h, brix_mirror_conf_t::strip_auth, and brix_mirror_conf_t::token.
Referenced by mirror_create_request().
mirror_create_request()
ngx_int_t mirror_create_request (ngx_http_request_t * r)
Definition at line 338 of file http_mirror_request.c.
References mirror_build_subrequest(), mirror_copy_headers(), mirror_headers_len(), mirror_set_body(), and ngx_http_brix_webdav_module.
Referenced by brix_http_mirror_proxy().
mirror_finalize_request()
void mirror_finalize_request (ngx_http_request_t * r, ngx_int_t rc)
Definition at line 431 of file http_mirror_request.c.
References brix_mirror_status_class(), brix_mirror_conf_t::log_diverge, MIR_HTTP_INC, ngx_http_brix_webdav_loc_conf_t::mirror, ngx_http_brix_webdav_module, and ngx_http_brix_webdav_req_ctx_t::primary_status.
Referenced by brix_http_mirror_proxy().
mirror_headers_len()
static size_t mirror_headers_len (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const mirror_req_plan_t * plan) static
Definition at line 195 of file http_mirror_request.c.
References mirror_req_plan_t::cl_digits, mirror_req_plan_t::depth_h, mirror_req_plan_t::dest, mirror_req_plan_t::has_body, mirror_req_plan_t::host, mirror_req_plan_t::inject_token, ngx_http_brix_webdav_loc_conf_t::mirror, mirror_req_plan_t::over_h, brix_mirror_conf_t::strip_auth, and brix_mirror_conf_t::token.
Referenced by mirror_create_request().
mirror_process_header()
static ngx_int_t mirror_process_header (ngx_http_request_t * r) static
Definition at line 404 of file http_mirror_request.c.
Referenced by mirror_process_status_line().
mirror_process_status_line()
ngx_int_t mirror_process_status_line (ngx_http_request_t * r)
Definition at line 380 of file http_mirror_request.c.
References mirror_process_header(), ngx_http_brix_webdav_req_ctx_t::mirror_status, and ngx_http_brix_webdav_module.
Referenced by brix_http_mirror_proxy().
mirror_reinit_request()
ngx_int_t mirror_reinit_request (ngx_http_request_t * r)
Definition at line 367 of file http_mirror_request.c.
References ngx_http_brix_webdav_req_ctx_t::mirror_status, and ngx_http_brix_webdav_module.
Referenced by brix_http_mirror_proxy().
mirror_set_body()
static ngx_int_t mirror_set_body (ngx_http_request_t * r, const mirror_req_plan_t * plan, ngx_buf_t * b) static
Definition at line 316 of file http_mirror_request.c.
References mirror_req_plan_t::body.
Referenced by mirror_create_request().