nginx-xrootd: src/core/http/http_compress.c File Reference
http_compress.c File Reference
#include "http_compress.h"
#include "fs/vfs/vfs.h"
#include "http_file_response.h"
#include <unistd.h>
Data Structures
struct compress_send_t
Macros
#define BRIX_COMPRESS_CHUNK (64 * 1024)
Functions
static int content_type_incompressible (ngx_http_request_t *r)
static int accept_encoding_q_is_zero (const u_char *semi, const u_char *seg_end)
static int accept_encoding_segment_has (const u_char *seg, const u_char *seg_end, const char *token, size_t tlen)
static int accept_encoding_has (const u_char *ae, size_t ae_len, const char *token)
brix_codec_id_t brix_http_compress_negotiate (ngx_http_request_t *r, off_t file_size, ngx_flag_t is_range)
static ngx_int_t compress_emit (ngx_http_request_t *r, const u_char *data, size_t len, int last)
static ngx_int_t compress_set_headers (ngx_http_request_t *r, const brix_codec_desc_t *desc, off_t size, time_t mtime, unsigned etag_flags)
static ngx_int_t compress_drain_chunk (compress_send_t *st, size_t fill, int finish, int *ended)
static ngx_int_t compress_stream_step (compress_send_t *st, int *done)
static ngx_int_t compress_stream_body (compress_send_t *st)
ngx_int_t brix_http_send_file_compressed (ngx_http_request_t *r, ngx_fd_t send_fd, const char *fs_path, off_t size, brix_codec_id_t codec, time_t mtime, unsigned etag_flags, off_t *bytes_in_out)
Variables
static const brix_codec_id_t brix_compress_pref []
Macro Definition Documentation
BRIX_COMPRESS_CHUNK
#define BRIX_COMPRESS_CHUNK (64 * 1024)
Definition at line 17 of file http_compress.c.
Function Documentation
accept_encoding_has()
static int accept_encoding_has (const u_char * ae, size_t ae_len, const char * token) static
Definition at line 117 of file http_compress.c.
References accept_encoding_segment_has().
Referenced by brix_http_compress_negotiate().
accept_encoding_q_is_zero()
static int accept_encoding_q_is_zero (const u_char * semi, const u_char * seg_end) static
Definition at line 63 of file http_compress.c.
Referenced by accept_encoding_segment_has().
accept_encoding_segment_has()
static int accept_encoding_segment_has (const u_char * seg, const u_char * seg_end, const char * token, size_t tlen) static
Definition at line 94 of file http_compress.c.
References accept_encoding_q_is_zero().
Referenced by accept_encoding_has().
brix_http_compress_negotiate()
brix_codec_id_t brix_http_compress_negotiate (ngx_http_request_t * r, off_t file_size, ngx_flag_t is_range)
Definition at line 138 of file http_compress.c.
References accept_encoding_has(), brix_codec_desc_t::available, brix_codec_by_id(), BRIX_CODEC_IDENTITY, BRIX_COMPRESS_MIN_SIZE, brix_compress_pref, content_type_incompressible(), and brix_codec_desc_t::http_token.
Referenced by serve_try_compressed().
brix_http_send_file_compressed()
ngx_int_t brix_http_send_file_compressed (ngx_http_request_t * r, ngx_fd_t send_fd, const char * fs_path, off_t size, brix_codec_id_t codec, time_t mtime, unsigned etag_flags, off_t * bytes_in_out)
Definition at line 338 of file http_compress.c.
References brix_codec_desc_t::available, brix_codec_by_id(), brix_codec_close(), BRIX_CODEC_DIR_COMPRESS, brix_codec_open(), BRIX_COMPRESS_CHUNK, compress_send_t::bytes_in_out, compress_set_headers(), compress_stream_body(), compress_send_t::fd, compress_send_t::inbuf, compress_send_t::outbuf, compress_send_t::r, compress_send_t::size, and compress_send_t::stream.
Referenced by serve_try_compressed().
compress_drain_chunk()
static ngx_int_t compress_drain_chunk (compress_send_t * st, size_t fill, int finish, int * ended) static
Definition at line 265 of file http_compress.c.
References BRIX_CODEC_END, brix_codec_step(), BRIX_COMPRESS_CHUNK, compress_send_t::bytes_in_out, compress_emit(), compress_send_t::inbuf, op, compress_send_t::outbuf, compress_send_t::r, and compress_send_t::stream.
Referenced by compress_stream_step().
compress_emit()
static ngx_int_t compress_emit (ngx_http_request_t * r, const u_char * data, size_t len, int last) static
Definition at line 170 of file http_compress.c.
References ngx_memcpy.
Referenced by compress_drain_chunk().
compress_set_headers()
static ngx_int_t compress_set_headers (ngx_http_request_t * r, const brix_codec_desc_t * desc, off_t size, time_t mtime, unsigned etag_flags) static
Definition at line 224 of file http_compress.c.
References brix_http_set_file_headers(), and brix_codec_desc_t::http_token.
Referenced by brix_http_send_file_compressed().
compress_stream_body()
static ngx_int_t compress_stream_body (compress_send_t * st) static
Definition at line 325 of file http_compress.c.
References compress_stream_step().
Referenced by brix_http_send_file_compressed().
compress_stream_step()
static ngx_int_t compress_stream_step (compress_send_t * st, int * done) static
Definition at line 301 of file http_compress.c.
References BRIX_COMPRESS_CHUNK, brix_vfs_pread_full(), compress_drain_chunk(), compress_send_t::fd, compress_send_t::inbuf, compress_send_t::off, and compress_send_t::size.
Referenced by compress_stream_body().
content_type_incompressible()
static int content_type_incompressible (ngx_http_request_t * r) static
Definition at line 28 of file http_compress.c.
Referenced by brix_http_compress_negotiate().
Variable Documentation
brix_compress_pref
const brix_codec_id_t brix_compress_pref[] static
Initial value:
= {
    BRIX_CODEC_ZSTD, BRIX_CODEC_BROTLI, BRIX_CODEC_GZIP,
    BRIX_CODEC_XZ, BRIX_CODEC_DEFLATE, BRIX_CODEC_BZIP2,
    BRIX_CODEC_LZ4
}
Definition at line 20 of file http_compress.c.
Referenced by brix_http_compress_negotiate().