nginx-xrootd: src/core/config/http_common.c File Reference
http_common.c File Reference
#include "core/config/http_common.h"
#include "core/config/tier_directives.h"
#include "fs/cache/verify.h"
#include "fs/backend/sd.h"
#include <stdio.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
#include <openssl/evp.h>
Macros
#define BRIX_HTTP_ALL_CONF (NGX_HTTP_MAIN_CONF|NGX_HTTP_SRV_CONF|NGX_HTTP_LOC_CONF)
#define BRIX_ADOPT_STR(f) do { if (dst->f.data == NULL && src->f.data != NULL) dst->f = src->f; } while (0)
#define BRIX_ADOPT_VAL(f, unset) do { if (dst->f == (unset) && src->f != (unset)) dst->f = src->f; } while (0)
#define BRIX_ADOPT_PTR(f) do { if (dst->f == NULL && src->f != NULL) dst->f = src->f; } while (0)
Functions
static void * brix_http_common_create_loc_conf (ngx_conf_t *cf)
static char * brix_http_common_merge_loc_conf (ngx_conf_t *cf, void *parent, void *child)
static char * brix_conf_set_mint_ca (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
void brix_shared_adopt_unified (ngx_http_brix_shared_conf_t *dst, const ngx_http_brix_shared_conf_t *src)
void brix_http_common_adopt (ngx_conf_t *cf, ngx_http_brix_shared_conf_t *dst)
Variables
static ngx_conf_enum_t brix_http_ucred_fallback_enum []
static ngx_conf_enum_t brix_backend_delegation_enum []
static ngx_conf_enum_t brix_http_cache_verify_enum []
static ngx_command_t brix_http_common_commands []
static ngx_http_module_t brix_http_common_module_ctx
ngx_module_t ngx_http_brix_common_module
Macro Definition Documentation
BRIX_ADOPT_PTR
#define BRIX_ADOPT_PTR (f) do { if (dst->f == NULL && src->f != NULL) dst->f = src->f; } while (0)
Definition at line 332 of file http_common.c.
BRIX_ADOPT_STR
#define BRIX_ADOPT_STR (f) do { if (dst->f.data == NULL && src->f.data != NULL) dst->f = src->f; } while (0)
Definition at line 328 of file http_common.c.
BRIX_ADOPT_VAL
#define BRIX_ADOPT_VAL (f, unset) do { if (dst->f == (unset) && src->f != (unset)) dst->f = src->f; } while (0)
Definition at line 330 of file http_common.c.
BRIX_HTTP_ALL_CONF
#define BRIX_HTTP_ALL_CONF (NGX_HTTP_MAIN_CONF|NGX_HTTP_SRV_CONF|NGX_HTTP_LOC_CONF)
Definition at line 99 of file http_common.c.
Function Documentation
brix_conf_set_mint_ca()
static char * brix_conf_set_mint_ca (ngx_conf_t * cf, ngx_command_t * cmd, void * conf) static
Definition at line 45 of file http_common.c.
References c, and key.
brix_http_common_adopt()
void brix_http_common_adopt (ngx_conf_t * cf, ngx_http_brix_shared_conf_t * dst)
Definition at line 377 of file http_common.c.
References brix_shared_adopt_unified(), ngx_http_brix_common_conf_t::common, and ngx_http_brix_common_module.
Referenced by cvmfs_merge_preamble(), s3_merge_preamble(), and webdav_merge_base_conf().
brix_http_common_create_loc_conf()
static void * brix_http_common_create_loc_conf (ngx_conf_t * cf) static
Definition at line 298 of file http_common.c.
References c, ngx_http_brix_shared_init(), and ngx_pcalloc().
brix_http_common_merge_loc_conf()
static char * brix_http_common_merge_loc_conf (ngx_conf_t * cf, void * parent, void * child) static
Definition at line 318 of file http_common.c.
References brix_shared_adopt_unified(), and ngx_http_brix_common_conf_t::common.
brix_shared_adopt_unified()
void brix_shared_adopt_unified (ngx_http_brix_shared_conf_t * dst, const ngx_http_brix_shared_conf_t * src)
Definition at line 336 of file http_common.c.
References BRIX_ADOPT_PTR, BRIX_ADOPT_STR, and BRIX_ADOPT_VAL.
Referenced by brix_http_common_adopt(), and brix_http_common_merge_loc_conf().
Variable Documentation
brix_backend_delegation_enum
ngx_conf_enum_t brix_backend_delegation_enum[] static
Initial value:
= {
    { ngx_string("select"),      BRIX_CRED_SELECT },
    { ngx_string("passthrough"), BRIX_CRED_PASSTHROUGH },
    { ngx_string("exchange"),    BRIX_CRED_EXCHANGE },
    { ngx_string("delegate"),    BRIX_CRED_DELEGATE },
    { ngx_string("mint"),        BRIX_CRED_MINT },
    { ngx_string("auto"),        BRIX_CRED_AUTO },
    { ngx_null_string, 0 }
}
Definition at line 24 of file http_common.c.
brix_http_cache_verify_enum
ngx_conf_enum_t brix_http_cache_verify_enum[] static
Initial value:
= {
    { ngx_string("off"),       BRIX_CACHE_VERIFY_OFF },
    { ngx_string("cvmfs-cas"), BRIX_CACHE_VERIFY_CVMFS_CAS },
    { ngx_null_string, 0 }
}
Definition at line 93 of file http_common.c.
brix_http_common_commands
ngx_command_t brix_http_common_commands[] static
Definition at line 102 of file http_common.c.
brix_http_common_module_ctx
ngx_http_module_t brix_http_common_module_ctx static
Initial value:
= {
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    brix_http_common_create_loc_conf,
    brix_http_common_merge_loc_conf
}
Definition at line 275 of file http_common.c.
brix_http_ucred_fallback_enum
ngx_conf_enum_t brix_http_ucred_fallback_enum[] static
Initial value:
= {
    { ngx_string("allow"), 0 },
    { ngx_string("deny"),  1 },
    { ngx_null_string, 0 }
}
Definition at line 16 of file http_common.c.
ngx_http_brix_common_module
ngx_module_t ngx_http_brix_common_module
Initial value:
= {
    NGX_MODULE_V1,
    &brix_http_common_module_ctx,
    brix_http_common_commands,
    NGX_HTTP_MODULE,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NGX_MODULE_V1_PADDING
}
Definition at line 283 of file http_common.c.
Referenced by brix_http_common_adopt().