nginx-xrootd: src/core/http/http_query.c File Reference
http_query.c File Reference
#include "http_query.h"
#include "core/compat/uri.h"
Functions
static int brix_http_query_key_eq (const u_char *a, const char *b, size_t len, unsigned flags)
static int brix_http_query_hex (u_char c, u_char *out)
static int brix_http_query_pct (const u_char *src, size_t src_len, size_t si, u_char *out)
static int brix_http_query_emit (char *dst, size_t dst_sz, size_t *di, u_char c, unsigned flags)
static int brix_http_query_decode_trunc (const u_char *src, size_t src_len, char *dst, size_t dst_sz, unsigned flags)
static int brix_http_query_copy_value (const u_char *src, size_t src_len, char *dst, size_t dst_sz, unsigned flags)
int brix_http_query_get (ngx_str_t args, const char *key, char *out, size_t outsz, unsigned flags)
int brix_http_query_has (ngx_str_t args, const char *key, unsigned flags)
Function Documentation
brix_http_query_copy_value()
static int brix_http_query_copy_value (const u_char * src, size_t src_len, char * dst, size_t dst_sz, unsigned flags) static
Definition at line 197 of file http_query.c.
References brix_http_query_decode_trunc(), BRIX_HTTP_QUERY_DECODE_VALUE, BRIX_HTTP_QUERY_PLUS_TO_SPACE, BRIX_HTTP_QUERY_REJECT_NUL, BRIX_HTTP_QUERY_TRUNCATE, brix_http_urldecode(), BRIX_URLDECODE_OK, BRIX_URLDECODE_PLUS_TO_SPACE, BRIX_URLDECODE_REJECT_NUL, and ngx_memcpy.
Referenced by brix_http_query_get().
brix_http_query_decode_trunc()
static int brix_http_query_decode_trunc (const u_char * src, size_t src_len, char * dst, size_t dst_sz, unsigned flags) static
Definition at line 144 of file http_query.c.
References brix_http_query_emit(), brix_http_query_pct(), BRIX_HTTP_QUERY_PLUS_TO_SPACE, and c.
Referenced by brix_http_query_copy_value().
brix_http_query_emit()
static int brix_http_query_emit (char * dst, size_t dst_sz, size_t * di, u_char c, unsigned flags) static
Definition at line 112 of file http_query.c.
References BRIX_HTTP_QUERY_REJECT_NUL, and c.
Referenced by brix_http_query_decode_trunc().
brix_http_query_get()
int brix_http_query_get (ngx_str_t args, const char * key, char * out, size_t outsz, unsigned flags)
Definition at line 254 of file http_query.c.
References BRIX_HTTP_QUERY_ALLOW_EMPTY, brix_http_query_copy_value(), brix_http_query_key_eq(), and key.
Referenced by s3_apply_response_overrides(), s3_get_query_param(), s3_handle_list_v1(), s3_is_list_request(), s3_list_decode_params(), s3_list_parse_max_keys(), s3_override_header(), and xrdhttp_args_get().
brix_http_query_has()
int brix_http_query_has (ngx_str_t args, const char * key, unsigned flags)
Definition at line 309 of file http_query.c.
References BRIX_HTTP_QUERY_HAS_VALUE_OK, brix_http_query_key_eq(), and key.
Referenced by s3_has_query_flag(), and xrdhttp_args_has_key().
brix_http_query_hex()
static int brix_http_query_hex (u_char c, u_char * out) static
Definition at line 54 of file http_query.c.
References c.
Referenced by brix_http_query_pct().
brix_http_query_key_eq()
static int brix_http_query_key_eq (const u_char * a, const char * b, size_t len, unsigned flags) static
Definition at line 29 of file http_query.c.
References BRIX_HTTP_QUERY_CASE_INSENSITIVE.
Referenced by brix_http_query_get(), and brix_http_query_has().
brix_http_query_pct()
static int brix_http_query_pct (const u_char * src, size_t src_len, size_t si, u_char * out) static
Definition at line 78 of file http_query.c.
References brix_http_query_hex().
Referenced by brix_http_query_decode_trunc().