nginx-xrootd: src/core/http/http_headers.c File Reference
http_headers.c File Reference
#include "http_headers.h"
#include "core/compat/cstr.h"
#include <string.h>
Functions
ngx_table_elt_t * brix_http_find_header (ngx_http_request_t *r, const char *name, size_t name_len)
ngx_str_t brix_http_get_header (ngx_http_request_t *r, const char *name)
static u_char * brix_http_skip_ws (u_char *p, const u_char *end)
static u_char * brix_http_trim_trailing_ws (const u_char *start, u_char *end)
ngx_int_t brix_http_extract_bearer (const ngx_str_t *auth_header, ngx_str_t *token_out)
ngx_int_t brix_http_str_has_ctl (const u_char *data, size_t len)
ngx_int_t brix_http_header_value_equals (const ngx_str_t *value, const char *literal)
static int brix_hex_nibble (u_char c)
size_t brix_urldecode_inplace (char *str)
ngx_int_t brix_http_arg (ngx_http_request_t *r, const char *name, size_t name_len, ngx_str_t *out)
void brix_http_redact_query_token (ngx_str_t *query)
Function Documentation
brix_hex_nibble()
static int brix_hex_nibble (u_char c) static
Definition at line 285 of file http_headers.c.
References c.
Referenced by brix_urldecode_inplace().
brix_http_arg()
ngx_int_t brix_http_arg (ngx_http_request_t * r, const char * name, size_t name_len, ngx_str_t * out)
Definition at line 319 of file http_headers.c.
References brix_pstrdup_z(), and name.
Referenced by webdav_bearer_from_query().
brix_http_extract_bearer()
ngx_int_t brix_http_extract_bearer (const ngx_str_t * auth_header, ngx_str_t * token_out)
Definition at line 165 of file http_headers.c.
References brix_http_skip_ws(), and brix_http_trim_trailing_ws().
Referenced by admin_auth_secret_ok(), webdav_introspect_access_handler(), webdav_tpc_extract_subject_token(), and wt_parse_header().
brix_http_find_header()
ngx_table_elt_t * brix_http_find_header (ngx_http_request_t * r, const char * name, size_t name_len)
Definition at line 43 of file http_headers.c.
References key, and name.
Referenced by brix_http_add_cors_headers(), brix_http_get_header(), brix_http_overwrite_forbidden(), brix_proto_deleg_capture_proxy_header(), cors_emit_allow_headers(), mirror_build_subrequest(), s3_add_preflight_headers(), s3_apply_put_tagging_header(), s3_aws_chunked_has_inner_coding(), s3_body_is_aws_chunked(), s3_copy_find_header(), s3_dispatch_object_put(), s3_echo_object_checksums(), s3_find_request_header_value(), s3_is_post_object_form(), s3_post_boundary(), s3_prepare_upload_part(), s3_put_select_algo(), s3_put_streaming(), s3put_select_codec(), webdav_add_cors_headers(), webdav_put_precheck(), and webdav_put_select_codec().
brix_http_get_header()
ngx_str_t brix_http_get_header (ngx_http_request_t * r, const char * name)
Definition at line 93 of file http_headers.c.
References brix_http_find_header(), and name.
Referenced by get_header(), propfind_parse_depth(), webdav_dispatch_macaroon(), and webdav_sess_mode().
brix_http_header_value_equals()
ngx_int_t brix_http_header_value_equals (const ngx_str_t * value, const char * literal)
Definition at line 259 of file http_headers.c.
References brix_http_skip_ws(), and brix_http_trim_trailing_ws().
Referenced by brix_http_overwrite_forbidden().
brix_http_redact_query_token()
void brix_http_redact_query_token (ngx_str_t * query)
Definition at line 339 of file http_headers.c.
Referenced by wt_parse_header().
brix_http_skip_ws()
static u_char * brix_http_skip_ws (u_char * p, const u_char * end) static
Definition at line 120 of file http_headers.c.
Referenced by brix_http_extract_bearer(), and brix_http_header_value_equals().
brix_http_str_has_ctl()
ngx_int_t brix_http_str_has_ctl (const u_char * data, size_t len)
Definition at line 226 of file http_headers.c.
Referenced by cors_emit_allow_headers(), s3_add_preflight_headers(), s3_apply_response_overrides(), s3_override_header(), s3_post_expand_filename(), and s3_post_send_success().
brix_http_trim_trailing_ws()
static u_char * brix_http_trim_trailing_ws (const u_char * start, u_char * end) static
Definition at line 144 of file http_headers.c.
Referenced by brix_http_extract_bearer(), and brix_http_header_value_equals().
brix_urldecode_inplace()
size_t brix_urldecode_inplace (char * str)
Definition at line 294 of file http_headers.c.
References brix_hex_nibble().
Referenced by webdav_bearer_from_query().