nginx-xrootd: src/core/http/http_xml.c File Reference
http_xml.c File Reference
#include "http_xml.h"
#include "core/compat/xml.h"
#include <stdio.h>
#include <string.h>
Functions
ngx_buf_t * brix_http_chain_vappendf (ngx_pool_t *pool, ngx_chain_t **head, ngx_chain_t **tail, const char *fmt, va_list ap)
ngx_buf_t * brix_http_chain_appendf (ngx_pool_t *pool, ngx_chain_t **head, ngx_chain_t **tail, const char *fmt,...)
ngx_int_t brix_http_send_xml_buffer (ngx_http_request_t *r, ngx_uint_t status, ngx_str_t content_type, ngx_buf_t *b)
ngx_int_t brix_http_send_xml_error (ngx_http_request_t *r, ngx_uint_t status, const char *code, const char *message)
Function Documentation
brix_http_chain_appendf()
ngx_buf_t * brix_http_chain_appendf (ngx_pool_t * pool, ngx_chain_t ** head, ngx_chain_t ** tail, const char * fmt, ...)
Definition at line 117 of file http_xml.c.
References brix_http_chain_vappendf().
Referenced by propfind_append_acl_properties(), propfind_build_body(), propfind_emit_404_propstat(), propfind_emit_acl(), propfind_emit_basic_metadata(), propfind_emit_current_privilege(), propfind_emit_displayname(), propfind_emit_locality(), propfind_emit_owner(), propfind_emit_quota(), propfind_emit_standard_props(), propfind_emit_supported_privilege(), propfind_entry(), webdav_dead_prop_append_empty(), webdav_dead_prop_append_value(), webdav_handle_acl(), webdav_lock_append_discovery(), webdav_lock_append_supported(), webdav_lock_xml_response(), webdav_proppatch_append_propstat(), webdav_proppatch_finish_multistatus(), webdav_proppatch_start_multistatus(), webdav_search_append_response(), and webdav_search_build_body().
brix_http_chain_vappendf()
ngx_buf_t * brix_http_chain_vappendf (ngx_pool_t * pool, ngx_chain_t ** head, ngx_chain_t ** tail, const char * fmt, va_list ap)
Definition at line 45 of file http_xml.c.
References ngx_memcpy, and ngx_pnalloc().
Referenced by brix_http_chain_appendf().
brix_http_send_xml_buffer()
ngx_int_t brix_http_send_xml_buffer (ngx_http_request_t * r, ngx_uint_t status, ngx_str_t content_type, ngx_buf_t * b)
Definition at line 146 of file http_xml.c.
Referenced by brix_http_send_xml_error(), lp_render_xml(), mpu_render_and_send(), s3_delete_objects_finish(), s3_handle_copy_object(), s3_handle_get_acl(), s3_handle_get_bucket_location(), s3_handle_get_object_tagging(), s3_handle_multipart_initiate(), s3_list_finalize(), s3_mpu_send_result(), s3_send_copy_part_result(), and s3_send_xml_literal().
brix_http_send_xml_error()
ngx_int_t brix_http_send_xml_error (ngx_http_request_t * r, ngx_uint_t status, const char * code, const char * message)
Definition at line 183 of file http_xml.c.
References brix_http_send_xml_buffer(), BRIX_XML_ESCAPE_APOS_ENTITY, brix_xml_text_element_len(), brix_xml_write_text_element(), and code.
Referenced by s3_send_xml_error().