nginx-xrootd: src/core/http/http_conditionals.c File Reference
http_conditionals.c File Reference
#include "http_conditionals.h"
#include "etag.h"
#include "http_headers.h"
#include <string.h>
Functions
static void brix_http_strip_weak (const char **data, size_t *len)
static ngx_flag_t brix_http_next_etag_token (const char **cursor, const char *end, const char **tok_start, size_t *tok_len)
ngx_int_t brix_http_etag_list_contains (const ngx_str_t *header, const char *etag, unsigned flags)
static ngx_flag_t cond_header_present (const ngx_table_elt_t *h)
static ngx_flag_t cond_is_wildcard (const ngx_str_t *v)
static ngx_flag_t brix_http_validator_selects (const ngx_str_t *value, ngx_flag_t resource_exists, const char *etag, unsigned condition_flags)
static ngx_int_t brix_http_eval_if_unmodified_since (const ngx_table_elt_t *if_unmod, time_t mtime)
static ngx_int_t brix_http_eval_if_modified_since (const ngx_table_elt_t *if_mod, time_t mtime)
ngx_int_t brix_http_check_etag_preconditions (ngx_http_request_t *r, ngx_flag_t resource_exists, const struct stat *st, unsigned etag_flags, unsigned condition_flags)
static ngx_int_t brix_http_eval_match_group (ngx_table_elt_t *if_match, ngx_table_elt_t *if_unmod, ngx_flag_t resource_exists, const char *etag, unsigned condition_flags, unsigned time_mode, time_t mtime)
static ngx_int_t brix_http_eval_none_match_group (ngx_table_elt_t *if_none, ngx_table_elt_t *if_mod, ngx_flag_t resource_exists, const char *etag, unsigned condition_flags, unsigned read_mode, unsigned time_mode, time_t mtime)
ngx_int_t brix_http_eval_preconditions (ngx_http_request_t *r, ngx_flag_t resource_exists, time_t mtime, off_t size, unsigned etag_flags, unsigned condition_flags)
ngx_int_t brix_http_check_if_modified_since (ngx_http_request_t *r, time_t mtime)
ngx_flag_t brix_http_overwrite_forbidden (ngx_http_request_t *r)
Function Documentation
brix_http_check_etag_preconditions()
ngx_int_t brix_http_check_etag_preconditions (ngx_http_request_t * r, ngx_flag_t resource_exists, const struct stat * st, unsigned etag_flags, unsigned condition_flags)
Definition at line 239 of file http_conditionals.c.
References brix_http_etag_str(), and brix_http_validator_selects().
Referenced by webdav_check_copy_conditionals(), and webdav_put_precheck().
brix_http_check_if_modified_since()
ngx_int_t brix_http_check_if_modified_since (ngx_http_request_t * r, time_t mtime)
Definition at line 399 of file http_conditionals.c.
Referenced by cvmfs_tier_open_respond(), and get_eval_conditionals().
brix_http_etag_list_contains()
ngx_int_t brix_http_etag_list_contains (const ngx_str_t * header, const char * etag, unsigned flags)
Definition at line 95 of file http_conditionals.c.
References BRIX_HTTP_COND_WEAK_EQUIV, brix_http_next_etag_token(), and brix_http_strip_weak().
Referenced by brix_http_validator_selects().
brix_http_eval_if_modified_since()
static ngx_int_t brix_http_eval_if_modified_since (const ngx_table_elt_t * if_mod, time_t mtime) static
Definition at line 228 of file http_conditionals.c.
Referenced by brix_http_eval_none_match_group().
brix_http_eval_if_unmodified_since()
static ngx_int_t brix_http_eval_if_unmodified_since (const ngx_table_elt_t * if_unmod, time_t mtime) static
Definition at line 205 of file http_conditionals.c.
Referenced by brix_http_eval_match_group().
brix_http_eval_match_group()
static ngx_int_t brix_http_eval_match_group (ngx_table_elt_t * if_match, ngx_table_elt_t * if_unmod, ngx_flag_t resource_exists, const char * etag, unsigned condition_flags, unsigned time_mode, time_t mtime) static
Definition at line 298 of file http_conditionals.c.
References brix_http_eval_if_unmodified_since(), brix_http_validator_selects(), and cond_header_present().
Referenced by brix_http_eval_preconditions().
brix_http_eval_none_match_group()
static ngx_int_t brix_http_eval_none_match_group (ngx_table_elt_t * if_none, ngx_table_elt_t * if_mod, ngx_flag_t resource_exists, const char * etag, unsigned condition_flags, unsigned read_mode, unsigned time_mode, time_t mtime) static
Definition at line 336 of file http_conditionals.c.
References brix_http_eval_if_modified_since(), brix_http_validator_selects(), and cond_header_present().
Referenced by brix_http_eval_preconditions().
brix_http_eval_preconditions()
ngx_int_t brix_http_eval_preconditions (ngx_http_request_t * r, ngx_flag_t resource_exists, time_t mtime, off_t size, unsigned etag_flags, unsigned condition_flags)
Definition at line 359 of file http_conditionals.c.
References BRIX_HTTP_COND_READ, BRIX_HTTP_COND_TIME, brix_http_etag_str(), brix_http_eval_match_group(), and brix_http_eval_none_match_group().
Referenced by s3_handle_conditional(), and s3_put_precondition().
brix_http_next_etag_token()
static ngx_flag_t brix_http_next_etag_token (const char ** cursor, const char * end, const char ** tok_start, size_t * tok_len) static
Definition at line 63 of file http_conditionals.c.
Referenced by brix_http_etag_list_contains().
brix_http_overwrite_forbidden()
ngx_flag_t brix_http_overwrite_forbidden (ngx_http_request_t * r)
Definition at line 418 of file http_conditionals.c.
References brix_http_find_header(), and brix_http_header_value_equals().
Referenced by webdav_copy_parse_request(), and webdav_handle_move().
brix_http_strip_weak()
static void brix_http_strip_weak (const char ** data, size_t * len) static
Definition at line 38 of file http_conditionals.c.
Referenced by brix_http_etag_list_contains().
brix_http_validator_selects()
static ngx_flag_t brix_http_validator_selects (const ngx_str_t * value, ngx_flag_t resource_exists, const char * etag, unsigned condition_flags) static
Definition at line 179 of file http_conditionals.c.
References brix_http_etag_list_contains(), and cond_is_wildcard().
Referenced by brix_http_check_etag_preconditions(), brix_http_eval_match_group(), and brix_http_eval_none_match_group().
cond_header_present()
static ngx_flag_t cond_header_present (const ngx_table_elt_t * h) static
Definition at line 143 of file http_conditionals.c.
Referenced by brix_http_eval_match_group(), and brix_http_eval_none_match_group().
cond_is_wildcard()
static ngx_flag_t cond_is_wildcard (const ngx_str_t * v) static
Definition at line 157 of file http_conditionals.c.
Referenced by brix_http_validator_selects().