nginx-xrootd: src/net/mirror/http_mirror_config.c File Reference
http_mirror_config.c File Reference
#include "http_mirror.h"
Functions
ngx_int_t brix_http_mirror_setup (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_loc_conf_t *prev)
char * brix_http_mirror_set_url (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_http_mirror_set_methods (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Function Documentation
brix_http_mirror_set_methods()
char * brix_http_mirror_set_methods (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 172 of file http_mirror_config.c.
References BRIX_MIRROR_M_COPY, BRIX_MIRROR_M_DELETE, BRIX_MIRROR_M_GET, BRIX_MIRROR_M_HEAD, BRIX_MIRROR_M_MKCOL, BRIX_MIRROR_M_MOVE, BRIX_MIRROR_M_OPTIONS, BRIX_MIRROR_M_PROPFIND, BRIX_MIRROR_M_PUT, brix_mirror_conf_t::method_mask, and ngx_http_brix_webdav_loc_conf_t::mirror.
brix_http_mirror_set_url()
char * brix_http_mirror_set_url (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 85 of file http_mirror_config.c.
References BRIX_MIRROR_MAX_TARGETS, brix_mirror_target_t::host, ngx_http_brix_webdav_loc_conf_t::mirror, ngx_memcpy, ngx_pnalloc(), brix_mirror_target_t::port, brix_mirror_target_t::sockaddr, brix_mirror_target_t::socklen, brix_mirror_target_t::ssl, brix_mirror_conf_t::targets, brix_mirror_target_t::url, and brix_mirror_target_t::url_base.
brix_http_mirror_setup()
ngx_int_t brix_http_mirror_setup (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_loc_conf_t * prev)
Definition at line 20 of file http_mirror_config.c.
References BRIX_MIRROR_DEFAULT_TIMEOUT_MS, ngx_http_brix_webdav_loc_conf_t::mirror, ngx_http_brix_webdav_loc_conf_t::mirror_upstream_conf, ngx_pcalloc(), s, and brix_mirror_conf_t::timeout_ms.
Referenced by webdav_merge_mirror_and_summary().