nginx-xrootd: client/lib/protocols/http/http_internal.h File Reference
http_internal.h File Reference
#include "brix.h"
#include "core/compat/host_format.h"
#include <errno.h>
#include <poll.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
struct body_src
Macros
#define XRDC_HTTP_MAX (1u << 20)
#define XRDC_HTTPX_MAX (8u << 20) /* 8 MiB body ceiling for the deep-dive */
#define XRDC_XFER_BUF (1u << 16) /* 64 KiB socket↔fd window */
#define XRDC_HDR_CAP (1u << 14) /* 16 KiB response-header ceiling */
Functions
ssize_t httpx_read_some (brix_io *io, void *buf, size_t n, int timeout_ms, brix_status *st)
int ci_contains (const char *hay, const char *needle)
size_t dechunk (char *b, size_t len)
void httpx_parse (char *buf, size_t total, brix_http_resp *resp)
int httpx_body_complete (const char *buf, size_t total, size_t body_off, long long clen, int chunked)
int httpx_exchange (brix_io *io, const char *host, int port, const char *method, const char *path, const char *extra_headers, const void *body, size_t blen, int timeout_ms, brix_http_resp *resp, brix_status *st)
int httpx_connect (brix_io *io, const char *host, int port, int tls, int verify, const char *ca_dir, int timeout_ms, void **tls_ctx, brix_status *st)
ssize_t bsrc_read (body_src *s, void *buf, size_t n, brix_status *st)
int bsrc_getline (body_src *s, char *out, size_t outsz, brix_status *st)
int write_all_fd (int fd, const char *buf, size_t n, brix_status *st)
int stream_clen (body_src *src, long long remaining, int out_fd, long long *written, brix_status *st)
int stream_eof (body_src *src, int out_fd, long long *written, brix_status *st)
int stream_chunked (body_src *src, int out_fd, long long *written, brix_status *st)
int read_resp_headers (brix_io *io, char *hdr, size_t hdrcap, int timeout_ms, int *status, size_t *total, size_t *body_off, brix_status *st)
int raw_header (const char *hdr, const char *name, char *out, size_t outsz)
int httpx_download_body (brix_io *io, char *hdr, size_t total, size_t body_off, int out_fd, int timeout_ms, long long *body_len, brix_status *st)
int httpx_download_exchange (brix_io *io, const char *host, int port, const char *path, const char *extra_headers, long long start_off, int out_fd, int timeout_ms, int *http_status, long long *body_len, brix_status *st)
int httpx_window_ms (void)
int httpx_upload_body (brix_io *io, brix_http_body_src_fn src, void *src_ctx, long long base_off, long long clen, brix_status *st)
int httpx_upload_response (brix_io *io, int timeout_ms, int *http_status, brix_status *st)
int httpx_upload_exchange (brix_io *io, const char *host, int port, const char *path, const char *extra_headers, brix_http_body_src_fn src, void *src_ctx, long long clen, int timeout_ms, int *http_status, brix_status *st)
long long httpx_parse_upload_offset (const char *hdr, size_t len)
int httpx_upload_chunk (brix_io *io, const char *host, int port, const char *path, const char *extra_headers, brix_http_body_src_fn src, void *src_ctx, long long off, long long chunk_len, long long total, int timeout_ms, int *status_out, long long *srv_off_out, brix_status *st)
Macro Definition Documentation
XRDC_HDR_CAP
#define XRDC_HDR_CAP (1u << 14) /* 16 KiB response-header ceiling */
Definition at line 21 of file http_internal.h.
XRDC_HTTP_MAX
#define XRDC_HTTP_MAX (1u << 20)
Definition at line 17 of file http_internal.h.
XRDC_HTTPX_MAX
#define XRDC_HTTPX_MAX (8u << 20) /* 8 MiB body ceiling for the deep-dive */
Definition at line 19 of file http_internal.h.
XRDC_XFER_BUF
#define XRDC_XFER_BUF (1u << 16) /* 64 KiB socket↔fd window */
Definition at line 20 of file http_internal.h.
Function Documentation
bsrc_getline()
int bsrc_getline (body_src * s, char * out, size_t outsz, brix_status * st)
Definition at line 347 of file http.c.
References bsrc_read(), and s.
Referenced by stream_chunked().
bsrc_read()
ssize_t bsrc_read (body_src * s, void * buf, size_t n, brix_status * st)
Definition at line 331 of file http.c.
References httpx_read_some(), and s.
Referenced by bsrc_getline(), stream_chunked(), stream_clen(), and stream_eof().
ci_contains()
int ci_contains (const char * hay, const char * needle)
Definition at line 202 of file http.c.
Referenced by httpx_parse(), and httpx_read_frame_headers().
dechunk()
size_t dechunk (char * b, size_t len)
Definition at line 214 of file http.c.
Referenced by httpx_parse().
httpx_body_complete()
int httpx_body_complete (const char * buf, size_t total, size_t body_off, long long clen, int chunked)
Definition at line 52 of file http_req.c.
Referenced by httpx_read_response().
httpx_connect()
int httpx_connect (brix_io * io, const char * host, int port, int tls, int verify, const char * ca_dir, int timeout_ms, void ** tls_ctx, brix_status * st)
Definition at line 303 of file http.c.
References brix_tcp_connect(), brix_tls_client(), close(), brix_io::fd, host, port, brix_io::timeout_ms, and tls.
Referenced by brix_http_req(), brix_http_upload(), http_download_attempt(), and httpx_resumable_attempt().
httpx_download_body()
int httpx_download_body (brix_io * io, char * hdr, size_t total, size_t body_off, int out_fd, int timeout_ms, long long * body_len, brix_status * st)
Definition at line 154 of file http_download.c.
References brix_status_set(), body_src::io, body_src::lo, body_src::lo_len, body_src::lo_off, raw_header(), stream_chunked(), stream_clen(), stream_eof(), body_src::timeout_ms, and XRDC_EPROTO.
Referenced by httpx_download_exchange().
httpx_download_exchange()
int httpx_download_exchange (brix_io * io, const char * host, int port, const char * path, const char * extra_headers, long long start_off, int out_fd, int timeout_ms, int * http_status, long long * body_len, brix_status * st)
Definition at line 197 of file http_download.c.
References brix_format_host_port(), brix_status_set(), brix_write_full(), host, httpx_download_body(), port, read_resp_headers(), XRDC_EPROTO, XRDC_EUSAGE, and XRDC_HDR_CAP.
Referenced by http_download_attempt().
httpx_exchange()
int httpx_exchange (brix_io * io, const char * host, int port, const char * method, const char * path, const char * extra_headers, const void * body, size_t blen, int timeout_ms, brix_http_resp * resp, brix_status * st)
Definition at line 295 of file http_req.c.
References host, httpx_build_request(), httpx_read_response(), httpx_send_request(), and port.
Referenced by brix_http_req().
httpx_parse()
void httpx_parse (char * buf, size_t total, brix_http_resp * resp)
Definition at line 257 of file http.c.
References brix_http_resp::body, brix_http_resp::body_len, ci_contains(), dechunk(), brix_http_resp::headers, brix_http_resp::reason, and brix_http_resp::status.
Referenced by httpx_read_response().
httpx_parse_upload_offset()
long long httpx_parse_upload_offset (const char * hdr, size_t len)
Definition at line 200 of file http_upload.c.
References c, and key.
Referenced by httpx_chunk_read_status().
httpx_read_some()
ssize_t httpx_read_some (brix_io * io, void * buf, size_t n, int timeout_ms, brix_status * st)
Definition at line 14 of file http_req.c.
References brix_status_set(), brix_tls_read_some(), brix_io::fd, read(), brix_io::ssl, and XRDC_ESOCK.
Referenced by bsrc_read(), httpx_read_response(), and read_resp_headers().
httpx_upload_body()
int httpx_upload_body (brix_io * io, brix_http_body_src_fn src, void * src_ctx, long long base_off, long long clen, brix_status * st)
Definition at line 71 of file http_upload.c.
References brix_status_set(), brix_write_full(), brix_status::kxr, brix_status::sys_errno, XRDC_EPROTO, XRDC_ESOCK, and XRDC_XFER_BUF.
Referenced by httpx_chunk_core(), and httpx_exchange_core().
httpx_upload_chunk()
int httpx_upload_chunk (brix_io * io, const char * host, int port, const char * path, const char * extra_headers, brix_http_body_src_fn src, void * src_ctx, long long off, long long chunk_len, long long total, int timeout_ms, int * status_out, long long * srv_off_out, brix_status * st)
Definition at line 318 of file http_upload.c.
References c, host, httpx_upload_ctx_t::host, httpx_chunk_core(), httpx_chunk_range_t::off, and port.
httpx_upload_exchange()
int httpx_upload_exchange (brix_io * io, const char * host, int port, const char * path, const char * extra_headers, brix_http_body_src_fn src, void * src_ctx, long long clen, int timeout_ms, int * http_status, brix_status * st)
Definition at line 182 of file http_upload.c.
References c, host, httpx_upload_ctx_t::host, httpx_exchange_core(), and port.
httpx_upload_response()
int httpx_upload_response (brix_io * io, int timeout_ms, int * http_status, brix_status * st)
Definition at line 103 of file http_upload.c.
References brix_status_set(), read_resp_headers(), XRDC_EPROTO, and XRDC_HDR_CAP.
Referenced by httpx_exchange_core().
httpx_window_ms()
int httpx_window_ms (void)
Definition at line 385 of file http.c.
References brix_xrdrc_default_ms(), and XRDC_DEFAULT_MAX_STALL_MS.
Referenced by brix_http_download().
raw_header()
int raw_header (const char * hdr, const char * name, char * out, size_t outsz)
Definition at line 119 of file http_download.c.
References name.
Referenced by brix_http_header(), httpx_download_body(), and httpx_read_frame_headers().
read_resp_headers()
int read_resp_headers (brix_io * io, char * hdr, size_t hdrcap, int timeout_ms, int * status, size_t * total, size_t * body_off, brix_status * st)
Definition at line 87 of file http_download.c.
References brix_status_set(), httpx_read_some(), and XRDC_EPROTO.
Referenced by httpx_chunk_read_status(), httpx_download_exchange(), and httpx_upload_response().
stream_chunked()
int stream_chunked (body_src * src, int out_fd, long long * written, brix_status * st)
Definition at line 50 of file http_download.c.
References brix_status_set(), bsrc_getline(), bsrc_read(), write_all_fd(), XRDC_EPROTO, and XRDC_XFER_BUF.
Referenced by httpx_download_body().
stream_clen()
int stream_clen (body_src * src, long long remaining, int out_fd, long long * written, brix_status * st)
Definition at line 10 of file http_download.c.
References brix_status_set(), bsrc_read(), write_all_fd(), XRDC_EPROTO, and XRDC_XFER_BUF.
Referenced by httpx_download_body().
stream_eof()
int stream_eof (body_src * src, int out_fd, long long * written, brix_status * st)
Definition at line 34 of file http_download.c.
References bsrc_read(), write_all_fd(), and XRDC_XFER_BUF.
Referenced by httpx_download_body().
write_all_fd()
int write_all_fd (int fd, const char * buf, size_t n, brix_status * st)
Definition at line 365 of file http.c.
References brix_status_set(), and XRDC_ESOCK.
Referenced by stream_chunked(), stream_clen(), and stream_eof().