nginx-xrootd: src/core/http/http_headers_set.c File Reference
http_headers_set.c File Reference
#include "http_headers.h"
#include <stdio.h>
Functions
ngx_uint_t brix_http_effective_status (ngx_http_request_t *r, ngx_int_t rc)
ngx_int_t brix_http_set_header_str (ngx_http_request_t *r, const char *key, const ngx_str_t *value, ngx_flag_t copy_value, ngx_table_elt_t **out)
ngx_int_t brix_http_set_header (ngx_http_request_t *r, const char *key, const char *value, ngx_table_elt_t **out)
ngx_int_t brix_http_set_header_num (ngx_http_request_t *r, const char *key, long value)
void brix_http_source_offer (ngx_http_request_t *r)
ngx_int_t brix_http_request_header_add (ngx_http_request_t *r, const char *key, const char *value, ngx_table_elt_t **out)
Function Documentation
brix_http_effective_status()
ngx_uint_t brix_http_effective_status (ngx_http_request_t * r, ngx_int_t rc)
Definition at line 40 of file http_headers_set.c.
Referenced by cvmfs_finalize_observe(), s3_metrics_response_method(), and webdav_metrics_response().
brix_http_request_header_add()
ngx_int_t brix_http_request_header_add (ngx_http_request_t * r, const char * key, const char * value, ngx_table_elt_t ** out)
Definition at line 174 of file http_headers_set.c.
References key.
Referenced by xrdhttp_inject_tpc_headers().
brix_http_set_header()
ngx_int_t brix_http_set_header (ngx_http_request_t * r, const char * key, const char * value, ngx_table_elt_t ** out)
Definition at line 129 of file http_headers_set.c.
References brix_http_set_header_str(), and key.
Referenced by admin_rate_gate(), brix_http_add_content_range_header(), brix_http_add_etag_header(), brix_http_set_file_headers(), cors_emit_allow_headers(), cors_emit_allow_origin(), cors_emit_methods_and_flags(), rl_reject(), s3_add_preflight_headers(), s3_handle_head(), s3_override_header(), s3_set_header(), serve_range_unsatisfiable(), tape_stage_post(), xrdhttp_add_checksum_header(), xrdhttp_add_response_headers(), and xrdhttp_set_redir_target_headers().
brix_http_set_header_num()
ngx_int_t brix_http_set_header_num (ngx_http_request_t * r, const char * key, long value)
Definition at line 145 of file http_headers_set.c.
References brix_http_set_header_str(), and key.
Referenced by xrdhttp_add_response_headers(), and xrdhttp_set_redir_target_headers().
brix_http_set_header_str()
ngx_int_t brix_http_set_header_str (ngx_http_request_t * r, const char * key, const ngx_str_t * value, ngx_flag_t copy_value, ngx_table_elt_t ** out)
Definition at line 74 of file http_headers_set.c.
References key.
Referenced by brix_http_set_header(), brix_http_set_header_num(), brix_http_source_offer(), cors_emit_allow_headers(), cors_emit_allow_origin(), cors_emit_max_age(), cors_emit_methods_and_flags(), and s3_add_preflight_headers().
brix_http_source_offer()
void brix_http_source_offer (ngx_http_request_t * r)
Definition at line 163 of file http_headers_set.c.
References brix_http_set_header_str(), and BRIX_SOURCE_URL.
Referenced by dashboard_files_gate(), ngx_http_brix_dashboard_config_download_handler(), ngx_http_brix_dashboard_main_handler(), ngx_http_brix_dashboard_scan_handler(), ngx_http_brix_health_handler(), ngx_http_brix_metrics_handler(), ngx_http_brix_srr_handler(), ngx_http_s3_handler(), vfs_browse_preamble(), and webdav_dispatch_inner().