nginx-xrootd: client/lib/protocols/http/http_req.c File Reference
http_req.c File Reference
#include "http_internal.h"
Data Structures
struct httpx_exchange_t
struct httpx_frame_t
Functions
ssize_t httpx_read_some (brix_io *io, void *buf, size_t n, int timeout_ms, brix_status *st)
int httpx_body_complete (const char *buf, size_t total, size_t body_off, long long clen, int chunked)
static int httpx_build_request (const httpx_exchange_t *ex, char *req, size_t cap, brix_status *st)
static int httpx_send_request (brix_io *io, const httpx_exchange_t *ex, const char *req, size_t rlen, brix_status *st)
static void httpx_read_frame_headers (char *buf, size_t total, httpx_frame_t *fr)
static int httpx_read_response (brix_io *io, const httpx_exchange_t *ex, brix_http_resp *resp, brix_status *st)
int httpx_exchange (brix_io *io, const char *host, int port, const char *method, const char *path, const char *extra_headers, const void *body, size_t blen, int timeout_ms, brix_http_resp *resp, brix_status *st)
int brix_http_req (const char *host, int port, int tls, const char *method, const char *path, const char *extra_headers, const void *body, size_t blen, int timeout_ms, int verify, const char *ca_dir, brix_http_resp *resp, brix_status *st)
Function Documentation
brix_http_req()
int brix_http_req (const char * host, int port, int tls, const char * method, const char * path, const char * extra_headers, const void * body, size_t blen, int timeout_ms, int verify, const char * ca_dir, brix_http_resp * resp, brix_status * st)
Definition at line 316 of file http_req.c.
References brix_http_resp_free(), brix_tls_client_free(), brix_tls_client_info(), c, close(), brix_io::fd, httpx_connect(), httpx_exchange(), brix_http_resp::tls, tls, brix_http_resp::tls_cipher, and brix_http_resp::tls_ver.
Referenced by brix_s3_list(), brix_web_readdir(), brix_web_stat(), brix_webdav_list(), brix_webdav_mkcol(), do_srr(), do_tape(), doctor_http(), doctor_s3(), http_davs_extras(), s3_delete(), s3_sigv4_probe(), s3t_request(), scan_fetch(), scan_login(), tape_poll_status(), web_move_delete(), web_read_suite(), web_write_suite(), and xrd_clockskew_http().
httpx_body_complete()
int httpx_body_complete (const char * buf, size_t total, size_t body_off, long long clen, int chunked)
Definition at line 52 of file http_req.c.
Referenced by httpx_read_response().
httpx_build_request()
static int httpx_build_request (const httpx_exchange_t * ex, char * req, size_t cap, brix_status * st) static
Definition at line 130 of file http_req.c.
References httpx_exchange_t::blen, httpx_exchange_t::body, brix_format_host_port(), brix_status_set(), httpx_exchange_t::extra_headers, httpx_exchange_t::host, httpx_exchange_t::method, httpx_exchange_t::path, httpx_exchange_t::port, and XRDC_EUSAGE.
Referenced by httpx_exchange().
httpx_exchange()
int httpx_exchange (brix_io * io, const char * host, int port, const char * method, const char * path, const char * extra_headers, const void * body, size_t blen, int timeout_ms, brix_http_resp * resp, brix_status * st)
Definition at line 295 of file http_req.c.
References httpx_build_request(), httpx_read_response(), and httpx_send_request().
Referenced by brix_http_req().
httpx_read_frame_headers()
static void httpx_read_frame_headers (char * buf, size_t total, httpx_frame_t * fr) static
Definition at line 201 of file http_req.c.
References httpx_frame_t::body_off, httpx_frame_t::chunked, ci_contains(), httpx_frame_t::clen, httpx_frame_t::have_hdrs, and raw_header().
Referenced by httpx_read_response().
httpx_read_response()
static int httpx_read_response (brix_io * io, const httpx_exchange_t * ex, brix_http_resp * resp, brix_status * st) static
Definition at line 241 of file http_req.c.
References httpx_frame_t::body_off, brix_status_set(), httpx_frame_t::chunked, httpx_frame_t::clen, httpx_frame_t::have_hdrs, httpx_body_complete(), httpx_parse(), httpx_read_frame_headers(), httpx_read_some(), httpx_exchange_t::timeout_ms, XRDC_EPROTO, and XRDC_HTTPX_MAX.
Referenced by httpx_exchange().
httpx_read_some()
ssize_t httpx_read_some (brix_io * io, void * buf, size_t n, int timeout_ms, brix_status * st)
Definition at line 14 of file http_req.c.
References brix_status_set(), brix_tls_read_some(), brix_io::fd, read(), brix_io::ssl, and XRDC_ESOCK.
Referenced by bsrc_read(), httpx_read_response(), and read_resp_headers().
httpx_send_request()
static int httpx_send_request (brix_io * io, const httpx_exchange_t * ex, const char * req, size_t rlen, brix_status * st) static
Definition at line 172 of file http_req.c.
References httpx_exchange_t::blen, httpx_exchange_t::body, and brix_write_full().
Referenced by httpx_exchange().