nginx-xrootd: src/core/http/http_query.h File Reference
http_query.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
Macros
#define BRIX_HTTP_QUERY_CASE_INSENSITIVE 0x0001u
#define BRIX_HTTP_QUERY_DECODE_VALUE 0x0002u
#define BRIX_HTTP_QUERY_PLUS_TO_SPACE 0x0004u
#define BRIX_HTTP_QUERY_REJECT_NUL 0x0008u
#define BRIX_HTTP_QUERY_ALLOW_EMPTY 0x0010u
#define BRIX_HTTP_QUERY_TRUNCATE 0x0020u
#define BRIX_HTTP_QUERY_HAS_VALUE_OK 0x0040u
Functions
int brix_http_query_get (ngx_str_t args, const char *key, char *out, size_t outsz, unsigned flags)
int brix_http_query_has (ngx_str_t args, const char *key, unsigned flags)
Macro Definition Documentation
BRIX_HTTP_QUERY_ALLOW_EMPTY
#define BRIX_HTTP_QUERY_ALLOW_EMPTY 0x0010u
Definition at line 11 of file http_query.h.
BRIX_HTTP_QUERY_CASE_INSENSITIVE
#define BRIX_HTTP_QUERY_CASE_INSENSITIVE 0x0001u
Definition at line 7 of file http_query.h.
BRIX_HTTP_QUERY_DECODE_VALUE
#define BRIX_HTTP_QUERY_DECODE_VALUE 0x0002u
Definition at line 8 of file http_query.h.
BRIX_HTTP_QUERY_HAS_VALUE_OK
#define BRIX_HTTP_QUERY_HAS_VALUE_OK 0x0040u
Definition at line 13 of file http_query.h.
BRIX_HTTP_QUERY_PLUS_TO_SPACE
#define BRIX_HTTP_QUERY_PLUS_TO_SPACE 0x0004u
Definition at line 9 of file http_query.h.
BRIX_HTTP_QUERY_REJECT_NUL
#define BRIX_HTTP_QUERY_REJECT_NUL 0x0008u
Definition at line 10 of file http_query.h.
BRIX_HTTP_QUERY_TRUNCATE
#define BRIX_HTTP_QUERY_TRUNCATE 0x0020u
Definition at line 12 of file http_query.h.
Function Documentation
brix_http_query_get()
int brix_http_query_get (ngx_str_t args, const char * key, char * out, size_t outsz, unsigned flags)
Definition at line 202 of file http_query.c.
References BRIX_HTTP_QUERY_ALLOW_EMPTY, brix_http_query_copy_value(), brix_http_query_key_eq(), and key.
Referenced by s3_apply_response_overrides(), s3_get_query_param(), s3_handle_list(), s3_handle_list_v1(), s3_is_list_request(), s3_list_parse_max_keys(), s3_override_header(), and xrdhttp_args_get().
brix_http_query_has()
int brix_http_query_has (ngx_str_t args, const char * key, unsigned flags)
Definition at line 257 of file http_query.c.
References BRIX_HTTP_QUERY_HAS_VALUE_OK, brix_http_query_key_eq(), and key.
Referenced by s3_has_query_flag(), and xrdhttp_args_has_key().