nginx-xrootd: client/lib/protocols/http/http.c File Reference
http.c File Reference
#include "http_internal.h"
Data Structures
struct http_get_ctx
Functions
static int http_get_send_request (int fd, const http_get_ctx *c, brix_status *st)
static int http_get_read_response (int fd, char *resp, size_t cap, int timeout_ms, size_t *total, brix_status *st)
static void http_get_extract (char *resp, size_t total, const http_get_ctx *c)
int brix_http_get (const char *host, int port, const char *path, int timeout_ms, int *http_status, char *out, size_t outsz, size_t *outlen, brix_status *st)
int ci_contains (const char *hay, const char *needle)
size_t dechunk (char *b, size_t len)
void brix_http_resp_free (brix_http_resp *resp)
int brix_http_header (const brix_http_resp *resp, const char *name, char *out, size_t outsz)
void httpx_parse (char *buf, size_t total, brix_http_resp *resp)
int httpx_connect (brix_io *io, const char *host, int port, int tls, int verify, const char *ca_dir, int timeout_ms, void **tls_ctx, brix_status *st)
ssize_t bsrc_read (body_src *s, void *buf, size_t n, brix_status *st)
int bsrc_getline (body_src *s, char *out, size_t outsz, brix_status *st)
int write_all_fd (int fd, const char *buf, size_t n, brix_status *st)
int httpx_window_ms (void)
Function Documentation
brix_http_get()
int brix_http_get (const char * host, int port, const char * path, int timeout_ms, int * http_status, char * out, size_t outsz, size_t * outlen, brix_status * st)
Definition at line 151 of file http.c.
References brix_status_set(), brix_tcp_connect(), c, close(), host, http_get_extract(), http_get_read_response(), http_get_send_request(), port, XRDC_EPROTO, XRDC_EUSAGE, and XRDC_HTTP_MAX.
Referenced by brix_mpxstats_main(), do_compare_davs(), do_status(), doctor_metrics(), and topo_report_cluster().
brix_http_header()
int brix_http_header (const brix_http_resp * resp, const char * name, char * out, size_t outsz)
Definition at line 249 of file http.c.
References brix_http_resp::headers, name, and raw_header().
Referenced by http_check_common_headers(), http_davs_extras(), s3t_resp_header(), scan_login(), web_read_suite(), and xrd_clockskew_http().
brix_http_resp_free()
void brix_http_resp_free (brix_http_resp * resp)
Definition at line 236 of file http.c.
References brix_http_resp::body.
Referenced by brix_http_req(), brix_s3_list(), brix_web_readdir(), brix_web_stat(), brix_webdav_list(), brix_webdav_mkcol(), cmd_scan(), do_srr(), do_tape(), doctor_http(), doctor_s3(), http_davs_extras(), s3_delete(), s3_sigv4_probe(), s3t_resp_free(), scan_fetch(), scan_login(), tape_poll_status(), web_move_delete(), web_read_suite(), web_write_suite(), and xrd_clockskew_http().
bsrc_getline()
int bsrc_getline (body_src * s, char * out, size_t outsz, brix_status * st)
Definition at line 347 of file http.c.
References bsrc_read(), and s.
Referenced by stream_chunked().
bsrc_read()
ssize_t bsrc_read (body_src * s, void * buf, size_t n, brix_status * st)
Definition at line 331 of file http.c.
References httpx_read_some(), and s.
Referenced by bsrc_getline(), stream_chunked(), stream_clen(), and stream_eof().
ci_contains()
int ci_contains (const char * hay, const char * needle)
Definition at line 202 of file http.c.
Referenced by httpx_parse(), and httpx_read_frame_headers().
dechunk()
size_t dechunk (char * b, size_t len)
Definition at line 214 of file http.c.
Referenced by httpx_parse().
http_get_extract()
static void http_get_extract (char * resp, size_t total, const http_get_ctx * c) static
Definition at line 127 of file http.c.
References c.
Referenced by brix_http_get().
http_get_read_response()
static int http_get_read_response (int fd, char * resp, size_t cap, int timeout_ms, size_t * total, brix_status * st) static
Definition at line 79 of file http.c.
References brix_status_set(), read(), and XRDC_ESOCK.
Referenced by brix_http_get().
http_get_send_request()
static int http_get_send_request (int fd, const http_get_ctx * c, brix_status * st) static
Definition at line 41 of file http.c.
References brix_format_host_port(), brix_status_set(), c, XRDC_ESOCK, and XRDC_EUSAGE.
Referenced by brix_http_get().
httpx_connect()
int httpx_connect (brix_io * io, const char * host, int port, int tls, int verify, const char * ca_dir, int timeout_ms, void ** tls_ctx, brix_status * st)
Definition at line 303 of file http.c.
References brix_tcp_connect(), brix_tls_client(), close(), brix_io::fd, host, port, brix_io::timeout_ms, and tls.
Referenced by brix_http_req(), brix_http_upload(), http_download_attempt(), and httpx_resumable_attempt().
httpx_parse()
void httpx_parse (char * buf, size_t total, brix_http_resp * resp)
Definition at line 257 of file http.c.
References brix_http_resp::body, brix_http_resp::body_len, ci_contains(), dechunk(), brix_http_resp::headers, brix_http_resp::reason, and brix_http_resp::status.
Referenced by httpx_read_response().
httpx_window_ms()
int httpx_window_ms (void)
Definition at line 385 of file http.c.
References brix_xrdrc_default_ms(), and XRDC_DEFAULT_MAX_STALL_MS.
Referenced by brix_http_download().
write_all_fd()
int write_all_fd (int fd, const char * buf, size_t n, brix_status * st)
Definition at line 365 of file http.c.
References brix_status_set(), and XRDC_ESOCK.
Referenced by stream_chunked(), stream_clen(), and stream_eof().