nginx-xrootd: client/lib/protocols/http/http_upload.c File Reference
http_upload.c File Reference
#include "http_internal.h"
Data Structures
struct httpx_upload_ctx_t
struct httpx_chunk_range_t
Functions
int httpx_upload_body (brix_io *io, brix_http_body_src_fn src, void *src_ctx, long long base_off, long long clen, brix_status *st)
int httpx_upload_response (brix_io *io, int timeout_ms, int *http_status, brix_status *st)
static int httpx_fmt_put_request (const httpx_upload_ctx_t *c, char *req, size_t cap, int *rlen_out)
static int httpx_exchange_core (const httpx_upload_ctx_t *c, brix_io *io)
int httpx_upload_exchange (brix_io *io, const char *host, int port, const char *path, const char *extra_headers, brix_http_body_src_fn src, void *src_ctx, long long clen, int timeout_ms, int *http_status, brix_status *st)
long long httpx_parse_upload_offset (const char *hdr, size_t len)
static int httpx_fmt_chunk_request (const httpx_upload_ctx_t *c, const httpx_chunk_range_t *rng, char *req, size_t cap, int *rlen_out)
static int httpx_chunk_read_status (const httpx_upload_ctx_t *c, brix_io *io, int *status_out, long long *srv_off_out)
static int httpx_chunk_core (const httpx_upload_ctx_t *c, brix_io *io, const httpx_chunk_range_t *rng)
int httpx_upload_chunk (brix_io *io, const char *host, int port, const char *path, const char *extra_headers, brix_http_body_src_fn src, void *src_ctx, long long off, long long chunk_len, long long total, int timeout_ms, int *status_out, long long *srv_off_out, brix_status *st)
static int httpx_resumable_attempt (const httpx_upload_ctx_t *c, const httpx_chunk_range_t *rng)
static int httpx_resumable_may_retry (const httpx_upload_ctx_t *c, int max_stall_ms, uint64_t deadline)
int brix_http_upload_resumable (const char *host, int port, int tls, const char *path, const char *extra_headers, brix_http_body_src_fn src, void *src_ctx, long long clen, int verify, const char *ca_dir, int timeout_ms, int max_stall_ms, int *http_status, brix_status *st)
int brix_http_upload (const char *host, int port, int tls, const char *path, const char *extra_headers, brix_http_body_src_fn src, void *src_ctx, long long clen, int verify, const char *ca_dir, int timeout_ms, int *http_status, brix_status *st)
Function Documentation
brix_http_upload()
int brix_http_upload (const char * host, int port, int tls, const char * path, const char * extra_headers, brix_http_body_src_fn src, void * src_ctx, long long clen, int verify, const char * ca_dir, int timeout_ms, int * http_status, brix_status * st)
Definition at line 449 of file http_upload.c.
References brix_tls_client_free(), c, close(), brix_io::fd, httpx_upload_ctx_t::host, httpx_connect(), httpx_exchange_core(), and tls.
Referenced by s3_put(), and web_put_get_verify().
brix_http_upload_resumable()
int brix_http_upload_resumable (const char * host, int port, int tls, const char * path, const char * extra_headers, brix_http_body_src_fn src, void * src_ctx, long long clen, int verify, const char * ca_dir, int timeout_ms, int max_stall_ms, int * http_status, brix_status * st)
Definition at line 388 of file http_upload.c.
References brix_backoff_sleep_fast(), brix_mono_ns(), brix_status_set(), c, httpx_upload_ctx_t::host, httpx_resumable_attempt(), httpx_resumable_may_retry(), httpx_chunk_range_t::off, tls, and XRDC_EPROTO.
Referenced by copy_web_upload().
httpx_chunk_core()
static int httpx_chunk_core (const httpx_upload_ctx_t * c, brix_io * io, const httpx_chunk_range_t * rng) static
Definition at line 296 of file http_upload.c.
References brix_write_full(), c, httpx_chunk_read_status(), httpx_fmt_chunk_request(), httpx_upload_body(), httpx_chunk_range_t::len, httpx_chunk_range_t::off, httpx_chunk_range_t::srv_off_out, and httpx_chunk_range_t::status_out.
Referenced by httpx_resumable_attempt(), and httpx_upload_chunk().
httpx_chunk_read_status()
static int httpx_chunk_read_status (const httpx_upload_ctx_t * c, brix_io * io, int * status_out, long long * srv_off_out) static
Definition at line 266 of file http_upload.c.
References brix_status_set(), c, httpx_parse_upload_offset(), read_resp_headers(), brix_io::timeout_ms, XRDC_EPROTO, and XRDC_HDR_CAP.
Referenced by httpx_chunk_core().
httpx_exchange_core()
static int httpx_exchange_core (const httpx_upload_ctx_t * c, brix_io * io) static
Definition at line 164 of file http_upload.c.
References brix_write_full(), c, httpx_fmt_put_request(), httpx_upload_body(), httpx_upload_response(), and brix_io::timeout_ms.
Referenced by brix_http_upload(), and httpx_upload_exchange().
httpx_fmt_chunk_request()
static int httpx_fmt_chunk_request (const httpx_upload_ctx_t * c, const httpx_chunk_range_t * rng, char * req, size_t cap, int * rlen_out) static
Definition at line 235 of file http_upload.c.
References brix_format_host_port(), brix_status_set(), c, httpx_chunk_range_t::len, httpx_chunk_range_t::off, httpx_chunk_range_t::total, and XRDC_EUSAGE.
Referenced by httpx_chunk_core().
httpx_fmt_put_request()
static int httpx_fmt_put_request (const httpx_upload_ctx_t * c, char * req, size_t cap, int * rlen_out) static
Definition at line 137 of file http_upload.c.
References brix_format_host_port(), brix_status_set(), c, and XRDC_EUSAGE.
Referenced by httpx_exchange_core().
httpx_parse_upload_offset()
long long httpx_parse_upload_offset (const char * hdr, size_t len)
Definition at line 200 of file http_upload.c.
References c, and key.
Referenced by httpx_chunk_read_status().
httpx_resumable_attempt()
static int httpx_resumable_attempt (const httpx_upload_ctx_t * c, const httpx_chunk_range_t * rng) static
Definition at line 345 of file http_upload.c.
References brix_tls_client_free(), c, close(), brix_io::fd, httpx_chunk_core(), httpx_connect(), and brix_io::timeout_ms.
Referenced by brix_http_upload_resumable().
httpx_resumable_may_retry()
static int httpx_resumable_may_retry (const httpx_upload_ctx_t * c, int max_stall_ms, uint64_t deadline) static
Definition at line 370 of file http_upload.c.
References brix_mono_ns(), brix_status_retryable(), and c.
Referenced by brix_http_upload_resumable().
httpx_upload_body()
int httpx_upload_body (brix_io * io, brix_http_body_src_fn src, void * src_ctx, long long base_off, long long clen, brix_status * st)
Definition at line 71 of file http_upload.c.
References brix_status_set(), brix_write_full(), brix_status::kxr, brix_status::sys_errno, XRDC_EPROTO, XRDC_ESOCK, and XRDC_XFER_BUF.
Referenced by httpx_chunk_core(), and httpx_exchange_core().
httpx_upload_chunk()
int httpx_upload_chunk (brix_io * io, const char * host, int port, const char * path, const char * extra_headers, brix_http_body_src_fn src, void * src_ctx, long long off, long long chunk_len, long long total, int timeout_ms, int * status_out, long long * srv_off_out, brix_status * st)
Definition at line 318 of file http_upload.c.
References c, httpx_upload_ctx_t::host, httpx_chunk_core(), and httpx_chunk_range_t::off.
httpx_upload_exchange()
int httpx_upload_exchange (brix_io * io, const char * host, int port, const char * path, const char * extra_headers, brix_http_body_src_fn src, void * src_ctx, long long clen, int timeout_ms, int * http_status, brix_status * st)
Definition at line 182 of file http_upload.c.
References c, httpx_upload_ctx_t::host, and httpx_exchange_core().
httpx_upload_response()
int httpx_upload_response (brix_io * io, int timeout_ms, int * http_status, brix_status * st)
Definition at line 103 of file http_upload.c.
References brix_status_set(), read_resp_headers(), XRDC_EPROTO, and XRDC_HDR_CAP.
Referenced by httpx_exchange_core().