nginx-xrootd: src/protocols/shared/http_cache_fill.c File Reference
http_cache_fill.c File Reference
#include "http_cache_fill.h"
#include "fs/backend/cache/sd_cache.h"
#include "fs/backend/http/sd_http.h"
#include "fs/cache/fill_retry.h"
#include "core/aio/aio.h"
#include "fs/path/path.h"
#include <limits.h>
#include <stdatomic.h>
#include <stdlib.h>
#include <sys/socket.h>
Functions
ngx_int_t brix_http_cache_fill_if_needed (ngx_http_request_t *r, brix_sd_instance_t *inst, const char *key, ngx_http_brix_shared_conf_t *common, brix_http_cache_reenter_pt reenter, void *reenter_data)
Function Documentation
brix_http_cache_fill_if_needed()
ngx_int_t brix_http_cache_fill_if_needed (ngx_http_request_t * r, brix_sd_instance_t * inst, const char * key, ngx_http_brix_shared_conf_t * common, brix_http_cache_reenter_pt reenter, void * reenter_data)
Definition at line 618 of file http_cache_fill.c.
References key.
Referenced by cvmfs_tier_get(), s3_handle_get(), and webdav_handle_get().