nginx-xrootd: src/core/http/http_file_response.h File Reference
http_file_response.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include <sys/types.h>
#include <time.h>
#include "http_headers.h"
Functions
ngx_int_t brix_http_set_header (ngx_http_request_t *r, const char *key, const char *value, ngx_table_elt_t **out)
ngx_int_t brix_http_add_etag_header (ngx_http_request_t *r, time_t mtime, off_t size, unsigned etag_flags, ngx_flag_t register_not_modified)
ngx_int_t brix_http_add_content_range_header (ngx_http_request_t *r, off_t start, off_t end, off_t size)
ngx_int_t brix_http_send_file_range (ngx_http_request_t *r, ngx_fd_t fd, const char *path, off_t start, off_t len, ngx_flag_t close_fd)
ngx_int_t brix_http_chain_append_file_range (ngx_http_request_t *r, ngx_chain_t **tail, ngx_fd_t fd, const char *path, off_t start, off_t end, ngx_flag_t close_fd)
ngx_int_t brix_http_set_file_headers (ngx_http_request_t *r, time_t mtime, off_t total_size, off_t send_len, const char *content_type, unsigned etag_flags, int has_range, off_t range_start, off_t range_end)
Function Documentation
brix_http_add_content_range_header()
ngx_int_t brix_http_add_content_range_header (ngx_http_request_t * r, off_t start, off_t end, off_t size)
Definition at line 135 of file http_file_response.c.
References brix_http_set_header().
Referenced by brix_http_set_file_headers().
brix_http_add_etag_header()
ngx_int_t brix_http_add_etag_header (ngx_http_request_t * r, time_t mtime, off_t size, unsigned etag_flags, ngx_flag_t register_not_modified)
Definition at line 100 of file http_file_response.c.
References brix_http_etag_str(), and brix_http_set_header().
Referenced by brix_http_set_file_headers(), cvmfs_tier_open_respond(), and webdav_handle_head().
brix_http_chain_append_file_range()
ngx_int_t brix_http_chain_append_file_range (ngx_http_request_t * r, ngx_chain_t ** tail, ngx_fd_t fd, const char * path, off_t start, off_t end, ngx_flag_t close_fd)
Definition at line 27 of file http_file_response.c.
References BRIX_PCALLOC_OR_RETURN, ngx_pcalloc(), and ngx_pnalloc().
Referenced by mp_append_part().
brix_http_send_file_range()
ngx_int_t brix_http_send_file_range (ngx_http_request_t * r, ngx_fd_t fd, const char * path, off_t start, off_t len, ngx_flag_t close_fd)
Definition at line 345 of file http_file_response.c.
References brix_http_prepare_file_send().
Referenced by dashboard_download_body(), and serve_send_sendfile().
brix_http_set_file_headers()
ngx_int_t brix_http_set_file_headers (ngx_http_request_t * r, time_t mtime, off_t total_size, off_t send_len, const char * content_type, unsigned etag_flags, int has_range, off_t range_start, off_t range_end)
Definition at line 151 of file http_file_response.c.
References brix_http_add_content_range_header(), brix_http_add_etag_header(), and brix_http_set_header().
Referenced by brix_http_serve_file_ranged(), compress_set_headers(), and s3_handle_head().
brix_http_set_header()
ngx_int_t brix_http_set_header (ngx_http_request_t * r, const char * key, const char * value, ngx_table_elt_t ** out)
Definition at line 129 of file http_headers_set.c.
References brix_http_set_header_str(), and key.
Referenced by admin_rate_gate(), brix_http_add_content_range_header(), brix_http_add_etag_header(), brix_http_set_file_headers(), cors_emit_allow_headers(), cors_emit_allow_origin(), cors_emit_methods_and_flags(), rl_reject(), s3_add_preflight_headers(), s3_handle_head(), s3_override_header(), s3_set_header(), serve_range_unsatisfiable(), tape_stage_post(), xrdhttp_add_checksum_header(), xrdhttp_add_response_headers(), and xrdhttp_set_redir_target_headers().