nginx-xrootd: src/core/http/http_body.h File Reference
http_body.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include "core/compat/codec_core.h"
Data Structures
struct brix_http_body_summary_t
Macros
#define BRIX_DECODE_MAX_RATIO 1000
#define BRIX_DECODE_LZ4_MAX_RATIO 200
#define BRIX_DECODE_MAX_OUTPUT (16ULL * 1024 * 1024 * 1024)
Functions
ngx_int_t brix_http_body_summary (ngx_http_request_t *r, brix_http_body_summary_t *out)
ngx_int_t brix_http_body_write_buf (ngx_http_request_t *r, ngx_fd_t dst_fd, ngx_buf_t *buf, off_t *dst_off, const char *log_path)
ngx_int_t brix_http_body_write_to_fd (ngx_http_request_t *r, ngx_fd_t dst_fd, const char *log_path, brix_http_body_summary_t *summary_out)
ngx_int_t brix_http_body_write_to_fd_at (ngx_http_request_t *r, ngx_fd_t dst_fd, const char *log_path, brix_http_body_summary_t *summary_out, off_t base_off)
ngx_int_t brix_http_body_write_to_staged (ngx_http_request_t *r, struct brix_vfs_staged_s *st)
ngx_int_t brix_http_body_read_all (ngx_http_request_t *r, size_t max_bytes, u_char **out, size_t *out_len)
ngx_int_t brix_http_read_body (ngx_http_request_t *r, ngx_http_client_body_handler_pt handler)
ngx_int_t brix_http_body_inflate_to_fd (ngx_http_request_t *r, ngx_fd_t dst_fd, const char *log_path, int window_bits, brix_http_body_summary_t *summary_out)
ngx_int_t brix_http_body_decode_to_fd (ngx_http_request_t *r, ngx_fd_t dst_fd, const char *log_path, brix_codec_id_t codec, uint64_t max_output, brix_http_body_summary_t *summary_out, ngx_int_t *http_status_out)
Macro Definition Documentation
BRIX_DECODE_LZ4_MAX_RATIO
#define BRIX_DECODE_LZ4_MAX_RATIO 200
Definition at line 19 of file http_body.h.
BRIX_DECODE_MAX_OUTPUT
#define BRIX_DECODE_MAX_OUTPUT (16ULL * 1024 * 1024 * 1024)
Definition at line 29 of file http_body.h.
BRIX_DECODE_MAX_RATIO
#define BRIX_DECODE_MAX_RATIO 1000
Definition at line 13 of file http_body.h.
Function Documentation
brix_http_body_decode_to_fd()
ngx_int_t brix_http_body_decode_to_fd (ngx_http_request_t * r, ngx_fd_t dst_fd, const char * log_path, brix_codec_id_t codec, uint64_t max_output, brix_http_body_summary_t * summary_out, ngx_int_t * http_status_out)
Definition at line 314 of file http_body_decode.c.
References brix_codec_close(), BRIX_CODEC_OK, brix_http_body_summary(), codec_ctx_setup(), codec_decode_bufs(), codec_decode_http_status(), codec_ctx_t::dst_fd, brix_http_body_summary_t::has_spooled, codec_ctx_t::inbuf, codec_ctx_t::log, codec_ctx_t::log_path, codec_ctx_t::outbuf, codec_ctx_t::s, and codec_ctx_t::worst_rc.
Referenced by brix_http_body_inflate_to_fd(), s3put_stream_sync(), and webdav_put_write_sync().
brix_http_body_inflate_to_fd()
ngx_int_t brix_http_body_inflate_to_fd (ngx_http_request_t * r, ngx_fd_t dst_fd, const char * log_path, int window_bits, brix_http_body_summary_t * summary_out)
Definition at line 368 of file http_body_decode.c.
References BRIX_CODEC_DEFLATE, BRIX_CODEC_GZIP, and brix_http_body_decode_to_fd().
brix_http_body_read_all()
ngx_int_t brix_http_body_read_all (ngx_http_request_t * r, size_t max_bytes, u_char ** out, size_t * out_len)
Definition at line 365 of file http_body.c.
References brix_http_body_summary(), BRIX_PNALLOC_OR_RETURN, brix_vfs_pread_full(), brix_http_body_summary_t::bytes, and ngx_memcpy.
Referenced by mac_gate_and_read_body(), propfind_assemble_body(), s3_delete_parse_body(), s3_post_object_body_handler_inner(), s3_put_object_tagging_body_handler(), tape_parse_body(), webdav_delegation_handle(), webdav_delegation_put_handle(), webdav_proppatch_parse_body(), and webdav_search_parse().
brix_http_body_summary()
ngx_int_t brix_http_body_summary (ngx_http_request_t * r, brix_http_body_summary_t * out)
Definition at line 75 of file http_body.c.
References brix_http_body_summary_t::bytes, brix_http_body_summary_t::has_memory, and brix_http_body_summary_t::has_spooled.
Referenced by brix_http_body_decode_to_fd(), brix_http_body_read_all(), brix_http_body_write_to_fd(), brix_http_body_write_to_fd_at(), s3put_stream_body(), and webdav_put_stream_body().
brix_http_body_write_buf()
ngx_int_t brix_http_body_write_buf (ngx_http_request_t * r, ngx_fd_t dst_fd, ngx_buf_t * buf, off_t * dst_off, const char * log_path)
Definition at line 128 of file http_body.c.
References brix_copy_range(), and brix_http_body_pwrite_full().
Referenced by brix_http_body_write_to_fd(), brix_http_body_write_to_fd_at(), and webdav_copy_spooled_file().
brix_http_body_write_to_fd()
ngx_int_t brix_http_body_write_to_fd (ngx_http_request_t * r, ngx_fd_t dst_fd, const char * log_path, brix_http_body_summary_t * summary_out)
Definition at line 183 of file http_body.c.
References brix_http_body_summary(), and brix_http_body_write_buf().
Referenced by s3_put_aio_thread(), s3put_stream_sync(), webdav_put_aio_thread(), and webdav_put_write_sync().
brix_http_body_write_to_fd_at()
ngx_int_t brix_http_body_write_to_fd_at (ngx_http_request_t * r, ngx_fd_t dst_fd, const char * log_path, brix_http_body_summary_t * summary_out, off_t base_off)
Definition at line 220 of file http_body.c.
References brix_http_body_summary(), and brix_http_body_write_buf().
Referenced by webdav_put_ranged_resume().
brix_http_body_write_to_staged()
ngx_int_t brix_http_body_write_to_staged (ngx_http_request_t * r, struct brix_vfs_staged_s * st)
brix_http_read_body()
ngx_int_t brix_http_read_body (ngx_http_request_t * r, ngx_http_client_body_handler_pt handler)
Definition at line 443 of file http_body.c.
References handler.
Referenced by s3_read_body_metric(), webdav_dispatch_delegation_gridsite(), webdav_dispatch_delegation_upload(), webdav_dispatch_lock(), webdav_dispatch_macaroon(), webdav_dispatch_put(), webdav_handle_propfind(), webdav_handle_proppatch(), webdav_handle_search(), webdav_proxy_handler(), and webdav_tape_handle().