nginx-xrootd: src/core/http/http_body.c File Reference
http_body.c File Reference
#include "http_body.h"
#include "core/compat/copy_range.h"
#include "core/compat/codec_core.h"
#include "fs/vfs/vfs.h"
#include <errno.h>
#include <unistd.h>
#include "core/compat/alloc_guard.h"
Macros
#define BRIX_INFLATE_OUT_BUFSZ (64 * 1024)
#define BRIX_INFLATE_IN_BUFSZ (64 * 1024)
Functions
static ngx_int_t brix_http_body_pwrite_full (ngx_log_t *log, ngx_fd_t fd, const u_char *data, size_t len, off_t *off, const char *path)
ngx_int_t brix_http_body_summary (ngx_http_request_t *r, brix_http_body_summary_t *out)
ngx_int_t brix_http_body_write_buf (ngx_http_request_t *r, ngx_fd_t dst_fd, ngx_buf_t *buf, off_t *dst_off, const char *log_path)
ngx_int_t brix_http_body_write_to_fd (ngx_http_request_t *r, ngx_fd_t dst_fd, const char *log_path, brix_http_body_summary_t *summary_out)
ngx_int_t brix_http_body_write_to_fd_at (ngx_http_request_t *r, ngx_fd_t dst_fd, const char *log_path, brix_http_body_summary_t *summary_out, off_t base_off)
ngx_int_t brix_http_body_write_to_staged (ngx_http_request_t *r, brix_vfs_staged_t *st)
ngx_int_t brix_http_body_read_all (ngx_http_request_t *r, size_t max_bytes, u_char **out, size_t *out_len)
ngx_int_t brix_http_read_body (ngx_http_request_t *r, ngx_http_client_body_handler_pt handler)
static ngx_int_t codec_feed (brix_codec_stream_t *s, ngx_log_t *log, ngx_fd_t dst_fd, const char *log_path, off_t *dst_off, u_char *outbuf, const u_char *in, size_t in_len, int finish, int *ended, brix_codec_rc_t *worst_rc)
static ngx_int_t codec_decode_bufs (brix_codec_stream_t *s, ngx_http_request_t *r, ngx_fd_t dst_fd, const char *log_path, u_char *outbuf, u_char *inbuf, ngx_log_t *log, brix_codec_rc_t *worst_rc)
static uint32_t brix_http_body_decode_ratio (brix_codec_id_t codec)
ngx_int_t brix_http_body_decode_to_fd (ngx_http_request_t *r, ngx_fd_t dst_fd, const char *log_path, brix_codec_id_t codec, uint64_t max_output, brix_http_body_summary_t *summary_out, ngx_int_t *http_status_out)
ngx_int_t brix_http_body_inflate_to_fd (ngx_http_request_t *r, ngx_fd_t dst_fd, const char *log_path, int window_bits, brix_http_body_summary_t *summary_out)
Macro Definition Documentation
BRIX_INFLATE_IN_BUFSZ
#define BRIX_INFLATE_IN_BUFSZ (64 * 1024)
Definition at line 28 of file http_body.c.
BRIX_INFLATE_OUT_BUFSZ
#define BRIX_INFLATE_OUT_BUFSZ (64 * 1024)
Definition at line 27 of file http_body.c.
Function Documentation
brix_http_body_decode_ratio()
static uint32_t brix_http_body_decode_ratio (brix_codec_id_t codec) static
Definition at line 573 of file http_body.c.
References BRIX_CODEC_LZ4, BRIX_DECODE_LZ4_MAX_RATIO, and BRIX_DECODE_MAX_RATIO.
Referenced by brix_http_body_decode_to_fd().
brix_http_body_decode_to_fd()
ngx_int_t brix_http_body_decode_to_fd (ngx_http_request_t * r, ngx_fd_t dst_fd, const char * log_path, brix_codec_id_t codec, uint64_t max_output, brix_http_body_summary_t * summary_out, ngx_int_t * http_status_out)
Definition at line 593 of file http_body.c.
References brix_codec_close(), BRIX_CODEC_DIR_DECOMPRESS, BRIX_CODEC_ERR_BOMB, BRIX_CODEC_ERR_DATA, BRIX_CODEC_OK, brix_codec_open(), brix_http_body_decode_ratio(), brix_http_body_summary(), BRIX_INFLATE_IN_BUFSZ, BRIX_INFLATE_OUT_BUFSZ, codec_decode_bufs(), brix_http_body_summary_t::has_spooled, log, brix_codec_guard_t::max_ratio, brix_codec_guard_t::out_cap, and s.
Referenced by brix_http_body_inflate_to_fd(), s3_put_body_inner(), and webdav_put_body_inner().
brix_http_body_inflate_to_fd()
ngx_int_t brix_http_body_inflate_to_fd (ngx_http_request_t * r, ngx_fd_t dst_fd, const char * log_path, int window_bits, brix_http_body_summary_t * summary_out)
Definition at line 679 of file http_body.c.
References BRIX_CODEC_DEFLATE, BRIX_CODEC_GZIP, and brix_http_body_decode_to_fd().
brix_http_body_pwrite_full()
static ngx_int_t brix_http_body_pwrite_full (ngx_log_t * log, ngx_fd_t fd, const u_char * data, size_t len, off_t * off, const char * path) static
Definition at line 46 of file http_body.c.
References brix_vfs_pwrite_full(), and log.
Referenced by brix_http_body_write_buf(), and codec_feed().
brix_http_body_read_all()
ngx_int_t brix_http_body_read_all (ngx_http_request_t * r, size_t max_bytes, u_char ** out, size_t * out_len)
Definition at line 341 of file http_body.c.
References brix_http_body_summary(), BRIX_PNALLOC_OR_RETURN, brix_vfs_pread_full(), and brix_http_body_summary_t::bytes.
Referenced by propfind_assemble_body(), s3_delete_objects_body_handler_inner(), s3_post_object_body_handler_inner(), s3_put_object_tagging_body_handler(), tape_parse_body(), webdav_handle_macaroon_request(), webdav_handle_macaroon_token(), webdav_proppatch_do(), and webdav_search_parse().
brix_http_body_summary()
ngx_int_t brix_http_body_summary (ngx_http_request_t * r, brix_http_body_summary_t * out)
Definition at line 75 of file http_body.c.
References brix_http_body_summary_t::bytes, brix_http_body_summary_t::has_memory, and brix_http_body_summary_t::has_spooled.
Referenced by brix_http_body_decode_to_fd(), brix_http_body_read_all(), brix_http_body_write_to_fd(), brix_http_body_write_to_fd_at(), s3_put_body_inner(), and webdav_put_body_inner().
brix_http_body_write_buf()
ngx_int_t brix_http_body_write_buf (ngx_http_request_t * r, ngx_fd_t dst_fd, ngx_buf_t * buf, off_t * dst_off, const char * log_path)
Definition at line 128 of file http_body.c.
References brix_copy_range(), and brix_http_body_pwrite_full().
Referenced by brix_http_body_write_to_fd(), brix_http_body_write_to_fd_at(), and webdav_copy_spooled_file().
brix_http_body_write_to_fd()
ngx_int_t brix_http_body_write_to_fd (ngx_http_request_t * r, ngx_fd_t dst_fd, const char * log_path, brix_http_body_summary_t * summary_out)
Definition at line 183 of file http_body.c.
References brix_http_body_summary(), and brix_http_body_write_buf().
Referenced by s3_put_aio_thread(), s3_put_body_inner(), webdav_put_aio_thread(), and webdav_put_body_inner().
brix_http_body_write_to_fd_at()
ngx_int_t brix_http_body_write_to_fd_at (ngx_http_request_t * r, ngx_fd_t dst_fd, const char * log_path, brix_http_body_summary_t * summary_out, off_t base_off)
Definition at line 220 of file http_body.c.
References brix_http_body_summary(), and brix_http_body_write_buf().
Referenced by webdav_put_ranged_resume().
brix_http_body_write_to_staged()
ngx_int_t brix_http_body_write_to_staged (ngx_http_request_t * r, brix_vfs_staged_t * st)
Definition at line 256 of file http_body.c.
References brix_vfs_staged_write(), and pread().
Referenced by s3_put_aio_thread(), webdav_put_aio_thread(), and webdav_put_body_inner().
brix_http_read_body()
ngx_int_t brix_http_read_body (ngx_http_request_t * r, ngx_http_client_body_handler_pt handler)
Definition at line 419 of file http_body.c.
Referenced by s3_dispatch_after_auth(), webdav_dispatch_inner(), webdav_handle_propfind(), webdav_handle_proppatch(), webdav_handle_search(), webdav_proxy_handler(), and webdav_tape_handle().
codec_decode_bufs()
static ngx_int_t codec_decode_bufs (brix_codec_stream_t * s, ngx_http_request_t * r, ngx_fd_t dst_fd, const char * log_path, u_char * outbuf, u_char * inbuf, ngx_log_t * log, brix_codec_rc_t * worst_rc) static
Definition at line 489 of file http_body.c.
References BRIX_CODEC_ERR_DATA, BRIX_INFLATE_IN_BUFSZ, brix_vfs_pread_full(), codec_feed(), log, and s.
Referenced by brix_http_body_decode_to_fd().
codec_feed()
static ngx_int_t codec_feed (brix_codec_stream_t * s, ngx_log_t * log, ngx_fd_t dst_fd, const char * log_path, off_t * dst_off, u_char * outbuf, const u_char * in, size_t in_len, int finish, int * ended, brix_codec_rc_t * worst_rc) static
Definition at line 436 of file http_body.c.
References BRIX_CODEC_END, brix_codec_step(), brix_http_body_pwrite_full(), BRIX_INFLATE_OUT_BUFSZ, log, and s.
Referenced by codec_decode_bufs().