nginx-xrootd: src/core/http/http_body_decode.c File Reference
http_body_decode.c File Reference
#include "http_body.h"
#include "http_body_internal.h"
#include "core/compat/codec_core.h"
#include "fs/vfs/vfs.h"
#include <errno.h>
Data Structures
struct codec_ctx_t
Macros
#define BRIX_INFLATE_OUT_BUFSZ (64 * 1024)
#define BRIX_INFLATE_IN_BUFSZ (64 * 1024)
Functions
static ngx_int_t codec_feed (codec_ctx_t *cx, const u_char *in, size_t in_len, int finish, int *ended)
static ngx_int_t codec_decode_spooled_buf (codec_ctx_t *cx, ngx_buf_t *b, int *ended)
static ngx_int_t codec_decode_bufs (codec_ctx_t *cx, ngx_http_request_t *r)
static uint32_t brix_http_body_decode_ratio (brix_codec_id_t codec)
static ngx_int_t codec_ctx_setup (codec_ctx_t *cx, brix_codec_id_t codec, uint64_t max_output, int need_inbuf, ngx_int_t *http_status_out)
static ngx_int_t codec_decode_http_status (brix_codec_rc_t worst_rc)
ngx_int_t brix_http_body_decode_to_fd (ngx_http_request_t *r, ngx_fd_t dst_fd, const char *log_path, brix_codec_id_t codec, uint64_t max_output, brix_http_body_summary_t *summary_out, ngx_int_t *http_status_out)
ngx_int_t brix_http_body_inflate_to_fd (ngx_http_request_t *r, ngx_fd_t dst_fd, const char *log_path, int window_bits, brix_http_body_summary_t *summary_out)
Macro Definition Documentation
BRIX_INFLATE_IN_BUFSZ
#define BRIX_INFLATE_IN_BUFSZ (64 * 1024)
Definition at line 33 of file http_body_decode.c.
BRIX_INFLATE_OUT_BUFSZ
#define BRIX_INFLATE_OUT_BUFSZ (64 * 1024)
Definition at line 32 of file http_body_decode.c.
Function Documentation
brix_http_body_decode_ratio()
static uint32_t brix_http_body_decode_ratio (brix_codec_id_t codec) static
Definition at line 221 of file http_body_decode.c.
References BRIX_CODEC_LZ4, BRIX_DECODE_LZ4_MAX_RATIO, and BRIX_DECODE_MAX_RATIO.
Referenced by codec_ctx_setup().
brix_http_body_decode_to_fd()
ngx_int_t brix_http_body_decode_to_fd (ngx_http_request_t * r, ngx_fd_t dst_fd, const char * log_path, brix_codec_id_t codec, uint64_t max_output, brix_http_body_summary_t * summary_out, ngx_int_t * http_status_out)
Definition at line 314 of file http_body_decode.c.
References brix_codec_close(), BRIX_CODEC_OK, brix_http_body_summary(), codec_ctx_setup(), codec_decode_bufs(), codec_decode_http_status(), codec_ctx_t::dst_fd, brix_http_body_summary_t::has_spooled, codec_ctx_t::inbuf, codec_ctx_t::log, codec_ctx_t::log_path, codec_ctx_t::outbuf, codec_ctx_t::s, and codec_ctx_t::worst_rc.
Referenced by brix_http_body_inflate_to_fd(), s3put_stream_sync(), and webdav_put_write_sync().
brix_http_body_inflate_to_fd()
ngx_int_t brix_http_body_inflate_to_fd (ngx_http_request_t * r, ngx_fd_t dst_fd, const char * log_path, int window_bits, brix_http_body_summary_t * summary_out)
Definition at line 368 of file http_body_decode.c.
References BRIX_CODEC_DEFLATE, BRIX_CODEC_GZIP, and brix_http_body_decode_to_fd().
codec_ctx_setup()
static ngx_int_t codec_ctx_setup (codec_ctx_t * cx, brix_codec_id_t codec, uint64_t max_output, int need_inbuf, ngx_int_t * http_status_out) static
Definition at line 246 of file http_body_decode.c.
References brix_codec_close(), BRIX_CODEC_DIR_DECOMPRESS, brix_codec_open(), brix_http_body_decode_ratio(), BRIX_INFLATE_IN_BUFSZ, BRIX_INFLATE_OUT_BUFSZ, codec_ctx_t::inbuf, codec_ctx_t::log, codec_ctx_t::log_path, brix_codec_guard_t::max_ratio, brix_codec_guard_t::out_cap, codec_ctx_t::outbuf, and codec_ctx_t::s.
Referenced by brix_http_body_decode_to_fd().
codec_decode_bufs()
static ngx_int_t codec_decode_bufs (codec_ctx_t * cx, ngx_http_request_t * r) static
Definition at line 166 of file http_body_decode.c.
References BRIX_CODEC_ERR_DATA, codec_decode_spooled_buf(), codec_feed(), codec_ctx_t::log, codec_ctx_t::log_path, and codec_ctx_t::worst_rc.
Referenced by brix_http_body_decode_to_fd().
codec_decode_http_status()
static ngx_int_t codec_decode_http_status (brix_codec_rc_t worst_rc) static
Definition at line 290 of file http_body_decode.c.
References BRIX_CODEC_ERR_BOMB, and BRIX_CODEC_ERR_DATA.
Referenced by brix_http_body_decode_to_fd().
codec_decode_spooled_buf()
static ngx_int_t codec_decode_spooled_buf (codec_ctx_t * cx, ngx_buf_t * b, int * ended) static
Definition at line 125 of file http_body_decode.c.
References BRIX_INFLATE_IN_BUFSZ, brix_vfs_pread_full(), codec_feed(), codec_ctx_t::inbuf, codec_ctx_t::log, and codec_ctx_t::log_path.
Referenced by codec_decode_bufs().
codec_feed()
static ngx_int_t codec_feed (codec_ctx_t * cx, const u_char * in, size_t in_len, int finish, int * ended) static
Definition at line 69 of file http_body_decode.c.
References BRIX_CODEC_END, brix_codec_step(), brix_http_body_pwrite_full(), BRIX_INFLATE_OUT_BUFSZ, codec_ctx_t::dst_fd, codec_ctx_t::dst_off, codec_ctx_t::log, codec_ctx_t::log_path, op, codec_ctx_t::outbuf, codec_ctx_t::s, and codec_ctx_t::worst_rc.
Referenced by codec_decode_bufs(), and codec_decode_spooled_buf().