nginx-xrootd: src/net/mirror/http_mirror_internal.h File Reference
http_mirror_internal.h File Reference
Macros
#define MIR_HTTP_INC(field)
Functions
ngx_int_t brix_http_mirror_method_has_body (ngx_uint_t method)
ngx_int_t mirror_create_request (ngx_http_request_t *r)
ngx_int_t mirror_reinit_request (ngx_http_request_t *r)
ngx_int_t mirror_process_status_line (ngx_http_request_t *r)
void mirror_abort_request (ngx_http_request_t *r)
void mirror_finalize_request (ngx_http_request_t *r, ngx_int_t rc)
Macro Definition Documentation
MIR_HTTP_INC
#define MIR_HTTP_INC (field)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_m = brix_metrics_shared();                  \
        if (_m != NULL) { (void) ngx_atomic_fetch_add(&_m->field, 1); }      \
    } while (0)
Definition at line 30 of file http_mirror_internal.h.
Function Documentation
brix_http_mirror_method_has_body()
ngx_int_t brix_http_mirror_method_has_body (ngx_uint_t method)
Definition at line 57 of file http_mirror.c.
Referenced by brix_http_mirror_precontent_handler(), and mirror_build_subrequest().
mirror_abort_request()
void mirror_abort_request (ngx_http_request_t * r)
Definition at line 425 of file http_mirror_request.c.
Referenced by brix_http_mirror_proxy().
mirror_create_request()
ngx_int_t mirror_create_request (ngx_http_request_t * r)
Definition at line 338 of file http_mirror_request.c.
References mirror_build_subrequest(), mirror_copy_headers(), mirror_headers_len(), mirror_set_body(), and ngx_http_brix_webdav_module.
Referenced by brix_http_mirror_proxy().
mirror_finalize_request()
void mirror_finalize_request (ngx_http_request_t * r, ngx_int_t rc)
Definition at line 431 of file http_mirror_request.c.
References brix_mirror_status_class(), brix_mirror_conf_t::log_diverge, MIR_HTTP_INC, ngx_http_brix_webdav_loc_conf_t::mirror, ngx_http_brix_webdav_module, and ngx_http_brix_webdav_req_ctx_t::primary_status.
Referenced by brix_http_mirror_proxy().
mirror_process_status_line()
ngx_int_t mirror_process_status_line (ngx_http_request_t * r)
Definition at line 380 of file http_mirror_request.c.
References mirror_process_header(), ngx_http_brix_webdav_req_ctx_t::mirror_status, and ngx_http_brix_webdav_module.
Referenced by brix_http_mirror_proxy().
mirror_reinit_request()
ngx_int_t mirror_reinit_request (ngx_http_request_t * r)
Definition at line 367 of file http_mirror_request.c.
References ngx_http_brix_webdav_req_ctx_t::mirror_status, and ngx_http_brix_webdav_module.
Referenced by brix_http_mirror_proxy().