nginx-xrootd: src/core/http/http_compress.h File Reference
http_compress.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include "core/compat/codec_core.h"
Macros
#define BRIX_COMPRESS_MIN_SIZE 256
Functions
brix_codec_id_t brix_http_compress_negotiate (ngx_http_request_t *r, off_t file_size, ngx_flag_t is_range)
ngx_int_t brix_http_send_file_compressed (ngx_http_request_t *r, ngx_fd_t send_fd, const char *fs_path, off_t size, brix_codec_id_t codec, time_t mtime, unsigned etag_flags, off_t *bytes_in_out)
Macro Definition Documentation
BRIX_COMPRESS_MIN_SIZE
#define BRIX_COMPRESS_MIN_SIZE 256
Definition at line 25 of file http_compress.h.
Function Documentation
brix_http_compress_negotiate()
brix_codec_id_t brix_http_compress_negotiate (ngx_http_request_t * r, off_t file_size, ngx_flag_t is_range)
Definition at line 138 of file http_compress.c.
References accept_encoding_has(), brix_codec_desc_t::available, brix_codec_by_id(), BRIX_CODEC_IDENTITY, BRIX_COMPRESS_MIN_SIZE, brix_compress_pref, content_type_incompressible(), and brix_codec_desc_t::http_token.
Referenced by serve_try_compressed().
brix_http_send_file_compressed()
ngx_int_t brix_http_send_file_compressed (ngx_http_request_t * r, ngx_fd_t send_fd, const char * fs_path, off_t size, brix_codec_id_t codec, time_t mtime, unsigned etag_flags, off_t * bytes_in_out)
Definition at line 338 of file http_compress.c.
References brix_codec_desc_t::available, brix_codec_by_id(), brix_codec_close(), BRIX_CODEC_DIR_COMPRESS, brix_codec_open(), BRIX_COMPRESS_CHUNK, compress_send_t::bytes_in_out, compress_set_headers(), compress_stream_body(), compress_send_t::fd, compress_send_t::inbuf, compress_send_t::outbuf, compress_send_t::r, compress_send_t::size, and compress_send_t::stream.
Referenced by serve_try_compressed().