nginx-xrootd: src/core/types/identity.h File Reference
identity.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include "auth/token/token.h"
Data Structures
struct brix_identity_t
Macros
#define BRIX_AUTHN_NONE 0x00
#define BRIX_AUTHN_GSI 0x01
#define BRIX_AUTHN_TOKEN 0x02
#define BRIX_AUTHN_SSS 0x04
#define BRIX_AUTHN_S3KEY 0x08
#define BRIX_AUTHN_UNIX 0x10
#define BRIX_AUTHN_KRB5 0x20
#define BRIX_AUTHN_HOST 0x40
#define BRIX_AUTHN_PWD 0x80
Functions
brix_identity_t * brix_identity_alloc (ngx_pool_t *pool)
ngx_int_t brix_identity_set_cstr (ngx_pool_t *pool, ngx_str_t *dst, const char *src)
ngx_int_t brix_identity_set_dn (brix_identity_t *id, ngx_pool_t *pool, const char *dn, ngx_uint_t auth_method)
ngx_int_t brix_identity_set_subject (brix_identity_t *id, ngx_pool_t *pool, const char *subject, ngx_uint_t auth_method)
ngx_int_t brix_identity_set_vos_csv (brix_identity_t *id, ngx_pool_t *pool, const char *vo_csv)
ngx_int_t brix_identity_set_token_claims (brix_identity_t *id, ngx_pool_t *pool, const brix_token_claims_t *claims)
const char * brix_identity_dn_cstr (const brix_identity_t *id)
const char * brix_identity_subject_cstr (const brix_identity_t *id)
const char * brix_identity_vo_csv_cstr (const brix_identity_t *id)
const char * brix_identity_acc_vorg_cstr (const brix_identity_t *id)
const char * brix_identity_acc_role_cstr (const brix_identity_t *id)
const char * brix_identity_acc_group_cstr (const brix_identity_t *id)
ngx_int_t brix_identity_check_token_scope (const brix_identity_t *id, const char *logical_path, int need_write)
ngx_str_t brix_identity_describe (const brix_identity_t *id, ngx_pool_t *pool)
Macro Definition Documentation
BRIX_AUTHN_GSI
#define BRIX_AUTHN_GSI 0x01
Definition at line 18 of file identity.h.
BRIX_AUTHN_HOST
#define BRIX_AUTHN_HOST 0x40
Definition at line 24 of file identity.h.
BRIX_AUTHN_KRB5
#define BRIX_AUTHN_KRB5 0x20
Definition at line 23 of file identity.h.
BRIX_AUTHN_NONE
#define BRIX_AUTHN_NONE 0x00
Definition at line 17 of file identity.h.
BRIX_AUTHN_PWD
#define BRIX_AUTHN_PWD 0x80
Definition at line 25 of file identity.h.
BRIX_AUTHN_S3KEY
#define BRIX_AUTHN_S3KEY 0x08
Definition at line 21 of file identity.h.
BRIX_AUTHN_SSS
#define BRIX_AUTHN_SSS 0x04
Definition at line 20 of file identity.h.
BRIX_AUTHN_TOKEN
#define BRIX_AUTHN_TOKEN 0x02
Definition at line 19 of file identity.h.
BRIX_AUTHN_UNIX
#define BRIX_AUTHN_UNIX 0x10
Definition at line 22 of file identity.h.
Function Documentation
brix_identity_acc_group_cstr()
const char * brix_identity_acc_group_cstr (const brix_identity_t * id)
Definition at line 388 of file identity.c.
References brix_identity_t::acc_group_csv.
Referenced by brix_acc_gate_identity(), s3_acc_check(), and webdav_acc_check().
brix_identity_acc_role_cstr()
const char * brix_identity_acc_role_cstr (const brix_identity_t * id)
Definition at line 381 of file identity.c.
References brix_identity_t::acc_role_csv.
Referenced by brix_acc_gate_identity(), s3_acc_check(), and webdav_acc_check().
brix_identity_acc_vorg_cstr()
const char * brix_identity_acc_vorg_cstr (const brix_identity_t * id)
Definition at line 374 of file identity.c.
References brix_identity_t::acc_vorg_csv.
Referenced by brix_acc_gate_identity(), s3_acc_check(), and webdav_acc_check().
brix_identity_alloc()
brix_identity_t * brix_identity_alloc (ngx_pool_t * pool)
Definition at line 176 of file identity.c.
References BRIX_AUTHN_NONE, and ngx_pcalloc().
Referenced by conn_init_ctx(), ngx_http_s3_handler(), webdav_ensure_identity(), and wt_ensure_ctx().
brix_identity_check_token_scope()
ngx_int_t brix_identity_check_token_scope (const brix_identity_t * id, const char * logical_path, int need_write)
Definition at line 401 of file identity.c.
References brix_identity_t::auth_method, BRIX_AUTHN_TOKEN, brix_token_authz_strategy(), brix_token_check_read(), brix_token_check_write(), BRIX_TOKEN_OP_READ, BRIX_TOKEN_OP_WRITE, c, ngx_memcpy, op, brix_identity_t::token_issuer, brix_identity_t::token_scope_count, and brix_identity_t::token_scopes.
Referenced by brix_check_token_scope(), brix_tpc_check_scope_path(), mac_authorize(), s3_check_token_scope(), tape_authz_path(), and webdav_check_token_scope().
brix_identity_describe()
ngx_str_t brix_identity_describe (const brix_identity_t * id, ngx_pool_t * pool)
Definition at line 441 of file identity.c.
References brix_identity_t::auth_method, BRIX_AUTHN_NONE, brix_identity_dn_cstr(), brix_identity_method_name(), brix_identity_subject_cstr(), and ngx_pnalloc().
brix_identity_dn_cstr()
const char * brix_identity_dn_cstr (const brix_identity_t * id)
Definition at line 351 of file identity.c.
References brix_identity_t::dn.
Referenced by brix_acc_gate_identity(), brix_access_log_emit(), brix_check_authdb_identity(), brix_find_authdb_rule_identity(), brix_identity_describe(), brix_open_begin_pmark(), brix_prepare_owner_key(), dig_principal(), imp_principal_of(), s3_acc_check(), s3_pmark_begin_if_enabled(), s3_sess_user(), tape_stage_cancel(), tape_stage_delete(), tape_stage_enqueue_one(), tpc_pull_resolve_pmark(), tpc_sess_identity_user(), webdav_acc_check(), webdav_dispatch_pmark(), and webdav_sess_user().
brix_identity_set_cstr()
ngx_int_t brix_identity_set_cstr (ngx_pool_t * pool, ngx_str_t * dst, const char * src)
Definition at line 197 of file identity.c.
References ngx_memcpy, and ngx_pnalloc().
Referenced by brix_handle_bind(), brix_identity_set_dn(), brix_identity_set_subject(), brix_identity_set_token_claims(), and brix_identity_set_vos_csv().
brix_identity_set_dn()
ngx_int_t brix_identity_set_dn (brix_identity_t * id, ngx_pool_t * pool, const char * dn, ngx_uint_t auth_method)
Definition at line 228 of file identity.c.
References brix_identity_set_cstr(), and brix_identity_t::dn.
Referenced by brix_gsi_complete_auth(), brix_handle_bind(), brix_handle_host_auth(), brix_unix_apply_identity(), pwd_round2(), sss_reply(), and webdav_mark_req_verified().
brix_identity_set_subject()
ngx_int_t brix_identity_set_subject (brix_identity_t * id, ngx_pool_t * pool, const char * subject, ngx_uint_t auth_method)
Definition at line 249 of file identity.c.
References brix_identity_set_cstr(), and brix_identity_t::subject.
Referenced by brix_handle_bind(), brix_identity_set_token_claims(), and s3_sigv4_finish().
brix_identity_set_token_claims()
ngx_int_t brix_identity_set_token_claims (brix_identity_t * id, ngx_pool_t * pool, const brix_token_claims_t * claims)
Definition at line 297 of file identity.c.
References BRIX_AUTHN_TOKEN, brix_identity_set_cstr(), brix_identity_set_subject(), brix_identity_set_vos_csv(), brix_identity_split_spaces(), BRIX_MAX_TOKEN_SCOPES, brix_token_scope_t::create, brix_identity_t::dn, brix_token_claims_t::groups, brix_token_claims_t::iss, brix_identity_t::issuer, brix_token_scope_t::read, brix_token_claims_t::scope_count, brix_token_claims_t::scope_raw, brix_identity_t::scope_raw, brix_token_claims_t::scopes, brix_identity_t::scopes, brix_token_claims_t::sub, brix_identity_t::token_scope_count, and brix_token_scope_t::write.
Referenced by s3_verify_bearer(), tokenauth_map_identity(), and wt_check_claims().
brix_identity_set_vos_csv()
ngx_int_t brix_identity_set_vos_csv (brix_identity_t * id, ngx_pool_t * pool, const char * vo_csv)
Definition at line 271 of file identity.c.
References brix_identity_derive_attrs(), brix_identity_set_cstr(), brix_identity_split_csv(), brix_identity_t::vo_csv, and brix_identity_t::vo_list.
Referenced by brix_gsi_complete_auth(), brix_handle_bind(), brix_identity_set_token_claims(), brix_unix_apply_identity(), sss_reply(), and webdav_extract_and_set_voms_identity().
brix_identity_subject_cstr()
const char * brix_identity_subject_cstr (const brix_identity_t * id)
Definition at line 358 of file identity.c.
References brix_identity_t::subject.
Referenced by brix_access_log_emit(), brix_identity_describe(), dig_principal(), imp_principal_of(), s3_dashboard_identity(), s3_get_resolve_identity(), s3_sess_user(), tpc_sess_identity_user(), and webdav_sess_user().
brix_identity_vo_csv_cstr()
const char * brix_identity_vo_csv_cstr (const brix_identity_t * id)
Definition at line 366 of file identity.c.
References brix_identity_t::vo_csv.
Referenced by brix_check_authdb_identity(), brix_check_vo_acl_identity(), brix_find_authdb_rule_identity(), brix_open_begin_pmark(), s3_pmark_begin_if_enabled(), tpc_pull_resolve_pmark(), tpc_sess_identity_vo(), webdav_dispatch_pmark(), and webdav_sess_vo().