nginx-xrootd: src/core/types/identity.c File Reference
identity.c File Reference
#include "identity.h"
#include "auth/token/issuer_registry.h"
#include <string.h>
Functions
static ngx_int_t brix_identity_push_str (ngx_pool_t *pool, ngx_array_t **array, const char *start, size_t len)
static ngx_int_t brix_identity_split_csv (ngx_pool_t *pool, ngx_array_t **array, const char *csv)
static ngx_int_t brix_identity_split_spaces (ngx_pool_t *pool, ngx_array_t **array, const char *spaces)
static const char * brix_identity_method_name (ngx_uint_t method)
brix_identity_t * brix_identity_alloc (ngx_pool_t *pool)
ngx_int_t brix_identity_set_cstr (ngx_pool_t *pool, ngx_str_t *dst, const char *src)
ngx_int_t brix_identity_set_dn (brix_identity_t *id, ngx_pool_t *pool, const char *dn, ngx_uint_t auth_method)
ngx_int_t brix_identity_set_subject (brix_identity_t *id, ngx_pool_t *pool, const char *subject, ngx_uint_t auth_method)
static ngx_int_t brix_identity_derive_attrs (brix_identity_t *id, ngx_pool_t *pool, const char *vo_csv)
ngx_int_t brix_identity_set_vos_csv (brix_identity_t *id, ngx_pool_t *pool, const char *vo_csv)
ngx_int_t brix_identity_set_token_claims (brix_identity_t *id, ngx_pool_t *pool, const brix_token_claims_t *claims)
const char * brix_identity_dn_cstr (const brix_identity_t *id)
const char * brix_identity_subject_cstr (const brix_identity_t *id)
const char * brix_identity_vo_csv_cstr (const brix_identity_t *id)
const char * brix_identity_acc_vorg_cstr (const brix_identity_t *id)
const char * brix_identity_acc_role_cstr (const brix_identity_t *id)
const char * brix_identity_acc_group_cstr (const brix_identity_t *id)
ngx_int_t brix_identity_check_token_scope (const brix_identity_t *id, const char *logical_path, int need_write)
ngx_str_t brix_identity_describe (const brix_identity_t *id, ngx_pool_t *pool)
Function Documentation
brix_identity_acc_group_cstr()
const char * brix_identity_acc_group_cstr (const brix_identity_t * id)
Definition at line 469 of file identity.c.
References brix_identity_t::acc_group_csv.
Referenced by brix_acc_gate_engine(), s3_acc_check(), and webdav_acc_check().
brix_identity_acc_role_cstr()
const char * brix_identity_acc_role_cstr (const brix_identity_t * id)
Definition at line 462 of file identity.c.
References brix_identity_t::acc_role_csv.
Referenced by brix_acc_gate_engine(), s3_acc_check(), and webdav_acc_check().
brix_identity_acc_vorg_cstr()
const char * brix_identity_acc_vorg_cstr (const brix_identity_t * id)
Definition at line 455 of file identity.c.
References brix_identity_t::acc_vorg_csv.
Referenced by brix_acc_gate_engine(), s3_acc_check(), and webdav_acc_check().
brix_identity_alloc()
brix_identity_t * brix_identity_alloc (ngx_pool_t * pool)
Definition at line 175 of file identity.c.
References BRIX_AUTHN_NONE.
Referenced by ngx_http_s3_handler(), ngx_stream_brix_handler(), webdav_ensure_identity(), and webdav_verify_bearer_token().
brix_identity_check_token_scope()
ngx_int_t brix_identity_check_token_scope (const brix_identity_t * id, const char * logical_path, int need_write)
Definition at line 482 of file identity.c.
References brix_identity_t::auth_method, BRIX_AUTHN_TOKEN, brix_token_authz_strategy(), brix_token_check_read(), brix_token_check_write(), BRIX_TOKEN_OP_READ, BRIX_TOKEN_OP_WRITE, c, brix_identity_t::token_issuer, brix_identity_t::token_scope_count, and brix_identity_t::token_scopes.
Referenced by brix_check_token_scope(), brix_tpc_check_scope_path(), s3_dispatch_after_auth(), tape_authz_path(), and webdav_check_token_scope().
brix_identity_derive_attrs()
static ngx_int_t brix_identity_derive_attrs (brix_identity_t * id, ngx_pool_t * pool, const char * vo_csv) static
Definition at line 273 of file identity.c.
References brix_identity_t::acc_group_csv, brix_identity_t::acc_role_csv, and brix_identity_t::acc_vorg_csv.
Referenced by brix_identity_set_vos_csv().
brix_identity_describe()
ngx_str_t brix_identity_describe (const brix_identity_t * id, ngx_pool_t * pool)
Definition at line 522 of file identity.c.
References brix_identity_t::auth_method, BRIX_AUTHN_NONE, brix_identity_dn_cstr(), brix_identity_method_name(), and brix_identity_subject_cstr().
brix_identity_dn_cstr()
const char * brix_identity_dn_cstr (const brix_identity_t * id)
Definition at line 432 of file identity.c.
References brix_identity_t::dn.
Referenced by brix_acc_gate_engine(), brix_access_log_emit(), brix_check_authdb_identity(), brix_find_authdb_rule_identity(), brix_handle_open(), brix_identity_describe(), brix_prepare_owner_key(), brix_tpc_start_pull(), dig_principal(), imp_principal_of(), ngx_http_s3_handler(), s3_acc_check(), tape_stage_cancel(), tape_stage_delete(), tape_stage_post(), webdav_acc_check(), and webdav_dispatch_inner().
brix_identity_method_name()
static const char * brix_identity_method_name (ngx_uint_t method) static
Definition at line 147 of file identity.c.
References BRIX_AUTHN_GSI, BRIX_AUTHN_KRB5, BRIX_AUTHN_S3KEY, BRIX_AUTHN_SSS, BRIX_AUTHN_TOKEN, and BRIX_AUTHN_UNIX.
Referenced by brix_identity_describe().
brix_identity_push_str()
static ngx_int_t brix_identity_push_str (ngx_pool_t * pool, ngx_array_t ** array, const char * start, size_t len) static
Definition at line 40 of file identity.c.
Referenced by brix_identity_split_csv(), and brix_identity_split_spaces().
brix_identity_set_cstr()
ngx_int_t brix_identity_set_cstr (ngx_pool_t * pool, ngx_str_t * dst, const char * src)
Definition at line 196 of file identity.c.
Referenced by brix_handle_bind(), brix_identity_set_dn(), brix_identity_set_subject(), brix_identity_set_token_claims(), and brix_identity_set_vos_csv().
brix_identity_set_dn()
ngx_int_t brix_identity_set_dn (brix_identity_t * id, ngx_pool_t * pool, const char * dn, ngx_uint_t auth_method)
Definition at line 227 of file identity.c.
References brix_identity_set_cstr(), and brix_identity_t::dn.
Referenced by brix_gsi_complete_auth(), brix_handle_bind(), brix_handle_host_auth(), brix_handle_krb5_auth(), brix_handle_sss_auth(), brix_handle_unix_auth(), pwd_round2(), and webdav_mark_req_verified().
brix_identity_set_subject()
ngx_int_t brix_identity_set_subject (brix_identity_t * id, ngx_pool_t * pool, const char * subject, ngx_uint_t auth_method)
Definition at line 248 of file identity.c.
References brix_identity_set_cstr(), and brix_identity_t::subject.
Referenced by brix_handle_bind(), brix_identity_set_token_claims(), and s3_verify_sigv4().
brix_identity_set_token_claims()
ngx_int_t brix_identity_set_token_claims (brix_identity_t * id, ngx_pool_t * pool, const brix_token_claims_t * claims)
Definition at line 378 of file identity.c.
References BRIX_AUTHN_TOKEN, brix_identity_set_cstr(), brix_identity_set_subject(), brix_identity_set_vos_csv(), brix_identity_split_spaces(), BRIX_MAX_TOKEN_SCOPES, brix_token_scope_t::create, brix_identity_t::dn, brix_token_claims_t::groups, brix_token_claims_t::iss, brix_identity_t::issuer, brix_token_scope_t::read, brix_token_claims_t::scope_count, brix_token_claims_t::scope_raw, brix_identity_t::scope_raw, brix_token_claims_t::scopes, brix_identity_t::scopes, brix_token_claims_t::sub, brix_identity_t::token_scope_count, and brix_token_scope_t::write.
Referenced by brix_handle_token_auth(), s3_verify_bearer(), and webdav_verify_bearer_token().
brix_identity_set_vos_csv()
ngx_int_t brix_identity_set_vos_csv (brix_identity_t * id, ngx_pool_t * pool, const char * vo_csv)
Definition at line 352 of file identity.c.
References brix_identity_derive_attrs(), brix_identity_set_cstr(), brix_identity_split_csv(), brix_identity_t::vo_csv, and brix_identity_t::vo_list.
Referenced by brix_gsi_complete_auth(), brix_handle_bind(), brix_handle_sss_auth(), brix_handle_unix_auth(), brix_identity_set_token_claims(), and webdav_extract_and_set_voms_identity().
brix_identity_split_csv()
static ngx_int_t brix_identity_split_csv (ngx_pool_t * pool, ngx_array_t ** array, const char * csv) static
Definition at line 78 of file identity.c.
References brix_identity_push_str().
Referenced by brix_identity_set_vos_csv().
brix_identity_split_spaces()
static ngx_int_t brix_identity_split_spaces (ngx_pool_t * pool, ngx_array_t ** array, const char * spaces) static
Definition at line 112 of file identity.c.
References brix_identity_push_str().
Referenced by brix_identity_set_token_claims().
brix_identity_subject_cstr()
const char * brix_identity_subject_cstr (const brix_identity_t * id)
Definition at line 439 of file identity.c.
References brix_identity_t::subject.
Referenced by brix_access_log_emit(), brix_identity_describe(), dig_principal(), imp_principal_of(), s3_dashboard_identity(), and s3_handle_get().
brix_identity_vo_csv_cstr()
const char * brix_identity_vo_csv_cstr (const brix_identity_t * id)
Definition at line 447 of file identity.c.
References brix_identity_t::vo_csv.
Referenced by brix_check_authdb_identity(), brix_check_vo_acl_identity(), brix_find_authdb_rule_identity(), brix_handle_open(), brix_tpc_start_pull(), ngx_http_s3_handler(), and webdav_dispatch_inner().