nginx-xrootd: src/auth/impersonate/idmap_gridmap.c File Reference
idmap_gridmap.c File Reference
#include "impersonate.h"
#include "core/compat/cstr.h"
#include "idmap_internal.h"
#include <pwd.h>
#include <grp.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
Data Structures
struct idmap_gridmap_entry_t
Functions
static void idmap_gridmap_free (void)
static const char * idmap_skip_blanks (const char *p)
static int idmap_scan_quoted_dn (const char **pp, const char **start, const char **end)
static int idmap_scan_username (const char **pp, const char **start, const char **end)
static int idmap_gridmap_parse_line (const char *line, char **dn_out, char **user_out)
ngx_int_t idmap_gridmap_load (const char *path, ngx_log_t *log)
const char * idmap_gridmap_lookup (const char *dn)
Variables
static idmap_gridmap_entry_t * idmap_gridmap
static size_t idmap_gridmap_n
Function Documentation
idmap_gridmap_free()
static void idmap_gridmap_free (void) static
Definition at line 39 of file idmap_gridmap.c.
References idmap_gridmap, and idmap_gridmap_n.
Referenced by idmap_gridmap_load().
idmap_gridmap_load()
ngx_int_t idmap_gridmap_load (const char * path, ngx_log_t * log)
Definition at line 136 of file idmap_gridmap.c.
References idmap_gridmap_entry_t::dn, idmap_gridmap, idmap_gridmap_free(), idmap_gridmap_n, idmap_gridmap_parse_line(), log, and idmap_gridmap_entry_t::user.
Referenced by brix_idmap_init().
idmap_gridmap_lookup()
const char * idmap_gridmap_lookup (const char * dn)
Definition at line 200 of file idmap_gridmap.c.
References idmap_gridmap, idmap_gridmap_n, and idmap_gridmap_entry_t::user.
Referenced by idmap_resolve_uncached().
idmap_gridmap_parse_line()
static int idmap_gridmap_parse_line (const char * line, char ** dn_out, char ** user_out) static
Definition at line 111 of file idmap_gridmap.c.
References IDMAP_PRINC_MAX, idmap_scan_quoted_dn(), and idmap_scan_username().
Referenced by idmap_gridmap_load().
idmap_scan_quoted_dn()
static int idmap_scan_quoted_dn (const char ** pp, const char ** start, const char ** end) static
Definition at line 70 of file idmap_gridmap.c.
References idmap_skip_blanks().
Referenced by idmap_gridmap_parse_line().
idmap_scan_username()
static int idmap_scan_username (const char ** pp, const char ** start, const char ** end) static
Definition at line 93 of file idmap_gridmap.c.
References idmap_skip_blanks().
Referenced by idmap_gridmap_parse_line().
idmap_skip_blanks()
static const char * idmap_skip_blanks (const char * p) static
Definition at line 57 of file idmap_gridmap.c.
Referenced by idmap_scan_quoted_dn(), and idmap_scan_username().
Variable Documentation
idmap_gridmap
idmap_gridmap_entry_t* idmap_gridmap static
Definition at line 33 of file idmap_gridmap.c.
Referenced by idmap_gridmap_free(), idmap_gridmap_load(), and idmap_gridmap_lookup().
idmap_gridmap_n
size_t idmap_gridmap_n static
Definition at line 34 of file idmap_gridmap.c.
Referenced by idmap_gridmap_free(), idmap_gridmap_load(), and idmap_gridmap_lookup().