nginx-xrootd: src/auth/impersonate/idmap_denylist.c File Reference
idmap_denylist.c File Reference
#include "impersonate.h"
#include "core/compat/cstr.h"
#include "idmap_internal.h"
#include <pwd.h>
#include <grp.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
Macros
#define IDMAP_FORBID_MAX 256
Functions
static int idmap_gid_reserved_or_forbidden (gid_t gid)
int idmap_resolve_user (const char *user, brix_idmap_creds_t *out)
static void imp_priv_report (uint32_t id, char kind, uint32_t *out_id, char *out_kind)
static int imp_id_reserved (uint32_t id, uid_t floor)
int brix_imp_creds_privileged (const brix_idmap_creds_t *cr, uid_t floor, uint32_t *out_id, char *out_kind)
static void idmap_forbid_uid (uid_t uid)
static void idmap_forbid_gid (gid_t gid)
static size_t idmap_forbid_next_name (const char **pp, char *name, size_t cap)
static void idmap_forbid_resolve_name (const char *name, int is_user)
static void idmap_forbid_load (const char *list, const char *def, int is_user, ngx_log_t *log)
static int idmap_uid_forbidden (uid_t uid)
static int idmap_creds_have_forbidden_group (const brix_idmap_creds_t *cr)
int idmap_creds_allowed (const brix_idmap_creds_t *cr)
void idmap_init_denylists (const brix_idmap_conf_t *conf, ngx_log_t *log)
Variables
static uid_t idmap_forbidden_uids [256]
static int idmap_forbidden_uids_n
static gid_t idmap_forbidden_gids [256]
static int idmap_forbidden_gids_n
Macro Definition Documentation
IDMAP_FORBID_MAX
#define IDMAP_FORBID_MAX 256
Definition at line 35 of file idmap_denylist.c.
Function Documentation
brix_imp_creds_privileged()
int brix_imp_creds_privileged (const brix_idmap_creds_t * cr, uid_t floor, uint32_t * out_id, char * out_kind)
Definition at line 161 of file idmap_denylist.c.
References BRIX_IDMAP_MAXGROUPS, brix_idmap_creds_t::gid, brix_idmap_creds_t::groups, imp_id_reserved(), imp_priv_report(), brix_idmap_creds_t::ngroups, and brix_idmap_creds_t::uid.
Referenced by idmap_creds_allowed(), and imp_become().
idmap_creds_allowed()
int idmap_creds_allowed (const brix_idmap_creds_t * cr)
Definition at line 330 of file idmap_denylist.c.
References brix_imp_creds_privileged(), idmap_creds_have_forbidden_group(), idmap_min_uid, idmap_uid_forbidden(), and brix_idmap_creds_t::uid.
Referenced by idmap_resolve_uncached().
idmap_creds_have_forbidden_group()
static int idmap_creds_have_forbidden_group (const brix_idmap_creds_t * cr) static
Definition at line 306 of file idmap_denylist.c.
References brix_idmap_creds_t::gid, brix_idmap_creds_t::groups, idmap_forbidden_gids, idmap_forbidden_gids_n, and brix_idmap_creds_t::ngroups.
Referenced by idmap_creds_allowed().
idmap_forbid_gid()
static void idmap_forbid_gid (gid_t gid) static
Definition at line 210 of file idmap_denylist.c.
References IDMAP_FORBID_MAX, idmap_forbidden_gids, and idmap_forbidden_gids_n.
Referenced by idmap_forbid_resolve_name().
idmap_forbid_load()
static void idmap_forbid_load (const char * list, const char * def, int is_user, ngx_log_t * log) static
Definition at line 275 of file idmap_denylist.c.
References idmap_forbid_next_name(), idmap_forbid_resolve_name(), log, and name.
Referenced by idmap_init_denylists().
idmap_forbid_next_name()
static size_t idmap_forbid_next_name (const char ** pp, char * name, size_t cap) static
Definition at line 231 of file idmap_denylist.c.
References name.
Referenced by idmap_forbid_load().
idmap_forbid_resolve_name()
static void idmap_forbid_resolve_name (const char * name, int is_user) static
Definition at line 250 of file idmap_denylist.c.
References idmap_forbid_gid(), idmap_forbid_uid(), and name.
Referenced by idmap_forbid_load().
idmap_forbid_uid()
static void idmap_forbid_uid (uid_t uid) static
Definition at line 194 of file idmap_denylist.c.
References IDMAP_FORBID_MAX, idmap_forbidden_uids, and idmap_forbidden_uids_n.
Referenced by idmap_forbid_resolve_name(), and idmap_init_denylists().
idmap_gid_reserved_or_forbidden()
static int idmap_gid_reserved_or_forbidden (gid_t gid) static
Definition at line 45 of file idmap_denylist.c.
References idmap_forbidden_gids, idmap_forbidden_gids_n, and idmap_min_uid.
Referenced by idmap_resolve_user().
idmap_init_denylists()
void idmap_init_denylists (const brix_idmap_conf_t * conf, ngx_log_t * log)
Definition at line 345 of file idmap_denylist.c.
References BRIX_IMP_DEFAULT_FORBIDDEN_GROUPS, BRIX_IMP_DEFAULT_FORBIDDEN_USERS, brix_str_cbuf(), brix_idmap_conf_t::forbidden_groups, brix_idmap_conf_t::forbidden_users, idmap_forbid_load(), IDMAP_FORBID_MAX, idmap_forbid_uid(), idmap_forbidden_gids_n, idmap_forbidden_uids_n, log, and brix_idmap_conf_t::worker_uid.
Referenced by brix_idmap_init().
idmap_resolve_user()
int idmap_resolve_user (const char * user, brix_idmap_creds_t * out)
Definition at line 69 of file idmap_denylist.c.
References BRIX_IDMAP_MAXGROUPS, brix_idmap_creds_t::gid, brix_idmap_creds_t::groups, idmap_gid_reserved_or_forbidden(), idmap_primary_only, brix_idmap_creds_t::ngroups, and brix_idmap_creds_t::uid.
Referenced by idmap_resolve_uncached().
idmap_uid_forbidden()
static int idmap_uid_forbidden (uid_t uid) static
Definition at line 291 of file idmap_denylist.c.
References idmap_forbidden_uids, and idmap_forbidden_uids_n.
Referenced by idmap_creds_allowed().
imp_id_reserved()
static int imp_id_reserved (uint32_t id, uid_t floor) static
Definition at line 148 of file idmap_denylist.c.
Referenced by brix_imp_creds_privileged().
imp_priv_report()
static void imp_priv_report (uint32_t id, char kind, uint32_t * out_id, char * out_kind) static
Definition at line 140 of file idmap_denylist.c.
Referenced by brix_imp_creds_privileged().
Variable Documentation
idmap_forbidden_gids
gid_t idmap_forbidden_gids[256] static
Definition at line 38 of file idmap_denylist.c.
Referenced by idmap_creds_have_forbidden_group(), idmap_forbid_gid(), and idmap_gid_reserved_or_forbidden().
idmap_forbidden_gids_n
int idmap_forbidden_gids_n static
Definition at line 39 of file idmap_denylist.c.
Referenced by idmap_creds_have_forbidden_group(), idmap_forbid_gid(), idmap_gid_reserved_or_forbidden(), and idmap_init_denylists().
idmap_forbidden_uids
uid_t idmap_forbidden_uids[256] static
Definition at line 36 of file idmap_denylist.c.
Referenced by idmap_forbid_uid(), and idmap_uid_forbidden().
idmap_forbidden_uids_n
int idmap_forbidden_uids_n static
Definition at line 37 of file idmap_denylist.c.
Referenced by idmap_forbid_uid(), idmap_init_denylists(), and idmap_uid_forbidden().