nginx-xrootd: src/auth/impersonate/idmap_internal.h File Reference
idmap_internal.h File Reference
#include "impersonate.h"
Macros
#define IDMAP_PRINC_MAX 512 /* a GSI DN can be long */
Functions
ngx_int_t idmap_gridmap_load (const char *path, ngx_log_t *log)
const char * idmap_gridmap_lookup (const char *dn)
int idmap_resolve_user (const char *user, brix_idmap_creds_t *out)
int idmap_creds_allowed (const brix_idmap_creds_t *cr)
void idmap_init_denylists (const brix_idmap_conf_t *conf, ngx_log_t *log)
Variables
uid_t idmap_min_uid
int idmap_primary_only
Macro Definition Documentation
IDMAP_PRINC_MAX
#define IDMAP_PRINC_MAX 512 /* a GSI DN can be long */
Definition at line 24 of file idmap_internal.h.
Function Documentation
idmap_creds_allowed()
int idmap_creds_allowed (const brix_idmap_creds_t * cr)
Definition at line 330 of file idmap_denylist.c.
References brix_imp_creds_privileged(), idmap_creds_have_forbidden_group(), idmap_min_uid, idmap_uid_forbidden(), and brix_idmap_creds_t::uid.
Referenced by idmap_resolve_uncached().
idmap_gridmap_load()
ngx_int_t idmap_gridmap_load (const char * path, ngx_log_t * log)
Definition at line 136 of file idmap_gridmap.c.
References idmap_gridmap_entry_t::dn, idmap_gridmap, idmap_gridmap_free(), idmap_gridmap_n, idmap_gridmap_parse_line(), log, and idmap_gridmap_entry_t::user.
Referenced by brix_idmap_init().
idmap_gridmap_lookup()
const char * idmap_gridmap_lookup (const char * dn)
Definition at line 200 of file idmap_gridmap.c.
References idmap_gridmap, idmap_gridmap_n, and idmap_gridmap_entry_t::user.
Referenced by idmap_resolve_uncached().
idmap_init_denylists()
void idmap_init_denylists (const brix_idmap_conf_t * conf, ngx_log_t * log)
Definition at line 345 of file idmap_denylist.c.
References BRIX_IMP_DEFAULT_FORBIDDEN_GROUPS, BRIX_IMP_DEFAULT_FORBIDDEN_USERS, brix_str_cbuf(), brix_idmap_conf_t::forbidden_groups, brix_idmap_conf_t::forbidden_users, idmap_forbid_load(), IDMAP_FORBID_MAX, idmap_forbid_uid(), idmap_forbidden_gids_n, idmap_forbidden_uids_n, log, and brix_idmap_conf_t::worker_uid.
Referenced by brix_idmap_init().
idmap_resolve_user()
int idmap_resolve_user (const char * user, brix_idmap_creds_t * out)
Definition at line 69 of file idmap_denylist.c.
References BRIX_IDMAP_MAXGROUPS, brix_idmap_creds_t::gid, brix_idmap_creds_t::groups, idmap_gid_reserved_or_forbidden(), idmap_primary_only, brix_idmap_creds_t::ngroups, and brix_idmap_creds_t::uid.
Referenced by idmap_resolve_uncached().
Variable Documentation
idmap_min_uid
uid_t idmap_min_uid extern
Definition at line 46 of file idmap.c.
Referenced by idmap_creds_allowed(), idmap_gid_reserved_or_forbidden(), and idmap_init_policy().
idmap_primary_only
int idmap_primary_only extern
Definition at line 47 of file idmap.c.
Referenced by idmap_init_policy(), and idmap_resolve_user().