nginx-xrootd: src/auth/impersonate/idmap.c File Reference
idmap.c File Reference
#include "impersonate.h"
#include "core/compat/cstr.h"
#include "idmap_internal.h"
#include <pwd.h>
#include <grp.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
Data Structures
struct idmap_cache_slot_t
Macros
#define IDMAP_CACHE_SLOTS 256
#define IDMAP_DJB2_SEED 5381 /* djb2 hash initial basis */
Functions
static ngx_uint_t idmap_hash (const char *s)
static void idmap_init_policy (const brix_idmap_conf_t *conf, ngx_log_t *log)
ngx_int_t brix_idmap_init (const brix_idmap_conf_t *conf, ngx_log_t *log)
static int idmap_cache_get (const idmap_cache_slot_t *slot, const char *principal, time_t now, brix_idmap_creds_t *out, int *rc_out)
static int idmap_resolve_uncached (const char *principal, brix_idmap_creds_t *creds, const char **user_out)
static void idmap_cache_put (idmap_cache_slot_t *slot, const char *principal, int rc, const brix_idmap_creds_t *creds, time_t now)
ngx_int_t brix_idmap_resolve (const brix_idmap_conf_t *conf, const char *principal, brix_idmap_creds_t *out, ngx_log_t *log)
Variables
static idmap_cache_slot_t idmap_cache [256]
static time_t idmap_ttl = 600
uid_t idmap_min_uid = 1000
int idmap_primary_only
static char idmap_default_user [512]
Macro Definition Documentation
IDMAP_CACHE_SLOTS
#define IDMAP_CACHE_SLOTS 256
Definition at line 33 of file idmap.c.
IDMAP_DJB2_SEED
#define IDMAP_DJB2_SEED 5381 /* djb2 hash initial basis */
Definition at line 34 of file idmap.c.
Function Documentation
brix_idmap_init()
ngx_int_t brix_idmap_init (const brix_idmap_conf_t * conf, ngx_log_t * log)
Definition at line 97 of file idmap.c.
References brix_str_cbuf(), brix_idmap_conf_t::default_user, brix_idmap_conf_t::gridmap_path, idmap_cache, idmap_default_user, idmap_gridmap_load(), idmap_init_denylists(), idmap_init_policy(), IDMAP_PRINC_MAX, and log.
Referenced by imp_load_idmap().
brix_idmap_resolve()
ngx_int_t brix_idmap_resolve (const brix_idmap_conf_t * conf, const char * principal, brix_idmap_creds_t * out, ngx_log_t * log)
Definition at line 192 of file idmap.c.
References BRIX_IDMAP_DENY, BRIX_IDMAP_OK, BRIX_IDMAP_SQUASH, idmap_cache, idmap_cache_get(), idmap_cache_put(), idmap_hash(), IDMAP_PRINC_MAX, idmap_resolve_uncached(), and log.
Referenced by imp_serve_one().
idmap_cache_get()
static int idmap_cache_get (const idmap_cache_slot_t * slot, const char * principal, time_t now, brix_idmap_creds_t * out, int * rc_out) static
Definition at line 132 of file idmap.c.
References BRIX_IDMAP_OK, BRIX_IDMAP_SQUASH, idmap_cache_slot_t::creds, idmap_cache_slot_t::expiry, idmap_cache_slot_t::principal, and idmap_cache_slot_t::rc.
Referenced by brix_idmap_resolve().
idmap_cache_put()
static void idmap_cache_put (idmap_cache_slot_t * slot, const char * principal, int rc, const brix_idmap_creds_t * creds, time_t now) static
Definition at line 180 of file idmap.c.
References BRIX_IDMAP_OK, BRIX_IDMAP_SQUASH, idmap_cache_slot_t::creds, idmap_cache_slot_t::expiry, idmap_ttl, ngx_memcpy, idmap_cache_slot_t::principal, and idmap_cache_slot_t::rc.
Referenced by brix_idmap_resolve().
idmap_hash()
static ngx_uint_t idmap_hash (const char * s) static
Definition at line 52 of file idmap.c.
References IDMAP_CACHE_SLOTS, IDMAP_DJB2_SEED, and s.
Referenced by brix_idmap_resolve().
idmap_init_policy()
static void idmap_init_policy (const brix_idmap_conf_t * conf, ngx_log_t * log) static
Definition at line 70 of file idmap.c.
References BRIX_IDMAP_DEFAULT_MIN_UID, BRIX_IDMAP_DEFAULT_TTL, BRIX_IMP_HARD_MIN_ID, brix_idmap_conf_t::cache_ttl, idmap_min_uid, idmap_primary_only, idmap_ttl, log, brix_idmap_conf_t::min_uid, and brix_idmap_conf_t::primary_only.
Referenced by brix_idmap_init().
idmap_resolve_uncached()
static int idmap_resolve_uncached (const char * principal, brix_idmap_creds_t * creds, const char ** user_out) static
Definition at line 153 of file idmap.c.
References BRIX_IDMAP_DENY, BRIX_IDMAP_OK, BRIX_IDMAP_SQUASH, idmap_creds_allowed(), idmap_default_user, idmap_gridmap_lookup(), and idmap_resolve_user().
Referenced by brix_idmap_resolve().
Variable Documentation
idmap_cache
idmap_cache_slot_t idmap_cache[256] static
Definition at line 43 of file idmap.c.
Referenced by brix_idmap_init(), and brix_idmap_resolve().
idmap_default_user
char idmap_default_user[512] static
Definition at line 48 of file idmap.c.
Referenced by brix_idmap_init(), and idmap_resolve_uncached().
idmap_min_uid
uid_t idmap_min_uid = 1000
Definition at line 46 of file idmap.c.
Referenced by idmap_creds_allowed(), idmap_gid_reserved_or_forbidden(), and idmap_init_policy().
idmap_primary_only
int idmap_primary_only
Definition at line 47 of file idmap.c.
Referenced by idmap_init_policy(), and idmap_resolve_user().
idmap_ttl
time_t idmap_ttl = 600 static
Definition at line 45 of file idmap.c.
Referenced by idmap_cache_put(), and idmap_init_policy().