nginx-xrootd: src/auth/impersonate/impersonate.h File Reference
impersonate.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <signal.h>
Data Structures
struct brix_idmap_creds_t
struct brix_idmap_conf_t
Macros
#define BRIX_IMP_OFF 0 /* default: no broker, no mapping, worker uid */
#define BRIX_IMP_SINGLE 1 /* drop-back: all identities squash to one user */
#define BRIX_IMP_MAP 2 /* full: per-identity mapping via the root broker */
#define BRIX_IDMAP_MAXGROUPS 32
#define BRIX_IDMAP_OK 0 /* mapped to a concrete account (out filled) */
#define BRIX_IDMAP_SQUASH 1 /* no direct map; squashed to default_user */
#define BRIX_IDMAP_DENY 2 /* no map + deny policy (out NOT filled) */
#define BRIX_IDMAP_DEFAULT_MIN_UID 1000
#define BRIX_IDMAP_DEFAULT_TTL 600
#define BRIX_IMP_HARD_MIN_ID 1000
#define BRIX_IMP_DEFAULT_FORBIDDEN_GROUPS
#define BRIX_IMP_DEFAULT_FORBIDDEN_USERS
Functions
ngx_int_t brix_idmap_init (const brix_idmap_conf_t *conf, ngx_log_t *log)
ngx_int_t brix_idmap_resolve (const brix_idmap_conf_t *conf, const char *principal, brix_idmap_creds_t *out, ngx_log_t *log)
int brix_imp_creds_privileged (const brix_idmap_creds_t *cr, uid_t floor, uint32_t *out_id, char *out_kind)
int brix_imp_broker_drop_caps (ngx_log_t *log)
int brix_imp_broker_run (int listen_fd, int rootfd, const volatile sig_atomic_t *stop, ngx_log_t *log)
ngx_int_t brix_imp_client_connect (const char *path, ngx_log_t *log)
int brix_imp_client_active (void)
int brix_imp_enabled (void)
void brix_imp_mark_in_request (int on)
void brix_imp_set_principal (const char *principal)
void brix_imp_clear_principal (void)
int brix_imp_open (const char *reqpath, int flags, mode_t mode)
int brix_imp_stat (const char *reqpath, struct stat *st, int nofollow)
int brix_imp_mkdir (const char *reqpath, mode_t mode)
int brix_imp_unlink (const char *reqpath, int is_dir)
int brix_imp_rmdir (const char *reqpath)
int brix_imp_rename (const char *src, const char *dst)
int brix_imp_rename_noreplace (const char *src, const char *dst)
int brix_imp_link (const char *src, const char *dst)
int brix_imp_truncate (const char *reqpath, off_t length)
int brix_imp_chmod (const char *reqpath, mode_t mode)
int brix_imp_chown_gid (const char *reqpath, gid_t gid)
int brix_imp_setattr (const char *reqpath, int set_times, const struct timespec times[2], int set_owner, uid_t uid, gid_t gid)
int brix_imp_symlink (const char *target, const char *linkpath)
ssize_t brix_imp_readlink (const char *reqpath, char *buf, size_t bufsz)
ssize_t brix_imp_getxattr (const char *reqpath, const char *name, void *buf, size_t bufsz)
int brix_imp_setxattr (const char *reqpath, const char *name, const void *value, size_t len, int flags)
int brix_imp_removexattr (const char *reqpath, const char *name)
ssize_t brix_imp_listxattr (const char *reqpath, void *buf, size_t bufsz)
Variables
uid_t brix_imp_broker_allow_uid
uid_t brix_imp_broker_user_uid
gid_t brix_imp_broker_user_gid
Macro Definition Documentation
BRIX_IDMAP_DEFAULT_MIN_UID
#define BRIX_IDMAP_DEFAULT_MIN_UID 1000
Definition at line 119 of file impersonate.h.
BRIX_IDMAP_DEFAULT_TTL
#define BRIX_IDMAP_DEFAULT_TTL 600
Definition at line 121 of file impersonate.h.
BRIX_IDMAP_DENY
#define BRIX_IDMAP_DENY 2 /* no map + deny policy (out NOT filled) */
Definition at line 51 of file impersonate.h.
BRIX_IDMAP_MAXGROUPS
#define BRIX_IDMAP_MAXGROUPS 32
Definition at line 43 of file impersonate.h.
BRIX_IDMAP_OK
#define BRIX_IDMAP_OK 0 /* mapped to a concrete account (out filled) */
Definition at line 49 of file impersonate.h.
BRIX_IDMAP_SQUASH
#define BRIX_IDMAP_SQUASH 1 /* no direct map; squashed to default_user */
Definition at line 50 of file impersonate.h.
BRIX_IMP_DEFAULT_FORBIDDEN_GROUPS
#define BRIX_IMP_DEFAULT_FORBIDDEN_GROUPS
Value:
    "root,wheel,sudo,su,admin,sudoers,adm,sys,daemon,bin,staff,disk,shadow," \
    "kmem,mem,docker,lxd,libvirt,kvm,systemd-journal,ssl-cert,lpadmin,netdev"
Definition at line 140 of file impersonate.h.
BRIX_IMP_DEFAULT_FORBIDDEN_USERS
#define BRIX_IMP_DEFAULT_FORBIDDEN_USERS
Value:
    "root,daemon,bin,sys,sync,games,man,lp,mail,news,uucp,proxy,backup,list," \
    "nobody,nginx,www-data,xrootd,apache,httpd"
Definition at line 150 of file impersonate.h.
BRIX_IMP_HARD_MIN_ID
#define BRIX_IMP_HARD_MIN_ID 1000
Definition at line 131 of file impersonate.h.
BRIX_IMP_MAP
#define BRIX_IMP_MAP 2 /* full: per-identity mapping via the root broker */
Definition at line 40 of file impersonate.h.
BRIX_IMP_OFF
#define BRIX_IMP_OFF 0 /* default: no broker, no mapping, worker uid */
Definition at line 38 of file impersonate.h.
BRIX_IMP_SINGLE
#define BRIX_IMP_SINGLE 1 /* drop-back: all identities squash to one user */
Definition at line 39 of file impersonate.h.
Function Documentation
brix_idmap_init()
ngx_int_t brix_idmap_init (const brix_idmap_conf_t * conf, ngx_log_t * log)
Definition at line 97 of file idmap.c.
References brix_str_cbuf(), brix_idmap_conf_t::default_user, brix_idmap_conf_t::gridmap_path, idmap_cache, idmap_default_user, idmap_gridmap_load(), idmap_init_denylists(), idmap_init_policy(), IDMAP_PRINC_MAX, and log.
Referenced by imp_load_idmap().
brix_idmap_resolve()
ngx_int_t brix_idmap_resolve (const brix_idmap_conf_t * conf, const char * principal, brix_idmap_creds_t * out, ngx_log_t * log)
Definition at line 192 of file idmap.c.
References BRIX_IDMAP_DENY, BRIX_IDMAP_OK, BRIX_IDMAP_SQUASH, idmap_cache, idmap_cache_get(), idmap_cache_put(), idmap_hash(), IDMAP_PRINC_MAX, idmap_resolve_uncached(), and log.
Referenced by imp_serve_one().
brix_imp_broker_drop_caps()
int brix_imp_broker_drop_caps (ngx_log_t * log)
Definition at line 206 of file broker_creds.c.
References brix_seccomp_broker_apply(), BRIX_SECCOMP_CORE_ERR, BRIX_SECCOMP_CORE_OK, imp_capset_setuid_setgid(), imp_drop_to_service_user(), and log.
Referenced by imp_broker_init_creds().
brix_imp_broker_run()
int brix_imp_broker_run (int listen_fd, int rootfd, const volatile sig_atomic_t * stop, ngx_log_t * log)
Definition at line 413 of file broker.c.
References imp_broker_accept(), imp_broker_init_creds(), IMP_BROKER_MAXCONN, imp_broker_reap(), and log.
Referenced by imp_broker_child().
brix_imp_chmod()
int brix_imp_chmod (const char * reqpath, mode_t mode)
Definition at line 184 of file client_ops.c.
References imp_call_status(), and IMP_OP_CHMOD.
Referenced by brix_chmod_confined_canon().
brix_imp_chown_gid()
int brix_imp_chown_gid (const char * reqpath, gid_t gid)
Definition at line 190 of file client_ops.c.
References imp_call_status(), and IMP_OP_CHOWN.
brix_imp_clear_principal()
void brix_imp_clear_principal (void)
Definition at line 166 of file client.c.
References imp_principal.
Referenced by brix_imp_request_end().
brix_imp_client_active()
int brix_imp_client_active (void)
Definition at line 120 of file client.c.
References imp_enabled, imp_in_request, and imp_principal.
Referenced by brix_chmod_confined_canon(), brix_dirlist_access_ok(), brix_getxattr_confined_canon(), brix_link_beneath(), brix_link_confined_canon(), brix_listxattr_confined_canon(), brix_lstat_beneath(), brix_lstat_confined_canon(), brix_mkdir_beneath(), brix_mkdir_confined_canon(), brix_open_beneath(), brix_open_confined_canon(), brix_opendir_confined_canon(), brix_readlink_confined_canon(), brix_removexattr_confined_canon(), brix_rename_beneath(), brix_rename_beneath_excl(), brix_setattr_confined_canon(), brix_setxattr_confined_canon(), brix_stat_beneath(), brix_symlink_confined_canon(), brix_unlink_beneath(), brix_unlink_confined_canon(), and rename_confined_canon_impl().
brix_imp_client_connect()
ngx_int_t brix_imp_client_connect (const char * path, ngx_log_t * log)
Definition at line 94 of file client.c.
References imp_drop_conn(), imp_enabled, imp_ensure_conn(), imp_log, imp_sock_path, log, and ngx_memcpy.
Referenced by brix_imp_init_worker().
brix_imp_creds_privileged()
int brix_imp_creds_privileged (const brix_idmap_creds_t * cr, uid_t floor, uint32_t * out_id, char * out_kind)
Definition at line 161 of file idmap_denylist.c.
References BRIX_IDMAP_MAXGROUPS, brix_idmap_creds_t::gid, brix_idmap_creds_t::groups, imp_id_reserved(), imp_priv_report(), brix_idmap_creds_t::ngroups, and brix_idmap_creds_t::uid.
Referenced by idmap_creds_allowed(), and imp_become().
brix_imp_enabled()
int brix_imp_enabled (void)
Definition at line 137 of file client.c.
References imp_enabled.
Referenced by brix_dirlist_access_ok(), webdav_copy_collection_post_task(), and webdav_move_collection_post_task().
brix_imp_getxattr()
ssize_t brix_imp_getxattr (const char * reqpath, const char * name, void * buf, size_t bufsz)
Definition at line 303 of file client_ops.c.
References imp_get_or_list(), IMP_OP_GETXATTR, and name.
Referenced by brix_getxattr_confined_canon().
brix_imp_link()
int brix_imp_link (const char * src, const char * dst)
Definition at line 172 of file client_ops.c.
References imp_call_status(), and IMP_OP_LINK.
Referenced by brix_link_beneath(), and brix_link_confined_canon().
brix_imp_listxattr()
ssize_t brix_imp_listxattr (const char * reqpath, void * buf, size_t bufsz)
Definition at line 310 of file client_ops.c.
References imp_get_or_list(), and IMP_OP_LISTXATTR.
Referenced by brix_listxattr_confined_canon().
brix_imp_mark_in_request()
void brix_imp_mark_in_request (int on)
Definition at line 143 of file client.c.
References imp_in_request.
Referenced by brix_imp_request_begin(), and brix_imp_request_end().
brix_imp_mkdir()
int brix_imp_mkdir (const char * reqpath, mode_t mode)
Definition at line 141 of file client_ops.c.
References imp_call_status(), and IMP_OP_MKDIR.
Referenced by brix_mkdir_beneath(), and brix_mkdir_confined_canon().
brix_imp_open()
int brix_imp_open (const char * reqpath, int flags, mode_t mode)
Definition at line 73 of file client_ops.c.
References close(), imp_build_req(), imp_exchange(), IMP_OP_OPEN, IMP_REP_HAS_FD, imp_status_errno(), IMP_STATUS_INTERNAL, imp_rep_t::rep_flags, and imp_rep_t::status.
Referenced by brix_dirlist_access_ok(), brix_open_beneath(), brix_open_confined_canon(), and brix_opendir_confined_canon().
brix_imp_readlink()
ssize_t brix_imp_readlink (const char * reqpath, char * buf, size_t bufsz)
Definition at line 236 of file client_ops.c.
References close(), imp_rep_t::data_len, imp_build_req(), imp_exchange(), IMP_OP_READLINK, IMP_PATH_MAX, IMP_REP_HAS_DATA, imp_status_errno(), IMP_STATUS_INTERNAL, ngx_memcpy, imp_rep_t::rep_flags, and imp_rep_t::status.
Referenced by brix_readlink_confined_canon().
brix_imp_removexattr()
int brix_imp_removexattr (const char * reqpath, const char * name)
Definition at line 342 of file client_ops.c.
References close(), imp_build_req(), imp_exchange(), IMP_OP_REMOVEXATTR, imp_status_errno(), name, and imp_rep_t::status.
Referenced by brix_removexattr_confined_canon().
brix_imp_rename()
int brix_imp_rename (const char * src, const char * dst)
Definition at line 160 of file client_ops.c.
References imp_call_status(), and IMP_OP_RENAME.
Referenced by brix_rename_beneath(), and rename_confined_canon_impl().
brix_imp_rename_noreplace()
int brix_imp_rename_noreplace (const char * src, const char * dst)
Definition at line 166 of file client_ops.c.
References imp_call_status(), and IMP_OP_RENAME_NOREPLACE.
Referenced by brix_rename_beneath_excl(), and rename_confined_canon_impl().
brix_imp_rmdir()
int brix_imp_rmdir (const char * reqpath)
Definition at line 154 of file client_ops.c.
References imp_call_status(), and IMP_OP_RMDIR.
brix_imp_set_principal()
void brix_imp_set_principal (const char * principal)
Definition at line 149 of file client.c.
References imp_principal, and ngx_memcpy.
Referenced by brix_imp_request_begin().
brix_imp_setattr()
int brix_imp_setattr (const char * reqpath, int set_times, const struct timespec times[2], int set_owner, uid_t uid, gid_t gid)
Definition at line 197 of file client_ops.c.
References imp_req_t::atime_nsec, imp_req_t::atime_sec, imp_req_t::attr_flags, close(), IMP_ATTR_OWNER, IMP_ATTR_TIMES, imp_build_req(), imp_exchange(), IMP_OP_SETATTR, imp_status_errno(), imp_req_t::mtime_nsec, imp_req_t::mtime_sec, imp_req_t::set_gid, imp_req_t::set_uid, and imp_rep_t::status.
Referenced by brix_setattr_confined_canon().
brix_imp_setxattr()
int brix_imp_setxattr (const char * reqpath, const char * name, const void * value, size_t len, int flags)
Definition at line 316 of file client_ops.c.
References close(), imp_build_req(), imp_exchange(), IMP_OP_SETXATTR, imp_status_errno(), IMP_XATTR_MAX, name, imp_req_t::req_data_len, and imp_rep_t::status.
Referenced by brix_setxattr_confined_canon().
brix_imp_stat()
int brix_imp_stat (const char * reqpath, struct stat * st, int nofollow)
Definition at line 116 of file client_ops.c.
References close(), imp_build_req(), imp_exchange(), IMP_OP_LSTAT, IMP_OP_STAT, IMP_REP_HAS_STAT, imp_status_errno(), IMP_STATUS_INTERNAL, imp_unpack_stat(), imp_rep_t::rep_flags, imp_rep_t::st, and imp_rep_t::status.
Referenced by brix_lstat_beneath(), brix_lstat_confined_canon(), and brix_stat_beneath().
brix_imp_symlink()
int brix_imp_symlink (const char * target, const char * linkpath)
Definition at line 229 of file client_ops.c.
References imp_call_status(), and IMP_OP_SYMLINK.
Referenced by brix_symlink_confined_canon().
brix_imp_truncate()
int brix_imp_truncate (const char * reqpath, off_t length)
Definition at line 178 of file client_ops.c.
References imp_call_status(), and IMP_OP_TRUNCATE.
brix_imp_unlink()
int brix_imp_unlink (const char * reqpath, int is_dir)
Definition at line 147 of file client_ops.c.
References imp_call_status(), IMP_OP_RMDIR, and IMP_OP_UNLINK.
Referenced by brix_unlink_beneath(), and brix_unlink_confined_canon().
Variable Documentation
brix_imp_broker_allow_uid
uid_t brix_imp_broker_allow_uid extern
Definition at line 7 of file broker.c.
Referenced by brix_imp_init_module(), imp_become(), and imp_peer_allowed().
brix_imp_broker_user_gid
gid_t brix_imp_broker_user_gid extern
Definition at line 27 of file broker_creds.c.
Referenced by imp_resolve_broker_user(), and imp_resolve_service_ids().
brix_imp_broker_user_uid
uid_t brix_imp_broker_user_uid extern
Definition at line 26 of file broker_creds.c.
Referenced by imp_resolve_broker_user(), and imp_resolve_service_ids().