nginx-xrootd: src/auth/token/ini_unittest.c File Reference
ini_unittest.c File Reference
#include "ini.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
Data Structures
struct kv
struct collector
Macros
#define CHECK(cond, msg)
Functions
static int collect_cb (void *u, const char *section, const char *key, const char *value)
static const struct kv * find_kv (const struct collector *c, const char *section, const char *key)
static void write_tmp (const char *content, char *out, size_t outsz)
static void test_stock_fixture (void)
static void test_trim_and_comments (void)
static void test_malformed (void)
static void test_missing_file (void)
int main (void)
Variables
static int g_checks
static int g_failed
Macro Definition Documentation
CHECK
#define CHECK (cond, msg)
Value:
    do {                                                                       \
        g_checks++;                                                            \
        if (!(cond)) {                                                         \
            g_failed++;                                                        \
            fprintf(stderr, "FAIL: %s (line %d)\n", (msg), __LINE__);          \
        }                                                                      \
    } while (0)
Definition at line 25 of file ini_unittest.c.
Function Documentation
collect_cb()
static int collect_cb (void * u, const char * section, const char * key, const char * value) static
Definition at line 46 of file ini_unittest.c.
References c, and key.
Referenced by test_malformed(), test_missing_file(), test_stock_fixture(), and test_trim_and_comments().
find_kv()
static const struct kv * find_kv (const struct collector * c, const char * section, const char * key) static
Definition at line 60 of file ini_unittest.c.
References c, key, and kv::section.
Referenced by test_stock_fixture(), and test_trim_and_comments().
main()
int main (void)
Definition at line 167 of file ini_unittest.c.
References g_checks, g_failed, test_malformed(), test_missing_file(), test_stock_fixture(), and test_trim_and_comments().
test_malformed()
static void test_malformed (void) static
Definition at line 143 of file ini_unittest.c.
References brix_ini_parse_file(), c, CHECK, collect_cb(), and write_tmp().
Referenced by main().
test_missing_file()
static void test_missing_file (void) static
Definition at line 156 of file ini_unittest.c.
References brix_ini_parse_file(), c, CHECK, and collect_cb().
Referenced by main().
test_stock_fixture()
static void test_stock_fixture (void) static
Definition at line 85 of file ini_unittest.c.
References access(), brix_ini_parse_file(), c, CHECK, collect_cb(), find_kv(), and kv::value.
Referenced by main().
test_trim_and_comments()
static void test_trim_and_comments (void) static
Definition at line 115 of file ini_unittest.c.
References brix_ini_parse_file(), c, CHECK, collect_cb(), find_kv(), kv::value, and write_tmp().
Referenced by main().
write_tmp()
static void write_tmp (const char * content, char * out, size_t outsz) static
Definition at line 75 of file ini_unittest.c.
Referenced by test_malformed(), and test_trim_and_comments().
Variable Documentation
g_checks
int g_checks static
Definition at line 22 of file ini_unittest.c.
Referenced by main().
g_failed
int g_failed static
Definition at line 23 of file ini_unittest.c.
Referenced by main().