nginx-xrootd: src/auth/token/ini.h File Reference
ini.h File Reference
#include <stddef.h>
Typedefs
typedef int(* brix_ini_cb) (void *user, const char *section, const char *key, const char *value)
Functions
int brix_ini_parse_file (const char *path, brix_ini_cb cb, void *user, char *errbuf, size_t errlen)
Typedef Documentation
brix_ini_cb
typedef int(* brix_ini_cb) (void *user, const char *section, const char *key, const char *value)
Definition at line 20 of file ini.h.
Function Documentation
brix_ini_parse_file()
int brix_ini_parse_file (const char * path, brix_ini_cb cb, void * user, char * errbuf, size_t errlen)
Definition at line 82 of file ini.c.
References ini_drop_comment(), ini_section(), ini_trim(), and s.
Referenced by brix_throttle_userconfig_load(), brix_token_registry_load(), test_malformed(), test_missing_file(), test_stock_fixture(), and test_trim_and_comments().