nginx-xrootd: src/auth/token/ini.c File Reference
ini.c File Reference
#include "ini.h"
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <ctype.h>
Functions
static char * ini_lstrip (char *s)
static void ini_rstrip (char *s)
static char * ini_trim (char *s)
static void ini_drop_comment (char *s)
static int ini_section (char *s, char *out, size_t outsz)
int brix_ini_parse_file (const char *path, brix_ini_cb cb, void *user, char *errbuf, size_t errlen)
Function Documentation
brix_ini_parse_file()
int brix_ini_parse_file (const char * path, brix_ini_cb cb, void * user, char * errbuf, size_t errlen)
Definition at line 82 of file ini.c.
References ini_drop_comment(), ini_section(), ini_trim(), and s.
Referenced by brix_throttle_userconfig_load(), brix_token_registry_load(), test_malformed(), test_missing_file(), test_stock_fixture(), and test_trim_and_comments().
ini_drop_comment()
static void ini_drop_comment (char * s) static
Definition at line 50 of file ini.c.
References s.
Referenced by brix_ini_parse_file().
ini_lstrip()
static char * ini_lstrip (char * s) static
Definition at line 23 of file ini.c.
References s.
Referenced by ini_trim().
ini_rstrip()
static void ini_rstrip (char * s) static
Definition at line 32 of file ini.c.
References s.
Referenced by ini_trim().
ini_section()
static int ini_section (char * s, char * out, size_t outsz) static
Definition at line 63 of file ini.c.
References ini_trim(), name, and s.
Referenced by brix_ini_parse_file().
ini_trim()
static char * ini_trim (char * s) static
Definition at line 42 of file ini.c.
References ini_lstrip(), ini_rstrip(), and s.
Referenced by brix_ini_parse_file(), and ini_section().