nginx-xrootd: src/core/compat/integrity_info.c File Reference
integrity_info.c File Reference
#include "integrity_info.h"
#include "fs/vfs/vfs.h"
#include "fs/meta/xmeta_path.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/stat.h>
#include <openssl/evp.h>
Data Structures
struct xrd_cks_data
Macros
#define INTEGRITY_XATTR_VAL_MAX 160
Functions
static const char * integrity_xattr_key (const char *algo, char *buf, size_t bufsz)
static int cks_hex_nibble (unsigned char c)
size_t brix_cksdata_encode (const brix_integrity_info_t *in, time_t fmtime, unsigned char *out)
int brix_cksdata_decode (const unsigned char *buf, size_t len, time_t cur_mtime, brix_integrity_info_t *out)
static int integrity_xattr_read (int fd, const char *algo, brix_integrity_info_t *out)
void brix_integrity_set_xattr_format (ngx_uint_t fmt)
static int integrity_xattr_write_rc (int fd, const char *algo, const char *hexval)
static uint16_t integrity_alg_id (const char *algo)
static int integrity_record_read (const char *path, const char *algo, brix_integrity_info_t *out)
static void integrity_record_write (const char *path, const char *algo, const char *hexval)
ngx_int_t brix_integrity_get_fd (ngx_log_t *log, int fd, brix_sd_obj_t *obj, const char *path, const char *alg_name, const brix_integrity_opts_t *opts, brix_integrity_info_t *out)
ngx_int_t brix_integrity_format_http_digest (const brix_integrity_info_t *info, char *out, size_t outsz)
void brix_integrity_invalidate_fd (ngx_log_t *log, int fd)
void brix_integrity_invalidate_path (ngx_log_t *log, const char *root_canon, const char *path)
Variables
static const char *const s_algorithms []
static ngx_uint_t s_xattr_format = 0
static const brix_integrity_opts_t s_default_opts
Macro Definition Documentation
INTEGRITY_XATTR_VAL_MAX
#define INTEGRITY_XATTR_VAL_MAX 160
Definition at line 31 of file integrity_info.c.
Function Documentation
brix_cksdata_decode()
int brix_cksdata_decode (const unsigned char * buf, size_t len, time_t cur_mtime, brix_integrity_info_t * out)
Definition at line 97 of file integrity_info.c.
References brix_integrity_info_t::alg_name, xrd_cks_data::fmTime, brix_integrity_info_t::from_cache, brix_integrity_info_t::hex, xrd_cks_data::Length, xrd_cks_data::Name, and xrd_cks_data::Value.
Referenced by integrity_xattr_read().
brix_cksdata_encode()
size_t brix_cksdata_encode (const brix_integrity_info_t * in, time_t fmtime, unsigned char * out)
Definition at line 73 of file integrity_info.c.
References brix_integrity_info_t::alg_name, cks_hex_nibble(), xrd_cks_data::csTime, xrd_cks_data::fmTime, brix_integrity_info_t::hex, xrd_cks_data::Length, xrd_cks_data::Name, and xrd_cks_data::Value.
Referenced by integrity_xattr_write_rc().
brix_integrity_format_http_digest()
ngx_int_t brix_integrity_format_http_digest (const brix_integrity_info_t * info, char * out, size_t outsz)
Definition at line 498 of file integrity_info.c.
References brix_integrity_info_t::alg_name, and brix_integrity_info_t::hex.
Referenced by xrdhttp_add_checksum_header().
brix_integrity_get_fd()
ngx_int_t brix_integrity_get_fd (ngx_log_t * log, int fd, brix_sd_obj_t * obj, const char * path, const char * alg_name, const brix_integrity_opts_t * opts, brix_integrity_info_t * out)
Definition at line 409 of file integrity_info.c.
References brix_integrity_info_t::alg, brix_integrity_info_t::alg_name, brix_integrity_opts_t::allow_xattr_cache, brix_checksum_hex_fd(), brix_checksum_hex_obj(), brix_checksum_parse(), brix_integrity_info_t::from_cache, fstat(), hex(), brix_integrity_info_t::hex, integrity_record_read(), integrity_record_write(), integrity_xattr_read(), integrity_xattr_write_rc(), log, brix_integrity_opts_t::no_compute, brix_integrity_opts_t::require_regular_file, s_default_opts, stat(), and brix_integrity_opts_t::update_xattr_cache.
Referenced by brix_cksum_aio_thread(), brix_dirlist_checksum_token(), brix_query_build_checksum(), s3_checksum_b64(), s3_object_crc64nvme_b64(), scan_action_fill(), scan_action_verify(), scan_stored(), scan_verify_obj_record(), webdav_put_persist_checksums(), and xrdhttp_add_checksum_header().
brix_integrity_invalidate_fd()
void brix_integrity_invalidate_fd (ngx_log_t * log, int fd)
Definition at line 510 of file integrity_info.c.
References brix_vfs_fremovexattr(), integrity_xattr_key(), key, log, and s_algorithms.
brix_integrity_invalidate_path()
void brix_integrity_invalidate_path (ngx_log_t * log, const char * root_canon, const char * path)
Definition at line 525 of file integrity_info.c.
References BRIX_PROTO_ROOT, brix_vfs_ctx_init(), brix_vfs_removexattr(), integrity_xattr_key(), key, log, and s_algorithms.
brix_integrity_set_xattr_format()
void brix_integrity_set_xattr_format (ngx_uint_t fmt)
Definition at line 211 of file integrity_info.c.
References BRIX_CKS_FMT_TEXT, BRIX_CKS_FMT_XRDCKS, and s_xattr_format.
Referenced by ngx_http_brix_webdav_merge_loc_conf().
cks_hex_nibble()
static int cks_hex_nibble (unsigned char c) static
Definition at line 64 of file integrity_info.c.
References c.
Referenced by brix_cksdata_encode().
integrity_alg_id()
static uint16_t integrity_alg_id (const char * algo) static
Definition at line 277 of file integrity_info.c.
References BRIX_XMETA_ALG_ADLER32, BRIX_XMETA_ALG_CRC32, BRIX_XMETA_ALG_CRC32C, BRIX_XMETA_ALG_CRC64NVME, BRIX_XMETA_ALG_CRC64XZ, BRIX_XMETA_ALG_MD5, BRIX_XMETA_ALG_SHA1, BRIX_XMETA_ALG_SHA256, BRIX_XMETA_ALG_ZCRC32, and name.
Referenced by integrity_record_read(), and integrity_record_write().
integrity_record_read()
static int integrity_record_read (const char * path, const char * algo, brix_integrity_info_t * out) static
Definition at line 302 of file integrity_info.c.
References brix_xmeta_digest_get(), brix_xmeta_free(), BRIX_XMETA_OK, brix_xmeta_path_load(), brix_integrity_info_t::from_cache, brix_integrity_info_t::hex, integrity_alg_id(), INTEGRITY_XATTR_VAL_MAX, and stat().
Referenced by brix_integrity_get_fd().
integrity_record_write()
static void integrity_record_write (const char * path, const char * algo, const char * hexval) static
Definition at line 353 of file integrity_info.c.
References brix_xmeta_t::bitmap, brix_xmeta_digest_set(), BRIX_XMETA_ERR, BRIX_XMETA_FOREIGN, brix_xmeta_free(), brix_xmeta_init(), BRIX_XMETA_OK, brix_xmeta_path_load(), brix_xmeta_path_lock(), brix_xmeta_path_save(), brix_xmeta_path_unlock(), brix_xmeta_t::have_blockcrc, integrity_alg_id(), INTEGRITY_XATTR_VAL_MAX, brix_xmeta_t::nblocks, brix_xmeta_t::origin_mtime, and stat().
Referenced by brix_integrity_get_fd().
integrity_xattr_key()
static const char * integrity_xattr_key (const char * algo, char * buf, size_t bufsz) static
Definition at line 40 of file integrity_info.c.
Referenced by brix_integrity_invalidate_fd(), brix_integrity_invalidate_path(), integrity_xattr_read(), and integrity_xattr_write_rc().
integrity_xattr_read()
static int integrity_xattr_read (int fd, const char * algo, brix_integrity_info_t * out) static
Definition at line 137 of file integrity_info.c.
References brix_cksdata_decode(), brix_vfs_fgetxattr(), brix_integrity_info_t::from_cache, fstat(), brix_integrity_info_t::hex, integrity_xattr_key(), INTEGRITY_XATTR_VAL_MAX, key, and stat().
Referenced by brix_integrity_get_fd().
integrity_xattr_write_rc()
static int integrity_xattr_write_rc (int fd, const char * algo, const char * hexval) static
Definition at line 223 of file integrity_info.c.
References brix_integrity_info_t::alg_name, BRIX_CKS_FMT_XRDCKS, brix_cksdata_encode(), brix_vfs_fsetxattr(), fstat(), brix_integrity_info_t::hex, integrity_xattr_key(), INTEGRITY_XATTR_VAL_MAX, key, s_xattr_format, and stat().
Referenced by brix_integrity_get_fd().
Variable Documentation
s_algorithms
const char* const s_algorithms[] static
Initial value:
= {
    "adler32", "crc32", "crc32c", "md5", "sha1", "sha256",
    "crc64", "crc64nvme", "zcrc32", NULL
}
Definition at line 34 of file integrity_info.c.
Referenced by brix_integrity_invalidate_fd(), and brix_integrity_invalidate_path().
s_default_opts
const brix_integrity_opts_t s_default_opts static
Initial value:
= {
    .allow_xattr_cache    = 1,
    .update_xattr_cache   = 1,
    .require_regular_file = 0,
}
Definition at line 402 of file integrity_info.c.
Referenced by brix_integrity_get_fd().
s_xattr_format
ngx_uint_t s_xattr_format = 0 static
Definition at line 208 of file integrity_info.c.
Referenced by brix_integrity_set_xattr_format(), and integrity_xattr_write_rc().