nginx-xrootd: src/core/compat/integrity_info_record.c File Reference
integrity_info_record.c File Reference
#include "integrity_info.h"
#include "integrity_info_internal.h"
#include "fs/meta/xmeta_path.h"
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
Functions
static uint16_t integrity_alg_id (const char *algo)
int integrity_record_read (const char *path, const char *algo, brix_integrity_info_t *out)
void integrity_record_write (const char *path, const char *algo, const char *hexval)
Function Documentation
integrity_alg_id()
static uint16_t integrity_alg_id (const char * algo) static
Definition at line 41 of file integrity_info_record.c.
References BRIX_XMETA_ALG_ADLER32, BRIX_XMETA_ALG_CRC32, BRIX_XMETA_ALG_CRC32C, BRIX_XMETA_ALG_CRC64NVME, BRIX_XMETA_ALG_CRC64XZ, BRIX_XMETA_ALG_MD5, BRIX_XMETA_ALG_SHA1, BRIX_XMETA_ALG_SHA256, BRIX_XMETA_ALG_ZCRC32, and name.
Referenced by integrity_record_read(), and integrity_record_write().
integrity_record_read()
int integrity_record_read (const char * path, const char * algo, brix_integrity_info_t * out)
Definition at line 66 of file integrity_info_record.c.
References alg, brix_xmeta_digest_get(), brix_xmeta_free(), BRIX_XMETA_OK, brix_xmeta_path_load(), brix_integrity_info_t::from_cache, brix_integrity_info_t::hex, integrity_alg_id(), INTEGRITY_XATTR_VAL_MAX, and stat().
Referenced by integrity_cache_lookup().
integrity_record_write()
void integrity_record_write (const char * path, const char * algo, const char * hexval)
Definition at line 117 of file integrity_info_record.c.
References brix_xmeta_t::bitmap, brix_xmeta_digest_set(), BRIX_XMETA_ERR, BRIX_XMETA_FOREIGN, brix_xmeta_free(), brix_xmeta_init(), BRIX_XMETA_OK, brix_xmeta_path_load(), brix_xmeta_path_lock(), brix_xmeta_path_save(), brix_xmeta_path_unlock(), brix_xmeta_t::have_blockcrc, integrity_alg_id(), INTEGRITY_XATTR_VAL_MAX, brix_xmeta_t::nblocks, brix_xmeta_t::origin_mtime, and stat().
Referenced by integrity_persist_computed().