nginx-xrootd: src/core/compat/integrity_info.h File Reference
integrity_info.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include "checksum.h"
Data Structures
struct brix_integrity_info_t
struct brix_integrity_opts_t
Macros
#define BRIX_CKS_FMT_TEXT 0 /* "<hex> <mtime_sec> <mtime_nsec> <size>" */
#define BRIX_CKS_FMT_XRDCKS 1 /* binary XrdCksData (read by stock xrdfs/OSS) */
Functions
ngx_int_t brix_integrity_get_fd (ngx_log_t *log, int fd, brix_sd_obj_t *obj, const char *path, const char *alg_name, const brix_integrity_opts_t *opts, brix_integrity_info_t *out)
ngx_int_t brix_integrity_format_http_digest (const brix_integrity_info_t *info, char *out, size_t outsz)
void brix_integrity_invalidate_fd (ngx_log_t *log, int fd)
void brix_integrity_invalidate_path (ngx_log_t *log, const char *root_canon, const char *path)
size_t brix_cksdata_encode (const brix_integrity_info_t *in, time_t fmtime, unsigned char *out88)
int brix_cksdata_decode (const unsigned char *buf, size_t len, time_t cur_mtime, brix_integrity_info_t *out)
void brix_integrity_set_xattr_format (ngx_uint_t fmt)
Macro Definition Documentation
BRIX_CKS_FMT_TEXT
#define BRIX_CKS_FMT_TEXT 0 /* "<hex> <mtime_sec> <mtime_nsec> <size>" */
Definition at line 122 of file integrity_info.h.
BRIX_CKS_FMT_XRDCKS
#define BRIX_CKS_FMT_XRDCKS 1 /* binary XrdCksData (read by stock xrdfs/OSS) */
Definition at line 123 of file integrity_info.h.
Function Documentation
brix_cksdata_decode()
int brix_cksdata_decode (const unsigned char * buf, size_t len, time_t cur_mtime, brix_integrity_info_t * out)
Definition at line 98 of file integrity_info.c.
References brix_integrity_info_t::alg_name, xrd_cks_data::fmTime, brix_integrity_info_t::from_cache, brix_integrity_info_t::hex, xrd_cks_data::Length, xrd_cks_data::Name, ngx_memcpy, and xrd_cks_data::Value.
Referenced by integrity_xattr_read().
brix_cksdata_encode()
size_t brix_cksdata_encode (const brix_integrity_info_t * in, time_t fmtime, unsigned char * out88)
Definition at line 74 of file integrity_info.c.
References brix_integrity_info_t::alg_name, cks_hex_nibble(), xrd_cks_data::csTime, xrd_cks_data::fmTime, brix_integrity_info_t::hex, xrd_cks_data::Length, xrd_cks_data::Name, ngx_memcpy, and xrd_cks_data::Value.
Referenced by integrity_xattr_write_rc().
brix_integrity_format_http_digest()
ngx_int_t brix_integrity_format_http_digest (const brix_integrity_info_t * info, char * out, size_t outsz)
Definition at line 417 of file integrity_info.c.
References brix_integrity_info_t::alg_name, and brix_integrity_info_t::hex.
Referenced by xrdhttp_add_checksum_header().
brix_integrity_get_fd()
ngx_int_t brix_integrity_get_fd (ngx_log_t * log, int fd, brix_sd_obj_t * obj, const char * path, const char * alg_name, const brix_integrity_opts_t * opts, brix_integrity_info_t * out)
Definition at line 359 of file integrity_info.c.
References brix_integrity_info_t::alg, brix_integrity_info_t::alg_name, brix_integrity_opts_t::allow_xattr_cache, brix_checksum_parse(), brix_integrity_info_t::from_cache, hex(), brix_integrity_info_t::hex, integrity_cache_lookup(), integrity_compute_hex(), integrity_is_nonregular(), integrity_persist_computed(), log, brix_integrity_opts_t::no_compute, brix_integrity_opts_t::require_regular_file, s_default_opts, and brix_integrity_opts_t::update_xattr_cache.
Referenced by brix_cksum_aio_thread(), brix_dirlist_checksum_token(), brix_query_build_checksum(), s3_checksum_b64(), s3_object_crc64nvme_b64(), scan_action_fill(), scan_action_verify(), scan_stored(), scan_verify_obj_record(), webdav_put_persist_checksums(), and xrdhttp_add_checksum_header().
brix_integrity_invalidate_fd()
void brix_integrity_invalidate_fd (ngx_log_t * log, int fd)
Definition at line 429 of file integrity_info.c.
References brix_vfs_fremovexattr(), integrity_xattr_key(), key, log, and s_algorithms.
brix_integrity_invalidate_path()
void brix_integrity_invalidate_path (ngx_log_t * log, const char * root_canon, const char * path)
Definition at line 444 of file integrity_info.c.
References BRIX_PROTO_ROOT, brix_vfs_ctx_init(), brix_vfs_removexattr(), integrity_xattr_key(), key, log, and s_algorithms.
brix_integrity_set_xattr_format()
void brix_integrity_set_xattr_format (ngx_uint_t fmt)
Definition at line 212 of file integrity_info.c.
References BRIX_CKS_FMT_TEXT, BRIX_CKS_FMT_XRDCKS, and s_xattr_format.
Referenced by webdav_merge_base_conf().