nginx-xrootd: src/protocols/webdav/introspect.c File Reference
introspect.c File Reference
#include "webdav.h"
#include "core/compat/crypto.h"
#include <jansson.h>
#include "core/compat/alloc_guard.h"
Data Structures
struct webdav_introspect_data_t
Functions
static int webdav_introspect_parse_active (const u_char *body, size_t len)
static ngx_int_t webdav_introspect_done (ngx_http_request_t *r, void *data, ngx_int_t rc)
static ngx_int_t webdav_introspect_fire (ngx_http_request_t *r, ngx_http_brix_webdav_req_ctx_t *ctx, ngx_http_brix_webdav_loc_conf_t *conf, const ngx_str_t *token, const u_char key[32], int have_key)
ngx_int_t webdav_introspect_access_handler (ngx_http_request_t *r)
char * webdav_conf_revoke_cache (ngx_conf_t *cf, ngx_command_t *cmd, void *conf_ptr)
Function Documentation
webdav_conf_revoke_cache()
char * webdav_conf_revoke_cache (ngx_conf_t * cf, ngx_command_t * cmd, void * conf_ptr)
Definition at line 250 of file introspect.c.
References brix_kv_find(), and ngx_http_brix_webdav_loc_conf_t::revoke_kv.
webdav_introspect_access_handler()
ngx_int_t webdav_introspect_access_handler (ngx_http_request_t * r)
Definition at line 174 of file introspect.c.
References brix_http_extract_bearer(), brix_kv_get(), BRIX_PCALLOC_OR_RETURN, brix_sha256(), ngx_http_brix_webdav_req_ctx_t::introspect_active, ngx_http_brix_webdav_req_ctx_t::introspect_done, ngx_http_brix_webdav_loc_conf_t::introspect_fail_open, ngx_http_brix_webdav_loc_conf_t::introspect_loc, key, ngx_http_brix_webdav_module, ngx_http_brix_webdav_loc_conf_t::revoke_kv, and webdav_introspect_fire().
Referenced by webdav_postconf_install_handlers().
webdav_introspect_done()
static ngx_int_t webdav_introspect_done (ngx_http_request_t * r, void * data, ngx_int_t rc) static
Definition at line 91 of file introspect.c.
References brix_kv_set(), webdav_introspect_data_t::conf, webdav_introspect_data_t::have_key, ngx_http_brix_webdav_req_ctx_t::introspect_active, ngx_http_brix_webdav_req_ctx_t::introspect_done, ngx_http_brix_webdav_loc_conf_t::introspect_fail_open, ngx_http_brix_webdav_loc_conf_t::introspect_ttl, webdav_introspect_data_t::key, webdav_introspect_data_t::parent_ctx, ngx_http_brix_webdav_loc_conf_t::revoke_kv, and webdav_introspect_parse_active().
Referenced by webdav_introspect_fire().
webdav_introspect_fire()
static ngx_int_t webdav_introspect_fire (ngx_http_request_t * r, ngx_http_brix_webdav_req_ctx_t * ctx, ngx_http_brix_webdav_loc_conf_t * conf, const ngx_str_t * token, const u_char key[32], int have_key) static
Definition at line 129 of file introspect.c.
References webdav_introspect_data_t::conf, webdav_introspect_data_t::have_key, ngx_http_brix_webdav_loc_conf_t::introspect_loc, key, webdav_introspect_data_t::key, ngx_memcpy, ngx_pcalloc(), ngx_pnalloc(), webdav_introspect_data_t::parent_ctx, and webdav_introspect_done().
Referenced by webdav_introspect_access_handler().
webdav_introspect_parse_active()
static int webdav_introspect_parse_active (const u_char * body, size_t len) static
Definition at line 58 of file introspect.c.
References ngx_memcpy.
Referenced by webdav_introspect_done().