nginx-xrootd: client/lib/fs/iobuf.c File Reference
iobuf.c File Reference
#include "iobuf.h"
#include <stdlib.h>
#include <string.h>
Functions
void brix_iobuf_init (brix_iobuf *b, void *be, brix_iobuf_pread_fn pr, brix_iobuf_pwrite_fn pw, int writable, size_t ra_size, size_t wb_size)
int brix_iobuf_flush (brix_iobuf *b, brix_status *st)
static int iobuf_range_cached (const brix_iobuf *b, off_t off, size_t n)
static int iobuf_refill (brix_iobuf *b, off_t off, size_t n, brix_status *st)
static size_t iobuf_serve (const brix_iobuf *b, off_t off, char *out, size_t n)
ssize_t brix_iobuf_read (brix_iobuf *b, off_t off, char *out, size_t n, brix_status *st)
int brix_iobuf_write (brix_iobuf *b, off_t off, const char *in, size_t n, brix_status *st)
void brix_iobuf_dispose (brix_iobuf *b)
Function Documentation
brix_iobuf_dispose()
void brix_iobuf_dispose (brix_iobuf * b)
Definition at line 194 of file iobuf.c.
References brix_iobuf::rbuf, and brix_iobuf::wbuf.
Referenced by afh_free(), and xfs_handle_free().
brix_iobuf_flush()
int brix_iobuf_flush (brix_iobuf * b, brix_status * st)
Definition at line 28 of file iobuf.c.
References brix_iobuf::be, brix_iobuf::pwrite, brix_iobuf::wbuf, brix_iobuf::wbuf_len, and brix_iobuf::wbuf_off.
Referenced by afh_flush_wbuf(), brix_iobuf_read(), brix_iobuf_write(), and xfs_flush_wbuf().
brix_iobuf_init()
void brix_iobuf_init (brix_iobuf * b, void * be, brix_iobuf_pread_fn pr, brix_iobuf_pwrite_fn pw, int writable, size_t ra_size, size_t wb_size)
Definition at line 14 of file iobuf.c.
References brix_iobuf::be, brix_iobuf::pread, brix_iobuf::pwrite, brix_iobuf::ra_size, brix_iobuf::wb_size, and brix_iobuf::writable.
Referenced by afh_open(), xfs_create(), and xfs_open().
brix_iobuf_read()
ssize_t brix_iobuf_read (brix_iobuf * b, off_t off, char * out, size_t n, brix_status * st)
Definition at line 123 of file iobuf.c.
References brix_iobuf::be, brix_iobuf_flush(), iobuf_range_cached(), iobuf_refill(), iobuf_serve(), brix_iobuf::pread, brix_iobuf::ra_next, brix_iobuf::ra_size, brix_iobuf::rbuf, brix_iobuf::wbuf_len, and brix_iobuf::writable.
Referenced by xfs_read(), and xfs_read().
brix_iobuf_write()
int brix_iobuf_write (brix_iobuf * b, off_t off, const char * in, size_t n, brix_status * st)
Definition at line 157 of file iobuf.c.
References brix_iobuf::be, brix_iobuf_flush(), brix_iobuf::pwrite, brix_iobuf::wb_size, brix_iobuf::wbuf, brix_iobuf::wbuf_len, and brix_iobuf::wbuf_off.
Referenced by xfs_write(), and xfs_write().
iobuf_range_cached()
static int iobuf_range_cached (const brix_iobuf * b, off_t off, size_t n) static
Definition at line 56 of file iobuf.c.
References brix_iobuf::rbuf_len, and brix_iobuf::rbuf_off.
Referenced by brix_iobuf_read().
iobuf_refill()
static int iobuf_refill (brix_iobuf * b, off_t off, size_t n, brix_status * st) static
Definition at line 79 of file iobuf.c.
References brix_iobuf::be, brix_iobuf::pread, brix_iobuf::ra_next, brix_iobuf::ra_size, brix_iobuf::rbuf, brix_iobuf::rbuf_len, and brix_iobuf::rbuf_off.
Referenced by brix_iobuf_read().
iobuf_serve()
static size_t iobuf_serve (const brix_iobuf * b, off_t off, char * out, size_t n) static
Definition at line 108 of file iobuf.c.
References brix_iobuf::rbuf, brix_iobuf::rbuf_len, and brix_iobuf::rbuf_off.
Referenced by brix_iobuf_read().