nginx-xrootd: src/auth/token/issuer_registry.c File Reference
issuer_registry.c File Reference
#include "issuer_registry.h"
#include "ini.h"
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <sys/stat.h>
Functions
static int eqi (const char *a, const char *b)
static void copy_z (char *dst, size_t cap, const char *src)
static int parse_bool (const char *v)
uint32_t brix_token_strategy_parse (const char *value)
static void reg_add_list (char(*arr)[256], int *count, int cap, const char *csv)
static void reg_add_aud (char(*arr)[256], int *count, int cap, const char *csv)
static brix_token_issuer_t * reg_issuer_for (brix_token_registry_t *reg, const char *name)
static int reg_kv (void *u, const char *section, const char *key, const char *val)
ngx_int_t brix_token_registry_load (brix_token_registry_t *reg, const char *cfg_path, uint32_t default_strategy, char *errbuf, size_t errlen)
ngx_int_t brix_token_registry_build (ngx_conf_t *cf, const char *cfg_path, uint32_t default_strategy, brix_token_registry_t **out)
const brix_token_issuer_t * brix_token_registry_find (const brix_token_registry_t *reg, const char *iss)
int brix_token_issuer_path_ok (const brix_token_issuer_t *is, const char *req_path)
Function Documentation
brix_token_issuer_path_ok()
int brix_token_issuer_path_ok (const brix_token_issuer_t * is, const char * req_path)
Definition at line 287 of file issuer_registry.c.
References brix_token_issuer_t::base_path_count, brix_token_issuer_t::base_paths, brix_token_scope_path_matches(), brix_token_issuer_t::restricted_path_count, and brix_token_issuer_t::restricted_paths.
Referenced by brix_token_authz_strategy().
brix_token_registry_build()
ngx_int_t brix_token_registry_build (ngx_conf_t * cf, const char * cfg_path, uint32_t default_strategy, brix_token_registry_t ** out)
Definition at line 234 of file issuer_registry.c.
References brix_jwks_register_cleanup(), brix_token_registry_load(), brix_token_registry_t::count, brix_token_registry_t::issuers, brix_token_issuer_t::jwks_key_count, brix_token_issuer_t::jwks_keys, and brix_token_registry_t::log.
Referenced by brix_configure_token_auth(), ngx_http_brix_cvmfs_merge_loc_conf(), and ngx_http_brix_webdav_merge_loc_conf().
brix_token_registry_find()
const brix_token_issuer_t * brix_token_registry_find (const brix_token_registry_t * reg, const char * iss)
Definition at line 272 of file issuer_registry.c.
References brix_token_registry_t::count, brix_token_issuer_t::enabled, brix_token_issuer_t::issuer, and brix_token_registry_t::issuers.
Referenced by brix_token_validate_registry_authn().
brix_token_registry_load()
ngx_int_t brix_token_registry_load (brix_token_registry_t * reg, const char * cfg_path, uint32_t default_strategy, char * errbuf, size_t errlen)
Definition at line 186 of file issuer_registry.c.
References brix_token_issuer_t::base_path_count, brix_ini_parse_file(), brix_jwks_load(), BRIX_MAX_JWKS_KEYS, brix_token_registry_t::count, brix_token_registry_t::default_strategy, brix_token_issuer_t::issuer, brix_token_registry_t::issuers, brix_token_issuer_t::jwks_key_count, brix_token_issuer_t::jwks_keys, brix_token_issuer_t::jwks_mtime, brix_token_issuer_t::jwks_path, brix_token_registry_t::log, brix_token_issuer_t::name, reg_kv(), and stat().
Referenced by brix_token_registry_build().
brix_token_strategy_parse()
uint32_t brix_token_strategy_parse (const char * value)
Definition at line 45 of file issuer_registry.c.
References BRIX_AUTHZ_CAPABILITY, BRIX_AUTHZ_GROUP, BRIX_AUTHZ_MAPPING, copy_z(), and eqi().
Referenced by reg_kv().
copy_z()
static void copy_z (char * dst, size_t cap, const char * src) static
Definition at line 33 of file issuer_registry.c.
Referenced by brix_token_strategy_parse(), reg_add_aud(), reg_add_list(), reg_issuer_for(), and reg_kv().
eqi()
static int eqi (const char * a, const char * b) static
Definition at line 27 of file issuer_registry.c.
Referenced by brix_token_strategy_parse(), parse_bool(), reg_issuer_for(), and reg_kv().
parse_bool()
static int parse_bool (const char * v) static
Definition at line 39 of file issuer_registry.c.
References eqi().
Referenced by reg_kv().
reg_add_aud()
static void reg_add_aud (char(*) arr[256], int * count, int cap, const char * csv) static
Definition at line 85 of file issuer_registry.c.
References copy_z().
Referenced by reg_kv().
reg_add_list()
static void reg_add_list (char(*) arr[256], int * count, int cap, const char * csv) static
Definition at line 68 of file issuer_registry.c.
References BRIX_SCOPE_PATH_MAX, and copy_z().
Referenced by reg_kv().
reg_issuer_for()
static brix_token_issuer_t * reg_issuer_for (brix_token_registry_t * reg, const char * name) static
Definition at line 101 of file issuer_registry.c.
References BRIX_TOKEN_MAX_ISSUERS, copy_z(), brix_token_registry_t::count, brix_token_registry_t::default_strategy, brix_token_issuer_t::enabled, eqi(), brix_token_registry_t::issuers, brix_token_issuer_t::metric_bucket, brix_token_issuer_t::name, name, brix_token_issuer_t::onmissing_fail, brix_token_issuer_t::strategy, and brix_token_issuer_t::username_claim.
Referenced by reg_kv().
reg_kv()
static int reg_kv (void * u, const char * section, const char * key, const char * val) static
Definition at line 126 of file issuer_registry.c.
References brix_token_issuer_t::audience_count, brix_token_issuer_t::audiences, brix_token_issuer_t::base_path_count, brix_token_issuer_t::base_paths, BRIX_TOKEN_MAX_AUDIENCES, BRIX_TOKEN_MAX_BASEPATHS, brix_token_strategy_parse(), copy_z(), brix_token_issuer_t::default_user, brix_token_issuer_t::enabled, eqi(), brix_token_registry_t::global_audience_count, brix_token_registry_t::global_audiences, brix_token_issuer_t::groups_claim, brix_token_issuer_t::issuer, brix_token_issuer_t::jwks_path, key, brix_token_registry_t::log, brix_token_issuer_t::map_subject, brix_token_issuer_t::name_mapfile, brix_token_issuer_t::onmissing_fail, parse_bool(), reg_add_aud(), reg_add_list(), reg_issuer_for(), brix_token_issuer_t::restricted_path_count, brix_token_issuer_t::restricted_paths, brix_token_issuer_t::strategy, and brix_token_issuer_t::username_claim.
Referenced by brix_token_registry_load().