nginx-xrootd: src/auth/token/issuer_registry.h File Reference
issuer_registry.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include "token.h"
Data Structures
struct brix_token_issuer_t
struct brix_token_registry_t
Macros
#define BRIX_TOKEN_MAX_ISSUERS 16
#define BRIX_TOKEN_MAX_BASEPATHS 8
#define BRIX_TOKEN_MAX_AUDIENCES 8
#define BRIX_AUTHZ_CAPABILITY 0x1u /* WLCG storage.* scopes (default) */
#define BRIX_AUTHZ_GROUP 0x2u /* groups_claim ∈ authdb groups (W1b)*/
#define BRIX_AUTHZ_MAPPING 0x4u /* subject→authdb user rules (W1b)*/
Functions
ngx_int_t brix_token_registry_load (brix_token_registry_t *reg, const char *cfg_path, uint32_t default_strategy, char *errbuf, size_t errlen)
const brix_token_issuer_t * brix_token_registry_find (const brix_token_registry_t *reg, const char *iss)
int brix_token_issuer_path_ok (const brix_token_issuer_t *is, const char *req_path)
uint32_t brix_token_strategy_parse (const char *value)
ngx_int_t brix_token_registry_build (ngx_conf_t *cf, const char *cfg_path, uint32_t default_strategy, brix_token_registry_t **out)
int brix_token_validate_registry (ngx_log_t *log, const char *token, size_t token_len, const brix_token_registry_t *reg, const char *req_path, brix_token_op_e op, const u_char *macaroon_secret, size_t secret_len, int clock_skew, brix_token_claims_t *claims, int *out_issuer_bucket)
int brix_token_validate_registry_authn (ngx_log_t *log, const char *token, size_t token_len, const brix_token_registry_t *reg, const u_char *macaroon_secret, size_t secret_len, int clock_skew, brix_token_claims_t *claims, const brix_token_issuer_t **out_issuer)
int brix_token_authz_strategy (const brix_token_issuer_t *is, const brix_token_claims_t *claims, const char *req_path, brix_token_op_e op)
Macro Definition Documentation
BRIX_AUTHZ_CAPABILITY
#define BRIX_AUTHZ_CAPABILITY 0x1u /* WLCG storage.* scopes (default) */
Definition at line 25 of file issuer_registry.h.
BRIX_AUTHZ_GROUP
#define BRIX_AUTHZ_GROUP 0x2u /* groups_claim ∈ authdb groups (W1b)*/
Definition at line 26 of file issuer_registry.h.
BRIX_AUTHZ_MAPPING
#define BRIX_AUTHZ_MAPPING 0x4u /* subject→authdb user rules (W1b)*/
Definition at line 27 of file issuer_registry.h.
BRIX_TOKEN_MAX_AUDIENCES
#define BRIX_TOKEN_MAX_AUDIENCES 8
Definition at line 21 of file issuer_registry.h.
BRIX_TOKEN_MAX_BASEPATHS
#define BRIX_TOKEN_MAX_BASEPATHS 8
Definition at line 20 of file issuer_registry.h.
BRIX_TOKEN_MAX_ISSUERS
#define BRIX_TOKEN_MAX_ISSUERS 16
Definition at line 19 of file issuer_registry.h.
Function Documentation
brix_token_authz_strategy()
int brix_token_authz_strategy (const brix_token_issuer_t * is, const brix_token_claims_t * claims, const char * req_path, brix_token_op_e op)
Definition at line 581 of file validate.c.
References BRIX_AUTHZ_CAPABILITY, BRIX_AUTHZ_GROUP, BRIX_AUTHZ_MAPPING, brix_subject_mapfile_lookup(), brix_token_check_read(), brix_token_check_write(), brix_token_issuer_path_ok(), BRIX_TOKEN_OP_WRITE, brix_token_issuer_t::default_user, brix_token_claims_t::groups, brix_token_issuer_t::map_subject, brix_token_issuer_t::name_mapfile, brix_token_issuer_t::onmissing_fail, brix_token_claims_t::scope_count, brix_token_claims_t::scopes, brix_token_issuer_t::strategy, and brix_token_claims_t::sub.
Referenced by brix_identity_check_token_scope(), and brix_token_validate_registry().
brix_token_issuer_path_ok()
int brix_token_issuer_path_ok (const brix_token_issuer_t * is, const char * req_path)
Definition at line 287 of file issuer_registry.c.
References brix_token_issuer_t::base_path_count, brix_token_issuer_t::base_paths, brix_token_scope_path_matches(), brix_token_issuer_t::restricted_path_count, and brix_token_issuer_t::restricted_paths.
Referenced by brix_token_authz_strategy().
brix_token_registry_build()
ngx_int_t brix_token_registry_build (ngx_conf_t * cf, const char * cfg_path, uint32_t default_strategy, brix_token_registry_t ** out)
Definition at line 234 of file issuer_registry.c.
References brix_jwks_register_cleanup(), brix_token_registry_load(), brix_token_registry_t::count, brix_token_registry_t::issuers, brix_token_issuer_t::jwks_key_count, brix_token_issuer_t::jwks_keys, brix_token_registry_t::log, and ngx_pcalloc().
Referenced by brix_configure_token_auth(), ngx_http_brix_cvmfs_merge_loc_conf(), and ngx_http_brix_webdav_merge_loc_conf().
brix_token_registry_find()
const brix_token_issuer_t * brix_token_registry_find (const brix_token_registry_t * reg, const char * iss)
Definition at line 272 of file issuer_registry.c.
References brix_token_registry_t::count, brix_token_issuer_t::enabled, brix_token_issuer_t::issuer, and brix_token_registry_t::issuers.
Referenced by brix_token_validate_registry_authn().
brix_token_registry_load()
ngx_int_t brix_token_registry_load (brix_token_registry_t * reg, const char * cfg_path, uint32_t default_strategy, char * errbuf, size_t errlen)
Definition at line 186 of file issuer_registry.c.
References brix_token_issuer_t::base_path_count, brix_ini_parse_file(), brix_jwks_load(), BRIX_MAX_JWKS_KEYS, brix_token_registry_t::count, brix_token_registry_t::default_strategy, brix_token_issuer_t::issuer, brix_token_registry_t::issuers, brix_token_issuer_t::jwks_key_count, brix_token_issuer_t::jwks_keys, brix_token_issuer_t::jwks_mtime, brix_token_issuer_t::jwks_path, brix_token_registry_t::log, brix_token_issuer_t::name, reg_kv(), and stat().
Referenced by brix_token_registry_build().
brix_token_strategy_parse()
uint32_t brix_token_strategy_parse (const char * value)
Definition at line 45 of file issuer_registry.c.
References BRIX_AUTHZ_CAPABILITY, BRIX_AUTHZ_GROUP, BRIX_AUTHZ_MAPPING, copy_z(), and eqi().
Referenced by reg_kv().
brix_token_validate_registry()
int brix_token_validate_registry (ngx_log_t * log, const char * token, size_t token_len, const brix_token_registry_t * reg, const char * req_path, brix_token_op_e op, const u_char * macaroon_secret, size_t secret_len, int clock_skew, brix_token_claims_t * claims, int * out_issuer_bucket)
Definition at line 637 of file validate.c.
References brix_token_authz_strategy(), brix_token_validate_registry_authn(), log, brix_token_issuer_t::metric_bucket, and brix_token_issuer_t::name.
Referenced by scvmfs_check_bearer(), and webdav_verify_bearer_token().
brix_token_validate_registry_authn()
int brix_token_validate_registry_authn (ngx_log_t * log, const char * token, size_t token_len, const brix_token_registry_t * reg, const u_char * macaroon_secret, size_t secret_len, int clock_skew, brix_token_claims_t * claims, const brix_token_issuer_t ** out_issuer)
Definition at line 515 of file validate.c.
References brix_token_claims_t::aud, brix_token_issuer_t::audience_count, brix_token_issuer_t::audiences, brix_token_peek_iss(), brix_token_registry_find(), brix_token_validate(), brix_token_registry_t::global_audience_count, brix_token_registry_t::global_audiences, brix_token_issuer_t::issuer, brix_token_issuer_t::jwks_key_count, brix_token_issuer_t::jwks_keys, log, brix_token_issuer_t::name, and token_sanitize_for_log().
Referenced by brix_handle_token_auth(), and brix_token_validate_registry().