nginx-xrootd: src/auth/token/json.h File Reference
json.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>
Functions
ssize_t json_get_string (const char *json, size_t json_len, const char *key, char *out, size_t out_max)
int json_get_string_array (const char *json, size_t json_len, const char *key, char out[][256], int max_items)
int json_get_int64 (const char *json, size_t json_len, const char *key, int64_t *out)
int json_string_or_array_contains (const char *json, size_t json_len, const char *key, const char *needle)
int json_has_member (const char *json, size_t json_len, const char *key)
const char * json_backend_name (void)
Function Documentation
json_backend_name()
const char * json_backend_name (void)
Definition at line 276 of file json.c.
json_get_int64()
int json_get_int64 (const char * json, size_t json_len, const char * key, int64_t * out)
Definition at line 129 of file json.c.
References key.
Referenced by token_extract_claims().
json_get_string()
ssize_t json_get_string (const char * json, size_t json_len, const char * key, char * out, size_t out_max)
Definition at line 20 of file json.c.
References key.
Referenced by brix_subject_mapfile_lookup(), brix_token_peek_iss(), token_check_header(), and token_extract_claims().
json_get_string_array()
int json_get_string_array (const char * json, size_t json_len, const char * key, char out[][256], int max_items)
Definition at line 67 of file json.c.
References key.
Referenced by brix_token_extract_groups(), and token_extract_claims().
json_has_member()
int json_has_member (const char * json, size_t json_len, const char * key)
Definition at line 244 of file json.c.
References key.
Referenced by token_check_header().
json_string_or_array_contains()
int json_string_or_array_contains (const char * json, size_t json_len, const char * key, const char * needle)
Definition at line 196 of file json.c.
References key.
Referenced by token_check_issuer_audience().