nginx-xrootd: src/core/compat/json_min.c File Reference
json_min.c File Reference
#include "json_min.h"
#include <string.h>
#include <stdint.h>
Functions
static void jm_put (char *out, size_t outsz, size_t *pos, char c)
static void jm_put_utf8 (char *out, size_t outsz, size_t *pos, uint32_t cp)
static int jm_hex (char c)
static int jm_u16 (const char *p)
static const char * jm_skip_ws (const char *p, const char *end)
static uint32_t jm_utf16_pair (int hi, int lo)
static int jm_unescape_u (const char **pp, const char *end, char *out, size_t outsz, size_t *pos)
static int jm_unescape_char (const char **pp, const char *end, char *out, size_t outsz, size_t *pos)
static const char * jm_string (const char *p, const char *end, char *out, size_t outsz, size_t *outlen)
static const char * jm_skip_container (const char *p, const char *end)
static const char * jm_skip_scalar (const char *p, const char *end)
static const char * jm_skip_value (const char *p, const char *end)
static int jm_member_key (const char **pp, const char *end, char *kbuf, size_t kbufsz, size_t *klen)
static int jm_emit_value (const char *p, const char *end, char *out, size_t outsz)
int brix_json_get_str (const char *json, size_t len, const char *key, char *out, size_t outsz)
Function Documentation
brix_json_get_str()
int brix_json_get_str (const char * json, size_t len, const char * key, char * out, size_t outsz)
Definition at line 395 of file json_min.c.
References jm_emit_value(), jm_member_key(), jm_skip_value(), jm_skip_ws(), and key.
Referenced by json_str(), and webdav_handle_macaroon_request().
jm_emit_value()
static int jm_emit_value (const char * p, const char * end, char * out, size_t outsz) static
Definition at line 369 of file json_min.c.
References jm_skip_value(), and jm_string().
Referenced by brix_json_get_str().
jm_hex()
static int jm_hex (char c) static
Definition at line 47 of file json_min.c.
References c.
Referenced by jm_u16().
jm_member_key()
static int jm_member_key (const char ** pp, const char * end, char * kbuf, size_t kbufsz, size_t * klen) static
Definition at line 324 of file json_min.c.
References jm_skip_ws(), and jm_string().
Referenced by brix_json_get_str().
jm_put()
static void jm_put (char * out, size_t outsz, size_t * pos, char c) static
Definition at line 16 of file json_min.c.
References c.
Referenced by jm_put_utf8(), jm_string(), and jm_unescape_char().
jm_put_utf8()
static void jm_put_utf8 (char * out, size_t outsz, size_t * pos, uint32_t cp) static
Definition at line 26 of file json_min.c.
References jm_put().
Referenced by jm_unescape_u().
jm_skip_container()
static const char * jm_skip_container (const char * p, const char * end) static
Definition at line 244 of file json_min.c.
References c, and jm_string().
Referenced by jm_skip_value().
jm_skip_scalar()
static const char * jm_skip_scalar (const char * p, const char * end) static
Definition at line 282 of file json_min.c.
Referenced by jm_skip_value().
jm_skip_value()
static const char * jm_skip_value (const char * p, const char * end) static
Definition at line 293 of file json_min.c.
References jm_skip_container(), jm_skip_scalar(), and jm_string().
Referenced by brix_json_get_str(), and jm_emit_value().
jm_skip_ws()
static const char * jm_skip_ws (const char * p, const char * end) static
Definition at line 67 of file json_min.c.
Referenced by brix_json_get_str(), and jm_member_key().
jm_string()
static const char * jm_string (const char * p, const char * end, char * out, size_t outsz, size_t * outlen) static
Definition at line 193 of file json_min.c.
References c, jm_put(), and jm_unescape_char().
Referenced by jm_emit_value(), jm_member_key(), jm_skip_container(), and jm_skip_value().
jm_u16()
static int jm_u16 (const char * p) static
Definition at line 57 of file json_min.c.
References c, and jm_hex().
Referenced by jm_unescape_u().
jm_unescape_char()
static int jm_unescape_char (const char ** pp, const char * end, char * out, size_t outsz, size_t * pos) static
Definition at line 154 of file json_min.c.
References jm_put(), and jm_unescape_u().
Referenced by jm_string().
jm_unescape_u()
static int jm_unescape_u (const char ** pp, const char * end, char * out, size_t outsz, size_t * pos) static
Definition at line 110 of file json_min.c.
References jm_put_utf8(), jm_u16(), and jm_utf16_pair().
Referenced by jm_unescape_char().
jm_utf16_pair()
static uint32_t jm_utf16_pair (int hi, int lo) static
Definition at line 87 of file json_min.c.
Referenced by jm_unescape_u().