nginx-xrootd: client/lib/cli/jsonout.c File Reference
jsonout.c File Reference
#include "cli/jsonout.h"
Functions
void brix_json_escape (FILE *out, const char *s)
void brix_json_fputs (FILE *out, const char *s)
void brix_json_kv_str (FILE *out, const char *k, const char *v, int comma)
void brix_json_kv_ll (FILE *out, const char *k, long long v, int comma)
void brix_json_kv_bool (FILE *out, const char *k, int v, int comma)
Function Documentation
brix_json_escape()
void brix_json_escape (FILE * out, const char * s)
Definition at line 18 of file jsonout.c.
References s.
Referenced by brix_json_fputs().
brix_json_fputs()
void brix_json_fputs (FILE * out, const char * s)
Definition at line 50 of file jsonout.c.
References brix_json_escape(), and s.
Referenced by brix_json_kv_bool(), brix_json_kv_ll(), brix_json_kv_str(), emit_json_bool_or_null(), and fjson_str().
brix_json_kv_bool()
void brix_json_kv_bool (FILE * out, const char * k, int v, int comma)
Definition at line 102 of file jsonout.c.
References brix_json_fputs().
Referenced by chk_emit_json(), json_statinfo(), and ls_json_dir().
brix_json_kv_ll()
void brix_json_kv_ll (FILE * out, const char * k, long long v, int comma)
Definition at line 86 of file jsonout.c.
References brix_json_fputs().
Referenced by chk_emit_json(), du_print(), json_statinfo(), and ls_json_dir().
brix_json_kv_str()
void brix_json_kv_str (FILE * out, const char * k, const char * v, int comma)
Definition at line 67 of file jsonout.c.
References brix_json_fputs().
Referenced by chk_emit_json(), du_print(), json_statinfo(), ls_json_dir(), and topo_emit_json().