nginx-xrootd: src/auth/token/jwks.c File Reference
jwks.c File Reference
#include "token_internal.h"
#include "json.h"
#include "core/compat/log_diag.h"
#include "core/compat/safe_size.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <jansson.h>
Data Structures
struct brix_jwks_cleanup_t
Macros
#define JWKS_STRING_FIELD(obj, field) (v = json_object_get((obj), (field)), json_is_string(v) ? json_string_value(v) : "")
Functions
static int brix_jwks_store_rsa (ngx_log_t *log, const char *kid, const char *n_b64, const char *e_b64, brix_jwks_key_t *dest)
static int brix_jwks_store_ec (ngx_log_t *log, const char *kid, const char *x_b64, const char *y_b64, brix_jwks_key_t *dest)
static int brix_jwks_process_item (ngx_log_t *log, json_t *item, brix_jwks_key_t *dest)
static int brix_jwks_load_jansson (ngx_log_t *log, const char *path, const char *buf, size_t len, brix_jwks_key_t *keys, int max_keys)
int brix_jwks_load (ngx_log_t *log, const char *path, brix_jwks_key_t *keys, int max_keys)
static void brix_jwks_pool_cleanup (void *data)
ngx_int_t brix_jwks_register_cleanup (ngx_pool_t *pool, brix_jwks_key_t *keys, int *count)
void brix_jwks_free (brix_jwks_key_t *keys, int count)
Macro Definition Documentation
JWKS_STRING_FIELD
#define JWKS_STRING_FIELD (obj, field) (v = json_object_get((obj), (field)), json_is_string(v) ? json_string_value(v) : "")
Function Documentation
brix_jwks_free()
void brix_jwks_free (brix_jwks_key_t * keys, int count)
Definition at line 326 of file jwks.c.
References brix_jwks_key_t::pkey.
Referenced by brix_jwks_pool_cleanup(), and brix_token_jwks_try_reload().
brix_jwks_load()
int brix_jwks_load (ngx_log_t * log, const char * path, brix_jwks_key_t * keys, int max_keys)
Definition at line 212 of file jwks.c.
References BRIX_DIAG_ERR, brix_jwks_load_jansson(), brix_size_add(), and log.
Referenced by brix_token_jwks_try_reload(), brix_token_load_and_register_jwks(), brix_token_registry_load(), s3_merge_token(), and webdav_merge_auth_token_conf().
brix_jwks_load_jansson()
static int brix_jwks_load_jansson (ngx_log_t * log, const char * path, const char * buf, size_t len, brix_jwks_key_t * keys, int max_keys) static
Definition at line 152 of file jwks.c.
References BRIX_DIAG_ERR, brix_jwks_process_item(), and log.
Referenced by brix_jwks_load().
brix_jwks_pool_cleanup()
static void brix_jwks_pool_cleanup (void * data) static
Definition at line 298 of file jwks.c.
References brix_jwks_free(), and c.
Referenced by brix_jwks_register_cleanup().
brix_jwks_process_item()
static int brix_jwks_process_item (ngx_log_t * log, json_t * item, brix_jwks_key_t * dest) static
Definition at line 117 of file jwks.c.
References brix_jwks_store_ec(), brix_jwks_store_rsa(), JWKS_STRING_FIELD, and log.
Referenced by brix_jwks_load_jansson().
brix_jwks_register_cleanup()
ngx_int_t brix_jwks_register_cleanup (ngx_pool_t * pool, brix_jwks_key_t * keys, int * count)
Definition at line 306 of file jwks.c.
References brix_jwks_pool_cleanup(), and c.
Referenced by brix_token_load_and_register_jwks(), brix_token_registry_build(), s3_merge_token(), and webdav_merge_auth_token_conf().
brix_jwks_store_ec()
static int brix_jwks_store_ec (ngx_log_t * log, const char * kid, const char * x_b64, const char * y_b64, brix_jwks_key_t * dest) static
Definition at line 79 of file jwks.c.
References brix_token_ec_pubkey_from_xy(), brix_jwks_key_t::kid, log, and brix_jwks_key_t::pkey.
Referenced by brix_jwks_process_item().
brix_jwks_store_rsa()
static int brix_jwks_store_rsa (ngx_log_t * log, const char * kid, const char * n_b64, const char * e_b64, brix_jwks_key_t * dest) static
Definition at line 43 of file jwks.c.
References brix_token_rsa_pubkey_from_ne(), brix_jwks_key_t::kid, log, and brix_jwks_key_t::pkey.
Referenced by brix_jwks_process_item().