nginx-xrootd: src/auth/token/jwt_sign.h File Reference
jwt_sign.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <openssl/evp.h>
Functions
EVP_PKEY * brix_jwt_load_ec_key (const char *pem_path)
ngx_int_t brix_jwt_sign_es256 (EVP_PKEY *eckey, const char *header_json, const char *payload_json, char *out, size_t outsz)
Function Documentation
brix_jwt_load_ec_key()
EVP_PKEY * brix_jwt_load_ec_key (const char * pem_path)
Definition at line 22 of file jwt_sign.c.
Referenced by brix_cache_pelican_schedule_advertise().
brix_jwt_sign_es256()
ngx_int_t brix_jwt_sign_es256 (EVP_PKEY * eckey, const char * header_json, const char * payload_json, char * out, size_t outsz)
Definition at line 71 of file jwt_sign.c.
References b64url_encode(), and brix_jwt_der_to_p1363().
Referenced by brix_pelican_build_jwt().