nginx-xrootd: src/tpc/engine/key_registry.c File Reference
key_registry.c File Reference
#include "key_registry.h"
#include "core/compat/shm_slots.h"
#include <string.h>
#include <openssl/crypto.h>
Functions
static int tpc_key_eq (const char *stored, const char *presented)
static brix_tpc_key_table_t * key_table (void)
static ngx_int_t brix_tpc_key_shm_init_zone (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t brix_tpc_key_configure_registry (ngx_conf_t *cf)
void brix_tpc_generate_key (char *buf, size_t buf_sz)
void brix_tpc_key_register (const char *key, ngx_msec_t ttl_ms)
int brix_tpc_key_validate (const char *key)
int brix_tpc_key_consume (const char *key)
void brix_tpc_key_remove (const char *key)
Variables
static ngx_shm_zone_t * brix_tpc_key_shm_zone
static ngx_shmtx_t brix_tpc_key_mutex
static ngx_uint_t tpc_key_seq
Function Documentation
brix_tpc_generate_key()
void brix_tpc_generate_key (char * buf, size_t buf_sz)
Definition at line 151 of file key_registry.c.
References tpc_key_seq.
Referenced by tpc_handle_dest(), and tpc_init_dst_file().
brix_tpc_key_configure_registry()
ngx_int_t brix_tpc_key_configure_registry (ngx_conf_t * cf)
Definition at line 121 of file key_registry.c.
References brix_shm_zone_size(), brix_tpc_key_shm_init_zone(), brix_tpc_key_shm_zone, and ngx_stream_brix_module.
Referenced by postconf_shared_registries().
brix_tpc_key_consume()
int brix_tpc_key_consume (const char * key)
Definition at line 275 of file key_registry.c.
References brix_shm_slot_expired(), brix_tpc_key_mutex, BRIX_TPC_KEY_SLOTS, brix_tpc_key_entry_t::expiry, brix_tpc_key_entry_t::in_use, brix_tpc_key_entry_t::key, key, key_table(), brix_tpc_key_table_t::slots, and tpc_key_eq().
Referenced by tpc_handle_source().
brix_tpc_key_register()
void brix_tpc_key_register (const char * key, ngx_msec_t ttl_ms)
Definition at line 172 of file key_registry.c.
References brix_shm_remember_free_slot(), brix_shm_slot_expired(), brix_tpc_key_mutex, BRIX_TPC_KEY_SLOTS, brix_tpc_key_entry_t::expiry, brix_tpc_key_entry_t::in_use, brix_tpc_key_entry_t::key, key, key_table(), brix_tpc_key_table_t::slots, and tpc_key_eq().
Referenced by tpc_handle_dest(), and tpc_handle_source().
brix_tpc_key_remove()
void brix_tpc_key_remove (const char * key)
Definition at line 322 of file key_registry.c.
References brix_tpc_key_mutex, BRIX_TPC_KEY_SLOTS, brix_tpc_key_entry_t::in_use, brix_tpc_key_entry_t::key, key, key_table(), brix_tpc_key_table_t::slots, and tpc_key_eq().
brix_tpc_key_shm_init_zone()
static ngx_int_t brix_tpc_key_shm_init_zone (ngx_shm_zone_t * shm_zone, void * data) static
Definition at line 75 of file key_registry.c.
References brix_shm_table_alloc(), and brix_tpc_key_mutex.
Referenced by brix_tpc_key_configure_registry().
brix_tpc_key_validate()
int brix_tpc_key_validate (const char * key)
Definition at line 228 of file key_registry.c.
References brix_shm_slot_expired(), brix_tpc_key_mutex, BRIX_TPC_KEY_SLOTS, brix_tpc_key_entry_t::expiry, brix_tpc_key_entry_t::in_use, brix_tpc_key_entry_t::key, key, key_table(), brix_tpc_key_table_t::slots, and tpc_key_eq().
key_table()
static brix_tpc_key_table_t * key_table (void) static
Definition at line 52 of file key_registry.c.
References brix_tpc_key_shm_zone.
Referenced by brix_tpc_key_consume(), brix_tpc_key_register(), brix_tpc_key_remove(), and brix_tpc_key_validate().
tpc_key_eq()
static int tpc_key_eq (const char * stored, const char * presented) static
Definition at line 24 of file key_registry.c.
References BRIX_TPC_KEY_LEN, and ngx_memcpy.
Referenced by brix_tpc_key_consume(), brix_tpc_key_register(), brix_tpc_key_remove(), and brix_tpc_key_validate().
Variable Documentation
brix_tpc_key_mutex
ngx_shmtx_t brix_tpc_key_mutex static
Definition at line 38 of file key_registry.c.
Referenced by brix_tpc_key_consume(), brix_tpc_key_register(), brix_tpc_key_remove(), brix_tpc_key_shm_init_zone(), and brix_tpc_key_validate().
brix_tpc_key_shm_zone
ngx_shm_zone_t* brix_tpc_key_shm_zone static
Definition at line 37 of file key_registry.c.
Referenced by brix_tpc_key_configure_registry(), and key_table().
tpc_key_seq
ngx_uint_t tpc_key_seq static
Definition at line 39 of file key_registry.c.
Referenced by brix_tpc_generate_key().