nginx-xrootd: src/tpc/engine/key_registry.h File Reference
key_registry.h File Reference
#include "core/ngx_brix_module.h"
Data Structures
struct brix_tpc_key_entry_t
struct brix_tpc_key_table_t
Macros
#define BRIX_TPC_KEY_SLOTS 256
#define BRIX_TPC_KEY_LEN 128
#define BRIX_TPC_KEY_TTL_MS 60000 /* 60 seconds */
Functions
ngx_int_t brix_tpc_key_configure_registry (ngx_conf_t *cf)
void brix_tpc_generate_key (char *buf, size_t buf_sz)
void brix_tpc_key_register (const char *key, ngx_msec_t ttl_ms)
int brix_tpc_key_validate (const char *key)
int brix_tpc_key_consume (const char *key)
void brix_tpc_key_remove (const char *key)
Macro Definition Documentation
BRIX_TPC_KEY_LEN
#define BRIX_TPC_KEY_LEN 128
Definition at line 23 of file key_registry.h.
BRIX_TPC_KEY_SLOTS
#define BRIX_TPC_KEY_SLOTS 256
Definition at line 22 of file key_registry.h.
BRIX_TPC_KEY_TTL_MS
#define BRIX_TPC_KEY_TTL_MS 60000 /* 60 seconds */
Definition at line 24 of file key_registry.h.
Function Documentation
brix_tpc_generate_key()
void brix_tpc_generate_key (char * buf, size_t buf_sz)
Definition at line 151 of file key_registry.c.
References tpc_key_seq.
Referenced by tpc_handle_dest(), and tpc_init_dst_file().
brix_tpc_key_configure_registry()
ngx_int_t brix_tpc_key_configure_registry (ngx_conf_t * cf)
Definition at line 121 of file key_registry.c.
References brix_shm_zone_size(), brix_tpc_key_shm_init_zone(), brix_tpc_key_shm_zone, and ngx_stream_brix_module.
Referenced by postconf_shared_registries().
brix_tpc_key_consume()
int brix_tpc_key_consume (const char * key)
Definition at line 275 of file key_registry.c.
References brix_shm_slot_expired(), brix_tpc_key_mutex, BRIX_TPC_KEY_SLOTS, brix_tpc_key_entry_t::expiry, brix_tpc_key_entry_t::in_use, brix_tpc_key_entry_t::key, key, key_table(), brix_tpc_key_table_t::slots, and tpc_key_eq().
Referenced by tpc_handle_source().
brix_tpc_key_register()
void brix_tpc_key_register (const char * key, ngx_msec_t ttl_ms)
Definition at line 172 of file key_registry.c.
References brix_shm_remember_free_slot(), brix_shm_slot_expired(), brix_tpc_key_mutex, BRIX_TPC_KEY_SLOTS, brix_tpc_key_entry_t::expiry, brix_tpc_key_entry_t::in_use, brix_tpc_key_entry_t::key, key, key_table(), brix_tpc_key_table_t::slots, and tpc_key_eq().
Referenced by tpc_handle_dest(), and tpc_handle_source().
brix_tpc_key_remove()
void brix_tpc_key_remove (const char * key)
Definition at line 322 of file key_registry.c.
References brix_tpc_key_mutex, BRIX_TPC_KEY_SLOTS, brix_tpc_key_entry_t::in_use, brix_tpc_key_entry_t::key, key, key_table(), brix_tpc_key_table_t::slots, and tpc_key_eq().
brix_tpc_key_validate()
int brix_tpc_key_validate (const char * key)
Definition at line 228 of file key_registry.c.
References brix_shm_slot_expired(), brix_tpc_key_mutex, BRIX_TPC_KEY_SLOTS, brix_tpc_key_entry_t::expiry, brix_tpc_key_entry_t::in_use, brix_tpc_key_entry_t::key, key, key_table(), brix_tpc_key_table_t::slots, and tpc_key_eq().