nginx-xrootd: src/auth/gsi/keypool.h File Reference
keypool.h File Reference
#include "gsi_internal.h"
Functions
EVP_PKEY * brix_gsi_dh_keygen (void)
void brix_gsi_keypool_init (ngx_cycle_t *cycle, ngx_thread_pool_t *pool, ngx_uint_t target, ngx_uint_t seed)
ngx_int_t brix_gsi_keypool_pop (ngx_thread_pool_t *pool, ngx_log_t *log, EVP_PKEY **out)
Function Documentation
brix_gsi_dh_keygen()
EVP_PKEY * brix_gsi_dh_keygen (void)
Definition at line 9 of file gsi_dh.c.
brix_gsi_keypool_init()
void brix_gsi_keypool_init (ngx_cycle_t * cycle, ngx_thread_pool_t * pool, ngx_uint_t target, ngx_uint_t seed)
Definition at line 132 of file keypool.c.
References brix_gsi_dh_keygen(), BRIX_GSI_KEYPOOL_CAP, brix_kp_count, brix_kp_log, brix_kp_pool, brix_kp_ring, brix_kp_schedule_refill(), and brix_kp_target.
Referenced by brix_init_gsi_keypool().
brix_gsi_keypool_pop()
ngx_int_t brix_gsi_keypool_pop (ngx_thread_pool_t * pool, ngx_log_t * log, EVP_PKEY ** out)
Definition at line 182 of file keypool.c.
References brix_kp_count, brix_kp_log, brix_kp_low_water(), brix_kp_refill_pending, brix_kp_ring, brix_kp_schedule_refill(), and log.
Referenced by gsi_build_dh_public().