nginx-xrootd: src/auth/gsi/keypool.c File Reference
keypool.c File Reference
#include "keypool.h"
#include "gsi_core.h"
#include "core/aio/aio.h"
#include "core/types/tunables.h"
#include <openssl/evp.h>
#include <openssl/params.h>
Data Structures
struct brix_gsi_refill_t
Functions
static ngx_uint_t brix_kp_low_water (void)
static void brix_kp_refill_thread (void *data, ngx_log_t *log)
static void brix_kp_schedule_refill (ngx_thread_pool_t *pool)
static void brix_kp_refill_done (ngx_event_t *ev)
void brix_gsi_keypool_init (ngx_cycle_t *cycle, ngx_thread_pool_t *pool, ngx_uint_t target, ngx_uint_t seed)
ngx_int_t brix_gsi_keypool_pop (ngx_thread_pool_t *pool, ngx_log_t *log, EVP_PKEY **out)
Variables
static EVP_PKEY * brix_kp_ring [256]
static ngx_uint_t brix_kp_count
static ngx_uint_t brix_kp_target = 64
static ngx_uint_t brix_kp_refill_pending
static ngx_uint_t brix_kp_warmed_logged
static ngx_thread_pool_t * brix_kp_pool
static ngx_log_t * brix_kp_log
Function Documentation
brix_gsi_keypool_init()
void brix_gsi_keypool_init (ngx_cycle_t * cycle, ngx_thread_pool_t * pool, ngx_uint_t target, ngx_uint_t seed)
Definition at line 132 of file keypool.c.
References brix_gsi_dh_keygen(), BRIX_GSI_KEYPOOL_CAP, brix_kp_count, brix_kp_log, brix_kp_pool, brix_kp_ring, brix_kp_schedule_refill(), and brix_kp_target.
Referenced by ngx_stream_brix_init_process().
brix_gsi_keypool_pop()
ngx_int_t brix_gsi_keypool_pop (ngx_thread_pool_t * pool, ngx_log_t * log, EVP_PKEY ** out)
Definition at line 182 of file keypool.c.
References brix_kp_count, brix_kp_log, brix_kp_low_water(), brix_kp_refill_pending, brix_kp_ring, brix_kp_schedule_refill(), and log.
Referenced by brix_gsi_send_cert().
brix_kp_low_water()
static ngx_uint_t brix_kp_low_water (void) inline static
Definition at line 37 of file keypool.c.
References brix_kp_target.
Referenced by brix_gsi_keypool_pop().
brix_kp_refill_done()
static void brix_kp_refill_done (ngx_event_t * ev) static
Definition at line 75 of file keypool.c.
References brix_kp_count, brix_kp_log, brix_kp_pool, brix_kp_refill_pending, brix_kp_ring, brix_kp_schedule_refill(), brix_kp_target, brix_kp_warmed_logged, brix_gsi_refill_t::keys, and brix_gsi_refill_t::n.
Referenced by brix_kp_schedule_refill().
brix_kp_refill_thread()
static void brix_kp_refill_thread (void * data, ngx_log_t * log) static
Definition at line 54 of file keypool.c.
References brix_gsi_dh_keygen(), BRIX_GSI_KEYPOOL_REFILL_BATCH, brix_gsi_refill_t::keys, log, and brix_gsi_refill_t::n.
Referenced by brix_kp_schedule_refill().
brix_kp_schedule_refill()
static void brix_kp_schedule_refill (ngx_thread_pool_t * pool) static
Definition at line 111 of file keypool.c.
References brix_kp_log, brix_kp_refill_done(), brix_kp_refill_pending, and brix_kp_refill_thread().
Referenced by brix_gsi_keypool_init(), brix_gsi_keypool_pop(), and brix_kp_refill_done().
Variable Documentation
brix_kp_count
ngx_uint_t brix_kp_count static
Definition at line 28 of file keypool.c.
Referenced by brix_gsi_keypool_init(), brix_gsi_keypool_pop(), and brix_kp_refill_done().
brix_kp_log
ngx_log_t* brix_kp_log static
Definition at line 33 of file keypool.c.
Referenced by brix_gsi_keypool_init(), brix_gsi_keypool_pop(), brix_kp_refill_done(), and brix_kp_schedule_refill().
brix_kp_pool
ngx_thread_pool_t* brix_kp_pool static
Definition at line 32 of file keypool.c.
Referenced by brix_gsi_keypool_init(), and brix_kp_refill_done().
brix_kp_refill_pending
ngx_uint_t brix_kp_refill_pending static
Definition at line 30 of file keypool.c.
Referenced by brix_gsi_keypool_pop(), brix_kp_refill_done(), and brix_kp_schedule_refill().
brix_kp_ring
EVP_PKEY* brix_kp_ring[256] static
Definition at line 27 of file keypool.c.
Referenced by brix_gsi_keypool_init(), brix_gsi_keypool_pop(), and brix_kp_refill_done().
brix_kp_target
ngx_uint_t brix_kp_target = 64 static
Definition at line 29 of file keypool.c.
Referenced by brix_gsi_keypool_init(), brix_kp_low_water(), and brix_kp_refill_done().
brix_kp_warmed_logged
ngx_uint_t brix_kp_warmed_logged static
Definition at line 31 of file keypool.c.
Referenced by brix_kp_refill_done().