nginx-xrootd: src/core/shm/kv.c File Reference
kv.c File Reference
#include "core/ngx_brix_module.h"
#include "kv.h"
#include "core/compat/shm_slots.h"
#include "core/compat/alloc_guard.h"
Data Structures
struct brix_kv_header_t
struct brix_kv_entry_t
Functions
static uint64_t brix_kv_hash (const void *key, size_t len)
static uint32_t brix_kv_floor_pow2 (size_t n)
static brix_kv_header_t * brix_kv_hdr (brix_kv_t *kv)
static brix_kv_entry_t * brix_kv_slot (brix_kv_header_t *h, size_t stride, uint32_t i)
static ngx_uint_t brix_kv_should_shift (uint32_t home, uint32_t hole, uint32_t cur)
static void brix_kv_remove_at (brix_kv_header_t *h, size_t stride, uint32_t mask, uint32_t hole)
static ngx_int_t brix_kv_init_zone (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t brix_kv_configure (ngx_conf_t *cf, brix_kv_t *kv, ngx_str_t *name, size_t size, size_t key_max, size_t val_max, void *module)
int brix_kv_get (brix_kv_t *kv, const void *key, size_t key_len, void *out, size_t *out_len)
ngx_int_t brix_kv_set (brix_kv_t *kv, const void *key, size_t key_len, const void *val, size_t val_len, ngx_msec_t ttl_ms)
void brix_kv_delete (brix_kv_t *kv, const void *key, size_t key_len)
void brix_kv_stats (brix_kv_t *kv, brix_kv_stats_t *out)
brix_kv_t * brix_kv_find (const ngx_str_t *name)
ngx_uint_t brix_kv_zone_count (void)
brix_kv_t * brix_kv_zone_get (ngx_uint_t i)
char * brix_kv_zone_directive (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Variables
ngx_module_t ngx_http_brix_webdav_module
static brix_kv_t * brix_kv_zones [16]
static ngx_uint_t brix_kv_nzones
Function Documentation
brix_kv_configure()
ngx_int_t brix_kv_configure (ngx_conf_t * cf, brix_kv_t * kv, ngx_str_t * name, size_t size, size_t key_max, size_t val_max, void * module)
Definition at line 192 of file kv.c.
References brix_kv_floor_pow2(), brix_kv_init_zone(), BRIX_KV_MAX_ZONES, BRIX_KV_MIN_SIZE, brix_kv_nzones, brix_kv_zones, brix_shm_zone_size(), and name.
Referenced by brix_kv_zone_directive().
brix_kv_delete()
void brix_kv_delete (brix_kv_t * kv, const void * key, size_t key_len)
Definition at line 380 of file kv.c.
References brix_kv_hash(), brix_kv_hdr(), brix_kv_remove_at(), brix_kv_slot(), brix_kv_header_t::capacity, brix_kv_header_t::count, brix_kv_entry_t::hash, key, and brix_kv_entry_t::key_len.
brix_kv_find()
brix_kv_t * brix_kv_find (const ngx_str_t * name)
Definition at line 440 of file kv.c.
References brix_kv_nzones, brix_kv_zones, and name.
Referenced by brix_auth_cache_directive(), brix_kv_zone_directive(), brix_rate_limit_directive(), brix_token_cache_directive(), and webdav_conf_revoke_cache().
brix_kv_floor_pow2()
static uint32_t brix_kv_floor_pow2 (size_t n) static
Definition at line 74 of file kv.c.
Referenced by brix_kv_configure().
brix_kv_get()
int brix_kv_get (brix_kv_t * kv, const void * key, size_t key_len, void * out, size_t * out_len)
Definition at line 253 of file kv.c.
References brix_kv_hash(), brix_kv_hdr(), brix_kv_remove_at(), brix_kv_slot(), brix_kv_header_t::capacity, brix_kv_header_t::count, brix_kv_header_t::evictions, brix_kv_entry_t::expires, brix_kv_entry_t::hash, brix_kv_header_t::hits, key, brix_kv_entry_t::key_len, brix_kv_header_t::misses, and brix_kv_entry_t::val_len.
Referenced by brix_auth_gate_op(), brix_rate_limit_check(), brix_token_cache_lookup(), and webdav_introspect_access_handler().
brix_kv_hash()
static uint64_t brix_kv_hash (const void * key, size_t len) static
Definition at line 60 of file kv.c.
References key.
Referenced by brix_kv_delete(), brix_kv_get(), and brix_kv_set().
brix_kv_hdr()
static brix_kv_header_t * brix_kv_hdr (brix_kv_t * kv) static
Definition at line 88 of file kv.c.
Referenced by brix_kv_delete(), brix_kv_get(), brix_kv_set(), and brix_kv_stats().
brix_kv_init_zone()
static ngx_int_t brix_kv_init_zone (ngx_shm_zone_t * shm_zone, void * data) static
Definition at line 160 of file kv.c.
References brix_shm_table_alloc(), brix_kv_header_t::capacity, brix_kv_header_t::key_max, and brix_kv_header_t::val_max.
Referenced by brix_kv_configure().
brix_kv_remove_at()
static void brix_kv_remove_at (brix_kv_header_t * h, size_t stride, uint32_t mask, uint32_t hole) static
Definition at line 129 of file kv.c.
References brix_kv_should_shift(), brix_kv_slot(), brix_kv_entry_t::hash, and brix_kv_entry_t::key_len.
Referenced by brix_kv_delete(), and brix_kv_get().
brix_kv_set()
ngx_int_t brix_kv_set (brix_kv_t * kv, const void * key, size_t key_len, const void * val, size_t val_len, ngx_msec_t ttl_ms)
Definition at line 311 of file kv.c.
References brix_kv_hash(), brix_kv_hdr(), brix_kv_slot(), brix_kv_header_t::capacity, brix_kv_header_t::count, brix_kv_entry_t::expires, brix_kv_entry_t::hash, key, brix_kv_entry_t::key_len, and brix_kv_entry_t::val_len.
Referenced by brix_auth_gate_cache_put(), brix_rate_limit_check(), brix_token_cache_store(), and webdav_introspect_done().
brix_kv_should_shift()
static ngx_uint_t brix_kv_should_shift (uint32_t home, uint32_t hole, uint32_t cur) static
Definition at line 119 of file kv.c.
Referenced by brix_kv_remove_at().
brix_kv_slot()
static brix_kv_entry_t * brix_kv_slot (brix_kv_header_t * h, size_t stride, uint32_t i) static
Definition at line 107 of file kv.c.
Referenced by brix_kv_delete(), brix_kv_get(), brix_kv_remove_at(), and brix_kv_set().
brix_kv_stats()
void brix_kv_stats (brix_kv_t * kv, brix_kv_stats_t * out)
Definition at line 420 of file kv.c.
References brix_kv_hdr(), brix_kv_header_t::capacity, brix_kv_stats_t::capacity, brix_kv_header_t::count, brix_kv_stats_t::count, brix_kv_header_t::evictions, brix_kv_stats_t::evictions, brix_kv_header_t::hits, brix_kv_stats_t::hits, brix_kv_header_t::misses, and brix_kv_stats_t::misses.
Referenced by brix_kv_metrics_emit().
brix_kv_zone_count()
ngx_uint_t brix_kv_zone_count (void)
Definition at line 456 of file kv.c.
References brix_kv_nzones.
Referenced by brix_kv_metrics_emit().
brix_kv_zone_directive()
char * brix_kv_zone_directive (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 469 of file kv.c.
References brix_kv_configure(), brix_kv_find(), BRIX_PCALLOC_OR_RETURN, and name.
brix_kv_zone_get()
brix_kv_t * brix_kv_zone_get (ngx_uint_t i)
Definition at line 462 of file kv.c.
References brix_kv_nzones, and brix_kv_zones.
Referenced by brix_kv_metrics_emit().
Variable Documentation
brix_kv_nzones
ngx_uint_t brix_kv_nzones static
Definition at line 56 of file kv.c.
Referenced by brix_kv_configure(), brix_kv_find(), brix_kv_zone_count(), and brix_kv_zone_get().
brix_kv_zones
brix_kv_t* brix_kv_zones[16] static
Definition at line 55 of file kv.c.
Referenced by brix_kv_configure(), brix_kv_find(), and brix_kv_zone_get().
ngx_http_brix_webdav_module
ngx_module_t ngx_http_brix_webdav_module extern
Definition at line 548 of file module.c.
Referenced by brix_acc_http_both(), brix_acc_http_set_audit(), brix_acc_http_set_authdb(), brix_acc_http_set_format(), brix_dig_handle(), brix_http_mirror_log_handler(), brix_http_mirror_precontent_handler(), brix_http_mirror_proxy(), brix_http_protocol_variable(), brix_http_serve_file_ranged(), brix_http_set_ktls(), brix_proto_mask(), brix_rl_http_access_handler(), brix_rl_http_log_handler(), mirror_create_request(), mirror_finalize_request(), mirror_fire_subrequests(), mirror_process_status_line(), mirror_put_body_handler(), mirror_reinit_request(), ngx_http_brix_webdav_access_handler(), ngx_http_brix_webdav_handler(), ngx_http_brix_webdav_postconfiguration(), ngx_http_brix_webdav_tpc_handle_copy(), propfind_append_acl_properties(), propfind_body_handler(), propfind_entry(), propfind_walk(), tape_dispatch_post(), tape_residency(), webdav_acc_check(), webdav_add_cors_headers(), webdav_check_locks(), webdav_check_token_scope(), webdav_copy_probe(), webdav_dashboard_identity(), webdav_dead_prop_vfs_ctx_init(), webdav_dispatch_inner(), webdav_handle_copy(), webdav_handle_get(), webdav_handle_head(), webdav_handle_lock(), webdav_handle_lock_inner(), webdav_handle_macaroon_request(), webdav_handle_macaroon_token(), webdav_handle_mkcol(), webdav_handle_move(), webdav_handle_options(), webdav_handle_put_body(), webdav_handle_unlock(), webdav_introspect_access_handler(), webdav_lock_vfs_ctx(), webdav_lock_vfs_ctx_init(), webdav_move_probe(), webdav_ns_vfs_ctx_init(), webdav_proppatch_body_handler(), webdav_proxy_create_request(), webdav_proxy_finalize_request(), webdav_proxy_handler(), webdav_proxy_process_status_line(), webdav_proxy_reinit_request(), webdav_put_body_inner(), webdav_put_persist_checksums(), webdav_put_ranged_resume(), webdav_put_vfs_ctx_init(), webdav_resolve_stat(), webdav_search_body_handler(), webdav_search_walk(), webdav_tape_handle(), webdav_tpc_cred_obtain_token(), webdav_tpc_probe(), webdav_tpc_request_identity(), webdav_verify_bearer_token(), and webdav_verify_proxy_cert().