nginx-xrootd: src/core/shm/kv.h File Reference
kv.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
Data Structures
struct brix_kv_t
struct brix_kv_stats_t
Macros
#define BRIX_KV_MIN_SIZE (64 * 1024) /* smallest accepted zone size */
#define BRIX_KV_MAX_ZONES 16 /* module-wide zone registry cap */
Functions
ngx_int_t brix_kv_configure (ngx_conf_t *cf, brix_kv_t *kv, ngx_str_t *name, size_t size, size_t key_max, size_t val_max, void *module)
int brix_kv_get (brix_kv_t *kv, const void *key, size_t key_len, void *out, size_t *out_len)
ngx_int_t brix_kv_set (brix_kv_t *kv, const void *key, size_t key_len, const void *val, size_t val_len, ngx_msec_t ttl_ms)
void brix_kv_delete (brix_kv_t *kv, const void *key, size_t key_len)
void brix_kv_stats (brix_kv_t *kv, brix_kv_stats_t *out)
brix_kv_t * brix_kv_find (const ngx_str_t *name)
ngx_uint_t brix_kv_zone_count (void)
brix_kv_t * brix_kv_zone_get (ngx_uint_t i)
char * brix_kv_zone_directive (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Macro Definition Documentation
BRIX_KV_MAX_ZONES
#define BRIX_KV_MAX_ZONES 16 /* module-wide zone registry cap */
Definition at line 32 of file kv.h.
BRIX_KV_MIN_SIZE
#define BRIX_KV_MIN_SIZE (64 * 1024) /* smallest accepted zone size */
Definition at line 31 of file kv.h.
Function Documentation
brix_kv_configure()
ngx_int_t brix_kv_configure (ngx_conf_t * cf, brix_kv_t * kv, ngx_str_t * name, size_t size, size_t key_max, size_t val_max, void * module)
Definition at line 141 of file kv_config.c.
References brix_kv_floor_pow2(), brix_kv_init_zone(), BRIX_KV_MAX_ZONES, BRIX_KV_MIN_SIZE, brix_kv_nzones, brix_kv_zones, brix_shm_zone_size(), and name.
Referenced by brix_kv_zone_directive().
brix_kv_delete()
void brix_kv_delete (brix_kv_t * kv, const void * key, size_t key_len)
Definition at line 282 of file kv.c.
References brix_kv_entry_matches(), brix_kv_hash(), brix_kv_hdr(), brix_kv_remove_at(), brix_kv_slot(), brix_kv_header_t::capacity, brix_kv_header_t::count, key, and brix_kv_entry_t::key_len.
brix_kv_find()
brix_kv_t * brix_kv_find (const ngx_str_t * name)
Definition at line 213 of file kv_config.c.
References brix_kv_nzones, brix_kv_zones, and name.
Referenced by brix_auth_cache_directive(), brix_kv_zone_directive(), brix_rl_resolve_zone(), brix_token_cache_directive(), and webdav_conf_revoke_cache().
brix_kv_get()
int brix_kv_get (brix_kv_t * kv, const void * key, size_t key_len, void * out, size_t * out_len)
Definition at line 164 of file kv.c.
References brix_kv_copy_value(), brix_kv_entry_matches(), brix_kv_hash(), brix_kv_hdr(), brix_kv_remove_at(), brix_kv_slot(), brix_kv_header_t::capacity, brix_kv_header_t::count, brix_kv_header_t::evictions, brix_kv_entry_t::expires, brix_kv_header_t::hits, key, brix_kv_entry_t::key_len, and brix_kv_header_t::misses.
Referenced by brix_auth_gate_cache_probe(), brix_rate_limit_check(), brix_token_cache_lookup(), and webdav_introspect_access_handler().
brix_kv_set()
ngx_int_t brix_kv_set (brix_kv_t * kv, const void * key, size_t key_len, const void * val, size_t val_len, ngx_msec_t ttl_ms)
Definition at line 215 of file kv.c.
References brix_kv_entry_matches(), brix_kv_hash(), brix_kv_hdr(), brix_kv_slot(), brix_kv_header_t::capacity, brix_kv_header_t::count, brix_kv_entry_t::expires, brix_kv_entry_t::hash, key, brix_kv_entry_t::key_len, ngx_memcpy, and brix_kv_entry_t::val_len.
Referenced by brix_auth_gate_cache_put(), brix_rate_limit_check(), brix_token_cache_store(), and webdav_introspect_done().
brix_kv_stats()
void brix_kv_stats (brix_kv_t * kv, brix_kv_stats_t * out)
Definition at line 320 of file kv.c.
References brix_kv_hdr(), brix_kv_stats_t::capacity, brix_kv_header_t::capacity, brix_kv_stats_t::count, brix_kv_header_t::count, brix_kv_stats_t::evictions, brix_kv_header_t::evictions, brix_kv_stats_t::hits, brix_kv_header_t::hits, brix_kv_stats_t::misses, and brix_kv_header_t::misses.
Referenced by brix_kv_metrics_emit().
brix_kv_zone_count()
ngx_uint_t brix_kv_zone_count (void)
Definition at line 237 of file kv_config.c.
References brix_kv_nzones.
Referenced by brix_kv_metrics_emit().
brix_kv_zone_directive()
char * brix_kv_zone_directive (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 276 of file kv_config.c.
References brix_kv_configure(), brix_kv_find(), BRIX_PCALLOC_OR_RETURN, and name.
brix_kv_zone_get()
brix_kv_t * brix_kv_zone_get (ngx_uint_t i)
Definition at line 252 of file kv_config.c.
References brix_kv_nzones, and brix_kv_zones.
Referenced by brix_kv_metrics_emit().