nginx-xrootd: src/core/compat/kxr_names.c File Reference
kxr_names.c File Reference
#include <stddef.h>
#include "kxr_names.h"
#include "protocols/root/protocol/opcodes.h"
Data Structures
struct kxr_name_entry_t
Macros
#define KXR_TABLE_N(t) (sizeof(t) / sizeof((t)[0]))
Functions
static const char * kxr_lookup (const kxr_name_entry_t *table, size_t n, int code, const char *fallback)
const char * brix_kxr_request_name (int reqid)
const char * brix_kxr_response_status_name (int status)
const char * brix_kxr_error_name (int kxr)
Variables
static const kxr_name_entry_t kxr_request_names []
static const kxr_name_entry_t kxr_response_status_names []
static const kxr_name_entry_t kxr_error_names []
Macro Definition Documentation
KXR_TABLE_N
#define KXR_TABLE_N (t) (sizeof(t) / sizeof((t)[0]))
Definition at line 128 of file kxr_names.c.
Function Documentation
brix_kxr_error_name()
const char * brix_kxr_error_name (int kxr)
Definition at line 146 of file kxr_names.c.
References kxr_error_names, kxr_lookup(), and KXR_TABLE_N.
Referenced by brix_kxr_name().
brix_kxr_request_name()
const char * brix_kxr_request_name (int reqid)
Definition at line 131 of file kxr_names.c.
References kxr_lookup(), kxr_request_names, and KXR_TABLE_N.
Referenced by brix_reqid_name().
brix_kxr_response_status_name()
const char * brix_kxr_response_status_name (int status)
Definition at line 138 of file kxr_names.c.
References kxr_lookup(), kxr_response_status_names, and KXR_TABLE_N.
Referenced by brix_status_name().
kxr_lookup()
static const char * kxr_lookup (const kxr_name_entry_t * table, size_t n, int code, const char * fallback) static
Definition at line 114 of file kxr_names.c.
References code, and kxr_name_entry_t::name.
Referenced by brix_kxr_error_name(), brix_kxr_request_name(), and brix_kxr_response_status_name().
Variable Documentation
kxr_error_names
const kxr_name_entry_t kxr_error_names[] static
Definition at line 73 of file kxr_names.c.
Referenced by brix_kxr_error_name().
kxr_request_names
const kxr_name_entry_t kxr_request_names[] static
Definition at line 25 of file kxr_names.c.
Referenced by brix_kxr_request_name().
kxr_response_status_names
const kxr_name_entry_t kxr_response_status_names[] static
Initial value:
= {
    {  0  ,       "ok"       },
    {  4000  ,  "oksofar"  },
    {  4001  ,     "attn"     },
    {  4002  , "authmore" },
    {  4003  ,    "error"    },
    {  4004  , "redirect" },
    {  4005  ,     "wait"     },
    {  4006  , "waitresp" },
    {  4007  ,   "status"   },
}
Definition at line 61 of file kxr_names.c.
Referenced by brix_kxr_response_status_name().