nginx-xrootd: src/core/compat/kxr_names.h File Reference
kxr_names.h File Reference
Functions
const char * brix_kxr_request_name (int reqid)
const char * brix_kxr_response_status_name (int status)
const char * brix_kxr_error_name (int kxr)
Function Documentation
brix_kxr_error_name()
const char * brix_kxr_error_name (int kxr)
Definition at line 70 of file kxr_names.c.
References kXR_ArgInvalid, kXR_ArgMissing, kXR_ArgTooLong, kXR_AttrNotFound, kXR_AuthFailed, kXR_Cancelled, kXR_ChkSumErr, kXR_Conflict, kXR_FileLocked, kXR_FileNotOpen, kXR_FSError, kXR_fsReadOnly, kXR_Impossible, kXR_inProgress, kXR_InvalidRequest, kXR_IOError, kXR_isDirectory, kXR_ItExists, kXR_NoMemory, kXR_noserver, kXR_NoSpace, kXR_NotAuthorized, kXR_NotFile, kXR_NotFound, kXR_Overloaded, kXR_overQuota, kXR_ServerError, kXR_TLSRequired, kXR_TooManyErrs, and kXR_Unsupported.
Referenced by brix_kxr_name().
brix_kxr_request_name()
const char * brix_kxr_request_name (int reqid)
Definition at line 12 of file kxr_names.c.
References kXR_auth, kXR_bind, kXR_chkpoint, kXR_chmod, kXR_clone, kXR_close, kXR_dirlist, kXR_endsess, kXR_fattr, kXR_gpfile, kXR_locate, kXR_login, kXR_mkdir, kXR_mv, kXR_open, kXR_pgread, kXR_pgwrite, kXR_ping, kXR_prepare, kXR_protocol, kXR_query, kXR_read, kXR_readv, kXR_rm, kXR_rmdir, kXR_set, kXR_sigver, kXR_stat, kXR_statx, kXR_sync, kXR_truncate, kXR_write, and kXR_writev.
Referenced by brix_reqid_name().
brix_kxr_response_status_name()
const char * brix_kxr_response_status_name (int status)
Definition at line 53 of file kxr_names.c.
References kXR_attn, kXR_authmore, kXR_error, kXR_ok, kXR_oksofar, kXR_redirect, kXR_status, kXR_wait, and kXR_waitresp.
Referenced by brix_status_name().