nginx-xrootd: src/tpc/engine/launch_prepare.c File Reference
launch_prepare.c File Reference
#include "tpc_internal.h"
#include "fs/vfs/vfs.h"
#include "core/compat/host_format.h"
#include "observability/sesslog/sesslog_ngx.h"
#include "protocols/root/session/registry.h"
#include <string.h>
#include <errno.h>
#include <unistd.h>
#include <fcntl.h>
#include <netdb.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include "core/compat/alloc_guard.h"
#include "core/compat/cstr.h"
Functions
static ngx_int_t tpc_send_open_response (brix_ctx_t *ctx, ngx_connection_t *c, int idx, int fd, uint16_t options)
static void tpc_build_origin_id (brix_ctx_t *ctx, ngx_connection_t *c, char *dst, size_t dst_size)
static int tpc_destination_open_flags (uint16_t options)
static ngx_int_t tpc_prepare_check_preconditions (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const brix_tpc_params_t *tpc, const char *dst_path)
static int tpc_open_dst_logical (ngx_stream_brix_srv_conf_t *conf, const char *dst_path, uint16_t options, mode_t create_mode)
static void tpc_init_dst_file (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, brix_file_t *file, const brix_tpc_params_t *tpc, const struct stat *st)
ngx_int_t brix_tpc_prepare_pull (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const brix_tpc_params_t *tpc, const char *dst_path, uint16_t options, uint16_t mode_bits)
Function Documentation
brix_tpc_prepare_pull()
ngx_int_t brix_tpc_prepare_pull (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const brix_tpc_params_t * tpc, const char * dst_path, uint16_t options, uint16_t mode_bits)
Definition at line 384 of file launch_prepare.c.
References brix_alloc_fhandle(), brix_free_fhandle(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_OPEN_WR, BRIX_RETURN_ERR, brix_send_error(), brix_session_handle_publish(), brix_set_fhandle_path(), c, close(), brix_file_t::fd, brix_ctx_t::files, fstat(), brix_ctx_t::is_bound, kXR_IOError, kXR_ServerError, brix_ctx_t::login, brix_ctx_login_t::sessid, stat(), tpc_init_dst_file(), tpc_open_dst_logical(), tpc_prepare_check_preconditions(), and tpc_send_open_response().
Referenced by brix_tpc_launch_pull(), and tpc_handle_dest().
tpc_build_origin_id()
static void tpc_build_origin_id (brix_ctx_t * ctx, ngx_connection_t * c, char * dst, size_t dst_size) static
Definition at line 101 of file launch_prepare.c.
References c, host, brix_ctx_t::login, ngx_memcpy, brix_ctx_login_t::pid, and brix_ctx_login_t::user.
Referenced by tpc_init_dst_file().
tpc_destination_open_flags()
static int tpc_destination_open_flags (uint16_t options) static
Definition at line 199 of file launch_prepare.c.
References kXR_delete, and kXR_new.
Referenced by tpc_open_dst_logical().
tpc_init_dst_file()
static void tpc_init_dst_file (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, brix_file_t * file, const brix_tpc_params_t * tpc, const struct stat * st) static
Definition at line 320 of file launch_prepare.c.
References brix_tpc_generate_key(), brix_file_t::bytes_read, brix_file_t::bytes_written, c, brix_file_t::cached_size, brix_file_t::device, brix_file_t::from_cache, brix_tpc_params_t::has_token_mode, brix_file_t::inode, brix_file_t::is_regular, brix_tpc_params_t::key, brix_file_t::open_time, brix_file_t::read_ahead_end, brix_file_t::read_last_end, brix_file_t::readable, brix_tpc_params_t::src_host, brix_tpc_params_t::src_path, brix_tpc_params_t::src_port, brix_tpc_params_t::token_mode, brix_file_t::tpc_armed, tpc_build_origin_id(), brix_file_t::tpc_destination, brix_file_t::tpc_done, brix_file_t::tpc_key, brix_file_t::tpc_org, brix_file_t::tpc_src_host, brix_file_t::tpc_src_path, brix_file_t::tpc_src_port, brix_file_t::tpc_started, brix_file_t::tpc_token_mode, brix_file_t::tpc_transfer_id, and brix_file_t::writable.
Referenced by brix_tpc_prepare_pull().
tpc_open_dst_logical()
static int tpc_open_dst_logical (ngx_stream_brix_srv_conf_t * conf, const char * dst_path, uint16_t options, mode_t create_mode) static
Definition at line 287 of file launch_prepare.c.
References brix_vfs_open_fd_at(), and tpc_destination_open_flags().
Referenced by brix_tpc_prepare_pull().
tpc_prepare_check_preconditions()
static ngx_int_t tpc_prepare_check_preconditions (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const brix_tpc_params_t * tpc, const char * dst_path) static
Definition at line 234 of file launch_prepare.c.
References brix_log_access(), BRIX_OP_ERR, BRIX_OP_OPEN_WR, BRIX_RETURN_ERR, brix_send_error(), brix_tpc_check_src_policy(), c, kXR_ArgInvalid, kXR_NotAuthorized, kXR_ServerError, brix_tpc_params_t::src_host, brix_tpc_params_t::src_path, and brix_tpc_params_t::src_port.
Referenced by brix_tpc_prepare_pull().
tpc_send_open_response()
static ngx_int_t tpc_send_open_response (brix_ctx_t * ctx, ngx_connection_t * c, int idx, int fd, uint16_t options) static
Definition at line 47 of file launch_prepare.c.
References brix_build_resp_hdr(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), c, brix_ctx_recv_t::cur_streamid, ServerOpenBody::fhandle, fstat(), kXR_ok, kXR_readable, kXR_retstat, kXR_writable, ngx_memcpy, brix_ctx_t::recv, stat(), and XRD_RESPONSE_HDR_LEN.
Referenced by brix_tpc_prepare_pull().