nginx-xrootd: src/tpc/engine/launch.c File Reference
launch.c File Reference
#include "tpc_internal.h"
#include "fs/vfs/vfs.h"
#include "core/compat/host_format.h"
#include "observability/sesslog/sesslog_ngx.h"
#include "protocols/root/session/registry.h"
#include <string.h>
#include <errno.h>
#include <unistd.h>
#include <fcntl.h>
#include <netdb.h>
#include "core/compat/alloc_guard.h"
#include "core/compat/cstr.h"
Functions
static brix_sess_am_t tpc_sess_auth_method (const brix_tpc_pull_t *t)
static const char * tpc_sess_identity_user (const brix_tpc_pull_t *t)
static const char * tpc_sess_identity_vo (const brix_tpc_pull_t *t)
static void tpc_sess_begin_pull (brix_tpc_pull_t *t)
static void tpc_sess_abort_pull (brix_tpc_pull_t *t, const char *err)
static uint64_t tpc_register_stream_transfer (ngx_connection_t *c, brix_file_t *file)
static void tpc_populate_pull_task (brix_tpc_pull_t *t, brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, brix_file_t *file)
static void tpc_pull_capture_passthrough_token (brix_tpc_pull_t *t, brix_ctx_t *ctx)
static void tpc_pull_attach_creds (brix_tpc_pull_t *t, brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *conf)
static void tpc_pull_resolve_pmark (brix_tpc_pull_t *t, brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_tpc_start_pull (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, int fhandle_idx)
ngx_int_t brix_tpc_launch_pull (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const brix_tpc_params_t *tpc, const char *dst_path, uint16_t options, uint16_t mode_bits)
Function Documentation
brix_tpc_launch_pull()
ngx_int_t brix_tpc_launch_pull (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const brix_tpc_params_t * tpc, const char * dst_path, uint16_t options, uint16_t mode_bits)
Definition at line 409 of file launch.c.
References brix_tpc_prepare_pull(), and c.
brix_tpc_start_pull()
ngx_int_t brix_tpc_start_pull (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, int fhandle_idx)
Definition at line 340 of file launch.c.
References brix_log_access(), BRIX_MAX_FILES, BRIX_OP_ERR, BRIX_OP_SYNC, BRIX_RETURN_ERR, brix_send_error(), brix_send_wait(), brix_tpc_pull_done(), brix_tpc_pull_thread(), brix_tpc_registry_remove(), c, brix_tpc_pull_t::ctx, brix_file_t::fd, brix_tpc_pull_t::fhandle_idx, brix_ctx_t::files, kXR_FileNotOpen, kXR_Overloaded, kXR_ServerError, brix_file_t::path, brix_ctx_t::state, brix_file_t::tpc_destination, tpc_populate_pull_task(), tpc_pull_attach_creds(), tpc_pull_resolve_pmark(), tpc_register_stream_transfer(), tpc_sess_abort_pull(), tpc_sess_begin_pull(), brix_file_t::tpc_started, brix_file_t::tpc_transfer_id, and XRD_ST_AIO.
Referenced by brix_handle_sync().
tpc_populate_pull_task()
static void tpc_populate_pull_task (brix_tpc_pull_t * t, brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, brix_file_t * file) static
Definition at line 188 of file launch.c.
References BRIX_TPC_REPLY_SYNC, c, brix_tpc_pull_t::c, brix_tpc_pull_t::conf, brix_tpc_pull_t::ctx, brix_ctx_recv_t::cur_streamid, brix_tpc_pull_t::dst_fd, brix_tpc_pull_t::dst_path, brix_file_t::fd, brix_file_t::path, brix_ctx_t::recv, brix_tpc_pull_t::reply_kind, brix_tpc_pull_t::src_host, brix_tpc_pull_t::src_path, brix_tpc_pull_t::src_port, brix_tpc_pull_t::streamid, brix_tpc_pull_t::token_mode, brix_file_t::tpc_key, brix_tpc_pull_t::tpc_key, brix_file_t::tpc_org, brix_tpc_pull_t::tpc_org, brix_file_t::tpc_src_host, brix_file_t::tpc_src_path, brix_file_t::tpc_src_port, brix_file_t::tpc_token_mode, brix_file_t::tpc_transfer_id, and brix_tpc_pull_t::transfer_id.
Referenced by brix_tpc_start_pull().
tpc_pull_attach_creds()
static void tpc_pull_attach_creds (brix_tpc_pull_t * t, brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * conf) static
Definition at line 269 of file launch.c.
References brix_str_cbuf(), brix_tpc_pull_t::deleg_cred_len, brix_tpc_pull_t::deleg_cred_pem, brix_ctx_gsi_t::deleg_proxy_len, brix_ctx_gsi_t::deleg_proxy_pem, brix_ctx_t::gsi, ngx_memcpy, brix_tpc_pull_t::token_scope, and tpc_pull_capture_passthrough_token().
Referenced by brix_tpc_start_pull().
tpc_pull_capture_passthrough_token()
static void tpc_pull_capture_passthrough_token (brix_tpc_pull_t * t, brix_ctx_t * ctx) static
Definition at line 233 of file launch.c.
References brix_ctx_t::bearer_token, brix_tpc_pull_t::delegated_token, ngx_memcpy, and brix_tpc_pull_t::token_mode.
Referenced by tpc_pull_attach_creds().
tpc_pull_resolve_pmark()
static void tpc_pull_resolve_pmark (brix_tpc_pull_t * t, brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf) static
Definition at line 308 of file launch.c.
References brix_identity_dn_cstr(), brix_identity_vo_csv_cstr(), brix_pmark_map_codes(), brix_pmark_runtime_ensure(), c, brix_pmark_flow_id_t::cgi, brix_tpc_pull_t::dst_path, brix_ctx_t::identity, brix_pmark_flow_id_t::path, brix_tpc_pull_t::pmark_act, brix_tpc_pull_t::pmark_exp, brix_pmark_flow_id_t::user, and brix_pmark_flow_id_t::vo_csv.
Referenced by brix_tpc_start_pull().
tpc_register_stream_transfer()
static uint64_t tpc_register_stream_transfer (ngx_connection_t * c, brix_file_t * file) static
Definition at line 135 of file launch.c.
References brix_format_host_port(), BRIX_TPC_DIR_PULL, BRIX_TPC_PROTO_STREAM, brix_tpc_registry_add(), BRIX_TPC_STATE_PENDING, c, brix_tpc_transfer_t::direction, brix_tpc_transfer_t::dst_path, brix_file_t::path, PATH_MAX, brix_tpc_transfer_t::protocol, brix_tpc_transfer_t::src_url, brix_tpc_transfer_t::state, brix_file_t::tpc_src_host, brix_file_t::tpc_src_path, and brix_file_t::tpc_src_port.
Referenced by brix_tpc_start_pull().
tpc_sess_abort_pull()
static void tpc_sess_abort_pull (brix_tpc_pull_t * t, const char * err) static
Definition at line 113 of file launch.c.
References brix_sess_end(), BRIX_SESS_END_ERROR, BRIX_SESS_MODE_READ, brix_sess_result(), BRIX_SESS_XFER_ABORTED, brix_sess_xfer_end(), brix_tpc_pull_t::sess, brix_tpc_pull_t::sess_xfer, and brix_tpc_pull_t::src_path.
Referenced by brix_tpc_start_pull().
tpc_sess_auth_method()
static brix_sess_am_t tpc_sess_auth_method (const brix_tpc_pull_t * t) static
Definition at line 35 of file launch.c.
References BRIX_SESS_AM_ANON, BRIX_SESS_AM_GSI, BRIX_SESS_AM_TOKEN, brix_tpc_pull_t::conf, brix_tpc_pull_t::deleg_cred_len, and brix_tpc_pull_t::token_mode.
Referenced by tpc_sess_begin_pull().
tpc_sess_begin_pull()
static void tpc_sess_begin_pull (brix_tpc_pull_t * t) static
Definition at line 88 of file launch.c.
References brix_format_host_port(), brix_sess_attempt(), brix_sess_auth_once(), brix_sess_begin(), BRIX_SESS_DIR_OUT, BRIX_SESS_MODE_READ, BRIX_SESS_PROTO_TPC, brix_sess_xfer_start(), brix_tpc_pull_t::conf, brix_tpc_pull_t::ctx, brix_ctx_t::sess, brix_tpc_pull_t::sess, brix_tpc_pull_t::sess_xfer, brix_tpc_pull_t::src_host, brix_tpc_pull_t::src_path, brix_tpc_pull_t::src_port, tpc_sess_auth_method(), tpc_sess_identity_user(), and tpc_sess_identity_vo().
Referenced by brix_tpc_start_pull().
tpc_sess_identity_user()
static const char * tpc_sess_identity_user (const brix_tpc_pull_t * t) static
Definition at line 57 of file launch.c.
References brix_identity_dn_cstr(), brix_identity_subject_cstr(), brix_tpc_pull_t::ctx, and brix_ctx_t::identity.
Referenced by tpc_sess_begin_pull().
tpc_sess_identity_vo()
static const char * tpc_sess_identity_vo (const brix_tpc_pull_t * t) static
Definition at line 75 of file launch.c.
References brix_identity_vo_csv_cstr(), brix_tpc_pull_t::ctx, and brix_ctx_t::identity.
Referenced by tpc_sess_begin_pull().