nginx-xrootd: src/auth/impersonate/lifecycle_worker.c File Reference
lifecycle_worker.c File Reference
#include "lifecycle.h"
#include "impersonate.h"
#include "impersonate_proto.h"
#include "observability/metrics/metrics.h"
#include "core/compat/log_diag.h"
#include "lifecycle_internal.h"
#include <errno.h>
#include <fcntl.h>
#include <grp.h>
#include <pwd.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <sys/prctl.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/un.h>
#include <sys/wait.h>
#include <linux/capability.h>
Functions
int brix_imp_cap_held (int cap)
static void imp_worker_drop_caps (ngx_log_t *log)
void brix_imp_worker_harden (ngx_log_t *log)
char * brix_conf_set_worker_user (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
ngx_int_t brix_imp_worker_runtime_ids (ngx_uid_t conf_uid, ngx_gid_t conf_gid, uid_t *uid_out, gid_t *gid_out)
ngx_int_t brix_imp_worker_deescalate (ngx_log_t *log)
ngx_int_t brix_imp_init_worker (ngx_cycle_t *cycle)
static const char * imp_principal_of (const brix_identity_t *id)
void brix_imp_request_begin (const brix_identity_t *id)
void brix_imp_request_end (void)
Variables
char brix_worker_user [64] = ""
Function Documentation
brix_conf_set_worker_user()
char * brix_conf_set_worker_user (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 142 of file lifecycle_worker.c.
References brix_worker_user, and ngx_memcpy.
brix_imp_cap_held()
int brix_imp_cap_held (int cap)
Definition at line 50 of file lifecycle_worker.c.
Referenced by brix_imp_worker_deescalate(), and imp_worker_drop_caps().
brix_imp_init_worker()
ngx_int_t brix_imp_init_worker (ngx_cycle_t * cycle)
Definition at line 322 of file lifecycle_worker.c.
References brix_imp_client_connect(), BRIX_IMP_MAP, imp_settings, imp_settings_t::mode, and imp_settings_t::socket.
Referenced by ngx_stream_brix_init_process().
brix_imp_request_begin()
void brix_imp_request_begin (const brix_identity_t * id)
Definition at line 360 of file lifecycle_worker.c.
References BRIX_IMP_MAP, brix_imp_mark_in_request(), brix_imp_set_principal(), imp_principal_of(), imp_settings, and imp_settings_t::mode.
Referenced by brix_dispatch(), ngx_http_brix_webdav_handler(), ngx_http_s3_handler(), propfind_body_handler(), s3_delete_objects_body_handler(), s3_multipart_complete_body_handler(), s3_post_object_body_handler(), s3_put_body_handler(), webdav_handle_lock(), webdav_handle_put_body(), webdav_proppatch_body_handler(), and webdav_search_body_handler().
brix_imp_request_end()
void brix_imp_request_end (void)
Definition at line 373 of file lifecycle_worker.c.
References brix_imp_clear_principal(), BRIX_IMP_MAP, brix_imp_mark_in_request(), imp_settings, and imp_settings_t::mode.
Referenced by brix_dispatch(), ngx_http_brix_webdav_handler(), ngx_http_s3_handler(), propfind_body_handler(), s3_delete_objects_body_handler(), s3_multipart_complete_body_handler(), s3_post_object_body_handler(), s3_put_body_handler(), webdav_handle_lock(), webdav_handle_put_body(), webdav_proppatch_body_handler(), and webdav_search_body_handler().
brix_imp_worker_deescalate()
ngx_int_t brix_imp_worker_deescalate (ngx_log_t * log)
Definition at line 213 of file lifecycle_worker.c.
References brix_imp_cap_held(), brix_imp_worker_harden(), brix_worker_user, and log.
Referenced by ngx_stream_brix_init_process().
brix_imp_worker_harden()
void brix_imp_worker_harden (ngx_log_t * log)
Definition at line 129 of file lifecycle_worker.c.
References imp_worker_drop_caps(), and log.
Referenced by brix_imp_worker_deescalate(), and ngx_stream_brix_init_process().
brix_imp_worker_runtime_ids()
ngx_int_t brix_imp_worker_runtime_ids (ngx_uid_t conf_uid, ngx_gid_t conf_gid, uid_t * uid_out, gid_t * gid_out)
Definition at line 170 of file lifecycle_worker.c.
References brix_worker_user.
Referenced by brix_shared_worker_dir_ids().
imp_principal_of()
static const char * imp_principal_of (const brix_identity_t * id) static
Definition at line 348 of file lifecycle_worker.c.
References brix_identity_dn_cstr(), and brix_identity_subject_cstr().
Referenced by brix_imp_request_begin().
imp_worker_drop_caps()
static void imp_worker_drop_caps (ngx_log_t * log) static
Definition at line 67 of file lifecycle_worker.c.
References brix_imp_cap_held(), and log.
Referenced by brix_imp_worker_harden().
Variable Documentation
brix_worker_user
char brix_worker_user[64] = ""
Definition at line 139 of file lifecycle_worker.c.
Referenced by brix_conf_set_worker_user(), brix_imp_worker_deescalate(), and brix_imp_worker_runtime_ids().