nginx-xrootd: src/auth/impersonate/lifecycle_broker.c File Reference
lifecycle_broker.c File Reference
#include "lifecycle.h"
#include "impersonate.h"
#include "impersonate_proto.h"
#include "observability/metrics/metrics.h"
#include "core/compat/log_diag.h"
#include "lifecycle_internal.h"
#include <errno.h>
#include <fcntl.h>
#include <pwd.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <sys/prctl.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/un.h>
#include <sys/wait.h>
#include <linux/capability.h>
Data Structures
struct imp_broker_fds_t
Functions
static void imp_fill_idmap_conf (brix_idmap_conf_t *c, uid_t worker_uid)
static int imp_make_listen (const char *path, uid_t wuid, ngx_log_t *log)
static void imp_pidfile (char *buf, size_t n)
static void imp_kill_stale_broker (ngx_log_t *log)
static void imp_broker_child (int lfd, int rootfd, ngx_log_t *log)
static uid_t imp_worker_uid (ngx_cycle_t *cycle)
static ngx_int_t imp_resolve_broker_user (ngx_cycle_t *cycle, uid_t wuid)
static ngx_int_t imp_load_idmap (ngx_cycle_t *cycle, uid_t wuid)
static ngx_int_t imp_open_broker_fds (const char *sockbuf, const char *rootbuf, uid_t wuid, ngx_log_t *log, imp_broker_fds_t *fds)
static ngx_int_t imp_spawn_broker (int lfd, int rootfd, ngx_log_t *log)
static ngx_int_t imp_init_module_gate (ngx_cycle_t *cycle)
ngx_int_t brix_imp_init_module (ngx_cycle_t *cycle)
Variables
ngx_uint_t ngx_test_config
Function Documentation
brix_imp_init_module()
ngx_int_t brix_imp_init_module (ngx_cycle_t * cycle)
Definition at line 369 of file lifecycle_broker.c.
References brix_imp_broker_allow_uid, imp_settings_t::export_root, imp_init_module_gate(), imp_kill_stale_broker(), imp_load_idmap(), imp_open_broker_fds(), imp_resolve_broker_user(), imp_settings, imp_spawn_broker(), imp_worker_uid(), imp_broker_fds_t::lfd, imp_broker_fds_t::rootfd, and imp_settings_t::socket.
imp_broker_child()
static void imp_broker_child (int lfd, int rootfd, ngx_log_t * log) static
Definition at line 133 of file lifecycle_broker.c.
References brix_imp_broker_run(), imp_pidfile(), and log.
Referenced by imp_spawn_broker().
imp_fill_idmap_conf()
static void imp_fill_idmap_conf (brix_idmap_conf_t * c, uid_t worker_uid) static
Definition at line 43 of file lifecycle_broker.c.
References c, imp_settings_t::cache_ttl, imp_settings_t::default_user, imp_settings_t::forbidden_groups, imp_settings_t::forbidden_users, imp_settings_t::gridmap, imp_settings, imp_settings_t::min_uid, and imp_settings_t::single_user.
Referenced by imp_load_idmap().
imp_init_module_gate()
static ngx_int_t imp_init_module_gate (ngx_cycle_t * cycle) static
Definition at line 348 of file lifecycle_broker.c.
References brix_config_version_publish(), BRIX_DIAG_EMERG, BRIX_IMP_MAP, imp_settings, imp_settings_t::mode, and ngx_test_config.
Referenced by brix_imp_init_module().
imp_kill_stale_broker()
static void imp_kill_stale_broker (ngx_log_t * log) static
Definition at line 111 of file lifecycle_broker.c.
References imp_pidfile(), and log.
Referenced by brix_imp_init_module().
imp_load_idmap()
static ngx_int_t imp_load_idmap (ngx_cycle_t * cycle, uid_t wuid) static
Definition at line 236 of file lifecycle_broker.c.
References BRIX_DIAG_EMERG, brix_idmap_init(), and imp_fill_idmap_conf().
Referenced by brix_imp_init_module().
imp_make_listen()
static int imp_make_listen (const char * path, uid_t wuid, ngx_log_t * log) static
Definition at line 60 of file lifecycle_broker.c.
References BRIX_DIAG_EMERG, close(), log, and ngx_memcpy.
Referenced by imp_open_broker_fds().
imp_open_broker_fds()
static ngx_int_t imp_open_broker_fds (const char * sockbuf, const char * rootbuf, uid_t wuid, ngx_log_t * log, imp_broker_fds_t * fds) static
Definition at line 267 of file lifecycle_broker.c.
References BRIX_DIAG_EMERG, close(), imp_make_listen(), imp_broker_fds_t::lfd, log, O_PATH, open(), and imp_broker_fds_t::rootfd.
Referenced by brix_imp_init_module().
imp_pidfile()
static void imp_pidfile (char * buf, size_t n) static
Definition at line 104 of file lifecycle_broker.c.
References imp_settings, and imp_settings_t::socket.
Referenced by imp_broker_child(), and imp_kill_stale_broker().
imp_resolve_broker_user()
static ngx_int_t imp_resolve_broker_user (ngx_cycle_t * cycle, uid_t wuid) static
Definition at line 191 of file lifecycle_broker.c.
References BRIX_DIAG_EMERG, brix_imp_broker_user_gid, brix_imp_broker_user_uid, imp_settings_t::broker_user, and imp_settings.
Referenced by brix_imp_init_module().
imp_spawn_broker()
static ngx_int_t imp_spawn_broker (int lfd, int rootfd, ngx_log_t * log) static
Definition at line 304 of file lifecycle_broker.c.
References close(), imp_broker_child(), and log.
Referenced by brix_imp_init_module().
imp_worker_uid()
static uid_t imp_worker_uid (ngx_cycle_t * cycle) static
Definition at line 157 of file lifecycle_broker.c.
Referenced by brix_imp_init_module().
Variable Documentation
ngx_test_config
ngx_uint_t ngx_test_config extern
Referenced by imp_init_module_gate().