nginx-xrootd: src/core/compat/lifecycle_timing.h File Reference
lifecycle_timing.h File Reference
#include <ngx_core.h>
#include <stdint.h>
Data Structures
struct brix_phase_timer_t
Macros
#define BRIX_PHASE_SUMMARY_CAP 512
Functions
uint64_t brix_phase_now_ns (void)
void brix_phase_timer_start (brix_phase_timer_t *t)
void brix_phase_mark (brix_phase_timer_t *t, const char *name)
void brix_phase_timer_log (brix_phase_timer_t *t, ngx_log_t *log, const char *context)
Macro Definition Documentation
BRIX_PHASE_SUMMARY_CAP
#define BRIX_PHASE_SUMMARY_CAP 512
Definition at line 43 of file lifecycle_timing.h.
Function Documentation
brix_phase_mark()
void brix_phase_mark (brix_phase_timer_t * t, const char * name)
Definition at line 68 of file lifecycle_timing.c.
References brix_phase_now_ns(), brix_phase_timer_t::last_ns, name, now_ns(), brix_phase_timer_t::pos, brix_phase_timer_t::summary, and us_since().
Referenced by ngx_stream_brix_init_process(), and ngx_stream_brix_postconfiguration().
brix_phase_now_ns()
uint64_t brix_phase_now_ns (void)
Definition at line 21 of file lifecycle_timing.c.
Referenced by brix_configure_gsi(), brix_phase_mark(), brix_phase_timer_log(), brix_phase_timer_start(), ngx_brix_cms_start(), and ngx_brix_cms_write_handler().
brix_phase_timer_log()
void brix_phase_timer_log (brix_phase_timer_t * t, ngx_log_t * log, const char * context)
Definition at line 97 of file lifecycle_timing.c.
References brix_phase_now_ns(), log, brix_phase_timer_t::start_ns, brix_phase_timer_t::summary, and us_since().
Referenced by ngx_stream_brix_init_process(), and ngx_stream_brix_postconfiguration().
brix_phase_timer_start()
void brix_phase_timer_start (brix_phase_timer_t * t)
Definition at line 35 of file lifecycle_timing.c.
References brix_phase_now_ns(), brix_phase_timer_t::last_ns, brix_phase_timer_t::pos, brix_phase_timer_t::start_ns, and brix_phase_timer_t::summary.
Referenced by ngx_stream_brix_init_process(), and ngx_stream_brix_postconfiguration().