nginx-xrootd: src/auth/impersonate/lifecycle.h File Reference
lifecycle.h File Reference
#include "core/ngx_brix_module.h"
#include "core/types/identity.h"
Macros
#define BRIX_IMP_F_SOCKET 1
#define BRIX_IMP_F_EXPORT_ROOT 2
#define BRIX_IMP_F_GRIDMAP 3
#define BRIX_IMP_F_DEFAULT_USER 4
#define BRIX_IMP_F_SINGLE_USER 5
#define BRIX_IMP_F_MIN_UID 6
#define BRIX_IMP_F_CACHE_TTL 7
#define BRIX_IMP_F_BROKER_USER 8
#define BRIX_IMP_F_FORBIDDEN_USERS 9
#define BRIX_IMP_F_FORBIDDEN_GROUPS 10
Functions
char * brix_imp_conf_mode (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_imp_conf_str (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_imp_conf_num (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
ngx_int_t brix_imp_validate (ngx_conf_t *cf, const char *derived_export_root)
ngx_int_t brix_imp_init_module (ngx_cycle_t *cycle)
ngx_int_t brix_imp_init_worker (ngx_cycle_t *cycle)
void brix_imp_worker_harden (ngx_log_t *log)
int brix_imp_cap_held (int cap)
ngx_int_t brix_imp_worker_deescalate (ngx_log_t *log)
char * brix_conf_set_worker_user (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
ngx_int_t brix_imp_worker_runtime_ids (ngx_uid_t conf_uid, ngx_gid_t conf_gid, uid_t *uid_out, gid_t *gid_out)
void brix_imp_request_begin (const brix_identity_t *id)
void brix_imp_request_end (void)
int brix_imp_mode (void)
Variables
char brix_worker_user [64]
Macro Definition Documentation
BRIX_IMP_F_BROKER_USER
#define BRIX_IMP_F_BROKER_USER 8
Definition at line 46 of file lifecycle.h.
BRIX_IMP_F_CACHE_TTL
#define BRIX_IMP_F_CACHE_TTL 7
Definition at line 45 of file lifecycle.h.
BRIX_IMP_F_DEFAULT_USER
#define BRIX_IMP_F_DEFAULT_USER 4
Definition at line 42 of file lifecycle.h.
BRIX_IMP_F_EXPORT_ROOT
#define BRIX_IMP_F_EXPORT_ROOT 2
Definition at line 40 of file lifecycle.h.
BRIX_IMP_F_FORBIDDEN_GROUPS
#define BRIX_IMP_F_FORBIDDEN_GROUPS 10
Definition at line 48 of file lifecycle.h.
BRIX_IMP_F_FORBIDDEN_USERS
#define BRIX_IMP_F_FORBIDDEN_USERS 9
Definition at line 47 of file lifecycle.h.
BRIX_IMP_F_GRIDMAP
#define BRIX_IMP_F_GRIDMAP 3
Definition at line 41 of file lifecycle.h.
BRIX_IMP_F_MIN_UID
#define BRIX_IMP_F_MIN_UID 6
Definition at line 44 of file lifecycle.h.
BRIX_IMP_F_SINGLE_USER
#define BRIX_IMP_F_SINGLE_USER 5
Definition at line 43 of file lifecycle.h.
BRIX_IMP_F_SOCKET
#define BRIX_IMP_F_SOCKET 1
Definition at line 39 of file lifecycle.h.
Function Documentation
brix_conf_set_worker_user()
char * brix_conf_set_worker_user (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 142 of file lifecycle_worker.c.
References brix_worker_user, and ngx_memcpy.
brix_imp_cap_held()
int brix_imp_cap_held (int cap)
Definition at line 50 of file lifecycle_worker.c.
Referenced by brix_imp_worker_deescalate(), and imp_worker_drop_caps().
brix_imp_conf_mode()
char * brix_imp_conf_mode (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 72 of file lifecycle.c.
References BRIX_IMP_MAP, BRIX_IMP_OFF, BRIX_IMP_SINGLE, imp_settings_t::configured, imp_settings, and imp_settings_t::mode.
brix_imp_conf_num()
char * brix_imp_conf_num (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 120 of file lifecycle.c.
References BRIX_IMP_F_CACHE_TTL, BRIX_IMP_F_MIN_UID, imp_settings_t::cache_ttl, imp_settings_t::configured, imp_settings, and imp_settings_t::min_uid.
brix_imp_conf_str()
char * brix_imp_conf_str (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 96 of file lifecycle.c.
References BRIX_IMP_F_BROKER_USER, BRIX_IMP_F_DEFAULT_USER, BRIX_IMP_F_EXPORT_ROOT, BRIX_IMP_F_FORBIDDEN_GROUPS, BRIX_IMP_F_FORBIDDEN_USERS, BRIX_IMP_F_GRIDMAP, BRIX_IMP_F_SINGLE_USER, BRIX_IMP_F_SOCKET, imp_settings_t::broker_user, imp_settings_t::configured, imp_settings_t::default_user, imp_settings_t::export_root, imp_settings_t::forbidden_groups, imp_settings_t::forbidden_users, imp_settings_t::gridmap, imp_dup(), imp_settings, imp_settings_t::single_user, and imp_settings_t::socket.
brix_imp_init_module()
ngx_int_t brix_imp_init_module (ngx_cycle_t * cycle)
Definition at line 369 of file lifecycle_broker.c.
References brix_imp_broker_allow_uid, imp_settings_t::export_root, imp_init_module_gate(), imp_kill_stale_broker(), imp_load_idmap(), imp_open_broker_fds(), imp_resolve_broker_user(), imp_settings, imp_spawn_broker(), imp_worker_uid(), imp_broker_fds_t::lfd, imp_broker_fds_t::rootfd, and imp_settings_t::socket.
brix_imp_init_worker()
ngx_int_t brix_imp_init_worker (ngx_cycle_t * cycle)
Definition at line 322 of file lifecycle_worker.c.
References brix_imp_client_connect(), BRIX_IMP_MAP, imp_settings, imp_settings_t::mode, and imp_settings_t::socket.
Referenced by ngx_stream_brix_init_process().
brix_imp_mode()
int brix_imp_mode (void)
Definition at line 51 of file lifecycle.c.
References imp_settings, and imp_settings_t::mode.
brix_imp_request_begin()
void brix_imp_request_begin (const brix_identity_t * id)
Definition at line 360 of file lifecycle_worker.c.
References BRIX_IMP_MAP, brix_imp_mark_in_request(), brix_imp_set_principal(), imp_principal_of(), imp_settings, and imp_settings_t::mode.
Referenced by brix_dispatch(), ngx_http_brix_webdav_handler(), ngx_http_s3_handler(), propfind_body_handler(), s3_delete_objects_body_handler(), s3_multipart_complete_body_handler(), s3_post_object_body_handler(), s3_put_body_handler(), webdav_handle_lock(), webdav_handle_put_body(), webdav_proppatch_body_handler(), and webdav_search_body_handler().
brix_imp_request_end()
void brix_imp_request_end (void)
Definition at line 373 of file lifecycle_worker.c.
References brix_imp_clear_principal(), BRIX_IMP_MAP, brix_imp_mark_in_request(), imp_settings, and imp_settings_t::mode.
Referenced by brix_dispatch(), ngx_http_brix_webdav_handler(), ngx_http_s3_handler(), propfind_body_handler(), s3_delete_objects_body_handler(), s3_multipart_complete_body_handler(), s3_post_object_body_handler(), s3_put_body_handler(), webdav_handle_lock(), webdav_handle_put_body(), webdav_proppatch_body_handler(), and webdav_search_body_handler().
brix_imp_validate()
ngx_int_t brix_imp_validate (ngx_conf_t * cf, const char * derived_export_root)
Definition at line 145 of file lifecycle.c.
References BRIX_IMP_OFF, BRIX_IMP_SINGLE, imp_settings_t::configured, imp_settings_t::default_user, imp_settings_t::export_root, imp_settings_t::gridmap, IMP_DEFAULT_SOCKET, imp_dup(), imp_settings, imp_settings_t::mode, s, imp_settings_t::single_user, and imp_settings_t::socket.
Referenced by postconf_impersonation().
brix_imp_worker_deescalate()
ngx_int_t brix_imp_worker_deescalate (ngx_log_t * log)
Definition at line 213 of file lifecycle_worker.c.
References brix_imp_cap_held(), brix_imp_worker_harden(), brix_worker_user, and log.
Referenced by ngx_stream_brix_init_process().
brix_imp_worker_harden()
void brix_imp_worker_harden (ngx_log_t * log)
Definition at line 129 of file lifecycle_worker.c.
References imp_worker_drop_caps(), and log.
Referenced by brix_imp_worker_deescalate(), and ngx_stream_brix_init_process().
brix_imp_worker_runtime_ids()
ngx_int_t brix_imp_worker_runtime_ids (ngx_uid_t conf_uid, ngx_gid_t conf_gid, uid_t * uid_out, gid_t * gid_out)
Definition at line 170 of file lifecycle_worker.c.
References brix_worker_user.
Referenced by brix_tier_pblock_hand_to_worker().
Variable Documentation
brix_worker_user
char brix_worker_user[64] extern
Definition at line 139 of file lifecycle_worker.c.
Referenced by brix_conf_set_worker_user(), brix_imp_worker_deescalate(), and brix_imp_worker_runtime_ids().