nginx-xrootd: src/protocols/s3/list_common.c File Reference
list_common.c File Reference
#include "s3.h"
#include "list_cache.h"
#include "core/http/http_query.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
Functions
int s3_list_parse_max_keys (ngx_http_request_t *r, int default_max)
ngx_int_t s3_list_collect_sorted (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const char *prefix, const char *delimiter, s3_entry_t **items, int *total)
int s3_list_paginate (const s3_entry_t *items, int total, const char *start_after, int max_keys, int *start_idx, int *end_idx)
ngx_int_t s3_list_emit_entries (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, s3_entry_t *items, int start_idx, int end_idx, int url_encode, int fetch_owner, u_char *xml, size_t *xml_len_io, size_t xml_capacity, int *contents_out, int *prefixes_out)
ngx_int_t s3_list_finalize (ngx_http_request_t *r, const u_char *xml, size_t xml_len, int contents, int prefixes, int truncated)
Function Documentation
s3_list_collect_sorted()
ngx_int_t s3_list_collect_sorted (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const char * prefix, const char * delimiter, s3_entry_t ** items, int * total)
Definition at line 73 of file list_common.c.
References ngx_http_s3_loc_conf_t::common, entry_cmp(), ngx_http_s3_loc_conf_t::list_cache, ngx_http_s3_loc_conf_t::list_cache_ttl, ngx_http_brix_shared_conf_t::root, s3_list_cache_get(), s3_list_cache_put(), S3_LIST_MAX_ENTRIES, s3_walk(), and stat().
Referenced by s3_handle_list(), and s3_handle_list_v1().
s3_list_emit_entries()
ngx_int_t s3_list_emit_entries (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, s3_entry_t * items, int start_idx, int end_idx, int url_encode, int fetch_owner, u_char * xml, size_t * xml_len_io, size_t xml_capacity, int * contents_out, int * prefixes_out)
Definition at line 160 of file list_common.c.
References ngx_http_s3_loc_conf_t::access_key, brix_format_iso8601(), brix_http_urlencode(), ngx_http_s3_loc_conf_t::common, s3_entry_t::etag, s3_entry_t::is_prefix, s3_entry_t::key, s3_entry_t::mtime, ngx_http_brix_shared_conf_t::root, s3_entry_fill_stat(), S3_MAX_KEY, s3_entry_t::size, XML_APPEND, and XML_APPEND_ELEM.
Referenced by s3_handle_list(), and s3_handle_list_v1().
s3_list_finalize()
ngx_int_t s3_list_finalize (ngx_http_request_t * r, const u_char * xml, size_t xml_len, int contents, int prefixes, int truncated)
Definition at line 232 of file list_common.c.
References brix_http_send_xml_buffer(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_ADD, and BRIX_S3_METRIC_INC.
Referenced by s3_handle_list(), and s3_handle_list_v1().
s3_list_paginate()
int s3_list_paginate (const s3_entry_t * items, int total, const char * start_after, int max_keys, int * start_idx, int * end_idx)
Definition at line 126 of file list_common.c.
References key.
Referenced by s3_handle_list(), and s3_handle_list_v1().
s3_list_parse_max_keys()
int s3_list_parse_max_keys (ngx_http_request_t * r, int default_max)
Definition at line 38 of file list_common.c.
References brix_http_query_get(), mk(), and S3_LIST_QUERY_FLAGS.
Referenced by s3_handle_list_v1(), and s3_list_decode_params().