nginx-xrootd: src/protocols/root/fattr/list.c File Reference
list.c File Reference
#include "ngx_brix_fattr.h"
#include <errno.h>
#include <string.h>
#include <sys/types.h>
#include <arpa/inet.h>
#include "core/compat/alloc_guard.h"
Data Structures
struct fattr_recurse_ctx_t
struct fattr_list_read_t
Macros
#define FATTR_RECURSE_XLIST_BUF 8192
#define FATTR_RECURSE_RESP_CAP (256 * 1024)
#define FATTR_RECURSE_MAX_DEPTH 16
Functions
static void fattr_recurse_bind_deleg (fattr_recurse_ctx_t *rctx, brix_vfs_ctx_t *vctx)
static void fattr_recurse_init_node_ctx (fattr_recurse_ctx_t *rctx, brix_vfs_ctx_t *vctx, const char *node_path)
static void fattr_recurse_emit_names (fattr_recurse_ctx_t *rctx, const char *relpath, const char *xlist, ssize_t list_sz)
static void fattr_recurse_file (fattr_recurse_ctx_t *rctx, const char *fpath, const brix_vfs_stat_t *vst)
static void fattr_recurse_dir (fattr_recurse_ctx_t *rctx, const char *dir_path, int depth)
static ngx_int_t fattr_list_recurse (brix_ctx_t *ctx, ngx_connection_t *c, brix_vfs_ctx_t *vctx, const char *path)
static int fattr_list_try_recurse (brix_ctx_t *ctx, ngx_connection_t *c, brix_vfs_ctx_t *vctx, const char *path, int options, ngx_int_t *out)
static fattr_list_read_t fattr_list_read_names (brix_ctx_t *ctx, ngx_connection_t *c, brix_vfs_ctx_t *vctx, const char *path, int fd)
static void fattr_list_append_value (brix_vfs_ctx_t *vctx, const char *path, int fd, const char *full_key, u_char **wp)
static size_t fattr_list_build (brix_vfs_ctx_t *vctx, const char *path, int fd, int aData, const char *raw, ssize_t actual, u_char *resp, size_t resp_cap)
ngx_int_t fattr_list (brix_ctx_t *ctx, ngx_connection_t *c, brix_vfs_ctx_t *vctx, const char *path, int fd, int options)
Macro Definition Documentation
FATTR_RECURSE_MAX_DEPTH
#define FATTR_RECURSE_MAX_DEPTH 16
Definition at line 23 of file list.c.
FATTR_RECURSE_RESP_CAP
#define FATTR_RECURSE_RESP_CAP (256 * 1024)
Definition at line 22 of file list.c.
FATTR_RECURSE_XLIST_BUF
#define FATTR_RECURSE_XLIST_BUF 8192
Definition at line 21 of file list.c.
Function Documentation
fattr_list()
ngx_int_t fattr_list (brix_ctx_t * ctx, ngx_connection_t * c, brix_vfs_ctx_t * vctx, const char * path, int fd, int options)
Definition at line 522 of file list.c.
References fattr_list_read_t::actual, BRIX_OP_FATTR, BRIX_OP_OK, brix_send_error(), brix_send_ok(), c, fattr_list_read_t::done, fattr_list_build(), fattr_list_read_names(), fattr_list_try_recurse(), kXR_fa_aData, kXR_faMaxVars, kXR_NoMemory, fattr_list_read_t::raw, and fattr_list_read_t::rc.
Referenced by brix_handle_fattr().
fattr_list_append_value()
static void fattr_list_append_value (brix_vfs_ctx_t * vctx, const char * path, int fd, const char * full_key, u_char ** wp) static
Definition at line 430 of file list.c.
References brix_vfs_fgetxattr(), brix_vfs_getxattr(), and ngx_memcpy.
Referenced by fattr_list_build().
fattr_list_build()
static size_t fattr_list_build (brix_vfs_ctx_t * vctx, const char * path, int fd, int aData, const char * raw, ssize_t actual, u_char * resp, size_t resp_cap) static
Definition at line 464 of file list.c.
References BRIX_FATTR_XKEY_PFX, BRIX_FATTR_XKEY_PFX_LEN, fattr_list_append_value(), and ngx_memcpy.
Referenced by fattr_list().
fattr_list_read_names()
static fattr_list_read_t fattr_list_read_names (brix_ctx_t * ctx, ngx_connection_t * c, brix_vfs_ctx_t * vctx, const char * path, int fd) static
Definition at line 360 of file list.c.
References fattr_list_read_t::actual, BRIX_OP_ERR, BRIX_OP_FATTR, BRIX_OP_OK, brix_send_error(), brix_send_ok(), brix_vfs_flistxattr(), brix_vfs_listxattr(), c, fattr_list_read_t::done, kXR_FSError, kXR_NoMemory, fattr_list_read_t::raw, and fattr_list_read_t::rc.
Referenced by fattr_list().
fattr_list_recurse()
static ngx_int_t fattr_list_recurse (brix_ctx_t * ctx, ngx_connection_t * c, brix_vfs_ctx_t * vctx, const char * path) static
Definition at line 265 of file list.c.
References BRIX_OP_FATTR, BRIX_OP_OK, BRIX_PALLOC_OR_RETURN, brix_send_error(), brix_send_ok(), brix_vfs_deleg_snapshot(), fattr_recurse_ctx_t::buf, c, fattr_recurse_ctx_t::cap, fattr_recurse_ctx_t::deleg_bearer, fattr_recurse_ctx_t::deleg_mode, fattr_recurse_dir(), FATTR_RECURSE_RESP_CAP, brix_vfs_ctx_t::identity, fattr_recurse_ctx_t::identity, kXR_NoMemory, fattr_recurse_ctx_t::len, brix_vfs_ctx_t::log, fattr_recurse_ctx_t::log, brix_vfs_ctx_t::pool, fattr_recurse_ctx_t::pool, brix_vfs_ctx_t::root_canon, fattr_recurse_ctx_t::root_canon, fattr_recurse_ctx_t::root_len, brix_vfs_ctx_t::storage_cred_deny, brix_vfs_ctx_t::storage_cred_dir, fattr_recurse_ctx_t::storage_cred_dir, and fattr_recurse_ctx_t::storage_cred_fallback.
Referenced by fattr_list_try_recurse().
fattr_list_try_recurse()
static int fattr_list_try_recurse (brix_ctx_t * ctx, ngx_connection_t * c, brix_vfs_ctx_t * vctx, const char * path, int options, ngx_int_t * out) static
Definition at line 329 of file list.c.
References brix_vfs_probe(), c, fattr_list_recurse(), brix_vfs_stat_t::is_directory, and kXR_fa_recurse.
Referenced by fattr_list().
fattr_recurse_bind_deleg()
static void fattr_recurse_bind_deleg (fattr_recurse_ctx_t * rctx, brix_vfs_ctx_t * vctx) static
Definition at line 56 of file list.c.
References brix_vfs_deleg_bind(), fattr_recurse_ctx_t::deleg_bearer, fattr_recurse_ctx_t::deleg_mode, and fattr_recurse_ctx_t::pool.
Referenced by fattr_recurse_init_node_ctx().
fattr_recurse_dir()
static void fattr_recurse_dir (fattr_recurse_ctx_t * rctx, const char * dir_path, int depth) static
Definition at line 205 of file list.c.
References BRIX_PATH_MAX, brix_vfs_closedir(), brix_vfs_opendir_quiet(), brix_vfs_readdir(), fattr_recurse_dir(), fattr_recurse_file(), fattr_recurse_init_node_ctx(), FATTR_RECURSE_MAX_DEPTH, brix_vfs_stat_t::is_directory, fattr_recurse_ctx_t::log, and name.
Referenced by fattr_list_recurse(), and fattr_recurse_dir().
fattr_recurse_emit_names()
static void fattr_recurse_emit_names (fattr_recurse_ctx_t * rctx, const char * relpath, const char * xlist, ssize_t list_sz) static
Definition at line 101 of file list.c.
References BRIX_FATTR_XKEY_PFX, BRIX_FATTR_XKEY_PFX_LEN, fattr_recurse_ctx_t::buf, fattr_recurse_ctx_t::len, and ngx_memcpy.
Referenced by fattr_recurse_file().
fattr_recurse_file()
static void fattr_recurse_file (fattr_recurse_ctx_t * rctx, const char * fpath, const brix_vfs_stat_t * vst) static
Definition at line 157 of file list.c.
References brix_vfs_listxattr(), fattr_recurse_emit_names(), fattr_recurse_init_node_ctx(), FATTR_RECURSE_XLIST_BUF, brix_vfs_stat_t::is_regular, and fattr_recurse_ctx_t::root_len.
Referenced by fattr_recurse_dir().
fattr_recurse_init_node_ctx()
static void fattr_recurse_init_node_ctx (fattr_recurse_ctx_t * rctx, brix_vfs_ctx_t * vctx, const char * node_path) static
Definition at line 76 of file list.c.
References BRIX_PROTO_ROOT, brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), fattr_recurse_bind_deleg(), fattr_recurse_ctx_t::identity, fattr_recurse_ctx_t::log, fattr_recurse_ctx_t::pool, fattr_recurse_ctx_t::root_canon, fattr_recurse_ctx_t::storage_cred_dir, and fattr_recurse_ctx_t::storage_cred_fallback.
Referenced by fattr_recurse_dir(), and fattr_recurse_file().