nginx-xrootd: src/protocols/s3/list_cache.h File Reference
list_cache.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include "s3.h"
Macros
#define S3_LIST_CACHE_MAX_ENTRIES 20000
Functions
int s3_list_cache_get (ngx_http_request_t *r, const char *root, const char *prefix, const char *delimiter, time_t dir_mtime, ngx_msec_t ttl_ms, s3_entry_t **out_items, int *out_n)
void s3_list_cache_put (ngx_log_t *log, const char *root, const char *prefix, const char *delimiter, time_t dir_mtime, const s3_entry_t *items, int n)
Macro Definition Documentation
S3_LIST_CACHE_MAX_ENTRIES
#define S3_LIST_CACHE_MAX_ENTRIES 20000
Definition at line 35 of file list_cache.h.
Function Documentation
s3_list_cache_get()
int s3_list_cache_get (ngx_http_request_t * r, const char * root, const char * prefix, const char * delimiter, time_t dir_mtime, ngx_msec_t ttl_ms, s3_entry_t ** out_items, int * out_n)
Definition at line 80 of file list_cache.c.
References s3_entry_t::is_prefix, s3_entry_t::key, ngx_memcpy, ngx_pcalloc(), ngx_pnalloc(), s, s3_lc_matches(), s3_lc_seq, s3_lc_slot_clear(), s3_lc_slots, and S3_LIST_CACHE_SLOTS.
Referenced by s3_list_collect_sorted().
s3_list_cache_put()
void s3_list_cache_put (ngx_log_t * log, const char * root, const char * prefix, const char * delimiter, time_t dir_mtime, const s3_entry_t * items, int n)
Definition at line 259 of file list_cache.c.
References log, s3_lc_copy_entries(), s3_lc_select_victim(), s3_lc_slot_clear(), s3_lc_slot_store(), and s3_lc_within_cap().
Referenced by s3_list_collect_sorted().