nginx-xrootd: src/protocols/s3/list_walk.c File Reference
list_walk.c File Reference
#include "s3.h"
#include "core/compat/fs_walk.h"
#include "fs/vfs/vfs.h"
#include "fs/path/path.h"
#include "fs/path/reserved_names.h"
#include <errno.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <dirent.h>
#include <string.h>
#include <stdio.h>
#include <limits.h>
#include <time.h>
#include "core/compat/alloc_guard.h"
Data Structures
struct s3_walk_ctx_t
struct s3_child_paths_t
Functions
int entry_cmp (const void *a, const void *b)
static int s3_walk_push (ngx_array_t *entries, const char *key, unsigned is_prefix)
static int s3_walk_classify (ngx_pool_t *pool, ngx_log_t *log, const char *root, const char *child_path, brix_vfs_dirent_kind_t dkind)
static int s3_walk_run (s3_walk_ctx_t *ctx, const char *dir_path, const char *key_prefix)
static int s3_walk_build_paths (const char *dir_path, const char *key_prefix, const ngx_str_t *name, s3_child_paths_t *out)
static int s3_walk_emit_dir (s3_walk_ctx_t *ctx, const char *child_path, const char *child_key)
static int s3_walk_emit_file (s3_walk_ctx_t *ctx, const char *child_key, const char *dname)
static int s3_walk_entry (s3_walk_ctx_t *ctx, const char *dir_path, const char *key_prefix, const ngx_str_t *name, brix_vfs_dirent_kind_t dkind)
int s3_walk (ngx_log_t *log, const char *root, const char *dir_path, const char *key_prefix, const char *filter_prefix, const char *delimiter, ngx_array_t *entries, int max_entries)
ngx_int_t s3_entry_fill_stat (ngx_pool_t *pool, ngx_log_t *log, const char *root, s3_entry_t *e)
Function Documentation
entry_cmp()
int entry_cmp (const void * a, const void * b)
Definition at line 53 of file list_walk.c.
References key.
Referenced by s3_list_collect_sorted().
s3_entry_fill_stat()
ngx_int_t s3_entry_fill_stat (ngx_pool_t * pool, ngx_log_t * log, const char * root, s3_entry_t * e)
Definition at line 455 of file list_walk.c.
References BRIX_PROTO_S3, brix_vfs_ctx_init(), brix_vfs_probe(), s3_entry_t::etag, s3_entry_t::is_prefix, brix_vfs_stat_t::is_regular, s3_entry_t::key, log, brix_vfs_stat_t::mtime, s3_entry_t::mtime, PATH_MAX, s3_etag(), brix_vfs_stat_t::size, s3_entry_t::size, and stat().
Referenced by s3_list_emit_entries().
s3_walk()
int s3_walk (ngx_log_t * log, const char * root, const char * dir_path, const char * key_prefix, const char * filter_prefix, const char * delimiter, ngx_array_t * entries, int max_entries)
Definition at line 425 of file list_walk.c.
References s3_walk_ctx_t::del_len, s3_walk_ctx_t::delimiter, s3_walk_ctx_t::entries, s3_walk_ctx_t::filter_prefix, s3_walk_ctx_t::fp_len, log, s3_walk_ctx_t::log, s3_walk_ctx_t::max_entries, s3_walk_ctx_t::root, and s3_walk_run().
Referenced by s3_list_collect_sorted().
s3_walk_build_paths()
static int s3_walk_build_paths (const char * dir_path, const char * key_prefix, const ngx_str_t * name, s3_child_paths_t * out) static
Definition at line 189 of file list_walk.c.
References s3_child_paths_t::key, name, and s3_child_paths_t::path.
Referenced by s3_walk_entry().
s3_walk_classify()
static int s3_walk_classify (ngx_pool_t * pool, ngx_log_t * log, const char * root, const char * child_path, brix_vfs_dirent_kind_t dkind) static
Definition at line 92 of file list_walk.c.
References BRIX_PROTO_S3, brix_vfs_ctx_init(), BRIX_VFS_DT_DIR, BRIX_VFS_DT_OTHER, BRIX_VFS_DT_REG, BRIX_VFS_DT_UNKNOWN, brix_vfs_probe(), brix_vfs_stat_t::is_directory, brix_vfs_stat_t::is_regular, and log.
Referenced by s3_walk_entry().
s3_walk_emit_dir()
static int s3_walk_emit_dir (s3_walk_ctx_t * ctx, const char * child_path, const char * child_key) static
Definition at line 228 of file list_walk.c.
References s3_walk_ctx_t::del_len, s3_walk_ctx_t::entries, s3_walk_ctx_t::filter_prefix, s3_walk_ctx_t::fp_len, S3_MAX_KEY, s3_walk_push(), and s3_walk_run().
Referenced by s3_walk_entry().
s3_walk_emit_file()
static int s3_walk_emit_file (s3_walk_ctx_t * ctx, const char * child_key, const char * dname) static
Definition at line 284 of file list_walk.c.
References brix_is_internal_name(), s3_walk_ctx_t::del_len, s3_walk_ctx_t::delimiter, s3_walk_ctx_t::entries, s3_walk_ctx_t::filter_prefix, s3_walk_ctx_t::fp_len, S3_DIR_SENTINEL, and s3_walk_push().
Referenced by s3_walk_entry().
s3_walk_entry()
static int s3_walk_entry (s3_walk_ctx_t * ctx, const char * dir_path, const char * key_prefix, const ngx_str_t * name, brix_vfs_dirent_kind_t dkind) static
Definition at line 331 of file list_walk.c.
References s3_walk_ctx_t::entries, s3_child_paths_t::key, s3_walk_ctx_t::log, name, s3_child_paths_t::path, s3_walk_ctx_t::root, s3_walk_build_paths(), s3_walk_classify(), s3_walk_emit_dir(), and s3_walk_emit_file().
Referenced by s3_walk_run().
s3_walk_push()
static int s3_walk_push (ngx_array_t * entries, const char * key, unsigned is_prefix) static
Definition at line 64 of file list_walk.c.
References BRIX_PNALLOC_OR_RETURN, s3_entry_t::etag, s3_entry_t::is_prefix, key, s3_entry_t::key, s3_entry_t::mtime, ngx_memcpy, and s3_entry_t::size.
Referenced by s3_walk_emit_dir(), and s3_walk_emit_file().
s3_walk_run()
static int s3_walk_run (s3_walk_ctx_t * ctx, const char * dir_path, const char * key_prefix) static
Definition at line 371 of file list_walk.c.
References brix_dirlist_access_ok(), BRIX_PROTO_S3, brix_vfs_closedir(), brix_vfs_ctx_init(), brix_vfs_opendir_quiet(), brix_vfs_readdir_kind(), s3_walk_ctx_t::entries, s3_walk_ctx_t::log, s3_walk_ctx_t::max_entries, name, s3_walk_ctx_t::root, and s3_walk_entry().
Referenced by s3_walk(), and s3_walk_emit_dir().