nginx-xrootd: src/protocols/s3/list_cache.c File Reference
list_cache.c File Reference
#include "list_cache.h"
#include <string.h>
Data Structures
struct s3_lc_entry_t
struct s3_lc_id_t
struct s3_lc_slot_t
Macros
#define S3_LIST_CACHE_SLOTS 16
Functions
static char * s3_lc_strdup (const char *s)
static void s3_lc_slot_clear (s3_lc_slot_t *s)
static int s3_lc_matches (const s3_lc_slot_t *s, const s3_lc_id_t *id)
int s3_list_cache_get (ngx_http_request_t *r, const char *root, const char *prefix, const char *delimiter, time_t dir_mtime, ngx_msec_t ttl_ms, s3_entry_t **out_items, int *out_n)
static int s3_lc_within_cap (ngx_log_t *log, int n)
static s3_lc_slot_t * s3_lc_select_victim (const s3_lc_id_t *id)
static s3_lc_entry_t * s3_lc_copy_entries (ngx_log_t *log, const s3_entry_t *items, int n)
static int s3_lc_slot_store (s3_lc_slot_t *victim, const s3_lc_id_t *id, time_t dir_mtime, s3_lc_entry_t *copy, int n)
void s3_list_cache_put (ngx_log_t *log, const char *root, const char *prefix, const char *delimiter, time_t dir_mtime, const s3_entry_t *items, int n)
Variables
static s3_lc_slot_t s3_lc_slots [16]
static uint64_t s3_lc_seq
Macro Definition Documentation
S3_LIST_CACHE_SLOTS
#define S3_LIST_CACHE_SLOTS 16
Definition at line 10 of file list_cache.c.
Function Documentation
s3_lc_copy_entries()
static s3_lc_entry_t * s3_lc_copy_entries (ngx_log_t * log, const s3_entry_t * items, int n) static
Definition at line 201 of file list_cache.c.
References s3_lc_entry_t::is_prefix, s3_entry_t::is_prefix, key, s3_lc_entry_t::key, log, and s3_lc_strdup().
Referenced by s3_list_cache_put().
s3_lc_matches()
static int s3_lc_matches (const s3_lc_slot_t * s, const s3_lc_id_t * id) static
Definition at line 71 of file list_cache.c.
References s3_lc_id_t::delimiter, s3_lc_id_t::prefix, s3_lc_id_t::root, and s.
Referenced by s3_lc_select_victim(), and s3_list_cache_get().
s3_lc_select_victim()
static s3_lc_slot_t * s3_lc_select_victim (const s3_lc_id_t * id) static
Definition at line 165 of file list_cache.c.
References s3_lc_matches(), s3_lc_slots, S3_LIST_CACHE_SLOTS, s3_lc_slot_t::seq, and s3_lc_slot_t::used.
Referenced by s3_list_cache_put().
s3_lc_slot_clear()
static void s3_lc_slot_clear (s3_lc_slot_t * s) static
Definition at line 54 of file list_cache.c.
References s.
Referenced by s3_lc_slot_store(), s3_list_cache_get(), and s3_list_cache_put().
s3_lc_slot_store()
static int s3_lc_slot_store (s3_lc_slot_t * victim, const s3_lc_id_t * id, time_t dir_mtime, s3_lc_entry_t * copy, int n) static
Definition at line 232 of file list_cache.c.
References s3_lc_id_t::delimiter, s3_lc_slot_t::delimiter, s3_lc_slot_t::dir_mtime, s3_lc_slot_t::entries, key, s3_lc_slot_t::n, s3_lc_id_t::prefix, s3_lc_slot_t::prefix, s3_lc_id_t::root, s3_lc_slot_t::root, s3_lc_seq, s3_lc_slot_clear(), s3_lc_strdup(), s3_lc_slot_t::seq, s3_lc_slot_t::stored_at, and s3_lc_slot_t::used.
Referenced by s3_list_cache_put().
s3_lc_strdup()
static char * s3_lc_strdup (const char * s) static
Definition at line 42 of file list_cache.c.
References ngx_memcpy, and s.
Referenced by s3_lc_copy_entries(), and s3_lc_slot_store().
s3_lc_within_cap()
static int s3_lc_within_cap (ngx_log_t * log, int n) static
Definition at line 138 of file list_cache.c.
References log, and S3_LIST_CACHE_MAX_ENTRIES.
Referenced by s3_list_cache_put().
s3_list_cache_get()
int s3_list_cache_get (ngx_http_request_t * r, const char * root, const char * prefix, const char * delimiter, time_t dir_mtime, ngx_msec_t ttl_ms, s3_entry_t ** out_items, int * out_n)
Definition at line 80 of file list_cache.c.
References s3_entry_t::is_prefix, s3_entry_t::key, ngx_memcpy, ngx_pcalloc(), ngx_pnalloc(), s, s3_lc_matches(), s3_lc_seq, s3_lc_slot_clear(), s3_lc_slots, and S3_LIST_CACHE_SLOTS.
Referenced by s3_list_collect_sorted().
s3_list_cache_put()
void s3_list_cache_put (ngx_log_t * log, const char * root, const char * prefix, const char * delimiter, time_t dir_mtime, const s3_entry_t * items, int n)
Definition at line 259 of file list_cache.c.
References log, s3_lc_copy_entries(), s3_lc_select_victim(), s3_lc_slot_clear(), s3_lc_slot_store(), and s3_lc_within_cap().
Referenced by s3_list_collect_sorted().
Variable Documentation
s3_lc_seq
uint64_t s3_lc_seq static
Definition at line 39 of file list_cache.c.
Referenced by s3_lc_slot_store(), and s3_list_cache_get().
s3_lc_slots
s3_lc_slot_t s3_lc_slots[16] static
Definition at line 38 of file list_cache.c.
Referenced by s3_lc_select_victim(), and s3_list_cache_get().