nginx-xrootd: src/protocols/s3/list_objects_v1.c File Reference
list_objects_v1.c File Reference
#include "s3.h"
#include "core/http/http_query.h"
#include <string.h>
Functions
ngx_int_t s3_handle_list_v1 (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf)
Function Documentation
s3_handle_list_v1()
ngx_int_t s3_handle_list_v1 (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf)
Definition at line 33 of file list_objects_v1.c.
References brix_http_query_get(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, ngx_http_s3_loc_conf_t::bucket, key, ngx_http_s3_loc_conf_t::max_keys, s3_list_collect_sorted(), s3_list_emit_entries(), s3_list_finalize(), s3_list_paginate(), s3_list_parse_max_keys(), S3_LIST_QUERY_FLAGS, S3_MAX_KEY, S3_MAX_PARAM, XML_APPEND, and XML_APPEND_ELEM.
Referenced by s3_dispatch_bucket_get().