nginx-xrootd: src/auth/voms/loader.c File Reference
loader.c File Reference
#include "voms_internal.h"
#include <dlfcn.h>
Macros
#define LOAD_SYM(field, name)
Functions
ngx_flag_t brix_voms_available (void)
ngx_int_t brix_voms_init (ngx_log_t *log)
Variables
brix_voms_api_t brix_voms_api
ngx_flag_t brix_voms_loaded
Macro Definition Documentation
LOAD_SYM
#define LOAD_SYM (field, name)
Value:
    do {                                                              \
        *(void **) (&brix_voms_api.field) =                         \
            dlsym(brix_voms_api.handle, #name);                     \
        if (brix_voms_api.field == NULL) {                          \
            ngx_log_error(NGX_LOG_ERR, log, 0,                        \
                          "brix: dlsym(%s) failed: %s",             \
                          #name, dlerror());                          \
            dlclose(brix_voms_api.handle);                          \
            ngx_memzero(&brix_voms_api, sizeof(brix_voms_api));    \
            return NGX_ERROR;                                         \
        }                                                             \
    } while (0)
Function Documentation
brix_voms_available()
ngx_flag_t brix_voms_available (void)
Definition at line 20 of file loader.c.
References brix_voms_loaded.
Referenced by brix_config_finalize_policy(), gsi_cert_extract_voms(), and webdav_extract_and_set_voms_identity().
brix_voms_init()
ngx_int_t brix_voms_init (ngx_log_t * log)
Definition at line 32 of file loader.c.
References brix_voms_api, brix_voms_loaded, brix_voms_api_t::handle, LOAD_SYM, and log.
Referenced by ngx_stream_brix_postconfiguration(), and webdav_finalize_authz_rules().
Variable Documentation
brix_voms_api
brix_voms_api_t brix_voms_api
Definition at line 12 of file loader.c.
Referenced by brix_extract_voms_info(), brix_voms_init(), and brix_voms_retrieve_and_collect().
brix_voms_loaded
ngx_flag_t brix_voms_loaded
Definition at line 13 of file loader.c.
Referenced by brix_voms_available(), brix_voms_init(), and brix_voms_precheck().