nginx-xrootd: src/net/manager/loc_cache.c File Reference
loc_cache.c File Reference
#include "loc_cache.h"
#include "core/ngx_brix_module.h"
#include "core/fnv.h"
#include "core/compat/shm_slots.h"
Functions
static brix_loc_table_t * loc_table (void)
static uint32_t loc_hash (const char *path)
static ngx_int_t loc_cache_shm_init_zone (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t brix_loc_cache_configure (ngx_conf_t *cf)
int brix_loc_cache_lookup (const char *path, char *host, size_t host_sz, uint16_t *port)
void brix_loc_cache_insert (const char *path, const char *host, uint16_t port)
Variables
ngx_shm_zone_t * brix_loc_cache_shm_zone
static ngx_shmtx_t brix_loc_cache_mutex
Function Documentation
brix_loc_cache_configure()
ngx_int_t brix_loc_cache_configure (ngx_conf_t * cf)
Definition at line 67 of file loc_cache.c.
References brix_loc_cache_shm_zone, brix_shm_zone_size(), loc_cache_shm_init_zone(), and ngx_stream_brix_module.
Referenced by postconf_shared_registries().
brix_loc_cache_insert()
void brix_loc_cache_insert (const char * path, const char * host, uint16_t port)
Definition at line 129 of file loc_cache.c.
References brix_loc_cache_mutex, BRIX_LOC_CACHE_PATH_MAX, BRIX_LOC_CACHE_SLOTS, BRIX_LOC_CACHE_TTL_MS, brix_shm_slot_expired(), brix_loc_entry_t::expires, host, brix_loc_entry_t::host, brix_loc_entry_t::in_use, loc_hash(), loc_table(), brix_loc_entry_t::path, brix_loc_entry_t::path_hash, port, brix_loc_entry_t::port, and brix_loc_table_t::slots.
Referenced by cms_srv_frame_have().
brix_loc_cache_lookup()
int brix_loc_cache_lookup (const char * path, char * host, size_t host_sz, uint16_t * port)
Definition at line 85 of file loc_cache.c.
References brix_loc_cache_mutex, BRIX_LOC_CACHE_PATH_MAX, BRIX_LOC_CACHE_SLOTS, brix_shm_slot_expired(), brix_loc_entry_t::expires, host, brix_loc_entry_t::host, brix_loc_entry_t::in_use, loc_hash(), loc_table(), brix_loc_entry_t::path, brix_loc_entry_t::path_hash, port, brix_loc_entry_t::port, and brix_loc_table_t::slots.
Referenced by locate_try_dynamic().
loc_cache_shm_init_zone()
static ngx_int_t loc_cache_shm_init_zone (ngx_shm_zone_t * shm_zone, void * data) static
Definition at line 48 of file loc_cache.c.
References brix_loc_cache_mutex, brix_shm_table_alloc(), and brix_loc_table_t::slots.
Referenced by brix_loc_cache_configure().
loc_hash()
static uint32_t loc_hash (const char * path) static
Definition at line 36 of file loc_cache.c.
References BRIX_FNV1A32_OFFSET_BASIS, and BRIX_FNV1A32_PRIME.
Referenced by brix_loc_cache_insert(), and brix_loc_cache_lookup().
loc_table()
static brix_loc_table_t * loc_table (void) static
Definition at line 22 of file loc_cache.c.
References brix_loc_cache_shm_zone.
Referenced by brix_loc_cache_insert(), and brix_loc_cache_lookup().
Variable Documentation
brix_loc_cache_mutex
ngx_shmtx_t brix_loc_cache_mutex static
Definition at line 17 of file loc_cache.c.
Referenced by brix_loc_cache_insert(), brix_loc_cache_lookup(), and loc_cache_shm_init_zone().
brix_loc_cache_shm_zone
ngx_shm_zone_t* brix_loc_cache_shm_zone
Definition at line 15 of file loc_cache.c.
Referenced by brix_loc_cache_configure(), and loc_table().