nginx-xrootd: src/protocols/root/read/locate.c File Reference
locate.c File Reference
#include "core/ngx_brix_module.h"
#include "net/upstream/upstream.h"
#include "protocols/root/path/op_path.h"
#include "net/manager/registry.h"
#include "net/manager/redir_cache.h"
#include "net/manager/pending.h"
#include "net/cms/cms_internal.h"
#include <arpa/inet.h>
Data Structures
struct locate_ctx_t
Functions
static int locate_resolve_reqpath (locate_ctx_t *lc, ngx_int_t *out_rc)
static int locate_try_cms_parent (locate_ctx_t *lc, ngx_int_t *out_rc)
static int locate_try_manager (locate_ctx_t *lc, ngx_int_t *out_rc)
static int locate_try_manager_map (locate_ctx_t *lc, ngx_int_t *out_rc)
static int locate_check_data_server (locate_ctx_t *lc, ngx_int_t *out_rc)
static int locate_format_local (ngx_stream_brix_srv_conf_t *conf, ngx_connection_t *c, char *loc_buf, size_t loc_sz)
ngx_int_t brix_handle_locate (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_handle_locate()
ngx_int_t brix_handle_locate (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 370 of file locate.c.
References brix_log_access(), BRIX_MAX_PATH, BRIX_OP_LOCATE, BRIX_OP_OK, brix_send_ok(), c, locate_ctx_t::ctx, locate_check_data_server(), locate_format_local(), locate_resolve_reqpath(), locate_try_manager(), and locate_try_manager_map().
Referenced by brix_dispatch_read_opcode().
locate_check_data_server()
static int locate_check_data_server (locate_ctx_t * lc, ngx_int_t * out_rc) static
Definition at line 278 of file locate.c.
References brix_auth_gate(), BRIX_AUTH_READ, brix_beneath_full_path(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_LOCATE, BRIX_OP_OK, brix_send_error(), brix_stat_beneath(), brix_upstream_start(), c, locate_ctx_t::c, locate_ctx_t::conf, locate_ctx_t::ctx, locate_ctx_t::is_wildcard, kXR_NotFound, PATH_MAX, locate_ctx_t::reqpath, stat(), and brix_ctx_t::write_rc.
Referenced by brix_handle_locate().
locate_format_local()
static int locate_format_local (ngx_stream_brix_srv_conf_t * conf, ngx_connection_t * c, char * loc_buf, size_t loc_sz) static
Definition at line 334 of file locate.c.
References c.
Referenced by brix_handle_locate().
locate_resolve_reqpath()
static int locate_resolve_reqpath (locate_ctx_t * lc, ngx_int_t * out_rc) static
Definition at line 77 of file locate.c.
References brix_count_path_depth(), brix_extract_path(), BRIX_OP_ERR, BRIX_OP_LOCATE, brix_reject_dotdot_path(), brix_send_error(), c, locate_ctx_t::c, locate_ctx_t::ctx, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::hdr_buf, locate_ctx_t::is_wildcard, kXR_ArgInvalid, kXR_ArgMissing, xrdw_locate_req_t::options, brix_ctx_recv_t::payload, brix_ctx_t::recv, locate_ctx_t::reqpath, locate_ctx_t::reqpath_sz, brix_ctx_t::write_rc, and xrdw_locate_req_unpack().
Referenced by brix_handle_locate().
locate_try_cms_parent()
static int locate_try_cms_parent (locate_ctx_t * lc, ngx_int_t * out_rc) static
Definition at line 139 of file locate.c.
References brix_pending_insert(), brix_pending_remove(), c, locate_ctx_t::c, brix_ctx_t::cms_wait_streamid, locate_ctx_t::conf, locate_ctx_t::ctx, brix_ctx_recv_t::cur_streamid, ngx_brix_cms_next_streamid(), ngx_brix_cms_send_locate(), brix_ctx_t::recv, locate_ctx_t::reqpath, brix_ctx_t::state, XRD_ST_REQ_HEADER, and XRD_ST_WAITING_CMS.
Referenced by locate_try_manager().
locate_try_manager()
static int locate_try_manager (locate_ctx_t * lc, ngx_int_t * out_rc) static
Definition at line 183 of file locate.c.
References brix_log_access(), BRIX_OP_LOCATE, BRIX_OP_OK, brix_redir_cache_insert(), brix_redir_cache_lookup(), brix_send_redirect(), brix_srv_select(), c, locate_ctx_t::c, locate_ctx_t::conf, locate_ctx_t::ctx, locate_ctx_t::is_wildcard, locate_try_cms_parent(), and locate_ctx_t::reqpath.
Referenced by brix_handle_locate().
locate_try_manager_map()
static int locate_try_manager_map (locate_ctx_t * lc, ngx_int_t * out_rc) static
Definition at line 243 of file locate.c.
References brix_find_manager_map(), brix_log_access(), BRIX_OP_LOCATE, BRIX_OP_OK, brix_send_redirect(), c, locate_ctx_t::c, locate_ctx_t::conf, locate_ctx_t::ctx, brix_manager_map_t::host, locate_ctx_t::is_wildcard, brix_manager_map_t::port, and locate_ctx_t::reqpath.
Referenced by brix_handle_locate().