nginx-xrootd: src/protocols/root/read/locate.h File Reference
locate.h File Reference
#include "core/ngx_brix_module.h"
Functions
ngx_int_t brix_handle_locate (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_handle_locate()
ngx_int_t brix_handle_locate (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 44 of file locate.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_auth_gate(), BRIX_AUTH_READ, brix_beneath_full_path(), brix_count_path_depth(), brix_extract_path(), brix_find_manager_map(), brix_log_access(), BRIX_MAX_PATH, BRIX_OP_ERR, BRIX_OP_LOCATE, BRIX_OP_OK, brix_pending_insert(), brix_pending_remove(), brix_redir_cache_insert(), brix_redir_cache_lookup(), brix_reject_dotdot_path(), BRIX_RETURN_ERR, brix_send_error(), brix_send_ok(), brix_send_redirect(), brix_srv_select(), brix_stat_beneath(), brix_upstream_start(), c, ngx_stream_brix_srv_conf_t::caps, ngx_stream_brix_srv_conf_t::cms, brix_ctx_t::cms_wait_streamid, brix_node_caps_conf_t::collapse_redir, brix_node_caps_conf_t::collapse_redir_ttl, ngx_stream_brix_srv_conf_t::common, brix_cms_conf_t::ctx, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_streamid, brix_ctx_recv_t::hdr_buf, brix_manager_map_t::host, kXR_ArgInvalid, kXR_ArgMissing, kXR_NotFound, brix_cms_conf_t::locate_timeout, ngx_stream_brix_srv_conf_t::manager_map, ngx_stream_brix_srv_conf_t::manager_mode, ngx_brix_cms_next_streamid(), ngx_brix_cms_send_locate(), xrdw_locate_req_t::options, PATH_MAX, brix_ctx_recv_t::payload, brix_manager_map_t::port, brix_ctx_t::recv, ngx_http_brix_shared_conf_t::root_canon, ngx_stream_brix_srv_conf_t::rootfd, stat(), brix_ctx_t::state, ngx_stream_brix_srv_conf_t::upstream_host, brix_ctx_t::write_rc, XRD_ST_REQ_HEADER, XRD_ST_WAITING_CMS, and xrdw_locate_req_unpack().
Referenced by brix_dispatch_read_opcode().