nginx-xrootd: src/protocols/webdav/lock_discovery.c File Reference
lock_discovery.c File Reference
#include "webdav.h"
#include "fs/path/path.h"
#include "fs/vfs/vfs.h"
#include "auth/impersonate/lifecycle.h"
#include "protocols/webdav/locks/request.h"
#include "core/http/http_xml.h"
#include "core/compat/fs_walk.h"
#include <openssl/crypto.h>
#include <openssl/rand.h>
#include <dirent.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/xattr.h>
#include <time.h>
#include "lock_internal.h"
Data Structures
struct webdav_lock_sweep_ctx_t
Macros
#define NGX_HTTP_LOCKED 423
Functions
static void webdav_lock_sweep_remove (webdav_lock_sweep_ctx_t *sw, const char *path)
static ngx_int_t webdav_lock_sweep_cb (const brix_fs_walk_entry_t *entry, void *data)
ngx_uint_t webdav_lock_startup_sweep (ngx_pool_t *pool, ngx_log_t *log, const char *root_canon)
ngx_int_t webdav_handle_unlock (ngx_http_request_t *r)
ngx_int_t webdav_lock_append_supported (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail)
ngx_int_t webdav_lock_append_discovery (ngx_http_request_t *r, const char *path, ngx_chain_t **head, ngx_chain_t **tail)
Macro Definition Documentation
NGX_HTTP_LOCKED
#define NGX_HTTP_LOCKED 423
Definition at line 35 of file lock_discovery.c.
Function Documentation
webdav_handle_unlock()
ngx_int_t webdav_handle_unlock (ngx_http_request_t * r)
Definition at line 110 of file lock_discovery.c.
References ngx_http_brix_webdav_loc_conf_t::common, webdav_lock_xattr_t::expires, ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), ngx_http_brix_shared_conf_t::root_canon, webdav_lock_xattr_t::token, webdav_lock_reap_null(), webdav_lock_xattr_delete(), webdav_lock_xattr_read(), WEBDAV_MAX_PATH, webdav_send_no_body(), and webdav_tpc_find_header.
Referenced by webdav_dispatch_lock_patch_search().
webdav_lock_append_discovery()
ngx_int_t webdav_lock_append_discovery (ngx_http_request_t * r, const char * path, ngx_chain_t ** head, ngx_chain_t ** tail)
Definition at line 215 of file lock_discovery.c.
References brix_http_chain_appendf(), webdav_lock_xattr_t::depth_infinity, webdav_lock_xattr_t::exclusive, webdav_lock_xattr_t::expires, webdav_lock_xattr_t::owner, webdav_lock_xattr_t::token, webdav_escape_xml_text(), webdav_lock_reap_null(), webdav_lock_xattr_delete(), and webdav_lock_xattr_read().
Referenced by propfind_emit_standard_props().
webdav_lock_append_supported()
ngx_int_t webdav_lock_append_supported (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail)
Definition at line 189 of file lock_discovery.c.
References brix_http_chain_appendf().
Referenced by propfind_emit_standard_props().
webdav_lock_startup_sweep()
ngx_uint_t webdav_lock_startup_sweep (ngx_pool_t * pool, ngx_log_t * log, const char * root_canon)
Definition at line 83 of file lock_discovery.c.
References brix_fs_walk(), brix_fs_walk_options_t::include_dirs, brix_fs_walk_options_t::include_files, log, webdav_lock_sweep_ctx_t::log, webdav_lock_sweep_ctx_t::pool, webdav_lock_sweep_ctx_t::removed, webdav_lock_sweep_ctx_t::root_canon, webdav_lock_sweep_cb(), and webdav_lock_sweep_remove().
Referenced by webdav_run_lock_startup_sweep().
webdav_lock_sweep_cb()
static ngx_int_t webdav_lock_sweep_cb (const brix_fs_walk_entry_t * entry, void * data) static
Definition at line 76 of file lock_discovery.c.
References brix_fs_walk_entry_t::path, and webdav_lock_sweep_remove().
Referenced by webdav_lock_startup_sweep().
webdav_lock_sweep_remove()
static void webdav_lock_sweep_remove (webdav_lock_sweep_ctx_t * sw, const char * path) static
Definition at line 63 of file lock_discovery.c.
References BRIX_PROTO_WEBDAV, brix_vfs_ctx_init(), brix_vfs_removexattr(), webdav_lock_sweep_ctx_t::log, webdav_lock_sweep_ctx_t::pool, webdav_lock_sweep_ctx_t::removed, webdav_lock_sweep_ctx_t::root_canon, and WEBDAV_LOCK_XATTR_KEY.
Referenced by webdav_lock_startup_sweep(), and webdav_lock_sweep_cb().