nginx-xrootd: src/protocols/webdav/lock_check.c File Reference
lock_check.c File Reference
#include "webdav.h"
#include "fs/path/path.h"
#include "fs/vfs/vfs.h"
#include "auth/impersonate/lifecycle.h"
#include "protocols/webdav/locks/request.h"
#include "core/http/http_xml.h"
#include "core/compat/fs_walk.h"
#include <openssl/crypto.h>
#include <openssl/rand.h>
#include <dirent.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/xattr.h>
#include <time.h>
#include "lock_internal.h"
Data Structures
struct webdav_lock_walk_t
Macros
#define NGX_HTTP_LOCKED 423
Functions
static ngx_int_t webdav_check_lock_at (ngx_http_request_t *r, const webdav_lock_walk_t *w)
static int webdav_lock_path_ascend (char *check, size_t check_len)
ngx_int_t webdav_check_locks (ngx_http_request_t *r, const char *path, int need_write)
static ngx_int_t check_locks_descendants (ngx_http_request_t *r, const char *dir)
ngx_int_t webdav_check_locks_tree (ngx_http_request_t *r, const char *path)
Macro Definition Documentation
NGX_HTTP_LOCKED
#define NGX_HTTP_LOCKED 423
Definition at line 34 of file lock_check.c.
Function Documentation
check_locks_descendants()
static ngx_int_t check_locks_descendants (ngx_http_request_t * r, const char * dir) static
Definition at line 179 of file lock_check.c.
References brix_vfs_closedir(), BRIX_VFS_DT_DIR, BRIX_VFS_DT_UNKNOWN, brix_vfs_opendir_quiet(), brix_vfs_probe(), brix_vfs_readdir_kind(), check_locks_descendants(), webdav_lock_xattr_t::expires, brix_vfs_stat_t::is_directory, name, NGX_HTTP_LOCKED, PATH_MAX, webdav_lock_xattr_t::token, webdav_lock_if_header_matches(), webdav_lock_reap_null(), webdav_lock_vfs_ctx(), webdav_lock_xattr_delete(), and webdav_lock_xattr_read().
Referenced by check_locks_descendants(), and webdav_check_locks_tree().
webdav_check_lock_at()
static ngx_int_t webdav_check_lock_at (ngx_http_request_t * r, const webdav_lock_walk_t * w) static
Definition at line 63 of file lock_check.c.
References webdav_lock_walk_t::check, webdav_lock_walk_t::check_len, webdav_lock_xattr_t::depth_infinity, webdav_lock_xattr_t::expires, NGX_HTTP_LOCKED, webdav_lock_walk_t::path, webdav_lock_walk_t::path_len, webdav_lock_xattr_t::token, webdav_lock_if_header_matches(), webdav_lock_reap_null(), webdav_lock_xattr_delete(), and webdav_lock_xattr_read().
Referenced by webdav_check_locks().
webdav_check_locks()
ngx_int_t webdav_check_locks (ngx_http_request_t * r, const char * path, int need_write)
Definition at line 129 of file lock_check.c.
References check(), webdav_lock_walk_t::check, webdav_lock_walk_t::check_len, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_module, webdav_lock_walk_t::path, webdav_lock_walk_t::path_len, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, webdav_check_lock_at(), and webdav_lock_path_ascend().
Referenced by webdav_check_locks_tree(), webdav_handle_mkcol(), webdav_lock_check_request_path(), and webdav_proppatch_do().
webdav_check_locks_tree()
ngx_int_t webdav_check_locks_tree (ngx_http_request_t * r, const char * path)
Definition at line 267 of file lock_check.c.
References brix_vfs_probe(), check_locks_descendants(), brix_vfs_stat_t::is_directory, webdav_check_locks(), and webdav_lock_vfs_ctx().
Referenced by webdav_copy_resolve_pair(), webdav_handle_delete(), and webdav_handle_move().
webdav_lock_path_ascend()
static int webdav_lock_path_ascend (char * check, size_t check_len) static
Definition at line 104 of file lock_check.c.
References check().
Referenced by webdav_check_locks().