nginx-xrootd: src/protocols/webdav/lock_internal.h File Reference
lock_internal.h File Reference
#include "webdav.h"
#include "fs/vfs/vfs.h"
Functions
void webdav_lock_vfs_ctx (ngx_http_request_t *r, const char *path, brix_vfs_ctx_t *vctx)
void webdav_lock_reap_null (ngx_http_request_t *r, const char *path, const webdav_lock_xattr_t *e)
Function Documentation
webdav_lock_reap_null()
void webdav_lock_reap_null (ngx_http_request_t * r, const char * path, const webdav_lock_xattr_t * e)
Definition at line 175 of file lock.c.
References brix_vfs_probe(), brix_vfs_unlink(), webdav_lock_xattr_t::is_null, brix_vfs_stat_t::is_regular, brix_vfs_stat_t::size, and webdav_lock_vfs_ctx().
Referenced by check_locks_descendants(), webdav_check_lock_at(), webdav_handle_unlock(), and webdav_lock_append_discovery().
webdav_lock_vfs_ctx()
void webdav_lock_vfs_ctx (ngx_http_request_t * r, const char * path, brix_vfs_ctx_t * vctx)
Definition at line 156 of file lock.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_WEBDAV, brix_vfs_ctx_init(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, brix_vfs_ctx_t::pool, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by check_locks_descendants(), webdav_check_locks_tree(), webdav_lock_create_null(), and webdav_lock_reap_null().