nginx-xrootd: src/core/compat/log.h File Reference
log.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
Functions
void brix_log_safe_path (ngx_log_t *log, ngx_uint_t level, ngx_err_t err, const char *fmt, const char *path)
Function Documentation
brix_log_safe_path()
void brix_log_safe_path (ngx_log_t * log, ngx_uint_t level, ngx_err_t err, const char * fmt, const char * path)
Definition at line 11 of file log.c.
References brix_sanitize_log_string(), and log.
Referenced by brix_chkpoint_recover_root(), ckp_recover_one(), ckp_recover_open_dir(), ckp_recover_scan(), s3_chunk_finalize(), s3_handle_multipart_initiate(), s3_mpu_assemble(), s3_put_aio_done(), s3_put_try_sentinel(), s3put_commit_and_headers(), s3put_ensure_parent_dirs(), s3put_open_target(), tpc_thread_pull_commit(), webdav_copy_collection_commit(), webdav_move_collection_done(), webdav_move_run_sync(), webdav_put_aio_done(), webdav_put_commit(), webdav_put_open_target(), webdav_put_verify_ingest_digest(), and webdav_tpc_commit_pulled_file().