nginx-xrootd: src/protocols/root/session/login.c File Reference
login.c File Reference
#include "core/ngx_brix_module.h"
#include "registry.h"
#include "core/compat/alloc_guard.h"
#include "observability/sesslog/sesslog_ngx.h"
Functions
static void brix_count_login_ok (brix_ctx_t *ctx)
static ngx_int_t brix_login_check_username (brix_ctx_t *ctx, ngx_connection_t *c, const char user[9])
static ngx_int_t brix_login_precheck_and_parse (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, char user[9], char user_log[64])
static ngx_int_t brix_login_respond_anon (brix_ctx_t *ctx, ngx_connection_t *c, const char *user)
static size_t brix_login_build_parms (ngx_stream_brix_srv_conf_t *conf, char *parms, size_t cap)
static ngx_int_t brix_login_respond_authenticated (brix_ctx_t *ctx, ngx_connection_t *c, const char *user)
ngx_int_t brix_handle_login (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_count_login_ok()
static void brix_count_login_ok (brix_ctx_t * ctx) static
Definition at line 12 of file login.c.
References BRIX_OP_LOGIN, brix_ctx_t::metrics, and ngx_brix_srv_metrics_t::op_ok.
Referenced by brix_login_respond_anon(), and brix_login_respond_authenticated().
brix_handle_login()
ngx_int_t brix_handle_login (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 271 of file login.c.
References BRIX_AUTH_NONE, brix_login_precheck_and_parse(), brix_login_respond_anon(), brix_login_respond_authenticated(), and c.
Referenced by brix_dispatch_session_opcode().
brix_login_build_parms()
static size_t brix_login_build_parms (ngx_stream_brix_srv_conf_t * conf, char * parms, size_t cap) static
Definition at line 164 of file login.c.
References BRIX_AUTH_BOTH, BRIX_AUTH_HOST, BRIX_AUTH_KRB5, BRIX_AUTH_PWD, BRIX_AUTH_SSS, BRIX_AUTH_TOKEN, BRIX_AUTH_UNIX, and BRIX_GSI_SDH_OFF.
Referenced by brix_login_respond_authenticated().
brix_login_check_username()
static ngx_int_t brix_login_check_username (brix_ctx_t * ctx, ngx_connection_t * c, const char user[9]) static
Definition at line 31 of file login.c.
References brix_send_error(), c, and kXR_ArgInvalid.
Referenced by brix_login_precheck_and_parse().
brix_login_precheck_and_parse()
static ngx_int_t brix_login_precheck_and_parse (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, char user[9], char user_log[64]) static
Definition at line 59 of file login.c.
References BRIX_AUTH_BOTH, BRIX_AUTH_GSI, BRIX_AUTH_KRB5, BRIX_AUTH_SSS, BRIX_AUTH_TOKEN, BRIX_AUTH_UNIX, brix_login_check_username(), brix_sanitize_log_string(), brix_send_error(), c, brix_ctx_recv_t::hdr_buf, kXR_InvalidRequest, kXR_Overloaded, brix_ctx_login_t::logged_in, brix_ctx_t::login, ngx_memcpy, brix_ctx_login_t::pid, xrdw_login_req_t::pid, brix_ctx_t::recv, brix_ctx_login_t::user, xrdw_login_req_t::username, and xrdw_login_req_unpack().
Referenced by brix_handle_login().
brix_login_respond_anon()
static ngx_int_t brix_login_respond_anon (brix_ctx_t * ctx, ngx_connection_t * c, const char * user) static
Definition at line 124 of file login.c.
References brix_ctx_login_t::auth_done, brix_identity_t::auth_method, BRIX_AUTHN_NONE, brix_build_resp_hdr(), brix_count_login_ok(), brix_log_access(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), BRIX_SESS_AM_ANON, brix_sess_auth_once(), BRIX_SESSION_ID_LEN, brix_session_register(), c, brix_ctx_recv_t::cur_streamid, brix_ctx_login_t::dn, brix_ctx_t::identity, kXR_ok, brix_ctx_t::login, ngx_memcpy, brix_ctx_t::recv, brix_ctx_t::sess, brix_ctx_login_t::sessid, brix_ctx_totals_t::start, brix_ctx_t::totals, brix_ctx_login_t::vo_list, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_handle_login().
brix_login_respond_authenticated()
static ngx_int_t brix_login_respond_authenticated (brix_ctx_t * ctx, ngx_connection_t * c, const char * user) static
Definition at line 223 of file login.c.
References brix_build_resp_hdr(), brix_count_login_ok(), brix_log_access(), brix_login_build_parms(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), brix_send_error(), BRIX_SESSION_ID_LEN, c, brix_ctx_recv_t::cur_streamid, kXR_ok, kXR_ServerError, brix_ctx_t::login, ngx_memcpy, ngx_stream_brix_module, brix_ctx_t::recv, brix_ctx_login_t::sessid, brix_ctx_t::session, brix_ctx_totals_t::start, brix_ctx_t::totals, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_handle_login().