nginx-xrootd: src/auth/token/macaroon.c File Reference
macaroon.c File Reference
#include "token_internal.h"
#include "macaroon.h"
#include "b64url.h"
#include "scopes.h"
#include "core/compat/hex.h"
#include <openssl/evp.h>
#include <openssl/hmac.h>
#include <openssl/crypto.h>
#include <string.h>
#include <time.h>
Data Structures
struct brix_macaroon_tp_t
Macros
#define MACAROON_MAX_BIN 8192
#define BRIX_MACAROON_MAX_DISCHARGES 8
#define BRIX_MACAROON_MAX_TP_CAVEATS 8
#define BRIX_MACAROON_MAX_CID_LEN 512
#define BRIX_MACAROON_MAX_VID_LEN 256
Functions
static int parse_packet_len (const u_char *p)
static time_t parse_iso8601 (const char *s, size_t len)
int brix_token_is_macaroon (const char *token, size_t token_len)
ssize_t brix_macaroon_secret_parse (const char *hex, size_t hex_len, u_char *bin, size_t bin_max)
static int macaroon_decrypt_vid_inner (EVP_CIPHER_CTX *ctx, u_char *plain, const u_char *vid, size_t vid_len, const u_char *aes_key, u_char *discharge_key)
static int macaroon_decrypt_vid (const u_char *vid, size_t vid_len, const u_char *aes_key, u_char *discharge_key)
static void macaroon_rebuild_scope_raw (brix_token_claims_t *claims)
static void macaroon_apply_path_caveats (ngx_log_t *log, brix_token_claims_t *claims, char path_caveats[][256], int n_path_caveats)
static int macaroon_parse_core (ngx_log_t *log, const u_char *bin, size_t bin_len, const u_char *key, size_t key_len, brix_token_claims_t *claims, brix_macaroon_tp_t *tp_arr, int *n_tp, int max_tp)
int brix_macaroon_validate_bundle (ngx_log_t *log, const char *token, size_t token_len, const u_char *root_key, size_t root_key_len, brix_token_claims_t *claims)
int brix_macaroon_validate (ngx_log_t *log, const char *token, size_t token_len, const u_char *root_key, size_t root_key_len, brix_token_claims_t *claims)
Macro Definition Documentation
BRIX_MACAROON_MAX_CID_LEN
#define BRIX_MACAROON_MAX_CID_LEN 512
Definition at line 120 of file macaroon.c.
BRIX_MACAROON_MAX_DISCHARGES
#define BRIX_MACAROON_MAX_DISCHARGES 8
Definition at line 117 of file macaroon.c.
BRIX_MACAROON_MAX_TP_CAVEATS
#define BRIX_MACAROON_MAX_TP_CAVEATS 8
Definition at line 119 of file macaroon.c.
BRIX_MACAROON_MAX_VID_LEN
#define BRIX_MACAROON_MAX_VID_LEN 256
Definition at line 121 of file macaroon.c.
MACAROON_MAX_BIN
#define MACAROON_MAX_BIN 8192
Definition at line 31 of file macaroon.c.
Function Documentation
brix_macaroon_secret_parse()
ssize_t brix_macaroon_secret_parse (const char * hex, size_t hex_len, u_char * bin, size_t bin_max)
Definition at line 92 of file macaroon.c.
References brix_hex_from_char(), and hex().
Referenced by brix_handle_token_auth(), webdav_handle_macaroon_request(), webdav_handle_macaroon_token(), and webdav_verify_bearer_token().
brix_macaroon_validate()
int brix_macaroon_validate (ngx_log_t * log, const char * token, size_t token_len, const u_char * root_key, size_t root_key_len, brix_token_claims_t * claims)
Definition at line 795 of file macaroon.c.
References brix_macaroon_validate_bundle(), and log.
Referenced by brix_token_validate().
brix_macaroon_validate_bundle()
int brix_macaroon_validate_bundle (ngx_log_t * log, const char * token, size_t token_len, const u_char * root_key, size_t root_key_len, brix_token_claims_t * claims)
Definition at line 576 of file macaroon.c.
References b64url_decode(), BRIX_MACAROON_MAX_DISCHARGES, BRIX_MACAROON_MAX_TP_CAVEATS, BRIX_MAX_TOKEN_SCOPES, BRIX_SCOPE_PATH_MAX, brix_macaroon_tp_t::cid, brix_macaroon_tp_t::cid_len, brix_token_claims_t::exp, brix_token_claims_t::iss, log, macaroon_apply_path_caveats(), macaroon_decrypt_vid(), MACAROON_MAX_BIN, macaroon_parse_core(), parse_packet_len(), brix_token_scope_t::path, brix_token_claims_t::scope_count, brix_token_claims_t::scope_raw, brix_token_claims_t::scopes, brix_macaroon_tp_t::sig_before, brix_token_claims_t::sub, brix_macaroon_tp_t::vid, and brix_macaroon_tp_t::vid_len.
Referenced by brix_macaroon_validate().
brix_token_is_macaroon()
int brix_token_is_macaroon (const char * token, size_t token_len)
Definition at line 78 of file macaroon.c.
Referenced by brix_token_validate().
macaroon_apply_path_caveats()
static void macaroon_apply_path_caveats (ngx_log_t * log, brix_token_claims_t * claims, char path_caveats[][256], int n_path_caveats) static
Definition at line 272 of file macaroon.c.
References brix_token_scope_t::create, log, macaroon_rebuild_scope_raw(), brix_token_scope_t::modify, brix_token_scope_t::path, brix_token_scope_t::read, brix_token_claims_t::scope_count, brix_token_claims_t::scopes, and brix_token_scope_t::write.
Referenced by brix_macaroon_validate_bundle(), and macaroon_parse_core().
macaroon_decrypt_vid()
static int macaroon_decrypt_vid (const u_char * vid, size_t vid_len, const u_char * aes_key, u_char * discharge_key) static
Definition at line 187 of file macaroon.c.
References macaroon_decrypt_vid_inner().
Referenced by brix_macaroon_validate_bundle().
macaroon_decrypt_vid_inner()
static int macaroon_decrypt_vid_inner (EVP_CIPHER_CTX * ctx, u_char * plain, const u_char * vid, size_t vid_len, const u_char * aes_key, u_char * discharge_key) static
Definition at line 151 of file macaroon.c.
Referenced by macaroon_decrypt_vid().
macaroon_parse_core()
static int macaroon_parse_core (ngx_log_t * log, const u_char * bin, size_t bin_len, const u_char * key, size_t key_len, brix_token_claims_t * claims, brix_macaroon_tp_t * tp_arr, int * n_tp, int max_tp) static
Definition at line 333 of file macaroon.c.
References BRIX_MACAROON_MAX_CID_LEN, BRIX_MAX_TOKEN_SCOPES, BRIX_SCOPE_PATH_MAX, brix_token_parse_scopes(), brix_macaroon_tp_t::cid, brix_macaroon_tp_t::cid_len, brix_token_claims_t::exp, brix_token_claims_t::iss, key, log, macaroon_apply_path_caveats(), parse_iso8601(), parse_packet_len(), brix_token_claims_t::scope_count, brix_token_claims_t::scope_raw, brix_token_claims_t::scopes, brix_macaroon_tp_t::sig_before, brix_token_claims_t::sub, brix_macaroon_tp_t::vid, and brix_macaroon_tp_t::vid_len.
Referenced by brix_macaroon_validate_bundle().
macaroon_rebuild_scope_raw()
static void macaroon_rebuild_scope_raw (brix_token_claims_t * claims) static
Definition at line 220 of file macaroon.c.
References BRIX_MAX_TOKEN_SCOPES, brix_token_parse_scopes(), brix_token_scope_t::create, brix_token_scope_t::modify, brix_token_scope_t::path, brix_token_scope_t::read, brix_token_claims_t::scope_count, brix_token_claims_t::scope_raw, brix_token_claims_t::scopes, and brix_token_scope_t::write.
Referenced by macaroon_apply_path_caveats().
parse_iso8601()
static time_t parse_iso8601 (const char * s, size_t len) static
Definition at line 52 of file macaroon.c.
References s.
Referenced by macaroon_parse_core().
parse_packet_len()
static int parse_packet_len (const u_char * p) static
Definition at line 34 of file macaroon.c.
References brix_hex_from_char().
Referenced by brix_macaroon_validate_bundle(), and macaroon_parse_core().