nginx-xrootd: src/auth/token/macaroon_issue.c File Reference
macaroon_issue.c File Reference
#include "macaroon_issue.h"
#include "b64url.h"
#include <openssl/hmac.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
Data Structures
struct issue_buf_t
Macros
#define ISSUE_BIN_MAX 4096
Functions
static int write_packet (issue_buf_t *buf, const char *label, size_t label_len, const u_char *value, size_t val_len)
static void chain_hmac (u_char sig[32], const u_char *msg, size_t msg_len)
static ngx_int_t emit_cid_caveat (issue_buf_t *buf, u_char sig[32], const char *cav, size_t cav_len, ngx_log_t *log)
static ngx_int_t emit_location (issue_buf_t *buf, const char *location, ngx_log_t *log)
static ngx_int_t emit_identifier (issue_buf_t *buf, u_char sig[32], const u_char *root_key, size_t root_key_len, const char *identifier, ngx_log_t *log)
static ngx_int_t emit_activity_caveat (issue_buf_t *buf, u_char sig[32], const char *activities, ngx_log_t *log)
static ngx_int_t emit_path_caveat (issue_buf_t *buf, u_char sig[32], const char *path, ngx_log_t *log)
static ngx_int_t emit_expiry_caveat (issue_buf_t *buf, u_char sig[32], time_t expiry, ngx_log_t *log)
static ngx_int_t emit_signature (issue_buf_t *buf, const u_char sig[32], ngx_log_t *log)
ngx_int_t brix_macaroon_issue (ngx_log_t *log, const u_char *root_key, size_t root_key_len, const char *location, const char *identifier, const char *activities, const char *path, time_t expiry, char *out_b64, size_t out_b64sz)
Macro Definition Documentation
ISSUE_BIN_MAX
#define ISSUE_BIN_MAX 4096
Definition at line 29 of file macaroon_issue.c.
Function Documentation
brix_macaroon_issue()
ngx_int_t brix_macaroon_issue (ngx_log_t * log, const u_char * root_key, size_t root_key_len, const char * location, const char * identifier, const char * activities, const char * path, time_t expiry, char * out_b64, size_t out_b64sz)
Definition at line 299 of file macaroon_issue.c.
References b64url_encode(), BRIX_MACAROON_ISSUE_OUT_MAX, emit_activity_caveat(), emit_expiry_caveat(), emit_identifier(), emit_location(), emit_path_caveat(), emit_signature(), ISSUE_BIN_MAX, log, issue_buf_t::p, issue_buf_t::rem, and issue_buf_t::start.
Referenced by webdav_handle_macaroon_request(), and webdav_handle_macaroon_token().
chain_hmac()
static void chain_hmac (u_char sig[32], const u_char * msg, size_t msg_len) static
Definition at line 97 of file macaroon_issue.c.
References ngx_memcpy.
Referenced by emit_cid_caveat().
emit_activity_caveat()
static ngx_int_t emit_activity_caveat (issue_buf_t * buf, u_char sig[32], const char * activities, ngx_log_t * log) static
Definition at line 189 of file macaroon_issue.c.
References emit_cid_caveat(), and log.
Referenced by brix_macaroon_issue().
emit_cid_caveat()
static ngx_int_t emit_cid_caveat (issue_buf_t * buf, u_char sig[32], const char * cav, size_t cav_len, ngx_log_t * log) static
Definition at line 116 of file macaroon_issue.c.
References chain_hmac(), log, and write_packet().
Referenced by emit_activity_caveat(), emit_expiry_caveat(), and emit_path_caveat().
emit_expiry_caveat()
static ngx_int_t emit_expiry_caveat (issue_buf_t * buf, u_char sig[32], time_t expiry, ngx_log_t * log) static
Definition at line 244 of file macaroon_issue.c.
References emit_cid_caveat(), and log.
Referenced by brix_macaroon_issue().
emit_identifier()
static ngx_int_t emit_identifier (issue_buf_t * buf, u_char sig[32], const u_char * root_key, size_t root_key_len, const char * identifier, ngx_log_t * log) static
Definition at line 161 of file macaroon_issue.c.
References log, and write_packet().
Referenced by brix_macaroon_issue().
emit_location()
static ngx_int_t emit_location (issue_buf_t * buf, const char * location, ngx_log_t * log) static
Definition at line 137 of file macaroon_issue.c.
References log, and write_packet().
Referenced by brix_macaroon_issue().
emit_path_caveat()
static ngx_int_t emit_path_caveat (issue_buf_t * buf, u_char sig[32], const char * path, ngx_log_t * log) static
Definition at line 217 of file macaroon_issue.c.
References emit_cid_caveat(), and log.
Referenced by brix_macaroon_issue().
emit_signature()
static ngx_int_t emit_signature (issue_buf_t * buf, const u_char sig[32], ngx_log_t * log) static
Definition at line 278 of file macaroon_issue.c.
References log, ngx_memcpy, issue_buf_t::p, and issue_buf_t::rem.
Referenced by brix_macaroon_issue().
write_packet()
static int write_packet (issue_buf_t * buf, const char * label, size_t label_len, const u_char * value, size_t val_len) static
Definition at line 60 of file macaroon_issue.c.
References ngx_memcpy, issue_buf_t::p, and issue_buf_t::rem.
Referenced by emit_cid_caveat(), emit_identifier(), and emit_location().