nginx-xrootd: src/auth/token/macaroon_internal.h File Reference
macaroon_internal.h File Reference
#include "token_internal.h"
#include "scopes.h"
Data Structures
struct brix_macaroon_tp_t
struct brix_macaroon_parse_state_t
struct macaroon_parse_input_t
Macros
#define BRIX_MACAROON_MAX_CID_LEN 512
#define BRIX_MACAROON_MAX_VID_LEN 256
Functions
int brix_macaroon_packet_len (const u_char *p)
int macaroon_parse_core (const macaroon_parse_input_t *in, const u_char *bin, size_t bin_len)
void macaroon_apply_path_caveats (ngx_log_t *log, brix_token_claims_t *claims, char path_caveats[][256], int n_path_caveats)
void macaroon_parse_first_party_caveat (brix_macaroon_parse_state_t *state, const u_char *caveat, size_t caveat_len)
int macaroon_decrypt_vid (const u_char *vid, size_t vid_len, const u_char *aes_key, u_char *discharge_key)
Macro Definition Documentation
BRIX_MACAROON_MAX_CID_LEN
#define BRIX_MACAROON_MAX_CID_LEN 512
Definition at line 35 of file macaroon_internal.h.
BRIX_MACAROON_MAX_VID_LEN
#define BRIX_MACAROON_MAX_VID_LEN 256
Definition at line 36 of file macaroon_internal.h.
Function Documentation
brix_macaroon_packet_len()
int brix_macaroon_packet_len (const u_char * p)
Definition at line 33 of file macaroon_parse.c.
References brix_hex_from_char().
Referenced by macaroon_candidate_matches_cid(), and macaroon_parse_core().
macaroon_apply_path_caveats()
void macaroon_apply_path_caveats (ngx_log_t * log, brix_token_claims_t * claims, char path_caveats[][256], int n_path_caveats)
Definition at line 161 of file macaroon_caveats.c.
References log, macaroon_apply_path_to_scope(), macaroon_rebuild_scope_raw(), brix_token_claims_t::scope_count, and brix_token_claims_t::scopes.
Referenced by macaroon_finalize_scopes(), and macaroon_intersect_discharge_claims().
macaroon_decrypt_vid()
int macaroon_decrypt_vid (const u_char * vid, size_t vid_len, const u_char * aes_key, u_char * discharge_key)
Definition at line 98 of file macaroon_crypto.c.
References macaroon_vid_t::aes_key, macaroon_vid_t::discharge_key, macaroon_decrypt_vid_inner(), macaroon_vid_t::vid, and macaroon_vid_t::vid_len.
Referenced by macaroon_validate_one_discharge().
macaroon_parse_core()
int macaroon_parse_core (const macaroon_parse_input_t * in, const u_char * bin, size_t bin_len)
Definition at line 231 of file macaroon_parse.c.
References brix_macaroon_packet_len(), brix_macaroon_parse_state_t::found_sig, log, macaroon_parse_input_t::log, macaroon_check_expiry(), macaroon_dispatch_packet(), macaroon_finalize_scopes(), and macaroon_parse_state_init().
Referenced by brix_macaroon_validate_bundle(), and macaroon_validate_one_discharge().
macaroon_parse_first_party_caveat()
void macaroon_parse_first_party_caveat (brix_macaroon_parse_state_t * state, const u_char * caveat, size_t caveat_len)
Definition at line 288 of file macaroon_caveats.c.
References macaroon_parse_activity_caveat(), macaroon_parse_before_caveat(), and macaroon_parse_path_caveat().
Referenced by macaroon_packet_cid().