nginx-xrootd: src/auth/token/macaroon_caveats.c File Reference
macaroon_caveats.c File Reference
#include "token_internal.h"
#include "macaroon.h"
#include "macaroon_internal.h"
#include "b64url.h"
#include "scopes.h"
#include "core/compat/hex.h"
#include <openssl/evp.h>
#include <openssl/hmac.h>
#include <openssl/crypto.h>
#include <string.h>
#include <time.h>
Functions
static time_t parse_iso8601 (const char *s, size_t len)
static void macaroon_rebuild_scope_raw (brix_token_claims_t *claims)
static int macaroon_apply_path_to_scope (ngx_log_t *log, brix_token_scope_t *scope, const char *caveat_path, size_t caveat_path_len)
void macaroon_apply_path_caveats (ngx_log_t *log, brix_token_claims_t *claims, char path_caveats[][256], int n_path_caveats)
static const char * macaroon_scope_for_activity (const char *activity, size_t activity_len)
static void macaroon_append_activity_scope (brix_macaroon_parse_state_t *state, const char *scope)
static void macaroon_parse_activity_caveat (brix_macaroon_parse_state_t *state, const u_char *caveat, size_t caveat_len)
static void macaroon_parse_before_caveat (brix_macaroon_parse_state_t *state, const u_char *caveat, size_t caveat_len)
static void macaroon_parse_path_caveat (brix_macaroon_parse_state_t *state, const u_char *caveat, size_t caveat_len)
void macaroon_parse_first_party_caveat (brix_macaroon_parse_state_t *state, const u_char *caveat, size_t caveat_len)
Function Documentation
macaroon_append_activity_scope()
static void macaroon_append_activity_scope (brix_macaroon_parse_state_t * state, const char * scope) static
Definition at line 208 of file macaroon_caveats.c.
References scope, brix_macaroon_parse_state_t::scope_buf, and brix_macaroon_parse_state_t::scope_off.
Referenced by macaroon_parse_activity_caveat().
macaroon_apply_path_caveats()
void macaroon_apply_path_caveats (ngx_log_t * log, brix_token_claims_t * claims, char path_caveats[][256], int n_path_caveats)
Definition at line 161 of file macaroon_caveats.c.
References log, macaroon_apply_path_to_scope(), macaroon_rebuild_scope_raw(), brix_token_claims_t::scope_count, and brix_token_claims_t::scopes.
Referenced by macaroon_finalize_scopes(), and macaroon_intersect_discharge_claims().
macaroon_apply_path_to_scope()
static int macaroon_apply_path_to_scope (ngx_log_t * log, brix_token_scope_t * scope, const char * caveat_path, size_t caveat_path_len) static
Definition at line 121 of file macaroon_caveats.c.
References log, and scope.
Referenced by macaroon_apply_path_caveats().
macaroon_parse_activity_caveat()
static void macaroon_parse_activity_caveat (brix_macaroon_parse_state_t * state, const u_char * caveat, size_t caveat_len) static
Definition at line 236 of file macaroon_caveats.c.
References activity, macaroon_append_activity_scope(), macaroon_scope_for_activity(), and scope.
Referenced by macaroon_parse_first_party_caveat().
macaroon_parse_before_caveat()
static void macaroon_parse_before_caveat (brix_macaroon_parse_state_t * state, const u_char * caveat, size_t caveat_len) static
Definition at line 259 of file macaroon_caveats.c.
References brix_macaroon_parse_state_t::claims, brix_token_claims_t::exp, and parse_iso8601().
Referenced by macaroon_parse_first_party_caveat().
macaroon_parse_first_party_caveat()
void macaroon_parse_first_party_caveat (brix_macaroon_parse_state_t * state, const u_char * caveat, size_t caveat_len)
Definition at line 288 of file macaroon_caveats.c.
References macaroon_parse_activity_caveat(), macaroon_parse_before_caveat(), and macaroon_parse_path_caveat().
Referenced by macaroon_packet_cid().
macaroon_parse_path_caveat()
static void macaroon_parse_path_caveat (brix_macaroon_parse_state_t * state, const u_char * caveat, size_t caveat_len) static
Definition at line 271 of file macaroon_caveats.c.
References BRIX_SCOPE_PATH_MAX, brix_macaroon_parse_state_t::n_path_caveats, and brix_macaroon_parse_state_t::path_caveats.
Referenced by macaroon_parse_first_party_caveat().
macaroon_rebuild_scope_raw()
static void macaroon_rebuild_scope_raw (brix_token_claims_t * claims) static
Definition at line 69 of file macaroon_caveats.c.
References BRIX_MAX_TOKEN_SCOPES, brix_token_parse_scopes(), brix_token_scope_t::create, brix_token_scope_t::modify, brix_token_scope_t::path, brix_token_scope_t::read, brix_token_claims_t::scope_count, brix_token_claims_t::scope_raw, brix_token_claims_t::scopes, and brix_token_scope_t::write.
Referenced by macaroon_apply_path_caveats().
macaroon_scope_for_activity()
static const char * macaroon_scope_for_activity (const char * activity, size_t activity_len) static
Definition at line 184 of file macaroon_caveats.c.
References activity.
Referenced by macaroon_parse_activity_caveat().
parse_iso8601()
static time_t parse_iso8601 (const char * s, size_t len) static
Definition at line 36 of file macaroon_caveats.c.
References s.
Referenced by macaroon_parse_before_caveat().