nginx-xrootd: src/protocols/webdav/macaroon_endpoint_request.c File Reference
macaroon_endpoint_request.c File Reference
#include "webdav.h"
#include "auth/token/macaroon.h"
#include "auth/token/macaroon_issue.h"
#include "core/compat/log_diag.h"
#include "core/http/http_body.h"
#include "core/compat/json_min.h"
#include <openssl/rand.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "macaroon_endpoint_internal.h"
Data Structures
struct mac_caveats_t
Functions
static ngx_int_t mac_iso_component (const char *s, size_t len, size_t *ip, uint64_t *total)
static ngx_int_t mac_iso8601_secs (const char *s, size_t len, time_t max, time_t *out)
static void mac_caveat_apply (const u_char *p, size_t elen, mac_caveats_t *out)
static void mac_caveats_scan (const char *body, size_t len, mac_caveats_t *out)
static void mac_request_respond (ngx_http_request_t *r, const char *token_out)
void webdav_handle_macaroon_request (ngx_http_request_t *r)
Function Documentation
mac_caveat_apply()
static void mac_caveat_apply (const u_char * p, size_t elen, mac_caveats_t * out) static
Definition at line 107 of file macaroon_endpoint_request.c.
References mac_caveats_t::act, mac_caveats_t::actsz, ngx_memcpy, mac_caveats_t::path, and mac_caveats_t::pathsz.
Referenced by mac_caveats_scan().
mac_caveats_scan()
static void mac_caveats_scan (const char * body, size_t len, mac_caveats_t * out) static
Definition at line 139 of file macaroon_endpoint_request.c.
References mac_caveats_t::act, mac_caveat_apply(), and mac_caveats_t::path.
Referenced by webdav_handle_macaroon_request().
mac_iso8601_secs()
static ngx_int_t mac_iso8601_secs (const char * s, size_t len, time_t max, time_t * out) static
Definition at line 64 of file macaroon_endpoint_request.c.
References mac_iso_component(), and s.
Referenced by webdav_handle_macaroon_request().
mac_iso_component()
static ngx_int_t mac_iso_component (const char * s, size_t len, size_t * ip, uint64_t * total) static
Definition at line 34 of file macaroon_endpoint_request.c.
References s.
Referenced by mac_iso8601_secs().
mac_request_respond()
static void mac_request_respond (ngx_http_request_t * r, const char * token_out) static
Definition at line 174 of file macaroon_endpoint_request.c.
References BRIX_MACAROON_ISSUE_OUT_MAX, mac_respond(), and scheme.
Referenced by webdav_handle_macaroon_request().
webdav_handle_macaroon_request()
void webdav_handle_macaroon_request (ngx_http_request_t * r)
Definition at line 203 of file macaroon_endpoint_request.c.
References mac_caveats_t::act, mac_caveats_t::actsz, brix_json_get_str(), brix_macaroon_issue(), BRIX_MACAROON_ISSUE_OUT_MAX, brix_macaroon_secret_parse(), J_SERVER_ERROR, mac_authorize(), mac_build_location(), mac_caveats_scan(), mac_gate_and_read_body(), mac_iso8601_secs(), mac_make_identifier(), mac_request_respond(), mac_respond(), ngx_http_brix_webdav_loc_conf_t::macaroon_max_validity, ngx_http_brix_webdav_module, ngx_memcpy, mac_caveats_t::path, mac_caveats_t::pathsz, and ngx_http_brix_webdav_loc_conf_t::token_macaroon_secret.
Referenced by webdav_dispatch_macaroon().