nginx-xrootd: src/protocols/webdav/macaroon_endpoint_oauth2.c File Reference
macaroon_endpoint_oauth2.c File Reference
#include "webdav.h"
#include "auth/token/macaroon.h"
#include "auth/token/macaroon_issue.h"
#include "core/compat/log_diag.h"
#include "core/http/http_body.h"
#include "core/compat/json_min.h"
#include <openssl/rand.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "macaroon_endpoint_internal.h"
Functions
static int hex_nibble (char c)
static size_t urlencode_decode_inplace (char *str)
static ngx_int_t form_find (const char *form, const char *key, char *dst, size_t dstsz)
static const char * mac_scope_activity (const char *scope_item)
static ngx_int_t mac_act_append (char *act_buf, size_t act_sz, size_t *act_len, const char *activity)
static void mac_path_capture (char *path_buf, size_t path_sz, const char *path)
static ngx_int_t scope_to_activities (const char *scope, char *act_buf, size_t act_sz, char *path_buf, size_t path_sz)
static ngx_int_t mac_token_parse_form (ngx_http_request_t *r, const char *body, char *scope_str, size_t scope_sz, long *expire_in)
void webdav_handle_macaroon_token (ngx_http_request_t *r)
Variables
struct {
const char * scope
const char * activity
} mac_scope_activity_map []
Function Documentation
form_find()
static ngx_int_t form_find (const char * form, const char * key, char * dst, size_t dstsz) static
Definition at line 68 of file macaroon_endpoint_oauth2.c.
References key, ngx_memcpy, and urlencode_decode_inplace().
Referenced by mac_token_parse_form().
hex_nibble()
static int hex_nibble (char c) static
Definition at line 28 of file macaroon_endpoint_oauth2.c.
References c.
Referenced by urlencode_decode_inplace().
mac_act_append()
static ngx_int_t mac_act_append (char * act_buf, size_t act_sz, size_t * act_len, const char * activity) static
Definition at line 144 of file macaroon_endpoint_oauth2.c.
References activity, and ngx_memcpy.
Referenced by scope_to_activities().
mac_path_capture()
static void mac_path_capture (char * path_buf, size_t path_sz, const char * path) static
Definition at line 168 of file macaroon_endpoint_oauth2.c.
References ngx_memcpy.
Referenced by scope_to_activities().
mac_scope_activity()
static const char * mac_scope_activity (const char * scope_item) static
Definition at line 125 of file macaroon_endpoint_oauth2.c.
References mac_scope_activity_map, and scope.
Referenced by scope_to_activities().
mac_token_parse_form()
static ngx_int_t mac_token_parse_form (ngx_http_request_t * r, const char * body, char * scope_str, size_t scope_sz, long * expire_in) static
Definition at line 241 of file macaroon_endpoint_oauth2.c.
References form_find(), J_INVALID_SCOPE, J_UNSUPPORTED_GT, and mac_respond().
Referenced by webdav_handle_macaroon_token().
scope_to_activities()
static ngx_int_t scope_to_activities (const char * scope, char * act_buf, size_t act_sz, char * path_buf, size_t path_sz) static
Definition at line 189 of file macaroon_endpoint_oauth2.c.
References activity, mac_act_append(), mac_path_capture(), mac_scope_activity(), and scope.
Referenced by webdav_handle_macaroon_token().
urlencode_decode_inplace()
static size_t urlencode_decode_inplace (char * str) static
Definition at line 38 of file macaroon_endpoint_oauth2.c.
References hex_nibble().
Referenced by form_find().
webdav_handle_macaroon_token()
void webdav_handle_macaroon_token (ngx_http_request_t * r)
Definition at line 278 of file macaroon_endpoint_oauth2.c.
References BRIX_DIAG_ERR, brix_macaroon_issue(), BRIX_MACAROON_ISSUE_OUT_MAX, brix_macaroon_secret_parse(), J_INVALID_SCOPE, J_SERVER_ERROR, mac_authorize(), mac_build_location(), mac_gate_and_read_body(), mac_make_identifier(), mac_respond(), mac_token_parse_form(), ngx_http_brix_webdav_module, scope_to_activities(), and ngx_http_brix_webdav_loc_conf_t::token_macaroon_secret.
Referenced by webdav_dispatch_macaroon().
Variable Documentation
activity
const char* activity
Definition at line 109 of file macaroon_endpoint_oauth2.c.
Referenced by brix_pmark_flowlabel_encode(), mac_act_append(), macaroon_parse_activity_caveat(), macaroon_scope_for_activity(), and scope_to_activities().
[struct]
const struct { ... } mac_scope_activity_map[]
Initial value:
= {
    { "storage.read",   "DOWNLOAD" },
    { "storage.write",  "UPLOAD"   },
    { "storage.create", "UPLOAD"   },
    { "storage.modify", "MANAGE"   },
    { "storage.stage",  "STAGE"    },
    { "storage.delete", "DELETE"   },
    { "storage.list",   "LIST"     },
}
Referenced by mac_scope_activity().
scope
const char* scope
Definition at line 108 of file macaroon_endpoint_oauth2.c.
Referenced by brix_auth_gate_cache_key(), brix_build_ca_store_cached(), brix_s3_sign_v4_q(), brix_s3_sigv4_build_sts(), brix_s3_sigv4_sign_and_emit(), brix_token_exchange(), brix_tx_build_body(), mac_scope_activity(), macaroon_append_activity_scope(), macaroon_apply_path_to_scope(), macaroon_parse_activity_caveat(), scope_to_activities(), sd_s3_sign(), sts_sign_query(), token_meta_apply_scope(), token_scope_copy_path(), token_scope_from_heuristic(), token_scope_set_permission(), tpc_cred_oidc_agent_fetch(), tpc_cred_rfc8693_exchange(), webdav_search_parse(), and webdav_tpc_cred_obtain_token().