nginx-xrootd: src/protocols/webdav/macaroon_endpoint.c File Reference
macaroon_endpoint.c File Reference
#include "webdav.h"
#include "auth/token/macaroon.h"
#include "auth/token/macaroon_issue.h"
#include "core/compat/log_diag.h"
#include "core/http/http_body.h"
#include "core/compat/json_min.h"
#include <openssl/rand.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
Macros
#define J_NOT_CONFIGURED "{\"error\":\"not_configured\"}"
#define J_UNAUTHORIZED "{\"error\":\"unauthorized\"}"
#define J_INVALID_REQUEST "{\"error\":\"invalid_request\"}"
#define J_UNSUPPORTED_GT "{\"error\":\"unsupported_grant_type\"}"
#define J_INVALID_SCOPE "{\"error\":\"invalid_scope\"}"
#define J_SERVER_ERROR "{\"error\":\"server_error\"}"
Functions
static int hex_nibble (char c)
static size_t urlencode_decode_inplace (char *str)
static ngx_int_t form_find (const char *form, const char *key, char *dst, size_t dstsz)
static ngx_int_t scope_to_activities (const char *scope, char *act_buf, size_t act_sz, char *path_buf, size_t path_sz)
static ngx_int_t send_json (ngx_http_request_t *r, ngx_int_t status, const char *json, size_t json_len)
ngx_int_t webdav_handle_macaroon_discovery (ngx_http_request_t *r)
void webdav_handle_macaroon_token (ngx_http_request_t *r)
static ngx_int_t mac_iso8601_secs (const char *s, size_t len, time_t max, time_t *out)
static void mac_caveats_scan (const char *body, size_t len, char *act, size_t actsz, char *path, size_t pathsz)
void webdav_handle_macaroon_request (ngx_http_request_t *r)
Macro Definition Documentation
J_INVALID_REQUEST
#define J_INVALID_REQUEST "{\"error\":\"invalid_request\"}"
J_INVALID_SCOPE
#define J_INVALID_SCOPE "{\"error\":\"invalid_scope\"}"
J_NOT_CONFIGURED
#define J_NOT_CONFIGURED "{\"error\":\"not_configured\"}"
J_SERVER_ERROR
#define J_SERVER_ERROR "{\"error\":\"server_error\"}"
J_UNAUTHORIZED
#define J_UNAUTHORIZED "{\"error\":\"unauthorized\"}"
J_UNSUPPORTED_GT
#define J_UNSUPPORTED_GT "{\"error\":\"unsupported_grant_type\"}"
Function Documentation
form_find()
static ngx_int_t form_find (const char * form, const char * key, char * dst, size_t dstsz) static
Definition at line 79 of file macaroon_endpoint.c.
References key, and urlencode_decode_inplace().
Referenced by webdav_handle_macaroon_token().
hex_nibble()
static int hex_nibble (char c) static
Definition at line 39 of file macaroon_endpoint.c.
References c.
Referenced by urlencode_decode_inplace().
mac_caveats_scan()
static void mac_caveats_scan (const char * body, size_t len, char * act, size_t actsz, char * path, size_t pathsz) static
Definition at line 559 of file macaroon_endpoint.c.
Referenced by webdav_handle_macaroon_request().
mac_iso8601_secs()
static ngx_int_t mac_iso8601_secs (const char * s, size_t len, time_t max, time_t * out) static
Definition at line 514 of file macaroon_endpoint.c.
References s.
Referenced by webdav_handle_macaroon_request().
scope_to_activities()
static ngx_int_t scope_to_activities (const char * scope, char * act_buf, size_t act_sz, char * path_buf, size_t path_sz) static
Definition at line 118 of file macaroon_endpoint.c.
Referenced by webdav_handle_macaroon_token().
send_json()
static ngx_int_t send_json (ngx_http_request_t * r, ngx_int_t status, const char * json, size_t json_len) static
Definition at line 194 of file macaroon_endpoint.c.
Referenced by webdav_handle_macaroon_discovery(), webdav_handle_macaroon_request(), and webdav_handle_macaroon_token().
urlencode_decode_inplace()
static size_t urlencode_decode_inplace (char * str) static
Definition at line 49 of file macaroon_endpoint.c.
References hex_nibble().
Referenced by form_find().
webdav_handle_macaroon_discovery()
ngx_int_t webdav_handle_macaroon_discovery (ngx_http_request_t * r)
Definition at line 237 of file macaroon_endpoint.c.
References scheme, and send_json().
Referenced by webdav_dispatch_inner().
webdav_handle_macaroon_request()
void webdav_handle_macaroon_request (ngx_http_request_t * r)
Definition at line 610 of file macaroon_endpoint.c.
References brix_http_body_read_all(), brix_identity_check_token_scope(), brix_json_get_str(), brix_macaroon_issue(), BRIX_MACAROON_ISSUE_OUT_MAX, brix_macaroon_secret_parse(), brix_token_check_read(), brix_token_check_write(), ngx_http_brix_webdav_req_ctx_t::identity, J_INVALID_REQUEST, J_NOT_CONFIGURED, J_SERVER_ERROR, J_UNAUTHORIZED, mac_caveats_scan(), mac_iso8601_secs(), ngx_http_brix_webdav_loc_conf_t::macaroon_location, ngx_http_brix_webdav_loc_conf_t::macaroon_max_validity, ngx_http_brix_webdav_module, scheme, send_json(), ngx_http_brix_webdav_req_ctx_t::token_auth, ngx_http_brix_webdav_loc_conf_t::token_issuer, ngx_http_brix_webdav_loc_conf_t::token_macaroon_secret, ngx_http_brix_webdav_req_ctx_t::token_scope_count, ngx_http_brix_webdav_req_ctx_t::token_scopes, ngx_http_brix_webdav_req_ctx_t::verified, and webdav_metrics_finalize_request().
Referenced by webdav_dispatch_inner().
webdav_handle_macaroon_token()
void webdav_handle_macaroon_token (ngx_http_request_t * r)
Definition at line 271 of file macaroon_endpoint.c.
References BRIX_DIAG_ERR, brix_http_body_read_all(), brix_identity_check_token_scope(), brix_macaroon_issue(), BRIX_MACAROON_ISSUE_OUT_MAX, brix_macaroon_secret_parse(), brix_token_check_read(), brix_token_check_write(), form_find(), ngx_http_brix_webdav_req_ctx_t::identity, J_INVALID_REQUEST, J_INVALID_SCOPE, J_NOT_CONFIGURED, J_SERVER_ERROR, J_UNAUTHORIZED, J_UNSUPPORTED_GT, ngx_http_brix_webdav_module, scheme, scope_to_activities(), send_json(), ngx_http_brix_webdav_req_ctx_t::token_auth, ngx_http_brix_webdav_loc_conf_t::token_issuer, ngx_http_brix_webdav_loc_conf_t::token_macaroon_secret, ngx_http_brix_webdav_req_ctx_t::token_scope_count, ngx_http_brix_webdav_req_ctx_t::token_scopes, ngx_http_brix_webdav_req_ctx_t::verified, and webdav_metrics_finalize_request().
Referenced by webdav_dispatch_inner().