nginx-xrootd: src/auth/token/macaroon.h File Reference
macaroon.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include "token.h"
Functions
int brix_macaroon_validate (ngx_log_t *log, const char *token, size_t token_len, const u_char *root_key, size_t root_key_len, brix_token_claims_t *claims)
int brix_macaroon_validate_bundle (ngx_log_t *log, const char *token, size_t token_len, const u_char *root_key, size_t root_key_len, brix_token_claims_t *claims)
ssize_t brix_macaroon_secret_parse (const char *hex, size_t hex_len, u_char *bin, size_t bin_max)
int brix_token_is_macaroon (const char *token, size_t token_len)
Function Documentation
brix_macaroon_secret_parse()
ssize_t brix_macaroon_secret_parse (const char * hex, size_t hex_len, u_char * bin, size_t bin_max)
Definition at line 55 of file macaroon.c.
References brix_hex_from_char(), and hex().
Referenced by tokenauth_grace_retry(), tokenauth_validate(), webdav_handle_macaroon_request(), webdav_handle_macaroon_token(), webdav_verify_bearer_token(), and wt_grace_retry().
brix_macaroon_validate()
int brix_macaroon_validate (ngx_log_t * log, const char * token, size_t token_len, const u_char * root_key, size_t root_key_len, brix_token_claims_t * claims)
Definition at line 386 of file macaroon.c.
References brix_macaroon_validate_bundle(), and log.
Referenced by token_validate_macaroon().
brix_macaroon_validate_bundle()
int brix_macaroon_validate_bundle (ngx_log_t * log, const char * token, size_t token_len, const u_char * root_key, size_t root_key_len, brix_token_claims_t * claims)
Definition at line 310 of file macaroon.c.
References b64url_decode(), BRIX_MACAROON_MAX_DISCHARGES, BRIX_MACAROON_MAX_TP_CAVEATS, macaroon_parse_input_t::claims, brix_token_claims_t::exp, brix_token_claims_t::iss, macaroon_parse_input_t::key, macaroon_parse_input_t::key_len, log, macaroon_parse_input_t::log, macaroon_bundle_tokenize(), MACAROON_MAX_BIN, macaroon_parse_core(), macaroon_validate_discharges(), macaroon_parse_input_t::max_tp, macaroon_bundle_t::n_tokens, macaroon_parse_input_t::n_tp, brix_token_claims_t::scope_raw, brix_token_claims_t::sub, macaroon_bundle_t::token_lens, macaroon_bundle_t::tokens, and macaroon_parse_input_t::tp_arr.
Referenced by brix_macaroon_validate().
brix_token_is_macaroon()
int brix_token_is_macaroon (const char * token, size_t token_len)
Definition at line 41 of file macaroon.c.
Referenced by brix_token_validate().