nginx-xrootd: src/auth/token/macaroon_parse.c File Reference
macaroon_parse.c File Reference
#include "token_internal.h"
#include "macaroon.h"
#include "macaroon_internal.h"
#include "b64url.h"
#include "scopes.h"
#include "core/compat/hex.h"
#include <openssl/evp.h>
#include <openssl/hmac.h>
#include <openssl/crypto.h>
#include <string.h>
#include <time.h>
Functions
int brix_macaroon_packet_len (const u_char *p)
static ngx_int_t macaroon_packet_identifier (brix_macaroon_parse_state_t *state, const u_char *data, size_t data_len)
static void macaroon_packet_location (brix_macaroon_parse_state_t *state, const u_char *data, size_t data_len)
static ngx_int_t macaroon_packet_cid (brix_macaroon_parse_state_t *state, const u_char *data, size_t data_len)
static void macaroon_record_third_party_caveat (brix_macaroon_parse_state_t *state, const u_char *vid_data, size_t vid_len)
static ngx_int_t macaroon_packet_vid (brix_macaroon_parse_state_t *state, const u_char *data, size_t data_len)
static ngx_int_t macaroon_packet_signature (brix_macaroon_parse_state_t *state, const u_char *data, size_t data_len)
static ngx_int_t macaroon_dispatch_packet (brix_macaroon_parse_state_t *state, const u_char *data, size_t data_len)
static ngx_int_t macaroon_check_expiry (brix_macaroon_parse_state_t *state)
static void macaroon_finalize_scopes (brix_macaroon_parse_state_t *state)
static void macaroon_parse_state_init (brix_macaroon_parse_state_t *state, const macaroon_parse_input_t *in)
int macaroon_parse_core (const macaroon_parse_input_t *in, const u_char *bin, size_t bin_len)
Function Documentation
brix_macaroon_packet_len()
int brix_macaroon_packet_len (const u_char * p)
Definition at line 33 of file macaroon_parse.c.
References brix_hex_from_char().
Referenced by macaroon_candidate_matches_cid(), and macaroon_parse_core().
macaroon_check_expiry()
static ngx_int_t macaroon_check_expiry (brix_macaroon_parse_state_t * state) static
Definition at line 178 of file macaroon_parse.c.
References brix_macaroon_parse_state_t::claims, brix_token_claims_t::exp, brix_macaroon_parse_state_t::log, and brix_macaroon_parse_state_t::tp_arr.
Referenced by macaroon_parse_core().
macaroon_dispatch_packet()
static ngx_int_t macaroon_dispatch_packet (brix_macaroon_parse_state_t * state, const u_char * data, size_t data_len) static
Definition at line 155 of file macaroon_parse.c.
References macaroon_packet_cid(), macaroon_packet_identifier(), macaroon_packet_location(), macaroon_packet_signature(), and macaroon_packet_vid().
Referenced by macaroon_parse_core().
macaroon_finalize_scopes()
static void macaroon_finalize_scopes (brix_macaroon_parse_state_t * state) static
Definition at line 198 of file macaroon_parse.c.
References BRIX_MAX_TOKEN_SCOPES, brix_token_parse_scopes(), brix_macaroon_parse_state_t::claims, brix_macaroon_parse_state_t::log, macaroon_apply_path_caveats(), brix_macaroon_parse_state_t::n_path_caveats, ngx_memcpy, brix_macaroon_parse_state_t::path_caveats, brix_macaroon_parse_state_t::scope_buf, brix_token_claims_t::scope_count, brix_macaroon_parse_state_t::scope_off, brix_token_claims_t::scope_raw, and brix_token_claims_t::scopes.
Referenced by macaroon_parse_core().
macaroon_packet_cid()
static ngx_int_t macaroon_packet_cid (brix_macaroon_parse_state_t * state, const u_char * data, size_t data_len) static
Definition at line 77 of file macaroon_parse.c.
References brix_macaroon_parse_state_t::found_id, brix_macaroon_parse_state_t::have_last_cid, brix_macaroon_parse_state_t::last_cid, brix_macaroon_parse_state_t::last_cid_len, brix_macaroon_parse_state_t::log, macaroon_parse_first_party_caveat(), ngx_memcpy, brix_macaroon_parse_state_t::sig, brix_macaroon_parse_state_t::sig_before_cid, and brix_macaroon_parse_state_t::sig_out_len.
Referenced by macaroon_dispatch_packet().
macaroon_packet_identifier()
static ngx_int_t macaroon_packet_identifier (brix_macaroon_parse_state_t * state, const u_char * data, size_t data_len) static
Definition at line 48 of file macaroon_parse.c.
References brix_macaroon_parse_state_t::claims, brix_macaroon_parse_state_t::found_id, brix_macaroon_parse_state_t::have_last_cid, brix_macaroon_parse_state_t::key, brix_macaroon_parse_state_t::key_len, ngx_memcpy, brix_macaroon_parse_state_t::sig, brix_macaroon_parse_state_t::sig_out_len, and brix_token_claims_t::sub.
Referenced by macaroon_dispatch_packet().
macaroon_packet_location()
static void macaroon_packet_location (brix_macaroon_parse_state_t * state, const u_char * data, size_t data_len) static
Definition at line 65 of file macaroon_parse.c.
References brix_macaroon_parse_state_t::claims, brix_token_claims_t::iss, and ngx_memcpy.
Referenced by macaroon_dispatch_packet().
macaroon_packet_signature()
static ngx_int_t macaroon_packet_signature (brix_macaroon_parse_state_t * state, const u_char * data, size_t data_len) static
Definition at line 139 of file macaroon_parse.c.
References brix_macaroon_parse_state_t::found_sig, brix_macaroon_parse_state_t::log, and brix_macaroon_parse_state_t::sig.
Referenced by macaroon_dispatch_packet().
macaroon_packet_vid()
static ngx_int_t macaroon_packet_vid (brix_macaroon_parse_state_t * state, const u_char * data, size_t data_len) static
Definition at line 123 of file macaroon_parse.c.
References brix_macaroon_parse_state_t::have_last_cid, macaroon_record_third_party_caveat(), ngx_memcpy, brix_macaroon_parse_state_t::sig, and brix_macaroon_parse_state_t::sig_out_len.
Referenced by macaroon_dispatch_packet().
macaroon_parse_core()
int macaroon_parse_core (const macaroon_parse_input_t * in, const u_char * bin, size_t bin_len)
Definition at line 231 of file macaroon_parse.c.
References brix_macaroon_packet_len(), brix_macaroon_parse_state_t::found_sig, log, macaroon_parse_input_t::log, macaroon_check_expiry(), macaroon_dispatch_packet(), macaroon_finalize_scopes(), and macaroon_parse_state_init().
Referenced by brix_macaroon_validate_bundle(), and macaroon_validate_one_discharge().
macaroon_parse_state_init()
static void macaroon_parse_state_init (brix_macaroon_parse_state_t * state, const macaroon_parse_input_t * in) static
Definition at line 214 of file macaroon_parse.c.
References brix_macaroon_parse_state_t::claims, macaroon_parse_input_t::claims, brix_macaroon_parse_state_t::key, macaroon_parse_input_t::key, brix_macaroon_parse_state_t::key_len, macaroon_parse_input_t::key_len, brix_macaroon_parse_state_t::log, macaroon_parse_input_t::log, brix_macaroon_parse_state_t::max_tp, macaroon_parse_input_t::max_tp, brix_macaroon_parse_state_t::n_tp, macaroon_parse_input_t::n_tp, brix_macaroon_parse_state_t::tp_arr, and macaroon_parse_input_t::tp_arr.
Referenced by macaroon_parse_core().
macaroon_record_third_party_caveat()
static void macaroon_record_third_party_caveat (brix_macaroon_parse_state_t * state, const u_char * vid_data, size_t vid_len) static
Definition at line 104 of file macaroon_parse.c.
References brix_macaroon_tp_t::cid, brix_macaroon_tp_t::cid_len, brix_macaroon_parse_state_t::have_last_cid, brix_macaroon_parse_state_t::last_cid, brix_macaroon_parse_state_t::last_cid_len, brix_macaroon_parse_state_t::max_tp, brix_macaroon_parse_state_t::n_tp, ngx_memcpy, brix_macaroon_tp_t::sig_before, brix_macaroon_parse_state_t::sig_before_cid, brix_macaroon_parse_state_t::tp_arr, brix_macaroon_tp_t::vid, and brix_macaroon_tp_t::vid_len.
Referenced by macaroon_packet_vid().