nginx-xrootd: src/observability/pmark/mapping.c File Reference
mapping.c File Reference
#include "pmark.h"
#include "core/compat/cstr.h"
#include <sys/socket.h>
#include <netinet/in.h>
#include <netdb.h>
#include <string.h>
Functions
static int pmark_path_match (const char *path, ngx_str_t *pat)
static int pmark_csv_has (const char *csv, ngx_str_t *needle)
static int pmark_extract_role (const char *vo_csv, char *out, size_t outlen)
static ngx_int_t pmark_resolve_dest (ngx_str_t *spec, brix_pmark_dest_t *dst, ngx_log_t *log)
static ngx_array_t * pmark_load_defs (brix_pmark_conf_t *pm, ngx_pool_t *pool, ngx_log_t *log)
static ngx_int_t pmark_resolve_exp_rules (brix_pmark_conf_t *pm, ngx_array_t *defs, ngx_pool_t *pool, ngx_log_t *log)
static ngx_int_t pmark_resolve_act_rules (brix_pmark_conf_t *pm, ngx_array_t *defs, ngx_pool_t *pool, ngx_log_t *log)
static ngx_int_t pmark_resolve_dests (brix_pmark_conf_t *pm, ngx_pool_t *pool, ngx_log_t *log)
ngx_int_t brix_pmark_runtime_ensure (brix_pmark_conf_t *pm, ngx_pool_t *pool, ngx_log_t *log)
static int pmark_str_eq (const char *s, ngx_str_t *pat)
static ngx_uint_t pmark_map_experiment (brix_pmark_conf_t *pm, const char *vo_csv, const char *path)
static ngx_uint_t pmark_map_activity (brix_pmark_conf_t *pm, ngx_uint_t e, const char *vo_csv, const char *user)
ngx_int_t brix_pmark_map_codes (brix_pmark_conf_t *pm, const brix_pmark_flow_id_t *flow, ngx_uint_t *exp, ngx_uint_t *act)
Function Documentation
brix_pmark_map_codes()
ngx_int_t brix_pmark_map_codes (brix_pmark_conf_t * pm, const brix_pmark_flow_id_t * flow, ngx_uint_t * exp, ngx_uint_t * act)
Definition at line 437 of file mapping.c.
References brix_pmark_codes_valid(), brix_pmark_parse_scitag(), brix_pmark_flow_id_t::cgi, brix_pmark_flow_id_t::path, pmark_map_activity(), pmark_map_experiment(), brix_pmark_conf_t::scitag_cgi, brix_pmark_flow_id_t::user, and brix_pmark_flow_id_t::vo_csv.
Referenced by brix_pmark_flow_begin(), tpc_pull_resolve_pmark(), and webdav_tpc_pmark_attach().
brix_pmark_runtime_ensure()
ngx_int_t brix_pmark_runtime_ensure (brix_pmark_conf_t * pm, ngx_pool_t * pool, ngx_log_t * log)
Definition at line 313 of file mapping.c.
References brix_pmark_conf_t::enable, log, pmark_load_defs(), pmark_resolve_act_rules(), pmark_resolve_dests(), pmark_resolve_exp_rules(), brix_pmark_conf_t::rt_ok, and brix_pmark_conf_t::rt_ready.
Referenced by brix_pmark_flow_begin(), tpc_pull_resolve_pmark(), and webdav_tpc_pmark_attach().
pmark_csv_has()
static int pmark_csv_has (const char * csv, ngx_str_t * needle) static
Definition at line 53 of file mapping.c.
References tok.
Referenced by pmark_map_experiment().
pmark_extract_role()
static int pmark_extract_role (const char * vo_csv, char * out, size_t outlen) static
Definition at line 83 of file mapping.c.
References ngx_memcpy.
Referenced by pmark_map_activity().
pmark_load_defs()
static ngx_array_t * pmark_load_defs (brix_pmark_conf_t * pm, ngx_pool_t * pool, ngx_log_t * log) static
Definition at line 173 of file mapping.c.
References brix_pmark_defsfile_load(), brix_str_cbuf(), brix_pmark_conf_t::defsfile, and log.
Referenced by brix_pmark_runtime_ensure().
pmark_map_activity()
static ngx_uint_t pmark_map_activity (brix_pmark_conf_t * pm, ngx_uint_t e, const char * vo_csv, const char * user) static
Definition at line 396 of file mapping.c.
References brix_pmark_act_rule_r_t::act_id, brix_pmark_conf_t::act_rules_r, BRIX_PMARK_ACTR_DEFAULT, BRIX_PMARK_ACTR_ROLE, BRIX_PMARK_ACTR_USER, pmark_extract_role(), and pmark_str_eq().
Referenced by brix_pmark_map_codes().
pmark_map_experiment()
static ngx_uint_t pmark_map_experiment (brix_pmark_conf_t * pm, const char * vo_csv, const char * path) static
Definition at line 359 of file mapping.c.
References BRIX_PMARK_EXP_DEFAULT, BRIX_PMARK_EXP_PATH, BRIX_PMARK_EXP_VO, brix_pmark_exp_rule_r_t::exp_id, brix_pmark_conf_t::exp_rules_r, pmark_csv_has(), and pmark_path_match().
Referenced by brix_pmark_map_codes().
pmark_path_match()
static int pmark_path_match (const char * path, ngx_str_t * pat) static
Definition at line 33 of file mapping.c.
Referenced by pmark_map_experiment().
pmark_resolve_act_rules()
static ngx_int_t pmark_resolve_act_rules (brix_pmark_conf_t * pm, ngx_array_t * defs, ngx_pool_t * pool, ngx_log_t * log) static
Definition at line 234 of file mapping.c.
References brix_pmark_act_rule_r_t::act_id, brix_pmark_conf_t::act_rules, brix_pmark_conf_t::act_rules_r, brix_pmark_defs_act_id(), brix_pmark_defs_exp_id(), brix_pmark_act_rule_r_t::exp_id, brix_pmark_act_rule_t::kind, brix_pmark_act_rule_r_t::kind, log, brix_pmark_act_rule_t::match, and brix_pmark_act_rule_r_t::match.
Referenced by brix_pmark_runtime_ensure().
pmark_resolve_dest()
static ngx_int_t pmark_resolve_dest (ngx_str_t * spec, brix_pmark_dest_t * dst, ngx_log_t * log) static
Definition at line 109 of file mapping.c.
References BRIX_PMARK_FF_PORT, brix_pmark_dest_t::family, host, brix_pmark_dest_t::len, log, ngx_memcpy, port, and brix_pmark_dest_t::ss.
Referenced by pmark_resolve_dests().
pmark_resolve_dests()
static ngx_int_t pmark_resolve_dests (brix_pmark_conf_t * pm, ngx_pool_t * pool, ngx_log_t * log) static
Definition at line 277 of file mapping.c.
References brix_pmark_conf_t::dest_sa, brix_pmark_conf_t::firefly, brix_pmark_conf_t::firefly_dest, log, and pmark_resolve_dest().
Referenced by brix_pmark_runtime_ensure().
pmark_resolve_exp_rules()
static ngx_int_t pmark_resolve_exp_rules (brix_pmark_conf_t * pm, ngx_array_t * defs, ngx_pool_t * pool, ngx_log_t * log) static
Definition at line 195 of file mapping.c.
References brix_pmark_defs_exp_id(), brix_pmark_exp_rule_r_t::exp_id, brix_pmark_conf_t::exp_rules, brix_pmark_conf_t::exp_rules_r, brix_pmark_exp_rule_t::kind, brix_pmark_exp_rule_r_t::kind, log, brix_pmark_exp_rule_t::match, and brix_pmark_exp_rule_r_t::match.
Referenced by brix_pmark_runtime_ensure().
pmark_str_eq()
static int pmark_str_eq (const char * s, ngx_str_t * pat) static
Definition at line 348 of file mapping.c.
References s.
Referenced by pmark_map_activity().