nginx-xrootd: client/lib/observability/metabench/metabench.c File Reference
metabench.c File Reference
#include "metabench.h"
#include <stdlib.h>
#include <string.h>
Functions
void metabench_plan_init (metabench_plan *p, int workers, int ops_per_worker, int p99_ceil_ms)
long metabench_storm_ops (const metabench_plan *p)
static int entry_cmp (const void *a, const void *b)
size_t metabench_expected (const metabench_plan *p, metabench_entry *out, size_t cap)
static int dbl_cmp (const void *a, const void *b)
double metabench_percentile (const double *ms, size_t n, double pct)
void metabench_result_print (const metabench_result *r, FILE *f)
void metabench_result_json (const metabench_result *r, FILE *f)
Function Documentation
dbl_cmp()
static int dbl_cmp (const void * a, const void * b) static
Definition at line 81 of file metabench.c.
Referenced by metabench_percentile().
entry_cmp()
static int entry_cmp (const void * a, const void * b) static
Definition at line 38 of file metabench.c.
Referenced by metabench_expected().
metabench_expected()
size_t metabench_expected (const metabench_plan * p, metabench_entry * out, size_t cap)
Definition at line 44 of file metabench.c.
References metabench_plan::dirs_per_worker, entry_cmp(), metabench_plan::files_per_dir, metabench_entry::is_dir, metabench_entry::mode, and metabench_plan::workers.
Referenced by main().
metabench_percentile()
double metabench_percentile (const double * ms, size_t n, double pct)
Definition at line 87 of file metabench.c.
References c, and dbl_cmp().
Referenced by main(), and metabench_run().
metabench_plan_init()
void metabench_plan_init (metabench_plan * p, int workers, int ops_per_worker, int p99_ceil_ms)
Definition at line 13 of file metabench.c.
References D, metabench_plan::dirs_per_worker, metabench_plan::files_per_dir, metabench_plan::p99_ceil_ms, and metabench_plan::workers.
Referenced by do_metabench(), and main().
metabench_result_json()
void metabench_result_json (const metabench_result * r, FILE * f)
Definition at line 120 of file metabench.c.
References metabench_result::failures, metabench_result::nworkers, metabench_result::ops_per_sec, metabench_result::p50_ms, metabench_result::p95_ms, metabench_result::p99_ms, metabench_result::phase, metabench_result::total_ops, and metabench_result::wall_s.
metabench_result_print()
void metabench_result_print (const metabench_result * r, FILE * f)
Definition at line 111 of file metabench.c.
References metabench_result::failures, metabench_result::ops_per_sec, metabench_result::p50_ms, metabench_result::p95_ms, metabench_result::p99_ms, and metabench_result::total_ops.
Referenced by do_metabench().
metabench_storm_ops()
long metabench_storm_ops (const metabench_plan * p)
Definition at line 28 of file metabench.c.
References metabench_plan::dirs_per_worker, metabench_plan::files_per_dir, and metabench_plan::workers.
Referenced by main(), and metabench_run().