nginx-xrootd: src/protocols/root/query/metadata.c File Reference
metadata.c File Reference
#include "query_internal.h"
#include "core/ident.h"
Functions
static ngx_int_t brix_query_arg_missing (brix_ctx_t *ctx, ngx_connection_t *c, const char *tag, ngx_uint_t op)
static ngx_int_t brix_query_fsctl_unsupported (brix_ctx_t *ctx, ngx_connection_t *c, const char *path, const char *tag, ngx_uint_t op)
static ngx_int_t brix_query_fctl_unsupported (brix_ctx_t *ctx, ngx_connection_t *c, const char *path, const char *tag, ngx_uint_t op)
static ngx_flag_t brix_query_payload_equals (brix_ctx_t *ctx, const char *text)
ngx_int_t brix_query_stats (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_query_xattr (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_query_finfo (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_query_visa (brix_ctx_t *ctx, ngx_connection_t *c, const xrdw_query_req_t *req)
ngx_int_t brix_query_opaque (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_query_opaquf (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_query_opaqug (brix_ctx_t *ctx, ngx_connection_t *c, const xrdw_query_req_t *req)
Function Documentation
brix_query_arg_missing()
static ngx_int_t brix_query_arg_missing (brix_ctx_t * ctx, ngx_connection_t * c, const char * tag, ngx_uint_t op) static
Definition at line 23 of file metadata.c.
References BRIX_RETURN_ERR, c, and kXR_ArgMissing.
Referenced by brix_query_opaque(), and brix_query_opaquf().
brix_query_fctl_unsupported()
static ngx_int_t brix_query_fctl_unsupported (brix_ctx_t * ctx, ngx_connection_t * c, const char * path, const char * tag, ngx_uint_t op) static
Definition at line 39 of file metadata.c.
References BRIX_RETURN_ERR, c, and kXR_Unsupported.
Referenced by brix_query_opaqug(), and brix_query_visa().
brix_query_finfo()
ngx_int_t brix_query_finfo (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 218 of file metadata.c.
References brix_log_access(), BRIX_OP_OK, BRIX_OP_QUERY_FINFO, brix_send_ok(), and c.
Referenced by brix_handle_query().
brix_query_fsctl_unsupported()
static ngx_int_t brix_query_fsctl_unsupported (brix_ctx_t * ctx, ngx_connection_t * c, const char * path, const char * tag, ngx_uint_t op) static
Definition at line 31 of file metadata.c.
References BRIX_RETURN_ERR, c, and kXR_Unsupported.
Referenced by brix_query_opaque(), and brix_query_opaquf().
brix_query_opaque()
ngx_int_t brix_query_opaque (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 247 of file metadata.c.
References BRIX_OP_QUERY_OPAQUE, brix_query_arg_missing(), brix_query_fsctl_unsupported(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by brix_handle_query().
brix_query_opaquf()
ngx_int_t brix_query_opaquf (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 261 of file metadata.c.
References brix_auth_gate(), BRIX_AUTH_READ, brix_beneath_full_path(), brix_extract_path(), BRIX_MAX_PATH, BRIX_OP_QUERY_OPAQUF, brix_query_arg_missing(), brix_query_fsctl_unsupported(), BRIX_RETURN_ERR, c, ngx_stream_brix_srv_conf_t::common, brix_ctx_recv_t::cur_dlen, kXR_ArgInvalid, PATH_MAX, brix_ctx_recv_t::payload, brix_ctx_t::recv, ngx_http_brix_shared_conf_t::root_canon, and brix_ctx_t::write_rc.
Referenced by brix_handle_query().
brix_query_opaqug()
ngx_int_t brix_query_opaqug (brix_ctx_t * ctx, ngx_connection_t * c, const xrdw_query_req_t * req)
Definition at line 294 of file metadata.c.
References BRIX_OP_QUERY_OPAQUG, brix_query_fctl_unsupported(), brix_query_payload_equals(), BRIX_RETURN_ERR, brix_validate_file_handle(), c, xrdw_query_req_t::fhandle, brix_ctx_t::files, kXR_FSError, and brix_file_t::path.
Referenced by brix_handle_query().
brix_query_payload_equals()
static ngx_flag_t brix_query_payload_equals (brix_ctx_t * ctx, const char * text) static
Definition at line 47 of file metadata.c.
References brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by brix_query_opaqug().
brix_query_stats()
ngx_int_t brix_query_stats (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 68 of file metadata.c.
References brix_log_access(), BRIX_OP_OK, BRIX_OP_QUERY_STATS, brix_send_ok(), BRIX_SERVER_NAME, BRIX_SERVER_VERSION, ngx_brix_srv_metrics_t::bytes_rx_total, ngx_brix_srv_metrics_t::bytes_tx_total, c, ngx_brix_srv_metrics_t::connections_active, ngx_brix_srv_metrics_t::connections_total, brix_ctx_t::metrics, and ngx_brix_srv_metrics_t::port.
Referenced by brix_handle_query().
brix_query_visa()
ngx_int_t brix_query_visa (brix_ctx_t * ctx, ngx_connection_t * c, const xrdw_query_req_t * req)
Definition at line 228 of file metadata.c.
References BRIX_OP_QUERY_VISA, brix_query_fctl_unsupported(), brix_validate_file_handle(), c, xrdw_query_req_t::fhandle, brix_ctx_t::files, and brix_file_t::path.
Referenced by brix_handle_query().
brix_query_xattr()
ngx_int_t brix_query_xattr (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 119 of file metadata.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_vfs_stat_t::atime, brix_auth_gate(), BRIX_AUTH_READ, brix_beneath_full_path(), brix_extract_path(), brix_kxr_from_errno(), brix_log_access(), BRIX_MAX_PATH, BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_QUERY_XATTR, BRIX_PROTO_ROOT, brix_send_error(), brix_send_ok(), brix_vfs_ctx_init(), brix_vfs_getxattr(), brix_vfs_listxattr(), brix_vfs_probe(), c, ngx_stream_brix_srv_conf_t::common, brix_vfs_stat_t::ctime, brix_ctx_recv_t::cur_dlen, brix_vfs_stat_t::is_directory, brix_vfs_stat_t::is_regular, kXR_ArgInvalid, kXR_ArgMissing, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, PATH_MAX, brix_ctx_recv_t::payload, brix_vfs_ctx_t::pool, brix_ctx_t::recv, ngx_http_brix_shared_conf_t::root_canon, brix_vfs_stat_t::size, and brix_ctx_t::write_rc.
Referenced by brix_handle_query().