nginx-xrootd: src/fs/cache/meta.c File Reference
meta.c File Reference
#include "meta.h"
#include "cinfo.h"
#include "fs/meta/xmeta_path.h"
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
Functions
ngx_int_t brix_cache_meta_from_stat (const struct stat *st, const char *etag, brix_cache_meta_t *meta)
static ngx_int_t cache_meta_read_legacy (const char *cache_path, brix_cache_meta_t *meta)
ngx_int_t brix_cache_meta_read (ngx_log_t *log, const char *cache_path, brix_cache_meta_t *meta)
static void meta_onto_record (const brix_cache_meta_t *meta, brix_xmeta_t *xm)
ngx_int_t brix_cache_meta_touch (ngx_log_t *log, const char *cache_path, uint64_t nbytes)
ngx_int_t brix_cache_meta_write (ngx_log_t *log, const char *cache_path, const brix_cache_meta_t *meta)
Function Documentation
brix_cache_meta_from_stat()
ngx_int_t brix_cache_meta_from_stat (const struct stat * st, const char * etag, brix_cache_meta_t * meta)
Definition at line 13 of file meta.c.
References BRIX_CACHE_META_ETAG_MAX, brix_cache_meta_t::etag, brix_cache_meta_t::etag_len, brix_cache_meta_t::mtime, ngx_memcpy, and brix_cache_meta_t::size.
Referenced by brix_cache_commit_staged().
brix_cache_meta_read()
ngx_int_t brix_cache_meta_read (ngx_log_t * log, const char * cache_path, brix_cache_meta_t * meta)
Definition at line 79 of file meta.c.
References brix_xmeta_t::access_cnt, brix_cache_meta_t::access_count, brix_xmeta_t::astat, BRIX_CACHE_META_VERSION, BRIX_XMETA_FOREIGN, brix_xmeta_free(), BRIX_XMETA_OK, brix_xmeta_path_load(), brix_xmeta_astat_t::bytes_hit, brix_cache_meta_t::bytes_served, cache_meta_read_legacy(), brix_cache_meta_t::cks_alg, brix_xmeta_t::cks_alg, brix_cache_meta_t::cks_alg_len, brix_xmeta_t::cks_alg_len, brix_cache_meta_t::cks_hex, brix_xmeta_t::cks_hex, brix_cache_meta_t::cks_len, brix_xmeta_t::cks_len, brix_xmeta_astat_t::detach_time, brix_xmeta_t::etag, brix_cache_meta_t::etag, brix_cache_meta_t::etag_len, brix_xmeta_t::etag_len, brix_xmeta_t::file_size, brix_cache_meta_t::last_access, log, brix_cache_meta_t::mtime, ngx_memcpy, brix_xmeta_t::origin_mtime, brix_cache_meta_t::size, and brix_cache_meta_t::version.
Referenced by brix_cache_validate_meta().
brix_cache_meta_touch()
ngx_int_t brix_cache_meta_touch (ngx_log_t * log, const char * cache_path, uint64_t nbytes)
Definition at line 150 of file meta.c.
References brix_xmeta_t::access_cnt, brix_xmeta_t::astat, brix_xmeta_t::astat_count, brix_xmeta_astat_t::attach_time, BRIX_XMETA_FOREIGN, brix_xmeta_free(), BRIX_XMETA_OK, brix_xmeta_path_load(), brix_xmeta_path_lock(), brix_xmeta_path_save(), brix_xmeta_path_unlock(), brix_xmeta_astat_t::bytes_hit, brix_xmeta_astat_t::detach_time, and log.
brix_cache_meta_write()
ngx_int_t brix_cache_meta_write (ngx_log_t * log, const char * cache_path, const brix_cache_meta_t * meta)
Definition at line 191 of file meta.c.
References brix_xmeta_t::bitmap, BRIX_CACHE_DIRTY_BLOCK, BRIX_XMETA_ERR, BRIX_XMETA_FOREIGN, brix_xmeta_free(), brix_xmeta_init(), BRIX_XMETA_OK, brix_xmeta_path_load(), brix_xmeta_path_lock(), brix_xmeta_path_save(), brix_xmeta_path_unlock(), brix_xmeta_t::have_blockcrc, log, meta_onto_record(), brix_xmeta_t::nblocks, and brix_cache_meta_t::size.
Referenced by brix_cache_commit_staged().
cache_meta_read_legacy()
static ngx_int_t cache_meta_read_legacy (const char * cache_path, brix_cache_meta_t * meta) static
Definition at line 53 of file meta.c.
References BRIX_CACHE_META_BASE_SIZE, BRIX_CACHE_META_ETAG_MAX, brix_cache_meta_path(), close(), brix_cache_meta_t::etag_len, open(), PATH_MAX, read(), and brix_cache_meta_t::version.
Referenced by brix_cache_meta_read().
meta_onto_record()
static void meta_onto_record (const brix_cache_meta_t * meta, brix_xmeta_t * xm) static
Definition at line 125 of file meta.c.
References brix_xmeta_t::access_cnt, brix_cache_meta_t::access_count, brix_xmeta_t::astat, brix_xmeta_t::astat_count, brix_xmeta_astat_t::attach_time, brix_xmeta_astat_t::bytes_hit, brix_cache_meta_t::bytes_served, brix_cache_meta_t::cks_alg, brix_xmeta_t::cks_alg, brix_cache_meta_t::cks_alg_len, brix_xmeta_t::cks_alg_len, brix_cache_meta_t::cks_hex, brix_xmeta_t::cks_hex, brix_cache_meta_t::cks_len, brix_xmeta_t::cks_len, brix_xmeta_astat_t::detach_time, brix_xmeta_t::etag, brix_cache_meta_t::etag, brix_cache_meta_t::etag_len, brix_xmeta_t::etag_len, brix_cache_meta_t::last_access, brix_cache_meta_t::mtime, ngx_memcpy, and brix_xmeta_t::origin_mtime.
Referenced by brix_cache_meta_write().