nginx-xrootd: src/fs/backend/meta_advisory.h File Reference
meta_advisory.h File Reference
#include <sys/types.h>
#include <stddef.h>
Data Structures
struct brix_meta_advisory_t
Macros
#define BRIX_META_ADVISORY_XATTR "user.xrd.unixattr"
#define BRIX_META_ADVISORY_S3META "xrd-unixattr" /* → x-amz-meta-xrd-unixattr */
Functions
int brix_meta_advisory_encode (const brix_meta_advisory_t *m, char *out, size_t cap)
int brix_meta_advisory_decode (const char *blob, size_t len, brix_meta_advisory_t *m)
int brix_meta_advisory_patch (char *blob, size_t cap, const brix_meta_advisory_t *delta)
Macro Definition Documentation
BRIX_META_ADVISORY_S3META
#define BRIX_META_ADVISORY_S3META "xrd-unixattr" /* → x-amz-meta-xrd-unixattr */
Definition at line 32 of file meta_advisory.h.
BRIX_META_ADVISORY_XATTR
#define BRIX_META_ADVISORY_XATTR "user.xrd.unixattr"
Definition at line 31 of file meta_advisory.h.
Function Documentation
brix_meta_advisory_decode()
int brix_meta_advisory_decode (const char * blob, size_t len, brix_meta_advisory_t * m)
Definition at line 68 of file meta_advisory.c.
References brix_meta_advisory_t::gid, brix_meta_advisory_t::have_mode, brix_meta_advisory_t::have_mtime, brix_meta_advisory_t::have_owner, key, brix_meta_advisory_t::mode, brix_meta_advisory_t::mtime, brix_meta_advisory_t::mtime_ns, and brix_meta_advisory_t::uid.
Referenced by brix_meta_advisory_patch(), and sd_s3_get_unixattr().
brix_meta_advisory_encode()
int brix_meta_advisory_encode (const brix_meta_advisory_t * m, char * out, size_t cap)
Definition at line 39 of file meta_advisory.c.
References adv_append(), brix_meta_advisory_t::gid, brix_meta_advisory_t::have_mode, brix_meta_advisory_t::have_mtime, brix_meta_advisory_t::have_owner, brix_meta_advisory_t::mode, brix_meta_advisory_t::mtime, brix_meta_advisory_t::mtime_ns, and brix_meta_advisory_t::uid.
Referenced by brix_meta_advisory_patch(), and sd_s3_set_unixattr().
brix_meta_advisory_patch()
int brix_meta_advisory_patch (char * blob, size_t cap, const brix_meta_advisory_t * delta)
Definition at line 123 of file meta_advisory.c.
References brix_meta_advisory_decode(), brix_meta_advisory_encode(), brix_meta_advisory_t::gid, brix_meta_advisory_t::have_mode, brix_meta_advisory_t::have_mtime, brix_meta_advisory_t::have_owner, brix_meta_advisory_t::mode, brix_meta_advisory_t::mtime, brix_meta_advisory_t::mtime_ns, and brix_meta_advisory_t::uid.