nginx-xrootd: src/fs/backend/meta_advisory.c File Reference
meta_advisory.c File Reference
#include "meta_advisory.h"
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Macros
#define _POSIX_C_SOURCE 200809L
Functions
static int adv_append (char *out, size_t cap, int *n, const char *fmt,...)
int brix_meta_advisory_encode (const brix_meta_advisory_t *m, char *out, size_t cap)
int brix_meta_advisory_decode (const char *blob, size_t len, brix_meta_advisory_t *m)
int brix_meta_advisory_patch (char *blob, size_t cap, const brix_meta_advisory_t *delta)
Macro Definition Documentation
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
Definition at line 7 of file meta_advisory.c.
Function Documentation
adv_append()
static int adv_append (char * out, size_t cap, int * n, const char * fmt, ...) static
Definition at line 23 of file meta_advisory.c.
Referenced by brix_meta_advisory_encode().
brix_meta_advisory_decode()
int brix_meta_advisory_decode (const char * blob, size_t len, brix_meta_advisory_t * m)
Definition at line 68 of file meta_advisory.c.
References brix_meta_advisory_t::gid, brix_meta_advisory_t::have_mode, brix_meta_advisory_t::have_mtime, brix_meta_advisory_t::have_owner, key, brix_meta_advisory_t::mode, brix_meta_advisory_t::mtime, brix_meta_advisory_t::mtime_ns, tok, and brix_meta_advisory_t::uid.
Referenced by brix_meta_advisory_patch(), and sd_s3_get_unixattr().
brix_meta_advisory_encode()
int brix_meta_advisory_encode (const brix_meta_advisory_t * m, char * out, size_t cap)
Definition at line 39 of file meta_advisory.c.
References adv_append(), brix_meta_advisory_t::gid, brix_meta_advisory_t::have_mode, brix_meta_advisory_t::have_mtime, brix_meta_advisory_t::have_owner, brix_meta_advisory_t::mode, brix_meta_advisory_t::mtime, brix_meta_advisory_t::mtime_ns, and brix_meta_advisory_t::uid.
Referenced by brix_meta_advisory_patch(), and sd_s3_set_unixattr().
brix_meta_advisory_patch()
int brix_meta_advisory_patch (char * blob, size_t cap, const brix_meta_advisory_t * delta)
Definition at line 123 of file meta_advisory.c.
References brix_meta_advisory_decode(), brix_meta_advisory_encode(), brix_meta_advisory_t::gid, brix_meta_advisory_t::have_mode, brix_meta_advisory_t::have_mtime, brix_meta_advisory_t::have_owner, brix_meta_advisory_t::mode, brix_meta_advisory_t::mtime, brix_meta_advisory_t::mtime_ns, and brix_meta_advisory_t::uid.