nginx-xrootd: client/lib/observability/metabench/metabench_run.c File Reference
metabench_run.c File Reference
#include "metabench_run.h"
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct mb_worker
Functions
static void mb_record (mb_worker *w, uint64_t t0)
static void mb_create (mb_worker *w, brix_conn *c)
static void mb_remove (mb_worker *w, brix_conn *c)
static void * mb_thread (void *arg)
static void mb_init_workers (mb_worker *wk, int W, const brix_url *url, const brix_opts *opts, const metabench_plan *plan, metabench_phase phase, long per_cap)
static double mb_run_workers (mb_worker *wk, pthread_t *th, int W)
static long mb_total_lat (const mb_worker *wk, int W)
static long mb_aggregate (metabench_result *out, mb_worker *wk, int W, double *all, double wall)
static int mb_verdict (const metabench_result *out, const metabench_plan *plan)
int metabench_run (const brix_url *url, const brix_opts *opts, const metabench_plan *plan, metabench_phase phase, metabench_result *out, brix_status *st)
Function Documentation
mb_aggregate()
static long mb_aggregate (metabench_result * out, mb_worker * wk, int W, double * all, double wall) static
Definition at line 239 of file metabench_run.c.
References metabench_wstat::failures, metabench_result::failures, mb_worker::failures, metabench_wstat::id, mb_worker::lat_ms, mb_worker::lat_n, metabench_wstat::ops, mb_worker::ops, metabench_wstat::ops_per_sec, metabench_result::per_worker, and metabench_result::total_ops.
Referenced by metabench_run().
mb_create()
static void mb_create (mb_worker * w, brix_conn * c) static
Definition at line 42 of file metabench_run.c.
References brix_chmod(), brix_file_close(), brix_file_open_write(), brix_mkdir(), brix_mono_ns(), brix_stat(), c, metabench_plan::dirs_per_worker, mb_worker::failures, metabench_plan::files_per_dir, brix_statinfo::have_ext, mb_worker::id, mb_record(), brix_statinfo::mode, mb_worker::ops, and mb_worker::plan.
Referenced by mb_thread().
mb_init_workers()
static void mb_init_workers (mb_worker * wk, int W, const brix_url * url, const brix_opts * opts, const metabench_plan * plan, metabench_phase phase, long per_cap) static
Definition at line 165 of file metabench_run.c.
References mb_worker::id, mb_worker::lat_cap, mb_worker::lat_ms, mb_worker::opts, mb_worker::phase, mb_worker::plan, and mb_worker::url.
Referenced by metabench_run().
mb_record()
static void mb_record (mb_worker * w, uint64_t t0) static
Definition at line 32 of file metabench_run.c.
References brix_mono_ns(), mb_worker::lat_cap, mb_worker::lat_ms, and mb_worker::lat_n.
Referenced by mb_create(), and mb_remove().
mb_remove()
static void mb_remove (mb_worker * w, brix_conn * c) static
Definition at line 100 of file metabench_run.c.
References brix_mono_ns(), brix_rm(), brix_rmdir(), c, metabench_plan::dirs_per_worker, mb_worker::failures, metabench_plan::files_per_dir, mb_worker::id, mb_record(), mb_worker::ops, and mb_worker::plan.
Referenced by mb_thread().
mb_run_workers()
static double mb_run_workers (mb_worker * wk, pthread_t * th, int W) static
Definition at line 192 of file metabench_run.c.
References brix_mono_ns(), and mb_thread().
Referenced by metabench_run().
mb_thread()
static void * mb_thread (void * arg) static
Definition at line 128 of file metabench_run.c.
References brix_close(), brix_connect(), brix_status_clear(), c, mb_worker::failures, mb_worker::lat_cap, MB_CREATE, mb_create(), mb_remove(), mb_worker::ops, mb_worker::opts, mb_worker::phase, and mb_worker::url.
Referenced by mb_run_workers().
mb_total_lat()
static long mb_total_lat (const mb_worker * wk, int W) static
Definition at line 214 of file metabench_run.c.
References mb_worker::lat_n.
Referenced by metabench_run().
mb_verdict()
static int mb_verdict (const metabench_result * out, const metabench_plan * plan) static
Definition at line 270 of file metabench_run.c.
References metabench_result::failures, metabench_plan::p99_ceil_ms, and metabench_result::p99_ms.
Referenced by metabench_run().
metabench_run()
int metabench_run (const brix_url * url, const brix_opts * opts, const metabench_plan * plan, metabench_phase phase, metabench_result * out, brix_status * st)
Definition at line 277 of file metabench_run.c.
References mb_aggregate(), mb_init_workers(), mb_run_workers(), mb_total_lat(), mb_verdict(), metabench_percentile(), metabench_storm_ops(), metabench_result::nworkers, metabench_result::ops_per_sec, metabench_result::p50_ms, metabench_result::p95_ms, metabench_result::p99_ms, metabench_result::phase, metabench_result::total_ops, metabench_result::wall_s, and metabench_plan::workers.
Referenced by do_metabench().