nginx-xrootd: src/net/cms/meter.c File Reference
meter.c File Reference
#include "meter.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Functions
static uint8_t meter_clamp_pct (unsigned long v)
int brix_cms_meter_parse_loadavg (const char *buf, long ncpu, uint8_t *pct)
static int meter_find_counter (const char *buf, const char *key, uint64_t *out)
int brix_cms_meter_parse_meminfo (const char *buf, uint8_t *pct)
static int meter_netdev_line_bytes (const char *colon, uint64_t *bytes)
int brix_cms_meter_parse_netdev (const char *buf, uint64_t *total_bytes)
int brix_cms_meter_parse_vmstat (const char *buf, uint64_t *pgmajfault)
uint8_t brix_cms_meter_rate_pct (uint64_t delta, uint64_t elapsed_ms, uint64_t ref_per_sec)
static int meter_slurp (const char *path, char *buf, size_t bufsz)
static void meter_sample_gauges (uint8_t out5[5])
static void meter_fold_deltas (brix_cms_meter_t *m, uint64_t now_ms, int have_net, uint64_t net_bytes, int have_pag, uint64_t pgmaj, uint8_t out5[5])
void brix_cms_meter_sample (brix_cms_meter_t *m, uint64_t now_ms, uint8_t out5[5])
Function Documentation
brix_cms_meter_parse_loadavg()
int brix_cms_meter_parse_loadavg (const char * buf, long ncpu, uint8_t * pct)
Definition at line 35 of file meter.c.
References meter_clamp_pct().
Referenced by meter_sample_gauges(), and test_loadavg().
brix_cms_meter_parse_meminfo()
int brix_cms_meter_parse_meminfo (const char * buf, uint8_t * pct)
Definition at line 85 of file meter.c.
References meter_clamp_pct(), and meter_find_counter().
Referenced by meter_sample_gauges(), and test_meminfo().
brix_cms_meter_parse_netdev()
int brix_cms_meter_parse_netdev (const char * buf, uint64_t * total_bytes)
Definition at line 141 of file meter.c.
References meter_netdev_line_bytes(), and name.
Referenced by brix_cms_meter_sample(), and test_netdev().
brix_cms_meter_parse_vmstat()
int brix_cms_meter_parse_vmstat (const char * buf, uint64_t * pgmajfault)
Definition at line 199 of file meter.c.
References meter_find_counter().
Referenced by brix_cms_meter_sample(), and test_vmstat().
brix_cms_meter_rate_pct()
uint8_t brix_cms_meter_rate_pct (uint64_t delta, uint64_t elapsed_ms, uint64_t ref_per_sec)
Definition at line 209 of file meter.c.
References meter_clamp_pct().
Referenced by meter_fold_deltas(), and test_rate_pct().
brix_cms_meter_sample()
void brix_cms_meter_sample (brix_cms_meter_t * m, uint64_t now_ms, uint8_t out5[5])
Definition at line 306 of file meter.c.
References brix_cms_meter_parse_netdev(), brix_cms_meter_parse_vmstat(), meter_fold_deltas(), meter_sample_gauges(), and meter_slurp().
Referenced by cms_srv_frame_usage(), ngx_brix_cms_send_load(), and test_sample_live().
meter_clamp_pct()
static uint8_t meter_clamp_pct (unsigned long v) static
Definition at line 28 of file meter.c.
Referenced by brix_cms_meter_parse_loadavg(), brix_cms_meter_parse_meminfo(), and brix_cms_meter_rate_pct().
meter_find_counter()
static int meter_find_counter (const char * buf, const char * key, uint64_t * out) static
Definition at line 57 of file meter.c.
References key.
Referenced by brix_cms_meter_parse_meminfo(), and brix_cms_meter_parse_vmstat().
meter_fold_deltas()
static void meter_fold_deltas (brix_cms_meter_t * m, uint64_t now_ms, int have_net, uint64_t net_bytes, int have_pag, uint64_t pgmaj, uint8_t out5[5]) static
Definition at line 273 of file meter.c.
References BRIX_CMS_METER_NET_REF_BYTES_PER_SEC, BRIX_CMS_METER_PAG_REF_FAULTS_PER_SEC, brix_cms_meter_rate_pct(), brix_cms_meter_t::prev_ms, brix_cms_meter_t::prev_net_bytes, brix_cms_meter_t::prev_pgmajfault, and brix_cms_meter_t::primed.
Referenced by brix_cms_meter_sample().
meter_netdev_line_bytes()
static int meter_netdev_line_bytes (const char * colon, uint64_t * bytes) static
Definition at line 109 of file meter.c.
Referenced by brix_cms_meter_parse_netdev().
meter_sample_gauges()
static void meter_sample_gauges (uint8_t out5[5]) static
Definition at line 248 of file meter.c.
References brix_cms_meter_parse_loadavg(), brix_cms_meter_parse_meminfo(), and meter_slurp().
Referenced by brix_cms_meter_sample().
meter_slurp()
static int meter_slurp (const char * path, char * buf, size_t bufsz) static
Definition at line 226 of file meter.c.
Referenced by brix_cms_meter_sample(), and meter_sample_gauges().