nginx-xrootd: src/protocols/webdav/methods_proppatch.c File Reference
methods_proppatch.c File Reference
#include "webdav.h"
#include "fs/vfs/vfs.h"
#include "auth/impersonate/lifecycle.h"
#include "core/http/etag.h"
#include "core/http/http_body.h"
#include "core/http/http_file_response.h"
#include "core/http/http_xml.h"
#include <libxml/parser.h>
#include <libxml/tree.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include "core/compat/alloc_guard.h"
Data Structures
struct webdav_proppatch_walk_t
Macros
#define WEBDAV_PROPPATCH_BODY_MAX 65536u
Functions
static char * webdav_proppatch_serialize_dead_prop (ngx_http_request_t *r, xmlNodePtr prop, size_t *out_len)
static ngx_int_t webdav_proppatch_append_propstat (webdav_proppatch_walk_t *w, const char *ns, const char *local, const char *status)
static const char * webdav_proppatch_prop_status (webdav_proppatch_walk_t *w, xmlNodePtr prop, const char *ns, const char *local, ngx_flag_t is_set)
static ngx_int_t webdav_proppatch_process_action (webdav_proppatch_walk_t *w, xmlNodePtr action, ngx_flag_t is_set, ngx_uint_t *processed)
static ngx_int_t webdav_proppatch_start_multistatus (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail)
static ngx_int_t webdav_proppatch_finish_multistatus (ngx_http_request_t *r, ngx_chain_t *head, ngx_chain_t *tail)
static ngx_int_t webdav_proppatch_parse_body (ngx_http_request_t *r, xmlDocPtr *doc, xmlNodePtr *root)
static ngx_int_t webdav_proppatch_do (ngx_http_request_t *r)
static void webdav_proppatch_body_handler (ngx_http_request_t *r)
ngx_int_t webdav_handle_proppatch (ngx_http_request_t *r)
Macro Definition Documentation
WEBDAV_PROPPATCH_BODY_MAX
#define WEBDAV_PROPPATCH_BODY_MAX 65536u
Definition at line 29 of file methods_proppatch.c.
Function Documentation
webdav_handle_proppatch()
ngx_int_t webdav_handle_proppatch (ngx_http_request_t * r)
Definition at line 496 of file methods_proppatch.c.
References brix_http_read_body(), and webdav_proppatch_body_handler().
Referenced by webdav_dispatch_lock_patch_search().
webdav_proppatch_append_propstat()
static ngx_int_t webdav_proppatch_append_propstat (webdav_proppatch_walk_t * w, const char * ns, const char * local, const char * status) static
Definition at line 112 of file methods_proppatch.c.
References brix_http_chain_appendf(), webdav_proppatch_walk_t::head, webdav_proppatch_walk_t::r, webdav_proppatch_walk_t::tail, and webdav_dead_prop_append_empty().
Referenced by webdav_proppatch_process_action().
webdav_proppatch_body_handler()
static void webdav_proppatch_body_handler (ngx_http_request_t * r) static
Definition at line 476 of file methods_proppatch.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, webdav_metrics_finalize_request(), and webdav_proppatch_do().
Referenced by webdav_handle_proppatch().
webdav_proppatch_do()
static ngx_int_t webdav_proppatch_do (ngx_http_request_t * r) static
Definition at line 398 of file methods_proppatch.c.
References webdav_proppatch_walk_t::head, webdav_proppatch_walk_t::path, stat(), webdav_proppatch_walk_t::tail, webdav_check_locks(), WEBDAV_MAX_PATH, webdav_proppatch_finish_multistatus(), webdav_proppatch_parse_body(), webdav_proppatch_process_action(), webdav_proppatch_start_multistatus(), and webdav_resolve_stat().
Referenced by webdav_proppatch_body_handler().
webdav_proppatch_finish_multistatus()
static ngx_int_t webdav_proppatch_finish_multistatus (ngx_http_request_t * r, ngx_chain_t * head, ngx_chain_t * tail) static
Definition at line 298 of file methods_proppatch.c.
References brix_http_chain_appendf().
Referenced by webdav_proppatch_do().
webdav_proppatch_parse_body()
static ngx_int_t webdav_proppatch_parse_body (ngx_http_request_t * r, xmlDocPtr * doc, xmlNodePtr * root) static
Definition at line 354 of file methods_proppatch.c.
References brix_http_body_read_all(), and WEBDAV_PROPPATCH_BODY_MAX.
Referenced by webdav_proppatch_do().
webdav_proppatch_process_action()
static ngx_int_t webdav_proppatch_process_action (webdav_proppatch_walk_t * w, xmlNodePtr action, ngx_flag_t is_set, ngx_uint_t * processed) static
Definition at line 196 of file methods_proppatch.c.
References webdav_proppatch_append_propstat(), and webdav_proppatch_prop_status().
Referenced by webdav_proppatch_do().
webdav_proppatch_prop_status()
static const char * webdav_proppatch_prop_status (webdav_proppatch_walk_t * w, xmlNodePtr prop, const char * ns, const char * local, ngx_flag_t is_set) static
Definition at line 152 of file methods_proppatch.c.
References webdav_proppatch_walk_t::path, webdav_proppatch_walk_t::r, webdav_dead_prop_is_protected_dav(), webdav_dead_prop_remove(), webdav_dead_prop_set(), and webdav_proppatch_serialize_dead_prop().
Referenced by webdav_proppatch_process_action().
webdav_proppatch_serialize_dead_prop()
static char * webdav_proppatch_serialize_dead_prop (ngx_http_request_t * r, xmlNodePtr prop, size_t * out_len) static
Definition at line 56 of file methods_proppatch.c.
References BRIX_PNALLOC_OR_RETURN, and webdav_escape_xml_text().
Referenced by webdav_proppatch_prop_status().
webdav_proppatch_start_multistatus()
static ngx_int_t webdav_proppatch_start_multistatus (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail) static
Definition at line 255 of file methods_proppatch.c.
References brix_http_chain_appendf(), ngx_memcpy, webdav_escape_xml_text(), and WEBDAV_MAX_PATH.
Referenced by webdav_proppatch_do().