nginx-xrootd: src/protocols/webdav/methods_basic.c File Reference
methods_basic.c File Reference
#include "webdav.h"
#include "fs/vfs/vfs.h"
#include "auth/impersonate/lifecycle.h"
#include "core/http/etag.h"
#include "core/http/http_body.h"
#include "core/http/http_file_response.h"
#include "core/http/http_xml.h"
#include <libxml/parser.h>
#include <libxml/tree.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include "core/compat/alloc_guard.h"
Macros
#define WEBDAV_PROPPATCH_BODY_MAX 65536u
Functions
ngx_int_t webdav_handle_options (ngx_http_request_t *r)
ngx_int_t webdav_handle_head (ngx_http_request_t *r, int send_body)
static char * webdav_proppatch_serialize_dead_prop (ngx_http_request_t *r, xmlNodePtr prop, size_t *out_len)
static ngx_int_t webdav_proppatch_append_propstat (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, const char *ns, const char *local, const char *status)
static ngx_int_t webdav_proppatch_do (ngx_http_request_t *r)
static void webdav_proppatch_body_handler (ngx_http_request_t *r)
ngx_int_t webdav_handle_proppatch (ngx_http_request_t *r)
Macro Definition Documentation
WEBDAV_PROPPATCH_BODY_MAX
#define WEBDAV_PROPPATCH_BODY_MAX 65536u
Definition at line 29 of file methods_basic.c.
Function Documentation
webdav_handle_head()
ngx_int_t webdav_handle_head (ngx_http_request_t * r, int send_body)
Definition at line 99 of file methods_basic.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_ETAG_WEAK, brix_http_add_etag_header(), BRIX_PROTO_WEBDAV, brix_vfs_close(), brix_vfs_ctx_init(), brix_vfs_file_fd(), BRIX_VFS_O_READ, brix_vfs_open(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, brix_vfs_ctx_t::pool, ngx_http_brix_shared_conf_t::root_canon, stat(), xrdhttp_req_ctx_t::want_cksum, WEBDAV_MAX_PATH, webdav_resolve_stat(), xrdhttp_add_checksum_header(), and xrdhttp_get_ctx().
Referenced by webdav_dispatch_inner().
webdav_handle_options()
ngx_int_t webdav_handle_options (ngx_http_request_t * r)
Definition at line 39 of file methods_basic.c.
References brix_http_operation_allow_header(), BRIX_WEBDAV_ALLOW_FLAGS, brix_webdav_operations, brix_webdav_operations_count, and ngx_http_brix_webdav_module.
Referenced by webdav_dispatch_inner().
webdav_handle_proppatch()
ngx_int_t webdav_handle_proppatch (ngx_http_request_t * r)
Definition at line 505 of file methods_basic.c.
References brix_http_read_body(), and webdav_proppatch_body_handler().
Referenced by webdav_dispatch_inner().
webdav_proppatch_append_propstat()
static ngx_int_t webdav_proppatch_append_propstat (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, const char * ns, const char * local, const char * status) static
Definition at line 244 of file methods_basic.c.
References brix_http_chain_appendf(), and webdav_dead_prop_append_empty().
Referenced by webdav_proppatch_do().
webdav_proppatch_body_handler()
static void webdav_proppatch_body_handler (ngx_http_request_t * r) static
Definition at line 485 of file methods_basic.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, webdav_metrics_finalize_request(), and webdav_proppatch_do().
Referenced by webdav_handle_proppatch().
webdav_proppatch_do()
static ngx_int_t webdav_proppatch_do (ngx_http_request_t * r) static
Definition at line 276 of file methods_basic.c.
References brix_http_body_read_all(), brix_http_chain_appendf(), ngx_memcpy, stat(), webdav_check_locks(), webdav_dead_prop_is_protected_dav(), webdav_dead_prop_remove(), webdav_dead_prop_set(), webdav_escape_xml_text(), WEBDAV_MAX_PATH, webdav_proppatch_append_propstat(), WEBDAV_PROPPATCH_BODY_MAX, webdav_proppatch_serialize_dead_prop(), and webdav_resolve_stat().
Referenced by webdav_proppatch_body_handler().
webdav_proppatch_serialize_dead_prop()
static char * webdav_proppatch_serialize_dead_prop (ngx_http_request_t * r, xmlNodePtr prop, size_t * out_len) static
Definition at line 188 of file methods_basic.c.
References BRIX_PNALLOC_OR_RETURN, and webdav_escape_xml_text().
Referenced by webdav_proppatch_do().