nginx-xrootd: src/observability/metrics/metrics_macros.h File Reference
metrics_macros.h File Reference
Macros
#define BRIX_ATOMIC_INC(counter)
#define BRIX_ATOMIC_DEC(counter)
#define BRIX_ATOMIC_ADD(counter, amount)
#define BRIX_SRV_METRIC_INC(ctx, field)
#define BRIX_SRV_METRIC_ADD(ctx, field, amount)
#define BRIX_WEBDAV_METRIC_INC(field)
#define BRIX_WEBDAV_METRIC_ADD(field, amount)
#define BRIX_S3_METRIC_INC(field)
#define BRIX_CVMFS_METRIC_INC(field)
#define BRIX_CVMFS_METRIC_ADD(field, amount)
#define BRIX_PMARK_METRIC_INC(field)
#define BRIX_S3_METRIC_ADD(field, amount)
#define BRIX_RESIL_METRIC_INC(field)
#define BRIX_FRM_METRIC_INC(field)
#define BRIX_FRM_METRIC_DEC(field)
#define BRIX_FRM_METRIC_ADD(field, amount)
#define BRIX_PROXY_METRIC_INC(ctx, field)
#define BRIX_PROXY_METRIC_ADD(ctx, field, amount)
#define BRIX_PROXY_UP_INC(proxy_ptr, field)
#define BRIX_PROXY_UP_ADD(proxy_ptr, field, amount)
Functions
static ngx_brix_metrics_t * brix_metrics_shared (void)
Macro Definition Documentation
BRIX_ATOMIC_ADD
#define BRIX_ATOMIC_ADD (counter, amount)
Value:
    do {                                                                     \
        size_t _brix_metric_amount = (size_t) (amount);                    \
        if (_brix_metric_amount > 0) {                                     \
            ngx_atomic_fetch_add((counter), _brix_metric_amount);          \
        }                                                                    \
    } while (0)
Definition at line 50 of file metrics_macros.h.
BRIX_ATOMIC_DEC
#define BRIX_ATOMIC_DEC (counter)
Value:
    do {                                                                     \
        ngx_atomic_fetch_add((counter), (ngx_atomic_int_t) -1);              \
    } while (0)
Definition at line 45 of file metrics_macros.h.
BRIX_ATOMIC_INC
#define BRIX_ATOMIC_INC (counter)
Value:
    do {                                                                     \
        ngx_atomic_fetch_add((counter), 1);                                  \
    } while (0)
Definition at line 40 of file metrics_macros.h.
BRIX_CVMFS_METRIC_ADD
#define BRIX_CVMFS_METRIC_ADD (field, amount)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_brix_metrics = brix_metrics_shared();     \
        if (_brix_metrics != NULL) {                                       \
            BRIX_ATOMIC_ADD(&_brix_metrics->cvmfs.field, (amount));      \
        }                                                                    \
    } while (0)
Definition at line 104 of file metrics_macros.h.
BRIX_CVMFS_METRIC_INC
#define BRIX_CVMFS_METRIC_INC (field)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_brix_metrics = brix_metrics_shared();     \
        if (_brix_metrics != NULL) {                                       \
            BRIX_ATOMIC_INC(&_brix_metrics->cvmfs.field);                \
        }                                                                    \
    } while (0)
Definition at line 96 of file metrics_macros.h.
BRIX_FRM_METRIC_ADD
#define BRIX_FRM_METRIC_ADD (field, amount)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_brix_metrics = brix_metrics_shared();     \
        if (_brix_metrics != NULL) {                                       \
            BRIX_ATOMIC_ADD(&_brix_metrics->frm.field, (amount));        \
        }                                                                    \
    } while (0)
Definition at line 161 of file metrics_macros.h.
BRIX_FRM_METRIC_DEC
#define BRIX_FRM_METRIC_DEC (field)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_brix_metrics = brix_metrics_shared();     \
        if (_brix_metrics != NULL) {                                       \
            BRIX_ATOMIC_DEC(&_brix_metrics->frm.field);                  \
        }                                                                    \
    } while (0)
Definition at line 153 of file metrics_macros.h.
BRIX_FRM_METRIC_INC
#define BRIX_FRM_METRIC_INC (field)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_brix_metrics = brix_metrics_shared();     \
        if (_brix_metrics != NULL) {                                       \
            BRIX_ATOMIC_INC(&_brix_metrics->frm.field);                  \
        }                                                                    \
    } while (0)
Definition at line 145 of file metrics_macros.h.
BRIX_PMARK_METRIC_INC
#define BRIX_PMARK_METRIC_INC (field)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_brix_metrics = brix_metrics_shared();     \
        if (_brix_metrics != NULL) {                                       \
            BRIX_ATOMIC_INC(&_brix_metrics->field);                      \
        }                                                                    \
    } while (0)
Definition at line 115 of file metrics_macros.h.
BRIX_PROXY_METRIC_ADD
#define BRIX_PROXY_METRIC_ADD (ctx, field, amount)
Value:
    do {                                                                     \
        if ((ctx) != NULL && (ctx)->metrics != NULL) {                       \
            BRIX_ATOMIC_ADD(&(ctx)->metrics->proxy.field, (amount));       \
        }                                                                    \
    } while (0)
Definition at line 177 of file metrics_macros.h.
BRIX_PROXY_METRIC_INC
#define BRIX_PROXY_METRIC_INC (ctx, field)
Value:
    do {                                                                     \
        if ((ctx) != NULL && (ctx)->metrics != NULL) {                       \
            BRIX_ATOMIC_INC(&(ctx)->metrics->proxy.field);                 \
        }                                                                    \
    } while (0)
Definition at line 170 of file metrics_macros.h.
BRIX_PROXY_UP_ADD
#define BRIX_PROXY_UP_ADD (proxy_ptr, field, amount)
Value:
    do {                                                                     \
        int _ui = (proxy_ptr)->upstream_idx;                                 \
        if (_ui >= 0 && _ui < BRIX_PROXY_MAX_UPSTREAMS                    \
            && (proxy_ptr)->client_ctx != NULL                               \
            && (proxy_ptr)->client_ctx->metrics != NULL)                     \
        {                                                                    \
            BRIX_ATOMIC_ADD(                                               \
                &(proxy_ptr)->client_ctx->metrics->proxy.upstreams[_ui].field, \
                (amount));                                                   \
        }                                                                    \
    } while (0)
Definition at line 201 of file metrics_macros.h.
BRIX_PROXY_UP_INC
#define BRIX_PROXY_UP_INC (proxy_ptr, field)
Value:
    do {                                                                     \
        int _ui = (proxy_ptr)->upstream_idx;                                 \
        if (_ui >= 0 && _ui < BRIX_PROXY_MAX_UPSTREAMS                    \
            && (proxy_ptr)->client_ctx != NULL                               \
            && (proxy_ptr)->client_ctx->metrics != NULL)                     \
        {                                                                    \
            BRIX_ATOMIC_INC(                                               \
                &(proxy_ptr)->client_ctx->metrics->proxy.upstreams[_ui].field); \
        }                                                                    \
    } while (0)
Definition at line 189 of file metrics_macros.h.
BRIX_RESIL_METRIC_INC
#define BRIX_RESIL_METRIC_INC (field)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_brix_metrics = brix_metrics_shared();     \
        if (_brix_metrics != NULL) {                                       \
            BRIX_ATOMIC_INC(&_brix_metrics->field);                      \
        }                                                                    \
    } while (0)
Definition at line 134 of file metrics_macros.h.
BRIX_S3_METRIC_ADD
#define BRIX_S3_METRIC_ADD (field, amount)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_brix_metrics = brix_metrics_shared();     \
        if (_brix_metrics != NULL) {                                       \
            BRIX_ATOMIC_ADD(&_brix_metrics->s3.field, (amount));         \
        }                                                                    \
    } while (0)
Definition at line 123 of file metrics_macros.h.
BRIX_S3_METRIC_INC
#define BRIX_S3_METRIC_INC (field)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_brix_metrics = brix_metrics_shared();     \
        if (_brix_metrics != NULL) {                                       \
            BRIX_ATOMIC_INC(&_brix_metrics->s3.field);                   \
        }                                                                    \
    } while (0)
Definition at line 88 of file metrics_macros.h.
BRIX_SRV_METRIC_ADD
#define BRIX_SRV_METRIC_ADD (ctx, field, amount)
Value:
    do {                                                                     \
        if ((ctx) != NULL && (ctx)->metrics != NULL) {                       \
            BRIX_ATOMIC_ADD(&(ctx)->metrics->field, (amount));             \
        }                                                                    \
    } while (0)
Definition at line 65 of file metrics_macros.h.
BRIX_SRV_METRIC_INC
#define BRIX_SRV_METRIC_INC (ctx, field)
Value:
    do {                                                                     \
        if ((ctx) != NULL && (ctx)->metrics != NULL) {                       \
            BRIX_ATOMIC_INC(&(ctx)->metrics->field);                       \
        }                                                                    \
    } while (0)
Definition at line 58 of file metrics_macros.h.
BRIX_WEBDAV_METRIC_ADD
#define BRIX_WEBDAV_METRIC_ADD (field, amount)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_brix_metrics = brix_metrics_shared();     \
        if (_brix_metrics != NULL) {                                       \
            BRIX_ATOMIC_ADD(&_brix_metrics->webdav.field, (amount));     \
        }                                                                    \
    } while (0)
Definition at line 80 of file metrics_macros.h.
BRIX_WEBDAV_METRIC_INC
#define BRIX_WEBDAV_METRIC_INC (field)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_brix_metrics = brix_metrics_shared();     \
        if (_brix_metrics != NULL) {                                       \
            BRIX_ATOMIC_INC(&_brix_metrics->webdav.field);               \
        }                                                                    \
    } while (0)
Definition at line 72 of file metrics_macros.h.
Function Documentation
brix_metrics_shared()
static ngx_brix_metrics_t * brix_metrics_shared (void) inline static
Definition at line 28 of file metrics_macros.h.
References ngx_brix_shm_zone.
Referenced by brix_cvmfs_repo_slot(), brix_export_cluster_metrics(), brix_gsi_complete_auth(), brix_metric_auth(), brix_metric_backend_bytes(), brix_metric_cache_result(), brix_metric_cache_usage_ratio(), brix_metric_cache_watermark_purge(), brix_metric_cred_result(), brix_metric_op_done(), brix_metric_tpc(), brix_metric_wt_stage_throttled(), brix_metric_wt_stage_usage_ratio(), brix_session_finish_eviction(), brix_session_reap_lru(), brix_srv_register(), brix_storage_io_bytes_emit(), brix_unix_track_identity(), build_stats_xml(), cvmfs_upstream_slot(), sss_track_metrics(), and tokenauth_bind_session().