nginx-xrootd: src/observability/metrics/metrics_cvmfs.h File Reference
metrics_cvmfs.h File Reference
#include <ngx_core.h>
Data Structures
struct ngx_brix_cvmfs_repo_metrics_t
struct ngx_brix_cvmfs_upstream_metrics_t
struct ngx_brix_cvmfs_metrics_t
Macros
#define BRIX_CVMFS_REPO_SLOTS 32
#define BRIX_CVMFS_REPO_NAME_MAX 64
#define BRIX_CVMFS_REPO_EMPTY 0u
#define BRIX_CVMFS_REPO_CLAIMED 1u
#define BRIX_CVMFS_REPO_READY 2u
#define BRIX_CVMFS_UPSTREAM_SLOTS 16 /* >= a site's Stratum-1 allowlist */
#define BRIX_CVMFS_UPSTREAM_NAME_MAX 300 /* matches sd_http last_origin buf */
#define BRIX_CVMFS_UP_HBUCKETS 6
Enumerations
enum brix_cvmfs_class_metric_e {
BRIX_CVMFS_CLASS_CAS = 0 , BRIX_CVMFS_CLASS_MANIFEST , BRIX_CVMFS_CLASS_GEO , BRIX_CVMFS_CLASS_REJECT ,
BRIX_CVMFS_CLASS_COUNT
}
Functions
ngx_brix_cvmfs_repo_metrics_t * brix_cvmfs_repo_slot (const char *name, size_t len)
void brix_cvmfs_upstream_record (const char *host, int ok, off_t bytes, long dur_ms, int failover)
Variables
static const long brix_cvmfs_up_bucket_ms [6]
Macro Definition Documentation
BRIX_CVMFS_REPO_CLAIMED
#define BRIX_CVMFS_REPO_CLAIMED 1u
Definition at line 45 of file metrics_cvmfs.h.
BRIX_CVMFS_REPO_EMPTY
#define BRIX_CVMFS_REPO_EMPTY 0u
Definition at line 44 of file metrics_cvmfs.h.
BRIX_CVMFS_REPO_NAME_MAX
#define BRIX_CVMFS_REPO_NAME_MAX 64
Definition at line 42 of file metrics_cvmfs.h.
BRIX_CVMFS_REPO_READY
#define BRIX_CVMFS_REPO_READY 2u
Definition at line 46 of file metrics_cvmfs.h.
BRIX_CVMFS_REPO_SLOTS
#define BRIX_CVMFS_REPO_SLOTS 32
Definition at line 41 of file metrics_cvmfs.h.
BRIX_CVMFS_UP_HBUCKETS
#define BRIX_CVMFS_UP_HBUCKETS 6
Definition at line 80 of file metrics_cvmfs.h.
BRIX_CVMFS_UPSTREAM_NAME_MAX
#define BRIX_CVMFS_UPSTREAM_NAME_MAX 300 /* matches sd_http last_origin buf */
Definition at line 74 of file metrics_cvmfs.h.
BRIX_CVMFS_UPSTREAM_SLOTS
#define BRIX_CVMFS_UPSTREAM_SLOTS 16 /* >= a site's Stratum-1 allowlist */
Definition at line 73 of file metrics_cvmfs.h.
Enumeration Type Documentation
brix_cvmfs_class_metric_e
enum brix_cvmfs_class_metric_e
Enumerator
BRIX_CVMFS_CLASS_CAS
BRIX_CVMFS_CLASS_MANIFEST
BRIX_CVMFS_CLASS_GEO
BRIX_CVMFS_CLASS_REJECT
BRIX_CVMFS_CLASS_COUNT
Definition at line 22 of file metrics_cvmfs.h.
Function Documentation
brix_cvmfs_repo_slot()
ngx_brix_cvmfs_repo_metrics_t * brix_cvmfs_repo_slot (const char * name, size_t len)
Definition at line 35 of file cvmfs.c.
References BRIX_CVMFS_REPO_CLAIMED, BRIX_CVMFS_REPO_EMPTY, BRIX_CVMFS_REPO_NAME_MAX, BRIX_CVMFS_REPO_READY, BRIX_CVMFS_REPO_SLOTS, brix_metrics_shared(), ngx_brix_metrics_t::cvmfs, cvmfs_repo_slot_is(), ngx_brix_cvmfs_repo_metrics_t::name, name, ngx_brix_cvmfs_metrics_t::repos, and ngx_brix_cvmfs_repo_metrics_t::state.
Referenced by brix_cvmfs_gate(), and sd_cache_repo_metrics().
brix_cvmfs_upstream_record()
void brix_cvmfs_upstream_record (const char * host, int ok, off_t bytes, long dur_ms, int failover)
Definition at line 180 of file cvmfs.c.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, brix_cvmfs_up_bucket_ms, BRIX_CVMFS_UP_HBUCKETS, ngx_brix_cvmfs_upstream_metrics_t::dur_bucket, ngx_brix_cvmfs_upstream_metrics_t::dur_count, ngx_brix_cvmfs_upstream_metrics_t::dur_sum_ms, ngx_brix_cvmfs_upstream_metrics_t::failovers_total, ngx_brix_cvmfs_upstream_metrics_t::fill_failures_total, ngx_brix_cvmfs_upstream_metrics_t::fills_total, host, ngx_brix_cvmfs_upstream_metrics_t::origin_bytes_total, and ngx_brix_cvmfs_upstream_metrics_t::requests_total.
Referenced by sd_cache_note_upstream().
Variable Documentation
brix_cvmfs_up_bucket_ms
const long brix_cvmfs_up_bucket_ms[6] static
Initial value:
= {
    5, 25, 100, 500, 2000, 10000
}
Definition at line 81 of file metrics_cvmfs.h.
Referenced by brix_cvmfs_upstream_record(), and cvmfs_export_upstreams().