nginx-xrootd: src/observability/metrics/access_log.h File Reference
access_log.h File Reference
#include "fs/vfs/vfs.h"
#include "unified.h"
Functions
void brix_access_log_emit (const brix_vfs_ctx_t *ctx, const char *path, brix_metric_op_t op, const brix_vfs_io_result_t *result, size_t bytes, brix_err_class_t err, ngx_msec_t latency_usec)
Function Documentation
brix_access_log_emit()
void brix_access_log_emit (const brix_vfs_ctx_t * ctx, const char * path, brix_metric_op_t op, const brix_vfs_io_result_t * result, size_t bytes, brix_err_class_t err, ngx_msec_t latency_usec)
Definition at line 89 of file access_log.c.
References brix_identity_t::auth_method, brix_access_json_escape(), brix_identity_dn_cstr(), brix_identity_subject_cstr(), brix_metric_auth_method_name(), brix_metric_err_name(), brix_metric_op_name(), brix_metric_proto_name(), brix_vfs_io_result_t::from_cache, brix_vfs_ctx_t::identity, brix_vfs_ctx_t::log, brix_vfs_ctx_t::metrics_proto, brix_vfs_io_result_t::offset, and op.
Referenced by brix_vfs_observe_ctx_op().