nginx-xrootd: src/observability/metrics/metrics_internal.h File Reference
metrics_internal.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include "metrics.h"
Data Structures
struct ngx_http_brix_metrics_loc_conf_t
struct metrics_writer_t
Macros
#define METRICS_BUF_SIZE 65536
Functions
ngx_int_t mw_init (metrics_writer_t *mw, ngx_pool_t *pool)
ngx_int_t mw_printf (metrics_writer_t *mw, const char *fmt,...)
void mw_emit_labeled (metrics_writer_t *mw, const char *name, const char *help, const char *label_key, const char *const *names, ngx_uint_t n, ngx_atomic_t *counters)
void mw_emit_scalar (metrics_writer_t *mw, const char *name, const char *help, ngx_atomic_t *counter)
void brix_kv_metrics_emit (metrics_writer_t *mw)
void brix_storage_backend_metrics_emit (metrics_writer_t *mw)
void mw_finish (metrics_writer_t *mw)
void brix_export_prometheus_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void brix_export_stream_cache_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void brix_export_stream_proxy_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void brix_export_stream_tracking_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void brix_export_unified_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void brix_export_cvmfs_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void brix_export_webdav_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void brix_export_s3_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void brix_export_pmark_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void brix_export_resilience_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void brix_export_frm_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void brix_export_cluster_metrics (metrics_writer_t *mw)
void brix_export_ratelimit_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
ngx_int_t ngx_http_brix_metrics_handler (ngx_http_request_t *r)
ngx_int_t ngx_http_brix_health_handler (ngx_http_request_t *r)
ngx_int_t brix_track_vo_activity (ngx_brix_metrics_t *shm, const char *vo_name, size_t bytes_tx, size_t bytes_rx)
ngx_int_t brix_track_unique_user (ngx_brix_metrics_t *shm, const char *identity, size_t identity_len)
Variables
ngx_module_t ngx_http_brix_metrics_module
const char * brix_http_status_names [6]
const char * brix_http_range_result_names [3]
Macro Definition Documentation
METRICS_BUF_SIZE
#define METRICS_BUF_SIZE 65536
Definition at line 39 of file metrics_internal.h.
Function Documentation
brix_export_cluster_metrics()
void brix_export_cluster_metrics (metrics_writer_t * mw)
Definition at line 30 of file cluster.c.
References brix_srv_snapshot_entry_t::blacklisted_until, brix_metrics_shared(), BRIX_SRV_REGISTRY_SLOTS, brix_srv_shm_zone, brix_srv_snapshot(), CLUSTER_LABEL, ngx_brix_metrics_t::hc_blacklist_total, ngx_brix_metrics_t::hc_fail_total, ngx_brix_metrics_t::hc_pass_total, ngx_brix_metrics_t::hc_probes_total, brix_srv_snapshot_entry_t::last_seen, and mw_printf().
Referenced by brix_export_prometheus_metrics().
brix_export_cvmfs_metrics()
void brix_export_cvmfs_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 305 of file cvmfs.c.
References BRIX_CVMFS_CLASS_COUNT, brix_cvmfs_class_names, BRIX_CVMFS_REPO_READY, BRIX_CVMFS_REPO_SLOTS, ngx_brix_cvmfs_repo_metrics_t::bytes_served_fill_total, ngx_brix_cvmfs_repo_metrics_t::bytes_served_hit_total, c, cls(), ngx_brix_metrics_t::cvmfs, cvmfs_export_upstreams(), cvmfs_repo_slot_is_dup(), mw_emit_labeled(), mw_emit_scalar(), mw_printf(), ngx_brix_cvmfs_repo_metrics_t::name, name, ngx_brix_cvmfs_repo_metrics_t::requests_total, and ngx_brix_cvmfs_repo_metrics_t::state.
Referenced by brix_export_prometheus_metrics().
brix_export_frm_metrics()
void brix_export_frm_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 43 of file frm_metrics.c.
References ngx_brix_frm_metrics_t::asynresp_total, brix_frm_fail_names, brix_frm_latency_bounds, BRIX_FRM_LATENCY_BUCKETS, BRIX_FRM_NFAIL, ngx_brix_frm_metrics_t::cmsd_have_total, ngx_brix_frm_metrics_t::dedup_hits_total, ngx_brix_frm_metrics_t::evict_total, ngx_brix_metrics_t::frm, ngx_brix_frm_metrics_t::in_flight, ngx_brix_frm_metrics_t::migrate_total, mw_emit_labeled(), mw_emit_scalar(), mw_printf(), ngx_brix_frm_metrics_t::purge_total, ngx_brix_frm_metrics_t::reject_inflight_total, ngx_brix_frm_metrics_t::requests_total, ngx_brix_frm_metrics_t::stage_fail_total, ngx_brix_frm_metrics_t::stage_latency_bucket, ngx_brix_frm_metrics_t::stage_latency_count, ngx_brix_frm_metrics_t::stage_latency_sum_sec, ngx_brix_frm_metrics_t::stage_success_total, and ngx_brix_frm_metrics_t::waitresp_total.
Referenced by brix_export_prometheus_metrics().
brix_export_pmark_metrics()
void brix_export_pmark_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 252 of file stream.c.
References mw_emit_scalar(), ngx_brix_metrics_t::pmark_firefly_dropped_total, ngx_brix_metrics_t::pmark_firefly_sent_total, ngx_brix_metrics_t::pmark_flowlabel_failed_total, ngx_brix_metrics_t::pmark_flowlabel_set_total, ngx_brix_metrics_t::pmark_flows_ended_total, ngx_brix_metrics_t::pmark_flows_started_total, and ngx_brix_metrics_t::pmark_map_unresolved_total.
Referenced by brix_export_prometheus_metrics().
brix_export_prometheus_metrics()
void brix_export_prometheus_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 204 of file stream.c.
References brix_export_cluster_metrics(), brix_export_cvmfs_metrics(), brix_export_frm_metrics(), brix_export_pmark_metrics(), brix_export_ratelimit_metrics(), brix_export_resilience_metrics(), brix_export_s3_metrics(), brix_export_stream_cache_metrics(), brix_export_stream_proxy_metrics(), brix_export_stream_tracking_metrics(), brix_export_unified_metrics(), brix_export_webdav_metrics(), metrics_emit_bytes(), metrics_emit_config_generation(), metrics_emit_connections(), metrics_emit_fault_timeouts(), metrics_emit_io_uring(), metrics_emit_mirror(), metrics_emit_path_depth(), metrics_emit_registry_health(), metrics_emit_request_ops(), metrics_emit_ssi(), metrics_emit_wire_frames(), and metrics_emit_xfer_heap().
Referenced by ngx_http_brix_metrics_handler().
brix_export_ratelimit_metrics()
void brix_export_ratelimit_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 12 of file ratelimit.c.
References mw_printf(), ngx_brix_metrics_t::rl_eviction_total, ngx_brix_metrics_t::rl_throttled_http_total, ngx_brix_metrics_t::rl_throttled_stream_total, and ngx_brix_metrics_t::rl_zone_full_errors.
Referenced by brix_export_prometheus_metrics().
brix_export_resilience_metrics()
void brix_export_resilience_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 281 of file stream.c.
References ngx_brix_metrics_t::acc_dns_breaker_open_total, ngx_brix_metrics_t::acc_nss_breaker_open_total, ngx_brix_metrics_t::auth_l1_hits_total, ngx_brix_metrics_t::auth_l1_misses_total, ngx_brix_metrics_t::cms_cap_rejections_total, ngx_brix_metrics_t::cms_frame_yields_total, ngx_brix_metrics_t::cms_idle_closes_total, ngx_brix_metrics_t::cms_login_timeouts_total, ngx_brix_metrics_t::cms_read_timeouts_total, mw_emit_scalar(), and ngx_brix_metrics_t::ocsp_timeouts_total.
Referenced by brix_export_prometheus_metrics().
brix_export_s3_metrics()
void brix_export_s3_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 73 of file s3.c.
References ngx_brix_s3_metrics_t::auth_total, BRIX_HTTP_NSTATUS, brix_http_range_result_names, brix_http_status_names, brix_s3_auth_names, brix_s3_event_names, brix_s3_method_names, BRIX_S3_NAUTH_RESULTS, BRIX_S3_NEVENTS, BRIX_S3_NMETHODS, BRIX_S3_NPUT_MODES, BRIX_S3_NRANGE_RESULTS, brix_s3_put_names, ngx_brix_s3_metrics_t::bytes_rx_ipv4_total, ngx_brix_s3_metrics_t::bytes_rx_total, ngx_brix_s3_metrics_t::bytes_tx_ipv4_total, ngx_brix_s3_metrics_t::bytes_tx_total, ngx_brix_s3_metrics_t::events_total, ngx_brix_s3_metrics_t::list_common_prefixes_total, ngx_brix_s3_metrics_t::list_contents_total, ngx_brix_s3_metrics_t::list_truncated_total, mw_emit_labeled(), mw_emit_scalar(), mw_printf(), ngx_brix_s3_metrics_t::put_body_total, ngx_brix_s3_metrics_t::range_total, ngx_brix_s3_metrics_t::requests_total, ngx_brix_s3_metrics_t::responses_total, and ngx_brix_metrics_t::s3.
Referenced by brix_export_prometheus_metrics().
brix_export_stream_cache_metrics()
void brix_export_stream_cache_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 401 of file stream_cache.c.
References stream_cache_emit_cache_bytes(), stream_cache_emit_dirty_reaped(), stream_cache_emit_eviction_counters(), stream_cache_emit_eviction_threshold(), stream_cache_emit_occupancy_ratio(), and stream_cache_emit_write_through().
Referenced by brix_export_prometheus_metrics().
brix_export_stream_proxy_metrics()
void brix_export_stream_proxy_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 17 of file stream_proxy.c.
References BRIX_EXPORT_PROXY_COUNTER.
Referenced by brix_export_prometheus_metrics().
brix_export_stream_tracking_metrics()
void brix_export_stream_tracking_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 26 of file stream_tracking.c.
References BRIX_USERS_MAX_TRACKED, BRIX_VO_MAX_TRACKED, BRIX_VO_NAME_LEN, ngx_brix_vo_slot_t::bytes_rx_total, ngx_brix_vo_slot_t::bytes_tx_total, ngx_brix_user_global_t::evictions_total, ngx_brix_user_slot_t::id_hash, mw_printf(), ngx_brix_vo_slot_t::name, ngx_brix_vo_global_t::overflow_total, ngx_brix_vo_slot_t::requests_total, ngx_brix_user_slot_t::sessions_total, ngx_brix_user_global_t::slots, ngx_brix_vo_global_t::slots, ngx_brix_user_global_t::total_unique, ngx_brix_user_global_t::unique_count, ngx_brix_metrics_t::user_tracking, and ngx_brix_metrics_t::vo_global.
Referenced by brix_export_prometheus_metrics().
brix_export_unified_metrics()
void brix_export_unified_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 277 of file unified_export.c.
References unified_emit_auth(), unified_emit_cache(), unified_emit_cache_watermark(), unified_emit_cred_select(), unified_emit_io_bytes(), unified_emit_io_latency(), unified_emit_io_ops(), unified_emit_tpc(), and unified_emit_wt_stage().
Referenced by brix_export_prometheus_metrics().
brix_export_webdav_metrics()
void brix_export_webdav_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 98 of file webdav.c.
References ngx_brix_webdav_metrics_t::auth_total, BRIX_HTTP_NSTATUS, brix_http_range_result_names, brix_http_status_names, brix_webdav_auth_names, brix_webdav_cors_names, brix_webdav_method_names, BRIX_WEBDAV_NAUTH_RESULTS, BRIX_WEBDAV_NCORS_EVENTS, BRIX_WEBDAV_NMETHODS, BRIX_WEBDAV_NPROPFIND_DEPTHS, BRIX_WEBDAV_NPUT_MODES, BRIX_WEBDAV_NRANGE_RESULTS, BRIX_WEBDAV_NTPC_CRED_EVENTS, BRIX_WEBDAV_NTPC_EVENTS, brix_webdav_propfind_depth_names, brix_webdav_put_names, brix_webdav_tpc_cred_names, brix_webdav_tpc_names, ngx_brix_webdav_metrics_t::bytes_rx_ipv4_total, ngx_brix_webdav_metrics_t::bytes_rx_ipv6_total, ngx_brix_webdav_metrics_t::bytes_rx_total, ngx_brix_webdav_metrics_t::bytes_tx_ipv4_total, ngx_brix_webdav_metrics_t::bytes_tx_ipv6_total, ngx_brix_webdav_metrics_t::bytes_tx_total, ngx_brix_webdav_metrics_t::cors_total, mw_emit_labeled(), mw_emit_scalar(), mw_printf(), ngx_brix_webdav_metrics_t::propfind_depth_total, ngx_brix_webdav_metrics_t::propfind_entries_total, ngx_brix_webdav_metrics_t::put_body_total, ngx_brix_webdav_metrics_t::range_total, ngx_brix_webdav_metrics_t::requests_total, ngx_brix_webdav_metrics_t::responses_total, ngx_brix_webdav_metrics_t::tpc_cred_total, ngx_brix_webdav_metrics_t::tpc_total, and ngx_brix_metrics_t::webdav.
Referenced by brix_export_prometheus_metrics().
brix_kv_metrics_emit()
void brix_kv_metrics_emit (metrics_writer_t * mw)
Definition at line 172 of file writer.c.
References brix_kv_stats(), brix_kv_zone_count(), brix_kv_zone_get(), mw_printf(), and s.
Referenced by ngx_http_brix_metrics_handler().
brix_storage_backend_metrics_emit()
void brix_storage_backend_metrics_emit (metrics_writer_t * mw)
Definition at line 370 of file writer.c.
References brix_storage_backend_info_emit(), brix_storage_capacity_emit(), brix_storage_io_bytes_emit(), and brix_vfs_backend_export_count().
Referenced by ngx_http_brix_metrics_handler().
brix_track_unique_user()
ngx_int_t brix_track_unique_user (ngx_brix_metrics_t * shm, const char * identity, size_t identity_len)
Definition at line 108 of file tracking.c.
brix_track_vo_activity()
ngx_int_t brix_track_vo_activity (ngx_brix_metrics_t * shm, const char * vo_name, size_t bytes_tx, size_t bytes_rx)
Definition at line 40 of file tracking.c.
mw_emit_labeled()
void mw_emit_labeled (metrics_writer_t * mw, const char * name, const char * help, const char * label_key, const char *const * names, ngx_uint_t n, ngx_atomic_t * counters)
Definition at line 143 of file writer.c.
References mw_printf(), and name.
Referenced by brix_export_cvmfs_metrics(), brix_export_frm_metrics(), brix_export_s3_metrics(), and brix_export_webdav_metrics().
mw_emit_scalar()
void mw_emit_scalar (metrics_writer_t * mw, const char * name, const char * help, ngx_atomic_t * counter)
Definition at line 157 of file writer.c.
References mw_printf(), and name.
Referenced by brix_export_cvmfs_metrics(), brix_export_frm_metrics(), brix_export_pmark_metrics(), brix_export_resilience_metrics(), brix_export_s3_metrics(), and brix_export_webdav_metrics().
mw_finish()
void mw_finish (metrics_writer_t * mw)
Definition at line 383 of file writer.c.
References metrics_writer_t::pos, and metrics_writer_t::tail.
Referenced by ngx_http_brix_metrics_handler().
mw_init()
ngx_int_t mw_init (metrics_writer_t * mw, ngx_pool_t * pool)
Definition at line 86 of file writer.c.
References metrics_writer_t::head, mw_alloc_chain_buffer(), mw_select_tail_buffer(), metrics_writer_t::pool, metrics_writer_t::tail, and metrics_writer_t::total.
Referenced by ngx_http_brix_metrics_handler().
mw_printf()
ngx_int_t mw_printf (metrics_writer_t * mw, const char * fmt, ...)
Definition at line 105 of file writer.c.
References metrics_writer_t::last, METRICS_BUF_SIZE, mw_append_buffer(), metrics_writer_t::pos, and metrics_writer_t::total.
Referenced by brix_export_cluster_metrics(), brix_export_cvmfs_metrics(), brix_export_frm_metrics(), brix_export_ratelimit_metrics(), brix_export_s3_metrics(), brix_export_stream_tracking_metrics(), brix_export_webdav_metrics(), brix_kv_metrics_emit(), brix_storage_backend_info_emit(), brix_storage_capacity_emit(), brix_storage_io_bytes_emit(), cvmfs_export_upstreams(), metrics_emit_config_generation(), metrics_emit_mirror(), metrics_emit_registry_health(), metrics_emit_request_ops(), metrics_emit_srv_family(), mw_emit_labeled(), mw_emit_scalar(), ngx_http_brix_metrics_handler(), stream_cache_emit_cache_bytes(), stream_cache_emit_dirty_reaped(), stream_cache_emit_eviction_counter(), stream_cache_emit_eviction_threshold(), stream_cache_emit_occupancy_ratio(), stream_cache_emit_wt_flushes(), stream_cache_emit_wt_single(), unified_emit_auth(), unified_emit_cache_watermark(), unified_emit_io_bytes(), unified_emit_io_latency(), unified_emit_io_latency_series(), unified_emit_io_ops(), unified_emit_proto_counter(), unified_emit_tpc(), and unified_emit_wt_stage().
ngx_http_brix_health_handler()
ngx_int_t ngx_http_brix_health_handler (ngx_http_request_t * r)
Definition at line 146 of file health.c.
References brix_http_source_offer(), BRIX_PCALLOC_OR_RETURN, ngx_http_brix_metrics_loc_conf_t::health, health_build_json(), health_verbose_requested(), and ngx_http_brix_metrics_module.
Referenced by ngx_http_brix_health_set().
ngx_http_brix_metrics_handler()
ngx_int_t ngx_http_brix_metrics_handler (ngx_http_request_t * r)
Definition at line 20 of file handler.c.
References brix_export_prometheus_metrics(), brix_http_source_offer(), brix_kv_metrics_emit(), brix_storage_backend_metrics_emit(), ngx_http_brix_metrics_loc_conf_t::enable, metrics_writer_t::head, mw_finish(), mw_init(), mw_printf(), ngx_brix_shm_zone, ngx_http_brix_metrics_module, metrics_writer_t::pool, and metrics_writer_t::total.
Referenced by ngx_http_brix_metrics_set().
Variable Documentation
brix_http_range_result_names
const char* brix_http_range_result_names[3] extern
Definition at line 15 of file writer.c.
Referenced by brix_export_s3_metrics(), and brix_export_webdav_metrics().
brix_http_status_names
const char* brix_http_status_names[6] extern
Definition at line 11 of file writer.c.
Referenced by brix_export_s3_metrics(), and brix_export_webdav_metrics().
ngx_http_brix_metrics_module
ngx_module_t ngx_http_brix_metrics_module extern
Definition at line 153 of file module.c.
Referenced by ngx_http_brix_health_handler(), and ngx_http_brix_metrics_handler().