nginx-xrootd: src/net/mirror/mirror.h File Reference
mirror.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
Data Structures
struct brix_mirror_target_t
struct brix_mirror_conf_t
Macros
#define BRIX_MIRROR_MAX_TARGETS 4 /* up to 4 shadow backends per context */
#define BRIX_MIRROR_M_GET (1u << 0)
#define BRIX_MIRROR_M_HEAD (1u << 1)
#define BRIX_MIRROR_M_PROPFIND (1u << 2)
#define BRIX_MIRROR_M_OPTIONS (1u << 3)
#define BRIX_MIRROR_M_PUT (1u << 4)
#define BRIX_MIRROR_M_DELETE (1u << 5)
#define BRIX_MIRROR_M_MKCOL (1u << 6)
#define BRIX_MIRROR_M_MOVE (1u << 7)
#define BRIX_MIRROR_M_COPY (1u << 8)
#define BRIX_MIRROR_M_WRITE_ALL
#define BRIX_MIRROR_M_DEFAULT
#define BRIX_MIRROR_OP_STAT (1u << 0)
#define BRIX_MIRROR_OP_LOCATE (1u << 1)
#define BRIX_MIRROR_OP_OPEN (1u << 2) /* read opens only */
#define BRIX_MIRROR_OP_READ (1u << 3)
#define BRIX_MIRROR_OP_READV (1u << 4)
#define BRIX_MIRROR_OP_DIRLIST (1u << 5)
#define BRIX_MIRROR_OP_STATX (1u << 6)
#define BRIX_MIRROR_OP_QUERY (1u << 7)
#define BRIX_MIRROR_OP_MKDIR (1u << 8)
#define BRIX_MIRROR_OP_RM (1u << 9)
#define BRIX_MIRROR_OP_RMDIR (1u << 10)
#define BRIX_MIRROR_OP_MV (1u << 11)
#define BRIX_MIRROR_OP_TRUNCATE (1u << 12)
#define BRIX_MIRROR_OP_CHMOD (1u << 13)
#define BRIX_MIRROR_OP_WRITE (1u << 14)
#define BRIX_MIRROR_OP_WRITE_ALL
#define BRIX_MIRROR_OP_DEFAULT
#define BRIX_MIRROR_OP_ALL
Functions
static ngx_uint_t brix_mirror_should_sample (ngx_uint_t sample_pct)
static ngx_uint_t brix_mirror_status_class (ngx_uint_t status)
Macro Definition Documentation
BRIX_MIRROR_M_COPY
#define BRIX_MIRROR_M_COPY (1u << 8)
Definition at line 44 of file mirror.h.
BRIX_MIRROR_M_DEFAULT
#define BRIX_MIRROR_M_DEFAULT
Value:
                                  (BRIX_MIRROR_M_GET     \
                                  | BRIX_MIRROR_M_HEAD    \
                                  | BRIX_MIRROR_M_PROPFIND)
Definition at line 50 of file mirror.h.
BRIX_MIRROR_M_DELETE
#define BRIX_MIRROR_M_DELETE (1u << 5)
Definition at line 41 of file mirror.h.
BRIX_MIRROR_M_GET
#define BRIX_MIRROR_M_GET (1u << 0)
Definition at line 33 of file mirror.h.
BRIX_MIRROR_M_HEAD
#define BRIX_MIRROR_M_HEAD (1u << 1)
Definition at line 34 of file mirror.h.
BRIX_MIRROR_M_MKCOL
#define BRIX_MIRROR_M_MKCOL (1u << 6)
Definition at line 42 of file mirror.h.
BRIX_MIRROR_M_MOVE
#define BRIX_MIRROR_M_MOVE (1u << 7)
Definition at line 43 of file mirror.h.
BRIX_MIRROR_M_OPTIONS
#define BRIX_MIRROR_M_OPTIONS (1u << 3)
Definition at line 36 of file mirror.h.
BRIX_MIRROR_M_PROPFIND
#define BRIX_MIRROR_M_PROPFIND (1u << 2)
Definition at line 35 of file mirror.h.
BRIX_MIRROR_M_PUT
#define BRIX_MIRROR_M_PUT (1u << 4)
Definition at line 40 of file mirror.h.
BRIX_MIRROR_M_WRITE_ALL
#define BRIX_MIRROR_M_WRITE_ALL
Value:
                                  (BRIX_MIRROR_M_PUT     \
                                  | BRIX_MIRROR_M_DELETE  \
                                  | BRIX_MIRROR_M_MKCOL   \
                                  | BRIX_MIRROR_M_MOVE    \
                                  | BRIX_MIRROR_M_COPY)
Definition at line 45 of file mirror.h.
BRIX_MIRROR_MAX_TARGETS
#define BRIX_MIRROR_MAX_TARGETS 4 /* up to 4 shadow backends per context */
Definition at line 30 of file mirror.h.
BRIX_MIRROR_OP_ALL
#define BRIX_MIRROR_OP_ALL
Value:
                                  (BRIX_MIRROR_OP_STAT    \
                                  | BRIX_MIRROR_OP_LOCATE  \
                                  | BRIX_MIRROR_OP_OPEN    \
                                  | BRIX_MIRROR_OP_READ    \
                                  | BRIX_MIRROR_OP_READV   \
                                  | BRIX_MIRROR_OP_DIRLIST \
                                  | BRIX_MIRROR_OP_STATX   \
                                  | BRIX_MIRROR_OP_QUERY)
Definition at line 100 of file mirror.h.
BRIX_MIRROR_OP_CHMOD
#define BRIX_MIRROR_OP_CHMOD (1u << 13)
Definition at line 79 of file mirror.h.
BRIX_MIRROR_OP_DEFAULT
#define BRIX_MIRROR_OP_DEFAULT
Value:
                                  (BRIX_MIRROR_OP_STAT    \
                                  | BRIX_MIRROR_OP_LOCATE  \
                                  | BRIX_MIRROR_OP_OPEN    \
                                  | BRIX_MIRROR_OP_DIRLIST \
                                  | BRIX_MIRROR_OP_STATX)
Definition at line 88 of file mirror.h.
BRIX_MIRROR_OP_DIRLIST
#define BRIX_MIRROR_OP_DIRLIST (1u << 5)
Definition at line 64 of file mirror.h.
BRIX_MIRROR_OP_LOCATE
#define BRIX_MIRROR_OP_LOCATE (1u << 1)
Definition at line 60 of file mirror.h.
BRIX_MIRROR_OP_MKDIR
#define BRIX_MIRROR_OP_MKDIR (1u << 8)
Definition at line 74 of file mirror.h.
BRIX_MIRROR_OP_MV
#define BRIX_MIRROR_OP_MV (1u << 11)
Definition at line 77 of file mirror.h.
BRIX_MIRROR_OP_OPEN
#define BRIX_MIRROR_OP_OPEN (1u << 2) /* read opens only */
Definition at line 61 of file mirror.h.
BRIX_MIRROR_OP_QUERY
#define BRIX_MIRROR_OP_QUERY (1u << 7)
Definition at line 66 of file mirror.h.
BRIX_MIRROR_OP_READ
#define BRIX_MIRROR_OP_READ (1u << 3)
Definition at line 62 of file mirror.h.
BRIX_MIRROR_OP_READV
#define BRIX_MIRROR_OP_READV (1u << 4)
Definition at line 63 of file mirror.h.
BRIX_MIRROR_OP_RM
#define BRIX_MIRROR_OP_RM (1u << 9)
Definition at line 75 of file mirror.h.
BRIX_MIRROR_OP_RMDIR
#define BRIX_MIRROR_OP_RMDIR (1u << 10)
Definition at line 76 of file mirror.h.
BRIX_MIRROR_OP_STAT
#define BRIX_MIRROR_OP_STAT (1u << 0)
Definition at line 59 of file mirror.h.
BRIX_MIRROR_OP_STATX
#define BRIX_MIRROR_OP_STATX (1u << 6)
Definition at line 65 of file mirror.h.
BRIX_MIRROR_OP_TRUNCATE
#define BRIX_MIRROR_OP_TRUNCATE (1u << 12)
Definition at line 78 of file mirror.h.
BRIX_MIRROR_OP_WRITE
#define BRIX_MIRROR_OP_WRITE (1u << 14)
Definition at line 80 of file mirror.h.
BRIX_MIRROR_OP_WRITE_ALL
#define BRIX_MIRROR_OP_WRITE_ALL
Value:
                                  (BRIX_MIRROR_OP_MKDIR    \
                                  | BRIX_MIRROR_OP_RM        \
                                  | BRIX_MIRROR_OP_RMDIR     \
                                  | BRIX_MIRROR_OP_MV        \
                                  | BRIX_MIRROR_OP_TRUNCATE  \
                                  | BRIX_MIRROR_OP_CHMOD     \
                                  | BRIX_MIRROR_OP_WRITE)
Definition at line 81 of file mirror.h.
Function Documentation
brix_mirror_should_sample()
static ngx_uint_t brix_mirror_should_sample (ngx_uint_t sample_pct) inline static
Definition at line 147 of file mirror.h.
Referenced by brix_http_mirror_precontent_handler(), and brix_stream_mirror_maybe().
brix_mirror_status_class()
static ngx_uint_t brix_mirror_status_class (ngx_uint_t status) inline static
Definition at line 156 of file mirror.h.
Referenced by mirror_finalize_request().