nginx-xrootd: src/protocols/webdav/module_directives.c File Reference
module_directives.c File Reference
#include "webdav_module_internal.h"
#include "fs/path/path.h"
#include "core/config/config.h"
#include <openssl/pem.h>
#include <openssl/x509.h>
Functions
char * webdav_conf_authdb (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * webdav_conf_require_vo (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * webdav_conf_add_cors_origin (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * webdav_conf_dig_export (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * webdav_conf_proxy_auth (ngx_conf_t *cf, ngx_command_t *cmd, void *conf_ptr)
char * webdav_conf_proxy_upstream (ngx_conf_t *cf, ngx_command_t *cmd, void *conf_ptr)
ngx_int_t webdav_open_file_cache_arg (ngx_str_t *arg, ngx_int_t *max, time_t *inactive, ngx_flag_t *off)
char * webdav_conf_open_file_cache (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static X509 * webdav_conf_load_leaf_cert (ngx_conf_t *cf, ngx_str_t *path)
static ngx_int_t webdav_conf_probe_issuer_file (ngx_conf_t *cf, ngx_str_t *folder, X509_NAME *issuer, ngx_str_t *found)
char * webdav_conf_client_cert_folder (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static ngx_int_t webdav_conf_pick_ca_file (ngx_conf_t *cf, ngx_str_t *folder, ngx_str_t *picked)
char * webdav_conf_proxy_ssl_capath (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Variables
ngx_module_t ngx_http_proxy_module
Function Documentation
webdav_conf_add_cors_origin()
char * webdav_conf_add_cors_origin (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 86 of file module_directives.c.
References ngx_http_brix_webdav_loc_conf_t::cors_origins.
webdav_conf_authdb()
char * webdav_conf_authdb (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 19 of file module_directives.c.
References ngx_http_brix_webdav_loc_conf_t::authdb_rules, and brix_parse_authdb().
webdav_conf_client_cert_folder()
char * webdav_conf_client_cert_folder (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 452 of file module_directives.c.
References webdav_conf_load_leaf_cert(), and webdav_conf_probe_issuer_file().
webdav_conf_dig_export()
char * webdav_conf_dig_export (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 121 of file module_directives.c.
References brix_dig_export_t::canon, ngx_http_brix_webdav_loc_conf_t::dig_exports, brix_dig_export_t::dir, brix_dig_export_t::name, ngx_memcpy, ngx_pnalloc(), and PATH_MAX.
webdav_conf_load_leaf_cert()
static X509 * webdav_conf_load_leaf_cert (ngx_conf_t * cf, ngx_str_t * path) static
Definition at line 342 of file module_directives.c.
Referenced by webdav_conf_client_cert_folder().
webdav_conf_open_file_cache()
char * webdav_conf_open_file_cache (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 280 of file module_directives.c.
References ngx_http_brix_webdav_loc_conf_t::open_file_cache, and webdav_open_file_cache_arg().
webdav_conf_pick_ca_file()
static ngx_int_t webdav_conf_pick_ca_file (ngx_conf_t * cf, ngx_str_t * folder, ngx_str_t * picked) static
Definition at line 565 of file module_directives.c.
References name, ngx_memcpy, and ngx_pnalloc().
Referenced by webdav_conf_proxy_ssl_capath().
webdav_conf_probe_issuer_file()
static ngx_int_t webdav_conf_probe_issuer_file (ngx_conf_t * cf, ngx_str_t * folder, X509_NAME * issuer, ngx_str_t * found) static
Definition at line 378 of file module_directives.c.
References ngx_pnalloc().
Referenced by webdav_conf_client_cert_folder().
webdav_conf_proxy_auth()
char * webdav_conf_proxy_auth (ngx_conf_t * cf, ngx_command_t * cmd, void * conf_ptr)
Definition at line 170 of file module_directives.c.
References ngx_http_brix_webdav_loc_conf_t::upstream_auth, ngx_http_brix_webdav_loc_conf_t::upstream_auth_token, WEBDAV_PROXY_AUTH_ANONYMOUS, WEBDAV_PROXY_AUTH_FORWARD, and WEBDAV_PROXY_AUTH_TOKEN.
webdav_conf_proxy_ssl_capath()
char * webdav_conf_proxy_ssl_capath (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 669 of file module_directives.c.
References ngx_http_proxy_module, ngx_http_brix_webdav_loc_conf_t::proxy_ssl_capath, and webdav_conf_pick_ca_file().
webdav_conf_proxy_upstream()
char * webdav_conf_proxy_upstream (ngx_conf_t * cf, ngx_command_t * cmd, void * conf_ptr)
Definition at line 209 of file module_directives.c.
References ngx_http_brix_webdav_loc_conf_t::upstream_url, and ngx_http_brix_webdav_loc_conf_t::upstream_urls.
webdav_conf_require_vo()
char * webdav_conf_require_vo (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 49 of file module_directives.c.
References brix_copy_conf_string(), brix_normalize_policy_path(), brix_vo_rule_t::path, brix_vo_rule_t::vo, and ngx_http_brix_webdav_loc_conf_t::vo_rules.
webdav_open_file_cache_arg()
ngx_int_t webdav_open_file_cache_arg (ngx_str_t * arg, ngx_int_t * max, time_t * inactive, ngx_flag_t * off)
Definition at line 253 of file module_directives.c.
References s.
Referenced by webdav_conf_open_file_cache().
Variable Documentation
ngx_http_proxy_module
ngx_module_t ngx_http_proxy_module extern
Referenced by webdav_conf_proxy_ssl_capath().