nginx-xrootd: src/protocols/s3/module_merge.c File Reference
module_merge.c File Reference
#include "s3.h"
#include "auth/authz/acc/acc.h"
#include "auth/token/token.h"
#include "core/config/root_prepare.h"
#include "core/config/http_rootfd.h"
#include "core/compat/tmp_path.h"
#include "core/config/credential_block.h"
#include "core/config/http_common.h"
#include "core/config/export_guard.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "core/compat/alloc_guard.h"
#include "module_internal.h"
Functions
char * s3_merge_preamble (ngx_conf_t *cf, ngx_http_s3_loc_conf_t *prev, ngx_http_s3_loc_conf_t *conf)
void s3_merge_scalars (ngx_http_s3_loc_conf_t *prev, ngx_http_s3_loc_conf_t *conf)
char * s3_merge_token (ngx_conf_t *cf, ngx_http_s3_loc_conf_t *prev, ngx_http_s3_loc_conf_t *conf)
static char * s3_export_attach_credential (ngx_conf_t *cf, ngx_http_s3_loc_conf_t *conf)
char * s3_merge_export (ngx_conf_t *cf, ngx_http_s3_loc_conf_t *conf)
Function Documentation
s3_export_attach_credential()
static char * s3_export_attach_credential (ngx_conf_t * cf, ngx_http_s3_loc_conf_t * conf) static
Definition at line 184 of file module_merge.c.
References brix_credential_lookup(), brix_credential_to_backend_cred(), brix_vfs_backend_set_credential(), ngx_http_s3_loc_conf_t::common, ngx_http_brix_shared_conf_t::root_canon, and ngx_http_brix_shared_conf_t::storage_credential.
Referenced by s3_merge_export().
s3_merge_export()
char * s3_merge_export (ngx_conf_t * cf, ngx_http_s3_loc_conf_t * conf)
Definition at line 230 of file module_merge.c.
References brix_export_root_opts_t::allow_write, ngx_http_brix_shared_conf_t::allow_write, BRIX_AF_AUTO, brix_assert_dir_outside_export(), brix_http_open_rootfd(), brix_prepare_export_root(), brix_storage_backend_is_remote(), brix_storage_backend_posix_root(), brix_tier_register_stores(), brix_tmp_reap_register(), brix_vfs_backend_config_str(), ngx_http_s3_loc_conf_t::cache_root, ngx_http_s3_loc_conf_t::cache_root_canon, brix_export_root_opts_t::canon_size, ngx_http_s3_loc_conf_t::common, brix_export_root_opts_t::directive_name, ngx_http_brix_shared_conf_t::pblock_block_size, brix_export_root_opts_t::required, ngx_http_brix_shared_conf_t::root, ngx_http_brix_shared_conf_t::root_canon, s3_export_attach_credential(), ngx_http_brix_shared_conf_t::storage_backend, and ngx_http_brix_shared_conf_t::storage_credential.
Referenced by ngx_http_s3_merge_loc_conf().
s3_merge_preamble()
char * s3_merge_preamble (ngx_conf_t * cf, ngx_http_s3_loc_conf_t * prev, ngx_http_s3_loc_conf_t * conf)
Definition at line 52 of file module_merge.c.
References brix_http_common_adopt(), ngx_http_s3_loc_conf_t::common, and ngx_http_brix_shared_merge().
Referenced by ngx_http_s3_merge_loc_conf().
s3_merge_scalars()
void s3_merge_scalars (ngx_http_s3_loc_conf_t * prev, ngx_http_s3_loc_conf_t * conf)
Definition at line 85 of file module_merge.c.
References ngx_http_s3_loc_conf_t::acc, ngx_http_s3_loc_conf_t::access_key, ngx_http_s3_loc_conf_t::allow_unsigned_session_token, brix_acc_http_merge_conf(), ngx_http_s3_loc_conf_t::bucket, ngx_http_s3_loc_conf_t::cache_root, ngx_http_s3_loc_conf_t::list_cache, ngx_http_s3_loc_conf_t::list_cache_ttl, ngx_http_s3_loc_conf_t::max_keys, ngx_http_s3_loc_conf_t::mpu_max_age, ngx_http_s3_loc_conf_t::region, ngx_http_s3_loc_conf_t::secret_key, ngx_http_s3_loc_conf_t::verify_chunk_signatures, ngx_http_s3_loc_conf_t::zip_access, and ngx_http_s3_loc_conf_t::zip_cd_max_bytes.
Referenced by ngx_http_s3_merge_loc_conf().
s3_merge_token()
char * s3_merge_token (ngx_conf_t * cf, ngx_http_s3_loc_conf_t * prev, ngx_http_s3_loc_conf_t * conf)
Definition at line 124 of file module_merge.c.
References brix_jwks_load(), brix_jwks_register_cleanup(), BRIX_MAX_JWKS_KEYS, ngx_http_s3_loc_conf_t::jwks_key_count, ngx_http_s3_loc_conf_t::jwks_keys, ngx_http_s3_loc_conf_t::token_audience, ngx_http_s3_loc_conf_t::token_clock_skew, ngx_http_s3_loc_conf_t::token_enable, ngx_http_s3_loc_conf_t::token_issuer, and ngx_http_s3_loc_conf_t::token_jwks.
Referenced by ngx_http_s3_merge_loc_conf().