nginx-xrootd: src/observability/dashboard/module_config.c File Reference
module_config.c File Reference
#include "dashboard_http.h"
#include "module_internal.h"
#include <stdio.h>
#include <string.h>
Enumerations
enum dashboard_user_line_t { DASH_USER_LINE_SKIP = 0 , DASH_USER_LINE_OK , DASH_USER_LINE_MALFORMED , DASH_USER_LINE_OOM }
Functions
static dashboard_user_line_t dashboard_parse_user_line (ngx_conf_t *cf, char *line, ngx_array_t *users)
char * ngx_http_brix_dashboard_set_users (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Enumeration Type Documentation
dashboard_user_line_t
enum dashboard_user_line_t
Enumerator
DASH_USER_LINE_SKIP
DASH_USER_LINE_OK
DASH_USER_LINE_MALFORMED
DASH_USER_LINE_OOM
Definition at line 27 of file module_config.c.
Function Documentation
dashboard_parse_user_line()
static dashboard_user_line_t dashboard_parse_user_line (ngx_conf_t * cf, char * line, ngx_array_t * users) static
Definition at line 45 of file module_config.c.
References DASH_USER_LINE_MALFORMED, DASH_USER_LINE_OK, DASH_USER_LINE_OOM, DASH_USER_LINE_SKIP, ngx_memcpy, ngx_pnalloc(), ngx_http_brix_dashboard_user_t::password_hash, and ngx_http_brix_dashboard_user_t::username.
Referenced by ngx_http_brix_dashboard_set_users().
ngx_http_brix_dashboard_set_users()
char * ngx_http_brix_dashboard_set_users (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 90 of file module_config.c.
References DASH_USER_LINE_MALFORMED, DASH_USER_LINE_OOM, dashboard_parse_user_line(), ngx_http_brix_dashboard_loc_conf_t::password, and ngx_http_brix_dashboard_loc_conf_t::users.