nginx-xrootd: src/observability/dashboard/module_dispatch.c File Reference
module_dispatch.c File Reference
#include "dashboard_http.h"
#include "api_admin.h"
#include "core/http/http_headers.h"
#include "module_internal.h"
Data Structures
struct dashboard_api_route_t
struct dashboard_handler_route_t
Enumerations
enum dashboard_match_kind_t { DASH_MATCH_EQ = 0 , DASH_MATCH_PREFIX }
Functions
static ngx_int_t dashboard_uri_eq (ngx_str_t uri, const char *literal)
static ngx_int_t dashboard_uri_prefix (ngx_str_t uri, const char *literal)
static ngx_int_t dashboard_api_route_matches (ngx_str_t uri, const dashboard_api_route_t *route)
static ngx_int_t dashboard_dispatch_api_route (ngx_http_request_t *r, ngx_str_t uri, ngx_int_t *out)
static ngx_int_t dashboard_dispatch_handler_route (ngx_http_request_t *r, ngx_str_t uri, ngx_int_t *out)
ngx_int_t ngx_http_brix_dashboard_main_handler (ngx_http_request_t *r)
Variables
static const dashboard_api_route_t dashboard_api_routes []
static const dashboard_handler_route_t dashboard_handler_routes []
Enumeration Type Documentation
dashboard_match_kind_t
enum dashboard_match_kind_t
Enumerator
DASH_MATCH_EQ
DASH_MATCH_PREFIX
Definition at line 52 of file module_dispatch.c.
Function Documentation
dashboard_api_route_matches()
static ngx_int_t dashboard_api_route_matches (ngx_str_t uri, const dashboard_api_route_t * route) static
Definition at line 114 of file module_dispatch.c.
References DASH_MATCH_PREFIX, dashboard_uri_eq(), dashboard_uri_prefix(), dashboard_api_route_t::literal, and dashboard_api_route_t::match.
Referenced by dashboard_dispatch_api_route().
dashboard_dispatch_api_route()
static ngx_int_t dashboard_dispatch_api_route (ngx_http_request_t * r, ngx_str_t uri, ngx_int_t * out) static
Definition at line 132 of file module_dispatch.c.
References dashboard_api_route_matches(), dashboard_api_routes, and ngx_http_brix_dashboard_api_handler().
Referenced by ngx_http_brix_dashboard_main_handler().
dashboard_dispatch_handler_route()
static ngx_int_t dashboard_dispatch_handler_route (ngx_http_request_t * r, ngx_str_t uri, ngx_int_t * out) static
Definition at line 157 of file module_dispatch.c.
References dashboard_handler_routes, dashboard_uri_eq(), and dashboard_handler_route_t::handler.
Referenced by ngx_http_brix_dashboard_main_handler().
dashboard_uri_eq()
static ngx_int_t dashboard_uri_eq (ngx_str_t uri, const char * literal) static
Definition at line 20 of file module_dispatch.c.
Referenced by dashboard_api_route_matches(), dashboard_dispatch_handler_route(), and ngx_http_brix_dashboard_main_handler().
dashboard_uri_prefix()
static ngx_int_t dashboard_uri_prefix (ngx_str_t uri, const char * literal) static
Definition at line 32 of file module_dispatch.c.
Referenced by dashboard_api_route_matches().
ngx_http_brix_dashboard_main_handler()
ngx_int_t ngx_http_brix_dashboard_main_handler (ngx_http_request_t * r)
Definition at line 182 of file module_dispatch.c.
References brix_admin_dispatch(), BRIX_DASHBOARD_API_V1_NOT_FOUND, brix_http_source_offer(), dashboard_dispatch_api_route(), dashboard_dispatch_handler_route(), dashboard_uri_eq(), ngx_http_brix_dashboard_loc_conf_t::enable, ngx_http_brix_dashboard_api_handler(), ngx_http_brix_dashboard_login_handler(), ngx_http_brix_dashboard_module, and ngx_http_brix_dashboard_page_handler().
Referenced by ngx_http_brix_dashboard_set().
Variable Documentation
dashboard_api_routes
const dashboard_api_route_t dashboard_api_routes[] static
Initial value:
= {
    { DASH_MATCH_EQ,     "/brix/transfers",             BRIX_DASHBOARD_API_COMPAT_TRANSFERS },
    { DASH_MATCH_EQ,     "/brix/api/v1/transfers",      BRIX_DASHBOARD_API_V1_TRANSFERS },
    { DASH_MATCH_PREFIX, "/brix/api/v1/transfers/",     BRIX_DASHBOARD_API_V1_TRANSFER_DETAIL },
    { DASH_MATCH_EQ,     "/brix/api/v1/snapshot",       BRIX_DASHBOARD_API_V1_SNAPSHOT },
    { DASH_MATCH_EQ,     "/brix/api/v1/events",         BRIX_DASHBOARD_API_V1_EVENTS },
    { DASH_MATCH_EQ,     "/brix/api/v1/history",        BRIX_DASHBOARD_API_V1_HISTORY },
    { DASH_MATCH_EQ,     "/brix/api/v1/cluster",        BRIX_DASHBOARD_API_V1_CLUSTER },
    { DASH_MATCH_EQ,     "/brix/api/v1/cache",          BRIX_DASHBOARD_API_V1_CACHE },
    { DASH_MATCH_EQ,     "/brix/api/v1/ratelimit",      BRIX_DASHBOARD_API_V1_RATELIMIT },
    { DASH_MATCH_EQ,     "/brix/api/v1/cvmfs",          BRIX_DASHBOARD_API_V1_CVMFS },
}
Definition at line 75 of file module_dispatch.c.
Referenced by dashboard_dispatch_api_route().
dashboard_handler_routes
const dashboard_handler_route_t dashboard_handler_routes[] static
Initial value:
= {
    { "/brix/api/v1/config",       ngx_http_brix_dashboard_config_download_handler },
    { "/brix/api/v1/files",        ngx_http_brix_dashboard_files_handler },
    { "/brix/api/v1/download",     ngx_http_brix_dashboard_download_handler },
    { "/brix/api/v1/vfs",          ngx_http_brix_dashboard_vfs_exports_handler },
    { "/brix/api/v1/vfs/files",    ngx_http_brix_dashboard_vfs_files_handler },
    { "/brix/api/v1/vfs/download", ngx_http_brix_dashboard_vfs_download_handler },
    { "/brix/api/v1/scan",         ngx_http_brix_dashboard_scan_handler },
}
Definition at line 97 of file module_dispatch.c.
Referenced by dashboard_dispatch_handler_route().