nginx-xrootd: src/protocols/webdav/module_directives_cert.c File Reference
module_directives_cert.c File Reference
#include "webdav_module_internal.h"
#include "core/config/config.h"
#include <openssl/pem.h>
#include <openssl/x509.h>
Functions
static X509 * webdav_conf_load_leaf_cert (ngx_conf_t *cf, ngx_str_t *path)
static ngx_int_t webdav_conf_probe_issuer_file (ngx_conf_t *cf, ngx_str_t *folder, X509_NAME *issuer, ngx_str_t *found)
char * webdav_conf_client_cert_folder (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static ngx_int_t webdav_conf_pick_ca_file (ngx_conf_t *cf, ngx_str_t *folder, ngx_str_t *picked)
char * webdav_conf_proxy_ssl_capath (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Variables
ngx_module_t ngx_http_proxy_module
Function Documentation
webdav_conf_client_cert_folder()
char * webdav_conf_client_cert_folder (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 136 of file module_directives_cert.c.
References webdav_conf_load_leaf_cert(), and webdav_conf_probe_issuer_file().
webdav_conf_load_leaf_cert()
static X509 * webdav_conf_load_leaf_cert (ngx_conf_t * cf, ngx_str_t * path) static
Definition at line 26 of file module_directives_cert.c.
Referenced by webdav_conf_client_cert_folder().
webdav_conf_pick_ca_file()
static ngx_int_t webdav_conf_pick_ca_file (ngx_conf_t * cf, ngx_str_t * folder, ngx_str_t * picked) static
Definition at line 249 of file module_directives_cert.c.
References name, ngx_memcpy, and ngx_pnalloc().
Referenced by webdav_conf_proxy_ssl_capath().
webdav_conf_probe_issuer_file()
static ngx_int_t webdav_conf_probe_issuer_file (ngx_conf_t * cf, ngx_str_t * folder, X509_NAME * issuer, ngx_str_t * found) static
Definition at line 62 of file module_directives_cert.c.
References ngx_pnalloc().
Referenced by webdav_conf_client_cert_folder().
webdav_conf_proxy_ssl_capath()
char * webdav_conf_proxy_ssl_capath (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 353 of file module_directives_cert.c.
References ngx_http_proxy_module, ngx_http_brix_webdav_loc_conf_t::proxy_ssl_capath, and webdav_conf_pick_ca_file().
Variable Documentation
ngx_http_proxy_module
ngx_module_t ngx_http_proxy_module extern
Referenced by webdav_conf_proxy_ssl_capath().