nginx-xrootd: src/protocols/webdav/module_init.c File Reference
module_init.c File Reference
#include "webdav_module_internal.h"
#include "protocols/cvmfs/cvmfs.h"
Functions
ngx_int_t brix_http_protocol_variable (ngx_http_request_t *r, ngx_http_variable_value_t *v, uintptr_t data)
ngx_int_t brix_http_add_protocol_variables (ngx_conf_t *cf)
ngx_int_t ngx_http_brix_webdav_preconfiguration (ngx_conf_t *cf)
ngx_int_t ngx_http_brix_webdav_init_process (ngx_cycle_t *cycle)
void ngx_http_brix_webdav_exit_process (ngx_cycle_t *cycle)
Function Documentation
brix_http_add_protocol_variables()
ngx_int_t brix_http_add_protocol_variables (ngx_conf_t * cf)
Definition at line 68 of file module_init.c.
References brix_http_protocol_variable(), and name.
Referenced by ngx_http_brix_webdav_preconfiguration().
brix_http_protocol_variable()
ngx_int_t brix_http_protocol_variable (ngx_http_request_t * r, ngx_http_variable_value_t * v, uintptr_t data)
Definition at line 29 of file module_init.c.
References ngx_http_s3_loc_conf_t::common, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, ngx_http_brix_shared_conf_t::enable, brix_cvmfs_conf_t::enable, ngx_http_brix_cvmfs_module, ngx_http_brix_s3_module, and ngx_http_brix_webdav_module.
Referenced by brix_http_add_protocol_variables().
ngx_http_brix_webdav_exit_process()
void ngx_http_brix_webdav_exit_process (ngx_cycle_t * cycle)
Definition at line 102 of file module_init.c.
ngx_http_brix_webdav_init_process()
ngx_int_t ngx_http_brix_webdav_init_process (ngx_cycle_t * cycle)
Definition at line 93 of file module_init.c.
ngx_http_brix_webdav_preconfiguration()
ngx_int_t ngx_http_brix_webdav_preconfiguration (ngx_conf_t * cf)
Definition at line 86 of file module_init.c.
References brix_http_add_protocol_variables().