nginx-xrootd: src/protocols/webdav/module_acc_directives.c File Reference
module_acc_directives.c File Reference
#include "webdav.h"
#include "auth/authz/acc/acc.h"
#include "protocols/s3/s3.h"
#include "module_acc_directives.h"
Functions
char * brix_http_set_ktls (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_acc_http_set_authdb (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static char * brix_acc_http_set_enum (ngx_conf_t *cf, ngx_conf_enum_t *e, ngx_uint_t *wp, ngx_uint_t *sp)
char * brix_acc_http_set_format (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_acc_http_set_audit (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static char * brix_acc_http_both (ngx_conf_t *cf, brix_acc_http_t **wc, brix_acc_http_t **sc)
char * brix_acc_http_set_refresh (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_acc_http_set_gidlifetime (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_acc_http_set_nisdomain (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static char * brix_acc_http_set_flag (ngx_conf_t *cf, ngx_flag_t *wp, ngx_flag_t *sp, ngx_str_t *val)
char * brix_acc_http_set_pgo (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_acc_http_set_resolve_hosts (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_acc_http_set_spacechar (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_acc_http_set_encoding (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_acc_http_set_gidretran (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Function Documentation
brix_acc_http_both()
static char * brix_acc_http_both (ngx_conf_t * cf, brix_acc_http_t ** wc, brix_acc_http_t ** sc) static
Definition at line 109 of file module_acc_directives.c.
References ngx_http_brix_webdav_loc_conf_t::acc, ngx_http_brix_s3_module, ngx_http_brix_webdav_module, and s.
Referenced by brix_acc_http_set_encoding(), brix_acc_http_set_gidlifetime(), brix_acc_http_set_gidretran(), brix_acc_http_set_nisdomain(), brix_acc_http_set_pgo(), brix_acc_http_set_refresh(), brix_acc_http_set_resolve_hosts(), and brix_acc_http_set_spacechar().
brix_acc_http_set_audit()
char * brix_acc_http_set_audit (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 93 of file module_acc_directives.c.
References ngx_http_s3_loc_conf_t::acc, ngx_http_brix_webdav_loc_conf_t::acc, brix_acc_http_t::audit, brix_acc_audit_modes, brix_acc_http_set_enum(), ngx_http_brix_s3_module, and ngx_http_brix_webdav_module.
brix_acc_http_set_authdb()
char * brix_acc_http_set_authdb (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 51 of file module_acc_directives.c.
References ngx_http_s3_loc_conf_t::acc, ngx_http_brix_webdav_loc_conf_t::acc, brix_acc_http_t::authdb, ngx_http_brix_s3_module, and ngx_http_brix_webdav_module.
brix_acc_http_set_encoding()
char * brix_acc_http_set_encoding (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 216 of file module_acc_directives.c.
References brix_acc_http_both(), brix_acc_http_set_flag(), and brix_acc_http_t::encoding.
brix_acc_http_set_enum()
static char * brix_acc_http_set_enum (ngx_conf_t * cf, ngx_conf_enum_t * e, ngx_uint_t * wp, ngx_uint_t * sp) static
Definition at line 64 of file module_acc_directives.c.
References name.
Referenced by brix_acc_http_set_audit(), and brix_acc_http_set_format().
brix_acc_http_set_flag()
static char * brix_acc_http_set_flag (ngx_conf_t * cf, ngx_flag_t * wp, ngx_flag_t * sp, ngx_str_t * val) static
Definition at line 168 of file module_acc_directives.c.
Referenced by brix_acc_http_set_encoding(), brix_acc_http_set_pgo(), and brix_acc_http_set_resolve_hosts().
brix_acc_http_set_format()
char * brix_acc_http_set_format (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 82 of file module_acc_directives.c.
References ngx_http_s3_loc_conf_t::acc, ngx_http_brix_webdav_loc_conf_t::acc, brix_acc_format_modes, brix_acc_http_set_enum(), brix_acc_http_t::format, ngx_http_brix_s3_module, and ngx_http_brix_webdav_module.
brix_acc_http_set_gidlifetime()
char * brix_acc_http_set_gidlifetime (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 139 of file module_acc_directives.c.
References brix_acc_http_both(), and brix_acc_http_t::gidlifetime.
brix_acc_http_set_gidretran()
char * brix_acc_http_set_gidretran (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 226 of file module_acc_directives.c.
References brix_acc_http_both(), and brix_acc_http_t::gidretran.
brix_acc_http_set_nisdomain()
char * brix_acc_http_set_nisdomain (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 157 of file module_acc_directives.c.
References brix_acc_http_both(), and brix_acc_http_t::nisdomain.
brix_acc_http_set_pgo()
char * brix_acc_http_set_pgo (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 184 of file module_acc_directives.c.
References brix_acc_http_both(), brix_acc_http_set_flag(), and brix_acc_http_t::pgo.
brix_acc_http_set_refresh()
char * brix_acc_http_set_refresh (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 121 of file module_acc_directives.c.
References brix_acc_http_both(), and brix_acc_http_t::refresh.
brix_acc_http_set_resolve_hosts()
char * brix_acc_http_set_resolve_hosts (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 194 of file module_acc_directives.c.
References brix_acc_http_both(), brix_acc_http_set_flag(), and brix_acc_http_t::resolve_hosts.
brix_acc_http_set_spacechar()
char * brix_acc_http_set_spacechar (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 205 of file module_acc_directives.c.
References brix_acc_http_both(), and brix_acc_http_t::spacechar.
brix_http_set_ktls()
char * brix_http_set_ktls (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 26 of file module_acc_directives.c.
References ngx_http_s3_loc_conf_t::common, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::ktls, ngx_http_brix_s3_module, and ngx_http_brix_webdav_module.