nginx-xrootd: src/protocols/webdav/move.c File Reference
move.c File Reference
#include "webdav.h"
#include "fs/vfs/vfs.h"
#include "core/http/http_conditionals.h"
#include "auth/impersonate/impersonate.h"
#include "fs/path/path.h"
#include <limits.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
struct webdav_move_collection_task_t
struct webdav_move_req_t
Functions
static ngx_int_t webdav_move_probe (ngx_http_request_t *r, const char *path, struct stat *sb)
static ngx_int_t webdav_move_execute_cred (const webdav_move_req_t *req, int *sys_errno)
static void webdav_move_collection_thread (void *data, ngx_log_t *log)
static void webdav_move_collection_done (ngx_event_t *ev)
static ngx_int_t webdav_move_collection_post_task (const webdav_move_req_t *req)
static ngx_int_t webdav_move_resolve_dest (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, char *dst_path, size_t dst_cap)
static ngx_int_t webdav_move_run_sync (const webdav_move_req_t *req)
static ngx_int_t webdav_move_dispatch (const webdav_move_req_t *req, int is_dir)
ngx_int_t webdav_handle_move (ngx_http_request_t *r)
Function Documentation
webdav_handle_move()
ngx_int_t webdav_handle_move (ngx_http_request_t * r)
Definition at line 461 of file move.c.
References brix_http_overwrite_forbidden(), brix_webdav_backend_instance(), ngx_http_brix_webdav_loc_conf_t::common, webdav_move_req_t::conf, webdav_move_req_t::dst_existed, webdav_move_req_t::dst_path, ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), webdav_move_req_t::overwrite, webdav_move_req_t::r, ngx_http_brix_shared_conf_t::root_canon, webdav_move_req_t::sd, webdav_move_req_t::src_path, stat(), webdav_check_locks_tree(), WEBDAV_MAX_PATH, webdav_move_dispatch(), webdav_move_probe(), and webdav_move_resolve_dest().
Referenced by webdav_dispatch_move().
webdav_move_collection_done()
static void webdav_move_collection_done (ngx_event_t * ev) static
Definition at line 210 of file move.c.
References brix_log_safe_path(), webdav_move_collection_task_t::http_status, webdav_move_collection_task_t::r, webdav_move_collection_task_t::src_path, webdav_move_collection_task_t::sys_errno, webdav_metrics_finalize_request(), and webdav_send_status_only().
Referenced by webdav_move_collection_post_task().
webdav_move_collection_post_task()
static ngx_int_t webdav_move_collection_post_task (const webdav_move_req_t * req) static
Definition at line 237 of file move.c.
References brix_imp_enabled(), ngx_http_brix_webdav_loc_conf_t::common, webdav_move_req_t::conf, webdav_move_collection_task_t::dst_existed, webdav_move_req_t::dst_existed, webdav_move_collection_task_t::dst_path, webdav_move_req_t::dst_path, webdav_move_collection_task_t::http_status, webdav_move_collection_task_t::log, webdav_move_collection_task_t::overwrite, webdav_move_req_t::overwrite, webdav_move_collection_task_t::r, webdav_move_req_t::r, webdav_move_collection_task_t::root_canon, ngx_http_brix_shared_conf_t::root_canon, webdav_move_collection_task_t::sd, webdav_move_req_t::sd, webdav_move_collection_task_t::src_path, webdav_move_req_t::src_path, webdav_move_collection_task_t::sys_errno, ngx_http_brix_shared_conf_t::thread_pool, ngx_http_brix_shared_conf_t::thread_pool_name, webdav_move_collection_done(), and webdav_move_collection_thread().
Referenced by webdav_move_dispatch().
webdav_move_collection_thread()
static void webdav_move_collection_thread (void * data, ngx_log_t * log) static
Definition at line 184 of file move.c.
References webdav_move_req_t::conf, webdav_move_collection_task_t::dst_existed, webdav_move_req_t::dst_existed, webdav_move_collection_task_t::dst_path, webdav_move_req_t::dst_path, webdav_move_collection_task_t::http_status, log, ngx_http_brix_webdav_module, webdav_move_collection_task_t::overwrite, webdav_move_req_t::overwrite, webdav_move_collection_task_t::r, webdav_move_req_t::r, webdav_move_collection_task_t::sd, webdav_move_req_t::sd, webdav_move_collection_task_t::src_path, webdav_move_req_t::src_path, webdav_move_collection_task_t::sys_errno, and webdav_move_execute_cred().
Referenced by webdav_move_collection_post_task().
webdav_move_dispatch()
static ngx_int_t webdav_move_dispatch (const webdav_move_req_t * req, int is_dir) static
Definition at line 422 of file move.c.
References webdav_move_collection_post_task(), and webdav_move_run_sync().
Referenced by webdav_handle_move().
webdav_move_execute_cred()
static ngx_int_t webdav_move_execute_cred (const webdav_move_req_t * req, int * sys_errno) static
Definition at line 130 of file move.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_WEBDAV, brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), brix_vfs_rename(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, webdav_move_req_t::conf, webdav_move_req_t::dst_existed, webdav_move_req_t::dst_path, ngx_http_brix_webdav_req_ctx_t::identity, brix_path_result_t::is_confined, ngx_http_brix_webdav_module, webdav_move_req_t::overwrite, brix_vfs_ctx_t::pool, webdav_move_req_t::r, brix_path_result_t::resolved, ngx_http_brix_shared_conf_t::root_canon, brix_vfs_ctx_t::sd, webdav_move_req_t::sd, webdav_move_req_t::src_path, ngx_http_brix_shared_conf_t::storage_credential_dir, ngx_http_brix_shared_conf_t::storage_credential_fallback, and webdav_vfs_bind_deleg().
Referenced by webdav_move_collection_thread(), and webdav_move_run_sync().
webdav_move_probe()
static ngx_int_t webdav_move_probe (ngx_http_request_t * r, const char * path, struct stat * sb) static
Definition at line 62 of file move.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_WEBDAV, brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), brix_vfs_probe(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, brix_vfs_stat_t::dev, ngx_http_brix_webdav_req_ctx_t::identity, brix_vfs_stat_t::ino, brix_vfs_stat_t::mode, ngx_http_brix_webdav_module, brix_vfs_ctx_t::pool, ngx_http_brix_shared_conf_t::root_canon, ngx_http_brix_shared_conf_t::storage_credential_dir, ngx_http_brix_shared_conf_t::storage_credential_fallback, and webdav_vfs_bind_deleg().
Referenced by webdav_handle_move().
webdav_move_resolve_dest()
static ngx_int_t webdav_move_resolve_dest (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, char * dst_path, size_t dst_cap) static
Definition at line 321 of file move.c.
References ngx_http_brix_shared_conf_t::cache_store_endpoint, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::root_canon, webdav_destination_extract_path(), WEBDAV_MAX_PATH, webdav_resolve_destination_path(), webdav_tpc_find_header, and webdav_urldecode().
Referenced by webdav_handle_move().
webdav_move_run_sync()
static ngx_int_t webdav_move_run_sync (const webdav_move_req_t * req) static
Definition at line 376 of file move.c.
References brix_log_safe_path(), webdav_move_req_t::r, webdav_move_req_t::src_path, webdav_move_execute_cred(), and webdav_send_no_body().
Referenced by webdav_move_dispatch().