nginx-xrootd: client/apps/diag/mpxstats.c File Reference
mpxstats.c File Reference
#include "brix.h"
#include "core/version.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct mpx_metric
Macros
#define MPX_MAX_METRICS 512
Functions
static void ingest_line (const char *line)
static void ingest_buffer (char *buf)
static void report (const char *source)
static int usage_fp (FILE *out, int rc)
int brix_mpxstats_main (int argc, char **argv)
Variables
static mpx_metric g_tab [512]
static int g_n
Macro Definition Documentation
MPX_MAX_METRICS
#define MPX_MAX_METRICS 512
Definition at line 25 of file mpxstats.c.
Function Documentation
brix_mpxstats_main()
int brix_mpxstats_main (int argc, char ** argv)
Definition at line 125 of file mpxstats.c.
References brix_client_version(), brix_http_get(), brix_status_clear(), g_n, ingest_buffer(), brix_status::msg, report(), and usage_fp().
Referenced by main().
ingest_buffer()
static void ingest_buffer (char * buf) static
Definition at line 84 of file mpxstats.c.
References ingest_line().
Referenced by brix_mpxstats_main().
ingest_line()
static void ingest_line (const char * line) static
Definition at line 38 of file mpxstats.c.
References g_n, g_tab, MPX_MAX_METRICS, name, mpx_metric::series, and mpx_metric::sum.
Referenced by ingest_buffer().
report()
static void report (const char * source) static
Definition at line 94 of file mpxstats.c.
References g_n, g_tab, name, and mpx_metric::series.
Referenced by brix_mpxstats_main(), brix_rmtree(), and rmtree_depth().
usage_fp()
static int usage_fp (FILE * out, int rc) static
Definition at line 114 of file mpxstats.c.
References BRIX_USAGE_FOOTER.
Referenced by brix_mpxstats_main().
Variable Documentation
g_n
int g_n static
Definition at line 34 of file mpxstats.c.
Referenced by brix_mpxstats_main(), ingest_line(), and report().
g_tab
mpx_metric g_tab[512] static
Definition at line 33 of file mpxstats.c.
Referenced by ingest_line(), and report().