nginx-xrootd: src/protocols/s3/multipart_internal.h File Reference
multipart_internal.h File Reference
Macros
#define MPU_MAX_PART_NUMBER 10000
Functions
int mpu_validate_upload_id (const char *upload_id)
int mpu_rmdir_recursive (ngx_log_t *log, const char *root_canon, const char *path)
int s3_mpu_reap_stale (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const char *final_path, time_t max_age_secs)
Macro Definition Documentation
MPU_MAX_PART_NUMBER
#define MPU_MAX_PART_NUMBER 10000
Definition at line 9 of file multipart_internal.h.
Function Documentation
mpu_rmdir_recursive()
int mpu_rmdir_recursive (ngx_log_t * log, const char * root_canon, const char * path)
Definition at line 139 of file multipart_helpers.c.
References brix_fs_remove_tree_confined(), and log.
Referenced by s3_handle_multipart_abort(), s3_mpu_assemble(), and s3_mpu_reap_stale().
mpu_validate_upload_id()
int mpu_validate_upload_id (const char * upload_id)
Definition at line 112 of file multipart_helpers.c.
Referenced by s3_handle_list_parts(), s3_handle_multipart_abort(), s3_handle_upload_part_copy(), and s3_multipart_complete_body_handler_inner().
s3_mpu_reap_stale()
int s3_mpu_reap_stale (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const char * final_path, time_t max_age_secs)
Definition at line 165 of file multipart_helpers.c.
References brix_vfs_closedir(), brix_vfs_opendir_quiet(), brix_vfs_probe(), brix_vfs_readdir_kind(), ngx_http_s3_loc_conf_t::common, brix_vfs_stat_t::is_directory, log, mpu_rmdir_recursive(), brix_vfs_stat_t::mtime, name, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, and s3_build_vfs_ctx().
Referenced by s3_handle_multipart_initiate().