nginx-xrootd: src/protocols/s3/multipart_helpers.c File Reference
multipart_helpers.c File Reference
#include "s3.h"
#include "multipart_internal.h"
#include "core/compat/fs_walk.h"
#include "fs/path/path.h"
#include "fs/vfs/vfs.h"
#include "core/http/http_query.h"
#include <dirent.h>
#include <fcntl.h>
#include <limits.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Functions
int s3_has_query_flag (ngx_http_request_t *r, const char *key)
int s3_get_query_param (ngx_http_request_t *r, const char *key, char *out, size_t outsz)
void s3_get_mpu_dir (const char *fs_path, const char *upload_id, char *out_dir, size_t outsz)
int mpu_validate_upload_id (const char *upload_id)
int mpu_rmdir_recursive (ngx_log_t *log, const char *root_canon, const char *path)
static int s3_mpu_reap_one_entry (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const char *root_canon, ngx_log_t *log, const char *dir, const char *dname, time_t now, time_t max_age_secs)
int s3_mpu_reap_stale (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const char *final_path, time_t max_age_secs)
Function Documentation
mpu_rmdir_recursive()
int mpu_rmdir_recursive (ngx_log_t * log, const char * root_canon, const char * path)
Definition at line 139 of file multipart_helpers.c.
References brix_fs_remove_tree_confined(), and log.
Referenced by s3_handle_multipart_abort(), s3_mpu_assemble(), and s3_mpu_reap_one_entry().
mpu_validate_upload_id()
int mpu_validate_upload_id (const char * upload_id)
Definition at line 112 of file multipart_helpers.c.
Referenced by s3_handle_list_parts(), s3_handle_multipart_abort(), s3_multipart_complete_body_handler_inner(), and s3_resolve_part_target().
s3_get_mpu_dir()
void s3_get_mpu_dir (const char * fs_path, const char * upload_id, char * out_dir, size_t outsz)
Definition at line 87 of file multipart_helpers.c.
Referenced by s3_handle_list_parts(), s3_handle_multipart_abort(), s3_handle_multipart_initiate(), s3_multipart_complete_body_handler_inner(), s3_prepare_upload_part(), and s3_resolve_part_target().
s3_get_query_param()
int s3_get_query_param (ngx_http_request_t * r, const char * key, char * out, size_t outsz)
Definition at line 66 of file multipart_helpers.c.
References brix_http_query_get(), BRIX_HTTP_QUERY_TRUNCATE, and key.
Referenced by lp_parse_query(), mpu_parse_max_uploads(), s3_apply_put_precondition(), s3_dashboard_put_op(), s3_dispatch_object_delete(), s3_dispatch_object_get(), s3_dispatch_object_post(), s3_handle_list_multipart_uploads(), s3_handle_list_parts(), s3_multipart_complete_body_handler_inner(), and s3_prepare_upload_part().
s3_has_query_flag()
int s3_has_query_flag (ngx_http_request_t * r, const char * key)
Definition at line 56 of file multipart_helpers.c.
References brix_http_query_has(), and key.
Referenced by s3_dispatch_bucket_get(), s3_dispatch_empty_post(), s3_dispatch_object_delete(), s3_dispatch_object_get(), s3_dispatch_object_post(), s3_dispatch_object_put(), and s3_prepare_upload_part().
s3_mpu_reap_one_entry()
static int s3_mpu_reap_one_entry (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const char * root_canon, ngx_log_t * log, const char * dir, const char * dname, time_t now, time_t max_age_secs) static
Definition at line 164 of file multipart_helpers.c.
References brix_vfs_probe(), brix_vfs_stat_t::is_directory, log, mpu_rmdir_recursive(), brix_vfs_stat_t::mtime, PATH_MAX, and s3_build_vfs_ctx().
Referenced by s3_mpu_reap_stale().
s3_mpu_reap_stale()
int s3_mpu_reap_stale (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const char * final_path, time_t max_age_secs)
Definition at line 213 of file multipart_helpers.c.
References brix_vfs_closedir(), brix_vfs_opendir_quiet(), brix_vfs_readdir_kind(), ngx_http_s3_loc_conf_t::common, log, name, ngx_memcpy, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, s3_build_vfs_ctx(), and s3_mpu_reap_one_entry().
Referenced by s3_handle_multipart_initiate().