nginx-xrootd: src/protocols/s3/multipart_complete_body.c File Reference
multipart_complete_body.c File Reference
#include "s3.h"
#include "multipart_internal.h"
#include "auth/impersonate/lifecycle.h"
#include "fs/vfs/vfs.h"
#include "core/compat/copy_range.h"
#include <string.h>
Data Structures
struct s3_mpu_aio_t
Functions
static void s3_multipart_complete_body_handler_inner (ngx_http_request_t *r)
void s3_multipart_complete_body_handler (ngx_http_request_t *r)
static ngx_int_t s3_mpu_assemble (ngx_http_request_t *r, ngx_log_t *log, const char *root_canon, const char *mpu_dir, const char *final_tmp, const char *fs_path, struct stat *st_out, char *crc64_b64_out, size_t crc64_sz, int *http_status_out)
static void s3_mpu_send_result (ngx_http_request_t *r, ngx_uint_t method_slot, const ngx_str_t *bucket, const char *fs_path, const struct stat *st, const char *crc64_b64)
static void s3_mpu_aio_thread (void *data, ngx_log_t *log)
static void s3_mpu_aio_done (ngx_event_t *ev)
Function Documentation
s3_mpu_aio_done()
static void s3_mpu_aio_done (ngx_event_t * ev) static
Definition at line 279 of file multipart_complete_body.c.
References BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, s3_mpu_aio_t::bucket, s3_mpu_aio_t::crc64_b64, s3_mpu_aio_t::fs_path, s3_mpu_aio_t::http_status, s3_mpu_aio_t::method_slot, s3_mpu_aio_t::r, s3_mpu_aio_t::rc, s3_metrics_finalize_request_method(), s3_mpu_send_result(), and s3_mpu_aio_t::st.
Referenced by s3_multipart_complete_body_handler_inner().
s3_mpu_aio_thread()
static void s3_mpu_aio_thread (void * data, ngx_log_t * log) static
Definition at line 269 of file multipart_complete_body.c.
References s3_mpu_aio_t::crc64_b64, s3_mpu_aio_t::final_tmp, s3_mpu_aio_t::fs_path, s3_mpu_aio_t::http_status, log, s3_mpu_aio_t::mpu_dir, s3_mpu_aio_t::r, s3_mpu_aio_t::rc, s3_mpu_aio_t::root_canon, s3_mpu_assemble(), and s3_mpu_aio_t::st.
Referenced by s3_multipart_complete_body_handler_inner().
s3_mpu_assemble()
static ngx_int_t s3_mpu_assemble (ngx_http_request_t * r, ngx_log_t * log, const char * root_canon, const char * mpu_dir, const char * final_tmp, const char * fs_path, struct stat * st_out, char * crc64_b64_out, size_t crc64_sz, int * http_status_out) static
Definition at line 79 of file multipart_complete_body.c.
References brix_copy_range(), brix_log_safe_path(), brix_rename_confined_canon(), brix_vfs_open_fd(), brix_vfs_unlink_path(), close(), fstat(), log, MPU_MAX_PART_NUMBER, mpu_rmdir_recursive(), PATH_MAX, s3_object_crc64nvme_b64(), and stat().
Referenced by s3_mpu_aio_thread(), and s3_multipart_complete_body_handler_inner().
s3_mpu_send_result()
static void s3_mpu_send_result (ngx_http_request_t * r, ngx_uint_t method_slot, const ngx_str_t * bucket, const char * fs_path, const struct stat * st, const char * crc64_b64) static
Definition at line 198 of file multipart_complete_body.c.
References brix_http_send_xml_buffer(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, ngx_memcpy, s3_etag(), S3_HDR_CHECKSUM_CRC64NVME, S3_HDR_CHECKSUM_TYPE, s3_metrics_finalize_request_method(), and s3_set_header().
Referenced by s3_mpu_aio_done(), and s3_multipart_complete_body_handler_inner().
s3_multipart_complete_body_handler()
void s3_multipart_complete_body_handler (ngx_http_request_t * r)
Definition at line 56 of file multipart_complete_body.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, and s3_multipart_complete_body_handler_inner().
Referenced by s3_dispatch_object_post().
s3_multipart_complete_body_handler_inner()
static void s3_multipart_complete_body_handler_inner (ngx_http_request_t * r) static
Definition at line 295 of file multipart_complete_body.c.
References BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, brix_vfs_probe(), s3_mpu_aio_t::bucket, ngx_http_s3_loc_conf_t::bucket, ngx_http_s3_loc_conf_t::common, s3_mpu_aio_t::final_tmp, s3_mpu_aio_t::fs_path, ngx_http_s3_req_ctx_t::fs_path, brix_vfs_stat_t::is_directory, s3_mpu_aio_t::method_slot, s3_mpu_aio_t::mpu_dir, mpu_validate_upload_id(), ngx_http_brix_s3_module, PATH_MAX, s3_mpu_aio_t::r, ngx_http_brix_shared_conf_t::root_canon, s3_mpu_aio_t::root_canon, s3_build_vfs_ctx(), S3_CRC64NVME_B64_MAX, s3_get_mpu_dir(), s3_get_query_param(), s3_metrics_finalize_request_method(), s3_metrics_method_slot(), s3_mpu_aio_done(), s3_mpu_aio_thread(), s3_mpu_assemble(), s3_mpu_send_result(), s3_send_xml_error(), s3_thread_pool(), and stat().
Referenced by s3_multipart_complete_body_handler().