nginx-xrootd: src/protocols/s3/multipart_complete_list_uploads.c File Reference
multipart_complete_list_uploads.c File Reference
#include "s3.h"
#include "multipart_internal.h"
#include "fs/vfs/vfs.h"
#include <dirent.h>
#include <fcntl.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
struct mpu_upload_entry_t
struct mpu_scan_t
struct mpu_page_t
Macros
#define MPU_MAX_LISTED_UPLOADS 1000
#define MPU_LIST_MAX_DEPTH 16
Functions
static void mpu_collect (mpu_scan_t *scan, const char *dir_path, const char *key_prefix, int depth)
static int mpu_upload_entry_cmp (const void *a, const void *b)
static void mpu_record_staging (mpu_scan_t *scan, const char *dname, const char *key_prefix, time_t mtime)
static void mpu_scan_entry (mpu_scan_t *scan, const char *dir_path, const char *key_prefix, const char *dname, int depth)
static int mpu_parse_max_uploads (ngx_http_request_t *r)
static int mpu_marker_start_idx (const mpu_upload_entry_t *uploads, int nuploads, const char *key_marker)
static ngx_int_t mpu_render_and_send (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const mpu_page_t *pg)
ngx_int_t s3_handle_list_multipart_uploads (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf)
Macro Definition Documentation
MPU_LIST_MAX_DEPTH
#define MPU_LIST_MAX_DEPTH 16
Definition at line 63 of file multipart_complete_list_uploads.c.
MPU_MAX_LISTED_UPLOADS
#define MPU_MAX_LISTED_UPLOADS 1000
Definition at line 57 of file multipart_complete_list_uploads.c.
Function Documentation
mpu_collect()
static void mpu_collect (mpu_scan_t * scan, const char * dir_path, const char * key_prefix, int depth) static
Definition at line 234 of file multipart_complete_list_uploads.c.
References brix_vfs_closedir(), brix_vfs_opendir_quiet(), brix_vfs_readdir_kind(), mpu_scan_t::cf, mpu_scan_t::max, MPU_LIST_MAX_DEPTH, mpu_scan_entry(), mpu_scan_t::n, name, mpu_scan_t::r, and s3_build_vfs_ctx().
Referenced by mpu_scan_entry(), and s3_handle_list_multipart_uploads().
mpu_marker_start_idx()
static int mpu_marker_start_idx (const mpu_upload_entry_t * uploads, int nuploads, const char * key_marker) static
Definition at line 309 of file multipart_complete_list_uploads.c.
References key.
Referenced by s3_handle_list_multipart_uploads().
mpu_parse_max_uploads()
static int mpu_parse_max_uploads (ngx_http_request_t * r) static
Definition at line 282 of file multipart_complete_list_uploads.c.
References MPU_MAX_LISTED_UPLOADS, and s3_get_query_param().
Referenced by s3_handle_list_multipart_uploads().
mpu_record_staging()
static void mpu_record_staging (mpu_scan_t * scan, const char * dname, const char * key_prefix, time_t mtime) static
Definition at line 128 of file multipart_complete_list_uploads.c.
References mpu_upload_entry_t::key, mpu_upload_entry_t::mtime, mpu_scan_t::n, mpu_upload_entry_t::upload_id, and mpu_scan_t::uploads.
Referenced by mpu_scan_entry().
mpu_render_and_send()
static ngx_int_t mpu_render_and_send (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const mpu_page_t * pg) static
Definition at line 344 of file multipart_complete_list_uploads.c.
References brix_format_iso8601(), brix_http_send_xml_buffer(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, ngx_http_s3_loc_conf_t::bucket, mpu_page_t::end_idx, key, mpu_page_t::key_marker, mpu_page_t::max_uploads, ngx_memcpy, mpu_page_t::start_idx, mpu_page_t::truncated, mpu_page_t::uploads, XML_APPEND, and XML_APPEND_ELEM.
Referenced by s3_handle_list_multipart_uploads().
mpu_scan_entry()
static void mpu_scan_entry (mpu_scan_t * scan, const char * dir_path, const char * key_prefix, const char * dname, int depth) static
Definition at line 173 of file multipart_complete_list_uploads.c.
References brix_vfs_probe(), mpu_scan_t::cf, brix_vfs_stat_t::is_directory, mpu_collect(), mpu_record_staging(), brix_vfs_stat_t::mtime, PATH_MAX, mpu_scan_t::r, and s3_build_vfs_ctx().
Referenced by mpu_collect().
mpu_upload_entry_cmp()
static int mpu_upload_entry_cmp (const void * a, const void * b) static
Definition at line 107 of file multipart_complete_list_uploads.c.
References key.
Referenced by s3_handle_list_multipart_uploads().
s3_handle_list_multipart_uploads()
ngx_int_t s3_handle_list_multipart_uploads (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf)
Definition at line 425 of file multipart_complete_list_uploads.c.
References BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, mpu_scan_t::cf, ngx_http_s3_loc_conf_t::common, mpu_page_t::end_idx, mpu_page_t::key_marker, mpu_scan_t::max, mpu_page_t::max_uploads, mpu_collect(), mpu_marker_start_idx(), MPU_MAX_LISTED_UPLOADS, mpu_parse_max_uploads(), mpu_render_and_send(), mpu_upload_entry_cmp(), mpu_scan_t::n, mpu_scan_t::r, ngx_http_brix_shared_conf_t::root, ngx_http_brix_shared_conf_t::root_canon, s3_get_query_param(), mpu_page_t::start_idx, mpu_page_t::truncated, mpu_scan_t::uploads, and mpu_page_t::uploads.
Referenced by s3_dispatch_bucket_get().