nginx-xrootd: src/protocols/s3/multipart_complete_list_parts.c File Reference
multipart_complete_list_parts.c File Reference
#include "s3.h"
#include "multipart_internal.h"
#include "fs/vfs/vfs.h"
#include <dirent.h>
#include <fcntl.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
struct mpu_part_entry_t
struct lp_page_t
Functions
static int mpu_part_entry_cmp (const void *a, const void *b)
static void lp_parse_query (ngx_http_request_t *r, int *marker, int *max_parts)
static int lp_scan_staged_parts (ngx_http_request_t *r, brix_vfs_ctx_t *vctx, const char *mpu_dir, ngx_http_s3_loc_conf_t *cf, mpu_part_entry_t *parts)
static ngx_int_t lp_render_xml (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const lp_page_t *page)
ngx_int_t s3_handle_list_parts (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, const char *key_str)
Function Documentation
lp_parse_query()
static void lp_parse_query (ngx_http_request_t * r, int * marker, int * max_parts) static
Definition at line 92 of file multipart_complete_list_parts.c.
References MPU_MAX_PART_NUMBER, and s3_get_query_param().
Referenced by s3_handle_list_parts().
lp_render_xml()
static ngx_int_t lp_render_xml (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const lp_page_t * page) static
Definition at line 228 of file multipart_complete_list_parts.c.
References brix_format_iso8601(), brix_http_send_xml_buffer(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, ngx_http_s3_loc_conf_t::bucket, lp_page_t::end_idx, lp_page_t::key_str, lp_page_t::max_parts, ngx_memcpy, lp_page_t::nparts, lp_page_t::part_number_marker, lp_page_t::parts, lp_page_t::start_idx, lp_page_t::upload_id, XML_APPEND, and XML_APPEND_ELEM.
Referenced by s3_handle_list_parts().
lp_scan_staged_parts()
static int lp_scan_staged_parts (ngx_http_request_t * r, brix_vfs_ctx_t * vctx, const char * mpu_dir, ngx_http_s3_loc_conf_t * cf, mpu_part_entry_t * parts) static
Definition at line 137 of file multipart_complete_list_parts.c.
References brix_vfs_closedir(), brix_vfs_opendir_quiet(), brix_vfs_probe(), brix_vfs_readdir_kind(), brix_vfs_stat_t::is_regular, MPU_MAX_PART_NUMBER, mpu_part_entry_cmp(), brix_vfs_stat_t::mtime, mpu_part_entry_t::mtime, name, mpu_part_entry_t::part_num, PATH_MAX, s3_build_vfs_ctx(), brix_vfs_stat_t::size, and mpu_part_entry_t::size.
Referenced by s3_handle_list_parts().
mpu_part_entry_cmp()
static int mpu_part_entry_cmp (const void * a, const void * b) static
Definition at line 72 of file multipart_complete_list_parts.c.
Referenced by lp_scan_staged_parts().
s3_handle_list_parts()
ngx_int_t s3_handle_list_parts (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, const char * key_str)
Definition at line 314 of file multipart_complete_list_parts.c.
References BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, brix_vfs_probe(), lp_page_t::end_idx, brix_vfs_stat_t::is_directory, lp_page_t::key_str, lp_parse_query(), lp_render_xml(), lp_scan_staged_parts(), lp_page_t::max_parts, MPU_MAX_PART_NUMBER, mpu_validate_upload_id(), lp_page_t::nparts, lp_page_t::part_number_marker, lp_page_t::parts, PATH_MAX, s3_build_vfs_ctx(), s3_get_mpu_dir(), s3_get_query_param(), s3_send_xml_error(), lp_page_t::start_idx, and lp_page_t::upload_id.
Referenced by s3_dispatch_object_get().