nginx-xrootd: src/protocols/s3/multipart_complete_upload_part_copy.c File Reference
multipart_complete_upload_part_copy.c File Reference
#include "s3.h"
#include "multipart_internal.h"
#include "fs/vfs/vfs.h"
#include "core/http/http_headers.h"
#include "fs/backend/sd.h"
#include <string.h>
#include "core/compat/cstr.h"
Data Structures
struct s3_upcp_req_t
Functions
static const char * s3_find_request_header_value (ngx_http_request_t *r, const char *name, size_t name_len)
static const char * s3_copy_source_key (const char *copy_src_hdr)
static ngx_int_t s3_resolve_copy_source (const s3_upcp_req_t *req, const char *src_key, char *src_fs_path, size_t src_fs_path_sz, brix_vfs_ctx_t *sctx)
static ngx_int_t s3_resolve_part_target (const s3_upcp_req_t *req, char *part_path, size_t part_path_sz)
static int s3_copy_bytes (int src_fd, int dst_fd, char *iobuf, size_t iobuf_sz)
static ngx_int_t s3_send_copy_part_result (ngx_http_request_t *r, const struct stat *part_sb)
ngx_int_t s3_handle_upload_part_copy (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, const char *upload_id, int part_num)
Function Documentation
s3_copy_bytes()
static int s3_copy_bytes (int src_fd, int dst_fd, char * iobuf, size_t iobuf_sz) static
Definition at line 218 of file multipart_complete_upload_part_copy.c.
References brix_sd_posix_wrap().
Referenced by s3_handle_upload_part_copy().
s3_copy_source_key()
static const char * s3_copy_source_key (const char * copy_src_hdr) static
Definition at line 84 of file multipart_complete_upload_part_copy.c.
Referenced by s3_handle_upload_part_copy().
s3_find_request_header_value()
static const char * s3_find_request_header_value (ngx_http_request_t * r, const char * name, size_t name_len) static
Definition at line 53 of file multipart_complete_upload_part_copy.c.
References brix_http_find_header(), brix_pstrdup_z(), and name.
Referenced by s3_handle_upload_part_copy().
s3_handle_upload_part_copy()
ngx_int_t s3_handle_upload_part_copy (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, const char * upload_id, int part_num)
Definition at line 296 of file multipart_complete_upload_part_copy.c.
References BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, brix_vfs_close(), brix_vfs_file_fd(), BRIX_VFS_O_READ, brix_vfs_open(), brix_vfs_open_fd(), brix_vfs_unlink_path(), s3_upcp_req_t::cf, close(), ngx_http_s3_loc_conf_t::common, s3_upcp_req_t::fs_path, fstat(), s3_upcp_req_t::part_num, PATH_MAX, s3_upcp_req_t::r, ngx_http_brix_shared_conf_t::root_canon, s3_copy_bytes(), s3_copy_source_key(), s3_find_request_header_value(), s3_resolve_copy_source(), s3_resolve_part_target(), s3_send_copy_part_result(), s3_send_xml_error(), stat(), and s3_upcp_req_t::upload_id.
Referenced by s3_prepare_upload_part().
s3_resolve_copy_source()
static ngx_int_t s3_resolve_copy_source (const s3_upcp_req_t * req, const char * src_key, char * src_fs_path, size_t src_fs_path_sz, brix_vfs_ctx_t * sctx) static
Definition at line 116 of file multipart_complete_upload_part_copy.c.
References brix_vfs_probe(), s3_upcp_req_t::cf, ngx_http_s3_loc_conf_t::common, brix_vfs_stat_t::is_regular, s3_upcp_req_t::r, ngx_http_brix_shared_conf_t::root_canon, s3_build_vfs_ctx(), and s3_send_xml_error().
Referenced by s3_handle_upload_part_copy().
s3_resolve_part_target()
static ngx_int_t s3_resolve_part_target (const s3_upcp_req_t * req, char * part_path, size_t part_path_sz) static
Definition at line 167 of file multipart_complete_upload_part_copy.c.
References brix_vfs_probe(), s3_upcp_req_t::cf, s3_upcp_req_t::fs_path, mpu_validate_upload_id(), s3_upcp_req_t::part_num, PATH_MAX, s3_upcp_req_t::r, s3_build_vfs_ctx(), s3_get_mpu_dir(), s3_send_xml_error(), and s3_upcp_req_t::upload_id.
Referenced by s3_handle_upload_part_copy().
s3_send_copy_part_result()
static ngx_int_t s3_send_copy_part_result (ngx_http_request_t * r, const struct stat * part_sb) static
Definition at line 262 of file multipart_complete_upload_part_copy.c.
References brix_format_iso8601(), brix_http_send_xml_buffer(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, ngx_memcpy, and s3_etag().
Referenced by s3_handle_upload_part_copy().