nginx-xrootd: src/protocols/root/write/mv.c File Reference
mv.c File Reference
#include "core/ngx_brix_module.h"
#include "core/compat/error_mapping.h"
#include "protocols/root/path/op_path.h"
#include "fs/vfs/vfs.h"
#include "fs/vfs/vfs_backend_registry.h"
Data Structures
struct mv_req_t
Functions
static ngx_int_t mv_fail (brix_ctx_t *ctx, ngx_connection_t *c, const char *path, int kxr, const char *msg)
static ngx_int_t mv_parse_paths (brix_ctx_t *ctx, ngx_connection_t *c, mv_req_t *mv)
static void mv_bind_vfs (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *path, brix_vfs_ctx_t *vctx)
static ngx_int_t mv_dst_slash_precheck (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, mv_req_t *mv)
static void mv_make_dst_parents (ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *dst_buf)
static ngx_int_t mv_execute (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, mv_req_t *mv)
ngx_int_t brix_handle_mv (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_handle_mv()
ngx_int_t brix_handle_mv (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 359 of file mv.c.
References BRIX_AOP_INSERT, BRIX_AOP_RENAME, BRIX_AUTH_DELETE, brix_auth_gate_op(), BRIX_AUTH_UPDATE, BRIX_OP_MV, BRIX_PATH_EXISTING, brix_path_resolve_beneath(), BRIX_PATH_WRITE, BRIX_RETURN_ERR, BRIX_RETURN_OK, c, mv_req_t::dst_buf, mv_req_t::dst_resolved, kXR_NotFound, mv_dst_slash_precheck(), mv_execute(), mv_make_dst_parents(), mv_parse_paths(), mv_req_t::src_buf, mv_req_t::src_resolved, and brix_ctx_t::write_rc.
mv_bind_vfs()
static void mv_bind_vfs (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * path, brix_vfs_ctx_t * vctx) static
Definition at line 150 of file mv.c.
References BRIX_PROTO_ROOT, brix_root_vfs_bind_deleg(), brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), c, brix_ctx_t::identity, and brix_vfs_ctx_t::pool.
Referenced by mv_dst_slash_precheck(), and mv_execute().
mv_dst_slash_precheck()
static ngx_int_t mv_dst_slash_precheck (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, mv_req_t * mv) static
Definition at line 180 of file mv.c.
References brix_kxr_from_errno(), brix_vfs_probe(), c, mv_req_t::dst_buf, brix_vfs_stat_t::is_directory, mv_bind_vfs(), mv_fail(), mv_req_t::src_buf, and mv_req_t::src_resolved.
Referenced by brix_handle_mv().
mv_execute()
static ngx_int_t mv_execute (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, mv_req_t * mv) static
Definition at line 278 of file mv.c.
References brix_kxr_from_errno(), brix_vfs_probe(), brix_vfs_rename(), c, mv_req_t::dst_resolved, brix_path_result_t::is_confined, brix_vfs_stat_t::is_directory, kXR_ArgTooLong, kXR_FSError, kXR_isDirectory, kXR_ItExists, kXR_NoSpace, kXR_NotAuthorized, kXR_NotFound, mv_bind_vfs(), mv_fail(), brix_path_result_t::resolved, and mv_req_t::src_resolved.
Referenced by brix_handle_mv().
mv_fail()
static ngx_int_t mv_fail (brix_ctx_t * ctx, ngx_connection_t * c, const char * path, int kxr, const char * msg) static
Definition at line 43 of file mv.c.
References brix_log_access(), BRIX_OP_ERR, BRIX_OP_MV, brix_send_error(), c, and brix_ctx_t::write_rc.
Referenced by mv_dst_slash_precheck(), and mv_execute().
mv_make_dst_parents()
static void mv_make_dst_parents (ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * dst_buf) static
Definition at line 224 of file mv.c.
References brix_beneath_full_path(), BRIX_MAX_PATH, brix_mkdir_recursive_policy(), brix_vfs_backend_mkpath(), brix_vfs_backend_resolve(), c, ngx_memcpy, and PATH_MAX.
Referenced by brix_handle_mv().
mv_parse_paths()
static ngx_int_t mv_parse_paths (brix_ctx_t * ctx, ngx_connection_t * c, mv_req_t * mv) static
Definition at line 73 of file mv.c.
References xrdw_twopath_req_t::arg1len, brix_extract_path(), brix_send_error(), c, brix_ctx_recv_t::cur_dlen, mv_req_t::dst_buf, brix_ctx_recv_t::hdr_buf, kXR_ArgInvalid, kXR_ArgMissing, brix_ctx_recv_t::payload, brix_ctx_t::recv, mv_req_t::src_buf, brix_ctx_t::write_rc, and xrdw_twopath_req_unpack().
Referenced by brix_handle_mv().