nginx-xrootd: src/core/compat/namespace_ops_internal.h File Reference
namespace_ops_internal.h File Reference
#include "namespace_ops.h"
Functions
const char * ns_rel (const char *root_canon, const char *abspath, int *rootfd_out)
void ns_set_err (brix_ns_result_t *res, int err)
Function Documentation
ns_rel()
const char * ns_rel (const char * root_canon, const char * abspath, int * rootfd_out)
Definition at line 48 of file namespace_ops.c.
References brix_beneath_open_root(), and brix_beneath_strip_root().
Referenced by brix_ns_delete(), brix_ns_local_copy(), brix_ns_mkdir(), and brix_ns_rename().
ns_set_err()
void ns_set_err (brix_ns_result_t * res, int err)
Definition at line 105 of file namespace_ops.c.
References errno_to_ns_status(), brix_ns_result_t::status, and brix_ns_result_t::sys_errno.
Referenced by brix_ns_delete(), brix_ns_local_copy(), ns_copy_finalize(), ns_copy_open_dst(), ns_copy_validate(), ns_delete_probe(), and ns_delete_remove().