nginx-xrootd: src/core/compat/namespace_ops.h File Reference
namespace_ops.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include "ns_status.h"
Data Structures
struct brix_ns_result_t
struct brix_ns_delete_opts_t
struct brix_ns_copy_opts_t
Functions
brix_ns_result_t brix_ns_delete (ngx_log_t *log, const char *root_canon, const char *path, const brix_ns_delete_opts_t *opts)
brix_ns_result_t brix_ns_mkdir (ngx_log_t *log, const char *root_canon, const char *path, mode_t mode, ngx_flag_t recursive)
brix_ns_result_t brix_ns_rename (ngx_log_t *log, const char *root_canon, const char *src, const char *dst, ngx_flag_t overwrite_dirs)
brix_ns_result_t brix_ns_local_copy (ngx_log_t *log, const char *root_canon, const char *src, const char *dst, const brix_ns_copy_opts_t *opts)
void brix_ns_copy_fattrs (ngx_log_t *log, const char *src, const char *dst)
void brix_xattr_copy_by_prefix (ngx_log_t *log, const char *src, const char *dst, const char *prefix, size_t prefix_len, size_t value_max)
Function Documentation
brix_ns_copy_fattrs()
void brix_ns_copy_fattrs (ngx_log_t * log, const char * src, const char * dst)
Definition at line 149 of file namespace_ops.c.
References BRIX_FATTR_MAX_VBUF, BRIX_FATTR_XKEY_PFX, BRIX_FATTR_XKEY_PFX_LEN, brix_xattr_copy_by_prefix(), and log.
Referenced by brix_ns_local_copy(), brix_vfs_copyfile(), brix_vfs_copytree(), and webdav_copy_collection_execute().
brix_ns_delete()
brix_ns_result_t brix_ns_delete (ngx_log_t * log, const char * root_canon, const char * path, const brix_ns_delete_opts_t * opts)
Definition at line 157 of file namespace_ops.c.
References brix_fs_dir_is_empty(), brix_fs_remove_tree_confined(), brix_lstat_beneath(), BRIX_NS_NOT_EMPTY, BRIX_NS_OK, brix_unlink_beneath(), close(), errno_to_ns_status(), brix_ns_result_t::existed, brix_ns_delete_opts_t::idempotent_missing, log, ns_rel(), brix_ns_delete_opts_t::recursive, brix_ns_delete_opts_t::require_directory, brix_ns_delete_opts_t::require_empty_dir, stat(), brix_ns_result_t::status, brix_ns_result_t::sys_errno, and brix_ns_result_t::was_dir.
Referenced by brix_vfs_delete(), and sd_posix_unlink().
brix_ns_local_copy()
brix_ns_result_t brix_ns_local_copy (ngx_log_t * log, const char * root_canon, const char * src, const char * dst, const brix_ns_copy_opts_t * opts)
Definition at line 341 of file namespace_ops.c.
References brix_beneath_strip_root(), brix_copy_range(), BRIX_NS_CONFLICT, brix_ns_copy_fattrs(), BRIX_NS_EXISTS, BRIX_NS_OK, brix_open_beneath(), brix_staged_abort(), brix_staged_commit(), brix_staged_open(), brix_stat_beneath(), close(), brix_ns_result_t::created, errno_to_ns_status(), brix_ns_result_t::existed, brix_staged_file_t::fd, log, ns_rel(), brix_ns_copy_opts_t::overwrite, brix_ns_copy_opts_t::overwrite_dirs, brix_ns_copy_opts_t::preserve_xattrs, brix_ns_copy_opts_t::staged_commit, stat(), brix_ns_result_t::status, brix_ns_result_t::sys_errno, brix_staged_file_t::tmp_path, and brix_ns_result_t::was_dir.
Referenced by brix_vfs_copy(), and sd_posix_server_copy().
brix_ns_mkdir()
brix_ns_result_t brix_ns_mkdir (ngx_log_t * log, const char * root_canon, const char * path, mode_t mode, ngx_flag_t recursive)
Definition at line 239 of file namespace_ops.c.
References brix_mkdir_beneath(), brix_mkdir_recursive_beneath(), BRIX_NS_OK, close(), brix_ns_result_t::created, errno_to_ns_status(), log, mode, ns_rel(), brix_ns_result_t::status, and brix_ns_result_t::sys_errno.
Referenced by brix_vfs_mkdir(), and sd_posix_mkdir().
brix_ns_rename()
brix_ns_result_t brix_ns_rename (ngx_log_t * log, const char * root_canon, const char * src, const char * dst, ngx_flag_t overwrite_dirs)
Definition at line 282 of file namespace_ops.c.
References brix_beneath_strip_root(), brix_fs_remove_tree_confined(), BRIX_NS_EXISTS, BRIX_NS_OK, brix_rename_beneath(), brix_stat_beneath(), close(), errno_to_ns_status(), brix_ns_result_t::existed, log, ns_rel(), stat(), brix_ns_result_t::status, brix_ns_result_t::sys_errno, and brix_ns_result_t::was_dir.
Referenced by brix_vfs_rename(), brix_vfs_rename_path(), and sd_posix_rename().
brix_xattr_copy_by_prefix()
void brix_xattr_copy_by_prefix (ngx_log_t * log, const char * src, const char * dst, const char * prefix, size_t prefix_len, size_t value_max)
Definition at line 102 of file namespace_ops.c.
References log.
Referenced by brix_ns_copy_fattrs(), and webdav_dead_props_copy().