nginx-xrootd: src/core/compat/namespace_ops.c File Reference
namespace_ops.c File Reference
#include "namespace_ops.h"
#include "namespace_ops_internal.h"
#include "fs/path/path.h"
#include "fs/path/beneath.h"
#include "fs_walk.h"
#include <errno.h>
#include <string.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
Functions
const char * ns_rel (const char *root_canon, const char *abspath, int *rootfd_out)
static brix_ns_status_t errno_to_ns_status (int err)
void ns_set_err (brix_ns_result_t *res, int err)
static ngx_flag_t ns_delete_probe (int rootfd, const char *rel, const brix_ns_delete_opts_t *opts, brix_ns_result_t *res)
static void ns_delete_remove (ngx_log_t *log, const char *root_canon, const char *path, int rootfd, const char *rel, const brix_ns_delete_opts_t *opts, brix_ns_result_t *res)
brix_ns_result_t brix_ns_delete (ngx_log_t *log, const char *root_canon, const char *path, const brix_ns_delete_opts_t *opts)
brix_ns_result_t brix_ns_mkdir (ngx_log_t *log, const char *root_canon, const char *path, mode_t mode, ngx_flag_t recursive)
brix_ns_result_t brix_ns_rename (ngx_log_t *log, const char *root_canon, const char *src, const char *dst, ngx_flag_t overwrite_dirs)
Function Documentation
brix_ns_delete()
brix_ns_result_t brix_ns_delete (ngx_log_t * log, const char * root_canon, const char * path, const brix_ns_delete_opts_t * opts)
Definition at line 205 of file namespace_ops.c.
References close(), log, ns_delete_probe(), ns_delete_remove(), ns_rel(), and ns_set_err().
Referenced by brix_vfs_delete_via_namespace(), and sd_posix_unlink().
brix_ns_mkdir()
brix_ns_result_t brix_ns_mkdir (ngx_log_t * log, const char * root_canon, const char * path, mode_t mode, ngx_flag_t recursive)
Definition at line 232 of file namespace_ops.c.
References brix_mkdir_beneath(), brix_mkdir_recursive_beneath(), BRIX_NS_OK, close(), brix_ns_result_t::created, errno_to_ns_status(), log, ns_rel(), brix_ns_result_t::status, and brix_ns_result_t::sys_errno.
Referenced by brix_vfs_mkdir(), and sd_posix_mkdir().
brix_ns_rename()
brix_ns_result_t brix_ns_rename (ngx_log_t * log, const char * root_canon, const char * src, const char * dst, ngx_flag_t overwrite_dirs)
Definition at line 275 of file namespace_ops.c.
References brix_beneath_strip_root(), brix_fs_remove_tree_confined(), BRIX_NS_EXISTS, BRIX_NS_OK, brix_rename_beneath(), brix_stat_beneath(), close(), errno_to_ns_status(), brix_ns_result_t::existed, log, ns_rel(), stat(), brix_ns_result_t::status, brix_ns_result_t::sys_errno, and brix_ns_result_t::was_dir.
Referenced by brix_vfs_rename(), brix_vfs_rename_path(), and sd_posix_rename().
errno_to_ns_status()
static brix_ns_status_t errno_to_ns_status (int err) static
Definition at line 71 of file namespace_ops.c.
References BRIX_NS_CONFLICT, BRIX_NS_DENIED, BRIX_NS_EXISTS, BRIX_NS_IO_ERROR, BRIX_NS_NO_SPACE, BRIX_NS_NOT_EMPTY, BRIX_NS_NOT_FOUND, BRIX_NS_OK, and BRIX_NS_TOO_LONG.
Referenced by brix_ns_mkdir(), brix_ns_rename(), and ns_set_err().
ns_delete_probe()
static ngx_flag_t ns_delete_probe (int rootfd, const char * rel, const brix_ns_delete_opts_t * opts, brix_ns_result_t * res) static
Definition at line 126 of file namespace_ops.c.
References brix_lstat_beneath(), BRIX_NS_OK, brix_ns_result_t::existed, brix_ns_delete_opts_t::idempotent_missing, ns_set_err(), brix_ns_delete_opts_t::require_directory, stat(), brix_ns_result_t::status, and brix_ns_result_t::was_dir.
Referenced by brix_ns_delete().
ns_delete_remove()
static void ns_delete_remove (ngx_log_t * log, const char * root_canon, const char * path, int rootfd, const char * rel, const brix_ns_delete_opts_t * opts, brix_ns_result_t * res) static
Definition at line 172 of file namespace_ops.c.
References brix_fs_dir_is_empty(), brix_fs_remove_tree_confined(), BRIX_NS_NOT_EMPTY, BRIX_NS_OK, brix_unlink_beneath(), log, ns_set_err(), brix_ns_delete_opts_t::recursive, brix_ns_delete_opts_t::require_empty_dir, brix_ns_result_t::status, and brix_ns_result_t::was_dir.
Referenced by brix_ns_delete().
ns_rel()
const char * ns_rel (const char * root_canon, const char * abspath, int * rootfd_out)
Definition at line 48 of file namespace_ops.c.
References brix_beneath_open_root(), and brix_beneath_strip_root().
Referenced by brix_ns_delete(), brix_ns_local_copy(), brix_ns_mkdir(), and brix_ns_rename().
ns_set_err()
void ns_set_err (brix_ns_result_t * res, int err)
Definition at line 105 of file namespace_ops.c.
References errno_to_ns_status(), brix_ns_result_t::status, and brix_ns_result_t::sys_errno.
Referenced by brix_ns_delete(), brix_ns_local_copy(), ns_copy_finalize(), ns_copy_open_dst(), ns_copy_validate(), ns_delete_probe(), and ns_delete_remove().