nginx-xrootd: src/protocols/webdav/namespace.c File Reference
namespace.c File Reference
#include "webdav.h"
#include "core/compat/fs_walk.h"
#include "fs/vfs/vfs.h"
#include "protocols/shared/backend_async_http.h"
#include <errno.h>
#include <sys/stat.h>
#include <unistd.h>
Functions
static void webdav_ns_vfs_ctx_init (ngx_http_request_t *r, const char *path, brix_vfs_ctx_t *vctx)
ngx_int_t webdav_delete_path_recursive (ngx_log_t *log, const char *root_canon, const char *path)
static ngx_int_t webdav_delete_respond (ngx_http_request_t *r, int op_errno)
static void webdav_delete_async_render (ngx_http_request_t *r, void *ctx, int op_errno)
ngx_int_t webdav_handle_delete (ngx_http_request_t *r)
ngx_int_t webdav_handle_mkcol (ngx_http_request_t *r)
Function Documentation
webdav_delete_async_render()
static void webdav_delete_async_render (ngx_http_request_t * r, void * ctx, int op_errno) static
Definition at line 93 of file namespace.c.
References webdav_delete_respond(), and webdav_metrics_finalize_request().
Referenced by webdav_handle_delete().
webdav_delete_path_recursive()
ngx_int_t webdav_delete_path_recursive (ngx_log_t * log, const char * root_canon, const char * path)
Definition at line 56 of file namespace.c.
References brix_fs_remove_tree_confined(), and log.
Referenced by webdav_copy_collection_commit(), webdav_copy_collection_stage(), and webdav_copy_do_file().
webdav_delete_respond()
static ngx_int_t webdav_delete_respond (ngx_http_request_t * r, int op_errno) static
Definition at line 70 of file namespace.c.
References webdav_send_no_body().
Referenced by webdav_delete_async_render(), and webdav_handle_delete().
webdav_handle_delete()
ngx_int_t webdav_handle_delete (ngx_http_request_t * r)
Definition at line 109 of file namespace.c.
References ngx_http_brix_shared_conf_t::backend_async, brix_baq_http_try(), BRIX_BAQ_RMDIR, BRIX_BAQ_UNLINK, brix_vfs_rmdir(), brix_vfs_unlink(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_module, op, ngx_http_brix_shared_conf_t::root_canon, stat(), webdav_check_locks_tree(), webdav_delete_async_render(), webdav_delete_respond(), WEBDAV_MAX_PATH, webdav_ns_vfs_ctx_init(), and webdav_resolve_stat().
Referenced by webdav_dispatch_core_method().
webdav_handle_mkcol()
ngx_int_t webdav_handle_mkcol (ngx_http_request_t * r)
Definition at line 164 of file namespace.c.
References brix_vfs_mkdir(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), ngx_http_brix_shared_conf_t::root_canon, webdav_check_locks(), WEBDAV_MAX_PATH, webdav_ns_vfs_ctx_init(), and webdav_send_no_body().
Referenced by webdav_dispatch_copy_move_props().
webdav_ns_vfs_ctx_init()
static void webdav_ns_vfs_ctx_init (ngx_http_request_t * r, const char * path, brix_vfs_ctx_t * vctx) static
Definition at line 20 of file namespace.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_WEBDAV, brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, brix_vfs_ctx_t::pool, ngx_http_brix_shared_conf_t::root_canon, ngx_http_brix_shared_conf_t::storage_credential_dir, ngx_http_brix_shared_conf_t::storage_credential_fallback, and webdav_vfs_bind_deleg().
Referenced by webdav_handle_delete(), and webdav_handle_mkcol().