nginx-xrootd: src/core/compat/namespace_ops_copy.c File Reference
namespace_ops_copy.c File Reference
#include "namespace_ops.h"
#include "namespace_ops_internal.h"
#include "fs/path/path.h"
#include "fs/path/beneath.h"
#include "protocols/root/fattr/ngx_brix_fattr.h"
#include "fs_walk.h"
#include "copy_range.h"
#include "staged_file.h"
#include <errno.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/xattr.h>
#include <fcntl.h>
#include <unistd.h>
Functions
void brix_xattr_copy_by_prefix (ngx_log_t *log, const char *src, const char *dst, const char *prefix, size_t prefix_len, size_t value_max)
void brix_ns_copy_fattrs (ngx_log_t *log, const char *src, const char *dst)
static ngx_flag_t ns_copy_validate (int rootfd, const char *src_rel, const char *dst_rel, const brix_ns_copy_opts_t *opts, struct stat *ssb, brix_ns_result_t *res)
static ngx_flag_t ns_copy_open_dst (ngx_log_t *log, int rootfd, const char *root_canon, const char *dst, const char *dst_rel, mode_t mode, const brix_ns_copy_opts_t *opts, brix_staged_file_t *staged, int *dst_fd_out, ngx_flag_t *use_staging_out, brix_ns_result_t *res)
static void ns_copy_finalize (ngx_log_t *log, const char *root_canon, const char *src, const char *dst, int src_fd, int dst_fd, const struct stat *ssb, const brix_ns_copy_opts_t *opts, ngx_flag_t use_staging, brix_staged_file_t *staged, brix_ns_result_t *res)
brix_ns_result_t brix_ns_local_copy (ngx_log_t *log, const char *root_canon, const char *src, const char *dst, const brix_ns_copy_opts_t *opts)
Function Documentation
brix_ns_copy_fattrs()
void brix_ns_copy_fattrs (ngx_log_t * log, const char * src, const char * dst)
Definition at line 104 of file namespace_ops_copy.c.
References BRIX_FATTR_MAX_VBUF, BRIX_FATTR_XKEY_PFX, BRIX_FATTR_XKEY_PFX_LEN, brix_xattr_copy_by_prefix(), and log.
Referenced by brix_vfs_copyfile(), ns_copy_finalize(), vfs_copytree_subdir(), and webdav_copy_collection_stage().
brix_ns_local_copy()
brix_ns_result_t brix_ns_local_copy (ngx_log_t * log, const char * root_canon, const char * src, const char * dst, const brix_ns_copy_opts_t * opts)
Definition at line 277 of file namespace_ops_copy.c.
References brix_beneath_strip_root(), brix_open_beneath(), close(), log, ns_copy_finalize(), ns_copy_open_dst(), ns_copy_validate(), ns_rel(), ns_set_err(), and stat().
Referenced by brix_vfs_copy_ns(), and sd_posix_server_copy().
brix_xattr_copy_by_prefix()
void brix_xattr_copy_by_prefix (ngx_log_t * log, const char * src, const char * dst, const char * prefix, size_t prefix_len, size_t value_max)
Definition at line 57 of file namespace_ops_copy.c.
References log.
Referenced by brix_ns_copy_fattrs(), and webdav_dead_props_copy().
ns_copy_finalize()
static void ns_copy_finalize (ngx_log_t * log, const char * root_canon, const char * src, const char * dst, int src_fd, int dst_fd, const struct stat * ssb, const brix_ns_copy_opts_t * opts, ngx_flag_t use_staging, brix_staged_file_t * staged, brix_ns_result_t * res) static
Definition at line 223 of file namespace_ops_copy.c.
References brix_copy_range(), brix_ns_copy_fattrs(), BRIX_NS_OK, brix_staged_abort(), brix_staged_commit(), close(), brix_ns_result_t::created, log, ns_set_err(), brix_ns_copy_opts_t::preserve_xattrs, brix_ns_result_t::status, and brix_staged_file_t::tmp_path.
Referenced by brix_ns_local_copy().
ns_copy_open_dst()
static ngx_flag_t ns_copy_open_dst (ngx_log_t * log, int rootfd, const char * root_canon, const char * dst, const char * dst_rel, mode_t mode, const brix_ns_copy_opts_t * opts, brix_staged_file_t * staged, int * dst_fd_out, ngx_flag_t * use_staging_out, brix_ns_result_t * res) static
Definition at line 174 of file namespace_ops_copy.c.
References brix_open_beneath(), brix_staged_open(), brix_staged_file_t::fd, log, ns_set_err(), brix_staged_open_req_t::root_canon, and brix_ns_copy_opts_t::staged_commit.
Referenced by brix_ns_local_copy().
ns_copy_validate()
static ngx_flag_t ns_copy_validate (int rootfd, const char * src_rel, const char * dst_rel, const brix_ns_copy_opts_t * opts, struct stat * ssb, brix_ns_result_t * res) static
Definition at line 127 of file namespace_ops_copy.c.
References BRIX_NS_CONFLICT, BRIX_NS_EXISTS, brix_stat_beneath(), brix_ns_result_t::existed, ns_set_err(), brix_ns_copy_opts_t::overwrite, brix_ns_copy_opts_t::overwrite_dirs, stat(), brix_ns_result_t::status, and brix_ns_result_t::was_dir.
Referenced by brix_ns_local_copy().