nginx-xrootd: src/core/negcache/negcache.h File Reference
negcache.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
Data Structures
struct brix_negcache_conf_t
Functions
char * brix_negcache_set (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
ngx_int_t brix_negcache_configure (ngx_conf_t *cf)
unsigned brix_negcache_note_miss (struct brix_ctx_s *ctx, unsigned threshold, unsigned window_ms, unsigned backoff_s)
Function Documentation
brix_negcache_configure()
ngx_int_t brix_negcache_configure (ngx_conf_t * cf)
Definition at line 122 of file negcache.c.
References brix_shm_zone_size(), negcache_init_zone(), NEGCACHE_SLOTS, negcache_zone, and ngx_stream_brix_module.
Referenced by postconf_stage_waiter().
brix_negcache_note_miss()
unsigned brix_negcache_note_miss (struct brix_ctx_s * ctx, unsigned threshold, unsigned window_ms, unsigned backoff_s)
brix_negcache_set()
char * brix_negcache_set (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 76 of file negcache.c.
References brix_negcache_conf_t::backoff_s, brix_negcache_conf_t::threshold, and brix_negcache_conf_t::window_ms.