nginx-xrootd: src/net/cms/send.c File Reference
send.c File Reference
#include "cms_internal.h"
#include "frame_io.h"
#include "net/manager/registry.h"
#include <unistd.h>
Functions
static ngx_int_t ngx_brix_cms_send_frame (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, u_char code, u_char modifier, const u_char *payload, size_t payload_len)
ngx_int_t ngx_brix_cms_send_error (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, uint32_t ecode, const char *text)
ngx_int_t ngx_brix_cms_send_login (ngx_brix_cms_ctx_t *ctx)
ngx_int_t ngx_brix_cms_send_status (ngx_brix_cms_ctx_t *ctx)
ngx_int_t ngx_brix_cms_send_load (ngx_brix_cms_ctx_t *ctx)
ngx_int_t ngx_brix_cms_send_avail (ngx_brix_cms_ctx_t *ctx, uint32_t streamid)
ngx_int_t ngx_brix_cms_send_pong (ngx_brix_cms_ctx_t *ctx, uint32_t streamid)
uint32_t ngx_brix_cms_next_streamid (ngx_brix_cms_ctx_t *ctx)
ngx_int_t ngx_brix_cms_send_locate (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, const char *path)
ngx_int_t ngx_brix_cms_send_have (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, const char *path, size_t path_len)
Function Documentation
ngx_brix_cms_next_streamid()
uint32_t ngx_brix_cms_next_streamid (ngx_brix_cms_ctx_t * ctx)
Definition at line 336 of file send.c.
Referenced by brix_open_cms_locate(), brix_qcksum_manager_bounce(), locate_try_cms_parent(), and stat_manager_route().
ngx_brix_cms_send_avail()
ngx_int_t ngx_brix_cms_send_avail (ngx_brix_cms_ctx_t * ctx, uint32_t streamid)
Definition at line 284 of file send.c.
References brix_srv_aggregate_space(), CMS_RR_AVAIL, ngx_brix_cms_put_int(), ngx_brix_cms_send_frame(), and ngx_brix_cms_stat_space().
Referenced by cms_frame_space().
ngx_brix_cms_send_error()
ngx_int_t ngx_brix_cms_send_error (ngx_brix_cms_ctx_t * ctx, uint32_t streamid, uint32_t ecode, const char * text)
Definition at line 32 of file send.c.
References CMS_RSP_ERROR, ngx_brix_cms_put32(), ngx_brix_cms_send_frame(), and ngx_memcpy.
Referenced by cms_forward_via_driver(), cms_forward_via_posix(), and cms_node_exec_forward().
ngx_brix_cms_send_frame()
static ngx_int_t ngx_brix_cms_send_frame (ngx_brix_cms_ctx_t * ctx, uint32_t streamid, u_char code, u_char modifier, const u_char * payload, size_t payload_len) static
Definition at line 18 of file send.c.
References brix_cms_send_frame(), and code.
Referenced by ngx_brix_cms_send_avail(), ngx_brix_cms_send_error(), ngx_brix_cms_send_have(), ngx_brix_cms_send_load(), ngx_brix_cms_send_locate(), ngx_brix_cms_send_login(), ngx_brix_cms_send_pong(), and ngx_brix_cms_send_status().
ngx_brix_cms_send_have()
ngx_int_t ngx_brix_cms_send_have (ngx_brix_cms_ctx_t * ctx, uint32_t streamid, const char * path, size_t path_len)
Definition at line 384 of file send.c.
References BRIX_SRV_MAX_PATHS, CMS_HAVE_ONLINE, CMS_MOD_RAW, CMS_RR_HAVE, ngx_brix_cms_send_frame(), and ngx_memcpy.
Referenced by cms_frame_state().
ngx_brix_cms_send_load()
ngx_int_t ngx_brix_cms_send_load (ngx_brix_cms_ctx_t * ctx)
Definition at line 227 of file send.c.
References brix_srv_aggregate_space(), CMS_RR_LOAD, ngx_brix_cms_put16(), ngx_brix_cms_put_int(), ngx_brix_cms_send_frame(), and ngx_brix_cms_stat_space().
Referenced by ngx_brix_cms_timer(), and ngx_brix_cms_write_handler().
ngx_brix_cms_send_locate()
ngx_int_t ngx_brix_cms_send_locate (ngx_brix_cms_ctx_t * ctx, uint32_t streamid, const char * path)
Definition at line 356 of file send.c.
References BRIX_SRV_MAX_PATHS, CMS_RR_LOCATE, ngx_brix_cms_send_frame(), and ngx_memcpy.
Referenced by brix_open_cms_locate(), brix_qcksum_manager_bounce(), locate_try_cms_parent(), and stat_manager_route().
ngx_brix_cms_send_login()
ngx_int_t ngx_brix_cms_send_login (ngx_brix_cms_ctx_t * ctx)
Definition at line 64 of file send.c.
References brix_srv_aggregate_space(), CMS_LOGIN_MODE, CMS_LOGIN_MODE_MANAGER, CMS_LOGIN_VERSION, CMS_RR_LOGIN, ngx_brix_cms_export_paths(), NGX_BRIX_CMS_MIN_FREE_MB, ngx_brix_cms_put_int(), ngx_brix_cms_put_short(), ngx_brix_cms_put_string(), ngx_brix_cms_send_frame(), ngx_brix_cms_stat_space(), and ngx_memcpy.
Referenced by ngx_brix_cms_write_handler().
ngx_brix_cms_send_pong()
ngx_int_t ngx_brix_cms_send_pong (ngx_brix_cms_ctx_t * ctx, uint32_t streamid)
Definition at line 321 of file send.c.
References CMS_RR_PONG, and ngx_brix_cms_send_frame().
Referenced by cms_frame_ping().
ngx_brix_cms_send_status()
ngx_int_t ngx_brix_cms_send_status (ngx_brix_cms_ctx_t * ctx)
Definition at line 209 of file send.c.
References CMS_RR_STATUS, CMS_ST_NOSTAGE, CMS_ST_RESUME, and ngx_brix_cms_send_frame().
Referenced by cms_frame_update(), and ngx_brix_cms_write_handler().