nginx-xrootd: src/net/upstream/bootstrap.c File Reference
bootstrap.c File Reference
#include "upstream_internal.h"
#include "protocols/root/protocol/bootstrap_pack.h"
#include <stdio.h>
#include <ctype.h>
#include <errno.h>
Functions
void brix_upstream_build_bootstrap (u_char *buf)
void brix_upstream_build_login (ClientLoginRequest *req)
static void brix_upstream_continue_auth (brix_upstream_t *up)
void brix_upstream_handle_bootstrap_response (brix_upstream_t *up)
Variables
static const uint8_t brix_upstream_streamid [2] = { 0, 1 }
Function Documentation
brix_upstream_build_bootstrap()
void brix_upstream_build_bootstrap (u_char * buf)
Definition at line 32 of file bootstrap.c.
References brix_upstream_streamid, kXR_ver005, xrd_pack_handshake(), xrd_pack_login_request(), and xrd_pack_protocol_request().
Referenced by brix_hc_start(), brix_mir_start(), brix_upstream_start(), and wmir_start().
brix_upstream_build_login()
void brix_upstream_build_login (ClientLoginRequest * req)
Definition at line 55 of file bootstrap.c.
References brix_upstream_streamid, kXR_ver005, and xrd_pack_login_request().
brix_upstream_continue_auth()
static void brix_upstream_continue_auth (brix_upstream_t * up) static
Definition at line 78 of file bootstrap.c.
References brix_upstream_abort(), brix_upstream_send_token_auth(), ngx_stream_brix_module, ngx_stream_brix_srv_conf_t::upstream_token_file, and XRD_OBA_MAX_ROUNDS.
Referenced by brix_upstream_handle_bootstrap_response().
brix_upstream_handle_bootstrap_response()
void brix_upstream_handle_bootstrap_response (brix_upstream_t * up)
Definition at line 103 of file bootstrap.c.
References brix_upstream_abort(), brix_upstream_continue_auth(), brix_upstream_send_request(), kXR_authmore, kXR_gotoTLS, kXR_ok, ngx_stream_brix_module, ngx_stream_brix_srv_conf_t::upstream_tls, XRD_UP_BS_AUTH, XRD_UP_BS_DONE, XRD_UP_BS_HANDSHAKE, XRD_UP_BS_LOGIN, XRD_UP_BS_PROTOCOL, and XRD_UP_BS_TLS.
Referenced by brix_upstream_read_handler().
Variable Documentation
brix_upstream_streamid
const uint8_t brix_upstream_streamid[2] = { 0, 1 } static
Definition at line 29 of file bootstrap.c.
Referenced by brix_upstream_build_bootstrap(), and brix_upstream_build_login().