nginx-xrootd: src/net/cms/recv_frame.c File Reference
recv_frame.c File Reference
#include "cms_internal.h"
#include "recv_internal.h"
#include "node_ops.h"
#include "router.h"
#include "net/manager/pending.h"
#include "net/manager/registry.h"
#include "fs/path/beneath.h"
#include "fs/path/path.h"
#include "core/compat/net_target.h"
#include <errno.h>
#include <unistd.h>
Typedefs
typedef ngx_int_t(* cms_frame_handler_pt) (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, u_char code)
Functions
ngx_connection_t * brix_cms_client_conn_by_fd (int fd)
ngx_int_t brix_cms_wake_pending_session (ngx_log_t *log, uint32_t streamid, const char *host, uint16_t port)
static ngx_int_t cms_frame_ping (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, u_char code)
static ngx_int_t cms_frame_space (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, u_char code)
static ngx_int_t cms_frame_status (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, u_char code)
static ngx_int_t cms_frame_redirect (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, u_char code)
static ngx_int_t cms_state_extract_path (const u_char *payload, size_t plen, char *pathz, size_t pathz_size, size_t *pl_out)
static ngx_int_t cms_frame_state (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, u_char code)
static ngx_int_t cms_frame_forward (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, u_char code)
static ngx_int_t cms_frame_prepare (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, u_char code)
static ngx_int_t cms_frame_update (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, u_char code)
static ngx_int_t cms_frame_disc (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, u_char code)
ngx_int_t ngx_brix_cms_process_frame (ngx_brix_cms_ctx_t *ctx)
Variables
struct {
u_char code
cms_frame_handler_pt handler
} cms_frame_table []
Typedef Documentation
cms_frame_handler_pt
typedef ngx_int_t(* cms_frame_handler_pt) (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, u_char code)
Definition at line 379 of file recv_frame.c.
Function Documentation
brix_cms_client_conn_by_fd()
ngx_connection_t * brix_cms_client_conn_by_fd (int fd)
Definition at line 44 of file recv_frame.c.
References c.
Referenced by brix_cms_fanout_finalize(), and brix_cms_wake_pending_session().
brix_cms_wake_pending_session()
ngx_int_t brix_cms_wake_pending_session (ngx_log_t * log, uint32_t streamid, const char * host, uint16_t port)
Definition at line 80 of file recv_frame.c.
References brix_cms_client_conn_by_fd(), brix_net_host_chars_valid(), brix_pending_lookup(), brix_pending_remove(), brix_pending_unlock(), brix_sanitize_log_string(), brix_schedule_read_resume(), brix_send_redirect(), brix_pending_locate_t::client_streamid, brix_pending_locate_t::conn_fd, brix_pending_locate_t::conn_number, brix_ctx_recv_t::cur_streamid, host, log, ngx_stream_brix_module, port, brix_ctx_t::recv, brix_ctx_t::state, XRD_ST_REQ_HEADER, and XRD_ST_WAITING_CMS.
Referenced by cms_frame_redirect(), and cms_srv_frame_have().
cms_frame_disc()
static ngx_int_t cms_frame_disc (ngx_brix_cms_ctx_t * ctx, uint32_t streamid, u_char code) static
Definition at line 366 of file recv_frame.c.
References BRIX_SESS_END_SERVER, ngx_brix_cms_disconnect(), ngx_brix_cms_schedule_retry(), and ngx_brix_cms_set_end_hint().
cms_frame_forward()
static ngx_int_t cms_frame_forward (ngx_brix_cms_ctx_t * ctx, uint32_t streamid, u_char code) static
Definition at line 335 of file recv_frame.c.
References cms_node_exec_forward(), code, and NGX_BRIX_CMS_HDR_LEN.
cms_frame_ping()
static ngx_int_t cms_frame_ping (ngx_brix_cms_ctx_t * ctx, uint32_t streamid, u_char code) static
Definition at line 163 of file recv_frame.c.
References ngx_brix_cms_send_pong().
cms_frame_prepare()
static ngx_int_t cms_frame_prepare (ngx_brix_cms_ctx_t * ctx, uint32_t streamid, u_char code) static
Definition at line 346 of file recv_frame.c.
References cms_node_exec_prepare(), code, and NGX_BRIX_CMS_HDR_LEN.
cms_frame_redirect()
static ngx_int_t cms_frame_redirect (ngx_brix_cms_ctx_t * ctx, uint32_t streamid, u_char code) static
Definition at line 205 of file recv_frame.c.
References brix_cms_wake_pending_session(), host, ngx_brix_cms_get16(), NGX_BRIX_CMS_HDR_LEN, and port.
cms_frame_space()
static ngx_int_t cms_frame_space (ngx_brix_cms_ctx_t * ctx, uint32_t streamid, u_char code) static
Definition at line 171 of file recv_frame.c.
References ngx_brix_cms_send_avail().
cms_frame_state()
static ngx_int_t cms_frame_state (ngx_brix_cms_ctx_t * ctx, uint32_t streamid, u_char code) static
Definition at line 276 of file recv_frame.c.
References brix_srv_select(), brix_stat_beneath(), cms_state_extract_path(), host, NGX_BRIX_CMS_HDR_LEN, ngx_brix_cms_send_have(), and stat().
cms_frame_status()
static ngx_int_t cms_frame_status (ngx_brix_cms_ctx_t * ctx, uint32_t streamid, u_char code) static
Definition at line 180 of file recv_frame.c.
References CMS_ST_RESUME, and CMS_ST_SUSPEND.
cms_frame_update()
static ngx_int_t cms_frame_update (ngx_brix_cms_ctx_t * ctx, uint32_t streamid, u_char code) static
Definition at line 356 of file recv_frame.c.
References ngx_brix_cms_send_status().
cms_state_extract_path()
static ngx_int_t cms_state_extract_path (const u_char * payload, size_t plen, char * pathz, size_t pathz_size, size_t * pl_out) static
Definition at line 237 of file recv_frame.c.
References ngx_memcpy.
Referenced by cms_frame_state().
ngx_brix_cms_process_frame()
ngx_int_t ngx_brix_cms_process_frame (ngx_brix_cms_ctx_t * ctx)
Definition at line 416 of file recv_frame.c.
References brix_cms_route_lookup(), cms_frame_table, code, brix_cms_route_t::name, ngx_brix_cms_get32(), and XRDCMS_ROLE_NODE.
Referenced by ngx_brix_cms_read_handler().
Variable Documentation
[struct]
const struct { ... } cms_frame_table[]
Initial value:
= {
    {  17  ,   cms_frame_ping     },
    {  19  ,  cms_frame_space    },
    {  22  , cms_frame_status   },
    {  10  , cms_frame_redirect },
    {  24  ,    cms_frame_redirect },
    {  20  ,  cms_frame_state    },
    {  1  ,  cms_frame_forward  },
    {  3  ,  cms_frame_forward  },
    {  4  , cms_frame_forward  },
    {  5  ,     cms_frame_forward  },
    {  8  ,     cms_frame_forward  },
    {  9  ,  cms_frame_forward  },
    {  23  ,  cms_frame_forward  },
    {  6  , cms_frame_prepare },
    {  7  , cms_frame_prepare },
    {  25  , cms_frame_update   },
    {  13  ,   cms_frame_disc     },
}
Referenced by ngx_brix_cms_process_frame().
code
u_char code
Definition at line 387 of file recv_frame.c.
Referenced by admin_send_error(), brix_capture_frame(), brix_cms_fanout_mutation(), brix_cms_fanout_op_code(), brix_cms_fanout_send_all(), brix_cms_forward_to_node(), brix_cms_node_plan(), brix_cms_route_lookup(), brix_cms_rrdata_encode(), brix_cms_rrdata_parse(), brix_cms_send_frame(), brix_cms_srv_send_frame(), brix_ftp_ev_cmd_protected(), brix_ftp_ev_send_adat(), brix_http_send_xml_error(), brix_pelican_discover_cfg(), brix_pelican_post(), brix_qcksum_open(), brix_sess_err_lookup(), brix_stage_waiter_deliver(), brix_trace_frame(), brix_trace_response(), brix_tx_http_post(), brix_unix_apply_identity(), brix_xfer_run_reparented(), cms_forward_via_driver(), cms_forward_via_posix(), cms_frame_forward(), cms_frame_prepare(), cms_node_exec_forward(), cms_node_exec_prepare(), cms_srv_dispatch_frame(), connect_resolved(), ev_xfer_resolve_start(), fp_apply_lever_opt(), http_get_range(), kxr_lookup(), ngx_brix_cms_process_frame(), ngx_brix_cms_send_frame(), node_plan_mode_op(), playback_frame_record(), playback_reissue_wire(), rec_err(), replay_frame_record(), route_scan(), s3_fail(), s3_post_error(), s3_put_finalize_client_error(), s3_put_finalize_codec_error(), s3_put_finalize_fs_error(), s3_send_xml_error(), scan_err_http(), ssi_push_error(), ssi_resp_error(), xfer_spawn_agent(), and zip_open_error().
handler
cms_frame_handler_pt handler
Definition at line 388 of file recv_frame.c.
Referenced by brix_admin_read_body(), brix_http_read_body(), s3_read_body_metric(), and webdav_postconf_push_handler().