nginx-xrootd: src/net/upstream/lifecycle.c File Reference
lifecycle.c File Reference
#include "upstream_internal.h"
Functions
void brix_upstream_cleanup (brix_upstream_t *up)
void brix_upstream_abort (brix_upstream_t *up, const char *reason)
Function Documentation
brix_upstream_abort()
void brix_upstream_abort (brix_upstream_t * up, const char * reason)
Definition at line 41 of file lifecycle.c.
References brix_schedule_read_resume(), brix_send_error(), brix_upstream_cleanup(), c, brix_ctx_recv_t::cur_streamid, kXR_ServerError, brix_ctx_t::recv, brix_ctx_t::state, and XRD_ST_REQ_HEADER.
Referenced by brix_upstream_bootstrap_advance(), brix_upstream_bs_auth(), brix_upstream_bs_goto_tls(), brix_upstream_bs_handshake(), brix_upstream_bs_login(), brix_upstream_bs_protocol(), brix_upstream_continue_auth(), brix_upstream_dispatch_response(), brix_upstream_forward_response(), brix_upstream_handle_bootstrap_response(), brix_upstream_parse_header_and_alloc(), brix_upstream_read_handler(), brix_upstream_recv_chunk(), brix_upstream_wait_timer_handler(), and brix_upstream_write_handler().
brix_upstream_cleanup()
void brix_upstream_cleanup (brix_upstream_t * up)
Definition at line 13 of file lifecycle.c.
Referenced by brix_on_disconnect(), brix_upstream_abort(), brix_upstream_forward_response(), brix_upstream_read_handler(), brix_upstream_start(), brix_upstream_wait_timer_handler(), and brix_upstream_write_handler().