nginx-xrootd: src/net/proxy/directives.c File Reference
directives.c File Reference
#include "proxy_internal.h"
#include <stdlib.h>
#include <string.h>
#include "core/compat/alloc_guard.h"
#include "core/compat/cstr.h"
Functions
static char * proxy_parse_host_port (ngx_conf_t *cf, ngx_str_t *value, char *addr_copy, ngx_str_t *host_out, uint16_t *port_out)
static char * proxy_parse_upstream_auth (ngx_conf_t *cf, ngx_str_t *auth_arg, brix_proxy_upstream_t *entry)
char * brix_conf_set_proxy_upstream (ngx_conf_t *cf, ngx_command_t *cmd, void *conf_ptr)
char * brix_conf_set_proxy_auth (ngx_conf_t *cf, ngx_command_t *cmd, void *conf_ptr)
char * brix_conf_set_proxy_login_user (ngx_conf_t *cf, ngx_command_t *cmd, void *conf_ptr)
char * brix_conf_set_proxy_path_rewrite (ngx_conf_t *cf, ngx_command_t *cmd, void *conf_ptr)
Function Documentation
brix_conf_set_proxy_auth()
char * brix_conf_set_proxy_auth (ngx_conf_t * cf, ngx_command_t * cmd, void * conf_ptr)
Definition at line 242 of file directives.c.
References BRIX_PROXY_AUTH_ANONYMOUS, BRIX_PROXY_AUTH_FORWARD, BRIX_PROXY_AUTH_GSI, and BRIX_PROXY_AUTH_SSS.
brix_conf_set_proxy_login_user()
char * brix_conf_set_proxy_login_user (ngx_conf_t * cf, ngx_command_t * cmd, void * conf_ptr)
Definition at line 281 of file directives.c.
References BRIX_PROXY_LOGIN_ANONYMOUS, BRIX_PROXY_LOGIN_FIXED, BRIX_PROXY_LOGIN_PASSTHROUGH, and ngx_memcpy.
brix_conf_set_proxy_path_rewrite()
char * brix_conf_set_proxy_path_rewrite (ngx_conf_t * cf, ngx_command_t * cmd, void * conf_ptr)
Definition at line 328 of file directives.c.
brix_conf_set_proxy_upstream()
char * brix_conf_set_proxy_upstream (ngx_conf_t * cf, ngx_command_t * cmd, void * conf_ptr)
Definition at line 173 of file directives.c.
References brix_proxy_upstream_t::auth, brix_pstrdup_z(), host, brix_proxy_upstream_t::host, port, brix_proxy_upstream_t::port, proxy_parse_host_port(), proxy_parse_upstream_auth(), and brix_proxy_upstream_t::sss_keyname.
proxy_parse_host_port()
static char * proxy_parse_host_port (ngx_conf_t * cf, ngx_str_t * value, char * addr_copy, ngx_str_t * host_out, uint16_t * port_out) static
Definition at line 40 of file directives.c.
References ngx_memcpy, and ngx_pnalloc().
Referenced by brix_conf_set_proxy_upstream().
proxy_parse_upstream_auth()
static char * proxy_parse_upstream_auth (ngx_conf_t * cf, ngx_str_t * auth_arg, brix_proxy_upstream_t * entry) static
Definition at line 116 of file directives.c.
References brix_proxy_upstream_t::auth, BRIX_PROXY_AUTH_ANONYMOUS, BRIX_PROXY_AUTH_FORWARD, BRIX_PROXY_AUTH_SSS, BRIX_SSS_NAME_MAX, ngx_memcpy, and brix_proxy_upstream_t::sss_keyname.
Referenced by brix_conf_set_proxy_upstream().