nginx-xrootd: src/net/httpguard/module.c File Reference
module.c File Reference
#include "guard_http.h"
Functions
static void * ngx_http_brix_guard_create_loc_conf (ngx_conf_t *cf)
static char * ngx_http_brix_guard_merge_loc_conf (ngx_conf_t *cf, void *parent, void *child)
static ngx_int_t ngx_http_brix_guard_postconf (ngx_conf_t *cf)
static char * ngx_http_brix_guard_audit_log_slot (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static char * ngx_http_brix_guard_array_slot (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static guard_op_class_t method_name_to_op (const ngx_str_t *name)
static char * ngx_http_brix_guard_build_ruleset (ngx_conf_t *cf, ngx_http_brix_guard_loc_conf_t *lcf)
Variables
static ngx_command_t ngx_http_brix_guard_commands []
static ngx_http_module_t ngx_http_brix_guard_module_ctx
ngx_module_t ngx_http_brix_guard_module
Function Documentation
method_name_to_op()
static guard_op_class_t method_name_to_op (const ngx_str_t * name) static
Definition at line 197 of file module.c.
References GUARD_OP_DELETE, GUARD_OP_INFO, GUARD_OP_LIST, GUARD_OP_READ, GUARD_OP_UNKNOWN, GUARD_OP_WRITE, name, and op.
Referenced by ngx_http_brix_guard_build_ruleset().
ngx_http_brix_guard_array_slot()
static char * ngx_http_brix_guard_array_slot (ngx_conf_t * cf, ngx_command_t * cmd, void * conf) static
Definition at line 158 of file module.c.
ngx_http_brix_guard_audit_log_slot()
static char * ngx_http_brix_guard_audit_log_slot (ngx_conf_t * cf, ngx_command_t * cmd, void * conf) static
Definition at line 124 of file module.c.
References ngx_http_brix_guard_loc_conf_t::audit_log.
ngx_http_brix_guard_build_ruleset()
static char * ngx_http_brix_guard_build_ruleset (ngx_conf_t * cf, ngx_http_brix_guard_loc_conf_t * lcf) static
Definition at line 237 of file module.c.
References ngx_http_brix_guard_loc_conf_t::default_sigs, ngx_http_brix_guard_loc_conf_t::extra_sigs, GUARD_MAX_PREFIXES, GUARD_MAX_SIGS, GUARD_OP_UNKNOWN, guard_ruleset_add_default_signatures(), guard_ruleset_add_prefix(), guard_ruleset_add_signature(), guard_ruleset_init(), guard_ruleset_load_profile(), GUARD_SIG_SUBSTR, method_name_to_op(), ngx_http_brix_guard_loc_conf_t::methods, op, guard_ruleset_t::op_allowed, ngx_http_brix_guard_loc_conf_t::prefixes, ngx_http_brix_guard_loc_conf_t::profile, and ngx_http_brix_guard_loc_conf_t::ruleset.
Referenced by ngx_http_brix_guard_merge_loc_conf().
ngx_http_brix_guard_create_loc_conf()
static void * ngx_http_brix_guard_create_loc_conf (ngx_conf_t * cf) static
Definition at line 324 of file module.c.
References ngx_http_brix_guard_loc_conf_t::bounce_status, ngx_http_brix_guard_loc_conf_t::default_sigs, ngx_http_brix_guard_loc_conf_t::enable, ngx_http_brix_guard_loc_conf_t::extra_sigs, ngx_http_brix_guard_loc_conf_t::methods, ngx_pcalloc(), and ngx_http_brix_guard_loc_conf_t::prefixes.
ngx_http_brix_guard_merge_loc_conf()
static char * ngx_http_brix_guard_merge_loc_conf (ngx_conf_t * cf, void * parent, void * child) static
Definition at line 359 of file module.c.
References ngx_http_brix_guard_loc_conf_t::audit_log, ngx_http_brix_guard_loc_conf_t::bounce_status, ngx_http_brix_guard_loc_conf_t::default_sigs, ngx_http_brix_guard_loc_conf_t::enable, ngx_http_brix_guard_loc_conf_t::extra_sigs, ngx_http_brix_guard_loc_conf_t::methods, ngx_http_brix_guard_build_ruleset(), ngx_http_brix_guard_loc_conf_t::prefixes, and ngx_http_brix_guard_loc_conf_t::profile.
ngx_http_brix_guard_postconf()
static ngx_int_t ngx_http_brix_guard_postconf (ngx_conf_t * cf) static
Definition at line 402 of file module.c.
References ngx_http_brix_guard_access_handler(), and ngx_http_brix_guard_log_handler().
Variable Documentation
ngx_http_brix_guard_commands
ngx_command_t ngx_http_brix_guard_commands[] static
Definition at line 27 of file module.c.
ngx_http_brix_guard_module
ngx_module_t ngx_http_brix_guard_module
Initial value:
= {
    NGX_MODULE_V1,
    &ngx_http_brix_guard_module_ctx,
    ngx_http_brix_guard_commands,
    NGX_HTTP_MODULE,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NGX_MODULE_V1_PADDING
}
Definition at line 101 of file module.c.
Referenced by ngx_http_brix_guard_access_handler(), and ngx_http_brix_guard_log_handler().
ngx_http_brix_guard_module_ctx
ngx_http_module_t ngx_http_brix_guard_module_ctx static
Initial value:
= {
    NULL,
    ngx_http_brix_guard_postconf,
    NULL,
    NULL,
    NULL,
    NULL,
    ngx_http_brix_guard_create_loc_conf,
    ngx_http_brix_guard_merge_loc_conf
}
Definition at line 89 of file module.c.