nginx-xrootd: src/core/compat/net_target_parse.c File Reference
net_target_parse.c File Reference
#include "net_target.h"
#include "net_target_internal.h"
#include "cstr.h"
#include <netdb.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <stdio.h>
#include <string.h>
Data Structures
struct net_url_span_t
Functions
static const u_char * net_parse_scheme (const ngx_str_t *url, brix_net_target_t *out, char *err, size_t errsz)
static ngx_int_t net_parse_port_digits (const u_char *begin, const u_char *end, uint16_t *out_port, char *err, size_t errsz)
static ngx_int_t net_parse_bracketed_host (const net_url_span_t *span, brix_net_target_t *out)
static ngx_int_t net_parse_plain_host (const net_url_span_t *span, brix_net_target_t *out)
static ngx_int_t net_parse_authority (const net_url_span_t *span, brix_net_target_t *out)
ngx_int_t brix_net_target_parse (ngx_pool_t *pool, const ngx_str_t *url, brix_net_target_t *out, char *err, size_t errsz)
Function Documentation
brix_net_target_parse()
ngx_int_t brix_net_target_parse (ngx_pool_t * pool, const ngx_str_t * url, brix_net_target_t * out, char * err, size_t errsz)
Definition at line 244 of file net_target_parse.c.
References net_url_span_t::err, net_url_span_t::errsz, brix_net_target_t::host, net_url_span_t::host_end, net_url_span_t::host_start, net_parse_authority(), net_parse_scheme(), brix_net_target_t::path, and brix_net_target_t::raw_url.
Referenced by tpc_curl_secure(), tpc_marker_thread_func(), tpc_thread_ssrf_preflight(), and xrdhttp_inject_tpc_headers().
net_parse_authority()
static ngx_int_t net_parse_authority (const net_url_span_t * span, brix_net_target_t * out) static
Definition at line 222 of file net_target_parse.c.
References net_url_span_t::host_end, net_url_span_t::host_start, net_parse_bracketed_host(), and net_parse_plain_host().
Referenced by brix_net_target_parse().
net_parse_bracketed_host()
static ngx_int_t net_parse_bracketed_host (const net_url_span_t * span, brix_net_target_t * out) static
Definition at line 137 of file net_target_parse.c.
References net_url_span_t::err, net_url_span_t::errsz, brix_net_target_t::has_port, brix_net_target_t::host, net_url_span_t::host_end, net_url_span_t::host_start, net_parse_port_digits(), and brix_net_target_t::port.
Referenced by net_parse_authority().
net_parse_plain_host()
static ngx_int_t net_parse_plain_host (const net_url_span_t * span, brix_net_target_t * out) static
Definition at line 181 of file net_target_parse.c.
References net_url_span_t::err, net_url_span_t::errsz, brix_net_target_t::has_port, brix_net_target_t::host, net_url_span_t::host_end, net_url_span_t::host_start, net_parse_port_digits(), and brix_net_target_t::port.
Referenced by net_parse_authority().
net_parse_port_digits()
static ngx_int_t net_parse_port_digits (const u_char * begin, const u_char * end, uint16_t * out_port, char * err, size_t errsz) static
Definition at line 103 of file net_target_parse.c.
Referenced by net_parse_bracketed_host(), and net_parse_plain_host().
net_parse_scheme()
static const u_char * net_parse_scheme (const ngx_str_t * url, brix_net_target_t * out, char * err, size_t errsz) static
Definition at line 53 of file net_target_parse.c.
References brix_net_target_t::scheme.
Referenced by brix_net_target_parse().