nginx-xrootd: src/core/compat/net_target_dns.c File Reference
net_target_dns.c File Reference
#include "net_target.h"
#include "net_target_internal.h"
#include "cstr.h"
#include <netdb.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <stdio.h>
#include <string.h>
Data Structures
struct net_pin_out_t
Functions
static uint16_t net_default_port (const brix_net_target_t *target, const brix_net_target_policy_t *policy)
static ngx_int_t net_resolve_host (const char *host_buf, uint16_t port, struct addrinfo **out_res, char *err, size_t errsz)
static int net_addr_is_prohibited_msg (const struct sockaddr *sa, const brix_net_target_policy_t *policy, const char *host_buf, char *err, size_t errsz)
ngx_int_t brix_net_target_check_dns (const brix_net_target_t *target, const brix_net_target_policy_t *policy, char *err, size_t errsz)
static ngx_int_t net_pin_append_addr (const struct addrinfo *rp, const char *host_buf, const net_pin_out_t *pin, char *err, size_t errsz)
ngx_int_t brix_net_target_check_dns_pin (const brix_net_target_t *target, const brix_net_target_policy_t *policy, char *out_ip, size_t out_ipsz, char *err, size_t errsz)
Function Documentation
brix_net_target_check_dns()
ngx_int_t brix_net_target_check_dns (const brix_net_target_t * target, const brix_net_target_policy_t * policy, char * err, size_t errsz)
Definition at line 121 of file net_target_dns.c.
References brix_str_cbuf(), brix_net_target_t::host, net_addr_is_prohibited_msg(), net_default_port(), and net_resolve_host().
Referenced by brix_tpc_check_src_policy(), tpc_marker_thread_func(), and tpc_thread_ssrf_preflight().
brix_net_target_check_dns_pin()
ngx_int_t brix_net_target_check_dns_pin (const brix_net_target_t * target, const brix_net_target_policy_t * policy, char * out_ip, size_t out_ipsz, char * err, size_t errsz)
Definition at line 236 of file net_target_dns.c.
References brix_str_cbuf(), brix_net_target_t::host, net_addr_is_prohibited_msg(), net_default_port(), net_pin_append_addr(), and net_resolve_host().
Referenced by tpc_curl_secure().
net_addr_is_prohibited_msg()
static int net_addr_is_prohibited_msg (const struct sockaddr * sa, const brix_net_target_policy_t * policy, const char * host_buf, char * err, size_t errsz) static
Definition at line 90 of file net_target_dns.c.
References brix_net_target_policy_t::allow_local, brix_net_target_policy_t::allow_private, and net_addr_check().
Referenced by brix_net_target_check_dns(), and brix_net_target_check_dns_pin().
net_default_port()
static uint16_t net_default_port (const brix_net_target_t * target, const brix_net_target_policy_t * policy) static
Definition at line 34 of file net_target_dns.c.
References brix_net_target_policy_t::default_https_port, brix_net_target_policy_t::default_root_port, brix_net_target_t::port, brix_net_target_policy_t::require_https, and brix_net_target_t::scheme.
Referenced by brix_net_target_check_dns(), and brix_net_target_check_dns_pin().
net_pin_append_addr()
static ngx_int_t net_pin_append_addr (const struct addrinfo * rp, const char * host_buf, const net_pin_out_t * pin, char * err, size_t errsz) static
Definition at line 193 of file net_target_dns.c.
References net_pin_out_t::buf, ngx_memcpy, and net_pin_out_t::size.
Referenced by brix_net_target_check_dns_pin().
net_resolve_host()
static ngx_int_t net_resolve_host (const char * host_buf, uint16_t port, struct addrinfo ** out_res, char * err, size_t errsz) static
Definition at line 59 of file net_target_dns.c.
Referenced by brix_net_target_check_dns(), and brix_net_target_check_dns_pin().