nginx-xrootd: src/core/compat/net_target.h File Reference
net_target.h File Reference
#include <ngx_http.h>
#include <stdint.h>
#include <sys/socket.h>
Data Structures
struct brix_net_target_t
struct brix_net_target_policy_t
Functions
ngx_int_t brix_net_target_parse (ngx_pool_t *pool, const ngx_str_t *url, brix_net_target_t *out, char *err, size_t errsz)
ngx_int_t brix_net_target_check_addr (const struct sockaddr *sa, const brix_net_target_policy_t *policy, char *err, size_t errsz)
ngx_int_t brix_net_target_check_dns (const brix_net_target_t *target, const brix_net_target_policy_t *policy, char *err, size_t errsz)
ngx_int_t brix_net_target_check_dns_pin (const brix_net_target_t *target, const brix_net_target_policy_t *policy, char *out_ip, size_t out_ipsz, char *err, size_t errsz)
int brix_net_host_chars_valid (const char *host, size_t len)
Function Documentation
brix_net_host_chars_valid()
int brix_net_host_chars_valid (const char * host, size_t len)
Definition at line 175 of file net_target.c.
Referenced by brix_srv_register(), and cms_wake_pending_session().
brix_net_target_check_addr()
ngx_int_t brix_net_target_check_addr (const struct sockaddr * sa, const brix_net_target_policy_t * policy, char * err, size_t errsz)
Definition at line 151 of file net_target.c.
References brix_net_target_policy_t::allow_local, brix_net_target_policy_t::allow_private, and net_addr_check().
Referenced by tpc_connect().
brix_net_target_check_dns()
ngx_int_t brix_net_target_check_dns (const brix_net_target_t * target, const brix_net_target_policy_t * policy, char * err, size_t errsz)
Definition at line 121 of file net_target_dns.c.
References brix_str_cbuf(), brix_net_target_t::host, net_addr_is_prohibited_msg(), net_default_port(), and net_resolve_host().
Referenced by brix_tpc_check_src_policy(), tpc_marker_thread_func(), and tpc_thread_ssrf_preflight().
brix_net_target_check_dns_pin()
ngx_int_t brix_net_target_check_dns_pin (const brix_net_target_t * target, const brix_net_target_policy_t * policy, char * out_ip, size_t out_ipsz, char * err, size_t errsz)
Definition at line 215 of file net_target_dns.c.
References brix_str_cbuf(), brix_net_target_t::host, net_addr_is_prohibited_msg(), net_default_port(), net_pin_first_addr(), and net_resolve_host().
Referenced by tpc_curl_secure().
brix_net_target_parse()
ngx_int_t brix_net_target_parse (ngx_pool_t * pool, const ngx_str_t * url, brix_net_target_t * out, char * err, size_t errsz)
Definition at line 244 of file net_target_parse.c.
References net_url_span_t::err, net_url_span_t::errsz, brix_net_target_t::host, net_url_span_t::host_end, net_url_span_t::host_start, net_parse_authority(), net_parse_scheme(), brix_net_target_t::path, and brix_net_target_t::raw_url.
Referenced by tpc_curl_secure(), tpc_marker_thread_func(), tpc_thread_ssrf_preflight(), and xrdhttp_inject_tpc_headers().