nginx-xrootd: src/core/compat/net_target.c File Reference
net_target.c File Reference
#include "net_target.h"
#include "cstr.h"
#include <netdb.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <stdio.h>
#include <string.h>
Functions
static int net_ipv4_is_prohibited (uint32_t addr, ngx_flag_t allow_local, ngx_flag_t allow_private)
static int net_ipv6_is_prohibited (const uint8_t *addr, ngx_flag_t allow_local, ngx_flag_t allow_private)
static int net_addr_check (const struct sockaddr *sa, ngx_flag_t allow_local, ngx_flag_t allow_private)
ngx_int_t brix_net_target_check_addr (const struct sockaddr *sa, const brix_net_target_policy_t *policy, char *err, size_t errsz)
ngx_int_t brix_net_target_parse (ngx_pool_t *pool, const ngx_str_t *url, brix_net_target_t *out, char *err, size_t errsz)
ngx_int_t brix_net_target_check_dns (const brix_net_target_t *target, const brix_net_target_policy_t *policy, char *err, size_t errsz)
ngx_int_t brix_net_target_check_dns_pin (const brix_net_target_t *target, const brix_net_target_policy_t *policy, char *out_ip, size_t out_ipsz, char *err, size_t errsz)
int brix_net_host_chars_valid (const char *host, size_t len)
Function Documentation
brix_net_host_chars_valid()
int brix_net_host_chars_valid (const char * host, size_t len)
Definition at line 509 of file net_target.c.
Referenced by brix_srv_register(), and cms_wake_pending_session().
brix_net_target_check_addr()
ngx_int_t brix_net_target_check_addr (const struct sockaddr * sa, const brix_net_target_policy_t * policy, char * err, size_t errsz)
Definition at line 145 of file net_target.c.
References brix_net_target_policy_t::allow_local, brix_net_target_policy_t::allow_private, and net_addr_check().
Referenced by tpc_connect().
brix_net_target_check_dns()
ngx_int_t brix_net_target_check_dns (const brix_net_target_t * target, const brix_net_target_policy_t * policy, char * err, size_t errsz)
Definition at line 337 of file net_target.c.
References brix_net_target_policy_t::allow_local, brix_net_target_policy_t::allow_private, brix_str_cbuf(), brix_net_target_policy_t::default_https_port, brix_net_target_policy_t::default_root_port, brix_net_target_t::host, net_addr_check(), brix_net_target_t::port, brix_net_target_policy_t::require_https, and brix_net_target_t::scheme.
Referenced by brix_tpc_check_src_policy(), tpc_marker_thread_func(), and tpc_thread_func().
brix_net_target_check_dns_pin()
ngx_int_t brix_net_target_check_dns_pin (const brix_net_target_t * target, const brix_net_target_policy_t * policy, char * out_ip, size_t out_ipsz, char * err, size_t errsz)
Definition at line 416 of file net_target.c.
References brix_net_target_policy_t::allow_local, brix_net_target_policy_t::allow_private, brix_str_cbuf(), brix_net_target_policy_t::default_https_port, brix_net_target_policy_t::default_root_port, brix_net_target_t::host, net_addr_check(), brix_net_target_t::port, brix_net_target_policy_t::require_https, and brix_net_target_t::scheme.
Referenced by tpc_curl_secure().
brix_net_target_parse()
ngx_int_t brix_net_target_parse (ngx_pool_t * pool, const ngx_str_t * url, brix_net_target_t * out, char * err, size_t errsz)
Definition at line 175 of file net_target.c.
References brix_net_target_t::has_port, brix_net_target_t::host, brix_net_target_t::path, brix_net_target_t::port, brix_net_target_t::raw_url, and brix_net_target_t::scheme.
Referenced by tpc_curl_secure(), tpc_marker_thread_func(), tpc_thread_func(), and xrdhttp_inject_tpc_headers().
net_addr_check()
static int net_addr_check (const struct sockaddr * sa, ngx_flag_t allow_local, ngx_flag_t allow_private) static
Definition at line 103 of file net_target.c.
References net_ipv4_is_prohibited(), and net_ipv6_is_prohibited().
Referenced by brix_net_target_check_addr(), brix_net_target_check_dns(), and brix_net_target_check_dns_pin().
net_ipv4_is_prohibited()
static int net_ipv4_is_prohibited (uint32_t addr, ngx_flag_t allow_local, ngx_flag_t allow_private) static
Definition at line 29 of file net_target.c.
Referenced by net_addr_check().
net_ipv6_is_prohibited()
static int net_ipv6_is_prohibited (const uint8_t * addr, ngx_flag_t allow_local, ngx_flag_t allow_private) static
Definition at line 65 of file net_target.c.
Referenced by net_addr_check().