nginx-xrootd: src/net/manager/registry.c File Reference
registry.c File Reference
#include "registry_internal.h"
Functions
void brix_srv_set_stale_after (ngx_msec_t ms)
void brix_srv_set_load_weight (ngx_uint_t weight)
void brix_srv_set_affinity (ngx_uint_t on)
brix_srv_table_t * srv_table (void)
ngx_int_t brix_srv_shm_init_zone (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t brix_srv_configure_registry (ngx_conf_t *cf, ngx_uint_t slots)
void brix_srv_register (const char *host, uint16_t port, const char *paths, uint32_t free_mb, uint32_t util_pct)
void brix_srv_update_load (const char *host, uint16_t port, uint32_t free_mb, uint32_t util_pct)
void brix_srv_unregister (const char *host, uint16_t port)
static brix_srv_entry_t * srv_find_locked (const char *host, uint16_t port)
int brix_srv_reset (const char *host, uint16_t port)
void brix_srv_set_vnid (const char *host, uint16_t port, const char *vnid)
void brix_srv_set_stage (const char *host, uint16_t port, ngx_uint_t stage)
void brix_srv_set_machine_load (const char *host, uint16_t port, uint32_t load_pct)
Variables
ngx_shm_zone_t * brix_srv_shm_zone
ngx_shmtx_t brix_srv_mutex
ngx_uint_t brix_srv_registry_nslots = 128
ngx_msec_t brix_srv_stale_after_ms
ngx_uint_t brix_srv_load_weight
ngx_uint_t brix_srv_affinity
Function Documentation
brix_srv_configure_registry()
ngx_int_t brix_srv_configure_registry (ngx_conf_t * cf, ngx_uint_t slots)
Definition at line 113 of file registry.c.
References brix_shm_zone_size(), brix_shm_zone_warn_on_resize(), brix_srv_registry_nslots, brix_srv_shm_init_zone(), brix_srv_shm_zone, and ngx_stream_brix_module.
Referenced by postconf_server_registry().
brix_srv_register()
void brix_srv_register (const char * host, uint16_t port, const char * paths, uint32_t free_mb, uint32_t util_pct)
Definition at line 156 of file registry.c.
References brix_srv_entry_t::blacklisted_until, brix_metrics_shared(), brix_net_host_chars_valid(), brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::error_count, brix_srv_entry_t::free_mb, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, brix_srv_entry_t::last_seen, brix_srv_entry_t::paths, port, brix_srv_entry_t::port, ngx_brix_metrics_t::registry_full_total, brix_srv_table_t::slots, srv_table(), and brix_srv_entry_t::util_pct.
Referenced by admin_cluster_register(), brix_cache_fill_done(), and cms_srv_complete_login().
brix_srv_reset()
int brix_srv_reset (const char * host, uint16_t port)
Definition at line 362 of file registry.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_mutex, brix_srv_entry_t::error_count, brix_srv_entry_t::free_mb, brix_srv_entry_t::hc_fail_count, brix_srv_entry_t::hc_in_progress, host, brix_srv_entry_t::last_seen, brix_srv_entry_t::load_pct, port, srv_find_locked(), srv_table(), and brix_srv_entry_t::util_pct.
Referenced by cms_srv_frame_status().
brix_srv_set_affinity()
void brix_srv_set_affinity (ngx_uint_t on)
Definition at line 34 of file registry.c.
References brix_srv_affinity.
Referenced by brix_merge_srv_cms().
brix_srv_set_load_weight()
void brix_srv_set_load_weight (ngx_uint_t weight)
Definition at line 27 of file registry.c.
References brix_srv_load_weight.
Referenced by brix_merge_srv_cms().
brix_srv_set_machine_load()
void brix_srv_set_machine_load (const char * host, uint16_t port, uint32_t load_pct)
Definition at line 431 of file registry.c.
References brix_srv_mutex, host, brix_srv_entry_t::load_pct, port, srv_find_locked(), and srv_table().
Referenced by cms_srv_frame_load().
brix_srv_set_stage()
void brix_srv_set_stage (const char * host, uint16_t port, ngx_uint_t stage)
Definition at line 412 of file registry.c.
References brix_srv_mutex, host, port, srv_find_locked(), srv_table(), and brix_srv_entry_t::stage.
Referenced by cms_srv_frame_status().
brix_srv_set_stale_after()
void brix_srv_set_stale_after (ngx_msec_t ms)
Definition at line 20 of file registry.c.
References brix_srv_stale_after_ms.
Referenced by brix_merge_srv_net_fault().
brix_srv_set_vnid()
void brix_srv_set_vnid (const char * host, uint16_t port, const char * vnid)
Definition at line 392 of file registry.c.
References brix_srv_mutex, host, port, srv_find_locked(), srv_table(), and brix_srv_entry_t::vnid.
Referenced by cms_srv_complete_login().
brix_srv_shm_init_zone()
ngx_int_t brix_srv_shm_init_zone (ngx_shm_zone_t * shm_zone, void * data)
Definition at line 73 of file registry.c.
References brix_shm_table_alloc(), brix_srv_mutex, brix_srv_registry_nslots, and brix_srv_table_t::capacity.
Referenced by brix_srv_configure_registry().
brix_srv_unregister()
void brix_srv_unregister (const char * host, uint16_t port)
Definition at line 300 of file registry.c.
References brix_srv_mutex, brix_srv_table_t::capacity, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, port, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by admin_cluster_delete().
brix_srv_update_load()
void brix_srv_update_load (const char * host, uint16_t port, uint32_t free_mb, uint32_t util_pct)
Definition at line 256 of file registry.c.
References brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::free_mb, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, brix_srv_entry_t::last_seen, port, brix_srv_entry_t::port, brix_srv_table_t::slots, srv_table(), and brix_srv_entry_t::util_pct.
Referenced by cms_srv_frame_avail(), and cms_srv_frame_load().
srv_find_locked()
static brix_srv_entry_t * srv_find_locked (const char * host, uint16_t port) static
Definition at line 333 of file registry.c.
References brix_srv_table_t::capacity, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, port, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by brix_srv_reset(), brix_srv_set_machine_load(), brix_srv_set_stage(), and brix_srv_set_vnid().
srv_table()
brix_srv_table_t * srv_table (void)
Definition at line 41 of file registry.c.
References brix_srv_shm_zone.
Referenced by brix_srv_aggregate_space(), brix_srv_blacklist(), brix_srv_count_matching(), brix_srv_hc_claim(), brix_srv_hc_fail(), brix_srv_hc_pass(), brix_srv_is_blacklisted(), brix_srv_locate_all(), brix_srv_register(), brix_srv_reset(), brix_srv_set_machine_load(), brix_srv_set_stage(), brix_srv_set_vnid(), brix_srv_snapshot(), brix_srv_undrain(), brix_srv_unregister(), brix_srv_unregister_path(), brix_srv_update_load(), srv_find_locked(), and srv_select_core().
Variable Documentation
brix_srv_affinity
ngx_uint_t brix_srv_affinity
Definition at line 16 of file registry.c.
Referenced by brix_srv_set_affinity(), and srv_select_core().
brix_srv_load_weight
ngx_uint_t brix_srv_load_weight
Definition at line 14 of file registry.c.
Referenced by brix_srv_set_load_weight(), and srv_sel_load_metric().
brix_srv_mutex
ngx_shmtx_t brix_srv_mutex
Definition at line 8 of file registry.c.
Referenced by brix_srv_aggregate_space(), brix_srv_blacklist(), brix_srv_count_matching(), brix_srv_hc_claim(), brix_srv_hc_fail(), brix_srv_hc_pass(), brix_srv_is_blacklisted(), brix_srv_locate_all(), brix_srv_register(), brix_srv_reset(), brix_srv_set_machine_load(), brix_srv_set_stage(), brix_srv_set_vnid(), brix_srv_shm_init_zone(), brix_srv_snapshot(), brix_srv_undrain(), brix_srv_unregister(), brix_srv_unregister_path(), brix_srv_update_load(), and srv_select_core().
brix_srv_registry_nslots
ngx_uint_t brix_srv_registry_nslots = 128
Definition at line 10 of file registry.c.
Referenced by brix_srv_configure_registry(), and brix_srv_shm_init_zone().
brix_srv_shm_zone
ngx_shm_zone_t* brix_srv_shm_zone
Definition at line 7 of file registry.c.
Referenced by brix_export_cluster_metrics(), brix_srv_configure_registry(), and srv_table().
brix_srv_stale_after_ms
ngx_msec_t brix_srv_stale_after_ms
Definition at line 12 of file registry.c.
Referenced by brix_srv_set_stale_after(), and srv_sel_state_consider().