nginx-xrootd: src/net/cms/connect.c File Reference
connect.c File Reference
#include "cms_internal.h"
#include "protocols/root/connection/netopt.h"
#include "core/compat/log_diag.h"
#include "core/compat/lifecycle_timing.h"
#include "observability/sesslog/sesslog_ngx.h"
#include <ngx_event_connect.h>
#include <netinet/in.h>
Functions
static ngx_uint_t cms_addr_is_loopback (struct sockaddr *sa)
void ngx_brix_cms_set_end_hint (ngx_brix_cms_ctx_t *ctx, brix_sess_end_t why)
static brix_sess_end_t ngx_brix_cms_end_reason (ngx_brix_cms_ctx_t *ctx, ngx_connection_t *c)
static const char * ngx_brix_cms_manager_cstr (ngx_brix_cms_ctx_t *ctx, char *dst, size_t dst_size)
static void ngx_brix_cms_sess_begin (ngx_brix_cms_ctx_t *ctx)
static void ngx_brix_cms_log_registration (ngx_brix_cms_ctx_t *ctx)
void ngx_brix_cms_arm_read_deadline (ngx_brix_cms_ctx_t *ctx)
void ngx_brix_cms_schedule (ngx_brix_cms_ctx_t *ctx, ngx_msec_t delay)
void ngx_brix_cms_schedule_retry (ngx_brix_cms_ctx_t *ctx)
void ngx_brix_cms_disconnect (ngx_brix_cms_ctx_t *ctx)
static void ngx_brix_cms_write_handler (ngx_event_t *ev)
static void ngx_brix_cms_connect (ngx_brix_cms_ctx_t *ctx)
static void ngx_brix_cms_timer (ngx_event_t *ev)
void ngx_brix_cms_start (ngx_cycle_t *cycle, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
cms_addr_is_loopback()
static ngx_uint_t cms_addr_is_loopback (struct sockaddr * sa) static
Definition at line 14 of file connect.c.
Referenced by ngx_brix_cms_start().
ngx_brix_cms_arm_read_deadline()
void ngx_brix_cms_arm_read_deadline (ngx_brix_cms_ctx_t * ctx)
Definition at line 134 of file connect.c.
References c.
Referenced by ngx_brix_cms_read_handler(), and ngx_brix_cms_write_handler().
ngx_brix_cms_connect()
static void ngx_brix_cms_connect (ngx_brix_cms_ctx_t * ctx) static
Definition at line 403 of file connect.c.
References brix_apply_tcp_deadpeer_opts(), BRIX_DIAG_WARN, c, NGX_BRIX_CMS_CONNECT_TIMEOUT, NGX_BRIX_CMS_HDR_LEN, ngx_brix_cms_read_handler(), ngx_brix_cms_schedule_retry(), ngx_brix_cms_sess_begin(), and ngx_brix_cms_write_handler().
Referenced by ngx_brix_cms_timer().
ngx_brix_cms_disconnect()
void ngx_brix_cms_disconnect (ngx_brix_cms_ctx_t * ctx)
Definition at line 255 of file connect.c.
References brix_sess_end(), c, ngx_brix_cms_end_reason(), and NGX_BRIX_CMS_HDR_LEN.
Referenced by cms_conn_fail(), cms_frame_disc(), ngx_brix_cms_timer(), and ngx_brix_cms_write_handler().
ngx_brix_cms_end_reason()
static brix_sess_end_t ngx_brix_cms_end_reason (ngx_brix_cms_ctx_t * ctx, ngx_connection_t * c) static
Definition at line 47 of file connect.c.
References BRIX_SESS_END_ERROR, BRIX_SESS_END_SHUTDOWN, BRIX_SESS_END_TIMEOUT, and c.
Referenced by ngx_brix_cms_disconnect().
ngx_brix_cms_log_registration()
static void ngx_brix_cms_log_registration (ngx_brix_cms_ctx_t * ctx) static
Definition at line 112 of file connect.c.
References BRIX_SESS_AM_HOST, brix_sess_attempt(), brix_sess_auth_once(), BRIX_SESS_MODE_META, brix_sess_result(), BRIX_SESSLOG_PATH_MAX, and ngx_brix_cms_manager_cstr().
Referenced by ngx_brix_cms_write_handler().
ngx_brix_cms_manager_cstr()
static const char * ngx_brix_cms_manager_cstr (ngx_brix_cms_ctx_t * ctx, char * dst, size_t dst_size) static
Definition at line 72 of file connect.c.
References ngx_memcpy.
Referenced by ngx_brix_cms_log_registration().
ngx_brix_cms_schedule()
void ngx_brix_cms_schedule (ngx_brix_cms_ctx_t * ctx, ngx_msec_t delay)
Definition at line 151 of file connect.c.
Referenced by ngx_brix_cms_schedule_retry(), ngx_brix_cms_start(), ngx_brix_cms_timer(), and ngx_brix_cms_write_handler().
ngx_brix_cms_schedule_retry()
void ngx_brix_cms_schedule_retry (ngx_brix_cms_ctx_t * ctx)
Definition at line 180 of file connect.c.
References BRIX_DIAG_WARN, NGX_BRIX_CMS_BACKOFF_MAX, and ngx_brix_cms_schedule().
Referenced by cms_conn_fail(), cms_frame_disc(), ngx_brix_cms_connect(), ngx_brix_cms_timer(), and ngx_brix_cms_write_handler().
ngx_brix_cms_sess_begin()
static void ngx_brix_cms_sess_begin (ngx_brix_cms_ctx_t * ctx) static
Definition at line 96 of file connect.c.
References BRIX_SESS_AM_HOST, brix_sess_begin(), BRIX_SESS_DIR_OUT, and BRIX_SESS_PROTO_CMS.
Referenced by ngx_brix_cms_connect().
ngx_brix_cms_set_end_hint()
void ngx_brix_cms_set_end_hint (ngx_brix_cms_ctx_t * ctx, brix_sess_end_t why)
Definition at line 36 of file connect.c.
Referenced by cms_conn_fail(), cms_frame_disc(), ngx_brix_cms_timer(), and ngx_brix_cms_write_handler().
ngx_brix_cms_start()
void ngx_brix_cms_start (ngx_cycle_t * cycle, ngx_stream_brix_srv_conf_t * conf)
Definition at line 514 of file connect.c.
References brix_phase_now_ns(), cms_addr_is_loopback(), NGX_BRIX_CMS_BACKOFF_INITIAL, NGX_BRIX_CMS_FASTRETRY_FLOOR, NGX_BRIX_CMS_FASTRETRY_LOOPBACK, NGX_BRIX_CMS_FASTRETRY_REMOTE, NGX_BRIX_CMS_FASTWIN_LOOPBACK, NGX_BRIX_CMS_FASTWIN_REMOTE, NGX_BRIX_CMS_HDR_LEN, NGX_BRIX_CMS_INITDELAY_LOOPBACK, NGX_BRIX_CMS_INITDELAY_REMOTE, ngx_brix_cms_schedule(), ngx_brix_cms_timer(), and ngx_pcalloc().
Referenced by brix_init_one_server().
ngx_brix_cms_timer()
static void ngx_brix_cms_timer (ngx_event_t * ev) static
Definition at line 473 of file connect.c.
References BRIX_SESS_END_ERROR, ngx_brix_cms_connect(), ngx_brix_cms_disconnect(), ngx_brix_cms_schedule(), ngx_brix_cms_schedule_retry(), ngx_brix_cms_send_load(), and ngx_brix_cms_set_end_hint().
Referenced by ngx_brix_cms_start().
ngx_brix_cms_write_handler()
static void ngx_brix_cms_write_handler (ngx_event_t * ev) static
Definition at line 286 of file connect.c.
References brix_phase_now_ns(), BRIX_SESS_END_ERROR, BRIX_SESS_END_TIMEOUT, c, ngx_brix_cms_arm_read_deadline(), NGX_BRIX_CMS_BACKOFF_INITIAL, ngx_brix_cms_disconnect(), ngx_brix_cms_log_registration(), ngx_brix_cms_schedule(), ngx_brix_cms_schedule_retry(), ngx_brix_cms_send_load(), ngx_brix_cms_send_login(), ngx_brix_cms_send_status(), and ngx_brix_cms_set_end_hint().
Referenced by ngx_brix_cms_connect().