nginx-xrootd: src/net/ratelimit/ratelimit.c File Reference
ratelimit.c File Reference
#include "ratelimit.h"
Functions
ngx_int_t brix_rl_check (brix_rl_rule_t *rule, const char *key_str, uint32_t *wait_seconds)
ngx_int_t brix_rl_conc_acquire (brix_rl_rule_t *rule, const char *key_str)
void brix_rl_conc_release (brix_rl_rule_t *rule, const char *key_str)
ngx_int_t brix_rl_bw_check (brix_rl_rule_t *rule, const char *key_str, uint32_t *wait_seconds)
void brix_rl_charge_bytes (brix_rl_rule_t *rule, const char *key_str, size_t nbytes)
ngx_int_t brix_rl_snapshot (brix_rl_zone_t *zone, brix_rl_snapshot_entry_t *out, ngx_uint_t max, ngx_uint_t *count)
Function Documentation
brix_rl_bw_check()
ngx_int_t brix_rl_bw_check (brix_rl_rule_t * rule, const char * key_str, uint32_t * wait_seconds)
Definition at line 159 of file ratelimit.c.
References brix_rl_hash(), brix_rl_lookup_locked(), brix_rl_rule_t::bw_burst, brix_rl_node_t::bw_excess, brix_rl_rule_t::bw_rate, brix_rl_node_t::last, brix_rl_zone_t::sh, brix_rl_zone_t::shpool, brix_rl_node_t::throttle_count, and brix_rl_rule_t::zone.
Referenced by brix_rl_http_access_handler(), and brix_rl_stream_gate().
brix_rl_charge_bytes()
void brix_rl_charge_bytes (brix_rl_rule_t * rule, const char * key_str, size_t nbytes)
Definition at line 205 of file ratelimit.c.
References brix_rl_create_locked(), brix_rl_hash(), brix_rl_lookup_locked(), brix_rl_node_t::bw_excess, brix_rl_rule_t::bw_rate, brix_rl_node_t::bytes_total, brix_rl_node_t::last, brix_rl_zone_t::sh, brix_rl_zone_t::shpool, and brix_rl_rule_t::zone.
Referenced by brix_rl_charge_ctx(), and brix_rl_http_log_handler().
brix_rl_check()
ngx_int_t brix_rl_check (brix_rl_rule_t * rule, const char * key_str, uint32_t * wait_seconds)
Definition at line 19 of file ratelimit.c.
References brix_rl_create_locked(), brix_rl_hash(), brix_rl_lookup_locked(), brix_rl_node_t::last, brix_rl_rule_t::req_burst, brix_rl_node_t::req_excess, brix_rl_rule_t::req_rate, brix_rl_node_t::req_total, brix_rl_zone_t::sh, brix_rl_zone_t::shpool, brix_rl_node_t::throttle_count, and brix_rl_rule_t::zone.
Referenced by brix_rl_http_access_handler(), and brix_rl_stream_gate().
brix_rl_conc_acquire()
ngx_int_t brix_rl_conc_acquire (brix_rl_rule_t * rule, const char * key_str)
Definition at line 89 of file ratelimit.c.
References brix_rl_create_locked(), brix_rl_hash(), brix_rl_lookup_locked(), brix_rl_node_t::in_flight, brix_rl_node_t::last, brix_rl_rule_t::req_conc, brix_rl_node_t::req_total, brix_rl_zone_t::sh, brix_rl_zone_t::shpool, brix_rl_node_t::throttle_count, and brix_rl_rule_t::zone.
Referenced by brix_rl_http_access_handler(), and brix_rl_stream_gate().
brix_rl_conc_release()
void brix_rl_conc_release (brix_rl_rule_t * rule, const char * key_str)
Definition at line 129 of file ratelimit.c.
References brix_rl_hash(), brix_rl_lookup_locked(), brix_rl_node_t::in_flight, brix_rl_rule_t::req_conc, brix_rl_zone_t::sh, brix_rl_zone_t::shpool, and brix_rl_rule_t::zone.
Referenced by brix_rl_http_access_handler(), brix_rl_http_log_handler(), and brix_rl_release_ctx().
brix_rl_snapshot()
ngx_int_t brix_rl_snapshot (brix_rl_zone_t * zone, brix_rl_snapshot_entry_t * out, ngx_uint_t max, ngx_uint_t * count)
Definition at line 249 of file ratelimit.c.
References BRIX_RL_KEY_LEN, brix_rl_node_t::bw_excess, brix_rl_snapshot_entry_t::bw_excess, brix_rl_node_t::bytes_total, brix_rl_snapshot_entry_t::bytes_total, brix_rl_snapshot_entry_t::key_str, brix_rl_node_t::key_str, brix_rl_node_t::len, ngx_memcpy, brix_rl_shctx_t::queue, brix_rl_node_t::req_excess, brix_rl_snapshot_entry_t::req_excess, brix_rl_node_t::req_total, brix_rl_snapshot_entry_t::req_total, brix_rl_zone_t::sh, brix_rl_zone_t::shpool, brix_rl_node_t::throttle_count, and brix_rl_snapshot_entry_t::throttle_count.
Referenced by dashboard_build_v1_ratelimit().