nginx-xrootd: src/net/upstream/events.c File Reference
events.c File Reference
#include "upstream_internal.h"
#include "core/compat/log_diag.h"
#include <sys/socket.h>
Functions
void brix_upstream_wait_timer_handler (ngx_event_t *ev)
void brix_upstream_write_handler (ngx_event_t *wev)
static ngx_int_t brix_upstream_recv_chunk (brix_upstream_t *up, ngx_connection_t *uconn, ngx_event_t *rev, u_char *buf, size_t *pos, size_t total, const char *again_msg, const char *closed_msg)
static ngx_int_t brix_upstream_parse_header_and_alloc (brix_upstream_t *up, ngx_connection_t *uconn)
static void brix_upstream_dispatch_response (brix_upstream_t *up)
void brix_upstream_read_handler (ngx_event_t *rev)
Function Documentation
brix_upstream_dispatch_response()
static void brix_upstream_dispatch_response (brix_upstream_t * up) static
Definition at line 210 of file events.c.
References brix_upstream_abort(), brix_upstream_forward_response(), brix_upstream_handle_bootstrap_response(), XRD_UP_ASYNC, XRD_UP_BOOTSTRAP, and XRD_UP_REQUEST.
Referenced by brix_upstream_read_handler().
brix_upstream_parse_header_and_alloc()
static ngx_int_t brix_upstream_parse_header_and_alloc (brix_upstream_t * up, ngx_connection_t * uconn) static
Definition at line 169 of file events.c.
References BRIX_MAX_PATH, brix_upstream_abort(), ServerResponseHdr::dlen, and ServerResponseHdr::status.
Referenced by brix_upstream_read_handler().
brix_upstream_read_handler()
void brix_upstream_read_handler (ngx_event_t * rev)
Definition at line 244 of file events.c.
References brix_upstream_abort(), brix_upstream_cleanup(), brix_upstream_dispatch_response(), brix_upstream_parse_header_and_alloc(), brix_upstream_recv_chunk(), brix_ctx_t::destroyed, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_upstream_start_wrap_conn().
brix_upstream_recv_chunk()
static ngx_int_t brix_upstream_recv_chunk (brix_upstream_t * up, ngx_connection_t * uconn, ngx_event_t * rev, u_char * buf, size_t * pos, size_t total, const char * again_msg, const char * closed_msg) static
Definition at line 134 of file events.c.
References brix_upstream_abort().
Referenced by brix_upstream_read_handler().
brix_upstream_wait_timer_handler()
void brix_upstream_wait_timer_handler (ngx_event_t * ev)
Definition at line 22 of file events.c.
References brix_upstream_abort(), brix_upstream_cleanup(), brix_upstream_send_request(), and brix_ctx_t::destroyed.
Referenced by brix_upstream_forward_response().
brix_upstream_write_handler()
void brix_upstream_write_handler (ngx_event_t * wev)
Definition at line 53 of file events.c.
References BRIX_DIAG_ERR, brix_upstream_abort(), brix_upstream_cleanup(), brix_upstream_flush(), brix_ctx_t::destroyed, XRD_UP_BOOTSTRAP, XRD_UP_BS_HANDSHAKE, and XRD_UP_CONNECTING.
Referenced by brix_upstream_start_wrap_conn().