nginx-xrootd: src/net/manager/registry.h File Reference
registry.h File Reference
#include "core/ngx_brix_module.h"
Data Structures
struct brix_srv_entry_t
struct brix_srv_table_t
struct brix_srv_snapshot_entry_t
Macros
#define BRIX_SRV_REGISTRY_SLOTS 128 /* default; overridden by brix_registry_slots */
#define BRIX_SRV_MAX_PATHS 1024
Functions
ngx_int_t brix_srv_shm_init_zone (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t brix_srv_configure_registry (ngx_conf_t *cf, ngx_uint_t slots)
void brix_srv_register (const char *host, uint16_t port, const char *paths, uint32_t free_mb, uint32_t util_pct)
void brix_srv_update_load (const char *host, uint16_t port, uint32_t free_mb, uint32_t util_pct)
void brix_srv_unregister (const char *host, uint16_t port)
void brix_srv_blacklist (const char *host, uint16_t port, ngx_msec_t duration_ms)
int brix_srv_undrain (const char *host, uint16_t port)
int brix_srv_reset (const char *host, uint16_t port)
void brix_srv_set_vnid (const char *host, uint16_t port, const char *vnid)
void brix_srv_set_stage (const char *host, uint16_t port, ngx_uint_t stage)
void brix_srv_set_machine_load (const char *host, uint16_t port, uint32_t load_pct)
void brix_srv_set_load_weight (ngx_uint_t weight)
void brix_srv_set_affinity (ngx_uint_t on)
int brix_srv_hc_claim (char *host_out, size_t host_size, uint16_t *port_out, ngx_msec_t interval_ms, ngx_msec_t *next_due_ms)
void brix_srv_hc_pass (const char *host, uint16_t port)
int brix_srv_hc_fail (const char *host, uint16_t port, uint32_t threshold, ngx_msec_t blacklist_ms)
void brix_srv_unregister_path (const char *host, uint16_t port, const char *path)
int brix_srv_select (const char *path, int for_write, char *host_out, size_t host_size, uint16_t *port_out)
int brix_srv_count_matching (const char *path)
int brix_srv_paths_cover (const char *paths, const char *path)
int brix_srv_is_blacklisted (const char *host, uint16_t port)
int brix_srv_select_or_blacklisted (const char *path, int for_write, char *host_out, size_t host_size, uint16_t *port_out)
void brix_srv_set_stale_after (ngx_msec_t ms)
int brix_manager_tried_exhausted (const u_char *payload, size_t payload_len, const char *clean_path)
int brix_srv_locate_all (const char *path, int for_write, char *buf, size_t bufsz)
void brix_srv_aggregate_space (uint32_t *total_free_mb, uint32_t *avg_util_pct)
ngx_uint_t brix_srv_snapshot (brix_srv_snapshot_entry_t *out, ngx_uint_t max_entries, ngx_msec_t now)
Variables
ngx_shm_zone_t * brix_srv_shm_zone
Macro Definition Documentation
BRIX_SRV_MAX_PATHS
#define BRIX_SRV_MAX_PATHS 1024
Definition at line 25 of file registry.h.
BRIX_SRV_REGISTRY_SLOTS
#define BRIX_SRV_REGISTRY_SLOTS 128 /* default; overridden by brix_registry_slots */
Definition at line 24 of file registry.h.
Function Documentation
brix_manager_tried_exhausted()
int brix_manager_tried_exhausted (const u_char * payload, size_t payload_len, const char * clean_path)
Definition at line 425 of file registry_select.c.
References brix_srv_count_matching(), and ngx_memcpy.
Referenced by brix_open_manager_redirect(), brix_qcksum_manager_bounce(), and stat_manager_route().
brix_srv_aggregate_space()
void brix_srv_aggregate_space (uint32_t * total_free_mb, uint32_t * avg_util_pct)
Definition at line 311 of file registry_health.c.
References brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::free_mb, brix_srv_entry_t::in_use, brix_srv_table_t::slots, srv_table(), and brix_srv_entry_t::util_pct.
Referenced by cms_srv_frame_statfs(), cms_srv_frame_usage(), ngx_brix_cms_send_avail(), ngx_brix_cms_send_load(), and ngx_brix_cms_send_login().
brix_srv_blacklist()
void brix_srv_blacklist (const char * host, uint16_t port, ngx_msec_t duration_ms)
Definition at line 28 of file registry_select_blacklist.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::error_count, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, port, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by admin_cluster_drain(), brix_cms_blfile_poll(), brix_cms_srv_close(), and cms_srv_frame_status().
brix_srv_configure_registry()
ngx_int_t brix_srv_configure_registry (ngx_conf_t * cf, ngx_uint_t slots)
Definition at line 113 of file registry.c.
brix_srv_count_matching()
int brix_srv_count_matching (const char * path)
Definition at line 381 of file registry_select.c.
References brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::in_use, brix_srv_entry_t::paths, brix_srv_table_t::slots, srv_path_matches(), and srv_table().
Referenced by brix_cms_fanout_mutation(), brix_manager_tried_exhausted(), and cms_srv_frame_statfs().
brix_srv_hc_claim()
int brix_srv_hc_claim (char * host_out, size_t host_size, uint16_t * port_out, ngx_msec_t interval_ms, ngx_msec_t * next_due_ms)
Definition at line 10 of file registry_health.c.
References brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::hc_in_progress, brix_srv_entry_t::hc_next_check, brix_srv_entry_t::host, brix_srv_entry_t::in_use, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by brix_hc_timer_handler().
brix_srv_hc_fail()
int brix_srv_hc_fail (const char * host, uint16_t port, uint32_t threshold, ngx_msec_t blacklist_ms)
Definition at line 102 of file registry_health.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::hc_fail_count, brix_srv_entry_t::hc_in_progress, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, port, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by brix_hc_ctx_create(), brix_hc_finish(), brix_hc_pre_connect_fail(), and brix_hc_resolve().
brix_srv_hc_pass()
void brix_srv_hc_pass (const char * host, uint16_t port)
Definition at line 66 of file registry_health.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::hc_fail_count, brix_srv_entry_t::hc_in_progress, brix_srv_entry_t::hc_last_ok, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, port, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by brix_hc_finish().
brix_srv_is_blacklisted()
int brix_srv_is_blacklisted (const char * host, uint16_t port)
Definition at line 110 of file registry_select_blacklist.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_mutex, brix_srv_table_t::capacity, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, port, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by brix_cms_fanout_collect_eligible(), cms_srv_frame_have(), and locate_try_dynamic().
brix_srv_locate_all()
int brix_srv_locate_all (const char * path, int for_write, char * buf, size_t bufsz)
Definition at line 160 of file registry_health.c.
References brix_srv_entry_t::blacklisted_until, brix_format_host_port(), brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::host, brix_srv_entry_t::in_use, ngx_memcpy, brix_srv_entry_t::paths, brix_srv_entry_t::port, brix_srv_table_t::slots, srv_path_matches(), and srv_table().
Referenced by locate_try_manager().
brix_srv_paths_cover()
int brix_srv_paths_cover (const char * paths, const char * path)
Definition at line 99 of file registry_select_blacklist.c.
References srv_path_matches().
Referenced by brix_cms_fanout_collect_eligible(), cms_srv_frame_have(), and locate_try_dynamic().
brix_srv_register()
void brix_srv_register (const char * host, uint16_t port, const char * paths, uint32_t free_mb, uint32_t util_pct)
Definition at line 156 of file registry.c.
References brix_srv_entry_t::blacklisted_until, brix_metrics_shared(), brix_net_host_chars_valid(), brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::error_count, brix_srv_entry_t::free_mb, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, brix_srv_entry_t::last_seen, brix_srv_entry_t::paths, port, brix_srv_entry_t::port, ngx_brix_metrics_t::registry_full_total, brix_srv_table_t::slots, srv_table(), and brix_srv_entry_t::util_pct.
Referenced by admin_cluster_register(), brix_cache_fill_done(), and cms_srv_complete_login().
brix_srv_reset()
int brix_srv_reset (const char * host, uint16_t port)
Definition at line 362 of file registry.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_mutex, brix_srv_entry_t::error_count, brix_srv_entry_t::free_mb, brix_srv_entry_t::hc_fail_count, brix_srv_entry_t::hc_in_progress, host, brix_srv_entry_t::last_seen, brix_srv_entry_t::load_pct, port, srv_find_locked(), srv_table(), and brix_srv_entry_t::util_pct.
Referenced by cms_srv_frame_status().
brix_srv_select()
int brix_srv_select (const char * path, int for_write, char * host_out, size_t host_size, uint16_t * port_out)
Definition at line 347 of file registry_select.c.
References srv_select_core().
Referenced by brix_dirlist_check_redirect(), brix_qcksum_manager_bounce(), cms_frame_state(), locate_try_manager(), and tpc_handle_dest().
brix_srv_select_or_blacklisted()
int brix_srv_select_or_blacklisted (const char * path, int for_write, char * host_out, size_t host_size, uint16_t * port_out)
Definition at line 358 of file registry_select.c.
References srv_select_core().
Referenced by brix_open_manager_redirect(), manager_redirect_mutation(), and stat_manager_route().
brix_srv_set_affinity()
void brix_srv_set_affinity (ngx_uint_t on)
Definition at line 34 of file registry.c.
References brix_srv_affinity.
Referenced by brix_merge_srv_cms().
brix_srv_set_load_weight()
void brix_srv_set_load_weight (ngx_uint_t weight)
Definition at line 27 of file registry.c.
References brix_srv_load_weight.
Referenced by brix_merge_srv_cms().
brix_srv_set_machine_load()
void brix_srv_set_machine_load (const char * host, uint16_t port, uint32_t load_pct)
Definition at line 431 of file registry.c.
References brix_srv_mutex, host, brix_srv_entry_t::load_pct, port, srv_find_locked(), and srv_table().
Referenced by cms_srv_frame_load().
brix_srv_set_stage()
void brix_srv_set_stage (const char * host, uint16_t port, ngx_uint_t stage)
Definition at line 412 of file registry.c.
References brix_srv_mutex, host, port, srv_find_locked(), srv_table(), and brix_srv_entry_t::stage.
Referenced by cms_srv_frame_status().
brix_srv_set_stale_after()
void brix_srv_set_stale_after (ngx_msec_t ms)
Definition at line 20 of file registry.c.
References brix_srv_stale_after_ms.
Referenced by brix_merge_srv_net_fault().
brix_srv_set_vnid()
void brix_srv_set_vnid (const char * host, uint16_t port, const char * vnid)
Definition at line 392 of file registry.c.
References brix_srv_mutex, host, port, srv_find_locked(), srv_table(), and brix_srv_entry_t::vnid.
Referenced by cms_srv_complete_login().
brix_srv_shm_init_zone()
ngx_int_t brix_srv_shm_init_zone (ngx_shm_zone_t * shm_zone, void * data)
Definition at line 73 of file registry.c.
References brix_shm_table_alloc(), brix_srv_mutex, brix_srv_registry_nslots, and brix_srv_table_t::capacity.
Referenced by brix_srv_configure_registry().
brix_srv_snapshot()
ngx_uint_t brix_srv_snapshot (brix_srv_snapshot_entry_t * out, ngx_uint_t max_entries, ngx_msec_t now)
Definition at line 352 of file registry_health.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_snapshot_entry_t::blacklisted_until, brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::error_count, brix_srv_snapshot_entry_t::error_count, brix_srv_entry_t::free_mb, brix_srv_snapshot_entry_t::free_mb, brix_srv_entry_t::hc_fail_count, brix_srv_snapshot_entry_t::hc_fail_count, brix_srv_entry_t::hc_last_ok, brix_srv_snapshot_entry_t::hc_last_ok, host, brix_srv_entry_t::host, brix_srv_snapshot_entry_t::host, brix_srv_entry_t::in_use, brix_srv_entry_t::last_seen, brix_srv_snapshot_entry_t::last_seen, brix_srv_entry_t::load_pct, brix_srv_snapshot_entry_t::load_pct, brix_srv_entry_t::paths, brix_srv_snapshot_entry_t::paths, brix_srv_entry_t::port, brix_srv_snapshot_entry_t::port, brix_srv_table_t::slots, srv_table(), brix_srv_entry_t::stage, brix_srv_snapshot_entry_t::stage, brix_srv_entry_t::util_pct, brix_srv_snapshot_entry_t::util_pct, brix_srv_entry_t::vnid, and brix_srv_snapshot_entry_t::vnid.
Referenced by brix_cms_blfile_poll(), brix_export_cluster_metrics(), and dashboard_fill_cluster().
brix_srv_undrain()
int brix_srv_undrain (const char * host, uint16_t port)
Definition at line 64 of file registry_select_blacklist.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::error_count, brix_srv_entry_t::hc_fail_count, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, port, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by admin_cluster_undrain(), and cms_srv_frame_status().
brix_srv_unregister()
void brix_srv_unregister (const char * host, uint16_t port)
Definition at line 300 of file registry.c.
References brix_srv_mutex, brix_srv_table_t::capacity, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, port, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by admin_cluster_delete().
brix_srv_unregister_path()
void brix_srv_unregister_path (const char * host, uint16_t port, const char * path)
Definition at line 236 of file registry_health.c.
References brix_srv_mutex, brix_srv_table_t::capacity, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, ngx_memcpy, brix_srv_entry_t::paths, port, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by brix_cache_evict_unregister(), and cms_srv_frame_gone().
brix_srv_update_load()
void brix_srv_update_load (const char * host, uint16_t port, uint32_t free_mb, uint32_t util_pct)
Definition at line 256 of file registry.c.
References brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::free_mb, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, brix_srv_entry_t::last_seen, port, brix_srv_entry_t::port, brix_srv_table_t::slots, srv_table(), and brix_srv_entry_t::util_pct.
Referenced by cms_srv_frame_avail(), and cms_srv_frame_load().
Variable Documentation
brix_srv_shm_zone
ngx_shm_zone_t* brix_srv_shm_zone extern
Definition at line 7 of file registry.c.
Referenced by brix_export_cluster_metrics(), brix_srv_configure_registry(), and srv_table().