nginx-xrootd: src/net/cms/recv.c File Reference
recv.c File Reference
#include "cms_internal.h"
#include "fs/vfs/vfs.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "node_ops.h"
#include "rrdata.h"
#include "router.h"
#include "net/manager/pending.h"
#include "net/manager/registry.h"
#include "fs/path/beneath.h"
#include "fs/path/path.h"
#include "core/compat/net_target.h"
#include "observability/metrics/metrics_macros.h"
#include <errno.h>
#include <unistd.h>
Functions
static ngx_connection_t * cms_find_client_connection (int fd)
static int cms_node_exec_driver (brix_sd_instance_t *sd, const char *root_canon, const brix_cms_node_plan_t *plan, ngx_log_t *log, int *handled)
static ngx_int_t cms_node_exec_forward (ngx_brix_cms_ctx_t *ctx, u_char code, uint32_t streamid, const u_char *payload, size_t plen)
static ngx_int_t cms_wake_pending_session (ngx_brix_cms_ctx_t *cms_ctx, uint32_t streamid, const char *host, uint16_t port)
static ngx_int_t ngx_brix_cms_process_frame (ngx_brix_cms_ctx_t *ctx)
void ngx_brix_cms_read_handler (ngx_event_t *ev)
Function Documentation
cms_find_client_connection()
static ngx_connection_t * cms_find_client_connection (int fd) static
Definition at line 288 of file recv.c.
References c.
Referenced by cms_wake_pending_session().
cms_node_exec_driver()
static int cms_node_exec_driver (brix_sd_instance_t * sd, const char * root_canon, const brix_cms_node_plan_t * plan, ngx_log_t * log, int * handled) static
Definition at line 29 of file recv.c.
References brix_cms_node_plan_t::action, BRIX_SD_O_WRITE, brix_vfs_backend_mkpath(), log, brix_sd_setattr_t::mode, brix_cms_node_plan_t::mode, brix_cms_node_plan_t::path, brix_cms_node_plan_t::path2, brix_sd_setattr_t::set_mode, brix_cms_node_plan_t::size, XRDCMS_NACT_CHMOD, XRDCMS_NACT_MKDIR, XRDCMS_NACT_MKPATH, XRDCMS_NACT_MV, XRDCMS_NACT_RM, XRDCMS_NACT_RMDIR, and XRDCMS_NACT_TRUNC.
Referenced by cms_node_exec_forward().
cms_node_exec_forward()
static ngx_int_t cms_node_exec_forward (ngx_brix_cms_ctx_t * ctx, u_char code, uint32_t streamid, const u_char * payload, size_t plen) static
Definition at line 95 of file recv.c.
References brix_cms_node_plan_t::action, brix_beneath_full_path(), brix_cms_node_plan(), brix_cms_rrdata_parse(), brix_mkdir_beneath(), brix_mkdir_recursive_beneath(), brix_rename_beneath(), brix_sd_default_driver(), brix_vfs_backend_resolve(), brix_vfs_open_fd_at(), brix_vfs_unlink_at(), close(), CMS_ERR_EINVAL, cms_node_exec_driver(), brix_cms_node_plan_t::mode, ngx_brix_cms_send_error(), brix_cms_node_plan_t::path, brix_cms_node_plan_t::path2, PATH_MAX, brix_cms_node_plan_t::size, XRDCMS_NACT_CHMOD, XRDCMS_NACT_MKDIR, XRDCMS_NACT_MKPATH, XRDCMS_NACT_MV, XRDCMS_NACT_RM, XRDCMS_NACT_RMDIR, and XRDCMS_NACT_TRUNC.
Referenced by ngx_brix_cms_process_frame().
cms_wake_pending_session()
static ngx_int_t cms_wake_pending_session (ngx_brix_cms_ctx_t * cms_ctx, uint32_t streamid, const char * host, uint16_t port) static
Definition at line 207 of file recv.c.
References brix_net_host_chars_valid(), brix_pending_lookup(), brix_pending_remove(), brix_pending_unlock(), brix_sanitize_log_string(), brix_schedule_read_resume(), brix_send_redirect(), brix_pending_locate_t::client_streamid, cms_find_client_connection(), brix_pending_locate_t::conn_fd, brix_pending_locate_t::conn_number, brix_ctx_recv_t::cur_streamid, ngx_stream_brix_module, brix_ctx_t::recv, brix_ctx_t::state, XRD_ST_REQ_HEADER, and XRD_ST_WAITING_CMS.
Referenced by ngx_brix_cms_process_frame().
ngx_brix_cms_process_frame()
static ngx_int_t ngx_brix_cms_process_frame (ngx_brix_cms_ctx_t * ctx) static
Definition at line 321 of file recv.c.
References brix_cms_route_lookup(), brix_srv_select(), brix_stat_beneath(), cms_node_exec_forward(), CMS_RR_CHMOD, CMS_RR_DISC, CMS_RR_MKDIR, CMS_RR_MKPATH, CMS_RR_MV, CMS_RR_PING, CMS_RR_RM, CMS_RR_RMDIR, CMS_RR_SELECT, CMS_RR_SPACE, CMS_RR_STATE, CMS_RR_STATUS, CMS_RR_TRUNC, CMS_RR_TRY, CMS_RR_UPDATE, CMS_ST_RESUME, CMS_ST_SUSPEND, cms_wake_pending_session(), brix_cms_route_t::name, ngx_brix_cms_disconnect(), ngx_brix_cms_get16(), ngx_brix_cms_get32(), NGX_BRIX_CMS_HDR_LEN, ngx_brix_cms_schedule_retry(), ngx_brix_cms_send_avail(), ngx_brix_cms_send_have(), ngx_brix_cms_send_pong(), ngx_brix_cms_send_status(), stat(), and XRDCMS_ROLE_NODE.
Referenced by ngx_brix_cms_read_handler().
ngx_brix_cms_read_handler()
void ngx_brix_cms_read_handler (ngx_event_t * ev)
Definition at line 550 of file recv.c.
References BRIX_RESIL_METRIC_INC, c, ngx_brix_cms_arm_read_deadline(), ngx_brix_cms_disconnect(), ngx_brix_cms_get16(), NGX_BRIX_CMS_HDR_LEN, NGX_BRIX_CMS_MAX_FRAME, NGX_BRIX_CMS_MAX_FRAMES_PER_WAKEUP, ngx_brix_cms_process_frame(), and ngx_brix_cms_schedule_retry().
Referenced by ngx_brix_cms_connect().