nginx-xrootd: src/net/cms/space.c File Reference
space.c File Reference
#include "cms_internal.h"
Functions
ngx_str_t ngx_brix_cms_export_paths (ngx_stream_brix_srv_conf_t *conf)
ngx_int_t ngx_brix_cms_stat_space (ngx_stream_brix_srv_conf_t *conf, uint32_t *total_gb, uint32_t *free_mb, uint32_t *util_pct)
Function Documentation
ngx_brix_cms_export_paths()
ngx_str_t ngx_brix_cms_export_paths (ngx_stream_brix_srv_conf_t * conf)
Definition at line 7 of file space.c.
Referenced by ngx_brix_cms_send_login().
ngx_brix_cms_stat_space()
ngx_int_t ngx_brix_cms_stat_space (ngx_stream_brix_srv_conf_t * conf, uint32_t * total_gb, uint32_t * free_mb, uint32_t * util_pct)
Definition at line 20 of file space.c.
Referenced by ngx_brix_cms_send_avail(), ngx_brix_cms_send_load(), and ngx_brix_cms_send_login().