nginx-xrootd: src/net/upstream/request.c File Reference
request.c File Reference
#include "upstream_internal.h"
#include <string.h>
#include "core/compat/alloc_guard.h"
Functions
ngx_int_t brix_upstream_send_request (brix_upstream_t *up)
ngx_int_t brix_upstream_flush (brix_upstream_t *up)
Function Documentation
brix_upstream_flush()
ngx_int_t brix_upstream_flush (brix_upstream_t * up)
Definition at line 101 of file request.c.
Referenced by brix_upstream_send_request(), brix_upstream_send_token_auth(), brix_upstream_start(), and brix_upstream_write_handler().
brix_upstream_send_request()
ngx_int_t brix_upstream_send_request (brix_upstream_t * up)
Definition at line 29 of file request.c.
References BRIX_PALLOC_OR_RETURN, brix_upstream_flush(), ClientOpenRequest::dlen, ClientStatRequest::dlen, ClientLocateRequest::dlen, kXR_locate, kXR_open, kXR_stat, xrdw_open_req_t::mode, ngx_memcpy, xrdw_locate_req_t::options, ClientOpenRequest::requestid, ClientStatRequest::requestid, ClientLocateRequest::requestid, ClientOpenRequest::streamid, ClientStatRequest::streamid, ClientLocateRequest::streamid, XRD_REQUEST_HDR_LEN, XRD_UP_REQUEST, xrdw_locate_req_pack(), and xrdw_open_req_pack().
Referenced by brix_upstream_handle_bootstrap_response(), and brix_upstream_wait_timer_handler().