nginx-xrootd: src/protocols/root/connection/netconnect.h File Reference
netconnect.h File Reference
#include <ngx_core.h>
#include <ngx_event.h>
#include "core/compat/af_policy.h"
#include <errno.h>
#include <fcntl.h>
#include <netdb.h>
#include <poll.h>
#include <stdio.h>
#include <sys/socket.h>
#include <sys/time.h>
Enumerations
enum brix_resolve_status_t { BRIX_RESOLVE_OK = 0 , BRIX_RESOLVE_ERR_DNS , BRIX_RESOLVE_ERR_SOCKET }
Functions
static int brix_resolve_connect_socket (const char *host, unsigned port, brix_af_policy_t af_policy, struct sockaddr_storage *addr_out, socklen_t *addrlen_out, brix_resolve_status_t *status_out)
static void brix_apply_socket_io_timeouts (int fd, long timeout_secs)
static int brix_connect_fd_deadline (int fd, const struct sockaddr *addr, socklen_t addrlen, int timeout_ms)
Enumeration Type Documentation
brix_resolve_status_t
enum brix_resolve_status_t
Enumerator
BRIX_RESOLVE_OK
BRIX_RESOLVE_ERR_DNS
BRIX_RESOLVE_ERR_SOCKET
Definition at line 45 of file netconnect.h.
Function Documentation
brix_apply_socket_io_timeouts()
static void brix_apply_socket_io_timeouts (int fd, long timeout_secs) inline static
Definition at line 118 of file netconnect.h.
Referenced by brix_cache_origin_connect_addr(), ocsp_set_io_timeouts(), and tpc_connect().
brix_connect_fd_deadline()
static int brix_connect_fd_deadline (int fd, const struct sockaddr * addr, socklen_t addrlen, int timeout_ms) inline static
Definition at line 140 of file netconnect.h.
Referenced by brix_cache_origin_connect_addr(), and tpc_connect().
brix_resolve_connect_socket()
static int brix_resolve_connect_socket (const char * host, unsigned port, brix_af_policy_t af_policy, struct sockaddr_storage * addr_out, socklen_t * addrlen_out, brix_resolve_status_t * status_out) inline static
Definition at line 67 of file netconnect.h.
References BRIX_RESOLVE_ERR_DNS, BRIX_RESOLVE_ERR_SOCKET, BRIX_RESOLVE_OK, host, ngx_memcpy, and port.
Referenced by brix_upstream_start_resolve_socket(), and pc_resolve_target().