nginx-xrootd: src/protocols/root/connection/netopt.h File Reference
netopt.h File Reference
#include <ngx_core.h>
#include <ngx_event.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
Functions
static void brix_apply_tcp_deadpeer_opts (ngx_socket_t fd, ngx_flag_t keepalive, ngx_msec_t user_timeout_ms)
static void brix_apply_tcp_congestion (ngx_socket_t fd, ngx_str_t algo)
Function Documentation
brix_apply_tcp_congestion()
static void brix_apply_tcp_congestion (ngx_socket_t fd, ngx_str_t algo) inline static
Definition at line 83 of file netopt.h.
Referenced by brix_http_serve_file_ranged(), and ngx_stream_brix_handler().
brix_apply_tcp_deadpeer_opts()
static void brix_apply_tcp_deadpeer_opts (ngx_socket_t fd, ngx_flag_t keepalive, ngx_msec_t user_timeout_ms) inline static
Definition at line 39 of file netopt.h.
Referenced by brix_cms_srv_handler(), ngx_brix_cms_connect(), and ngx_stream_brix_handler().