nginx-xrootd: client/lib/net/netpref.c File Reference
netpref.c File Reference
#include "brix.h"
#include <stdatomic.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
Functions
static int fallback_enabled (void)
int brix_netpref_family (void)
int brix_netpref_demoted (void)
void brix_netpref_disable (void)
static void do_demote (const char *cause)
void brix_netpref_demote_ipv6 (const char *host)
void brix_netpref_note_wire_error (int family)
void brix_netpref_undo_demote (const char *why)
Variables
static atomic_int g_demoted = 0
static atomic_int g_logged = 0
static atomic_int g_revert_logged = 0
static atomic_int g_enabled = -1
Function Documentation
brix_netpref_demote_ipv6()
void brix_netpref_demote_ipv6 (const char * host)
Definition at line 105 of file netpref.c.
References do_demote(), and fallback_enabled().
Referenced by connect_resolved().
brix_netpref_demoted()
int brix_netpref_demoted (void)
Definition at line 74 of file netpref.c.
References g_demoted.
brix_netpref_disable()
void brix_netpref_disable (void)
Definition at line 80 of file netpref.c.
References g_enabled.
brix_netpref_family()
int brix_netpref_family (void)
Definition at line 67 of file netpref.c.
References g_demoted.
Referenced by brix_tcp_connect(), and resolve_once().
brix_netpref_note_wire_error()
void brix_netpref_note_wire_error (int family)
Definition at line 117 of file netpref.c.
References do_demote(), fallback_enabled(), and g_demoted.
Referenced by note_io_failure().
brix_netpref_undo_demote()
void brix_netpref_undo_demote (const char * why)
Definition at line 134 of file netpref.c.
References g_demoted, and g_revert_logged.
Referenced by brix_tcp_connect().
do_demote()
static void do_demote (const char * cause) static
Definition at line 92 of file netpref.c.
References g_demoted, and g_logged.
Referenced by brix_netpref_demote_ipv6(), and brix_netpref_note_wire_error().
fallback_enabled()
static int fallback_enabled (void) static
Definition at line 55 of file netpref.c.
References g_enabled.
Referenced by brix_netpref_demote_ipv6(), and brix_netpref_note_wire_error().
Variable Documentation
g_demoted
atomic_int g_demoted = 0 static
Definition at line 40 of file netpref.c.
Referenced by brix_netpref_demoted(), brix_netpref_family(), brix_netpref_note_wire_error(), brix_netpref_undo_demote(), and do_demote().
g_enabled
atomic_int g_enabled = -1 static
Definition at line 46 of file netpref.c.
Referenced by brix_netpref_disable(), and fallback_enabled().
g_logged
atomic_int g_logged = 0 static
Definition at line 42 of file netpref.c.
Referenced by do_demote().
g_revert_logged
atomic_int g_revert_logged = 0 static
Definition at line 44 of file netpref.c.
Referenced by brix_netpref_undo_demote().