nginx-xrootd: client/lib/net/nettmo.c File Reference
nettmo.c File Reference
#include "brix.h"
#include <stdatomic.h>
#include <stdlib.h>
#include <time.h>
Macros
#define XRDC_TMO_CONNECT_DEFAULT_MS 15000 /* bring-up: connect+handshake+login */
#define XRDC_TMO_IO_DEFAULT_MS 30000 /* steady-state read/write */
Functions
static int resolve_ms (atomic_int *slot, const char *env, const char *xrdrc_key, int dflt)
int brix_tmo_connect_ms (void)
int brix_tmo_io_ms (void)
int brix_tmo_stall_ms (void)
void brix_tmo_set_stall_ms (int ms)
void brix_tmo_set_connect_ms (int ms)
void brix_tmo_set_io_ms (int ms)
unsigned brix_backoff_delay_ms (unsigned attempt, uint64_t *seed)
static unsigned backoff_base_ms (void)
unsigned brix_backoff_delay_fast_ms (unsigned attempt, uint64_t *seed)
static void sleep_ms_cancelable (unsigned ms)
void brix_backoff_sleep (unsigned attempt)
void brix_backoff_sleep_fast (unsigned attempt)
Variables
static atomic_int g_connect_ms = 0
static atomic_int g_io_ms = 0
static atomic_int g_stall_ms = 0
Macro Definition Documentation
XRDC_TMO_CONNECT_DEFAULT_MS
#define XRDC_TMO_CONNECT_DEFAULT_MS 15000 /* bring-up: connect+handshake+login */
Definition at line 37 of file nettmo.c.
XRDC_TMO_IO_DEFAULT_MS
#define XRDC_TMO_IO_DEFAULT_MS 30000 /* steady-state read/write */
Definition at line 38 of file nettmo.c.
Function Documentation
backoff_base_ms()
static unsigned backoff_base_ms (void) static
Definition at line 165 of file nettmo.c.
References brix_xrdrc_default_ms().
Referenced by brix_backoff_delay_fast_ms().
brix_backoff_delay_fast_ms()
unsigned brix_backoff_delay_fast_ms (unsigned attempt, uint64_t * seed)
Definition at line 191 of file nettmo.c.
References backoff_base_ms(), and s.
Referenced by brix_backoff_sleep_fast().
brix_backoff_delay_ms()
unsigned brix_backoff_delay_ms (unsigned attempt, uint64_t * seed)
Definition at line 128 of file nettmo.c.
References s.
Referenced by brix_backoff_sleep().
brix_backoff_sleep()
void brix_backoff_sleep (unsigned attempt)
Definition at line 232 of file nettmo.c.
References brix_backoff_delay_ms(), brix_mono_ns(), and sleep_ms_cancelable().
brix_backoff_sleep_fast()
void brix_backoff_sleep_fast (unsigned attempt)
Definition at line 242 of file nettmo.c.
References brix_backoff_delay_fast_ms(), brix_mono_ns(), and sleep_ms_cancelable().
Referenced by brix_connect_resilient(), brix_fuse_run(), brix_http_download(), brix_http_upload_resumable(), brix_mfile_pread(), brix_mfile_pwrite(), brix_rfile_open_read(), brix_rfile_open_write(), brix_rfile_pread(), brix_rfile_pwrite(), brix_roundtrip_resilient(), brix_webfile_pread(), brix_webmeta_propfind(), brix_with_resilience(), csctx_retry_gate(), pump_sink_remote(), pump_src_remote(), resilient_setup(), upload_close_commit_resilient(), and xfs_readlink().
brix_tmo_connect_ms()
int brix_tmo_connect_ms (void)
Definition at line 78 of file nettmo.c.
References g_connect_ms, resolve_ms(), and XRDC_TMO_CONNECT_DEFAULT_MS.
Referenced by brix_bringup_ex().
brix_tmo_io_ms()
int brix_tmo_io_ms (void)
Definition at line 85 of file nettmo.c.
References g_io_ms, resolve_ms(), and XRDC_TMO_IO_DEFAULT_MS.
Referenced by brix_bringup_ex(), brix_connect(), and brix_connect_no_login().
brix_tmo_set_connect_ms()
void brix_tmo_set_connect_ms (int ms)
Definition at line 112 of file nettmo.c.
References g_connect_ms.
Referenced by aio_opt_conn_value(), and xfs_opt_value().
brix_tmo_set_io_ms()
void brix_tmo_set_io_ms (int ms)
Definition at line 120 of file nettmo.c.
References g_io_ms.
Referenced by aio_opt_conn_value(), and xfs_opt_value().
brix_tmo_set_stall_ms()
void brix_tmo_set_stall_ms (int ms)
Definition at line 104 of file nettmo.c.
References g_stall_ms.
brix_tmo_stall_ms()
int brix_tmo_stall_ms (void)
Definition at line 97 of file nettmo.c.
References g_stall_ms, and resolve_ms().
Referenced by brix_bringup_ex().
resolve_ms()
static int resolve_ms (atomic_int * slot, const char * env, const char * xrdrc_key, int dflt) static
Definition at line 56 of file nettmo.c.
References brix_xrdrc_default_ms().
Referenced by brix_tmo_connect_ms(), brix_tmo_io_ms(), and brix_tmo_stall_ms().
sleep_ms_cancelable()
static void sleep_ms_cancelable (unsigned ms) static
Definition at line 217 of file nettmo.c.
References brix_copy_quit_requested().
Referenced by brix_backoff_sleep(), and brix_backoff_sleep_fast().
Variable Documentation
g_connect_ms
atomic_int g_connect_ms = 0 static
Definition at line 41 of file nettmo.c.
Referenced by brix_tmo_connect_ms(), and brix_tmo_set_connect_ms().
g_io_ms
atomic_int g_io_ms = 0 static
Definition at line 42 of file nettmo.c.
Referenced by brix_tmo_io_ms(), and brix_tmo_set_io_ms().
g_stall_ms
atomic_int g_stall_ms = 0 static
Definition at line 94 of file nettmo.c.
Referenced by brix_tmo_set_stall_ms(), and brix_tmo_stall_ms().