nginx-xrootd: src/core/ngx_brix_module.h File Reference
ngx_brix_module.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_stream.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <sys/types.h>
#include <sys/xattr.h>
#include <fcntl.h>
#include <dirent.h>
#include <limits.h>
#include <arpa/inet.h>
#include <regex.h>
#include <openssl/ssl.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/pem.h>
#include <openssl/err.h>
#include <openssl/evp.h>
#include <openssl/bn.h>
#include <openssl/rand.h>
#include <openssl/rsa.h>
#include <openssl/params.h>
#include <openssl/param_build.h>
#include <openssl/core_names.h>
#include "protocols/root/protocol/protocol.h"
#include "observability/metrics/metrics.h"
#include "observability/dashboard/dashboard.h"
#include "auth/token/token.h"
#include <ngx_thread_pool.h>
#include "core/compat/err_strings.h"
#include "core/compat/error_mapping.h"
#include "core/config/merge_macros.h"
#include "fs/path/beneath.h"
#include "core/types/tunables.h"
#include "core/types/identity.h"
#include "core/types/state.h"
#include "core/types/file.h"
#include "core/types/context.h"
#include "core/types/config.h"
#include "protocols/root/connection/handler.h"
#include "protocols/root/connection/event_sched.h"
#include "protocols/root/connection/write_helpers.h"
#include "protocols/root/connection/tls.h"
#include "protocols/root/connection/fd_table.h"
#include "protocols/root/connection/disconnect.h"
#include "protocols/root/connection/chain_helpers.h"
#include "protocols/root/session/session.h"
#include "protocols/root/read/stat.h"
#include "protocols/root/read/open.h"
#include "protocols/root/read/read.h"
#include "protocols/root/read/statx.h"
#include "protocols/root/read/locate.h"
#include "protocols/root/read/close.h"
#include "protocols/root/fattr/ngx_brix_fattr.h"
#include "protocols/root/dirlist/dirlist.h"
#include "protocols/root/write/write.h"
#include "protocols/root/write/op_table.h"
#include "protocols/root/response/response.h"
#include "protocols/root/response/async.h"
#include "fs/path/path.h"
#include "auth/authz/auth_gate.h"
#include "protocols/root/path/op_path.h"
#include "net/upstream/upstream.h"
#include "tpc/engine/tpc_internal.h"
#include "core/aio/aio.h"
Functions
void * ngx_stream_brix_create_srv_conf (ngx_conf_t *cf)
char * ngx_stream_brix_merge_srv_conf (ngx_conf_t *cf, void *parent, void *child)
char * ngx_stream_brix_enable (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
ngx_int_t ngx_stream_brix_postconfiguration (ngx_conf_t *cf)
ngx_int_t ngx_stream_brix_init_process (ngx_cycle_t *cycle)
void brix_exit_process (ngx_cycle_t *cycle)
ngx_int_t ngx_brix_metrics_shm_init (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t brix_rebuild_gsi_store (ngx_stream_brix_srv_conf_t *xcf, ngx_log_t *log)
ngx_int_t brix_check_pki_consistency_stream (ngx_log_t *log, ngx_stream_brix_srv_conf_t *xcf)
char * brix_conf_set_require_vo (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_authdb (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_inherit_parent_group (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_manager_map (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cms_manager (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_upstream (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cache_origin_family (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cache_eviction_threshold (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cache_watermark (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cache_max_file_size (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cache_include_regex (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cache_verify (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cache_verify_digest (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cache_advertise_ns (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_wt_enable (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_wt_mode (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_wt_origin (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_wt_deny_prefix (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_wt_allow_prefix (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cache_deny_prefix (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_cache_allow_prefix (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
ngx_int_t brix_process_handshake (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_dispatch (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_check_token_scope (brix_ctx_t *ctx, const char *logical_path, int need_write)
ngx_int_t brix_handle_bind (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_handle_query (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_handle_prepare (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_handle_set (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_prepare_invoke_command (ngx_log_t *log, ngx_stream_brix_srv_conf_t *conf, const char **paths, ngx_uint_t count, ngx_flag_t coloc)
const brix_manager_map_t * brix_find_manager_map (const char *reqpath, ngx_array_t *map)
ngx_int_t brix_handle_fattr (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_cache_open_or_fill (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *clean_path, const char *cache_path, uint16_t options, uint16_t mode_bits)
ngx_int_t brix_cache_open_fill_offload (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *clean_path, const char *full_path, brix_sd_instance_t *inst, uint16_t options, uint16_t mode_bits)
void ngx_brix_cms_start (ngx_cycle_t *cycle, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_voms_init (ngx_log_t *log)
ngx_flag_t brix_voms_available (void)
ngx_int_t brix_extract_voms_info (ngx_log_t *log, X509 *leaf, STACK_OF(X509) *chain, const ngx_str_t *vomsdir, const ngx_str_t *cert_dir, char *primary_vo, size_t primary_vo_sz, char *vo_list, size_t vo_list_sz)
ngx_int_t brix_sss_build_proxy_credential (const brix_sss_key_t *key, const char *username, u_char *buf, size_t buf_max, size_t *out_len)
ngx_int_t brix_handle_unix_auth (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_handle_krb5_auth (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_handle_host_auth (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_handle_pwd_auth (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
void brix_rl_charge_ctx (brix_ctx_t *ctx, size_t nbytes)
Variables
ngx_module_t ngx_stream_brix_module
Function Documentation
brix_cache_open_fill_offload()
ngx_int_t brix_cache_open_fill_offload (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * clean_path, const char * full_path, brix_sd_instance_t * inst, uint16_t options, uint16_t mode_bits)
Definition at line 198 of file open_or_fill.c.
References brix_cache_fill_composed_done(), brix_cache_fill_composed_thread(), BRIX_OP_OPEN_RD, BRIX_RETURN_ERR, brix_cache_fill_t::c, c, cache_composed_fill_pool(), brix_cache_fill_t::cache_path, brix_cache_fill_t::clean_path, brix_cache_fill_t::conf, brix_cache_fill_t::ctx, brix_ctx_recv_t::cur_streamid, kXR_ServerError, brix_cache_fill_t::mode_bits, brix_cache_fill_t::options, brix_ctx_t::recv, brix_cache_fill_t::source_inst, brix_ctx_t::state, brix_cache_fill_t::streamid, and XRD_ST_AIO.
Referenced by brix_handle_open().
brix_cache_open_or_fill()
ngx_int_t brix_cache_open_or_fill (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * clean_path, const char * cache_path, uint16_t options, uint16_t mode_bits)
Definition at line 33 of file noop.c.
References brix_cache_append_suffix(), brix_cache_fill_done(), brix_cache_fill_thread(), BRIX_CACHE_LOCK_SUFFIX, BRIX_CACHE_PART_SUFFIX, brix_cache_ready(), BRIX_OP_OPEN_RD, brix_open_resolved_file(), BRIX_RETURN_ERR, brix_sd_backend_name(), brix_send_error(), brix_vfs_backend_resolve(), brix_cache_fill_t::c, c, ngx_stream_brix_srv_conf_t::cache_origin_host, brix_cache_fill_t::cache_path, brix_cache_fill_t::clean_path, ngx_stream_brix_srv_conf_t::common, brix_cache_fill_t::conf, brix_cache_fill_t::ctx, brix_ctx_recv_t::cur_streamid, kXR_ArgTooLong, kXR_IOError, kXR_ServerError, kXR_Unsupported, brix_cache_fill_t::lock_path, brix_cache_fill_t::mode_bits, brix_cache_fill_t::options, brix_cache_fill_t::part_path, brix_ctx_t::recv, ngx_http_brix_shared_conf_t::root_canon, brix_cache_fill_t::source_inst, brix_ctx_t::state, brix_cache_fill_t::streamid, ngx_http_brix_shared_conf_t::thread_pool, and XRD_ST_AIO.
Referenced by brix_open_cached_read().
brix_check_pki_consistency_stream()
ngx_int_t brix_check_pki_consistency_stream (ngx_log_t * log, ngx_stream_brix_srv_conf_t * xcf)
Definition at line 21 of file pki.c.
References brix_pki_check_paths(), ngx_stream_brix_srv_conf_t::crl, log, and ngx_stream_brix_srv_conf_t::trusted_ca.
Referenced by brix_configure_gsi().
brix_check_token_scope()
ngx_int_t brix_check_token_scope (brix_ctx_t * ctx, const char * logical_path, int need_write)
Definition at line 19 of file policy.c.
References brix_ctx_token_t::auth, brix_identity_check_token_scope(), brix_token_check_read(), brix_token_check_write(), brix_ctx_t::identity, brix_ctx_token_t::scope_count, brix_ctx_token_t::scopes, and brix_ctx_t::token.
Referenced by brix_auth_gate_op(), brix_handle_statx(), brix_prepare_check_path(), and brix_query_prep_status().
brix_conf_set_authdb()
char * brix_conf_set_authdb (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 13 of file policy.c.
References ngx_stream_brix_srv_conf_t::authdb, ngx_stream_brix_srv_conf_t::authdb_rules, and brix_parse_authdb().
brix_conf_set_cache_advertise_ns()
char * brix_conf_set_cache_advertise_ns (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 362 of file directives.c.
References ngx_stream_brix_srv_conf_t::advertise, BRIX_PNALLOC_OR_RETURN, ngx_memcpy, and brix_cache_advertise_conf_t::ns.
brix_conf_set_cache_allow_prefix()
char * brix_conf_set_cache_allow_prefix (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 594 of file directives.c.
References brix_conf_push_prefix(), and ngx_stream_brix_srv_conf_t::cache_allow_prefixes.
brix_conf_set_cache_deny_prefix()
char * brix_conf_set_cache_deny_prefix (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 585 of file directives.c.
References brix_conf_push_prefix(), and ngx_stream_brix_srv_conf_t::cache_deny_prefixes.
brix_conf_set_cache_eviction_threshold()
char * brix_conf_set_cache_eviction_threshold (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 46 of file directives.c.
References brix_pstrdup_z(), and ngx_stream_brix_srv_conf_t::cache_eviction_threshold.
brix_conf_set_cache_include_regex()
char * brix_conf_set_cache_include_regex (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 242 of file directives.c.
References brix_pstrdup_z(), ngx_stream_brix_srv_conf_t::include_regex, brix_cache_include_regex_conf_t::re, brix_cache_include_regex_conf_t::set, and brix_cache_include_regex_conf_t::str.
brix_conf_set_cache_max_file_size()
char * brix_conf_set_cache_max_file_size (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 168 of file directives.c.
References brix_str_cbuf(), and ngx_stream_brix_srv_conf_t::cache_max_file_size.
brix_conf_set_cache_origin_family()
char * brix_conf_set_cache_origin_family (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 25 of file directives.c.
References brix_af_policy_parse(), and ngx_stream_brix_srv_conf_t::cache_origin_family.
brix_conf_set_cache_verify()
char * brix_conf_set_cache_verify (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 288 of file directives.c.
References BRIX_CACHE_VERIFY_BESTEFFORT, BRIX_CACHE_VERIFY_OFF, BRIX_CACHE_VERIFY_REQUIRE, and ngx_stream_brix_srv_conf_t::cache_verify.
brix_conf_set_cache_verify_digest()
char * brix_conf_set_cache_verify_digest (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 323 of file directives.c.
References brix_checksum_parse(), brix_pstrdupz(), and ngx_stream_brix_srv_conf_t::cache_verify_digest.
brix_conf_set_cache_watermark()
char * brix_conf_set_cache_watermark (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 109 of file directives.c.
References brix_pstrdup_z().
brix_conf_set_cms_manager()
char * brix_conf_set_cms_manager (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 10 of file config.c.
References brix_cms_conf_t::addr, brix_copy_conf_string(), BRIX_PCALLOC_OR_RETURN, ngx_stream_brix_srv_conf_t::cms, brix_cms_conf_t::manager, ngx_memcpy, and ngx_pnalloc().
brix_conf_set_inherit_parent_group()
char * brix_conf_set_inherit_parent_group (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 85 of file policy.c.
References brix_normalize_policy_path(), ngx_stream_brix_srv_conf_t::group_rules, and brix_group_rule_t::path.
brix_conf_set_manager_map()
char * brix_conf_set_manager_map (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 16 of file manager_map.c.
References brix_normalize_policy_path(), brix_pstrdup_z(), brix_manager_map_t::host, ngx_stream_brix_srv_conf_t::manager_map, ngx_memcpy, ngx_pnalloc(), brix_manager_map_t::port, and brix_manager_map_t::prefix.
brix_conf_set_require_vo()
char * brix_conf_set_require_vo (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 46 of file policy.c.
References brix_copy_conf_string(), brix_normalize_policy_path(), brix_vo_rule_t::path, brix_vo_rule_t::vo, and ngx_stream_brix_srv_conf_t::vo_rules.
brix_conf_set_upstream()
char * brix_conf_set_upstream (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 16 of file directives.c.
References brix_pstrdup_z(), brix_pstrdupz(), ngx_memcpy, ngx_pcalloc(), ngx_pnalloc(), ngx_stream_brix_srv_conf_t::upstream_addr, ngx_stream_brix_srv_conf_t::upstream_host, and ngx_stream_brix_srv_conf_t::upstream_port.
brix_conf_set_wt_allow_prefix()
char * brix_conf_set_wt_allow_prefix (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 615 of file directives.c.
References brix_conf_add_wt_prefix().
brix_conf_set_wt_deny_prefix()
char * brix_conf_set_wt_deny_prefix (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 606 of file directives.c.
References brix_conf_add_wt_prefix().
brix_conf_set_wt_enable()
char * brix_conf_set_wt_enable (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 400 of file directives.c.
References brix_wt_conf_t::enable, and ngx_stream_brix_srv_conf_t::wt.
brix_conf_set_wt_mode()
char * brix_conf_set_wt_mode (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 431 of file directives.c.
References BRIX_WT_MODE_ASYNC, BRIX_WT_MODE_SYNC, brix_wt_conf_t::mode, and ngx_stream_brix_srv_conf_t::wt.
brix_conf_set_wt_origin()
char * brix_conf_set_wt_origin (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 460 of file directives.c.
References BRIX_PNALLOC_OR_RETURN, brix_pstrdupz(), ngx_memcpy, brix_wt_conf_t::origin_host, brix_wt_conf_t::origin_port, and ngx_stream_brix_srv_conf_t::wt.
brix_dispatch()
ngx_int_t brix_dispatch (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 31 of file dispatch.c.
References brix_ctx_login_t::auth_done, BRIX_DISPATCH_CONTINUE, brix_dispatch_read_opcode(), brix_dispatch_session_opcode(), brix_dispatch_signing_opcode(), brix_dispatch_write_opcode(), brix_imp_request_begin(), brix_imp_request_end(), brix_proxy_dispatch(), brix_rl_stream_gate(), brix_send_error(), brix_signing_enforce_level(), brix_stream_mirror_maybe(), brix_stream_wmirror_observe(), brix_verify_pending_sigver(), c, brix_ctx_recv_t::cur_reqid, brix_proxy_conf_t::enable, brix_ctx_t::identity, kXR_InvalidRequest, brix_ctx_t::login, ngx_stream_brix_srv_conf_t::proxy, brix_ctx_t::recv, and brix_ctx_t::req_start.
Referenced by ngx_stream_brix_recv().
brix_exit_process()
void brix_exit_process (ngx_cycle_t * cycle)
Definition at line 501 of file process.c.
References brix_cache_storage_cleanup(), brix_crypto_cleanup(), brix_proxy_pool_shutdown(), brix_sesslog_shutdown_flush(), brix_uring_exit_worker(), close(), ngx_stream_brix_srv_conf_t::common, ngx_http_brix_shared_conf_t::enable, ngx_stream_brix_module, and ngx_stream_brix_srv_conf_t::rootfd.
brix_extract_voms_info()
ngx_int_t brix_extract_voms_info (ngx_log_t * log, X509 * leaf, STACK_OF(X509) * chain, const ngx_str_t * vomsdir, const ngx_str_t * cert_dir, char * primary_vo, size_t primary_vo_sz, char * vo_list, size_t vo_list_sz)
Definition at line 32 of file extract.c.
References brix_collect_voms_vos(), brix_voms_api, brix_voms_loaded, brix_voms_api_t::destroy, brix_voms_api_t::error_message, brix_voms_api_t::init, log, ngx_memcpy, PATH_MAX, brix_voms_api_t::retrieve, STACK_OF(), VOMS_RECURSE_CHAIN, VOMS_VERR_NODATA, and VOMS_VERR_NOEXT.
Referenced by brix_handle_auth_inner(), and webdav_extract_and_set_voms_identity().
brix_find_manager_map()
const brix_manager_map_t * brix_find_manager_map (const char * reqpath, ngx_array_t * map)
Definition at line 123 of file find_rule.c.
References brix_path_prefix_match(), and brix_manager_map_t::prefix.
Referenced by brix_handle_dirlist(), brix_handle_locate(), brix_handle_open(), and brix_handle_stat().
brix_handle_bind()
ngx_int_t brix_handle_bind (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 35 of file bind.c.
References brix_ctx_token_t::auth, brix_ctx_login_t::auth_done, brix_ctx_t::bound_sessid, BRIX_AUTHN_GSI, BRIX_AUTHN_TOKEN, brix_build_resp_hdr(), brix_identity_set_cstr(), brix_identity_set_dn(), brix_identity_set_subject(), brix_identity_set_vos_csv(), brix_log_access(), brix_next_pathid, BRIX_PALLOC_OR_RETURN, brix_queue_response(), brix_send_error(), BRIX_SESSION_ID_LEN, brix_session_lookup(), c, brix_ctx_recv_t::cur_streamid, brix_ctx_login_t::dn, brix_identity_t::dn, brix_ctx_recv_t::hdr_buf, brix_ctx_t::identity, brix_ctx_t::is_bound, kXR_NotAuthorized, kXR_ok, brix_ctx_login_t::logged_in, brix_ctx_t::login, ngx_memcpy, brix_ctx_t::pathid, brix_ctx_t::recv, xrdw_sessid_req_t::sessid, brix_ctx_t::token, brix_ctx_login_t::vo_list, XRD_RESPONSE_HDR_LEN, and xrdw_sessid_req_unpack().
Referenced by brix_dispatch_session_opcode().
brix_handle_fattr()
ngx_int_t brix_handle_fattr (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 34 of file dispatch.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_auth_gate(), BRIX_AUTH_READ, BRIX_AUTH_UPDATE, brix_beneath_full_path(), brix_extract_path(), brix_kxr_from_errno(), BRIX_MAX_FILES, BRIX_MAX_PATH, BRIX_OP_ERR, BRIX_OP_FATTR, BRIX_PALLOC_OR_RETURN, BRIX_PROTO_ROOT, brix_send_error(), brix_vfs_ctx_init(), c, close(), ngx_stream_brix_srv_conf_t::common, brix_ctx_recv_t::cur_dlen, fattr_del(), fattr_get(), fattr_list(), fattr_parse_nvec(), fattr_set(), brix_file_t::fd, xrdw_fattr_req_t::fhandle, brix_ctx_t::files, brix_ctx_recv_t::hdr_buf, kXR_ArgInvalid, kXR_ArgMissing, kXR_faMaxVars, kXR_fattrDel, kXR_fattrGet, kXR_fattrList, kXR_fattrMaxSC, kXR_fattrSet, kXR_FileNotOpen, kXR_fsReadOnly, kXR_NoMemory, kXR_Unsupported, ngx_memcpy, xrdw_fattr_req_t::numattr, xrdw_fattr_req_t::options, brix_file_t::path, PATH_MAX, brix_ctx_recv_t::payload, brix_vfs_ctx_t::pool, brix_ctx_t::recv, ngx_http_brix_shared_conf_t::root_canon, brix_file_t::sd_obj, xrdw_fattr_req_t::subcode, brix_ctx_t::write_rc, and xrdw_fattr_req_unpack().
Referenced by brix_dispatch_read_opcode().
brix_handle_host_auth()
ngx_int_t brix_handle_host_auth (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 84 of file auth.c.
References brix_ctx_token_t::auth, brix_ctx_login_t::auth_done, brix_acc_resolve_peer(), BRIX_AUTHN_HOST, brix_host_allowed(), brix_identity_set_dn(), brix_metric_auth(), BRIX_OP_AUTH, BRIX_PROTO_ROOT, BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_sanitize_log_string(), brix_send_error(), brix_session_register(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_login_t::dn, brix_ctx_t::identity, kXR_NoMemory, kXR_NotAuthorized, brix_ctx_t::login, brix_ctx_recv_t::payload, brix_ctx_login_t::primary_vo, brix_ctx_t::recv, brix_ctx_login_t::sessid, brix_ctx_t::token, and brix_ctx_login_t::vo_list.
Referenced by brix_handle_auth_inner().
brix_handle_krb5_auth()
ngx_int_t brix_handle_krb5_auth (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 165 of file auth.c.
References brix_ctx_token_t::auth, brix_ctx_login_t::auth_done, BRIX_AUTHN_KRB5, brix_identity_set_dn(), brix_log_access(), brix_metric_auth(), BRIX_OP_AUTH, BRIX_OP_ERR, BRIX_PROTO_ROOT, BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_sanitize_log_string(), brix_send_error(), brix_session_register(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_login_t::dn, brix_ctx_t::identity, brix_krb5_conf_t::ip_check, ngx_stream_brix_srv_conf_t::krb5, kXR_NoMemory, kXR_NotAuthorized, brix_ctx_t::login, brix_ctx_recv_t::payload, brix_ctx_t::recv, brix_ctx_login_t::sessid, brix_ctx_t::token, and brix_ctx_login_t::vo_list.
Referenced by brix_handle_auth_inner().
brix_handle_prepare()
ngx_int_t brix_handle_prepare (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 322 of file prepare.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_attn_asyncms_frame_len(), brix_build_attn_asyncms_frame(), brix_build_resp_hdr(), brix_log_access(), BRIX_PALLOC_OR_RETURN, brix_prepare_check_path(), BRIX_PREPARE_CMD_MAX_PATHS, brix_prepare_handle_cancel(), brix_prepare_invoke_command(), brix_prepare_owner_key(), BRIX_PREPARE_OWNER_KEY_MAX, brix_prepare_send_fail(), brix_queue_response(), brix_send_ok(), brix_stage_registry_singleton(), BRIX_STAGE_REQID_LEN, brix_stage_request_add(), c, ngx_stream_brix_srv_conf_t::common, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_streamid, brix_frm_conf_t::enable, ngx_stream_brix_srv_conf_t::frm, brix_ctx_recv_t::hdr_buf, kXR_ArgMissing, kXR_cancel, kXR_coloc, kXR_evict, kXR_fsReadOnly, kXR_noerrs, kXR_notify, kXR_ok, kXR_stage, kXR_wmode, brix_stage_request_view_t::lfn, ngx_memcpy, xrdw_prepare_req_t::options, xrdw_prepare_req_t::optionX, PATH_MAX, brix_ctx_prepare_t::paths, brix_ctx_prepare_t::paths_len, brix_ctx_recv_t::payload, brix_ctx_t::prepare, ngx_stream_brix_srv_conf_t::prepare_command, brix_ctx_t::recv, brix_ctx_prepare_t::reqid, brix_stage_request_view_t::requester_dn, brix_frm_conf_t::stage_ttl, brix_stage_request_view_t::tod_expire, XRD_RESPONSE_HDR_LEN, and xrdw_prepare_req_unpack().
Referenced by brix_dispatch_read_opcode().
brix_handle_pwd_auth()
ngx_int_t brix_handle_pwd_auth (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 263 of file auth.c.
References BRIX_AUTHN_PWD, brix_metric_auth(), BRIX_OP_AUTH, BRIX_PROTO_ROOT, BRIX_RETURN_ERR, c, brix_ctx_recv_t::cur_dlen, kXR_NotAuthorized, brix_ctx_recv_t::payload, brix_ctx_t::pwd, pwd_round1(), pwd_round2(), brix_ctx_t::recv, and brix_ctx_pwd_t::round.
Referenced by brix_handle_auth_inner().
brix_handle_query()
ngx_int_t brix_handle_query (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 17 of file dispatch.c.
References BRIX_OP_QUERY_VISA, brix_query_ckscan(), brix_query_cksum(), brix_query_config(), brix_query_finfo(), brix_query_fsinfo(), brix_query_opaque(), brix_query_opaquf(), brix_query_opaqug(), brix_query_prep_status(), brix_query_space(), brix_query_stats(), brix_query_visa(), brix_query_xattr(), BRIX_RETURN_ERR, brix_send_error(), brix_ssi_query(), c, brix_ctx_recv_t::cur_dlen, xrdw_query_req_t::fhandle, brix_ctx_recv_t::hdr_buf, xrdw_query_req_t::infotype, kXR_ArgInvalid, kXR_Qckscan, kXR_Qcksum, kXR_Qconfig, kXR_QFinfo, kXR_QFSinfo, kXR_Qopaque, kXR_Qopaquf, kXR_Qopaqug, kXR_QPrep, kXR_Qspace, kXR_QStats, kXR_Qvisa, kXR_Qxattr, kXR_Unsupported, brix_ctx_recv_t::payload, brix_ctx_t::recv, and xrdw_query_req_unpack().
Referenced by brix_dispatch_read_opcode().
brix_handle_set()
ngx_int_t brix_handle_set (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 108 of file set.c.
References BRIX_OP_SET, BRIX_RETURN_OK, brix_set_handle_cms_space(), c, CMS_SPACE_PREFIX, CMS_SPACE_PREFIX_LEN, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::hdr_buf, kXR_set_appid, kXR_set_clttl, xrdw_set_req_t::modifier, ngx_memcpy, brix_ctx_recv_t::payload, brix_ctx_t::recv, and xrdw_set_req_unpack().
Referenced by brix_dispatch_session_opcode().
brix_handle_unix_auth()
ngx_int_t brix_handle_unix_auth (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 157 of file auth.c.
References brix_ctx_token_t::auth, brix_ctx_login_t::auth_done, BRIX_AUTHN_UNIX, brix_identity_set_dn(), brix_identity_set_vos_csv(), brix_metric_auth(), BRIX_OP_AUTH, BRIX_PROTO_ROOT, BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_sanitize_log_string(), brix_send_error(), brix_session_register(), BRIX_SSS_GROUP_MAX, BRIX_SSS_USER_MAX, brix_unix_copy_name(), brix_unix_peer_is_loopback(), brix_unix_track_identity(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_login_t::dn, brix_ctx_t::identity, kXR_NoMemory, kXR_NotAuthorized, brix_ctx_t::login, brix_ctx_recv_t::payload, brix_ctx_login_t::primary_vo, brix_ctx_t::recv, brix_ctx_login_t::sessid, brix_ctx_t::token, ngx_stream_brix_srv_conf_t::unix_trust_remote, and brix_ctx_login_t::vo_list.
Referenced by brix_handle_auth_inner().
brix_prepare_invoke_command()
ngx_int_t brix_prepare_invoke_command (ngx_log_t * log, ngx_stream_brix_srv_conf_t * conf, const char ** paths, ngx_uint_t count, ngx_flag_t coloc)
Definition at line 44 of file prepare_cmd.c.
References close(), log, and ngx_stream_brix_srv_conf_t::prepare_command.
Referenced by brix_handle_prepare().
brix_process_handshake()
ngx_int_t brix_process_handshake (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 14 of file client_hello.c.
References BRIX_PALLOC_OR_RETURN, brix_queue_response(), c, ServerResponseHdr::dlen, ClientInitHandShake::fifth, ClientInitHandShake::fourth, brix_ctx_recv_t::hdr_buf, kXR_DataServer, kXR_ok, kXR_PROTOCOLVERSION, brix_ctx_t::recv, ROOTD_PQ, ServerResponseHdr::status, ServerResponseHdr::streamid, and XRD_RESPONSE_HDR_LEN.
Referenced by ngx_stream_brix_recv().
brix_rebuild_gsi_store()
ngx_int_t brix_rebuild_gsi_store (ngx_stream_brix_srv_conf_t * xcf, ngx_log_t * log)
Definition at line 16 of file config.c.
References brix_build_ca_store(), ngx_stream_brix_srv_conf_t::crl, ngx_stream_brix_srv_conf_t::crl_mode, ngx_stream_brix_srv_conf_t::gsi_store, log, ngx_stream_brix_srv_conf_t::signing_policy_mode, stat(), and ngx_stream_brix_srv_conf_t::trusted_ca.
Referenced by brix_configure_gsi(), and brix_crl_reload_handler().
brix_rl_charge_ctx()
void brix_rl_charge_ctx (brix_ctx_t * ctx, size_t nbytes)
Definition at line 187 of file ratelimit_stream.c.
References brix_rl_charge_bytes(), brix_ctx_rl_t::bw_key, brix_ctx_rl_t::bw_rule, and brix_ctx_t::rl.
Referenced by brix_handle_pgread(), brix_handle_pgwrite(), brix_handle_write(), brix_read_compressed(), brix_read_serve_sendfile(), and brix_write_compressed().
brix_sss_build_proxy_credential()
ngx_int_t brix_sss_build_proxy_credential (const brix_sss_key_t * key, const char * username, u_char * buf, size_t buf_max, size_t * out_len)
Definition at line 29 of file auth_proxy_credential.c.
References BRIX_SSS_BASE_TIME, brix_sss_build_credential(), and key.
Referenced by brix_cache_origin_auth_sss(), and proxy_send_sss_auth().
brix_voms_available()
ngx_flag_t brix_voms_available (void)
Definition at line 20 of file loader.c.
References brix_voms_loaded.
Referenced by brix_config_finalize_policy(), brix_handle_auth_inner(), and webdav_extract_and_set_voms_identity().
brix_voms_init()
ngx_int_t brix_voms_init (ngx_log_t * log)
Definition at line 32 of file loader.c.
References brix_voms_api, brix_voms_loaded, brix_voms_api_t::handle, LOAD_SYM, and log.
Referenced by ngx_http_brix_webdav_merge_loc_conf(), and ngx_stream_brix_postconfiguration().
ngx_brix_cms_start()
void ngx_brix_cms_start (ngx_cycle_t * cycle, ngx_stream_brix_srv_conf_t * conf)
Definition at line 514 of file connect.c.
References brix_cms_conf_t::addr, brix_phase_now_ns(), ngx_stream_brix_srv_conf_t::cms, cms_addr_is_loopback(), brix_cms_conf_t::connect_retry, brix_cms_conf_t::ctx, brix_cms_conf_t::initial_delay, brix_cms_conf_t::interval, brix_cms_conf_t::manager, NGX_BRIX_CMS_BACKOFF_INITIAL, NGX_BRIX_CMS_FASTRETRY_FLOOR, NGX_BRIX_CMS_FASTRETRY_LOOPBACK, NGX_BRIX_CMS_FASTRETRY_REMOTE, NGX_BRIX_CMS_FASTWIN_LOOPBACK, NGX_BRIX_CMS_FASTWIN_REMOTE, NGX_BRIX_CMS_HDR_LEN, NGX_BRIX_CMS_INITDELAY_LOOPBACK, NGX_BRIX_CMS_INITDELAY_REMOTE, ngx_brix_cms_schedule(), ngx_brix_cms_timer(), and ngx_pcalloc().
Referenced by ngx_stream_brix_init_process().
ngx_brix_metrics_shm_init()
ngx_int_t ngx_brix_metrics_shm_init (ngx_shm_zone_t * shm_zone, void * data)
Definition at line 179 of file config.c.
References brix_shm_table_alloc().
Referenced by brix_metrics_ensure_zone().
ngx_stream_brix_create_srv_conf()
void * ngx_stream_brix_create_srv_conf (ngx_conf_t * cf)
Definition at line 31 of file server_conf.c.
References ngx_stream_brix_srv_conf_t::acc, ngx_stream_brix_srv_conf_t::access_log_fd, ngx_stream_brix_srv_conf_t::advertise, ngx_stream_brix_srv_conf_t::auth, ngx_stream_brix_srv_conf_t::auth_cache, brix_acc_conf_init(), brix_cache_reaper_conf_init(), brix_cms_conf_init(), brix_csi_conf_init(), brix_frm_conf_init(), brix_hc_conf_init(), brix_krb5_conf_init(), brix_node_caps_conf_init(), brix_ocsp_conf_init(), brix_proxy_conf_init(), brix_wt_conf_init(), brix_rate_limit_conf_t::burst, ngx_stream_brix_srv_conf_t::cache, ngx_stream_brix_srv_conf_t::cache_allow_prefixes, ngx_stream_brix_srv_conf_t::cache_deny_prefixes, ngx_stream_brix_srv_conf_t::cache_dirty_max_age, ngx_stream_brix_srv_conf_t::cache_eviction_threshold, ngx_stream_brix_srv_conf_t::cache_lock_timeout, ngx_stream_brix_srv_conf_t::cache_max_file_size, ngx_stream_brix_srv_conf_t::cache_origin_family, ngx_stream_brix_srv_conf_t::cache_origin_tls, ngx_stream_brix_srv_conf_t::cache_rootfd, ngx_stream_brix_srv_conf_t::cache_state_rootfd, ngx_stream_brix_srv_conf_t::cache_verify, ngx_stream_brix_srv_conf_t::cache_wt_stage_block_size, ngx_stream_brix_srv_conf_t::cache_wt_stage_high_watermark, ngx_stream_brix_srv_conf_t::cache_wt_stage_low_watermark, ngx_stream_brix_srv_conf_t::cache_wt_stage_rootfd, ngx_stream_brix_srv_conf_t::cache_wt_store_rootfd, ngx_stream_brix_srv_conf_t::caps, ngx_stream_brix_srv_conf_t::ckscan_max_depth, ngx_stream_brix_srv_conf_t::ckscan_max_files, ngx_stream_brix_srv_conf_t::cms, ngx_stream_brix_srv_conf_t::cns_mode, ngx_stream_brix_srv_conf_t::common, ngx_stream_brix_srv_conf_t::crl_mode, ngx_stream_brix_srv_conf_t::crl_reload, ngx_stream_brix_srv_conf_t::csi, brix_cache_advertise_conf_t::enable, brix_mirror_conf_t::enabled, ngx_stream_brix_srv_conf_t::frm, ngx_stream_brix_srv_conf_t::group_rules, ngx_stream_brix_srv_conf_t::gsi_ca_hash, ngx_stream_brix_srv_conf_t::gsi_cert, ngx_stream_brix_srv_conf_t::gsi_cert_pem, ngx_stream_brix_srv_conf_t::gsi_cert_pem_len, ngx_stream_brix_srv_conf_t::gsi_key, ngx_stream_brix_srv_conf_t::gsi_keypool_seed, ngx_stream_brix_srv_conf_t::gsi_keypool_size, ngx_stream_brix_srv_conf_t::gsi_max_inflight, ngx_stream_brix_srv_conf_t::gsi_signed_dh, ngx_stream_brix_srv_conf_t::gsi_store, ngx_stream_brix_srv_conf_t::handshake_timeout, ngx_stream_brix_srv_conf_t::hc, ngx_stream_brix_srv_conf_t::host_allow, ngx_stream_brix_srv_conf_t::http_handoff_addr, ngx_stream_brix_srv_conf_t::include_regex, brix_cache_advertise_conf_t::interval, ngx_stream_brix_srv_conf_t::io_uring, ngx_stream_brix_srv_conf_t::io_uring_admin, ngx_stream_brix_srv_conf_t::io_uring_queue_depth, ngx_stream_brix_srv_conf_t::io_uring_restrict, ngx_stream_brix_srv_conf_t::jwks_mtime, ngx_stream_brix_srv_conf_t::jwks_timer, brix_rate_limit_conf_t::key_ip, ngx_stream_brix_srv_conf_t::krb5, brix_auth_cache_conf_t::kv, brix_rate_limit_conf_t::kv, ngx_stream_brix_srv_conf_t::listen_port, brix_mirror_conf_t::log_diverge, ngx_stream_brix_srv_conf_t::manager_mode, ngx_stream_brix_srv_conf_t::manager_stale_after, brix_throttle_conf_t::max_active_conn, ngx_stream_brix_srv_conf_t::max_connections, brix_throttle_conf_t::max_open_files, ngx_stream_brix_srv_conf_t::memory_budget, brix_mirror_conf_t::method_mask, ngx_stream_brix_srv_conf_t::metrics_slot, ngx_stream_brix_srv_conf_t::mirror, brix_mirror_conf_t::mirror_writes, ngx_http_brix_shared_init(), ngx_pcalloc(), ngx_stream_brix_srv_conf_t::ocsp, brix_mirror_conf_t::opcode_exclude_mask, brix_mirror_conf_t::opcode_mask, ngx_stream_brix_srv_conf_t::pipeline_depth, ngx_stream_brix_srv_conf_t::prepare_command, ngx_stream_brix_srv_conf_t::proxy, brix_rate_limit_conf_t::rate, ngx_stream_brix_srv_conf_t::rate_limit, ngx_stream_brix_srv_conf_t::read_compress, ngx_stream_brix_srv_conf_t::read_timeout, ngx_stream_brix_srv_conf_t::readv_segment_size, ngx_stream_brix_srv_conf_t::reaper, ngx_stream_brix_srv_conf_t::redir_cache_slots, ngx_stream_brix_srv_conf_t::registry_slots, ngx_stream_brix_srv_conf_t::relay_addr, ngx_stream_brix_srv_conf_t::relay_guard_enable, ngx_stream_brix_srv_conf_t::rootfd, brix_mirror_conf_t::sample_pct, ngx_stream_brix_srv_conf_t::security_level, ngx_stream_brix_srv_conf_t::send_timeout, ngx_stream_brix_srv_conf_t::session_log, ngx_stream_brix_srv_conf_t::session_slots, brix_cache_include_regex_conf_t::set, ngx_stream_brix_srv_conf_t::signing_policy_mode, ngx_stream_brix_srv_conf_t::ssi_cta_enable, ngx_stream_brix_srv_conf_t::ssi_cta_executor, ngx_stream_brix_srv_conf_t::ssi_enable, ngx_stream_brix_srv_conf_t::ssi_max_inflight, ngx_stream_brix_srv_conf_t::ssi_request_max, ngx_stream_brix_srv_conf_t::ssi_response_max, ngx_stream_brix_srv_conf_t::sss_keys, ngx_stream_brix_srv_conf_t::sss_lifetime, brix_mirror_conf_t::strip_auth, brix_mirror_conf_t::targets, ngx_stream_brix_srv_conf_t::tcp_keepalive, ngx_stream_brix_srv_conf_t::tcp_user_timeout, ngx_stream_brix_srv_conf_t::throttle, brix_mirror_conf_t::timeout_ms, ngx_stream_brix_srv_conf_t::tls, ngx_stream_brix_srv_conf_t::tls_ctx, ngx_stream_brix_srv_conf_t::tls_ktls, ngx_stream_brix_srv_conf_t::token_cache_kv, ngx_stream_brix_srv_conf_t::token_clock_skew, ngx_stream_brix_srv_conf_t::token_jwks_refresh_interval, ngx_stream_brix_srv_conf_t::tpc_allow_local, ngx_stream_brix_srv_conf_t::tpc_allow_private, ngx_stream_brix_srv_conf_t::tpc_delegate, ngx_stream_brix_srv_conf_t::tpc_key_ttl_ms, ngx_stream_brix_srv_conf_t::tpc_max_transfer_secs, ngx_stream_brix_srv_conf_t::tpc_outbound_bearer_file, ngx_stream_brix_srv_conf_t::tpc_outbound_client_id, ngx_stream_brix_srv_conf_t::tpc_outbound_client_secret, ngx_stream_brix_srv_conf_t::tpc_outbound_scope, ngx_stream_brix_srv_conf_t::tpc_outbound_tls, ngx_stream_brix_srv_conf_t::tpc_outbound_token_endpoint, ngx_stream_brix_srv_conf_t::tpc_transfer_max_age, brix_auth_cache_conf_t::ttl_secs, ngx_stream_brix_srv_conf_t::unix_trust_remote, ngx_stream_brix_srv_conf_t::upload_resume, ngx_stream_brix_srv_conf_t::upstream_addr, ngx_stream_brix_srv_conf_t::upstream_tls, ngx_stream_brix_srv_conf_t::upstream_tls_ca, ngx_stream_brix_srv_conf_t::upstream_tls_name, ngx_stream_brix_srv_conf_t::upstream_token_file, ngx_stream_brix_srv_conf_t::vo_rules, ngx_stream_brix_srv_conf_t::write_compress, ngx_stream_brix_srv_conf_t::wt, ngx_stream_brix_srv_conf_t::zip_access, ngx_stream_brix_srv_conf_t::zip_cd_max_bytes, ngx_stream_brix_srv_conf_t::zip_force_scratch, and ngx_stream_brix_srv_conf_t::zip_stage_max_bytes.
ngx_stream_brix_enable()
char * ngx_stream_brix_enable (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 890 of file server_conf.c.
References ngx_stream_brix_srv_conf_t::common, ngx_http_brix_shared_conf_t::enable, and ngx_stream_brix_handler().
ngx_stream_brix_init_process()
ngx_int_t ngx_stream_brix_init_process (ngx_cycle_t * cycle)
Definition at line 205 of file process.c.
References ngx_stream_brix_srv_conf_t::access_log_fd, ngx_stream_brix_srv_conf_t::access_log_file, brix_cms_conf_t::addr, brix_proxy_conf_t::audit_log_fd, brix_proxy_conf_t::audit_log_file, ngx_stream_brix_srv_conf_t::auth, brix_acc_init_server(), BRIX_AUTH_BOTH, BRIX_AUTH_GSI, brix_cache_pelican_schedule_advertise(), BRIX_CACHE_REAP_FIRST_MS, brix_cache_reap_handler(), brix_cache_state_root(), brix_cache_storage_init(), brix_cache_watermark_timer_handler(), brix_chkpoint_recover_root(), brix_crl_reload_handler(), brix_crypto_init(), brix_gsi_keypool_init(), brix_hc_manager_start(), brix_imp_init_worker(), brix_maint_timer_conn, brix_openat2_runtime_available(), brix_pending_reap_handler(), BRIX_PENDING_REAP_INTERVAL_MS, brix_pending_reap_timer, brix_phase_mark(), brix_phase_timer_log(), brix_phase_timer_start(), brix_proxy_pool_init(), brix_stage_dir_count(), brix_stage_engine_init(), BRIX_STAGE_REAP_FIRST_MS, brix_stage_reap_handler(), brix_stage_reap_timer, brix_stage_reconcile(), brix_stage_registry_init(), brix_stage_sched_handler(), BRIX_STAGE_SCHED_MS, brix_stage_sched_timer, brix_str_cbuf(), brix_tmp_reap_all(), brix_token_jwks_schedule_refresh(), brix_uring_init_worker(), brix_xfer_resume_sweep_register(), ngx_stream_brix_srv_conf_t::cache, ngx_stream_brix_srv_conf_t::cache_dirty_max_age, ngx_stream_brix_srv_conf_t::cache_reap_timer, ngx_http_brix_shared_conf_t::cache_store, ngx_stream_brix_srv_conf_t::cms, ngx_stream_brix_srv_conf_t::common, brix_frm_conf_t::control_dir, ngx_stream_brix_srv_conf_t::crl, ngx_stream_brix_srv_conf_t::crl_reload, ngx_stream_brix_srv_conf_t::crl_timer, ngx_http_brix_shared_conf_t::enable, brix_frm_conf_t::enable, ngx_stream_brix_srv_conf_t::frm, ngx_stream_brix_srv_conf_t::gsi_keypool_seed, ngx_stream_brix_srv_conf_t::gsi_keypool_size, brix_cache_reaper_conf_t::high_watermark, ngx_stream_brix_srv_conf_t::manager_mode, ngx_brix_cms_start(), ngx_pcalloc(), ngx_stream_brix_module, O_PATH, open(), ngx_stream_brix_srv_conf_t::proxy, ngx_stream_brix_srv_conf_t::reaper, ngx_http_brix_shared_conf_t::root_canon, ngx_stream_brix_srv_conf_t::rootfd, ngx_http_brix_shared_conf_t::thread_pool, brix_cache_reaper_conf_t::timer, and ngx_stream_brix_srv_conf_t::upload_stage_dir_canon.
ngx_stream_brix_merge_srv_conf()
char * ngx_stream_brix_merge_srv_conf (ngx_conf_t * cf, void * parent, void * child)
Definition at line 864 of file server_conf.c.
References brix_merge_srv_cluster(), brix_merge_srv_proxy_net(), brix_merge_srv_security(), brix_merge_srv_storage(), and brix_merge_srv_tpc().
ngx_stream_brix_postconfiguration()
ngx_int_t ngx_stream_brix_postconfiguration (ngx_conf_t * cf)
Definition at line 96 of file postconfiguration.c.
References brix_config_finalize_policy(), brix_config_prepare_server(), brix_configure_dashboard(), brix_configure_gsi(), brix_configure_krb5_auth(), brix_configure_metrics(), brix_configure_session_registry(), brix_configure_sss_auth(), brix_configure_thread_pools(), brix_configure_tls(), brix_configure_token_auth(), brix_imp_validate(), BRIX_IO_URING_OFF, brix_log_startup_summary(), brix_pending_configure(), brix_phase_mark(), brix_phase_timer_log(), brix_phase_timer_start(), brix_redir_cache_configure(), brix_srv_configure_registry(), brix_stage_waiter_configure(), brix_tpc_key_configure_registry(), brix_tpc_registry_configure(), brix_uring_admin_set_enabled(), brix_uring_killswitch_configure(), brix_uring_validate_conf(), brix_voms_init(), ngx_stream_brix_srv_conf_t::caps, brix_node_caps_conf_t::collapse_redir, ngx_stream_brix_srv_conf_t::common, ngx_http_brix_shared_conf_t::enable, brix_frm_conf_t::enable, ngx_stream_brix_srv_conf_t::frm, ngx_stream_brix_srv_conf_t::io_uring, ngx_stream_brix_srv_conf_t::io_uring_admin, brix_frm_conf_t::max_inflight, ngx_stream_brix_module, ngx_stream_brix_srv_conf_t::redir_cache_slots, ngx_stream_brix_srv_conf_t::registry_slots, ngx_http_brix_shared_conf_t::root_canon, and ngx_stream_brix_srv_conf_t::session_slots.
Variable Documentation
ngx_stream_brix_module
ngx_module_t ngx_stream_brix_module extern
Definition at line 29 of file module_definition.c.
Referenced by brix_aio_resume(), brix_check_authdb(), brix_cms_srv_handler(), brix_configure_dashboard(), brix_configure_metrics(), brix_configure_session_registry(), brix_configure_thread_pools(), brix_exit_process(), brix_free_fhandle(), brix_gsi_send_cert(), brix_handle_auth_inner(), brix_handle_close(), brix_handle_login(), brix_handle_pgread(), brix_handle_pgwrite(), brix_handle_read(), brix_handle_readv(), brix_handle_sync(), brix_handle_writev(), brix_http_handoff_start(), brix_log_access(), brix_metrics_ensure_zone(), brix_on_disconnect(), brix_open_resolved_file(), brix_parse_authdb(), brix_pending_configure(), brix_pgread_aio_done(), brix_redir_cache_configure(), brix_relay_start(), brix_reopen_bound_read_handle(), brix_schedule_write_resume(), brix_srv_configure_registry(), brix_ssi_open(), brix_tls_handshake_done(), brix_tpc_key_configure_registry(), brix_tpc_registry_configure(), brix_try_post_write_aio(), brix_upstream_continue_auth(), brix_upstream_handle_bootstrap_response(), brix_uring_any_block_on(), brix_uring_killswitch_configure(), brix_write_aio_done(), brix_write_compressed(), brix_writev_write_aio_done(), cms_wake_pending_session(), handoff_from_client(), ngx_stream_brix_handler(), ngx_stream_brix_init_process(), ngx_stream_brix_postconfiguration(), ngx_stream_brix_recv(), ngx_stream_brix_send(), and relay_from_client().