nginx-xrootd: src/net/cms/node_ops.c File Reference
node_ops.c File Reference
#include "node_ops.h"
#include <stddef.h>
#include <stdlib.h>
Macros
#define K_CHMOD 1
#define K_MKDIR 3
#define K_MKPATH 4
#define K_MV 5
#define K_PREPADD 6
#define K_PREPDEL 7
#define K_RM 8
#define K_RMDIR 9
#define K_TRUNC 23
Functions
static const char * field_str (const unsigned char *p, size_t len)
int brix_cms_node_plan (unsigned char code, const brix_cms_rrdata_t *d, brix_cms_node_plan_t *plan)
Macro Definition Documentation
K_CHMOD
#define K_CHMOD 1
Definition at line 14 of file node_ops.c.
K_MKDIR
#define K_MKDIR 3
Definition at line 15 of file node_ops.c.
K_MKPATH
#define K_MKPATH 4
Definition at line 16 of file node_ops.c.
K_MV
#define K_MV 5
Definition at line 17 of file node_ops.c.
K_PREPADD
#define K_PREPADD 6
Definition at line 18 of file node_ops.c.
K_PREPDEL
#define K_PREPDEL 7
Definition at line 19 of file node_ops.c.
K_RM
#define K_RM 8
Definition at line 20 of file node_ops.c.
K_RMDIR
#define K_RMDIR 9
Definition at line 21 of file node_ops.c.
K_TRUNC
#define K_TRUNC 23
Definition at line 22 of file node_ops.c.
Function Documentation
brix_cms_node_plan()
int brix_cms_node_plan (unsigned char code, const brix_cms_rrdata_t * d, brix_cms_node_plan_t * plan)
Definition at line 33 of file node_ops.c.
References brix_cms_node_plan_t::action, code, field_str(), K_CHMOD, K_MKDIR, K_MKPATH, K_MV, K_PREPADD, K_PREPDEL, K_RM, K_RMDIR, K_TRUNC, brix_cms_node_plan_t::mode, brix_cms_rrdata_t::mode, brix_cms_rrdata_t::mode_len, brix_cms_node_plan_t::notify, brix_cms_rrdata_t::notify, brix_cms_rrdata_t::notify_len, brix_cms_node_plan_t::path, brix_cms_rrdata_t::path, brix_cms_node_plan_t::path2, brix_cms_rrdata_t::path2, brix_cms_rrdata_t::path2_len, brix_cms_rrdata_t::path_len, brix_cms_node_plan_t::prty, brix_cms_rrdata_t::prty, brix_cms_rrdata_t::prty_len, brix_cms_node_plan_t::reqid, brix_cms_rrdata_t::reqid, brix_cms_rrdata_t::reqid_len, brix_cms_node_plan_t::size, XRDCMS_NACT_CHMOD, XRDCMS_NACT_MKDIR, XRDCMS_NACT_MKPATH, XRDCMS_NACT_MV, XRDCMS_NACT_NONE, XRDCMS_NACT_PREPADD, XRDCMS_NACT_PREPDEL, XRDCMS_NACT_RM, XRDCMS_NACT_RMDIR, XRDCMS_NACT_TRUNC, and XRDCMS_NODE_DEFAULT_DIR_MODE.
Referenced by cms_node_exec_forward(), cms_node_exec_prepare(), test_chmod(), test_chmod_requires_mode(), test_missing_path_rejected(), test_mkdir_default_mode(), test_mkdir_mode(), test_mkpath(), test_mv(), test_mv_requires_two_paths(), test_non_executed_opcode(), test_prepadd_plan(), test_prepadd_requires_reqid(), test_prepdel_plan(), test_prepdel_requires_reqid(), test_rm_and_rmdir(), and test_trunc_size().
field_str()
static const char * field_str (const unsigned char * p, size_t len) static
Definition at line 27 of file node_ops.c.
Referenced by brix_cms_node_plan().