nginx-xrootd: src/net/cms/node_ops.h File Reference
node_ops.h File Reference
#include <sys/types.h>
#include "rrdata.h"
Data Structures
struct brix_cms_node_plan_t
Macros
#define XRDCMS_NODE_DEFAULT_DIR_MODE 0755
Enumerations
enum brix_cms_node_action_t {
XRDCMS_NACT_NONE = 0 , XRDCMS_NACT_MKDIR , XRDCMS_NACT_MKPATH , XRDCMS_NACT_RMDIR ,
XRDCMS_NACT_RM , XRDCMS_NACT_MV , XRDCMS_NACT_CHMOD , XRDCMS_NACT_TRUNC ,
XRDCMS_NACT_PREPADD , XRDCMS_NACT_PREPDEL
}
Functions
int brix_cms_node_plan (unsigned char code, const brix_cms_rrdata_t *d, brix_cms_node_plan_t *plan)
Macro Definition Documentation
XRDCMS_NODE_DEFAULT_DIR_MODE
#define XRDCMS_NODE_DEFAULT_DIR_MODE 0755
Definition at line 47 of file node_ops.h.
Enumeration Type Documentation
brix_cms_node_action_t
enum brix_cms_node_action_t
Enumerator
XRDCMS_NACT_NONE
XRDCMS_NACT_MKDIR
XRDCMS_NACT_MKPATH
XRDCMS_NACT_RMDIR
XRDCMS_NACT_RM
XRDCMS_NACT_MV
XRDCMS_NACT_CHMOD
XRDCMS_NACT_TRUNC
XRDCMS_NACT_PREPADD
XRDCMS_NACT_PREPDEL
Definition at line 23 of file node_ops.h.
Function Documentation
brix_cms_node_plan()
int brix_cms_node_plan (unsigned char code, const brix_cms_rrdata_t * d, brix_cms_node_plan_t * plan)
Definition at line 71 of file node_ops.c.
References brix_cms_node_plan_t::action, code, field_str(), K_CHMOD, K_MKDIR, K_MKPATH, K_MV, K_PREPADD, K_PREPDEL, K_RM, K_RMDIR, K_TRUNC, brix_cms_node_plan_t::mode, brix_cms_rrdata_t::mode, brix_cms_rrdata_t::mode_len, node_plan_mode_op(), brix_cms_node_plan_t::notify, brix_cms_rrdata_t::notify, brix_cms_rrdata_t::notify_len, brix_cms_node_plan_t::path, brix_cms_rrdata_t::path, brix_cms_node_plan_t::path2, brix_cms_rrdata_t::path2, brix_cms_rrdata_t::path2_len, brix_cms_rrdata_t::path_len, brix_cms_node_plan_t::prty, brix_cms_rrdata_t::prty, brix_cms_rrdata_t::prty_len, brix_cms_node_plan_t::reqid, brix_cms_rrdata_t::reqid, brix_cms_rrdata_t::reqid_len, brix_cms_node_plan_t::size, XRDCMS_NACT_MV, XRDCMS_NACT_NONE, XRDCMS_NACT_PREPADD, XRDCMS_NACT_PREPDEL, XRDCMS_NACT_RM, and XRDCMS_NACT_RMDIR.
Referenced by cms_node_exec_forward(), cms_node_exec_prepare(), test_chmod(), test_chmod_requires_mode(), test_missing_path_rejected(), test_mkdir_default_mode(), test_mkdir_mode(), test_mkpath(), test_mv(), test_mv_requires_two_paths(), test_non_executed_opcode(), test_prepadd_plan(), test_prepadd_requires_reqid(), test_prepdel_plan(), test_prepdel_requires_reqid(), test_rm_and_rmdir(), and test_trunc_size().