nginx-xrootd: src/net/cms/node_ops_unittest.c File Reference
node_ops_unittest.c File Reference
#include "node_ops.h"
#include <stdio.h>
#include <string.h>
Macros
#define K_CHMOD 1
#define K_MKDIR 3
#define K_MKPATH 4
#define K_MV 5
#define K_RM 8
#define K_RMDIR 9
#define K_TRUNC 23
#define K_PREPADD 6
#define K_PREPDEL 7
#define CHECK(cond)
Functions
static brix_cms_rrdata_t rr (const char *path, const char *path2, const char *mode)
static void test_mkdir_mode (void)
static void test_mkdir_default_mode (void)
static void test_mkpath (void)
static void test_chmod (void)
static void test_chmod_requires_mode (void)
static void test_trunc_size (void)
static void test_mv (void)
static void test_mv_requires_two_paths (void)
static void test_rm_and_rmdir (void)
static void test_missing_path_rejected (void)
static void test_non_executed_opcode (void)
static void test_prepadd_plan (void)
static void test_prepadd_requires_reqid (void)
static void test_prepdel_plan (void)
static void test_prepdel_requires_reqid (void)
int main (void)
Variables
static int g_fail
Macro Definition Documentation
CHECK
#define CHECK (cond)
Value:
    do { \
    if (!(cond)) { printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
                   g_fail++; } \
} while (0)
Definition at line 26 of file node_ops_unittest.c.
K_CHMOD
#define K_CHMOD 1
Definition at line 15 of file node_ops_unittest.c.
K_MKDIR
#define K_MKDIR 3
Definition at line 16 of file node_ops_unittest.c.
K_MKPATH
#define K_MKPATH 4
Definition at line 17 of file node_ops_unittest.c.
K_MV
#define K_MV 5
Definition at line 18 of file node_ops_unittest.c.
K_PREPADD
#define K_PREPADD 6
Definition at line 22 of file node_ops_unittest.c.
K_PREPDEL
#define K_PREPDEL 7
Definition at line 23 of file node_ops_unittest.c.
K_RM
#define K_RM 8
Definition at line 19 of file node_ops_unittest.c.
K_RMDIR
#define K_RMDIR 9
Definition at line 20 of file node_ops_unittest.c.
K_TRUNC
#define K_TRUNC 23
Definition at line 21 of file node_ops_unittest.c.
Function Documentation
main()
int main (void)
Definition at line 193 of file node_ops_unittest.c.
References g_fail, test_chmod(), test_chmod_requires_mode(), test_missing_path_rejected(), test_mkdir_default_mode(), test_mkdir_mode(), test_mkpath(), test_mv(), test_mv_requires_two_paths(), test_non_executed_opcode(), test_prepadd_plan(), test_prepadd_requires_reqid(), test_prepdel_plan(), test_prepdel_requires_reqid(), test_rm_and_rmdir(), and test_trunc_size().
rr()
static brix_cms_rrdata_t rr (const char * path, const char * path2, const char * mode) static
Definition at line 34 of file node_ops_unittest.c.
References brix_cms_rrdata_t::mode, brix_cms_rrdata_t::mode_len, brix_cms_rrdata_t::path, brix_cms_rrdata_t::path2, brix_cms_rrdata_t::path2_len, and brix_cms_rrdata_t::path_len.
Referenced by cache_open_recall_parked(), roundtrip_loop(), test_chmod(), test_chmod_requires_mode(), test_missing_path_rejected(), test_mkdir_default_mode(), test_mkdir_mode(), test_mkpath(), test_mv(), test_mv_requires_two_paths(), test_non_executed_opcode(), test_prepadd_plan(), test_prepadd_requires_reqid(), test_prepdel_plan(), test_prepdel_requires_reqid(), test_rm_and_rmdir(), and test_trunc_size().
test_chmod()
static void test_chmod (void) static
Definition at line 74 of file node_ops_unittest.c.
References brix_cms_node_plan_t::action, brix_cms_node_plan(), CHECK, K_CHMOD, brix_cms_node_plan_t::mode, rr(), and XRDCMS_NACT_CHMOD.
Referenced by main().
test_chmod_requires_mode()
static void test_chmod_requires_mode (void) static
Definition at line 84 of file node_ops_unittest.c.
References brix_cms_node_plan(), CHECK, K_CHMOD, and rr().
Referenced by main().
test_missing_path_rejected()
static void test_missing_path_rejected (void) static
Definition at line 130 of file node_ops_unittest.c.
References brix_cms_node_plan(), CHECK, K_MKDIR, and rr().
Referenced by main().
test_mkdir_default_mode()
static void test_mkdir_default_mode (void) static
Definition at line 56 of file node_ops_unittest.c.
References brix_cms_node_plan(), CHECK, K_MKDIR, brix_cms_node_plan_t::mode, rr(), and XRDCMS_NODE_DEFAULT_DIR_MODE.
Referenced by main().
test_mkdir_mode()
static void test_mkdir_mode (void) static
Definition at line 45 of file node_ops_unittest.c.
References brix_cms_node_plan_t::action, brix_cms_node_plan(), CHECK, K_MKDIR, brix_cms_node_plan_t::mode, brix_cms_node_plan_t::path, rr(), and XRDCMS_NACT_MKDIR.
Referenced by main().
test_mkpath()
static void test_mkpath (void) static
Definition at line 65 of file node_ops_unittest.c.
References brix_cms_node_plan_t::action, brix_cms_node_plan(), CHECK, K_MKPATH, rr(), and XRDCMS_NACT_MKPATH.
Referenced by main().
test_mv()
static void test_mv (void) static
Definition at line 102 of file node_ops_unittest.c.
References brix_cms_node_plan_t::action, brix_cms_node_plan(), CHECK, K_MV, brix_cms_node_plan_t::path, brix_cms_node_plan_t::path2, rr(), and XRDCMS_NACT_MV.
Referenced by main().
test_mv_requires_two_paths()
static void test_mv_requires_two_paths (void) static
Definition at line 113 of file node_ops_unittest.c.
References brix_cms_node_plan(), CHECK, K_MV, and rr().
Referenced by main().
test_non_executed_opcode()
static void test_non_executed_opcode (void) static
Definition at line 138 of file node_ops_unittest.c.
References brix_cms_node_plan(), CHECK, and rr().
Referenced by main().
test_prepadd_plan()
static void test_prepadd_plan (void) static
Definition at line 148 of file node_ops_unittest.c.
References brix_cms_node_plan_t::action, brix_cms_node_plan(), CHECK, K_PREPADD, brix_cms_node_plan_t::notify, brix_cms_rrdata_t::notify, brix_cms_rrdata_t::notify_len, brix_cms_node_plan_t::path, brix_cms_node_plan_t::prty, brix_cms_rrdata_t::prty, brix_cms_rrdata_t::prty_len, brix_cms_node_plan_t::reqid, brix_cms_rrdata_t::reqid, brix_cms_rrdata_t::reqid_len, rr(), and XRDCMS_NACT_PREPADD.
Referenced by main().
test_prepadd_requires_reqid()
static void test_prepadd_requires_reqid (void) static
Definition at line 165 of file node_ops_unittest.c.
References brix_cms_node_plan(), CHECK, K_PREPADD, and rr().
Referenced by main().
test_prepdel_plan()
static void test_prepdel_plan (void) static
Definition at line 173 of file node_ops_unittest.c.
References brix_cms_node_plan_t::action, brix_cms_node_plan(), CHECK, K_PREPDEL, brix_cms_node_plan_t::reqid, brix_cms_rrdata_t::reqid, brix_cms_rrdata_t::reqid_len, rr(), and XRDCMS_NACT_PREPDEL.
Referenced by main().
test_prepdel_requires_reqid()
static void test_prepdel_requires_reqid (void) static
Definition at line 185 of file node_ops_unittest.c.
References brix_cms_node_plan(), CHECK, K_PREPDEL, and rr().
Referenced by main().
test_rm_and_rmdir()
static void test_rm_and_rmdir (void) static
Definition at line 121 of file node_ops_unittest.c.
References brix_cms_node_plan_t::action, brix_cms_node_plan(), CHECK, K_RM, K_RMDIR, rr(), XRDCMS_NACT_RM, and XRDCMS_NACT_RMDIR.
Referenced by main().
test_trunc_size()
static void test_trunc_size (void) static
Definition at line 92 of file node_ops_unittest.c.
References brix_cms_node_plan_t::action, brix_cms_node_plan(), CHECK, K_TRUNC, rr(), brix_cms_node_plan_t::size, and XRDCMS_NACT_TRUNC.
Referenced by main().
Variable Documentation
g_fail
int g_fail static
Definition at line 25 of file node_ops_unittest.c.
Referenced by main().