nginx-xrootd: src/protocols/s3/object_meta.c File Reference
object_meta.c File Reference
#include "s3.h"
#include "usermeta.h"
#include "fs/cache/open.h"
#include "core/http/http_file_response.h"
#include "core/http/http_headers.h"
#include "observability/dashboard/dashboard_tracking.h"
#include "fs/vfs/vfs.h"
#include "protocols/shared/file_serve.h"
#include "protocols/shared/http_cache_fill.h"
#include "protocols/shared/http_serve_offload.h"
#include "protocols/root/zip/zip_http.h"
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include "object_internal.h"
Functions
ngx_int_t s3_handle_head (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf)
ngx_int_t s3_handle_head_bucket (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf)
ngx_int_t s3_handle_get_bucket_location (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf)
ngx_int_t s3_delete_respond (ngx_http_request_t *r, int op_errno)
ngx_int_t s3_handle_delete (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf)
Function Documentation
s3_delete_respond()
ngx_int_t s3_delete_respond (ngx_http_request_t * r, int op_errno)
Definition at line 235 of file object_meta.c.
References BRIX_S3_EVENT_DELETE_MISSING, BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, and s3_send_xml_error().
Referenced by s3_delete_async_render(), and s3_handle_delete().
s3_handle_delete()
ngx_int_t s3_handle_delete (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf)
Definition at line 258 of file object_meta.c.
References brix_vfs_unlink(), s3_delete_respond(), and s3_vfs_ctx().
Referenced by s3_dispatch_object_delete().
s3_handle_get_bucket_location()
ngx_int_t s3_handle_get_bucket_location (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf)
Definition at line 180 of file object_meta.c.
References brix_http_send_xml_buffer(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_ADD, BRIX_S3_METRIC_INC, ngx_http_s3_loc_conf_t::region, and XML_APPEND.
Referenced by s3_dispatch_bucket_get().
s3_handle_head()
ngx_int_t s3_handle_head (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf)
Definition at line 27 of file object_meta.c.
References brix_http_errno_to_status(), brix_http_set_file_headers(), brix_http_set_header(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_EVENT_NO_SUCH_KEY, BRIX_S3_METRIC_INC, BRIX_SD_RES_NEARLINE, BRIX_SD_RES_OFFLINE, brix_vfs_close(), brix_vfs_file_fd(), BRIX_VFS_O_READ, brix_vfs_open(), brix_vfs_residency(), brix_vfs_stat_t::is_directory, brix_vfs_stat_t::mtime, s3_echo_object_checksums(), s3_echo_user_metadata(), s3_fail(), s3_handle_conditional(), s3_vfs_ctx(), and brix_vfs_stat_t::size.
Referenced by s3_dispatch_object_method().
s3_handle_head_bucket()
ngx_int_t s3_handle_head_bucket (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf)
Definition at line 133 of file object_meta.c.
References BRIX_S3_EVENT_INVALID_URI, BRIX_S3_METRIC_INC, ngx_http_s3_loc_conf_t::common, ngx_memcpy, region, ngx_http_s3_loc_conf_t::region, ngx_http_brix_shared_conf_t::root_canon, s3_set_header(), and stat().
Referenced by s3_dispatch_empty_key().