nginx-xrootd: src/protocols/s3/object.c File Reference
object.c File Reference
#include "s3.h"
#include "usermeta.h"
#include "fs/cache/open.h"
#include "core/http/http_file_response.h"
#include "core/http/http_headers.h"
#include "observability/dashboard/dashboard_tracking.h"
#include "fs/vfs/vfs.h"
#include "protocols/shared/file_serve.h"
#include "protocols/shared/http_cache_fill.h"
#include "protocols/shared/http_serve_offload.h"
#include "protocols/root/zip/zip_http.h"
#include "object_internal.h"
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
struct s3_get_reenter_t
struct s3_get_serve_t
Functions
static void s3_serve_metrics (ngx_http_request_t *r, const brix_http_serve_result_t *result)
void s3_vfs_ctx (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, brix_vfs_ctx_t *vctx)
static ngx_int_t s3_get_reenter (ngx_http_request_t *r, void *data)
static ngx_int_t s3_get_serve_zip_member (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf)
static ngx_int_t s3_get_check_residency (ngx_http_request_t *r, brix_vfs_ctx_t *vctx)
static ngx_int_t s3_get_serve_offload (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, brix_vfs_ctx_t *vctx)
static ngx_int_t s3_get_cache_fill (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, brix_vfs_ctx_t *vctx)
static ngx_int_t s3_get_resolve (ngx_http_request_t *r, brix_vfs_ctx_t *vctx, brix_vfs_file_t **out_fh, brix_vfs_stat_t *out_vst)
static void s3_get_resolve_identity (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, char *identity, size_t identity_size)
static void s3_get_echo_headers (ngx_http_request_t *r, brix_vfs_file_t *fh, const char *fs_path)
static ngx_int_t s3_get_serve (ngx_http_request_t *r, const s3_get_serve_t *sv)
ngx_int_t s3_handle_get (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf)
Function Documentation
s3_get_cache_fill()
static ngx_int_t s3_get_cache_fill (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, brix_vfs_ctx_t * vctx) static
Definition at line 224 of file object.c.
References brix_http_cache_fill_if_needed(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, brix_vfs_export_relative(), s3_get_reenter_t::cf, ngx_http_s3_loc_conf_t::common, s3_get_reenter_t::fs_path, ngx_memcpy, ngx_pnalloc(), s3_get_reenter(), and brix_vfs_ctx_t::sd.
Referenced by s3_handle_get().
s3_get_check_residency()
static ngx_int_t s3_get_check_residency (ngx_http_request_t * r, brix_vfs_ctx_t * vctx) static
Definition at line 154 of file object.c.
References BRIX_S3_EVENT_ACCESS_DENIED, BRIX_SD_RES_NEARLINE, BRIX_SD_RES_OFFLINE, BRIX_SD_RES_ONLINE, brix_vfs_residency(), and s3_fail().
Referenced by s3_handle_get().
s3_get_echo_headers()
static void s3_get_echo_headers (ngx_http_request_t * r, brix_vfs_file_t * fh, const char * fs_path) static
Definition at line 348 of file object.c.
References brix_vfs_file_fd(), s3_echo_object_checksums(), and s3_echo_user_metadata().
Referenced by s3_handle_get().
s3_get_reenter()
static ngx_int_t s3_get_reenter (ngx_http_request_t * r, void * data) static
Definition at line 91 of file object.c.
References s3_get_reenter_t::cf, s3_get_reenter_t::fs_path, and s3_handle_get().
Referenced by s3_get_cache_fill().
s3_get_resolve()
static ngx_int_t s3_get_resolve (ngx_http_request_t * r, brix_vfs_ctx_t * vctx, brix_vfs_file_t ** out_fh, brix_vfs_stat_t * out_vst) static
Definition at line 272 of file object.c.
References brix_http_errno_to_status(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_EVENT_NO_SUCH_KEY, BRIX_S3_METRIC_INC, brix_vfs_close(), brix_vfs_file_stat(), BRIX_VFS_O_READ, brix_vfs_open(), brix_vfs_stat_t::is_directory, and s3_fail().
Referenced by s3_handle_get().
s3_get_resolve_identity()
static void s3_get_resolve_identity (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, char * identity, size_t identity_size) static
Definition at line 316 of file object.c.
References ngx_http_s3_loc_conf_t::access_key, brix_identity_subject_cstr(), ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, and ngx_memcpy.
Referenced by s3_handle_get().
s3_get_serve()
static ngx_int_t s3_get_serve (ngx_http_request_t * r, const s3_get_serve_t * sv) static
Definition at line 380 of file object.c.
References brix_http_serve_file_ranged(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, BRIX_XFER_PROTO_S3, s3_get_serve_t::compress, brix_http_serve_opts_t::compress, brix_http_serve_opts_t::etag_flags, s3_get_serve_t::fh, s3_get_serve_t::fs_path, s3_get_serve_t::identity, brix_http_serve_opts_t::identity, brix_http_serve_opts_t::op_name, brix_http_serve_opts_t::pre_header_send, s3_get_pre_header(), s3_serve_metrics(), s3_get_serve_t::vst, and brix_http_serve_opts_t::xfer_proto.
Referenced by s3_handle_get().
s3_get_serve_offload()
static ngx_int_t s3_get_serve_offload (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, brix_vfs_ctx_t * vctx) static
Definition at line 179 of file object.c.
References brix_http_serve_offload_remote(), BRIX_S3_EVENT_ACCESS_DENIED, BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, brix_vfs_export_relative(), BRIX_XFER_PROTO_S3, ngx_http_s3_loc_conf_t::common, ngx_http_brix_shared_conf_t::compress, brix_http_serve_opts_t::compress, brix_http_serve_opts_t::etag_flags, brix_http_serve_opts_t::identity, brix_http_serve_opts_t::op_name, s3_fail(), s3_serve_metrics(), brix_vfs_ctx_t::sd, and brix_http_serve_opts_t::xfer_proto.
Referenced by s3_handle_get().
s3_get_serve_zip_member()
static ngx_int_t s3_get_serve_zip_member (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf) static
Definition at line 110 of file object.c.
References BRIX_S3_EVENT_NO_SUCH_KEY, brix_zip_http_member_arg(), brix_zip_http_serve(), ngx_http_s3_loc_conf_t::common, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, s3_fail(), s3_send_xml_error(), ngx_http_s3_loc_conf_t::zip_access, and ngx_http_s3_loc_conf_t::zip_cd_max_bytes.
Referenced by s3_handle_get().
s3_handle_get()
ngx_int_t s3_handle_get (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf)
Definition at line 422 of file object.c.
References brix_vfs_close(), ngx_http_s3_loc_conf_t::common, ngx_http_brix_shared_conf_t::compress, s3_get_serve_t::compress, s3_get_serve_t::fh, s3_get_serve_t::fs_path, s3_get_serve_t::identity, brix_vfs_stat_t::mtime, s3_get_cache_fill(), s3_get_check_residency(), s3_get_echo_headers(), s3_get_resolve(), s3_get_resolve_identity(), s3_get_serve(), s3_get_serve_offload(), s3_get_serve_zip_member(), s3_handle_conditional(), s3_vfs_ctx(), brix_vfs_stat_t::size, and s3_get_serve_t::vst.
Referenced by s3_dispatch_object_get(), and s3_get_reenter().
s3_serve_metrics()
static void s3_serve_metrics (ngx_http_request_t * r, const brix_http_serve_result_t * result) static
Definition at line 17 of file object.c.
References BRIX_S3_METRIC_ADD, BRIX_S3_METRIC_INC, BRIX_S3_RANGE_FULL, BRIX_S3_RANGE_PARTIAL, BRIX_S3_RANGE_UNSATISFIED, BRIX_SERVE_RANGE_PARTIAL, BRIX_SERVE_RANGE_UNSATISFIED, brix_http_serve_result_t::bytes_sent, and brix_http_serve_result_t::range_result.
Referenced by s3_get_serve(), and s3_get_serve_offload().
s3_vfs_ctx()
void s3_vfs_ctx (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, brix_vfs_ctx_t * vctx)
Definition at line 50 of file object.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_S3, brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_bind_backend_mint(), brix_vfs_ctx_init(), ngx_http_s3_loc_conf_t::cache_root_canon, ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, brix_vfs_ctx_t::pool, ngx_http_brix_shared_conf_t::root_canon, s3_vfs_bind_deleg(), ngx_http_brix_shared_conf_t::storage_credential_dir, ngx_http_brix_shared_conf_t::storage_credential_fallback, ngx_http_brix_shared_conf_t::storage_credential_mint_ca_cert, ngx_http_brix_shared_conf_t::storage_credential_mint_ca_key, and ngx_http_brix_shared_conf_t::storage_credential_mint_ttl.
Referenced by s3_handle_delete(), s3_handle_get(), and s3_handle_head().