nginx-xrootd: src/observability/metrics/unified.h File Reference
unified.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include "core/types/proto_list.h"
Macros
#define X(ID, metric_label, dash_name, http_plane) BRIX_PROTO_##ID,
#define BRIX_METRIC_AUTH_NONE 0
#define BRIX_METRIC_AUTH_GSI 1
#define BRIX_METRIC_AUTH_TOKEN 2
#define BRIX_METRIC_AUTH_SSS 3
#define BRIX_METRIC_AUTH_S3KEY 4
#define BRIX_METRIC_AUTH_UNIX 5
#define BRIX_METRIC_AUTH_KRB5 6
#define BRIX_METRIC_AUTH_HOST 7
#define BRIX_METRIC_AUTH_PWD 8
#define BRIX_METRIC_AUTH_COUNT 9
#define BRIX_METRIC_AUTH_FAIL 0
#define BRIX_METRIC_AUTH_OK 1
#define BRIX_METRIC_AUTH_STATUS_COUNT 2
#define BRIX_METRIC_TPC_PULL 0
#define BRIX_METRIC_TPC_PUSH 1
#define BRIX_METRIC_TPC_DIRECTION_COUNT 2
#define BRIX_IO_LATENCY_BUCKETS 9
Enumerations
enum brix_proto_t {
BRIX_PROTO_ROOT , BRIX_PROTO_WEBDAV , BRIX_PROTO_S3 , BRIX_PROTO_CVMFS ,
BRIX_PROTO_COUNT
}
enum brix_metric_op_t {
BRIX_METRIC_OP_READ = 0 , BRIX_METRIC_OP_WRITE = 1 , BRIX_METRIC_OP_STAT = 2 , BRIX_METRIC_OP_DELETE = 3 ,
BRIX_METRIC_OP_MKDIR = 4 , BRIX_METRIC_OP_RENAME = 5 , BRIX_METRIC_OP_DIRLIST = 6 , BRIX_METRIC_OP_TPC = 7 ,
BRIX_METRIC_OP_XATTR = 8 , BRIX_METRIC_OP_COPY = 9 , BRIX_METRIC_OP_COUNT = 10
}
enum brix_err_class_t {
BRIX_ERR_NONE = 0 , BRIX_ERR_NOT_FOUND = 1 , BRIX_ERR_FORBIDDEN = 2 , BRIX_ERR_IO = 3 ,
BRIX_ERR_OTHER = 4 , BRIX_ERR_COUNT = 5
}
Functions
const char * brix_metric_proto_name (brix_proto_t proto)
const char * brix_metric_op_name (brix_metric_op_t op)
const char * brix_metric_err_name (brix_err_class_t err)
const char * brix_metric_auth_method_name (ngx_uint_t auth_method)
brix_err_class_t brix_metric_err_from_errno (int sys_errno)
brix_err_class_t brix_metric_err_from_http_status (ngx_uint_t status)
ngx_uint_t brix_metric_auth_slot (ngx_uint_t auth_method)
void brix_metric_op_done (brix_proto_t proto, brix_metric_op_t op, size_t bytes, ngx_msec_t latency_usec, brix_err_class_t err)
void brix_metric_backend_bytes (const char *backend_name, brix_metric_op_t op, size_t bytes)
void brix_metric_cache_result (brix_proto_t proto, unsigned int hit, size_t bytes_evicted)
void brix_metric_cache_usage_ratio (ngx_uint_t occupancy_ppm)
void brix_metric_cache_watermark_purge (ngx_uint_t files, uint64_t bytes)
void brix_metric_wt_stage_usage_ratio (ngx_uint_t occupancy_ppm)
void brix_metric_wt_stage_throttled (int reject)
void brix_metric_auth (brix_proto_t proto, ngx_uint_t auth_method, unsigned int success)
void brix_metric_tpc (brix_proto_t proto, unsigned int is_push, size_t bytes, brix_err_class_t err)
Macro Definition Documentation
BRIX_IO_LATENCY_BUCKETS
#define BRIX_IO_LATENCY_BUCKETS 9
Definition at line 82 of file unified.h.
BRIX_METRIC_AUTH_COUNT
#define BRIX_METRIC_AUTH_COUNT 9
Definition at line 71 of file unified.h.
BRIX_METRIC_AUTH_FAIL
#define BRIX_METRIC_AUTH_FAIL 0
Definition at line 73 of file unified.h.
BRIX_METRIC_AUTH_GSI
#define BRIX_METRIC_AUTH_GSI 1
Definition at line 63 of file unified.h.
BRIX_METRIC_AUTH_HOST
#define BRIX_METRIC_AUTH_HOST 7
Definition at line 69 of file unified.h.
BRIX_METRIC_AUTH_KRB5
#define BRIX_METRIC_AUTH_KRB5 6
Definition at line 68 of file unified.h.
BRIX_METRIC_AUTH_NONE
#define BRIX_METRIC_AUTH_NONE 0
Definition at line 62 of file unified.h.
BRIX_METRIC_AUTH_OK
#define BRIX_METRIC_AUTH_OK 1
Definition at line 74 of file unified.h.
BRIX_METRIC_AUTH_PWD
#define BRIX_METRIC_AUTH_PWD 8
Definition at line 70 of file unified.h.
BRIX_METRIC_AUTH_S3KEY
#define BRIX_METRIC_AUTH_S3KEY 4
Definition at line 66 of file unified.h.
BRIX_METRIC_AUTH_SSS
#define BRIX_METRIC_AUTH_SSS 3
Definition at line 65 of file unified.h.
BRIX_METRIC_AUTH_STATUS_COUNT
#define BRIX_METRIC_AUTH_STATUS_COUNT 2
Definition at line 75 of file unified.h.
BRIX_METRIC_AUTH_TOKEN
#define BRIX_METRIC_AUTH_TOKEN 2
Definition at line 64 of file unified.h.
BRIX_METRIC_AUTH_UNIX
#define BRIX_METRIC_AUTH_UNIX 5
Definition at line 67 of file unified.h.
BRIX_METRIC_TPC_DIRECTION_COUNT
#define BRIX_METRIC_TPC_DIRECTION_COUNT 2
Definition at line 79 of file unified.h.
BRIX_METRIC_TPC_PULL
#define BRIX_METRIC_TPC_PULL 0
Definition at line 77 of file unified.h.
BRIX_METRIC_TPC_PUSH
#define BRIX_METRIC_TPC_PUSH 1
Definition at line 78 of file unified.h.
X
#define X (ID, metric_label, dash_name, http_plane) BRIX_PROTO_##ID,
Definition at line 33 of file unified.h.
Enumeration Type Documentation
brix_err_class_t
enum brix_err_class_t
Enumerator
BRIX_ERR_NONE
BRIX_ERR_NOT_FOUND
BRIX_ERR_FORBIDDEN
BRIX_ERR_IO
BRIX_ERR_OTHER
BRIX_ERR_COUNT
Definition at line 53 of file unified.h.
brix_metric_op_t
enum brix_metric_op_t
Enumerator
BRIX_METRIC_OP_READ
BRIX_METRIC_OP_WRITE
BRIX_METRIC_OP_STAT
BRIX_METRIC_OP_DELETE
BRIX_METRIC_OP_MKDIR
BRIX_METRIC_OP_RENAME
BRIX_METRIC_OP_DIRLIST
BRIX_METRIC_OP_TPC
BRIX_METRIC_OP_XATTR
BRIX_METRIC_OP_COPY
BRIX_METRIC_OP_COUNT
Definition at line 39 of file unified.h.
brix_proto_t
enum brix_proto_t
Enumerator
BRIX_PROTO_ROOT
BRIX_PROTO_WEBDAV
BRIX_PROTO_S3
BRIX_PROTO_CVMFS
BRIX_PROTO_COUNT
Definition at line 32 of file unified.h.
Function Documentation
brix_metric_auth()
void brix_metric_auth (brix_proto_t proto, ngx_uint_t auth_method, unsigned int success)
Definition at line 396 of file unified.c.
References ngx_brix_unified_metrics_t::auth_total, BRIX_ATOMIC_INC, BRIX_METRIC_AUTH_FAIL, BRIX_METRIC_AUTH_OK, brix_metric_auth_slot(), brix_metrics_shared(), BRIX_PROTO_COUNT, and ngx_brix_metrics_t::unified.
Referenced by brix_handle_host_auth(), brix_handle_krb5_auth(), brix_handle_pwd_auth(), brix_handle_unix_auth(), ngx_http_brix_webdav_access_handler(), pwd_round1(), pwd_round2(), s3_record_auth_result(), and s3_verify_bearer().
brix_metric_auth_method_name()
const char * brix_metric_auth_method_name (ngx_uint_t auth_method)
Definition at line 150 of file unified.c.
References brix_metric_auth_slot(), and brix_unified_auth_names.
Referenced by brix_access_log_emit().
brix_metric_auth_slot()
ngx_uint_t brix_metric_auth_slot (ngx_uint_t auth_method)
Definition at line 119 of file unified.c.
References BRIX_AUTHN_GSI, BRIX_AUTHN_HOST, BRIX_AUTHN_KRB5, BRIX_AUTHN_PWD, BRIX_AUTHN_S3KEY, BRIX_AUTHN_SSS, BRIX_AUTHN_TOKEN, BRIX_AUTHN_UNIX, BRIX_METRIC_AUTH_GSI, BRIX_METRIC_AUTH_HOST, BRIX_METRIC_AUTH_KRB5, BRIX_METRIC_AUTH_NONE, BRIX_METRIC_AUTH_PWD, BRIX_METRIC_AUTH_S3KEY, BRIX_METRIC_AUTH_SSS, BRIX_METRIC_AUTH_TOKEN, and BRIX_METRIC_AUTH_UNIX.
Referenced by brix_metric_auth(), and brix_metric_auth_method_name().
brix_metric_backend_bytes()
void brix_metric_backend_bytes (const char * backend_name, brix_metric_op_t op, size_t bytes)
Definition at line 266 of file unified.c.
References BRIX_ATOMIC_ADD, brix_fs_id_from_name(), BRIX_METRIC_OP_READ, BRIX_METRIC_OP_WRITE, brix_metrics_shared(), ngx_brix_unified_metrics_t::io_bytes_read_backend, ngx_brix_unified_metrics_t::io_bytes_written_backend, and ngx_brix_metrics_t::unified.
Referenced by brix_handle_pgread(), brix_handle_read(), brix_http_serve_file_ranged(), brix_read_serve_sendfile(), brix_vfs_io_account(), and brix_vfs_observe_ctx_op().
brix_metric_cache_result()
void brix_metric_cache_result (brix_proto_t proto, unsigned int hit, size_t bytes_evicted)
Definition at line 301 of file unified.c.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, brix_metrics_shared(), BRIX_PROTO_COUNT, ngx_brix_unified_metrics_t::cache_bytes_evicted, ngx_brix_unified_metrics_t::cache_hits, ngx_brix_unified_metrics_t::cache_misses, and ngx_brix_metrics_t::unified.
Referenced by brix_vfs_open(), and cvmfs_finalize_observe().
brix_metric_cache_usage_ratio()
void brix_metric_cache_usage_ratio (ngx_uint_t occupancy_ppm)
Definition at line 330 of file unified.c.
References brix_metrics_shared(), ngx_brix_unified_metrics_t::cache_usage_ratio_ppm, and ngx_brix_metrics_t::unified.
Referenced by brix_cache_watermark_purge().
brix_metric_cache_watermark_purge()
void brix_metric_cache_watermark_purge (ngx_uint_t files, uint64_t bytes)
Definition at line 346 of file unified.c.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, brix_metrics_shared(), ngx_brix_unified_metrics_t::cache_watermark_evicted_bytes, ngx_brix_unified_metrics_t::cache_watermark_evicted_files, ngx_brix_unified_metrics_t::cache_watermark_purges, and ngx_brix_metrics_t::unified.
Referenced by brix_cache_watermark_purge().
brix_metric_err_from_errno()
brix_err_class_t brix_metric_err_from_errno (int sys_errno)
Definition at line 161 of file unified.c.
References BRIX_ERR_FORBIDDEN, BRIX_ERR_IO, BRIX_ERR_NONE, BRIX_ERR_NOT_FOUND, and BRIX_ERR_OTHER.
Referenced by brix_vfs_observe_ctx_op().
brix_metric_err_from_http_status()
brix_err_class_t brix_metric_err_from_http_status (ngx_uint_t status)
Definition at line 187 of file unified.c.
References BRIX_ERR_FORBIDDEN, BRIX_ERR_IO, BRIX_ERR_NONE, BRIX_ERR_NOT_FOUND, and BRIX_ERR_OTHER.
Referenced by s3_metrics_response_status(), and webdav_metrics_response().
brix_metric_err_name()
const char * brix_metric_err_name (brix_err_class_t err)
Definition at line 108 of file unified.c.
References BRIX_ERR_COUNT, and brix_unified_err_names.
Referenced by brix_access_log_emit(), and brix_export_unified_metrics().
brix_metric_op_done()
void brix_metric_op_done (brix_proto_t proto, brix_metric_op_t op, size_t bytes, ngx_msec_t latency_usec, brix_err_class_t err)
Definition at line 212 of file unified.c.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, BRIX_ERR_COUNT, BRIX_IO_LATENCY_BUCKETS, brix_latency_bounds, BRIX_METRIC_OP_COUNT, BRIX_METRIC_OP_READ, BRIX_METRIC_OP_WRITE, brix_metrics_shared(), BRIX_PROTO_COUNT, ngx_brix_unified_metrics_t::io_bytes_read, ngx_brix_unified_metrics_t::io_bytes_written, ngx_brix_unified_metrics_t::io_latency_bucket, ngx_brix_unified_metrics_t::io_latency_count, ngx_brix_unified_metrics_t::io_latency_sum_usec, ngx_brix_unified_metrics_t::io_ops_total, and ngx_brix_metrics_t::unified.
Referenced by brix_vfs_observe_ctx_op(), s3_metrics_response_status(), and webdav_metrics_response().
brix_metric_op_name()
const char * brix_metric_op_name (brix_metric_op_t op)
Definition at line 101 of file unified.c.
References BRIX_METRIC_OP_COUNT, and brix_unified_op_names.
Referenced by brix_access_log_emit(), and brix_export_unified_metrics().
brix_metric_proto_name()
const char * brix_metric_proto_name (brix_proto_t proto)
Definition at line 94 of file unified.c.
References BRIX_PROTO_COUNT, and brix_unified_proto_names.
Referenced by brix_access_log_emit(), and brix_export_unified_metrics().
brix_metric_tpc()
void brix_metric_tpc (brix_proto_t proto, unsigned int is_push, size_t bytes, brix_err_class_t err)
Definition at line 423 of file unified.c.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, BRIX_ERR_COUNT, BRIX_ERR_NONE, BRIX_METRIC_TPC_PULL, BRIX_METRIC_TPC_PUSH, brix_metrics_shared(), BRIX_PROTO_COUNT, ngx_brix_unified_metrics_t::tpc_bytes, ngx_brix_unified_metrics_t::tpc_transfers, and ngx_brix_metrics_t::unified.
Referenced by brix_tpc_metric_transfer().
brix_metric_wt_stage_throttled()
void brix_metric_wt_stage_throttled (int reject)
Definition at line 377 of file unified.c.
References BRIX_ATOMIC_INC, brix_metrics_shared(), ngx_brix_metrics_t::unified, ngx_brix_unified_metrics_t::wt_stage_throttled_reject, and ngx_brix_unified_metrics_t::wt_stage_throttled_wait.
Referenced by brix_open_stage_backpressure().
brix_metric_wt_stage_usage_ratio()
void brix_metric_wt_stage_usage_ratio (ngx_uint_t occupancy_ppm)
Definition at line 363 of file unified.c.
References brix_metrics_shared(), ngx_brix_metrics_t::unified, and ngx_brix_unified_metrics_t::wt_stage_usage_ratio_ppm.
Referenced by brix_wt_stage_admit().