nginx-xrootd: src/observability/pmark/config.c File Reference
config.c File Reference
#include "pmark.h"
#include "core/config/shared_conf.h"
Functions
void brix_pmark_conf_init (brix_pmark_conf_t *c)
char * brix_pmark_conf_merge (ngx_conf_t *cf, brix_pmark_conf_t *prev, brix_pmark_conf_t *conf)
static brix_pmark_conf_t * pmark_conf (void *conf)
char * brix_pmark_set_firefly_dest (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_pmark_set_domain (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_pmark_set_map_experiment (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_pmark_set_map_activity (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Function Documentation
brix_pmark_conf_init()
void brix_pmark_conf_init (brix_pmark_conf_t * c)
Definition at line 26 of file config.c.
References c.
Referenced by ngx_http_brix_shared_init().
brix_pmark_conf_merge()
char * brix_pmark_conf_merge (ngx_conf_t * cf, brix_pmark_conf_t * prev, brix_pmark_conf_t * conf)
Definition at line 40 of file config.c.
References brix_pmark_conf_t::act_rules, brix_pmark_conf_t::appname, BRIX_PMARK_DOMAIN_REMOTE, brix_pmark_conf_t::defsfile, brix_pmark_conf_t::domain, brix_pmark_conf_t::echo, brix_pmark_conf_t::enable, brix_pmark_conf_t::exp_rules, brix_pmark_conf_t::firefly, brix_pmark_conf_t::firefly_dest, brix_pmark_conf_t::firefly_origin, brix_pmark_conf_t::flowlabel, brix_pmark_conf_t::http_plain, and brix_pmark_conf_t::scitag_cgi.
Referenced by ngx_http_brix_shared_merge().
brix_pmark_set_domain()
char * brix_pmark_set_domain (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 102 of file config.c.
References BRIX_PMARK_DOMAIN_ANY, BRIX_PMARK_DOMAIN_LOCAL, BRIX_PMARK_DOMAIN_REMOTE, brix_pmark_conf_t::domain, and pmark_conf().
brix_pmark_set_firefly_dest()
char * brix_pmark_set_firefly_dest (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 74 of file config.c.
References brix_pmark_conf_t::firefly_dest, and pmark_conf().
brix_pmark_set_map_activity()
char * brix_pmark_set_map_activity (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 171 of file config.c.
References brix_pmark_act_rule_t::act_name, brix_pmark_conf_t::act_rules, BRIX_PMARK_ACTR_DEFAULT, BRIX_PMARK_ACTR_ROLE, BRIX_PMARK_ACTR_USER, brix_pmark_act_rule_t::exp_name, brix_pmark_act_rule_t::kind, brix_pmark_act_rule_t::match, and pmark_conf().
brix_pmark_set_map_experiment()
char * brix_pmark_set_map_experiment (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 126 of file config.c.
References BRIX_PMARK_EXP_DEFAULT, BRIX_PMARK_EXP_PATH, BRIX_PMARK_EXP_VO, brix_pmark_exp_rule_t::exp_name, brix_pmark_conf_t::exp_rules, brix_pmark_exp_rule_t::kind, brix_pmark_exp_rule_t::match, and pmark_conf().
pmark_conf()
static brix_pmark_conf_t * pmark_conf (void * conf) static
Definition at line 67 of file config.c.
Referenced by brix_pmark_set_domain(), brix_pmark_set_firefly_dest(), brix_pmark_set_map_activity(), and brix_pmark_set_map_experiment().