nginx-xrootd: src/observability/dashboard/noop.c File Reference
noop.c File Reference
#include "dashboard.h"
#include "dashboard_tracking.h"
Functions
ngx_int_t brix_configure_dashboard (ngx_conf_t *cf)
ngx_int_t ngx_brix_dashboard_shm_init (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t ngx_brix_dashboard_events_shm_init (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t ngx_brix_dashboard_history_shm_init (ngx_shm_zone_t *shm_zone, void *data)
int brix_transfer_slot_alloc (brix_transfer_table_t *t, const u_char sessid[16], const char *client_ip, const char *identity, const char *path, uint8_t direction, uint8_t proto, int64_t now_ms)
int brix_transfer_slot_alloc_ex (brix_transfer_table_t *t, const u_char sessid[16], const char *client_ip, const char *identity, const char *vo, const char *path, const char *op, uint8_t direction, uint8_t proto, int64_t expected_bytes, int64_t now_ms)
void brix_transfer_slot_update (brix_transfer_table_t *t, int slot_idx, ngx_atomic_int_t nbytes, int64_t now_ms)
void brix_transfer_slot_update_bytes (brix_transfer_table_t *t, int slot_idx, ngx_atomic_int_t nbytes, int64_t now_ms)
void brix_transfer_slot_set_state (brix_transfer_table_t *t, int slot_idx, uint8_t state, int64_t now_ms)
void brix_transfer_slot_set_error (brix_transfer_table_t *t, int slot_idx, const char *reason, int64_t now_ms)
void brix_transfer_slot_set_tpc_remote (brix_transfer_table_t *t, int slot_idx, const char *remote_host, const char *path_hint, int remote_status, int curl_exit)
void brix_transfer_slot_count_op (brix_transfer_table_t *t, int slot_idx, const char *op)
void brix_transfer_slot_free (brix_transfer_table_t *t, int slot_idx)
void brix_transfer_slot_free_all_for_session (brix_transfer_table_t *t, const u_char sessid[16])
void brix_dashboard_event_add (uint8_t class_id, uint8_t proto, uint16_t status, const char *message, const char *path_hint)
ngx_uint_t brix_dashboard_events_snapshot (brix_dashboard_event_t *out, ngx_uint_t max_events)
void brix_dashboard_history_sample (int64_t now_ms)
ngx_uint_t brix_dashboard_history_snapshot (brix_dashboard_history_bucket_t *out, ngx_uint_t max_buckets)
int brix_dashboard_http_start (ngx_http_request_t *r, const char *path, uint8_t proto, uint8_t direction, const char *op, int64_t expected_bytes)
int brix_dashboard_http_start_identity (ngx_http_request_t *r, const char *path, const char *identity, const char *vo, uint8_t proto, uint8_t direction, const char *op, int64_t expected_bytes)
void brix_dashboard_http_add (ngx_http_request_t *r, ngx_atomic_int_t bytes)
void brix_dashboard_http_state (ngx_http_request_t *r, uint8_t state)
void brix_dashboard_http_error (ngx_http_request_t *r, const char *reason)
void brix_dashboard_http_tpc_remote (ngx_http_request_t *r, const char *remote_url, int remote_status, int curl_exit)
void brix_dashboard_http_finish (ngx_http_request_t *r)
Variables
ngx_shm_zone_t * ngx_brix_dashboard_shm_zone
ngx_shm_zone_t * ngx_brix_dashboard_events_shm_zone
ngx_shm_zone_t * ngx_brix_dashboard_history_shm_zone
Function Documentation
brix_configure_dashboard()
ngx_int_t brix_configure_dashboard (ngx_conf_t * cf)
Definition at line 31 of file noop.c.
References brix_shm_zone_size(), ngx_brix_dashboard_events_shm_init(), ngx_brix_dashboard_events_shm_zone, ngx_brix_dashboard_history_shm_init(), ngx_brix_dashboard_history_shm_zone, ngx_brix_dashboard_shm_init(), ngx_brix_dashboard_shm_zone, and ngx_stream_brix_module.
Referenced by ngx_http_brix_cvmfs_postconfiguration(), and ngx_stream_brix_postconfiguration().
brix_dashboard_event_add()
void brix_dashboard_event_add (uint8_t class_id, uint8_t proto, uint16_t status, const char * message, const char * path_hint)
Definition at line 177 of file noop.c.
References brix_dashboard_events_mutex, BRIX_DASHBOARD_MAX_EVENTS, brix_dashboard_event_t::class_id, dashboard_event_copy(), dashboard_events_table(), brix_dashboard_event_table_t::events, brix_dashboard_event_t::message, brix_dashboard_event_table_t::next_sequence, brix_dashboard_event_t::path_hint, brix_dashboard_event_t::proto, brix_dashboard_event_t::sequence, brix_dashboard_event_t::status, and brix_dashboard_event_t::time_ms.
Referenced by admin_cluster_delete(), admin_cluster_drain(), admin_cluster_register(), admin_cluster_undrain(), admin_proxy_add(), brix_transfer_slot_alloc_ex(), brix_transfer_slot_set_error(), dashboard_build_transfer_rows(), login_post_body_handler(), ngx_http_brix_dashboard_api_handler(), and ngx_http_brix_dashboard_check_auth().
brix_dashboard_events_snapshot()
ngx_uint_t brix_dashboard_events_snapshot (brix_dashboard_event_t * out, ngx_uint_t max_events)
Definition at line 188 of file noop.c.
References brix_dashboard_events_mutex, BRIX_DASHBOARD_MAX_EVENTS, dashboard_events_table(), brix_dashboard_event_table_t::events, brix_dashboard_event_table_t::next_sequence, and brix_dashboard_event_t::sequence.
Referenced by dashboard_build_events().
brix_dashboard_history_sample()
void brix_dashboard_history_sample (int64_t now_ms)
Definition at line 197 of file noop.c.
References brix_dashboard_history_bucket_t::active, brix_dashboard_history_bucket_t::active_tpc, brix_dashboard_history_bucket_t::auth_failures, ngx_brix_webdav_metrics_t::auth_total, ngx_brix_s3_metrics_t::auth_total, BRIX_DASHBOARD_HISTORY_INTERVAL_MS, brix_dashboard_history_mutex, BRIX_DASHBOARD_MAX_TRANSFERS, BRIX_METRICS_MAX_SERVERS, BRIX_NOPS, BRIX_OP_AUTH, BRIX_S3_AUTH_BAD_KEY, BRIX_S3_AUTH_MALFORMED, BRIX_S3_AUTH_SIG_MISMATCH, BRIX_WEBDAV_AUTH_RESULT_REJECTED, BRIX_XFER_DIR_TPC, BRIX_XFER_NPROTOS, BRIX_XFER_PROTO_ROOT, brix_dashboard_history_bucket_t::bucket_start_ms, brix_dashboard_history_t::buckets, brix_dashboard_history_bucket_t::bytes_rx, ngx_brix_srv_metrics_t::bytes_rx_total, ngx_brix_s3_metrics_t::bytes_rx_total, ngx_brix_webdav_metrics_t::bytes_rx_total, brix_dashboard_history_bucket_t::bytes_tx, ngx_brix_srv_metrics_t::bytes_tx_total, ngx_brix_s3_metrics_t::bytes_tx_total, ngx_brix_webdav_metrics_t::bytes_tx_total, brix_dashboard_history_bucket_t::cache_occupancy_ppm, dashboard_history_bucket_index(), dashboard_history_table(), brix_transfer_slot_t::direction, brix_dashboard_history_bucket_t::errors, brix_transfer_slot_t::in_use, brix_dashboard_history_t::last_bucket_start_ms, ngx_brix_dashboard_shm_zone, ngx_brix_shm_zone, ngx_brix_srv_metrics_t::op_err, brix_transfer_slot_t::proto, ngx_brix_metrics_t::s3, ngx_brix_metrics_t::servers, brix_transfer_table_t::slots, ngx_brix_metrics_t::webdav, and brix_dashboard_history_bucket_t::write_stalls.
Referenced by ngx_http_brix_dashboard_api_handler().
brix_dashboard_history_snapshot()
ngx_uint_t brix_dashboard_history_snapshot (brix_dashboard_history_bucket_t * out, ngx_uint_t max_buckets)
Definition at line 203 of file noop.c.
References BRIX_DASHBOARD_HISTORY_BUCKETS, BRIX_DASHBOARD_HISTORY_INTERVAL_MS, brix_dashboard_history_mutex, brix_dashboard_history_bucket_t::bucket_start_ms, brix_dashboard_history_t::buckets, dashboard_history_bucket_index(), dashboard_history_table(), and brix_dashboard_history_t::last_bucket_start_ms.
Referenced by dashboard_fill_history().
brix_dashboard_http_add()
void brix_dashboard_http_add (ngx_http_request_t * r, ngx_atomic_int_t bytes)
Definition at line 241 of file noop.c.
References brix_transfer_slot_update_bytes(), dashboard_http_track(), brix_dashboard_http_track_t::slot, and brix_dashboard_http_track_t::table.
Referenced by brix_http_serve_file_ranged(), ngx_http_brix_webdav_tpc_handle_copy(), s3_put_aio_done(), s3_put_finalize_ok(), tpc_marker_finish(), tpc_thread_done(), webdav_put_aio_done(), webdav_put_body_inner(), and webdav_tpc_handle_push().
brix_dashboard_http_error()
void brix_dashboard_http_error (ngx_http_request_t * r, const char * reason)
Definition at line 255 of file noop.c.
References brix_transfer_slot_set_error(), dashboard_http_track(), brix_dashboard_http_track_t::slot, and brix_dashboard_http_track_t::table.
Referenced by brix_http_serve_file_ranged(), ngx_http_brix_webdav_tpc_handle_copy(), s3_put_finalize_bad_digest(), s3_put_finalize_client_error(), s3_put_finalize_codec_error(), s3_put_finalize_error(), s3_put_finalize_fs_error(), s3_put_finalize_invalid_request(), tpc_marker_finish(), tpc_thread_done(), webdav_put_aio_done(), webdav_put_body_inner(), and webdav_tpc_handle_push().
brix_dashboard_http_finish()
void brix_dashboard_http_finish (ngx_http_request_t * r)
Definition at line 272 of file noop.c.
References brix_transfer_slot_free(), brix_transfer_slot_set_state(), BRIX_XFER_STATE_CLOSING, dashboard_http_track(), brix_dashboard_http_track_t::slot, and brix_dashboard_http_track_t::table.
Referenced by brix_http_serve_file_ranged(), ngx_http_brix_webdav_tpc_handle_copy(), s3_put_finalize_bad_digest(), s3_put_finalize_client_error(), s3_put_finalize_codec_error(), s3_put_finalize_empty_ok(), s3_put_finalize_error(), s3_put_finalize_fs_error(), s3_put_finalize_invalid_request(), tpc_marker_finish(), tpc_thread_done(), webdav_put_aio_done(), webdav_put_body_inner(), and webdav_tpc_handle_push().
brix_dashboard_http_start()
int brix_dashboard_http_start (ngx_http_request_t * r, const char * path, uint8_t proto, uint8_t direction, const char * op, int64_t expected_bytes)
Definition at line 212 of file noop.c.
References brix_dashboard_http_start_identity().
brix_dashboard_http_start_identity()
int brix_dashboard_http_start_identity (ngx_http_request_t * r, const char * path, const char * identity, const char * vo, uint8_t proto, uint8_t direction, const char * op, int64_t expected_bytes)
Definition at line 225 of file noop.c.
References brix_transfer_slot_alloc_ex(), brix_transfer_slot_count_op(), brix_transfer_slot_free(), dashboard_http_cleanup(), dashboard_http_client(), dashboard_http_track(), ngx_brix_dashboard_shm_zone, ngx_http_brix_dashboard_module, brix_dashboard_http_track_t::r, brix_dashboard_http_track_t::slot, and brix_dashboard_http_track_t::table.
Referenced by brix_http_serve_file_ranged(), cvmfs_tier_get(), ngx_http_brix_webdav_tpc_handle_copy(), s3_put_body_inner(), s3_put_try_sentinel(), webdav_put_body_inner(), and webdav_tpc_handle_push().
brix_dashboard_http_state()
void brix_dashboard_http_state (ngx_http_request_t * r, uint8_t state)
Definition at line 248 of file noop.c.
References brix_transfer_slot_set_state(), dashboard_http_track(), brix_dashboard_http_track_t::slot, and brix_dashboard_http_track_t::table.
brix_dashboard_http_tpc_remote()
void brix_dashboard_http_tpc_remote (ngx_http_request_t * r, const char * remote_url, int remote_status, int curl_exit)
Definition at line 262 of file noop.c.
References BRIX_DASHBOARD_HOST_LEN, BRIX_DASHBOARD_PATH_LEN, brix_transfer_slot_set_tpc_remote(), dashboard_http_track(), dashboard_redact_url(), brix_dashboard_http_track_t::slot, and brix_dashboard_http_track_t::table.
Referenced by ngx_http_brix_webdav_tpc_handle_copy(), and webdav_tpc_handle_push().
brix_transfer_slot_alloc()
int brix_transfer_slot_alloc (brix_transfer_table_t * t, const u_char sessid[16], const char * client_ip, const char * identity, const char * path, uint8_t direction, uint8_t proto, int64_t now_ms)
Definition at line 62 of file noop.c.
brix_transfer_slot_alloc_ex()
int brix_transfer_slot_alloc_ex (brix_transfer_table_t * t, const u_char sessid[16], const char * client_ip, const char * identity, const char * vo, const char * path, const char * op, uint8_t direction, uint8_t proto, int64_t expected_bytes, int64_t now_ms)
Definition at line 79 of file noop.c.
brix_transfer_slot_count_op()
void brix_transfer_slot_count_op (brix_transfer_table_t * t, int slot_idx, const char * op)
Definition at line 153 of file noop.c.
brix_transfer_slot_free()
void brix_transfer_slot_free (brix_transfer_table_t * t, int slot_idx)
Definition at line 162 of file noop.c.
brix_transfer_slot_free_all_for_session()
void brix_transfer_slot_free_all_for_session (brix_transfer_table_t * t, const u_char sessid[16])
Definition at line 169 of file noop.c.
brix_transfer_slot_set_error()
void brix_transfer_slot_set_error (brix_transfer_table_t * t, int slot_idx, const char * reason, int64_t now_ms)
Definition at line 130 of file noop.c.
brix_transfer_slot_set_state()
void brix_transfer_slot_set_state (brix_transfer_table_t * t, int slot_idx, uint8_t state, int64_t now_ms)
Definition at line 120 of file noop.c.
brix_transfer_slot_set_tpc_remote()
void brix_transfer_slot_set_tpc_remote (brix_transfer_table_t * t, int slot_idx, const char * remote_host, const char * path_hint, int remote_status, int curl_exit)
Definition at line 140 of file noop.c.
brix_transfer_slot_update()
void brix_transfer_slot_update (brix_transfer_table_t * t, int slot_idx, ngx_atomic_int_t nbytes, int64_t now_ms)
Definition at line 100 of file noop.c.
brix_transfer_slot_update_bytes()
void brix_transfer_slot_update_bytes (brix_transfer_table_t * t, int slot_idx, ngx_atomic_int_t nbytes, int64_t now_ms)
Definition at line 110 of file noop.c.
ngx_brix_dashboard_events_shm_init()
ngx_int_t ngx_brix_dashboard_events_shm_init (ngx_shm_zone_t * shm_zone, void * data)
Definition at line 46 of file noop.c.
References brix_dashboard_events_mutex, and brix_shm_table_alloc().
Referenced by brix_configure_dashboard().
ngx_brix_dashboard_history_shm_init()
ngx_int_t ngx_brix_dashboard_history_shm_init (ngx_shm_zone_t * shm_zone, void * data)
Definition at line 54 of file noop.c.
References brix_dashboard_history_mutex, and brix_shm_table_alloc().
Referenced by brix_configure_dashboard().
ngx_brix_dashboard_shm_init()
ngx_int_t ngx_brix_dashboard_shm_init (ngx_shm_zone_t * shm_zone, void * data)
Definition at line 38 of file noop.c.
Variable Documentation
ngx_brix_dashboard_events_shm_zone
ngx_shm_zone_t* ngx_brix_dashboard_events_shm_zone
Definition at line 27 of file noop.c.
ngx_brix_dashboard_history_shm_zone
ngx_shm_zone_t* ngx_brix_dashboard_history_shm_zone
Definition at line 28 of file noop.c.
ngx_brix_dashboard_shm_zone
ngx_shm_zone_t* ngx_brix_dashboard_shm_zone
Definition at line 26 of file noop.c.