nginx-xrootd: src/observability/metrics/metrics.h File Reference
metrics.h File Reference
#include <limits.h>
#include <stdint.h>
#include <ngx_core.h>
#include "core/types/fs_list.h"
#include "unified.h"
#include "metrics_webdav.h"
#include "metrics_s3.h"
#include "metrics_frm.h"
#include "metrics_cvmfs.h"
#include "metrics_proxy.h"
#include "metrics_macros.h"
Data Structures
struct ngx_brix_srv_metrics_t
struct ngx_brix_vo_slot_t
struct ngx_brix_vo_global_t
struct ngx_brix_user_slot_t
struct ngx_brix_user_global_t
struct ngx_brix_unified_metrics_t
struct ngx_brix_metrics_t
Macros
#define BRIX_METRICS_MAX_SERVERS 16
#define BRIX_OP_LOGIN 0
#define BRIX_OP_AUTH 1
#define BRIX_OP_STAT 2
#define BRIX_OP_OPEN_RD 3
#define BRIX_OP_OPEN_WR 4
#define BRIX_OP_READ 5
#define BRIX_OP_WRITE 6
#define BRIX_OP_SYNC 7
#define BRIX_OP_CLOSE 8
#define BRIX_OP_DIRLIST 9
#define BRIX_OP_MKDIR 10
#define BRIX_OP_RMDIR 11
#define BRIX_OP_RM 12
#define BRIX_OP_MV 13
#define BRIX_OP_CHMOD 14
#define BRIX_OP_TRUNCATE 15
#define BRIX_OP_PING 16
#define BRIX_OP_QUERY_CKSUM 17 /* kXR_query / kXR_QChecksum */
#define BRIX_OP_QUERY_SPACE 17 /* kXR_query / kXR_QSpace */
#define BRIX_OP_READV 18 /* kXR_readv */
#define BRIX_OP_PGREAD 19 /* kXR_pgread */
#define BRIX_OP_WRITEV 20 /* kXR_writev */
#define BRIX_OP_LOCATE 21 /* kXR_locate */
#define BRIX_OP_STATX 22 /* kXR_statx */
#define BRIX_OP_FATTR 23 /* kXR_fattr */
#define BRIX_OP_QUERY_STATS 24 /* kXR_query / kXR_QStats */
#define BRIX_OP_QUERY_XATTR 25 /* kXR_query / kXR_Qxattr */
#define BRIX_OP_QUERY_FINFO 26 /* kXR_query / kXR_QFinfo */
#define BRIX_OP_QUERY_FSINFO 27 /* kXR_query / kXR_QFSinfo */
#define BRIX_OP_SET 28 /* kXR_set */
#define BRIX_OP_QUERY_VISA 29 /* kXR_query / kXR_Qvisa */
#define BRIX_OP_QUERY_OPAQUE 30 /* kXR_query / kXR_Qopaque */
#define BRIX_OP_QUERY_OPAQUF 31 /* kXR_query / kXR_Qopaquf */
#define BRIX_OP_QUERY_OPAQUG 32 /* kXR_query / kXR_Qopaqug */
#define BRIX_OP_QUERY_CKSCAN 33 /* kXR_query / kXR_Qckscan */
#define BRIX_OP_CLONE 34 /* kXR_clone */
#define BRIX_OP_CHKPOINT 35 /* kXR_chkpoint */
#define BRIX_NOPS 37
#define BRIX_METRIC_CACHELINE 64
#define BRIX_METRIC_ALIGNED __attribute__((aligned(BRIX_METRIC_CACHELINE)))
#define BRIX_VO_MAX_TRACKED 32
#define BRIX_VO_NAME_LEN 16
#define BRIX_USERS_MAX_TRACKED 1024
Enumerations
enum brix_cache_reap_reason_t { BRIX_CACHE_REAP_ABANDONED = 0 , BRIX_CACHE_REAP_INCOMPLETE , BRIX_CACHE_REAP_COMPLETED , BRIX_CACHE_REAP_REASON_COUNT }
Functions
void brix_config_version_publish (ngx_cycle_t *cycle)
ngx_int_t brix_track_vo_activity (ngx_brix_metrics_t *shm, const char *vo_name, size_t bytes_tx, size_t bytes_rx)
ngx_int_t brix_track_unique_user (ngx_brix_metrics_t *shm, const char *identity, size_t identity_len)
Variables
ngx_shm_zone_t * ngx_brix_shm_zone
Macro Definition Documentation
BRIX_METRIC_ALIGNED
#define BRIX_METRIC_ALIGNED __attribute__((aligned(BRIX_METRIC_CACHELINE)))
Definition at line 79 of file metrics.h.
BRIX_METRIC_CACHELINE
#define BRIX_METRIC_CACHELINE 64
Definition at line 78 of file metrics.h.
BRIX_METRICS_MAX_SERVERS
#define BRIX_METRICS_MAX_SERVERS 16
Definition at line 21 of file metrics.h.
BRIX_NOPS
#define BRIX_NOPS 37
Definition at line 69 of file metrics.h.
BRIX_OP_AUTH
#define BRIX_OP_AUTH 1
Definition at line 32 of file metrics.h.
BRIX_OP_CHKPOINT
#define BRIX_OP_CHKPOINT 35 /* kXR_chkpoint */
Definition at line 67 of file metrics.h.
BRIX_OP_CHMOD
#define BRIX_OP_CHMOD 14
Definition at line 45 of file metrics.h.
BRIX_OP_CLONE
#define BRIX_OP_CLONE 34 /* kXR_clone */
Definition at line 66 of file metrics.h.
BRIX_OP_CLOSE
#define BRIX_OP_CLOSE 8
Definition at line 39 of file metrics.h.
BRIX_OP_DIRLIST
#define BRIX_OP_DIRLIST 9
Definition at line 40 of file metrics.h.
BRIX_OP_FATTR
#define BRIX_OP_FATTR 23 /* kXR_fattr */
Definition at line 55 of file metrics.h.
BRIX_OP_LOCATE
#define BRIX_OP_LOCATE 21 /* kXR_locate */
Definition at line 53 of file metrics.h.
BRIX_OP_LOGIN
#define BRIX_OP_LOGIN 0
Definition at line 31 of file metrics.h.
BRIX_OP_MKDIR
#define BRIX_OP_MKDIR 10
Definition at line 41 of file metrics.h.
BRIX_OP_MV
#define BRIX_OP_MV 13
Definition at line 44 of file metrics.h.
BRIX_OP_OPEN_RD
#define BRIX_OP_OPEN_RD 3
Definition at line 34 of file metrics.h.
BRIX_OP_OPEN_WR
#define BRIX_OP_OPEN_WR 4
Definition at line 35 of file metrics.h.
BRIX_OP_PGREAD
#define BRIX_OP_PGREAD 19 /* kXR_pgread */
Definition at line 51 of file metrics.h.
BRIX_OP_PING
#define BRIX_OP_PING 16
Definition at line 47 of file metrics.h.
BRIX_OP_QUERY_CKSCAN
#define BRIX_OP_QUERY_CKSCAN 33 /* kXR_query / kXR_Qckscan */
Definition at line 65 of file metrics.h.
BRIX_OP_QUERY_CKSUM
#define BRIX_OP_QUERY_CKSUM 17 /* kXR_query / kXR_QChecksum */
Definition at line 48 of file metrics.h.
BRIX_OP_QUERY_FINFO
#define BRIX_OP_QUERY_FINFO 26 /* kXR_query / kXR_QFinfo */
Definition at line 58 of file metrics.h.
BRIX_OP_QUERY_FSINFO
#define BRIX_OP_QUERY_FSINFO 27 /* kXR_query / kXR_QFSinfo */
Definition at line 59 of file metrics.h.
BRIX_OP_QUERY_OPAQUE
#define BRIX_OP_QUERY_OPAQUE 30 /* kXR_query / kXR_Qopaque */
Definition at line 62 of file metrics.h.
BRIX_OP_QUERY_OPAQUF
#define BRIX_OP_QUERY_OPAQUF 31 /* kXR_query / kXR_Qopaquf */
Definition at line 63 of file metrics.h.
BRIX_OP_QUERY_OPAQUG
#define BRIX_OP_QUERY_OPAQUG 32 /* kXR_query / kXR_Qopaqug */
Definition at line 64 of file metrics.h.
BRIX_OP_QUERY_SPACE
#define BRIX_OP_QUERY_SPACE 17 /* kXR_query / kXR_QSpace */
Definition at line 49 of file metrics.h.
BRIX_OP_QUERY_STATS
#define BRIX_OP_QUERY_STATS 24 /* kXR_query / kXR_QStats */
Definition at line 56 of file metrics.h.
BRIX_OP_QUERY_VISA
#define BRIX_OP_QUERY_VISA 29 /* kXR_query / kXR_Qvisa */
Definition at line 61 of file metrics.h.
BRIX_OP_QUERY_XATTR
#define BRIX_OP_QUERY_XATTR 25 /* kXR_query / kXR_Qxattr */
Definition at line 57 of file metrics.h.
BRIX_OP_READ
#define BRIX_OP_READ 5
Definition at line 36 of file metrics.h.
BRIX_OP_READV
#define BRIX_OP_READV 18 /* kXR_readv */
Definition at line 50 of file metrics.h.
BRIX_OP_RM
#define BRIX_OP_RM 12
Definition at line 43 of file metrics.h.
BRIX_OP_RMDIR
#define BRIX_OP_RMDIR 11
Definition at line 42 of file metrics.h.
BRIX_OP_SET
#define BRIX_OP_SET 28 /* kXR_set */
Definition at line 60 of file metrics.h.
BRIX_OP_STAT
#define BRIX_OP_STAT 2
Definition at line 33 of file metrics.h.
BRIX_OP_STATX
#define BRIX_OP_STATX 22 /* kXR_statx */
Definition at line 54 of file metrics.h.
BRIX_OP_SYNC
#define BRIX_OP_SYNC 7
Definition at line 38 of file metrics.h.
BRIX_OP_TRUNCATE
#define BRIX_OP_TRUNCATE 15
Definition at line 46 of file metrics.h.
BRIX_OP_WRITE
#define BRIX_OP_WRITE 6
Definition at line 37 of file metrics.h.
BRIX_OP_WRITEV
#define BRIX_OP_WRITEV 20 /* kXR_writev */
Definition at line 52 of file metrics.h.
BRIX_USERS_MAX_TRACKED
#define BRIX_USERS_MAX_TRACKED 1024
Definition at line 287 of file metrics.h.
BRIX_VO_MAX_TRACKED
#define BRIX_VO_MAX_TRACKED 32
Definition at line 270 of file metrics.h.
BRIX_VO_NAME_LEN
#define BRIX_VO_NAME_LEN 16
Definition at line 271 of file metrics.h.
Enumeration Type Documentation
brix_cache_reap_reason_t
enum brix_cache_reap_reason_t
Enumerator
BRIX_CACHE_REAP_ABANDONED
BRIX_CACHE_REAP_INCOMPLETE
BRIX_CACHE_REAP_COMPLETED
BRIX_CACHE_REAP_REASON_COUNT
Definition at line 126 of file metrics.h.
Function Documentation
brix_config_version_publish()
void brix_config_version_publish (ngx_cycle_t * cycle)
Definition at line 145 of file config.c.
References ngx_brix_metrics_t::config_generation, ngx_brix_metrics_t::config_hash, fnv1a64_file(), and ngx_brix_shm_zone.
Referenced by imp_init_module_gate().
brix_track_unique_user()
ngx_int_t brix_track_unique_user (ngx_brix_metrics_t * shm, const char * identity, size_t identity_len)
Definition at line 108 of file tracking.c.
References BRIX_ATOMIC_DEC, BRIX_ATOMIC_INC, brix_fnv1a_hash(), BRIX_USERS_MAX_TRACKED, ngx_brix_user_global_t::evictions_total, ngx_brix_user_slot_t::first_seen, ngx_brix_user_slot_t::id_hash, ngx_brix_user_slot_t::sessions_total, ngx_brix_user_global_t::slots, ngx_brix_user_global_t::total_unique, ngx_brix_user_global_t::unique_count, and ngx_brix_metrics_t::user_tracking.
Referenced by brix_gsi_complete_auth(), brix_unix_track_identity(), sss_track_metrics(), and tokenauth_bind_session().
brix_track_vo_activity()
ngx_int_t brix_track_vo_activity (ngx_brix_metrics_t * shm, const char * vo_name, size_t bytes_tx, size_t bytes_rx)
Definition at line 40 of file tracking.c.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, BRIX_VO_MAX_TRACKED, BRIX_VO_NAME_LEN, ngx_brix_vo_slot_t::bytes_rx_total, ngx_brix_vo_slot_t::bytes_tx_total, ngx_brix_vo_slot_t::name, ngx_memcpy, ngx_brix_vo_global_t::overflow_total, ngx_brix_vo_slot_t::requests_total, ngx_brix_vo_global_t::slot_count, ngx_brix_vo_global_t::slots, and ngx_brix_metrics_t::vo_global.
Referenced by brix_gsi_complete_auth(), brix_unix_track_identity(), sss_track_metrics(), and tokenauth_bind_session().
Variable Documentation
ngx_brix_shm_zone
ngx_shm_zone_t* ngx_brix_shm_zone extern
Definition at line 11 of file handler.c.
Referenced by brix_config_version_publish(), brix_metrics_ensure_zone(), brix_metrics_shared(), conn_metrics_row(), dashboard_build_storage_io(), dashboard_collect_totals(), dashboard_fill_cache(), dashboard_fill_cvmfs(), dashboard_history_sum_totals(), health_build_json(), ngx_http_brix_metrics_handler(), and reap_metrics_slot().