nginx-xrootd: src/observability/dashboard/events.c File Reference
events.c File Reference
#include "dashboard.h"
#include "core/compat/shm_slots.h"
#include <ngx_shmtx.h>
#include <string.h>
Functions
static brix_dashboard_event_table_t * dashboard_events_table (void)
static void dashboard_event_copy (char *dst, size_t dstsz, const char *src, ngx_flag_t stop_at_query)
ngx_int_t ngx_brix_dashboard_events_shm_init (ngx_shm_zone_t *shm_zone, void *data)
void brix_dashboard_event_add (uint8_t class_id, uint8_t proto, uint16_t status, const char *message, const char *path_hint)
ngx_uint_t brix_dashboard_events_snapshot (brix_dashboard_event_t *out, ngx_uint_t max_events)
Variables
static ngx_shmtx_t brix_dashboard_events_mutex
Function Documentation
brix_dashboard_event_add()
void brix_dashboard_event_add (uint8_t class_id, uint8_t proto, uint16_t status, const char * message, const char * path_hint)
Definition at line 109 of file events.c.
brix_dashboard_events_snapshot()
ngx_uint_t brix_dashboard_events_snapshot (brix_dashboard_event_t * out, ngx_uint_t max_events)
Definition at line 141 of file events.c.
dashboard_event_copy()
static void dashboard_event_copy (char * dst, size_t dstsz, const char * src, ngx_flag_t stop_at_query) static
Definition at line 49 of file events.c.
References c.
Referenced by brix_dashboard_event_add().
dashboard_events_table()
static brix_dashboard_event_table_t * dashboard_events_table (void) static
Definition at line 35 of file events.c.
References ngx_brix_dashboard_events_shm_zone.
Referenced by brix_dashboard_event_add(), and brix_dashboard_events_snapshot().
ngx_brix_dashboard_events_shm_init()
ngx_int_t ngx_brix_dashboard_events_shm_init (ngx_shm_zone_t * shm_zone, void * data)
Definition at line 82 of file events.c.
Variable Documentation
brix_dashboard_events_mutex
ngx_shmtx_t brix_dashboard_events_mutex static
Definition at line 32 of file events.c.
Referenced by brix_dashboard_event_add(), brix_dashboard_events_snapshot(), and ngx_brix_dashboard_events_shm_init().