nginx-xrootd: src/observability/metrics/unified.c File Reference
unified.c File Reference
#include "metrics_internal.h"
#include "core/types/identity.h"
#include <errno.h>
#include <string.h>
Macros
#define X(ID, metric_label, dash_name, http_plane) metric_label,
Functions
const char * brix_metric_proto_name (brix_proto_t proto)
const char * brix_metric_op_name (brix_metric_op_t op)
const char * brix_metric_err_name (brix_err_class_t err)
ngx_uint_t brix_metric_auth_slot (ngx_uint_t auth_method)
const char * brix_metric_auth_method_name (ngx_uint_t auth_method)
brix_err_class_t brix_metric_err_from_errno (int sys_errno)
brix_err_class_t brix_metric_err_from_http_status (ngx_uint_t status)
void brix_metric_op_done (brix_proto_t proto, brix_metric_op_t op, size_t bytes, ngx_msec_t latency_usec, brix_err_class_t err)
void brix_metric_backend_bytes (const char *backend_name, brix_metric_op_t op, size_t bytes)
void brix_metric_cache_result (brix_proto_t proto, unsigned int hit, size_t bytes_evicted)
void brix_metric_cache_usage_ratio (ngx_uint_t occupancy_ppm)
void brix_metric_cache_watermark_purge (ngx_uint_t files, uint64_t bytes)
void brix_metric_wt_stage_usage_ratio (ngx_uint_t occupancy_ppm)
void brix_metric_wt_stage_throttled (int reject)
void brix_metric_auth (brix_proto_t proto, ngx_uint_t auth_method, unsigned int success)
void brix_metric_tpc (brix_proto_t proto, unsigned int is_push, size_t bytes, brix_err_class_t err)
static unsigned long long brix_metric_value (ngx_atomic_t *counter)
static unsigned long long brix_unified_legacy_stream_bytes (ngx_brix_metrics_t *shm, unsigned int is_write)
static unsigned long long brix_unified_legacy_stream_op_slot (ngx_brix_metrics_t *shm, ngx_uint_t slot, unsigned int ok)
static unsigned long long brix_unified_legacy_stream_op (ngx_brix_metrics_t *shm, brix_metric_op_t op, unsigned int ok)
static ngx_uint_t brix_unified_srv_auth_slot (const char *auth)
static unsigned long long brix_unified_legacy_stream_auth (ngx_brix_metrics_t *shm, ngx_uint_t method, ngx_uint_t status)
static unsigned long long brix_unified_legacy_auth (ngx_brix_metrics_t *shm, brix_proto_t proto, ngx_uint_t method, ngx_uint_t status)
void brix_export_unified_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
Variables
static const char * brix_unified_proto_names [BRIX_PROTO_COUNT]
static const char * brix_unified_op_names [BRIX_METRIC_OP_COUNT]
static const char * brix_unified_err_names [BRIX_ERR_COUNT]
static const char * brix_unified_auth_names [9]
static const char * brix_unified_tpc_direction_names [2]
static const ngx_msec_t brix_latency_bounds [9 - 1]
Macro Definition Documentation
X
#define X (ID, metric_label, dash_name, http_plane) metric_label,
Function Documentation
brix_export_unified_metrics()
void brix_export_unified_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 604 of file unified.c.
References ngx_brix_unified_metrics_t::auth_total, BRIX_ERR_COUNT, BRIX_ERR_NONE, BRIX_ERR_OTHER, BRIX_IO_LATENCY_BUCKETS, brix_latency_bounds, BRIX_METRIC_AUTH_COUNT, BRIX_METRIC_AUTH_OK, BRIX_METRIC_AUTH_STATUS_COUNT, brix_metric_err_name(), BRIX_METRIC_OP_COUNT, brix_metric_op_name(), brix_metric_proto_name(), BRIX_METRIC_TPC_DIRECTION_COUNT, brix_metric_value(), BRIX_PROTO_COUNT, BRIX_PROTO_ROOT, BRIX_PROTO_S3, BRIX_PROTO_WEBDAV, brix_unified_auth_names, brix_unified_legacy_auth(), brix_unified_legacy_stream_bytes(), brix_unified_legacy_stream_op(), brix_unified_tpc_direction_names, ngx_brix_s3_metrics_t::bytes_rx_total, ngx_brix_webdav_metrics_t::bytes_rx_total, ngx_brix_s3_metrics_t::bytes_tx_total, ngx_brix_webdav_metrics_t::bytes_tx_total, ngx_brix_unified_metrics_t::cache_bytes_evicted, ngx_brix_unified_metrics_t::cache_hits, ngx_brix_unified_metrics_t::cache_misses, ngx_brix_unified_metrics_t::cache_usage_ratio_ppm, ngx_brix_unified_metrics_t::cache_watermark_evicted_bytes, ngx_brix_unified_metrics_t::cache_watermark_evicted_files, ngx_brix_unified_metrics_t::cache_watermark_purges, ngx_brix_unified_metrics_t::io_bytes_read, ngx_brix_unified_metrics_t::io_bytes_written, ngx_brix_unified_metrics_t::io_latency_bucket, ngx_brix_unified_metrics_t::io_latency_count, ngx_brix_unified_metrics_t::io_latency_sum_usec, ngx_brix_unified_metrics_t::io_ops_total, mw_printf(), ngx_brix_metrics_t::s3, ngx_brix_unified_metrics_t::tpc_bytes, ngx_brix_unified_metrics_t::tpc_transfers, ngx_brix_metrics_t::unified, ngx_brix_metrics_t::webdav, ngx_brix_unified_metrics_t::wt_stage_throttled_reject, ngx_brix_unified_metrics_t::wt_stage_throttled_wait, and ngx_brix_unified_metrics_t::wt_stage_usage_ratio_ppm.
Referenced by brix_export_prometheus_metrics().
brix_metric_auth()
void brix_metric_auth (brix_proto_t proto, ngx_uint_t auth_method, unsigned int success)
Definition at line 396 of file unified.c.
References ngx_brix_unified_metrics_t::auth_total, BRIX_ATOMIC_INC, BRIX_METRIC_AUTH_FAIL, BRIX_METRIC_AUTH_OK, brix_metric_auth_slot(), brix_metrics_shared(), BRIX_PROTO_COUNT, and ngx_brix_metrics_t::unified.
Referenced by brix_handle_host_auth(), brix_handle_krb5_auth(), brix_handle_pwd_auth(), brix_handle_unix_auth(), ngx_http_brix_webdav_access_handler(), pwd_round1(), pwd_round2(), s3_record_auth_result(), and s3_verify_bearer().
brix_metric_auth_method_name()
const char * brix_metric_auth_method_name (ngx_uint_t auth_method)
Definition at line 150 of file unified.c.
References brix_metric_auth_slot(), and brix_unified_auth_names.
Referenced by brix_access_log_emit().
brix_metric_auth_slot()
ngx_uint_t brix_metric_auth_slot (ngx_uint_t auth_method)
Definition at line 119 of file unified.c.
References BRIX_AUTHN_GSI, BRIX_AUTHN_HOST, BRIX_AUTHN_KRB5, BRIX_AUTHN_PWD, BRIX_AUTHN_S3KEY, BRIX_AUTHN_SSS, BRIX_AUTHN_TOKEN, BRIX_AUTHN_UNIX, BRIX_METRIC_AUTH_GSI, BRIX_METRIC_AUTH_HOST, BRIX_METRIC_AUTH_KRB5, BRIX_METRIC_AUTH_NONE, BRIX_METRIC_AUTH_PWD, BRIX_METRIC_AUTH_S3KEY, BRIX_METRIC_AUTH_SSS, BRIX_METRIC_AUTH_TOKEN, and BRIX_METRIC_AUTH_UNIX.
Referenced by brix_metric_auth(), and brix_metric_auth_method_name().
brix_metric_backend_bytes()
void brix_metric_backend_bytes (const char * backend_name, brix_metric_op_t op, size_t bytes)
Definition at line 266 of file unified.c.
References BRIX_ATOMIC_ADD, brix_fs_id_from_name(), BRIX_METRIC_OP_READ, BRIX_METRIC_OP_WRITE, brix_metrics_shared(), ngx_brix_unified_metrics_t::io_bytes_read_backend, ngx_brix_unified_metrics_t::io_bytes_written_backend, and ngx_brix_metrics_t::unified.
Referenced by brix_handle_pgread(), brix_handle_read(), brix_http_serve_file_ranged(), brix_read_serve_sendfile(), brix_vfs_io_account(), and brix_vfs_observe_ctx_op().
brix_metric_cache_result()
void brix_metric_cache_result (brix_proto_t proto, unsigned int hit, size_t bytes_evicted)
Definition at line 301 of file unified.c.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, brix_metrics_shared(), BRIX_PROTO_COUNT, ngx_brix_unified_metrics_t::cache_bytes_evicted, ngx_brix_unified_metrics_t::cache_hits, ngx_brix_unified_metrics_t::cache_misses, and ngx_brix_metrics_t::unified.
Referenced by brix_vfs_open(), and cvmfs_finalize_observe().
brix_metric_cache_usage_ratio()
void brix_metric_cache_usage_ratio (ngx_uint_t occupancy_ppm)
Definition at line 330 of file unified.c.
References brix_metrics_shared(), ngx_brix_unified_metrics_t::cache_usage_ratio_ppm, and ngx_brix_metrics_t::unified.
Referenced by brix_cache_watermark_purge().
brix_metric_cache_watermark_purge()
void brix_metric_cache_watermark_purge (ngx_uint_t files, uint64_t bytes)
Definition at line 346 of file unified.c.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, brix_metrics_shared(), ngx_brix_unified_metrics_t::cache_watermark_evicted_bytes, ngx_brix_unified_metrics_t::cache_watermark_evicted_files, ngx_brix_unified_metrics_t::cache_watermark_purges, and ngx_brix_metrics_t::unified.
Referenced by brix_cache_watermark_purge().
brix_metric_err_from_errno()
brix_err_class_t brix_metric_err_from_errno (int sys_errno)
Definition at line 161 of file unified.c.
References BRIX_ERR_FORBIDDEN, BRIX_ERR_IO, BRIX_ERR_NONE, BRIX_ERR_NOT_FOUND, and BRIX_ERR_OTHER.
Referenced by brix_vfs_observe_ctx_op().
brix_metric_err_from_http_status()
brix_err_class_t brix_metric_err_from_http_status (ngx_uint_t status)
Definition at line 187 of file unified.c.
References BRIX_ERR_FORBIDDEN, BRIX_ERR_IO, BRIX_ERR_NONE, BRIX_ERR_NOT_FOUND, and BRIX_ERR_OTHER.
Referenced by s3_metrics_response_status(), and webdav_metrics_response().
brix_metric_err_name()
const char * brix_metric_err_name (brix_err_class_t err)
Definition at line 108 of file unified.c.
References BRIX_ERR_COUNT, and brix_unified_err_names.
Referenced by brix_access_log_emit(), and brix_export_unified_metrics().
brix_metric_op_done()
void brix_metric_op_done (brix_proto_t proto, brix_metric_op_t op, size_t bytes, ngx_msec_t latency_usec, brix_err_class_t err)
Definition at line 212 of file unified.c.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, BRIX_ERR_COUNT, BRIX_IO_LATENCY_BUCKETS, brix_latency_bounds, BRIX_METRIC_OP_COUNT, BRIX_METRIC_OP_READ, BRIX_METRIC_OP_WRITE, brix_metrics_shared(), BRIX_PROTO_COUNT, ngx_brix_unified_metrics_t::io_bytes_read, ngx_brix_unified_metrics_t::io_bytes_written, ngx_brix_unified_metrics_t::io_latency_bucket, ngx_brix_unified_metrics_t::io_latency_count, ngx_brix_unified_metrics_t::io_latency_sum_usec, ngx_brix_unified_metrics_t::io_ops_total, and ngx_brix_metrics_t::unified.
Referenced by brix_vfs_observe_ctx_op(), s3_metrics_response_status(), and webdav_metrics_response().
brix_metric_op_name()
const char * brix_metric_op_name (brix_metric_op_t op)
Definition at line 101 of file unified.c.
References BRIX_METRIC_OP_COUNT, and brix_unified_op_names.
Referenced by brix_access_log_emit(), and brix_export_unified_metrics().
brix_metric_proto_name()
const char * brix_metric_proto_name (brix_proto_t proto)
Definition at line 94 of file unified.c.
References BRIX_PROTO_COUNT, and brix_unified_proto_names.
Referenced by brix_access_log_emit(), and brix_export_unified_metrics().
brix_metric_tpc()
void brix_metric_tpc (brix_proto_t proto, unsigned int is_push, size_t bytes, brix_err_class_t err)
Definition at line 423 of file unified.c.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, BRIX_ERR_COUNT, BRIX_ERR_NONE, BRIX_METRIC_TPC_PULL, BRIX_METRIC_TPC_PUSH, brix_metrics_shared(), BRIX_PROTO_COUNT, ngx_brix_unified_metrics_t::tpc_bytes, ngx_brix_unified_metrics_t::tpc_transfers, and ngx_brix_metrics_t::unified.
Referenced by brix_tpc_metric_transfer().
brix_metric_value()
static unsigned long long brix_metric_value (ngx_atomic_t * counter) static
Definition at line 447 of file unified.c.
Referenced by brix_export_unified_metrics(), brix_unified_legacy_stream_auth(), brix_unified_legacy_stream_bytes(), and brix_unified_legacy_stream_op_slot().
brix_metric_wt_stage_throttled()
void brix_metric_wt_stage_throttled (int reject)
Definition at line 377 of file unified.c.
References BRIX_ATOMIC_INC, brix_metrics_shared(), ngx_brix_metrics_t::unified, ngx_brix_unified_metrics_t::wt_stage_throttled_reject, and ngx_brix_unified_metrics_t::wt_stage_throttled_wait.
Referenced by brix_open_stage_backpressure().
brix_metric_wt_stage_usage_ratio()
void brix_metric_wt_stage_usage_ratio (ngx_uint_t occupancy_ppm)
Definition at line 363 of file unified.c.
References brix_metrics_shared(), ngx_brix_metrics_t::unified, and ngx_brix_unified_metrics_t::wt_stage_usage_ratio_ppm.
Referenced by brix_wt_stage_admit().
brix_unified_legacy_auth()
static unsigned long long brix_unified_legacy_auth (ngx_brix_metrics_t * shm, brix_proto_t proto, ngx_uint_t method, ngx_uint_t status) static
Definition at line 584 of file unified.c.
References BRIX_PROTO_ROOT, and brix_unified_legacy_stream_auth().
Referenced by brix_export_unified_metrics().
brix_unified_legacy_stream_auth()
static unsigned long long brix_unified_legacy_stream_auth (ngx_brix_metrics_t * shm, ngx_uint_t method, ngx_uint_t status) static
Definition at line 562 of file unified.c.
References ngx_brix_srv_metrics_t::auth, BRIX_METRIC_AUTH_OK, brix_metric_value(), BRIX_METRICS_MAX_SERVERS, BRIX_OP_AUTH, brix_unified_srv_auth_slot(), ngx_brix_srv_metrics_t::in_use, ngx_brix_srv_metrics_t::op_err, ngx_brix_srv_metrics_t::op_ok, and ngx_brix_metrics_t::servers.
Referenced by brix_unified_legacy_auth().
brix_unified_legacy_stream_bytes()
static unsigned long long brix_unified_legacy_stream_bytes (ngx_brix_metrics_t * shm, unsigned int is_write) static
Definition at line 461 of file unified.c.
References brix_metric_value(), BRIX_METRICS_MAX_SERVERS, ngx_brix_srv_metrics_t::bytes_rx_total, ngx_brix_srv_metrics_t::bytes_tx_total, ngx_brix_srv_metrics_t::in_use, and ngx_brix_metrics_t::servers.
Referenced by brix_export_unified_metrics().
brix_unified_legacy_stream_op()
static unsigned long long brix_unified_legacy_stream_op (ngx_brix_metrics_t * shm, brix_metric_op_t op, unsigned int ok) static
Definition at line 508 of file unified.c.
References BRIX_METRIC_OP_DELETE, BRIX_METRIC_OP_DIRLIST, BRIX_METRIC_OP_MKDIR, BRIX_METRIC_OP_READ, BRIX_METRIC_OP_RENAME, BRIX_METRIC_OP_STAT, BRIX_METRIC_OP_WRITE, BRIX_OP_DIRLIST, BRIX_OP_MKDIR, BRIX_OP_MV, BRIX_OP_PGREAD, BRIX_OP_READ, BRIX_OP_READV, BRIX_OP_RM, BRIX_OP_RMDIR, BRIX_OP_STAT, BRIX_OP_STATX, BRIX_OP_WRITE, BRIX_OP_WRITEV, and brix_unified_legacy_stream_op_slot().
Referenced by brix_export_unified_metrics().
brix_unified_legacy_stream_op_slot()
static unsigned long long brix_unified_legacy_stream_op_slot (ngx_brix_metrics_t * shm, ngx_uint_t slot, unsigned int ok) static
Definition at line 483 of file unified.c.
References brix_metric_value(), BRIX_METRICS_MAX_SERVERS, BRIX_NOPS, ngx_brix_srv_metrics_t::in_use, ngx_brix_srv_metrics_t::op_err, ngx_brix_srv_metrics_t::op_ok, and ngx_brix_metrics_t::servers.
Referenced by brix_unified_legacy_stream_op().
brix_unified_srv_auth_slot()
static ngx_uint_t brix_unified_srv_auth_slot (const char * auth) static
Definition at line 537 of file unified.c.
References BRIX_METRIC_AUTH_GSI, BRIX_METRIC_AUTH_KRB5, BRIX_METRIC_AUTH_NONE, BRIX_METRIC_AUTH_SSS, BRIX_METRIC_AUTH_TOKEN, and BRIX_METRIC_AUTH_UNIX.
Referenced by brix_unified_legacy_stream_auth().
Variable Documentation
brix_latency_bounds
const ngx_msec_t brix_latency_bounds[9 - 1] static
Initial value:
= {
    1000,
    5000,
    10000,
    50000,
    100000,
    500000,
    1000000,
    5000000,
}
Definition at line 82 of file unified.c.
Referenced by brix_export_unified_metrics(), and brix_metric_op_done().
brix_unified_auth_names
const char* brix_unified_auth_names[9] static
Initial value:
= {
    "none",
    "gsi",
    "token",
    "sss",
    "s3key",
    "unix",
    "krb5",
    "host",
    "pwd",
}
Definition at line 63 of file unified.c.
Referenced by brix_export_unified_metrics(), and brix_metric_auth_method_name().
brix_unified_err_names
const char* brix_unified_err_names[BRIX_ERR_COUNT] static
Initial value:
= {
    "ok",
    "not_found",
    "forbidden",
    "io_error",
    "other",
}
Definition at line 55 of file unified.c.
Referenced by brix_metric_err_name().
brix_unified_op_names
const char* brix_unified_op_names[BRIX_METRIC_OP_COUNT] static
Initial value:
= {
    "read",
    "write",
    "stat",
    "delete",
    "mkdir",
    "rename",
    "dirlist",
    "tpc",
    "xattr",
    "copy",
}
Definition at line 42 of file unified.c.
Referenced by brix_metric_op_name().
brix_unified_proto_names
const char* brix_unified_proto_names[BRIX_PROTO_COUNT] static
Initial value:
= {
#define X(ID, metric_label, dash_name, http_plane)
      "stream" ,      "webdav" ,      "s3" ,      "cvmfs" ,
}
Definition at line 36 of file unified.c.
Referenced by brix_metric_proto_name().
brix_unified_tpc_direction_names
const char* brix_unified_tpc_direction_names[ 2] static
Initial value:
=
{
    "pull",
    "push",
}
Definition at line 75 of file unified.c.
Referenced by brix_export_unified_metrics().