nginx-xrootd: src/observability/metrics/module.c File Reference
module.c File Reference
#include "metrics_internal.h"
Functions
static void * ngx_http_brix_metrics_create_loc_conf (ngx_conf_t *cf)
static char * ngx_http_brix_metrics_merge_loc_conf (ngx_conf_t *cf, void *parent, void *child)
static char * ngx_http_brix_metrics_set (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static char * ngx_http_brix_health_set (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Variables
static ngx_command_t ngx_http_brix_metrics_commands []
static ngx_http_module_t ngx_http_brix_metrics_module_ctx
ngx_module_t ngx_http_brix_metrics_module
Function Documentation
ngx_http_brix_health_set()
static char * ngx_http_brix_health_set (ngx_conf_t * cf, ngx_command_t * cmd, void * conf) static
Definition at line 86 of file module.c.
References ngx_http_brix_health_handler().
ngx_http_brix_metrics_create_loc_conf()
static void * ngx_http_brix_metrics_create_loc_conf (ngx_conf_t * cf) static
Definition at line 22 of file module.c.
References ngx_http_brix_metrics_loc_conf_t::enable, ngx_http_brix_metrics_loc_conf_t::health, and ngx_pcalloc().
ngx_http_brix_metrics_merge_loc_conf()
static char * ngx_http_brix_metrics_merge_loc_conf (ngx_conf_t * cf, void * parent, void * child) static
Definition at line 42 of file module.c.
References ngx_http_brix_metrics_loc_conf_t::enable, and ngx_http_brix_metrics_loc_conf_t::health.
ngx_http_brix_metrics_set()
static char * ngx_http_brix_metrics_set (ngx_conf_t * cf, ngx_command_t * cmd, void * conf) static
Definition at line 62 of file module.c.
References ngx_http_brix_metrics_handler().
Variable Documentation
ngx_http_brix_metrics_commands
ngx_command_t ngx_http_brix_metrics_commands[] static
Initial value:
= {
    { ngx_string("brix_metrics"),
      NGX_HTTP_LOC_CONF | NGX_CONF_FLAG,
      ngx_http_brix_metrics_set,
      NGX_HTTP_LOC_CONF_OFFSET,
      offsetof(ngx_http_brix_metrics_loc_conf_t, enable),
      NULL },
    { ngx_string("brix_health"),
      NGX_HTTP_LOC_CONF | NGX_CONF_FLAG,
      ngx_http_brix_health_set,
      NGX_HTTP_LOC_CONF_OFFSET,
      offsetof(ngx_http_brix_metrics_loc_conf_t, health),
      NULL },
    ngx_null_command
}
Definition at line 107 of file module.c.
ngx_http_brix_metrics_module
ngx_module_t ngx_http_brix_metrics_module
Initial value:
= {
    NGX_MODULE_V1,
    &ngx_http_brix_metrics_module_ctx,
    ngx_http_brix_metrics_commands,
    NGX_HTTP_MODULE,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NGX_MODULE_V1_PADDING
}
Definition at line 153 of file module.c.
Referenced by ngx_http_brix_health_handler(), and ngx_http_brix_metrics_handler().
ngx_http_brix_metrics_module_ctx
ngx_http_module_t ngx_http_brix_metrics_module_ctx static
Initial value:
= {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    ngx_http_brix_metrics_create_loc_conf,
    ngx_http_brix_metrics_merge_loc_conf
}
Definition at line 134 of file module.c.