nginx-xrootd: src/observability/dashboard/module.c File Reference
module.c File Reference
#include "dashboard_http.h"
#include "api_admin.h"
#include "core/http/http_headers.h"
#include "core/compat/cstr.h"
#include "core/config/http_common.h"
#include "module_internal.h"
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct dashboard_canon_root_t
Functions
static void * ngx_http_brix_dashboard_create_loc_conf (ngx_conf_t *cf)
static char * ngx_http_brix_dashboard_merge_loc_conf (ngx_conf_t *cf, void *parent, void *child)
static char * ngx_http_brix_dashboard_set (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static char * ngx_http_brix_dashboard_set_password (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static char * ngx_http_brix_dashboard_set_session_ttl (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static char * ngx_http_brix_dashboard_set_cookie_path (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static ngx_int_t dashboard_merge_canon_root (ngx_conf_t *cf, const dashboard_canon_root_t *req, char **err)
static ngx_int_t dashboard_cookie_path_valid (ngx_str_t *path)
Variables
static ngx_command_t ngx_http_brix_dashboard_commands []
static ngx_http_module_t ngx_http_brix_dashboard_module_ctx
ngx_module_t ngx_http_brix_dashboard_module
Function Documentation
dashboard_cookie_path_valid()
static ngx_int_t dashboard_cookie_path_valid (ngx_str_t * path) static
Definition at line 297 of file module.c.
Referenced by ngx_http_brix_dashboard_set_cookie_path().
dashboard_merge_canon_root()
static ngx_int_t dashboard_merge_canon_root (ngx_conf_t * cf, const dashboard_canon_root_t * req, char ** err) static
Definition at line 102 of file module.c.
References brix_str_cbuf(), dashboard_canon_root_t::canon, dashboard_canon_root_t::directive, ngx_memcpy, PATH_MAX, dashboard_canon_root_t::prev_canon, dashboard_canon_root_t::root, and dashboard_canon_root_t::too_long_msg.
Referenced by ngx_http_brix_dashboard_merge_loc_conf().
ngx_http_brix_dashboard_create_loc_conf()
static void * ngx_http_brix_dashboard_create_loc_conf (ngx_conf_t * cf) static
Definition at line 52 of file module.c.
References ngx_http_brix_dashboard_loc_conf_t::admin_require_both, ngx_http_brix_dashboard_loc_conf_t::admin_rl_enable, ngx_http_brix_dashboard_loc_conf_t::admin_rl_read_pm, ngx_http_brix_dashboard_loc_conf_t::admin_rl_write_pm, ngx_http_brix_dashboard_loc_conf_t::anonymous, ngx_http_brix_dashboard_loc_conf_t::cluster_stale_after_ms, ngx_http_brix_dashboard_loc_conf_t::enable, ngx_http_brix_dashboard_loc_conf_t::idle_threshold_ms, ngx_pcalloc(), ngx_http_brix_dashboard_loc_conf_t::scan_max_files, ngx_http_brix_dashboard_loc_conf_t::session_ttl, ngx_http_brix_dashboard_loc_conf_t::stalled_threshold_ms, and ngx_http_brix_dashboard_loc_conf_t::vfs_browse.
ngx_http_brix_dashboard_merge_loc_conf()
static char * ngx_http_brix_dashboard_merge_loc_conf (ngx_conf_t * cf, void * parent, void * child) static
Definition at line 127 of file module.c.
References ngx_http_brix_dashboard_loc_conf_t::admin_allow, ngx_http_brix_dashboard_loc_conf_t::admin_require_both, ngx_http_brix_dashboard_loc_conf_t::admin_rl_enable, ngx_http_brix_dashboard_loc_conf_t::admin_rl_read_pm, ngx_http_brix_dashboard_loc_conf_t::admin_rl_write_pm, ngx_http_brix_dashboard_loc_conf_t::admin_secret, ngx_http_brix_dashboard_loc_conf_t::anonymous, brix_admin_rl_finalize(), brix_shared_security_gate(), ngx_http_brix_dashboard_loc_conf_t::browse_root, ngx_http_brix_dashboard_loc_conf_t::browse_root_canon, ngx_http_brix_dashboard_loc_conf_t::cluster_stale_after_ms, ngx_http_brix_common_conf_t::common, ngx_http_brix_dashboard_loc_conf_t::cookie_path, dashboard_merge_canon_root(), ngx_http_brix_dashboard_loc_conf_t::enable, ngx_http_brix_dashboard_loc_conf_t::idle_threshold_ms, ngx_http_brix_common_module, ngx_http_brix_dashboard_loc_conf_t::password, ngx_http_brix_dashboard_loc_conf_t::scan_max_files, ngx_http_brix_dashboard_loc_conf_t::scan_root, ngx_http_brix_dashboard_loc_conf_t::scan_root_canon, ngx_http_brix_dashboard_loc_conf_t::session_ttl, ngx_http_brix_dashboard_loc_conf_t::stalled_threshold_ms, ngx_http_brix_shared_conf_t::strict_security, ngx_http_brix_dashboard_loc_conf_t::users, and ngx_http_brix_dashboard_loc_conf_t::vfs_browse.
ngx_http_brix_dashboard_set()
static char * ngx_http_brix_dashboard_set (ngx_conf_t * cf, ngx_command_t * cmd, void * conf) static
Definition at line 234 of file module.c.
References ngx_http_brix_dashboard_main_handler().
ngx_http_brix_dashboard_set_cookie_path()
static char * ngx_http_brix_dashboard_set_cookie_path (ngx_conf_t * cf, ngx_command_t * cmd, void * conf) static
Definition at line 315 of file module.c.
References ngx_http_brix_dashboard_loc_conf_t::cookie_path, and dashboard_cookie_path_valid().
ngx_http_brix_dashboard_set_password()
static char * ngx_http_brix_dashboard_set_password (ngx_conf_t * cf, ngx_command_t * cmd, void * conf) static
Definition at line 252 of file module.c.
References ngx_http_brix_dashboard_loc_conf_t::password, and ngx_http_brix_dashboard_loc_conf_t::users.
ngx_http_brix_dashboard_set_session_ttl()
static char * ngx_http_brix_dashboard_set_session_ttl (ngx_conf_t * cf, ngx_command_t * cmd, void * conf) static
Definition at line 273 of file module.c.
References ngx_http_brix_dashboard_loc_conf_t::session_ttl.
Variable Documentation
ngx_http_brix_dashboard_commands
ngx_command_t ngx_http_brix_dashboard_commands[] static
Definition at line 330 of file module.c.
ngx_http_brix_dashboard_module
ngx_module_t ngx_http_brix_dashboard_module
Initial value:
= {
    NGX_MODULE_V1,
    &ngx_http_brix_dashboard_module_ctx,
    ngx_http_brix_dashboard_commands,
    NGX_HTTP_MODULE,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NGX_MODULE_V1_PADDING
}
Definition at line 479 of file module.c.
Referenced by admin_proxy_add(), brix_admin_body_callback(), brix_admin_dispatch(), brix_admin_read_body(), dashboard_http_bind_slot(), dashboard_http_track(), login_post_body_handler(), ngx_http_brix_dashboard_api_handler(), ngx_http_brix_dashboard_config_download_handler(), ngx_http_brix_dashboard_download_handler(), ngx_http_brix_dashboard_files_handler(), ngx_http_brix_dashboard_main_handler(), ngx_http_brix_dashboard_page_handler(), ngx_http_brix_dashboard_scan_handler(), ngx_http_brix_dashboard_vfs_download_handler(), ngx_http_brix_dashboard_vfs_exports_handler(), and ngx_http_brix_dashboard_vfs_files_handler().
ngx_http_brix_dashboard_module_ctx
ngx_http_module_t ngx_http_brix_dashboard_module_ctx static
Initial value:
= {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    ngx_http_brix_dashboard_create_loc_conf,
    ngx_http_brix_dashboard_merge_loc_conf
}
Definition at line 468 of file module.c.