nginx-xrootd: src/observability/metrics/config.c File Reference
config.c File Reference
#include "core/config/config.h"
#include "core/compat/shm_slots.h"
#include "core/fnv.h"
Functions
ngx_int_t brix_metrics_ensure_zone (ngx_conf_t *cf)
ngx_int_t brix_configure_metrics (ngx_conf_t *cf, ngx_stream_core_main_conf_t *cmcf)
static uint64_t fnv1a64_file (ngx_str_t *path, ngx_log_t *log)
void brix_config_version_publish (ngx_cycle_t *cycle)
ngx_int_t ngx_brix_metrics_shm_init (ngx_shm_zone_t *shm_zone, void *data)
Function Documentation
brix_config_version_publish()
void brix_config_version_publish (ngx_cycle_t * cycle)
Definition at line 146 of file config.c.
References ngx_brix_metrics_t::config_generation, ngx_brix_metrics_t::config_hash, fnv1a64_file(), and ngx_brix_shm_zone.
Referenced by imp_init_module_gate().
brix_configure_metrics()
ngx_int_t brix_configure_metrics (ngx_conf_t * cf, ngx_stream_core_main_conf_t * cmcf)
Definition at line 43 of file config.c.
References brix_metrics_ensure_zone(), BRIX_METRICS_MAX_SERVERS, and ngx_stream_brix_module.
Referenced by ngx_stream_brix_postconfiguration().
brix_metrics_ensure_zone()
ngx_int_t brix_metrics_ensure_zone (ngx_conf_t * cf)
Definition at line 24 of file config.c.
References brix_shm_zone_size(), ngx_brix_metrics_shm_init(), ngx_brix_shm_zone, and ngx_stream_brix_module.
Referenced by brix_configure_metrics(), and ngx_http_brix_cvmfs_postconfiguration().
fnv1a64_file()
static uint64_t fnv1a64_file (ngx_str_t * path, ngx_log_t * log) static
Definition at line 109 of file config.c.
References BRIX_FNV1A64_OFFSET_BASIS, BRIX_FNV1A64_PRIME, and log.
Referenced by brix_config_version_publish().
ngx_brix_metrics_shm_init()
ngx_int_t ngx_brix_metrics_shm_init (ngx_shm_zone_t * shm_zone, void * data)
Definition at line 180 of file config.c.
References brix_shm_table_alloc().
Referenced by brix_metrics_ensure_zone().