nginx-xrootd: src/observability/metrics/unified_internal.h File Reference
unified_internal.h File Reference
#include "metrics_internal.h"
Functions
unsigned long long brix_metric_value (ngx_atomic_t *counter)
unsigned long long brix_unified_legacy_auth (ngx_brix_metrics_t *shm, brix_proto_t proto, ngx_uint_t method, ngx_uint_t status)
void unified_emit_io_bytes (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void unified_emit_io_ops (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void unified_emit_io_latency (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
Variables
const char * brix_unified_auth_names [9]
const char * brix_unified_tpc_direction_names [2]
const ngx_msec_t brix_latency_bounds [9 - 1]
Function Documentation
brix_metric_value()
unsigned long long brix_metric_value (ngx_atomic_t * counter)
Definition at line 30 of file unified_export_io.c.
Referenced by brix_unified_legacy_stream_auth(), brix_unified_legacy_stream_bytes(), brix_unified_legacy_stream_op_slot(), unified_emit_auth(), unified_emit_cache_watermark(), unified_emit_io_bytes(), unified_emit_io_latency_series(), unified_emit_io_ops(), unified_emit_proto_counter(), unified_emit_tpc(), and unified_emit_wt_stage().
brix_unified_legacy_auth()
unsigned long long brix_unified_legacy_auth (ngx_brix_metrics_t * shm, brix_proto_t proto, ngx_uint_t method, ngx_uint_t status)
Definition at line 167 of file unified_export_io.c.
References BRIX_PROTO_ROOT, and brix_unified_legacy_stream_auth().
Referenced by unified_emit_auth().
unified_emit_io_bytes()
void unified_emit_io_bytes (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 191 of file unified_export_io.c.
References brix_metric_proto_name(), brix_metric_value(), BRIX_PROTO_COUNT, BRIX_PROTO_ROOT, BRIX_PROTO_S3, BRIX_PROTO_WEBDAV, brix_unified_legacy_stream_bytes(), ngx_brix_s3_metrics_t::bytes_rx_total, ngx_brix_webdav_metrics_t::bytes_rx_total, ngx_brix_s3_metrics_t::bytes_tx_total, ngx_brix_webdav_metrics_t::bytes_tx_total, ngx_brix_unified_metrics_t::io_bytes_read, ngx_brix_unified_metrics_t::io_bytes_written, mw_printf(), ngx_brix_metrics_t::s3, ngx_brix_metrics_t::unified, and ngx_brix_metrics_t::webdav.
Referenced by brix_export_unified_metrics().
unified_emit_io_latency()
void unified_emit_io_latency (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 335 of file unified_export_io.c.
References BRIX_METRIC_OP_COUNT, BRIX_PROTO_COUNT, mw_printf(), op, and unified_emit_io_latency_series().
Referenced by brix_export_unified_metrics().
unified_emit_io_ops()
void unified_emit_io_ops (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 240 of file unified_export_io.c.
References BRIX_ERR_COUNT, BRIX_ERR_NONE, BRIX_ERR_OTHER, brix_metric_err_name(), BRIX_METRIC_OP_COUNT, brix_metric_op_name(), brix_metric_proto_name(), brix_metric_value(), BRIX_PROTO_COUNT, BRIX_PROTO_ROOT, brix_unified_legacy_stream_op(), ngx_brix_unified_metrics_t::io_ops_total, mw_printf(), op, and ngx_brix_metrics_t::unified.
Referenced by brix_export_unified_metrics().
Variable Documentation
brix_latency_bounds
const ngx_msec_t brix_latency_bounds[9 - 1] extern
Definition at line 81 of file unified.c.
Referenced by brix_metric_op_done(), and unified_emit_io_latency_series().
brix_unified_auth_names
const char* brix_unified_auth_names[9] extern
Definition at line 59 of file unified.c.
Referenced by brix_metric_auth_method_name(), and unified_emit_auth().
brix_unified_tpc_direction_names
const char* brix_unified_tpc_direction_names[ 2] extern
Definition at line 72 of file unified.c.
Referenced by unified_emit_tpc().