nginx-xrootd: src/observability/metrics/handler.c File Reference
handler.c File Reference
#include "metrics_internal.h"
#include "core/http/http_headers.h"
Functions
ngx_int_t ngx_http_brix_metrics_handler (ngx_http_request_t *r)
Variables
ngx_shm_zone_t * ngx_brix_shm_zone = NULL
Function Documentation
ngx_http_brix_metrics_handler()
ngx_int_t ngx_http_brix_metrics_handler (ngx_http_request_t * r)
Definition at line 20 of file handler.c.
References brix_export_prometheus_metrics(), brix_http_source_offer(), brix_kv_metrics_emit(), brix_storage_backend_metrics_emit(), ngx_http_brix_metrics_loc_conf_t::enable, metrics_writer_t::head, mw_finish(), mw_init(), mw_printf(), ngx_brix_shm_zone, ngx_http_brix_metrics_module, metrics_writer_t::pool, and metrics_writer_t::total.
Referenced by ngx_http_brix_metrics_set().
Variable Documentation
ngx_brix_shm_zone
ngx_shm_zone_t* ngx_brix_shm_zone = NULL
Definition at line 11 of file handler.c.
Referenced by brix_config_version_publish(), brix_metrics_ensure_zone(), brix_metrics_shared(), conn_metrics_row(), dashboard_build_storage_io(), dashboard_collect_totals(), dashboard_fill_cache(), dashboard_fill_cvmfs(), dashboard_history_sum_totals(), health_build_json(), ngx_http_brix_metrics_handler(), and reap_metrics_slot().