nginx-xrootd: src/auth/crypto/ocsp_internal.h File Reference
ocsp_internal.h File Reference
#include "ocsp.h"
#include <openssl/ocsp.h>
#include <openssl/x509.h>
#include <openssl/bio.h>
#include <openssl/ssl.h>
Data Structures
struct ocsp_url_t
struct ocsp_conn_t
Macros
#define BRIX_OCSP_TIMEOUT_SECS 5
#define OCSP_MAX_RESPONSE_BYTES (64 * 1024)
Functions
int parse_ocsp_url (const char *url, ocsp_url_t *out)
int ocsp_open_bio (ngx_log_t *log, const ocsp_url_t *u, const char *hostport, ocsp_conn_t *out)
int ocsp_connect_bio (ngx_log_t *log, ocsp_conn_t *conn, const char *hostport)
void ocsp_set_io_timeouts (BIO *cbio, int secs)
int ocsp_tls_handshake (ngx_log_t *log, ocsp_conn_t *conn, const char *host, const char *hostport)
void ocsp_conn_free (ocsp_conn_t *c)
OCSP_RESPONSE * do_ocsp_request (ngx_log_t *log, const char *url, X509 *leaf, X509 *issuer, OCSP_CERTID *id, OCSP_REQUEST **req_out)
int check_ocsp_response (ngx_log_t *log, OCSP_RESPONSE *resp, X509_STORE *store, OCSP_CERTID *id, OCSP_REQUEST *req_for_nonce, int require_nonce)
Macro Definition Documentation
BRIX_OCSP_TIMEOUT_SECS
#define BRIX_OCSP_TIMEOUT_SECS 5
Definition at line 47 of file ocsp_internal.h.
OCSP_MAX_RESPONSE_BYTES
#define OCSP_MAX_RESPONSE_BYTES (64 * 1024)
Definition at line 58 of file ocsp_internal.h.
Function Documentation
check_ocsp_response()
int check_ocsp_response (ngx_log_t * log, OCSP_RESPONSE * resp, X509_STORE * store, OCSP_CERTID * id, OCSP_REQUEST * req_for_nonce, int require_nonce)
Definition at line 175 of file ocsp_request.c.
References log.
Referenced by ocsp_check_urls(), and ocsp_fetch_staple_urls().
do_ocsp_request()
OCSP_RESPONSE * do_ocsp_request (ngx_log_t * log, const char * url, X509 * leaf, X509 * issuer, OCSP_CERTID * id, OCSP_REQUEST ** req_out)
Definition at line 70 of file ocsp_request.c.
References BRIX_OCSP_TIMEOUT_SECS, ocsp_conn_t::cbio, ocsp_url_t::host, log, ocsp_build_request(), ocsp_conn_free(), ocsp_connect_bio(), OCSP_MAX_RESPONSE_BYTES, ocsp_open_bio(), ocsp_set_io_timeouts(), ocsp_tls_handshake(), parse_ocsp_url(), ocsp_url_t::path, ocsp_url_t::port, and ocsp_url_t::use_ssl.
Referenced by ocsp_check_urls(), and ocsp_fetch_staple_urls().
ocsp_conn_free()
void ocsp_conn_free (ocsp_conn_t * c)
Definition at line 184 of file ocsp_transport.c.
References c.
Referenced by do_ocsp_request(), ocsp_bio_new_ssl(), and ocsp_open_bio().
ocsp_connect_bio()
int ocsp_connect_bio (ngx_log_t * log, ocsp_conn_t * conn, const char * hostport)
Definition at line 296 of file ocsp_transport.c.
References BRIX_OCSP_TIMEOUT_SECS, BRIX_RESIL_METRIC_INC, ocsp_conn_t::cbio, log, ocsp_connect_deadline(), OCSP_CONNECT_OK, and OCSP_CONNECT_TIMEOUT.
Referenced by do_ocsp_request().
ocsp_open_bio()
int ocsp_open_bio (ngx_log_t * log, const ocsp_url_t * u, const char * hostport, ocsp_conn_t * out)
Definition at line 260 of file ocsp_transport.c.
References ocsp_conn_t::cbio, ocsp_url_t::host, log, ocsp_bio_new_ssl(), ocsp_conn_free(), ocsp_conn_t::ssl, ocsp_conn_t::ssl_ctx, and ocsp_url_t::use_ssl.
Referenced by do_ocsp_request().
ocsp_set_io_timeouts()
void ocsp_set_io_timeouts (BIO * cbio, int secs)
Definition at line 39 of file ocsp_transport.c.
References brix_apply_socket_io_timeouts().
Referenced by do_ocsp_request().
ocsp_tls_handshake()
int ocsp_tls_handshake (ngx_log_t * log, ocsp_conn_t * conn, const char * host, const char * hostport)
Definition at line 323 of file ocsp_transport.c.
References ocsp_conn_t::cbio, host, log, and ocsp_conn_t::ssl.
Referenced by do_ocsp_request().
parse_ocsp_url()
int parse_ocsp_url (const char * url, ocsp_url_t * out)
Definition at line 133 of file ocsp_transport.c.
References ocsp_url_t::host, ocsp_url_scheme_start(), ocsp_url_t::path, and ocsp_url_t::port.
Referenced by do_ocsp_request().