nginx-xrootd: src/auth/crypto/ocsp.h File Reference
ocsp.h File Reference
#include "core/ngx_brix_module.h"
#include <openssl/x509.h>
Functions
int brix_ocsp_check_cert (ngx_log_t *log, X509 *leaf, X509 *issuer, int soft_fail)
ngx_int_t brix_ocsp_staple_fetch (ngx_log_t *log, ngx_stream_brix_srv_conf_t *xcf)
Function Documentation
brix_ocsp_check_cert()
int brix_ocsp_check_cert (ngx_log_t * log, X509 * leaf, X509 * issuer, int soft_fail)
Definition at line 419 of file ocsp.c.
References check_ocsp_response(), do_ocsp_request(), log, and STACK_OF().
Referenced by brix_handle_auth_inner().
brix_ocsp_staple_fetch()
ngx_int_t brix_ocsp_staple_fetch (ngx_log_t * log, ngx_stream_brix_srv_conf_t * xcf)
Definition at line 511 of file ocsp.c.
References check_ocsp_response(), do_ocsp_request(), ngx_stream_brix_srv_conf_t::gsi_cert, ngx_stream_brix_srv_conf_t::gsi_store, log, ngx_memcpy, ngx_stream_brix_srv_conf_t::ocsp, STACK_OF(), brix_ocsp_conf_t::staple_data, and brix_ocsp_conf_t::staple_len.