nginx-xrootd: src/auth/crypto/ocsp_request.c File Reference
ocsp_request.c File Reference
#include "ocsp_internal.h"
#include <openssl/ocsp.h>
#include <openssl/x509.h>
#include <stdio.h>
Functions
static OCSP_REQUEST * ocsp_build_request (OCSP_CERTID *id)
OCSP_RESPONSE * do_ocsp_request (ngx_log_t *log, const char *url, X509 *leaf, X509 *issuer, OCSP_CERTID *id)
int check_ocsp_response (ngx_log_t *log, OCSP_RESPONSE *resp, X509_STORE *store, OCSP_CERTID *id, OCSP_REQUEST *req_for_nonce)
Function Documentation
check_ocsp_response()
int check_ocsp_response (ngx_log_t * log, OCSP_RESPONSE * resp, X509_STORE * store, OCSP_CERTID * id, OCSP_REQUEST * req_for_nonce)
Definition at line 140 of file ocsp_request.c.
References log.
Referenced by ocsp_check_urls(), and ocsp_fetch_staple_urls().
do_ocsp_request()
OCSP_RESPONSE * do_ocsp_request (ngx_log_t * log, const char * url, X509 * leaf, X509 * issuer, OCSP_CERTID * id)
Definition at line 70 of file ocsp_request.c.
References BRIX_OCSP_TIMEOUT_SECS, ocsp_conn_t::cbio, ocsp_url_t::host, log, ocsp_build_request(), ocsp_conn_free(), ocsp_connect_bio(), ocsp_open_bio(), ocsp_set_io_timeouts(), ocsp_tls_handshake(), parse_ocsp_url(), ocsp_url_t::path, ocsp_url_t::port, and ocsp_url_t::use_ssl.
Referenced by ocsp_check_urls(), and ocsp_fetch_staple_urls().
ocsp_build_request()
static OCSP_REQUEST * ocsp_build_request (OCSP_CERTID * id) static
Definition at line 46 of file ocsp_request.c.
Referenced by do_ocsp_request().