nginx-xrootd: src/auth/crypto/ocsp_transport.c File Reference
ocsp_transport.c File Reference
#include "ocsp_internal.h"
#include "observability/metrics/metrics.h"
#include "observability/metrics/metrics_macros.h"
#include "protocols/root/connection/netconnect.h"
#include <string.h>
#include <stdlib.h>
#include <poll.h>
#include <time.h>
Macros
#define OCSP_CONNECT_OK 0
#define OCSP_CONNECT_FAIL (-1)
#define OCSP_CONNECT_TIMEOUT (-2)
Functions
void ocsp_set_io_timeouts (BIO *cbio, int secs)
static int ocsp_connect_deadline (BIO *cbio, int secs)
static const char * ocsp_url_scheme_start (const char *url, ocsp_url_t *out)
int parse_ocsp_url (const char *url, ocsp_url_t *out)
void ocsp_conn_free (ocsp_conn_t *c)
static int ocsp_bio_new_ssl (ngx_log_t *log, const char *host, ocsp_conn_t *out)
int ocsp_open_bio (ngx_log_t *log, const ocsp_url_t *u, const char *hostport, ocsp_conn_t *out)
int ocsp_connect_bio (ngx_log_t *log, ocsp_conn_t *conn, const char *hostport)
int ocsp_tls_handshake (ngx_log_t *log, ocsp_conn_t *conn, const char *host, const char *hostport)
Macro Definition Documentation
OCSP_CONNECT_FAIL
#define OCSP_CONNECT_FAIL (-1)
Definition at line 56 of file ocsp_transport.c.
OCSP_CONNECT_OK
#define OCSP_CONNECT_OK 0
Definition at line 55 of file ocsp_transport.c.
OCSP_CONNECT_TIMEOUT
#define OCSP_CONNECT_TIMEOUT (-2)
Definition at line 57 of file ocsp_transport.c.
Function Documentation
ocsp_bio_new_ssl()
static int ocsp_bio_new_ssl (ngx_log_t * log, const char * host, ocsp_conn_t * out) static
Definition at line 208 of file ocsp_transport.c.
References ocsp_conn_t::cbio, host, log, ocsp_conn_free(), ocsp_conn_t::ssl, and ocsp_conn_t::ssl_ctx.
Referenced by ocsp_open_bio().
ocsp_conn_free()
void ocsp_conn_free (ocsp_conn_t * c)
Definition at line 184 of file ocsp_transport.c.
References c.
Referenced by do_ocsp_request(), ocsp_bio_new_ssl(), and ocsp_open_bio().
ocsp_connect_bio()
int ocsp_connect_bio (ngx_log_t * log, ocsp_conn_t * conn, const char * hostport)
Definition at line 296 of file ocsp_transport.c.
References BRIX_OCSP_TIMEOUT_SECS, BRIX_RESIL_METRIC_INC, ocsp_conn_t::cbio, log, ocsp_connect_deadline(), OCSP_CONNECT_OK, and OCSP_CONNECT_TIMEOUT.
Referenced by do_ocsp_request().
ocsp_connect_deadline()
static int ocsp_connect_deadline (BIO * cbio, int secs) static
Definition at line 60 of file ocsp_transport.c.
References OCSP_CONNECT_FAIL, OCSP_CONNECT_OK, and OCSP_CONNECT_TIMEOUT.
Referenced by ocsp_connect_bio().
ocsp_open_bio()
int ocsp_open_bio (ngx_log_t * log, const ocsp_url_t * u, const char * hostport, ocsp_conn_t * out)
Definition at line 260 of file ocsp_transport.c.
References ocsp_conn_t::cbio, ocsp_url_t::host, log, ocsp_bio_new_ssl(), ocsp_conn_free(), ocsp_conn_t::ssl, ocsp_conn_t::ssl_ctx, and ocsp_url_t::use_ssl.
Referenced by do_ocsp_request().
ocsp_set_io_timeouts()
void ocsp_set_io_timeouts (BIO * cbio, int secs)
Definition at line 39 of file ocsp_transport.c.
References brix_apply_socket_io_timeouts().
Referenced by do_ocsp_request().
ocsp_tls_handshake()
int ocsp_tls_handshake (ngx_log_t * log, ocsp_conn_t * conn, const char * host, const char * hostport)
Definition at line 323 of file ocsp_transport.c.
References ocsp_conn_t::cbio, host, log, and ocsp_conn_t::ssl.
Referenced by do_ocsp_request().
ocsp_url_scheme_start()
static const char * ocsp_url_scheme_start (const char * url, ocsp_url_t * out) static
Definition at line 105 of file ocsp_transport.c.
References ocsp_url_t::port, and ocsp_url_t::use_ssl.
Referenced by parse_ocsp_url().
parse_ocsp_url()
int parse_ocsp_url (const char * url, ocsp_url_t * out)
Definition at line 133 of file ocsp_transport.c.
References ocsp_url_t::host, ocsp_url_scheme_start(), ocsp_url_t::path, and ocsp_url_t::port.
Referenced by do_ocsp_request().