nginx-xrootd: src/auth/crypto/ocsp.c File Reference
ocsp.c File Reference
#include "ocsp.h"
#include "observability/metrics/metrics.h"
#include "observability/metrics/metrics_macros.h"
#include "protocols/root/connection/netconnect.h"
#include <openssl/ocsp.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/bio.h>
#include <openssl/err.h>
#include <openssl/ssl.h>
#include <string.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <poll.h>
#include <time.h>
Macros
#define OCSP_MAX_RESPONSE_BYTES (64 * 1024)
#define BRIX_OCSP_TIMEOUT_SECS 5
#define OCSP_CONNECT_OK 0
#define OCSP_CONNECT_FAIL (-1)
#define OCSP_CONNECT_TIMEOUT (-2)
Functions
static void ocsp_set_io_timeouts (BIO *cbio, int secs)
static int ocsp_connect_deadline (BIO *cbio, int secs)
static int parse_ocsp_url (const char *url, char *host, size_t host_sz, char *path, size_t path_sz, int *port, int *use_ssl)
static OCSP_RESPONSE * do_ocsp_request (ngx_log_t *log, const char *url, X509 *leaf, X509 *issuer, OCSP_CERTID *id)
static int check_ocsp_response (ngx_log_t *log, OCSP_RESPONSE *resp, X509_STORE *store, OCSP_CERTID *id, OCSP_REQUEST *req_for_nonce)
int brix_ocsp_check_cert (ngx_log_t *log, X509 *leaf, X509 *issuer, int soft_fail)
ngx_int_t brix_ocsp_staple_fetch (ngx_log_t *log, ngx_stream_brix_srv_conf_t *xcf)
Macro Definition Documentation
BRIX_OCSP_TIMEOUT_SECS
#define BRIX_OCSP_TIMEOUT_SECS 5
Definition at line 52 of file ocsp.c.
OCSP_CONNECT_FAIL
#define OCSP_CONNECT_FAIL (-1)
Definition at line 73 of file ocsp.c.
OCSP_CONNECT_OK
#define OCSP_CONNECT_OK 0
Definition at line 72 of file ocsp.c.
OCSP_CONNECT_TIMEOUT
#define OCSP_CONNECT_TIMEOUT (-2)
Definition at line 74 of file ocsp.c.
OCSP_MAX_RESPONSE_BYTES
#define OCSP_MAX_RESPONSE_BYTES (64 * 1024)
Definition at line 41 of file ocsp.c.
Function Documentation
brix_ocsp_check_cert()
int brix_ocsp_check_cert (ngx_log_t * log, X509 * leaf, X509 * issuer, int soft_fail)
Definition at line 419 of file ocsp.c.
References check_ocsp_response(), do_ocsp_request(), log, and STACK_OF().
Referenced by brix_handle_auth_inner().
brix_ocsp_staple_fetch()
ngx_int_t brix_ocsp_staple_fetch (ngx_log_t * log, ngx_stream_brix_srv_conf_t * xcf)
Definition at line 511 of file ocsp.c.
References check_ocsp_response(), do_ocsp_request(), ngx_stream_brix_srv_conf_t::gsi_cert, ngx_stream_brix_srv_conf_t::gsi_store, log, ngx_memcpy, ngx_stream_brix_srv_conf_t::ocsp, STACK_OF(), brix_ocsp_conf_t::staple_data, and brix_ocsp_conf_t::staple_len.
check_ocsp_response()
static int check_ocsp_response (ngx_log_t * log, OCSP_RESPONSE * resp, X509_STORE * store, OCSP_CERTID * id, OCSP_REQUEST * req_for_nonce) static
Definition at line 334 of file ocsp.c.
References log.
Referenced by brix_ocsp_check_cert(), and brix_ocsp_staple_fetch().
do_ocsp_request()
static OCSP_RESPONSE * do_ocsp_request (ngx_log_t * log, const char * url, X509 * leaf, X509 * issuer, OCSP_CERTID * id) static
Definition at line 178 of file ocsp.c.
References BRIX_OCSP_TIMEOUT_SECS, BRIX_RESIL_METRIC_INC, log, ocsp_connect_deadline(), OCSP_CONNECT_OK, OCSP_CONNECT_TIMEOUT, ocsp_set_io_timeouts(), and parse_ocsp_url().
Referenced by brix_ocsp_check_cert(), and brix_ocsp_staple_fetch().
ocsp_connect_deadline()
static int ocsp_connect_deadline (BIO * cbio, int secs) static
Definition at line 77 of file ocsp.c.
References OCSP_CONNECT_FAIL, OCSP_CONNECT_OK, and OCSP_CONNECT_TIMEOUT.
Referenced by do_ocsp_request().
ocsp_set_io_timeouts()
static void ocsp_set_io_timeouts (BIO * cbio, int secs) static
Definition at line 56 of file ocsp.c.
References brix_apply_socket_io_timeouts().
Referenced by do_ocsp_request().
parse_ocsp_url()
static int parse_ocsp_url (const char * url, char * host, size_t host_sz, char * path, size_t path_sz, int * port, int * use_ssl) static
Definition at line 120 of file ocsp.c.
Referenced by do_ocsp_request().