nginx-xrootd: src/protocols/root/path/op_path.c File Reference
op_path.c File Reference
#include "core/ngx_brix_module.h"
#include "op_path.h"
#include "fs/path/beneath.h"
#include "fs/path/path_internal.h"
#include "fs/vfs/vfs.h"
#include "fs/vfs/vfs_backend_registry.h"
#include <sys/stat.h>
Functions
int brix_op_path_forbidden_component (const char *reqpath)
static ngx_int_t op_path_probe (ngx_stream_brix_srv_conf_t *conf, ngx_log_t *log, const char *reqpath, int nofollow, brix_vfs_stat_t *vst)
static ngx_int_t op_path_existence_gate (ngx_stream_brix_srv_conf_t *conf, ngx_log_t *log, const char *reqpath, int want_dir)
static void op_path_mode_flags (brix_path_mode_t mode, int *want_dir, int *strip_trailing_slash)
static ngx_int_t op_path_normalize_trailing (int strip_trailing_slash, const char **reqpath, char *norm, size_t norm_sz)
static ngx_int_t op_path_gate (ngx_stream_brix_srv_conf_t *conf, ngx_log_t *log, const char *reqpath, brix_path_mode_t mode, int want_dir)
ngx_int_t brix_path_resolve_beneath (ngx_stream_brix_srv_conf_t *conf, ngx_log_t *log, const char *reqpath, brix_path_mode_t mode, char *resolved, size_t resolved_sz)
int brix_reject_dotdot_path (brix_ctx_t *ctx, ngx_connection_t *c, ngx_uint_t op_id, const char *op_name, const char *reqpath)
ngx_int_t brix_resolve_op_path (brix_ctx_t *ctx, ngx_connection_t *c, ngx_uint_t op_id, const char *op_name, ngx_stream_brix_srv_conf_t *conf, brix_path_mode_t mode, char *reqpath, size_t reqpath_sz, char *resolved, size_t resolved_sz)
void brix_root_vfs_bind_deleg (brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *conf, brix_vfs_ctx_t *vctx)
Function Documentation
brix_op_path_forbidden_component()
int brix_op_path_forbidden_component (const char * reqpath)
Definition at line 38 of file op_path.c.
References brix_path_component_forbidden().
Referenced by brix_http_resolve_path_ex(), brix_path_resolve_beneath(), and brix_resolve_op_path().
brix_path_resolve_beneath()
ngx_int_t brix_path_resolve_beneath (ngx_stream_brix_srv_conf_t * conf, ngx_log_t * log, const char * reqpath, brix_path_mode_t mode, char * resolved, size_t resolved_sz)
Definition at line 279 of file op_path.c.
References brix_beneath_full_path(), brix_count_path_depth(), BRIX_MAX_PATH, brix_op_path_forbidden_component(), log, op_path_gate(), op_path_mode_flags(), and op_path_normalize_trailing().
Referenced by brix_handle_link(), brix_handle_mv(), brix_handle_setattr(), brix_handle_symlink(), and brix_resolve_op_path().
brix_reject_dotdot_path()
int brix_reject_dotdot_path (brix_ctx_t * ctx, ngx_connection_t * c, ngx_uint_t op_id, const char * op_name, const char * reqpath)
Definition at line 317 of file op_path.c.
References brix_log_access(), brix_log_path_warning(), BRIX_OP_ERR, brix_path_has_dotdot(), brix_send_error(), c, kXR_ArgInvalid, and brix_ctx_t::write_rc.
Referenced by brix_dirlist_parse_request(), brix_open_precheck(), locate_resolve_reqpath(), and stat_query_path().
brix_resolve_op_path()
ngx_int_t brix_resolve_op_path (brix_ctx_t * ctx, ngx_connection_t * c, ngx_uint_t op_id, const char * op_name, ngx_stream_brix_srv_conf_t * conf, brix_path_mode_t mode, char * reqpath, size_t reqpath_sz, char * resolved, size_t resolved_sz)
Definition at line 333 of file op_path.c.
References brix_extract_path(), brix_log_access(), brix_log_path_warning(), BRIX_OP_ERR, brix_op_path_forbidden_component(), brix_path_resolve_beneath(), brix_send_error(), c, brix_ctx_recv_t::cur_dlen, kXR_ArgInvalid, kXR_ArgMissing, kXR_NotFound, brix_ctx_recv_t::payload, brix_ctx_t::recv, and brix_ctx_t::write_rc.
Referenced by brix_dispatch_op(), brix_handle_mkdir(), brix_handle_readlink(), and brix_handle_truncate().
brix_root_vfs_bind_deleg()
void brix_root_vfs_bind_deleg (brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * conf, brix_vfs_ctx_t * vctx)
Definition at line 412 of file op_path.c.
References brix_ctx_t::bearer_token, BRIX_CRED_PASSTHROUGH, BRIX_CRED_SELECT, brix_vfs_deleg_bind(), brix_ctx_t::deleg_proxy_pem, and brix_vfs_ctx_t::pool.
Referenced by brix_dirlist_open_dir(), brix_handle_mkdir(), brix_handle_setattr(), brix_handle_truncate(), brix_open_build_cred_ctx(), brix_open_probe(), brix_open_read_probe(), brix_qcksum_open(), brix_statx_symlink_fallback_stat(), fattr_bind_vctx(), mv_bind_vfs(), op_vfs_ctx(), and stat_vfs_ctx_prepare().
op_path_existence_gate()
static ngx_int_t op_path_existence_gate (ngx_stream_brix_srv_conf_t * conf, ngx_log_t * log, const char * reqpath, int want_dir) static
Definition at line 86 of file op_path.c.
References BRIX_MAX_PATH, brix_vfs_backend_resolve(), brix_vfs_stat_t::is_directory, log, ngx_memcpy, and op_path_probe().
Referenced by op_path_gate().
op_path_gate()
static ngx_int_t op_path_gate (ngx_stream_brix_srv_conf_t * conf, ngx_log_t * log, const char * reqpath, brix_path_mode_t mode, int want_dir) static
Definition at line 251 of file op_path.c.
References BRIX_PATH_EITHER, log, and op_path_existence_gate().
Referenced by brix_path_resolve_beneath().
op_path_mode_flags()
static void op_path_mode_flags (brix_path_mode_t mode, int * want_dir, int * strip_trailing_slash) static
Definition at line 177 of file op_path.c.
References BRIX_PATH_EITHER, BRIX_PATH_EXISTING, BRIX_PATH_NOEXIST, and BRIX_PATH_WRITE.
Referenced by brix_path_resolve_beneath().
op_path_normalize_trailing()
static ngx_int_t op_path_normalize_trailing (int strip_trailing_slash, const char ** reqpath, char * norm, size_t norm_sz) static
Definition at line 208 of file op_path.c.
References ngx_memcpy.
Referenced by brix_path_resolve_beneath().
op_path_probe()
static ngx_int_t op_path_probe (ngx_stream_brix_srv_conf_t * conf, ngx_log_t * log, const char * reqpath, int nofollow, brix_vfs_stat_t * vst) static
Definition at line 71 of file op_path.c.
References brix_beneath_full_path(), BRIX_PROTO_ROOT, brix_vfs_ctx_init(), brix_vfs_probe(), log, and PATH_MAX.
Referenced by op_path_existence_gate().