nginx-xrootd: src/protocols/root/write/op_table.c File Reference
op_table.c File Reference
#include "core/ngx_brix_module.h"
#include "op_table.h"
#include "core/compat/namespace_ops.h"
#include "core/compat/error_mapping.h"
#include "fs/path/path.h"
#include "fs/vfs/vfs.h"
Macros
#define N_OPS (sizeof(_ops) / sizeof(_ops[0]))
Functions
static void op_vfs_ctx (const brix_op_exec_t *e, brix_vfs_ctx_t *vctx)
static ngx_int_t exec_chmod (const brix_op_exec_t *e, int *out_errno)
static ngx_int_t exec_rm (const brix_op_exec_t *e, int *out_errno)
static ngx_int_t exec_rmdir (const brix_op_exec_t *e, int *out_errno)
ngx_int_t brix_dispatch_op (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, uint16_t opcode)
Variables
static const brix_op_desc_t _ops []
Macro Definition Documentation
N_OPS
#define N_OPS (sizeof(_ops) / sizeof(_ops[0]))
Definition at line 97 of file op_table.c.
Function Documentation
brix_dispatch_op()
ngx_int_t brix_dispatch_op (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, uint16_t opcode)
Definition at line 101 of file op_table.c.
References _ops, brix_op_desc_t::auth_level, brix_auth_gate(), brix_kxr_err_string(), brix_kxr_from_errno(), BRIX_MAX_PATH, brix_resolve_op_path(), BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_send_error(), c, brix_op_exec_t::c, brix_op_exec_t::conf, brix_op_exec_t::ctx, brix_op_desc_t::exec, kXR_InvalidRequest, N_OPS, brix_op_desc_t::name, brix_op_desc_t::need_write, brix_op_desc_t::op_id, PATH_MAX, brix_op_desc_t::path_mode, brix_op_exec_t::reqpath, brix_op_exec_t::resolved, and brix_ctx_t::write_rc.
Referenced by brix_handle_chmod(), brix_handle_rm(), and brix_handle_rmdir().
exec_chmod()
static ngx_int_t exec_chmod (const brix_op_exec_t * e, int * out_errno) static
Definition at line 26 of file op_table.c.
References brix_vfs_chmod(), brix_op_exec_t::ctx, brix_ctx_recv_t::hdr_buf, mode, xrdw_chmod_req_t::mode, op_vfs_ctx(), brix_ctx_t::recv, and xrdw_chmod_req_unpack().
exec_rm()
static ngx_int_t exec_rm (const brix_op_exec_t * e, int * out_errno) static
Definition at line 53 of file op_table.c.
References brix_vfs_unlink(), and op_vfs_ctx().
exec_rmdir()
static ngx_int_t exec_rmdir (const brix_op_exec_t * e, int * out_errno) static
Definition at line 70 of file op_table.c.
References brix_vfs_rmdir(), and op_vfs_ctx().
op_vfs_ctx()
static void op_vfs_ctx (const brix_op_exec_t * e, brix_vfs_ctx_t * vctx) static
Definition at line 17 of file op_table.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_ROOT, brix_vfs_ctx_init(), brix_op_exec_t::c, ngx_stream_brix_srv_conf_t::common, brix_op_exec_t::conf, brix_op_exec_t::resolved, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by exec_chmod(), exec_rm(), and exec_rmdir().
Variable Documentation
_ops
const brix_op_desc_t _ops[] static
Initial value:
= {
    {  3002  ,  "CHMOD",   14 ,   0x04  , 1,
      BRIX_PATH_EXISTING, exec_chmod },
    {  3014  ,     "RM",      12 ,      0x08  , 1,
      BRIX_PATH_EXISTING, exec_rm    },
    {  3015  ,  "RMDIR",   11 ,   0x08  , 1,
      BRIX_PATH_EITHER,   exec_rmdir },
}
Definition at line 89 of file op_table.c.
Referenced by brix_dispatch_op().