nginx-xrootd: src/protocols/root/write/op_table.h File Reference
op_table.h File Reference
#include "core/ngx_brix_module.h"
#include "protocols/root/path/op_path.h"
Data Structures
struct brix_op_exec_t
struct brix_op_desc_t
Functions
ngx_int_t brix_dispatch_op (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, uint16_t opcode)
Function Documentation
brix_dispatch_op()
ngx_int_t brix_dispatch_op (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, uint16_t opcode)
Definition at line 119 of file op_table.c.
References brix_op_desc_t::auth_level, brix_auth_gate(), brix_kxr_err_string(), brix_kxr_from_errno(), BRIX_MAX_PATH, brix_resolve_op_path(), BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_send_error(), c, brix_op_exec_t::c, brix_op_exec_t::conf, brix_op_exec_t::ctx, brix_op_desc_t::exec, kXR_InvalidRequest, N_OPS, brix_op_desc_t::name, brix_op_desc_t::need_write, brix_op_desc_t::op_id, op_table, PATH_MAX, brix_op_desc_t::path_mode, brix_op_exec_t::reqpath, brix_op_exec_t::resolved, and brix_ctx_t::write_rc.
Referenced by brix_handle_chmod(), brix_handle_rm(), and brix_handle_rmdir().