nginx-xrootd: src/protocols/root/path/opaque_validate.c File Reference
opaque_validate.c File Reference
#include "opaque_validate.h"
#include <stddef.h>
Functions
static void brix_opaque_permit_init (void)
int brix_opaque_illegal_byte (const char *opaque, unsigned char *bad)
static size_t brix_opaque_key_len (const char *seg, size_t seg_len)
static int brix_opaque_key_eq (const char *key, size_t key_len, const char *cand)
static int brix_opaque_key_has_prefix (const char *key, size_t key_len, const char *prefix)
static int brix_opaque_is_uint (const char *val, size_t val_len)
static void brix_opaque_copy_key (const char *key, size_t key_len, char *keybuf, size_t keybuf_len)
static int brix_opaque_check_segment (const char *seg, size_t seg_len, char *keybuf, size_t keybuf_len)
int brix_opaque_schema_check (const char *opaque, char *keybuf, size_t keybuf_len)
Variables
static const char BRIX_OPAQUE_ALLOWED []
static unsigned char brix_opaque_permit [256]
static int brix_opaque_permit_ready
static const char *const BRIX_OPAQUE_NAMESPACES []
static const char *const BRIX_OPAQUE_BARE_KEYS []
Function Documentation
brix_opaque_check_segment()
static int brix_opaque_check_segment (const char * seg, size_t seg_len, char * keybuf, size_t keybuf_len) static
Definition at line 219 of file opaque_validate.c.
References BRIX_OPAQUE_BARE_KEYS, brix_opaque_copy_key(), brix_opaque_is_uint(), brix_opaque_key_eq(), brix_opaque_key_has_prefix(), brix_opaque_key_len(), BRIX_OPAQUE_NAMESPACES, BRIX_OPAQUE_SCHEMA_BAD_TYPE, BRIX_OPAQUE_SCHEMA_OK, and BRIX_OPAQUE_SCHEMA_UNKNOWN_KEY.
Referenced by brix_opaque_schema_check().
brix_opaque_copy_key()
static void brix_opaque_copy_key (const char * key, size_t key_len, char * keybuf, size_t keybuf_len) static
Definition at line 199 of file opaque_validate.c.
References key.
Referenced by brix_opaque_check_segment().
brix_opaque_illegal_byte()
int brix_opaque_illegal_byte (const char * opaque, unsigned char * bad)
Definition at line 88 of file opaque_validate.c.
References brix_opaque_permit, brix_opaque_permit_init(), brix_opaque_permit_ready, and s.
Referenced by brix_open_precheck().
brix_opaque_is_uint()
static int brix_opaque_is_uint (const char * val, size_t val_len) static
Definition at line 183 of file opaque_validate.c.
Referenced by brix_opaque_check_segment().
brix_opaque_key_eq()
static int brix_opaque_key_eq (const char * key, size_t key_len, const char * cand) static
Definition at line 155 of file opaque_validate.c.
References key.
Referenced by brix_opaque_check_segment().
brix_opaque_key_has_prefix()
static int brix_opaque_key_has_prefix (const char * key, size_t key_len, const char * prefix) static
Definition at line 169 of file opaque_validate.c.
References key.
Referenced by brix_opaque_check_segment().
brix_opaque_key_len()
static size_t brix_opaque_key_len (const char * seg, size_t seg_len) static
Definition at line 141 of file opaque_validate.c.
Referenced by brix_opaque_check_segment().
brix_opaque_permit_init()
static void brix_opaque_permit_init (void) static
Definition at line 67 of file opaque_validate.c.
References BRIX_OPAQUE_ALLOWED, brix_opaque_permit, and brix_opaque_permit_ready.
Referenced by brix_opaque_illegal_byte().
brix_opaque_schema_check()
int brix_opaque_schema_check (const char * opaque, char * keybuf, size_t keybuf_len)
Definition at line 262 of file opaque_validate.c.
References brix_opaque_check_segment(), and BRIX_OPAQUE_SCHEMA_OK.
Referenced by brix_open_precheck().
Variable Documentation
BRIX_OPAQUE_ALLOWED
const char BRIX_OPAQUE_ALLOWED[] static
Initial value:
=
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "abcdefghijklmnopqrstuvwxyz"
    "0123456789"
    ".-_~"
    "/:@[]"
    "%+"
    "=&,?;"
Definition at line 42 of file opaque_validate.c.
Referenced by brix_opaque_permit_init().
BRIX_OPAQUE_BARE_KEYS
const char* const BRIX_OPAQUE_BARE_KEYS[] static
Initial value:
= {
    "authz", NULL
}
Definition at line 135 of file opaque_validate.c.
Referenced by brix_opaque_check_segment().
BRIX_OPAQUE_NAMESPACES
const char* const BRIX_OPAQUE_NAMESPACES[] static
Initial value:
= {
    "oss.", "tpc.", "xrd.", "xrdcl.", "cms.", "scitag.", NULL
}
Definition at line 130 of file opaque_validate.c.
Referenced by brix_opaque_check_segment().
brix_opaque_permit
unsigned char brix_opaque_permit[256] static
Definition at line 63 of file opaque_validate.c.
Referenced by brix_opaque_illegal_byte(), and brix_opaque_permit_init().
brix_opaque_permit_ready
int brix_opaque_permit_ready static
Definition at line 64 of file opaque_validate.c.
Referenced by brix_opaque_illegal_byte(), and brix_opaque_permit_init().