nginx-xrootd: src/protocols/root/path/opaque_validate.h File Reference
opaque_validate.h File Reference
#include <stddef.h>
Macros
#define BRIX_OPAQUE_SCHEMA_OK 0 /* every key recognized, typed values conform */
#define BRIX_OPAQUE_SCHEMA_BAD_TYPE 1 /* a typed key carried a non-conforming value */
#define BRIX_OPAQUE_SCHEMA_UNKNOWN_KEY 2 /* a key outside every recognized namespace */
Functions
int brix_opaque_illegal_byte (const char *opaque, unsigned char *bad)
int brix_opaque_schema_check (const char *opaque, char *keybuf, size_t keybuf_len)
Macro Definition Documentation
BRIX_OPAQUE_SCHEMA_BAD_TYPE
#define BRIX_OPAQUE_SCHEMA_BAD_TYPE 1 /* a typed key carried a non-conforming value */
Definition at line 33 of file opaque_validate.h.
BRIX_OPAQUE_SCHEMA_OK
#define BRIX_OPAQUE_SCHEMA_OK 0 /* every key recognized, typed values conform */
Definition at line 32 of file opaque_validate.h.
BRIX_OPAQUE_SCHEMA_UNKNOWN_KEY
#define BRIX_OPAQUE_SCHEMA_UNKNOWN_KEY 2 /* a key outside every recognized namespace */
Definition at line 34 of file opaque_validate.h.
Function Documentation
brix_opaque_illegal_byte()
int brix_opaque_illegal_byte (const char * opaque, unsigned char * bad)
Definition at line 84 of file opaque_validate.c.
References brix_opaque_permit, brix_opaque_permit_init(), brix_opaque_permit_ready, and s.
Referenced by brix_open_precheck().
brix_opaque_schema_check()
int brix_opaque_schema_check (const char * opaque, char * keybuf, size_t keybuf_len)
Definition at line 258 of file opaque_validate.c.
References brix_opaque_check_segment(), and BRIX_OPAQUE_SCHEMA_OK.
Referenced by brix_open_precheck().