nginx-xrootd: src/protocols/root/read/open_cache.c File Reference
open_cache.c File Reference
#include "open.h"
#include "fs/cache/cache_storage.h"
#include "fs/path/beneath.h"
Functions
ngx_int_t brix_open_cached_read (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *clean_path, uint16_t options, uint16_t mode_bits)
Function Documentation
brix_open_cached_read()
ngx_int_t brix_open_cached_read (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * clean_path, uint16_t options, uint16_t mode_bits)
Definition at line 11 of file open_cache.c.
References brix_auth_gate(), BRIX_AUTH_READ, brix_beneath_full_path(), brix_beneath_rel(), brix_cache_open_or_fill(), BRIX_OP_OPEN_RD, brix_open_resolved_file(), BRIX_RETURN_ERR, c, ngx_stream_brix_srv_conf_t::cache_root, ngx_stream_brix_srv_conf_t::common, kXR_ArgInvalid, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, stat(), and brix_ctx_t::write_rc.
Referenced by brix_handle_open().