nginx-xrootd: src/protocols/root/read/open_resolved_file_staging.c File Reference
open_resolved_file_staging.c File Reference
#include "open.h"
#include "fs/vfs/vfs.h"
#include "protocols/root/path/op_path.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "fs/vfs/vfs_internal.h"
#include "fs/backend/sd.h"
#include "core/ngx_brix_module.h"
#include "fs/backend/csi_tagstore.h"
#include "fs/cache/cache_storage.h"
#include "net/ratelimit/throttle_compat.h"
#include "protocols/root/response/async.h"
#include "net/mirror/stream_wmirror.h"
#include "protocols/root/write/wrts_journal.h"
#include "core/compat/tmp_path.h"
#include "fs/cache/writethrough_metrics.h"
#include "net/manager/registry.h"
#include "net/manager/pending.h"
#include "protocols/root/session/registry.h"
#include "core/compat/codec_core.h"
#include "protocols/root/protocol/open_flags.h"
#include "observability/sesslog/sesslog_ngx.h"
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include "open_resolved_file_internal.h"
Functions
static int brix_open_probe (ngx_log_t *log, const char *root, const char *abs, int nofollow, brix_vfs_stat_t *vst, brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *conf, ngx_pool_t *pool)
static ngx_int_t brix_open_check_write_target (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *resolved, ngx_flag_t is_write)
static ngx_int_t brix_open_stage_backpressure (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *resolved, ngx_flag_t is_write)
static ngx_int_t brix_open_check_exclusive_create (brix_open_args_t *a)
static ngx_int_t brix_open_build_stage_temp (brix_open_args_t *a)
static void brix_open_resume_inplace_decide (brix_open_args_t *a)
ngx_int_t brix_open_stage_preflight (brix_open_args_t *a)
Function Documentation
brix_open_build_stage_temp()
static ngx_int_t brix_open_build_stage_temp (brix_open_args_t * a) static
Definition at line 193 of file open_resolved_file_staging.c.
References brix_make_resume_path(), brix_make_tmp_path(), BRIX_OP_OPEN_WR, BRIX_RETURN_ERR, c, brix_open_args_t::c, brix_open_args_t::conf, brix_open_args_t::ctx, brix_ctx_login_t::dn, kXR_ServerError, brix_ctx_t::login, brix_open_args_t::posc_temp_path, brix_open_args_t::resolved, brix_open_args_t::use_posc, and brix_open_args_t::use_resume.
Referenced by brix_open_stage_preflight().
brix_open_check_exclusive_create()
static ngx_int_t brix_open_check_exclusive_create (brix_open_args_t * a) static
Definition at line 166 of file open_resolved_file_staging.c.
References BRIX_OP_OPEN_WR, brix_open_probe(), BRIX_RETURN_ERR, c, brix_open_args_t::c, brix_open_args_t::conf, brix_open_args_t::ctx, kXR_delete, kXR_ItExists, kXR_new, brix_open_args_t::options, brix_open_args_t::resolved, and brix_open_args_t::stage.
Referenced by brix_open_stage_preflight().
brix_open_check_write_target()
static ngx_int_t brix_open_check_write_target (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * resolved, ngx_flag_t is_write) static
Definition at line 86 of file open_resolved_file_staging.c.
References BRIX_OP_OPEN_WR, brix_open_probe(), BRIX_RETURN_ERR, c, brix_vfs_stat_t::is_directory, kXR_isDirectory, kXR_NotAuthorized, and brix_vfs_stat_t::mode.
Referenced by brix_open_stage_preflight().
brix_open_probe()
static int brix_open_probe (ngx_log_t * log, const char * root, const char * abs, int nofollow, brix_vfs_stat_t * vst, brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * conf, ngx_pool_t * pool) static
Definition at line 66 of file open_resolved_file_staging.c.
References BRIX_PROTO_ROOT, brix_root_vfs_bind_deleg(), brix_vfs_ctx_init(), brix_vfs_probe(), and log.
Referenced by brix_open_check_exclusive_create(), brix_open_check_write_target(), brix_open_resume_inplace_decide(), and brix_open_stage_preflight().
brix_open_resume_inplace_decide()
static void brix_open_resume_inplace_decide (brix_open_args_t * a) static
Definition at line 239 of file open_resolved_file_staging.c.
References brix_open_probe(), c, brix_open_args_t::c, brix_open_args_t::conf, brix_open_args_t::ctx, brix_vfs_stat_t::is_regular, kXR_delete, kXR_new, brix_open_args_t::options, brix_open_args_t::posc_temp_path, brix_open_args_t::resolved, brix_open_args_t::stage, stat(), brix_open_args_t::use_posc, and brix_open_args_t::use_resume.
Referenced by brix_open_stage_preflight().
brix_open_stage_backpressure()
static ngx_int_t brix_open_stage_backpressure (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * resolved, ngx_flag_t is_write) static
Definition at line 128 of file open_resolved_file_staging.c.
References brix_log_access(), brix_metric_wt_stage_throttled(), BRIX_OP_OPEN_WR, BRIX_RETURN_ERR, brix_send_wait(), BRIX_WT_ADMIT_ALLOW, BRIX_WT_ADMIT_REJECT, BRIX_WT_ADMIT_WAIT, brix_wt_stage_admit(), BRIX_WT_STAGE_WAIT_SECS, c, and kXR_Overloaded.
Referenced by brix_open_stage_preflight().
brix_open_stage_preflight()
ngx_int_t brix_open_stage_preflight (brix_open_args_t * a)
Definition at line 295 of file open_resolved_file_staging.c.
References brix_cache_storage_decorator(), BRIX_OP_OPEN_RD, brix_open_build_stage_temp(), brix_open_check_exclusive_create(), brix_open_check_write_target(), brix_open_probe(), brix_open_resume_inplace_decide(), brix_open_stage_backpressure(), BRIX_RETURN_ERR, c, brix_open_args_t::c, brix_open_args_t::conf, brix_open_args_t::ctx, brix_vfs_stat_t::is_directory, brix_open_args_t::is_write, kXR_isDirectory, and brix_open_args_t::resolved.
Referenced by brix_open_resolved_file().