nginx-xrootd: src/protocols/root/read/open_request_resolve.c File Reference
open_request_resolve.c File Reference
#include "open.h"
#include "open_internal.h"
#include "protocols/ssi/ssi.h"
#include "protocols/root/path/op_path.h"
#include "net/manager/registry.h"
#include "net/manager/redir_cache.h"
#include "net/manager/pending.h"
#include "fs/xfer/stage_request_registry.h"
#include "fs/xfer/stage_waiter.h"
#include "fs/vfs/vfs.h"
#include "fs/path/reserved_names.h"
#include "protocols/root/session/registry.h"
#include "net/cms/cms_internal.h"
#include "core/compat/codec_core.h"
#include "protocols/root/protocol/open_flags.h"
#include "protocols/root/zip/zip_member.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "fs/vfs/vfs_internal.h"
#include "fs/backend/sd.h"
#include "fs/backend/cache/sd_cache.h"
#include <string.h>
#include <unistd.h>
Functions
static int brix_open_read_probe (brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *conf, ngx_connection_t *c, const char *clean_path, const char *full_path, int *is_dir)
static ngx_int_t brix_open_residency_gate (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *clean_path, char *full_path, uint16_t options)
ngx_int_t brix_open_read_resolve (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *clean_path, char *full_path, uint16_t options, uint16_t mode_bits)
ngx_int_t brix_open_write_resolve (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *clean_path, char *full_path, uint16_t options)
Function Documentation
brix_open_read_probe()
static int brix_open_read_probe (brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * conf, ngx_connection_t * c, const char * clean_path, const char * full_path, int * is_dir) static
Definition at line 46 of file open_request_resolve.c.
References BRIX_PROTO_ROOT, brix_root_vfs_bind_deleg(), brix_sd_cache_fill_needs_offload(), brix_sd_stat_maybe_cred(), brix_sd_ucred_wipe(), brix_stat_beneath(), brix_vfs_backend_cred(), brix_vfs_backend_resolve(), brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), brix_vfs_export_relative_root(), brix_vfs_ns_leaf(), c, brix_ctx_t::identity, brix_sd_stat_t::is_dir, key, log, brix_vfs_ctx_t::pool, and stat().
Referenced by brix_open_read_resolve().
brix_open_read_resolve()
ngx_int_t brix_open_read_resolve (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * clean_path, char * full_path, uint16_t options, uint16_t mode_bits)
Definition at line 213 of file open_request_resolve.c.
References brix_auth_gate(), BRIX_AUTH_READ, brix_beneath_full_path(), brix_log_access(), BRIX_OP_OK, BRIX_OP_OPEN_RD, brix_open_cached_read(), brix_open_read_probe(), brix_open_residency_gate(), BRIX_RETURN_ERR, brix_upstream_start(), brix_zip_open_member(), c, kXR_ArgInvalid, kXR_isDirectory, kXR_NotFound, open_extract_zip_member(), PATH_MAX, and brix_ctx_t::write_rc.
Referenced by brix_handle_open().
brix_open_residency_gate()
static ngx_int_t brix_open_residency_gate (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * clean_path, char * full_path, uint16_t options) static
Definition at line 141 of file open_request_resolve.c.
References brix_log_access(), BRIX_OP_OPEN_RD, BRIX_PROTO_ROOT, BRIX_RETURN_ERR, BRIX_SD_RES_LOST, BRIX_SD_RES_NEARLINE, BRIX_SD_RES_OFFLINE, brix_send_wait(), brix_send_waitresp(), brix_stage_registry_singleton(), BRIX_STAGE_REQID_LEN, brix_stage_request_add(), brix_stage_waiter_add(), brix_vfs_ctx_init(), brix_vfs_residency(), c, brix_ctx_recv_t::cur_streamid, brix_ctx_login_t::dn, kXR_FSError, kXR_wait, brix_stage_request_view_t::lfn, brix_ctx_t::login, brix_vfs_ctx_t::pool, brix_ctx_t::recv, brix_stage_request_view_t::requester_dn, brix_ctx_t::state, brix_stage_request_view_t::tod_expire, and XRD_ST_WAITING_FRM.
Referenced by brix_open_read_resolve().
brix_open_write_resolve()
ngx_int_t brix_open_write_resolve (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * clean_path, char * full_path, uint16_t options)
Definition at line 289 of file open_request_resolve.c.
References BRIX_AOP_CREATE, BRIX_AOP_UPDATE, brix_auth_gate_op(), BRIX_AUTH_UPDATE, brix_beneath_full_path(), brix_mkdir_recursive_policy(), BRIX_OP_OPEN_WR, c, kXR_async, kXR_mkpath, kXR_new, PATH_MAX, and brix_ctx_t::write_rc.
Referenced by brix_handle_open().