nginx-xrootd: src/protocols/root/read/open_request.c File Reference
open_request.c File Reference
#include "open.h"
#include "open_internal.h"
#include "protocols/ssi/ssi.h"
#include "protocols/root/path/op_path.h"
#include "net/manager/registry.h"
#include "net/manager/redir_cache.h"
#include "net/manager/pending.h"
#include "fs/xfer/stage_request_registry.h"
#include "fs/xfer/stage_waiter.h"
#include "fs/vfs/vfs.h"
#include "fs/path/reserved_names.h"
#include "protocols/root/session/registry.h"
#include "net/cms/cms_internal.h"
#include "core/compat/codec_core.h"
#include "protocols/root/protocol/open_flags.h"
#include "protocols/root/zip/zip_member.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "fs/vfs/vfs_internal.h"
#include "fs/backend/sd.h"
#include "fs/backend/cache/sd_cache.h"
#include <string.h>
#include <unistd.h>
Functions
static int open_cgi_find_value (const char *opaque, const char *key, const char **val, size_t *vlen)
static int brix_open_read_probe (brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *conf, ngx_connection_t *c, const char *clean_path, const char *full_path, int *is_dir)
static uint8_t open_negotiate_compress_codec (brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *conf, ngx_flag_t is_write)
static int open_zip_member_path_unsafe (const char *out, size_t vlen)
static int open_extract_zip_member (brix_ctx_t *ctx, char *out, size_t outsz)
static void brix_pmark_echo_timer (ngx_event_t *ev)
static ngx_int_t brix_open_mode_guard (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, int is_write, const char *md)
static ngx_int_t brix_open_precheck (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, int is_write, char *clean_path)
static ngx_int_t brix_open_residency_gate (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *clean_path, char *full_path, uint16_t options)
static ngx_int_t brix_open_read_resolve (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *clean_path, char *full_path, uint16_t options, uint16_t mode_bits)
static ngx_int_t brix_open_write_resolve (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *clean_path, char *full_path, uint16_t options)
static void brix_open_begin_pmark (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, int is_write, const char *clean_path)
static ngx_int_t brix_open_try_cache_offload (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *clean_path, char *full_path, uint16_t options, uint16_t mode_bits)
ngx_int_t brix_handle_open (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_handle_open()
ngx_int_t brix_handle_open (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 744 of file open_request.c.
References brix_extract_path(), brix_open_begin_pmark(), brix_open_handle_tpc(), brix_open_manager_redirect(), brix_open_options_is_write(), brix_open_precheck(), brix_open_read_resolve(), brix_open_resolved_file(), brix_open_try_cache_offload(), brix_open_write_resolve(), brix_ssi_match(), brix_ssi_open(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::hdr_buf, xrdw_open_req_t::mode, open_negotiate_compress_codec(), xrdw_open_req_t::options, PATH_MAX, brix_ctx_recv_t::payload, brix_ctx_t::recv, brix_open_request_t::resolved, and xrdw_open_req_unpack().
Referenced by brix_dispatch_read_opcode().
brix_open_begin_pmark()
static void brix_open_begin_pmark (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, int is_write, const char * clean_path) static
Definition at line 657 of file open_request.c.
References brix_identity_dn_cstr(), brix_identity_vo_csv_cstr(), BRIX_MAX_PATH, brix_pmark_echo_timer(), brix_pmark_flow_begin(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_pmark_t::echo_ev, brix_ctx_pmark_t::echo_ms, brix_ctx_pmark_t::flow, brix_ctx_t::identity, open_extract_opaque(), brix_ctx_recv_t::payload, brix_ctx_t::pmark, and brix_ctx_t::recv.
Referenced by brix_handle_open().
brix_open_mode_guard()
static ngx_int_t brix_open_mode_guard (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, int is_write, const char * md) static
Definition at line 314 of file open_request.c.
References brix_log_access(), BRIX_OP_ERR, BRIX_OP_OPEN_WR, brix_send_error(), c, kXR_fsReadOnly, kXR_Unsupported, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by brix_open_precheck().
brix_open_precheck()
static ngx_int_t brix_open_precheck (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, int is_write, char * clean_path) static
Definition at line 348 of file open_request.c.
References brix_count_path_depth(), brix_extract_path(), brix_is_internal_name(), BRIX_MAX_PATH, BRIX_OP_OPEN_RD, BRIX_OP_OPEN_WR, brix_opaque_illegal_byte(), BRIX_OPAQUE_SCHEMA_BAD_TYPE, brix_opaque_schema_check(), BRIX_OPAQUE_SCHEMA_OK, brix_open_mode_guard(), brix_reject_dotdot_path(), BRIX_RETURN_ERR, c, brix_ctx_recv_t::cur_dlen, kXR_ArgInvalid, kXR_ArgMissing, kXR_NotFound, op, open_extract_opaque(), PATH_MAX, brix_ctx_recv_t::payload, brix_ctx_t::recv, and brix_ctx_t::write_rc.
Referenced by brix_handle_open().
brix_open_read_probe()
static int brix_open_read_probe (brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * conf, ngx_connection_t * c, const char * clean_path, const char * full_path, int * is_dir) static
Definition at line 79 of file open_request.c.
References BRIX_PROTO_ROOT, brix_root_vfs_bind_deleg(), brix_sd_cache_fill_needs_offload(), brix_sd_stat_maybe_cred(), brix_sd_ucred_wipe(), brix_stat_beneath(), brix_vfs_backend_cred(), brix_vfs_backend_resolve(), brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), brix_vfs_export_relative_root(), c, brix_ctx_t::identity, brix_sd_stat_t::is_dir, key, log, brix_vfs_ctx_t::pool, and stat().
Referenced by brix_open_read_resolve().
brix_open_read_resolve()
static ngx_int_t brix_open_read_resolve (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * clean_path, char * full_path, uint16_t options, uint16_t mode_bits) static
Definition at line 536 of file open_request.c.
References brix_auth_gate(), BRIX_AUTH_READ, brix_beneath_full_path(), brix_log_access(), BRIX_OP_OK, BRIX_OP_OPEN_RD, brix_open_cached_read(), brix_open_read_probe(), brix_open_residency_gate(), BRIX_RETURN_ERR, brix_upstream_start(), brix_zip_open_member(), c, kXR_ArgInvalid, kXR_isDirectory, kXR_NotFound, open_extract_zip_member(), PATH_MAX, and brix_ctx_t::write_rc.
Referenced by brix_handle_open().
brix_open_residency_gate()
static ngx_int_t brix_open_residency_gate (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * clean_path, char * full_path, uint16_t options) static
Definition at line 464 of file open_request.c.
References brix_log_access(), BRIX_OP_OPEN_RD, BRIX_PROTO_ROOT, BRIX_RETURN_ERR, BRIX_SD_RES_LOST, BRIX_SD_RES_NEARLINE, BRIX_SD_RES_OFFLINE, brix_send_wait(), brix_send_waitresp(), brix_stage_registry_singleton(), BRIX_STAGE_REQID_LEN, brix_stage_request_add(), brix_stage_waiter_add(), brix_vfs_ctx_init(), brix_vfs_residency(), c, brix_ctx_recv_t::cur_streamid, brix_ctx_login_t::dn, kXR_FSError, kXR_wait, brix_stage_request_view_t::lfn, brix_ctx_t::login, brix_vfs_ctx_t::pool, brix_ctx_t::recv, brix_stage_request_view_t::requester_dn, brix_ctx_t::state, brix_stage_request_view_t::tod_expire, and XRD_ST_WAITING_FRM.
Referenced by brix_open_read_resolve().
brix_open_try_cache_offload()
static ngx_int_t brix_open_try_cache_offload (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * clean_path, char * full_path, uint16_t options, uint16_t mode_bits) static
Definition at line 699 of file open_request.c.
References brix_cache_open_fill_offload(), brix_sd_cache_fill_needs_offload(), brix_vfs_backend_resolve(), brix_vfs_export_relative_root(), and c.
Referenced by brix_handle_open().
brix_open_write_resolve()
static ngx_int_t brix_open_write_resolve (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * clean_path, char * full_path, uint16_t options) static
Definition at line 612 of file open_request.c.
References BRIX_AOP_CREATE, BRIX_AOP_UPDATE, brix_auth_gate_op(), BRIX_AUTH_UPDATE, brix_beneath_full_path(), brix_mkdir_recursive_policy(), BRIX_OP_OPEN_WR, c, kXR_async, kXR_mkpath, kXR_new, PATH_MAX, and brix_ctx_t::write_rc.
Referenced by brix_handle_open().
brix_pmark_echo_timer()
static void brix_pmark_echo_timer (ngx_event_t * ev) static
Definition at line 295 of file open_request.c.
References brix_pmark_flow_echo(), brix_ctx_t::destroyed, brix_ctx_pmark_t::echo_ms, brix_ctx_pmark_t::flow, and brix_ctx_t::pmark.
Referenced by brix_open_begin_pmark().
open_cgi_find_value()
static int open_cgi_find_value (const char * opaque, const char * key, const char ** val, size_t * vlen) static
Definition at line 35 of file open_request.c.
References key.
Referenced by open_extract_zip_member(), and open_negotiate_compress_codec().
open_extract_zip_member()
static int open_extract_zip_member (brix_ctx_t * ctx, char * out, size_t outsz) static
Definition at line 256 of file open_request.c.
References BRIX_MAX_PATH, brix_ctx_recv_t::cur_dlen, ngx_memcpy, open_cgi_find_value(), open_extract_opaque(), open_zip_member_path_unsafe(), brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by brix_open_read_resolve().
open_negotiate_compress_codec()
static uint8_t open_negotiate_compress_codec (brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * conf, ngx_flag_t is_write) static
Definition at line 178 of file open_request.c.
References brix_codec_desc_t::available, brix_codec_by_http_token(), brix_codec_by_name(), BRIX_CODEC_IDENTITY, BRIX_MAX_PATH, brix_ctx_recv_t::cur_dlen, brix_codec_desc_t::id, open_cgi_find_value(), open_extract_opaque(), brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by brix_handle_open().
open_zip_member_path_unsafe()
static int open_zip_member_path_unsafe (const char * out, size_t vlen) static
Definition at line 235 of file open_request.c.
Referenced by open_extract_zip_member().