nginx-xrootd: src/protocols/root/read/open_manager.c File Reference
open_manager.c File Reference
#include "open_internal.h"
#include "net/manager/registry.h"
#include "net/manager/redir_cache.h"
#include "net/manager/pending.h"
#include "net/cms/cms_internal.h"
Functions
static ngx_int_t brix_open_cms_locate (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *clean_path)
ngx_int_t brix_open_manager_redirect (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, int is_write, const char *clean_path)
Function Documentation
brix_open_cms_locate()
static ngx_int_t brix_open_cms_locate (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * clean_path) static
Definition at line 21 of file open_manager.c.
References brix_pending_insert(), brix_pending_remove(), c, brix_ctx_t::cms_wait_streamid, brix_ctx_recv_t::cur_streamid, ngx_brix_cms_next_streamid(), ngx_brix_cms_send_locate(), brix_ctx_t::recv, brix_ctx_t::state, XRD_ST_REQ_HEADER, and XRD_ST_WAITING_CMS.
Referenced by brix_open_manager_redirect().
brix_open_manager_redirect()
ngx_int_t brix_open_manager_redirect (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, int is_write, const char * clean_path)
Definition at line 51 of file open_manager.c.
References brix_find_manager_map(), brix_manager_tried_exhausted(), BRIX_OP_OPEN_RD, BRIX_OP_OPEN_WR, brix_open_cms_locate(), brix_redir_cache_insert(), brix_redir_cache_lookup(), BRIX_RETURN_ERR, BRIX_RETURN_REDIR, brix_srv_select_or_blacklisted(), c, brix_ctx_recv_t::cur_dlen, brix_manager_map_t::host, kXR_NotFound, op, brix_ctx_recv_t::payload, brix_manager_map_t::port, and brix_ctx_t::recv.
Referenced by brix_handle_open().