nginx-xrootd: src/fs/cache/open_or_fill.c File Reference
open_or_fill.c File Reference
#include "cache_internal.h"
#include "cache_storage.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "fs/vfs/vfs_internal.h"
#include "fs/backend/cache/sd_cache.h"
#include "core/compat/error_mapping.h"
#include <errno.h>
#include <string.h>
Functions
ngx_int_t brix_cache_open_or_fill (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *clean_path, const char *cache_path, uint16_t options, uint16_t mode_bits)
static ngx_thread_pool_t * cache_composed_fill_pool (ngx_stream_brix_srv_conf_t *conf)
static void brix_cache_fill_composed_thread (void *data, ngx_log_t *log)
static void brix_cache_fill_composed_done (ngx_event_t *ev)
ngx_int_t brix_cache_open_fill_offload (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *clean_path, const char *full_path, brix_sd_instance_t *inst, uint16_t options, uint16_t mode_bits)
Function Documentation
brix_cache_fill_composed_done()
static void brix_cache_fill_composed_done (ngx_event_t * ev) static
Definition at line 158 of file open_or_fill.c.
References brix_aio_restore_request(), brix_aio_resume(), brix_kxr_from_errno(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OPEN_RD, brix_open_resolved_file(), brix_send_error(), c, brix_cache_fill_t::c, brix_cache_fill_t::cache_path, brix_cache_fill_t::clean_path, brix_cache_fill_t::conf, brix_cache_fill_t::ctx, kXR_ServerError, brix_cache_fill_t::mode_bits, brix_cache_fill_t::options, brix_open_request_t::resolved, brix_cache_fill_t::result, brix_ctx_t::state, brix_cache_fill_t::streamid, brix_cache_fill_t::sys_errno, and XRD_ST_SENDING.
Referenced by brix_cache_open_fill_offload().
brix_cache_fill_composed_thread()
static void brix_cache_fill_composed_thread (void * data, ngx_log_t * log) static
Definition at line 141 of file open_or_fill.c.
References brix_sd_cache_fill_key(), brix_vfs_export_relative_root(), brix_cache_fill_t::cache_path, brix_cache_fill_t::conf, key, log, brix_cache_fill_t::result, brix_cache_fill_t::source_inst, and brix_cache_fill_t::sys_errno.
Referenced by brix_cache_open_fill_offload().
brix_cache_open_fill_offload()
ngx_int_t brix_cache_open_fill_offload (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * clean_path, const char * full_path, brix_sd_instance_t * inst, uint16_t options, uint16_t mode_bits)
Definition at line 210 of file open_or_fill.c.
References brix_cache_fill_composed_done(), brix_cache_fill_composed_thread(), BRIX_OP_OPEN_RD, BRIX_RETURN_ERR, c, brix_cache_fill_t::c, cache_composed_fill_pool(), brix_cache_fill_t::cache_path, brix_cache_fill_t::clean_path, brix_cache_fill_t::conf, brix_cache_fill_t::ctx, brix_ctx_recv_t::cur_streamid, kXR_ServerError, brix_cache_fill_t::mode_bits, brix_cache_fill_t::options, brix_ctx_t::recv, brix_cache_fill_t::source_inst, brix_ctx_t::state, brix_cache_fill_t::streamid, and XRD_ST_AIO.
Referenced by brix_open_try_cache_offload().
brix_cache_open_or_fill()
ngx_int_t brix_cache_open_or_fill (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * clean_path, const char * cache_path, uint16_t options, uint16_t mode_bits)
Definition at line 18 of file open_or_fill.c.
References brix_cache_append_suffix(), brix_cache_fill_done(), brix_cache_fill_thread(), BRIX_CACHE_LOCK_SUFFIX, BRIX_CACHE_PART_SUFFIX, brix_cache_ready(), BRIX_OP_OPEN_RD, brix_open_resolved_file(), BRIX_RETURN_ERR, brix_sd_backend_name(), brix_send_error(), brix_vfs_backend_resolve(), c, brix_cache_fill_t::c, brix_cache_fill_t::cache_path, brix_cache_fill_t::clean_path, brix_cache_fill_t::conf, brix_cache_fill_t::ctx, brix_ctx_recv_t::cur_streamid, kXR_ArgTooLong, kXR_IOError, kXR_ServerError, kXR_Unsupported, brix_cache_fill_t::lock_path, brix_cache_fill_t::mode_bits, brix_cache_fill_t::options, brix_cache_fill_t::part_path, brix_ctx_t::recv, brix_open_request_t::resolved, brix_cache_fill_t::source_inst, brix_ctx_t::state, brix_cache_fill_t::streamid, and XRD_ST_AIO.
Referenced by brix_open_cached_read().
cache_composed_fill_pool()
static ngx_thread_pool_t * cache_composed_fill_pool (ngx_stream_brix_srv_conf_t * conf) static
Definition at line 121 of file open_or_fill.c.
Referenced by brix_cache_open_fill_offload().