nginx-xrootd: src/protocols/root/read/open_tpc.c File Reference
open_tpc.c File Reference
#include "open_internal.h"
#include "protocols/root/path/op_path.h"
#include "net/manager/registry.h"
#include <string.h>
Functions
static ngx_int_t tpc_handle_dest (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const brix_tpc_params_t *tpc, uint16_t options, uint16_t mode_bits)
static ngx_int_t tpc_handle_source (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const brix_tpc_params_t *tpc)
ngx_int_t brix_open_handle_tpc (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, int is_write, uint16_t options, uint16_t mode_bits)
Function Documentation
brix_open_handle_tpc()
ngx_int_t brix_open_handle_tpc (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, int is_write, uint16_t options, uint16_t mode_bits)
Definition at line 187 of file open_tpc.c.
References BRIX_MAX_PATH, brix_tpc_parse_opaque(), c, brix_ctx_recv_t::cur_dlen, brix_tpc_params_t::has_dst, brix_tpc_params_t::has_key, brix_tpc_params_t::has_org, brix_tpc_params_t::has_src, open_extract_opaque(), brix_ctx_recv_t::payload, brix_ctx_t::recv, brix_tpc_params_t::src_host, tpc_handle_dest(), and tpc_handle_source().
Referenced by brix_handle_open().
tpc_handle_dest()
static ngx_int_t tpc_handle_dest (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const brix_tpc_params_t * tpc, uint16_t options, uint16_t mode_bits) static
Definition at line 31 of file open_tpc.c.
References BRIX_AOP_CREATE, BRIX_AUTH_UPDATE, brix_authz_check(), brix_beneath_full_path(), brix_check_vo_acl_identity(), brix_count_path_depth(), brix_extract_path(), brix_log_access(), brix_mkdir_recursive_policy(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_OPEN_WR, BRIX_RETURN_ERR, brix_send_error(), brix_send_redirect_tpc(), brix_srv_select(), brix_tpc_check_authz(), brix_tpc_generate_key(), BRIX_TPC_KEY_LEN, brix_tpc_key_register(), brix_tpc_prepare_pull(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_t::identity, kXR_ArgInvalid, kXR_fsReadOnly, kXR_mkpath, kXR_NotAuthorized, kXR_Overloaded, PATH_MAX, brix_ctx_recv_t::payload, brix_ctx_t::recv, and brix_tpc_params_t::src_path.
Referenced by brix_open_handle_tpc().
tpc_handle_source()
static ngx_int_t tpc_handle_source (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const brix_tpc_params_t * tpc) static
Definition at line 153 of file open_tpc.c.
References BRIX_OP_OPEN_RD, BRIX_RETURN_ERR, brix_tpc_key_consume(), brix_tpc_key_register(), c, brix_tpc_params_t::dst, brix_tpc_params_t::has_dst, brix_tpc_params_t::has_key, brix_tpc_params_t::has_org, brix_tpc_params_t::key, kXR_NotAuthorized, brix_tpc_params_t::org, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by brix_open_handle_tpc().