nginx-xrootd: src/protocols/root/read/open_resolved_file_dispatch.c File Reference
open_resolved_file_dispatch.c File Reference
#include "open.h"
#include "fs/vfs/vfs.h"
#include "protocols/root/path/op_path.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "fs/vfs/vfs_internal.h"
#include "fs/backend/sd.h"
#include "core/ngx_brix_module.h"
#include "fs/backend/csi_tagstore.h"
#include "net/ratelimit/throttle_compat.h"
#include "protocols/root/response/async.h"
#include "net/mirror/stream_wmirror.h"
#include "protocols/root/write/wrts_journal.h"
#include "core/compat/tmp_path.h"
#include "fs/cache/writethrough_metrics.h"
#include "fs/cache/cache_storage.h"
#include "net/manager/registry.h"
#include "net/manager/pending.h"
#include "protocols/root/session/registry.h"
#include "core/compat/codec_core.h"
#include "protocols/root/protocol/open_flags.h"
#include "observability/sesslog/sesslog_ngx.h"
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include "open_resolved_file_internal.h"
Functions
static ngx_int_t brix_open_dispatch_staged (brix_open_args_t *a, brix_vfs_ctx_t *vctx, brix_sd_instance_t *sd)
static brix_sd_instance_t * brix_open_select_sd_inst (brix_open_args_t *a)
static void brix_open_build_cred_ctx (brix_open_args_t *a, brix_sd_instance_t *sd_inst, brix_vfs_ctx_t *cred_vctx)
int brix_open_write_needs_staged (brix_open_args_t *a, brix_sd_instance_t *sd_inst)
static ngx_int_t brix_open_dispatch_driver (brix_open_args_t *a, brix_sd_instance_t *sd_inst, ngx_int_t *out_failed, ngx_int_t *out_rc)
ngx_int_t brix_open_dispatch_open (brix_open_args_t *a)
Function Documentation
brix_open_build_cred_ctx()
static void brix_open_build_cred_ctx (brix_open_args_t * a, brix_sd_instance_t * sd_inst, brix_vfs_ctx_t * cred_vctx) static
Definition at line 129 of file open_resolved_file_dispatch.c.
References BRIX_PROTO_ROOT, brix_root_vfs_bind_deleg(), brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_bind_backend_mint(), brix_vfs_ctx_init(), c, brix_open_args_t::c, brix_open_args_t::conf, brix_open_args_t::ctx, brix_ctx_t::identity, brix_vfs_ctx_t::pool, brix_open_args_t::resolved, and brix_vfs_ctx_t::sd.
Referenced by brix_open_dispatch_driver().
brix_open_dispatch_driver()
static ngx_int_t brix_open_dispatch_driver (brix_open_args_t * a, brix_sd_instance_t * sd_inst, ngx_int_t * out_failed, ngx_int_t * out_rc) static
Definition at line 186 of file open_resolved_file_dispatch.c.
References brix_open_build_cred_ctx(), brix_open_dispatch_staged(), brix_open_resolved_via_driver(), brix_open_write_needs_staged(), brix_vfs_export_relative_root(), brix_open_args_t::conf, brix_open_args_t::driver_backed, and brix_open_args_t::resolved.
Referenced by brix_open_dispatch_open().
brix_open_dispatch_open()
ngx_int_t brix_open_dispatch_open (brix_open_args_t * a)
Definition at line 229 of file open_resolved_file_dispatch.c.
References brix_open_dispatch_driver(), brix_open_map_open_error(), brix_open_posix_dispatch(), brix_open_select_sd_inst(), c, brix_open_args_t::c, brix_open_args_t::ctx, brix_open_args_t::driver_backed, brix_open_args_t::from_cache, brix_open_args_t::is_write, brix_open_args_t::resolved, brix_open_args_t::use_resume, and brix_open_args_t::wt_via_stage.
Referenced by brix_open_resolved_file().
brix_open_dispatch_staged()
static ngx_int_t brix_open_dispatch_staged (brix_open_args_t * a, brix_vfs_ctx_t * vctx, brix_sd_instance_t * sd) static
Definition at line 61 of file open_resolved_file_dispatch.c.
References brix_open_map_open_error(), BRIX_VFS_O_TRUNC, brix_vfs_writer_open(), c, brix_open_args_t::c, brix_open_args_t::conf, brix_open_args_t::create_mode, brix_open_args_t::ctx, brix_open_args_t::driver_backed, brix_open_args_t::fd, brix_ctx_t::files, brix_open_args_t::idx, brix_open_args_t::is_write, brix_open_args_t::resolved, brix_vfs_ctx_t::sd, brix_open_args_t::st, brix_file_t::staged_committed, and brix_file_t::writer.
Referenced by brix_open_dispatch_driver().
brix_open_select_sd_inst()
static brix_sd_instance_t * brix_open_select_sd_inst (brix_open_args_t * a) static
Definition at line 102 of file open_resolved_file_dispatch.c.
References brix_cache_wt_stage_sd_inst(), brix_vfs_backend_resolve(), brix_open_args_t::c, brix_open_args_t::conf, brix_open_args_t::from_cache, brix_open_args_t::is_write, brix_open_args_t::use_resume, and brix_open_args_t::wt_via_stage.
Referenced by brix_open_dispatch_open().
brix_open_write_needs_staged()
int brix_open_write_needs_staged (brix_open_args_t * a, brix_sd_instance_t * sd_inst)
Definition at line 164 of file open_resolved_file_dispatch.c.
References BRIX_SD_CAP_RANDOM_WRITE, brix_sd_caps(), brix_vfs_ns_leaf(), and brix_open_args_t::is_write.
Referenced by brix_open_dispatch_driver(), and brix_open_resolved_file().