nginx-xrootd: src/fs/cache/open.c File Reference
open.c File Reference
#include "open.h"
#include "cache_internal.h"
#include "cache_storage.h"
#include "meta.h"
#include "fs/vfs/vfs_internal.h"
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Functions
static ngx_int_t brix_cache_path_args_valid (const char *cache_root_canon, const char *root_canon, const char *resolved, const char *out, size_t outsz)
static const char * brix_cache_export_suffix (const char *root_canon, const char *resolved)
ngx_int_t brix_cache_path_for_resolved (const char *cache_root_canon, const char *root_canon, const char *resolved, char *out, size_t outsz)
static ngx_int_t brix_cache_validate_meta (const char *cache_path, const struct stat *st, ngx_log_t *log)
static ngx_int_t brix_cache_open_declined (const brix_vfs_ctx_t *ctx, ngx_uint_t flags)
static ngx_int_t brix_cache_hit_fresh (const brix_vfs_ctx_t *ctx, brix_sd_instance_t *inst, const char *key, const char *cache_path)
static ngx_int_t brix_cache_open_adopt (brix_vfs_ctx_t *ctx, brix_sd_instance_t *inst, const char *key, brix_vfs_file_t **fh_out)
ngx_int_t brix_cache_open (brix_vfs_ctx_t *ctx, ngx_uint_t flags, brix_vfs_file_t **fh_out)
ngx_int_t brix_cache_record_access (const char *cache_path, size_t bytes, ngx_log_t *log)
Function Documentation
brix_cache_export_suffix()
static const char * brix_cache_export_suffix (const char * root_canon, const char * resolved) static
Definition at line 69 of file open.c.
Referenced by brix_cache_path_for_resolved().
brix_cache_hit_fresh()
static ngx_int_t brix_cache_hit_fresh (const brix_vfs_ctx_t * ctx, brix_sd_instance_t * inst, const char * key, const char * cache_path) static
Definition at line 200 of file open.c.
References brix_cache_sidecar_path(), brix_cache_state_root_by_root(), brix_cache_validate_meta(), brix_vfs_ctx_t::cache_root_canon, brix_sd_stat_t::is_reg, key, brix_vfs_ctx_t::log, brix_sd_stat_t::mtime, PATH_MAX, brix_sd_stat_t::size, and stat().
Referenced by brix_cache_open().
brix_cache_open()
ngx_int_t brix_cache_open (brix_vfs_ctx_t * ctx, ngx_uint_t flags, brix_vfs_file_t ** fh_out)
Definition at line 284 of file open.c.
References brix_cache_hit_fresh(), brix_cache_open_adopt(), brix_cache_open_declined(), brix_cache_path_for_resolved(), brix_cache_storage_by_root(), brix_vfs_ctx_path(), brix_vfs_ctx_t::cache_root_canon, key, PATH_MAX, and brix_vfs_ctx_t::root_canon.
Referenced by brix_vfs_open_try_cache().
brix_cache_open_adopt()
static ngx_int_t brix_cache_open_adopt (brix_vfs_ctx_t * ctx, brix_sd_instance_t * inst, const char * key, brix_vfs_file_t ** fh_out) static
Definition at line 249 of file open.c.
References BRIX_SD_O_READ, brix_vfs_adopt_obj(), and key.
Referenced by brix_cache_open().
brix_cache_open_declined()
static ngx_int_t brix_cache_open_declined (const brix_vfs_ctx_t * ctx, ngx_uint_t flags) static
Definition at line 178 of file open.c.
References BRIX_VFS_O_APPEND, BRIX_VFS_O_CREATE, BRIX_VFS_O_NOCACHE, BRIX_VFS_O_TRUNC, BRIX_VFS_O_WRITE, brix_vfs_ctx_t::cache_enabled, and brix_vfs_ctx_t::cache_root_canon.
Referenced by brix_cache_open().
brix_cache_path_args_valid()
static ngx_int_t brix_cache_path_args_valid (const char * cache_root_canon, const char * root_canon, const char * resolved, const char * out, size_t outsz) static
Definition at line 49 of file open.c.
Referenced by brix_cache_path_for_resolved().
brix_cache_path_for_resolved()
ngx_int_t brix_cache_path_for_resolved (const char * cache_root_canon, const char * root_canon, const char * resolved, char * out, size_t outsz)
Definition at line 102 of file open.c.
References brix_cache_export_suffix(), brix_cache_path_args_valid(), and ngx_memcpy.
Referenced by brix_cache_open(), and brix_cache_state_path().
brix_cache_record_access()
ngx_int_t brix_cache_record_access (const char * cache_path, size_t bytes, ngx_log_t * log)
Definition at line 347 of file open.c.
References log.
Referenced by get_serve_range(), and serve_record_body_accounting().
brix_cache_validate_meta()
static ngx_int_t brix_cache_validate_meta (const char * cache_path, const struct stat * st, ngx_log_t * log) static
Definition at line 148 of file open.c.
References brix_cache_meta_read(), log, brix_cache_meta_t::mtime, and brix_cache_meta_t::size.
Referenced by brix_cache_hit_fresh().