nginx-xrootd: src/protocols/root/read/open_resolved_file.c File Reference
open_resolved_file.c File Reference
#include "open.h"
#include "fs/vfs/vfs.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "fs/vfs/vfs_internal.h"
#include "fs/backend/sd.h"
#include "core/ngx_brix_module.h"
#include "fs/backend/csi_tagstore.h"
#include "net/ratelimit/throttle_compat.h"
#include "protocols/root/response/async.h"
#include "net/mirror/stream_wmirror.h"
#include "protocols/root/write/wrts_journal.h"
#include "core/compat/tmp_path.h"
#include "fs/cache/writethrough_metrics.h"
#include "fs/cache/cache_storage.h"
#include "net/manager/registry.h"
#include "net/manager/pending.h"
#include "protocols/root/session/registry.h"
#include "core/compat/codec_core.h"
#include "protocols/root/protocol/open_flags.h"
#include "observability/sesslog/sesslog_ngx.h"
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
Macros
#define BRIX_RECALL_WAIT_SECS 10
Functions
static int brix_open_probe (ngx_log_t *log, const char *root, const char *abs, int nofollow, brix_vfs_stat_t *vst)
static const char * brix_open_logical (const char *abs, const char *root)
static int brix_open_oflags_to_sd (int oflags, int is_readable, int is_write)
static ngx_int_t brix_open_resolved_via_driver (brix_sd_instance_t *sd, const char *logical, int oflags, int is_readable, int is_write, mode_t create_mode, brix_file_t *fh, int *out_fd, struct stat *st)
static ngx_int_t brix_open_attach_csi (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *resolved, int idx, int fd, const struct stat *st, ngx_flag_t is_write)
static ngx_int_t brix_open_apply_throttle (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *resolved, int idx, int fd, ngx_flag_t is_write)
static void brix_open_decide_writethrough (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *resolved, uint16_t options, int idx, mode_t create_mode, ngx_flag_t is_write, ngx_flag_t wt_via_stage)
static void brix_open_register_monitor (brix_ctx_t *ctx, const char *resolved, int idx, ngx_flag_t is_write)
static void brix_open_build_retstat (brix_ctx_t *ctx, int idx, int fd, struct stat *st, ngx_flag_t *want_stat, char *statbuf, size_t statbuf_sz)
static ngx_int_t brix_open_set_handle_path (brix_ctx_t *ctx, ngx_connection_t *c, int idx, const char *resolved, const char *posc_temp_path, ngx_flag_t stage, ngx_flag_t use_resume)
static ngx_int_t brix_open_validate_fd (brix_ctx_t *ctx, ngx_connection_t *c, const char *resolved, int fd, struct stat *st, ngx_flag_t is_write, ngx_flag_t driver_backed)
static ngx_int_t brix_open_check_write_target (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *resolved, ngx_flag_t is_write)
static ngx_int_t brix_open_stage_backpressure (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *resolved, ngx_flag_t is_write)
static ngx_int_t brix_open_check_exclusive_create (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *resolved, ngx_flag_t stage, uint16_t options)
static ngx_int_t brix_open_build_stage_temp (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *resolved, ngx_flag_t use_resume, ngx_flag_t use_posc, char *posc_temp_path, size_t posc_temp_path_sz)
ngx_int_t brix_open_resolved_file (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *resolved, uint16_t options, uint16_t mode_bits, ngx_flag_t is_write, uint8_t codec)
Macro Definition Documentation
BRIX_RECALL_WAIT_SECS
#define BRIX_RECALL_WAIT_SECS 10
Definition at line 28 of file open_resolved_file.c.
Function Documentation
brix_open_apply_throttle()
static ngx_int_t brix_open_apply_throttle (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * resolved, int idx, int fd, ngx_flag_t is_write) static
Definition at line 228 of file open_resolved_file.c.
References brix_csi_close(), BRIX_OP_OPEN_RD, BRIX_OP_OPEN_WR, BRIX_RETURN_ERR, brix_throttle_open_inc(), c, close(), brix_file_t::csi, brix_ctx_login_t::dn, brix_file_t::fd, brix_ctx_t::files, kXR_Overloaded, brix_ctx_t::login, brix_throttle_conf_t::max_open_files, brix_ctx_throttle_t::open_held, ngx_stream_brix_srv_conf_t::throttle, brix_ctx_t::throttle, and brix_throttle_conf_t::zone.
Referenced by brix_open_resolved_file().
brix_open_attach_csi()
static ngx_int_t brix_open_attach_csi (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * resolved, int idx, int fd, const struct stat * st, ngx_flag_t is_write) static
Definition at line 183 of file open_resolved_file.c.
References brix_csi_conf_t::block, brix_csi_close(), BRIX_CSI_NOTAGS, BRIX_CSI_OK, brix_csi_open(), BRIX_OP_OPEN_RD, BRIX_RETURN_ERR, c, close(), ngx_stream_brix_srv_conf_t::csi, brix_file_t::csi, brix_csi_conf_t::enable, brix_file_t::fd, brix_ctx_t::files, kXR_ChkSumErr, brix_csi_conf_t::require, brix_csi_conf_t::trust_fs, and brix_csi_t::trust_fs.
Referenced by brix_open_resolved_file().
brix_open_build_retstat()
static void brix_open_build_retstat (brix_ctx_t * ctx, int idx, int fd, struct stat * st, ngx_flag_t * want_stat, char * statbuf, size_t statbuf_sz) static
Definition at line 351 of file open_resolved_file.c.
References brix_ctx_t::files, brix_file_t::from_cache, fstat(), kXR_cachersp, kXR_readable, and kXR_writable.
Referenced by brix_open_resolved_file().
brix_open_build_stage_temp()
static ngx_int_t brix_open_build_stage_temp (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * resolved, ngx_flag_t use_resume, ngx_flag_t use_posc, char * posc_temp_path, size_t posc_temp_path_sz) static
Definition at line 588 of file open_resolved_file.c.
References brix_make_resume_path(), brix_make_tmp_path(), BRIX_OP_OPEN_WR, BRIX_RETURN_ERR, c, brix_ctx_login_t::dn, kXR_ServerError, brix_ctx_t::login, and ngx_stream_brix_srv_conf_t::upload_stage_dir_canon.
Referenced by brix_open_resolved_file().
brix_open_check_exclusive_create()
static ngx_int_t brix_open_check_exclusive_create (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * resolved, ngx_flag_t stage, uint16_t options) static
Definition at line 563 of file open_resolved_file.c.
References BRIX_OP_OPEN_WR, brix_open_probe(), BRIX_RETURN_ERR, c, ngx_stream_brix_srv_conf_t::common, kXR_delete, kXR_ItExists, kXR_new, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by brix_open_resolved_file().
brix_open_check_write_target()
static ngx_int_t brix_open_check_write_target (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * resolved, ngx_flag_t is_write) static
Definition at line 483 of file open_resolved_file.c.
References BRIX_OP_OPEN_WR, brix_open_probe(), BRIX_RETURN_ERR, c, ngx_stream_brix_srv_conf_t::common, brix_vfs_stat_t::is_directory, kXR_isDirectory, kXR_NotAuthorized, brix_vfs_stat_t::mode, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by brix_open_resolved_file().
brix_open_decide_writethrough()
static void brix_open_decide_writethrough (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * resolved, uint16_t options, int idx, mode_t create_mode, ngx_flag_t is_write, ngx_flag_t wt_via_stage) static
Definition at line 290 of file open_resolved_file.c.
References brix_sanitize_log_string(), BRIX_WT_DECISION_ALLOW_SYNC, BRIX_WT_DECISION_DENY, c, brix_wt_conf_t::decision, brix_wt_conf_t::enable, brix_ctx_t::files, brix_wt_decision_cfg_t::fn, ngx_stream_brix_srv_conf_t::wt, brix_file_t::wt_bytes_written, brix_file_t::wt_dirty_offset, brix_file_t::wt_enabled, brix_file_t::wt_flush_pending, brix_file_t::wt_flush_task, brix_file_t::wt_mode_bits, and brix_file_t::wt_policy.
Referenced by brix_open_resolved_file().
brix_open_logical()
static const char * brix_open_logical (const char * abs, const char * root) static
Definition at line 53 of file open_resolved_file.c.
Referenced by brix_open_resolved_file().
brix_open_oflags_to_sd()
static int brix_open_oflags_to_sd (int oflags, int is_readable, int is_write) static
Definition at line 71 of file open_resolved_file.c.
References BRIX_SD_O_APPEND, BRIX_SD_O_CREATE, BRIX_SD_O_EXCL, BRIX_SD_O_READ, BRIX_SD_O_TRUNC, and BRIX_SD_O_WRITE.
Referenced by brix_open_resolved_via_driver().
brix_open_probe()
static int brix_open_probe (ngx_log_t * log, const char * root, const char * abs, int nofollow, brix_vfs_stat_t * vst) static
Definition at line 37 of file open_resolved_file.c.
References BRIX_PROTO_ROOT, brix_vfs_ctx_init(), brix_vfs_probe(), and log.
Referenced by brix_open_check_exclusive_create(), brix_open_check_write_target(), and brix_open_resolved_file().
brix_open_register_monitor()
static void brix_open_register_monitor (brix_ctx_t * ctx, const char * resolved, int idx, ngx_flag_t is_write) static
Definition at line 331 of file open_resolved_file.c.
References brix_transfer_slot_alloc(), BRIX_XFER_DIR_READ, BRIX_XFER_DIR_WRITE, BRIX_XFER_PROTO_ROOT, brix_file_t::dashboard_slot, brix_ctx_login_t::dn, brix_ctx_t::files, brix_ctx_t::login, ngx_brix_dashboard_shm_zone, brix_ctx_login_t::peer_ip, and brix_ctx_login_t::sessid.
Referenced by brix_open_resolved_file().
brix_open_resolved_file()
ngx_int_t brix_open_resolved_file (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * resolved, uint16_t options, uint16_t mode_bits, ngx_flag_t is_write, uint8_t codec)
Definition at line 647 of file open_resolved_file.c.
References brix_alloc_fhandle(), brix_apply_parent_group_policy_fd(), brix_build_resp_hdr(), brix_cache_wt_stage_sd_inst(), BRIX_CODEC_IDENTITY, brix_free_fhandle(), BRIX_INLINE_CMP_MAGIC, brix_log_access(), BRIX_OP_OK, BRIX_OP_OPEN_RD, BRIX_OP_OPEN_WR, brix_open_apply_throttle(), brix_open_attach_csi(), brix_open_build_retstat(), brix_open_build_stage_temp(), brix_open_check_exclusive_create(), brix_open_check_write_target(), brix_open_decide_writethrough(), brix_open_logical(), brix_open_options_to_posix(), brix_open_probe(), brix_open_register_monitor(), brix_open_resolved_via_driver(), brix_open_set_handle_path(), brix_open_stage_backpressure(), brix_open_validate_fd(), brix_queue_response(), BRIX_RECALL_WAIT_SECS, BRIX_RETURN_ERR, brix_sanitize_log_string(), brix_send_attn_asynresp(), brix_send_wait(), BRIX_SESS_MODE_READ, BRIX_SESS_MODE_WRITE, brix_sess_xfer_start(), brix_session_handle_publish(), brix_stream_wmirror_on_open(), brix_vfs_backend_resolve(), brix_vfs_export_relative_root(), brix_vfs_open_fd_at(), brix_wrts_open(), BRIX_WT_DECISION_DENY, brix_file_t::bytes_read, brix_file_t::bytes_written, c, ngx_stream_brix_srv_conf_t::cache, ngx_stream_brix_srv_conf_t::cache_root, brix_file_t::cached_size, ngx_stream_brix_srv_conf_t::caps, ngx_stream_brix_srv_conf_t::common, ServerOpenBody::cpsize, ServerOpenBody::cptype, brix_ctx_recv_t::cur_streamid, brix_file_t::dashboard_slot, brix_file_t::device, brix_wt_conf_t::enable, brix_file_t::fd, ServerOpenBody::fhandle, brix_ctx_t::files, brix_file_t::from_cache, ngx_stream_brix_srv_conf_t::group_rules, brix_file_t::inode, brix_ctx_t::is_bound, brix_vfs_stat_t::is_directory, brix_file_t::is_regular, brix_vfs_stat_t::is_regular, kXR_delete, kXR_IOError, kXR_isDirectory, kXR_ItExists, kXR_new, kXR_NotAuthorized, kXR_NotFound, kXR_ok, kXR_posc, kXR_retstat, kXR_ServerError, brix_ctx_t::login, ngx_memcpy, ngx_stream_brix_module, open(), brix_file_t::open_time, PATH_MAX, brix_ctx_t::prepare, brix_file_t::read_ahead_end, brix_file_t::read_codec, brix_file_t::read_last_end, brix_file_t::readable, brix_node_caps_conf_t::recover_writes, brix_ctx_t::recv, ngx_http_brix_shared_conf_t::root_canon, ngx_stream_brix_srv_conf_t::rootfd, brix_ctx_t::sess, brix_file_t::sess_xfer, brix_ctx_login_t::sessid, brix_ctx_prepare_t::stage_async_active, brix_ctx_prepare_t::stage_async_streamid, stat(), ngx_stream_brix_srv_conf_t::upload_resume, ngx_stream_brix_srv_conf_t::upload_stage_dir_canon, brix_file_t::writable, brix_file_t::write_codec, brix_file_t::wrts_count, brix_file_t::wrts_enabled, brix_file_t::wrts_gen, brix_file_t::wrts_head, ngx_stream_brix_srv_conf_t::wt, brix_file_t::wt_bytes_written, brix_file_t::wt_dirty_offset, brix_file_t::wt_enabled, brix_file_t::wt_flush_pending, brix_file_t::wt_flush_task, brix_file_t::wt_mode_bits, brix_file_t::wt_policy, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_cache_fill_composed_done(), brix_cache_fill_done(), brix_cache_open_or_fill(), brix_handle_open(), brix_open_cached_read(), and stage_waiter_deliver_one().
brix_open_resolved_via_driver()
static ngx_int_t brix_open_resolved_via_driver (brix_sd_instance_t * sd, const char * logical, int oflags, int is_readable, int is_write, mode_t create_mode, brix_file_t * fh, int * out_fd, struct stat * st) static
Definition at line 94 of file open_resolved_file.c.
References brix_open_oflags_to_sd(), fstat(), brix_file_t::sd_obj, and stat().
Referenced by brix_open_resolved_file().
brix_open_set_handle_path()
static ngx_int_t brix_open_set_handle_path (brix_ctx_t * ctx, ngx_connection_t * c, int idx, const char * resolved, const char * posc_temp_path, ngx_flag_t stage, ngx_flag_t use_resume) static
Definition at line 393 of file open_resolved_file.c.
References brix_free_fhandle(), brix_set_fhandle_path(), c, brix_ctx_t::files, brix_file_t::is_resume, and brix_file_t::posc_final_path.
Referenced by brix_open_resolved_file().
brix_open_stage_backpressure()
static ngx_int_t brix_open_stage_backpressure (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * resolved, ngx_flag_t is_write) static
Definition at line 524 of file open_resolved_file.c.
References brix_log_access(), brix_metric_wt_stage_throttled(), BRIX_OP_OPEN_WR, BRIX_RETURN_ERR, brix_send_wait(), BRIX_WT_ADMIT_ALLOW, BRIX_WT_ADMIT_REJECT, BRIX_WT_ADMIT_WAIT, brix_wt_stage_admit(), BRIX_WT_STAGE_WAIT_SECS, c, brix_wt_conf_t::enable, kXR_Overloaded, and ngx_stream_brix_srv_conf_t::wt.
Referenced by brix_open_resolved_file().
brix_open_validate_fd()
static ngx_int_t brix_open_validate_fd (brix_ctx_t * ctx, ngx_connection_t * c, const char * resolved, int fd, struct stat * st, ngx_flag_t is_write, ngx_flag_t driver_backed) static
Definition at line 428 of file open_resolved_file.c.
References BRIX_OP_OPEN_RD, BRIX_OP_OPEN_WR, BRIX_RETURN_ERR, c, close(), fstat(), kXR_IOError, and kXR_isDirectory.
Referenced by brix_open_resolved_file().