nginx-xrootd: src/protocols/root/read/open_resolved_file_internal.h File Reference
open_resolved_file_internal.h File Reference
#include "open.h"
#include "fs/vfs/vfs.h"
#include "fs/backend/sd.h"
#include <sys/stat.h>
#include <limits.h>
Data Structures
struct brix_open_args_t
Functions
ngx_int_t brix_open_stage_preflight (brix_open_args_t *a)
ngx_int_t brix_open_resolved_via_driver (brix_open_args_t *a, brix_vfs_ctx_t *vctx, brix_sd_instance_t *sd, const char *logical)
ngx_int_t brix_open_map_open_error (brix_ctx_t *ctx, ngx_connection_t *c, const char *resolved, int err, ngx_flag_t is_write)
int brix_open_posix_dispatch (brix_open_args_t *a)
ngx_int_t brix_open_dispatch_open (brix_open_args_t *a)
int brix_open_write_needs_staged (brix_open_args_t *a, brix_sd_instance_t *sd_inst)
ngx_int_t brix_open_finalize_handle (brix_open_args_t *a)
void brix_open_build_retstat (brix_open_args_t *a)
Function Documentation
brix_open_build_retstat()
void brix_open_build_retstat (brix_open_args_t * a)
Definition at line 66 of file open_resolved_file.c.
References brix_open_args_t::ctx, brix_open_args_t::fd, brix_ctx_t::files, brix_file_t::from_cache, fstat(), brix_open_args_t::idx, kXR_cachersp, kXR_readable, kXR_writable, brix_open_args_t::st, stat(), brix_open_args_t::statbuf, and brix_open_args_t::want_stat.
Referenced by brix_open_finalize_handle().
brix_open_dispatch_open()
ngx_int_t brix_open_dispatch_open (brix_open_args_t * a)
Definition at line 229 of file open_resolved_file_dispatch.c.
References brix_open_dispatch_driver(), brix_open_map_open_error(), brix_open_posix_dispatch(), brix_open_select_sd_inst(), c, brix_open_args_t::c, brix_open_args_t::ctx, brix_open_args_t::driver_backed, brix_open_args_t::from_cache, brix_open_args_t::is_write, brix_open_args_t::resolved, brix_open_args_t::use_resume, and brix_open_args_t::wt_via_stage.
Referenced by brix_open_resolved_file().
brix_open_finalize_handle()
ngx_int_t brix_open_finalize_handle (brix_open_args_t * a)
Definition at line 358 of file open_resolved_file_finalize.c.
References brix_apply_parent_group_policy_fd(), brix_open_apply_throttle(), brix_open_attach_csi(), brix_open_build_retstat(), brix_open_decide_writethrough(), brix_open_init_handle(), brix_open_register_monitor(), brix_open_set_handle_path(), brix_open_validate_fd(), brix_sanitize_log_string(), c, brix_open_args_t::c, brix_open_args_t::conf, brix_open_args_t::ctx, brix_open_args_t::fd, brix_open_args_t::idx, brix_open_args_t::is_write, brix_open_args_t::resolved, and brix_open_args_t::want_stat.
Referenced by brix_open_resolved_file().
brix_open_map_open_error()
ngx_int_t brix_open_map_open_error (brix_ctx_t * ctx, ngx_connection_t * c, const char * resolved, int err, ngx_flag_t is_write)
Definition at line 217 of file open_resolved_file_open.c.
References brix_log_access(), BRIX_OP_OPEN_RD, BRIX_OP_OPEN_WR, BRIX_RECALL_WAIT_SECS, BRIX_RETURN_ERR, brix_send_wait(), c, kXR_FileLocked, kXR_IOError, kXR_isDirectory, kXR_ItExists, kXR_NotAuthorized, and kXR_NotFound.
Referenced by brix_open_dispatch_open(), and brix_open_dispatch_staged().
brix_open_posix_dispatch()
int brix_open_posix_dispatch (brix_open_args_t * a)
Definition at line 283 of file open_resolved_file_open.c.
References brix_open_logical(), brix_vfs_open_fd_at(), brix_open_args_t::conf, brix_open_args_t::create_mode, brix_open_args_t::fd, brix_open_args_t::from_cache, brix_open_args_t::oflags, open(), brix_open_args_t::posc_temp_path, brix_open_args_t::resolved, brix_open_args_t::stage, and brix_open_args_t::use_resume.
Referenced by brix_open_dispatch_open().
brix_open_resolved_via_driver()
ngx_int_t brix_open_resolved_via_driver (brix_open_args_t * a, brix_vfs_ctx_t * vctx, brix_sd_instance_t * sd, const char * logical)
Definition at line 116 of file open_resolved_file_open.c.
References brix_open_oflags_to_sd(), brix_sd_open_maybe_cred(), brix_sd_ucred_wipe(), brix_vfs_backend_cred(), brix_open_args_t::create_mode, brix_open_args_t::ctx, brix_open_args_t::fd, brix_ctx_t::files, fstat(), brix_open_args_t::idx, brix_open_args_t::is_readable, brix_open_args_t::is_write, brix_open_args_t::oflags, brix_file_t::sd_obj, brix_open_args_t::st, and stat().
Referenced by brix_open_dispatch_driver().
brix_open_stage_preflight()
ngx_int_t brix_open_stage_preflight (brix_open_args_t * a)
Definition at line 294 of file open_resolved_file_staging.c.
References BRIX_OP_OPEN_RD, brix_open_build_stage_temp(), brix_open_check_exclusive_create(), brix_open_check_write_target(), brix_open_probe(), brix_open_resume_inplace_decide(), brix_open_stage_backpressure(), BRIX_RETURN_ERR, c, brix_open_args_t::c, brix_open_args_t::conf, brix_open_args_t::ctx, brix_vfs_stat_t::is_directory, brix_open_args_t::is_write, kXR_isDirectory, and brix_open_args_t::resolved.
Referenced by brix_open_resolved_file().
brix_open_write_needs_staged()
int brix_open_write_needs_staged (brix_open_args_t * a, brix_sd_instance_t * sd_inst)
Definition at line 164 of file open_resolved_file_dispatch.c.
References BRIX_SD_CAP_RANDOM_WRITE, brix_sd_caps(), brix_vfs_ns_leaf(), and brix_open_args_t::is_write.
Referenced by brix_open_dispatch_driver(), and brix_open_resolved_file().