nginx-xrootd: src/protocols/root/protocol/open_flags.h File Reference
open_flags.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <fcntl.h>
#include "flags.h"
Macros
#define BRIX_OPEN_WRITE_BITS (kXR_new | kXR_delete | kXR_open_updt | kXR_open_wrto | kXR_open_apnd)
Functions
static int brix_open_options_is_write (uint16_t options)
static uint16_t brix_open_options_build (int write, int force, int posc, int mkpath)
static void brix_open_options_to_posix (uint16_t options, int is_write, int *oflags, int *is_readable)
static int brix_open_force_for_open (int o_flags)
static int brix_open_force_for_create (int o_flags)
Macro Definition Documentation
BRIX_OPEN_WRITE_BITS
#define BRIX_OPEN_WRITE_BITS (kXR_new | kXR_delete | kXR_open_updt | kXR_open_wrto | kXR_open_apnd)
Definition at line 40 of file open_flags.h.
Function Documentation
brix_open_force_for_create()
static int brix_open_force_for_create (int o_flags) inline static
Definition at line 152 of file open_flags.h.
Referenced by xfs_create(), and xfs_create().
brix_open_force_for_open()
static int brix_open_force_for_open (int o_flags) inline static
Definition at line 146 of file open_flags.h.
Referenced by xfs_open(), and xfs_open().
brix_open_options_build()
static uint16_t brix_open_options_build (int write, int force, int posc, int mkpath) inline static
Definition at line 60 of file open_flags.h.
References kXR_delete, kXR_mkpath, kXR_new, kXR_open_read, kXR_open_updt, and kXR_posc.
Referenced by brix_file_open_opaque().
brix_open_options_is_write()
static int brix_open_options_is_write (uint16_t options) inline static
Definition at line 45 of file open_flags.h.
References BRIX_OPEN_WRITE_BITS.
Referenced by brix_handle_open().
brix_open_options_to_posix()
static void brix_open_options_to_posix (uint16_t options, int is_write, int * oflags, int * is_readable) inline static
Definition at line 98 of file open_flags.h.
References kXR_delete, kXR_new, kXR_open_apnd, and kXR_open_updt.
Referenced by brix_open_resolved_file().