nginx-xrootd: src/protocols/root/read/open_resolved_file_finalize.c File Reference
open_resolved_file_finalize.c File Reference
#include "open.h"
#include "fs/vfs/vfs.h"
#include "protocols/root/path/op_path.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "fs/vfs/vfs_internal.h"
#include "fs/backend/sd.h"
#include "core/ngx_brix_module.h"
#include "fs/backend/csi_tagstore.h"
#include "net/ratelimit/throttle_compat.h"
#include "protocols/root/response/async.h"
#include "net/mirror/stream_wmirror.h"
#include "protocols/root/write/wrts_journal.h"
#include "core/compat/tmp_path.h"
#include "fs/cache/writethrough_metrics.h"
#include "fs/cache/cache_storage.h"
#include "net/manager/registry.h"
#include "net/manager/pending.h"
#include "protocols/root/session/registry.h"
#include "core/compat/codec_core.h"
#include "protocols/root/protocol/open_flags.h"
#include "observability/sesslog/sesslog_ngx.h"
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include "open_resolved_file_internal.h"
Functions
static ngx_int_t brix_open_attach_csi (brix_open_args_t *a)
static ngx_int_t brix_open_apply_throttle (brix_open_args_t *a)
static void brix_open_decide_writethrough (brix_open_args_t *a)
static void brix_open_register_monitor (brix_ctx_t *ctx, const char *resolved, int idx, ngx_flag_t is_write)
static ngx_int_t brix_open_set_handle_path (brix_open_args_t *a)
static ngx_int_t brix_open_validate_fd (brix_open_args_t *a)
static void brix_open_init_handle (brix_open_args_t *a)
ngx_int_t brix_open_finalize_handle (brix_open_args_t *a)
Function Documentation
brix_open_apply_throttle()
static ngx_int_t brix_open_apply_throttle (brix_open_args_t * a) static
Definition at line 108 of file open_resolved_file_finalize.c.
References brix_csi_close(), BRIX_OP_OPEN_RD, BRIX_OP_OPEN_WR, BRIX_RETURN_ERR, brix_throttle_open_inc(), c, brix_open_args_t::c, close(), brix_open_args_t::conf, brix_file_t::csi, brix_open_args_t::ctx, brix_ctx_login_t::dn, brix_file_t::fd, brix_open_args_t::fd, brix_ctx_t::files, brix_open_args_t::idx, brix_open_args_t::is_write, kXR_Overloaded, brix_ctx_t::login, brix_ctx_throttle_t::open_held, brix_open_args_t::resolved, and brix_ctx_t::throttle.
Referenced by brix_open_finalize_handle().
brix_open_attach_csi()
static ngx_int_t brix_open_attach_csi (brix_open_args_t * a) static
Definition at line 57 of file open_resolved_file_finalize.c.
References brix_csi_close(), BRIX_CSI_NOTAGS, BRIX_CSI_OK, brix_csi_open(), BRIX_OP_OPEN_RD, BRIX_RETURN_ERR, c, brix_open_args_t::c, close(), brix_open_args_t::conf, brix_file_t::csi, brix_open_args_t::ctx, brix_file_t::fd, brix_open_args_t::fd, brix_ctx_t::files, brix_open_args_t::idx, brix_open_args_t::is_write, kXR_ChkSumErr, brix_open_args_t::resolved, brix_open_args_t::st, stat(), and brix_csi_t::trust_fs.
Referenced by brix_open_finalize_handle().
brix_open_decide_writethrough()
static void brix_open_decide_writethrough (brix_open_args_t * a) static
Definition at line 175 of file open_resolved_file_finalize.c.
References brix_sanitize_log_string(), BRIX_WT_DECISION_ALLOW_SYNC, BRIX_WT_DECISION_DENY, c, brix_open_args_t::c, brix_open_args_t::conf, brix_open_args_t::create_mode, brix_open_args_t::ctx, brix_ctx_t::files, brix_open_args_t::idx, brix_open_args_t::is_write, brix_open_args_t::options, brix_open_args_t::resolved, brix_file_t::wt_bytes_written, brix_file_t::wt_dirty_offset, brix_file_t::wt_enabled, brix_file_t::wt_flush_pending, brix_file_t::wt_flush_task, brix_file_t::wt_mode_bits, brix_file_t::wt_policy, and brix_open_args_t::wt_via_stage.
Referenced by brix_open_finalize_handle().
brix_open_finalize_handle()
ngx_int_t brix_open_finalize_handle (brix_open_args_t * a)
Definition at line 358 of file open_resolved_file_finalize.c.
References brix_apply_parent_group_policy_fd(), brix_open_apply_throttle(), brix_open_attach_csi(), brix_open_build_retstat(), brix_open_decide_writethrough(), brix_open_init_handle(), brix_open_register_monitor(), brix_open_set_handle_path(), brix_open_validate_fd(), brix_sanitize_log_string(), c, brix_open_args_t::c, brix_open_args_t::conf, brix_open_args_t::ctx, brix_open_args_t::fd, brix_open_args_t::idx, brix_open_args_t::is_write, brix_open_args_t::resolved, and brix_open_args_t::want_stat.
Referenced by brix_open_resolved_file().
brix_open_init_handle()
static void brix_open_init_handle (brix_open_args_t * a) static
Definition at line 423 of file open_resolved_file_finalize.c.
References BRIX_CODEC_IDENTITY, brix_wrts_open(), BRIX_WT_DECISION_DENY, c, brix_open_args_t::c, brix_file_t::cached_size, brix_open_args_t::codec, brix_open_args_t::create_mode, brix_open_args_t::ctx, brix_file_t::dashboard_slot, brix_file_t::device, brix_file_t::fd, brix_open_args_t::fd, brix_ctx_t::files, brix_file_t::from_cache, brix_open_args_t::from_cache, brix_open_args_t::idx, brix_file_t::inode, brix_open_args_t::is_readable, brix_file_t::is_regular, brix_open_args_t::is_write, ngx_stream_brix_module, brix_file_t::read_ahead_end, brix_file_t::read_codec, brix_file_t::read_last_end, brix_file_t::readable, brix_open_args_t::st, stat(), brix_file_t::writable, brix_file_t::write_codec, brix_file_t::wrts_count, brix_file_t::wrts_enabled, brix_file_t::wrts_gen, brix_file_t::wrts_head, brix_file_t::wt_bytes_written, brix_file_t::wt_dirty_offset, brix_file_t::wt_enabled, brix_file_t::wt_flush_pending, brix_file_t::wt_flush_task, brix_file_t::wt_mode_bits, and brix_file_t::wt_policy.
Referenced by brix_open_finalize_handle().
brix_open_register_monitor()
static void brix_open_register_monitor (brix_ctx_t * ctx, const char * resolved, int idx, ngx_flag_t is_write) static
Definition at line 223 of file open_resolved_file_finalize.c.
References brix_transfer_slot_alloc(), BRIX_XFER_DIR_READ, BRIX_XFER_DIR_WRITE, BRIX_XFER_PROTO_ROOT, brix_file_t::dashboard_slot, brix_ctx_login_t::dn, brix_ctx_t::files, brix_ctx_t::login, ngx_brix_dashboard_shm_zone, brix_ctx_login_t::peer_ip, and brix_ctx_login_t::sessid.
Referenced by brix_open_finalize_handle().
brix_open_set_handle_path()
static ngx_int_t brix_open_set_handle_path (brix_open_args_t * a) static
Definition at line 245 of file open_resolved_file_finalize.c.
References brix_free_fhandle(), brix_set_fhandle_path(), c, brix_open_args_t::c, brix_open_args_t::ctx, brix_ctx_t::files, brix_open_args_t::idx, brix_file_t::is_resume, brix_file_t::posc_final_path, brix_open_args_t::posc_temp_path, brix_open_args_t::resolved, brix_open_args_t::stage, and brix_open_args_t::use_resume.
Referenced by brix_open_finalize_handle().
brix_open_validate_fd()
static ngx_int_t brix_open_validate_fd (brix_open_args_t * a) static
Definition at line 285 of file open_resolved_file_finalize.c.
References BRIX_OP_OPEN_RD, BRIX_OP_OPEN_WR, BRIX_RETURN_ERR, c, brix_open_args_t::c, close(), brix_open_args_t::ctx, brix_open_args_t::driver_backed, brix_open_args_t::fd, fstat(), brix_open_args_t::is_write, kXR_IOError, kXR_isDirectory, op, brix_open_args_t::resolved, brix_open_args_t::st, and stat().
Referenced by brix_open_finalize_handle().