nginx-xrootd: src/protocols/root/read/open_resolved_file_open.c File Reference
open_resolved_file_open.c File Reference
#include "open.h"
#include "fs/vfs/vfs.h"
#include "protocols/root/path/op_path.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "fs/vfs/vfs_internal.h"
#include "fs/backend/sd.h"
#include "core/ngx_brix_module.h"
#include "fs/backend/csi_tagstore.h"
#include "net/ratelimit/throttle_compat.h"
#include "protocols/root/response/async.h"
#include "net/mirror/stream_wmirror.h"
#include "protocols/root/write/wrts_journal.h"
#include "core/compat/tmp_path.h"
#include "fs/cache/writethrough_metrics.h"
#include "fs/cache/cache_storage.h"
#include "net/manager/registry.h"
#include "net/manager/pending.h"
#include "protocols/root/session/registry.h"
#include "core/compat/codec_core.h"
#include "protocols/root/protocol/open_flags.h"
#include "observability/sesslog/sesslog_ngx.h"
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include "open_resolved_file_internal.h"
Macros
#define BRIX_RECALL_WAIT_SECS 10
Functions
static const char * brix_open_logical (const char *abs, const char *root)
static int brix_open_oflags_to_sd (int oflags, int is_readable, int is_write)
ngx_int_t brix_open_resolved_via_driver (brix_open_args_t *a, brix_vfs_ctx_t *vctx, brix_sd_instance_t *sd, const char *logical)
ngx_int_t brix_open_map_open_error (brix_ctx_t *ctx, ngx_connection_t *c, const char *resolved, int err, ngx_flag_t is_write)
int brix_open_posix_dispatch (brix_open_args_t *a)
Macro Definition Documentation
BRIX_RECALL_WAIT_SECS
#define BRIX_RECALL_WAIT_SECS 10
Definition at line 50 of file open_resolved_file_open.c.
Function Documentation
brix_open_logical()
static const char * brix_open_logical (const char * abs, const char * root) static
Definition at line 58 of file open_resolved_file_open.c.
Referenced by brix_open_posix_dispatch().
brix_open_map_open_error()
ngx_int_t brix_open_map_open_error (brix_ctx_t * ctx, ngx_connection_t * c, const char * resolved, int err, ngx_flag_t is_write)
Definition at line 217 of file open_resolved_file_open.c.
References brix_log_access(), BRIX_OP_OPEN_RD, BRIX_OP_OPEN_WR, BRIX_RECALL_WAIT_SECS, BRIX_RETURN_ERR, brix_send_wait(), c, kXR_FileLocked, kXR_IOError, kXR_isDirectory, kXR_ItExists, kXR_NotAuthorized, and kXR_NotFound.
Referenced by brix_open_dispatch_open(), and brix_open_dispatch_staged().
brix_open_oflags_to_sd()
static int brix_open_oflags_to_sd (int oflags, int is_readable, int is_write) static
Definition at line 76 of file open_resolved_file_open.c.
References BRIX_SD_O_APPEND, BRIX_SD_O_CREATE, BRIX_SD_O_EXCL, BRIX_SD_O_READ, BRIX_SD_O_TRUNC, and BRIX_SD_O_WRITE.
Referenced by brix_open_resolved_via_driver().
brix_open_posix_dispatch()
int brix_open_posix_dispatch (brix_open_args_t * a)
Definition at line 283 of file open_resolved_file_open.c.
References brix_open_logical(), brix_vfs_open_fd_at(), brix_open_args_t::conf, brix_open_args_t::create_mode, brix_open_args_t::fd, brix_open_args_t::from_cache, brix_open_args_t::oflags, open(), brix_open_args_t::posc_temp_path, brix_open_args_t::resolved, brix_open_args_t::stage, and brix_open_args_t::use_resume.
Referenced by brix_open_dispatch_open().
brix_open_resolved_via_driver()
ngx_int_t brix_open_resolved_via_driver (brix_open_args_t * a, brix_vfs_ctx_t * vctx, brix_sd_instance_t * sd, const char * logical)
Definition at line 116 of file open_resolved_file_open.c.
References brix_open_oflags_to_sd(), brix_sd_open_maybe_cred(), brix_sd_ucred_wipe(), brix_vfs_backend_cred(), brix_open_args_t::create_mode, brix_open_args_t::ctx, brix_open_args_t::fd, brix_ctx_t::files, fstat(), brix_open_args_t::idx, brix_open_args_t::is_readable, brix_open_args_t::is_write, brix_open_args_t::oflags, brix_file_t::sd_obj, brix_open_args_t::st, and stat().
Referenced by brix_open_dispatch_driver().