nginx-xrootd: client/lib/protocols/root/ops_meta.c File Reference
ops_meta.c File Reference
#include "brix.h"
#include "protocols/root/protocol/stat_line.h"
#include "protocols/root/protocol/dirlist_fmt.h"
#include <arpa/inet.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct dirlist_args
Functions
static int parse_statinfo (const char *s, brix_statinfo *out)
static int stat_opt (brix_conn *c, const char *path, uint8_t options, brix_statinfo *out, brix_status *st)
int brix_stat (brix_conn *c, const char *path, brix_statinfo *out, brix_status *st)
int brix_lstat (brix_conn *c, const char *path, brix_statinfo *out, brix_status *st)
static int buf_append (uint8_t **buf, size_t *len, size_t *cap, const uint8_t *src, size_t n)
static size_t next_line (const uint8_t *b, size_t len, size_t i, size_t *start, size_t *linelen, int *was_nul)
static int dirent_push (brix_dirent **ents, size_t *count, size_t *cap, const brix_dirent *e)
static int dirlist_accumulate (brix_conn *c, ClientDirlistRequest *req, const char *path, uint8_t **acc_out, size_t *acclen_out, brix_status *st)
static size_t dirlist_skip_dstat_leadin (const uint8_t *acc, size_t acclen, int want_stat)
static int dirlist_parse_entries (const uint8_t *acc, size_t acclen, size_t i, int want_stat, brix_dirent **ents_out, size_t *count_out, brix_status *st)
static int dirlist_once (brix_conn *c, const char *path, int want_stat, brix_dirent **ents_out, size_t *count_out, brix_status *st)
static int dirlist_op (brix_conn *c, void *arg, brix_status *st)
int brix_dirlist (brix_conn *c, const char *path, int want_stat, brix_dirent **ents_out, size_t *count_out, brix_status *st)
Function Documentation
brix_dirlist()
int brix_dirlist (brix_conn * c, const char * path, int want_stat, brix_dirent ** ents_out, size_t * count_out, brix_status * st)
Definition at line 380 of file ops_meta.c.
References brix_resilient_window_ms(), brix_with_resilience(), c, dirlist_args::count_out, dirlist_op(), dirlist_args::ents_out, dirlist_args::path, dirlist_args::want_stat, and XRDC_OP_READONLY.
Referenced by brix_fuse_op_dirlist(), brix_glob(), chk_probe_dirlist(), compare_dirs(), copy_tree_download(), dx_probe_namespace(), ls_json_dir(), ls_print_dir(), mirror_delete_remote(), probe_root_read_suite(), resolve_target(), rmtree_depth(), tree_recurse(), tree_walk_depth(), and walk_dir().
brix_lstat()
int brix_lstat (brix_conn * c, const char * path, brix_statinfo * out, brix_status * st)
Definition at line 93 of file ops_meta.c.
References c, kXR_statNoFollow, and stat_opt().
Referenced by brix_fuse_op_lstat(), and rmtree_handle_dir_entry().
brix_stat()
int brix_stat (brix_conn * c, const char * path, brix_statinfo * out, brix_status * st)
Definition at line 87 of file ops_meta.c.
References c, and stat_opt().
Referenced by brix_fuse_op_stat(), chk_probe_confinement(), chk_probe_dirlist(), chk_probe_handle_limits(), chk_probe_posc(), cmd_bench(), compare_probe(), copy_remote_to_remote(), copy_unzip(), copy_zip_store_remote(), dest_is_dir(), do_rm(), do_stat(), do_tail(), do_wc(), doctor_cms(), dx_authz_anon(), dx_probe_namespace(), dx_probe_read(), entry_meta(), main(), mb_create(), probe_holder(), probe_p1_path_escape(), probe_path_confinement(), probe_root_read_suite(), probe_server_survives(), remote_entry_is_dir(), remote_open(), remote_stat(), resilient_setup(), resolve_target(), slurp_file(), statx(), tail_follow(), topo_probe_redirect(), touch_ensure_file(), tpc_setup_source(), ul_sync_skip(), upload_close_commit_resilient(), wait_online(), xfs_access(), xrd_clockskew_root(), and xrd_ping().
buf_append()
static int buf_append (uint8_t ** buf, size_t * len, size_t * cap, const uint8_t * src, size_t n) static
Definition at line 103 of file ops_meta.c.
Referenced by dirlist_accumulate().
dirent_push()
static int dirent_push (brix_dirent ** ents, size_t * count, size_t * cap, const brix_dirent * e) static
Definition at line 144 of file ops_meta.c.
Referenced by dirlist_parse_entries().
dirlist_accumulate()
static int dirlist_accumulate (brix_conn * c, ClientDirlistRequest * req, const char * path, uint8_t ** acc_out, size_t * acclen_out, brix_status * st) static
Definition at line 181 of file ops_meta.c.
References brix_recv(), brix_roundtrip(), brix_status_set(), buf_append(), c, kXR_oksofar, and XRDC_EPROTO.
Referenced by dirlist_once().
dirlist_once()
static int dirlist_once (brix_conn * c, const char * path, int want_stat, brix_dirent ** ents_out, size_t * count_out, brix_status * st) static
Definition at line 328 of file ops_meta.c.
References c, dirlist_accumulate(), dirlist_parse_entries(), dirlist_skip_dstat_leadin(), kXR_dirlist, kXR_dstat, xrdw_dirlist_req_t::options, ClientDirlistRequest::requestid, and xrdw_dirlist_req_pack().
Referenced by dirlist_op().
dirlist_op()
static int dirlist_op (brix_conn * c, void * arg, brix_status * st) static
Definition at line 370 of file ops_meta.c.
References c, dirlist_args::count_out, dirlist_once(), dirlist_args::ents_out, dirlist_args::path, and dirlist_args::want_stat.
Referenced by brix_dirlist().
dirlist_parse_entries()
static int dirlist_parse_entries (const uint8_t * acc, size_t acclen, size_t i, int want_stat, brix_dirent ** ents_out, size_t * count_out, brix_status * st) static
Definition at line 274 of file ops_meta.c.
References brix_status_set(), dirent_push(), brix_dirent::have_stat, brix_dirent::name, next_line(), parse_statinfo(), brix_dirent::st, and XRDC_EPROTO.
Referenced by dirlist_once().
dirlist_skip_dstat_leadin()
static size_t dirlist_skip_dstat_leadin (const uint8_t * acc, size_t acclen, int want_stat) static
Definition at line 241 of file ops_meta.c.
References BRIX_DSTAT_LEADIN, and BRIX_DSTAT_PREFIX_LEN.
Referenced by dirlist_once().
next_line()
static size_t next_line (const uint8_t * b, size_t len, size_t i, size_t * start, size_t * linelen, int * was_nul) static
Definition at line 127 of file ops_meta.c.
Referenced by dirlist_parse_entries().
parse_statinfo()
static int parse_statinfo (const char * s, brix_statinfo * out) static
Definition at line 26 of file ops_meta.c.
References brix_statinfo::atime, brix_statline_ext::atime, brix_statline_parse(), brix_statinfo::ctime, brix_statline_ext::ctime, brix_statinfo::flags, brix_statinfo::group, brix_statline_ext::group, brix_statinfo::have_ext, brix_statline_ext::have_ext, brix_statinfo::id, brix_statinfo::mode, brix_statline_ext::mode, brix_statinfo::mtime, brix_statinfo::owner, brix_statline_ext::owner, s, and brix_statinfo::size.
Referenced by dirlist_parse_entries(), and stat_opt().
stat_opt()
static int stat_opt (brix_conn * c, const char * path, uint8_t options, brix_statinfo * out, brix_status * st) static
Definition at line 51 of file ops_meta.c.
References brix_roundtrip_resilient(), brix_status_set(), c, kXR_stat, xrdw_stat_req_t::options, parse_statinfo(), ClientStatRequest::requestid, XRDC_EPROTO, XRDC_OP_READONLY, and xrdw_stat_req_pack().
Referenced by brix_lstat(), and brix_stat().