nginx-xrootd: client/lib/protocols/root/ops_file_rw.c File Reference
ops_file_rw.c File Reference
#include "ops_internal.h"
Functions
ssize_t brix_inflate_frame (uint8_t codec, const uint8_t *comp, size_t comp_len, void *out, size_t out_cap, brix_status *st)
static ssize_t file_read_frames (brix_conn *c, brix_file *f, int64_t offset, void *buf, size_t len, brix_status *st)
ssize_t brix_file_read (brix_conn *c, brix_file *f, int64_t offset, void *buf, size_t len, brix_status *st)
uint8_t * brix_deflate_frame (uint8_t codec, const void *in, size_t in_len, size_t *out_len, brix_status *st)
int brix_file_write (brix_conn *c, brix_file *f, int64_t offset, const void *buf, size_t len, brix_status *st)
static int brix_readv_accumulate (brix_conn *c, uint16_t sid, uint8_t **out_acc, size_t *out_len, brix_status *st)
static ssize_t brix_readv_scatter (const uint8_t *acc, size_t acc_len, brix_readv_seg *segs, size_t nseg, brix_status *st)
static ssize_t file_readv_frames (brix_conn *c, brix_file *f, brix_readv_seg *segs, size_t nseg, brix_status *st)
ssize_t brix_file_readv (brix_conn *c, brix_file *f, brix_readv_seg *segs, size_t nseg, brix_status *st)
int brix_file_writev (brix_conn *c, brix_file *f, const brix_writev_seg *segs, size_t nseg, int do_sync, brix_status *st)
Function Documentation
brix_deflate_frame()
uint8_t * brix_deflate_frame (uint8_t codec, const void * in, size_t in_len, size_t * out_len, brix_status * st)
Definition at line 178 of file ops_file_rw.c.
References brix_codec_close(), BRIX_CODEC_DIR_COMPRESS, BRIX_CODEC_END, BRIX_CODEC_OK, brix_codec_open(), brix_codec_step(), brix_status_set(), s, and XRDC_EPROTO.
Referenced by brix_file_write(), and brix_mfile_pwrite().
brix_file_read()
ssize_t brix_file_read (brix_conn * c, brix_file * f, int64_t offset, void * buf, size_t len, brix_status * st)
Definition at line 161 of file ops_file_rw.c.
References brix_io_stall_arm(), brix_io_stall_disarm(), c, and file_read_frames().
Referenced by bench_run(), bench_sweep(), brix_rfile_pread(), doctor_xfer(), download_to_fd(), dx_probe_read(), dx_probe_write(), probe_write_suite(), pump_src_remote(), verify_download_tmp(), watch_probe_once(), and zip_remote_pread().
brix_file_readv()
ssize_t brix_file_readv (brix_conn * c, brix_file * f, brix_readv_seg * segs, size_t nseg, brix_status * st)
Definition at line 463 of file ops_file_rw.c.
References brix_io_stall_arm(), brix_io_stall_disarm(), c, and file_readv_frames().
Referenced by do_readv(), main(), and write_readv().
brix_file_write()
int brix_file_write (brix_conn * c, brix_file * f, int64_t offset, const void * buf, size_t len, brix_status * st)
Definition at line 239 of file ops_file_rw.c.
References brix_deflate_frame(), brix_recv(), brix_send(), c, xrdw_write_req_t::fhandle, brix_file::fhandle, kXR_write, xrdw_write_req_t::offset, ClientWriteRequest::requestid, brix_file::write_codec, XRD_FHANDLE_LEN, and xrdw_write_req_pack().
Referenced by brix_rfile_pwrite(), chk_probe_posc(), dx_probe_write(), pump_sink_remote(), write_verify(), and zipw_remote_write().
brix_file_writev()
int brix_file_writev (brix_conn * c, brix_file * f, const brix_writev_seg * segs, size_t nseg, int do_sync, brix_status * st)
Definition at line 485 of file ops_file_rw.c.
References brix_recv(), brix_send_ext(), brix_status_set(), c, brix_file::fhandle, kXR_writev, kXR_wv_doSync, brix_writev_seg::len, xrdw_writev_req_t::options, ClientWriteVRequest::requestid, XRD_FHANDLE_LEN, XRDC_EPROTO, XRDC_EUSAGE, XRDC_VEC_MAXBYTES, XRDC_VEC_MAXSEGS, and xrdw_writev_req_pack().
Referenced by do_writev().
brix_inflate_frame()
ssize_t brix_inflate_frame (uint8_t codec, const uint8_t * comp, size_t comp_len, void * out, size_t out_cap, brix_status * st)
Definition at line 16 of file ops_file_rw.c.
References brix_codec_close(), BRIX_CODEC_DIR_DECOMPRESS, BRIX_CODEC_END, BRIX_CODEC_OK, brix_codec_open(), brix_codec_step(), brix_status_set(), brix_codec_guard_t::max_ratio, brix_codec_guard_t::out_cap, s, and XRDC_EPROTO.
Referenced by brix_mfile_pread(), and file_read_frames().
brix_readv_accumulate()
static int brix_readv_accumulate (brix_conn * c, uint16_t sid, uint8_t ** out_acc, size_t * out_len, brix_status * st) static
Definition at line 311 of file ops_file_rw.c.
References brix_recv(), brix_status_set(), c, kXR_ok, XRDC_EPROTO, and XRDC_VEC_MAXBYTES.
Referenced by file_readv_frames().
brix_readv_scatter()
static ssize_t brix_readv_scatter (const uint8_t * acc, size_t acc_len, brix_readv_seg * segs, size_t nseg, brix_status * st) static
Definition at line 378 of file ops_file_rw.c.
References brix_readv_seg_rlen(), BRIX_READV_SEGSIZE, brix_status_set(), brix_readv_seg::got, brix_readv_seg::len, and XRDC_EPROTO.
Referenced by file_readv_frames().
file_read_frames()
static ssize_t file_read_frames (brix_conn * c, brix_file * f, int64_t offset, void * buf, size_t len, brix_status * st) static
Definition at line 64 of file ops_file_rw.c.
References brix_inflate_frame(), brix_recv(), brix_send(), brix_status_set(), c, xrdw_read_req_t::fhandle, brix_file::fhandle, kXR_ok, kXR_read, xrdw_read_req_t::offset, brix_file::read_codec, ClientReadRequest::requestid, XRD_FHANDLE_LEN, XRDC_EPROTO, and xrdw_read_req_pack().
Referenced by brix_file_read().
file_readv_frames()
static ssize_t file_readv_frames (brix_conn * c, brix_file * f, brix_readv_seg * segs, size_t nseg, brix_status * st) static
Definition at line 415 of file ops_file_rw.c.
References brix_readv_accumulate(), brix_readv_scatter(), brix_readv_seg_pack(), BRIX_READV_SEGSIZE, brix_send(), brix_status_set(), c, brix_file::fhandle, kXR_readv, brix_readv_seg::len, brix_readv_seg::offset, ClientRequestHdr::requestid, XRDC_EPROTO, XRDC_EUSAGE, XRDC_VEC_MAXSEGS, and xrdw_empty_req_pack().
Referenced by brix_file_readv().