nginx-xrootd: client/lib/protocols/root/ops_fs.c File Reference
ops_fs.c File Reference
#include "brix.h"
#include <arpa/inet.h>
#include <endian.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
static int fs_simple (brix_conn *c, void *hdr24, const void *payload, uint32_t plen, brix_op_class cls, int benign_errno, brix_status *st)
static int fs_text (brix_conn *c, void *hdr24, const void *payload, uint32_t plen, char *out, size_t outsz, brix_status *st)
int brix_mkdir (brix_conn *c, const char *path, int mode, int parents, brix_status *st)
int brix_rm (brix_conn *c, const char *path, brix_status *st)
int brix_rmdir (brix_conn *c, const char *path, brix_status *st)
int brix_mv (brix_conn *c, const char *src, const char *dst, brix_status *st)
int brix_chmod (brix_conn *c, const char *path, int mode, brix_status *st)
int brix_truncate (brix_conn *c, const char *path, int64_t size, brix_status *st)
int brix_query (brix_conn *c, int infotype, const char *args, char *out, size_t outsz, brix_status *st)
int brix_statvfs (brix_conn *c, const char *path, char *out, size_t outsz, brix_status *st)
int brix_locate (brix_conn *c, const char *path, char *out, size_t outsz, brix_status *st)
int brix_prepare (brix_conn *c, const char *const *paths, int npaths, int options, int optionX, int prty, char *out, size_t outsz, brix_status *st)
Function Documentation
brix_chmod()
int brix_chmod (brix_conn * c, const char * path, int mode, brix_status * st)
Definition at line 147 of file ops_fs.c.
References c, fs_simple(), kXR_chmod, xrdw_chmod_req_t::mode, ClientChmodRequest::requestid, XRDC_OP_IDEMPOTENT, and xrdw_chmod_req_pack().
Referenced by brix_fuse_op_chmod(), chmod_visit(), do_chmod(), and mb_create().
brix_locate()
int brix_locate (brix_conn * c, const char * path, char * out, size_t outsz, brix_status * st)
Definition at line 206 of file ops_fs.c.
References c, fs_text(), kXR_locate, xrdw_locate_req_t::options, ClientLocateRequest::requestid, and xrdw_locate_req_pack().
Referenced by do_locate(), do_map(), doctor_cms(), doctor_diagnose(), topo_probe_locate(), and watch_probe_once().
brix_mkdir()
int brix_mkdir (brix_conn * c, const char * path, int mode, int parents, brix_status * st)
Definition at line 71 of file ops_fs.c.
References c, fs_simple(), kXR_mkdir, kXR_mkdirpath, xrdw_mkdir_req_t::options, ClientMkdirRequest::requestid, XRDC_OP_MUTATION_NORMALIZE, and xrdw_mkdir_req_pack().
Referenced by brix_fuse_op_mkdir(), copy_tree_upload(), do_mkdir(), dx_authz_scope(), dx_probe_write(), mb_create(), and probe_write_suite().
brix_mv()
int brix_mv (brix_conn * c, const char * src, const char * dst, brix_status * st)
Definition at line 110 of file ops_fs.c.
References xrdw_twopath_req_t::arg1len, brix_status_set(), c, fs_simple(), kXR_mv, ClientMvRequest::requestid, XRDC_EPROTO, XRDC_EUSAGE, XRDC_OP_MUTATION_NORMALIZE, and xrdw_twopath_req_pack().
Referenced by brix_fuse_op_mv(), do_mv(), and write_rename_truncate_rm().
brix_prepare()
int brix_prepare (brix_conn * c, const char *const * paths, int npaths, int options, int optionX, int prty, char * out, size_t outsz, brix_status * st)
Definition at line 220 of file ops_fs.c.
References brix_status_set(), c, fs_text(), kXR_prepare, kXR_stage, xrdw_prepare_req_t::options, ClientPrepareRequest::requestid, XRDC_EPROTO, XRDC_EUSAGE, and xrdw_prepare_req_pack().
Referenced by do_evict(), do_prepare(), do_stage(), dx_probe_stage(), and xrdprep_run().
brix_query()
int brix_query (brix_conn * c, int infotype, const char * args, char * out, size_t outsz, brix_status * st)
Definition at line 177 of file ops_fs.c.
References c, fs_text(), xrdw_query_req_t::infotype, kXR_query, ClientQueryRequest::requestid, and xrdw_query_req_pack().
Referenced by brix_ext_probe(), brix_qstats_main(), do_df(), do_query(), op_qspace(), print_space(), probe_root_read_suite(), xfs_statfs(), and xrd_probe_caps().
brix_rm()
int brix_rm (brix_conn * c, const char * path, brix_status * st)
Definition at line 87 of file ops_fs.c.
References c, fs_simple(), kXR_rm, ClientRmRequest::requestid, XRDC_OP_MUTATION_NORMALIZE, and xrdw_empty_req_pack().
Referenced by brix_fuse_op_rm(), chk_probe_posc(), do_ln(), do_rm(), dx_probe_write(), mb_remove(), mirror_remote_remove(), remove_source_entry(), rmtree_remove_leaf(), tree_dl_file(), write_rename_truncate_rm(), write_symlink_ops(), and xrd_clockskew_root().
brix_rmdir()
int brix_rmdir (brix_conn * c, const char * path, brix_status * st)
Definition at line 99 of file ops_fs.c.
References c, fs_simple(), kXR_rmdir, ClientRmdirRequest::requestid, XRDC_OP_MUTATION_NORMALIZE, and xrdw_empty_req_pack().
Referenced by brix_fuse_op_rmdir(), copy_recursive(), do_rmdir(), dx_authz_scope(), dx_probe_write(), mb_remove(), rmtree_depth(), tree_dl_entry(), and write_rename_truncate_rm().
brix_statvfs()
int brix_statvfs (brix_conn * c, const char * path, char * out, size_t outsz, brix_status * st)
Definition at line 192 of file ops_fs.c.
References c, fs_text(), kXR_stat, kXR_vfs, xrdw_stat_req_t::options, ClientStatRequest::requestid, and xrdw_stat_req_pack().
Referenced by do_statvfs(), and probe_root_read_suite().
brix_truncate()
int brix_truncate (brix_conn * c, const char * path, int64_t size, brix_status * st)
Definition at line 162 of file ops_fs.c.
References c, fs_simple(), kXR_truncate, xrdw_truncate_req_t::offset, ClientTruncateRequest::requestid, XRDC_OP_IDEMPOTENT, and xrdw_truncate_req_pack().
Referenced by brix_fuse_op_trunc(), do_truncate(), and write_rename_truncate_rm().
fs_simple()
static int fs_simple (brix_conn * c, void * hdr24, const void * payload, uint32_t plen, brix_op_class cls, int benign_errno, brix_status * st) static
Definition at line 29 of file ops_fs.c.
References brix_roundtrip_resilient(), c, and cls().
Referenced by brix_chmod(), brix_mkdir(), brix_mv(), brix_rm(), brix_rmdir(), and brix_truncate().
fs_text()
static int fs_text (brix_conn * c, void * hdr24, const void * payload, uint32_t plen, char * out, size_t outsz, brix_status * st) static
Definition at line 48 of file ops_fs.c.
References brix_roundtrip_resilient(), c, and XRDC_OP_READONLY.
Referenced by brix_locate(), brix_prepare(), brix_query(), and brix_statvfs().