nginx-xrootd: client/lib/protocols/root/ops_file.c File Reference
ops_file.c File Reference
#include "ops_internal.h"
Functions
int brix_file_open_read (brix_conn *c, const char *path, brix_file *f, brix_status *st)
int brix_file_open_write (brix_conn *c, const char *path, int force, int posc, brix_file *f, brix_status *st)
int brix_file_open_update (brix_conn *c, const char *path, int posc, brix_file *f, brix_status *st)
int brix_file_close (brix_conn *c, brix_file *f, brix_status *st)
static int brix_open_apply_inline_codec (const uint8_t *body, uint32_t blen, int write, brix_file *f, brix_status *st)
int brix_file_open_opaque (brix_conn *c, const char *path, const char *opaque, int write, int force, int posc, brix_file *f, brix_status *st)
int brix_file_sync (brix_conn *c, brix_file *f, brix_status *st)
Function Documentation
brix_file_close()
int brix_file_close (brix_conn * c, brix_file * f, brix_status * st)
Definition at line 33 of file ops_file.c.
References brix_recv(), brix_send(), c, xrdw_close_req_t::fhandle, brix_file::fhandle, kXR_close, ClientCloseRequest::requestid, XRD_FHANDLE_LEN, and xrdw_close_req_pack().
Referenced by bench_run(), bench_sweep(), brix_rfile_close(), chk_probe_handle_limits(), chk_probe_pgread(), copy_one_l2r(), copy_one_r2l(), copy_unzip(), copy_zip_store_remote(), do_readv(), do_writev(), doctor_xfer(), download_stream_body(), download_to_fd(), dx_authz_anon(), dx_probe_read(), dx_probe_write(), main(), mb_create(), probe_write_suite(), r2r_teardown(), touch_ensure_file(), tpc_teardown(), upload_close_commit_resilient(), verify_download_tmp(), watch_probe_once(), write_readv(), write_verify(), and xrd_clockskew_root().
brix_file_open_opaque()
int brix_file_open_opaque (brix_conn * c, const char * path, const char * opaque, int write, int force, int posc, brix_file * f, brix_status * st)
Definition at line 132 of file ops_file.c.
References brix_open_apply_inline_codec(), brix_open_options_build(), brix_roundtrip(), brix_status_set(), c, brix_file::fhandle, kXR_open, kXR_waitresp, xrdw_open_req_t::mode, brix_file::read_codec, ClientOpenRequest::requestid, brix_file::write_codec, XRD_FHANDLE_LEN, XRDC_EPROTO, and xrdw_open_req_pack().
Referenced by brix_file_open_read(), brix_file_open_update(), brix_file_open_write(), download_open_resilient(), pump_remote_reopen(), rfile_do_open(), tpc_run_rendezvous(), and upload_open_resilient().
brix_file_open_read()
int brix_file_open_read (brix_conn * c, const char * path, brix_file * f, brix_status * st)
Definition at line 8 of file ops_file.c.
References brix_file_open_opaque(), and c.
Referenced by bench_run(), bench_sweep(), chk_probe_handle_limits(), chk_probe_pgread(), copy_one_r2l(), copy_remote_to_remote(), copy_unzip(), do_readv(), doctor_xfer(), download_open_resilient(), download_to_fd(), dx_authz_anon(), dx_probe_read(), dx_probe_write(), main(), probe_write_suite(), pump_remote_reopen(), rfile_do_open(), verify_download_tmp(), watch_probe_once(), and write_readv().
brix_file_open_update()
int brix_file_open_update (brix_conn * c, const char * path, int posc, brix_file * f, brix_status * st)
Definition at line 23 of file ops_file.c.
References brix_file_open_opaque(), and c.
Referenced by copy_zip_store_remote(), pump_sink_reopen(), and rfile_do_open().
brix_file_open_write()
int brix_file_open_write (brix_conn * c, const char * path, int force, int posc, brix_file * f, brix_status * st)
Definition at line 15 of file ops_file.c.
References brix_file_open_opaque(), and c.
Referenced by brix_rfile_open_write(), chk_probe_posc(), copy_one_l2r(), copy_remote_to_remote(), copy_zip_store_remote(), do_writev(), dx_probe_write(), mb_create(), touch_ensure_file(), upload_open_resilient(), write_verify(), and xrd_clockskew_root().
brix_file_sync()
int brix_file_sync (brix_conn * c, brix_file * f, brix_status * st)
Definition at line 216 of file ops_file.c.
References brix_recv(), brix_send(), c, xrdw_sync_req_t::fhandle, brix_file::fhandle, kXR_sync, ClientSyncRequest::requestid, XRD_FHANDLE_LEN, and xrdw_sync_req_pack().
Referenced by copy_tpc(), tpc_run_rendezvous(), and xfs_fsync().
brix_open_apply_inline_codec()
static int brix_open_apply_inline_codec (const uint8_t * body, uint32_t blen, int write, brix_file * f, brix_status * st) static
Definition at line 90 of file ops_file.c.
References brix_codec_available(), BRIX_CODEC_MAX, BRIX_INLINE_CMP_MAGIC, brix_status_set(), brix_file::read_codec, brix_file::write_codec, and XRDC_EUNSUPPORTED.
Referenced by brix_file_open_opaque().