nginx-xrootd: client/lib/protocols/root/ops_ext.c File Reference
ops_ext.c File Reference
#include "brix.h"
#include "core/compat/vendor_ext.h"
#include <endian.h>
#include <arpa/inet.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
Functions
static int ext_simple (brix_conn *c, void *hdr24, const void *payload, uint32_t plen, brix_status *st)
int brix_setattr (brix_conn *c, const char *path, int set_times, const struct timespec times[2], int set_owner, uint32_t uid, uint32_t gid, brix_status *st)
int brix_symlink (brix_conn *c, const char *target, const char *linkpath, brix_status *st)
int brix_link (brix_conn *c, const char *oldpath, const char *newpath, brix_status *st)
ssize_t brix_readlink (brix_conn *c, const char *path, char *out, size_t outsz, brix_status *st)
int brix_ext_probe (brix_conn *c, int *has_setattr, int *has_symlink, int *has_readlink, int *has_link, brix_status *st)
Function Documentation
brix_ext_probe()
int brix_ext_probe (brix_conn * c, int * has_setattr, int * has_symlink, int * has_readlink, int * has_link, brix_status * st)
Definition at line 188 of file ops_ext.c.
References brix_query(), c, and kXR_Qconfig.
Referenced by aio_probe_ext(), and battery_root().
brix_link()
int brix_link (brix_conn * c, const char * oldpath, const char * newpath, brix_status * st)
Definition at line 125 of file ops_ext.c.
References xrdw_twopath_req_t::arg1len, brix_status_set(), c, ext_simple(), kXR_link, ClientLinkRequest::requestid, XRDC_EPROTO, XRDC_EUSAGE, and xrdw_twopath_req_pack().
Referenced by brix_fuse_op_link(), and do_ln().
brix_readlink()
ssize_t brix_readlink (brix_conn * c, const char * path, char * out, size_t outsz, brix_status * st)
Definition at line 160 of file ops_ext.c.
References brix_roundtrip(), c, kXR_readlink, ClientReadlinkRequest::requestid, and xrdw_empty_req_pack().
Referenced by do_readlink(), write_symlink_ops(), and xfs_readlink_one_attempt().
brix_setattr()
int brix_setattr (brix_conn * c, const char * path, int set_times, const struct timespec times[2], int set_owner, uint32_t uid, uint32_t gid, brix_status * st)
Definition at line 44 of file ops_ext.c.
References xrdp_setattr_t::atime_nsec, xrdp_setattr_t::atime_sec, BRIX_SETATTR_PREFIX_LEN, brix_status_set(), c, ext_simple(), xrdp_setattr_t::flags, xrdp_setattr_t::gid, kXR_sa_owner, kXR_sa_times, kXR_setattr, xrdp_setattr_t::mtime_nsec, xrdp_setattr_t::mtime_sec, ClientSetattrRequest::requestid, xrdp_setattr_t::uid, XRDC_EPROTO, xrdp_setattr_prefix_pack(), and xrdw_empty_req_pack().
Referenced by brix_fuse_op_setattr(), do_touch(), and probe_write_suite().
brix_symlink()
int brix_symlink (brix_conn * c, const char * target, const char * linkpath, brix_status * st)
Definition at line 90 of file ops_ext.c.
References xrdw_twopath_req_t::arg1len, brix_status_set(), c, ext_simple(), kXR_symlink, ClientSymlinkRequest::requestid, XRDC_EPROTO, XRDC_EUSAGE, and xrdw_twopath_req_pack().
Referenced by brix_fuse_op_symlink(), do_ln(), and write_symlink_ops().
ext_simple()
static int ext_simple (brix_conn * c, void * hdr24, const void * payload, uint32_t plen, brix_status * st) static
Definition at line 27 of file ops_ext.c.
References brix_roundtrip(), and c.
Referenced by brix_link(), brix_setattr(), and brix_symlink().