nginx-xrootd: client/lib/protocols/root/ops_file_pg.c File Reference
ops_file_pg.c File Reference
#include "ops_internal.h"
Functions
int read_status_frame (brix_conn *c, uint16_t want_sid, uint8_t *resptype, uint32_t *pgdlen, int64_t *foff, brix_status *st)
ssize_t decode_pages (const uint8_t *pg, uint32_t pglen, int64_t file_off, uint8_t *dst, size_t dstcap, brix_status *st)
ssize_t brix_file_pgread (brix_conn *c, brix_file *f, int64_t offset, void *buf, size_t len, brix_status *st)
int pgwrite_retry_one (brix_conn *c, brix_file *f, const uint8_t *buf, int64_t base, size_t len, int64_t pgoff, brix_status *st)
int brix_file_pgwrite (brix_conn *c, brix_file *f, int64_t offset, const void *buf, size_t len, brix_status *st)
Function Documentation
brix_file_pgread()
ssize_t brix_file_pgread (brix_conn * c, brix_file * f, int64_t offset, void * buf, size_t len, brix_status * st)
Definition at line 122 of file ops_file_pg.c.
References brix_read_full(), brix_send(), brix_status_set(), c, decode_pages(), xrdw_pgread_req_t::fhandle, brix_file::fhandle, kXR_FinalResult, kXR_pgread, xrdw_pgread_req_t::offset, read_status_frame(), ClientPgReadRequest::requestid, XRD_FHANDLE_LEN, XRDC_EPROTO, and xrdw_pgread_req_pack().
Referenced by brix_rfile_pread(), do_check(), and pump_src_remote().
brix_file_pgwrite()
int brix_file_pgwrite (brix_conn * c, brix_file * f, int64_t offset, const void * buf, size_t len, brix_status * st)
Definition at line 242 of file ops_file_pg.c.
References brix_read_full(), brix_send(), brix_status_set(), c, xrdw_pgwrite_req_t::fhandle, brix_file::fhandle, kXR_pgPageSZ, kXR_pgwrite, xrdw_pgwrite_req_t::offset, pgwrite_retry_one(), read_status_frame(), ClientPgWriteRequest::requestid, XRD_FHANDLE_LEN, XRDC_EINTEGRITY, XRDC_EPROTO, XRDC_PGW_MAX_RETRY, xrdp_pg_encode(), and xrdw_pgwrite_req_pack().
Referenced by brix_rfile_pwrite(), and pump_sink_remote().
decode_pages()
ssize_t decode_pages (const uint8_t * pg, uint32_t pglen, int64_t file_off, uint8_t * dst, size_t dstcap, brix_status * st)
Definition at line 102 of file ops_file_pg.c.
References brix_status_set(), XRDC_EINTEGRITY, XRDC_EPROTO, and xrdp_pg_decode().
Referenced by brix_file_pgread().
pgwrite_retry_one()
int pgwrite_retry_one (brix_conn * c, brix_file * f, const uint8_t * buf, int64_t base, size_t len, int64_t pgoff, brix_status * st)
Definition at line 190 of file ops_file_pg.c.
References brix_read_full(), brix_send(), brix_status_set(), c, xrdw_pgwrite_req_t::fhandle, brix_file::fhandle, kXR_pgPageSZ, kXR_pgRetry, kXR_pgwrite, xrdw_pgwrite_req_t::offset, read_status_frame(), ClientPgWriteRequest::requestid, XRD_FHANDLE_LEN, XRDC_EPROTO, xrdp_pg_encode(), and xrdw_pgwrite_req_pack().
Referenced by brix_file_pgwrite().
read_status_frame()
int read_status_frame (brix_conn * c, uint16_t want_sid, uint8_t * resptype, uint32_t * pgdlen, int64_t * foff, brix_status * st)
Definition at line 25 of file ops_file_pg.c.
References brix_crc32c_value(), brix_kxr_name(), brix_read_full(), brix_status_set(), c, brix_status::kxr, kXR_error, kXR_status, stat(), xrd_error_body_decode(), xrd_get_u32_be(), xrd_resp_hdr_unpack(), XRD_RESPONSE_HDR_LEN, XRDC_DLEN_MAX, XRDC_EINTEGRITY, XRDC_EPROTO, and XRDC_PG_STATUSBODY.
Referenced by brix_file_pgread(), brix_file_pgwrite(), and pgwrite_retry_one().