nginx-xrootd: src/protocols/cvmfs/origin_geo.h File Reference
origin_geo.h File Reference
Functions
double brix_cvmfs_haversine_km (double lat1, double lon1, double lat2, double lon2)
void brix_cvmfs_rank_by_metric (const double *metric, int n, int *ranks)
Function Documentation
brix_cvmfs_haversine_km()
double brix_cvmfs_haversine_km (double lat1, double lon1, double lat2, double lon2)
Definition at line 17 of file origin_geo.c.
References CVMFS_EARTH_RADIUS_KM.
Referenced by cvmfs_geo_compute_metrics().
brix_cvmfs_rank_by_metric()
void brix_cvmfs_rank_by_metric (const double * metric, int n, int * ranks)
Definition at line 29 of file origin_geo.c.
Referenced by cvmfs_geo_apply_ranks(), cvmfs_geo_render(), and cvmfs_probe_done().