nginx-xrootd: src/fs/cache/origin_protocol.c File Reference
origin_protocol.c File Reference
#include "cache_internal.h"
#include "protocols/root/protocol/bootstrap_pack.h"
#include "core/compat/fattr_codec.h"
#include "protocols/root/protocol/frame_hdr.h"
#include "auth/gsi/gsi_core.h"
#include "protocols/root/protocol/gsi.h"
#include "auth/sss/sss_keytab_kernel.h"
#include <stdio.h>
#include <errno.h>
#include <fcntl.h>
#include <inttypes.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <openssl/bio.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
#include <openssl/x509_vfy.h>
#include <openssl/evp.h>
#include <openssl/err.h>
Functions
static const char * cache_origin_gsi_parms (const char *parms, size_t plen)
int brix_cache_origin_bootstrap (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc)
int brix_cache_origin_open (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, u_char fhandle[4])
int brix_cache_origin_query_checksum (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, char *alg_out, size_t alg_sz, char *hex_out, size_t hex_sz)
int brix_cache_origin_read_chunk (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const u_char fhandle[4], brix_cache_sink_t *sink, uint64_t read_off, uint64_t dst_off, size_t want, size_t *got)
Function Documentation
brix_cache_origin_bootstrap()
int brix_cache_origin_bootstrap (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc)
Definition at line 58 of file origin_protocol.c.
References brix_cache_io_send(), brix_cache_origin_auth_gsi(), brix_cache_origin_auth_sss(), brix_cache_origin_auth_ztn(), brix_cache_read_response(), brix_cache_set_error(), BRIX_SESSION_ID_LEN, ngx_stream_brix_srv_conf_t::cache_origin_bearer, cache_origin_gsi_parms(), ngx_stream_brix_srv_conf_t::cache_origin_sss_keytab, ngx_stream_brix_srv_conf_t::cache_origin_tls, ngx_stream_brix_srv_conf_t::cache_origin_x509_proxy, brix_cache_fill_t::conf, ServerProtocolBody::flags, kXR_AuthFailed, kXR_authmore, kXR_gotoTLS, kXR_ok, kXR_ServerError, kXR_TLSRequired, kXR_ver005, ngx_memcpy, xrd_pack_handshake(), xrd_pack_login_request(), and xrd_pack_protocol_request().
Referenced by proxy_gsi_login_thread(), sd_xroot_origin_open(), sd_xroot_session(), and sd_xroot_staged_open().
brix_cache_origin_open()
int brix_cache_origin_open (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, u_char fhandle[4])
Definition at line 219 of file origin_protocol.c.
References brix_cache_io_send(), brix_cache_read_response(), brix_cache_set_error(), brix_cache_set_origin_error(), BRIX_MAX_PATH, brix_cache_fill_t::clean_path, ClientOpenRequest::dlen, brix_cache_fill_t::file_size, kXR_error, kXR_NoMemory, kXR_ok, kXR_open, kXR_open_read, kXR_redirect, kXR_retstat, kXR_ServerError, kXR_Unsupported, ngx_memcpy, xrdw_open_req_t::options, ClientOpenRequest::requestid, ClientOpenRequest::streamid, XRD_FHANDLE_LEN, and xrdw_open_req_pack().
Referenced by sd_xroot_origin_open(), and sd_xroot_server_copy().
brix_cache_origin_query_checksum()
int brix_cache_origin_query_checksum (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, char * alg_out, size_t alg_sz, char * hex_out, size_t hex_sz)
Definition at line 323 of file origin_protocol.c.
References brix_cache_io_send(), brix_cache_read_response(), brix_cache_fill_t::clean_path, ClientQueryRequest::dlen, xrdw_query_req_t::infotype, kXR_ok, kXR_Qcksum, kXR_query, ngx_memcpy, ClientQueryRequest::requestid, brix_cache_fill_t::result, ClientQueryRequest::streamid, brix_cache_fill_t::xrd_error, and xrdw_query_req_pack().
Referenced by brix_sd_xroot_query_checksum().
brix_cache_origin_read_chunk()
int brix_cache_origin_read_chunk (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const u_char fhandle[4], brix_cache_sink_t * sink, uint64_t read_off, uint64_t dst_off, size_t want, size_t * got)
Definition at line 417 of file origin_protocol.c.
References BRIX_CACHE_FETCH_CHUNK, brix_cache_io_send(), brix_cache_read_response(), brix_cache_set_error(), brix_cache_set_origin_error(), brix_cache_set_syserror(), brix_cache_sink_pwrite(), ClientReadRequest::dlen, ClientReadRequest::fhandle, kXR_error, kXR_IOError, kXR_ok, kXR_oksofar, kXR_read, kXR_ServerError, ngx_memcpy, ClientReadRequest::offset, ClientReadRequest::requestid, ClientReadRequest::rlen, ClientReadRequest::streamid, and XRD_FHANDLE_LEN.
Referenced by sd_xroot_copy_body(), and sd_xroot_pread().
cache_origin_gsi_parms()
static const char * cache_origin_gsi_parms (const char * parms, size_t plen) static
Definition at line 34 of file origin_protocol.c.
Referenced by brix_cache_origin_bootstrap().