nginx-xrootd: src/fs/cache/origin_auth.c File Reference
origin_auth.c File Reference
#include "cache_internal.h"
#include "protocols/root/protocol/bootstrap_pack.h"
#include "protocols/root/protocol/frame_hdr.h"
#include "auth/gsi/gsi_core.h"
#include "protocols/root/protocol/gsi.h"
#include "auth/sss/sss_keytab_kernel.h"
#include <stdio.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <inttypes.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <openssl/bio.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
#include <openssl/x509_vfy.h>
#include <openssl/evp.h>
#include <openssl/err.h>
Data Structures
struct originauth_gsi_cred_t
Macros
#define BRIX_ZTN_VERSION 0
#define BRIX_ZTN_OPR_ISTKN 'T'
#define BRIX_ZTN_PREFIX_LEN 10 /* 8-byte TokenHdr + 2-byte length */
Functions
static int cache_origin_send_kxr_auth (brix_cache_origin_conn_t *oc, const char credtype[4], const u_char *payload, uint32_t plen)
static int cache_origin_build_ztn_credential (const ngx_str_t *token, u_char **out, size_t *outlen)
int brix_cache_origin_auth_ztn (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const ngx_str_t *token)
static uint8_t * cache_origin_load_proxy_pem (const char *path, size_t *outlen)
static EVP_PKEY * cache_origin_load_proxy_key (const char *path)
static int originauth_gsi_certreq (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *gsi_parms)
static int originauth_gsi_read_cert (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, u_char **body, uint32_t *dlen)
static int originauth_gsi_verify_srv_cert (brix_cache_fill_t *t, const u_char *body, uint32_t dlen)
static int originauth_gsi_load_credential (brix_cache_fill_t *t, const char *proxy_path, originauth_gsi_cred_t *cred)
static void originauth_gsi_warn_bare_cert (const uint8_t *proxy_pem, size_t proxy_pem_len, const char *proxy_path)
static int originauth_gsi_send_response (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, u_char *body, uint32_t dlen, originauth_gsi_cred_t *cred)
static int originauth_gsi_read_final (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc)
int brix_cache_origin_auth_gsi (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *gsi_parms, const char *proxy_path)
static int cache_origin_load_sss_key (const char *path, brix_sss_key_t *out)
int brix_cache_origin_auth_sss (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *keytab_path)
Macro Definition Documentation
BRIX_ZTN_OPR_ISTKN
#define BRIX_ZTN_OPR_ISTKN 'T'
Definition at line 77 of file origin_auth.c.
BRIX_ZTN_PREFIX_LEN
#define BRIX_ZTN_PREFIX_LEN 10 /* 8-byte TokenHdr + 2-byte length */
Definition at line 78 of file origin_auth.c.
BRIX_ZTN_VERSION
#define BRIX_ZTN_VERSION 0
Definition at line 76 of file origin_auth.c.
Function Documentation
brix_cache_origin_auth_gsi()
int brix_cache_origin_auth_gsi (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * gsi_parms, const char * proxy_path)
Definition at line 545 of file origin_auth.c.
References originauth_gsi_certreq(), originauth_gsi_load_credential(), originauth_gsi_read_cert(), originauth_gsi_read_final(), originauth_gsi_send_response(), originauth_gsi_verify_srv_cert(), originauth_gsi_warn_bare_cert(), originauth_gsi_cred_t::pem, originauth_gsi_cred_t::pem_len, and proxy_path().
Referenced by origin_bs_auth_dispatch().
brix_cache_origin_auth_sss()
int brix_cache_origin_auth_sss (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * keytab_path)
Definition at line 641 of file origin_auth.c.
References brix_cache_read_response(), brix_cache_set_error(), brix_cache_set_origin_error(), brix_sss_build_proxy_credential(), cache_origin_load_sss_key(), cache_origin_send_kxr_auth(), key, kXR_AuthFailed, kXR_error, kXR_ok, and kXR_ServerError.
Referenced by origin_bs_auth_dispatch().
brix_cache_origin_auth_ztn()
int brix_cache_origin_auth_ztn (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const ngx_str_t * token)
Definition at line 132 of file origin_auth.c.
References brix_cache_read_response(), brix_cache_set_error(), brix_cache_set_origin_error(), cache_origin_build_ztn_credential(), cache_origin_send_kxr_auth(), kXR_AuthFailed, kXR_error, kXR_NoMemory, kXR_ok, and kXR_ServerError.
Referenced by origin_bs_auth_dispatch(), and origin_bs_authmore_fallback().
cache_origin_build_ztn_credential()
static int cache_origin_build_ztn_credential (const ngx_str_t * token, u_char ** out, size_t * outlen) static
Definition at line 94 of file origin_auth.c.
References BRIX_ZTN_OPR_ISTKN, BRIX_ZTN_PREFIX_LEN, BRIX_ZTN_VERSION, and ngx_memcpy.
Referenced by brix_cache_origin_auth_ztn().
cache_origin_load_proxy_key()
static EVP_PKEY * cache_origin_load_proxy_key (const char * path) static
Definition at line 226 of file origin_auth.c.
References close(), and open().
Referenced by originauth_gsi_load_credential().
cache_origin_load_proxy_pem()
static uint8_t * cache_origin_load_proxy_pem (const char * path, size_t * outlen) static
Definition at line 181 of file origin_auth.c.
References close(), ngx_memcpy, and open().
Referenced by originauth_gsi_load_credential().
cache_origin_load_sss_key()
static int cache_origin_load_sss_key (const char * path, brix_sss_key_t * out) static
Definition at line 590 of file origin_auth.c.
References close(), sss_keytab_entry_t::exp, brix_sss_key_t::exp, sss_keytab_entry_t::group, brix_sss_key_t::group, sss_keytab_entry_t::id, brix_sss_key_t::id, sss_keytab_entry_t::key, brix_sss_key_t::key, sss_keytab_entry_t::key_len, brix_sss_key_t::key_len, sss_keytab_entry_t::name, brix_sss_key_t::name, ngx_memcpy, open(), sss_keytab_parse_line(), sss_keytab_entry_t::user, and brix_sss_key_t::user.
Referenced by brix_cache_origin_auth_sss().
cache_origin_send_kxr_auth()
static int cache_origin_send_kxr_auth (brix_cache_origin_conn_t * oc, const char credtype[4], const u_char * payload, uint32_t plen) static
Definition at line 40 of file origin_auth.c.
References brix_cache_io_send(), ClientAuthRequest::credtype, ClientAuthRequest::dlen, kXR_auth, ngx_memcpy, ClientAuthRequest::requestid, and ClientAuthRequest::streamid.
Referenced by brix_cache_origin_auth_sss(), brix_cache_origin_auth_ztn(), originauth_gsi_certreq(), and originauth_gsi_send_response().
originauth_gsi_certreq()
static int originauth_gsi_certreq (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * gsi_parms) static
Definition at line 257 of file origin_auth.c.
References brix_cache_set_error(), brix_gsi_build_certreq(), brix_gsi_parse_parms(), brix_gsi_rand(), cache_origin_send_kxr_auth(), kXR_ServerError, and ngx_memcpy.
Referenced by brix_cache_origin_auth_gsi().
originauth_gsi_load_credential()
static int originauth_gsi_load_credential (brix_cache_fill_t * t, const char * proxy_path, originauth_gsi_cred_t * cred) static
Definition at line 404 of file origin_auth.c.
References brix_cache_set_error(), cache_origin_load_proxy_key(), cache_origin_load_proxy_pem(), brix_cache_fill_t::conf, originauth_gsi_cred_t::key, kXR_AuthFailed, originauth_gsi_cred_t::pem, originauth_gsi_cred_t::pem_len, and proxy_path().
Referenced by brix_cache_origin_auth_gsi().
originauth_gsi_read_cert()
static int originauth_gsi_read_cert (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, u_char ** body, uint32_t * dlen) static
Definition at line 305 of file origin_auth.c.
References brix_cache_read_response(), brix_cache_set_error(), brix_cache_set_origin_error(), kXR_AuthFailed, kXR_authmore, and kXR_error.
Referenced by brix_cache_origin_auth_gsi().
originauth_gsi_read_final()
static int originauth_gsi_read_final (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc) static
Definition at line 509 of file origin_auth.c.
References brix_cache_read_response(), brix_cache_set_error(), brix_cache_set_origin_error(), kXR_AuthFailed, kXR_error, and kXR_ok.
Referenced by brix_cache_origin_auth_gsi().
originauth_gsi_send_response()
static int originauth_gsi_send_response (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, u_char * body, uint32_t dlen, originauth_gsi_cred_t * cred) static
Definition at line 470 of file origin_auth.c.
References brix_cache_set_error(), brix_gsi_build_cert_response(), cache_origin_send_kxr_auth(), originauth_gsi_cred_t::key, kXR_AuthFailed, kXR_ServerError, originauth_gsi_cred_t::pem, and originauth_gsi_cred_t::pem_len.
Referenced by brix_cache_origin_auth_gsi().
originauth_gsi_verify_srv_cert()
static int originauth_gsi_verify_srv_cert (brix_cache_fill_t * t, const u_char * body, uint32_t dlen) static
Definition at line 341 of file origin_auth.c.
References brix_cache_set_error(), brix_gsi_find_bucket(), brix_cache_fill_t::conf, kXR_NotAuthorized, and kXRS_x509.
Referenced by brix_cache_origin_auth_gsi().
originauth_gsi_warn_bare_cert()
static void originauth_gsi_warn_bare_cert (const uint8_t * proxy_pem, size_t proxy_pem_len, const char * proxy_path) static
Definition at line 434 of file origin_auth.c.
References proxy_path().
Referenced by brix_cache_origin_auth_gsi().