nginx-xrootd: src/fs/cache/origin_connection.c File Reference
origin_connection.c File Reference
#include "cache_internal.h"
#include "protocols/root/connection/netconnect.h"
#include "core/compat/af_policy.h"
#include <fcntl.h>
#include <netdb.h>
#include <poll.h>
#include <stdio.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <unistd.h>
#include <openssl/err.h>
Functions
void brix_cache_origin_close (brix_cache_origin_conn_t *oc)
static int origin_tls_load_verify (SSL_CTX *ctx, const ngx_str_t *ca)
int brix_cache_origin_tls_upgrade (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const ngx_str_t *host)
int brix_cache_origin_connect_addr (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const ngx_str_t *host, uint16_t portnum)
int brix_cache_origin_connect (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc)
Function Documentation
brix_cache_origin_close()
void brix_cache_origin_close (brix_cache_origin_conn_t * oc)
Definition at line 23 of file origin_connection.c.
References close(), brix_cache_origin_conn_t::fd, brix_cache_origin_conn_t::ssl, and brix_cache_origin_conn_t::ssl_ctx.
Referenced by proxy_gsi_login_thread(), sd_xroot_getxattr(), sd_xroot_getxattr_cred(), sd_xroot_listxattr(), sd_xroot_listxattr_cred(), sd_xroot_obj_teardown(), sd_xroot_opendir_common(), sd_xroot_removexattr(), sd_xroot_removexattr_cred(), sd_xroot_rename(), sd_xroot_rename_cred(), sd_xroot_server_copy(), sd_xroot_server_copy_cred(), sd_xroot_session(), sd_xroot_setxattr(), sd_xroot_setxattr_cred(), sd_xroot_staged_connect_open(), sd_xroot_staged_teardown(), sd_xroot_unlink(), and sd_xroot_unlink_cred().
brix_cache_origin_connect()
int brix_cache_origin_connect (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc)
Definition at line 243 of file origin_connection.c.
References brix_cache_origin_connect_addr(), and brix_cache_fill_t::conf.
Referenced by proxy_gsi_login_thread(), sd_xroot_origin_open(), sd_xroot_session(), and sd_xroot_staged_connect_open().
brix_cache_origin_connect_addr()
int brix_cache_origin_connect_addr (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const ngx_str_t * host, uint16_t portnum)
Definition at line 164 of file origin_connection.c.
References BRIX_AF_AUTO, brix_apply_socket_io_timeouts(), BRIX_CACHE_IO_TIMEOUT, brix_cache_set_error(), brix_cache_set_syserror(), brix_connect_fd_deadline(), close(), brix_cache_fill_t::conf, brix_cache_origin_conn_t::fd, host, kXR_ServerError, port, brix_cache_origin_conn_t::ssl, and brix_cache_origin_conn_t::ssl_ctx.
Referenced by brix_cache_origin_connect().
brix_cache_origin_tls_upgrade()
int brix_cache_origin_tls_upgrade (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const ngx_str_t * host)
Definition at line 93 of file origin_connection.c.
References brix_cache_set_error(), brix_cache_fill_t::conf, brix_cache_origin_conn_t::fd, host, kXR_ServerError, kXR_TLSRequired, ngx_memcpy, origin_tls_load_verify(), brix_cache_origin_conn_t::ssl, and brix_cache_origin_conn_t::ssl_ctx.
Referenced by origin_bs_protocol().
origin_tls_load_verify()
static int origin_tls_load_verify (SSL_CTX * ctx, const ngx_str_t * ca) static
Definition at line 51 of file origin_connection.c.
References ngx_memcpy, PATH_MAX, and stat().
Referenced by brix_cache_origin_tls_upgrade().