nginx-xrootd: src/fs/cache/origin_protocol_bootstrap.c File Reference
origin_protocol_bootstrap.c File Reference
#include "cache_internal.h"
#include "protocols/root/protocol/bootstrap_pack.h"
#include "core/compat/fattr_codec.h"
#include "protocols/root/protocol/frame_hdr.h"
#include "auth/gsi/gsi_core.h"
#include "protocols/root/protocol/gsi.h"
#include "auth/sss/sss_keytab_kernel.h"
#include <stdio.h>
#include <errno.h>
#include <fcntl.h>
#include <inttypes.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <openssl/bio.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
#include <openssl/x509_vfy.h>
#include <openssl/evp.h>
#include <openssl/err.h>
Data Structures
struct origin_frame_t
struct origin_auth_advert_t
Functions
static const char * cache_origin_gsi_parms (const char *parms, size_t plen)
static int origin_expect_frame (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, uint32_t max_dlen, const char *fail_msg, origin_frame_t *fr)
static int origin_bs_handshake (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc)
static int origin_bs_protocol (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc)
static int origin_bs_login (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, origin_frame_t *fr)
static void origin_bs_parse_advert (const u_char *parms, size_t plen, origin_auth_advert_t *ad)
static const char * origin_bs_auth_fail_msg (const brix_cache_fill_t *t)
static int origin_bs_auth_dispatch (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const origin_auth_advert_t *ad)
static int origin_bs_authmore_fallback (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc)
int brix_cache_origin_bootstrap (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc)
Function Documentation
brix_cache_origin_bootstrap()
int brix_cache_origin_bootstrap (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc)
Definition at line 355 of file origin_protocol_bootstrap.c.
References origin_frame_t::body, brix_cache_set_error(), BRIX_SESSION_ID_LEN, origin_frame_t::dlen, kXR_authmore, kXR_ok, kXR_ServerError, origin_auth_advert_t::needs_auth, origin_bs_auth_dispatch(), origin_bs_authmore_fallback(), origin_bs_handshake(), origin_bs_login(), origin_bs_parse_advert(), origin_bs_protocol(), and origin_frame_t::status.
Referenced by proxy_gsi_login_thread(), sd_xroot_origin_open(), sd_xroot_session(), and sd_xroot_staged_connect_open().
cache_origin_gsi_parms()
static const char * cache_origin_gsi_parms (const char * parms, size_t plen) static
Definition at line 34 of file origin_protocol_bootstrap.c.
Referenced by origin_bs_parse_advert().
origin_bs_auth_dispatch()
static int origin_bs_auth_dispatch (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const origin_auth_advert_t * ad) static
Definition at line 274 of file origin_protocol_bootstrap.c.
References brix_cache_origin_auth_gsi(), brix_cache_origin_auth_sss(), brix_cache_origin_auth_ztn(), brix_cache_set_error(), brix_cache_fill_t::conf, brix_cache_fill_t::cred_bearer, brix_cache_fill_t::cred_x509_proxy, origin_auth_advert_t::gsi_parms, origin_auth_advert_t::has_gsi, origin_auth_advert_t::has_sss, origin_auth_advert_t::has_ztn, kXR_AuthFailed, and origin_bs_auth_fail_msg().
Referenced by brix_cache_origin_bootstrap().
origin_bs_auth_fail_msg()
static const char * origin_bs_auth_fail_msg (const brix_cache_fill_t * t) static
Definition at line 249 of file origin_protocol_bootstrap.c.
References brix_cache_fill_t::conf.
Referenced by origin_bs_auth_dispatch().
origin_bs_authmore_fallback()
static int origin_bs_authmore_fallback (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc) static
Definition at line 320 of file origin_protocol_bootstrap.c.
References brix_cache_origin_auth_ztn(), brix_cache_set_error(), brix_cache_fill_t::conf, brix_cache_fill_t::cred_bearer, brix_cache_fill_t::cred_x509_proxy, and kXR_AuthFailed.
Referenced by brix_cache_origin_bootstrap().
origin_bs_handshake()
static int origin_bs_handshake (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc) static
Definition at line 100 of file origin_protocol_bootstrap.c.
References origin_frame_t::body, brix_cache_io_send(), brix_cache_set_error(), kXR_ServerError, origin_expect_frame(), and xrd_pack_handshake().
Referenced by brix_cache_origin_bootstrap().
origin_bs_login()
static int origin_bs_login (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, origin_frame_t * fr) static
Definition at line 191 of file origin_protocol_bootstrap.c.
References origin_frame_t::body, brix_cache_io_send(), brix_cache_read_response(), brix_cache_set_error(), origin_frame_t::dlen, kXR_ServerError, kXR_ver005, origin_frame_t::status, and xrd_pack_login_request().
Referenced by brix_cache_origin_bootstrap().
origin_bs_parse_advert()
static void origin_bs_parse_advert (const u_char * parms, size_t plen, origin_auth_advert_t * ad) static
Definition at line 218 of file origin_protocol_bootstrap.c.
References cache_origin_gsi_parms(), origin_auth_advert_t::gsi_parms, origin_auth_advert_t::has_gsi, origin_auth_advert_t::has_sss, origin_auth_advert_t::has_ztn, origin_auth_advert_t::needs_auth, and ngx_memcpy.
Referenced by brix_cache_origin_bootstrap().
origin_bs_protocol()
static int origin_bs_protocol (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc) static
Definition at line 136 of file origin_protocol_bootstrap.c.
References origin_frame_t::body, brix_cache_io_send(), brix_cache_origin_tls_upgrade(), brix_cache_set_error(), brix_cache_fill_t::conf, origin_frame_t::dlen, ServerProtocolBody::flags, kXR_ableTLS, kXR_gotoTLS, kXR_ServerError, kXR_TLSRequired, origin_expect_frame(), and xrd_pack_protocol_request().
Referenced by brix_cache_origin_bootstrap().
origin_expect_frame()
static int origin_expect_frame (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, uint32_t max_dlen, const char * fail_msg, origin_frame_t * fr) static
Definition at line 79 of file origin_protocol_bootstrap.c.
References origin_frame_t::body, brix_cache_read_response(), brix_cache_set_error(), origin_frame_t::dlen, kXR_ok, kXR_ServerError, and origin_frame_t::status.
Referenced by origin_bs_handshake(), and origin_bs_protocol().