nginx-xrootd: src/fs/cache/origin_ns.c File Reference
origin_ns.c File Reference
#include "cache_internal.h"
#include "protocols/root/protocol/bootstrap_pack.h"
#include "core/compat/fattr_codec.h"
#include "protocols/root/protocol/frame_hdr.h"
#include <endian.h>
#include <errno.h>
#include <inttypes.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Functions
static int origin_request (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, uint16_t requestid, const uint8_t body[16], const void *payload, size_t plen, uint16_t *status, u_char **rbody, uint32_t *rdlen, size_t rmax)
static int origin_status_errno (uint16_t status, const u_char *body, uint32_t dlen)
int brix_cache_origin_rename (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *src, const char *dst)
int brix_cache_origin_rm (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *path)
int brix_cache_origin_rmdir (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *path)
static u_char * origin_fattr_payload (const char *path, const char *name, const void *val, size_t vlen, int with_value, size_t *plen)
ssize_t brix_cache_origin_getfattr (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *path, const char *name, void *buf, size_t cap)
ssize_t brix_cache_origin_listfattr (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *path, void *buf, size_t cap)
static int origin_fattr_set_or_del (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *path, const char *name, const void *val, size_t vlen, int with_value, uint8_t subcode)
int brix_cache_origin_setfattr (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *path, const char *name, const void *val, size_t vlen)
int brix_cache_origin_delfattr (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *path, const char *name)
Function Documentation
brix_cache_origin_delfattr()
int brix_cache_origin_delfattr (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * path, const char * name)
Definition at line 378 of file origin_ns.c.
References kXR_fattrDel, name, and origin_fattr_set_or_del().
Referenced by sd_xroot_removexattr().
brix_cache_origin_getfattr()
ssize_t brix_cache_origin_getfattr (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * path, const char * name, void * buf, size_t cap)
Definition at line 231 of file origin_ns.c.
References kXR_fattr, kXR_fattrGet, kXR_ok, name, origin_fattr_payload(), origin_request(), origin_status_errno(), xrdw_fattr_req_t::subcode, xrdp_fattr_nvec_parse(), XRDW_BODY_LEN, and xrdw_fattr_req_pack().
Referenced by sd_xroot_getxattr().
brix_cache_origin_listfattr()
ssize_t brix_cache_origin_listfattr (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * path, void * buf, size_t cap)
Definition at line 286 of file origin_ns.c.
References kXR_fattr, kXR_fattrList, kXR_ok, origin_request(), origin_status_errno(), xrdw_fattr_req_t::subcode, XRDW_BODY_LEN, and xrdw_fattr_req_pack().
Referenced by sd_xroot_listxattr().
brix_cache_origin_rename()
int brix_cache_origin_rename (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * src, const char * dst)
Definition at line 86 of file origin_ns.c.
References xrdw_twopath_req_t::arg1len, kXR_mv, kXR_ok, origin_request(), origin_status_errno(), XRDW_BODY_LEN, and xrdw_twopath_req_pack().
Referenced by sd_xroot_rename().
brix_cache_origin_rm()
int brix_cache_origin_rm (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * path)
Definition at line 135 of file origin_ns.c.
References kXR_ok, kXR_rm, origin_request(), origin_status_errno(), and XRDW_BODY_LEN.
Referenced by sd_xroot_unlink().
brix_cache_origin_rmdir()
int brix_cache_origin_rmdir (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * path)
Definition at line 171 of file origin_ns.c.
References kXR_ok, kXR_rmdir, origin_request(), origin_status_errno(), and XRDW_BODY_LEN.
Referenced by sd_xroot_unlink().
brix_cache_origin_setfattr()
int brix_cache_origin_setfattr (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * path, const char * name, const void * val, size_t vlen)
Definition at line 369 of file origin_ns.c.
References kXR_fattrSet, name, and origin_fattr_set_or_del().
Referenced by sd_xroot_setxattr().
origin_fattr_payload()
static u_char * origin_fattr_payload (const char * path, const char * name, const void * val, size_t vlen, int with_value, size_t * plen) static
Definition at line 204 of file origin_ns.c.
References name.
Referenced by brix_cache_origin_getfattr(), and origin_fattr_set_or_del().
origin_fattr_set_or_del()
static int origin_fattr_set_or_del (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * path, const char * name, const void * val, size_t vlen, int with_value, uint8_t subcode) static
Definition at line 324 of file origin_ns.c.
References kXR_fattr, kXR_fattrDel, kXR_ok, name, origin_fattr_payload(), origin_request(), origin_status_errno(), xrdw_fattr_req_t::subcode, xrdp_fattr_nvec_parse(), XRDW_BODY_LEN, and xrdw_fattr_req_pack().
Referenced by brix_cache_origin_delfattr(), and brix_cache_origin_setfattr().
origin_request()
static int origin_request (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, uint16_t requestid, const uint8_t body[16], const void * payload, size_t plen, uint16_t * status, u_char ** rbody, uint32_t * rdlen, size_t rmax) static
Definition at line 28 of file origin_ns.c.
References ClientRequestHdr::body, brix_cache_io_send(), brix_cache_read_response(), ClientRequestHdr::dlen, ClientRequestHdr::requestid, ClientRequestHdr::streamid, and XRDW_BODY_LEN.
Referenced by brix_cache_origin_getfattr(), brix_cache_origin_listfattr(), brix_cache_origin_rename(), brix_cache_origin_rm(), brix_cache_origin_rmdir(), and origin_fattr_set_or_del().
origin_status_errno()
static int origin_status_errno (uint16_t status, const u_char * body, uint32_t dlen) static
Definition at line 65 of file origin_ns.c.
References kXR_error, kXR_isDirectory, kXR_ItExists, kXR_NotAuthorized, kXR_NotFound, and xrd_error_body_decode().
Referenced by brix_cache_origin_getfattr(), brix_cache_origin_listfattr(), brix_cache_origin_rename(), brix_cache_origin_rm(), brix_cache_origin_rmdir(), and origin_fattr_set_or_del().