nginx-xrootd: src/fs/cache/origin_response.c File Reference
origin_response.c File Reference
#include "cache_internal.h"
#include "protocols/root/protocol/frame_hdr.h"
#include <errno.h>
#include <stdlib.h>
Functions
int brix_cache_read_response (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, uint16_t *status, u_char **body, uint32_t *dlen, uint32_t max_body)
void brix_cache_set_origin_error (brix_cache_fill_t *t, u_char *body, uint32_t dlen, const char *fallback)
Function Documentation
brix_cache_read_response()
int brix_cache_read_response (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, uint16_t * status, u_char ** body, uint32_t * dlen, uint32_t max_body)
Definition at line 31 of file origin_response.c.
References brix_cache_io_recv_exact(), brix_cache_set_error(), ServerResponseHdr::dlen, kXR_NoMemory, kXR_ServerError, and ServerResponseHdr::status.
Referenced by brix_cache_origin_auth_sss(), brix_cache_origin_auth_ztn(), brix_cache_origin_close_file(), brix_cache_origin_dirlist(), brix_cache_origin_open(), brix_cache_origin_open_write(), brix_cache_origin_query_checksum(), brix_cache_origin_read_chunk(), brix_cache_origin_sync(), brix_cache_origin_truncate(), brix_cache_origin_write_chunk(), origin_bs_login(), origin_expect_frame(), origin_request(), originauth_gsi_read_cert(), and originauth_gsi_read_final().
brix_cache_set_origin_error()
void brix_cache_set_origin_error (brix_cache_fill_t * t, u_char * body, uint32_t dlen, const char * fallback)
Definition at line 79 of file origin_response.c.
References brix_cache_set_error(), kXR_ServerError, ngx_memcpy, and xrd_error_body_decode().
Referenced by brix_cache_origin_auth_sss(), brix_cache_origin_auth_ztn(), brix_cache_origin_open(), brix_cache_origin_open_write(), brix_cache_origin_read_chunk(), brix_cache_origin_sync(), brix_cache_origin_truncate(), brix_cache_origin_write_chunk(), originauth_gsi_read_cert(), and originauth_gsi_read_final().