nginx-xrootd: src/protocols/cvmfs/origin_probe.c File Reference
origin_probe.c File Reference
#include "cvmfs.h"
#include "origin_geo.h"
#include "core/aio/aio.h"
#include "fs/backend/cache/sd_cache.h"
#include "fs/backend/http/sd_http.h"
#include "fs/vfs/vfs_backend_registry.h"
#include <netdb.h>
#include <poll.h>
#include <time.h>
Data Structures
struct cvmfs_rtt_reg_t
struct cvmfs_probe_ctx_t
Macros
#define CVMFS_PROBE_TIMEOUT_MS 2000
#define CVMFS_PROBE_FAIL_US (CVMFS_PROBE_TIMEOUT_MS * 1000L * 4)
#define CVMFS_PROBE_MAX_EXPORTS 8
Functions
void brix_cvmfs_rtt_register (const char *root_canon, time_t interval, const ngx_str_t *pool_name)
long brix_cvmfs_connect_rtt_us (const char *host, int port, int timeout_ms)
static void cvmfs_probe_thread (void *data, ngx_log_t *log)
static int cvmfs_rank_zero_index (const int *ranks, int n)
static void cvmfs_probe_table (const cvmfs_probe_ctx_t *pc, const double *metric, const int *ranks, char *buf, size_t cap)
static void cvmfs_probe_log_reachability (cvmfs_probe_ctx_t *pc, ngx_log_t *log)
static brix_sd_instance_t * cvmfs_unwrap_http (brix_sd_instance_t *inst)
static void cvmfs_probe_done (ngx_event_t *ev)
static void cvmfs_probe_fire (ngx_event_t *ev)
ngx_int_t brix_cvmfs_rtt_init_worker (ngx_cycle_t *cycle)
Variables
static cvmfs_rtt_reg_t cvmfs_rtt_regs [8]
static ngx_uint_t cvmfs_rtt_regs_n
Macro Definition Documentation
CVMFS_PROBE_FAIL_US
#define CVMFS_PROBE_FAIL_US (CVMFS_PROBE_TIMEOUT_MS * 1000L * 4)
Definition at line 29 of file origin_probe.c.
CVMFS_PROBE_MAX_EXPORTS
#define CVMFS_PROBE_MAX_EXPORTS 8
Definition at line 30 of file origin_probe.c.
CVMFS_PROBE_TIMEOUT_MS
#define CVMFS_PROBE_TIMEOUT_MS 2000
Definition at line 28 of file origin_probe.c.
Function Documentation
brix_cvmfs_connect_rtt_us()
long brix_cvmfs_connect_rtt_us (const char * host, int port, int timeout_ms)
Definition at line 99 of file origin_probe.c.
References close(), host, and port.
Referenced by cvmfs_geo_thread(), and cvmfs_probe_thread().
brix_cvmfs_rtt_init_worker()
ngx_int_t brix_cvmfs_rtt_init_worker (ngx_cycle_t * cycle)
Definition at line 333 of file origin_probe.c.
References brix_vfs_backend_http_endpoint_at(), cvmfs_probe_done(), cvmfs_probe_fire(), cvmfs_probe_thread(), cvmfs_rtt_regs, cvmfs_rtt_regs_n, host, cvmfs_probe_ctx_t::hosts, cvmfs_probe_ctx_t::n, port, cvmfs_probe_ctx_t::ports, cvmfs_probe_ctx_t::prev_ranks, cvmfs_probe_ctx_t::reg, cvmfs_rtt_reg_t::root, SD_HTTP_EP_MAX, cvmfs_probe_ctx_t::task, and cvmfs_probe_ctx_t::timer.
Referenced by ngx_http_brix_cvmfs_init_process().
brix_cvmfs_rtt_register()
void brix_cvmfs_rtt_register (const char * root_canon, time_t interval, const ngx_str_t * pool_name)
Definition at line 44 of file origin_probe.c.
References CVMFS_PROBE_MAX_EXPORTS, cvmfs_rtt_regs, cvmfs_rtt_regs_n, cvmfs_rtt_reg_t::interval, ngx_memcpy, cvmfs_rtt_reg_t::pool, and cvmfs_rtt_reg_t::root.
Referenced by cvmfs_merge_cache().
cvmfs_probe_done()
static void cvmfs_probe_done (ngx_event_t * ev) static
Definition at line 245 of file origin_probe.c.
References brix_cvmfs_rank_by_metric(), brix_vfs_backend_resolve(), CVMFS_PROBE_FAIL_US, cvmfs_probe_log_reachability(), cvmfs_probe_table(), cvmfs_rank_zero_index(), cvmfs_unwrap_http(), cvmfs_probe_ctx_t::ewma_us, cvmfs_probe_ctx_t::hosts, cvmfs_rtt_reg_t::interval, cvmfs_probe_ctx_t::n, cvmfs_probe_ctx_t::ports, cvmfs_probe_ctx_t::prev_ranks, cvmfs_probe_ctx_t::reg, cvmfs_rtt_reg_t::root, s, cvmfs_probe_ctx_t::sample_us, SD_HTTP_EP_MAX, sd_http_set_ranks(), and cvmfs_probe_ctx_t::timer.
Referenced by brix_cvmfs_rtt_init_worker().
cvmfs_probe_fire()
static void cvmfs_probe_fire (ngx_event_t * ev) static
Definition at line 311 of file origin_probe.c.
References cvmfs_rtt_reg_t::interval, cvmfs_rtt_reg_t::pool, cvmfs_probe_ctx_t::reg, and cvmfs_probe_ctx_t::task.
Referenced by brix_cvmfs_rtt_init_worker().
cvmfs_probe_log_reachability()
static void cvmfs_probe_log_reachability (cvmfs_probe_ctx_t * pc, ngx_log_t * log) static
Definition at line 203 of file origin_probe.c.
References CVMFS_PROBE_TIMEOUT_MS, cvmfs_probe_ctx_t::ewma_us, cvmfs_probe_ctx_t::hosts, log, cvmfs_probe_ctx_t::n, cvmfs_probe_ctx_t::ports, cvmfs_probe_ctx_t::probe_down, and cvmfs_probe_ctx_t::sample_us.
Referenced by cvmfs_probe_done().
cvmfs_probe_table()
static void cvmfs_probe_table (const cvmfs_probe_ctx_t * pc, const double * metric, const int * ranks, char * buf, size_t cap) static
Definition at line 176 of file origin_probe.c.
References cvmfs_probe_ctx_t::hosts, cvmfs_probe_ctx_t::n, cvmfs_probe_ctx_t::ports, and cvmfs_probe_ctx_t::sample_us.
Referenced by cvmfs_probe_done().
cvmfs_probe_thread()
static void cvmfs_probe_thread (void * data, ngx_log_t * log) static
Definition at line 146 of file origin_probe.c.
References brix_cvmfs_connect_rtt_us(), CVMFS_PROBE_TIMEOUT_MS, cvmfs_probe_ctx_t::hosts, log, cvmfs_probe_ctx_t::n, cvmfs_probe_ctx_t::ports, and cvmfs_probe_ctx_t::sample_us.
Referenced by brix_cvmfs_rtt_init_worker().
cvmfs_rank_zero_index()
static int cvmfs_rank_zero_index (const int * ranks, int n) static
Definition at line 160 of file origin_probe.c.
Referenced by cvmfs_probe_done().
cvmfs_unwrap_http()
static brix_sd_instance_t * cvmfs_unwrap_http (brix_sd_instance_t * inst) static
Definition at line 233 of file origin_probe.c.
References brix_sd_cache_source_instance().
Referenced by cvmfs_probe_done().
Variable Documentation
cvmfs_rtt_regs
cvmfs_rtt_reg_t cvmfs_rtt_regs[8] static
Definition at line 40 of file origin_probe.c.
Referenced by brix_cvmfs_rtt_init_worker(), and brix_cvmfs_rtt_register().
cvmfs_rtt_regs_n
ngx_uint_t cvmfs_rtt_regs_n static
Definition at line 41 of file origin_probe.c.
Referenced by brix_cvmfs_rtt_init_worker(), and brix_cvmfs_rtt_register().