nginx-xrootd: src/fs/cache/origin_write.c File Reference
origin_write.c File Reference
#include "cache_internal.h"
#include "protocols/root/protocol/bootstrap_pack.h"
#include "protocols/root/protocol/frame_hdr.h"
#include <endian.h>
#include <errno.h>
#include <inttypes.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Functions
int brix_cache_origin_open_write (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const char *path, uint16_t mode_bits, u_char fhandle[4])
void brix_cache_origin_close_file (brix_cache_origin_conn_t *oc, const u_char fhandle[4])
int brix_cache_origin_write_chunk (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const u_char fhandle[4], uint64_t offset, const u_char *data, size_t len)
int brix_cache_origin_truncate (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const u_char fhandle[4], uint64_t length)
int brix_cache_origin_sync (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const u_char fhandle[4])
int brix_cache_sink_pwrite (brix_cache_sink_t *sink, const void *buf, size_t len, off_t off)
Function Documentation
brix_cache_origin_close_file()
void brix_cache_origin_close_file (brix_cache_origin_conn_t * oc, const u_char fhandle[4])
Definition at line 123 of file origin_write.c.
References brix_cache_io_send(), brix_cache_read_response(), ClientCloseRequest::dlen, ClientCloseRequest::fhandle, kXR_close, ngx_memcpy, ClientCloseRequest::requestid, brix_cache_fill_t::result, ClientCloseRequest::streamid, and XRD_FHANDLE_LEN.
Referenced by sd_xroot_obj_teardown(), sd_xroot_server_copy(), sd_xroot_server_copy_cred(), and sd_xroot_staged_teardown().
brix_cache_origin_open_write()
int brix_cache_origin_open_write (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const char * path, uint16_t mode_bits, u_char fhandle[4])
Definition at line 28 of file origin_write.c.
References brix_cache_io_send(), brix_cache_read_response(), brix_cache_set_error(), brix_cache_set_origin_error(), BRIX_MAX_PATH, ClientOpenRequest::dlen, kXR_ArgInvalid, kXR_delete, kXR_error, kXR_mkpath, kXR_NoMemory, kXR_ok, kXR_open, kXR_open_updt, kXR_redirect, kXR_ServerError, kXR_Unsupported, xrdw_open_req_t::mode, ngx_memcpy, ClientOpenRequest::requestid, ClientOpenRequest::streamid, XRD_FHANDLE_LEN, and xrdw_open_req_pack().
Referenced by sd_xroot_origin_do_open(), sd_xroot_server_copy(), sd_xroot_server_copy_cred(), and sd_xroot_staged_connect_open().
brix_cache_origin_sync()
int brix_cache_origin_sync (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const u_char fhandle[4])
Definition at line 259 of file origin_write.c.
References brix_cache_io_send(), brix_cache_read_response(), brix_cache_set_error(), brix_cache_set_origin_error(), ClientSyncRequest::dlen, ClientSyncRequest::fhandle, kXR_error, kXR_ok, kXR_ServerError, kXR_sync, ngx_memcpy, ClientSyncRequest::requestid, ClientSyncRequest::streamid, and XRD_FHANDLE_LEN.
Referenced by sd_xroot_copy_body(), sd_xroot_fsync(), and sd_xroot_staged_commit().
brix_cache_origin_truncate()
int brix_cache_origin_truncate (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const u_char fhandle[4], uint64_t length)
Definition at line 210 of file origin_write.c.
References brix_cache_io_send(), brix_cache_read_response(), brix_cache_set_error(), brix_cache_set_origin_error(), ClientTruncateRequest::dlen, ClientTruncateRequest::fhandle, kXR_error, kXR_ok, kXR_ServerError, kXR_truncate, ngx_memcpy, ClientTruncateRequest::offset, ClientTruncateRequest::requestid, ClientTruncateRequest::streamid, and XRD_FHANDLE_LEN.
Referenced by sd_xroot_copy_body(), and sd_xroot_ftruncate().
brix_cache_origin_write_chunk()
int brix_cache_origin_write_chunk (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const u_char fhandle[4], uint64_t offset, const u_char * data, size_t len)
Definition at line 153 of file origin_write.c.
References brix_cache_io_send(), brix_cache_read_response(), brix_cache_set_error(), brix_cache_set_origin_error(), ClientWriteRequest::dlen, ClientWriteRequest::fhandle, kXR_ArgTooLong, kXR_error, kXR_ok, kXR_ServerError, kXR_write, ngx_memcpy, ClientWriteRequest::offset, ClientWriteRequest::requestid, ClientWriteRequest::streamid, and XRD_FHANDLE_LEN.
Referenced by sd_xroot_copy_body(), sd_xroot_pwrite(), and sd_xroot_staged_write().
brix_cache_sink_pwrite()
int brix_cache_sink_pwrite (brix_cache_sink_t * sink, const void * buf, size_t len, off_t off)
Definition at line 305 of file origin_write.c.
References brix_cache_fd_write_all(), brix_cache_sink_t::fd, brix_cache_sink_t::mem, brix_cache_sink_t::mem_cap, ngx_memcpy, and brix_cache_sink_t::staged.
Referenced by brix_cache_fill_copy(), and brix_cache_origin_read_chunk().