nginx-xrootd: client/lib/fs/overlay.h File Reference
overlay.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <time.h>
#include <sys/stat.h>
#include <sys/types.h>
Data Structures
struct brix_overlay
struct brix_ov_nameset
Macros
#define BRIX_OV_WH_PREFIX ".brix.wh." /* whiteout: deleted lower name */
#define BRIX_OV_OPQ_NAME ".brix.opq" /* opaque dir: don't merge lower */
#define BRIX_OV_TMP_PREFIX ".brix.tmp." /* in-flight copy-up */
#define BRIX_OV_DIRNAME ".brixwrites" /* overlay root under the mount */
#define BRIX_OV_UPPER_DIRNAME "upper" /* the path-mirroring upper tree */
Typedefs
typedef int(* brix_ov_read_fn) (void *ud, const char *rel, uint64_t off, size_t len, unsigned char *buf, size_t *outlen)
Enumerations
enum brix_ov_state { BRIX_OV_NONE = 0 , BRIX_OV_UPPER , BRIX_OV_MASKED }
Functions
int brix_overlay_init (brix_overlay *ov, int writes_fd)
void brix_overlay_close (brix_overlay *ov)
int brix_ov_name_reserved (const char *name)
int brix_overlay_classify (const brix_overlay *ov, const char *rel, struct stat *st, brix_ov_state *state)
int brix_overlay_whiteout (const brix_overlay *ov, const char *rel)
int brix_overlay_whiteout_set (const brix_overlay *ov, const char *rel)
int brix_overlay_whiteout_clear (const brix_overlay *ov, const char *rel)
int brix_overlay_mkdirs (const brix_overlay *ov, const char *rel_dir, mode_t(*mode_fn)(void *ud, const char *rel_dir), void *ud)
int brix_overlay_open (const brix_overlay *ov, const char *rel, int oflags, mode_t mode)
int brix_overlay_mkdir (const brix_overlay *ov, const char *rel, mode_t mode)
int brix_overlay_set_opaque (const brix_overlay *ov, const char *rel_dir)
int brix_overlay_unlink_upper (const brix_overlay *ov, const char *rel)
int brix_overlay_rmdir_upper (const brix_overlay *ov, const char *rel)
int brix_overlay_rename_upper (const brix_overlay *ov, const char *from, const char *to)
int brix_overlay_symlink (const brix_overlay *ov, const char *target, const char *rel)
int brix_overlay_readlink (const brix_overlay *ov, const char *rel, char *buf, size_t n)
int brix_overlay_chmod (const brix_overlay *ov, const char *rel, mode_t mode)
int brix_overlay_utimens (const brix_overlay *ov, const char *rel, const struct timespec tv[2])
int brix_overlay_truncate (const brix_overlay *ov, const char *rel, off_t len)
int brix_overlay_copyup (const brix_overlay *ov, const char *rel, const struct stat *lower_st, brix_ov_read_fn read_lower, void *ud)
int brix_overlay_read_upper (const brix_overlay *ov, const char *rel, brix_ov_nameset *set, int *opaque)
char brix_ov_nameset_flag (const brix_ov_nameset *s, const char *name)
const char * brix_ov_nameset_at (const brix_ov_nameset *s, size_t i, char *flag)
void brix_ov_nameset_free (brix_ov_nameset *s)
int brix_overlay_cli_list (const char *mountdir, FILE *out)
int brix_overlay_cli_reset (const char *mountdir)
Macro Definition Documentation
BRIX_OV_DIRNAME
#define BRIX_OV_DIRNAME ".brixwrites" /* overlay root under the mount */
Definition at line 38 of file overlay.h.
BRIX_OV_OPQ_NAME
#define BRIX_OV_OPQ_NAME ".brix.opq" /* opaque dir: don't merge lower */
Definition at line 36 of file overlay.h.
BRIX_OV_TMP_PREFIX
#define BRIX_OV_TMP_PREFIX ".brix.tmp." /* in-flight copy-up */
Definition at line 37 of file overlay.h.
BRIX_OV_UPPER_DIRNAME
#define BRIX_OV_UPPER_DIRNAME "upper" /* the path-mirroring upper tree */
Definition at line 39 of file overlay.h.
BRIX_OV_WH_PREFIX
#define BRIX_OV_WH_PREFIX ".brix.wh." /* whiteout: deleted lower name */
Definition at line 35 of file overlay.h.
Typedef Documentation
brix_ov_read_fn
typedef int(* brix_ov_read_fn) (void *ud, const char *rel, uint64_t off, size_t len, unsigned char *buf, size_t *outlen)
Definition at line 118 of file overlay.h.
Enumeration Type Documentation
brix_ov_state
enum brix_ov_state
Enumerator
BRIX_OV_NONE
BRIX_OV_UPPER
BRIX_OV_MASKED
Definition at line 42 of file overlay.h.
Function Documentation
brix_ov_name_reserved()
int brix_ov_name_reserved (const char * name)
Definition at line 47 of file overlay.c.
References BRIX_OV_OPQ_NAME, BRIX_OV_TMP_PREFIX, BRIX_OV_WH_PREFIX, and name.
Referenced by ov_clear_markers(), rw_reserved(), and test_reserved_names().
brix_ov_nameset_at()
const char * brix_ov_nameset_at (const brix_ov_nameset * s, size_t i, char * flag)
Definition at line 527 of file overlay.c.
References s.
Referenced by rw_readdir(), rw_rmdir(), and test_nameset().
brix_ov_nameset_flag()
char brix_ov_nameset_flag (const brix_ov_nameset * s, const char * name)
Definition at line 517 of file overlay.c.
References name, and s.
Referenced by rw_lowcount_cb(), rw_lowdir_emit(), and test_nameset().
brix_ov_nameset_free()
void brix_ov_nameset_free (brix_ov_nameset * s)
Definition at line 540 of file overlay.c.
References s.
Referenced by brix_overlay_read_upper(), rw_readdir(), rw_rename(), rw_rmdir(), and test_nameset().
brix_overlay_chmod()
int brix_overlay_chmod (const brix_overlay * ov, const char * rel, mode_t mode)
Definition at line 367 of file overlay.c.
References close(), fstatat(), mode, OV_NAME_MAX, ov_walk_parent(), and stat().
Referenced by rw_apply_chmod(), and test_mutations().
brix_overlay_classify()
int brix_overlay_classify (const brix_overlay * ov, const char * rel, struct stat * st, brix_ov_state * state)
Definition at line 142 of file overlay.c.
References BRIX_OV_MASKED, BRIX_OV_NONE, BRIX_OV_OPQ_NAME, BRIX_OV_UPPER, BRIX_OV_WH_PREFIX, close(), fstat(), fstatat(), name, openat(), ov_marker_at(), OV_NAME_MAX, ov_split(), ov_wh_name(), stat(), and brix_overlay::upper_fd.
Referenced by cls(), and rw_classify().
brix_overlay_cli_list()
int brix_overlay_cli_list (const char * mountdir, FILE * out)
Definition at line 621 of file overlay.c.
brix_overlay_cli_reset()
int brix_overlay_cli_reset (const char * mountdir)
Definition at line 658 of file overlay.c.
brix_overlay_close()
void brix_overlay_close (brix_overlay * ov)
Definition at line 131 of file overlay.c.
References close(), and brix_overlay::upper_fd.
Referenced by brixcvmfs_teardown_rw(), and fix_down().
brix_overlay_copyup()
int brix_overlay_copyup (const brix_overlay * ov, const char * rel, const struct stat * lower_st, brix_ov_read_fn read_lower, void * ud)
Definition at line 440 of file overlay.c.
References BRIX_OV_TMP_PREFIX, brix_overlay_whiteout_clear(), close(), openat(), ov_copyup_stream(), OV_NAME_MAX, and ov_walk_parent_mk().
Referenced by rw_copyup(), and test_copyup().
brix_overlay_init()
int brix_overlay_init (brix_overlay * ov, int writes_fd)
Definition at line 121 of file overlay.c.
References BRIX_OV_UPPER_DIRNAME, openat(), brix_overlay::upper_fd, and brix_overlay::writes_fd.
Referenced by brixcvmfs_setup_rw(), and fix_up().
brix_overlay_mkdir()
int brix_overlay_mkdir (const brix_overlay * ov, const char * rel, mode_t mode)
Definition at line 270 of file overlay.c.
References close(), mode, OV_NAME_MAX, and ov_walk_parent().
Referenced by rw_mkdir(), and test_mutations().
brix_overlay_mkdirs()
int brix_overlay_mkdirs (const brix_overlay * ov, const char * rel_dir, mode_t(*)(void *ud, const char *rel_dir) mode_fn, void * ud)
Definition at line 238 of file overlay.c.
References close(), fstatat(), OV_NAME_MAX, ov_walk_parent_mk(), and stat().
Referenced by rw_ensure_parents(), rw_meta_apply(), and test_mutations().
brix_overlay_open()
int brix_overlay_open (const brix_overlay * ov, const char * rel, int oflags, mode_t mode)
Definition at line 259 of file overlay.c.
References close(), mode, openat(), OV_NAME_MAX, and ov_walk_parent().
Referenced by brix_overlay_truncate(), rw_open_common(), test_copyup(), and test_mutations().
brix_overlay_read_upper()
int brix_overlay_read_upper (const brix_overlay * ov, const char * rel, brix_ov_nameset * set, int * opaque)
Definition at line 488 of file overlay.c.
References brix_ov_nameset_free(), BRIX_OV_OPQ_NAME, BRIX_OV_TMP_PREFIX, BRIX_OV_WH_PREFIX, close(), ov_nameset_add(), and ov_open_dir().
Referenced by rw_readdir(), rw_rename(), rw_rmdir(), and test_nameset().
brix_overlay_readlink()
int brix_overlay_readlink (const brix_overlay * ov, const char * rel, char * buf, size_t n)
Definition at line 354 of file overlay.c.
References close(), OV_NAME_MAX, and ov_walk_parent().
Referenced by rw_readlink(), and test_mutations().
brix_overlay_rename_upper()
int brix_overlay_rename_upper (const brix_overlay * ov, const char * from, const char * to)
Definition at line 331 of file overlay.c.
References close(), OV_NAME_MAX, and ov_walk_parent().
Referenced by rw_rename(), and test_mutations().
brix_overlay_rmdir_upper()
int brix_overlay_rmdir_upper (const brix_overlay * ov, const char * rel)
Definition at line 316 of file overlay.c.
References close(), ov_clear_markers(), OV_NAME_MAX, ov_open_dir(), and ov_walk_parent().
Referenced by rw_rmdir(), and test_mutations().
brix_overlay_set_opaque()
int brix_overlay_set_opaque (const brix_overlay * ov, const char * rel_dir)
Definition at line 279 of file overlay.c.
References BRIX_OV_OPQ_NAME, close(), openat(), and ov_open_dir().
Referenced by rw_mkdir(), and test_mutations().
brix_overlay_symlink()
int brix_overlay_symlink (const brix_overlay * ov, const char * target, const char * rel)
Definition at line 344 of file overlay.c.
References close(), OV_NAME_MAX, and ov_walk_parent().
Referenced by rw_symlink(), and test_mutations().
brix_overlay_truncate()
int brix_overlay_truncate (const brix_overlay * ov, const char * rel, off_t len)
Definition at line 391 of file overlay.c.
References brix_overlay_open(), and close().
Referenced by rw_truncate(), and test_mutations().
brix_overlay_unlink_upper()
int brix_overlay_unlink_upper (const brix_overlay * ov, const char * rel)
Definition at line 289 of file overlay.c.
References close(), OV_NAME_MAX, and ov_walk_parent().
Referenced by rw_unlink(), and test_mutations().
brix_overlay_utimens()
int brix_overlay_utimens (const brix_overlay * ov, const char * rel, const struct timespec tv[2])
Definition at line 381 of file overlay.c.
References close(), OV_NAME_MAX, and ov_walk_parent().
Referenced by rw_apply_utimens(), and test_mutations().
brix_overlay_whiteout()
int brix_overlay_whiteout (const brix_overlay * ov, const char * rel)
Definition at line 201 of file overlay.c.
References BRIX_OV_WH_PREFIX, close(), ov_marker_at(), OV_NAME_MAX, ov_walk_parent(), and ov_wh_name().
Referenced by test_classify(), and test_copyup().
brix_overlay_whiteout_clear()
int brix_overlay_whiteout_clear (const brix_overlay * ov, const char * rel)
Definition at line 399 of file overlay.c.
References BRIX_OV_WH_PREFIX, close(), OV_NAME_MAX, ov_walk_parent(), and ov_wh_name().
Referenced by brix_overlay_copyup(), rw_mkdir(), rw_open_common(), rw_rename(), rw_symlink(), and test_classify().
brix_overlay_whiteout_set()
int brix_overlay_whiteout_set (const brix_overlay * ov, const char * rel)
Definition at line 212 of file overlay.c.
References BRIX_OV_WH_PREFIX, close(), openat(), OV_NAME_MAX, ov_walk_parent_mk(), and ov_wh_name().
Referenced by rw_rename(), rw_rmdir(), rw_unlink(), test_classify(), test_copyup(), and test_mutations().