nginx-xrootd: client/lib/fs/overlay.c File Reference
overlay.c File Reference
#include "fs/overlay.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/xattr.h>
Macros
#define _GNU_SOURCE
#define OV_NAME_MAX 256 /* one path component incl. NUL */
#define OV_COPYUP_CHUNK (1024u * 1024u)
Functions
static int ov_split (const char **relp, char *name, size_t cap)
int brix_ov_name_reserved (const char *name)
static void ov_wh_name (const char *name, char *buf, size_t cap)
static int ov_marker_at (int dirfd, const char *marker)
static int ov_descend_dir (int dirfd, const char *name, int mk, mode_t(*mode_fn)(void *ud, const char *rel_dir), void *ud, const char *prefix)
static int ov_walk_parent_mk (const brix_overlay *ov, const char *rel, char *leaf, size_t leafcap, int mk, mode_t(*mode_fn)(void *ud, const char *rel_dir), void *ud)
static int ov_walk_parent (const brix_overlay *ov, const char *rel, char *leaf, size_t leafcap)
int brix_overlay_init (brix_overlay *ov, int writes_fd)
void brix_overlay_close (brix_overlay *ov)
static int ov_classify_root (const brix_overlay *ov, struct stat *st, brix_ov_state *state)
static int ov_descend_child (int cur, const char *name, int *opaque)
int brix_overlay_classify (const brix_overlay *ov, const char *rel, struct stat *st, brix_ov_state *state)
int brix_overlay_whiteout (const brix_overlay *ov, const char *rel)
int brix_overlay_whiteout_set (const brix_overlay *ov, const char *rel)
static int ov_open_dir (const brix_overlay *ov, const char *rel_dir)
int brix_overlay_mkdirs (const brix_overlay *ov, const char *rel_dir, mode_t(*mode_fn)(void *ud, const char *rel_dir), void *ud)
int brix_overlay_open (const brix_overlay *ov, const char *rel, int oflags, mode_t mode)
int brix_overlay_mkdir (const brix_overlay *ov, const char *rel, mode_t mode)
int brix_overlay_set_opaque (const brix_overlay *ov, const char *rel_dir)
int brix_overlay_unlink_upper (const brix_overlay *ov, const char *rel)
static int ov_clear_markers (int dirfd)
int brix_overlay_rmdir_upper (const brix_overlay *ov, const char *rel)
int brix_overlay_rename_upper (const brix_overlay *ov, const char *from, const char *to)
int brix_overlay_symlink (const brix_overlay *ov, const char *target, const char *rel)
int brix_overlay_readlink (const brix_overlay *ov, const char *rel, char *buf, size_t n)
int brix_overlay_chmod (const brix_overlay *ov, const char *rel, mode_t mode)
int brix_overlay_utimens (const brix_overlay *ov, const char *rel, const struct timespec tv[2])
int brix_overlay_truncate (const brix_overlay *ov, const char *rel, off_t len)
int brix_overlay_whiteout_clear (const brix_overlay *ov, const char *rel)
static int ov_copyup_stream (int fd, const char *rel, uint64_t size, brix_ov_read_fn read_lower, void *ud)
int brix_overlay_copyup (const brix_overlay *ov, const char *rel, const struct stat *lower_st, brix_ov_read_fn read_lower, void *ud)
static int ov_nameset_add (brix_ov_nameset *s, char flag, const char *name)
int brix_overlay_read_upper (const brix_overlay *ov, const char *rel, brix_ov_nameset *set, int *opaque)
char brix_ov_nameset_flag (const brix_ov_nameset *s, const char *name)
const char * brix_ov_nameset_at (const brix_ov_nameset *s, size_t i, char *flag)
void brix_ov_nameset_free (brix_ov_nameset *s)
static int ov_cli_guard (const char *mountdir, char **upper_out)
static void ov_cli_kind (const char *mountdir, const char *rel, char *kind, size_t cap)
static int ov_cli_list_entry (const char *mountdir, const char *upper_root, const char *rel, const char *dirp, const char *name, FILE *out)
static int ov_cli_list_dir (const char *mountdir, const char *upper_root, const char *rel, FILE *out)
int brix_overlay_cli_list (const char *mountdir, FILE *out)
static int ov_cli_reset_contents (int dirfd)
int brix_overlay_cli_reset (const char *mountdir)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 15 of file overlay.c.
OV_COPYUP_CHUNK
#define OV_COPYUP_CHUNK (1024u * 1024u)
Definition at line 467 of file overlay.c.
OV_NAME_MAX
#define OV_NAME_MAX 256 /* one path component incl. NUL */
Definition at line 27 of file overlay.c.
Function Documentation
brix_ov_name_reserved()
int brix_ov_name_reserved (const char * name)
Definition at line 47 of file overlay.c.
References BRIX_OV_OPQ_NAME, BRIX_OV_TMP_PREFIX, BRIX_OV_WH_PREFIX, and name.
Referenced by ov_clear_markers(), rw_reserved(), and test_reserved_names().
brix_ov_nameset_at()
const char * brix_ov_nameset_at (const brix_ov_nameset * s, size_t i, char * flag)
Definition at line 582 of file overlay.c.
References s.
Referenced by rw_dir_merged_nonempty(), rw_readdir(), and test_nameset().
brix_ov_nameset_flag()
char brix_ov_nameset_flag (const brix_ov_nameset * s, const char * name)
Definition at line 572 of file overlay.c.
References name, and s.
Referenced by rw_lowcount_cb(), rw_lowdir_emit(), and test_nameset().
brix_ov_nameset_free()
void brix_ov_nameset_free (brix_ov_nameset * s)
Definition at line 595 of file overlay.c.
References s.
Referenced by brix_overlay_read_upper(), rw_dir_merged_nonempty(), rw_readdir(), rw_rename_dir(), and test_nameset().
brix_overlay_chmod()
int brix_overlay_chmod (const brix_overlay * ov, const char * rel, mode_t mode)
Definition at line 422 of file overlay.c.
References close(), fstatat(), OV_NAME_MAX, ov_walk_parent(), and stat().
Referenced by rw_apply_chmod(), and test_mut_attrs().
brix_overlay_classify()
int brix_overlay_classify (const brix_overlay * ov, const char * rel, struct stat * st, brix_ov_state * state)
Definition at line 203 of file overlay.c.
References BRIX_OV_MASKED, BRIX_OV_NONE, BRIX_OV_UPPER, BRIX_OV_WH_PREFIX, close(), fstatat(), name, openat(), ov_classify_root(), ov_descend_child(), ov_marker_at(), OV_NAME_MAX, ov_split(), ov_wh_name(), stat(), and brix_overlay::upper_fd.
Referenced by cls(), and rw_classify().
brix_overlay_cli_list()
int brix_overlay_cli_list (const char * mountdir, FILE * out)
Definition at line 706 of file overlay.c.
References ov_cli_guard(), and ov_cli_list_dir().
Referenced by main(), and test_cli().
brix_overlay_cli_reset()
int brix_overlay_cli_reset (const char * mountdir)
Definition at line 743 of file overlay.c.
References close(), open(), ov_cli_guard(), and ov_cli_reset_contents().
Referenced by main(), and test_cli().
brix_overlay_close()
void brix_overlay_close (brix_overlay * ov)
Definition at line 151 of file overlay.c.
References close(), and brix_overlay::upper_fd.
Referenced by brixcvmfs_teardown_rw(), and fix_down().
brix_overlay_copyup()
int brix_overlay_copyup (const brix_overlay * ov, const char * rel, const struct stat * lower_st, brix_ov_read_fn read_lower, void * ud)
Definition at line 495 of file overlay.c.
References BRIX_OV_TMP_PREFIX, brix_overlay_whiteout_clear(), close(), openat(), ov_copyup_stream(), OV_NAME_MAX, and ov_walk_parent_mk().
Referenced by rw_copyup(), and test_copyup().
brix_overlay_init()
int brix_overlay_init (brix_overlay * ov, int writes_fd)
Definition at line 141 of file overlay.c.
References BRIX_OV_UPPER_DIRNAME, openat(), brix_overlay::upper_fd, and brix_overlay::writes_fd.
Referenced by brixcvmfs_setup_rw(), and fix_up().
brix_overlay_mkdir()
int brix_overlay_mkdir (const brix_overlay * ov, const char * rel, mode_t mode)
Definition at line 325 of file overlay.c.
References close(), OV_NAME_MAX, and ov_walk_parent().
Referenced by rw_mkdir(), and test_mut_mkdirs_create().
brix_overlay_mkdirs()
int brix_overlay_mkdirs (const brix_overlay * ov, const char * rel_dir, mode_t(*)(void *ud, const char *rel_dir) mode_fn, void * ud)
Definition at line 293 of file overlay.c.
References close(), fstatat(), OV_NAME_MAX, ov_walk_parent_mk(), and stat().
Referenced by rw_ensure_parents(), rw_meta_apply(), and test_mut_mkdirs_create().
brix_overlay_open()
int brix_overlay_open (const brix_overlay * ov, const char * rel, int oflags, mode_t mode)
Definition at line 314 of file overlay.c.
References close(), openat(), OV_NAME_MAX, and ov_walk_parent().
Referenced by brix_overlay_truncate(), rw_open_create(), rw_open_lower(), rw_open_upper(), test_copyup(), and test_mut_mkdirs_create().
brix_overlay_read_upper()
int brix_overlay_read_upper (const brix_overlay * ov, const char * rel, brix_ov_nameset * set, int * opaque)
Definition at line 543 of file overlay.c.
References brix_ov_nameset_free(), BRIX_OV_OPQ_NAME, BRIX_OV_TMP_PREFIX, BRIX_OV_WH_PREFIX, close(), ov_nameset_add(), and ov_open_dir().
Referenced by rw_dir_merged_nonempty(), rw_readdir(), rw_rename_dir(), and test_nameset().
brix_overlay_readlink()
int brix_overlay_readlink (const brix_overlay * ov, const char * rel, char * buf, size_t n)
Definition at line 409 of file overlay.c.
References close(), OV_NAME_MAX, and ov_walk_parent().
Referenced by rw_readlink(), and test_mut_rename_symlink().
brix_overlay_rename_upper()
int brix_overlay_rename_upper (const brix_overlay * ov, const char * from, const char * to)
Definition at line 386 of file overlay.c.
References close(), OV_NAME_MAX, and ov_walk_parent().
Referenced by rw_rename_commit(), and test_mut_rename_symlink().
brix_overlay_rmdir_upper()
int brix_overlay_rmdir_upper (const brix_overlay * ov, const char * rel)
Definition at line 371 of file overlay.c.
References close(), ov_clear_markers(), OV_NAME_MAX, ov_open_dir(), and ov_walk_parent().
Referenced by rw_rmdir(), and test_mut_rmdir().
brix_overlay_set_opaque()
int brix_overlay_set_opaque (const brix_overlay * ov, const char * rel_dir)
Definition at line 334 of file overlay.c.
References BRIX_OV_OPQ_NAME, close(), openat(), and ov_open_dir().
Referenced by rw_mkdir(), and test_mut_mkdirs_create().
brix_overlay_symlink()
int brix_overlay_symlink (const brix_overlay * ov, const char * target, const char * rel)
Definition at line 399 of file overlay.c.
References close(), OV_NAME_MAX, and ov_walk_parent().
Referenced by rw_symlink(), and test_mut_rename_symlink().
brix_overlay_truncate()
int brix_overlay_truncate (const brix_overlay * ov, const char * rel, off_t len)
Definition at line 446 of file overlay.c.
References brix_overlay_open(), and close().
Referenced by rw_truncate(), test_mut_attrs(), and test_mut_symlink_escape().
brix_overlay_unlink_upper()
int brix_overlay_unlink_upper (const brix_overlay * ov, const char * rel)
Definition at line 344 of file overlay.c.
References close(), OV_NAME_MAX, and ov_walk_parent().
Referenced by rw_unlink(), and test_mut_mkdirs_create().
brix_overlay_utimens()
int brix_overlay_utimens (const brix_overlay * ov, const char * rel, const struct timespec tv[2])
Definition at line 436 of file overlay.c.
References close(), OV_NAME_MAX, and ov_walk_parent().
Referenced by rw_apply_utimens(), and test_mut_attrs().
brix_overlay_whiteout()
int brix_overlay_whiteout (const brix_overlay * ov, const char * rel)
Definition at line 256 of file overlay.c.
References BRIX_OV_WH_PREFIX, close(), ov_marker_at(), OV_NAME_MAX, ov_walk_parent(), and ov_wh_name().
Referenced by test_classify(), and test_copyup().
brix_overlay_whiteout_clear()
int brix_overlay_whiteout_clear (const brix_overlay * ov, const char * rel)
Definition at line 454 of file overlay.c.
References BRIX_OV_WH_PREFIX, close(), OV_NAME_MAX, ov_walk_parent(), and ov_wh_name().
Referenced by brix_overlay_copyup(), rw_mkdir(), rw_open_create(), rw_rename_commit(), rw_symlink(), and test_classify().
brix_overlay_whiteout_set()
int brix_overlay_whiteout_set (const brix_overlay * ov, const char * rel)
Definition at line 267 of file overlay.c.
References BRIX_OV_WH_PREFIX, close(), openat(), OV_NAME_MAX, ov_walk_parent_mk(), and ov_wh_name().
Referenced by rw_rename_commit(), rw_rmdir(), rw_unlink(), test_classify(), test_copyup(), and test_mut_rmdir().
ov_classify_root()
static int ov_classify_root (const brix_overlay * ov, struct stat * st, brix_ov_state * state) static
Definition at line 170 of file overlay.c.
References BRIX_OV_UPPER, fstat(), and brix_overlay::upper_fd.
Referenced by brix_overlay_classify().
ov_clear_markers()
static int ov_clear_markers (int dirfd) static
Definition at line 354 of file overlay.c.
References brix_ov_name_reserved(), close(), and openat().
Referenced by brix_overlay_rmdir_upper().
ov_cli_guard()
static int ov_cli_guard (const char * mountdir, char ** upper_out) static
Definition at line 604 of file overlay.c.
References BRIX_OV_DIRNAME, BRIX_OV_UPPER_DIRNAME, lstat(), and stat().
Referenced by brix_overlay_cli_list(), and brix_overlay_cli_reset().
ov_cli_kind()
static void ov_cli_kind (const char * mountdir, const char * rel, char * kind, size_t cap) static
Definition at line 619 of file overlay.c.
Referenced by ov_cli_list_entry().
ov_cli_list_dir()
static int ov_cli_list_dir (const char * mountdir, const char * upper_root, const char * rel, FILE * out) static
Definition at line 637 of file overlay.c.
References ov_cli_list_entry().
Referenced by brix_overlay_cli_list(), and ov_cli_list_entry().
ov_cli_list_entry()
static int ov_cli_list_entry (const char * mountdir, const char * upper_root, const char * rel, const char * dirp, const char * name, FILE * out) static
Definition at line 671 of file overlay.c.
References BRIX_OV_OPQ_NAME, BRIX_OV_TMP_PREFIX, BRIX_OV_WH_PREFIX, lstat(), name, ov_cli_kind(), ov_cli_list_dir(), and stat().
Referenced by ov_cli_list_dir().
ov_cli_reset_contents()
static int ov_cli_reset_contents (int dirfd) static
Definition at line 716 of file overlay.c.
References close(), fstatat(), openat(), ov_cli_reset_contents(), and stat().
Referenced by brix_overlay_cli_reset(), and ov_cli_reset_contents().
ov_copyup_stream()
static int ov_copyup_stream (int fd, const char * rel, uint64_t size, brix_ov_read_fn read_lower, void * ud) static
Definition at line 471 of file overlay.c.
References OV_COPYUP_CHUNK.
Referenced by brix_overlay_copyup().
ov_descend_child()
static int ov_descend_child (int cur, const char * name, int * opaque) static
Definition at line 191 of file overlay.c.
References BRIX_OV_OPQ_NAME, close(), name, openat(), and ov_marker_at().
Referenced by brix_overlay_classify().
ov_descend_dir()
static int ov_descend_dir (int dirfd, const char * name, int mk, mode_t(*)(void *ud, const char *rel_dir) mode_fn, void * ud, const char * prefix) static
Definition at line 84 of file overlay.c.
References mk(), name, and openat().
Referenced by ov_walk_parent_mk().
ov_marker_at()
static int ov_marker_at (int dirfd, const char * marker) static
Definition at line 60 of file overlay.c.
References fstatat(), and stat().
Referenced by brix_overlay_classify(), brix_overlay_whiteout(), and ov_descend_child().
ov_nameset_add()
static int ov_nameset_add (brix_ov_nameset * s, char flag, const char * name) static
Definition at line 526 of file overlay.c.
References name, and s.
Referenced by brix_overlay_read_upper().
ov_open_dir()
static int ov_open_dir (const brix_overlay * ov, const char * rel_dir) static
Definition at line 281 of file overlay.c.
References close(), openat(), OV_NAME_MAX, ov_walk_parent(), and brix_overlay::upper_fd.
Referenced by brix_overlay_read_upper(), brix_overlay_rmdir_upper(), and brix_overlay_set_opaque().
ov_split()
static int ov_split (const char ** relp, char * name, size_t cap) static
Definition at line 34 of file overlay.c.
References name.
Referenced by brix_overlay_classify(), and ov_walk_parent_mk().
ov_walk_parent()
static int ov_walk_parent (const brix_overlay * ov, const char * rel, char * leaf, size_t leafcap) static
Definition at line 134 of file overlay.c.
References ov_walk_parent_mk().
Referenced by brix_overlay_chmod(), brix_overlay_mkdir(), brix_overlay_open(), brix_overlay_readlink(), brix_overlay_rename_upper(), brix_overlay_rmdir_upper(), brix_overlay_symlink(), brix_overlay_unlink_upper(), brix_overlay_utimens(), brix_overlay_whiteout(), brix_overlay_whiteout_clear(), and ov_open_dir().
ov_walk_parent_mk()
static int ov_walk_parent_mk (const brix_overlay * ov, const char * rel, char * leaf, size_t leafcap, int mk, mode_t(*)(void *ud, const char *rel_dir) mode_fn, void * ud) static
Definition at line 101 of file overlay.c.
References close(), mk(), openat(), ov_descend_dir(), ov_split(), and brix_overlay::upper_fd.
Referenced by brix_overlay_copyup(), brix_overlay_mkdirs(), brix_overlay_whiteout_set(), and ov_walk_parent().
ov_wh_name()
static void ov_wh_name (const char * name, char * buf, size_t cap) static
Definition at line 55 of file overlay.c.
References BRIX_OV_WH_PREFIX, and name.
Referenced by brix_overlay_classify(), brix_overlay_whiteout(), brix_overlay_whiteout_clear(), and brix_overlay_whiteout_set().