nginx-xrootd: client/lib/fs/overlay_unittest.c File Reference
overlay_unittest.c File Reference
#include "fs/overlay.h"
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/stat.h>
Data Structures
struct fix_t
struct cu_src_t
Macros
#define _GNU_SOURCE
#define CHECK(c, n)
#define CU_SIZE (3u * 1024u * 1024u) /* 3 MiB → exercises the chunk loop */
Functions
static int fix_up (fix_t *f)
static void fix_down (fix_t *f)
static void raw_put (const fix_t *f, const char *rel, const char *content)
static void raw_mkdir (const fix_t *f, const char *rel)
static brix_ov_state cls (const fix_t *f, const char *rel, struct stat *st)
static void test_reserved_names (void)
static void test_classify (void)
static mode_t mode_0700 (void *ud, const char *rel_dir)
static void test_mutations (void)
static int cu_read (void *ud, const char *rel, uint64_t off, size_t len, unsigned char *buf, size_t *outlen)
static int cu_tmp_residue (const fix_t *f)
static void test_copyup (void)
static void test_nameset (void)
static void test_cli (void)
int main (void)
Variables
static int g_checks
static int g_failed
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 16 of file overlay_unittest.c.
CHECK
#define CHECK (c, n)
Value:
    do { g_checks++; if (c) { printf("  ok   %s\n", n); } \
    else { printf("  FAIL %s (line %d)\n", n, __LINE__); g_failed++; } } while (0)
Definition at line 29 of file overlay_unittest.c.
CU_SIZE
#define CU_SIZE (3u * 1024u * 1024u) /* 3 MiB → exercises the chunk loop */
Definition at line 234 of file overlay_unittest.c.
Function Documentation
cls()
static brix_ov_state cls (const fix_t * f, const char * rel, struct stat * st) static
Definition at line 71 of file overlay_unittest.c.
References brix_overlay_classify(), fix_t::ov, s, and stat().
Referenced by brix_export_cvmfs_metrics(), brix_roundtrip_resilient(), brix_scan_record_drift(), brix_with_resilience(), cvmfs_json_requests(), fs_simple(), scan_render(), test_classify(), test_copyup(), and test_mutations().
cu_read()
static int cu_read (void * ud, const char * rel, uint64_t off, size_t len, unsigned char * buf, size_t * outlen) static
Definition at line 239 of file overlay_unittest.c.
References CU_SIZE, and s.
Referenced by test_copyup().
cu_tmp_residue()
static int cu_tmp_residue (const fix_t * f) static
Definition at line 254 of file overlay_unittest.c.
References fix_t::root.
Referenced by test_copyup().
fix_down()
static void fix_down (fix_t * f) static
Definition at line 48 of file overlay_unittest.c.
References brix_overlay_close(), close(), fix_t::ov, fix_t::root, and fix_t::writes_fd.
Referenced by test_classify(), test_copyup(), test_mutations(), and test_nameset().
fix_up()
static int fix_up (fix_t * f) static
Definition at line 40 of file overlay_unittest.c.
References brix_overlay_init(), open(), fix_t::ov, fix_t::root, and fix_t::writes_fd.
Referenced by test_classify(), test_copyup(), test_mutations(), and test_nameset().
main()
int main (void)
Definition at line 402 of file overlay_unittest.c.
References g_checks, g_failed, test_classify(), test_cli(), test_copyup(), test_mutations(), test_nameset(), and test_reserved_names().
mode_0700()
static mode_t mode_0700 (void * ud, const char * rel_dir) static
Definition at line 145 of file overlay_unittest.c.
Referenced by test_mutations().
raw_mkdir()
static void raw_mkdir (const fix_t * f, const char * rel) static
Definition at line 64 of file overlay_unittest.c.
References fix_t::root.
Referenced by test_classify(), test_mutations(), and test_nameset().
raw_put()
static void raw_put (const fix_t * f, const char * rel, const char * content) static
Definition at line 57 of file overlay_unittest.c.
References fix_t::root.
Referenced by test_classify(), test_mutations(), and test_nameset().
test_classify()
static void test_classify (void) static
Definition at line 89 of file overlay_unittest.c.
References BRIX_OV_MASKED, BRIX_OV_NONE, BRIX_OV_UPPER, BRIX_OV_UPPER_DIRNAME, brix_overlay_whiteout(), brix_overlay_whiteout_clear(), brix_overlay_whiteout_set(), CHECK, cls(), fix_down(), fix_up(), fstatat(), fix_t::ov, raw_mkdir(), raw_put(), fix_t::root, stat(), and fix_t::writes_fd.
Referenced by main().
test_cli()
static void test_cli (void) static
Definition at line 352 of file overlay_unittest.c.
References BRIX_OV_DIRNAME, BRIX_OV_UPPER_DIRNAME, brix_overlay_cli_list(), brix_overlay_cli_reset(), CHECK, lstat(), and stat().
Referenced by main().
test_copyup()
static void test_copyup (void) static
Definition at line 261 of file overlay_unittest.c.
References BRIX_OV_NONE, BRIX_OV_UPPER, brix_overlay_copyup(), brix_overlay_open(), brix_overlay_whiteout(), brix_overlay_whiteout_set(), CHECK, close(), cls(), cu_read(), CU_SIZE, cu_tmp_residue(), cu_src_t::fail_at_mib, fix_down(), fix_up(), fix_t::ov, pread(), and stat().
Referenced by main().
test_mutations()
static void test_mutations (void) static
Definition at line 150 of file overlay_unittest.c.
References BRIX_OV_MASKED, BRIX_OV_NONE, BRIX_OV_UPPER, brix_overlay_chmod(), brix_overlay_mkdir(), brix_overlay_mkdirs(), brix_overlay_open(), brix_overlay_readlink(), brix_overlay_rename_upper(), brix_overlay_rmdir_upper(), brix_overlay_set_opaque(), brix_overlay_symlink(), brix_overlay_truncate(), brix_overlay_unlink_upper(), brix_overlay_utimens(), brix_overlay_whiteout_set(), CHECK, close(), cls(), fix_down(), fix_up(), mode_0700(), fix_t::ov, raw_mkdir(), raw_put(), fix_t::root, and stat().
Referenced by main().
test_nameset()
static void test_nameset (void) static
Definition at line 306 of file overlay_unittest.c.
References brix_ov_nameset_at(), brix_ov_nameset_flag(), brix_ov_nameset_free(), brix_overlay_read_upper(), CHECK, brix_ov_nameset::count, fix_down(), fix_up(), fix_t::ov, raw_mkdir(), and raw_put().
Referenced by main().
test_reserved_names()
static void test_reserved_names (void) static
Definition at line 80 of file overlay_unittest.c.
References brix_ov_name_reserved(), and CHECK.
Referenced by main().
Variable Documentation
g_checks
int g_checks static
Definition at line 28 of file overlay_unittest.c.
Referenced by main().
g_failed
int g_failed static
Definition at line 28 of file overlay_unittest.c.
Referenced by main().