nginx-xrootd: src/observability/dashboard/page.c File Reference
page.c File Reference
#include "dashboard_http.h"
#include "core/compat/alloc_guard.h"
#include "core/ident.h"
Functions
ngx_int_t ngx_http_brix_dashboard_page_handler (ngx_http_request_t *r)
Variables
static const char ngx_brix_dashboard_html []
Function Documentation
ngx_http_brix_dashboard_page_handler()
ngx_int_t ngx_http_brix_dashboard_page_handler (ngx_http_request_t * r)
Definition at line 164 of file page.c.
References ngx_http_brix_dashboard_loc_conf_t::anonymous, BRIX_PCALLOC_OR_RETURN, ngx_http_brix_dashboard_loc_conf_t::cookie_path, ngx_brix_dashboard_html, ngx_http_brix_dashboard_check_auth(), ngx_http_brix_dashboard_module, ngx_memcpy, and ngx_pnalloc().
Referenced by ngx_http_brix_dashboard_main_handler().
Variable Documentation
ngx_brix_dashboard_html
const char ngx_brix_dashboard_html[] static
Definition at line 25 of file page.c.
Referenced by ngx_http_brix_dashboard_page_handler().