nginx-xrootd: src/auth/gsi/parse_x509.c File Reference
parse_x509.c File Reference
#include "gsi_internal.h"
#include "gsi_core.h"
#include <string.h>
#include <stdlib.h>
Functions
BIGNUM * brix_gsi_parse_client_dh_public_key (ngx_connection_t *c, ngx_log_t *log, const u_char *public_key_blob, size_t public_key_blob_len)
void brix_gsi_select_cipher_name (const u_char *payload, size_t payload_len, char *cipher_name, size_t cipher_name_size)
EVP_PKEY * brix_gsi_build_peer_dh_key (ngx_log_t *log, EVP_PKEY *server_dh_key, BIGNUM *client_public_bn)
static void gsi_persist_session_cipher (brix_ctx_t *ctx, const char *name, const u_char *key, int keylen, int use_iv)
static void gsi_capture_client_rtag (brix_ctx_t *ctx, const u_char *plain, size_t plain_len)
static STACK_OF (X509)
static EVP_PKEY * gsi_recover_peer_signed (const u_char *payload, size_t plen, ngx_log_t *log)
Function Documentation
brix_gsi_build_peer_dh_key()
EVP_PKEY * brix_gsi_build_peer_dh_key (ngx_log_t * log, EVP_PKEY * server_dh_key, BIGNUM * client_public_bn) extern
Definition at line 71 of file parse_crypto_helpers.c.
References brix_gsi_dh_build_peer(), and log.
brix_gsi_parse_client_dh_public_key()
BIGNUM * brix_gsi_parse_client_dh_public_key (ngx_connection_t * c, ngx_log_t * log, const u_char * public_key_blob, size_t public_key_blob_len) extern
Definition at line 16 of file parse_crypto_helpers.c.
References brix_gsi_dh_pub_decode(), c, and log.
brix_gsi_select_cipher_name()
void brix_gsi_select_cipher_name (const u_char * payload, size_t payload_len, char * cipher_name, size_t cipher_name_size) extern
Definition at line 35 of file parse_crypto_helpers.c.
References gsi_find_bucket(), and kXRS_cipher_alg.
Referenced by STACK_OF().
gsi_capture_client_rtag()
static void gsi_capture_client_rtag (brix_ctx_t * ctx, const u_char * plain, size_t plain_len) static
Definition at line 45 of file parse_x509.c.
References brix_gsi_find_bucket(), brix_ctx_gsi_t::deleg_client_rtag, brix_ctx_gsi_t::deleg_client_rtag_len, brix_ctx_t::gsi, and kXRS_rtag.
Referenced by STACK_OF().
gsi_persist_session_cipher()
static void gsi_persist_session_cipher (brix_ctx_t * ctx, const char * name, const u_char * key, int keylen, int use_iv) static
Definition at line 23 of file parse_x509.c.
References brix_ctx_t::gsi, key, name, brix_ctx_gsi_t::sess_cipher, brix_ctx_gsi_t::sess_key, brix_ctx_gsi_t::sess_keylen, and brix_ctx_gsi_t::sess_use_iv.
Referenced by STACK_OF().
gsi_recover_peer_signed()
static EVP_PKEY * gsi_recover_peer_signed (const u_char * payload, size_t plen, ngx_log_t * log) static
Definition at line 114 of file parse_x509.c.
References brix_gsi_cipher_parse_peer(), brix_gsi_rsa_decrypt_public(), gsi_find_bucket(), kXRS_cipher, kXRS_puk, and log.
Referenced by STACK_OF().
STACK_OF()
static STACK_OF (X509) static
Definition at line 64 of file parse_x509.c.
References gsi_find_bucket(), kXRS_x509, log, and STACK_OF().
Referenced by STACK_OF(), and STACK_OF().