nginx-xrootd: src/tpc/engine/parse.c File Reference
parse.c File Reference
#include "tpc_internal.h"
#include "core/compat/host_split.h"
#include <string.h>
#include <stdlib.h>
#include <stddef.h>
Data Structures
struct tpc_src_spec_out_t
struct tpc_key_desc_t
Macros
#define TPC_KEY_ROW(bare, field)
Functions
static int tpc_copy_src_path (char *path, size_t path_size, const char *path_start)
static int tpc_parse_src_spec (const char *src, tpc_src_spec_out_t *dst)
static int tpc_copy_value (char *dst, size_t dst_size, const char *value_start, size_t value_len)
static void tpc_fill_src_path_from_lfn (brix_tpc_params_t *out)
static void tpc_parse_src_fields (brix_tpc_params_t *out)
static void tpc_apply_key (brix_tpc_params_t *out, const char *key_start, size_t key_len, const char *value_start, size_t value_len)
static const char * tpc_parse_token (const char *token_start, const char *opaque_end, brix_tpc_params_t *out)
int brix_tpc_parse_opaque (const char *opaque, brix_tpc_params_t *out)
Variables
static const tpc_key_desc_t tpc_key_table []
Macro Definition Documentation
TPC_KEY_ROW
#define TPC_KEY_ROW (bare, field)
Value:
    { (bare), sizeof(bare) - 1,                                           \
      offsetof(brix_tpc_params_t, field), sizeof(((brix_tpc_params_t *)0)->field), \
      offsetof(brix_tpc_params_t, has_##field) }
Definition at line 237 of file parse.c.
Function Documentation
brix_tpc_parse_opaque()
int brix_tpc_parse_opaque (const char * opaque, brix_tpc_params_t * out)
Definition at line 336 of file parse.c.
References brix_tpc_params_t::has_dst, brix_tpc_params_t::has_key, brix_tpc_params_t::has_lfn, brix_tpc_params_t::has_org, brix_tpc_params_t::has_src, brix_tpc_params_t::has_stage, brix_tpc_params_t::has_token_mode, tpc_parse_src_fields(), and tpc_parse_token().
tpc_apply_key()
static void tpc_apply_key (brix_tpc_params_t * out, const char * key_start, size_t key_len, const char * value_start, size_t value_len) static
Definition at line 263 of file parse.c.
References tpc_key_desc_t::flag_off, tpc_key_desc_t::name, tpc_key_desc_t::name_len, tpc_copy_value(), tpc_key_table, tpc_key_desc_t::value_off, and tpc_key_desc_t::value_size.
Referenced by tpc_parse_token().
tpc_copy_src_path()
static int tpc_copy_src_path (char * path, size_t path_size, const char * path_start) static
Definition at line 24 of file parse.c.
Referenced by tpc_parse_src_spec().
tpc_copy_value()
static int tpc_copy_value (char * dst, size_t dst_size, const char * value_start, size_t value_len) static
Definition at line 147 of file parse.c.
Referenced by tpc_apply_key().
tpc_fill_src_path_from_lfn()
static void tpc_fill_src_path_from_lfn (brix_tpc_params_t * out) static
Definition at line 165 of file parse.c.
References brix_tpc_params_t::has_lfn, brix_tpc_params_t::lfn, and brix_tpc_params_t::src_path.
Referenced by tpc_parse_src_fields().
tpc_parse_src_fields()
static void tpc_parse_src_fields (brix_tpc_params_t * out) static
Definition at line 189 of file parse.c.
References brix_tpc_params_t::has_src, tpc_src_spec_out_t::host, port, brix_tpc_params_t::src, brix_tpc_params_t::src_host, brix_tpc_params_t::src_path, brix_tpc_params_t::src_port, tpc_fill_src_path_from_lfn(), and tpc_parse_src_spec().
Referenced by brix_tpc_parse_opaque().
tpc_parse_src_spec()
static int tpc_parse_src_spec (const char * src, tpc_src_spec_out_t * dst) static
Definition at line 77 of file parse.c.
References brix_split_host_port(), tpc_src_spec_out_t::host, tpc_src_spec_out_t::host_size, tpc_src_spec_out_t::path, tpc_src_spec_out_t::path_size, tpc_src_spec_out_t::port, and tpc_copy_src_path().
Referenced by tpc_parse_src_fields().
tpc_parse_token()
static const char * tpc_parse_token (const char * token_start, const char * opaque_end, brix_tpc_params_t * out) static
Definition at line 289 of file parse.c.
References tpc_apply_key().
Referenced by brix_tpc_parse_opaque().
Variable Documentation
tpc_key_table
const tpc_key_desc_t tpc_key_table[] static
Initial value:
= {
    { ( "src" ), sizeof( "src" ) - 1,   offsetof(brix_tpc_params_t,  src ), sizeof(((brix_tpc_params_t *)0)-> src ),   offsetof(brix_tpc_params_t, has_src ) },
    { ( "dst" ), sizeof( "dst" ) - 1,   offsetof(brix_tpc_params_t,  dst ), sizeof(((brix_tpc_params_t *)0)-> dst ),   offsetof(brix_tpc_params_t, has_dst ) },
    { ( "key" ), sizeof( "key" ) - 1,   offsetof(brix_tpc_params_t,  key ), sizeof(((brix_tpc_params_t *)0)-> key ),   offsetof(brix_tpc_params_t, has_key ) },
    { ( "lfn" ), sizeof( "lfn" ) - 1,   offsetof(brix_tpc_params_t,  lfn ), sizeof(((brix_tpc_params_t *)0)-> lfn ),   offsetof(brix_tpc_params_t, has_lfn ) },
    { ( "org" ), sizeof( "org" ) - 1,   offsetof(brix_tpc_params_t,  org ), sizeof(((brix_tpc_params_t *)0)-> org ),   offsetof(brix_tpc_params_t, has_org ) },
    { ( "stage" ), sizeof( "stage" ) - 1,   offsetof(brix_tpc_params_t,  stage ), sizeof(((brix_tpc_params_t *)0)-> stage ),   offsetof(brix_tpc_params_t, has_stage ) },
    { ( "token_mode" ), sizeof( "token_mode" ) - 1,   offsetof(brix_tpc_params_t,  token_mode ), sizeof(((brix_tpc_params_t *)0)-> token_mode ),   offsetof(brix_tpc_params_t, has_token_mode ) },
}
Definition at line 242 of file parse.c.
Referenced by tpc_apply_key().