nginx-xrootd: src/auth/gsi/parse_x509_unsigned.c File Reference
parse_x509_unsigned.c File Reference
#include "gsi_internal.h"
#include "gsi_core.h"
#include <string.h>
#include <stdlib.h>
#include "parse_x509_internal.h"
Functions
BIGNUM * brix_gsi_parse_client_dh_public_key (ngx_connection_t *c, ngx_log_t *log, const u_char *public_key_blob, size_t public_key_blob_len)
void brix_gsi_select_cipher_name (const u_char *payload, size_t payload_len, char *cipher_name, size_t cipher_name_size)
EVP_PKEY * brix_gsi_build_peer_dh_key (ngx_log_t *log, EVP_PKEY *server_dh_key, BIGNUM *client_public_bn)
static unsigned char * gsi_unsigned_derive_secret (ngx_connection_t *c, EVP_PKEY *dh_key, EVP_PKEY *peer, size_t *secret_len)
static size_t gsi_unsigned_key_length (const EVP_CIPHER *evp_cipher, size_t secret_len)
static EVP_CIPHER_CTX * gsi_unsigned_decrypt_init (brix_ctx_t *ctx, const EVP_CIPHER *evp_cipher, unsigned char *secret, size_t secret_len, const char *cipher_name)
static unsigned char * gsi_unsigned_decrypt_main (ngx_connection_t *c, EVP_CIPHER_CTX *dctx, const u_char *main_data, size_t main_len, size_t *plain_len)
static EVP_PKEY * gsi_unsigned_build_peer (brix_ctx_t *ctx, ngx_connection_t *c, const u_char **main_data, size_t *main_len)
STACK_OF (X509)
Function Documentation
brix_gsi_build_peer_dh_key()
EVP_PKEY * brix_gsi_build_peer_dh_key (ngx_log_t * log, EVP_PKEY * server_dh_key, BIGNUM * client_public_bn) extern
Definition at line 71 of file parse_crypto_helpers.c.
References brix_gsi_dh_build_peer(), and log.
Referenced by gsi_unsigned_build_peer().
brix_gsi_parse_client_dh_public_key()
BIGNUM * brix_gsi_parse_client_dh_public_key (ngx_connection_t * c, ngx_log_t * log, const u_char * public_key_blob, size_t public_key_blob_len) extern
Definition at line 16 of file parse_crypto_helpers.c.
References brix_gsi_dh_pub_decode(), c, and log.
Referenced by gsi_unsigned_build_peer().
brix_gsi_select_cipher_name()
void brix_gsi_select_cipher_name (const u_char * payload, size_t payload_len, char * cipher_name, size_t cipher_name_size) extern
Definition at line 35 of file parse_crypto_helpers.c.
References gsi_find_bucket(), and kXRS_cipher_alg.
Referenced by STACK_OF().
gsi_unsigned_build_peer()
static EVP_PKEY * gsi_unsigned_build_peer (brix_ctx_t * ctx, ngx_connection_t * c, const u_char ** main_data, size_t * main_len) static
Definition at line 226 of file parse_x509_unsigned.c.
References brix_gsi_build_peer_dh_key(), brix_gsi_parse_client_dh_public_key(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_gsi_t::dh_key, brix_ctx_t::gsi, gsi_find_bucket(), kXRS_main, kXRS_puk, log, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by STACK_OF().
gsi_unsigned_decrypt_init()
static EVP_CIPHER_CTX * gsi_unsigned_decrypt_init (brix_ctx_t * ctx, const EVP_CIPHER * evp_cipher, unsigned char * secret, size_t secret_len, const char * cipher_name) static
Definition at line 125 of file parse_x509_unsigned.c.
References gsi_persist_session_cipher(), and gsi_unsigned_key_length().
Referenced by STACK_OF().
gsi_unsigned_decrypt_main()
static unsigned char * gsi_unsigned_decrypt_main (ngx_connection_t * c, EVP_CIPHER_CTX * dctx, const u_char * main_data, size_t main_len, size_t * plain_len) static
Definition at line 171 of file parse_x509_unsigned.c.
References c, and plain_len.
Referenced by STACK_OF().
gsi_unsigned_derive_secret()
static unsigned char * gsi_unsigned_derive_secret (ngx_connection_t * c, EVP_PKEY * dh_key, EVP_PKEY * peer, size_t * secret_len) static
Definition at line 26 of file parse_x509_unsigned.c.
References c.
Referenced by STACK_OF().
gsi_unsigned_key_length()
static size_t gsi_unsigned_key_length (const EVP_CIPHER * evp_cipher, size_t secret_len) static
Definition at line 81 of file parse_x509_unsigned.c.
Referenced by gsi_unsigned_decrypt_init().
STACK_OF()
STACK_OF (X509)
Definition at line 277 of file parse_x509_unsigned.c.
References brix_gsi_select_cipher_name(), brix_sanitize_log_string(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_gsi_t::dh_key, brix_ctx_t::gsi, gsi_capture_client_rtag(), gsi_capture_fullproxy(), gsi_store_signing_key(), gsi_unsigned_build_peer(), gsi_unsigned_decrypt_init(), gsi_unsigned_decrypt_main(), gsi_unsigned_derive_secret(), log, brix_ctx_recv_t::payload, plain_len, brix_ctx_t::recv, and brix_ctx_gsi_t::signed_dh.