nginx-xrootd: src/fs/path/path_internal.h File Reference
path_internal.h File Reference
#include "core/ngx_brix_module.h"
Functions
int brix_path_component_forbidden (const char *comp, size_t comp_len)
int brix_path_has_dotdot (const char *path)
void brix_log_path_warning (ngx_log_t *log, const char *prefix, const char *path)
int brix_path_within_root (const char *root_canon, const char *path_canon)
int brix_resolved_relative_to_root (ngx_log_t *log, const char *root_canon, const char *resolved, char *rel, size_t relsz)
int brix_get_canonical_root (ngx_log_t *log, const ngx_str_t *root, char *root_canon, size_t root_canon_sz)
ngx_int_t brix_finalize_path_rules (ngx_log_t *log, const ngx_str_t *root, ngx_array_t *rules, size_t element_size, size_t path_offset, size_t resolved_offset, size_t resolved_size)
Function Documentation
brix_finalize_path_rules()
ngx_int_t brix_finalize_path_rules (ngx_log_t * log, const ngx_str_t * root, ngx_array_t * rules, size_t element_size, size_t path_offset, size_t resolved_offset, size_t resolved_size)
Definition at line 118 of file helpers.c.
References brix_get_canonical_root(), brix_resolve_path_noexist(), log, and PATH_MAX.
Referenced by brix_finalize_authdb_rules(), brix_finalize_group_rules(), and brix_finalize_vo_rules().
brix_get_canonical_root()
int brix_get_canonical_root (ngx_log_t * log, const ngx_str_t * root, char * root_canon, size_t root_canon_sz)
Definition at line 10 of file canonical.c.
References log, and PATH_MAX.
Referenced by brix_finalize_path_rules(), brix_open_confined(), and brix_resolve_with_opts().
brix_log_path_warning()
void brix_log_path_warning (ngx_log_t * log, const char * prefix, const char * path)
Definition at line 69 of file resolve_confined_helpers.c.
References brix_sanitize_log_string(), and log.
Referenced by brix_path_warn(), brix_reject_dotdot_path(), brix_resolve_op_path(), and brix_resolved_relative_to_root().
brix_path_component_forbidden()
int brix_path_component_forbidden (const char * comp, size_t comp_len)
Definition at line 10 of file helpers.c.
Referenced by brix_normalize_policy_path(), brix_op_path_forbidden_component(), brix_open_confined_parent_fallback(), and brix_validate_components_cstr().
brix_path_has_dotdot()
int brix_path_has_dotdot (const char * path)
Definition at line 17 of file helpers.c.
Referenced by brix_reject_dotdot_path().
brix_path_within_root()
int brix_path_within_root (const char * root_canon, const char * path_canon)
Definition at line 84 of file resolve_confined_helpers.c.
Referenced by brix_finish_resolved(), brix_resolve_missing_parents(), brix_resolve_missing_tail(), and brix_resolved_relative_to_root().
brix_resolved_relative_to_root()
int brix_resolved_relative_to_root (ngx_log_t * log, const char * root_canon, const char * resolved, char * rel, size_t relsz)
Definition at line 107 of file resolve_confined_helpers.c.
References brix_log_path_warning(), brix_path_within_root(), and log.
Referenced by brix_chmod_confined_canon(), brix_dirlist_access_ok(), brix_getxattr_confined_canon(), brix_link_confined_canon(), brix_listxattr_confined_canon(), brix_lstat_confined_canon(), brix_mkdir_confined_canon(), brix_open_confined_canon(), brix_open_confined_parent_canon(), brix_opendir_confined_canon(), brix_readlink_confined_canon(), brix_removexattr_confined_canon(), brix_setattr_confined_canon(), brix_setxattr_confined_canon(), brix_symlink_confined_canon(), brix_unlink_confined_canon(), and rename_confined_canon_impl().