nginx-xrootd: src/fs/cache/paths.c File Reference
paths.c File Reference
#include "cache_internal.h"
#include "meta.h"
#include "open.h"
#include "cstore.h"
#include "cache_storage.h"
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
Functions
int brix_cache_append_suffix (char *dst, size_t dstsz, const char *path, const char *suffix)
int brix_cache_meta_path (char *dst, size_t dstsz, const char *cache_path)
int brix_cache_ensure_parent (const char *path)
int brix_cache_file_ready (const char *path)
const char * brix_cache_state_root (const ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_cache_state_path (const ngx_stream_brix_srv_conf_t *conf, const char *resolved, char *dst, size_t dstsz)
Function Documentation
brix_cache_append_suffix()
int brix_cache_append_suffix (char * dst, size_t dstsz, const char * path, const char * suffix)
Definition at line 24 of file paths.c.
Referenced by brix_cache_meta_path(), and brix_cache_open_or_fill().
brix_cache_ensure_parent()
int brix_cache_ensure_parent (const char * path)
Definition at line 44 of file paths.c.
References brix_mkdir_recursive(), and PATH_MAX.
Referenced by brix_cache_fill_thread().
brix_cache_file_ready()
int brix_cache_file_ready (const char * path)
Definition at line 73 of file paths.c.
References stat().
Referenced by brix_cache_ready(), and brix_cache_wait_or_lock().
brix_cache_meta_path()
int brix_cache_meta_path (char * dst, size_t dstsz, const char * cache_path)
Definition at line 34 of file paths.c.
References brix_cache_append_suffix().
Referenced by brix_cache_evict_remove_sidecars(), and cache_meta_read_legacy().
brix_cache_state_path()
ngx_int_t brix_cache_state_path (const ngx_stream_brix_srv_conf_t * conf, const char * resolved, char * dst, size_t dstsz)
Definition at line 124 of file paths.c.
References brix_cache_path_for_resolved(), and brix_cache_state_root().
brix_cache_state_root()
const char * brix_cache_state_root (const ngx_stream_brix_srv_conf_t * conf)
Definition at line 93 of file paths.c.
References brix_cache_storage_cstore(), and brix_cstore_local_root().
Referenced by brix_cache_purge_setup(), brix_cache_reap_dirty(), brix_cache_state_path(), brix_cache_try_evict_lock(), brix_cache_watermark_purge(), brix_init_server_cache_reap_timer(), brix_init_server_watermark_timer(), and brix_server_setup_export().