nginx-xrootd: src/protocols/ssi/svc_cta/pb_wire_unittest.c File Reference
pb_wire_unittest.c File Reference
#include "pb_wire.h"
#include <stdio.h>
#include <string.h>
Macros
#define CHECK(cond)
Functions
static int bytes_eq (const pb_writer *w, const char *hex)
static void test_varint_roundtrip (void)
static void test_varint_encoding_golden (void)
static void test_varint_truncated_rejected (void)
static void test_tag_roundtrip (void)
static void test_len_delim_roundtrip (void)
static void test_len_delim_overrun_rejected (void)
static void test_skip_field (void)
static void test_writer_overflow_rejected (void)
int main (void)
Variables
static int g_fail
Macro Definition Documentation
CHECK
#define CHECK (cond)
Value:
    do { \
    if (!(cond)) { printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
                   g_fail++; } \
} while (0)
Definition at line 13 of file pb_wire_unittest.c.
Function Documentation
bytes_eq()
static int bytes_eq (const pb_writer * w, const char * hex) static
Definition at line 18 of file pb_wire_unittest.c.
References hex(), pb_writer::len, and pb_writer::p.
Referenced by test_varint_encoding_golden().
main()
int main (void)
Definition at line 137 of file pb_wire_unittest.c.
References g_fail, test_len_delim_overrun_rejected(), test_len_delim_roundtrip(), test_skip_field(), test_tag_roundtrip(), test_varint_encoding_golden(), test_varint_roundtrip(), test_varint_truncated_rejected(), and test_writer_overflow_rejected().
test_len_delim_overrun_rejected()
static void test_len_delim_overrun_rejected (void) static
Definition at line 99 of file pb_wire_unittest.c.
References CHECK, pb_read_len_delim(), and pb_read_tag().
Referenced by main().
test_len_delim_roundtrip()
static void test_len_delim_roundtrip (void) static
Definition at line 84 of file pb_wire_unittest.c.
References CHECK, pb_reader::end, pb_writer::len, pb_reader::p, pb_read_len_delim(), pb_read_tag(), pb_write_string(), and PB_WT_LEN.
Referenced by main().
test_skip_field()
static void test_skip_field (void) static
Definition at line 110 of file pb_wire_unittest.c.
References CHECK, pb_reader::end, pb_writer::len, pb_reader::p, pb_read_len_delim(), pb_read_tag(), pb_skip_field(), pb_write_string(), and pb_write_varint_field().
Referenced by main().
test_tag_roundtrip()
static void test_tag_roundtrip (void) static
Definition at line 70 of file pb_wire_unittest.c.
References CHECK, pb_reader::end, pb_writer::len, pb_reader::p, pb_writer::p, pb_read_tag(), pb_write_tag(), and PB_WT_LEN.
Referenced by main().
test_varint_encoding_golden()
static void test_varint_encoding_golden (void) static
Definition at line 53 of file pb_wire_unittest.c.
References bytes_eq(), CHECK, and pb_write_varint().
Referenced by main().
test_varint_roundtrip()
static void test_varint_roundtrip (void) static
Definition at line 34 of file pb_wire_unittest.c.
References CHECK, pb_reader::end, pb_writer::len, pb_reader::p, pb_read_varint(), and pb_write_varint().
Referenced by main().
test_varint_truncated_rejected()
static void test_varint_truncated_rejected (void) static
Definition at line 61 of file pb_wire_unittest.c.
References CHECK, and pb_read_varint().
Referenced by main().
test_writer_overflow_rejected()
static void test_writer_overflow_rejected (void) static
Definition at line 130 of file pb_wire_unittest.c.
References CHECK, and pb_write_varint().
Referenced by main().
Variable Documentation
g_fail
int g_fail static
Definition at line 12 of file pb_wire_unittest.c.
Referenced by main().