nginx-xrootd: src/protocols/ssi/svc_cta/pb_wire.c File Reference
pb_wire.c File Reference
#include "pb_wire.h"
#include <string.h>
Functions
int pb_read_varint (pb_reader *r, uint64_t *out)
int pb_read_tag (pb_reader *r, uint32_t *field, int *wiretype)
int pb_read_len_delim (pb_reader *r, const unsigned char **data, size_t *len)
int pb_skip_field (pb_reader *r, int wiretype)
int pb_write_varint (pb_writer *w, uint64_t v)
int pb_write_tag (pb_writer *w, uint32_t field, int wiretype)
int pb_write_len_delim (pb_writer *w, uint32_t field, const unsigned char *data, size_t len)
int pb_write_string (pb_writer *w, uint32_t field, const char *s)
int pb_write_varint_field (pb_writer *w, uint32_t field, uint64_t v)
Function Documentation
pb_read_len_delim()
int pb_read_len_delim (pb_reader * r, const unsigned char ** data, size_t * len)
Definition at line 53 of file pb_wire.c.
References pb_reader::end, pb_reader::p, and pb_read_varint().
Referenced by cta_pb_decode_request(), decode_client(), decode_metadata(), decode_notification(), decode_requester(), decode_service(), decode_workflow(), pb_skip_field(), test_encode_response(), test_encode_stream_header(), test_len_delim_overrun_rejected(), test_len_delim_roundtrip(), and test_skip_field().
pb_read_tag()
int pb_read_tag (pb_reader * r, uint32_t * field, int * wiretype)
Definition at line 37 of file pb_wire.c.
References pb_read_varint().
Referenced by cta_pb_decode_request(), decode_client(), decode_metadata(), decode_notification(), decode_requester(), decode_service(), decode_workflow(), test_encode_error_response(), test_encode_response(), test_encode_stream_header(), test_len_delim_overrun_rejected(), test_len_delim_roundtrip(), test_skip_field(), and test_tag_roundtrip().
pb_read_varint()
int pb_read_varint (pb_reader * r, uint64_t * out)
Definition at line 14 of file pb_wire.c.
References pb_reader::end, and pb_reader::p.
Referenced by decode_metadata(), decode_workflow(), pb_read_len_delim(), pb_read_tag(), pb_skip_field(), test_encode_error_response(), test_encode_response(), test_varint_roundtrip(), and test_varint_truncated_rejected().
pb_skip_field()
int pb_skip_field (pb_reader * r, int wiretype)
Definition at line 70 of file pb_wire.c.
References pb_reader::end, pb_reader::p, pb_read_len_delim(), pb_read_varint(), PB_WT_I32, PB_WT_I64, PB_WT_LEN, and PB_WT_VARINT.
Referenced by cta_pb_decode_request(), decode_client(), decode_metadata(), decode_notification(), decode_requester(), decode_service(), decode_workflow(), test_encode_response(), and test_skip_field().
pb_write_len_delim()
int pb_write_len_delim (pb_writer * w, uint32_t field, const unsigned char * data, size_t len)
Definition at line 122 of file pb_wire.c.
References pb_writer::cap, pb_writer::len, pb_writer::p, pb_write_tag(), pb_write_varint(), and PB_WT_LEN.
Referenced by build_request(), cta_pb_encode_stream_header(), and pb_write_string().
pb_write_string()
int pb_write_string (pb_writer * w, uint32_t field, const char * s)
Definition at line 142 of file pb_wire.c.
References pb_write_len_delim(), and s.
Referenced by build_request(), cta_pb_encode_response(), test_len_delim_roundtrip(), and test_skip_field().
pb_write_tag()
int pb_write_tag (pb_writer * w, uint32_t field, int wiretype)
Definition at line 116 of file pb_wire.c.
References pb_write_varint().
Referenced by pb_write_len_delim(), pb_write_varint_field(), and test_tag_roundtrip().
pb_write_varint()
int pb_write_varint (pb_writer * w, uint64_t v)
Definition at line 99 of file pb_wire.c.
References pb_writer::cap, pb_writer::len, and pb_writer::p.
Referenced by pb_write_len_delim(), pb_write_tag(), pb_write_varint_field(), test_varint_encoding_golden(), test_varint_roundtrip(), and test_writer_overflow_rejected().
pb_write_varint_field()
int pb_write_varint_field (pb_writer * w, uint32_t field, uint64_t v)
Definition at line 148 of file pb_wire.c.
References pb_write_tag(), pb_write_varint(), and PB_WT_VARINT.
Referenced by build_request(), cta_pb_encode_response(), test_skip_field(), and test_unknown_field_skipped().