nginx-xrootd: src/fs/backend/pblock/pblock_store.c File Reference
pblock_store.c File Reference
#include "pblock_store.h"
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <sys/random.h>
#include <sys/stat.h>
#include <sys/uio.h>
Functions
int64_t pblock_now (void)
int64_t pblock_last_block (int64_t size, int64_t bs)
uint64_t pblock_fnv (const char *s)
int pblock_mkdir_p (const char *path)
int pblock_gen_blob_id (char out[(32+1)])
int pblock_obj_dir (const pblock_state_t *st, const char *blob_id, char *out, size_t cap)
int pblock_block_path (const pblock_state_t *st, const char *blob_id, int64_t idx, char *out, size_t cap)
int pblock_ensure_obj_dir (const pblock_state_t *st, const char *blob_id)
void pblock_fill_sd_stat (const pblock_meta *m, const char *path, brix_sd_stat_t *out)
ssize_t pblock_write_blocks (const pblock_state_t *st, const char *blob_id, int64_t bs, int blk0_fd, const void *buf, size_t len, off_t off)
ssize_t pblock_read_blocks (const pblock_state_t *st, const char *blob_id, int64_t bs, int blk0_fd, void *buf, size_t len, off_t off)
void pblock_remove_blocks (const pblock_state_t *st, const char *blob_id, int64_t size, int64_t bs)
ssize_t pblock_copy_one_block (const char *src_path, const char *dst_path)
Function Documentation
pblock_block_path()
int pblock_block_path (const pblock_state_t * st, const char * blob_id, int64_t idx, char * out, size_t cap)
Definition at line 134 of file pblock_store.c.
References pblock_state_t::data_dir.
Referenced by pblock_read_blocks(), pblock_remove_blocks(), and pblock_write_blocks().
pblock_copy_one_block()
ssize_t pblock_copy_one_block (const char * src_path, const char * dst_path)
Definition at line 325 of file pblock_store.c.
References close(), open(), and pread().
pblock_ensure_obj_dir()
int pblock_ensure_obj_dir (const pblock_state_t * st, const char * blob_id)
Definition at line 151 of file pblock_store.c.
References PATH_MAX, pblock_mkdir_p(), and pblock_obj_dir().
pblock_fill_sd_stat()
void pblock_fill_sd_stat (const pblock_meta * m, const char * path, brix_sd_stat_t * out)
Definition at line 164 of file pblock_store.c.
References pblock_meta::ctime, brix_sd_stat_t::ctime, brix_sd_stat_t::ino, pblock_meta::is_dir, brix_sd_stat_t::is_dir, brix_sd_stat_t::is_reg, pblock_meta::mode, brix_sd_stat_t::mode, pblock_meta::mtime, brix_sd_stat_t::mtime, pblock_fnv(), pblock_meta::size, and brix_sd_stat_t::size.
pblock_fnv()
uint64_t pblock_fnv (const char * s)
Definition at line 42 of file pblock_store.c.
References s.
Referenced by pblock_fill_sd_stat().
pblock_gen_blob_id()
int pblock_gen_blob_id (char out[(32+1)])
Definition at line 89 of file pblock_store.c.
References hex(), and PBLOCK_BLOB_ID_HEX.
pblock_last_block()
int64_t pblock_last_block (int64_t size, int64_t bs)
Definition at line 34 of file pblock_store.c.
Referenced by pblock_remove_blocks().
pblock_mkdir_p()
int pblock_mkdir_p (const char * path)
Definition at line 56 of file pblock_store.c.
References PATH_MAX.
Referenced by pblock_ensure_obj_dir().
pblock_now()
int64_t pblock_now (void)
Definition at line 26 of file pblock_store.c.
pblock_obj_dir()
int pblock_obj_dir (const pblock_state_t * st, const char * blob_id, char * out, size_t cap)
Definition at line 118 of file pblock_store.c.
References pblock_state_t::data_dir.
Referenced by pblock_ensure_obj_dir(), and pblock_remove_blocks().
pblock_read_blocks()
ssize_t pblock_read_blocks (const pblock_state_t * st, const char * blob_id, int64_t bs, int blk0_fd, void * buf, size_t len, off_t off)
Definition at line 240 of file pblock_store.c.
References close(), open(), PATH_MAX, pblock_block_path(), and pread().
pblock_remove_blocks()
void pblock_remove_blocks (const pblock_state_t * st, const char * blob_id, int64_t size, int64_t bs)
Definition at line 292 of file pblock_store.c.
References pblock_state_t::data_dir, PATH_MAX, pblock_block_path(), pblock_last_block(), and pblock_obj_dir().
pblock_write_blocks()
ssize_t pblock_write_blocks (const pblock_state_t * st, const char * blob_id, int64_t bs, int blk0_fd, const void * buf, size_t len, off_t off)
Definition at line 184 of file pblock_store.c.
References close(), open(), PATH_MAX, and pblock_block_path().