nginx-xrootd: src/fs/backend/pblock/pblock_xform.h File Reference
pblock_xform.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>
Data Structures
struct pblock_xform_t
Macros
#define PBLOCK_XFORM_HDR 8
Enumerations
enum pblock_xform_kind { PBLOCK_XFORM_NONE = 0 , PBLOCK_XFORM_CRYPT = 1 , PBLOCK_XFORM_ZSTD = 2 }
Functions
int pblock_xform_config (pblock_xform_t *xf, const char *spec, size_t len)
int pblock_xform_active (const pblock_xform_t *xf)
const char * pblock_xform_name (pblock_xform_kind kind)
pblock_xform_kind pblock_xform_kind_from_name (const char *name)
int pblock_xform_block_load (const pblock_xform_t *xf, int64_t idx, const char *path, unsigned char *out, int64_t bs, uint32_t *llen_out)
int pblock_xform_block_store (const pblock_xform_t *xf, int64_t idx, const char *path, const unsigned char *logical, uint32_t llen, int64_t bs)
Macro Definition Documentation
PBLOCK_XFORM_HDR
#define PBLOCK_XFORM_HDR 8
Definition at line 48 of file pblock_xform.h.
Enumeration Type Documentation
pblock_xform_kind
enum pblock_xform_kind
Enumerator
PBLOCK_XFORM_NONE
PBLOCK_XFORM_CRYPT
PBLOCK_XFORM_ZSTD
Definition at line 34 of file pblock_xform.h.
Function Documentation
pblock_xform_active()
int pblock_xform_active (const pblock_xform_t * xf)
Referenced by pblock_read_blocks(), and pblock_write_blocks().
pblock_xform_block_load()
int pblock_xform_block_load (const pblock_xform_t * xf, int64_t idx, const char * path, unsigned char * out, int64_t bs, uint32_t * llen_out)
Referenced by pblock_xform_read(), and pblock_xform_write().
pblock_xform_block_store()
int pblock_xform_block_store (const pblock_xform_t * xf, int64_t idx, const char * path, const unsigned char * logical, uint32_t llen, int64_t bs)
Referenced by pblock_xform_write().
pblock_xform_config()
int pblock_xform_config (pblock_xform_t * xf, const char * spec, size_t len)
pblock_xform_kind_from_name()
pblock_xform_kind pblock_xform_kind_from_name (const char * name)
pblock_xform_name()
const char * pblock_xform_name (pblock_xform_kind kind)