nginx-xrootd: src/fs/cache/origin/pelican_register.c File Reference
pelican_register.c File Reference
#include "pelican_register.h"
#include "auth/token/jwt_sign.h"
#include "core/ident.h"
#include <ngx_thread_pool.h>
#include <curl/curl.h>
#include <jansson.h>
#include <openssl/rand.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
Data Structures
struct brix_pelican_adv_t
struct brix_pelican_mem2_t
Functions
static void brix_pelican_rfc3339 (time_t t, char *out, size_t outsz)
static void brix_pelican_hex_random (char *out, size_t nbytes)
static const char * brix_pelican_cstr (const ngx_str_t *s, const char *dflt)
static json_t * brix_pelican_caps_json (void)
static char * brix_pelican_build_ad (ngx_stream_brix_srv_conf_t *conf, time_t now)
static ngx_int_t brix_pelican_build_jwt (ngx_stream_brix_srv_conf_t *conf, const char *director, time_t now, char *out, size_t outsz)
static size_t brix_pelican_mem2_cb (char *ptr, size_t size, size_t nmemb, void *ud)
static void brix_pelican_set_ca (ngx_stream_brix_srv_conf_t *conf, CURL *curl)
static ngx_int_t brix_pelican_discover_cfg (ngx_stream_brix_srv_conf_t *conf, ngx_log_t *log, char *out, size_t outsz)
static ngx_int_t brix_pelican_post (ngx_stream_brix_srv_conf_t *conf, ngx_log_t *log, const char *director, const char *body, const char *jwt)
ngx_int_t brix_cache_pelican_advertise_once (ngx_stream_brix_srv_conf_t *conf, ngx_log_t *log)
static void brix_pelican_adv_thread (void *data, ngx_log_t *log)
static void brix_pelican_adv_done (ngx_event_t *ev)
static void brix_pelican_adv_timer (ngx_event_t *ev)
void brix_cache_pelican_schedule_advertise (ngx_cycle_t *cycle, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_cache_pelican_advertise_once()
ngx_int_t brix_cache_pelican_advertise_once (ngx_stream_brix_srv_conf_t * conf, ngx_log_t * log)
Definition at line 379 of file pelican_register.c.
References ngx_stream_brix_srv_conf_t::advertise, brix_pelican_build_ad(), brix_pelican_build_jwt(), brix_pelican_discover_cfg(), brix_pelican_post(), brix_cache_advertise_conf_t::data_url, brix_cache_advertise_conf_t::gen, brix_cache_advertise_conf_t::key_pkey, and log.
Referenced by brix_pelican_adv_thread(), and brix_pelican_adv_timer().
brix_cache_pelican_schedule_advertise()
void brix_cache_pelican_schedule_advertise (ngx_cycle_t * cycle, ngx_stream_brix_srv_conf_t * conf)
Definition at line 464 of file pelican_register.c.
References ngx_stream_brix_srv_conf_t::advertise, brix_jwt_load_ec_key(), brix_pelican_adv_done(), brix_pelican_adv_thread(), brix_pelican_adv_timer(), brix_pelican_hex_random(), ngx_stream_brix_srv_conf_t::cache_origin_host, brix_pelican_adv_t::conf, brix_cache_advertise_conf_t::data_url, brix_cache_advertise_conf_t::enable, brix_pelican_adv_t::in_flight, brix_cache_advertise_conf_t::instance, brix_cache_advertise_conf_t::interval, brix_cache_advertise_conf_t::key, brix_cache_advertise_conf_t::key_pkey, brix_pelican_adv_t::log, ngx_pcalloc(), brix_pelican_adv_t::task, and brix_cache_advertise_conf_t::timer.
Referenced by ngx_stream_brix_init_process().
brix_pelican_adv_done()
static void brix_pelican_adv_done (ngx_event_t * ev) static
Definition at line 430 of file pelican_register.c.
References brix_pelican_adv_t::in_flight.
Referenced by brix_cache_pelican_schedule_advertise().
brix_pelican_adv_thread()
static void brix_pelican_adv_thread (void * data, ngx_log_t * log) static
Definition at line 423 of file pelican_register.c.
References brix_cache_pelican_advertise_once(), brix_pelican_adv_t::conf, log, and brix_pelican_adv_t::result.
Referenced by brix_cache_pelican_schedule_advertise().
brix_pelican_adv_timer()
static void brix_pelican_adv_timer (ngx_event_t * ev) static
Definition at line 437 of file pelican_register.c.
References ngx_stream_brix_srv_conf_t::advertise, brix_cache_pelican_advertise_once(), ngx_stream_brix_srv_conf_t::common, brix_pelican_adv_t::conf, brix_pelican_adv_t::in_flight, brix_cache_advertise_conf_t::interval, brix_pelican_adv_t::task, and ngx_http_brix_shared_conf_t::thread_pool.
Referenced by brix_cache_pelican_schedule_advertise().
brix_pelican_build_ad()
static char * brix_pelican_build_ad (ngx_stream_brix_srv_conf_t * conf, time_t now) static
Definition at line 101 of file pelican_register.c.
References ngx_stream_brix_srv_conf_t::advertise, brix_pelican_caps_json(), brix_pelican_cstr(), brix_pelican_rfc3339(), BRIX_SERVER_NAME, BRIX_SERVER_VERSION, brix_cache_advertise_conf_t::data_url, brix_cache_advertise_conf_t::gen, brix_cache_advertise_conf_t::instance, brix_cache_advertise_conf_t::interval, brix_cache_advertise_conf_t::ns, brix_cache_advertise_conf_t::sitename, and brix_cache_advertise_conf_t::web_url.
Referenced by brix_cache_pelican_advertise_once().
brix_pelican_build_jwt()
static ngx_int_t brix_pelican_build_jwt (ngx_stream_brix_srv_conf_t * conf, const char * director, time_t now, char * out, size_t outsz) static
Definition at line 182 of file pelican_register.c.
References ngx_stream_brix_srv_conf_t::advertise, brix_jwt_sign_es256(), brix_pelican_cstr(), brix_pelican_hex_random(), brix_cache_advertise_conf_t::data_url, brix_cache_advertise_conf_t::issuer_url, and brix_cache_advertise_conf_t::key_pkey.
Referenced by brix_cache_pelican_advertise_once().
brix_pelican_caps_json()
static json_t * brix_pelican_caps_json (void) static
Definition at line 84 of file pelican_register.c.
References c.
Referenced by brix_pelican_build_ad().
brix_pelican_cstr()
static const char * brix_pelican_cstr (const ngx_str_t * s, const char * dflt) static
Definition at line 77 of file pelican_register.c.
References s.
Referenced by brix_pelican_build_ad(), and brix_pelican_build_jwt().
brix_pelican_discover_cfg()
static ngx_int_t brix_pelican_discover_cfg (ngx_stream_brix_srv_conf_t * conf, ngx_log_t * log, char * out, size_t outsz) static
Definition at line 250 of file pelican_register.c.
References BRIX_CACHE_IO_TIMEOUT, brix_pelican_mem2_cb(), brix_pelican_set_ca(), brix_pelican_mem2_t::buf, ngx_stream_brix_srv_conf_t::cache_origin_host, ngx_stream_brix_srv_conf_t::cache_origin_port, brix_pelican_mem2_t::cap, brix_pelican_mem2_t::len, log, and ngx_memcpy.
Referenced by brix_cache_pelican_advertise_once().
brix_pelican_hex_random()
static void brix_pelican_hex_random (char * out, size_t nbytes) static
Definition at line 55 of file pelican_register.c.
Referenced by brix_cache_pelican_schedule_advertise(), and brix_pelican_build_jwt().
brix_pelican_mem2_cb()
static size_t brix_pelican_mem2_cb (char * ptr, size_t size, size_t nmemb, void * ud) static
Definition at line 227 of file pelican_register.c.
References brix_pelican_mem2_t::buf, brix_pelican_mem2_t::cap, brix_pelican_mem2_t::len, and ngx_memcpy.
Referenced by brix_pelican_discover_cfg().
brix_pelican_post()
static ngx_int_t brix_pelican_post (ngx_stream_brix_srv_conf_t * conf, ngx_log_t * log, const char * director, const char * body, const char * jwt) static
Definition at line 318 of file pelican_register.c.
References BRIX_CACHE_IO_TIMEOUT, brix_pelican_set_ca(), and log.
Referenced by brix_cache_pelican_advertise_once().
brix_pelican_rfc3339()
static void brix_pelican_rfc3339 (time_t t, char * out, size_t outsz) static
Definition at line 47 of file pelican_register.c.
Referenced by brix_pelican_build_ad().
brix_pelican_set_ca()
static void brix_pelican_set_ca (ngx_stream_brix_srv_conf_t * conf, CURL * curl) static
Definition at line 240 of file pelican_register.c.
References ngx_stream_brix_srv_conf_t::trusted_ca.
Referenced by brix_pelican_discover_cfg(), and brix_pelican_post().