nginx-xrootd: src/fs/cache/origin/pelican_register.h File Reference
pelican_register.h File Reference
#include "fs/cache/cache_internal.h"
#include <ngx_event.h>
Functions
void brix_cache_pelican_schedule_advertise (ngx_cycle_t *cycle, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_cache_pelican_advertise_once (ngx_stream_brix_srv_conf_t *conf, ngx_log_t *log)
Function Documentation
brix_cache_pelican_advertise_once()
ngx_int_t brix_cache_pelican_advertise_once (ngx_stream_brix_srv_conf_t * conf, ngx_log_t * log)
Definition at line 379 of file pelican_register.c.
References ngx_stream_brix_srv_conf_t::advertise, brix_pelican_build_ad(), brix_pelican_build_jwt(), brix_pelican_discover_cfg(), brix_pelican_post(), brix_cache_advertise_conf_t::data_url, brix_cache_advertise_conf_t::gen, brix_cache_advertise_conf_t::key_pkey, and log.
Referenced by brix_pelican_adv_thread(), and brix_pelican_adv_timer().
brix_cache_pelican_schedule_advertise()
void brix_cache_pelican_schedule_advertise (ngx_cycle_t * cycle, ngx_stream_brix_srv_conf_t * conf)
Definition at line 464 of file pelican_register.c.
References ngx_stream_brix_srv_conf_t::advertise, brix_jwt_load_ec_key(), brix_pelican_adv_done(), brix_pelican_adv_thread(), brix_pelican_adv_timer(), brix_pelican_hex_random(), ngx_stream_brix_srv_conf_t::cache_origin_host, brix_pelican_adv_t::conf, brix_cache_advertise_conf_t::data_url, brix_cache_advertise_conf_t::enable, brix_pelican_adv_t::in_flight, brix_cache_advertise_conf_t::instance, brix_cache_advertise_conf_t::interval, brix_cache_advertise_conf_t::key, brix_cache_advertise_conf_t::key_pkey, brix_pelican_adv_t::log, ngx_pcalloc(), brix_pelican_adv_t::task, and brix_cache_advertise_conf_t::timer.
Referenced by ngx_stream_brix_init_process().