nginx-xrootd: src/net/manager/pending.h File Reference
pending.h File Reference
#include <ngx_core.h>
#include <ngx_shmtx.h>
#include "core/ngx_brix_module.h"
Data Structures
struct brix_pending_locate_t
struct brix_pending_table_t
Macros
#define BRIX_PENDING_LOCATE_SLOTS 32 /* concurrent in-flight locates */
#define BRIX_PENDING_REAP_INTERVAL_MS 5000
Functions
ngx_int_t brix_pending_configure (ngx_conf_t *cf)
WHAT: Configure the pending-locate shared-memory zone during nginx startup.
ngx_int_t brix_pending_insert (uint32_t streamid, ngx_pid_t worker_pid, int conn_fd, ngx_atomic_uint_t conn_number, const u_char client_streamid[2], ngx_msec_t timeout_ms)
brix_pending_locate_t * brix_pending_lookup (uint32_t streamid, ngx_pid_t worker_pid)
void brix_pending_unlock (void)
void brix_pending_remove (uint32_t streamid, ngx_pid_t worker_pid)
ngx_uint_t brix_pending_reap_expired (void)
Variables
ngx_shm_zone_t * brix_pending_shm_zone
Macro Definition Documentation
BRIX_PENDING_LOCATE_SLOTS
#define BRIX_PENDING_LOCATE_SLOTS 32 /* concurrent in-flight locates */
Definition at line 20 of file pending.h.
BRIX_PENDING_REAP_INTERVAL_MS
#define BRIX_PENDING_REAP_INTERVAL_MS 5000
Definition at line 77 of file pending.h.
Function Documentation
brix_pending_configure()
ngx_int_t brix_pending_configure (ngx_conf_t * cf)
WHAT: Configure the pending-locate shared-memory zone during nginx startup.
WHY: Creates a dedicated SHM region named "brix_pending_locate" that stores up to BRIX_PENDING_LOCATE_SLOTS (32) in-flight kXR_locate entries. Each entry tracks a worker's locate request until the CMS manager responds with a redirect host/port via kXR_select. HOW: Adds a shared memory zone sized via brix_shm_zone_size() so the table can be slab-allocated alongside the slab-pool header (see brix_pending_shm_init_zone), registers brix_pending_shm_init_zone as the init callback (called after allocation), and sets data=(void *) 1 as an initialization sentinel so accessors know the zone is not yet ready. Returns NGX_OK or NGX_ERROR.
Definition at line 77 of file pending.c.
brix_pending_insert()
ngx_int_t brix_pending_insert (uint32_t streamid, ngx_pid_t worker_pid, int conn_fd, ngx_atomic_uint_t conn_number, const u_char client_streamid[2], ngx_msec_t timeout_ms)
Definition at line 98 of file pending.c.
References BRIX_PENDING_LOCATE_SLOTS, brix_pending_mutex, brix_shm_remember_free_slot(), brix_shm_slot_expired(), brix_pending_locate_t::client_streamid, brix_pending_locate_t::conn_fd, brix_pending_locate_t::conn_number, brix_pending_locate_t::expires, brix_pending_locate_t::in_use, pending_table(), brix_pending_locate_t::redir_host, brix_pending_locate_t::redir_port, brix_pending_table_t::slots, brix_pending_locate_t::streamid, and brix_pending_locate_t::worker_pid.
Referenced by brix_open_cms_locate(), brix_qcksum_manager_bounce(), locate_try_cms_parent(), and stat_manager_route().
brix_pending_lookup()
brix_pending_locate_t * brix_pending_lookup (uint32_t streamid, ngx_pid_t worker_pid)
Definition at line 160 of file pending.c.
References BRIX_PENDING_LOCATE_SLOTS, brix_pending_mutex, brix_pending_locate_t::in_use, pending_table(), brix_pending_table_t::slots, brix_pending_locate_t::streamid, and brix_pending_locate_t::worker_pid.
Referenced by cms_wake_pending_session().
brix_pending_reap_expired()
ngx_uint_t brix_pending_reap_expired (void)
Definition at line 195 of file pending.c.
References BRIX_PENDING_LOCATE_SLOTS, brix_pending_mutex, brix_shm_slot_expired(), brix_pending_locate_t::expires, brix_pending_locate_t::in_use, pending_table(), and brix_pending_table_t::slots.
Referenced by brix_pending_reap_handler().
brix_pending_remove()
void brix_pending_remove (uint32_t streamid, ngx_pid_t worker_pid)
Definition at line 221 of file pending.c.
References BRIX_PENDING_LOCATE_SLOTS, brix_pending_mutex, brix_pending_locate_t::in_use, pending_table(), brix_pending_table_t::slots, brix_pending_locate_t::streamid, and brix_pending_locate_t::worker_pid.
Referenced by brix_open_cms_locate(), brix_qcksum_manager_bounce(), brix_recv_pre_loop(), cms_wake_pending_session(), locate_try_cms_parent(), and stat_manager_route().
brix_pending_unlock()
void brix_pending_unlock (void)
Definition at line 189 of file pending.c.
References brix_pending_mutex.
Referenced by cms_wake_pending_session().
Variable Documentation
brix_pending_shm_zone
ngx_shm_zone_t* brix_pending_shm_zone extern
Definition at line 5 of file pending.c.
Referenced by brix_pending_configure(), and pending_table().