nginx-xrootd: src/net/manager/pending.c File Reference
pending.c File Reference
#include "pending.h"
#include "core/compat/shm_slots.h"
#include <ngx_shmtx.h>
Functions
static brix_pending_table_t * pending_table (void)
WHAT: Retrieve the shared-memory pending-locate table pointer.
static ngx_int_t brix_pending_shm_init_zone (ngx_shm_zone_t *shm_zone, void *data)
WHAT: Initialize the pending-locate shared-memory zone.
ngx_int_t brix_pending_configure (ngx_conf_t *cf)
WHAT: Configure the pending-locate shared-memory zone during nginx startup.
ngx_int_t brix_pending_insert (uint32_t streamid, ngx_pid_t worker_pid, int conn_fd, ngx_atomic_uint_t conn_number, const u_char client_streamid[2], ngx_msec_t timeout_ms)
brix_pending_locate_t * brix_pending_lookup (uint32_t streamid, ngx_pid_t worker_pid)
void brix_pending_unlock (void)
ngx_uint_t brix_pending_reap_expired (void)
void brix_pending_remove (uint32_t streamid, ngx_pid_t worker_pid)
Variables
ngx_shm_zone_t * brix_pending_shm_zone
static ngx_shmtx_t brix_pending_mutex
Function Documentation
brix_pending_configure()
ngx_int_t brix_pending_configure (ngx_conf_t * cf)
WHAT: Configure the pending-locate shared-memory zone during nginx startup.
WHY: Creates a dedicated SHM region named "brix_pending_locate" that stores up to BRIX_PENDING_LOCATE_SLOTS (32) in-flight kXR_locate entries. Each entry tracks a worker's locate request until the CMS manager responds with a redirect host/port via kXR_select. HOW: Adds a shared memory zone sized via brix_shm_zone_size() so the table can be slab-allocated alongside the slab-pool header (see brix_pending_shm_init_zone), registers brix_pending_shm_init_zone as the init callback (called after allocation), and sets data=(void *) 1 as an initialization sentinel so accessors know the zone is not yet ready. Returns NGX_OK or NGX_ERROR.
Definition at line 77 of file pending.c.
References brix_pending_shm_init_zone(), brix_pending_shm_zone, brix_shm_zone_size(), and ngx_stream_brix_module.
Referenced by ngx_stream_brix_postconfiguration().
brix_pending_insert()
ngx_int_t brix_pending_insert (uint32_t streamid, ngx_pid_t worker_pid, int conn_fd, ngx_atomic_uint_t conn_number, const u_char client_streamid[2], ngx_msec_t timeout_ms)
Definition at line 98 of file pending.c.
References BRIX_PENDING_LOCATE_SLOTS, brix_pending_mutex, brix_shm_remember_free_slot(), brix_shm_slot_expired(), brix_pending_locate_t::client_streamid, brix_pending_locate_t::conn_fd, brix_pending_locate_t::conn_number, brix_pending_locate_t::expires, brix_pending_locate_t::in_use, pending_table(), brix_pending_locate_t::redir_host, brix_pending_locate_t::redir_port, brix_pending_table_t::slots, brix_pending_locate_t::streamid, and brix_pending_locate_t::worker_pid.
Referenced by brix_handle_locate(), brix_handle_open(), brix_handle_stat(), and brix_query_cksum_path().
brix_pending_lookup()
brix_pending_locate_t * brix_pending_lookup (uint32_t streamid, ngx_pid_t worker_pid)
Definition at line 160 of file pending.c.
References BRIX_PENDING_LOCATE_SLOTS, brix_pending_mutex, brix_pending_locate_t::in_use, pending_table(), brix_pending_table_t::slots, brix_pending_locate_t::streamid, and brix_pending_locate_t::worker_pid.
Referenced by cms_wake_pending_session().
brix_pending_reap_expired()
ngx_uint_t brix_pending_reap_expired (void)
Definition at line 195 of file pending.c.
References BRIX_PENDING_LOCATE_SLOTS, brix_pending_mutex, brix_shm_slot_expired(), brix_pending_locate_t::expires, brix_pending_locate_t::in_use, pending_table(), and brix_pending_table_t::slots.
Referenced by brix_pending_reap_handler().
brix_pending_remove()
void brix_pending_remove (uint32_t streamid, ngx_pid_t worker_pid)
Definition at line 221 of file pending.c.
References BRIX_PENDING_LOCATE_SLOTS, brix_pending_mutex, brix_pending_locate_t::in_use, pending_table(), brix_pending_table_t::slots, brix_pending_locate_t::streamid, and brix_pending_locate_t::worker_pid.
Referenced by brix_handle_locate(), brix_handle_open(), brix_handle_stat(), brix_query_cksum_path(), brix_recv_pre_loop(), and cms_wake_pending_session().
brix_pending_shm_init_zone()
static ngx_int_t brix_pending_shm_init_zone (ngx_shm_zone_t * shm_zone, void * data) static
WHAT: Initialize the pending-locate shared-memory zone.
WHY: Called during nginx configuration to allocate the shared memory region that holds slots for in-flight kXR_locate requests. The mutex is created here so all workers can safely access the table. HOW: Delegates fresh-alloc / reload / re-attach to brix_shm_table_alloc(), which allocates the table FROM the slab pool (leaving nginx's ngx_slab_pool_t header at shm.addr intact so ngx_unlock_mutexes() does not clobber it when a child exits) and publishes it via shm_zone->data. The mutex is created from the table's leading ngx_shmtx_sh_t lock. Only a brand-new allocation (fresh==1) zeroes the slot array; on reload/re-attach the live slot state is preserved. Returns NGX_OK or NGX_ERROR.
Definition at line 44 of file pending.c.
References brix_pending_mutex, brix_shm_table_alloc(), and brix_pending_table_t::slots.
Referenced by brix_pending_configure().
brix_pending_unlock()
void brix_pending_unlock (void)
Definition at line 189 of file pending.c.
References brix_pending_mutex.
Referenced by cms_wake_pending_session().
pending_table()
static brix_pending_table_t * pending_table (void) static
WHAT: Retrieve the shared-memory pending-locate table pointer.
WHY: All operations in this module access a single shm_zone to track in-flight kXR_locate requests across workers. This helper centralizes NULL-check logic so callers don't repeat it. HOW: Returns NULL if the shm_zone hasn't been allocated yet, is still at initialization sentinel ((void *) 1), or has no data attached. Otherwise casts and returns the zone->data pointer as brix_pending_table_t*.
Definition at line 19 of file pending.c.
References brix_pending_shm_zone.
Referenced by brix_pending_insert(), brix_pending_lookup(), brix_pending_reap_expired(), and brix_pending_remove().
Variable Documentation
brix_pending_mutex
ngx_shmtx_t brix_pending_mutex static
Definition at line 7 of file pending.c.
Referenced by brix_pending_insert(), brix_pending_lookup(), brix_pending_reap_expired(), brix_pending_remove(), brix_pending_shm_init_zone(), and brix_pending_unlock().
brix_pending_shm_zone
ngx_shm_zone_t* brix_pending_shm_zone
Definition at line 5 of file pending.c.
Referenced by brix_pending_configure(), and pending_table().