nginx-xrootd: src/core/compat/pgio.c File Reference
pgio.c File Reference
#include "pgio.h"
#include "crc32c.h"
#include "protocols/root/protocol/flags.h"
#include <string.h>
#include <stdint.h>
#include <arpa/inet.h>
Macros
#define XRDP_PG_CKSZ 4 /* one CRC32c per page (big-endian) */
Functions
size_t xrdp_pg_encode (const uint8_t *src, size_t len, int64_t file_off, uint8_t *dst)
ssize_t xrdp_pg_decode (const uint8_t *pg, size_t pglen, int64_t file_off, uint8_t *dst, size_t dstcap, int64_t *bad_off)
ssize_t xrdp_pg_decode_collect (const uint8_t *pg, size_t pglen, int64_t file_off, uint8_t *dst, size_t dstcap, xrdp_pg_bad_t *bad_out, size_t max_bad, size_t *bad_count)
Macro Definition Documentation
XRDP_PG_CKSZ
#define XRDP_PG_CKSZ 4 /* one CRC32c per page (big-endian) */
Definition at line 15 of file pgio.c.
Function Documentation
xrdp_pg_decode()
ssize_t xrdp_pg_decode (const uint8_t * pg, size_t pglen, int64_t file_off, uint8_t * dst, size_t dstcap, int64_t * bad_off)
Definition at line 45 of file pgio.c.
References brix_crc32c_copy_value(), kXR_pgPageSZ, and XRDP_PG_CKSZ.
Referenced by brix_pgwrite_decode_payload(), and decode_pages().
xrdp_pg_decode_collect()
ssize_t xrdp_pg_decode_collect (const uint8_t * pg, size_t pglen, int64_t file_off, uint8_t * dst, size_t dstcap, xrdp_pg_bad_t * bad_out, size_t max_bad, size_t * bad_count)
Definition at line 96 of file pgio.c.
References brix_crc32c_copy_value(), xrdp_pg_bad_t::dlen, kXR_pgPageSZ, xrdp_pg_bad_t::off, and XRDP_PG_CKSZ.
Referenced by pgwrite_decode_collect().
xrdp_pg_encode()
size_t xrdp_pg_encode (const uint8_t * src, size_t len, int64_t file_off, uint8_t * dst)
Definition at line 18 of file pgio.c.
References brix_crc32c_copy_value(), kXR_pgPageSZ, and XRDP_PG_CKSZ.
Referenced by brix_file_pgwrite(), brix_pgread_encode_pages(), and pgwrite_retry_one().