nginx-xrootd: src/protocols/root/read/pgread_encode.c File Reference
pgread_encode.c File Reference
#include "read.h"
#include "fs/backend/sd.h"
#include "core/compat/pgio.h"
#include "core/compat/crc32c.h"
#include <sys/uio.h>
Data Structures
struct brix_pgread_batch_t
Macros
#define BRIX_PG_CKSZ ((size_t) (kXR_pgUnitSZ - kXR_pgPageSZ))
#define BRIX_PGREAD_MAXIOV 64
Functions
static u_char * brix_pgread_layout_batch (off_t offset, size_t rlen, size_t remaining, u_char *o, brix_pgread_batch_t *b)
static int brix_pgread_crc_batch (brix_pgread_batch_t *b, size_t got, size_t *out_size)
size_t brix_pgread_read_encode_inplace (brix_sd_obj_t *obj, off_t offset, size_t rlen, u_char *out, brix_pgread_io_t *io)
size_t brix_pgread_encode_pages (const u_char *src, size_t len, off_t offset, u_char *dst)
Macro Definition Documentation
BRIX_PG_CKSZ
#define BRIX_PG_CKSZ ((size_t) (kXR_pgUnitSZ - kXR_pgPageSZ))
Definition at line 21 of file pgread_encode.c.
BRIX_PGREAD_MAXIOV
#define BRIX_PGREAD_MAXIOV 64
Definition at line 23 of file pgread_encode.c.
Function Documentation
brix_pgread_crc_batch()
static int brix_pgread_crc_batch (brix_pgread_batch_t * b, size_t got, size_t * out_size) static
Definition at line 107 of file pgread_encode.c.
References brix_crc32c_value(), BRIX_PG_CKSZ, brix_pgread_batch_t::data, brix_pgread_batch_t::dlen, and brix_pgread_batch_t::k.
Referenced by brix_pgread_read_encode_inplace().
brix_pgread_encode_pages()
size_t brix_pgread_encode_pages (const u_char * src, size_t len, off_t offset, u_char * dst)
Definition at line 233 of file pgread_encode.c.
References xrdp_pg_encode().
brix_pgread_layout_batch()
static u_char * brix_pgread_layout_batch (off_t offset, size_t rlen, size_t remaining, u_char * o, brix_pgread_batch_t * b) static
Definition at line 64 of file pgread_encode.c.
References BRIX_PG_CKSZ, BRIX_PGREAD_MAXIOV, brix_pgread_batch_t::bytes, brix_pgread_batch_t::data, brix_pgread_batch_t::dlen, brix_pgread_batch_t::iov, brix_pgread_batch_t::k, and kXR_pgPageSZ.
Referenced by brix_pgread_read_encode_inplace().
brix_pgread_read_encode_inplace()
size_t brix_pgread_read_encode_inplace (brix_sd_obj_t * obj, off_t offset, size_t rlen, u_char * out, brix_pgread_io_t * io)
Definition at line 159 of file pgread_encode.c.
References brix_pgread_crc_batch(), brix_pgread_layout_batch(), brix_sd_obj_preadv(), brix_pgread_batch_t::bytes, brix_pgread_io_t::io_errno, brix_pgread_batch_t::iov, brix_pgread_batch_t::k, brix_pgread_io_t::nowait, and brix_pgread_io_t::nread.
Referenced by brix_pgread_try_warm(), and brix_vfs_io_execute_pgread().