nginx-xrootd: src/protocols/root/read/pgread.c File Reference
pgread.c File Reference
#include "read.h"
#include "core/ngx_brix_module.h"
#include "fs/backend/sd.h"
#include "fs/vfs/vfs_io_core.h"
#include "core/compat/pgio.h"
#include "core/compat/crc32c.h"
#include <sys/uio.h>
Data Structures
struct brix_pgread_batch_t
struct brix_pgread_run_t
Macros
#define BRIX_PG_CKSZ ((size_t) (kXR_pgUnitSZ - kXR_pgPageSZ))
#define BRIX_PGREAD_MAXIOV 64
Functions
static u_char * brix_pgread_layout_batch (off_t offset, size_t rlen, size_t remaining, u_char *o, brix_pgread_batch_t *b)
static int brix_pgread_crc_batch (brix_pgread_batch_t *b, size_t got, size_t *out_size)
size_t brix_pgread_read_encode_inplace (brix_sd_obj_t *obj, off_t offset, size_t rlen, u_char *out, brix_pgread_io_t *io)
size_t brix_pgread_encode_pages (const u_char *src, size_t len, off_t offset, u_char *dst)
static ngx_int_t brix_pgread_parse_validate (brix_ctx_t *ctx, ngx_connection_t *c, brix_pgread_run_t *run, ngx_int_t *rc)
static u_char * brix_pgread_alloc_scratch (brix_ctx_t *ctx, ngx_connection_t *c, brix_pgread_run_t *run)
static ngx_flag_t brix_pgread_try_warm (brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *rconf, brix_pgread_run_t *run)
static ngx_int_t brix_pgread_post_aio (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf, brix_pgread_run_t *run)
static int brix_pgread_sync_fill (brix_ctx_t *ctx, brix_pgread_run_t *run)
static ngx_int_t brix_pgread_send_response (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf, brix_pgread_run_t *run)
ngx_int_t brix_handle_pgread (brix_ctx_t *ctx, ngx_connection_t *c)
Macro Definition Documentation
BRIX_PG_CKSZ
#define BRIX_PG_CKSZ ((size_t) (kXR_pgUnitSZ - kXR_pgPageSZ))
Definition at line 16 of file pgread.c.
BRIX_PGREAD_MAXIOV
#define BRIX_PGREAD_MAXIOV 64
Definition at line 18 of file pgread.c.
Function Documentation
brix_handle_pgread()
ngx_int_t brix_handle_pgread (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 598 of file pgread.c.
References BRIX_OP_PGREAD, brix_pgread_alloc_scratch(), brix_pgread_parse_validate(), brix_pgread_post_aio(), brix_pgread_send_response(), brix_pgread_sync_fill(), brix_pgread_try_warm(), BRIX_RETURN_ERR, c, brix_ctx_t::files, brix_pgread_run_t::idx, kXR_IOError, kXR_ServerError, ngx_stream_brix_module, brix_pgread_run_t::out_buf, brix_file_t::path, and brix_pgread_run_t::scratch.
Referenced by brix_dispatch_read_opcode().
brix_pgread_alloc_scratch()
static u_char * brix_pgread_alloc_scratch (brix_ctx_t * ctx, ngx_connection_t * c, brix_pgread_run_t * run) static
Definition at line 346 of file pgread.c.
References BRIX_GET_SCRATCH, BRIX_PG_CKSZ, c, kXR_pgPageSZ, brix_pgread_run_t::offset, and brix_pgread_run_t::rlen.
Referenced by brix_handle_pgread().
brix_pgread_crc_batch()
static int brix_pgread_crc_batch (brix_pgread_batch_t * b, size_t got, size_t * out_size) static
Definition at line 102 of file pgread.c.
References brix_crc32c_value(), BRIX_PG_CKSZ, brix_pgread_batch_t::data, brix_pgread_batch_t::dlen, and brix_pgread_batch_t::k.
Referenced by brix_pgread_read_encode_inplace().
brix_pgread_encode_pages()
size_t brix_pgread_encode_pages (const u_char * src, size_t len, off_t offset, u_char * dst)
Definition at line 228 of file pgread.c.
References xrdp_pg_encode().
brix_pgread_layout_batch()
static u_char * brix_pgread_layout_batch (off_t offset, size_t rlen, size_t remaining, u_char * o, brix_pgread_batch_t * b) static
Definition at line 59 of file pgread.c.
References BRIX_PG_CKSZ, BRIX_PGREAD_MAXIOV, brix_pgread_batch_t::bytes, brix_pgread_batch_t::data, brix_pgread_batch_t::dlen, brix_pgread_batch_t::iov, brix_pgread_batch_t::k, and kXR_pgPageSZ.
Referenced by brix_pgread_read_encode_inplace().
brix_pgread_parse_validate()
static ngx_int_t brix_pgread_parse_validate (brix_ctx_t * ctx, ngx_connection_t * c, brix_pgread_run_t * run, ngx_int_t * rc) static
Definition at line 276 of file pgread.c.
References brix_build_pgread_status(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_PGREAD, brix_queue_response(), BRIX_READ_REQUEST_MAX, brix_send_error(), brix_validate_read_handle(), c, brix_file_t::fd, brix_pgread_run_t::fd, xrdw_pgread_req_t::fhandle, brix_ctx_t::files, brix_ctx_recv_t::hdr_buf, brix_pgread_run_t::idx, kXR_ArgInvalid, kXR_IOError, xrdw_pgread_req_t::offset, brix_pgread_run_t::offset, brix_ctx_t::recv, xrdw_pgread_req_t::rlen, brix_pgread_run_t::rlen, and xrdw_pgread_req_unpack().
Referenced by brix_handle_pgread().
brix_pgread_post_aio()
static ngx_int_t brix_pgread_post_aio (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf, brix_pgread_run_t * run) static
Definition at line 452 of file pgread.c.
References brix_aio_post_task(), brix_pgread_aio_done(), brix_pgread_aio_thread(), c, brix_pgread_aio_t::c, brix_pgread_aio_t::ctx, brix_ctx_recv_t::cur_streamid, brix_pgread_aio_t::fd, brix_pgread_run_t::fd, brix_ctx_t::files, brix_pgread_aio_t::handle_idx, brix_pgread_run_t::idx, brix_pgread_aio_t::obj, brix_pgread_aio_t::offset, brix_pgread_run_t::offset, brix_pgread_aio_t::out_size, brix_ctx_rd_t::pgread_aio_task, brix_ctx_t::rd, brix_ctx_t::recv, brix_pgread_aio_t::rlen, brix_pgread_run_t::rlen, brix_pgread_aio_t::scratch, brix_pgread_run_t::scratch, brix_file_t::sd_obj, and brix_pgread_aio_t::streamid.
Referenced by brix_handle_pgread().
brix_pgread_read_encode_inplace()
size_t brix_pgread_read_encode_inplace (brix_sd_obj_t * obj, off_t offset, size_t rlen, u_char * out, brix_pgread_io_t * io)
Definition at line 154 of file pgread.c.
References brix_pgread_crc_batch(), brix_pgread_layout_batch(), brix_sd_obj_preadv(), brix_pgread_batch_t::bytes, brix_pgread_io_t::io_errno, brix_pgread_batch_t::iov, brix_pgread_batch_t::k, brix_pgread_io_t::nowait, and brix_pgread_io_t::nread.
Referenced by brix_pgread_try_warm(), and brix_vfs_io_execute_pgread().
brix_pgread_send_response()
static ngx_int_t brix_pgread_send_response (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf, brix_pgread_run_t * run) static
Definition at line 550 of file pgread.c.
References brix_build_pgread_chain(), brix_log_access(), BRIX_OP_OK, BRIX_OP_PGREAD, brix_queue_response_chain(), brix_release_read_buffer(), brix_rl_charge_ctx(), brix_ctx_totals_t::bytes, brix_file_t::bytes_read, c, brix_ctx_t::files, brix_pgread_run_t::flat_buf, brix_pgread_run_t::idx, brix_pgread_run_t::offset, brix_pgread_run_t::out_buf, brix_pgread_run_t::out_size, brix_file_t::path, brix_pgread_run_t::rlen, brix_ctx_t::state, brix_ctx_t::totals, and XRD_ST_SENDING.
Referenced by brix_handle_pgread().
brix_pgread_sync_fill()
static int brix_pgread_sync_fill (brix_ctx_t * ctx, brix_pgread_run_t * run) static
Definition at line 512 of file pgread.c.
References brix_vfs_io_execute(), BRIX_VFS_IO_PGREAD, brix_vfs_job_read_init(), brix_vfs_job_set_obj(), brix_pgread_run_t::fd, brix_ctx_t::files, brix_pgread_run_t::flat_buf, brix_pgread_run_t::idx, brix_vfs_job_t::io_errno, brix_vfs_job_t::nio, brix_pgread_run_t::offset, brix_vfs_job_t::op, brix_pgread_run_t::out_buf, brix_vfs_job_t::out_size, brix_pgread_run_t::out_size, brix_pgread_run_t::rlen, brix_pgread_run_t::scratch, and brix_file_t::sd_obj.
Referenced by brix_handle_pgread().
brix_pgread_try_warm()
static ngx_flag_t brix_pgread_try_warm (brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * rconf, brix_pgread_run_t * run) static
Definition at line 389 of file pgread.c.
References brix_metric_backend_bytes(), BRIX_METRIC_OP_READ, brix_pgread_read_encode_inplace(), brix_vfs_effective_obj(), brix_pgread_run_t::fd, brix_ctx_t::files, brix_pgread_run_t::flat_buf, brix_pgread_run_t::idx, brix_pgread_io_t::io_errno, brix_file_t::is_regular, brix_pgread_io_t::nowait, brix_pgread_io_t::nread, brix_pgread_run_t::offset, brix_pgread_run_t::out_buf, brix_pgread_run_t::out_size, brix_pgread_run_t::rlen, brix_pgread_run_t::scratch, and brix_file_t::sd_obj.
Referenced by brix_handle_pgread().