nginx-xrootd: src/protocols/root/write/pgw_fob.c File Reference
pgw_fob.c File Reference
#include "core/ngx_brix_module.h"
#include "pgw_fob.h"
#include "protocols/root/protocol/flags.h"
#include <string.h>
Functions
static int64_t pgw_fob_key (int64_t off, uint32_t dlen)
void brix_pgw_fob_open (brix_file_t *f)
int brix_pgw_fob_add (brix_file_t *f, int64_t off, uint32_t dlen)
int brix_pgw_fob_del (brix_file_t *f, int64_t off, uint32_t dlen)
int brix_pgw_fob_has (const brix_file_t *f, int64_t off, uint32_t dlen)
uint32_t brix_pgw_fob_count (const brix_file_t *f)
void brix_pgw_fob_reset (brix_file_t *f)
Function Documentation
brix_pgw_fob_add()
int brix_pgw_fob_add (brix_file_t * f, int64_t off, uint32_t dlen)
Definition at line 43 of file pgw_fob.c.
References BRIX_PGW_FOB_SLOTS, brix_pgw_fob_entry_t::key, key, brix_file_t::pgw_fob, brix_file_t::pgw_fob_count, brix_file_t::pgw_fob_errs, pgw_fob_key(), and brix_pgw_fob_entry_t::used.
Referenced by pgwrite_register_bad_pages().
brix_pgw_fob_count()
uint32_t brix_pgw_fob_count (const brix_file_t * f)
Definition at line 107 of file pgw_fob.c.
References brix_file_t::pgw_fob_count.
Referenced by brix_close_pgw_gate().
brix_pgw_fob_del()
int brix_pgw_fob_del (brix_file_t * f, int64_t off, uint32_t dlen)
Definition at line 73 of file pgw_fob.c.
References BRIX_PGW_FOB_SLOTS, brix_pgw_fob_entry_t::key, key, brix_file_t::pgw_fob, brix_file_t::pgw_fob_count, brix_file_t::pgw_fob_fixes, pgw_fob_key(), and brix_pgw_fob_entry_t::used.
Referenced by pgwrite_execute_sync().
brix_pgw_fob_has()
int brix_pgw_fob_has (const brix_file_t * f, int64_t off, uint32_t dlen)
Definition at line 93 of file pgw_fob.c.
References BRIX_PGW_FOB_SLOTS, brix_pgw_fob_entry_t::key, key, brix_file_t::pgw_fob, pgw_fob_key(), and brix_pgw_fob_entry_t::used.
Referenced by pgwrite_parse_validate().
brix_pgw_fob_open()
void brix_pgw_fob_open (brix_file_t * f)
Definition at line 30 of file pgw_fob.c.
References brix_file_t::pgw_fob, brix_file_t::pgw_fob_count, brix_file_t::pgw_fob_enabled, brix_file_t::pgw_fob_errs, and brix_file_t::pgw_fob_fixes.
Referenced by pgwrite_register_bad_pages().
brix_pgw_fob_reset()
void brix_pgw_fob_reset (brix_file_t * f)
Definition at line 113 of file pgw_fob.c.
References brix_file_t::pgw_fob, brix_file_t::pgw_fob_count, brix_file_t::pgw_fob_enabled, brix_file_t::pgw_fob_errs, and brix_file_t::pgw_fob_fixes.
Referenced by fhandle_reset_slot().
pgw_fob_key()
static int64_t pgw_fob_key (int64_t off, uint32_t dlen) static
Definition at line 19 of file pgw_fob.c.
References key, kXR_pgPageBL, and kXR_pgPageSZ.
Referenced by brix_pgw_fob_add(), brix_pgw_fob_del(), and brix_pgw_fob_has().