nginx-xrootd: src/protocols/root/write/pgwrite.c File Reference
pgwrite.c File Reference
#include "core/ngx_brix_module.h"
#include "fs/cache/writethrough_metrics.h"
#include "wrts_journal.h"
#include "pgw_fob.h"
#include "core/compat/pgio.h"
Data Structures
struct pgw_state_t
Functions
static int pgwrite_retry_spans_multiple_pages (int64_t offset, size_t dlen)
ngx_int_t brix_pgwrite_decode_payload (const u_char *payload, size_t payload_len, int64_t offset, u_char *flat, size_t *flat_len, int64_t *bad_offset)
static void pgw_fmt_detail (char *buf, size_t bufsz, int64_t offset, size_t len)
static ngx_flag_t pgwrite_parse_validate (brix_ctx_t *ctx, ngx_connection_t *c, pgw_state_t *st, ngx_int_t *rc)
static ngx_flag_t pgwrite_register_bad_pages (brix_ctx_t *ctx, ngx_connection_t *c, pgw_state_t *st, ngx_int_t *rc)
static ngx_flag_t pgwrite_decode_collect (brix_ctx_t *ctx, ngx_connection_t *c, pgw_state_t *st, ngx_int_t *rc)
static ngx_flag_t pgwrite_execute_sync (brix_ctx_t *ctx, ngx_connection_t *c, pgw_state_t *st, ngx_int_t *rc)
ngx_int_t brix_handle_pgwrite (brix_ctx_t *ctx, ngx_connection_t *c)
Function Documentation
brix_handle_pgwrite()
ngx_int_t brix_handle_pgwrite (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 424 of file pgwrite.c.
References pgw_state_t::bad_count, pgw_state_t::bad_pages, BRIX_OP_OK, BRIX_OP_WRITE, BRIX_RETURN_ERR, brix_send_pgwrite_status(), brix_staged_append(), brix_try_post_write_aio(), c, pgw_state_t::dlen, brix_ctx_t::files, pgw_state_t::flat, pgw_state_t::flat_sz, pgw_state_t::idx, pgw_state_t::is_retry, kXR_ChkSumErr, ngx_stream_brix_module, pgw_state_t::offset, brix_file_t::path, pgw_fmt_detail(), pgwrite_decode_collect(), pgwrite_execute_sync(), pgwrite_parse_validate(), pgw_state_t::rconf, and brix_file_t::writer.
brix_pgwrite_decode_payload()
ngx_int_t brix_pgwrite_decode_payload (const u_char * payload, size_t payload_len, int64_t offset, u_char * flat, size_t * flat_len, int64_t * bad_offset)
Definition at line 44 of file pgwrite.c.
References XRD_PGWRITE_CKSZ, and xrdp_pg_decode().
Referenced by ckp_xeq_pgwrite().
pgw_fmt_detail()
static void pgw_fmt_detail (char * buf, size_t bufsz, int64_t offset, size_t len) static
Definition at line 109 of file pgwrite.c.
Referenced by brix_handle_pgwrite(), pgwrite_decode_collect(), pgwrite_execute_sync(), pgwrite_parse_validate(), and pgwrite_register_bad_pages().
pgwrite_decode_collect()
static ngx_flag_t pgwrite_decode_collect (brix_ctx_t * ctx, ngx_connection_t * c, pgw_state_t * st, ngx_int_t * rc) static
Definition at line 231 of file pgwrite.c.
References pgw_state_t::bad_count, pgw_state_t::bad_pages, BRIX_GET_SCRATCH, BRIX_OP_OK, BRIX_OP_WRITE, BRIX_RETURN_ERR, brix_send_pgwrite_status(), brix_wrts_is_replay(), c, pgw_state_t::dlen, brix_ctx_t::files, pgw_state_t::flat, pgw_state_t::flat_sz, pgw_state_t::idx, pgw_state_t::is_retry, kXR_ArgInvalid, kXR_pgMaxEpr, kXR_TooManyErrs, pgw_state_t::offset, brix_file_t::path, pgw_state_t::payload, pgw_fmt_detail(), pgwrite_register_bad_pages(), brix_file_t::wrts_enabled, and xrdp_pg_decode_collect().
Referenced by brix_handle_pgwrite().
pgwrite_execute_sync()
static ngx_flag_t pgwrite_execute_sync (brix_ctx_t * ctx, ngx_connection_t * c, pgw_state_t * st, ngx_int_t * rc) static
Definition at line 311 of file pgwrite.c.
References pgw_state_t::bad_count, pgw_state_t::bad_pages, brix_log_access(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_WRITE, brix_pgw_fob_del(), brix_rl_charge_ctx(), brix_send_error(), brix_send_pgwrite_cse(), brix_send_pgwrite_status(), brix_vfs_io_execute(), brix_vfs_job_set_obj(), brix_vfs_job_write_init(), brix_wrts_record(), brix_wt_mark_dirty(), brix_ctx_totals_t::bytes_written, brix_file_t::bytes_written, c, brix_file_t::csi, brix_vfs_job_t::csi, brix_file_t::fd, brix_ctx_t::files, pgw_state_t::flat, pgw_state_t::flat_sz, pgw_state_t::idx, brix_vfs_job_t::io_errno, pgw_state_t::is_retry, kXR_IOError, brix_vfs_job_t::nio, pgw_state_t::offset, brix_file_t::path, pgw_fmt_detail(), pgw_state_t::rconf, brix_file_t::sd_obj, brix_ctx_t::totals, brix_file_t::wrts_enabled, and brix_file_t::wt_enabled.
Referenced by brix_handle_pgwrite().
pgwrite_parse_validate()
static ngx_flag_t pgwrite_parse_validate (brix_ctx_t * ctx, ngx_connection_t * c, pgw_state_t * st, ngx_int_t * rc) static
Definition at line 126 of file pgwrite.c.
References brix_log_access(), BRIX_OP_ERR, BRIX_OP_WRITE, brix_pgw_fob_has(), BRIX_RETURN_ERR, brix_send_error(), brix_validate_write_handle(), c, brix_ctx_recv_t::cur_dlen, pgw_state_t::dlen, xrdw_pgwrite_req_t::fhandle, brix_ctx_t::files, brix_ctx_recv_t::hdr_buf, pgw_state_t::idx, pgw_state_t::is_retry, kXR_ArgInvalid, kXR_pgRetry, xrdw_pgwrite_req_t::offset, pgw_state_t::offset, brix_file_t::path, brix_ctx_recv_t::payload, pgw_state_t::payload, pgw_fmt_detail(), pgwrite_retry_spans_multiple_pages(), brix_ctx_t::recv, pgw_state_t::req, xrdw_pgwrite_req_t::reqflags, XRD_PGWRITE_CKSZ, and xrdw_pgwrite_req_unpack().
Referenced by brix_handle_pgwrite().
pgwrite_register_bad_pages()
static ngx_flag_t pgwrite_register_bad_pages (brix_ctx_t * ctx, ngx_connection_t * c, pgw_state_t * st, ngx_int_t * rc) static
Definition at line 192 of file pgwrite.c.
References pgw_state_t::bad_count, pgw_state_t::bad_pages, brix_log_access(), BRIX_OP_ERR, BRIX_OP_WRITE, brix_pgw_fob_add(), brix_pgw_fob_open(), brix_send_error(), c, xrdp_pg_bad_t::dlen, pgw_state_t::dlen, brix_ctx_t::files, pgw_state_t::idx, kXR_TooManyErrs, xrdp_pg_bad_t::off, pgw_state_t::offset, brix_file_t::path, and pgw_fmt_detail().
Referenced by pgwrite_decode_collect().
pgwrite_retry_spans_multiple_pages()
static int pgwrite_retry_spans_multiple_pages (int64_t offset, size_t dlen) static
Definition at line 17 of file pgwrite.c.
References kXR_pgPageSZ, kXR_pgUnitSZ, and XRD_PGWRITE_CKSZ.
Referenced by pgwrite_parse_validate().