nginx-xrootd: src/auth/crypto/pki_check.c File Reference
pki_check.c File Reference
#include "pki_check.h"
#include <ngx_config.h>
#include <ngx_core.h>
#include "core/compat/log_diag.h"
#include <openssl/pem.h>
#include <openssl/evp.h>
Macros
#define HAVE_X509_CRL_GET0_ISSUER 0
#define CRL_GET_ISSUER(crl) X509_CRL_get_issuer((crl))
Functions
static char * brix_pki_name_to_str (const X509_NAME *name)
static void brix_pki_log_name_error (ngx_log_t *log, const char *log_prefix, const char *message, const X509_NAME *name)
static ngx_flag_t brix_pki_crl_matches_ca (X509_CRL *crl, X509 *ca_cert)
static ngx_flag_t brix_pki_crl_signature_valid (ngx_log_t *log, X509_CRL *crl, X509 *issuer_ca, const char *log_prefix)
ngx_int_t brix_pki_verify_crls (ngx_log_t *log, STACK_OF(X509) *ca_certs, STACK_OF(X509_CRL) *crls, const char *log_prefix)
ngx_int_t brix_pki_check_paths (ngx_log_t *log, const char *ca_path, const char *crl_path, const char *log_prefix)
int brix_check_pki_and_crl (const char *ca_dir, const char *crl_dir, ngx_log_t *log)
Macro Definition Documentation
CRL_GET_ISSUER
#define CRL_GET_ISSUER (crl) X509_CRL_get_issuer((crl))
Definition at line 27 of file pki_check.c.
HAVE_X509_CRL_GET0_ISSUER
#define HAVE_X509_CRL_GET0_ISSUER 0
Definition at line 20 of file pki_check.c.
Function Documentation
brix_check_pki_and_crl()
int brix_check_pki_and_crl (const char * ca_dir, const char * crl_dir, ngx_log_t * log)
Definition at line 253 of file pki_check.c.
References brix_pki_check_paths(), and log.
brix_pki_check_paths()
ngx_int_t brix_pki_check_paths (ngx_log_t * log, const char * ca_path, const char * crl_path, const char * log_prefix)
Definition at line 205 of file pki_check.c.
References BRIX_DIAG_WARN, brix_pki_verify_crls(), log, and STACK_OF().
Referenced by brix_check_pki_and_crl(), brix_check_pki_consistency_stream(), and webdav_check_pki_consistency().
brix_pki_crl_matches_ca()
static ngx_flag_t brix_pki_crl_matches_ca (X509_CRL * crl, X509 * ca_cert) static
Definition at line 80 of file pki_check.c.
References CRL_GET_ISSUER.
Referenced by brix_pki_verify_crls().
brix_pki_crl_signature_valid()
static ngx_flag_t brix_pki_crl_signature_valid (ngx_log_t * log, X509_CRL * crl, X509 * issuer_ca, const char * log_prefix) static
Definition at line 101 of file pki_check.c.
References brix_pki_log_name_error(), and log.
Referenced by brix_pki_verify_crls().
brix_pki_log_name_error()
static void brix_pki_log_name_error (ngx_log_t * log, const char * log_prefix, const char * message, const X509_NAME * name) static
Definition at line 55 of file pki_check.c.
References brix_pki_name_to_str(), log, and name.
Referenced by brix_pki_crl_signature_valid(), and brix_pki_verify_crls().
brix_pki_name_to_str()
static char * brix_pki_name_to_str (const X509_NAME * name) static
Definition at line 40 of file pki_check.c.
References name.
Referenced by brix_pki_log_name_error().
brix_pki_verify_crls()
ngx_int_t brix_pki_verify_crls (ngx_log_t * log, STACK_OF(X509) * ca_certs, STACK_OF(X509_CRL) * crls, const char * log_prefix)
Definition at line 153 of file pki_check.c.
References brix_pki_crl_matches_ca(), brix_pki_crl_signature_valid(), brix_pki_log_name_error(), CRL_GET_ISSUER, and log.
Referenced by brix_pki_check_paths().