nginx-xrootd: src/auth/crypto/pki_build.c File Reference
pki_build.c File Reference
#include "pki_build.h"
#include "auth/crypto/store_policy.h"
#include <openssl/pem.h>
#include <openssl/x509_vfy.h>
#include <openssl/x509v3.h>
#include <dirent.h>
#include <fcntl.h>
#include <limits.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
Data Structures
struct brix_ca_store_cache_ent_t
Macros
#define BRIX_CA_STORE_CACHE_MAX 16
Functions
static int pki_load_crls_from_file (X509_STORE *store, const char *path, ngx_log_t *log)
static int pki_crl_name_matches (const char *name)
static int pki_load_crls_from_dirent (X509_STORE *store, const char *dir_path, const char *name, ngx_log_t *log)
static int pki_load_crls_from_dir (X509_STORE *store, const char *path, ngx_log_t *log)
static int pki_load_crls (X509_STORE *store, const char *path, ngx_log_t *log)
static void brix_pki_sp_log (void *log, int level, const char *msg)
X509_STORE * brix_build_ca_store (ngx_log_t *log, const char *cadir, const char *cafile, const char *crl_path, unsigned long extra_flags, int *crl_count_out, brix_sp_mode_t sp_mode, int crl_mode)
static void brix_ca_store_cache_key (char *buf, size_t buflen, const char *cadir, const char *cafile, const char *crl_path, unsigned long extra_flags, brix_sp_mode_t sp_mode, int crl_mode)
static X509_STORE * brix_ca_store_cache_get (const char *key, ngx_log_t *log, const char *cadir, const char *cafile, int *crl_count_out, int *free_slot_out)
static void brix_ca_store_cache_put (int slot, const char *key, X509_STORE *store, int crl_count)
X509_STORE * brix_build_ca_store_cached (void *scope, ngx_log_t *log, const char *cadir, const char *cafile, const char *crl_path, unsigned long extra_flags, int *crl_count_out, brix_sp_mode_t sp_mode, int crl_mode)
Variables
static brix_ca_store_cache_ent_t brix_ca_store_cache [16]
Macro Definition Documentation
BRIX_CA_STORE_CACHE_MAX
#define BRIX_CA_STORE_CACHE_MAX 16
Definition at line 265 of file pki_build.c.
Function Documentation
brix_build_ca_store()
X509_STORE * brix_build_ca_store (ngx_log_t * log, const char * cadir, const char * cafile, const char * crl_path, unsigned long extra_flags, int * crl_count_out, brix_sp_mode_t sp_mode, int crl_mode)
Definition at line 191 of file pki_build.c.
References brix_pki_sp_log(), brix_store_configure(), log, and pki_load_crls().
Referenced by brix_build_ca_store_cached(), sd_xroot_origin_build_ca_store(), and webdav_build_ca_store().
brix_build_ca_store_cached()
X509_STORE * brix_build_ca_store_cached (void * scope, ngx_log_t * log, const char * cadir, const char * cafile, const char * crl_path, unsigned long extra_flags, int * crl_count_out, brix_sp_mode_t sp_mode, int crl_mode)
Definition at line 366 of file pki_build.c.
References brix_build_ca_store(), brix_ca_store_cache_get(), brix_ca_store_cache_key(), brix_ca_store_cache_put(), key, log, and scope.
Referenced by brix_ftp_build_gsi(), and brix_rebuild_gsi_store().
brix_ca_store_cache_get()
static X509_STORE * brix_ca_store_cache_get (const char * key, ngx_log_t * log, const char * cadir, const char * cafile, int * crl_count_out, int * free_slot_out) static
Definition at line 302 of file pki_build.c.
References brix_ca_store_cache, BRIX_CA_STORE_CACHE_MAX, brix_ca_store_cache_ent_t::crl_count, key, brix_ca_store_cache_ent_t::key, log, and brix_ca_store_cache_ent_t::store.
Referenced by brix_build_ca_store_cached().
brix_ca_store_cache_key()
static void brix_ca_store_cache_key (char * buf, size_t buflen, const char * cadir, const char * cafile, const char * crl_path, unsigned long extra_flags, brix_sp_mode_t sp_mode, int crl_mode) static
Definition at line 283 of file pki_build.c.
Referenced by brix_build_ca_store_cached().
brix_ca_store_cache_put()
static void brix_ca_store_cache_put (int slot, const char * key, X509_STORE * store, int crl_count) static
Definition at line 342 of file pki_build.c.
References brix_ca_store_cache, brix_ca_store_cache_ent_t::crl_count, key, brix_ca_store_cache_ent_t::key, and brix_ca_store_cache_ent_t::store.
Referenced by brix_build_ca_store_cached().
brix_pki_sp_log()
static void brix_pki_sp_log (void * log, int level, const char * msg) static
Definition at line 184 of file pki_build.c.
References BRIX_SP_LOG_WARN, and log.
Referenced by brix_build_ca_store().
pki_crl_name_matches()
static int pki_crl_name_matches (const char * name) static
Definition at line 68 of file pki_build.c.
References name.
Referenced by pki_load_crls_from_dir().
pki_load_crls()
static int pki_load_crls (X509_STORE * store, const char * path, ngx_log_t * log) static
Definition at line 154 of file pki_build.c.
References log, pki_load_crls_from_dir(), pki_load_crls_from_file(), and stat().
Referenced by brix_build_ca_store().
pki_load_crls_from_dir()
static int pki_load_crls_from_dir (X509_STORE * store, const char * path, ngx_log_t * log) static
Definition at line 123 of file pki_build.c.
References log, pki_crl_name_matches(), and pki_load_crls_from_dirent().
Referenced by pki_load_crls().
pki_load_crls_from_dirent()
static int pki_load_crls_from_dirent (X509_STORE * store, const char * dir_path, const char * name, ngx_log_t * log) static
Definition at line 94 of file pki_build.c.
References log, name, PATH_MAX, pki_load_crls_from_file(), and stat().
Referenced by pki_load_crls_from_dir().
pki_load_crls_from_file()
static int pki_load_crls_from_file (X509_STORE * store, const char * path, ngx_log_t * log) static
Definition at line 31 of file pki_build.c.
References log.
Referenced by pki_load_crls(), and pki_load_crls_from_dirent().
Variable Documentation
brix_ca_store_cache
brix_ca_store_cache_ent_t brix_ca_store_cache[16] static
Definition at line 273 of file pki_build.c.
Referenced by brix_ca_store_cache_get(), and brix_ca_store_cache_put().