nginx-xrootd: src/auth/crypto/pki_load.c File Reference
pki_load.c File Reference
#include "pki_check.h"
#include <dirent.h>
#include <fcntl.h>
#include <limits.h>
#include <openssl/pem.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
Functions
static ngx_flag_t brix_pki_crl_filename_matches (const char *name)
static ngx_int_t brix_pki_join_child_path (char *dst, size_t dst_size, const char *directory, const char *filename)
static ngx_flag_t brix_pki_is_regular_file (const char *path)
static ngx_uint_t brix_pki_load_certs_from_file (STACK_OF(X509) *certs, const char *path, ngx_log_t *log, ngx_flag_t log_open_error)
static ngx_uint_t brix_pki_load_crls_from_file (STACK_OF(X509_CRL) *crls, const char *path, ngx_log_t *log, ngx_flag_t log_open_error)
STACK_OF (X509)
STACK_OF (X509_CRL)
Function Documentation
brix_pki_crl_filename_matches()
static ngx_flag_t brix_pki_crl_filename_matches (const char * name) static
Definition at line 24 of file pki_load.c.
References name.
Referenced by STACK_OF().
brix_pki_is_regular_file()
static ngx_flag_t brix_pki_is_regular_file (const char * path) static
Definition at line 70 of file pki_load.c.
References stat().
Referenced by STACK_OF(), and STACK_OF().
brix_pki_join_child_path()
static ngx_int_t brix_pki_join_child_path (char * dst, size_t dst_size, const char * directory, const char * filename) static
Definition at line 53 of file pki_load.c.
Referenced by STACK_OF(), and STACK_OF().
brix_pki_load_certs_from_file()
static ngx_uint_t brix_pki_load_certs_from_file (STACK_OF(X509) * certs, const char * path, ngx_log_t * log, ngx_flag_t log_open_error) static
Definition at line 82 of file pki_load.c.
References log.
Referenced by STACK_OF().
brix_pki_load_crls_from_file()
static ngx_uint_t brix_pki_load_crls_from_file (STACK_OF(X509_CRL) * crls, const char * path, ngx_log_t * log, ngx_flag_t log_open_error) static
Definition at line 120 of file pki_load.c.
References log.
Referenced by STACK_OF().
STACK_OF() [1/2]
STACK_OF (X509)
Definition at line 154 of file pki_load.c.
References brix_pki_is_regular_file(), brix_pki_join_child_path(), brix_pki_load_certs_from_file(), log, PATH_MAX, STACK_OF(), and stat().
Referenced by STACK_OF(), and STACK_OF().
STACK_OF() [2/2]
STACK_OF (X509_CRL)
Definition at line 226 of file pki_load.c.
References brix_pki_crl_filename_matches(), brix_pki_is_regular_file(), brix_pki_join_child_path(), brix_pki_load_crls_from_file(), log, PATH_MAX, STACK_OF(), and stat().