nginx-xrootd: src/auth/crypto/pki_build.h File Reference
pki_build.h File Reference
#include <ngx_core.h>
#include <openssl/x509.h>
#include "auth/crypto/signing_policy.h"
#include "auth/crypto/store_policy.h"
Functions
X509_STORE * brix_build_ca_store (ngx_log_t *log, const char *cadir, const char *cafile, const char *crl_path, unsigned long extra_flags, int *crl_count_out, brix_sp_mode_t sp_mode, int crl_mode)
X509_STORE * brix_build_ca_store_cached (void *scope, ngx_log_t *log, const char *cadir, const char *cafile, const char *crl_path, unsigned long extra_flags, int *crl_count_out, brix_sp_mode_t sp_mode, int crl_mode)
Function Documentation
brix_build_ca_store()
X509_STORE * brix_build_ca_store (ngx_log_t * log, const char * cadir, const char * cafile, const char * crl_path, unsigned long extra_flags, int * crl_count_out, brix_sp_mode_t sp_mode, int crl_mode)
Definition at line 191 of file pki_build.c.
References brix_pki_sp_log(), brix_store_configure(), log, and pki_load_crls().
Referenced by brix_build_ca_store_cached(), sd_xroot_origin_build_ca_store(), and webdav_build_ca_store().
brix_build_ca_store_cached()
X509_STORE * brix_build_ca_store_cached (void * scope, ngx_log_t * log, const char * cadir, const char * cafile, const char * crl_path, unsigned long extra_flags, int * crl_count_out, brix_sp_mode_t sp_mode, int crl_mode)
Definition at line 366 of file pki_build.c.
References brix_build_ca_store(), brix_ca_store_cache_get(), brix_ca_store_cache_key(), brix_ca_store_cache_put(), key, log, and scope.
Referenced by brix_ftp_build_gsi(), and brix_rebuild_gsi_store().