nginx-xrootd: src/observability/pmark/pmark.h File Reference
pmark.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
Data Structures
struct brix_pmark_exp_rule_t
struct brix_pmark_act_rule_t
struct brix_pmark_conf_t
struct brix_pmark_dest_t
struct brix_pmark_exp_rule_r_t
struct brix_pmark_act_rule_r_t
struct brix_pmark_flow_t
struct brix_pmark_named_t
struct brix_pmark_exp_def_t
struct brix_pmark_flow_id_t
struct brix_pmark_sockstats_t
Macros
#define BRIX_PMARK_FLOW_MIN 65 /* smallest valid scitag.flow value */
#define BRIX_PMARK_FLOW_MAX 65535 /* 16-bit flow-id space */
#define BRIX_PMARK_ACT_BITS 6 /* low 6 bits = activity */
#define BRIX_PMARK_ACT_MASK 0x3F /* activity mask */
#define BRIX_PMARK_EXP_MIN 1
#define BRIX_PMARK_EXP_MAX 1023 /* 10-bit experiment space */
#define BRIX_PMARK_ACT_MIN 1
#define BRIX_PMARK_ACT_MAX 63
#define BRIX_PMARK_FF_PORT 10514 /* default firefly collector UDP port */
#define BRIX_PMARK_FL_MASK 0x000FFFFFu /* 20-bit field */
#define BRIX_PMARK_FL_ENTROPY_MASK 0x000C0103u /* E bits 0,1,8,18,19 */
Enumerations
enum { BRIX_PMARK_DOMAIN_ANY = 0 , BRIX_PMARK_DOMAIN_LOCAL = 1 , BRIX_PMARK_DOMAIN_REMOTE = 2 }
enum { BRIX_PMARK_ACT_READ = 0 , BRIX_PMARK_ACT_WRITE = 1 , BRIX_PMARK_ACT_TPC = 2 }
enum brix_pmark_exp_kind_t { BRIX_PMARK_EXP_DEFAULT = 0 , BRIX_PMARK_EXP_PATH , BRIX_PMARK_EXP_VO }
enum brix_pmark_act_kind_t { BRIX_PMARK_ACTR_DEFAULT = 0 , BRIX_PMARK_ACTR_ROLE , BRIX_PMARK_ACTR_USER }
Functions
void brix_pmark_conf_init (brix_pmark_conf_t *c)
char * brix_pmark_conf_merge (ngx_conf_t *cf, brix_pmark_conf_t *prev, brix_pmark_conf_t *conf)
char * brix_pmark_set_firefly_dest (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_pmark_set_map_experiment (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_pmark_set_map_activity (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_pmark_set_domain (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static ngx_uint_t brix_pmark_flowid (ngx_uint_t exp, ngx_uint_t act)
static ngx_int_t brix_pmark_flow_split (ngx_uint_t flow, ngx_uint_t *exp, ngx_uint_t *act)
static uint32_t brix_pmark_reverse9 (ngx_uint_t v)
static uint32_t brix_pmark_flowlabel_encode (ngx_uint_t exp, ngx_uint_t act)
ngx_int_t brix_pmark_parse_scitag (const char *cgi, ngx_uint_t *exp, ngx_uint_t *act)
static ngx_int_t brix_pmark_codes_valid (ngx_uint_t exp, ngx_uint_t act)
ngx_int_t brix_pmark_defsfile_load (const char *path, ngx_pool_t *pool, ngx_array_t **out, ngx_log_t *log)
ngx_uint_t brix_pmark_defs_exp_id (ngx_array_t *defs, ngx_str_t *name)
ngx_uint_t brix_pmark_defs_act_id (ngx_array_t *defs, ngx_uint_t exp_id, ngx_str_t *name)
ngx_int_t brix_pmark_runtime_ensure (brix_pmark_conf_t *pm, ngx_pool_t *pool, ngx_log_t *log)
ngx_int_t brix_pmark_map_codes (brix_pmark_conf_t *pm, const brix_pmark_flow_id_t *flow, ngx_uint_t *exp, ngx_uint_t *act)
ngx_int_t brix_pmark_sockstats (int fd, brix_pmark_sockstats_t *st)
void brix_pmark_iso8601_now (char *buf, size_t buflen)
ngx_int_t brix_pmark_endpoint (int fd, int which, char *ip, size_t iplen, int *port, char *afi)
brix_pmark_flow_t * brix_pmark_flow_begin (brix_pmark_conf_t *pm, ngx_pool_t *pool, ngx_connection_t *c, int is_write, const char *vo_csv, const char *user, const char *path, const char *cgi, ngx_log_t *log)
void brix_pmark_flow_end (brix_pmark_flow_t *flow, ngx_log_t *log)
void brix_pmark_flow_echo (brix_pmark_flow_t *flow, ngx_log_t *log)
void brix_pmark_firefly_oneshot (brix_pmark_conf_t *pm, int fd, ngx_uint_t exp, ngx_uint_t act, int peer_is_src, const char *app, ngx_log_t *log)
void brix_pmark_flow_cleanup (void *data)
void brix_pmark_http_mark (brix_pmark_conf_t *pm, ngx_pool_t *pool, ngx_connection_t *c, int is_write, const char *vo_csv, const char *user, const char *path, const char *cgi)
ngx_int_t brix_pmark_flowlabel_apply (ngx_connection_t *c, int fd, ngx_uint_t exp, ngx_uint_t act, ngx_log_t *log)
ngx_int_t brix_pmark_flowlabel_apply_addr (int fd, const struct sockaddr *dst, socklen_t dstlen, ngx_uint_t exp, ngx_uint_t act, ngx_log_t *log)
ngx_int_t brix_pmark_flowlabel_usable (ngx_log_t *log)
Macro Definition Documentation
BRIX_PMARK_ACT_BITS
#define BRIX_PMARK_ACT_BITS 6 /* low 6 bits = activity */
Definition at line 33 of file pmark.h.
BRIX_PMARK_ACT_MASK
#define BRIX_PMARK_ACT_MASK 0x3F /* activity mask */
Definition at line 34 of file pmark.h.
BRIX_PMARK_ACT_MAX
#define BRIX_PMARK_ACT_MAX 63
Definition at line 38 of file pmark.h.
BRIX_PMARK_ACT_MIN
#define BRIX_PMARK_ACT_MIN 1
Definition at line 37 of file pmark.h.
BRIX_PMARK_EXP_MAX
#define BRIX_PMARK_EXP_MAX 1023 /* 10-bit experiment space */
Definition at line 36 of file pmark.h.
BRIX_PMARK_EXP_MIN
#define BRIX_PMARK_EXP_MIN 1
Definition at line 35 of file pmark.h.
BRIX_PMARK_FF_PORT
#define BRIX_PMARK_FF_PORT 10514 /* default firefly collector UDP port */
Definition at line 40 of file pmark.h.
BRIX_PMARK_FL_ENTROPY_MASK
#define BRIX_PMARK_FL_ENTROPY_MASK 0x000C0103u /* E bits 0,1,8,18,19 */
Definition at line 62 of file pmark.h.
BRIX_PMARK_FL_MASK
#define BRIX_PMARK_FL_MASK 0x000FFFFFu /* 20-bit field */
Definition at line 61 of file pmark.h.
BRIX_PMARK_FLOW_MAX
#define BRIX_PMARK_FLOW_MAX 65535 /* 16-bit flow-id space */
Definition at line 32 of file pmark.h.
BRIX_PMARK_FLOW_MIN
#define BRIX_PMARK_FLOW_MIN 65 /* smallest valid scitag.flow value */
Definition at line 31 of file pmark.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BRIX_PMARK_DOMAIN_ANY
BRIX_PMARK_DOMAIN_LOCAL
BRIX_PMARK_DOMAIN_REMOTE
Definition at line 65 of file pmark.h.
anonymous enum
anonymous enum
Enumerator
BRIX_PMARK_ACT_READ
BRIX_PMARK_ACT_WRITE
BRIX_PMARK_ACT_TPC
Definition at line 73 of file pmark.h.
brix_pmark_act_kind_t
enum brix_pmark_act_kind_t
Enumerator
BRIX_PMARK_ACTR_DEFAULT
BRIX_PMARK_ACTR_ROLE
BRIX_PMARK_ACTR_USER
Definition at line 95 of file pmark.h.
brix_pmark_exp_kind_t
enum brix_pmark_exp_kind_t
Enumerator
BRIX_PMARK_EXP_DEFAULT
BRIX_PMARK_EXP_PATH
BRIX_PMARK_EXP_VO
Definition at line 82 of file pmark.h.
Function Documentation
brix_pmark_codes_valid()
static ngx_int_t brix_pmark_codes_valid (ngx_uint_t exp, ngx_uint_t act) inline static
Definition at line 265 of file pmark.h.
References BRIX_PMARK_ACT_MAX, BRIX_PMARK_ACT_MIN, BRIX_PMARK_EXP_MAX, and BRIX_PMARK_EXP_MIN.
Referenced by brix_pmark_map_codes(), and pmark_parse_flow_value().
brix_pmark_conf_init()
void brix_pmark_conf_init (brix_pmark_conf_t * c)
Definition at line 26 of file config.c.
References c.
Referenced by ngx_http_brix_shared_init().
brix_pmark_conf_merge()
char * brix_pmark_conf_merge (ngx_conf_t * cf, brix_pmark_conf_t * prev, brix_pmark_conf_t * conf)
Definition at line 40 of file config.c.
References brix_pmark_conf_t::act_rules, brix_pmark_conf_t::appname, BRIX_PMARK_DOMAIN_REMOTE, brix_pmark_conf_t::defsfile, brix_pmark_conf_t::domain, brix_pmark_conf_t::echo, brix_pmark_conf_t::enable, brix_pmark_conf_t::exp_rules, brix_pmark_conf_t::firefly, brix_pmark_conf_t::firefly_dest, brix_pmark_conf_t::firefly_origin, brix_pmark_conf_t::flowlabel, brix_pmark_conf_t::http_plain, and brix_pmark_conf_t::scitag_cgi.
Referenced by ngx_http_brix_shared_merge().
brix_pmark_defs_act_id()
ngx_uint_t brix_pmark_defs_act_id (ngx_array_t * defs, ngx_uint_t exp_id, ngx_str_t * name)
Definition at line 175 of file defsfile.c.
References brix_pmark_exp_def_t::activities, brix_pmark_named_t::id, and name.
Referenced by pmark_resolve_act_rules().
brix_pmark_defs_exp_id()
ngx_uint_t brix_pmark_defs_exp_id (ngx_array_t * defs, ngx_str_t * name)
Definition at line 154 of file defsfile.c.
References brix_pmark_exp_def_t::exp_id, and name.
Referenced by pmark_resolve_act_rules(), and pmark_resolve_exp_rules().
brix_pmark_defsfile_load()
ngx_int_t brix_pmark_defsfile_load (const char * path, ngx_pool_t * pool, ngx_array_t ** out, ngx_log_t * log)
Definition at line 51 of file defsfile.c.
References access(), brix_pmark_exp_def_t::activities, brix_pmark_exp_def_t::exp_id, brix_pmark_exp_def_t::exp_name, brix_pmark_named_t::id, log, brix_pmark_named_t::name, and pmark_dup_json_str().
Referenced by pmark_load_defs().
brix_pmark_endpoint()
ngx_int_t brix_pmark_endpoint (int fd, int which, char * ip, size_t iplen, int * port, char * afi)
Definition at line 109 of file sockstats.c.
References ngx_memcpy.
Referenced by brix_pmark_firefly_oneshot(), and brix_pmark_flow_begin().
brix_pmark_firefly_oneshot()
void brix_pmark_firefly_oneshot (brix_pmark_conf_t * pm, int fd, ngx_uint_t exp, ngx_uint_t act, int peer_is_src, const char * app, ngx_log_t * log)
Definition at line 283 of file firefly.c.
References brix_pmark_flow_t::act, brix_pmark_flow_t::afi, brix_pmark_flow_t::app, brix_pmark_endpoint(), brix_pmark_iso8601_now(), BRIX_PMARK_METRIC_INC, brix_pmark_flow_t::dst_ip, brix_pmark_flow_t::dst_port, brix_pmark_flow_t::exp, brix_pmark_flow_t::fd, brix_pmark_conf_t::firefly, brix_pmark_flow_t::firefly_started, brix_pmark_flow_t::is_put, log, ngx_memcpy, brix_pmark_flow_t::pm, pmark_emit(), brix_pmark_flow_t::src_ip, brix_pmark_flow_t::src_port, and brix_pmark_flow_t::start_iso.
Referenced by webdav_tpc_pmark_closesocket().
brix_pmark_flow_begin()
brix_pmark_flow_t * brix_pmark_flow_begin (brix_pmark_conf_t * pm, ngx_pool_t * pool, ngx_connection_t * c, int is_write, const char * vo_csv, const char * user, const char * path, const char * cgi, ngx_log_t * log)
Definition at line 168 of file firefly.c.
References brix_pmark_flow_t::act, brix_pmark_flow_t::afi, brix_pmark_flow_t::app, brix_pmark_conf_t::appname, BRIX_PCALLOC_OR_RETURN, brix_pmark_endpoint(), brix_pmark_flowlabel_apply(), brix_pmark_iso8601_now(), brix_pmark_map_codes(), BRIX_PMARK_METRIC_INC, brix_pmark_runtime_ensure(), c, brix_pmark_flow_t::dst_ip, brix_pmark_flow_t::dst_port, brix_pmark_conf_t::enable, brix_pmark_flow_t::exp, brix_pmark_flow_t::fd, brix_pmark_conf_t::firefly, brix_pmark_conf_t::firefly_origin, brix_pmark_flow_t::firefly_started, brix_pmark_conf_t::flowlabel, brix_pmark_flow_t::is_put, log, ngx_memcpy, brix_pmark_flow_t::peer_len, brix_pmark_flow_t::peer_ss, brix_pmark_flow_t::pm, pmark_emit(), brix_pmark_flow_t::src_ip, brix_pmark_flow_t::src_port, brix_pmark_flow_t::start_iso, brix_pmark_flow_id_t::vo_csv, and brix_pmark_flow_t::want_origin.
Referenced by brix_open_begin_pmark(), and brix_pmark_http_mark().
brix_pmark_flow_cleanup()
void brix_pmark_flow_cleanup (void * data)
Definition at line 276 of file firefly.c.
References brix_pmark_flow_end().
Referenced by brix_pmark_http_mark().
brix_pmark_flow_echo()
void brix_pmark_flow_echo (brix_pmark_flow_t * flow, ngx_log_t * log)
Definition at line 264 of file firefly.c.
References brix_pmark_conf_t::firefly, brix_pmark_flow_t::firefly_started, log, brix_pmark_flow_t::pm, and pmark_emit().
Referenced by brix_pmark_echo_timer().
brix_pmark_flow_end()
void brix_pmark_flow_end (brix_pmark_flow_t * flow, ngx_log_t * log)
Definition at line 251 of file firefly.c.
References BRIX_PMARK_METRIC_INC, brix_pmark_conf_t::firefly, brix_pmark_flow_t::firefly_started, log, brix_pmark_flow_t::pm, and pmark_emit().
Referenced by brix_disconnect_end_pmark(), and brix_pmark_flow_cleanup().
brix_pmark_flow_split()
static ngx_int_t brix_pmark_flow_split (ngx_uint_t flow, ngx_uint_t * exp, ngx_uint_t * act) inline static
Definition at line 214 of file pmark.h.
References BRIX_PMARK_ACT_BITS, BRIX_PMARK_ACT_MASK, and BRIX_PMARK_FLOW_MAX.
Referenced by pmark_parse_flow_value().
brix_pmark_flowid()
static ngx_uint_t brix_pmark_flowid (ngx_uint_t exp, ngx_uint_t act) inline static
Definition at line 205 of file pmark.h.
References BRIX_PMARK_ACT_BITS, and BRIX_PMARK_ACT_MASK.
brix_pmark_flowlabel_apply()
ngx_int_t brix_pmark_flowlabel_apply (ngx_connection_t * c, int fd, ngx_uint_t exp, ngx_uint_t act, ngx_log_t * log)
Definition at line 208 of file flowlabel.c.
References c, and log.
Referenced by brix_pmark_flow_begin().
brix_pmark_flowlabel_apply_addr()
ngx_int_t brix_pmark_flowlabel_apply_addr (int fd, const struct sockaddr * dst, socklen_t dstlen, ngx_uint_t exp, ngx_uint_t act, ngx_log_t * log)
Definition at line 216 of file flowlabel.c.
References log.
Referenced by tpc_connect(), and webdav_tpc_pmark_opensocket().
brix_pmark_flowlabel_encode()
static uint32_t brix_pmark_flowlabel_encode (ngx_uint_t exp, ngx_uint_t act) inline static
Definition at line 247 of file pmark.h.
References activity, BRIX_PMARK_ACT_MASK, BRIX_PMARK_FL_MASK, and brix_pmark_reverse9().
brix_pmark_flowlabel_usable()
ngx_int_t brix_pmark_flowlabel_usable (ngx_log_t * log)
Definition at line 201 of file flowlabel.c.
References log.
brix_pmark_http_mark()
void brix_pmark_http_mark (brix_pmark_conf_t * pm, ngx_pool_t * pool, ngx_connection_t * c, int is_write, const char * vo_csv, const char * user, const char * path, const char * cgi)
Definition at line 334 of file firefly.c.
References brix_pmark_flow_begin(), brix_pmark_flow_cleanup(), and c.
Referenced by s3_pmark_begin_if_enabled(), and webdav_dispatch_pmark().
brix_pmark_iso8601_now()
void brix_pmark_iso8601_now (char * buf, size_t buflen)
Definition at line 86 of file sockstats.c.
Referenced by brix_pmark_firefly_oneshot(), brix_pmark_flow_begin(), and pmark_build().
brix_pmark_map_codes()
ngx_int_t brix_pmark_map_codes (brix_pmark_conf_t * pm, const brix_pmark_flow_id_t * flow, ngx_uint_t * exp, ngx_uint_t * act)
Definition at line 437 of file mapping.c.
References brix_pmark_codes_valid(), brix_pmark_parse_scitag(), brix_pmark_flow_id_t::cgi, brix_pmark_flow_id_t::path, pmark_map_activity(), pmark_map_experiment(), brix_pmark_conf_t::scitag_cgi, brix_pmark_flow_id_t::user, and brix_pmark_flow_id_t::vo_csv.
Referenced by brix_pmark_flow_begin(), tpc_pull_resolve_pmark(), and webdav_tpc_pmark_attach().
brix_pmark_parse_scitag()
ngx_int_t brix_pmark_parse_scitag (const char * cgi, ngx_uint_t * exp, ngx_uint_t * act)
Definition at line 75 of file scitag.c.
References BRIX_PMARK_SCITAG_KEY, BRIX_PMARK_SCITAG_KEY_LEN, pmark_is_param_boundary(), and pmark_parse_flow_value().
Referenced by brix_pmark_map_codes().
brix_pmark_reverse9()
static uint32_t brix_pmark_reverse9 (ngx_uint_t v) inline static
Definition at line 227 of file pmark.h.
Referenced by brix_pmark_flowlabel_encode().
brix_pmark_runtime_ensure()
ngx_int_t brix_pmark_runtime_ensure (brix_pmark_conf_t * pm, ngx_pool_t * pool, ngx_log_t * log)
Definition at line 313 of file mapping.c.
References brix_pmark_conf_t::enable, log, pmark_load_defs(), pmark_resolve_act_rules(), pmark_resolve_dests(), pmark_resolve_exp_rules(), brix_pmark_conf_t::rt_ok, and brix_pmark_conf_t::rt_ready.
Referenced by brix_pmark_flow_begin(), tpc_pull_resolve_pmark(), and webdav_tpc_pmark_attach().
brix_pmark_set_domain()
char * brix_pmark_set_domain (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 102 of file config.c.
References BRIX_PMARK_DOMAIN_ANY, BRIX_PMARK_DOMAIN_LOCAL, BRIX_PMARK_DOMAIN_REMOTE, brix_pmark_conf_t::domain, and pmark_conf().
brix_pmark_set_firefly_dest()
char * brix_pmark_set_firefly_dest (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 74 of file config.c.
References brix_pmark_conf_t::firefly_dest, and pmark_conf().
brix_pmark_set_map_activity()
char * brix_pmark_set_map_activity (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 171 of file config.c.
References brix_pmark_act_rule_t::act_name, brix_pmark_conf_t::act_rules, BRIX_PMARK_ACTR_DEFAULT, BRIX_PMARK_ACTR_ROLE, BRIX_PMARK_ACTR_USER, brix_pmark_act_rule_t::exp_name, brix_pmark_act_rule_t::kind, brix_pmark_act_rule_t::match, and pmark_conf().
brix_pmark_set_map_experiment()
char * brix_pmark_set_map_experiment (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 126 of file config.c.
References BRIX_PMARK_EXP_DEFAULT, BRIX_PMARK_EXP_PATH, BRIX_PMARK_EXP_VO, brix_pmark_exp_rule_t::exp_name, brix_pmark_conf_t::exp_rules, brix_pmark_exp_rule_t::kind, brix_pmark_exp_rule_t::match, and pmark_conf().
brix_pmark_sockstats()
ngx_int_t brix_pmark_sockstats (int fd, brix_pmark_sockstats_t * st)
Definition at line 48 of file sockstats.c.
References brix_pmark_sockstats_t::bytes_recv, brix_pmark_sockstats_t::bytes_sent, ngx_memcpy, and brix_pmark_sockstats_t::rtt_us.
Referenced by pmark_build().