nginx-xrootd: client/lib/posix/posix_map.h File Reference
posix_map.h File Reference
#include "brix.h"
#include <sys/stat.h>
#include <stddef.h>
Functions
void brix_statinfo_to_stat (const brix_statinfo *si, int allow_symlink, struct stat *stbuf)
void brix_parse_qspace (const char *text, unsigned long long *total, unsigned long long *freeb)
int brix_fattr_listxattr_xlate (const char *raw, size_t rawlen, char *list, size_t size)
Function Documentation
brix_fattr_listxattr_xlate()
int brix_fattr_listxattr_xlate (const char * raw, size_t rawlen, char * list, size_t size)
Definition at line 52 of file posix_map.c.
Referenced by xfs_listxattr(), and xfs_listxattr().
brix_parse_qspace()
void brix_parse_qspace (const char * text, unsigned long long * total, unsigned long long * freeb)
Definition at line 44 of file posix_map.c.
References brix_qspace_parse().
Referenced by xfs_statfs(), and xfs_statfs().
brix_statinfo_to_stat()
void brix_statinfo_to_stat (const brix_statinfo * si, int allow_symlink, struct stat * stbuf)
Definition at line 16 of file posix_map.c.
References brix_stat_mode_from_flags(), brix_statinfo::flags, brix_statinfo::id, brix_statinfo::mtime, and brix_statinfo::size.
Referenced by xfs_fill_stat(), and xfs_fill_stat().