nginx-xrootd: src/protocols/s3/post_form_multipart.c File Reference
post_form_multipart.c File Reference
#include "s3_post_internal.h"
Data Structures
struct pf_part_headers_t
Functions
static ngx_int_t pf_parse_header_line (const char *line, pf_part_headers_t *hdr)
static ngx_int_t pf_parse_part_headers (u_char **pos, u_char *end, pf_part_headers_t *hdr)
static void pf_capture_file (s3_post_form_t *form, u_char *content, size_t content_len, const char *filename, const char *content_type)
static ngx_int_t pf_parse_one_part (u_char **pos, u_char *end, const char *delim, size_t delim_len, s3_post_form_t *form)
ngx_int_t s3_post_parse_form (ngx_http_request_t *r, u_char *body, size_t body_len, const char *boundary, s3_post_form_t *form)
Function Documentation
pf_capture_file()
static void pf_capture_file (s3_post_form_t * form, u_char * content, size_t content_len, const char * filename, const char * content_type) static
Definition at line 136 of file post_form_multipart.c.
References s3_post_form_t::content_type, s3_post_form_t::file_data, s3_post_form_t::file_len, s3_post_form_t::filename, and s3_post_form_t::have_file.
Referenced by pf_parse_one_part().
pf_parse_header_line()
static ngx_int_t pf_parse_header_line (const char * line, pf_part_headers_t * hdr) static
Definition at line 40 of file post_form_multipart.c.
References pf_part_headers_t::content_type, pf_part_headers_t::filename, pf_part_headers_t::name, s3_post_basename(), and s3_post_extract_param().
Referenced by pf_parse_part_headers().
pf_parse_one_part()
static ngx_int_t pf_parse_one_part (u_char ** pos, u_char * end, const char * delim, size_t delim_len, s3_post_form_t * form) static
Definition at line 162 of file post_form_multipart.c.
References pf_part_headers_t::content_type, pf_part_headers_t::filename, pf_part_headers_t::name, pf_capture_file(), pf_parse_part_headers(), s3_memmem(), and s3_post_store_field().
Referenced by s3_post_parse_form().
pf_parse_part_headers()
static ngx_int_t pf_parse_part_headers (u_char ** pos, u_char * end, pf_part_headers_t * hdr) static
Definition at line 90 of file post_form_multipart.c.
References ngx_memcpy, pf_parse_header_line(), and s3_memmem().
Referenced by pf_parse_one_part().
s3_post_parse_form()
ngx_int_t s3_post_parse_form (ngx_http_request_t * r, u_char * body, size_t body_len, const char * boundary, s3_post_form_t * form)
Definition at line 226 of file post_form_multipart.c.
References pf_parse_one_part().
Referenced by s3_post_object_body_handler_inner().