nginx-xrootd: src/protocols/webdav/postconfig.c File Reference
postconfig.c File Reference
#include "webdav.h"
#include "postconfig_internal.h"
#include "protocols/shared/proto_exclusive.h"
#include "protocols/shared/protocol.h"
#include "core/http/ktls.h"
#include "tpc/common/registry.h"
#include "net/mirror/http_mirror.h"
#include "net/ratelimit/ratelimit.h"
Functions
static ngx_int_t webdav_postconf_push_handler (ngx_http_core_main_conf_t *cmcf, ngx_uint_t phase, ngx_http_handler_pt handler)
static ngx_int_t webdav_postconf_install_handlers (ngx_http_core_main_conf_t *cmcf)
static ngx_int_t webdav_postconf_load_client_capath (ngx_conf_t *cf, ngx_http_core_srv_conf_t *cscf, ngx_http_ssl_srv_conf_t *sslcf, ngx_str_t *capath)
static ngx_int_t webdav_postconf_setup_ssl_ctx (ngx_conf_t *cf, ngx_http_core_srv_conf_t *cscf)
static void webdav_postconf_setup_thread_pool (ngx_conf_t *cf, ngx_http_core_srv_conf_t *cscf)
static ngx_int_t webdav_postconf_setup_servers (ngx_conf_t *cf, ngx_http_core_main_conf_t *cmcf)
ngx_int_t ngx_http_brix_webdav_postconfiguration (ngx_conf_t *cf)
Function Documentation
ngx_http_brix_webdav_postconfiguration()
ngx_int_t ngx_http_brix_webdav_postconfiguration (ngx_conf_t * cf)
Definition at line 366 of file postconfig.c.
References brix_http_proto_exclusive_check(), brix_protocol_register_all(), brix_tpc_registry_configure(), webdav_auth_init_ssl_indices(), webdav_postconf_install_handlers(), webdav_postconf_setup_proxy_capath(), and webdav_postconf_setup_servers().
webdav_postconf_install_handlers()
static ngx_int_t webdav_postconf_install_handlers (ngx_http_core_main_conf_t * cmcf) static
Definition at line 70 of file postconfig.c.
References brix_http_mirror_log_handler(), brix_http_mirror_precontent_handler(), brix_rl_http_access_handler(), brix_rl_http_log_handler(), ngx_http_brix_webdav_access_handler(), ngx_http_brix_webdav_handler(), webdav_introspect_access_handler(), and webdav_postconf_push_handler().
Referenced by ngx_http_brix_webdav_postconfiguration().
webdav_postconf_load_client_capath()
static ngx_int_t webdav_postconf_load_client_capath (ngx_conf_t * cf, ngx_http_core_srv_conf_t * cscf, ngx_http_ssl_srv_conf_t * sslcf, ngx_str_t * capath) static
Definition at line 164 of file postconfig.c.
Referenced by webdav_postconf_setup_ssl_ctx().
webdav_postconf_push_handler()
static ngx_int_t webdav_postconf_push_handler (ngx_http_core_main_conf_t * cmcf, ngx_uint_t phase, ngx_http_handler_pt handler) static
Definition at line 37 of file postconfig.c.
References handler.
Referenced by webdav_postconf_install_handlers().
webdav_postconf_setup_servers()
static ngx_int_t webdav_postconf_setup_servers (ngx_conf_t * cf, ngx_http_core_main_conf_t * cmcf) static
Definition at line 347 of file postconfig.c.
References s, webdav_postconf_setup_ssl_ctx(), and webdav_postconf_setup_thread_pool().
Referenced by ngx_http_brix_webdav_postconfiguration().
webdav_postconf_setup_ssl_ctx()
static ngx_int_t webdav_postconf_setup_ssl_ctx (ngx_conf_t * cf, ngx_http_core_srv_conf_t * cscf) static
Definition at line 230 of file postconfig.c.
References brix_http_ktls_enable_ctx(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::ktls, ngx_http_brix_webdav_module, ngx_http_brix_webdav_loc_conf_t::proxy_certs, ngx_http_brix_webdav_loc_conf_t::ssl_client_capath, and webdav_postconf_load_client_capath().
Referenced by webdav_postconf_setup_servers().
webdav_postconf_setup_thread_pool()
static void webdav_postconf_setup_thread_pool (ngx_conf_t * cf, ngx_http_core_srv_conf_t * cscf) static
Definition at line 299 of file postconfig.c.
References ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::enable, ngx_http_brix_webdav_module, ngx_http_brix_shared_conf_t::thread_pool, and ngx_http_brix_shared_conf_t::thread_pool_name.
Referenced by webdav_postconf_setup_servers().