nginx-xrootd: src/protocols/s3/post_response.c File Reference
post_response.c File Reference
#include "s3_post_internal.h"
Functions
ngx_int_t s3_post_send_empty (ngx_http_request_t *r, ngx_uint_t status)
ngx_int_t s3_post_send_created (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form, const char *etag)
ngx_int_t s3_post_send_success (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form, const char *etag)
Function Documentation
s3_post_send_created()
ngx_int_t s3_post_send_created (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form, const char * etag)
Definition at line 26 of file post_response.c.
References BRIX_PNALLOC_OR_RETURN, ngx_http_s3_loc_conf_t::bucket, host, s3_post_form_t::key, ngx_memcpy, S3_MAX_KEY, XML_APPEND, and XML_APPEND_ELEM.
Referenced by s3_post_send_success().
s3_post_send_empty()
ngx_int_t s3_post_send_empty (ngx_http_request_t * r, ngx_uint_t status)
Definition at line 10 of file post_response.c.
Referenced by s3_post_send_success().
s3_post_send_success()
ngx_int_t s3_post_send_success (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form, const char * etag)
Definition at line 97 of file post_response.c.
References brix_http_str_has_ctl(), s3_post_error(), s3_post_send_created(), s3_post_send_empty(), s3_set_header(), s3_post_form_t::success_redirect, and s3_post_form_t::success_status.
Referenced by s3_post_object_body_handler_inner().