nginx-xrootd: src/protocols/s3/post_policy_conditions.c File Reference
post_policy_conditions.c File Reference
#include "s3_post_internal.h"
Data Structures
struct s3_post_op_desc_t
Functions
int64_t s3_post_days_from_civil (int y, unsigned m, unsigned d)
ngx_int_t s3_post_parse_iso8601 (const char *s, time_t *out)
ngx_int_t s3_post_check_field_eq (const char *actual, const char *expected)
static ngx_int_t s3_post_cond_object (ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form, json_t *cond)
static ngx_int_t s3_post_cond_length_range (const s3_post_form_t *form, json_t *cond)
static ngx_int_t s3_post_cond_string_op (const s3_post_form_t *form, json_t *cond, const char *op)
static ngx_int_t s3_post_cond_length_range_adapter (const s3_post_form_t *form, json_t *cond, const char *op)
static ngx_int_t s3_post_cond_array (const s3_post_form_t *form, json_t *cond)
ngx_int_t s3_post_policy_condition (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form, json_t *cond)
ngx_int_t s3_post_validate_policy_json (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form, u_char *policy_json, size_t policy_len)
Variables
static const s3_post_op_desc_t s3_post_ops []
Function Documentation
s3_post_check_field_eq()
ngx_int_t s3_post_check_field_eq (const char * actual, const char * expected)
Definition at line 77 of file post_policy_conditions.c.
Referenced by s3_post_cond_object().
s3_post_cond_array()
static ngx_int_t s3_post_cond_array (const s3_post_form_t * form, json_t * cond) static
Definition at line 257 of file post_policy_conditions.c.
References s3_post_op_desc_t::eval, op, and s3_post_ops.
Referenced by s3_post_policy_condition().
s3_post_cond_length_range()
static ngx_int_t s3_post_cond_length_range (const s3_post_form_t * form, json_t * cond) static
Definition at line 143 of file post_policy_conditions.c.
References s3_post_form_t::file_len.
Referenced by s3_post_cond_length_range_adapter().
s3_post_cond_length_range_adapter()
static ngx_int_t s3_post_cond_length_range_adapter (const s3_post_form_t * form, json_t * cond, const char * op) static
Definition at line 228 of file post_policy_conditions.c.
References op, and s3_post_cond_length_range().
s3_post_cond_object()
static ngx_int_t s3_post_cond_object (ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form, json_t * cond) static
Definition at line 97 of file post_policy_conditions.c.
References ngx_http_s3_loc_conf_t::bucket, key, s3_post_check_field_eq(), and s3_post_field_value().
Referenced by s3_post_policy_condition().
s3_post_cond_string_op()
static ngx_int_t s3_post_cond_string_op (const s3_post_form_t * form, json_t * cond, const char * op) static
Definition at line 177 of file post_policy_conditions.c.
References op, and s3_post_field_value().
s3_post_days_from_civil()
int64_t s3_post_days_from_civil (int y, unsigned m, unsigned d)
Definition at line 23 of file post_policy_conditions.c.
Referenced by s3_post_parse_iso8601().
s3_post_parse_iso8601()
ngx_int_t s3_post_parse_iso8601 (const char * s, time_t * out)
Definition at line 49 of file post_policy_conditions.c.
References s, and s3_post_days_from_civil().
Referenced by s3_post_validate_policy_json().
s3_post_policy_condition()
ngx_int_t s3_post_policy_condition (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form, json_t * cond)
Definition at line 292 of file post_policy_conditions.c.
References s3_post_cond_array(), and s3_post_cond_object().
Referenced by s3_post_validate_policy_json().
s3_post_validate_policy_json()
ngx_int_t s3_post_validate_policy_json (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form, u_char * policy_json, size_t policy_len)
Definition at line 325 of file post_policy_conditions.c.
References s3_post_parse_iso8601(), and s3_post_policy_condition().
Referenced by s3_post_enforce_policy().
Variable Documentation
s3_post_ops
const s3_post_op_desc_t s3_post_ops[] static
Initial value:
= {
    { "eq",                   s3_post_cond_string_op },
    { "starts-with",          s3_post_cond_string_op },
    { "content-length-range", s3_post_cond_length_range_adapter },
}
Definition at line 241 of file post_policy_conditions.c.
Referenced by s3_post_cond_array().