nginx-xrootd: src/protocols/s3/post_form.c File Reference
post_form.c File Reference
#include "s3_post_internal.h"
Functions
const char * s3_post_field_value (const s3_post_form_t *form, const char *name)
ngx_int_t s3_post_store_field (s3_post_form_t *form, const char *name, const u_char *data, size_t len)
ngx_int_t s3_post_boundary (ngx_http_request_t *r, char *boundary, size_t boundary_sz)
ngx_int_t s3_post_extract_param (const char *line, const char *name, char *out, size_t outsz)
ngx_int_t s3_post_expand_filename (ngx_http_request_t *r, s3_post_form_t *form)
ngx_int_t s3_post_parse_form (ngx_http_request_t *r, u_char *body, size_t body_len, const char *boundary, s3_post_form_t *form)
Function Documentation
s3_post_boundary()
ngx_int_t s3_post_boundary (ngx_http_request_t * r, char * boundary, size_t boundary_sz)
Definition at line 129 of file post_form.c.
References brix_http_find_header().
Referenced by s3_post_object_body_handler_inner().
s3_post_expand_filename()
ngx_int_t s3_post_expand_filename (ngx_http_request_t * r, s3_post_form_t * form)
Definition at line 280 of file post_form.c.
References brix_http_str_has_ctl(), s3_post_form_t::filename, s3_post_form_t::key, and S3_MAX_KEY.
Referenced by s3_post_object_body_handler_inner().
s3_post_extract_param()
ngx_int_t s3_post_extract_param (const char * line, const char * name, char * out, size_t outsz)
Definition at line 214 of file post_form.c.
References name.
Referenced by s3_post_parse_form().
s3_post_field_value()
const char * s3_post_field_value (const s3_post_form_t * form, const char * name)
Definition at line 18 of file post_form.c.
References s3_post_form_t::content_type, s3_post_form_t::fields, s3_post_form_t::key, s3_post_field_t::name, name, s3_post_form_t::nfields, and s3_post_field_t::value.
Referenced by s3_post_policy_condition().
s3_post_parse_form()
ngx_int_t s3_post_parse_form (ngx_http_request_t * r, u_char * body, size_t body_len, const char * boundary, s3_post_form_t * form)
Definition at line 352 of file post_form.c.
References s3_post_form_t::content_type, s3_post_form_t::file_data, s3_post_form_t::file_len, s3_post_form_t::filename, s3_post_form_t::have_file, name, s3_memmem(), s3_post_basename(), s3_post_extract_param(), and s3_post_store_field().
Referenced by s3_post_object_body_handler_inner().
s3_post_store_field()
ngx_int_t s3_post_store_field (s3_post_form_t * form, const char * name, const u_char * data, size_t len)
Definition at line 56 of file post_form.c.
References s3_post_form_t::algorithm, s3_post_form_t::amz_date, s3_post_form_t::credential, s3_post_form_t::fields, s3_post_form_t::key, s3_post_field_t::name, name, s3_post_form_t::nfields, s3_post_form_t::policy, s3_post_copy_text(), S3_POST_MAX_FIELD, S3_POST_MAX_FIELDS, s3_post_form_t::signature, s3_post_form_t::success_redirect, s3_post_form_t::success_status, and s3_post_field_t::value.
Referenced by s3_post_parse_form().