nginx-xrootd: src/protocols/s3/post_object.c File Reference
post_object.c File Reference
#include "s3_post_internal.h"
Functions
ngx_int_t s3_post_error (ngx_http_request_t *r, ngx_uint_t status, const char *code, const char *message)
ngx_int_t s3_post_copy_text (const u_char *data, size_t len, char *dst, size_t dstsz)
u_char * s3_memmem (u_char *hay, size_t hay_len, const u_char *needle, size_t needle_len)
void s3_post_basename (char *s)
ngx_int_t s3_post_write_object (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form, const char *fs_path, char *etag, size_t etag_sz)
void s3_post_object_body_handler (ngx_http_request_t *r)
void s3_post_object_body_handler_inner (ngx_http_request_t *r)
Function Documentation
s3_memmem()
u_char * s3_memmem (u_char * hay, size_t hay_len, const u_char * needle, size_t needle_len)
Definition at line 54 of file post_object.c.
Referenced by pf_parse_one_part(), and pf_parse_part_headers().
s3_post_basename()
void s3_post_basename (char * s)
Definition at line 85 of file post_object.c.
References s.
Referenced by pf_parse_header_line().
s3_post_copy_text()
ngx_int_t s3_post_copy_text (const u_char * data, size_t len, char * dst, size_t dstsz)
Definition at line 25 of file post_object.c.
References ngx_memcpy.
Referenced by s3_post_store_field().
s3_post_error()
ngx_int_t s3_post_error (ngx_http_request_t * r, ngx_uint_t status, const char * code, const char * message)
Definition at line 8 of file post_object.c.
References code, and s3_send_xml_error().
Referenced by s3_post_enforce_policy(), s3_post_object_body_handler_inner(), s3_post_send_success(), s3_post_verify_fields(), s3_post_verify_scope(), and s3_post_verify_signature().
s3_post_object_body_handler()
void s3_post_object_body_handler (ngx_http_request_t * r)
Definition at line 219 of file post_object.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, and s3_post_object_body_handler_inner().
Referenced by s3_dispatch_empty_post().
s3_post_object_body_handler_inner()
void s3_post_object_body_handler_inner (ngx_http_request_t * r)
Definition at line 231 of file post_object.c.
References brix_http_body_read_all(), brix_http_map_errno(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METHOD_POST, BRIX_S3_METRIC_ADD, BRIX_S3_METRIC_INC, ngx_http_s3_loc_conf_t::common, s3_post_form_t::file_len, s3_post_form_t::have_file, s3_post_form_t::key, ngx_http_brix_s3_module, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, s3_metrics_finalize_request_method(), s3_post_boundary(), s3_post_error(), s3_post_expand_filename(), S3_POST_MAX_BODY, s3_post_parse_form(), s3_post_send_success(), s3_post_verify_policy(), s3_post_write_object(), and s3_resolve_key().
Referenced by s3_post_object_body_handler().
s3_post_write_object()
ngx_int_t s3_post_write_object (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form, const char * fs_path, char * etag, size_t etag_sz)
Definition at line 115 of file post_object.c.
References brix_vfs_mkdir(), brix_vfs_probe(), brix_vfs_pwrite_full(), brix_vfs_staged_abort(), brix_vfs_staged_commit(), brix_vfs_staged_fd(), brix_vfs_staged_open(), s3_post_form_t::file_data, s3_post_form_t::file_len, brix_vfs_stat_t::mtime, ngx_memcpy, PATH_MAX, s3_build_vfs_ctx(), s3_etag(), s3_set_header(), brix_vfs_stat_t::size, and stat().
Referenced by s3_post_object_body_handler_inner().