nginx-xrootd: src/core/config/postconfiguration.c File Reference
postconfiguration.c File Reference
#include "config.h"
#include "net/manager/redir_cache.h"
#include "net/manager/loc_cache.h"
#include "net/cms/reqid_map.h"
#include "fs/xfer/stage_waiter.h"
#include "core/negcache/negcache.h"
#include "auth/impersonate/lifecycle.h"
#include "core/aio/uring.h"
#include "core/compat/lifecycle_timing.h"
#include "postconfiguration_internal.h"
Functions
static const char * brix_auth_mode_name (ngx_uint_t auth)
static void brix_log_startup_summary (ngx_log_t *log, ngx_stream_brix_srv_conf_t *xcf)
static ngx_stream_brix_srv_conf_t * postconf_srv_conf (ngx_stream_core_srv_conf_t **cscfp, ngx_uint_t i)
static ngx_int_t postconf_prepare_servers (ngx_conf_t *cf, ngx_stream_core_main_conf_t *cmcf, ngx_stream_core_srv_conf_t **cscfp)
static ngx_int_t postconf_finalize_policies (ngx_conf_t *cf, ngx_stream_core_main_conf_t *cmcf, ngx_stream_core_srv_conf_t **cscfp)
static ngx_int_t postconf_session_registry (ngx_conf_t *cf, ngx_stream_core_main_conf_t *cmcf, ngx_stream_core_srv_conf_t **cscfp)
static ngx_int_t postconf_server_registry (ngx_conf_t *cf, ngx_stream_core_main_conf_t *cmcf, ngx_stream_core_srv_conf_t **cscfp)
static ngx_int_t postconf_redir_cache (ngx_conf_t *cf, ngx_stream_core_main_conf_t *cmcf, ngx_stream_core_srv_conf_t **cscfp)
static ngx_int_t postconf_stage_waiter (ngx_conf_t *cf, ngx_stream_core_main_conf_t *cmcf, ngx_stream_core_srv_conf_t **cscfp)
static ngx_int_t postconf_impersonation (ngx_conf_t *cf, ngx_stream_core_main_conf_t *cmcf, ngx_stream_core_srv_conf_t **cscfp)
static void postconf_log_summaries (ngx_conf_t *cf, ngx_stream_core_main_conf_t *cmcf, ngx_stream_core_srv_conf_t **cscfp)
static ngx_int_t postconf_shared_registries (ngx_conf_t *cf, ngx_stream_core_main_conf_t *cmcf, ngx_stream_core_srv_conf_t **cscfp)
ngx_int_t ngx_stream_brix_postconfiguration (ngx_conf_t *cf)
Function Documentation
brix_auth_mode_name()
static const char * brix_auth_mode_name (ngx_uint_t auth) static
Definition at line 14 of file postconfiguration.c.
References BRIX_AUTH_BOTH, BRIX_AUTH_GSI, BRIX_AUTH_HOST, BRIX_AUTH_KRB5, BRIX_AUTH_NONE, BRIX_AUTH_PWD, BRIX_AUTH_SSS, BRIX_AUTH_TOKEN, and BRIX_AUTH_UNIX.
Referenced by brix_log_startup_summary().
brix_log_startup_summary()
static void brix_log_startup_summary (ngx_log_t * log, ngx_stream_brix_srv_conf_t * xcf) static
Definition at line 33 of file postconfiguration.c.
References BRIX_AUTH_BOTH, BRIX_AUTH_GSI, brix_auth_mode_name(), BRIX_AUTH_NONE, BRIX_AUTH_PWD, and log.
Referenced by postconf_log_summaries().
ngx_stream_brix_postconfiguration()
ngx_int_t ngx_stream_brix_postconfiguration (ngx_conf_t * cf)
Definition at line 409 of file postconfiguration.c.
References brix_configure_dashboard(), brix_configure_metrics(), brix_configure_thread_pools(), brix_phase_mark(), brix_phase_timer_log(), brix_phase_timer_start(), brix_uring_validate_conf(), brix_voms_init(), postconf_finalize_policies(), postconf_impersonation(), postconf_log_summaries(), postconf_prepare_servers(), postconf_proxy_protocol_host_acl(), postconf_shared_registries(), and postconf_stage_waiter().
postconf_finalize_policies()
static ngx_int_t postconf_finalize_policies (ngx_conf_t * cf, ngx_stream_core_main_conf_t * cmcf, ngx_stream_core_srv_conf_t ** cscfp) static
Definition at line 149 of file postconfiguration.c.
References brix_config_finalize_policy(), and postconf_srv_conf().
Referenced by ngx_stream_brix_postconfiguration().
postconf_impersonation()
static ngx_int_t postconf_impersonation (ngx_conf_t * cf, ngx_stream_core_main_conf_t * cmcf, ngx_stream_core_srv_conf_t ** cscfp) static
Definition at line 340 of file postconfiguration.c.
References brix_imp_validate(), and postconf_srv_conf().
Referenced by ngx_stream_brix_postconfiguration().
postconf_log_summaries()
static void postconf_log_summaries (ngx_conf_t * cf, ngx_stream_core_main_conf_t * cmcf, ngx_stream_core_srv_conf_t ** cscfp) static
Definition at line 365 of file postconfiguration.c.
References brix_log_startup_summary(), and postconf_srv_conf().
Referenced by ngx_stream_brix_postconfiguration().
postconf_prepare_servers()
static ngx_int_t postconf_prepare_servers (ngx_conf_t * cf, ngx_stream_core_main_conf_t * cmcf, ngx_stream_core_srv_conf_t ** cscfp) static
Definition at line 117 of file postconfiguration.c.
References brix_config_prepare_server(), brix_configure_gsi(), brix_configure_krb5_auth(), brix_configure_sss_auth(), brix_configure_tls(), brix_configure_token_auth(), and postconf_srv_conf().
Referenced by ngx_stream_brix_postconfiguration().
postconf_redir_cache()
static ngx_int_t postconf_redir_cache (ngx_conf_t * cf, ngx_stream_core_main_conf_t * cmcf, ngx_stream_core_srv_conf_t ** cscfp) static
Definition at line 218 of file postconfiguration.c.
References brix_redir_cache_configure(), and postconf_srv_conf().
Referenced by postconf_shared_registries().
postconf_server_registry()
static ngx_int_t postconf_server_registry (ngx_conf_t * cf, ngx_stream_core_main_conf_t * cmcf, ngx_stream_core_srv_conf_t ** cscfp) static
Definition at line 197 of file postconfiguration.c.
References brix_srv_configure_registry(), and postconf_srv_conf().
Referenced by postconf_shared_registries().
postconf_session_registry()
static ngx_int_t postconf_session_registry (ngx_conf_t * cf, ngx_stream_core_main_conf_t * cmcf, ngx_stream_core_srv_conf_t ** cscfp) static
Definition at line 173 of file postconfiguration.c.
References brix_configure_session_registry(), and postconf_srv_conf().
Referenced by postconf_shared_registries().
postconf_shared_registries()
static ngx_int_t postconf_shared_registries (ngx_conf_t * cf, ngx_stream_core_main_conf_t * cmcf, ngx_stream_core_srv_conf_t ** cscfp) static
Definition at line 383 of file postconfiguration.c.
References brix_cms_reqid_map_configure(), brix_loc_cache_configure(), brix_pending_configure(), brix_tpc_key_configure_registry(), brix_tpc_registry_configure(), postconf_redir_cache(), postconf_server_registry(), and postconf_session_registry().
Referenced by ngx_stream_brix_postconfiguration().
postconf_srv_conf()
static ngx_stream_brix_srv_conf_t * postconf_srv_conf (ngx_stream_core_srv_conf_t ** cscfp, ngx_uint_t i) static
Definition at line 106 of file postconfiguration.c.
References ngx_stream_brix_module.
Referenced by postconf_finalize_policies(), postconf_impersonation(), postconf_log_summaries(), postconf_prepare_servers(), postconf_redir_cache(), postconf_server_registry(), postconf_session_registry(), and postconf_stage_waiter().
postconf_stage_waiter()
static ngx_int_t postconf_stage_waiter (ngx_conf_t * cf, ngx_stream_core_main_conf_t * cmcf, ngx_stream_core_srv_conf_t ** cscfp) static
Definition at line 252 of file postconfiguration.c.
References brix_negcache_configure(), brix_stage_waiter_configure(), and postconf_srv_conf().
Referenced by ngx_stream_brix_postconfiguration().