nginx-xrootd: src/protocols/webdav/postconfig_proxy_capath.c File Reference
postconfig_proxy_capath.c File Reference
#include "webdav.h"
#include "postconfig_internal.h"
Functions
static ngx_int_t webdav_postconf_proxy_capath_apply (ngx_conf_t *cf, void **loc_conf, ngx_str_t *name)
static ngx_int_t webdav_postconf_proxy_capath_location (ngx_conf_t *cf, ngx_http_core_loc_conf_t *clcf)
static ngx_int_t webdav_postconf_proxy_capath_loc_array (ngx_conf_t *cf, ngx_http_core_loc_conf_t **arr)
static ngx_int_t webdav_postconf_proxy_capath_tree (ngx_conf_t *cf, ngx_http_location_tree_node_t *node)
ngx_int_t webdav_postconf_setup_proxy_capath (ngx_conf_t *cf, ngx_http_core_main_conf_t *cmcf)
Variables
ngx_module_t ngx_http_proxy_module
Function Documentation
webdav_postconf_proxy_capath_apply()
static ngx_int_t webdav_postconf_proxy_capath_apply (ngx_conf_t * cf, void ** loc_conf, ngx_str_t * name) static
Definition at line 58 of file postconfig_proxy_capath.c.
References name, ngx_http_brix_webdav_module, ngx_http_proxy_module, and ngx_http_brix_webdav_loc_conf_t::proxy_ssl_capath.
Referenced by webdav_postconf_proxy_capath_location().
webdav_postconf_proxy_capath_loc_array()
static ngx_int_t webdav_postconf_proxy_capath_loc_array (ngx_conf_t * cf, ngx_http_core_loc_conf_t ** arr) static
Definition at line 108 of file postconfig_proxy_capath.c.
References webdav_postconf_proxy_capath_location().
Referenced by webdav_postconf_proxy_capath_location(), and webdav_postconf_setup_proxy_capath().
webdav_postconf_proxy_capath_location()
static ngx_int_t webdav_postconf_proxy_capath_location (ngx_conf_t * cf, ngx_http_core_loc_conf_t * clcf) static
Definition at line 156 of file postconfig_proxy_capath.c.
References webdav_postconf_proxy_capath_apply(), webdav_postconf_proxy_capath_loc_array(), and webdav_postconf_proxy_capath_tree().
Referenced by webdav_postconf_proxy_capath_loc_array(), and webdav_postconf_proxy_capath_tree().
webdav_postconf_proxy_capath_tree()
static ngx_int_t webdav_postconf_proxy_capath_tree (ngx_conf_t * cf, ngx_http_location_tree_node_t * node) static
Definition at line 126 of file postconfig_proxy_capath.c.
References webdav_postconf_proxy_capath_location(), and webdav_postconf_proxy_capath_tree().
Referenced by webdav_postconf_proxy_capath_location(), webdav_postconf_proxy_capath_tree(), and webdav_postconf_setup_proxy_capath().
webdav_postconf_setup_proxy_capath()
ngx_int_t webdav_postconf_setup_proxy_capath (ngx_conf_t * cf, ngx_http_core_main_conf_t * cmcf)
Definition at line 189 of file postconfig_proxy_capath.c.
References s, webdav_postconf_proxy_capath_loc_array(), and webdav_postconf_proxy_capath_tree().
Referenced by ngx_http_brix_webdav_postconfiguration().
Variable Documentation
ngx_http_proxy_module
ngx_module_t ngx_http_proxy_module extern
Referenced by webdav_postconf_proxy_capath_apply().