nginx-xrootd: src/protocols/s3/post_policy.c File Reference
post_policy.c File Reference
#include "s3_post_internal.h"
Data Structures
struct s3_post_op_desc_t
struct s3_post_scope_t
Functions
int64_t s3_post_days_from_civil (int y, unsigned m, unsigned d)
ngx_int_t s3_post_parse_iso8601 (const char *s, time_t *out)
ngx_int_t s3_post_check_field_eq (const char *actual, const char *expected)
static ngx_int_t s3_post_cond_object (ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form, json_t *cond)
static ngx_int_t s3_post_cond_length_range (const s3_post_form_t *form, json_t *cond)
static ngx_int_t s3_post_cond_string_op (const s3_post_form_t *form, json_t *cond, const char *op)
static ngx_int_t s3_post_cond_length_range_adapter (const s3_post_form_t *form, json_t *cond, const char *op)
static ngx_int_t s3_post_cond_array (const s3_post_form_t *form, json_t *cond)
ngx_int_t s3_post_policy_condition (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form, json_t *cond)
ngx_int_t s3_post_validate_policy_json (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form, u_char *policy_json, size_t policy_len)
ngx_int_t s3_post_parse_credential (const char *credential, char *date, size_t date_sz, char *region, size_t region_sz, const char **akid)
static ngx_int_t s3_post_verify_fields (ngx_http_request_t *r, const s3_post_form_t *form, s3_post_scope_t *sc)
static ngx_int_t s3_post_verify_scope (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form, s3_post_scope_t *sc)
static ngx_int_t s3_post_verify_signature (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form, s3_post_scope_t *sc)
static ngx_int_t s3_post_enforce_policy (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form)
ngx_int_t s3_post_verify_policy (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form)
Variables
static const s3_post_op_desc_t s3_post_ops []
Function Documentation
s3_post_check_field_eq()
ngx_int_t s3_post_check_field_eq (const char * actual, const char * expected)
Definition at line 76 of file post_policy.c.
Referenced by s3_post_cond_object().
s3_post_cond_array()
static ngx_int_t s3_post_cond_array (const s3_post_form_t * form, json_t * cond) static
Definition at line 256 of file post_policy.c.
References s3_post_op_desc_t::eval, op, and s3_post_ops.
Referenced by s3_post_policy_condition().
s3_post_cond_length_range()
static ngx_int_t s3_post_cond_length_range (const s3_post_form_t * form, json_t * cond) static
Definition at line 142 of file post_policy.c.
References s3_post_form_t::file_len.
Referenced by s3_post_cond_length_range_adapter().
s3_post_cond_length_range_adapter()
static ngx_int_t s3_post_cond_length_range_adapter (const s3_post_form_t * form, json_t * cond, const char * op) static
Definition at line 227 of file post_policy.c.
References op, and s3_post_cond_length_range().
s3_post_cond_object()
static ngx_int_t s3_post_cond_object (ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form, json_t * cond) static
Definition at line 96 of file post_policy.c.
References ngx_http_s3_loc_conf_t::bucket, key, s3_post_check_field_eq(), and s3_post_field_value().
Referenced by s3_post_policy_condition().
s3_post_cond_string_op()
static ngx_int_t s3_post_cond_string_op (const s3_post_form_t * form, json_t * cond, const char * op) static
Definition at line 176 of file post_policy.c.
References op, and s3_post_field_value().
s3_post_days_from_civil()
int64_t s3_post_days_from_civil (int y, unsigned m, unsigned d)
Definition at line 22 of file post_policy.c.
Referenced by s3_post_parse_iso8601().
s3_post_enforce_policy()
static ngx_int_t s3_post_enforce_policy (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form) static
Definition at line 583 of file post_policy.c.
References ngx_pnalloc(), s3_post_form_t::policy, s3_post_error(), and s3_post_validate_policy_json().
Referenced by s3_post_verify_policy().
s3_post_parse_credential()
ngx_int_t s3_post_parse_credential (const char * credential, char * date, size_t date_sz, char * region, size_t region_sz, const char ** akid)
Definition at line 390 of file post_policy.c.
References date, ngx_memcpy, and region.
Referenced by s3_post_verify_fields().
s3_post_parse_iso8601()
ngx_int_t s3_post_parse_iso8601 (const char * s, time_t * out)
Definition at line 48 of file post_policy.c.
References s, and s3_post_days_from_civil().
Referenced by s3_post_validate_policy_json().
s3_post_policy_condition()
ngx_int_t s3_post_policy_condition (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form, json_t * cond)
Definition at line 291 of file post_policy.c.
References s3_post_cond_array(), and s3_post_cond_object().
Referenced by s3_post_validate_policy_json().
s3_post_validate_policy_json()
ngx_int_t s3_post_validate_policy_json (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form, u_char * policy_json, size_t policy_len)
Definition at line 324 of file post_policy.c.
References s3_post_parse_iso8601(), and s3_post_policy_condition().
Referenced by s3_post_enforce_policy().
s3_post_verify_fields()
static ngx_int_t s3_post_verify_fields (ngx_http_request_t * r, const s3_post_form_t * form, s3_post_scope_t * sc) static
Definition at line 460 of file post_policy.c.
References s3_post_scope_t::akid, s3_post_form_t::algorithm, s3_post_form_t::amz_date, s3_post_form_t::credential, s3_post_scope_t::date, s3_post_form_t::policy, s3_post_scope_t::region, s3_post_error(), s3_post_parse_credential(), s3_post_form_t::signature, and s3_post_scope_t::status.
Referenced by s3_post_verify_policy().
s3_post_verify_policy()
ngx_int_t s3_post_verify_policy (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form)
Definition at line 634 of file post_policy.c.
References ngx_http_s3_loc_conf_t::access_key, s3_post_enforce_policy(), s3_post_verify_fields(), s3_post_verify_scope(), s3_post_verify_signature(), and s3_post_scope_t::status.
Referenced by s3_post_object_body_handler_inner().
s3_post_verify_scope()
static ngx_int_t s3_post_verify_scope (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form, s3_post_scope_t * sc) static
Definition at line 500 of file post_policy.c.
References ngx_http_s3_loc_conf_t::access_key, s3_post_scope_t::akid, s3_post_form_t::amz_date, s3_post_form_t::credential, s3_post_scope_t::date, s3_post_scope_t::region, ngx_http_s3_loc_conf_t::region, s3_post_error(), and s3_post_scope_t::status.
Referenced by s3_post_verify_policy().
s3_post_verify_signature()
static ngx_int_t s3_post_verify_signature (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form, s3_post_scope_t * sc) static
Definition at line 544 of file post_policy.c.
References brix_hex_encode(), brix_hmac_sha256(), s3_post_scope_t::date, s3_post_form_t::policy, s3_post_scope_t::region, s3_post_error(), s3_sigv4_derive_signing_key_cached(), ngx_http_s3_loc_conf_t::secret_key, s3_post_form_t::signature, and s3_post_scope_t::status.
Referenced by s3_post_verify_policy().
Variable Documentation
s3_post_ops
const s3_post_op_desc_t s3_post_ops[] static
Initial value:
= {
    { "eq",                   s3_post_cond_string_op },
    { "starts-with",          s3_post_cond_string_op },
    { "content-length-range", s3_post_cond_length_range_adapter },
}
Definition at line 240 of file post_policy.c.
Referenced by s3_post_cond_array().