nginx-xrootd: src/protocols/root/read/prefetch.c File Reference
prefetch.c File Reference
#include "prefetch.h"
#include <string.h>
Functions
void brix_prefetch_fd_range (ngx_log_t *log, int fd, off_t offset, size_t length)
static ngx_flag_t brix_prefetch_read_end (brix_file_t *file, off_t offset, size_t length, off_t file_size, off_t *end_out)
static void brix_prefetch_seq_window (brix_file_t *file, off_t offset, off_t end, off_t file_size, off_t *hint_start, off_t *hint_end)
void brix_prefetch_read_file (ngx_log_t *log, brix_file_t *file, off_t offset, size_t length, off_t file_size)
void brix_prefetch_flush (ngx_log_t *log, int fd, off_t range_start, off_t range_end)
void brix_prefetch_readv_segments (brix_ctx_t *ctx, ngx_connection_t *c, readahead_list *segments, size_t segment_count, size_t readv_seg_max)
Function Documentation
brix_prefetch_fd_range()
void brix_prefetch_fd_range (ngx_log_t * log, int fd, off_t offset, size_t length)
Definition at line 11 of file prefetch.c.
References BRIX_READ_PREFETCH_MIN, and log.
Referenced by brix_prefetch_flush(), and brix_prefetch_read_file().
brix_prefetch_flush()
void brix_prefetch_flush (ngx_log_t * log, int fd, off_t range_start, off_t range_end)
Definition at line 169 of file prefetch.c.
References brix_prefetch_fd_range(), and log.
Referenced by brix_prefetch_readv_segments().
brix_prefetch_read_end()
static ngx_flag_t brix_prefetch_read_end (brix_file_t * file, off_t offset, size_t length, off_t file_size, off_t * end_out) static
Definition at line 52 of file prefetch.c.
References BRIX_READ_PREFETCH_MIN, and brix_file_t::fd.
Referenced by brix_prefetch_read_file().
brix_prefetch_read_file()
void brix_prefetch_read_file (ngx_log_t * log, brix_file_t * file, off_t offset, size_t length, off_t file_size)
Definition at line 136 of file prefetch.c.
References brix_prefetch_fd_range(), brix_prefetch_read_end(), brix_prefetch_seq_window(), brix_file_t::fd, log, brix_file_t::read_ahead_end, and brix_file_t::read_last_end.
Referenced by brix_read_compressed(), brix_read_serve_sendfile(), read_prefetch_buffered(), and read_serve_windowed().
brix_prefetch_readv_segments()
void brix_prefetch_readv_segments (brix_ctx_t * ctx, ngx_connection_t * c, readahead_list * segments, size_t segment_count, size_t readv_seg_max)
Definition at line 180 of file prefetch.c.
References BRIX_MAX_FILES, brix_prefetch_flush(), BRIX_READV_PREFETCH_GAP, BRIX_READV_PREFETCH_MAX, c, brix_file_t::fd, readahead_list::fhandle, brix_ctx_t::files, readahead_list::offset, and readahead_list::rlen.
Referenced by brix_handle_readv().
brix_prefetch_seq_window()
static void brix_prefetch_seq_window (brix_file_t * file, off_t offset, off_t end, off_t file_size, off_t * hint_start, off_t * hint_end) static
Definition at line 101 of file prefetch.c.
References BRIX_READ_PREFETCH_LOW_WATER, BRIX_READ_PREFETCH_WINDOW, and brix_file_t::read_ahead_end.
Referenced by brix_prefetch_read_file().