nginx-xrootd: src/protocols/root/read/prefetch.h File Reference
prefetch.h File Reference
#include "core/ngx_brix_module.h"
Macros
#define BRIX_READ_PREFETCH_MIN (1024 * 1024)
#define BRIX_READ_PREFETCH_WINDOW (32 * 1024 * 1024)
#define BRIX_READ_PREFETCH_LOW_WATER (8 * 1024 * 1024)
#define BRIX_READV_PREFETCH_GAP (128 * 1024)
#define BRIX_READV_PREFETCH_MAX (16 * 1024 * 1024)
Functions
void brix_prefetch_fd_range (ngx_log_t *log, int fd, off_t offset, size_t length)
void brix_prefetch_read_file (ngx_log_t *log, brix_file_t *file, off_t offset, size_t length, off_t file_size)
void brix_prefetch_flush (ngx_log_t *log, int fd, off_t range_start, off_t range_end)
void brix_prefetch_readv_segments (brix_ctx_t *ctx, ngx_connection_t *c, readahead_list *segments, size_t segment_count, size_t readv_seg_max)
Macro Definition Documentation
BRIX_READ_PREFETCH_LOW_WATER
#define BRIX_READ_PREFETCH_LOW_WATER (8 * 1024 * 1024)
Definition at line 30 of file prefetch.h.
BRIX_READ_PREFETCH_MIN
#define BRIX_READ_PREFETCH_MIN (1024 * 1024)
Definition at line 28 of file prefetch.h.
BRIX_READ_PREFETCH_WINDOW
#define BRIX_READ_PREFETCH_WINDOW (32 * 1024 * 1024)
Definition at line 29 of file prefetch.h.
BRIX_READV_PREFETCH_GAP
#define BRIX_READV_PREFETCH_GAP (128 * 1024)
Definition at line 31 of file prefetch.h.
BRIX_READV_PREFETCH_MAX
#define BRIX_READV_PREFETCH_MAX (16 * 1024 * 1024)
Definition at line 32 of file prefetch.h.
Function Documentation
brix_prefetch_fd_range()
void brix_prefetch_fd_range (ngx_log_t * log, int fd, off_t offset, size_t length)
Definition at line 11 of file prefetch.c.
References BRIX_READ_PREFETCH_MIN, and log.
Referenced by brix_prefetch_flush(), and brix_prefetch_read_file().
brix_prefetch_flush()
void brix_prefetch_flush (ngx_log_t * log, int fd, off_t range_start, off_t range_end)
Definition at line 105 of file prefetch.c.
References brix_prefetch_fd_range(), and log.
Referenced by brix_prefetch_readv_segments().
brix_prefetch_read_file()
void brix_prefetch_read_file (ngx_log_t * log, brix_file_t * file, off_t offset, size_t length, off_t file_size)
Definition at line 36 of file prefetch.c.
References brix_prefetch_fd_range(), BRIX_READ_PREFETCH_LOW_WATER, BRIX_READ_PREFETCH_MIN, BRIX_READ_PREFETCH_WINDOW, brix_file_t::fd, log, brix_file_t::read_ahead_end, and brix_file_t::read_last_end.
Referenced by brix_handle_read(), brix_read_compressed(), and brix_read_serve_sendfile().
brix_prefetch_readv_segments()
void brix_prefetch_readv_segments (brix_ctx_t * ctx, ngx_connection_t * c, readahead_list * segments, size_t segment_count, size_t readv_seg_max)
Definition at line 116 of file prefetch.c.
References BRIX_MAX_FILES, brix_prefetch_flush(), BRIX_READV_PREFETCH_GAP, BRIX_READV_PREFETCH_MAX, c, brix_file_t::fd, readahead_list::fhandle, brix_ctx_t::files, readahead_list::offset, and readahead_list::rlen.
Referenced by brix_handle_readv().