nginx-xrootd: src/protocols/root/query/prepare.c File Reference
prepare.c File Reference
#include "query_internal.h"
#include "prepare_internal.h"
#include "fs/path/beneath.h"
#include "fs/xfer/stage_request_registry.h"
#include <errno.h>
#include <sys/stat.h>
#include <time.h>
#include "core/compat/alloc_guard.h"
Data Structures
struct prepare_scan_t
Macros
#define BRIX_PREPARE_OWNER_KEY_MAX 64
Functions
static const char * brix_prepare_owner_key (brix_ctx_t *ctx, char *anon_key, size_t anon_key_sz)
ngx_int_t brix_prepare_send_fail (brix_ctx_t *ctx, ngx_connection_t *c, const char *path, uint16_t errcode, const char *errmsg)
static ngx_int_t brix_prepare_handle_cancel (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
static ngx_int_t prepare_alloc_stage_arrays (ngx_connection_t *c, prepare_scan_t *sc, size_t dlen)
static void prepare_enqueue_resolved (brix_ctx_t *ctx, ngx_connection_t *c, prepare_scan_t *sc, char *out_resolved)
static ngx_int_t prepare_scan_paths (brix_ctx_t *ctx, ngx_connection_t *c, prepare_scan_t *sc)
static ngx_int_t prepare_emit_stage (brix_ctx_t *ctx, ngx_connection_t *c, prepare_scan_t *sc)
static ngx_int_t prepare_dispatch_special (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const xrdw_prepare_req_t *req, uint16_t optionx)
ngx_int_t brix_handle_prepare (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Macro Definition Documentation
BRIX_PREPARE_OWNER_KEY_MAX
#define BRIX_PREPARE_OWNER_KEY_MAX 64
Definition at line 11 of file prepare.c.
Function Documentation
brix_handle_prepare()
ngx_int_t brix_handle_prepare (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 446 of file prepare.c.
References brix_log_access(), brix_prepare_send_fail(), brix_send_ok(), brix_stage_registry_singleton(), BRIX_STAGE_REQID_LEN, c, prepare_scan_t::collect_stage, prepare_scan_t::conf, brix_ctx_recv_t::cur_dlen, prepare_scan_t::do_enqueue, prepare_scan_t::group_reqid, brix_ctx_recv_t::hdr_buf, kXR_ArgMissing, kXR_coloc, kXR_ok, kXR_stage, prepare_scan_t::missing, prepare_scan_t::need_resolved, xrdw_prepare_req_t::options, prepare_scan_t::options, xrdw_prepare_req_t::optionX, prepare_scan_t::paths, brix_ctx_recv_t::payload, prepare_alloc_stage_arrays(), prepare_dispatch_special(), prepare_emit_stage(), prepare_scan_paths(), brix_ctx_t::recv, and xrdw_prepare_req_unpack().
Referenced by brix_dispatch_read_opcode().
brix_prepare_handle_cancel()
static ngx_int_t brix_prepare_handle_cancel (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf) static
Definition at line 93 of file prepare.c.
References brix_log_access(), brix_prepare_owner_key(), BRIX_PREPARE_OWNER_KEY_MAX, brix_prepare_send_fail(), brix_send_ok(), brix_stage_registry_singleton(), BRIX_STAGE_REQID_LEN, brix_stage_request_delete(), brix_stage_request_owner_check(), c, brix_ctx_recv_t::cur_dlen, kXR_ArgMissing, kXR_NotAuthorized, kXR_ok, ngx_memcpy, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by prepare_dispatch_special().
brix_prepare_owner_key()
static const char * brix_prepare_owner_key (brix_ctx_t * ctx, char * anon_key, size_t anon_key_sz) static
Definition at line 45 of file prepare.c.
References brix_identity_dn_cstr(), hex(), brix_ctx_t::identity, brix_ctx_t::login, ngx_memcpy, and brix_ctx_login_t::sessid.
Referenced by brix_prepare_handle_cancel(), and prepare_enqueue_resolved().
brix_prepare_send_fail()
ngx_int_t brix_prepare_send_fail (brix_ctx_t * ctx, ngx_connection_t * c, const char * path, uint16_t errcode, const char * errmsg)
Definition at line 78 of file prepare.c.
References brix_log_access(), brix_send_error(), and c.
Referenced by brix_handle_prepare(), brix_prepare_check_fail(), brix_prepare_handle_cancel(), prepare_dispatch_special(), and qprep_resolve_src().
prepare_alloc_stage_arrays()
static ngx_int_t prepare_alloc_stage_arrays (ngx_connection_t * c, prepare_scan_t * sc, size_t dlen) static
Definition at line 165 of file prepare.c.
References BRIX_PREPARE_CMD_MAX_PATHS, c, prepare_scan_t::need_resolved, PATH_MAX, prepare_scan_t::stage_bufs, prepare_scan_t::stage_max, and prepare_scan_t::stage_paths.
Referenced by brix_handle_prepare().
prepare_dispatch_special()
static ngx_int_t prepare_dispatch_special (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const xrdw_prepare_req_t * req, uint16_t optionx) static
Definition at line 406 of file prepare.c.
References brix_log_access(), brix_prepare_handle_cancel(), brix_prepare_send_fail(), brix_send_ok(), brix_stage_registry_singleton(), c, kXR_cancel, kXR_evict, kXR_fsReadOnly, kXR_ok, kXR_wmode, and xrdw_prepare_req_t::options.
Referenced by brix_handle_prepare().
prepare_emit_stage()
static ngx_int_t prepare_emit_stage (brix_ctx_t * ctx, ngx_connection_t * c, prepare_scan_t * sc) static
Definition at line 305 of file prepare.c.
References brix_attn_asyncms_frame_len(), brix_build_attn_asyncms_frame(), brix_build_resp_hdr(), BRIX_PALLOC_OR_RETURN, brix_prepare_invoke_command(), brix_queue_response(), brix_send_ok(), c, prepare_scan_t::collect_stage, prepare_scan_t::conf, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_streamid, prepare_scan_t::do_enqueue, prepare_scan_t::group_reqid, kXR_coloc, kXR_notify, kXR_ok, prepare_scan_t::missing, ngx_memcpy, prepare_scan_t::options, brix_ctx_prepare_t::paths, brix_ctx_prepare_t::paths_len, brix_ctx_recv_t::payload, brix_ctx_t::prepare, brix_ctx_t::recv, brix_ctx_prepare_t::reqid, prepare_scan_t::stage_count, prepare_scan_t::stage_paths, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_handle_prepare().
prepare_enqueue_resolved()
static void prepare_enqueue_resolved (brix_ctx_t * ctx, ngx_connection_t * c, prepare_scan_t * sc, char * out_resolved) static
Definition at line 190 of file prepare.c.
References brix_prepare_owner_key(), BRIX_PREPARE_OWNER_KEY_MAX, brix_stage_registry_singleton(), BRIX_STAGE_REQID_LEN, brix_stage_request_add(), c, prepare_scan_t::collect_stage, prepare_scan_t::conf, prepare_scan_t::do_enqueue, prepare_scan_t::group_reqid, brix_stage_request_view_t::lfn, brix_stage_request_view_t::requester_dn, prepare_scan_t::stage_count, prepare_scan_t::stage_paths, and brix_stage_request_view_t::tod_expire.
Referenced by prepare_scan_paths().
prepare_scan_paths()
static ngx_int_t prepare_scan_paths (brix_ctx_t * ctx, ngx_connection_t * c, prepare_scan_t * sc) static
Definition at line 238 of file prepare.c.
References brix_prepare_check_path(), c, prepare_scan_t::conf, brix_ctx_recv_t::cur_dlen, kXR_noerrs, prepare_scan_t::missing, prepare_scan_t::need_resolved, prepare_scan_t::options, PATH_MAX, prepare_scan_t::paths, brix_ctx_recv_t::payload, prepare_enqueue_resolved(), brix_ctx_t::recv, prepare_scan_t::stage_bufs, prepare_scan_t::stage_count, and prepare_scan_t::stage_max.
Referenced by brix_handle_prepare().