nginx-xrootd: src/protocols/root/query/prepare_qprep.c File Reference
prepare_qprep.c File Reference
#include "query_internal.h"
#include "prepare_internal.h"
#include "fs/path/beneath.h"
#include "fs/xfer/stage_request_registry.h"
#include "core/compat/alloc_guard.h"
#include <errno.h>
#include <sys/stat.h>
Functions
static char qprep_status_letter (brix_stage_req_status_t s)
static ngx_flag_t qprep_path_authorized (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *pathbuf, const char *full_path)
static char qprep_status_for_path (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *pathbuf, const char *full_path)
static const u_char * qprep_capture_reqid (const u_char *p, const u_char *end, char *reqid, size_t reqid_sz)
static ngx_int_t qprep_resolve_src (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const u_char *p, const u_char *end, const char *reqid, const u_char **src, size_t *src_len)
static size_t qprep_emit_all (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const u_char *src, size_t src_len, u_char *resp, size_t resp_cap)
ngx_int_t brix_query_prep_status (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_query_prep_status()
ngx_int_t brix_query_prep_status (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 240 of file prepare_qprep.c.
References brix_log_access(), BRIX_PALLOC_OR_RETURN, brix_send_error(), brix_send_ok(), BRIX_STAGE_REQID_LEN, c, brix_ctx_recv_t::cur_dlen, kXR_NoMemory, kXR_ok, brix_ctx_recv_t::payload, qprep_capture_reqid(), qprep_emit_all(), qprep_resolve_src(), and brix_ctx_t::recv.
Referenced by brix_query_route_common().
qprep_capture_reqid()
static const u_char * qprep_capture_reqid (const u_char * p, const u_char * end, char * reqid, size_t reqid_sz) static
Definition at line 100 of file prepare_qprep.c.
References ngx_memcpy.
Referenced by brix_query_prep_status().
qprep_emit_all()
static size_t qprep_emit_all (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const u_char * src, size_t src_len, u_char * resp, size_t resp_cap) static
Definition at line 171 of file prepare_qprep.c.
References brix_beneath_full_path(), brix_extract_path(), BRIX_MAX_PATH, c, ngx_memcpy, PATH_MAX, and qprep_status_for_path().
Referenced by brix_query_prep_status().
qprep_path_authorized()
static ngx_flag_t qprep_path_authorized (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * pathbuf, const char * full_path) static
Definition at line 49 of file prepare_qprep.c.
References BRIX_AOP_STAGE, BRIX_AUTH_READ, brix_authz_check(), brix_check_token_scope(), brix_check_vo_acl_identity(), c, and brix_ctx_t::identity.
Referenced by qprep_status_for_path().
qprep_resolve_src()
static ngx_int_t qprep_resolve_src (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const u_char * p, const u_char * end, const char * reqid, const u_char ** src, size_t * src_len) static
Definition at line 134 of file prepare_qprep.c.
References brix_prepare_send_fail(), brix_send_ok(), brix_stage_registry_singleton(), brix_stage_request_get(), c, kXR_ArgInvalid, brix_ctx_prepare_t::paths, brix_ctx_prepare_t::paths_len, and brix_ctx_t::prepare.
Referenced by brix_query_prep_status().
qprep_status_for_path()
static char qprep_status_for_path (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * pathbuf, const char * full_path) static
Definition at line 65 of file prepare_qprep.c.
References brix_stage_registry_singleton(), BRIX_STAGE_REQID_LEN, brix_stage_request_find_by_path(), brix_stage_request_get(), brix_stat_beneath(), c, qprep_path_authorized(), qprep_status_letter(), stat(), and brix_stage_request_t::status.
Referenced by qprep_emit_all().
qprep_status_letter()
static char qprep_status_letter (brix_stage_req_status_t s) static
Definition at line 32 of file prepare_qprep.c.
References BRIX_STAGE_REQ_ACTIVE, BRIX_STAGE_REQ_DONE, BRIX_STAGE_REQ_FAILED, BRIX_STAGE_REQ_QUEUED, and s.
Referenced by qprep_status_for_path().