nginx-xrootd: src/protocols/root/query/prepare_check.c File Reference
prepare_check.c File Reference
#include "query_internal.h"
#include "prepare_internal.h"
#include "fs/path/beneath.h"
#include "fs/xfer/stage_request_registry.h"
#include <errno.h>
#include <sys/stat.h>
#include <time.h>
#include "core/compat/alloc_guard.h"
Functions
static ngx_flag_t brix_prepare_has_forbidden_component (const char *path)
static ngx_int_t brix_prepare_check_fail (brix_ctx_t *ctx, ngx_connection_t *c, const char *path, uint16_t errcode, const char *errmsg)
static ngx_int_t prepare_path_authz (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *pathbuf, const char *full_path)
static ngx_int_t prepare_stat_error (brix_ctx_t *ctx, ngx_connection_t *c, const char *pathbuf, const char *full_path)
ngx_int_t brix_prepare_check_path (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const u_char *line, size_t line_len, ngx_flag_t noerrs, ngx_uint_t *missing, char *out_resolved)
Function Documentation
brix_prepare_check_fail()
static ngx_int_t brix_prepare_check_fail (brix_ctx_t * ctx, ngx_connection_t * c, const char * path, uint16_t errcode, const char * errmsg) static
Definition at line 53 of file prepare_check.c.
References brix_prepare_send_fail(), and c.
Referenced by brix_prepare_check_path(), prepare_path_authz(), and prepare_stat_error().
brix_prepare_check_path()
ngx_int_t brix_prepare_check_path (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const u_char * line, size_t line_len, ngx_flag_t noerrs, ngx_uint_t * missing, char * out_resolved)
Definition at line 118 of file prepare_check.c.
References brix_beneath_full_path(), brix_extract_path(), BRIX_MAX_PATH, brix_prepare_check_fail(), brix_prepare_has_forbidden_component(), brix_stat_beneath(), c, kXR_ArgInvalid, kXR_ArgTooLong, kXR_isDirectory, PATH_MAX, prepare_path_authz(), prepare_stat_error(), and stat().
Referenced by prepare_scan_paths().
brix_prepare_has_forbidden_component()
static ngx_flag_t brix_prepare_has_forbidden_component (const char * path) static
Definition at line 22 of file prepare_check.c.
Referenced by brix_prepare_check_path().
prepare_path_authz()
static ngx_int_t prepare_path_authz (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * pathbuf, const char * full_path) static
Definition at line 76 of file prepare_check.c.
References BRIX_AOP_STAGE, BRIX_AUTH_READ, brix_authz_check(), brix_check_token_scope(), brix_check_vo_acl_identity(), brix_prepare_check_fail(), c, brix_ctx_t::identity, and kXR_NotAuthorized.
Referenced by brix_prepare_check_path().
prepare_stat_error()
static ngx_int_t prepare_stat_error (brix_ctx_t * ctx, ngx_connection_t * c, const char * pathbuf, const char * full_path) static
Definition at line 102 of file prepare_check.c.
References brix_prepare_check_fail(), c, kXR_IOError, kXR_NotAuthorized, and kXR_NotFound.
Referenced by brix_prepare_check_path().