nginx-xrootd: src/protocols/root/query/prepare_internal.h File Reference
prepare_internal.h File Reference
#include "core/ngx_brix_module.h"
Functions
ngx_int_t brix_prepare_send_fail (brix_ctx_t *ctx, ngx_connection_t *c, const char *path, uint16_t errcode, const char *errmsg)
ngx_int_t brix_prepare_check_path (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const u_char *line, size_t line_len, ngx_flag_t noerrs, ngx_uint_t *missing, char *out_resolved)
Function Documentation
brix_prepare_check_path()
ngx_int_t brix_prepare_check_path (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const u_char * line, size_t line_len, ngx_flag_t noerrs, ngx_uint_t * missing, char * out_resolved)
Definition at line 118 of file prepare_check.c.
References brix_beneath_full_path(), brix_extract_path(), BRIX_MAX_PATH, brix_prepare_check_fail(), brix_prepare_has_forbidden_component(), brix_stat_beneath(), c, kXR_ArgInvalid, kXR_ArgTooLong, kXR_isDirectory, PATH_MAX, prepare_path_authz(), prepare_stat_error(), and stat().
Referenced by prepare_scan_paths().
brix_prepare_send_fail()
ngx_int_t brix_prepare_send_fail (brix_ctx_t * ctx, ngx_connection_t * c, const char * path, uint16_t errcode, const char * errmsg)
Definition at line 78 of file prepare.c.
References brix_log_access(), brix_send_error(), and c.
Referenced by brix_handle_prepare(), brix_prepare_check_fail(), brix_prepare_handle_cancel(), prepare_dispatch_special(), and qprep_resolve_src().