nginx-xrootd: src/auth/authz/acc/privs.c File Reference
privs.c File Reference
#include "privs.h"
Functions
brix_acc_privs_t brix_acc_op_needs (brix_acc_op_t op)
int brix_acc_test (brix_acc_privs_t priv, brix_acc_op_t op)
const char * brix_acc_op_name (brix_acc_op_t op)
int brix_acc_parse_privs (const char *s, size_t len, brix_acc_priv_caps_t *caps)
Variables
static const brix_acc_privs_t brix_acc_op_need [BRIX_AOP_LAST+1]
Function Documentation
brix_acc_op_name()
const char * brix_acc_op_name (brix_acc_op_t op)
Definition at line 68 of file privs.c.
References BRIX_AOP_LAST, and op.
Referenced by brix_acc_http_authorize().
brix_acc_op_needs()
brix_acc_privs_t brix_acc_op_needs (brix_acc_op_t op)
Definition at line 49 of file privs.c.
References brix_acc_op_need, BRIX_AOP_LAST, and op.
Referenced by brix_acc_test().
brix_acc_parse_privs()
int brix_acc_parse_privs (const char * s, size_t len, brix_acc_priv_caps_t * caps)
Definition at line 82 of file privs.c.
References BRIX_ACC_PRIV_ALL, BRIX_ACC_PRIV_DELETE, BRIX_ACC_PRIV_INSERT, BRIX_ACC_PRIV_LOCK, BRIX_ACC_PRIV_LOOKUP, BRIX_ACC_PRIV_NONE, BRIX_ACC_PRIV_READ, BRIX_ACC_PRIV_RENAME, BRIX_ACC_PRIV_WRITE, brix_acc_priv_caps_t::nprivs, brix_acc_priv_caps_t::pprivs, and s.
Referenced by acc_cap_path().
brix_acc_test()
int brix_acc_test (brix_acc_privs_t priv, brix_acc_op_t op)
Definition at line 58 of file privs.c.
References brix_acc_op_needs(), and op.
Referenced by acc_access2().
Variable Documentation
brix_acc_op_need
const brix_acc_privs_t brix_acc_op_need[BRIX_AOP_LAST+1] static
Initial value:
= {
    [BRIX_AOP_ANY]         =  0x000u ,
    [BRIX_AOP_CHMOD]       =  ( 0x002u   |  ( 0x020u   |  0x040u  )     |  0x001u  )  ,
    [BRIX_AOP_CHOWN]       =  ( 0x002u   |  ( 0x020u   |  0x040u  )     |  0x001u  )  ,
    [BRIX_AOP_CREATE]      =  ( 0x002u   |  ( 0x020u   |  0x040u  )  )  ,
    [BRIX_AOP_DELETE]      =  0x001u  ,
    [BRIX_AOP_INSERT]      =  0x002u  ,
    [BRIX_AOP_LOCK]        =  0x004u  ,
    [BRIX_AOP_MKDIR]       =  0x002u  ,
    [BRIX_AOP_READ]        =  0x020u  ,
    [BRIX_AOP_READDIR]     =  0x020u  ,
    [BRIX_AOP_RENAME]      =  0x010u  ,
    [BRIX_AOP_STAT]        =  0x008u  ,
    [BRIX_AOP_UPDATE]      =  ( 0x020u   |  0x040u  )  ,
    [BRIX_AOP_EXCL_CREATE] = 0xffffu,
    [BRIX_AOP_EXCL_INSERT] = 0xffffu,
    [BRIX_AOP_STAGE]       =  ( 0x100u   | 0x080u)  ,
    [BRIX_AOP_POLL]        =  0x100u  ,
}
Definition at line 28 of file privs.c.
Referenced by brix_acc_op_needs().