nginx-xrootd: src/auth/authz/acc/privs.h File Reference
privs.h File Reference
#include <stddef.h>
#include <stdint.h>
Data Structures
struct brix_acc_priv_caps_t
Macros
#define BRIX_AUTHDB_FORMAT_NATIVE 0 /* original src/path/authdb.c (default) */
#define BRIX_AUTHDB_FORMAT_XRDACC 1 /* faithful XrdAcc engine (src/acc/) */
#define BRIX_AUTHDB_AUDIT_NONE 0
#define BRIX_AUTHDB_AUDIT_DENY 1
#define BRIX_AUTHDB_AUDIT_GRANT 2
#define BRIX_AUTHDB_AUDIT_ALL 3
#define BRIX_ACC_PRIV_NONE 0x000u
#define BRIX_ACC_PRIV_DELETE 0x001u /* 'd' */
#define BRIX_ACC_PRIV_INSERT 0x002u /* 'i' (also mkdir, create target) */
#define BRIX_ACC_PRIV_LOCK 0x004u /* 'k' (historically unused) */
#define BRIX_ACC_PRIV_LOOKUP 0x008u /* 'l' (stat / traversal) */
#define BRIX_ACC_PRIV_RENAME 0x010u /* 'n' (mv source) */
#define BRIX_ACC_PRIV_READ 0x020u /* 'r' (open r/o, readdir) */
#define BRIX_ACC_PRIV_WRITE 0x040u /* 'w' (open w/append) */
#define BRIX_ACC_PRIV_POLL 0x100u /* stage polling */
#define BRIX_ACC_PRIV_ALL 0x1ffu /* 'a' */
#define BRIX_ACC_PRIV_UPDATE (BRIX_ACC_PRIV_READ | BRIX_ACC_PRIV_WRITE) /* 0x060 */
#define BRIX_ACC_PRIV_CREATE (BRIX_ACC_PRIV_INSERT | BRIX_ACC_PRIV_UPDATE) /* 0x062 */
#define BRIX_ACC_PRIV_CHMOD
#define BRIX_ACC_PRIV_STAGE (BRIX_ACC_PRIV_POLL | 0x080u) /* 0x180 */
Typedefs
typedef uint16_t brix_acc_privs_t
Enumerations
enum brix_acc_op_t {
BRIX_AOP_ANY = 0 , BRIX_AOP_CHMOD = 1 , BRIX_AOP_CHOWN = 2 , BRIX_AOP_CREATE = 3 ,
BRIX_AOP_DELETE = 4 , BRIX_AOP_INSERT = 5 , BRIX_AOP_LOCK = 6 , BRIX_AOP_MKDIR = 7 ,
BRIX_AOP_READ = 8 , BRIX_AOP_READDIR = 9 , BRIX_AOP_RENAME = 10 , BRIX_AOP_STAT = 11 ,
BRIX_AOP_UPDATE = 12 , BRIX_AOP_EXCL_CREATE = 13 , BRIX_AOP_EXCL_INSERT = 14 , BRIX_AOP_STAGE = 15 ,
BRIX_AOP_POLL = 16 , BRIX_AOP_LAST = 16
}
Functions
brix_acc_privs_t brix_acc_op_needs (brix_acc_op_t op)
int brix_acc_test (brix_acc_privs_t priv, brix_acc_op_t op)
int brix_acc_parse_privs (const char *s, size_t len, brix_acc_priv_caps_t *caps)
const char * brix_acc_op_name (brix_acc_op_t op)
Macro Definition Documentation
BRIX_ACC_PRIV_ALL
#define BRIX_ACC_PRIV_ALL 0x1ffu /* 'a' */
Definition at line 49 of file privs.h.
BRIX_ACC_PRIV_CHMOD
#define BRIX_ACC_PRIV_CHMOD
Value:
                                 (BRIX_ACC_PRIV_INSERT | BRIX_ACC_PRIV_UPDATE \
                                 | BRIX_ACC_PRIV_DELETE)                        /* 0x063 */
Definition at line 54 of file privs.h.
BRIX_ACC_PRIV_CREATE
#define BRIX_ACC_PRIV_CREATE (BRIX_ACC_PRIV_INSERT | BRIX_ACC_PRIV_UPDATE) /* 0x062 */
Definition at line 53 of file privs.h.
BRIX_ACC_PRIV_DELETE
#define BRIX_ACC_PRIV_DELETE 0x001u /* 'd' */
Definition at line 41 of file privs.h.
BRIX_ACC_PRIV_INSERT
#define BRIX_ACC_PRIV_INSERT 0x002u /* 'i' (also mkdir, create target) */
Definition at line 42 of file privs.h.
BRIX_ACC_PRIV_LOCK
#define BRIX_ACC_PRIV_LOCK 0x004u /* 'k' (historically unused) */
Definition at line 43 of file privs.h.
BRIX_ACC_PRIV_LOOKUP
#define BRIX_ACC_PRIV_LOOKUP 0x008u /* 'l' (stat / traversal) */
Definition at line 44 of file privs.h.
BRIX_ACC_PRIV_NONE
#define BRIX_ACC_PRIV_NONE 0x000u
Definition at line 40 of file privs.h.
BRIX_ACC_PRIV_POLL
#define BRIX_ACC_PRIV_POLL 0x100u /* stage polling */
Definition at line 48 of file privs.h.
BRIX_ACC_PRIV_READ
#define BRIX_ACC_PRIV_READ 0x020u /* 'r' (open r/o, readdir) */
Definition at line 46 of file privs.h.
BRIX_ACC_PRIV_RENAME
#define BRIX_ACC_PRIV_RENAME 0x010u /* 'n' (mv source) */
Definition at line 45 of file privs.h.
BRIX_ACC_PRIV_STAGE
#define BRIX_ACC_PRIV_STAGE (BRIX_ACC_PRIV_POLL | 0x080u) /* 0x180 */
Definition at line 56 of file privs.h.
BRIX_ACC_PRIV_UPDATE
#define BRIX_ACC_PRIV_UPDATE (BRIX_ACC_PRIV_READ | BRIX_ACC_PRIV_WRITE) /* 0x060 */
Definition at line 52 of file privs.h.
BRIX_ACC_PRIV_WRITE
#define BRIX_ACC_PRIV_WRITE 0x040u /* 'w' (open w/append) */
Definition at line 47 of file privs.h.
BRIX_AUTHDB_AUDIT_ALL
#define BRIX_AUTHDB_AUDIT_ALL 3
Definition at line 34 of file privs.h.
BRIX_AUTHDB_AUDIT_DENY
#define BRIX_AUTHDB_AUDIT_DENY 1
Definition at line 32 of file privs.h.
BRIX_AUTHDB_AUDIT_GRANT
#define BRIX_AUTHDB_AUDIT_GRANT 2
Definition at line 33 of file privs.h.
BRIX_AUTHDB_AUDIT_NONE
#define BRIX_AUTHDB_AUDIT_NONE 0
Definition at line 31 of file privs.h.
BRIX_AUTHDB_FORMAT_NATIVE
#define BRIX_AUTHDB_FORMAT_NATIVE 0 /* original src/path/authdb.c (default) */
Definition at line 27 of file privs.h.
BRIX_AUTHDB_FORMAT_XRDACC
#define BRIX_AUTHDB_FORMAT_XRDACC 1 /* faithful XrdAcc engine (src/acc/) */
Definition at line 28 of file privs.h.
Typedef Documentation
brix_acc_privs_t
typedef uint16_t brix_acc_privs_t
Definition at line 58 of file privs.h.
Enumeration Type Documentation
brix_acc_op_t
enum brix_acc_op_t
Enumerator
BRIX_AOP_ANY
BRIX_AOP_CHMOD
BRIX_AOP_CHOWN
BRIX_AOP_CREATE
BRIX_AOP_DELETE
BRIX_AOP_INSERT
BRIX_AOP_LOCK
BRIX_AOP_MKDIR
BRIX_AOP_READ
BRIX_AOP_READDIR
BRIX_AOP_RENAME
BRIX_AOP_STAT
BRIX_AOP_UPDATE
BRIX_AOP_EXCL_CREATE
BRIX_AOP_EXCL_INSERT
BRIX_AOP_STAGE
BRIX_AOP_POLL
BRIX_AOP_LAST
Definition at line 73 of file privs.h.
Function Documentation
brix_acc_op_name()
const char * brix_acc_op_name (brix_acc_op_t op)
Definition at line 68 of file privs.c.
References BRIX_AOP_LAST.
Referenced by brix_acc_http_authorize().
brix_acc_op_needs()
brix_acc_privs_t brix_acc_op_needs (brix_acc_op_t op)
Definition at line 49 of file privs.c.
References brix_acc_op_need, and BRIX_AOP_LAST.
Referenced by brix_acc_test().
brix_acc_parse_privs()
int brix_acc_parse_privs (const char * s, size_t len, brix_acc_priv_caps_t * caps)
Definition at line 82 of file privs.c.
References BRIX_ACC_PRIV_ALL, BRIX_ACC_PRIV_DELETE, BRIX_ACC_PRIV_INSERT, BRIX_ACC_PRIV_LOCK, BRIX_ACC_PRIV_LOOKUP, BRIX_ACC_PRIV_NONE, BRIX_ACC_PRIV_READ, BRIX_ACC_PRIV_RENAME, BRIX_ACC_PRIV_WRITE, brix_acc_priv_caps_t::nprivs, brix_acc_priv_caps_t::pprivs, and s.
Referenced by acc_cap_path().
brix_acc_test()
int brix_acc_test (brix_acc_privs_t priv, brix_acc_op_t op)
Definition at line 58 of file privs.c.
References brix_acc_op_needs().
Referenced by acc_access2().