nginx-xrootd: src/core/config/process.c File Reference
process.c File Reference
#include <unistd.h>
#include <sys/stat.h>
#include "config.h"
#include "net/proxy/proxy.h"
#include "net/proxy/proxy_internal.h"
#include "core/compat/staged_file.h"
#include "core/compat/tmp_path.h"
#include "protocols/root/write/chkpoint.h"
#include "core/compat/crypto.h"
#include "core/compat/log_diag.h"
#include "core/compat/lifecycle_timing.h"
#include "net/manager/health_check.h"
#include "net/manager/pending.h"
#include "fs/cache/origin/pelican_register.h"
#include "fs/cache/cache_internal.h"
#include "fs/cache/cache_reap.h"
#include "fs/cache/reap_watermark.h"
#include "fs/xfer/stage_request_registry.h"
#include "fs/cache/cache_storage.h"
#include "fs/xfer/xfer.h"
#include "fs/xfer/stage_engine.h"
#include "auth/gsi/keypool.h"
#include "auth/impersonate/lifecycle.h"
#include "core/aio/uring.h"
#include "fs/backend/sd.h"
#include "core/compat/cstr.h"
Macros
#define BRIX_STAGE_REAP_FIRST_MS 1000
#define BRIX_STAGE_REAP_INTERVAL_MS 60000
#define BRIX_CACHE_REAP_FIRST_MS 5000
#define BRIX_CACHE_REAP_INTERVAL_MS 3600000 /* hourly */
#define BRIX_STAGE_SCHED_MS 1000
Functions
static void brix_crl_reload_handler (ngx_event_t *ev)
static void brix_pending_reap_handler (ngx_event_t *ev)
static void brix_stage_reap_handler (ngx_event_t *ev)
static void brix_cache_reap_handler (ngx_event_t *ev)
static void brix_stage_sched_handler (ngx_event_t *ev)
ngx_int_t ngx_stream_brix_init_process (ngx_cycle_t *cycle)
void brix_exit_process (ngx_cycle_t *cycle)
Variables
static ngx_event_t brix_pending_reap_timer
static ngx_event_t brix_stage_reap_timer
static ngx_event_t brix_stage_sched_timer
Macro Definition Documentation
BRIX_CACHE_REAP_FIRST_MS
#define BRIX_CACHE_REAP_FIRST_MS 5000
Definition at line 147 of file process.c.
BRIX_CACHE_REAP_INTERVAL_MS
#define BRIX_CACHE_REAP_INTERVAL_MS 3600000 /* hourly */
Definition at line 148 of file process.c.
BRIX_STAGE_REAP_FIRST_MS
#define BRIX_STAGE_REAP_FIRST_MS 1000
Definition at line 121 of file process.c.
BRIX_STAGE_REAP_INTERVAL_MS
#define BRIX_STAGE_REAP_INTERVAL_MS 60000
Definition at line 122 of file process.c.
BRIX_STAGE_SCHED_MS
#define BRIX_STAGE_SCHED_MS 1000
Definition at line 167 of file process.c.
Function Documentation
brix_cache_reap_handler()
static void brix_cache_reap_handler (ngx_event_t * ev) static
Definition at line 151 of file process.c.
References brix_cache_reap_dirty(), and BRIX_CACHE_REAP_INTERVAL_MS.
Referenced by ngx_stream_brix_init_process().
brix_crl_reload_handler()
static void brix_crl_reload_handler (ngx_event_t * ev) static
Definition at line 40 of file process.c.
References BRIX_DIAG_CRIT, brix_rebuild_gsi_store(), ngx_stream_brix_srv_conf_t::crl, ngx_stream_brix_srv_conf_t::crl_mtime, ngx_stream_brix_srv_conf_t::crl_reload, and stat().
Referenced by ngx_stream_brix_init_process().
brix_exit_process()
void brix_exit_process (ngx_cycle_t * cycle)
Definition at line 485 of file process.c.
References brix_cache_storage_cleanup(), brix_crypto_cleanup(), brix_proxy_pool_shutdown(), brix_uring_exit_worker(), close(), ngx_stream_brix_srv_conf_t::common, ngx_http_brix_shared_conf_t::enable, ngx_stream_brix_module, and ngx_stream_brix_srv_conf_t::rootfd.
brix_pending_reap_handler()
static void brix_pending_reap_handler (ngx_event_t * ev) static
Definition at line 100 of file process.c.
References brix_pending_reap_expired(), and BRIX_PENDING_REAP_INTERVAL_MS.
Referenced by ngx_stream_brix_init_process().
brix_stage_reap_handler()
static void brix_stage_reap_handler (ngx_event_t * ev) static
Definition at line 128 of file process.c.
References brix_stage_reap_all(), and BRIX_STAGE_REAP_INTERVAL_MS.
Referenced by ngx_stream_brix_init_process().
brix_stage_sched_handler()
static void brix_stage_sched_handler (ngx_event_t * ev) static
Definition at line 171 of file process.c.
References BRIX_STAGE_SCHED_MS, and brix_stage_scheduler_tick().
Referenced by ngx_stream_brix_init_process().
ngx_stream_brix_init_process()
ngx_int_t ngx_stream_brix_init_process (ngx_cycle_t * cycle)
Definition at line 189 of file process.c.
References ngx_stream_brix_srv_conf_t::access_log_fd, ngx_stream_brix_srv_conf_t::access_log_file, brix_cms_conf_t::addr, brix_proxy_conf_t::audit_log_fd, brix_proxy_conf_t::audit_log_file, ngx_stream_brix_srv_conf_t::auth, brix_acc_init_server(), BRIX_AUTH_BOTH, BRIX_AUTH_GSI, brix_cache_pelican_schedule_advertise(), BRIX_CACHE_REAP_FIRST_MS, brix_cache_reap_handler(), brix_cache_state_root(), brix_cache_storage_init(), brix_cache_watermark_timer_handler(), brix_chkpoint_recover_root(), brix_crl_reload_handler(), brix_crypto_init(), brix_gsi_keypool_init(), brix_hc_manager_start(), brix_imp_init_worker(), brix_openat2_runtime_available(), brix_pending_reap_handler(), BRIX_PENDING_REAP_INTERVAL_MS, brix_pending_reap_timer, brix_phase_mark(), brix_phase_timer_log(), brix_phase_timer_start(), brix_proxy_pool_init(), brix_stage_dir_count(), brix_stage_engine_init(), BRIX_STAGE_REAP_FIRST_MS, brix_stage_reap_handler(), brix_stage_reap_timer, brix_stage_reconcile(), brix_stage_registry_init(), brix_stage_sched_handler(), BRIX_STAGE_SCHED_MS, brix_stage_sched_timer, brix_str_cbuf(), brix_tmp_reap_all(), brix_token_jwks_schedule_refresh(), brix_uring_init_worker(), brix_xfer_resume_sweep_register(), ngx_stream_brix_srv_conf_t::cache, ngx_stream_brix_srv_conf_t::cache_dirty_max_age, ngx_stream_brix_srv_conf_t::cache_reap_timer, ngx_http_brix_shared_conf_t::cache_store, ngx_stream_brix_srv_conf_t::cms, ngx_stream_brix_srv_conf_t::common, brix_frm_conf_t::control_dir, ngx_stream_brix_srv_conf_t::crl, ngx_stream_brix_srv_conf_t::crl_reload, ngx_stream_brix_srv_conf_t::crl_timer, ngx_http_brix_shared_conf_t::enable, brix_frm_conf_t::enable, ngx_stream_brix_srv_conf_t::frm, ngx_stream_brix_srv_conf_t::gsi_keypool_seed, ngx_stream_brix_srv_conf_t::gsi_keypool_size, brix_cache_reaper_conf_t::high_watermark, ngx_stream_brix_srv_conf_t::manager_mode, ngx_brix_cms_start(), ngx_stream_brix_module, O_PATH, open(), ngx_stream_brix_srv_conf_t::proxy, ngx_stream_brix_srv_conf_t::reaper, ngx_http_brix_shared_conf_t::root_canon, ngx_stream_brix_srv_conf_t::rootfd, ngx_http_brix_shared_conf_t::thread_pool, brix_cache_reaper_conf_t::timer, and ngx_stream_brix_srv_conf_t::upload_stage_dir_canon.
Variable Documentation
brix_pending_reap_timer
ngx_event_t brix_pending_reap_timer static
Definition at line 95 of file process.c.
Referenced by ngx_stream_brix_init_process().
brix_stage_reap_timer
ngx_event_t brix_stage_reap_timer static
Definition at line 123 of file process.c.
Referenced by ngx_stream_brix_init_process().
brix_stage_sched_timer
ngx_event_t brix_stage_sched_timer static
Definition at line 168 of file process.c.
Referenced by ngx_stream_brix_init_process().