nginx-xrootd: src/core/config/process_internal.h File Reference
process_internal.h File Reference
Macros
#define BRIX_CACHE_REAP_FIRST_MS 5000
#define BRIX_CACHE_REAP_INTERVAL_MS 3600000 /* hourly */
Functions
void brix_crl_reload_handler (ngx_event_t *ev)
void brix_cache_reap_handler (ngx_event_t *ev)
void brix_init_stage_sched_timer (ngx_cycle_t *cycle)
void brix_init_pending_reap_timer (ngx_cycle_t *cycle, ngx_uint_t manager_seen)
void brix_init_stage_reap_timer (ngx_cycle_t *cycle)
ngx_int_t brix_init_one_server (ngx_cycle_t *cycle, ngx_stream_brix_srv_conf_t *xcf)
Macro Definition Documentation
BRIX_CACHE_REAP_FIRST_MS
#define BRIX_CACHE_REAP_FIRST_MS 5000
Definition at line 39 of file process_internal.h.
BRIX_CACHE_REAP_INTERVAL_MS
#define BRIX_CACHE_REAP_INTERVAL_MS 3600000 /* hourly */
Definition at line 40 of file process_internal.h.
Function Documentation
brix_cache_reap_handler()
void brix_cache_reap_handler (ngx_event_t * ev)
Definition at line 161 of file process_timers.c.
References brix_cache_reap_dirty(), and BRIX_CACHE_REAP_INTERVAL_MS.
Referenced by brix_init_server_cache_reap_timer().
brix_crl_reload_handler()
void brix_crl_reload_handler (ngx_event_t * ev)
Definition at line 49 of file process_timers.c.
References BRIX_DIAG_CRIT, brix_rebuild_gsi_store(), and stat().
Referenced by brix_init_server_crl_jwks().
brix_init_one_server()
ngx_int_t brix_init_one_server (ngx_cycle_t * cycle, ngx_stream_brix_srv_conf_t * xcf)
Definition at line 351 of file process_server_init.c.
References brix_acc_init_server(), brix_cache_pelican_schedule_advertise(), brix_cache_storage_init(), brix_chkpoint_recover_root(), brix_hc_manager_start(), brix_init_server_backend_credential(), brix_init_server_cache_reap_timer(), brix_init_server_crl_jwks(), brix_init_server_rootfd(), brix_init_server_stage_registry(), brix_init_server_watermark_timer(), and ngx_brix_cms_start().
Referenced by ngx_stream_brix_init_process().
brix_init_pending_reap_timer()
void brix_init_pending_reap_timer (ngx_cycle_t * cycle, ngx_uint_t manager_seen)
Definition at line 236 of file process_timers.c.
References brix_maint_timer_conn, brix_pending_reap_handler(), BRIX_PENDING_REAP_INTERVAL_MS, and brix_pending_reap_timer.
Referenced by ngx_stream_brix_init_process().
brix_init_stage_reap_timer()
void brix_init_stage_reap_timer (ngx_cycle_t * cycle)
Definition at line 266 of file process_timers.c.
References brix_maint_timer_conn, brix_stage_dir_count(), BRIX_STAGE_REAP_FIRST_MS, brix_stage_reap_handler(), and brix_stage_reap_timer.
Referenced by ngx_stream_brix_init_process().
brix_init_stage_sched_timer()
void brix_init_stage_sched_timer (ngx_cycle_t * cycle)
Definition at line 207 of file process_timers.c.
References brix_maint_timer_conn, brix_stage_sched_handler(), BRIX_STAGE_SCHED_MS, and brix_stage_sched_timer.
Referenced by ngx_stream_brix_init_process().