nginx-xrootd: src/core/config/process_timers.c File Reference
process_timers.c File Reference
#include "config.h"
#include "process_internal.h"
#include <sys/stat.h>
#include "core/compat/log_diag.h"
#include "net/manager/pending.h"
#include "core/compat/staged_file.h"
#include "fs/cache/cache_reap.h"
#include "fs/xfer/stage_engine.h"
Macros
#define BRIX_STAGE_REAP_FIRST_MS 1000
#define BRIX_STAGE_REAP_INTERVAL_MS 60000
#define BRIX_STAGE_SCHED_MS 1000
Functions
void brix_crl_reload_handler (ngx_event_t *ev)
static void brix_pending_reap_handler (ngx_event_t *ev)
static void brix_stage_reap_handler (ngx_event_t *ev)
void brix_cache_reap_handler (ngx_event_t *ev)
static void brix_stage_sched_handler (ngx_event_t *ev)
void brix_init_stage_sched_timer (ngx_cycle_t *cycle)
void brix_init_pending_reap_timer (ngx_cycle_t *cycle, ngx_uint_t manager_seen)
void brix_init_stage_reap_timer (ngx_cycle_t *cycle)
Variables
ngx_connection_t brix_maint_timer_conn = { .fd = (ngx_socket_t) -1 }
static ngx_event_t brix_pending_reap_timer
static ngx_event_t brix_stage_reap_timer
static ngx_event_t brix_stage_sched_timer
Macro Definition Documentation
BRIX_STAGE_REAP_FIRST_MS
#define BRIX_STAGE_REAP_FIRST_MS 1000
Definition at line 132 of file process_timers.c.
BRIX_STAGE_REAP_INTERVAL_MS
#define BRIX_STAGE_REAP_INTERVAL_MS 60000
Definition at line 133 of file process_timers.c.
BRIX_STAGE_SCHED_MS
#define BRIX_STAGE_SCHED_MS 1000
Definition at line 177 of file process_timers.c.
Function Documentation
brix_cache_reap_handler()
void brix_cache_reap_handler (ngx_event_t * ev)
Definition at line 161 of file process_timers.c.
References brix_cache_reap_dirty(), and BRIX_CACHE_REAP_INTERVAL_MS.
Referenced by brix_init_server_cache_reap_timer().
brix_crl_reload_handler()
void brix_crl_reload_handler (ngx_event_t * ev)
Definition at line 49 of file process_timers.c.
References BRIX_DIAG_CRIT, brix_rebuild_gsi_store(), and stat().
Referenced by brix_init_server_crl_jwks().
brix_init_pending_reap_timer()
void brix_init_pending_reap_timer (ngx_cycle_t * cycle, ngx_uint_t manager_seen)
Definition at line 236 of file process_timers.c.
References brix_maint_timer_conn, brix_pending_reap_handler(), BRIX_PENDING_REAP_INTERVAL_MS, and brix_pending_reap_timer.
Referenced by ngx_stream_brix_init_process().
brix_init_stage_reap_timer()
void brix_init_stage_reap_timer (ngx_cycle_t * cycle)
Definition at line 266 of file process_timers.c.
References brix_maint_timer_conn, brix_stage_dir_count(), BRIX_STAGE_REAP_FIRST_MS, brix_stage_reap_handler(), and brix_stage_reap_timer.
Referenced by ngx_stream_brix_init_process().
brix_init_stage_sched_timer()
void brix_init_stage_sched_timer (ngx_cycle_t * cycle)
Definition at line 207 of file process_timers.c.
References brix_maint_timer_conn, brix_stage_sched_handler(), BRIX_STAGE_SCHED_MS, and brix_stage_sched_timer.
Referenced by ngx_stream_brix_init_process().
brix_pending_reap_handler()
static void brix_pending_reap_handler (ngx_event_t * ev) static
Definition at line 111 of file process_timers.c.
References brix_pending_reap_expired(), and BRIX_PENDING_REAP_INTERVAL_MS.
Referenced by brix_init_pending_reap_timer().
brix_stage_reap_handler()
static void brix_stage_reap_handler (ngx_event_t * ev) static
Definition at line 139 of file process_timers.c.
References brix_stage_reap_all(), and BRIX_STAGE_REAP_INTERVAL_MS.
Referenced by brix_init_stage_reap_timer().
brix_stage_sched_handler()
static void brix_stage_sched_handler (ngx_event_t * ev) static
Definition at line 181 of file process_timers.c.
References BRIX_STAGE_SCHED_MS, and brix_stage_scheduler_tick().
Referenced by brix_init_stage_sched_timer().
Variable Documentation
brix_maint_timer_conn
ngx_connection_t brix_maint_timer_conn = { .fd = (ngx_socket_t) -1 }
Definition at line 44 of file process_timers.c.
Referenced by brix_alog_emit(), brix_init_pending_reap_timer(), brix_init_stage_reap_timer(), brix_init_stage_sched_timer(), and brix_uring_panicfile_arm().
brix_pending_reap_timer
ngx_event_t brix_pending_reap_timer static
Definition at line 106 of file process_timers.c.
Referenced by brix_init_pending_reap_timer().
brix_stage_reap_timer
ngx_event_t brix_stage_reap_timer static
Definition at line 134 of file process_timers.c.
Referenced by brix_init_stage_reap_timer().
brix_stage_sched_timer
ngx_event_t brix_stage_sched_timer static
Definition at line 178 of file process_timers.c.
Referenced by brix_init_stage_sched_timer().