nginx-xrootd: src/core/config/process_server_init.c File Reference
process_server_init.c File Reference
#include "config.h"
#include "process_internal.h"
#include <unistd.h>
#include "protocols/root/write/chkpoint.h"
#include "net/manager/health_check.h"
#include "fs/cache/origin/pelican_register.h"
#include "fs/cache/reap_watermark.h"
#include "fs/xfer/stage_request_registry.h"
#include "fs/cache/cache_storage.h"
#include "fs/xfer/xfer.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "core/config/credential_block.h"
#include "core/compat/cstr.h"
Functions
static void brix_init_server_backend_credential (ngx_cycle_t *cycle, ngx_stream_brix_srv_conf_t *xcf)
static void brix_init_server_stage_registry (ngx_cycle_t *cycle, ngx_stream_brix_srv_conf_t *xcf)
static ngx_int_t brix_init_server_rootfd (ngx_cycle_t *cycle, ngx_stream_brix_srv_conf_t *xcf)
static ngx_int_t brix_init_server_cache_reap_timer (ngx_cycle_t *cycle, ngx_stream_brix_srv_conf_t *xcf)
static ngx_int_t brix_init_server_watermark_timer (ngx_cycle_t *cycle, ngx_stream_brix_srv_conf_t *xcf)
static ngx_int_t brix_init_server_crl_jwks (ngx_cycle_t *cycle, ngx_stream_brix_srv_conf_t *xcf)
ngx_int_t brix_init_one_server (ngx_cycle_t *cycle, ngx_stream_brix_srv_conf_t *xcf)
Function Documentation
brix_init_one_server()
ngx_int_t brix_init_one_server (ngx_cycle_t * cycle, ngx_stream_brix_srv_conf_t * xcf)
Definition at line 351 of file process_server_init.c.
References brix_acc_init_server(), brix_cache_pelican_schedule_advertise(), brix_cache_storage_init(), brix_chkpoint_recover_root(), brix_hc_manager_start(), brix_init_server_backend_credential(), brix_init_server_cache_reap_timer(), brix_init_server_crl_jwks(), brix_init_server_rootfd(), brix_init_server_stage_registry(), brix_init_server_watermark_timer(), and ngx_brix_cms_start().
Referenced by ngx_stream_brix_init_process().
brix_init_server_backend_credential()
static void brix_init_server_backend_credential (ngx_cycle_t * cycle, ngx_stream_brix_srv_conf_t * xcf) static
Definition at line 67 of file process_server_init.c.
References brix_credential_lookup(), brix_credential_to_backend_cred(), and brix_vfs_backend_set_credential().
Referenced by brix_init_one_server().
brix_init_server_cache_reap_timer()
static ngx_int_t brix_init_server_cache_reap_timer (ngx_cycle_t * cycle, ngx_stream_brix_srv_conf_t * xcf) static
Definition at line 202 of file process_server_init.c.
References BRIX_CACHE_REAP_FIRST_MS, brix_cache_reap_handler(), brix_cache_state_root(), and ngx_pcalloc().
Referenced by brix_init_one_server().
brix_init_server_crl_jwks()
static ngx_int_t brix_init_server_crl_jwks (ngx_cycle_t * cycle, ngx_stream_brix_srv_conf_t * xcf) static
Definition at line 291 of file process_server_init.c.
References BRIX_AUTH_BOTH, BRIX_AUTH_GSI, brix_crl_reload_handler(), brix_token_jwks_schedule_refresh(), and ngx_pcalloc().
Referenced by brix_init_one_server().
brix_init_server_rootfd()
static ngx_int_t brix_init_server_rootfd (ngx_cycle_t * cycle, ngx_stream_brix_srv_conf_t * xcf) static
Definition at line 164 of file process_server_init.c.
References O_PATH, and open().
Referenced by brix_init_one_server().
brix_init_server_stage_registry()
static void brix_init_server_stage_registry (ngx_cycle_t * cycle, ngx_stream_brix_srv_conf_t * xcf) static
Definition at line 128 of file process_server_init.c.
References brix_stage_registry_init(), brix_str_cbuf(), and brix_xfer_resume_sweep_register().
Referenced by brix_init_one_server().
brix_init_server_watermark_timer()
static ngx_int_t brix_init_server_watermark_timer (ngx_cycle_t * cycle, ngx_stream_brix_srv_conf_t * xcf) static
Definition at line 243 of file process_server_init.c.
References BRIX_CACHE_REAP_FIRST_MS, brix_cache_state_root(), brix_cache_watermark_timer_handler(), and ngx_pcalloc().
Referenced by brix_init_one_server().