nginx-xrootd: client/lib/core/progname.h File Reference
progname.h File Reference
#include <stdio.h>
#include <string.h>
Macros
#define BRIX_COMPAT_PREFIX "brix-"
#define BRIX_COMPAT_PREFIX_LEN 5
Functions
static const char * brix_prog_base (const char *argv0)
static const char * brix_prog_strip_compat (const char *base)
static const char * brix_prog_prefix (const char *base)
static void brix_usage_footer (FILE *out, const char *argv0)
Macro Definition Documentation
BRIX_COMPAT_PREFIX
#define BRIX_COMPAT_PREFIX "brix-"
Definition at line 27 of file progname.h.
BRIX_COMPAT_PREFIX_LEN
#define BRIX_COMPAT_PREFIX_LEN 5
Definition at line 28 of file progname.h.
Function Documentation
brix_prog_base()
static const char * brix_prog_base (const char * argv0) inline static
Definition at line 36 of file progname.h.
Referenced by brix_mpxstats_main(), brix_qstats_main(), brix_usage_footer(), brix_wait41_main(), brix_xrdcinfo_main(), ckv_handle_early_flags(), cmd_cp(), cmd_diag(), cmd_fs_verb(), cmd_get(), cmd_put(), cmd_replicas(), cmd_storascan(), cmd_sync(), cmd_version(), dispatch(), dispatch(), dx_personality_route(), main(), opt_early_exit(), usage_fp(), usage_fp(), usage_fp(), usage_fp(), usage_fp(), usage_fp(), usage_fp(), usage_fp(), usage_fp(), usage_fp(), xrd_mount(), xrdcp_parse_option(), xrdprep_handle_meta_flags(), and xrdprep_print_help().
brix_prog_prefix()
static const char * brix_prog_prefix (const char * base) inline static
Definition at line 68 of file progname.h.
References BRIX_COMPAT_PREFIX, and BRIX_COMPAT_PREFIX_LEN.
Referenced by cmd_cp(), cmd_diag(), cmd_fs_verb(), cmd_get(), cmd_put(), cmd_replicas(), cmd_storascan(), cmd_sync(), and xrd_mount().
brix_prog_strip_compat()
static const char * brix_prog_strip_compat (const char * base) inline static
Definition at line 54 of file progname.h.
References BRIX_COMPAT_PREFIX, and BRIX_COMPAT_PREFIX_LEN.
Referenced by dx_personality_route(), and main().
brix_usage_footer()
static void brix_usage_footer (FILE * out, const char * argv0) inline static
Definition at line 84 of file progname.h.
References brix_prog_base().
Referenced by bench_help(), brix_qstats_main(), brix_wait41_main(), brix_xrdcinfo_main(), cmd_scan(), dispatch(), main(), usage_fp(), usage_fp(), usage_fp(), usage_fp(), usage_fp(), usage_fp(), usage_fp(), usage_fp(), usage_fp(), usage_fp(), usage_fp(), verify_help(), and xrdprep_print_help().