nginx-xrootd: src/protocols/webdav/propfind_props.c File Reference
propfind_props.c File Reference
#include "propfind_internal.h"
Functions
static ngx_int_t propfind_emit_owner (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, ngx_http_brix_webdav_req_ctx_t *ctx)
static ngx_int_t propfind_emit_current_privilege (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t propfind_emit_supported_privilege (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail)
static ngx_int_t propfind_emit_acl (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, ngx_http_brix_webdav_loc_conf_t *conf)
ngx_int_t propfind_append_acl_properties (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, unsigned mask)
static ngx_int_t propfind_emit_quota (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, unsigned mask, const char *path, struct stat *sb)
static ngx_int_t propfind_emit_displayname (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, const char *href)
static ngx_int_t propfind_emit_locality (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, const char *path, struct stat *sb)
static ngx_int_t propfind_emit_basic_metadata (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, unsigned mask, struct stat *sb, char *date_buf)
static ngx_int_t propfind_emit_standard_props (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, unsigned mask, const char *href, const char *path, struct stat *sb, char *date_buf)
static ngx_int_t propfind_dead_props_resolve_and_emit (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, const char *path, const propfind_req_t *req, ngx_flag_t unknown_found[16])
static ngx_int_t propfind_emit_404_propstat (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, const propfind_req_t *req, const ngx_flag_t unknown_found[16])
ngx_int_t propfind_entry (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, const char *href, const char *path, struct stat *sb, const propfind_req_t *req)
Function Documentation
propfind_append_acl_properties()
ngx_int_t propfind_append_acl_properties (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, unsigned mask)
Definition at line 176 of file propfind_props.c.
References brix_http_chain_appendf(), ngx_http_brix_webdav_module, PF_ACL, PF_ACL_RESTRICTIONS, PF_CURRENT_PRIVILEGE, PF_GROUP, PF_OWNER, PF_PRINCIPAL_SET, PF_SUPPORTED_PRIVILEGE, propfind_emit_acl(), propfind_emit_current_privilege(), propfind_emit_owner(), and propfind_emit_supported_privilege().
Referenced by propfind_entry().
propfind_dead_props_resolve_and_emit()
static ngx_int_t propfind_dead_props_resolve_and_emit (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, const char * path, const propfind_req_t * req, ngx_flag_t unknown_found[16]) static
Definition at line 532 of file propfind_props.c.
References propfind_unknown_t::local, propfind_unknown_t::ns, PROPFIND_ALLPROP, PROPFIND_PROP, propfind_req_t::type, propfind_req_t::unknown, propfind_req_t::unknown_count, webdav_dead_prop_append_value(), and webdav_dead_props_append_all().
Referenced by propfind_entry().
propfind_emit_404_propstat()
static ngx_int_t propfind_emit_404_propstat (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, const propfind_req_t * req, const ngx_flag_t unknown_found[16]) static
Definition at line 579 of file propfind_props.c.
References brix_http_chain_appendf(), PROPFIND_PROP, propfind_req_t::type, propfind_req_t::unknown, propfind_req_t::unknown_count, and propfind_unknown_t::xml.
Referenced by propfind_entry().
propfind_emit_acl()
static ngx_int_t propfind_emit_acl (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 139 of file propfind_props.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_http_chain_appendf(), and ngx_http_brix_webdav_loc_conf_t::common.
Referenced by propfind_append_acl_properties().
propfind_emit_basic_metadata()
static ngx_int_t propfind_emit_basic_metadata (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, unsigned mask, struct stat * sb, char * date_buf) static
Definition at line 389 of file propfind_props.c.
References BRIX_ETAG_WEAK, brix_format_iso8601(), brix_http_chain_appendf(), brix_http_etag_str(), PF_CONTENTLENGTH, PF_CREATIONDATE, PF_ETAG, PF_LASTMODIFIED, and PF_RESOURCETYPE.
Referenced by propfind_emit_standard_props().
propfind_emit_current_privilege()
static ngx_int_t propfind_emit_current_privilege (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 50 of file propfind_props.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_http_chain_appendf(), and ngx_http_brix_webdav_loc_conf_t::common.
Referenced by propfind_append_acl_properties().
propfind_emit_displayname()
static ngx_int_t propfind_emit_displayname (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, const char * href) static
Definition at line 293 of file propfind_props.c.
References brix_http_chain_appendf(), name, and webdav_escape_xml_text().
Referenced by propfind_emit_standard_props().
propfind_emit_locality()
static ngx_int_t propfind_emit_locality (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, const char * path, struct stat * sb) static
Definition at line 326 of file propfind_props.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_http_chain_appendf(), BRIX_PROTO_WEBDAV, BRIX_SD_RES_LOST, BRIX_SD_RES_NEARLINE, BRIX_SD_RES_OFFLINE, BRIX_SD_RES_ONLINE, brix_vfs_ctx_init(), brix_vfs_residency(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, nearline, ngx_http_brix_webdav_module, brix_vfs_ctx_t::pool, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by propfind_emit_standard_props().
propfind_emit_owner()
static ngx_int_t propfind_emit_owner (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, ngx_http_brix_webdav_req_ctx_t * ctx) static
Definition at line 21 of file propfind_props.c.
References brix_http_chain_appendf(), ngx_http_brix_webdav_req_ctx_t::dn, and webdav_escape_xml_text().
Referenced by propfind_append_acl_properties().
propfind_emit_quota()
static ngx_int_t propfind_emit_quota (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, unsigned mask, const char * path, struct stat * sb) static
Definition at line 246 of file propfind_props.c.
References brix_fs_usage_t::available_bytes, brix_fs_usage_stat(), brix_http_chain_appendf(), PF_QUOTA_AVAILABLE, PF_QUOTA_USED, and brix_fs_usage_t::used_bytes.
Referenced by propfind_emit_standard_props().
propfind_emit_standard_props()
static ngx_int_t propfind_emit_standard_props (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, unsigned mask, const char * href, const char * path, struct stat * sb, char * date_buf) static
Definition at line 459 of file propfind_props.c.
References brix_http_chain_appendf(), PF_CONTENTTYPE, PF_DISPLAYNAME, PF_LOCALITY, PF_LOCKDISCOVERY, PF_QUOTA_AVAILABLE, PF_QUOTA_USED, PF_SUPPORTED_REPORT, PF_SUPPORTEDLOCK, propfind_emit_basic_metadata(), propfind_emit_displayname(), propfind_emit_locality(), propfind_emit_quota(), webdav_lock_append_discovery(), and webdav_lock_append_supported().
Referenced by propfind_entry().
propfind_emit_supported_privilege()
static ngx_int_t propfind_emit_supported_privilege (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail) static
Definition at line 93 of file propfind_props.c.
References brix_http_chain_appendf().
Referenced by propfind_append_acl_properties().
propfind_entry()
ngx_int_t propfind_entry (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, const char * href, const char * path, struct stat * sb, const propfind_req_t * req)
Definition at line 642 of file propfind_props.c.
References brix_http_chain_appendf(), PF_ALL, PF_UNKNOWN_MAX, propfind_req_t::prop_mask, propfind_append_acl_properties(), propfind_dead_props_resolve_and_emit(), propfind_emit_404_propstat(), propfind_emit_standard_props(), PROPFIND_PROP, PROPFIND_PROPNAME, propfind_req_t::type, webdav_dead_props_append_all(), and webdav_escape_xml_text().
Referenced by propfind_build_body(), and propfind_walk_emit().