nginx-xrootd: src/protocols/webdav/propfind.c File Reference
propfind.c File Reference
#include "propfind_internal.h"
Functions
unsigned propfind_name_to_bit (const char *name)
const char * propfind_assemble_body (ngx_http_request_t *r, size_t *len)
static xmlDocPtr propfind_read_doc (const char *body, size_t body_len)
static void propfind_capture_unknown (ngx_http_request_t *r, propfind_req_t *req, xmlNodePtr prop)
static void propfind_collect_props (ngx_http_request_t *r, propfind_req_t *req, xmlNodePtr child)
static void propfind_walk_root (ngx_http_request_t *r, propfind_req_t *req, xmlNodePtr root)
void propfind_parse_request (ngx_http_request_t *r, propfind_req_t *req)
int propfind_parse_depth (ngx_http_request_t *r)
void propfind_body_handler (ngx_http_request_t *r)
ngx_int_t webdav_handle_propfind (ngx_http_request_t *r)
Function Documentation
propfind_assemble_body()
const char * propfind_assemble_body (ngx_http_request_t * r, size_t * len)
Definition at line 49 of file propfind.c.
References brix_http_body_read_all(), and PROPFIND_BODY_MAX.
Referenced by propfind_parse_request().
propfind_body_handler()
void propfind_body_handler (ngx_http_request_t * r)
Definition at line 299 of file propfind.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, and propfind_do().
Referenced by webdav_handle_propfind().
propfind_capture_unknown()
static void propfind_capture_unknown (ngx_http_request_t * r, propfind_req_t * req, xmlNodePtr prop) static
Definition at line 108 of file propfind.c.
References propfind_unknown_t::local, propfind_unknown_t::ns, PF_UNKNOWN_MAX, PF_UNKNOWN_XML_MAX, propfind_req_t::unknown, propfind_req_t::unknown_count, webdav_escape_xml_text(), and propfind_unknown_t::xml.
Referenced by propfind_collect_props().
propfind_collect_props()
static void propfind_collect_props (ngx_http_request_t * r, propfind_req_t * req, xmlNodePtr child) static
Definition at line 157 of file propfind.c.
References propfind_req_t::prop_mask, propfind_capture_unknown(), and propfind_name_to_bit().
Referenced by propfind_walk_root().
propfind_name_to_bit()
unsigned propfind_name_to_bit (const char * name)
Definition at line 8 of file propfind.c.
References name, PF_ACL, PF_ACL_RESTRICTIONS, PF_CONTENTLENGTH, PF_CONTENTTYPE, PF_CREATIONDATE, PF_CURRENT_PRIVILEGE, PF_DISPLAYNAME, PF_ETAG, PF_GROUP, PF_LASTMODIFIED, PF_LOCALITY, PF_LOCKDISCOVERY, PF_OWNER, PF_PRINCIPAL_SET, PF_QUOTA_AVAILABLE, PF_QUOTA_USED, PF_RESOURCETYPE, PF_SUPPORTED_PRIVILEGE, PF_SUPPORTED_REPORT, and PF_SUPPORTEDLOCK.
Referenced by propfind_collect_props().
propfind_parse_depth()
int propfind_parse_depth (ngx_http_request_t * r)
Definition at line 270 of file propfind.c.
References brix_http_get_header().
Referenced by propfind_do().
propfind_parse_request()
void propfind_parse_request (ngx_http_request_t * r, propfind_req_t * req)
Definition at line 225 of file propfind.c.
References propfind_req_t::prop_mask, PROPFIND_ALLPROP, propfind_assemble_body(), propfind_read_doc(), propfind_walk_root(), propfind_req_t::type, and propfind_req_t::unknown_count.
Referenced by propfind_do().
propfind_read_doc()
static xmlDocPtr propfind_read_doc (const char * body, size_t body_len) static
Definition at line 83 of file propfind.c.
Referenced by propfind_parse_request().
propfind_walk_root()
static void propfind_walk_root (ngx_http_request_t * r, propfind_req_t * req, xmlNodePtr root) static
Definition at line 192 of file propfind.c.
References PROPFIND_ALLPROP, propfind_collect_props(), PROPFIND_PROP, PROPFIND_PROPNAME, and propfind_req_t::type.
Referenced by propfind_parse_request().
webdav_handle_propfind()
ngx_int_t webdav_handle_propfind (ngx_http_request_t * r)
Definition at line 319 of file propfind.c.
References brix_http_read_body(), and propfind_body_handler().
Referenced by webdav_dispatch_copy_move_props().