nginx-xrootd: src/protocols/webdav/propfind_props_acl.c File Reference
propfind_props_acl.c File Reference
#include "propfind_internal.h"
Functions
static ngx_int_t propfind_emit_owner (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, ngx_http_brix_webdav_req_ctx_t *ctx)
static ngx_int_t propfind_emit_current_privilege (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t propfind_emit_supported_privilege (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail)
static ngx_int_t propfind_emit_acl (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, ngx_http_brix_webdav_loc_conf_t *conf)
ngx_int_t propfind_append_acl_properties (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, unsigned mask)
Function Documentation
propfind_append_acl_properties()
ngx_int_t propfind_append_acl_properties (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, unsigned mask)
Definition at line 171 of file propfind_props_acl.c.
References brix_http_chain_appendf(), ngx_http_brix_webdav_module, PF_ACL, PF_ACL_RESTRICTIONS, PF_CURRENT_PRIVILEGE, PF_GROUP, PF_OWNER, PF_PRINCIPAL_SET, PF_SUPPORTED_PRIVILEGE, propfind_emit_acl(), propfind_emit_current_privilege(), propfind_emit_owner(), and propfind_emit_supported_privilege().
Referenced by propfind_entry().
propfind_emit_acl()
static ngx_int_t propfind_emit_acl (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 134 of file propfind_props_acl.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_http_chain_appendf(), and ngx_http_brix_webdav_loc_conf_t::common.
Referenced by propfind_append_acl_properties().
propfind_emit_current_privilege()
static ngx_int_t propfind_emit_current_privilege (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 45 of file propfind_props_acl.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_http_chain_appendf(), and ngx_http_brix_webdav_loc_conf_t::common.
Referenced by propfind_append_acl_properties().
propfind_emit_owner()
static ngx_int_t propfind_emit_owner (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, ngx_http_brix_webdav_req_ctx_t * ctx) static
Definition at line 16 of file propfind_props_acl.c.
References brix_http_chain_appendf(), ngx_http_brix_webdav_req_ctx_t::dn, and webdav_escape_xml_text().
Referenced by propfind_append_acl_properties().
propfind_emit_supported_privilege()
static ngx_int_t propfind_emit_supported_privilege (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail) static
Definition at line 88 of file propfind_props_acl.c.
References brix_http_chain_appendf().
Referenced by propfind_append_acl_properties().