nginx-xrootd: src/protocols/webdav/propfind_internal.h File Reference
propfind_internal.h File Reference
#include "webdav.h"
#include "fs/vfs/vfs.h"
#include "fs/path/path.h"
#include "auth/impersonate/lifecycle.h"
#include "core/http/etag.h"
#include "core/compat/fs_walk.h"
#include "core/compat/fs_usage.h"
#include "core/http/http_body.h"
#include "core/http/http_xml.h"
#include "core/compat/time.h"
#include <libxml/parser.h>
#include <libxml/tree.h>
#include <dirent.h>
#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
Data Structures
struct propfind_unknown_t
struct propfind_req_t
Macros
#define PF_RESOURCETYPE (1u << 0)
#define PF_CONTENTLENGTH (1u << 1)
#define PF_LASTMODIFIED (1u << 2)
#define PF_ETAG (1u << 3)
#define PF_CREATIONDATE (1u << 4)
#define PF_DISPLAYNAME (1u << 5)
#define PF_QUOTA_AVAILABLE (1u << 6)
#define PF_QUOTA_USED (1u << 7)
#define PF_SUPPORTED_REPORT (1u << 8)
#define PF_SUPPORTEDLOCK (1u << 9)
#define PF_LOCKDISCOVERY (1u << 10)
#define PF_CONTENTTYPE (1u << 11)
#define PF_OWNER (1u << 12)
#define PF_GROUP (1u << 13)
#define PF_CURRENT_PRIVILEGE (1u << 14)
#define PF_SUPPORTED_PRIVILEGE (1u << 15)
#define PF_ACL (1u << 16)
#define PF_ACL_RESTRICTIONS (1u << 17)
#define PF_PRINCIPAL_SET (1u << 18)
#define PF_ALL ((1u << 19) - 1)
#define PF_LOCALITY (1u << 19)
#define PF_UNKNOWN_MAX 16
#define PF_UNKNOWN_XML_MAX 288
#define PROPFIND_BODY_MAX 65536u
#define PROPFIND_INFINITY_MAX_ENTRIES 10000
Enumerations
enum propfind_type_t { PROPFIND_ALLPROP = 0 , PROPFIND_PROPNAME = 1 , PROPFIND_PROP = 2 }
Functions
unsigned propfind_name_to_bit (const char *name)
const char * propfind_assemble_body (ngx_http_request_t *r, size_t *len)
void propfind_parse_request (ngx_http_request_t *r, propfind_req_t *req)
ngx_int_t propfind_append_acl_properties (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, unsigned mask)
ngx_int_t propfind_entry (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, const char *href, const char *path, struct stat *sb, const propfind_req_t *req)
int propfind_parse_depth (ngx_http_request_t *r)
ngx_int_t propfind_walk (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, const char *dir_path, const char *base_href, ngx_uint_t *entry_count, ngx_uint_t max_entries, const propfind_req_t *req, ngx_flag_t recurse)
ngx_int_t propfind_do (ngx_http_request_t *r)
void propfind_body_handler (ngx_http_request_t *r)
Macro Definition Documentation
PF_ACL
#define PF_ACL (1u << 16)
Definition at line 47 of file propfind_internal.h.
PF_ACL_RESTRICTIONS
#define PF_ACL_RESTRICTIONS (1u << 17)
Definition at line 48 of file propfind_internal.h.
PF_ALL
#define PF_ALL ((1u << 19) - 1)
Definition at line 50 of file propfind_internal.h.
PF_CONTENTLENGTH
#define PF_CONTENTLENGTH (1u << 1)
Definition at line 32 of file propfind_internal.h.
PF_CONTENTTYPE
#define PF_CONTENTTYPE (1u << 11)
Definition at line 42 of file propfind_internal.h.
PF_CREATIONDATE
#define PF_CREATIONDATE (1u << 4)
Definition at line 35 of file propfind_internal.h.
PF_CURRENT_PRIVILEGE
#define PF_CURRENT_PRIVILEGE (1u << 14)
Definition at line 45 of file propfind_internal.h.
PF_DISPLAYNAME
#define PF_DISPLAYNAME (1u << 5)
Definition at line 36 of file propfind_internal.h.
PF_ETAG
#define PF_ETAG (1u << 3)
Definition at line 34 of file propfind_internal.h.
PF_GROUP
#define PF_GROUP (1u << 13)
Definition at line 44 of file propfind_internal.h.
PF_LASTMODIFIED
#define PF_LASTMODIFIED (1u << 2)
Definition at line 33 of file propfind_internal.h.
PF_LOCALITY
#define PF_LOCALITY (1u << 19)
Definition at line 51 of file propfind_internal.h.
PF_LOCKDISCOVERY
#define PF_LOCKDISCOVERY (1u << 10)
Definition at line 41 of file propfind_internal.h.
PF_OWNER
#define PF_OWNER (1u << 12)
Definition at line 43 of file propfind_internal.h.
PF_PRINCIPAL_SET
#define PF_PRINCIPAL_SET (1u << 18)
Definition at line 49 of file propfind_internal.h.
PF_QUOTA_AVAILABLE
#define PF_QUOTA_AVAILABLE (1u << 6)
Definition at line 37 of file propfind_internal.h.
PF_QUOTA_USED
#define PF_QUOTA_USED (1u << 7)
Definition at line 38 of file propfind_internal.h.
PF_RESOURCETYPE
#define PF_RESOURCETYPE (1u << 0)
Definition at line 31 of file propfind_internal.h.
PF_SUPPORTED_PRIVILEGE
#define PF_SUPPORTED_PRIVILEGE (1u << 15)
Definition at line 46 of file propfind_internal.h.
PF_SUPPORTED_REPORT
#define PF_SUPPORTED_REPORT (1u << 8)
Definition at line 39 of file propfind_internal.h.
PF_SUPPORTEDLOCK
#define PF_SUPPORTEDLOCK (1u << 9)
Definition at line 40 of file propfind_internal.h.
PF_UNKNOWN_MAX
#define PF_UNKNOWN_MAX 16
Definition at line 52 of file propfind_internal.h.
PF_UNKNOWN_XML_MAX
#define PF_UNKNOWN_XML_MAX 288
Definition at line 53 of file propfind_internal.h.
PROPFIND_BODY_MAX
#define PROPFIND_BODY_MAX 65536u
Definition at line 54 of file propfind_internal.h.
PROPFIND_INFINITY_MAX_ENTRIES
#define PROPFIND_INFINITY_MAX_ENTRIES 10000
Definition at line 68 of file propfind_internal.h.
Enumeration Type Documentation
propfind_type_t
enum propfind_type_t
Enumerator
PROPFIND_ALLPROP
PROPFIND_PROPNAME
PROPFIND_PROP
Definition at line 25 of file propfind_internal.h.
Function Documentation
propfind_append_acl_properties()
ngx_int_t propfind_append_acl_properties (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, unsigned mask)
Definition at line 176 of file propfind_props.c.
References brix_http_chain_appendf(), ngx_http_brix_webdav_module, PF_ACL, PF_ACL_RESTRICTIONS, PF_CURRENT_PRIVILEGE, PF_GROUP, PF_OWNER, PF_PRINCIPAL_SET, PF_SUPPORTED_PRIVILEGE, propfind_emit_acl(), propfind_emit_current_privilege(), propfind_emit_owner(), and propfind_emit_supported_privilege().
Referenced by propfind_entry().
propfind_assemble_body()
const char * propfind_assemble_body (ngx_http_request_t * r, size_t * len)
Definition at line 49 of file propfind.c.
References brix_http_body_read_all(), and PROPFIND_BODY_MAX.
Referenced by propfind_parse_request().
propfind_body_handler()
void propfind_body_handler (ngx_http_request_t * r)
Definition at line 299 of file propfind.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, and propfind_do().
Referenced by webdav_handle_propfind().
propfind_do()
ngx_int_t propfind_do (ngx_http_request_t * r)
Definition at line 455 of file propfind_walk.c.
References BRIX_WEBDAV_METRIC_ADD, propfind_build_body(), propfind_count_depth(), propfind_count_tx(), propfind_finalize_chain(), propfind_parse_depth(), propfind_parse_request(), propfind_send_headers(), propfind_resp_t::r, stat(), WEBDAV_MAX_PATH, and webdav_resolve_stat().
Referenced by propfind_body_handler().
propfind_entry()
ngx_int_t propfind_entry (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, const char * href, const char * path, struct stat * sb, const propfind_req_t * req)
Definition at line 642 of file propfind_props.c.
References brix_http_chain_appendf(), PF_ALL, PF_UNKNOWN_MAX, propfind_req_t::prop_mask, propfind_append_acl_properties(), propfind_dead_props_resolve_and_emit(), propfind_emit_404_propstat(), propfind_emit_standard_props(), PROPFIND_PROP, PROPFIND_PROPNAME, propfind_req_t::type, webdav_dead_props_append_all(), and webdav_escape_xml_text().
Referenced by propfind_build_body(), and propfind_walk_emit().
propfind_name_to_bit()
unsigned propfind_name_to_bit (const char * name)
Definition at line 8 of file propfind.c.
References name, PF_ACL, PF_ACL_RESTRICTIONS, PF_CONTENTLENGTH, PF_CONTENTTYPE, PF_CREATIONDATE, PF_CURRENT_PRIVILEGE, PF_DISPLAYNAME, PF_ETAG, PF_GROUP, PF_LASTMODIFIED, PF_LOCALITY, PF_LOCKDISCOVERY, PF_OWNER, PF_PRINCIPAL_SET, PF_QUOTA_AVAILABLE, PF_QUOTA_USED, PF_RESOURCETYPE, PF_SUPPORTED_PRIVILEGE, PF_SUPPORTED_REPORT, and PF_SUPPORTEDLOCK.
Referenced by propfind_collect_props().
propfind_parse_depth()
int propfind_parse_depth (ngx_http_request_t * r)
Definition at line 270 of file propfind.c.
References brix_http_get_header().
Referenced by propfind_do().
propfind_parse_request()
void propfind_parse_request (ngx_http_request_t * r, propfind_req_t * req)
Definition at line 225 of file propfind.c.
References propfind_req_t::prop_mask, PROPFIND_ALLPROP, propfind_assemble_body(), propfind_read_doc(), propfind_walk_root(), propfind_req_t::type, and propfind_req_t::unknown_count.
Referenced by propfind_do().
propfind_walk()
ngx_int_t propfind_walk (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, const char * dir_path, const char * base_href, ngx_uint_t * entry_count, ngx_uint_t max_entries, const propfind_req_t * req, ngx_flag_t recurse)
Definition at line 194 of file propfind_walk.c.
References brix_dirlist_access_ok(), brix_vfs_closedir(), brix_vfs_opendir(), brix_vfs_readdir(), ngx_http_brix_webdav_loc_conf_t::common, propfind_walk_ctx_t::entry_count, propfind_walk_ctx_t::head, propfind_walk_ctx_t::max_entries, name, ngx_http_brix_webdav_module, propfind_child_visible(), propfind_dir_ctx(), propfind_walk_emit(), propfind_walk_ctx_t::r, propfind_walk_ctx_t::recurse, propfind_walk_ctx_t::req, ngx_http_brix_shared_conf_t::root_canon, and propfind_walk_ctx_t::tail.
Referenced by propfind_build_body(), and propfind_recurse_child().