nginx-xrootd: src/protocols/webdav/prop_xattr.c File Reference
prop_xattr.c File Reference
#include "webdav.h"
#include "fs/path/path.h"
#include "fs/vfs/vfs.h"
#include <sys/xattr.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
Macros
#define ENOATTR ENODATA
Functions
static void webdav_lock_vfs_ctx_init (ngx_http_request_t *r, const char *path, brix_vfs_ctx_t *vctx)
ngx_int_t webdav_lock_xattr_encode (const webdav_lock_xattr_t *e, char *out, size_t outsz)
ngx_int_t webdav_lock_xattr_decode (const char *raw, size_t rawlen, webdav_lock_xattr_t *e)
ngx_int_t webdav_lock_xattr_write (ngx_http_request_t *r, const char *path, const webdav_lock_xattr_t *e, int flags)
ngx_int_t webdav_lock_xattr_read (ngx_http_request_t *r, const char *path, webdav_lock_xattr_t *e)
ngx_int_t webdav_lock_xattr_delete (ngx_http_request_t *r, const char *path)
Macro Definition Documentation
ENOATTR
#define ENOATTR ENODATA
Definition at line 57 of file prop_xattr.c.
Function Documentation
webdav_lock_vfs_ctx_init()
static void webdav_lock_vfs_ctx_init (ngx_http_request_t * r, const char * path, brix_vfs_ctx_t * vctx) static
Definition at line 37 of file prop_xattr.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_WEBDAV, brix_vfs_ctx_init(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, brix_vfs_ctx_t::pool, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by webdav_lock_xattr_delete(), webdav_lock_xattr_read(), and webdav_lock_xattr_write().
webdav_lock_xattr_decode()
ngx_int_t webdav_lock_xattr_decode (const char * raw, size_t rawlen, webdav_lock_xattr_t * e)
Definition at line 82 of file prop_xattr.c.
References webdav_lock_xattr_t::depth_infinity, webdav_lock_xattr_t::exclusive, webdav_lock_xattr_t::expires, webdav_lock_xattr_t::is_null, webdav_lock_xattr_t::owner, webdav_lock_xattr_t::token, and WEBDAV_LOCK_XATTR_MAXLEN.
Referenced by webdav_lock_xattr_read().
webdav_lock_xattr_delete()
ngx_int_t webdav_lock_xattr_delete (ngx_http_request_t * r, const char * path)
Definition at line 211 of file prop_xattr.c.
References brix_vfs_removexattr(), ENOATTR, log, webdav_lock_vfs_ctx_init(), and WEBDAV_LOCK_XATTR_KEY.
Referenced by check_locks_descendants(), webdav_check_locks(), webdav_handle_lock_inner(), webdav_handle_unlock(), and webdav_lock_append_discovery().
webdav_lock_xattr_encode()
ngx_int_t webdav_lock_xattr_encode (const webdav_lock_xattr_t * e, char * out, size_t outsz)
Definition at line 61 of file prop_xattr.c.
References webdav_lock_xattr_t::depth_infinity, webdav_lock_xattr_t::exclusive, webdav_lock_xattr_t::expires, webdav_lock_xattr_t::is_null, webdav_lock_xattr_t::owner, and webdav_lock_xattr_t::token.
Referenced by webdav_lock_xattr_write().
webdav_lock_xattr_read()
ngx_int_t webdav_lock_xattr_read (ngx_http_request_t * r, const char * path, webdav_lock_xattr_t * e)
Definition at line 182 of file prop_xattr.c.
References brix_vfs_getxattr(), ENOATTR, log, webdav_lock_vfs_ctx_init(), webdav_lock_xattr_decode(), WEBDAV_LOCK_XATTR_KEY, and WEBDAV_LOCK_XATTR_MAXLEN.
Referenced by check_locks_descendants(), webdav_check_locks(), webdav_handle_lock_inner(), webdav_handle_unlock(), and webdav_lock_append_discovery().
webdav_lock_xattr_write()
ngx_int_t webdav_lock_xattr_write (ngx_http_request_t * r, const char * path, const webdav_lock_xattr_t * e, int flags)
Definition at line 152 of file prop_xattr.c.
References brix_vfs_setxattr(), log, webdav_lock_vfs_ctx_init(), webdav_lock_xattr_encode(), WEBDAV_LOCK_XATTR_KEY, and WEBDAV_LOCK_XATTR_MAXLEN.
Referenced by webdav_handle_lock_inner().