nginx-xrootd: src/protocols/webdav/propfind_walk.c File Reference
propfind_walk.c File Reference
#include "propfind_internal.h"
#include "fs/vfs/vfs.h"
#include "fs/path/reserved_names.h"
Functions
static void propfind_vfs_to_stat (const brix_vfs_stat_t *vs, struct stat *st)
static void propfind_dir_ctx (ngx_http_request_t *r, const char *root_canon, const char *dir_path, brix_vfs_ctx_t *vctx)
ngx_int_t propfind_walk (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, const char *dir_path, const char *base_href, ngx_uint_t *entry_count, ngx_uint_t max_entries, const propfind_req_t *req, ngx_flag_t recurse)
ngx_int_t propfind_do (ngx_http_request_t *r)
Function Documentation
propfind_dir_ctx()
static void propfind_dir_ctx (ngx_http_request_t * r, const char * root_canon, const char * dir_path, brix_vfs_ctx_t * vctx) static
Definition at line 28 of file propfind_walk.c.
References BRIX_PROTO_WEBDAV, brix_vfs_ctx_init(), and brix_vfs_ctx_t::pool.
Referenced by propfind_walk().
propfind_do()
ngx_int_t propfind_do (ngx_http_request_t * r)
Definition at line 188 of file propfind_walk.c.
References brix_http_chain_appendf(), BRIX_WEBDAV_METRIC_ADD, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_PROPFIND_DEPTH_0, BRIX_WEBDAV_PROPFIND_DEPTH_1, BRIX_WEBDAV_PROPFIND_DEPTH_INF, propfind_entry(), PROPFIND_INFINITY_MAX_ENTRIES, propfind_parse_depth(), propfind_parse_request(), propfind_walk(), stat(), WEBDAV_MAX_PATH, and webdav_resolve_stat().
Referenced by propfind_body_handler().
propfind_vfs_to_stat()
static void propfind_vfs_to_stat (const brix_vfs_stat_t * vs, struct stat * st) static
Definition at line 14 of file propfind_walk.c.
References brix_vfs_stat_t::ctime, brix_vfs_stat_t::ino, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, and brix_vfs_stat_t::size.
Referenced by propfind_walk().
propfind_walk()
ngx_int_t propfind_walk (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, const char * dir_path, const char * base_href, ngx_uint_t * entry_count, ngx_uint_t max_entries, const propfind_req_t * req, ngx_flag_t recurse)
Definition at line 57 of file propfind_walk.c.
References brix_dirlist_access_ok(), brix_fs_join_path(), brix_is_internal_name(), brix_vfs_closedir(), brix_vfs_opendir(), brix_vfs_readdir(), ngx_http_brix_webdav_loc_conf_t::common, name, ngx_http_brix_webdav_module, propfind_dir_ctx(), propfind_entry(), propfind_vfs_to_stat(), propfind_walk(), ngx_http_brix_shared_conf_t::root_canon, stat(), and WEBDAV_MAX_PATH.
Referenced by propfind_do(), and propfind_walk().