nginx-xrootd: src/protocols/root/connection/recv.c File Reference
recv.c File Reference
#include "core/ngx_brix_module.h"
#include "disconnect.h"
#include "fd_table.h"
#include "tls.h"
#include "budget.h"
#include "deadline.h"
#include "net/manager/pending.h"
#include "fs/xfer/stage_waiter.h"
#include "protocols/root/handoff/handoff.h"
Enumerations
enum { BRIX_RECV_PROCEED = 0 , BRIX_RECV_RETURN , BRIX_RECV_BREAK }
Functions
static uint32_t brix_max_payload_for_request (uint16_t reqid)
static ngx_int_t brix_ensure_payload_buffer (brix_ctx_t *ctx, ngx_connection_t *c, uint32_t dlen)
static ngx_int_t brix_grow_payload_buffer (brix_ctx_t *ctx, ngx_connection_t *c, uint32_t dlen)
static int brix_recv_pre_loop (ngx_stream_session_t *s, ngx_connection_t *c, brix_ctx_t *ctx, ngx_event_t *rev)
static int brix_recv_handoff_state (brix_ctx_t *ctx, ngx_event_t *rev)
void ngx_stream_brix_recv (ngx_event_t *rev)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BRIX_RECV_PROCEED
BRIX_RECV_RETURN
BRIX_RECV_BREAK
Definition at line 217 of file recv.c.
Function Documentation
brix_ensure_payload_buffer()
static ngx_int_t brix_ensure_payload_buffer (brix_ctx_t * ctx, ngx_connection_t * c, uint32_t dlen) static
Definition at line 55 of file recv.c.
References c, brix_ctx_recv_t::payload, brix_ctx_recv_t::payload_buf, brix_ctx_recv_t::payload_buf_size, and brix_ctx_t::recv.
Referenced by ngx_stream_brix_recv().
brix_grow_payload_buffer()
static ngx_int_t brix_grow_payload_buffer (brix_ctx_t * ctx, ngx_connection_t * c, uint32_t dlen) static
Definition at line 99 of file recv.c.
References c, brix_ctx_recv_t::payload, brix_ctx_recv_t::payload_buf, brix_ctx_recv_t::payload_buf_size, brix_ctx_recv_t::payload_pos, and brix_ctx_t::recv.
Referenced by ngx_stream_brix_recv().
brix_max_payload_for_request()
static uint32_t brix_max_payload_for_request (uint16_t reqid) static
Definition at line 22 of file recv.c.
References BRIX_MAX_AUTH_PAYLOAD, BRIX_MAX_PATH, BRIX_MAX_PREPARE_PAYLOAD, BRIX_MAX_WRITE_PAYLOAD, BRIX_READV_MAXSEGS, BRIX_READV_SEGSIZE, kXR_auth, kXR_chkpoint, kXR_pgwrite, kXR_prepare, kXR_readv, kXR_write, and kXR_writev.
Referenced by ngx_stream_brix_recv().
brix_recv_handoff_state()
static int brix_recv_handoff_state (brix_ctx_t * ctx, ngx_event_t * rev) static
Definition at line 231 of file recv.c.
References BRIX_RECV_BREAK, BRIX_RECV_PROCEED, BRIX_RECV_RETURN, brix_ctx_t::state, XRD_ST_AIO, XRD_ST_PROXY, XRD_ST_SENDING, XRD_ST_TLS_HANDSHAKE, XRD_ST_UPSTREAM, XRD_ST_WAITING_CMS, and XRD_ST_WAITING_FRM.
Referenced by ngx_stream_brix_recv().
brix_recv_pre_loop()
static int brix_recv_pre_loop (ngx_stream_session_t * s, ngx_connection_t * c, brix_ctx_t * ctx, ngx_event_t * rev) static
Definition at line 148 of file recv.c.
References brix_ctx_login_t::auth_done, brix_close_all_files(), brix_defer_teardown_if_writing(), brix_on_disconnect(), brix_pending_remove(), brix_schedule_read_resume(), brix_send_wait(), BRIX_SRV_METRIC_INC, brix_stage_waiter_drop_conn(), c, brix_ctx_t::cms_wait_streamid, brix_ctx_t::deadline, brix_ctx_t::login, brix_ctx_deadline_t::read_armed, s, brix_ctx_t::state, XRD_ST_REQ_HEADER, XRD_ST_WAITING_CMS, and XRD_ST_WAITING_FRM.
Referenced by ngx_stream_brix_recv().
ngx_stream_brix_recv()
void ngx_stream_brix_recv (ngx_event_t * rev)
Definition at line 253 of file recv.c.
References ClientRequestHdr::body, brix_arm_read_deadline(), brix_budget_sync(), brix_ckpxeq_body_extra(), brix_close_all_files(), brix_ctx_has_open_file(), brix_defer_teardown_if_writing(), brix_disarm_read_deadline(), brix_dispatch(), brix_ensure_payload_buffer(), brix_grow_payload_buffer(), brix_http_handoff_start(), brix_max_payload_for_request(), brix_on_disconnect(), brix_process_handshake(), BRIX_RECV_BREAK, brix_recv_handoff_state(), brix_recv_pre_loop(), BRIX_RECV_RETURN, BRIX_SRV_METRIC_ADD, BRIX_SRV_METRIC_INC, brix_start_tls(), brix_trim_scratch(), brix_writev_body_extra(), c, brix_ctx_out_t::count, brix_ctx_recv_t::cur_body, brix_ctx_recv_t::cur_body_extended, brix_ctx_recv_t::cur_body_extra, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, brix_ctx_recv_t::cur_streamid, ClientRequestHdr::dlen, brix_ctx_recv_t::hdr_buf, brix_ctx_recv_t::hdr_pos, ngx_stream_brix_srv_conf_t::http_handoff_addr, kXR_chkpoint, kXR_ckpXeq, kXR_read, kXR_write, kXR_writev, ngx_stream_brix_module, brix_ctx_t::out, brix_ctx_recv_t::payload, brix_ctx_recv_t::payload_pos, brix_ctx_out_t::pipeline_depth, brix_ctx_t::rd, brix_ctx_t::recv, brix_ctx_out_t::recv_deferred, ClientRequestHdr::requestid, brix_ctx_out_t::resp_pipelinable, s, brix_ctx_t::state, ClientRequestHdr::streamid, brix_ctx_t::tls_pending, brix_ctx_rd_t::win_active, brix_ctx_out_t::wr_inflight, XRD_HANDSHAKE_LEN, XRD_REQUEST_HDR_LEN, XRD_ST_AIO, XRD_ST_HANDSHAKE, XRD_ST_REQ_HEADER, XRD_ST_REQ_PAYLOAD, and XRD_ST_SENDING.
Referenced by brix_tls_handshake_done(), ngx_stream_brix_handler(), and ngx_stream_brix_send().