nginx-xrootd: src/protocols/root/connection/handler.c File Reference
handler.c File Reference
#include "core/ngx_brix_module.h"
#include <netinet/tcp.h>
#include "netopt.h"
#include "protocols/root/relay/relay.h"
#include "observability/sesslog/sesslog_ngx.h"
#include "core/aio/uring.h"
Functions
static void conn_set_immutable_labels (ngx_connection_t *c, brix_ctx_t *ctx)
static ngx_int_t conn_init_slots_and_sessid (ngx_connection_t *c, brix_ctx_t *ctx)
static brix_ctx_t * conn_init_ctx (ngx_stream_session_t *s, ngx_connection_t *c)
static ngx_int_t conn_setup_pipeline (ngx_stream_session_t *s, ngx_connection_t *c, brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *mconf)
static const char * conn_metrics_auth_label (ngx_uint_t auth)
static void conn_metrics_set_port (ngx_connection_t *c, ngx_brix_srv_metrics_t *srv)
static void conn_metrics_set_upstreams (ngx_stream_brix_srv_conf_t *mconf, ngx_brix_srv_metrics_t *srv)
static void conn_metrics_init_labels (ngx_connection_t *c, ngx_stream_brix_srv_conf_t *mconf, ngx_brix_srv_metrics_t *srv)
static ngx_brix_srv_metrics_t * conn_metrics_row (ngx_stream_brix_srv_conf_t *mconf)
static ngx_int_t conn_register_metrics (ngx_stream_session_t *s, ngx_connection_t *c, brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *mconf)
static ngx_int_t conn_apply_srv_conf (ngx_stream_session_t *s, ngx_connection_t *c, brix_ctx_t *ctx)
static ngx_int_t conn_try_relay (ngx_stream_session_t *s, ngx_connection_t *c)
static void conn_begin_session (ngx_stream_session_t *s, ngx_connection_t *c, brix_ctx_t *ctx)
static void conn_pump (ngx_connection_t *c)
void ngx_stream_brix_handler (ngx_stream_session_t *s)
Function Documentation
conn_apply_srv_conf()
static ngx_int_t conn_apply_srv_conf (ngx_stream_session_t * s, ngx_connection_t * c, brix_ctx_t * ctx) static
Definition at line 380 of file handler.c.
References brix_apply_tcp_congestion(), brix_apply_tcp_deadpeer_opts(), c, conn_register_metrics(), conn_setup_pipeline(), ngx_stream_brix_module, and s.
Referenced by ngx_stream_brix_handler().
conn_begin_session()
static void conn_begin_session (ngx_stream_session_t * s, ngx_connection_t * c, brix_ctx_t * ctx) static
Definition at line 440 of file handler.c.
References brix_sess_am_from_stream_auth(), brix_sess_begin(), BRIX_SESS_DIR_IN, BRIX_SESS_PROTO_ROOT, c, ngx_stream_brix_module, s, and brix_ctx_t::sess.
Referenced by ngx_stream_brix_handler().
conn_init_ctx()
static brix_ctx_t * conn_init_ctx (ngx_stream_session_t * s, ngx_connection_t * c) static
Definition at line 127 of file handler.c.
References brix_identity_alloc(), c, conn_init_slots_and_sessid(), conn_set_immutable_labels(), brix_ctx_recv_t::hdr_pos, brix_ctx_t::identity, ngx_pcalloc(), ngx_stream_brix_module, brix_ctx_t::recv, s, brix_ctx_t::session, brix_ctx_t::state, and XRD_ST_HANDSHAKE.
Referenced by ngx_stream_brix_handler().
conn_init_slots_and_sessid()
static ngx_int_t conn_init_slots_and_sessid (ngx_connection_t * c, brix_ctx_t * ctx) static
Definition at line 98 of file handler.c.
References BRIX_MAX_FILES, BRIX_SESSION_ID_LEN, c, brix_file_t::fd, brix_ctx_t::files, brix_ctx_t::login, brix_ctx_login_t::sessid, and brix_file_t::shared_handle_slot_hint.
Referenced by conn_init_ctx().
conn_metrics_auth_label()
static const char * conn_metrics_auth_label (ngx_uint_t auth) static
Definition at line 199 of file handler.c.
References BRIX_AUTH_GSI, BRIX_AUTH_KRB5, BRIX_AUTH_SSS, BRIX_AUTH_TOKEN, and BRIX_AUTH_UNIX.
Referenced by conn_metrics_init_labels().
conn_metrics_init_labels()
static void conn_metrics_init_labels (ngx_connection_t * c, ngx_stream_brix_srv_conf_t * mconf, ngx_brix_srv_metrics_t * srv) static
Definition at line 274 of file handler.c.
References ngx_brix_srv_metrics_t::auth, c, conn_metrics_auth_label(), conn_metrics_set_port(), conn_metrics_set_upstreams(), and ngx_brix_srv_metrics_t::in_use.
Referenced by conn_register_metrics().
conn_metrics_row()
static ngx_brix_srv_metrics_t * conn_metrics_row (ngx_stream_brix_srv_conf_t * mconf) static
Definition at line 298 of file handler.c.
References ngx_brix_shm_zone, and ngx_brix_metrics_t::servers.
Referenced by conn_register_metrics().
conn_metrics_set_port()
static void conn_metrics_set_port (ngx_connection_t * c, ngx_brix_srv_metrics_t * srv) static
Definition at line 217 of file handler.c.
References c, and ngx_brix_srv_metrics_t::port.
Referenced by conn_metrics_init_labels().
conn_metrics_set_upstreams()
static void conn_metrics_set_upstreams (ngx_stream_brix_srv_conf_t * mconf, ngx_brix_srv_metrics_t * srv) static
Definition at line 243 of file handler.c.
References BRIX_PROXY_MAX_UPSTREAMS, BRIX_PROXY_UPSTREAM_LABEL_LEN, brix_proxy_upstream_t::host, ngx_brix_proxy_upstream_metrics_t::label, brix_proxy_upstream_t::port, ngx_brix_srv_metrics_t::proxy, and ngx_brix_proxy_metrics_t::upstreams.
Referenced by conn_metrics_init_labels().
conn_pump()
static void conn_pump (ngx_connection_t * c) static
Definition at line 471 of file handler.c.
References c, ngx_stream_brix_recv(), and ngx_stream_brix_send().
Referenced by ngx_stream_brix_handler().
conn_register_metrics()
static ngx_int_t conn_register_metrics (ngx_stream_session_t * s, ngx_connection_t * c, brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * mconf) static
Definition at line 322 of file handler.c.
References c, ngx_brix_srv_metrics_t::cache_enabled, ngx_brix_srv_metrics_t::cache_eviction_threshold, ngx_brix_srv_metrics_t::cache_root, conn_metrics_init_labels(), conn_metrics_row(), ngx_brix_srv_metrics_t::connections_active, ngx_brix_srv_metrics_t::connections_rejected_total, ngx_brix_srv_metrics_t::connections_total, brix_ctx_t::metrics, ngx_memcpy, and s.
Referenced by conn_apply_srv_conf().
conn_set_immutable_labels()
static void conn_set_immutable_labels (ngx_connection_t * c, brix_ctx_t * ctx) static
Definition at line 54 of file handler.c.
References c, brix_ctx_t::ip_version, brix_ctx_t::login, ngx_memcpy, brix_ctx_login_t::peer_ip, and brix_ctx_t::protocol_label.
Referenced by conn_init_ctx().
conn_setup_pipeline()
static ngx_int_t conn_setup_pipeline (ngx_stream_session_t * s, ngx_connection_t * c, brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * mconf) static
Definition at line 171 of file handler.c.
References c, brix_ctx_t::deadline, brix_ctx_deadline_t::handshake_ms, ngx_pcalloc(), brix_ctx_t::out, brix_ctx_out_t::pipeline_depth, brix_ctx_rd_t::pool, brix_ctx_t::rd, brix_ctx_deadline_t::read_ms, brix_ctx_out_t::ring, s, and brix_ctx_deadline_t::send_ms.
Referenced by conn_apply_srv_conf().
conn_try_relay()
static ngx_int_t conn_try_relay (ngx_stream_session_t * s, ngx_connection_t * c) static
Definition at line 417 of file handler.c.
References brix_relay_start(), c, ngx_stream_brix_module, and s.
Referenced by ngx_stream_brix_handler().
ngx_stream_brix_handler()
void ngx_stream_brix_handler (ngx_stream_session_t * s)
Definition at line 489 of file handler.c.
References c, conn_apply_srv_conf(), conn_begin_session(), conn_init_ctx(), conn_pump(), conn_try_relay(), and s.
Referenced by ngx_stream_brix_enable().