nginx-xrootd: src/protocols/root/path/extract.c File Reference
extract.c File Reference
#include "core/ngx_brix_module.h"
#include <string.h>
Functions
int brix_extract_path (ngx_log_t *log, const u_char *payload, size_t payload_len, char *out, size_t outsz, ngx_flag_t strip_cgi)
Function Documentation
brix_extract_path()
int brix_extract_path (ngx_log_t * log, const u_char * payload, size_t payload_len, char * out, size_t outsz, ngx_flag_t strip_cgi)
Definition at line 12 of file extract.c.
References BRIX_MAX_PATH, log, and ngx_memcpy.
Referenced by brix_dirlist_parse_request(), brix_handle_link(), brix_handle_open(), brix_handle_setattr(), brix_handle_symlink(), brix_open_precheck(), brix_prepare_check_path(), brix_qcksum_resolve(), brix_query_ckscan(), brix_query_opaquf(), brix_query_xattr(), brix_resolve_op_path(), brix_upstream_start_snapshot_request(), fattr_path_target(), locate_resolve_reqpath(), manager_redirect_mutation(), mv_parse_paths(), qprep_emit_all(), stat_query_path(), and tpc_handle_dest().