nginx-xrootd: src/protocols/webdav/delegation.c File Reference
delegation.c File Reference
#include "webdav.h"
#include "delegation.h"
#include "fs/backend/ucred.h"
#include "auth/crypto/store_policy.h"
#include "auth/gsi/proxy_req.h"
#include "auth/crypto/gsi_verify.h"
#include "core/compat/log_diag.h"
#include "core/compat/hex.h"
#include "core/http/http_body.h"
#include <openssl/bio.h>
#include <openssl/pem.h>
#include <openssl/rand.h>
#include <openssl/ssl.h>
#include <openssl/x509.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct brix_deleg_entry_t
struct brix_deleg_store_t
Macros
#define BRIX_DELEGATION_BODY_MAX (64 * 1024)
#define BRIX_DELEGATION_CSR_MAX (16 * 1024)
#define BRIX_DELEG_ID_BYTES 16
#define BRIX_DELEG_ID_HEXLEN (BRIX_DELEG_ID_BYTES * 2)
#define BRIX_DELEG_STORE_CAP 256
#define BRIX_DELEG_TTL_SEC 600
Enumerations
enum brix_deleg_take_t { BRIX_DELEG_TAKE_NOT_FOUND = 0 , BRIX_DELEG_TAKE_EXPIRED , BRIX_DELEG_TAKE_DN_MISMATCH , BRIX_DELEG_TAKE_OK }
Functions
static int delegation_client_authenticated (const ngx_http_brix_webdav_req_ctx_t *ctx)
static X509 * delegation_find_eec (STACK_OF(X509) *chain)
static STACK_OF (X509)
static int delegation_chain_expired (STACK_OF(X509) *chain)
static int delegation_eec_dn_matches (X509 *eec, const char *want_dn)
static ngx_int_t delegation_chain_trusted (ngx_http_request_t *r, const ngx_http_brix_webdav_loc_conf_t *conf, STACK_OF(X509) *chain)
static ngx_int_t delegation_store_pem (ngx_log_t *log, const ngx_str_t *dir, const char *key, const u_char *pem, size_t pem_len)
static void delegation_reject (ngx_http_request_t *r, ngx_uint_t status, const char *msg)
static brix_deleg_store_t * brix_deleg_store (void)
static void brix_deleg_entry_free (brix_deleg_entry_t *e)
static void brix_deleg_store_sweep (brix_deleg_store_t *st, time_t now)
static ngx_int_t brix_deleg_store_put (brix_deleg_store_t *st, EVP_PKEY *fresh_key, const char *client_dn, char *id_out, size_t id_out_cap)
static brix_deleg_take_t brix_deleg_store_take (brix_deleg_store_t *st, const char *id, const char *want_dn, EVP_PKEY **key_out)
static ngx_int_t delegation_get_peer_pem (ngx_http_request_t *r, u_char **pem, size_t *pem_len)
static u_char * delegation_req_der_to_pem (const uint8_t *der, size_t der_len, size_t *pem_len)
static ngx_int_t delegation_send_csr (ngx_http_request_t *r, const char *id, const u_char *pem, size_t pem_len)
static ngx_int_t delegation_request_reject (ngx_http_request_t *r, ngx_uint_t status, const char *msg)
ngx_int_t webdav_delegation_request_handle (ngx_http_request_t *r)
static u_char * gsi_pem_export_one (X509 *cert, size_t *len)
static u_char * gsi_pem_export_chain (STACK_OF(X509) *chain, size_t *len)
static ngx_int_t delegation_split_first_pem_block (const u_char *body, size_t body_len, u_char **proxy_pem, size_t *proxy_pem_len, u_char **chain_pem, size_t *chain_pem_len)
static ngx_int_t delegation_extract_id (ngx_http_request_t *r, const u_char **id, size_t *id_len)
static ngx_int_t delegation_put_take_key (ngx_http_request_t *r, const ngx_http_brix_webdav_req_ctx_t *ctx, const char *id, EVP_PKEY **reqkey)
static ngx_int_t delegation_put_assemble (ngx_http_request_t *r, const char *id, EVP_PKEY *reqkey, const u_char *body, size_t body_len, uint8_t **out_pem, size_t *out_len)
static ngx_int_t delegation_put_validate_chain (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const ngx_http_brix_webdav_req_ctx_t *ctx, const char *id, const uint8_t *out_pem, size_t out_len)
static ngx_int_t delegation_put_store (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const ngx_http_brix_webdav_req_ctx_t *ctx, const uint8_t *out_pem, size_t out_len, char *key, size_t key_len)
void webdav_delegation_put_handle (ngx_http_request_t *r)
static void delegation_validate_and_store (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const ngx_http_brix_webdav_req_ctx_t *ctx, const u_char *body, size_t body_len)
void webdav_delegation_handle (ngx_http_request_t *r)
Variables
static brix_deleg_store_t * brix_deleg_store_singleton = NULL
Macro Definition Documentation
BRIX_DELEG_ID_BYTES
#define BRIX_DELEG_ID_BYTES 16
Definition at line 487 of file delegation.c.
BRIX_DELEG_ID_HEXLEN
#define BRIX_DELEG_ID_HEXLEN (BRIX_DELEG_ID_BYTES * 2)
Definition at line 488 of file delegation.c.
BRIX_DELEG_STORE_CAP
#define BRIX_DELEG_STORE_CAP 256
Definition at line 493 of file delegation.c.
BRIX_DELEG_TTL_SEC
#define BRIX_DELEG_TTL_SEC 600
Definition at line 498 of file delegation.c.
BRIX_DELEGATION_BODY_MAX
#define BRIX_DELEGATION_BODY_MAX (64 * 1024)
Definition at line 157 of file delegation.c.
BRIX_DELEGATION_CSR_MAX
#define BRIX_DELEGATION_CSR_MAX (16 * 1024)
Definition at line 160 of file delegation.c.
Enumeration Type Documentation
brix_deleg_take_t
enum brix_deleg_take_t
Enumerator
BRIX_DELEG_TAKE_NOT_FOUND
BRIX_DELEG_TAKE_EXPIRED
BRIX_DELEG_TAKE_DN_MISMATCH
BRIX_DELEG_TAKE_OK
Definition at line 624 of file delegation.c.
Function Documentation
brix_deleg_entry_free()
static void brix_deleg_entry_free (brix_deleg_entry_t * e) static
Definition at line 534 of file delegation.c.
References brix_deleg_entry_t::client_dn, brix_deleg_entry_t::created_at, brix_deleg_entry_t::expires_at, brix_deleg_entry_t::fresh_key, and brix_deleg_entry_t::id.
Referenced by brix_deleg_store_sweep(), and brix_deleg_store_take().
brix_deleg_store()
static brix_deleg_store_t * brix_deleg_store (void) static
Definition at line 518 of file delegation.c.
References brix_deleg_store_singleton, and ngx_pcalloc().
Referenced by delegation_put_take_key(), and webdav_delegation_request_handle().
brix_deleg_store_put()
static ngx_int_t brix_deleg_store_put (brix_deleg_store_t * st, EVP_PKEY * fresh_key, const char * client_dn, char * id_out, size_t id_out_cap) static
Definition at line 586 of file delegation.c.
References BRIX_DELEG_ID_BYTES, BRIX_DELEG_ID_HEXLEN, BRIX_DELEG_STORE_CAP, brix_deleg_store_sweep(), BRIX_DELEG_TTL_SEC, brix_hex_encode(), brix_deleg_entry_t::client_dn, brix_deleg_entry_t::created_at, brix_deleg_entry_t::expires_at, brix_deleg_entry_t::fresh_key, hex(), brix_deleg_entry_t::id, ngx_memcpy, and brix_deleg_store_t::slots.
Referenced by webdav_delegation_request_handle().
brix_deleg_store_sweep()
static void brix_deleg_store_sweep (brix_deleg_store_t * st, time_t now) static
Definition at line 553 of file delegation.c.
References brix_deleg_entry_free(), BRIX_DELEG_STORE_CAP, brix_deleg_entry_t::expires_at, brix_deleg_entry_t::id, and brix_deleg_store_t::slots.
Referenced by brix_deleg_store_put(), and brix_deleg_store_take().
brix_deleg_store_take()
static brix_deleg_take_t brix_deleg_store_take (brix_deleg_store_t * st, const char * id, const char * want_dn, EVP_PKEY ** key_out) static
Definition at line 667 of file delegation.c.
References brix_deleg_entry_free(), BRIX_DELEG_STORE_CAP, brix_deleg_store_sweep(), BRIX_DELEG_TAKE_DN_MISMATCH, BRIX_DELEG_TAKE_EXPIRED, BRIX_DELEG_TAKE_NOT_FOUND, BRIX_DELEG_TAKE_OK, brix_deleg_entry_t::client_dn, brix_deleg_entry_t::expires_at, brix_deleg_entry_t::fresh_key, brix_deleg_entry_t::id, and brix_deleg_store_t::slots.
Referenced by delegation_put_take_key().
delegation_chain_expired()
static int delegation_chain_expired (STACK_OF(X509) * chain) static
Definition at line 244 of file delegation.c.
Referenced by delegation_put_validate_chain(), and delegation_validate_and_store().
delegation_chain_trusted()
static ngx_int_t delegation_chain_trusted (ngx_http_request_t * r, const ngx_http_brix_webdav_loc_conf_t * conf, STACK_OF(X509) * chain) static
Definition at line 301 of file delegation.c.
References brix_gsi_verify_chain(), ngx_http_brix_webdav_loc_conf_t::ca_store, and ngx_http_brix_webdav_loc_conf_t::verify_depth.
Referenced by delegation_put_validate_chain(), and delegation_validate_and_store().
delegation_client_authenticated()
static int delegation_client_authenticated (const ngx_http_brix_webdav_req_ctx_t * ctx) static
Definition at line 168 of file delegation.c.
References ngx_http_brix_webdav_req_ctx_t::dn, ngx_http_brix_webdav_req_ctx_t::token_auth, and ngx_http_brix_webdav_req_ctx_t::verified.
Referenced by webdav_delegation_handle(), webdav_delegation_put_handle(), and webdav_delegation_request_handle().
delegation_eec_dn_matches()
static int delegation_eec_dn_matches (X509 * eec, const char * want_dn) static
Definition at line 264 of file delegation.c.
References brix_x509_oneline().
Referenced by delegation_put_validate_chain(), and delegation_validate_and_store().
delegation_extract_id()
static ngx_int_t delegation_extract_id (ngx_http_request_t * r, const u_char ** id, size_t * id_len) static
Definition at line 1111 of file delegation.c.
References BRIX_DELEG_ID_HEXLEN.
Referenced by webdav_delegation_put_handle().
delegation_find_eec()
static X509 * delegation_find_eec (STACK_OF(X509) * chain) static
Definition at line 184 of file delegation.c.
References brix_px_classify(), and BRIX_PX_NONE.
Referenced by delegation_put_validate_chain(), and delegation_validate_and_store().
delegation_get_peer_pem()
static ngx_int_t delegation_get_peer_pem (ngx_http_request_t * r, u_char ** pem, size_t * pem_len) static
Definition at line 711 of file delegation.c.
Referenced by webdav_delegation_request_handle().
delegation_put_assemble()
static ngx_int_t delegation_put_assemble (ngx_http_request_t * r, const char * id, EVP_PKEY * reqkey, const u_char * body, size_t body_len, uint8_t ** out_pem, size_t * out_len) static
Definition at line 1178 of file delegation.c.
References brix_gsi_assemble_proxy(), brix_gsi_buf_t::data, delegation_reject(), delegation_split_first_pem_block(), and brix_gsi_buf_t::len.
Referenced by webdav_delegation_put_handle().
delegation_put_store()
static ngx_int_t delegation_put_store (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const ngx_http_brix_webdav_req_ctx_t * ctx, const uint8_t * out_pem, size_t out_len, char * key, size_t key_len) static
Definition at line 1272 of file delegation.c.
References brix_sd_ucred_key(), ngx_http_brix_webdav_loc_conf_t::common, delegation_reject(), delegation_store_pem(), ngx_http_brix_webdav_req_ctx_t::dn, key, and ngx_http_brix_shared_conf_t::storage_credential_dir.
Referenced by webdav_delegation_put_handle().
delegation_put_take_key()
static ngx_int_t delegation_put_take_key (ngx_http_request_t * r, const ngx_http_brix_webdav_req_ctx_t * ctx, const char * id, EVP_PKEY ** reqkey) static
Definition at line 1144 of file delegation.c.
References brix_deleg_store(), brix_deleg_store_take(), BRIX_DELEG_TAKE_EXPIRED, BRIX_DELEG_TAKE_NOT_FOUND, BRIX_DELEG_TAKE_OK, brix_sanitize_log_string(), delegation_reject(), and ngx_http_brix_webdav_req_ctx_t::dn.
Referenced by webdav_delegation_put_handle().
delegation_put_validate_chain()
static ngx_int_t delegation_put_validate_chain (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const ngx_http_brix_webdav_req_ctx_t * ctx, const char * id, const uint8_t * out_pem, size_t out_len) static
Definition at line 1222 of file delegation.c.
References delegation_chain_expired(), delegation_chain_trusted(), delegation_eec_dn_matches(), delegation_find_eec(), delegation_reject(), ngx_http_brix_webdav_req_ctx_t::dn, and STACK_OF().
Referenced by webdav_delegation_put_handle().
delegation_reject()
static void delegation_reject (ngx_http_request_t * r, ngx_uint_t status, const char * msg) static
Definition at line 413 of file delegation.c.
References ngx_memcpy, ngx_pcalloc(), ngx_pnalloc(), and webdav_metrics_finalize_request().
Referenced by delegation_put_assemble(), delegation_put_store(), delegation_put_take_key(), delegation_put_validate_chain(), delegation_validate_and_store(), webdav_delegation_handle(), and webdav_delegation_put_handle().
delegation_req_der_to_pem()
static u_char * delegation_req_der_to_pem (const uint8_t * der, size_t der_len, size_t * pem_len) static
Definition at line 759 of file delegation.c.
Referenced by webdav_delegation_request_handle().
delegation_request_reject()
static ngx_int_t delegation_request_reject (ngx_http_request_t * r, ngx_uint_t status, const char * msg) static
Definition at line 866 of file delegation.c.
References ngx_memcpy, ngx_pcalloc(), and ngx_pnalloc().
Referenced by webdav_delegation_request_handle().
delegation_send_csr()
static ngx_int_t delegation_send_csr (ngx_http_request_t * r, const char * id, const u_char * pem, size_t pem_len) static
Definition at line 804 of file delegation.c.
References ngx_memcpy, ngx_pcalloc(), and ngx_pnalloc().
Referenced by webdav_delegation_request_handle().
delegation_split_first_pem_block()
static ngx_int_t delegation_split_first_pem_block (const u_char * body, size_t body_len, u_char ** proxy_pem, size_t * proxy_pem_len, u_char ** chain_pem, size_t * chain_pem_len) static
Definition at line 1051 of file delegation.c.
References gsi_pem_export_chain(), gsi_pem_export_one(), and STACK_OF().
Referenced by delegation_put_assemble().
delegation_store_pem()
static ngx_int_t delegation_store_pem (ngx_log_t * log, const ngx_str_t * dir, const char * key, const u_char * pem, size_t pem_len) static
Definition at line 343 of file delegation.c.
References close(), key, log, and open().
Referenced by delegation_put_store(), and delegation_validate_and_store().
delegation_validate_and_store()
static void delegation_validate_and_store (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const ngx_http_brix_webdav_req_ctx_t * ctx, const u_char * body, size_t body_len) static
Definition at line 1376 of file delegation.c.
References brix_sanitize_log_string(), brix_sd_ucred_key(), BRIX_UCRED_KEY_MAX, ngx_http_brix_webdav_loc_conf_t::common, delegation_chain_expired(), delegation_chain_trusted(), delegation_eec_dn_matches(), delegation_find_eec(), delegation_reject(), delegation_store_pem(), ngx_http_brix_webdav_req_ctx_t::dn, key, STACK_OF(), and ngx_http_brix_shared_conf_t::storage_credential_dir.
Referenced by webdav_delegation_handle().
gsi_pem_export_chain()
static u_char * gsi_pem_export_chain (STACK_OF(X509) * chain, size_t * len) static
Definition at line 1005 of file delegation.c.
Referenced by delegation_split_first_pem_block().
gsi_pem_export_one()
static u_char * gsi_pem_export_one (X509 * cert, size_t * len) static
Definition at line 984 of file delegation.c.
Referenced by delegation_split_first_pem_block().
STACK_OF()
static STACK_OF (X509) static
Definition at line 206 of file delegation.c.
References STACK_OF().
webdav_delegation_handle()
void webdav_delegation_handle (ngx_http_request_t * r)
Definition at line 1457 of file delegation.c.
References BRIX_DELEGATION_BODY_MAX, brix_http_body_read_all(), delegation_client_authenticated(), delegation_reject(), delegation_validate_and_store(), and ngx_http_brix_webdav_module.
Referenced by webdav_dispatch_delegation_upload().
webdav_delegation_put_handle()
void webdav_delegation_put_handle (ngx_http_request_t * r)
Definition at line 1294 of file delegation.c.
References BRIX_DELEG_ID_HEXLEN, BRIX_DELEGATION_BODY_MAX, brix_http_body_read_all(), BRIX_UCRED_KEY_MAX, delegation_client_authenticated(), delegation_extract_id(), delegation_put_assemble(), delegation_put_store(), delegation_put_take_key(), delegation_put_validate_chain(), delegation_reject(), key, ngx_http_brix_webdav_module, and ngx_memcpy.
Referenced by webdav_dispatch_delegation_gridsite().
webdav_delegation_request_handle()
ngx_int_t webdav_delegation_request_handle (ngx_http_request_t * r)
Definition at line 903 of file delegation.c.
References BRIX_DELEG_ID_HEXLEN, brix_deleg_store(), brix_deleg_store_put(), brix_gsi_build_pxyreq(), brix_gsi_buf_t::data, delegation_client_authenticated(), delegation_get_peer_pem(), delegation_req_der_to_pem(), delegation_request_reject(), delegation_send_csr(), ngx_http_brix_webdav_req_ctx_t::dn, brix_gsi_buf_t::len, and ngx_http_brix_webdav_module.
Referenced by webdav_dispatch_delegation_gridsite().
Variable Documentation
brix_deleg_store_singleton
brix_deleg_store_t* brix_deleg_store_singleton = NULL static
Definition at line 515 of file delegation.c.
Referenced by brix_deleg_store().