nginx-xrootd: src/protocols/cvmfs/module.c File Reference
module.c File Reference
#include "cvmfs.h"
#include "core/config/config.h"
#include "core/config/root_prepare.h"
#include "core/config/http_rootfd.h"
#include "core/config/http_common.h"
#include "core/compat/alloc_guard.h"
#include "fs/cache/verify.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "origin_geo.h"
#include "fs/backend/http/sd_http.h"
#include "auth/token/issuer_registry.h"
#include "fs/backend/cache/sd_cache.h"
#include "fs/cache/origin/s3_transport.h"
#include <stdlib.h>
#include "directives_resilience.inc"
#include "directives_core.inc"
Functions
static ngx_int_t ngx_http_brix_cvmfs_postconfiguration (ngx_conf_t *cf)
static char * cvmfs_geo_rank_config (ngx_conf_t *cf, ngx_http_brix_cvmfs_loc_conf_t *conf)
static char * brix_cvmfs_reject_unsupported (ngx_conf_t *cf, ngx_http_brix_cvmfs_loc_conf_t *conf)
static void * ngx_http_brix_cvmfs_create_loc_conf (ngx_conf_t *cf)
static int cvmfs_parse_latlon (const ngx_str_t *v, double *lat, double *lon)
static char * cvmfs_conf_upstream_allow (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static char * ngx_http_brix_cvmfs_set_coords (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static char * ngx_http_brix_cvmfs_merge_loc_conf (ngx_conf_t *cf, void *parent, void *child)
static ngx_int_t cvmfs_var_set (ngx_http_request_t *r, ngx_http_variable_value_t *v, const char *val)
static ngx_int_t cvmfs_var_class (ngx_http_request_t *r, ngx_http_variable_value_t *v, uintptr_t data)
static ngx_int_t cvmfs_var_cache (ngx_http_request_t *r, ngx_http_variable_value_t *v, uintptr_t data)
static ngx_int_t cvmfs_var_origin (ngx_http_request_t *r, ngx_http_variable_value_t *v, uintptr_t data)
static ngx_int_t ngx_http_brix_cvmfs_preconfiguration (ngx_conf_t *cf)
static char * ngx_http_brix_cvmfs_set (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static ngx_int_t ngx_http_brix_cvmfs_init_process (ngx_cycle_t *cycle)
Variables
static ngx_http_variable_t ngx_http_brix_cvmfs_vars []
static ngx_http_module_t ngx_http_brix_cvmfs_module_ctx
static ngx_conf_enum_t brix_scvmfs_authz_enum []
static ngx_conf_enum_t brix_cvmfs_select_enum []
static ngx_conf_enum_t brix_cvmfs_retry_policy_enum []
static ngx_conf_enum_t brix_cvmfs_geo_answer_enum []
static ngx_command_t ngx_http_brix_cvmfs_commands []
ngx_module_t ngx_http_brix_cvmfs_module
Function Documentation
brix_cvmfs_reject_unsupported()
static char * brix_cvmfs_reject_unsupported (ngx_conf_t * cf, ngx_http_brix_cvmfs_loc_conf_t * conf) static
Definition at line 328 of file module.c.
References ngx_http_brix_shared_conf_t::allow_write, ngx_http_brix_shared_conf_t::cache_slice_size, ngx_http_brix_cvmfs_loc_conf_t::common, ngx_http_brix_shared_conf_t::stage_enable, and ngx_http_brix_shared_conf_t::stage_store.
Referenced by ngx_http_brix_cvmfs_merge_loc_conf().
cvmfs_conf_upstream_allow()
static char * cvmfs_conf_upstream_allow (ngx_conf_t * cf, ngx_command_t * cmd, void * conf) static
Definition at line 128 of file module.c.
References c.
cvmfs_geo_rank_config()
static char * cvmfs_geo_rank_config (ngx_conf_t * cf, ngx_http_brix_cvmfs_loc_conf_t * conf) static
Definition at line 159 of file module.c.
References brix_cvmfs_haversine_km(), brix_cvmfs_rank_by_metric(), brix_vfs_backend_http_endpoint_at(), brix_vfs_backend_set_http_ranks(), ngx_http_brix_cvmfs_loc_conf_t::common, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, cvmfs_parse_latlon(), brix_cvmfs_conf_t::here, brix_cvmfs_conf_t::origin_coords, ngx_http_brix_shared_conf_t::root_canon, and SD_HTTP_EP_MAX.
Referenced by ngx_http_brix_cvmfs_merge_loc_conf().
cvmfs_parse_latlon()
static int cvmfs_parse_latlon (const ngx_str_t * v, double * lat, double * lon) static
Definition at line 95 of file module.c.
References ngx_memcpy.
Referenced by cvmfs_geo_rank_config(), and ngx_http_brix_cvmfs_set_coords().
cvmfs_var_cache()
static ngx_int_t cvmfs_var_cache (ngx_http_request_t * r, ngx_http_variable_value_t * v, uintptr_t data) static
Definition at line 668 of file module.c.
References BRIX_CVMFS_CACHE_NEG, ngx_http_brix_cvmfs_ctx_t::cache_status, cvmfs_var_set(), and ngx_http_brix_cvmfs_module.
cvmfs_var_class()
static ngx_int_t cvmfs_var_class (ngx_http_request_t * r, ngx_http_variable_value_t * v, uintptr_t data) static
Definition at line 653 of file module.c.
References cvmfs_var_set(), ngx_http_brix_cvmfs_module, and ngx_http_brix_cvmfs_ctx_t::url.
cvmfs_var_origin()
static ngx_int_t cvmfs_var_origin (ngx_http_request_t * r, ngx_http_variable_value_t * v, uintptr_t data) static
Definition at line 683 of file module.c.
References BRIX_CVMFS_CACHE_FILL, brix_sd_cache_source_instance(), brix_vfs_backend_resolve(), ngx_http_brix_cvmfs_ctx_t::cache_status, ngx_http_brix_cvmfs_loc_conf_t::common, cvmfs_var_set(), ngx_http_brix_cvmfs_module, ngx_http_brix_shared_conf_t::root_canon, sd_http_last_origin(), and ngx_http_brix_cvmfs_ctx_t::up_root.
cvmfs_var_set()
static ngx_int_t cvmfs_var_set (ngx_http_request_t * r, ngx_http_variable_value_t * v, const char * val) static
Definition at line 634 of file module.c.
References ngx_memcpy, and ngx_pnalloc().
Referenced by cvmfs_var_cache(), cvmfs_var_class(), and cvmfs_var_origin().
ngx_http_brix_cvmfs_create_loc_conf()
static void * ngx_http_brix_cvmfs_create_loc_conf (ngx_conf_t * cf) static
Definition at line 57 of file module.c.
References BRIX_PCALLOC_OR_RETURN, c, and ngx_http_brix_shared_init().
ngx_http_brix_cvmfs_init_process()
static ngx_int_t ngx_http_brix_cvmfs_init_process (ngx_cycle_t * cycle) static
Definition at line 864 of file module.c.
References brix_cvmfs_rtt_init_worker().
ngx_http_brix_cvmfs_merge_loc_conf()
static char * ngx_http_brix_cvmfs_merge_loc_conf (ngx_conf_t * cf, void * parent, void * child) static
Definition at line 363 of file module.c.
References brix_export_root_opts_t::allow_write, ngx_http_brix_shared_conf_t::allow_write, BRIX_AF_AUTO, BRIX_AUTHZ_CAPABILITY, BRIX_CACHE_VERIFY_CVMFS_CAS, BRIX_CVMFS_GEO_PASSTHROUGH, brix_cvmfs_reject_unsupported(), BRIX_CVMFS_RETRY_FAILOVER, BRIX_CVMFS_RETRY_FORCE_PRIMARY, brix_cvmfs_rtt_register(), BRIX_CVMFS_SELECT_GEO, BRIX_CVMFS_SELECT_RTT, brix_http_common_adopt(), brix_http_open_rootfd(), brix_origin_trace_set(), brix_prepare_export_root(), brix_s3_origin_reuse_set(), brix_s3_origin_timeouts_set(), BRIX_SCVMFS_AUTHZ_BEARER, BRIX_SCVMFS_AUTHZ_NONE, brix_storage_backend_posix_root(), brix_tier_register_stores(), brix_token_registry_build(), brix_vfs_backend_config_str(), ngx_http_brix_shared_conf_t::cache_client_hold, ngx_http_brix_shared_conf_t::cache_fill_max_life, ngx_http_brix_shared_conf_t::cache_manifest_ttl, ngx_http_brix_shared_conf_t::cache_quarantine_dir, ngx_http_brix_shared_conf_t::cache_verify_mode, brix_export_root_opts_t::canon_size, brix_cvmfs_conf_t::client_hold, ngx_http_brix_cvmfs_loc_conf_t::common, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, cvmfs_geo_rank_config(), brix_export_root_opts_t::directive_name, brix_cvmfs_conf_t::enable, brix_cvmfs_conf_t::fill_max_life, brix_cvmfs_conf_t::fill_retry_policy, brix_cvmfs_conf_t::geo_answer, brix_cvmfs_conf_t::geo_cache_ttl, brix_cvmfs_conf_t::geo_max_servers, brix_cvmfs_conf_t::here, brix_cvmfs_conf_t::manifest_ttl, brix_cvmfs_conf_t::negative_ttl, ngx_http_brix_shared_merge(), brix_cvmfs_conf_t::origin_attempt_timeout, brix_cvmfs_conf_t::origin_connect_timeout, brix_cvmfs_conf_t::origin_coords, brix_cvmfs_conf_t::origin_reuse_conn, brix_cvmfs_conf_t::origin_select, brix_cvmfs_conf_t::origin_stall_bytes, brix_cvmfs_conf_t::origin_stall_timeout, ngx_http_brix_shared_conf_t::pblock_block_size, brix_cvmfs_conf_t::quarantine_dir, brix_export_root_opts_t::required, ngx_http_brix_shared_conf_t::root, ngx_http_brix_shared_conf_t::root_canon, brix_cvmfs_conf_t::rtt_interval, ngx_http_brix_cvmfs_loc_conf_t::scvmfs, ngx_http_brix_cvmfs_loc_conf_t::scvmfs_authz, ngx_http_brix_cvmfs_loc_conf_t::scvmfs_registry, ngx_http_brix_cvmfs_loc_conf_t::scvmfs_token_issuers, sd_http_force_primary_set(), brix_cvmfs_conf_t::shared_cache, ngx_http_brix_shared_conf_t::storage_backend, ngx_http_brix_shared_conf_t::thread_pool_name, brix_cvmfs_conf_t::trace, brix_cvmfs_conf_t::unified_origin, brix_cvmfs_conf_t::upstream_allow, and brix_cvmfs_conf_t::upstream_max.
ngx_http_brix_cvmfs_postconfiguration()
static ngx_int_t ngx_http_brix_cvmfs_postconfiguration (ngx_conf_t * cf) static
Definition at line 739 of file module.c.
References brix_configure_dashboard(), brix_metrics_ensure_zone(), ngx_http_brix_cvmfs_loc_conf_t::common, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, brix_cvmfs_conf_t::enable, ngx_http_brix_cvmfs_module, s, ngx_http_brix_shared_conf_t::thread_pool, and ngx_http_brix_shared_conf_t::thread_pool_name.
ngx_http_brix_cvmfs_preconfiguration()
static ngx_int_t ngx_http_brix_cvmfs_preconfiguration (ngx_conf_t * cf) static
Definition at line 719 of file module.c.
References ngx_http_brix_cvmfs_vars.
ngx_http_brix_cvmfs_set()
static char * ngx_http_brix_cvmfs_set (ngx_conf_t * cf, ngx_command_t * cmd, void * conf) static
Definition at line 802 of file module.c.
References ngx_http_brix_cvmfs_handler().
ngx_http_brix_cvmfs_set_coords()
static char * ngx_http_brix_cvmfs_set_coords (ngx_conf_t * cf, ngx_command_t * cmd, void * conf) static
Definition at line 260 of file module.c.
References c, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, cvmfs_parse_latlon(), and brix_cvmfs_conf_t::origin_coords.
Variable Documentation
brix_cvmfs_geo_answer_enum
ngx_conf_enum_t brix_cvmfs_geo_answer_enum[] static
Initial value:
= {
    { ngx_string("off"), BRIX_CVMFS_GEO_PASSTHROUGH },
    { ngx_string("rtt"), BRIX_CVMFS_GEO_RTT },
    { ngx_null_string, 0 }
}
Definition at line 845 of file module.c.
brix_cvmfs_retry_policy_enum
ngx_conf_enum_t brix_cvmfs_retry_policy_enum[] static
Initial value:
= {
    { ngx_string("failover"),      BRIX_CVMFS_RETRY_FAILOVER },
    { ngx_string("force-primary"), BRIX_CVMFS_RETRY_FORCE_PRIMARY },
    { ngx_null_string, 0 }
}
Definition at line 839 of file module.c.
brix_cvmfs_select_enum
ngx_conf_enum_t brix_cvmfs_select_enum[] static
Initial value:
= {
    { ngx_string("static"), BRIX_CVMFS_SELECT_STATIC },
    { ngx_string("geo"),    BRIX_CVMFS_SELECT_GEO },
    { ngx_string("rtt"),    BRIX_CVMFS_SELECT_RTT },
    { ngx_null_string, 0 }
}
Definition at line 832 of file module.c.
brix_scvmfs_authz_enum
ngx_conf_enum_t brix_scvmfs_authz_enum[] static
Initial value:
= {
    { ngx_string("none"),   BRIX_SCVMFS_AUTHZ_NONE },
    { ngx_string("bearer"), BRIX_SCVMFS_AUTHZ_BEARER },
    { ngx_null_string, 0 }
}
Definition at line 826 of file module.c.
ngx_http_brix_cvmfs_commands
ngx_command_t ngx_http_brix_cvmfs_commands[] static
Initial value:
= {
    ngx_null_command
}
Definition at line 851 of file module.c.
ngx_http_brix_cvmfs_module
ngx_module_t ngx_http_brix_cvmfs_module
Initial value:
= {
    NGX_MODULE_V1,
    &ngx_http_brix_cvmfs_module_ctx,
    ngx_http_brix_cvmfs_commands,
    NGX_HTTP_MODULE,
    NULL,
    NULL,
    ngx_http_brix_cvmfs_init_process,
    NULL,
    NULL,
    NULL,
    NULL,
    NGX_MODULE_V1_PADDING
}
Definition at line 869 of file module.c.
Referenced by brix_cvmfs_gate(), brix_cvmfs_geo_passthrough(), brix_cvmfs_proxy_target(), brix_http_protocol_variable(), brix_proto_mask(), brix_scvmfs_preamble(), cvmfs_finalize_observe(), cvmfs_resolve_sd(), cvmfs_tier_get(), cvmfs_var_cache(), cvmfs_var_class(), cvmfs_var_origin(), ngx_http_brix_cvmfs_handler(), and ngx_http_brix_cvmfs_postconfiguration().
ngx_http_brix_cvmfs_module_ctx
ngx_http_module_t ngx_http_brix_cvmfs_module_ctx static
Initial value:
= {
    ngx_http_brix_cvmfs_preconfiguration,
    ngx_http_brix_cvmfs_postconfiguration,
    NULL,
    NULL,
    NULL,
    NULL,
    ngx_http_brix_cvmfs_create_loc_conf,
    ngx_http_brix_cvmfs_merge_loc_conf,
}
Definition at line 788 of file module.c.
ngx_http_brix_cvmfs_vars
ngx_http_variable_t ngx_http_brix_cvmfs_vars[] static
Initial value:
= {
    { ngx_string("cvmfs_class"),  NULL, cvmfs_var_class,  0, 0, 0 },
    { ngx_string("cvmfs_cache"),  NULL, cvmfs_var_cache,  0, 0, 0 },
    { ngx_string("cvmfs_origin"), NULL, cvmfs_var_origin, 0, 0, 0 },
      ngx_http_null_variable
}
Definition at line 711 of file module.c.
Referenced by ngx_http_brix_cvmfs_preconfiguration().