nginx-xrootd: src/core/compat/protocol_caps.h File Reference
protocol_caps.h File Reference
#include <ngx_http.h>
Data Structures
struct brix_http_operation_t
Enumerations
enum brix_proto_op_flags_t {
BRIX_PROTO_OP_READ = 0x0001 , BRIX_PROTO_OP_WRITE = 0x0002 , BRIX_PROTO_OP_LIST = 0x0004 , BRIX_PROTO_OP_TPC = 0x0008 ,
BRIX_PROTO_OP_LOCK = 0x0010 , BRIX_PROTO_OP_ASYNC_BODY = 0x0020
}
Functions
const brix_http_operation_t * brix_http_operation_find (ngx_http_request_t *r, const brix_http_operation_t *ops, ngx_uint_t nops)
ngx_int_t brix_http_operation_allow_header (ngx_pool_t *pool, const brix_http_operation_t *ops, ngx_uint_t nops, ngx_uint_t enabled_flags, ngx_str_t *out)
Enumeration Type Documentation
brix_proto_op_flags_t
enum brix_proto_op_flags_t
Enumerator
BRIX_PROTO_OP_READ
BRIX_PROTO_OP_WRITE
BRIX_PROTO_OP_LIST
BRIX_PROTO_OP_TPC
BRIX_PROTO_OP_LOCK
BRIX_PROTO_OP_ASYNC_BODY
Definition at line 21 of file protocol_caps.h.
Function Documentation
brix_http_operation_allow_header()
ngx_int_t brix_http_operation_allow_header (ngx_pool_t * pool, const brix_http_operation_t * ops, ngx_uint_t nops, ngx_uint_t enabled_flags, ngx_str_t * out)
Definition at line 35 of file protocol_caps.c.
References BRIX_PALLOC_OR_RETURN, name, and ngx_memcpy.
Referenced by s3_handle_options(), webdav_add_cors_headers(), webdav_dispatch_not_allowed(), and webdav_handle_options().
brix_http_operation_find()
const brix_http_operation_t * brix_http_operation_find (ngx_http_request_t * r, const brix_http_operation_t * ops, ngx_uint_t nops)
Definition at line 14 of file protocol_caps.c.
References brix_http_operation_t::name, and name.
Referenced by access_check_scope(), s3_metrics_method_slot(), webdav_is_write_method(), and webdav_metrics_method().