nginx-xrootd: src/protocols/root/fattr/helpers.c File Reference
helpers.c File Reference
#include "ngx_brix_fattr.h"
#include "core/compat/error_mapping.h"
#include "core/compat/fattr_codec.h"
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/xattr.h>
#include <arpa/inet.h>
#include "core/compat/alloc_guard.h"
Functions
uint16_t fattr_errno_to_xrd (int err)
void fattr_set_rc (brix_fattr_entry_t *attr, uint16_t rc)
ssize_t fattr_parse_nvec (ngx_log_t *log, u_char *nvec_copy, size_t buflen, int numattr, brix_fattr_entry_t *attrs)
ngx_int_t fattr_send_vector_status (brix_ctx_t *ctx, ngx_connection_t *c, u_char *nvec_copy, size_t nvec_len, int numattr, brix_fattr_entry_t *attrs)
Function Documentation
fattr_errno_to_xrd()
uint16_t fattr_errno_to_xrd (int err)
Definition at line 17 of file helpers.c.
References brix_kxr_from_errno(), kXR_ArgTooLong, and kXR_AttrNotFound.
Referenced by fattr_del(), fattr_get(), and fattr_set().
fattr_parse_nvec()
ssize_t fattr_parse_nvec (ngx_log_t * log, u_char * nvec_copy, size_t buflen, int numattr, brix_fattr_entry_t * attrs)
Definition at line 44 of file helpers.c.
References BRIX_FATTR_XKEY_PFX, brix_fattr_entry_t::errcode, kXR_faMaxNlen, log, brix_fattr_entry_t::name, brix_fattr_entry_t::nlen, brix_fattr_entry_t::rc_ptr, brix_fattr_entry_t::value, brix_fattr_entry_t::vlen, and xrdp_fattr_nvec_parse().
Referenced by fattr_decode_names().
fattr_send_vector_status()
ngx_int_t fattr_send_vector_status (brix_ctx_t * ctx, ngx_connection_t * c, u_char * nvec_copy, size_t nvec_len, int numattr, brix_fattr_entry_t * attrs)
Definition at line 102 of file helpers.c.
References BRIX_OP_FATTR, BRIX_OP_OK, BRIX_PALLOC_OR_RETURN, brix_send_error(), brix_send_ok(), c, kXR_NoMemory, and ngx_memcpy.
Referenced by fattr_del(), and fattr_set().
fattr_set_rc()
void fattr_set_rc (brix_fattr_entry_t * attr, uint16_t rc)
Definition at line 30 of file helpers.c.
References brix_fattr_entry_t::errcode, ngx_memcpy, and brix_fattr_entry_t::rc_ptr.
Referenced by fattr_del(), fattr_get(), and fattr_set().