nginx-xrootd: src/protocols/root/handshake/policy.c File Reference
policy.c File Reference
#include "handshake.h"
Functions
ngx_int_t brix_check_token_scope (brix_ctx_t *ctx, const char *logical_path, int need_write)
ngx_int_t brix_min_sec_enforce (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_dispatch_require_login (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_dispatch_require_auth (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_dispatch_require_write (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_check_token_scope()
ngx_int_t brix_check_token_scope (brix_ctx_t * ctx, const char * logical_path, int need_write)
Definition at line 19 of file policy.c.
References brix_ctx_token_t::auth, brix_identity_check_token_scope(), brix_token_check_read(), brix_token_check_write(), brix_ctx_t::identity, brix_ctx_token_t::scope_count, brix_ctx_token_t::scopes, and brix_ctx_t::token.
Referenced by brix_auth_gate_evaluate(), brix_statx_path_authorized(), prepare_path_authz(), and qprep_path_authorized().
brix_dispatch_require_auth()
ngx_int_t brix_dispatch_require_auth (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 96 of file policy.c.
References brix_ctx_login_t::auth_done, BRIX_DISPATCH_CONTINUE, brix_send_error(), c, kXR_NotAuthorized, brix_ctx_login_t::logged_in, and brix_ctx_t::login.
Referenced by brix_dispatch_require_write().
brix_dispatch_require_login()
ngx_int_t brix_dispatch_require_login (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 85 of file policy.c.
References BRIX_DISPATCH_CONTINUE, brix_send_error(), c, kXR_NotAuthorized, brix_ctx_login_t::logged_in, and brix_ctx_t::login.
Referenced by brix_dispatch_session_opcode(), and brix_dispatch_signing_opcode().
brix_dispatch_require_write()
ngx_int_t brix_dispatch_require_write (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 107 of file policy.c.
References BRIX_DISPATCH_CONTINUE, brix_dispatch_require_auth(), brix_send_error(), c, brix_ctx_t::is_bound, kXR_fsReadOnly, and kXR_NotAuthorized.
Referenced by brix_dispatch_write_opcode().
brix_min_sec_enforce()
ngx_int_t brix_min_sec_enforce (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 43 of file policy.c.
References BRIX_AUTH_NONE, BRIX_DISPATCH_CONTINUE, BRIX_MIN_SEC_INTENSE, BRIX_MIN_SEC_NONE, brix_send_error(), c, brix_ctx_recv_t::cur_reqid, kXR_NotAuthorized, kXR_TLSRequired, and brix_ctx_t::recv.
Referenced by brix_dispatch().