nginx-xrootd: src/protocols/root/write/write.c File Reference
write.c File Reference
#include "core/ngx_brix_module.h"
#include "protocols/ssi/ssi.h"
#include "fs/cache/writethrough_metrics.h"
#include "wrts_journal.h"
Data Structures
struct brix_write_desc_t
Functions
static ngx_flag_t brix_write_route_special (brix_ctx_t *ctx, ngx_connection_t *c, const brix_write_desc_t *w, ngx_int_t *out_rc)
static ngx_int_t brix_write_finalize_sync (brix_ctx_t *ctx, ngx_connection_t *c, const brix_write_desc_t *w, ssize_t nwritten, const char *write_detail)
ngx_int_t brix_write_require_pgwrite (brix_ctx_t *ctx, ngx_connection_t *c, int idx, size_t wlen, const char *op, ngx_int_t *rc)
ngx_int_t brix_handle_write (brix_ctx_t *ctx, ngx_connection_t *c)
Function Documentation
brix_handle_write()
ngx_int_t brix_handle_write (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 276 of file write.c.
References BRIX_OP_WRITE, brix_try_post_write_aio(), brix_validate_write_handle(), brix_vfs_io_execute(), brix_vfs_job_set_obj(), brix_vfs_job_write_init(), brix_write_finalize_sync(), brix_write_require_pgwrite(), brix_write_route_special(), c, brix_file_t::csi, brix_vfs_job_t::csi, brix_ctx_recv_t::cur_dlen, brix_file_t::fd, xrdw_write_req_t::fhandle, brix_ctx_t::files, brix_ctx_recv_t::hdr_buf, brix_vfs_job_t::io_errno, brix_vfs_job_t::nio, xrdw_write_req_t::offset, brix_ctx_t::out, brix_ctx_recv_t::payload, brix_ctx_recv_t::payload_buf, brix_ctx_recv_t::payload_buf_size, brix_ctx_t::recv, brix_file_t::sd_obj, brix_ctx_out_t::wr_inflight, and xrdw_write_req_unpack().
brix_write_finalize_sync()
static ngx_int_t brix_write_finalize_sync (brix_ctx_t * ctx, ngx_connection_t * c, const brix_write_desc_t * w, ssize_t nwritten, const char * write_detail) static
Definition at line 154 of file write.c.
References BRIX_OP_WRITE, BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_rl_charge_ctx(), brix_transfer_slot_count_op(), brix_transfer_slot_update(), brix_wrts_record(), brix_wt_mark_dirty(), brix_ctx_totals_t::bytes_written, brix_file_t::bytes_written, c, brix_file_t::dashboard_slot, brix_ctx_t::files, brix_write_desc_t::idx, kXR_IOError, ngx_brix_dashboard_shm_zone, brix_write_desc_t::offset, brix_file_t::path, brix_ctx_t::totals, brix_file_t::wrts_enabled, and brix_file_t::wt_enabled.
Referenced by brix_handle_write().
brix_write_require_pgwrite()
ngx_int_t brix_write_require_pgwrite (brix_ctx_t * ctx, ngx_connection_t * c, int idx, size_t wlen, const char * op, ngx_int_t * rc)
Definition at line 232 of file write.c.
References brix_log_access(), BRIX_OP_ERR, BRIX_OP_WRITE, brix_send_error(), c, brix_ctx_t::files, kXR_Unsupported, ngx_stream_brix_module, op, brix_file_t::path, and brix_file_t::ssi.
Referenced by brix_handle_write().
brix_write_route_special()
static ngx_flag_t brix_write_route_special (brix_ctx_t * ctx, ngx_connection_t * c, const brix_write_desc_t * w, ngx_int_t * out_rc) static
Definition at line 76 of file write.c.
References BRIX_OP_OK, BRIX_OP_WRITE, brix_send_ok(), brix_ssi_write(), brix_write_compressed(), brix_write_staged(), brix_wrts_is_replay(), c, brix_ctx_t::files, brix_write_desc_t::hdrbody, brix_write_desc_t::idx, brix_write_desc_t::offset, brix_file_t::ssi, brix_write_desc_t::wlen, brix_file_t::write_codec, brix_file_t::writer, and brix_file_t::wrts_enabled.
Referenced by brix_handle_write().