nginx-xrootd: src/protocols/cvmfs/handler.c File Reference
handler.c File Reference
#include "cvmfs.h"
#include "fs/path/path.h"
#include "core/compat/error_mapping.h"
#include "core/http/etag.h"
#include "core/http/http_conditionals.h"
#include "core/http/http_headers.h"
#include "core/http/sesslog_conn.h"
#include "fs/vfs/vfs.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "observability/dashboard/dashboard.h"
#include "observability/dashboard/dashboard_tracking.h"
#include "observability/metrics/unified.h"
#include "protocols/shared/file_serve.h"
#include "protocols/shared/http_cache_fill.h"
#include "protocols/shared/http_serve_offload.h"
#include "core/compat/cstr.h"
#include <limits.h>
Functions
static ngx_uint_t cvmfs_errno_status (int err)
static ngx_int_t cvmfs_reenter (ngx_http_request_t *r, void *data)
static brix_sd_instance_t * cvmfs_resolve_sd (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf)
static ngx_int_t cvmfs_build_fs_path (ngx_http_request_t *r, const char *root, char *path, size_t path_size)
static void cvmfs_serve_opts_init (brix_http_serve_opts_t *opts)
static ngx_int_t cvmfs_tier_serve_or_fill (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf, brix_sd_instance_t *sd, const char *key, const char *path)
static ngx_int_t cvmfs_tier_open_respond (ngx_http_request_t *r, ngx_http_brix_cvmfs_ctx_t *ctx, brix_vfs_ctx_t *vctx, const char *path)
static ngx_int_t cvmfs_tier_get (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf)
static void cvmfs_finalize_sesslog (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf, ngx_http_brix_cvmfs_ctx_t *ctx, ngx_uint_t status)
static void cvmfs_finalize_trace (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf, ngx_http_brix_cvmfs_ctx_t *ctx, ngx_uint_t status)
static void cvmfs_finalize_metrics_fill (ngx_http_request_t *r, ngx_http_brix_cvmfs_ctx_t *ctx, ngx_uint_t status)
static void cvmfs_finalize_metrics_hit (ngx_http_request_t *r, ngx_http_brix_cvmfs_ctx_t *ctx)
static void cvmfs_finalize_metrics (ngx_http_request_t *r, ngx_http_brix_cvmfs_ctx_t *ctx, ngx_uint_t status)
static void cvmfs_finalize_observe (void *data)
ngx_int_t ngx_http_brix_cvmfs_handler (ngx_http_request_t *r)
Function Documentation
cvmfs_build_fs_path()
static ngx_int_t cvmfs_build_fs_path (ngx_http_request_t * r, const char * root, char * path, size_t path_size) static
Definition at line 85 of file handler.c.
References brix_str_cbuf(), and ngx_memcpy.
Referenced by cvmfs_tier_get().
cvmfs_errno_status()
static ngx_uint_t cvmfs_errno_status (int err) static
Definition at line 38 of file handler.c.
References brix_http_errno_to_status().
Referenced by cvmfs_tier_open_respond().
cvmfs_finalize_metrics()
static void cvmfs_finalize_metrics (ngx_http_request_t * r, ngx_http_brix_cvmfs_ctx_t * ctx, ngx_uint_t status) static
Definition at line 449 of file handler.c.
References BRIX_CVMFS_CACHE_FILL, BRIX_CVMFS_CACHE_HIT, ngx_http_brix_cvmfs_ctx_t::cache_status, cvmfs_finalize_metrics_fill(), and cvmfs_finalize_metrics_hit().
Referenced by cvmfs_finalize_observe().
cvmfs_finalize_metrics_fill()
static void cvmfs_finalize_metrics_fill (ngx_http_request_t * r, ngx_http_brix_cvmfs_ctx_t * ctx, ngx_uint_t status) static
Definition at line 386 of file handler.c.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, BRIX_CVMFS_METRIC_ADD, BRIX_CVMFS_METRIC_INC, brix_metric_cache_result(), BRIX_PROTO_CVMFS, ngx_brix_cvmfs_repo_metrics_t::bytes_served_fill_total, ngx_brix_cvmfs_repo_metrics_t::cache_misses_total, ngx_brix_cvmfs_repo_metrics_t::files_accessed_total, ngx_brix_cvmfs_repo_metrics_t::fill_failures_total, ngx_brix_cvmfs_repo_metrics_t::fills_total, ngx_http_brix_cvmfs_ctx_t::repo, and ngx_http_brix_cvmfs_ctx_t::url.
Referenced by cvmfs_finalize_metrics().
cvmfs_finalize_metrics_hit()
static void cvmfs_finalize_metrics_hit (ngx_http_request_t * r, ngx_http_brix_cvmfs_ctx_t * ctx) static
Definition at line 424 of file handler.c.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, BRIX_CVMFS_METRIC_ADD, brix_metric_cache_result(), BRIX_PROTO_CVMFS, ngx_brix_cvmfs_repo_metrics_t::bytes_served_hit_total, ngx_brix_cvmfs_repo_metrics_t::cache_hits_total, ngx_brix_cvmfs_repo_metrics_t::files_accessed_total, ngx_http_brix_cvmfs_ctx_t::repo, and ngx_http_brix_cvmfs_ctx_t::url.
Referenced by cvmfs_finalize_metrics().
cvmfs_finalize_observe()
static void cvmfs_finalize_observe (void * data) static
Definition at line 467 of file handler.c.
References brix_cvmfs_notify_status(), brix_http_effective_status(), cvmfs_finalize_metrics(), cvmfs_finalize_sesslog(), cvmfs_finalize_trace(), and ngx_http_brix_cvmfs_module.
Referenced by ngx_http_brix_cvmfs_handler().
cvmfs_finalize_sesslog()
static void cvmfs_finalize_sesslog (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf, ngx_http_brix_cvmfs_ctx_t * ctx, ngx_uint_t status) static
Definition at line 299 of file handler.c.
References brix_http_sess(), brix_http_sess_uri(), BRIX_SESS_AM_ANON, BRIX_SESS_MODE_READ, BRIX_SESS_PROTO_CVMFS, brix_sess_result(), BRIX_SESS_XFER_ABORTED, brix_sess_xfer_add(), BRIX_SESS_XFER_COMPLETE, brix_sess_xfer_end(), brix_sesslog_err_from_http(), BRIX_SESSLOG_ERR_MAX, BRIX_SESSLOG_PATH_MAX, ngx_http_brix_cvmfs_loc_conf_t::common, ngx_http_brix_cvmfs_ctx_t::sess_attempt_logged, ngx_http_brix_cvmfs_ctx_t::sess_xfer, and ngx_http_brix_cvmfs_ctx_t::sess_xfer_started.
Referenced by cvmfs_finalize_observe().
cvmfs_finalize_trace()
static void cvmfs_finalize_trace (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf, ngx_http_brix_cvmfs_ctx_t * ctx, ngx_uint_t status) static
Definition at line 339 of file handler.c.
References BRIX_CVMFS_CACHE_NEG, brix_sanitize_log_string(), ngx_http_brix_cvmfs_ctx_t::cache_status, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, ngx_memcpy, brix_cvmfs_conf_t::trace, and ngx_http_brix_cvmfs_ctx_t::url.
Referenced by cvmfs_finalize_observe().
cvmfs_reenter()
static ngx_int_t cvmfs_reenter (ngx_http_request_t * r, void * data) static
Definition at line 56 of file handler.c.
References ngx_http_brix_cvmfs_handler().
Referenced by cvmfs_tier_serve_or_fill().
cvmfs_resolve_sd()
static brix_sd_instance_t * cvmfs_resolve_sd (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf) static
Definition at line 66 of file handler.c.
References brix_vfs_backend_resolve(), ngx_http_brix_cvmfs_loc_conf_t::common, ngx_http_brix_cvmfs_module, ngx_http_brix_shared_conf_t::root_canon, and ngx_http_brix_cvmfs_ctx_t::sd_override.
Referenced by cvmfs_tier_get().
cvmfs_serve_opts_init()
static void cvmfs_serve_opts_init (brix_http_serve_opts_t * opts) static
Definition at line 114 of file handler.c.
References BRIX_ETAG_WEAK, BRIX_XFER_PROTO_CVMFS, brix_http_serve_opts_t::etag_flags, brix_http_serve_opts_t::identity, brix_http_serve_opts_t::op_name, and brix_http_serve_opts_t::xfer_proto.
Referenced by cvmfs_tier_open_respond(), and cvmfs_tier_serve_or_fill().
cvmfs_tier_get()
static ngx_int_t cvmfs_tier_get (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf) static
Definition at line 239 of file handler.c.
References brix_dashboard_http_start_identity(), BRIX_PROTO_CVMFS, brix_vfs_ctx_init(), brix_vfs_export_relative(), BRIX_XFER_DIR_READ, BRIX_XFER_PROTO_CVMFS, ngx_http_brix_cvmfs_loc_conf_t::common, cvmfs_build_fs_path(), cvmfs_resolve_sd(), cvmfs_tier_open_respond(), cvmfs_tier_serve_or_fill(), key, ngx_http_brix_cvmfs_module, PATH_MAX, brix_vfs_ctx_t::pool, ngx_http_brix_shared_conf_t::root_canon, brix_vfs_ctx_t::sd, and ngx_http_brix_cvmfs_ctx_t::up_root.
Referenced by ngx_http_brix_cvmfs_handler().
cvmfs_tier_open_respond()
static ngx_int_t cvmfs_tier_open_respond (ngx_http_request_t * r, ngx_http_brix_cvmfs_ctx_t * ctx, brix_vfs_ctx_t * vctx, const char * path) static
Definition at line 186 of file handler.c.
References BRIX_CVMFS_CACHE_HIT, BRIX_CVMFS_CACHE_NONE, brix_http_check_if_modified_since(), brix_http_serve_file_ranged(), brix_vfs_close(), brix_vfs_file_stat(), BRIX_VFS_O_READ, brix_vfs_open(), ngx_http_brix_cvmfs_ctx_t::cache_status, cvmfs_errno_status(), cvmfs_serve_opts_init(), brix_vfs_stat_t::is_directory, and brix_vfs_stat_t::mtime.
Referenced by cvmfs_tier_get().
cvmfs_tier_serve_or_fill()
static ngx_int_t cvmfs_tier_serve_or_fill (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf, brix_sd_instance_t * sd, const char * key, const char * path) static
Definition at line 135 of file handler.c.
References BRIX_CVMFS_CACHE_FILL, brix_http_cache_fill_if_needed(), brix_http_serve_offload_remote(), ngx_http_brix_cvmfs_ctx_t::cache_status, ngx_http_brix_cvmfs_loc_conf_t::common, cvmfs_reenter(), cvmfs_serve_opts_init(), key, and ngx_http_brix_cvmfs_module.
Referenced by cvmfs_tier_get().
ngx_http_brix_cvmfs_handler()
ngx_int_t ngx_http_brix_cvmfs_handler (ngx_http_request_t * r)
Definition at line 492 of file handler.c.
References brix_sess_xfer_t::active, brix_cvmfs_gate(), brix_http_sess(), brix_http_sess_uri(), brix_scvmfs_preamble(), BRIX_SESS_AM_ANON, brix_sess_attempt(), brix_sess_auth_once(), BRIX_SESS_MODE_READ, BRIX_SESS_PROTO_CVMFS, brix_sess_xfer_start(), BRIX_SESSLOG_PATH_MAX, ngx_http_brix_cvmfs_loc_conf_t::common, cvmfs_finalize_observe(), cvmfs_tier_get(), ngx_http_brix_cvmfs_module, ngx_pcalloc(), ngx_http_brix_cvmfs_loc_conf_t::scvmfs, ngx_http_brix_cvmfs_ctx_t::sess_attempt_logged, ngx_http_brix_cvmfs_ctx_t::sess_xfer, and ngx_http_brix_cvmfs_ctx_t::sess_xfer_started.
Referenced by cvmfs_reenter(), and ngx_http_brix_cvmfs_set().