nginx-xrootd: src/protocols/webdav/config.c File Reference
config.c File Reference
#include "webdav.h"
#include "auth/crypto/store_policy.h"
#include "core/compat/integrity_info.h"
#include "core/compat/tmp_path.h"
#include "auth/token/issuer_registry.h"
#include "proxy_internal.h"
#include "net/mirror/http_mirror.h"
#include "core/config/config.h"
#include "fs/path/path.h"
#include "core/config/root_prepare.h"
#include "core/config/http_rootfd.h"
#include "core/config/http_common.h"
#include "core/config/export_guard.h"
#include "core/compat/staged_file.h"
#include "fs/backend/sd.h"
#include "fs/vfs/vfs_backend_registry.h"
#include <openssl/x509.h>
#include <limits.h>
#include <sys/stat.h>
#include <unistd.h>
#include "core/compat/alloc_guard.h"
#include "core/config/credential_block.h"
Macros
#define webdav_validate_path brix_validate_path
#define WEBDAV_PATH_REGULAR_FILE BRIX_PATH_REGULAR_FILE
#define WEBDAV_PATH_DIRECTORY BRIX_PATH_DIRECTORY
#define WEBDAV_PATH_FILE_OR_DIRECTORY BRIX_PATH_FILE_OR_DIRECTORY
Functions
static void webdav_x509_store_cleanup (void *data)
static ngx_int_t webdav_validate_cors_origins (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
void * brix_webdav_backend_instance (ngx_http_brix_webdav_loc_conf_t *conf, ngx_log_t *log)
void * ngx_http_brix_webdav_create_loc_conf (ngx_conf_t *cf)
static const char * webdav_auth_name (ngx_uint_t auth)
static ngx_uint_t webdav_summary_is_new (ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_loc_conf_t *prev)
static void webdav_log_endpoint_summary (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
char * ngx_http_brix_webdav_merge_loc_conf (ngx_conf_t *cf, void *parent, void *child)
Macro Definition Documentation
WEBDAV_PATH_DIRECTORY
#define WEBDAV_PATH_DIRECTORY BRIX_PATH_DIRECTORY
Definition at line 38 of file config.c.
WEBDAV_PATH_FILE_OR_DIRECTORY
#define WEBDAV_PATH_FILE_OR_DIRECTORY BRIX_PATH_FILE_OR_DIRECTORY
Definition at line 39 of file config.c.
WEBDAV_PATH_REGULAR_FILE
#define WEBDAV_PATH_REGULAR_FILE BRIX_PATH_REGULAR_FILE
Definition at line 37 of file config.c.
webdav_validate_path
#define webdav_validate_path brix_validate_path
Definition at line 36 of file config.c.
Function Documentation
brix_webdav_backend_instance()
void * brix_webdav_backend_instance (ngx_http_brix_webdav_loc_conf_t * conf, ngx_log_t * log)
Definition at line 105 of file config.c.
References brix_vfs_backend_resolve(), ngx_http_brix_webdav_loc_conf_t::common, log, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by webdav_handle_get(), webdav_handle_move(), webdav_move_collection_post_task(), and webdav_put_vfs_ctx_init().
ngx_http_brix_webdav_create_loc_conf()
void * ngx_http_brix_webdav_create_loc_conf (ngx_conf_t * cf)
Definition at line 115 of file config.c.
References ngx_http_brix_webdav_loc_conf_t::acc, ngx_http_brix_webdav_loc_conf_t::auth, ngx_http_brix_webdav_loc_conf_t::authdb_rules, brix_acc_http_init_conf(), BRIX_PCALLOC_OR_RETURN, brix_rate_limit_conf_t::burst, ngx_http_brix_webdav_loc_conf_t::ca_store, ngx_http_brix_webdav_loc_conf_t::checksum_xattr_format, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_loc_conf_t::cors_credentials, ngx_http_brix_webdav_loc_conf_t::cors_max_age, ngx_http_brix_webdav_loc_conf_t::cors_origins, ngx_http_brix_webdav_loc_conf_t::crl_mode, ngx_http_brix_webdav_loc_conf_t::dig_enable, ngx_http_brix_webdav_loc_conf_t::dig_exports, brix_mirror_conf_t::enabled, ngx_http_brix_webdav_loc_conf_t::http_query_token, ngx_http_brix_webdav_loc_conf_t::introspect_fail_open, ngx_http_brix_webdav_loc_conf_t::introspect_ttl, brix_rate_limit_conf_t::key_ip, brix_rate_limit_conf_t::kv, ngx_http_brix_webdav_loc_conf_t::lock_startup_sweep, ngx_http_brix_webdav_loc_conf_t::lock_timeout, brix_mirror_conf_t::log_diverge, ngx_http_brix_webdav_loc_conf_t::macaroon_max_validity, brix_mirror_conf_t::method_mask, ngx_http_brix_webdav_loc_conf_t::mirror, ngx_http_brix_webdav_loc_conf_t::mirror_upstream_conf, brix_mirror_conf_t::mirror_writes, ngx_http_brix_shared_init(), ngx_http_brix_webdav_tpc_create_loc_conf(), brix_mirror_conf_t::opcode_mask, ngx_http_brix_webdav_loc_conf_t::open_file_cache, ngx_http_brix_webdav_loc_conf_t::open_file_cache_errors, ngx_http_brix_webdav_loc_conf_t::open_file_cache_events, ngx_http_brix_webdav_loc_conf_t::open_file_cache_min_uses, ngx_http_brix_webdav_loc_conf_t::open_file_cache_valid, ngx_http_brix_webdav_loc_conf_t::proxy_certs, ngx_http_brix_webdav_loc_conf_t::proxy_pool_enabled, brix_rate_limit_conf_t::rate, ngx_http_brix_webdav_loc_conf_t::rate_limit, ngx_http_brix_webdav_loc_conf_t::revoke_kv, brix_mirror_conf_t::sample_pct, ngx_http_brix_webdav_loc_conf_t::signing_policy_mode, brix_mirror_conf_t::strip_auth, ngx_http_brix_webdav_loc_conf_t::tape_rest, brix_mirror_conf_t::targets, brix_mirror_conf_t::timeout_ms, ngx_http_brix_webdav_loc_conf_t::token_cache_kv, ngx_http_brix_webdav_loc_conf_t::token_clock_skew, ngx_http_brix_webdav_loc_conf_t::upload_resume, ngx_http_brix_webdav_loc_conf_t::upstream_auth, ngx_http_brix_webdav_loc_conf_t::upstream_backends, ngx_http_brix_webdav_loc_conf_t::upstream_conf, ngx_http_brix_webdav_loc_conf_t::upstream_fail_timeout, ngx_http_brix_webdav_loc_conf_t::upstream_max_fails, ngx_http_brix_webdav_loc_conf_t::upstream_proxy, ngx_http_brix_webdav_loc_conf_t::upstream_resolved, ngx_http_brix_webdav_loc_conf_t::upstream_urls, ngx_http_brix_webdav_loc_conf_t::verify_depth, ngx_http_brix_webdav_loc_conf_t::vo_rules, ngx_http_brix_webdav_loc_conf_t::zip_access, and ngx_http_brix_webdav_loc_conf_t::zip_cd_max_bytes.
ngx_http_brix_webdav_merge_loc_conf()
char * ngx_http_brix_webdav_merge_loc_conf (ngx_conf_t * cf, void * parent, void * child)
Definition at line 308 of file config.c.
References ngx_http_brix_webdav_loc_conf_t::acc, brix_export_root_opts_t::allow_write, ngx_http_brix_shared_conf_t::allow_write, ngx_http_brix_webdav_loc_conf_t::auth, ngx_http_brix_webdav_loc_conf_t::authdb_rules, brix_vfs_backend_cred_t::bearer, brix_acc_http_merge_conf(), BRIX_AF_AUTO, brix_assert_dir_outside_export(), BRIX_AUTHZ_CAPABILITY, BRIX_CKS_FMT_TEXT, brix_credential_bearer(), brix_credential_lookup(), BRIX_CRL_MODE_TRY, brix_finalize_authdb_rules(), brix_finalize_vo_rules(), brix_http_common_adopt(), brix_http_mirror_setup(), brix_http_open_rootfd(), brix_integrity_set_xattr_format(), brix_jwks_load(), brix_jwks_register_cleanup(), BRIX_MAX_JWKS_KEYS, BRIX_MERGE_PTR, BRIX_MIRROR_M_DEFAULT, brix_prepare_export_root(), BRIX_SP_MODE_ON, brix_stage_dir_register(), brix_storage_backend_is_remote(), brix_storage_backend_posix_root(), brix_tier_register_stores(), brix_tmp_reap_register(), BRIX_TOKEN_CLOCK_SKEW_SECS, brix_token_registry_build(), brix_vfs_backend_config_str(), brix_vfs_backend_set_credential(), brix_vfs_backend_set_staging(), brix_voms_init(), brix_credential_t::ca_dir, brix_vfs_backend_cred_t::ca_dir, ngx_http_brix_webdav_loc_conf_t::ca_store, ngx_http_brix_webdav_loc_conf_t::cache_root, ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::cadir, ngx_http_brix_webdav_loc_conf_t::cafile, brix_export_root_opts_t::canon_size, ngx_http_brix_webdav_loc_conf_t::checksum_on_write, ngx_http_brix_webdav_loc_conf_t::checksum_xattr_format, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_loc_conf_t::cors_credentials, ngx_http_brix_webdav_loc_conf_t::cors_max_age, ngx_http_brix_webdav_loc_conf_t::crl, ngx_http_brix_webdav_loc_conf_t::crl_mode, ngx_http_brix_webdav_loc_conf_t::dig_auth_file, ngx_http_brix_webdav_loc_conf_t::dig_enable, ngx_http_brix_webdav_loc_conf_t::dig_exports, brix_export_root_opts_t::directive_name, ngx_http_brix_shared_conf_t::enable, brix_mirror_conf_t::enabled, ngx_http_brix_webdav_loc_conf_t::http_query_token, ngx_http_brix_webdav_loc_conf_t::introspect_fail_open, ngx_http_brix_webdav_loc_conf_t::introspect_loc, ngx_http_brix_webdav_loc_conf_t::introspect_ttl, ngx_http_brix_webdav_loc_conf_t::introspect_url, ngx_http_brix_webdav_loc_conf_t::jwks_key_count, ngx_http_brix_webdav_loc_conf_t::jwks_keys, brix_rate_limit_conf_t::kv, ngx_http_brix_webdav_loc_conf_t::lock_startup_sweep, ngx_http_brix_webdav_loc_conf_t::lock_timeout, brix_mirror_conf_t::log_diverge, ngx_http_brix_webdav_loc_conf_t::macaroon_location, ngx_http_brix_webdav_loc_conf_t::macaroon_max_validity, brix_mirror_conf_t::method_mask, ngx_http_brix_webdav_loc_conf_t::mirror, ngx_http_brix_webdav_loc_conf_t::mirror_upstream_conf, brix_mirror_conf_t::mirror_writes, ngx_http_brix_shared_merge(), ngx_http_brix_webdav_tpc_merge_loc_conf(), ngx_test_config, ngx_http_brix_webdav_loc_conf_t::open_file_cache, ngx_http_brix_webdav_loc_conf_t::open_file_cache_errors, ngx_http_brix_webdav_loc_conf_t::open_file_cache_events, ngx_http_brix_webdav_loc_conf_t::open_file_cache_min_uses, ngx_http_brix_webdav_loc_conf_t::open_file_cache_valid, ngx_http_brix_shared_conf_t::pblock_block_size, ngx_http_brix_webdav_loc_conf_t::proxy_certs, ngx_http_brix_webdav_loc_conf_t::proxy_pool_enabled, ngx_http_brix_webdav_loc_conf_t::rate_limit, brix_export_root_opts_t::required, ngx_http_brix_webdav_loc_conf_t::revoke_kv, ngx_http_brix_shared_conf_t::root, ngx_http_brix_shared_conf_t::root_canon, brix_credential_t::s3_access_key, brix_vfs_backend_cred_t::s3_access_key, brix_credential_t::s3_region, brix_vfs_backend_cred_t::s3_region, brix_credential_t::s3_secret_key, brix_vfs_backend_cred_t::s3_secret_key, brix_mirror_conf_t::sample_pct, ngx_http_brix_webdav_loc_conf_t::signing_policy_mode, brix_credential_t::sss_keytab, brix_vfs_backend_cred_t::sss_keytab, ngx_http_brix_shared_conf_t::storage_backend, ngx_http_brix_shared_conf_t::storage_credential, ngx_http_brix_shared_conf_t::storage_staging, brix_mirror_conf_t::strip_auth, ngx_http_brix_webdav_loc_conf_t::tape_rest, brix_mirror_conf_t::targets, ngx_http_brix_webdav_loc_conf_t::tcp_congestion, brix_mirror_conf_t::timeout_ms, brix_mirror_conf_t::token, ngx_http_brix_webdav_loc_conf_t::token_audience, ngx_http_brix_webdav_loc_conf_t::token_cache_kv, ngx_http_brix_webdav_loc_conf_t::token_clock_skew, ngx_http_brix_webdav_loc_conf_t::token_config, ngx_http_brix_webdav_loc_conf_t::token_issuer, ngx_http_brix_webdav_loc_conf_t::token_jwks, ngx_http_brix_webdav_loc_conf_t::token_macaroon_secret, ngx_http_brix_webdav_loc_conf_t::token_macaroon_secret_old, ngx_http_brix_webdav_loc_conf_t::token_registry, ngx_http_brix_webdav_loc_conf_t::tpc, ngx_http_brix_webdav_loc_conf_t::tpc_cadir, ngx_http_brix_webdav_loc_conf_t::tpc_cafile, ngx_http_brix_webdav_loc_conf_t::tpc_cert, ngx_http_brix_webdav_loc_conf_t::tpc_curl, ngx_http_brix_webdav_loc_conf_t::tpc_key, ngx_http_brix_webdav_loc_conf_t::upload_resume, ngx_http_brix_webdav_loc_conf_t::upload_stage_dir, ngx_http_brix_webdav_loc_conf_t::upload_stage_dir_canon, ngx_http_brix_webdav_loc_conf_t::upstream_auth, ngx_http_brix_webdav_loc_conf_t::upstream_auth_token, ngx_http_brix_webdav_loc_conf_t::upstream_backends, ngx_http_brix_webdav_loc_conf_t::upstream_conf, ngx_http_brix_webdav_loc_conf_t::upstream_fail_timeout, ngx_http_brix_webdav_loc_conf_t::upstream_host, ngx_http_brix_webdav_loc_conf_t::upstream_max_fails, ngx_http_brix_webdav_loc_conf_t::upstream_proxy, ngx_http_brix_webdav_loc_conf_t::upstream_resolved, ngx_http_brix_webdav_loc_conf_t::upstream_ssl, ngx_http_brix_webdav_loc_conf_t::upstream_url, ngx_http_brix_webdav_loc_conf_t::upstream_url_base, ngx_http_brix_webdav_loc_conf_t::upstream_urls, ngx_http_brix_webdav_loc_conf_t::verify_depth, ngx_http_brix_webdav_loc_conf_t::vo_rules, ngx_http_brix_webdav_loc_conf_t::voms_cert_dir, ngx_http_brix_webdav_loc_conf_t::vomsdir, WEBDAV_AUTH_OPTIONAL, WEBDAV_AUTH_REQUIRED, webdav_build_ca_store(), webdav_check_pki_consistency(), webdav_lock_startup_sweep(), webdav_log_endpoint_summary(), WEBDAV_PATH_DIRECTORY, WEBDAV_PATH_FILE_OR_DIRECTORY, WEBDAV_PATH_REGULAR_FILE, WEBDAV_PROXY_AUTH_ANONYMOUS, WEBDAV_PROXY_AUTH_TOKEN, webdav_proxy_build_backends(), webdav_proxy_pool_setup(), webdav_summary_is_new(), webdav_validate_cors_origins(), webdav_validate_path, webdav_x509_store_cleanup(), brix_credential_t::x509_proxy, brix_vfs_backend_cred_t::x509_proxy, ngx_http_brix_webdav_loc_conf_t::zip_access, and ngx_http_brix_webdav_loc_conf_t::zip_cd_max_bytes.
webdav_auth_name()
static const char * webdav_auth_name (ngx_uint_t auth) static
Definition at line 214 of file config.c.
References WEBDAV_AUTH_OPTIONAL, and WEBDAV_AUTH_REQUIRED.
Referenced by webdav_log_endpoint_summary().
webdav_log_endpoint_summary()
static void webdav_log_endpoint_summary (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 252 of file config.c.
References ngx_http_brix_shared_conf_t::allow_write, ngx_http_brix_webdav_loc_conf_t::auth, ngx_http_brix_webdav_loc_conf_t::cadir, ngx_http_brix_webdav_loc_conf_t::cafile, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_loc_conf_t::crl, ngx_http_brix_webdav_loc_conf_t::jwks_key_count, ngx_http_brix_webdav_loc_conf_t::proxy_certs, ngx_http_brix_shared_conf_t::root, ngx_http_brix_webdav_loc_conf_t::tpc, ngx_http_brix_webdav_loc_conf_t::upstream_proxy, ngx_http_brix_webdav_loc_conf_t::upstream_url, webdav_auth_name(), and WEBDAV_AUTH_REQUIRED.
Referenced by ngx_http_brix_webdav_merge_loc_conf().
webdav_summary_is_new()
static ngx_uint_t webdav_summary_is_new (ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_loc_conf_t * prev) static
Definition at line 230 of file config.c.
References ngx_http_brix_shared_conf_t::allow_write, ngx_http_brix_webdav_loc_conf_t::auth, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::enable, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by ngx_http_brix_webdav_merge_loc_conf().
webdav_validate_cors_origins()
static ngx_int_t webdav_validate_cors_origins (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 63 of file config.c.
References ngx_http_brix_webdav_loc_conf_t::cors_origins, and webdav_tpc_str_has_ctl.
Referenced by ngx_http_brix_webdav_merge_loc_conf().
webdav_x509_store_cleanup()
static void webdav_x509_store_cleanup (void * data) static
Definition at line 47 of file config.c.
Referenced by ngx_http_brix_webdav_merge_loc_conf().