nginx-xrootd: src/protocols/root/write/mkdir.c File Reference
mkdir.c File Reference
#include "core/ngx_brix_module.h"
#include "core/compat/error_mapping.h"
#include "fs/vfs/vfs.h"
#include "protocols/root/path/op_path.h"
#include "fs/vfs/vfs_backend_registry.h"
Functions
ngx_int_t brix_handle_mkdir (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_handle_mkdir()
ngx_int_t brix_handle_mkdir (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 28 of file mkdir.c.
References brix_apply_parent_group_policy_path(), brix_auth_gate(), BRIX_AUTH_MKDIR, brix_kxr_from_errno(), BRIX_MAX_PATH, BRIX_OP_MKDIR, BRIX_PATH_NOEXIST, BRIX_PATH_WRITE, BRIX_PROTO_ROOT, brix_resolve_op_path(), BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_root_vfs_bind_deleg(), brix_vfs_backend_resolve(), brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), brix_vfs_mkdir(), c, brix_ctx_recv_t::hdr_buf, brix_ctx_t::identity, kXR_ItExists, kXR_mkdirpath, xrdw_mkdir_req_t::mode, xrdw_mkdir_req_t::options, PATH_MAX, brix_vfs_ctx_t::pool, brix_ctx_t::recv, brix_ctx_t::write_rc, and xrdw_mkdir_req_unpack().