nginx-xrootd: src/protocols/root/response/crc32c.c File Reference
crc32c.c File Reference
#include "core/ngx_brix_module.h"
#include "core/compat/crc32c.h"
#include "core/compat/checksum.h"
Functions
uint32_t brix_crc32c (const void *buf, size_t len)
uint32_t brix_crc32c_copy (const u_char *src, u_char *dst, size_t len)
uint32_t brix_crc32c_file (int fd, const char *path, ngx_log_t *log)
Function Documentation
brix_crc32c()
uint32_t brix_crc32c (const void * buf, size_t len)
Definition at line 16 of file crc32c.c.
References brix_crc32c_value().
Referenced by brix_build_pgread_status(), brix_send_pgwrite_cse(), and brix_send_pgwrite_status().
brix_crc32c_copy()
uint32_t brix_crc32c_copy (const u_char * src, u_char * dst, size_t len)
Definition at line 25 of file crc32c.c.
References brix_crc32c_copy_value().
brix_crc32c_file()
uint32_t brix_crc32c_file (int fd, const char * path, ngx_log_t * log)
Definition at line 39 of file crc32c.c.
References BRIX_CHECKSUM_CRC32C, brix_checksum_u32_fd(), and log.