nginx-xrootd: src/protocols/s3/metrics.c File Reference
metrics.c File Reference
#include "s3.h"
#include "core/http/http_headers.h"
#include "core/http/sesslog_conn.h"
#include "observability/metrics/http_common.h"
#include "observability/metrics/unified.h"
Functions
static brix_metric_op_t s3_unified_op (ngx_uint_t method_slot)
static brix_sess_mode_t s3_sess_mode (ngx_uint_t method_slot)
static brix_sess_am_t s3_sess_auth_method (const ngx_http_s3_req_ctx_t *ctx)
static const char * s3_sess_user (const ngx_http_s3_req_ctx_t *ctx)
static brix_sess_t * s3_sess (ngx_http_request_t *r)
static int s3_sess_method_has_xfer (ngx_uint_t method_slot)
static int64_t s3_sess_xfer_expected (ngx_http_request_t *r, brix_sess_mode_t mode)
static uint64_t s3_sess_xfer_bytes (ngx_http_request_t *r, brix_sess_mode_t mode, int64_t expected)
static void s3_sess_start_xfer (ngx_http_request_t *r, brix_sess_t *sess, const char *path, ngx_uint_t method_slot)
static void s3_sess_finish_xfer (ngx_http_request_t *r, brix_sess_t *sess, ngx_uint_t method_slot, ngx_uint_t http_status)
void s3_sess_begin_request (ngx_http_request_t *r, ngx_uint_t method_slot)
void s3_sess_attempt_request (ngx_http_request_t *r, ngx_uint_t method_slot)
ngx_uint_t s3_metrics_method_slot (ngx_http_request_t *r)
void s3_metrics_request_method (ngx_uint_t method_slot)
void s3_metrics_response_status (ngx_uint_t method_slot, ngx_uint_t http_status)
void s3_metrics_response_method (ngx_http_request_t *r, ngx_uint_t method_slot, ngx_int_t handler_rc)
ngx_int_t s3_metrics_return_method (ngx_http_request_t *r, ngx_uint_t method_slot, ngx_int_t handler_rc)
void s3_metrics_finalize_request_method (ngx_http_request_t *r, ngx_uint_t method_slot, ngx_int_t handler_rc)
Function Documentation
s3_metrics_finalize_request_method()
void s3_metrics_finalize_request_method (ngx_http_request_t * r, ngx_uint_t method_slot, ngx_int_t handler_rc)
Definition at line 321 of file metrics.c.
References s3_metrics_response_method().
Referenced by s3_delete_async_render(), s3_delete_objects_body_handler_inner(), s3_delete_objects_finish(), s3_delete_parse_body(), s3_delete_run_batch(), s3_mpu_aio_done(), s3_mpu_send_result(), s3_multipart_complete_body_handler_inner(), s3_post_object_body_handler_inner(), s3_put_finalize_bad_digest(), s3_put_finalize_client_error(), s3_put_finalize_codec_error(), s3_put_finalize_empty_ok(), s3_put_finalize_error(), s3_put_finalize_fs_error(), s3_put_finalize_invalid_digest(), and s3_put_finalize_invalid_request().
s3_metrics_method_slot()
ngx_uint_t s3_metrics_method_slot (ngx_http_request_t * r)
Definition at line 246 of file metrics.c.
References brix_http_operation_find(), BRIX_S3_METHOD_OTHER, brix_s3_operations, brix_s3_operations_count, and op.
Referenced by ngx_http_s3_handler(), s3_delete_objects_body_handler_inner(), and s3_multipart_complete_body_handler_inner().
s3_metrics_request_method()
void s3_metrics_request_method (ngx_uint_t method_slot)
Definition at line 257 of file metrics.c.
References BRIX_S3_METHOD_OTHER, BRIX_S3_METRIC_INC, and BRIX_S3_NMETHODS.
Referenced by ngx_http_s3_handler().
s3_metrics_response_method()
void s3_metrics_response_method (ngx_http_request_t * r, ngx_uint_t method_slot, ngx_int_t handler_rc)
Definition at line 283 of file metrics.c.
References brix_http_effective_status(), brix_http_sess_uri(), brix_sess_result(), brix_sesslog_err_from_http(), BRIX_SESSLOG_ERR_MAX, BRIX_SESSLOG_PATH_MAX, s3_metrics_response_status(), s3_sess(), s3_sess_finish_xfer(), and s3_sess_mode().
Referenced by s3_metrics_finalize_request_method(), and s3_metrics_return_method().
s3_metrics_response_status()
void s3_metrics_response_status (ngx_uint_t method_slot, ngx_uint_t http_status)
Definition at line 267 of file metrics.c.
References brix_http_status_class(), brix_metric_err_from_http_status(), brix_metric_op_done(), BRIX_PROTO_S3, BRIX_S3_METHOD_OTHER, BRIX_S3_METRIC_INC, BRIX_S3_NMETHODS, and s3_unified_op().
Referenced by s3_metrics_response_method().
s3_metrics_return_method()
ngx_int_t s3_metrics_return_method (ngx_http_request_t * r, ngx_uint_t method_slot, ngx_int_t handler_rc)
Definition at line 313 of file metrics.c.
References s3_metrics_response_method().
Referenced by ngx_http_s3_handler(), s3_apply_put_precondition(), s3_check_token_scope(), s3_dispatch_after_auth(), s3_dispatch_bucket_get(), s3_dispatch_empty_key(), s3_dispatch_object_delete(), s3_dispatch_object_get(), s3_dispatch_object_method(), s3_dispatch_object_post(), s3_dispatch_object_put(), s3_dispatch_parse_uri(), s3_prepare_upload_part(), s3_read_body_metric(), s3_reject_write_disabled(), and s3_resolve_object_key().
s3_sess()
static brix_sess_t * s3_sess (ngx_http_request_t * r) static
Definition at line 113 of file metrics.c.
References brix_http_sess(), BRIX_SESS_PROTO_S3, ngx_http_s3_loc_conf_t::common, ngx_http_brix_s3_module, and s3_sess_auth_method().
Referenced by s3_metrics_response_method(), s3_sess_attempt_request(), and s3_sess_begin_request().
s3_sess_attempt_request()
void s3_sess_attempt_request (ngx_http_request_t * r, ngx_uint_t method_slot)
Definition at line 234 of file metrics.c.
References brix_http_sess_uri(), brix_sess_attempt(), BRIX_SESSLOG_PATH_MAX, s3_sess(), s3_sess_mode(), and s3_sess_start_xfer().
Referenced by ngx_http_s3_handler().
s3_sess_auth_method()
static brix_sess_am_t s3_sess_auth_method (const ngx_http_s3_req_ctx_t * ctx) static
Definition at line 77 of file metrics.c.
References brix_identity_t::auth_method, BRIX_AUTHN_S3KEY, BRIX_AUTHN_TOKEN, BRIX_SESS_AM_ANON, BRIX_SESS_AM_SIGV4, BRIX_SESS_AM_TOKEN, and ngx_http_s3_req_ctx_t::identity.
Referenced by s3_sess(), and s3_sess_begin_request().
s3_sess_begin_request()
void s3_sess_begin_request (ngx_http_request_t * r, ngx_uint_t method_slot)
Definition at line 219 of file metrics.c.
References brix_sess_auth_once(), ngx_http_brix_s3_module, s3_sess(), s3_sess_auth_method(), and s3_sess_user().
Referenced by ngx_http_s3_handler().
s3_sess_finish_xfer()
static void s3_sess_finish_xfer (ngx_http_request_t * r, brix_sess_t * sess, ngx_uint_t method_slot, ngx_uint_t http_status) static
Definition at line 190 of file metrics.c.
References BRIX_SESS_XFER_ABORTED, brix_sess_xfer_add(), BRIX_SESS_XFER_COMPLETE, brix_sess_xfer_end(), brix_sess_xfer_t::bytes, brix_sess_xfer_t::expected, ngx_http_brix_s3_module, s3_sess_mode(), s3_sess_xfer_bytes(), s3_sess_xfer_expected(), ngx_http_s3_req_ctx_t::sess_xfer, and ngx_http_s3_req_ctx_t::sess_xfer_started.
Referenced by s3_metrics_response_method().
s3_sess_method_has_xfer()
static int s3_sess_method_has_xfer (ngx_uint_t method_slot) static
Definition at line 126 of file metrics.c.
References BRIX_S3_METHOD_GET, and BRIX_S3_METHOD_PUT.
Referenced by s3_sess_start_xfer().
s3_sess_mode()
static brix_sess_mode_t s3_sess_mode (ngx_uint_t method_slot) static
Definition at line 58 of file metrics.c.
References BRIX_S3_METHOD_DELETE, BRIX_S3_METHOD_GET, BRIX_S3_METHOD_HEAD, BRIX_S3_METHOD_LIST, BRIX_S3_METHOD_POST, BRIX_S3_METHOD_PUT, BRIX_SESS_MODE_DELETE, BRIX_SESS_MODE_LIST, BRIX_SESS_MODE_META, BRIX_SESS_MODE_READ, and BRIX_SESS_MODE_WRITE.
Referenced by s3_metrics_response_method(), s3_sess_attempt_request(), s3_sess_finish_xfer(), and s3_sess_start_xfer().
s3_sess_start_xfer()
static void s3_sess_start_xfer (ngx_http_request_t * r, brix_sess_t * sess, const char * path, ngx_uint_t method_slot) static
Definition at line 170 of file metrics.c.
References brix_sess_xfer_t::active, brix_sess_xfer_start(), ngx_http_brix_s3_module, s3_sess_method_has_xfer(), s3_sess_mode(), ngx_http_s3_req_ctx_t::sess_xfer, and ngx_http_s3_req_ctx_t::sess_xfer_started.
Referenced by s3_sess_attempt_request().
s3_sess_user()
static const char * s3_sess_user (const ngx_http_s3_req_ctx_t * ctx) static
Definition at line 95 of file metrics.c.
References brix_identity_dn_cstr(), brix_identity_subject_cstr(), and ngx_http_s3_req_ctx_t::identity.
Referenced by s3_sess_begin_request().
s3_sess_xfer_bytes()
static uint64_t s3_sess_xfer_bytes (ngx_http_request_t * r, brix_sess_mode_t mode, int64_t expected) static
Definition at line 153 of file metrics.c.
References BRIX_SESS_MODE_READ, and BRIX_SESS_MODE_WRITE.
Referenced by s3_sess_finish_xfer().
s3_sess_xfer_expected()
static int64_t s3_sess_xfer_expected (ngx_http_request_t * r, brix_sess_mode_t mode) static
Definition at line 133 of file metrics.c.
References BRIX_SESS_MODE_READ, and BRIX_SESS_MODE_WRITE.
Referenced by s3_sess_finish_xfer().
s3_unified_op()
static brix_metric_op_t s3_unified_op (ngx_uint_t method_slot) static
Definition at line 38 of file metrics.c.
References BRIX_METRIC_OP_DELETE, BRIX_METRIC_OP_DIRLIST, BRIX_METRIC_OP_READ, BRIX_METRIC_OP_STAT, BRIX_METRIC_OP_WRITE, BRIX_S3_METHOD_DELETE, BRIX_S3_METHOD_GET, BRIX_S3_METHOD_HEAD, BRIX_S3_METHOD_LIST, BRIX_S3_METHOD_POST, and BRIX_S3_METHOD_PUT.
Referenced by s3_metrics_response_status().