nginx-xrootd: src/protocols/shared/proto_exclusive.c File Reference
proto_exclusive.c File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include "protocols/shared/proto_exclusive.h"
#include "protocols/webdav/webdav.h"
#include "protocols/s3/s3.h"
#include "protocols/cvmfs/cvmfs.h"
Macros
#define BRIX_PROTO_NONE 0u
#define BRIX_PROTO_WEBDAV (1u << 0)
#define BRIX_PROTO_S3 (1u << 1)
#define BRIX_PROTO_CVMFS (1u << 2)
Functions
static const char * brix_proto_name (ngx_uint_t bit)
static ngx_uint_t brix_proto_mask (void **loc_conf)
static ngx_int_t brix_proto_add_level (ngx_conf_t *cf, void **loc_conf, ngx_str_t *name, ngx_uint_t *server_mask)
static ngx_int_t brix_proto_walk_location (ngx_conf_t *cf, ngx_http_core_loc_conf_t *clcf, ngx_uint_t *server_mask)
static ngx_int_t brix_proto_walk_loc_array (ngx_conf_t *cf, ngx_http_core_loc_conf_t **arr, ngx_uint_t *server_mask)
static ngx_int_t brix_proto_walk_tree (ngx_conf_t *cf, ngx_http_location_tree_node_t *node, ngx_uint_t *server_mask)
static ngx_int_t brix_proto_server_mask (ngx_conf_t *cf, ngx_http_core_srv_conf_t *cscf, ngx_uint_t *mask)
ngx_int_t brix_http_proto_exclusive_check (ngx_conf_t *cf)
Macro Definition Documentation
BRIX_PROTO_CVMFS
#define BRIX_PROTO_CVMFS (1u << 2)
Definition at line 40 of file proto_exclusive.c.
BRIX_PROTO_NONE
#define BRIX_PROTO_NONE 0u
Definition at line 37 of file proto_exclusive.c.
BRIX_PROTO_S3
#define BRIX_PROTO_S3 (1u << 1)
Definition at line 39 of file proto_exclusive.c.
BRIX_PROTO_WEBDAV
#define BRIX_PROTO_WEBDAV (1u << 0)
Definition at line 38 of file proto_exclusive.c.
Function Documentation
brix_http_proto_exclusive_check()
ngx_int_t brix_http_proto_exclusive_check (ngx_conf_t * cf)
Definition at line 271 of file proto_exclusive.c.
References brix_proto_name(), BRIX_PROTO_NONE, brix_proto_server_mask(), and s.
Referenced by ngx_http_brix_webdav_postconfiguration().
brix_proto_add_level()
static ngx_int_t brix_proto_add_level (ngx_conf_t * cf, void ** loc_conf, ngx_str_t * name, ngx_uint_t * server_mask) static
Definition at line 103 of file proto_exclusive.c.
References brix_proto_mask(), and name.
Referenced by brix_proto_server_mask(), and brix_proto_walk_location().
brix_proto_mask()
static ngx_uint_t brix_proto_mask (void ** loc_conf) static
Definition at line 70 of file proto_exclusive.c.
References BRIX_PROTO_CVMFS, BRIX_PROTO_NONE, BRIX_PROTO_S3, BRIX_PROTO_WEBDAV, c, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::enable, ngx_http_brix_cvmfs_module, ngx_http_brix_s3_module, ngx_http_brix_webdav_module, and s.
Referenced by brix_proto_add_level().
brix_proto_name()
static const char * brix_proto_name (ngx_uint_t bit) static
Definition at line 50 of file proto_exclusive.c.
References BRIX_PROTO_S3, and BRIX_PROTO_WEBDAV.
Referenced by brix_http_proto_exclusive_check().
brix_proto_server_mask()
static ngx_int_t brix_proto_server_mask (ngx_conf_t * cf, ngx_http_core_srv_conf_t * cscf, ngx_uint_t * mask) static
Definition at line 232 of file proto_exclusive.c.
References brix_proto_add_level(), brix_proto_walk_loc_array(), and brix_proto_walk_tree().
Referenced by brix_http_proto_exclusive_check().
brix_proto_walk_loc_array()
static ngx_int_t brix_proto_walk_loc_array (ngx_conf_t * cf, ngx_http_core_loc_conf_t ** arr, ngx_uint_t * server_mask) static
Definition at line 132 of file proto_exclusive.c.
References brix_proto_walk_location().
Referenced by brix_proto_server_mask(), and brix_proto_walk_location().
brix_proto_walk_location()
static ngx_int_t brix_proto_walk_location (ngx_conf_t * cf, ngx_http_core_loc_conf_t * clcf, ngx_uint_t * server_mask) static
Definition at line 195 of file proto_exclusive.c.
References brix_proto_add_level(), brix_proto_walk_loc_array(), and brix_proto_walk_tree().
Referenced by brix_proto_walk_loc_array(), and brix_proto_walk_tree().
brix_proto_walk_tree()
static ngx_int_t brix_proto_walk_tree (ngx_conf_t * cf, ngx_http_location_tree_node_t * node, ngx_uint_t * server_mask) static
Definition at line 158 of file proto_exclusive.c.
References brix_proto_walk_location(), and brix_proto_walk_tree().
Referenced by brix_proto_server_mask(), brix_proto_walk_location(), and brix_proto_walk_tree().