nginx-xrootd: src/protocols/root/read/readv.c File Reference
readv.c File Reference
#include "read.h"
#include "fs/backend/sd.h"
#include "core/compat/safe_size.h"
#include "core/ngx_brix_module.h"
#include "protocols/root/connection/budget.h"
#include "prefetch.h"
#include "core/compat/range_vector.h"
#include "protocols/root/protocol/readv_seg.h"
#include <stdlib.h>
#include <sys/uio.h>
Data Structures
struct brix_readv_req_t
Macros
#define BRIX_MAX_READV_TOTAL (256u * 1024u * 1024u)
Functions
static ngx_flag_t brix_readv_validate_and_size (brix_ctx_t *ctx, ngx_connection_t *c, brix_readv_req_t *req, ngx_int_t *rc_out)
static void brix_readv_build_descriptors (brix_ctx_t *ctx, brix_readv_req_t *req)
static ngx_flag_t brix_readv_try_post_async (brix_ctx_t *ctx, ngx_connection_t *c, brix_readv_req_t *req, ngx_int_t *rc_out)
static ngx_int_t brix_readv_execute_sync (brix_ctx_t *ctx, ngx_connection_t *c, brix_readv_req_t *req)
ngx_int_t brix_handle_readv (brix_ctx_t *ctx, ngx_connection_t *c)
Macro Definition Documentation
BRIX_MAX_READV_TOTAL
#define BRIX_MAX_READV_TOTAL (256u * 1024u * 1024u)
Definition at line 14 of file readv.c.
Function Documentation
brix_handle_readv()
ngx_int_t brix_handle_readv (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 331 of file readv.c.
References brix_alloc_array(), brix_budget_admit(), brix_budget_sync(), BRIX_GET_SCRATCH, BRIX_OP_ERR, BRIX_OP_READV, brix_prefetch_readv_segments(), brix_readv_build_descriptors(), brix_readv_execute_sync(), BRIX_READV_MAXSEGS, BRIX_READV_SEGSIZE, brix_readv_try_post_async(), brix_readv_validate_and_size(), brix_release_read_buffer(), brix_send_error(), brix_send_wait(), c, brix_ctx_recv_t::cur_dlen, kXR_ArgInvalid, kXR_ArgTooLong, brix_readv_req_t::max_response_bytes, ngx_stream_brix_module, brix_ctx_recv_t::payload, brix_readv_req_t::rconf, brix_readv_req_t::readv_seg_max, brix_ctx_t::recv, brix_readv_req_t::response_buffer, brix_readv_req_t::segment_count, brix_readv_req_t::segment_descs, and brix_readv_req_t::wire_segments.
Referenced by brix_dispatch_read_opcode().
brix_readv_build_descriptors()
static void brix_readv_build_descriptors (brix_ctx_t * ctx, brix_readv_req_t * req) static
Definition at line 122 of file readv.c.
References BRIX_READV_SEGSIZE, brix_file_t::fd, brix_vfs_readv_seg_t::fd, readahead_list::fhandle, brix_ctx_t::files, brix_vfs_readv_seg_t::handle_index, brix_vfs_readv_seg_t::header_read_length_ptr, ngx_memcpy, brix_vfs_readv_seg_t::obj, brix_vfs_readv_seg_t::offset, readahead_list::offset, brix_vfs_readv_seg_t::payload_ptr, brix_vfs_readv_seg_t::read_length, brix_readv_req_t::readv_seg_max, brix_readv_req_t::response_buffer, readahead_list::rlen, brix_file_t::sd_obj, brix_readv_req_t::segment_count, brix_readv_req_t::segment_descs, and brix_readv_req_t::wire_segments.
Referenced by brix_handle_readv().
brix_readv_execute_sync()
static ngx_int_t brix_readv_execute_sync (brix_ctx_t * ctx, ngx_connection_t * c, brix_readv_req_t * req) static
Definition at line 259 of file readv.c.
References brix_build_chunked_chain(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_READV, brix_queue_response_chain(), brix_release_read_buffer(), brix_send_error(), brix_vfs_io_execute(), BRIX_VFS_IO_READV, brix_ctx_totals_t::bytes, brix_file_t::bytes_read, c, brix_vfs_job_t::err_msg, brix_vfs_job_t::err_msg_cap, brix_ctx_t::files, brix_vfs_readv_seg_t::handle_index, brix_vfs_job_t::io_errno, kXR_IOError, brix_vfs_job_t::nio, brix_vfs_job_t::nsegs, brix_vfs_job_t::op, brix_vfs_job_t::out_size, brix_readv_req_t::rconf, brix_vfs_readv_seg_t::read_length, brix_readv_req_t::response_buffer, brix_readv_req_t::segment_count, brix_readv_req_t::segment_descs, brix_vfs_job_t::segs, brix_ctx_t::state, brix_ctx_t::totals, and XRD_ST_SENDING.
Referenced by brix_handle_readv().
brix_readv_try_post_async()
static ngx_flag_t brix_readv_try_post_async (brix_ctx_t * ctx, ngx_connection_t * c, brix_readv_req_t * req, ngx_int_t * rc_out) static
Definition at line 188 of file readv.c.
References brix_aio_post_task(), brix_readv_aio_done(), brix_readv_aio_thread(), brix_release_read_buffer(), brix_readv_aio_t::bytes_read_total, c, brix_readv_aio_t::c, brix_readv_aio_t::ctx, brix_ctx_recv_t::cur_streamid, brix_readv_aio_t::io_error, brix_readv_req_t::rconf, brix_ctx_t::rd, brix_ctx_rd_t::readv_aio_task, brix_ctx_t::recv, brix_readv_aio_t::response_buffer, brix_readv_req_t::response_buffer, brix_readv_aio_t::response_bytes, brix_readv_aio_t::segment_count, brix_readv_req_t::segment_count, brix_readv_req_t::segment_descs, brix_readv_aio_t::segments, and brix_readv_aio_t::streamid.
Referenced by brix_handle_readv().
brix_readv_validate_and_size()
static ngx_flag_t brix_readv_validate_and_size (brix_ctx_t * ctx, ngx_connection_t * c, brix_readv_req_t * req, ngx_int_t * rc_out) static
Definition at line 62 of file readv.c.
References BRIX_MAX_READV_TOTAL, BRIX_OP_ERR, BRIX_OP_READV, BRIX_READV_SEGSIZE, brix_send_error(), brix_validate_read_handle(), c, readahead_list::fhandle, kXR_ArgTooLong, brix_readv_req_t::max_response_bytes, brix_readv_req_t::readv_seg_max, readahead_list::rlen, brix_readv_req_t::segment_count, and brix_readv_req_t::wire_segments.
Referenced by brix_handle_readv().