nginx-xrootd: src/protocols/root/session/registry.h File Reference
registry.h File Reference
#include "core/ngx_brix_module.h"
Data Structures
struct brix_session_entry_t
struct brix_shared_handle_entry_t
struct brix_session_table_t
struct brix_shared_handle_table_t
Macros
#define BRIX_SESSION_REGISTRY_SLOTS 1024
#define BRIX_SESSION_HANDLE_SESSIONS 512
#define BRIX_SESSION_HANDLES_PER_SESSION 8
#define BRIX_SESSION_HANDLE_SLOTS (BRIX_SESSION_HANDLE_SESSIONS * BRIX_SESSION_HANDLES_PER_SESSION)
#define BRIX_SESSION_REAP_MIN_AGE_MS 60000
Functions
ngx_int_t brix_session_shm_init_zone (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t brix_handle_shm_init_zone (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t brix_configure_session_registry (ngx_conf_t *cf, ngx_uint_t slots)
void brix_session_register (const u_char sessid[16], const char *dn, const char *vo_list, ngx_uint_t token_auth)
int brix_session_lookup (const u_char sessid[16], char *dn_out, size_t dn_size, char *vo_out, size_t vo_size, ngx_uint_t *token_auth_out)
void brix_session_unregister (const u_char sessid[16])
void brix_session_handle_publish (const u_char sessid[16], int handle_index, const brix_file_t *file)
int brix_session_handle_lookup (const u_char sessid[16], int handle_index, brix_shared_handle_entry_t *out)
int brix_session_handle_lookup_hint (const u_char sessid[16], int handle_index, int *inout_slot, brix_shared_handle_entry_t *out)
void brix_session_handle_unpublish (const u_char sessid[16], int handle_index)
void brix_session_handle_unpublish_all (const u_char sessid[16])
Variables
ngx_shm_zone_t * brix_session_shm_zone
ngx_shm_zone_t * brix_handle_shm_zone
Macro Definition Documentation
BRIX_SESSION_HANDLE_SESSIONS
#define BRIX_SESSION_HANDLE_SESSIONS 512
Definition at line 53 of file registry.h.
BRIX_SESSION_HANDLE_SLOTS
#define BRIX_SESSION_HANDLE_SLOTS (BRIX_SESSION_HANDLE_SESSIONS * BRIX_SESSION_HANDLES_PER_SESSION)
Definition at line 55 of file registry.h.
BRIX_SESSION_HANDLES_PER_SESSION
#define BRIX_SESSION_HANDLES_PER_SESSION 8
Definition at line 54 of file registry.h.
BRIX_SESSION_REAP_MIN_AGE_MS
#define BRIX_SESSION_REAP_MIN_AGE_MS 60000
Definition at line 77 of file registry.h.
BRIX_SESSION_REGISTRY_SLOTS
#define BRIX_SESSION_REGISTRY_SLOTS 1024
Definition at line 30 of file registry.h.
Function Documentation
brix_configure_session_registry()
ngx_int_t brix_configure_session_registry (ngx_conf_t * cf, ngx_uint_t slots)
Definition at line 74 of file registry.c.
brix_handle_shm_init_zone()
ngx_int_t brix_handle_shm_init_zone (ngx_shm_zone_t * shm_zone, void * data)
Definition at line 35 of file handles.c.
References brix_handle_mutex, and brix_shm_table_alloc().
Referenced by brix_configure_session_registry().
brix_session_handle_lookup()
int brix_session_handle_lookup (const u_char sessid[16], int handle_index, brix_shared_handle_entry_t * out)
Definition at line 249 of file handles.c.
References brix_session_handle_lookup_hint().
Referenced by brix_proxy_lazy_open().
brix_session_handle_lookup_hint()
int brix_session_handle_lookup_hint (const u_char sessid[16], int handle_index, int * inout_slot, brix_shared_handle_entry_t * out)
Definition at line 192 of file handles.c.
References brix_handle_mutex, BRIX_MAX_FILES, BRIX_MAX_PATH, BRIX_SESSION_HANDLE_SLOTS, brix_shared_handle_same_key(), handle_table(), ngx_memcpy, brix_shared_handle_entry_t::path, and brix_shared_handle_table_t::slots.
Referenced by brix_ensure_read_handle(), and brix_session_handle_lookup().
brix_session_handle_publish()
void brix_session_handle_publish (const u_char sessid[16], int handle_index, const brix_file_t * file)
Definition at line 84 of file handles.c.
References brix_handle_mutex, BRIX_MAX_FILES, BRIX_MAX_PATH, BRIX_SESSION_HANDLE_SLOTS, BRIX_SESSION_ID_LEN, brix_shared_handle_same_key(), brix_file_t::cached_size, brix_shared_handle_entry_t::cached_size, brix_file_t::device, brix_shared_handle_entry_t::device, brix_file_t::fd, brix_file_t::from_cache, brix_shared_handle_entry_t::from_cache, brix_shared_handle_entry_t::handle_index, handle_table(), brix_shared_handle_entry_t::in_use, brix_file_t::inode, brix_shared_handle_entry_t::inode, brix_file_t::is_regular, brix_shared_handle_entry_t::is_regular, ngx_memcpy, brix_file_t::path, brix_shared_handle_entry_t::path, brix_file_t::readable, brix_shared_handle_entry_t::readable, brix_shared_handle_entry_t::sessid, brix_shared_handle_table_t::slots, brix_file_t::writable, and brix_shared_handle_entry_t::writable.
Referenced by brix_open_resolved_file(), brix_tpc_prepare_pull(), and brix_zip_open_member().
brix_session_handle_unpublish()
void brix_session_handle_unpublish (const u_char sessid[16], int handle_index)
Definition at line 263 of file handles.c.
References brix_handle_mutex, BRIX_MAX_FILES, BRIX_SESSION_HANDLE_SLOTS, brix_shared_handle_same_key(), handle_table(), and brix_shared_handle_table_t::slots.
Referenced by brix_free_fhandle().
brix_session_handle_unpublish_all()
void brix_session_handle_unpublish_all (const u_char sessid[16])
Definition at line 300 of file handles.c.
References brix_handle_mutex, BRIX_SESSION_HANDLE_SLOTS, BRIX_SESSION_ID_LEN, handle_table(), brix_shared_handle_entry_t::in_use, brix_shared_handle_entry_t::sessid, and brix_shared_handle_table_t::slots.
Referenced by brix_session_register(), and brix_session_unregister().
brix_session_lookup()
int brix_session_lookup (const u_char sessid[16], char * dn_out, size_t dn_size, char * vo_out, size_t vo_size, ngx_uint_t * token_auth_out)
Definition at line 211 of file registry.c.
References BRIX_SESSION_ID_LEN, brix_session_mutex, brix_session_table_t::capacity, brix_session_entry_t::dn, brix_session_entry_t::in_use, brix_session_entry_t::last_seen, brix_session_entry_t::sessid, session_table(), brix_session_table_t::slots, brix_session_entry_t::token_auth, and brix_session_entry_t::vo_list.
Referenced by brix_handle_bind().
brix_session_register()
void brix_session_register (const u_char sessid[16], const char * dn, const char * vo_list, ngx_uint_t token_auth)
Definition at line 118 of file registry.c.
References brix_metrics_shared(), brix_session_handle_unpublish_all(), BRIX_SESSION_ID_LEN, brix_session_mutex, BRIX_SESSION_REAP_MIN_AGE_MS, brix_session_table_t::capacity, brix_session_entry_t::dn, brix_session_entry_t::in_use, brix_session_entry_t::last_seen, ngx_memcpy, brix_session_entry_t::sessid, ngx_brix_metrics_t::session_evict_total, ngx_brix_metrics_t::session_registry_full_total, session_table(), brix_session_table_t::slots, brix_session_entry_t::token_auth, and brix_session_entry_t::vo_list.
Referenced by brix_gsi_complete_auth(), brix_handle_host_auth(), brix_handle_krb5_auth(), brix_handle_login(), brix_handle_sss_auth(), brix_handle_token_auth(), brix_handle_unix_auth(), and pwd_round2().
brix_session_shm_init_zone()
ngx_int_t brix_session_shm_init_zone (ngx_shm_zone_t * shm_zone, void * data)
Definition at line 42 of file registry.c.
References brix_session_mutex, brix_session_registry_nslots, brix_shm_table_alloc(), and brix_session_table_t::capacity.
Referenced by brix_configure_session_registry().
brix_session_unregister()
void brix_session_unregister (const u_char sessid[16])
Definition at line 250 of file registry.c.
References brix_session_handle_unpublish_all(), BRIX_SESSION_ID_LEN, brix_session_mutex, brix_session_table_t::capacity, brix_session_entry_t::in_use, brix_session_entry_t::sessid, session_table(), and brix_session_table_t::slots.
Referenced by brix_handle_endsess(), and brix_on_disconnect().
Variable Documentation
brix_handle_shm_zone
ngx_shm_zone_t* brix_handle_shm_zone extern
Definition at line 17 of file registry.c.
Referenced by brix_configure_session_registry(), and handle_table().
brix_session_shm_zone
ngx_shm_zone_t* brix_session_shm_zone extern
Definition at line 16 of file registry.c.
Referenced by brix_configure_session_registry(), and session_table().