nginx-xrootd: src/protocols/webdav/access.c File Reference
access.c File Reference
#include "webdav.h"
#include "observability/metrics/unified.h"
#include "auth/authz/acc/acc.h"
#include "fs/path/path.h"
#include "webdav_tpc.h"
#include "protocols/shared/deleg_capture.h"
#include "fs/backend/sd.h"
Functions
static brix_acc_op_t webdav_method_aop (ngx_http_request_t *r)
static ngx_int_t webdav_acc_check (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static int webdav_is_write_method (ngx_http_request_t *r)
static int access_is_mirror_subrequest (ngx_http_request_t *r)
static void access_count_request (ngx_http_request_t *r)
static ngx_int_t access_rate_limit (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t access_options_preflight (ngx_http_request_t *r)
static ngx_int_t access_try_cert (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t access_try_token (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t access_try_basic (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t access_basic_challenge (ngx_http_request_t *r)
static ngx_int_t access_authenticate (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t access_capture_deleg_proxy (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t access_apply_authdb (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static int access_is_oauth_endpoint (ngx_http_request_t *r)
static ngx_int_t access_check_scope (ngx_http_request_t *r)
ngx_int_t ngx_http_brix_webdav_access_handler (ngx_http_request_t *r)
void webdav_vfs_bind_deleg (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, brix_vfs_ctx_t *vctx)
Function Documentation
access_apply_authdb()
static ngx_int_t access_apply_authdb (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 457 of file access.c.
References ngx_http_brix_webdav_loc_conf_t::authdb_rules, BRIX_AUTH_READ, brix_check_authdb_identity(), brix_check_vo_acl_identity(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), ngx_memcpy, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, brix_authdb_query_t::rules, ngx_http_brix_webdav_loc_conf_t::vo_rules, webdav_is_write_method(), and webdav_metrics_return().
Referenced by ngx_http_brix_webdav_access_handler().
access_authenticate()
static ngx_int_t access_authenticate (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 358 of file access.c.
References access_basic_challenge(), access_try_basic(), access_try_cert(), access_try_token(), ngx_http_brix_webdav_loc_conf_t::auth, BRIX_AUTHN_NONE, brix_metric_auth(), BRIX_PROTO_WEBDAV, BRIX_WEBDAV_AUTH_RESULT_ANONYMOUS, BRIX_WEBDAV_AUTH_RESULT_NONE, BRIX_WEBDAV_AUTH_RESULT_REJECTED, BRIX_WEBDAV_METRIC_INC, ngx_http_brix_webdav_loc_conf_t::pwd_file, WEBDAV_AUTH_NONE, WEBDAV_AUTH_REQUIRED, and webdav_metrics_return().
Referenced by ngx_http_brix_webdav_access_handler().
access_basic_challenge()
static ngx_int_t access_basic_challenge (ngx_http_request_t * r) static
Definition at line 325 of file access.c.
Referenced by access_authenticate().
access_capture_deleg_proxy()
static ngx_int_t access_capture_deleg_proxy (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 415 of file access.c.
References ngx_http_brix_shared_conf_t::backend_delegation, BRIX_CRED_SELECT, brix_proto_deleg_capture_proxy_header(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::deleg_proxy_pem, ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, and webdav_metrics_return().
Referenced by ngx_http_brix_webdav_access_handler().
access_check_scope()
static ngx_int_t access_check_scope (ngx_http_request_t * r) static
Definition at line 546 of file access.c.
References access_is_oauth_endpoint(), brix_http_operation_find(), brix_webdav_operations, brix_webdav_operations_count, op, webdav_check_token_scope(), and webdav_metrics_return().
Referenced by ngx_http_brix_webdav_access_handler().
access_count_request()
static void access_count_request (ngx_http_request_t * r) static
Definition at line 162 of file access.c.
References BRIX_WEBDAV_METRIC_INC, and webdav_metrics_request().
Referenced by ngx_http_brix_webdav_access_handler().
access_is_mirror_subrequest()
static int access_is_mirror_subrequest (ngx_http_request_t * r) static
Definition at line 141 of file access.c.
References ngx_http_brix_webdav_req_ctx_t::is_mirror, and ngx_http_brix_webdav_module.
Referenced by ngx_http_brix_webdav_access_handler().
access_is_oauth_endpoint()
static int access_is_oauth_endpoint (ngx_http_request_t * r) static
Definition at line 516 of file access.c.
Referenced by access_check_scope().
access_options_preflight()
static ngx_int_t access_options_preflight (ngx_http_request_t * r) static
Definition at line 220 of file access.c.
References BRIX_WEBDAV_CORS_PREFLIGHT, BRIX_WEBDAV_METRIC_INC, and webdav_tpc_find_header.
Referenced by ngx_http_brix_webdav_access_handler().
access_rate_limit()
static ngx_int_t access_rate_limit (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 186 of file access.c.
References brix_rate_limit_check(), brix_rate_limit_conf_t::kv, ngx_http_brix_webdav_loc_conf_t::rate_limit, and webdav_metrics_return().
Referenced by ngx_http_brix_webdav_access_handler().
access_try_basic()
static ngx_int_t access_try_basic (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 294 of file access.c.
References BRIX_AUTHN_PWD, brix_metric_auth(), BRIX_PROTO_WEBDAV, BRIX_WEBDAV_AUTH_RESULT_PWD_OK, BRIX_WEBDAV_METRIC_INC, and webdav_verify_basic_pwd().
Referenced by access_authenticate().
access_try_cert()
static ngx_int_t access_try_cert (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 244 of file access.c.
References BRIX_AUTHN_GSI, brix_metric_auth(), BRIX_PROTO_WEBDAV, BRIX_WEBDAV_AUTH_RESULT_CERT_OK, BRIX_WEBDAV_METRIC_INC, and webdav_verify_proxy_cert().
Referenced by access_authenticate().
access_try_token()
static ngx_int_t access_try_token (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 269 of file access.c.
References BRIX_AUTHN_TOKEN, brix_metric_auth(), BRIX_PROTO_WEBDAV, BRIX_WEBDAV_AUTH_RESULT_TOKEN_OK, BRIX_WEBDAV_METRIC_INC, and webdav_verify_bearer_token().
Referenced by access_authenticate().
ngx_http_brix_webdav_access_handler()
ngx_int_t ngx_http_brix_webdav_access_handler (ngx_http_request_t * r)
Definition at line 576 of file access.c.
References access_apply_authdb(), access_authenticate(), access_capture_deleg_proxy(), access_check_scope(), access_count_request(), access_is_mirror_subrequest(), access_options_preflight(), access_rate_limit(), ngx_http_brix_shared_conf_t::allow_write, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::enable, ngx_http_brix_webdav_module, webdav_acc_check(), webdav_add_cors_headers(), webdav_is_write_method(), webdav_metrics_return(), xrdhttp_inject_tpc_headers(), and xrdhttp_parse_request().
Referenced by webdav_postconf_install_handlers().
webdav_acc_check()
static ngx_int_t webdav_acc_check (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 63 of file access.c.
References ngx_http_brix_webdav_loc_conf_t::acc, brix_acc_http_authorize(), brix_acc_resolve_peer(), BRIX_AUTHDB_FORMAT_XRDACC, brix_identity_acc_group_cstr(), brix_identity_acc_role_cstr(), brix_identity_acc_vorg_cstr(), brix_identity_dn_cstr(), brix_acc_http_t::format, host, ngx_http_brix_webdav_req_ctx_t::identity, name, ngx_http_brix_webdav_module, ngx_memcpy, brix_acc_http_t::resolve_hosts, and webdav_method_aop().
Referenced by ngx_http_brix_webdav_access_handler().
webdav_is_write_method()
static int webdav_is_write_method (ngx_http_request_t * r) static
Definition at line 117 of file access.c.
References brix_http_operation_find(), BRIX_PROTO_OP_WRITE, brix_webdav_operations, brix_webdav_operations_count, and op.
Referenced by access_apply_authdb(), and ngx_http_brix_webdav_access_handler().
webdav_method_aop()
static brix_acc_op_t webdav_method_aop (ngx_http_request_t * r) static
Definition at line 31 of file access.c.
References BRIX_AOP_ANY, BRIX_AOP_CREATE, BRIX_AOP_DELETE, BRIX_AOP_MKDIR, BRIX_AOP_READ, BRIX_AOP_READDIR, BRIX_AOP_RENAME, BRIX_AOP_STAT, BRIX_AOP_UPDATE, and webdav_tpc_find_header.
Referenced by webdav_acc_check().
webdav_vfs_bind_deleg()
void webdav_vfs_bind_deleg (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, brix_vfs_ctx_t * vctx)
Definition at line 669 of file access.c.
References ngx_http_brix_shared_conf_t::backend_delegation, ngx_http_brix_webdav_req_ctx_t::bearer_token, BRIX_CRED_SELECT, brix_vfs_deleg_bind(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::deleg_proxy_pem, and ngx_http_brix_webdav_module.
Referenced by get_init_vfs_ctx(), webdav_copy_file_vfs_init(), webdav_copy_probe(), webdav_lock_vfs_ctx_init(), webdav_move_execute_cred(), webdav_move_probe(), webdav_ns_vfs_ctx_init(), webdav_put_precheck(), webdav_put_vfs_ctx_init(), and webdav_resolve_stat().