nginx-xrootd: src/protocols/root/read/open.h File Reference
open.h File Reference
#include "core/ngx_brix_module.h"
Functions
ngx_int_t brix_handle_open (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_open_resolved_file (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *resolved, uint16_t options, uint16_t mode_bits, ngx_flag_t is_write, uint8_t codec)
ngx_int_t brix_open_cached_read (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *clean_path, uint16_t options, uint16_t mode_bits)
Function Documentation
brix_handle_open()
ngx_int_t brix_handle_open (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 269 of file open_request.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_frm_conf_t::async_recall, BRIX_AOP_CREATE, BRIX_AOP_UPDATE, brix_auth_gate(), brix_auth_gate_op(), BRIX_AUTH_READ, BRIX_AUTH_UPDATE, brix_authz_check(), brix_beneath_full_path(), brix_cache_open_fill_offload(), brix_check_vo_acl_identity(), brix_count_path_depth(), brix_extract_path(), brix_find_manager_map(), brix_identity_dn_cstr(), brix_identity_vo_csv_cstr(), brix_is_internal_name(), brix_log_access(), brix_manager_tried_exhausted(), BRIX_MAX_PATH, brix_mkdir_recursive_policy(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_OPEN_RD, BRIX_OP_OPEN_WR, brix_open_cached_read(), brix_open_options_is_write(), brix_open_read_probe(), brix_open_resolved_file(), brix_pending_insert(), brix_pending_remove(), brix_pmark_echo_timer(), brix_pmark_flow_begin(), BRIX_PROTO_ROOT, brix_redir_cache_insert(), brix_redir_cache_lookup(), brix_reject_dotdot_path(), BRIX_RETURN_ERR, BRIX_RETURN_REDIR, brix_sd_cache_fill_needs_offload(), BRIX_SD_RES_LOST, BRIX_SD_RES_NEARLINE, BRIX_SD_RES_OFFLINE, brix_send_error(), brix_send_redirect_tpc(), brix_send_wait(), brix_send_waitresp(), brix_srv_select(), brix_srv_select_or_blacklisted(), brix_ssi_match(), brix_ssi_open(), brix_stage_registry_singleton(), BRIX_STAGE_REQID_LEN, brix_stage_request_add(), brix_stage_waiter_add(), brix_tpc_check_authz(), brix_tpc_generate_key(), brix_tpc_key_consume(), BRIX_TPC_KEY_LEN, brix_tpc_key_register(), brix_tpc_parse_opaque(), brix_tpc_prepare_pull(), brix_upstream_start(), brix_vfs_backend_resolve(), brix_vfs_ctx_init(), brix_vfs_export_relative_root(), brix_vfs_residency(), brix_zip_open_member(), c, ngx_stream_brix_srv_conf_t::cache, ngx_stream_brix_srv_conf_t::caps, ngx_stream_brix_srv_conf_t::cms, brix_ctx_t::cms_wait_streamid, brix_node_caps_conf_t::collapse_redir, brix_node_caps_conf_t::collapse_redir_ttl, ngx_stream_brix_srv_conf_t::common, brix_cms_conf_t::ctx, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_streamid, brix_ctx_login_t::dn, brix_tpc_params_t::dst, brix_pmark_conf_t::echo, brix_ctx_pmark_t::echo_ev, brix_ctx_pmark_t::echo_ms, brix_frm_conf_t::enable, brix_pmark_conf_t::enable, brix_ctx_pmark_t::flow, ngx_stream_brix_srv_conf_t::frm, ngx_stream_brix_srv_conf_t::group_rules, brix_tpc_params_t::has_dst, brix_tpc_params_t::has_key, brix_tpc_params_t::has_org, brix_tpc_params_t::has_src, brix_ctx_recv_t::hdr_buf, brix_manager_map_t::host, brix_ctx_t::identity, brix_tpc_params_t::key, kXR_ArgInvalid, kXR_ArgMissing, kXR_async, kXR_FSError, kXR_fsReadOnly, kXR_isDirectory, kXR_mkpath, kXR_new, kXR_NotAuthorized, kXR_NotFound, kXR_Overloaded, kXR_Unsupported, kXR_wait, brix_stage_request_view_t::lfn, brix_cms_conf_t::locate_timeout, brix_ctx_t::login, ngx_stream_brix_srv_conf_t::manager_map, ngx_stream_brix_srv_conf_t::manager_mode, brix_node_caps_conf_t::metadata_only, xrdw_open_req_t::mode, ngx_brix_cms_next_streamid(), ngx_brix_cms_send_locate(), open_extract_opaque(), open_extract_zip_member(), open_negotiate_compress_codec(), xrdw_open_req_t::options, brix_tpc_params_t::org, PATH_MAX, brix_ctx_recv_t::payload, ngx_http_brix_shared_conf_t::pmark, brix_ctx_t::pmark, brix_vfs_ctx_t::pool, brix_manager_map_t::port, brix_ctx_t::recv, brix_stage_request_view_t::requester_dn, ngx_http_brix_shared_conf_t::root_canon, brix_tpc_params_t::src_host, brix_tpc_params_t::src_path, ngx_stream_brix_srv_conf_t::ssi_enable, brix_frm_conf_t::stage_ttl, brix_frm_conf_t::stage_wait, brix_ctx_t::state, brix_stage_request_view_t::tod_expire, ngx_stream_brix_srv_conf_t::tpc_key_ttl_ms, ngx_stream_brix_srv_conf_t::upstream_host, ngx_stream_brix_srv_conf_t::vo_rules, brix_ctx_t::write_rc, XRD_ST_REQ_HEADER, XRD_ST_WAITING_CMS, XRD_ST_WAITING_FRM, xrdw_open_req_unpack(), and ngx_stream_brix_srv_conf_t::zip_access.
Referenced by brix_dispatch_read_opcode().
brix_open_cached_read()
ngx_int_t brix_open_cached_read (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * clean_path, uint16_t options, uint16_t mode_bits)
Definition at line 11 of file open_cache.c.
References brix_auth_gate(), BRIX_AUTH_READ, brix_beneath_full_path(), brix_beneath_rel(), brix_cache_open_or_fill(), BRIX_OP_OPEN_RD, brix_open_resolved_file(), BRIX_RETURN_ERR, c, ngx_stream_brix_srv_conf_t::cache_root, ngx_stream_brix_srv_conf_t::common, kXR_ArgInvalid, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, stat(), and brix_ctx_t::write_rc.
Referenced by brix_handle_open().
brix_open_resolved_file()
ngx_int_t brix_open_resolved_file (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * resolved, uint16_t options, uint16_t mode_bits, ngx_flag_t is_write, uint8_t codec)
Definition at line 646 of file open_resolved_file.c.
References brix_alloc_fhandle(), brix_apply_parent_group_policy_fd(), brix_build_resp_hdr(), brix_cache_wt_stage_sd_inst(), BRIX_CODEC_IDENTITY, brix_free_fhandle(), BRIX_INLINE_CMP_MAGIC, brix_log_access(), BRIX_OP_OK, BRIX_OP_OPEN_RD, BRIX_OP_OPEN_WR, brix_open_apply_throttle(), brix_open_attach_csi(), brix_open_build_retstat(), brix_open_build_stage_temp(), brix_open_check_exclusive_create(), brix_open_check_write_target(), brix_open_decide_writethrough(), brix_open_logical(), brix_open_options_to_posix(), brix_open_probe(), brix_open_register_monitor(), brix_open_resolved_via_driver(), brix_open_set_handle_path(), brix_open_stage_backpressure(), brix_open_validate_fd(), brix_queue_response(), BRIX_RECALL_WAIT_SECS, BRIX_RETURN_ERR, brix_sanitize_log_string(), brix_send_attn_asynresp(), brix_send_wait(), brix_session_handle_publish(), brix_stream_wmirror_on_open(), brix_vfs_backend_resolve(), brix_vfs_export_relative_root(), brix_vfs_open_fd_at(), brix_wrts_open(), BRIX_WT_DECISION_DENY, brix_file_t::bytes_read, brix_file_t::bytes_written, c, ngx_stream_brix_srv_conf_t::cache, ngx_stream_brix_srv_conf_t::cache_root, brix_file_t::cached_size, ngx_stream_brix_srv_conf_t::caps, ngx_stream_brix_srv_conf_t::common, ServerOpenBody::cpsize, ServerOpenBody::cptype, brix_ctx_recv_t::cur_streamid, brix_file_t::dashboard_slot, brix_file_t::device, brix_wt_conf_t::enable, brix_file_t::fd, ServerOpenBody::fhandle, brix_ctx_t::files, brix_file_t::from_cache, ngx_stream_brix_srv_conf_t::group_rules, brix_file_t::inode, brix_ctx_t::is_bound, brix_vfs_stat_t::is_directory, brix_file_t::is_regular, brix_vfs_stat_t::is_regular, kXR_delete, kXR_IOError, kXR_isDirectory, kXR_ItExists, kXR_new, kXR_NotAuthorized, kXR_NotFound, kXR_ok, kXR_posc, kXR_retstat, kXR_ServerError, brix_ctx_t::login, ngx_stream_brix_module, open(), brix_file_t::open_time, PATH_MAX, brix_ctx_t::prepare, brix_file_t::read_ahead_end, brix_file_t::read_codec, brix_file_t::read_last_end, brix_file_t::readable, brix_node_caps_conf_t::recover_writes, brix_ctx_t::recv, ngx_http_brix_shared_conf_t::root_canon, ngx_stream_brix_srv_conf_t::rootfd, brix_ctx_login_t::sessid, brix_ctx_prepare_t::stage_async_active, brix_ctx_prepare_t::stage_async_streamid, stat(), ngx_stream_brix_srv_conf_t::upload_resume, ngx_stream_brix_srv_conf_t::upload_stage_dir_canon, brix_file_t::writable, brix_file_t::write_codec, brix_file_t::wrts_count, brix_file_t::wrts_enabled, brix_file_t::wrts_gen, brix_file_t::wrts_head, ngx_stream_brix_srv_conf_t::wt, brix_file_t::wt_bytes_written, brix_file_t::wt_dirty_offset, brix_file_t::wt_enabled, brix_file_t::wt_flush_pending, brix_file_t::wt_flush_task, brix_file_t::wt_mode_bits, brix_file_t::wt_policy, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_cache_fill_composed_done(), brix_cache_fill_done(), brix_cache_open_or_fill(), brix_handle_open(), brix_open_cached_read(), and stage_waiter_deliver_one().