nginx-xrootd: src/protocols/webdav/metrics.c File Reference
metrics.c File Reference
#include "webdav.h"
#include "core/http/http_headers.h"
#include "core/http/sesslog_conn.h"
#include "observability/metrics/http_common.h"
#include "observability/metrics/unified.h"
Functions
static brix_metric_op_t webdav_unified_op (ngx_uint_t method)
static brix_sess_mode_t webdav_sess_mode (ngx_http_request_t *r, ngx_uint_t method)
static brix_sess_am_t webdav_sess_auth_method (ngx_http_brix_webdav_req_ctx_t *ctx)
static const char * webdav_sess_user (ngx_http_brix_webdav_req_ctx_t *ctx)
static const char * webdav_sess_vo (ngx_http_brix_webdav_req_ctx_t *ctx)
static brix_sess_t * webdav_sess (ngx_http_request_t *r)
static int webdav_sess_mode_has_xfer (brix_sess_mode_t mode)
static int64_t webdav_sess_xfer_expected (ngx_http_request_t *r, brix_sess_mode_t mode)
static uint64_t webdav_sess_xfer_bytes (ngx_http_request_t *r, brix_sess_mode_t mode, int64_t expected)
static void webdav_sess_start_xfer (ngx_http_request_t *r, brix_sess_t *sess, const char *path, brix_sess_mode_t mode)
static void webdav_sess_finish_xfer (ngx_http_request_t *r, brix_sess_t *sess, brix_sess_mode_t mode, ngx_uint_t status)
void webdav_sess_begin_request (ngx_http_request_t *r)
void webdav_sess_attempt_request (ngx_http_request_t *r)
ngx_uint_t webdav_metrics_method (ngx_http_request_t *r)
WHAT: Map nginx HTTP method to the WebDAV metric enum for Prometheus request counting.
void webdav_metrics_request (ngx_http_request_t *r)
WHAT: Increment the WebDAV requests_total counter for this request's method.
void webdav_metrics_response (ngx_http_request_t *r, ngx_int_t rc)
WHAT: Increment the WebDAV responses_total counter by method and status class.
ngx_int_t webdav_metrics_return (ngx_http_request_t *r, ngx_int_t rc)
WHAT: Wrapper helper — records response metrics then returns the original rc value.
void webdav_metrics_finalize_request (ngx_http_request_t *r, ngx_int_t rc)
WHAT: Wrapper helper — records response metrics then finalizes the nginx request.
void webdav_send_status_only (ngx_http_request_t *r, ngx_uint_t status)
WHAT: Emit a status-only (empty-body) response and finalize the request.
Function Documentation
webdav_metrics_finalize_request()
void webdav_metrics_finalize_request (ngx_http_request_t * r, ngx_int_t rc)
WHAT: Wrapper helper — records response metrics then finalizes the nginx request.
Convenience function that calls webdav_metrics_response(r, rc) followed by ngx_http_finalize_request(r, rc). Used by handlers that want to record metrics and complete the request lifecycle in a single call. Equivalent to: webdav_metrics_response(r, rc); ngx_http_finalize_request(r, rc);
Definition at line 355 of file metrics.c.
References webdav_metrics_response().
Referenced by delegation_reject(), mac_respond(), tape_post_body_handler(), tpc_thread_done(), webdav_copy_collection_done(), webdav_delete_async_render(), webdav_handle_lock_inner(), webdav_move_async_render(), webdav_move_collection_done(), webdav_proppatch_body_handler(), webdav_put_aio_done(), webdav_put_commit(), webdav_put_open_target(), webdav_put_precheck(), webdav_put_ranged_resume(), webdav_put_select_codec(), webdav_put_stream_body(), webdav_put_try_threaded(), webdav_put_write_sync(), webdav_search_body_handler(), and webdav_send_status_only().
webdav_metrics_method()
ngx_uint_t webdav_metrics_method (ngx_http_request_t * r)
WHAT: Map nginx HTTP method to the WebDAV metric enum for Prometheus request counting.
Returns a value from BRIX_WEBDAV_METHOD_* enum corresponding to the incoming request's HTTP method. Uses r->method (nginx internal enum) for OPTIONS/HEAD/GET/ PUT/DELETE; uses r->method_name string comparison for WebDAV-specific methods MKCOL, COPY, and PROPFIND (which nginx doesn't have built-in enums for). Returns BRIX_WEBDAV_METHOD_OTHER as fallback for unknown or custom methods. All callers use this to index into the requests_total[METHOD] metric counter before processing begins or after completing an operation.
Definition at line 261 of file metrics.c.
References brix_http_operation_find(), BRIX_WEBDAV_METHOD_OTHER, brix_webdav_operations, brix_webdav_operations_count, and op.
Referenced by webdav_metrics_request(), webdav_metrics_response(), and webdav_sess_attempt_request().
webdav_metrics_request()
void webdav_metrics_request (ngx_http_request_t * r)
WHAT: Increment the WebDAV requests_total counter for this request's method.
Called early in each handler to record that a request arrived for a specific HTTP method. Uses webdav_metrics_method() to classify the method, then increments the requests_total[method] Prometheus metric via BRIX_WEBDAV_METRIC_INC(). This is typically called at the start of every WebDAV operation handler (GET, PUT, DELETE, etc.) before any processing begins. Does not track status — only counts request arrivals.
Definition at line 281 of file metrics.c.
References BRIX_WEBDAV_METRIC_INC, and webdav_metrics_method().
Referenced by access_count_request().
webdav_metrics_response()
void webdav_metrics_response (ngx_http_request_t * r, ngx_int_t rc)
WHAT: Increment the WebDAV responses_total counter by method and status class.
Called at end of each handler to record the outcome of processing. Determines the HTTP status from either rc (error code), r->headers_out.status (explicitly set response), or defaults to NGX_HTTP_OK if no status was set. Maps to a low-cardinality status class via webdav_metrics_status_class(), then increments responses_total[method][status_class]. Returns immediately if rc == NGX_DONE (request already finalized, metrics should not be double-counted). Used by all handlers after completing their operation logic.
Definition at line 299 of file metrics.c.
References brix_http_effective_status(), brix_http_sess_uri(), brix_http_status_class(), brix_metric_err_from_http_status(), brix_metric_op_done(), BRIX_PROTO_WEBDAV, brix_sess_result(), brix_sesslog_err_from_http(), BRIX_SESSLOG_ERR_MAX, BRIX_SESSLOG_PATH_MAX, BRIX_WEBDAV_METRIC_INC, webdav_metrics_method(), webdav_sess(), webdav_sess_finish_xfer(), webdav_sess_mode(), and webdav_unified_op().
Referenced by webdav_metrics_finalize_request(), and webdav_metrics_return().
webdav_metrics_return()
ngx_int_t webdav_metrics_return (ngx_http_request_t * r, ngx_int_t rc)
WHAT: Wrapper helper — records response metrics then returns the original rc value.
Convenience function that calls webdav_metrics_response(r, rc) and immediately returns rc to the caller. Used by handlers that want to record metrics before returning an nginx result code without needing two separate statement lines. Equivalent to: webdav_metrics_response(r, rc); return rc;
Definition at line 340 of file metrics.c.
References webdav_metrics_response().
Referenced by access_apply_authdb(), access_authenticate(), access_capture_deleg_proxy(), access_check_scope(), access_rate_limit(), ngx_http_brix_webdav_access_handler(), webdav_dispatch_copy(), webdav_dispatch_copy_move_props(), webdav_dispatch_core_method(), webdav_dispatch_delegation_gridsite(), webdav_dispatch_delegation_upload(), webdav_dispatch_draining(), webdav_dispatch_inner(), webdav_dispatch_lock(), webdav_dispatch_lock_patch_search(), webdav_dispatch_macaroon(), webdav_dispatch_move(), webdav_dispatch_not_allowed(), webdav_dispatch_put(), and webdav_dispatch_tape_rest().
webdav_send_status_only()
void webdav_send_status_only (ngx_http_request_t * r, ngx_uint_t status)
WHAT: Emit a status-only (empty-body) response and finalize the request.
Captures the recurring four-line tail used by status-only outcomes (201/204/… with no body): set the status and a zero content length, send the header, then finalize via the send_special result so response metrics are recorded. Equivalent to: r->headers_out.status = status; r->headers_out.content_length_n = 0; ngx_http_send_header(r); webdav_metrics_finalize_request(r, ngx_http_send_special(r, NGX_HTTP_LAST));
The caller still owns flow control: this finalizes the request, so it must be the last action on r and the caller should return immediately after. Add any response headers (e.g. Location for 201) before calling.
Definition at line 378 of file metrics.c.
References webdav_metrics_finalize_request().
Referenced by tpc_thread_done(), webdav_copy_collection_done(), webdav_move_collection_done(), webdav_put_aio_done(), and webdav_put_ranged_resume().
webdav_sess()
static brix_sess_t * webdav_sess (ngx_http_request_t * r) static
Definition at line 113 of file metrics.c.
References brix_http_sess(), BRIX_SESS_PROTO_WEBDAV, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_module, and webdav_sess_auth_method().
Referenced by webdav_metrics_response(), webdav_sess_attempt_request(), and webdav_sess_begin_request().
webdav_sess_attempt_request()
void webdav_sess_attempt_request (ngx_http_request_t * r)
Definition at line 235 of file metrics.c.
References brix_http_sess_uri(), brix_sess_attempt(), BRIX_SESSLOG_PATH_MAX, webdav_metrics_method(), webdav_sess(), webdav_sess_mode(), and webdav_sess_start_xfer().
Referenced by webdav_dispatch_inner().
webdav_sess_auth_method()
static brix_sess_am_t webdav_sess_auth_method (ngx_http_brix_webdav_req_ctx_t * ctx) static
Definition at line 64 of file metrics.c.
References BRIX_SESS_AM_ANON, BRIX_SESS_AM_GSI, BRIX_SESS_AM_TOKEN, ngx_http_brix_webdav_req_ctx_t::token_auth, and ngx_http_brix_webdav_req_ctx_t::verified.
Referenced by webdav_sess(), and webdav_sess_begin_request().
webdav_sess_begin_request()
void webdav_sess_begin_request (ngx_http_request_t * r)
Definition at line 221 of file metrics.c.
References brix_sess_auth_once(), ngx_http_brix_webdav_module, webdav_sess(), webdav_sess_auth_method(), webdav_sess_user(), and webdav_sess_vo().
Referenced by webdav_dispatch_inner().
webdav_sess_finish_xfer()
static void webdav_sess_finish_xfer (ngx_http_request_t * r, brix_sess_t * sess, brix_sess_mode_t mode, ngx_uint_t status) static
Definition at line 189 of file metrics.c.
References BRIX_SESS_MODE_COPY, BRIX_SESS_XFER_ABORTED, brix_sess_xfer_add(), BRIX_SESS_XFER_COMPLETE, brix_sess_xfer_end(), brix_sess_xfer_t::bytes, brix_sess_xfer_t::expected, ngx_http_brix_webdav_module, ngx_http_brix_webdav_req_ctx_t::sess_xfer, ngx_http_brix_webdav_req_ctx_t::sess_xfer_started, webdav_sess_xfer_bytes(), and webdav_sess_xfer_expected().
Referenced by webdav_metrics_response().
webdav_sess_mode()
static brix_sess_mode_t webdav_sess_mode (ngx_http_request_t * r, ngx_uint_t method) static
Definition at line 35 of file metrics.c.
References brix_http_get_header(), BRIX_SESS_MODE_COPY, BRIX_SESS_MODE_DELETE, BRIX_SESS_MODE_LIST, BRIX_SESS_MODE_META, BRIX_SESS_MODE_READ, BRIX_SESS_MODE_WRITE, BRIX_WEBDAV_METHOD_COPY, BRIX_WEBDAV_METHOD_DELETE, BRIX_WEBDAV_METHOD_GET, BRIX_WEBDAV_METHOD_MKCOL, BRIX_WEBDAV_METHOD_PROPFIND, and BRIX_WEBDAV_METHOD_PUT.
Referenced by webdav_metrics_response(), and webdav_sess_attempt_request().
webdav_sess_mode_has_xfer()
static int webdav_sess_mode_has_xfer (brix_sess_mode_t mode) static
Definition at line 126 of file metrics.c.
References BRIX_SESS_MODE_COPY, BRIX_SESS_MODE_READ, and BRIX_SESS_MODE_WRITE.
Referenced by webdav_sess_start_xfer().
webdav_sess_start_xfer()
static void webdav_sess_start_xfer (ngx_http_request_t * r, brix_sess_t * sess, const char * path, brix_sess_mode_t mode) static
Definition at line 170 of file metrics.c.
References brix_sess_xfer_t::active, brix_sess_xfer_start(), ngx_http_brix_webdav_module, ngx_http_brix_webdav_req_ctx_t::sess_xfer, ngx_http_brix_webdav_req_ctx_t::sess_xfer_started, and webdav_sess_mode_has_xfer().
Referenced by webdav_sess_attempt_request().
webdav_sess_user()
static const char * webdav_sess_user (ngx_http_brix_webdav_req_ctx_t * ctx) static
Definition at line 82 of file metrics.c.
References brix_identity_dn_cstr(), brix_identity_subject_cstr(), and ngx_http_brix_webdav_req_ctx_t::identity.
Referenced by webdav_sess_begin_request().
webdav_sess_vo()
static const char * webdav_sess_vo (ngx_http_brix_webdav_req_ctx_t * ctx) static
Definition at line 100 of file metrics.c.
References brix_identity_vo_csv_cstr(), and ngx_http_brix_webdav_req_ctx_t::identity.
Referenced by webdav_sess_begin_request().
webdav_sess_xfer_bytes()
static uint64_t webdav_sess_xfer_bytes (ngx_http_request_t * r, brix_sess_mode_t mode, int64_t expected) static
Definition at line 153 of file metrics.c.
References BRIX_SESS_MODE_COPY, BRIX_SESS_MODE_READ, and BRIX_SESS_MODE_WRITE.
Referenced by webdav_sess_finish_xfer().
webdav_sess_xfer_expected()
static int64_t webdav_sess_xfer_expected (ngx_http_request_t * r, brix_sess_mode_t mode) static
Definition at line 133 of file metrics.c.
References BRIX_SESS_MODE_COPY, BRIX_SESS_MODE_READ, and BRIX_SESS_MODE_WRITE.
Referenced by webdav_sess_finish_xfer().
webdav_unified_op()
static brix_metric_op_t webdav_unified_op (ngx_uint_t method) static
Definition at line 12 of file metrics.c.
References BRIX_METRIC_OP_DELETE, BRIX_METRIC_OP_DIRLIST, BRIX_METRIC_OP_MKDIR, BRIX_METRIC_OP_READ, BRIX_METRIC_OP_STAT, BRIX_METRIC_OP_TPC, BRIX_METRIC_OP_WRITE, BRIX_WEBDAV_METHOD_COPY, BRIX_WEBDAV_METHOD_DELETE, BRIX_WEBDAV_METHOD_GET, BRIX_WEBDAV_METHOD_HEAD, BRIX_WEBDAV_METHOD_MKCOL, BRIX_WEBDAV_METHOD_PROPFIND, and BRIX_WEBDAV_METHOD_PUT.
Referenced by webdav_metrics_response().