nginx-xrootd: src/protocols/root/session/protocol.c File Reference
protocol.c File Reference
#include "core/ngx_brix_module.h"
#include "core/compat/alloc_guard.h"
Functions
ngx_int_t brix_handle_protocol (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_handle_protocol()
ngx_int_t brix_handle_protocol (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 19 of file protocol.c.
References brix_cms_conf_t::addr, ngx_stream_brix_srv_conf_t::auth, BRIX_AUTH_BOTH, BRIX_AUTH_GSI, BRIX_AUTH_HOST, BRIX_AUTH_KRB5, BRIX_AUTH_PWD, BRIX_AUTH_SSS, BRIX_AUTH_TOKEN, BRIX_AUTH_UNIX, brix_build_resp_hdr(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), brix_send_error(), c, ngx_stream_brix_srv_conf_t::cache_origin_host, ngx_stream_brix_srv_conf_t::cache_root, ngx_stream_brix_srv_conf_t::caps, ngx_stream_brix_srv_conf_t::cms, brix_node_caps_conf_t::collapse_redir, brix_ctx_recv_t::cur_body, brix_ctx_recv_t::cur_streamid, brix_proxy_conf_t::enable, ServerProtocolBody::flags, kXR_ableTLS, kXR_attrCache, kXR_attrMeta, kXR_attrProxy, kXR_attrSuper, kXR_attrVirtRdr, kXR_collapseRedir, kXR_gotoTLS, kXR_haveTLS, kXR_isManager, kXR_isServer, kXR_ok, kXR_PROTOCOLVERSION, kXR_recoverWrts, kXR_secOData, kXR_secreqs, kXR_suppgrw, kXR_supposc, kXR_tlsLogin, kXR_TLSRequired, kXR_wantTLS, ngx_stream_brix_srv_conf_t::manager_map, ngx_stream_brix_srv_conf_t::manager_mode, brix_node_caps_conf_t::metadata_only, ngx_memcpy, ngx_stream_brix_srv_conf_t::proxy, ServerProtocolBody::pval, brix_node_caps_conf_t::recover_writes, brix_ctx_t::recv, ngx_stream_brix_srv_conf_t::security_level, brix_node_caps_conf_t::supervisor, ngx_stream_brix_srv_conf_t::tls, ngx_stream_brix_srv_conf_t::tls_ctx, brix_ctx_t::tls_pending, brix_proxy_conf_t::upstreams, brix_node_caps_conf_t::virtual_redirector, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_dispatch_session_opcode().