nginx-xrootd: src/protocols/webdav/proxy_internal.h File Reference
proxy_internal.h File Reference
#include "webdav.h"
#include "proxy_pool.h"
Data Structures
struct brix_webdav_backend_t
struct webdav_proxy_ctx_t
Functions
brix_webdav_backend_t * webdav_proxy_pick_backend (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
ngx_int_t webdav_proxy_build_backends (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
ngx_int_t webdav_proxy_pool_setup (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_loc_conf_t *prev)
ngx_int_t webdav_proxy_create_request (ngx_http_request_t *r)
ngx_int_t webdav_proxy_reinit_request (ngx_http_request_t *r)
ngx_int_t webdav_proxy_process_status_line (ngx_http_request_t *r)
ngx_int_t webdav_proxy_process_header (ngx_http_request_t *r)
void webdav_proxy_abort_request (ngx_http_request_t *r)
void webdav_proxy_finalize_request (ngx_http_request_t *r, ngx_int_t rc)
Function Documentation
webdav_proxy_abort_request()
void webdav_proxy_abort_request (ngx_http_request_t * r)
Definition at line 159 of file proxy_response.c.
Referenced by webdav_proxy_handler().
webdav_proxy_build_backends()
ngx_int_t webdav_proxy_build_backends (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 151 of file proxy_config.c.
webdav_proxy_create_request()
ngx_int_t webdav_proxy_create_request (ngx_http_request_t * r)
Definition at line 70 of file proxy_request.c.
References brix_webdav_backend_t::host, key, ngx_http_brix_webdav_module, webdav_proxy_ctx_t::selected_backend, ngx_http_brix_webdav_loc_conf_t::upstream_auth, ngx_http_brix_webdav_loc_conf_t::upstream_auth_token, ngx_http_brix_webdav_loc_conf_t::upstream_host, ngx_http_brix_webdav_loc_conf_t::upstream_url_base, brix_webdav_backend_t::url_base, WEBDAV_PROXY_AUTH_ANONYMOUS, WEBDAV_PROXY_AUTH_FORWARD, WEBDAV_PROXY_AUTH_TOKEN, and webdav_proxy_rewrite_destination().
Referenced by webdav_proxy_handler().
webdav_proxy_finalize_request()
void webdav_proxy_finalize_request (ngx_http_request_t * r, ngx_int_t rc)
Definition at line 174 of file proxy_response.c.
References brix_proxy_pool_dec_in_flight(), brix_webdav_backend_t::fail_count, brix_webdav_backend_t::fail_time, ngx_http_brix_webdav_module, webdav_proxy_ctx_t::proxy_be_id, and webdav_proxy_ctx_t::selected_backend.
Referenced by webdav_proxy_handler().
webdav_proxy_pick_backend()
brix_webdav_backend_t * webdav_proxy_pick_backend (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 129 of file proxy.c.
References brix_webdav_backend_t::fail_count, brix_webdav_backend_t::fail_time, ngx_http_brix_webdav_loc_conf_t::upstream_backends, ngx_http_brix_webdav_loc_conf_t::upstream_fail_timeout, ngx_http_brix_webdav_loc_conf_t::upstream_max_fails, and ngx_http_brix_webdav_loc_conf_t::upstream_rr.
Referenced by webdav_proxy_handler().
webdav_proxy_pool_setup()
ngx_int_t webdav_proxy_pool_setup (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_loc_conf_t * prev)
Definition at line 246 of file proxy_config.c.
References brix_proxy_pool_configure(), s, and ngx_http_brix_webdav_loc_conf_t::upstream_conf.
Referenced by ngx_http_brix_webdav_merge_loc_conf().
webdav_proxy_process_header()
ngx_int_t webdav_proxy_process_header (ngx_http_request_t * r)
Definition at line 94 of file proxy_response.c.
Referenced by webdav_proxy_process_status_line(), and webdav_proxy_reinit_request().
webdav_proxy_process_status_line()
ngx_int_t webdav_proxy_process_status_line (ngx_http_request_t * r)
Definition at line 43 of file proxy_response.c.
References ngx_http_brix_webdav_module, webdav_proxy_ctx_t::status, and webdav_proxy_process_header().
Referenced by webdav_proxy_handler().
webdav_proxy_reinit_request()
ngx_int_t webdav_proxy_reinit_request (ngx_http_request_t * r)
Definition at line 21 of file proxy_response.c.
References ngx_http_brix_webdav_module, webdav_proxy_ctx_t::status, and webdav_proxy_process_header().
Referenced by webdav_proxy_handler().