nginx-xrootd: src/protocols/cvmfs/request.c File Reference
request.c File Reference
#include "cvmfs.h"
Functions
static ngx_int_t brix_cvmfs_proxy_scheme_check (ngx_http_request_t *r)
static ngx_int_t brix_cvmfs_proxy_parse_port (ngx_http_request_t *r, in_port_t *port)
static ngx_int_t brix_cvmfs_proxy_host_allowed (const brix_cvmfs_conf_t *cc, const ngx_str_t *host)
ngx_int_t brix_cvmfs_proxy_target (ngx_http_request_t *r, const brix_cvmfs_conf_t *cc, ngx_str_t *host, in_port_t *port)
Function Documentation
brix_cvmfs_proxy_host_allowed()
static ngx_int_t brix_cvmfs_proxy_host_allowed (const brix_cvmfs_conf_t * cc, const ngx_str_t * host) static
Definition at line 97 of file request.c.
References host, and brix_cvmfs_conf_t::upstream_allow.
Referenced by brix_cvmfs_proxy_target().
brix_cvmfs_proxy_parse_port()
static ngx_int_t brix_cvmfs_proxy_parse_port (ngx_http_request_t * r, in_port_t * port) static
Definition at line 65 of file request.c.
References port.
Referenced by brix_cvmfs_proxy_target().
brix_cvmfs_proxy_scheme_check()
static ngx_int_t brix_cvmfs_proxy_scheme_check (ngx_http_request_t * r) static
Definition at line 31 of file request.c.
References ngx_http_brix_cvmfs_module, and ngx_http_brix_cvmfs_ctx_t::secure.
Referenced by brix_cvmfs_proxy_target().
brix_cvmfs_proxy_target()
ngx_int_t brix_cvmfs_proxy_target (ngx_http_request_t * r, const brix_cvmfs_conf_t * cc, ngx_str_t * host, in_port_t * port)
Definition at line 135 of file request.c.
References brix_cvmfs_proxy_host_allowed(), brix_cvmfs_proxy_parse_port(), brix_cvmfs_proxy_scheme_check(), host, and port.
Referenced by cvmfs_gate_proxy_bind().