nginx-xrootd: src/protocols/webdav/lock.c File Reference
lock.c File Reference
#include "webdav.h"
#include "fs/path/path.h"
#include "fs/vfs/vfs.h"
#include "auth/impersonate/lifecycle.h"
#include "protocols/webdav/locks/request.h"
#include "core/http/http_xml.h"
#include "core/compat/fs_walk.h"
#include <openssl/crypto.h>
#include <openssl/rand.h>
#include <dirent.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/xattr.h>
#include <time.h>
Data Structures
struct webdav_lock_sweep_ctx_t
Macros
#define NGX_HTTP_LOCKED 423
Functions
static void webdav_generate_uuid (char *buf, size_t bufsz)
static void webdav_lock_sweep_remove (webdav_lock_sweep_ctx_t *sw, const char *path)
static ngx_int_t webdav_lock_sweep_cb (const brix_fs_walk_entry_t *entry, void *data)
ngx_uint_t webdav_lock_startup_sweep (ngx_pool_t *pool, ngx_log_t *log, const char *root_canon)
static void webdav_lock_xml_response (ngx_http_request_t *r, webdav_lock_xattr_t *e)
static void webdav_lock_vfs_ctx (ngx_http_request_t *r, const char *path, brix_vfs_ctx_t *vctx)
static void webdav_lock_reap_null (ngx_http_request_t *r, const char *path, const webdav_lock_xattr_t *e)
ngx_int_t webdav_check_locks (ngx_http_request_t *r, const char *path, int need_write)
static ngx_int_t check_locks_descendants (ngx_http_request_t *r, const char *dir)
ngx_int_t webdav_check_locks_tree (ngx_http_request_t *r, const char *path)
static void webdav_handle_lock_inner (ngx_http_request_t *r)
void webdav_handle_lock (ngx_http_request_t *r)
ngx_int_t webdav_handle_unlock (ngx_http_request_t *r)
ngx_int_t webdav_lock_append_supported (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail)
ngx_int_t webdav_lock_append_discovery (ngx_http_request_t *r, const char *path, ngx_chain_t **head, ngx_chain_t **tail)
Macro Definition Documentation
NGX_HTTP_LOCKED
#define NGX_HTTP_LOCKED 423
Definition at line 31 of file lock.c.
Function Documentation
check_locks_descendants()
static ngx_int_t check_locks_descendants (ngx_http_request_t * r, const char * dir) static
Definition at line 343 of file lock.c.
References brix_vfs_closedir(), BRIX_VFS_DT_DIR, BRIX_VFS_DT_UNKNOWN, brix_vfs_opendir_quiet(), brix_vfs_probe(), brix_vfs_readdir_kind(), check_locks_descendants(), webdav_lock_xattr_t::expires, brix_vfs_stat_t::is_directory, name, NGX_HTTP_LOCKED, PATH_MAX, webdav_lock_xattr_t::token, webdav_lock_if_header_matches(), webdav_lock_reap_null(), webdav_lock_vfs_ctx(), webdav_lock_xattr_delete(), and webdav_lock_xattr_read().
Referenced by check_locks_descendants(), and webdav_check_locks_tree().
webdav_check_locks()
ngx_int_t webdav_check_locks (ngx_http_request_t * r, const char * path, int need_write)
Definition at line 269 of file lock.c.
References check(), ngx_http_brix_webdav_loc_conf_t::common, webdav_lock_xattr_t::depth_infinity, webdav_lock_xattr_t::expires, ngx_http_brix_webdav_module, NGX_HTTP_LOCKED, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, webdav_lock_xattr_t::token, webdav_lock_if_header_matches(), webdav_lock_reap_null(), webdav_lock_xattr_delete(), and webdav_lock_xattr_read().
Referenced by webdav_check_locks_tree(), webdav_dispatch_inner(), webdav_handle_mkcol(), and webdav_proppatch_do().
webdav_check_locks_tree()
ngx_int_t webdav_check_locks_tree (ngx_http_request_t * r, const char * path)
Definition at line 431 of file lock.c.
References brix_vfs_probe(), check_locks_descendants(), brix_vfs_stat_t::is_directory, webdav_check_locks(), and webdav_lock_vfs_ctx().
Referenced by webdav_handle_copy(), webdav_handle_delete(), and webdav_handle_move().
webdav_generate_uuid()
static void webdav_generate_uuid (char * buf, size_t bufsz) static
Definition at line 39 of file lock.c.
Referenced by webdav_handle_lock_inner().
webdav_handle_lock()
void webdav_handle_lock (ngx_http_request_t * r)
Definition at line 464 of file lock.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, and webdav_handle_lock_inner().
Referenced by webdav_dispatch_inner().
webdav_handle_lock_inner()
static void webdav_handle_lock_inner (ngx_http_request_t * r) static
Definition at line 475 of file lock.c.
References brix_vfs_close(), BRIX_VFS_O_CREATE, BRIX_VFS_O_EXCL, BRIX_VFS_O_WRITE, brix_vfs_open(), brix_vfs_probe(), ngx_http_brix_webdav_loc_conf_t::common, webdav_lock_xattr_t::depth_infinity, ngx_http_brix_webdav_req_ctx_t::dn, webdav_lock_xattr_t::exclusive, webdav_lock_xattr_t::expires, webdav_lock_xattr_t::is_null, ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), NGX_HTTP_LOCKED, webdav_lock_xattr_t::owner, ngx_http_brix_shared_conf_t::root_canon, webdav_lock_xattr_t::token, webdav_generate_uuid(), webdav_lock_if_header_matches(), webdav_lock_parse_body(), webdav_lock_parse_depth(), webdav_lock_parse_timeout(), webdav_lock_vfs_ctx(), webdav_lock_xattr_delete(), webdav_lock_xattr_read(), webdav_lock_xattr_write(), webdav_lock_xml_response(), WEBDAV_MAX_PATH, and webdav_metrics_finalize_request().
Referenced by webdav_handle_lock().
webdav_handle_unlock()
ngx_int_t webdav_handle_unlock (ngx_http_request_t * r)
Definition at line 595 of file lock.c.
References ngx_http_brix_webdav_loc_conf_t::common, webdav_lock_xattr_t::expires, ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), ngx_http_brix_shared_conf_t::root_canon, webdav_lock_xattr_t::token, webdav_lock_reap_null(), webdav_lock_xattr_delete(), webdav_lock_xattr_read(), WEBDAV_MAX_PATH, webdav_send_no_body(), and webdav_tpc_find_header.
Referenced by webdav_dispatch_inner().
webdav_lock_append_discovery()
ngx_int_t webdav_lock_append_discovery (ngx_http_request_t * r, const char * path, ngx_chain_t ** head, ngx_chain_t ** tail)
Definition at line 700 of file lock.c.
References brix_http_chain_appendf(), webdav_lock_xattr_t::depth_infinity, webdav_lock_xattr_t::exclusive, webdav_lock_xattr_t::expires, webdav_lock_xattr_t::owner, webdav_lock_xattr_t::token, webdav_escape_xml_text(), webdav_lock_reap_null(), webdav_lock_xattr_delete(), and webdav_lock_xattr_read().
Referenced by propfind_entry().
webdav_lock_append_supported()
ngx_int_t webdav_lock_append_supported (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail)
Definition at line 674 of file lock.c.
References brix_http_chain_appendf().
Referenced by propfind_entry().
webdav_lock_reap_null()
static void webdav_lock_reap_null (ngx_http_request_t * r, const char * path, const webdav_lock_xattr_t * e) static
Definition at line 241 of file lock.c.
References brix_vfs_probe(), brix_vfs_unlink(), webdav_lock_xattr_t::is_null, brix_vfs_stat_t::is_regular, brix_vfs_stat_t::size, and webdav_lock_vfs_ctx().
Referenced by check_locks_descendants(), webdav_check_locks(), webdav_handle_unlock(), and webdav_lock_append_discovery().
webdav_lock_startup_sweep()
ngx_uint_t webdav_lock_startup_sweep (ngx_pool_t * pool, ngx_log_t * log, const char * root_canon)
Definition at line 101 of file lock.c.
References brix_fs_walk(), brix_fs_walk_options_t::include_dirs, brix_fs_walk_options_t::include_files, log, webdav_lock_sweep_ctx_t::log, webdav_lock_sweep_ctx_t::pool, webdav_lock_sweep_ctx_t::removed, webdav_lock_sweep_ctx_t::root_canon, webdav_lock_sweep_cb(), and webdav_lock_sweep_remove().
Referenced by ngx_http_brix_webdav_merge_loc_conf().
webdav_lock_sweep_cb()
static ngx_int_t webdav_lock_sweep_cb (const brix_fs_walk_entry_t * entry, void * data) static
Definition at line 94 of file lock.c.
References brix_fs_walk_entry_t::path, and webdav_lock_sweep_remove().
Referenced by webdav_lock_startup_sweep().
webdav_lock_sweep_remove()
static void webdav_lock_sweep_remove (webdav_lock_sweep_ctx_t * sw, const char * path) static
Definition at line 81 of file lock.c.
References BRIX_PROTO_WEBDAV, brix_vfs_ctx_init(), brix_vfs_removexattr(), webdav_lock_sweep_ctx_t::log, webdav_lock_sweep_ctx_t::pool, webdav_lock_sweep_ctx_t::removed, webdav_lock_sweep_ctx_t::root_canon, and WEBDAV_LOCK_XATTR_KEY.
Referenced by webdav_lock_startup_sweep(), and webdav_lock_sweep_cb().
webdav_lock_vfs_ctx()
static void webdav_lock_vfs_ctx (ngx_http_request_t * r, const char * path, brix_vfs_ctx_t * vctx) static
Definition at line 222 of file lock.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_WEBDAV, brix_vfs_ctx_init(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, brix_vfs_ctx_t::pool, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by check_locks_descendants(), webdav_check_locks_tree(), webdav_handle_lock_inner(), and webdav_lock_reap_null().
webdav_lock_xml_response()
static void webdav_lock_xml_response (ngx_http_request_t * r, webdav_lock_xattr_t * e) static
Definition at line 132 of file lock.c.
References brix_http_chain_appendf(), webdav_lock_xattr_t::depth_infinity, webdav_lock_xattr_t::exclusive, webdav_lock_xattr_t::expires, webdav_lock_xattr_t::owner, webdav_lock_xattr_t::token, and webdav_escape_xml_text().
Referenced by webdav_handle_lock_inner().