nginx-xrootd: src/protocols/ssi/registry.h File Reference
registry.h File Reference
#include "session.h"
Macros
#define BRIX_SSI_REGISTRY_SLOTS 256
Functions
void brix_ssi_registry_add (uintptr_t conn_id, brix_ssi_session_t *s)
void brix_ssi_registry_remove (uintptr_t conn_id)
brix_ssi_session_t * brix_ssi_registry_find (uintptr_t conn_id, uint64_t generation)
Macro Definition Documentation
BRIX_SSI_REGISTRY_SLOTS
#define BRIX_SSI_REGISTRY_SLOTS 256
Definition at line 20 of file registry.h.
Function Documentation
brix_ssi_registry_add()
void brix_ssi_registry_add (uintptr_t conn_id, brix_ssi_session_t * s)
Definition at line 21 of file registry.c.
References BRIX_SSI_REGISTRY_SLOTS, conn_id, brix_ssi_session_t::conn_id, brix_ssi_session_t::generation, in_use, s, and ssi_reg.
Referenced by brix_ssi_open(), test_add_find_remove(), and test_recycled_conn_id_refreshes_generation().
brix_ssi_registry_find()
brix_ssi_session_t * brix_ssi_registry_find (uintptr_t conn_id, uint64_t generation)
Definition at line 62 of file registry.c.
References BRIX_SSI_REGISTRY_SLOTS, conn_id, generation, brix_ssi_session_t::generation, in_use, and ssi_reg.
Referenced by ssi_defer_timer_handler(), test_add_find_remove(), and test_recycled_conn_id_refreshes_generation().
brix_ssi_registry_remove()
void brix_ssi_registry_remove (uintptr_t conn_id)
Definition at line 48 of file registry.c.
References BRIX_SSI_REGISTRY_SLOTS, conn_id, in_use, and ssi_reg.
Referenced by brix_ssi_handle_cleanup(), test_add_find_remove(), and test_recycled_conn_id_refreshes_generation().