nginx-xrootd: src/protocols/root/dirlist/handler.c File Reference
handler.c File Reference
#include "core/ngx_brix_module.h"
#include "core/aio/aio.h"
#include "protocols/root/path/op_path.h"
#include "net/manager/registry.h"
#include "protocols/root/protocol/dirlist_fmt.h"
#include "fs/vfs/vfs.h"
#include "fs/path/reserved_names.h"
#include "dcksm.h"
#include <spawn.h>
#include <sys/wait.h>
#include "core/compat/alloc_guard.h"
Data Structures
struct brix_dirlist_walk_t
struct brix_dirlist_entry_fmt_t
Functions
static ngx_flag_t brix_dirlist_name_is_unsafe (const char *name)
static int brix_dirlist_parse_request (brix_ctx_t *ctx, ngx_connection_t *c, brix_dirlist_walk_t *walk, ngx_int_t *rc)
static int brix_dirlist_check_redirect (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, brix_dirlist_walk_t *walk, ngx_int_t *rc)
static int brix_dirlist_open_dir (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, brix_dirlist_walk_t *walk, ngx_int_t *rc)
static int brix_dirlist_alloc_chunk (brix_ctx_t *ctx, ngx_connection_t *c, brix_dirlist_walk_t *walk, ngx_int_t *rc)
static ngx_flag_t brix_dirlist_entry_skip (ngx_log_t *log, const char *name)
static void brix_dirlist_entry_meta (ngx_log_t *log, brix_dirlist_walk_t *walk, const char *name, const brix_vfs_stat_t *vst, brix_dirlist_entry_fmt_t *fmt)
static ngx_int_t brix_dirlist_flush_chunk (brix_ctx_t *ctx, ngx_connection_t *c, brix_dirlist_walk_t *walk)
static void brix_dirlist_append_entry (brix_dirlist_walk_t *walk, const char *name, size_t nlen, const brix_dirlist_entry_fmt_t *fmt)
static ngx_int_t brix_dirlist_send_final (brix_ctx_t *ctx, ngx_connection_t *c, brix_dirlist_walk_t *walk)
static ngx_int_t brix_dirlist_stream_entries (brix_ctx_t *ctx, ngx_connection_t *c, brix_dirlist_walk_t *walk)
ngx_int_t brix_handle_dirlist (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Variables
char ** environ
Function Documentation
brix_dirlist_alloc_chunk()
static int brix_dirlist_alloc_chunk (brix_ctx_t * ctx, ngx_connection_t * c, brix_dirlist_walk_t * walk, ngx_int_t * rc) static
Definition at line 267 of file handler.c.
References BRIX_DSTAT_LEADIN, BRIX_DSTAT_LEADIN_LEN, BRIX_MAX_CONN_POOL_BYTES, brix_send_error(), brix_vfs_closedir(), c, brix_dirlist_walk_t::chunk, brix_dirlist_walk_t::chunk_cap, brix_dirlist_walk_t::chunk_pos, brix_dirlist_walk_t::dh, kXR_NoMemory, brix_ctx_t::login, ngx_memcpy, brix_ctx_login_t::pool_bytes_used, brix_dirlist_walk_t::want_stat, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_handle_dirlist().
brix_dirlist_append_entry()
static void brix_dirlist_append_entry (brix_dirlist_walk_t * walk, const char * name, size_t nlen, const brix_dirlist_entry_fmt_t * fmt) static
Definition at line 440 of file handler.c.
References brix_dirlist_walk_t::chunk, brix_dirlist_walk_t::chunk_cap, brix_dirlist_walk_t::chunk_pos, brix_dirlist_entry_fmt_t::cksum_token, brix_dirlist_entry_fmt_t::have_stat, name, ngx_memcpy, brix_dirlist_entry_fmt_t::statbuf, brix_dirlist_walk_t::want_cksum, brix_dirlist_walk_t::want_stat, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_dirlist_stream_entries().
brix_dirlist_check_redirect()
static int brix_dirlist_check_redirect (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, brix_dirlist_walk_t * walk, ngx_int_t * rc) static
Definition at line 162 of file handler.c.
References brix_find_manager_map(), brix_log_access(), BRIX_OP_DIRLIST, BRIX_OP_ERR, BRIX_OP_OK, brix_send_error(), brix_send_redirect(), brix_srv_select(), c, brix_manager_map_t::host, kXR_ok, kXR_Overloaded, brix_manager_map_t::port, and brix_dirlist_walk_t::reqpath.
Referenced by brix_handle_dirlist().
brix_dirlist_entry_meta()
static void brix_dirlist_entry_meta (ngx_log_t * log, brix_dirlist_walk_t * walk, const char * name, const brix_vfs_stat_t * vst, brix_dirlist_entry_fmt_t * fmt) static
Definition at line 354 of file handler.c.
References brix_vfs_stat_t::blocks, brix_dirlist_checksum_token(), brix_dirlist_make_dcksm_stat_body(), brix_make_stat_body(), brix_vfs_dir_fd(), brix_dirlist_walk_t::cksum_algo, brix_dirlist_entry_fmt_t::cksum_token, brix_vfs_stat_t::ctime, brix_vfs_stat_t::dev, brix_dirlist_walk_t::dh, brix_dirlist_walk_t::full_path, brix_vfs_stat_t::gid, brix_dirlist_entry_fmt_t::have_stat, brix_vfs_stat_t::ino, log, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, name, brix_dirlist_entry_fmt_t::need, PATH_MAX, brix_vfs_stat_t::size, stat(), brix_dirlist_entry_fmt_t::statbuf, brix_vfs_stat_t::uid, brix_dirlist_walk_t::want_cksum, and brix_dirlist_walk_t::want_stat.
Referenced by brix_dirlist_stream_entries().
brix_dirlist_entry_skip()
static ngx_flag_t brix_dirlist_entry_skip (ngx_log_t * log, const char * name) static
Definition at line 311 of file handler.c.
References brix_dirlist_name_is_unsafe(), brix_is_internal_name(), brix_sanitize_log_string(), log, and name.
Referenced by brix_dirlist_stream_entries().
brix_dirlist_flush_chunk()
static ngx_int_t brix_dirlist_flush_chunk (brix_ctx_t * ctx, ngx_connection_t * c, brix_dirlist_walk_t * walk) static
Definition at line 413 of file handler.c.
References brix_build_resp_hdr(), brix_queue_response(), c, brix_dirlist_walk_t::chunk, brix_dirlist_walk_t::chunk_pos, brix_ctx_recv_t::cur_streamid, kXR_oksofar, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_dirlist_stream_entries().
brix_dirlist_name_is_unsafe()
static ngx_flag_t brix_dirlist_name_is_unsafe (const char * name) static
Definition at line 71 of file handler.c.
References name.
Referenced by brix_dirlist_entry_skip().
brix_dirlist_open_dir()
static int brix_dirlist_open_dir (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, brix_dirlist_walk_t * walk, ngx_int_t * rc) static
Definition at line 214 of file handler.c.
References brix_auth_gate(), BRIX_AUTH_LOOKUP, BRIX_BAIL_ERR, brix_beneath_full_path(), BRIX_OP_DIRLIST, BRIX_PROTO_ROOT, brix_root_vfs_bind_deleg(), brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), brix_vfs_opendir(), c, brix_dirlist_walk_t::dh, brix_dirlist_walk_t::full_path, brix_ctx_t::identity, kXR_IOError, kXR_NotFile, kXR_NotFound, brix_vfs_ctx_t::pool, brix_dirlist_walk_t::reqpath, and brix_ctx_t::write_rc.
Referenced by brix_handle_dirlist().
brix_dirlist_parse_request()
static int brix_dirlist_parse_request (brix_ctx_t * ctx, ngx_connection_t * c, brix_dirlist_walk_t * walk, ngx_int_t * rc) static
Definition at line 96 of file handler.c.
References BRIX_BAIL_ERR, brix_dirlist_checksum_algorithm(), brix_extract_path(), BRIX_OP_DIRLIST, brix_reject_dotdot_path(), c, brix_dirlist_walk_t::cksum_algo, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::hdr_buf, kXR_ArgInvalid, kXR_ArgMissing, kXR_dcksm, kXR_dstat, kXR_ServerError, brix_dirlist_walk_t::options, xrdw_dirlist_req_t::options, brix_ctx_recv_t::payload, brix_ctx_t::recv, brix_dirlist_walk_t::reqpath, brix_dirlist_walk_t::want_cksum, brix_dirlist_walk_t::want_stat, brix_ctx_t::write_rc, and xrdw_dirlist_req_unpack().
Referenced by brix_handle_dirlist().
brix_dirlist_send_final()
static ngx_int_t brix_dirlist_send_final (brix_ctx_t * ctx, ngx_connection_t * c, brix_dirlist_walk_t * walk) static
Definition at line 481 of file handler.c.
References brix_build_resp_hdr(), brix_log_access(), BRIX_OP_DIRLIST, BRIX_OP_OK, brix_queue_response(), c, brix_dirlist_walk_t::chunk, brix_dirlist_walk_t::chunk_pos, brix_ctx_recv_t::cur_streamid, kXR_ok, brix_ctx_t::recv, brix_dirlist_walk_t::reqpath, brix_dirlist_walk_t::want_cksum, brix_dirlist_walk_t::want_stat, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_dirlist_stream_entries().
brix_dirlist_stream_entries()
static ngx_int_t brix_dirlist_stream_entries (brix_ctx_t * ctx, ngx_connection_t * c, brix_dirlist_walk_t * walk) static
Definition at line 523 of file handler.c.
References brix_dirlist_append_entry(), brix_dirlist_entry_meta(), brix_dirlist_entry_skip(), brix_dirlist_flush_chunk(), brix_dirlist_send_final(), brix_vfs_closedir(), brix_vfs_readdir(), c, brix_dirlist_walk_t::chunk_cap, brix_dirlist_walk_t::chunk_pos, brix_dirlist_walk_t::dh, name, brix_dirlist_entry_fmt_t::need, and brix_dirlist_walk_t::want_stat.
Referenced by brix_handle_dirlist().
brix_handle_dirlist()
ngx_int_t brix_handle_dirlist (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 586 of file handler.c.
References brix_dirlist_alloc_chunk(), brix_dirlist_check_redirect(), brix_dirlist_open_dir(), brix_dirlist_parse_request(), brix_dirlist_stream_entries(), c, and brix_dirlist_walk_t::chunk_cap.
Referenced by brix_dispatch_read_opcode().
Variable Documentation
environ
char** environ extern