nginx-xrootd: src/protocols/root/session/registry.c File Reference
registry.c File Reference
#include "registry.h"
#include "core/compat/shm_slots.h"
#include <ngx_shmtx.h>
#include <string.h>
Functions
static brix_session_table_t * session_table (void)
ngx_int_t brix_session_shm_init_zone (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t brix_configure_session_registry (ngx_conf_t *cf, ngx_uint_t slots)
static int brix_session_scan (brix_session_table_t *tbl, const u_char sessid[16], ngx_msec_t now, ngx_uint_t *free_slot_out, ngx_uint_t *lru_slot_out, ngx_msec_t *lru_seen_out)
static int brix_session_reap_lru (brix_session_table_t *tbl, ngx_msec_t now, ngx_uint_t lru_slot, ngx_msec_t lru_seen, ngx_uint_t *free_slot_out, u_char victim[16])
static void brix_session_fill_slot (brix_session_table_t *tbl, ngx_uint_t slot, const u_char sessid[16], const char *dn, const char *vo_list, ngx_uint_t token_auth, ngx_msec_t now)
static void brix_session_finish_eviction (const u_char victim[16])
void brix_session_register (const u_char sessid[16], const char *dn, const char *vo_list, ngx_uint_t token_auth)
int brix_session_lookup (const u_char sessid[16], char *dn_out, size_t dn_size, char *vo_out, size_t vo_size, ngx_uint_t *token_auth_out)
void brix_session_unregister (const u_char sessid[16])
Variables
ngx_shm_zone_t * brix_session_shm_zone
ngx_shm_zone_t * brix_handle_shm_zone
static ngx_shmtx_t brix_session_mutex
static ngx_uint_t brix_session_registry_nslots
Function Documentation
brix_configure_session_registry()
ngx_int_t brix_configure_session_registry (ngx_conf_t * cf, ngx_uint_t slots)
Definition at line 74 of file registry.c.
References brix_handle_shm_init_zone(), brix_handle_shm_zone, brix_session_registry_nslots, BRIX_SESSION_REGISTRY_SLOTS, brix_session_shm_init_zone(), brix_session_shm_zone, brix_shm_zone_size(), brix_shm_zone_warn_on_resize(), and ngx_stream_brix_module.
Referenced by postconf_session_registry().
brix_session_fill_slot()
static void brix_session_fill_slot (brix_session_table_t * tbl, ngx_uint_t slot, const u_char sessid[16], const char * dn, const char * vo_list, ngx_uint_t token_auth, ngx_msec_t now) static
Definition at line 224 of file registry.c.
References BRIX_SESSION_ID_LEN, brix_session_entry_t::dn, brix_session_entry_t::in_use, brix_session_entry_t::last_seen, ngx_memcpy, brix_session_entry_t::sessid, brix_session_table_t::slots, brix_session_entry_t::token_auth, and brix_session_entry_t::vo_list.
Referenced by brix_session_register().
brix_session_finish_eviction()
static void brix_session_finish_eviction (const u_char victim[16]) static
Definition at line 254 of file registry.c.
References brix_metrics_shared(), brix_session_handle_unpublish_all(), and ngx_brix_metrics_t::session_evict_total.
Referenced by brix_session_register().
brix_session_lookup()
int brix_session_lookup (const u_char sessid[16], char * dn_out, size_t dn_size, char * vo_out, size_t vo_size, ngx_uint_t * token_auth_out)
Definition at line 314 of file registry.c.
References BRIX_SESSION_ID_LEN, brix_session_mutex, brix_session_table_t::capacity, brix_session_entry_t::dn, brix_session_entry_t::in_use, brix_session_entry_t::last_seen, brix_session_entry_t::sessid, session_table(), brix_session_table_t::slots, brix_session_entry_t::token_auth, and brix_session_entry_t::vo_list.
Referenced by brix_handle_bind().
brix_session_reap_lru()
static int brix_session_reap_lru (brix_session_table_t * tbl, ngx_msec_t now, ngx_uint_t lru_slot, ngx_msec_t lru_seen, ngx_uint_t * free_slot_out, u_char victim[16]) static
Definition at line 187 of file registry.c.
References brix_metrics_shared(), BRIX_SESSION_ID_LEN, BRIX_SESSION_REAP_MIN_AGE_MS, ngx_memcpy, brix_session_entry_t::sessid, ngx_brix_metrics_t::session_registry_full_total, and brix_session_table_t::slots.
Referenced by brix_session_register().
brix_session_register()
void brix_session_register (const u_char sessid[16], const char * dn, const char * vo_list, ngx_uint_t token_auth)
Definition at line 268 of file registry.c.
References brix_session_fill_slot(), brix_session_finish_eviction(), BRIX_SESSION_ID_LEN, brix_session_mutex, brix_session_reap_lru(), brix_session_scan(), brix_session_table_t::capacity, and session_table().
Referenced by brix_gsi_complete_auth(), brix_handle_host_auth(), brix_login_respond_anon(), brix_unix_finalize(), pwd_round2(), sss_reply(), and tokenauth_bind_session().
brix_session_scan()
static int brix_session_scan (brix_session_table_t * tbl, const u_char sessid[16], ngx_msec_t now, ngx_uint_t * free_slot_out, ngx_uint_t * lru_slot_out, ngx_msec_t * lru_seen_out) static
Definition at line 134 of file registry.c.
References BRIX_SESSION_ID_LEN, brix_session_table_t::capacity, brix_session_entry_t::in_use, brix_session_entry_t::last_seen, brix_session_entry_t::sessid, and brix_session_table_t::slots.
Referenced by brix_session_register().
brix_session_shm_init_zone()
ngx_int_t brix_session_shm_init_zone (ngx_shm_zone_t * shm_zone, void * data)
Definition at line 42 of file registry.c.
References brix_session_mutex, brix_session_registry_nslots, brix_shm_table_alloc(), and brix_session_table_t::capacity.
Referenced by brix_configure_session_registry().
brix_session_unregister()
void brix_session_unregister (const u_char sessid[16])
Definition at line 353 of file registry.c.
References brix_session_handle_unpublish_all(), BRIX_SESSION_ID_LEN, brix_session_mutex, brix_session_table_t::capacity, brix_session_entry_t::in_use, brix_session_entry_t::sessid, session_table(), and brix_session_table_t::slots.
Referenced by brix_handle_endsess(), and brix_on_disconnect().
session_table()
static brix_session_table_t * session_table (void) static
Definition at line 28 of file registry.c.
References brix_session_shm_zone.
Referenced by brix_session_lookup(), brix_session_register(), and brix_session_unregister().
Variable Documentation
brix_handle_shm_zone
ngx_shm_zone_t* brix_handle_shm_zone
Definition at line 17 of file registry.c.
Referenced by brix_configure_session_registry(), and handle_table().
brix_session_mutex
ngx_shmtx_t brix_session_mutex static
Definition at line 19 of file registry.c.
Referenced by brix_session_lookup(), brix_session_register(), brix_session_shm_init_zone(), and brix_session_unregister().
brix_session_registry_nslots
ngx_uint_t brix_session_registry_nslots static
Initial value:
=
     1024
Definition at line 23 of file registry.c.
Referenced by brix_configure_session_registry(), and brix_session_shm_init_zone().
brix_session_shm_zone
ngx_shm_zone_t* brix_session_shm_zone
Definition at line 16 of file registry.c.
Referenced by brix_configure_session_registry(), and session_table().