nginx-xrootd: src/protocols/webdav/locks/request.c File Reference
request.c File Reference
#include "request.h"
#include "core/compat/xml.h"
Functions
int64_t webdav_lock_parse_timeout (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
int webdav_lock_if_header_matches (ngx_http_request_t *r, const char *token)
ngx_int_t webdav_lock_parse_depth (ngx_http_request_t *r, int *depth_infinity)
void webdav_lock_parse_body (ngx_http_request_t *r, char *owner, size_t owner_len, int *exclusive)
Function Documentation
webdav_lock_if_header_matches()
int webdav_lock_if_header_matches (ngx_http_request_t * r, const char * token)
Definition at line 44 of file request.c.
References webdav_tpc_find_header.
Referenced by check_locks_descendants(), webdav_check_locks(), and webdav_handle_lock_inner().
webdav_lock_parse_body()
void webdav_lock_parse_body (ngx_http_request_t * r, char * owner, size_t owner_len, int * exclusive)
Definition at line 92 of file request.c.
References brix_xml_parse_lockinfo().
Referenced by webdav_handle_lock_inner().
webdav_lock_parse_depth()
ngx_int_t webdav_lock_parse_depth (ngx_http_request_t * r, int * depth_infinity)
Definition at line 66 of file request.c.
References webdav_tpc_find_header.
Referenced by webdav_handle_lock_inner().
webdav_lock_parse_timeout()
int64_t webdav_lock_parse_timeout (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 9 of file request.c.
References ngx_http_brix_webdav_loc_conf_t::lock_timeout, and webdav_tpc_find_header.
Referenced by webdav_handle_lock_inner().