nginx-xrootd: src/protocols/root/query/config.c File Reference
config.c File Reference
#include "query_internal.h"
#include "core/compat/codec_core.h"
#include "core/ident.h"
#include <stdarg.h>
#include <stdio.h>
Data Structures
struct brix_qconfig_entry_t
Typedefs
typedef ngx_flag_t(* brix_qconfig_emit_fn) (ngx_stream_brix_srv_conf_t *conf, char *resp, size_t resp_sz, size_t *pos)
Functions
static void brix_qconfig_skip_ws (const char **pp)
static ngx_flag_t brix_qconfig_next_token (const char **pp, char *tok, size_t tok_sz)
static ngx_flag_t brix_qconfig_append (char *resp, size_t resp_sz, size_t *pos, const char *fmt,...)
static void brix_qconfig_codec_list (char *list, size_t list_sz)
static ngx_flag_t brix_qconfig_emit_chksum (ngx_stream_brix_srv_conf_t *conf, char *resp, size_t resp_sz, size_t *pos)
static ngx_flag_t brix_qconfig_emit_readv (ngx_stream_brix_srv_conf_t *conf, char *resp, size_t resp_sz, size_t *pos)
static ngx_flag_t brix_qconfig_emit_readv_ior_max (ngx_stream_brix_srv_conf_t *conf, char *resp, size_t resp_sz, size_t *pos)
static ngx_flag_t brix_qconfig_emit_readv_iov_max (ngx_stream_brix_srv_conf_t *conf, char *resp, size_t resp_sz, size_t *pos)
static ngx_flag_t brix_qconfig_emit_tpc (ngx_stream_brix_srv_conf_t *conf, char *resp, size_t resp_sz, size_t *pos)
static ngx_flag_t brix_qconfig_emit_tpcdlg (ngx_stream_brix_srv_conf_t *conf, char *resp, size_t resp_sz, size_t *pos)
static ngx_flag_t brix_qconfig_emit_cmpread (ngx_stream_brix_srv_conf_t *conf, char *resp, size_t resp_sz, size_t *pos)
static ngx_flag_t brix_qconfig_emit_cmpwrite (ngx_stream_brix_srv_conf_t *conf, char *resp, size_t resp_sz, size_t *pos)
static ngx_flag_t brix_qconfig_emit_xrdfs_ext (ngx_stream_brix_srv_conf_t *conf, char *resp, size_t resp_sz, size_t *pos)
static ngx_flag_t brix_qconfig_emit_version (ngx_stream_brix_srv_conf_t *conf, char *resp, size_t resp_sz, size_t *pos)
static ngx_flag_t brix_qconfig_emit_bind_max (ngx_stream_brix_srv_conf_t *conf, char *resp, size_t resp_sz, size_t *pos)
static ngx_flag_t brix_qconfig_emit_pio_max (ngx_stream_brix_srv_conf_t *conf, char *resp, size_t resp_sz, size_t *pos)
static ngx_flag_t brix_qconfig_emit_role (ngx_stream_brix_srv_conf_t *conf, char *resp, size_t resp_sz, size_t *pos)
static ngx_flag_t brix_qconfig_emit_fattr (ngx_stream_brix_srv_conf_t *conf, char *resp, size_t resp_sz, size_t *pos)
static ngx_flag_t brix_qconfig_emit_key (const char *key, ngx_stream_brix_srv_conf_t *conf, char *resp, size_t resp_sz, size_t *pos)
ngx_int_t brix_query_config (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Variables
static const brix_qconfig_entry_t brix_qconfig_table []
Typedef Documentation
brix_qconfig_emit_fn
typedef ngx_flag_t(* brix_qconfig_emit_fn) (ngx_stream_brix_srv_conf_t *conf, char *resp, size_t resp_sz, size_t *pos)
Definition at line 105 of file config.c.
Function Documentation
brix_qconfig_append()
static ngx_flag_t brix_qconfig_append (char * resp, size_t resp_sz, size_t * pos, const char * fmt, ...) static
Definition at line 73 of file config.c.
Referenced by brix_qconfig_emit_bind_max(), brix_qconfig_emit_chksum(), brix_qconfig_emit_cmpread(), brix_qconfig_emit_cmpwrite(), brix_qconfig_emit_fattr(), brix_qconfig_emit_key(), brix_qconfig_emit_pio_max(), brix_qconfig_emit_readv(), brix_qconfig_emit_readv_ior_max(), brix_qconfig_emit_readv_iov_max(), brix_qconfig_emit_role(), brix_qconfig_emit_tpc(), brix_qconfig_emit_tpcdlg(), brix_qconfig_emit_version(), and brix_qconfig_emit_xrdfs_ext().
brix_qconfig_codec_list()
static void brix_qconfig_codec_list (char * list, size_t list_sz) static
Definition at line 115 of file config.c.
References brix_codec_desc_t::available, brix_codec_by_id(), BRIX_CODEC_MAX, and brix_codec_desc_t::name.
Referenced by brix_qconfig_emit_cmpread(), and brix_qconfig_emit_cmpwrite().
brix_qconfig_emit_bind_max()
static ngx_flag_t brix_qconfig_emit_bind_max (ngx_stream_brix_srv_conf_t * conf, char * resp, size_t resp_sz, size_t * pos) static
Definition at line 291 of file config.c.
References brix_qconfig_append().
brix_qconfig_emit_chksum()
static ngx_flag_t brix_qconfig_emit_chksum (ngx_stream_brix_srv_conf_t * conf, char * resp, size_t resp_sz, size_t * pos) static
Definition at line 145 of file config.c.
References brix_qconfig_append().
brix_qconfig_emit_cmpread()
static ngx_flag_t brix_qconfig_emit_cmpread (ngx_stream_brix_srv_conf_t * conf, char * resp, size_t resp_sz, size_t * pos) static
Definition at line 227 of file config.c.
References brix_qconfig_append(), and brix_qconfig_codec_list().
brix_qconfig_emit_cmpwrite()
static ngx_flag_t brix_qconfig_emit_cmpwrite (ngx_stream_brix_srv_conf_t * conf, char * resp, size_t resp_sz, size_t * pos) static
Definition at line 246 of file config.c.
References brix_qconfig_append(), and brix_qconfig_codec_list().
brix_qconfig_emit_fattr()
static ngx_flag_t brix_qconfig_emit_fattr (ngx_stream_brix_srv_conf_t * conf, char * resp, size_t resp_sz, size_t * pos) static
Definition at line 329 of file config.c.
References brix_qconfig_append().
brix_qconfig_emit_key()
static ngx_flag_t brix_qconfig_emit_key (const char * key, ngx_stream_brix_srv_conf_t * conf, char * resp, size_t resp_sz, size_t * pos) static
Definition at line 373 of file config.c.
References brix_qconfig_append(), brix_qconfig_table, brix_qconfig_entry_t::emit, brix_qconfig_entry_t::key, and key.
Referenced by brix_query_config().
brix_qconfig_emit_pio_max()
static ngx_flag_t brix_qconfig_emit_pio_max (ngx_stream_brix_srv_conf_t * conf, char * resp, size_t resp_sz, size_t * pos) static
Definition at line 303 of file config.c.
References brix_qconfig_append().
brix_qconfig_emit_readv()
static ngx_flag_t brix_qconfig_emit_readv (ngx_stream_brix_srv_conf_t * conf, char * resp, size_t resp_sz, size_t * pos) static
Definition at line 157 of file config.c.
References brix_qconfig_append().
brix_qconfig_emit_readv_ior_max()
static ngx_flag_t brix_qconfig_emit_readv_ior_max (ngx_stream_brix_srv_conf_t * conf, char * resp, size_t resp_sz, size_t * pos) static
Definition at line 170 of file config.c.
References brix_qconfig_append().
brix_qconfig_emit_readv_iov_max()
static ngx_flag_t brix_qconfig_emit_readv_iov_max (ngx_stream_brix_srv_conf_t * conf, char * resp, size_t resp_sz, size_t * pos) static
Definition at line 181 of file config.c.
References brix_qconfig_append(), and BRIX_READV_MAXSEGS.
brix_qconfig_emit_role()
static ngx_flag_t brix_qconfig_emit_role (ngx_stream_brix_srv_conf_t * conf, char * resp, size_t resp_sz, size_t * pos) static
Definition at line 315 of file config.c.
References brix_qconfig_append().
brix_qconfig_emit_tpc()
static ngx_flag_t brix_qconfig_emit_tpc (ngx_stream_brix_srv_conf_t * conf, char * resp, size_t resp_sz, size_t * pos) static
Definition at line 199 of file config.c.
References brix_qconfig_append().
brix_qconfig_emit_tpcdlg()
static ngx_flag_t brix_qconfig_emit_tpcdlg (ngx_stream_brix_srv_conf_t * conf, char * resp, size_t resp_sz, size_t * pos) static
Definition at line 212 of file config.c.
References brix_qconfig_append().
brix_qconfig_emit_version()
static ngx_flag_t brix_qconfig_emit_version (ngx_stream_brix_srv_conf_t * conf, char * resp, size_t resp_sz, size_t * pos) static
Definition at line 279 of file config.c.
References brix_qconfig_append(), and BRIX_SERVER_VERSION.
brix_qconfig_emit_xrdfs_ext()
static ngx_flag_t brix_qconfig_emit_xrdfs_ext (ngx_stream_brix_srv_conf_t * conf, char * resp, size_t resp_sz, size_t * pos) static
Definition at line 265 of file config.c.
References brix_qconfig_append().
brix_qconfig_next_token()
static ngx_flag_t brix_qconfig_next_token (const char ** pp, char * tok, size_t tok_sz) static
Definition at line 40 of file config.c.
References brix_qconfig_skip_ws().
Referenced by brix_query_config().
brix_qconfig_skip_ws()
static void brix_qconfig_skip_ws (const char ** pp) static
Definition at line 28 of file config.c.
Referenced by brix_qconfig_next_token().
brix_query_config()
ngx_int_t brix_query_config (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 390 of file config.c.
References brix_qconfig_emit_key(), brix_qconfig_next_token(), brix_send_error(), brix_send_ok(), c, brix_ctx_recv_t::cur_dlen, key, kXR_ArgMissing, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by brix_query_route_common().
Variable Documentation
brix_qconfig_table
const brix_qconfig_entry_t brix_qconfig_table[] static
Initial value:
= {
    { "chksum",        brix_qconfig_emit_chksum        },
    { "readv",         brix_qconfig_emit_readv         },
    { "readv_ior_max", brix_qconfig_emit_readv_ior_max },
    { "readv_iov_max", brix_qconfig_emit_readv_iov_max },
    { "tpc",           brix_qconfig_emit_tpc           },
    { "tpcdlg",        brix_qconfig_emit_tpcdlg        },
    { "cmpread",       brix_qconfig_emit_cmpread       },
    { "cmpwrite",      brix_qconfig_emit_cmpwrite      },
    { "xrdfs.ext",     brix_qconfig_emit_xrdfs_ext     },
    { "version",       brix_qconfig_emit_version       },
    { "bind_max",      brix_qconfig_emit_bind_max      },
    { "pio_max",       brix_qconfig_emit_pio_max       },
    { "role",          brix_qconfig_emit_role          },
    { "fattr",         brix_qconfig_emit_fattr         },
    { NULL,            NULL                            },
}
Definition at line 347 of file config.c.
Referenced by brix_qconfig_emit_key().