nginx-xrootd: src/protocols/root/query/space.c File Reference
space.c File Reference
#include "query_internal.h"
#include "core/compat/fs_usage.h"
#include "protocols/root/protocol/qspace.h"
#include <errno.h>
Functions
ngx_int_t brix_query_space (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_query_fsinfo (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_query_fsinfo()
ngx_int_t brix_query_fsinfo (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 119 of file space.c.
References brix_fs_usage_t::available_bytes, brix_fs_usage_stat(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_QUERY_FSINFO, brix_send_error(), brix_send_ok(), c, ngx_stream_brix_srv_conf_t::common, kXR_IOError, ngx_http_brix_shared_conf_t::root, brix_fs_usage_t::total_bytes, and brix_fs_usage_t::used_bytes.
Referenced by brix_handle_query().
brix_query_space()
ngx_int_t brix_query_space (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 51 of file space.c.
References brix_fs_usage_t::available_bytes, brix_fs_usage_stat(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_QUERY_SPACE, brix_qspace_format(), brix_send_error(), brix_send_ok(), c, ngx_stream_brix_srv_conf_t::common, brix_ctx_recv_t::cur_dlen, kXR_IOError, kXR_NotAuthorized, brix_ctx_recv_t::payload, brix_ctx_t::recv, ngx_http_brix_shared_conf_t::root, brix_fs_usage_t::total_bytes, and brix_fs_usage_t::used_bytes.
Referenced by brix_handle_query().