nginx-xrootd: src/protocols/s3/handler.c File Reference
handler.c File Reference
#include "s3.h"
#include "tagging.h"
#include "auth/impersonate/lifecycle.h"
#include "core/http/http_body.h"
#include "core/http/http_headers.h"
#include "core/http/http_query.h"
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include "auth/authz/acc/acc.h"
#include "core/compat/alloc_guard.h"
Functions
static brix_acc_op_t s3_method_aop (ngx_http_request_t *r)
static ngx_int_t s3_acc_check (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, brix_identity_t *id)
static int s3_parse_uri (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, u_char *key_out, size_t key_sz)
static int s3_is_list_request (ngx_http_request_t *r)
static ngx_flag_t s3_is_post_object_form (ngx_http_request_t *r)
static ngx_uint_t s3_allow_flags (ngx_http_s3_loc_conf_t *cf)
static ngx_int_t s3_add_preflight_headers (ngx_http_request_t *r, const ngx_str_t *allow)
static ngx_int_t s3_handle_options (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf)
static ngx_int_t s3_dispatch_after_auth (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, ngx_http_s3_req_ctx_t *s3ctx, ngx_uint_t method_slot, int is_list_request, ngx_flag_t is_post_object_form)
ngx_int_t ngx_http_s3_handler (ngx_http_request_t *r)
Function Documentation
ngx_http_s3_handler()
ngx_int_t ngx_http_s3_handler (ngx_http_request_t * r)
Definition at line 362 of file handler.c.
References brix_http_source_offer(), brix_identity_alloc(), brix_identity_dn_cstr(), brix_identity_vo_csv_cstr(), brix_imp_request_begin(), brix_imp_request_end(), BRIX_PCALLOC_OR_RETURN, brix_pmark_http_mark(), BRIX_S3_METHOD_LIST, ngx_http_s3_loc_conf_t::common, ngx_http_brix_shared_conf_t::enable, brix_pmark_conf_t::enable, brix_pmark_conf_t::http_plain, ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, ngx_http_brix_shared_conf_t::pmark, s3_acc_check(), s3_dispatch_after_auth(), s3_handle_options(), s3_is_list_request(), s3_is_post_object_form(), s3_metrics_method_slot(), s3_metrics_request_method(), s3_metrics_return_method(), s3_sess_attempt_request(), s3_sess_begin_request(), and s3_verify_sigv4().
Referenced by ngx_http_s3_set().
s3_acc_check()
static ngx_int_t s3_acc_check (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, brix_identity_t * id) static
Definition at line 64 of file handler.c.
References ngx_http_s3_loc_conf_t::acc, brix_acc_http_authorize(), brix_acc_resolve_peer(), BRIX_AUTHDB_FORMAT_XRDACC, brix_identity_acc_group_cstr(), brix_identity_acc_role_cstr(), brix_identity_acc_vorg_cstr(), brix_identity_dn_cstr(), brix_acc_http_t::format, name, ngx_memcpy, brix_acc_http_t::resolve_hosts, and s3_method_aop().
Referenced by ngx_http_s3_handler().
s3_add_preflight_headers()
static ngx_int_t s3_add_preflight_headers (ngx_http_request_t * r, const ngx_str_t * allow) static
Definition at line 243 of file handler.c.
References brix_http_find_header(), brix_http_set_header(), brix_http_set_header_str(), and brix_http_str_has_ctl().
Referenced by s3_handle_options().
s3_allow_flags()
static ngx_uint_t s3_allow_flags (ngx_http_s3_loc_conf_t * cf) static
Definition at line 230 of file handler.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_OP_ASYNC_BODY, BRIX_PROTO_OP_LIST, BRIX_PROTO_OP_READ, BRIX_PROTO_OP_WRITE, and ngx_http_s3_loc_conf_t::common.
Referenced by s3_handle_options().
s3_dispatch_after_auth()
static ngx_int_t s3_dispatch_after_auth (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, ngx_http_s3_req_ctx_t * s3ctx, ngx_uint_t method_slot, int is_list_request, ngx_flag_t is_post_object_form) static
Definition at line 474 of file handler.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_identity_t::auth_method, BRIX_AOP_CREATE, BRIX_AOP_DELETE, BRIX_AUTHN_TOKEN, brix_http_find_header(), brix_http_read_body(), brix_identity_check_token_scope(), BRIX_S3_EVENT_ACCESS_DENIED, BRIX_S3_EVENT_INVALID_URI, BRIX_S3_EVENT_METHOD_NOT_ALLOWED, BRIX_S3_EVENT_WRITE_DISABLED, BRIX_S3_METRIC_INC, c, ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::exclusive_create, ngx_http_s3_req_ctx_t::fs_path, ngx_http_s3_req_ctx_t::identity, key, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, s3_delete_objects_body_handler(), s3_get_mpu_dir(), s3_get_query_param(), s3_handle_copy_object(), s3_handle_delete(), s3_handle_delete_object_tagging(), s3_handle_get(), s3_handle_get_acl(), s3_handle_get_bucket_location(), s3_handle_get_bucket_versioning(), s3_handle_get_cors(), s3_handle_get_object_tagging(), s3_handle_head(), s3_handle_head_bucket(), s3_handle_list(), s3_handle_list_multipart_uploads(), s3_handle_list_parts(), s3_handle_list_v1(), s3_handle_multipart_abort(), s3_handle_multipart_initiate(), s3_handle_upload_part_copy(), s3_has_query_flag(), S3_MAX_KEY, s3_method_aop(), s3_metrics_return_method(), s3_multipart_complete_body_handler(), s3_parse_uri(), s3_post_object_body_handler(), s3_put_body_handler(), s3_put_is_exclusive_create(), s3_put_object_tagging_body_handler(), s3_put_precondition(), s3_resolve_key(), and s3_send_xml_error().
Referenced by ngx_http_s3_handler().
s3_handle_options()
static ngx_int_t s3_handle_options (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf) static
Definition at line 292 of file handler.c.
References brix_http_operation_allow_header(), brix_s3_operations, brix_s3_operations_count, s3_add_preflight_headers(), and s3_allow_flags().
Referenced by ngx_http_s3_handler().
s3_is_list_request()
static int s3_is_list_request (ngx_http_request_t * r) static
Definition at line 197 of file handler.c.
References brix_http_query_get().
Referenced by ngx_http_s3_handler().
s3_is_post_object_form()
static ngx_flag_t s3_is_post_object_form (ngx_http_request_t * r) static
Definition at line 211 of file handler.c.
References brix_http_find_header().
Referenced by ngx_http_s3_handler().
s3_method_aop()
static brix_acc_op_t s3_method_aop (ngx_http_request_t * r) static
Definition at line 47 of file handler.c.
References BRIX_AOP_CREATE, BRIX_AOP_DELETE, BRIX_AOP_READ, and BRIX_AOP_STAT.
Referenced by s3_acc_check(), and s3_dispatch_after_auth().
s3_parse_uri()
static int s3_parse_uri (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, u_char * key_out, size_t key_sz) static
Definition at line 134 of file handler.c.
References brix_http_urldecode(), BRIX_URLDECODE_OK, BRIX_URLDECODE_PLUS_TO_SPACE, BRIX_URLDECODE_REJECT_NUL, and ngx_http_s3_loc_conf_t::bucket.
Referenced by s3_dispatch_after_auth().