nginx-xrootd: src/protocols/webdav/delegation.h File Reference
delegation.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
Functions
void webdav_delegation_handle (ngx_http_request_t *r)
ngx_int_t webdav_delegation_request_handle (ngx_http_request_t *r)
void webdav_delegation_put_handle (ngx_http_request_t *r)
Function Documentation
webdav_delegation_handle()
void webdav_delegation_handle (ngx_http_request_t * r)
Definition at line 1439 of file delegation.c.
References BRIX_DELEGATION_BODY_MAX, brix_http_body_read_all(), delegation_client_authenticated(), delegation_reject(), delegation_validate_and_store(), and ngx_http_brix_webdav_module.
Referenced by webdav_dispatch_delegation_upload().
webdav_delegation_put_handle()
void webdav_delegation_put_handle (ngx_http_request_t * r)
Definition at line 1276 of file delegation.c.
References BRIX_DELEG_ID_HEXLEN, BRIX_DELEGATION_BODY_MAX, brix_http_body_read_all(), BRIX_UCRED_KEY_MAX, delegation_client_authenticated(), delegation_extract_id(), delegation_put_assemble(), delegation_put_store(), delegation_put_take_key(), delegation_put_validate_chain(), delegation_reject(), key, ngx_http_brix_webdav_module, and ngx_memcpy.
Referenced by webdav_dispatch_delegation_gridsite().
webdav_delegation_request_handle()
ngx_int_t webdav_delegation_request_handle (ngx_http_request_t * r)
Definition at line 885 of file delegation.c.
References BRIX_DELEG_ID_HEXLEN, brix_deleg_store(), brix_deleg_store_put(), brix_gsi_build_pxyreq(), brix_gsi_buf_t::data, delegation_client_authenticated(), delegation_get_peer_pem(), delegation_req_der_to_pem(), delegation_request_reject(), delegation_send_csr(), ngx_http_brix_webdav_req_ctx_t::dn, brix_gsi_buf_t::len, and ngx_http_brix_webdav_module.
Referenced by webdav_dispatch_delegation_gridsite().