nginx-xrootd: src/protocols/root/connection/recv_frame.c File Reference
recv_frame.c File Reference
#include "recv_frame.h"
#include "disconnect.h"
#include "fd_table.h"
#include "tls.h"
#include "budget.h"
#include "deadline.h"
#include "net/manager/pending.h"
#include "fs/xfer/stage_waiter.h"
#include "protocols/root/handoff/handoff.h"
Functions
brix_recv_step_t brix_recv_run_deferred (ngx_stream_session_t *s, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, brix_ctx_t *ctx, ngx_event_t *rev, size_t *rx_pending)
static brix_recv_step_t brix_recv_header_prep (ngx_stream_session_t *s, ngx_connection_t *c, brix_ctx_t *ctx, size_t rx_pending)
static brix_recv_step_t brix_recv_handle_nonxrootd (ngx_stream_session_t *s, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, brix_ctx_t *ctx)
static brix_recv_step_t brix_recv_advance (ngx_stream_session_t *s, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, brix_ctx_t *ctx, size_t avail, size_t need, size_t *rx_pending)
brix_recv_step_t brix_recv_read_frame (ngx_stream_session_t *s, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, brix_ctx_t *ctx, ngx_event_t *rev, size_t *rx_pending)
Function Documentation
brix_recv_advance()
static brix_recv_step_t brix_recv_advance (ngx_stream_session_t * s, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, brix_ctx_t * ctx, size_t avail, size_t need, size_t * rx_pending) static
Definition at line 173 of file recv_frame.c.
References brix_recv_handle_nonxrootd(), BRIX_RECV_STEP_CONTINUE, BRIX_RECV_STEP_NEXT, c, brix_ctx_recv_t::hdr_buf, brix_ctx_recv_t::hdr_pos, brix_ctx_recv_t::payload_pos, brix_ctx_t::recv, s, brix_ctx_t::state, XRD_ST_HANDSHAKE, and XRD_ST_REQ_HEADER.
Referenced by brix_recv_read_frame().
brix_recv_handle_nonxrootd()
static brix_recv_step_t brix_recv_handle_nonxrootd (ngx_stream_session_t * s, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, brix_ctx_t * ctx) static
Definition at line 150 of file recv_frame.c.
References brix_http_handoff_start(), BRIX_RECV_STEP_BREAK, BRIX_RECV_STEP_RETURN, c, brix_ctx_recv_t::hdr_buf, brix_ctx_recv_t::hdr_pos, brix_ctx_t::recv, and s.
Referenced by brix_recv_advance().
brix_recv_header_prep()
static brix_recv_step_t brix_recv_header_prep (ngx_stream_session_t * s, ngx_connection_t * c, brix_ctx_t * ctx, size_t rx_pending) static
Definition at line 86 of file recv_frame.c.
References brix_budget_sync(), brix_close_all_files(), brix_ctx_has_open_file(), brix_on_disconnect(), BRIX_RECV_STEP_NEXT, BRIX_RECV_STEP_RETURN, BRIX_SRV_METRIC_ADD, brix_trim_scratch(), c, brix_ctx_out_t::count, brix_ctx_t::out, brix_ctx_out_t::pipeline_depth, s, brix_ctx_t::state, brix_ctx_out_t::wr_inflight, and XRD_ST_SENDING.
Referenced by brix_recv_read_frame().
brix_recv_read_frame()
brix_recv_step_t brix_recv_read_frame (ngx_stream_session_t * s, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, brix_ctx_t * ctx, ngx_event_t * rev, size_t * rx_pending)
Definition at line 201 of file recv_frame.c.
References brix_arm_read_deadline(), brix_close_all_files(), brix_defer_teardown_if_writing(), brix_on_disconnect(), brix_recv_advance(), brix_recv_header_prep(), BRIX_RECV_STEP_BREAK, BRIX_RECV_STEP_NEXT, BRIX_RECV_STEP_RETURN, BRIX_SRV_METRIC_ADD, c, brix_ctx_recv_t::cur_body_extra, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::hdr_buf, brix_ctx_recv_t::hdr_pos, brix_ctx_recv_t::payload, brix_ctx_recv_t::payload_pos, brix_ctx_t::recv, s, brix_ctx_t::state, XRD_HANDSHAKE_LEN, XRD_REQUEST_HDR_LEN, XRD_ST_HANDSHAKE, and XRD_ST_REQ_HEADER.
Referenced by ngx_stream_brix_recv().
brix_recv_run_deferred()
brix_recv_step_t brix_recv_run_deferred (ngx_stream_session_t * s, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, brix_ctx_t * ctx, ngx_event_t * rev, size_t * rx_pending)
Definition at line 21 of file recv_frame.c.
References brix_dispatch(), BRIX_RECV_STEP_BREAK, BRIX_RECV_STEP_CONTINUE, BRIX_RECV_STEP_RETURN, BRIX_SRV_METRIC_ADD, brix_start_tls(), c, brix_ctx_out_t::count, brix_ctx_recv_t::cur_streamid, brix_ctx_out_t::deferred_streamid, brix_ctx_recv_t::hdr_pos, brix_ctx_t::out, brix_ctx_t::recv, brix_ctx_out_t::recv_deferred, brix_ctx_t::state, brix_ctx_t::tls_pending, brix_ctx_out_t::wr_inflight, XRD_ST_AIO, XRD_ST_REQ_HEADER, and XRD_ST_SENDING.
Referenced by ngx_stream_brix_recv().