nginx-xrootd: src/protocols/root/session/lifecycle.c File Reference
lifecycle.c File Reference
#include "core/ngx_brix_module.h"
#include "net/proxy/proxy.h"
#include "net/proxy/proxy_internal.h"
#include "registry.h"
Functions
ngx_int_t brix_handle_ping (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_handle_endsess (brix_ctx_t *ctx, ngx_connection_t *c)
Function Documentation
brix_handle_endsess()
ngx_int_t brix_handle_endsess (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 23 of file lifecycle.c.
References brix_ctx_login_t::auth_done, brix_close_all_files(), brix_on_disconnect(), brix_send_ok(), BRIX_SESSION_ID_LEN, brix_session_unregister(), c, brix_ctx_recv_t::hdr_buf, kXR_endsess, brix_ctx_login_t::logged_in, brix_ctx_t::login, brix_ctx_t::proxy, brix_ctx_t::recv, ClientEndsessRequest::sessid, brix_ctx_login_t::sessid, XRD_PX_IDLE, and XRD_REQUEST_HDR_LEN.
Referenced by brix_dispatch_session_opcode().
brix_handle_ping()
ngx_int_t brix_handle_ping (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 13 of file lifecycle.c.
References BRIX_OP_PING, BRIX_RETURN_OK, and c.
Referenced by brix_dispatch_session_opcode().