nginx-xrootd: src/protocols/ssi/provider_unittest.c File Reference
provider_unittest.c File Reference
#include "provider.h"
#include <stdio.h>
#include <string.h>
Macros
#define CHECK(cond)
Functions
static void test_known_service (void)
static void test_unknown_service (void)
static void test_null_name (void)
int main (void)
Variables
static int g_fail
Macro Definition Documentation
CHECK
#define CHECK (cond)
Value:
    do { \
    if (!(cond)) { printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
                   g_fail++; } \
} while (0)
Definition at line 15 of file provider_unittest.c.
Function Documentation
main()
int main (void)
Definition at line 41 of file provider_unittest.c.
References g_fail, test_known_service(), test_null_name(), and test_unknown_service().
test_known_service()
static void test_known_service (void) static
Definition at line 20 of file provider_unittest.c.
References brix_ssi_provider_lookup(), CHECK, brix_ssi_provider_t::name, and brix_ssi_provider_t::process.
Referenced by main().
test_null_name()
static void test_null_name (void) static
Definition at line 35 of file provider_unittest.c.
References brix_ssi_provider_lookup(), and CHECK.
Referenced by main().
test_unknown_service()
static void test_unknown_service (void) static
Definition at line 28 of file provider_unittest.c.
References brix_ssi_provider_lookup(), and CHECK.
Referenced by main().
Variable Documentation
g_fail
int g_fail static
Definition at line 14 of file provider_unittest.c.
Referenced by main().