nginx-xrootd: src/net/proxy/proxy_internal.h File Reference
proxy_internal.h File Reference
#include "proxy.h"
#include "net/tap/tap.h"
Data Structures
struct brix_proxy_fh_entry_t
struct brix_proxy_pooled_conn_t
struct brix_proxy_up_status_t
struct brix_proxy_ctx_t
Macros
#define BRIX_PROXY_MAX_BODY (16 * 1024 * 1024)
#define BRIX_PROXY_FH_FREE (-1)
#define BRIX_PROXY_PATH_MAX 512
#define BRIX_PROXY_MAX_WAIT_RETRIES 5
#define BRIX_PROXY_MAX_WAIT_SECS 30
#define BRIX_PROXY_POOL_SIZE 32
#define BRIX_PROXY_POOL_KEEPALIVE 60
#define BRIX_PROXY_MAX_FAILS 3
#define BRIX_PROXY_FAIL_TIMEOUT 10
#define BRIX_PROXY_MAX_CONN_FAILS 8
Enumerations
enum brix_proxy_up_state_t {
XRD_PX_CONNECTING = 0 , XRD_PX_TLS_HANDSHAKE , XRD_PX_BOOTSTRAP , XRD_PX_IDLE ,
XRD_PX_FORWARDING
}
enum brix_proxy_bs_t {
XRD_PX_BS_HANDSHAKE = 0 , XRD_PX_BS_PROTOCOL , XRD_PX_BS_LOGIN , XRD_PX_BS_AUTH ,
XRD_PX_BS_DONE
}
Functions
void brix_proxy_tap_audit_sink (void *ctx, const brix_tap_frame_t *f, brix_tap_dir_t dir, const u_char *payload, size_t payload_len)
void brix_proxy_tap_init (brix_proxy_ctx_t *proxy, ngx_connection_t *c)
ngx_int_t brix_proxy_gsi_connect_async (brix_proxy_ctx_t *proxy, ngx_stream_brix_srv_conf_t *conf, ngx_str_t *host, uint16_t port)
ngx_int_t brix_proxy_connect (brix_proxy_ctx_t *proxy, ngx_connection_t *client_conn, ngx_stream_brix_srv_conf_t *conf)
void brix_proxy_abort (brix_proxy_ctx_t *proxy, const char *reason)
ngx_int_t brix_proxy_flush (brix_proxy_ctx_t *proxy)
static void brix_proxy_wbuf_release (brix_proxy_ctx_t *proxy)
size_t brix_proxy_build_bootstrap (u_char *buf, const char *username)
void brix_proxy_pool_init (void)
void brix_proxy_pool_shutdown (void)
ngx_connection_t * brix_proxy_pool_get (brix_proxy_ctx_t *proxy, ngx_stream_brix_srv_conf_t *conf, int *idx_out)
void brix_proxy_pool_put (brix_proxy_ctx_t *proxy)
void brix_proxy_up_status_init (ngx_stream_brix_srv_conf_t *conf)
void brix_proxy_up_mark_failed (brix_proxy_ctx_t *proxy)
void brix_proxy_up_mark_ok (brix_proxy_ctx_t *proxy)
void brix_proxy_write_handler (ngx_event_t *wev)
void brix_proxy_read_handler (ngx_event_t *rev)
void brix_proxy_handle_bootstrap (brix_proxy_ctx_t *proxy)
void brix_proxy_splice_pump (brix_proxy_ctx_t *proxy)
ngx_int_t brix_proxy_try_splice (brix_proxy_ctx_t *proxy)
void brix_proxy_splice_fallback_finish (brix_proxy_ctx_t *proxy)
ngx_int_t brix_proxy_forward_request (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_proxy_fh_translate_single (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, u_char *req, size_t total, uint16_t reqid, size_t body_len)
ngx_int_t brix_proxy_fh_translate_vector (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, u_char *req, size_t total, uint16_t reqid, uint32_t cur_dlen)
void brix_proxy_relay_to_client (brix_proxy_ctx_t *proxy)
int brix_proxy_alloc_local_fh (brix_proxy_ctx_t *proxy)
void proxy_write_audit (brix_proxy_ctx_t *proxy, int local_fh)
u_char * proxy_rewrite_path (ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, u_char *req, size_t total, size_t path_off, size_t path_len, size_t *total_out)
u_char * proxy_rewrite_prepare_payload (ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, u_char *req, size_t total, size_t *total_out)
int proxy_translate_fh (brix_proxy_ctx_t *proxy, u_char *buf, size_t offset)
ngx_int_t proxy_reject_request (brix_ctx_t *ctx, ngx_connection_t *c, u_char *req, uint16_t errcode, const char *msg)
ngx_int_t brix_proxy_lazy_open (brix_proxy_ctx_t *proxy, brix_ctx_t *ctx, ngx_connection_t *c, int local_fh, u_char *read_req, size_t read_req_len)
ngx_int_t brix_proxy_dispatch_pending (brix_proxy_ctx_t *proxy)
void brix_proxy_wait_handler (ngx_event_t *ev)
Variables
brix_proxy_up_status_t * proxy_up_status
Macro Definition Documentation
BRIX_PROXY_FAIL_TIMEOUT
#define BRIX_PROXY_FAIL_TIMEOUT 10
Definition at line 50 of file proxy_internal.h.
BRIX_PROXY_FH_FREE
#define BRIX_PROXY_FH_FREE (-1)
Definition at line 33 of file proxy_internal.h.
BRIX_PROXY_MAX_BODY
#define BRIX_PROXY_MAX_BODY (16 * 1024 * 1024)
Definition at line 30 of file proxy_internal.h.
BRIX_PROXY_MAX_CONN_FAILS
#define BRIX_PROXY_MAX_CONN_FAILS 8
Definition at line 57 of file proxy_internal.h.
BRIX_PROXY_MAX_FAILS
#define BRIX_PROXY_MAX_FAILS 3
Definition at line 49 of file proxy_internal.h.
BRIX_PROXY_MAX_WAIT_RETRIES
#define BRIX_PROXY_MAX_WAIT_RETRIES 5
Definition at line 39 of file proxy_internal.h.
BRIX_PROXY_MAX_WAIT_SECS
#define BRIX_PROXY_MAX_WAIT_SECS 30
Definition at line 41 of file proxy_internal.h.
BRIX_PROXY_PATH_MAX
#define BRIX_PROXY_PATH_MAX 512
Definition at line 36 of file proxy_internal.h.
BRIX_PROXY_POOL_KEEPALIVE
#define BRIX_PROXY_POOL_KEEPALIVE 60
Definition at line 46 of file proxy_internal.h.
BRIX_PROXY_POOL_SIZE
#define BRIX_PROXY_POOL_SIZE 32
Definition at line 44 of file proxy_internal.h.
Enumeration Type Documentation
brix_proxy_bs_t
enum brix_proxy_bs_t
Enumerator
XRD_PX_BS_HANDSHAKE
XRD_PX_BS_PROTOCOL
XRD_PX_BS_LOGIN
XRD_PX_BS_AUTH
XRD_PX_BS_DONE
Definition at line 80 of file proxy_internal.h.
brix_proxy_up_state_t
enum brix_proxy_up_state_t
Enumerator
XRD_PX_CONNECTING
XRD_PX_TLS_HANDSHAKE
XRD_PX_BOOTSTRAP
XRD_PX_IDLE
XRD_PX_FORWARDING
Definition at line 72 of file proxy_internal.h.
Function Documentation
brix_proxy_abort()
void brix_proxy_abort (brix_proxy_ctx_t * proxy, const char * reason)
Definition at line 46 of file connect_lifecycle.c.
References BRIX_MAX_FILES, brix_proxy_cleanup(), brix_proxy_connect(), BRIX_PROXY_FH_FREE, BRIX_PROXY_METRIC_INC, BRIX_PROXY_UP_INC, brix_proxy_up_mark_failed(), brix_schedule_read_resume(), brix_send_error(), c, brix_ctx_t::destroyed, kXR_IOError, brix_ctx_t::proxy, brix_ctx_t::proxy_fail_count, brix_ctx_t::state, XRD_PX_BS_HANDSHAKE, XRD_PX_CONNECTING, XRD_PX_IDLE, and XRD_ST_REQ_HEADER.
Referenced by brix_proxy_build_relay_buffer(), brix_proxy_check_connect(), brix_proxy_dispatch_saved_read(), brix_proxy_flush_buffered(), brix_proxy_handle_bootstrap(), brix_proxy_lazy_open(), brix_proxy_pending_flush(), brix_proxy_queue_and_flush(), brix_proxy_read_handler(), brix_proxy_wait_handler(), brix_proxy_write_complete(), brix_proxy_write_handler(), proxy_bs_auth_error(), proxy_bs_check_protocol_reply(), proxy_gsi_login_done(), proxy_read_arm(), proxy_read_dispatch(), proxy_read_expand_status(), proxy_read_fill_body(), proxy_read_fill_hdr(), and proxy_read_hdr_complete().
brix_proxy_alloc_local_fh()
int brix_proxy_alloc_local_fh (brix_proxy_ctx_t * proxy)
Definition at line 135 of file forward_session_helpers.c.
References BRIX_MAX_FILES, and BRIX_PROXY_FH_FREE.
Referenced by brix_proxy_dispatch(), and brix_proxy_forward_open().
brix_proxy_build_bootstrap()
size_t brix_proxy_build_bootstrap (u_char * buf, const char * username)
Definition at line 34 of file connect_upstream_bootstrap.c.
References xrdw_login_req_t::capver, xrdw_protocol_req_t::clientpv, kXR_login, kXR_protocol, kXR_PROTOCOLVERSION, kXR_ver005, ngx_memcpy, xrdw_login_req_t::pid, proxy_upstream_seq, ClientProtocolRequest::requestid, ClientLoginRequest::requestid, ROOTD_PQ, ClientProtocolRequest::streamid, ClientLoginRequest::streamid, xrdw_login_req_t::username, xrdw_login_req_pack(), and xrdw_protocol_req_pack().
Referenced by pc_open_socket().
brix_proxy_connect()
ngx_int_t brix_proxy_connect (brix_proxy_ctx_t * proxy, ngx_connection_t * client_conn, ngx_stream_brix_srv_conf_t * conf)
Definition at line 446 of file connect_upstream.c.
References BRIX_PROXY_AUTH_GSI, brix_proxy_gsi_connect_async(), pc_target_t::fd, pc_target_t::host, pc_arm_events(), pc_open_socket(), pc_resolve_target(), pc_select_endpoint(), and pc_target_t::port.
Referenced by brix_proxy_abort(), brix_proxy_dispatch(), and brix_proxy_relay_try_redirect().
brix_proxy_dispatch_pending()
ngx_int_t brix_proxy_dispatch_pending (brix_proxy_ctx_t * proxy)
Definition at line 150 of file forward_relay_dispatch.c.
References brix_proxy_lazy_open(), brix_proxy_pending_flush(), brix_proxy_pending_lazy_fh(), BRIX_TAP_C2U, brix_tap_decode_request(), brix_tap_emit(), c, ClientRequestHdr::requestid, ClientRequestHdr::streamid, and XRD_REQUEST_HDR_LEN.
Referenced by pc_select_endpoint(), proxy_bs_adopt_conn(), and proxy_gsi_login_done().
brix_proxy_fh_translate_single()
ngx_int_t brix_proxy_fh_translate_single (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, u_char * req, size_t total, uint16_t reqid, size_t body_len)
Definition at line 155 of file forward_fh_translate.c.
References c, check_bound_secondary_lazy_open(), kXR_chkpoint, kXR_ckpXeq, kXR_InvalidRequest, proxy_reject_request(), proxy_translate_fh(), and translate_ckpxeq_sub_request().
Referenced by brix_proxy_translate_fh_op().
brix_proxy_fh_translate_vector()
ngx_int_t brix_proxy_fh_translate_vector (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, u_char * req, size_t total, uint16_t reqid, uint32_t cur_dlen)
Definition at line 284 of file forward_fh_translate.c.
References c, initiate_readv_lazy_open_queue(), brix_ctx_t::is_bound, kXR_InvalidRequest, kXR_readv, proxy_reject_request(), proxy_translate_fh(), and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_translate_fh_op().
brix_proxy_flush()
ngx_int_t brix_proxy_flush (brix_proxy_ctx_t * proxy)
Definition at line 20 of file connect_lifecycle.c.
Referenced by brix_proxy_dispatch_saved_read(), brix_proxy_flush_buffered(), brix_proxy_lazy_open(), brix_proxy_pending_flush(), brix_proxy_queue_and_flush(), brix_proxy_wait_handler(), pc_arm_events(), and proxy_bs_queue_auth_frame().
brix_proxy_forward_request()
ngx_int_t brix_proxy_forward_request (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 417 of file forward_request.c.
References brix_proxy_queue_and_flush(), brix_proxy_save_wait_retry(), brix_proxy_translate_dispatch(), brix_send_error(), BRIX_TAP_C2U, brix_tap_decode_request(), brix_tap_emit(), c, brix_ctx_recv_t::cur_body_extra, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, brix_ctx_recv_t::cur_streamid, brix_ctx_recv_t::hdr_buf, kXR_IOError, ngx_memcpy, brix_ctx_recv_t::payload, brix_ctx_t::recv, and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_dispatch().
brix_proxy_gsi_connect_async()
ngx_int_t brix_proxy_gsi_connect_async (brix_proxy_ctx_t * proxy, ngx_stream_brix_srv_conf_t * conf, ngx_str_t * host, uint16_t port)
Definition at line 182 of file gsi_upstream_login.c.
References BRIX_AF_AUTO, brix_proxy_gsi_write_pem_temp(), c, proxy_gsi_login_t::client_conn, proxy_gsi_login_t::deleg_path, brix_ctx_gsi_t::deleg_proxy_len, brix_ctx_gsi_t::deleg_proxy_pem, proxy_gsi_login_t::family, brix_ctx_t::gsi, proxy_gsi_login_t::gsi_store, host, proxy_gsi_login_t::host, proxy_gsi_login_t::log, port, proxy_gsi_login_t::port, proxy_gsi_login_t::proxy, proxy_gsi_login_done(), proxy_gsi_login_thread(), proxy_gsi_login_t::result_fd, and XRD_ST_PROXY.
Referenced by brix_proxy_connect().
brix_proxy_handle_bootstrap()
void brix_proxy_handle_bootstrap (brix_proxy_ctx_t * proxy)
Definition at line 162 of file events_bootstrap.c.
References brix_proxy_abort(), brix_proxy_bs_login(), kXR_ok, proxy_bs_adopt_conn(), proxy_bs_auth_error(), proxy_bs_check_protocol_reply(), proxy_bs_reset_resp(), XRD_PX_BS_AUTH, XRD_PX_BS_DONE, XRD_PX_BS_HANDSHAKE, XRD_PX_BS_LOGIN, and XRD_PX_BS_PROTOCOL.
Referenced by proxy_read_dispatch().
brix_proxy_lazy_open()
ngx_int_t brix_proxy_lazy_open (brix_proxy_ctx_t * proxy, brix_ctx_t * ctx, ngx_connection_t * c, int local_fh, u_char * read_req, size_t read_req_len)
Definition at line 164 of file forward_session_helpers.c.
References brix_ctx_t::bound_sessid, brix_proxy_abort(), brix_proxy_flush(), brix_send_error(), brix_session_handle_lookup(), c, ClientOpenRequest::dlen, kXR_InvalidRequest, kXR_IOError, kXR_open, kXR_open_read, ngx_memcpy, xrdw_open_req_t::options, brix_shared_handle_entry_t::path, ClientOpenRequest::requestid, brix_ctx_t::state, ClientOpenRequest::streamid, XRD_PX_FORWARDING, XRD_ST_PROXY, and xrdw_open_req_pack().
Referenced by brix_proxy_dispatch_pending(), brix_proxy_lazy_open_next(), check_bound_secondary_lazy_open(), and initiate_readv_lazy_open_queue().
brix_proxy_pool_get()
ngx_connection_t * brix_proxy_pool_get (brix_proxy_ctx_t * proxy, ngx_stream_brix_srv_conf_t * conf, int * idx_out)
Definition at line 270 of file pool.c.
References brix_proxy_pooled_conn_t::auth_type, BRIX_PROXY_AUTH_FORWARD, BRIX_PROXY_FAIL_TIMEOUT, brix_proxy_read_handler(), brix_proxy_up_status_init(), brix_proxy_write_handler(), c, brix_proxy_up_status_t::checked, brix_proxy_pooled_conn_t::conn, brix_proxy_pooled_conn_t::ping_ev, proxy_pool, proxy_pool_count, proxy_up_status, brix_proxy_pooled_conn_t::token_hash, and brix_proxy_pooled_conn_t::upstream_idx.
Referenced by pc_select_endpoint().
brix_proxy_pool_init()
void brix_proxy_pool_init (void)
Definition at line 257 of file pool.c.
References proxy_pool, and proxy_pool_count.
Referenced by ngx_stream_brix_init_process().
brix_proxy_pool_put()
void brix_proxy_pool_put (brix_proxy_ctx_t * proxy)
Definition at line 359 of file pool.c.
References brix_proxy_pooled_conn_t::auth_type, BRIX_PROXY_AUTH_FORWARD, brix_proxy_pool_evict(), brix_proxy_pool_ping_handler(), brix_proxy_pool_read_handler(), BRIX_PROXY_POOL_SIZE, brix_proxy_pool_write_handler(), brix_proxy_pooled_conn_t::conn, brix_proxy_pooled_conn_t::idle_since, brix_proxy_pooled_conn_t::keepalive_interval, brix_proxy_pooled_conn_t::ping_ev, proxy_pool, proxy_pool_count, brix_proxy_pooled_conn_t::queue, brix_proxy_pooled_conn_t::token_hash, brix_proxy_pooled_conn_t::upstream_idx, and XRD_PX_IDLE.
Referenced by brix_proxy_cleanup_conn().
brix_proxy_pool_shutdown()
void brix_proxy_pool_shutdown (void)
Definition at line 209 of file pool.c.
References brix_proxy_pooled_conn_t::conn, brix_proxy_pooled_conn_t::ping_ev, proxy_pool, proxy_pool_count, and brix_proxy_pooled_conn_t::queue.
Referenced by brix_exit_process().
brix_proxy_read_handler()
void brix_proxy_read_handler (ngx_event_t * rev)
Definition at line 423 of file events_read.c.
References brix_proxy_abort(), brix_proxy_cleanup(), BRIX_PXR_DONE, brix_ctx_t::destroyed, brix_ctx_t::proxy, and proxy_read_step().
Referenced by brix_proxy_pool_get(), pc_open_socket(), and proxy_gsi_promote_fd().
brix_proxy_relay_to_client()
void brix_proxy_relay_to_client (brix_proxy_ctx_t * proxy)
Definition at line 376 of file forward_relay_response.c.
References brix_proxy_build_relay_buffer(), brix_proxy_relay_absorb_wait(), brix_proxy_relay_close_status(), brix_proxy_relay_emit_tap(), brix_proxy_relay_finish_final(), brix_proxy_relay_io_metrics(), brix_proxy_relay_lazy_open(), brix_proxy_relay_open_status(), brix_proxy_relay_path_audit(), brix_proxy_relay_streaming_frame(), brix_proxy_relay_try_redirect(), brix_proxy_relay_wait_exhausted(), c, and kXR_status.
Referenced by proxy_read_dispatch().
brix_proxy_splice_fallback_finish()
void brix_proxy_splice_fallback_finish (brix_proxy_ctx_t * proxy)
Referenced by proxy_read_dispatch().
brix_proxy_splice_pump()
void brix_proxy_splice_pump (brix_proxy_ctx_t * proxy)
Referenced by proxy_read_fill_body().
brix_proxy_tap_audit_sink()
void brix_proxy_tap_audit_sink (void * ctx, const brix_tap_frame_t * f, brix_tap_dir_t dir, const u_char * payload, size_t payload_len)
Definition at line 12 of file forward_relay_dispatch.c.
References brix_tap_audit_format(), and log.
Referenced by brix_proxy_tap_init().
brix_proxy_tap_init()
void brix_proxy_tap_init (brix_proxy_ctx_t * proxy, ngx_connection_t * c)
Definition at line 27 of file forward_relay_dispatch.c.
References brix_proxy_tap_audit_sink(), brix_tap_register_sink(), and c.
Referenced by brix_proxy_dispatch().
brix_proxy_try_splice()
ngx_int_t brix_proxy_try_splice (brix_proxy_ctx_t * proxy)
Referenced by proxy_read_hdr_complete().
brix_proxy_up_mark_failed()
void brix_proxy_up_mark_failed (brix_proxy_ctx_t * proxy)
Definition at line 64 of file pool.c.
References BRIX_PROXY_MAX_FAILS, brix_proxy_up_status_t::checked, brix_proxy_up_status_t::down, fails, brix_proxy_up_status_t::fails, proxy_up_status, and proxy_up_status_count.
Referenced by brix_proxy_abort().
brix_proxy_up_mark_ok()
void brix_proxy_up_mark_ok (brix_proxy_ctx_t * proxy)
Definition at line 88 of file pool.c.
References brix_proxy_up_status_t::checked, brix_proxy_up_status_t::down, brix_proxy_up_status_t::fails, proxy_up_status, and proxy_up_status_count.
Referenced by proxy_bs_adopt_conn().
brix_proxy_up_status_init()
void brix_proxy_up_status_init (ngx_stream_brix_srv_conf_t * conf)
Definition at line 41 of file pool.c.
References brix_alloc_array(), proxy_up_status, and proxy_up_status_count.
Referenced by brix_proxy_pool_get().
brix_proxy_wait_handler()
void brix_proxy_wait_handler (ngx_event_t * ev)
Definition at line 70 of file forward_session_helpers.c.
References brix_proxy_abort(), brix_proxy_cleanup(), brix_proxy_flush(), brix_ctx_t::destroyed, XRD_PX_FORWARDING, and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_relay_absorb_wait().
brix_proxy_wbuf_release()
static void brix_proxy_wbuf_release (brix_proxy_ctx_t * proxy) inline static
Definition at line 254 of file proxy_internal.h.
Referenced by brix_proxy_cleanup_free_buffers(), brix_proxy_queue_and_flush(), and brix_proxy_write_complete().
brix_proxy_write_handler()
void brix_proxy_write_handler (ngx_event_t * wev)
Definition at line 244 of file events_write.c.
References brix_proxy_abort(), brix_proxy_cleanup(), brix_proxy_flush_buffered(), brix_proxy_handle_connecting(), brix_proxy_write_complete(), brix_ctx_t::destroyed, PW_DONE, XRD_PX_CONNECTING, and XRD_PX_TLS_HANDSHAKE.
Referenced by brix_proxy_pool_get(), pc_open_socket(), and proxy_gsi_promote_fd().
proxy_reject_request()
ngx_int_t proxy_reject_request (brix_ctx_t * ctx, ngx_connection_t * c, u_char * req, uint16_t errcode, const char * msg)
Definition at line 274 of file forward_rewrite_helpers.c.
References brix_send_error(), and c.
Referenced by brix_proxy_fh_translate_single(), brix_proxy_fh_translate_vector(), brix_proxy_forward_clone(), brix_proxy_forward_open(), brix_proxy_forward_stat(), translate_ckpxeq_sub_request(), and translate_ckpxeq_writev_fhandles().
proxy_rewrite_path()
u_char * proxy_rewrite_path (ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, u_char * req, size_t total, size_t path_off, size_t path_len, size_t * total_out)
Definition at line 22 of file forward_rewrite_helpers.c.
References c, ngx_memcpy, and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_forward_open(), and brix_proxy_forward_pathop().
proxy_rewrite_prepare_payload()
u_char * proxy_rewrite_prepare_payload (ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, u_char * req, size_t total, size_t * total_out)
Definition at line 211 of file forward_rewrite_helpers.c.
References proxy_prepare_rewrite_t::add, proxy_prepare_rewrite_t::alen, c, ngx_memcpy, proxy_prepare_rewrite_t::payload, proxy_prepare_rewrite_t::plen, proxy_prepare_emit(), proxy_prepare_measure(), proxy_prepare_rewrite_t::slen, proxy_prepare_rewrite_t::strip, and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_forward_prepare().
proxy_translate_fh()
int proxy_translate_fh (brix_proxy_ctx_t * proxy, u_char * buf, size_t offset)
Definition at line 289 of file forward_rewrite_helpers.c.
References BRIX_MAX_FILES, and BRIX_PROXY_FH_FREE.
Referenced by brix_proxy_fh_translate_single(), brix_proxy_fh_translate_vector(), brix_proxy_forward_clone(), brix_proxy_forward_stat(), translate_ckpxeq_sub_request(), and translate_ckpxeq_writev_fhandles().
proxy_write_audit()
void proxy_write_audit (brix_proxy_ctx_t * proxy, int local_fh)
Definition at line 34 of file forward_session_helpers.c.
References BRIX_MAX_FILES, brix_proxy_fh_entry_t::bytes_read, brix_proxy_fh_entry_t::bytes_written, brix_proxy_fh_entry_t::open_msec, and brix_proxy_fh_entry_t::path.
Referenced by brix_proxy_cleanup_audit_handles(), and brix_proxy_relay_close_status().
Variable Documentation
proxy_up_status
brix_proxy_up_status_t* proxy_up_status extern
Definition at line 33 of file pool.c.
Referenced by brix_proxy_pool_get(), brix_proxy_up_mark_failed(), brix_proxy_up_mark_ok(), brix_proxy_up_status_init(), and pc_pick_healthy_upstream().