nginx-xrootd: src/auth/gsi/proxy_req.h File Reference
proxy_req.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <openssl/evp.h>
Data Structures
struct brix_gsi_blob_t
struct brix_gsi_buf_t
struct brix_gsi_err_t
Functions
int brix_gsi_build_pxyreq (const brix_gsi_blob_t *parent_pem, EVP_PKEY **newkey, brix_gsi_buf_t *req_der, const brix_gsi_err_t *err)
int brix_gsi_sign_pxyreq (const brix_gsi_blob_t *signer_pem, EVP_PKEY *signer_key, const brix_gsi_blob_t *req_der, brix_gsi_buf_t *proxy_pem, const brix_gsi_err_t *err)
int brix_gsi_assemble_proxy (const brix_gsi_blob_t *proxy_pem, EVP_PKEY *reqkey, const brix_gsi_blob_t *chain_pem, brix_gsi_buf_t *out_pem, const brix_gsi_err_t *err)
Function Documentation
brix_gsi_assemble_proxy()
int brix_gsi_assemble_proxy (const brix_gsi_blob_t * proxy_pem, EVP_PKEY * reqkey, const brix_gsi_blob_t * chain_pem, brix_gsi_buf_t * out_pem, const brix_gsi_err_t * err)
Definition at line 105 of file proxy_req_assemble.c.
References asm_check_key_match(), asm_concat_pem(), brix_gsi_err_t::buf, brix_gsi_err_t::cap, asm_args::chain_pem, asm_args::chain_pem_len, brix_gsi_blob_t::data, brix_gsi_buf_t::data, asm_args::err, asm_args::errcap, brix_gsi_blob_t::len, brix_gsi_buf_t::len, asm_args::proxy_pem, and asm_args::proxy_pem_len.
Referenced by brix_gsi_handle_sigpxy(), delegation_put_assemble(), and test_assemble_proxy().
brix_gsi_build_pxyreq()
int brix_gsi_build_pxyreq (const brix_gsi_blob_t * parent_pem, EVP_PKEY ** newkey, brix_gsi_buf_t * req_der, const brix_gsi_err_t * err)
Definition at line 356 of file proxy_req.c.
References brix_gsi_err_t::buf, brix_gsi_err_t::cap, brix_gsi_blob_t::data, brix_gsi_buf_t::data, pxr_ctx::key, brix_gsi_blob_t::len, brix_gsi_buf_t::len, pxr_build_extstack(), pxr_build_subject(), pxr_fail(), pxr_load_parent_and_key(), and pxr_sign_and_encode_req().
Referenced by brix_gsi_begin_delegation(), test_build_pxyreq(), test_negatives(), test_two_level_delegation(), and webdav_delegation_request_handle().
brix_gsi_sign_pxyreq()
int brix_gsi_sign_pxyreq (const brix_gsi_blob_t * signer_pem, EVP_PKEY * signer_key, const brix_gsi_blob_t * req_der, brix_gsi_buf_t * proxy_pem, const brix_gsi_err_t * err)
Definition at line 317 of file proxy_req_sign.c.
References brix_gsi_err_t::buf, brix_gsi_err_t::cap, brix_gsi_blob_t::data, brix_gsi_buf_t::data, sgn_ctx::err, sgn_ctx::errcap, brix_gsi_blob_t::len, brix_gsi_buf_t::len, sgn_ctx::proxy, sgn_add_extensions(), sgn_args_ok(), sgn_check_signer_validity(), sgn_check_subject(), sgn_export_pem(), sgn_fail(), sgn_parse_inputs(), sgn_populate_proxy(), and sgn_verify_req_signature().
Referenced by gsi_sigpxy(), test_negatives(), test_sign_pxyreq(), and test_two_level_delegation().