nginx-xrootd: src/protocols/webdav/proxy_pool.c File Reference
proxy_pool.c File Reference
#include "core/ngx_brix_module.h"
#include "proxy_pool.h"
#include "core/compat/host_format.h"
#include "core/compat/shm_slots.h"
Functions
static brix_proxy_be_table_t * pool_table (void)
static ngx_int_t brix_proxy_pool_init_zone (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t brix_proxy_pool_configure (ngx_conf_t *cf)
static ngx_int_t proxy_pool_resolve (const char *url, ngx_pool_t *pool, ngx_log_t *log, brix_proxy_be_entry_t *out)
ngx_int_t brix_proxy_pool_add (const char *url, ngx_uint_t weight, ngx_pool_t *pool, ngx_log_t *log, uint32_t *id_out)
static int proxy_pool_set_state (uint32_t id, int remove_it, brix_proxy_be_state_e state)
int brix_proxy_pool_remove (uint32_t id)
int brix_proxy_pool_drain (uint32_t id)
int brix_proxy_pool_undrain (uint32_t id)
long brix_proxy_pool_in_flight (uint32_t id)
ngx_int_t brix_proxy_pool_select (brix_proxy_be_pick_t *out)
void brix_proxy_pool_dec_in_flight (uint32_t id)
ngx_uint_t brix_proxy_pool_snapshot (brix_proxy_be_snapshot_t *out, ngx_uint_t max)
Variables
static ngx_shm_zone_t * brix_proxy_pool_zone
static ngx_shmtx_t brix_proxy_pool_mutex
ngx_module_t ngx_http_brix_webdav_module
Function Documentation
brix_proxy_pool_add()
ngx_int_t brix_proxy_pool_add (const char * url, ngx_uint_t weight, ngx_pool_t * pool, ngx_log_t * log, uint32_t * id_out)
Definition at line 187 of file proxy_pool.c.
References brix_proxy_be_entry_t::added_at, BRIX_PROXY_BE_ACTIVE, brix_proxy_pool_mutex, brix_proxy_be_table_t::capacity, brix_proxy_be_entry_t::drained_at, brix_proxy_be_entry_t::host, brix_proxy_be_entry_t::id, brix_proxy_be_entry_t::in_flight, brix_proxy_be_entry_t::in_use, log, brix_proxy_be_table_t::next_id, ngx_memcpy, pool_table(), brix_proxy_be_entry_t::port, proxy_pool_resolve(), brix_proxy_be_table_t::slots, brix_proxy_be_entry_t::sockaddr, brix_proxy_be_entry_t::socklen, brix_proxy_be_entry_t::ssl, brix_proxy_be_entry_t::state, brix_proxy_be_entry_t::url_base, and brix_proxy_be_entry_t::weight.
Referenced by admin_proxy_add().
brix_proxy_pool_configure()
ngx_int_t brix_proxy_pool_configure (ngx_conf_t * cf)
Definition at line 79 of file proxy_pool.c.
References brix_proxy_pool_init_zone(), BRIX_PROXY_POOL_SLOTS, brix_proxy_pool_zone, brix_shm_zone_size(), name, and ngx_http_brix_webdav_module.
Referenced by webdav_proxy_pool_setup().
brix_proxy_pool_dec_in_flight()
void brix_proxy_pool_dec_in_flight (uint32_t id)
Definition at line 400 of file proxy_pool.c.
References brix_proxy_pool_mutex, brix_proxy_be_table_t::capacity, brix_proxy_be_entry_t::id, brix_proxy_be_entry_t::in_flight, brix_proxy_be_entry_t::in_use, pool_table(), and brix_proxy_be_table_t::slots.
Referenced by webdav_proxy_finalize_request(), and webdav_proxy_handler().
brix_proxy_pool_drain()
int brix_proxy_pool_drain (uint32_t id)
Definition at line 288 of file proxy_pool.c.
References BRIX_PROXY_BE_DRAINING, and proxy_pool_set_state().
Referenced by admin_proxy_one().
brix_proxy_pool_in_flight()
long brix_proxy_pool_in_flight (uint32_t id)
Definition at line 303 of file proxy_pool.c.
References brix_proxy_pool_mutex, brix_proxy_be_table_t::capacity, brix_proxy_be_entry_t::id, brix_proxy_be_entry_t::in_flight, brix_proxy_be_entry_t::in_use, pool_table(), and brix_proxy_be_table_t::slots.
Referenced by admin_proxy_one().
brix_proxy_pool_init_zone()
static ngx_int_t brix_proxy_pool_init_zone (ngx_shm_zone_t * shm_zone, void * data) static
Definition at line 49 of file proxy_pool.c.
References brix_proxy_pool_mutex, BRIX_PROXY_POOL_SLOTS, brix_shm_table_alloc(), brix_proxy_be_table_t::capacity, and brix_proxy_be_table_t::next_id.
Referenced by brix_proxy_pool_configure().
brix_proxy_pool_remove()
int brix_proxy_pool_remove (uint32_t id)
Definition at line 280 of file proxy_pool.c.
References BRIX_PROXY_BE_ACTIVE, and proxy_pool_set_state().
Referenced by admin_proxy_one().
brix_proxy_pool_select()
ngx_int_t brix_proxy_pool_select (brix_proxy_be_pick_t * out)
Definition at line 335 of file proxy_pool.c.
References BRIX_PROXY_BE_ACTIVE, brix_proxy_pool_mutex, brix_proxy_be_table_t::capacity, brix_proxy_be_entry_t::host, brix_proxy_be_pick_t::host, brix_proxy_be_entry_t::id, brix_proxy_be_pick_t::id, brix_proxy_be_entry_t::in_flight, brix_proxy_be_entry_t::in_use, ngx_memcpy, pool_table(), brix_proxy_be_entry_t::port, brix_proxy_be_pick_t::port, brix_proxy_be_table_t::rr_index, brix_proxy_be_table_t::slots, brix_proxy_be_entry_t::sockaddr, brix_proxy_be_pick_t::sockaddr, brix_proxy_be_entry_t::socklen, brix_proxy_be_pick_t::socklen, brix_proxy_be_entry_t::ssl, brix_proxy_be_pick_t::ssl, brix_proxy_be_entry_t::state, brix_proxy_be_entry_t::url_base, brix_proxy_be_pick_t::url_base, and brix_proxy_be_entry_t::weight.
Referenced by webdav_proxy_handler().
brix_proxy_pool_snapshot()
ngx_uint_t brix_proxy_pool_snapshot (brix_proxy_be_snapshot_t * out, ngx_uint_t max)
Definition at line 429 of file proxy_pool.c.
References brix_proxy_be_entry_t::added_at, brix_proxy_be_snapshot_t::added_at, brix_proxy_pool_mutex, brix_proxy_be_table_t::capacity, brix_proxy_be_entry_t::host, brix_proxy_be_snapshot_t::host, brix_proxy_be_entry_t::id, brix_proxy_be_snapshot_t::id, brix_proxy_be_entry_t::in_flight, brix_proxy_be_snapshot_t::in_flight, brix_proxy_be_entry_t::in_use, ngx_memcpy, pool_table(), brix_proxy_be_entry_t::port, brix_proxy_be_snapshot_t::port, brix_proxy_be_table_t::slots, brix_proxy_be_entry_t::ssl, brix_proxy_be_snapshot_t::ssl, brix_proxy_be_entry_t::state, brix_proxy_be_snapshot_t::state, brix_proxy_be_entry_t::weight, and brix_proxy_be_snapshot_t::weight.
Referenced by admin_proxy_list().
brix_proxy_pool_undrain()
int brix_proxy_pool_undrain (uint32_t id)
Definition at line 295 of file proxy_pool.c.
References BRIX_PROXY_BE_ACTIVE, and proxy_pool_set_state().
Referenced by admin_proxy_one().
pool_table()
static brix_proxy_be_table_t * pool_table (void) static
Definition at line 27 of file proxy_pool.c.
References brix_proxy_pool_zone.
Referenced by brix_proxy_pool_add(), brix_proxy_pool_dec_in_flight(), brix_proxy_pool_in_flight(), brix_proxy_pool_select(), brix_proxy_pool_snapshot(), and proxy_pool_set_state().
proxy_pool_resolve()
static ngx_int_t proxy_pool_resolve (const char * url, ngx_pool_t * pool, ngx_log_t * log, brix_proxy_be_entry_t * out) static
Definition at line 113 of file proxy_pool.c.
References brix_format_host(), brix_format_host_port(), brix_proxy_be_entry_t::host, log, ngx_memcpy, brix_proxy_be_entry_t::port, brix_proxy_be_entry_t::sockaddr, brix_proxy_be_entry_t::socklen, brix_proxy_be_entry_t::ssl, and brix_proxy_be_entry_t::url_base.
Referenced by brix_proxy_pool_add().
proxy_pool_set_state()
static int proxy_pool_set_state (uint32_t id, int remove_it, brix_proxy_be_state_e state) static
Definition at line 247 of file proxy_pool.c.
References BRIX_PROXY_BE_DRAINING, brix_proxy_pool_mutex, brix_proxy_be_table_t::capacity, brix_proxy_be_entry_t::drained_at, brix_proxy_be_entry_t::id, brix_proxy_be_entry_t::in_use, pool_table(), brix_proxy_be_table_t::slots, and brix_proxy_be_entry_t::state.
Referenced by brix_proxy_pool_drain(), brix_proxy_pool_remove(), and brix_proxy_pool_undrain().
Variable Documentation
brix_proxy_pool_mutex
ngx_shmtx_t brix_proxy_pool_mutex static
Definition at line 16 of file proxy_pool.c.
Referenced by brix_proxy_pool_add(), brix_proxy_pool_dec_in_flight(), brix_proxy_pool_in_flight(), brix_proxy_pool_init_zone(), brix_proxy_pool_select(), brix_proxy_pool_snapshot(), and proxy_pool_set_state().
brix_proxy_pool_zone
ngx_shm_zone_t* brix_proxy_pool_zone static
Definition at line 15 of file proxy_pool.c.
Referenced by brix_proxy_pool_configure(), and pool_table().
ngx_http_brix_webdav_module
ngx_module_t ngx_http_brix_webdav_module extern
Definition at line 10 of file module.c.
Referenced by brix_proxy_pool_configure().