nginx-xrootd: src/auth/gsi/proxy_req_assemble.c File Reference
proxy_req_assemble.c File Reference
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <openssl/x509.h>
#include <openssl/pem.h>
#include <openssl/evp.h>
#include <openssl/crypto.h>
#include "proxy_req_internal.h"
Data Structures
struct asm_args
Functions
static int asm_check_key_match (const asm_args *a, EVP_PKEY *reqkey)
static uint8_t * asm_export_key (const asm_args *a, EVP_PKEY *reqkey, size_t *len)
static int asm_concat_pem (const asm_args *a, uint8_t **out_pem, size_t *out_len)
int brix_gsi_assemble_proxy (const brix_gsi_blob_t *proxy_pem, EVP_PKEY *reqkey, const brix_gsi_blob_t *chain_pem, brix_gsi_buf_t *out_pem, const brix_gsi_err_t *err)
Function Documentation
asm_check_key_match()
static int asm_check_key_match (const asm_args * a, EVP_PKEY * reqkey) static
Definition at line 55 of file proxy_req_assemble.c.
References asm_args::err, asm_args::errcap, asm_args::proxy_pem, and asm_args::proxy_pem_len.
Referenced by brix_gsi_assemble_proxy().
asm_concat_pem()
static int asm_concat_pem (const asm_args * a, uint8_t ** out_pem, size_t * out_len) static
Definition at line 124 of file proxy_req_assemble.c.
References brix_size_add(), asm_args::chain_pem, asm_args::chain_pem_len, asm_args::err, asm_args::errcap, asm_args::key_pem, asm_args::key_pem_len, asm_args::proxy_pem, and asm_args::proxy_pem_len.
Referenced by brix_gsi_assemble_proxy().
asm_export_key()
static uint8_t * asm_export_key (const asm_args * a, EVP_PKEY * reqkey, size_t * len) static
Definition at line 88 of file proxy_req_assemble.c.
References asm_args::err, and asm_args::errcap.
Referenced by brix_gsi_assemble_proxy().
brix_gsi_assemble_proxy()
int brix_gsi_assemble_proxy (const brix_gsi_blob_t * proxy_pem, EVP_PKEY * reqkey, const brix_gsi_blob_t * chain_pem, brix_gsi_buf_t * out_pem, const brix_gsi_err_t * err)
Definition at line 152 of file proxy_req_assemble.c.
References asm_check_key_match(), asm_concat_pem(), asm_export_key(), brix_gsi_err_t::buf, brix_gsi_err_t::cap, asm_args::chain_pem, asm_args::chain_pem_len, brix_gsi_blob_t::data, brix_gsi_buf_t::data, asm_args::err, asm_args::errcap, asm_args::key_pem, asm_args::key_pem_len, brix_gsi_blob_t::len, brix_gsi_buf_t::len, asm_args::proxy_pem, and asm_args::proxy_pem_len.
Referenced by brix_gsi_handle_sigpxy(), delegation_put_assemble(), gss_recv_signed(), and test_assemble_proxy().