nginx-xrootd: src/net/proxy/proxy.h File Reference
proxy.h File Reference
#include "core/ngx_brix_module.h"
Functions
ngx_int_t brix_proxy_dispatch (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
char * brix_conf_set_proxy_upstream (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_proxy_auth (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_proxy_login_user (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_conf_set_proxy_path_rewrite (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
void brix_proxy_cleanup (brix_proxy_ctx_t *proxy)
Function Documentation
brix_conf_set_proxy_auth()
char * brix_conf_set_proxy_auth (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 242 of file directives.c.
References BRIX_PROXY_AUTH_ANONYMOUS, BRIX_PROXY_AUTH_FORWARD, BRIX_PROXY_AUTH_GSI, and BRIX_PROXY_AUTH_SSS.
brix_conf_set_proxy_login_user()
char * brix_conf_set_proxy_login_user (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 281 of file directives.c.
References BRIX_PROXY_LOGIN_ANONYMOUS, BRIX_PROXY_LOGIN_FIXED, BRIX_PROXY_LOGIN_PASSTHROUGH, and ngx_memcpy.
brix_conf_set_proxy_path_rewrite()
char * brix_conf_set_proxy_path_rewrite (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 328 of file directives.c.
brix_conf_set_proxy_upstream()
char * brix_conf_set_proxy_upstream (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 173 of file directives.c.
References brix_proxy_upstream_t::auth, brix_pstrdup_z(), host, brix_proxy_upstream_t::host, port, brix_proxy_upstream_t::port, proxy_parse_host_port(), proxy_parse_upstream_auth(), and brix_proxy_upstream_t::sss_keyname.
brix_proxy_cleanup()
void brix_proxy_cleanup (brix_proxy_ctx_t * proxy)
Definition at line 332 of file connect_lifecycle.c.
References brix_proxy_cleanup_audit_handles(), brix_proxy_cleanup_conn(), brix_proxy_cleanup_free_buffers(), brix_proxy_cleanup_redirect(), brix_proxy_cleanup_splice(), and brix_proxy_cleanup_timers().
Referenced by brix_on_disconnect(), brix_proxy_abort(), brix_proxy_read_handler(), brix_proxy_wait_handler(), brix_proxy_write_handler(), and pc_arm_events().
brix_proxy_dispatch()
ngx_int_t brix_proxy_dispatch (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 199 of file forward_relay_dispatch.c.
References BRIX_MAX_FILES, brix_proxy_alloc_local_fh(), brix_proxy_connect(), BRIX_PROXY_FH_FREE, brix_proxy_forward_request(), BRIX_PROXY_MAX_CONN_FAILS, brix_proxy_tap_init(), brix_send_error(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, brix_ctx_recv_t::hdr_buf, kXR_IOError, kXR_open, ngx_memcpy, ngx_pcalloc(), brix_ctx_recv_t::payload, brix_ctx_t::proxy, brix_ctx_t::proxy_fail_count, brix_ctx_t::recv, brix_ctx_t::state, XRD_PX_IDLE, XRD_REQUEST_HDR_LEN, and XRD_ST_PROXY.
Referenced by brix_dispatch().