nginx-xrootd: src/auth/gsi/proxy_req_sign.c File Reference
proxy_req_sign.c File Reference
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/pem.h>
#include <openssl/evp.h>
#include <openssl/objects.h>
#include <openssl/asn1.h>
#include "proxy_req_internal.h"
Data Structures
struct sgn_ctx
Functions
static int pxr_req_pathlen (X509_REQ *req)
static int sgn_fail (sgn_ctx *x, const char *msg)
static int sgn_copy_signer_exts (X509 *signer, X509 *proxy, int *indepth, int *haskeyusage)
static int sgn_parse_inputs (sgn_ctx *x, const uint8_t *signer_pem, size_t signer_pem_len, const uint8_t *req_der, size_t req_len)
static int sgn_check_subject (sgn_ctx *x, long *serial)
static int sgn_check_signer_validity (sgn_ctx *x, int *timeleft)
static int sgn_verify_req_signature (sgn_ctx *x)
static int sgn_populate_proxy (sgn_ctx *x, long serial, int timeleft)
static int sgn_add_extensions (sgn_ctx *x)
static int sgn_export_pem (sgn_ctx *x, uint8_t **proxy_pem, size_t *proxy_len)
static int sgn_args_ok (const brix_gsi_blob_t *signer_pem, EVP_PKEY *signer_key, const brix_gsi_blob_t *req_der, const brix_gsi_buf_t *proxy_pem)
int brix_gsi_sign_pxyreq (const brix_gsi_blob_t *signer_pem, EVP_PKEY *signer_key, const brix_gsi_blob_t *req_der, brix_gsi_buf_t *proxy_pem, const brix_gsi_err_t *err)
Function Documentation
brix_gsi_sign_pxyreq()
int brix_gsi_sign_pxyreq (const brix_gsi_blob_t * signer_pem, EVP_PKEY * signer_key, const brix_gsi_blob_t * req_der, brix_gsi_buf_t * proxy_pem, const brix_gsi_err_t * err)
Definition at line 317 of file proxy_req_sign.c.
References brix_gsi_err_t::buf, brix_gsi_err_t::cap, brix_gsi_blob_t::data, brix_gsi_buf_t::data, sgn_ctx::err, sgn_ctx::errcap, brix_gsi_blob_t::len, brix_gsi_buf_t::len, sgn_ctx::proxy, sgn_add_extensions(), sgn_args_ok(), sgn_check_signer_validity(), sgn_check_subject(), sgn_export_pem(), sgn_fail(), sgn_parse_inputs(), sgn_populate_proxy(), and sgn_verify_req_signature().
Referenced by gsi_sigpxy(), test_negatives(), test_sign_pxyreq(), and test_two_level_delegation().
pxr_req_pathlen()
static int pxr_req_pathlen (X509_REQ * req) static
Definition at line 42 of file proxy_req_sign.c.
References GSI_PROXYCERTINFO_OID, and STACK_OF().
Referenced by sgn_add_extensions().
sgn_add_extensions()
static int sgn_add_extensions (sgn_ctx * x) static
Definition at line 260 of file proxy_req_sign.c.
References sgn_ctx::pciext, sgn_ctx::proxy, pxr_make_pci_ext(), pxr_req_pathlen(), sgn_ctx::req, sgn_copy_signer_exts(), sgn_fail(), and sgn_ctx::signer.
Referenced by brix_gsi_sign_pxyreq().
sgn_args_ok()
static int sgn_args_ok (const brix_gsi_blob_t * signer_pem, EVP_PKEY * signer_key, const brix_gsi_blob_t * req_der, const brix_gsi_buf_t * proxy_pem) static
Definition at line 308 of file proxy_req_sign.c.
References brix_gsi_blob_t::data.
Referenced by brix_gsi_sign_pxyreq().
sgn_check_signer_validity()
static int sgn_check_signer_validity (sgn_ctx * x, int * timeleft) static
Definition at line 206 of file proxy_req_sign.c.
References sgn_fail(), and sgn_ctx::signer.
Referenced by brix_gsi_sign_pxyreq().
sgn_check_subject()
static int sgn_check_subject (sgn_ctx * x, long * serial) static
Definition at line 178 of file proxy_req_sign.c.
References sgn_ctx::req, sgn_fail(), and sgn_ctx::signer.
Referenced by brix_gsi_sign_pxyreq().
sgn_copy_signer_exts()
static int sgn_copy_signer_exts (X509 * signer, X509 * proxy, int * indepth, int * haskeyusage) static
Definition at line 112 of file proxy_req_sign.c.
References GSI_KEY_USAGE_OID, GSI_PROXYCERTINFO_OID, GSI_PROXYCERTINFO_OLD_OID, and GSI_SUBJ_ALT_NAME_OID.
Referenced by sgn_add_extensions().
sgn_export_pem()
static int sgn_export_pem (sgn_ctx * x, uint8_t ** proxy_pem, size_t * proxy_len) static
Definition at line 285 of file proxy_req_sign.c.
References sgn_ctx::obio, sgn_ctx::proxy, and sgn_fail().
Referenced by brix_gsi_sign_pxyreq().
sgn_fail()
static int sgn_fail (sgn_ctx * x, const char * msg) static
Definition at line 94 of file proxy_req_sign.c.
References sgn_ctx::err, sgn_ctx::errcap, sgn_ctx::obio, sgn_ctx::pciext, sgn_ctx::proxy, sgn_ctx::req, sgn_ctx::reqpub, sgn_ctx::sbio, and sgn_ctx::signer.
Referenced by brix_gsi_sign_pxyreq(), sgn_add_extensions(), sgn_check_signer_validity(), sgn_check_subject(), sgn_export_pem(), sgn_parse_inputs(), sgn_populate_proxy(), and sgn_verify_req_signature().
sgn_parse_inputs()
static int sgn_parse_inputs (sgn_ctx * x, const uint8_t * signer_pem, size_t signer_pem_len, const uint8_t * req_der, size_t req_len) static
Definition at line 157 of file proxy_req_sign.c.
References sgn_ctx::req, sgn_ctx::sbio, sgn_fail(), and sgn_ctx::signer.
Referenced by brix_gsi_sign_pxyreq().
sgn_populate_proxy()
static int sgn_populate_proxy (sgn_ctx * x, long serial, int timeleft) static
Definition at line 237 of file proxy_req_sign.c.
References sgn_ctx::proxy, sgn_ctx::req, sgn_ctx::reqpub, sgn_fail(), and sgn_ctx::signer.
Referenced by brix_gsi_sign_pxyreq().
sgn_verify_req_signature()
static int sgn_verify_req_signature (sgn_ctx * x) static
Definition at line 224 of file proxy_req_sign.c.
References sgn_ctx::req, sgn_ctx::reqpub, and sgn_fail().
Referenced by brix_gsi_sign_pxyreq().