nginx-xrootd: src/protocols/webdav/proxy_request.c File Reference
proxy_request.c File Reference
#include "proxy_internal.h"
Data Structures
struct wpr_ctx_t
Functions
static ngx_str_t webdav_proxy_rewrite_destination (ngx_pool_t *pool, ngx_str_t *dest, ngx_str_t *upstream_url_base)
static int wpr_is_hop_by_hop (ngx_str_t *key, int drop_content_length)
static void wpr_build_url (ngx_http_request_t *r, wpr_ctx_t *wc)
static size_t wpr_size_auth (ngx_http_request_t *r, const wpr_ctx_t *wc)
static size_t wpr_size_request (ngx_http_request_t *r, const wpr_ctx_t *wc)
static u_char * wpr_emit_auth (ngx_http_request_t *r, const wpr_ctx_t *wc, u_char *p)
static u_char * wpr_emit_client_headers (ngx_http_request_t *r, const wpr_ctx_t *wc, u_char *p)
static void wpr_fill_request (ngx_http_request_t *r, const wpr_ctx_t *wc, ngx_buf_t *b)
static ngx_int_t wpr_attach_body (ngx_http_request_t *r, ngx_buf_t *b)
ngx_int_t webdav_proxy_create_request (ngx_http_request_t *r)
Function Documentation
webdav_proxy_create_request()
ngx_int_t webdav_proxy_create_request (ngx_http_request_t * r)
Definition at line 444 of file proxy_request.c.
References wpr_attach_body(), wpr_build_url(), wpr_fill_request(), and wpr_size_request().
Referenced by webdav_proxy_handler().
webdav_proxy_rewrite_destination()
static ngx_str_t webdav_proxy_rewrite_destination (ngx_pool_t * pool, ngx_str_t * dest, ngx_str_t * upstream_url_base) static
Definition at line 14 of file proxy_request.c.
References ngx_pnalloc().
Referenced by wpr_emit_client_headers().
wpr_attach_body()
static ngx_int_t wpr_attach_body (ngx_http_request_t * r, ngx_buf_t * b) static
Definition at line 407 of file proxy_request.c.
Referenced by webdav_proxy_create_request().
wpr_build_url()
static void wpr_build_url (ngx_http_request_t * r, wpr_ctx_t * wc) static
Definition at line 135 of file proxy_request.c.
References wpr_ctx_t::conf, brix_webdav_backend_t::host, wpr_ctx_t::host, ngx_http_brix_webdav_module, webdav_proxy_ctx_t::selected_backend, ngx_http_brix_webdav_loc_conf_t::upstream_host, ngx_http_brix_webdav_loc_conf_t::upstream_url_base, brix_webdav_backend_t::url_base, and wpr_ctx_t::url_base.
Referenced by webdav_proxy_create_request().
wpr_emit_auth()
static u_char * wpr_emit_auth (ngx_http_request_t * r, const wpr_ctx_t * wc, u_char * p) static
Definition at line 264 of file proxy_request.c.
References wpr_ctx_t::conf, ngx_http_brix_webdav_loc_conf_t::upstream_auth, ngx_http_brix_webdav_loc_conf_t::upstream_auth_token, WEBDAV_PROXY_AUTH_FORWARD, and WEBDAV_PROXY_AUTH_TOKEN.
Referenced by wpr_fill_request().
wpr_emit_client_headers()
static u_char * wpr_emit_client_headers (ngx_http_request_t * r, const wpr_ctx_t * wc, u_char * p) static
Definition at line 299 of file proxy_request.c.
References key, wpr_ctx_t::url_base, webdav_proxy_rewrite_destination(), and wpr_is_hop_by_hop().
Referenced by wpr_fill_request().
wpr_fill_request()
static void wpr_fill_request (ngx_http_request_t * r, const wpr_ctx_t * wc, ngx_buf_t * b) static
Definition at line 353 of file proxy_request.c.
References wpr_ctx_t::host, wpr_emit_auth(), and wpr_emit_client_headers().
Referenced by webdav_proxy_create_request().
wpr_is_hop_by_hop()
static int wpr_is_hop_by_hop (ngx_str_t * key, int drop_content_length) static
Definition at line 99 of file proxy_request.c.
References key.
Referenced by wpr_emit_client_headers(), and wpr_size_request().
wpr_size_auth()
static size_t wpr_size_auth (ngx_http_request_t * r, const wpr_ctx_t * wc) static
Definition at line 164 of file proxy_request.c.
References wpr_ctx_t::conf, ngx_http_brix_webdav_loc_conf_t::upstream_auth, ngx_http_brix_webdav_loc_conf_t::upstream_auth_token, WEBDAV_PROXY_AUTH_FORWARD, and WEBDAV_PROXY_AUTH_TOKEN.
Referenced by wpr_size_request().
wpr_size_request()
static size_t wpr_size_request (ngx_http_request_t * r, const wpr_ctx_t * wc) static
Definition at line 195 of file proxy_request.c.
References wpr_ctx_t::host, key, wpr_ctx_t::url_base, wpr_is_hop_by_hop(), and wpr_size_auth().
Referenced by webdav_proxy_create_request().