nginx-xrootd: src/protocols/webdav/proxy_pool.h File Reference
proxy_pool.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
Data Structures
struct brix_proxy_be_entry_t
struct brix_proxy_be_table_t
struct brix_proxy_be_snapshot_t
struct brix_proxy_be_pick_t
Macros
#define BRIX_PROXY_POOL_SLOTS 32
Enumerations
enum brix_proxy_be_state_e { BRIX_PROXY_BE_ACTIVE = 0 , BRIX_PROXY_BE_DRAINING , BRIX_PROXY_BE_DEAD }
Functions
ngx_int_t brix_proxy_pool_configure (ngx_conf_t *cf)
ngx_int_t brix_proxy_pool_add (const char *url, ngx_uint_t weight, ngx_pool_t *pool, ngx_log_t *log, uint32_t *id_out)
int brix_proxy_pool_remove (uint32_t id)
int brix_proxy_pool_drain (uint32_t id)
int brix_proxy_pool_undrain (uint32_t id)
long brix_proxy_pool_in_flight (uint32_t id)
ngx_int_t brix_proxy_pool_select (brix_proxy_be_pick_t *out)
void brix_proxy_pool_dec_in_flight (uint32_t id)
ngx_uint_t brix_proxy_pool_snapshot (brix_proxy_be_snapshot_t *out, ngx_uint_t max)
Macro Definition Documentation
BRIX_PROXY_POOL_SLOTS
#define BRIX_PROXY_POOL_SLOTS 32
Definition at line 21 of file proxy_pool.h.
Enumeration Type Documentation
brix_proxy_be_state_e
enum brix_proxy_be_state_e
Enumerator
BRIX_PROXY_BE_ACTIVE
BRIX_PROXY_BE_DRAINING
BRIX_PROXY_BE_DEAD
Definition at line 23 of file proxy_pool.h.
Function Documentation
brix_proxy_pool_add()
ngx_int_t brix_proxy_pool_add (const char * url, ngx_uint_t weight, ngx_pool_t * pool, ngx_log_t * log, uint32_t * id_out)
Definition at line 187 of file proxy_pool.c.
References brix_proxy_be_entry_t::added_at, BRIX_PROXY_BE_ACTIVE, brix_proxy_pool_mutex, brix_proxy_be_table_t::capacity, brix_proxy_be_entry_t::drained_at, brix_proxy_be_entry_t::host, brix_proxy_be_entry_t::id, brix_proxy_be_entry_t::in_flight, brix_proxy_be_entry_t::in_use, log, brix_proxy_be_table_t::next_id, ngx_memcpy, pool_table(), brix_proxy_be_entry_t::port, proxy_pool_resolve(), brix_proxy_be_table_t::slots, brix_proxy_be_entry_t::sockaddr, brix_proxy_be_entry_t::socklen, brix_proxy_be_entry_t::ssl, brix_proxy_be_entry_t::state, brix_proxy_be_entry_t::url_base, and brix_proxy_be_entry_t::weight.
Referenced by admin_proxy_add().
brix_proxy_pool_configure()
ngx_int_t brix_proxy_pool_configure (ngx_conf_t * cf)
Definition at line 79 of file proxy_pool.c.
References brix_proxy_pool_init_zone(), BRIX_PROXY_POOL_SLOTS, brix_proxy_pool_zone, brix_shm_zone_size(), name, and ngx_http_brix_webdav_module.
brix_proxy_pool_dec_in_flight()
void brix_proxy_pool_dec_in_flight (uint32_t id)
Definition at line 400 of file proxy_pool.c.
References brix_proxy_pool_mutex, brix_proxy_be_table_t::capacity, brix_proxy_be_entry_t::id, brix_proxy_be_entry_t::in_flight, brix_proxy_be_entry_t::in_use, pool_table(), and brix_proxy_be_table_t::slots.
brix_proxy_pool_drain()
int brix_proxy_pool_drain (uint32_t id)
Definition at line 288 of file proxy_pool.c.
References BRIX_PROXY_BE_DRAINING, and proxy_pool_set_state().
Referenced by admin_proxy_one().
brix_proxy_pool_in_flight()
long brix_proxy_pool_in_flight (uint32_t id)
Definition at line 303 of file proxy_pool.c.
References brix_proxy_pool_mutex, brix_proxy_be_table_t::capacity, brix_proxy_be_entry_t::id, brix_proxy_be_entry_t::in_flight, brix_proxy_be_entry_t::in_use, pool_table(), and brix_proxy_be_table_t::slots.
Referenced by admin_proxy_one().
brix_proxy_pool_remove()
int brix_proxy_pool_remove (uint32_t id)
Definition at line 280 of file proxy_pool.c.
References BRIX_PROXY_BE_ACTIVE, and proxy_pool_set_state().
Referenced by admin_proxy_one().
brix_proxy_pool_select()
ngx_int_t brix_proxy_pool_select (brix_proxy_be_pick_t * out)
Definition at line 335 of file proxy_pool.c.
References BRIX_PROXY_BE_ACTIVE, brix_proxy_pool_mutex, brix_proxy_be_table_t::capacity, brix_proxy_be_entry_t::host, brix_proxy_be_pick_t::host, brix_proxy_be_entry_t::id, brix_proxy_be_pick_t::id, brix_proxy_be_entry_t::in_flight, brix_proxy_be_entry_t::in_use, ngx_memcpy, pool_table(), brix_proxy_be_entry_t::port, brix_proxy_be_pick_t::port, brix_proxy_be_table_t::rr_index, brix_proxy_be_table_t::slots, brix_proxy_be_entry_t::sockaddr, brix_proxy_be_pick_t::sockaddr, brix_proxy_be_entry_t::socklen, brix_proxy_be_pick_t::socklen, brix_proxy_be_entry_t::ssl, brix_proxy_be_pick_t::ssl, brix_proxy_be_entry_t::state, brix_proxy_be_entry_t::url_base, brix_proxy_be_pick_t::url_base, and brix_proxy_be_entry_t::weight.
brix_proxy_pool_snapshot()
ngx_uint_t brix_proxy_pool_snapshot (brix_proxy_be_snapshot_t * out, ngx_uint_t max)
Definition at line 429 of file proxy_pool.c.
References brix_proxy_be_entry_t::added_at, brix_proxy_be_snapshot_t::added_at, brix_proxy_pool_mutex, brix_proxy_be_table_t::capacity, host, brix_proxy_be_entry_t::host, brix_proxy_be_snapshot_t::host, brix_proxy_be_entry_t::id, brix_proxy_be_snapshot_t::id, brix_proxy_be_entry_t::in_flight, brix_proxy_be_snapshot_t::in_flight, brix_proxy_be_entry_t::in_use, ngx_memcpy, pool_table(), brix_proxy_be_entry_t::port, brix_proxy_be_snapshot_t::port, brix_proxy_be_table_t::slots, brix_proxy_be_entry_t::ssl, brix_proxy_be_snapshot_t::ssl, brix_proxy_be_entry_t::state, brix_proxy_be_snapshot_t::state, brix_proxy_be_entry_t::weight, and brix_proxy_be_snapshot_t::weight.
Referenced by admin_proxy_list().
brix_proxy_pool_undrain()
int brix_proxy_pool_undrain (uint32_t id)
Definition at line 295 of file proxy_pool.c.
References BRIX_PROXY_BE_ACTIVE, and proxy_pool_set_state().
Referenced by admin_proxy_one().