nginx-xrootd: src/auth/gsi/proxy_req_internal.h File Reference
proxy_req_internal.h File Reference
#include "proxy_req.h"
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/objects.h>
#include <openssl/asn1.h>
#include "core/compat/safe_size.h"
Macros
#define GSI_PROXYCERTINFO_OID "1.3.6.1.5.5.7.1.14"
#define GSI_PROXYCERTINFO_OLD_OID "1.3.6.1.4.1.3536.1.222"
#define GSI_PROXYPOLICY_IMPERSONATION "1.3.6.1.5.5.7.21.1"
#define GSI_KEY_USAGE_OID "2.5.29.15"
#define GSI_SUBJ_ALT_NAME_OID "2.5.29.17"
#define GSI_MIN_RSA_BITS 2048
Functions
X509_EXTENSION * pxr_make_pci_ext (int parent_pathlen)
Macro Definition Documentation
GSI_KEY_USAGE_OID
#define GSI_KEY_USAGE_OID "2.5.29.15"
Definition at line 63 of file proxy_req_internal.h.
GSI_MIN_RSA_BITS
#define GSI_MIN_RSA_BITS 2048
Definition at line 65 of file proxy_req_internal.h.
GSI_PROXYCERTINFO_OID
#define GSI_PROXYCERTINFO_OID "1.3.6.1.5.5.7.1.14"
Definition at line 60 of file proxy_req_internal.h.
GSI_PROXYCERTINFO_OLD_OID
#define GSI_PROXYCERTINFO_OLD_OID "1.3.6.1.4.1.3536.1.222"
Definition at line 61 of file proxy_req_internal.h.
GSI_PROXYPOLICY_IMPERSONATION
#define GSI_PROXYPOLICY_IMPERSONATION "1.3.6.1.5.5.7.21.1"
Definition at line 62 of file proxy_req_internal.h.
GSI_SUBJ_ALT_NAME_OID
#define GSI_SUBJ_ALT_NAME_OID "2.5.29.17"
Definition at line 64 of file proxy_req_internal.h.
Function Documentation
pxr_make_pci_ext()
X509_EXTENSION * pxr_make_pci_ext (int parent_pathlen)
Definition at line 239 of file proxy_req.c.
References pxr_pci_encode_der(), and pxr_pci_ext_from_der().
Referenced by pxr_build_extstack(), and sgn_add_extensions().