nginx-xrootd: src/auth/gsi/proxy_req.c File Reference
proxy_req.c File Reference
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/pem.h>
#include <openssl/evp.h>
#include <openssl/rsa.h>
#include <openssl/rand.h>
#include <openssl/bn.h>
#include <openssl/objects.h>
#include <openssl/asn1.h>
#include "proxy_req.h"
#include "core/compat/safe_size.h"
Data Structures
struct pxr_ctx
struct sgn_ctx
Macros
#define GSI_PROXYCERTINFO_OID "1.3.6.1.5.5.7.1.14"
#define GSI_PROXYCERTINFO_OLD_OID "1.3.6.1.4.1.3536.1.222"
#define GSI_PROXYPOLICY_IMPERSONATION "1.3.6.1.5.5.7.21.1"
#define GSI_KEY_USAGE_OID "2.5.29.15"
#define GSI_SUBJ_ALT_NAME_OID "2.5.29.17"
#define GSI_MIN_RSA_BITS 2048
Functions
static int pxr_fail (pxr_ctx *x, char *err, size_t cap, const char *msg)
static int pxr_parent_pathlen (X509 *parent)
static int pxr_copy_parent_exts (X509 *parent, STACK_OF(X509_EXTENSION) *dst)
static EVP_PKEY * pxr_keygen (X509 *parent)
static X509_EXTENSION * pxr_make_pci_ext (int parent_pathlen)
int brix_gsi_build_pxyreq (const uint8_t *parent_pem, size_t parent_pem_len, EVP_PKEY **newkey, uint8_t **req_der, size_t *req_len, char *err, size_t errcap)
static int pxr_req_pathlen (X509_REQ *req)
static int sgn_fail (sgn_ctx *x, char *err, size_t cap, const char *msg)
static int sgn_copy_signer_exts (X509 *signer, X509 *proxy, int *indepth, int *haskeyusage)
int brix_gsi_sign_pxyreq (const uint8_t *signer_pem, size_t signer_pem_len, EVP_PKEY *signer_key, const uint8_t *req_der, size_t req_len, uint8_t **proxy_pem, size_t *proxy_len, char *err, size_t errcap)
int brix_gsi_assemble_proxy (const uint8_t *proxy_pem, size_t proxy_pem_len, EVP_PKEY *reqkey, const uint8_t *chain_pem, size_t chain_pem_len, uint8_t **out_pem, size_t *out_len, char *err, size_t errcap)
Macro Definition Documentation
GSI_KEY_USAGE_OID
#define GSI_KEY_USAGE_OID "2.5.29.15"
Definition at line 65 of file proxy_req.c.
GSI_MIN_RSA_BITS
#define GSI_MIN_RSA_BITS 2048
Definition at line 67 of file proxy_req.c.
GSI_PROXYCERTINFO_OID
#define GSI_PROXYCERTINFO_OID "1.3.6.1.5.5.7.1.14"
Definition at line 62 of file proxy_req.c.
GSI_PROXYCERTINFO_OLD_OID
#define GSI_PROXYCERTINFO_OLD_OID "1.3.6.1.4.1.3536.1.222"
Definition at line 63 of file proxy_req.c.
GSI_PROXYPOLICY_IMPERSONATION
#define GSI_PROXYPOLICY_IMPERSONATION "1.3.6.1.5.5.7.21.1"
Definition at line 64 of file proxy_req.c.
GSI_SUBJ_ALT_NAME_OID
#define GSI_SUBJ_ALT_NAME_OID "2.5.29.17"
Definition at line 66 of file proxy_req.c.
Function Documentation
brix_gsi_assemble_proxy()
int brix_gsi_assemble_proxy (const uint8_t * proxy_pem, size_t proxy_pem_len, EVP_PKEY * reqkey, const uint8_t * chain_pem, size_t chain_pem_len, uint8_t ** out_pem, size_t * out_len, char * err, size_t errcap)
Definition at line 570 of file proxy_req.c.
References brix_size_add().
Referenced by brix_gsi_handle_sigpxy(), and main().
brix_gsi_build_pxyreq()
int brix_gsi_build_pxyreq (const uint8_t * parent_pem, size_t parent_pem_len, EVP_PKEY ** newkey, uint8_t ** req_der, size_t * req_len, char * err, size_t errcap)
Definition at line 253 of file proxy_req.c.
References pxr_ctx::key, pxr_ctx::parent, pxr_ctx::pbio, pxr_copy_parent_exts(), pxr_fail(), pxr_keygen(), pxr_make_pci_ext(), pxr_parent_pathlen(), and pxr_ctx::subj.
Referenced by brix_gsi_begin_delegation(), and main().
brix_gsi_sign_pxyreq()
int brix_gsi_sign_pxyreq (const uint8_t * signer_pem, size_t signer_pem_len, EVP_PKEY * signer_key, const uint8_t * req_der, size_t req_len, uint8_t ** proxy_pem, size_t * proxy_len, char * err, size_t errcap)
Definition at line 448 of file proxy_req.c.
References sgn_ctx::obio, sgn_ctx::pciext, sgn_ctx::proxy, pxr_make_pci_ext(), pxr_req_pathlen(), sgn_ctx::req, sgn_ctx::reqpub, sgn_ctx::sbio, sgn_copy_signer_exts(), sgn_fail(), and sgn_ctx::signer.
Referenced by gsi_sigpxy(), and main().
pxr_copy_parent_exts()
static int pxr_copy_parent_exts (X509 * parent, STACK_OF(X509_EXTENSION) * dst) static
Definition at line 137 of file proxy_req.c.
References GSI_PROXYCERTINFO_OID, GSI_PROXYCERTINFO_OLD_OID, and GSI_SUBJ_ALT_NAME_OID.
Referenced by brix_gsi_build_pxyreq().
pxr_fail()
static int pxr_fail (pxr_ctx * x, char * err, size_t cap, const char * msg) static
Definition at line 82 of file proxy_req.c.
References pxr_ctx::key, pxr_ctx::parent, pxr_ctx::pbio, pxr_ctx::pci, and pxr_ctx::subj.
Referenced by brix_gsi_build_pxyreq().
pxr_keygen()
static EVP_PKEY * pxr_keygen (X509 * parent) static
Definition at line 164 of file proxy_req.c.
References GSI_MIN_RSA_BITS, and key.
Referenced by brix_gsi_build_pxyreq().
pxr_make_pci_ext()
static X509_EXTENSION * pxr_make_pci_ext (int parent_pathlen) static
Definition at line 193 of file proxy_req.c.
References GSI_PROXYCERTINFO_OID, and GSI_PROXYPOLICY_IMPERSONATION.
Referenced by brix_gsi_build_pxyreq(), and brix_gsi_sign_pxyreq().
pxr_parent_pathlen()
static int pxr_parent_pathlen (X509 * parent) static
Definition at line 100 of file proxy_req.c.
References GSI_PROXYCERTINFO_OID, and GSI_PROXYCERTINFO_OLD_OID.
Referenced by brix_gsi_build_pxyreq().
pxr_req_pathlen()
static int pxr_req_pathlen (X509_REQ * req) static
Definition at line 343 of file proxy_req.c.
References GSI_PROXYCERTINFO_OID, and STACK_OF().
Referenced by brix_gsi_sign_pxyreq().
sgn_copy_signer_exts()
static int sgn_copy_signer_exts (X509 * signer, X509 * proxy, int * indepth, int * haskeyusage) static
Definition at line 405 of file proxy_req.c.
References GSI_KEY_USAGE_OID, GSI_PROXYCERTINFO_OID, GSI_PROXYCERTINFO_OLD_OID, and GSI_SUBJ_ALT_NAME_OID.
Referenced by brix_gsi_sign_pxyreq().
sgn_fail()
static int sgn_fail (sgn_ctx * x, char * err, size_t cap, const char * msg) static
Definition at line 387 of file proxy_req.c.
References sgn_ctx::obio, sgn_ctx::pciext, sgn_ctx::proxy, sgn_ctx::req, sgn_ctx::reqpub, sgn_ctx::sbio, and sgn_ctx::signer.
Referenced by brix_gsi_sign_pxyreq().