nginx-xrootd: src/protocols/webdav/proxy_config.c File Reference
proxy_config.c File Reference
#include "proxy_internal.h"
#include "core/compat/host_format.h"
#include "core/compat/log_diag.h"
Functions
static ngx_int_t webdav_proxy_split_scheme (ngx_conf_t *cf, ngx_str_t *url, ngx_flag_t *ssl, size_t *scheme_len, in_port_t *default_port)
static ngx_int_t webdav_proxy_parse_authority (ngx_conf_t *cf, ngx_str_t *url, size_t scheme_len, in_port_t default_port, ngx_url_t *u)
static ngx_int_t webdav_proxy_build_host (ngx_conf_t *cf, ngx_url_t *u, in_port_t default_port, ngx_str_t *host)
static ngx_int_t webdav_proxy_build_url_base (ngx_conf_t *cf, ngx_str_t *url, size_t scheme_len, ngx_str_t *host, ngx_str_t *url_base)
static ngx_int_t webdav_proxy_ensure_ssl_ctx (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf, ngx_flag_t ssl)
static ngx_int_t webdav_proxy_push_backends (ngx_http_brix_webdav_loc_conf_t *conf, ngx_url_t *u, ngx_str_t *host, ngx_str_t *url_base, ngx_flag_t ssl)
static ngx_int_t webdav_proxy_add_url (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf, ngx_str_t *url)
ngx_int_t webdav_proxy_build_backends (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
ngx_int_t webdav_proxy_parse_upstream_url (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
ngx_int_t webdav_proxy_pool_setup (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_loc_conf_t *prev)
Function Documentation
webdav_proxy_add_url()
static ngx_int_t webdav_proxy_add_url (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf, ngx_str_t * url) static
Definition at line 276 of file proxy_config.c.
References webdav_proxy_build_host(), webdav_proxy_build_url_base(), webdav_proxy_ensure_ssl_ctx(), webdav_proxy_parse_authority(), webdav_proxy_push_backends(), and webdav_proxy_split_scheme().
Referenced by webdav_proxy_build_backends().
webdav_proxy_build_backends()
ngx_int_t webdav_proxy_build_backends (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 316 of file proxy_config.c.
References brix_webdav_backend_t::host, brix_webdav_backend_t::resolved, brix_webdav_backend_t::ssl, ngx_http_brix_webdav_loc_conf_t::upstream_backends, ngx_http_brix_webdav_loc_conf_t::upstream_conf, ngx_http_brix_webdav_loc_conf_t::upstream_host, ngx_http_brix_webdav_loc_conf_t::upstream_resolved, ngx_http_brix_webdav_loc_conf_t::upstream_ssl, ngx_http_brix_webdav_loc_conf_t::upstream_url, ngx_http_brix_webdav_loc_conf_t::upstream_url_base, ngx_http_brix_webdav_loc_conf_t::upstream_urls, brix_webdav_backend_t::url_base, and webdav_proxy_add_url().
Referenced by webdav_build_static_proxy_backends(), and webdav_proxy_parse_upstream_url().
webdav_proxy_build_host()
static ngx_int_t webdav_proxy_build_host (ngx_conf_t * cf, ngx_url_t * u, in_port_t default_port, ngx_str_t * host) static
Definition at line 119 of file proxy_config.c.
References brix_format_host(), brix_format_host_port(), fn, ngx_memcpy, and ngx_pnalloc().
Referenced by webdav_proxy_add_url().
webdav_proxy_build_url_base()
static ngx_int_t webdav_proxy_build_url_base (ngx_conf_t * cf, ngx_str_t * url, size_t scheme_len, ngx_str_t * host, ngx_str_t * url_base) static
Definition at line 160 of file proxy_config.c.
References ngx_memcpy, and ngx_pnalloc().
Referenced by webdav_proxy_add_url().
webdav_proxy_ensure_ssl_ctx()
static ngx_int_t webdav_proxy_ensure_ssl_ctx (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf, ngx_flag_t ssl) static
Definition at line 193 of file proxy_config.c.
References ngx_pcalloc(), and s.
Referenced by webdav_proxy_add_url().
webdav_proxy_parse_authority()
static ngx_int_t webdav_proxy_parse_authority (ngx_conf_t * cf, ngx_str_t * url, size_t scheme_len, in_port_t default_port, ngx_url_t * u) static
Definition at line 77 of file proxy_config.c.
Referenced by webdav_proxy_add_url().
webdav_proxy_parse_upstream_url()
ngx_int_t webdav_proxy_parse_upstream_url (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 394 of file proxy_config.c.
References webdav_proxy_build_backends().
webdav_proxy_pool_setup()
ngx_int_t webdav_proxy_pool_setup (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_loc_conf_t * prev)
Definition at line 411 of file proxy_config.c.
References brix_proxy_pool_configure(), ngx_pcalloc(), s, and ngx_http_brix_webdav_loc_conf_t::upstream_conf.
Referenced by webdav_setup_dynamic_proxy_pool().
webdav_proxy_push_backends()
static ngx_int_t webdav_proxy_push_backends (ngx_http_brix_webdav_loc_conf_t * conf, ngx_url_t * u, ngx_str_t * host, ngx_str_t * url_base, ngx_flag_t ssl) static
Definition at line 230 of file proxy_config.c.
References brix_webdav_backend_t::host, brix_webdav_backend_t::resolved, brix_webdav_backend_t::ssl, ngx_http_brix_webdav_loc_conf_t::upstream_backends, and brix_webdav_backend_t::url_base.
Referenced by webdav_proxy_add_url().
webdav_proxy_split_scheme()
static ngx_int_t webdav_proxy_split_scheme (ngx_conf_t * cf, ngx_str_t * url, ngx_flag_t * ssl, size_t * scheme_len, in_port_t * default_port) static
Definition at line 35 of file proxy_config.c.
References BRIX_DIAG_CONF.
Referenced by webdav_proxy_add_url().