nginx-xrootd: src/protocols/webdav/proxy_response.c File Reference
proxy_response.c File Reference
#include "proxy_internal.h"
Functions
ngx_int_t webdav_proxy_reinit_request (ngx_http_request_t *r)
ngx_int_t webdav_proxy_process_status_line (ngx_http_request_t *r)
ngx_int_t webdav_proxy_process_header (ngx_http_request_t *r)
void webdav_proxy_abort_request (ngx_http_request_t *r)
void webdav_proxy_finalize_request (ngx_http_request_t *r, ngx_int_t rc)
Function Documentation
webdav_proxy_abort_request()
void webdav_proxy_abort_request (ngx_http_request_t * r)
Definition at line 159 of file proxy_response.c.
Referenced by webdav_proxy_handler().
webdav_proxy_finalize_request()
void webdav_proxy_finalize_request (ngx_http_request_t * r, ngx_int_t rc)
Definition at line 174 of file proxy_response.c.
References brix_proxy_pool_dec_in_flight(), brix_webdav_backend_t::fail_count, brix_webdav_backend_t::fail_time, ngx_http_brix_webdav_module, webdav_proxy_ctx_t::proxy_be_id, and webdav_proxy_ctx_t::selected_backend.
Referenced by webdav_proxy_handler().
webdav_proxy_process_header()
ngx_int_t webdav_proxy_process_header (ngx_http_request_t * r)
Definition at line 94 of file proxy_response.c.
Referenced by webdav_proxy_process_status_line(), and webdav_proxy_reinit_request().
webdav_proxy_process_status_line()
ngx_int_t webdav_proxy_process_status_line (ngx_http_request_t * r)
Definition at line 43 of file proxy_response.c.
References ngx_http_brix_webdav_module, webdav_proxy_ctx_t::status, and webdav_proxy_process_header().
Referenced by webdav_proxy_handler().
webdav_proxy_reinit_request()
ngx_int_t webdav_proxy_reinit_request (ngx_http_request_t * r)
Definition at line 21 of file proxy_response.c.
References ngx_http_brix_webdav_module, webdav_proxy_ctx_t::status, and webdav_proxy_process_header().
Referenced by webdav_proxy_handler().