nginx-xrootd: src/auth/gsi/proxy_req_unittest.c File Reference
proxy_req_unittest.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/pem.h>
#include <openssl/evp.h>
#include <openssl/bn.h>
#include <openssl/bio.h>
#include "proxy_req.h"
Data Structures
struct suite_t
Macros
#define CHECK(cond, msg)
Functions
static EVP_PKEY * genkey (void)
static uint8_t * pem_of (X509 *x, size_t *len)
static X509 * mkcert (const char *cn, int is_ca, X509 *ca, EVP_PKEY *cakey, EVP_PKEY **key)
static int verify_proxy (X509 *leaf, X509 *ca, X509 **inter, int ninter)
static X509 * x509_from_pem (const uint8_t *pem, size_t len)
static void suite_fixtures (suite_t *s)
static void test_build_pxyreq (suite_t *s)
static void test_sign_pxyreq (suite_t *s)
static void test_assemble_proxy (suite_t *s)
static void test_full_chain_verify (suite_t *s)
static void test_two_level_delegation (suite_t *s)
static void test_negatives (suite_t *s)
static void suite_teardown (suite_t *s)
int main (void)
Variables
static int checks = 0
static int failures = 0
Macro Definition Documentation
CHECK
#define CHECK (cond, msg)
Value:
        do {                                                  \
        checks++;                                                              \
        if (!(cond)) { failures++; printf("  FAIL: %s\n", (msg)); }           \
        else { printf("  ok: %s\n", (msg)); }                                 \
    } while (0)
Definition at line 28 of file proxy_req_unittest.c.
Function Documentation
genkey()
static EVP_PKEY * genkey (void) static
Definition at line 35 of file proxy_req_unittest.c.
References c.
Referenced by mkcert(), and test_assemble_proxy().
main()
int main (void)
Definition at line 359 of file proxy_req_unittest.c.
References checks, failures, s, suite_fixtures(), suite_teardown(), test_assemble_proxy(), test_build_pxyreq(), test_full_chain_verify(), test_negatives(), test_sign_pxyreq(), and test_two_level_delegation().
mkcert()
static X509 * mkcert (const char * cn, int is_ca, X509 * ca, EVP_PKEY * cakey, EVP_PKEY ** key) static
Definition at line 65 of file proxy_req_unittest.c.
References genkey(), and key.
Referenced by suite_fixtures(), and test_negatives().
pem_of()
static uint8_t * pem_of (X509 * x, size_t * len) static
Definition at line 47 of file proxy_req_unittest.c.
Referenced by suite_fixtures(), and test_negatives().
suite_fixtures()
static void suite_fixtures (suite_t * s) static
Definition at line 161 of file proxy_req_unittest.c.
References mkcert(), pem_of(), and s.
Referenced by main().
suite_teardown()
static void suite_teardown (suite_t * s) static
Definition at line 350 of file proxy_req_unittest.c.
References s.
Referenced by main().
test_assemble_proxy()
static void test_assemble_proxy (suite_t * s) static
Definition at line 233 of file proxy_req_unittest.c.
References brix_gsi_assemble_proxy(), CHECK, brix_gsi_buf_t::data, genkey(), brix_gsi_buf_t::len, and s.
Referenced by main().
test_build_pxyreq()
static void test_build_pxyreq (suite_t * s) static
Definition at line 175 of file proxy_req_unittest.c.
References brix_gsi_build_pxyreq(), CHECK, brix_gsi_buf_t::data, brix_gsi_buf_t::len, and s.
Referenced by main().
test_full_chain_verify()
static void test_full_chain_verify (suite_t * s) static
Definition at line 265 of file proxy_req_unittest.c.
References CHECK, s, and verify_proxy().
Referenced by main().
test_negatives()
static void test_negatives (suite_t * s) static
Definition at line 310 of file proxy_req_unittest.c.
References brix_gsi_build_pxyreq(), brix_gsi_sign_pxyreq(), CHECK, brix_gsi_buf_t::data, mkcert(), pem_of(), and s.
Referenced by main().
test_sign_pxyreq()
static void test_sign_pxyreq (suite_t * s) static
Definition at line 193 of file proxy_req_unittest.c.
References brix_gsi_sign_pxyreq(), CHECK, brix_gsi_buf_t::data, brix_gsi_buf_t::len, s, and x509_from_pem().
Referenced by main().
test_two_level_delegation()
static void test_two_level_delegation (suite_t * s) static
Definition at line 276 of file proxy_req_unittest.c.
References brix_gsi_build_pxyreq(), brix_gsi_sign_pxyreq(), CHECK, brix_gsi_buf_t::data, brix_gsi_buf_t::len, s, verify_proxy(), and x509_from_pem().
Referenced by main().
verify_proxy()
static int verify_proxy (X509 * leaf, X509 * ca, X509 ** inter, int ninter) static
Definition at line 98 of file proxy_req_unittest.c.
References STACK_OF().
Referenced by test_full_chain_verify(), and test_two_level_delegation().
x509_from_pem()
static X509 * x509_from_pem (const uint8_t * pem, size_t len) static
Definition at line 120 of file proxy_req_unittest.c.
Referenced by test_sign_pxyreq(), and test_two_level_delegation().
Variable Documentation
checks
int checks = 0 static
Definition at line 27 of file proxy_req_unittest.c.
Referenced by main().
failures
int failures = 0 static
Definition at line 27 of file proxy_req_unittest.c.
Referenced by chmod_recursive(), do_chmod(), and main().