nginx-xrootd: src/protocols/s3/put_finalize.c File Reference
put_finalize.c File Reference
#include "s3_put_internal.h"
#include "fs/xfer/xfer.h"
#include <sys/stat.h>
Functions
ngx_int_t s3_commit_put (ngx_http_request_t *r, ngx_log_t *log, const char *root_canon, brix_vfs_writer_t *writer, const char *final_path)
int s3_put_commit_conflict (ngx_http_request_t *r)
void s3_put_finalize_error (ngx_http_request_t *r)
void s3_put_finalize_fs_error (ngx_http_request_t *r, int saved_errno)
void s3_put_finalize_empty_ok (ngx_http_request_t *r)
void s3_put_finalize_ok (ngx_http_request_t *r, size_t body_bytes, ngx_uint_t body_mode)
void s3_put_finalize_bad_digest (ngx_http_request_t *r)
void s3_put_finalize_invalid_request (ngx_http_request_t *r)
void s3_put_finalize_codec_error (ngx_http_request_t *r, ngx_int_t status)
int s3_put_checksum_failed (ngx_http_request_t *r, const char *fs_path, const char *root_canon)
void s3_put_finalize_client_error (ngx_http_request_t *r, int status, const char *code, const char *message)
Function Documentation
s3_commit_put()
ngx_int_t s3_commit_put (ngx_http_request_t * r, ngx_log_t * log, const char * root_canon, brix_vfs_writer_t * writer, const char * final_path)
Definition at line 22 of file put_finalize.c.
References BRIX_PROTO_S3, brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), brix_vfs_probe(), brix_vfs_writer_commit_ex(), BRIX_XFER_COMMIT_ERR, brix_xfer_finish(), BRIX_XFER_OK, BRIX_XFER_STAGE, ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::exclusive_create, brix_vfs_stat_t::is_regular, log, ngx_http_brix_s3_module, brix_vfs_ctx_t::pool, s3_vfs_bind_deleg(), brix_vfs_stat_t::size, ngx_http_brix_shared_conf_t::storage_credential_dir, and ngx_http_brix_shared_conf_t::storage_credential_fallback.
Referenced by s3_chunk_finalize(), s3_put_aio_done(), and s3put_commit_and_headers().
s3_put_checksum_failed()
int s3_put_checksum_failed (ngx_http_request_t * r, const char * fs_path, const char * root_canon)
Definition at line 286 of file put_finalize.c.
References S3_CKSUM_CONFLICT, S3_CKSUM_MISMATCH, s3_put_checksum_apply(), s3_put_finalize_bad_digest(), and s3_put_finalize_invalid_request().
Referenced by s3_chunk_finalize(), s3_put_aio_done(), and s3put_commit_and_headers().
s3_put_commit_conflict()
int s3_put_commit_conflict (ngx_http_request_t * r)
Definition at line 79 of file put_finalize.c.
References s3_put_finalize_client_error().
Referenced by s3_chunk_finalize(), s3_put_aio_done(), and s3put_commit_and_headers().
s3_put_finalize_bad_digest()
void s3_put_finalize_bad_digest (ngx_http_request_t * r)
Definition at line 222 of file put_finalize.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), BRIX_S3_METHOD_PUT, s3_metrics_finalize_request_method(), and s3_send_xml_error().
Referenced by s3_chunk_finalize(), and s3_put_checksum_failed().
s3_put_finalize_client_error()
void s3_put_finalize_client_error (ngx_http_request_t * r, int status, const char * code, const char * message)
Definition at line 340 of file put_finalize.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), BRIX_S3_METHOD_PUT, code, s3_metrics_finalize_request_method(), and s3_send_xml_error().
Referenced by s3_chunk_decode_failed(), s3_put_commit_conflict(), and s3_put_streaming().
s3_put_finalize_codec_error()
void s3_put_finalize_codec_error (ngx_http_request_t * r, ngx_int_t status)
Definition at line 260 of file put_finalize.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), BRIX_S3_METHOD_PUT, code, s3_metrics_finalize_request_method(), and s3_send_xml_error().
Referenced by s3put_select_codec(), s3put_stream_aws_chunked(), and s3put_stream_sync().
s3_put_finalize_empty_ok()
void s3_put_finalize_empty_ok (ngx_http_request_t * r)
Definition at line 175 of file put_finalize.c.
References brix_dashboard_http_finish(), BRIX_S3_METHOD_PUT, and s3_metrics_finalize_request_method().
Referenced by s3_put_aio_done(), s3_put_finalize_ok(), and s3_put_try_sentinel().
s3_put_finalize_error()
void s3_put_finalize_error (ngx_http_request_t * r)
Definition at line 100 of file put_finalize.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METHOD_PUT, BRIX_S3_METRIC_INC, and s3_metrics_finalize_request_method().
Referenced by s3_chunk_decode_failed(), s3_chunk_finalize(), s3_put_aio_done(), s3_put_finalize_fs_error(), s3_put_streaming(), s3_put_try_sentinel(), s3put_commit_and_headers(), s3put_precondition(), s3put_stream_body(), s3put_stream_offload(), and s3put_stream_sync().
s3_put_finalize_fs_error()
void s3_put_finalize_fs_error (ngx_http_request_t * r, int saved_errno)
Definition at line 127 of file put_finalize.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_http_errno_to_status(), BRIX_S3_EVENT_ACCESS_DENIED, BRIX_S3_EVENT_NO_SUCH_KEY, BRIX_S3_METHOD_PUT, BRIX_S3_METRIC_INC, code, s3_metrics_finalize_request_method(), s3_put_finalize_error(), and s3_send_xml_error().
Referenced by s3_put_try_sentinel(), s3put_ensure_parent_dirs(), and s3put_open_target().
s3_put_finalize_invalid_request()
void s3_put_finalize_invalid_request (ngx_http_request_t * r)
Definition at line 239 of file put_finalize.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), BRIX_S3_METHOD_PUT, s3_metrics_finalize_request_method(), and s3_send_xml_error().
Referenced by s3_chunk_finalize(), and s3_put_checksum_failed().
s3_put_finalize_ok()
void s3_put_finalize_ok (ngx_http_request_t * r, size_t body_bytes, ngx_uint_t body_mode)
Definition at line 200 of file put_finalize.c.
References brix_dashboard_http_add(), BRIX_S3_METRIC_ADD, BRIX_S3_METRIC_INC, and s3_put_finalize_empty_ok().
Referenced by s3_chunk_finalize(), and s3put_commit_and_headers().