nginx-xrootd: src/protocols/webdav/put_body.c File Reference
put_body.c File Reference
#include "webdav.h"
#include "core/http/etag.h"
#include "core/http/http_body.h"
#include "core/compat/integrity_info.h"
#include "core/http/http_conditionals.h"
#include "core/compat/range.h"
#include "core/compat/staged_file.h"
#include "observability/dashboard/dashboard_tracking.h"
#include "fs/vfs/vfs.h"
#include "fs/xfer/xfer.h"
#include "auth/impersonate/lifecycle.h"
#include "fs/path/path.h"
#include "core/compat/cstr.h"
#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>
#include "put_internal.h"
Data Structures
struct webdav_put_aio_t
struct webdav_put_body_ctx_t
Enumerations
enum webdav_digest_kind_t { WEBDAV_DIGEST_NONE = 0 , WEBDAV_DIGEST_FOUND , WEBDAV_DIGEST_BAD }
Functions
static int webdav_hex_norm_equal (const char *a, const char *b)
static ngx_int_t webdav_digest_value_hex (ngx_http_request_t *r, const u_char *val, size_t vlen, int is_b64, char *out, size_t outsz)
static webdav_digest_kind_t webdav_digest_select (ngx_http_request_t *r, const char **alg, char *exp_hex, size_t exp_sz)
ngx_int_t webdav_put_verify_ingest_digest (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, brix_vfs_writer_t *writer, const char *path)
void webdav_put_persist_checksums (ngx_http_request_t *r, const char *path)
static void webdav_put_aio_thread (void *data, ngx_log_t *log)
static void webdav_put_aio_done (ngx_event_t *ev)
static webdav_put_step_t webdav_put_try_threaded (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const webdav_put_body_ctx_t *bctx)
static webdav_put_step_t webdav_put_select_codec (ngx_http_request_t *r, webdav_put_body_ctx_t *bctx)
static webdav_put_step_t webdav_put_write_sync (ngx_http_request_t *r, webdav_put_body_ctx_t *bctx)
webdav_put_step_t webdav_put_stream_body (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const char *path, brix_vfs_writer_t *writer, int created)
Variables
struct {
const char * tok
size_t toklen
const char * alg
int b64
} webdav_digest_tokens []
Enumeration Type Documentation
webdav_digest_kind_t
enum webdav_digest_kind_t
Enumerator
WEBDAV_DIGEST_NONE
WEBDAV_DIGEST_FOUND
WEBDAV_DIGEST_BAD
Definition at line 42 of file put_body.c.
Function Documentation
webdav_digest_select()
static webdav_digest_kind_t webdav_digest_select (ngx_http_request_t * r, const char ** alg, char * exp_hex, size_t exp_sz) static
Definition at line 127 of file put_body.c.
References alg, b64, brix_http_find_header(), tok, toklen, WEBDAV_DIGEST_BAD, WEBDAV_DIGEST_FOUND, WEBDAV_DIGEST_NONE, webdav_digest_tokens, and webdav_digest_value_hex().
Referenced by webdav_put_verify_ingest_digest().
webdav_digest_value_hex()
static ngx_int_t webdav_digest_value_hex (ngx_http_request_t * r, const u_char * val, size_t vlen, int is_b64, char * out, size_t outsz) static
Definition at line 80 of file put_body.c.
References c, webdav_put_aio_t::len, and ngx_pnalloc().
Referenced by webdav_digest_select().
webdav_hex_norm_equal()
static int webdav_hex_norm_equal (const char * a, const char * b) static
Definition at line 65 of file put_body.c.
Referenced by webdav_put_verify_ingest_digest().
webdav_put_aio_done()
static void webdav_put_aio_done (ngx_event_t * ev) static
Definition at line 355 of file put_body.c.
References brix_dashboard_http_add(), brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_log_safe_path(), brix_vfs_writer_abort(), brix_vfs_writer_commit(), BRIX_XFER_COMMIT_ERR, brix_xfer_finish(), BRIX_XFER_OK, BRIX_XFER_STAGE, webdav_put_aio_t::created, webdav_put_aio_t::io_errno, webdav_put_aio_t::len, ngx_http_brix_webdav_module, webdav_put_aio_t::nwritten, webdav_put_aio_t::path, webdav_put_aio_t::r, webdav_metrics_finalize_request(), webdav_put_persist_checksums(), webdav_put_verify_ingest_digest(), webdav_send_status_only(), and webdav_put_aio_t::writer.
Referenced by webdav_put_try_threaded().
webdav_put_aio_thread()
static void webdav_put_aio_thread (void * data, ngx_log_t * log) static
Definition at line 326 of file put_body.c.
References brix_http_body_write_to_writer(), webdav_put_aio_t::io_errno, webdav_put_aio_t::len, log, webdav_put_aio_t::nwritten, webdav_put_aio_t::r, and webdav_put_aio_t::writer.
Referenced by webdav_put_try_threaded().
webdav_put_persist_checksums()
void webdav_put_persist_checksums (ngx_http_request_t * r, const char * path)
Definition at line 289 of file put_body.c.
References brix_integrity_opts_t::allow_xattr_cache, brix_integrity_get_fd(), brix_str_cbuf(), brix_vfs_open_fd(), ngx_http_brix_webdav_loc_conf_t::checksum_on_write, close(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_module, brix_integrity_opts_t::require_regular_file, ngx_http_brix_shared_conf_t::root_canon, tok, and brix_integrity_opts_t::update_xattr_cache.
Referenced by webdav_put_aio_done(), webdav_put_commit(), and webdav_put_ranged_resume().
webdav_put_select_codec()
static webdav_put_step_t webdav_put_select_codec (ngx_http_request_t * r, webdav_put_body_ctx_t * bctx) static
Definition at line 538 of file put_body.c.
References brix_codec_desc_t::available, webdav_put_body_ctx_t::body_summary, brix_codec_by_http_token(), BRIX_CODEC_IDENTITY, brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_http_find_header(), brix_vfs_writer_abort(), brix_http_body_summary_t::bytes, brix_http_body_summary_t::has_spooled, brix_codec_desc_t::id, webdav_put_body_ctx_t::put_codec, webdav_metrics_finalize_request(), WEBDAV_PUT_CONTINUE, WEBDAV_PUT_DONE, and webdav_put_body_ctx_t::writer.
Referenced by webdav_put_stream_body().
webdav_put_stream_body()
webdav_put_step_t webdav_put_stream_body (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const char * path, brix_vfs_writer_t * writer, int created)
Definition at line 684 of file put_body.c.
References webdav_put_body_ctx_t::body_summary, BRIX_CODEC_IDENTITY, brix_http_body_summary(), brix_vfs_writer_abort(), BRIX_WEBDAV_METRIC_ADD, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_PUT_EMPTY, brix_http_body_summary_t::bytes, webdav_put_body_ctx_t::created, webdav_put_body_ctx_t::path, webdav_put_body_ctx_t::put_codec, webdav_metrics_finalize_request(), WEBDAV_PUT_CONTINUE, WEBDAV_PUT_DONE, webdav_put_select_codec(), webdav_put_start_dashboard(), webdav_put_try_threaded(), webdav_put_write_sync(), and webdav_put_body_ctx_t::writer.
Referenced by webdav_put_body_inner().
webdav_put_try_threaded()
static webdav_put_step_t webdav_put_try_threaded (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const webdav_put_body_ctx_t * bctx) static
Definition at line 469 of file put_body.c.
References webdav_put_body_ctx_t::body_summary, BRIX_CODEC_IDENTITY, brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_vfs_writer_abort(), BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_PUT_THREADED, brix_http_body_summary_t::bytes, ngx_http_brix_webdav_loc_conf_t::common, webdav_put_aio_t::created, webdav_put_body_ctx_t::created, brix_http_body_summary_t::has_spooled, webdav_put_aio_t::len, webdav_put_aio_t::path, webdav_put_body_ctx_t::path, webdav_put_body_ctx_t::put_codec, webdav_put_aio_t::r, ngx_http_brix_shared_conf_t::thread_pool, webdav_metrics_finalize_request(), webdav_put_aio_done(), webdav_put_aio_thread(), WEBDAV_PUT_CONTINUE, WEBDAV_PUT_DONE, webdav_put_aio_t::writer, and webdav_put_body_ctx_t::writer.
Referenced by webdav_put_stream_body().
webdav_put_verify_ingest_digest()
ngx_int_t webdav_put_verify_ingest_digest (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, brix_vfs_writer_t * writer, const char * path)
Definition at line 206 of file put_body.c.
References alg, brix_http_find_header(), brix_integrity_get_fd(), brix_log_safe_path(), brix_vfs_writer_fd(), close(), brix_integrity_info_t::hex, open(), ngx_http_brix_webdav_loc_conf_t::require_digest, brix_integrity_opts_t::require_regular_file, WEBDAV_DIGEST_BAD, WEBDAV_DIGEST_NONE, webdav_digest_select(), and webdav_hex_norm_equal().
Referenced by webdav_put_aio_done(), and webdav_put_commit().
webdav_put_write_sync()
static webdav_put_step_t webdav_put_write_sync (ngx_http_request_t * r, webdav_put_body_ctx_t * bctx) static
Definition at line 605 of file put_body.c.
References webdav_put_body_ctx_t::body_summary, BRIX_CODEC_IDENTITY, brix_dashboard_http_add(), brix_dashboard_http_error(), brix_dashboard_http_finish(), BRIX_DECODE_MAX_OUTPUT, brix_http_body_decode_to_fd(), brix_http_body_write_to_writer(), brix_vfs_writer_abort(), brix_vfs_writer_fd(), BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_PUT_EMPTY, BRIX_WEBDAV_PUT_MEMORY, BRIX_WEBDAV_PUT_SPOOLED, brix_http_body_summary_t::bytes, brix_http_body_summary_t::has_memory, brix_http_body_summary_t::has_spooled, webdav_put_body_ctx_t::path, webdav_put_body_ctx_t::put_codec, webdav_metrics_finalize_request(), WEBDAV_PUT_CONTINUE, WEBDAV_PUT_DONE, and webdav_put_body_ctx_t::writer.
Referenced by webdav_put_stream_body().
Variable Documentation
alg
const char* alg
Definition at line 52 of file put_body.c.
Referenced by brix_cache_commit_staged(), brix_checksum_digest_fd(), brix_checksum_hex_fd(), brix_checksum_hex_name_fd(), brix_checksum_hex_obj(), brix_checksum_is_u32(), brix_checksum_is_u64(), brix_checksum_lookup_alg(), brix_checksum_name(), brix_checksum_parse(), brix_checksum_u32_fd(), brix_checksum_u64_fd(), brix_ckscan_algorithm_supported(), brix_ckscan_select_payload(), brix_conf_set_cache_verify_digest(), brix_dirlist_parse_algorithm(), brix_query_digest_fd(), brix_query_digest_file(), brix_query_parse_algorithm(), brix_scan_record_file(), brix_sd_xroot_query_checksum(), brix_xmeta_digest_add(), brix_xmeta_digest_get(), brix_xmeta_digest_set(), check_digests(), ckv_verify_one(), emit_ext_digest(), integrity_record_read(), tpc_verify_source_checksum(), webdav_digest_select(), webdav_put_verify_ingest_digest(), and xrdhttp_add_checksum_header().
b64
int b64
Definition at line 52 of file put_body.c.
Referenced by brix_ftp_ev_b64_decode(), brix_ftp_ev_send_adat(), ev_reply_wrapped(), s3_echo_object_checksums(), s3_put_checksum_apply(), s3_put_trailer_checksum_apply(), wb_parse_basic_userpass(), and webdav_digest_select().
tok
const char* tok
Definition at line 52 of file put_body.c.
Referenced by acc_csv_push_field(), acc_tokenize_and_dispatch(), add_target(), af_is_mounted(), af_readdir(), auth_hdr_bearer(), auth_suite_token_probes(), bearer_acquire(), brix_codec_by_http_token(), brix_credential_mode_token(), brix_ftp_ev_cmd_adat(), brix_ftp_ev_cmd_protected(), brix_ftp_ev_send_adat(), brix_identity_derive_attrs(), brix_identity_parse_fqan(), brix_identity_trim_ws(), brix_meta_advisory_decode(), brix_oauth2_parse_access_token(), brix_path_resolve(), brix_qconfig_next_token(), brix_relay_guard_handshake(), brix_tier_register_cache_peers(), brix_token_strategy_parse(), brix_tx_parse_response(), brixautofs_repo_listed(), build_canonical_headers(), chk_probe_cred_validity(), cms_srv_login_append_path(), cms_srv_login_next_path(), cms_srv_login_seg_path(), cms_srv_parse_login(), cvmfs_geo_parse(), cvmfs_geo_parse_entry(), cvmfs_geo_scan_host(), cvmfs_geo_scan_port(), diagnose_token(), dig_authorize(), dir_of(), dispatch(), dispatch_builtin(), dx_authz_expired(), dx_authz_scope(), ev_reply_wrapped(), explain_env_credentials(), inner_coding_is_passthrough(), inner_coding_next_token(), map_holder(), map_holders(), parse_holder(), parse_list(), pmark_csv_has(), refresh_bearer_token(), reg_add_aud(), reg_add_list(), remote_doctor_report_creds(), repl(), s3_aws_chunked_has_inner_coding(), s3_cksum_by_token(), token_first(), token_needs_refresh(), tokenauth_slice_token(), tokenize(), topo_emit_json(), webdav_digest_select(), webdav_put_persist_checksums(), xrd_run_battery(), xrd_whoami(), and xrdjwt_split().
toklen
size_t toklen
Definition at line 52 of file put_body.c.
Referenced by srr_vos_array(), and webdav_digest_select().
[struct]
const struct { ... } webdav_digest_tokens[]
Initial value:
= {
    { "md5",     3, "md5",     1 },
    { "sha-256", 7, "sha256",  1 },
    { "sha256",  6, "sha256",  1 },
    { "adler32", 7, "adler32", 0 },
    { "crc32c",  6, "crc32c",  0 },
    { "crc32",   5, "crc32",   0 },
}
Referenced by webdav_digest_select().