nginx-xrootd: src/protocols/webdav/put_internal.h File Reference
put_internal.h File Reference
Enumerations
enum webdav_put_step_t { WEBDAV_PUT_CONTINUE = 0 , WEBDAV_PUT_DONE }
Functions
void webdav_put_persist_checksums (ngx_http_request_t *r, const char *path)
webdav_put_step_t webdav_put_precheck (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, char *path, int *created)
webdav_put_step_t webdav_put_open_target (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const char *path, brix_vfs_ctx_t *vctx, brix_vfs_writer_t **out_writer)
void webdav_put_start_dashboard (ngx_http_request_t *r, const char *path, int64_t bytes)
webdav_put_step_t webdav_put_stream_body (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const char *path, brix_vfs_writer_t *writer, int created)
Enumeration Type Documentation
webdav_put_step_t
enum webdav_put_step_t
Enumerator
WEBDAV_PUT_CONTINUE
WEBDAV_PUT_DONE
Definition at line 24 of file put_internal.h.
Function Documentation
webdav_put_open_target()
webdav_put_step_t webdav_put_open_target (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const char * path, brix_vfs_ctx_t * vctx, brix_vfs_writer_t ** out_writer)
Definition at line 323 of file put_setup.c.
References brix_http_map_errno(), brix_log_safe_path(), BRIX_VFS_O_ATOMIC, brix_vfs_writer_open(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::verify_write, webdav_metrics_finalize_request(), WEBDAV_PUT_CONTINUE, WEBDAV_PUT_DONE, and webdav_put_vfs_ctx_init().
Referenced by webdav_put_body_inner().
webdav_put_persist_checksums()
void webdav_put_persist_checksums (ngx_http_request_t * r, const char * path)
Definition at line 51 of file put_body.c.
References brix_integrity_opts_t::allow_xattr_cache, brix_integrity_get_fd(), brix_str_cbuf(), brix_vfs_open_fd(), ngx_http_brix_webdav_loc_conf_t::checksum_on_write, close(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_module, brix_integrity_opts_t::require_regular_file, ngx_http_brix_shared_conf_t::root_canon, and brix_integrity_opts_t::update_xattr_cache.
Referenced by webdav_put_aio_done(), webdav_put_commit(), and webdav_put_ranged_resume().
webdav_put_precheck()
webdav_put_step_t webdav_put_precheck (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, char * path, int * created)
Definition at line 219 of file put_setup.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_ETAG_WEAK, brix_http_check_etag_preconditions(), BRIX_HTTP_COND_WEAK_EQUIV, brix_http_find_header(), brix_http_parse_content_range(), BRIX_PROTO_WEBDAV, brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), brix_vfs_probe(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::identity, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), brix_vfs_ctx_t::pool, brix_http_content_range_t::present, ngx_http_brix_shared_conf_t::root_canon, brix_vfs_stat_t::size, stat(), ngx_http_brix_shared_conf_t::storage_credential_dir, ngx_http_brix_shared_conf_t::storage_credential_fallback, ngx_http_brix_webdav_loc_conf_t::upload_resume, WEBDAV_MAX_PATH, webdav_metrics_finalize_request(), WEBDAV_PUT_CONTINUE, WEBDAV_PUT_DONE, webdav_put_ranged_resume(), and webdav_vfs_bind_deleg().
Referenced by webdav_put_body_inner().
webdav_put_start_dashboard()
void webdav_put_start_dashboard (ngx_http_request_t * r, const char * path, int64_t bytes)
Definition at line 395 of file put_setup.c.
References brix_dashboard_http_start_identity(), BRIX_XFER_DIR_WRITE, BRIX_XFER_PROTO_WEBDAV, ngx_http_brix_webdav_req_ctx_t::dn, and ngx_http_brix_webdav_module.
Referenced by webdav_put_stream_body().
webdav_put_stream_body()
webdav_put_step_t webdav_put_stream_body (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const char * path, brix_vfs_writer_t * writer, int created)
Definition at line 426 of file put_body.c.
References webdav_put_body_ctx_t::body_summary, BRIX_CODEC_IDENTITY, brix_http_body_summary(), brix_vfs_writer_abort(), BRIX_WEBDAV_METRIC_ADD, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_PUT_EMPTY, brix_http_body_summary_t::bytes, webdav_put_body_ctx_t::created, webdav_put_body_ctx_t::path, webdav_put_body_ctx_t::put_codec, webdav_metrics_finalize_request(), WEBDAV_PUT_CONTINUE, WEBDAV_PUT_DONE, webdav_put_select_codec(), webdav_put_start_dashboard(), webdav_put_try_threaded(), webdav_put_write_sync(), and webdav_put_body_ctx_t::writer.
Referenced by webdav_put_body_inner().