nginx-xrootd: src/protocols/s3/put_inner.c File Reference
put_inner.c File Reference
#include "s3_put_internal.h"
Functions
static int s3_put_try_sentinel (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const u_char *fs_path)
static ngx_int_t s3put_ensure_parent_dirs (s3put_state_t *st)
static ngx_int_t s3put_precondition (s3put_state_t *st)
static ngx_int_t s3put_open_target (s3put_state_t *st)
void s3_put_body_inner (ngx_http_request_t *r)
Function Documentation
s3_put_body_inner()
void s3_put_body_inner (ngx_http_request_t * r)
Definition at line 218 of file put_inner.c.
References s3put_state_t::body_mode, BRIX_CODEC_IDENTITY, BRIX_S3_PUT_EMPTY, s3put_state_t::cf, ngx_http_s3_req_ctx_t::fs_path, s3put_state_t::fs_path, ngx_http_brix_s3_module, s3put_state_t::put_codec, s3put_state_t::r, s3put_commit_and_headers(), s3put_open_target(), s3put_precondition(), and s3put_stream_body().
Referenced by s3_put_body_handler().
s3_put_try_sentinel()
static int s3_put_try_sentinel (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const u_char * fs_path) static
Definition at line 12 of file put_inner.c.
References brix_dashboard_http_start_identity(), brix_log_safe_path(), BRIX_S3_EVENT_DIR_SENTINEL, BRIX_S3_METRIC_INC, BRIX_S3_PUT_EMPTY, brix_vfs_mkdir(), brix_vfs_open_fd(), BRIX_XFER_DIR_WRITE, BRIX_XFER_PROTO_S3, close(), ngx_http_s3_loc_conf_t::common, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, s3_build_vfs_ctx(), s3_dashboard_identity(), S3_DIR_SENTINEL, s3_put_finalize_empty_ok(), s3_put_finalize_error(), and s3_put_finalize_fs_error().
Referenced by s3put_precondition().
s3put_ensure_parent_dirs()
static ngx_int_t s3put_ensure_parent_dirs (s3put_state_t * st) static
Definition at line 91 of file put_inner.c.
References brix_log_safe_path(), brix_vfs_mkdir(), brix_vfs_probe(), s3put_state_t::cf, s3put_state_t::fs_path, brix_vfs_stat_t::is_directory, PATH_MAX, s3put_state_t::r, s3_build_vfs_ctx(), and s3_put_finalize_fs_error().
Referenced by s3put_precondition().
s3put_open_target()
static ngx_int_t s3put_open_target (s3put_state_t * st) static
Definition at line 193 of file put_inner.c.
References brix_log_safe_path(), brix_vfs_staged_open(), s3put_state_t::cf, s3put_state_t::fs_path, s3put_state_t::r, s3_build_vfs_ctx(), s3_put_finalize_fs_error(), and s3put_state_t::staged.
Referenced by s3_put_body_inner().
s3put_precondition()
static ngx_int_t s3put_precondition (s3put_state_t * st) static
Definition at line 163 of file put_inner.c.
References s3put_state_t::cf, s3put_state_t::fs_path, s3put_state_t::r, s3_put_finalize_error(), s3_put_try_sentinel(), and s3put_ensure_parent_dirs().
Referenced by s3_put_body_inner().