nginx-xrootd: src/protocols/s3/put_chunk.c File Reference
put_chunk.c File Reference
#include "s3_put_internal.h"
Functions
void s3_chunk_finalize (ngx_http_request_t *r, const char *root_canon, const char *fs_path, brix_vfs_staged_t *staged, const s3_chunk_trailer_t *trailer, uint64_t expected, ngx_uint_t body_mode)
void s3_chunk_decode_failed (ngx_http_request_t *r, const char *root_canon, brix_vfs_staged_t *staged, int http_status)
void s3_chunk_aio_thread (void *data, ngx_log_t *log)
void s3_build_chunk_verify (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, s3_chunk_verify_t *v)
void s3_chunk_aio_done (ngx_event_t *ev)
Function Documentation
s3_build_chunk_verify()
void s3_build_chunk_verify (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, s3_chunk_verify_t * v)
Definition at line 133 of file put_chunk.c.
References s3_chunk_verify_t::amz_date, s3_chunk_verify_t::enabled, ngx_http_s3_req_ctx_t::have_sigv4, ngx_http_brix_s3_module, ngx_memcpy, s3_chunk_verify_t::scope, s3_chunk_verify_t::seed_signature, s3_chunk_verify_t::signing_key, ngx_http_s3_req_ctx_t::sigv4_amz_date, ngx_http_s3_req_ctx_t::sigv4_scope, ngx_http_s3_req_ctx_t::sigv4_seed_signature, ngx_http_s3_req_ctx_t::sigv4_signing_key, and ngx_http_s3_loc_conf_t::verify_chunk_signatures.
Referenced by s3_put_streaming().
s3_chunk_aio_done()
void s3_chunk_aio_done (ngx_event_t * ev)
Definition at line 158 of file put_chunk.c.
References s3_chunk_aio_t::body_mode, s3_chunk_aio_t::expected, s3_chunk_aio_t::fs_path, s3_chunk_aio_t::http_status, s3_chunk_aio_t::r, s3_chunk_aio_t::rc, s3_chunk_aio_t::root_canon, s3_chunk_decode_failed(), s3_chunk_finalize(), s3_chunk_aio_t::staged, and s3_chunk_aio_t::trailer.
Referenced by s3_put_streaming().
s3_chunk_aio_thread()
void s3_chunk_aio_thread (void * data, ngx_log_t * log)
Definition at line 113 of file put_chunk.c.
References brix_vfs_staged_fd(), s3_chunk_aio_t::expected, s3_chunk_aio_t::fs_path, s3_chunk_aio_t::http_status, log, s3_chunk_aio_t::r, s3_chunk_aio_t::rc, s3_aws_chunked_decode_to_fd(), s3_chunk_aio_t::staged, s3_chunk_aio_t::trailer, s3_chunk_aio_t::verify, and s3_chunk_aio_t::window.
Referenced by s3_put_streaming().
s3_chunk_decode_failed()
void s3_chunk_decode_failed (ngx_http_request_t * r, const char * root_canon, brix_vfs_staged_t * staged, int http_status)
Definition at line 87 of file put_chunk.c.
References brix_vfs_staged_abort(), s3_put_finalize_client_error(), and s3_put_finalize_error().
Referenced by s3_chunk_aio_done(), and s3_put_streaming().
s3_chunk_finalize()
void s3_chunk_finalize (ngx_http_request_t * r, const char * root_canon, const char * fs_path, brix_vfs_staged_t * staged, const s3_chunk_trailer_t * trailer, uint64_t expected, ngx_uint_t body_mode)
Definition at line 15 of file put_chunk.c.
References s3_chunk_trailer_t::algo_token, brix_log_safe_path(), BRIX_PROTO_S3, brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), brix_vfs_probe(), ngx_http_s3_loc_conf_t::common, brix_vfs_stat_t::mtime, ngx_http_brix_s3_module, brix_vfs_ctx_t::pool, s3_apply_put_tagging_header(), s3_apply_put_user_metadata(), S3_CKSUM_CONFLICT, S3_CKSUM_MISMATCH, s3_commit_put(), s3_etag(), s3_put_checksum_failed(), s3_put_commit_conflict(), s3_put_finalize_bad_digest(), s3_put_finalize_error(), s3_put_finalize_invalid_request(), s3_put_finalize_ok(), s3_put_trailer_checksum_apply(), s3_set_header(), s3_vfs_bind_deleg(), brix_vfs_stat_t::size, stat(), ngx_http_brix_shared_conf_t::storage_credential_dir, ngx_http_brix_shared_conf_t::storage_credential_fallback, and s3_chunk_trailer_t::value.
Referenced by s3_chunk_aio_done(), and s3_put_streaming().