nginx-xrootd: src/protocols/s3/put_aio.c File Reference
put_aio.c File Reference
#include "s3_put_internal.h"
Functions
ngx_thread_pool_t * s3_thread_pool (ngx_http_s3_loc_conf_t *cf)
void s3_put_aio_thread (void *data, ngx_log_t *log)
void s3_put_aio_done (ngx_event_t *ev)
Function Documentation
s3_put_aio_done()
void s3_put_aio_done (ngx_event_t * ev)
Definition at line 75 of file put_aio.c.
References s3_put_aio_t::body_bytes, s3_put_aio_t::body_mode, brix_dashboard_http_add(), brix_log_safe_path(), BRIX_PROTO_S3, BRIX_S3_METRIC_ADD, BRIX_S3_METRIC_INC, brix_vfs_ctx_init(), brix_vfs_probe(), brix_vfs_staged_abort(), s3_put_aio_t::final_path, s3_put_aio_t::io_errno, s3_put_aio_t::len, log, brix_vfs_stat_t::mtime, s3_put_aio_t::nwritten, brix_vfs_ctx_t::pool, s3_put_aio_t::r, s3_put_aio_t::root_canon, s3_apply_put_tagging_header(), s3_apply_put_user_metadata(), s3_commit_put(), s3_etag(), s3_put_checksum_failed(), s3_put_commit_conflict(), s3_put_finalize_empty_ok(), s3_put_finalize_error(), s3_set_header(), brix_vfs_stat_t::size, s3_put_aio_t::staged, and stat().
Referenced by s3_put_body_inner().
s3_put_aio_thread()
void s3_put_aio_thread (void * data, ngx_log_t * log)
Definition at line 42 of file put_aio.c.
References brix_http_body_write_to_fd(), brix_http_body_write_to_staged(), brix_vfs_staged_fd(), brix_vfs_staged_is_driver(), s3_put_aio_t::final_path, s3_put_aio_t::io_errno, s3_put_aio_t::len, log, s3_put_aio_t::nwritten, s3_put_aio_t::r, and s3_put_aio_t::staged.
Referenced by s3_put_body_inner().
s3_thread_pool()
ngx_thread_pool_t * s3_thread_pool (ngx_http_s3_loc_conf_t * cf)
Definition at line 22 of file put_aio.c.
References ngx_http_s3_loc_conf_t::common, ngx_http_brix_shared_conf_t::thread_pool, and ngx_http_brix_shared_conf_t::thread_pool_name.
Referenced by s3_multipart_complete_body_handler_inner(), s3_put_body_inner(), and s3_put_streaming().