nginx-xrootd: src/protocols/s3/put_stream.c File Reference
put_stream.c File Reference
#include "s3_put_internal.h"
Functions
static void s3put_stream_aws_chunked (s3put_state_t *st)
static ngx_int_t s3put_select_codec (s3put_state_t *st)
static ngx_int_t s3put_stream_offload (s3put_state_t *st)
static ngx_int_t s3put_stream_sync (s3put_state_t *st)
ngx_int_t s3put_stream_body (s3put_state_t *st)
static void s3put_emit_etag (s3put_state_t *st)
void s3put_commit_and_headers (s3put_state_t *st)
Function Documentation
s3put_commit_and_headers()
void s3put_commit_and_headers (s3put_state_t * st)
Definition at line 297 of file put_stream.c.
References s3put_state_t::body_bytes, s3put_state_t::body_mode, brix_log_safe_path(), s3put_state_t::cf, ngx_http_s3_loc_conf_t::common, s3put_state_t::fs_path, s3put_state_t::r, ngx_http_brix_shared_conf_t::root_canon, s3_apply_put_tagging_header(), s3_apply_put_user_metadata(), s3_commit_put(), s3_put_checksum_failed(), s3_put_commit_conflict(), s3_put_finalize_error(), s3_put_finalize_ok(), s3put_emit_etag(), and s3put_state_t::writer.
Referenced by s3_put_body_inner().
s3put_emit_etag()
static void s3put_emit_etag (s3put_state_t * st) static
Definition at line 267 of file put_stream.c.
References brix_vfs_probe(), s3put_state_t::cf, s3put_state_t::fs_path, brix_vfs_stat_t::mtime, s3put_state_t::r, s3_build_vfs_ctx(), s3_etag(), s3_set_header(), brix_vfs_stat_t::size, and stat().
Referenced by s3put_commit_and_headers().
s3put_select_codec()
static ngx_int_t s3put_select_codec (s3put_state_t * st) static
Definition at line 48 of file put_stream.c.
References brix_codec_desc_t::available, brix_codec_by_http_token(), brix_http_find_header(), brix_vfs_writer_abort(), brix_codec_desc_t::id, s3put_state_t::put_codec, s3put_state_t::r, s3_put_finalize_codec_error(), and s3put_state_t::writer.
Referenced by s3put_stream_body().
s3put_stream_aws_chunked()
static void s3put_stream_aws_chunked (s3put_state_t * st) static
Definition at line 19 of file put_stream.c.
References s3put_state_t::body_mode, brix_vfs_writer_abort(), s3put_state_t::cf, s3put_state_t::fs_path, s3put_state_t::r, s3_aws_chunked_has_inner_coding(), s3_put_finalize_codec_error(), s3_put_streaming(), and s3put_state_t::writer.
Referenced by s3put_stream_body().
s3put_stream_body()
ngx_int_t s3put_stream_body (s3put_state_t * st)
Definition at line 213 of file put_stream.c.
References s3put_state_t::body_bytes, s3put_state_t::body_mode, s3put_state_t::body_summary, brix_dashboard_http_start_identity(), brix_http_body_summary(), brix_vfs_writer_abort(), BRIX_XFER_DIR_WRITE, BRIX_XFER_PROTO_S3, brix_http_body_summary_t::bytes, s3put_state_t::cf, s3put_state_t::fs_path, s3put_state_t::r, s3_body_is_aws_chunked(), s3_dashboard_identity(), s3_dashboard_put_op(), s3_put_body_mode(), s3_put_finalize_error(), s3put_select_codec(), s3put_stream_aws_chunked(), s3put_stream_offload(), s3put_stream_sync(), and s3put_state_t::writer.
Referenced by s3_put_body_inner().
s3put_stream_offload()
static ngx_int_t s3put_stream_offload (s3put_state_t * st) static
Definition at line 83 of file put_stream.c.
References s3_put_aio_t::body_bytes, s3put_state_t::body_bytes, s3_put_aio_t::body_mode, s3put_state_t::body_mode, s3put_state_t::body_summary, BRIX_CODEC_IDENTITY, brix_vfs_writer_abort(), brix_http_body_summary_t::bytes, s3put_state_t::cf, ngx_http_s3_loc_conf_t::common, s3_put_aio_t::final_path, s3put_state_t::fs_path, s3_put_aio_t::len, s3put_state_t::put_codec, s3_put_aio_t::r, s3put_state_t::r, ngx_http_brix_shared_conf_t::root_canon, s3_put_aio_t::root_canon, s3_put_aio_done(), s3_put_aio_thread(), s3_put_finalize_error(), s3_thread_pool(), ngx_http_brix_shared_conf_t::thread_pool, s3_put_aio_t::writer, and s3put_state_t::writer.
Referenced by s3put_stream_body().
s3put_stream_sync()
static ngx_int_t s3put_stream_sync (s3put_state_t * st) static
Definition at line 152 of file put_stream.c.
References s3put_state_t::body_summary, BRIX_CODEC_IDENTITY, BRIX_DECODE_MAX_OUTPUT, brix_http_body_decode_to_fd(), brix_http_body_write_to_writer(), brix_vfs_writer_abort(), brix_vfs_writer_fd(), s3put_state_t::fs_path, s3put_state_t::put_codec, s3put_state_t::r, s3_put_finalize_codec_error(), s3_put_finalize_error(), and s3put_state_t::writer.
Referenced by s3put_stream_body().