nginx-xrootd: src/auth/pwd/pwd.h File Reference
pwd.h File Reference
#include <ngx_core.h>
#include <stddef.h>
#include <stdint.h>
Macros
#define kXPC_normal 1000 /* client: standard credential packet */
#define kXPC_creds 1003 /* client: (additional) credentials packet */
#define kXPS_credsreq 2001 /* server: please send credentials */
#define kXPS_none 0 /* server: done */
#define BRIX_PWD_VERSION 10100
#define kpCT_normal 0
#define kOptsClntTty 0x0080
#define BRIX_PWD_KDF_ITERS 10000
#define BRIX_PWD_HASH_LEN 24
#define BRIX_PWD_MAX_SALT 64
#define BRIX_PWD_SESSION_KEYLEN 16
Functions
ngx_int_t brix_pwd_file_lookup (const char *path, const char *user, uint8_t *salt, size_t *saltlen, uint8_t *hash, size_t *hashlen)
int brix_pwd_verify (const uint8_t *password, size_t plen, const uint8_t *salt, size_t saltlen, const uint8_t *hash, size_t hashlen)
Macro Definition Documentation
BRIX_PWD_HASH_LEN
#define BRIX_PWD_HASH_LEN 24
Definition at line 42 of file pwd.h.
BRIX_PWD_KDF_ITERS
#define BRIX_PWD_KDF_ITERS 10000
Definition at line 41 of file pwd.h.
BRIX_PWD_MAX_SALT
#define BRIX_PWD_MAX_SALT 64
Definition at line 43 of file pwd.h.
BRIX_PWD_SESSION_KEYLEN
#define BRIX_PWD_SESSION_KEYLEN 16
Definition at line 47 of file pwd.h.
BRIX_PWD_VERSION
#define BRIX_PWD_VERSION 10100
Definition at line 31 of file pwd.h.
kOptsClntTty
#define kOptsClntTty 0x0080
Definition at line 38 of file pwd.h.
kpCT_normal
#define kpCT_normal 0
Definition at line 34 of file pwd.h.
kXPC_creds
#define kXPC_creds 1003 /* client: (additional) credentials packet */
Definition at line 26 of file pwd.h.
kXPC_normal
#define kXPC_normal 1000 /* client: standard credential packet */
Definition at line 25 of file pwd.h.
kXPS_credsreq
#define kXPS_credsreq 2001 /* server: please send credentials */
Definition at line 27 of file pwd.h.
kXPS_none
#define kXPS_none 0 /* server: done */
Definition at line 28 of file pwd.h.
Function Documentation
brix_pwd_file_lookup()
ngx_int_t brix_pwd_file_lookup (const char * path, const char * user, uint8_t * salt, size_t * saltlen, uint8_t * hash, size_t * hashlen)
Definition at line 133 of file pwdfile.c.
References pwd_parse_line().
Referenced by pwd_round2().
brix_pwd_verify()
int brix_pwd_verify (const uint8_t * password, size_t plen, const uint8_t * salt, size_t saltlen, const uint8_t * hash, size_t hashlen)
Definition at line 158 of file pwdfile.c.
References BRIX_PWD_HASH_LEN, and BRIX_PWD_KDF_ITERS.
Referenced by pwd_round2().