nginx-xrootd: src/protocols/root/query/set.c File Reference
set.c File Reference
#include "core/ngx_brix_module.h"
#include <stdlib.h>
Macros
#define CMS_SPACE_PREFIX "cms.space"
#define CMS_SPACE_PREFIX_LEN (sizeof(CMS_SPACE_PREFIX) - 1)
Functions
static void brix_set_handle_cms_space (ngx_connection_t *c, const char *payload, size_t payload_len)
ngx_int_t brix_handle_set (brix_ctx_t *ctx, ngx_connection_t *c)
Macro Definition Documentation
CMS_SPACE_PREFIX
#define CMS_SPACE_PREFIX "cms.space"
Definition at line 29 of file set.c.
CMS_SPACE_PREFIX_LEN
#define CMS_SPACE_PREFIX_LEN (sizeof(CMS_SPACE_PREFIX) - 1)
Definition at line 30 of file set.c.
Function Documentation
brix_handle_set()
ngx_int_t brix_handle_set (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 108 of file set.c.
References BRIX_OP_SET, BRIX_RETURN_OK, brix_set_handle_cms_space(), c, CMS_SPACE_PREFIX, CMS_SPACE_PREFIX_LEN, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::hdr_buf, kXR_set_appid, kXR_set_clttl, xrdw_set_req_t::modifier, brix_ctx_recv_t::payload, brix_ctx_t::recv, and xrdw_set_req_unpack().
Referenced by brix_dispatch_session_opcode().
brix_set_handle_cms_space()
static void brix_set_handle_cms_space (ngx_connection_t * c, const char * payload, size_t payload_len) static
Definition at line 48 of file set.c.
References c, and CMS_SPACE_PREFIX_LEN.
Referenced by brix_handle_set().