nginx-xrootd: src/protocols/root/query/query_internal.h File Reference
query_internal.h File Reference
#include "core/ngx_brix_module.h"
#include "core/compat/checksum.h"
#include "fs/vfs/vfs.h"
Data Structures
struct brix_ckscan_aio_t
struct brix_cksum_aio_t
Macros
#define BRIX_CKSCAN_INIT_CAP (256 * 1024)
#define BRIX_PREPARE_CMD_MAX_PATHS 512
Functions
uint32_t brix_query_adler32_fd (int fd, const char *path, ngx_log_t *log)
uint32_t brix_query_crc32_fd (int fd, const char *path, ngx_log_t *log)
uint32_t brix_query_crc32_file (const ngx_str_t *root, const char *path, ngx_log_t *log)
void brix_cksum_aio_thread (void *data, ngx_log_t *log)
void brix_cksum_aio_done (ngx_event_t *ev)
int brix_ckscan_append (u_char **buf, size_t *cap, size_t *used, const char *algo, const char *hex, const char *logical)
ngx_int_t brix_ckscan_run (ngx_log_t *log, int rootfd, const char *logical, const char *algo, u_char **buf, size_t *cap, size_t *used, ngx_uint_t max_depth, ngx_uint_t max_files, uint16_t *err_code, char *err_msg, size_t err_sz)
uint32_t brix_query_adler32_file (const ngx_str_t *root, const char *path, ngx_log_t *log)
ngx_flag_t brix_query_digest_fd (int fd, const char *path, brix_checksum_alg_t alg, unsigned char *out, unsigned int *outlen, ngx_log_t *log)
ngx_flag_t brix_query_digest_file (const ngx_str_t *root, const char *path, brix_checksum_alg_t alg, unsigned char *out, unsigned int *outlen, ngx_log_t *log)
ngx_int_t brix_query_cksum (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const xrdw_query_req_t *req)
ngx_int_t brix_query_ckscan (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_query_space (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_query_fsinfo (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_query_config (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_query_stats (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_query_xattr (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_query_finfo (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_query_visa (brix_ctx_t *ctx, ngx_connection_t *c, const xrdw_query_req_t *req)
ngx_int_t brix_query_opaque (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_query_opaquf (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_query_opaqug (brix_ctx_t *ctx, ngx_connection_t *c, const xrdw_query_req_t *req)
ngx_int_t brix_query_prep_status (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Macro Definition Documentation
BRIX_CKSCAN_INIT_CAP
#define BRIX_CKSCAN_INIT_CAP (256 * 1024)
Definition at line 8 of file query_internal.h.
BRIX_PREPARE_CMD_MAX_PATHS
#define BRIX_PREPARE_CMD_MAX_PATHS 512
Definition at line 13 of file query_internal.h.
Function Documentation
brix_ckscan_append()
int brix_ckscan_append (u_char ** buf, size_t * cap, size_t * used, const char * algo, const char * hex, const char * logical)
Definition at line 21 of file checksum_ckscan_common.c.
References BRIX_MAX_PATH, hex(), and ngx_memcpy.
Referenced by ckscan_walk_file().
brix_ckscan_run()
ngx_int_t brix_ckscan_run (ngx_log_t * log, int rootfd, const char * logical, const char * algo, u_char ** buf, size_t * cap, size_t * used, ngx_uint_t max_depth, ngx_uint_t max_files, uint16_t * err_code, char * err_msg, size_t err_sz)
Definition at line 125 of file checksum_ckscan_common.c.
References ckscan_walk_ctx_t::algo, brix_vfs_walk(), BRIX_VFS_WALK_FILE, BRIX_VFS_WALK_NONE, BRIX_VFS_WALK_OTHER, ckscan_walk_ctx_t::buf, ckscan_walk_ctx_t::cap, ckscan_walk_file(), kXR_ArgInvalid, kXR_IOError, kXR_NoMemory, kXR_NotFound, log, ckscan_walk_ctx_t::log, brix_vfs_walk_opts_t::max_depth, brix_vfs_walk_opts_t::max_files, ckscan_walk_ctx_t::oom, brix_vfs_walk_opts_t::open_files, and ckscan_walk_ctx_t::used.
Referenced by brix_ckscan_aio_thread(), and brix_ckscan_sync().
brix_cksum_aio_done()
void brix_cksum_aio_done (ngx_event_t * ev)
Definition at line 69 of file checksum_qcksum_async.c.
brix_cksum_aio_thread()
void brix_cksum_aio_thread (void * data, ngx_log_t * log)
Definition at line 33 of file checksum_qcksum_async.c.
brix_query_adler32_fd()
uint32_t brix_query_adler32_fd (int fd, const char * path, ngx_log_t * log)
Definition at line 106 of file util.c.
References BRIX_CHECKSUM_ADLER32, brix_checksum_u32_fd(), and log.
Referenced by brix_query_adler32_file().
brix_query_adler32_file()
uint32_t brix_query_adler32_file (const ngx_str_t * root, const char * path, ngx_log_t * log)
Definition at line 120 of file util.c.
References brix_open_confined(), brix_query_adler32_fd(), brix_sanitize_log_string(), close(), and log.
brix_query_ckscan()
ngx_int_t brix_query_ckscan (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 158 of file checksum_ckscan_dispatch.c.
References brix_ckscan_aio_t::algo, brix_aio_post_task(), brix_auth_gate(), BRIX_AUTH_READ, brix_beneath_full_path(), brix_ckscan_aio_done(), brix_ckscan_aio_thread(), brix_ckscan_select_payload(), brix_ckscan_sync(), brix_extract_path(), BRIX_MAX_PATH, BRIX_OP_ERR, BRIX_OP_QUERY_CKSCAN, BRIX_RETURN_ERR, brix_send_error(), brix_ckscan_aio_t::c, c, ngx_stream_brix_srv_conf_t::ckscan_max_depth, ngx_stream_brix_srv_conf_t::ckscan_max_files, ngx_stream_brix_srv_conf_t::common, brix_ckscan_aio_t::conf, brix_ckscan_aio_t::ctx, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_streamid, brix_ckscan_aio_t::error_code, kXR_ArgInvalid, kXR_ArgMissing, kXR_NoMemory, brix_ckscan_aio_t::max_depth, brix_ckscan_aio_t::max_files, ngx_memcpy, PATH_MAX, brix_ctx_recv_t::payload, brix_ctx_t::recv, brix_ckscan_aio_t::resp, brix_ckscan_aio_t::resp_len, ngx_http_brix_shared_conf_t::root_canon, ngx_stream_brix_srv_conf_t::rootfd, brix_ckscan_aio_t::rootfd, brix_ckscan_aio_t::scan_logical, brix_ckscan_aio_t::streamid, ngx_http_brix_shared_conf_t::thread_pool, and brix_ctx_t::write_rc.
Referenced by brix_handle_query().
brix_query_cksum()
ngx_int_t brix_query_cksum (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const xrdw_query_req_t * req)
Definition at line 445 of file checksum_qcksum.c.
References brix_query_cksum_handle(), brix_query_cksum_path(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by battery_root(), brix_cli_cksum_main(), brix_handle_query(), brix_xrdckcheck_main(), cksum_verify(), cmd_verify(), do_check(), do_cksum(), do_cmp(), dx_probe_checksum(), entry_cksum(), op_cks(), remote_tree_visitor(), sync_cksum_match(), and xfs_getxattr().
brix_query_config()
ngx_int_t brix_query_config (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 99 of file config.c.
References brix_codec_desc_t::available, brix_codec_by_id(), BRIX_CODEC_MAX, brix_qconfig_append(), brix_qconfig_next_token(), BRIX_READV_MAXSEGS, brix_send_error(), brix_send_ok(), BRIX_SERVER_VERSION, c, brix_ctx_recv_t::cur_dlen, key, kXR_ArgMissing, ngx_stream_brix_srv_conf_t::manager_mode, brix_codec_desc_t::name, brix_ctx_recv_t::payload, ngx_stream_brix_srv_conf_t::read_compress, ngx_stream_brix_srv_conf_t::readv_segment_size, brix_ctx_t::recv, and ngx_stream_brix_srv_conf_t::write_compress.
Referenced by brix_handle_query().
brix_query_crc32_fd()
uint32_t brix_query_crc32_fd (int fd, const char * path, ngx_log_t * log)
Definition at line 192 of file util.c.
References BRIX_CHECKSUM_CRC32, brix_checksum_u32_fd(), and log.
Referenced by brix_query_crc32_file().
brix_query_crc32_file()
uint32_t brix_query_crc32_file (const ngx_str_t * root, const char * path, ngx_log_t * log)
Definition at line 206 of file util.c.
References brix_open_confined(), brix_query_crc32_fd(), brix_sanitize_log_string(), close(), and log.
brix_query_digest_fd()
ngx_flag_t brix_query_digest_fd (int fd, const char * path, brix_checksum_alg_t alg, unsigned char * out, unsigned int * outlen, ngx_log_t * log)
Definition at line 142 of file util.c.
References brix_checksum_digest_fd(), and log.
Referenced by brix_query_digest_file().
brix_query_digest_file()
ngx_flag_t brix_query_digest_file (const ngx_str_t * root, const char * path, brix_checksum_alg_t alg, unsigned char * out, unsigned int * outlen, ngx_log_t * log)
Definition at line 151 of file util.c.
References brix_open_confined(), brix_query_digest_fd(), brix_sanitize_log_string(), close(), and log.
brix_query_finfo()
ngx_int_t brix_query_finfo (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 218 of file metadata.c.
References brix_log_access(), BRIX_OP_OK, BRIX_OP_QUERY_FINFO, brix_send_ok(), and c.
Referenced by brix_handle_query().
brix_query_fsinfo()
ngx_int_t brix_query_fsinfo (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 119 of file space.c.
References brix_fs_usage_t::available_bytes, brix_fs_usage_stat(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_QUERY_FSINFO, brix_send_error(), brix_send_ok(), c, ngx_stream_brix_srv_conf_t::common, kXR_IOError, ngx_http_brix_shared_conf_t::root, brix_fs_usage_t::total_bytes, and brix_fs_usage_t::used_bytes.
Referenced by brix_handle_query().
brix_query_opaque()
ngx_int_t brix_query_opaque (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 247 of file metadata.c.
References BRIX_OP_QUERY_OPAQUE, brix_query_arg_missing(), brix_query_fsctl_unsupported(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by brix_handle_query().
brix_query_opaquf()
ngx_int_t brix_query_opaquf (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 261 of file metadata.c.
References brix_auth_gate(), BRIX_AUTH_READ, brix_beneath_full_path(), brix_extract_path(), BRIX_MAX_PATH, BRIX_OP_QUERY_OPAQUF, brix_query_arg_missing(), brix_query_fsctl_unsupported(), BRIX_RETURN_ERR, c, ngx_stream_brix_srv_conf_t::common, brix_ctx_recv_t::cur_dlen, kXR_ArgInvalid, PATH_MAX, brix_ctx_recv_t::payload, brix_ctx_t::recv, ngx_http_brix_shared_conf_t::root_canon, and brix_ctx_t::write_rc.
Referenced by brix_handle_query().
brix_query_opaqug()
ngx_int_t brix_query_opaqug (brix_ctx_t * ctx, ngx_connection_t * c, const xrdw_query_req_t * req)
Definition at line 294 of file metadata.c.
References BRIX_OP_QUERY_OPAQUG, brix_query_fctl_unsupported(), brix_query_payload_equals(), BRIX_RETURN_ERR, brix_validate_file_handle(), c, xrdw_query_req_t::fhandle, brix_ctx_t::files, kXR_FSError, and brix_file_t::path.
Referenced by brix_handle_query().
brix_query_prep_status()
ngx_int_t brix_query_prep_status (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 626 of file prepare.c.
References BRIX_AOP_STAGE, BRIX_AUTH_READ, brix_authz_check(), brix_beneath_full_path(), brix_check_token_scope(), brix_check_vo_acl_identity(), brix_extract_path(), brix_log_access(), BRIX_MAX_PATH, BRIX_PALLOC_OR_RETURN, brix_prepare_send_fail(), brix_prepare_status_char(), brix_send_error(), brix_send_ok(), brix_stage_registry_singleton(), BRIX_STAGE_REQID_LEN, brix_stage_request_find_by_path(), brix_stage_request_get(), brix_stat_beneath(), c, ngx_stream_brix_srv_conf_t::common, brix_ctx_recv_t::cur_dlen, brix_frm_conf_t::enable, ngx_stream_brix_srv_conf_t::frm, brix_ctx_t::identity, kXR_ArgInvalid, kXR_NoMemory, kXR_ok, ngx_memcpy, PATH_MAX, brix_ctx_prepare_t::paths, brix_ctx_prepare_t::paths_len, brix_ctx_recv_t::payload, brix_ctx_t::prepare, brix_ctx_t::recv, ngx_http_brix_shared_conf_t::root_canon, ngx_stream_brix_srv_conf_t::rootfd, stat(), brix_stage_request_t::status, and ngx_stream_brix_srv_conf_t::vo_rules.
Referenced by brix_handle_query().
brix_query_space()
ngx_int_t brix_query_space (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 51 of file space.c.
References brix_fs_usage_t::available_bytes, brix_fs_usage_stat(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_QUERY_SPACE, brix_qspace_format(), brix_send_error(), brix_send_ok(), c, ngx_stream_brix_srv_conf_t::common, brix_ctx_recv_t::cur_dlen, kXR_IOError, kXR_NotAuthorized, brix_ctx_recv_t::payload, brix_ctx_t::recv, ngx_http_brix_shared_conf_t::root, brix_fs_usage_t::total_bytes, and brix_fs_usage_t::used_bytes.
Referenced by brix_handle_query().
brix_query_stats()
ngx_int_t brix_query_stats (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 68 of file metadata.c.
References brix_log_access(), BRIX_OP_OK, BRIX_OP_QUERY_STATS, brix_send_ok(), BRIX_SERVER_NAME, BRIX_SERVER_VERSION, ngx_brix_srv_metrics_t::bytes_rx_total, ngx_brix_srv_metrics_t::bytes_tx_total, c, ngx_brix_srv_metrics_t::connections_active, ngx_brix_srv_metrics_t::connections_total, brix_ctx_t::metrics, and ngx_brix_srv_metrics_t::port.
Referenced by brix_handle_query().
brix_query_visa()
ngx_int_t brix_query_visa (brix_ctx_t * ctx, ngx_connection_t * c, const xrdw_query_req_t * req)
Definition at line 228 of file metadata.c.
References BRIX_OP_QUERY_VISA, brix_query_fctl_unsupported(), brix_validate_file_handle(), c, xrdw_query_req_t::fhandle, brix_ctx_t::files, and brix_file_t::path.
Referenced by brix_handle_query().
brix_query_xattr()
ngx_int_t brix_query_xattr (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 119 of file metadata.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_vfs_stat_t::atime, brix_auth_gate(), BRIX_AUTH_READ, brix_beneath_full_path(), brix_extract_path(), brix_kxr_from_errno(), brix_log_access(), BRIX_MAX_PATH, BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_QUERY_XATTR, BRIX_PROTO_ROOT, brix_send_error(), brix_send_ok(), brix_vfs_ctx_init(), brix_vfs_getxattr(), brix_vfs_listxattr(), brix_vfs_probe(), c, ngx_stream_brix_srv_conf_t::common, brix_vfs_stat_t::ctime, brix_ctx_recv_t::cur_dlen, brix_vfs_stat_t::is_directory, brix_vfs_stat_t::is_regular, kXR_ArgInvalid, kXR_ArgMissing, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, PATH_MAX, brix_ctx_recv_t::payload, brix_vfs_ctx_t::pool, brix_ctx_t::recv, ngx_http_brix_shared_conf_t::root_canon, brix_vfs_stat_t::size, and brix_ctx_t::write_rc.
Referenced by brix_handle_query().