nginx-xrootd: src/core/compat/range.c File Reference
range.c File Reference
#include "range.h"
#include "range_vector.h"
#include <string.h>
Functions
void brix_http_parse_range (const unsigned char *hdr_val, size_t hdr_len, off_t file_size, brix_http_range_t *out)
static int cr_parse_u64 (const unsigned char **p, const unsigned char *end, off_t *val)
static void cr_skip_unit_prefix (const unsigned char **cursor, const unsigned char *end)
static int cr_parse_span (const unsigned char **cursor, const unsigned char *end, brix_http_content_range_t *out)
static int cr_parse_total (const unsigned char **cursor, const unsigned char *end, brix_http_content_range_t *out)
static int cr_only_trailing_ws (const unsigned char *cursor, const unsigned char *end)
void brix_http_parse_content_range (const unsigned char *hdr_val, size_t hdr_len, brix_http_content_range_t *out)
Function Documentation
brix_http_parse_content_range()
void brix_http_parse_content_range (const unsigned char * hdr_val, size_t hdr_len, brix_http_content_range_t * out)
Definition at line 223 of file range.c.
References cr_only_trailing_ws(), cr_parse_span(), cr_parse_total(), cr_skip_unit_prefix(), brix_http_content_range_t::end, brix_http_content_range_t::present, brix_http_content_range_t::start, and brix_http_content_range_t::total.
Referenced by webdav_put_precheck().
brix_http_parse_range()
void brix_http_parse_range (const unsigned char * hdr_val, size_t hdr_len, off_t file_size, brix_http_range_t * out)
Definition at line 40 of file range.c.
References brix_range_vector_opts_t::allow_open_ended, brix_range_vector_opts_t::allow_suffix, brix_http_parse_range_vector(), brix_range_vector_opts_t::drop_unsatisfiable, brix_http_range_t::end, brix_byte_range_t::end, brix_range_vector_opts_t::max_ranges, brix_http_range_t::present, brix_http_range_t::satisfiable, brix_http_range_t::start, and brix_byte_range_t::start.
Referenced by brix_http_serve_file_ranged().
cr_only_trailing_ws()
static int cr_only_trailing_ws (const unsigned char * cursor, const unsigned char * end) static
Definition at line 198 of file range.c.
Referenced by brix_http_parse_content_range().
cr_parse_span()
static int cr_parse_span (const unsigned char ** cursor, const unsigned char * end, brix_http_content_range_t * out) static
Definition at line 139 of file range.c.
References cr_parse_u64(), brix_http_content_range_t::end, and brix_http_content_range_t::start.
Referenced by brix_http_parse_content_range().
cr_parse_total()
static int cr_parse_total (const unsigned char ** cursor, const unsigned char * end, brix_http_content_range_t * out) static
Definition at line 170 of file range.c.
References cr_parse_u64(), and brix_http_content_range_t::total.
Referenced by brix_http_parse_content_range().
cr_parse_u64()
static int cr_parse_u64 (const unsigned char ** p, const unsigned char * end, off_t * val) static
Definition at line 82 of file range.c.
References s.
Referenced by cr_parse_span(), and cr_parse_total().
cr_skip_unit_prefix()
static void cr_skip_unit_prefix (const unsigned char ** cursor, const unsigned char * end) static
Definition at line 115 of file range.c.
Referenced by brix_http_parse_content_range().