nginx-xrootd: src/core/compat/range.h File Reference
range.h File Reference
#include <stddef.h>
#include <sys/types.h>
Data Structures
struct brix_http_range_t
struct brix_http_content_range_t
Functions
void brix_http_parse_range (const unsigned char *hdr_val, size_t hdr_len, off_t file_size, brix_http_range_t *out)
void brix_http_parse_content_range (const unsigned char *hdr_val, size_t hdr_len, brix_http_content_range_t *out)
Function Documentation
brix_http_parse_content_range()
void brix_http_parse_content_range (const unsigned char * hdr_val, size_t hdr_len, brix_http_content_range_t * out)
Definition at line 229 of file range.c.
References cr_only_trailing_ws(), cr_parse_span(), cr_parse_total(), cr_skip_unit_prefix(), brix_http_content_range_t::end, brix_http_content_range_t::present, brix_http_content_range_t::start, and brix_http_content_range_t::total.
Referenced by webdav_put_precheck().
brix_http_parse_range()
void brix_http_parse_range (const unsigned char * hdr_val, size_t hdr_len, off_t file_size, brix_http_range_t * out)
Definition at line 40 of file range.c.
References brix_range_vector_opts_t::allow_open_ended, brix_range_vector_opts_t::allow_suffix, brix_http_parse_range_vector(), BRIX_RANGE_FAIL_NONE, BRIX_RANGE_FAIL_UNSATISFIABLE, brix_range_vector_opts_t::drop_unsatisfiable, brix_http_range_t::end, brix_byte_range_t::end, brix_range_vector_opts_t::max_ranges, brix_http_range_t::present, brix_http_range_t::satisfiable, brix_http_range_t::start, and brix_byte_range_t::start.
Referenced by brix_http_serve_file_ranged().