nginx-xrootd: src/core/compat/range_vector.h File Reference
range_vector.h File Reference
#include <ngx_http.h>
Data Structures
struct brix_byte_range_t
struct brix_range_vector_opts_t
Functions
ngx_int_t brix_http_parse_range_vector (const u_char *data, size_t len, off_t file_size, const brix_range_vector_opts_t *opts, brix_byte_range_t *ranges, ngx_uint_t *nranges)
ngx_int_t brix_range_vector_validate_total (const brix_byte_range_t *ranges, ngx_uint_t nranges, off_t max_total_bytes, off_t *total_out)
ngx_uint_t brix_range_vector_next_coalesced_run (const brix_byte_range_t *ranges, ngx_uint_t nranges, ngx_uint_t start_index, ngx_uint_t max_iov)
Function Documentation
brix_http_parse_range_vector()
ngx_int_t brix_http_parse_range_vector (const u_char * data, size_t len, off_t file_size, const brix_range_vector_opts_t * opts, brix_byte_range_t * ranges, ngx_uint_t * nranges)
Definition at line 105 of file range_vector.c.
References range_vector_parse_one().
Referenced by brix_http_parse_range(), and xrdhttp_handle_multipart_get().
brix_range_vector_next_coalesced_run()
ngx_uint_t brix_range_vector_next_coalesced_run (const brix_byte_range_t * ranges, ngx_uint_t nranges, ngx_uint_t start_index, ngx_uint_t max_iov)
Definition at line 173 of file range_vector.c.
Referenced by brix_readv_read_segments().
brix_range_vector_validate_total()
ngx_int_t brix_range_vector_validate_total (const brix_byte_range_t * ranges, ngx_uint_t nranges, off_t max_total_bytes, off_t * total_out)
Definition at line 145 of file range_vector.c.
References brix_byte_range_t::end, and brix_byte_range_t::start.