nginx-xrootd: src/net/ratelimit/ratelimit_keys_rules.c File Reference
ratelimit_keys_rules.c File Reference
#include "ratelimit.h"
#include "protocols/webdav/webdav.h"
#include "ratelimit_keys_internal.h"
Data Structures
struct rl_rule_parse_t
Functions
static char * rl_rule_push (ngx_conf_t *cf, ngx_command_t *cmd, void *conf, brix_rl_rule_t **out_rule)
static char * rl_rule_bind_zone (ngx_conf_t *cf, brix_rl_rule_t *rule, ngx_str_t *zone_name, const char *who)
static char * rl_rule_set_rate (ngx_conf_t *cf, ngx_str_t *r, int is_bw, brix_rl_rule_t *rule)
static char * rl_rule_set_burst (ngx_conf_t *cf, ngx_str_t *b, int is_bw, brix_rl_rule_t *rule)
static char * rl_rule_parse_token (ngx_conf_t *cf, ngx_str_t *a, int is_bw, rl_rule_parse_t *st)
static char * rl_add_rule (ngx_conf_t *cf, ngx_command_t *cmd, void *conf, int is_bw)
char * brix_rl_rule_directive (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_rl_bw_directive (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static char * rl_conc_parse_token (ngx_conf_t *cf, ngx_str_t *a, rl_rule_parse_t *st)
char * brix_rl_conc_directive (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Function Documentation
brix_rl_bw_directive()
char * brix_rl_bw_directive (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 272 of file ratelimit_keys_rules.c.
References rl_add_rule().
brix_rl_conc_directive()
char * brix_rl_conc_directive (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 328 of file ratelimit_keys_rules.c.
References rl_rule_parse_t::have_extra, rl_rule_parse_t::have_key, rl_conc_parse_token(), rl_rule_bind_zone(), rl_rule_push(), rl_rule_parse_t::rule, and rl_rule_parse_t::zone_name.
brix_rl_rule_directive()
char * brix_rl_rule_directive (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 266 of file ratelimit_keys_rules.c.
References rl_add_rule().
rl_add_rule()
static char * rl_add_rule (ngx_conf_t * cf, ngx_command_t * cmd, void * conf, int is_bw) static
Definition at line 232 of file ratelimit_keys_rules.c.
References brix_rl_rule_t::bw_burst, brix_rl_rule_t::bw_rate, rl_rule_parse_t::have_extra, rl_rule_parse_t::have_key, brix_rl_rule_t::req_burst, rl_rule_bind_zone(), rl_rule_parse_token(), rl_rule_push(), rl_rule_parse_t::rule, and rl_rule_parse_t::zone_name.
Referenced by brix_rl_bw_directive(), and brix_rl_rule_directive().
rl_conc_parse_token()
static char * rl_conc_parse_token (ngx_conf_t * cf, ngx_str_t * a, rl_rule_parse_t * st) static
Definition at line 299 of file ratelimit_keys_rules.c.
References rl_rule_parse_t::have_extra, rl_rule_parse_t::have_key, brix_rl_rule_t::req_conc, rl_parse_key(), rl_rule_parse_t::rule, and rl_rule_parse_t::zone_name.
Referenced by brix_rl_conc_directive().
rl_rule_bind_zone()
static char * rl_rule_bind_zone (ngx_conf_t * cf, brix_rl_rule_t * rule, ngx_str_t * zone_name, const char * who) static
Definition at line 81 of file ratelimit_keys_rules.c.
References brix_rl_zone_get(), and brix_rl_rule_t::zone.
Referenced by brix_rl_conc_directive(), and rl_add_rule().
rl_rule_parse_token()
static char * rl_rule_parse_token (ngx_conf_t * cf, ngx_str_t * a, int is_bw, rl_rule_parse_t * st) static
Definition at line 186 of file ratelimit_keys_rules.c.
References rl_rule_parse_t::have_extra, rl_rule_parse_t::have_key, brix_rl_rule_t::nodelay, rl_parse_key(), rl_rule_set_burst(), rl_rule_set_rate(), rl_rule_parse_t::rule, and rl_rule_parse_t::zone_name.
Referenced by rl_add_rule().
rl_rule_push()
static char * rl_rule_push (ngx_conf_t * cf, ngx_command_t * cmd, void * conf, brix_rl_rule_t ** out_rule) static
Definition at line 50 of file ratelimit_keys_rules.c.
Referenced by brix_rl_conc_directive(), and rl_add_rule().
rl_rule_set_burst()
static char * rl_rule_set_burst (ngx_conf_t * cf, ngx_str_t * b, int is_bw, brix_rl_rule_t * rule) static
Definition at line 148 of file ratelimit_keys_rules.c.
References brix_rl_rule_t::bw_burst, brix_rl_rule_t::req_burst, and rl_parse_size().
Referenced by rl_rule_parse_token().
rl_rule_set_rate()
static char * rl_rule_set_rate (ngx_conf_t * cf, ngx_str_t * r, int is_bw, brix_rl_rule_t * rule) static
Definition at line 107 of file ratelimit_keys_rules.c.
References BRIX_RL_REQ_SCALE, brix_rl_rule_t::bw_rate, brix_rl_rule_t::req_rate, rl_parse_bw_rate(), and rl_parse_req_rate().
Referenced by rl_rule_parse_token().