nginx-xrootd: src/net/ratelimit/ratelimit_stream.c File Reference
ratelimit_stream.c File Reference
#include "ratelimit.h"
#include "protocols/root/response/response.h"
#include "observability/metrics/metrics_macros.h"
Macros
#define BRIX_RL_METRIC_INC(field)
Functions
static int rl_op_rate_limited (uint16_t reqid)
static int rl_op_path_bearing (uint16_t reqid)
static void rl_request_path (brix_ctx_t *ctx, char *buf, size_t bufsz)
ngx_int_t brix_rl_stream_gate (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
void brix_rl_charge_ctx (brix_ctx_t *ctx, size_t nbytes)
void brix_rl_release_ctx (brix_ctx_t *ctx)
Macro Definition Documentation
BRIX_RL_METRIC_INC
#define BRIX_RL_METRIC_INC (field)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_m = brix_metrics_shared();                  \
        if (_m != NULL) { (void) ngx_atomic_fetch_add(&_m->field, 1); }      \
    } while (0)
Definition at line 16 of file ratelimit_stream.c.
Function Documentation
brix_rl_charge_ctx()
void brix_rl_charge_ctx (brix_ctx_t * ctx, size_t nbytes)
Definition at line 187 of file ratelimit_stream.c.
References brix_rl_charge_bytes(), brix_ctx_rl_t::bw_key, brix_ctx_rl_t::bw_rule, and brix_ctx_t::rl.
Referenced by brix_handle_pgread(), brix_handle_pgwrite(), brix_handle_write(), brix_read_compressed(), brix_read_serve_sendfile(), and brix_write_compressed().
brix_rl_release_ctx()
void brix_rl_release_ctx (brix_ctx_t * ctx)
Definition at line 196 of file ratelimit_stream.c.
References brix_rl_conc_release(), brix_ctx_rl_t::conc_key, brix_ctx_rl_t::conc_rule, and brix_ctx_t::rl.
Referenced by brix_on_disconnect().
brix_rl_stream_gate()
ngx_int_t brix_rl_stream_gate (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 73 of file ratelimit_stream.c.
References brix_rl_bw_check(), brix_rl_check(), brix_rl_conc_acquire(), BRIX_RL_KEY_LEN, brix_rl_key_stream(), BRIX_RL_KEY_VOLUME, BRIX_RL_METRIC_INC, BRIX_RL_RULE_CACHE_MAX, brix_send_wait(), brix_ctx_rl_t::bw_key, brix_ctx_rl_t::bw_rule, c, brix_ctx_rl_t::conc_key, brix_ctx_rl_t::conc_rule, brix_ctx_recv_t::cur_reqid, key, brix_ctx_rl_t::key_cache, brix_ctx_rl_t::key_cache_valid, brix_rl_rule_t::key_type, brix_ctx_t::recv, brix_ctx_t::rl, rl_op_rate_limited(), rl_request_path(), and ngx_stream_brix_srv_conf_t::rl_rules.
Referenced by brix_dispatch().
rl_op_path_bearing()
static int rl_op_path_bearing (uint16_t reqid) static
Definition at line 40 of file ratelimit_stream.c.
References kXR_dirlist, kXR_locate, and kXR_open.
Referenced by rl_request_path().
rl_op_rate_limited()
static int rl_op_rate_limited (uint16_t reqid) static
Definition at line 25 of file ratelimit_stream.c.
References kXR_dirlist, kXR_locate, kXR_open, kXR_pgread, kXR_pgwrite, kXR_read, kXR_readv, kXR_write, and kXR_writev.
Referenced by brix_rl_stream_gate().
rl_request_path()
static void rl_request_path (brix_ctx_t * ctx, char * buf, size_t bufsz) static
Definition at line 53 of file ratelimit_stream.c.
References brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, brix_ctx_recv_t::payload, brix_ctx_t::recv, and rl_op_path_bearing().
Referenced by brix_rl_stream_gate().