nginx-xrootd: src/net/ratelimit/ratelimit_keys.c File Reference
ratelimit_keys.c File Reference
#include "ratelimit.h"
#include "protocols/webdav/webdav.h"
Functions
static void rl_key_dn_hash (const u_char *dn, size_t dn_len, char *out, size_t out_sz)
ngx_int_t brix_rl_key_stream (brix_rl_rule_t *rule, brix_ctx_t *ctx, const char *path, char *out, size_t out_sz)
ngx_int_t brix_rl_key_http (brix_rl_rule_t *rule, ngx_http_request_t *r, void *wctx_v, const char *path, char *out, size_t out_sz)
static ngx_int_t rl_parse_key (ngx_conf_t *cf, ngx_str_t *v, brix_rl_rule_t *rule)
static ngx_int_t rl_parse_req_rate (ngx_str_t *v)
static ssize_t rl_parse_bw_rate (ngx_str_t *v)
static ssize_t rl_parse_size (ngx_str_t *v)
char * brix_rl_zone_directive (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static char * rl_add_rule (ngx_conf_t *cf, ngx_command_t *cmd, void *conf, int is_bw)
char * brix_rl_rule_directive (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_rl_bw_directive (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_rl_conc_directive (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Function Documentation
brix_rl_bw_directive()
char * brix_rl_bw_directive (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 441 of file ratelimit_keys.c.
References rl_add_rule().
brix_rl_conc_directive()
char * brix_rl_conc_directive (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 455 of file ratelimit_keys.c.
References brix_rl_zone_get(), brix_rl_rule_t::req_conc, rl_parse_key(), and brix_rl_rule_t::zone.
brix_rl_key_http()
ngx_int_t brix_rl_key_http (brix_rl_rule_t * rule, ngx_http_request_t * r, void * wctx_v, const char * path, char * out, size_t out_sz)
Definition at line 110 of file ratelimit_keys.c.
References BRIX_RL_KEY_DN, BRIX_RL_KEY_IP, BRIX_RL_KEY_ISSUER, BRIX_RL_KEY_VO, BRIX_RL_KEY_VOLUME, brix_identity_t::dn, ngx_http_brix_webdav_req_ctx_t::dn, ngx_http_brix_webdav_req_ctx_t::identity, brix_identity_t::issuer, brix_rl_rule_t::key_match, brix_rl_rule_t::key_type, rl_key_dn_hash(), and brix_identity_t::vo_csv.
Referenced by brix_rl_http_access_handler().
brix_rl_key_stream()
ngx_int_t brix_rl_key_stream (brix_rl_rule_t * rule, brix_ctx_t * ctx, const char * path, char * out, size_t out_sz)
Definition at line 44 of file ratelimit_keys.c.
References BRIX_RL_KEY_DN, BRIX_RL_KEY_IP, BRIX_RL_KEY_ISSUER, BRIX_RL_KEY_VO, BRIX_RL_KEY_VOLUME, brix_ctx_login_t::dn, brix_ctx_t::identity, brix_identity_t::issuer, brix_rl_rule_t::key_match, brix_rl_rule_t::key_type, brix_ctx_t::login, brix_ctx_login_t::peer_ip, brix_ctx_login_t::primary_vo, and rl_key_dn_hash().
Referenced by brix_rl_stream_gate().
brix_rl_rule_directive()
char * brix_rl_rule_directive (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 435 of file ratelimit_keys.c.
References rl_add_rule().
brix_rl_zone_directive()
char * brix_rl_zone_directive (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 258 of file ratelimit_keys.c.
References brix_rl_zone_add(), name, and rl_parse_size().
rl_add_rule()
static char * rl_add_rule (ngx_conf_t * cf, ngx_command_t * cmd, void * conf, int is_bw) static
Definition at line 320 of file ratelimit_keys.c.
References brix_rl_zone_get(), brix_rl_rule_t::bw_burst, brix_rl_rule_t::bw_rate, brix_rl_rule_t::nodelay, brix_rl_rule_t::req_burst, brix_rl_rule_t::req_rate, rl_parse_bw_rate(), rl_parse_key(), rl_parse_req_rate(), rl_parse_size(), and brix_rl_rule_t::zone.
Referenced by brix_rl_bw_directive(), and brix_rl_rule_directive().
rl_key_dn_hash()
static void rl_key_dn_hash (const u_char * dn, size_t dn_len, char * out, size_t out_sz) static
Definition at line 28 of file ratelimit_keys.c.
References brix_rl_hash().
Referenced by brix_rl_key_http(), and brix_rl_key_stream().
rl_parse_bw_rate()
static ssize_t rl_parse_bw_rate (ngx_str_t * v) static
Definition at line 226 of file ratelimit_keys.c.
Referenced by rl_add_rule().
rl_parse_key()
static ngx_int_t rl_parse_key (ngx_conf_t * cf, ngx_str_t * v, brix_rl_rule_t * rule) static
Definition at line 176 of file ratelimit_keys.c.
References BRIX_RL_KEY_DN, BRIX_RL_KEY_IP, BRIX_RL_KEY_ISSUER, BRIX_RL_KEY_VO, BRIX_RL_KEY_VOLUME, brix_rl_rule_t::key_match, and brix_rl_rule_t::key_type.
Referenced by brix_rl_conc_directive(), and rl_add_rule().
rl_parse_req_rate()
static ngx_int_t rl_parse_req_rate (ngx_str_t * v) static
Definition at line 214 of file ratelimit_keys.c.
Referenced by rl_add_rule().
rl_parse_size()
static ssize_t rl_parse_size (ngx_str_t * v) static
Definition at line 250 of file ratelimit_keys.c.
Referenced by brix_rl_zone_directive(), and rl_add_rule().