nginx-xrootd: src/net/ratelimit/ratelimit_http.c File Reference
ratelimit_http.c File Reference
#include "ratelimit.h"
#include "protocols/webdav/webdav.h"
#include "core/http/http_headers.h"
#include "observability/metrics/metrics_macros.h"
Macros
#define BRIX_RL_PATH_LEN 1024
#define BRIX_RL_METRIC_INC(field)
Functions
static ngx_int_t rl_reject (ngx_http_request_t *r, brix_rl_rule_t *rule, uint32_t wait_sec, const char *key_str)
static ngx_http_brix_webdav_req_ctx_t * rl_ensure_ctx (ngx_http_request_t *r, ngx_http_brix_webdav_req_ctx_t *wctx)
static void rl_resolve_volume_path (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *lcf, const brix_rl_rule_t *rule, char *path, int *have_path)
static ngx_int_t rl_check_bw (ngx_http_request_t *r, brix_rl_rule_t *rule, const char *key_str, ngx_http_brix_webdav_req_ctx_t **wctx_p)
static ngx_int_t rl_check_conc (ngx_http_request_t *r, brix_rl_rule_t *rule, const char *key_str, ngx_http_brix_webdav_req_ctx_t **wctx_p, int *conc_held)
static ngx_int_t rl_apply_rule (ngx_http_request_t *r, brix_rl_rule_t *rule, const char *key_str, ngx_http_brix_webdav_req_ctx_t **wctx_p, int *conc_held)
ngx_int_t brix_rl_http_access_handler (ngx_http_request_t *r)
ngx_int_t brix_rl_http_log_handler (ngx_http_request_t *r)
Macro Definition Documentation
BRIX_RL_METRIC_INC
#define BRIX_RL_METRIC_INC (field)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_m = brix_metrics_shared();                  \
        if (_m != NULL) { (void) ngx_atomic_fetch_add(&_m->field, 1); }      \
    } while (0)
Definition at line 20 of file ratelimit_http.c.
BRIX_RL_PATH_LEN
#define BRIX_RL_PATH_LEN 1024
Definition at line 18 of file ratelimit_http.c.
Function Documentation
brix_rl_http_access_handler()
ngx_int_t brix_rl_http_access_handler (ngx_http_request_t * r)
Definition at line 195 of file ratelimit_http.c.
References brix_rl_key_http(), BRIX_RL_KEY_LEN, BRIX_RL_PATH_LEN, rl_key_req_t::id, ngx_http_brix_webdav_req_ctx_t::identity, rl_key_req_t::ip, ngx_http_brix_webdav_module, rl_key_req_t::path, rl_apply_rule(), rl_resolve_volume_path(), ngx_http_brix_webdav_loc_conf_t::rl_rules, and rl_key_req_t::wctx.
Referenced by webdav_postconf_install_handlers().
brix_rl_http_log_handler()
ngx_int_t brix_rl_http_log_handler (ngx_http_request_t * r)
Definition at line 254 of file ratelimit_http.c.
References brix_rl_charge_bytes(), brix_rl_conc_release(), ngx_http_brix_webdav_module, ngx_http_brix_webdav_req_ctx_t::rl_bw_rule, ngx_http_brix_webdav_req_ctx_t::rl_conc_key, ngx_http_brix_webdav_req_ctx_t::rl_conc_rule, and ngx_http_brix_webdav_req_ctx_t::rl_key_str.
Referenced by webdav_postconf_install_handlers().
rl_apply_rule()
static ngx_int_t rl_apply_rule (ngx_http_request_t * r, brix_rl_rule_t * rule, const char * key_str, ngx_http_brix_webdav_req_ctx_t ** wctx_p, int * conc_held) static
Definition at line 173 of file ratelimit_http.c.
References brix_rl_check(), brix_rl_rule_t::req_rate, rl_check_bw(), rl_check_conc(), and rl_reject().
Referenced by brix_rl_http_access_handler().
rl_check_bw()
static ngx_int_t rl_check_bw (ngx_http_request_t * r, brix_rl_rule_t * rule, const char * key_str, ngx_http_brix_webdav_req_ctx_t ** wctx_p) static
Definition at line 104 of file ratelimit_http.c.
References brix_rl_bw_check(), brix_rl_rule_t::bw_rate, ngx_http_brix_webdav_req_ctx_t::rl_bw_rule, rl_ensure_ctx(), ngx_http_brix_webdav_req_ctx_t::rl_key_str, and rl_reject().
Referenced by rl_apply_rule().
rl_check_conc()
static ngx_int_t rl_check_conc (ngx_http_request_t * r, brix_rl_rule_t * rule, const char * key_str, ngx_http_brix_webdav_req_ctx_t ** wctx_p, int * conc_held) static
Definition at line 137 of file ratelimit_http.c.
References brix_rl_conc_acquire(), brix_rl_conc_release(), brix_rl_rule_t::req_conc, ngx_http_brix_webdav_req_ctx_t::rl_conc_key, ngx_http_brix_webdav_req_ctx_t::rl_conc_rule, rl_ensure_ctx(), and rl_reject().
Referenced by rl_apply_rule().
rl_ensure_ctx()
static ngx_http_brix_webdav_req_ctx_t * rl_ensure_ctx (ngx_http_request_t * r, ngx_http_brix_webdav_req_ctx_t * wctx) static
Definition at line 57 of file ratelimit_http.c.
References ngx_http_brix_webdav_module, and ngx_pcalloc().
Referenced by rl_check_bw(), and rl_check_conc().
rl_reject()
static ngx_int_t rl_reject (ngx_http_request_t * r, brix_rl_rule_t * rule, uint32_t wait_sec, const char * key_str) static
Definition at line 28 of file ratelimit_http.c.
References brix_http_set_header(), BRIX_RL_METRIC_INC, and brix_rl_rule_t::nodelay.
Referenced by rl_apply_rule(), rl_check_bw(), and rl_check_conc().
rl_resolve_volume_path()
static void rl_resolve_volume_path (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * lcf, const brix_rl_rule_t * rule, char * path, int * have_path) static
Definition at line 79 of file ratelimit_http.c.
References BRIX_RL_KEY_VOLUME, BRIX_RL_PATH_LEN, ngx_http_brix_webdav_loc_conf_t::common, brix_rl_rule_t::key_type, ngx_http_brix_webdav_resolve_path(), and ngx_http_brix_shared_conf_t::root_canon.
Referenced by brix_rl_http_access_handler().