nginx-xrootd: src/net/ratelimit/ratelimit_keys_parse.c File Reference
ratelimit_keys_parse.c File Reference
#include "ratelimit.h"
#include "protocols/webdav/webdav.h"
#include "ratelimit_keys_internal.h"
Functions
ngx_int_t rl_parse_key (ngx_conf_t *cf, ngx_str_t *v, brix_rl_rule_t *rule)
ngx_int_t rl_parse_req_rate (ngx_str_t *v)
ssize_t rl_parse_bw_rate (ngx_str_t *v)
ssize_t rl_parse_size (ngx_str_t *v)
char * brix_rl_zone_directive (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Function Documentation
brix_rl_zone_directive()
char * brix_rl_zone_directive (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 101 of file ratelimit_keys_parse.c.
References brix_rl_zone_add(), name, and rl_parse_size().
rl_parse_bw_rate()
ssize_t rl_parse_bw_rate (ngx_str_t * v)
Definition at line 69 of file ratelimit_keys_parse.c.
Referenced by rl_rule_set_rate().
rl_parse_key()
ngx_int_t rl_parse_key (ngx_conf_t * cf, ngx_str_t * v, brix_rl_rule_t * rule)
Definition at line 19 of file ratelimit_keys_parse.c.
References BRIX_RL_KEY_DN, BRIX_RL_KEY_IP, BRIX_RL_KEY_ISSUER, BRIX_RL_KEY_VO, BRIX_RL_KEY_VOLUME, brix_rl_rule_t::key_match, and brix_rl_rule_t::key_type.
Referenced by rl_conc_parse_token(), and rl_rule_parse_token().
rl_parse_req_rate()
ngx_int_t rl_parse_req_rate (ngx_str_t * v)
Definition at line 57 of file ratelimit_keys_parse.c.
Referenced by rl_rule_set_rate().
rl_parse_size()
ssize_t rl_parse_size (ngx_str_t * v)
Definition at line 93 of file ratelimit_keys_parse.c.
Referenced by brix_rl_zone_directive(), and rl_rule_set_burst().