nginx-xrootd: src/net/ratelimit/ratelimit.h File Reference
ratelimit.h File Reference
#include "core/ngx_brix_module.h"
#include <ngx_http.h>
Data Structures
struct brix_rl_node_t
struct brix_rl_shctx_t
struct brix_rl_zone_t
struct brix_rl_rule_t
struct brix_rl_snapshot_entry_t
Macros
#define BRIX_RL_KEY_LEN 128 /* max bytes of the human-readable key string */
Enumerations
enum brix_rl_key_type_t {
BRIX_RL_KEY_VO = 0 , BRIX_RL_KEY_ISSUER = 1 , BRIX_RL_KEY_IP = 2 , BRIX_RL_KEY_DN = 3 ,
BRIX_RL_KEY_VOLUME = 4
}
Functions
ngx_int_t brix_rl_zone_add (ngx_conf_t *cf, ngx_str_t *name, size_t size, brix_rl_zone_t **out)
brix_rl_zone_t * brix_rl_zone_get (ngx_str_t *name)
ngx_uint_t brix_rl_zones_all (brix_rl_zone_t **out, ngx_uint_t max)
void brix_rl_zone_reset_gauges (brix_rl_shctx_t *sh)
uint32_t brix_rl_hash (const char *key, size_t len)
brix_rl_node_t * brix_rl_lookup_locked (brix_rl_zone_t *zone, uint32_t hash, const char *key_str, size_t len)
brix_rl_node_t * brix_rl_create_locked (brix_rl_zone_t *zone, uint32_t hash, const char *key_str, size_t len)
ngx_int_t brix_rl_check (brix_rl_rule_t *rule, const char *key_str, uint32_t *wait_seconds)
ngx_int_t brix_rl_bw_check (brix_rl_rule_t *rule, const char *key_str, uint32_t *wait_seconds)
void brix_rl_charge_bytes (brix_rl_rule_t *rule, const char *key_str, size_t nbytes)
ngx_int_t brix_rl_conc_acquire (brix_rl_rule_t *rule, const char *key_str)
void brix_rl_conc_release (brix_rl_rule_t *rule, const char *key_str)
ngx_int_t brix_rl_snapshot (brix_rl_zone_t *zone, brix_rl_snapshot_entry_t *out, ngx_uint_t max, ngx_uint_t *count)
ngx_int_t brix_rl_key_stream (brix_rl_rule_t *rule, brix_ctx_t *ctx, const char *path, char *out, size_t out_sz)
ngx_int_t brix_rl_key_http (brix_rl_rule_t *rule, ngx_http_request_t *r, void *wctx, const char *path, char *out, size_t out_sz)
char * brix_rl_zone_directive (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_rl_rule_directive (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_rl_bw_directive (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_rl_conc_directive (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
ngx_int_t brix_rl_http_access_handler (ngx_http_request_t *r)
ngx_int_t brix_rl_http_log_handler (ngx_http_request_t *r)
ngx_int_t brix_rl_stream_gate (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
void brix_rl_charge_ctx (brix_ctx_t *ctx, size_t nbytes)
void brix_rl_release_ctx (brix_ctx_t *ctx)
Macro Definition Documentation
BRIX_RL_KEY_LEN
#define BRIX_RL_KEY_LEN 128 /* max bytes of the human-readable key string */
Definition at line 43 of file ratelimit.h.
Enumeration Type Documentation
brix_rl_key_type_t
enum brix_rl_key_type_t
Enumerator
BRIX_RL_KEY_VO
BRIX_RL_KEY_ISSUER
BRIX_RL_KEY_IP
BRIX_RL_KEY_DN
BRIX_RL_KEY_VOLUME
Definition at line 35 of file ratelimit.h.
Function Documentation
brix_rl_bw_check()
ngx_int_t brix_rl_bw_check (brix_rl_rule_t * rule, const char * key_str, uint32_t * wait_seconds)
Definition at line 159 of file ratelimit.c.
References brix_rl_hash(), brix_rl_lookup_locked(), brix_rl_rule_t::bw_burst, brix_rl_node_t::bw_excess, brix_rl_rule_t::bw_rate, brix_rl_node_t::last, brix_rl_zone_t::sh, brix_rl_zone_t::shpool, brix_rl_node_t::throttle_count, and brix_rl_rule_t::zone.
Referenced by brix_rl_http_access_handler(), and brix_rl_stream_gate().
brix_rl_bw_directive()
char * brix_rl_bw_directive (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 441 of file ratelimit_keys.c.
References rl_add_rule().
brix_rl_charge_bytes()
void brix_rl_charge_bytes (brix_rl_rule_t * rule, const char * key_str, size_t nbytes)
Definition at line 205 of file ratelimit.c.
References brix_rl_create_locked(), brix_rl_hash(), brix_rl_lookup_locked(), brix_rl_node_t::bw_excess, brix_rl_rule_t::bw_rate, brix_rl_node_t::bytes_total, brix_rl_node_t::last, brix_rl_zone_t::sh, brix_rl_zone_t::shpool, and brix_rl_rule_t::zone.
Referenced by brix_rl_charge_ctx(), and brix_rl_http_log_handler().
brix_rl_charge_ctx()
void brix_rl_charge_ctx (brix_ctx_t * ctx, size_t nbytes)
Definition at line 187 of file ratelimit_stream.c.
brix_rl_check()
ngx_int_t brix_rl_check (brix_rl_rule_t * rule, const char * key_str, uint32_t * wait_seconds)
Definition at line 19 of file ratelimit.c.
References brix_rl_create_locked(), brix_rl_hash(), brix_rl_lookup_locked(), brix_rl_node_t::last, brix_rl_rule_t::req_burst, brix_rl_node_t::req_excess, brix_rl_rule_t::req_rate, brix_rl_node_t::req_total, brix_rl_zone_t::sh, brix_rl_zone_t::shpool, brix_rl_node_t::throttle_count, and brix_rl_rule_t::zone.
Referenced by brix_rl_http_access_handler(), and brix_rl_stream_gate().
brix_rl_conc_acquire()
ngx_int_t brix_rl_conc_acquire (brix_rl_rule_t * rule, const char * key_str)
Definition at line 89 of file ratelimit.c.
References brix_rl_create_locked(), brix_rl_hash(), brix_rl_lookup_locked(), brix_rl_node_t::in_flight, brix_rl_node_t::last, brix_rl_rule_t::req_conc, brix_rl_node_t::req_total, brix_rl_zone_t::sh, brix_rl_zone_t::shpool, brix_rl_node_t::throttle_count, and brix_rl_rule_t::zone.
Referenced by brix_rl_http_access_handler(), and brix_rl_stream_gate().
brix_rl_conc_directive()
char * brix_rl_conc_directive (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 455 of file ratelimit_keys.c.
References brix_rl_zone_get(), brix_rl_rule_t::req_conc, rl_parse_key(), and brix_rl_rule_t::zone.
brix_rl_conc_release()
void brix_rl_conc_release (brix_rl_rule_t * rule, const char * key_str)
Definition at line 129 of file ratelimit.c.
References brix_rl_hash(), brix_rl_lookup_locked(), brix_rl_node_t::in_flight, brix_rl_rule_t::req_conc, brix_rl_zone_t::sh, brix_rl_zone_t::shpool, and brix_rl_rule_t::zone.
Referenced by brix_rl_http_access_handler(), brix_rl_http_log_handler(), and brix_rl_release_ctx().
brix_rl_create_locked()
brix_rl_node_t * brix_rl_create_locked (brix_rl_zone_t * zone, uint32_t hash, const char * key_str, size_t len)
Definition at line 317 of file ratelimit_zone.c.
References brix_rl_evict_oldest_locked(), BRIX_RL_METRIC_INC, brix_rl_node_t::key_str, brix_rl_node_t::len, ngx_memcpy, brix_rl_node_t::node, brix_rl_node_t::queue, brix_rl_shctx_t::queue, brix_rl_shctx_t::rbtree, brix_rl_zone_t::sh, and brix_rl_zone_t::shpool.
Referenced by brix_rl_charge_bytes(), brix_rl_check(), brix_rl_conc_acquire(), and throttle_node_locked().
brix_rl_hash()
uint32_t brix_rl_hash (const char * key, size_t len)
Definition at line 36 of file ratelimit_zone.c.
References key.
Referenced by brix_rl_bw_check(), brix_rl_charge_bytes(), brix_rl_check(), brix_rl_conc_acquire(), brix_rl_conc_release(), brix_throttle_ioload_over(), brix_throttle_open_dec(), rl_key_dn_hash(), and throttle_node_locked().
brix_rl_http_access_handler()
ngx_int_t brix_rl_http_access_handler (ngx_http_request_t * r)
Definition at line 43 of file ratelimit_http.c.
References brix_rl_bw_check(), brix_rl_check(), brix_rl_conc_acquire(), brix_rl_conc_release(), brix_rl_key_http(), BRIX_RL_KEY_LEN, BRIX_RL_KEY_VOLUME, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), ngx_pcalloc(), ngx_http_brix_webdav_req_ctx_t::rl_bw_rule, ngx_http_brix_webdav_req_ctx_t::rl_conc_key, ngx_http_brix_webdav_req_ctx_t::rl_conc_rule, ngx_http_brix_webdav_req_ctx_t::rl_key_str, rl_reject(), ngx_http_brix_webdav_loc_conf_t::rl_rules, ngx_http_brix_shared_conf_t::root_canon, and ngx_http_brix_webdav_loc_conf_t::upstream_proxy.
Referenced by ngx_http_brix_webdav_postconfiguration().
brix_rl_http_log_handler()
ngx_int_t brix_rl_http_log_handler (ngx_http_request_t * r)
Definition at line 157 of file ratelimit_http.c.
References brix_rl_charge_bytes(), brix_rl_conc_release(), ngx_http_brix_webdav_module, ngx_http_brix_webdav_req_ctx_t::rl_bw_rule, ngx_http_brix_webdav_req_ctx_t::rl_conc_key, ngx_http_brix_webdav_req_ctx_t::rl_conc_rule, ngx_http_brix_webdav_req_ctx_t::rl_key_str, and ngx_http_brix_webdav_loc_conf_t::upstream_proxy.
Referenced by ngx_http_brix_webdav_postconfiguration().
brix_rl_key_http()
ngx_int_t brix_rl_key_http (brix_rl_rule_t * rule, ngx_http_request_t * r, void * wctx, const char * path, char * out, size_t out_sz)
Definition at line 110 of file ratelimit_keys.c.
References BRIX_RL_KEY_DN, BRIX_RL_KEY_IP, BRIX_RL_KEY_ISSUER, BRIX_RL_KEY_VO, BRIX_RL_KEY_VOLUME, brix_identity_t::dn, ngx_http_brix_webdav_req_ctx_t::dn, ngx_http_brix_webdav_req_ctx_t::identity, brix_identity_t::issuer, brix_rl_rule_t::key_match, brix_rl_rule_t::key_type, rl_key_dn_hash(), and brix_identity_t::vo_csv.
Referenced by brix_rl_http_access_handler().
brix_rl_key_stream()
ngx_int_t brix_rl_key_stream (brix_rl_rule_t * rule, brix_ctx_t * ctx, const char * path, char * out, size_t out_sz)
Definition at line 44 of file ratelimit_keys.c.
References BRIX_RL_KEY_DN, BRIX_RL_KEY_IP, BRIX_RL_KEY_ISSUER, BRIX_RL_KEY_VO, BRIX_RL_KEY_VOLUME, brix_ctx_login_t::dn, brix_ctx_t::identity, brix_identity_t::issuer, brix_rl_rule_t::key_match, brix_rl_rule_t::key_type, brix_ctx_t::login, brix_ctx_login_t::peer_ip, brix_ctx_login_t::primary_vo, and rl_key_dn_hash().
Referenced by brix_rl_stream_gate().
brix_rl_lookup_locked()
brix_rl_node_t * brix_rl_lookup_locked (brix_rl_zone_t * zone, uint32_t hash, const char * key_str, size_t len)
Definition at line 262 of file ratelimit_zone.c.
References key, brix_rl_node_t::key_str, brix_rl_node_t::len, brix_rl_node_t::queue, brix_rl_shctx_t::queue, brix_rl_shctx_t::rbtree, and brix_rl_zone_t::sh.
Referenced by brix_rl_bw_check(), brix_rl_charge_bytes(), brix_rl_check(), brix_rl_conc_acquire(), brix_rl_conc_release(), brix_throttle_ioload_over(), brix_throttle_open_dec(), and throttle_node_locked().
brix_rl_release_ctx()
void brix_rl_release_ctx (brix_ctx_t * ctx)
Definition at line 196 of file ratelimit_stream.c.
References brix_rl_conc_release(), brix_ctx_rl_t::conc_key, brix_ctx_rl_t::conc_rule, and brix_ctx_t::rl.
Referenced by brix_on_disconnect().
brix_rl_rule_directive()
char * brix_rl_rule_directive (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 435 of file ratelimit_keys.c.
References rl_add_rule().
brix_rl_snapshot()
ngx_int_t brix_rl_snapshot (brix_rl_zone_t * zone, brix_rl_snapshot_entry_t * out, ngx_uint_t max, ngx_uint_t * count)
Definition at line 249 of file ratelimit.c.
References BRIX_RL_KEY_LEN, brix_rl_node_t::bw_excess, brix_rl_snapshot_entry_t::bw_excess, brix_rl_node_t::bytes_total, brix_rl_snapshot_entry_t::bytes_total, brix_rl_snapshot_entry_t::key_str, brix_rl_node_t::key_str, brix_rl_node_t::len, ngx_memcpy, brix_rl_shctx_t::queue, brix_rl_node_t::req_excess, brix_rl_snapshot_entry_t::req_excess, brix_rl_node_t::req_total, brix_rl_snapshot_entry_t::req_total, brix_rl_zone_t::sh, brix_rl_zone_t::shpool, brix_rl_node_t::throttle_count, and brix_rl_snapshot_entry_t::throttle_count.
Referenced by dashboard_build_v1_ratelimit().
brix_rl_stream_gate()
ngx_int_t brix_rl_stream_gate (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 73 of file ratelimit_stream.c.
References brix_rl_bw_check(), brix_rl_check(), brix_rl_conc_acquire(), BRIX_RL_KEY_LEN, brix_rl_key_stream(), BRIX_RL_KEY_VOLUME, BRIX_RL_METRIC_INC, BRIX_RL_RULE_CACHE_MAX, brix_send_wait(), brix_ctx_rl_t::bw_key, brix_ctx_rl_t::bw_rule, c, brix_ctx_rl_t::conc_key, brix_ctx_rl_t::conc_rule, brix_ctx_recv_t::cur_reqid, key, brix_ctx_rl_t::key_cache, brix_ctx_rl_t::key_cache_valid, brix_rl_rule_t::key_type, brix_ctx_t::recv, brix_ctx_t::rl, rl_op_rate_limited(), rl_request_path(), and ngx_stream_brix_srv_conf_t::rl_rules.
Referenced by brix_dispatch().
brix_rl_zone_add()
ngx_int_t brix_rl_zone_add (ngx_conf_t * cf, ngx_str_t * name, size_t size, brix_rl_zone_t ** out)
Definition at line 181 of file ratelimit_zone.c.
References BRIX_PCALLOC_OR_RETURN, brix_rl_init_zone(), BRIX_RL_MAX_ZONES, BRIX_RL_MIN_SIZE, brix_rl_nzones, brix_rl_zone_get(), brix_rl_zone_tag, brix_rl_zones, brix_rl_zone_t::name, name, brix_rl_zone_t::shm_zone, and brix_rl_zone_t::size.
Referenced by brix_rl_zone_directive().
brix_rl_zone_directive()
char * brix_rl_zone_directive (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 258 of file ratelimit_keys.c.
References brix_rl_zone_add(), name, and rl_parse_size().
brix_rl_zone_get()
brix_rl_zone_t * brix_rl_zone_get (ngx_str_t * name)
Definition at line 232 of file ratelimit_zone.c.
References brix_rl_nzones, brix_rl_zones, and name.
Referenced by brix_merge_srv_security(), brix_rl_conc_directive(), brix_rl_zone_add(), and rl_add_rule().
brix_rl_zone_reset_gauges()
void brix_rl_zone_reset_gauges (brix_rl_shctx_t * sh)
Definition at line 105 of file ratelimit_zone.c.
References brix_rl_node_t::in_flight, brix_rl_node_t::open_files, and brix_rl_shctx_t::queue.
Referenced by brix_rl_init_zone().
brix_rl_zones_all()
ngx_uint_t brix_rl_zones_all (brix_rl_zone_t ** out, ngx_uint_t max)
Definition at line 248 of file ratelimit_zone.c.
References brix_rl_nzones, and brix_rl_zones.
Referenced by dashboard_build_v1_ratelimit().