nginx-xrootd: src/net/ratelimit/ratelimit_zone.c File Reference
ratelimit_zone.c File Reference
#include "ratelimit.h"
#include "observability/metrics/metrics_macros.h"
#include "core/compat/alloc_guard.h"
Macros
#define BRIX_RL_MAX_ZONES 16
#define BRIX_RL_MIN_SIZE (64 * 1024)
#define BRIX_RL_METRIC_INC(field)
Functions
uint32_t brix_rl_hash (const char *key, size_t len)
static void brix_rl_rbtree_insert_value (ngx_rbtree_node_t *temp, ngx_rbtree_node_t *node, ngx_rbtree_node_t *sentinel)
void brix_rl_zone_reset_gauges (brix_rl_shctx_t *sh)
static ngx_int_t brix_rl_init_zone (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t brix_rl_zone_add (ngx_conf_t *cf, ngx_str_t *name, size_t size, brix_rl_zone_t **out)
brix_rl_zone_t * brix_rl_zone_get (ngx_str_t *name)
ngx_uint_t brix_rl_zones_all (brix_rl_zone_t **out, ngx_uint_t max)
brix_rl_node_t * brix_rl_lookup_locked (brix_rl_zone_t *zone, uint32_t hash, const char *key_str, size_t len)
static int brix_rl_evict_oldest_locked (brix_rl_zone_t *zone)
brix_rl_node_t * brix_rl_create_locked (brix_rl_zone_t *zone, uint32_t hash, const char *key_str, size_t len)
Variables
static ngx_uint_t brix_rl_zone_tag
static brix_rl_zone_t * brix_rl_zones [16]
static ngx_uint_t brix_rl_nzones
Macro Definition Documentation
BRIX_RL_MAX_ZONES
#define BRIX_RL_MAX_ZONES 16
Definition at line 19 of file ratelimit_zone.c.
BRIX_RL_METRIC_INC
#define BRIX_RL_METRIC_INC (field)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_m = brix_metrics_shared();                  \
        if (_m != NULL) { (void) ngx_atomic_fetch_add(&_m->field, 1); }      \
    } while (0)
Definition at line 27 of file ratelimit_zone.c.
BRIX_RL_MIN_SIZE
#define BRIX_RL_MIN_SIZE (64 * 1024)
Definition at line 20 of file ratelimit_zone.c.
Function Documentation
brix_rl_create_locked()
brix_rl_node_t * brix_rl_create_locked (brix_rl_zone_t * zone, uint32_t hash, const char * key_str, size_t len)
Definition at line 317 of file ratelimit_zone.c.
References brix_rl_evict_oldest_locked(), BRIX_RL_METRIC_INC, brix_rl_node_t::key_str, brix_rl_node_t::len, brix_rl_node_t::node, brix_rl_node_t::queue, brix_rl_shctx_t::queue, brix_rl_shctx_t::rbtree, brix_rl_zone_t::sh, and brix_rl_zone_t::shpool.
Referenced by brix_rl_charge_bytes(), brix_rl_check(), brix_rl_conc_acquire(), and throttle_node_locked().
brix_rl_evict_oldest_locked()
static int brix_rl_evict_oldest_locked (brix_rl_zone_t * zone) static
Definition at line 294 of file ratelimit_zone.c.
References BRIX_RL_METRIC_INC, brix_rl_node_t::node, brix_rl_shctx_t::queue, brix_rl_shctx_t::rbtree, brix_rl_zone_t::sh, and brix_rl_zone_t::shpool.
Referenced by brix_rl_create_locked().
brix_rl_hash()
uint32_t brix_rl_hash (const char * key, size_t len)
Definition at line 36 of file ratelimit_zone.c.
References key.
Referenced by brix_rl_bw_check(), brix_rl_charge_bytes(), brix_rl_check(), brix_rl_conc_acquire(), brix_rl_conc_release(), brix_throttle_ioload_over(), brix_throttle_open_dec(), rl_key_dn_hash(), and throttle_node_locked().
brix_rl_init_zone()
static ngx_int_t brix_rl_init_zone (ngx_shm_zone_t * shm_zone, void * data) static
Definition at line 125 of file ratelimit_zone.c.
References brix_rl_rbtree_insert_value(), brix_rl_zone_reset_gauges(), brix_rl_zone_t::name, brix_rl_shctx_t::queue, brix_rl_shctx_t::rbtree, brix_rl_shctx_t::sentinel, brix_rl_zone_t::sh, and brix_rl_zone_t::shpool.
Referenced by brix_rl_zone_add().
brix_rl_lookup_locked()
brix_rl_node_t * brix_rl_lookup_locked (brix_rl_zone_t * zone, uint32_t hash, const char * key_str, size_t len)
Definition at line 262 of file ratelimit_zone.c.
References key, brix_rl_node_t::key_str, brix_rl_node_t::len, brix_rl_node_t::queue, brix_rl_shctx_t::queue, brix_rl_shctx_t::rbtree, and brix_rl_zone_t::sh.
Referenced by brix_rl_bw_check(), brix_rl_charge_bytes(), brix_rl_check(), brix_rl_conc_acquire(), brix_rl_conc_release(), brix_throttle_ioload_over(), brix_throttle_open_dec(), and throttle_node_locked().
brix_rl_rbtree_insert_value()
static void brix_rl_rbtree_insert_value (ngx_rbtree_node_t * temp, ngx_rbtree_node_t * node, ngx_rbtree_node_t * sentinel) static
Definition at line 60 of file ratelimit_zone.c.
References brix_rl_node_t::key_str, and brix_rl_node_t::len.
Referenced by brix_rl_init_zone().
brix_rl_zone_add()
ngx_int_t brix_rl_zone_add (ngx_conf_t * cf, ngx_str_t * name, size_t size, brix_rl_zone_t ** out)
Definition at line 181 of file ratelimit_zone.c.
References BRIX_PCALLOC_OR_RETURN, brix_rl_init_zone(), BRIX_RL_MAX_ZONES, BRIX_RL_MIN_SIZE, brix_rl_nzones, brix_rl_zone_get(), brix_rl_zone_tag, brix_rl_zones, brix_rl_zone_t::name, name, brix_rl_zone_t::shm_zone, and brix_rl_zone_t::size.
Referenced by brix_rl_zone_directive().
brix_rl_zone_get()
brix_rl_zone_t * brix_rl_zone_get (ngx_str_t * name)
Definition at line 232 of file ratelimit_zone.c.
References brix_rl_nzones, brix_rl_zones, and name.
Referenced by brix_merge_srv_security(), brix_rl_conc_directive(), brix_rl_zone_add(), and rl_add_rule().
brix_rl_zone_reset_gauges()
void brix_rl_zone_reset_gauges (brix_rl_shctx_t * sh)
Definition at line 105 of file ratelimit_zone.c.
References brix_rl_node_t::in_flight, brix_rl_node_t::open_files, and brix_rl_shctx_t::queue.
Referenced by brix_rl_init_zone().
brix_rl_zones_all()
ngx_uint_t brix_rl_zones_all (brix_rl_zone_t ** out, ngx_uint_t max)
Definition at line 248 of file ratelimit_zone.c.
References brix_rl_nzones, and brix_rl_zones.
Referenced by dashboard_build_v1_ratelimit().
Variable Documentation
brix_rl_nzones
ngx_uint_t brix_rl_nzones static
Definition at line 25 of file ratelimit_zone.c.
Referenced by brix_rl_zone_add(), brix_rl_zone_get(), and brix_rl_zones_all().
brix_rl_zone_tag
ngx_uint_t brix_rl_zone_tag static
Definition at line 23 of file ratelimit_zone.c.
Referenced by brix_rl_zone_add().
brix_rl_zones
brix_rl_zone_t* brix_rl_zones[16] static
Definition at line 24 of file ratelimit_zone.c.
Referenced by brix_rl_zone_add(), brix_rl_zone_get(), and brix_rl_zones_all().