nginx-xrootd: src/protocols/root/read/read.h File Reference
read.h File Reference
#include "core/ngx_brix_module.h"
#include "fs/backend/sd.h"
Functions
ngx_int_t brix_handle_read (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_read_compressed (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf, int idx, off_t offset, size_t rlen)
ngx_int_t brix_handle_readv (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_handle_pgread (brix_ctx_t *ctx, ngx_connection_t *c)
size_t brix_pgread_encode_pages (const u_char *src, size_t len, off_t offset, u_char *dst)
size_t brix_pgread_read_encode_inplace (brix_sd_obj_t *obj, off_t offset, size_t rlen, u_char *out, ssize_t *nread_out, int *io_errno_out, int nowait)
Function Documentation
brix_handle_pgread()
ngx_int_t brix_handle_pgread (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 164 of file pgread.c.
References ngx_stream_brix_srv_conf_t::access_log_fd, brix_aio_post_task(), brix_build_pgread_chain(), brix_build_pgread_status(), BRIX_GET_SCRATCH, brix_log_access(), brix_metric_backend_bytes(), BRIX_METRIC_OP_READ, BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_PGREAD, BRIX_PG_CKSZ, brix_pgread_aio_done(), brix_pgread_aio_thread(), brix_pgread_read_encode_inplace(), brix_queue_response(), brix_queue_response_chain(), BRIX_READ_REQUEST_MAX, brix_release_read_buffer(), BRIX_RETURN_ERR, brix_rl_charge_ctx(), brix_send_error(), brix_validate_read_handle(), brix_vfs_effective_obj(), brix_vfs_io_execute(), BRIX_VFS_IO_PGREAD, brix_vfs_job_read_init(), brix_vfs_job_set_obj(), brix_ctx_totals_t::bytes, brix_file_t::bytes_read, brix_pgread_aio_t::c, c, ngx_stream_brix_srv_conf_t::common, brix_pgread_aio_t::ctx, brix_ctx_recv_t::cur_streamid, brix_pgread_aio_t::fd, brix_file_t::fd, xrdw_pgread_req_t::fhandle, brix_ctx_t::files, brix_pgread_aio_t::handle_idx, brix_ctx_recv_t::hdr_buf, brix_vfs_job_t::io_errno, brix_file_t::is_regular, kXR_ArgInvalid, kXR_IOError, kXR_pgPageSZ, ngx_stream_brix_module, brix_vfs_job_t::nio, brix_pgread_aio_t::obj, brix_pgread_aio_t::offset, xrdw_pgread_req_t::offset, brix_vfs_job_t::op, brix_pgread_aio_t::out_size, brix_vfs_job_t::out_size, brix_file_t::path, brix_ctx_rd_t::pgread_aio_task, brix_ctx_t::rd, brix_ctx_t::recv, brix_pgread_aio_t::rlen, xrdw_pgread_req_t::rlen, brix_pgread_aio_t::scratch, brix_file_t::sd_obj, brix_ctx_t::state, brix_pgread_aio_t::streamid, ngx_http_brix_shared_conf_t::thread_pool, brix_ctx_t::totals, XRD_ST_SENDING, and xrdw_pgread_req_unpack().
Referenced by brix_dispatch_read_opcode().
brix_handle_read()
ngx_int_t brix_handle_read (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 156 of file read.c.
References ngx_stream_brix_srv_conf_t::access_log_fd, brix_acquire_read_buffer(), brix_aio_post_task(), brix_budget_admit(), brix_budget_sync(), brix_build_chunked_chain(), BRIX_CSI_MISMATCH, brix_csi_verify_read(), brix_ktls_send_active(), brix_log_access(), brix_metric_backend_bytes(), BRIX_METRIC_OP_READ, BRIX_OP_OK, BRIX_OP_READ, brix_prefetch_read_file(), brix_queue_response_chain(), brix_read_aio_done(), brix_read_aio_thread(), brix_read_compressed(), BRIX_READ_REQUEST_MAX, brix_read_serve_sendfile(), BRIX_READ_WINDOW, brix_read_window_pump(), brix_release_read_buffer(), BRIX_RETURN_ERR, brix_sd_posix_wrap(), brix_send_ok(), brix_send_wait(), brix_ssi_read(), brix_transfer_slot_count_op(), brix_transfer_slot_update(), brix_validate_read_handle(), brix_vfs_io_execute(), brix_vfs_job_read_init(), brix_vfs_job_set_obj(), brix_zip_read(), brix_ctx_totals_t::bytes, brix_file_t::bytes_read, brix_read_aio_t::c, c, brix_file_t::cached_size, ngx_stream_brix_srv_conf_t::common, brix_read_aio_t::csi, brix_file_t::csi, brix_vfs_job_t::csi, brix_read_aio_t::ctx, brix_ctx_recv_t::cur_streamid, brix_file_t::dashboard_slot, brix_read_aio_t::databuf, brix_read_aio_t::fd, brix_file_t::fd, xrdw_read_req_t::fhandle, brix_ctx_t::files, brix_read_aio_t::handle_idx, brix_ctx_recv_t::hdr_buf, brix_read_aio_t::io_errno, brix_vfs_job_t::io_errno, brix_file_t::is_regular, kXR_IOError, ngx_stream_brix_srv_conf_t::memory_budget, ngx_brix_dashboard_shm_zone, ngx_stream_brix_module, brix_vfs_job_t::nio, brix_read_aio_t::nread, brix_read_aio_t::obj, brix_read_aio_t::offset, xrdw_read_req_t::offset, brix_ctx_t::out, brix_file_t::path, brix_ctx_t::rd, brix_ctx_rd_t::read_aio_task, brix_file_t::read_codec, brix_ctx_t::recv, brix_ctx_out_t::resp_pipelinable, brix_read_aio_t::rlen, xrdw_read_req_t::rlen, brix_file_t::sd_obj, brix_file_t::ssi, brix_ctx_t::state, brix_read_aio_t::streamid, ngx_http_brix_shared_conf_t::thread_pool, brix_ctx_t::totals, brix_ctx_rd_t::win_active, brix_ctx_rd_t::win_fd, brix_ctx_rd_t::win_idx, brix_ctx_rd_t::win_offset, brix_ctx_rd_t::win_remaining, brix_ctx_rd_t::win_streamid, brix_file_t::writable, XRD_ST_SENDING, xrdw_read_req_unpack(), and brix_file_t::zip_mode.
Referenced by brix_dispatch_read_opcode().
brix_handle_readv()
ngx_int_t brix_handle_readv (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 164 of file readv.c.
References ngx_stream_brix_srv_conf_t::access_log_fd, brix_aio_post_task(), brix_alloc_array(), brix_budget_admit(), brix_budget_sync(), brix_build_chunked_chain(), BRIX_GET_SCRATCH, brix_log_access(), BRIX_MAX_READV_TOTAL, BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_READV, brix_prefetch_readv_segments(), brix_queue_response_chain(), brix_readv_aio_done(), brix_readv_aio_thread(), BRIX_READV_MAXSEGS, BRIX_READV_SEGSIZE, brix_release_read_buffer(), brix_send_error(), brix_send_wait(), brix_validate_read_handle(), brix_vfs_io_execute(), BRIX_VFS_IO_READV, brix_ctx_totals_t::bytes, brix_file_t::bytes_read, brix_readv_aio_t::bytes_read_total, brix_readv_aio_t::c, c, ngx_stream_brix_srv_conf_t::common, brix_readv_aio_t::ctx, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_streamid, brix_vfs_job_t::err_msg, brix_vfs_job_t::err_msg_cap, brix_file_t::fd, brix_vfs_readv_seg_t::fd, readahead_list::fhandle, brix_ctx_t::files, brix_vfs_readv_seg_t::handle_index, brix_vfs_readv_seg_t::header_read_length_ptr, brix_vfs_job_t::io_errno, brix_readv_aio_t::io_error, kXR_ArgInvalid, kXR_ArgTooLong, kXR_IOError, ngx_stream_brix_srv_conf_t::memory_budget, ngx_stream_brix_module, brix_vfs_job_t::nio, brix_vfs_job_t::nsegs, brix_vfs_readv_seg_t::obj, brix_vfs_readv_seg_t::offset, brix_vfs_job_t::op, brix_vfs_job_t::out_size, brix_ctx_recv_t::payload, brix_vfs_readv_seg_t::payload_ptr, brix_ctx_t::rd, brix_vfs_readv_seg_t::read_length, brix_ctx_rd_t::readv_aio_task, ngx_stream_brix_srv_conf_t::readv_segment_size, brix_ctx_t::recv, brix_readv_aio_t::response_buffer, brix_readv_aio_t::response_bytes, readahead_list::rlen, brix_file_t::sd_obj, brix_readv_aio_t::segment_count, brix_readv_aio_t::segments, brix_vfs_job_t::segs, brix_ctx_t::state, brix_readv_aio_t::streamid, ngx_http_brix_shared_conf_t::thread_pool, brix_ctx_t::totals, and XRD_ST_SENDING.
Referenced by brix_dispatch_read_opcode().
brix_pgread_encode_pages()
size_t brix_pgread_encode_pages (const u_char * src, size_t len, off_t offset, u_char * dst)
Definition at line 156 of file pgread.c.
References xrdp_pg_encode().
brix_pgread_read_encode_inplace()
size_t brix_pgread_read_encode_inplace (brix_sd_obj_t * obj, off_t offset, size_t rlen, u_char * out, ssize_t * nread_out, int * io_errno_out, int nowait)
Definition at line 49 of file pgread.c.
References brix_crc32c_value(), BRIX_PG_CKSZ, BRIX_PGREAD_MAXIOV, and kXR_pgPageSZ.
Referenced by brix_handle_pgread(), and brix_vfs_io_execute_pgread().
brix_read_compressed()
ngx_int_t brix_read_compressed (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf, int idx, off_t offset, size_t rlen)
Definition at line 109 of file read_compress.c.
References ngx_stream_brix_srv_conf_t::access_log_fd, brix_build_chunked_chain(), brix_compress_frame(), BRIX_GET_SCRATCH, brix_log_access(), BRIX_OP_OK, BRIX_OP_READ, brix_prefetch_read_file(), brix_queue_response_chain(), BRIX_READ_CHUNK_MAX, brix_release_read_buffer(), BRIX_RETURN_ERR, brix_rl_charge_ctx(), brix_send_ok(), brix_transfer_slot_count_op(), brix_transfer_slot_update(), brix_vfs_io_execute(), brix_vfs_job_read_init(), brix_ctx_totals_t::bytes, brix_file_t::bytes_read, c, brix_file_t::cached_size, brix_ctx_rd_t::cmp_scratch, brix_file_t::dashboard_slot, brix_file_t::fd, brix_ctx_t::files, fstat(), brix_vfs_job_t::io_errno, kXR_IOError, ngx_brix_dashboard_shm_zone, brix_vfs_job_t::nio, brix_file_t::path, brix_ctx_t::rd, brix_file_t::read_codec, stat(), brix_ctx_t::state, brix_ctx_t::totals, brix_file_t::writable, and XRD_ST_SENDING.
Referenced by brix_handle_read().