nginx-xrootd: src/core/aio/reads.c File Reference
reads.c File Reference
#include "core/ngx_brix_module.h"
#include "protocols/root/connection/budget.h"
Functions
static ngx_int_t brix_read_window_emit (brix_ctx_t *ctx, ngx_connection_t *c, ssize_t nread, int io_errno)
void brix_read_window_pump (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf)
void brix_read_aio_thread (void *data, ngx_log_t *log)
void brix_read_aio_done (ngx_event_t *ev)
void brix_pgread_aio_thread (void *data, ngx_log_t *log)
void brix_pgread_aio_done (ngx_event_t *ev)
Function Documentation
brix_pgread_aio_done()
void brix_pgread_aio_done (ngx_event_t * ev)
Definition at line 400 of file reads.c.
References brix_aio_restore_request(), brix_aio_resume(), brix_build_pgread_chain(), brix_build_pgread_status(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_PGREAD, brix_queue_response(), brix_queue_response_chain(), brix_release_read_buffer(), brix_send_error(), brix_ctx_totals_t::bytes, brix_file_t::bytes_read, c, brix_pgread_aio_t::c, brix_pgread_aio_t::ctx, brix_ctx_t::files, brix_pgread_aio_t::handle_idx, brix_pgread_aio_t::io_errno, kXR_IOError, ngx_stream_brix_module, brix_pgread_aio_t::nread, brix_pgread_aio_t::offset, brix_pgread_aio_t::out_size, brix_file_t::path, brix_pgread_aio_t::scratch, brix_ctx_t::state, brix_pgread_aio_t::streamid, brix_ctx_t::totals, and XRD_ST_SENDING.
Referenced by brix_pgread_post_aio().
brix_pgread_aio_thread()
void brix_pgread_aio_thread (void * data, ngx_log_t * log)
Definition at line 376 of file reads.c.
References brix_vfs_io_execute(), BRIX_VFS_IO_PGREAD, brix_vfs_job_read_init(), brix_vfs_job_set_obj(), brix_pgread_aio_t::fd, brix_pgread_aio_t::io_errno, brix_vfs_job_t::io_errno, brix_vfs_job_t::nio, brix_pgread_aio_t::nread, brix_pgread_aio_t::obj, brix_pgread_aio_t::offset, brix_vfs_job_t::op, brix_pgread_aio_t::out_size, brix_vfs_job_t::out_size, brix_pgread_aio_t::rlen, and brix_pgread_aio_t::scratch.
Referenced by brix_pgread_post_aio().
brix_read_aio_done()
void brix_read_aio_done (ngx_event_t * ev)
Definition at line 263 of file reads.c.
References brix_aio_restore_stream(), brix_aio_resume(), brix_build_chunked_chain(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_READ, brix_queue_response_chain(), brix_read_window_emit(), brix_read_window_pump(), brix_release_read_buffer(), brix_send_error(), brix_ctx_totals_t::bytes, brix_file_t::bytes_read, c, brix_read_aio_t::c, brix_read_aio_t::conf, brix_read_aio_t::ctx, brix_read_aio_t::databuf, brix_ctx_t::files, brix_read_aio_t::handle_idx, brix_ctx_recv_t::hdr_pos, brix_read_aio_t::io_errno, kXR_IOError, brix_read_aio_t::nread, brix_ctx_t::out, brix_ctx_t::rd, brix_ctx_t::recv, brix_ctx_out_t::resp_pipelinable, brix_ctx_t::state, brix_read_aio_t::streamid, brix_ctx_t::totals, brix_ctx_rd_t::win_active, XRD_ST_REQ_HEADER, and XRD_ST_SENDING.
Referenced by brix_read_window_pump(), and read_post_aio().
brix_read_aio_thread()
void brix_read_aio_thread (void * data, ngx_log_t * log)
Definition at line 229 of file reads.c.
References brix_vfs_io_execute(), brix_vfs_job_read_init(), brix_vfs_job_set_obj(), brix_read_aio_t::csi, brix_vfs_job_t::csi, brix_read_aio_t::databuf, brix_read_aio_t::fd, brix_read_aio_t::io_errno, brix_vfs_job_t::io_errno, brix_vfs_job_t::nio, brix_read_aio_t::nread, brix_read_aio_t::obj, brix_read_aio_t::offset, and brix_read_aio_t::rlen.
Referenced by brix_read_window_pump(), and read_post_aio().
brix_read_window_emit()
static ngx_int_t brix_read_window_emit (brix_ctx_t * ctx, ngx_connection_t * c, ssize_t nread, int io_errno) static
Definition at line 44 of file reads.c.
References brix_build_window_chain(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_READ, brix_queue_response_chain(), brix_release_read_buffer(), brix_send_error(), brix_ctx_totals_t::bytes, brix_file_t::bytes_read, c, brix_ctx_t::files, brix_ctx_recv_t::hdr_pos, kXR_IOError, kXR_ok, kXR_oksofar, brix_ctx_t::rd, brix_ctx_rd_t::read_scratch, brix_ctx_t::recv, brix_ctx_t::state, brix_ctx_t::totals, brix_ctx_rd_t::win_active, brix_ctx_rd_t::win_idx, brix_ctx_rd_t::win_offset, brix_ctx_rd_t::win_remaining, XRD_ST_REQ_HEADER, and XRD_ST_SENDING.
Referenced by brix_read_aio_done(), and brix_read_window_pump().
brix_read_window_pump()
void brix_read_window_pump (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf)
Definition at line 104 of file reads.c.
References brix_aio_post_task(), brix_aio_resume(), brix_budget_sync(), BRIX_GET_SCRATCH, brix_read_aio_done(), brix_read_aio_thread(), BRIX_READ_WINDOW, brix_read_window_emit(), brix_send_error(), brix_vfs_io_execute(), brix_vfs_job_read_init(), c, brix_read_aio_t::c, brix_read_aio_t::conf, brix_read_aio_t::ctx, brix_read_aio_t::databuf, brix_read_aio_t::fd, brix_read_aio_t::handle_idx, brix_read_aio_t::io_errno, brix_vfs_job_t::io_errno, kXR_NoMemory, brix_vfs_job_t::nio, brix_read_aio_t::nread, brix_read_aio_t::offset, brix_ctx_t::rd, brix_ctx_rd_t::read_aio_task, brix_read_aio_t::rlen, brix_ctx_t::state, brix_read_aio_t::streamid, brix_ctx_rd_t::win_active, brix_ctx_rd_t::win_fd, brix_ctx_rd_t::win_idx, brix_ctx_rd_t::win_offset, brix_ctx_rd_t::win_remaining, brix_ctx_rd_t::win_streamid, XRD_ST_REQ_HEADER, and XRD_ST_SENDING.
Referenced by brix_read_aio_done(), ngx_stream_brix_send(), and read_serve_windowed().