nginx-xrootd: src/protocols/root/read/read_sendfile.c File Reference
read_sendfile.c File Reference
#include "read.h"
#include "fs/backend/sd.h"
#include "fs/backend/csi_tagstore.h"
#include "protocols/root/zip/zip_member.h"
#include "protocols/ssi/ssi.h"
#include "core/ngx_brix_module.h"
#include "protocols/root/connection/budget.h"
#include "prefetch.h"
#include <sys/uio.h>
#include "read_internal.h"
Functions
static ngx_flag_t brix_ktls_send_active (ngx_connection_t *c)
ngx_int_t brix_read_serve_sendfile (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf, const brix_read_io_t *io)
ngx_flag_t read_sendfile_eligible (brix_ctx_t *ctx, ngx_connection_t *c, int idx)
Function Documentation
brix_ktls_send_active()
static ngx_flag_t brix_ktls_send_active (ngx_connection_t * c) static
Definition at line 35 of file read_sendfile.c.
References c.
Referenced by read_sendfile_eligible().
brix_read_serve_sendfile()
ngx_int_t brix_read_serve_sendfile (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf, const brix_read_io_t * io)
Definition at line 50 of file read_sendfile.c.
References brix_build_sendfile_chain(), brix_log_access(), brix_metric_backend_bytes(), BRIX_METRIC_OP_READ, BRIX_OP_OK, BRIX_OP_READ, brix_prefetch_read_file(), brix_queue_response_chain(), brix_release_read_buffer(), BRIX_RETURN_ERR, brix_rl_charge_ctx(), brix_transfer_slot_count_op(), brix_transfer_slot_update(), brix_ctx_totals_t::bytes, brix_file_t::bytes_read, c, brix_file_t::cached_size, brix_file_t::dashboard_slot, brix_read_io_t::fd, brix_ctx_t::files, fstat(), brix_read_io_t::idx, kXR_IOError, ngx_brix_dashboard_shm_zone, brix_read_io_t::offset, brix_file_t::path, brix_read_io_t::rlen, stat(), brix_ctx_t::state, brix_ctx_t::totals, brix_file_t::writable, and XRD_ST_SENDING.
Referenced by brix_handle_read().
read_sendfile_eligible()
ngx_flag_t read_sendfile_eligible (brix_ctx_t * ctx, ngx_connection_t * c, int idx)
Definition at line 167 of file read_sendfile.c.
References brix_ktls_send_active(), c, brix_file_t::csi, brix_ctx_t::files, brix_file_t::is_regular, and brix_file_t::sd_obj.
Referenced by brix_handle_read().