nginx-xrootd: src/protocols/root/read/read_buffered.c File Reference
read_buffered.c File Reference
#include "read.h"
#include "fs/backend/sd.h"
#include "fs/backend/csi_tagstore.h"
#include "protocols/root/zip/zip_member.h"
#include "protocols/ssi/ssi.h"
#include "core/ngx_brix_module.h"
#include "protocols/root/connection/budget.h"
#include "prefetch.h"
#include <sys/uio.h>
#include "read_internal.h"
Functions
size_t read_clamped_total (brix_ctx_t *ctx, const brix_read_io_t *io)
ngx_int_t read_serve_windowed (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf, const brix_read_io_t *io, size_t total)
static void read_prefetch_buffered (brix_ctx_t *ctx, ngx_connection_t *c, const brix_read_io_t *io)
static ngx_flag_t read_try_warm (brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *rconf, const brix_read_io_t *io, ssize_t *nread_out)
static ngx_int_t read_post_aio (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf, const brix_read_io_t *io, ngx_flag_t *posted)
static ssize_t read_sync_fill (brix_ctx_t *ctx, const brix_read_io_t *io)
static ngx_int_t read_finish_buffered (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf, const brix_read_io_t *io, ssize_t nread)
ngx_int_t read_serve_buffered (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf, brix_read_io_t *io)
Function Documentation
read_clamped_total()
size_t read_clamped_total (brix_ctx_t * ctx, const brix_read_io_t * io)
Definition at line 33 of file read_buffered.c.
References brix_file_t::cached_size, brix_ctx_t::files, brix_read_io_t::idx, brix_read_io_t::offset, brix_read_io_t::rlen, and brix_file_t::writable.
Referenced by brix_handle_read().
read_finish_buffered()
static ngx_int_t read_finish_buffered (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf, const brix_read_io_t * io, ssize_t nread) static
Definition at line 315 of file read_buffered.c.
References brix_build_chunked_chain(), brix_log_access(), BRIX_OP_OK, BRIX_OP_READ, brix_queue_response_chain(), brix_read_io_failure_log(), brix_release_read_buffer(), BRIX_RETURN_ERR, brix_transfer_slot_count_op(), brix_transfer_slot_update(), brix_ctx_totals_t::bytes, brix_file_t::bytes_read, c, brix_file_t::dashboard_slot, brix_read_io_t::databuf, brix_read_io_t::fd, brix_ctx_t::files, brix_read_io_t::idx, kXR_IOError, ngx_brix_dashboard_shm_zone, brix_read_io_t::offset, brix_ctx_t::out, brix_file_t::path, brix_ctx_out_t::resp_pipelinable, brix_read_io_t::rlen, brix_ctx_t::state, brix_ctx_t::totals, and XRD_ST_SENDING.
Referenced by read_serve_buffered().
read_post_aio()
static ngx_int_t read_post_aio (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf, const brix_read_io_t * io, ngx_flag_t * posted) static
Definition at line 231 of file read_buffered.c.
References brix_aio_post_task(), brix_read_aio_done(), brix_read_aio_thread(), brix_release_read_buffer(), c, brix_read_aio_t::c, brix_read_aio_t::csi, brix_file_t::csi, brix_read_aio_t::ctx, brix_ctx_recv_t::cur_streamid, brix_read_aio_t::databuf, brix_read_io_t::databuf, brix_read_aio_t::fd, brix_read_io_t::fd, brix_ctx_t::files, brix_read_aio_t::handle_idx, brix_read_io_t::idx, brix_read_aio_t::io_errno, brix_read_aio_t::nread, brix_read_aio_t::obj, brix_read_aio_t::offset, brix_read_io_t::offset, brix_ctx_t::rd, brix_ctx_rd_t::read_aio_task, brix_ctx_t::recv, brix_read_aio_t::rlen, brix_read_io_t::rlen, brix_file_t::sd_obj, and brix_read_aio_t::streamid.
Referenced by read_serve_buffered().
read_prefetch_buffered()
static void read_prefetch_buffered (brix_ctx_t * ctx, ngx_connection_t * c, const brix_read_io_t * io) static
Definition at line 116 of file read_buffered.c.
References brix_prefetch_read_file(), c, brix_file_t::cached_size, brix_ctx_t::files, brix_read_io_t::idx, brix_file_t::is_regular, brix_read_io_t::offset, brix_read_io_t::rlen, and brix_file_t::writable.
Referenced by read_serve_buffered().
read_serve_buffered()
ngx_int_t read_serve_buffered (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf, brix_read_io_t * io)
Definition at line 399 of file read_buffered.c.
References brix_acquire_read_buffer(), brix_budget_admit(), brix_budget_sync(), brix_send_wait(), c, brix_read_io_t::databuf, read_finish_buffered(), read_post_aio(), read_prefetch_buffered(), read_sync_fill(), read_try_warm(), and brix_read_io_t::rlen.
Referenced by brix_handle_read().
read_serve_windowed()
ngx_int_t read_serve_windowed (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf, const brix_read_io_t * io, size_t total)
Definition at line 59 of file read_buffered.c.
References brix_budget_admit(), brix_log_access(), brix_prefetch_read_file(), BRIX_READ_WINDOW, brix_read_window_pump(), brix_send_wait(), c, brix_file_t::cached_size, brix_ctx_recv_t::cur_streamid, brix_read_io_t::fd, brix_ctx_t::files, brix_read_io_t::idx, brix_read_io_t::offset, brix_file_t::path, brix_ctx_t::rd, brix_ctx_t::recv, brix_read_io_t::rlen, brix_ctx_rd_t::win_active, brix_ctx_rd_t::win_fd, brix_ctx_rd_t::win_idx, brix_ctx_rd_t::win_offset, brix_ctx_rd_t::win_remaining, brix_ctx_rd_t::win_streamid, and brix_file_t::writable.
Referenced by brix_handle_read().
read_sync_fill()
static ssize_t read_sync_fill (brix_ctx_t * ctx, const brix_read_io_t * io) static
Definition at line 286 of file read_buffered.c.
References brix_vfs_io_execute(), brix_vfs_job_read_init(), brix_vfs_job_set_obj(), brix_file_t::csi, brix_vfs_job_t::csi, brix_read_io_t::databuf, brix_read_io_t::fd, brix_ctx_t::files, brix_read_io_t::idx, brix_vfs_job_t::io_errno, brix_vfs_job_t::nio, brix_read_io_t::offset, brix_read_io_t::rlen, and brix_file_t::sd_obj.
Referenced by read_serve_buffered().
read_try_warm()
static ngx_flag_t read_try_warm (brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * rconf, const brix_read_io_t * io, ssize_t * nread_out) static
Definition at line 158 of file read_buffered.c.
References BRIX_CSI_MISMATCH, brix_csi_verify_read(), brix_metric_backend_bytes(), BRIX_METRIC_OP_READ, brix_sd_posix_wrap(), brix_file_t::csi, brix_read_io_t::databuf, brix_read_io_t::fd, brix_ctx_t::files, brix_read_io_t::idx, brix_file_t::is_regular, brix_read_io_t::offset, brix_read_io_t::rlen, and brix_file_t::sd_obj.
Referenced by read_serve_buffered().