nginx-xrootd: src/protocols/root/read/read.c File Reference
read.c File Reference
#include "read.h"
#include "fs/backend/sd.h"
#include "fs/backend/csi_tagstore.h"
#include "protocols/root/zip/zip_member.h"
#include "protocols/ssi/ssi.h"
#include "core/ngx_brix_module.h"
#include "protocols/root/connection/budget.h"
#include "prefetch.h"
#include <sys/uio.h>
Functions
static ngx_flag_t brix_ktls_send_active (ngx_connection_t *c)
static ngx_int_t brix_read_serve_sendfile (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf, int idx, ngx_fd_t fd, int64_t offset, size_t rlen)
ngx_int_t brix_handle_read (brix_ctx_t *ctx, ngx_connection_t *c)
Function Documentation
brix_handle_read()
ngx_int_t brix_handle_read (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 156 of file read.c.
References ngx_stream_brix_srv_conf_t::access_log_fd, brix_acquire_read_buffer(), brix_aio_post_task(), brix_budget_admit(), brix_budget_sync(), brix_build_chunked_chain(), BRIX_CSI_MISMATCH, brix_csi_verify_read(), brix_ktls_send_active(), brix_log_access(), brix_metric_backend_bytes(), BRIX_METRIC_OP_READ, BRIX_OP_OK, BRIX_OP_READ, brix_prefetch_read_file(), brix_queue_response_chain(), brix_read_aio_done(), brix_read_aio_thread(), brix_read_compressed(), BRIX_READ_REQUEST_MAX, brix_read_serve_sendfile(), BRIX_READ_WINDOW, brix_read_window_pump(), brix_release_read_buffer(), BRIX_RETURN_ERR, brix_sd_posix_wrap(), brix_send_ok(), brix_send_wait(), brix_ssi_read(), brix_transfer_slot_count_op(), brix_transfer_slot_update(), brix_validate_read_handle(), brix_vfs_io_execute(), brix_vfs_job_read_init(), brix_vfs_job_set_obj(), brix_zip_read(), brix_ctx_totals_t::bytes, brix_file_t::bytes_read, brix_read_aio_t::c, c, brix_file_t::cached_size, ngx_stream_brix_srv_conf_t::common, brix_read_aio_t::csi, brix_file_t::csi, brix_vfs_job_t::csi, brix_read_aio_t::ctx, brix_ctx_recv_t::cur_streamid, brix_file_t::dashboard_slot, brix_read_aio_t::databuf, brix_read_aio_t::fd, brix_file_t::fd, xrdw_read_req_t::fhandle, brix_ctx_t::files, brix_read_aio_t::handle_idx, brix_ctx_recv_t::hdr_buf, brix_read_aio_t::io_errno, brix_vfs_job_t::io_errno, brix_file_t::is_regular, kXR_IOError, ngx_stream_brix_srv_conf_t::memory_budget, ngx_brix_dashboard_shm_zone, ngx_stream_brix_module, brix_vfs_job_t::nio, brix_read_aio_t::nread, brix_read_aio_t::obj, brix_read_aio_t::offset, xrdw_read_req_t::offset, brix_ctx_t::out, brix_file_t::path, brix_ctx_t::rd, brix_ctx_rd_t::read_aio_task, brix_file_t::read_codec, brix_ctx_t::recv, brix_ctx_out_t::resp_pipelinable, brix_read_aio_t::rlen, xrdw_read_req_t::rlen, brix_file_t::sd_obj, brix_file_t::ssi, brix_ctx_t::state, brix_read_aio_t::streamid, ngx_http_brix_shared_conf_t::thread_pool, brix_ctx_t::totals, brix_ctx_rd_t::win_active, brix_ctx_rd_t::win_fd, brix_ctx_rd_t::win_idx, brix_ctx_rd_t::win_offset, brix_ctx_rd_t::win_remaining, brix_ctx_rd_t::win_streamid, brix_file_t::writable, XRD_ST_SENDING, xrdw_read_req_unpack(), and brix_file_t::zip_mode.
Referenced by brix_dispatch_read_opcode().
brix_ktls_send_active()
static ngx_flag_t brix_ktls_send_active (ngx_connection_t * c) static
Definition at line 41 of file read.c.
References c.
Referenced by brix_handle_read().
brix_read_serve_sendfile()
static ngx_int_t brix_read_serve_sendfile (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf, int idx, ngx_fd_t fd, int64_t offset, size_t rlen) static
Definition at line 56 of file read.c.
References ngx_stream_brix_srv_conf_t::access_log_fd, brix_build_sendfile_chain(), brix_log_access(), brix_metric_backend_bytes(), BRIX_METRIC_OP_READ, BRIX_OP_OK, BRIX_OP_READ, brix_prefetch_read_file(), brix_queue_response_chain(), brix_release_read_buffer(), BRIX_RETURN_ERR, brix_rl_charge_ctx(), brix_transfer_slot_count_op(), brix_transfer_slot_update(), brix_ctx_totals_t::bytes, brix_file_t::bytes_read, c, brix_file_t::cached_size, brix_file_t::dashboard_slot, brix_ctx_t::files, fstat(), kXR_IOError, ngx_brix_dashboard_shm_zone, brix_file_t::path, stat(), brix_ctx_t::state, brix_ctx_t::totals, brix_file_t::writable, and XRD_ST_SENDING.
Referenced by brix_handle_read().