nginx-xrootd: src/protocols/root/read/read_internal.h File Reference
read_internal.h File Reference
#include "read.h"
Data Structures
struct brix_read_io_t
Functions
ngx_flag_t read_sendfile_eligible (brix_ctx_t *ctx, ngx_connection_t *c, int idx)
ngx_int_t brix_read_serve_sendfile (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf, const brix_read_io_t *io)
size_t read_clamped_total (brix_ctx_t *ctx, const brix_read_io_t *io)
ngx_int_t read_serve_windowed (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf, const brix_read_io_t *io, size_t total)
ngx_int_t read_serve_buffered (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf, brix_read_io_t *io)
Function Documentation
brix_read_serve_sendfile()
ngx_int_t brix_read_serve_sendfile (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf, const brix_read_io_t * io)
Definition at line 50 of file read_sendfile.c.
References brix_build_sendfile_chain(), brix_log_access(), brix_metric_backend_bytes(), BRIX_METRIC_OP_READ, BRIX_OP_OK, BRIX_OP_READ, brix_prefetch_read_file(), brix_queue_response_chain(), brix_release_read_buffer(), BRIX_RETURN_ERR, brix_rl_charge_ctx(), brix_transfer_slot_count_op(), brix_transfer_slot_update(), brix_ctx_totals_t::bytes, brix_file_t::bytes_read, c, brix_file_t::cached_size, brix_file_t::dashboard_slot, brix_read_io_t::fd, brix_ctx_t::files, fstat(), brix_read_io_t::idx, kXR_IOError, ngx_brix_dashboard_shm_zone, brix_read_io_t::offset, brix_file_t::path, brix_read_io_t::rlen, stat(), brix_ctx_t::state, brix_ctx_t::totals, brix_file_t::writable, and XRD_ST_SENDING.
Referenced by brix_handle_read().
read_clamped_total()
size_t read_clamped_total (brix_ctx_t * ctx, const brix_read_io_t * io)
Definition at line 33 of file read_buffered.c.
References brix_file_t::cached_size, brix_ctx_t::files, brix_read_io_t::idx, brix_read_io_t::offset, brix_read_io_t::rlen, and brix_file_t::writable.
Referenced by brix_handle_read().
read_sendfile_eligible()
ngx_flag_t read_sendfile_eligible (brix_ctx_t * ctx, ngx_connection_t * c, int idx)
Definition at line 167 of file read_sendfile.c.
References brix_ktls_send_active(), c, brix_file_t::csi, brix_ctx_t::files, brix_file_t::is_regular, and brix_file_t::sd_obj.
Referenced by brix_handle_read().
read_serve_buffered()
ngx_int_t read_serve_buffered (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf, brix_read_io_t * io)
Definition at line 399 of file read_buffered.c.
References brix_acquire_read_buffer(), brix_budget_admit(), brix_budget_sync(), brix_send_wait(), c, brix_read_io_t::databuf, read_finish_buffered(), read_post_aio(), read_prefetch_buffered(), read_sync_fill(), read_try_warm(), and brix_read_io_t::rlen.
Referenced by brix_handle_read().
read_serve_windowed()
ngx_int_t read_serve_windowed (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf, const brix_read_io_t * io, size_t total)
Definition at line 59 of file read_buffered.c.
References brix_budget_admit(), brix_log_access(), brix_prefetch_read_file(), BRIX_READ_WINDOW, brix_read_window_pump(), brix_send_wait(), c, brix_file_t::cached_size, brix_ctx_recv_t::cur_streamid, brix_read_io_t::fd, brix_ctx_t::files, brix_read_io_t::idx, brix_read_io_t::offset, brix_file_t::path, brix_ctx_t::rd, brix_ctx_t::recv, brix_read_io_t::rlen, brix_ctx_rd_t::win_active, brix_ctx_rd_t::win_fd, brix_ctx_rd_t::win_idx, brix_ctx_rd_t::win_offset, brix_ctx_rd_t::win_remaining, brix_ctx_rd_t::win_streamid, and brix_file_t::writable.
Referenced by brix_handle_read().