nginx-xrootd: src/protocols/root/read/read_compress.c File Reference
read_compress.c File Reference
#include "read.h"
#include "core/ngx_brix_module.h"
#include "core/compat/codec_core.h"
#include "protocols/root/response/response.h"
#include "prefetch.h"
#include <errno.h>
#include <unistd.h>
#include <string.h>
Functions
static size_t brix_codec_max_out (size_t plain)
static size_t brix_compress_frame (brix_ctx_t *ctx, ngx_connection_t *c, uint8_t codec_id, const u_char *in, size_t in_len)
static ngx_int_t brix_compressed_extent (brix_ctx_t *ctx, int idx, off_t offset, size_t rlen, off_t *file_size, size_t *data_total, int *io_err)
static ngx_int_t brix_compressed_read_window (brix_ctx_t *ctx, int idx, off_t offset, u_char *plain, size_t data_total, size_t *nread_out, int *io_err)
static void brix_compressed_account (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf, int idx, off_t offset, size_t data_total, size_t clen)
ngx_int_t brix_read_compressed (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf, int idx, off_t offset, size_t rlen)
Function Documentation
brix_codec_max_out()
static size_t brix_codec_max_out (size_t plain) static
Definition at line 44 of file read_compress.c.
Referenced by brix_compress_frame().
brix_compress_frame()
static size_t brix_compress_frame (brix_ctx_t * ctx, ngx_connection_t * c, uint8_t codec_id, const u_char * in, size_t in_len) static
Definition at line 56 of file read_compress.c.
References brix_codec_close(), BRIX_CODEC_DIR_COMPRESS, BRIX_CODEC_END, brix_codec_max_out(), BRIX_CODEC_OK, brix_codec_open(), brix_codec_step(), BRIX_GET_SCRATCH, c, brix_ctx_rd_t::cmp_scratch, brix_ctx_rd_t::cmp_scratch_size, brix_ctx_t::rd, and s.
Referenced by brix_read_compressed().
brix_compressed_account()
static void brix_compressed_account (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf, int idx, off_t offset, size_t data_total, size_t clen) static
Definition at line 210 of file read_compress.c.
References brix_log_access(), BRIX_OP_OK, BRIX_OP_READ, brix_rl_charge_ctx(), brix_transfer_slot_count_op(), brix_transfer_slot_update(), brix_ctx_totals_t::bytes, brix_file_t::bytes_read, c, brix_file_t::dashboard_slot, brix_ctx_t::files, ngx_brix_dashboard_shm_zone, brix_file_t::path, and brix_ctx_t::totals.
Referenced by brix_read_compressed().
brix_compressed_extent()
static ngx_int_t brix_compressed_extent (brix_ctx_t * ctx, int idx, off_t offset, size_t rlen, off_t * file_size, size_t * data_total, int * io_err) static
Definition at line 125 of file read_compress.c.
References BRIX_READ_CHUNK_MAX, brix_file_t::cached_size, brix_file_t::fd, brix_ctx_t::files, fstat(), stat(), and brix_file_t::writable.
Referenced by brix_read_compressed().
brix_compressed_read_window()
static ngx_int_t brix_compressed_read_window (brix_ctx_t * ctx, int idx, off_t offset, u_char * plain, size_t data_total, size_t * nread_out, int * io_err) static
Definition at line 173 of file read_compress.c.
References brix_vfs_io_execute(), brix_vfs_job_read_init(), brix_file_t::fd, brix_ctx_t::files, brix_vfs_job_t::io_errno, and brix_vfs_job_t::nio.
Referenced by brix_read_compressed().
brix_read_compressed()
ngx_int_t brix_read_compressed (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf, int idx, off_t offset, size_t rlen)
Definition at line 258 of file read_compress.c.
References brix_build_chunked_chain(), brix_compress_frame(), brix_compressed_account(), brix_compressed_extent(), brix_compressed_read_window(), BRIX_GET_SCRATCH, BRIX_OP_OK, BRIX_OP_READ, brix_prefetch_read_file(), brix_queue_response_chain(), brix_release_read_buffer(), BRIX_RETURN_ERR, brix_send_ok(), c, brix_ctx_rd_t::cmp_scratch, brix_ctx_t::files, kXR_IOError, brix_file_t::path, brix_ctx_t::rd, brix_file_t::read_codec, brix_ctx_t::state, and XRD_ST_SENDING.
Referenced by brix_handle_read().