nginx-xrootd: src/protocols/root/read/readv_engine.c File Reference
readv_engine.c File Reference
#include "read.h"
#include "fs/backend/sd.h"
#include "fs/vfs/vfs_io_core.h"
#include "core/aio/aio.h"
#include "core/compat/safe_size.h"
#include "core/ngx_brix_module.h"
#include "core/compat/range_vector.h"
#include <stdlib.h>
#include <sys/uio.h>
Data Structures
struct brix_readv_run_ctx_t
Macros
#define BRIX_READV_PREADV_MAXIOV 64
Functions
static ngx_int_t brix_readv_build_ranges (const brix_readv_seg_desc_t *segments, size_t segment_count, brix_byte_range_t *ranges, char *error_message, size_t error_message_len)
static ngx_int_t brix_readv_read_one_run (const brix_readv_run_ctx_t *rctx, size_t segment_index, ngx_uint_t *run_count_out, size_t *run_bytes_out)
ngx_int_t brix_readv_read_segments (brix_readv_seg_desc_t *segments, size_t segment_count, size_t *bytes_read_total, char *error_message, size_t error_message_len)
Macro Definition Documentation
BRIX_READV_PREADV_MAXIOV
#define BRIX_READV_PREADV_MAXIOV 64
Definition at line 13 of file readv_engine.c.
Function Documentation
brix_readv_build_ranges()
static ngx_int_t brix_readv_build_ranges (const brix_readv_seg_desc_t * segments, size_t segment_count, brix_byte_range_t * ranges, char * error_message, size_t error_message_len) static
Definition at line 33 of file readv_engine.c.
References brix_byte_range_t::end, brix_byte_range_t::fd, brix_vfs_readv_seg_t::fd, brix_byte_range_t::handle, brix_vfs_readv_seg_t::offset, brix_vfs_readv_seg_t::read_length, and brix_byte_range_t::start.
Referenced by brix_readv_read_segments().
brix_readv_read_one_run()
static ngx_int_t brix_readv_read_one_run (const brix_readv_run_ctx_t * rctx, size_t segment_index, ngx_uint_t * run_count_out, size_t * run_bytes_out) static
Definition at line 106 of file readv_engine.c.
References brix_range_vector_next_coalesced_run(), BRIX_READV_PREADV_MAXIOV, brix_sd_obj_preadv(), brix_vfs_effective_obj(), brix_readv_run_ctx_t::error_message, brix_readv_run_ctx_t::error_message_len, brix_vfs_readv_seg_t::fd, brix_vfs_readv_seg_t::header_read_length_ptr, ngx_memcpy, brix_vfs_readv_seg_t::obj, brix_vfs_readv_seg_t::offset, brix_readv_run_ctx_t::ranges, brix_vfs_readv_seg_t::read_length, brix_readv_run_ctx_t::segment_count, and brix_readv_run_ctx_t::segments.
Referenced by brix_readv_read_segments().
brix_readv_read_segments()
ngx_int_t brix_readv_read_segments (brix_readv_seg_desc_t * segments, size_t segment_count, size_t * bytes_read_total, char * error_message, size_t error_message_len)
Definition at line 180 of file readv_engine.c.
References brix_readv_build_ranges(), BRIX_READV_MAXSEGS, brix_readv_read_one_run(), brix_size_mul(), brix_readv_run_ctx_t::error_message, brix_readv_run_ctx_t::error_message_len, ngx_memcpy, brix_readv_run_ctx_t::ranges, brix_readv_run_ctx_t::segment_count, and brix_readv_run_ctx_t::segments.
Referenced by brix_vfs_io_execute_readv().