nginx-xrootd: src/protocols/root/protocol/readv_seg.h File Reference
readv_seg.h File Reference
#include <stdint.h>
#include <string.h>
#include "frame_hdr.h"
#include "flags.h"
Functions
static void brix_readv_seg_pack (uint8_t out[16], const uint8_t fhandle[4], uint32_t rlen, uint64_t offset)
static uint32_t brix_readv_seg_rlen (const uint8_t in[16])
Function Documentation
brix_readv_seg_pack()
static void brix_readv_seg_pack (uint8_t out[16], const uint8_t fhandle[4], uint32_t rlen, uint64_t offset) inline static
Definition at line 39 of file readv_seg.h.
References xrd_put_u32_be(), and xrd_put_u64_be().
Referenced by brix_file_readv().
brix_readv_seg_rlen()
static uint32_t brix_readv_seg_rlen (const uint8_t in[16]) inline static
Definition at line 49 of file readv_seg.h.
References xrd_get_u32_be().
Referenced by brix_readv_scatter().