nginx-xrootd: src/fs/cache/reap_watermark.h File Reference
reap_watermark.h File Reference
#include "cache_internal.h"
Functions
ngx_uint_t brix_cache_watermark_purge (ngx_stream_brix_srv_conf_t *conf, ngx_log_t *log)
void brix_cache_watermark_timer_handler (ngx_event_t *ev)
Function Documentation
brix_cache_watermark_purge()
ngx_uint_t brix_cache_watermark_purge (ngx_stream_brix_srv_conf_t * conf, ngx_log_t * log)
Definition at line 12 of file reap_watermark.c.
References brix_cache_evict_unlock(), brix_cache_fs_usage_sampled(), brix_cache_purge_to_target(), brix_cache_state_root(), brix_cache_try_evict_lock(), brix_metric_cache_usage_ratio(), brix_metric_cache_watermark_purge(), ngx_stream_brix_srv_conf_t::cache, ngx_http_brix_shared_conf_t::cache_store, ngx_stream_brix_srv_conf_t::common, brix_cache_reaper_conf_t::high_watermark, log, brix_cache_reaper_conf_t::low_watermark, PATH_MAX, ngx_stream_brix_srv_conf_t::reaper, and usage().
Referenced by brix_cache_watermark_timer_handler().
brix_cache_watermark_timer_handler()
void brix_cache_watermark_timer_handler (ngx_event_t * ev)
Definition at line 79 of file reap_watermark.c.
References brix_cache_watermark_purge(), brix_cache_reaper_conf_t::reap_interval, and ngx_stream_brix_srv_conf_t::reaper.
Referenced by ngx_stream_brix_init_process().