nginx-xrootd: src/net/cms/recv_forward.c File Reference
recv_forward.c File Reference
#include "cms_internal.h"
#include "recv_internal.h"
#include "fs/vfs/vfs.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "node_ops.h"
#include "rrdata.h"
#include "fs/path/beneath.h"
#include <errno.h>
#include <unistd.h>
Functions
static int cms_drv_unlink (brix_sd_instance_t *sd, const char *path, int isdir)
static int cms_drv_chmod (brix_sd_instance_t *sd, const brix_cms_node_plan_t *plan)
static int cms_drv_trunc (brix_sd_instance_t *sd, const brix_cms_node_plan_t *plan)
static int cms_node_exec_driver (brix_sd_instance_t *sd, const char *root_canon, const brix_cms_node_plan_t *plan, ngx_log_t *log, int *handled)
static ngx_int_t cms_forward_via_driver (ngx_brix_cms_ctx_t *ctx, brix_sd_instance_t *sd, u_char code, uint32_t streamid, const brix_cms_node_plan_t *plan)
static int cms_posix_apply (ngx_brix_cms_ctx_t *ctx, const brix_cms_node_plan_t *plan, int *handled)
static ngx_int_t cms_forward_via_posix (ngx_brix_cms_ctx_t *ctx, u_char code, uint32_t streamid, const brix_cms_node_plan_t *plan)
ngx_int_t cms_node_exec_forward (ngx_brix_cms_ctx_t *ctx, u_char code, uint32_t streamid, const u_char *payload, size_t plen)
Function Documentation
cms_drv_chmod()
static int cms_drv_chmod (brix_sd_instance_t * sd, const brix_cms_node_plan_t * plan) static
Definition at line 57 of file recv_forward.c.
References brix_sd_setattr_t::mode, brix_cms_node_plan_t::mode, brix_cms_node_plan_t::path, and brix_sd_setattr_t::set_mode.
Referenced by cms_node_exec_driver().
cms_drv_trunc()
static int cms_drv_trunc (brix_sd_instance_t * sd, const brix_cms_node_plan_t * plan) static
Definition at line 75 of file recv_forward.c.
References BRIX_SD_O_WRITE, brix_cms_node_plan_t::path, and brix_cms_node_plan_t::size.
Referenced by cms_node_exec_driver().
cms_drv_unlink()
static int cms_drv_unlink (brix_sd_instance_t * sd, const char * path, int isdir) static
Definition at line 44 of file recv_forward.c.
Referenced by cms_node_exec_driver().
cms_forward_via_driver()
static ngx_int_t cms_forward_via_driver (ngx_brix_cms_ctx_t * ctx, brix_sd_instance_t * sd, u_char code, uint32_t streamid, const brix_cms_node_plan_t * plan) static
Definition at line 147 of file recv_forward.c.
References CMS_ERR_EINVAL, cms_node_exec_driver(), code, ngx_brix_cms_send_error(), and brix_cms_node_plan_t::path.
Referenced by cms_node_exec_forward().
cms_forward_via_posix()
static ngx_int_t cms_forward_via_posix (ngx_brix_cms_ctx_t * ctx, u_char code, uint32_t streamid, const brix_cms_node_plan_t * plan) static
Definition at line 236 of file recv_forward.c.
References CMS_ERR_EINVAL, cms_posix_apply(), code, ngx_brix_cms_send_error(), and brix_cms_node_plan_t::path.
Referenced by cms_node_exec_forward().
cms_node_exec_driver()
static int cms_node_exec_driver (brix_sd_instance_t * sd, const char * root_canon, const brix_cms_node_plan_t * plan, ngx_log_t * log, int * handled) static
Definition at line 103 of file recv_forward.c.
References brix_cms_node_plan_t::action, brix_vfs_backend_mkpath(), cms_drv_chmod(), cms_drv_trunc(), cms_drv_unlink(), log, brix_cms_node_plan_t::mode, brix_cms_node_plan_t::path, brix_cms_node_plan_t::path2, XRDCMS_NACT_CHMOD, XRDCMS_NACT_MKDIR, XRDCMS_NACT_MKPATH, XRDCMS_NACT_MV, XRDCMS_NACT_RM, XRDCMS_NACT_RMDIR, and XRDCMS_NACT_TRUNC.
Referenced by cms_forward_via_driver().
cms_node_exec_forward()
ngx_int_t cms_node_exec_forward (ngx_brix_cms_ctx_t * ctx, u_char code, uint32_t streamid, const u_char * payload, size_t plen)
Definition at line 272 of file recv_forward.c.
References brix_cms_node_plan(), brix_cms_rrdata_parse(), brix_sd_default_driver(), brix_vfs_backend_resolve(), CMS_ERR_EINVAL, cms_forward_via_driver(), cms_forward_via_posix(), code, and ngx_brix_cms_send_error().
Referenced by cms_frame_forward().
cms_posix_apply()
static int cms_posix_apply (ngx_brix_cms_ctx_t * ctx, const brix_cms_node_plan_t * plan, int * handled) static
Definition at line 180 of file recv_forward.c.
References brix_cms_node_plan_t::action, brix_beneath_full_path(), brix_mkdir_beneath(), brix_mkdir_recursive_beneath(), brix_rename_beneath(), brix_vfs_open_fd_at(), brix_vfs_unlink_at(), close(), brix_cms_node_plan_t::mode, brix_cms_node_plan_t::path, brix_cms_node_plan_t::path2, PATH_MAX, brix_cms_node_plan_t::size, XRDCMS_NACT_CHMOD, XRDCMS_NACT_MKDIR, XRDCMS_NACT_MKPATH, XRDCMS_NACT_MV, XRDCMS_NACT_RM, XRDCMS_NACT_RMDIR, and XRDCMS_NACT_TRUNC.
Referenced by cms_forward_via_posix().