nginx-xrootd: src/protocols/root/connection/recv_frame.h File Reference
recv_frame.h File Reference
#include "core/ngx_brix_module.h"
Enumerations
enum brix_recv_step_t { BRIX_RECV_STEP_NEXT = 0 , BRIX_RECV_STEP_CONTINUE , BRIX_RECV_STEP_RETURN , BRIX_RECV_STEP_BREAK }
Functions
brix_recv_step_t brix_recv_run_deferred (ngx_stream_session_t *s, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, brix_ctx_t *ctx, ngx_event_t *rev, size_t *rx_pending)
brix_recv_step_t brix_recv_read_frame (ngx_stream_session_t *s, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, brix_ctx_t *ctx, ngx_event_t *rev, size_t *rx_pending)
brix_recv_step_t brix_recv_process_frame (ngx_stream_session_t *s, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, brix_ctx_t *ctx, ngx_event_t *rev, size_t *rx_pending)
Enumeration Type Documentation
brix_recv_step_t
enum brix_recv_step_t
Enumerator
BRIX_RECV_STEP_NEXT
BRIX_RECV_STEP_CONTINUE
BRIX_RECV_STEP_RETURN
BRIX_RECV_STEP_BREAK
Definition at line 20 of file recv_frame.h.
Function Documentation
brix_recv_process_frame()
brix_recv_step_t brix_recv_process_frame (ngx_stream_session_t * s, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, brix_ctx_t * ctx, ngx_event_t * rev, size_t * rx_pending)
Definition at line 423 of file recv_process.c.
References brix_process_handshake(), brix_recv_after_header(), brix_recv_after_payload(), BRIX_RECV_STEP_BREAK, BRIX_RECV_STEP_CONTINUE, c, brix_ctx_recv_t::hdr_pos, brix_ctx_t::recv, s, brix_ctx_t::state, XRD_ST_HANDSHAKE, and XRD_ST_REQ_HEADER.
Referenced by ngx_stream_brix_recv().
brix_recv_read_frame()
brix_recv_step_t brix_recv_read_frame (ngx_stream_session_t * s, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, brix_ctx_t * ctx, ngx_event_t * rev, size_t * rx_pending)
Definition at line 188 of file recv_frame.c.
References brix_arm_read_deadline(), brix_close_all_files(), brix_defer_teardown_if_writing(), brix_on_disconnect(), brix_recv_advance(), brix_recv_header_prep(), BRIX_RECV_STEP_BREAK, BRIX_RECV_STEP_NEXT, BRIX_RECV_STEP_RETURN, BRIX_SRV_METRIC_ADD, c, brix_ctx_recv_t::cur_body_extra, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::hdr_buf, brix_ctx_recv_t::hdr_pos, brix_ctx_recv_t::payload, brix_ctx_recv_t::payload_pos, brix_ctx_t::recv, s, brix_ctx_t::state, XRD_HANDSHAKE_LEN, XRD_REQUEST_HDR_LEN, XRD_ST_HANDSHAKE, and XRD_ST_REQ_HEADER.
Referenced by ngx_stream_brix_recv().
brix_recv_run_deferred()
brix_recv_step_t brix_recv_run_deferred (ngx_stream_session_t * s, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, brix_ctx_t * ctx, ngx_event_t * rev, size_t * rx_pending)
Definition at line 21 of file recv_frame.c.
References brix_dispatch(), BRIX_RECV_STEP_BREAK, BRIX_RECV_STEP_CONTINUE, BRIX_RECV_STEP_RETURN, BRIX_SRV_METRIC_ADD, brix_start_tls(), c, brix_ctx_out_t::count, brix_ctx_recv_t::hdr_pos, brix_ctx_t::out, brix_ctx_t::recv, brix_ctx_out_t::recv_deferred, brix_ctx_t::state, brix_ctx_t::tls_pending, brix_ctx_out_t::wr_inflight, XRD_ST_AIO, XRD_ST_REQ_HEADER, and XRD_ST_SENDING.
Referenced by ngx_stream_brix_recv().