nginx-xrootd: src/protocols/root/connection/recv_process.c File Reference
recv_process.c File Reference
#include "recv_frame.h"
#include "disconnect.h"
#include "fd_table.h"
#include "tls.h"
#include "budget.h"
#include "deadline.h"
#include "net/manager/pending.h"
#include "fs/xfer/stage_waiter.h"
#include "protocols/root/handoff/handoff.h"
Functions
static uint32_t brix_max_payload_for_request (uint16_t reqid)
static ngx_int_t brix_ensure_payload_buffer (brix_ctx_t *ctx, ngx_connection_t *c, uint32_t dlen)
static ngx_int_t brix_grow_payload_buffer (brix_ctx_t *ctx, ngx_connection_t *c, uint32_t dlen)
static ngx_flag_t brix_recv_should_defer (brix_ctx_t *ctx)
static ngx_flag_t brix_recv_try_pipeline_read (brix_ctx_t *ctx)
static brix_recv_step_t brix_recv_extend_body (brix_ctx_t *ctx, ngx_connection_t *c)
static brix_recv_step_t brix_recv_after_header (ngx_stream_session_t *s, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, brix_ctx_t *ctx, ngx_event_t *rev, size_t *rx_pending)
static brix_recv_step_t brix_recv_after_payload (ngx_stream_session_t *s, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, brix_ctx_t *ctx, ngx_event_t *rev, size_t *rx_pending)
brix_recv_step_t brix_recv_process_frame (ngx_stream_session_t *s, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, brix_ctx_t *ctx, ngx_event_t *rev, size_t *rx_pending)
Function Documentation
brix_ensure_payload_buffer()
static ngx_int_t brix_ensure_payload_buffer (brix_ctx_t * ctx, ngx_connection_t * c, uint32_t dlen) static
Definition at line 53 of file recv_process.c.
References c, brix_ctx_recv_t::payload, brix_ctx_recv_t::payload_buf, brix_ctx_recv_t::payload_buf_size, and brix_ctx_t::recv.
Referenced by brix_recv_after_header().
brix_grow_payload_buffer()
static ngx_int_t brix_grow_payload_buffer (brix_ctx_t * ctx, ngx_connection_t * c, uint32_t dlen) static
Definition at line 91 of file recv_process.c.
References c, ngx_memcpy, brix_ctx_recv_t::payload, brix_ctx_recv_t::payload_buf, brix_ctx_recv_t::payload_buf_size, brix_ctx_recv_t::payload_pos, and brix_ctx_t::recv.
Referenced by brix_recv_extend_body().
brix_max_payload_for_request()
static uint32_t brix_max_payload_for_request (uint16_t reqid) static
Definition at line 24 of file recv_process.c.
References BRIX_MAX_AUTH_PAYLOAD, BRIX_MAX_PATH, BRIX_MAX_PREPARE_PAYLOAD, BRIX_MAX_WRITE_PAYLOAD, BRIX_READV_MAXSEGS, BRIX_READV_SEGSIZE, kXR_auth, kXR_chkpoint, kXR_pgwrite, kXR_prepare, kXR_readv, kXR_write, and kXR_writev.
Referenced by brix_recv_after_header().
brix_recv_after_header()
static brix_recv_step_t brix_recv_after_header (ngx_stream_session_t * s, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, brix_ctx_t * ctx, ngx_event_t * rev, size_t * rx_pending) static
Definition at line 227 of file recv_process.c.
References ClientRequestHdr::body, brix_dispatch(), brix_ensure_payload_buffer(), brix_max_payload_for_request(), brix_recv_should_defer(), BRIX_RECV_STEP_BREAK, BRIX_RECV_STEP_CONTINUE, BRIX_RECV_STEP_RETURN, brix_recv_try_pipeline_read(), BRIX_SRV_METRIC_ADD, BRIX_SRV_METRIC_INC, brix_start_tls(), c, brix_ctx_recv_t::cur_body, brix_ctx_recv_t::cur_body_extended, brix_ctx_recv_t::cur_body_extra, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, brix_ctx_recv_t::cur_streamid, ClientRequestHdr::dlen, brix_ctx_recv_t::hdr_buf, brix_ctx_recv_t::hdr_pos, ngx_memcpy, brix_ctx_t::out, brix_ctx_recv_t::payload, brix_ctx_recv_t::payload_pos, brix_ctx_t::recv, brix_ctx_out_t::recv_deferred, ClientRequestHdr::requestid, brix_ctx_out_t::resp_pipelinable, brix_ctx_t::state, ClientRequestHdr::streamid, brix_ctx_t::tls_pending, XRD_ST_AIO, XRD_ST_REQ_HEADER, XRD_ST_REQ_PAYLOAD, and XRD_ST_SENDING.
Referenced by brix_recv_process_frame().
brix_recv_after_payload()
static brix_recv_step_t brix_recv_after_payload (ngx_stream_session_t * s, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, brix_ctx_t * ctx, ngx_event_t * rev, size_t * rx_pending) static
Definition at line 346 of file recv_process.c.
References brix_dispatch(), brix_recv_extend_body(), brix_recv_should_defer(), BRIX_RECV_STEP_BREAK, BRIX_RECV_STEP_CONTINUE, BRIX_RECV_STEP_NEXT, BRIX_RECV_STEP_RETURN, brix_recv_try_pipeline_read(), BRIX_SRV_METRIC_ADD, c, brix_ctx_recv_t::cur_reqid, brix_ctx_recv_t::hdr_pos, kXR_write, brix_ctx_t::out, brix_ctx_t::recv, brix_ctx_out_t::recv_deferred, brix_ctx_out_t::resp_pipelinable, brix_ctx_t::state, brix_ctx_out_t::wr_inflight, XRD_ST_AIO, XRD_ST_REQ_HEADER, and XRD_ST_SENDING.
Referenced by brix_recv_process_frame().
brix_recv_extend_body()
static brix_recv_step_t brix_recv_extend_body (brix_ctx_t * ctx, ngx_connection_t * c) static
Definition at line 172 of file recv_process.c.
References brix_ckpxeq_body_extra(), brix_grow_payload_buffer(), BRIX_RECV_STEP_BREAK, BRIX_RECV_STEP_CONTINUE, BRIX_RECV_STEP_NEXT, brix_writev_body_extra(), c, brix_ctx_recv_t::cur_body, brix_ctx_recv_t::cur_body_extended, brix_ctx_recv_t::cur_body_extra, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, kXR_chkpoint, kXR_ckpXeq, kXR_writev, brix_ctx_recv_t::payload, brix_ctx_t::recv, and XRD_REQUEST_HDR_LEN.
Referenced by brix_recv_after_payload().
brix_recv_process_frame()
brix_recv_step_t brix_recv_process_frame (ngx_stream_session_t * s, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, brix_ctx_t * ctx, ngx_event_t * rev, size_t * rx_pending)
Definition at line 423 of file recv_process.c.
References brix_process_handshake(), brix_recv_after_header(), brix_recv_after_payload(), BRIX_RECV_STEP_BREAK, BRIX_RECV_STEP_CONTINUE, c, brix_ctx_recv_t::hdr_pos, brix_ctx_t::recv, s, brix_ctx_t::state, XRD_ST_HANDSHAKE, and XRD_ST_REQ_HEADER.
Referenced by ngx_stream_brix_recv().
brix_recv_should_defer()
static ngx_flag_t brix_recv_should_defer (brix_ctx_t * ctx) static
Definition at line 134 of file recv_process.c.
References brix_ctx_out_t::count, brix_ctx_recv_t::cur_reqid, kXR_read, kXR_write, brix_ctx_t::out, brix_ctx_t::recv, and brix_ctx_out_t::wr_inflight.
Referenced by brix_recv_after_header(), and brix_recv_after_payload().
brix_recv_try_pipeline_read()
static ngx_flag_t brix_recv_try_pipeline_read (brix_ctx_t * ctx) static
Definition at line 150 of file recv_process.c.
References brix_ctx_out_t::count, brix_ctx_recv_t::cur_reqid, kXR_read, brix_ctx_t::out, brix_ctx_out_t::pipeline_depth, brix_ctx_t::rd, brix_ctx_t::recv, brix_ctx_out_t::resp_pipelinable, brix_ctx_t::state, brix_ctx_rd_t::win_active, and XRD_ST_SENDING.
Referenced by brix_recv_after_header(), and brix_recv_after_payload().