nginx-xrootd: src/net/cms/recv_prepare.c File Reference
recv_prepare.c File Reference
#include "cms_internal.h"
#include "recv_internal.h"
#include "node_ops.h"
#include "rrdata.h"
#include "reqid_map.h"
#include "fs/xfer/stage_request_registry.h"
#include <time.h>
Functions
static int cms_prep_path_ok (const char *path)
static ngx_int_t cms_prep_add (ngx_brix_cms_ctx_t *ctx, uint32_t streamid, const brix_cms_rrdata_t *d, const brix_cms_node_plan_t *plan)
static ngx_int_t cms_prep_del (ngx_brix_cms_ctx_t *ctx, const brix_cms_node_plan_t *plan)
ngx_int_t cms_node_exec_prepare (ngx_brix_cms_ctx_t *ctx, u_char code, uint32_t streamid, const u_char *payload, size_t plen)
Function Documentation
cms_node_exec_prepare()
ngx_int_t cms_node_exec_prepare (ngx_brix_cms_ctx_t * ctx, u_char code, uint32_t streamid, const u_char * payload, size_t plen)
Definition at line 129 of file recv_prepare.c.
References brix_cms_node_plan_t::action, brix_cms_node_plan(), brix_cms_rrdata_parse(), CMS_ERR_EINVAL, cms_prep_add(), cms_prep_del(), code, ngx_brix_cms_send_error(), and XRDCMS_NACT_PREPADD.
Referenced by cms_frame_prepare().
cms_prep_add()
static ngx_int_t cms_prep_add (ngx_brix_cms_ctx_t * ctx, uint32_t streamid, const brix_cms_rrdata_t * d, const brix_cms_node_plan_t * plan) static
Definition at line 53 of file recv_prepare.c.
References brix_cms_reqid_map_put(), BRIX_STAGE_DN_LEN, brix_stage_registry_singleton(), BRIX_STAGE_REQID_LEN, brix_stage_request_add(), CMS_ERR_EINVAL, cms_prep_path_ok(), brix_cms_rrdata_t::ident, brix_cms_rrdata_t::ident_len, brix_stage_request_view_t::lfn, ngx_brix_cms_send_error(), ngx_memcpy, brix_cms_node_plan_t::notify, brix_cms_node_plan_t::path, brix_cms_node_plan_t::prty, brix_cms_node_plan_t::reqid, brix_stage_request_view_t::requester_dn, and brix_stage_request_view_t::tod_expire.
Referenced by cms_node_exec_prepare().
cms_prep_del()
static ngx_int_t cms_prep_del (ngx_brix_cms_ctx_t * ctx, const brix_cms_node_plan_t * plan) static
Definition at line 109 of file recv_prepare.c.
References brix_cms_reqid_map_take(), brix_stage_registry_singleton(), BRIX_STAGE_REQID_LEN, brix_stage_request_delete(), and brix_cms_node_plan_t::reqid.
Referenced by cms_node_exec_prepare().
cms_prep_path_ok()
static int cms_prep_path_ok (const char * path) static
Definition at line 39 of file recv_prepare.c.
References BRIX_STAGE_LFN_LEN.
Referenced by cms_prep_add().