nginx-xrootd: src/net/cms/recv_internal.h File Reference
recv_internal.h File Reference
#include "cms_internal.h"
Functions
ngx_int_t ngx_brix_cms_process_frame (ngx_brix_cms_ctx_t *ctx)
ngx_int_t brix_cms_wake_pending_session (ngx_log_t *log, uint32_t streamid, const char *host, uint16_t port)
ngx_connection_t * brix_cms_client_conn_by_fd (int fd)
ngx_int_t cms_node_exec_forward (ngx_brix_cms_ctx_t *ctx, u_char code, uint32_t streamid, const u_char *payload, size_t plen)
ngx_int_t cms_node_exec_prepare (ngx_brix_cms_ctx_t *ctx, u_char code, uint32_t streamid, const u_char *payload, size_t plen)
Function Documentation
brix_cms_client_conn_by_fd()
ngx_connection_t * brix_cms_client_conn_by_fd (int fd)
Definition at line 44 of file recv_frame.c.
References c.
Referenced by brix_cms_fanout_finalize(), and brix_cms_wake_pending_session().
brix_cms_wake_pending_session()
ngx_int_t brix_cms_wake_pending_session (ngx_log_t * log, uint32_t streamid, const char * host, uint16_t port)
Definition at line 80 of file recv_frame.c.
References brix_cms_client_conn_by_fd(), brix_net_host_chars_valid(), brix_pending_lookup(), brix_pending_remove(), brix_pending_unlock(), brix_sanitize_log_string(), brix_schedule_read_resume(), brix_send_redirect(), brix_pending_locate_t::client_streamid, brix_pending_locate_t::conn_fd, brix_pending_locate_t::conn_number, brix_ctx_recv_t::cur_streamid, host, log, ngx_stream_brix_module, port, brix_ctx_t::recv, brix_ctx_t::state, XRD_ST_REQ_HEADER, and XRD_ST_WAITING_CMS.
Referenced by cms_frame_redirect(), and cms_srv_frame_have().
cms_node_exec_forward()
ngx_int_t cms_node_exec_forward (ngx_brix_cms_ctx_t * ctx, u_char code, uint32_t streamid, const u_char * payload, size_t plen)
Definition at line 272 of file recv_forward.c.
References brix_cms_node_plan(), brix_cms_rrdata_parse(), brix_sd_default_driver(), brix_vfs_backend_resolve(), CMS_ERR_EINVAL, cms_forward_via_driver(), cms_forward_via_posix(), code, and ngx_brix_cms_send_error().
Referenced by cms_frame_forward().
cms_node_exec_prepare()
ngx_int_t cms_node_exec_prepare (ngx_brix_cms_ctx_t * ctx, u_char code, uint32_t streamid, const u_char * payload, size_t plen)
Definition at line 129 of file recv_prepare.c.
References brix_cms_node_plan_t::action, brix_cms_node_plan(), brix_cms_rrdata_parse(), CMS_ERR_EINVAL, cms_prep_add(), cms_prep_del(), code, ngx_brix_cms_send_error(), and XRDCMS_NACT_PREPADD.
Referenced by cms_frame_prepare().
ngx_brix_cms_process_frame()
ngx_int_t ngx_brix_cms_process_frame (ngx_brix_cms_ctx_t * ctx)
Definition at line 416 of file recv_frame.c.
References brix_cms_route_lookup(), cms_frame_table, code, brix_cms_route_t::name, ngx_brix_cms_get32(), and XRDCMS_ROLE_NODE.
Referenced by ngx_brix_cms_read_handler().