nginx-xrootd: src/net/manager/redir_cache.c File Reference
redir_cache.c File Reference
#include "redir_cache.h"
#include "core/compat/shm_slots.h"
#include <ngx_shmtx.h>
#include <string.h>
Data Structures
struct brix_redir_cache_entry_t
struct brix_redir_cache_t
Macros
#define BRIX_REDIR_PROBE_MAX 32
Functions
static brix_redir_cache_t * redir_cache (void)
static uint32_t redir_hash (const char *path)
static ngx_int_t redir_cache_shm_init (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t brix_redir_cache_configure (ngx_conf_t *cf, ngx_uint_t slots)
int brix_redir_cache_lookup (const char *path, char *host_out, size_t host_size, uint16_t *port_out)
void brix_redir_cache_insert (const char *path, const char *host, uint16_t port, ngx_msec_t ttl_ms)
Variables
static ngx_shm_zone_t * brix_redir_shm_zone
static ngx_shmtx_t brix_redir_mutex
static ngx_uint_t brix_redir_cache_nslots = 512
Macro Definition Documentation
BRIX_REDIR_PROBE_MAX
#define BRIX_REDIR_PROBE_MAX 32
Definition at line 54 of file redir_cache.c.
Function Documentation
brix_redir_cache_configure()
ngx_int_t brix_redir_cache_configure (ngx_conf_t * cf, ngx_uint_t slots)
Definition at line 124 of file redir_cache.c.
References brix_redir_cache_nslots, BRIX_REDIR_CACHE_SLOTS, brix_redir_shm_zone, brix_shm_zone_size(), name, ngx_stream_brix_module, and redir_cache_shm_init().
Referenced by postconf_redir_cache().
brix_redir_cache_insert()
void brix_redir_cache_insert (const char * path, const char * host, uint16_t port, ngx_msec_t ttl_ms)
Definition at line 191 of file redir_cache.c.
References brix_redir_mutex, BRIX_REDIR_PROBE_MAX, c, brix_redir_cache_entry_t::expires, brix_redir_cache_entry_t::host, host, brix_redir_cache_entry_t::in_use, brix_redir_cache_entry_t::path, port, brix_redir_cache_entry_t::port, probe(), redir_cache(), and redir_hash().
Referenced by brix_open_manager_redirect(), and locate_try_manager().
brix_redir_cache_lookup()
int brix_redir_cache_lookup (const char * path, char * host_out, size_t host_size, uint16_t * port_out)
Definition at line 151 of file redir_cache.c.
References brix_redir_mutex, BRIX_REDIR_PROBE_MAX, c, brix_redir_cache_entry_t::expires, brix_redir_cache_entry_t::host, brix_redir_cache_entry_t::in_use, brix_redir_cache_entry_t::path, brix_redir_cache_entry_t::port, probe(), redir_cache(), and redir_hash().
Referenced by brix_open_manager_redirect(), and locate_try_manager().
redir_cache()
static brix_redir_cache_t * redir_cache (void) static
Definition at line 66 of file redir_cache.c.
References brix_redir_shm_zone.
Referenced by brix_redir_cache_insert(), and brix_redir_cache_lookup().
redir_cache_shm_init()
static ngx_int_t redir_cache_shm_init (ngx_shm_zone_t * shm_zone, void * data) static
Definition at line 92 of file redir_cache.c.
References brix_redir_cache_nslots, brix_redir_mutex, brix_shm_table_alloc(), and c.
Referenced by brix_redir_cache_configure().
redir_hash()
static uint32_t redir_hash (const char * path) static
Definition at line 79 of file redir_cache.c.
Referenced by brix_redir_cache_insert(), and brix_redir_cache_lookup().
Variable Documentation
brix_redir_cache_nslots
ngx_uint_t brix_redir_cache_nslots = 512 static
Definition at line 62 of file redir_cache.c.
Referenced by brix_redir_cache_configure(), and redir_cache_shm_init().
brix_redir_mutex
ngx_shmtx_t brix_redir_mutex static
Definition at line 58 of file redir_cache.c.
Referenced by brix_redir_cache_insert(), brix_redir_cache_lookup(), and redir_cache_shm_init().
brix_redir_shm_zone
ngx_shm_zone_t* brix_redir_shm_zone static
Definition at line 57 of file redir_cache.c.
Referenced by brix_redir_cache_configure(), and redir_cache().