nginx-xrootd: src/net/manager/redir_cache.h File Reference
redir_cache.h File Reference
#include "core/ngx_brix_module.h"
Macros
#define BRIX_REDIR_CACHE_SLOTS 512
Functions
ngx_int_t brix_redir_cache_configure (ngx_conf_t *cf, ngx_uint_t slots)
int brix_redir_cache_lookup (const char *path, char *host_out, size_t host_size, uint16_t *port_out)
void brix_redir_cache_insert (const char *path, const char *host, uint16_t port, ngx_msec_t ttl_ms)
Macro Definition Documentation
BRIX_REDIR_CACHE_SLOTS
#define BRIX_REDIR_CACHE_SLOTS 512
Definition at line 20 of file redir_cache.h.
Function Documentation
brix_redir_cache_configure()
ngx_int_t brix_redir_cache_configure (ngx_conf_t * cf, ngx_uint_t slots)
Definition at line 124 of file redir_cache.c.
References brix_redir_cache_nslots, BRIX_REDIR_CACHE_SLOTS, brix_redir_shm_zone, brix_shm_zone_size(), name, ngx_stream_brix_module, and redir_cache_shm_init().
Referenced by postconf_redir_cache().
brix_redir_cache_insert()
void brix_redir_cache_insert (const char * path, const char * host, uint16_t port, ngx_msec_t ttl_ms)
Definition at line 191 of file redir_cache.c.
References brix_redir_mutex, BRIX_REDIR_PROBE_MAX, c, brix_redir_cache_entry_t::expires, brix_redir_cache_entry_t::host, brix_redir_cache_entry_t::in_use, brix_redir_cache_entry_t::path, brix_redir_cache_entry_t::port, probe(), redir_cache(), and redir_hash().
Referenced by brix_open_manager_redirect(), and locate_try_manager().
brix_redir_cache_lookup()
int brix_redir_cache_lookup (const char * path, char * host_out, size_t host_size, uint16_t * port_out)
Definition at line 151 of file redir_cache.c.
References brix_redir_mutex, BRIX_REDIR_PROBE_MAX, c, brix_redir_cache_entry_t::expires, brix_redir_cache_entry_t::host, brix_redir_cache_entry_t::in_use, brix_redir_cache_entry_t::path, brix_redir_cache_entry_t::port, probe(), redir_cache(), and redir_hash().
Referenced by brix_open_manager_redirect(), and locate_try_manager().