nginx-xrootd: src/auth/token/refresh.c File Reference
refresh.c File Reference
#include "core/config/config.h"
#include "token.h"
#include <sys/stat.h>
Functions
static void brix_token_jwks_try_reload (ngx_stream_brix_srv_conf_t *conf, ngx_log_t *log)
static void brix_token_jwks_refresh_handler (ngx_event_t *ev)
void brix_token_jwks_schedule_refresh (ngx_cycle_t *cycle, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_token_jwks_refresh_handler()
static void brix_token_jwks_refresh_handler (ngx_event_t * ev) static
Definition at line 81 of file refresh.c.
References brix_token_jwks_try_reload().
Referenced by brix_token_jwks_schedule_refresh().
brix_token_jwks_schedule_refresh()
void brix_token_jwks_schedule_refresh (ngx_cycle_t * cycle, ngx_stream_brix_srv_conf_t * conf)
Definition at line 110 of file refresh.c.
References brix_token_jwks_refresh_handler(), and ngx_pcalloc().
Referenced by brix_init_server_crl_jwks().
brix_token_jwks_try_reload()
static void brix_token_jwks_try_reload (ngx_stream_brix_srv_conf_t * conf, ngx_log_t * log) static
Definition at line 40 of file refresh.c.
References brix_jwks_free(), brix_jwks_load(), BRIX_MAX_JWKS_KEYS, log, ngx_memcpy, and stat().
Referenced by brix_token_jwks_refresh_handler().