nginx-xrootd: src/net/manager/registry_select.c File Reference
registry_select.c File Reference
#include "registry_internal.h"
#include "core/fnv.h"
Data Structures
struct srv_sel_tier_t
struct srv_sel_state_t
Macros
#define SRV_SEL_AFFINITY_MAX 64
Functions
int srv_path_matches (const char *paths, const char *path)
static void srv_sel_tier_init (srv_sel_tier_t *tier, int for_write)
static void srv_sel_state_init (srv_sel_state_t *st, int for_write)
static int srv_sel_metric_better (const srv_sel_tier_t *tier, uint32_t metric, int for_write)
static void srv_sel_tier_offer (srv_sel_tier_t *tier, int idx, uint32_t metric, int for_write)
static uint32_t srv_sel_load_metric (uint32_t metric, uint32_t load_pct, int for_write)
static void srv_sel_state_consider (srv_sel_state_t *st, int idx, const brix_srv_entry_t *e, int is_black)
static uint32_t srv_sel_path_hash (const char *path)
static int srv_sel_state_winner (const srv_sel_state_t *st)
int srv_select_core (const char *path, int for_write, int allow_blacklisted, char *host_out, size_t host_size, uint16_t *port_out)
int brix_srv_select (const char *path, int for_write, char *host_out, size_t host_size, uint16_t *port_out)
int brix_srv_select_or_blacklisted (const char *path, int for_write, char *host_out, size_t host_size, uint16_t *port_out)
int brix_srv_count_matching (const char *path)
int brix_manager_tried_exhausted (const u_char *payload, size_t payload_len, const char *clean_path)
void brix_srv_blacklist (const char *host, uint16_t port, ngx_msec_t duration_ms)
int brix_srv_undrain (const char *host, uint16_t port)
int brix_srv_paths_cover (const char *paths, const char *path)
int brix_srv_is_blacklisted (const char *host, uint16_t port)
Macro Definition Documentation
SRV_SEL_AFFINITY_MAX
#define SRV_SEL_AFFINITY_MAX 64
Definition at line 84 of file registry_select.c.
Function Documentation
brix_manager_tried_exhausted()
int brix_manager_tried_exhausted (const u_char * payload, size_t payload_len, const char * clean_path)
Definition at line 425 of file registry_select.c.
References brix_srv_count_matching(), and ngx_memcpy.
Referenced by brix_open_manager_redirect(), brix_qcksum_manager_bounce(), and stat_manager_route().
brix_srv_blacklist()
void brix_srv_blacklist (const char * host, uint16_t port, ngx_msec_t duration_ms)
Definition at line 492 of file registry_select.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::error_count, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, port, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by admin_cluster_drain(), brix_cms_blfile_poll(), brix_cms_srv_close(), and cms_srv_frame_status().
brix_srv_count_matching()
int brix_srv_count_matching (const char * path)
Definition at line 381 of file registry_select.c.
References brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::in_use, brix_srv_entry_t::paths, brix_srv_table_t::slots, srv_path_matches(), and srv_table().
Referenced by brix_cms_fanout_mutation(), brix_manager_tried_exhausted(), and cms_srv_frame_statfs().
brix_srv_is_blacklisted()
int brix_srv_is_blacklisted (const char * host, uint16_t port)
Definition at line 574 of file registry_select.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_mutex, brix_srv_table_t::capacity, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, port, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by brix_cms_fanout_collect_eligible(), cms_srv_frame_have(), and locate_try_dynamic().
brix_srv_paths_cover()
int brix_srv_paths_cover (const char * paths, const char * path)
Definition at line 563 of file registry_select.c.
References srv_path_matches().
Referenced by brix_cms_fanout_collect_eligible(), cms_srv_frame_have(), and locate_try_dynamic().
brix_srv_select()
int brix_srv_select (const char * path, int for_write, char * host_out, size_t host_size, uint16_t * port_out)
Definition at line 347 of file registry_select.c.
References srv_select_core().
Referenced by brix_dirlist_check_redirect(), brix_qcksum_manager_bounce(), cms_frame_state(), locate_try_manager(), and tpc_handle_dest().
brix_srv_select_or_blacklisted()
int brix_srv_select_or_blacklisted (const char * path, int for_write, char * host_out, size_t host_size, uint16_t * port_out)
Definition at line 358 of file registry_select.c.
References srv_select_core().
Referenced by brix_open_manager_redirect(), manager_redirect_mutation(), and stat_manager_route().
brix_srv_undrain()
int brix_srv_undrain (const char * host, uint16_t port)
Definition at line 528 of file registry_select.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::error_count, brix_srv_entry_t::hc_fail_count, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, port, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by admin_cluster_undrain(), and cms_srv_frame_status().
srv_path_matches()
int srv_path_matches (const char * paths, const char * path)
Definition at line 11 of file registry_select.c.
Referenced by brix_srv_count_matching(), brix_srv_locate_all(), brix_srv_paths_cover(), and srv_select_core().
srv_sel_load_metric()
static uint32_t srv_sel_load_metric (uint32_t metric, uint32_t load_pct, int for_write) static
Definition at line 171 of file registry_select.c.
References brix_srv_load_weight.
Referenced by srv_sel_state_consider().
srv_sel_metric_better()
static int srv_sel_metric_better (const srv_sel_tier_t * tier, uint32_t metric, int for_write) static
Definition at line 132 of file registry_select.c.
References srv_sel_tier_t::idx, and srv_sel_tier_t::val.
Referenced by srv_sel_tier_offer().
srv_sel_path_hash()
static uint32_t srv_sel_path_hash (const char * path) static
Definition at line 228 of file registry_select.c.
References BRIX_FNV1A32_OFFSET_BASIS, and BRIX_FNV1A32_PRIME.
Referenced by srv_select_core().
srv_sel_state_consider()
static void srv_sel_state_consider (srv_sel_state_t * st, int idx, const brix_srv_entry_t * e, int is_black) static
Definition at line 187 of file registry_select.c.
References srv_sel_state_t::any, srv_sel_state_t::black, brix_srv_stale_after_ms, srv_sel_state_t::for_write, brix_srv_entry_t::free_mb, srv_sel_state_t::fresh, srv_sel_state_t::fresh_cands, brix_srv_entry_t::last_seen, brix_srv_entry_t::load_pct, srv_sel_state_t::n_fresh, SRV_SEL_AFFINITY_MAX, srv_sel_load_metric(), srv_sel_tier_offer(), and brix_srv_entry_t::util_pct.
Referenced by srv_select_core().
srv_sel_state_init()
static void srv_sel_state_init (srv_sel_state_t * st, int for_write) static
Definition at line 115 of file registry_select.c.
References srv_sel_state_t::any, srv_sel_state_t::black, srv_sel_state_t::for_write, srv_sel_state_t::fresh, srv_sel_state_t::n_fresh, and srv_sel_tier_init().
Referenced by srv_select_core().
srv_sel_state_winner()
static int srv_sel_state_winner (const srv_sel_state_t * st) static
Definition at line 245 of file registry_select.c.
References srv_sel_state_t::any, srv_sel_state_t::black, srv_sel_state_t::fresh, and srv_sel_tier_t::idx.
Referenced by srv_select_core().
srv_sel_tier_init()
static void srv_sel_tier_init (srv_sel_tier_t * tier, int for_write) static
Definition at line 104 of file registry_select.c.
References srv_sel_tier_t::idx, and srv_sel_tier_t::val.
Referenced by srv_sel_state_init().
srv_sel_tier_offer()
static void srv_sel_tier_offer (srv_sel_tier_t * tier, int idx, uint32_t metric, int for_write) static
Definition at line 146 of file registry_select.c.
References srv_sel_tier_t::idx, srv_sel_metric_better(), and srv_sel_tier_t::val.
Referenced by srv_sel_state_consider().
srv_select_core()
int srv_select_core (const char * path, int for_write, int allow_blacklisted, char * host_out, size_t host_size, uint16_t * port_out)
Definition at line 281 of file registry_select.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_affinity, brix_srv_mutex, brix_srv_table_t::capacity, srv_sel_state_t::fresh_cands, brix_srv_entry_t::host, brix_srv_entry_t::in_use, srv_sel_state_t::n_fresh, brix_srv_entry_t::paths, brix_srv_entry_t::port, brix_srv_table_t::slots, srv_path_matches(), srv_sel_path_hash(), srv_sel_state_consider(), srv_sel_state_init(), srv_sel_state_winner(), and srv_table().
Referenced by brix_srv_select(), and brix_srv_select_or_blacklisted().