nginx-xrootd: src/net/manager/registry_select_blacklist.c File Reference
registry_select_blacklist.c File Reference
#include "registry_internal.h"
Functions
void brix_srv_blacklist (const char *host, uint16_t port, ngx_msec_t duration_ms)
int brix_srv_undrain (const char *host, uint16_t port)
int brix_srv_paths_cover (const char *paths, const char *path)
int brix_srv_is_blacklisted (const char *host, uint16_t port)
Function Documentation
brix_srv_blacklist()
void brix_srv_blacklist (const char * host, uint16_t port, ngx_msec_t duration_ms)
Definition at line 28 of file registry_select_blacklist.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::error_count, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, port, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by admin_cluster_drain(), brix_cms_blfile_poll(), brix_cms_srv_close(), and cms_srv_frame_status().
brix_srv_is_blacklisted()
int brix_srv_is_blacklisted (const char * host, uint16_t port)
Definition at line 110 of file registry_select_blacklist.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_mutex, brix_srv_table_t::capacity, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, port, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by brix_cms_fanout_collect_eligible(), cms_srv_frame_have(), and locate_try_dynamic().
brix_srv_paths_cover()
int brix_srv_paths_cover (const char * paths, const char * path)
Definition at line 99 of file registry_select_blacklist.c.
References srv_path_matches().
Referenced by brix_cms_fanout_collect_eligible(), cms_srv_frame_have(), and locate_try_dynamic().
brix_srv_undrain()
int brix_srv_undrain (const char * host, uint16_t port)
Definition at line 64 of file registry_select_blacklist.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::error_count, brix_srv_entry_t::hc_fail_count, host, brix_srv_entry_t::host, brix_srv_entry_t::in_use, port, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by admin_cluster_undrain(), and cms_srv_frame_status().