nginx-xrootd: src/net/manager/registry_health.c File Reference
registry_health.c File Reference
#include "registry_internal.h"
Functions
int brix_srv_hc_claim (char *host_out, size_t host_size, uint16_t *port_out, ngx_msec_t interval_ms, ngx_msec_t *next_due_ms)
void brix_srv_hc_pass (const char *host, uint16_t port)
int brix_srv_hc_fail (const char *host, uint16_t port, uint32_t threshold, ngx_msec_t blacklist_ms)
int brix_srv_locate_all (const char *path, int for_write, char *buf, size_t bufsz)
void brix_srv_unregister_path (const char *host, uint16_t port, const char *path)
void brix_srv_aggregate_space (uint32_t *total_free_mb, uint32_t *avg_util_pct)
ngx_uint_t brix_srv_snapshot (brix_srv_snapshot_entry_t *out, ngx_uint_t max_entries, ngx_msec_t now)
Function Documentation
brix_srv_aggregate_space()
void brix_srv_aggregate_space (uint32_t * total_free_mb, uint32_t * avg_util_pct)
Definition at line 311 of file registry_health.c.
References brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::free_mb, brix_srv_entry_t::in_use, brix_srv_table_t::slots, srv_table(), and brix_srv_entry_t::util_pct.
Referenced by cms_srv_process_frame(), ngx_brix_cms_send_avail(), ngx_brix_cms_send_load(), and ngx_brix_cms_send_login().
brix_srv_hc_claim()
int brix_srv_hc_claim (char * host_out, size_t host_size, uint16_t * port_out, ngx_msec_t interval_ms, ngx_msec_t * next_due_ms)
Definition at line 10 of file registry_health.c.
References brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::hc_in_progress, brix_srv_entry_t::hc_next_check, brix_srv_entry_t::host, brix_srv_entry_t::in_use, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by brix_hc_timer_handler().
brix_srv_hc_fail()
int brix_srv_hc_fail (const char * host, uint16_t port, uint32_t threshold, ngx_msec_t blacklist_ms)
Definition at line 102 of file registry_health.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::hc_fail_count, brix_srv_entry_t::hc_in_progress, brix_srv_entry_t::host, brix_srv_entry_t::in_use, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by brix_hc_finish(), brix_hc_pre_connect_fail(), and brix_hc_start().
brix_srv_hc_pass()
void brix_srv_hc_pass (const char * host, uint16_t port)
Definition at line 66 of file registry_health.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::hc_fail_count, brix_srv_entry_t::hc_in_progress, brix_srv_entry_t::hc_last_ok, brix_srv_entry_t::host, brix_srv_entry_t::in_use, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by brix_hc_finish().
brix_srv_locate_all()
int brix_srv_locate_all (const char * path, int for_write, char * buf, size_t bufsz)
Definition at line 160 of file registry_health.c.
References brix_srv_entry_t::blacklisted_until, brix_format_host_port(), brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::host, brix_srv_entry_t::in_use, brix_srv_entry_t::paths, brix_srv_entry_t::port, brix_srv_table_t::slots, srv_path_matches(), and srv_table().
brix_srv_snapshot()
ngx_uint_t brix_srv_snapshot (brix_srv_snapshot_entry_t * out, ngx_uint_t max_entries, ngx_msec_t now)
Definition at line 352 of file registry_health.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_snapshot_entry_t::blacklisted_until, brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::error_count, brix_srv_snapshot_entry_t::error_count, brix_srv_entry_t::free_mb, brix_srv_snapshot_entry_t::free_mb, brix_srv_entry_t::hc_fail_count, brix_srv_snapshot_entry_t::hc_fail_count, brix_srv_entry_t::hc_last_ok, brix_srv_snapshot_entry_t::hc_last_ok, brix_srv_entry_t::host, brix_srv_snapshot_entry_t::host, brix_srv_entry_t::in_use, brix_srv_entry_t::last_seen, brix_srv_snapshot_entry_t::last_seen, brix_srv_entry_t::paths, brix_srv_snapshot_entry_t::paths, brix_srv_entry_t::port, brix_srv_snapshot_entry_t::port, brix_srv_table_t::slots, srv_table(), brix_srv_entry_t::util_pct, and brix_srv_snapshot_entry_t::util_pct.
Referenced by brix_export_cluster_metrics(), and dashboard_fill_cluster().
brix_srv_unregister_path()
void brix_srv_unregister_path (const char * host, uint16_t port, const char * path)
Definition at line 236 of file registry_health.c.
References brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::host, brix_srv_entry_t::in_use, brix_srv_entry_t::paths, brix_srv_entry_t::port, brix_srv_table_t::slots, and srv_table().
Referenced by brix_cache_evict_one(), and cms_srv_process_frame().