nginx-xrootd: src/net/manager/registry_internal.h File Reference
registry_internal.h File Reference
#include "registry.h"
#include "core/compat/net_target.h"
#include "core/compat/host_format.h"
#include "core/compat/shm_slots.h"
#include <ngx_shmtx.h>
#include <string.h>
Functions
brix_srv_table_t * srv_table (void)
int srv_path_matches (const char *paths, const char *path)
int srv_select_core (const char *path, int for_write, int allow_blacklisted, char *host_out, size_t host_size, uint16_t *port_out)
Variables
ngx_shmtx_t brix_srv_mutex
ngx_uint_t brix_srv_registry_nslots
ngx_msec_t brix_srv_stale_after_ms
Function Documentation
srv_path_matches()
int srv_path_matches (const char * paths, const char * path)
Definition at line 10 of file registry_select.c.
Referenced by brix_srv_count_matching(), brix_srv_locate_all(), and srv_select_core().
srv_select_core()
int srv_select_core (const char * path, int for_write, int allow_blacklisted, char * host_out, size_t host_size, uint16_t * port_out)
Definition at line 222 of file registry_select.c.
References brix_srv_entry_t::blacklisted_until, brix_srv_mutex, brix_srv_table_t::capacity, brix_srv_entry_t::host, brix_srv_entry_t::in_use, brix_srv_entry_t::paths, brix_srv_entry_t::port, brix_srv_table_t::slots, srv_path_matches(), srv_sel_state_consider(), srv_sel_state_init(), srv_sel_state_winner(), and srv_table().
Referenced by brix_srv_select(), and brix_srv_select_or_blacklisted().
srv_table()
brix_srv_table_t * srv_table (void)
Definition at line 23 of file registry.c.
References brix_srv_shm_zone.
Referenced by brix_srv_aggregate_space(), brix_srv_blacklist(), brix_srv_count_matching(), brix_srv_hc_claim(), brix_srv_hc_fail(), brix_srv_hc_pass(), brix_srv_locate_all(), brix_srv_register(), brix_srv_snapshot(), brix_srv_undrain(), brix_srv_unregister(), brix_srv_unregister_path(), brix_srv_update_load(), and srv_select_core().
Variable Documentation
brix_srv_mutex
ngx_shmtx_t brix_srv_mutex extern
Definition at line 8 of file registry.c.
Referenced by brix_srv_aggregate_space(), brix_srv_blacklist(), brix_srv_count_matching(), brix_srv_hc_claim(), brix_srv_hc_fail(), brix_srv_hc_pass(), brix_srv_locate_all(), brix_srv_register(), brix_srv_shm_init_zone(), brix_srv_snapshot(), brix_srv_undrain(), brix_srv_unregister(), brix_srv_unregister_path(), brix_srv_update_load(), and srv_select_core().
brix_srv_registry_nslots
ngx_uint_t brix_srv_registry_nslots extern
Definition at line 10 of file registry.c.
Referenced by brix_srv_configure_registry(), and brix_srv_shm_init_zone().
brix_srv_stale_after_ms
ngx_msec_t brix_srv_stale_after_ms extern
Definition at line 12 of file registry.c.
Referenced by brix_srv_set_stale_after(), and srv_sel_state_consider().