nginx-xrootd: src/protocols/root/relay/relay.c File Reference
relay.c File Reference
#include "core/ngx_brix_module.h"
#include "relay.h"
#include "relay_guard.h"
#include "net/tap/tap.h"
Data Structures
struct brix_relay_t
Macros
#define BRIX_RELAY_BUF (64 * 1024)
#define BRIX_RELAY_IDLE 75000 /* ms; drop a relay that stalls both ways */
Functions
char * brix_conf_set_transparent_proxy (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static void relay_audit_sink (void *ctx, const brix_tap_frame_t *f, brix_tap_dir_t dir, const uint8_t *payload, size_t payload_len)
static ngx_int_t relay_peer_get (ngx_peer_connection_t *pc, void *data)
static void relay_peer_free (ngx_peer_connection_t *pc, void *data, ngx_uint_t state)
static void relay_close (brix_relay_t *r)
static ngx_int_t relay_pump (brix_relay_t *r, ngx_connection_t *from, ngx_connection_t *to, u_char *buf, size_t *off, size_t *end, brix_tap_stream_t *dec)
static brix_relay_t * relay_from_client (ngx_event_t *ev)
static void relay_cu (brix_relay_t *r, ngx_event_t *ev)
static void relay_uc (brix_relay_t *r, ngx_event_t *ev)
static void relay_client_read (ngx_event_t *ev)
static void relay_client_write (ngx_event_t *ev)
static void relay_upstream_read (ngx_event_t *ev)
static void relay_upstream_write (ngx_event_t *ev)
static void relay_begin (brix_relay_t *r)
static void relay_connect_done (ngx_event_t *ev)
ngx_int_t brix_relay_start (ngx_stream_session_t *s, ngx_connection_t *c, void *srv_conf)
Macro Definition Documentation
BRIX_RELAY_BUF
#define BRIX_RELAY_BUF (64 * 1024)
Definition at line 15 of file relay.c.
BRIX_RELAY_IDLE
#define BRIX_RELAY_IDLE 75000 /* ms; drop a relay that stalls both ways */
Definition at line 16 of file relay.c.
Function Documentation
brix_conf_set_transparent_proxy()
char * brix_conf_set_transparent_proxy (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 56 of file relay.c.
References ngx_memcpy, ngx_pcalloc(), and ngx_pnalloc().
brix_relay_start()
ngx_int_t brix_relay_start (ngx_stream_session_t * s, ngx_connection_t * c, void * srv_conf)
Definition at line 322 of file relay.c.
References BRIX_RELAY_BUF, brix_relay_guard_init(), brix_relay_guard_sink(), BRIX_RELAY_IDLE, BRIX_TAP_C2U, brix_tap_register_sink(), brix_tap_stream_init(), BRIX_TAP_U2C, c, brix_relay_t::client, brix_relay_t::cu, brix_relay_t::cu_dec, brix_relay_t::cu_end, brix_relay_t::cu_off, brix_relay_guard_t::enable, brix_relay_t::guard, brix_relay_t::log, brix_ctx_t::metrics, brix_relay_t::metrics, ngx_pcalloc(), ngx_pnalloc(), ngx_stream_brix_module, brix_relay_t::peer, brix_ctx_t::relay, relay_audit_sink(), relay_begin(), relay_connect_done(), relay_peer_free(), relay_peer_get(), relay_upstream_read(), brix_relay_t::s, s, brix_ctx_t::state, brix_relay_t::tap, brix_relay_t::uc, brix_relay_t::uc_dec, brix_relay_t::uc_end, brix_relay_t::uc_off, brix_relay_t::upstream, and XRD_ST_PROXY.
Referenced by conn_try_relay().
relay_audit_sink()
static void relay_audit_sink (void * ctx, const brix_tap_frame_t * f, brix_tap_dir_t dir, const uint8_t * payload, size_t payload_len) static
Definition at line 107 of file relay.c.
References brix_tap_audit_format(), and log.
Referenced by brix_relay_start().
relay_begin()
static void relay_begin (brix_relay_t * r) static
Definition at line 269 of file relay.c.
References brix_relay_t::client, brix_relay_t::connected, brix_relay_t::cu, brix_relay_t::cu_dec, brix_relay_t::cu_end, brix_relay_t::cu_off, relay_client_read(), relay_client_write(), relay_close(), relay_pump(), relay_upstream_read(), relay_upstream_write(), brix_relay_t::uc, brix_relay_t::uc_dec, brix_relay_t::uc_end, brix_relay_t::uc_off, and brix_relay_t::upstream.
Referenced by brix_relay_start(), and relay_connect_done().
relay_client_read()
static void relay_client_read (ngx_event_t * ev) static
Definition at line 252 of file relay.c.
References relay_cu(), and relay_from_client().
Referenced by relay_begin().
relay_client_write()
static void relay_client_write (ngx_event_t * ev) static
Definition at line 255 of file relay.c.
References relay_from_client(), and relay_uc().
Referenced by relay_begin().
relay_close()
static void relay_close (brix_relay_t * r) static
Definition at line 135 of file relay.c.
References brix_relay_t::closed, ngx_brix_srv_metrics_t::connections_active, brix_relay_t::metrics, brix_relay_t::s, and brix_relay_t::upstream.
Referenced by relay_begin(), relay_connect_done(), relay_cu(), and relay_uc().
relay_connect_done()
static void relay_connect_done (ngx_event_t * ev) static
Definition at line 293 of file relay.c.
References brix_relay_t::client, brix_relay_t::peer, relay_begin(), and relay_close().
Referenced by brix_relay_start().
relay_cu()
static void relay_cu (brix_relay_t * r, ngx_event_t * ev) static
Definition at line 224 of file relay.c.
References brix_relay_t::client, brix_relay_t::cu, brix_relay_t::cu_dec, brix_relay_t::cu_end, brix_relay_t::cu_off, relay_close(), relay_pump(), and brix_relay_t::upstream.
Referenced by relay_client_read(), and relay_upstream_write().
relay_from_client()
static brix_relay_t * relay_from_client (ngx_event_t * ev) static
Definition at line 212 of file relay.c.
References c, ngx_stream_brix_module, brix_ctx_t::relay, and s.
Referenced by relay_client_read(), and relay_client_write().
relay_peer_free()
static void relay_peer_free (ngx_peer_connection_t * pc, void * data, ngx_uint_t state) static
Definition at line 127 of file relay.c.
Referenced by brix_relay_start().
relay_peer_get()
static ngx_int_t relay_peer_get (ngx_peer_connection_t * pc, void * data) static
Definition at line 124 of file relay.c.
Referenced by brix_relay_start().
relay_pump()
static ngx_int_t relay_pump (brix_relay_t * r, ngx_connection_t * from, ngx_connection_t * to, u_char * buf, size_t * off, size_t * end, brix_tap_stream_t * dec) static
Definition at line 165 of file relay.c.
References BRIX_RELAY_BUF, brix_relay_guard_should_drop(), BRIX_RELAY_IDLE, brix_tap_stream_feed(), and brix_relay_t::guard.
Referenced by relay_begin(), relay_cu(), and relay_uc().
relay_uc()
static void relay_uc (brix_relay_t * r, ngx_event_t * ev) static
Definition at line 239 of file relay.c.
References brix_relay_t::client, relay_close(), relay_pump(), brix_relay_t::uc, brix_relay_t::uc_dec, brix_relay_t::uc_end, brix_relay_t::uc_off, and brix_relay_t::upstream.
Referenced by relay_client_write(), and relay_upstream_read().
relay_upstream_read()
static void relay_upstream_read (ngx_event_t * ev) static
Definition at line 258 of file relay.c.
References relay_uc().
Referenced by brix_relay_start(), and relay_begin().
relay_upstream_write()
static void relay_upstream_write (ngx_event_t * ev) static
Definition at line 261 of file relay.c.
References relay_cu().
Referenced by relay_begin().