nginx-xrootd: src/protocols/root/relay/relay_guard.h File Reference
relay_guard.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include "net/tap/tap.h"
#include "net/guard/guard.h"
Data Structures
struct brix_relay_guard_t
Functions
void brix_relay_guard_init (brix_relay_guard_t *g, int enable, const ngx_str_t *client_addr, ngx_log_t *log)
void brix_relay_guard_sink (void *ctx, const brix_tap_frame_t *f, brix_tap_dir_t dir, const uint8_t *payload, size_t payload_len)
void brix_relay_guard_handshake (brix_relay_guard_t *g, const unsigned char *buf, size_t len)
int brix_relay_guard_should_drop (const brix_relay_guard_t *g)
Function Documentation
brix_relay_guard_handshake()
void brix_relay_guard_handshake (brix_relay_guard_t * g, const unsigned char * buf, size_t len)
Definition at line 203 of file relay_guard.c.
References brix_sanitize_log_string(), guard_request_t::cred_present, brix_relay_guard_t::drop, brix_relay_guard_t::enable, guard_classify_handshake(), GUARD_OP_HANDSHAKE, GUARD_R_NOTROOT, GUARD_WIRE_ROOT, guard_wire_str(), brix_relay_guard_t::hs_buf, brix_relay_guard_t::hs_len, brix_relay_guard_t::hs_seen, guard_request_t::ip, brix_relay_guard_t::ip, ngx_memcpy, guard_request_t::op, guard_request_t::outcome, OUTCOME_PENDING, guard_request_t::path, guard_request_t::path_len, guard_request_t::proto, relay_guard_audit(), guard_request_t::status_code, and tok.
Referenced by relay_pump().
brix_relay_guard_init()
void brix_relay_guard_init (brix_relay_guard_t * g, int enable, const ngx_str_t * client_addr, ngx_log_t * log)
Definition at line 159 of file relay_guard.c.
References brix_relay_guard_t::enable, guard_ruleset_add_default_signatures(), guard_ruleset_init(), guard_ruleset_load_profile(), brix_relay_guard_t::ip, log, brix_relay_guard_t::log, ngx_memcpy, and brix_relay_guard_t::rules.
Referenced by brix_relay_start().
brix_relay_guard_should_drop()
int brix_relay_guard_should_drop (const brix_relay_guard_t * g)
Definition at line 338 of file relay_guard.c.
References brix_relay_guard_t::drop.
Referenced by relay_pump().
brix_relay_guard_sink()
void brix_relay_guard_sink (void * ctx, const brix_tap_frame_t * f, brix_tap_dir_t dir, const uint8_t * payload, size_t payload_len)
Definition at line 278 of file relay_guard.c.
References brix_sanitize_log_string(), BRIX_TAP_C2U, BRIX_TAP_PATH_CAP, BRIX_TAP_U2C, guard_request_t::cred_present, brix_relay_guard_t::drop, brix_relay_guard_t::enable, brix_tap_frame_t::errnum, errnum_to_outcome(), GUARD_BOUNCE, guard_classify_post(), guard_classify_pre(), GUARD_OP_UNKNOWN, GUARD_R_NONE, guard_request_t::ip, brix_relay_guard_t::ip, brix_tap_frame_t::is_request, ngx_memcpy, guard_request_t::op, brix_tap_frame_t::opcode, opcode_to_op(), guard_request_t::outcome, OUTCOME_PENDING, guard_request_t::path, brix_tap_frame_t::path, guard_request_t::path_len, brix_tap_frame_t::path_len, guard_request_t::proto, relay_guard_audit(), brix_relay_guard_t::rules, brix_tap_frame_t::status, and guard_request_t::status_code.
Referenced by brix_relay_start().