nginx-xrootd: src/protocols/root/relay/relay.h File Reference
relay.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_stream.h>
Functions
char * brix_conf_set_transparent_proxy (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
ngx_int_t brix_relay_start (ngx_stream_session_t *s, ngx_connection_t *c, void *srv_conf)
Function Documentation
brix_conf_set_transparent_proxy()
char * brix_conf_set_transparent_proxy (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 56 of file relay.c.
References ngx_memcpy, ngx_pcalloc(), and ngx_pnalloc().
brix_relay_start()
ngx_int_t brix_relay_start (ngx_stream_session_t * s, ngx_connection_t * c, void * srv_conf)
Definition at line 327 of file relay.c.
References BRIX_RELAY_BUF, brix_relay_guard_init(), brix_relay_guard_sink(), BRIX_RELAY_IDLE, BRIX_TAP_C2U, brix_tap_register_sink(), brix_tap_stream_init(), BRIX_TAP_U2C, c, brix_relay_t::client, brix_relay_t::cu, brix_relay_t::cu_dec, brix_relay_t::cu_end, brix_relay_t::cu_off, brix_relay_guard_t::enable, brix_relay_t::guard, brix_relay_t::log, brix_ctx_t::metrics, brix_relay_t::metrics, ngx_pcalloc(), ngx_pnalloc(), ngx_stream_brix_module, brix_relay_t::peer, brix_ctx_t::relay, relay_audit_sink(), relay_begin(), relay_connect_done(), relay_peer_free(), relay_peer_get(), relay_upstream_read(), brix_relay_t::s, s, brix_ctx_t::state, brix_relay_t::tap, brix_relay_t::uc, brix_relay_t::uc_dec, brix_relay_t::uc_end, brix_relay_t::uc_off, brix_relay_t::upstream, and XRD_ST_PROXY.
Referenced by conn_try_relay().