nginx-xrootd: src/net/cms/reqid_map.h File Reference
reqid_map.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
Data Structures
struct brix_cms_reqid_entry_t
struct brix_cms_reqid_table_t
Macros
#define BRIX_CMS_REQID_MAP_SLOTS 512 /* power of two */
#define BRIX_CMS_REQID_KEY_MAX 64 /* manager reqid text */
#define BRIX_CMS_REQID_ENGINE_MAX 64 /* = BRIX_STAGE_REQID_LEN */
#define BRIX_CMS_REQID_NOTIFY_MAX 256 /* padArgs notify target */
#define BRIX_CMS_REQID_PRTY_MAX 16 /* padArgs priority text */
#define BRIX_CMS_REQID_MAP_TTL_MS (24 * 60 * 60 * 1000)
Functions
ngx_int_t brix_cms_reqid_map_configure (ngx_conf_t *cf)
void brix_cms_reqid_map_put (const char *cms_reqid, const char *engine_reqid, const char *notify, const char *prty)
int brix_cms_reqid_map_take (const char *cms_reqid, char *engine_reqid_out, size_t engine_reqid_sz)
Macro Definition Documentation
BRIX_CMS_REQID_ENGINE_MAX
#define BRIX_CMS_REQID_ENGINE_MAX 64 /* = BRIX_STAGE_REQID_LEN */
Definition at line 34 of file reqid_map.h.
BRIX_CMS_REQID_KEY_MAX
#define BRIX_CMS_REQID_KEY_MAX 64 /* manager reqid text */
Definition at line 33 of file reqid_map.h.
BRIX_CMS_REQID_MAP_SLOTS
#define BRIX_CMS_REQID_MAP_SLOTS 512 /* power of two */
Definition at line 32 of file reqid_map.h.
BRIX_CMS_REQID_MAP_TTL_MS
#define BRIX_CMS_REQID_MAP_TTL_MS (24 * 60 * 60 * 1000)
Definition at line 37 of file reqid_map.h.
BRIX_CMS_REQID_NOTIFY_MAX
#define BRIX_CMS_REQID_NOTIFY_MAX 256 /* padArgs notify target */
Definition at line 35 of file reqid_map.h.
BRIX_CMS_REQID_PRTY_MAX
#define BRIX_CMS_REQID_PRTY_MAX 16 /* padArgs priority text */
Definition at line 36 of file reqid_map.h.
Function Documentation
brix_cms_reqid_map_configure()
ngx_int_t brix_cms_reqid_map_configure (ngx_conf_t * cf)
Definition at line 66 of file reqid_map.c.
References brix_cms_reqid_map_shm_zone, brix_shm_zone_size(), ngx_stream_brix_module, and reqid_map_shm_init_zone().
Referenced by postconf_shared_registries().
brix_cms_reqid_map_put()
void brix_cms_reqid_map_put (const char * cms_reqid, const char * engine_reqid, const char * notify, const char * prty)
Definition at line 84 of file reqid_map.c.
References BRIX_CMS_REQID_ENGINE_MAX, BRIX_CMS_REQID_KEY_MAX, brix_cms_reqid_map_mutex, BRIX_CMS_REQID_MAP_SLOTS, BRIX_CMS_REQID_MAP_TTL_MS, brix_shm_slot_expired(), brix_cms_reqid_entry_t::cms_reqid, brix_cms_reqid_entry_t::engine_reqid, brix_cms_reqid_entry_t::expires, brix_cms_reqid_entry_t::in_use, brix_cms_reqid_entry_t::key_hash, brix_cms_reqid_entry_t::notify, brix_cms_reqid_entry_t::prty, reqid_hash(), reqid_table(), and brix_cms_reqid_table_t::slots.
Referenced by cms_prep_add().
brix_cms_reqid_map_take()
int brix_cms_reqid_map_take (const char * cms_reqid, char * engine_reqid_out, size_t engine_reqid_sz)
Definition at line 146 of file reqid_map.c.
References BRIX_CMS_REQID_KEY_MAX, brix_cms_reqid_map_mutex, BRIX_CMS_REQID_MAP_SLOTS, brix_shm_slot_expired(), brix_cms_reqid_entry_t::cms_reqid, brix_cms_reqid_entry_t::engine_reqid, brix_cms_reqid_entry_t::expires, brix_cms_reqid_entry_t::in_use, brix_cms_reqid_entry_t::key_hash, reqid_hash(), reqid_table(), and brix_cms_reqid_table_t::slots.
Referenced by cms_prep_del().