nginx-xrootd: src/net/cms/reqid_map.c File Reference
reqid_map.c File Reference
#include "reqid_map.h"
#include "core/ngx_brix_module.h"
#include "core/fnv.h"
#include "core/compat/shm_slots.h"
Functions
static brix_cms_reqid_table_t * reqid_table (void)
static uint32_t reqid_hash (const char *key)
static ngx_int_t reqid_map_shm_init_zone (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t brix_cms_reqid_map_configure (ngx_conf_t *cf)
void brix_cms_reqid_map_put (const char *cms_reqid, const char *engine_reqid, const char *notify, const char *prty)
int brix_cms_reqid_map_take (const char *cms_reqid, char *engine_reqid_out, size_t engine_reqid_sz)
Variables
ngx_shm_zone_t * brix_cms_reqid_map_shm_zone
static ngx_shmtx_t brix_cms_reqid_map_mutex
Function Documentation
brix_cms_reqid_map_configure()
ngx_int_t brix_cms_reqid_map_configure (ngx_conf_t * cf)
Definition at line 66 of file reqid_map.c.
References brix_cms_reqid_map_shm_zone, brix_shm_zone_size(), ngx_stream_brix_module, and reqid_map_shm_init_zone().
Referenced by postconf_shared_registries().
brix_cms_reqid_map_put()
void brix_cms_reqid_map_put (const char * cms_reqid, const char * engine_reqid, const char * notify, const char * prty)
Definition at line 84 of file reqid_map.c.
References BRIX_CMS_REQID_ENGINE_MAX, BRIX_CMS_REQID_KEY_MAX, brix_cms_reqid_map_mutex, BRIX_CMS_REQID_MAP_SLOTS, BRIX_CMS_REQID_MAP_TTL_MS, brix_shm_slot_expired(), brix_cms_reqid_entry_t::cms_reqid, brix_cms_reqid_entry_t::engine_reqid, brix_cms_reqid_entry_t::expires, brix_cms_reqid_entry_t::in_use, brix_cms_reqid_entry_t::key_hash, brix_cms_reqid_entry_t::notify, brix_cms_reqid_entry_t::prty, reqid_hash(), reqid_table(), and brix_cms_reqid_table_t::slots.
Referenced by cms_prep_add().
brix_cms_reqid_map_take()
int brix_cms_reqid_map_take (const char * cms_reqid, char * engine_reqid_out, size_t engine_reqid_sz)
Definition at line 146 of file reqid_map.c.
References BRIX_CMS_REQID_KEY_MAX, brix_cms_reqid_map_mutex, BRIX_CMS_REQID_MAP_SLOTS, brix_shm_slot_expired(), brix_cms_reqid_entry_t::cms_reqid, brix_cms_reqid_entry_t::engine_reqid, brix_cms_reqid_entry_t::expires, brix_cms_reqid_entry_t::in_use, brix_cms_reqid_entry_t::key_hash, reqid_hash(), reqid_table(), and brix_cms_reqid_table_t::slots.
Referenced by cms_prep_del().
reqid_hash()
static uint32_t reqid_hash (const char * key) static
Definition at line 34 of file reqid_map.c.
References BRIX_FNV1A32_OFFSET_BASIS, BRIX_FNV1A32_PRIME, and key.
Referenced by brix_cms_reqid_map_put(), and brix_cms_reqid_map_take().
reqid_map_shm_init_zone()
static ngx_int_t reqid_map_shm_init_zone (ngx_shm_zone_t * shm_zone, void * data) static
Definition at line 46 of file reqid_map.c.
References brix_cms_reqid_map_mutex, brix_shm_table_alloc(), and brix_cms_reqid_table_t::slots.
Referenced by brix_cms_reqid_map_configure().
reqid_table()
static brix_cms_reqid_table_t * reqid_table (void) static
Definition at line 22 of file reqid_map.c.
References brix_cms_reqid_map_shm_zone.
Referenced by brix_cms_reqid_map_put(), and brix_cms_reqid_map_take().
Variable Documentation
brix_cms_reqid_map_mutex
ngx_shmtx_t brix_cms_reqid_map_mutex static
Definition at line 17 of file reqid_map.c.
Referenced by brix_cms_reqid_map_put(), brix_cms_reqid_map_take(), and reqid_map_shm_init_zone().
brix_cms_reqid_map_shm_zone
ngx_shm_zone_t* brix_cms_reqid_map_shm_zone
Definition at line 15 of file reqid_map.c.
Referenced by brix_cms_reqid_map_configure(), and reqid_table().