nginx-xrootd: client/lib/net/resilient.c File Reference
resilient.c File Reference
#include "brix.h"
#include <errno.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
Macros
#define XRDC_RFILE_CHUNK0 (4u * 1024u * 1024u)
#define XRDC_RFILE_FLOOR (256u * 1024u)
Functions
static int opts_window_ms (const brix_opts *o)
int brix_resilient_window_ms (const brix_conn *c)
int brix_connect_resilient (brix_conn *c, const brix_url *u, const brix_opts *o, brix_status *st)
int brix_reconnect_home (brix_conn *c, brix_status *st)
int brix_with_resilience (brix_conn *c, int max_stall_ms, brix_op_class cls, int benign_errno, brix_op_fn op, void *arg, brix_status *st)
int brix_roundtrip_resilient (brix_conn *c, void *hdr24, const void *payload, uint32_t plen, brix_op_class cls, int benign_errno, uint16_t *status, uint8_t **body, uint32_t *blen, brix_status *st)
static int rfile_do_open (brix_rfile *rf, brix_status *st)
static int rfile_reopen (brix_rfile *rf, brix_status *st)
static int rfile_canceled (const brix_rfile *rf)
static void rfile_init (brix_rfile *rf, brix_conn *c, const char *path, int pgrw, int max_stall_ms)
int brix_rfile_open_read (brix_conn *c, const char *path, const char *opaque, int pgrw, int max_stall_ms, brix_rfile *rf, brix_status *st)
int brix_rfile_open_write (brix_conn *c, const char *path, int force, int posc, int pgrw, int max_stall_ms, brix_rfile *rf, brix_status *st)
ssize_t brix_rfile_pread (brix_rfile *rf, int64_t off, void *buf, size_t len, brix_status *st)
int brix_rfile_pwrite (brix_rfile *rf, int64_t off, const void *buf, size_t len, brix_status *st)
int brix_rfile_close (brix_rfile *rf, brix_status *st)
Macro Definition Documentation
XRDC_RFILE_CHUNK0
#define XRDC_RFILE_CHUNK0 (4u * 1024u * 1024u)
Definition at line 36 of file resilient.c.
XRDC_RFILE_FLOOR
#define XRDC_RFILE_FLOOR (256u * 1024u)
Definition at line 37 of file resilient.c.
Function Documentation
brix_connect_resilient()
int brix_connect_resilient (brix_conn * c, const brix_url * u, const brix_opts * o, brix_status * st)
Definition at line 70 of file resilient.c.
References brix_backoff_sleep_fast(), brix_connect(), brix_mono_ns(), brix_status_retryable(), c, brix_status::kxr, opts_window_ms(), brix_status::sys_errno, and XRDC_ESOCK.
Referenced by brix_cli_connect(), do_map(), main(), run_root_endpoint(), and upload_stream_body().
brix_reconnect_home()
int brix_reconnect_home (brix_conn * c, brix_status * st)
Definition at line 102 of file resilient.c.
References brix_reconnect(), c, host, and port.
Referenced by brix_rfile_open_read(), brix_rfile_open_write(), brix_roundtrip_resilient(), brix_with_resilience(), rfile_reopen(), and tail_follow().
brix_resilient_window_ms()
int brix_resilient_window_ms (const brix_conn * c)
Definition at line 64 of file resilient.c.
References c, and opts_window_ms().
Referenced by brix_dirlist(), brix_roundtrip_resilient(), rfile_init(), and tail_follow().
brix_rfile_close()
int brix_rfile_close (brix_rfile * rf, brix_status * st)
Definition at line 370 of file resilient.c.
References brix_file_close(), brix_rfile::c, and brix_rfile::f.
Referenced by close(), do_dd(), do_download(), do_grep(), do_hexdump(), do_upload(), head_lines(), slurp_file(), stream_file(), tail_follow(), tail_follow_drain(), tail_start_for_lines(), wc_count_stream(), and xfs_release().
brix_rfile_open_read()
int brix_rfile_open_read (brix_conn * c, const char * path, const char * opaque, int pgrw, int max_stall_ms, brix_rfile * rf, brix_status * st)
Definition at line 261 of file resilient.c.
References brix_backoff_sleep_fast(), brix_mono_ns(), brix_reconnect_home(), brix_status_retryable(), brix_rfile::c, c, brix_rfile::max_stall_ms, brix_rfile::opaque, rfile_canceled(), rfile_do_open(), rfile_init(), and brix_rfile::writable.
Referenced by do_dd(), do_download(), do_grep(), do_hexdump(), head_lines(), remote_open(), slurp_file(), stream_file(), tail_follow(), tail_follow_drain(), tail_start_for_lines(), wc_count_stream(), and xfs_open().
brix_rfile_open_write()
int brix_rfile_open_write (brix_conn * c, const char * path, int force, int posc, int pgrw, int max_stall_ms, brix_rfile * rf, brix_status * st)
Definition at line 286 of file resilient.c.
References brix_backoff_sleep_fast(), brix_file_open_write(), brix_mono_ns(), brix_reconnect_home(), brix_status_retryable(), brix_rfile::c, c, brix_rfile::f, brix_rfile::max_stall_ms, brix_rfile::path, brix_rfile::posc, rfile_canceled(), rfile_init(), and brix_rfile::writable.
Referenced by do_upload(), xfs_create(), and xfs_open().
brix_rfile_pread()
ssize_t brix_rfile_pread (brix_rfile * rf, int64_t off, void * buf, size_t len, brix_status * st)
Definition at line 312 of file resilient.c.
References brix_backoff_sleep_fast(), brix_file_pgread(), brix_file_read(), brix_mono_ns(), brix_status_retryable(), brix_status_set(), brix_rfile::c, brix_rfile::cur_chunk, brix_rfile::f, brix_rfile::max_stall_ms, brix_rfile::pgrw, rfile_canceled(), rfile_reopen(), XRDC_EUSAGE, and XRDC_RFILE_FLOOR.
Referenced by do_dd(), do_grep(), download_copy_loop(), head_lines(), hexdump_stream(), pread(), read(), slurp_file(), stream_file(), tail_follow_drain(), tail_start_for_lines(), wc_count_stream(), and xfs_io_pread().
brix_rfile_pwrite()
int brix_rfile_pwrite (brix_rfile * rf, int64_t off, const void * buf, size_t len, brix_status * st)
Definition at line 343 of file resilient.c.
References brix_backoff_sleep_fast(), brix_file_pgwrite(), brix_file_write(), brix_mono_ns(), brix_status_retryable(), brix_status_set(), brix_rfile::c, brix_rfile::f, brix_rfile::max_stall_ms, brix_rfile::pgrw, rfile_canceled(), rfile_reopen(), and XRDC_EUSAGE.
Referenced by upload_copy_loop(), and xfs_io_pwrite().
brix_roundtrip_resilient()
int brix_roundtrip_resilient (brix_conn * c, void * hdr24, const void * payload, uint32_t plen, brix_op_class cls, int benign_errno, uint16_t * status, uint8_t ** body, uint32_t * blen, brix_status * st)
Definition at line 164 of file resilient.c.
References brix_backoff_sleep_fast(), brix_kxr_to_errno(), brix_mono_ns(), brix_reconnect_home(), brix_resilient_window_ms(), brix_roundtrip(), brix_status_clear(), brix_status_retryable(), c, cls(), XRDC_OP_MUTATION_NORMALIZE, and XRDC_OP_UNSAFE.
Referenced by brix_query_cksum(), fs_simple(), fs_text(), and stat_opt().
brix_with_resilience()
int brix_with_resilience (brix_conn * c, int max_stall_ms, brix_op_class cls, int benign_errno, brix_op_fn op, void * arg, brix_status * st)
Definition at line 111 of file resilient.c.
References brix_backoff_sleep_fast(), brix_kxr_to_errno(), brix_mono_ns(), brix_reconnect_home(), brix_status_clear(), brix_status_retryable(), c, cls(), op, XRDC_OP_MUTATION_NORMALIZE, and XRDC_OP_UNSAFE.
Referenced by brix_dirlist().
opts_window_ms()
static int opts_window_ms (const brix_opts * o) static
Definition at line 44 of file resilient.c.
References brix_xrdrc_default_ms(), brix_opts::max_stall_ms, brix_opts::no_retry, and XRDC_DEFAULT_MAX_STALL_MS.
Referenced by brix_connect_resilient(), and brix_resilient_window_ms().
rfile_canceled()
static int rfile_canceled (const brix_rfile * rf) static
Definition at line 242 of file resilient.c.
References brix_rfile::cancel.
Referenced by brix_rfile_open_read(), brix_rfile_open_write(), brix_rfile_pread(), and brix_rfile_pwrite().
rfile_do_open()
static int rfile_do_open (brix_rfile * rf, brix_status * st) static
Definition at line 219 of file resilient.c.
References brix_file_open_opaque(), brix_file_open_read(), brix_file_open_update(), brix_rfile::c, brix_rfile::f, brix_rfile::opaque, brix_rfile::path, brix_rfile::posc, and brix_rfile::writable.
Referenced by brix_rfile_open_read(), and rfile_reopen().
rfile_init()
static void rfile_init (brix_rfile * rf, brix_conn * c, const char * path, int pgrw, int max_stall_ms) static
Definition at line 248 of file resilient.c.
References brix_resilient_window_ms(), brix_rfile::c, c, brix_rfile::cur_chunk, brix_rfile::max_stall_ms, brix_rfile::path, brix_rfile::pgrw, and XRDC_RFILE_CHUNK0.
Referenced by brix_rfile_open_read(), and brix_rfile_open_write().
rfile_reopen()
static int rfile_reopen (brix_rfile * rf, brix_status * st) static
Definition at line 233 of file resilient.c.
References brix_reconnect_home(), brix_rfile::c, and rfile_do_open().
Referenced by brix_rfile_pread(), and brix_rfile_pwrite().