nginx-xrootd: src/auth/authz/acc/resolve.c File Reference
resolve.c File Reference
#include "acc.h"
#include "observability/metrics/metrics.h"
#include "observability/metrics/metrics_macros.h"
#include <netdb.h>
#include <sys/socket.h>
#include <time.h>
Macros
#define ACC_DNS_SLOW_MS 2000
#define ACC_DNS_TRIP_COUNT 5
#define ACC_DNS_COOLDOWN_SECS 10
Functions
static int64_t acc_dns_monotonic_ms (void)
const char * brix_acc_resolve_peer (struct sockaddr *sa, socklen_t salen, char *buf, size_t buflen)
Variables
struct {
int consecutive_slow
time_t open_until
} acc_dns_breaker
Macro Definition Documentation
ACC_DNS_COOLDOWN_SECS
#define ACC_DNS_COOLDOWN_SECS 10
Definition at line 40 of file resolve.c.
ACC_DNS_SLOW_MS
#define ACC_DNS_SLOW_MS 2000
Definition at line 38 of file resolve.c.
ACC_DNS_TRIP_COUNT
#define ACC_DNS_TRIP_COUNT 5
Definition at line 39 of file resolve.c.
Function Documentation
acc_dns_monotonic_ms()
static int64_t acc_dns_monotonic_ms (void) static
Definition at line 48 of file resolve.c.
Referenced by brix_acc_resolve_peer().
brix_acc_resolve_peer()
const char * brix_acc_resolve_peer (struct sockaddr * sa, socklen_t salen, char * buf, size_t buflen)
Definition at line 58 of file resolve.c.
References acc_dns_breaker, ACC_DNS_COOLDOWN_SECS, acc_dns_monotonic_ms(), ACC_DNS_SLOW_MS, ACC_DNS_TRIP_COUNT, and BRIX_RESIL_METRIC_INC.
Referenced by brix_acc_gate_host(), brix_handle_host_auth(), s3_acc_check(), and webdav_acc_check().
Variable Documentation
[struct]
struct { ... } acc_dns_breaker
Referenced by brix_acc_resolve_peer().
consecutive_slow
int consecutive_slow
Definition at line 43 of file resolve.c.
open_until
time_t open_until
Definition at line 44 of file resolve.c.