nginx-xrootd: src/protocols/webdav/resource.c File Reference
resource.c File Reference
#include "webdav.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "fs/vfs/vfs.h"
#include <errno.h>
Functions
ngx_int_t webdav_resolve_stat (ngx_http_request_t *r, char *path, size_t pathsz, struct stat *sb)
WHAT: Resolve the request URI to a canonicalised filesystem path then perform stat(2) on the result — combines ngx_http_brix_webdav_resolve_path() and stat(2) into a single helper for handlers needing both path and metadata.
Function Documentation
webdav_resolve_stat()
ngx_int_t webdav_resolve_stat (ngx_http_request_t * r, char * path, size_t pathsz, struct stat * sb)
WHAT: Resolve the request URI to a canonicalised filesystem path then perform stat(2) on the result — combines ngx_http_brix_webdav_resolve_path() and stat(2) into a single helper for handlers needing both path and metadata.
Calls the primary path resolver (ngx_http_brix_webdav_resolve_path()) to convert r->uri into an absolute canonicalised path within root_canon, then immediately calls stat(2) on that path to populate sb with file metadata. Returns NGX_OK if both steps succeed; NGX_HTTP_NOT_FOUND (404) if the resolved path doesn't exist (ENOENT); any other stat error returns NGX_HTTP_INTERNAL_SERVER_ERROR (500). The caller-supplied path buffer must be at least WEBDAV_MAX_PATH bytes to accommodate the decoded and canonicalised output. Used by GET, HEAD, PROPFIND handlers that need both the resolved path and file metadata in a single atomic operation.
WHY: Many WebDAV methods (GET, HEAD, PROPFIND) require both the resolved path AND file metadata — calling resolve_path separately then stat would duplicate error handling logic across multiple handler files. This helper provides an atomic two-step operation with consistent error mapping. Per AGENTS.md INVARIANT #4: all wire paths must go through resolve_path() before any filesystem operations — this function enforces that invariant by embedding the resolution step into stat itself. Security invariant: resolved path is confined to root_canon, preventing ../ traversal attacks even if client supplies malicious URI components.
HOW: Retrieves WebDAV location configuration via ngx_http_get_module_loc_conf(). Calls ngx_http_brix_webdav_resolve_path() first — if resolution fails (invalid URI, outside root_canon), returns immediately with that error code. On successful resolution calls stat(2) on the resolved path — maps ENOENT to 404, all other errors to 500. Returns NGX_OK only when both resolution and stat succeed. Caller must ensure path buffer has sufficient capacity (WEBDAV_MAX_PATH). sb pointer may be NULL if caller needs path only without metadata.
Definition at line 41 of file resource.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_vfs_ctx_t::allow_write, BRIX_PROTO_WEBDAV, brix_vfs_backend_resolve(), brix_vfs_ctx_bind_backend_cred(), ngx_http_brix_webdav_loc_conf_t::common, brix_vfs_stat_t::ctime, brix_vfs_ctx_t::identity, ngx_http_brix_webdav_req_ctx_t::identity, brix_vfs_stat_t::ino, brix_path_result_t::is_confined, brix_vfs_ctx_t::is_tls, brix_vfs_ctx_t::log, brix_vfs_ctx_t::metrics_proto, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), brix_vfs_ctx_t::pool, brix_path_result_t::resolved, brix_vfs_ctx_t::resolved, ngx_http_brix_shared_conf_t::root_canon, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::rootfd, brix_vfs_ctx_t::sd, brix_vfs_stat_t::size, ngx_http_brix_shared_conf_t::storage_credential_dir, ngx_http_brix_shared_conf_t::storage_credential_fallback, and webdav_vfs_bind_deleg().
Referenced by propfind_do(), webdav_handle_delete(), webdav_handle_head(), webdav_proppatch_do(), webdav_search_do(), and webdav_tpc_handle_push().