nginx-xrootd: src/fs/path/resolve_confined_helpers.c File Reference
resolve_confined_helpers.c File Reference
#include "core/ngx_brix_module.h"
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include "path_internal.h"
Macros
#define O_PATH O_RDONLY
Functions
void brix_log_path_warning (ngx_log_t *log, const char *prefix, const char *path)
int brix_path_within_root (const char *root_canon, const char *path_canon)
int brix_resolved_relative_to_root (ngx_log_t *log, const char *root_canon, const char *resolved, char *rel, size_t relsz)
int brix_open_root_fd (ngx_log_t *log, const char *root_canon)
int brix_openat2_runtime_available (void)
static int brix_open_dir_no_symlink (int parentfd, const char *name)
int brix_open_confined_parent_fallback (int rootfd, const char *parent)
int brix_split_relative_parent (const char *rel, char *parent, size_t parentsz, char *base, size_t basesz)
int brix_open_confined_parent_canon (ngx_log_t *log, const char *root_canon, const char *resolved, char *base, size_t basesz)
Macro Definition Documentation
O_PATH
#define O_PATH O_RDONLY
Definition at line 60 of file resolve_confined_helpers.c.
Function Documentation
brix_log_path_warning()
void brix_log_path_warning (ngx_log_t * log, const char * prefix, const char * path)
Definition at line 69 of file resolve_confined_helpers.c.
References brix_sanitize_log_string(), and log.
Referenced by brix_path_warn(), brix_reject_dotdot_path(), brix_resolve_op_path(), and brix_resolved_relative_to_root().
brix_open_confined_parent_canon()
int brix_open_confined_parent_canon (ngx_log_t * log, const char * root_canon, const char * resolved, char * base, size_t basesz)
Definition at line 361 of file resolve_confined_helpers.c.
References brix_open_confined_parent_fallback(), brix_open_root_fd(), brix_resolved_relative_to_root(), brix_split_relative_parent(), close(), log, O_PATH, and PATH_MAX.
Referenced by brix_chmod_confined_canon(), brix_link_confined_canon(), brix_mkdir_confined_canon(), brix_readlink_confined_canon(), brix_setattr_confined_canon(), brix_symlink_confined_canon(), brix_unlink_confined_canon(), and rename_confined_canon_impl().
brix_open_confined_parent_fallback()
int brix_open_confined_parent_fallback (int rootfd, const char * parent)
Definition at line 236 of file resolve_confined_helpers.c.
References brix_open_dir_no_symlink(), brix_path_component_forbidden(), close(), and PATH_MAX.
Referenced by brix_open_confined_canon(), and brix_open_confined_parent_canon().
brix_open_dir_no_symlink()
static int brix_open_dir_no_symlink (int parentfd, const char * name) static
Definition at line 222 of file resolve_confined_helpers.c.
References name, O_PATH, and openat().
Referenced by brix_open_confined_parent_fallback().
brix_open_root_fd()
int brix_open_root_fd (ngx_log_t * log, const char * root_canon)
Definition at line 151 of file resolve_confined_helpers.c.
References log, O_PATH, and open().
Referenced by brix_lstat_confined_canon(), brix_open_confined_canon(), brix_open_confined_parent_canon(), and brix_opendir_confined_canon().
brix_openat2_runtime_available()
int brix_openat2_runtime_available (void)
Definition at line 197 of file resolve_confined_helpers.c.
References close(), and O_PATH.
Referenced by ngx_stream_brix_init_process().
brix_path_within_root()
int brix_path_within_root (const char * root_canon, const char * path_canon)
Definition at line 84 of file resolve_confined_helpers.c.
Referenced by brix_finish_resolved(), brix_resolve_missing_parents(), brix_resolve_missing_tail(), and brix_resolved_relative_to_root().
brix_resolved_relative_to_root()
int brix_resolved_relative_to_root (ngx_log_t * log, const char * root_canon, const char * resolved, char * rel, size_t relsz)
Definition at line 107 of file resolve_confined_helpers.c.
References brix_log_path_warning(), brix_path_within_root(), and log.
Referenced by brix_chmod_confined_canon(), brix_dirlist_access_ok(), brix_getxattr_confined_canon(), brix_link_confined_canon(), brix_listxattr_confined_canon(), brix_lstat_confined_canon(), brix_mkdir_confined_canon(), brix_open_confined_canon(), brix_open_confined_parent_canon(), brix_opendir_confined_canon(), brix_readlink_confined_canon(), brix_removexattr_confined_canon(), brix_setattr_confined_canon(), brix_setxattr_confined_canon(), brix_symlink_confined_canon(), brix_unlink_confined_canon(), and rename_confined_canon_impl().
brix_split_relative_parent()
int brix_split_relative_parent (const char * rel, char * parent, size_t parentsz, char * base, size_t basesz)
Definition at line 310 of file resolve_confined_helpers.c.
Referenced by brix_open_confined_canon(), and brix_open_confined_parent_canon().