nginx-xrootd: src/fs/path/resolve_confined_ops.c File Reference
resolve_confined_ops.c File Reference
#include "core/ngx_brix_module.h"
#include "path_internal.h"
#include "beneath.h"
#include "auth/impersonate/impersonate.h"
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <sys/syscall.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/xattr.h>
#include <time.h>
#include <unistd.h>
#include <linux/openat2.h>
Macros
#define RENAME_NOREPLACE (1u << 0)
Functions
int brix_open_root_fd (ngx_log_t *log, const char *root_canon)
char * brix_split_relative_parent (const char *rel, char *parent, size_t parentsz, char *base, size_t basesz)
int brix_open_confined_parent_fallback (int rootfd, const char *parent)
int brix_open_confined_parent_canon (ngx_log_t *log, const char *root_canon, const char *resolved, char *base, size_t basesz)
ngx_int_t brix_dirlist_access_ok (ngx_log_t *log, const char *root_canon, const char *resolved)
int brix_open_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, int flags, mode_t mode)
int brix_open_confined (ngx_log_t *log, const ngx_str_t *root, const char *resolved, int flags, mode_t mode)
int brix_unlink_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, int is_dir)
int brix_mkdir_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, mode_t mode)
static int rename_confined_canon_impl (ngx_log_t *log, const char *root_canon, const char *src_resolved, const char *dst_resolved, int noreplace)
int brix_rename_confined_canon (ngx_log_t *log, const char *root_canon, const char *src_resolved, const char *dst_resolved)
int brix_rename_confined_canon_excl (ngx_log_t *log, const char *root_canon, const char *src_resolved, const char *dst_resolved)
int brix_link_confined_canon (ngx_log_t *log, const char *root_canon, const char *src_resolved, const char *dst_resolved)
int brix_setattr_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, int set_times, const struct timespec times[2], int set_owner, uid_t uid, gid_t gid)
int brix_chmod_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, mode_t mode)
int brix_symlink_confined_canon (ngx_log_t *log, const char *root_canon, const char *target, const char *link_resolved)
ssize_t brix_readlink_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, char *buf, size_t bufsz)
int brix_setxattr_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, const char *name, const void *value, size_t len, int flags)
ssize_t brix_getxattr_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, const char *name, void *buf, size_t bufsz)
int brix_removexattr_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, const char *name)
ssize_t brix_listxattr_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, void *buf, size_t bufsz)
DIR * brix_opendir_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved)
int brix_lstat_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, struct stat *st, int nofollow)
Macro Definition Documentation
RENAME_NOREPLACE
#define RENAME_NOREPLACE (1u << 0)
Definition at line 251 of file resolve_confined_ops.c.
Function Documentation
brix_chmod_confined_canon()
int brix_chmod_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, mode_t mode)
Definition at line 444 of file resolve_confined_ops.c.
References brix_imp_chmod(), brix_imp_client_active(), brix_open_confined_parent_canon(), brix_resolved_relative_to_root(), close(), log, and PATH_MAX.
Referenced by brix_vfs_chmod(), and brix_vfs_setattr().
brix_dirlist_access_ok()
ngx_int_t brix_dirlist_access_ok (ngx_log_t * log, const char * root_canon, const char * resolved)
Definition at line 47 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_enabled(), brix_imp_open(), brix_resolved_relative_to_root(), close(), log, and PATH_MAX.
Referenced by propfind_walk(), s3_walk_run(), and webdav_search_walk().
brix_getxattr_confined_canon()
ssize_t brix_getxattr_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, const char * name, void * buf, size_t bufsz)
Definition at line 593 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_getxattr(), brix_resolved_relative_to_root(), log, name, and PATH_MAX.
Referenced by brix_vfs_getxattr(), and sd_posix_getxattr().
brix_link_confined_canon()
int brix_link_confined_canon (ngx_log_t * log, const char * root_canon, const char * src_resolved, const char * dst_resolved)
Definition at line 341 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_link(), brix_open_confined_parent_canon(), brix_resolved_relative_to_root(), close(), log, and PATH_MAX.
Referenced by brix_handle_link(), tpc_marker_commit_pull(), tpc_thread_pull_commit(), and webdav_tpc_commit_pulled_file().
brix_listxattr_confined_canon()
ssize_t brix_listxattr_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, void * buf, size_t bufsz)
Definition at line 625 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_listxattr(), brix_resolved_relative_to_root(), log, and PATH_MAX.
Referenced by brix_vfs_listxattr(), and sd_posix_listxattr().
brix_lstat_confined_canon()
int brix_lstat_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, struct stat * st, int nofollow)
Definition at line 708 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_stat(), brix_lstat_beneath(), brix_open_root_fd(), brix_resolved_relative_to_root(), brix_stat_beneath(), close(), log, and PATH_MAX.
Referenced by brix_vfs_copy_ns_bytes(), brix_vfs_copyfile(), brix_vfs_probe(), brix_vfs_staged_commit(), brix_vfs_stat_impl(), vfs_copytree_entry(), and vfs_readdir_stat_child().
brix_mkdir_confined_canon()
int brix_mkdir_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, mode_t mode)
Definition at line 217 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_mkdir(), brix_open_confined_parent_canon(), brix_resolved_relative_to_root(), close(), log, and PATH_MAX.
Referenced by brix_mkdir_level_confined(), brix_vfs_mkdir_path(), s3_handle_multipart_initiate(), and vfs_copytree_subdir().
brix_open_confined()
int brix_open_confined (ngx_log_t * log, const ngx_str_t * root, const char * resolved, int flags, mode_t mode)
Definition at line 168 of file resolve_confined_ops.c.
References brix_get_canonical_root(), brix_open_confined_canon(), log, and PATH_MAX.
Referenced by brix_query_adler32_file(), brix_query_crc32_file(), and brix_query_digest_file().
brix_open_confined_canon()
int brix_open_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, int flags, mode_t mode)
Definition at line 95 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_open(), brix_open_confined_parent_fallback(), brix_open_root_fd(), brix_resolved_relative_to_root(), brix_split_relative_parent(), close(), log, openat(), and PATH_MAX.
Referenced by brix_open_confined(), brix_vfs_copyfile(), brix_vfs_open_confined_fd(), and brix_vfs_open_fd().
brix_open_confined_parent_canon()
int brix_open_confined_parent_canon (ngx_log_t * log, const char * root_canon, const char * resolved, char * base, size_t basesz) extern
Definition at line 361 of file resolve_confined_helpers.c.
References brix_open_confined_parent_fallback(), brix_open_root_fd(), brix_resolved_relative_to_root(), brix_split_relative_parent(), close(), log, O_PATH, and PATH_MAX.
Referenced by brix_chmod_confined_canon(), brix_link_confined_canon(), brix_mkdir_confined_canon(), brix_readlink_confined_canon(), brix_setattr_confined_canon(), brix_symlink_confined_canon(), brix_unlink_confined_canon(), and rename_confined_canon_impl().
brix_open_confined_parent_fallback()
int brix_open_confined_parent_fallback (int rootfd, const char * parent) extern
Definition at line 236 of file resolve_confined_helpers.c.
References brix_open_dir_no_symlink(), brix_path_component_forbidden(), close(), ngx_memcpy, and PATH_MAX.
Referenced by brix_open_confined_canon(), and brix_open_confined_parent_canon().
brix_open_root_fd()
int brix_open_root_fd (ngx_log_t * log, const char * root_canon) extern
Definition at line 151 of file resolve_confined_helpers.c.
References log, O_PATH, and open().
Referenced by brix_lstat_confined_canon(), brix_open_confined_canon(), brix_open_confined_parent_canon(), and brix_opendir_confined_canon().
brix_opendir_confined_canon()
DIR * brix_opendir_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved)
Definition at line 657 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_open(), brix_open_root_fd(), brix_opendir_beneath(), brix_resolved_relative_to_root(), close(), log, and PATH_MAX.
Referenced by brix_fs_remove_tree_confined(), brix_vfs_copytree(), and vfs_dir_open_confined().
brix_readlink_confined_canon()
ssize_t brix_readlink_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, char * buf, size_t bufsz)
Definition at line 524 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_readlink(), brix_open_confined_parent_canon(), brix_resolved_relative_to_root(), close(), log, and PATH_MAX.
Referenced by brix_handle_readlink().
brix_removexattr_confined_canon()
int brix_removexattr_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, const char * name)
Definition at line 609 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_removexattr(), brix_resolved_relative_to_root(), log, name, and PATH_MAX.
Referenced by brix_vfs_removexattr(), and sd_posix_removexattr().
brix_rename_confined_canon()
int brix_rename_confined_canon (ngx_log_t * log, const char * root_canon, const char * src_resolved, const char * dst_resolved)
Definition at line 323 of file resolve_confined_ops.c.
References log, and rename_confined_canon_impl().
Referenced by s3_mpu_assemble(), tpc_marker_commit_pull(), tpc_thread_pull_commit(), and webdav_copy_collection_commit().
brix_rename_confined_canon_excl()
int brix_rename_confined_canon_excl (ngx_log_t * log, const char * root_canon, const char * src_resolved, const char * dst_resolved)
Definition at line 331 of file resolve_confined_ops.c.
References log, and rename_confined_canon_impl().
brix_setattr_confined_canon()
int brix_setattr_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, int set_times, const struct timespec times[2], int set_owner, uid_t uid, gid_t gid)
Definition at line 395 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_setattr(), brix_open_confined_parent_canon(), brix_resolved_relative_to_root(), close(), log, and PATH_MAX.
Referenced by brix_vfs_setattr().
brix_setxattr_confined_canon()
int brix_setxattr_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, const char * name, const void * value, size_t len, int flags)
Definition at line 576 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_setxattr(), brix_resolved_relative_to_root(), log, name, and PATH_MAX.
Referenced by brix_vfs_setxattr(), and sd_posix_setxattr().
brix_split_relative_parent()
char * brix_split_relative_parent (const char * rel, char * parent, size_t parentsz, char * base, size_t basesz) extern
Definition at line 310 of file resolve_confined_helpers.c.
References ngx_memcpy.
Referenced by brix_open_confined_canon(), and brix_open_confined_parent_canon().
brix_symlink_confined_canon()
int brix_symlink_confined_canon (ngx_log_t * log, const char * root_canon, const char * target, const char * link_resolved)
Definition at line 485 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_symlink(), brix_open_confined_parent_canon(), brix_resolved_relative_to_root(), close(), log, and PATH_MAX.
Referenced by brix_handle_symlink().
brix_unlink_confined_canon()
int brix_unlink_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, int is_dir)
Definition at line 185 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_unlink(), brix_open_confined_parent_canon(), brix_resolved_relative_to_root(), close(), log, and PATH_MAX.
Referenced by brix_vfs_unlink_path(), tpc_marker_commit_pull(), tpc_marker_settle_temp(), tpc_thread_pull_commit(), and tpc_thread_pull_fetch().
rename_confined_canon_impl()
static int rename_confined_canon_impl (ngx_log_t * log, const char * root_canon, const char * src_resolved, const char * dst_resolved, int noreplace) static
Definition at line 258 of file resolve_confined_ops.c.
References brix_imp_client_active(), brix_imp_rename(), brix_imp_rename_noreplace(), brix_open_confined_parent_canon(), brix_resolved_relative_to_root(), close(), log, PATH_MAX, and RENAME_NOREPLACE.
Referenced by brix_rename_confined_canon(), and brix_rename_confined_canon_excl().