nginx-xrootd: src/fs/path/resolve_confined_ops_xattr.c File Reference
resolve_confined_ops_xattr.c File Reference
#include "core/ngx_brix_module.h"
#include "path_internal.h"
#include "beneath.h"
#include "auth/impersonate/impersonate.h"
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <sys/syscall.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/xattr.h>
#include <time.h>
#include <unistd.h>
#include <linux/openat2.h>
Functions
int brix_setxattr_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, const char *name, const void *value, size_t len, int flags)
ssize_t brix_getxattr_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, const char *name, void *buf, size_t bufsz)
int brix_removexattr_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, const char *name)
ssize_t brix_listxattr_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, void *buf, size_t bufsz)
Function Documentation
brix_getxattr_confined_canon()
ssize_t brix_getxattr_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, const char * name, void * buf, size_t bufsz)
Definition at line 60 of file resolve_confined_ops_xattr.c.
References brix_imp_client_active(), brix_imp_getxattr(), brix_resolved_relative_to_root(), log, name, and PATH_MAX.
Referenced by brix_vfs_getxattr(), and sd_posix_getxattr().
brix_listxattr_confined_canon()
ssize_t brix_listxattr_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, void * buf, size_t bufsz)
Definition at line 92 of file resolve_confined_ops_xattr.c.
References brix_imp_client_active(), brix_imp_listxattr(), brix_resolved_relative_to_root(), log, and PATH_MAX.
Referenced by brix_vfs_listxattr(), and sd_posix_listxattr().
brix_removexattr_confined_canon()
int brix_removexattr_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, const char * name)
Definition at line 76 of file resolve_confined_ops_xattr.c.
References brix_imp_client_active(), brix_imp_removexattr(), brix_resolved_relative_to_root(), log, name, and PATH_MAX.
Referenced by brix_vfs_removexattr(), and sd_posix_removexattr().
brix_setxattr_confined_canon()
int brix_setxattr_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, const char * name, const void * value, size_t len, int flags)
Definition at line 43 of file resolve_confined_ops_xattr.c.
References brix_imp_client_active(), brix_imp_setxattr(), brix_resolved_relative_to_root(), log, name, and PATH_MAX.
Referenced by brix_vfs_setxattr(), and sd_posix_setxattr().