nginx-xrootd: src/protocols/root/response/response.h File Reference
response.h File Reference
#include "core/ngx_brix_module.h"
#include "core/compat/pgio.h"
Functions
void brix_build_resp_hdr (const u_char *streamid, uint16_t status, uint32_t dlen, ServerResponseHdr *out)
ngx_int_t brix_send_ok (brix_ctx_t *ctx, ngx_connection_t *c, const void *body, uint32_t bodylen)
ngx_int_t brix_send_error (brix_ctx_t *ctx, ngx_connection_t *c, uint16_t errcode, const char *msg)
ngx_int_t brix_send_redirect (brix_ctx_t *ctx, ngx_connection_t *c, const char *host, uint16_t port)
ngx_int_t brix_send_redirect_tpc (brix_ctx_t *ctx, ngx_connection_t *c, const char *host, uint16_t port, const char *tpc_key)
ngx_int_t brix_send_wait (brix_ctx_t *ctx, ngx_connection_t *c, uint32_t seconds)
ngx_int_t brix_send_waitresp (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_send_pgwrite_status (brix_ctx_t *ctx, ngx_connection_t *c, int64_t write_offset)
ngx_int_t brix_send_pgwrite_cse (brix_ctx_t *ctx, ngx_connection_t *c, int64_t write_offset, const xrdp_pg_bad_t *bad, size_t n)
void brix_build_pgread_status (brix_ctx_t *ctx, int64_t file_offset, uint32_t total_with_crcs, ServerStatusResponse_pgRead *out)
uint32_t brix_crc32c (const void *buf, size_t len)
uint32_t brix_crc32c_extend (uint32_t crc, const void *buf, size_t len)
uint32_t brix_crc32c_copy (const u_char *src, u_char *dst, size_t len)
uint32_t brix_crc32c_file (int fd, const char *path, ngx_log_t *log)
Function Documentation
brix_build_pgread_status()
void brix_build_pgread_status (brix_ctx_t * ctx, int64_t file_offset, uint32_t total_with_crcs, ServerStatusResponse_pgRead * out)
Definition at line 134 of file status.c.
References ServerStatusResponse_pgRead::bdy, brix_crc32c(), ServerResponseBody_Status::crc32c, brix_ctx_recv_t::cur_streamid, ServerResponseHdr::dlen, ServerResponseBody_Status::dlen, ServerStatusResponse_pgRead::hdr, kXR_1stRequest, kXR_FinalResult, kXR_pgread, kXR_status, ServerResponseBody_pgRead::offset, ServerStatusResponse_pgRead::pgr, brix_ctx_t::recv, ServerResponseBody_Status::requestid, ServerResponseBody_Status::reserved, ServerResponseBody_Status::resptype, ServerResponseHdr::status, ServerResponseHdr::streamid, and ServerResponseBody_Status::streamID.
Referenced by brix_build_pgread_chain(), brix_handle_pgread(), and brix_pgread_aio_done().
brix_build_resp_hdr()
void brix_build_resp_hdr (const u_char * streamid, uint16_t status, uint32_t dlen, ServerResponseHdr * out)
Definition at line 33 of file basic.c.
References ServerResponseHdr::dlen, ServerResponseHdr::status, and ServerResponseHdr::streamid.
Referenced by brix_build_attn_asyncms_frame(), brix_build_chunked_chain(), brix_build_sendfile_chain(), brix_build_single_memory_chain(), brix_build_single_sendfile_chain(), brix_build_window_chain(), brix_gsi_begin_delegation(), brix_gsi_send_cert(), brix_handle_bind(), brix_handle_dirlist(), brix_handle_login(), brix_handle_prepare(), brix_handle_protocol(), brix_open_resolved_file(), brix_proxy_relay_to_client(), brix_send_attn(), brix_send_attn_asynresp(), brix_send_error(), brix_send_ok(), brix_send_redirect(), brix_send_redirect_tpc(), brix_send_wait(), brix_send_waitresp(), brix_ssi_open(), brix_sss_send_authmore(), brix_tpc_pull_done(), brix_upstream_forward_response(), brix_vfs_io_dirlist_flush_chunk(), brix_vfs_io_execute_opendir(), brix_zip_open_member(), pwd_send_credsreq(), and tpc_send_open_response().
brix_crc32c()
uint32_t brix_crc32c (const void * buf, size_t len)
Definition at line 16 of file crc32c.c.
References brix_crc32c_value().
Referenced by brix_build_pgread_status(), brix_send_pgwrite_cse(), and brix_send_pgwrite_status().
brix_crc32c_copy()
uint32_t brix_crc32c_copy (const u_char * src, u_char * dst, size_t len)
Definition at line 25 of file crc32c.c.
References brix_crc32c_copy_value().
brix_crc32c_extend()
uint32_t brix_crc32c_extend (uint32_t crc, const void * buf, size_t len)
Definition at line 556 of file crc32c.c.
References brix_crc32c_sw_extend().
Referenced by brix_cksum_u32_obj(), brix_crc32c_value(), brix_xmeta_decode(), and brix_xmeta_encode().
brix_crc32c_file()
uint32_t brix_crc32c_file (int fd, const char * path, ngx_log_t * log)
Definition at line 39 of file crc32c.c.
References BRIX_CHECKSUM_CRC32C, brix_checksum_u32_fd(), and log.
brix_send_error()
ngx_int_t brix_send_error (brix_ctx_t * ctx, ngx_connection_t * c, uint16_t errcode, const char * msg)
Definition at line 67 of file basic.c.
References brix_build_resp_hdr(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), c, brix_ctx_recv_t::cur_streamid, kXR_error, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_auth_gate_op(), brix_cache_fill_composed_done(), brix_cache_fill_done(), brix_cache_open_or_fill(), brix_ckscan_aio_done(), brix_ckscan_send_error(), brix_ckscan_sync(), brix_cksum_aio_done(), brix_dirlist_aio_done(), brix_dispatch(), brix_dispatch_op(), brix_dispatch_require_auth(), brix_dispatch_require_login(), brix_dispatch_require_write(), brix_gsi_complete_auth(), brix_handle_async_ab(), brix_handle_async_av(), brix_handle_async_di(), brix_handle_async_go(), brix_handle_async_ms(), brix_handle_async_rd(), brix_handle_async_unav(), brix_handle_async_wt(), brix_handle_auth(), brix_handle_auth_inner(), brix_handle_bind(), brix_handle_chkpoint(), brix_handle_close(), brix_handle_dirlist(), brix_handle_fattr(), brix_handle_host_auth(), brix_handle_krb5_auth(), brix_handle_link(), brix_handle_locate(), brix_handle_login(), brix_handle_mv(), brix_handle_open(), brix_handle_pgread(), brix_handle_protocol(), brix_handle_query(), brix_handle_readv(), brix_handle_setattr(), brix_handle_sigver(), brix_handle_sss_auth(), brix_handle_statx(), brix_handle_symlink(), brix_handle_token_auth(), brix_handle_unix_auth(), brix_handle_writev(), brix_pgread_aio_done(), brix_prepare_send_fail(), brix_proxy_abort(), brix_proxy_dispatch(), brix_proxy_forward_request(), brix_proxy_lazy_open(), brix_proxy_relay_lazy_open(), brix_query_ckscan(), brix_query_cksum_handle(), brix_query_cksum_path(), brix_query_cksum_send_error(), brix_query_config(), brix_query_fsinfo(), brix_query_prep_status(), brix_query_space(), brix_query_xattr(), brix_read_aio_done(), brix_read_window_emit(), brix_read_window_pump(), brix_readv_aio_done(), brix_reject_bound_nonread_file_op(), brix_reject_dotdot_path(), brix_resolve_op_path(), brix_signing_enforce_level(), brix_ssi_open(), brix_ssi_query(), brix_ssi_write(), brix_tpc_prepare_pull(), brix_tpc_pull_done(), brix_tpc_start_pull(), brix_upstream_abort(), brix_upstream_forward_response(), brix_verify_pending_sigver(), brix_verify_sigver_hmac(), brix_write_aio_done(), brix_writev_write_aio_done(), brix_zip_read(), ckp_begin(), ckp_rollback(), ckp_xeq(), ckp_xeq_pgwrite(), ckp_xeq_truncate(), ckp_xeq_write(), ckp_xeq_writev(), fattr_get(), fattr_list(), fattr_list_recurse(), fattr_send_vector_status(), fattr_set(), manager_redirect_mutation(), pwd_round1(), pwd_round2(), and pwd_send_credsreq().
brix_send_ok()
ngx_int_t brix_send_ok (brix_ctx_t * ctx, ngx_connection_t * c, const void * body, uint32_t bodylen)
Definition at line 43 of file basic.c.
References brix_build_resp_hdr(), brix_queue_response(), c, brix_ctx_recv_t::cur_streamid, kXR_ok, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_ckscan_aio_done(), brix_ckscan_sync(), brix_cksum_aio_done(), brix_handle_auth_inner(), brix_handle_close(), brix_handle_endsess(), brix_handle_locate(), brix_handle_prepare(), brix_handle_read(), brix_handle_readlink(), brix_handle_stat(), brix_handle_statx(), brix_handle_truncate(), brix_handle_write(), brix_handle_writev(), brix_prepare_handle_cancel(), brix_query_cksum_handle(), brix_query_cksum_path(), brix_query_config(), brix_query_finfo(), brix_query_fsinfo(), brix_query_prep_status(), brix_query_space(), brix_query_stats(), brix_query_xattr(), brix_read_compressed(), brix_ssi_query(), brix_ssi_read(), brix_ssi_write(), brix_tpc_pull_done(), brix_write_aio_done(), brix_write_compressed(), brix_writev_write_aio_done(), brix_zip_read(), ckp_query(), ckp_xeq_truncate(), ckp_xeq_write(), ckp_xeq_writev(), fattr_get(), fattr_list(), fattr_list_recurse(), and fattr_send_vector_status().
brix_send_pgwrite_cse()
ngx_int_t brix_send_pgwrite_cse (brix_ctx_t * ctx, ngx_connection_t * c, int64_t write_offset, const xrdp_pg_bad_t * bad, size_t n)
Definition at line 72 of file status.c.
References ServerStatusResponse_pgWrite::bdy, brix_crc32c(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), brix_send_pgwrite_status(), c, ServerResponseBody_Status::crc32c, ServerResponseBody_pgWrCSE::cseCRC, brix_ctx_recv_t::cur_streamid, xrdp_pg_bad_t::dlen, ServerResponseHdr::dlen, ServerResponseBody_Status::dlen, ServerResponseBody_pgWrCSE::dlFirst, ServerResponseBody_pgWrCSE::dlLast, ServerStatusResponse_pgWrite::hdr, kXR_1stRequest, kXR_FinalResult, kXR_pgwrite, kXR_status, xrdp_pg_bad_t::off, ServerResponseBody_pgWrite::offset, ServerStatusResponse_pgWrite::pgw, brix_ctx_t::recv, ServerResponseBody_Status::requestid, ServerResponseBody_Status::reserved, ServerResponseBody_Status::resptype, ServerResponseHdr::status, ServerResponseHdr::streamid, and ServerResponseBody_Status::streamID.
Referenced by brix_handle_pgwrite(), and brix_write_aio_done().
brix_send_pgwrite_status()
ngx_int_t brix_send_pgwrite_status (brix_ctx_t * ctx, ngx_connection_t * c, int64_t write_offset)
Definition at line 18 of file status.c.
References ServerStatusResponse_pgWrite::bdy, brix_crc32c(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), c, ServerResponseBody_Status::crc32c, brix_ctx_recv_t::cur_streamid, ServerResponseHdr::dlen, ServerResponseBody_Status::dlen, ServerStatusResponse_pgWrite::hdr, kXR_1stRequest, kXR_FinalResult, kXR_pgwrite, kXR_status, ServerResponseBody_pgWrite::offset, ServerStatusResponse_pgWrite::pgw, brix_ctx_t::recv, ServerResponseBody_Status::requestid, ServerResponseBody_Status::reserved, ServerResponseBody_Status::resptype, ServerResponseHdr::status, ServerResponseHdr::streamid, and ServerResponseBody_Status::streamID.
Referenced by brix_handle_pgwrite(), brix_send_pgwrite_cse(), brix_write_aio_done(), and ckp_xeq_pgwrite().
brix_send_redirect()
ngx_int_t brix_send_redirect (brix_ctx_t * ctx, ngx_connection_t * c, const char * host, uint16_t port)
Definition at line 10 of file control.c.
References brix_build_resp_hdr(), brix_format_host(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), c, brix_ctx_recv_t::cur_streamid, kXR_redirect, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_cache_fill_done(), brix_handle_locate(), brix_send_redirect_tpc(), cms_wake_pending_session(), and manager_redirect_mutation().
brix_send_redirect_tpc()
ngx_int_t brix_send_redirect_tpc (brix_ctx_t * ctx, ngx_connection_t * c, const char * host, uint16_t port, const char * tpc_key)
Definition at line 51 of file control.c.
References brix_build_resp_hdr(), brix_format_host(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), brix_send_redirect(), c, brix_ctx_recv_t::cur_streamid, kXR_redirect, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_handle_open().
brix_send_wait()
ngx_int_t brix_send_wait (brix_ctx_t * ctx, ngx_connection_t * c, uint32_t seconds)
Definition at line 96 of file control.c.
References brix_build_resp_hdr(), brix_queue_response(), c, brix_ctx_recv_t::cur_streamid, kXR_wait, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_handle_auth_inner(), brix_handle_open(), brix_handle_read(), brix_handle_readv(), brix_open_resolved_file(), brix_open_stage_backpressure(), brix_recv_pre_loop(), brix_rl_stream_gate(), and brix_tpc_start_pull().
brix_send_waitresp()
ngx_int_t brix_send_waitresp (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 124 of file control.c.
References brix_build_resp_hdr(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), c, brix_ctx_recv_t::cur_streamid, kXR_waitresp, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_handle_open(), brix_ssi_write(), and brix_upstream_forward_response().