nginx-xrootd: src/protocols/ssi/respbuf_unittest.c File Reference
respbuf_unittest.c File Reference
#include "respbuf.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Macros
#define CHECK(cond)
Functions
static void test_append_concatenates (void)
static void test_grows_past_initial_cap (void)
static void test_cap_max_rejects_overflow (void)
int main (void)
Variables
static int g_fail
Macro Definition Documentation
CHECK
#define CHECK (cond)
Value:
    do { \
    if (!(cond)) { printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
                   g_fail++; } \
} while (0)
Definition at line 13 of file respbuf_unittest.c.
Function Documentation
main()
int main (void)
Definition at line 54 of file respbuf_unittest.c.
References g_fail, test_append_concatenates(), test_cap_max_rejects_overflow(), and test_grows_past_initial_cap().
test_append_concatenates()
static void test_append_concatenates (void) static
Definition at line 18 of file respbuf_unittest.c.
References brix_ssi_respbuf_append(), CHECK, brix_ssi_respbuf_t::data, and brix_ssi_respbuf_t::len.
Referenced by main().
test_cap_max_rejects_overflow()
static void test_cap_max_rejects_overflow (void) static
Definition at line 42 of file respbuf_unittest.c.
References brix_ssi_respbuf_append(), CHECK, brix_ssi_respbuf_t::data, and brix_ssi_respbuf_t::len.
Referenced by main().
test_grows_past_initial_cap()
static void test_grows_past_initial_cap (void) static
Definition at line 29 of file respbuf_unittest.c.
References brix_ssi_respbuf_append(), brix_ssi_respbuf_t::cap, CHECK, brix_ssi_respbuf_t::data, and brix_ssi_respbuf_t::len.
Referenced by main().
Variable Documentation
g_fail
int g_fail static
Definition at line 12 of file respbuf_unittest.c.
Referenced by main().