nginx-xrootd: src/core/compat/result_mapper.h File Reference
result_mapper.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include "namespace_ops.h"
Functions
ngx_int_t brix_http_map_ns_status (brix_ns_status_t status)
ngx_int_t brix_http_map_errno (int err)
Function Documentation
brix_http_map_errno()
ngx_int_t brix_http_map_errno (int err)
Definition at line 278 of file error_mapping.c.
References brix_http_errno_to_status().
Referenced by s3_post_object_body_handler_inner(), webdav_put_open_target(), and webdav_put_ranged_resume().
brix_http_map_ns_status()
ngx_int_t brix_http_map_ns_status (brix_ns_status_t status)
Definition at line 240 of file error_mapping.c.
References BRIX_NS_CONFLICT, BRIX_NS_DENIED, BRIX_NS_EXISTS, BRIX_NS_IO_ERROR, BRIX_NS_NO_SPACE, BRIX_NS_NOT_EMPTY, BRIX_NS_NOT_FOUND, BRIX_NS_OK, and BRIX_NS_TOO_LONG.
Referenced by webdav_copy_errno_to_status().