nginx-xrootd: src/core/aio/resume.c File Reference
resume.c File Reference
#include "core/ngx_brix_module.h"
#include "uring.h"
#include "protocols/root/connection/disconnect.h"
#include "protocols/root/connection/fd_table.h"
Functions
static void brix_aio_resume_fail (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_session_t *s)
ngx_flag_t brix_aio_restore_stream (brix_ctx_t *ctx, const u_char streamid[2])
ngx_flag_t brix_aio_restore_request (brix_ctx_t *ctx, const u_char streamid[2])
ngx_int_t brix_aio_post_task (brix_ctx_t *ctx, ngx_connection_t *c, ngx_thread_pool_t *pool, ngx_thread_task_t *task, const char *fallback_log, ngx_flag_t *posted)
void brix_aio_resume (ngx_connection_t *c)
Function Documentation
brix_aio_post_task()
ngx_int_t brix_aio_post_task (brix_ctx_t * ctx, ngx_connection_t * c, ngx_thread_pool_t * pool, ngx_thread_task_t * task, const char * fallback_log, ngx_flag_t * posted)
Definition at line 74 of file resume.c.
References BRIX_SRV_METRIC_INC, c, ngx_brix_srv_metrics_t::io_uring_active, brix_ctx_t::metrics, op, brix_ctx_t::state, XRD_ST_AIO, and XRD_URING_OP_NONE.
Referenced by brix_pgread_post_aio(), brix_qcksum_handle_try_async(), brix_qcksum_try_async(), brix_query_ckscan(), brix_read_window_pump(), brix_readv_try_post_async(), brix_try_post_write_aio(), read_post_aio(), and writev_try_aio().
brix_aio_restore_request()
ngx_flag_t brix_aio_restore_request (brix_ctx_t * ctx, const u_char streamid[2])
Definition at line 48 of file resume.c.
References brix_aio_restore_stream(), brix_ctx_recv_t::hdr_pos, brix_ctx_t::recv, brix_ctx_t::state, and XRD_ST_REQ_HEADER.
Referenced by brix_cache_fill_composed_done(), brix_cache_fill_done(), brix_ckscan_aio_done(), brix_cksum_aio_done(), brix_dirlist_aio_done(), brix_pgread_aio_done(), brix_readv_aio_done(), brix_tpc_pull_done(), brix_write_aio_done_serial(), and brix_writev_write_aio_done().
brix_aio_restore_stream()
ngx_flag_t brix_aio_restore_stream (brix_ctx_t * ctx, const u_char streamid[2])
Definition at line 27 of file resume.c.
References brix_ctx_recv_t::cur_streamid, brix_ctx_t::destroyed, and brix_ctx_t::recv.
Referenced by brix_aio_restore_request(), brix_read_aio_done(), and brix_write_aio_done_pipelined().
brix_aio_resume()
void brix_aio_resume (ngx_connection_t * c)
Definition at line 141 of file resume.c.
References brix_aio_resume_fail(), brix_ensure_write_event(), brix_schedule_read_resume(), c, brix_ctx_t::destroyed, ngx_stream_brix_module, s, brix_ctx_t::state, and XRD_ST_SENDING.
Referenced by brix_cache_fill_composed_done(), brix_cache_fill_done(), brix_ckscan_aio_done(), brix_cksum_aio_done(), brix_dirlist_aio_done(), brix_pgread_aio_done(), brix_read_aio_done(), brix_read_window_pump(), brix_readv_aio_done(), brix_write_aio_done_serial(), brix_write_aio_serial_reply_ok(), brix_writev_write_aio_done(), tpc_done_reply_open(), tpc_done_reply_sync(), tpc_done_send_open_ok(), and tpc_done_sync_fail().
brix_aio_resume_fail()
static void brix_aio_resume_fail (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_session_t * s) static
Definition at line 191 of file resume.c.
References brix_close_all_files(), brix_defer_teardown_if_writing(), brix_on_disconnect(), c, and s.
Referenced by brix_aio_resume().