nginx-xrootd: client/lib/fs/rmtree.c File Reference
rmtree.c File Reference
#include "brix.h"
#include "brix_ops.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Macros
#define BRIX_RMTREE_MAXDEPTH 64
Functions
static int rmtree_join (const char *dir, const char *name, char *out, size_t outsz)
static int rmtree_depth (brix_conn *c, const char *path, int depth, unsigned flags, brix_rmtree_report report, void *u, brix_status *st)
int brix_rmtree (brix_conn *c, const char *path, unsigned flags, brix_rmtree_report report, void *u, brix_status *st)
Macro Definition Documentation
BRIX_RMTREE_MAXDEPTH
#define BRIX_RMTREE_MAXDEPTH 64
Definition at line 18 of file rmtree.c.
Function Documentation
brix_rmtree()
int brix_rmtree (brix_conn * c, const char * path, unsigned flags, brix_rmtree_report report, void * u, brix_status * st)
Definition at line 139 of file rmtree.c.
References brix_status_set(), c, report(), rmtree_depth(), and XRDC_EUSAGE.
Referenced by do_rm(), and mirror_delete_remote().
rmtree_depth()
static int rmtree_depth (brix_conn * c, const char * path, int depth, unsigned flags, brix_rmtree_report report, void * u, brix_status * st) static
Definition at line 50 of file rmtree.c.
References brix_dirlist(), brix_lstat(), brix_rm(), brix_rmdir(), BRIX_RMTREE_DRYRUN, BRIX_RMTREE_MAXDEPTH, brix_status_set(), c, brix_statinfo::flags, kXR_isDir, kXR_other, name, report(), rmtree_depth(), rmtree_join(), XRDC_EUSAGE, and XRDC_PATH_MAX.
Referenced by brix_rmtree(), and rmtree_depth().
rmtree_join()
static int rmtree_join (const char * dir, const char * name, char * out, size_t outsz) static
Definition at line 29 of file rmtree.c.
References name.
Referenced by rmtree_depth().