nginx-xrootd: src/protocols/root/query/util.c File Reference
util.c File Reference
#include "query_internal.h"
#include "core/compat/checksum.h"
#include <errno.h>
Functions
uint32_t brix_query_adler32_fd (int fd, const char *path, ngx_log_t *log)
uint32_t brix_query_adler32_file (const ngx_str_t *root, const char *path, ngx_log_t *log)
ngx_flag_t brix_query_digest_fd (int fd, const char *path, brix_checksum_alg_t alg, unsigned char *out, unsigned int *outlen, ngx_log_t *log)
ngx_flag_t brix_query_digest_file (const ngx_str_t *root, const char *path, brix_checksum_alg_t alg, unsigned char *out, unsigned int *outlen, ngx_log_t *log)
uint32_t brix_query_crc32_fd (int fd, const char *path, ngx_log_t *log)
uint32_t brix_query_crc32_file (const ngx_str_t *root, const char *path, ngx_log_t *log)
Function Documentation
brix_query_adler32_fd()
uint32_t brix_query_adler32_fd (int fd, const char * path, ngx_log_t * log)
Definition at line 106 of file util.c.
References BRIX_CHECKSUM_ADLER32, brix_checksum_u32_fd(), and log.
Referenced by brix_query_adler32_file().
brix_query_adler32_file()
uint32_t brix_query_adler32_file (const ngx_str_t * root, const char * path, ngx_log_t * log)
Definition at line 120 of file util.c.
References brix_open_confined(), brix_query_adler32_fd(), brix_sanitize_log_string(), close(), and log.
brix_query_crc32_fd()
uint32_t brix_query_crc32_fd (int fd, const char * path, ngx_log_t * log)
Definition at line 192 of file util.c.
References BRIX_CHECKSUM_CRC32, brix_checksum_u32_fd(), and log.
Referenced by brix_query_crc32_file().
brix_query_crc32_file()
uint32_t brix_query_crc32_file (const ngx_str_t * root, const char * path, ngx_log_t * log)
Definition at line 206 of file util.c.
References brix_open_confined(), brix_query_crc32_fd(), brix_sanitize_log_string(), close(), and log.
brix_query_digest_fd()
ngx_flag_t brix_query_digest_fd (int fd, const char * path, brix_checksum_alg_t alg, unsigned char * out, unsigned int * outlen, ngx_log_t * log)
Definition at line 142 of file util.c.
References brix_checksum_digest_fd(), and log.
Referenced by brix_query_digest_file().
brix_query_digest_file()
ngx_flag_t brix_query_digest_file (const ngx_str_t * root, const char * path, brix_checksum_alg_t alg, unsigned char * out, unsigned int * outlen, ngx_log_t * log)
Definition at line 151 of file util.c.
References brix_open_confined(), brix_query_digest_fd(), brix_sanitize_log_string(), close(), and log.