nginx-xrootd: src/protocols/root/handshake/dispatch.c File Reference
dispatch.c File Reference
#include "handshake.h"
#include "net/proxy/proxy.h"
#include "net/mirror/stream_mirror.h"
#include "net/mirror/stream_wmirror.h"
#include "net/ratelimit/ratelimit.h"
#include "auth/impersonate/lifecycle.h"
Functions
ngx_int_t brix_dispatch (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_dispatch()
ngx_int_t brix_dispatch (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 31 of file dispatch.c.
References brix_ctx_login_t::auth_done, BRIX_DISPATCH_CONTINUE, brix_dispatch_read_opcode(), brix_dispatch_session_opcode(), brix_dispatch_signing_opcode(), brix_dispatch_write_opcode(), brix_imp_request_begin(), brix_imp_request_end(), brix_min_sec_enforce(), brix_proxy_dispatch(), brix_rl_stream_gate(), brix_send_error(), brix_signing_enforce_level(), brix_stream_mirror_maybe(), brix_stream_wmirror_observe(), brix_verify_pending_sigver(), c, brix_ctx_recv_t::cur_reqid, brix_ctx_t::identity, kXR_InvalidRequest, brix_ctx_t::login, brix_ctx_t::recv, and brix_ctx_t::req_start.
Referenced by brix_recv_after_header(), brix_recv_after_payload(), and brix_recv_run_deferred().