nginx-xrootd: src/protocols/root/fattr/dispatch.c File Reference
dispatch.c File Reference
#include "ngx_brix_fattr.h"
#include "fs/vfs/vfs.h"
#include "protocols/root/path/op_path.h"
#include <string.h>
#include "core/compat/alloc_guard.h"
Data Structures
struct fattr_state_t
struct fattr_names_t
Functions
static ngx_int_t fattr_fail (fattr_state_t *st, ngx_int_t rc)
static ngx_int_t fattr_check_request (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, fattr_state_t *st)
static void fattr_bind_vctx (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, fattr_state_t *st)
static ngx_int_t fattr_fhandle_target (brix_ctx_t *ctx, ngx_connection_t *c, fattr_state_t *st, unsigned char fh0)
static ngx_int_t fattr_path_target (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, fattr_state_t *st)
static ngx_int_t fattr_select_target (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, fattr_state_t *st, const xrdw_fattr_req_t *req)
static ngx_int_t fattr_decode_names (brix_ctx_t *ctx, ngx_connection_t *c, fattr_state_t *st, brix_fattr_entry_t *attrs, fattr_names_t *names)
static ngx_int_t fattr_dispatch_named (brix_ctx_t *ctx, ngx_connection_t *c, fattr_state_t *st)
ngx_int_t brix_handle_fattr (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_handle_fattr()
ngx_int_t brix_handle_fattr (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 432 of file dispatch.c.
References fattr_state_t::args_buf, fattr_state_t::args_len, brix_send_error(), c, close(), fattr_state_t::close_fd, fattr_state_t::err_rc, fattr_check_request(), fattr_dispatch_named(), fattr_list(), fattr_select_target(), fattr_state_t::fd, brix_ctx_recv_t::hdr_buf, kXR_ArgMissing, kXR_fattrList, fattr_state_t::numattr, xrdw_fattr_req_t::numattr, fattr_state_t::options, xrdw_fattr_req_t::options, fattr_state_t::path, brix_ctx_t::recv, fattr_state_t::subcode, xrdw_fattr_req_t::subcode, fattr_state_t::vctx, and xrdw_fattr_req_unpack().
Referenced by brix_dispatch_read_opcode().
fattr_bind_vctx()
static void fattr_bind_vctx (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, fattr_state_t * st) static
Definition at line 141 of file dispatch.c.
References BRIX_PROTO_ROOT, brix_root_vfs_bind_deleg(), brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), c, brix_ctx_t::identity, fattr_state_t::path, brix_vfs_ctx_t::pool, and fattr_state_t::vctx.
Referenced by fattr_path_target(), and fattr_select_target().
fattr_check_request()
static ngx_int_t fattr_check_request (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, fattr_state_t * st) static
Definition at line 98 of file dispatch.c.
References BRIX_OP_ERR, BRIX_OP_FATTR, brix_send_error(), c, fattr_fail(), kXR_ArgInvalid, kXR_faMaxVars, kXR_fattrDel, kXR_fattrList, kXR_fattrMaxSC, kXR_fattrSet, kXR_fsReadOnly, fattr_state_t::numattr, and fattr_state_t::subcode.
Referenced by brix_handle_fattr().
fattr_decode_names()
static ngx_int_t fattr_decode_names (brix_ctx_t * ctx, ngx_connection_t * c, fattr_state_t * st, brix_fattr_entry_t * attrs, fattr_names_t * names) static
Definition at line 339 of file dispatch.c.
References fattr_state_t::args_buf, fattr_state_t::args_len, BRIX_PALLOC_OR_RETURN, brix_send_error(), c, fattr_fail(), fattr_parse_nvec(), kXR_ArgInvalid, kXR_NoMemory, ngx_memcpy, fattr_state_t::numattr, fattr_names_t::nvec_copy, fattr_names_t::nvec_len, fattr_names_t::vvec_buf, and fattr_names_t::vvec_len.
Referenced by fattr_dispatch_named().
fattr_dispatch_named()
static ngx_int_t fattr_dispatch_named (brix_ctx_t * ctx, ngx_connection_t * c, fattr_state_t * st) static
Definition at line 377 of file dispatch.c.
References brix_send_error(), c, close(), fattr_state_t::close_fd, fattr_state_t::err_rc, fattr_decode_names(), fattr_del(), fattr_get(), fattr_set(), fattr_state_t::fd, kXR_faMaxVars, kXR_fattrDel, kXR_fattrGet, kXR_fattrSet, kXR_Unsupported, fattr_state_t::numattr, fattr_names_t::nvec_copy, fattr_names_t::nvec_len, fattr_state_t::options, fattr_state_t::path, fattr_state_t::subcode, fattr_state_t::vctx, fattr_names_t::vvec_buf, and fattr_names_t::vvec_len.
Referenced by brix_handle_fattr().
fattr_fail()
static ngx_int_t fattr_fail (fattr_state_t * st, ngx_int_t rc) static
Definition at line 79 of file dispatch.c.
References fattr_state_t::err_rc.
Referenced by fattr_check_request(), fattr_decode_names(), fattr_fhandle_target(), fattr_path_target(), and fattr_select_target().
fattr_fhandle_target()
static ngx_int_t fattr_fhandle_target (brix_ctx_t * ctx, ngx_connection_t * c, fattr_state_t * st, unsigned char fh0) static
Definition at line 168 of file dispatch.c.
References BRIX_MAX_FILES, BRIX_OP_ERR, BRIX_OP_FATTR, brix_send_error(), c, fattr_fail(), brix_file_t::fd, fattr_state_t::fd, brix_ctx_t::files, kXR_FileNotOpen, brix_file_t::path, fattr_state_t::path, and brix_file_t::sd_obj.
Referenced by fattr_select_target().
fattr_path_target()
static ngx_int_t fattr_path_target (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, fattr_state_t * st) static
Definition at line 209 of file dispatch.c.
References fattr_state_t::args_buf, fattr_state_t::args_len, brix_auth_gate(), BRIX_AUTH_READ, BRIX_AUTH_UPDATE, brix_beneath_full_path(), brix_extract_path(), brix_kxr_from_errno(), BRIX_OP_ERR, BRIX_OP_FATTR, brix_send_error(), c, brix_ctx_recv_t::cur_dlen, fattr_bind_vctx(), fattr_fail(), fattr_state_t::full_path, kXR_ArgInvalid, kXR_ArgMissing, kXR_fattrDel, kXR_fattrSet, fattr_state_t::path, fattr_state_t::pathbuf, brix_ctx_recv_t::payload, brix_ctx_t::recv, fattr_state_t::subcode, fattr_state_t::vctx, and brix_ctx_t::write_rc.
Referenced by fattr_select_target().
fattr_select_target()
static ngx_int_t fattr_select_target (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, fattr_state_t * st, const xrdw_fattr_req_t * req) static
Definition at line 288 of file dispatch.c.
References fattr_state_t::args_buf, fattr_state_t::args_len, brix_send_error(), c, brix_ctx_recv_t::cur_dlen, fattr_bind_vctx(), fattr_fail(), fattr_fhandle_target(), fattr_path_target(), xrdw_fattr_req_t::fhandle, kXR_ArgMissing, kXR_fattrList, brix_ctx_recv_t::payload, brix_ctx_t::recv, and fattr_state_t::subcode.
Referenced by brix_handle_fattr().