nginx-xrootd: src/protocols/root/session/session.h File Reference
session.h File Reference
#include "core/ngx_brix_module.h"
Functions
ngx_int_t brix_handle_protocol (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_handle_login (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_handle_ping (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_handle_endsess (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_handle_sigver (brix_ctx_t *ctx, ngx_connection_t *c)
int gsi_find_bucket (const u_char *payload, size_t plen, uint32_t target_type, const u_char **data_out, size_t *len_out)
STACK_OF (X509) *brix_gsi_parse_x509(brix_ctx_t *ctx
ngx_int_t brix_handle_auth (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_gsi_inflight_admit (brix_ctx_t *ctx, ngx_int_t cap)
void brix_gsi_inflight_release (brix_ctx_t *ctx)
Variables
ngx_connection_t * c
Function Documentation
brix_gsi_inflight_admit()
ngx_int_t brix_gsi_inflight_admit (brix_ctx_t * ctx, ngx_int_t cap)
Definition at line 125 of file auth.c.
References brix_gsi_inflight, brix_ctx_login_t::gsi_counted, and brix_ctx_t::login.
Referenced by gsi_auth_step_certreq().
brix_gsi_inflight_release()
void brix_gsi_inflight_release (brix_ctx_t * ctx)
Definition at line 139 of file auth.c.
References brix_gsi_inflight, brix_ctx_login_t::gsi_counted, and brix_ctx_t::login.
Referenced by brix_gsi_complete_auth(), and brix_on_disconnect().
brix_handle_auth()
ngx_int_t brix_handle_auth (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 662 of file auth.c.
References brix_ctx_login_t::auth_done, brix_ctx_login_t::auth_fail_count, brix_handle_auth_inner(), BRIX_MAX_AUTH_ATTEMPTS, brix_send_error(), c, brix_ctx_recv_t::cur_body, brix_ctx_recv_t::cur_dlen, kXGC_certreq, kXR_NotAuthorized, brix_ctx_t::login, ngx_memcpy, brix_ctx_recv_t::payload, brix_ctx_t::pwd, brix_ctx_t::recv, brix_ctx_pwd_t::round, and brix_ctx_login_t::user.
Referenced by brix_dispatch_session_opcode().
brix_handle_endsess()
ngx_int_t brix_handle_endsess (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 23 of file lifecycle.c.
References brix_ctx_login_t::auth_done, brix_close_all_files(), brix_on_disconnect(), brix_send_ok(), BRIX_SESS_END_SERVER, BRIX_SESSION_ID_LEN, brix_session_unregister(), c, brix_ctx_recv_t::hdr_buf, kXR_endsess, brix_ctx_login_t::logged_in, brix_ctx_t::login, ngx_memcpy, brix_ctx_t::proxy, brix_ctx_t::recv, brix_ctx_t::sess_end_hint, brix_ctx_t::sess_end_hint_set, ClientEndsessRequest::sessid, brix_ctx_login_t::sessid, XRD_PX_IDLE, and XRD_REQUEST_HDR_LEN.
Referenced by brix_dispatch_session_opcode().
brix_handle_login()
ngx_int_t brix_handle_login (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 271 of file login.c.
References BRIX_AUTH_NONE, brix_login_precheck_and_parse(), brix_login_respond_anon(), brix_login_respond_authenticated(), and c.
Referenced by brix_dispatch_session_opcode().
brix_handle_ping()
ngx_int_t brix_handle_ping (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 13 of file lifecycle.c.
References BRIX_OP_PING, BRIX_RETURN_OK, and c.
Referenced by brix_dispatch_session_opcode().
brix_handle_protocol()
ngx_int_t brix_handle_protocol (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 212 of file protocol.c.
References brix_build_resp_hdr(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), brix_send_error(), c, protocol_want_t::client_flags, protocol_want_t::client_wants_tls, brix_ctx_recv_t::cur_streamid, ServerProtocolBody::flags, kXR_ok, kXR_PROTOCOLVERSION, kXR_secreqs, kXR_TLSRequired, ngx_memcpy, protocol_want_t::offer_tls, protocol_negotiate_flags(), protocol_parse_client_req(), protocol_sec_count(), protocol_write_sec_trailer(), ServerProtocolBody::pval, brix_ctx_t::recv, brix_ctx_t::tls_pending, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_dispatch_session_opcode().
brix_handle_sigver()
ngx_int_t brix_handle_sigver (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 28 of file signing.c.
References brix_log_access(), brix_send_error(), c, xrdw_sigver_req_t::crypto, brix_ctx_recv_t::cur_dlen, brix_ctx_sigver_t::expectrid, xrdw_sigver_req_t::expectrid, xrdw_sigver_req_t::flags, brix_ctx_recv_t::hdr_buf, brix_ctx_sigver_t::hmac, kXR_ArgInvalid, kXR_HashMask_sig, kXR_nodata_sig, kXR_NotAuthorized, kXR_rsaKey_sig, kXR_SHA256_sig, brix_ctx_sigver_t::last_seqno, ngx_memcpy, brix_ctx_sigver_t::nodata, brix_ctx_recv_t::payload, brix_ctx_sigver_t::pending, brix_ctx_t::recv, brix_ctx_sigver_t::seqno, xrdw_sigver_req_t::seqno, brix_ctx_sigver_t::signing_active, brix_ctx_t::sigver, and xrdw_sigver_req_unpack().
Referenced by brix_dispatch_signing_opcode().
gsi_find_bucket()
int gsi_find_bucket (const u_char * payload, size_t plen, uint32_t target_type, const u_char ** data_out, size_t * len_out)
Definition at line 29 of file buffer.c.
References brix_gsi_find_bucket().
Referenced by brix_gsi_select_cipher_name(), gsi_capture_fullproxy(), gsi_certreq_clnt_opts(), gsi_certreq_version(), gsi_recover_peer_signed(), gsi_sign_client_rtag(), gsi_unsigned_build_peer(), STACK_OF(), and tpc_gsi_verify_server_cert().
STACK_OF()
STACK_OF (X509)
Variable Documentation
c
ngx_connection_t* c
Definition at line 59 of file session.h.