nginx-xrootd: src/protocols/root/fattr/get.c File Reference
get.c File Reference
#include "ngx_brix_fattr.h"
#include <errno.h>
#include <sys/types.h>
#include <arpa/inet.h>
#include "core/compat/alloc_guard.h"
Functions
static ssize_t fattr_read_value_size (brix_vfs_ctx_t *vctx, const char *path, int fd, const char *xkey)
static ssize_t fattr_read_value (brix_vfs_ctx_t *vctx, const char *path, int fd, const char *xkey, u_char *value, size_t value_len)
static size_t fattr_value_len_for_response (const brix_fattr_entry_t *attr)
ngx_int_t fattr_get (brix_ctx_t *ctx, ngx_connection_t *c, brix_vfs_ctx_t *vctx, const char *path, int fd, u_char *nvec_copy, size_t nvec_len, int numattr, brix_fattr_entry_t *attrs)
Function Documentation
fattr_get()
ngx_int_t fattr_get (brix_ctx_t * ctx, ngx_connection_t * c, brix_vfs_ctx_t * vctx, const char * path, int fd, u_char * nvec_copy, size_t nvec_len, int numattr, brix_fattr_entry_t * attrs)
Definition at line 81 of file get.c.
References BRIX_OP_FATTR, BRIX_OP_OK, BRIX_PALLOC_OR_RETURN, brix_send_error(), brix_send_ok(), c, fattr_errno_to_xrd(), fattr_read_value(), fattr_read_value_size(), fattr_set_rc(), fattr_value_len_for_response(), kXR_faMaxVlen, kXR_NoMemory, brix_fattr_entry_t::value, brix_fattr_entry_t::vlen, and brix_fattr_entry_t::xkey.
Referenced by brix_handle_fattr().
fattr_read_value()
static ssize_t fattr_read_value (brix_vfs_ctx_t * vctx, const char * path, int fd, const char * xkey, u_char * value, size_t value_len) static
Definition at line 39 of file get.c.
References brix_vfs_fgetxattr(), and brix_vfs_getxattr().
Referenced by fattr_get().
fattr_read_value_size()
static ssize_t fattr_read_value_size (brix_vfs_ctx_t * vctx, const char * path, int fd, const char * xkey) static
Definition at line 20 of file get.c.
References brix_vfs_fgetxattr(), and brix_vfs_getxattr().
Referenced by fattr_get().
fattr_value_len_for_response()
static size_t fattr_value_len_for_response (const brix_fattr_entry_t * attr) static
Definition at line 55 of file get.c.
References brix_fattr_entry_t::vlen.
Referenced by fattr_get().