nginx-xrootd: src/protocols/root/query/dispatch.c File Reference
dispatch.c File Reference
#include "query_internal.h"
#include "protocols/ssi/ssi.h"
Functions
static ngx_int_t brix_query_route_common (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, xrdw_query_req_t *req, uint16_t infotype)
static ngx_int_t brix_query_route_extended (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, xrdw_query_req_t *req, uint16_t infotype)
ngx_int_t brix_handle_query (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_handle_query()
ngx_int_t brix_handle_query (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 154 of file dispatch.c.
References brix_query_route_common(), brix_query_route_extended(), brix_send_error(), c, brix_ctx_recv_t::hdr_buf, xrdw_query_req_t::infotype, kXR_Unsupported, brix_ctx_t::recv, and xrdw_query_req_unpack().
Referenced by brix_dispatch_read_opcode().
brix_query_route_common()
static ngx_int_t brix_query_route_common (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, xrdw_query_req_t * req, uint16_t infotype) static
Definition at line 36 of file dispatch.c.
References brix_query_ckscan(), brix_query_cksum(), brix_query_config(), brix_query_finfo(), brix_query_fsinfo(), brix_query_prep_status(), brix_query_space(), brix_query_stats(), brix_query_xattr(), c, kXR_Qckscan, kXR_Qcksum, kXR_Qconfig, kXR_QFinfo, kXR_QFSinfo, kXR_QPrep, kXR_Qspace, kXR_QStats, and kXR_Qxattr.
Referenced by brix_handle_query().
brix_query_route_extended()
static ngx_int_t brix_query_route_extended (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, xrdw_query_req_t * req, uint16_t infotype) static
Definition at line 100 of file dispatch.c.
References BRIX_OP_QUERY_VISA, brix_query_opaque(), brix_query_opaquf(), brix_query_opaqug(), brix_query_visa(), BRIX_RETURN_ERR, brix_ssi_query(), c, brix_ctx_recv_t::cur_dlen, xrdw_query_req_t::fhandle, kXR_ArgInvalid, kXR_Qopaque, kXR_Qopaquf, kXR_Qopaqug, kXR_Qvisa, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by brix_handle_query().