nginx-xrootd: src/net/cms/router.h File Reference
router.h File Reference
Data Structures
struct brix_cms_route_t
Macros
#define XRDCMS_RF_SYNC 0x01u /* isSync: handled inline, reply now */
#define XRDCMS_RF_FORWARD 0x02u /* Forward: manager fans op out to nodes */
#define XRDCMS_RF_REPLIABLE 0x04u /* Repliable: originator expects a reply */
#define XRDCMS_RF_DELAYABLE 0x08u /* Delayable: may answer kYR_wait */
#define XRDCMS_RF_NOARGS 0x10u /* noArgs: header-only, empty payload */
Enumerations
enum brix_cms_role_t { XRDCMS_ROLE_MANAGER = 0 , XRDCMS_ROLE_NODE = 1 }
Functions
const brix_cms_route_t * brix_cms_route_lookup (brix_cms_role_t role, unsigned char code)
Macro Definition Documentation
XRDCMS_RF_DELAYABLE
#define XRDCMS_RF_DELAYABLE 0x08u /* Delayable: may answer kYR_wait */
Definition at line 22 of file router.h.
XRDCMS_RF_FORWARD
#define XRDCMS_RF_FORWARD 0x02u /* Forward: manager fans op out to nodes */
Definition at line 20 of file router.h.
XRDCMS_RF_NOARGS
#define XRDCMS_RF_NOARGS 0x10u /* noArgs: header-only, empty payload */
Definition at line 23 of file router.h.
XRDCMS_RF_REPLIABLE
#define XRDCMS_RF_REPLIABLE 0x04u /* Repliable: originator expects a reply */
Definition at line 21 of file router.h.
XRDCMS_RF_SYNC
#define XRDCMS_RF_SYNC 0x01u /* isSync: handled inline, reply now */
Definition at line 19 of file router.h.
Enumeration Type Documentation
brix_cms_role_t
enum brix_cms_role_t
Enumerator
XRDCMS_ROLE_MANAGER
XRDCMS_ROLE_NODE
Definition at line 25 of file router.h.
Function Documentation
brix_cms_route_lookup()
const brix_cms_route_t * brix_cms_route_lookup (brix_cms_role_t role, unsigned char code)
Definition at line 116 of file router.c.
References code, manager_routes, node_routes, route_scan(), and XRDCMS_ROLE_NODE.
Referenced by cms_frame_forward(), cms_srv_frame_unknown(), ngx_brix_cms_process_frame(), test_manager_forwardable_mkdir(), test_manager_locate_not_forwarded(), test_manager_ping_sync_noargs(), test_node_executes_forwarded_mkdir_without_reforward(), test_node_rejects_node_status_opcode(), test_unknown_opcode_rejected(), and test_update_routed_both_roles().