nginx-xrootd: src/net/cms/router_unittest.c File Reference
router_unittest.c File Reference
#include "router.h"
#include <stdio.h>
#include <string.h>
Macros
#define K_LOCATE 2
#define K_MKDIR 3
#define K_MV 5
#define K_PREPDEL 7
#define K_PING 17
#define K_AVAIL 12
#define K_UPDATE 25
#define CHECK(cond)
Functions
static void test_manager_forwardable_mkdir (void)
static void test_manager_locate_not_forwarded (void)
static void test_manager_ping_sync_noargs (void)
static void test_node_executes_forwarded_mkdir_without_reforward (void)
static void test_node_rejects_node_status_opcode (void)
static void test_update_routed_both_roles (void)
static void test_unknown_opcode_rejected (void)
int main (void)
Variables
static int g_fail
Macro Definition Documentation
CHECK
#define CHECK (cond)
Value:
    do { \
    if (!(cond)) { printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
                   g_fail++; } \
} while (0)
Definition at line 24 of file router_unittest.c.
K_AVAIL
#define K_AVAIL 12
Definition at line 20 of file router_unittest.c.
K_LOCATE
#define K_LOCATE 2
Definition at line 15 of file router_unittest.c.
K_MKDIR
#define K_MKDIR 3
Definition at line 16 of file router_unittest.c.
K_MV
#define K_MV 5
Definition at line 17 of file router_unittest.c.
K_PING
#define K_PING 17
Definition at line 19 of file router_unittest.c.
K_PREPDEL
#define K_PREPDEL 7
Definition at line 18 of file router_unittest.c.
K_UPDATE
#define K_UPDATE 25
Definition at line 21 of file router_unittest.c.
Function Documentation
main()
int main (void)
Definition at line 106 of file router_unittest.c.
References g_fail, test_manager_forwardable_mkdir(), test_manager_locate_not_forwarded(), test_manager_ping_sync_noargs(), test_node_executes_forwarded_mkdir_without_reforward(), test_node_rejects_node_status_opcode(), test_unknown_opcode_rejected(), and test_update_routed_both_roles().
test_manager_forwardable_mkdir()
static void test_manager_forwardable_mkdir (void) static
Definition at line 30 of file router_unittest.c.
References brix_cms_route_lookup(), CHECK, brix_cms_route_t::flags, K_MKDIR, brix_cms_route_t::name, XRDCMS_RF_DELAYABLE, XRDCMS_RF_FORWARD, XRDCMS_RF_REPLIABLE, and XRDCMS_ROLE_MANAGER.
Referenced by main().
test_manager_locate_not_forwarded()
static void test_manager_locate_not_forwarded (void) static
Definition at line 44 of file router_unittest.c.
References brix_cms_route_lookup(), CHECK, brix_cms_route_t::flags, K_LOCATE, XRDCMS_RF_FORWARD, XRDCMS_RF_REPLIABLE, and XRDCMS_ROLE_MANAGER.
Referenced by main().
test_manager_ping_sync_noargs()
static void test_manager_ping_sync_noargs (void) static
Definition at line 57 of file router_unittest.c.
References brix_cms_route_lookup(), CHECK, brix_cms_route_t::flags, K_PING, brix_cms_route_t::name, XRDCMS_RF_FORWARD, XRDCMS_RF_NOARGS, XRDCMS_RF_SYNC, and XRDCMS_ROLE_MANAGER.
Referenced by main().
test_node_executes_forwarded_mkdir_without_reforward()
static void test_node_executes_forwarded_mkdir_without_reforward (void) static
Definition at line 71 of file router_unittest.c.
References brix_cms_route_lookup(), CHECK, brix_cms_route_t::flags, K_MKDIR, XRDCMS_RF_FORWARD, and XRDCMS_ROLE_NODE.
Referenced by main().
test_node_rejects_node_status_opcode()
static void test_node_rejects_node_status_opcode (void) static
Definition at line 83 of file router_unittest.c.
References brix_cms_route_lookup(), CHECK, K_AVAIL, and XRDCMS_ROLE_NODE.
Referenced by main().
test_unknown_opcode_rejected()
static void test_unknown_opcode_rejected (void) static
Definition at line 99 of file router_unittest.c.
References brix_cms_route_lookup(), CHECK, XRDCMS_ROLE_MANAGER, and XRDCMS_ROLE_NODE.
Referenced by main().
test_update_routed_both_roles()
static void test_update_routed_both_roles (void) static
Definition at line 92 of file router_unittest.c.
References brix_cms_route_lookup(), CHECK, K_UPDATE, XRDCMS_ROLE_MANAGER, and XRDCMS_ROLE_NODE.
Referenced by main().
Variable Documentation
g_fail
int g_fail static
Definition at line 23 of file router_unittest.c.
Referenced by main().