nginx-xrootd: src/net/cms/router.c File Reference
router.c File Reference
#include "router.h"
#include <stddef.h>
Macros
#define K_LOGIN 0
#define K_CHMOD 1
#define K_LOCATE 2
#define K_MKDIR 3
#define K_MKPATH 4
#define K_MV 5
#define K_PREPADD 6
#define K_PREPDEL 7
#define K_RM 8
#define K_RMDIR 9
#define K_SELECT 10
#define K_STATS 11
#define K_AVAIL 12
#define K_DISC 13
#define K_GONE 14
#define K_HAVE 15
#define K_LOAD 16
#define K_PING 17
#define K_PONG 18
#define K_SPACE 19
#define K_STATE 20
#define K_STATFS 21
#define K_STATUS 22
#define K_TRUNC 23
#define K_TRY 24
#define K_UPDATE 25
#define K_USAGE 26
#define K_XAUTH 27
#define RF_FWD (XRDCMS_RF_FORWARD | XRDCMS_RF_REPLIABLE | XRDCMS_RF_DELAYABLE)
#define RF_RD (XRDCMS_RF_REPLIABLE | XRDCMS_RF_DELAYABLE)
Functions
static const brix_cms_route_t * route_scan (const brix_cms_route_t *tbl, size_t n, unsigned char code)
const brix_cms_route_t * brix_cms_route_lookup (brix_cms_role_t role, unsigned char code)
Variables
static const brix_cms_route_t manager_routes []
static const brix_cms_route_t node_routes []
Macro Definition Documentation
K_AVAIL
#define K_AVAIL 12
Definition at line 28 of file router.c.
K_CHMOD
#define K_CHMOD 1
Definition at line 17 of file router.c.
K_DISC
#define K_DISC 13
Definition at line 29 of file router.c.
K_GONE
#define K_GONE 14
Definition at line 30 of file router.c.
K_HAVE
#define K_HAVE 15
Definition at line 31 of file router.c.
K_LOAD
#define K_LOAD 16
Definition at line 32 of file router.c.
K_LOCATE
#define K_LOCATE 2
Definition at line 18 of file router.c.
K_LOGIN
#define K_LOGIN 0
Definition at line 16 of file router.c.
K_MKDIR
#define K_MKDIR 3
Definition at line 19 of file router.c.
K_MKPATH
#define K_MKPATH 4
Definition at line 20 of file router.c.
K_MV
#define K_MV 5
Definition at line 21 of file router.c.
K_PING
#define K_PING 17
Definition at line 33 of file router.c.
K_PONG
#define K_PONG 18
Definition at line 34 of file router.c.
K_PREPADD
#define K_PREPADD 6
Definition at line 22 of file router.c.
K_PREPDEL
#define K_PREPDEL 7
Definition at line 23 of file router.c.
K_RM
#define K_RM 8
Definition at line 24 of file router.c.
K_RMDIR
#define K_RMDIR 9
Definition at line 25 of file router.c.
K_SELECT
#define K_SELECT 10
Definition at line 26 of file router.c.
K_SPACE
#define K_SPACE 19
Definition at line 35 of file router.c.
K_STATE
#define K_STATE 20
Definition at line 36 of file router.c.
K_STATFS
#define K_STATFS 21
Definition at line 37 of file router.c.
K_STATS
#define K_STATS 11
Definition at line 27 of file router.c.
K_STATUS
#define K_STATUS 22
Definition at line 38 of file router.c.
K_TRUNC
#define K_TRUNC 23
Definition at line 39 of file router.c.
K_TRY
#define K_TRY 24
Definition at line 40 of file router.c.
K_UPDATE
#define K_UPDATE 25
Definition at line 41 of file router.c.
K_USAGE
#define K_USAGE 26
Definition at line 42 of file router.c.
K_XAUTH
#define K_XAUTH 27
Definition at line 43 of file router.c.
RF_FWD
#define RF_FWD (XRDCMS_RF_FORWARD | XRDCMS_RF_REPLIABLE | XRDCMS_RF_DELAYABLE)
Definition at line 45 of file router.c.
RF_RD
#define RF_RD (XRDCMS_RF_REPLIABLE | XRDCMS_RF_DELAYABLE)
Definition at line 46 of file router.c.
Function Documentation
brix_cms_route_lookup()
const brix_cms_route_t * brix_cms_route_lookup (brix_cms_role_t role, unsigned char code)
Definition at line 116 of file router.c.
References code, manager_routes, node_routes, route_scan(), and XRDCMS_ROLE_NODE.
Referenced by cms_srv_frame_unknown(), ngx_brix_cms_process_frame(), test_manager_forwardable_mkdir(), test_manager_locate_not_forwarded(), test_manager_ping_sync_noargs(), test_node_executes_forwarded_mkdir_without_reforward(), test_node_rejects_node_status_opcode(), test_unknown_opcode_rejected(), and test_update_routed_both_roles().
route_scan()
static const brix_cms_route_t * route_scan (const brix_cms_route_t * tbl, size_t n, unsigned char code) static
Definition at line 104 of file router.c.
References code.
Referenced by brix_cms_route_lookup().
Variable Documentation
manager_routes
const brix_cms_route_t manager_routes[] static
Definition at line 49 of file router.c.
Referenced by brix_cms_route_lookup().
node_routes
const brix_cms_route_t node_routes[] static
Initial value:
= {
    {  1 ,   "chmod",   ( 0x04u   |  0x08u  )  },
    {  2 ,  "locate",  ( 0x04u   |  0x08u  )  },
    {  3 ,   "mkdir",   ( 0x04u   |  0x08u  )  },
    {  4 ,  "mkpath",  ( 0x04u   |  0x08u  )  },
    {  5 ,      "mv",      ( 0x04u   |  0x08u  )  },
    {  6 , "prepadd", 0x01u   |  ( 0x04u   |  0x08u  )  },
    {  7 , "prepdel", 0x01u   |  ( 0x04u   |  0x08u  )  },
    {  8 ,      "rm",      ( 0x04u   |  0x08u  )  },
    {  9 ,   "rmdir",   ( 0x04u   |  0x08u  )  },
    {  10 ,  "select",  ( 0x04u   |  0x08u  )  },
    {  21 ,  "statfs",  ( 0x04u   |  0x08u  )  },
    {  11 ,   "stats",   ( 0x04u   |  0x08u  )  },
    {  23 ,   "trunc",   ( 0x04u   |  0x08u  )  },
    {  20 ,   "state",   0x01u   },
    {  17 ,    "ping",    0x01u   |  0x10u   },
    {  13 ,    "disc",    0x01u   |  0x10u   },
    {  25 ,  "update",  0x01u   |  0x10u   |  0x04u   },
}
Definition at line 83 of file router.c.
Referenced by brix_cms_route_lookup().