nginx-xrootd: src/net/cms/rrdata.c File Reference
rrdata.c File Reference
#include "rrdata.h"
#include <string.h>
#include <stdio.h>
Macros
#define K_CHMOD 1
#define K_LOCATE 2
#define K_MKDIR 3
#define K_MKPATH 4
#define K_MV 5
#define K_PREPADD 6
#define K_PREPDEL 7
#define K_RM 8
#define K_RMDIR 9
#define K_SELECT 10
#define K_STATFS 21
#define K_TRUNC 23
#define CMS_PT_INT 0xa0 /* tagged 32-bit scalar */
Functions
static int read_str (const unsigned char **p, const unsigned char *end, const unsigned char **out, size_t *out_len)
static int read_opt_str (const unsigned char **p, const unsigned char *end, const unsigned char **out, size_t *out_len)
static int read_int (const unsigned char **p, const unsigned char *end, uint32_t *v)
int brix_cms_rrdata_parse (unsigned char code, const unsigned char *payload, size_t len, brix_cms_rrdata_t *out)
static int enc_str (unsigned char **p, unsigned char *end, const char *s)
int brix_cms_rrdata_encode (unsigned char code, const char *ident, const char *path, const char *path2, const char *mode, const char *opaque, unsigned char *buf, size_t buflen)
int brix_cms_statfs_encode (uint32_t w_num, uint32_t w_free, uint32_t w_util, uint32_t s_num, uint32_t s_free, uint32_t s_util, unsigned char *buf, size_t buflen)
Macro Definition Documentation
CMS_PT_INT
#define CMS_PT_INT 0xa0 /* tagged 32-bit scalar */
Definition at line 29 of file rrdata.c.
K_CHMOD
#define K_CHMOD 1
Definition at line 16 of file rrdata.c.
K_LOCATE
#define K_LOCATE 2
Definition at line 17 of file rrdata.c.
K_MKDIR
#define K_MKDIR 3
Definition at line 18 of file rrdata.c.
K_MKPATH
#define K_MKPATH 4
Definition at line 19 of file rrdata.c.
K_MV
#define K_MV 5
Definition at line 20 of file rrdata.c.
K_PREPADD
#define K_PREPADD 6
Definition at line 21 of file rrdata.c.
K_PREPDEL
#define K_PREPDEL 7
Definition at line 22 of file rrdata.c.
K_RM
#define K_RM 8
Definition at line 23 of file rrdata.c.
K_RMDIR
#define K_RMDIR 9
Definition at line 24 of file rrdata.c.
K_SELECT
#define K_SELECT 10
Definition at line 25 of file rrdata.c.
K_STATFS
#define K_STATFS 21
Definition at line 26 of file rrdata.c.
K_TRUNC
#define K_TRUNC 23
Definition at line 27 of file rrdata.c.
Function Documentation
brix_cms_rrdata_encode()
int brix_cms_rrdata_encode (unsigned char code, const char * ident, const char * path, const char * path2, const char * mode, const char * opaque, unsigned char * buf, size_t buflen)
Definition at line 194 of file rrdata.c.
References enc_str(), K_CHMOD, K_MKDIR, K_MKPATH, K_MV, K_RM, K_RMDIR, K_STATFS, K_TRUNC, and mode.
Referenced by brix_cms_forward_to_node(), test_encode_overflow_rejected(), test_encode_roundtrip_mkdir(), test_encode_roundtrip_mv_with_opaque(), and test_encode_roundtrip_rm().
brix_cms_rrdata_parse()
int brix_cms_rrdata_parse (unsigned char code, const unsigned char * payload, size_t len, brix_cms_rrdata_t * out)
Definition at line 93 of file rrdata.c.
References brix_cms_rrdata_t::avoid, brix_cms_rrdata_t::avoid_len, brix_cms_rrdata_t::has_opts, brix_cms_rrdata_t::ident, brix_cms_rrdata_t::ident_len, K_CHMOD, K_LOCATE, K_MKDIR, K_MKPATH, K_MV, K_PREPADD, K_PREPDEL, K_RM, K_RMDIR, K_SELECT, K_STATFS, K_TRUNC, brix_cms_rrdata_t::mode, brix_cms_rrdata_t::mode_len, brix_cms_rrdata_t::notify, brix_cms_rrdata_t::notify_len, brix_cms_rrdata_t::opaque, brix_cms_rrdata_t::opaque2, brix_cms_rrdata_t::opaque2_len, brix_cms_rrdata_t::opaque_len, brix_cms_rrdata_t::opts, brix_cms_rrdata_t::path, brix_cms_rrdata_t::path2, brix_cms_rrdata_t::path2_len, brix_cms_rrdata_t::path_len, brix_cms_rrdata_t::prty, brix_cms_rrdata_t::prty_len, read_int(), read_opt_str(), read_str(), brix_cms_rrdata_t::reqid, and brix_cms_rrdata_t::reqid_len.
Referenced by cms_node_exec_forward(), cms_srv_process_frame(), test_chmod_with_opaque(), test_encode_roundtrip_mkdir(), test_encode_roundtrip_mv_with_opaque(), test_encode_roundtrip_rm(), test_mkdir(), test_mv(), test_prepadd(), test_prepdel(), test_rm(), test_select_with_opts(), test_truncated_string_rejected(), and test_unknown_opcode_rejected().
brix_cms_statfs_encode()
int brix_cms_statfs_encode (uint32_t w_num, uint32_t w_free, uint32_t w_util, uint32_t s_num, uint32_t s_free, uint32_t s_util, unsigned char * buf, size_t buflen)
Definition at line 238 of file rrdata.c.
Referenced by cms_srv_process_frame(), test_statfs_encode(), and test_statfs_encode_overflow().
enc_str()
static int enc_str (unsigned char ** p, unsigned char * end, const char * s) static
Definition at line 169 of file rrdata.c.
References s.
Referenced by brix_cms_rrdata_encode().
read_int()
static int read_int (const unsigned char ** p, const unsigned char * end, uint32_t * v) static
Definition at line 81 of file rrdata.c.
References CMS_PT_INT.
Referenced by brix_cms_rrdata_parse().
read_opt_str()
static int read_opt_str (const unsigned char ** p, const unsigned char * end, const unsigned char ** out, size_t * out_len) static
Definition at line 68 of file rrdata.c.
References read_str().
Referenced by brix_cms_rrdata_parse().
read_str()
static int read_str (const unsigned char ** p, const unsigned char * end, const unsigned char ** out, size_t * out_len) static
Definition at line 38 of file rrdata.c.
Referenced by brix_cms_rrdata_parse(), and read_opt_str().