nginx-xrootd: src/net/cms/rrdata_unittest.c File Reference
rrdata_unittest.c File Reference
#include "rrdata.h"
#include <stdio.h>
#include <string.h>
Macros
#define K_CHMOD 1
#define K_MKDIR 3
#define K_MV 5
#define K_PREPADD 6
#define K_PREPDEL 7
#define K_RM 8
#define K_SELECT 10
#define CHECK(cond)
Functions
static unsigned char * put_str (unsigned char *p, const char *s)
static unsigned char * put_int (unsigned char *p, uint32_t v)
static int span_eq (const unsigned char *p, size_t len, const char *s)
static void test_mkdir (void)
static void test_chmod_with_opaque (void)
static void test_mv (void)
static void test_rm (void)
static void test_select_with_opts (void)
static void test_prepadd (void)
static void test_prepdel (void)
static void test_truncated_string_rejected (void)
static void test_unknown_opcode_rejected (void)
static void test_encode_roundtrip_mkdir (void)
static void test_encode_roundtrip_mv_with_opaque (void)
static void test_encode_roundtrip_rm (void)
static void test_encode_overflow_rejected (void)
static void test_statfs_encode (void)
static void test_statfs_encode_overflow (void)
int main (void)
Variables
static int g_fail
Macro Definition Documentation
CHECK
#define CHECK (cond)
Value:
    do { \
    if (!(cond)) { printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
                   g_fail++; } \
} while (0)
Definition at line 25 of file rrdata_unittest.c.
K_CHMOD
#define K_CHMOD 1
Definition at line 16 of file rrdata_unittest.c.
K_MKDIR
#define K_MKDIR 3
Definition at line 17 of file rrdata_unittest.c.
K_MV
#define K_MV 5
Definition at line 18 of file rrdata_unittest.c.
K_PREPADD
#define K_PREPADD 6
Definition at line 19 of file rrdata_unittest.c.
K_PREPDEL
#define K_PREPDEL 7
Definition at line 20 of file rrdata_unittest.c.
K_RM
#define K_RM 8
Definition at line 21 of file rrdata_unittest.c.
K_SELECT
#define K_SELECT 10
Definition at line 22 of file rrdata_unittest.c.
Function Documentation
main()
int main (void)
Definition at line 263 of file rrdata_unittest.c.
References g_fail, test_chmod_with_opaque(), test_encode_overflow_rejected(), test_encode_roundtrip_mkdir(), test_encode_roundtrip_mv_with_opaque(), test_encode_roundtrip_rm(), test_mkdir(), test_mv(), test_prepadd(), test_prepdel(), test_rm(), test_select_with_opts(), test_statfs_encode(), test_statfs_encode_overflow(), test_truncated_string_rejected(), and test_unknown_opcode_rejected().
put_int()
static unsigned char * put_int (unsigned char * p, uint32_t v) static
Definition at line 47 of file rrdata_unittest.c.
Referenced by test_select_with_opts().
put_str()
static unsigned char * put_str (unsigned char * p, const char * s) static
Definition at line 33 of file rrdata_unittest.c.
References s.
Referenced by test_chmod_with_opaque(), test_mkdir(), test_mv(), test_prepadd(), test_prepdel(), test_rm(), and test_select_with_opts().
span_eq()
static int span_eq (const unsigned char * p, size_t len, const char * s) static
Definition at line 58 of file rrdata_unittest.c.
References s.
Referenced by test_chmod_with_opaque(), test_encode_roundtrip_mkdir(), test_encode_roundtrip_mv_with_opaque(), test_encode_roundtrip_rm(), test_mkdir(), test_mv(), test_prepadd(), test_prepdel(), test_rm(), and test_select_with_opts().
test_chmod_with_opaque()
static void test_chmod_with_opaque (void) static
Definition at line 84 of file rrdata_unittest.c.
References brix_cms_rrdata_parse(), CHECK, K_CHMOD, brix_cms_rrdata_t::opaque, brix_cms_rrdata_t::opaque_len, brix_cms_rrdata_t::path, brix_cms_rrdata_t::path_len, put_str(), and span_eq().
Referenced by main().
test_encode_overflow_rejected()
static void test_encode_overflow_rejected (void) static
Definition at line 235 of file rrdata_unittest.c.
References brix_cms_rrdata_encode(), CHECK, and K_MKDIR.
Referenced by main().
test_encode_roundtrip_mkdir()
static void test_encode_roundtrip_mkdir (void) static
Definition at line 195 of file rrdata_unittest.c.
References brix_cms_rrdata_encode(), brix_cms_rrdata_parse(), CHECK, brix_cms_rrdata_t::ident, brix_cms_rrdata_t::ident_len, K_MKDIR, brix_cms_rrdata_t::mode, brix_cms_rrdata_t::mode_len, brix_cms_rrdata_t::path, brix_cms_rrdata_t::path_len, and span_eq().
Referenced by main().
test_encode_roundtrip_mv_with_opaque()
static void test_encode_roundtrip_mv_with_opaque (void) static
Definition at line 209 of file rrdata_unittest.c.
References brix_cms_rrdata_encode(), brix_cms_rrdata_parse(), CHECK, K_MV, brix_cms_rrdata_t::opaque, brix_cms_rrdata_t::opaque_len, brix_cms_rrdata_t::path, brix_cms_rrdata_t::path2, brix_cms_rrdata_t::path2_len, brix_cms_rrdata_t::path_len, and span_eq().
Referenced by main().
test_encode_roundtrip_rm()
static void test_encode_roundtrip_rm (void) static
Definition at line 223 of file rrdata_unittest.c.
References brix_cms_rrdata_encode(), brix_cms_rrdata_parse(), CHECK, K_RM, brix_cms_rrdata_t::path, brix_cms_rrdata_t::path_len, and span_eq().
Referenced by main().
test_mkdir()
static void test_mkdir (void) static
Definition at line 65 of file rrdata_unittest.c.
References brix_cms_rrdata_parse(), CHECK, brix_cms_rrdata_t::ident, brix_cms_rrdata_t::ident_len, K_MKDIR, brix_cms_rrdata_t::mode, brix_cms_rrdata_t::mode_len, brix_cms_rrdata_t::opaque, brix_cms_rrdata_t::path, brix_cms_rrdata_t::path_len, put_str(), and span_eq().
Referenced by main().
test_mv()
static void test_mv (void) static
Definition at line 99 of file rrdata_unittest.c.
References brix_cms_rrdata_parse(), CHECK, K_MV, brix_cms_rrdata_t::path, brix_cms_rrdata_t::path2, brix_cms_rrdata_t::path2_len, brix_cms_rrdata_t::path_len, put_str(), and span_eq().
Referenced by main().
test_prepadd()
static void test_prepadd (void) static
Definition at line 143 of file rrdata_unittest.c.
References brix_cms_rrdata_parse(), CHECK, K_PREPADD, brix_cms_rrdata_t::path, brix_cms_rrdata_t::path_len, put_str(), brix_cms_rrdata_t::reqid, brix_cms_rrdata_t::reqid_len, and span_eq().
Referenced by main().
test_prepdel()
static void test_prepdel (void) static
Definition at line 161 of file rrdata_unittest.c.
References brix_cms_rrdata_parse(), CHECK, K_PREPDEL, put_str(), brix_cms_rrdata_t::reqid, brix_cms_rrdata_t::reqid_len, and span_eq().
Referenced by main().
test_rm()
static void test_rm (void) static
Definition at line 114 of file rrdata_unittest.c.
References brix_cms_rrdata_parse(), CHECK, K_RM, brix_cms_rrdata_t::path, brix_cms_rrdata_t::path_len, put_str(), and span_eq().
Referenced by main().
test_select_with_opts()
static void test_select_with_opts (void) static
Definition at line 127 of file rrdata_unittest.c.
References brix_cms_rrdata_parse(), CHECK, brix_cms_rrdata_t::has_opts, K_SELECT, brix_cms_rrdata_t::opts, brix_cms_rrdata_t::path, brix_cms_rrdata_t::path_len, put_int(), put_str(), and span_eq().
Referenced by main().
test_statfs_encode()
static void test_statfs_encode (void) static
Definition at line 244 of file rrdata_unittest.c.
References brix_cms_statfs_encode(), and CHECK.
Referenced by main().
test_statfs_encode_overflow()
static void test_statfs_encode_overflow (void) static
Definition at line 255 of file rrdata_unittest.c.
References brix_cms_statfs_encode(), and CHECK.
Referenced by main().
test_truncated_string_rejected()
static void test_truncated_string_rejected (void) static
Definition at line 174 of file rrdata_unittest.c.
References brix_cms_rrdata_parse(), CHECK, and K_RM.
Referenced by main().
test_unknown_opcode_rejected()
static void test_unknown_opcode_rejected (void) static
Definition at line 186 of file rrdata_unittest.c.
References brix_cms_rrdata_parse(), and CHECK.
Referenced by main().
Variable Documentation
g_fail
int g_fail static
Definition at line 24 of file rrdata_unittest.c.
Referenced by main().