nginx-xrootd: src/net/cms/rrdata.h File Reference
rrdata.h File Reference
#include <stddef.h>
#include <stdint.h>
Data Structures
struct brix_cms_rrdata_t
struct brix_cms_fwd_fields_t
struct brix_cms_statfs_fields_t
Functions
int brix_cms_rrdata_parse (unsigned char code, const unsigned char *payload, size_t len, brix_cms_rrdata_t *out)
int brix_cms_rrdata_encode (unsigned char code, const brix_cms_fwd_fields_t *fields, unsigned char *buf, size_t buflen)
int brix_cms_statfs_encode (const brix_cms_statfs_fields_t *space, unsigned char *buf, size_t buflen)
Function Documentation
brix_cms_rrdata_encode()
int brix_cms_rrdata_encode (unsigned char code, const brix_cms_fwd_fields_t * fields, unsigned char * buf, size_t buflen)
Definition at line 260 of file rrdata.c.
References code, enc_seq(), brix_cms_fwd_fields_t::ident, K_CHMOD, K_MKDIR, K_MKPATH, K_MV, K_RM, K_RMDIR, K_STATFS, K_TRUNC, brix_cms_fwd_fields_t::mode, brix_cms_fwd_fields_t::opaque, brix_cms_fwd_fields_t::path, and brix_cms_fwd_fields_t::path2.
Referenced by brix_cms_forward_to_node(), test_encode_overflow_rejected(), test_encode_roundtrip_mkdir(), test_encode_roundtrip_mv_with_opaque(), and test_encode_roundtrip_rm().
brix_cms_rrdata_parse()
int brix_cms_rrdata_parse (unsigned char code, const unsigned char * payload, size_t len, brix_cms_rrdata_t * out)
Definition at line 169 of file rrdata.c.
References code, K_CHMOD, K_LOCATE, K_MKDIR, K_MKPATH, K_MV, K_PREPADD, K_PREPDEL, K_RM, K_RMDIR, K_SELECT, K_STATFS, K_TRUNC, parse_fwd_a(), parse_fwd_b(), parse_fwd_c(), parse_loc(), parse_pad(), and parse_pdl().
Referenced by cms_node_exec_forward(), cms_node_exec_prepare(), cms_srv_frame_statfs(), test_chmod_with_opaque(), test_encode_roundtrip_mkdir(), test_encode_roundtrip_mv_with_opaque(), test_encode_roundtrip_rm(), test_mkdir(), test_mv(), test_prepadd(), test_prepdel(), test_rm(), test_select_with_opts(), test_truncated_string_rejected(), and test_unknown_opcode_rejected().
brix_cms_statfs_encode()
int brix_cms_statfs_encode (const brix_cms_statfs_fields_t * space, unsigned char * buf, size_t buflen)
Definition at line 305 of file rrdata.c.
References brix_cms_statfs_fields_t::s_free, brix_cms_statfs_fields_t::s_num, brix_cms_statfs_fields_t::s_util, brix_cms_statfs_fields_t::w_free, brix_cms_statfs_fields_t::w_num, and brix_cms_statfs_fields_t::w_util.
Referenced by cms_srv_frame_statfs(), test_statfs_encode(), and test_statfs_encode_overflow().