nginx-xrootd: src/core/config/runtime_server.c File Reference
runtime_server.c File Reference
#include "config.h"
#include "root_prepare.h"
#include "credential_block.h"
#include "core/compat/staged_file.h"
#include "core/compat/tmp_path.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "fs/path/path.h"
#include "fs/tier/tier.h"
#include "fs/cache/cache_internal.h"
#include "core/config/export_guard.h"
Functions
char * brix_conf_set_store_slot (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
void brix_storage_backend_posix_root (ngx_http_brix_shared_conf_t *common)
int brix_storage_backend_is_remote (const ngx_http_brix_shared_conf_t *common)
ngx_int_t brix_tier_register_stores (ngx_conf_t *cf, ngx_http_brix_shared_conf_t *common)
ngx_int_t brix_config_prepare_server (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
Function Documentation
brix_conf_set_store_slot()
char * brix_conf_set_store_slot (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 20 of file runtime_server.c.
brix_config_prepare_server()
ngx_int_t brix_config_prepare_server (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf)
Definition at line 233 of file runtime_server.c.
References ngx_stream_brix_srv_conf_t::access_log, ngx_stream_brix_srv_conf_t::access_log_file, brix_export_root_opts_t::allow_write, ngx_http_brix_shared_conf_t::allow_write, brix_proxy_conf_t::audit_log, brix_proxy_conf_t::audit_log_file, brix_proxy_conf_t::auth, brix_vfs_backend_cred_t::bearer, brix_assert_dir_outside_export(), brix_cache_state_root(), brix_credential_bearer(), brix_credential_lookup(), BRIX_PATH_DIRECTORY, brix_prepare_export_root(), BRIX_PROXY_AUTH_GSI, brix_shared_apply_read_only(), brix_stage_dir_register(), brix_storage_backend_is_remote(), brix_storage_backend_posix_root(), brix_tier_register_stores(), brix_tmp_reap_register(), brix_validate_path(), brix_vfs_backend_config(), brix_vfs_backend_config_str(), brix_vfs_backend_set_credential(), brix_credential_t::ca_dir, brix_vfs_backend_cred_t::ca_dir, ngx_stream_brix_srv_conf_t::cache, ngx_stream_brix_srv_conf_t::cache_eviction_threshold, ngx_stream_brix_srv_conf_t::cache_lock_timeout, ngx_stream_brix_srv_conf_t::cache_origin, ngx_stream_brix_srv_conf_t::cache_origin_bearer, ngx_stream_brix_srv_conf_t::cache_origin_ca_dir, ngx_stream_brix_srv_conf_t::cache_origin_family, ngx_stream_brix_srv_conf_t::cache_origin_tls, ngx_stream_brix_srv_conf_t::cache_origin_x509_proxy, ngx_stream_brix_srv_conf_t::cache_root, ngx_stream_brix_srv_conf_t::cache_state_root, ngx_stream_brix_srv_conf_t::cache_wt_stage_backend, ngx_stream_brix_srv_conf_t::cache_wt_stage_block_size, ngx_stream_brix_srv_conf_t::cache_wt_stage_high_watermark, ngx_stream_brix_srv_conf_t::cache_wt_stage_low_watermark, ngx_stream_brix_srv_conf_t::cache_wt_stage_root, brix_export_root_opts_t::canon_size, ngx_stream_brix_srv_conf_t::caps, ngx_stream_brix_srv_conf_t::common, brix_wt_conf_t::credential, brix_export_root_opts_t::directive_name, brix_wt_conf_t::enable, brix_proxy_conf_t::enable, brix_cache_reaper_conf_t::high_watermark, brix_cache_reaper_conf_t::low_watermark, ngx_stream_brix_srv_conf_t::manager_map, ngx_stream_brix_srv_conf_t::manager_mode, ngx_memcpy, ngx_pcalloc(), ngx_pnalloc(), ngx_http_brix_shared_conf_t::pblock_block_size, ngx_stream_brix_srv_conf_t::proxy, ngx_stream_brix_srv_conf_t::reaper, brix_export_root_opts_t::required, ngx_http_brix_shared_conf_t::root, ngx_http_brix_shared_conf_t::root_canon, brix_credential_t::s3_access_key, brix_vfs_backend_cred_t::s3_access_key, brix_credential_t::s3_region, brix_vfs_backend_cred_t::s3_region, brix_credential_t::s3_secret_key, brix_vfs_backend_cred_t::s3_secret_key, brix_credential_t::sss_keytab, brix_vfs_backend_cred_t::sss_keytab, ngx_http_brix_shared_conf_t::storage_backend, ngx_http_brix_shared_conf_t::storage_credential, brix_node_caps_conf_t::supervisor, ngx_stream_brix_srv_conf_t::tpc_delegate, ngx_stream_brix_srv_conf_t::upload_stage_dir, ngx_stream_brix_srv_conf_t::upload_stage_dir_canon, brix_proxy_conf_t::upstream_tls, ngx_stream_brix_srv_conf_t::upstream_tls, brix_proxy_conf_t::upstream_tls_ca, ngx_stream_brix_srv_conf_t::upstream_tls_ca, ngx_stream_brix_srv_conf_t::wt, brix_credential_t::x509_proxy, and brix_vfs_backend_cred_t::x509_proxy.
Referenced by ngx_stream_brix_postconfiguration().
brix_storage_backend_is_remote()
int brix_storage_backend_is_remote (const ngx_http_brix_shared_conf_t * common)
Definition at line 112 of file runtime_server.c.
References ngx_http_brix_shared_conf_t::storage_backend.
Referenced by brix_config_prepare_server(), ngx_http_brix_webdav_merge_loc_conf(), and ngx_http_s3_merge_loc_conf().
brix_storage_backend_posix_root()
void brix_storage_backend_posix_root (ngx_http_brix_shared_conf_t * common)
Definition at line 60 of file runtime_server.c.
References brix_mkdir_recursive(), ngx_http_brix_shared_conf_t::root, and ngx_http_brix_shared_conf_t::storage_backend.
Referenced by brix_config_prepare_server(), ngx_http_brix_cvmfs_merge_loc_conf(), ngx_http_brix_webdav_merge_loc_conf(), and ngx_http_s3_merge_loc_conf().
brix_tier_register_stores()
ngx_int_t brix_tier_register_stores (ngx_conf_t * cf, ngx_http_brix_shared_conf_t * common)
Definition at line 137 of file runtime_server.c.
References brix_cache_policy_t::batch_cinfo, BRIX_CACHE_VERIFY_CVMFS_CAS, BRIX_CACHE_VERIFY_OFF, BRIX_TIER_CACHE, brix_tier_parse_store(), BRIX_TIER_STAGE, brix_vfs_backend_config_cache_store(), brix_vfs_backend_config_stage_store(), BRIX_WT_MODE_ASYNC, BRIX_WT_MODE_SYNC, ngx_http_brix_shared_conf_t::cache_batch_cinfo, ngx_http_brix_shared_conf_t::cache_evict_at, ngx_http_brix_shared_conf_t::cache_evict_to, ngx_http_brix_shared_conf_t::cache_index_cache, ngx_http_brix_shared_conf_t::cache_manifest_ttl, ngx_http_brix_shared_conf_t::cache_max_object, ngx_http_brix_shared_conf_t::cache_meta_mode, ngx_http_brix_shared_conf_t::cache_quarantine_dir, ngx_http_brix_shared_conf_t::cache_slice_size, ngx_http_brix_shared_conf_t::cache_store, ngx_http_brix_shared_conf_t::cache_store_args, ngx_http_brix_shared_conf_t::cache_verify_mode, brix_cache_policy_t::cvmfs_manifest_ttl, brix_tier_cfg_t::driver, brix_cache_policy_t::enabled, brix_stage_policy_t::enabled, brix_cache_policy_t::evict_at, brix_cache_policy_t::evict_to, brix_stage_policy_t::flush_mode, brix_cache_policy_t::l1_entries, brix_cache_policy_t::max_file_size, brix_cache_policy_t::meta_mode, brix_cache_policy_t::quarantine_dir, ngx_http_brix_shared_conf_t::root_canon, brix_cache_policy_t::slice_size, ngx_http_brix_shared_conf_t::stage_enable, ngx_http_brix_shared_conf_t::stage_flush_async, ngx_http_brix_shared_conf_t::stage_store, ngx_http_brix_shared_conf_t::stage_store_args, ngx_http_brix_shared_conf_t::storage_backend, and brix_cache_policy_t::verify.
Referenced by brix_config_prepare_server(), ngx_http_brix_cvmfs_merge_loc_conf(), ngx_http_brix_webdav_merge_loc_conf(), and ngx_http_s3_merge_loc_conf().