nginx-xrootd: src/core/config/runtime_server_backend_internal.h File Reference
runtime_server_backend_internal.h File Reference
Functions
void brix_tier_default_stage_store (ngx_conf_t *cf, ngx_http_brix_shared_conf_t *common)
void brix_tier_warn_private_tmp (ngx_conf_t *cf, const ngx_http_brix_shared_conf_t *common)
ngx_int_t brix_tier_register_cache_store (ngx_conf_t *cf, ngx_http_brix_shared_conf_t *common)
ngx_int_t brix_server_setup_tls (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *xcf)
Function Documentation
brix_server_setup_tls()
ngx_int_t brix_server_setup_tls (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * xcf)
Definition at line 59 of file runtime_server_tls.c.
References ngx_pcalloc().
Referenced by brix_config_prepare_server().
brix_tier_default_stage_store()
void brix_tier_default_stage_store (ngx_conf_t * cf, ngx_http_brix_shared_conf_t * common)
Definition at line 168 of file runtime_server_backend_stage.c.
References access(), brix_mkdir_recursive(), brix_shared_worker_dir_ids(), BRIX_TIER_DEFAULT_STAGE_BASE, brix_tier_default_stage_dir(), ngx_pnalloc(), PATH_MAX, ngx_http_brix_shared_conf_t::stage_enable, ngx_http_brix_shared_conf_t::stage_store, stat(), and ngx_http_brix_shared_conf_t::storage_backend.
Referenced by brix_tier_register_stores().
brix_tier_register_cache_store()
ngx_int_t brix_tier_register_cache_store (ngx_conf_t * cf, ngx_http_brix_shared_conf_t * common)
Definition at line 225 of file runtime_server_backend_cache.c.
References BRIX_CACHE_VERIFY_CVMFS_CAS, BRIX_TIER_CACHE, brix_tier_fill_cache_policy(), brix_tier_load_master_key(), brix_tier_parse_store(), brix_tier_register_cache_peers(), brix_vfs_backend_config_cache_cold_store(), brix_vfs_backend_config_cache_store(), ngx_http_brix_shared_conf_t::cache_cold_store, ngx_http_brix_shared_conf_t::cache_cold_store_args, ngx_http_brix_shared_conf_t::cache_cvmfs_master_key, ngx_http_brix_shared_conf_t::cache_peers, ngx_http_brix_shared_conf_t::cache_store, ngx_http_brix_shared_conf_t::cache_store_args, brix_tier_cfg_t::driver, ngx_http_brix_shared_conf_t::root_canon, and brix_cache_policy_t::verify.
Referenced by brix_tier_register_stores().
brix_tier_warn_private_tmp()
void brix_tier_warn_private_tmp (ngx_conf_t * cf, const ngx_http_brix_shared_conf_t * common)
Definition at line 63 of file runtime_server_backend_stage.c.
References brix_tmp_is_systemd_private(), ngx_http_brix_shared_conf_t::cache_store, and ngx_http_brix_shared_conf_t::stage_store.
Referenced by brix_tier_register_stores().