nginx-xrootd: src/core/config/runtime_server_backend.c File Reference
runtime_server_backend.c File Reference
#include "config.h"
#include "root_prepare.h"
#include "credential_block.h"
#include "core/compat/staged_file.h"
#include "core/compat/tmp_path.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "fs/path/path.h"
#include "fs/tier/tier.h"
#include "fs/cache/cache_internal.h"
#include "core/config/export_guard.h"
#include <stdlib.h>
#include <string.h>
Macros
#define BRIX_TIER_DEFAULT_STAGE_BASE "/tmp/staging"
Functions
static void brix_pblock_write_opts_sidecar (const char *root, const char *tail)
char * brix_conf_set_store_slot (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
void brix_storage_backend_posix_root (ngx_http_brix_shared_conf_t *common)
int brix_storage_backend_is_remote (const ngx_http_brix_shared_conf_t *common)
static int brix_storage_backend_is_whole_object (const ngx_http_brix_shared_conf_t *common)
static int brix_tmp_is_systemd_private (void)
static void brix_tier_warn_private_tmp (ngx_conf_t *cf, const ngx_http_brix_shared_conf_t *common)
static void brix_tier_default_stage_dir (const ngx_str_t *backend, char *dir, size_t cap)
static void brix_tier_default_stage_store (ngx_conf_t *cf, ngx_http_brix_shared_conf_t *common)
static ngx_int_t brix_tier_load_master_key (ngx_conf_t *cf, const ngx_str_t *path, brix_cache_policy_t *pol)
static ngx_int_t brix_tier_register_cache_peers (ngx_conf_t *cf, ngx_http_brix_shared_conf_t *common)
static ngx_int_t brix_tier_register_cache_store (ngx_conf_t *cf, ngx_http_brix_shared_conf_t *common)
ngx_int_t brix_tier_register_stores (ngx_conf_t *cf, ngx_http_brix_shared_conf_t *common)
Macro Definition Documentation
BRIX_TIER_DEFAULT_STAGE_BASE
#define BRIX_TIER_DEFAULT_STAGE_BASE "/tmp/staging"
Definition at line 204 of file runtime_server_backend.c.
Function Documentation
brix_conf_set_store_slot()
char * brix_conf_set_store_slot (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 47 of file runtime_server_backend.c.
brix_pblock_write_opts_sidecar()
static void brix_pblock_write_opts_sidecar (const char * root, const char * tail) static
Definition at line 28 of file runtime_server_backend.c.
Referenced by brix_storage_backend_posix_root().
brix_storage_backend_is_remote()
int brix_storage_backend_is_remote (const ngx_http_brix_shared_conf_t * common)
Definition at line 162 of file runtime_server_backend.c.
References ngx_http_brix_shared_conf_t::storage_backend.
Referenced by brix_server_guard_remote_authz(), brix_server_setup_export(), s3_merge_export(), and webdav_prepare_export_root().
brix_storage_backend_is_whole_object()
static int brix_storage_backend_is_whole_object (const ngx_http_brix_shared_conf_t * common) static
Definition at line 187 of file runtime_server_backend.c.
References ngx_http_brix_shared_conf_t::storage_backend.
Referenced by brix_tier_register_stores().
brix_storage_backend_posix_root()
void brix_storage_backend_posix_root (ngx_http_brix_shared_conf_t * common)
Definition at line 87 of file runtime_server_backend.c.
References brix_mkdir_recursive(), brix_pblock_write_opts_sidecar(), ngx_http_brix_shared_conf_t::root, and ngx_http_brix_shared_conf_t::storage_backend.
Referenced by brix_server_setup_export(), cvmfs_merge_cache(), s3_merge_export(), and webdav_prepare_export_root().
brix_tier_default_stage_dir()
static void brix_tier_default_stage_dir (const ngx_str_t * backend, char * dir, size_t cap) static
Definition at line 289 of file runtime_server_backend.c.
References BRIX_TIER_DEFAULT_STAGE_BASE, and c.
Referenced by brix_tier_default_stage_store().
brix_tier_default_stage_store()
static void brix_tier_default_stage_store (ngx_conf_t * cf, ngx_http_brix_shared_conf_t * common) static
Definition at line 338 of file runtime_server_backend.c.
References brix_mkdir_recursive(), brix_shared_worker_dir_ids(), BRIX_TIER_DEFAULT_STAGE_BASE, brix_tier_default_stage_dir(), ngx_pnalloc(), PATH_MAX, ngx_http_brix_shared_conf_t::stage_enable, ngx_http_brix_shared_conf_t::stage_store, stat(), and ngx_http_brix_shared_conf_t::storage_backend.
Referenced by brix_tier_register_stores().
brix_tier_load_master_key()
static ngx_int_t brix_tier_load_master_key (ngx_conf_t * cf, const ngx_str_t * path, brix_cache_policy_t * pol) static
Definition at line 418 of file runtime_server_backend.c.
References close(), brix_cache_policy_t::cvmfs_master_pub, brix_cache_policy_t::cvmfs_master_pub_len, open(), and read().
Referenced by brix_tier_register_cache_store().
brix_tier_register_cache_peers()
static ngx_int_t brix_tier_register_cache_peers (ngx_conf_t * cf, ngx_http_brix_shared_conf_t * common) static
Definition at line 481 of file runtime_server_backend.c.
References brix_vfs_backend_config_cache_peers(), ngx_http_brix_shared_conf_t::cache_peers, ngx_memcpy, port, ngx_http_brix_shared_conf_t::root_canon, and tok.
Referenced by brix_tier_register_cache_store().
brix_tier_register_cache_store()
static ngx_int_t brix_tier_register_cache_store (ngx_conf_t * cf, ngx_http_brix_shared_conf_t * common) static
Definition at line 565 of file runtime_server_backend.c.
References brix_cache_policy_t::allow_prefixes, brix_cache_policy_t::batch_cinfo, BRIX_CACHE_VERIFY_CVMFS_CAS, BRIX_CACHE_VERIFY_OFF, BRIX_TIER_CACHE, brix_tier_load_master_key(), brix_tier_parse_store(), brix_tier_register_cache_peers(), brix_vfs_backend_config_cache_cold_store(), brix_vfs_backend_config_cache_store(), ngx_http_brix_shared_conf_t::cache_allow_prefixes, ngx_http_brix_shared_conf_t::cache_batch_cinfo, ngx_http_brix_shared_conf_t::cache_cold_store, ngx_http_brix_shared_conf_t::cache_cold_store_args, ngx_http_brix_shared_conf_t::cache_cvmfs_master_key, ngx_http_brix_shared_conf_t::cache_deny_prefixes, ngx_http_brix_shared_conf_t::cache_evict_at, ngx_http_brix_shared_conf_t::cache_evict_to, ngx_http_brix_shared_conf_t::cache_include_re, ngx_http_brix_shared_conf_t::cache_index_cache, ngx_http_brix_shared_conf_t::cache_manifest_ttl, ngx_http_brix_shared_conf_t::cache_max_object, ngx_http_brix_shared_conf_t::cache_meta_mode, ngx_http_brix_shared_conf_t::cache_offline_ttl, ngx_http_brix_shared_conf_t::cache_peers, ngx_http_brix_shared_conf_t::cache_quarantine_dir, ngx_http_brix_shared_conf_t::cache_slice_size, ngx_http_brix_shared_conf_t::cache_store, ngx_http_brix_shared_conf_t::cache_store_args, ngx_http_brix_shared_conf_t::cache_verify_mode, brix_cache_policy_t::cvmfs_manifest_ttl, brix_cache_policy_t::cvmfs_offline_ttl, brix_cache_policy_t::deny_prefixes, brix_tier_cfg_t::driver, brix_cache_policy_t::enabled, brix_cache_policy_t::evict_at, brix_cache_policy_t::evict_to, brix_cache_policy_t::include_regex, brix_cache_policy_t::l1_entries, brix_cache_policy_t::max_file_size, brix_cache_policy_t::meta_mode, brix_cache_policy_t::quarantine_dir, ngx_http_brix_shared_conf_t::root_canon, brix_cache_policy_t::slice_size, and brix_cache_policy_t::verify.
Referenced by brix_tier_register_stores().
brix_tier_register_stores()
ngx_int_t brix_tier_register_stores (ngx_conf_t * cf, ngx_http_brix_shared_conf_t * common)
Definition at line 664 of file runtime_server_backend.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_storage_backend_is_whole_object(), brix_tier_default_stage_store(), brix_tier_parse_store(), brix_tier_register_cache_store(), BRIX_TIER_STAGE, brix_tier_warn_private_tmp(), brix_vfs_backend_config_stage_store(), BRIX_WT_MODE_ASYNC, BRIX_WT_MODE_SYNC, ngx_http_brix_shared_conf_t::cache_cold_store, ngx_http_brix_shared_conf_t::cache_peers, ngx_http_brix_shared_conf_t::cache_store, brix_stage_policy_t::enabled, brix_stage_policy_t::flush_mode, ngx_http_brix_shared_conf_t::root_canon, ngx_http_brix_shared_conf_t::stage_enable, ngx_http_brix_shared_conf_t::stage_flush_async, ngx_http_brix_shared_conf_t::stage_store, ngx_http_brix_shared_conf_t::stage_store_args, and ngx_http_brix_shared_conf_t::storage_backend.
Referenced by brix_server_setup_export(), cvmfs_merge_cache(), s3_merge_export(), and webdav_validate_webdav_enabled().
brix_tier_warn_private_tmp()
static void brix_tier_warn_private_tmp (ngx_conf_t * cf, const ngx_http_brix_shared_conf_t * common) static
Definition at line 243 of file runtime_server_backend.c.
References brix_tmp_is_systemd_private(), ngx_http_brix_shared_conf_t::cache_store, and ngx_http_brix_shared_conf_t::stage_store.
Referenced by brix_tier_register_stores().
brix_tmp_is_systemd_private()
static int brix_tmp_is_systemd_private (void) static
Definition at line 211 of file runtime_server_backend.c.
Referenced by brix_tier_warn_private_tmp().