nginx-xrootd: src/core/config/runtime_server_backend_cache.c File Reference
runtime_server_backend_cache.c File Reference
#include "config.h"
#include "root_prepare.h"
#include "credential_block.h"
#include "core/compat/staged_file.h"
#include "core/compat/tmp_path.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "fs/path/path.h"
#include "fs/tier/tier.h"
#include "fs/cache/cache_internal.h"
#include "core/config/export_guard.h"
#include "runtime_server_backend_internal.h"
#include <stdlib.h>
#include <string.h>
Functions
static ngx_int_t brix_tier_load_master_key (ngx_conf_t *cf, const ngx_str_t *path, brix_cache_policy_t *pol)
static ngx_int_t brix_tier_register_cache_peers (ngx_conf_t *cf, ngx_http_brix_shared_conf_t *common)
static void brix_tier_fill_cache_policy (ngx_http_brix_shared_conf_t *common, brix_cache_policy_t *polp)
ngx_int_t brix_tier_register_cache_store (ngx_conf_t *cf, ngx_http_brix_shared_conf_t *common)
Function Documentation
brix_tier_fill_cache_policy()
static void brix_tier_fill_cache_policy (ngx_http_brix_shared_conf_t * common, brix_cache_policy_t * polp) static
Definition at line 180 of file runtime_server_backend_cache.c.
References brix_cache_policy_t::allow_prefixes, brix_cache_policy_t::batch_cinfo, BRIX_CACHE_VERIFY_OFF, ngx_http_brix_shared_conf_t::cache_allow_prefixes, ngx_http_brix_shared_conf_t::cache_batch_cinfo, ngx_http_brix_shared_conf_t::cache_deny_prefixes, ngx_http_brix_shared_conf_t::cache_evict_at, ngx_http_brix_shared_conf_t::cache_evict_to, ngx_http_brix_shared_conf_t::cache_include_re, ngx_http_brix_shared_conf_t::cache_index_cache, ngx_http_brix_shared_conf_t::cache_manifest_ttl, ngx_http_brix_shared_conf_t::cache_max_object, ngx_http_brix_shared_conf_t::cache_meta_mode, ngx_http_brix_shared_conf_t::cache_offline_ttl, ngx_http_brix_shared_conf_t::cache_quarantine_dir, ngx_http_brix_shared_conf_t::cache_slice_size, ngx_http_brix_shared_conf_t::cache_verify_mode, brix_cache_policy_t::cvmfs_manifest_ttl, brix_cache_policy_t::cvmfs_offline_ttl, brix_cache_policy_t::deny_prefixes, brix_cache_policy_t::enabled, brix_cache_policy_t::evict_at, brix_cache_policy_t::evict_to, brix_cache_policy_t::include_regex, brix_cache_policy_t::l1_entries, brix_cache_policy_t::max_file_size, brix_cache_policy_t::meta_mode, brix_cache_policy_t::quarantine_dir, brix_cache_policy_t::slice_size, and brix_cache_policy_t::verify.
Referenced by brix_tier_register_cache_store().
brix_tier_load_master_key()
static ngx_int_t brix_tier_load_master_key (ngx_conf_t * cf, const ngx_str_t * path, brix_cache_policy_t * pol) static
Definition at line 33 of file runtime_server_backend_cache.c.
References close(), brix_cache_policy_t::cvmfs_master_pub, brix_cache_policy_t::cvmfs_master_pub_len, open(), and read().
Referenced by brix_tier_register_cache_store().
brix_tier_register_cache_peers()
static ngx_int_t brix_tier_register_cache_peers (ngx_conf_t * cf, ngx_http_brix_shared_conf_t * common) static
Definition at line 96 of file runtime_server_backend_cache.c.
References brix_vfs_backend_config_cache_peers(), ngx_http_brix_shared_conf_t::cache_peers, ngx_memcpy, port, ngx_http_brix_shared_conf_t::root_canon, and tok.
Referenced by brix_tier_register_cache_store().
brix_tier_register_cache_store()
ngx_int_t brix_tier_register_cache_store (ngx_conf_t * cf, ngx_http_brix_shared_conf_t * common)
Definition at line 225 of file runtime_server_backend_cache.c.
References BRIX_CACHE_VERIFY_CVMFS_CAS, BRIX_TIER_CACHE, brix_tier_fill_cache_policy(), brix_tier_load_master_key(), brix_tier_parse_store(), brix_tier_register_cache_peers(), brix_vfs_backend_config_cache_cold_store(), brix_vfs_backend_config_cache_store(), ngx_http_brix_shared_conf_t::cache_cold_store, ngx_http_brix_shared_conf_t::cache_cold_store_args, ngx_http_brix_shared_conf_t::cache_cvmfs_master_key, ngx_http_brix_shared_conf_t::cache_peers, ngx_http_brix_shared_conf_t::cache_store, ngx_http_brix_shared_conf_t::cache_store_args, brix_tier_cfg_t::driver, ngx_http_brix_shared_conf_t::root_canon, and brix_cache_policy_t::verify.
Referenced by brix_tier_register_stores().