nginx-xrootd: src/core/config/runtime_server_backend_stage.c File Reference
runtime_server_backend_stage.c File Reference
#include "config.h"
#include "root_prepare.h"
#include "credential_block.h"
#include "core/compat/staged_file.h"
#include "core/compat/tmp_path.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "fs/path/path.h"
#include "fs/tier/tier.h"
#include "fs/cache/cache_internal.h"
#include "core/config/export_guard.h"
#include "runtime_server_backend_internal.h"
#include <stdlib.h>
#include <string.h>
Macros
#define BRIX_TIER_DEFAULT_STAGE_BASE "/tmp/staging"
Functions
static int brix_tmp_is_systemd_private (void)
void brix_tier_warn_private_tmp (ngx_conf_t *cf, const ngx_http_brix_shared_conf_t *common)
static void brix_tier_default_stage_dir (const ngx_str_t *backend, uid_t worker_uid, char *dir, size_t cap)
void brix_tier_default_stage_store (ngx_conf_t *cf, ngx_http_brix_shared_conf_t *common)
Macro Definition Documentation
BRIX_TIER_DEFAULT_STAGE_BASE
#define BRIX_TIER_DEFAULT_STAGE_BASE "/tmp/staging"
Definition at line 24 of file runtime_server_backend_stage.c.
Function Documentation
brix_tier_default_stage_dir()
static void brix_tier_default_stage_dir (const ngx_str_t * backend, uid_t worker_uid, char * dir, size_t cap) static
Definition at line 113 of file runtime_server_backend_stage.c.
References BRIX_TIER_DEFAULT_STAGE_BASE, and c.
Referenced by brix_tier_default_stage_store().
brix_tier_default_stage_store()
void brix_tier_default_stage_store (ngx_conf_t * cf, ngx_http_brix_shared_conf_t * common)
Definition at line 168 of file runtime_server_backend_stage.c.
References access(), brix_mkdir_recursive(), brix_shared_worker_dir_ids(), BRIX_TIER_DEFAULT_STAGE_BASE, brix_tier_default_stage_dir(), ngx_pnalloc(), PATH_MAX, ngx_http_brix_shared_conf_t::stage_enable, ngx_http_brix_shared_conf_t::stage_store, stat(), and ngx_http_brix_shared_conf_t::storage_backend.
Referenced by brix_tier_register_stores().
brix_tier_warn_private_tmp()
void brix_tier_warn_private_tmp (ngx_conf_t * cf, const ngx_http_brix_shared_conf_t * common)
Definition at line 63 of file runtime_server_backend_stage.c.
References brix_tmp_is_systemd_private(), ngx_http_brix_shared_conf_t::cache_store, and ngx_http_brix_shared_conf_t::stage_store.
Referenced by brix_tier_register_stores().
brix_tmp_is_systemd_private()
static int brix_tmp_is_systemd_private (void) static
Definition at line 31 of file runtime_server_backend_stage.c.
Referenced by brix_tier_warn_private_tmp().