nginx-xrootd: src/protocols/s3/put.c File Reference
put.c File Reference
#include "s3_put_internal.h"
Functions
const char * s3_dashboard_put_op (ngx_http_request_t *r)
void s3_dashboard_identity (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, char *out, size_t outsz)
ngx_uint_t s3_put_body_mode (const brix_http_body_summary_t *summary)
void s3_put_streaming (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, brix_vfs_staged_t *staged, const char *fs_path, ngx_uint_t body_mode)
void s3_put_body_handler (ngx_http_request_t *r)
static int s3_put_try_sentinel (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const u_char *fs_path)
void s3_put_body_inner (ngx_http_request_t *r)
Function Documentation
s3_dashboard_identity()
void s3_dashboard_identity (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, char * out, size_t outsz)
Definition at line 24 of file put.c.
References ngx_http_s3_loc_conf_t::access_key, brix_identity_subject_cstr(), ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, and ngx_memcpy.
Referenced by s3_put_body_inner(), and s3_put_try_sentinel().
s3_dashboard_put_op()
const char * s3_dashboard_put_op (ngx_http_request_t * r)
Definition at line 8 of file put.c.
References s3_get_query_param().
Referenced by s3_put_body_inner().
s3_put_body_handler()
void s3_put_body_handler (ngx_http_request_t * r)
Definition at line 178 of file put.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, and s3_put_body_inner().
Referenced by s3_dispatch_after_auth().
s3_put_body_inner()
void s3_put_body_inner (ngx_http_request_t * r)
Definition at line 262 of file put.c.
References brix_codec_desc_t::available, s3_put_aio_t::body_bytes, s3_put_aio_t::body_mode, brix_codec_by_http_token(), BRIX_CODEC_IDENTITY, brix_dashboard_http_start_identity(), BRIX_DECODE_MAX_OUTPUT, brix_http_body_decode_to_fd(), brix_http_body_summary(), brix_http_body_write_to_fd(), brix_http_find_header(), brix_log_safe_path(), BRIX_S3_PUT_EMPTY, brix_vfs_mkdir(), brix_vfs_probe(), brix_vfs_staged_abort(), brix_vfs_staged_fd(), brix_vfs_staged_open(), BRIX_XFER_DIR_WRITE, BRIX_XFER_PROTO_S3, brix_http_body_summary_t::bytes, ngx_http_s3_loc_conf_t::common, s3_put_aio_t::final_path, ngx_http_s3_req_ctx_t::fs_path, brix_codec_desc_t::id, brix_vfs_stat_t::is_directory, s3_put_aio_t::len, brix_vfs_stat_t::mtime, ngx_http_brix_s3_module, PATH_MAX, s3_put_aio_t::r, ngx_http_brix_shared_conf_t::root_canon, s3_put_aio_t::root_canon, s3_apply_put_tagging_header(), s3_apply_put_user_metadata(), s3_aws_chunked_has_inner_coding(), s3_body_is_aws_chunked(), s3_build_vfs_ctx(), s3_commit_put(), s3_dashboard_identity(), s3_dashboard_put_op(), s3_etag(), s3_put_aio_done(), s3_put_aio_thread(), s3_put_body_mode(), s3_put_checksum_failed(), s3_put_commit_conflict(), s3_put_finalize_codec_error(), s3_put_finalize_error(), s3_put_finalize_fs_error(), s3_put_finalize_ok(), s3_put_streaming(), s3_put_try_sentinel(), s3_set_header(), s3_thread_pool(), brix_vfs_stat_t::size, s3_put_aio_t::staged, stat(), and ngx_http_brix_shared_conf_t::thread_pool.
Referenced by s3_put_body_handler().
s3_put_body_mode()
ngx_uint_t s3_put_body_mode (const brix_http_body_summary_t * summary)
Definition at line 64 of file put.c.
References BRIX_S3_PUT_EMPTY, BRIX_S3_PUT_MEMORY, BRIX_S3_PUT_MIXED, BRIX_S3_PUT_SPOOLED, brix_http_body_summary_t::has_memory, and brix_http_body_summary_t::has_spooled.
Referenced by s3_put_body_inner().
s3_put_streaming()
void s3_put_streaming (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, brix_vfs_staged_t * staged, const char * fs_path, ngx_uint_t body_mode)
Definition at line 88 of file put.c.
References s3_chunk_aio_t::body_mode, brix_http_find_header(), brix_vfs_staged_abort(), brix_vfs_staged_fd(), ngx_http_s3_loc_conf_t::common, s3_chunk_aio_t::expected, s3_chunk_aio_t::fs_path, s3_chunk_aio_t::r, ngx_http_brix_shared_conf_t::root_canon, s3_chunk_aio_t::root_canon, s3_aws_chunked_decode_to_fd(), s3_build_chunk_verify(), s3_chunk_aio_done(), s3_chunk_aio_thread(), s3_chunk_decode_failed(), s3_chunk_finalize(), s3_put_finalize_client_error(), s3_put_finalize_error(), s3_thread_pool(), s3_chunk_aio_t::staged, and s3_chunk_aio_t::verify.
Referenced by s3_put_body_inner().
s3_put_try_sentinel()
static int s3_put_try_sentinel (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const u_char * fs_path) static
Definition at line 194 of file put.c.
References brix_dashboard_http_start_identity(), brix_log_safe_path(), BRIX_S3_EVENT_DIR_SENTINEL, BRIX_S3_METRIC_INC, BRIX_S3_PUT_EMPTY, brix_vfs_mkdir(), brix_vfs_open_fd(), BRIX_XFER_DIR_WRITE, BRIX_XFER_PROTO_S3, close(), ngx_http_s3_loc_conf_t::common, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, s3_build_vfs_ctx(), s3_dashboard_identity(), S3_DIR_SENTINEL, s3_put_finalize_empty_ok(), s3_put_finalize_error(), and s3_put_finalize_fs_error().
Referenced by s3_put_body_inner().