nginx-xrootd: src/protocols/s3/util.c File Reference
util.c File Reference
#include "s3.h"
#include "core/http/etag.h"
#include "core/http/http_headers.h"
#include "core/http/http_xml.h"
#include "core/compat/integrity_info.h"
#include "core/compat/path.h"
#include "core/compat/xml.h"
#include <sys/stat.h>
#include <limits.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
Functions
void s3_build_vfs_ctx (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, brix_vfs_ctx_t *vctx)
void s3_vfs_bind_deleg (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, brix_vfs_ctx_t *vctx)
ngx_int_t s3_set_header (ngx_http_request_t *r, const char *key, const char *val)
int s3_resolve_key (const char *root, const char *key, char *out, size_t outsz, unsigned allow_internal)
void s3_etag (const struct stat *st, char *buf, size_t bufsz)
ngx_int_t s3_send_xml_error (ngx_http_request_t *r, ngx_uint_t status, const char *code, const char *message)
ngx_int_t s3_fail (ngx_http_request_t *r, ngx_uint_t status, const char *code, const char *message, int event)
ngx_int_t s3_object_crc64nvme_b64 (ngx_http_request_t *r, int fd, const char *path, ngx_flag_t cache_only, char *out, size_t outsz)
Function Documentation
s3_build_vfs_ctx()
void s3_build_vfs_ctx (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, brix_vfs_ctx_t * vctx)
Definition at line 27 of file util.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_S3, brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_bind_backend_mint(), brix_vfs_ctx_init(), ngx_http_s3_loc_conf_t::cache_root_canon, ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, brix_vfs_ctx_t::pool, ngx_http_brix_shared_conf_t::root_canon, s3_vfs_bind_deleg(), ngx_http_brix_shared_conf_t::storage_credential_dir, ngx_http_brix_shared_conf_t::storage_credential_fallback, ngx_http_brix_shared_conf_t::storage_credential_mint_ca_cert, ngx_http_brix_shared_conf_t::storage_credential_mint_ca_key, and ngx_http_brix_shared_conf_t::storage_credential_mint_ttl.
Referenced by lp_scan_staged_parts(), mpu_collect(), mpu_scan_entry(), s3_handle_list_parts(), s3_handle_multipart_abort(), s3_mpu_reap_one_entry(), s3_mpu_reap_stale(), s3_multipart_complete_body_handler_inner(), s3_post_write_object(), s3_put_try_sentinel(), s3_resolve_copy_source(), s3_resolve_part_target(), s3put_emit_etag(), s3put_ensure_parent_dirs(), and s3put_open_target().
s3_etag()
void s3_etag (const struct stat * st, char * buf, size_t bufsz)
Definition at line 156 of file util.c.
References brix_http_etag_str().
Referenced by s3_chunk_finalize(), s3_entry_fill_stat(), s3_handle_copy_object(), s3_mpu_send_result(), s3_post_write_object(), s3_put_aio_done(), s3_send_copy_part_result(), and s3put_emit_etag().
s3_fail()
ngx_int_t s3_fail (ngx_http_request_t * r, ngx_uint_t status, const char * code, const char * message, int event)
Definition at line 192 of file util.c.
References BRIX_S3_METRIC_INC, code, and s3_send_xml_error().
Referenced by s3_get_check_residency(), s3_get_resolve(), s3_get_serve_offload(), s3_get_serve_zip_member(), s3_handle_copy_object(), s3_handle_delete_object_tagging(), s3_handle_get_acl(), s3_handle_get_object_tagging(), and s3_handle_head().
s3_object_crc64nvme_b64()
ngx_int_t s3_object_crc64nvme_b64 (ngx_http_request_t * r, int fd, const char * path, ngx_flag_t cache_only, char * out, size_t outsz)
Definition at line 219 of file util.c.
References brix_integrity_opts_t::allow_xattr_cache, brix_integrity_get_fd(), brix_integrity_info_t::hex, brix_integrity_opts_t::no_compute, brix_integrity_opts_t::require_regular_file, and brix_integrity_opts_t::update_xattr_cache.
Referenced by s3_mpu_assemble().
s3_resolve_key()
int s3_resolve_key (const char * root, const char * key, char * out, size_t outsz, unsigned allow_internal)
Definition at line 125 of file util.c.
References brix_http_resolve_path_ex(), key, and PATH_MAX.
Referenced by s3_delete_dispose_key(), s3_handle_copy_object(), s3_post_object_body_handler_inner(), and s3_resolve_object_key().
s3_send_xml_error()
ngx_int_t s3_send_xml_error (ngx_http_request_t * r, ngx_uint_t status, const char * code, const char * message)
Definition at line 172 of file util.c.
References brix_http_send_xml_error(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, and code.
Referenced by s3_check_token_scope(), s3_delete_parse_body(), s3_delete_run_batch(), s3_dispatch_empty_key(), s3_dispatch_object_put(), s3_dispatch_parse_uri(), s3_fail(), s3_get_serve_zip_member(), s3_handle_copy_object(), s3_handle_delete(), s3_handle_get_cors(), s3_handle_list_parts(), s3_handle_multipart_abort(), s3_handle_upload_part_copy(), s3_multipart_complete_body_handler_inner(), s3_post_error(), s3_prepare_upload_part(), s3_put_finalize_bad_digest(), s3_put_finalize_client_error(), s3_put_finalize_codec_error(), s3_put_finalize_fs_error(), s3_put_finalize_invalid_request(), s3_put_object_tagging_body_handler(), s3_reject_bad_amz_date(), s3_reject_clock_skew(), s3_reject_write_disabled(), s3_resolve_copy_source(), s3_resolve_object_key(), s3_resolve_part_target(), s3_send_precondition_failed(), s3_sigv4_bearer_intercept(), s3_sigv4_check_session_token(), s3_sigv4_compare(), s3_sigv4_parse_authz_header(), s3_sigv4_resolve_request_time(), and s3_verify_bearer().
s3_set_header()
ngx_int_t s3_set_header (ngx_http_request_t * r, const char * key, const char * val)
Definition at line 99 of file util.c.
References brix_http_set_header(), and key.
Referenced by s3_chunk_finalize(), s3_echo_object_checksums(), s3_echo_user_metadata(), s3_handle_head_bucket(), s3_mpu_send_result(), s3_post_send_success(), s3_post_write_object(), s3_put_aio_done(), s3_put_checksum_apply(), s3_put_trailer_checksum_apply(), s3_send_not_modified(), and s3put_emit_etag().
s3_vfs_bind_deleg()
void s3_vfs_bind_deleg (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, brix_vfs_ctx_t * vctx)
Definition at line 71 of file util.c.
References ngx_http_brix_shared_conf_t::backend_delegation, ngx_http_s3_req_ctx_t::bearer_token, BRIX_CRED_SELECT, brix_vfs_deleg_bind(), ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::deleg_proxy_pem, and ngx_http_brix_s3_module.
Referenced by s3_build_vfs_ctx(), s3_chunk_finalize(), s3_commit_put(), s3_copy_vfs_ctx(), s3_put_aio_done(), and s3_vfs_ctx().