nginx-xrootd: src/protocols/s3/s3.h File Reference
s3.h File Reference
#include <ngx_http.h>
#include <openssl/evp.h>
#include <openssl/hmac.h>
#include <limits.h>
#include <sys/types.h>
#include <ngx_thread_pool.h>
#include "observability/metrics/metrics.h"
#include "core/compat/protocol_caps.h"
#include "fs/vfs/vfs.h"
#include "core/config/shared_conf.h"
#include "core/compat/namespace_ops.h"
#include "auth/authz/acc/acc.h"
#include "core/http/etag.h"
#include "core/compat/error_mapping.h"
#include "core/http/http_xml.h"
#include "core/compat/log.h"
#include "core/compat/range.h"
#include "core/compat/time.h"
#include "core/compat/uri.h"
#include "core/compat/xml.h"
#include "core/types/identity.h"
#include "s3_handlers.h"
Data Structures
struct ngx_http_s3_loc_conf_t
struct ngx_http_s3_req_ctx_t
struct s3_entry_t
Macros
#define S3_DIR_SENTINEL ".xrdcls3.dirsentinel"
#define S3_MAX_KEY 4096
#define S3_MAX_PARAM 2048
#define S3_LIST_MAX_ENTRIES 65536
#define S3_LIST_QUERY_FLAGS
#define XML_APPEND(fmt, ...)
#define XML_APPEND_ELEM(name, value, value_len)
#define S3_HDR_CHECKSUM_CRC64NVME "x-amz-checksum-crc64nvme"
#define S3_HDR_CHECKSUM_TYPE "x-amz-checksum-type"
#define S3_CRC64NVME_B64_MAX 16
#define S3_HDR_SDK_CHECKSUM_ALGO "x-amz-sdk-checksum-algorithm"
#define S3_HDR_CHECKSUM_MODE "x-amz-checksum-mode"
#define S3_CHECKSUM_B64_MAX 48
Enumerations
enum s3_cksum_result_t { S3_CKSUM_OK = 0 , S3_CKSUM_MISMATCH , S3_CKSUM_CONFLICT , S3_CKSUM_ERROR }
Functions
int brix_open_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, int flags, mode_t mode)
int brix_unlink_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, int is_dir)
int brix_mkdir_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, mode_t mode)
int brix_rename_confined_canon (ngx_log_t *log, const char *root_canon, const char *src_resolved, const char *dst_resolved)
int brix_link_confined_canon (ngx_log_t *log, const char *root_canon, const char *src_resolved, const char *dst_resolved)
ngx_int_t ngx_http_s3_handler (ngx_http_request_t *r)
ngx_int_t s3_handle_conditional (ngx_http_request_t *r, time_t mtime, off_t size)
ngx_int_t s3_put_precondition (ngx_http_request_t *r, const char *root_canon, const char *fs_path)
int s3_put_is_exclusive_create (ngx_http_request_t *r)
void s3_apply_response_overrides (ngx_http_request_t *r)
void s3_get_pre_header (ngx_http_request_t *r, ngx_fd_t fd, off_t file_size, void *userdata)
ngx_int_t s3_handle_delete (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf)
void s3_put_body_handler (ngx_http_request_t *r)
ngx_thread_pool_t * s3_thread_pool (ngx_http_s3_loc_conf_t *cf)
void s3_post_object_body_handler (ngx_http_request_t *r)
ngx_uint_t s3_metrics_method_slot (ngx_http_request_t *r)
void s3_metrics_request_method (ngx_uint_t method_slot)
void s3_metrics_response_status (ngx_uint_t method_slot, ngx_uint_t http_status)
void s3_metrics_response_method (ngx_http_request_t *r, ngx_uint_t method_slot, ngx_int_t handler_rc)
ngx_int_t s3_metrics_return_method (ngx_http_request_t *r, ngx_uint_t method_slot, ngx_int_t handler_rc)
void s3_metrics_finalize_request_method (ngx_http_request_t *r, ngx_uint_t method_slot, ngx_int_t handler_rc)
ngx_int_t s3_verify_sigv4 (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, brix_identity_t *identity)
ngx_int_t s3_send_xml_error (ngx_http_request_t *r, ngx_uint_t status, const char *code, const char *message)
ngx_int_t s3_fail (ngx_http_request_t *r, ngx_uint_t status, const char *code, const char *message, int event)
ngx_int_t s3_set_header (ngx_http_request_t *r, const char *key, const char *val)
int s3_resolve_key (const char *root, const char *key, char *out, size_t outsz)
int s3_has_query_flag (ngx_http_request_t *r, const char *key)
int s3_get_query_param (ngx_http_request_t *r, const char *key, char *out, size_t outsz)
void s3_get_mpu_dir (const char *fs_path, const char *upload_id, char *out_dir, size_t outsz)
ngx_int_t s3_handle_multipart_initiate (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, const char *key_str)
ngx_int_t s3_handle_multipart_abort (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, const char *upload_id)
void s3_multipart_complete_body_handler (ngx_http_request_t *r)
ngx_int_t s3_handle_list_parts (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, const char *key_str)
ngx_int_t s3_handle_list_multipart_uploads (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf)
ngx_int_t s3_handle_upload_part_copy (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, const char *upload_id, int part_num)
ngx_int_t s3_handle_copy_object (ngx_http_request_t *r, const char *dst_fs_path, ngx_http_s3_loc_conf_t *cf)
void s3_delete_objects_body_handler (ngx_http_request_t *r)
void s3_etag (const struct stat *st, char *buf, size_t bufsz)
void s3_build_vfs_ctx (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, brix_vfs_ctx_t *vctx)
ngx_int_t s3_object_crc64nvme_b64 (ngx_http_request_t *r, int fd, const char *path, ngx_flag_t cache_only, char *out, size_t outsz)
ngx_int_t s3_checksum_b64 (ngx_http_request_t *r, int fd, const char *path, const char *alg_name, ngx_flag_t cache_only, char *out, size_t outsz)
s3_cksum_result_t s3_put_checksum_apply (ngx_http_request_t *r, const char *fs_path, const char *root_canon)
s3_cksum_result_t s3_put_trailer_checksum_apply (ngx_http_request_t *r, const char *fs_path, const char *root_canon, const char *algo_token, const char *value)
void s3_echo_object_checksums (ngx_http_request_t *r, int fd, const char *path)
Variables
ngx_module_t ngx_http_brix_s3_module
const brix_http_operation_t brix_s3_operations []
const ngx_uint_t brix_s3_operations_count
Macro Definition Documentation
S3_CHECKSUM_B64_MAX
#define S3_CHECKSUM_B64_MAX 48
Definition at line 476 of file s3.h.
S3_CRC64NVME_B64_MAX
#define S3_CRC64NVME_B64_MAX 16
Definition at line 456 of file s3.h.
S3_DIR_SENTINEL
#define S3_DIR_SENTINEL ".xrdcls3.dirsentinel"
Definition at line 137 of file s3.h.
S3_HDR_CHECKSUM_CRC64NVME
#define S3_HDR_CHECKSUM_CRC64NVME "x-amz-checksum-crc64nvme"
Definition at line 453 of file s3.h.
S3_HDR_CHECKSUM_MODE
#define S3_HDR_CHECKSUM_MODE "x-amz-checksum-mode"
Definition at line 474 of file s3.h.
S3_HDR_CHECKSUM_TYPE
#define S3_HDR_CHECKSUM_TYPE "x-amz-checksum-type"
Definition at line 454 of file s3.h.
S3_HDR_SDK_CHECKSUM_ALGO
#define S3_HDR_SDK_CHECKSUM_ALGO "x-amz-sdk-checksum-algorithm"
Definition at line 473 of file s3.h.
S3_LIST_MAX_ENTRIES
#define S3_LIST_MAX_ENTRIES 65536
Definition at line 146 of file s3.h.
S3_LIST_QUERY_FLAGS
#define S3_LIST_QUERY_FLAGS
Value:
    (BRIX_HTTP_QUERY_DECODE_VALUE | BRIX_HTTP_QUERY_PLUS_TO_SPACE \
     | BRIX_HTTP_QUERY_REJECT_NUL | BRIX_HTTP_QUERY_ALLOW_EMPTY)
Definition at line 153 of file s3.h.
S3_MAX_KEY
#define S3_MAX_KEY 4096
Definition at line 140 of file s3.h.
S3_MAX_PARAM
#define S3_MAX_PARAM 2048
Definition at line 143 of file s3.h.
XML_APPEND
#define XML_APPEND (fmt, ...)
Value:
    do { \
    int _xml_n = snprintf((char *) xml + xml_len, xml_capacity - xml_len, \
                          fmt, ##__VA_ARGS__); \
    if (_xml_n < 0 || (size_t) _xml_n >= xml_capacity - xml_len) { \
        BRIX_S3_METRIC_INC(events_total[BRIX_S3_EVENT_INTERNAL_ERROR]); \
        return NGX_HTTP_INTERNAL_SERVER_ERROR; \
    } \
    xml_len += (size_t) _xml_n; \
} while (0)
Definition at line 183 of file s3.h.
XML_APPEND_ELEM
#define XML_APPEND_ELEM (name, value, value_len)
Value:
    do { \
    size_t _xml_written; \
    if (brix_xml_write_text_element((name), \
            (const unsigned char *)(value), (value_len), \
            BRIX_XML_ESCAPE_APOS_ENTITY, \
            xml + xml_len, xml_capacity - xml_len, \
            &_xml_written) != 0) \
    { \
        BRIX_S3_METRIC_INC(events_total[BRIX_S3_EVENT_INTERNAL_ERROR]); \
        return NGX_HTTP_INTERNAL_SERVER_ERROR; \
    } \
    xml_len += _xml_written; \
} while (0)
Definition at line 193 of file s3.h.
Enumeration Type Documentation
s3_cksum_result_t
enum s3_cksum_result_t
Enumerator
S3_CKSUM_OK
S3_CKSUM_MISMATCH
S3_CKSUM_CONFLICT
S3_CKSUM_ERROR
Definition at line 479 of file s3.h.
Function Documentation
brix_link_confined_canon()
int brix_link_confined_canon (ngx_log_t * log, const char * root_canon, const char * src_resolved, const char * dst_resolved)
Definition at line 341 of file resolve_confined_ops.c.
brix_mkdir_confined_canon()
int brix_mkdir_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, mode_t mode)
Definition at line 217 of file resolve_confined_ops.c.
brix_open_confined_canon()
int brix_open_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, int flags, mode_t mode)
Definition at line 95 of file resolve_confined_ops.c.
brix_rename_confined_canon()
int brix_rename_confined_canon (ngx_log_t * log, const char * root_canon, const char * src_resolved, const char * dst_resolved)
Definition at line 323 of file resolve_confined_ops.c.
brix_unlink_confined_canon()
int brix_unlink_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, int is_dir)
Definition at line 185 of file resolve_confined_ops.c.
ngx_http_s3_handler()
ngx_int_t ngx_http_s3_handler (ngx_http_request_t * r)
Definition at line 362 of file handler.c.
References brix_http_source_offer(), brix_identity_alloc(), brix_identity_dn_cstr(), brix_identity_vo_csv_cstr(), brix_imp_request_begin(), brix_imp_request_end(), BRIX_PCALLOC_OR_RETURN, brix_pmark_http_mark(), BRIX_S3_METHOD_LIST, ngx_http_s3_loc_conf_t::common, ngx_http_brix_shared_conf_t::enable, brix_pmark_conf_t::enable, brix_pmark_conf_t::http_plain, ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, ngx_http_brix_shared_conf_t::pmark, s3_acc_check(), s3_dispatch_after_auth(), s3_handle_options(), s3_is_list_request(), s3_is_post_object_form(), s3_metrics_method_slot(), s3_metrics_request_method(), s3_metrics_return_method(), and s3_verify_sigv4().
Referenced by ngx_http_s3_set().
s3_apply_response_overrides()
void s3_apply_response_overrides (ngx_http_request_t * r)
Definition at line 233 of file conditional.c.
References brix_http_query_get(), brix_http_str_has_ctl(), s3_override_header(), and S3_OVERRIDE_QUERY_FLAGS.
Referenced by s3_get_pre_header().
s3_build_vfs_ctx()
void s3_build_vfs_ctx (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, brix_vfs_ctx_t * vctx)
Definition at line 27 of file util.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_S3, brix_vfs_ctx_init(), ngx_http_s3_loc_conf_t::cache_root_canon, ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, brix_vfs_ctx_t::pool, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by mpu_collect(), s3_handle_list_parts(), s3_handle_multipart_abort(), s3_handle_upload_part_copy(), s3_mpu_reap_stale(), s3_multipart_complete_body_handler_inner(), s3_post_write_object(), s3_put_body_inner(), and s3_put_try_sentinel().
s3_checksum_b64()
ngx_int_t s3_checksum_b64 (ngx_http_request_t * r, int fd, const char * path, const char * alg_name, ngx_flag_t cache_only, char * out, size_t outsz)
Definition at line 135 of file checksum.c.
References brix_integrity_opts_t::allow_xattr_cache, brix_integrity_get_fd(), brix_integrity_info_t::hex, brix_integrity_opts_t::no_compute, brix_integrity_opts_t::require_regular_file, s3_hexval(), and brix_integrity_opts_t::update_xattr_cache.
Referenced by s3_echo_object_checksums(), s3_put_checksum_apply(), and s3_put_trailer_checksum_apply().
s3_delete_objects_body_handler()
void s3_delete_objects_body_handler (ngx_http_request_t * r)
Definition at line 267 of file delete_objects.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, and s3_delete_objects_body_handler_inner().
Referenced by s3_dispatch_after_auth().
s3_echo_object_checksums()
void s3_echo_object_checksums (ngx_http_request_t * r, int fd, const char * path)
Definition at line 378 of file checksum.c.
References brix_http_find_header(), mode, s3_checksum_b64(), S3_CHECKSUM_B64_MAX, S3_CKSUM_DEFAULT_IDX, s3_cksum_table, S3_CKSUM_TABLE_N, S3_HDR_CHECKSUM_TYPE, and s3_set_header().
Referenced by s3_handle_get(), and s3_handle_head().
s3_etag()
void s3_etag (const struct stat * st, char * buf, size_t bufsz)
Definition at line 106 of file util.c.
References brix_http_etag_str().
Referenced by s3_chunk_finalize(), s3_entry_fill_stat(), s3_handle_copy_object(), s3_handle_upload_part_copy(), s3_mpu_send_result(), s3_post_write_object(), s3_put_aio_done(), and s3_put_body_inner().
s3_fail()
ngx_int_t s3_fail (ngx_http_request_t * r, ngx_uint_t status, const char * code, const char * message, int event)
Definition at line 142 of file util.c.
References BRIX_S3_METRIC_INC, and s3_send_xml_error().
Referenced by s3_handle_copy_object(), s3_handle_delete_object_tagging(), s3_handle_get(), s3_handle_get_object_tagging(), and s3_handle_head().
s3_get_mpu_dir()
void s3_get_mpu_dir (const char * fs_path, const char * upload_id, char * out_dir, size_t outsz)
Definition at line 87 of file multipart_helpers.c.
Referenced by s3_dispatch_after_auth(), s3_handle_list_parts(), s3_handle_multipart_abort(), s3_handle_multipart_initiate(), s3_handle_upload_part_copy(), and s3_multipart_complete_body_handler_inner().
s3_get_pre_header()
void s3_get_pre_header (ngx_http_request_t * r, ngx_fd_t fd, off_t file_size, void * userdata)
Definition at line 271 of file conditional.c.
References s3_apply_response_overrides().
Referenced by s3_handle_get().
s3_get_query_param()
int s3_get_query_param (ngx_http_request_t * r, const char * key, char * out, size_t outsz)
Definition at line 66 of file multipart_helpers.c.
References brix_http_query_get(), BRIX_HTTP_QUERY_TRUNCATE, and key.
Referenced by s3_dashboard_put_op(), s3_dispatch_after_auth(), s3_handle_list_multipart_uploads(), s3_handle_list_parts(), and s3_multipart_complete_body_handler_inner().
s3_handle_conditional()
ngx_int_t s3_handle_conditional (ngx_http_request_t * r, time_t mtime, off_t size)
Definition at line 86 of file conditional.c.
References BRIX_HTTP_COND_READ, BRIX_HTTP_COND_TIME, BRIX_HTTP_COND_WEAK_EQUIV, brix_http_etag_str(), brix_http_eval_preconditions(), s3_send_not_modified(), and s3_send_precondition_failed().
Referenced by s3_handle_get(), and s3_handle_head().
s3_handle_copy_object()
ngx_int_t s3_handle_copy_object (ngx_http_request_t * r, const char * dst_fs_path, ngx_http_s3_loc_conf_t * cf)
Definition at line 72 of file copy.c.
References brix_format_iso8601(), brix_http_send_xml_buffer(), BRIX_S3_EVENT_ACCESS_DENIED, BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_EVENT_NO_SUCH_KEY, BRIX_S3_METRIC_INC, brix_vfs_copy(), brix_vfs_probe(), ngx_http_s3_loc_conf_t::common, brix_vfs_stat_t::mtime, brix_vfs_copy_opts_t::overwrite, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, s3_apply_put_user_metadata(), s3_copy_find_header(), s3_copy_vfs_ctx(), s3_etag(), s3_fail(), s3_resolve_key(), s3_send_xml_error(), s3_user_meta_copy(), brix_vfs_stat_t::size, brix_vfs_copy_opts_t::staged_commit, and stat().
Referenced by s3_dispatch_after_auth().
s3_handle_delete()
ngx_int_t s3_handle_delete (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf)
Definition at line 520 of file object.c.
References BRIX_S3_EVENT_DELETE_MISSING, BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, brix_vfs_unlink(), s3_send_xml_error(), and s3_vfs_ctx().
Referenced by s3_dispatch_after_auth().
s3_handle_list_multipart_uploads()
ngx_int_t s3_handle_list_multipart_uploads (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf)
Definition at line 188 of file multipart_complete_list_uploads.c.
References brix_format_iso8601(), brix_http_send_xml_buffer(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, ngx_http_s3_loc_conf_t::bucket, ngx_http_s3_loc_conf_t::common, key, mpu_collect(), MPU_MAX_LISTED_UPLOADS, mpu_upload_entry_cmp(), ngx_http_brix_shared_conf_t::root, ngx_http_brix_shared_conf_t::root_canon, s3_get_query_param(), XML_APPEND, and XML_APPEND_ELEM.
Referenced by s3_dispatch_after_auth().
s3_handle_list_parts()
ngx_int_t s3_handle_list_parts (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, const char * key_str)
Definition at line 59 of file multipart_complete_list_parts.c.
References brix_format_iso8601(), brix_http_send_xml_buffer(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, brix_vfs_closedir(), brix_vfs_opendir_quiet(), brix_vfs_probe(), brix_vfs_readdir_kind(), ngx_http_s3_loc_conf_t::bucket, brix_vfs_stat_t::is_directory, brix_vfs_stat_t::is_regular, MPU_MAX_PART_NUMBER, mpu_part_entry_cmp(), mpu_validate_upload_id(), brix_vfs_stat_t::mtime, mpu_part_entry_t::mtime, name, mpu_part_entry_t::part_num, PATH_MAX, s3_build_vfs_ctx(), s3_get_mpu_dir(), s3_get_query_param(), s3_send_xml_error(), brix_vfs_stat_t::size, mpu_part_entry_t::size, XML_APPEND, and XML_APPEND_ELEM.
Referenced by s3_dispatch_after_auth().
s3_handle_multipart_abort()
ngx_int_t s3_handle_multipart_abort (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, const char * upload_id)
Definition at line 17 of file multipart_abort.c.
References BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, brix_vfs_probe(), ngx_http_s3_loc_conf_t::common, mpu_rmdir_recursive(), mpu_validate_upload_id(), PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, s3_build_vfs_ctx(), s3_get_mpu_dir(), and s3_send_xml_error().
Referenced by s3_dispatch_after_auth().
s3_handle_multipart_initiate()
ngx_int_t s3_handle_multipart_initiate (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, const char * key_str)
Definition at line 38 of file multipart_initiate.c.
References brix_http_send_xml_buffer(), brix_log_safe_path(), brix_mkdir_confined_canon(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, ngx_http_s3_loc_conf_t::bucket, ngx_http_s3_loc_conf_t::common, ngx_http_s3_loc_conf_t::mpu_max_age, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, s3_get_mpu_dir(), and s3_mpu_reap_stale().
Referenced by s3_dispatch_after_auth().
s3_handle_upload_part_copy()
ngx_int_t s3_handle_upload_part_copy (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, const char * upload_id, int part_num)
Definition at line 54 of file multipart_complete_upload_part_copy.c.
References brix_format_iso8601(), brix_http_send_xml_buffer(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, brix_sd_posix_wrap(), brix_vfs_close(), brix_vfs_file_fd(), BRIX_VFS_O_READ, brix_vfs_open(), brix_vfs_open_fd(), brix_vfs_probe(), brix_vfs_unlink_path(), close(), ngx_http_s3_loc_conf_t::common, fstat(), brix_vfs_stat_t::is_regular, mpu_validate_upload_id(), PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, s3_build_vfs_ctx(), s3_etag(), s3_find_request_header_value(), s3_get_mpu_dir(), s3_send_xml_error(), and stat().
Referenced by s3_dispatch_after_auth().
s3_has_query_flag()
int s3_has_query_flag (ngx_http_request_t * r, const char * key)
Definition at line 56 of file multipart_helpers.c.
References brix_http_query_has(), and key.
Referenced by s3_dispatch_after_auth().
s3_metrics_finalize_request_method()
void s3_metrics_finalize_request_method (ngx_http_request_t * r, ngx_uint_t method_slot, ngx_int_t handler_rc)
Definition at line 120 of file metrics.c.
References s3_metrics_response_method().
Referenced by s3_delete_objects_body_handler_inner(), s3_delete_objects_finish(), s3_mpu_aio_done(), s3_mpu_send_result(), s3_multipart_complete_body_handler_inner(), s3_post_object_body_handler_inner(), s3_put_finalize_bad_digest(), s3_put_finalize_client_error(), s3_put_finalize_codec_error(), s3_put_finalize_empty_ok(), s3_put_finalize_error(), s3_put_finalize_fs_error(), and s3_put_finalize_invalid_request().
s3_metrics_method_slot()
ngx_uint_t s3_metrics_method_slot (ngx_http_request_t * r)
Definition at line 57 of file metrics.c.
References brix_http_operation_find(), BRIX_S3_METHOD_OTHER, brix_s3_operations, brix_s3_operations_count, and brix_http_operation_t::metric_slot.
Referenced by ngx_http_s3_handler(), s3_delete_objects_body_handler_inner(), and s3_multipart_complete_body_handler_inner().
s3_metrics_request_method()
void s3_metrics_request_method (ngx_uint_t method_slot)
Definition at line 68 of file metrics.c.
References BRIX_S3_METHOD_OTHER, BRIX_S3_METRIC_INC, and BRIX_S3_NMETHODS.
Referenced by ngx_http_s3_handler().
s3_metrics_response_method()
void s3_metrics_response_method (ngx_http_request_t * r, ngx_uint_t method_slot, ngx_int_t handler_rc)
Definition at line 94 of file metrics.c.
References brix_http_effective_status(), and s3_metrics_response_status().
Referenced by s3_metrics_finalize_request_method(), and s3_metrics_return_method().
s3_metrics_response_status()
void s3_metrics_response_status (ngx_uint_t method_slot, ngx_uint_t http_status)
Definition at line 78 of file metrics.c.
References brix_http_status_class(), brix_metric_err_from_http_status(), brix_metric_op_done(), BRIX_PROTO_S3, BRIX_S3_METHOD_OTHER, BRIX_S3_METRIC_INC, BRIX_S3_NMETHODS, and s3_unified_op().
Referenced by s3_metrics_response_method().
s3_metrics_return_method()
ngx_int_t s3_metrics_return_method (ngx_http_request_t * r, ngx_uint_t method_slot, ngx_int_t handler_rc)
Definition at line 112 of file metrics.c.
References s3_metrics_response_method().
Referenced by ngx_http_s3_handler(), and s3_dispatch_after_auth().
s3_multipart_complete_body_handler()
void s3_multipart_complete_body_handler (ngx_http_request_t * r)
Definition at line 56 of file multipart_complete_body.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, and s3_multipart_complete_body_handler_inner().
Referenced by s3_dispatch_after_auth().
s3_object_crc64nvme_b64()
ngx_int_t s3_object_crc64nvme_b64 (ngx_http_request_t * r, int fd, const char * path, ngx_flag_t cache_only, char * out, size_t outsz)
Definition at line 169 of file util.c.
References brix_integrity_opts_t::allow_xattr_cache, brix_integrity_get_fd(), brix_integrity_info_t::hex, brix_integrity_opts_t::no_compute, brix_integrity_opts_t::require_regular_file, and brix_integrity_opts_t::update_xattr_cache.
Referenced by s3_mpu_assemble().
s3_post_object_body_handler()
void s3_post_object_body_handler (ngx_http_request_t * r)
Definition at line 219 of file post_object.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, and s3_post_object_body_handler_inner().
Referenced by s3_dispatch_after_auth().
s3_put_body_handler()
void s3_put_body_handler (ngx_http_request_t * r)
Definition at line 178 of file put.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, and s3_put_body_inner().
Referenced by s3_dispatch_after_auth().
s3_put_checksum_apply()
s3_cksum_result_t s3_put_checksum_apply (ngx_http_request_t * r, const char * fs_path, const char * root_canon)
Definition at line 274 of file checksum.c.
References s3_cksum_desc_t::alg_name, brix_vfs_close(), brix_vfs_file_fd(), s3_cksum_desc_t::header, s3_checksum_b64(), S3_CHECKSUM_B64_MAX, S3_CKSUM_CONFLICT, S3_CKSUM_DEFAULT_IDX, S3_CKSUM_ERROR, S3_CKSUM_MISMATCH, S3_CKSUM_OK, s3_cksum_table, s3_cksum_vfs_open(), s3_cksum_vfs_unlink(), S3_HDR_CHECKSUM_TYPE, s3_put_select_algo(), and s3_set_header().
Referenced by s3_put_checksum_failed().
s3_put_is_exclusive_create()
int s3_put_is_exclusive_create (ngx_http_request_t * r)
Definition at line 197 of file conditional.c.
Referenced by s3_dispatch_after_auth().
s3_put_precondition()
ngx_int_t s3_put_precondition (ngx_http_request_t * r, const char * root_canon, const char * fs_path)
Definition at line 144 of file conditional.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_HTTP_COND_WEAK_EQUIV, brix_http_eval_preconditions(), BRIX_PROTO_S3, brix_vfs_ctx_init(), ngx_http_s3_loc_conf_t::cache_root_canon, ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::identity, brix_vfs_stat_t::is_regular, brix_vfs_stat_t::mtime, ngx_http_brix_s3_module, brix_vfs_ctx_t::pool, s3_send_precondition_failed(), and brix_vfs_stat_t::size.
Referenced by s3_dispatch_after_auth().
s3_put_trailer_checksum_apply()
s3_cksum_result_t s3_put_trailer_checksum_apply (ngx_http_request_t * r, const char * fs_path, const char * root_canon, const char * algo_token, const char * value)
Definition at line 328 of file checksum.c.
References s3_cksum_desc_t::alg_name, brix_vfs_close(), brix_vfs_file_fd(), s3_cksum_desc_t::header, s3_checksum_b64(), S3_CHECKSUM_B64_MAX, s3_cksum_by_token(), S3_CKSUM_CONFLICT, S3_CKSUM_ERROR, S3_CKSUM_MISMATCH, S3_CKSUM_OK, s3_cksum_vfs_open(), s3_cksum_vfs_unlink(), S3_HDR_CHECKSUM_TYPE, and s3_set_header().
Referenced by s3_chunk_finalize().
s3_resolve_key()
int s3_resolve_key (const char * root, const char * key, char * out, size_t outsz)
Definition at line 77 of file util.c.
References brix_http_resolve_path(), key, and PATH_MAX.
Referenced by s3_delete_objects_body_handler_inner(), s3_dispatch_after_auth(), s3_handle_copy_object(), and s3_post_object_body_handler_inner().
s3_send_xml_error()
ngx_int_t s3_send_xml_error (ngx_http_request_t * r, ngx_uint_t status, const char * code, const char * message)
Definition at line 122 of file util.c.
References brix_http_send_xml_error(), BRIX_S3_EVENT_INTERNAL_ERROR, and BRIX_S3_METRIC_INC.
Referenced by s3_delete_objects_body_handler_inner(), s3_dispatch_after_auth(), s3_fail(), s3_handle_copy_object(), s3_handle_delete(), s3_handle_get(), s3_handle_get_cors(), s3_handle_list_parts(), s3_handle_multipart_abort(), s3_handle_upload_part_copy(), s3_multipart_complete_body_handler_inner(), s3_post_error(), s3_put_finalize_bad_digest(), s3_put_finalize_client_error(), s3_put_finalize_codec_error(), s3_put_finalize_fs_error(), s3_put_finalize_invalid_request(), s3_put_object_tagging_body_handler(), s3_reject_bad_amz_date(), s3_reject_clock_skew(), s3_send_precondition_failed(), s3_verify_bearer(), and s3_verify_sigv4().
s3_set_header()
ngx_int_t s3_set_header (ngx_http_request_t * r, const char * key, const char * val)
Definition at line 55 of file util.c.
References brix_http_set_header(), and key.
Referenced by s3_chunk_finalize(), s3_echo_object_checksums(), s3_echo_user_metadata(), s3_handle_head_bucket(), s3_mpu_send_result(), s3_post_send_success(), s3_post_write_object(), s3_put_aio_done(), s3_put_body_inner(), s3_put_checksum_apply(), s3_put_trailer_checksum_apply(), and s3_send_not_modified().
s3_thread_pool()
ngx_thread_pool_t * s3_thread_pool (ngx_http_s3_loc_conf_t * cf)
Definition at line 22 of file put_aio.c.
References ngx_http_s3_loc_conf_t::common, ngx_http_brix_shared_conf_t::thread_pool, and ngx_http_brix_shared_conf_t::thread_pool_name.
Referenced by s3_multipart_complete_body_handler_inner(), s3_put_body_inner(), and s3_put_streaming().
s3_verify_sigv4()
ngx_int_t s3_verify_sigv4 (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, brix_identity_t * identity)
Definition at line 360 of file auth_sigv4_verify.c.
References ngx_http_s3_loc_conf_t::access_key, sigv4_components_t::akid, ngx_http_s3_loc_conf_t::allow_unsigned_session_token, sigv4_components_t::amz_date, sigv4_components_t::amz_expires, brix_identity_t::auth_method, BRIX_AUTHN_NONE, BRIX_AUTHN_S3KEY, brix_hex_encode(), brix_hmac_sha256(), brix_http_urlencode(), brix_identity_set_subject(), BRIX_S3_AUTH_ANONYMOUS, BRIX_S3_AUTH_BAD_DATE, BRIX_S3_AUTH_BAD_KEY, BRIX_S3_AUTH_INTERNAL_ERROR, BRIX_S3_AUTH_MALFORMED, BRIX_S3_AUTH_MISSING, BRIX_S3_AUTH_SIG_MISMATCH, BRIX_S3_AUTH_SIGV4_OK, brix_sha256(), brix_str_cbuf(), build_canonical_headers(), build_canonical_qs(), sigv4_components_t::date, get_header(), ngx_http_s3_req_ctx_t::have_sigv4, ngx_http_brix_s3_module, parse_authorization(), parse_presigned_authorization(), sigv4_components_t::presigned, sigv4_components_t::region, s3_bearer_present(), s3_check_header_clock_skew(), s3_check_presigned_future_skew(), S3_MAX_KEY, s3_parse_amz_datetime(), s3_record_auth_result(), s3_reject_bad_amz_date(), s3_request_has_session_token(), s3_send_xml_error(), s3_signed_headers_contains(), s3_sigv4_derive_signing_key_cached(), s3_verify_bearer(), ngx_http_s3_loc_conf_t::secret_key, sigv4_components_t::signature, sigv4_components_t::signed_hdrs, ngx_http_s3_req_ctx_t::sigv4_amz_date, ngx_http_s3_req_ctx_t::sigv4_scope, ngx_http_s3_req_ctx_t::sigv4_seed_signature, ngx_http_s3_req_ctx_t::sigv4_signing_key, ngx_http_s3_loc_conf_t::token_enable, and ngx_http_s3_loc_conf_t::verify_chunk_signatures.
Referenced by ngx_http_s3_handler().
Variable Documentation
brix_s3_operations
const brix_http_operation_t brix_s3_operations[] extern
Definition at line 17 of file operation_table.c.
Referenced by s3_handle_options(), and s3_metrics_method_slot().
brix_s3_operations_count
const ngx_uint_t brix_s3_operations_count extern
Definition at line 35 of file operation_table.c.
Referenced by s3_handle_options(), and s3_metrics_method_slot().
ngx_http_brix_s3_module
ngx_module_t ngx_http_brix_s3_module extern
Definition at line 550 of file module.c.
Referenced by brix_acc_http_both(), brix_acc_http_set_audit(), brix_acc_http_set_authdb(), brix_acc_http_set_format(), brix_http_protocol_variable(), brix_http_set_ktls(), brix_proto_mask(), ngx_http_s3_handler(), ngx_http_s3_postconfiguration(), s3_apply_put_tagging_header(), s3_apply_put_user_metadata(), s3_build_chunk_verify(), s3_build_vfs_ctx(), s3_cksum_vfs_open(), s3_cksum_vfs_unlink(), s3_commit_put(), s3_copy_vfs_ctx(), s3_dashboard_identity(), s3_delete_objects_body_handler(), s3_delete_objects_body_handler_inner(), s3_delete_one(), s3_echo_user_metadata(), s3_handle_get(), s3_multipart_complete_body_handler(), s3_multipart_complete_body_handler_inner(), s3_post_object_body_handler(), s3_post_object_body_handler_inner(), s3_put_body_handler(), s3_put_body_inner(), s3_put_object_tagging_body_handler(), s3_put_precondition(), s3_tag_vfs_ctx(), s3_user_meta_copy(), s3_user_meta_vfs_ctx(), s3_verify_sigv4(), and s3_vfs_ctx().