nginx-xrootd: src/fs/cache/origin/s3_transport_setup.c File Reference
s3_transport_setup.c File Reference
#include "s3_transport.h"
#include "s3_transport_internal.h"
#include <ngx_config.h>
#include <ngx_core.h>
#include "fs/path/path.h"
#include <curl/curl.h>
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
Functions
void brix_origin_trace_set (int info_on)
void brix_s3_origin_timeouts_set (long connect_ms, long stall_secs, long stall_bytes_per_s, long attempt_ms)
void brix_s3_origin_reuse_set (int reuse_on)
void brix_s3_origin_http_version_set (int ver)
int brix_s3_origin_http_version_supported (int ver)
static void s3o_apply_http_version (CURL *curl)
const char * s3o_negotiated_proto (CURL *curl)
static struct curl_slist * s3o_build_slist (const char *headers)
void s3o_trace (const s3o_trace_t *t)
static void s3o_curl_thread_free (void *handle)
static void s3o_curl_key_init (void)
CURL * s3o_curl_acquire (void)
static void s3o_apply_ca (CURL *curl, const char *ca_path)
struct curl_slist * s3o_build_headers (const s3o_request_t *req)
static void s3o_apply_timeouts (CURL *curl, int timeout_ms)
static void s3o_apply_reuse (CURL *curl)
static void s3o_apply_method (CURL *curl, const s3o_request_t *req)
static void s3o_apply_tls (CURL *curl, const s3o_request_t *req)
void s3o_configure (CURL *curl, const s3o_request_t *req, s3o_resp_t *r, struct curl_slist *slist)
Variables
static int g_origin_trace_info
static long g_origin_connect_ms
static long g_origin_stall_secs
static long g_origin_stall_bytes
static long g_origin_attempt_ms
static int g_origin_no_reuse
static int g_origin_http_version
static pthread_key_t g_curl_key
static pthread_once_t g_curl_key_once = PTHREAD_ONCE_INIT
Function Documentation
brix_origin_trace_set()
void brix_origin_trace_set (int info_on)
Definition at line 34 of file s3_transport_setup.c.
References g_origin_trace_info.
Referenced by cvmfs_merge_upstreams().
brix_s3_origin_http_version_set()
void brix_s3_origin_http_version_set (int ver)
Definition at line 89 of file s3_transport_setup.c.
References g_origin_http_version.
Referenced by cvmfs_merge_resilience().
brix_s3_origin_http_version_supported()
int brix_s3_origin_http_version_supported (int ver)
Definition at line 95 of file s3_transport_setup.c.
Referenced by cvmfs_merge_resilience().
brix_s3_origin_reuse_set()
void brix_s3_origin_reuse_set (int reuse_on)
Definition at line 76 of file s3_transport_setup.c.
References g_origin_no_reuse.
Referenced by cvmfs_merge_resilience().
brix_s3_origin_timeouts_set()
void brix_s3_origin_timeouts_set (long connect_ms, long stall_secs, long stall_bytes_per_s, long attempt_ms)
Definition at line 57 of file s3_transport_setup.c.
References g_origin_attempt_ms, g_origin_connect_ms, g_origin_stall_bytes, and g_origin_stall_secs.
Referenced by cvmfs_merge_resilience().
s3o_apply_ca()
static void s3o_apply_ca (CURL * curl, const char * ca_path) static
Definition at line 300 of file s3_transport_setup.c.
References stat().
Referenced by s3o_apply_tls().
s3o_apply_http_version()
static void s3o_apply_http_version (CURL * curl) static
Definition at line 121 of file s3_transport_setup.c.
References g_origin_http_version.
Referenced by s3o_configure().
s3o_apply_method()
static void s3o_apply_method (CURL * curl, const s3o_request_t * req) static
Definition at line 404 of file s3_transport_setup.c.
References s3o_request_t::body, s3o_request_t::body_len, and s3o_request_t::method.
Referenced by s3o_configure().
s3o_apply_reuse()
static void s3o_apply_reuse (CURL * curl) static
Definition at line 379 of file s3_transport_setup.c.
References g_origin_no_reuse.
Referenced by s3o_configure().
s3o_apply_timeouts()
static void s3o_apply_timeouts (CURL * curl, int timeout_ms) static
Definition at line 350 of file s3_transport_setup.c.
References g_origin_attempt_ms, g_origin_connect_ms, g_origin_stall_bytes, and g_origin_stall_secs.
Referenced by s3o_configure().
s3o_apply_tls()
static void s3o_apply_tls (CURL * curl, const s3o_request_t * req) static
Definition at line 438 of file s3_transport_setup.c.
References s3o_request_t::client_cert_pem, s3o_apply_ca(), s3o_request_t::tctx, and s3o_request_t::tls.
Referenced by s3o_configure().
s3o_build_headers()
struct curl_slist * s3o_build_headers (const s3o_request_t * req)
Definition at line 326 of file s3_transport_setup.c.
References s3o_request_t::headers, s3o_request_t::host, s3o_request_t::port, and s3o_build_slist().
Referenced by s3o_request_impl().
s3o_build_slist()
static struct curl_slist * s3o_build_slist (const char * headers) static
Definition at line 176 of file s3_transport_setup.c.
Referenced by s3o_build_headers().
s3o_configure()
void s3o_configure (CURL * curl, const s3o_request_t * req, s3o_resp_t * r, struct curl_slist * slist)
Definition at line 464 of file s3_transport_setup.c.
References s3o_request_t::host, s3o_request_t::path_and_query, s3o_request_t::port, s3o_apply_http_version(), s3o_apply_method(), s3o_apply_reuse(), s3o_apply_timeouts(), s3o_apply_tls(), s3o_header_cb(), s3o_write_cb(), s3o_request_t::timeout_ms, and s3o_request_t::tls.
Referenced by s3o_request_impl().
s3o_curl_acquire()
CURL * s3o_curl_acquire (void)
Definition at line 266 of file s3_transport_setup.c.
References g_curl_key, g_curl_key_once, and s3o_curl_key_init().
Referenced by s3o_request_impl().
s3o_curl_key_init()
static void s3o_curl_key_init (void) static
Definition at line 258 of file s3_transport_setup.c.
References g_curl_key, and s3o_curl_thread_free().
Referenced by s3o_curl_acquire().
s3o_curl_thread_free()
static void s3o_curl_thread_free (void * handle) static
Definition at line 250 of file s3_transport_setup.c.
Referenced by s3o_curl_key_init().
s3o_negotiated_proto()
const char * s3o_negotiated_proto (CURL * curl)
Definition at line 155 of file s3_transport_setup.c.
Referenced by s3o_request_impl().
s3o_trace()
void s3o_trace (const s3o_trace_t * t)
Definition at line 206 of file s3_transport_setup.c.
References brix_sanitize_log_string(), s3o_trace_t::bytes, s3o_trace_t::dur_ms, s3o_trace_t::err, g_origin_trace_info, s3o_trace_t::host, s3o_trace_t::method, s3o_trace_t::path, s3o_trace_t::port, s3o_trace_t::proto, and s3o_trace_t::status.
Referenced by s3o_request_impl().
Variable Documentation
g_curl_key
pthread_key_t g_curl_key static
Definition at line 246 of file s3_transport_setup.c.
Referenced by s3o_curl_acquire(), and s3o_curl_key_init().
g_curl_key_once
pthread_once_t g_curl_key_once = PTHREAD_ONCE_INIT static
Definition at line 247 of file s3_transport_setup.c.
Referenced by s3o_curl_acquire().
g_origin_attempt_ms
long g_origin_attempt_ms static
Definition at line 54 of file s3_transport_setup.c.
Referenced by brix_s3_origin_timeouts_set(), and s3o_apply_timeouts().
g_origin_connect_ms
long g_origin_connect_ms static
Definition at line 51 of file s3_transport_setup.c.
Referenced by brix_s3_origin_timeouts_set(), and s3o_apply_timeouts().
g_origin_http_version
int g_origin_http_version static
Definition at line 86 of file s3_transport_setup.c.
Referenced by brix_s3_origin_http_version_set(), and s3o_apply_http_version().
g_origin_no_reuse
int g_origin_no_reuse static
Definition at line 73 of file s3_transport_setup.c.
Referenced by brix_s3_origin_reuse_set(), and s3o_apply_reuse().
g_origin_stall_bytes
long g_origin_stall_bytes static
Definition at line 53 of file s3_transport_setup.c.
Referenced by brix_s3_origin_timeouts_set(), and s3o_apply_timeouts().
g_origin_stall_secs
long g_origin_stall_secs static
Definition at line 52 of file s3_transport_setup.c.
Referenced by brix_s3_origin_timeouts_set(), and s3o_apply_timeouts().
g_origin_trace_info
int g_origin_trace_info static
Definition at line 31 of file s3_transport_setup.c.
Referenced by brix_origin_trace_set(), and s3o_trace().