nginx-xrootd: src/protocols/s3/s3_handler_internal.h File Reference
s3_handler_internal.h File Reference
#include "s3.h"
#include "auth/authz/acc/acc.h"
Functions
brix_acc_op_t s3_method_aop (ngx_http_request_t *r)
ngx_int_t s3_dispatch_after_auth (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, ngx_http_s3_req_ctx_t *s3ctx, ngx_uint_t method_slot, int is_list_request, ngx_flag_t is_post_object_form)
ngx_int_t s3_dispatch_object_method (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, ngx_http_s3_req_ctx_t *s3ctx, ngx_uint_t method_slot, const u_char *key, char *fs_path)
ngx_int_t s3_reject_write_disabled (ngx_http_request_t *r, ngx_uint_t method_slot)
ngx_int_t s3_read_body_metric (ngx_http_request_t *r, ngx_uint_t method_slot, ngx_http_client_body_handler_pt handler)
Function Documentation
s3_dispatch_after_auth()
ngx_int_t s3_dispatch_after_auth (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, ngx_http_s3_req_ctx_t * s3ctx, ngx_uint_t method_slot, int is_list_request, ngx_flag_t is_post_object_form)
Definition at line 311 of file handler_dispatch.c.
References key, PATH_MAX, s3_check_token_scope(), s3_dispatch_empty_key(), s3_dispatch_object_method(), s3_dispatch_parse_uri(), s3_handle_list(), S3_MAX_KEY, s3_metrics_return_method(), and s3_resolve_object_key().
Referenced by ngx_http_s3_handler().
s3_dispatch_object_method()
ngx_int_t s3_dispatch_object_method (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, ngx_http_s3_req_ctx_t * s3ctx, ngx_uint_t method_slot, const u_char * key, char * fs_path)
Definition at line 258 of file handler_object_route.c.
References BRIX_S3_EVENT_METHOD_NOT_ALLOWED, BRIX_S3_METRIC_INC, key, s3_dispatch_object_delete(), s3_dispatch_object_get(), s3_dispatch_object_post(), s3_dispatch_object_put(), s3_handle_head(), and s3_metrics_return_method().
Referenced by s3_dispatch_after_auth().
s3_method_aop()
brix_acc_op_t s3_method_aop (ngx_http_request_t * r)
Definition at line 57 of file handler.c.
References BRIX_AOP_CREATE, BRIX_AOP_DELETE, BRIX_AOP_READ, and BRIX_AOP_STAT.
Referenced by s3_acc_check(), and s3_check_token_scope().
s3_read_body_metric()
ngx_int_t s3_read_body_metric (ngx_http_request_t * r, ngx_uint_t method_slot, ngx_http_client_body_handler_pt handler)
Definition at line 200 of file handler_dispatch.c.
References brix_http_read_body(), handler, and s3_metrics_return_method().
Referenced by s3_dispatch_empty_post(), s3_dispatch_object_post(), and s3_dispatch_object_put().
s3_reject_write_disabled()
ngx_int_t s3_reject_write_disabled (ngx_http_request_t * r, ngx_uint_t method_slot)
Definition at line 190 of file handler_dispatch.c.
References BRIX_S3_EVENT_WRITE_DISABLED, BRIX_S3_METRIC_INC, s3_metrics_return_method(), and s3_send_xml_error().
Referenced by s3_dispatch_empty_post(), s3_dispatch_object_delete(), s3_dispatch_object_post(), and s3_dispatch_object_put().