nginx-xrootd: src/protocols/s3/s3_handlers.h File Reference
s3_handlers.h File Reference
#include "s3.h"
Functions
ngx_int_t s3_handle_get (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf)
ngx_int_t s3_handle_list (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf)
ngx_int_t s3_handle_list_v1 (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf)
ngx_int_t s3_handle_head_bucket (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf)
ngx_int_t s3_handle_get_bucket_location (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf)
int s3_walk (ngx_log_t *log, const char *root, const char *dir_path, const char *key_prefix, const char *filter_prefix, const char *delimiter, ngx_array_t *entries, int max_entries)
int entry_cmp (const void *a, const void *b)
ngx_int_t s3_entry_fill_stat (ngx_pool_t *pool, ngx_log_t *log, const char *root, s3_entry_t *e)
int s3_list_parse_max_keys (ngx_http_request_t *r, int default_max)
ngx_int_t s3_list_collect_sorted (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const char *prefix, const char *delimiter, s3_entry_t **items, int *total)
int s3_list_paginate (const s3_entry_t *items, int total, const char *start_after, int max_keys, int *start_idx, int *end_idx)
ngx_int_t s3_list_emit_entries (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, s3_entry_t *items, int start_idx, int end_idx, int url_encode, int fetch_owner, u_char *xml, size_t *xml_len_io, size_t xml_capacity, int *contents_out, int *prefixes_out)
ngx_int_t s3_list_finalize (ngx_http_request_t *r, const u_char *xml, size_t xml_len, int contents, int prefixes, int truncated)
ngx_int_t s3_handle_head (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf)
Function Documentation
entry_cmp()
int entry_cmp (const void * a, const void * b)
Definition at line 53 of file list_walk.c.
References key.
Referenced by s3_list_collect_sorted().
s3_entry_fill_stat()
ngx_int_t s3_entry_fill_stat (ngx_pool_t * pool, ngx_log_t * log, const char * root, s3_entry_t * e)
Definition at line 455 of file list_walk.c.
References BRIX_PROTO_S3, brix_vfs_ctx_init(), brix_vfs_probe(), s3_entry_t::etag, s3_entry_t::is_prefix, brix_vfs_stat_t::is_regular, s3_entry_t::key, log, brix_vfs_stat_t::mtime, s3_entry_t::mtime, PATH_MAX, s3_etag(), brix_vfs_stat_t::size, s3_entry_t::size, and stat().
Referenced by s3_list_emit_entries().
s3_handle_get()
ngx_int_t s3_handle_get (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf)
Definition at line 492 of file object.c.
References brix_vfs_close(), ngx_http_s3_loc_conf_t::common, ngx_http_brix_shared_conf_t::compress, s3_get_serve_t::compress, s3_get_serve_t::fh, s3_get_serve_t::fs_path, s3_get_serve_t::identity, brix_vfs_stat_t::mtime, s3_get_cache_fill(), s3_get_check_residency(), s3_get_echo_headers(), s3_get_resolve(), s3_get_resolve_identity(), s3_get_serve(), s3_get_serve_multirange(), s3_get_serve_offload(), s3_get_serve_zip_member(), s3_handle_conditional(), s3_vfs_ctx(), brix_vfs_stat_t::size, s3_get_serve_t::vst, and xrdhttp_request_is_multirange().
Referenced by s3_dispatch_object_get(), and s3_get_reenter().
s3_handle_get_bucket_location()
ngx_int_t s3_handle_get_bucket_location (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf)
Definition at line 180 of file object_meta.c.
References brix_http_send_xml_buffer(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_ADD, BRIX_S3_METRIC_INC, ngx_http_s3_loc_conf_t::region, and XML_APPEND.
Referenced by s3_dispatch_bucket_get().
s3_handle_head()
ngx_int_t s3_handle_head (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf)
Definition at line 27 of file object_meta.c.
References brix_http_errno_to_status(), brix_http_set_file_headers(), brix_http_set_header(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_EVENT_NO_SUCH_KEY, BRIX_S3_METRIC_INC, BRIX_SD_RES_NEARLINE, BRIX_SD_RES_OFFLINE, brix_vfs_close(), brix_vfs_file_fd(), BRIX_VFS_O_READ, brix_vfs_open(), brix_vfs_residency(), brix_vfs_stat_t::is_directory, brix_vfs_stat_t::mtime, s3_echo_object_checksums(), s3_echo_user_metadata(), s3_fail(), s3_handle_conditional(), s3_vfs_ctx(), and brix_vfs_stat_t::size.
Referenced by s3_dispatch_object_method().
s3_handle_head_bucket()
ngx_int_t s3_handle_head_bucket (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf)
Definition at line 133 of file object_meta.c.
References BRIX_S3_EVENT_INVALID_URI, BRIX_S3_METRIC_INC, ngx_http_s3_loc_conf_t::common, ngx_memcpy, region, ngx_http_s3_loc_conf_t::region, ngx_http_brix_shared_conf_t::root_canon, s3_set_header(), and stat().
Referenced by s3_dispatch_empty_key().
s3_handle_list()
ngx_int_t s3_handle_list (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf)
Definition at line 149 of file list_objects_v2.c.
References b64url_encode(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, ngx_http_s3_loc_conf_t::bucket, key, s3_list_collect_sorted(), s3_list_decode_params(), s3_list_emit_entries(), s3_list_emit_header(), s3_list_finalize(), s3_list_paginate(), S3_MAX_KEY, S3_MAX_PARAM, and XML_APPEND.
Referenced by s3_dispatch_after_auth().
s3_handle_list_v1()
ngx_int_t s3_handle_list_v1 (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf)
Definition at line 33 of file list_objects_v1.c.
References brix_http_query_get(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, ngx_http_s3_loc_conf_t::bucket, key, ngx_http_s3_loc_conf_t::max_keys, s3_list_collect_sorted(), s3_list_emit_entries(), s3_list_finalize(), s3_list_paginate(), s3_list_parse_max_keys(), S3_LIST_QUERY_FLAGS, S3_MAX_KEY, S3_MAX_PARAM, XML_APPEND, and XML_APPEND_ELEM.
Referenced by s3_dispatch_bucket_get().
s3_list_collect_sorted()
ngx_int_t s3_list_collect_sorted (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const char * prefix, const char * delimiter, s3_entry_t ** items, int * total)
Definition at line 73 of file list_common.c.
References ngx_http_s3_loc_conf_t::common, entry_cmp(), ngx_http_s3_loc_conf_t::list_cache, ngx_http_s3_loc_conf_t::list_cache_ttl, ngx_http_brix_shared_conf_t::root, s3_list_cache_get(), s3_list_cache_put(), S3_LIST_MAX_ENTRIES, s3_walk(), and stat().
Referenced by s3_handle_list(), and s3_handle_list_v1().
s3_list_emit_entries()
ngx_int_t s3_list_emit_entries (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, s3_entry_t * items, int start_idx, int end_idx, int url_encode, int fetch_owner, u_char * xml, size_t * xml_len_io, size_t xml_capacity, int * contents_out, int * prefixes_out)
Definition at line 160 of file list_common.c.
References ngx_http_s3_loc_conf_t::access_key, brix_format_iso8601(), brix_http_urlencode(), ngx_http_s3_loc_conf_t::common, s3_entry_t::etag, s3_entry_t::is_prefix, s3_entry_t::key, s3_entry_t::mtime, ngx_http_brix_shared_conf_t::root, s3_entry_fill_stat(), S3_MAX_KEY, s3_entry_t::size, XML_APPEND, and XML_APPEND_ELEM.
Referenced by s3_handle_list(), and s3_handle_list_v1().
s3_list_finalize()
ngx_int_t s3_list_finalize (ngx_http_request_t * r, const u_char * xml, size_t xml_len, int contents, int prefixes, int truncated)
Definition at line 232 of file list_common.c.
References brix_http_send_xml_buffer(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_ADD, and BRIX_S3_METRIC_INC.
Referenced by s3_handle_list(), and s3_handle_list_v1().
s3_list_paginate()
int s3_list_paginate (const s3_entry_t * items, int total, const char * start_after, int max_keys, int * start_idx, int * end_idx)
Definition at line 126 of file list_common.c.
References key.
Referenced by s3_handle_list(), and s3_handle_list_v1().
s3_list_parse_max_keys()
int s3_list_parse_max_keys (ngx_http_request_t * r, int default_max)
Definition at line 38 of file list_common.c.
References brix_http_query_get(), mk(), and S3_LIST_QUERY_FLAGS.
Referenced by s3_handle_list_v1(), and s3_list_decode_params().
s3_walk()
int s3_walk (ngx_log_t * log, const char * root, const char * dir_path, const char * key_prefix, const char * filter_prefix, const char * delimiter, ngx_array_t * entries, int max_entries)
Definition at line 425 of file list_walk.c.
References s3_walk_ctx_t::del_len, s3_walk_ctx_t::delimiter, s3_walk_ctx_t::entries, s3_walk_ctx_t::filter_prefix, s3_walk_ctx_t::fp_len, log, s3_walk_ctx_t::log, s3_walk_ctx_t::max_entries, s3_walk_ctx_t::root, and s3_walk_run().
Referenced by s3_list_collect_sorted().