nginx-xrootd: src/protocols/s3/s3_ops.h File Reference
s3_ops.h File Reference
Macros
#define S3_HDR_CHECKSUM_CRC64NVME "x-amz-checksum-crc64nvme"
#define S3_HDR_CHECKSUM_TYPE "x-amz-checksum-type"
#define S3_CRC64NVME_B64_MAX 16
#define S3_HDR_SDK_CHECKSUM_ALGO "x-amz-sdk-checksum-algorithm"
#define S3_HDR_CHECKSUM_MODE "x-amz-checksum-mode"
#define S3_CHECKSUM_B64_MAX 48
Enumerations
enum s3_cksum_result_t { S3_CKSUM_OK = 0 , S3_CKSUM_MISMATCH , S3_CKSUM_CONFLICT , S3_CKSUM_ERROR }
Functions
int s3_has_query_flag (ngx_http_request_t *r, const char *key)
int s3_get_query_param (ngx_http_request_t *r, const char *key, char *out, size_t outsz)
void s3_get_mpu_dir (const char *fs_path, const char *upload_id, char *out_dir, size_t outsz)
ngx_int_t s3_handle_multipart_initiate (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, const char *key_str)
ngx_int_t s3_handle_multipart_abort (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, const char *upload_id)
void s3_multipart_complete_body_handler (ngx_http_request_t *r)
ngx_int_t s3_handle_list_parts (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, const char *key_str)
ngx_int_t s3_handle_list_multipart_uploads (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf)
ngx_int_t s3_handle_upload_part_copy (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, const char *upload_id, int part_num)
ngx_int_t s3_handle_copy_object (ngx_http_request_t *r, const char *dst_fs_path, ngx_http_s3_loc_conf_t *cf)
void s3_delete_objects_body_handler (ngx_http_request_t *r)
void s3_etag (const struct stat *st, char *buf, size_t bufsz)
void s3_build_vfs_ctx (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, brix_vfs_ctx_t *vctx)
void s3_vfs_bind_deleg (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, brix_vfs_ctx_t *vctx)
ngx_int_t s3_object_crc64nvme_b64 (ngx_http_request_t *r, int fd, const char *path, ngx_flag_t cache_only, char *out, size_t outsz)
ngx_int_t s3_checksum_b64 (ngx_http_request_t *r, int fd, const char *path, const char *alg_name, ngx_flag_t cache_only, char *out, size_t outsz)
s3_cksum_result_t s3_put_checksum_apply (ngx_http_request_t *r, const char *fs_path, const char *root_canon)
s3_cksum_result_t s3_put_trailer_checksum_apply (ngx_http_request_t *r, const char *fs_path, const char *root_canon, const char *algo_token, const char *value)
s3_cksum_result_t s3_content_md5_verify (ngx_http_request_t *r, const char *fs_path, const char *root_canon)
void s3_echo_object_checksums (ngx_http_request_t *r, int fd, const char *path)
Macro Definition Documentation
S3_CHECKSUM_B64_MAX
#define S3_CHECKSUM_B64_MAX 48
Definition at line 103 of file s3_ops.h.
S3_CRC64NVME_B64_MAX
#define S3_CRC64NVME_B64_MAX 16
Definition at line 83 of file s3_ops.h.
S3_HDR_CHECKSUM_CRC64NVME
#define S3_HDR_CHECKSUM_CRC64NVME "x-amz-checksum-crc64nvme"
Definition at line 80 of file s3_ops.h.
S3_HDR_CHECKSUM_MODE
#define S3_HDR_CHECKSUM_MODE "x-amz-checksum-mode"
Definition at line 101 of file s3_ops.h.
S3_HDR_CHECKSUM_TYPE
#define S3_HDR_CHECKSUM_TYPE "x-amz-checksum-type"
Definition at line 81 of file s3_ops.h.
S3_HDR_SDK_CHECKSUM_ALGO
#define S3_HDR_SDK_CHECKSUM_ALGO "x-amz-sdk-checksum-algorithm"
Definition at line 100 of file s3_ops.h.
Enumeration Type Documentation
s3_cksum_result_t
enum s3_cksum_result_t
Enumerator
S3_CKSUM_OK
S3_CKSUM_MISMATCH
S3_CKSUM_CONFLICT
S3_CKSUM_ERROR
Definition at line 106 of file s3_ops.h.
Function Documentation
s3_build_vfs_ctx()
void s3_build_vfs_ctx (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, brix_vfs_ctx_t * vctx)
Definition at line 27 of file util.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_S3, brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_bind_backend_mint(), brix_vfs_ctx_init(), ngx_http_s3_loc_conf_t::cache_root_canon, ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, brix_vfs_ctx_t::pool, ngx_http_brix_shared_conf_t::root_canon, s3_vfs_bind_deleg(), ngx_http_brix_shared_conf_t::storage_credential_dir, ngx_http_brix_shared_conf_t::storage_credential_fallback, ngx_http_brix_shared_conf_t::storage_credential_mint_ca_cert, ngx_http_brix_shared_conf_t::storage_credential_mint_ca_key, and ngx_http_brix_shared_conf_t::storage_credential_mint_ttl.
Referenced by lp_scan_staged_parts(), mpu_collect(), mpu_scan_entry(), s3_handle_list_parts(), s3_handle_multipart_abort(), s3_mpu_reap_one_entry(), s3_mpu_reap_stale(), s3_multipart_complete_body_handler_inner(), s3_post_write_object(), s3_put_try_sentinel(), s3_resolve_copy_source(), s3_resolve_part_target(), s3put_emit_etag(), s3put_ensure_parent_dirs(), and s3put_open_target().
s3_checksum_b64()
ngx_int_t s3_checksum_b64 (ngx_http_request_t * r, int fd, const char * path, const char * alg_name, ngx_flag_t cache_only, char * out, size_t outsz)
Definition at line 127 of file checksum.c.
References brix_integrity_opts_t::allow_xattr_cache, brix_hex_from_char(), brix_integrity_get_fd(), brix_integrity_info_t::hex, brix_integrity_opts_t::no_compute, brix_integrity_opts_t::require_regular_file, and brix_integrity_opts_t::update_xattr_cache.
Referenced by s3_echo_object_checksums(), s3_put_checksum_apply(), and s3_put_trailer_checksum_apply().
s3_content_md5_verify()
s3_cksum_result_t s3_content_md5_verify (ngx_http_request_t * r, const char * fs_path, const char * root_canon)
Definition at line 338 of file checksum.c.
References brix_http_find_header(), brix_integrity_get_fd(), brix_vfs_close(), brix_vfs_file_fd(), brix_integrity_info_t::hex, brix_integrity_opts_t::require_regular_file, S3_CKSUM_CONFLICT, S3_CKSUM_ERROR, S3_CKSUM_MISMATCH, S3_CKSUM_OK, s3_cksum_vfs_open(), and s3_cksum_vfs_unlink().
Referenced by s3_put_checksum_failed().
s3_delete_objects_body_handler()
void s3_delete_objects_body_handler (ngx_http_request_t * r)
Definition at line 507 of file delete_objects.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, and s3_delete_objects_body_handler_inner().
Referenced by s3_dispatch_empty_post().
s3_echo_object_checksums()
void s3_echo_object_checksums (ngx_http_request_t * r, int fd, const char * path)
Definition at line 459 of file checksum.c.
References b64, brix_http_find_header(), s3_checksum_b64(), S3_CHECKSUM_B64_MAX, S3_CKSUM_DEFAULT_IDX, s3_cksum_table, S3_CKSUM_TABLE_N, S3_HDR_CHECKSUM_TYPE, and s3_set_header().
Referenced by s3_get_echo_headers(), and s3_handle_head().
s3_etag()
void s3_etag (const struct stat * st, char * buf, size_t bufsz)
Definition at line 156 of file util.c.
References brix_http_etag_str().
Referenced by s3_chunk_finalize(), s3_entry_fill_stat(), s3_handle_copy_object(), s3_mpu_send_result(), s3_post_write_object(), s3_put_aio_done(), s3_send_copy_part_result(), and s3put_emit_etag().
s3_get_mpu_dir()
void s3_get_mpu_dir (const char * fs_path, const char * upload_id, char * out_dir, size_t outsz)
Definition at line 87 of file multipart_helpers.c.
Referenced by s3_handle_list_parts(), s3_handle_multipart_abort(), s3_handle_multipart_initiate(), s3_multipart_complete_body_handler_inner(), s3_prepare_upload_part(), and s3_resolve_part_target().
s3_get_query_param()
int s3_get_query_param (ngx_http_request_t * r, const char * key, char * out, size_t outsz)
Definition at line 66 of file multipart_helpers.c.
References brix_http_query_get(), BRIX_HTTP_QUERY_TRUNCATE, and key.
Referenced by lp_parse_query(), mpu_parse_max_uploads(), s3_apply_put_precondition(), s3_dashboard_put_op(), s3_dispatch_object_delete(), s3_dispatch_object_get(), s3_dispatch_object_post(), s3_handle_list_multipart_uploads(), s3_handle_list_parts(), s3_multipart_complete_body_handler_inner(), and s3_prepare_upload_part().
s3_handle_copy_object()
ngx_int_t s3_handle_copy_object (ngx_http_request_t * r, const char * dst_fs_path, ngx_http_s3_loc_conf_t * cf)
Definition at line 86 of file copy.c.
References brix_format_iso8601(), brix_http_send_xml_buffer(), BRIX_S3_EVENT_ACCESS_DENIED, BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_EVENT_NO_SUCH_KEY, BRIX_S3_METRIC_INC, brix_vfs_copy(), brix_vfs_probe(), ngx_http_brix_shared_conf_t::cache_store_endpoint, ngx_http_s3_loc_conf_t::common, brix_vfs_stat_t::mtime, brix_vfs_copy_opts_t::overwrite, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, s3_apply_put_user_metadata(), s3_copy_find_header(), s3_copy_vfs_ctx(), s3_etag(), s3_fail(), s3_resolve_key(), s3_send_xml_error(), s3_user_meta_copy(), brix_vfs_stat_t::size, brix_vfs_copy_opts_t::staged_commit, and stat().
Referenced by s3_dispatch_object_put().
s3_handle_list_multipart_uploads()
ngx_int_t s3_handle_list_multipart_uploads (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf)
Definition at line 425 of file multipart_complete_list_uploads.c.
References BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, mpu_scan_t::cf, ngx_http_s3_loc_conf_t::common, mpu_page_t::end_idx, mpu_page_t::key_marker, mpu_scan_t::max, mpu_page_t::max_uploads, mpu_collect(), mpu_marker_start_idx(), MPU_MAX_LISTED_UPLOADS, mpu_parse_max_uploads(), mpu_render_and_send(), mpu_upload_entry_cmp(), mpu_scan_t::n, mpu_scan_t::r, ngx_http_brix_shared_conf_t::root, ngx_http_brix_shared_conf_t::root_canon, s3_get_query_param(), mpu_page_t::start_idx, mpu_page_t::truncated, mpu_scan_t::uploads, and mpu_page_t::uploads.
Referenced by s3_dispatch_bucket_get().
s3_handle_list_parts()
ngx_int_t s3_handle_list_parts (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, const char * key_str)
Definition at line 314 of file multipart_complete_list_parts.c.
References BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, brix_vfs_probe(), lp_page_t::end_idx, brix_vfs_stat_t::is_directory, lp_page_t::key_str, lp_parse_query(), lp_render_xml(), lp_scan_staged_parts(), lp_page_t::max_parts, MPU_MAX_PART_NUMBER, mpu_validate_upload_id(), lp_page_t::nparts, lp_page_t::part_number_marker, lp_page_t::parts, PATH_MAX, s3_build_vfs_ctx(), s3_get_mpu_dir(), s3_get_query_param(), s3_send_xml_error(), lp_page_t::start_idx, and lp_page_t::upload_id.
Referenced by s3_dispatch_object_get().
s3_handle_multipart_abort()
ngx_int_t s3_handle_multipart_abort (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, const char * upload_id)
Definition at line 17 of file multipart_abort.c.
References BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, brix_vfs_probe(), ngx_http_s3_loc_conf_t::common, mpu_rmdir_recursive(), mpu_validate_upload_id(), PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, s3_build_vfs_ctx(), s3_get_mpu_dir(), and s3_send_xml_error().
Referenced by s3_dispatch_object_delete().
s3_handle_multipart_initiate()
ngx_int_t s3_handle_multipart_initiate (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, const char * key_str)
Definition at line 38 of file multipart_initiate.c.
References brix_http_send_xml_buffer(), brix_log_safe_path(), brix_mkdir_confined_canon(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, ngx_http_s3_loc_conf_t::bucket, ngx_http_s3_loc_conf_t::common, ngx_http_s3_loc_conf_t::mpu_max_age, ngx_memcpy, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, s3_get_mpu_dir(), and s3_mpu_reap_stale().
Referenced by s3_dispatch_object_post().
s3_handle_upload_part_copy()
ngx_int_t s3_handle_upload_part_copy (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, const char * upload_id, int part_num)
Definition at line 296 of file multipart_complete_upload_part_copy.c.
References BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METRIC_INC, brix_vfs_close(), brix_vfs_file_fd(), BRIX_VFS_O_READ, brix_vfs_open(), brix_vfs_open_fd(), brix_vfs_unlink_path(), s3_upcp_req_t::cf, close(), ngx_http_s3_loc_conf_t::common, s3_upcp_req_t::fs_path, fstat(), s3_upcp_req_t::part_num, PATH_MAX, s3_upcp_req_t::r, ngx_http_brix_shared_conf_t::root_canon, s3_copy_bytes(), s3_copy_source_key(), s3_find_request_header_value(), s3_resolve_copy_source(), s3_resolve_part_target(), s3_send_copy_part_result(), s3_send_xml_error(), stat(), and s3_upcp_req_t::upload_id.
Referenced by s3_prepare_upload_part().
s3_has_query_flag()
int s3_has_query_flag (ngx_http_request_t * r, const char * key)
Definition at line 56 of file multipart_helpers.c.
References brix_http_query_has(), and key.
Referenced by s3_dispatch_bucket_get(), s3_dispatch_empty_post(), s3_dispatch_object_delete(), s3_dispatch_object_get(), s3_dispatch_object_post(), s3_dispatch_object_put(), and s3_prepare_upload_part().
s3_multipart_complete_body_handler()
void s3_multipart_complete_body_handler (ngx_http_request_t * r)
Definition at line 56 of file multipart_complete_body.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, and s3_multipart_complete_body_handler_inner().
Referenced by s3_dispatch_object_post().
s3_object_crc64nvme_b64()
ngx_int_t s3_object_crc64nvme_b64 (ngx_http_request_t * r, int fd, const char * path, ngx_flag_t cache_only, char * out, size_t outsz)
Definition at line 219 of file util.c.
References brix_integrity_opts_t::allow_xattr_cache, brix_integrity_get_fd(), brix_integrity_info_t::hex, brix_integrity_opts_t::no_compute, brix_integrity_opts_t::require_regular_file, and brix_integrity_opts_t::update_xattr_cache.
Referenced by s3_mpu_assemble().
s3_put_checksum_apply()
s3_cksum_result_t s3_put_checksum_apply (ngx_http_request_t * r, const char * fs_path, const char * root_canon)
Definition at line 266 of file checksum.c.
References s3_cksum_desc_t::alg_name, b64, brix_vfs_close(), brix_vfs_file_fd(), s3_cksum_desc_t::header, s3_checksum_b64(), S3_CHECKSUM_B64_MAX, S3_CKSUM_CONFLICT, S3_CKSUM_DEFAULT_IDX, S3_CKSUM_ERROR, S3_CKSUM_MISMATCH, S3_CKSUM_OK, s3_cksum_table, s3_cksum_vfs_open(), s3_cksum_vfs_unlink(), S3_HDR_CHECKSUM_TYPE, s3_put_select_algo(), and s3_set_header().
Referenced by s3_put_checksum_failed().
s3_put_trailer_checksum_apply()
s3_cksum_result_t s3_put_trailer_checksum_apply (ngx_http_request_t * r, const char * fs_path, const char * root_canon, const char * algo_token, const char * value)
Definition at line 409 of file checksum.c.
References s3_cksum_desc_t::alg_name, b64, brix_vfs_close(), brix_vfs_file_fd(), s3_cksum_desc_t::header, s3_checksum_b64(), S3_CHECKSUM_B64_MAX, s3_cksum_by_token(), S3_CKSUM_CONFLICT, S3_CKSUM_ERROR, S3_CKSUM_MISMATCH, S3_CKSUM_OK, s3_cksum_vfs_open(), s3_cksum_vfs_unlink(), S3_HDR_CHECKSUM_TYPE, and s3_set_header().
Referenced by s3_chunk_finalize().
s3_vfs_bind_deleg()
void s3_vfs_bind_deleg (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, brix_vfs_ctx_t * vctx)
Definition at line 71 of file util.c.
References ngx_http_brix_shared_conf_t::backend_delegation, ngx_http_s3_req_ctx_t::bearer_token, BRIX_CRED_SELECT, brix_vfs_deleg_bind(), ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::deleg_proxy_pem, and ngx_http_brix_s3_module.
Referenced by s3_build_vfs_ctx(), s3_chunk_finalize(), s3_commit_put(), s3_copy_vfs_ctx(), s3_put_aio_done(), and s3_vfs_ctx().