nginx-xrootd: src/fs/cache/origin/s3_transport.h File Reference
s3_transport.h File Reference
#include "fs/backend/s3/sd_s3_transport.h"
Functions
void brix_origin_trace_set (int info_on)
void brix_s3_origin_timeouts_set (long connect_ms, long stall_secs, long stall_bytes_per_s, long attempt_ms)
void brix_s3_origin_reuse_set (int reuse_on)
void brix_s3_origin_http_version_set (int ver)
int brix_s3_origin_http_version_supported (int ver)
Variables
const brix_s3_transport_t brix_s3_origin_curl_transport
Function Documentation
brix_origin_trace_set()
void brix_origin_trace_set (int info_on)
Definition at line 34 of file s3_transport_setup.c.
References g_origin_trace_info.
Referenced by cvmfs_merge_upstreams().
brix_s3_origin_http_version_set()
void brix_s3_origin_http_version_set (int ver)
Definition at line 89 of file s3_transport_setup.c.
References g_origin_http_version.
Referenced by cvmfs_merge_resilience().
brix_s3_origin_http_version_supported()
int brix_s3_origin_http_version_supported (int ver)
Definition at line 95 of file s3_transport_setup.c.
Referenced by cvmfs_merge_resilience().
brix_s3_origin_reuse_set()
void brix_s3_origin_reuse_set (int reuse_on)
Definition at line 76 of file s3_transport_setup.c.
References g_origin_no_reuse.
Referenced by cvmfs_merge_resilience().
brix_s3_origin_timeouts_set()
void brix_s3_origin_timeouts_set (long connect_ms, long stall_secs, long stall_bytes_per_s, long attempt_ms)
Definition at line 57 of file s3_transport_setup.c.
References g_origin_attempt_ms, g_origin_connect_ms, g_origin_stall_bytes, and g_origin_stall_secs.
Referenced by cvmfs_merge_resilience().
Variable Documentation
brix_s3_origin_curl_transport
const brix_s3_transport_t brix_s3_origin_curl_transport extern
Definition at line 289 of file s3_transport.c.
Referenced by brix_vbr_build_http(), brix_vbr_build_s3(), cvmfs_pt_thread(), tier_build_http(), and tier_build_s3().