nginx-xrootd: src/fs/cache/origin/s3_transport.c File Reference
s3_transport.c File Reference
#include "s3_transport.h"
#include <ngx_config.h>
#include <ngx_core.h>
#include "fs/path/path.h"
#include <curl/curl.h>
#include <ctype.h>
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/stat.h>
#include <time.h>
Data Structures
struct s3o_resp_t
struct s3o_trace_t
struct s3o_request_t
Functions
void brix_origin_trace_set (int info_on)
void brix_s3_origin_timeouts_set (long connect_ms, long stall_secs, long stall_bytes_per_s, long attempt_ms)
void brix_s3_origin_reuse_set (int reuse_on)
static long s3o_ms_since (const struct timespec *t0)
static int s3o_buf_append (char **buf, size_t *len, size_t *cap, const char *src, size_t n)
static size_t s3o_write_cb (char *ptr, size_t size, size_t nmemb, void *userdata)
static size_t s3o_header_cb (char *ptr, size_t size, size_t nmemb, void *userdata)
static struct curl_slist * s3o_build_slist (const char *headers)
static void s3o_trace (const s3o_trace_t *t)
static void s3o_curl_thread_free (void *handle)
static void s3o_curl_key_init (void)
static CURL * s3o_curl_acquire (void)
static void s3o_apply_ca (CURL *curl, const char *ca_path)
static struct curl_slist * s3o_build_headers (const s3o_request_t *req)
static void s3o_apply_timeouts (CURL *curl, int timeout_ms)
static void s3o_apply_reuse (CURL *curl)
static void s3o_apply_method (CURL *curl, const s3o_request_t *req)
static void s3o_apply_tls (CURL *curl, const s3o_request_t *req)
static void s3o_configure (CURL *curl, const s3o_request_t *req, s3o_resp_t *r, struct curl_slist *slist)
static int s3o_request_impl (const s3o_request_t *req, brix_s3_resp_t *resp, char *errbuf, size_t errcap)
static int s3o_request (void *tctx, const char *host, int port, int tls, const char *method, const char *path_and_query, const char *headers, const void *body, size_t body_len, int timeout_ms, brix_s3_resp_t *resp, char *errbuf, size_t errcap)
static int s3o_request_cred (void *tctx, const char *host, int port, int tls, const char *method, const char *path_and_query, const char *headers, const void *body, size_t body_len, int timeout_ms, const char *client_cert_pem, brix_s3_resp_t *resp, char *errbuf, size_t errcap)
static int s3o_resp_header (const brix_s3_resp_t *resp, const char *name, char *out, size_t outcap)
static const void * s3o_resp_body (const brix_s3_resp_t *resp, size_t *len)
static void s3o_resp_free (brix_s3_resp_t *resp)
Variables
static int g_origin_trace_info
static long g_origin_connect_ms
static long g_origin_stall_secs
static long g_origin_stall_bytes
static long g_origin_attempt_ms
static int g_origin_no_reuse
static pthread_key_t g_curl_key
static pthread_once_t g_curl_key_once = PTHREAD_ONCE_INIT
const brix_s3_transport_t brix_s3_origin_curl_transport
Function Documentation
brix_origin_trace_set()
void brix_origin_trace_set (int info_on)
Definition at line 33 of file s3_transport.c.
References g_origin_trace_info.
Referenced by cvmfs_merge_upstreams().
brix_s3_origin_reuse_set()
void brix_s3_origin_reuse_set (int reuse_on)
Definition at line 75 of file s3_transport.c.
References g_origin_no_reuse.
Referenced by cvmfs_merge_resilience().
brix_s3_origin_timeouts_set()
void brix_s3_origin_timeouts_set (long connect_ms, long stall_secs, long stall_bytes_per_s, long attempt_ms)
Definition at line 56 of file s3_transport.c.
References g_origin_attempt_ms, g_origin_connect_ms, g_origin_stall_bytes, and g_origin_stall_secs.
Referenced by cvmfs_merge_resilience().
s3o_apply_ca()
static void s3o_apply_ca (CURL * curl, const char * ca_path) static
Definition at line 301 of file s3_transport.c.
References stat().
Referenced by s3o_apply_tls().
s3o_apply_method()
static void s3o_apply_method (CURL * curl, const s3o_request_t * req) static
Definition at line 435 of file s3_transport.c.
References s3o_request_t::body, s3o_request_t::body_len, and s3o_request_t::method.
Referenced by s3o_configure().
s3o_apply_reuse()
static void s3o_apply_reuse (CURL * curl) static
Definition at line 410 of file s3_transport.c.
References g_origin_no_reuse.
Referenced by s3o_configure().
s3o_apply_timeouts()
static void s3o_apply_timeouts (CURL * curl, int timeout_ms) static
Definition at line 381 of file s3_transport.c.
References g_origin_attempt_ms, g_origin_connect_ms, g_origin_stall_bytes, and g_origin_stall_secs.
Referenced by s3o_configure().
s3o_apply_tls()
static void s3o_apply_tls (CURL * curl, const s3o_request_t * req) static
Definition at line 469 of file s3_transport.c.
References s3o_request_t::client_cert_pem, s3o_apply_ca(), s3o_request_t::tctx, and s3o_request_t::tls.
Referenced by s3o_configure().
s3o_buf_append()
static int s3o_buf_append (char ** buf, size_t * len, size_t * cap, const char * src, size_t n) static
Definition at line 106 of file s3_transport.c.
Referenced by s3o_header_cb(), and s3o_write_cb().
s3o_build_headers()
static struct curl_slist * s3o_build_headers (const s3o_request_t * req) static
Definition at line 357 of file s3_transport.c.
References s3o_request_t::headers, s3o_request_t::host, s3o_request_t::port, and s3o_build_slist().
Referenced by s3o_request_impl().
s3o_build_slist()
static struct curl_slist * s3o_build_slist (const char * headers) static
Definition at line 155 of file s3_transport.c.
Referenced by s3o_build_headers().
s3o_configure()
static void s3o_configure (CURL * curl, const s3o_request_t * req, s3o_resp_t * r, struct curl_slist * slist) static
Definition at line 495 of file s3_transport.c.
References s3o_request_t::host, s3o_request_t::path_and_query, s3o_request_t::port, s3o_apply_method(), s3o_apply_reuse(), s3o_apply_timeouts(), s3o_apply_tls(), s3o_header_cb(), s3o_write_cb(), s3o_request_t::timeout_ms, and s3o_request_t::tls.
Referenced by s3o_request_impl().
s3o_curl_acquire()
static CURL * s3o_curl_acquire (void) static
Definition at line 267 of file s3_transport.c.
References g_curl_key, g_curl_key_once, and s3o_curl_key_init().
Referenced by s3o_request_impl().
s3o_curl_key_init()
static void s3o_curl_key_init (void) static
Definition at line 259 of file s3_transport.c.
References g_curl_key, and s3o_curl_thread_free().
Referenced by s3o_curl_acquire().
s3o_curl_thread_free()
static void s3o_curl_thread_free (void * handle) static
Definition at line 251 of file s3_transport.c.
Referenced by s3o_curl_key_init().
s3o_header_cb()
static size_t s3o_header_cb (char * ptr, size_t size, size_t nmemb, void * userdata) static
Definition at line 141 of file s3_transport.c.
References s3o_resp_t::hdrs, s3o_resp_t::hdrs_cap, s3o_resp_t::hdrs_len, and s3o_buf_append().
Referenced by s3o_configure().
s3o_ms_since()
static long s3o_ms_since (const struct timespec * t0) static
Definition at line 81 of file s3_transport.c.
Referenced by s3o_request_impl().
s3o_request()
static int s3o_request (void * tctx, const char * host, int port, int tls, const char * method, const char * path_and_query, const char * headers, const void * body, size_t body_len, int timeout_ms, brix_s3_resp_t * resp, char * errbuf, size_t errcap) static
Definition at line 596 of file s3_transport.c.
References s3o_request_impl(), s3o_request_t::tctx, and tls.
s3o_request_cred()
static int s3o_request_cred (void * tctx, const char * host, int port, int tls, const char * method, const char * path_and_query, const char * headers, const void * body, size_t body_len, int timeout_ms, const char * client_cert_pem, brix_s3_resp_t * resp, char * errbuf, size_t errcap) static
Definition at line 621 of file s3_transport.c.
References s3o_request_impl(), s3o_request_t::tctx, and tls.
s3o_request_impl()
static int s3o_request_impl (const s3o_request_t * req, brix_s3_resp_t * resp, char * errbuf, size_t errcap) static
Definition at line 532 of file s3_transport.c.
References s3o_resp_t::body, s3o_resp_t::body_len, s3o_resp_t::hdrs, s3o_request_t::host, s3o_request_t::method, brix_s3_resp_t::opaque, s3o_request_t::path_and_query, s3o_request_t::port, s3o_build_headers(), s3o_configure(), s3o_curl_acquire(), s3o_ms_since(), s3o_trace(), and brix_s3_resp_t::status.
Referenced by s3o_request(), and s3o_request_cred().
s3o_resp_body()
static const void * s3o_resp_body (const brix_s3_resp_t * resp, size_t * len) static
Definition at line 679 of file s3_transport.c.
References s3o_resp_t::body, s3o_resp_t::body_len, and brix_s3_resp_t::opaque.
s3o_resp_free()
static void s3o_resp_free (brix_s3_resp_t * resp) static
Definition at line 692 of file s3_transport.c.
References s3o_resp_t::body, s3o_resp_t::hdrs, and brix_s3_resp_t::opaque.
s3o_resp_header()
static int s3o_resp_header (const brix_s3_resp_t * resp, const char * name, char * out, size_t outcap) static
Definition at line 645 of file s3_transport.c.
References s3o_resp_t::hdrs, name, and brix_s3_resp_t::opaque.
s3o_trace()
static void s3o_trace (const s3o_trace_t * t) static
Definition at line 208 of file s3_transport.c.
References brix_sanitize_log_string(), s3o_trace_t::bytes, s3o_trace_t::dur_ms, s3o_trace_t::err, g_origin_trace_info, s3o_trace_t::host, s3o_trace_t::method, s3o_trace_t::path, s3o_trace_t::port, and s3o_trace_t::status.
Referenced by s3o_request_impl().
s3o_write_cb()
static size_t s3o_write_cb (char * ptr, size_t size, size_t nmemb, void * userdata) static
Definition at line 129 of file s3_transport.c.
References s3o_resp_t::body, s3o_resp_t::body_cap, s3o_resp_t::body_len, and s3o_buf_append().
Referenced by s3o_configure().
Variable Documentation
brix_s3_origin_curl_transport
const brix_s3_transport_t brix_s3_origin_curl_transport
Initial value:
= {
    .request      = s3o_request,
    .request_cred = s3o_request_cred,
    .resp_header = s3o_resp_header,
    .resp_body   = s3o_resp_body,
    .resp_free   = s3o_resp_free,
}
Definition at line 706 of file s3_transport.c.
Referenced by brix_vbr_build_http(), brix_vbr_build_s3(), cvmfs_pt_thread(), tier_build_http(), and tier_build_s3().
g_curl_key
pthread_key_t g_curl_key static
Definition at line 247 of file s3_transport.c.
Referenced by s3o_curl_acquire(), and s3o_curl_key_init().
g_curl_key_once
pthread_once_t g_curl_key_once = PTHREAD_ONCE_INIT static
Definition at line 248 of file s3_transport.c.
Referenced by s3o_curl_acquire().
g_origin_attempt_ms
long g_origin_attempt_ms static
Definition at line 53 of file s3_transport.c.
Referenced by brix_s3_origin_timeouts_set(), and s3o_apply_timeouts().
g_origin_connect_ms
long g_origin_connect_ms static
Definition at line 50 of file s3_transport.c.
Referenced by brix_s3_origin_timeouts_set(), and s3o_apply_timeouts().
g_origin_no_reuse
int g_origin_no_reuse static
Definition at line 72 of file s3_transport.c.
Referenced by brix_s3_origin_reuse_set(), and s3o_apply_reuse().
g_origin_stall_bytes
long g_origin_stall_bytes static
Definition at line 52 of file s3_transport.c.
Referenced by brix_s3_origin_timeouts_set(), and s3o_apply_timeouts().
g_origin_stall_secs
long g_origin_stall_secs static
Definition at line 51 of file s3_transport.c.
Referenced by brix_s3_origin_timeouts_set(), and s3o_apply_timeouts().
g_origin_trace_info
int g_origin_trace_info static
Definition at line 30 of file s3_transport.c.
Referenced by brix_origin_trace_set(), and s3o_trace().