nginx-xrootd: src/fs/cache/origin/s3_transport_internal.h File Reference
s3_transport_internal.h File Reference
#include <curl/curl.h>
#include <stddef.h>
Data Structures
struct s3o_resp_t
struct s3o_request_t
struct s3o_trace_t
Functions
size_t s3o_write_cb (char *ptr, size_t size, size_t nmemb, void *userdata)
size_t s3o_header_cb (char *ptr, size_t size, size_t nmemb, void *userdata)
CURL * s3o_curl_acquire (void)
struct curl_slist * s3o_build_headers (const s3o_request_t *req)
void s3o_configure (CURL *curl, const s3o_request_t *req, s3o_resp_t *r, struct curl_slist *slist)
void s3o_trace (const s3o_trace_t *t)
const char * s3o_negotiated_proto (CURL *curl)
Function Documentation
s3o_build_headers()
struct curl_slist * s3o_build_headers (const s3o_request_t * req)
Definition at line 326 of file s3_transport_setup.c.
References s3o_request_t::headers, s3o_request_t::host, s3o_request_t::port, and s3o_build_slist().
Referenced by s3o_request_impl().
s3o_configure()
void s3o_configure (CURL * curl, const s3o_request_t * req, s3o_resp_t * r, struct curl_slist * slist)
Definition at line 464 of file s3_transport_setup.c.
References s3o_request_t::host, s3o_request_t::path_and_query, s3o_request_t::port, s3o_apply_http_version(), s3o_apply_method(), s3o_apply_reuse(), s3o_apply_timeouts(), s3o_apply_tls(), s3o_header_cb(), s3o_write_cb(), s3o_request_t::timeout_ms, and s3o_request_t::tls.
Referenced by s3o_request_impl().
s3o_curl_acquire()
CURL * s3o_curl_acquire (void)
Definition at line 266 of file s3_transport_setup.c.
References g_curl_key, g_curl_key_once, and s3o_curl_key_init().
Referenced by s3o_request_impl().
s3o_header_cb()
size_t s3o_header_cb (char * ptr, size_t size, size_t nmemb, void * userdata)
Definition at line 79 of file s3_transport.c.
References s3o_resp_t::hdrs, s3o_resp_t::hdrs_cap, s3o_resp_t::hdrs_len, and s3o_buf_append().
Referenced by s3o_configure().
s3o_negotiated_proto()
const char * s3o_negotiated_proto (CURL * curl)
Definition at line 155 of file s3_transport_setup.c.
Referenced by s3o_request_impl().
s3o_trace()
void s3o_trace (const s3o_trace_t * t)
Definition at line 206 of file s3_transport_setup.c.
References brix_sanitize_log_string(), s3o_trace_t::bytes, s3o_trace_t::dur_ms, s3o_trace_t::err, g_origin_trace_info, s3o_trace_t::host, s3o_trace_t::method, s3o_trace_t::path, s3o_trace_t::port, s3o_trace_t::proto, and s3o_trace_t::status.
Referenced by s3o_request_impl().
s3o_write_cb()
size_t s3o_write_cb (char * ptr, size_t size, size_t nmemb, void * userdata)
Definition at line 67 of file s3_transport.c.
References s3o_resp_t::body, s3o_resp_t::body_cap, s3o_resp_t::body_len, and s3o_buf_append().
Referenced by s3o_configure().