nginx-xrootd: src/protocols/s3/s3_auth_internal.h File Reference
s3_auth_internal.h File Reference
Data Structures
struct sigv4_components_t
Functions
int s3_sigv4_derive_signing_key_cached (const ngx_str_t *secret_key, const char *date, const char *region, u_char out[32])
int parse_authorization (const ngx_str_t *auth, sigv4_components_t *out)
int parse_presigned_authorization (ngx_http_request_t *r, sigv4_components_t *out)
Function Documentation
parse_authorization()
int parse_authorization (const ngx_str_t * auth, sigv4_components_t * out)
Definition at line 240 of file auth_sigv4_parse.c.
References sigv4_components_t::signature, sigv4_components_t::signed_hdrs, sigv4_extract_auth_value(), and sigv4_parse_credential_scope().
parse_presigned_authorization()
int parse_presigned_authorization (ngx_http_request_t * r, sigv4_components_t * out)
Definition at line 294 of file auth_sigv4_parse.c.
References sigv4_components_t::amz_date, sigv4_components_t::amz_expires, brix_str_cbuf(), sigv4_components_t::presigned, sigv4_components_t::signature, sigv4_components_t::signed_hdrs, sigv4_copy_arg_decoded(), sigv4_parse_credential_scope(), and sigv4_parse_expires().
s3_sigv4_derive_signing_key_cached()
int s3_sigv4_derive_signing_key_cached (const ngx_str_t * secret_key, const char * date, const char * region, u_char out[32])
Definition at line 245 of file auth_sigv4_verify.c.
References brix_sigv4_signing_key(), date, ngx_memcpy, region, and s_signing_key_cache.
Referenced by s3_post_verify_policy(), and s3_verify_sigv4().