nginx-xrootd: src/protocols/s3/s3_post_internal.h File Reference
s3_post_internal.h File Reference
#include "s3.h"
#include "fs/backend/sd.h"
#include "auth/impersonate/lifecycle.h"
#include "s3_auth_internal.h"
#include "core/compat/crypto.h"
#include "core/compat/hex.h"
#include "core/http/http_body.h"
#include "core/http/http_headers.h"
#include "fs/vfs/vfs.h"
#include "fs/path/path.h"
#include <jansson.h>
#include <openssl/crypto.h>
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include "core/compat/alloc_guard.h"
Data Structures
struct s3_post_field_t
struct s3_post_form_t
Macros
#define S3_POST_MAX_BODY (128 * 1024 * 1024)
#define S3_POST_MAX_FIELD 4096
#define S3_POST_MAX_FIELDS 64
#define S3_POST_MAX_POLICY 65536
Functions
ngx_int_t s3_post_error (ngx_http_request_t *r, ngx_uint_t status, const char *code, const char *message)
ngx_int_t s3_post_copy_text (const u_char *data, size_t len, char *dst, size_t dstsz)
const char * s3_post_field_value (const s3_post_form_t *form, const char *name)
ngx_int_t s3_post_store_field (s3_post_form_t *form, const char *name, const u_char *data, size_t len)
ngx_int_t s3_post_boundary (ngx_http_request_t *r, char *boundary, size_t boundary_sz)
u_char * s3_memmem (u_char *hay, size_t hay_len, const u_char *needle, size_t needle_len)
ngx_int_t s3_post_extract_param (const char *line, const char *name, char *out, size_t outsz)
void s3_post_basename (char *s)
ngx_int_t s3_post_expand_filename (ngx_http_request_t *r, s3_post_form_t *form)
ngx_int_t s3_post_parse_form (ngx_http_request_t *r, u_char *body, size_t body_len, const char *boundary, s3_post_form_t *form)
int64_t s3_post_days_from_civil (int y, unsigned m, unsigned d)
ngx_int_t s3_post_parse_iso8601 (const char *s, time_t *out)
ngx_int_t s3_post_check_field_eq (const char *actual, const char *expected)
ngx_int_t s3_post_policy_condition (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form, json_t *cond)
ngx_int_t s3_post_validate_policy_json (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form, u_char *policy_json, size_t policy_len)
ngx_int_t s3_post_parse_credential (const char *credential, char *date, size_t date_sz, char *region, size_t region_sz, const char **akid)
ngx_int_t s3_post_verify_policy (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form)
ngx_int_t s3_post_write_object (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form, const char *fs_path, char *etag, size_t etag_sz)
ngx_int_t s3_post_send_empty (ngx_http_request_t *r, ngx_uint_t status)
ngx_int_t s3_post_send_created (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form, const char *etag)
ngx_int_t s3_post_send_success (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const s3_post_form_t *form, const char *etag)
void s3_post_object_body_handler_inner (ngx_http_request_t *r)
Macro Definition Documentation
S3_POST_MAX_BODY
#define S3_POST_MAX_BODY (128 * 1024 * 1024)
Definition at line 26 of file s3_post_internal.h.
S3_POST_MAX_FIELD
#define S3_POST_MAX_FIELD 4096
Definition at line 27 of file s3_post_internal.h.
S3_POST_MAX_FIELDS
#define S3_POST_MAX_FIELDS 64
Definition at line 28 of file s3_post_internal.h.
S3_POST_MAX_POLICY
#define S3_POST_MAX_POLICY 65536
Definition at line 29 of file s3_post_internal.h.
Function Documentation
s3_memmem()
u_char * s3_memmem (u_char * hay, size_t hay_len, const u_char * needle, size_t needle_len)
Definition at line 54 of file post_object.c.
Referenced by s3_post_parse_form().
s3_post_basename()
void s3_post_basename (char * s)
Definition at line 85 of file post_object.c.
References s.
Referenced by s3_post_parse_form().
s3_post_boundary()
ngx_int_t s3_post_boundary (ngx_http_request_t * r, char * boundary, size_t boundary_sz)
Definition at line 129 of file post_form.c.
References brix_http_find_header().
Referenced by s3_post_object_body_handler_inner().
s3_post_check_field_eq()
ngx_int_t s3_post_check_field_eq (const char * actual, const char * expected)
Definition at line 76 of file post_policy.c.
Referenced by s3_post_policy_condition().
s3_post_copy_text()
ngx_int_t s3_post_copy_text (const u_char * data, size_t len, char * dst, size_t dstsz)
Definition at line 25 of file post_object.c.
Referenced by s3_post_store_field().
s3_post_days_from_civil()
int64_t s3_post_days_from_civil (int y, unsigned m, unsigned d)
Definition at line 22 of file post_policy.c.
Referenced by s3_post_parse_iso8601().
s3_post_error()
ngx_int_t s3_post_error (ngx_http_request_t * r, ngx_uint_t status, const char * code, const char * message)
Definition at line 8 of file post_object.c.
References s3_send_xml_error().
Referenced by s3_post_object_body_handler_inner(), s3_post_send_success(), and s3_post_verify_policy().
s3_post_expand_filename()
ngx_int_t s3_post_expand_filename (ngx_http_request_t * r, s3_post_form_t * form)
Definition at line 280 of file post_form.c.
References brix_http_str_has_ctl(), s3_post_form_t::filename, s3_post_form_t::key, and S3_MAX_KEY.
Referenced by s3_post_object_body_handler_inner().
s3_post_extract_param()
ngx_int_t s3_post_extract_param (const char * line, const char * name, char * out, size_t outsz)
Definition at line 214 of file post_form.c.
References name.
Referenced by s3_post_parse_form().
s3_post_field_value()
const char * s3_post_field_value (const s3_post_form_t * form, const char * name)
Definition at line 18 of file post_form.c.
References s3_post_form_t::content_type, s3_post_form_t::fields, s3_post_form_t::key, s3_post_field_t::name, name, s3_post_form_t::nfields, and s3_post_field_t::value.
Referenced by s3_post_policy_condition().
s3_post_object_body_handler_inner()
void s3_post_object_body_handler_inner (ngx_http_request_t * r)
Definition at line 231 of file post_object.c.
References brix_http_body_read_all(), brix_http_map_errno(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METHOD_POST, BRIX_S3_METRIC_ADD, BRIX_S3_METRIC_INC, ngx_http_s3_loc_conf_t::common, s3_post_form_t::file_len, s3_post_form_t::have_file, s3_post_form_t::key, ngx_http_brix_s3_module, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, s3_metrics_finalize_request_method(), s3_post_boundary(), s3_post_error(), s3_post_expand_filename(), S3_POST_MAX_BODY, s3_post_parse_form(), s3_post_send_success(), s3_post_verify_policy(), s3_post_write_object(), and s3_resolve_key().
Referenced by s3_post_object_body_handler().
s3_post_parse_credential()
ngx_int_t s3_post_parse_credential (const char * credential, char * date, size_t date_sz, char * region, size_t region_sz, const char ** akid)
Definition at line 275 of file post_policy.c.
References date, and region.
Referenced by s3_post_verify_policy().
s3_post_parse_form()
ngx_int_t s3_post_parse_form (ngx_http_request_t * r, u_char * body, size_t body_len, const char * boundary, s3_post_form_t * form)
Definition at line 352 of file post_form.c.
References s3_post_form_t::content_type, s3_post_form_t::file_data, s3_post_form_t::file_len, s3_post_form_t::filename, s3_post_form_t::have_file, name, s3_memmem(), s3_post_basename(), s3_post_extract_param(), and s3_post_store_field().
Referenced by s3_post_object_body_handler_inner().
s3_post_parse_iso8601()
ngx_int_t s3_post_parse_iso8601 (const char * s, time_t * out)
Definition at line 48 of file post_policy.c.
References s, and s3_post_days_from_civil().
Referenced by s3_post_validate_policy_json().
s3_post_policy_condition()
ngx_int_t s3_post_policy_condition (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form, json_t * cond)
Definition at line 100 of file post_policy.c.
References ngx_http_s3_loc_conf_t::bucket, s3_post_form_t::file_len, key, s3_post_check_field_eq(), and s3_post_field_value().
Referenced by s3_post_validate_policy_json().
s3_post_send_created()
ngx_int_t s3_post_send_created (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form, const char * etag)
Definition at line 26 of file post_response.c.
References BRIX_PNALLOC_OR_RETURN, ngx_http_s3_loc_conf_t::bucket, s3_post_form_t::key, S3_MAX_KEY, XML_APPEND, and XML_APPEND_ELEM.
Referenced by s3_post_send_success().
s3_post_send_empty()
ngx_int_t s3_post_send_empty (ngx_http_request_t * r, ngx_uint_t status)
Definition at line 10 of file post_response.c.
Referenced by s3_post_send_success().
s3_post_send_success()
ngx_int_t s3_post_send_success (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form, const char * etag)
Definition at line 97 of file post_response.c.
References brix_http_str_has_ctl(), s3_post_error(), s3_post_send_created(), s3_post_send_empty(), s3_set_header(), s3_post_form_t::success_redirect, and s3_post_form_t::success_status.
Referenced by s3_post_object_body_handler_inner().
s3_post_store_field()
ngx_int_t s3_post_store_field (s3_post_form_t * form, const char * name, const u_char * data, size_t len)
Definition at line 56 of file post_form.c.
References s3_post_form_t::algorithm, s3_post_form_t::amz_date, s3_post_form_t::credential, s3_post_form_t::fields, s3_post_form_t::key, s3_post_field_t::name, name, s3_post_form_t::nfields, s3_post_form_t::policy, s3_post_copy_text(), S3_POST_MAX_FIELD, S3_POST_MAX_FIELDS, s3_post_form_t::signature, s3_post_form_t::success_redirect, s3_post_form_t::success_status, and s3_post_field_t::value.
Referenced by s3_post_parse_form().
s3_post_validate_policy_json()
ngx_int_t s3_post_validate_policy_json (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form, u_char * policy_json, size_t policy_len)
Definition at line 209 of file post_policy.c.
References s3_post_parse_iso8601(), and s3_post_policy_condition().
Referenced by s3_post_verify_policy().
s3_post_verify_policy()
ngx_int_t s3_post_verify_policy (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form)
Definition at line 339 of file post_policy.c.
References ngx_http_s3_loc_conf_t::access_key, s3_post_form_t::algorithm, s3_post_form_t::amz_date, brix_hex_encode(), brix_hmac_sha256(), s3_post_form_t::credential, date, s3_post_form_t::policy, region, ngx_http_s3_loc_conf_t::region, s3_post_error(), s3_post_parse_credential(), s3_post_validate_policy_json(), s3_sigv4_derive_signing_key_cached(), ngx_http_s3_loc_conf_t::secret_key, and s3_post_form_t::signature.
Referenced by s3_post_object_body_handler_inner().
s3_post_write_object()
ngx_int_t s3_post_write_object (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const s3_post_form_t * form, const char * fs_path, char * etag, size_t etag_sz)
Definition at line 115 of file post_object.c.
References brix_vfs_mkdir(), brix_vfs_probe(), brix_vfs_pwrite_full(), brix_vfs_staged_abort(), brix_vfs_staged_commit(), brix_vfs_staged_fd(), brix_vfs_staged_open(), s3_post_form_t::file_data, s3_post_form_t::file_len, brix_vfs_stat_t::mtime, PATH_MAX, s3_build_vfs_ctx(), s3_etag(), s3_set_header(), brix_vfs_stat_t::size, and stat().
Referenced by s3_post_object_body_handler_inner().