nginx-xrootd: src/protocols/s3/s3_put_internal.h File Reference
s3_put_internal.h File Reference
#include "s3.h"
#include "aws_chunked.h"
#include "tagging.h"
#include "usermeta.h"
#include "core/http/http_body.h"
#include "core/http/http_headers.h"
#include "core/compat/staged_file.h"
#include "fs/vfs/vfs.h"
#include "fs/path/path.h"
#include "observability/dashboard/dashboard_tracking.h"
#include "auth/impersonate/lifecycle.h"
#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <limits.h>
Data Structures
struct s3_put_aio_t
struct s3_chunk_aio_t
struct s3put_state_t
Functions
const char * s3_dashboard_put_op (ngx_http_request_t *r)
void s3_dashboard_identity (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, char *out, size_t outsz)
ngx_int_t s3put_stream_body (s3put_state_t *st)
void s3put_commit_and_headers (s3put_state_t *st)
ngx_int_t s3_commit_put (ngx_http_request_t *r, ngx_log_t *log, const char *root_canon, brix_vfs_writer_t *writer, const char *final_path)
int s3_put_commit_conflict (ngx_http_request_t *r)
void s3_put_aio_thread (void *data, ngx_log_t *log)
void s3_put_aio_done (ngx_event_t *ev)
ngx_uint_t s3_put_body_mode (const brix_http_body_summary_t *summary)
void s3_put_finalize_error (ngx_http_request_t *r)
void s3_put_finalize_fs_error (ngx_http_request_t *r, int saved_errno)
void s3_put_finalize_empty_ok (ngx_http_request_t *r)
void s3_put_finalize_ok (ngx_http_request_t *r, size_t body_bytes, ngx_uint_t body_mode)
void s3_put_finalize_bad_digest (ngx_http_request_t *r)
void s3_put_finalize_invalid_request (ngx_http_request_t *r)
void s3_put_finalize_invalid_digest (ngx_http_request_t *r)
void s3_put_finalize_codec_error (ngx_http_request_t *r, ngx_int_t status)
int s3_put_checksum_failed (ngx_http_request_t *r, const char *fs_path, const char *root_canon)
void s3_put_finalize_client_error (ngx_http_request_t *r, int status, const char *code, const char *message)
void s3_chunk_finalize (ngx_http_request_t *r, const char *root_canon, const char *fs_path, brix_vfs_writer_t *writer, const s3_chunk_trailer_t *trailer, uint64_t expected, ngx_uint_t body_mode)
void s3_chunk_decode_failed (ngx_http_request_t *r, const char *root_canon, brix_vfs_writer_t *writer, int http_status)
void s3_chunk_aio_thread (void *data, ngx_log_t *log)
void s3_build_chunk_verify (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, s3_chunk_verify_t *v)
void s3_chunk_aio_done (ngx_event_t *ev)
void s3_put_streaming (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, brix_vfs_writer_t *writer, const char *fs_path, ngx_uint_t body_mode)
void s3_put_body_inner (ngx_http_request_t *r)
Function Documentation
s3_build_chunk_verify()
void s3_build_chunk_verify (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, s3_chunk_verify_t * v)
Definition at line 133 of file put_chunk.c.
References s3_chunk_verify_t::amz_date, s3_chunk_verify_t::enabled, ngx_http_s3_req_ctx_t::have_sigv4, ngx_http_brix_s3_module, ngx_memcpy, s3_chunk_verify_t::scope, s3_chunk_verify_t::seed_signature, s3_chunk_verify_t::signing_key, ngx_http_s3_req_ctx_t::sigv4_amz_date, ngx_http_s3_req_ctx_t::sigv4_scope, ngx_http_s3_req_ctx_t::sigv4_seed_signature, ngx_http_s3_req_ctx_t::sigv4_signing_key, and ngx_http_s3_loc_conf_t::verify_chunk_signatures.
Referenced by s3_put_streaming().
s3_chunk_aio_done()
void s3_chunk_aio_done (ngx_event_t * ev)
Definition at line 158 of file put_chunk.c.
References s3_chunk_aio_t::body_mode, s3_chunk_aio_t::expected, s3_chunk_aio_t::fs_path, s3_chunk_aio_t::http_status, s3_chunk_aio_t::r, s3_chunk_aio_t::rc, s3_chunk_aio_t::root_canon, s3_chunk_decode_failed(), s3_chunk_finalize(), s3_chunk_aio_t::trailer, and s3_chunk_aio_t::writer.
Referenced by s3_put_streaming().
s3_chunk_aio_thread()
void s3_chunk_aio_thread (void * data, ngx_log_t * log)
Definition at line 113 of file put_chunk.c.
References brix_vfs_writer_fd(), s3_chunk_aio_t::expected, s3_chunk_aio_t::fs_path, s3_chunk_aio_t::http_status, log, s3_chunk_aio_t::r, s3_chunk_aio_t::rc, s3_aws_chunked_decode_to_fd(), s3_chunk_aio_t::trailer, s3_chunk_aio_t::verify, s3_chunk_aio_t::window, and s3_chunk_aio_t::writer.
Referenced by s3_put_streaming().
s3_chunk_decode_failed()
void s3_chunk_decode_failed (ngx_http_request_t * r, const char * root_canon, brix_vfs_writer_t * writer, int http_status)
Definition at line 87 of file put_chunk.c.
References brix_vfs_writer_abort(), s3_put_finalize_client_error(), and s3_put_finalize_error().
Referenced by s3_chunk_aio_done(), and s3_put_streaming().
s3_chunk_finalize()
void s3_chunk_finalize (ngx_http_request_t * r, const char * root_canon, const char * fs_path, brix_vfs_writer_t * writer, const s3_chunk_trailer_t * trailer, uint64_t expected, ngx_uint_t body_mode)
Definition at line 15 of file put_chunk.c.
References s3_chunk_trailer_t::algo_token, brix_log_safe_path(), BRIX_PROTO_S3, brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), brix_vfs_probe(), ngx_http_s3_loc_conf_t::common, brix_vfs_stat_t::mtime, ngx_http_brix_s3_module, brix_vfs_ctx_t::pool, s3_apply_put_tagging_header(), s3_apply_put_user_metadata(), S3_CKSUM_CONFLICT, S3_CKSUM_MISMATCH, s3_commit_put(), s3_etag(), s3_put_checksum_failed(), s3_put_commit_conflict(), s3_put_finalize_bad_digest(), s3_put_finalize_error(), s3_put_finalize_invalid_request(), s3_put_finalize_ok(), s3_put_trailer_checksum_apply(), s3_set_header(), s3_vfs_bind_deleg(), brix_vfs_stat_t::size, stat(), ngx_http_brix_shared_conf_t::storage_credential_dir, ngx_http_brix_shared_conf_t::storage_credential_fallback, and s3_chunk_trailer_t::value.
Referenced by s3_chunk_aio_done(), and s3_put_streaming().
s3_commit_put()
ngx_int_t s3_commit_put (ngx_http_request_t * r, ngx_log_t * log, const char * root_canon, brix_vfs_writer_t * writer, const char * final_path)
Definition at line 22 of file put_finalize.c.
References BRIX_PROTO_S3, brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), brix_vfs_probe(), brix_vfs_writer_commit_ex(), BRIX_XFER_COMMIT_ERR, brix_xfer_finish(), BRIX_XFER_OK, BRIX_XFER_STAGE, ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::exclusive_create, brix_vfs_stat_t::is_regular, log, ngx_http_brix_s3_module, brix_vfs_ctx_t::pool, s3_vfs_bind_deleg(), brix_vfs_stat_t::size, ngx_http_brix_shared_conf_t::storage_credential_dir, and ngx_http_brix_shared_conf_t::storage_credential_fallback.
Referenced by s3_chunk_finalize(), s3_put_aio_done(), and s3put_commit_and_headers().
s3_dashboard_identity()
void s3_dashboard_identity (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, char * out, size_t outsz)
Definition at line 24 of file put.c.
References ngx_http_s3_loc_conf_t::access_key, brix_identity_subject_cstr(), ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, and ngx_memcpy.
Referenced by s3_put_try_sentinel(), and s3put_stream_body().
s3_dashboard_put_op()
const char * s3_dashboard_put_op (ngx_http_request_t * r)
Definition at line 8 of file put.c.
References s3_get_query_param().
Referenced by s3put_stream_body().
s3_put_aio_done()
void s3_put_aio_done (ngx_event_t * ev)
Definition at line 70 of file put_aio.c.
References s3_put_aio_t::body_bytes, s3_put_aio_t::body_mode, brix_dashboard_http_add(), brix_log_safe_path(), BRIX_PROTO_S3, BRIX_S3_METRIC_ADD, BRIX_S3_METRIC_INC, brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), brix_vfs_probe(), brix_vfs_writer_abort(), ngx_http_s3_loc_conf_t::common, s3_put_aio_t::final_path, s3_put_aio_t::io_errno, s3_put_aio_t::len, log, brix_vfs_stat_t::mtime, ngx_http_brix_s3_module, s3_put_aio_t::nwritten, brix_vfs_ctx_t::pool, s3_put_aio_t::r, s3_put_aio_t::root_canon, s3_apply_put_tagging_header(), s3_apply_put_user_metadata(), s3_commit_put(), s3_etag(), s3_put_checksum_failed(), s3_put_commit_conflict(), s3_put_finalize_empty_ok(), s3_put_finalize_error(), s3_set_header(), s3_vfs_bind_deleg(), brix_vfs_stat_t::size, stat(), ngx_http_brix_shared_conf_t::storage_credential_dir, ngx_http_brix_shared_conf_t::storage_credential_fallback, and s3_put_aio_t::writer.
Referenced by s3put_stream_offload().
s3_put_aio_thread()
void s3_put_aio_thread (void * data, ngx_log_t * log)
Definition at line 42 of file put_aio.c.
References brix_http_body_write_to_writer(), s3_put_aio_t::io_errno, s3_put_aio_t::len, log, s3_put_aio_t::nwritten, s3_put_aio_t::r, and s3_put_aio_t::writer.
Referenced by s3put_stream_offload().
s3_put_body_inner()
void s3_put_body_inner (ngx_http_request_t * r)
Definition at line 239 of file put_inner.c.
References s3put_state_t::body_mode, BRIX_CODEC_IDENTITY, BRIX_S3_PUT_EMPTY, s3put_state_t::cf, ngx_http_s3_req_ctx_t::fs_path, s3put_state_t::fs_path, ngx_http_brix_s3_module, s3put_state_t::put_codec, s3put_state_t::r, s3put_commit_and_headers(), s3put_open_target(), s3put_precondition(), and s3put_stream_body().
Referenced by s3_put_body_handler().
s3_put_body_mode()
ngx_uint_t s3_put_body_mode (const brix_http_body_summary_t * summary)
Definition at line 64 of file put.c.
References BRIX_S3_PUT_EMPTY, BRIX_S3_PUT_MEMORY, BRIX_S3_PUT_MIXED, BRIX_S3_PUT_SPOOLED, brix_http_body_summary_t::has_memory, and brix_http_body_summary_t::has_spooled.
Referenced by s3put_stream_body().
s3_put_checksum_failed()
int s3_put_checksum_failed (ngx_http_request_t * r, const char * fs_path, const char * root_canon)
Definition at line 303 of file put_finalize.c.
References S3_CKSUM_CONFLICT, S3_CKSUM_MISMATCH, s3_content_md5_verify(), s3_put_checksum_apply(), s3_put_finalize_bad_digest(), s3_put_finalize_invalid_digest(), and s3_put_finalize_invalid_request().
Referenced by s3_chunk_finalize(), s3_put_aio_done(), and s3put_commit_and_headers().
s3_put_commit_conflict()
int s3_put_commit_conflict (ngx_http_request_t * r)
Definition at line 79 of file put_finalize.c.
References s3_put_finalize_client_error().
Referenced by s3_chunk_finalize(), s3_put_aio_done(), and s3put_commit_and_headers().
s3_put_finalize_bad_digest()
void s3_put_finalize_bad_digest (ngx_http_request_t * r)
Definition at line 222 of file put_finalize.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), BRIX_S3_METHOD_PUT, s3_metrics_finalize_request_method(), and s3_send_xml_error().
Referenced by s3_chunk_finalize(), and s3_put_checksum_failed().
s3_put_finalize_client_error()
void s3_put_finalize_client_error (ngx_http_request_t * r, int status, const char * code, const char * message)
Definition at line 373 of file put_finalize.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), BRIX_S3_METHOD_PUT, code, s3_metrics_finalize_request_method(), and s3_send_xml_error().
Referenced by s3_chunk_decode_failed(), s3_put_commit_conflict(), and s3_put_streaming().
s3_put_finalize_codec_error()
void s3_put_finalize_codec_error (ngx_http_request_t * r, ngx_int_t status)
Definition at line 277 of file put_finalize.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), BRIX_S3_METHOD_PUT, code, s3_metrics_finalize_request_method(), and s3_send_xml_error().
Referenced by s3put_select_codec(), s3put_stream_aws_chunked(), and s3put_stream_sync().
s3_put_finalize_empty_ok()
void s3_put_finalize_empty_ok (ngx_http_request_t * r)
Definition at line 175 of file put_finalize.c.
References brix_dashboard_http_finish(), BRIX_S3_METHOD_PUT, and s3_metrics_finalize_request_method().
Referenced by s3_put_aio_done(), s3_put_finalize_ok(), and s3_put_try_sentinel().
s3_put_finalize_error()
void s3_put_finalize_error (ngx_http_request_t * r)
Definition at line 100 of file put_finalize.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_METHOD_PUT, BRIX_S3_METRIC_INC, and s3_metrics_finalize_request_method().
Referenced by s3_chunk_decode_failed(), s3_chunk_finalize(), s3_put_aio_done(), s3_put_finalize_fs_error(), s3_put_streaming(), s3_put_try_sentinel(), s3put_commit_and_headers(), s3put_precondition(), s3put_stream_body(), s3put_stream_offload(), and s3put_stream_sync().
s3_put_finalize_fs_error()
void s3_put_finalize_fs_error (ngx_http_request_t * r, int saved_errno)
Definition at line 127 of file put_finalize.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_http_errno_to_status(), BRIX_S3_EVENT_ACCESS_DENIED, BRIX_S3_EVENT_NO_SUCH_KEY, BRIX_S3_METHOD_PUT, BRIX_S3_METRIC_INC, code, s3_metrics_finalize_request_method(), s3_put_finalize_error(), and s3_send_xml_error().
Referenced by s3_put_try_sentinel(), s3put_ensure_parent_dirs(), and s3put_open_target().
s3_put_finalize_invalid_digest()
void s3_put_finalize_invalid_digest (ngx_http_request_t * r)
Definition at line 256 of file put_finalize.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), BRIX_S3_METHOD_PUT, s3_metrics_finalize_request_method(), and s3_send_xml_error().
Referenced by s3_put_checksum_failed().
s3_put_finalize_invalid_request()
void s3_put_finalize_invalid_request (ngx_http_request_t * r)
Definition at line 239 of file put_finalize.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), BRIX_S3_METHOD_PUT, s3_metrics_finalize_request_method(), and s3_send_xml_error().
Referenced by s3_chunk_finalize(), and s3_put_checksum_failed().
s3_put_finalize_ok()
void s3_put_finalize_ok (ngx_http_request_t * r, size_t body_bytes, ngx_uint_t body_mode)
Definition at line 200 of file put_finalize.c.
References brix_dashboard_http_add(), BRIX_S3_METRIC_ADD, BRIX_S3_METRIC_INC, and s3_put_finalize_empty_ok().
Referenced by s3_chunk_finalize(), and s3put_commit_and_headers().
s3_put_streaming()
void s3_put_streaming (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, brix_vfs_writer_t * writer, const char * fs_path, ngx_uint_t body_mode)
Definition at line 88 of file put.c.
References s3_chunk_aio_t::body_mode, brix_http_find_header(), brix_vfs_writer_abort(), brix_vfs_writer_fd(), ngx_http_s3_loc_conf_t::common, s3_chunk_aio_t::expected, s3_chunk_aio_t::fs_path, s3_chunk_aio_t::r, ngx_http_brix_shared_conf_t::root_canon, s3_chunk_aio_t::root_canon, s3_aws_chunked_decode_to_fd(), s3_build_chunk_verify(), s3_chunk_aio_done(), s3_chunk_aio_thread(), s3_chunk_decode_failed(), s3_chunk_finalize(), s3_put_finalize_client_error(), s3_put_finalize_error(), s3_thread_pool(), s3_chunk_aio_t::verify, and s3_chunk_aio_t::writer.
Referenced by s3put_stream_aws_chunked().
s3put_commit_and_headers()
void s3put_commit_and_headers (s3put_state_t * st)
Definition at line 297 of file put_stream.c.
References s3put_state_t::body_bytes, s3put_state_t::body_mode, brix_log_safe_path(), s3put_state_t::cf, ngx_http_s3_loc_conf_t::common, s3put_state_t::fs_path, s3put_state_t::r, ngx_http_brix_shared_conf_t::root_canon, s3_apply_put_tagging_header(), s3_apply_put_user_metadata(), s3_commit_put(), s3_put_checksum_failed(), s3_put_commit_conflict(), s3_put_finalize_error(), s3_put_finalize_ok(), s3put_emit_etag(), and s3put_state_t::writer.
Referenced by s3_put_body_inner().
s3put_stream_body()
ngx_int_t s3put_stream_body (s3put_state_t * st)
Definition at line 213 of file put_stream.c.
References s3put_state_t::body_bytes, s3put_state_t::body_mode, s3put_state_t::body_summary, brix_dashboard_http_start_identity(), brix_http_body_summary(), brix_vfs_writer_abort(), BRIX_XFER_DIR_WRITE, BRIX_XFER_PROTO_S3, brix_http_body_summary_t::bytes, s3put_state_t::cf, s3put_state_t::fs_path, s3put_state_t::r, s3_body_is_aws_chunked(), s3_dashboard_identity(), s3_dashboard_put_op(), s3_put_body_mode(), s3_put_finalize_error(), s3put_select_codec(), s3put_stream_aws_chunked(), s3put_stream_offload(), s3put_stream_sync(), and s3put_state_t::writer.
Referenced by s3_put_body_inner().