nginx-xrootd: src/core/compat/safe_size.h File Reference
safe_size.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
Functions
static ngx_int_t brix_size_mul (size_t a, size_t b, size_t *out)
static ngx_int_t brix_size_add (size_t a, size_t b, size_t *out)
static void * brix_palloc_array (ngx_pool_t *pool, size_t n, size_t sz)
static void * brix_pcalloc_array (ngx_pool_t *pool, size_t n, size_t sz)
static void * brix_alloc_array (ngx_log_t *log, size_t n, size_t sz)
Function Documentation
brix_alloc_array()
static void * brix_alloc_array (ngx_log_t * log, size_t n, size_t sz) inline static
Definition at line 127 of file safe_size.h.
References brix_size_mul(), and log.
Referenced by brix_handle_readv(), and brix_proxy_up_status_init().
brix_palloc_array()
static void * brix_palloc_array (ngx_pool_t * pool, size_t n, size_t sz) inline static
Definition at line 91 of file safe_size.h.
References brix_size_mul().
Referenced by tape_stage_post().
brix_pcalloc_array()
static void * brix_pcalloc_array (ngx_pool_t * pool, size_t n, size_t sz) inline static
Definition at line 107 of file safe_size.h.
References brix_size_mul().
brix_size_add()
static ngx_int_t brix_size_add (size_t a, size_t b, size_t * out) inline static
Definition at line 65 of file safe_size.h.
Referenced by brix_gsi_assemble_proxy(), brix_jwks_load(), brix_zip_extract_full(), and brix_zip_find_member().
brix_size_mul()
static ngx_int_t brix_size_mul (size_t a, size_t b, size_t * out) inline static
Definition at line 43 of file safe_size.h.
Referenced by brix_alloc_array(), brix_cache_add_candidate(), brix_palloc_array(), brix_pcalloc_array(), and brix_readv_read_segments().