nginx-xrootd: src/fs/scan/scan_record.h File Reference
scan_record.h File Reference
#include <stddef.h>
#include <stdint.h>
Data Structures
struct brix_scan_summary_t
Functions
int brix_scan_json_escape (const char *in, size_t len, char *out, size_t cap)
int brix_scan_record_file (char *buf, size_t cap, const char *path, int64_t size, int64_t mtime, const char *alg, const char *stored, const char *computed, const char *status)
int brix_scan_record_inspect (char *buf, size_t cap, const char *path, const char *backend, int64_t size, int64_t mtime, const char *stored_src, int ns_consistent)
int brix_scan_record_health (char *buf, size_t cap, const char *backend, uint64_t total_bytes, uint64_t free_bytes, uint64_t used_bytes)
int brix_scan_record_object (char *buf, size_t cap, const char *key, const char *path, int64_t size, int64_t mtime, int orphan)
int brix_scan_record_drift (char *buf, size_t cap, const char *key, const char *path, const char *cls, int64_t size)
int brix_scan_record_cursor (char *buf, size_t cap, const char *after)
int brix_scan_record_summary (char *buf, size_t cap, const brix_scan_summary_t *s)
Function Documentation
brix_scan_json_escape()
int brix_scan_json_escape (const char * in, size_t len, char * out, size_t cap)
Definition at line 18 of file scan_record.c.
Referenced by brix_scan_record_cursor(), brix_scan_record_file(), brix_scan_record_inspect(), brix_scan_record_object(), scan_str_or_null(), and test_json_escape().
brix_scan_record_cursor()
int brix_scan_record_cursor (char * buf, size_t cap, const char * after)
Definition at line 212 of file scan_record.c.
References brix_scan_json_escape(), and SCAN_ESC_MAX.
Referenced by test_record_cursor_summary().
brix_scan_record_drift()
int brix_scan_record_drift (char * buf, size_t cap, const char * key, const char * path, const char * cls, int64_t size)
Definition at line 190 of file scan_record.c.
References cls(), key, SCAN_ESC_MAX, and scan_str_or_null().
Referenced by scan_action_drift(), and test_record_object_drift().
brix_scan_record_file()
int brix_scan_record_file (char * buf, size_t cap, const char * path, int64_t size, int64_t mtime, const char * alg, const char * stored, const char * computed, const char * status)
Definition at line 66 of file scan_record.c.
References brix_scan_json_escape(), and SCAN_ESC_MAX.
Referenced by scan_action_dump(), scan_action_fill(), scan_action_verify(), scan_catalog_verify_one(), scan_verify_obj_record(), and test_record_file().
brix_scan_record_health()
int brix_scan_record_health (char * buf, size_t cap, const char * backend, uint64_t total_bytes, uint64_t free_bytes, uint64_t used_bytes)
Definition at line 124 of file scan_record.c.
Referenced by scan_health(), and test_record_inspect_health().
brix_scan_record_inspect()
int brix_scan_record_inspect (char * buf, size_t cap, const char * path, const char * backend, int64_t size, int64_t mtime, const char * stored_src, int ns_consistent)
Definition at line 102 of file scan_record.c.
References brix_scan_json_escape(), and SCAN_ESC_MAX.
Referenced by scan_action_inspect(), and test_record_inspect_health().
brix_scan_record_object()
int brix_scan_record_object (char * buf, size_t cap, const char * key, const char * path, int64_t size, int64_t mtime, int orphan)
Definition at line 161 of file scan_record.c.
References brix_scan_json_escape(), key, SCAN_ESC_MAX, and scan_str_or_null().
Referenced by scan_action_inventory(), scan_catalog_emit_object(), and test_record_object_drift().
brix_scan_record_summary()
int brix_scan_record_summary (char * buf, size_t cap, const brix_scan_summary_t * s)
Definition at line 228 of file scan_record.c.
References s.
Referenced by scan_render(), and test_record_cursor_summary().