nginx-xrootd: src/fs/scan/scan_engine.c File Reference
scan_engine.c File Reference
#include "scan_engine.h"
#include "core/compat/integrity_info.h"
#include "fs/vfs/vfs.h"
#include "protocols/root/protocol/opcodes.h"
#include <limits.h>
#include <string.h>
#include <strings.h>
Data Structures
struct scan_walk_ctx_t
struct scan_catalog_ctx_t
struct scan_verify_ctx_t
Macros
#define SCAN_LINE_MAX 3072
Functions
static void scan_display_path (const char *logical, char *out, size_t outsz)
ngx_int_t brix_scan_mode_parse (const char *name, brix_scan_mode_t *out)
static int scan_append (u_char **buf, size_t *cap, size_t *used, const char *line, size_t llen)
static const char * scan_stored (scan_walk_ctx_t *cc, int fd, const char *logical, brix_integrity_info_t *info)
static int scan_action_dump (scan_walk_ctx_t *cc, const char *logical, off_t size, time_t mtime, int fd, char *line, size_t linesz)
static int scan_action_verify (scan_walk_ctx_t *cc, const char *logical, off_t size, time_t mtime, int fd, char *line, size_t linesz)
static int scan_action_fill (scan_walk_ctx_t *cc, const char *logical, off_t size, time_t mtime, int fd, char *line, size_t linesz)
static int scan_action_inspect (scan_walk_ctx_t *cc, const char *logical, off_t size, time_t mtime, int fd, char *line, size_t linesz)
static int scan_action_inventory (scan_walk_ctx_t *cc, const char *logical, off_t size, time_t mtime, char *line, size_t linesz)
static int scan_action_drift (scan_walk_ctx_t *cc, const char *logical, off_t size, time_t mtime, char *line, size_t linesz)
static ngx_int_t scan_walk_file (void *cookie, const char *logical, const brix_vfs_stat_t *st, int fd)
ngx_int_t brix_scan_run (ngx_log_t *log, int rootfd, const char *logical, const brix_scan_opts_t *opts, u_char **buf, size_t *cap, size_t *used, brix_scan_summary_t *summary, uint16_t *err_code, char *err_msg, size_t err_sz)
static int scan_catalog_emit_object (void *ctx, const brix_sd_catalog_ent_t *ent)
ngx_int_t brix_scan_run_inventory (ngx_log_t *log, brix_sd_instance_t *sd, const brix_scan_opts_t *opts, u_char **buf, size_t *cap, size_t *used, brix_scan_summary_t *summary, uint16_t *err_code, char *err_msg, size_t err_sz)
static int scan_verify_obj_record (scan_verify_ctx_t *cc, const char *logical, const brix_sd_catalog_ent_t *ent, brix_sd_obj_t *obj, char *line, size_t linesz)
static int scan_catalog_verify_one (void *ctx, const brix_sd_catalog_ent_t *ent)
ngx_int_t brix_scan_run_verify_catalog (ngx_log_t *log, brix_sd_instance_t *sd, const brix_scan_opts_t *opts, u_char **buf, size_t *cap, size_t *used, brix_scan_summary_t *summary, uint16_t *err_code, char *err_msg, size_t err_sz)
Macro Definition Documentation
SCAN_LINE_MAX
#define SCAN_LINE_MAX 3072
Definition at line 19 of file scan_engine.c.
Function Documentation
brix_scan_mode_parse()
ngx_int_t brix_scan_mode_parse (const char * name, brix_scan_mode_t * out)
Definition at line 38 of file scan_engine.c.
References BRIX_SCAN_COMPARE, BRIX_SCAN_DRIFT, BRIX_SCAN_DUMP, BRIX_SCAN_FILL, BRIX_SCAN_INSPECT, BRIX_SCAN_INVENTORY, BRIX_SCAN_VERIFY, and name.
Referenced by ngx_http_brix_dashboard_scan_handler().
brix_scan_run()
ngx_int_t brix_scan_run (ngx_log_t * log, int rootfd, const char * logical, const brix_scan_opts_t * opts, u_char ** buf, size_t * cap, size_t * used, brix_scan_summary_t * summary, uint16_t * err_code, char * err_msg, size_t err_sz)
Definition at line 304 of file scan_engine.c.
References brix_vfs_walk(), BRIX_VFS_WALK_NONE, BRIX_VFS_WALK_OTHER, scan_walk_ctx_t::buf, scan_walk_ctx_t::cap, kXR_ArgInvalid, kXR_IOError, kXR_NoMemory, kXR_NotFound, log, scan_walk_ctx_t::log, brix_scan_opts_t::max_depth, brix_vfs_walk_opts_t::max_depth, brix_scan_opts_t::max_files, brix_vfs_walk_opts_t::max_files, scan_walk_ctx_t::oom, brix_vfs_walk_opts_t::open_files, scan_walk_ctx_t::opts, scan_walk_file(), scan_walk_ctx_t::sum, and scan_walk_ctx_t::used.
Referenced by ngx_http_brix_dashboard_scan_handler().
brix_scan_run_inventory()
ngx_int_t brix_scan_run_inventory (ngx_log_t * log, brix_sd_instance_t * sd, const brix_scan_opts_t * opts, u_char ** buf, size_t * cap, size_t * used, brix_scan_summary_t * summary, uint16_t * err_code, char * err_msg, size_t err_sz)
Definition at line 391 of file scan_engine.c.
References brix_vfs_enumerate_catalog(), scan_catalog_ctx_t::buf, scan_catalog_ctx_t::cap, kXR_IOError, kXR_NoMemory, kXR_Unsupported, log, scan_catalog_ctx_t::oom, scan_catalog_emit_object(), scan_catalog_ctx_t::sum, and scan_catalog_ctx_t::used.
Referenced by ngx_http_brix_dashboard_scan_handler().
brix_scan_run_verify_catalog()
ngx_int_t brix_scan_run_verify_catalog (ngx_log_t * log, brix_sd_instance_t * sd, const brix_scan_opts_t * opts, u_char ** buf, size_t * cap, size_t * used, brix_scan_summary_t * summary, uint16_t * err_code, char * err_msg, size_t err_sz)
Definition at line 531 of file scan_engine.c.
References scan_verify_ctx_t::alg, brix_scan_opts_t::alg, brix_vfs_enumerate_catalog(), scan_verify_ctx_t::buf, scan_verify_ctx_t::cap, kXR_IOError, kXR_NoMemory, kXR_Unsupported, log, scan_verify_ctx_t::log, scan_verify_ctx_t::oom, scan_catalog_verify_one(), scan_verify_ctx_t::sd, scan_verify_ctx_t::sum, and scan_verify_ctx_t::used.
Referenced by ngx_http_brix_dashboard_scan_handler().
scan_action_drift()
static int scan_action_drift (scan_walk_ctx_t * cc, const char * logical, off_t size, time_t mtime, char * line, size_t linesz) static
Definition at line 243 of file scan_engine.c.
References brix_scan_record_drift(), brix_scan_summary_t::ok, and scan_walk_ctx_t::sum.
Referenced by scan_walk_file().
scan_action_dump()
static int scan_action_dump (scan_walk_ctx_t * cc, const char * logical, off_t size, time_t mtime, int fd, char * line, size_t linesz) static
Definition at line 107 of file scan_engine.c.
References brix_scan_opts_t::alg, brix_scan_record_file(), brix_scan_summary_t::ok, scan_walk_ctx_t::opts, scan_stored(), and scan_walk_ctx_t::sum.
Referenced by scan_walk_file().
scan_action_fill()
static int scan_action_fill (scan_walk_ctx_t * cc, const char * logical, off_t size, time_t mtime, int fd, char * line, size_t linesz) static
Definition at line 167 of file scan_engine.c.
References brix_scan_opts_t::alg, brix_integrity_opts_t::allow_xattr_cache, brix_scan_summary_t::already, brix_integrity_get_fd(), brix_scan_record_file(), brix_scan_summary_t::bytes, brix_scan_summary_t::filled, brix_integrity_info_t::hex, scan_walk_ctx_t::log, brix_integrity_opts_t::no_compute, scan_walk_ctx_t::opts, scan_stored(), scan_walk_ctx_t::sum, brix_scan_summary_t::unreadable, and brix_integrity_opts_t::update_xattr_cache.
Referenced by scan_walk_file().
scan_action_inspect()
static int scan_action_inspect (scan_walk_ctx_t * cc, const char * logical, off_t size, time_t mtime, int fd, char * line, size_t linesz) static
Definition at line 210 of file scan_engine.c.
References brix_scan_record_inspect(), brix_scan_summary_t::ok, scan_stored(), and scan_walk_ctx_t::sum.
Referenced by scan_walk_file().
scan_action_inventory()
static int scan_action_inventory (scan_walk_ctx_t * cc, const char * logical, off_t size, time_t mtime, char * line, size_t linesz) static
Definition at line 230 of file scan_engine.c.
References brix_scan_record_object(), brix_scan_summary_t::ok, and scan_walk_ctx_t::sum.
Referenced by scan_walk_file().
scan_action_verify()
static int scan_action_verify (scan_walk_ctx_t * cc, const char * logical, off_t size, time_t mtime, int fd, char * line, size_t linesz) static
Definition at line 122 of file scan_engine.c.
References brix_scan_opts_t::alg, brix_integrity_opts_t::allow_xattr_cache, brix_integrity_get_fd(), brix_scan_record_file(), brix_scan_summary_t::bytes, brix_integrity_info_t::hex, scan_walk_ctx_t::log, brix_scan_summary_t::mismatch, brix_scan_summary_t::missing, brix_integrity_opts_t::no_compute, brix_scan_summary_t::ok, scan_walk_ctx_t::opts, scan_stored(), scan_walk_ctx_t::sum, and brix_scan_summary_t::unreadable.
Referenced by scan_walk_file().
scan_append()
static int scan_append (u_char ** buf, size_t * cap, size_t * used, const char * line, size_t llen) static
Definition at line 54 of file scan_engine.c.
Referenced by scan_catalog_emit_object(), scan_catalog_verify_one(), and scan_walk_file().
scan_catalog_emit_object()
static int scan_catalog_emit_object (void * ctx, const brix_sd_catalog_ent_t * ent) static
Definition at line 368 of file scan_engine.c.
References brix_scan_record_object(), scan_catalog_ctx_t::buf, scan_catalog_ctx_t::cap, brix_scan_summary_t::files, brix_sd_catalog_ent_t::have_stat, brix_sd_catalog_ent_t::key, brix_sd_catalog_ent_t::mtime, brix_scan_summary_t::ok, scan_catalog_ctx_t::oom, brix_sd_catalog_ent_t::path, scan_append(), SCAN_LINE_MAX, brix_sd_catalog_ent_t::size, scan_catalog_ctx_t::sum, and scan_catalog_ctx_t::used.
Referenced by brix_scan_run_inventory().
scan_catalog_verify_one()
static int scan_catalog_verify_one (void * ctx, const brix_sd_catalog_ent_t * ent) static
Definition at line 498 of file scan_engine.c.
References scan_verify_ctx_t::alg, brix_scan_record_file(), BRIX_SD_O_READ, scan_verify_ctx_t::buf, scan_verify_ctx_t::cap, brix_scan_summary_t::files, brix_sd_catalog_ent_t::have_stat, brix_sd_catalog_ent_t::key, brix_sd_catalog_ent_t::mtime, scan_verify_ctx_t::oom, brix_sd_catalog_ent_t::path, scan_append(), SCAN_LINE_MAX, scan_verify_obj_record(), scan_verify_ctx_t::sd, brix_sd_catalog_ent_t::size, scan_verify_ctx_t::sum, brix_scan_summary_t::unreadable, and scan_verify_ctx_t::used.
Referenced by brix_scan_run_verify_catalog().
scan_display_path()
static void scan_display_path (const char * logical, char * out, size_t outsz) static
Definition at line 25 of file scan_engine.c.
Referenced by scan_walk_file().
scan_stored()
static const char * scan_stored (scan_walk_ctx_t * cc, int fd, const char * logical, brix_integrity_info_t * info) static
Definition at line 89 of file scan_engine.c.
References brix_scan_opts_t::alg, brix_integrity_opts_t::allow_xattr_cache, brix_integrity_get_fd(), brix_integrity_info_t::hex, scan_walk_ctx_t::log, brix_integrity_opts_t::no_compute, and scan_walk_ctx_t::opts.
Referenced by scan_action_dump(), scan_action_fill(), scan_action_inspect(), and scan_action_verify().
scan_verify_obj_record()
static int scan_verify_obj_record (scan_verify_ctx_t * cc, const char * logical, const brix_sd_catalog_ent_t * ent, brix_sd_obj_t * obj, char * line, size_t linesz) static
Definition at line 445 of file scan_engine.c.
References scan_verify_ctx_t::alg, brix_integrity_opts_t::allow_xattr_cache, brix_integrity_get_fd(), brix_scan_record_file(), brix_scan_summary_t::bytes, brix_sd_catalog_ent_t::have_stat, brix_integrity_info_t::hex, scan_verify_ctx_t::log, brix_scan_summary_t::mismatch, brix_scan_summary_t::missing, brix_sd_catalog_ent_t::mtime, brix_integrity_opts_t::no_compute, brix_scan_summary_t::ok, brix_sd_catalog_ent_t::size, scan_verify_ctx_t::sum, and brix_scan_summary_t::unreadable.
Referenced by scan_catalog_verify_one().
scan_walk_file()
static ngx_int_t scan_walk_file (void * cookie, const char * logical, const brix_vfs_stat_t * st, int fd) static
Definition at line 253 of file scan_engine.c.
References BRIX_SCAN_COMPARE, BRIX_SCAN_DRIFT, BRIX_SCAN_DUMP, BRIX_SCAN_FILL, BRIX_SCAN_INSPECT, BRIX_SCAN_INVENTORY, BRIX_SCAN_VERIFY, scan_walk_ctx_t::buf, scan_walk_ctx_t::cap, brix_scan_summary_t::files, brix_scan_opts_t::mode, brix_vfs_stat_t::mtime, scan_walk_ctx_t::oom, scan_walk_ctx_t::opts, PATH_MAX, scan_action_drift(), scan_action_dump(), scan_action_fill(), scan_action_inspect(), scan_action_inventory(), scan_action_verify(), scan_append(), scan_display_path(), SCAN_LINE_MAX, brix_vfs_stat_t::size, scan_walk_ctx_t::sum, and scan_walk_ctx_t::used.
Referenced by brix_scan_run().