nginx-xrootd: src/fs/scan/scan_http.c File Reference
scan_http.c File Reference
#include "scan_engine.h"
#include "scan_record.h"
#include "observability/dashboard/dashboard_http.h"
#include "fs/path/beneath.h"
#include "core/http/http_headers.h"
#include "protocols/root/protocol/opcodes.h"
#include "fs/vfs/vfs.h"
#include "fs/vfs/vfs_backend_registry.h"
#include <fcntl.h>
#include <limits.h>
#include <string.h>
#include <sys/statvfs.h>
#include <unistd.h>
Data Structures
struct scan_arg_spec_t
struct scan_request_t
struct scan_result_t
struct scan_err_t
Functions
static ngx_int_t scan_arg (ngx_http_request_t *r, const scan_arg_spec_t *spec)
static ngx_int_t scan_get_path (ngx_http_request_t *r, char *out, size_t outsz)
static ngx_int_t scan_err_http (uint16_t code)
static ngx_int_t scan_send (ngx_http_request_t *r, u_char *body, size_t len)
static ngx_int_t scan_health (ngx_http_request_t *r, const char *root_canon)
static ngx_int_t scan_read_mode (ngx_http_request_t *r, scan_request_t *req)
static ngx_int_t scan_parse_query (ngx_http_request_t *r, ngx_http_brix_dashboard_loc_conf_t *conf, scan_request_t *req)
static ngx_int_t scan_run_walk (ngx_http_request_t *r, ngx_http_brix_dashboard_loc_conf_t *conf, scan_request_t *req, scan_result_t *res, scan_err_t *err)
static ngx_int_t scan_render (ngx_http_request_t *r, scan_result_t *res)
ngx_int_t ngx_http_brix_dashboard_scan_handler (ngx_http_request_t *r)
Function Documentation
ngx_http_brix_dashboard_scan_handler()
ngx_int_t ngx_http_brix_dashboard_scan_handler (ngx_http_request_t * r)
Definition at line 392 of file scan_http.c.
References brix_http_source_offer(), scan_result_t::buf, scan_err_t::code, brix_scan_summary_t::elapsed_s, scan_request_t::mode_raw, scan_err_t::msg, ngx_http_brix_dashboard_check_auth(), ngx_http_brix_dashboard_module, scan_request_t::relpath, scan_err_http(), scan_health(), scan_parse_query(), scan_read_mode(), scan_render(), ngx_http_brix_dashboard_loc_conf_t::scan_root_canon, scan_run_walk(), and scan_result_t::summary.
scan_arg()
static ngx_int_t scan_arg (ngx_http_request_t * r, const scan_arg_spec_t * spec) static
Definition at line 59 of file scan_http.c.
References scan_arg_spec_t::dflt, scan_arg_spec_t::name, scan_arg_spec_t::namelen, ngx_memcpy, scan_arg_spec_t::out, and scan_arg_spec_t::outsz.
Referenced by scan_get_path(), scan_parse_query(), and scan_read_mode().
scan_err_http()
static ngx_int_t scan_err_http (uint16_t code) static
Definition at line 118 of file scan_http.c.
References code, kXR_ArgInvalid, kXR_NoMemory, kXR_NotAuthorized, and kXR_NotFound.
Referenced by ngx_http_brix_dashboard_scan_handler().
scan_get_path()
static ngx_int_t scan_get_path (ngx_http_request_t * r, char * out, size_t outsz) static
Definition at line 96 of file scan_http.c.
References ngx_memcpy, and scan_arg().
Referenced by scan_parse_query().
scan_health()
static ngx_int_t scan_health (ngx_http_request_t * r, const char * root_canon) static
Definition at line 164 of file scan_http.c.
References brix_scan_record_health(), ngx_memcpy, and scan_send().
Referenced by ngx_http_brix_dashboard_scan_handler().
scan_parse_query()
static ngx_int_t scan_parse_query (ngx_http_request_t * r, ngx_http_brix_dashboard_loc_conf_t * conf, scan_request_t * req) static
Definition at line 265 of file scan_http.c.
References brix_scan_opts_t::alg, brix_scan_mode_parse(), brix_scan_opts_t::max_depth, brix_scan_opts_t::max_files, brix_scan_opts_t::mode, scan_request_t::mode_raw, scan_request_t::opts, scan_request_t::relpath, scan_arg(), scan_get_path(), and ngx_http_brix_dashboard_loc_conf_t::scan_max_files.
Referenced by ngx_http_brix_dashboard_scan_handler().
scan_read_mode()
static ngx_int_t scan_read_mode (ngx_http_request_t * r, scan_request_t * req) static
Definition at line 243 of file scan_http.c.
References scan_request_t::mode_raw, scan_request_t::opts, and scan_arg().
Referenced by ngx_http_brix_dashboard_scan_handler().
scan_render()
static ngx_int_t scan_render (ngx_http_request_t * r, scan_result_t * res) static
Definition at line 357 of file scan_http.c.
References brix_scan_record_summary(), scan_result_t::buf, ngx_memcpy, scan_send(), scan_result_t::summary, and scan_result_t::used.
Referenced by ngx_http_brix_dashboard_scan_handler().
scan_run_walk()
static ngx_int_t scan_run_walk (ngx_http_request_t * r, ngx_http_brix_dashboard_loc_conf_t * conf, scan_request_t * req, scan_result_t * res, scan_err_t * err) static
Definition at line 309 of file scan_http.c.
References brix_beneath_open_root(), BRIX_SCAN_INVENTORY, brix_scan_run(), brix_scan_run_inventory(), brix_scan_run_verify_catalog(), BRIX_SCAN_VERIFY, BRIX_SD_CAP_CATALOG, brix_sd_caps(), brix_vfs_backend_resolve(), scan_result_t::buf, scan_result_t::cap, close(), scan_err_t::code, brix_scan_opts_t::mode, scan_err_t::msg, scan_request_t::opts, scan_request_t::relpath, ngx_http_brix_dashboard_loc_conf_t::scan_root_canon, scan_result_t::summary, and scan_result_t::used.
Referenced by ngx_http_brix_dashboard_scan_handler().
scan_send()
static ngx_int_t scan_send (ngx_http_request_t * r, u_char * body, size_t len) static
Definition at line 131 of file scan_http.c.
References ngx_pcalloc().
Referenced by scan_health(), and scan_render().