nginx-xrootd: src/fs/scan/scan_engine.h File Reference
scan_engine.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include "scan_record.h"
#include "fs/backend/sd.h"
Data Structures
struct brix_scan_opts_t
Enumerations
enum brix_scan_mode_t {
BRIX_SCAN_DUMP = 0 , BRIX_SCAN_VERIFY , BRIX_SCAN_FILL , BRIX_SCAN_COMPARE ,
BRIX_SCAN_INSPECT , BRIX_SCAN_INVENTORY , BRIX_SCAN_DRIFT
}
Functions
ngx_int_t brix_scan_mode_parse (const char *name, brix_scan_mode_t *out)
ngx_int_t brix_scan_run (ngx_log_t *log, int rootfd, const char *logical, const brix_scan_opts_t *opts, u_char **buf, size_t *cap, size_t *used, brix_scan_summary_t *summary, uint16_t *err_code, char *err_msg, size_t err_sz)
ngx_int_t brix_scan_run_inventory (ngx_log_t *log, brix_sd_instance_t *sd, const brix_scan_opts_t *opts, u_char **buf, size_t *cap, size_t *used, brix_scan_summary_t *summary, uint16_t *err_code, char *err_msg, size_t err_sz)
ngx_int_t brix_scan_run_verify_catalog (ngx_log_t *log, brix_sd_instance_t *sd, const brix_scan_opts_t *opts, u_char **buf, size_t *cap, size_t *used, brix_scan_summary_t *summary, uint16_t *err_code, char *err_msg, size_t err_sz)
Enumeration Type Documentation
brix_scan_mode_t
enum brix_scan_mode_t
Enumerator
BRIX_SCAN_DUMP
BRIX_SCAN_VERIFY
BRIX_SCAN_FILL
BRIX_SCAN_COMPARE
BRIX_SCAN_INSPECT
BRIX_SCAN_INVENTORY
BRIX_SCAN_DRIFT
Definition at line 23 of file scan_engine.h.
Function Documentation
brix_scan_mode_parse()
ngx_int_t brix_scan_mode_parse (const char * name, brix_scan_mode_t * out)
Definition at line 38 of file scan_engine.c.
References BRIX_SCAN_COMPARE, BRIX_SCAN_DRIFT, BRIX_SCAN_DUMP, BRIX_SCAN_FILL, BRIX_SCAN_INSPECT, BRIX_SCAN_INVENTORY, BRIX_SCAN_VERIFY, and name.
Referenced by ngx_http_brix_dashboard_scan_handler().
brix_scan_run()
ngx_int_t brix_scan_run (ngx_log_t * log, int rootfd, const char * logical, const brix_scan_opts_t * opts, u_char ** buf, size_t * cap, size_t * used, brix_scan_summary_t * summary, uint16_t * err_code, char * err_msg, size_t err_sz)
Definition at line 304 of file scan_engine.c.
References brix_vfs_walk(), BRIX_VFS_WALK_NONE, BRIX_VFS_WALK_OTHER, scan_walk_ctx_t::buf, scan_walk_ctx_t::cap, kXR_ArgInvalid, kXR_IOError, kXR_NoMemory, kXR_NotFound, log, scan_walk_ctx_t::log, brix_scan_opts_t::max_depth, brix_vfs_walk_opts_t::max_depth, brix_scan_opts_t::max_files, brix_vfs_walk_opts_t::max_files, scan_walk_ctx_t::oom, brix_vfs_walk_opts_t::open_files, scan_walk_ctx_t::opts, scan_walk_file(), scan_walk_ctx_t::sum, and scan_walk_ctx_t::used.
Referenced by ngx_http_brix_dashboard_scan_handler().
brix_scan_run_inventory()
ngx_int_t brix_scan_run_inventory (ngx_log_t * log, brix_sd_instance_t * sd, const brix_scan_opts_t * opts, u_char ** buf, size_t * cap, size_t * used, brix_scan_summary_t * summary, uint16_t * err_code, char * err_msg, size_t err_sz)
Definition at line 391 of file scan_engine.c.
References brix_vfs_enumerate_catalog(), scan_catalog_ctx_t::buf, scan_catalog_ctx_t::cap, kXR_IOError, kXR_NoMemory, kXR_Unsupported, log, scan_catalog_ctx_t::oom, scan_catalog_emit_object(), scan_catalog_ctx_t::sum, and scan_catalog_ctx_t::used.
Referenced by ngx_http_brix_dashboard_scan_handler().
brix_scan_run_verify_catalog()
ngx_int_t brix_scan_run_verify_catalog (ngx_log_t * log, brix_sd_instance_t * sd, const brix_scan_opts_t * opts, u_char ** buf, size_t * cap, size_t * used, brix_scan_summary_t * summary, uint16_t * err_code, char * err_msg, size_t err_sz)
Definition at line 531 of file scan_engine.c.
References scan_verify_ctx_t::alg, brix_scan_opts_t::alg, brix_vfs_enumerate_catalog(), scan_verify_ctx_t::buf, scan_verify_ctx_t::cap, kXR_IOError, kXR_NoMemory, kXR_Unsupported, log, scan_verify_ctx_t::log, scan_verify_ctx_t::oom, scan_catalog_verify_one(), scan_verify_ctx_t::sd, scan_verify_ctx_t::sum, and scan_verify_ctx_t::used.
Referenced by ngx_http_brix_dashboard_scan_handler().