nginx-xrootd: src/fs/scan/scan_engine_catalog.c File Reference
scan_engine_catalog.c File Reference
#include "scan_engine.h"
#include "scan_engine_internal.h"
#include "core/compat/integrity_info.h"
#include "fs/vfs/vfs.h"
#include "protocols/root/protocol/opcodes.h"
#include <limits.h>
#include <string.h>
#include <strings.h>
Data Structures
struct scan_catalog_ctx_t
struct scan_verify_ctx_t
struct scan_verify_obj_ctx_t
Functions
static int scan_catalog_emit_object (void *ctx, const brix_sd_catalog_ent_t *ent)
ngx_int_t brix_scan_run_inventory (ngx_log_t *log, brix_sd_instance_t *sd, const brix_scan_opts_t *opts, u_char **buf, size_t *cap, size_t *used, brix_scan_summary_t *summary, uint16_t *err_code, char *err_msg, size_t err_sz)
static int scan_verify_obj_record (scan_verify_obj_ctx_t *v)
static int scan_catalog_verify_one (void *ctx, const brix_sd_catalog_ent_t *ent)
ngx_int_t brix_scan_run_verify_catalog (ngx_log_t *log, brix_sd_instance_t *sd, const brix_scan_opts_t *opts, u_char **buf, size_t *cap, size_t *used, brix_scan_summary_t *summary, uint16_t *err_code, char *err_msg, size_t err_sz)
Function Documentation
brix_scan_run_inventory()
ngx_int_t brix_scan_run_inventory (ngx_log_t * log, brix_sd_instance_t * sd, const brix_scan_opts_t * opts, u_char ** buf, size_t * cap, size_t * used, brix_scan_summary_t * summary, uint16_t * err_code, char * err_msg, size_t err_sz)
Definition at line 55 of file scan_engine_catalog.c.
References brix_vfs_enumerate_catalog(), scan_catalog_ctx_t::buf, scan_catalog_ctx_t::cap, kXR_IOError, kXR_NoMemory, kXR_Unsupported, log, scan_catalog_ctx_t::oom, scan_catalog_emit_object(), scan_catalog_ctx_t::sum, and scan_catalog_ctx_t::used.
Referenced by scan_run_walk().
brix_scan_run_verify_catalog()
ngx_int_t brix_scan_run_verify_catalog (ngx_log_t * log, brix_sd_instance_t * sd, const brix_scan_opts_t * opts, u_char ** buf, size_t * cap, size_t * used, brix_scan_summary_t * summary, uint16_t * err_code, char * err_msg, size_t err_sz)
Definition at line 221 of file scan_engine_catalog.c.
References brix_scan_opts_t::alg, scan_verify_ctx_t::alg, brix_vfs_enumerate_catalog(), scan_verify_ctx_t::buf, scan_verify_ctx_t::cap, kXR_IOError, kXR_NoMemory, kXR_Unsupported, log, scan_verify_ctx_t::log, scan_verify_ctx_t::oom, scan_catalog_verify_one(), scan_verify_ctx_t::sd, scan_verify_ctx_t::sum, and scan_verify_ctx_t::used.
Referenced by scan_run_walk().
scan_catalog_emit_object()
static int scan_catalog_emit_object (void * ctx, const brix_sd_catalog_ent_t * ent) static
Definition at line 32 of file scan_engine_catalog.c.
References brix_scan_record_object(), scan_catalog_ctx_t::buf, scan_catalog_ctx_t::cap, brix_scan_summary_t::files, brix_sd_catalog_ent_t::have_stat, brix_sd_catalog_ent_t::key, brix_sd_catalog_ent_t::mtime, brix_scan_summary_t::ok, scan_catalog_ctx_t::oom, brix_sd_catalog_ent_t::path, scan_append(), SCAN_LINE_MAX, brix_sd_catalog_ent_t::size, scan_catalog_ctx_t::sum, and scan_catalog_ctx_t::used.
Referenced by brix_scan_run_inventory().
scan_catalog_verify_one()
static int scan_catalog_verify_one (void * ctx, const brix_sd_catalog_ent_t * ent) static
Definition at line 179 of file scan_engine_catalog.c.
References scan_verify_ctx_t::alg, brix_scan_record_file(), BRIX_SD_O_READ, scan_verify_ctx_t::buf, scan_verify_ctx_t::cap, scan_verify_obj_ctx_t::cc, scan_verify_obj_ctx_t::ent, brix_scan_summary_t::files, brix_sd_catalog_ent_t::have_stat, brix_sd_catalog_ent_t::key, scan_verify_obj_ctx_t::line, scan_verify_obj_ctx_t::linesz, scan_verify_obj_ctx_t::logical, brix_sd_catalog_ent_t::mtime, scan_verify_obj_ctx_t::obj, scan_verify_ctx_t::oom, brix_sd_catalog_ent_t::path, scan_append(), SCAN_LINE_MAX, scan_verify_obj_record(), scan_verify_ctx_t::sd, brix_sd_catalog_ent_t::size, scan_verify_ctx_t::sum, brix_scan_summary_t::unreadable, and scan_verify_ctx_t::used.
Referenced by brix_scan_run_verify_catalog().
scan_verify_obj_record()
static int scan_verify_obj_record (scan_verify_obj_ctx_t * v) static
Definition at line 127 of file scan_engine_catalog.c.
References scan_verify_ctx_t::alg, brix_integrity_opts_t::allow_xattr_cache, brix_integrity_get_fd(), brix_scan_record_file(), brix_scan_summary_t::bytes, scan_verify_obj_ctx_t::cc, scan_verify_obj_ctx_t::ent, brix_sd_catalog_ent_t::have_stat, brix_integrity_info_t::hex, scan_verify_obj_ctx_t::line, scan_verify_obj_ctx_t::linesz, scan_verify_ctx_t::log, scan_verify_obj_ctx_t::logical, brix_scan_summary_t::mismatch, brix_scan_summary_t::missing, brix_sd_catalog_ent_t::mtime, ngx_memcpy, brix_integrity_opts_t::no_compute, scan_verify_obj_ctx_t::obj, brix_scan_summary_t::ok, brix_sd_catalog_ent_t::size, scan_verify_ctx_t::sum, and brix_scan_summary_t::unreadable.
Referenced by scan_catalog_verify_one().