nginx-xrootd: src/fs/scan/scan_unittest.c File Reference
scan_unittest.c File Reference
#include "scan_record.h"
#include "scan_throttle.h"
#include "scan_emit.h"
#include "scan_drift.h"
#include <math.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
Macros
#define CHECK(cond, msg)
#define STREQ(a, b) (strcmp((a), (b)) == 0)
#define CLOSE(a, b, eps) (fabs((double)(a) - (double)(b)) < (eps))
#define PAY(seq) ((void *) (uintptr_t) (seq))
Functions
static void test_json_escape (void)
static void test_record_file (void)
static void test_record_cursor_summary (void)
static void test_record_inspect_health (void)
static void test_record_object_drift (void)
static void test_token_bucket (void)
static void test_budget (void)
static void test_adapt (void)
static void emit_collect (void *ctx, uint64_t seq, void *payload)
static void test_emitq_ordering (void)
static void test_emitq_errors (void)
static void orphan_collect (void *ctx, const char *key, int64_t size)
static void test_drift (void)
int main (void)
Variables
static int g_fail
static uint64_t g_emit_order [16]
static int g_emit_n
static int g_orphan_n
static char g_orphan_keys [8][64]
static int64_t g_orphan_sizes [8]
Macro Definition Documentation
CHECK
#define CHECK (cond, msg)
Value:
    do {                                                                       \
        if (!(cond)) {                                                         \
            fprintf(stderr, "FAIL: %s (%s:%d)\n", (msg), __FILE__, __LINE__);  \
            g_fail++;                                                          \
        }                                                                      \
    } while (0)
Definition at line 23 of file scan_unittest.c.
CLOSE
#define CLOSE (a, b, eps) (fabs((double)(a) - (double)(b)) < (eps))
Definition at line 32 of file scan_unittest.c.
PAY
#define PAY (seq) ((void *) (uintptr_t) (seq))
Definition at line 245 of file scan_unittest.c.
STREQ
#define STREQ (a, b) (strcmp((a), (b)) == 0)
Definition at line 31 of file scan_unittest.c.
Function Documentation
emit_collect()
static void emit_collect (void * ctx, uint64_t seq, void * payload) static
Definition at line 235 of file scan_unittest.c.
References CHECK, g_emit_n, and g_emit_order.
Referenced by test_emitq_errors(), and test_emitq_ordering().
main()
int main (void)
Definition at line 361 of file scan_unittest.c.
References g_fail, test_adapt(), test_budget(), test_drift(), test_emitq_errors(), test_emitq_ordering(), test_json_escape(), test_record_cursor_summary(), test_record_file(), test_record_inspect_health(), test_record_object_drift(), and test_token_bucket().
orphan_collect()
static void orphan_collect (void * ctx, const char * key, int64_t size) static
Definition at line 299 of file scan_unittest.c.
References g_orphan_keys, g_orphan_n, g_orphan_sizes, and key.
Referenced by test_drift().
test_adapt()
static void test_adapt (void) static
Definition at line 212 of file scan_unittest.c.
References brix_scan_adapt(), CHECK, and CLOSE.
Referenced by main().
test_budget()
static void test_budget (void) static
Definition at line 194 of file scan_unittest.c.
References brix_scan_budget_hit(), CHECK, brix_scan_budget_t::max_bytes, and brix_scan_budget_t::max_seconds.
Referenced by main().
test_drift()
static void test_drift (void) static
Definition at line 310 of file scan_unittest.c.
References BRIX_DRIFT_IN_BOTH, BRIX_DRIFT_NAMESPACE_ONLY, BRIX_DRIFT_SIZE_MISMATCH, brix_scan_driftset_add(), brix_scan_driftset_create(), brix_scan_driftset_free(), brix_scan_driftset_match(), brix_scan_driftset_orphans(), CHECK, g_orphan_keys, g_orphan_n, g_orphan_sizes, orphan_collect(), and s.
Referenced by main().
test_emitq_errors()
static void test_emitq_errors (void) static
Definition at line 272 of file scan_unittest.c.
References brix_scan_emitq_init(), brix_scan_emitq_submit(), CHECK, emit_collect(), g_emit_n, and PAY.
Referenced by main().
test_emitq_ordering()
static void test_emitq_ordering (void) static
Definition at line 248 of file scan_unittest.c.
References brix_scan_emitq_init(), brix_scan_emitq_submit(), CHECK, emit_collect(), g_emit_n, g_emit_order, and PAY.
Referenced by main().
test_json_escape()
static void test_json_escape (void) static
Definition at line 37 of file scan_unittest.c.
References brix_scan_json_escape(), CHECK, and STREQ.
Referenced by main().
test_record_cursor_summary()
static void test_record_cursor_summary (void) static
Definition at line 91 of file scan_unittest.c.
References brix_scan_record_cursor(), brix_scan_record_summary(), CHECK, s, and STREQ.
Referenced by main().
test_record_file()
static void test_record_file (void) static
Definition at line 64 of file scan_unittest.c.
References brix_scan_record_file(), CHECK, and STREQ.
Referenced by main().
test_record_inspect_health()
static void test_record_inspect_health (void) static
Definition at line 111 of file scan_unittest.c.
References brix_scan_record_health(), brix_scan_record_inspect(), CHECK, and STREQ.
Referenced by main().
test_record_object_drift()
static void test_record_object_drift (void) static
Definition at line 135 of file scan_unittest.c.
References brix_scan_record_drift(), brix_scan_record_object(), CHECK, and STREQ.
Referenced by main().
test_token_bucket()
static void test_token_bucket (void) static
Definition at line 171 of file scan_unittest.c.
References brix_scan_tb_consume(), brix_scan_tb_init(), brix_scan_tb_wait_ns(), CHECK, and CLOSE.
Referenced by main().
Variable Documentation
g_emit_n
int g_emit_n static
Definition at line 232 of file scan_unittest.c.
Referenced by emit_collect(), test_emitq_errors(), and test_emitq_ordering().
g_emit_order
uint64_t g_emit_order[16] static
Definition at line 231 of file scan_unittest.c.
Referenced by emit_collect(), and test_emitq_ordering().
g_fail
int g_fail static
Definition at line 21 of file scan_unittest.c.
Referenced by main().
g_orphan_keys
char g_orphan_keys[8][64] static
Definition at line 295 of file scan_unittest.c.
Referenced by orphan_collect(), and test_drift().
g_orphan_n
int g_orphan_n static
Definition at line 294 of file scan_unittest.c.
Referenced by orphan_collect(), and test_drift().
g_orphan_sizes
int64_t g_orphan_sizes[8] static
Definition at line 296 of file scan_unittest.c.
Referenced by orphan_collect(), and test_drift().