nginx-xrootd: src/fs/scan/scan_throttle.c File Reference
scan_throttle.c File Reference
#include "scan_throttle.h"
Functions
void brix_scan_tb_init (brix_scan_tb_t *tb, double rate_bps, double capacity, uint64_t now_ns)
void brix_scan_tb_refill (brix_scan_tb_t *tb, uint64_t now_ns)
uint64_t brix_scan_tb_wait_ns (brix_scan_tb_t *tb, double need, uint64_t now_ns)
void brix_scan_tb_consume (brix_scan_tb_t *tb, double need)
int brix_scan_budget_hit (const brix_scan_budget_t *b, uint64_t bytes_done, double elapsed_s)
double brix_scan_adapt (int foreground_active, double latency_ewma_ms, double nominal_latency_ms)
Function Documentation
brix_scan_adapt()
double brix_scan_adapt (int foreground_active, double latency_ewma_ms, double nominal_latency_ms)
Definition at line 79 of file scan_throttle.c.
Referenced by test_adapt().
brix_scan_budget_hit()
int brix_scan_budget_hit (const brix_scan_budget_t * b, uint64_t bytes_done, double elapsed_s)
Definition at line 66 of file scan_throttle.c.
References brix_scan_budget_t::max_bytes, and brix_scan_budget_t::max_seconds.
Referenced by test_budget().
brix_scan_tb_consume()
void brix_scan_tb_consume (brix_scan_tb_t * tb, double need)
Definition at line 57 of file scan_throttle.c.
References brix_scan_tb_t::capacity, and brix_scan_tb_t::tokens.
Referenced by test_token_bucket().
brix_scan_tb_init()
void brix_scan_tb_init (brix_scan_tb_t * tb, double rate_bps, double capacity, uint64_t now_ns)
Definition at line 11 of file scan_throttle.c.
References brix_scan_tb_t::capacity, brix_scan_tb_t::last_ns, now_ns(), brix_scan_tb_t::rate_bps, and brix_scan_tb_t::tokens.
Referenced by test_token_bucket().
brix_scan_tb_refill()
void brix_scan_tb_refill (brix_scan_tb_t * tb, uint64_t now_ns)
Definition at line 21 of file scan_throttle.c.
References brix_scan_tb_t::capacity, brix_scan_tb_t::last_ns, now_ns(), brix_scan_tb_t::rate_bps, and brix_scan_tb_t::tokens.
Referenced by brix_scan_tb_wait_ns().
brix_scan_tb_wait_ns()
uint64_t brix_scan_tb_wait_ns (brix_scan_tb_t * tb, double need, uint64_t now_ns)
Definition at line 41 of file scan_throttle.c.
References brix_scan_tb_refill(), now_ns(), brix_scan_tb_t::rate_bps, and brix_scan_tb_t::tokens.
Referenced by test_token_bucket().