nginx-xrootd: src/fs/scan/scan_drift.c File Reference
scan_drift.c File Reference
#include "scan_drift.h"
#include <stdlib.h>
#include <string.h>
Data Structures
struct drift_slot
struct brix_scan_driftset_t
Functions
static size_t drift_hash (const char *s)
static size_t drift_roundup_pow2 (size_t v)
brix_scan_driftset_t * brix_scan_driftset_create (size_t expected)
void brix_scan_driftset_free (brix_scan_driftset_t *s)
static size_t drift_probe (const drift_slot *tab, size_t cap, const char *key)
static int drift_grow (brix_scan_driftset_t *s)
int brix_scan_driftset_add (brix_scan_driftset_t *s, const char *key, int64_t size)
brix_scan_drift_class_t brix_scan_driftset_match (brix_scan_driftset_t *s, const char *key, int64_t ns_size, int64_t *cat_size)
void brix_scan_driftset_orphans (brix_scan_driftset_t *s, brix_scan_orphan_cb cb, void *ctx)
Function Documentation
brix_scan_driftset_add()
int brix_scan_driftset_add (brix_scan_driftset_t * s, const char * key, int64_t size)
Definition at line 113 of file scan_drift.c.
References drift_grow(), drift_probe(), key, and s.
Referenced by test_drift().
brix_scan_driftset_create()
brix_scan_driftset_t * brix_scan_driftset_create (size_t expected)
Definition at line 46 of file scan_drift.c.
References drift_roundup_pow2(), and s.
Referenced by test_drift().
brix_scan_driftset_free()
void brix_scan_driftset_free (brix_scan_driftset_t * s)
Definition at line 63 of file scan_drift.c.
References s.
Referenced by test_drift().
brix_scan_driftset_match()
brix_scan_drift_class_t brix_scan_driftset_match (brix_scan_driftset_t * s, const char * key, int64_t ns_size, int64_t * cat_size)
Definition at line 138 of file scan_drift.c.
References BRIX_DRIFT_IN_BOTH, BRIX_DRIFT_NAMESPACE_ONLY, BRIX_DRIFT_SIZE_MISMATCH, drift_probe(), key, and s.
Referenced by test_drift().
brix_scan_driftset_orphans()
void brix_scan_driftset_orphans (brix_scan_driftset_t * s, brix_scan_orphan_cb cb, void * ctx)
Definition at line 155 of file scan_drift.c.
References s.
Referenced by test_drift().
drift_grow()
static int drift_grow (brix_scan_driftset_t * s) static
Definition at line 91 of file scan_drift.c.
References drift_probe(), and s.
Referenced by brix_scan_driftset_add().
drift_hash()
static size_t drift_hash (const char * s) static
Definition at line 26 of file scan_drift.c.
References s.
Referenced by drift_probe().
drift_probe()
static size_t drift_probe (const drift_slot * tab, size_t cap, const char * key) static
Definition at line 80 of file scan_drift.c.
References drift_hash(), and key.
Referenced by brix_scan_driftset_add(), brix_scan_driftset_match(), and drift_grow().
drift_roundup_pow2()
static size_t drift_roundup_pow2 (size_t v) static
Definition at line 36 of file scan_drift.c.
Referenced by brix_scan_driftset_create().