nginx-xrootd: src/observability/pmark/scitag.c File Reference
scitag.c File Reference
#include "pmark.h"
Macros
#define BRIX_PMARK_SCITAG_KEY "scitag.flow="
#define BRIX_PMARK_SCITAG_KEY_LEN (sizeof(BRIX_PMARK_SCITAG_KEY) - 1)
Functions
static int pmark_is_param_boundary (char ch)
static ngx_int_t pmark_parse_flow_value (const char *p, ngx_uint_t *exp, ngx_uint_t *act)
ngx_int_t brix_pmark_parse_scitag (const char *cgi, ngx_uint_t *exp, ngx_uint_t *act)
Macro Definition Documentation
BRIX_PMARK_SCITAG_KEY
#define BRIX_PMARK_SCITAG_KEY "scitag.flow="
Definition at line 24 of file scitag.c.
BRIX_PMARK_SCITAG_KEY_LEN
#define BRIX_PMARK_SCITAG_KEY_LEN (sizeof(BRIX_PMARK_SCITAG_KEY) - 1)
Definition at line 25 of file scitag.c.
Function Documentation
brix_pmark_parse_scitag()
ngx_int_t brix_pmark_parse_scitag (const char * cgi, ngx_uint_t * exp, ngx_uint_t * act)
Definition at line 75 of file scitag.c.
References BRIX_PMARK_SCITAG_KEY, BRIX_PMARK_SCITAG_KEY_LEN, pmark_is_param_boundary(), and pmark_parse_flow_value().
Referenced by brix_pmark_map_codes().
pmark_is_param_boundary()
static int pmark_is_param_boundary (char ch) inline static
Definition at line 29 of file scitag.c.
Referenced by brix_pmark_parse_scitag(), and pmark_parse_flow_value().
pmark_parse_flow_value()
static ngx_int_t pmark_parse_flow_value (const char * p, ngx_uint_t * exp, ngx_uint_t * act) static
Definition at line 41 of file scitag.c.
References brix_pmark_codes_valid(), BRIX_PMARK_FLOW_MAX, brix_pmark_flow_split(), and pmark_is_param_boundary().
Referenced by brix_pmark_parse_scitag().