nginx-xrootd: src/auth/token/scopes.c File Reference
scopes.c File Reference
#include "scopes.h"
#include <string.h>
Functions
static const char * token_scope_skip_spaces (const char *cursor)
static const char * token_scope_end (const char *scope_start)
static void token_scope_copy_path (brix_token_scope_t *scope, const char *path, size_t path_len)
static void token_scope_set_permission (brix_token_scope_t *scope, const char *permission, size_t permission_len)
int brix_token_parse_scopes (const char *scope_str, brix_token_scope_t *scopes, int max_scopes)
int brix_token_scope_path_matches (const char *scope_path, const char *request_path)
int brix_token_check_read (const brix_token_scope_t *scopes, int scope_count, const char *path)
int brix_token_check_write (const brix_token_scope_t *scopes, int scope_count, const char *path)
Function Documentation
brix_token_check_read()
int brix_token_check_read (const brix_token_scope_t * scopes, int scope_count, const char * path)
Definition at line 238 of file scopes.c.
References brix_token_scope_path_matches(), and read().
Referenced by brix_check_token_scope(), brix_identity_check_token_scope(), brix_token_authz_strategy(), webdav_check_token_scope(), webdav_handle_macaroon_request(), and webdav_handle_macaroon_token().
brix_token_check_write()
int brix_token_check_write (const brix_token_scope_t * scopes, int scope_count, const char * path)
Definition at line 265 of file scopes.c.
References brix_token_scope_path_matches().
Referenced by brix_check_token_scope(), brix_identity_check_token_scope(), brix_token_authz_strategy(), webdav_check_token_scope(), webdav_handle_macaroon_request(), and webdav_handle_macaroon_token().
brix_token_parse_scopes()
int brix_token_parse_scopes (const char * scope_str, brix_token_scope_t * scopes, int max_scopes)
Definition at line 126 of file scopes.c.
References token_scope_copy_path(), token_scope_end(), token_scope_set_permission(), and token_scope_skip_spaces().
Referenced by brix_token_meta_get(), brix_token_validate(), macaroon_parse_core(), and macaroon_rebuild_scope_raw().
brix_token_scope_path_matches()
int brix_token_scope_path_matches (const char * scope_path, const char * request_path)
Definition at line 206 of file scopes.c.
Referenced by brix_token_check_read(), brix_token_check_write(), and brix_token_issuer_path_ok().
token_scope_copy_path()
static void token_scope_copy_path (brix_token_scope_t * scope, const char * path, size_t path_len) static
Definition at line 50 of file scopes.c.
References BRIX_SCOPE_PATH_MAX, and brix_token_scope_t::path.
Referenced by brix_token_parse_scopes().
token_scope_end()
static const char * token_scope_end (const char * scope_start) static
Definition at line 33 of file scopes.c.
Referenced by brix_token_parse_scopes().
token_scope_set_permission()
static void token_scope_set_permission (brix_token_scope_t * scope, const char * permission, size_t permission_len) static
Definition at line 72 of file scopes.c.
References brix_token_scope_t::create, brix_token_scope_t::modify, brix_token_scope_t::read, and brix_token_scope_t::write.
Referenced by brix_token_parse_scopes().
token_scope_skip_spaces()
static const char * token_scope_skip_spaces (const char * cursor) static
Definition at line 23 of file scopes.c.
Referenced by brix_token_parse_scopes().