nginx-xrootd: src/fs/backend/sd.h File Reference
sd.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <stdint.h>
#include <errno.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/uio.h>
Data Structures
struct brix_sd_cred_t
struct brix_sd_space_t
struct brix_sd_catalog_ent_t
struct brix_sd_stat_t
struct brix_sd_dirent_t
struct brix_sd_setattr_t
struct brix_sd_instance_t
struct brix_sd_obj_t
struct brix_sd_dir_t
struct brix_sd_staged_t
struct brix_sd_driver_t
Macros
#define BRIX_SD_O_READ 0x01
#define BRIX_SD_O_WRITE 0x02
#define BRIX_SD_O_CREATE 0x04
#define BRIX_SD_O_EXCL 0x08
#define BRIX_SD_O_TRUNC 0x10
#define BRIX_SD_O_APPEND 0x20
#define BRIX_SD_O_DIR 0x40
#define BRIX_SD_O_NOFOLLOW 0x80 /* refuse a symlink at the final component */
Typedefs
typedef int(* brix_sd_catalog_cb) (void *ctx, const brix_sd_catalog_ent_t *ent)
Enumerations
enum brix_sd_cap_t {
BRIX_SD_CAP_FD = 1u << 0 , BRIX_SD_CAP_SENDFILE = 1u << 1 , BRIX_SD_CAP_RANDOM_WRITE = 1u << 2 , BRIX_SD_CAP_RANGE_READ = 1u << 3 ,
BRIX_SD_CAP_TRUNCATE = 1u << 4 , BRIX_SD_CAP_SERVER_COPY = 1u << 5 , BRIX_SD_CAP_XATTR = 1u << 6 , BRIX_SD_CAP_HARD_RENAME = 1u << 7 ,
BRIX_SD_CAP_DIRS = 1u << 8 , BRIX_SD_CAP_APPEND = 1u << 9 , BRIX_SD_CAP_IOURING = 1u << 10 , BRIX_SD_CAP_FSCS = 1u << 11 ,
BRIX_SD_CAP_NEARLINE = 1u << 12 , BRIX_SD_CAP_CATALOG = 1u << 13 , BRIX_SD_CAP_DIRS_WRITE = 1u << 14 , BRIX_SD_CAP_XATTR_WRITE = 1u << 15 ,
BRIX_SD_CAP_MEMFILE = 1u << 16
}
enum brix_sd_cred_kind_t { BRIX_SD_CRED_NONE = 0 , BRIX_SD_CRED_BEARER = 1u << 0 , BRIX_SD_CRED_PROXY_PEM = 1u << 1 , BRIX_SD_CRED_IDENTITY = 1u << 2 }
enum brix_cred_mode {
BRIX_CRED_SELECT = 0 , BRIX_CRED_PASSTHROUGH , BRIX_CRED_EXCHANGE , BRIX_CRED_DELEGATE ,
BRIX_CRED_MINT , BRIX_CRED_AUTO
}
enum brix_sd_residency_t { BRIX_SD_RES_ONLINE = 0 , BRIX_SD_RES_NEARLINE = 1 , BRIX_SD_RES_OFFLINE = 2 , BRIX_SD_RES_LOST = 3 }
Functions
static void brix_sd_obj_release (brix_sd_obj_t *o)
uint32_t brix_sd_caps (const brix_sd_instance_t *inst)
ngx_fd_t brix_sd_fd (const brix_sd_obj_t *obj)
const char * brix_sd_backend_name (const brix_sd_instance_t *inst)
ngx_int_t brix_sd_supports (const brix_sd_instance_t *inst, uint32_t required_caps)
uint32_t brix_sd_cred_accept (const brix_sd_instance_t *inst)
static brix_sd_obj_t * brix_sd_open_maybe_cred (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
static brix_sd_staged_t * brix_sd_staged_open_maybe_cred (brix_sd_instance_t *inst, const char *final_path, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
static ngx_int_t brix_sd_stat_maybe_cred (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out, const brix_sd_cred_t *cred)
static ngx_int_t brix_sd_unlink_maybe_cred (brix_sd_instance_t *inst, const char *path, int is_dir, const brix_sd_cred_t *cred)
static ngx_int_t brix_sd_mkdir_maybe_cred (brix_sd_instance_t *inst, const char *path, mode_t mode, const brix_sd_cred_t *cred)
static ngx_int_t brix_sd_rename_maybe_cred (brix_sd_instance_t *inst, const char *src, const char *dst, int noreplace, const brix_sd_cred_t *cred)
static ngx_int_t brix_sd_setattr_maybe_cred (brix_sd_instance_t *inst, const char *path, const brix_sd_setattr_t *attr, const brix_sd_cred_t *cred)
static ssize_t brix_sd_getxattr_maybe_cred (brix_sd_instance_t *inst, const char *path, const char *name, void *buf, size_t cap, const brix_sd_cred_t *cred)
static ssize_t brix_sd_listxattr_maybe_cred (brix_sd_instance_t *inst, const char *path, void *buf, size_t cap, const brix_sd_cred_t *cred)
static ngx_int_t brix_sd_setxattr_maybe_cred (brix_sd_instance_t *inst, const char *path, const char *name, const void *val, size_t len, int flags, const brix_sd_cred_t *cred)
static ngx_int_t brix_sd_removexattr_maybe_cred (brix_sd_instance_t *inst, const char *path, const char *name, const brix_sd_cred_t *cred)
static ngx_int_t brix_sd_server_copy_maybe_cred (brix_sd_instance_t *inst, const char *src, const char *dst, off_t *bytes_out, const brix_sd_cred_t *cred)
static brix_sd_dir_t * brix_sd_opendir_maybe_cred (brix_sd_instance_t *inst, const char *path, int *err_out, const brix_sd_cred_t *cred)
const brix_sd_driver_t * brix_sd_driver_find (const char *name)
ngx_uint_t brix_sd_driver_count (void)
const brix_sd_driver_t * brix_sd_driver_at (ngx_uint_t i)
brix_sd_instance_t * brix_sd_instance_create (ngx_log_t *log, const char *name, void *driver_conf, int *err_out)
void brix_sd_instance_destroy (brix_sd_instance_t *inst)
int brix_sd_posix_open_unconfined (const char *path, int sd_flags, mode_t mode)
int brix_sd_block_open_unconfined (const char *path, int sd_flags, mode_t mode)
const brix_sd_driver_t * brix_sd_default_driver (void)
brix_sd_instance_t * brix_sd_posix_borrow_instance (ngx_pool_t *pool, ngx_log_t *log, int rootfd, const char *root_canon)
static void brix_sd_posix_wrap (brix_sd_obj_t *obj, ngx_fd_t fd)
static ssize_t brix_sd_obj_preadv (brix_sd_obj_t *obj, const struct iovec *iov, int iovcnt, off_t off)
Variables
const brix_sd_driver_t brix_sd_posix_driver
const brix_sd_driver_t brix_sd_block_driver
Macro Definition Documentation
BRIX_SD_O_APPEND
#define BRIX_SD_O_APPEND 0x20
Definition at line 135 of file sd.h.
BRIX_SD_O_CREATE
#define BRIX_SD_O_CREATE 0x04
Definition at line 132 of file sd.h.
BRIX_SD_O_DIR
#define BRIX_SD_O_DIR 0x40
Definition at line 136 of file sd.h.
BRIX_SD_O_EXCL
#define BRIX_SD_O_EXCL 0x08
Definition at line 133 of file sd.h.
BRIX_SD_O_NOFOLLOW
#define BRIX_SD_O_NOFOLLOW 0x80 /* refuse a symlink at the final component */
Definition at line 137 of file sd.h.
BRIX_SD_O_READ
#define BRIX_SD_O_READ 0x01
Definition at line 130 of file sd.h.
BRIX_SD_O_TRUNC
#define BRIX_SD_O_TRUNC 0x10
Definition at line 134 of file sd.h.
BRIX_SD_O_WRITE
#define BRIX_SD_O_WRITE 0x02
Definition at line 131 of file sd.h.
Typedef Documentation
brix_sd_catalog_cb
typedef int(* brix_sd_catalog_cb) (void *ctx, const brix_sd_catalog_ent_t *ent)
Definition at line 264 of file sd.h.
Enumeration Type Documentation
brix_cred_mode
enum brix_cred_mode
Enumerator
BRIX_CRED_SELECT
BRIX_CRED_PASSTHROUGH
BRIX_CRED_EXCHANGE
BRIX_CRED_DELEGATE
BRIX_CRED_MINT
BRIX_CRED_AUTO
Definition at line 196 of file sd.h.
brix_sd_cap_t
enum brix_sd_cap_t
Enumerator
BRIX_SD_CAP_FD
BRIX_SD_CAP_SENDFILE
BRIX_SD_CAP_RANDOM_WRITE
BRIX_SD_CAP_RANGE_READ
BRIX_SD_CAP_TRUNCATE
BRIX_SD_CAP_SERVER_COPY
BRIX_SD_CAP_XATTR
BRIX_SD_CAP_HARD_RENAME
BRIX_SD_CAP_DIRS
BRIX_SD_CAP_APPEND
BRIX_SD_CAP_IOURING
BRIX_SD_CAP_FSCS
BRIX_SD_CAP_NEARLINE
BRIX_SD_CAP_CATALOG
BRIX_SD_CAP_DIRS_WRITE
BRIX_SD_CAP_XATTR_WRITE
BRIX_SD_CAP_MEMFILE
Definition at line 82 of file sd.h.
brix_sd_cred_kind_t
enum brix_sd_cred_kind_t
Enumerator
BRIX_SD_CRED_NONE
BRIX_SD_CRED_BEARER
BRIX_SD_CRED_PROXY_PEM
BRIX_SD_CRED_IDENTITY
Definition at line 116 of file sd.h.
brix_sd_residency_t
enum brix_sd_residency_t
Enumerator
BRIX_SD_RES_ONLINE
BRIX_SD_RES_NEARLINE
BRIX_SD_RES_OFFLINE
BRIX_SD_RES_LOST
Definition at line 230 of file sd.h.
Function Documentation
brix_sd_backend_name()
const char * brix_sd_backend_name (const brix_sd_instance_t * inst)
Definition at line 183 of file sd_registry.c.
Referenced by brix_cache_fill_body(), brix_cache_open_or_fill(), brix_vfs_file_backend_name(), brix_vfs_observe_ctx_op(), and vfs_cred_no_cap().
brix_sd_block_open_unconfined()
int brix_sd_block_open_unconfined (const char * path, int sd_flags, mode_t mode)
Definition at line 100 of file sd_block.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_TRUNC, and brix_sd_posix_open_unconfined().
Referenced by block_be_open(), and block_be_stat().
brix_sd_caps()
uint32_t brix_sd_caps (const brix_sd_instance_t * inst)
Definition at line 164 of file sd_registry.c.
Referenced by brix_cstore_init(), brix_open_write_needs_staged(), brix_sd_cache_fill_needs_offload(), brix_sd_supports(), brix_vfs_memfile_materialize(), brix_vfs_residency(), brix_vfs_truncate(), cache_open_recall_parked(), s3put_ensure_parent_dirs(), scan_run_walk(), and writer_random_backend().
brix_sd_cred_accept()
uint32_t brix_sd_cred_accept (const brix_sd_instance_t * inst)
Definition at line 196 of file sd_registry.c.
Referenced by brix_vfs_backend_accepts_proxy(), brix_vfs_cred_gate_active(), brix_vfs_deleg_live_cred(), and vfs_backend_cred_decide().
brix_sd_default_driver()
const brix_sd_driver_t * brix_sd_default_driver (void)
Definition at line 60 of file sd_registry.c.
References brix_sd_posix_driver.
Referenced by brix_commit_staged(), brix_vfs_ctx_driver(), brix_vfs_ctx_sd_obj(), brix_vfs_open_via_driver(), brix_vfs_rename_path(), brix_vfs_staged_open(), cms_node_exec_forward(), and stat_query_handle().
brix_sd_driver_at()
const brix_sd_driver_t * brix_sd_driver_at (ngx_uint_t i)
Definition at line 50 of file sd_registry.c.
References sd_drivers.
brix_sd_driver_count()
ngx_uint_t brix_sd_driver_count (void)
Definition at line 44 of file sd_registry.c.
References sd_drivers.
brix_sd_driver_find()
const brix_sd_driver_t * brix_sd_driver_find (const char * name)
Definition at line 69 of file sd_registry.c.
References name, and sd_drivers.
Referenced by brix_sd_instance_create().
brix_sd_fd()
ngx_fd_t brix_sd_fd (const brix_sd_obj_t * obj)
Definition at line 170 of file sd_registry.c.
References BRIX_SD_CAP_FD.
brix_sd_getxattr_maybe_cred()
static ssize_t brix_sd_getxattr_maybe_cred (brix_sd_instance_t * inst, const char * path, const char * name, void * buf, size_t cap, const brix_sd_cred_t * cred) inline static
Definition at line 770 of file sd.h.
References brix_sd_cred_t::fallback_deny, and name.
Referenced by brix_vfs_getxattr().
brix_sd_instance_create()
brix_sd_instance_t * brix_sd_instance_create (ngx_log_t * log, const char * name, void * driver_conf, int * err_out)
Definition at line 113 of file sd_registry.c.
References brix_sd_driver_find(), brix_sd_instance_pool(), driver, log, name, and ngx_pcalloc().
Referenced by brix_vbr_build_posix(), brix_vbr_wrap_staging_shim(), tier_build_ceph(), tier_build_pblock(), and tier_build_posix().
brix_sd_instance_destroy()
void brix_sd_instance_destroy (brix_sd_instance_t * inst)
Definition at line 154 of file sd_registry.c.
brix_sd_listxattr_maybe_cred()
static ssize_t brix_sd_listxattr_maybe_cred (brix_sd_instance_t * inst, const char * path, void * buf, size_t cap, const brix_sd_cred_t * cred) inline static
Definition at line 791 of file sd.h.
References brix_sd_cred_t::fallback_deny.
Referenced by brix_vfs_listxattr().
brix_sd_mkdir_maybe_cred()
static ngx_int_t brix_sd_mkdir_maybe_cred (brix_sd_instance_t * inst, const char * path, mode_t mode, const brix_sd_cred_t * cred) inline static
Definition at line 709 of file sd.h.
References brix_sd_cred_t::fallback_deny.
Referenced by vfs_backend_mkdir_dispatch(), and vfs_backend_mkpath_leaf().
brix_sd_obj_preadv()
static ssize_t brix_sd_obj_preadv (brix_sd_obj_t * obj, const struct iovec * iov, int iovcnt, off_t off) inline static
Definition at line 1031 of file sd.h.
Referenced by brix_pgread_read_encode_inplace(), and brix_readv_read_one_run().
brix_sd_obj_release()
static void brix_sd_obj_release (brix_sd_obj_t * o) inline static
Definition at line 555 of file sd.h.
Referenced by brix_sd_cache_demote(), cache_fill_acquire(), cache_fill_pump(), meta_fetch_source(), sd_cache_close(), and stage_engine_move().
brix_sd_open_maybe_cred()
static brix_sd_obj_t * brix_sd_open_maybe_cred (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, const brix_sd_cred_t * cred, int * err_out) inline static
Definition at line 599 of file sd.h.
References brix_sd_cred_t::fallback_deny.
Referenced by brix_open_resolved_via_driver(), brix_vfs_open_via_driver(), cache_fill_acquire(), meta_fetch_source(), partial_source_ensure(), sd_cache_open_common(), and sd_stage_open_cred().
brix_sd_opendir_maybe_cred()
static brix_sd_dir_t * brix_sd_opendir_maybe_cred (brix_sd_instance_t * inst, const char * path, int * err_out, const brix_sd_cred_t * cred) inline static
Definition at line 877 of file sd.h.
References brix_sd_cred_t::fallback_deny.
Referenced by brix_vfs_driver_rmtree(), and vfs_dir_open_driver().
brix_sd_posix_borrow_instance()
brix_sd_instance_t * brix_sd_posix_borrow_instance (ngx_pool_t * pool, ngx_log_t * log, int rootfd, const char * root_canon)
Definition at line 161 of file sd_posix.c.
References sd_posix_state_t::borrowed, brix_sd_posix_driver, log, ngx_pcalloc(), sd_posix_state_t::root_canon, and sd_posix_state_t::rootfd.
Referenced by brix_vfs_open_confined_fd(), cache_build_instance(), cache_build_wt_stage(), and cs_root_lazy_posix().
brix_sd_posix_open_unconfined()
int brix_sd_posix_open_unconfined (const char * path, int sd_flags, mode_t mode)
Definition at line 84 of file sd_posix.c.
References open(), and sd_posix_flags().
Referenced by brix_sd_block_open_unconfined(), and posix_be_open().
brix_sd_posix_wrap()
static void brix_sd_posix_wrap (brix_sd_obj_t * obj, ngx_fd_t fd) inline static
Definition at line 1003 of file sd.h.
References brix_sd_posix_driver.
Referenced by block_be_stat(), block_commit(), block_fstat(), block_pread(), block_pwrite(), block_sync(), brix_cache_fd_write_all(), brix_cksum_digest_fd(), brix_cksum_u32_fd(), brix_cksum_u64_fd(), brix_cstore_serve_pread(), brix_vfs_effective_obj(), brix_vfs_pread_full(), brix_vfs_pwrite_full(), commit_cross_device(), commit_flush_and_chmod(), cstb_pump_and_commit(), main(), ms_write_cb(), posix_fstat(), posix_pread(), posix_pwrite(), posix_sync(), posix_truncate(), pread_full(), read_try_warm(), s3_copy_bytes(), srq_pread_all(), srq_pwrite_all(), tpc_ms_prepare_output(), webdav_write_full(), xvfs_stage_fd(), zip_deflate_pump(), and zip_pread_full().
brix_sd_removexattr_maybe_cred()
static ngx_int_t brix_sd_removexattr_maybe_cred (brix_sd_instance_t * inst, const char * path, const char * name, const brix_sd_cred_t * cred) inline static
Definition at line 835 of file sd.h.
References brix_sd_cred_t::fallback_deny, and name.
Referenced by brix_vfs_removexattr().
brix_sd_rename_maybe_cred()
static ngx_int_t brix_sd_rename_maybe_cred (brix_sd_instance_t * inst, const char * src, const char * dst, int noreplace, const brix_sd_cred_t * cred) inline static
Definition at line 727 of file sd.h.
References brix_sd_cred_t::fallback_deny.
Referenced by brix_vfs_rename().
brix_sd_server_copy_maybe_cred()
static ngx_int_t brix_sd_server_copy_maybe_cred (brix_sd_instance_t * inst, const char * src, const char * dst, off_t * bytes_out, const brix_sd_cred_t * cred) inline static
Definition at line 856 of file sd.h.
References brix_sd_cred_t::fallback_deny.
Referenced by brix_vfs_copy_driver().
brix_sd_setattr_maybe_cred()
static ngx_int_t brix_sd_setattr_maybe_cred (brix_sd_instance_t * inst, const char * path, const brix_sd_setattr_t * attr, const brix_sd_cred_t * cred) inline static
Definition at line 747 of file sd.h.
References brix_sd_cred_t::fallback_deny.
Referenced by brix_vfs_chmod(), and brix_vfs_setattr().
brix_sd_setxattr_maybe_cred()
static ngx_int_t brix_sd_setxattr_maybe_cred (brix_sd_instance_t * inst, const char * path, const char * name, const void * val, size_t len, int flags, const brix_sd_cred_t * cred) inline static
Definition at line 812 of file sd.h.
References brix_sd_cred_t::fallback_deny, and name.
Referenced by brix_vfs_setxattr().
brix_sd_staged_open_maybe_cred()
static brix_sd_staged_t * brix_sd_staged_open_maybe_cred (brix_sd_instance_t * inst, const char * final_path, mode_t mode, const brix_sd_cred_t * cred, int * err_out) inline static
Definition at line 626 of file sd.h.
References brix_sd_cred_t::fallback_deny.
Referenced by sd_cache_staged_open_cred(), stage_engine_move(), and staged_open_driver().
brix_sd_stat_maybe_cred()
static ngx_int_t brix_sd_stat_maybe_cred (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out, const brix_sd_cred_t * cred) inline static
Definition at line 669 of file sd.h.
References brix_sd_cred_t::fallback_deny.
Referenced by brix_open_read_probe(), brix_vfs_copy_driver(), brix_vfs_driver_rmtree(), brix_vfs_probe(), and brix_vfs_stat_impl().
brix_sd_supports()
ngx_int_t brix_sd_supports (const brix_sd_instance_t * inst, uint32_t required_caps)
Definition at line 189 of file sd_registry.c.
References brix_sd_caps().
brix_sd_unlink_maybe_cred()
static ngx_int_t brix_sd_unlink_maybe_cred (brix_sd_instance_t * inst, const char * path, int is_dir, const brix_sd_cred_t * cred) inline static
Definition at line 689 of file sd.h.
References brix_sd_cred_t::fallback_deny.
Referenced by brix_vfs_delete_via_driver(), and brix_vfs_driver_rmtree().
Variable Documentation
brix_sd_block_driver
const brix_sd_driver_t brix_sd_block_driver extern
Definition at line 109 of file sd_block.c.
Referenced by block_be_stat(), and block_fstat().
brix_sd_posix_driver
const brix_sd_driver_t brix_sd_posix_driver extern
Definition at line 253 of file sd_posix.c.
Referenced by brix_sd_default_driver(), brix_sd_posix_borrow_instance(), brix_sd_posix_wrap(), brix_vfs_pwrite_full(), sd_block_fsync(), sd_block_pread(), sd_block_preadv(), sd_block_preadv2(), sd_block_pwrite(), and tpc_ms_prepare_output().