nginx-xrootd: src/fs/backend/pblock/sd_pblock_unittest_internal.h File Reference
sd_pblock_unittest_internal.h File Reference
#include "fs/backend/sd.h"
#include <stdint.h>
#include <stdio.h>
#include <sys/types.h>
Macros
#define CHECK(cond, ...)
Functions
ngx_int_t pb_close (brix_sd_obj_t *o)
int write_file (brix_sd_instance_t *inst, const char *path, const char *data, size_t len)
ssize_t read_file (brix_sd_instance_t *inst, const char *path, char *buf, size_t cap)
int open_block_export (brix_sd_instance_t *inst, char *root, int64_t block_size)
void lab_write_sidecar (const char *root, const char *line)
void test_write_read_fstat (brix_sd_instance_t *inst)
void test_truncate_and_stat (brix_sd_instance_t *inst)
void test_preadv (brix_sd_instance_t *inst)
void test_dirs (brix_sd_instance_t *inst)
void test_rename (brix_sd_instance_t *inst)
void test_server_copy (brix_sd_instance_t *inst)
void test_xattr (brix_sd_instance_t *inst)
void test_staged (brix_sd_instance_t *inst)
void test_unlink (brix_sd_instance_t *inst)
void test_fsync_durability (const char *root)
void test_threads (brix_sd_instance_t *inst)
void test_processes (const char *root, brix_sd_instance_t *inst)
void test_block_striping (void)
void test_block_size_configurable (void)
void test_block_sparse (void)
void test_block_truncate (void)
void test_block_copy_and_unlink (void)
void test_identity (void)
void test_lab_fault_inject (void)
void test_lab_gate_closed (void)
void test_lab_caps_mask (void)
void test_lab_enumerate (void)
void test_dedup_refs (void)
void test_dedup_forged_hash (void)
void test_dedup_gate_closed (void)
void test_snapshot (void)
void test_versioning (void)
Variables
int failures
const brix_sd_driver_t * D
Macro Definition Documentation
CHECK
#define CHECK (cond, ...)
Value:
    do {                                                                       \
        if (!(cond)) {                                                         \
            fprintf(stderr, "FAIL %s:%d: ", __func__, __LINE__);              \
            fprintf(stderr, __VA_ARGS__);                                      \
            fprintf(stderr, "\n");                                             \
            failures++;                                                        \
        }                                                                      \
    } while (0)
Definition at line 21 of file sd_pblock_unittest_internal.h.
Function Documentation
lab_write_sidecar()
void lab_write_sidecar (const char * root, const char * line)
Definition at line 34 of file sd_pblock_unittest_lab.c.
References CHECK, and PATH_MAX.
Referenced by test_dedup_forged_hash(), test_dedup_refs(), test_lab_caps_mask(), test_lab_fault_inject(), test_snapshot(), and test_versioning().
open_block_export()
int open_block_export (brix_sd_instance_t * inst, char * root, int64_t block_size)
Definition at line 61 of file sd_pblock_unittest_block.c.
References D.
Referenced by test_block_copy_and_unlink(), test_block_size_configurable(), test_block_sparse(), test_block_striping(), test_block_truncate(), and test_identity().
pb_close()
ngx_int_t pb_close (brix_sd_obj_t * o)
Definition at line 41 of file sd_pblock_unittest.c.
References D.
Referenced by cred_write_file(), read_file(), test_block_sparse(), test_block_striping(), test_block_truncate(), test_fsync_durability(), test_ident_ownership(), test_ident_traverse(), test_lab_fault_inject(), test_lab_gate_closed(), test_preadv(), test_snapshot(), test_truncate_and_stat(), test_write_read_fstat(), trunc_write(), and write_file().
read_file()
ssize_t read_file (brix_sd_instance_t * inst, const char * path, char * buf, size_t cap)
Definition at line 74 of file sd_pblock_unittest.c.
References BRIX_SD_O_READ, D, and pb_close().
Referenced by test_block_copy_and_unlink(), test_block_sparse(), test_block_striping(), test_block_truncate(), test_dedup_forged_hash(), test_dedup_gate_closed(), test_dedup_refs(), test_rename(), test_server_copy(), test_snapshot(), test_staged(), test_versioning(), test_write_read_fstat(), and thread_body().
test_block_copy_and_unlink()
void test_block_copy_and_unlink (void)
Definition at line 211 of file sd_pblock_unittest_block.c.
References CHECK, D, g_blk_count, open_block_export(), read_file(), scan_blocks(), brix_sd_stat_t::size, and write_file().
Referenced by main().
test_block_size_configurable()
void test_block_size_configurable (void)
Definition at line 115 of file sd_pblock_unittest_block.c.
References CHECK, D, g_blk_count, g_blk_max, g_blk_total, open_block_export(), scan_blocks(), and write_file().
Referenced by main().
test_block_sparse()
void test_block_sparse (void)
Definition at line 139 of file sd_pblock_unittest_block.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, D, g_blk_count, open_block_export(), pb_close(), read_file(), scan_blocks(), and brix_sd_stat_t::size.
Referenced by main().
test_block_striping()
void test_block_striping (void)
Definition at line 76 of file sd_pblock_unittest_block.c.
References BRIX_SD_O_READ, CHECK, D, g_blk_count, g_blk_max, g_blk_total, open_block_export(), pb_close(), read_file(), scan_blocks(), brix_sd_stat_t::size, and write_file().
Referenced by main().
test_block_truncate()
void test_block_truncate (void)
Definition at line 176 of file sd_pblock_unittest_block.c.
References BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, D, g_blk_count, g_blk_total, open_block_export(), pb_close(), read_file(), scan_blocks(), brix_sd_stat_t::size, and write_file().
Referenced by main().
test_dedup_forged_hash()
void test_dedup_forged_hash (void)
Definition at line 256 of file sd_pblock_unittest_dedup.c.
References CHECK, D, break_arg::inst, lab_write_sidecar(), PATH_MAX, PBLOCK_BLOB_ID_CAP, q_blob_id(), read_file(), and write_file().
Referenced by main().
test_dedup_gate_closed()
void test_dedup_gate_closed (void)
Definition at line 337 of file sd_pblock_unittest_dedup.c.
References CHECK, D, break_arg::inst, PBLOCK_BLOB_ID_CAP, q_blob_id(), read_file(), and write_file().
Referenced by main().
test_dedup_refs()
void test_dedup_refs (void)
Definition at line 167 of file sd_pblock_unittest_dedup.c.
References break_body(), CHECK, D, break_arg::inst, lab_write_sidecar(), PBLOCK_BLOB_ID_CAP, q_blob_id(), q_refcount(), break_arg::rc, read_file(), trunc_write(), and write_file().
Referenced by main().
test_dirs()
void test_dirs (brix_sd_instance_t * inst)
Definition at line 101 of file sd_pblock_unittest_core.c.
References CHECK, D, brix_sd_dirent_t::name, and write_file().
Referenced by main().
test_fsync_durability()
void test_fsync_durability (const char * root)
Definition at line 235 of file sd_pblock_unittest_core.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, D, pb_close(), and brix_sd_stat_t::size.
Referenced by main().
test_identity()
void test_identity (void)
Definition at line 341 of file sd_pblock_unittest_ident.c.
References BRIX_SD_CRED_IDENTITY, CHECK, D, open_block_export(), test_ident_ownership(), test_ident_setattr(), test_ident_traverse(), test_ident_vo_dir(), and test_ident_xattr_sticky().
Referenced by main().
test_lab_caps_mask()
void test_lab_caps_mask (void)
Definition at line 151 of file sd_pblock_unittest_lab.c.
References BRIX_SD_CAP_CATALOG, BRIX_SD_CAP_FD, BRIX_SD_CAP_SENDFILE, CHECK, D, and lab_write_sidecar().
Referenced by main().
test_lab_enumerate()
void test_lab_enumerate (void)
Definition at line 236 of file sd_pblock_unittest_lab.c.
References BRIX_SD_CAP_CATALOG, enum_probe_t::bytes, CHECK, D, enum_probe_cb(), enum_walk(), enum_probe_t::files, enum_probe_t::saw_nested, enum_probe_t::stop_after, and write_file().
Referenced by main().
test_lab_fault_inject()
void test_lab_fault_inject (void)
Definition at line 73 of file sd_pblock_unittest_lab.c.
References BRIX_SD_O_READ, CHECK, D, lab_ctl_set(), lab_write_sidecar(), pb_close(), and write_file().
Referenced by main().
test_lab_gate_closed()
void test_lab_gate_closed (void)
Definition at line 117 of file sd_pblock_unittest_lab.c.
References BRIX_SD_O_READ, CHECK, D, lab_ctl_set(), pb_close(), and write_file().
Referenced by main().
test_preadv()
void test_preadv (brix_sd_instance_t * inst)
Definition at line 82 of file sd_pblock_unittest_core.c.
References BRIX_SD_O_READ, CHECK, D, pb_close(), and write_file().
Referenced by main().
test_processes()
void test_processes (const char * root, brix_sd_instance_t * inst)
Definition at line 332 of file sd_pblock_unittest_core.c.
References CHECK, D, and write_file().
Referenced by main().
test_rename()
void test_rename (brix_sd_instance_t * inst)
Definition at line 127 of file sd_pblock_unittest_core.c.
References CHECK, D, read_file(), and write_file().
Referenced by main().
test_server_copy()
void test_server_copy (brix_sd_instance_t * inst)
Definition at line 151 of file sd_pblock_unittest_core.c.
References CHECK, D, read_file(), and write_file().
Referenced by main().
test_snapshot()
void test_snapshot (void)
Definition at line 375 of file sd_pblock_unittest_dedup.c.
References BRIX_SD_O_READ, CHECK, D, break_arg::inst, lab_write_sidecar(), pb_close(), read_file(), and write_file().
Referenced by main().
test_staged()
void test_staged (brix_sd_instance_t * inst)
Definition at line 184 of file sd_pblock_unittest_core.c.
References CHECK, D, read_file(), s, and brix_sd_stat_t::size.
Referenced by main().
test_threads()
void test_threads (brix_sd_instance_t * inst)
Definition at line 306 of file sd_pblock_unittest_core.c.
References CHECK, D, thread_arg::id, thread_arg::inst, thread_arg::ok, thread_arg::ops, and thread_body().
Referenced by main().
test_truncate_and_stat()
void test_truncate_and_stat (brix_sd_instance_t * inst)
Definition at line 59 of file sd_pblock_unittest_core.c.
References BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, D, pb_close(), brix_sd_stat_t::size, and write_file().
Referenced by main().
test_unlink()
void test_unlink (brix_sd_instance_t * inst)
Definition at line 214 of file sd_pblock_unittest_core.c.
References CHECK, D, and write_file().
Referenced by main().
test_versioning()
void test_versioning (void)
Definition at line 454 of file sd_pblock_unittest_dedup.c.
References CHECK, D, break_arg::inst, lab_write_sidecar(), PBLOCK_BLOB_ID_CAP, q_blob_id(), q_count(), q_refcount(), read_file(), and staged_put().
Referenced by main().
test_write_read_fstat()
void test_write_read_fstat (brix_sd_instance_t * inst)
Definition at line 30 of file sd_pblock_unittest_core.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, D, brix_sd_stat_t::is_reg, pb_close(), read_file(), and brix_sd_stat_t::size.
Referenced by main().
test_xattr()
void test_xattr (brix_sd_instance_t * inst)
Definition at line 166 of file sd_pblock_unittest_core.c.
References CHECK, D, and write_file().
write_file()
int write_file (brix_sd_instance_t * inst, const char * path, const char * data, size_t len)
Definition at line 53 of file sd_pblock_unittest.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_READ, BRIX_SD_O_WRITE, D, and pb_close().
Variable Documentation
D
const brix_sd_driver_t* D extern
Definition at line 35 of file sd_pblock_unittest.c.
Referenced by cred_write_file(), enum_walk(), main(), metabench_plan_init(), open_block_export(), pb_close(), read_file(), staged_put(), test_block_copy_and_unlink(), test_block_size_configurable(), test_block_sparse(), test_block_striping(), test_block_truncate(), test_dedup_forged_hash(), test_dedup_gate_closed(), test_dedup_refs(), test_dirs(), test_fsync_durability(), test_ident_ownership(), test_ident_setattr(), test_ident_traverse(), test_ident_vo_dir(), test_ident_xattr_sticky(), test_identity(), test_lab_caps_mask(), test_lab_enumerate(), test_lab_fault_inject(), test_lab_gate_closed(), test_preadv(), test_processes(), test_rename(), test_server_copy(), test_snapshot(), test_staged(), test_threads(), test_truncate_and_stat(), test_unlink(), test_versioning(), test_write_read_fstat(), test_xattr(), trunc_write(), and write_file().
failures
int failures extern
Definition at line 33 of file sd_pblock_unittest.c.
Referenced by main().