nginx-xrootd: src/fs/backend/posix/sd_posix_io.c File Reference
sd_posix_io.c File Reference
#include "fs/backend/sd.h"
#include "fs/vfs/vfs_internal.h"
#include "core/compat/crc32c.h"
#include "core/compat/namespace_ops.h"
#include "core/compat/staged_file.h"
#include "fs/path/beneath.h"
#include "fs/path/path.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <string.h>
#include <sys/syscall.h>
#include <unistd.h>
#include "sd_posix_internal.h"
Functions
ssize_t sd_posix_pread (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
ssize_t sd_posix_pwrite (brix_sd_obj_t *obj, const void *buf, size_t len, off_t off)
ssize_t sd_posix_preadv (brix_sd_obj_t *obj, const struct iovec *iov, int iovcnt, off_t off)
ssize_t sd_posix_preadv2 (brix_sd_obj_t *obj, const struct iovec *iov, int iovcnt, off_t off, int flags)
ssize_t sd_posix_copy_range (brix_sd_obj_t *src, off_t src_off, brix_sd_obj_t *dst, off_t dst_off, size_t len)
ngx_fd_t sd_posix_read_sendfile_fd (brix_sd_obj_t *obj, off_t off, size_t len, unsigned want_zerocopy)
ngx_int_t sd_posix_ftruncate (brix_sd_obj_t *obj, off_t len)
ngx_int_t sd_posix_fsync (brix_sd_obj_t *obj)
ngx_int_t sd_posix_fstat (brix_sd_obj_t *obj, brix_sd_stat_t *out)
Function Documentation
sd_posix_copy_range()
ssize_t sd_posix_copy_range (brix_sd_obj_t * src, off_t src_off, brix_sd_obj_t * dst, off_t dst_off, size_t len)
Definition at line 88 of file sd_posix_io.c.
sd_posix_fstat()
ngx_int_t sd_posix_fstat (brix_sd_obj_t * obj, brix_sd_stat_t * out)
Definition at line 135 of file sd_posix_io.c.
References fstat(), sd_posix_fill_stat(), and stat().
sd_posix_fsync()
ngx_int_t sd_posix_fsync (brix_sd_obj_t * obj)
Definition at line 129 of file sd_posix_io.c.
sd_posix_ftruncate()
ngx_int_t sd_posix_ftruncate (brix_sd_obj_t * obj, off_t len)
Definition at line 123 of file sd_posix_io.c.
sd_posix_pread()
ssize_t sd_posix_pread (brix_sd_obj_t * obj, void * buf, size_t len, off_t off)
Definition at line 50 of file sd_posix_io.c.
References pread().
sd_posix_preadv()
ssize_t sd_posix_preadv (brix_sd_obj_t * obj, const struct iovec * iov, int iovcnt, off_t off)
Definition at line 68 of file sd_posix_io.c.
sd_posix_preadv2()
ssize_t sd_posix_preadv2 (brix_sd_obj_t * obj, const struct iovec * iov, int iovcnt, off_t off, int flags)
Definition at line 78 of file sd_posix_io.c.
sd_posix_pwrite()
ssize_t sd_posix_pwrite (brix_sd_obj_t * obj, const void * buf, size_t len, off_t off)
Definition at line 59 of file sd_posix_io.c.
sd_posix_read_sendfile_fd()
ngx_fd_t sd_posix_read_sendfile_fd (brix_sd_obj_t * obj, off_t off, size_t len, unsigned want_zerocopy)
Definition at line 109 of file sd_posix_io.c.