nginx-xrootd: src/fs/backend/xroot/sd_xroot_staged.c File Reference
sd_xroot_staged.c File Reference
#include "sd_xroot_internal.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct sd_xroot_staged_state
Functions
static void sd_xroot_staged_teardown (brix_sd_staged_t *handle)
static int sd_xroot_staged_connect_open (sd_xroot_staged_state *ss, const char *final_path, mode_t mode, int *err_out)
static brix_sd_staged_t * sd_xroot_staged_open_common (brix_sd_instance_t *inst, const char *final_path, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
brix_sd_staged_t * sd_xroot_staged_open (brix_sd_instance_t *inst, const char *final_path, mode_t mode, int *err_out)
brix_sd_staged_t * sd_xroot_staged_open_cred (brix_sd_instance_t *inst, const char *final_path, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
ssize_t sd_xroot_staged_write (brix_sd_staged_t *handle, const void *buf, size_t len, off_t off)
ngx_int_t sd_xroot_staged_commit (brix_sd_staged_t *handle, int noreplace)
void sd_xroot_staged_abort (brix_sd_staged_t *handle)
Function Documentation
sd_xroot_staged_abort()
void sd_xroot_staged_abort (brix_sd_staged_t * handle)
Definition at line 205 of file sd_xroot_staged.c.
References sd_xroot_staged_teardown().
sd_xroot_staged_commit()
ngx_int_t sd_xroot_staged_commit (brix_sd_staged_t * handle, int noreplace)
Definition at line 191 of file sd_xroot_staged.c.
References brix_cache_origin_sync(), sd_xroot_staged_state::fhandle, sd_xroot_staged_state::oc, sd_xroot_staged_teardown(), and sd_xroot_staged_state::t.
sd_xroot_staged_connect_open()
static int sd_xroot_staged_connect_open (sd_xroot_staged_state * ss, const char * final_path, mode_t mode, int * err_out) static
Definition at line 71 of file sd_xroot_staged.c.
References brix_cache_origin_bootstrap(), brix_cache_origin_close(), brix_cache_origin_connect(), brix_cache_origin_open_write(), brix_cache_fill_t::err_msg, sd_xroot_staged_state::fhandle, sd_xroot_staged_state::file_open, sd_xroot_staged_state::oc, sd_xroot_errno(), sd_xroot_staged_state::t, and brix_cache_fill_t::xrd_error.
Referenced by sd_xroot_staged_open_common().
sd_xroot_staged_open()
brix_sd_staged_t * sd_xroot_staged_open (brix_sd_instance_t * inst, const char * final_path, mode_t mode, int * err_out)
Definition at line 149 of file sd_xroot_staged.c.
References sd_xroot_staged_open_common().
sd_xroot_staged_open_common()
static brix_sd_staged_t * sd_xroot_staged_open_common (brix_sd_instance_t * inst, const char * final_path, mode_t mode, const brix_sd_cred_t * cred, int * err_out) static
Definition at line 108 of file sd_xroot_staged.c.
References brix_cache_fill_t::clean_path, sd_xroot_inst_state::conf, brix_cache_fill_t::conf, brix_cache_origin_conn_t::fd, sd_xroot_staged_state::oc, sd_xroot_copy_cred_into_task(), sd_xroot_staged_connect_open(), and sd_xroot_staged_state::t.
Referenced by sd_xroot_staged_open(), and sd_xroot_staged_open_cred().
sd_xroot_staged_open_cred()
brix_sd_staged_t * sd_xroot_staged_open_cred (brix_sd_instance_t * inst, const char * final_path, mode_t mode, const brix_sd_cred_t * cred, int * err_out)
Definition at line 162 of file sd_xroot_staged.c.
References sd_xroot_staged_open_common().
sd_xroot_staged_teardown()
static void sd_xroot_staged_teardown (brix_sd_staged_t * handle) static
Definition at line 39 of file sd_xroot_staged.c.
References brix_cache_origin_close(), brix_cache_origin_close_file(), sd_xroot_staged_state::fhandle, sd_xroot_staged_state::file_open, sd_xroot_staged_state::oc, and sd_xroot_staged_state::t.
Referenced by sd_xroot_staged_abort(), and sd_xroot_staged_commit().
sd_xroot_staged_write()
ssize_t sd_xroot_staged_write (brix_sd_staged_t * handle, const void * buf, size_t len, off_t off)
Definition at line 169 of file sd_xroot_staged.c.
References brix_cache_origin_write_chunk(), sd_xroot_staged_state::fhandle, sd_xroot_staged_state::oc, and sd_xroot_staged_state::t.