nginx-xrootd: src/fs/backend/posix/sd_posix_internal.h File Reference
sd_posix_internal.h File Reference
#include "fs/backend/sd.h"
#include <sys/stat.h>
#include <sys/uio.h>
Data Structures
struct sd_posix_state_t
Functions
void sd_posix_fill_stat (const struct stat *st, brix_sd_stat_t *out)
ssize_t sd_posix_pread (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
ssize_t sd_posix_pwrite (brix_sd_obj_t *obj, const void *buf, size_t len, off_t off)
ssize_t sd_posix_preadv (brix_sd_obj_t *obj, const struct iovec *iov, int iovcnt, off_t off)
ssize_t sd_posix_preadv2 (brix_sd_obj_t *obj, const struct iovec *iov, int iovcnt, off_t off, int flags)
ssize_t sd_posix_copy_range (brix_sd_obj_t *src, off_t src_off, brix_sd_obj_t *dst, off_t dst_off, size_t len)
ngx_fd_t sd_posix_read_sendfile_fd (brix_sd_obj_t *obj, off_t off, size_t len, unsigned want_zerocopy)
ngx_int_t sd_posix_ftruncate (brix_sd_obj_t *obj, off_t len)
ngx_int_t sd_posix_fsync (brix_sd_obj_t *obj)
ngx_int_t sd_posix_fstat (brix_sd_obj_t *obj, brix_sd_stat_t *out)
ngx_int_t sd_posix_stat (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out)
ngx_int_t sd_posix_unlink (brix_sd_instance_t *inst, const char *path, int is_dir)
ngx_int_t sd_posix_mkdir (brix_sd_instance_t *inst, const char *path, mode_t mode)
ngx_int_t sd_posix_rename (brix_sd_instance_t *inst, const char *src, const char *dst, int noreplace)
ngx_int_t sd_posix_server_copy (brix_sd_instance_t *inst, const char *src, const char *dst, off_t *bytes_out)
brix_sd_dir_t * sd_posix_opendir (brix_sd_instance_t *inst, const char *path, int *err_out)
ngx_int_t sd_posix_readdir (brix_sd_dir_t *d, brix_sd_dirent_t *out)
ngx_int_t sd_posix_closedir (brix_sd_dir_t *d)
ssize_t sd_posix_getxattr (brix_sd_instance_t *inst, const char *path, const char *name, void *buf, size_t cap)
ssize_t sd_posix_listxattr (brix_sd_instance_t *inst, const char *path, void *buf, size_t cap)
ngx_int_t sd_posix_setxattr (brix_sd_instance_t *inst, const char *path, const char *name, const void *val, size_t len, int flags)
ngx_int_t sd_posix_removexattr (brix_sd_instance_t *inst, const char *path, const char *name)
brix_sd_staged_t * sd_posix_staged_open (brix_sd_instance_t *inst, const char *final_path, mode_t mode, int *err_out)
ssize_t sd_posix_staged_write (brix_sd_staged_t *st, const void *buf, size_t len, off_t off)
ngx_int_t sd_posix_staged_commit (brix_sd_staged_t *st, int noreplace)
void sd_posix_staged_abort (brix_sd_staged_t *st)
const char * sd_posix_staged_path (const brix_sd_staged_t *st)
Function Documentation
sd_posix_closedir()
ngx_int_t sd_posix_closedir (brix_sd_dir_t * d)
Definition at line 219 of file sd_posix_ns.c.
References sd_posix_dir_t::dp.
sd_posix_copy_range()
ssize_t sd_posix_copy_range (brix_sd_obj_t * src, off_t src_off, brix_sd_obj_t * dst, off_t dst_off, size_t len)
Definition at line 88 of file sd_posix_io.c.
sd_posix_fill_stat()
void sd_posix_fill_stat (const struct stat * st, brix_sd_stat_t * out)
Definition at line 94 of file sd_posix.c.
References brix_sd_stat_t::ctime, brix_sd_stat_t::gid, brix_sd_stat_t::ino, brix_sd_stat_t::is_dir, brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, brix_sd_stat_t::mtime, brix_sd_stat_t::size, and brix_sd_stat_t::uid.
Referenced by sd_posix_fstat(), and sd_posix_stat().
sd_posix_fstat()
ngx_int_t sd_posix_fstat (brix_sd_obj_t * obj, brix_sd_stat_t * out)
Definition at line 135 of file sd_posix_io.c.
References fstat(), sd_posix_fill_stat(), and stat().
sd_posix_fsync()
ngx_int_t sd_posix_fsync (brix_sd_obj_t * obj)
Definition at line 129 of file sd_posix_io.c.
sd_posix_ftruncate()
ngx_int_t sd_posix_ftruncate (brix_sd_obj_t * obj, off_t len)
Definition at line 123 of file sd_posix_io.c.
sd_posix_getxattr()
ssize_t sd_posix_getxattr (brix_sd_instance_t * inst, const char * path, const char * name, void * buf, size_t cap)
Definition at line 238 of file sd_posix_ns.c.
References brix_getxattr_confined_canon(), name, PATH_MAX, and sd_posix_state_t::root_canon.
sd_posix_listxattr()
ssize_t sd_posix_listxattr (brix_sd_instance_t * inst, const char * path, void * buf, size_t cap)
Definition at line 255 of file sd_posix_ns.c.
References brix_listxattr_confined_canon(), PATH_MAX, and sd_posix_state_t::root_canon.
sd_posix_mkdir()
ngx_int_t sd_posix_mkdir (brix_sd_instance_t * inst, const char * path, mode_t mode)
Definition at line 100 of file sd_posix_ns.c.
References brix_ns_mkdir(), PATH_MAX, sd_posix_state_t::root_canon, and sd_posix_ns_result().
sd_posix_opendir()
brix_sd_dir_t * sd_posix_opendir (brix_sd_instance_t * inst, const char * path, int * err_out)
Definition at line 159 of file sd_posix_ns.c.
References brix_open_beneath(), close(), sd_posix_dir_t::dp, ngx_pcalloc(), and sd_posix_state_t::rootfd.
sd_posix_pread()
ssize_t sd_posix_pread (brix_sd_obj_t * obj, void * buf, size_t len, off_t off)
Definition at line 50 of file sd_posix_io.c.
References pread().
sd_posix_preadv()
ssize_t sd_posix_preadv (brix_sd_obj_t * obj, const struct iovec * iov, int iovcnt, off_t off)
Definition at line 68 of file sd_posix_io.c.
sd_posix_preadv2()
ssize_t sd_posix_preadv2 (brix_sd_obj_t * obj, const struct iovec * iov, int iovcnt, off_t off, int flags)
Definition at line 78 of file sd_posix_io.c.
sd_posix_pwrite()
ssize_t sd_posix_pwrite (brix_sd_obj_t * obj, const void * buf, size_t len, off_t off)
Definition at line 59 of file sd_posix_io.c.
sd_posix_read_sendfile_fd()
ngx_fd_t sd_posix_read_sendfile_fd (brix_sd_obj_t * obj, off_t off, size_t len, unsigned want_zerocopy)
Definition at line 109 of file sd_posix_io.c.
sd_posix_readdir()
ngx_int_t sd_posix_readdir (brix_sd_dir_t * d, brix_sd_dirent_t * out)
Definition at line 195 of file sd_posix_ns.c.
References sd_posix_dir_t::dp, and brix_sd_dirent_t::name.
sd_posix_removexattr()
ngx_int_t sd_posix_removexattr (brix_sd_instance_t * inst, const char * path, const char * name)
Definition at line 290 of file sd_posix_ns.c.
References brix_removexattr_confined_canon(), name, PATH_MAX, and sd_posix_state_t::root_canon.
sd_posix_rename()
ngx_int_t sd_posix_rename (brix_sd_instance_t * inst, const char * src, const char * dst, int noreplace)
Definition at line 119 of file sd_posix_ns.c.
References brix_ns_rename(), sd_posix_state_t::root_canon, and sd_posix_ns_result().
sd_posix_server_copy()
ngx_int_t sd_posix_server_copy (brix_sd_instance_t * inst, const char * src, const char * dst, off_t * bytes_out)
Definition at line 130 of file sd_posix_ns.c.
References brix_lstat_beneath(), brix_ns_local_copy(), brix_ns_copy_opts_t::overwrite, sd_posix_state_t::root_canon, sd_posix_state_t::rootfd, sd_posix_ns_result(), sd_posix_stat(), and stat().
sd_posix_setxattr()
ngx_int_t sd_posix_setxattr (brix_sd_instance_t * inst, const char * path, const char * name, const void * val, size_t len, int flags)
Definition at line 272 of file sd_posix_ns.c.
References brix_setxattr_confined_canon(), name, PATH_MAX, and sd_posix_state_t::root_canon.
sd_posix_staged_abort()
void sd_posix_staged_abort (brix_sd_staged_t * st)
Definition at line 407 of file sd_posix_ns.c.
References brix_staged_abort(), sd_posix_state_t::root_canon, and sd_posix_staged_t::staged.
sd_posix_staged_commit()
ngx_int_t sd_posix_staged_commit (brix_sd_staged_t * st, int noreplace)
Definition at line 389 of file sd_posix_ns.c.
References brix_staged_commit(), brix_staged_commit_excl(), sd_posix_staged_t::final_path, sd_posix_state_t::root_canon, and sd_posix_staged_t::staged.
sd_posix_staged_open()
brix_sd_staged_t * sd_posix_staged_open (brix_sd_instance_t * inst, const char * final_path, mode_t mode, int * err_out)
Definition at line 316 of file sd_posix_ns.c.
References brix_staged_open(), sd_posix_staged_t::final_path, PATH_MAX, brix_staged_open_req_t::root_canon, sd_posix_state_t::root_canon, and sd_posix_staged_t::staged.
sd_posix_staged_path()
const char * sd_posix_staged_path (const brix_sd_staged_t * st)
Definition at line 421 of file sd_posix_ns.c.
References sd_posix_staged_t::staged, and brix_staged_file_t::tmp_path.
sd_posix_staged_write()
ssize_t sd_posix_staged_write (brix_sd_staged_t * st, const void * buf, size_t len, off_t off)
Definition at line 377 of file sd_posix_ns.c.
References brix_vfs_pwrite_full(), brix_staged_file_t::fd, and sd_posix_staged_t::staged.
sd_posix_stat()
ngx_int_t sd_posix_stat (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out)
Definition at line 51 of file sd_posix_ns.c.
References brix_lstat_beneath(), sd_posix_state_t::rootfd, sd_posix_fill_stat(), and stat().
Referenced by sd_posix_server_copy().
sd_posix_unlink()
ngx_int_t sd_posix_unlink (brix_sd_instance_t * inst, const char * path, int is_dir)
Definition at line 78 of file sd_posix_ns.c.
References brix_ns_delete(), PATH_MAX, brix_ns_delete_opts_t::require_directory, sd_posix_state_t::root_canon, and sd_posix_ns_result().