nginx-xrootd: src/fs/backend/stage/sd_stage.h File Reference
sd_stage.h File Reference
#include <ngx_core.h>
#include "fs/backend/sd.h"
#include "fs/tier/tier.h"
#include "fs/xfer/stage_engine.h"
Functions
brix_sd_instance_t * brix_sd_stage_create (brix_sd_instance_t *source, brix_sd_instance_t *store, const brix_stage_policy_t *policy, const char *root_canon, ngx_log_t *log)
void brix_sd_stage_destroy (brix_sd_instance_t *inst)
int brix_sd_stage_instance_is (const brix_sd_instance_t *inst)
brix_sd_instance_t * brix_sd_stage_source_instance (const brix_sd_instance_t *inst)
brix_sd_instance_t * brix_sd_stage_store_instance (const brix_sd_instance_t *inst)
ngx_int_t brix_sd_stage_reflush (brix_sd_instance_t *inst, const char *key, const brix_stage_cred_t *cred)
Function Documentation
brix_sd_stage_create()
brix_sd_instance_t * brix_sd_stage_create (brix_sd_instance_t * source, brix_sd_instance_t * store, const brix_stage_policy_t * policy, const char * root_canon, ngx_log_t * log)
Definition at line 224 of file sd_stage.c.
References brix_sd_stage_driver, BRIX_WT_MODE_SYNC, brix_stage_policy_t::flush_mode, log, sd_stage_inst_state::log, sd_stage_inst_state::policy, sd_stage_inst_state::root_canon, sd_stage_inst_state::source, and sd_stage_inst_state::store.
Referenced by brix_vbr_wrap_stage_tier(), brix_vbr_wrap_staging_shim(), cache_build_wt_stage(), and tier_compose_stage().
brix_sd_stage_destroy()
void brix_sd_stage_destroy (brix_sd_instance_t * inst)
Definition at line 264 of file sd_stage.c.
Referenced by brix_cache_storage_cleanup().
brix_sd_stage_instance_is()
int brix_sd_stage_instance_is (const brix_sd_instance_t * inst)
Definition at line 275 of file sd_stage.c.
References brix_sd_stage_driver.
Referenced by brix_sd_stage_reflush(), brix_sd_stage_source_instance(), brix_sd_stage_store_instance(), and stage_reconcile_one().
brix_sd_stage_reflush()
ngx_int_t brix_sd_stage_reflush (brix_sd_instance_t * inst, const char * key, const brix_stage_cred_t * cred)
Definition at line 312 of file sd_stage.c.
References brix_sd_stage_instance_is(), BRIX_STAGE_FLUSH, brix_stage_run_inline_cred(), key, sd_stage_inst_state::source, and sd_stage_inst_state::store.
Referenced by stage_reconcile_one().
brix_sd_stage_source_instance()
brix_sd_instance_t * brix_sd_stage_source_instance (const brix_sd_instance_t * inst)
Definition at line 284 of file sd_stage.c.
References brix_sd_stage_instance_is(), and SD_STAGE_SRC.
Referenced by brix_cache_storage_cleanup(), brix_vfs_decorator_source(), and brix_vfs_ns_leaf().
brix_sd_stage_store_instance()
brix_sd_instance_t * brix_sd_stage_store_instance (const brix_sd_instance_t * inst)
Definition at line 291 of file sd_stage.c.
References brix_sd_stage_instance_is().