nginx-xrootd: src/fs/backend/remote/sd_remote_internal.h File Reference
sd_remote_internal.h File Reference
#include "sd_remote.h"
#include "fs/backend/s3/sd_s3.h"
Functions
void sd_remote_s3_key (const brix_sd_remote_cfg_t *cfg, const char *key, char *dst, size_t dstcap)
void sd_remote_s3_params (const brix_sd_remote_cfg_t *cfg, const char *objpath, sd_s3_open_params *p)
int sd_remote_cred_gate (const brix_sd_cred_t *cred)
ssize_t sd_remote_getxattr (brix_sd_instance_t *inst, const char *path, const char *name, void *buf, size_t cap)
ssize_t sd_remote_listxattr (brix_sd_instance_t *inst, const char *path, void *buf, size_t cap)
ngx_int_t sd_remote_stat (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out)
ngx_int_t sd_remote_stat_cred (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out, const brix_sd_cred_t *cred)
brix_sd_staged_t * sd_remote_staged_open (brix_sd_instance_t *inst, const char *final_path, mode_t mode, int *err_out)
brix_sd_staged_t * sd_remote_staged_open_cred (brix_sd_instance_t *inst, const char *final_path, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
ssize_t sd_remote_staged_write (brix_sd_staged_t *h, const void *buf, size_t len, off_t off)
ngx_int_t sd_remote_staged_commit (brix_sd_staged_t *h, int noreplace)
void sd_remote_staged_abort (brix_sd_staged_t *h)
ngx_int_t sd_remote_unlink (brix_sd_instance_t *inst, const char *path, int is_dir)
ngx_int_t sd_remote_unlink_cred (brix_sd_instance_t *inst, const char *path, int is_dir, const brix_sd_cred_t *cred)
Function Documentation
sd_remote_cred_gate()
int sd_remote_cred_gate (const brix_sd_cred_t * cred)
Definition at line 72 of file sd_remote.c.
References brix_sd_cred_t::fallback_deny, brix_sd_cred_t::s3_ak, and brix_sd_cred_t::s3_sk.
Referenced by sd_remote_open_cred(), sd_remote_staged_open_cred(), sd_remote_stat_cred(), and sd_remote_unlink_cred().
sd_remote_getxattr()
ssize_t sd_remote_getxattr (brix_sd_instance_t * inst, const char * path, const char * name, void * buf, size_t cap)
Definition at line 35 of file sd_remote_meta.c.
References name, sd_remote_meta_open(), sd_s3_close(), and sd_s3_get_meta().
sd_remote_listxattr()
ssize_t sd_remote_listxattr (brix_sd_instance_t * inst, const char * path, void * buf, size_t cap)
Definition at line 76 of file sd_remote_meta.c.
References sd_remote_meta_open(), sd_s3_close(), and sd_s3_list_meta().
sd_remote_s3_key()
void sd_remote_s3_key (const brix_sd_remote_cfg_t * cfg, const char * key, char * dst, size_t dstcap)
Definition at line 29 of file sd_remote.c.
References brix_sd_remote_cfg_t::bucket, and key.
Referenced by sd_remote_meta_open(), sd_remote_open_impl(), sd_remote_staged_open_impl(), sd_remote_stat_impl(), and sd_remote_unlink_impl().
sd_remote_s3_params()
void sd_remote_s3_params (const brix_sd_remote_cfg_t * cfg, const char * objpath, sd_s3_open_params * p)
Definition at line 38 of file sd_remote.c.
References brix_sd_remote_cfg_t::access_key, sd_s3_open_params::ak, brix_sd_remote_cfg_t::host, sd_s3_open_params::host, sd_s3_open_params::key, brix_sd_remote_cfg_t::port, sd_s3_open_params::port, brix_sd_remote_cfg_t::put_checksum, sd_s3_open_params::put_checksum, brix_sd_remote_cfg_t::region, sd_s3_open_params::region, brix_sd_remote_cfg_t::secret_key, sd_s3_open_params::sk, brix_sd_remote_cfg_t::tctx, sd_s3_open_params::tctx, brix_sd_remote_cfg_t::timeout_ms, sd_s3_open_params::timeout_ms, brix_sd_remote_cfg_t::tls, sd_s3_open_params::tls, brix_sd_remote_cfg_t::transport, and sd_s3_open_params::transport.
Referenced by sd_remote_meta_open(), sd_remote_open_impl(), sd_remote_staged_commit(), sd_remote_staged_open_impl(), sd_remote_stat_impl(), and sd_remote_unlink_impl().
sd_remote_staged_abort()
void sd_remote_staged_abort (brix_sd_staged_t * h)
Definition at line 193 of file sd_remote_write.c.
References sd_remote_staged_state::s3, sd_s3_abort(), and sd_s3_close().
sd_remote_staged_commit()
ngx_int_t sd_remote_staged_commit (brix_sd_staged_t * h, int noreplace)
Definition at line 142 of file sd_remote_write.c.
References sd_remote_staged_state::ak, sd_s3_open_params::ak, sd_remote_staged_state::has_cred, sd_remote_staged_state::objpath, probe(), sd_remote_staged_state::region, sd_s3_open_params::region, sd_remote_staged_state::s3, sd_remote_s3_params(), sd_s3_close(), sd_s3_commit(), sd_s3_open_read(), sd_s3_size(), sd_remote_staged_state::sk, and sd_s3_open_params::sk.
sd_remote_staged_open()
brix_sd_staged_t * sd_remote_staged_open (brix_sd_instance_t * inst, const char * final_path, mode_t mode, int * err_out)
Definition at line 93 of file sd_remote_write.c.
References sd_remote_staged_open_impl().
sd_remote_staged_open_cred()
brix_sd_staged_t * sd_remote_staged_open_cred (brix_sd_instance_t * inst, const char * final_path, mode_t mode, const brix_sd_cred_t * cred, int * err_out)
Definition at line 107 of file sd_remote_write.c.
References brix_sd_cred_t::s3_ak, brix_sd_cred_t::s3_region, brix_sd_cred_t::s3_sk, sd_remote_cred_gate(), and sd_remote_staged_open_impl().
sd_remote_staged_write()
ssize_t sd_remote_staged_write (brix_sd_staged_t * h, const void * buf, size_t len, off_t off)
Definition at line 128 of file sd_remote_write.c.
References sd_remote_staged_state::s3, and sd_s3_pwrite().
sd_remote_stat()
ngx_int_t sd_remote_stat (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out)
Definition at line 136 of file sd_remote_meta.c.
References sd_remote_stat_impl().
sd_remote_stat_cred()
ngx_int_t sd_remote_stat_cred (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out, const brix_sd_cred_t * cred)
Definition at line 147 of file sd_remote_meta.c.
References brix_sd_cred_t::s3_ak, brix_sd_cred_t::s3_region, brix_sd_cred_t::s3_sk, sd_remote_cred_gate(), and sd_remote_stat_impl().
sd_remote_unlink()
ngx_int_t sd_remote_unlink (brix_sd_instance_t * inst, const char * path, int is_dir)
Definition at line 228 of file sd_remote_write.c.
References sd_remote_unlink_impl().
sd_remote_unlink_cred()
ngx_int_t sd_remote_unlink_cred (brix_sd_instance_t * inst, const char * path, int is_dir, const brix_sd_cred_t * cred)
Definition at line 237 of file sd_remote_write.c.
References brix_sd_cred_t::s3_ak, brix_sd_cred_t::s3_region, brix_sd_cred_t::s3_sk, sd_remote_cred_gate(), and sd_remote_unlink_impl().