nginx-xrootd: src/fs/backend/xroot/sd_xroot_ns_cred.c File Reference
sd_xroot_ns_cred.c File Reference
#include "sd_xroot_internal.h"
#include "auth/crypto/pki_build.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <openssl/x509.h>
#include <openssl/x509_vfy.h>
Functions
ngx_int_t sd_xroot_unlink_cred (brix_sd_instance_t *inst, const char *path, int is_dir, const brix_sd_cred_t *cred)
ngx_int_t sd_xroot_rename_cred (brix_sd_instance_t *inst, const char *src, const char *dst, int noreplace, const brix_sd_cred_t *cred)
ngx_int_t sd_xroot_server_copy_cred (brix_sd_instance_t *inst, const char *src, const char *dst, off_t *bytes_out, const brix_sd_cred_t *cred)
ssize_t sd_xroot_getxattr_cred (brix_sd_instance_t *inst, const char *path, const char *name, void *buf, size_t cap, const brix_sd_cred_t *cred)
ssize_t sd_xroot_listxattr_cred (brix_sd_instance_t *inst, const char *path, void *buf, size_t cap, const brix_sd_cred_t *cred)
ngx_int_t sd_xroot_setxattr_cred (brix_sd_instance_t *inst, const char *path, const char *name, const void *val, size_t len, int flags, const brix_sd_cred_t *cred)
ngx_int_t sd_xroot_removexattr_cred (brix_sd_instance_t *inst, const char *path, const char *name, const brix_sd_cred_t *cred)
Function Documentation
sd_xroot_getxattr_cred()
ssize_t sd_xroot_getxattr_cred (brix_sd_instance_t * inst, const char * path, const char * name, void * buf, size_t cap, const brix_sd_cred_t * cred)
Definition at line 124 of file sd_xroot_ns_cred.c.
References brix_cache_origin_close(), brix_cache_origin_getfattr(), sd_xroot_inst_state::conf, name, sd_xroot_fattr_unmap(), and sd_xroot_session().
sd_xroot_listxattr_cred()
ssize_t sd_xroot_listxattr_cred (brix_sd_instance_t * inst, const char * path, void * buf, size_t cap, const brix_sd_cred_t * cred)
Definition at line 145 of file sd_xroot_ns_cred.c.
References brix_cache_origin_close(), brix_cache_origin_listfattr(), sd_xroot_inst_state::conf, ngx_memcpy, SD_XROOT_FATTR_PFX, SD_XROOT_FATTR_PFX_LEN, and sd_xroot_session().
sd_xroot_removexattr_cred()
ngx_int_t sd_xroot_removexattr_cred (brix_sd_instance_t * inst, const char * path, const char * name, const brix_sd_cred_t * cred)
Definition at line 212 of file sd_xroot_ns_cred.c.
References brix_cache_origin_close(), brix_cache_origin_delfattr(), sd_xroot_inst_state::conf, name, sd_xroot_fattr_unmap(), and sd_xroot_session().
sd_xroot_rename_cred()
ngx_int_t sd_xroot_rename_cred (brix_sd_instance_t * inst, const char * src, const char * dst, int noreplace, const brix_sd_cred_t * cred)
Definition at line 67 of file sd_xroot_ns_cred.c.
References brix_cache_origin_close(), brix_cache_origin_rename(), sd_xroot_inst_state::conf, and sd_xroot_session().
sd_xroot_server_copy_cred()
ngx_int_t sd_xroot_server_copy_cred (brix_sd_instance_t * inst, const char * src, const char * dst, off_t * bytes_out, const brix_sd_cred_t * cred)
Definition at line 89 of file sd_xroot_ns_cred.c.
References brix_cache_origin_close(), brix_cache_origin_close_file(), brix_cache_origin_open(), brix_cache_origin_open_write(), brix_cache_fill_t::clean_path, sd_xroot_inst_state::conf, sd_xroot_copy_body(), sd_xroot_errno(), sd_xroot_session(), and XRD_FHANDLE_LEN.
sd_xroot_setxattr_cred()
ngx_int_t sd_xroot_setxattr_cred (brix_sd_instance_t * inst, const char * path, const char * name, const void * val, size_t len, int flags, const brix_sd_cred_t * cred)
Definition at line 190 of file sd_xroot_ns_cred.c.
References brix_cache_origin_close(), brix_cache_origin_setfattr(), sd_xroot_inst_state::conf, name, sd_xroot_fattr_unmap(), and sd_xroot_session().
sd_xroot_unlink_cred()
ngx_int_t sd_xroot_unlink_cred (brix_sd_instance_t * inst, const char * path, int is_dir, const brix_sd_cred_t * cred)
Definition at line 45 of file sd_xroot_ns_cred.c.
References brix_cache_origin_close(), brix_cache_origin_rm(), brix_cache_origin_rmdir(), sd_xroot_inst_state::conf, and sd_xroot_session().