nginx-xrootd: src/fs/backend/cache/sd_cache_partial.c File Reference
sd_cache_partial.c File Reference
#include "sd_cache.h"
#include "sd_cache_internal.h"
#include "sd_cache_policy.h"
#include "protocols/cvmfs/classify.h"
#include "observability/metrics/metrics.h"
#include "observability/metrics/metrics_macros.h"
#include "fs/cache/cstore.h"
#include "fs/backend/http/sd_http.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct sd_cache_partial_t
Functions
static int partial_source_ensure (sd_cache_partial_t *p)
static int partial_block_copy (sd_cache_partial_t *p, off_t bstart, size_t blen)
static int sd_cache_fill_block (sd_cache_partial_t *p, uint64_t blk)
static void partial_capture_cred (sd_cache_partial_t *p, const brix_sd_cred_t *cred)
static void partial_adopt_bitmap (sd_cache_partial_t *p, const char *cpath)
brix_sd_obj_t * sd_cache_partial_open (brix_sd_instance_t *inst, sd_cache_inst_state *st, const char *key, const brix_sd_cred_t *cred, int *err_out)
static int sd_cache_fill_block_cb (void *ctx, uint64_t blk)
ssize_t sd_cache_pread (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
ngx_int_t sd_cache_close (brix_sd_obj_t *obj)
ngx_int_t sd_cache_fstat (brix_sd_obj_t *obj, brix_sd_stat_t *out)
ngx_fd_t sd_cache_read_sendfile_fd (brix_sd_obj_t *obj, off_t off, size_t len, unsigned want_zerocopy)
Function Documentation
partial_adopt_bitmap()
static void partial_adopt_bitmap (sd_cache_partial_t * p, const char * cpath) static
Definition at line 250 of file sd_cache_partial.c.
References sd_cache_partial_t::bitmap, sd_cache_partial_t::bitmap_len, sd_cache_partial_t::block_size, brix_cache_cinfo_t::block_size, brix_cache_cinfo_load(), sd_cache_partial_t::size, and brix_cache_cinfo_t::size.
Referenced by sd_cache_partial_open().
partial_block_copy()
static int partial_block_copy (sd_cache_partial_t * p, off_t bstart, size_t blen) static
Definition at line 140 of file sd_cache_partial.c.
References sd_cache_partial_t::cache_fd, and sd_cache_partial_t::src_obj.
Referenced by sd_cache_fill_block().
partial_capture_cred()
static void partial_capture_cred (sd_cache_partial_t * p, const brix_sd_cred_t * cred) static
Definition at line 221 of file sd_cache_partial.c.
References sd_cache_partial_t::cred_key, sd_cache_partial_t::cred_principal, sd_cache_partial_t::cred_proxy, brix_sd_cred_t::key, brix_sd_cred_t::principal, and brix_sd_cred_t::x509_proxy.
Referenced by sd_cache_partial_open().
partial_source_ensure()
static int partial_source_ensure (sd_cache_partial_t * p) static
Definition at line 90 of file sd_cache_partial.c.
References BRIX_SD_O_READ, brix_sd_open_maybe_cred(), sd_cache_partial_t::cred_key, sd_cache_partial_t::cred_principal, sd_cache_partial_t::cred_proxy, sd_cache_partial_t::key, brix_sd_cred_t::key, brix_sd_cred_t::principal, sd_cache_partial_t::source, sd_cache_partial_t::src_obj, and brix_sd_cred_t::x509_proxy.
Referenced by sd_cache_fill_block().
sd_cache_close()
ngx_int_t sd_cache_close (brix_sd_obj_t * obj)
Definition at line 374 of file sd_cache_partial.c.
References sd_cache_partial_t::bitmap, brix_sd_obj_release(), sd_cache_partial_t::cache_fd, close(), and sd_cache_partial_t::src_obj.
sd_cache_fill_block()
static int sd_cache_fill_block (sd_cache_partial_t * p, uint64_t blk) static
Definition at line 180 of file sd_cache_partial.c.
References sd_cache_partial_t::bitmap, sd_cache_partial_t::block_size, brix_cache_cinfo_mark_block(), brix_cache_cinfo_record_block(), sd_cache_partial_t::cache_path, sd_cache_partial_t::log, sd_cache_partial_t::mode, sd_cache_partial_t::mtime, partial_block_copy(), partial_source_ensure(), and sd_cache_partial_t::size.
Referenced by sd_cache_fill_block_cb().
sd_cache_fill_block_cb()
static int sd_cache_fill_block_cb (void * ctx, uint64_t blk) static
Definition at line 353 of file sd_cache_partial.c.
References sd_cache_fill_block().
Referenced by sd_cache_pread().
sd_cache_fstat()
ngx_int_t sd_cache_fstat (brix_sd_obj_t * obj, brix_sd_stat_t * out)
Definition at line 393 of file sd_cache_partial.c.
References brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, sd_cache_partial_t::mtime, brix_sd_stat_t::mtime, sd_cache_partial_t::size, and brix_sd_stat_t::size.
sd_cache_partial_open()
brix_sd_obj_t * sd_cache_partial_open (brix_sd_instance_t * inst, sd_cache_inst_state * st, const char * key, const brix_sd_cred_t * cred, int * err_out)
Definition at line 282 of file sd_cache_partial.c.
References sd_cache_partial_t::bitmap_len, sd_cache_partial_t::block_size, brix_cache_cinfo_bitmap_len(), brix_cache_cinfo_nblocks(), brix_cstore_partial_open(), sd_cache_partial_t::cache_fd, sd_cache_partial_t::cache_path, close(), sd_cache_inst_state::cstore, sd_cache_partial_t::key, key, sd_cache_inst_state::log, sd_cache_partial_t::log, sd_cache_partial_t::mode, brix_sd_stat_t::mode, sd_cache_partial_t::mtime, brix_sd_stat_t::mtime, sd_cache_partial_t::nblocks, partial_adopt_bitmap(), partial_capture_cred(), PATH_MAX, sd_cache_inst_state::policy, sd_cache_partial_t::size, brix_sd_stat_t::size, brix_cache_policy_t::slice_size, sd_cache_inst_state::source, and sd_cache_partial_t::source.
Referenced by cache_open_miss_serve().
sd_cache_pread()
ssize_t sd_cache_pread (brix_sd_obj_t * obj, void * buf, size_t len, off_t off)
Definition at line 359 of file sd_cache_partial.c.
References sd_cache_partial_t::bitmap, sd_cache_partial_t::block_size, brix_cstore_serve_pread(), sd_cache_partial_t::cache_fd, sd_cache_partial_t::nblocks, sd_cache_fill_block_cb(), and sd_cache_partial_t::size.
sd_cache_read_sendfile_fd()
ngx_fd_t sd_cache_read_sendfile_fd (brix_sd_obj_t * obj, off_t off, size_t len, unsigned want_zerocopy)
Definition at line 409 of file sd_cache_partial.c.