nginx-xrootd: src/fs/backend/rados/sd_ceph_compat.c File Reference
sd_ceph_compat.c File Reference
#include "sd_ceph_compat.h"
#include <string.h>
Macros
#define SUFFIX BRIX_CEPH_FIRST_STRIPE_SUFFIX
#define SUFFIX_LEN (sizeof(BRIX_CEPH_FIRST_STRIPE_SUFFIX) - 1) /* 17 */
Functions
int sd_ceph_first_stripe (const char *name, char *oid, size_t cap)
int sd_ceph_oid_is_first_stripe (const char *oid)
int sd_ceph_oid_to_pfn (const char *oid, char *pfn, size_t cap)
int sd_ceph_oid_is_stripe_data (const char *oid)
Macro Definition Documentation
SUFFIX
#define SUFFIX BRIX_CEPH_FIRST_STRIPE_SUFFIX
Definition at line 9 of file sd_ceph_compat.c.
SUFFIX_LEN
#define SUFFIX_LEN (sizeof(BRIX_CEPH_FIRST_STRIPE_SUFFIX) - 1) /* 17 */
Definition at line 10 of file sd_ceph_compat.c.
Function Documentation
sd_ceph_first_stripe()
int sd_ceph_first_stripe (const char * name, char * oid, size_t cap)
Definition at line 13 of file sd_ceph_compat.c.
References name, SUFFIX, and SUFFIX_LEN.
sd_ceph_oid_is_first_stripe()
int sd_ceph_oid_is_first_stripe (const char * oid)
Definition at line 30 of file sd_ceph_compat.c.
References SUFFIX, and SUFFIX_LEN.
Referenced by sd_ceph_oid_is_stripe_data(), sd_ceph_oid_to_pfn(), and test_striper_layout().
sd_ceph_oid_is_stripe_data()
int sd_ceph_oid_is_stripe_data (const char * oid)
Definition at line 63 of file sd_ceph_compat.c.
References c, sd_ceph_oid_is_first_stripe(), and SUFFIX_LEN.
Referenced by test_striper_layout().
sd_ceph_oid_to_pfn()
int sd_ceph_oid_to_pfn (const char * oid, char * pfn, size_t cap)
Definition at line 45 of file sd_ceph_compat.c.
References sd_ceph_oid_is_first_stripe(), and SUFFIX_LEN.
Referenced by test_striper_layout().