nginx-xrootd: src/fs/backend/pblock/sd_pblock_unittest_dedup.c File Reference
sd_pblock_unittest_dedup.c File Reference
#include "fs/backend/sd.h"
#include "sd_pblock_catalog.h"
#include "sd_pblock_unittest_internal.h"
#include <errno.h>
#include <ftw.h>
#include <limits.h>
#include <pthread.h>
#include <sqlite3.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>
Data Structures
struct break_arg
Macros
#define _GNU_SOURCE /* nftw(3) + FTW_PHYS for the on-disk block scan */
Functions
static void q_blob_id (const char *root, const char *path, char *out, size_t cap)
static int q_refcount (const char *root, const char *blob_id)
static int q_count (const char *root, const char *sql)
static int staged_put (brix_sd_instance_t *inst, const char *path, const char *data, size_t len)
static int trunc_write (brix_sd_instance_t *inst, const char *path, const char *data, size_t len)
static void * break_body (void *p)
void test_dedup_refs (void)
void test_dedup_forged_hash (void)
void test_dedup_gate_closed (void)
void test_snapshot (void)
void test_versioning (void)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE /* nftw(3) + FTW_PHYS for the on-disk block scan */
Definition at line 9 of file sd_pblock_unittest_dedup.c.
Function Documentation
break_body()
static void * break_body (void * p) static
Definition at line 158 of file sd_pblock_unittest_dedup.c.
References break_arg::data, break_arg::inst, break_arg::len, break_arg::path, break_arg::rc, and trunc_write().
Referenced by test_dedup_refs().
q_blob_id()
static void q_blob_id (const char * root, const char * path, char * out, size_t cap) static
Definition at line 35 of file sd_pblock_unittest_dedup.c.
References CHECK, and PATH_MAX.
Referenced by test_dedup_forged_hash(), test_dedup_gate_closed(), test_dedup_refs(), and test_versioning().
q_count()
static int q_count (const char * root, const char * sql) static
Definition at line 88 of file sd_pblock_unittest_dedup.c.
References CHECK, and PATH_MAX.
Referenced by test_versioning().
q_refcount()
static int q_refcount (const char * root, const char * blob_id) static
Definition at line 62 of file sd_pblock_unittest_dedup.c.
References CHECK, and PATH_MAX.
Referenced by test_dedup_refs(), and test_versioning().
staged_put()
static int staged_put (brix_sd_instance_t * inst, const char * path, const char * data, size_t len) static
Definition at line 111 of file sd_pblock_unittest_dedup.c.
References D, and s.
Referenced by test_versioning().
test_dedup_forged_hash()
void test_dedup_forged_hash (void)
Definition at line 256 of file sd_pblock_unittest_dedup.c.
References CHECK, D, break_arg::inst, lab_write_sidecar(), PATH_MAX, PBLOCK_BLOB_ID_CAP, q_blob_id(), read_file(), and write_file().
Referenced by main().
test_dedup_gate_closed()
void test_dedup_gate_closed (void)
Definition at line 337 of file sd_pblock_unittest_dedup.c.
References CHECK, D, break_arg::inst, PBLOCK_BLOB_ID_CAP, q_blob_id(), read_file(), and write_file().
Referenced by main().
test_dedup_refs()
void test_dedup_refs (void)
Definition at line 167 of file sd_pblock_unittest_dedup.c.
References break_body(), CHECK, D, break_arg::inst, lab_write_sidecar(), PBLOCK_BLOB_ID_CAP, q_blob_id(), q_refcount(), break_arg::rc, read_file(), trunc_write(), and write_file().
Referenced by main().
test_snapshot()
void test_snapshot (void)
Definition at line 375 of file sd_pblock_unittest_dedup.c.
References BRIX_SD_O_READ, CHECK, D, break_arg::inst, lab_write_sidecar(), pb_close(), read_file(), and write_file().
Referenced by main().
test_versioning()
void test_versioning (void)
Definition at line 454 of file sd_pblock_unittest_dedup.c.
References CHECK, D, break_arg::inst, lab_write_sidecar(), PBLOCK_BLOB_ID_CAP, q_blob_id(), q_count(), q_refcount(), read_file(), and staged_put().
Referenced by main().
trunc_write()
static int trunc_write (brix_sd_instance_t * inst, const char * path, const char * data, size_t len) static
Definition at line 130 of file sd_pblock_unittest_dedup.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_READ, BRIX_SD_O_TRUNC, BRIX_SD_O_WRITE, D, and pb_close().
Referenced by break_body(), and test_dedup_refs().