nginx-xrootd: src/fs/backend/s3/sd_s3_sign.c File Reference
sd_s3_sign.c File Reference
#include "sd_s3.h"
#include "sd_s3_internal.h"
#include "core/compat/crypto.h"
#include "core/compat/hex.h"
#include "core/compat/sigv4.h"
#include "core/compat/uri.h"
#include "core/compat/host_format.h"
#include <errno.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
Functions
void sd_s3_set_err (char *errbuf, size_t errcap, const char *fmt,...)
void sd_s3_utc_now (char amzdate[20], char datestamp[12])
void sd_s3_sha256_hex (const void *data, size_t len, char *out)
int sd_s3_sign (const sd_s3_file *f, const char *method, const char *canon_qs, char *hdrs, size_t hdrsz)
int sd_s3_status_err (int status, const char *op, const char *key, char *errbuf, size_t errcap)
Function Documentation
sd_s3_set_err()
void sd_s3_set_err (char * errbuf, size_t errcap, const char * fmt, ...)
Definition at line 36 of file sd_s3_sign.c.
Referenced by sd_s3_check_sequential(), sd_s3_commit(), sd_s3_delete(), sd_s3_etag_ensure_cap(), sd_s3_get_meta(), sd_s3_get_unixattr(), sd_s3_mpu_complete(), sd_s3_mpu_create(), sd_s3_mpu_upload_part(), sd_s3_open_read(), sd_s3_open_write(), sd_s3_pread(), sd_s3_pwrite(), sd_s3_set_meta_f(), sd_s3_set_unixattr(), sd_s3_size(), and sd_s3_status_err().
sd_s3_sha256_hex()
void sd_s3_sha256_hex (const void * data, size_t len, char * out)
Definition at line 93 of file sd_s3_sign.c.
References brix_hex_encode(), and brix_sha256().
Referenced by sd_s3_canonical_request(), and sd_s3_sign().
sd_s3_sign()
int sd_s3_sign (const sd_s3_file * f, const char * method, const char * canon_qs, char * hdrs, size_t hdrsz)
Definition at line 104 of file sd_s3_sign.c.
References sd_s3_file::ak, brix_format_host_port(), brix_hex_encode(), brix_hmac_sha256(), brix_http_urlencode(), brix_sigv4_signing_key(), sd_s3_file::host, sd_s3_file::key, sd_s3_file::port, sd_s3_file::region, scope, sd_s3_sha256_hex(), sd_s3_utc_now(), and sd_s3_file::sk.
Referenced by sd_s3_commit(), sd_s3_delete(), sd_s3_get_meta(), sd_s3_mpu_abort(), sd_s3_mpu_complete(), sd_s3_mpu_create(), sd_s3_mpu_upload_part(), sd_s3_pread(), and sd_s3_size().
sd_s3_status_err()
int sd_s3_status_err (int status, const char * op, const char * key, char * errbuf, size_t errcap)
Definition at line 167 of file sd_s3_sign.c.
References key, op, and sd_s3_set_err().
Referenced by sd_s3_commit(), sd_s3_delete(), sd_s3_get_meta(), sd_s3_mpu_complete(), sd_s3_mpu_create(), sd_s3_mpu_upload_part(), sd_s3_pread(), sd_s3_set_meta_f(), and sd_s3_size().
sd_s3_utc_now()
void sd_s3_utc_now (char amzdate[20], char datestamp[12])
Definition at line 53 of file sd_s3_sign.c.
Referenced by sd_s3_sign(), and sd_s3_sign_prepare().