nginx-xrootd: src/fs/backend/xroot/sd_xroot_ns.c File Reference
sd_xroot_ns.c File Reference
#include "sd_xroot_internal.h"
#include "auth/crypto/pki_build.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <openssl/x509.h>
#include <openssl/x509_vfy.h>
Data Structures
struct sd_xroot_dir_state
Macros
#define SD_XROOT_FATTR_PFX "user.U."
#define SD_XROOT_FATTR_PFX_LEN 7
Functions
static const char * sd_xroot_fattr_unmap (const char *name)
static int sd_xroot_cred_must_deny (const brix_sd_cred_t *cred)
static void sd_xroot_cred_copy (brix_cache_fill_t *t, const brix_sd_cred_t *cred)
static int sd_xroot_session (ngx_stream_brix_srv_conf_t *conf, const brix_sd_cred_t *cred, brix_cache_origin_conn_t *oc, brix_cache_fill_t **t_out, int *err_out)
ssize_t sd_xroot_getxattr (brix_sd_instance_t *inst, const char *path, const char *name, void *buf, size_t cap)
ssize_t sd_xroot_listxattr (brix_sd_instance_t *inst, const char *path, void *buf, size_t cap)
ngx_int_t sd_xroot_setxattr (brix_sd_instance_t *inst, const char *path, const char *name, const void *val, size_t len, int flags)
ngx_int_t sd_xroot_removexattr (brix_sd_instance_t *inst, const char *path, const char *name)
ngx_int_t sd_xroot_rename (brix_sd_instance_t *inst, const char *src, const char *dst, int noreplace)
ngx_int_t sd_xroot_unlink (brix_sd_instance_t *inst, const char *path, int is_dir)
static ngx_int_t sd_xroot_copy_body (brix_cache_fill_t *t, brix_cache_origin_conn_t *oc, const u_char *src_fh, const u_char *dst_fh, off_t *bytes_out)
ngx_int_t sd_xroot_server_copy (brix_sd_instance_t *inst, const char *src, const char *dst, off_t *bytes_out)
ngx_int_t sd_xroot_unlink_cred (brix_sd_instance_t *inst, const char *path, int is_dir, const brix_sd_cred_t *cred)
ngx_int_t sd_xroot_rename_cred (brix_sd_instance_t *inst, const char *src, const char *dst, int noreplace, const brix_sd_cred_t *cred)
ngx_int_t sd_xroot_server_copy_cred (brix_sd_instance_t *inst, const char *src, const char *dst, off_t *bytes_out, const brix_sd_cred_t *cred)
ssize_t sd_xroot_getxattr_cred (brix_sd_instance_t *inst, const char *path, const char *name, void *buf, size_t cap, const brix_sd_cred_t *cred)
ssize_t sd_xroot_listxattr_cred (brix_sd_instance_t *inst, const char *path, void *buf, size_t cap, const brix_sd_cred_t *cred)
ngx_int_t sd_xroot_setxattr_cred (brix_sd_instance_t *inst, const char *path, const char *name, const void *val, size_t len, int flags, const brix_sd_cred_t *cred)
ngx_int_t sd_xroot_removexattr_cred (brix_sd_instance_t *inst, const char *path, const char *name, const brix_sd_cred_t *cred)
static brix_sd_dir_t * sd_xroot_opendir_common (brix_sd_instance_t *inst, const char *path, const brix_sd_cred_t *cred, int *err_out)
brix_sd_dir_t * sd_xroot_opendir (brix_sd_instance_t *inst, const char *path, int *err_out)
brix_sd_dir_t * sd_xroot_opendir_cred (brix_sd_instance_t *inst, const char *path, int *err_out, const brix_sd_cred_t *cred)
ngx_int_t sd_xroot_readdir (brix_sd_dir_t *d, brix_sd_dirent_t *out)
ngx_int_t sd_xroot_closedir (brix_sd_dir_t *d)
Macro Definition Documentation
SD_XROOT_FATTR_PFX
#define SD_XROOT_FATTR_PFX "user.U."
Definition at line 34 of file sd_xroot_ns.c.
SD_XROOT_FATTR_PFX_LEN
#define SD_XROOT_FATTR_PFX_LEN 7
Definition at line 35 of file sd_xroot_ns.c.
Function Documentation
sd_xroot_closedir()
ngx_int_t sd_xroot_closedir (brix_sd_dir_t * d)
Definition at line 714 of file sd_xroot_ns.c.
References brix_cache_dirlist_free(), and sd_xroot_dir_state::dl.
sd_xroot_copy_body()
static ngx_int_t sd_xroot_copy_body (brix_cache_fill_t * t, brix_cache_origin_conn_t * oc, const u_char * src_fh, const u_char * dst_fh, off_t * bytes_out) static
Definition at line 293 of file sd_xroot_ns.c.
References brix_cache_origin_read_chunk(), brix_cache_origin_sync(), brix_cache_origin_truncate(), brix_cache_origin_write_chunk(), brix_cache_sink_t::fd, brix_cache_read_range_t::got, brix_cache_sink_t::mem, brix_cache_sink_t::mem_cap, brix_cache_read_range_t::read_off, and brix_cache_read_range_t::want.
Referenced by sd_xroot_server_copy(), and sd_xroot_server_copy_cred().
sd_xroot_cred_copy()
static void sd_xroot_cred_copy (brix_cache_fill_t * t, const brix_sd_cred_t * cred) static
Definition at line 73 of file sd_xroot_ns.c.
References brix_sd_cred_t::bearer, brix_cache_fill_t::cred_bearer, brix_cache_fill_t::cred_principal, brix_cache_fill_t::cred_x509_proxy, brix_sd_cred_t::principal, and brix_sd_cred_t::x509_proxy.
Referenced by sd_xroot_session().
sd_xroot_cred_must_deny()
static int sd_xroot_cred_must_deny (const brix_sd_cred_t * cred) static
Definition at line 57 of file sd_xroot_ns.c.
References brix_sd_cred_t::bearer, brix_sd_cred_t::fallback_deny, and brix_sd_cred_t::x509_proxy.
Referenced by sd_xroot_session().
sd_xroot_fattr_unmap()
static const char * sd_xroot_fattr_unmap (const char * name) static
Definition at line 38 of file sd_xroot_ns.c.
References name, SD_XROOT_FATTR_PFX, and SD_XROOT_FATTR_PFX_LEN.
Referenced by sd_xroot_getxattr(), sd_xroot_getxattr_cred(), sd_xroot_removexattr(), sd_xroot_removexattr_cred(), sd_xroot_setxattr(), and sd_xroot_setxattr_cred().
sd_xroot_getxattr()
ssize_t sd_xroot_getxattr (brix_sd_instance_t * inst, const char * path, const char * name, void * buf, size_t cap)
Definition at line 143 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_getfattr(), sd_xroot_inst_state::conf, name, sd_xroot_fattr_unmap(), and sd_xroot_session().
sd_xroot_getxattr_cred()
ssize_t sd_xroot_getxattr_cred (brix_sd_instance_t * inst, const char * path, const char * name, void * buf, size_t cap, const brix_sd_cred_t * cred)
Definition at line 479 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_getfattr(), sd_xroot_inst_state::conf, name, sd_xroot_fattr_unmap(), and sd_xroot_session().
sd_xroot_listxattr()
ssize_t sd_xroot_listxattr (brix_sd_instance_t * inst, const char * path, void * buf, size_t cap)
Definition at line 163 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_listfattr(), sd_xroot_inst_state::conf, ngx_memcpy, SD_XROOT_FATTR_PFX, SD_XROOT_FATTR_PFX_LEN, and sd_xroot_session().
sd_xroot_listxattr_cred()
ssize_t sd_xroot_listxattr_cred (brix_sd_instance_t * inst, const char * path, void * buf, size_t cap, const brix_sd_cred_t * cred)
Definition at line 500 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_listfattr(), sd_xroot_inst_state::conf, ngx_memcpy, SD_XROOT_FATTR_PFX, SD_XROOT_FATTR_PFX_LEN, and sd_xroot_session().
sd_xroot_opendir()
brix_sd_dir_t * sd_xroot_opendir (brix_sd_instance_t * inst, const char * path, int * err_out)
Definition at line 668 of file sd_xroot_ns.c.
References sd_xroot_opendir_common().
sd_xroot_opendir_common()
static brix_sd_dir_t * sd_xroot_opendir_common (brix_sd_instance_t * inst, const char * path, const brix_sd_cred_t * cred, int * err_out) static
Definition at line 615 of file sd_xroot_ns.c.
References brix_cache_dirlist_free(), brix_cache_dirlist_init(), brix_cache_origin_close(), brix_cache_origin_dirlist(), sd_xroot_inst_state::conf, sd_xroot_dir_state::dl, sd_xroot_errno(), and sd_xroot_session().
Referenced by sd_xroot_opendir(), and sd_xroot_opendir_cred().
sd_xroot_opendir_cred()
brix_sd_dir_t * sd_xroot_opendir_cred (brix_sd_instance_t * inst, const char * path, int * err_out, const brix_sd_cred_t * cred)
Definition at line 676 of file sd_xroot_ns.c.
References sd_xroot_opendir_common().
sd_xroot_readdir()
ngx_int_t sd_xroot_readdir (brix_sd_dir_t * d, brix_sd_dirent_t * out)
Definition at line 688 of file sd_xroot_ns.c.
References brix_cache_dirlist_t::count, sd_xroot_dir_state::dl, brix_sd_dirent_t::name, brix_cache_dirlist_t::names, and sd_xroot_dir_state::next.
sd_xroot_removexattr()
ngx_int_t sd_xroot_removexattr (brix_sd_instance_t * inst, const char * path, const char * name)
Definition at line 230 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_delfattr(), sd_xroot_inst_state::conf, name, sd_xroot_fattr_unmap(), and sd_xroot_session().
sd_xroot_removexattr_cred()
ngx_int_t sd_xroot_removexattr_cred (brix_sd_instance_t * inst, const char * path, const char * name, const brix_sd_cred_t * cred)
Definition at line 567 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_delfattr(), sd_xroot_inst_state::conf, name, sd_xroot_fattr_unmap(), and sd_xroot_session().
sd_xroot_rename()
ngx_int_t sd_xroot_rename (brix_sd_instance_t * inst, const char * src, const char * dst, int noreplace)
Definition at line 248 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_rename(), sd_xroot_inst_state::conf, and sd_xroot_session().
sd_xroot_rename_cred()
ngx_int_t sd_xroot_rename_cred (brix_sd_instance_t * inst, const char * src, const char * dst, int noreplace, const brix_sd_cred_t * cred)
Definition at line 422 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_rename(), sd_xroot_inst_state::conf, and sd_xroot_session().
sd_xroot_server_copy()
ngx_int_t sd_xroot_server_copy (brix_sd_instance_t * inst, const char * src, const char * dst, off_t * bytes_out)
Definition at line 346 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_close_file(), brix_cache_origin_open(), brix_cache_origin_open_write(), brix_cache_fill_t::clean_path, sd_xroot_inst_state::conf, sd_xroot_copy_body(), sd_xroot_errno(), sd_xroot_session(), and XRD_FHANDLE_LEN.
sd_xroot_server_copy_cred()
ngx_int_t sd_xroot_server_copy_cred (brix_sd_instance_t * inst, const char * src, const char * dst, off_t * bytes_out, const brix_sd_cred_t * cred)
Definition at line 444 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_close_file(), brix_cache_origin_open(), brix_cache_origin_open_write(), brix_cache_fill_t::clean_path, sd_xroot_inst_state::conf, sd_xroot_copy_body(), sd_xroot_errno(), sd_xroot_session(), and XRD_FHANDLE_LEN.
sd_xroot_session()
static int sd_xroot_session (ngx_stream_brix_srv_conf_t * conf, const brix_sd_cred_t * cred, brix_cache_origin_conn_t * oc, brix_cache_fill_t ** t_out, int * err_out) static
Definition at line 108 of file sd_xroot_ns.c.
References brix_cache_origin_bootstrap(), brix_cache_origin_close(), brix_cache_origin_connect(), brix_cache_fill_t::conf, brix_cache_origin_conn_t::fd, sd_xroot_cred_copy(), sd_xroot_cred_must_deny(), and sd_xroot_errno().
Referenced by sd_xroot_getxattr(), sd_xroot_getxattr_cred(), sd_xroot_listxattr(), sd_xroot_listxattr_cred(), sd_xroot_opendir_common(), sd_xroot_removexattr(), sd_xroot_removexattr_cred(), sd_xroot_rename(), sd_xroot_rename_cred(), sd_xroot_server_copy(), sd_xroot_server_copy_cred(), sd_xroot_setxattr(), sd_xroot_setxattr_cred(), sd_xroot_unlink(), and sd_xroot_unlink_cred().
sd_xroot_setxattr()
ngx_int_t sd_xroot_setxattr (brix_sd_instance_t * inst, const char * path, const char * name, const void * val, size_t len, int flags)
Definition at line 210 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_setfattr(), sd_xroot_inst_state::conf, name, sd_xroot_fattr_unmap(), and sd_xroot_session().
sd_xroot_setxattr_cred()
ngx_int_t sd_xroot_setxattr_cred (brix_sd_instance_t * inst, const char * path, const char * name, const void * val, size_t len, int flags, const brix_sd_cred_t * cred)
Definition at line 545 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_setfattr(), sd_xroot_inst_state::conf, name, sd_xroot_fattr_unmap(), and sd_xroot_session().
sd_xroot_unlink()
ngx_int_t sd_xroot_unlink (brix_sd_instance_t * inst, const char * path, int is_dir)
Definition at line 273 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_rm(), brix_cache_origin_rmdir(), sd_xroot_inst_state::conf, and sd_xroot_session().
sd_xroot_unlink_cred()
ngx_int_t sd_xroot_unlink_cred (brix_sd_instance_t * inst, const char * path, int is_dir, const brix_sd_cred_t * cred)
Definition at line 400 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_rm(), brix_cache_origin_rmdir(), sd_xroot_inst_state::conf, and sd_xroot_session().