nginx-xrootd: src/fs/backend/sd_registry.h File Reference
sd_registry.h File Reference
#include <errno.h>
#include <sys/types.h>
#include <sys/uio.h>
Functions
const brix_sd_driver_t * brix_sd_driver_find (const char *name)
ngx_uint_t brix_sd_driver_count (void)
const brix_sd_driver_t * brix_sd_driver_at (ngx_uint_t i)
brix_sd_instance_t * brix_sd_instance_create (ngx_log_t *log, const char *name, void *driver_conf, int *err_out)
void brix_sd_instance_destroy (brix_sd_instance_t *inst)
int brix_sd_posix_open_unconfined (const char *path, int sd_flags, mode_t mode)
int brix_sd_block_open_unconfined (const char *path, int sd_flags, mode_t mode)
const brix_sd_driver_t * brix_sd_default_driver (void)
brix_sd_instance_t * brix_sd_posix_borrow_instance (ngx_pool_t *pool, ngx_log_t *log, int rootfd, const char *root_canon)
static void brix_sd_posix_wrap (brix_sd_obj_t *obj, ngx_fd_t fd)
static ssize_t brix_sd_obj_preadv (brix_sd_obj_t *obj, const struct iovec *iov, int iovcnt, off_t off)
Variables
const brix_sd_driver_t brix_sd_posix_driver
const brix_sd_driver_t brix_sd_block_driver
Function Documentation
brix_sd_block_open_unconfined()
int brix_sd_block_open_unconfined (const char * path, int sd_flags, mode_t mode)
Definition at line 100 of file sd_block.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_TRUNC, and brix_sd_posix_open_unconfined().
Referenced by block_be_open(), and block_be_stat().
brix_sd_default_driver()
const brix_sd_driver_t * brix_sd_default_driver (void)
Definition at line 60 of file sd_registry.c.
References brix_sd_posix_driver.
Referenced by brix_commit_staged(), brix_vfs_ctx_driver(), brix_vfs_ctx_sd_obj(), brix_vfs_open_via_driver(), brix_vfs_rename_path(), brix_vfs_staged_open(), cms_node_exec_forward(), and stat_query_handle().
brix_sd_driver_at()
const brix_sd_driver_t * brix_sd_driver_at (ngx_uint_t i)
Definition at line 50 of file sd_registry.c.
References sd_drivers.
brix_sd_driver_count()
ngx_uint_t brix_sd_driver_count (void)
Definition at line 44 of file sd_registry.c.
References sd_drivers.
brix_sd_driver_find()
const brix_sd_driver_t * brix_sd_driver_find (const char * name)
Definition at line 69 of file sd_registry.c.
References name, and sd_drivers.
Referenced by brix_sd_instance_create().
brix_sd_instance_create()
brix_sd_instance_t * brix_sd_instance_create (ngx_log_t * log, const char * name, void * driver_conf, int * err_out)
Definition at line 113 of file sd_registry.c.
References brix_sd_driver_find(), brix_sd_instance_pool(), driver, log, name, and ngx_pcalloc().
Referenced by brix_vbr_build_posix(), brix_vbr_wrap_staging_shim(), tier_build_ceph(), tier_build_pblock(), and tier_build_posix().
brix_sd_instance_destroy()
void brix_sd_instance_destroy (brix_sd_instance_t * inst)
Definition at line 154 of file sd_registry.c.
brix_sd_obj_preadv()
static ssize_t brix_sd_obj_preadv (brix_sd_obj_t * obj, const struct iovec * iov, int iovcnt, off_t off) inline static
Definition at line 149 of file sd_registry.h.
Referenced by brix_pgread_read_encode_inplace(), and brix_readv_read_one_run().
brix_sd_posix_borrow_instance()
brix_sd_instance_t * brix_sd_posix_borrow_instance (ngx_pool_t * pool, ngx_log_t * log, int rootfd, const char * root_canon)
Definition at line 161 of file sd_posix.c.
References sd_posix_state_t::borrowed, brix_sd_posix_driver, log, ngx_pcalloc(), sd_posix_state_t::root_canon, and sd_posix_state_t::rootfd.
Referenced by brix_vfs_open_confined_fd(), cache_build_instance(), cache_build_wt_stage(), and cs_root_lazy_posix().
brix_sd_posix_open_unconfined()
int brix_sd_posix_open_unconfined (const char * path, int sd_flags, mode_t mode)
Definition at line 84 of file sd_posix.c.
References open(), and sd_posix_flags().
Referenced by brix_sd_block_open_unconfined(), and posix_be_open().
brix_sd_posix_wrap()
static void brix_sd_posix_wrap (brix_sd_obj_t * obj, ngx_fd_t fd) inline static
Definition at line 121 of file sd_registry.h.
References brix_sd_posix_driver.
Referenced by block_be_stat(), block_commit(), block_fstat(), block_pread(), block_pwrite(), block_sync(), brix_cache_fd_write_all(), brix_cksum_digest_fd(), brix_cksum_u32_fd(), brix_cksum_u64_fd(), brix_cstore_serve_pread(), brix_vfs_effective_obj(), brix_vfs_pread_full(), brix_vfs_pwrite_full(), commit_cross_device(), commit_flush_and_chmod(), cstb_pump_and_commit(), main(), ms_write_cb(), posix_fstat(), posix_pread(), posix_pwrite(), posix_sync(), posix_truncate(), pread_full(), read_try_warm(), s3_copy_bytes(), srq_pread_all(), srq_pwrite_all(), tpc_ms_prepare_output(), webdav_write_full(), xvfs_stage_fd(), zip_deflate_pump(), and zip_pread_full().
Variable Documentation
brix_sd_block_driver
const brix_sd_driver_t brix_sd_block_driver extern
Definition at line 109 of file sd_block.c.
Referenced by block_be_stat(), and block_fstat().
brix_sd_posix_driver
const brix_sd_driver_t brix_sd_posix_driver extern
Definition at line 253 of file sd_posix.c.
Referenced by brix_sd_default_driver(), brix_sd_posix_borrow_instance(), brix_sd_posix_wrap(), brix_vfs_pwrite_full(), sd_block_fsync(), sd_block_pread(), sd_block_preadv(), sd_block_preadv2(), sd_block_pwrite(), and tpc_ms_prepare_output().