nginx-xrootd: src/fs/backend/pblock/sd_pblock_unittest_ident.c File Reference
sd_pblock_unittest_ident.c File Reference
#include "fs/backend/sd.h"
#include "sd_pblock_catalog.h"
#include "sd_pblock_unittest_internal.h"
#include <errno.h>
#include <ftw.h>
#include <limits.h>
#include <pthread.h>
#include <sqlite3.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>
Macros
#define _GNU_SOURCE /* nftw(3) + FTW_PHYS for the on-disk block scan */
Functions
static int cred_write_file (brix_sd_instance_t *inst, const char *path, mode_t mode, const brix_sd_cred_t *who)
static void test_ident_ownership (brix_sd_instance_t *inst)
static void test_ident_vo_dir (brix_sd_instance_t *inst)
static void test_ident_traverse (brix_sd_instance_t *inst)
static void test_ident_setattr (brix_sd_instance_t *inst)
static void test_ident_xattr_sticky (brix_sd_instance_t *inst)
void test_identity (void)
Variables
static const brix_sd_cred_t CRED_ALICE
static const brix_sd_cred_t CRED_BOB
static const brix_sd_cred_t CRED_CAROL
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE /* nftw(3) + FTW_PHYS for the on-disk block scan */
Definition at line 8 of file sd_pblock_unittest_ident.c.
Function Documentation
cred_write_file()
static int cred_write_file (brix_sd_instance_t * inst, const char * path, mode_t mode, const brix_sd_cred_t * who) static
Definition at line 42 of file sd_pblock_unittest_ident.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_READ, BRIX_SD_O_WRITE, D, and pb_close().
Referenced by test_ident_ownership(), test_ident_setattr(), and test_ident_traverse().
test_ident_ownership()
static void test_ident_ownership (brix_sd_instance_t * inst) static
Definition at line 64 of file sd_pblock_unittest_ident.c.
References BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, CRED_ALICE, CRED_BOB, CRED_CAROL, cred_write_file(), D, brix_sd_stat_t::gid, pb_close(), PBLOCK_ID_BASE, and brix_sd_stat_t::uid.
Referenced by test_identity().
test_ident_setattr()
static void test_ident_setattr (brix_sd_instance_t * inst) static
Definition at line 225 of file sd_pblock_unittest_ident.c.
References CHECK, CRED_ALICE, CRED_BOB, cred_write_file(), D, brix_sd_stat_t::gid, brix_sd_setattr_t::gid, brix_sd_setattr_t::mode, brix_sd_setattr_t::set_mode, brix_sd_setattr_t::set_owner, brix_sd_stat_t::uid, and brix_sd_setattr_t::uid.
Referenced by test_identity().
test_ident_traverse()
static void test_ident_traverse (brix_sd_instance_t * inst) static
Definition at line 181 of file sd_pblock_unittest_ident.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, CRED_ALICE, CRED_BOB, CRED_CAROL, cred_write_file(), D, and pb_close().
Referenced by test_identity().
test_ident_vo_dir()
static void test_ident_vo_dir (brix_sd_instance_t * inst) static
Definition at line 132 of file sd_pblock_unittest_ident.c.
References CHECK, CRED_ALICE, CRED_BOB, CRED_CAROL, D, PBLOCK_ID_BASE, and brix_sd_stat_t::uid.
Referenced by test_identity().
test_ident_xattr_sticky()
static void test_ident_xattr_sticky (brix_sd_instance_t * inst) static
Definition at line 278 of file sd_pblock_unittest_ident.c.
References BRIX_SD_O_WRITE, CHECK, CRED_ALICE, CRED_BOB, CRED_CAROL, and D.
Referenced by test_identity().
test_identity()
void test_identity (void)
Definition at line 341 of file sd_pblock_unittest_ident.c.
References BRIX_SD_CRED_IDENTITY, CHECK, D, open_block_export(), test_ident_ownership(), test_ident_setattr(), test_ident_traverse(), test_ident_vo_dir(), and test_ident_xattr_sticky().
Referenced by main().
Variable Documentation
CRED_ALICE
const brix_sd_cred_t CRED_ALICE static
Initial value:
= { .principal = "alice",
                                           .vos = "atlas" }
Definition at line 32 of file sd_pblock_unittest_ident.c.
Referenced by test_ident_ownership(), test_ident_setattr(), test_ident_traverse(), test_ident_vo_dir(), and test_ident_xattr_sticky().
CRED_BOB
const brix_sd_cred_t CRED_BOB static
Initial value:
= { .principal = "bob",
                                           .vos = "cms" }
Definition at line 34 of file sd_pblock_unittest_ident.c.
Referenced by test_ident_ownership(), test_ident_setattr(), test_ident_traverse(), test_ident_vo_dir(), and test_ident_xattr_sticky().
CRED_CAROL
const brix_sd_cred_t CRED_CAROL static
Initial value:
= { .principal = "carol",
                                           .vos = "atlas" }
Definition at line 36 of file sd_pblock_unittest_ident.c.
Referenced by test_ident_ownership(), test_ident_traverse(), test_ident_vo_dir(), and test_ident_xattr_sticky().