nginx-xrootd: src/fs/backend/stage/sd_stage_write.c File Reference
sd_stage_write.c File Reference
#include "sd_stage.h"
#include "sd_stage_internal.h"
#include "fs/xfer/stage_engine.h"
#include <errno.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct sd_stage_staged_state
struct sd_stage_wb_state
Functions
static void sd_stage_record_cred (brix_stage_cred_t *dst, const brix_sd_cred_t *cred)
brix_sd_obj_t * sd_stage_open_writeback (brix_sd_instance_t *inst, sd_stage_inst_state *is, const char *path, int sd_flags, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
static ngx_int_t sd_stage_wb_flush (sd_stage_wb_state *wb)
ssize_t sd_stage_wb_pwrite (brix_sd_obj_t *obj, const void *buf, size_t len, off_t off)
ssize_t sd_stage_wb_pread (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
ngx_int_t sd_stage_wb_ftruncate (brix_sd_obj_t *obj, off_t length)
ngx_int_t sd_stage_wb_fstat (brix_sd_obj_t *obj, brix_sd_stat_t *out)
ngx_int_t sd_stage_wb_fsync (brix_sd_obj_t *obj)
ngx_int_t sd_stage_wb_close (brix_sd_obj_t *obj)
static brix_sd_staged_t * sd_stage_staged_open_inner (brix_sd_instance_t *inst, sd_stage_inst_state *is, const char *final_path, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
brix_sd_staged_t * sd_stage_staged_open (brix_sd_instance_t *inst, const char *final_path, mode_t mode, int *err_out)
brix_sd_staged_t * sd_stage_staged_open_cred (brix_sd_instance_t *inst, const char *final_path, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
ssize_t sd_stage_staged_write (brix_sd_staged_t *st, const void *buf, size_t len, off_t off)
ngx_int_t sd_stage_staged_commit (brix_sd_staged_t *st, int noreplace)
void sd_stage_staged_abort (brix_sd_staged_t *st)
Function Documentation
sd_stage_open_writeback()
brix_sd_obj_t * sd_stage_open_writeback (brix_sd_instance_t * inst, sd_stage_inst_state * is, const char * path, int sd_flags, mode_t mode, const brix_sd_cred_t * cred, int * err_out)
Definition at line 109 of file sd_stage_write.c.
References brix_sd_stage_driver, sd_stage_wb_state::cred, sd_stage_wb_state::dirty, sd_stage_wb_state::high_water, sd_stage_wb_state::is, sd_stage_wb_state::key, sd_stage_record_cred(), sd_stage_inst_state::store, and sd_stage_wb_state::store_obj.
Referenced by sd_stage_open(), and sd_stage_open_cred().
sd_stage_record_cred()
static void sd_stage_record_cred (brix_stage_cred_t * dst, const brix_sd_cred_t * cred) static
Definition at line 78 of file sd_stage_write.c.
References brix_sd_cred_t::cred_dir, brix_stage_cred_t::deny, brix_stage_cred_t::dir, brix_sd_cred_t::fallback_deny, brix_sd_cred_t::key, brix_stage_cred_t::key, brix_sd_cred_t::principal, and brix_stage_cred_t::principal.
Referenced by sd_stage_open_writeback(), and sd_stage_staged_open_inner().
sd_stage_staged_abort()
void sd_stage_staged_abort (brix_sd_staged_t * st)
Definition at line 421 of file sd_stage_write.c.
References sd_stage_staged_state::inner, sd_stage_staged_state::is, and sd_stage_inst_state::store.
sd_stage_staged_commit()
ngx_int_t sd_stage_staged_commit (brix_sd_staged_t * st, int noreplace)
Definition at line 355 of file sd_stage_write.c.
References brix_stage_opts_t::async, BRIX_STAGE_FLUSH, brix_stage_run_inline_cred(), brix_stage_submit(), BRIX_WT_MODE_ASYNC, sd_stage_staged_state::cred, brix_stage_opts_t::cred, brix_stage_opts_t::export_root, brix_stage_policy_t::flush_mode, sd_stage_staged_state::inner, sd_stage_staged_state::is, brix_stage_cred_t::key, sd_stage_staged_state::key, sd_stage_inst_state::policy, sd_stage_inst_state::root_canon, sd_stage_inst_state::source, and sd_stage_inst_state::store.
sd_stage_staged_open()
brix_sd_staged_t * sd_stage_staged_open (brix_sd_instance_t * inst, const char * final_path, mode_t mode, int * err_out)
Definition at line 313 of file sd_stage_write.c.
References sd_stage_staged_open_inner().
sd_stage_staged_open_cred()
brix_sd_staged_t * sd_stage_staged_open_cred (brix_sd_instance_t * inst, const char * final_path, mode_t mode, const brix_sd_cred_t * cred, int * err_out)
Definition at line 332 of file sd_stage_write.c.
References sd_stage_staged_open_inner().
sd_stage_staged_open_inner()
static brix_sd_staged_t * sd_stage_staged_open_inner (brix_sd_instance_t * inst, sd_stage_inst_state * is, const char * final_path, mode_t mode, const brix_sd_cred_t * cred, int * err_out) static
Definition at line 271 of file sd_stage_write.c.
References sd_stage_staged_state::cred, sd_stage_staged_state::inner, sd_stage_staged_state::is, sd_stage_staged_state::key, sd_stage_record_cred(), and sd_stage_inst_state::store.
Referenced by sd_stage_staged_open(), and sd_stage_staged_open_cred().
sd_stage_staged_write()
ssize_t sd_stage_staged_write (brix_sd_staged_t * st, const void * buf, size_t len, off_t off)
Definition at line 340 of file sd_stage_write.c.
References sd_stage_staged_state::inner.
sd_stage_wb_close()
ngx_int_t sd_stage_wb_close (brix_sd_obj_t * obj)
Definition at line 242 of file sd_stage_write.c.
References sd_stage_wb_state::dirty, sd_stage_wb_flush(), and sd_stage_wb_state::store_obj.
sd_stage_wb_flush()
static ngx_int_t sd_stage_wb_flush (sd_stage_wb_state * wb) static
Definition at line 166 of file sd_stage_write.c.
References BRIX_STAGE_FLUSH, brix_stage_run_inline_cred(), sd_stage_wb_state::cred, sd_stage_wb_state::dirty, sd_stage_wb_state::is, brix_stage_cred_t::key, sd_stage_wb_state::key, sd_stage_inst_state::source, sd_stage_inst_state::store, and sd_stage_wb_state::store_obj.
Referenced by sd_stage_wb_close(), and sd_stage_wb_fsync().
sd_stage_wb_fstat()
ngx_int_t sd_stage_wb_fstat (brix_sd_obj_t * obj, brix_sd_stat_t * out)
Definition at line 228 of file sd_stage_write.c.
References sd_stage_wb_state::store_obj.
sd_stage_wb_fsync()
ngx_int_t sd_stage_wb_fsync (brix_sd_obj_t * obj)
Definition at line 236 of file sd_stage_write.c.
References sd_stage_wb_flush().
sd_stage_wb_ftruncate()
ngx_int_t sd_stage_wb_ftruncate (brix_sd_obj_t * obj, off_t length)
Definition at line 210 of file sd_stage_write.c.
References sd_stage_wb_state::dirty, sd_stage_wb_state::high_water, and sd_stage_wb_state::store_obj.
sd_stage_wb_pread()
ssize_t sd_stage_wb_pread (brix_sd_obj_t * obj, void * buf, size_t len, off_t off)
Definition at line 202 of file sd_stage_write.c.
References sd_stage_wb_state::store_obj.
sd_stage_wb_pwrite()
ssize_t sd_stage_wb_pwrite (brix_sd_obj_t * obj, const void * buf, size_t len, off_t off)
Definition at line 187 of file sd_stage_write.c.
References sd_stage_wb_state::dirty, sd_stage_wb_state::high_water, and sd_stage_wb_state::store_obj.