nginx-xrootd: src/fs/backend/frm/sd_frm_exec.c File Reference
sd_frm_exec.c File Reference
#include "sd_frm_mss.h"
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <spawn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct exec_ctx_t
Functions
static int exec_online_path (const exec_ctx_t *c, const char *key, char *out, size_t cap)
static int exec_run (const exec_ctx_t *c, const char *verb, const char *key, const char *online)
static int exec_residency (void *mss, const char *key, off_t *size_out, time_t *mtime_out)
static int exec_recall_begin (void *mss, const char *key)
static int exec_recall_poll (void *mss, const char *key)
static int exec_migrate (void *mss, const char *key)
static int exec_purge (void *mss, const char *key)
static int exec_open_online (void *mss, const char *key)
static int exec_create_online (void *mss, const char *key, mode_t mode)
static void exec_destroy (void *mss)
void * brix_mss_exec_create (const char *location, const char *stagecmd, ngx_log_t *log)
Variables
const brix_mss_adapter_t brix_mss_exec_adapter
Function Documentation
brix_mss_exec_create()
void * brix_mss_exec_create (const char * location, const char * stagecmd, ngx_log_t * log)
Definition at line 201 of file sd_frm_exec.c.
References exec_ctx_t::base, log, exec_ctx_t::log, and exec_ctx_t::stagecmd.
Referenced by frm_select_exec_adapter().
exec_create_online()
static int exec_create_online (void * mss, const char * key, mode_t mode) static
Definition at line 165 of file sd_frm_exec.c.
References c, exec_online_path(), frm_mkparents(), key, open(), and PATH_MAX.
exec_destroy()
static void exec_destroy (void * mss) static
Definition at line 180 of file sd_frm_exec.c.
exec_migrate()
static int exec_migrate (void * mss, const char * key) static
Definition at line 128 of file sd_frm_exec.c.
References c, exec_online_path(), exec_run(), key, and PATH_MAX.
exec_online_path()
static int exec_online_path (const exec_ctx_t * c, const char * key, char * out, size_t cap) static
Definition at line 40 of file sd_frm_exec.c.
References c, and key.
Referenced by exec_create_online(), exec_migrate(), exec_open_online(), exec_purge(), exec_recall_begin(), exec_recall_poll(), and exec_residency().
exec_open_online()
static int exec_open_online (void * mss, const char * key) static
Definition at line 152 of file sd_frm_exec.c.
References c, exec_online_path(), key, open(), and PATH_MAX.
exec_purge()
static int exec_purge (void * mss, const char * key) static
Definition at line 140 of file sd_frm_exec.c.
References c, exec_online_path(), key, and PATH_MAX.
exec_recall_begin()
static int exec_recall_begin (void * mss, const char * key) static
Definition at line 100 of file sd_frm_exec.c.
References access(), c, exec_online_path(), exec_run(), frm_mkparents(), key, and PATH_MAX.
exec_recall_poll()
static int exec_recall_poll (void * mss, const char * key) static
Definition at line 116 of file sd_frm_exec.c.
References access(), c, exec_online_path(), key, and PATH_MAX.
exec_residency()
static int exec_residency (void * mss, const char * key, off_t * size_out, time_t * mtime_out) static
Definition at line 76 of file sd_frm_exec.c.
References BRIX_RESIDENCY_ABSENT, BRIX_RESIDENCY_OFFLINE, BRIX_RESIDENCY_ONLINE, c, exec_online_path(), exec_run(), key, PATH_MAX, and stat().
exec_run()
static int exec_run (const exec_ctx_t * c, const char * verb, const char * key, const char * online) static
Definition at line 51 of file sd_frm_exec.c.
References c, environ, and key.
Referenced by exec_migrate(), exec_recall_begin(), and exec_residency().
Variable Documentation
brix_mss_exec_adapter
const brix_mss_adapter_t brix_mss_exec_adapter
Initial value:
= {
    .name          = "exec",
    .residency     = exec_residency,
    .recall_begin  = exec_recall_begin,
    .recall_poll   = exec_recall_poll,
    .migrate       = exec_migrate,
    .purge         = exec_purge,
    .open_online   = exec_open_online,
    .create_online = exec_create_online,
    .destroy       = exec_destroy,
}
Definition at line 185 of file sd_frm_exec.c.
Referenced by frm_select_exec_adapter().