nginx-xrootd: src/fs/backend/xroot/sd_xroot_io.c File Reference
sd_xroot_io.c File Reference
#include "sd_xroot_internal.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
Functions
static brix_sd_obj_t * sd_xroot_open_common (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
brix_sd_obj_t * sd_xroot_open (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, int *err_out)
brix_sd_obj_t * sd_xroot_open_cred (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
ngx_int_t sd_xroot_close (brix_sd_obj_t *obj)
ssize_t sd_xroot_pread (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
ssize_t sd_xroot_pwrite (brix_sd_obj_t *obj, const void *buf, size_t len, off_t off)
ngx_int_t sd_xroot_ftruncate (brix_sd_obj_t *obj, off_t len)
ngx_int_t sd_xroot_fsync (brix_sd_obj_t *obj)
ngx_int_t sd_xroot_fstat (brix_sd_obj_t *obj, brix_sd_stat_t *out)
ngx_int_t sd_xroot_stat (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out)
ngx_int_t sd_xroot_stat_cred (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out, const brix_sd_cred_t *cred)
ssize_t sd_xroot_preadv (brix_sd_obj_t *obj, const struct iovec *iov, int iovcnt, off_t off)
Function Documentation
sd_xroot_close()
ngx_int_t sd_xroot_close (brix_sd_obj_t * obj)
Definition at line 124 of file sd_xroot_io.c.
References sd_xroot_obj_teardown().
sd_xroot_fstat()
ngx_int_t sd_xroot_fstat (brix_sd_obj_t * obj, brix_sd_stat_t * out)
Definition at line 221 of file sd_xroot_io.c.
sd_xroot_fsync()
ngx_int_t sd_xroot_fsync (brix_sd_obj_t * obj)
Definition at line 206 of file sd_xroot_io.c.
References brix_cache_origin_sync(), sd_xroot_obj_state::fhandle, sd_xroot_obj_state::is_write, sd_xroot_obj_state::oc, and sd_xroot_obj_state::t.
sd_xroot_ftruncate()
ngx_int_t sd_xroot_ftruncate (brix_sd_obj_t * obj, off_t len)
Definition at line 187 of file sd_xroot_io.c.
References brix_cache_origin_truncate(), sd_xroot_obj_state::fhandle, sd_xroot_obj_state::is_write, sd_xroot_obj_state::oc, and sd_xroot_obj_state::t.
sd_xroot_open()
brix_sd_obj_t * sd_xroot_open (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, int * err_out)
Definition at line 102 of file sd_xroot_io.c.
References sd_xroot_open_common().
sd_xroot_open_common()
static brix_sd_obj_t * sd_xroot_open_common (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, const brix_sd_cred_t * cred, int * err_out) static
Definition at line 45 of file sd_xroot_io.c.
References brix_sd_cred_t::bearer, BRIX_SD_O_APPEND, BRIX_SD_O_CREATE, BRIX_SD_O_TRUNC, BRIX_SD_O_WRITE, sd_xroot_inst_state::conf, sd_xroot_origin_open_req_t::conf, brix_sd_cred_t::fallback_deny, brix_sd_cred_t::mode, sd_xroot_obj_teardown(), sd_xroot_origin_open(), and brix_sd_cred_t::x509_proxy.
Referenced by sd_xroot_open(), and sd_xroot_open_cred().
sd_xroot_open_cred()
brix_sd_obj_t * sd_xroot_open_cred (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, const brix_sd_cred_t * cred, int * err_out)
Definition at line 117 of file sd_xroot_io.c.
References sd_xroot_open_common().
sd_xroot_pread()
ssize_t sd_xroot_pread (brix_sd_obj_t * obj, void * buf, size_t len, off_t off)
Definition at line 134 of file sd_xroot_io.c.
References brix_cache_origin_read_chunk(), brix_cache_sink_t::fd, sd_xroot_obj_state::fhandle, brix_cache_read_range_t::got, brix_cache_sink_t::mem, brix_cache_sink_t::mem_cap, sd_xroot_obj_state::oc, brix_cache_read_range_t::read_off, sd_xroot_obj_state::t, and brix_cache_read_range_t::want.
Referenced by sd_xroot_preadv().
sd_xroot_preadv()
ssize_t sd_xroot_preadv (brix_sd_obj_t * obj, const struct iovec * iov, int iovcnt, off_t off)
Definition at line 297 of file sd_xroot_io.c.
References sd_xroot_pread().
sd_xroot_pwrite()
ssize_t sd_xroot_pwrite (brix_sd_obj_t * obj, const void * buf, size_t len, off_t off)
Definition at line 165 of file sd_xroot_io.c.
References brix_cache_origin_write_chunk(), sd_xroot_obj_state::fhandle, sd_xroot_obj_state::is_write, sd_xroot_obj_state::oc, and sd_xroot_obj_state::t.
sd_xroot_stat()
ngx_int_t sd_xroot_stat (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out)
Definition at line 228 of file sd_xroot_io.c.
References sd_xroot_inst_state::conf, sd_xroot_origin_open_req_t::conf, brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, sd_xroot_obj_teardown(), sd_xroot_origin_open(), and brix_sd_stat_t::size.
sd_xroot_stat_cred()
ngx_int_t sd_xroot_stat_cred (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out, const brix_sd_cred_t * cred)
Definition at line 267 of file sd_xroot_io.c.
References sd_xroot_inst_state::conf, sd_xroot_origin_open_req_t::conf, brix_sd_stat_t::is_reg, brix_sd_cred_t::mode, brix_sd_stat_t::mode, sd_xroot_obj_teardown(), sd_xroot_origin_open(), and brix_sd_stat_t::size.