nginx-xrootd: src/fs/backend/cache/sd_cache_fill_internal.h File Reference
sd_cache_fill_internal.h File Reference
#include "sd_cache_internal.h"
#include <time.h>
Data Structures
struct sd_cache_fill_state_t
Macros
#define SD_CACHE_CHUNK (1u << 20)
Functions
ngx_int_t cache_fill_verify (sd_cache_inst_state *st, const char *key, sd_cache_fill_state_t *fs)
Macro Definition Documentation
SD_CACHE_CHUNK
#define SD_CACHE_CHUNK (1u << 20)
Definition at line 22 of file sd_cache_fill_internal.h.
Function Documentation
cache_fill_verify()
ngx_int_t cache_fill_verify (sd_cache_inst_state * st, const char * key, sd_cache_fill_state_t * fs)
Definition at line 284 of file sd_cache_fill_verify.c.
References BRIX_CACHE_VERIFY_BESTEFFORT, brix_cache_verify_cvmfs_cas(), BRIX_CACHE_VERIFY_CVMFS_CAS, BRIX_CACHE_VERIFY_ERROR, BRIX_CACHE_VERIFY_MISMATCH, BRIX_CACHE_VERIFY_OFF, BRIX_CACHE_VERIFY_REQUIRE, BRIX_CACHE_VERIFY_VERIFIED, brix_cstore_fill_abort(), cache_fill_verify_origin(), cache_fill_verify_reject(), sd_cache_fill_state_t::cks_alg, sd_cache_fill_state_t::cks_hex, brix_cache_policy_t::cvmfs_master_pub, key, sd_cache_inst_state::log, sd_cache_inst_state::policy, sd_cache_verify_manifest(), sd_cache_fill_state_t::staged, sd_cache_fill_state_t::verified, and brix_cache_policy_t::verify.
Referenced by sd_cache_fill_attempt().