nginx-xrootd: src/fs/backend/http/sd_http_read.c File Reference
sd_http_read.c File Reference
#include "sd_http_internal.h"
#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
Data Structures
struct sd_http_obj_state
struct sd_http_open_result_t
struct sd_http_open_req_t
Macros
#define SD_HTTP_PREAD_MAX (8LL * 1024 * 1024)
Functions
static int sd_http_head_size (sd_http_inst_state *is, const char *key, const char *auth_hdr, const char *cert_pem, int64_t *size_out)
int sd_http_cred_gate (sd_http_inst_state *is, const brix_sd_cred_t *cred)
const char * sd_http_resolve_open_cred (sd_http_inst_state *is, const brix_sd_cred_t *cred, char *open_auth, size_t auth_cap)
static brix_sd_obj_t * sd_http_build_obj (brix_sd_instance_t *inst, const char *path, const sd_http_open_result_t *res, int *err_out)
static brix_sd_obj_t * sd_http_open_common (brix_sd_instance_t *inst, const sd_http_open_req_t *req, int *err_out)
brix_sd_obj_t * sd_http_open (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, int *err_out)
brix_sd_obj_t * sd_http_open_cred (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
ngx_int_t sd_http_close (brix_sd_obj_t *obj)
ssize_t sd_http_pread (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
ngx_int_t sd_http_fstat (brix_sd_obj_t *obj, brix_sd_stat_t *out)
static void sd_http_stat_fill (brix_sd_stat_t *out, int64_t size)
ngx_int_t sd_http_stat (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out)
ngx_int_t sd_http_stat_cred (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out, const brix_sd_cred_t *cred)
Macro Definition Documentation
SD_HTTP_PREAD_MAX
#define SD_HTTP_PREAD_MAX (8LL * 1024 * 1024)
Definition at line 34 of file sd_http_read.c.
Function Documentation
sd_http_build_obj()
static brix_sd_obj_t * sd_http_build_obj (brix_sd_instance_t * inst, const char * path, const sd_http_open_result_t * res, int * err_out) static
Definition at line 176 of file sd_http_read.c.
References sd_http_obj_state::auth_hdr, sd_http_obj_state::cert_pem, sd_http_obj_state::key, sd_http_open_result_t::open_auth, sd_http_open_result_t::open_cert, and sd_http_open_result_t::size.
Referenced by sd_http_open_common().
sd_http_close()
ngx_int_t sd_http_close (brix_sd_obj_t * obj)
Definition at line 305 of file sd_http_read.c.
sd_http_cred_gate()
int sd_http_cred_gate (sd_http_inst_state * is, const brix_sd_cred_t * cred)
Definition at line 108 of file sd_http_read.c.
References brix_sd_cred_t::bearer, brix_sd_cred_t::fallback_deny, brix_s3_transport_t::request_cred, sd_http_inst_state::transport, and brix_sd_cred_t::x509_proxy.
Referenced by sd_http_open_common(), sd_http_staged_open_common(), and sd_http_stat_cred().
sd_http_fstat()
ngx_int_t sd_http_fstat (brix_sd_obj_t * obj, brix_sd_stat_t * out)
Definition at line 383 of file sd_http_read.c.
sd_http_head_size()
static int sd_http_head_size (sd_http_inst_state * is, const char * key, const char * auth_hdr, const char * cert_pem, int64_t * size_out) static
Definition at line 61 of file sd_http_read.c.
References g_sd_http_force_primary, key, brix_s3_transport_t::resp_free, brix_s3_transport_t::resp_header, sd_http_request_fo(), brix_s3_resp_t::status, and sd_http_inst_state::transport.
Referenced by sd_http_open_common(), sd_http_stat(), and sd_http_stat_cred().
sd_http_open()
brix_sd_obj_t * sd_http_open (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, int * err_out)
Definition at line 279 of file sd_http_read.c.
References sd_http_open_common().
sd_http_open_common()
static brix_sd_obj_t * sd_http_open_common (brix_sd_instance_t * inst, const sd_http_open_req_t * req, int * err_out) static
Definition at line 233 of file sd_http_read.c.
References sd_http_inst_state::auth_hdr, BRIX_SD_O_APPEND, BRIX_SD_O_CREATE, BRIX_SD_O_TRUNC, BRIX_SD_O_WRITE, sd_http_open_req_t::cred, sd_http_open_req_t::mode, sd_http_open_req_t::path, sd_http_open_req_t::sd_flags, SD_HTTP_AUTH_MAX, sd_http_build_obj(), sd_http_cred_gate(), sd_http_head_size(), and sd_http_resolve_open_cred().
Referenced by sd_http_open(), and sd_http_open_cred().
sd_http_open_cred()
brix_sd_obj_t * sd_http_open_cred (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, const brix_sd_cred_t * cred, int * err_out)
Definition at line 296 of file sd_http_read.c.
References sd_http_open_common().
sd_http_pread()
ssize_t sd_http_pread (brix_sd_obj_t * obj, void * buf, size_t len, off_t off)
Definition at line 315 of file sd_http_read.c.
References sd_http_inst_state::auth_hdr, sd_http_obj_state::auth_hdr, sd_http_obj_state::cert_pem, g_sd_http_force_primary, sd_http_obj_state::key, brix_s3_transport_t::resp_body, brix_s3_transport_t::resp_free, SD_HTTP_AUTH_MAX, SD_HTTP_PREAD_MAX, sd_http_request_fo(), brix_s3_resp_t::status, and sd_http_inst_state::transport.
sd_http_resolve_open_cred()
const char * sd_http_resolve_open_cred (sd_http_inst_state * is, const brix_sd_cred_t * cred, char * open_auth, size_t auth_cap)
Definition at line 140 of file sd_http_read.c.
References brix_sd_cred_t::bearer, brix_s3_transport_t::request_cred, sd_http_inst_state::transport, and brix_sd_cred_t::x509_proxy.
Referenced by sd_http_open_common(), and sd_http_stat_cred().
sd_http_stat()
ngx_int_t sd_http_stat (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out)
Definition at line 407 of file sd_http_read.c.
References sd_http_inst_state::auth_hdr, sd_http_head_size(), and sd_http_stat_fill().
sd_http_stat_cred()
ngx_int_t sd_http_stat_cred (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out, const brix_sd_cred_t * cred)
Definition at line 446 of file sd_http_read.c.
References sd_http_inst_state::auth_hdr, SD_HTTP_AUTH_MAX, sd_http_cred_gate(), sd_http_head_size(), sd_http_resolve_open_cred(), and sd_http_stat_fill().
sd_http_stat_fill()
static void sd_http_stat_fill (brix_sd_stat_t * out, int64_t size) static
Definition at line 398 of file sd_http_read.c.
References brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, and brix_sd_stat_t::size.
Referenced by sd_http_stat(), and sd_http_stat_cred().