nginx-xrootd: src/fs/backend/xroot/sd_xroot.c File Reference
sd_xroot.c File Reference
#include "sd_xroot.h"
#include "sd_xroot_internal.h"
#include "fs/cache/cache_internal.h"
#include "auth/crypto/pki_build.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <openssl/x509.h>
#include <openssl/x509_vfy.h>
Data Structures
struct sd_xroot_obj_state
struct sd_xroot_staged_state
Functions
int sd_xroot_errno (const brix_cache_fill_t *t)
static void sd_xroot_obj_teardown (sd_xroot_obj_state *st)
static sd_xroot_obj_state * sd_xroot_origin_open (ngx_stream_brix_srv_conf_t *conf, const char *path, int want_write, mode_t mode, off_t *size_out, int *err_out)
static brix_sd_obj_t * sd_xroot_open (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, int *err_out)
static ngx_int_t sd_xroot_close (brix_sd_obj_t *obj)
static ssize_t sd_xroot_pread (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
static ssize_t sd_xroot_pwrite (brix_sd_obj_t *obj, const void *buf, size_t len, off_t off)
static ngx_int_t sd_xroot_ftruncate (brix_sd_obj_t *obj, off_t len)
static ngx_int_t sd_xroot_fsync (brix_sd_obj_t *obj)
static ngx_int_t sd_xroot_fstat (brix_sd_obj_t *obj, brix_sd_stat_t *out)
static ngx_int_t sd_xroot_stat (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out)
static void sd_xroot_staged_teardown (brix_sd_staged_t *handle)
static brix_sd_staged_t * sd_xroot_staged_open (brix_sd_instance_t *inst, const char *final_path, mode_t mode, int *err_out)
static ssize_t sd_xroot_staged_write (brix_sd_staged_t *handle, const void *buf, size_t len, off_t off)
static ngx_int_t sd_xroot_staged_commit (brix_sd_staged_t *handle, int noreplace)
static void sd_xroot_staged_abort (brix_sd_staged_t *handle)
static ssize_t sd_xroot_preadv (brix_sd_obj_t *obj, const struct iovec *iov, int iovcnt, off_t off)
void brix_sd_xroot_query_checksum (brix_sd_obj_t *obj, char *alg, size_t algsz, char *hex, size_t hexsz)
brix_sd_instance_t * brix_sd_xroot_create (void *conf, ngx_log_t *log)
brix_sd_instance_t * brix_sd_xroot_create_origin (const char *host, int port, int tls, int af_policy, const char *bearer, const char *x509_proxy, const char *ca_dir, const char *sss_keytab, ngx_log_t *log)
void brix_sd_xroot_destroy (brix_sd_instance_t *inst)
Variables
static const brix_sd_driver_t brix_sd_xroot_driver
Function Documentation
brix_sd_xroot_create()
brix_sd_instance_t * brix_sd_xroot_create (void * conf, ngx_log_t * log)
Definition at line 465 of file sd_xroot.c.
References brix_sd_xroot_driver, sd_xroot_inst_state::conf, log, and sd_xroot_inst_state::synth.
brix_sd_xroot_create_origin()
brix_sd_instance_t * brix_sd_xroot_create_origin (const char * host, int port, int tls, int af_policy, const char * bearer, const char * x509_proxy, const char * ca_dir, const char * sss_keytab, ngx_log_t * log)
Definition at line 492 of file sd_xroot.c.
References sd_xroot_inst_state::bearer, brix_build_ca_store(), BRIX_CRL_MODE_TRY, brix_sd_xroot_driver, BRIX_SP_MODE_OFF, sd_xroot_inst_state::ca_dir, ngx_stream_brix_srv_conf_t::cache_origin_bearer, ngx_stream_brix_srv_conf_t::cache_origin_ca_dir, ngx_stream_brix_srv_conf_t::cache_origin_family, ngx_stream_brix_srv_conf_t::cache_origin_host, ngx_stream_brix_srv_conf_t::cache_origin_port, ngx_stream_brix_srv_conf_t::cache_origin_sss_keytab, ngx_stream_brix_srv_conf_t::cache_origin_tls, ngx_stream_brix_srv_conf_t::cache_origin_x509_proxy, sd_xroot_inst_state::conf, ngx_stream_brix_srv_conf_t::gsi_store, sd_xroot_inst_state::host, log, sd_xroot_inst_state::sss_keytab, stat(), sd_xroot_inst_state::synth, tls, and sd_xroot_inst_state::x509_proxy.
Referenced by brix_cache_build_wt_origin(), brix_tier_build(), and brix_vfs_backend_build_source().
brix_sd_xroot_destroy()
void brix_sd_xroot_destroy (brix_sd_instance_t * inst)
Definition at line 579 of file sd_xroot.c.
References ngx_stream_brix_srv_conf_t::gsi_store, and sd_xroot_inst_state::synth.
Referenced by brix_cache_storage_cleanup(), and cache_build_wt_stage().
brix_sd_xroot_query_checksum()
void brix_sd_xroot_query_checksum (brix_sd_obj_t * obj, char * alg, size_t algsz, char * hex, size_t hexsz)
Definition at line 449 of file sd_xroot.c.
References brix_cache_origin_query_checksum(), hex(), sd_xroot_obj_state::oc, and sd_xroot_obj_state::t.
Referenced by brix_cache_fill_from_source().
sd_xroot_close()
static ngx_int_t sd_xroot_close (brix_sd_obj_t * obj) static
Definition at line 151 of file sd_xroot.c.
References sd_xroot_obj_teardown().
sd_xroot_errno()
int sd_xroot_errno (const brix_cache_fill_t * t)
Definition at line 36 of file sd_xroot.c.
References kXR_isDirectory, kXR_NotAuthorized, kXR_NotFound, and brix_cache_fill_t::xrd_error.
Referenced by sd_xroot_origin_open(), sd_xroot_server_copy(), sd_xroot_session(), and sd_xroot_staged_open().
sd_xroot_fstat()
static ngx_int_t sd_xroot_fstat (brix_sd_obj_t * obj, brix_sd_stat_t * out) static
Definition at line 244 of file sd_xroot.c.
sd_xroot_fsync()
static ngx_int_t sd_xroot_fsync (brix_sd_obj_t * obj) static
Definition at line 229 of file sd_xroot.c.
References brix_cache_origin_sync(), sd_xroot_obj_state::fhandle, sd_xroot_obj_state::is_write, sd_xroot_obj_state::oc, and sd_xroot_obj_state::t.
sd_xroot_ftruncate()
static ngx_int_t sd_xroot_ftruncate (brix_sd_obj_t * obj, off_t len) static
Definition at line 210 of file sd_xroot.c.
References brix_cache_origin_truncate(), sd_xroot_obj_state::fhandle, sd_xroot_obj_state::is_write, sd_xroot_obj_state::oc, and sd_xroot_obj_state::t.
sd_xroot_obj_teardown()
static void sd_xroot_obj_teardown (sd_xroot_obj_state * st) static
Definition at line 47 of file sd_xroot.c.
References brix_cache_origin_close(), brix_cache_origin_close_file(), sd_xroot_obj_state::fhandle, sd_xroot_obj_state::file_open, sd_xroot_obj_state::oc, and sd_xroot_obj_state::t.
Referenced by sd_xroot_close(), sd_xroot_open(), sd_xroot_origin_open(), and sd_xroot_stat().
sd_xroot_open()
static brix_sd_obj_t * sd_xroot_open (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, int * err_out) static
Definition at line 116 of file sd_xroot.c.
References BRIX_SD_O_APPEND, BRIX_SD_O_CREATE, BRIX_SD_O_TRUNC, BRIX_SD_O_WRITE, sd_xroot_inst_state::conf, mode, sd_xroot_obj_teardown(), and sd_xroot_origin_open().
sd_xroot_origin_open()
static sd_xroot_obj_state * sd_xroot_origin_open (ngx_stream_brix_srv_conf_t * conf, const char * path, int want_write, mode_t mode, off_t * size_out, int * err_out) static
Definition at line 65 of file sd_xroot.c.
References brix_cache_origin_bootstrap(), brix_cache_origin_connect(), brix_cache_origin_open(), brix_cache_origin_open_write(), brix_cache_fill_t::clean_path, brix_cache_fill_t::conf, brix_cache_origin_conn_t::fd, sd_xroot_obj_state::fhandle, sd_xroot_obj_state::file_open, brix_cache_fill_t::file_size, sd_xroot_obj_state::is_write, mode, sd_xroot_obj_state::oc, sd_xroot_errno(), sd_xroot_obj_teardown(), and sd_xroot_obj_state::t.
Referenced by sd_xroot_open(), and sd_xroot_stat().
sd_xroot_pread()
static ssize_t sd_xroot_pread (brix_sd_obj_t * obj, void * buf, size_t len, off_t off) static
Definition at line 161 of file sd_xroot.c.
References brix_cache_origin_read_chunk(), brix_cache_sink_t::fd, sd_xroot_obj_state::fhandle, brix_cache_sink_t::mem, brix_cache_sink_t::mem_cap, sd_xroot_obj_state::oc, and sd_xroot_obj_state::t.
Referenced by sd_xroot_preadv().
sd_xroot_preadv()
static ssize_t sd_xroot_preadv (brix_sd_obj_t * obj, const struct iovec * iov, int iovcnt, off_t off) static
Definition at line 396 of file sd_xroot.c.
References sd_xroot_pread().
sd_xroot_pwrite()
static ssize_t sd_xroot_pwrite (brix_sd_obj_t * obj, const void * buf, size_t len, off_t off) static
Definition at line 188 of file sd_xroot.c.
References brix_cache_origin_write_chunk(), sd_xroot_obj_state::fhandle, sd_xroot_obj_state::is_write, sd_xroot_obj_state::oc, and sd_xroot_obj_state::t.
sd_xroot_staged_abort()
static void sd_xroot_staged_abort (brix_sd_staged_t * handle) static
Definition at line 386 of file sd_xroot.c.
References sd_xroot_staged_teardown().
sd_xroot_staged_commit()
static ngx_int_t sd_xroot_staged_commit (brix_sd_staged_t * handle, int noreplace) static
Definition at line 372 of file sd_xroot.c.
References brix_cache_origin_sync(), sd_xroot_staged_state::fhandle, sd_xroot_staged_state::oc, sd_xroot_staged_teardown(), and sd_xroot_staged_state::t.
sd_xroot_staged_open()
static brix_sd_staged_t * sd_xroot_staged_open (brix_sd_instance_t * inst, const char * final_path, mode_t mode, int * err_out) static
Definition at line 310 of file sd_xroot.c.
References brix_cache_origin_bootstrap(), brix_cache_origin_close(), brix_cache_origin_connect(), brix_cache_origin_open_write(), brix_cache_fill_t::clean_path, sd_xroot_inst_state::conf, brix_cache_fill_t::conf, brix_cache_origin_conn_t::fd, sd_xroot_staged_state::fhandle, sd_xroot_staged_state::file_open, mode, sd_xroot_staged_state::oc, sd_xroot_errno(), and sd_xroot_staged_state::t.
sd_xroot_staged_teardown()
static void sd_xroot_staged_teardown (brix_sd_staged_t * handle) static
Definition at line 290 of file sd_xroot.c.
References brix_cache_origin_close(), brix_cache_origin_close_file(), sd_xroot_staged_state::fhandle, sd_xroot_staged_state::file_open, sd_xroot_staged_state::oc, and sd_xroot_staged_state::t.
Referenced by sd_xroot_staged_abort(), and sd_xroot_staged_commit().
sd_xroot_staged_write()
static ssize_t sd_xroot_staged_write (brix_sd_staged_t * handle, const void * buf, size_t len, off_t off) static
Definition at line 350 of file sd_xroot.c.
References brix_cache_origin_write_chunk(), sd_xroot_staged_state::fhandle, sd_xroot_staged_state::oc, and sd_xroot_staged_state::t.
sd_xroot_stat()
static ngx_int_t sd_xroot_stat (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out) static
Definition at line 251 of file sd_xroot.c.
References sd_xroot_inst_state::conf, brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, sd_xroot_obj_teardown(), sd_xroot_origin_open(), and brix_sd_stat_t::size.
Variable Documentation
brix_sd_xroot_driver
const brix_sd_driver_t brix_sd_xroot_driver static
Initial value:
= {
    .name      = "xroot",
    .caps      = BRIX_SD_CAP_RANGE_READ | BRIX_SD_CAP_RANDOM_WRITE
                 | BRIX_SD_CAP_TRUNCATE | BRIX_SD_CAP_XATTR
                 | BRIX_SD_CAP_HARD_RENAME | BRIX_SD_CAP_SERVER_COPY,
    .open          = sd_xroot_open,
    .close         = sd_xroot_close,
    .pread         = sd_xroot_pread,
    .preadv        = sd_xroot_preadv,
    .pwrite        = sd_xroot_pwrite,
    .fstat         = sd_xroot_fstat,
    .ftruncate     = sd_xroot_ftruncate,
    .fsync         = sd_xroot_fsync,
    .stat          = sd_xroot_stat,
    .rename        = sd_xroot_rename,
    .unlink        = sd_xroot_unlink,
    .server_copy   = sd_xroot_server_copy,
    .getxattr      = sd_xroot_getxattr,
    .listxattr     = sd_xroot_listxattr,
    .setxattr      = sd_xroot_setxattr,
    .removexattr   = sd_xroot_removexattr,
    .staged_open   = sd_xroot_staged_open,
    .staged_write  = sd_xroot_staged_write,
    .staged_commit = sd_xroot_staged_commit,
    .staged_abort  = sd_xroot_staged_abort,
}
Definition at line 421 of file sd_xroot.c.
Referenced by brix_sd_xroot_create(), and brix_sd_xroot_create_origin().