nginx-xrootd: src/fs/backend/xroot/sd_xroot_internal.h File Reference
sd_xroot_internal.h File Reference
#include "sd_xroot.h"
#include "fs/cache/cache_internal.h"
Data Structures
struct sd_xroot_inst_state
struct sd_xroot_obj_state
struct sd_xroot_origin_open_req_t
Functions
int sd_xroot_errno (const brix_cache_fill_t *t)
void sd_xroot_copy_cred_into_task (brix_cache_fill_t *t, const brix_sd_cred_t *cred)
void sd_xroot_obj_teardown (sd_xroot_obj_state *st)
sd_xroot_obj_state * sd_xroot_origin_open (const sd_xroot_origin_open_req_t *req)
brix_sd_obj_t * sd_xroot_open (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, int *err_out)
brix_sd_obj_t * sd_xroot_open_cred (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
ngx_int_t sd_xroot_close (brix_sd_obj_t *obj)
ssize_t sd_xroot_pread (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
ssize_t sd_xroot_preadv (brix_sd_obj_t *obj, const struct iovec *iov, int iovcnt, off_t off)
ssize_t sd_xroot_pwrite (brix_sd_obj_t *obj, const void *buf, size_t len, off_t off)
ngx_int_t sd_xroot_ftruncate (brix_sd_obj_t *obj, off_t len)
ngx_int_t sd_xroot_fsync (brix_sd_obj_t *obj)
ngx_int_t sd_xroot_fstat (brix_sd_obj_t *obj, brix_sd_stat_t *out)
ngx_int_t sd_xroot_stat (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out)
brix_sd_staged_t * sd_xroot_staged_open (brix_sd_instance_t *inst, const char *final_path, mode_t mode, int *err_out)
brix_sd_staged_t * sd_xroot_staged_open_cred (brix_sd_instance_t *inst, const char *final_path, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
ssize_t sd_xroot_staged_write (brix_sd_staged_t *handle, const void *buf, size_t len, off_t off)
ngx_int_t sd_xroot_staged_commit (brix_sd_staged_t *handle, int noreplace)
void sd_xroot_staged_abort (brix_sd_staged_t *handle)
ssize_t sd_xroot_getxattr (brix_sd_instance_t *inst, const char *path, const char *name, void *buf, size_t cap)
ssize_t sd_xroot_listxattr (brix_sd_instance_t *inst, const char *path, void *buf, size_t cap)
ngx_int_t sd_xroot_setxattr (brix_sd_instance_t *inst, const char *path, const char *name, const void *val, size_t len, int flags)
ngx_int_t sd_xroot_removexattr (brix_sd_instance_t *inst, const char *path, const char *name)
ngx_int_t sd_xroot_rename (brix_sd_instance_t *inst, const char *src, const char *dst, int noreplace)
ngx_int_t sd_xroot_unlink (brix_sd_instance_t *inst, const char *path, int is_dir)
ngx_int_t sd_xroot_server_copy (brix_sd_instance_t *inst, const char *src, const char *dst, off_t *bytes_out)
ngx_int_t sd_xroot_stat_cred (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out, const brix_sd_cred_t *cred)
ngx_int_t sd_xroot_unlink_cred (brix_sd_instance_t *inst, const char *path, int is_dir, const brix_sd_cred_t *cred)
ngx_int_t sd_xroot_rename_cred (brix_sd_instance_t *inst, const char *src, const char *dst, int noreplace, const brix_sd_cred_t *cred)
ngx_int_t sd_xroot_server_copy_cred (brix_sd_instance_t *inst, const char *src, const char *dst, off_t *bytes_out, const brix_sd_cred_t *cred)
ssize_t sd_xroot_getxattr_cred (brix_sd_instance_t *inst, const char *path, const char *name, void *buf, size_t cap, const brix_sd_cred_t *cred)
ssize_t sd_xroot_listxattr_cred (brix_sd_instance_t *inst, const char *path, void *buf, size_t cap, const brix_sd_cred_t *cred)
ngx_int_t sd_xroot_setxattr_cred (brix_sd_instance_t *inst, const char *path, const char *name, const void *val, size_t len, int flags, const brix_sd_cred_t *cred)
ngx_int_t sd_xroot_removexattr_cred (brix_sd_instance_t *inst, const char *path, const char *name, const brix_sd_cred_t *cred)
brix_sd_dir_t * sd_xroot_opendir (brix_sd_instance_t *inst, const char *path, int *err_out)
brix_sd_dir_t * sd_xroot_opendir_cred (brix_sd_instance_t *inst, const char *path, int *err_out, const brix_sd_cred_t *cred)
ngx_int_t sd_xroot_readdir (brix_sd_dir_t *d, brix_sd_dirent_t *out)
ngx_int_t sd_xroot_closedir (brix_sd_dir_t *d)
Function Documentation
sd_xroot_close()
ngx_int_t sd_xroot_close (brix_sd_obj_t * obj)
Definition at line 124 of file sd_xroot_io.c.
References sd_xroot_obj_teardown().
sd_xroot_closedir()
ngx_int_t sd_xroot_closedir (brix_sd_dir_t * d)
Definition at line 714 of file sd_xroot_ns.c.
References brix_cache_dirlist_free(), and sd_xroot_dir_state::dl.
sd_xroot_copy_cred_into_task()
void sd_xroot_copy_cred_into_task (brix_cache_fill_t * t, const brix_sd_cred_t * cred)
Definition at line 56 of file sd_xroot.c.
References brix_sd_cred_t::bearer, brix_cache_fill_t::cred_bearer, brix_cache_fill_t::cred_principal, brix_cache_fill_t::cred_x509_proxy, brix_sd_cred_t::principal, and brix_sd_cred_t::x509_proxy.
Referenced by sd_xroot_origin_open(), and sd_xroot_staged_open_common().
sd_xroot_errno()
int sd_xroot_errno (const brix_cache_fill_t * t)
Definition at line 32 of file sd_xroot.c.
References kXR_isDirectory, kXR_NotAuthorized, kXR_NotFound, and brix_cache_fill_t::xrd_error.
Referenced by sd_xroot_opendir_common(), sd_xroot_origin_do_open(), sd_xroot_origin_open(), sd_xroot_server_copy(), sd_xroot_server_copy_cred(), sd_xroot_session(), and sd_xroot_staged_connect_open().
sd_xroot_fstat()
ngx_int_t sd_xroot_fstat (brix_sd_obj_t * obj, brix_sd_stat_t * out)
Definition at line 221 of file sd_xroot_io.c.
sd_xroot_fsync()
ngx_int_t sd_xroot_fsync (brix_sd_obj_t * obj)
Definition at line 206 of file sd_xroot_io.c.
References brix_cache_origin_sync(), sd_xroot_obj_state::fhandle, sd_xroot_obj_state::is_write, sd_xroot_obj_state::oc, and sd_xroot_obj_state::t.
sd_xroot_ftruncate()
ngx_int_t sd_xroot_ftruncate (brix_sd_obj_t * obj, off_t len)
Definition at line 187 of file sd_xroot_io.c.
References brix_cache_origin_truncate(), sd_xroot_obj_state::fhandle, sd_xroot_obj_state::is_write, sd_xroot_obj_state::oc, and sd_xroot_obj_state::t.
sd_xroot_getxattr()
ssize_t sd_xroot_getxattr (brix_sd_instance_t * inst, const char * path, const char * name, void * buf, size_t cap)
Definition at line 143 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_getfattr(), sd_xroot_inst_state::conf, name, sd_xroot_fattr_unmap(), and sd_xroot_session().
sd_xroot_getxattr_cred()
ssize_t sd_xroot_getxattr_cred (brix_sd_instance_t * inst, const char * path, const char * name, void * buf, size_t cap, const brix_sd_cred_t * cred)
Definition at line 479 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_getfattr(), sd_xroot_inst_state::conf, name, sd_xroot_fattr_unmap(), and sd_xroot_session().
sd_xroot_listxattr()
ssize_t sd_xroot_listxattr (brix_sd_instance_t * inst, const char * path, void * buf, size_t cap)
Definition at line 163 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_listfattr(), sd_xroot_inst_state::conf, ngx_memcpy, SD_XROOT_FATTR_PFX, SD_XROOT_FATTR_PFX_LEN, and sd_xroot_session().
sd_xroot_listxattr_cred()
ssize_t sd_xroot_listxattr_cred (brix_sd_instance_t * inst, const char * path, void * buf, size_t cap, const brix_sd_cred_t * cred)
Definition at line 500 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_listfattr(), sd_xroot_inst_state::conf, ngx_memcpy, SD_XROOT_FATTR_PFX, SD_XROOT_FATTR_PFX_LEN, and sd_xroot_session().
sd_xroot_obj_teardown()
void sd_xroot_obj_teardown (sd_xroot_obj_state * st)
Definition at line 78 of file sd_xroot.c.
References brix_cache_origin_close(), brix_cache_origin_close_file(), sd_xroot_obj_state::fhandle, sd_xroot_obj_state::file_open, sd_xroot_obj_state::oc, and sd_xroot_obj_state::t.
Referenced by sd_xroot_close(), sd_xroot_open_common(), sd_xroot_origin_open(), sd_xroot_stat(), and sd_xroot_stat_cred().
sd_xroot_open()
brix_sd_obj_t * sd_xroot_open (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, int * err_out)
Definition at line 102 of file sd_xroot_io.c.
References sd_xroot_open_common().
sd_xroot_open_cred()
brix_sd_obj_t * sd_xroot_open_cred (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, const brix_sd_cred_t * cred, int * err_out)
Definition at line 117 of file sd_xroot_io.c.
References sd_xroot_open_common().
sd_xroot_opendir()
brix_sd_dir_t * sd_xroot_opendir (brix_sd_instance_t * inst, const char * path, int * err_out)
Definition at line 668 of file sd_xroot_ns.c.
References sd_xroot_opendir_common().
sd_xroot_opendir_cred()
brix_sd_dir_t * sd_xroot_opendir_cred (brix_sd_instance_t * inst, const char * path, int * err_out, const brix_sd_cred_t * cred)
Definition at line 676 of file sd_xroot_ns.c.
References sd_xroot_opendir_common().
sd_xroot_origin_open()
sd_xroot_obj_state * sd_xroot_origin_open (const sd_xroot_origin_open_req_t * req)
Definition at line 150 of file sd_xroot.c.
References brix_cache_origin_bootstrap(), brix_cache_origin_connect(), brix_cache_fill_t::clean_path, sd_xroot_origin_open_req_t::conf, brix_cache_fill_t::conf, sd_xroot_origin_open_req_t::cred, brix_cache_fill_t::err_msg, sd_xroot_origin_open_req_t::err_out, brix_cache_origin_conn_t::fd, sd_xroot_obj_state::oc, sd_xroot_origin_open_req_t::path, sd_xroot_copy_cred_into_task(), sd_xroot_errno(), sd_xroot_obj_teardown(), sd_xroot_origin_do_open(), sd_xroot_obj_state::t, and brix_cache_fill_t::xrd_error.
Referenced by sd_xroot_open_common(), sd_xroot_stat(), and sd_xroot_stat_cred().
sd_xroot_pread()
ssize_t sd_xroot_pread (brix_sd_obj_t * obj, void * buf, size_t len, off_t off)
Definition at line 134 of file sd_xroot_io.c.
References brix_cache_origin_read_chunk(), brix_cache_sink_t::fd, sd_xroot_obj_state::fhandle, brix_cache_read_range_t::got, brix_cache_sink_t::mem, brix_cache_sink_t::mem_cap, sd_xroot_obj_state::oc, brix_cache_read_range_t::read_off, sd_xroot_obj_state::t, and brix_cache_read_range_t::want.
Referenced by sd_xroot_preadv().
sd_xroot_preadv()
ssize_t sd_xroot_preadv (brix_sd_obj_t * obj, const struct iovec * iov, int iovcnt, off_t off)
Definition at line 297 of file sd_xroot_io.c.
References sd_xroot_pread().
sd_xroot_pwrite()
ssize_t sd_xroot_pwrite (brix_sd_obj_t * obj, const void * buf, size_t len, off_t off)
Definition at line 165 of file sd_xroot_io.c.
References brix_cache_origin_write_chunk(), sd_xroot_obj_state::fhandle, sd_xroot_obj_state::is_write, sd_xroot_obj_state::oc, and sd_xroot_obj_state::t.
sd_xroot_readdir()
ngx_int_t sd_xroot_readdir (brix_sd_dir_t * d, brix_sd_dirent_t * out)
Definition at line 688 of file sd_xroot_ns.c.
References brix_cache_dirlist_t::count, sd_xroot_dir_state::dl, brix_sd_dirent_t::name, brix_cache_dirlist_t::names, and sd_xroot_dir_state::next.
sd_xroot_removexattr()
ngx_int_t sd_xroot_removexattr (brix_sd_instance_t * inst, const char * path, const char * name)
Definition at line 230 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_delfattr(), sd_xroot_inst_state::conf, name, sd_xroot_fattr_unmap(), and sd_xroot_session().
sd_xroot_removexattr_cred()
ngx_int_t sd_xroot_removexattr_cred (brix_sd_instance_t * inst, const char * path, const char * name, const brix_sd_cred_t * cred)
Definition at line 567 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_delfattr(), sd_xroot_inst_state::conf, name, sd_xroot_fattr_unmap(), and sd_xroot_session().
sd_xroot_rename()
ngx_int_t sd_xroot_rename (brix_sd_instance_t * inst, const char * src, const char * dst, int noreplace)
Definition at line 248 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_rename(), sd_xroot_inst_state::conf, and sd_xroot_session().
sd_xroot_rename_cred()
ngx_int_t sd_xroot_rename_cred (brix_sd_instance_t * inst, const char * src, const char * dst, int noreplace, const brix_sd_cred_t * cred)
Definition at line 422 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_rename(), sd_xroot_inst_state::conf, and sd_xroot_session().
sd_xroot_server_copy()
ngx_int_t sd_xroot_server_copy (brix_sd_instance_t * inst, const char * src, const char * dst, off_t * bytes_out)
Definition at line 346 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_close_file(), brix_cache_origin_open(), brix_cache_origin_open_write(), brix_cache_fill_t::clean_path, sd_xroot_inst_state::conf, sd_xroot_copy_body(), sd_xroot_errno(), sd_xroot_session(), and XRD_FHANDLE_LEN.
sd_xroot_server_copy_cred()
ngx_int_t sd_xroot_server_copy_cred (brix_sd_instance_t * inst, const char * src, const char * dst, off_t * bytes_out, const brix_sd_cred_t * cred)
Definition at line 444 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_close_file(), brix_cache_origin_open(), brix_cache_origin_open_write(), brix_cache_fill_t::clean_path, sd_xroot_inst_state::conf, sd_xroot_copy_body(), sd_xroot_errno(), sd_xroot_session(), and XRD_FHANDLE_LEN.
sd_xroot_setxattr()
ngx_int_t sd_xroot_setxattr (brix_sd_instance_t * inst, const char * path, const char * name, const void * val, size_t len, int flags)
Definition at line 210 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_setfattr(), sd_xroot_inst_state::conf, name, sd_xroot_fattr_unmap(), and sd_xroot_session().
sd_xroot_setxattr_cred()
ngx_int_t sd_xroot_setxattr_cred (brix_sd_instance_t * inst, const char * path, const char * name, const void * val, size_t len, int flags, const brix_sd_cred_t * cred)
Definition at line 545 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_setfattr(), sd_xroot_inst_state::conf, name, sd_xroot_fattr_unmap(), and sd_xroot_session().
sd_xroot_staged_abort()
void sd_xroot_staged_abort (brix_sd_staged_t * handle)
Definition at line 205 of file sd_xroot_staged.c.
References sd_xroot_staged_teardown().
sd_xroot_staged_commit()
ngx_int_t sd_xroot_staged_commit (brix_sd_staged_t * handle, int noreplace)
Definition at line 191 of file sd_xroot_staged.c.
References brix_cache_origin_sync(), sd_xroot_staged_state::fhandle, sd_xroot_staged_state::oc, sd_xroot_staged_teardown(), and sd_xroot_staged_state::t.
sd_xroot_staged_open()
brix_sd_staged_t * sd_xroot_staged_open (brix_sd_instance_t * inst, const char * final_path, mode_t mode, int * err_out)
Definition at line 149 of file sd_xroot_staged.c.
References sd_xroot_staged_open_common().
sd_xroot_staged_open_cred()
brix_sd_staged_t * sd_xroot_staged_open_cred (brix_sd_instance_t * inst, const char * final_path, mode_t mode, const brix_sd_cred_t * cred, int * err_out)
Definition at line 162 of file sd_xroot_staged.c.
References sd_xroot_staged_open_common().
sd_xroot_staged_write()
ssize_t sd_xroot_staged_write (brix_sd_staged_t * handle, const void * buf, size_t len, off_t off)
Definition at line 169 of file sd_xroot_staged.c.
References brix_cache_origin_write_chunk(), sd_xroot_staged_state::fhandle, sd_xroot_staged_state::oc, and sd_xroot_staged_state::t.
sd_xroot_stat()
ngx_int_t sd_xroot_stat (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out)
Definition at line 228 of file sd_xroot_io.c.
References sd_xroot_inst_state::conf, sd_xroot_origin_open_req_t::conf, brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, sd_xroot_obj_teardown(), sd_xroot_origin_open(), and brix_sd_stat_t::size.
sd_xroot_stat_cred()
ngx_int_t sd_xroot_stat_cred (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out, const brix_sd_cred_t * cred)
Definition at line 267 of file sd_xroot_io.c.
References sd_xroot_inst_state::conf, sd_xroot_origin_open_req_t::conf, brix_sd_stat_t::is_reg, brix_sd_cred_t::mode, brix_sd_stat_t::mode, sd_xroot_obj_teardown(), sd_xroot_origin_open(), and brix_sd_stat_t::size.
sd_xroot_unlink()
ngx_int_t sd_xroot_unlink (brix_sd_instance_t * inst, const char * path, int is_dir)
Definition at line 273 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_rm(), brix_cache_origin_rmdir(), sd_xroot_inst_state::conf, and sd_xroot_session().
sd_xroot_unlink_cred()
ngx_int_t sd_xroot_unlink_cred (brix_sd_instance_t * inst, const char * path, int is_dir, const brix_sd_cred_t * cred)
Definition at line 400 of file sd_xroot_ns.c.
References brix_cache_origin_close(), brix_cache_origin_rm(), brix_cache_origin_rmdir(), sd_xroot_inst_state::conf, and sd_xroot_session().