nginx-xrootd: src/fs/backend/s3/sd_s3_internal.h File Reference
sd_s3_internal.h File Reference
#include "sd_s3.h"
#include "sd_s3_transport.h"
#include <stdint.h>
#include <stddef.h>
Data Structures
struct sd_s3_part_etag
struct sd_s3_file
Macros
#define SD_S3_AUTH_HDRS_CAP 4096
#define SD_S3_PREAD_MAX (7LL * 1024 * 1024)
#define SD_S3_KEY_MAX 4096
#define SD_S3_ETAG_LEN 96
#define SD_S3_UPLOAD_ID_LEN 128
#define SD_S3_ETAG_INIT_CAP 16
#define SD_S3_PUT_BUF_INIT (64 * 1024)
Functions
void sd_s3_set_err (char *errbuf, size_t errcap, const char *fmt,...)
void sd_s3_utc_now (char amzdate[20], char datestamp[12])
void sd_s3_sha256_hex (const void *data, size_t len, char *out)
int sd_s3_sign (const sd_s3_file *f, const char *method, const char *canon_qs, char *hdrs, size_t hdrsz)
int sd_s3_status_err (int status, const char *op, const char *key, char *errbuf, size_t errcap)
Macro Definition Documentation
SD_S3_AUTH_HDRS_CAP
#define SD_S3_AUTH_HDRS_CAP 4096
Definition at line 21 of file sd_s3_internal.h.
SD_S3_ETAG_INIT_CAP
#define SD_S3_ETAG_INIT_CAP 16
Definition at line 26 of file sd_s3_internal.h.
SD_S3_ETAG_LEN
#define SD_S3_ETAG_LEN 96
Definition at line 24 of file sd_s3_internal.h.
SD_S3_KEY_MAX
#define SD_S3_KEY_MAX 4096
Definition at line 23 of file sd_s3_internal.h.
SD_S3_PREAD_MAX
#define SD_S3_PREAD_MAX (7LL * 1024 * 1024)
Definition at line 22 of file sd_s3_internal.h.
SD_S3_PUT_BUF_INIT
#define SD_S3_PUT_BUF_INIT (64 * 1024)
Definition at line 27 of file sd_s3_internal.h.
SD_S3_UPLOAD_ID_LEN
#define SD_S3_UPLOAD_ID_LEN 128
Definition at line 25 of file sd_s3_internal.h.
Function Documentation
sd_s3_set_err()
void sd_s3_set_err (char * errbuf, size_t errcap, const char * fmt, ...)
Definition at line 35 of file sd_s3.c.
Referenced by sd_s3_check_sequential(), sd_s3_commit(), sd_s3_delete(), sd_s3_etag_ensure_cap(), sd_s3_get_meta(), sd_s3_get_unixattr(), sd_s3_mpu_complete(), sd_s3_mpu_create(), sd_s3_mpu_upload_part(), sd_s3_open_read(), sd_s3_open_write(), sd_s3_pread(), sd_s3_pwrite(), sd_s3_set_meta_f(), sd_s3_set_unixattr(), sd_s3_size(), and sd_s3_status_err().
sd_s3_sha256_hex()
void sd_s3_sha256_hex (const void * data, size_t len, char * out)
Definition at line 90 of file sd_s3.c.
References brix_hex_encode(), and brix_sha256().
Referenced by sd_s3_sign(), and sd_s3_sign_ext().
sd_s3_sign()
int sd_s3_sign (const sd_s3_file * f, const char * method, const char * canon_qs, char * hdrs, size_t hdrsz)
Definition at line 101 of file sd_s3.c.
References sd_s3_file::ak, brix_format_host_port(), brix_hex_encode(), brix_hmac_sha256(), brix_http_urlencode(), brix_sigv4_signing_key(), sd_s3_file::host, sd_s3_file::key, sd_s3_file::port, sd_s3_file::region, sd_s3_sha256_hex(), sd_s3_utc_now(), and sd_s3_file::sk.
Referenced by sd_s3_commit(), sd_s3_delete(), sd_s3_get_meta(), sd_s3_mpu_abort(), sd_s3_mpu_complete(), sd_s3_mpu_create(), sd_s3_mpu_upload_part(), sd_s3_pread(), and sd_s3_size().
sd_s3_status_err()
int sd_s3_status_err (int status, const char * op, const char * key, char * errbuf, size_t errcap)
Definition at line 164 of file sd_s3.c.
References key, and sd_s3_set_err().
Referenced by sd_s3_commit(), sd_s3_delete(), sd_s3_get_meta(), sd_s3_mpu_complete(), sd_s3_mpu_create(), sd_s3_mpu_upload_part(), sd_s3_pread(), sd_s3_set_meta_f(), and sd_s3_size().
sd_s3_utc_now()
void sd_s3_utc_now (char amzdate[20], char datestamp[12])
Definition at line 50 of file sd_s3.c.
Referenced by sd_s3_sign(), and sd_s3_sign_ext().