nginx-xrootd: src/fs/backend/frm/sd_frm.h File Reference
sd_frm.h File Reference
#include "fs/backend/sd.h"
Data Structures
struct brix_mss_adapter_t
Macros
#define BRIX_RESIDENCY_ONLINE 0 /* in the MSS disk buffer, readable now */
#define BRIX_RESIDENCY_NEARLINE 1 /* recallable (a stage is in flight/queued) */
#define BRIX_RESIDENCY_OFFLINE 2 /* on tape; a recall will fault it in */
#define BRIX_RESIDENCY_ABSENT (-1) /* unknown to the MSS */
Functions
brix_sd_instance_t * brix_sd_frm_create (const char *adapter, const char *location, ngx_log_t *log)
void brix_sd_frm_destroy (brix_sd_instance_t *inst)
Macro Definition Documentation
BRIX_RESIDENCY_ABSENT
#define BRIX_RESIDENCY_ABSENT (-1) /* unknown to the MSS */
Definition at line 41 of file sd_frm.h.
BRIX_RESIDENCY_NEARLINE
#define BRIX_RESIDENCY_NEARLINE 1 /* recallable (a stage is in flight/queued) */
Definition at line 39 of file sd_frm.h.
BRIX_RESIDENCY_OFFLINE
#define BRIX_RESIDENCY_OFFLINE 2 /* on tape; a recall will fault it in */
Definition at line 40 of file sd_frm.h.
BRIX_RESIDENCY_ONLINE
#define BRIX_RESIDENCY_ONLINE 0 /* in the MSS disk buffer, readable now */
Definition at line 38 of file sd_frm.h.
Function Documentation
brix_sd_frm_create()
brix_sd_instance_t * brix_sd_frm_create (const char * adapter, const char * location, ngx_log_t * log)
Definition at line 430 of file sd_frm.c.
References brix_sd_frm_driver, frm_select_exec_adapter(), frm_select_stub_adapter(), log, sd_frm_state::log, and sd_frm_state::mss.
Referenced by brix_vbr_build_tape(), and tier_build_tape().
brix_sd_frm_destroy()
void brix_sd_frm_destroy (brix_sd_instance_t * inst)
Definition at line 475 of file sd_frm.c.
References brix_mss_adapter_t::destroy, sd_frm_state::mss, and sd_frm_state::mss_ctx.