nginx-xrootd: src/fs/backend/cache/sd_cache.c File Reference
sd_cache.c File Reference
#include "sd_cache.h"
#include "sd_cache_internal.h"
#include "sd_cache_policy.h"
#include "protocols/cvmfs/classify.h"
#include "observability/metrics/metrics.h"
#include "observability/metrics/metrics_macros.h"
#include "fs/cache/cstore.h"
#include "fs/backend/http/sd_http.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct sd_cache_partial_t
Macros
#define SD_CACHE_CHUNK (1u << 20)
Functions
static ngx_int_t sd_cache_fill (sd_cache_inst_state *st, const char *key)
static int sd_cache_fill_block (sd_cache_partial_t *p, uint64_t blk)
static brix_sd_obj_t * sd_cache_partial_open (brix_sd_instance_t *inst, sd_cache_inst_state *st, const char *key, int *err_out)
static brix_sd_obj_t * sd_cache_open (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, int *err_out)
static ngx_int_t sd_cache_stat (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out)
static ngx_int_t sd_cache_unlink (brix_sd_instance_t *inst, const char *path, int is_dir)
static ngx_int_t sd_cache_mkdir (brix_sd_instance_t *inst, const char *path, mode_t mode)
static ngx_int_t sd_cache_rename (brix_sd_instance_t *inst, const char *src, const char *dst, int noreplace)
static ngx_int_t sd_cache_server_copy (brix_sd_instance_t *inst, const char *src, const char *dst, off_t *bytes_out)
static ngx_int_t sd_cache_setattr (brix_sd_instance_t *inst, const char *path, const brix_sd_setattr_t *attr)
static brix_sd_dir_t * sd_cache_opendir (brix_sd_instance_t *inst, const char *path, int *err_out)
static ngx_int_t sd_cache_readdir (brix_sd_dir_t *d, brix_sd_dirent_t *out)
static ngx_int_t sd_cache_closedir (brix_sd_dir_t *d)
static ssize_t sd_cache_getxattr (brix_sd_instance_t *inst, const char *path, const char *name, void *buf, size_t cap)
static ssize_t sd_cache_listxattr (brix_sd_instance_t *inst, const char *path, void *buf, size_t cap)
static ngx_int_t sd_cache_setxattr (brix_sd_instance_t *inst, const char *path, const char *name, const void *val, size_t len, int flags)
static ngx_int_t sd_cache_removexattr (brix_sd_instance_t *inst, const char *path, const char *name)
static brix_sd_staged_t * sd_cache_staged_open (brix_sd_instance_t *inst, const char *final_path, mode_t mode, int *err_out)
static ssize_t sd_cache_staged_write (brix_sd_staged_t *st, const void *buf, size_t len, off_t off)
static ngx_int_t sd_cache_staged_commit (brix_sd_staged_t *st, int noreplace)
static void sd_cache_staged_abort (brix_sd_staged_t *st)
static int sd_cache_fill_block_cb (void *ctx, uint64_t blk)
static ssize_t sd_cache_pread (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
static ngx_int_t sd_cache_close (brix_sd_obj_t *obj)
static ngx_int_t sd_cache_fstat (brix_sd_obj_t *obj, brix_sd_stat_t *out)
static ngx_fd_t sd_cache_read_sendfile_fd (brix_sd_obj_t *obj, off_t off, size_t len, unsigned want_zerocopy)
brix_sd_instance_t * brix_sd_cache_create (brix_sd_instance_t *source, brix_sd_instance_t *store, const brix_cache_policy_t *policy, const char *store_local_root, ngx_log_t *log)
void brix_sd_cache_destroy (brix_sd_instance_t *inst)
int brix_sd_cache_instance_is (const brix_sd_instance_t *inst)
int brix_sd_cache_fill_needs_offload (brix_sd_instance_t *inst, const char *key)
ngx_int_t brix_sd_cache_fill_key (brix_sd_instance_t *inst, const char *key)
brix_sd_instance_t * brix_sd_cache_store_instance (const brix_sd_instance_t *inst)
brix_sd_instance_t * brix_sd_cache_source_instance (const brix_sd_instance_t *inst)
void * brix_sd_cache_cstore (const brix_sd_instance_t *inst)
Variables
static const brix_sd_driver_t brix_sd_cache_driver
Macro Definition Documentation
SD_CACHE_CHUNK
#define SD_CACHE_CHUNK (1u << 20)
Definition at line 30 of file sd_cache.c.
Function Documentation
brix_sd_cache_create()
brix_sd_instance_t * brix_sd_cache_create (brix_sd_instance_t * source, brix_sd_instance_t * store, const brix_cache_policy_t * policy, const char * store_local_root, ngx_log_t * log)
Definition at line 841 of file sd_cache.c.
References brix_cache_policy_t::batch_cinfo, brix_cstore_init(), brix_sd_cache_driver, sd_cache_inst_state::cstore, brix_cache_policy_t::l1_entries, log, sd_cache_inst_state::log, brix_cache_policy_t::meta_mode, sd_cache_inst_state::policy, and sd_cache_inst_state::source.
Referenced by brix_tier_build_stack(), and brix_vfs_backend_entry_build().
brix_sd_cache_cstore()
void * brix_sd_cache_cstore (const brix_sd_instance_t * inst)
Definition at line 998 of file sd_cache.c.
References brix_sd_cache_instance_is(), and SD_CACHE_ST.
Referenced by brix_cache_storage_cstore().
brix_sd_cache_destroy()
void brix_sd_cache_destroy (brix_sd_instance_t * inst)
Definition at line 883 of file sd_cache.c.
References brix_cstore_cleanup(), and sd_cache_inst_state::cstore.
brix_sd_cache_fill_key()
ngx_int_t brix_sd_cache_fill_key (brix_sd_instance_t * inst, const char * key)
Definition at line 966 of file sd_cache.c.
References brix_sd_cache_instance_is(), key, sd_cache_fill(), and SD_CACHE_ST.
Referenced by brix_cache_fill_composed_thread().
brix_sd_cache_fill_needs_offload()
int brix_sd_cache_fill_needs_offload (brix_sd_instance_t * inst, const char * key)
Definition at line 922 of file sd_cache.c.
References brix_cache_cinfo_expired(), BRIX_CINFO_F_COMPLETE, BRIX_CMETA_LOCAL, brix_cstore_cinfo_load(), brix_sd_cache_instance_is(), BRIX_SD_CAP_FD, brix_sd_caps(), sd_cache_inst_state::cstore, brix_cache_policy_t::cvmfs_manifest_ttl, brix_cache_cinfo_t::flags, key, brix_cstore_t::meta_mode, sd_cache_inst_state::policy, SD_CACHE_ST, brix_cache_policy_t::slice_size, and sd_cache_inst_state::source.
Referenced by brix_handle_open(), and brix_open_read_probe().
brix_sd_cache_instance_is()
int brix_sd_cache_instance_is (const brix_sd_instance_t * inst)
Definition at line 909 of file sd_cache.c.
References brix_sd_cache_driver.
Referenced by brix_cache_storage(), brix_cache_storage_cstore(), brix_sd_cache_cstore(), brix_sd_cache_fill_key(), brix_sd_cache_fill_needs_offload(), brix_sd_cache_source_instance(), brix_sd_cache_store_instance(), and stage_reconcile_one().
brix_sd_cache_source_instance()
brix_sd_instance_t * brix_sd_cache_source_instance (const brix_sd_instance_t * inst)
Definition at line 989 of file sd_cache.c.
References brix_sd_cache_instance_is(), and SD_CACHE_SRC.
Referenced by brix_vfs_decorator_source(), cvmfs_unwrap_http(), cvmfs_var_origin(), health_build_json(), sd_cache_note_upstream(), and stage_reconcile_one().
brix_sd_cache_store_instance()
brix_sd_instance_t * brix_sd_cache_store_instance (const brix_sd_instance_t * inst)
Definition at line 979 of file sd_cache.c.
References brix_sd_cache_instance_is(), and SD_CACHE_ST.
Referenced by brix_cache_storage().
sd_cache_close()
static ngx_int_t sd_cache_close (brix_sd_obj_t * obj) static
Definition at line 760 of file sd_cache.c.
References sd_cache_partial_t::bitmap, sd_cache_partial_t::cache_fd, close(), and sd_cache_partial_t::src_obj.
sd_cache_closedir()
static ngx_int_t sd_cache_closedir (brix_sd_dir_t * d) static
Definition at line 632 of file sd_cache.c.
sd_cache_fill()
static ngx_int_t sd_cache_fill (sd_cache_inst_state * st, const char * key) static
Definition at line 39 of file sd_cache.c.
References brix_cache_cinfo_t::block_size, BRIX_ATOMIC_INC, BRIX_CACHE_CINFO_MAGIC, brix_cache_cinfo_nblocks(), brix_cache_cinfo_set_expires(), BRIX_CACHE_CINFO_VERSION, BRIX_CACHE_DIRTY_BLOCK, brix_cache_quarantine_part(), brix_cache_verify_cvmfs_cas(), BRIX_CACHE_VERIFY_CVMFS_CAS, BRIX_CACHE_VERIFY_ERROR, BRIX_CACHE_VERIFY_MISMATCH, BRIX_CACHE_VERIFY_VERIFIED, BRIX_CINFO_F_COMPLETE, BRIX_CINFO_F_VERIFIED, brix_cstore_cinfo_store(), brix_cstore_fill_abort(), brix_cstore_fill_commit(), brix_cstore_fill_open(), brix_cstore_fill_write(), BRIX_CVMFS_METRIC_INC, BRIX_SD_O_READ, sd_cache_inst_state::cstore, brix_cache_policy_t::cvmfs_manifest_ttl, brix_cache_cinfo_t::filled_at, brix_cache_cinfo_t::flags, key, sd_cache_inst_state::log, brix_cache_cinfo_t::magic, brix_sd_stat_t::mode, brix_cache_cinfo_t::mode, brix_sd_stat_t::mtime, brix_cache_cinfo_t::mtime, brix_cache_cinfo_t::nblocks, sd_cache_inst_state::policy, brix_cache_policy_t::quarantine_dir, sd_cache_admit(), SD_CACHE_CHUNK, sd_cache_is_manifest_key(), sd_cache_ms_since(), sd_cache_note_origin_bytes(), sd_cache_note_upstream(), sd_cache_repo_metrics(), sd_cache_stale_serve_ok(), brix_sd_stat_t::size, brix_cache_cinfo_t::size, sd_cache_inst_state::source, brix_cache_policy_t::verify, ngx_brix_cvmfs_repo_metrics_t::verify_failures_total, and brix_cache_cinfo_t::version.
Referenced by brix_sd_cache_fill_key(), and sd_cache_open().
sd_cache_fill_block()
static int sd_cache_fill_block (sd_cache_partial_t * p, uint64_t blk) static
Definition at line 266 of file sd_cache.c.
References sd_cache_partial_t::bitmap, sd_cache_partial_t::block_size, brix_cache_cinfo_mark_block(), brix_cache_cinfo_record_block(), BRIX_SD_O_READ, sd_cache_partial_t::cache_fd, sd_cache_partial_t::cache_path, sd_cache_partial_t::key, sd_cache_partial_t::log, sd_cache_partial_t::mode, sd_cache_partial_t::mtime, sd_cache_partial_t::size, sd_cache_partial_t::source, and sd_cache_partial_t::src_obj.
Referenced by sd_cache_fill_block_cb().
sd_cache_fill_block_cb()
static int sd_cache_fill_block_cb (void * ctx, uint64_t blk) static
Definition at line 739 of file sd_cache.c.
References sd_cache_fill_block().
Referenced by sd_cache_pread().
sd_cache_fstat()
static ngx_int_t sd_cache_fstat (brix_sd_obj_t * obj, brix_sd_stat_t * out) static
Definition at line 781 of file sd_cache.c.
References brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, sd_cache_partial_t::mtime, brix_sd_stat_t::mtime, sd_cache_partial_t::size, and brix_sd_stat_t::size.
sd_cache_getxattr()
static ssize_t sd_cache_getxattr (brix_sd_instance_t * inst, const char * path, const char * name, void * buf, size_t cap) static
Definition at line 638 of file sd_cache.c.
References name, s, and SD_CACHE_SRC.
sd_cache_listxattr()
static ssize_t sd_cache_listxattr (brix_sd_instance_t * inst, const char * path, void * buf, size_t cap) static
Definition at line 651 of file sd_cache.c.
References s, and SD_CACHE_SRC.
sd_cache_mkdir()
static ngx_int_t sd_cache_mkdir (brix_sd_instance_t * inst, const char * path, mode_t mode) static
Definition at line 569 of file sd_cache.c.
References mode, s, and SD_CACHE_SRC.
sd_cache_open()
static brix_sd_obj_t * sd_cache_open (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, int * err_out) static
Definition at line 425 of file sd_cache.c.
References BRIX_CINFO_F_COMPLETE, BRIX_CMETA_LOCAL, brix_cstore_cinfo_load(), brix_cstore_evict(), brix_cstore_serve_open(), BRIX_SD_CAP_NEARLINE, brix_sd_caps(), BRIX_SD_O_CREATE, BRIX_SD_O_TRUNC, BRIX_SD_O_WRITE, sd_cache_inst_state::cstore, brix_cache_cinfo_t::flags, sd_cache_inst_state::log, brix_cstore_t::meta_mode, mode, brix_cache_cinfo_t::mode, sd_cache_inst_state::policy, rr(), sd_cache_admit(), sd_cache_fill(), sd_cache_partial_open(), SD_CACHE_ST, brix_cache_policy_t::slice_size, and sd_cache_inst_state::source.
sd_cache_opendir()
static brix_sd_dir_t * sd_cache_opendir (brix_sd_instance_t * inst, const char * path, int * err_out) static
Definition at line 610 of file sd_cache.c.
References s, and SD_CACHE_SRC.
sd_cache_partial_open()
static brix_sd_obj_t * sd_cache_partial_open (brix_sd_instance_t * inst, sd_cache_inst_state * st, const char * key, int * err_out) static
Definition at line 343 of file sd_cache.c.
References sd_cache_partial_t::bitmap, sd_cache_partial_t::bitmap_len, sd_cache_partial_t::block_size, brix_cache_cinfo_t::block_size, brix_cache_cinfo_bitmap_len(), brix_cache_cinfo_load(), brix_cache_cinfo_nblocks(), brix_cstore_partial_open(), sd_cache_partial_t::cache_fd, sd_cache_partial_t::cache_path, close(), sd_cache_inst_state::cstore, sd_cache_partial_t::key, key, sd_cache_partial_t::log, sd_cache_inst_state::log, sd_cache_partial_t::mode, brix_sd_stat_t::mode, sd_cache_partial_t::mtime, brix_sd_stat_t::mtime, sd_cache_partial_t::nblocks, PATH_MAX, sd_cache_inst_state::policy, sd_cache_partial_t::size, brix_sd_stat_t::size, brix_cache_cinfo_t::size, brix_cache_policy_t::slice_size, sd_cache_partial_t::source, and sd_cache_inst_state::source.
Referenced by sd_cache_open().
sd_cache_pread()
static ssize_t sd_cache_pread (brix_sd_obj_t * obj, void * buf, size_t len, off_t off) static
Definition at line 745 of file sd_cache.c.
References sd_cache_partial_t::bitmap, sd_cache_partial_t::block_size, brix_cstore_serve_pread(), sd_cache_partial_t::cache_fd, sd_cache_partial_t::nblocks, sd_cache_fill_block_cb(), and sd_cache_partial_t::size.
sd_cache_read_sendfile_fd()
static ngx_fd_t sd_cache_read_sendfile_fd (brix_sd_obj_t * obj, off_t off, size_t len, unsigned want_zerocopy) static
Definition at line 797 of file sd_cache.c.
sd_cache_readdir()
static ngx_int_t sd_cache_readdir (brix_sd_dir_t * d, brix_sd_dirent_t * out) static
Definition at line 624 of file sd_cache.c.
sd_cache_removexattr()
static ngx_int_t sd_cache_removexattr (brix_sd_instance_t * inst, const char * path, const char * name) static
Definition at line 677 of file sd_cache.c.
References name, s, and SD_CACHE_SRC.
sd_cache_rename()
static ngx_int_t sd_cache_rename (brix_sd_instance_t * inst, const char * src, const char * dst, int noreplace) static
Definition at line 576 of file sd_cache.c.
References brix_cstore_evict(), sd_cache_inst_state::cstore, s, SD_CACHE_ST, and sd_cache_inst_state::source.
sd_cache_server_copy()
static ngx_int_t sd_cache_server_copy (brix_sd_instance_t * inst, const char * src, const char * dst, off_t * bytes_out) static
Definition at line 593 of file sd_cache.c.
References s, and SD_CACHE_SRC.
sd_cache_setattr()
static ngx_int_t sd_cache_setattr (brix_sd_instance_t * inst, const char * path, const brix_sd_setattr_t * attr) static
Definition at line 602 of file sd_cache.c.
References s, and SD_CACHE_SRC.
sd_cache_setxattr()
static ngx_int_t sd_cache_setxattr (brix_sd_instance_t * inst, const char * path, const char * name, const void * val, size_t len, int flags) static
Definition at line 664 of file sd_cache.c.
References name, s, and SD_CACHE_SRC.
sd_cache_staged_abort()
static void sd_cache_staged_abort (brix_sd_staged_t * st) static
Definition at line 725 of file sd_cache.c.
sd_cache_staged_commit()
static ngx_int_t sd_cache_staged_commit (brix_sd_staged_t * st, int noreplace) static
Definition at line 718 of file sd_cache.c.
sd_cache_staged_open()
static brix_sd_staged_t * sd_cache_staged_open (brix_sd_instance_t * inst, const char * final_path, mode_t mode, int * err_out) static
Definition at line 692 of file sd_cache.c.
References brix_cstore_evict(), sd_cache_inst_state::cstore, mode, s, SD_CACHE_ST, and sd_cache_inst_state::source.
sd_cache_staged_write()
static ssize_t sd_cache_staged_write (brix_sd_staged_t * st, const void * buf, size_t len, off_t off) static
Definition at line 710 of file sd_cache.c.
sd_cache_stat()
static ngx_int_t sd_cache_stat (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out) static
Definition at line 526 of file sd_cache.c.
References BRIX_CINFO_F_COMPLETE, brix_cstore_cinfo_load(), sd_cache_inst_state::cstore, brix_sd_stat_t::ctime, brix_cache_cinfo_t::flags, brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, brix_cache_cinfo_t::mode, brix_sd_stat_t::mtime, brix_cache_cinfo_t::mtime, s, SD_CACHE_SRC, SD_CACHE_ST, brix_sd_stat_t::size, and brix_cache_cinfo_t::size.
sd_cache_unlink()
static ngx_int_t sd_cache_unlink (brix_sd_instance_t * inst, const char * path, int is_dir) static
Definition at line 555 of file sd_cache.c.
References brix_cstore_evict(), sd_cache_inst_state::cstore, s, SD_CACHE_ST, and sd_cache_inst_state::source.
Variable Documentation
brix_sd_cache_driver
const brix_sd_driver_t brix_sd_cache_driver static
Initial value:
= {
    .name        = "cache",
    .caps        = BRIX_SD_CAP_RANGE_READ | BRIX_SD_CAP_RANDOM_WRITE
                 | BRIX_SD_CAP_TRUNCATE | BRIX_SD_CAP_XATTR
                 | BRIX_SD_CAP_HARD_RENAME | BRIX_SD_CAP_SERVER_COPY
                 | BRIX_SD_CAP_DIRS,
    .open             = sd_cache_open,
    .close            = sd_cache_close,
    .pread            = sd_cache_pread,
    .fstat            = sd_cache_fstat,
    .read_sendfile_fd = sd_cache_read_sendfile_fd,
    .stat          = sd_cache_stat,
    .unlink        = sd_cache_unlink,
    .mkdir         = sd_cache_mkdir,
    .rename        = sd_cache_rename,
    .server_copy   = sd_cache_server_copy,
    .setattr       = sd_cache_setattr,
    .opendir       = sd_cache_opendir,
    .readdir       = sd_cache_readdir,
    .closedir      = sd_cache_closedir,
    .getxattr      = sd_cache_getxattr,
    .listxattr     = sd_cache_listxattr,
    .setxattr      = sd_cache_setxattr,
    .removexattr   = sd_cache_removexattr,
    .staged_open   = sd_cache_staged_open,
    .staged_write  = sd_cache_staged_write,
    .staged_commit = sd_cache_staged_commit,
    .staged_abort  = sd_cache_staged_abort,
}
Definition at line 810 of file sd_cache.c.
Referenced by brix_sd_cache_create(), and brix_sd_cache_instance_is().