nginx-xrootd: src/fs/backend/pblock/sd_pblock_catalog.h File Reference
sd_pblock_catalog.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>
Data Structures
struct pblock_meta
Macros
#define PBLOCK_BLOB_ID_HEX 32
#define PBLOCK_BLOB_ID_CAP (PBLOCK_BLOB_ID_HEX + 1)
#define PBLOCK_DEFAULT_BLOCK_SIZE (64LL * 1024 * 1024)
Typedefs
typedef struct pblock_catalog pblock_catalog
typedef struct pblock_catalog_iter pblock_catalog_iter
Functions
pblock_catalog * pblock_catalog_open (const char *db_path, int busy_timeout_ms)
void pblock_catalog_close (pblock_catalog *cat)
int pblock_catalog_lookup (pblock_catalog *cat, const char *path, pblock_meta *out)
int pblock_catalog_put (pblock_catalog *cat, const char *path, const pblock_meta *meta)
int pblock_catalog_create (pblock_catalog *cat, const char *path, const pblock_meta *meta)
int pblock_catalog_setattr (pblock_catalog *cat, const char *path, int set_mode, uint32_t perm, int set_mtime, int64_t mtime, int64_t now)
int pblock_catalog_touch (pblock_catalog *cat, const char *path, int64_t size, int64_t mtime)
int pblock_catalog_remove (pblock_catalog *cat, const char *path)
int pblock_catalog_child_count (pblock_catalog *cat, const char *path)
int pblock_catalog_rename (pblock_catalog *cat, const char *src, const char *dst)
int pblock_catalog_parent_ok (pblock_catalog *cat, const char *path)
pblock_catalog_iter * pblock_catalog_opendir (pblock_catalog *cat, const char *parent)
int pblock_catalog_readdir (pblock_catalog_iter *it, char *name, size_t cap)
void pblock_catalog_closedir (pblock_catalog_iter *it)
ssize_t pblock_catalog_getxattr (pblock_catalog *cat, const char *path, const char *name, void *buf, size_t cap)
ssize_t pblock_catalog_listxattr (pblock_catalog *cat, const char *path, void *buf, size_t cap)
int pblock_catalog_setxattr (pblock_catalog *cat, const char *path, const char *name, const void *val, size_t len)
int pblock_catalog_removexattr (pblock_catalog *cat, const char *path, const char *name)
Macro Definition Documentation
PBLOCK_BLOB_ID_CAP
#define PBLOCK_BLOB_ID_CAP (PBLOCK_BLOB_ID_HEX + 1)
Definition at line 33 of file sd_pblock_catalog.h.
PBLOCK_BLOB_ID_HEX
#define PBLOCK_BLOB_ID_HEX 32
Definition at line 32 of file sd_pblock_catalog.h.
PBLOCK_DEFAULT_BLOCK_SIZE
#define PBLOCK_DEFAULT_BLOCK_SIZE (64LL * 1024 * 1024)
Definition at line 38 of file sd_pblock_catalog.h.
Typedef Documentation
pblock_catalog
typedef struct pblock_catalog pblock_catalog
Definition at line 41 of file sd_pblock_catalog.h.
pblock_catalog_iter
typedef struct pblock_catalog_iter pblock_catalog_iter
Definition at line 105 of file sd_pblock_catalog.h.
Function Documentation
pblock_catalog_child_count()
int pblock_catalog_child_count (pblock_catalog * cat, const char * path)
Referenced by test_children_and_remove().
pblock_catalog_close()
void pblock_catalog_close (pblock_catalog * cat)
Referenced by main().
pblock_catalog_closedir()
void pblock_catalog_closedir (pblock_catalog_iter * it)
Referenced by test_opendir().
pblock_catalog_create()
int pblock_catalog_create (pblock_catalog * cat, const char * path, const pblock_meta * meta)
Referenced by test_parent_gate().
pblock_catalog_getxattr()
ssize_t pblock_catalog_getxattr (pblock_catalog * cat, const char * path, const char * name, void * buf, size_t cap)
Referenced by test_xattr().
pblock_catalog_listxattr()
ssize_t pblock_catalog_listxattr (pblock_catalog * cat, const char * path, void * buf, size_t cap)
Referenced by test_xattr().
pblock_catalog_lookup()
int pblock_catalog_lookup (pblock_catalog * cat, const char * path, pblock_meta * out)
Referenced by test_children_and_remove(), test_parent_gate(), test_put_lookup(), test_rename_subtree(), and test_touch().
pblock_catalog_open()
pblock_catalog * pblock_catalog_open (const char * db_path, int busy_timeout_ms)
Referenced by main().
pblock_catalog_opendir()
pblock_catalog_iter * pblock_catalog_opendir (pblock_catalog * cat, const char * parent)
Referenced by test_opendir().
pblock_catalog_parent_ok()
int pblock_catalog_parent_ok (pblock_catalog * cat, const char * path)
pblock_catalog_put()
int pblock_catalog_put (pblock_catalog * cat, const char * path, const pblock_meta * meta)
Referenced by test_children_and_remove(), test_opendir(), test_parent_gate(), test_put_lookup(), test_rename_subtree(), test_touch(), and test_xattr().
pblock_catalog_readdir()
int pblock_catalog_readdir (pblock_catalog_iter * it, char * name, size_t cap)
Referenced by test_opendir().
pblock_catalog_remove()
int pblock_catalog_remove (pblock_catalog * cat, const char * path)
Referenced by test_children_and_remove(), and test_parent_gate().
pblock_catalog_removexattr()
int pblock_catalog_removexattr (pblock_catalog * cat, const char * path, const char * name)
Referenced by test_xattr().
pblock_catalog_rename()
int pblock_catalog_rename (pblock_catalog * cat, const char * src, const char * dst)
Referenced by test_parent_gate(), and test_rename_subtree().
pblock_catalog_setattr()
int pblock_catalog_setattr (pblock_catalog * cat, const char * path, int set_mode, uint32_t perm, int set_mtime, int64_t mtime, int64_t now)
pblock_catalog_setxattr()
int pblock_catalog_setxattr (pblock_catalog * cat, const char * path, const char * name, const void * val, size_t len)
Referenced by test_xattr().
pblock_catalog_touch()
int pblock_catalog_touch (pblock_catalog * cat, const char * path, int64_t size, int64_t mtime)
Referenced by test_touch().