nginx-xrootd: src/fs/backend/cache/sd_cache_fill.c File Reference
sd_cache_fill.c File Reference
#include "sd_cache.h"
#include "sd_cache_internal.h"
#include "sd_cache_policy.h"
#include "protocols/cvmfs/classify.h"
#include "observability/metrics/metrics.h"
#include "observability/metrics/metrics_macros.h"
#include "fs/cache/cstore.h"
#include "fs/backend/http/sd_http.h"
#include "fs/path/path.h"
#include "net/guard/guard.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct sd_cache_fill_state_t
Macros
#define SD_CACHE_CHUNK (1u << 20)
Functions
static ngx_int_t cache_fill_acquire (sd_cache_inst_state *st, const char *key, const brix_sd_cred_t *cred, sd_cache_fill_state_t *fs)
static ngx_int_t cache_fill_pump (sd_cache_inst_state *st, const char *key, sd_cache_fill_state_t *fs)
void sd_cache_guard_tamper (sd_cache_inst_state *st, brix_sd_instance_t *actor, const char *key)
static ngx_int_t cache_fill_verify_reject (sd_cache_inst_state *st, const char *key, sd_cache_fill_state_t *fs, const char *pp)
static ngx_int_t cache_fill_verify (sd_cache_inst_state *st, const char *key, sd_cache_fill_state_t *fs)
static ngx_int_t cache_fill_commit (sd_cache_inst_state *st, const char *key, sd_cache_fill_state_t *fs)
static ngx_int_t sd_cache_fill_attempt (sd_cache_inst_state *st, const char *key, const brix_sd_cred_t *cred, brix_sd_instance_t *src, int from_cold, int from_peer)
static uint64_t sd_cache_hrw_fnv1a64 (const char *label, const char *key)
static int sd_cache_peer_owner (const sd_cache_inst_state *st, const char *key)
ngx_int_t sd_cache_fill (sd_cache_inst_state *st, const char *key, const brix_sd_cred_t *cred)
ngx_int_t brix_sd_cache_demote (brix_sd_instance_t *inst, const char *key)
Macro Definition Documentation
SD_CACHE_CHUNK
#define SD_CACHE_CHUNK (1u << 20)
Definition at line 45 of file sd_cache_fill.c.
Function Documentation
brix_sd_cache_demote()
ngx_int_t brix_sd_cache_demote (brix_sd_instance_t * inst, const char * key)
Definition at line 633 of file sd_cache_fill.c.
References brix_sd_cache_instance_is(), BRIX_SD_O_READ, brix_sd_obj_release(), sd_cache_inst_state::cold, sd_cache_inst_state::cstore, key, SD_CACHE_CHUNK, SD_CACHE_ST, and brix_cstore_t::store.
Referenced by brix_cache_evict_one().
cache_fill_acquire()
static ngx_int_t cache_fill_acquire (sd_cache_inst_state * st, const char * key, const brix_sd_cred_t * cred, sd_cache_fill_state_t * fs) static
Definition at line 90 of file sd_cache_fill.c.
References brix_cstore_fill_abort(), brix_cstore_fill_open(), BRIX_SD_O_READ, brix_sd_obj_release(), brix_sd_open_maybe_cred(), sd_cache_fill_state_t::buf, sd_cache_inst_state::cstore, sd_cache_fill_state_t::from_cold, sd_cache_fill_state_t::from_peer, key, sd_cache_inst_state::log, sd_cache_inst_state::policy, sd_cache_admit(), SD_CACHE_CHUNK, sd_cache_stale_serve_ok(), brix_sd_stat_t::size, sd_cache_fill_state_t::snap, sd_cache_fill_state_t::so, sd_cache_fill_state_t::src, and sd_cache_fill_state_t::staged.
Referenced by sd_cache_fill_attempt().
cache_fill_commit()
static ngx_int_t cache_fill_commit (sd_cache_inst_state * st, const char * key, sd_cache_fill_state_t * fs) static
Definition at line 427 of file sd_cache_fill.c.
References brix_cache_cinfo_t::block_size, BRIX_CACHE_CINFO_MAGIC, brix_cache_cinfo_nblocks(), brix_cache_cinfo_set_expires(), BRIX_CACHE_CINFO_VERSION, BRIX_CACHE_DIRTY_BLOCK, BRIX_CINFO_F_COMPLETE, BRIX_CINFO_F_VERIFIED, brix_cstore_cinfo_store(), brix_cstore_fill_commit(), sd_cache_inst_state::cstore, brix_cache_policy_t::cvmfs_manifest_ttl, brix_cache_cinfo_t::filled_at, brix_cache_cinfo_t::flags, sd_cache_fill_state_t::from_cold, sd_cache_fill_state_t::from_peer, key, sd_cache_inst_state::log, brix_cache_cinfo_t::magic, brix_sd_stat_t::mode, brix_cache_cinfo_t::mode, brix_sd_stat_t::mtime, brix_cache_cinfo_t::mtime, brix_cache_cinfo_t::nblocks, sd_cache_fill_state_t::off, sd_cache_inst_state::policy, sd_cache_is_manifest_key(), sd_cache_ms_since(), sd_cache_note_origin_bytes(), sd_cache_note_upstream(), brix_cache_cinfo_t::size, sd_cache_fill_state_t::snap, sd_cache_fill_state_t::staged, sd_cache_fill_state_t::t0, sd_cache_fill_state_t::verified, and brix_cache_cinfo_t::version.
Referenced by sd_cache_fill_attempt().
cache_fill_pump()
static ngx_int_t cache_fill_pump (sd_cache_inst_state * st, const char * key, sd_cache_fill_state_t * fs) static
Definition at line 181 of file sd_cache_fill.c.
References brix_cstore_fill_abort(), brix_cstore_fill_write(), brix_sd_obj_release(), sd_cache_fill_state_t::buf, sd_cache_fill_state_t::from_cold, sd_cache_fill_state_t::from_peer, key, sd_cache_fill_state_t::off, SD_CACHE_CHUNK, sd_cache_stale_serve_ok(), brix_sd_stat_t::size, sd_cache_fill_state_t::snap, sd_cache_fill_state_t::so, and sd_cache_fill_state_t::staged.
Referenced by sd_cache_fill_attempt().
cache_fill_verify()
static ngx_int_t cache_fill_verify (sd_cache_inst_state * st, const char * key, sd_cache_fill_state_t * fs) static
Definition at line 363 of file sd_cache_fill.c.
References brix_cache_verify_cvmfs_cas(), BRIX_CACHE_VERIFY_CVMFS_CAS, BRIX_CACHE_VERIFY_ERROR, BRIX_CACHE_VERIFY_MISMATCH, BRIX_CACHE_VERIFY_VERIFIED, brix_cstore_fill_abort(), cache_fill_verify_reject(), brix_cache_policy_t::cvmfs_master_pub, key, sd_cache_inst_state::log, sd_cache_inst_state::policy, sd_cache_verify_manifest(), sd_cache_fill_state_t::staged, sd_cache_fill_state_t::verified, and brix_cache_policy_t::verify.
Referenced by sd_cache_fill_attempt().
cache_fill_verify_reject()
static ngx_int_t cache_fill_verify_reject (sd_cache_inst_state * st, const char * key, sd_cache_fill_state_t * fs, const char * pp) static
Definition at line 295 of file sd_cache_fill.c.
References BRIX_ATOMIC_INC, brix_cache_quarantine_part(), brix_cstore_fill_abort(), BRIX_CVMFS_METRIC_INC, sd_cache_fill_state_t::from_cold, sd_cache_fill_state_t::from_peer, key, sd_cache_inst_state::log, sd_cache_fill_state_t::off, sd_cache_inst_state::policy, brix_cache_policy_t::quarantine_dir, sd_cache_guard_tamper(), sd_cache_ms_since(), sd_cache_note_origin_bytes(), sd_cache_note_upstream(), sd_cache_repo_metrics(), sd_http_penalize_last_origin(), sd_cache_inst_state::source, sd_cache_fill_state_t::src, sd_cache_fill_state_t::staged, sd_cache_fill_state_t::t0, and ngx_brix_cvmfs_repo_metrics_t::verify_failures_total.
Referenced by cache_fill_verify().
sd_cache_fill()
ngx_int_t sd_cache_fill (sd_cache_inst_state * st, const char * key, const brix_sd_cred_t * cred)
Definition at line 578 of file sd_cache_fill.c.
References sd_cache_inst_state::cold, brix_sd_cache_peer_t::inst, key, brix_sd_cache_peer_t::label, sd_cache_inst_state::log, sd_cache_inst_state::n_peers, sd_cache_inst_state::peer_self, sd_cache_inst_state::peers, sd_cache_fill_attempt(), sd_cache_peer_owner(), and sd_cache_inst_state::source.
Referenced by brix_sd_cache_fill_key(), and cache_open_miss_serve().
sd_cache_fill_attempt()
static ngx_int_t sd_cache_fill_attempt (sd_cache_inst_state * st, const char * key, const brix_sd_cred_t * cred, brix_sd_instance_t * src, int from_cold, int from_peer) static
Definition at line 478 of file sd_cache_fill.c.
References cache_fill_acquire(), cache_fill_commit(), cache_fill_pump(), cache_fill_verify(), sd_cache_fill_state_t::from_cold, sd_cache_fill_state_t::from_peer, key, sd_cache_fill_state_t::src, and sd_cache_fill_state_t::t0.
Referenced by sd_cache_fill().
sd_cache_guard_tamper()
void sd_cache_guard_tamper (sd_cache_inst_state * st, brix_sd_instance_t * actor, const char * key)
Definition at line 245 of file sd_cache_fill.c.
References brix_sanitize_log_string(), guard_request_t::cred_present, guard_audit_format(), GUARD_OP_READ, GUARD_R_TAMPER, guard_request_t::ip, key, sd_cache_inst_state::log, guard_request_t::op, guard_request_t::outcome, OUTCOME_PENDING, guard_request_t::path, guard_request_t::path_len, guard_request_t::proto, sd_http_last_origin(), sd_cache_inst_state::source, and guard_request_t::status_code.
Referenced by cache_fill_verify_reject().
sd_cache_hrw_fnv1a64()
static uint64_t sd_cache_hrw_fnv1a64 (const char * label, const char * key) static
Definition at line 521 of file sd_cache_fill.c.
References key.
Referenced by sd_cache_peer_owner().
sd_cache_peer_owner()
static int sd_cache_peer_owner (const sd_cache_inst_state * st, const char * key) static
Definition at line 537 of file sd_cache_fill.c.
References key, brix_sd_cache_peer_t::label, sd_cache_inst_state::n_peers, sd_cache_inst_state::peers, and sd_cache_hrw_fnv1a64().
Referenced by sd_cache_fill().