nginx-xrootd: src/fs/backend/cache/sd_cache_internal.h File Reference
sd_cache_internal.h File Reference
#include "fs/backend/sd.h"
#include "fs/backend/cache/sd_cache.h"
#include "fs/cache/cstore.h"
#include "fs/tier/tier.h"
Data Structures
struct sd_cache_inst_state
Macros
#define SD_CACHE_ST(inst) ((sd_cache_inst_state *) (inst)->state)
#define SD_CACHE_SRC(inst) (SD_CACHE_ST(inst)->source)
Functions
ngx_int_t sd_cache_fill (sd_cache_inst_state *st, const char *key, const brix_sd_cred_t *cred)
void sd_cache_guard_tamper (sd_cache_inst_state *st, brix_sd_instance_t *actor, const char *key)
ngx_int_t sd_cache_verify_manifest (sd_cache_inst_state *st, const char *key, const char *pp)
brix_sd_obj_t * sd_cache_partial_open (brix_sd_instance_t *inst, sd_cache_inst_state *st, const char *key, const brix_sd_cred_t *cred, int *err_out)
ssize_t sd_cache_pread (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
ngx_int_t sd_cache_close (brix_sd_obj_t *obj)
ngx_int_t sd_cache_fstat (brix_sd_obj_t *obj, brix_sd_stat_t *out)
ngx_fd_t sd_cache_read_sendfile_fd (brix_sd_obj_t *obj, off_t off, size_t len, unsigned want_zerocopy)
ngx_int_t sd_cache_stat (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out)
ngx_int_t sd_cache_unlink (brix_sd_instance_t *inst, const char *path, int is_dir)
ngx_int_t sd_cache_mkdir (brix_sd_instance_t *inst, const char *path, mode_t mode)
ngx_int_t sd_cache_rename (brix_sd_instance_t *inst, const char *src, const char *dst, int noreplace)
ngx_int_t sd_cache_server_copy (brix_sd_instance_t *inst, const char *src, const char *dst, off_t *bytes_out)
ngx_int_t sd_cache_setattr (brix_sd_instance_t *inst, const char *path, const brix_sd_setattr_t *attr)
brix_sd_dir_t * sd_cache_opendir (brix_sd_instance_t *inst, const char *path, int *err_out)
ngx_int_t sd_cache_readdir (brix_sd_dir_t *d, brix_sd_dirent_t *out)
ngx_int_t sd_cache_closedir (brix_sd_dir_t *d)
ssize_t sd_cache_getxattr (brix_sd_instance_t *inst, const char *path, const char *name, void *buf, size_t cap)
ssize_t sd_cache_listxattr (brix_sd_instance_t *inst, const char *path, void *buf, size_t cap)
ngx_int_t sd_cache_setxattr (brix_sd_instance_t *inst, const char *path, const char *name, const void *val, size_t len, int flags)
ngx_int_t sd_cache_removexattr (brix_sd_instance_t *inst, const char *path, const char *name)
brix_sd_staged_t * sd_cache_staged_open (brix_sd_instance_t *inst, const char *final_path, mode_t mode, int *err_out)
brix_sd_staged_t * sd_cache_staged_open_cred (brix_sd_instance_t *inst, const char *final_path, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
ssize_t sd_cache_staged_write (brix_sd_staged_t *st, const void *buf, size_t len, off_t off)
ngx_int_t sd_cache_staged_commit (brix_sd_staged_t *st, int noreplace)
void sd_cache_staged_abort (brix_sd_staged_t *st)
Macro Definition Documentation
SD_CACHE_SRC
#define SD_CACHE_SRC (inst) (SD_CACHE_ST(inst)->source)
Definition at line 40 of file sd_cache_internal.h.
SD_CACHE_ST
#define SD_CACHE_ST (inst) ((sd_cache_inst_state *) (inst)->state)
Definition at line 39 of file sd_cache_internal.h.
Function Documentation
sd_cache_close()
ngx_int_t sd_cache_close (brix_sd_obj_t * obj)
Definition at line 374 of file sd_cache_partial.c.
References sd_cache_partial_t::bitmap, brix_sd_obj_release(), sd_cache_partial_t::cache_fd, close(), and sd_cache_partial_t::src_obj.
sd_cache_closedir()
ngx_int_t sd_cache_closedir (brix_sd_dir_t * d)
Definition at line 151 of file sd_cache_forward.c.
sd_cache_fill()
ngx_int_t sd_cache_fill (sd_cache_inst_state * st, const char * key, const brix_sd_cred_t * cred)
Definition at line 735 of file sd_cache_fill.c.
References sd_cache_inst_state::cold, brix_sd_cache_peer_t::inst, key, brix_sd_cache_peer_t::label, sd_cache_inst_state::log, sd_cache_inst_state::n_peers, sd_cache_inst_state::peer_self, sd_cache_inst_state::peers, sd_cache_fill_attempt(), sd_cache_peer_owner(), and sd_cache_inst_state::source.
Referenced by brix_sd_cache_fill_key(), and cache_open_miss_serve().
sd_cache_fstat()
ngx_int_t sd_cache_fstat (brix_sd_obj_t * obj, brix_sd_stat_t * out)
Definition at line 398 of file sd_cache_partial.c.
References brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, sd_cache_partial_t::mtime, brix_sd_stat_t::mtime, sd_cache_partial_t::size, and brix_sd_stat_t::size.
sd_cache_getxattr()
ssize_t sd_cache_getxattr (brix_sd_instance_t * inst, const char * path, const char * name, void * buf, size_t cap)
Definition at line 157 of file sd_cache_forward.c.
References name, s, and SD_CACHE_SRC.
sd_cache_guard_tamper()
void sd_cache_guard_tamper (sd_cache_inst_state * st, brix_sd_instance_t * actor, const char * key)
Definition at line 291 of file sd_cache_fill.c.
References brix_sanitize_log_string(), guard_request_t::cred_present, guard_audit_format(), GUARD_OP_READ, GUARD_R_TAMPER, guard_request_t::ip, key, sd_cache_inst_state::log, guard_request_t::op, guard_request_t::outcome, OUTCOME_PENDING, guard_request_t::path, guard_request_t::path_len, guard_request_t::proto, sd_http_last_origin(), sd_cache_inst_state::source, and guard_request_t::status_code.
Referenced by cache_fill_verify_reject().
sd_cache_listxattr()
ssize_t sd_cache_listxattr (brix_sd_instance_t * inst, const char * path, void * buf, size_t cap)
Definition at line 170 of file sd_cache_forward.c.
References s, and SD_CACHE_SRC.
sd_cache_mkdir()
ngx_int_t sd_cache_mkdir (brix_sd_instance_t * inst, const char * path, mode_t mode)
Definition at line 88 of file sd_cache_forward.c.
References s, and SD_CACHE_SRC.
sd_cache_opendir()
brix_sd_dir_t * sd_cache_opendir (brix_sd_instance_t * inst, const char * path, int * err_out)
Definition at line 129 of file sd_cache_forward.c.
References s, and SD_CACHE_SRC.
sd_cache_partial_open()
brix_sd_obj_t * sd_cache_partial_open (brix_sd_instance_t * inst, sd_cache_inst_state * st, const char * key, const brix_sd_cred_t * cred, int * err_out)
Definition at line 282 of file sd_cache_partial.c.
References sd_cache_partial_t::bitmap_len, sd_cache_partial_t::block_size, brix_cache_cinfo_bitmap_len(), brix_cache_cinfo_nblocks(), brix_cstore_partial_open(), sd_cache_partial_t::cache_fd, sd_cache_partial_t::cache_path, close(), sd_cache_inst_state::cstore, sd_cache_partial_t::key, key, sd_cache_inst_state::log, sd_cache_partial_t::log, sd_cache_partial_t::mode, brix_sd_stat_t::mode, sd_cache_partial_t::mtime, brix_sd_stat_t::mtime, sd_cache_partial_t::nblocks, partial_adopt_bitmap(), partial_capture_cred(), PATH_MAX, sd_cache_inst_state::policy, sd_cache_partial_t::size, brix_sd_stat_t::size, brix_cache_policy_t::slice_size, sd_cache_inst_state::source, and sd_cache_partial_t::source.
Referenced by cache_open_miss_serve().
sd_cache_pread()
ssize_t sd_cache_pread (brix_sd_obj_t * obj, void * buf, size_t len, off_t off)
Definition at line 359 of file sd_cache_partial.c.
References sd_cache_partial_t::bitmap, sd_cache_partial_t::block_size, brix_cstore_serve_pread(), sd_cache_partial_t::cache_fd, sd_cache_partial_t::nblocks, sd_cache_fill_block_cb(), and sd_cache_partial_t::size.
sd_cache_read_sendfile_fd()
ngx_fd_t sd_cache_read_sendfile_fd (brix_sd_obj_t * obj, off_t off, size_t len, unsigned want_zerocopy)
Definition at line 414 of file sd_cache_partial.c.
sd_cache_readdir()
ngx_int_t sd_cache_readdir (brix_sd_dir_t * d, brix_sd_dirent_t * out)
Definition at line 143 of file sd_cache_forward.c.
sd_cache_removexattr()
ngx_int_t sd_cache_removexattr (brix_sd_instance_t * inst, const char * path, const char * name)
Definition at line 196 of file sd_cache_forward.c.
References name, s, and SD_CACHE_SRC.
sd_cache_rename()
ngx_int_t sd_cache_rename (brix_sd_instance_t * inst, const char * src, const char * dst, int noreplace)
Definition at line 95 of file sd_cache_forward.c.
References brix_cstore_evict(), sd_cache_inst_state::cstore, s, SD_CACHE_ST, and sd_cache_inst_state::source.
sd_cache_server_copy()
ngx_int_t sd_cache_server_copy (brix_sd_instance_t * inst, const char * src, const char * dst, off_t * bytes_out)
Definition at line 112 of file sd_cache_forward.c.
References s, and SD_CACHE_SRC.
sd_cache_setattr()
ngx_int_t sd_cache_setattr (brix_sd_instance_t * inst, const char * path, const brix_sd_setattr_t * attr)
Definition at line 121 of file sd_cache_forward.c.
References s, and SD_CACHE_SRC.
sd_cache_setxattr()
ngx_int_t sd_cache_setxattr (brix_sd_instance_t * inst, const char * path, const char * name, const void * val, size_t len, int flags)
Definition at line 183 of file sd_cache_forward.c.
References name, s, and SD_CACHE_SRC.
sd_cache_staged_abort()
void sd_cache_staged_abort (brix_sd_staged_t * st)
Definition at line 272 of file sd_cache_forward.c.
sd_cache_staged_commit()
ngx_int_t sd_cache_staged_commit (brix_sd_staged_t * st, int noreplace)
Definition at line 265 of file sd_cache_forward.c.
sd_cache_staged_open()
brix_sd_staged_t * sd_cache_staged_open (brix_sd_instance_t * inst, const char * final_path, mode_t mode, int * err_out)
Definition at line 211 of file sd_cache_forward.c.
References brix_cstore_evict(), sd_cache_inst_state::cstore, s, SD_CACHE_ST, and sd_cache_inst_state::source.
sd_cache_staged_open_cred()
brix_sd_staged_t * sd_cache_staged_open_cred (brix_sd_instance_t * inst, const char * final_path, mode_t mode, const brix_sd_cred_t * cred, int * err_out)
Definition at line 240 of file sd_cache_forward.c.
References brix_cstore_evict(), brix_sd_staged_open_maybe_cred(), sd_cache_inst_state::cstore, s, SD_CACHE_ST, and sd_cache_inst_state::source.
sd_cache_staged_write()
ssize_t sd_cache_staged_write (brix_sd_staged_t * st, const void * buf, size_t len, off_t off)
Definition at line 257 of file sd_cache_forward.c.
sd_cache_stat()
ngx_int_t sd_cache_stat (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out)
Definition at line 45 of file sd_cache_forward.c.
References BRIX_CINFO_F_COMPLETE, brix_cstore_cinfo_load(), sd_cache_inst_state::cstore, brix_sd_stat_t::ctime, brix_cache_cinfo_t::flags, brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, brix_cache_cinfo_t::mode, brix_sd_stat_t::mtime, brix_cache_cinfo_t::mtime, s, SD_CACHE_SRC, SD_CACHE_ST, brix_sd_stat_t::size, and brix_cache_cinfo_t::size.
sd_cache_unlink()
ngx_int_t sd_cache_unlink (brix_sd_instance_t * inst, const char * path, int is_dir)
Definition at line 74 of file sd_cache_forward.c.
References brix_cstore_evict(), sd_cache_inst_state::cstore, s, SD_CACHE_ST, and sd_cache_inst_state::source.
sd_cache_verify_manifest()
ngx_int_t sd_cache_verify_manifest (sd_cache_inst_state * st, const char * key, const char * pp)
Definition at line 282 of file sd_cache_manifest.c.
References brix_cache_policy_t::cvmfs_master_pub, brix_cache_policy_t::cvmfs_master_pub_len, key, sd_cache_inst_state::log, meta_check_manifest(), meta_check_whitelist(), meta_read_part(), and sd_cache_inst_state::policy.
Referenced by cache_fill_verify().