nginx-xrootd: src/fs/backend/pblock/sd_pblock_unittest_core.c File Reference
sd_pblock_unittest_core.c File Reference
#include "fs/backend/sd.h"
#include "sd_pblock_catalog.h"
#include "sd_pblock_unittest_internal.h"
#include <errno.h>
#include <ftw.h>
#include <limits.h>
#include <pthread.h>
#include <sqlite3.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>
Data Structures
struct thread_arg
Macros
#define _GNU_SOURCE /* nftw(3) + FTW_PHYS for the on-disk block scan */
Functions
void test_write_read_fstat (brix_sd_instance_t *inst)
void test_truncate_and_stat (brix_sd_instance_t *inst)
void test_preadv (brix_sd_instance_t *inst)
void test_dirs (brix_sd_instance_t *inst)
void test_rename (brix_sd_instance_t *inst)
void test_server_copy (brix_sd_instance_t *inst)
void test_xattr (brix_sd_instance_t *inst)
void test_staged (brix_sd_instance_t *inst)
void test_unlink (brix_sd_instance_t *inst)
void test_fsync_durability (const char *root)
static void * thread_body (void *p)
void test_threads (brix_sd_instance_t *inst)
void test_processes (const char *root, brix_sd_instance_t *inst)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE /* nftw(3) + FTW_PHYS for the on-disk block scan */
Definition at line 8 of file sd_pblock_unittest_core.c.
Function Documentation
test_dirs()
void test_dirs (brix_sd_instance_t * inst)
Definition at line 101 of file sd_pblock_unittest_core.c.
References CHECK, D, brix_sd_dirent_t::name, and write_file().
Referenced by main().
test_fsync_durability()
void test_fsync_durability (const char * root)
Definition at line 235 of file sd_pblock_unittest_core.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, D, pb_close(), and brix_sd_stat_t::size.
Referenced by main().
test_preadv()
void test_preadv (brix_sd_instance_t * inst)
Definition at line 82 of file sd_pblock_unittest_core.c.
References BRIX_SD_O_READ, CHECK, D, pb_close(), and write_file().
Referenced by main().
test_processes()
void test_processes (const char * root, brix_sd_instance_t * inst)
Definition at line 332 of file sd_pblock_unittest_core.c.
References CHECK, D, and write_file().
Referenced by main().
test_rename()
void test_rename (brix_sd_instance_t * inst)
Definition at line 127 of file sd_pblock_unittest_core.c.
References CHECK, D, read_file(), and write_file().
Referenced by main().
test_server_copy()
void test_server_copy (brix_sd_instance_t * inst)
Definition at line 151 of file sd_pblock_unittest_core.c.
References CHECK, D, read_file(), and write_file().
Referenced by main().
test_staged()
void test_staged (brix_sd_instance_t * inst)
Definition at line 184 of file sd_pblock_unittest_core.c.
References CHECK, D, read_file(), s, and brix_sd_stat_t::size.
Referenced by main().
test_threads()
void test_threads (brix_sd_instance_t * inst)
Definition at line 306 of file sd_pblock_unittest_core.c.
References CHECK, D, thread_arg::id, thread_arg::inst, thread_arg::ok, thread_arg::ops, and thread_body().
Referenced by main().
test_truncate_and_stat()
void test_truncate_and_stat (brix_sd_instance_t * inst)
Definition at line 59 of file sd_pblock_unittest_core.c.
References BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, D, pb_close(), brix_sd_stat_t::size, and write_file().
Referenced by main().
test_unlink()
void test_unlink (brix_sd_instance_t * inst)
Definition at line 214 of file sd_pblock_unittest_core.c.
References CHECK, D, and write_file().
Referenced by main().
test_write_read_fstat()
void test_write_read_fstat (brix_sd_instance_t * inst)
Definition at line 30 of file sd_pblock_unittest_core.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, D, brix_sd_stat_t::is_reg, pb_close(), read_file(), and brix_sd_stat_t::size.
Referenced by main().
test_xattr()
void test_xattr (brix_sd_instance_t * inst)
Definition at line 166 of file sd_pblock_unittest_core.c.
References CHECK, D, and write_file().
thread_body()
static void * thread_body (void * p) static
Definition at line 280 of file sd_pblock_unittest_core.c.
References thread_arg::id, thread_arg::inst, thread_arg::ok, thread_arg::ops, read_file(), and write_file().
Referenced by test_threads().