nginx-xrootd: src/fs/backend/stage/sd_stage.c File Reference
sd_stage.c File Reference
#include "sd_stage.h"
#include "fs/xfer/stage_engine.h"
#include <errno.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct sd_stage_inst_state
struct sd_stage_staged_state
struct sd_stage_wb_state
Macros
#define SD_STAGE_SRC(inst) (((sd_stage_inst_state *) (inst)->state)->source)
Functions
static brix_sd_obj_t * sd_stage_open_writeback (brix_sd_instance_t *inst, sd_stage_inst_state *is, const char *path, int sd_flags, mode_t mode, int *err_out)
static brix_sd_obj_t * sd_stage_open (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, int *err_out)
static ngx_int_t sd_stage_wb_flush (sd_stage_wb_state *wb)
static ssize_t sd_stage_wb_pwrite (brix_sd_obj_t *obj, const void *buf, size_t len, off_t off)
static ssize_t sd_stage_wb_pread (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
static ngx_int_t sd_stage_wb_ftruncate (brix_sd_obj_t *obj, off_t length)
static ngx_int_t sd_stage_wb_fstat (brix_sd_obj_t *obj, brix_sd_stat_t *out)
static ngx_int_t sd_stage_wb_fsync (brix_sd_obj_t *obj)
static ngx_int_t sd_stage_wb_close (brix_sd_obj_t *obj)
static ngx_int_t sd_stage_stat (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out)
static ngx_int_t sd_stage_unlink (brix_sd_instance_t *inst, const char *path, int is_dir)
static ngx_int_t sd_stage_mkdir (brix_sd_instance_t *inst, const char *path, mode_t mode)
static ngx_int_t sd_stage_rename (brix_sd_instance_t *inst, const char *src, const char *dst, int noreplace)
static ngx_int_t sd_stage_server_copy (brix_sd_instance_t *inst, const char *src, const char *dst, off_t *bytes_out)
static ngx_int_t sd_stage_setattr (brix_sd_instance_t *inst, const char *path, const brix_sd_setattr_t *attr)
static brix_sd_dir_t * sd_stage_opendir (brix_sd_instance_t *inst, const char *path, int *err_out)
static ngx_int_t sd_stage_readdir (brix_sd_dir_t *d, brix_sd_dirent_t *out)
static ngx_int_t sd_stage_closedir (brix_sd_dir_t *d)
static ssize_t sd_stage_getxattr (brix_sd_instance_t *inst, const char *path, const char *name, void *buf, size_t cap)
static ssize_t sd_stage_listxattr (brix_sd_instance_t *inst, const char *path, void *buf, size_t cap)
static ngx_int_t sd_stage_setxattr (brix_sd_instance_t *inst, const char *path, const char *name, const void *val, size_t len, int flags)
static ngx_int_t sd_stage_removexattr (brix_sd_instance_t *inst, const char *path, const char *name)
static brix_sd_staged_t * sd_stage_staged_open (brix_sd_instance_t *inst, const char *final_path, mode_t mode, int *err_out)
static ssize_t sd_stage_staged_write (brix_sd_staged_t *st, const void *buf, size_t len, off_t off)
static ngx_int_t sd_stage_staged_commit (brix_sd_staged_t *st, int noreplace)
static void sd_stage_staged_abort (brix_sd_staged_t *st)
brix_sd_instance_t * brix_sd_stage_create (brix_sd_instance_t *source, brix_sd_instance_t *store, const brix_stage_policy_t *policy, const char *root_canon, ngx_log_t *log)
void brix_sd_stage_destroy (brix_sd_instance_t *inst)
int brix_sd_stage_instance_is (const brix_sd_instance_t *inst)
brix_sd_instance_t * brix_sd_stage_source_instance (const brix_sd_instance_t *inst)
brix_sd_instance_t * brix_sd_stage_store_instance (const brix_sd_instance_t *inst)
ngx_int_t brix_sd_stage_reflush (brix_sd_instance_t *inst, const char *key)
Variables
static const brix_sd_driver_t brix_sd_stage_driver
Macro Definition Documentation
SD_STAGE_SRC
#define SD_STAGE_SRC (inst) (((sd_stage_inst_state *) (inst)->state)->source)
Definition at line 46 of file sd_stage.c.
Function Documentation
brix_sd_stage_create()
brix_sd_instance_t * brix_sd_stage_create (brix_sd_instance_t * source, brix_sd_instance_t * store, const brix_stage_policy_t * policy, const char * root_canon, ngx_log_t * log)
Definition at line 479 of file sd_stage.c.
References brix_sd_stage_driver, BRIX_WT_MODE_SYNC, brix_stage_policy_t::flush_mode, log, sd_stage_inst_state::log, sd_stage_inst_state::policy, sd_stage_inst_state::root_canon, sd_stage_inst_state::source, and sd_stage_inst_state::store.
Referenced by brix_tier_build_stack(), brix_vfs_backend_entry_build(), and cache_build_wt_stage().
brix_sd_stage_destroy()
void brix_sd_stage_destroy (brix_sd_instance_t * inst)
Definition at line 519 of file sd_stage.c.
Referenced by brix_cache_storage_cleanup().
brix_sd_stage_instance_is()
int brix_sd_stage_instance_is (const brix_sd_instance_t * inst)
Definition at line 530 of file sd_stage.c.
References brix_sd_stage_driver.
Referenced by brix_sd_stage_reflush(), brix_sd_stage_source_instance(), brix_sd_stage_store_instance(), and stage_reconcile_one().
brix_sd_stage_reflush()
ngx_int_t brix_sd_stage_reflush (brix_sd_instance_t * inst, const char * key)
Definition at line 557 of file sd_stage.c.
References brix_sd_stage_instance_is(), BRIX_STAGE_FLUSH, brix_stage_run_inline(), key, sd_stage_inst_state::source, and sd_stage_inst_state::store.
Referenced by stage_reconcile_one().
brix_sd_stage_source_instance()
brix_sd_instance_t * brix_sd_stage_source_instance (const brix_sd_instance_t * inst)
Definition at line 539 of file sd_stage.c.
References brix_sd_stage_instance_is(), and SD_STAGE_SRC.
Referenced by brix_cache_storage_cleanup(), and brix_vfs_decorator_source().
brix_sd_stage_store_instance()
brix_sd_instance_t * brix_sd_stage_store_instance (const brix_sd_instance_t * inst)
Definition at line 546 of file sd_stage.c.
References brix_sd_stage_instance_is().
sd_stage_closedir()
static ngx_int_t sd_stage_closedir (brix_sd_dir_t * d) static
Definition at line 280 of file sd_stage.c.
sd_stage_getxattr()
static ssize_t sd_stage_getxattr (brix_sd_instance_t * inst, const char * path, const char * name, void * buf, size_t cap) static
Definition at line 286 of file sd_stage.c.
References name, s, and SD_STAGE_SRC.
sd_stage_listxattr()
static ssize_t sd_stage_listxattr (brix_sd_instance_t * inst, const char * path, void * buf, size_t cap) static
Definition at line 295 of file sd_stage.c.
References s, and SD_STAGE_SRC.
sd_stage_mkdir()
static ngx_int_t sd_stage_mkdir (brix_sd_instance_t * inst, const char * path, mode_t mode) static
Definition at line 229 of file sd_stage.c.
References mode, s, and SD_STAGE_SRC.
sd_stage_open()
static brix_sd_obj_t * sd_stage_open (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, int * err_out) static
Definition at line 104 of file sd_stage.c.
References BRIX_SD_O_WRITE, mode, sd_stage_open_writeback(), and sd_stage_inst_state::source.
sd_stage_open_writeback()
static brix_sd_obj_t * sd_stage_open_writeback (brix_sd_instance_t * inst, sd_stage_inst_state * is, const char * path, int sd_flags, mode_t mode, int * err_out) static
Definition at line 57 of file sd_stage.c.
References brix_sd_stage_driver, sd_stage_wb_state::dirty, sd_stage_wb_state::high_water, sd_stage_wb_state::is, sd_stage_wb_state::key, mode, sd_stage_inst_state::store, and sd_stage_wb_state::store_obj.
Referenced by sd_stage_open().
sd_stage_opendir()
static brix_sd_dir_t * sd_stage_opendir (brix_sd_instance_t * inst, const char * path, int * err_out) static
Definition at line 262 of file sd_stage.c.
References s, and SD_STAGE_SRC.
sd_stage_readdir()
static ngx_int_t sd_stage_readdir (brix_sd_dir_t * d, brix_sd_dirent_t * out) static
Definition at line 273 of file sd_stage.c.
sd_stage_removexattr()
static ngx_int_t sd_stage_removexattr (brix_sd_instance_t * inst, const char * path, const char * name) static
Definition at line 313 of file sd_stage.c.
References name, s, and SD_STAGE_SRC.
sd_stage_rename()
static ngx_int_t sd_stage_rename (brix_sd_instance_t * inst, const char * src, const char * dst, int noreplace) static
Definition at line 236 of file sd_stage.c.
References s, and SD_STAGE_SRC.
sd_stage_server_copy()
static ngx_int_t sd_stage_server_copy (brix_sd_instance_t * inst, const char * src, const char * dst, off_t * bytes_out) static
Definition at line 245 of file sd_stage.c.
References s, and SD_STAGE_SRC.
sd_stage_setattr()
static ngx_int_t sd_stage_setattr (brix_sd_instance_t * inst, const char * path, const brix_sd_setattr_t * attr) static
Definition at line 254 of file sd_stage.c.
References s, and SD_STAGE_SRC.
sd_stage_setxattr()
static ngx_int_t sd_stage_setxattr (brix_sd_instance_t * inst, const char * path, const char * name, const void * val, size_t len, int flags) static
Definition at line 304 of file sd_stage.c.
References name, s, and SD_STAGE_SRC.
sd_stage_staged_abort()
static void sd_stage_staged_abort (brix_sd_staged_t * st) static
Definition at line 431 of file sd_stage.c.
References sd_stage_staged_state::inner, sd_stage_staged_state::is, and sd_stage_inst_state::store.
sd_stage_staged_commit()
static ngx_int_t sd_stage_staged_commit (brix_sd_staged_t * st, int noreplace) static
Definition at line 378 of file sd_stage.c.
References brix_stage_opts_t::async, BRIX_STAGE_FLUSH, brix_stage_run_inline(), brix_stage_submit(), BRIX_WT_MODE_ASYNC, brix_stage_opts_t::export_root, brix_stage_policy_t::flush_mode, sd_stage_staged_state::inner, sd_stage_staged_state::is, sd_stage_staged_state::key, sd_stage_inst_state::policy, sd_stage_inst_state::root_canon, sd_stage_inst_state::source, and sd_stage_inst_state::store.
sd_stage_staged_open()
static brix_sd_staged_t * sd_stage_staged_open (brix_sd_instance_t * inst, const char * final_path, mode_t mode, int * err_out) static
Definition at line 324 of file sd_stage.c.
References sd_stage_staged_state::inner, sd_stage_staged_state::is, sd_stage_staged_state::key, mode, and sd_stage_inst_state::store.
sd_stage_staged_write()
static ssize_t sd_stage_staged_write (brix_sd_staged_t * st, const void * buf, size_t len, off_t off) static
Definition at line 363 of file sd_stage.c.
References sd_stage_staged_state::inner.
sd_stage_stat()
static ngx_int_t sd_stage_stat (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out) static
Definition at line 215 of file sd_stage.c.
References s, and SD_STAGE_SRC.
sd_stage_unlink()
static ngx_int_t sd_stage_unlink (brix_sd_instance_t * inst, const char * path, int is_dir) static
Definition at line 222 of file sd_stage.c.
References s, and SD_STAGE_SRC.
sd_stage_wb_close()
static ngx_int_t sd_stage_wb_close (brix_sd_obj_t * obj) static
Definition at line 199 of file sd_stage.c.
References sd_stage_wb_state::dirty, sd_stage_wb_flush(), and sd_stage_wb_state::store_obj.
sd_stage_wb_flush()
static ngx_int_t sd_stage_wb_flush (sd_stage_wb_state * wb) static
Definition at line 124 of file sd_stage.c.
References BRIX_STAGE_FLUSH, brix_stage_run_inline(), sd_stage_wb_state::dirty, sd_stage_wb_state::is, sd_stage_wb_state::key, sd_stage_inst_state::source, sd_stage_inst_state::store, and sd_stage_wb_state::store_obj.
Referenced by sd_stage_wb_close(), and sd_stage_wb_fsync().
sd_stage_wb_fstat()
static ngx_int_t sd_stage_wb_fstat (brix_sd_obj_t * obj, brix_sd_stat_t * out) static
Definition at line 185 of file sd_stage.c.
References sd_stage_wb_state::store_obj.
sd_stage_wb_fsync()
static ngx_int_t sd_stage_wb_fsync (brix_sd_obj_t * obj) static
Definition at line 193 of file sd_stage.c.
References sd_stage_wb_flush().
sd_stage_wb_ftruncate()
static ngx_int_t sd_stage_wb_ftruncate (brix_sd_obj_t * obj, off_t length) static
Definition at line 167 of file sd_stage.c.
References sd_stage_wb_state::dirty, sd_stage_wb_state::high_water, and sd_stage_wb_state::store_obj.
sd_stage_wb_pread()
static ssize_t sd_stage_wb_pread (brix_sd_obj_t * obj, void * buf, size_t len, off_t off) static
Definition at line 159 of file sd_stage.c.
References sd_stage_wb_state::store_obj.
sd_stage_wb_pwrite()
static ssize_t sd_stage_wb_pwrite (brix_sd_obj_t * obj, const void * buf, size_t len, off_t off) static
Definition at line 144 of file sd_stage.c.
References sd_stage_wb_state::dirty, sd_stage_wb_state::high_water, and sd_stage_wb_state::store_obj.
Variable Documentation
brix_sd_stage_driver
static const brix_sd_driver_t brix_sd_stage_driver static
Definition at line 48 of file sd_stage.c.
Referenced by brix_sd_stage_create(), brix_sd_stage_instance_is(), and sd_stage_open_writeback().