nginx-xrootd: src/fs/backend/cache/sd_cache_policy.h File Reference
sd_cache_policy.h File Reference
#include "sd_cache_internal.h"
#include "observability/metrics/metrics.h"
#include <time.h>
Functions
int sd_cache_admit (const brix_cache_policy_t *pol, const char *path, off_t size)
ngx_brix_cvmfs_repo_metrics_t * sd_cache_repo_metrics (const sd_cache_inst_state *st, const char *key)
void sd_cache_note_origin_bytes (const sd_cache_inst_state *st, const char *key, off_t bytes)
void sd_cache_note_upstream (const sd_cache_inst_state *st, int ok, off_t bytes, long dur_ms)
long sd_cache_ms_since (const struct timespec *t0)
int sd_cache_is_manifest_key (const char *key)
int sd_cache_stale_serve_ok (sd_cache_inst_state *st, const char *key)
Function Documentation
sd_cache_admit()
int sd_cache_admit (const brix_cache_policy_t * pol, const char * path, off_t size)
Definition at line 48 of file sd_cache_policy.c.
References brix_cache_policy_t::allow_prefixes, brix_cache_policy_t::deny_prefixes, brix_cache_policy_t::include_regex, brix_cache_policy_t::max_file_size, and sd_cache_has_prefix().
Referenced by sd_cache_fill(), and sd_cache_open().
sd_cache_is_manifest_key()
int sd_cache_is_manifest_key (const char * key)
Definition at line 158 of file sd_cache_policy.c.
References key.
Referenced by sd_cache_fill().
sd_cache_ms_since()
long sd_cache_ms_since (const struct timespec * t0)
Definition at line 143 of file sd_cache_policy.c.
Referenced by sd_cache_fill().
sd_cache_note_origin_bytes()
void sd_cache_note_origin_bytes (const sd_cache_inst_state * st, const char * key, off_t bytes)
Definition at line 96 of file sd_cache_policy.c.
References BRIX_ATOMIC_ADD, BRIX_CVMFS_METRIC_ADD, key, ngx_brix_cvmfs_repo_metrics_t::origin_bytes_total, sd_cache_is_cvmfs(), and sd_cache_repo_metrics().
Referenced by sd_cache_fill().
sd_cache_note_upstream()
void sd_cache_note_upstream (const sd_cache_inst_state * st, int ok, off_t bytes, long dur_ms)
Definition at line 117 of file sd_cache_policy.c.
References BRIX_CVMFS_UPSTREAM_NAME_MAX, brix_cvmfs_upstream_record(), brix_sd_cache_source_instance(), sd_cache_is_cvmfs(), sd_http_last_origin(), sd_http_last_was_failover(), and sd_cache_inst_state::source.
Referenced by sd_cache_fill().
sd_cache_repo_metrics()
ngx_brix_cvmfs_repo_metrics_t * sd_cache_repo_metrics (const sd_cache_inst_state * st, const char * key)
Definition at line 81 of file sd_cache_policy.c.
References brix_cvmfs_repo_slot(), key, and sd_cache_is_cvmfs().
Referenced by sd_cache_fill(), and sd_cache_note_origin_bytes().
sd_cache_stale_serve_ok()
int sd_cache_stale_serve_ok (sd_cache_inst_state * st, const char * key)
Definition at line 174 of file sd_cache_policy.c.
References brix_cache_cinfo_expired(), brix_cache_cinfo_set_expires(), BRIX_CINFO_F_COMPLETE, brix_cstore_cinfo_load(), brix_cstore_cinfo_store(), sd_cache_inst_state::cstore, brix_cache_policy_t::cvmfs_manifest_ttl, brix_cache_cinfo_t::expires_at, brix_cache_cinfo_t::filled_at, brix_cache_cinfo_t::flags, key, sd_cache_inst_state::log, and sd_cache_inst_state::policy.
Referenced by sd_cache_fill().