nginx-xrootd: src/fs/backend/cache/sd_cache_manifest.c File Reference
sd_cache_manifest.c File Reference
#include "sd_cache.h"
#include "sd_cache_internal.h"
#include "protocols/cvmfs/classify.h"
#include "cvmfs/grammar/hash.h"
#include "cvmfs/object/object.h"
#include "cvmfs/signature/manifest.h"
#include "cvmfs/signature/verify.h"
#include "cvmfs/signature/whitelist.h"
#include <errno.h>
#include <fcntl.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
Macros
#define SD_CACHE_META_MAX 65536
Functions
static ssize_t meta_read_part (const char *pp, unsigned char **out)
static ssize_t meta_fetch_source (sd_cache_inst_state *st, const char *key, unsigned char **out)
static int meta_check_whitelist (sd_cache_inst_state *st, const unsigned char *buf, size_t len, const char *key, cvmfs_whitelist_t *out)
static int meta_check_manifest (sd_cache_inst_state *st, const char *key, const cvmfs_url_info_t *info, const unsigned char *buf, size_t len)
ngx_int_t sd_cache_verify_manifest (sd_cache_inst_state *st, const char *key, const char *pp)
Macro Definition Documentation
SD_CACHE_META_MAX
#define SD_CACHE_META_MAX 65536
Definition at line 47 of file sd_cache_manifest.c.
Function Documentation
meta_check_manifest()
static int meta_check_manifest (sd_cache_inst_state * st, const char * key, const cvmfs_url_info_t * info, const unsigned char * buf, size_t len) static
Definition at line 176 of file sd_cache_manifest.c.
References key, sd_cache_inst_state::log, meta_check_whitelist(), meta_fetch_source(), and SD_CACHE_META_MAX.
Referenced by sd_cache_verify_manifest().
meta_check_whitelist()
static int meta_check_whitelist (sd_cache_inst_state * st, const unsigned char * buf, size_t len, const char * key, cvmfs_whitelist_t * out) static
Definition at line 146 of file sd_cache_manifest.c.
References brix_cache_policy_t::cvmfs_master_pub, brix_cache_policy_t::cvmfs_master_pub_len, key, sd_cache_inst_state::log, and sd_cache_inst_state::policy.
Referenced by meta_check_manifest(), and sd_cache_verify_manifest().
meta_fetch_source()
static ssize_t meta_fetch_source (sd_cache_inst_state * st, const char * key, unsigned char ** out) static
Definition at line 94 of file sd_cache_manifest.c.
References BRIX_SD_O_READ, brix_sd_obj_release(), brix_sd_open_maybe_cred(), key, SD_CACHE_META_MAX, and sd_cache_inst_state::source.
Referenced by meta_check_manifest().
meta_read_part()
static ssize_t meta_read_part (const char * pp, unsigned char ** out) static
Definition at line 52 of file sd_cache_manifest.c.
References close(), open(), read(), and SD_CACHE_META_MAX.
Referenced by sd_cache_verify_manifest().
sd_cache_verify_manifest()
ngx_int_t sd_cache_verify_manifest (sd_cache_inst_state * st, const char * key, const char * pp)
Definition at line 282 of file sd_cache_manifest.c.
References brix_cache_policy_t::cvmfs_master_pub, brix_cache_policy_t::cvmfs_master_pub_len, key, sd_cache_inst_state::log, meta_check_manifest(), meta_check_whitelist(), meta_read_part(), and sd_cache_inst_state::policy.
Referenced by cache_fill_verify().