nginx-xrootd: src/fs/backend/pblock/sd_pblock_unittest_block.c File Reference
sd_pblock_unittest_block.c File Reference
#include "fs/backend/sd.h"
#include "sd_pblock_catalog.h"
#include "sd_pblock_unittest_internal.h"
#include <errno.h>
#include <ftw.h>
#include <limits.h>
#include <pthread.h>
#include <sqlite3.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>
Macros
#define _GNU_SOURCE /* nftw(3) + FTW_PHYS for the on-disk block scan */
Functions
static int blk_walk_cb (const char *path, const struct stat *sb, int type, struct FTW *ftw)
static void scan_blocks (const char *root)
int open_block_export (brix_sd_instance_t *inst, char *root, int64_t block_size)
void test_block_striping (void)
void test_block_size_configurable (void)
void test_block_sparse (void)
void test_block_truncate (void)
void test_block_copy_and_unlink (void)
Variables
static long g_blk_count
static long g_blk_total
static long g_blk_max
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE /* nftw(3) + FTW_PHYS for the on-disk block scan */
Definition at line 8 of file sd_pblock_unittest_block.c.
Function Documentation
blk_walk_cb()
static int blk_walk_cb (const char * path, const struct stat * sb, int type, struct FTW * ftw) static
Definition at line 32 of file sd_pblock_unittest_block.c.
References g_blk_count, g_blk_max, and g_blk_total.
Referenced by scan_blocks().
open_block_export()
int open_block_export (brix_sd_instance_t * inst, char * root, int64_t block_size)
Definition at line 61 of file sd_pblock_unittest_block.c.
References D.
Referenced by test_block_copy_and_unlink(), test_block_size_configurable(), test_block_sparse(), test_block_striping(), test_block_truncate(), and test_identity().
scan_blocks()
static void scan_blocks (const char * root) static
Definition at line 49 of file sd_pblock_unittest_block.c.
References blk_walk_cb(), g_blk_count, g_blk_max, and g_blk_total.
Referenced by test_block_copy_and_unlink(), test_block_size_configurable(), test_block_sparse(), test_block_striping(), and test_block_truncate().
test_block_copy_and_unlink()
void test_block_copy_and_unlink (void)
Definition at line 211 of file sd_pblock_unittest_block.c.
References CHECK, D, g_blk_count, open_block_export(), read_file(), scan_blocks(), brix_sd_stat_t::size, and write_file().
Referenced by main().
test_block_size_configurable()
void test_block_size_configurable (void)
Definition at line 115 of file sd_pblock_unittest_block.c.
References CHECK, D, g_blk_count, g_blk_max, g_blk_total, open_block_export(), scan_blocks(), and write_file().
Referenced by main().
test_block_sparse()
void test_block_sparse (void)
Definition at line 139 of file sd_pblock_unittest_block.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, D, g_blk_count, open_block_export(), pb_close(), read_file(), scan_blocks(), and brix_sd_stat_t::size.
Referenced by main().
test_block_striping()
void test_block_striping (void)
Definition at line 76 of file sd_pblock_unittest_block.c.
References BRIX_SD_O_READ, CHECK, D, g_blk_count, g_blk_max, g_blk_total, open_block_export(), pb_close(), read_file(), scan_blocks(), brix_sd_stat_t::size, and write_file().
Referenced by main().
test_block_truncate()
void test_block_truncate (void)
Definition at line 176 of file sd_pblock_unittest_block.c.
References BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, D, g_blk_count, g_blk_total, open_block_export(), pb_close(), read_file(), scan_blocks(), brix_sd_stat_t::size, and write_file().
Referenced by main().
Variable Documentation
g_blk_count
long g_blk_count static
Definition at line 29 of file sd_pblock_unittest_block.c.
Referenced by blk_walk_cb(), scan_blocks(), test_block_copy_and_unlink(), test_block_size_configurable(), test_block_sparse(), test_block_striping(), and test_block_truncate().
g_blk_max
long g_blk_max static
Definition at line 29 of file sd_pblock_unittest_block.c.
Referenced by blk_walk_cb(), scan_blocks(), test_block_size_configurable(), and test_block_striping().
g_blk_total
long g_blk_total static
Definition at line 29 of file sd_pblock_unittest_block.c.
Referenced by blk_walk_cb(), scan_blocks(), test_block_size_configurable(), test_block_striping(), and test_block_truncate().