nginx-xrootd: src/fs/backend/sd_registry.c File Reference
sd_registry.c File Reference
#include "sd.h"
#include "core/types/fs_list.h"
#include "fs/backend/rados/sd_ceph.h"
#include <errno.h>
Macros
#define BRIX_FS_ROW_BACKEND(ID, sym, name) &brix_sd_##sym##_driver,
#define BRIX_FS_ROW_ORIGIN(ID, sym, name)
#define BRIX_FS_ROW_DECORATOR(ID, sym, name)
#define BRIX_FS_ROW_NEARLINE(ID, sym, name)
Functions
ngx_uint_t brix_sd_driver_count (void)
const brix_sd_driver_t * brix_sd_driver_at (ngx_uint_t i)
const brix_sd_driver_t * brix_sd_default_driver (void)
const brix_sd_driver_t * brix_sd_driver_find (const char *name)
brix_sd_instance_t * brix_sd_instance_create (ngx_pool_t *pool, ngx_log_t *log, const char *name, void *driver_conf, int *err_out)
void brix_sd_instance_destroy (brix_sd_instance_t *inst)
uint32_t brix_sd_caps (const brix_sd_instance_t *inst)
ngx_fd_t brix_sd_fd (const brix_sd_obj_t *obj)
const char * brix_sd_backend_name (const brix_sd_instance_t *inst)
ngx_int_t brix_sd_supports (const brix_sd_instance_t *inst, uint32_t required_caps)
Variables
static const brix_sd_driver_t *const sd_drivers []
Macro Definition Documentation
BRIX_FS_ROW_BACKEND
#define BRIX_FS_ROW_BACKEND (ID, sym, name) &brix_sd_##sym##_driver,
Definition at line 28 of file sd_registry.c.
BRIX_FS_ROW_DECORATOR
#define BRIX_FS_ROW_DECORATOR (ID, sym, name)
Definition at line 30 of file sd_registry.c.
BRIX_FS_ROW_NEARLINE
#define BRIX_FS_ROW_NEARLINE (ID, sym, name)
Definition at line 31 of file sd_registry.c.
BRIX_FS_ROW_ORIGIN
#define BRIX_FS_ROW_ORIGIN (ID, sym, name)
Definition at line 29 of file sd_registry.c.
Function Documentation
brix_sd_backend_name()
const char * brix_sd_backend_name (const brix_sd_instance_t * inst)
Definition at line 147 of file sd_registry.c.
Referenced by brix_cache_fill_from_source(), brix_cache_open_or_fill(), brix_vfs_file_backend_name(), and brix_vfs_observe_ctx_op().
brix_sd_caps()
uint32_t brix_sd_caps (const brix_sd_instance_t * inst)
Definition at line 130 of file sd_registry.c.
Referenced by brix_cstore_init(), brix_sd_cache_fill_needs_offload(), brix_sd_supports(), brix_vfs_residency(), ngx_http_brix_dashboard_scan_handler(), and sd_cache_open().
brix_sd_default_driver()
const brix_sd_driver_t * brix_sd_default_driver (void)
Definition at line 60 of file sd_registry.c.
References brix_sd_posix_driver.
Referenced by brix_commit_staged(), brix_handle_stat(), brix_vfs_ctx_driver(), brix_vfs_ctx_sd_obj(), brix_vfs_open(), brix_vfs_rename_path(), brix_vfs_staged_open(), and cms_node_exec_forward().
brix_sd_driver_at()
const brix_sd_driver_t * brix_sd_driver_at (ngx_uint_t i)
Definition at line 50 of file sd_registry.c.
References sd_drivers.
brix_sd_driver_count()
ngx_uint_t brix_sd_driver_count (void)
Definition at line 44 of file sd_registry.c.
References sd_drivers.
brix_sd_driver_find()
const brix_sd_driver_t * brix_sd_driver_find (const char * name)
Definition at line 69 of file sd_registry.c.
References name, and sd_drivers.
Referenced by brix_sd_instance_create().
brix_sd_fd()
ngx_fd_t brix_sd_fd (const brix_sd_obj_t * obj)
Definition at line 136 of file sd_registry.c.
References BRIX_SD_CAP_FD.
brix_sd_instance_create()
brix_sd_instance_t * brix_sd_instance_create (ngx_pool_t * pool, ngx_log_t * log, const char * name, void * driver_conf, int * err_out)
Definition at line 88 of file sd_registry.c.
References brix_sd_driver_find(), driver, log, and name.
Referenced by brix_tier_build(), brix_vfs_backend_build_source(), and brix_vfs_backend_entry_build().
brix_sd_instance_destroy()
void brix_sd_instance_destroy (brix_sd_instance_t * inst)
Definition at line 120 of file sd_registry.c.
brix_sd_supports()
ngx_int_t brix_sd_supports (const brix_sd_instance_t * inst, uint32_t required_caps)
Definition at line 153 of file sd_registry.c.
References brix_sd_caps().
Variable Documentation
sd_drivers
const brix_sd_driver_t* const sd_drivers[] static
Initial value:
= {
     &brix_sd_posix_driver,     &brix_sd_block_driver,
}
Definition at line 33 of file sd_registry.c.
Referenced by brix_sd_driver_at(), brix_sd_driver_count(), and brix_sd_driver_find().