nginx-xrootd: src/fs/backend/frm/sd_frm.c File Reference
sd_frm.c File Reference
#include "sd_frm.h"
#include "sd_frm_mss.h"
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <spawn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct sd_frm_state
struct sd_frm_staged_state
Macros
#define SD_FRM_ST(inst) ((sd_frm_state *) (inst)->state)
Functions
static int frm_ensure_online (sd_frm_state *st, const char *key)
static brix_sd_obj_t * sd_frm_open (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, int *err_out)
static ngx_int_t sd_frm_close (brix_sd_obj_t *obj)
static ssize_t sd_frm_pread (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
static ngx_int_t sd_frm_fstat (brix_sd_obj_t *obj, brix_sd_stat_t *out)
static ngx_int_t sd_frm_stat (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out)
static ngx_int_t sd_frm_residency (brix_sd_instance_t *inst, const char *key, brix_sd_residency_t *out)
static ngx_int_t sd_frm_recall (brix_sd_instance_t *inst, const char *key, char reqid_out[40])
static brix_sd_staged_t * sd_frm_staged_open (brix_sd_instance_t *inst, const char *final_path, mode_t mode, int *err_out)
static ssize_t sd_frm_staged_write (brix_sd_staged_t *st, const void *buf, size_t len, off_t off)
static ngx_int_t sd_frm_staged_commit (brix_sd_staged_t *st, int noreplace)
static void sd_frm_staged_abort (brix_sd_staged_t *st)
static int frm_select_exec_adapter (sd_frm_state *st, const char *adapter, const char *location, ngx_log_t *log)
static int frm_select_stub_adapter (sd_frm_state *st, const char *adapter, const char *location, ngx_log_t *log)
brix_sd_instance_t * brix_sd_frm_create (const char *adapter, const char *location, ngx_log_t *log)
void brix_sd_frm_destroy (brix_sd_instance_t *inst)
Variables
char ** environ
static const brix_sd_driver_t brix_sd_frm_driver
Macro Definition Documentation
SD_FRM_ST
#define SD_FRM_ST (inst) ((sd_frm_state *) (inst)->state)
Definition at line 48 of file sd_frm.c.
Function Documentation
brix_sd_frm_create()
brix_sd_instance_t * brix_sd_frm_create (const char * adapter, const char * location, ngx_log_t * log)
Definition at line 425 of file sd_frm.c.
References brix_sd_frm_driver, frm_select_exec_adapter(), frm_select_stub_adapter(), log, sd_frm_state::log, and sd_frm_state::mss.
Referenced by brix_vbr_build_tape(), and tier_build_tape().
brix_sd_frm_destroy()
void brix_sd_frm_destroy (brix_sd_instance_t * inst)
Definition at line 465 of file sd_frm.c.
References brix_mss_adapter_t::destroy, sd_frm_state::mss, and sd_frm_state::mss_ctx.
frm_ensure_online()
static int frm_ensure_online (sd_frm_state * st, const char * key) static
Definition at line 55 of file sd_frm.c.
References BRIX_RESIDENCY_ABSENT, BRIX_RESIDENCY_ONLINE, key, sd_frm_state::mss, sd_frm_state::mss_ctx, brix_mss_adapter_t::recall_begin, brix_mss_adapter_t::recall_poll, and brix_mss_adapter_t::residency.
Referenced by sd_frm_open(), and sd_frm_recall().
frm_select_exec_adapter()
static int frm_select_exec_adapter (sd_frm_state * st, const char * adapter, const char * location, ngx_log_t * log) static
Definition at line 340 of file sd_frm.c.
References brix_mss_exec_adapter, brix_mss_exec_create(), log, sd_frm_state::mss, and sd_frm_state::mss_ctx.
Referenced by brix_sd_frm_create().
frm_select_stub_adapter()
static int frm_select_stub_adapter (sd_frm_state * st, const char * adapter, const char * location, ngx_log_t * log) static
Definition at line 386 of file sd_frm.c.
References brix_mss_stub_adapter, brix_mss_stub_create(), log, sd_frm_state::mss, and sd_frm_state::mss_ctx.
Referenced by brix_sd_frm_create().
sd_frm_close()
static ngx_int_t sd_frm_close (brix_sd_obj_t * obj) static
Definition at line 137 of file sd_frm.c.
References close().
sd_frm_fstat()
static ngx_int_t sd_frm_fstat (brix_sd_obj_t * obj, brix_sd_stat_t * out) static
Definition at line 159 of file sd_frm.c.
References brix_sd_stat_t::ctime, fstat(), brix_sd_stat_t::ino, brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, brix_sd_stat_t::mtime, brix_sd_stat_t::size, and stat().
sd_frm_open()
static brix_sd_obj_t * sd_frm_open (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, int * err_out) static
Definition at line 91 of file sd_frm.c.
References BRIX_SD_O_WRITE, close(), frm_ensure_online(), fstat(), sd_frm_state::mss, sd_frm_state::mss_ctx, brix_mss_adapter_t::open_online, SD_FRM_ST, and stat().
sd_frm_pread()
static ssize_t sd_frm_pread (brix_sd_obj_t * obj, void * buf, size_t len, off_t off) static
Definition at line 153 of file sd_frm.c.
References pread().
sd_frm_recall()
static ngx_int_t sd_frm_recall (brix_sd_instance_t * inst, const char * key, char reqid_out[40]) static
Definition at line 218 of file sd_frm.c.
References frm_ensure_online(), key, and SD_FRM_ST.
sd_frm_residency()
static ngx_int_t sd_frm_residency (brix_sd_instance_t * inst, const char * key, brix_sd_residency_t * out) static
Definition at line 200 of file sd_frm.c.
References BRIX_RESIDENCY_NEARLINE, BRIX_RESIDENCY_OFFLINE, BRIX_RESIDENCY_ONLINE, BRIX_SD_RES_NEARLINE, BRIX_SD_RES_OFFLINE, BRIX_SD_RES_ONLINE, key, sd_frm_state::mss, sd_frm_state::mss_ctx, brix_mss_adapter_t::residency, and SD_FRM_ST.
sd_frm_staged_abort()
static void sd_frm_staged_abort (brix_sd_staged_t * st) static
Definition at line 291 of file sd_frm.c.
References close(), sd_frm_staged_state::fd, sd_frm_staged_state::fst, sd_frm_staged_state::key, sd_frm_state::mss, sd_frm_state::mss_ctx, and brix_mss_adapter_t::purge.
sd_frm_staged_commit()
static ngx_int_t sd_frm_staged_commit (brix_sd_staged_t * st, int noreplace) static
Definition at line 273 of file sd_frm.c.
References close(), sd_frm_staged_state::fd, sd_frm_staged_state::fst, sd_frm_staged_state::key, brix_mss_adapter_t::migrate, sd_frm_state::mss, and sd_frm_state::mss_ctx.
sd_frm_staged_open()
static brix_sd_staged_t * sd_frm_staged_open (brix_sd_instance_t * inst, const char * final_path, mode_t mode, int * err_out) static
Definition at line 234 of file sd_frm.c.
References close(), brix_mss_adapter_t::create_online, sd_frm_staged_state::fd, sd_frm_staged_state::fst, sd_frm_staged_state::key, sd_frm_state::mss, sd_frm_state::mss_ctx, and SD_FRM_ST.
sd_frm_staged_write()
static ssize_t sd_frm_staged_write (brix_sd_staged_t * st, const void * buf, size_t len, off_t off) static
Definition at line 265 of file sd_frm.c.
References sd_frm_staged_state::fd.
sd_frm_stat()
static ngx_int_t sd_frm_stat (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out) static
Definition at line 177 of file sd_frm.c.
References BRIX_RESIDENCY_ABSENT, brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, sd_frm_state::mss, sd_frm_state::mss_ctx, brix_sd_stat_t::mtime, brix_mss_adapter_t::residency, SD_FRM_ST, and brix_sd_stat_t::size.
Variable Documentation
brix_sd_frm_driver
const brix_sd_driver_t brix_sd_frm_driver static
Initial value:
= {
    .name = "frm",
    .caps = BRIX_SD_CAP_NEARLINE | BRIX_SD_CAP_RANGE_READ
          | BRIX_SD_CAP_RANDOM_WRITE | BRIX_SD_CAP_FD,
    .open          = sd_frm_open,
    .close         = sd_frm_close,
    .pread         = sd_frm_pread,
    .fstat         = sd_frm_fstat,
    .stat          = sd_frm_stat,
    .recall        = sd_frm_recall,
    .residency     = sd_frm_residency,
    .staged_open   = sd_frm_staged_open,
    .staged_write  = sd_frm_staged_write,
    .staged_commit = sd_frm_staged_commit,
    .staged_abort  = sd_frm_staged_abort,
}
Definition at line 304 of file sd_frm.c.
Referenced by brix_sd_frm_create().
environ
char** environ extern
Referenced by exec_run().