nginx-xrootd: src/fs/backend/pblock/sd_pblock_unittest.c File Reference
sd_pblock_unittest.c File Reference
#include "fs/backend/sd.h"
#include "sd_pblock_catalog.h"
#include <errno.h>
#include <ftw.h>
#include <limits.h>
#include <pthread.h>
#include <sqlite3.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>
Data Structures
struct thread_arg
struct enum_probe_t
struct break_arg
Macros
#define _GNU_SOURCE /* nftw(3) + FTW_PHYS for the on-disk block scan */
#define CHECK(cond, ...)
Functions
static ngx_int_t pb_close (brix_sd_obj_t *o)
static int write_file (brix_sd_instance_t *inst, const char *path, const char *data, size_t len)
static ssize_t read_file (brix_sd_instance_t *inst, const char *path, char *buf, size_t cap)
static void test_write_read_fstat (brix_sd_instance_t *inst)
static void test_truncate_and_stat (brix_sd_instance_t *inst)
static void test_preadv (brix_sd_instance_t *inst)
static void test_dirs (brix_sd_instance_t *inst)
static void test_rename (brix_sd_instance_t *inst)
static void test_server_copy (brix_sd_instance_t *inst)
static void test_xattr (brix_sd_instance_t *inst)
static void test_staged (brix_sd_instance_t *inst)
static void test_unlink (brix_sd_instance_t *inst)
static void test_fsync_durability (const char *root)
static void * thread_body (void *p)
static void test_threads (brix_sd_instance_t *inst)
static void test_processes (const char *root, brix_sd_instance_t *inst)
static int blk_walk_cb (const char *path, const struct stat *sb, int type, struct FTW *ftw)
static void scan_blocks (const char *root)
static int open_block_export (brix_sd_instance_t *inst, char *root, int64_t block_size)
static void test_block_striping (void)
static void test_block_size_configurable (void)
static void test_block_sparse (void)
static void test_block_truncate (void)
static void test_block_copy_and_unlink (void)
static int cred_write_file (brix_sd_instance_t *inst, const char *path, mode_t mode, const brix_sd_cred_t *who)
static void test_ident_ownership (brix_sd_instance_t *inst)
static void test_ident_vo_dir (brix_sd_instance_t *inst)
static void test_ident_traverse (brix_sd_instance_t *inst)
static void test_ident_setattr (brix_sd_instance_t *inst)
static void test_ident_xattr_sticky (brix_sd_instance_t *inst)
static void test_identity (void)
static void lab_write_sidecar (const char *root, const char *line)
static void lab_ctl_set (const char *root, const char *key, const char *val, long epoch)
static void test_lab_fault_inject (void)
static void test_lab_gate_closed (void)
static void test_lab_caps_mask (void)
static int enum_probe_cb (void *ctx, const brix_sd_catalog_ent_t *ent)
static void enum_walk (brix_sd_instance_t *inst, const char *dir, int *files, int64_t *bytes)
static void test_lab_enumerate (void)
static void q_blob_id (const char *root, const char *path, char *out, size_t cap)
static int q_refcount (const char *root, const char *blob_id)
static int q_count (const char *root, const char *sql)
static int staged_put (brix_sd_instance_t *inst, const char *path, const char *data, size_t len)
static int trunc_write (brix_sd_instance_t *inst, const char *path, const char *data, size_t len)
static void * break_body (void *p)
static void test_dedup_refs (void)
static void test_dedup_forged_hash (void)
static void test_dedup_gate_closed (void)
static void test_snapshot (void)
static void test_versioning (void)
int main (void)
Variables
static int failures
static const brix_sd_driver_t * D
static long g_blk_count
static long g_blk_total
static long g_blk_max
static const brix_sd_cred_t CRED_ALICE
static const brix_sd_cred_t CRED_BOB
static const brix_sd_cred_t CRED_CAROL
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE /* nftw(3) + FTW_PHYS for the on-disk block scan */
Definition at line 14 of file sd_pblock_unittest.c.
CHECK
#define CHECK (cond, ...)
Value:
    do {                                                                       \
        if (!(cond)) {                                                         \
            fprintf(stderr, "FAIL %s:%d: ", __func__, __LINE__);              \
            fprintf(stderr, __VA_ARGS__);                                      \
            fprintf(stderr, "\n");                                             \
            failures++;                                                        \
        }                                                                      \
    } while (0)
Definition at line 34 of file sd_pblock_unittest.c.
Function Documentation
blk_walk_cb()
static int blk_walk_cb (const char * path, const struct stat * sb, int type, struct FTW * ftw) static
Definition at line 468 of file sd_pblock_unittest.c.
References g_blk_count, g_blk_max, and g_blk_total.
Referenced by scan_blocks().
break_body()
static void * break_body (void * p) static
Definition at line 1400 of file sd_pblock_unittest.c.
References break_arg::data, break_arg::inst, break_arg::len, break_arg::path, break_arg::rc, and trunc_write().
Referenced by test_dedup_refs().
cred_write_file()
static int cred_write_file (brix_sd_instance_t * inst, const char * path, mode_t mode, const brix_sd_cred_t * who) static
Definition at line 691 of file sd_pblock_unittest.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_READ, BRIX_SD_O_WRITE, D, and pb_close().
Referenced by test_ident_ownership(), test_ident_setattr(), and test_ident_traverse().
enum_probe_cb()
static int enum_probe_cb (void * ctx, const brix_sd_catalog_ent_t * ent) static
Definition at line 1168 of file sd_pblock_unittest.c.
References enum_probe_t::bytes, enum_probe_t::files, brix_sd_catalog_ent_t::have_stat, brix_sd_catalog_ent_t::key, brix_sd_catalog_ent_t::path, enum_probe_t::saw_nested, brix_sd_catalog_ent_t::size, and enum_probe_t::stop_after.
Referenced by test_lab_enumerate().
enum_walk()
static void enum_walk (brix_sd_instance_t * inst, const char * dir, int * files, int64_t * bytes) static
Definition at line 1188 of file sd_pblock_unittest.c.
References D, enum_walk(), brix_sd_stat_t::is_dir, brix_sd_dirent_t::name, and brix_sd_stat_t::size.
Referenced by enum_walk(), and test_lab_enumerate().
lab_ctl_set()
static void lab_ctl_set (const char * root, const char * key, const char * val, long epoch) static
Definition at line 1032 of file sd_pblock_unittest.c.
References CHECK, key, and PATH_MAX.
Referenced by test_lab_fault_inject(), and test_lab_gate_closed().
lab_write_sidecar()
static void lab_write_sidecar (const char * root, const char * line) static
Definition at line 1016 of file sd_pblock_unittest.c.
References CHECK, and PATH_MAX.
Referenced by test_dedup_forged_hash(), test_dedup_refs(), test_lab_caps_mask(), test_lab_fault_inject(), test_snapshot(), and test_versioning().
main()
int main (void)
Definition at line 1785 of file sd_pblock_unittest.c.
References CHECK, D, failures, break_arg::inst, test_block_copy_and_unlink(), test_block_size_configurable(), test_block_sparse(), test_block_striping(), test_block_truncate(), test_dedup_forged_hash(), test_dedup_gate_closed(), test_dedup_refs(), test_dirs(), test_fsync_durability(), test_identity(), test_lab_caps_mask(), test_lab_enumerate(), test_lab_fault_inject(), test_lab_gate_closed(), test_preadv(), test_processes(), test_rename(), test_server_copy(), test_snapshot(), test_staged(), test_threads(), test_truncate_and_stat(), test_unlink(), test_versioning(), test_write_read_fstat(), and test_xattr().
open_block_export()
static int open_block_export (brix_sd_instance_t * inst, char * root, int64_t block_size) static
Definition at line 497 of file sd_pblock_unittest.c.
References D.
Referenced by test_block_copy_and_unlink(), test_block_size_configurable(), test_block_sparse(), test_block_striping(), test_block_truncate(), and test_identity().
pb_close()
static ngx_int_t pb_close (brix_sd_obj_t * o) static
Definition at line 50 of file sd_pblock_unittest.c.
References D.
Referenced by cred_write_file(), read_file(), test_block_sparse(), test_block_striping(), test_block_truncate(), test_fsync_durability(), test_ident_ownership(), test_ident_traverse(), test_lab_fault_inject(), test_lab_gate_closed(), test_preadv(), test_snapshot(), test_truncate_and_stat(), test_write_read_fstat(), trunc_write(), and write_file().
q_blob_id()
static void q_blob_id (const char * root, const char * path, char * out, size_t cap) static
Definition at line 1277 of file sd_pblock_unittest.c.
References CHECK, and PATH_MAX.
Referenced by test_dedup_forged_hash(), test_dedup_gate_closed(), test_dedup_refs(), and test_versioning().
q_count()
static int q_count (const char * root, const char * sql) static
Definition at line 1330 of file sd_pblock_unittest.c.
References CHECK, and PATH_MAX.
Referenced by test_versioning().
q_refcount()
static int q_refcount (const char * root, const char * blob_id) static
Definition at line 1304 of file sd_pblock_unittest.c.
References CHECK, and PATH_MAX.
Referenced by test_dedup_refs(), and test_versioning().
read_file()
static ssize_t read_file (brix_sd_instance_t * inst, const char * path, char * buf, size_t cap) static
Definition at line 83 of file sd_pblock_unittest.c.
References BRIX_SD_O_READ, D, and pb_close().
Referenced by test_block_copy_and_unlink(), test_block_sparse(), test_block_striping(), test_block_truncate(), test_dedup_forged_hash(), test_dedup_gate_closed(), test_dedup_refs(), test_rename(), test_server_copy(), test_snapshot(), test_staged(), test_versioning(), test_write_read_fstat(), and thread_body().
scan_blocks()
static void scan_blocks (const char * root) static
Definition at line 485 of file sd_pblock_unittest.c.
References blk_walk_cb(), g_blk_count, g_blk_max, and g_blk_total.
Referenced by test_block_copy_and_unlink(), test_block_size_configurable(), test_block_sparse(), test_block_striping(), and test_block_truncate().
staged_put()
static int staged_put (brix_sd_instance_t * inst, const char * path, const char * data, size_t len) static
Definition at line 1353 of file sd_pblock_unittest.c.
References D, and s.
Referenced by test_versioning().
test_block_copy_and_unlink()
static void test_block_copy_and_unlink (void) static
Definition at line 647 of file sd_pblock_unittest.c.
References CHECK, D, g_blk_count, open_block_export(), read_file(), scan_blocks(), brix_sd_stat_t::size, and write_file().
Referenced by main().
test_block_size_configurable()
static void test_block_size_configurable (void) static
Definition at line 551 of file sd_pblock_unittest.c.
References CHECK, D, g_blk_count, g_blk_max, g_blk_total, open_block_export(), scan_blocks(), and write_file().
Referenced by main().
test_block_sparse()
static void test_block_sparse (void) static
Definition at line 575 of file sd_pblock_unittest.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, D, g_blk_count, open_block_export(), pb_close(), read_file(), scan_blocks(), and brix_sd_stat_t::size.
Referenced by main().
test_block_striping()
static void test_block_striping (void) static
Definition at line 512 of file sd_pblock_unittest.c.
References BRIX_SD_O_READ, CHECK, D, g_blk_count, g_blk_max, g_blk_total, open_block_export(), pb_close(), read_file(), scan_blocks(), brix_sd_stat_t::size, and write_file().
Referenced by main().
test_block_truncate()
static void test_block_truncate (void) static
Definition at line 612 of file sd_pblock_unittest.c.
References BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, D, g_blk_count, g_blk_total, open_block_export(), pb_close(), read_file(), scan_blocks(), brix_sd_stat_t::size, and write_file().
Referenced by main().
test_dedup_forged_hash()
static void test_dedup_forged_hash (void) static
Definition at line 1498 of file sd_pblock_unittest.c.
References CHECK, D, break_arg::inst, lab_write_sidecar(), PATH_MAX, PBLOCK_BLOB_ID_CAP, q_blob_id(), read_file(), and write_file().
Referenced by main().
test_dedup_gate_closed()
static void test_dedup_gate_closed (void) static
Definition at line 1579 of file sd_pblock_unittest.c.
References CHECK, D, break_arg::inst, PBLOCK_BLOB_ID_CAP, q_blob_id(), read_file(), and write_file().
Referenced by main().
test_dedup_refs()
static void test_dedup_refs (void) static
Definition at line 1409 of file sd_pblock_unittest.c.
References break_body(), CHECK, D, break_arg::inst, lab_write_sidecar(), PBLOCK_BLOB_ID_CAP, q_blob_id(), q_refcount(), break_arg::rc, read_file(), trunc_write(), and write_file().
Referenced by main().
test_dirs()
static void test_dirs (brix_sd_instance_t * inst) static
Definition at line 173 of file sd_pblock_unittest.c.
References CHECK, D, brix_sd_dirent_t::name, and write_file().
Referenced by main().
test_fsync_durability()
static void test_fsync_durability (const char * root) static
Definition at line 307 of file sd_pblock_unittest.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, D, pb_close(), and brix_sd_stat_t::size.
Referenced by main().
test_ident_ownership()
static void test_ident_ownership (brix_sd_instance_t * inst) static
Definition at line 713 of file sd_pblock_unittest.c.
References BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, CRED_ALICE, CRED_BOB, CRED_CAROL, cred_write_file(), D, brix_sd_stat_t::gid, pb_close(), PBLOCK_ID_BASE, and brix_sd_stat_t::uid.
Referenced by test_identity().
test_ident_setattr()
static void test_ident_setattr (brix_sd_instance_t * inst) static
Definition at line 874 of file sd_pblock_unittest.c.
References CHECK, CRED_ALICE, CRED_BOB, cred_write_file(), D, brix_sd_stat_t::gid, brix_sd_setattr_t::gid, brix_sd_setattr_t::mode, brix_sd_setattr_t::set_mode, brix_sd_setattr_t::set_owner, brix_sd_stat_t::uid, and brix_sd_setattr_t::uid.
Referenced by test_identity().
test_ident_traverse()
static void test_ident_traverse (brix_sd_instance_t * inst) static
Definition at line 830 of file sd_pblock_unittest.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, CRED_ALICE, CRED_BOB, CRED_CAROL, cred_write_file(), D, and pb_close().
Referenced by test_identity().
test_ident_vo_dir()
static void test_ident_vo_dir (brix_sd_instance_t * inst) static
Definition at line 781 of file sd_pblock_unittest.c.
References CHECK, CRED_ALICE, CRED_BOB, CRED_CAROL, D, PBLOCK_ID_BASE, and brix_sd_stat_t::uid.
Referenced by test_identity().
test_ident_xattr_sticky()
static void test_ident_xattr_sticky (brix_sd_instance_t * inst) static
Definition at line 927 of file sd_pblock_unittest.c.
References BRIX_SD_O_WRITE, CHECK, CRED_ALICE, CRED_BOB, CRED_CAROL, and D.
Referenced by test_identity().
test_identity()
static void test_identity (void) static
Definition at line 990 of file sd_pblock_unittest.c.
References BRIX_SD_CRED_IDENTITY, CHECK, D, open_block_export(), test_ident_ownership(), test_ident_setattr(), test_ident_traverse(), test_ident_vo_dir(), and test_ident_xattr_sticky().
Referenced by main().
test_lab_caps_mask()
static void test_lab_caps_mask (void) static
Definition at line 1133 of file sd_pblock_unittest.c.
References BRIX_SD_CAP_CATALOG, BRIX_SD_CAP_FD, BRIX_SD_CAP_SENDFILE, CHECK, D, and lab_write_sidecar().
Referenced by main().
test_lab_enumerate()
static void test_lab_enumerate (void) static
Definition at line 1218 of file sd_pblock_unittest.c.
References BRIX_SD_CAP_CATALOG, enum_probe_t::bytes, CHECK, D, enum_probe_cb(), enum_walk(), enum_probe_t::files, enum_probe_t::saw_nested, enum_probe_t::stop_after, and write_file().
Referenced by main().
test_lab_fault_inject()
static void test_lab_fault_inject (void) static
Definition at line 1055 of file sd_pblock_unittest.c.
References BRIX_SD_O_READ, CHECK, D, lab_ctl_set(), lab_write_sidecar(), pb_close(), and write_file().
Referenced by main().
test_lab_gate_closed()
static void test_lab_gate_closed (void) static
Definition at line 1099 of file sd_pblock_unittest.c.
References BRIX_SD_O_READ, CHECK, D, lab_ctl_set(), pb_close(), and write_file().
Referenced by main().
test_preadv()
static void test_preadv (brix_sd_instance_t * inst) static
Definition at line 154 of file sd_pblock_unittest.c.
References BRIX_SD_O_READ, CHECK, D, pb_close(), and write_file().
Referenced by main().
test_processes()
static void test_processes (const char * root, brix_sd_instance_t * inst) static
Definition at line 404 of file sd_pblock_unittest.c.
References CHECK, D, and write_file().
Referenced by main().
test_rename()
static void test_rename (brix_sd_instance_t * inst) static
Definition at line 199 of file sd_pblock_unittest.c.
References CHECK, D, read_file(), and write_file().
Referenced by main().
test_server_copy()
static void test_server_copy (brix_sd_instance_t * inst) static
Definition at line 223 of file sd_pblock_unittest.c.
References CHECK, D, read_file(), and write_file().
Referenced by main().
test_snapshot()
static void test_snapshot (void) static
Definition at line 1617 of file sd_pblock_unittest.c.
References BRIX_SD_O_READ, CHECK, D, break_arg::inst, lab_write_sidecar(), pb_close(), read_file(), and write_file().
Referenced by main().
test_staged()
static void test_staged (brix_sd_instance_t * inst) static
Definition at line 256 of file sd_pblock_unittest.c.
References CHECK, D, read_file(), s, and brix_sd_stat_t::size.
Referenced by main().
test_threads()
static void test_threads (brix_sd_instance_t * inst) static
Definition at line 378 of file sd_pblock_unittest.c.
References CHECK, D, thread_arg::id, thread_arg::inst, thread_arg::ok, thread_arg::ops, and thread_body().
Referenced by main().
test_truncate_and_stat()
static void test_truncate_and_stat (brix_sd_instance_t * inst) static
Definition at line 131 of file sd_pblock_unittest.c.
References BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, D, pb_close(), brix_sd_stat_t::size, and write_file().
Referenced by main().
test_unlink()
static void test_unlink (brix_sd_instance_t * inst) static
Definition at line 286 of file sd_pblock_unittest.c.
References CHECK, D, and write_file().
Referenced by main().
test_versioning()
static void test_versioning (void) static
Definition at line 1696 of file sd_pblock_unittest.c.
References CHECK, D, break_arg::inst, lab_write_sidecar(), PBLOCK_BLOB_ID_CAP, q_blob_id(), q_count(), q_refcount(), read_file(), and staged_put().
Referenced by main().
test_write_read_fstat()
static void test_write_read_fstat (brix_sd_instance_t * inst) static
Definition at line 102 of file sd_pblock_unittest.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_READ, BRIX_SD_O_WRITE, CHECK, D, brix_sd_stat_t::is_reg, pb_close(), read_file(), and brix_sd_stat_t::size.
Referenced by main().
test_xattr()
static void test_xattr (brix_sd_instance_t * inst) static
Definition at line 238 of file sd_pblock_unittest.c.
References CHECK, D, and write_file().
Referenced by main().
thread_body()
static void * thread_body (void * p) static
Definition at line 352 of file sd_pblock_unittest.c.
References thread_arg::id, thread_arg::inst, thread_arg::ok, thread_arg::ops, read_file(), and write_file().
Referenced by test_threads().
trunc_write()
static int trunc_write (brix_sd_instance_t * inst, const char * path, const char * data, size_t len) static
Definition at line 1372 of file sd_pblock_unittest.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_READ, BRIX_SD_O_TRUNC, BRIX_SD_O_WRITE, D, and pb_close().
Referenced by break_body(), and test_dedup_refs().
write_file()
static int write_file (brix_sd_instance_t * inst, const char * path, const char * data, size_t len) static
Definition at line 62 of file sd_pblock_unittest.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_READ, BRIX_SD_O_WRITE, D, and pb_close().
Referenced by test_block_copy_and_unlink(), test_block_size_configurable(), test_block_striping(), test_block_truncate(), test_dedup_forged_hash(), test_dedup_gate_closed(), test_dedup_refs(), test_dirs(), test_lab_enumerate(), test_lab_fault_inject(), test_lab_gate_closed(), test_preadv(), test_processes(), test_rename(), test_server_copy(), test_snapshot(), test_truncate_and_stat(), test_unlink(), test_xattr(), and thread_body().
Variable Documentation
CRED_ALICE
const brix_sd_cred_t CRED_ALICE static
Initial value:
= { .principal = "alice",
                                           .vos = "atlas" }
Definition at line 681 of file sd_pblock_unittest.c.
Referenced by test_ident_ownership(), test_ident_setattr(), test_ident_traverse(), test_ident_vo_dir(), and test_ident_xattr_sticky().
CRED_BOB
const brix_sd_cred_t CRED_BOB static
Initial value:
= { .principal = "bob",
                                           .vos = "cms" }
Definition at line 683 of file sd_pblock_unittest.c.
Referenced by test_ident_ownership(), test_ident_setattr(), test_ident_traverse(), test_ident_vo_dir(), and test_ident_xattr_sticky().
CRED_CAROL
const brix_sd_cred_t CRED_CAROL static
Initial value:
= { .principal = "carol",
                                           .vos = "atlas" }
Definition at line 685 of file sd_pblock_unittest.c.
Referenced by test_ident_ownership(), test_ident_traverse(), test_ident_vo_dir(), and test_ident_xattr_sticky().
D
const brix_sd_driver_t* D static
Definition at line 44 of file sd_pblock_unittest.c.
Referenced by cred_write_file(), enum_walk(), main(), metabench_plan_init(), open_block_export(), pb_close(), read_file(), staged_put(), test_block_copy_and_unlink(), test_block_size_configurable(), test_block_sparse(), test_block_striping(), test_block_truncate(), test_dedup_forged_hash(), test_dedup_gate_closed(), test_dedup_refs(), test_dirs(), test_fsync_durability(), test_ident_ownership(), test_ident_setattr(), test_ident_traverse(), test_ident_vo_dir(), test_ident_xattr_sticky(), test_identity(), test_lab_caps_mask(), test_lab_enumerate(), test_lab_fault_inject(), test_lab_gate_closed(), test_preadv(), test_processes(), test_rename(), test_server_copy(), test_snapshot(), test_staged(), test_threads(), test_truncate_and_stat(), test_unlink(), test_versioning(), test_write_read_fstat(), test_xattr(), trunc_write(), and write_file().
failures
int failures static
Definition at line 32 of file sd_pblock_unittest.c.
Referenced by main().
g_blk_count
long g_blk_count static
Definition at line 465 of file sd_pblock_unittest.c.
Referenced by blk_walk_cb(), scan_blocks(), test_block_copy_and_unlink(), test_block_size_configurable(), test_block_sparse(), test_block_striping(), and test_block_truncate().
g_blk_max
long g_blk_max static
Definition at line 465 of file sd_pblock_unittest.c.
Referenced by blk_walk_cb(), scan_blocks(), test_block_size_configurable(), and test_block_striping().
g_blk_total
long g_blk_total static
Definition at line 465 of file sd_pblock_unittest.c.
Referenced by blk_walk_cb(), scan_blocks(), test_block_size_configurable(), test_block_striping(), and test_block_truncate().