nginx-xrootd: src/fs/backend/rados/sd_ceph.c File Reference
sd_ceph.c File Reference
#include "sd_ceph.h"
#include "sd_ceph_compat.h"
#include <errno.h>
#include <string.h>
Data Structures
struct sd_ceph_seg_t
Functions
static int sd_ceph_next_seg (const char **cursor, sd_ceph_seg_t *seg)
static size_t sd_ceph_norm_pop (char *out, size_t w)
static size_t sd_ceph_norm_append (char *out, size_t cap, size_t w, const sd_ceph_seg_t *seg)
static int sd_ceph_seg_is_dot (const sd_ceph_seg_t *seg)
static int sd_ceph_seg_is_dotdot (const sd_ceph_seg_t *seg)
int sd_ceph_normalize (const char *lfn, char *out, size_t cap)
int sd_ceph_key (const char *key_prefix, const char *lfn, char *out, size_t cap)
uint64_t sd_ceph_ino (const char *oid)
Function Documentation
sd_ceph_ino()
uint64_t sd_ceph_ino (const char * oid)
Definition at line 233 of file sd_ceph.c.
Referenced by test_ino_hash().
sd_ceph_key()
int sd_ceph_key (const char * key_prefix, const char * lfn, char * out, size_t cap)
Definition at line 206 of file sd_ceph.c.
References sd_ceph_normalize().
Referenced by check_key(), and test_key_alias_injectivity().
sd_ceph_next_seg()
static int sd_ceph_next_seg (const char ** cursor, sd_ceph_seg_t * seg) static
Definition at line 92 of file sd_ceph.c.
References sd_ceph_seg_t::len, and sd_ceph_seg_t::start.
Referenced by sd_ceph_normalize().
sd_ceph_norm_append()
static size_t sd_ceph_norm_append (char * out, size_t cap, size_t w, const sd_ceph_seg_t * seg) static
Definition at line 136 of file sd_ceph.c.
References sd_ceph_seg_t::len, and sd_ceph_seg_t::start.
Referenced by sd_ceph_normalize().
sd_ceph_norm_pop()
static size_t sd_ceph_norm_pop (char * out, size_t w) static
Definition at line 117 of file sd_ceph.c.
Referenced by sd_ceph_normalize().
sd_ceph_normalize()
int sd_ceph_normalize (const char * lfn, char * out, size_t cap)
Definition at line 166 of file sd_ceph.c.
References sd_ceph_next_seg(), sd_ceph_norm_append(), sd_ceph_norm_pop(), sd_ceph_seg_is_dot(), and sd_ceph_seg_is_dotdot().
Referenced by check_norm_ok(), check_norm_reject(), and sd_ceph_key().
sd_ceph_seg_is_dot()
static int sd_ceph_seg_is_dot (const sd_ceph_seg_t * seg) static
Definition at line 151 of file sd_ceph.c.
References sd_ceph_seg_t::len, and sd_ceph_seg_t::start.
Referenced by sd_ceph_normalize().
sd_ceph_seg_is_dotdot()
static int sd_ceph_seg_is_dotdot (const sd_ceph_seg_t * seg) static
Definition at line 157 of file sd_ceph.c.
References sd_ceph_seg_t::len, and sd_ceph_seg_t::start.
Referenced by sd_ceph_normalize().