nginx-xrootd: src/fs/backend/pblock/sd_pblock_unittest_lab.c File Reference
sd_pblock_unittest_lab.c File Reference
#include "fs/backend/sd.h"
#include "sd_pblock_catalog.h"
#include "sd_pblock_unittest_internal.h"
#include <errno.h>
#include <ftw.h>
#include <limits.h>
#include <pthread.h>
#include <sqlite3.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>
Data Structures
struct enum_probe_t
Macros
#define _GNU_SOURCE /* nftw(3) + FTW_PHYS for the on-disk block scan */
Functions
void lab_write_sidecar (const char *root, const char *line)
static void lab_ctl_set (const char *root, const char *key, const char *val, long epoch)
void test_lab_fault_inject (void)
void test_lab_gate_closed (void)
void test_lab_caps_mask (void)
static int enum_probe_cb (void *ctx, const brix_sd_catalog_ent_t *ent)
static void enum_walk (brix_sd_instance_t *inst, const char *dir, int *files, int64_t *bytes)
void test_lab_enumerate (void)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE /* nftw(3) + FTW_PHYS for the on-disk block scan */
Definition at line 8 of file sd_pblock_unittest_lab.c.
Function Documentation
enum_probe_cb()
static int enum_probe_cb (void * ctx, const brix_sd_catalog_ent_t * ent) static
Definition at line 186 of file sd_pblock_unittest_lab.c.
References enum_probe_t::bytes, enum_probe_t::files, brix_sd_catalog_ent_t::have_stat, brix_sd_catalog_ent_t::key, brix_sd_catalog_ent_t::path, enum_probe_t::saw_nested, brix_sd_catalog_ent_t::size, and enum_probe_t::stop_after.
Referenced by test_lab_enumerate().
enum_walk()
static void enum_walk (brix_sd_instance_t * inst, const char * dir, int * files, int64_t * bytes) static
Definition at line 206 of file sd_pblock_unittest_lab.c.
References D, enum_walk(), brix_sd_stat_t::is_dir, brix_sd_dirent_t::name, and brix_sd_stat_t::size.
Referenced by enum_walk(), and test_lab_enumerate().
lab_ctl_set()
static void lab_ctl_set (const char * root, const char * key, const char * val, long epoch) static
Definition at line 50 of file sd_pblock_unittest_lab.c.
References CHECK, key, and PATH_MAX.
Referenced by test_lab_fault_inject(), and test_lab_gate_closed().
lab_write_sidecar()
void lab_write_sidecar (const char * root, const char * line)
Definition at line 34 of file sd_pblock_unittest_lab.c.
References CHECK, and PATH_MAX.
Referenced by test_dedup_forged_hash(), test_dedup_refs(), test_lab_caps_mask(), test_lab_fault_inject(), test_snapshot(), and test_versioning().
test_lab_caps_mask()
void test_lab_caps_mask (void)
Definition at line 151 of file sd_pblock_unittest_lab.c.
References BRIX_SD_CAP_CATALOG, BRIX_SD_CAP_FD, BRIX_SD_CAP_SENDFILE, CHECK, D, and lab_write_sidecar().
Referenced by main().
test_lab_enumerate()
void test_lab_enumerate (void)
Definition at line 236 of file sd_pblock_unittest_lab.c.
References BRIX_SD_CAP_CATALOG, enum_probe_t::bytes, CHECK, D, enum_probe_cb(), enum_walk(), enum_probe_t::files, enum_probe_t::saw_nested, enum_probe_t::stop_after, and write_file().
Referenced by main().
test_lab_fault_inject()
void test_lab_fault_inject (void)
Definition at line 73 of file sd_pblock_unittest_lab.c.
References BRIX_SD_O_READ, CHECK, D, lab_ctl_set(), lab_write_sidecar(), pb_close(), and write_file().
Referenced by main().
test_lab_gate_closed()
void test_lab_gate_closed (void)
Definition at line 117 of file sd_pblock_unittest_lab.c.
References BRIX_SD_O_READ, CHECK, D, lab_ctl_set(), pb_close(), and write_file().
Referenced by main().