nginx-xrootd: src/fs/backend/http/sd_http.c File Reference
sd_http.c File Reference
#include "sd_http.h"
#include "sd_http_internal.h"
#include "fs/path/path.h"
#include <errno.h>
#include <stdatomic.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
Data Structures
struct sd_http_obj_state
struct sd_http_staged_state
Macros
#define SD_HTTP_PREAD_MAX (8LL * 1024 * 1024)
Functions
void sd_http_force_primary_set (int on)
static void sd_http_write_path (const sd_http_inst_state *is, const char *key, char *dst, size_t cap)
static int sd_http_ep_score (const sd_http_endpoint *ep)
static sd_http_endpoint * sd_http_pick (sd_http_inst_state *is)
static sd_http_endpoint * sd_http_preferred (sd_http_inst_state *is)
static void sd_http_score (sd_http_endpoint *ep, int ok)
static void sd_http_score_noted (sd_http_inst_state *is, sd_http_endpoint *ep, int ok)
static int sd_http_ep_rank (const sd_http_endpoint *ep)
static const char * sd_http_log_key (const char *key, char *buf, size_t cap)
static void sd_http_log_switch (sd_http_inst_state *is, sd_http_endpoint *ep)
static int sd_http_request_fo (sd_http_inst_state *is, const char *method, const char *key, const char *extra_hdrs, brix_s3_resp_t *resp, sd_http_endpoint **used)
static int sd_http_head_size (sd_http_inst_state *is, const char *key, int64_t *size_out)
static brix_sd_obj_t * sd_http_open (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, int *err_out)
static ngx_int_t sd_http_close (brix_sd_obj_t *obj)
static ssize_t sd_http_pread (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
static ngx_int_t sd_http_fstat (brix_sd_obj_t *obj, brix_sd_stat_t *out)
static ngx_int_t sd_http_stat (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out)
static brix_sd_staged_t * sd_http_staged_open (brix_sd_instance_t *inst, const char *final_path, mode_t mode, int *err_out)
static ssize_t sd_http_staged_write (brix_sd_staged_t *h, const void *buf, size_t len, off_t off)
static ngx_int_t sd_http_staged_commit (brix_sd_staged_t *h, int noreplace)
static void sd_http_staged_abort (brix_sd_staged_t *h)
static ngx_int_t sd_http_unlink (brix_sd_instance_t *inst, const char *path, int is_dir)
int sd_http_instance_is (const brix_sd_instance_t *inst)
brix_sd_instance_t * brix_sd_http_create (const brix_sd_http_cfg_t *cfg, ngx_log_t *log)
void brix_sd_http_destroy (brix_sd_instance_t *inst)
Variables
static int g_sd_http_force_primary
static const brix_sd_driver_t brix_sd_http_driver
Macro Definition Documentation
SD_HTTP_PREAD_MAX
#define SD_HTTP_PREAD_MAX (8LL * 1024 * 1024)
Definition at line 21 of file sd_http.c.
Function Documentation
brix_sd_http_create()
brix_sd_instance_t * brix_sd_http_create (const brix_sd_http_cfg_t * cfg, ngx_log_t * log)
Definition at line 639 of file sd_http.c.
References sd_http_inst_state::auth_hdr, brix_sd_http_ep_cfg_t::base_path, brix_sd_http_cfg_t::base_path, sd_http_endpoint::base_path, brix_sd_http_cfg_t::bearer_token, brix_sd_http_driver, sd_http_inst_state::cur_ep, sd_http_inst_state::eps, brix_sd_http_cfg_t::extra, brix_sd_http_cfg_t::failover_note, sd_http_inst_state::failover_note, brix_sd_http_cfg_t::health_note, sd_http_inst_state::health_note, brix_sd_http_ep_cfg_t::host, brix_sd_http_cfg_t::host, sd_http_endpoint::host, log, sd_http_inst_state::log, sd_http_inst_state::n_eps, brix_sd_http_cfg_t::n_extra, brix_sd_http_ep_cfg_t::port, brix_sd_http_cfg_t::port, sd_http_endpoint::port, SD_HTTP_EP_MAX, brix_sd_http_cfg_t::tctx, sd_http_inst_state::tctx, brix_sd_http_cfg_t::timeout_ms, sd_http_inst_state::timeout_ms, brix_sd_http_ep_cfg_t::tls, brix_sd_http_cfg_t::tls, sd_http_endpoint::tls, brix_sd_http_cfg_t::transport, and sd_http_inst_state::transport.
Referenced by brix_tier_build(), and brix_vfs_backend_build_source().
brix_sd_http_destroy()
void brix_sd_http_destroy (brix_sd_instance_t * inst)
Definition at line 708 of file sd_http.c.
sd_http_close()
static ngx_int_t sd_http_close (brix_sd_obj_t * obj) static
Definition at line 391 of file sd_http.c.
sd_http_ep_rank()
static int sd_http_ep_rank (const sd_http_endpoint * ep) static
Definition at line 134 of file sd_http.c.
References sd_http_endpoint::rank.
Referenced by sd_http_log_switch(), and sd_http_request_fo().
sd_http_ep_score()
static int sd_http_ep_score (const sd_http_endpoint * ep) static
Definition at line 67 of file sd_http.c.
References sd_http_endpoint::fail_score, sd_http_endpoint::rank, and SD_HTTP_RANK_WEIGHT.
Referenced by sd_http_pick(), and sd_http_request_fo().
sd_http_force_primary_set()
void sd_http_force_primary_set (int on)
Definition at line 33 of file sd_http.c.
References g_sd_http_force_primary.
Referenced by ngx_http_brix_cvmfs_merge_loc_conf().
sd_http_fstat()
static ngx_int_t sd_http_fstat (brix_sd_obj_t * obj, brix_sd_stat_t * out) static
Definition at line 459 of file sd_http.c.
sd_http_head_size()
static int sd_http_head_size (sd_http_inst_state * is, const char * key, int64_t * size_out) static
Definition at line 314 of file sd_http.c.
References sd_http_inst_state::auth_hdr, key, brix_s3_transport_t::resp_free, brix_s3_transport_t::resp_header, sd_http_request_fo(), brix_s3_resp_t::status, and sd_http_inst_state::transport.
Referenced by sd_http_open(), and sd_http_stat().
sd_http_instance_is()
int sd_http_instance_is (const brix_sd_instance_t * inst)
Definition at line 632 of file sd_http.c.
References brix_sd_http_driver.
Referenced by sd_http_endpoint_list(), sd_http_health_snapshot(), sd_http_last_origin(), sd_http_last_was_failover(), sd_http_n_endpoints(), and sd_http_set_ranks().
sd_http_log_key()
static const char * sd_http_log_key (const char * key, char * buf, size_t cap) static
Definition at line 143 of file sd_http.c.
References brix_sanitize_log_string(), and key.
Referenced by sd_http_request_fo().
sd_http_log_switch()
static void sd_http_log_switch (sd_http_inst_state * is, sd_http_endpoint * ep) static
Definition at line 155 of file sd_http.c.
References sd_http_inst_state::cur_ep, sd_http_inst_state::eps, sd_http_endpoint::fail_score, sd_http_endpoint::host, sd_http_inst_state::log, sd_http_inst_state::n_eps, sd_http_endpoint::port, sd_http_ep_rank(), and sd_http_preferred().
Referenced by sd_http_request_fo().
sd_http_open()
static brix_sd_obj_t * sd_http_open (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, int * err_out) static
Definition at line 345 of file sd_http.c.
References BRIX_SD_O_APPEND, BRIX_SD_O_CREATE, BRIX_SD_O_TRUNC, BRIX_SD_O_WRITE, sd_http_obj_state::key, mode, and sd_http_head_size().
sd_http_pick()
static sd_http_endpoint * sd_http_pick (sd_http_inst_state * is) static
Definition at line 76 of file sd_http.c.
References sd_http_inst_state::eps, sd_http_inst_state::n_eps, and sd_http_ep_score().
Referenced by sd_http_request_fo().
sd_http_pread()
static ssize_t sd_http_pread (brix_sd_obj_t * obj, void * buf, size_t len, off_t off) static
Definition at line 401 of file sd_http.c.
References sd_http_inst_state::auth_hdr, sd_http_obj_state::key, brix_s3_transport_t::resp_body, brix_s3_transport_t::resp_free, SD_HTTP_AUTH_MAX, SD_HTTP_PREAD_MAX, sd_http_request_fo(), brix_s3_resp_t::status, and sd_http_inst_state::transport.
sd_http_preferred()
static sd_http_endpoint * sd_http_preferred (sd_http_inst_state * is) static
Definition at line 91 of file sd_http.c.
References sd_http_inst_state::eps, sd_http_inst_state::n_eps, and sd_http_endpoint::rank.
Referenced by sd_http_log_switch(), and sd_http_request_fo().
sd_http_request_fo()
static int sd_http_request_fo (sd_http_inst_state * is, const char * method, const char * key, const char * extra_hdrs, brix_s3_resp_t * resp, sd_http_endpoint ** used) static
Definition at line 199 of file sd_http.c.
References sd_http_endpoint::base_path, sd_http_inst_state::eps, sd_http_endpoint::fail_score, sd_http_inst_state::failover_note, g_sd_http_force_primary, sd_http_endpoint::host, key, sd_http_inst_state::last_failover, sd_http_inst_state::last_origin, sd_http_inst_state::log, sd_http_inst_state::n_eps, sd_http_endpoint::port, sd_http_inst_state::probe_tick, brix_s3_transport_t::request, sd_http_ep_rank(), sd_http_ep_score(), sd_http_log_key(), sd_http_log_switch(), SD_HTTP_PATH_MAX, sd_http_pick(), sd_http_preferred(), sd_http_score_noted(), sd_http_inst_state::tctx, sd_http_inst_state::timeout_ms, sd_http_endpoint::tls, and sd_http_inst_state::transport.
Referenced by sd_http_head_size(), and sd_http_pread().
sd_http_score()
static void sd_http_score (sd_http_endpoint * ep, int ok) static
Definition at line 108 of file sd_http.c.
References sd_http_endpoint::fail_score.
Referenced by sd_http_score_noted().
sd_http_score_noted()
static void sd_http_score_noted (sd_http_inst_state * is, sd_http_endpoint * ep, int ok) static
Definition at line 117 of file sd_http.c.
References sd_http_endpoint::fail_score, sd_http_inst_state::health_note, sd_http_endpoint::host, sd_http_endpoint::port, and sd_http_score().
Referenced by sd_http_request_fo().
sd_http_staged_abort()
static void sd_http_staged_abort (brix_sd_staged_t * h) static
Definition at line 574 of file sd_http.c.
References sd_http_staged_state::buf.
sd_http_staged_commit()
static ngx_int_t sd_http_staged_commit (brix_sd_staged_t * h, int noreplace) static
Definition at line 541 of file sd_http.c.
References sd_http_inst_state::auth_hdr, sd_http_staged_state::buf, sd_http_inst_state::eps, sd_http_endpoint::host, sd_http_staged_state::len, sd_http_staged_state::path, sd_http_endpoint::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_free, brix_s3_resp_t::status, sd_http_inst_state::tctx, sd_http_inst_state::timeout_ms, sd_http_endpoint::tls, and sd_http_inst_state::transport.
sd_http_staged_open()
static brix_sd_staged_t * sd_http_staged_open (brix_sd_instance_t * inst, const char * final_path, mode_t mode, int * err_out) static
Definition at line 487 of file sd_http.c.
References mode, sd_http_staged_state::path, and sd_http_write_path().
sd_http_staged_write()
static ssize_t sd_http_staged_write (brix_sd_staged_t * h, const void * buf, size_t len, off_t off) static
Definition at line 510 of file sd_http.c.
References sd_http_staged_state::buf, sd_http_staged_state::cap, and sd_http_staged_state::len.
sd_http_stat()
static ngx_int_t sd_http_stat (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out) static
Definition at line 466 of file sd_http.c.
References brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, sd_http_head_size(), and brix_sd_stat_t::size.
sd_http_unlink()
static ngx_int_t sd_http_unlink (brix_sd_instance_t * inst, const char * path, int is_dir) static
Definition at line 584 of file sd_http.c.
References sd_http_inst_state::auth_hdr, sd_http_inst_state::eps, sd_http_endpoint::host, sd_http_endpoint::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_free, SD_HTTP_PATH_MAX, sd_http_write_path(), brix_s3_resp_t::status, sd_http_inst_state::tctx, sd_http_inst_state::timeout_ms, sd_http_endpoint::tls, and sd_http_inst_state::transport.
sd_http_write_path()
static void sd_http_write_path (const sd_http_inst_state * is, const char * key, char * dst, size_t cap) static
Definition at line 58 of file sd_http.c.
References sd_http_endpoint::base_path, sd_http_inst_state::eps, and key.
Referenced by sd_http_staged_open(), and sd_http_unlink().
Variable Documentation
brix_sd_http_driver
const brix_sd_driver_t brix_sd_http_driver static
Initial value:
= {
    .name  = "http",
    .caps  = BRIX_SD_CAP_RANGE_READ | BRIX_SD_CAP_RANDOM_WRITE,
    .open  = sd_http_open,
    .close = sd_http_close,
    .pread = sd_http_pread,
    .fstat = sd_http_fstat,
    .stat  = sd_http_stat,
    .unlink        = sd_http_unlink,
    .staged_open   = sd_http_staged_open,
    .staged_write  = sd_http_staged_write,
    .staged_commit = sd_http_staged_commit,
    .staged_abort  = sd_http_staged_abort,
}
Definition at line 613 of file sd_http.c.
Referenced by brix_sd_http_create(), and sd_http_instance_is().
g_sd_http_force_primary
int g_sd_http_force_primary static
Definition at line 30 of file sd_http.c.
Referenced by sd_http_force_primary_set(), and sd_http_request_fo().