nginx-xrootd: src/fs/backend/cache/sd_cache_forward.c File Reference
sd_cache_forward.c File Reference
#include "sd_cache.h"
#include "sd_cache_internal.h"
#include "sd_cache_policy.h"
#include "protocols/cvmfs/classify.h"
#include "observability/metrics/metrics.h"
#include "observability/metrics/metrics_macros.h"
#include "fs/cache/cstore.h"
#include "fs/backend/http/sd_http.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Functions
ngx_int_t sd_cache_stat (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out)
ngx_int_t sd_cache_unlink (brix_sd_instance_t *inst, const char *path, int is_dir)
ngx_int_t sd_cache_mkdir (brix_sd_instance_t *inst, const char *path, mode_t mode)
ngx_int_t sd_cache_rename (brix_sd_instance_t *inst, const char *src, const char *dst, int noreplace)
ngx_int_t sd_cache_server_copy (brix_sd_instance_t *inst, const char *src, const char *dst, off_t *bytes_out)
ngx_int_t sd_cache_setattr (brix_sd_instance_t *inst, const char *path, const brix_sd_setattr_t *attr)
brix_sd_dir_t * sd_cache_opendir (brix_sd_instance_t *inst, const char *path, int *err_out)
ngx_int_t sd_cache_readdir (brix_sd_dir_t *d, brix_sd_dirent_t *out)
ngx_int_t sd_cache_closedir (brix_sd_dir_t *d)
ssize_t sd_cache_getxattr (brix_sd_instance_t *inst, const char *path, const char *name, void *buf, size_t cap)
ssize_t sd_cache_listxattr (brix_sd_instance_t *inst, const char *path, void *buf, size_t cap)
ngx_int_t sd_cache_setxattr (brix_sd_instance_t *inst, const char *path, const char *name, const void *val, size_t len, int flags)
ngx_int_t sd_cache_removexattr (brix_sd_instance_t *inst, const char *path, const char *name)
brix_sd_staged_t * sd_cache_staged_open (brix_sd_instance_t *inst, const char *final_path, mode_t mode, int *err_out)
brix_sd_staged_t * sd_cache_staged_open_cred (brix_sd_instance_t *inst, const char *final_path, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
ssize_t sd_cache_staged_write (brix_sd_staged_t *st, const void *buf, size_t len, off_t off)
ngx_int_t sd_cache_staged_commit (brix_sd_staged_t *st, int noreplace)
void sd_cache_staged_abort (brix_sd_staged_t *st)
Function Documentation
sd_cache_closedir()
ngx_int_t sd_cache_closedir (brix_sd_dir_t * d)
Definition at line 151 of file sd_cache_forward.c.
sd_cache_getxattr()
ssize_t sd_cache_getxattr (brix_sd_instance_t * inst, const char * path, const char * name, void * buf, size_t cap)
Definition at line 157 of file sd_cache_forward.c.
References name, s, and SD_CACHE_SRC.
sd_cache_listxattr()
ssize_t sd_cache_listxattr (brix_sd_instance_t * inst, const char * path, void * buf, size_t cap)
Definition at line 170 of file sd_cache_forward.c.
References s, and SD_CACHE_SRC.
sd_cache_mkdir()
ngx_int_t sd_cache_mkdir (brix_sd_instance_t * inst, const char * path, mode_t mode)
Definition at line 88 of file sd_cache_forward.c.
References s, and SD_CACHE_SRC.
sd_cache_opendir()
brix_sd_dir_t * sd_cache_opendir (brix_sd_instance_t * inst, const char * path, int * err_out)
Definition at line 129 of file sd_cache_forward.c.
References s, and SD_CACHE_SRC.
sd_cache_readdir()
ngx_int_t sd_cache_readdir (brix_sd_dir_t * d, brix_sd_dirent_t * out)
Definition at line 143 of file sd_cache_forward.c.
sd_cache_removexattr()
ngx_int_t sd_cache_removexattr (brix_sd_instance_t * inst, const char * path, const char * name)
Definition at line 196 of file sd_cache_forward.c.
References name, s, and SD_CACHE_SRC.
sd_cache_rename()
ngx_int_t sd_cache_rename (brix_sd_instance_t * inst, const char * src, const char * dst, int noreplace)
Definition at line 95 of file sd_cache_forward.c.
References brix_cstore_evict(), sd_cache_inst_state::cstore, s, SD_CACHE_ST, and sd_cache_inst_state::source.
sd_cache_server_copy()
ngx_int_t sd_cache_server_copy (brix_sd_instance_t * inst, const char * src, const char * dst, off_t * bytes_out)
Definition at line 112 of file sd_cache_forward.c.
References s, and SD_CACHE_SRC.
sd_cache_setattr()
ngx_int_t sd_cache_setattr (brix_sd_instance_t * inst, const char * path, const brix_sd_setattr_t * attr)
Definition at line 121 of file sd_cache_forward.c.
References s, and SD_CACHE_SRC.
sd_cache_setxattr()
ngx_int_t sd_cache_setxattr (brix_sd_instance_t * inst, const char * path, const char * name, const void * val, size_t len, int flags)
Definition at line 183 of file sd_cache_forward.c.
References name, s, and SD_CACHE_SRC.
sd_cache_staged_abort()
void sd_cache_staged_abort (brix_sd_staged_t * st)
Definition at line 272 of file sd_cache_forward.c.
sd_cache_staged_commit()
ngx_int_t sd_cache_staged_commit (brix_sd_staged_t * st, int noreplace)
Definition at line 265 of file sd_cache_forward.c.
sd_cache_staged_open()
brix_sd_staged_t * sd_cache_staged_open (brix_sd_instance_t * inst, const char * final_path, mode_t mode, int * err_out)
Definition at line 211 of file sd_cache_forward.c.
References brix_cstore_evict(), sd_cache_inst_state::cstore, s, SD_CACHE_ST, and sd_cache_inst_state::source.
sd_cache_staged_open_cred()
brix_sd_staged_t * sd_cache_staged_open_cred (brix_sd_instance_t * inst, const char * final_path, mode_t mode, const brix_sd_cred_t * cred, int * err_out)
Definition at line 240 of file sd_cache_forward.c.
References brix_cstore_evict(), brix_sd_staged_open_maybe_cred(), sd_cache_inst_state::cstore, s, SD_CACHE_ST, and sd_cache_inst_state::source.
sd_cache_staged_write()
ssize_t sd_cache_staged_write (brix_sd_staged_t * st, const void * buf, size_t len, off_t off)
Definition at line 257 of file sd_cache_forward.c.
sd_cache_stat()
ngx_int_t sd_cache_stat (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out)
Definition at line 45 of file sd_cache_forward.c.
References BRIX_CINFO_F_COMPLETE, brix_cstore_cinfo_load(), sd_cache_inst_state::cstore, brix_sd_stat_t::ctime, brix_cache_cinfo_t::flags, brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, brix_cache_cinfo_t::mode, brix_sd_stat_t::mtime, brix_cache_cinfo_t::mtime, s, SD_CACHE_SRC, SD_CACHE_ST, brix_sd_stat_t::size, and brix_cache_cinfo_t::size.
sd_cache_unlink()
ngx_int_t sd_cache_unlink (brix_sd_instance_t * inst, const char * path, int is_dir)
Definition at line 74 of file sd_cache_forward.c.
References brix_cstore_evict(), sd_cache_inst_state::cstore, s, SD_CACHE_ST, and sd_cache_inst_state::source.