nginx-xrootd: src/fs/backend/s3/sd_s3.h File Reference
sd_s3.h File Reference
#include "sd_s3_transport.h"
#include "fs/backend/meta_advisory.h"
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>
Data Structures
struct sd_s3_open_params
struct sd_s3_meta_buf
struct sd_s3_meta_kv
Functions
sd_s3_file * sd_s3_open_read (const sd_s3_open_params *p, char *errbuf, size_t errcap)
int sd_s3_size (sd_s3_file *f, int64_t *out_size, char *errbuf, size_t errcap)
ssize_t sd_s3_pread (sd_s3_file *f, void *buf, size_t n, off_t off, char *errbuf, size_t errcap)
sd_s3_file * sd_s3_open_write (const sd_s3_open_params *p, int64_t expected_size, int64_t part_size, char *errbuf, size_t errcap)
int sd_s3_pwrite (sd_s3_file *f, const void *buf, size_t n, off_t off, char *errbuf, size_t errcap)
int sd_s3_commit (sd_s3_file *f, char *errbuf, size_t errcap)
void sd_s3_abort (sd_s3_file *f)
int64_t sd_s3_write_size (const sd_s3_file *f)
void sd_s3_close (sd_s3_file *f)
int sd_s3_delete (const sd_s3_open_params *p, char *errbuf, size_t errcap)
ssize_t sd_s3_get_meta (sd_s3_file *f, const char *name, const sd_s3_meta_buf *out, char *errbuf, size_t errcap)
ssize_t sd_s3_list_meta (sd_s3_file *f, char *buf, size_t cap, char *errbuf, size_t errcap)
int sd_s3_set_meta (const sd_s3_open_params *p, const sd_s3_meta_kv *kv, size_t nkv, char *errbuf, size_t errcap)
int sd_s3_get_unixattr (sd_s3_file *f, brix_meta_advisory_t *out, char *errbuf, size_t errcap)
int sd_s3_set_unixattr (const sd_s3_open_params *p, const brix_meta_advisory_t *a, char *errbuf, size_t errcap)
Function Documentation
sd_s3_abort()
void sd_s3_abort (sd_s3_file * f)
Definition at line 508 of file sd_s3_write.c.
References sd_s3_file::is_mpu, sd_s3_file::is_write, sd_s3_file::put_len, and sd_s3_mpu_abort().
Referenced by s3_abort(), sd_remote_staged_abort(), and sd_remote_staged_open_impl().
sd_s3_close()
void sd_s3_close (sd_s3_file * f)
Definition at line 239 of file sd_s3.c.
References sd_s3_file::etags, sd_s3_file::part_buf, and sd_s3_file::put_buf.
Referenced by s3_be_stat(), s3_close(), sd_remote_close(), sd_remote_getxattr(), sd_remote_listxattr(), sd_remote_open_impl(), sd_remote_staged_abort(), sd_remote_staged_commit(), sd_remote_staged_open_impl(), sd_remote_stat_impl(), sd_s3_delete(), sd_s3_open_write(), and sd_s3_set_meta().
sd_s3_commit()
int sd_s3_commit (sd_s3_file * f, char * errbuf, size_t errcap)
Definition at line 458 of file sd_s3_write.c.
References sd_s3_file::host, sd_s3_file::is_mpu, sd_s3_file::is_write, sd_s3_file::key, sd_s3_file::part_count, sd_s3_file::port, sd_s3_file::put_buf, sd_s3_file::put_checksum, sd_s3_file::put_len, brix_s3_transport_t::request, brix_s3_transport_t::resp_free, SD_S3_AUTH_HDRS_CAP, sd_s3_ck_crc32(), sd_s3_mpu_complete(), sd_s3_mpu_flush(), sd_s3_mpu_upload_part(), sd_s3_set_err(), sd_s3_sign(), sd_s3_sign_ex(), sd_s3_status_err(), brix_s3_resp_t::status, sd_s3_file::tctx, sd_s3_file::timeout_ms, sd_s3_file::tls, and sd_s3_file::transport.
Referenced by s3_commit(), and sd_remote_staged_commit().
sd_s3_delete()
int sd_s3_delete (const sd_s3_open_params * p, char * errbuf, size_t errcap)
Definition at line 207 of file sd_s3.c.
References sd_s3_file::host, sd_s3_file::key, sd_s3_file::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_free, SD_S3_AUTH_HDRS_CAP, sd_s3_close(), sd_s3_open_read(), sd_s3_set_err(), sd_s3_sign(), sd_s3_status_err(), brix_s3_resp_t::status, sd_s3_file::tctx, sd_s3_file::timeout_ms, sd_s3_file::tls, and sd_s3_file::transport.
Referenced by sd_remote_unlink_impl().
sd_s3_get_meta()
ssize_t sd_s3_get_meta (sd_s3_file * f, const char * name, const sd_s3_meta_buf * out, char * errbuf, size_t errcap)
Definition at line 29 of file sd_s3_meta.c.
References sd_s3_meta_buf::buf, sd_s3_meta_buf::cap, sd_s3_file::host, sd_s3_file::key, name, sd_s3_file::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_free, brix_s3_transport_t::resp_header, SD_S3_AUTH_HDRS_CAP, sd_s3_set_err(), sd_s3_sign(), sd_s3_status_err(), brix_s3_resp_t::status, sd_s3_file::tctx, sd_s3_file::timeout_ms, sd_s3_file::tls, and sd_s3_file::transport.
Referenced by sd_remote_getxattr(), and sd_s3_get_unixattr().
sd_s3_get_unixattr()
int sd_s3_get_unixattr (sd_s3_file * f, brix_meta_advisory_t * out, char * errbuf, size_t errcap)
Definition at line 171 of file sd_s3_meta.c.
References brix_meta_advisory_decode(), BRIX_META_ADVISORY_S3META, sd_s3_get_meta(), and sd_s3_set_err().
sd_s3_list_meta()
ssize_t sd_s3_list_meta (sd_s3_file * f, char * buf, size_t cap, char * errbuf, size_t errcap)
Definition at line 90 of file sd_s3_meta.c.
References BRIX_META_ADVISORY_S3META, sd_s3_file::host, sd_s3_file::key, name, sd_s3_file::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_free, brix_s3_transport_t::resp_headers_raw, SD_S3_AUTH_HDRS_CAP, sd_s3_list_meta_emit(), sd_s3_set_err(), sd_s3_sign(), sd_s3_status_err(), brix_s3_resp_t::status, sd_s3_file::tctx, sd_s3_file::timeout_ms, sd_s3_file::tls, and sd_s3_file::transport.
Referenced by sd_remote_listxattr().
sd_s3_open_read()
sd_s3_file * sd_s3_open_read (const sd_s3_open_params * p, char * errbuf, size_t errcap)
Definition at line 35 of file sd_s3.c.
References sd_s3_open_params::ak, sd_s3_file::ak, sd_s3_open_params::host, sd_s3_file::host, sd_s3_open_params::key, sd_s3_file::key, sd_s3_file::obj_size, sd_s3_open_params::port, sd_s3_file::port, sd_s3_open_params::region, sd_s3_file::region, sd_s3_set_err(), sd_s3_open_params::sk, sd_s3_file::sk, sd_s3_open_params::tctx, sd_s3_file::tctx, sd_s3_open_params::timeout_ms, sd_s3_file::timeout_ms, sd_s3_open_params::tls, sd_s3_file::tls, sd_s3_open_params::transport, and sd_s3_file::transport.
Referenced by s3_open_read(), sd_remote_meta_open(), sd_remote_open_impl(), sd_remote_staged_commit(), sd_remote_stat_impl(), sd_s3_delete(), sd_s3_open_write(), and sd_s3_set_meta().
sd_s3_open_write()
sd_s3_file * sd_s3_open_write (const sd_s3_open_params * p, int64_t expected_size, int64_t part_size, char * errbuf, size_t errcap)
Definition at line 313 of file sd_s3_write.c.
References sd_s3_file::is_mpu, sd_s3_file::is_write, sd_s3_file::lazy_mpu, sd_s3_file::part_buf, sd_s3_file::part_size, sd_s3_file::put_buf, sd_s3_file::put_cap, sd_s3_open_params::put_checksum, sd_s3_file::put_checksum, sd_s3_close(), sd_s3_mpu_abort(), sd_s3_mpu_create(), sd_s3_open_read(), SD_S3_PUT_BUF_INIT, and sd_s3_set_err().
Referenced by s3_be_open(), and sd_remote_staged_open_impl().
sd_s3_pread()
ssize_t sd_s3_pread (sd_s3_file * f, void * buf, size_t n, off_t off, char * errbuf, size_t errcap)
Definition at line 99 of file sd_s3.c.
References sd_s3_file::host, sd_s3_file::key, sd_s3_file::obj_size, sd_s3_file::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_body, brix_s3_transport_t::resp_free, brix_s3_transport_t::resp_header, SD_S3_AUTH_HDRS_CAP, SD_S3_PREAD_MAX, sd_s3_set_err(), sd_s3_sign(), sd_s3_status_err(), brix_s3_resp_t::status, sd_s3_file::tctx, sd_s3_file::timeout_ms, sd_s3_file::tls, and sd_s3_file::transport.
Referenced by s3_pread(), and sd_remote_pread().
sd_s3_pwrite()
int sd_s3_pwrite (sd_s3_file * f, const void * buf, size_t n, off_t off, char * errbuf, size_t errcap)
Definition at line 395 of file sd_s3_write.c.
References sd_s3_file::is_mpu, sd_s3_file::is_write, sd_s3_file::lazy_mpu, sd_s3_file::mpu_write_off, sd_s3_file::part_buf, sd_s3_file::part_buf_len, sd_s3_file::part_size, sd_s3_file::put_buf, sd_s3_file::put_cap, sd_s3_file::put_len, sd_s3_file::put_write_off, sd_s3_check_sequential(), sd_s3_mpu_flush(), SD_S3_PUT_BUF_INIT, sd_s3_put_upgrade_mpu(), and sd_s3_set_err().
Referenced by s3_pwrite(), and sd_remote_staged_write().
sd_s3_set_meta()
int sd_s3_set_meta (const sd_s3_open_params * p, const sd_s3_meta_kv * kv, size_t nkv, char * errbuf, size_t errcap)
Definition at line 510 of file sd_s3_meta.c.
References sd_s3_close(), sd_s3_open_read(), and sd_s3_set_meta_f().
Referenced by sd_s3_set_unixattr().
sd_s3_set_unixattr()
int sd_s3_set_unixattr (const sd_s3_open_params * p, const brix_meta_advisory_t * a, char * errbuf, size_t errcap)
Definition at line 526 of file sd_s3_meta.c.
References brix_meta_advisory_encode(), BRIX_META_ADVISORY_S3META, sd_s3_set_err(), sd_s3_set_meta(), and kv::value.
sd_s3_size()
int sd_s3_size (sd_s3_file * f, int64_t * out_size, char * errbuf, size_t errcap)
Definition at line 64 of file sd_s3.c.
References sd_s3_file::host, sd_s3_file::key, sd_s3_file::obj_size, sd_s3_file::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_free, brix_s3_transport_t::resp_header, SD_S3_AUTH_HDRS_CAP, sd_s3_set_err(), sd_s3_sign(), sd_s3_status_err(), brix_s3_resp_t::status, sd_s3_file::tctx, sd_s3_file::timeout_ms, sd_s3_file::tls, and sd_s3_file::transport.
Referenced by s3_load_size(), sd_remote_open_impl(), sd_remote_staged_commit(), and sd_remote_stat_impl().
sd_s3_write_size()
int64_t sd_s3_write_size (const sd_s3_file * f)
Definition at line 521 of file sd_s3_write.c.
References sd_s3_file::is_mpu, sd_s3_file::mpu_write_off, and sd_s3_file::put_len.
Referenced by s3_fstat().