nginx-xrootd: src/fs/backend/s3/sd_s3.c File Reference
sd_s3.c File Reference
#include "sd_s3.h"
#include "sd_s3_internal.h"
#include "core/compat/crypto.h"
#include "core/compat/hex.h"
#include "core/compat/sigv4.h"
#include "core/compat/uri.h"
#include "core/compat/host_format.h"
#include <errno.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
Functions
void sd_s3_set_err (char *errbuf, size_t errcap, const char *fmt,...)
void sd_s3_utc_now (char amzdate[20], char datestamp[12])
void sd_s3_sha256_hex (const void *data, size_t len, char *out)
int sd_s3_sign (const sd_s3_file *f, const char *method, const char *canon_qs, char *hdrs, size_t hdrsz)
int sd_s3_status_err (int status, const char *op, const char *key, char *errbuf, size_t errcap)
sd_s3_file * sd_s3_open_read (const sd_s3_open_params *p, char *errbuf, size_t errcap)
int sd_s3_size (sd_s3_file *f, int64_t *out_size, char *errbuf, size_t errcap)
ssize_t sd_s3_pread (sd_s3_file *f, void *buf, size_t n, off_t off, char *errbuf, size_t errcap)
int sd_s3_delete (const sd_s3_open_params *p, char *errbuf, size_t errcap)
static int sd_s3_xml_tag (const char *xml, const char *tag, char *out, size_t outsz)
static int sd_s3_etag_ensure_cap (sd_s3_file *f, int needed, char *errbuf, size_t errcap)
static int sd_s3_mpu_upload_part (sd_s3_file *f, int part_num, const void *data, size_t len, char *errbuf, size_t errcap)
static int sd_s3_mpu_flush (sd_s3_file *f, char *errbuf, size_t errcap)
static int sd_s3_mpu_create (sd_s3_file *f, char *errbuf, size_t errcap)
static int sd_s3_mpu_complete (sd_s3_file *f, char *errbuf, size_t errcap)
static void sd_s3_mpu_abort (sd_s3_file *f)
static int sd_s3_check_sequential (int64_t off, int64_t expected, char *errbuf, size_t errcap)
sd_s3_file * sd_s3_open_write (const sd_s3_open_params *p, int64_t expected_size, int64_t part_size, char *errbuf, size_t errcap)
int sd_s3_pwrite (sd_s3_file *f, const void *buf, size_t n, off_t off, char *errbuf, size_t errcap)
int sd_s3_commit (sd_s3_file *f, char *errbuf, size_t errcap)
void sd_s3_abort (sd_s3_file *f)
int64_t sd_s3_write_size (const sd_s3_file *f)
void sd_s3_close (sd_s3_file *f)
Function Documentation
sd_s3_abort()
void sd_s3_abort (sd_s3_file * f)
Definition at line 727 of file sd_s3.c.
References sd_s3_file::is_mpu, sd_s3_file::is_write, sd_s3_file::put_len, and sd_s3_mpu_abort().
Referenced by s3_abort(), sd_remote_staged_abort(), and sd_remote_staged_open().
sd_s3_check_sequential()
static int sd_s3_check_sequential (int64_t off, int64_t expected, char * errbuf, size_t errcap) static
Definition at line 575 of file sd_s3.c.
References sd_s3_set_err().
Referenced by sd_s3_pwrite().
sd_s3_close()
void sd_s3_close (sd_s3_file * f)
Definition at line 746 of file sd_s3.c.
References sd_s3_file::etags, sd_s3_file::part_buf, and sd_s3_file::put_buf.
Referenced by s3_be_stat(), s3_close(), sd_remote_close(), sd_remote_open(), sd_remote_staged_abort(), sd_remote_staged_commit(), sd_remote_staged_open(), sd_remote_stat(), sd_s3_delete(), sd_s3_open_write(), and sd_s3_set_meta().
sd_s3_commit()
int sd_s3_commit (sd_s3_file * f, char * errbuf, size_t errcap)
Definition at line 688 of file sd_s3.c.
References sd_s3_file::host, sd_s3_file::is_mpu, sd_s3_file::is_write, sd_s3_file::key, sd_s3_file::part_count, sd_s3_file::port, sd_s3_file::put_buf, sd_s3_file::put_len, brix_s3_transport_t::request, brix_s3_transport_t::resp_free, SD_S3_AUTH_HDRS_CAP, sd_s3_mpu_complete(), sd_s3_mpu_flush(), sd_s3_mpu_upload_part(), sd_s3_set_err(), sd_s3_sign(), sd_s3_status_err(), brix_s3_resp_t::status, sd_s3_file::tctx, sd_s3_file::timeout_ms, sd_s3_file::tls, and sd_s3_file::transport.
Referenced by s3_commit(), and sd_remote_staged_commit().
sd_s3_delete()
int sd_s3_delete (const sd_s3_open_params * p, char * errbuf, size_t errcap)
Definition at line 304 of file sd_s3.c.
References sd_s3_file::host, sd_s3_file::key, sd_s3_file::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_free, SD_S3_AUTH_HDRS_CAP, sd_s3_close(), sd_s3_open_read(), sd_s3_set_err(), sd_s3_sign(), sd_s3_status_err(), brix_s3_resp_t::status, sd_s3_file::tctx, sd_s3_file::timeout_ms, sd_s3_file::tls, and sd_s3_file::transport.
Referenced by sd_remote_unlink().
sd_s3_etag_ensure_cap()
static int sd_s3_etag_ensure_cap (sd_s3_file * f, int needed, char * errbuf, size_t errcap) static
Definition at line 360 of file sd_s3.c.
References sd_s3_file::etag_cap, sd_s3_file::etags, SD_S3_ETAG_INIT_CAP, and sd_s3_set_err().
Referenced by sd_s3_mpu_upload_part().
sd_s3_mpu_abort()
static void sd_s3_mpu_abort (sd_s3_file * f) static
Definition at line 553 of file sd_s3.c.
References sd_s3_file::host, sd_s3_file::key, sd_s3_file::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_free, SD_S3_AUTH_HDRS_CAP, SD_S3_KEY_MAX, sd_s3_sign(), SD_S3_UPLOAD_ID_LEN, sd_s3_file::tctx, sd_s3_file::timeout_ms, sd_s3_file::tls, sd_s3_file::transport, and sd_s3_file::upload_id.
Referenced by sd_s3_abort(), and sd_s3_open_write().
sd_s3_mpu_complete()
static int sd_s3_mpu_complete (sd_s3_file * f, char * errbuf, size_t errcap) static
Definition at line 483 of file sd_s3.c.
References sd_s3_file::etags, sd_s3_file::host, sd_s3_file::key, sd_s3_file::part_count, sd_s3_file::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_free, SD_S3_AUTH_HDRS_CAP, SD_S3_ETAG_LEN, SD_S3_KEY_MAX, sd_s3_set_err(), sd_s3_sign(), sd_s3_status_err(), SD_S3_UPLOAD_ID_LEN, brix_s3_resp_t::status, sd_s3_file::tctx, sd_s3_file::timeout_ms, sd_s3_file::tls, sd_s3_file::transport, sd_s3_file::upload_id, and sd_s3_part_etag::val.
Referenced by sd_s3_commit().
sd_s3_mpu_create()
static int sd_s3_mpu_create (sd_s3_file * f, char * errbuf, size_t errcap) static
Definition at line 441 of file sd_s3.c.
References sd_s3_file::host, sd_s3_file::key, sd_s3_file::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_body, brix_s3_transport_t::resp_free, SD_S3_AUTH_HDRS_CAP, SD_S3_KEY_MAX, sd_s3_set_err(), sd_s3_sign(), sd_s3_status_err(), sd_s3_xml_tag(), brix_s3_resp_t::status, sd_s3_file::tctx, sd_s3_file::timeout_ms, sd_s3_file::tls, sd_s3_file::transport, and sd_s3_file::upload_id.
Referenced by sd_s3_open_write().
sd_s3_mpu_flush()
static int sd_s3_mpu_flush (sd_s3_file * f, char * errbuf, size_t errcap) static
Definition at line 429 of file sd_s3.c.
References sd_s3_file::part_buf, sd_s3_file::part_buf_len, sd_s3_file::part_count, and sd_s3_mpu_upload_part().
Referenced by sd_s3_commit(), and sd_s3_pwrite().
sd_s3_mpu_upload_part()
static int sd_s3_mpu_upload_part (sd_s3_file * f, int part_num, const void * data, size_t len, char * errbuf, size_t errcap) static
Definition at line 379 of file sd_s3.c.
References sd_s3_file::etags, sd_s3_file::host, sd_s3_file::key, sd_s3_file::part_count, sd_s3_file::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_free, brix_s3_transport_t::resp_header, SD_S3_AUTH_HDRS_CAP, sd_s3_etag_ensure_cap(), SD_S3_ETAG_LEN, SD_S3_KEY_MAX, sd_s3_set_err(), sd_s3_sign(), sd_s3_status_err(), brix_s3_resp_t::status, sd_s3_file::tctx, sd_s3_file::timeout_ms, sd_s3_file::tls, sd_s3_file::transport, sd_s3_file::upload_id, and sd_s3_part_etag::val.
Referenced by sd_s3_commit(), and sd_s3_mpu_flush().
sd_s3_open_read()
sd_s3_file * sd_s3_open_read (const sd_s3_open_params * p, char * errbuf, size_t errcap)
Definition at line 184 of file sd_s3.c.
References sd_s3_open_params::ak, sd_s3_file::ak, sd_s3_open_params::host, sd_s3_file::host, sd_s3_open_params::key, sd_s3_file::key, sd_s3_file::obj_size, sd_s3_open_params::port, sd_s3_file::port, sd_s3_open_params::region, sd_s3_file::region, sd_s3_set_err(), sd_s3_open_params::sk, sd_s3_file::sk, sd_s3_open_params::tctx, sd_s3_file::tctx, sd_s3_open_params::timeout_ms, sd_s3_file::timeout_ms, sd_s3_open_params::tls, sd_s3_file::tls, sd_s3_open_params::transport, and sd_s3_file::transport.
Referenced by s3_open_read(), sd_remote_open(), sd_remote_stat(), sd_s3_delete(), sd_s3_open_write(), and sd_s3_set_meta().
sd_s3_open_write()
sd_s3_file * sd_s3_open_write (const sd_s3_open_params * p, int64_t expected_size, int64_t part_size, char * errbuf, size_t errcap)
Definition at line 588 of file sd_s3.c.
References sd_s3_file::is_mpu, sd_s3_file::is_write, sd_s3_file::part_buf, sd_s3_file::part_size, sd_s3_file::put_buf, sd_s3_file::put_cap, sd_s3_close(), sd_s3_mpu_abort(), sd_s3_mpu_create(), sd_s3_open_read(), SD_S3_PUT_BUF_INIT, and sd_s3_set_err().
Referenced by s3_be_open(), and sd_remote_staged_open().
sd_s3_pread()
ssize_t sd_s3_pread (sd_s3_file * f, void * buf, size_t n, off_t off, char * errbuf, size_t errcap)
Definition at line 248 of file sd_s3.c.
References sd_s3_file::host, sd_s3_file::key, sd_s3_file::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_body, brix_s3_transport_t::resp_free, SD_S3_AUTH_HDRS_CAP, SD_S3_PREAD_MAX, sd_s3_set_err(), sd_s3_sign(), sd_s3_status_err(), brix_s3_resp_t::status, sd_s3_file::tctx, sd_s3_file::timeout_ms, sd_s3_file::tls, and sd_s3_file::transport.
Referenced by s3_pread(), and sd_remote_pread().
sd_s3_pwrite()
int sd_s3_pwrite (sd_s3_file * f, const void * buf, size_t n, off_t off, char * errbuf, size_t errcap)
Definition at line 631 of file sd_s3.c.
References sd_s3_file::is_mpu, sd_s3_file::is_write, sd_s3_file::mpu_write_off, sd_s3_file::part_buf, sd_s3_file::part_buf_len, sd_s3_file::part_size, sd_s3_file::put_buf, sd_s3_file::put_cap, sd_s3_file::put_len, sd_s3_file::put_write_off, sd_s3_check_sequential(), sd_s3_mpu_flush(), SD_S3_PUT_BUF_INIT, and sd_s3_set_err().
Referenced by s3_pwrite(), and sd_remote_staged_write().
sd_s3_set_err()
void sd_s3_set_err (char * errbuf, size_t errcap, const char * fmt, ...)
Definition at line 35 of file sd_s3.c.
Referenced by sd_s3_check_sequential(), sd_s3_commit(), sd_s3_delete(), sd_s3_etag_ensure_cap(), sd_s3_get_meta(), sd_s3_get_unixattr(), sd_s3_mpu_complete(), sd_s3_mpu_create(), sd_s3_mpu_upload_part(), sd_s3_open_read(), sd_s3_open_write(), sd_s3_pread(), sd_s3_pwrite(), sd_s3_set_meta_f(), sd_s3_set_unixattr(), sd_s3_size(), and sd_s3_status_err().
sd_s3_sha256_hex()
void sd_s3_sha256_hex (const void * data, size_t len, char * out)
Definition at line 90 of file sd_s3.c.
References brix_hex_encode(), and brix_sha256().
Referenced by sd_s3_sign(), and sd_s3_sign_ext().
sd_s3_sign()
int sd_s3_sign (const sd_s3_file * f, const char * method, const char * canon_qs, char * hdrs, size_t hdrsz)
Definition at line 101 of file sd_s3.c.
References sd_s3_file::ak, brix_format_host_port(), brix_hex_encode(), brix_hmac_sha256(), brix_http_urlencode(), brix_sigv4_signing_key(), sd_s3_file::host, sd_s3_file::key, sd_s3_file::port, sd_s3_file::region, sd_s3_sha256_hex(), sd_s3_utc_now(), and sd_s3_file::sk.
Referenced by sd_s3_commit(), sd_s3_delete(), sd_s3_get_meta(), sd_s3_mpu_abort(), sd_s3_mpu_complete(), sd_s3_mpu_create(), sd_s3_mpu_upload_part(), sd_s3_pread(), and sd_s3_size().
sd_s3_size()
int sd_s3_size (sd_s3_file * f, int64_t * out_size, char * errbuf, size_t errcap)
Definition at line 213 of file sd_s3.c.
References sd_s3_file::host, sd_s3_file::key, sd_s3_file::obj_size, sd_s3_file::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_free, brix_s3_transport_t::resp_header, SD_S3_AUTH_HDRS_CAP, sd_s3_set_err(), sd_s3_sign(), sd_s3_status_err(), brix_s3_resp_t::status, sd_s3_file::tctx, sd_s3_file::timeout_ms, sd_s3_file::tls, and sd_s3_file::transport.
Referenced by s3_load_size(), sd_remote_open(), and sd_remote_stat().
sd_s3_status_err()
int sd_s3_status_err (int status, const char * op, const char * key, char * errbuf, size_t errcap)
Definition at line 164 of file sd_s3.c.
References key, and sd_s3_set_err().
Referenced by sd_s3_commit(), sd_s3_delete(), sd_s3_get_meta(), sd_s3_mpu_complete(), sd_s3_mpu_create(), sd_s3_mpu_upload_part(), sd_s3_pread(), sd_s3_set_meta_f(), and sd_s3_size().
sd_s3_utc_now()
void sd_s3_utc_now (char amzdate[20], char datestamp[12])
Definition at line 50 of file sd_s3.c.
Referenced by sd_s3_sign(), and sd_s3_sign_ext().
sd_s3_write_size()
int64_t sd_s3_write_size (const sd_s3_file * f)
Definition at line 740 of file sd_s3.c.
References sd_s3_file::is_mpu, sd_s3_file::mpu_write_off, and sd_s3_file::put_len.
Referenced by s3_fstat().
sd_s3_xml_tag()
static int sd_s3_xml_tag (const char * xml, const char * tag, char * out, size_t outsz) static
Definition at line 339 of file sd_s3.c.
Referenced by sd_s3_mpu_create().