nginx-xrootd: src/fs/backend/http/sd_http_internal.h File Reference
sd_http_internal.h File Reference
#include "sd_http.h"
#include <stdatomic.h>
Data Structures
struct sd_http_endpoint
struct sd_http_inst_state
struct sd_http_req_t
Macros
#define SD_HTTP_BASE_MAX 512 /* URL base path prefix */
#define SD_HTTP_PATH_MAX 2048 /* full URL path = base + key */
#define SD_HTTP_AUTH_MAX 4160 /* "Authorization: Bearer <tok>\r\n" */
#define SD_HTTP_RANK_WEIGHT 4096
Functions
int sd_http_instance_is (const brix_sd_instance_t *inst)
void sd_http_write_path (const sd_http_inst_state *is, const char *key, char *dst, size_t cap)
int sd_http_request_fo (const sd_http_req_t *rq, sd_http_endpoint **used)
int sd_http_cred_gate (sd_http_inst_state *is, const brix_sd_cred_t *cred)
const char * sd_http_resolve_open_cred (sd_http_inst_state *is, const brix_sd_cred_t *cred, char *open_auth, size_t auth_cap)
brix_sd_obj_t * sd_http_open (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, int *err_out)
brix_sd_obj_t * sd_http_open_cred (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
ngx_int_t sd_http_close (brix_sd_obj_t *obj)
ssize_t sd_http_pread (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
ngx_int_t sd_http_fstat (brix_sd_obj_t *obj, brix_sd_stat_t *out)
ngx_int_t sd_http_stat (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out)
ngx_int_t sd_http_stat_cred (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out, const brix_sd_cred_t *cred)
brix_sd_staged_t * sd_http_staged_open (brix_sd_instance_t *inst, const char *final_path, mode_t mode, int *err_out)
brix_sd_staged_t * sd_http_staged_open_cred (brix_sd_instance_t *inst, const char *final_path, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
ssize_t sd_http_staged_write (brix_sd_staged_t *h, const void *buf, size_t len, off_t off)
ngx_int_t sd_http_staged_commit (brix_sd_staged_t *h, int noreplace)
void sd_http_staged_abort (brix_sd_staged_t *h)
ngx_int_t sd_http_unlink (brix_sd_instance_t *inst, const char *path, int is_dir)
Variables
int g_sd_http_force_primary
Macro Definition Documentation
SD_HTTP_AUTH_MAX
#define SD_HTTP_AUTH_MAX 4160 /* "Authorization: Bearer <tok>\r\n" */
Definition at line 19 of file sd_http_internal.h.
SD_HTTP_BASE_MAX
#define SD_HTTP_BASE_MAX 512 /* URL base path prefix */
Definition at line 17 of file sd_http_internal.h.
SD_HTTP_PATH_MAX
#define SD_HTTP_PATH_MAX 2048 /* full URL path = base + key */
Definition at line 18 of file sd_http_internal.h.
SD_HTTP_RANK_WEIGHT
#define SD_HTTP_RANK_WEIGHT 4096
Definition at line 36 of file sd_http_internal.h.
Function Documentation
sd_http_close()
ngx_int_t sd_http_close (brix_sd_obj_t * obj)
Definition at line 305 of file sd_http_read.c.
sd_http_cred_gate()
int sd_http_cred_gate (sd_http_inst_state * is, const brix_sd_cred_t * cred)
Definition at line 108 of file sd_http_read.c.
References brix_sd_cred_t::bearer, brix_sd_cred_t::fallback_deny, brix_s3_transport_t::request_cred, sd_http_inst_state::transport, and brix_sd_cred_t::x509_proxy.
Referenced by sd_http_open_common(), sd_http_staged_open_common(), and sd_http_stat_cred().
sd_http_fstat()
ngx_int_t sd_http_fstat (brix_sd_obj_t * obj, brix_sd_stat_t * out)
Definition at line 383 of file sd_http_read.c.
sd_http_instance_is()
int sd_http_instance_is (const brix_sd_instance_t * inst)
Definition at line 55 of file sd_http.c.
References brix_sd_http_driver.
Referenced by sd_http_endpoint_list(), sd_http_health_snapshot(), sd_http_last_origin(), sd_http_last_was_failover(), sd_http_n_endpoints(), sd_http_penalize_last_origin(), and sd_http_set_ranks().
sd_http_open()
brix_sd_obj_t * sd_http_open (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, int * err_out)
Definition at line 279 of file sd_http_read.c.
References sd_http_open_common().
sd_http_open_cred()
brix_sd_obj_t * sd_http_open_cred (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, const brix_sd_cred_t * cred, int * err_out)
Definition at line 296 of file sd_http_read.c.
References sd_http_open_common().
sd_http_pread()
ssize_t sd_http_pread (brix_sd_obj_t * obj, void * buf, size_t len, off_t off)
Definition at line 315 of file sd_http_read.c.
References sd_http_inst_state::auth_hdr, sd_http_obj_state::auth_hdr, sd_http_obj_state::cert_pem, g_sd_http_force_primary, sd_http_obj_state::key, brix_s3_transport_t::resp_body, brix_s3_transport_t::resp_free, SD_HTTP_AUTH_MAX, SD_HTTP_PREAD_MAX, sd_http_request_fo(), brix_s3_resp_t::status, and sd_http_inst_state::transport.
sd_http_request_fo()
int sd_http_request_fo (const sd_http_req_t * rq, sd_http_endpoint ** used)
Definition at line 385 of file sd_http_select.c.
References sd_http_endpoint::fail_score, sd_http_req_t::force_primary, sd_http_req_t::is, sd_http_req_t::key, sd_http_req_t::method, sd_http_inst_state::n_eps, sd_http_fo_next(), sd_http_fo_note_fail(), sd_http_fo_note_success(), sd_http_fo_perform(), sd_http_fo_select(), sd_http_live_log(), and sd_http_log_key().
Referenced by sd_http_head_size(), and sd_http_pread().
sd_http_resolve_open_cred()
const char * sd_http_resolve_open_cred (sd_http_inst_state * is, const brix_sd_cred_t * cred, char * open_auth, size_t auth_cap)
Definition at line 140 of file sd_http_read.c.
References brix_sd_cred_t::bearer, brix_s3_transport_t::request_cred, sd_http_inst_state::transport, and brix_sd_cred_t::x509_proxy.
Referenced by sd_http_open_common(), and sd_http_stat_cred().
sd_http_staged_abort()
void sd_http_staged_abort (brix_sd_staged_t * h)
Definition at line 227 of file sd_http_write.c.
References sd_http_staged_state::buf.
sd_http_staged_commit()
ngx_int_t sd_http_staged_commit (brix_sd_staged_t * h, int noreplace)
Definition at line 173 of file sd_http_write.c.
References sd_http_inst_state::auth_hdr, sd_http_staged_state::auth_hdr, sd_http_staged_state::buf, sd_http_staged_state::cert_pem, sd_http_inst_state::eps, sd_http_endpoint::host, sd_http_staged_state::len, sd_http_staged_state::path, sd_http_endpoint::port, brix_s3_transport_t::request, brix_s3_transport_t::request_cred, brix_s3_transport_t::resp_free, brix_s3_resp_t::status, sd_http_inst_state::tctx, sd_http_inst_state::timeout_ms, sd_http_endpoint::tls, and sd_http_inst_state::transport.
sd_http_staged_open()
brix_sd_staged_t * sd_http_staged_open (brix_sd_instance_t * inst, const char * final_path, mode_t mode, int * err_out)
Definition at line 118 of file sd_http_write.c.
References sd_http_staged_open_common().
sd_http_staged_open_cred()
brix_sd_staged_t * sd_http_staged_open_cred (brix_sd_instance_t * inst, const char * final_path, mode_t mode, const brix_sd_cred_t * cred, int * err_out)
Definition at line 135 of file sd_http_write.c.
References sd_http_staged_open_common().
sd_http_staged_write()
ssize_t sd_http_staged_write (brix_sd_staged_t * h, const void * buf, size_t len, off_t off)
Definition at line 142 of file sd_http_write.c.
References sd_http_staged_state::buf, sd_http_staged_state::cap, sd_http_staged_state::len, and ngx_memcpy.
sd_http_stat()
ngx_int_t sd_http_stat (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out)
Definition at line 407 of file sd_http_read.c.
References sd_http_inst_state::auth_hdr, sd_http_head_size(), and sd_http_stat_fill().
sd_http_stat_cred()
ngx_int_t sd_http_stat_cred (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out, const brix_sd_cred_t * cred)
Definition at line 446 of file sd_http_read.c.
References sd_http_inst_state::auth_hdr, SD_HTTP_AUTH_MAX, sd_http_cred_gate(), sd_http_head_size(), sd_http_resolve_open_cred(), and sd_http_stat_fill().
sd_http_unlink()
ngx_int_t sd_http_unlink (brix_sd_instance_t * inst, const char * path, int is_dir)
Definition at line 237 of file sd_http_write.c.
References sd_http_inst_state::auth_hdr, sd_http_inst_state::eps, sd_http_endpoint::host, sd_http_endpoint::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_free, SD_HTTP_PATH_MAX, sd_http_write_path(), brix_s3_resp_t::status, sd_http_inst_state::tctx, sd_http_inst_state::timeout_ms, sd_http_endpoint::tls, and sd_http_inst_state::transport.
sd_http_write_path()
void sd_http_write_path (const sd_http_inst_state * is, const char * key, char * dst, size_t cap)
Definition at line 53 of file sd_http_select.c.
References sd_http_endpoint::base_path, sd_http_inst_state::eps, and key.
Referenced by sd_http_staged_open_common(), and sd_http_unlink().
Variable Documentation
g_sd_http_force_primary
int g_sd_http_force_primary extern
Definition at line 41 of file sd_http_select.c.
Referenced by sd_http_force_primary_set(), sd_http_head_size(), and sd_http_pread().