nginx-xrootd: src/fs/backend/pblock/sd_pblock_catalog_unittest.c File Reference
sd_pblock_catalog_unittest.c File Reference
#include "sd_pblock_catalog.h"
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/xattr.h>
#include <time.h>
#include <unistd.h>
Macros
#define CHECK(cond, ...)
Functions
static pblock_meta file_meta (const char *blob_id, int64_t size)
static pblock_meta dir_meta (void)
static void test_put_lookup (pblock_catalog *cat)
static void test_parent_gate (pblock_catalog *cat)
static void test_touch (pblock_catalog *cat)
static void test_children_and_remove (pblock_catalog *cat)
static void test_rename_subtree (pblock_catalog *cat)
static void test_opendir (pblock_catalog *cat)
static void test_xattr (pblock_catalog *cat)
static void test_id_map (pblock_catalog *cat)
static void test_setattr_owner (pblock_catalog *cat)
static void test_xattr_flags (pblock_catalog *cat)
static void test_parent_lookup (pblock_catalog *cat)
int main (void)
Variables
static int failures
Macro Definition Documentation
CHECK
#define CHECK (cond, ...)
Value:
    do {                                                                       \
        if (!(cond)) {                                                         \
            fprintf(stderr, "FAIL %s:%d: ", __func__, __LINE__);              \
            fprintf(stderr, __VA_ARGS__);                                      \
            fprintf(stderr, "\n");                                             \
            failures++;                                                        \
        }                                                                      \
    } while (0)
Definition at line 24 of file sd_pblock_catalog_unittest.c.
Function Documentation
dir_meta()
static pblock_meta dir_meta (void) static
Definition at line 51 of file sd_pblock_catalog_unittest.c.
References pblock_meta::ctime, pblock_meta::is_dir, pblock_meta::mode, and pblock_meta::mtime.
Referenced by test_children_and_remove(), test_opendir(), test_parent_lookup(), and test_rename_subtree().
file_meta()
static pblock_meta file_meta (const char * blob_id, int64_t size) static
Definition at line 35 of file sd_pblock_catalog_unittest.c.
References pblock_meta::blob_id, pblock_meta::block_size, pblock_meta::ctime, pblock_meta::is_dir, pblock_meta::mode, pblock_meta::mtime, and pblock_meta::size.
Referenced by test_children_and_remove(), test_opendir(), test_parent_lookup(), test_put_lookup(), test_rename_subtree(), test_setattr_owner(), test_touch(), test_xattr(), and test_xattr_flags().
main()
int main (void)
Definition at line 381 of file sd_pblock_catalog_unittest.c.
References CHECK, failures, pblock_catalog_close(), pblock_catalog_open(), test_children_and_remove(), test_id_map(), test_opendir(), test_parent_gate(), test_parent_lookup(), test_put_lookup(), test_rename_subtree(), test_setattr_owner(), test_touch(), test_xattr(), and test_xattr_flags().
test_children_and_remove()
static void test_children_and_remove (pblock_catalog * cat) static
Definition at line 145 of file sd_pblock_catalog_unittest.c.
References CHECK, dir_meta(), file_meta(), pblock_catalog_child_count(), pblock_catalog_lookup(), pblock_catalog_put(), and pblock_catalog_remove().
Referenced by main().
test_id_map()
static void test_id_map (pblock_catalog * cat) static
Definition at line 245 of file sd_pblock_catalog_unittest.c.
References CHECK, pblock_catalog_id_map(), PBLOCK_ID_BASE, PBLOCK_ID_GROUP, and PBLOCK_ID_USER.
Referenced by main().
test_opendir()
static void test_opendir (pblock_catalog * cat) static
Definition at line 184 of file sd_pblock_catalog_unittest.c.
References CHECK, dir_meta(), file_meta(), name, pblock_catalog_closedir(), pblock_catalog_opendir(), pblock_catalog_put(), and pblock_catalog_readdir().
Referenced by main().
test_parent_gate()
static void test_parent_gate (pblock_catalog * cat) static
Definition at line 85 of file sd_pblock_catalog_unittest.c.
References CHECK, pblock_meta::is_dir, pblock_meta::mode, pblock_catalog_create(), pblock_catalog_lookup(), pblock_catalog_put(), pblock_catalog_remove(), and pblock_catalog_rename().
Referenced by main().
test_parent_lookup()
static void test_parent_lookup (pblock_catalog * cat) static
Definition at line 354 of file sd_pblock_catalog_unittest.c.
References CHECK, dir_meta(), file_meta(), pblock_meta::is_dir, pblock_meta::mode, pblock_catalog_parent_lookup(), pblock_catalog_put(), and pblock_meta::uid.
Referenced by main().
test_put_lookup()
static void test_put_lookup (pblock_catalog * cat) static
Definition at line 65 of file sd_pblock_catalog_unittest.c.
References pblock_meta::blob_id, pblock_meta::block_size, CHECK, file_meta(), pblock_meta::is_dir, pblock_meta::mode, pblock_catalog_lookup(), pblock_catalog_put(), and pblock_meta::size.
Referenced by main().
test_rename_subtree()
static void test_rename_subtree (pblock_catalog * cat) static
Definition at line 163 of file sd_pblock_catalog_unittest.c.
References CHECK, dir_meta(), file_meta(), pblock_catalog_lookup(), pblock_catalog_put(), and pblock_catalog_rename().
Referenced by main().
test_setattr_owner()
static void test_setattr_owner (pblock_catalog * cat) static
Definition at line 272 of file sd_pblock_catalog_unittest.c.
References CHECK, pblock_meta::ctime, file_meta(), pblock_meta::gid, pblock_meta::mode, pblock_catalog_lookup(), pblock_catalog_put(), pblock_catalog_setattr(), and pblock_meta::uid.
Referenced by main().
test_touch()
static void test_touch (pblock_catalog * cat) static
Definition at line 127 of file sd_pblock_catalog_unittest.c.
References CHECK, file_meta(), pblock_meta::mtime, pblock_catalog_lookup(), pblock_catalog_put(), pblock_catalog_touch(), and pblock_meta::size.
Referenced by main().
test_xattr()
static void test_xattr (pblock_catalog * cat) static
Definition at line 219 of file sd_pblock_catalog_unittest.c.
References CHECK, file_meta(), pblock_catalog_getxattr(), pblock_catalog_listxattr(), pblock_catalog_put(), pblock_catalog_removexattr(), and pblock_catalog_setxattr().
Referenced by main().
test_xattr_flags()
static void test_xattr_flags (pblock_catalog * cat) static
Definition at line 306 of file sd_pblock_catalog_unittest.c.
References CHECK, file_meta(), pblock_catalog_getxattr(), pblock_catalog_listxattr(), pblock_catalog_put(), pblock_catalog_removexattr(), and pblock_catalog_setxattr().
Referenced by main().
Variable Documentation
failures
int failures static
Definition at line 22 of file sd_pblock_catalog_unittest.c.
Referenced by main().