nginx-xrootd: src/fs/backend/http/sd_http_write.c File Reference
sd_http_write.c File Reference
#include "sd_http_internal.h"
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <openssl/evp.h>
Data Structures
struct sd_http_staged_state
Functions
static void sd_http_content_md5 (const void *buf, size_t len, char out[25])
static brix_sd_staged_t * sd_http_staged_open_common (brix_sd_instance_t *inst, const char *final_path, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
brix_sd_staged_t * sd_http_staged_open (brix_sd_instance_t *inst, const char *final_path, mode_t mode, int *err_out)
brix_sd_staged_t * sd_http_staged_open_cred (brix_sd_instance_t *inst, const char *final_path, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
ssize_t sd_http_staged_write (brix_sd_staged_t *h, const void *buf, size_t len, off_t off)
ngx_int_t sd_http_staged_commit (brix_sd_staged_t *h, int noreplace)
void sd_http_staged_abort (brix_sd_staged_t *h)
ngx_int_t sd_http_unlink (brix_sd_instance_t *inst, const char *path, int is_dir)
Function Documentation
sd_http_content_md5()
static void sd_http_content_md5 (const void * buf, size_t len, char out[25]) static
Definition at line 39 of file sd_http_write.c.
Referenced by sd_http_staged_commit().
sd_http_staged_abort()
void sd_http_staged_abort (brix_sd_staged_t * h)
Definition at line 267 of file sd_http_write.c.
References sd_http_staged_state::buf.
sd_http_staged_commit()
ngx_int_t sd_http_staged_commit (brix_sd_staged_t * h, int noreplace)
Definition at line 192 of file sd_http_write.c.
References sd_http_inst_state::auth_hdr, sd_http_staged_state::auth_hdr, sd_http_staged_state::buf, sd_http_staged_state::cert_pem, sd_http_inst_state::eps, sd_http_endpoint::host, sd_http_staged_state::len, sd_http_staged_state::path, sd_http_endpoint::port, sd_http_inst_state::put_checksum, brix_s3_transport_t::request, brix_s3_transport_t::request_cred, brix_s3_transport_t::resp_free, SD_HTTP_AUTH_MAX, sd_http_content_md5(), brix_s3_resp_t::status, sd_http_inst_state::tctx, sd_http_inst_state::timeout_ms, sd_http_endpoint::tls, and sd_http_inst_state::transport.
sd_http_staged_open()
brix_sd_staged_t * sd_http_staged_open (brix_sd_instance_t * inst, const char * final_path, mode_t mode, int * err_out)
Definition at line 137 of file sd_http_write.c.
References sd_http_staged_open_common().
sd_http_staged_open_common()
static brix_sd_staged_t * sd_http_staged_open_common (brix_sd_instance_t * inst, const char * final_path, mode_t mode, const brix_sd_cred_t * cred, int * err_out) static
Definition at line 90 of file sd_http_write.c.
References sd_http_staged_state::auth_hdr, brix_sd_cred_t::bearer, sd_http_staged_state::cert_pem, sd_http_staged_state::path, brix_s3_transport_t::request_cred, sd_http_cred_gate(), sd_http_write_path(), sd_http_inst_state::transport, and brix_sd_cred_t::x509_proxy.
Referenced by sd_http_staged_open(), and sd_http_staged_open_cred().
sd_http_staged_open_cred()
brix_sd_staged_t * sd_http_staged_open_cred (brix_sd_instance_t * inst, const char * final_path, mode_t mode, const brix_sd_cred_t * cred, int * err_out)
Definition at line 154 of file sd_http_write.c.
References sd_http_staged_open_common().
sd_http_staged_write()
ssize_t sd_http_staged_write (brix_sd_staged_t * h, const void * buf, size_t len, off_t off)
Definition at line 161 of file sd_http_write.c.
References sd_http_staged_state::buf, sd_http_staged_state::cap, sd_http_staged_state::len, and ngx_memcpy.
sd_http_unlink()
ngx_int_t sd_http_unlink (brix_sd_instance_t * inst, const char * path, int is_dir)
Definition at line 277 of file sd_http_write.c.
References sd_http_inst_state::auth_hdr, sd_http_inst_state::eps, sd_http_endpoint::host, sd_http_endpoint::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_free, SD_HTTP_PATH_MAX, sd_http_write_path(), brix_s3_resp_t::status, sd_http_inst_state::tctx, sd_http_inst_state::timeout_ms, sd_http_endpoint::tls, and sd_http_inst_state::transport.