nginx-xrootd: src/fs/backend/frm/sd_frm_mss.h File Reference
sd_frm_mss.h File Reference
#include "sd_frm.h"
Functions
void * brix_mss_stub_create (const char *location, ngx_log_t *log)
void * brix_mss_exec_create (const char *location, const char *stagecmd, ngx_log_t *log)
void frm_mkparents (const char *path)
int stub_copyfile (const char *src, const char *dst, mode_t mode)
Variables
const brix_mss_adapter_t brix_mss_stub_adapter
const brix_mss_adapter_t brix_mss_exec_adapter
Function Documentation
brix_mss_exec_create()
void * brix_mss_exec_create (const char * location, const char * stagecmd, ngx_log_t * log)
Definition at line 201 of file sd_frm_exec.c.
References exec_ctx_t::base, log, exec_ctx_t::log, and exec_ctx_t::stagecmd.
Referenced by frm_select_exec_adapter().
brix_mss_stub_create()
void * brix_mss_stub_create (const char * location, ngx_log_t * log)
Definition at line 301 of file sd_frm_stub.c.
References stub_ctx_t::base, log, stub_ctx_t::log, and stub_ctx_t::recall_delay_ms.
Referenced by frm_select_stub_adapter().
frm_mkparents()
void frm_mkparents (const char * path)
Definition at line 61 of file sd_frm_stub.c.
References PATH_MAX.
Referenced by exec_create_online(), exec_recall_begin(), stub_copyfile(), stub_create_online(), and stub_recall_begin().
stub_copyfile()
int stub_copyfile (const char * src, const char * dst, mode_t mode)
Definition at line 82 of file sd_frm_stub.c.
References close(), frm_mkparents(), open(), and read().
Referenced by stub_migrate(), stub_recall_begin(), and stub_recall_poll().
Variable Documentation
brix_mss_exec_adapter
const brix_mss_adapter_t brix_mss_exec_adapter extern
Definition at line 185 of file sd_frm_exec.c.
Referenced by frm_select_exec_adapter().
brix_mss_stub_adapter
const brix_mss_adapter_t brix_mss_stub_adapter extern
Definition at line 285 of file sd_frm_stub.c.
Referenced by frm_select_stub_adapter().