nginx-xrootd: src/fs/backend/http/sd_http.h File Reference
sd_http.h File Reference
#include "fs/backend/sd.h"
#include "fs/backend/s3/sd_s3_transport.h"
Data Structures
struct brix_sd_http_ep_cfg_t
struct brix_sd_http_cfg_t
Macros
#define SD_HTTP_EP_MAX 8
#define BRIX_SD_HTTP_DEFAULT_TIMEOUT_MS 60000
Functions
brix_sd_instance_t * brix_sd_http_create (const brix_sd_http_cfg_t *cfg, ngx_log_t *log)
void brix_sd_http_destroy (brix_sd_instance_t *inst)
void sd_http_force_primary_set (int on)
void sd_http_set_ranks (brix_sd_instance_t *inst, const int *ranks, int n)
void sd_http_penalize_last_origin (brix_sd_instance_t *inst)
int sd_http_endpoint_list (brix_sd_instance_t *inst, char hosts[][256], int *ports, int max)
int sd_http_n_endpoints (brix_sd_instance_t *inst)
int sd_http_last_origin (brix_sd_instance_t *inst, char *buf, size_t cap)
int sd_http_last_was_failover (brix_sd_instance_t *inst)
int sd_http_health_snapshot (brix_sd_instance_t *inst, char hosts[][256], int *ports, int *scores, int max)
Macro Definition Documentation
BRIX_SD_HTTP_DEFAULT_TIMEOUT_MS
#define BRIX_SD_HTTP_DEFAULT_TIMEOUT_MS 60000
Definition at line 40 of file sd_http.h.
SD_HTTP_EP_MAX
#define SD_HTTP_EP_MAX 8
Definition at line 37 of file sd_http.h.
Function Documentation
brix_sd_http_create()
brix_sd_instance_t * brix_sd_http_create (const brix_sd_http_cfg_t * cfg, ngx_log_t * log)
Definition at line 126 of file sd_http.c.
References sd_http_inst_state::auth_hdr, brix_sd_http_cfg_t::bearer_token, BRIX_SD_HTTP_DEFAULT_TIMEOUT_MS, brix_sd_http_driver, sd_http_inst_state::cur_ep, brix_sd_http_cfg_t::failover_note, sd_http_inst_state::failover_note, brix_sd_http_cfg_t::health_note, sd_http_inst_state::health_note, brix_sd_http_cfg_t::host, log, sd_http_inst_state::log, brix_sd_http_cfg_t::port, brix_sd_http_cfg_t::put_checksum, sd_http_inst_state::put_checksum, sd_http_init_endpoints(), sd_http_init_tctx(), brix_sd_http_cfg_t::timeout_ms, sd_http_inst_state::timeout_ms, brix_sd_http_cfg_t::transport, and sd_http_inst_state::transport.
Referenced by brix_vbr_build_http(), and tier_build_http().
brix_sd_http_destroy()
void brix_sd_http_destroy (brix_sd_instance_t * inst)
Definition at line 174 of file sd_http.c.
sd_http_endpoint_list()
int sd_http_endpoint_list (brix_sd_instance_t * inst, char hosts[][256], int * ports, int max)
Definition at line 64 of file sd_http_introspect.c.
References sd_http_inst_state::eps, sd_http_endpoint::host, sd_http_inst_state::n_eps, sd_http_endpoint::port, and sd_http_instance_is().
sd_http_force_primary_set()
void sd_http_force_primary_set (int on)
Definition at line 44 of file sd_http_select.c.
References g_sd_http_force_primary.
Referenced by cvmfs_merge_resilience().
sd_http_health_snapshot()
int sd_http_health_snapshot (brix_sd_instance_t * inst, char hosts[][256], int * ports, int * scores, int max)
Definition at line 120 of file sd_http_introspect.c.
References sd_http_inst_state::eps, sd_http_endpoint::fail_score, sd_http_endpoint::host, sd_http_inst_state::n_eps, sd_http_endpoint::port, and sd_http_instance_is().
Referenced by health_build_json().
sd_http_last_origin()
int sd_http_last_origin (brix_sd_instance_t * inst, char * buf, size_t cap)
Definition at line 93 of file sd_http_introspect.c.
References sd_http_inst_state::last_origin, and sd_http_instance_is().
Referenced by cvmfs_var_origin(), sd_cache_guard_tamper(), and sd_cache_note_upstream().
sd_http_last_was_failover()
int sd_http_last_was_failover (brix_sd_instance_t * inst)
Definition at line 111 of file sd_http_introspect.c.
References sd_http_instance_is().
Referenced by sd_cache_note_upstream().
sd_http_n_endpoints()
int sd_http_n_endpoints (brix_sd_instance_t * inst)
Definition at line 84 of file sd_http_introspect.c.
References sd_http_instance_is().
sd_http_penalize_last_origin()
void sd_http_penalize_last_origin (brix_sd_instance_t * inst)
Definition at line 48 of file sd_http_introspect.c.
References sd_http_inst_state::cur_ep, sd_http_inst_state::eps, sd_http_endpoint::fail_score, sd_http_inst_state::n_eps, sd_http_instance_is(), and SD_HTTP_VERIFY_PENALTY.
Referenced by cache_fill_verify_reject().
sd_http_set_ranks()
void sd_http_set_ranks (brix_sd_instance_t * inst, const int * ranks, int n)
Definition at line 22 of file sd_http_introspect.c.
References sd_http_inst_state::eps, sd_http_inst_state::n_eps, sd_http_endpoint::rank, and sd_http_instance_is().
Referenced by brix_vbr_build_http(), and cvmfs_probe_done().