nginx-xrootd: src/fs/backend/cache/sd_cache.h File Reference
sd_cache.h File Reference
#include <ngx_core.h>
#include "fs/backend/sd.h"
#include "fs/tier/tier.h"
Data Structures
struct brix_sd_cache_peer_t
Macros
#define BRIX_SD_CACHE_MAX_PEERS 16
Functions
brix_sd_instance_t * brix_sd_cache_create (brix_sd_instance_t *source, brix_sd_instance_t *store, const brix_cache_policy_t *policy, const char *store_local_root, ngx_log_t *log)
void brix_sd_cache_destroy (brix_sd_instance_t *inst)
int brix_sd_cache_instance_is (const brix_sd_instance_t *inst)
void brix_sd_cache_evict (brix_sd_instance_t *inst, const char *key)
int brix_sd_cache_fill_needs_offload (brix_sd_instance_t *inst, const char *key)
ngx_int_t brix_sd_cache_fill_key (brix_sd_instance_t *inst, const char *key)
brix_sd_instance_t * brix_sd_cache_store_instance (const brix_sd_instance_t *inst)
brix_sd_instance_t * brix_sd_cache_source_instance (const brix_sd_instance_t *inst)
void * brix_sd_cache_cstore (const brix_sd_instance_t *inst)
void brix_sd_cache_set_cold (brix_sd_instance_t *inst, brix_sd_instance_t *cold)
ngx_int_t brix_sd_cache_demote (brix_sd_instance_t *inst, const char *key)
void brix_sd_cache_set_peers (brix_sd_instance_t *inst, const brix_sd_cache_peer_t *peers, int n, int self)
Macro Definition Documentation
BRIX_SD_CACHE_MAX_PEERS
#define BRIX_SD_CACHE_MAX_PEERS 16
Definition at line 117 of file sd_cache.h.
Function Documentation
brix_sd_cache_create()
brix_sd_instance_t * brix_sd_cache_create (brix_sd_instance_t * source, brix_sd_instance_t * store, const brix_cache_policy_t * policy, const char * store_local_root, ngx_log_t * log)
Definition at line 302 of file sd_cache.c.
References brix_cache_policy_t::batch_cinfo, brix_cstore_init(), brix_sd_cache_driver, sd_cache_inst_state::cstore, brix_cache_policy_t::l1_entries, log, sd_cache_inst_state::log, brix_cache_policy_t::meta_mode, sd_cache_inst_state::policy, and sd_cache_inst_state::source.
Referenced by brix_vbr_wrap_cache_tier(), and tier_compose_cache().
brix_sd_cache_cstore()
void * brix_sd_cache_cstore (const brix_sd_instance_t * inst)
Definition at line 477 of file sd_cache.c.
References brix_sd_cache_instance_is(), and SD_CACHE_ST.
Referenced by brix_cache_storage_cstore().
brix_sd_cache_demote()
ngx_int_t brix_sd_cache_demote (brix_sd_instance_t * inst, const char * key)
Definition at line 633 of file sd_cache_fill.c.
References brix_sd_cache_instance_is(), BRIX_SD_O_READ, brix_sd_obj_release(), sd_cache_inst_state::cold, sd_cache_inst_state::cstore, key, SD_CACHE_CHUNK, SD_CACHE_ST, and brix_cstore_t::store.
Referenced by brix_cache_evict_one().
brix_sd_cache_destroy()
void brix_sd_cache_destroy (brix_sd_instance_t * inst)
Definition at line 344 of file sd_cache.c.
References brix_cstore_cleanup(), and sd_cache_inst_state::cstore.
brix_sd_cache_evict()
void brix_sd_cache_evict (brix_sd_instance_t * inst, const char * key)
Definition at line 382 of file sd_cache.c.
References brix_cstore_evict(), brix_sd_cache_instance_is(), sd_cache_inst_state::cstore, key, and SD_CACHE_ST.
Referenced by brix_vfs_delete_via_driver(), and brix_vfs_rename().
brix_sd_cache_fill_key()
ngx_int_t brix_sd_cache_fill_key (brix_sd_instance_t * inst, const char * key)
Definition at line 445 of file sd_cache.c.
References brix_sd_cache_instance_is(), key, sd_cache_fill(), and SD_CACHE_ST.
Referenced by brix_cache_fill_composed_thread().
brix_sd_cache_fill_needs_offload()
int brix_sd_cache_fill_needs_offload (brix_sd_instance_t * inst, const char * key)
Definition at line 401 of file sd_cache.c.
References brix_cache_cinfo_expired(), BRIX_CINFO_F_COMPLETE, BRIX_CMETA_LOCAL, brix_cstore_cinfo_load(), brix_sd_cache_instance_is(), BRIX_SD_CAP_FD, brix_sd_caps(), sd_cache_inst_state::cstore, brix_cache_policy_t::cvmfs_manifest_ttl, brix_cache_cinfo_t::flags, key, brix_cstore_t::meta_mode, sd_cache_inst_state::policy, SD_CACHE_ST, brix_cache_policy_t::slice_size, and sd_cache_inst_state::source.
Referenced by brix_open_read_probe(), brix_open_try_cache_offload(), and cvmfs_tier_serve_or_fill().
brix_sd_cache_instance_is()
int brix_sd_cache_instance_is (const brix_sd_instance_t * inst)
Definition at line 370 of file sd_cache.c.
References brix_sd_cache_driver.
Referenced by brix_cache_storage(), brix_cache_storage_cstore(), brix_cache_storage_decorator(), brix_sd_cache_cstore(), brix_sd_cache_demote(), brix_sd_cache_evict(), brix_sd_cache_fill_key(), brix_sd_cache_fill_needs_offload(), brix_sd_cache_set_cold(), brix_sd_cache_set_peers(), brix_sd_cache_source_instance(), brix_sd_cache_store_instance(), and stage_reconcile_one().
brix_sd_cache_set_cold()
void brix_sd_cache_set_cold (brix_sd_instance_t * inst, brix_sd_instance_t * cold)
Definition at line 488 of file sd_cache.c.
References brix_sd_cache_instance_is(), and SD_CACHE_ST.
Referenced by brix_vbr_wrap_cache_tier().
brix_sd_cache_set_peers()
void brix_sd_cache_set_peers (brix_sd_instance_t * inst, const brix_sd_cache_peer_t * peers, int n, int self)
Definition at line 501 of file sd_cache.c.
References brix_sd_cache_instance_is(), BRIX_SD_CACHE_MAX_PEERS, sd_cache_inst_state::n_peers, sd_cache_inst_state::peer_self, sd_cache_inst_state::peers, and SD_CACHE_ST.
Referenced by brix_vbr_wrap_cache_tier().
brix_sd_cache_source_instance()
brix_sd_instance_t * brix_sd_cache_source_instance (const brix_sd_instance_t * inst)
Definition at line 468 of file sd_cache.c.
References brix_sd_cache_instance_is(), and SD_CACHE_SRC.
Referenced by brix_vfs_decorator_source(), brix_vfs_ns_leaf(), cvmfs_unwrap_http(), cvmfs_var_origin(), health_build_json(), sd_cache_note_upstream(), and stage_reconcile_one().
brix_sd_cache_store_instance()
brix_sd_instance_t * brix_sd_cache_store_instance (const brix_sd_instance_t * inst)
Definition at line 458 of file sd_cache.c.
References brix_sd_cache_instance_is(), and SD_CACHE_ST.
Referenced by brix_cache_storage().