nginx-xrootd: src/fs/backend/remote/sd_remote_meta.c File Reference
sd_remote_meta.c File Reference
#include "sd_remote_internal.h"
#include "fs/backend/s3/sd_s3.h"
#include <errno.h>
#include <string.h>
Functions
static sd_s3_file * sd_remote_meta_open (brix_sd_instance_t *inst, const char *path)
ssize_t sd_remote_getxattr (brix_sd_instance_t *inst, const char *path, const char *name, void *buf, size_t cap)
ssize_t sd_remote_listxattr (brix_sd_instance_t *inst, const char *path, void *buf, size_t cap)
static ngx_int_t sd_remote_stat_impl (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out, const char *ak, const char *sk, const char *region)
ngx_int_t sd_remote_stat (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out)
ngx_int_t sd_remote_stat_cred (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out, const brix_sd_cred_t *cred)
Function Documentation
sd_remote_getxattr()
ssize_t sd_remote_getxattr (brix_sd_instance_t * inst, const char * path, const char * name, void * buf, size_t cap)
Definition at line 35 of file sd_remote_meta.c.
References name, sd_remote_meta_open(), sd_s3_close(), and sd_s3_get_meta().
sd_remote_listxattr()
ssize_t sd_remote_listxattr (brix_sd_instance_t * inst, const char * path, void * buf, size_t cap)
Definition at line 76 of file sd_remote_meta.c.
References sd_remote_meta_open(), sd_s3_close(), and sd_s3_list_meta().
sd_remote_meta_open()
static sd_s3_file * sd_remote_meta_open (brix_sd_instance_t * inst, const char * path) static
Definition at line 22 of file sd_remote_meta.c.
References sd_remote_s3_key(), sd_remote_s3_params(), and sd_s3_open_read().
Referenced by sd_remote_getxattr(), and sd_remote_listxattr().
sd_remote_stat()
ngx_int_t sd_remote_stat (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out)
Definition at line 136 of file sd_remote_meta.c.
References sd_remote_stat_impl().
sd_remote_stat_cred()
ngx_int_t sd_remote_stat_cred (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out, const brix_sd_cred_t * cred)
Definition at line 147 of file sd_remote_meta.c.
References brix_sd_cred_t::s3_ak, brix_sd_cred_t::s3_region, brix_sd_cred_t::s3_sk, sd_remote_cred_gate(), and sd_remote_stat_impl().
sd_remote_stat_impl()
static ngx_int_t sd_remote_stat_impl (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out, const char * ak, const char * sk, const char * region) static
Definition at line 100 of file sd_remote_meta.c.
References sd_s3_open_params::ak, brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, sd_s3_open_params::region, region, sd_remote_s3_key(), sd_remote_s3_params(), sd_s3_close(), sd_s3_open_read(), sd_s3_size(), brix_sd_stat_t::size, and sd_s3_open_params::sk.
Referenced by sd_remote_stat(), and sd_remote_stat_cred().