nginx-xrootd: src/fs/backend/cache/sd_cache_fill_verify.c File Reference
sd_cache_fill_verify.c File Reference
#include "sd_cache.h"
#include "sd_cache_internal.h"
#include "sd_cache_policy.h"
#include "sd_cache_fill_internal.h"
#include "protocols/cvmfs/classify.h"
#include "observability/metrics/metrics.h"
#include "observability/metrics/metrics_macros.h"
#include "fs/cache/cstore.h"
#include "fs/backend/http/sd_http.h"
#include "fs/backend/xroot/sd_xroot.h"
#include "fs/path/path.h"
#include "net/guard/guard.h"
#include "core/compat/checksum.h"
#include "core/fnv.h"
#include <errno.h>
#include <fcntl.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Functions
void sd_cache_guard_tamper (sd_cache_inst_state *st, brix_sd_instance_t *actor, const char *key)
static ngx_int_t cache_fill_verify_reject (sd_cache_inst_state *st, const char *key, sd_cache_fill_state_t *fs, const char *pp)
static int sd_cache_hex_ieq (const char *a, const char *b)
static ngx_int_t cache_fill_verify_origin (sd_cache_inst_state *st, const char *key, sd_cache_fill_state_t *fs, const char *pp)
ngx_int_t cache_fill_verify (sd_cache_inst_state *st, const char *key, sd_cache_fill_state_t *fs)
Function Documentation
cache_fill_verify()
ngx_int_t cache_fill_verify (sd_cache_inst_state * st, const char * key, sd_cache_fill_state_t * fs)
Definition at line 284 of file sd_cache_fill_verify.c.
References BRIX_CACHE_VERIFY_BESTEFFORT, brix_cache_verify_cvmfs_cas(), BRIX_CACHE_VERIFY_CVMFS_CAS, BRIX_CACHE_VERIFY_ERROR, BRIX_CACHE_VERIFY_MISMATCH, BRIX_CACHE_VERIFY_OFF, BRIX_CACHE_VERIFY_REQUIRE, BRIX_CACHE_VERIFY_VERIFIED, brix_cstore_fill_abort(), cache_fill_verify_origin(), cache_fill_verify_reject(), sd_cache_fill_state_t::cks_alg, sd_cache_fill_state_t::cks_hex, brix_cache_policy_t::cvmfs_master_pub, key, sd_cache_inst_state::log, sd_cache_inst_state::policy, sd_cache_verify_manifest(), sd_cache_fill_state_t::staged, sd_cache_fill_state_t::verified, and brix_cache_policy_t::verify.
Referenced by sd_cache_fill_attempt().
cache_fill_verify_origin()
static ngx_int_t cache_fill_verify_origin (sd_cache_inst_state * st, const char * key, sd_cache_fill_state_t * fs, const char * pp) static
Definition at line 185 of file sd_cache_fill_verify.c.
References BRIX_CACHE_VERIFY_REQUIRE, brix_checksum_hex_name_fd(), brix_cstore_fill_abort(), cache_fill_verify_reject(), sd_cache_fill_state_t::cks_alg, sd_cache_fill_state_t::cks_hex, close(), hex(), key, sd_cache_inst_state::log, open(), sd_cache_fill_state_t::origin_alg, sd_cache_fill_state_t::origin_hex, sd_cache_inst_state::policy, sd_cache_hex_ieq(), sd_cache_fill_state_t::staged, sd_cache_fill_state_t::verified, and brix_cache_policy_t::verify.
Referenced by cache_fill_verify().
cache_fill_verify_reject()
static ngx_int_t cache_fill_verify_reject (sd_cache_inst_state * st, const char * key, sd_cache_fill_state_t * fs, const char * pp) static
Definition at line 107 of file sd_cache_fill_verify.c.
References BRIX_ATOMIC_INC, brix_cache_quarantine_part(), brix_cstore_fill_abort(), BRIX_CVMFS_METRIC_INC, sd_cache_fill_state_t::from_cold, sd_cache_fill_state_t::from_peer, key, sd_cache_inst_state::log, sd_cache_fill_state_t::off, sd_cache_inst_state::policy, brix_cache_policy_t::quarantine_dir, sd_cache_guard_tamper(), sd_cache_ms_since(), sd_cache_note_origin_bytes(), sd_cache_note_upstream(), sd_cache_repo_metrics(), sd_http_penalize_last_origin(), sd_cache_inst_state::source, sd_cache_fill_state_t::src, sd_cache_fill_state_t::staged, sd_cache_fill_state_t::t0, and ngx_brix_cvmfs_repo_metrics_t::verify_failures_total.
Referenced by cache_fill_verify(), and cache_fill_verify_origin().
sd_cache_guard_tamper()
void sd_cache_guard_tamper (sd_cache_inst_state * st, brix_sd_instance_t * actor, const char * key)
Definition at line 57 of file sd_cache_fill_verify.c.
References brix_sanitize_log_string(), guard_request_t::cred_present, guard_audit_format(), GUARD_OP_READ, GUARD_R_TAMPER, guard_request_t::ip, key, sd_cache_inst_state::log, guard_request_t::op, guard_request_t::outcome, OUTCOME_PENDING, guard_request_t::path, guard_request_t::path_len, guard_request_t::proto, sd_http_last_origin(), sd_cache_inst_state::source, and guard_request_t::status_code.
Referenced by cache_fill_verify_reject().
sd_cache_hex_ieq()
static int sd_cache_hex_ieq (const char * a, const char * b) static
Definition at line 160 of file sd_cache_fill_verify.c.
Referenced by cache_fill_verify_origin().