nginx-xrootd: src/fs/backend/xroot/sd_xroot_ns_dir.c File Reference
sd_xroot_ns_dir.c File Reference
#include "sd_xroot_internal.h"
#include "auth/crypto/pki_build.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <openssl/x509.h>
#include <openssl/x509_vfy.h>
Data Structures
struct sd_xroot_dir_state
Functions
static brix_sd_dir_t * sd_xroot_opendir_common (brix_sd_instance_t *inst, const char *path, const brix_sd_cred_t *cred, int *err_out)
brix_sd_dir_t * sd_xroot_opendir (brix_sd_instance_t *inst, const char *path, int *err_out)
brix_sd_dir_t * sd_xroot_opendir_cred (brix_sd_instance_t *inst, const char *path, int *err_out, const brix_sd_cred_t *cred)
ngx_int_t sd_xroot_readdir (brix_sd_dir_t *d, brix_sd_dirent_t *out)
ngx_int_t sd_xroot_closedir (brix_sd_dir_t *d)
Function Documentation
sd_xroot_closedir()
ngx_int_t sd_xroot_closedir (brix_sd_dir_t * d)
Definition at line 153 of file sd_xroot_ns_dir.c.
References brix_cache_dirlist_free(), and sd_xroot_dir_state::dl.
sd_xroot_opendir()
brix_sd_dir_t * sd_xroot_opendir (brix_sd_instance_t * inst, const char * path, int * err_out)
Definition at line 107 of file sd_xroot_ns_dir.c.
References sd_xroot_opendir_common().
sd_xroot_opendir_common()
static brix_sd_dir_t * sd_xroot_opendir_common (brix_sd_instance_t * inst, const char * path, const brix_sd_cred_t * cred, int * err_out) static
Definition at line 54 of file sd_xroot_ns_dir.c.
References brix_cache_dirlist_free(), brix_cache_dirlist_init(), brix_cache_origin_close(), brix_cache_origin_dirlist(), sd_xroot_inst_state::conf, sd_xroot_dir_state::dl, sd_xroot_errno(), and sd_xroot_session().
Referenced by sd_xroot_opendir(), and sd_xroot_opendir_cred().
sd_xroot_opendir_cred()
brix_sd_dir_t * sd_xroot_opendir_cred (brix_sd_instance_t * inst, const char * path, int * err_out, const brix_sd_cred_t * cred)
Definition at line 115 of file sd_xroot_ns_dir.c.
References sd_xroot_opendir_common().
sd_xroot_readdir()
ngx_int_t sd_xroot_readdir (brix_sd_dir_t * d, brix_sd_dirent_t * out)
Definition at line 127 of file sd_xroot_ns_dir.c.
References brix_cache_dirlist_t::count, sd_xroot_dir_state::dl, brix_sd_dirent_t::name, brix_cache_dirlist_t::names, and sd_xroot_dir_state::next.