nginx-xrootd: src/fs/backend/block/sd_block.c File Reference
sd_block.c File Reference
#include "fs/backend/sd.h"
#include <errno.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <sys/stat.h>
#include <unistd.h>
Functions
static ssize_t sd_block_pread (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
static ssize_t sd_block_pwrite (brix_sd_obj_t *obj, const void *buf, size_t len, off_t off)
static ssize_t sd_block_preadv (brix_sd_obj_t *obj, const struct iovec *iov, int iovcnt, off_t off)
static ssize_t sd_block_preadv2 (brix_sd_obj_t *obj, const struct iovec *iov, int iovcnt, off_t off, int flags)
static ngx_int_t sd_block_fsync (brix_sd_obj_t *obj)
static ngx_int_t sd_block_fstat (brix_sd_obj_t *obj, brix_sd_stat_t *out)
int brix_sd_block_open_unconfined (const char *path, int sd_flags, mode_t mode)
Variables
const brix_sd_driver_t brix_sd_block_driver
Function Documentation
brix_sd_block_open_unconfined()
int brix_sd_block_open_unconfined (const char * path, int sd_flags, mode_t mode)
Definition at line 100 of file sd_block.c.
References BRIX_SD_O_CREATE, BRIX_SD_O_TRUNC, and brix_sd_posix_open_unconfined().
Referenced by block_be_open(), and block_be_stat().
sd_block_fstat()
static ngx_int_t sd_block_fstat (brix_sd_obj_t * obj, brix_sd_stat_t * out) static
Definition at line 70 of file sd_block.c.
References brix_sd_stat_t::ctime, fstat(), brix_sd_stat_t::ino, brix_sd_stat_t::is_dir, brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, brix_sd_stat_t::mtime, brix_sd_stat_t::size, and stat().
sd_block_fsync()
static ngx_int_t sd_block_fsync (brix_sd_obj_t * obj) static
Definition at line 62 of file sd_block.c.
References brix_sd_posix_driver.
sd_block_pread()
static ssize_t sd_block_pread (brix_sd_obj_t * obj, void * buf, size_t len, off_t off) static
Definition at line 36 of file sd_block.c.
References brix_sd_posix_driver.
sd_block_preadv()
static ssize_t sd_block_preadv (brix_sd_obj_t * obj, const struct iovec * iov, int iovcnt, off_t off) static
Definition at line 48 of file sd_block.c.
References brix_sd_posix_driver.
sd_block_preadv2()
static ssize_t sd_block_preadv2 (brix_sd_obj_t * obj, const struct iovec * iov, int iovcnt, off_t off, int flags) static
Definition at line 55 of file sd_block.c.
References brix_sd_posix_driver.
sd_block_pwrite()
static ssize_t sd_block_pwrite (brix_sd_obj_t * obj, const void * buf, size_t len, off_t off) static
Definition at line 42 of file sd_block.c.
References brix_sd_posix_driver.
Variable Documentation
brix_sd_block_driver
const brix_sd_driver_t brix_sd_block_driver
Initial value:
= {
    .name = "block",
    .caps = BRIX_SD_CAP_FD | BRIX_SD_CAP_RANDOM_WRITE
          | BRIX_SD_CAP_RANGE_READ,
    .pread    = sd_block_pread,
    .pwrite   = sd_block_pwrite,
    .preadv   = sd_block_preadv,
    .preadv2  = sd_block_preadv2,
    .fsync    = sd_block_fsync,
    .fstat    = sd_block_fstat,
}
Definition at line 109 of file sd_block.c.
Referenced by block_be_stat(), and block_fstat().