nginx-xrootd: src/fs/backend/http/sd_http_introspect.c File Reference
sd_http_introspect.c File Reference
#include "sd_http_internal.h"
#include <string.h>
#include <stdio.h>
Macros
#define SD_HTTP_VERIFY_PENALTY 512
Functions
void sd_http_set_ranks (brix_sd_instance_t *inst, const int *ranks, int n)
void sd_http_penalize_last_origin (brix_sd_instance_t *inst)
int sd_http_endpoint_list (brix_sd_instance_t *inst, char hosts[][256], int *ports, int max)
int sd_http_n_endpoints (brix_sd_instance_t *inst)
int sd_http_last_origin (brix_sd_instance_t *inst, char *buf, size_t cap)
int sd_http_last_was_failover (brix_sd_instance_t *inst)
int sd_http_health_snapshot (brix_sd_instance_t *inst, char hosts[][256], int *ports, int *scores, int max)
Macro Definition Documentation
SD_HTTP_VERIFY_PENALTY
#define SD_HTTP_VERIFY_PENALTY 512
Definition at line 46 of file sd_http_introspect.c.
Function Documentation
sd_http_endpoint_list()
int sd_http_endpoint_list (brix_sd_instance_t * inst, char hosts[][256], int * ports, int max)
Definition at line 64 of file sd_http_introspect.c.
References sd_http_inst_state::eps, sd_http_endpoint::host, sd_http_inst_state::n_eps, sd_http_endpoint::port, and sd_http_instance_is().
sd_http_health_snapshot()
int sd_http_health_snapshot (brix_sd_instance_t * inst, char hosts[][256], int * ports, int * scores, int max)
Definition at line 120 of file sd_http_introspect.c.
References sd_http_inst_state::eps, sd_http_endpoint::fail_score, sd_http_endpoint::host, sd_http_inst_state::n_eps, sd_http_endpoint::port, and sd_http_instance_is().
Referenced by health_build_json().
sd_http_last_origin()
int sd_http_last_origin (brix_sd_instance_t * inst, char * buf, size_t cap)
Definition at line 93 of file sd_http_introspect.c.
References sd_http_inst_state::last_origin, and sd_http_instance_is().
Referenced by cvmfs_var_origin(), sd_cache_guard_tamper(), and sd_cache_note_upstream().
sd_http_last_was_failover()
int sd_http_last_was_failover (brix_sd_instance_t * inst)
Definition at line 111 of file sd_http_introspect.c.
References sd_http_instance_is().
Referenced by sd_cache_note_upstream().
sd_http_n_endpoints()
int sd_http_n_endpoints (brix_sd_instance_t * inst)
Definition at line 84 of file sd_http_introspect.c.
References sd_http_instance_is().
sd_http_penalize_last_origin()
void sd_http_penalize_last_origin (brix_sd_instance_t * inst)
Definition at line 48 of file sd_http_introspect.c.
References sd_http_inst_state::cur_ep, sd_http_inst_state::eps, sd_http_endpoint::fail_score, sd_http_inst_state::n_eps, sd_http_instance_is(), and SD_HTTP_VERIFY_PENALTY.
Referenced by cache_fill_verify_reject().
sd_http_set_ranks()
void sd_http_set_ranks (brix_sd_instance_t * inst, const int * ranks, int n)
Definition at line 22 of file sd_http_introspect.c.
References sd_http_inst_state::eps, sd_http_inst_state::n_eps, sd_http_endpoint::rank, and sd_http_instance_is().
Referenced by brix_vbr_build_http(), and cvmfs_probe_done().