nginx-xrootd: src/fs/backend/sd_fs_id.c File Reference
sd_fs_id.c File Reference
#include <string.h>
#include "core/types/fs_list.h"
Macros
#define BRIX_FS_ROW_NAME(ID, sym, name, kind) name,
Functions
const char * brix_fs_id_name (int id)
int brix_fs_id_from_name (const char *name)
Variables
static const char *const brix_fs_id_names []
Macro Definition Documentation
BRIX_FS_ROW_NAME
#define BRIX_FS_ROW_NAME (ID, sym, name, kind) name,
Function Documentation
brix_fs_id_from_name()
int brix_fs_id_from_name (const char * name)
Definition at line 38 of file sd_fs_id.c.
References BRIX_FS_ID_COUNT, brix_fs_id_names, and name.
Referenced by brix_metric_backend_bytes().
brix_fs_id_name()
const char * brix_fs_id_name (int id)
Definition at line 28 of file sd_fs_id.c.
References BRIX_FS_ID_COUNT, and brix_fs_id_names.
Referenced by brix_storage_io_bytes_emit(), and dashboard_fill_storage().
Variable Documentation
brix_fs_id_names
const char* const brix_fs_id_names[] static
Initial value:
= {
#define BRIX_FS_ROW_NAME(ID, sym, name, kind)
      "posix" ,      "block" ,      "http" ,      "xroot" ,      "cache" ,      "stage" ,      "remote" ,      "frm" ,
}
Definition at line 20 of file sd_fs_id.c.
Referenced by brix_fs_id_from_name(), and brix_fs_id_name().