nginx-xrootd: src/fs/backend/sd_cred_forward.h File Reference
sd_cred_forward.h File Reference
#include <errno.h>
Functions
static brix_sd_obj_t * brix_sd_open_maybe_cred (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
static brix_sd_staged_t * brix_sd_staged_open_maybe_cred (brix_sd_instance_t *inst, const char *final_path, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
static ngx_int_t brix_sd_stat_maybe_cred (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out, const brix_sd_cred_t *cred)
static ngx_int_t brix_sd_unlink_maybe_cred (brix_sd_instance_t *inst, const char *path, int is_dir, const brix_sd_cred_t *cred)
static ngx_int_t brix_sd_mkdir_maybe_cred (brix_sd_instance_t *inst, const char *path, mode_t mode, const brix_sd_cred_t *cred)
static ngx_int_t brix_sd_rename_maybe_cred (brix_sd_instance_t *inst, const char *src, const char *dst, int noreplace, const brix_sd_cred_t *cred)
static ngx_int_t brix_sd_setattr_maybe_cred (brix_sd_instance_t *inst, const char *path, const brix_sd_setattr_t *attr, const brix_sd_cred_t *cred)
static ssize_t brix_sd_getxattr_maybe_cred (brix_sd_instance_t *inst, const char *path, const char *name, void *buf, size_t cap, const brix_sd_cred_t *cred)
static ssize_t brix_sd_listxattr_maybe_cred (brix_sd_instance_t *inst, const char *path, void *buf, size_t cap, const brix_sd_cred_t *cred)
static ngx_int_t brix_sd_setxattr_maybe_cred (brix_sd_instance_t *inst, const char *path, const char *name, const void *val, size_t len, int flags, const brix_sd_cred_t *cred)
static ngx_int_t brix_sd_removexattr_maybe_cred (brix_sd_instance_t *inst, const char *path, const char *name, const brix_sd_cred_t *cred)
static ngx_int_t brix_sd_server_copy_maybe_cred (brix_sd_instance_t *inst, const char *src, const char *dst, off_t *bytes_out, const brix_sd_cred_t *cred)
static brix_sd_dir_t * brix_sd_opendir_maybe_cred (brix_sd_instance_t *inst, const char *path, int *err_out, const brix_sd_cred_t *cred)
Function Documentation
brix_sd_getxattr_maybe_cred()
static ssize_t brix_sd_getxattr_maybe_cred (brix_sd_instance_t * inst, const char * path, const char * name, void * buf, size_t cap, const brix_sd_cred_t * cred) inline static
Definition at line 206 of file sd_cred_forward.h.
References brix_sd_cred_t::fallback_deny, and name.
Referenced by brix_vfs_getxattr().
brix_sd_listxattr_maybe_cred()
static ssize_t brix_sd_listxattr_maybe_cred (brix_sd_instance_t * inst, const char * path, void * buf, size_t cap, const brix_sd_cred_t * cred) inline static
Definition at line 227 of file sd_cred_forward.h.
References brix_sd_cred_t::fallback_deny.
Referenced by brix_vfs_listxattr().
brix_sd_mkdir_maybe_cred()
static ngx_int_t brix_sd_mkdir_maybe_cred (brix_sd_instance_t * inst, const char * path, mode_t mode, const brix_sd_cred_t * cred) inline static
Definition at line 145 of file sd_cred_forward.h.
References brix_sd_cred_t::fallback_deny.
Referenced by vfs_backend_mkdir_dispatch(), and vfs_backend_mkpath_leaf().
brix_sd_open_maybe_cred()
static brix_sd_obj_t * brix_sd_open_maybe_cred (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, const brix_sd_cred_t * cred, int * err_out) inline static
Definition at line 35 of file sd_cred_forward.h.
References brix_sd_cred_t::fallback_deny.
Referenced by brix_open_resolved_via_driver(), brix_vfs_open_via_driver(), cache_fill_acquire(), meta_fetch_source(), partial_source_ensure(), sd_cache_open_common(), and sd_stage_open_cred().
brix_sd_opendir_maybe_cred()
static brix_sd_dir_t * brix_sd_opendir_maybe_cred (brix_sd_instance_t * inst, const char * path, int * err_out, const brix_sd_cred_t * cred) inline static
Definition at line 313 of file sd_cred_forward.h.
References brix_sd_cred_t::fallback_deny.
Referenced by brix_vfs_driver_rmtree(), and vfs_dir_open_driver().
brix_sd_removexattr_maybe_cred()
static ngx_int_t brix_sd_removexattr_maybe_cred (brix_sd_instance_t * inst, const char * path, const char * name, const brix_sd_cred_t * cred) inline static
Definition at line 271 of file sd_cred_forward.h.
References brix_sd_cred_t::fallback_deny, and name.
Referenced by brix_vfs_removexattr().
brix_sd_rename_maybe_cred()
static ngx_int_t brix_sd_rename_maybe_cred (brix_sd_instance_t * inst, const char * src, const char * dst, int noreplace, const brix_sd_cred_t * cred) inline static
Definition at line 163 of file sd_cred_forward.h.
References brix_sd_cred_t::fallback_deny.
Referenced by brix_vfs_rename().
brix_sd_server_copy_maybe_cred()
static ngx_int_t brix_sd_server_copy_maybe_cred (brix_sd_instance_t * inst, const char * src, const char * dst, off_t * bytes_out, const brix_sd_cred_t * cred) inline static
Definition at line 292 of file sd_cred_forward.h.
References brix_sd_cred_t::fallback_deny.
Referenced by brix_vfs_copy_driver().
brix_sd_setattr_maybe_cred()
static ngx_int_t brix_sd_setattr_maybe_cred (brix_sd_instance_t * inst, const char * path, const brix_sd_setattr_t * attr, const brix_sd_cred_t * cred) inline static
Definition at line 183 of file sd_cred_forward.h.
References brix_sd_cred_t::fallback_deny.
Referenced by brix_vfs_chmod(), and brix_vfs_setattr().
brix_sd_setxattr_maybe_cred()
static ngx_int_t brix_sd_setxattr_maybe_cred (brix_sd_instance_t * inst, const char * path, const char * name, const void * val, size_t len, int flags, const brix_sd_cred_t * cred) inline static
Definition at line 248 of file sd_cred_forward.h.
References brix_sd_cred_t::fallback_deny, and name.
Referenced by brix_vfs_setxattr().
brix_sd_staged_open_maybe_cred()
static brix_sd_staged_t * brix_sd_staged_open_maybe_cred (brix_sd_instance_t * inst, const char * final_path, mode_t mode, const brix_sd_cred_t * cred, int * err_out) inline static
Definition at line 62 of file sd_cred_forward.h.
References brix_sd_cred_t::fallback_deny.
Referenced by sd_cache_staged_open_cred(), stage_engine_move(), and staged_open_driver().
brix_sd_stat_maybe_cred()
static ngx_int_t brix_sd_stat_maybe_cred (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out, const brix_sd_cred_t * cred) inline static
Definition at line 105 of file sd_cred_forward.h.
References brix_sd_cred_t::fallback_deny.
Referenced by brix_open_read_probe(), brix_vfs_copy_driver(), brix_vfs_driver_rmtree(), brix_vfs_probe(), and brix_vfs_stat_impl().
brix_sd_unlink_maybe_cred()
static ngx_int_t brix_sd_unlink_maybe_cred (brix_sd_instance_t * inst, const char * path, int is_dir, const brix_sd_cred_t * cred) inline static
Definition at line 125 of file sd_cred_forward.h.
References brix_sd_cred_t::fallback_deny.
Referenced by brix_vfs_delete_via_driver(), and brix_vfs_driver_rmtree().