nginx-xrootd: src/fs/backend/posix/sd_posix_ns.c File Reference
sd_posix_ns.c File Reference
#include "fs/backend/sd.h"
#include "fs/vfs/vfs_internal.h"
#include "core/compat/crc32c.h"
#include "core/compat/namespace_ops.h"
#include "core/compat/staged_file.h"
#include "fs/path/beneath.h"
#include "fs/path/path.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <string.h>
#include <sys/syscall.h>
#include <unistd.h>
#include "sd_posix_internal.h"
Data Structures
struct sd_posix_dir_t
struct sd_posix_staged_t
Functions
ngx_int_t sd_posix_stat (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out)
static ngx_int_t sd_posix_ns_result (brix_ns_result_t res)
ngx_int_t sd_posix_unlink (brix_sd_instance_t *inst, const char *path, int is_dir)
ngx_int_t sd_posix_setattr (brix_sd_instance_t *inst, const char *path, const brix_sd_setattr_t *attr)
ngx_int_t sd_posix_mkdir (brix_sd_instance_t *inst, const char *path, mode_t mode)
ngx_int_t sd_posix_rename (brix_sd_instance_t *inst, const char *src, const char *dst, int noreplace)
ngx_int_t sd_posix_server_copy (brix_sd_instance_t *inst, const char *src, const char *dst, off_t *bytes_out)
brix_sd_dir_t * sd_posix_opendir (brix_sd_instance_t *inst, const char *path, int *err_out)
ngx_int_t sd_posix_readdir (brix_sd_dir_t *d, brix_sd_dirent_t *out)
ngx_int_t sd_posix_closedir (brix_sd_dir_t *d)
ssize_t sd_posix_getxattr (brix_sd_instance_t *inst, const char *path, const char *name, void *buf, size_t cap)
ssize_t sd_posix_listxattr (brix_sd_instance_t *inst, const char *path, void *buf, size_t cap)
ngx_int_t sd_posix_setxattr (brix_sd_instance_t *inst, const char *path, const char *name, const void *val, size_t len, int flags)
ngx_int_t sd_posix_removexattr (brix_sd_instance_t *inst, const char *path, const char *name)
brix_sd_staged_t * sd_posix_staged_open (brix_sd_instance_t *inst, const char *final_path, mode_t mode, int *err_out)
ssize_t sd_posix_staged_write (brix_sd_staged_t *st, const void *buf, size_t len, off_t off)
ngx_int_t sd_posix_staged_commit (brix_sd_staged_t *st, int noreplace)
void sd_posix_staged_abort (brix_sd_staged_t *st)
const char * sd_posix_staged_path (const brix_sd_staged_t *st)
Function Documentation
sd_posix_closedir()
ngx_int_t sd_posix_closedir (brix_sd_dir_t * d)
Definition at line 263 of file sd_posix_ns.c.
References sd_posix_dir_t::dp.
sd_posix_getxattr()
ssize_t sd_posix_getxattr (brix_sd_instance_t * inst, const char * path, const char * name, void * buf, size_t cap)
Definition at line 282 of file sd_posix_ns.c.
References brix_getxattr_confined_canon(), name, PATH_MAX, and sd_posix_state_t::root_canon.
sd_posix_listxattr()
ssize_t sd_posix_listxattr (brix_sd_instance_t * inst, const char * path, void * buf, size_t cap)
Definition at line 299 of file sd_posix_ns.c.
References brix_listxattr_confined_canon(), PATH_MAX, and sd_posix_state_t::root_canon.
sd_posix_mkdir()
ngx_int_t sd_posix_mkdir (brix_sd_instance_t * inst, const char * path, mode_t mode)
Definition at line 144 of file sd_posix_ns.c.
References brix_ns_mkdir(), PATH_MAX, sd_posix_state_t::root_canon, and sd_posix_ns_result().
sd_posix_ns_result()
static ngx_int_t sd_posix_ns_result (brix_ns_result_t res) static
Definition at line 67 of file sd_posix_ns.c.
References BRIX_NS_OK, brix_vfs_ns_status_errno(), brix_ns_result_t::status, and brix_ns_result_t::sys_errno.
Referenced by sd_posix_mkdir(), sd_posix_rename(), sd_posix_server_copy(), and sd_posix_unlink().
sd_posix_opendir()
brix_sd_dir_t * sd_posix_opendir (brix_sd_instance_t * inst, const char * path, int * err_out)
Definition at line 203 of file sd_posix_ns.c.
References brix_open_beneath(), close(), sd_posix_dir_t::dp, ngx_pcalloc(), and sd_posix_state_t::rootfd.
sd_posix_readdir()
ngx_int_t sd_posix_readdir (brix_sd_dir_t * d, brix_sd_dirent_t * out)
Definition at line 239 of file sd_posix_ns.c.
References sd_posix_dir_t::dp, and brix_sd_dirent_t::name.
sd_posix_removexattr()
ngx_int_t sd_posix_removexattr (brix_sd_instance_t * inst, const char * path, const char * name)
Definition at line 334 of file sd_posix_ns.c.
References brix_removexattr_confined_canon(), name, PATH_MAX, and sd_posix_state_t::root_canon.
sd_posix_rename()
ngx_int_t sd_posix_rename (brix_sd_instance_t * inst, const char * src, const char * dst, int noreplace)
Definition at line 163 of file sd_posix_ns.c.
References brix_ns_rename(), sd_posix_state_t::root_canon, and sd_posix_ns_result().
sd_posix_server_copy()
ngx_int_t sd_posix_server_copy (brix_sd_instance_t * inst, const char * src, const char * dst, off_t * bytes_out)
Definition at line 174 of file sd_posix_ns.c.
References brix_lstat_beneath(), brix_ns_local_copy(), brix_ns_copy_opts_t::overwrite, sd_posix_state_t::root_canon, sd_posix_state_t::rootfd, sd_posix_ns_result(), sd_posix_stat(), and stat().
sd_posix_setattr()
ngx_int_t sd_posix_setattr (brix_sd_instance_t * inst, const char * path, const brix_sd_setattr_t * attr)
Definition at line 110 of file sd_posix_ns.c.
References brix_sd_setattr_t::atime, brix_chmod_confined_canon(), brix_setattr_confined_canon(), brix_sd_setattr_t::gid, brix_sd_setattr_t::mode, brix_sd_setattr_t::mtime, PATH_MAX, sd_posix_state_t::root_canon, brix_sd_setattr_t::set_mode, brix_sd_setattr_t::set_owner, brix_sd_setattr_t::set_times, and brix_sd_setattr_t::uid.
sd_posix_setxattr()
ngx_int_t sd_posix_setxattr (brix_sd_instance_t * inst, const char * path, const char * name, const void * val, size_t len, int flags)
Definition at line 316 of file sd_posix_ns.c.
References brix_setxattr_confined_canon(), name, PATH_MAX, and sd_posix_state_t::root_canon.
sd_posix_staged_abort()
void sd_posix_staged_abort (brix_sd_staged_t * st)
Definition at line 451 of file sd_posix_ns.c.
References brix_staged_abort(), sd_posix_state_t::root_canon, and sd_posix_staged_t::staged.
sd_posix_staged_commit()
ngx_int_t sd_posix_staged_commit (brix_sd_staged_t * st, int noreplace)
Definition at line 433 of file sd_posix_ns.c.
References brix_staged_commit(), brix_staged_commit_excl(), sd_posix_staged_t::final_path, sd_posix_state_t::root_canon, and sd_posix_staged_t::staged.
sd_posix_staged_open()
brix_sd_staged_t * sd_posix_staged_open (brix_sd_instance_t * inst, const char * final_path, mode_t mode, int * err_out)
Definition at line 360 of file sd_posix_ns.c.
References brix_staged_open(), sd_posix_staged_t::final_path, PATH_MAX, brix_staged_open_req_t::root_canon, sd_posix_state_t::root_canon, and sd_posix_staged_t::staged.
sd_posix_staged_path()
const char * sd_posix_staged_path (const brix_sd_staged_t * st)
Definition at line 465 of file sd_posix_ns.c.
References sd_posix_staged_t::staged, and brix_staged_file_t::tmp_path.
sd_posix_staged_write()
ssize_t sd_posix_staged_write (brix_sd_staged_t * st, const void * buf, size_t len, off_t off)
Definition at line 421 of file sd_posix_ns.c.
References brix_vfs_pwrite_full(), brix_staged_file_t::fd, and sd_posix_staged_t::staged.
sd_posix_stat()
ngx_int_t sd_posix_stat (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out)
Definition at line 51 of file sd_posix_ns.c.
References brix_lstat_beneath(), sd_posix_state_t::rootfd, sd_posix_fill_stat(), and stat().
Referenced by sd_posix_server_copy().
sd_posix_unlink()
ngx_int_t sd_posix_unlink (brix_sd_instance_t * inst, const char * path, int is_dir)
Definition at line 78 of file sd_posix_ns.c.
References brix_ns_delete(), PATH_MAX, brix_ns_delete_opts_t::require_directory, sd_posix_state_t::root_canon, and sd_posix_ns_result().