nginx-xrootd: src/fs/backend/remote/sd_remote_write.c File Reference
sd_remote_write.c File Reference
#include "sd_remote_internal.h"
#include "fs/backend/s3/sd_s3.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct sd_remote_staged_state
Macros
#define SD_REMOTE_PART_SIZE (16 * 1024 * 1024)
Functions
static brix_sd_staged_t * sd_remote_staged_open_impl (brix_sd_instance_t *inst, const char *final_path, const char *ak, const char *sk, const char *region, int *err_out)
brix_sd_staged_t * sd_remote_staged_open (brix_sd_instance_t *inst, const char *final_path, mode_t mode, int *err_out)
brix_sd_staged_t * sd_remote_staged_open_cred (brix_sd_instance_t *inst, const char *final_path, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
ssize_t sd_remote_staged_write (brix_sd_staged_t *h, const void *buf, size_t len, off_t off)
ngx_int_t sd_remote_staged_commit (brix_sd_staged_t *h, int noreplace)
void sd_remote_staged_abort (brix_sd_staged_t *h)
static ngx_int_t sd_remote_unlink_impl (brix_sd_instance_t *inst, const char *path, const char *ak, const char *sk, const char *region)
ngx_int_t sd_remote_unlink (brix_sd_instance_t *inst, const char *path, int is_dir)
ngx_int_t sd_remote_unlink_cred (brix_sd_instance_t *inst, const char *path, int is_dir, const brix_sd_cred_t *cred)
Macro Definition Documentation
SD_REMOTE_PART_SIZE
#define SD_REMOTE_PART_SIZE (16 * 1024 * 1024)
Definition at line 36 of file sd_remote_write.c.
Function Documentation
sd_remote_staged_abort()
void sd_remote_staged_abort (brix_sd_staged_t * h)
Definition at line 193 of file sd_remote_write.c.
References sd_remote_staged_state::s3, sd_s3_abort(), and sd_s3_close().
sd_remote_staged_commit()
ngx_int_t sd_remote_staged_commit (brix_sd_staged_t * h, int noreplace)
Definition at line 142 of file sd_remote_write.c.
References sd_remote_staged_state::ak, sd_s3_open_params::ak, sd_remote_staged_state::has_cred, sd_remote_staged_state::objpath, probe(), sd_remote_staged_state::region, sd_s3_open_params::region, sd_remote_staged_state::s3, sd_remote_s3_params(), sd_s3_close(), sd_s3_commit(), sd_s3_open_read(), sd_s3_size(), sd_remote_staged_state::sk, and sd_s3_open_params::sk.
sd_remote_staged_open()
brix_sd_staged_t * sd_remote_staged_open (brix_sd_instance_t * inst, const char * final_path, mode_t mode, int * err_out)
Definition at line 93 of file sd_remote_write.c.
References sd_remote_staged_open_impl().
sd_remote_staged_open_cred()
brix_sd_staged_t * sd_remote_staged_open_cred (brix_sd_instance_t * inst, const char * final_path, mode_t mode, const brix_sd_cred_t * cred, int * err_out)
Definition at line 107 of file sd_remote_write.c.
References brix_sd_cred_t::s3_ak, brix_sd_cred_t::s3_region, brix_sd_cred_t::s3_sk, sd_remote_cred_gate(), and sd_remote_staged_open_impl().
sd_remote_staged_open_impl()
static brix_sd_staged_t * sd_remote_staged_open_impl (brix_sd_instance_t * inst, const char * final_path, const char * ak, const char * sk, const char * region, int * err_out) static
Definition at line 43 of file sd_remote_write.c.
References sd_remote_staged_state::ak, sd_s3_open_params::ak, sd_remote_staged_state::has_cred, sd_remote_staged_state::objpath, sd_remote_staged_state::region, sd_s3_open_params::region, region, sd_remote_staged_state::s3, SD_REMOTE_PART_SIZE, sd_remote_s3_key(), sd_remote_s3_params(), sd_s3_abort(), sd_s3_close(), sd_s3_open_write(), sd_remote_staged_state::sk, and sd_s3_open_params::sk.
Referenced by sd_remote_staged_open(), and sd_remote_staged_open_cred().
sd_remote_staged_write()
ssize_t sd_remote_staged_write (brix_sd_staged_t * h, const void * buf, size_t len, off_t off)
Definition at line 128 of file sd_remote_write.c.
References sd_remote_staged_state::s3, and sd_s3_pwrite().
sd_remote_unlink()
ngx_int_t sd_remote_unlink (brix_sd_instance_t * inst, const char * path, int is_dir)
Definition at line 228 of file sd_remote_write.c.
References sd_remote_unlink_impl().
sd_remote_unlink_cred()
ngx_int_t sd_remote_unlink_cred (brix_sd_instance_t * inst, const char * path, int is_dir, const brix_sd_cred_t * cred)
Definition at line 237 of file sd_remote_write.c.
References brix_sd_cred_t::s3_ak, brix_sd_cred_t::s3_region, brix_sd_cred_t::s3_sk, sd_remote_cred_gate(), and sd_remote_unlink_impl().
sd_remote_unlink_impl()
static ngx_int_t sd_remote_unlink_impl (brix_sd_instance_t * inst, const char * path, const char * ak, const char * sk, const char * region) static
Definition at line 206 of file sd_remote_write.c.
References sd_s3_open_params::ak, sd_s3_open_params::region, region, sd_remote_s3_key(), sd_remote_s3_params(), sd_s3_delete(), and sd_s3_open_params::sk.
Referenced by sd_remote_unlink(), and sd_remote_unlink_cred().