nginx-xrootd: src/fs/backend/xroot/sd_xroot.h File Reference
sd_xroot.h File Reference
#include "fs/backend/sd.h"
#include "core/compat/af_policy.h"
Functions
brix_sd_instance_t * brix_sd_xroot_create (void *conf, ngx_log_t *log)
brix_sd_instance_t * brix_sd_xroot_create_origin (const char *host, int port, int tls, int af_policy, const char *bearer, const char *x509_proxy, const char *ca_dir, const char *sss_keytab, ngx_log_t *log)
void brix_sd_xroot_destroy (brix_sd_instance_t *inst)
void brix_sd_xroot_query_checksum (brix_sd_obj_t *obj, char *alg, size_t algsz, char *hex, size_t hexsz)
Function Documentation
brix_sd_xroot_create()
brix_sd_instance_t * brix_sd_xroot_create (void * conf, ngx_log_t * log)
Definition at line 465 of file sd_xroot.c.
References brix_sd_xroot_driver, sd_xroot_inst_state::conf, log, and sd_xroot_inst_state::synth.
brix_sd_xroot_create_origin()
brix_sd_instance_t * brix_sd_xroot_create_origin (const char * host, int port, int tls, int af_policy, const char * bearer, const char * x509_proxy, const char * ca_dir, const char * sss_keytab, ngx_log_t * log)
Definition at line 492 of file sd_xroot.c.
References sd_xroot_inst_state::bearer, brix_build_ca_store(), BRIX_CRL_MODE_TRY, brix_sd_xroot_driver, BRIX_SP_MODE_OFF, sd_xroot_inst_state::ca_dir, ngx_stream_brix_srv_conf_t::cache_origin_bearer, ngx_stream_brix_srv_conf_t::cache_origin_ca_dir, ngx_stream_brix_srv_conf_t::cache_origin_family, ngx_stream_brix_srv_conf_t::cache_origin_host, ngx_stream_brix_srv_conf_t::cache_origin_port, ngx_stream_brix_srv_conf_t::cache_origin_sss_keytab, ngx_stream_brix_srv_conf_t::cache_origin_tls, ngx_stream_brix_srv_conf_t::cache_origin_x509_proxy, sd_xroot_inst_state::conf, ngx_stream_brix_srv_conf_t::gsi_store, sd_xroot_inst_state::host, log, sd_xroot_inst_state::sss_keytab, stat(), sd_xroot_inst_state::synth, tls, and sd_xroot_inst_state::x509_proxy.
Referenced by brix_cache_build_wt_origin(), brix_tier_build(), and brix_vfs_backend_build_source().
brix_sd_xroot_destroy()
void brix_sd_xroot_destroy (brix_sd_instance_t * inst)
Definition at line 579 of file sd_xroot.c.
References ngx_stream_brix_srv_conf_t::gsi_store, and sd_xroot_inst_state::synth.
Referenced by brix_cache_storage_cleanup(), and cache_build_wt_stage().
brix_sd_xroot_query_checksum()
void brix_sd_xroot_query_checksum (brix_sd_obj_t * obj, char * alg, size_t algsz, char * hex, size_t hexsz)
Definition at line 449 of file sd_xroot.c.
References brix_cache_origin_query_checksum(), hex(), sd_xroot_obj_state::oc, and sd_xroot_obj_state::t.
Referenced by brix_cache_fill_from_source().