nginx-xrootd: src/fs/backend/remote/sd_remote.c File Reference
sd_remote.c File Reference
#include "sd_remote.h"
#include "fs/backend/s3/sd_s3.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct sd_remote_obj_state
struct sd_remote_staged_state
Macros
#define SD_REMOTE_PART_SIZE (16 * 1024 * 1024)
Functions
static void sd_remote_s3_key (const brix_sd_remote_cfg_t *cfg, const char *key, char *dst, size_t dstcap)
static void sd_remote_s3_params (const brix_sd_remote_cfg_t *cfg, const char *objpath, sd_s3_open_params *p)
static int sd_remote_cred_gate (const brix_sd_cred_t *cred)
static brix_sd_obj_t * sd_remote_open_impl (brix_sd_instance_t *inst, const char *path, int sd_flags, const char *ak, const char *sk, const char *region, int *err_out)
static brix_sd_obj_t * sd_remote_open (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, int *err_out)
static brix_sd_obj_t * sd_remote_open_cred (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
static ngx_int_t sd_remote_close (brix_sd_obj_t *obj)
static ssize_t sd_remote_pread (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
static ssize_t sd_remote_pread_full (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
static ssize_t sd_remote_preadv (brix_sd_obj_t *obj, const struct iovec *iov, int iovcnt, off_t off)
static ngx_int_t sd_remote_fstat (brix_sd_obj_t *obj, brix_sd_stat_t *out)
static ngx_int_t sd_remote_stat_impl (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out, const char *ak, const char *sk, const char *region)
static ngx_int_t sd_remote_stat (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out)
static ngx_int_t sd_remote_stat_cred (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out, const brix_sd_cred_t *cred)
static brix_sd_staged_t * sd_remote_staged_open_impl (brix_sd_instance_t *inst, const char *final_path, const char *ak, const char *sk, const char *region, int *err_out)
static brix_sd_staged_t * sd_remote_staged_open (brix_sd_instance_t *inst, const char *final_path, mode_t mode, int *err_out)
static brix_sd_staged_t * sd_remote_staged_open_cred (brix_sd_instance_t *inst, const char *final_path, mode_t mode, const brix_sd_cred_t *cred, int *err_out)
static ssize_t sd_remote_staged_write (brix_sd_staged_t *h, const void *buf, size_t len, off_t off)
static ngx_int_t sd_remote_staged_commit (brix_sd_staged_t *h, int noreplace)
static void sd_remote_staged_abort (brix_sd_staged_t *h)
static ngx_int_t sd_remote_unlink_impl (brix_sd_instance_t *inst, const char *path, const char *ak, const char *sk, const char *region)
static ngx_int_t sd_remote_unlink (brix_sd_instance_t *inst, const char *path, int is_dir)
static ngx_int_t sd_remote_unlink_cred (brix_sd_instance_t *inst, const char *path, int is_dir, const brix_sd_cred_t *cred)
brix_sd_instance_t * brix_sd_remote_create (const brix_sd_remote_cfg_t *cfg, ngx_log_t *log)
void brix_sd_remote_destroy (brix_sd_instance_t *inst)
Variables
static const brix_sd_driver_t brix_sd_remote_driver
Macro Definition Documentation
SD_REMOTE_PART_SIZE
#define SD_REMOTE_PART_SIZE (16 * 1024 * 1024)
Definition at line 40 of file sd_remote.c.
Function Documentation
brix_sd_remote_create()
brix_sd_instance_t * brix_sd_remote_create (const brix_sd_remote_cfg_t * cfg, ngx_log_t * log)
Definition at line 664 of file sd_remote.c.
References brix_sd_remote_driver, BRIX_SD_REMOTE_S3, log, brix_sd_remote_cfg_t::scheme, and brix_sd_remote_cfg_t::transport.
Referenced by brix_vbr_build_s3(), and tier_build_s3().
brix_sd_remote_destroy()
void brix_sd_remote_destroy (brix_sd_instance_t * inst)
Definition at line 693 of file sd_remote.c.
sd_remote_close()
static ngx_int_t sd_remote_close (brix_sd_obj_t * obj) static
Definition at line 224 of file sd_remote.c.
References sd_remote_obj_state::s3, and sd_s3_close().
sd_remote_cred_gate()
static int sd_remote_cred_gate (const brix_sd_cred_t * cred) static
Definition at line 84 of file sd_remote.c.
References brix_sd_cred_t::fallback_deny, brix_sd_cred_t::s3_ak, and brix_sd_cred_t::s3_sk.
Referenced by sd_remote_open_cred(), sd_remote_staged_open_cred(), sd_remote_stat_cred(), and sd_remote_unlink_cred().
sd_remote_fstat()
static ngx_int_t sd_remote_fstat (brix_sd_obj_t * obj, brix_sd_stat_t * out) static
Definition at line 341 of file sd_remote.c.
sd_remote_open()
static brix_sd_obj_t * sd_remote_open (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, int * err_out) static
Definition at line 179 of file sd_remote.c.
References sd_remote_open_impl().
sd_remote_open_cred()
static brix_sd_obj_t * sd_remote_open_cred (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, const brix_sd_cred_t * cred, int * err_out) static
Definition at line 203 of file sd_remote.c.
References brix_sd_cred_t::s3_ak, brix_sd_cred_t::s3_region, brix_sd_cred_t::s3_sk, sd_remote_cred_gate(), and sd_remote_open_impl().
sd_remote_open_impl()
static brix_sd_obj_t * sd_remote_open_impl (brix_sd_instance_t * inst, const char * path, int sd_flags, const char * ak, const char * sk, const char * region, int * err_out) static
Definition at line 117 of file sd_remote.c.
References sd_s3_open_params::ak, BRIX_SD_O_APPEND, BRIX_SD_O_CREATE, BRIX_SD_O_TRUNC, BRIX_SD_O_WRITE, sd_s3_open_params::region, region, sd_remote_obj_state::s3, sd_remote_s3_key(), sd_remote_s3_params(), sd_s3_close(), sd_s3_open_read(), sd_s3_size(), and sd_s3_open_params::sk.
Referenced by sd_remote_open(), and sd_remote_open_cred().
sd_remote_pread()
static ssize_t sd_remote_pread (brix_sd_obj_t * obj, void * buf, size_t len, off_t off) static
Definition at line 239 of file sd_remote.c.
References sd_remote_obj_state::s3, and sd_s3_pread().
Referenced by sd_remote_pread_full().
sd_remote_pread_full()
static ssize_t sd_remote_pread_full (brix_sd_obj_t * obj, void * buf, size_t len, off_t off) static
Definition at line 275 of file sd_remote.c.
References sd_remote_pread().
Referenced by sd_remote_preadv().
sd_remote_preadv()
static ssize_t sd_remote_preadv (brix_sd_obj_t * obj, const struct iovec * iov, int iovcnt, off_t off) static
Definition at line 294 of file sd_remote.c.
References sd_remote_pread_full().
sd_remote_s3_key()
static void sd_remote_s3_key (const brix_sd_remote_cfg_t * cfg, const char * key, char * dst, size_t dstcap) static
Definition at line 45 of file sd_remote.c.
References brix_sd_remote_cfg_t::bucket, and key.
Referenced by sd_remote_open_impl(), sd_remote_staged_open_impl(), sd_remote_stat_impl(), and sd_remote_unlink_impl().
sd_remote_s3_params()
static void sd_remote_s3_params (const brix_sd_remote_cfg_t * cfg, const char * objpath, sd_s3_open_params * p) static
Definition at line 53 of file sd_remote.c.
References brix_sd_remote_cfg_t::access_key, sd_s3_open_params::ak, brix_sd_remote_cfg_t::host, sd_s3_open_params::host, sd_s3_open_params::key, brix_sd_remote_cfg_t::port, sd_s3_open_params::port, brix_sd_remote_cfg_t::region, sd_s3_open_params::region, brix_sd_remote_cfg_t::secret_key, sd_s3_open_params::sk, brix_sd_remote_cfg_t::tctx, sd_s3_open_params::tctx, brix_sd_remote_cfg_t::timeout_ms, sd_s3_open_params::timeout_ms, brix_sd_remote_cfg_t::tls, sd_s3_open_params::tls, brix_sd_remote_cfg_t::transport, and sd_s3_open_params::transport.
Referenced by sd_remote_open_impl(), sd_remote_staged_commit(), sd_remote_staged_open_impl(), sd_remote_stat_impl(), and sd_remote_unlink_impl().
sd_remote_staged_abort()
static void sd_remote_staged_abort (brix_sd_staged_t * h) static
Definition at line 572 of file sd_remote.c.
References sd_remote_staged_state::s3, sd_s3_abort(), and sd_s3_close().
sd_remote_staged_commit()
static ngx_int_t sd_remote_staged_commit (brix_sd_staged_t * h, int noreplace) static
Definition at line 521 of file sd_remote.c.
References sd_remote_staged_state::ak, sd_s3_open_params::ak, sd_remote_staged_state::has_cred, sd_remote_staged_state::objpath, probe(), sd_remote_staged_state::region, sd_s3_open_params::region, sd_remote_staged_state::s3, sd_remote_s3_params(), sd_s3_close(), sd_s3_commit(), sd_s3_open_read(), sd_s3_size(), sd_remote_staged_state::sk, and sd_s3_open_params::sk.
sd_remote_staged_open()
static brix_sd_staged_t * sd_remote_staged_open (brix_sd_instance_t * inst, const char * final_path, mode_t mode, int * err_out) static
Definition at line 472 of file sd_remote.c.
References sd_remote_staged_open_impl().
sd_remote_staged_open_cred()
static brix_sd_staged_t * sd_remote_staged_open_cred (brix_sd_instance_t * inst, const char * final_path, mode_t mode, const brix_sd_cred_t * cred, int * err_out) static
Definition at line 486 of file sd_remote.c.
References brix_sd_cred_t::s3_ak, brix_sd_cred_t::s3_region, brix_sd_cred_t::s3_sk, sd_remote_cred_gate(), and sd_remote_staged_open_impl().
sd_remote_staged_open_impl()
static brix_sd_staged_t * sd_remote_staged_open_impl (brix_sd_instance_t * inst, const char * final_path, const char * ak, const char * sk, const char * region, int * err_out) static
Definition at line 422 of file sd_remote.c.
References sd_remote_staged_state::ak, sd_s3_open_params::ak, sd_remote_staged_state::has_cred, sd_remote_staged_state::objpath, sd_remote_staged_state::region, sd_s3_open_params::region, region, sd_remote_staged_state::s3, SD_REMOTE_PART_SIZE, sd_remote_s3_key(), sd_remote_s3_params(), sd_s3_abort(), sd_s3_close(), sd_s3_open_write(), sd_remote_staged_state::sk, and sd_s3_open_params::sk.
Referenced by sd_remote_staged_open(), and sd_remote_staged_open_cred().
sd_remote_staged_write()
static ssize_t sd_remote_staged_write (brix_sd_staged_t * h, const void * buf, size_t len, off_t off) static
Definition at line 507 of file sd_remote.c.
References sd_remote_staged_state::s3, and sd_s3_pwrite().
sd_remote_stat()
static ngx_int_t sd_remote_stat (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out) static
Definition at line 386 of file sd_remote.c.
References sd_remote_stat_impl().
sd_remote_stat_cred()
static ngx_int_t sd_remote_stat_cred (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out, const brix_sd_cred_t * cred) static
Definition at line 397 of file sd_remote.c.
References brix_sd_cred_t::s3_ak, brix_sd_cred_t::s3_region, brix_sd_cred_t::s3_sk, sd_remote_cred_gate(), and sd_remote_stat_impl().
sd_remote_stat_impl()
static ngx_int_t sd_remote_stat_impl (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out, const char * ak, const char * sk, const char * region) static
Definition at line 350 of file sd_remote.c.
References sd_s3_open_params::ak, brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, sd_s3_open_params::region, region, sd_remote_s3_key(), sd_remote_s3_params(), sd_s3_close(), sd_s3_open_read(), sd_s3_size(), brix_sd_stat_t::size, and sd_s3_open_params::sk.
Referenced by sd_remote_stat(), and sd_remote_stat_cred().
sd_remote_unlink()
static ngx_int_t sd_remote_unlink (brix_sd_instance_t * inst, const char * path, int is_dir) static
Definition at line 607 of file sd_remote.c.
References sd_remote_unlink_impl().
sd_remote_unlink_cred()
static ngx_int_t sd_remote_unlink_cred (brix_sd_instance_t * inst, const char * path, int is_dir, const brix_sd_cred_t * cred) static
Definition at line 616 of file sd_remote.c.
References brix_sd_cred_t::s3_ak, brix_sd_cred_t::s3_region, brix_sd_cred_t::s3_sk, sd_remote_cred_gate(), and sd_remote_unlink_impl().
sd_remote_unlink_impl()
static ngx_int_t sd_remote_unlink_impl (brix_sd_instance_t * inst, const char * path, const char * ak, const char * sk, const char * region) static
Definition at line 585 of file sd_remote.c.
References sd_s3_open_params::ak, sd_s3_open_params::region, region, sd_remote_s3_key(), sd_remote_s3_params(), sd_s3_delete(), and sd_s3_open_params::sk.
Referenced by sd_remote_unlink(), and sd_remote_unlink_cred().
Variable Documentation
brix_sd_remote_driver
const brix_sd_driver_t brix_sd_remote_driver static
Initial value:
= {
    .name  = "remote",
    .caps  = BRIX_SD_CAP_RANGE_READ | BRIX_SD_CAP_MEMFILE,
    .cred_accept = BRIX_SD_CRED_BEARER | BRIX_SD_CRED_PROXY_PEM,
    .open  = sd_remote_open,
    .close = sd_remote_close,
    .pread = sd_remote_pread,
    .preadv = sd_remote_preadv,
    .fstat = sd_remote_fstat,
    .stat  = sd_remote_stat,
    .unlink        = sd_remote_unlink,
    .staged_open   = sd_remote_staged_open,
    .staged_write  = sd_remote_staged_write,
    .staged_commit = sd_remote_staged_commit,
    .staged_abort  = sd_remote_staged_abort,
    .open_cred     = sd_remote_open_cred,
    .staged_open_cred = sd_remote_staged_open_cred,
    .stat_cred        = sd_remote_stat_cred,
    .unlink_cred      = sd_remote_unlink_cred,
}
Definition at line 637 of file sd_remote.c.
Referenced by brix_sd_remote_create().