nginx-xrootd: src/fs/backend/cache/sd_cache_fill_demote.c File Reference
sd_cache_fill_demote.c File Reference
#include "sd_cache.h"
#include "sd_cache_internal.h"
#include "sd_cache_fill_internal.h"
#include <errno.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <unistd.h>
Functions
ngx_int_t brix_sd_cache_demote (brix_sd_instance_t *inst, const char *key)
Function Documentation
brix_sd_cache_demote()
ngx_int_t brix_sd_cache_demote (brix_sd_instance_t * inst, const char * key)
Definition at line 38 of file sd_cache_fill_demote.c.
References brix_sd_cache_instance_is(), BRIX_SD_O_READ, brix_sd_obj_release(), sd_cache_inst_state::cold, sd_cache_inst_state::cstore, key, SD_CACHE_CHUNK, SD_CACHE_ST, and brix_cstore_t::store.
Referenced by brix_cache_evict_one().