nginx-xrootd: src/fs/backend/s3/sd_s3_meta.c File Reference
sd_s3_meta.c File Reference
#include "sd_s3_internal.h"
#include "core/compat/crypto.h"
#include "core/compat/hex.h"
#include "core/compat/sigv4.h"
#include "core/compat/uri.h"
#include "core/compat/host_format.h"
#include <errno.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
Data Structures
struct sd_s3_sign_hdr_t
struct sd_s3_sign_req_t
struct sd_s3_sign_ctx_t
Functions
ssize_t sd_s3_get_meta (sd_s3_file *f, const char *name, const sd_s3_meta_buf *out, char *errbuf, size_t errcap)
static void sd_s3_list_meta_emit (const char *name, size_t nlen, char *buf, size_t cap, size_t *need)
static size_t sd_s3_list_meta_scan (const char *hdrs, char *buf, size_t cap)
ssize_t sd_s3_list_meta (sd_s3_file *f, char *buf, size_t cap, char *errbuf, size_t errcap)
int sd_s3_get_unixattr (sd_s3_file *f, brix_meta_advisory_t *out, char *errbuf, size_t errcap)
static int sd_s3_sign_hdr_cmp (const void *a, const void *b)
static int sd_s3_sign_prepare (const sd_s3_file *f, sd_s3_sign_ctx_t *sx)
static int sd_s3_canonical_request (sd_s3_sign_ctx_t *sx)
static int sd_s3_string_to_sign (const sd_s3_file *f, sd_s3_sign_ctx_t *sx, char *sts, size_t stscap)
static int sd_s3_derive_key_and_sign (const sd_s3_file *f, sd_s3_sign_ctx_t *sx, const char *sts)
static int sd_s3_emit_auth_header (const sd_s3_file *f, const sd_s3_sign_ctx_t *sx, char *hdrs, size_t hdrsz)
static int sd_s3_sign_ext (const sd_s3_file *f, const sd_s3_sign_req_t *req, char *hdrs, size_t hdrsz)
static int sd_s3_set_meta_f (sd_s3_file *f, const sd_s3_meta_kv *kv, size_t nkv, char *errbuf, size_t errcap)
int sd_s3_set_meta (const sd_s3_open_params *p, const sd_s3_meta_kv *kv, size_t nkv, char *errbuf, size_t errcap)
int sd_s3_set_unixattr (const sd_s3_open_params *p, const brix_meta_advisory_t *a, char *errbuf, size_t errcap)
Function Documentation
sd_s3_canonical_request()
static int sd_s3_canonical_request (sd_s3_sign_ctx_t * sx) static
Definition at line 297 of file sd_s3_meta.c.
References sd_s3_sign_ctx_t::all, sd_s3_sign_ctx_t::canon_hex, sd_s3_sign_ctx_t::canon_qs, sd_s3_sign_ctx_t::enc_uri, sd_s3_sign_ctx_t::method, sd_s3_sign_ctx_t::n_all, sd_s3_sign_hdr_t::name, sd_s3_sign_ctx_t::payload_hex, sd_s3_sha256_hex(), sd_s3_sign_ctx_t::signed_list, and sd_s3_sign_hdr_t::value.
Referenced by sd_s3_sign_ext().
sd_s3_derive_key_and_sign()
static int sd_s3_derive_key_and_sign (const sd_s3_file * f, sd_s3_sign_ctx_t * sx, const char * sts) static
Definition at line 363 of file sd_s3_meta.c.
References brix_hex_encode(), brix_hmac_sha256(), brix_sigv4_signing_key(), sd_s3_sign_ctx_t::datestamp, sd_s3_file::region, sd_s3_sign_ctx_t::sighex, and sd_s3_file::sk.
Referenced by sd_s3_sign_ext().
sd_s3_emit_auth_header()
static int sd_s3_emit_auth_header (const sd_s3_file * f, const sd_s3_sign_ctx_t * sx, char * hdrs, size_t hdrsz) static
Definition at line 386 of file sd_s3_meta.c.
References sd_s3_file::ak, sd_s3_sign_ctx_t::amzdate, sd_s3_sign_ctx_t::extra, sd_s3_sign_ctx_t::n_extra, sd_s3_sign_hdr_t::name, sd_s3_sign_ctx_t::payload_hex, sd_s3_sign_ctx_t::scope, sd_s3_sign_ctx_t::sighex, sd_s3_sign_ctx_t::signed_list, and sd_s3_sign_hdr_t::value.
Referenced by sd_s3_sign_ext().
sd_s3_get_meta()
ssize_t sd_s3_get_meta (sd_s3_file * f, const char * name, const sd_s3_meta_buf * out, char * errbuf, size_t errcap)
Definition at line 29 of file sd_s3_meta.c.
References sd_s3_meta_buf::buf, sd_s3_meta_buf::cap, sd_s3_file::host, sd_s3_file::key, name, sd_s3_file::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_free, brix_s3_transport_t::resp_header, SD_S3_AUTH_HDRS_CAP, sd_s3_set_err(), sd_s3_sign(), sd_s3_status_err(), brix_s3_resp_t::status, sd_s3_file::tctx, sd_s3_file::timeout_ms, sd_s3_file::tls, and sd_s3_file::transport.
Referenced by sd_remote_getxattr(), and sd_s3_get_unixattr().
sd_s3_get_unixattr()
int sd_s3_get_unixattr (sd_s3_file * f, brix_meta_advisory_t * out, char * errbuf, size_t errcap)
Definition at line 185 of file sd_s3_meta.c.
References brix_meta_advisory_decode(), BRIX_META_ADVISORY_S3META, sd_s3_get_meta(), and sd_s3_set_err().
sd_s3_list_meta()
ssize_t sd_s3_list_meta (sd_s3_file * f, char * buf, size_t cap, char * errbuf, size_t errcap)
Definition at line 126 of file sd_s3_meta.c.
References sd_s3_file::host, sd_s3_file::key, sd_s3_file::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_free, brix_s3_transport_t::resp_headers_raw, SD_S3_AUTH_HDRS_CAP, sd_s3_list_meta_scan(), sd_s3_set_err(), sd_s3_sign(), sd_s3_status_err(), brix_s3_resp_t::status, sd_s3_file::tctx, sd_s3_file::timeout_ms, sd_s3_file::tls, and sd_s3_file::transport.
Referenced by sd_remote_listxattr().
sd_s3_list_meta_emit()
static void sd_s3_list_meta_emit (const char * name, size_t nlen, char * buf, size_t cap, size_t * need) static
Definition at line 76 of file sd_s3_meta.c.
References name.
Referenced by sd_s3_list_meta_scan().
sd_s3_list_meta_scan()
static size_t sd_s3_list_meta_scan (const char * hdrs, char * buf, size_t cap) static
Definition at line 94 of file sd_s3_meta.c.
References BRIX_META_ADVISORY_S3META, name, and sd_s3_list_meta_emit().
Referenced by sd_s3_list_meta().
sd_s3_set_meta()
int sd_s3_set_meta (const sd_s3_open_params * p, const sd_s3_meta_kv * kv, size_t nkv, char * errbuf, size_t errcap)
Definition at line 524 of file sd_s3_meta.c.
References sd_s3_close(), sd_s3_open_read(), and sd_s3_set_meta_f().
Referenced by sd_s3_set_unixattr().
sd_s3_set_meta_f()
static int sd_s3_set_meta_f (sd_s3_file * f, const sd_s3_meta_kv * kv, size_t nkv, char * errbuf, size_t errcap) static
Definition at line 452 of file sd_s3_meta.c.
References c, sd_s3_sign_req_t::canon_qs, sd_s3_sign_req_t::extra, sd_s3_file::host, sd_s3_file::key, sd_s3_sign_req_t::method, sd_s3_sign_req_t::n_extra, sd_s3_sign_hdr_t::name, name, sd_s3_file::port, brix_s3_transport_t::request, brix_s3_transport_t::resp_free, SD_S3_AUTH_HDRS_CAP, sd_s3_set_err(), sd_s3_sign_ext(), sd_s3_status_err(), brix_s3_resp_t::status, sd_s3_file::tctx, sd_s3_file::timeout_ms, sd_s3_file::tls, sd_s3_file::transport, kv::value, and sd_s3_sign_hdr_t::value.
Referenced by sd_s3_set_meta().
sd_s3_set_unixattr()
int sd_s3_set_unixattr (const sd_s3_open_params * p, const brix_meta_advisory_t * a, char * errbuf, size_t errcap)
Definition at line 540 of file sd_s3_meta.c.
References brix_meta_advisory_encode(), BRIX_META_ADVISORY_S3META, sd_s3_set_err(), sd_s3_set_meta(), and kv::value.
sd_s3_sign_ext()
static int sd_s3_sign_ext (const sd_s3_file * f, const sd_s3_sign_req_t * req, char * hdrs, size_t hdrsz) static
Definition at line 426 of file sd_s3_meta.c.
References sd_s3_sign_req_t::canon_qs, sd_s3_sign_ctx_t::canon_qs, sd_s3_sign_req_t::extra, sd_s3_sign_ctx_t::extra, sd_s3_sign_req_t::method, sd_s3_sign_ctx_t::method, sd_s3_sign_req_t::n_extra, sd_s3_sign_ctx_t::n_extra, sd_s3_sign_ctx_t::payload_hex, sd_s3_canonical_request(), sd_s3_derive_key_and_sign(), sd_s3_emit_auth_header(), sd_s3_sign_prepare(), and sd_s3_string_to_sign().
Referenced by sd_s3_set_meta_f().
sd_s3_sign_hdr_cmp()
static int sd_s3_sign_hdr_cmp (const void * a, const void * b) static
Definition at line 221 of file sd_s3_meta.c.
References name.
Referenced by sd_s3_sign_prepare().
sd_s3_sign_prepare()
static int sd_s3_sign_prepare (const sd_s3_file * f, sd_s3_sign_ctx_t * sx) static
Definition at line 261 of file sd_s3_meta.c.
References sd_s3_sign_ctx_t::all, sd_s3_sign_ctx_t::amzdate, brix_format_host_port(), brix_http_urlencode(), sd_s3_sign_ctx_t::datestamp, sd_s3_sign_ctx_t::enc_uri, sd_s3_sign_ctx_t::extra, sd_s3_file::host, sd_s3_sign_ctx_t::host, sd_s3_file::key, sd_s3_sign_ctx_t::n_all, sd_s3_sign_ctx_t::n_extra, sd_s3_sign_hdr_t::name, sd_s3_sign_ctx_t::payload_hex, sd_s3_file::port, sd_s3_sign_hdr_cmp(), sd_s3_utc_now(), and sd_s3_sign_hdr_t::value.
Referenced by sd_s3_sign_ext().
sd_s3_string_to_sign()
static int sd_s3_string_to_sign (const sd_s3_file * f, sd_s3_sign_ctx_t * sx, char * sts, size_t stscap) static
Definition at line 338 of file sd_s3_meta.c.
References sd_s3_sign_ctx_t::amzdate, sd_s3_sign_ctx_t::canon_hex, sd_s3_sign_ctx_t::datestamp, sd_s3_file::region, and sd_s3_sign_ctx_t::scope.
Referenced by sd_s3_sign_ext().