nginx-xrootd: src/fs/backend/posix/sd_posix.c File Reference
sd_posix.c File Reference
#include "fs/backend/sd.h"
#include "fs/vfs/vfs_internal.h"
#include "core/compat/crc32c.h"
#include "core/compat/namespace_ops.h"
#include "core/compat/staged_file.h"
#include "fs/path/beneath.h"
#include "fs/path/path.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <string.h>
#include <sys/syscall.h>
#include <unistd.h>
Data Structures
struct sd_posix_state_t
struct sd_posix_dir_t
struct sd_posix_staged_t
Functions
static int sd_posix_flags (int sd_flags)
int brix_sd_posix_open_unconfined (const char *path, int sd_flags, mode_t mode)
static void sd_posix_fill_stat (const struct stat *st, brix_sd_stat_t *out)
static ngx_int_t sd_posix_init (brix_sd_instance_t *inst, void *driver_conf)
static void sd_posix_cleanup (brix_sd_instance_t *inst)
brix_sd_instance_t * brix_sd_posix_borrow_instance (ngx_pool_t *pool, ngx_log_t *log, int rootfd, const char *root_canon)
static brix_sd_obj_t * sd_posix_open (brix_sd_instance_t *inst, const char *path, int sd_flags, mode_t mode, int *err_out)
static ngx_int_t sd_posix_close (brix_sd_obj_t *obj)
static ssize_t sd_posix_pread (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
static ssize_t sd_posix_pwrite (brix_sd_obj_t *obj, const void *buf, size_t len, off_t off)
static ssize_t sd_posix_preadv (brix_sd_obj_t *obj, const struct iovec *iov, int iovcnt, off_t off)
static ssize_t sd_posix_preadv2 (brix_sd_obj_t *obj, const struct iovec *iov, int iovcnt, off_t off, int flags)
static ssize_t sd_posix_copy_range (brix_sd_obj_t *src, off_t src_off, brix_sd_obj_t *dst, off_t dst_off, size_t len)
static ngx_fd_t sd_posix_read_sendfile_fd (brix_sd_obj_t *obj, off_t off, size_t len, unsigned want_zerocopy)
static ngx_int_t sd_posix_ftruncate (brix_sd_obj_t *obj, off_t len)
static ngx_int_t sd_posix_fsync (brix_sd_obj_t *obj)
static ngx_int_t sd_posix_fstat (brix_sd_obj_t *obj, brix_sd_stat_t *out)
static ngx_int_t sd_posix_stat (brix_sd_instance_t *inst, const char *path, brix_sd_stat_t *out)
static ngx_int_t sd_posix_ns_result (brix_ns_result_t res)
static ngx_int_t sd_posix_unlink (brix_sd_instance_t *inst, const char *path, int is_dir)
static ngx_int_t sd_posix_mkdir (brix_sd_instance_t *inst, const char *path, mode_t mode)
static ngx_int_t sd_posix_rename (brix_sd_instance_t *inst, const char *src, const char *dst, int noreplace)
static ngx_int_t sd_posix_server_copy (brix_sd_instance_t *inst, const char *src, const char *dst, off_t *bytes_out)
static brix_sd_dir_t * sd_posix_opendir (brix_sd_instance_t *inst, const char *path, int *err_out)
static ngx_int_t sd_posix_readdir (brix_sd_dir_t *d, brix_sd_dirent_t *out)
static ngx_int_t sd_posix_closedir (brix_sd_dir_t *d)
static ssize_t sd_posix_getxattr (brix_sd_instance_t *inst, const char *path, const char *name, void *buf, size_t cap)
static ssize_t sd_posix_listxattr (brix_sd_instance_t *inst, const char *path, void *buf, size_t cap)
static ngx_int_t sd_posix_setxattr (brix_sd_instance_t *inst, const char *path, const char *name, const void *val, size_t len, int flags)
static ngx_int_t sd_posix_removexattr (brix_sd_instance_t *inst, const char *path, const char *name)
static brix_sd_staged_t * sd_posix_staged_open (brix_sd_instance_t *inst, const char *final_path, mode_t mode, int *err_out)
static ssize_t sd_posix_staged_write (brix_sd_staged_t *st, const void *buf, size_t len, off_t off)
static ngx_int_t sd_posix_staged_commit (brix_sd_staged_t *st, int noreplace)
static void sd_posix_staged_abort (brix_sd_staged_t *st)
static const char * sd_posix_staged_path (const brix_sd_staged_t *st)
Variables
const brix_sd_driver_t brix_sd_posix_driver
Function Documentation
brix_sd_posix_borrow_instance()
brix_sd_instance_t * brix_sd_posix_borrow_instance (ngx_pool_t * pool, ngx_log_t * log, int rootfd, const char * root_canon)
Definition at line 158 of file sd_posix.c.
References sd_posix_state_t::borrowed, brix_sd_posix_driver, log, sd_posix_state_t::root_canon, and sd_posix_state_t::rootfd.
Referenced by brix_vfs_open(), cache_build_instance(), cache_build_wt_stage(), and cs_root_lazy_posix().
brix_sd_posix_open_unconfined()
int brix_sd_posix_open_unconfined (const char * path, int sd_flags, mode_t mode)
Definition at line 85 of file sd_posix.c.
References mode, open(), and sd_posix_flags().
Referenced by brix_sd_block_open_unconfined(), and posix_be_open().
sd_posix_cleanup()
static void sd_posix_cleanup (brix_sd_instance_t * inst) static
Definition at line 142 of file sd_posix.c.
References sd_posix_state_t::borrowed, close(), and sd_posix_state_t::rootfd.
sd_posix_close()
static ngx_int_t sd_posix_close (brix_sd_obj_t * obj) static
Definition at line 220 of file sd_posix.c.
References close().
sd_posix_closedir()
static ngx_int_t sd_posix_closedir (brix_sd_dir_t * d) static
Definition at line 510 of file sd_posix.c.
References sd_posix_dir_t::dp.
sd_posix_copy_range()
static ssize_t sd_posix_copy_range (brix_sd_obj_t * src, off_t src_off, brix_sd_obj_t * dst, off_t dst_off, size_t len) static
Definition at line 279 of file sd_posix.c.
sd_posix_fill_stat()
static void sd_posix_fill_stat (const struct stat * st, brix_sd_stat_t * out) static
Definition at line 93 of file sd_posix.c.
References brix_sd_stat_t::ctime, brix_sd_stat_t::ino, brix_sd_stat_t::is_dir, brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, brix_sd_stat_t::mtime, and brix_sd_stat_t::size.
Referenced by sd_posix_fstat(), and sd_posix_stat().
sd_posix_flags()
static int sd_posix_flags (int sd_flags) static
Definition at line 58 of file sd_posix.c.
References BRIX_SD_O_APPEND, BRIX_SD_O_CREATE, BRIX_SD_O_DIR, BRIX_SD_O_EXCL, BRIX_SD_O_NOFOLLOW, BRIX_SD_O_READ, BRIX_SD_O_TRUNC, and BRIX_SD_O_WRITE.
Referenced by brix_sd_posix_open_unconfined(), and sd_posix_open().
sd_posix_fstat()
static ngx_int_t sd_posix_fstat (brix_sd_obj_t * obj, brix_sd_stat_t * out) static
Definition at line 326 of file sd_posix.c.
References fstat(), sd_posix_fill_stat(), and stat().
sd_posix_fsync()
static ngx_int_t sd_posix_fsync (brix_sd_obj_t * obj) static
Definition at line 320 of file sd_posix.c.
sd_posix_ftruncate()
static ngx_int_t sd_posix_ftruncate (brix_sd_obj_t * obj, off_t len) static
Definition at line 314 of file sd_posix.c.
sd_posix_getxattr()
static ssize_t sd_posix_getxattr (brix_sd_instance_t * inst, const char * path, const char * name, void * buf, size_t cap) static
Definition at line 529 of file sd_posix.c.
References brix_getxattr_confined_canon(), name, PATH_MAX, and sd_posix_state_t::root_canon.
sd_posix_init()
static ngx_int_t sd_posix_init (brix_sd_instance_t * inst, void * driver_conf) static
Definition at line 110 of file sd_posix.c.
References brix_beneath_open_root(), sd_posix_state_t::root_canon, and sd_posix_state_t::rootfd.
sd_posix_listxattr()
static ssize_t sd_posix_listxattr (brix_sd_instance_t * inst, const char * path, void * buf, size_t cap) static
Definition at line 546 of file sd_posix.c.
References brix_listxattr_confined_canon(), PATH_MAX, and sd_posix_state_t::root_canon.
sd_posix_mkdir()
static ngx_int_t sd_posix_mkdir (brix_sd_instance_t * inst, const char * path, mode_t mode) static
Definition at line 391 of file sd_posix.c.
References brix_ns_mkdir(), mode, PATH_MAX, sd_posix_state_t::root_canon, and sd_posix_ns_result().
sd_posix_ns_result()
static ngx_int_t sd_posix_ns_result (brix_ns_result_t res) static
Definition at line 358 of file sd_posix.c.
References BRIX_NS_OK, brix_vfs_ns_status_errno(), brix_ns_result_t::status, and brix_ns_result_t::sys_errno.
Referenced by sd_posix_mkdir(), sd_posix_rename(), sd_posix_server_copy(), and sd_posix_unlink().
sd_posix_open()
static brix_sd_obj_t * sd_posix_open (brix_sd_instance_t * inst, const char * path, int sd_flags, mode_t mode, int * err_out) static
Definition at line 191 of file sd_posix.c.
References brix_open_beneath(), close(), mode, sd_posix_state_t::rootfd, and sd_posix_flags().
sd_posix_opendir()
static brix_sd_dir_t * sd_posix_opendir (brix_sd_instance_t * inst, const char * path, int * err_out) static
Definition at line 450 of file sd_posix.c.
References brix_open_beneath(), close(), sd_posix_dir_t::dp, and sd_posix_state_t::rootfd.
sd_posix_pread()
static ssize_t sd_posix_pread (brix_sd_obj_t * obj, void * buf, size_t len, off_t off) static
Definition at line 241 of file sd_posix.c.
References pread().
sd_posix_preadv()
static ssize_t sd_posix_preadv (brix_sd_obj_t * obj, const struct iovec * iov, int iovcnt, off_t off) static
Definition at line 259 of file sd_posix.c.
sd_posix_preadv2()
static ssize_t sd_posix_preadv2 (brix_sd_obj_t * obj, const struct iovec * iov, int iovcnt, off_t off, int flags) static
Definition at line 269 of file sd_posix.c.
sd_posix_pwrite()
static ssize_t sd_posix_pwrite (brix_sd_obj_t * obj, const void * buf, size_t len, off_t off) static
Definition at line 250 of file sd_posix.c.
sd_posix_read_sendfile_fd()
static ngx_fd_t sd_posix_read_sendfile_fd (brix_sd_obj_t * obj, off_t off, size_t len, unsigned want_zerocopy) static
Definition at line 300 of file sd_posix.c.
sd_posix_readdir()
static ngx_int_t sd_posix_readdir (brix_sd_dir_t * d, brix_sd_dirent_t * out) static
Definition at line 486 of file sd_posix.c.
References sd_posix_dir_t::dp, and brix_sd_dirent_t::name.
sd_posix_removexattr()
static ngx_int_t sd_posix_removexattr (brix_sd_instance_t * inst, const char * path, const char * name) static
Definition at line 581 of file sd_posix.c.
References brix_removexattr_confined_canon(), name, PATH_MAX, and sd_posix_state_t::root_canon.
sd_posix_rename()
static ngx_int_t sd_posix_rename (brix_sd_instance_t * inst, const char * src, const char * dst, int noreplace) static
Definition at line 410 of file sd_posix.c.
References brix_ns_rename(), sd_posix_state_t::root_canon, and sd_posix_ns_result().
sd_posix_server_copy()
static ngx_int_t sd_posix_server_copy (brix_sd_instance_t * inst, const char * src, const char * dst, off_t * bytes_out) static
Definition at line 421 of file sd_posix.c.
References brix_lstat_beneath(), brix_ns_local_copy(), brix_ns_copy_opts_t::overwrite, sd_posix_state_t::root_canon, sd_posix_state_t::rootfd, sd_posix_ns_result(), sd_posix_stat(), and stat().
sd_posix_setxattr()
static ngx_int_t sd_posix_setxattr (brix_sd_instance_t * inst, const char * path, const char * name, const void * val, size_t len, int flags) static
Definition at line 563 of file sd_posix.c.
References brix_setxattr_confined_canon(), name, PATH_MAX, and sd_posix_state_t::root_canon.
sd_posix_staged_abort()
static void sd_posix_staged_abort (brix_sd_staged_t * st) static
Definition at line 674 of file sd_posix.c.
References brix_staged_abort(), sd_posix_state_t::root_canon, and sd_posix_staged_t::staged.
sd_posix_staged_commit()
static ngx_int_t sd_posix_staged_commit (brix_sd_staged_t * st, int noreplace) static
Definition at line 661 of file sd_posix.c.
References brix_staged_commit(), brix_staged_commit_excl(), sd_posix_staged_t::final_path, sd_posix_state_t::root_canon, and sd_posix_staged_t::staged.
sd_posix_staged_open()
static brix_sd_staged_t * sd_posix_staged_open (brix_sd_instance_t * inst, const char * final_path, mode_t mode, int * err_out) static
Definition at line 607 of file sd_posix.c.
References brix_staged_open(), sd_posix_staged_t::final_path, mode, PATH_MAX, sd_posix_state_t::root_canon, and sd_posix_staged_t::staged.
sd_posix_staged_path()
static const char * sd_posix_staged_path (const brix_sd_staged_t * st) static
Definition at line 685 of file sd_posix.c.
References sd_posix_staged_t::staged, and brix_staged_file_t::tmp_path.
sd_posix_staged_write()
static ssize_t sd_posix_staged_write (brix_sd_staged_t * st, const void * buf, size_t len, off_t off) static
Definition at line 649 of file sd_posix.c.
References brix_vfs_pwrite_full(), brix_staged_file_t::fd, and sd_posix_staged_t::staged.
sd_posix_stat()
static ngx_int_t sd_posix_stat (brix_sd_instance_t * inst, const char * path, brix_sd_stat_t * out) static
Definition at line 342 of file sd_posix.c.
References brix_lstat_beneath(), sd_posix_state_t::rootfd, sd_posix_fill_stat(), and stat().
Referenced by sd_posix_server_copy().
sd_posix_unlink()
static ngx_int_t sd_posix_unlink (brix_sd_instance_t * inst, const char * path, int is_dir) static
Definition at line 369 of file sd_posix.c.
References brix_ns_delete(), PATH_MAX, brix_ns_delete_opts_t::require_directory, sd_posix_state_t::root_canon, and sd_posix_ns_result().
Variable Documentation
brix_sd_posix_driver
const brix_sd_driver_t brix_sd_posix_driver
Definition at line 701 of file sd_posix.c.
Referenced by brix_sd_default_driver(), brix_sd_posix_borrow_instance(), brix_sd_posix_wrap(), brix_vfs_pwrite_full(), sd_block_fsync(), sd_block_pread(), sd_block_preadv(), sd_block_preadv2(), sd_block_pwrite(), and webdav_tpc_run_curl_pull_multi().