nginx-xrootd: src/fs/backend/rados/sd_ceph_unittest.c File Reference
sd_ceph_unittest.c File Reference
#include "sd_ceph.h"
#include "sd_ceph_compat.h"
#include <stdio.h>
#include <string.h>
Functions
static void check_norm_ok (const char *in, const char *want)
static void check_norm_reject (const char *in)
static void check_key (const char *prefix, const char *lfn, const char *want)
static void test_normalize_canonicalization (void)
static void test_key_alias_injectivity (void)
static void test_normalize_escape_rejects (void)
static void test_key_composition (void)
static void test_ino_hash (void)
static void test_striper_layout (void)
static void test_path_child (void)
int main (void)
Variables
static int failures
Function Documentation
check_key()
static void check_key (const char * prefix, const char * lfn, const char * want) static
Definition at line 49 of file sd_ceph_unittest.c.
References failures, and sd_ceph_key().
Referenced by test_key_composition().
check_norm_ok()
static void check_norm_ok (const char * in, const char * want) static
Definition at line 24 of file sd_ceph_unittest.c.
References failures, and sd_ceph_normalize().
Referenced by test_normalize_canonicalization().
check_norm_reject()
static void check_norm_reject (const char * in) static
Definition at line 37 of file sd_ceph_unittest.c.
References failures, and sd_ceph_normalize().
Referenced by test_normalize_escape_rejects().
main()
int main (void)
Definition at line 309 of file sd_ceph_unittest.c.
References failures, test_ino_hash(), test_key_alias_injectivity(), test_key_composition(), test_normalize_canonicalization(), test_normalize_escape_rejects(), test_path_child(), and test_striper_layout().
test_ino_hash()
static void test_ino_hash (void) static
Definition at line 182 of file sd_ceph_unittest.c.
References failures, and sd_ceph_ino().
Referenced by main().
test_key_alias_injectivity()
static void test_key_alias_injectivity (void) static
Definition at line 107 of file sd_ceph_unittest.c.
References failures, and sd_ceph_key().
Referenced by main().
test_key_composition()
static void test_key_composition (void) static
Definition at line 159 of file sd_ceph_unittest.c.
References check_key().
Referenced by main().
test_normalize_canonicalization()
static void test_normalize_canonicalization (void) static
Definition at line 77 of file sd_ceph_unittest.c.
References check_norm_ok().
Referenced by main().
test_normalize_escape_rejects()
static void test_normalize_escape_rejects (void) static
Definition at line 134 of file sd_ceph_unittest.c.
References check_norm_reject().
Referenced by main().
test_path_child()
static void test_path_child (void) static
Definition at line 255 of file sd_ceph_unittest.c.
References failures, name, and sd_ceph_path_child().
Referenced by main().
test_striper_layout()
static void test_striper_layout (void) static
Definition at line 211 of file sd_ceph_unittest.c.
References failures, sd_ceph_oid_is_first_stripe(), sd_ceph_oid_is_stripe_data(), and sd_ceph_oid_to_pfn().
Referenced by main().
Variable Documentation
failures
int failures static
Definition at line 21 of file sd_ceph_unittest.c.
Referenced by check_key(), check_norm_ok(), check_norm_reject(), main(), test_ino_hash(), test_key_alias_injectivity(), test_path_child(), and test_striper_layout().