nginx-xrootd: src/fs/backend/http/sd_http_select.c File Reference
sd_http_select.c File Reference
#include "sd_http_internal.h"
#include "fs/path/path.h"
#include <errno.h>
#include <stdatomic.h>
#include <stdio.h>
Functions
void sd_http_force_primary_set (int on)
void sd_http_write_path (const sd_http_inst_state *is, const char *key, char *dst, size_t cap)
static int sd_http_ep_score (const sd_http_endpoint *ep)
static sd_http_endpoint * sd_http_pick (sd_http_inst_state *is)
static sd_http_endpoint * sd_http_preferred (sd_http_inst_state *is)
static void sd_http_score (sd_http_endpoint *ep, int ok)
static void sd_http_score_noted (sd_http_inst_state *is, sd_http_endpoint *ep, int ok)
static int sd_http_ep_rank (const sd_http_endpoint *ep)
static const char * sd_http_log_key (const char *key, char *buf, size_t cap)
static void sd_http_log_switch (sd_http_inst_state *is, sd_http_endpoint *ep)
static sd_http_endpoint * sd_http_fo_select (const sd_http_req_t *rq)
static int sd_http_fo_perform (const sd_http_req_t *rq, sd_http_endpoint *ep, char *errbuf, size_t errcap)
static void sd_http_fo_note_success (const sd_http_req_t *rq, sd_http_endpoint *ep, sd_http_endpoint **used)
static sd_http_endpoint * sd_http_fo_next (const sd_http_req_t *rq, sd_http_endpoint *first)
static void sd_http_fo_note_fail (const sd_http_req_t *rq, sd_http_endpoint *ep, const char *errbuf, int attempt, int score_before)
int sd_http_request_fo (const sd_http_req_t *rq, sd_http_endpoint **used)
Variables
int g_sd_http_force_primary
Function Documentation
sd_http_ep_rank()
static int sd_http_ep_rank (const sd_http_endpoint * ep) static
Definition at line 129 of file sd_http_select.c.
References sd_http_endpoint::rank.
Referenced by sd_http_fo_next(), sd_http_fo_note_fail(), sd_http_fo_select(), and sd_http_log_switch().
sd_http_ep_score()
static int sd_http_ep_score (const sd_http_endpoint * ep) static
Definition at line 62 of file sd_http_select.c.
References sd_http_endpoint::fail_score, sd_http_endpoint::rank, and SD_HTTP_RANK_WEIGHT.
Referenced by sd_http_fo_next(), and sd_http_pick().
sd_http_fo_next()
static sd_http_endpoint * sd_http_fo_next (const sd_http_req_t * rq, sd_http_endpoint * first) static
Definition at line 297 of file sd_http_select.c.
References sd_http_inst_state::eps, sd_http_endpoint::fail_score, sd_http_inst_state::failover_note, sd_http_endpoint::host, sd_http_req_t::is, sd_http_req_t::key, sd_http_inst_state::log, sd_http_req_t::method, sd_http_inst_state::n_eps, sd_http_endpoint::port, sd_http_ep_rank(), sd_http_ep_score(), and sd_http_log_key().
Referenced by sd_http_request_fo().
sd_http_fo_note_fail()
static void sd_http_fo_note_fail (const sd_http_req_t * rq, sd_http_endpoint * ep, const char * errbuf, int attempt, int score_before) static
Definition at line 333 of file sd_http_select.c.
References sd_http_endpoint::fail_score, sd_http_endpoint::host, sd_http_req_t::is, sd_http_req_t::key, sd_http_inst_state::log, sd_http_req_t::method, sd_http_endpoint::port, sd_http_ep_rank(), and sd_http_log_key().
Referenced by sd_http_request_fo().
sd_http_fo_note_success()
static void sd_http_fo_note_success (const sd_http_req_t * rq, sd_http_endpoint * ep, sd_http_endpoint ** used) static
Definition at line 274 of file sd_http_select.c.
References sd_http_inst_state::eps, sd_http_endpoint::host, sd_http_req_t::is, sd_http_inst_state::last_failover, sd_http_inst_state::last_origin, sd_http_endpoint::port, and sd_http_log_switch().
Referenced by sd_http_request_fo().
sd_http_fo_perform()
static int sd_http_fo_perform (const sd_http_req_t * rq, sd_http_endpoint * ep, char * errbuf, size_t errcap) static
Definition at line 240 of file sd_http_select.c.
References sd_http_endpoint::base_path, sd_http_req_t::cert_pem, sd_http_req_t::extra_hdrs, sd_http_endpoint::host, sd_http_req_t::is, sd_http_req_t::key, sd_http_req_t::method, sd_http_endpoint::port, brix_s3_transport_t::request, brix_s3_transport_t::request_cred, sd_http_req_t::resp, SD_HTTP_PATH_MAX, sd_http_score_noted(), sd_http_inst_state::tctx, sd_http_inst_state::timeout_ms, sd_http_endpoint::tls, and sd_http_inst_state::transport.
Referenced by sd_http_request_fo().
sd_http_fo_select()
static sd_http_endpoint * sd_http_fo_select (const sd_http_req_t * rq) static
Definition at line 201 of file sd_http_select.c.
References sd_http_endpoint::fail_score, sd_http_req_t::force_primary, sd_http_endpoint::host, sd_http_req_t::is, sd_http_req_t::key, sd_http_inst_state::log, sd_http_req_t::method, sd_http_inst_state::n_eps, sd_http_endpoint::port, sd_http_inst_state::probe_tick, sd_http_ep_rank(), sd_http_log_key(), sd_http_pick(), and sd_http_preferred().
Referenced by sd_http_request_fo().
sd_http_force_primary_set()
void sd_http_force_primary_set (int on)
Definition at line 44 of file sd_http_select.c.
References g_sd_http_force_primary.
Referenced by cvmfs_merge_resilience().
sd_http_log_key()
static const char * sd_http_log_key (const char * key, char * buf, size_t cap) static
Definition at line 138 of file sd_http_select.c.
References brix_sanitize_log_string(), and key.
Referenced by sd_http_fo_next(), sd_http_fo_note_fail(), sd_http_fo_select(), and sd_http_request_fo().
sd_http_log_switch()
static void sd_http_log_switch (sd_http_inst_state * is, sd_http_endpoint * ep) static
Definition at line 150 of file sd_http_select.c.
References sd_http_inst_state::cur_ep, sd_http_inst_state::eps, sd_http_endpoint::fail_score, sd_http_endpoint::host, sd_http_inst_state::log, sd_http_inst_state::n_eps, sd_http_endpoint::port, sd_http_ep_rank(), and sd_http_preferred().
Referenced by sd_http_fo_note_success().
sd_http_pick()
static sd_http_endpoint * sd_http_pick (sd_http_inst_state * is) static
Definition at line 71 of file sd_http_select.c.
References sd_http_inst_state::eps, sd_http_inst_state::n_eps, and sd_http_ep_score().
Referenced by sd_http_fo_select().
sd_http_preferred()
static sd_http_endpoint * sd_http_preferred (sd_http_inst_state * is) static
Definition at line 86 of file sd_http_select.c.
References sd_http_inst_state::eps, sd_http_inst_state::n_eps, and sd_http_endpoint::rank.
Referenced by sd_http_fo_select(), and sd_http_log_switch().
sd_http_request_fo()
int sd_http_request_fo (const sd_http_req_t * rq, sd_http_endpoint ** used)
Definition at line 361 of file sd_http_select.c.
References sd_http_endpoint::fail_score, sd_http_req_t::force_primary, sd_http_req_t::is, sd_http_req_t::key, sd_http_inst_state::log, sd_http_req_t::method, sd_http_inst_state::n_eps, sd_http_fo_next(), sd_http_fo_note_fail(), sd_http_fo_note_success(), sd_http_fo_perform(), sd_http_fo_select(), and sd_http_log_key().
Referenced by sd_http_head_size(), and sd_http_pread().
sd_http_score()
static void sd_http_score (sd_http_endpoint * ep, int ok) static
Definition at line 103 of file sd_http_select.c.
References sd_http_endpoint::fail_score.
Referenced by sd_http_score_noted().
sd_http_score_noted()
static void sd_http_score_noted (sd_http_inst_state * is, sd_http_endpoint * ep, int ok) static
Definition at line 112 of file sd_http_select.c.
References sd_http_endpoint::fail_score, sd_http_inst_state::health_note, sd_http_endpoint::host, sd_http_endpoint::port, and sd_http_score().
Referenced by sd_http_fo_perform().
sd_http_write_path()
void sd_http_write_path (const sd_http_inst_state * is, const char * key, char * dst, size_t cap)
Definition at line 53 of file sd_http_select.c.
References sd_http_endpoint::base_path, sd_http_inst_state::eps, and key.
Referenced by sd_http_staged_open_common(), and sd_http_unlink().
Variable Documentation
g_sd_http_force_primary
int g_sd_http_force_primary
Definition at line 41 of file sd_http_select.c.
Referenced by sd_http_force_primary_set(), sd_http_head_size(), and sd_http_pread().