nginx-xrootd: src/protocols/webdav/search_parse.c File Reference
search_parse.c File Reference
#include "search_internal.h"
#include "core/http/http_body.h"
#include <libxml/parser.h>
#include <libxml/tree.h>
#include <stdio.h>
#include <string.h>
Functions
static xmlNodePtr webdav_search_find_child (xmlNodePtr parent, const char *name)
static void webdav_search_find_literal (xmlNodePtr n, webdav_search_query_t *q)
ngx_int_t webdav_search_parse (ngx_http_request_t *r, webdav_search_query_t *q)
Function Documentation
webdav_search_find_child()
static xmlNodePtr webdav_search_find_child (xmlNodePtr parent, const char * name) static
Definition at line 23 of file search_parse.c.
References name.
Referenced by webdav_search_parse().
webdav_search_find_literal()
static void webdav_search_find_literal (xmlNodePtr n, webdav_search_query_t * q) static
Definition at line 45 of file search_parse.c.
References webdav_search_query_t::literal, and webdav_search_find_literal().
Referenced by webdav_search_find_literal(), and webdav_search_parse().
webdav_search_parse()
ngx_int_t webdav_search_parse (ngx_http_request_t * r, webdav_search_query_t * q)
Definition at line 75 of file search_parse.c.
References brix_http_body_read_all(), webdav_search_query_t::depth, webdav_search_query_t::literal, scope, WEBDAV_SEARCH_BODY_MAX, webdav_search_find_child(), and webdav_search_find_literal().
Referenced by webdav_search_do().