nginx-xrootd: src/protocols/webdav/search.c File Reference
search.c File Reference
#include "search_internal.h"
#include "auth/impersonate/lifecycle.h"
#include "fs/path/path.h"
#include "fs/vfs/vfs.h"
#include "fs/path/reserved_names.h"
#include "core/compat/fs_walk.h"
#include "core/http/http_body.h"
#include "core/http/http_xml.h"
#include <dirent.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
Data Structures
struct webdav_search_walk_ctx_t
Functions
static ngx_flag_t webdav_search_matches (const char *href, const webdav_search_query_t *q)
static ngx_int_t webdav_search_append_response (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail, const char *href, const webdav_search_query_t *q)
static ngx_int_t webdav_search_walk (webdav_search_walk_ctx_t *w, const char *dir_path, const char *base_href)
static int webdav_search_entry_skip (const char *dname)
static ngx_int_t webdav_search_child_href (const char *base_href, const char *dname, char *child_href, size_t child_href_size)
static int webdav_search_entry_is_dir (webdav_search_walk_ctx_t *w, const char *root_canon, brix_vfs_dirent_kind_t dkind, const char *child_path)
static ngx_int_t webdav_search_visit_child (webdav_search_walk_ctx_t *w, const char *root_canon, brix_vfs_dirent_kind_t dkind, const char *child_path, const char *child_href)
static ngx_int_t webdav_search_scan_dir (webdav_search_walk_ctx_t *w, brix_vfs_dir_t *dp, const char *root_canon, const char *dir_path, const char *base_href)
static ngx_int_t webdav_search_build_body (webdav_search_walk_ctx_t *w, const char *path, const struct stat *sb, const webdav_search_query_t *q)
static ngx_int_t webdav_search_finalize (ngx_http_request_t *r, ngx_chain_t *head, ngx_chain_t *tail)
static ngx_int_t webdav_search_do (ngx_http_request_t *r)
static void webdav_search_body_handler (ngx_http_request_t *r)
ngx_int_t webdav_handle_search (ngx_http_request_t *r)
Function Documentation
webdav_handle_search()
ngx_int_t webdav_handle_search (ngx_http_request_t * r)
Definition at line 481 of file search.c.
References brix_http_read_body(), and webdav_search_body_handler().
Referenced by webdav_dispatch_lock_patch_search().
webdav_search_append_response()
static ngx_int_t webdav_search_append_response (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail, const char * href, const webdav_search_query_t * q) static
Definition at line 67 of file search.c.
References brix_http_chain_appendf(), webdav_escape_xml_text(), and webdav_search_matches().
Referenced by webdav_search_build_body(), and webdav_search_visit_child().
webdav_search_body_handler()
static void webdav_search_body_handler (ngx_http_request_t * r) static
Definition at line 463 of file search.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, webdav_metrics_finalize_request(), and webdav_search_do().
Referenced by webdav_handle_search().
webdav_search_build_body()
static ngx_int_t webdav_search_build_body (webdav_search_walk_ctx_t * w, const char * path, const struct stat * sb, const webdav_search_query_t * q) static
Definition at line 324 of file search.c.
References brix_http_chain_appendf(), webdav_search_query_t::depth, webdav_search_walk_ctx_t::head, ngx_memcpy, webdav_search_walk_ctx_t::r, webdav_search_walk_ctx_t::tail, WEBDAV_MAX_PATH, webdav_search_append_response(), and webdav_search_walk().
Referenced by webdav_search_do().
webdav_search_child_href()
static ngx_int_t webdav_search_child_href (const char * base_href, const char * dname, char * child_href, size_t child_href_size) static
Definition at line 122 of file search.c.
Referenced by webdav_search_scan_dir().
webdav_search_do()
static ngx_int_t webdav_search_do (ngx_http_request_t * r) static
Definition at line 416 of file search.c.
References webdav_search_walk_ctx_t::count, webdav_search_walk_ctx_t::head, webdav_search_walk_ctx_t::q, webdav_search_walk_ctx_t::r, stat(), webdav_search_walk_ctx_t::tail, WEBDAV_MAX_PATH, webdav_resolve_stat(), webdav_search_build_body(), webdav_search_finalize(), and webdav_search_parse().
Referenced by webdav_search_body_handler().
webdav_search_entry_is_dir()
static int webdav_search_entry_is_dir (webdav_search_walk_ctx_t * w, const char * root_canon, brix_vfs_dirent_kind_t dkind, const char * child_path) static
Definition at line 146 of file search.c.
References BRIX_PROTO_WEBDAV, brix_vfs_ctx_init(), BRIX_VFS_DT_DIR, BRIX_VFS_DT_UNKNOWN, brix_vfs_probe(), brix_vfs_stat_t::is_directory, and webdav_search_walk_ctx_t::r.
Referenced by webdav_search_visit_child().
webdav_search_entry_skip()
static int webdav_search_entry_skip (const char * dname) static
Definition at line 100 of file search.c.
References brix_is_internal_name().
Referenced by webdav_search_scan_dir().
webdav_search_finalize()
static ngx_int_t webdav_search_finalize (ngx_http_request_t * r, ngx_chain_t * head, ngx_chain_t * tail) static
Definition at line 373 of file search.c.
Referenced by webdav_search_do().
webdav_search_matches()
static ngx_flag_t webdav_search_matches (const char * href, const webdav_search_query_t * q) static
Definition at line 44 of file search.c.
References webdav_search_query_t::literal, and name.
Referenced by webdav_search_append_response().
webdav_search_scan_dir()
static ngx_int_t webdav_search_scan_dir (webdav_search_walk_ctx_t * w, brix_vfs_dir_t * dp, const char * root_canon, const char * dir_path, const char * base_href) static
Definition at line 215 of file search.c.
References brix_fs_join_path(), brix_vfs_readdir_kind(), webdav_search_walk_ctx_t::count, name, WEBDAV_MAX_PATH, webdav_search_child_href(), webdav_search_entry_skip(), WEBDAV_SEARCH_MAX_ENTRIES, and webdav_search_visit_child().
Referenced by webdav_search_walk().
webdav_search_visit_child()
static ngx_int_t webdav_search_visit_child (webdav_search_walk_ctx_t * w, const char * root_canon, brix_vfs_dirent_kind_t dkind, const char * child_path, const char * child_href) static
Definition at line 178 of file search.c.
References webdav_search_walk_ctx_t::count, webdav_search_query_t::depth, webdav_search_walk_ctx_t::head, webdav_search_walk_ctx_t::q, webdav_search_walk_ctx_t::r, webdav_search_walk_ctx_t::tail, WEBDAV_MAX_PATH, webdav_search_append_response(), webdav_search_entry_is_dir(), and webdav_search_walk().
Referenced by webdav_search_scan_dir().
webdav_search_walk()
static ngx_int_t webdav_search_walk (webdav_search_walk_ctx_t * w, const char * dir_path, const char * base_href) static
Definition at line 272 of file search.c.
References brix_dirlist_access_ok(), BRIX_PROTO_WEBDAV, brix_vfs_closedir(), brix_vfs_ctx_init(), brix_vfs_opendir_quiet(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_module, webdav_search_walk_ctx_t::r, ngx_http_brix_shared_conf_t::root_canon, and webdav_search_scan_dir().
Referenced by webdav_search_build_body(), and webdav_search_visit_child().