nginx-xrootd: client/lib/auth/sec/sec_pwd.c File Reference
sec_pwd.c File Reference
#include "sec.h"
#include "auth/gsi/gsi_core.h"
#include "core/config/envalias.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <arpa/inet.h>
#include <openssl/evp.h>
#include <openssl/crypto.h>
Macros
#define kXPC_normal 1000
#define kXPC_creds 1003
#define PWD_VERSION 10100
#define kOptsClntTty 0x0080
#define PWD_KEYLEN 16
Functions
static int pwd_have (brix_conn *c)
static int pwd_unhex (const char *hex, uint8_t *out, size_t cap)
static int pwd_load_password (void)
static uint32_t pwd_status_word (uint8_t ctype, uint16_t options)
static int pwd_first (brix_conn *c, const char *parms, uint8_t **payload, uint32_t *plen, brix_status *st)
static int pwd_more (brix_conn *c, const uint8_t *sbody, uint32_t slen, uint8_t **payload, uint32_t *plen, brix_status *st)
const brix_sec_module * brix_sec_pwd (void)
Variables
static EVP_PKEY * g_pwd_key
static uint8_t g_pwd_pass [256]
static size_t g_pwd_pass_len
static const char *const pwd_chain [] = { "XRDC_PWD", "XrdSecCREDS", NULL }
Macro Definition Documentation
kOptsClntTty
#define kOptsClntTty 0x0080
Definition at line 36 of file sec_pwd.c.
kXPC_creds
#define kXPC_creds 1003
Definition at line 34 of file sec_pwd.c.
kXPC_normal
#define kXPC_normal 1000
Definition at line 33 of file sec_pwd.c.
PWD_KEYLEN
#define PWD_KEYLEN 16
Definition at line 37 of file sec_pwd.c.
PWD_VERSION
#define PWD_VERSION 10100
Definition at line 35 of file sec_pwd.c.
Function Documentation
brix_sec_pwd()
const brix_sec_module * brix_sec_pwd (void)
Definition at line 304 of file sec_pwd.c.
References pwd_first(), pwd_have(), and pwd_more().
Referenced by build_module_list().
pwd_first()
static int pwd_first (brix_conn * c, const char * parms, uint8_t ** payload, uint32_t * plen, brix_status * st) static
Definition at line 158 of file sec_pwd.c.
References brix_gbuf_bucket(), brix_gbuf_end(), brix_gbuf_free(), brix_gbuf_init(), brix_gbuf_raw(), brix_gbuf_u32(), brix_gsi_cipher_keygen(), brix_gsi_cipher_public(), brix_status_set(), c, brix_gbuf::err, g_pwd_key, kOptsClntTty, kXPC_normal, brix_gbuf::len, brix_gbuf::p, pwd_load_password(), pwd_status_word(), PWD_VERSION, and XRDC_EAUTH.
Referenced by brix_sec_pwd().
pwd_have()
static int pwd_have (brix_conn * c) static
Definition at line 48 of file sec_pwd.c.
References brix_env_resolve(), c, and pwd_chain.
Referenced by brix_sec_pwd().
pwd_load_password()
static int pwd_load_password (void) static
Definition at line 91 of file sec_pwd.c.
References brix_env_resolve(), g_pwd_pass, g_pwd_pass_len, pwd_chain, and pwd_unhex().
Referenced by pwd_first().
pwd_more()
static int pwd_more (brix_conn * c, const uint8_t * sbody, uint32_t slen, uint8_t ** payload, uint32_t * plen, brix_status * st) static
Definition at line 224 of file sec_pwd.c.
References brix_gbuf_bucket(), brix_gbuf_end(), brix_gbuf_free(), brix_gbuf_init(), brix_gbuf_raw(), brix_gbuf_u32(), brix_gsi_cipher_encrypt(), brix_gsi_cipher_lookup(), brix_gsi_cipher_parse_peer(), brix_gsi_cipher_session_key(), brix_gsi_find_bucket(), brix_status_set(), c, brix_gbuf::err, g_pwd_key, g_pwd_pass, g_pwd_pass_len, key, kXPC_creds, brix_gbuf::len, brix_gbuf::p, PWD_KEYLEN, and XRDC_EAUTH.
Referenced by brix_sec_pwd().
pwd_status_word()
static uint32_t pwd_status_word (uint8_t ctype, uint16_t options) static
Definition at line 147 of file sec_pwd.c.
Referenced by pwd_first().
pwd_unhex()
static int pwd_unhex (const char * hex, uint8_t * out, size_t cap) static
Definition at line 65 of file sec_pwd.c.
References hex().
Referenced by pwd_load_password().
Variable Documentation
g_pwd_key
EVP_PKEY* g_pwd_key static
Definition at line 40 of file sec_pwd.c.
Referenced by pwd_first(), and pwd_more().
g_pwd_pass
uint8_t g_pwd_pass[256] static
Definition at line 41 of file sec_pwd.c.
Referenced by pwd_load_password(), and pwd_more().
g_pwd_pass_len
size_t g_pwd_pass_len static
Definition at line 42 of file sec_pwd.c.
Referenced by pwd_load_password(), and pwd_more().
pwd_chain
const char* const pwd_chain[] = { "XRDC_PWD", "XrdSecCREDS", NULL } static
Definition at line 45 of file sec_pwd.c.
Referenced by pwd_have(), and pwd_load_password().