nginx-xrootd: client/lib/auth/sec/sec_host.c File Reference
sec_host.c File Reference
#include "sec.h"
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Functions
static int host_have (brix_conn *c)
static int host_first (brix_conn *c, const char *parms, uint8_t **payload, uint32_t *plen, brix_status *st)
const brix_sec_module * brix_sec_host (void)
Function Documentation
brix_sec_host()
const brix_sec_module * brix_sec_host (void)
Definition at line 59 of file sec_host.c.
References host_first(), and host_have().
Referenced by build_module_list().
host_first()
static int host_first (brix_conn * c, const char * parms, uint8_t ** payload, uint32_t * plen, brix_status * st) static
Definition at line 29 of file sec_host.c.
References brix_status_set(), c, and XRDC_EAUTH.
Referenced by brix_sec_host().
host_have()
static int host_have (brix_conn * c) static
Definition at line 22 of file sec_host.c.
References c.
Referenced by brix_sec_host().