nginx-xrootd: client/lib/auth/sec/sec.h File Reference
sec.h File Reference
#include "brix.h"
Data Structures
struct brix_sec_module
Functions
const brix_sec_module * brix_sec_token (void)
const brix_sec_module * brix_sec_unix (void)
const brix_sec_module * brix_sec_sss (void)
const brix_sec_module * brix_sec_krb5 (void)
const brix_sec_module * brix_sec_gsi (void)
const brix_sec_module * brix_sec_host (void)
const brix_sec_module * brix_sec_pwd (void)
Function Documentation
brix_sec_gsi()
const brix_sec_module * brix_sec_gsi (void)
Definition at line 431 of file sec_gsi.c.
References gsi_first(), gsi_have(), and gsi_more().
Referenced by brix_auth_explain(), and brix_authenticate().
brix_sec_host()
const brix_sec_module * brix_sec_host (void)
Definition at line 59 of file sec_host.c.
References host_first(), and host_have().
Referenced by brix_auth_explain(), and brix_authenticate().
brix_sec_krb5()
const brix_sec_module * brix_sec_krb5 (void)
Definition at line 174 of file sec_krb5.c.
Referenced by brix_auth_explain(), and brix_authenticate().
brix_sec_pwd()
const brix_sec_module * brix_sec_pwd (void)
Definition at line 304 of file sec_pwd.c.
References pwd_first(), pwd_have(), and pwd_more().
Referenced by brix_auth_explain(), and brix_authenticate().
brix_sec_sss()
const brix_sec_module * brix_sec_sss (void)
Definition at line 150 of file sec_sss.c.
References sss_first(), and sss_have().
Referenced by brix_auth_explain(), and brix_authenticate().
brix_sec_token()
const brix_sec_module * brix_sec_token (void)
Definition at line 178 of file sec_token.c.
References token_first(), and token_have().
Referenced by brix_auth_explain(), and brix_authenticate().
brix_sec_unix()
const brix_sec_module * brix_sec_unix (void)
Definition at line 53 of file sec_unix.c.
References unix_first(), and unix_have().
Referenced by brix_auth_explain(), and brix_authenticate().