nginx-xrootd: client/lib/auth/sec/sec_gsi.c File Reference
sec_gsi.c File Reference
#include "sec.h"
#include "auth/cred/cred.h"
#include "auth/gsi/gsi_core.h"
#include "auth/gsi/proxy_req.h"
#include "protocols/root/protocol/gsi.h"
#include "core/compat/crypto.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <openssl/evp.h>
#include <openssl/bn.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
#include <openssl/crypto.h>
#include <openssl/err.h>
Macros
#define proxy_bio(path) brix_credfile_bio((path), 1)
Functions
static void proxy_path (char *out, size_t outsz)
static int gsi_have (brix_conn *c)
static uint8_t * load_proxy_pem (const char *path, size_t *outlen)
static int gsi_first (brix_conn *c, const char *parms, uint8_t **payload, uint32_t *plen, brix_status *st)
static EVP_PKEY * load_proxy_key (const char *path)
static void gsi_resolve_proxy (brix_conn *c, char *proxy, size_t sz, brix_status *st)
static uint32_t gsi_msg_step (const uint8_t *sbody, uint32_t slen)
static int gsi_req_pem_to_der (const uint8_t *pem, size_t pemlen, uint8_t **der, size_t *derlen)
static int gsi_sigpxy (brix_conn *c, const uint8_t *sbody, uint32_t slen, uint8_t **payload, uint32_t *plen, brix_status *st)
static int gsi_more (brix_conn *c, const uint8_t *sbody, uint32_t slen, uint8_t **payload, uint32_t *plen, brix_status *st)
const brix_sec_module * brix_sec_gsi (void)
Macro Definition Documentation
proxy_bio
#define proxy_bio (path) brix_credfile_bio((path), 1)
Definition at line 71 of file sec_gsi.c.
Function Documentation
brix_sec_gsi()
const brix_sec_module * brix_sec_gsi (void)
Definition at line 440 of file sec_gsi.c.
References gsi_first(), gsi_have(), and gsi_more().
Referenced by build_module_list().
gsi_first()
static int gsi_first (brix_conn * c, const char * parms, uint8_t ** payload, uint32_t * plen, brix_status * st) static
Definition at line 115 of file sec_gsi.c.
References brix_gsi_build_certreq(), brix_gsi_parse_parms(), brix_gsi_rand(), brix_status_set(), c, and XRDC_EAUTH.
Referenced by brix_sec_gsi().
gsi_have()
static int gsi_have (brix_conn * c) static
Definition at line 50 of file sec_gsi.c.
References access(), brix_cred_available(), c, proxy_path(), and XRDC_CRED_X509_PROXY.
Referenced by brix_sec_gsi().
gsi_more()
static int gsi_more (brix_conn * c, const uint8_t * sbody, uint32_t slen, uint8_t ** payload, uint32_t * plen, brix_status * st) static
Definition at line 388 of file sec_gsi.c.
References brix_gsi_build_cert_response_ex(), brix_status_set(), c, gsi_msg_step(), gsi_resolve_proxy(), gsi_sigpxy(), kXGS_pxyreq, load_proxy_key(), load_proxy_pem(), and XRDC_EAUTH.
Referenced by brix_sec_gsi().
gsi_msg_step()
static uint32_t gsi_msg_step (const uint8_t * sbody, uint32_t slen) static
Definition at line 208 of file sec_gsi.c.
Referenced by gsi_more().
gsi_req_pem_to_der()
static int gsi_req_pem_to_der (const uint8_t * pem, size_t pemlen, uint8_t ** der, size_t * derlen) static
Definition at line 226 of file sec_gsi.c.
Referenced by gsi_sigpxy().
gsi_resolve_proxy()
static void gsi_resolve_proxy (brix_conn * c, char * proxy, size_t sz, brix_status * st) static
Definition at line 191 of file sec_gsi.c.
References brix_cred_acquire(), brix_status_clear(), c, brix_cred_view::path, proxy_path(), and XRDC_CRED_X509_PROXY.
Referenced by gsi_more(), and gsi_sigpxy().
gsi_sigpxy()
static int gsi_sigpxy (brix_conn * c, const uint8_t * sbody, uint32_t slen, uint8_t ** payload, uint32_t * plen, brix_status * st) static
Definition at line 264 of file sec_gsi.c.
References brix_gbuf_bucket(), brix_gbuf_end(), brix_gbuf_free(), brix_gbuf_init(), brix_gbuf_start(), brix_gsi_cipher_decrypt(), brix_gsi_cipher_encrypt(), brix_gsi_cipher_lookup(), brix_gsi_find_bucket(), brix_gsi_sign_pxyreq(), brix_status_set(), c, brix_gsi_buf_t::data, brix_gbuf::err, gsi_req_pem_to_der(), gsi_resolve_proxy(), kXGC_sigpxy, kXRS_cipher_alg, kXRS_main, kXRS_x509, kXRS_x509_req, brix_gbuf::len, brix_gsi_buf_t::len, load_proxy_key(), load_proxy_pem(), brix_gbuf::p, and XRDC_EAUTH.
Referenced by gsi_more().
load_proxy_key()
static EVP_PKEY * load_proxy_key (const char * path) static
Definition at line 175 of file sec_gsi.c.
References proxy_bio.
Referenced by gsi_more(), and gsi_sigpxy().
load_proxy_pem()
static uint8_t * load_proxy_pem (const char * path, size_t * outlen) static
Definition at line 76 of file sec_gsi.c.
References proxy_bio.
Referenced by gsi_more(), and gsi_sigpxy().
proxy_path()
static void proxy_path (char * out, size_t outsz) static
Definition at line 39 of file sec_gsi.c.
Referenced by brix_cache_origin_auth_gsi(), brix_gsi_cert_explain(), cfg_copy_alloc(), gsi_have(), gsi_resolve_proxy(), originauth_gsi_load_credential(), and originauth_gsi_warn_bare_cert().