nginx-xrootd: client/lib/auth/sec/sec_token.c File Reference
sec_token.c File Reference
#include "sec.h"
#include "auth/cred/cred.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Functions
static void rstrip (char *s)
static char * slurp (const char *path)
char * brix_token_discover (void)
static int token_have (brix_conn *c)
static int token_first (brix_conn *c, const char *parms, uint8_t **payload, uint32_t *plen, brix_status *st)
const brix_sec_module * brix_sec_token (void)
Function Documentation
brix_sec_token()
const brix_sec_module * brix_sec_token (void)
Definition at line 178 of file sec_token.c.
References token_first(), and token_have().
Referenced by build_module_list().
brix_token_discover()
char * brix_token_discover (void)
Definition at line 81 of file sec_token.c.
References rstrip(), and slurp().
Referenced by auth_suite_token_probes(), chk_probe_cred_validity(), diagnose_token(), doctor_discover_creds(), explain_env_credentials(), obtain_token(), remote_doctor_report_creds(), token_first(), token_have(), token_needs_refresh(), xrd_run_battery(), and xrd_whoami().
rstrip()
static void rstrip (char * s) static
Definition at line 22 of file sec_token.c.
References s.
Referenced by brix_token_discover(), and slurp().
slurp()
static char * slurp (const char * path) static
Definition at line 32 of file sec_token.c.
References brix_open_credfile(), close(), and rstrip().
Referenced by brix_token_discover().
token_first()
static int token_first (brix_conn * c, const char * parms, uint8_t ** payload, uint32_t * plen, brix_status * st) static
Definition at line 133 of file sec_token.c.
References brix_cred_acquire(), brix_status_clear(), brix_status_set(), brix_token_discover(), c, brix_cred_view::token, XRDC_CRED_BEARER, and XRDC_EAUTH.
Referenced by brix_sec_token().
token_have()
static int token_have (brix_conn * c) static
Definition at line 116 of file sec_token.c.
References brix_cred_available(), brix_token_discover(), c, and XRDC_CRED_BEARER.
Referenced by brix_sec_token().