nginx-xrootd: src/protocols/cvmfs/secure.c File Reference
secure.c File Reference
#include "cvmfs.h"
#include "cvmfs_module_internal.h"
#include "auth/token/issuer_registry.h"
#include "core/compat/cstr.h"
#include "core/types/tunables.h"
#include <limits.h>
Functions
static ngx_int_t scvmfs_bearer_token (ngx_http_request_t *r, const char **token, size_t *len)
static ngx_int_t scvmfs_check_bearer (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf)
char * cvmfs_conf_repo_authz (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static brix_cvmfs_repo_authz_t * cvmfs_repo_authz_match (ngx_http_brix_cvmfs_loc_conf_t *lcf, const char *repo, size_t repo_len)
ngx_int_t brix_cvmfs_repo_authz_eval (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf)
ngx_int_t brix_scvmfs_preamble (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf)
char * cvmfs_conf_qos (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static brix_cvmfs_qos_t * cvmfs_qos_class (ngx_http_brix_cvmfs_loc_conf_t *lcf, const char *sub)
ngx_int_t brix_cvmfs_qos_check (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf)
Function Documentation
brix_cvmfs_qos_check()
ngx_int_t brix_cvmfs_qos_check (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf)
Definition at line 382 of file secure.c.
References cls(), cvmfs_qos_class(), ngx_http_brix_cvmfs_module, ngx_http_brix_cvmfs_loc_conf_t::qos, and ngx_http_brix_cvmfs_ctx_t::token_sub.
Referenced by cvmfs_tier_serve_or_fill().
brix_cvmfs_repo_authz_eval()
ngx_int_t brix_cvmfs_repo_authz_eval (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf)
Definition at line 181 of file secure.c.
References brix_str_cbuf(), BRIX_TOKEN_CLOCK_SKEW_SECS, BRIX_TOKEN_OP_READ, brix_token_validate_registry(), brix_token_registry_args_t::claims, brix_token_registry_args_t::clock_skew, cvmfs_repo_authz_match(), brix_token_registry_args_t::log, brix_token_registry_args_t::macaroon_secret, ngx_http_brix_cvmfs_module, PATH_MAX, brix_token_registry_args_t::reg, brix_cvmfs_repo_authz_t::registry, ngx_http_brix_cvmfs_loc_conf_t::repo_authz, scvmfs_bearer_token(), brix_token_registry_args_t::secret_len, brix_token_claims_t::sub, brix_token_registry_args_t::token, brix_token_registry_args_t::token_len, ngx_http_brix_cvmfs_ctx_t::token_sub, and ngx_http_brix_cvmfs_ctx_t::url.
Referenced by brix_cvmfs_gate().
brix_scvmfs_preamble()
ngx_int_t brix_scvmfs_preamble (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf)
Definition at line 256 of file secure.c.
References BRIX_CVMFS_CLASS_REJECT, BRIX_CVMFS_METRIC_INC, BRIX_SCVMFS_AUTHZ_BEARER, BRIX_SCVMFS_AUTHZ_NONE, ngx_http_brix_cvmfs_module, ngx_http_brix_cvmfs_loc_conf_t::scvmfs_authz, scvmfs_check_bearer(), and ngx_http_brix_cvmfs_ctx_t::secure.
Referenced by ngx_http_brix_cvmfs_handler().
cvmfs_conf_qos()
char * cvmfs_conf_qos (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 299 of file secure.c.
References c, brix_cvmfs_qos_t::fills, brix_cvmfs_qos_t::name, and brix_cvmfs_qos_t::sub.
cvmfs_conf_repo_authz()
char * cvmfs_conf_repo_authz (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 125 of file secure.c.
References c, brix_cvmfs_repo_authz_t::issuers, brix_cvmfs_repo_authz_t::registry, and brix_cvmfs_repo_authz_t::repo.
cvmfs_qos_class()
static brix_cvmfs_qos_t * cvmfs_qos_class (ngx_http_brix_cvmfs_loc_conf_t * lcf, const char * sub) static
Definition at line 358 of file secure.c.
References ngx_http_brix_cvmfs_loc_conf_t::qos.
Referenced by brix_cvmfs_qos_check().
cvmfs_repo_authz_match()
static brix_cvmfs_repo_authz_t * cvmfs_repo_authz_match (ngx_http_brix_cvmfs_loc_conf_t * lcf, const char * repo, size_t repo_len) static
Definition at line 161 of file secure.c.
References brix_cvmfs_repo_authz_t::repo, and ngx_http_brix_cvmfs_loc_conf_t::repo_authz.
Referenced by brix_cvmfs_repo_authz_eval().
scvmfs_bearer_token()
static ngx_int_t scvmfs_bearer_token (ngx_http_request_t * r, const char ** token, size_t * len) static
Definition at line 28 of file secure.c.
References ngx_memcpy, and ngx_pnalloc().
Referenced by brix_cvmfs_repo_authz_eval(), and scvmfs_check_bearer().
scvmfs_check_bearer()
static ngx_int_t scvmfs_check_bearer (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf) static
Definition at line 57 of file secure.c.
References brix_str_cbuf(), BRIX_TOKEN_CLOCK_SKEW_SECS, BRIX_TOKEN_OP_READ, brix_token_validate_registry(), brix_token_registry_args_t::claims, brix_token_registry_args_t::clock_skew, brix_token_registry_args_t::log, brix_token_registry_args_t::macaroon_secret, ngx_http_brix_cvmfs_module, PATH_MAX, brix_token_registry_args_t::reg, scvmfs_bearer_token(), ngx_http_brix_cvmfs_loc_conf_t::scvmfs_registry, brix_token_registry_args_t::secret_len, brix_token_claims_t::sub, brix_token_registry_args_t::token, brix_token_registry_args_t::token_len, and ngx_http_brix_cvmfs_ctx_t::token_sub.
Referenced by brix_scvmfs_preamble().