nginx-xrootd: src/net/cms/server_auth.c File Reference
server_auth.c File Reference
#include "server.h"
#include "core/compat/net_target.h"
#include "auth/sss/sss_internal.h"
Macros
#define CMS_SSS_LIFETIME 3600
Functions
ngx_int_t brix_cms_srv_check_peer (ngx_connection_t *c, ngx_stream_brix_cms_srv_conf_t *conf)
ngx_int_t brix_cms_srv_verify_xauth (brix_cms_srv_ctx_t *ctx, const u_char *payload, size_t payload_len)
Macro Definition Documentation
CMS_SSS_LIFETIME
#define CMS_SSS_LIFETIME 3600
Definition at line 28 of file server_auth.c.
Function Documentation
brix_cms_srv_check_peer()
ngx_int_t brix_cms_srv_check_peer (ngx_connection_t * c, ngx_stream_brix_cms_srv_conf_t * conf)
Definition at line 31 of file server_auth.c.
References c.
Referenced by brix_cms_srv_handler().
brix_cms_srv_verify_xauth()
ngx_int_t brix_cms_srv_verify_xauth (brix_cms_srv_ctx_t * ctx, const u_char * payload, size_t payload_len)
Definition at line 62 of file server_auth.c.
References brix_sanitize_log_string(), brix_sss_verify_blob(), brix_cms_srv_ctx_t::c, CMS_SSS_LIFETIME, brix_cms_srv_ctx_t::conf, brix_cms_srv_ctx_t::host, key, and name.
Referenced by cms_srv_frame_xauth().