nginx-xrootd: src/net/cms/server_module.c File Reference
server_module.c File Reference
#include "server.h"
#include "core/config/config.h"
Functions
static void * brix_cms_srv_create_conf (ngx_conf_t *cf)
static char * brix_cms_srv_merge_conf (ngx_conf_t *cf, void *parent, void *child)
static char * brix_cms_srv_set_enable (ngx_conf_t *cf, ngx_command_t *cmd, void *conf_ptr)
static char * brix_cms_srv_set_allow (ngx_conf_t *cf, ngx_command_t *cmd, void *conf_ptr)
static char * brix_cms_srv_set_sss_keytab (ngx_conf_t *cf, ngx_command_t *cmd, void *conf_ptr)
Variables
static ngx_command_t brix_cms_srv_commands []
static ngx_stream_module_t brix_cms_srv_module_ctx
ngx_module_t ngx_stream_brix_cms_srv_module
Function Documentation
brix_cms_srv_create_conf()
static void * brix_cms_srv_create_conf (ngx_conf_t * cf) static
Definition at line 10 of file server_module.c.
References ngx_pcalloc().
brix_cms_srv_merge_conf()
static char * brix_cms_srv_merge_conf (ngx_conf_t * cf, void * parent, void * child) static
Definition at line 37 of file server_module.c.
brix_cms_srv_set_allow()
static char * brix_cms_srv_set_allow (ngx_conf_t * cf, ngx_command_t * cmd, void * conf_ptr) static
Definition at line 143 of file server_module.c.
brix_cms_srv_set_enable()
static char * brix_cms_srv_set_enable (ngx_conf_t * cf, ngx_command_t * cmd, void * conf_ptr) static
Definition at line 94 of file server_module.c.
References brix_cms_srv_handler(), and ngx_stream_brix_module.
brix_cms_srv_set_sss_keytab()
static char * brix_cms_srv_set_sss_keytab (ngx_conf_t * cf, ngx_command_t * cmd, void * conf_ptr) static
Definition at line 187 of file server_module.c.
References brix_sss_load_keytab().
Variable Documentation
brix_cms_srv_commands
ngx_command_t brix_cms_srv_commands[] static
Definition at line 217 of file server_module.c.
brix_cms_srv_module_ctx
ngx_stream_module_t brix_cms_srv_module_ctx static
Initial value:
= {
    NULL,
    NULL,
    NULL,
    NULL,
    brix_cms_srv_create_conf,
    brix_cms_srv_merge_conf,
}
Definition at line 303 of file server_module.c.
ngx_stream_brix_cms_srv_module
ngx_module_t ngx_stream_brix_cms_srv_module
Initial value:
= {
    NGX_MODULE_V1,
    &brix_cms_srv_module_ctx,
    brix_cms_srv_commands,
    NGX_STREAM_MODULE,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NGX_MODULE_V1_PADDING
}
Definition at line 312 of file server_module.c.
Referenced by brix_cms_srv_handler().