nginx-xrootd: src/net/cms/server_recv_frame.c File Reference
server_recv_frame.c File Reference
#include "server.h"
#include "server_recv_internal.h"
#include "router.h"
#include "rrdata.h"
#include "net/manager/registry.h"
#include "net/manager/loc_cache.h"
#include "recv_internal.h"
#include "cns.h"
#include "fanout.h"
Typedefs
typedef void(* cms_srv_frame_pt) (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
Functions
static void cms_srv_blfile_tick (brix_cms_srv_ctx_t *ctx, ngx_uint_t force, ngx_log_t *log)
static void brix_cms_srv_ping_timer (ngx_event_t *ev)
static void cms_srv_complete_login (brix_cms_srv_ctx_t *ctx)
static void cms_srv_frame_login (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
static void cms_srv_frame_xauth (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
static void cms_srv_frame_load (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
static void cms_srv_frame_avail (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
static void cms_srv_frame_pong (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
static void cms_srv_frame_ping (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
static void cms_srv_frame_disc (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
static void cms_srv_frame_update (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
static void cms_srv_frame_statfs (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
static void cms_srv_frame_status (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
static void cms_srv_frame_usage (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
static void cms_srv_frame_stats (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
static void cms_srv_frame_gone (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
static void cms_srv_frame_have (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
static void cms_srv_frame_error (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
static void cms_srv_frame_cns (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
static void cms_srv_frame_unknown (brix_cms_srv_ctx_t *ctx, u_char code)
void cms_srv_process_frame (brix_cms_srv_ctx_t *ctx, u_char code, uint32_t streamid, const u_char *payload, size_t payload_len)
Variables
struct {
u_char code
cms_srv_frame_pt handler
} cms_srv_frame_routes []
Typedef Documentation
cms_srv_frame_pt
typedef void(* cms_srv_frame_pt) (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
Definition at line 140 of file server_recv_frame.c.
Function Documentation
brix_cms_srv_ping_timer()
static void brix_cms_srv_ping_timer (ngx_event_t * ev) static
Definition at line 57 of file server_recv_frame.c.
References brix_cms_srv_close(), brix_cms_srv_send_ping(), BRIX_SESS_END_ERROR, cms_srv_blfile_tick(), cms_srv_set_end_hint(), brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::interval_ms, and brix_cms_srv_ctx_t::ping_timer.
Referenced by cms_srv_complete_login().
cms_srv_blfile_tick()
static void cms_srv_blfile_tick (brix_cms_srv_ctx_t * ctx, ngx_uint_t force, ngx_log_t * log) static
Definition at line 49 of file server_recv_frame.c.
References brix_cms_blfile_poll(), brix_cms_srv_ctx_t::conf, brix_cms_srv_ctx_t::interval_ms, and log.
Referenced by brix_cms_srv_ping_timer(), and cms_srv_complete_login().
cms_srv_complete_login()
static void cms_srv_complete_login (brix_cms_srv_ctx_t * ctx) static
Definition at line 86 of file server_recv_frame.c.
References brix_cms_srv_node_add(), brix_cms_srv_ping_timer(), brix_srv_register(), brix_srv_set_vnid(), brix_cms_srv_ctx_t::c, cms_srv_blfile_tick(), cms_srv_log_registration(), brix_cms_srv_ctx_t::free_mb, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::idle_timeout_ms, brix_cms_srv_ctx_t::interval_ms, brix_cms_srv_ctx_t::logged_in, brix_cms_srv_ctx_t::paths, brix_cms_srv_ctx_t::ping_timer, brix_cms_srv_ctx_t::port, brix_cms_srv_ctx_t::util_pct, and brix_cms_srv_ctx_t::vnid.
Referenced by cms_srv_frame_login(), and cms_srv_frame_xauth().
cms_srv_frame_avail()
static void cms_srv_frame_avail (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len) static
Definition at line 232 of file server_recv_frame.c.
References brix_srv_update_load(), cms_srv_parse_avail(), brix_cms_srv_ctx_t::free_mb, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, brix_cms_srv_ctx_t::port, and brix_cms_srv_ctx_t::util_pct.
cms_srv_frame_cns()
static void cms_srv_frame_cns (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len) static
Definition at line 568 of file server_recv_frame.c.
References brix_cns_apply(), brix_cns_collecting(), brix_cns_event_decode(), BRIX_CNS_PATH_MAX, brix_cms_srv_ctx_t::c, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, op, and brix_cms_srv_ctx_t::port.
cms_srv_frame_disc()
static void cms_srv_frame_disc (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len) static
Definition at line 277 of file server_recv_frame.c.
References brix_cms_srv_send_disc(), BRIX_SESS_END_CLIENT, brix_cms_srv_ctx_t::c, cms_srv_fail_close(), and brix_cms_srv_ctx_t::host.
cms_srv_frame_error()
static void cms_srv_frame_error (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len) static
Definition at line 536 of file server_recv_frame.c.
References brix_cms_fanout_note_error(), brix_cms_srv_ctx_t::c, brix_cms_srv_ctx_t::logged_in, and ngx_memcpy.
cms_srv_frame_gone()
static void cms_srv_frame_gone (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len) static
Definition at line 449 of file server_recv_frame.c.
References BRIX_SRV_MAX_PATHS, brix_srv_unregister_path(), brix_cms_srv_ctx_t::c, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, ngx_memcpy, and brix_cms_srv_ctx_t::port.
cms_srv_frame_have()
static void cms_srv_frame_have (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len) static
Definition at line 484 of file server_recv_frame.c.
References brix_cms_wake_pending_session(), brix_loc_cache_insert(), BRIX_LOC_CACHE_PATH_MAX, brix_srv_is_blacklisted(), brix_srv_paths_cover(), brix_cms_srv_ctx_t::c, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, ngx_memcpy, brix_cms_srv_ctx_t::paths, and brix_cms_srv_ctx_t::port.
cms_srv_frame_load()
static void cms_srv_frame_load (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len) static
Definition at line 211 of file server_recv_frame.c.
References brix_srv_set_machine_load(), brix_srv_update_load(), cms_srv_parse_load_free_mb(), cms_srv_parse_load_machine_pct(), brix_cms_srv_ctx_t::free_mb, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, brix_cms_srv_ctx_t::port, and brix_cms_srv_ctx_t::util_pct.
cms_srv_frame_login()
static void cms_srv_frame_login (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len) static
Definition at line 151 of file server_recv_frame.c.
References brix_cms_srv_ctx_t::auth_state, brix_cms_srv_send_xauth(), BRIX_SESS_END_ERROR, brix_cms_srv_ctx_t::c, CMS_AUTH_CHALLENGED, CMS_AUTH_REQUESTED, cms_srv_complete_login(), cms_srv_fail_close(), cms_srv_log_auth_fail(), cms_srv_parse_login(), and brix_cms_srv_ctx_t::host.
cms_srv_frame_ping()
static void cms_srv_frame_ping (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len) static
Definition at line 262 of file server_recv_frame.c.
References brix_cms_srv_send_pong(), BRIX_SESS_END_ERROR, brix_cms_srv_ctx_t::c, cms_srv_fail_close(), and brix_cms_srv_ctx_t::host.
cms_srv_frame_pong()
static void cms_srv_frame_pong (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len) static
Definition at line 250 of file server_recv_frame.c.
References brix_cms_srv_ctx_t::c, and brix_cms_srv_ctx_t::host.
cms_srv_frame_statfs()
static void cms_srv_frame_statfs (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len) static
Definition at line 309 of file server_recv_frame.c.
References brix_cms_rrdata_parse(), brix_cms_srv_send_data(), brix_cms_statfs_encode(), brix_srv_aggregate_space(), brix_srv_count_matching(), CMS_RR_STATFS, brix_cms_srv_ctx_t::logged_in, brix_cms_rrdata_t::path, brix_cms_statfs_fields_t::s_free, brix_cms_statfs_fields_t::s_num, brix_cms_statfs_fields_t::s_util, brix_cms_statfs_fields_t::w_free, brix_cms_statfs_fields_t::w_num, and brix_cms_statfs_fields_t::w_util.
cms_srv_frame_stats()
static void cms_srv_frame_stats (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len) static
Definition at line 420 of file server_recv_frame.c.
References brix_cms_srv_send_data(), and brix_cms_srv_ctx_t::logged_in.
cms_srv_frame_status()
static void cms_srv_frame_status (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len) static
Definition at line 351 of file server_recv_frame.c.
References brix_srv_blacklist(), brix_srv_reset(), brix_srv_set_stage(), brix_srv_undrain(), brix_cms_srv_ctx_t::c, CMS_ST_NOSTAGE, CMS_ST_RESET, CMS_ST_RESUME, CMS_ST_STAGE, CMS_ST_SUSPEND, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::inbuf, brix_cms_srv_ctx_t::logged_in, and brix_cms_srv_ctx_t::port.
cms_srv_frame_unknown()
static void cms_srv_frame_unknown (brix_cms_srv_ctx_t * ctx, u_char code) static
Definition at line 607 of file server_recv_frame.c.
References brix_cms_route_lookup(), brix_cms_srv_ctx_t::c, code, brix_cms_srv_ctx_t::host, brix_cms_route_t::name, and XRDCMS_ROLE_MANAGER.
Referenced by cms_srv_process_frame().
cms_srv_frame_update()
static void cms_srv_frame_update (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len) static
Definition at line 291 of file server_recv_frame.c.
References brix_cms_srv_send_status(), BRIX_SESS_END_ERROR, brix_cms_srv_ctx_t::c, cms_srv_fail_close(), CMS_ST_NOSTAGE, CMS_ST_RESUME, and brix_cms_srv_ctx_t::host.
cms_srv_frame_usage()
static void cms_srv_frame_usage (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len) static
Definition at line 394 of file server_recv_frame.c.
References brix_cms_meter_sample(), brix_cms_srv_send_load(), brix_srv_aggregate_space(), brix_cms_srv_ctx_t::conf, and brix_cms_srv_ctx_t::logged_in.
cms_srv_frame_xauth()
static void cms_srv_frame_xauth (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len) static
Definition at line 184 of file server_recv_frame.c.
References brix_cms_srv_ctx_t::auth_state, brix_cms_srv_verify_xauth(), BRIX_SESS_END_ERROR, brix_cms_srv_ctx_t::c, CMS_AUTH_CHALLENGED, CMS_AUTH_DONE, cms_srv_complete_login(), cms_srv_fail_close(), cms_srv_log_auth_fail(), and brix_cms_srv_ctx_t::host.
cms_srv_process_frame()
void cms_srv_process_frame (brix_cms_srv_ctx_t * ctx, u_char code, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 655 of file server_recv_frame.c.
References cms_srv_frame_routes, cms_srv_frame_unknown(), and code.
Referenced by cms_srv_dispatch_frame().
Variable Documentation
[struct]
const struct { ... } cms_srv_frame_routes[]
Initial value:
= {
    {  0  ,  cms_srv_frame_login  },
    {  27  ,  cms_srv_frame_xauth  },
    {  16  ,   cms_srv_frame_load   },
    {  12  ,  cms_srv_frame_avail  },
    {  19  ,  cms_srv_frame_avail  },
    {  18  ,   cms_srv_frame_pong   },
    {  17  ,   cms_srv_frame_ping   },
    {  13  ,   cms_srv_frame_disc   },
    {  25  , cms_srv_frame_update },
    {  21  , cms_srv_frame_statfs },
    {  26  ,  cms_srv_frame_usage  },
    {  11  ,  cms_srv_frame_stats  },
    {  22  , cms_srv_frame_status },
    {  14  ,   cms_srv_frame_gone   },
    {  15  ,   cms_srv_frame_have   },
    {  1  , cms_srv_frame_error  },
    {  40 ,    cms_srv_frame_cns    },
    { 0,             NULL                 },
}
Referenced by cms_srv_process_frame().
code
u_char code
Definition at line 626 of file server_recv_frame.c.
Referenced by cms_srv_frame_unknown(), and cms_srv_process_frame().
handler
cms_srv_frame_pt handler
Definition at line 627 of file server_recv_frame.c.