nginx-xrootd: src/core/config/server_conf_merge_proxy_net.c File Reference
server_conf_merge_proxy_net.c File Reference
#include "config.h"
#include "server_conf_internal.h"
#include "net/manager/registry.h"
Functions
static void brix_merge_srv_proxy (ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
static char * brix_merge_srv_writethrough (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
static void brix_merge_srv_net_fault (ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
char * brix_merge_srv_proxy_net (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
Function Documentation
brix_merge_srv_net_fault()
static void brix_merge_srv_net_fault (ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 146 of file server_conf_merge_proxy_net.c.
References brix_ocsp_conf_merge(), and brix_srv_set_stale_after().
Referenced by brix_merge_srv_proxy_net().
brix_merge_srv_proxy()
static void brix_merge_srv_proxy (ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 36 of file server_conf_merge_proxy_net.c.
References BRIX_MERGE_HOSTPORT, BRIX_MERGE_PTR, BRIX_PROXY_AUTH_ANONYMOUS, and BRIX_PROXY_LOGIN_ANONYMOUS.
Referenced by brix_merge_srv_proxy_net().
brix_merge_srv_proxy_net()
char * brix_merge_srv_proxy_net (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev)
Definition at line 184 of file server_conf_merge_proxy_net.c.
References brix_merge_srv_net_fault(), brix_merge_srv_proxy(), and brix_merge_srv_writethrough().
Referenced by ngx_stream_brix_merge_srv_conf().
brix_merge_srv_writethrough()
static char * brix_merge_srv_writethrough (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 92 of file server_conf_merge_proxy_net.c.
References brix_merge_arrays(), BRIX_MERGE_ENUM, BRIX_MERGE_HOSTPORT, brix_wt_default_decide(), BRIX_WT_MODE_SYNC, and BRIX_WT_MODE_UNSET.
Referenced by brix_merge_srv_proxy_net().