nginx-xrootd: src/net/cms/server.h File Reference
server.h File Reference
#include "cms_internal.h"
#include "net/manager/registry.h"
Data Structures
struct brix_cms_srv_ctx_t
struct ngx_stream_brix_cms_srv_conf_t
Enumerations
enum brix_cms_auth_state_t { CMS_AUTH_NONE = 0 , CMS_AUTH_REQUESTED , CMS_AUTH_CHALLENGED , CMS_AUTH_DONE }
Functions
ngx_uint_t brix_cms_srv_conn_count (void)
void brix_cms_srv_conn_inc (void)
void brix_cms_srv_conn_dec (void)
ngx_uint_t brix_cms_srv_ip_count (const char *ip)
void brix_cms_srv_ip_inc (const char *ip)
void brix_cms_srv_ip_dec (const char *ip)
void brix_cms_srv_handler (ngx_stream_session_t *s)
void brix_cms_srv_read (ngx_event_t *ev)
void brix_cms_srv_write (ngx_event_t *ev)
void brix_cms_srv_close (brix_cms_srv_ctx_t *ctx)
ngx_int_t brix_cms_srv_send_ping (brix_cms_srv_ctx_t *ctx)
ngx_int_t brix_cms_srv_send_xauth (brix_cms_srv_ctx_t *ctx, const u_char *parms, size_t len)
ngx_int_t brix_cms_srv_send_pong (brix_cms_srv_ctx_t *ctx)
ngx_int_t brix_cms_srv_send_disc (brix_cms_srv_ctx_t *ctx)
ngx_int_t brix_cms_srv_send_status (brix_cms_srv_ctx_t *ctx, u_char modifier)
ngx_int_t brix_cms_srv_send_data (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t len)
ngx_int_t brix_cms_srv_check_peer (ngx_connection_t *c, ngx_stream_brix_cms_srv_conf_t *conf)
ngx_int_t brix_cms_srv_verify_xauth (brix_cms_srv_ctx_t *ctx, const u_char *payload, size_t payload_len)
Variables
ngx_module_t ngx_stream_brix_cms_srv_module
Enumeration Type Documentation
brix_cms_auth_state_t
enum brix_cms_auth_state_t
Enumerator
CMS_AUTH_NONE
CMS_AUTH_REQUESTED
CMS_AUTH_CHALLENGED
CMS_AUTH_DONE
Definition at line 28 of file server.h.
Function Documentation
brix_cms_srv_check_peer()
ngx_int_t brix_cms_srv_check_peer (ngx_connection_t * c, ngx_stream_brix_cms_srv_conf_t * conf)
Definition at line 31 of file server_auth.c.
References c.
Referenced by brix_cms_srv_handler().
brix_cms_srv_close()
void brix_cms_srv_close (brix_cms_srv_ctx_t * ctx)
Definition at line 116 of file server_recv_lifecycle.c.
References brix_cms_srv_conn_dec(), brix_cms_srv_ip_dec(), BRIX_DIAG, brix_sess_end(), brix_srv_blacklist(), c, brix_cms_srv_ctx_t::c, cms_srv_end_reason(), brix_cms_srv_ctx_t::counted, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, NGX_BRIX_CMS_SRV_DROP_BLACKLIST_MS, brix_cms_srv_ctx_t::ping_timer, brix_cms_srv_ctx_t::port, and brix_cms_srv_ctx_t::sess.
Referenced by brix_cms_srv_ping_timer(), brix_cms_srv_write(), and cms_srv_fail_close().
brix_cms_srv_conn_count()
ngx_uint_t brix_cms_srv_conn_count (void)
Definition at line 18 of file server_handler.c.
References brix_cms_srv_conns.
Referenced by brix_cms_srv_handler().
brix_cms_srv_conn_dec()
void brix_cms_srv_conn_dec (void)
Definition at line 30 of file server_handler.c.
References brix_cms_srv_conns.
Referenced by brix_cms_srv_close().
brix_cms_srv_conn_inc()
void brix_cms_srv_conn_inc (void)
Definition at line 24 of file server_handler.c.
References brix_cms_srv_conns.
Referenced by brix_cms_srv_handler().
brix_cms_srv_handler()
void brix_cms_srv_handler (ngx_stream_session_t * s)
Definition at line 140 of file server_handler.c.
References brix_cms_srv_ctx_t::auth_state, brix_apply_tcp_deadpeer_opts(), brix_cms_srv_check_peer(), brix_cms_srv_conn_count(), brix_cms_srv_conn_inc(), brix_cms_srv_ip_count(), brix_cms_srv_ip_inc(), brix_cms_srv_read(), brix_cms_srv_write(), BRIX_DIAG, BRIX_RESIL_METRIC_INC, BRIX_SESS_AM_HOST, brix_sess_begin(), BRIX_SESS_DIR_IN, BRIX_SESS_PROTO_CMS, c, brix_cms_srv_ctx_t::c, CMS_AUTH_NONE, CMS_AUTH_REQUESTED, brix_cms_srv_ctx_t::conf, brix_cms_srv_ctx_t::counted, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::idle_timeout_ms, brix_cms_srv_ctx_t::in_need, brix_cms_srv_ctx_t::interval_ms, brix_cms_srv_ctx_t::login_timeout_ms, NGX_BRIX_CMS_HDR_LEN, ngx_pcalloc(), ngx_stream_brix_cms_srv_module, ngx_stream_brix_module, brix_cms_srv_ctx_t::ping_timer, s, and brix_cms_srv_ctx_t::sess.
Referenced by brix_cms_srv_set_enable().
brix_cms_srv_ip_count()
ngx_uint_t brix_cms_srv_ip_count (const char * ip)
Definition at line 94 of file server_handler.c.
References brix_cms_ip_find(), and brix_cms_ip_slot_t::count.
Referenced by brix_cms_srv_handler().
brix_cms_srv_ip_dec()
void brix_cms_srv_ip_dec (const char * ip)
Definition at line 110 of file server_handler.c.
References brix_cms_ip_find(), brix_cms_ip_slot_t::count, and brix_cms_ip_slot_t::ip.
Referenced by brix_cms_srv_close().
brix_cms_srv_ip_inc()
void brix_cms_srv_ip_inc (const char * ip)
Definition at line 101 of file server_handler.c.
References brix_cms_ip_find(), and brix_cms_ip_slot_t::count.
Referenced by brix_cms_srv_handler().
brix_cms_srv_read()
void brix_cms_srv_read (ngx_event_t * ev)
Definition at line 181 of file server_recv.c.
References BRIX_SESS_END_ERROR, c, cms_srv_dispatch_frame(), cms_srv_fail_close(), cms_srv_read_accumulate(), cms_srv_read_timeout(), cms_srv_read_yield(), and NGX_BRIX_CMS_MAX_FRAMES_PER_WAKEUP.
Referenced by brix_cms_srv_handler().
brix_cms_srv_send_data()
ngx_int_t brix_cms_srv_send_data (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t len)
Definition at line 72 of file server_send.c.
References brix_cms_srv_send_frame(), and CMS_RSP_DATA.
Referenced by cms_srv_frame_statfs().
brix_cms_srv_send_disc()
ngx_int_t brix_cms_srv_send_disc (brix_cms_srv_ctx_t * ctx)
Definition at line 54 of file server_send.c.
References brix_cms_srv_send_frame(), and CMS_RR_DISC.
Referenced by cms_srv_frame_disc().
brix_cms_srv_send_ping()
ngx_int_t brix_cms_srv_send_ping (brix_cms_srv_ctx_t * ctx)
Definition at line 27 of file server_send.c.
References brix_cms_srv_send_frame(), and CMS_RR_PING.
Referenced by brix_cms_srv_ping_timer().
brix_cms_srv_send_pong()
ngx_int_t brix_cms_srv_send_pong (brix_cms_srv_ctx_t * ctx)
Definition at line 46 of file server_send.c.
References brix_cms_srv_send_frame(), and CMS_RR_PONG.
Referenced by cms_srv_frame_ping().
brix_cms_srv_send_status()
ngx_int_t brix_cms_srv_send_status (brix_cms_srv_ctx_t * ctx, u_char modifier)
Definition at line 63 of file server_send.c.
References brix_cms_srv_send_frame(), and CMS_RR_STATUS.
Referenced by cms_srv_frame_update().
brix_cms_srv_send_xauth()
ngx_int_t brix_cms_srv_send_xauth (brix_cms_srv_ctx_t * ctx, const u_char * parms, size_t len)
Definition at line 37 of file server_send.c.
References brix_cms_srv_send_frame(), and CMS_RR_XAUTH.
Referenced by cms_srv_frame_login().
brix_cms_srv_verify_xauth()
ngx_int_t brix_cms_srv_verify_xauth (brix_cms_srv_ctx_t * ctx, const u_char * payload, size_t payload_len)
Definition at line 62 of file server_auth.c.
References brix_sanitize_log_string(), brix_sss_verify_blob(), brix_cms_srv_ctx_t::c, CMS_SSS_LIFETIME, brix_cms_srv_ctx_t::conf, brix_cms_srv_ctx_t::host, key, and name.
Referenced by cms_srv_frame_xauth().
brix_cms_srv_write()
void brix_cms_srv_write (ngx_event_t * ev)
Definition at line 35 of file server_recv.c.
References brix_cms_srv_close(), BRIX_SESS_END_TIMEOUT, c, and cms_srv_set_end_hint().
Referenced by brix_cms_srv_handler().
Variable Documentation
ngx_stream_brix_cms_srv_module
ngx_module_t ngx_stream_brix_cms_srv_module extern
Definition at line 279 of file server_module.c.
Referenced by brix_cms_srv_handler().