nginx-xrootd: src/core/config/server_conf_merge_security.c File Reference
server_conf_merge_security.c File Reference
#include "config.h"
#include "server_conf_internal.h"
#include "auth/crypto/store_policy.h"
#include "core/compat/af_policy.h"
#include "fs/cache/verify.h"
#include "net/ratelimit/ratelimit.h"
Functions
static char * brix_merge_srv_gsi_acc (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
static char * brix_merge_srv_x509 (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
static char * brix_merge_srv_tokens (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
static void brix_merge_srv_authtail (ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
char * brix_merge_srv_security (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
static void brix_merge_srv_zip_stage (ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
static void brix_merge_srv_cache_origin (ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
static void brix_merge_srv_iouring_advertise (ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
char * brix_merge_srv_storage (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
Function Documentation
brix_merge_srv_authtail()
static void brix_merge_srv_authtail (ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 185 of file server_conf_merge_security.c.
References brix_csi_conf_merge().
Referenced by brix_merge_srv_security().
brix_merge_srv_cache_origin()
static void brix_merge_srv_cache_origin (ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 316 of file server_conf_merge_security.c.
References BRIX_AF_AUTO, and BRIX_READV_SEGSIZE.
Referenced by brix_merge_srv_storage().
brix_merge_srv_gsi_acc()
static char * brix_merge_srv_gsi_acc (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 40 of file server_conf_merge_security.c.
References BRIX_AUTH_GSI, BRIX_AUTH_NONE, BRIX_AUTH_TOKEN, BRIX_AUTHDB_AUDIT_NONE, BRIX_AUTHDB_FORMAT_NATIVE, BRIX_GSI_KEYPOOL_SEED_DEFAULT, BRIX_GSI_KEYPOOL_SIZE_DEFAULT, and BRIX_GSI_SDH_OFF.
Referenced by brix_merge_srv_security().
brix_merge_srv_iouring_advertise()
static void brix_merge_srv_iouring_advertise (ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 362 of file server_conf_merge_security.c.
References BRIX_CACHE_VERIFY_BESTEFFORT, BRIX_IO_URING_OFF, BRIX_IO_URING_QUEUE_DEPTH, and BRIX_SECCOMP_OFF.
Referenced by brix_merge_srv_storage().
brix_merge_srv_security()
char * brix_merge_srv_security (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev)
Definition at line 221 of file server_conf_merge_security.c.
References brix_merge_srv_authtail(), brix_merge_srv_gsi_acc(), brix_merge_srv_tokens(), brix_merge_srv_x509(), and ngx_http_brix_shared_merge().
Referenced by ngx_stream_brix_merge_srv_conf().
brix_merge_srv_storage()
char * brix_merge_srv_storage (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev)
Definition at line 439 of file server_conf_merge_security.c.
References brix_merge_srv_cache_origin(), brix_merge_srv_iouring_advertise(), and brix_merge_srv_zip_stage().
Referenced by ngx_stream_brix_merge_srv_conf().
brix_merge_srv_tokens()
static char * brix_merge_srv_tokens (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 131 of file server_conf_merge_security.c.
References brix_rl_zone_get(), and BRIX_TOKEN_CLOCK_SKEW_SECS.
Referenced by brix_merge_srv_security().
brix_merge_srv_x509()
static char * brix_merge_srv_x509 (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 96 of file server_conf_merge_security.c.
References BRIX_CRL_MODE_TRY, brix_frm_conf_merge(), and BRIX_SP_MODE_ON.
Referenced by brix_merge_srv_security().
brix_merge_srv_zip_stage()
static void brix_merge_srv_zip_stage (ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 264 of file server_conf_merge_security.c.
Referenced by brix_merge_srv_storage().