nginx-xrootd: src/net/cms/server_handler.c File Reference
server_handler.c File Reference
#include "server.h"
#include "protocols/root/connection/netopt.h"
#include "core/compat/log_diag.h"
#include "observability/metrics/metrics_macros.h"
#include "observability/sesslog/sesslog_ngx.h"
Data Structures
struct brix_cms_ip_slot_t
Macros
#define BRIX_CMS_IP_SLOTS 4096
Functions
ngx_uint_t brix_cms_srv_conn_count (void)
void brix_cms_srv_conn_inc (void)
void brix_cms_srv_conn_dec (void)
static ngx_uint_t brix_cms_ip_hash (const char *ip)
static brix_cms_ip_slot_t * brix_cms_ip_find (const char *ip, int create)
ngx_uint_t brix_cms_srv_ip_count (const char *ip)
void brix_cms_srv_ip_inc (const char *ip)
void brix_cms_srv_ip_dec (const char *ip)
void brix_cms_srv_node_add (brix_cms_srv_ctx_t *ctx)
void brix_cms_srv_node_del (brix_cms_srv_ctx_t *ctx)
ngx_uint_t brix_cms_srv_node_count (void)
brix_cms_srv_ctx_t * brix_cms_srv_node_at (ngx_uint_t i)
uint32_t brix_cms_srv_next_streamid (void)
void brix_cms_srv_handler (ngx_stream_session_t *s)
Variables
static ngx_uint_t brix_cms_srv_conns
static brix_cms_ip_slot_t brix_cms_ip_table [4096]
static brix_cms_srv_ctx_t * brix_cms_srv_nodes [128]
static ngx_uint_t brix_cms_srv_nnodes
static uint32_t brix_cms_srv_streamid_seq
Macro Definition Documentation
BRIX_CMS_IP_SLOTS
#define BRIX_CMS_IP_SLOTS 4096
Definition at line 45 of file server_handler.c.
Function Documentation
brix_cms_ip_find()
static brix_cms_ip_slot_t * brix_cms_ip_find (const char * ip, int create) static
Definition at line 69 of file server_handler.c.
References brix_cms_ip_hash(), BRIX_CMS_IP_SLOTS, brix_cms_ip_table, brix_cms_ip_slot_t::count, and brix_cms_ip_slot_t::ip.
Referenced by brix_cms_srv_ip_count(), brix_cms_srv_ip_dec(), and brix_cms_srv_ip_inc().
brix_cms_ip_hash()
static ngx_uint_t brix_cms_ip_hash (const char * ip) static
Definition at line 55 of file server_handler.c.
References BRIX_CMS_IP_SLOTS.
Referenced by brix_cms_ip_find().
brix_cms_srv_conn_count()
ngx_uint_t brix_cms_srv_conn_count (void)
Definition at line 18 of file server_handler.c.
References brix_cms_srv_conns.
Referenced by brix_cms_srv_handler().
brix_cms_srv_conn_dec()
void brix_cms_srv_conn_dec (void)
Definition at line 30 of file server_handler.c.
References brix_cms_srv_conns.
Referenced by brix_cms_srv_close().
brix_cms_srv_conn_inc()
void brix_cms_srv_conn_inc (void)
Definition at line 24 of file server_handler.c.
References brix_cms_srv_conns.
Referenced by brix_cms_srv_handler().
brix_cms_srv_handler()
void brix_cms_srv_handler (ngx_stream_session_t * s)
Definition at line 201 of file server_handler.c.
References brix_cms_srv_ctx_t::auth_state, brix_apply_tcp_deadpeer_opts(), brix_cms_srv_check_peer(), brix_cms_srv_conn_count(), brix_cms_srv_conn_inc(), brix_cms_srv_ip_count(), brix_cms_srv_ip_inc(), brix_cms_srv_read(), brix_cms_srv_write(), BRIX_DIAG, BRIX_RESIL_METRIC_INC, BRIX_SESS_AM_HOST, brix_sess_begin(), BRIX_SESS_DIR_IN, BRIX_SESS_PROTO_CMS, c, brix_cms_srv_ctx_t::c, CMS_AUTH_NONE, CMS_AUTH_REQUESTED, brix_cms_srv_ctx_t::conf, brix_cms_srv_ctx_t::counted, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::idle_timeout_ms, brix_cms_srv_ctx_t::in_need, brix_cms_srv_ctx_t::interval_ms, brix_cms_srv_ctx_t::login_timeout_ms, NGX_BRIX_CMS_HDR_LEN, ngx_pcalloc(), ngx_stream_brix_cms_srv_module, ngx_stream_brix_module, brix_cms_srv_ctx_t::ping_timer, s, and brix_cms_srv_ctx_t::sess.
Referenced by brix_cms_srv_set_enable().
brix_cms_srv_ip_count()
ngx_uint_t brix_cms_srv_ip_count (const char * ip)
Definition at line 94 of file server_handler.c.
References brix_cms_ip_find(), and brix_cms_ip_slot_t::count.
Referenced by brix_cms_srv_handler().
brix_cms_srv_ip_dec()
void brix_cms_srv_ip_dec (const char * ip)
Definition at line 110 of file server_handler.c.
References brix_cms_ip_find(), brix_cms_ip_slot_t::count, and brix_cms_ip_slot_t::ip.
Referenced by brix_cms_srv_close().
brix_cms_srv_ip_inc()
void brix_cms_srv_ip_inc (const char * ip)
Definition at line 101 of file server_handler.c.
References brix_cms_ip_find(), and brix_cms_ip_slot_t::count.
Referenced by brix_cms_srv_handler().
brix_cms_srv_next_streamid()
uint32_t brix_cms_srv_next_streamid (void)
Definition at line 177 of file server_handler.c.
References brix_cms_srv_streamid_seq.
Referenced by brix_cms_fanout_mutation(), and locate_try_dynamic().
brix_cms_srv_node_add()
void brix_cms_srv_node_add (brix_cms_srv_ctx_t * ctx)
Definition at line 136 of file server_handler.c.
References brix_cms_srv_nnodes, brix_cms_srv_nodes, BRIX_SRV_REGISTRY_SLOTS, and brix_cms_srv_ctx_t::in_node_list.
Referenced by cms_srv_complete_login().
brix_cms_srv_node_at()
brix_cms_srv_ctx_t * brix_cms_srv_node_at (ngx_uint_t i)
Definition at line 171 of file server_handler.c.
References brix_cms_srv_nnodes, and brix_cms_srv_nodes.
Referenced by brix_cms_fanout_mutation(), and locate_try_dynamic().
brix_cms_srv_node_count()
ngx_uint_t brix_cms_srv_node_count (void)
Definition at line 165 of file server_handler.c.
References brix_cms_srv_nnodes.
Referenced by brix_cms_fanout_mutation(), and locate_try_dynamic().
brix_cms_srv_node_del()
void brix_cms_srv_node_del (brix_cms_srv_ctx_t * ctx)
Definition at line 148 of file server_handler.c.
References brix_cms_srv_nnodes, brix_cms_srv_nodes, and brix_cms_srv_ctx_t::in_node_list.
Referenced by brix_cms_srv_close().
Variable Documentation
brix_cms_ip_table
brix_cms_ip_slot_t brix_cms_ip_table[4096] static
Definition at line 52 of file server_handler.c.
Referenced by brix_cms_ip_find().
brix_cms_srv_conns
ngx_uint_t brix_cms_srv_conns static
Definition at line 15 of file server_handler.c.
Referenced by brix_cms_srv_conn_count(), brix_cms_srv_conn_dec(), and brix_cms_srv_conn_inc().
brix_cms_srv_nnodes
ngx_uint_t brix_cms_srv_nnodes static
Definition at line 132 of file server_handler.c.
Referenced by brix_cms_srv_node_add(), brix_cms_srv_node_at(), brix_cms_srv_node_count(), and brix_cms_srv_node_del().
brix_cms_srv_nodes
brix_cms_srv_ctx_t* brix_cms_srv_nodes[128] static
Definition at line 131 of file server_handler.c.
Referenced by brix_cms_srv_node_add(), brix_cms_srv_node_at(), and brix_cms_srv_node_del().
brix_cms_srv_streamid_seq
uint32_t brix_cms_srv_streamid_seq static
Definition at line 133 of file server_handler.c.
Referenced by brix_cms_srv_next_streamid().