nginx-xrootd: src/core/config/server_conf_internal.h File Reference
server_conf_internal.h File Reference
Functions
char * brix_merge_srv_security (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
char * brix_merge_srv_storage (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
void brix_merge_srv_tpc (ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
char * brix_merge_srv_cluster (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
char * brix_merge_srv_proxy_net (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
Function Documentation
brix_merge_srv_cluster()
char * brix_merge_srv_cluster (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev)
Definition at line 368 of file server_conf_merge_cluster.c.
References BRIX_DEFAULT_PORT, brix_merge_srv_cluster_addrs(), brix_merge_srv_cluster_sizing(), brix_merge_srv_cms(), brix_merge_srv_healthcheck(), brix_merge_srv_mirror(), and brix_merge_srv_rules().
Referenced by ngx_stream_brix_merge_srv_conf().
brix_merge_srv_proxy_net()
char * brix_merge_srv_proxy_net (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev)
Definition at line 184 of file server_conf_merge_proxy_net.c.
References brix_merge_srv_net_fault(), brix_merge_srv_proxy(), and brix_merge_srv_writethrough().
Referenced by ngx_stream_brix_merge_srv_conf().
brix_merge_srv_security()
char * brix_merge_srv_security (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev)
Definition at line 221 of file server_conf_merge_security.c.
References brix_merge_srv_authtail(), brix_merge_srv_gsi_acc(), brix_merge_srv_tokens(), brix_merge_srv_x509(), and ngx_http_brix_shared_merge().
Referenced by ngx_stream_brix_merge_srv_conf().
brix_merge_srv_storage()
char * brix_merge_srv_storage (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev)
Definition at line 472 of file server_conf_merge_security.c.
References brix_merge_srv_cache_origin(), brix_merge_srv_iouring_advertise(), and brix_merge_srv_zip_stage().
Referenced by ngx_stream_brix_merge_srv_conf().
brix_merge_srv_tpc()
void brix_merge_srv_tpc (ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev)
Definition at line 37 of file server_conf_merge_cluster.c.
References BRIX_CNS_COLLECT, BRIX_CNS_OFF, brix_cns_set_collect(), BRIX_TPC_KEY_TTL_MS, and brix_tpc_registry_set_max_age().
Referenced by ngx_stream_brix_merge_srv_conf().