nginx-xrootd: src/core/config/server_conf.c File Reference
server_conf.c File Reference
#include "config.h"
#include "auth/crypto/store_policy.h"
#include "core/compat/af_policy.h"
#include "fs/cache/verify.h"
#include "net/ratelimit/ratelimit.h"
#include "net/cms/cns.h"
#include "tpc/engine/key_registry.h"
#include "tpc/common/registry.h"
#include "protocols/root/session/registry.h"
#include "net/manager/health_check.h"
#include "net/manager/registry.h"
Functions
void * ngx_stream_brix_create_srv_conf (ngx_conf_t *cf)
static char * brix_merge_srv_security (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
static char * brix_merge_srv_storage (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
static void brix_merge_srv_tpc (ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
static char * brix_merge_srv_cluster (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
static char * brix_merge_srv_proxy_net (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
char * ngx_stream_brix_merge_srv_conf (ngx_conf_t *cf, void *parent, void *child)
char * ngx_stream_brix_enable (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Function Documentation
brix_merge_srv_cluster()
static char * brix_merge_srv_cluster (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 575 of file server_conf.c.
References brix_cms_conf_t::addr, brix_hc_conf_t::blacklist_ms, BRIX_DEFAULT_PORT, BRIX_HC_TYPE_PING, brix_merge_arrays(), BRIX_MIRROR_M_DEFAULT, BRIX_MIRROR_OP_ALL, brix_node_caps_conf_merge(), BRIX_PIPELINE_DEPTH_DEFAULT, BRIX_PIPELINE_DEPTH_MAX, BRIX_PIPELINE_DEPTH_MIN, BRIX_SESSION_REGISTRY_SLOTS, ngx_stream_brix_srv_conf_t::caps, ngx_stream_brix_srv_conf_t::ckscan_max_depth, ngx_stream_brix_srv_conf_t::ckscan_max_files, ngx_stream_brix_srv_conf_t::cms, brix_cms_conf_t::connect_retry, brix_hc_conf_t::enabled, brix_mirror_conf_t::enabled, ngx_stream_brix_srv_conf_t::group_rules, ngx_stream_brix_srv_conf_t::hc, ngx_stream_brix_srv_conf_t::http_handoff_addr, ngx_stream_brix_srv_conf_t::http_handoff_name, brix_cms_conf_t::initial_delay, brix_cms_conf_t::interval, brix_hc_conf_t::interval_ms, ngx_stream_brix_srv_conf_t::listen_port, brix_cms_conf_t::locate_timeout, brix_mirror_conf_t::log_diverge, brix_cms_conf_t::manager, ngx_stream_brix_srv_conf_t::manager_map, ngx_stream_brix_srv_conf_t::manager_mode, brix_mirror_conf_t::method_mask, ngx_stream_brix_srv_conf_t::mirror, brix_mirror_conf_t::mirror_writes, brix_mirror_conf_t::opcode_exclude_mask, brix_mirror_conf_t::opcode_mask, brix_cms_conf_t::paths, ngx_stream_brix_srv_conf_t::pipeline_depth, brix_cms_conf_t::read_timeout, ngx_stream_brix_srv_conf_t::redir_cache_slots, ngx_stream_brix_srv_conf_t::registry_slots, ngx_stream_brix_srv_conf_t::relay_addr, ngx_stream_brix_srv_conf_t::relay_name, brix_mirror_conf_t::sample_pct, brix_cms_conf_t::send_timeout, ngx_stream_brix_srv_conf_t::session_slots, brix_mirror_conf_t::strip_auth, brix_mirror_conf_t::targets, brix_cms_conf_t::tcp_keepalive, brix_cms_conf_t::tcp_user_timeout, brix_hc_conf_t::threshold, brix_hc_conf_t::timeout_ms, brix_mirror_conf_t::timeout_ms, brix_hc_conf_t::type, ngx_stream_brix_srv_conf_t::upload_resume, ngx_stream_brix_srv_conf_t::upload_stage_dir, ngx_stream_brix_srv_conf_t::upstream_addr, ngx_stream_brix_srv_conf_t::upstream_host, ngx_stream_brix_srv_conf_t::upstream_port, and ngx_stream_brix_srv_conf_t::vo_rules.
Referenced by ngx_stream_brix_merge_srv_conf().
brix_merge_srv_proxy_net()
static char * brix_merge_srv_proxy_net (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 744 of file server_conf.c.
References brix_wt_conf_t::allow_prefixes, brix_wt_decision_cfg_t::allow_prefixes, brix_proxy_conf_t::audit_log, brix_proxy_conf_t::auth, brix_merge_arrays(), BRIX_MERGE_ENUM, BRIX_MERGE_HOSTPORT, BRIX_MERGE_PTR, brix_ocsp_conf_merge(), BRIX_PROXY_AUTH_ANONYMOUS, BRIX_PROXY_LOGIN_ANONYMOUS, brix_srv_set_stale_after(), brix_wt_default_decide(), BRIX_WT_MODE_SYNC, BRIX_WT_MODE_UNSET, ngx_stream_brix_srv_conf_t::cache_max_file_size, ngx_stream_brix_srv_conf_t::cache_origin_host, ngx_stream_brix_srv_conf_t::cache_origin_port, brix_proxy_conf_t::connect_timeout, brix_wt_conf_t::decision, brix_wt_conf_t::deny_prefixes, brix_wt_decision_cfg_t::deny_prefixes, brix_wt_conf_t::enable, brix_proxy_conf_t::enable, brix_wt_decision_cfg_t::fn, ngx_stream_brix_srv_conf_t::handshake_timeout, brix_proxy_conf_t::host, ngx_stream_brix_srv_conf_t::include_regex, brix_wt_decision_cfg_t::include_regex, brix_wt_decision_cfg_t::include_regex_set, brix_proxy_conf_t::keepalive_interval, brix_proxy_conf_t::login_user, brix_proxy_conf_t::login_user_name, ngx_stream_brix_srv_conf_t::manager_stale_after, ngx_stream_brix_srv_conf_t::max_connections, brix_wt_decision_cfg_t::max_write_through_bytes, ngx_stream_brix_srv_conf_t::ocsp, brix_wt_conf_t::origin_host, brix_wt_conf_t::origin_port, brix_proxy_conf_t::path_add, brix_proxy_conf_t::path_strip, brix_proxy_conf_t::port, ngx_stream_brix_srv_conf_t::proxy, brix_cache_include_regex_conf_t::re, brix_proxy_conf_t::read_timeout, ngx_stream_brix_srv_conf_t::read_timeout, brix_proxy_conf_t::reconnect_attempts, ngx_stream_brix_srv_conf_t::relay_guard_enable, ngx_stream_brix_srv_conf_t::rl_rules, ngx_stream_brix_srv_conf_t::send_timeout, brix_cache_include_regex_conf_t::set, ngx_stream_brix_srv_conf_t::tcp_congestion, ngx_stream_brix_srv_conf_t::tcp_keepalive, ngx_stream_brix_srv_conf_t::tcp_user_timeout, brix_proxy_conf_t::upstream_tls, ngx_stream_brix_srv_conf_t::upstream_tls, brix_proxy_conf_t::upstream_tls_ca, ngx_stream_brix_srv_conf_t::upstream_tls_ca, brix_proxy_conf_t::upstream_tls_name, ngx_stream_brix_srv_conf_t::upstream_tls_name, ngx_stream_brix_srv_conf_t::upstream_token_file, brix_wt_decision_cfg_t::user_data, brix_proxy_conf_t::write_timeout, and ngx_stream_brix_srv_conf_t::wt.
Referenced by ngx_stream_brix_merge_srv_conf().
brix_merge_srv_security()
static char * brix_merge_srv_security (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 235 of file server_conf.c.
References ngx_stream_brix_srv_conf_t::acc, ngx_stream_brix_srv_conf_t::access_log, brix_acc_conf_t::audit, ngx_stream_brix_srv_conf_t::auth, ngx_stream_brix_srv_conf_t::auth_cache, ngx_stream_brix_srv_conf_t::authdb, BRIX_AUTH_GSI, BRIX_AUTH_NONE, BRIX_AUTH_TOKEN, BRIX_AUTHDB_AUDIT_NONE, BRIX_AUTHDB_FORMAT_NATIVE, BRIX_CRL_MODE_TRY, brix_csi_conf_merge(), brix_frm_conf_merge(), BRIX_GSI_KEYPOOL_SEED_DEFAULT, BRIX_GSI_KEYPOOL_SIZE_DEFAULT, BRIX_GSI_SDH_OFF, brix_rl_zone_get(), BRIX_SP_MODE_ON, BRIX_TOKEN_CLOCK_SKEW_SECS, ngx_stream_brix_srv_conf_t::certificate, ngx_stream_brix_srv_conf_t::certificate_key, ngx_stream_brix_srv_conf_t::common, ngx_stream_brix_srv_conf_t::crl, ngx_stream_brix_srv_conf_t::crl_mode, ngx_stream_brix_srv_conf_t::crl_reload, ngx_stream_brix_srv_conf_t::csi, brix_acc_conf_t::encoding, brix_acc_conf_t::format, ngx_stream_brix_srv_conf_t::frm, brix_acc_conf_t::gidlifetime, brix_acc_conf_t::gidretran, ngx_stream_brix_srv_conf_t::gsi_ciphers, ngx_stream_brix_srv_conf_t::gsi_keypool_seed, ngx_stream_brix_srv_conf_t::gsi_keypool_size, ngx_stream_brix_srv_conf_t::gsi_max_inflight, ngx_stream_brix_srv_conf_t::gsi_signed_dh, ngx_stream_brix_srv_conf_t::host_allow, brix_krb5_conf_t::ip_check, brix_krb5_conf_t::keytab, ngx_stream_brix_srv_conf_t::krb5, brix_auth_cache_conf_t::kv, brix_rate_limit_conf_t::kv, brix_throttle_conf_t::max_active_conn, brix_throttle_conf_t::max_open_files, ngx_http_brix_shared_merge(), brix_acc_conf_t::nisdomain, brix_acc_conf_t::pgo, ngx_stream_brix_srv_conf_t::prepare_command, brix_krb5_conf_t::principal, ngx_stream_brix_srv_conf_t::pwd_file, ngx_stream_brix_srv_conf_t::rate_limit, brix_acc_conf_t::refresh, brix_acc_conf_t::resolve_hosts, ngx_stream_brix_srv_conf_t::security_level, ngx_stream_brix_srv_conf_t::session_log, ngx_stream_brix_srv_conf_t::signing_policy_mode, brix_acc_conf_t::spacechar, ngx_stream_brix_srv_conf_t::sss_keytab, ngx_stream_brix_srv_conf_t::sss_lifetime, ngx_stream_brix_srv_conf_t::throttle, ngx_stream_brix_srv_conf_t::tls, ngx_stream_brix_srv_conf_t::tls_ktls, ngx_stream_brix_srv_conf_t::token_audience, ngx_stream_brix_srv_conf_t::token_cache_kv, ngx_stream_brix_srv_conf_t::token_clock_skew, ngx_stream_brix_srv_conf_t::token_config, ngx_stream_brix_srv_conf_t::token_issuer, ngx_stream_brix_srv_conf_t::token_jwks, ngx_stream_brix_srv_conf_t::token_jwks_refresh_interval, ngx_stream_brix_srv_conf_t::token_macaroon_secret, ngx_stream_brix_srv_conf_t::token_macaroon_secret_old, ngx_stream_brix_srv_conf_t::token_registry, ngx_stream_brix_srv_conf_t::trusted_ca, ngx_stream_brix_srv_conf_t::unix_trust_remote, ngx_stream_brix_srv_conf_t::voms_cert_dir, ngx_stream_brix_srv_conf_t::vomsdir, brix_throttle_conf_t::zone, and brix_throttle_conf_t::zone_name.
Referenced by ngx_stream_brix_merge_srv_conf().
brix_merge_srv_storage()
static char * brix_merge_srv_storage (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 382 of file server_conf.c.
References ngx_stream_brix_srv_conf_t::advertise, BRIX_AF_AUTO, BRIX_CACHE_VERIFY_BESTEFFORT, BRIX_IO_URING_AUTO, BRIX_IO_URING_QUEUE_DEPTH, BRIX_READV_SEGSIZE, ngx_stream_brix_srv_conf_t::cache, ngx_stream_brix_srv_conf_t::cache_allow_prefixes, ngx_stream_brix_srv_conf_t::cache_deny_prefixes, ngx_stream_brix_srv_conf_t::cache_dirty_max_age, ngx_stream_brix_srv_conf_t::cache_eviction_threshold, ngx_stream_brix_srv_conf_t::cache_lock_timeout, ngx_stream_brix_srv_conf_t::cache_max_file_size, ngx_stream_brix_srv_conf_t::cache_origin, ngx_stream_brix_srv_conf_t::cache_origin_family, ngx_stream_brix_srv_conf_t::cache_origin_tls, ngx_stream_brix_srv_conf_t::cache_root, ngx_http_brix_shared_conf_t::cache_slice_size, ngx_stream_brix_srv_conf_t::cache_state_root, ngx_stream_brix_srv_conf_t::cache_verify, ngx_stream_brix_srv_conf_t::cache_verify_digest, ngx_stream_brix_srv_conf_t::cache_wt_stage_backend, ngx_stream_brix_srv_conf_t::cache_wt_stage_block_size, ngx_stream_brix_srv_conf_t::cache_wt_stage_high_watermark, ngx_stream_brix_srv_conf_t::cache_wt_stage_low_watermark, ngx_stream_brix_srv_conf_t::cache_wt_stage_root, ngx_stream_brix_srv_conf_t::common, brix_cache_advertise_conf_t::data_url, brix_cache_advertise_conf_t::enable, brix_cache_reaper_conf_t::high_watermark, ngx_stream_brix_srv_conf_t::include_regex, brix_cache_advertise_conf_t::interval, ngx_stream_brix_srv_conf_t::io_uring, ngx_stream_brix_srv_conf_t::io_uring_admin, ngx_stream_brix_srv_conf_t::io_uring_panic_file, ngx_stream_brix_srv_conf_t::io_uring_queue_depth, ngx_stream_brix_srv_conf_t::io_uring_restrict, brix_cache_advertise_conf_t::issuer_url, brix_cache_advertise_conf_t::key, brix_cache_reaper_conf_t::low_watermark, ngx_stream_brix_srv_conf_t::memory_budget, brix_cache_advertise_conf_t::ns, brix_cache_include_regex_conf_t::re, ngx_stream_brix_srv_conf_t::read_compress, ngx_stream_brix_srv_conf_t::readv_segment_size, brix_cache_reaper_conf_t::reap_interval, ngx_stream_brix_srv_conf_t::reaper, brix_cache_include_regex_conf_t::set, brix_cache_advertise_conf_t::sitename, brix_cache_include_regex_conf_t::str, brix_cache_advertise_conf_t::web_url, ngx_stream_brix_srv_conf_t::write_compress, ngx_stream_brix_srv_conf_t::zip_access, ngx_stream_brix_srv_conf_t::zip_cd_max_bytes, ngx_stream_brix_srv_conf_t::zip_force_scratch, ngx_stream_brix_srv_conf_t::zip_stage_dir, and ngx_stream_brix_srv_conf_t::zip_stage_max_bytes.
Referenced by ngx_stream_brix_merge_srv_conf().
brix_merge_srv_tpc()
static void brix_merge_srv_tpc (ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 522 of file server_conf.c.
References BRIX_CNS_COLLECT, BRIX_CNS_OFF, brix_cns_set_collect(), BRIX_TPC_KEY_TTL_MS, brix_tpc_registry_set_max_age(), ngx_stream_brix_srv_conf_t::cns_mode, ngx_stream_brix_srv_conf_t::ssi_cta_enable, ngx_stream_brix_srv_conf_t::ssi_cta_executor, ngx_stream_brix_srv_conf_t::ssi_cta_journal, ngx_stream_brix_srv_conf_t::ssi_enable, ngx_stream_brix_srv_conf_t::ssi_max_inflight, ngx_stream_brix_srv_conf_t::ssi_request_max, ngx_stream_brix_srv_conf_t::ssi_response_max, ngx_stream_brix_srv_conf_t::tpc_allow_local, ngx_stream_brix_srv_conf_t::tpc_allow_private, ngx_stream_brix_srv_conf_t::tpc_delegate, ngx_stream_brix_srv_conf_t::tpc_key_ttl_ms, ngx_stream_brix_srv_conf_t::tpc_max_transfer_secs, ngx_stream_brix_srv_conf_t::tpc_outbound_bearer_file, ngx_stream_brix_srv_conf_t::tpc_outbound_client_id, ngx_stream_brix_srv_conf_t::tpc_outbound_client_secret, ngx_stream_brix_srv_conf_t::tpc_outbound_scope, ngx_stream_brix_srv_conf_t::tpc_outbound_tls, ngx_stream_brix_srv_conf_t::tpc_outbound_token_endpoint, and ngx_stream_brix_srv_conf_t::tpc_transfer_max_age.
Referenced by ngx_stream_brix_merge_srv_conf().
ngx_stream_brix_create_srv_conf()
void * ngx_stream_brix_create_srv_conf (ngx_conf_t * cf)
Definition at line 31 of file server_conf.c.
References ngx_stream_brix_srv_conf_t::acc, ngx_stream_brix_srv_conf_t::access_log_fd, ngx_stream_brix_srv_conf_t::advertise, ngx_stream_brix_srv_conf_t::auth, ngx_stream_brix_srv_conf_t::auth_cache, brix_acc_conf_init(), brix_cache_reaper_conf_init(), brix_cms_conf_init(), brix_csi_conf_init(), brix_frm_conf_init(), brix_hc_conf_init(), brix_krb5_conf_init(), brix_node_caps_conf_init(), brix_ocsp_conf_init(), brix_proxy_conf_init(), brix_wt_conf_init(), brix_rate_limit_conf_t::burst, ngx_stream_brix_srv_conf_t::cache, ngx_stream_brix_srv_conf_t::cache_allow_prefixes, ngx_stream_brix_srv_conf_t::cache_deny_prefixes, ngx_stream_brix_srv_conf_t::cache_dirty_max_age, ngx_stream_brix_srv_conf_t::cache_eviction_threshold, ngx_stream_brix_srv_conf_t::cache_lock_timeout, ngx_stream_brix_srv_conf_t::cache_max_file_size, ngx_stream_brix_srv_conf_t::cache_origin_family, ngx_stream_brix_srv_conf_t::cache_origin_tls, ngx_stream_brix_srv_conf_t::cache_rootfd, ngx_stream_brix_srv_conf_t::cache_state_rootfd, ngx_stream_brix_srv_conf_t::cache_verify, ngx_stream_brix_srv_conf_t::cache_wt_stage_block_size, ngx_stream_brix_srv_conf_t::cache_wt_stage_high_watermark, ngx_stream_brix_srv_conf_t::cache_wt_stage_low_watermark, ngx_stream_brix_srv_conf_t::cache_wt_stage_rootfd, ngx_stream_brix_srv_conf_t::cache_wt_store_rootfd, ngx_stream_brix_srv_conf_t::caps, ngx_stream_brix_srv_conf_t::ckscan_max_depth, ngx_stream_brix_srv_conf_t::ckscan_max_files, ngx_stream_brix_srv_conf_t::cms, ngx_stream_brix_srv_conf_t::cns_mode, ngx_stream_brix_srv_conf_t::common, ngx_stream_brix_srv_conf_t::crl_mode, ngx_stream_brix_srv_conf_t::crl_reload, ngx_stream_brix_srv_conf_t::csi, brix_cache_advertise_conf_t::enable, brix_mirror_conf_t::enabled, ngx_stream_brix_srv_conf_t::frm, ngx_stream_brix_srv_conf_t::group_rules, ngx_stream_brix_srv_conf_t::gsi_ca_hash, ngx_stream_brix_srv_conf_t::gsi_cert, ngx_stream_brix_srv_conf_t::gsi_cert_pem, ngx_stream_brix_srv_conf_t::gsi_cert_pem_len, ngx_stream_brix_srv_conf_t::gsi_key, ngx_stream_brix_srv_conf_t::gsi_keypool_seed, ngx_stream_brix_srv_conf_t::gsi_keypool_size, ngx_stream_brix_srv_conf_t::gsi_max_inflight, ngx_stream_brix_srv_conf_t::gsi_signed_dh, ngx_stream_brix_srv_conf_t::gsi_store, ngx_stream_brix_srv_conf_t::handshake_timeout, ngx_stream_brix_srv_conf_t::hc, ngx_stream_brix_srv_conf_t::host_allow, ngx_stream_brix_srv_conf_t::http_handoff_addr, ngx_stream_brix_srv_conf_t::include_regex, brix_cache_advertise_conf_t::interval, ngx_stream_brix_srv_conf_t::io_uring, ngx_stream_brix_srv_conf_t::io_uring_admin, ngx_stream_brix_srv_conf_t::io_uring_queue_depth, ngx_stream_brix_srv_conf_t::io_uring_restrict, ngx_stream_brix_srv_conf_t::jwks_mtime, ngx_stream_brix_srv_conf_t::jwks_timer, brix_rate_limit_conf_t::key_ip, ngx_stream_brix_srv_conf_t::krb5, brix_auth_cache_conf_t::kv, brix_rate_limit_conf_t::kv, ngx_stream_brix_srv_conf_t::listen_port, brix_mirror_conf_t::log_diverge, ngx_stream_brix_srv_conf_t::manager_mode, ngx_stream_brix_srv_conf_t::manager_stale_after, brix_throttle_conf_t::max_active_conn, ngx_stream_brix_srv_conf_t::max_connections, brix_throttle_conf_t::max_open_files, ngx_stream_brix_srv_conf_t::memory_budget, brix_mirror_conf_t::method_mask, ngx_stream_brix_srv_conf_t::metrics_slot, ngx_stream_brix_srv_conf_t::mirror, brix_mirror_conf_t::mirror_writes, ngx_http_brix_shared_init(), ngx_pcalloc(), ngx_stream_brix_srv_conf_t::ocsp, brix_mirror_conf_t::opcode_exclude_mask, brix_mirror_conf_t::opcode_mask, ngx_stream_brix_srv_conf_t::pipeline_depth, ngx_stream_brix_srv_conf_t::prepare_command, ngx_stream_brix_srv_conf_t::proxy, brix_rate_limit_conf_t::rate, ngx_stream_brix_srv_conf_t::rate_limit, ngx_stream_brix_srv_conf_t::read_compress, ngx_stream_brix_srv_conf_t::read_timeout, ngx_stream_brix_srv_conf_t::readv_segment_size, ngx_stream_brix_srv_conf_t::reaper, ngx_stream_brix_srv_conf_t::redir_cache_slots, ngx_stream_brix_srv_conf_t::registry_slots, ngx_stream_brix_srv_conf_t::relay_addr, ngx_stream_brix_srv_conf_t::relay_guard_enable, ngx_stream_brix_srv_conf_t::rootfd, brix_mirror_conf_t::sample_pct, ngx_stream_brix_srv_conf_t::security_level, ngx_stream_brix_srv_conf_t::send_timeout, ngx_stream_brix_srv_conf_t::session_log, ngx_stream_brix_srv_conf_t::session_slots, brix_cache_include_regex_conf_t::set, ngx_stream_brix_srv_conf_t::signing_policy_mode, ngx_stream_brix_srv_conf_t::ssi_cta_enable, ngx_stream_brix_srv_conf_t::ssi_cta_executor, ngx_stream_brix_srv_conf_t::ssi_enable, ngx_stream_brix_srv_conf_t::ssi_max_inflight, ngx_stream_brix_srv_conf_t::ssi_request_max, ngx_stream_brix_srv_conf_t::ssi_response_max, ngx_stream_brix_srv_conf_t::sss_keys, ngx_stream_brix_srv_conf_t::sss_lifetime, brix_mirror_conf_t::strip_auth, brix_mirror_conf_t::targets, ngx_stream_brix_srv_conf_t::tcp_keepalive, ngx_stream_brix_srv_conf_t::tcp_user_timeout, ngx_stream_brix_srv_conf_t::throttle, brix_mirror_conf_t::timeout_ms, ngx_stream_brix_srv_conf_t::tls, ngx_stream_brix_srv_conf_t::tls_ctx, ngx_stream_brix_srv_conf_t::tls_ktls, ngx_stream_brix_srv_conf_t::token_cache_kv, ngx_stream_brix_srv_conf_t::token_clock_skew, ngx_stream_brix_srv_conf_t::token_jwks_refresh_interval, ngx_stream_brix_srv_conf_t::tpc_allow_local, ngx_stream_brix_srv_conf_t::tpc_allow_private, ngx_stream_brix_srv_conf_t::tpc_delegate, ngx_stream_brix_srv_conf_t::tpc_key_ttl_ms, ngx_stream_brix_srv_conf_t::tpc_max_transfer_secs, ngx_stream_brix_srv_conf_t::tpc_outbound_bearer_file, ngx_stream_brix_srv_conf_t::tpc_outbound_client_id, ngx_stream_brix_srv_conf_t::tpc_outbound_client_secret, ngx_stream_brix_srv_conf_t::tpc_outbound_scope, ngx_stream_brix_srv_conf_t::tpc_outbound_tls, ngx_stream_brix_srv_conf_t::tpc_outbound_token_endpoint, ngx_stream_brix_srv_conf_t::tpc_transfer_max_age, brix_auth_cache_conf_t::ttl_secs, ngx_stream_brix_srv_conf_t::unix_trust_remote, ngx_stream_brix_srv_conf_t::upload_resume, ngx_stream_brix_srv_conf_t::upstream_addr, ngx_stream_brix_srv_conf_t::upstream_tls, ngx_stream_brix_srv_conf_t::upstream_tls_ca, ngx_stream_brix_srv_conf_t::upstream_tls_name, ngx_stream_brix_srv_conf_t::upstream_token_file, ngx_stream_brix_srv_conf_t::vo_rules, ngx_stream_brix_srv_conf_t::write_compress, ngx_stream_brix_srv_conf_t::wt, ngx_stream_brix_srv_conf_t::zip_access, ngx_stream_brix_srv_conf_t::zip_cd_max_bytes, ngx_stream_brix_srv_conf_t::zip_force_scratch, and ngx_stream_brix_srv_conf_t::zip_stage_max_bytes.
ngx_stream_brix_enable()
char * ngx_stream_brix_enable (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 890 of file server_conf.c.
References ngx_stream_brix_srv_conf_t::common, ngx_http_brix_shared_conf_t::enable, and ngx_stream_brix_handler().
ngx_stream_brix_merge_srv_conf()
char * ngx_stream_brix_merge_srv_conf (ngx_conf_t * cf, void * parent, void * child)
Definition at line 864 of file server_conf.c.
References brix_merge_srv_cluster(), brix_merge_srv_proxy_net(), brix_merge_srv_security(), brix_merge_srv_storage(), and brix_merge_srv_tpc().