nginx-xrootd: src/net/cms/server_recv_internal.h File Reference
server_recv_internal.h File Reference
#include "server.h"
Functions
void cms_srv_set_end_hint (brix_cms_srv_ctx_t *ctx, brix_sess_end_t why)
void cms_srv_fail_close (brix_cms_srv_ctx_t *ctx, brix_sess_end_t why)
void cms_srv_log_auth_fail (brix_cms_srv_ctx_t *ctx, const char *err)
void cms_srv_log_registration (brix_cms_srv_ctx_t *ctx)
int cms_srv_parse_login (brix_cms_srv_ctx_t *ctx, const u_char *payload, size_t payload_len)
uint32_t cms_srv_parse_load_free_mb (const u_char *payload, size_t payload_len)
uint32_t cms_srv_parse_load_machine_pct (const u_char *payload, size_t payload_len)
void cms_srv_parse_avail (const u_char *payload, size_t payload_len, uint32_t *free_mb, uint32_t *util_pct)
void cms_srv_process_frame (brix_cms_srv_ctx_t *ctx, u_char code, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_complete_login (brix_cms_srv_ctx_t *ctx)
void cms_srv_frame_login (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_xauth (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_load (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_avail (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_pong (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_ping (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_disc (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_update (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_statfs (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_status (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_usage (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_stats (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_gone (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_have (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_error (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_cns (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
Function Documentation
cms_srv_complete_login()
void cms_srv_complete_login (brix_cms_srv_ctx_t * ctx)
Definition at line 86 of file server_recv_frame.c.
References brix_cms_srv_node_add(), brix_cms_srv_ping_timer(), brix_srv_register(), brix_srv_set_vnid(), brix_cms_srv_ctx_t::c, cms_srv_blfile_tick(), cms_srv_log_registration(), brix_cms_srv_ctx_t::free_mb, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::idle_timeout_ms, brix_cms_srv_ctx_t::interval_ms, brix_cms_srv_ctx_t::logged_in, brix_cms_srv_ctx_t::paths, brix_cms_srv_ctx_t::ping_timer, brix_cms_srv_ctx_t::port, brix_cms_srv_ctx_t::util_pct, and brix_cms_srv_ctx_t::vnid.
Referenced by cms_srv_frame_login(), and cms_srv_frame_xauth().
cms_srv_fail_close()
void cms_srv_fail_close (brix_cms_srv_ctx_t * ctx, brix_sess_end_t why)
Definition at line 174 of file server_recv_lifecycle.c.
References brix_cms_srv_close(), and cms_srv_set_end_hint().
Referenced by brix_cms_srv_read(), cms_srv_frame_disc(), cms_srv_frame_login(), cms_srv_frame_ping(), cms_srv_frame_update(), cms_srv_frame_xauth(), cms_srv_read_accumulate(), cms_srv_read_timeout(), and cms_srv_read_yield().
cms_srv_frame_avail()
void cms_srv_frame_avail (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 127 of file server_recv_frame_handlers.c.
References brix_srv_update_load(), cms_srv_parse_avail(), brix_cms_srv_ctx_t::free_mb, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, brix_cms_srv_ctx_t::port, and brix_cms_srv_ctx_t::util_pct.
cms_srv_frame_cns()
void cms_srv_frame_cns (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 463 of file server_recv_frame_handlers.c.
References brix_cns_apply(), brix_cns_collecting(), brix_cns_event_decode(), BRIX_CNS_PATH_MAX, brix_cms_srv_ctx_t::c, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, op, and brix_cms_srv_ctx_t::port.
cms_srv_frame_disc()
void cms_srv_frame_disc (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 172 of file server_recv_frame_handlers.c.
References brix_cms_srv_send_disc(), BRIX_SESS_END_CLIENT, brix_cms_srv_ctx_t::c, cms_srv_fail_close(), and brix_cms_srv_ctx_t::host.
cms_srv_frame_error()
void cms_srv_frame_error (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 431 of file server_recv_frame_handlers.c.
References brix_cms_fanout_note_error(), brix_cms_srv_ctx_t::c, brix_cms_srv_ctx_t::logged_in, and ngx_memcpy.
cms_srv_frame_gone()
void cms_srv_frame_gone (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 344 of file server_recv_frame_handlers.c.
References BRIX_SRV_MAX_PATHS, brix_srv_unregister_path(), brix_cms_srv_ctx_t::c, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, ngx_memcpy, and brix_cms_srv_ctx_t::port.
cms_srv_frame_have()
void cms_srv_frame_have (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 379 of file server_recv_frame_handlers.c.
References brix_cms_wake_pending_session(), brix_loc_cache_insert(), BRIX_LOC_CACHE_PATH_MAX, brix_srv_is_blacklisted(), brix_srv_paths_cover(), brix_cms_srv_ctx_t::c, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, ngx_memcpy, brix_cms_srv_ctx_t::paths, and brix_cms_srv_ctx_t::port.
cms_srv_frame_load()
void cms_srv_frame_load (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 106 of file server_recv_frame_handlers.c.
References brix_srv_set_machine_load(), brix_srv_update_load(), cms_srv_parse_load_free_mb(), cms_srv_parse_load_machine_pct(), brix_cms_srv_ctx_t::free_mb, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, brix_cms_srv_ctx_t::port, and brix_cms_srv_ctx_t::util_pct.
cms_srv_frame_login()
void cms_srv_frame_login (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 46 of file server_recv_frame_handlers.c.
References brix_cms_srv_ctx_t::auth_state, brix_cms_srv_send_xauth(), BRIX_SESS_END_ERROR, brix_cms_srv_ctx_t::c, CMS_AUTH_CHALLENGED, CMS_AUTH_REQUESTED, cms_srv_complete_login(), cms_srv_fail_close(), cms_srv_log_auth_fail(), cms_srv_parse_login(), and brix_cms_srv_ctx_t::host.
cms_srv_frame_ping()
void cms_srv_frame_ping (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 157 of file server_recv_frame_handlers.c.
References brix_cms_srv_send_pong(), BRIX_SESS_END_ERROR, brix_cms_srv_ctx_t::c, cms_srv_fail_close(), and brix_cms_srv_ctx_t::host.
cms_srv_frame_pong()
void cms_srv_frame_pong (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 145 of file server_recv_frame_handlers.c.
References brix_cms_srv_ctx_t::c, and brix_cms_srv_ctx_t::host.
cms_srv_frame_statfs()
void cms_srv_frame_statfs (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 204 of file server_recv_frame_handlers.c.
References brix_cms_rrdata_parse(), brix_cms_srv_send_data(), brix_cms_statfs_encode(), brix_srv_aggregate_space(), brix_srv_count_matching(), CMS_RR_STATFS, brix_cms_srv_ctx_t::logged_in, brix_cms_rrdata_t::path, brix_cms_statfs_fields_t::s_free, brix_cms_statfs_fields_t::s_num, brix_cms_statfs_fields_t::s_util, brix_cms_statfs_fields_t::w_free, brix_cms_statfs_fields_t::w_num, and brix_cms_statfs_fields_t::w_util.
cms_srv_frame_stats()
void cms_srv_frame_stats (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 315 of file server_recv_frame_handlers.c.
References brix_cms_srv_send_data(), and brix_cms_srv_ctx_t::logged_in.
cms_srv_frame_status()
void cms_srv_frame_status (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 246 of file server_recv_frame_handlers.c.
References brix_srv_blacklist(), brix_srv_reset(), brix_srv_set_stage(), brix_srv_undrain(), brix_cms_srv_ctx_t::c, CMS_ST_NOSTAGE, CMS_ST_RESET, CMS_ST_RESUME, CMS_ST_STAGE, CMS_ST_SUSPEND, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::inbuf, brix_cms_srv_ctx_t::logged_in, and brix_cms_srv_ctx_t::port.
cms_srv_frame_update()
void cms_srv_frame_update (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 186 of file server_recv_frame_handlers.c.
References brix_cms_srv_send_status(), BRIX_SESS_END_ERROR, brix_cms_srv_ctx_t::c, cms_srv_fail_close(), CMS_ST_NOSTAGE, CMS_ST_RESUME, and brix_cms_srv_ctx_t::host.
cms_srv_frame_usage()
void cms_srv_frame_usage (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 289 of file server_recv_frame_handlers.c.
References brix_cms_meter_sample(), brix_cms_srv_send_load(), brix_srv_aggregate_space(), brix_cms_srv_ctx_t::conf, and brix_cms_srv_ctx_t::logged_in.
cms_srv_frame_xauth()
void cms_srv_frame_xauth (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 79 of file server_recv_frame_handlers.c.
References brix_cms_srv_ctx_t::auth_state, brix_cms_srv_verify_xauth(), BRIX_SESS_END_ERROR, brix_cms_srv_ctx_t::c, CMS_AUTH_CHALLENGED, CMS_AUTH_DONE, cms_srv_complete_login(), cms_srv_fail_close(), cms_srv_log_auth_fail(), and brix_cms_srv_ctx_t::host.
cms_srv_log_auth_fail()
void cms_srv_log_auth_fail (brix_cms_srv_ctx_t * ctx, const char * err)
Definition at line 85 of file server_recv_lifecycle.c.
References BRIX_SESS_AM_HOST, brix_sess_auth(), and brix_cms_srv_ctx_t::sess.
Referenced by cms_srv_frame_login(), and cms_srv_frame_xauth().
cms_srv_log_registration()
void cms_srv_log_registration (brix_cms_srv_ctx_t * ctx)
Definition at line 95 of file server_recv_lifecycle.c.
References BRIX_SESS_AM_HOST, brix_sess_attempt(), brix_sess_auth_once(), BRIX_SESS_MODE_META, brix_sess_result(), BRIX_SESSLOG_PATH_MAX, cms_srv_target_path(), brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::sess, and brix_cms_srv_ctx_t::sess_attempt_logged.
Referenced by cms_srv_complete_login().
cms_srv_parse_avail()
void cms_srv_parse_avail (const u_char * payload, size_t payload_len, uint32_t * free_mb, uint32_t * util_pct)
Definition at line 363 of file server_recv_parse.c.
References tlv_read_next().
Referenced by cms_srv_frame_avail().
cms_srv_parse_load_free_mb()
uint32_t cms_srv_parse_load_free_mb (const u_char * payload, size_t payload_len)
Definition at line 312 of file server_recv_parse.c.
References tlv_read_next().
Referenced by cms_srv_frame_load().
cms_srv_parse_load_machine_pct()
uint32_t cms_srv_parse_load_machine_pct (const u_char * payload, size_t payload_len)
Definition at line 338 of file server_recv_parse.c.
Referenced by cms_srv_frame_load().
cms_srv_parse_login()
int cms_srv_parse_login (brix_cms_srv_ctx_t * ctx, const u_char * payload, size_t payload_len)
Definition at line 223 of file server_recv_parse.c.
References BRIX_DEFAULT_PORT, cms_srv_login_append_path(), cms_srv_login_next_path(), cms_srv_login_scalars(), cms_srv_read_string(), brix_cms_srv_ctx_t::paths, brix_cms_srv_ctx_t::port, tok, and brix_cms_srv_ctx_t::vnid.
Referenced by cms_srv_frame_login().
cms_srv_process_frame()
void cms_srv_process_frame (brix_cms_srv_ctx_t * ctx, u_char code, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 198 of file server_recv_frame.c.
References cms_srv_frame_routes, cms_srv_frame_unknown(), and code.
Referenced by cms_srv_dispatch_frame().
cms_srv_set_end_hint()
void cms_srv_set_end_hint (brix_cms_srv_ctx_t * ctx, brix_sess_end_t why)
Definition at line 27 of file server_recv_lifecycle.c.
References brix_cms_srv_ctx_t::sess_end_hint, and brix_cms_srv_ctx_t::sess_end_hint_set.
Referenced by brix_cms_srv_ping_timer(), brix_cms_srv_write(), and cms_srv_fail_close().