nginx-xrootd: src/net/cms/server_send.c File Reference
server_send.c File Reference
#include "server.h"
#include "frame_io.h"
Functions
static ngx_int_t brix_cms_srv_send_frame (brix_cms_srv_ctx_t *ctx, uint32_t streamid, u_char code, u_char modifier, const u_char *payload, size_t payload_len)
ngx_int_t brix_cms_srv_send_ping (brix_cms_srv_ctx_t *ctx)
ngx_int_t brix_cms_srv_send_xauth (brix_cms_srv_ctx_t *ctx, const u_char *parms, size_t len)
ngx_int_t brix_cms_srv_send_pong (brix_cms_srv_ctx_t *ctx)
ngx_int_t brix_cms_srv_send_disc (brix_cms_srv_ctx_t *ctx)
ngx_int_t brix_cms_srv_send_status (brix_cms_srv_ctx_t *ctx, u_char modifier)
ngx_int_t brix_cms_srv_send_load (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char load6[6], uint32_t free_mb)
ngx_int_t brix_cms_srv_send_data (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t len)
ngx_int_t brix_cms_srv_send_state (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const char *path)
Function Documentation
brix_cms_srv_send_data()
ngx_int_t brix_cms_srv_send_data (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t len)
Definition at line 101 of file server_send.c.
References brix_cms_srv_send_frame(), and CMS_RSP_DATA.
Referenced by cms_srv_frame_statfs(), and cms_srv_frame_stats().
brix_cms_srv_send_disc()
ngx_int_t brix_cms_srv_send_disc (brix_cms_srv_ctx_t * ctx)
Definition at line 54 of file server_send.c.
References brix_cms_srv_send_frame(), and CMS_RR_DISC.
Referenced by cms_srv_frame_disc().
brix_cms_srv_send_frame()
static ngx_int_t brix_cms_srv_send_frame (brix_cms_srv_ctx_t * ctx, uint32_t streamid, u_char code, u_char modifier, const u_char * payload, size_t payload_len) static
Definition at line 14 of file server_send.c.
References brix_cms_send_frame(), brix_cms_srv_ctx_t::c, and code.
Referenced by brix_cms_srv_send_data(), brix_cms_srv_send_disc(), brix_cms_srv_send_load(), brix_cms_srv_send_ping(), brix_cms_srv_send_pong(), brix_cms_srv_send_state(), brix_cms_srv_send_status(), and brix_cms_srv_send_xauth().
brix_cms_srv_send_load()
ngx_int_t brix_cms_srv_send_load (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char load6[6], uint32_t free_mb)
Definition at line 80 of file server_send.c.
References brix_cms_srv_send_frame(), CMS_RR_LOAD, ngx_brix_cms_put16(), ngx_brix_cms_put_int(), and ngx_memcpy.
Referenced by cms_srv_frame_usage().
brix_cms_srv_send_ping()
ngx_int_t brix_cms_srv_send_ping (brix_cms_srv_ctx_t * ctx)
Definition at line 27 of file server_send.c.
References brix_cms_srv_send_frame(), and CMS_RR_PING.
Referenced by brix_cms_srv_ping_timer().
brix_cms_srv_send_pong()
ngx_int_t brix_cms_srv_send_pong (brix_cms_srv_ctx_t * ctx)
Definition at line 46 of file server_send.c.
References brix_cms_srv_send_frame(), and CMS_RR_PONG.
Referenced by cms_srv_frame_ping().
brix_cms_srv_send_state()
ngx_int_t brix_cms_srv_send_state (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const char * path)
Definition at line 114 of file server_send.c.
References brix_cms_srv_send_frame(), CMS_MOD_RAW, and CMS_RR_STATE.
Referenced by locate_try_dynamic().
brix_cms_srv_send_status()
ngx_int_t brix_cms_srv_send_status (brix_cms_srv_ctx_t * ctx, u_char modifier)
Definition at line 63 of file server_send.c.
References brix_cms_srv_send_frame(), and CMS_RR_STATUS.
Referenced by cms_srv_frame_update().
brix_cms_srv_send_xauth()
ngx_int_t brix_cms_srv_send_xauth (brix_cms_srv_ctx_t * ctx, const u_char * parms, size_t len)
Definition at line 37 of file server_send.c.
References brix_cms_srv_send_frame(), and CMS_RR_XAUTH.
Referenced by cms_srv_frame_login().