nginx-xrootd: src/core/config/server_conf_merge_cluster.c File Reference
server_conf_merge_cluster.c File Reference
#include "config.h"
#include "server_conf_internal.h"
#include "net/cms/cns.h"
#include "tpc/engine/key_registry.h"
#include "tpc/common/registry.h"
#include "protocols/root/session/registry.h"
#include "net/manager/health_check.h"
#include "net/manager/registry.h"
Functions
void brix_merge_srv_tpc (ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
static void brix_merge_srv_cluster_sizing (ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
static void brix_merge_srv_healthcheck (ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
static void brix_merge_srv_mirror (ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
static void brix_merge_srv_cms (ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
static void brix_merge_srv_cluster_addrs (ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
static char * brix_merge_srv_rules (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
char * brix_merge_srv_cluster (ngx_conf_t *cf, ngx_stream_brix_srv_conf_t *conf, ngx_stream_brix_srv_conf_t *prev)
Function Documentation
brix_merge_srv_cluster()
char * brix_merge_srv_cluster (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev)
Definition at line 368 of file server_conf_merge_cluster.c.
References BRIX_DEFAULT_PORT, brix_merge_srv_cluster_addrs(), brix_merge_srv_cluster_sizing(), brix_merge_srv_cms(), brix_merge_srv_healthcheck(), brix_merge_srv_mirror(), and brix_merge_srv_rules().
Referenced by ngx_stream_brix_merge_srv_conf().
brix_merge_srv_cluster_addrs()
static void brix_merge_srv_cluster_addrs (ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 293 of file server_conf_merge_cluster.c.
Referenced by brix_merge_srv_cluster().
brix_merge_srv_cluster_sizing()
static void brix_merge_srv_cluster_sizing (ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 112 of file server_conf_merge_cluster.c.
References brix_node_caps_conf_merge(), BRIX_PIPELINE_DEPTH_DEFAULT, BRIX_PIPELINE_DEPTH_MAX, BRIX_PIPELINE_DEPTH_MIN, and BRIX_SESSION_REGISTRY_SLOTS.
Referenced by brix_merge_srv_cluster().
brix_merge_srv_cms()
static void brix_merge_srv_cms (ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 206 of file server_conf_merge_cluster.c.
References brix_srv_set_affinity(), and brix_srv_set_load_weight().
Referenced by brix_merge_srv_cluster().
brix_merge_srv_healthcheck()
static void brix_merge_srv_healthcheck (ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 148 of file server_conf_merge_cluster.c.
References BRIX_HC_TYPE_PING.
Referenced by brix_merge_srv_cluster().
brix_merge_srv_mirror()
static void brix_merge_srv_mirror (ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 169 of file server_conf_merge_cluster.c.
References BRIX_MIRROR_M_DEFAULT, and BRIX_MIRROR_OP_ALL.
Referenced by brix_merge_srv_cluster().
brix_merge_srv_rules()
static char * brix_merge_srv_rules (ngx_conf_t * cf, ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev) static
Definition at line 327 of file server_conf_merge_cluster.c.
References brix_merge_arrays().
Referenced by brix_merge_srv_cluster().
brix_merge_srv_tpc()
void brix_merge_srv_tpc (ngx_stream_brix_srv_conf_t * conf, ngx_stream_brix_srv_conf_t * prev)
Definition at line 37 of file server_conf_merge_cluster.c.
References BRIX_CNS_COLLECT, BRIX_CNS_OFF, brix_cns_set_collect(), BRIX_TPC_KEY_TTL_MS, and brix_tpc_registry_set_max_age().
Referenced by ngx_stream_brix_merge_srv_conf().