nginx-xrootd: src/net/cms/server_recv.c File Reference
server_recv.c File Reference
#include "server.h"
#include "router.h"
#include "rrdata.h"
#include "net/manager/registry.h"
#include "cns.h"
#include "observability/metrics/metrics_macros.h"
#include "core/compat/log_diag.h"
Functions
void brix_cms_srv_close (brix_cms_srv_ctx_t *ctx)
static uint32_t tlv_read_next (const u_char **p, const u_char *end)
static int cms_srv_read_string (const u_char **p, const u_char *end, const u_char **out, size_t *out_len)
static int cms_srv_parse_login (brix_cms_srv_ctx_t *ctx, const u_char *payload, size_t payload_len)
static uint32_t cms_srv_parse_load_free_mb (const u_char *payload, size_t payload_len)
static void cms_srv_parse_avail (const u_char *payload, size_t payload_len, uint32_t *free_mb, uint32_t *util_pct)
static void brix_cms_srv_ping_timer (ngx_event_t *ev)
static void cms_srv_complete_login (brix_cms_srv_ctx_t *ctx)
static void cms_srv_process_frame (brix_cms_srv_ctx_t *ctx, u_char code, uint32_t streamid, const u_char *payload, size_t payload_len)
void brix_cms_srv_write (ngx_event_t *ev)
void brix_cms_srv_read (ngx_event_t *ev)
Function Documentation
brix_cms_srv_close()
void brix_cms_srv_close (brix_cms_srv_ctx_t * ctx)
Definition at line 14 of file server_recv.c.
References brix_cms_srv_conn_dec(), brix_cms_srv_ip_dec(), BRIX_DIAG, brix_srv_blacklist(), brix_cms_srv_ctx_t::c, c, brix_cms_srv_ctx_t::counted, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, brix_cms_srv_ctx_t::ping_timer, and brix_cms_srv_ctx_t::port.
Referenced by brix_cms_srv_ping_timer(), brix_cms_srv_read(), brix_cms_srv_write(), and cms_srv_process_frame().
brix_cms_srv_ping_timer()
static void brix_cms_srv_ping_timer (ngx_event_t * ev) static
Definition at line 295 of file server_recv.c.
References brix_cms_srv_close(), brix_cms_srv_send_ping(), brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::interval_ms, and brix_cms_srv_ctx_t::ping_timer.
Referenced by cms_srv_complete_login().
brix_cms_srv_read()
void brix_cms_srv_read (ngx_event_t * ev)
Definition at line 596 of file server_recv.c.
References brix_cms_srv_close(), BRIX_RESIL_METRIC_INC, brix_cms_srv_ctx_t::c, c, cms_srv_process_frame(), brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::idle_timeout_ms, brix_cms_srv_ctx_t::in_need, brix_cms_srv_ctx_t::in_pos, brix_cms_srv_ctx_t::inbuf, brix_cms_srv_ctx_t::logged_in, ngx_brix_cms_get16(), ngx_brix_cms_get32(), NGX_BRIX_CMS_HDR_LEN, NGX_BRIX_CMS_MAX_FRAME, and NGX_BRIX_CMS_MAX_FRAMES_PER_WAKEUP.
Referenced by brix_cms_srv_handler().
brix_cms_srv_write()
void brix_cms_srv_write (ngx_event_t * ev)
Definition at line 578 of file server_recv.c.
References brix_cms_srv_close(), and c.
Referenced by brix_cms_srv_handler().
cms_srv_complete_login()
static void cms_srv_complete_login (brix_cms_srv_ctx_t * ctx) static
Definition at line 321 of file server_recv.c.
References brix_cms_srv_ping_timer(), brix_srv_register(), brix_cms_srv_ctx_t::c, brix_cms_srv_ctx_t::free_mb, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::idle_timeout_ms, brix_cms_srv_ctx_t::interval_ms, brix_cms_srv_ctx_t::logged_in, brix_cms_srv_ctx_t::paths, brix_cms_srv_ctx_t::ping_timer, brix_cms_srv_ctx_t::port, and brix_cms_srv_ctx_t::util_pct.
Referenced by cms_srv_process_frame().
cms_srv_parse_avail()
static void cms_srv_parse_avail (const u_char * payload, size_t payload_len, uint32_t * free_mb, uint32_t * util_pct) static
Definition at line 282 of file server_recv.c.
References tlv_read_next().
Referenced by cms_srv_process_frame().
cms_srv_parse_load_free_mb()
static uint32_t cms_srv_parse_load_free_mb (const u_char * payload, size_t payload_len) static
Definition at line 256 of file server_recv.c.
References tlv_read_next().
Referenced by cms_srv_process_frame().
cms_srv_parse_login()
static int cms_srv_parse_login (brix_cms_srv_ctx_t * ctx, const u_char * payload, size_t payload_len) static
Definition at line 137 of file server_recv.c.
References BRIX_DEFAULT_PORT, cms_srv_read_string(), brix_cms_srv_ctx_t::free_mb, brix_cms_srv_ctx_t::paths, brix_cms_srv_ctx_t::port, tlv_read_next(), and brix_cms_srv_ctx_t::util_pct.
Referenced by cms_srv_process_frame().
cms_srv_process_frame()
static void cms_srv_process_frame (brix_cms_srv_ctx_t * ctx, u_char code, uint32_t streamid, const u_char * payload, size_t payload_len) static
Definition at line 352 of file server_recv.c.
References brix_cms_srv_ctx_t::auth_state, brix_cms_route_lookup(), brix_cms_rrdata_parse(), brix_cms_srv_close(), brix_cms_srv_send_data(), brix_cms_srv_send_disc(), brix_cms_srv_send_pong(), brix_cms_srv_send_status(), brix_cms_srv_send_xauth(), brix_cms_srv_verify_xauth(), brix_cms_statfs_encode(), brix_cns_apply(), brix_cns_collecting(), brix_cns_event_decode(), BRIX_CNS_PATH_MAX, brix_srv_aggregate_space(), brix_srv_count_matching(), BRIX_SRV_MAX_PATHS, brix_srv_unregister_path(), brix_srv_update_load(), brix_cms_srv_ctx_t::c, CMS_AUTH_CHALLENGED, CMS_AUTH_DONE, CMS_AUTH_REQUESTED, CMS_RR_AVAIL, CMS_RR_CNS, CMS_RR_DISC, CMS_RR_GONE, CMS_RR_LOAD, CMS_RR_LOGIN, CMS_RR_PING, CMS_RR_PONG, CMS_RR_SPACE, CMS_RR_STATFS, CMS_RR_UPDATE, CMS_RR_XAUTH, cms_srv_complete_login(), cms_srv_parse_avail(), cms_srv_parse_load_free_mb(), cms_srv_parse_login(), CMS_ST_NOSTAGE, CMS_ST_RESUME, brix_cms_srv_ctx_t::free_mb, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, brix_cms_route_t::name, brix_cms_rrdata_t::path, brix_cms_srv_ctx_t::port, brix_cms_srv_ctx_t::util_pct, and XRDCMS_ROLE_MANAGER.
Referenced by brix_cms_srv_read().
cms_srv_read_string()
static int cms_srv_read_string (const u_char ** p, const u_char * end, const u_char ** out, size_t * out_len) static
Definition at line 104 of file server_recv.c.
References ngx_brix_cms_get16().
Referenced by cms_srv_parse_login().
tlv_read_next()
static uint32_t tlv_read_next (const u_char ** p, const u_char * end) static
Definition at line 69 of file server_recv.c.
References CMS_PT_INT, CMS_PT_SHORT, ngx_brix_cms_get16(), and ngx_brix_cms_get32().
Referenced by cms_srv_parse_avail(), cms_srv_parse_load_free_mb(), and cms_srv_parse_login().