nginx-xrootd: src/net/cms/server_recv_parse.c File Reference
server_recv_parse.c File Reference
#include "server.h"
#include "server_recv_internal.h"
Functions
static uint32_t tlv_read_next (const u_char **p, const u_char *end)
static int cms_srv_read_string (const u_char **p, const u_char *end, const u_char **out, size_t *out_len)
static void cms_srv_login_scalars (brix_cms_srv_ctx_t *ctx, const u_char **p, const u_char *end)
static void cms_srv_login_seg_path (const u_char **tok, size_t *tok_len)
static int cms_srv_login_next_path (const u_char *paths, size_t paths_len, size_t *i, const u_char **tok, size_t *tok_len)
static void cms_srv_login_append_path (brix_cms_srv_ctx_t *ctx, u_char **dst, u_char *dst_end, const u_char *tok, size_t tok_len)
int cms_srv_parse_login (brix_cms_srv_ctx_t *ctx, const u_char *payload, size_t payload_len)
uint32_t cms_srv_parse_load_free_mb (const u_char *payload, size_t payload_len)
void cms_srv_parse_avail (const u_char *payload, size_t payload_len, uint32_t *free_mb, uint32_t *util_pct)
Function Documentation
cms_srv_login_append_path()
static void cms_srv_login_append_path (brix_cms_srv_ctx_t * ctx, u_char ** dst, u_char * dst_end, const u_char * tok, size_t tok_len) static
Definition at line 202 of file server_recv_parse.c.
References ngx_memcpy, brix_cms_srv_ctx_t::paths, and tok.
Referenced by cms_srv_parse_login().
cms_srv_login_next_path()
static int cms_srv_login_next_path (const u_char * paths, size_t paths_len, size_t * i, const u_char ** tok, size_t * tok_len) static
Definition at line 165 of file server_recv_parse.c.
References cms_srv_login_seg_path(), and tok.
Referenced by cms_srv_parse_login().
cms_srv_login_scalars()
static void cms_srv_login_scalars (brix_cms_srv_ctx_t * ctx, const u_char ** p, const u_char * end) static
Definition at line 112 of file server_recv_parse.c.
References brix_cms_srv_ctx_t::free_mb, brix_cms_srv_ctx_t::port, tlv_read_next(), and brix_cms_srv_ctx_t::util_pct.
Referenced by cms_srv_parse_login().
cms_srv_login_seg_path()
static void cms_srv_login_seg_path (const u_char ** tok, size_t * tok_len) static
Definition at line 134 of file server_recv_parse.c.
References tok.
Referenced by cms_srv_login_next_path().
cms_srv_parse_avail()
void cms_srv_parse_avail (const u_char * payload, size_t payload_len, uint32_t * free_mb, uint32_t * util_pct)
Definition at line 305 of file server_recv_parse.c.
References tlv_read_next().
Referenced by cms_srv_frame_avail().
cms_srv_parse_load_free_mb()
uint32_t cms_srv_parse_load_free_mb (const u_char * payload, size_t payload_len)
Definition at line 279 of file server_recv_parse.c.
References tlv_read_next().
Referenced by cms_srv_frame_load().
cms_srv_parse_login()
int cms_srv_parse_login (brix_cms_srv_ctx_t * ctx, const u_char * payload, size_t payload_len)
Definition at line 223 of file server_recv_parse.c.
References BRIX_DEFAULT_PORT, cms_srv_login_append_path(), cms_srv_login_next_path(), cms_srv_login_scalars(), cms_srv_read_string(), brix_cms_srv_ctx_t::paths, brix_cms_srv_ctx_t::port, and tok.
Referenced by cms_srv_frame_login().
cms_srv_read_string()
static int cms_srv_read_string (const u_char ** p, const u_char * end, const u_char ** out, size_t * out_len) static
Definition at line 71 of file server_recv_parse.c.
References ngx_brix_cms_get16().
Referenced by cms_srv_parse_login().
tlv_read_next()
static uint32_t tlv_read_next (const u_char ** p, const u_char * end) static
Definition at line 36 of file server_recv_parse.c.
References CMS_PT_INT, CMS_PT_SHORT, ngx_brix_cms_get16(), and ngx_brix_cms_get32().
Referenced by cms_srv_login_scalars(), cms_srv_parse_avail(), and cms_srv_parse_load_free_mb().