nginx-xrootd: src/net/cms/server_recv_lifecycle.c File Reference
server_recv_lifecycle.c File Reference
#include "server.h"
#include "server_recv_internal.h"
#include "observability/sesslog/sesslog_ngx.h"
#include "core/compat/log_diag.h"
Functions
void cms_srv_set_end_hint (brix_cms_srv_ctx_t *ctx, brix_sess_end_t why)
static brix_sess_end_t cms_srv_end_reason (brix_cms_srv_ctx_t *ctx, ngx_connection_t *c)
static const char * cms_srv_target_path (brix_cms_srv_ctx_t *ctx, char *dst, size_t dst_size)
void cms_srv_log_auth_fail (brix_cms_srv_ctx_t *ctx, const char *err)
void cms_srv_log_registration (brix_cms_srv_ctx_t *ctx)
void brix_cms_srv_close (brix_cms_srv_ctx_t *ctx)
void cms_srv_fail_close (brix_cms_srv_ctx_t *ctx, brix_sess_end_t why)
Function Documentation
brix_cms_srv_close()
void brix_cms_srv_close (brix_cms_srv_ctx_t * ctx)
Definition at line 116 of file server_recv_lifecycle.c.
References brix_cms_srv_conn_dec(), brix_cms_srv_ip_dec(), brix_cms_srv_node_del(), BRIX_DIAG, brix_sess_end(), brix_srv_blacklist(), c, brix_cms_srv_ctx_t::c, cms_srv_end_reason(), brix_cms_srv_ctx_t::counted, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, NGX_BRIX_CMS_SRV_DROP_BLACKLIST_MS, brix_cms_srv_ctx_t::ping_timer, brix_cms_srv_ctx_t::port, and brix_cms_srv_ctx_t::sess.
Referenced by brix_cms_srv_ping_timer(), brix_cms_srv_write(), and cms_srv_fail_close().
cms_srv_end_reason()
static brix_sess_end_t cms_srv_end_reason (brix_cms_srv_ctx_t * ctx, ngx_connection_t * c) static
Definition at line 38 of file server_recv_lifecycle.c.
References BRIX_SESS_END_CLIENT, BRIX_SESS_END_ERROR, BRIX_SESS_END_SHUTDOWN, BRIX_SESS_END_TIMEOUT, c, brix_cms_srv_ctx_t::sess_end_hint, and brix_cms_srv_ctx_t::sess_end_hint_set.
Referenced by brix_cms_srv_close().
cms_srv_fail_close()
void cms_srv_fail_close (brix_cms_srv_ctx_t * ctx, brix_sess_end_t why)
Definition at line 174 of file server_recv_lifecycle.c.
References brix_cms_srv_close(), and cms_srv_set_end_hint().
Referenced by brix_cms_srv_read(), cms_srv_frame_disc(), cms_srv_frame_login(), cms_srv_frame_ping(), cms_srv_frame_update(), cms_srv_frame_xauth(), cms_srv_read_accumulate(), cms_srv_read_timeout(), and cms_srv_read_yield().
cms_srv_log_auth_fail()
void cms_srv_log_auth_fail (brix_cms_srv_ctx_t * ctx, const char * err)
Definition at line 85 of file server_recv_lifecycle.c.
References BRIX_SESS_AM_HOST, brix_sess_auth(), and brix_cms_srv_ctx_t::sess.
Referenced by cms_srv_frame_login(), and cms_srv_frame_xauth().
cms_srv_log_registration()
void cms_srv_log_registration (brix_cms_srv_ctx_t * ctx)
Definition at line 95 of file server_recv_lifecycle.c.
References BRIX_SESS_AM_HOST, brix_sess_attempt(), brix_sess_auth_once(), BRIX_SESS_MODE_META, brix_sess_result(), BRIX_SESSLOG_PATH_MAX, cms_srv_target_path(), brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::sess, and brix_cms_srv_ctx_t::sess_attempt_logged.
Referenced by cms_srv_complete_login().
cms_srv_set_end_hint()
void cms_srv_set_end_hint (brix_cms_srv_ctx_t * ctx, brix_sess_end_t why)
Definition at line 27 of file server_recv_lifecycle.c.
References brix_cms_srv_ctx_t::sess_end_hint, and brix_cms_srv_ctx_t::sess_end_hint_set.
Referenced by brix_cms_srv_ping_timer(), brix_cms_srv_write(), and cms_srv_fail_close().
cms_srv_target_path()
static const char * cms_srv_target_path (brix_cms_srv_ctx_t * ctx, char * dst, size_t dst_size) static
Definition at line 63 of file server_recv_lifecycle.c.
References brix_cms_srv_ctx_t::host, and brix_cms_srv_ctx_t::port.
Referenced by cms_srv_log_registration().