nginx-xrootd: src/net/cms/server_recv_frame_handlers.c File Reference
server_recv_frame_handlers.c File Reference
#include "server.h"
#include "server_recv_internal.h"
#include "rrdata.h"
#include "net/manager/registry.h"
#include "net/manager/loc_cache.h"
#include "recv_internal.h"
#include "cns.h"
#include "fanout.h"
#include "action_log.h"
Functions
void cms_srv_frame_login (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_xauth (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_load (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_avail (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_pong (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_ping (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_disc (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_update (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_statfs (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_status (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_usage (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_stats (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_gone (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_have (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_error (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
void cms_srv_frame_cns (brix_cms_srv_ctx_t *ctx, uint32_t streamid, const u_char *payload, size_t payload_len)
Function Documentation
cms_srv_frame_avail()
void cms_srv_frame_avail (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 141 of file server_recv_frame_handlers.c.
References brix_cms_log_action_hp(), brix_srv_update_load(), brix_cms_srv_ctx_t::c, cms_srv_parse_avail(), brix_cms_srv_ctx_t::free_mb, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, brix_cms_srv_ctx_t::port, and brix_cms_srv_ctx_t::util_pct.
cms_srv_frame_cns()
void cms_srv_frame_cns (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 508 of file server_recv_frame_handlers.c.
References brix_cns_apply(), brix_cns_collecting(), brix_cns_event_decode(), BRIX_CNS_PATH_MAX, brix_cms_srv_ctx_t::c, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, op, and brix_cms_srv_ctx_t::port.
cms_srv_frame_disc()
void cms_srv_frame_disc (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 196 of file server_recv_frame_handlers.c.
References brix_cms_log_action_hp(), brix_cms_srv_send_disc(), BRIX_SESS_END_CLIENT, brix_cms_srv_ctx_t::c, cms_srv_fail_close(), brix_cms_srv_ctx_t::host, and brix_cms_srv_ctx_t::port.
cms_srv_frame_error()
void cms_srv_frame_error (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 476 of file server_recv_frame_handlers.c.
References brix_cms_fanout_note_error(), brix_cms_srv_ctx_t::c, brix_cms_srv_ctx_t::logged_in, and ngx_memcpy.
cms_srv_frame_gone()
void cms_srv_frame_gone (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 380 of file server_recv_frame_handlers.c.
References brix_cms_log_action_hp(), BRIX_SRV_MAX_PATHS, brix_srv_unregister_path(), brix_cms_srv_ctx_t::c, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, ngx_memcpy, and brix_cms_srv_ctx_t::port.
cms_srv_frame_have()
void cms_srv_frame_have (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 418 of file server_recv_frame_handlers.c.
References brix_cms_log_action_hp(), brix_cms_wake_pending_session(), brix_loc_cache_insert(), BRIX_LOC_CACHE_PATH_MAX, brix_srv_is_blacklisted(), brix_srv_paths_cover(), brix_cms_srv_ctx_t::c, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, ngx_memcpy, brix_cms_srv_ctx_t::paths, and brix_cms_srv_ctx_t::port.
cms_srv_frame_load()
void cms_srv_frame_load (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 110 of file server_recv_frame_handlers.c.
References brix_cms_log_action_hp(), brix_srv_set_machine_load(), brix_srv_update_load(), brix_cms_srv_ctx_t::c, cms_srv_parse_load_free_mb(), cms_srv_parse_load_machine_pct(), brix_cms_srv_ctx_t::free_mb, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::logged_in, brix_cms_srv_ctx_t::port, and brix_cms_srv_ctx_t::util_pct.
cms_srv_frame_login()
void cms_srv_frame_login (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 47 of file server_recv_frame_handlers.c.
References brix_cms_srv_ctx_t::auth_state, brix_cms_log_action_hp(), brix_cms_srv_send_xauth(), BRIX_SESS_END_ERROR, brix_cms_srv_ctx_t::c, CMS_AUTH_CHALLENGED, CMS_AUTH_REQUESTED, cms_srv_complete_login(), cms_srv_fail_close(), cms_srv_log_auth_fail(), cms_srv_parse_login(), brix_cms_srv_ctx_t::host, and brix_cms_srv_ctx_t::port.
cms_srv_frame_ping()
void cms_srv_frame_ping (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 181 of file server_recv_frame_handlers.c.
References brix_cms_srv_send_pong(), BRIX_SESS_END_ERROR, brix_cms_srv_ctx_t::c, cms_srv_fail_close(), and brix_cms_srv_ctx_t::host.
cms_srv_frame_pong()
void cms_srv_frame_pong (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 169 of file server_recv_frame_handlers.c.
References brix_cms_srv_ctx_t::c, and brix_cms_srv_ctx_t::host.
cms_srv_frame_statfs()
void cms_srv_frame_statfs (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 231 of file server_recv_frame_handlers.c.
References brix_cms_rrdata_parse(), brix_cms_srv_send_data(), brix_cms_statfs_encode(), brix_srv_aggregate_space(), brix_srv_count_matching(), CMS_RR_STATFS, brix_cms_srv_ctx_t::logged_in, brix_cms_rrdata_t::path, brix_cms_statfs_fields_t::s_free, brix_cms_statfs_fields_t::s_num, brix_cms_statfs_fields_t::s_util, brix_cms_statfs_fields_t::w_free, brix_cms_statfs_fields_t::w_num, and brix_cms_statfs_fields_t::w_util.
cms_srv_frame_stats()
void cms_srv_frame_stats (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 351 of file server_recv_frame_handlers.c.
References brix_cms_srv_send_data(), and brix_cms_srv_ctx_t::logged_in.
cms_srv_frame_status()
void cms_srv_frame_status (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 273 of file server_recv_frame_handlers.c.
References brix_cms_log_action_hp(), brix_srv_blacklist(), brix_srv_reset(), brix_srv_set_stage(), brix_srv_undrain(), brix_cms_srv_ctx_t::c, CMS_ST_NOSTAGE, CMS_ST_RESET, CMS_ST_RESUME, CMS_ST_STAGE, CMS_ST_SUSPEND, brix_cms_srv_ctx_t::host, brix_cms_srv_ctx_t::inbuf, brix_cms_srv_ctx_t::logged_in, and brix_cms_srv_ctx_t::port.
cms_srv_frame_update()
void cms_srv_frame_update (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 213 of file server_recv_frame_handlers.c.
References brix_cms_srv_send_status(), BRIX_SESS_END_ERROR, brix_cms_srv_ctx_t::c, cms_srv_fail_close(), CMS_ST_NOSTAGE, CMS_ST_RESUME, and brix_cms_srv_ctx_t::host.
cms_srv_frame_usage()
void cms_srv_frame_usage (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 325 of file server_recv_frame_handlers.c.
References brix_cms_meter_sample(), brix_cms_srv_send_load(), brix_srv_aggregate_space(), brix_cms_srv_ctx_t::conf, and brix_cms_srv_ctx_t::logged_in.
cms_srv_frame_xauth()
void cms_srv_frame_xauth (brix_cms_srv_ctx_t * ctx, uint32_t streamid, const u_char * payload, size_t payload_len)
Definition at line 83 of file server_recv_frame_handlers.c.
References brix_cms_srv_ctx_t::auth_state, brix_cms_srv_verify_xauth(), BRIX_SESS_END_ERROR, brix_cms_srv_ctx_t::c, CMS_AUTH_CHALLENGED, CMS_AUTH_DONE, cms_srv_complete_login(), cms_srv_fail_close(), cms_srv_log_auth_fail(), and brix_cms_srv_ctx_t::host.