nginx-xrootd: src/observability/sesslog/sesslog.h File Reference
sesslog.h File Reference
#include <stddef.h>
#include <stdint.h>
Data Structures
struct brix_sess_xfer_t
struct brix_sess_t
struct brix_sesslog_auth_fields_t
struct brix_sesslog_attempt_fields_t
struct brix_sesslog_result_fields_t
struct brix_sesslog_xfer_fields_t
struct brix_sesslog_end_fields_t
Macros
#define BRIX_SESSLOG_ID_LEN 16
#define BRIX_SESSLOG_LINE_MAX 4096
#define BRIX_SESSLOG_PATH_MAX 1024
#define BRIX_SESSLOG_PENDING_PATH_MAX 256
#define BRIX_SESSLOG_USER_MAX 256
#define BRIX_SESSLOG_VO_MAX 128
#define BRIX_SESSLOG_PEER_MAX 80
#define BRIX_SESSLOG_ERR_MAX 32
Typedefs
typedef size_t(* brix_sess_sanitize_fn) (char *dst, size_t dst_size, const char *src, size_t src_len)
Enumerations
enum brix_sess_proto_t {
BRIX_SESS_PROTO_ROOT = 0 , BRIX_SESS_PROTO_WEBDAV , BRIX_SESS_PROTO_S3 , BRIX_SESS_PROTO_CVMFS ,
BRIX_SESS_PROTO_CMS , BRIX_SESS_PROTO_TPC , BRIX_SESS_PROTO_FILL , BRIX_SESS_PROTO_MAX
}
enum brix_sess_dir_t { BRIX_SESS_DIR_IN = 0 , BRIX_SESS_DIR_OUT }
enum brix_sess_am_t {
BRIX_SESS_AM_GSI = 0 , BRIX_SESS_AM_TOKEN , BRIX_SESS_AM_SSS , BRIX_SESS_AM_KRB5 ,
BRIX_SESS_AM_PWD , BRIX_SESS_AM_UNIX , BRIX_SESS_AM_HOST , BRIX_SESS_AM_SIGV4 ,
BRIX_SESS_AM_ANON , BRIX_SESS_AM_MAX
}
enum brix_sess_mode_t {
BRIX_SESS_MODE_READ = 0 , BRIX_SESS_MODE_WRITE , BRIX_SESS_MODE_META , BRIX_SESS_MODE_DELETE ,
BRIX_SESS_MODE_LIST , BRIX_SESS_MODE_COPY , BRIX_SESS_MODE_MAX
}
enum brix_sess_xfer_status_t { BRIX_SESS_XFER_COMPLETE = 0 , BRIX_SESS_XFER_ABORTED , BRIX_SESS_XFER_SHUTDOWN }
enum brix_sess_end_t {
BRIX_SESS_END_CLIENT = 0 , BRIX_SESS_END_SERVER , BRIX_SESS_END_TIMEOUT , BRIX_SESS_END_SHUTDOWN ,
BRIX_SESS_END_ERROR
}
Functions
size_t brix_sesslog_fmt_connect (char *line, size_t line_max, const brix_sess_t *s, brix_sess_sanitize_fn san)
size_t brix_sesslog_fmt_auth (char *line, size_t line_max, const brix_sess_t *s, const brix_sesslog_auth_fields_t *f, brix_sess_sanitize_fn san)
size_t brix_sesslog_fmt_attempt (char *line, size_t line_max, const brix_sess_t *s, const brix_sesslog_attempt_fields_t *f, brix_sess_sanitize_fn san)
size_t brix_sesslog_fmt_result (char *line, size_t line_max, const brix_sess_t *s, const brix_sesslog_result_fields_t *f, brix_sess_sanitize_fn san)
size_t brix_sesslog_fmt_xfer (char *line, size_t line_max, const brix_sess_t *s, const brix_sesslog_xfer_fields_t *f, brix_sess_sanitize_fn san)
size_t brix_sesslog_fmt_end (char *line, size_t line_max, const brix_sess_t *s, const brix_sesslog_end_fields_t *f, brix_sess_sanitize_fn san)
const char * brix_sesslog_proto_label (brix_sess_proto_t p)
const char * brix_sesslog_dir_label (brix_sess_dir_t d)
const char * brix_sesslog_am_label (brix_sess_am_t m)
const char * brix_sesslog_mode_label (brix_sess_mode_t m)
const char * brix_sesslog_xfer_label (brix_sess_xfer_status_t st)
const char * brix_sesslog_end_label (brix_sess_end_t e)
const char * brix_sesslog_err_from_errno (int err, char *scratch, size_t n)
const char * brix_sesslog_err_from_kxr (int kxr, char *scratch, size_t n)
const char * brix_sesslog_err_from_http (int status, char *scratch, size_t n)
Macro Definition Documentation
BRIX_SESSLOG_ERR_MAX
#define BRIX_SESSLOG_ERR_MAX 32
Definition at line 14 of file sesslog.h.
BRIX_SESSLOG_ID_LEN
#define BRIX_SESSLOG_ID_LEN 16
Definition at line 7 of file sesslog.h.
BRIX_SESSLOG_LINE_MAX
#define BRIX_SESSLOG_LINE_MAX 4096
Definition at line 8 of file sesslog.h.
BRIX_SESSLOG_PATH_MAX
#define BRIX_SESSLOG_PATH_MAX 1024
Definition at line 9 of file sesslog.h.
BRIX_SESSLOG_PEER_MAX
#define BRIX_SESSLOG_PEER_MAX 80
Definition at line 13 of file sesslog.h.
BRIX_SESSLOG_PENDING_PATH_MAX
#define BRIX_SESSLOG_PENDING_PATH_MAX 256
Definition at line 10 of file sesslog.h.
BRIX_SESSLOG_USER_MAX
#define BRIX_SESSLOG_USER_MAX 256
Definition at line 11 of file sesslog.h.
BRIX_SESSLOG_VO_MAX
#define BRIX_SESSLOG_VO_MAX 128
Definition at line 12 of file sesslog.h.
Typedef Documentation
brix_sess_sanitize_fn
typedef size_t(* brix_sess_sanitize_fn) (char *dst, size_t dst_size, const char *src, size_t src_len)
Definition at line 69 of file sesslog.h.
Enumeration Type Documentation
brix_sess_am_t
enum brix_sess_am_t
Enumerator
BRIX_SESS_AM_GSI
BRIX_SESS_AM_TOKEN
BRIX_SESS_AM_SSS
BRIX_SESS_AM_KRB5
BRIX_SESS_AM_PWD
BRIX_SESS_AM_UNIX
BRIX_SESS_AM_HOST
BRIX_SESS_AM_SIGV4
BRIX_SESS_AM_ANON
BRIX_SESS_AM_MAX
Definition at line 32 of file sesslog.h.
brix_sess_dir_t
enum brix_sess_dir_t
Enumerator
BRIX_SESS_DIR_IN
BRIX_SESS_DIR_OUT
Definition at line 27 of file sesslog.h.
brix_sess_end_t
enum brix_sess_end_t
Enumerator
BRIX_SESS_END_CLIENT
BRIX_SESS_END_SERVER
BRIX_SESS_END_TIMEOUT
BRIX_SESS_END_SHUTDOWN
BRIX_SESS_END_ERROR
Definition at line 61 of file sesslog.h.
brix_sess_mode_t
enum brix_sess_mode_t
Enumerator
BRIX_SESS_MODE_READ
BRIX_SESS_MODE_WRITE
BRIX_SESS_MODE_META
BRIX_SESS_MODE_DELETE
BRIX_SESS_MODE_LIST
BRIX_SESS_MODE_COPY
BRIX_SESS_MODE_MAX
Definition at line 45 of file sesslog.h.
brix_sess_proto_t
enum brix_sess_proto_t
Enumerator
BRIX_SESS_PROTO_ROOT
BRIX_SESS_PROTO_WEBDAV
BRIX_SESS_PROTO_S3
BRIX_SESS_PROTO_CVMFS
BRIX_SESS_PROTO_CMS
BRIX_SESS_PROTO_TPC
BRIX_SESS_PROTO_FILL
BRIX_SESS_PROTO_MAX
Definition at line 16 of file sesslog.h.
brix_sess_xfer_status_t
enum brix_sess_xfer_status_t
Enumerator
BRIX_SESS_XFER_COMPLETE
BRIX_SESS_XFER_ABORTED
BRIX_SESS_XFER_SHUTDOWN
Definition at line 55 of file sesslog.h.
Function Documentation
brix_sesslog_am_label()
const char * brix_sesslog_am_label (brix_sess_am_t m)
Definition at line 283 of file sesslog.c.
References brix_sess_am_labels, and BRIX_SESS_AM_MAX.
Referenced by brix_sesslog_fmt_auth(), and brix_sesslog_fmt_connect().
brix_sesslog_dir_label()
const char * brix_sesslog_dir_label (brix_sess_dir_t d)
Definition at line 274 of file sesslog.c.
References brix_sess_dir_labels, and BRIX_SESS_DIR_OUT.
Referenced by brix_sesslog_fmt_connect().
brix_sesslog_end_label()
const char * brix_sesslog_end_label (brix_sess_end_t e)
Definition at line 310 of file sesslog.c.
References BRIX_SESS_END_ERROR, and brix_sess_end_labels.
Referenced by brix_sesslog_fmt_end().
brix_sesslog_err_from_errno()
const char * brix_sesslog_err_from_errno (int err, char * scratch, size_t n)
Definition at line 132 of file sesslog_err.c.
References brix_sess_err_lookup(), and brix_sess_errno_table.
brix_sesslog_err_from_http()
const char * brix_sesslog_err_from_http (int status, char * scratch, size_t n)
Definition at line 160 of file sesslog_err.c.
References brix_sess_err_lookup(), and brix_sess_http_table.
Referenced by cvmfs_finalize_sesslog(), s3_metrics_response_method(), and webdav_metrics_response().
brix_sesslog_err_from_kxr()
const char * brix_sesslog_err_from_kxr (int kxr, char * scratch, size_t n)
Definition at line 146 of file sesslog_err.c.
References brix_sess_err_lookup(), and brix_sess_kxr_table.
Referenced by brix_access_sess_auth_err(), brix_access_sesslog_namespace(), and tpc_sess_finish_pull().
brix_sesslog_fmt_attempt()
size_t brix_sesslog_fmt_attempt (char * line, size_t line_max, const brix_sess_t * s, const brix_sesslog_attempt_fields_t * f, brix_sess_sanitize_fn san)
Definition at line 366 of file sesslog.c.
References brix_sess_append(), brix_sess_append_quoted(), brix_sess_buf(), brix_sesslog_mode_label(), BRIX_SESSLOG_PATH_MAX, brix_sesslog_attempt_fields_t::mode, brix_sesslog_attempt_fields_t::path, s, and brix_sess_buf_t::used.
Referenced by brix_sess_attempt().
brix_sesslog_fmt_auth()
size_t brix_sesslog_fmt_auth (char * line, size_t line_max, const brix_sess_t * s, const brix_sesslog_auth_fields_t * f, brix_sess_sanitize_fn san)
Definition at line 343 of file sesslog.c.
References brix_sess_append(), brix_sess_append_quoted(), brix_sess_buf(), brix_sesslog_am_label(), BRIX_SESSLOG_ERR_MAX, BRIX_SESSLOG_USER_MAX, BRIX_SESSLOG_VO_MAX, brix_sesslog_auth_fields_t::err, brix_sesslog_auth_fields_t::method, brix_sesslog_auth_fields_t::ok, s, brix_sess_buf_t::used, brix_sesslog_auth_fields_t::user, and brix_sesslog_auth_fields_t::vo.
Referenced by brix_sess_auth().
brix_sesslog_fmt_connect()
size_t brix_sesslog_fmt_connect (char * line, size_t line_max, const brix_sess_t * s, brix_sess_sanitize_fn san)
Definition at line 319 of file sesslog.c.
References brix_sess_append(), brix_sess_append_quoted(), brix_sess_buf(), brix_sesslog_am_label(), brix_sesslog_dir_label(), BRIX_SESSLOG_PEER_MAX, brix_sesslog_proto_label(), s, and brix_sess_buf_t::used.
Referenced by brix_sess_begin().
brix_sesslog_fmt_end()
size_t brix_sesslog_fmt_end (char * line, size_t line_max, const brix_sess_t * s, const brix_sesslog_end_fields_t * f, brix_sess_sanitize_fn san)
Definition at line 440 of file sesslog.c.
References brix_sess_append(), brix_sess_buf(), brix_sess_duration(), brix_sesslog_end_label(), brix_sesslog_end_fields_t::now_msec, s, brix_sess_buf_t::used, and brix_sesslog_end_fields_t::why.
Referenced by brix_sess_end().
brix_sesslog_fmt_result()
size_t brix_sesslog_fmt_result (char * line, size_t line_max, const brix_sess_t * s, const brix_sesslog_result_fields_t * f, brix_sess_sanitize_fn san)
Definition at line 383 of file sesslog.c.
References brix_sess_append(), brix_sess_append_quoted(), brix_sess_buf(), BRIX_SESSLOG_ERR_MAX, brix_sesslog_mode_label(), BRIX_SESSLOG_PATH_MAX, brix_sesslog_result_fields_t::err, brix_sesslog_result_fields_t::mode, brix_sesslog_result_fields_t::ok, brix_sesslog_result_fields_t::path, s, and brix_sess_buf_t::used.
Referenced by brix_sess_result().
brix_sesslog_fmt_xfer()
size_t brix_sesslog_fmt_xfer (char * line, size_t line_max, const brix_sess_t * s, const brix_sesslog_xfer_fields_t * f, brix_sess_sanitize_fn san)
Definition at line 405 of file sesslog.c.
References brix_sess_append(), brix_sess_append_quoted(), brix_sess_buf(), brix_sess_duration(), brix_sess_rate(), brix_sesslog_mode_label(), BRIX_SESSLOG_PENDING_PATH_MAX, brix_sesslog_xfer_label(), brix_sess_xfer_t::bytes, brix_sess_xfer_t::expected, brix_sess_xfer_t::mode, brix_sesslog_xfer_fields_t::now_msec, brix_sess_xfer_t::path, s, brix_sesslog_xfer_fields_t::st, brix_sess_xfer_t::start_msec, brix_sess_buf_t::used, and brix_sesslog_xfer_fields_t::x.
Referenced by brix_sess_xfer_end().
brix_sesslog_mode_label()
const char * brix_sesslog_mode_label (brix_sess_mode_t m)
Definition at line 292 of file sesslog.c.
References brix_sess_mode_labels, and BRIX_SESS_MODE_MAX.
Referenced by brix_sesslog_fmt_attempt(), brix_sesslog_fmt_result(), and brix_sesslog_fmt_xfer().
brix_sesslog_proto_label()
const char * brix_sesslog_proto_label (brix_sess_proto_t p)
Definition at line 265 of file sesslog.c.
References brix_sess_proto_labels, and BRIX_SESS_PROTO_MAX.
Referenced by brix_sesslog_fmt_connect().
brix_sesslog_xfer_label()
const char * brix_sesslog_xfer_label (brix_sess_xfer_status_t st)
Definition at line 301 of file sesslog.c.
References brix_sess_xfer_labels, and BRIX_SESS_XFER_SHUTDOWN.
Referenced by brix_sesslog_fmt_xfer().