nginx-xrootd: src/protocols/ssi/session_unittest.c File Reference
session_unittest.c File Reference
#include "session.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Macros
#define CHECK(cond)
Functions
static void test_create_and_lookup (void)
static void test_lookup_absent (void)
static void test_table_full (void)
static void test_generation_increments (void)
int main (void)
Variables
static int g_fail
Macro Definition Documentation
CHECK
#define CHECK (cond)
Value:
    do { \
    if (!(cond)) { printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
                   g_fail++; } \
} while (0)
Definition at line 14 of file session_unittest.c.
Function Documentation
main()
int main (void)
Definition at line 69 of file session_unittest.c.
References g_fail, test_create_and_lookup(), test_generation_increments(), test_lookup_absent(), and test_table_full().
test_create_and_lookup()
static void test_create_and_lookup (void) static
Definition at line 19 of file session_unittest.c.
References brix_ssi_session_create(), brix_ssi_session_req(), CHECK, brix_ssi_req_t::in_use, brix_ssi_provider_t::process, brix_ssi_session_t::provider, brix_ssi_req_t::req_id, s, and brix_ssi_session_t::service.
Referenced by main().
test_generation_increments()
static void test_generation_increments (void) static
Definition at line 59 of file session_unittest.c.
References brix_ssi_session_create(), CHECK, and brix_ssi_session_t::generation.
Referenced by main().
test_lookup_absent()
static void test_lookup_absent (void) static
Definition at line 38 of file session_unittest.c.
References brix_ssi_session_create(), brix_ssi_session_req(), CHECK, and s.
Referenced by main().
test_table_full()
static void test_table_full (void) static
Definition at line 46 of file session_unittest.c.
References BRIX_SSI_MAX_INFLIGHT, brix_ssi_session_create(), brix_ssi_session_drop(), brix_ssi_session_req(), CHECK, and s.
Referenced by main().
Variable Documentation
g_fail
int g_fail static
Definition at line 13 of file session_unittest.c.
Referenced by main().