nginx-xrootd: src/observability/sesslog/sesslog.c File Reference
sesslog.c File Reference
#include "observability/sesslog/sesslog.h"
#include "protocols/root/protocol/opcodes.h"
#include <errno.h>
#include <stdarg.h>
#include <stdio.h>
#include <string.h>
Data Structures
struct brix_sess_buf_t
struct brix_sess_err_entry_t
Functions
static size_t brix_sess_strnlen_or_dash (const char *s, size_t max)
static size_t brix_sess_default_sanitize (char *dst, size_t dst_size, const char *src, size_t src_len)
static void brix_sess_append (brix_sess_buf_t *b, const char *fmt,...)
static void brix_sess_append_quoted (brix_sess_buf_t *b, const char *key, const char *value, size_t raw_cap, brix_sess_sanitize_fn san)
static brix_sess_buf_t brix_sess_buf (char *line, size_t line_max)
static uint64_t brix_sess_duration (uint64_t start_msec, uint64_t now_msec)
static uint64_t brix_sess_rate (uint64_t bytes, uint64_t dur_ms)
const char * brix_sesslog_proto_label (brix_sess_proto_t p)
const char * brix_sesslog_dir_label (brix_sess_dir_t d)
const char * brix_sesslog_am_label (brix_sess_am_t m)
const char * brix_sesslog_mode_label (brix_sess_mode_t m)
const char * brix_sesslog_xfer_label (brix_sess_xfer_status_t st)
const char * brix_sesslog_end_label (brix_sess_end_t e)
size_t brix_sesslog_fmt_connect (char *line, size_t line_max, const brix_sess_t *s, brix_sess_sanitize_fn san)
size_t brix_sesslog_fmt_auth (char *line, size_t line_max, const brix_sess_t *s, const brix_sesslog_auth_fields_t *f, brix_sess_sanitize_fn san)
size_t brix_sesslog_fmt_attempt (char *line, size_t line_max, const brix_sess_t *s, const brix_sesslog_attempt_fields_t *f, brix_sess_sanitize_fn san)
size_t brix_sesslog_fmt_result (char *line, size_t line_max, const brix_sess_t *s, const brix_sesslog_result_fields_t *f, brix_sess_sanitize_fn san)
size_t brix_sesslog_fmt_xfer (char *line, size_t line_max, const brix_sess_t *s, const brix_sesslog_xfer_fields_t *f, brix_sess_sanitize_fn san)
size_t brix_sesslog_fmt_end (char *line, size_t line_max, const brix_sess_t *s, const brix_sesslog_end_fields_t *f, brix_sess_sanitize_fn san)
static const char * brix_sess_err_lookup (const brix_sess_err_entry_t *table, size_t count, int code, char *scratch, size_t n)
const char * brix_sesslog_err_from_errno (int err, char *scratch, size_t n)
const char * brix_sesslog_err_from_kxr (int kxr, char *scratch, size_t n)
const char * brix_sesslog_err_from_http (int status, char *scratch, size_t n)
Variables
static const char *const brix_sess_proto_labels []
static const char *const brix_sess_dir_labels []
static const char *const brix_sess_am_labels []
static const char *const brix_sess_mode_labels []
static const char *const brix_sess_xfer_labels []
static const char *const brix_sess_end_labels []
static const brix_sess_err_entry_t brix_sess_errno_table []
static const brix_sess_err_entry_t brix_sess_kxr_table []
static const brix_sess_err_entry_t brix_sess_http_table []
Function Documentation
brix_sess_append()
static void brix_sess_append (brix_sess_buf_t * b, const char * fmt, ...) static
Definition at line 123 of file sesslog.c.
References brix_sess_buf_t::pos, brix_sess_buf_t::rem, and brix_sess_buf_t::used.
Referenced by brix_sess_append_quoted(), brix_sesslog_fmt_attempt(), brix_sesslog_fmt_auth(), brix_sesslog_fmt_connect(), brix_sesslog_fmt_end(), brix_sesslog_fmt_result(), and brix_sesslog_fmt_xfer().
brix_sess_append_quoted()
static void brix_sess_append_quoted (brix_sess_buf_t * b, const char * key, const char * value, size_t raw_cap, brix_sess_sanitize_fn san) static
Definition at line 164 of file sesslog.c.
References brix_sess_append(), brix_sess_default_sanitize(), brix_sess_strnlen_or_dash(), BRIX_SESSLOG_PATH_MAX, and key.
Referenced by brix_sesslog_fmt_attempt(), brix_sesslog_fmt_auth(), brix_sesslog_fmt_connect(), brix_sesslog_fmt_result(), and brix_sesslog_fmt_xfer().
brix_sess_buf()
static brix_sess_buf_t brix_sess_buf (char * line, size_t line_max) static
Definition at line 214 of file sesslog.c.
References brix_sess_buf_t::pos, brix_sess_buf_t::rem, and brix_sess_buf_t::used.
Referenced by brix_sesslog_fmt_attempt(), brix_sesslog_fmt_auth(), brix_sesslog_fmt_connect(), brix_sesslog_fmt_end(), brix_sesslog_fmt_result(), and brix_sesslog_fmt_xfer().
brix_sess_default_sanitize()
static size_t brix_sess_default_sanitize (char * dst, size_t dst_size, const char * src, size_t src_len) static
Definition at line 69 of file sesslog.c.
References hex().
Referenced by brix_sess_append_quoted().
brix_sess_duration()
static uint64_t brix_sess_duration (uint64_t start_msec, uint64_t now_msec) static
Definition at line 237 of file sesslog.c.
Referenced by brix_sesslog_fmt_end(), and brix_sesslog_fmt_xfer().
brix_sess_err_lookup()
static const char * brix_sess_err_lookup (const brix_sess_err_entry_t * table, size_t count, int code, char * scratch, size_t n) static
Definition at line 482 of file sesslog.c.
References code, and brix_sess_err_entry_t::token.
Referenced by brix_sesslog_err_from_errno(), brix_sesslog_err_from_http(), and brix_sesslog_err_from_kxr().
brix_sess_rate()
static uint64_t brix_sess_rate (uint64_t bytes, uint64_t dur_ms) static
Definition at line 253 of file sesslog.c.
Referenced by brix_sesslog_fmt_xfer().
brix_sess_strnlen_or_dash()
static size_t brix_sess_strnlen_or_dash (const char * s, size_t max) static
Definition at line 47 of file sesslog.c.
References s.
Referenced by brix_sess_append_quoted().
brix_sesslog_am_label()
const char * brix_sesslog_am_label (brix_sess_am_t m)
Definition at line 283 of file sesslog.c.
References brix_sess_am_labels, and BRIX_SESS_AM_MAX.
Referenced by brix_sesslog_fmt_auth(), and brix_sesslog_fmt_connect().
brix_sesslog_dir_label()
const char * brix_sesslog_dir_label (brix_sess_dir_t d)
Definition at line 274 of file sesslog.c.
References brix_sess_dir_labels, and BRIX_SESS_DIR_OUT.
Referenced by brix_sesslog_fmt_connect().
brix_sesslog_end_label()
const char * brix_sesslog_end_label (brix_sess_end_t e)
Definition at line 310 of file sesslog.c.
References BRIX_SESS_END_ERROR, and brix_sess_end_labels.
Referenced by brix_sesslog_fmt_end().
brix_sesslog_err_from_errno()
const char * brix_sesslog_err_from_errno (int err, char * scratch, size_t n)
Definition at line 583 of file sesslog.c.
References brix_sess_err_lookup(), and brix_sess_errno_table.
brix_sesslog_err_from_http()
const char * brix_sesslog_err_from_http (int status, char * scratch, size_t n)
Definition at line 611 of file sesslog.c.
References brix_sess_err_lookup(), and brix_sess_http_table.
Referenced by cvmfs_finalize_sesslog(), s3_metrics_response_method(), and webdav_metrics_response().
brix_sesslog_err_from_kxr()
const char * brix_sesslog_err_from_kxr (int kxr, char * scratch, size_t n)
Definition at line 597 of file sesslog.c.
References brix_sess_err_lookup(), and brix_sess_kxr_table.
Referenced by brix_access_sess_auth_err(), brix_access_sesslog_namespace(), and tpc_sess_finish_pull().
brix_sesslog_fmt_attempt()
size_t brix_sesslog_fmt_attempt (char * line, size_t line_max, const brix_sess_t * s, const brix_sesslog_attempt_fields_t * f, brix_sess_sanitize_fn san)
Definition at line 366 of file sesslog.c.
References brix_sess_append(), brix_sess_append_quoted(), brix_sess_buf(), brix_sesslog_mode_label(), BRIX_SESSLOG_PATH_MAX, brix_sesslog_attempt_fields_t::mode, brix_sesslog_attempt_fields_t::path, s, and brix_sess_buf_t::used.
Referenced by brix_sess_attempt().
brix_sesslog_fmt_auth()
size_t brix_sesslog_fmt_auth (char * line, size_t line_max, const brix_sess_t * s, const brix_sesslog_auth_fields_t * f, brix_sess_sanitize_fn san)
Definition at line 343 of file sesslog.c.
References brix_sess_append(), brix_sess_append_quoted(), brix_sess_buf(), brix_sesslog_am_label(), BRIX_SESSLOG_ERR_MAX, BRIX_SESSLOG_USER_MAX, BRIX_SESSLOG_VO_MAX, brix_sesslog_auth_fields_t::err, brix_sesslog_auth_fields_t::method, brix_sesslog_auth_fields_t::ok, s, brix_sess_buf_t::used, brix_sesslog_auth_fields_t::user, and brix_sesslog_auth_fields_t::vo.
Referenced by brix_sess_auth().
brix_sesslog_fmt_connect()
size_t brix_sesslog_fmt_connect (char * line, size_t line_max, const brix_sess_t * s, brix_sess_sanitize_fn san)
Definition at line 319 of file sesslog.c.
References brix_sess_append(), brix_sess_append_quoted(), brix_sess_buf(), brix_sesslog_am_label(), brix_sesslog_dir_label(), BRIX_SESSLOG_PEER_MAX, brix_sesslog_proto_label(), s, and brix_sess_buf_t::used.
Referenced by brix_sess_begin().
brix_sesslog_fmt_end()
size_t brix_sesslog_fmt_end (char * line, size_t line_max, const brix_sess_t * s, const brix_sesslog_end_fields_t * f, brix_sess_sanitize_fn san)
Definition at line 440 of file sesslog.c.
References brix_sess_append(), brix_sess_buf(), brix_sess_duration(), brix_sesslog_end_label(), brix_sesslog_end_fields_t::now_msec, s, brix_sess_buf_t::used, and brix_sesslog_end_fields_t::why.
Referenced by brix_sess_end().
brix_sesslog_fmt_result()
size_t brix_sesslog_fmt_result (char * line, size_t line_max, const brix_sess_t * s, const brix_sesslog_result_fields_t * f, brix_sess_sanitize_fn san)
Definition at line 383 of file sesslog.c.
References brix_sess_append(), brix_sess_append_quoted(), brix_sess_buf(), BRIX_SESSLOG_ERR_MAX, brix_sesslog_mode_label(), BRIX_SESSLOG_PATH_MAX, brix_sesslog_result_fields_t::err, brix_sesslog_result_fields_t::mode, brix_sesslog_result_fields_t::ok, brix_sesslog_result_fields_t::path, s, and brix_sess_buf_t::used.
Referenced by brix_sess_result().
brix_sesslog_fmt_xfer()
size_t brix_sesslog_fmt_xfer (char * line, size_t line_max, const brix_sess_t * s, const brix_sesslog_xfer_fields_t * f, brix_sess_sanitize_fn san)
Definition at line 405 of file sesslog.c.
References brix_sess_append(), brix_sess_append_quoted(), brix_sess_buf(), brix_sess_duration(), brix_sess_rate(), brix_sesslog_mode_label(), BRIX_SESSLOG_PENDING_PATH_MAX, brix_sesslog_xfer_label(), brix_sess_xfer_t::bytes, brix_sess_xfer_t::expected, brix_sess_xfer_t::mode, brix_sesslog_xfer_fields_t::now_msec, brix_sess_xfer_t::path, s, brix_sesslog_xfer_fields_t::st, brix_sess_xfer_t::start_msec, brix_sess_buf_t::used, and brix_sesslog_xfer_fields_t::x.
Referenced by brix_sess_xfer_end().
brix_sesslog_mode_label()
const char * brix_sesslog_mode_label (brix_sess_mode_t m)
Definition at line 292 of file sesslog.c.
References brix_sess_mode_labels, and BRIX_SESS_MODE_MAX.
Referenced by brix_sesslog_fmt_attempt(), brix_sesslog_fmt_result(), and brix_sesslog_fmt_xfer().
brix_sesslog_proto_label()
const char * brix_sesslog_proto_label (brix_sess_proto_t p)
Definition at line 265 of file sesslog.c.
References brix_sess_proto_labels, and BRIX_SESS_PROTO_MAX.
Referenced by brix_sesslog_fmt_connect().
brix_sesslog_xfer_label()
const char * brix_sesslog_xfer_label (brix_sess_xfer_status_t st)
Definition at line 301 of file sesslog.c.
References brix_sess_xfer_labels, and BRIX_SESS_XFER_SHUTDOWN.
Referenced by brix_sesslog_fmt_xfer().
Variable Documentation
brix_sess_am_labels
const char* const brix_sess_am_labels[] static
Initial value:
= {
    "gsi", "token", "sss", "krb5", "pwd", "unix", "host", "sigv4",
    "anon"
}
Definition at line 23 of file sesslog.c.
Referenced by brix_sesslog_am_label().
brix_sess_dir_labels
const char* const brix_sess_dir_labels[] static
Initial value:
= {
    "in", "out"
}
Definition at line 19 of file sesslog.c.
Referenced by brix_sesslog_dir_label().
brix_sess_end_labels
const char* const brix_sess_end_labels[] static
Initial value:
= {
    "client-disconnect", "server-close", "timeout", "shutdown", "error"
}
Definition at line 36 of file sesslog.c.
Referenced by brix_sesslog_end_label().
brix_sess_errno_table
const brix_sess_err_entry_t brix_sess_errno_table[] static
Initial value:
= {
    { ENOENT,       "not-found" },
    { ENOTDIR,      "not-found" },
    { EACCES,       "permission" },
    { EPERM,        "permission" },
    { EINVAL,       "invalid" },
    { ENAMETOOLONG, "invalid" },
    { EIO,          "io" },
    { ENOMEM,       "no-memory" },
    { ENOSPC,       "no-space" },
    { EEXIST,       "exists" },
    { EBUSY,        "busy" },
    { ETIMEDOUT,    "timeout" },
}
Definition at line 506 of file sesslog.c.
Referenced by brix_sesslog_err_from_errno().
brix_sess_http_table
const brix_sess_err_entry_t brix_sess_http_table[] static
Initial value:
= {
    { 400, "invalid" },
    { 401, "auth-required" },
    { 403, "permission" },
    { 404, "not-found" },
    { 405, "unsupported" },
    { 501, "unsupported" },
    { 409, "exists" },
    { 412, "exists" },
    { 423, "locked" },
    { 500, "io" },
    { 502, "io" },
    { 503, "busy" },
    { 504, "timeout" },
    { 507, "no-space" },
}
Definition at line 559 of file sesslog.c.
Referenced by brix_sesslog_err_from_http().
brix_sess_kxr_table
const brix_sess_err_entry_t brix_sess_kxr_table[] static
Initial value:
= {
    {  3011  ,       "not-found" },
    {  3015  ,        "not-found" },
    {  3016  ,    "not-found" },
    {  3027  ,   "not-found" },
    {  3010  ,  "permission" },
    {  3025  ,     "permission" },
    {  3000  ,     "invalid" },
    {  3001  ,     "invalid" },
    {  3002  ,     "invalid" },
    {  3032  ,       "invalid" },
    {  3031  ,     "invalid" },
    {  3007  ,        "io" },
    {  3005  ,        "io" },
    {  3012  ,    "io" },
    {  3019  ,      "io" },
    {  3008  ,       "no-memory" },
    {  3009  ,        "no-space" },
    {  3021  ,      "no-space" },
    {  3003  ,     "locked" },
    {  3006  , "exists" },
    {  3018  ,       "exists" },
    {  3020  ,     "busy" },
    {  3024  ,     "busy" },
    {  3013  ,    "unsupported" },
    {  3028  ,    "auth-required" },
    {  3030  ,     "bad-signature" },
    {  3017  ,      "session-closed" },
}
Definition at line 528 of file sesslog.c.
Referenced by brix_sesslog_err_from_kxr().
brix_sess_mode_labels
const char* const brix_sess_mode_labels[] static
Initial value:
= {
    "read", "write", "meta", "delete", "list", "copy"
}
Definition at line 28 of file sesslog.c.
Referenced by brix_sesslog_mode_label().
brix_sess_proto_labels
const char* const brix_sess_proto_labels[] static
Initial value:
= {
    "root", "webdav", "s3", "cvmfs", "cms", "tpc", "fill"
}
Definition at line 15 of file sesslog.c.
Referenced by brix_sesslog_proto_label().
brix_sess_xfer_labels
const char* const brix_sess_xfer_labels[] static
Initial value:
= {
    "complete", "aborted", "shutdown"
}
Definition at line 32 of file sesslog.c.
Referenced by brix_sesslog_xfer_label().