nginx-xrootd: src/observability/sesslog/sesslog_ngx.h File Reference
sesslog_ngx.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include "observability/sesslog/sesslog.h"
Macros
#define BRIX_SESSLOG_REGISTRY_SLOTS 4096
Functions
brix_sess_t * brix_sess_begin (ngx_uint_t enabled, ngx_fd_t log_fd, brix_sess_proto_t proto, brix_sess_dir_t dir, const char *peer, size_t peer_len, brix_sess_am_t am, const brix_sess_t *parent)
void brix_sess_auth (brix_sess_t *s, int ok, brix_sess_am_t m, const char *user, const char *vo, const char *err)
void brix_sess_auth_once (brix_sess_t *s, brix_sess_am_t m, const char *user, const char *vo)
void brix_sess_attempt (brix_sess_t *s, const char *path, brix_sess_mode_t mode)
void brix_sess_result (brix_sess_t *s, int ok, const char *path, brix_sess_mode_t mode, const char *err)
void brix_sess_xfer_start (brix_sess_t *s, brix_sess_xfer_t *x, const char *path, brix_sess_mode_t mode, int64_t expected)
void brix_sess_xfer_add (brix_sess_xfer_t *x, uint64_t n)
void brix_sess_xfer_end (brix_sess_t *s, brix_sess_xfer_t *x, brix_sess_xfer_status_t st)
void brix_sess_end (brix_sess_t *s, brix_sess_end_t why)
void brix_sesslog_shutdown_flush (void)
brix_sess_am_t brix_sess_am_from_stream_auth (ngx_uint_t auth)
const char * brix_sess_id (const brix_sess_t *s)
Macro Definition Documentation
BRIX_SESSLOG_REGISTRY_SLOTS
#define BRIX_SESSLOG_REGISTRY_SLOTS 4096
Definition at line 9 of file sesslog_ngx.h.
Function Documentation
brix_sess_am_from_stream_auth()
brix_sess_am_t brix_sess_am_from_stream_auth (ngx_uint_t auth)
Definition at line 482 of file sesslog_ngx.c.
References BRIX_AUTH_BOTH, BRIX_AUTH_GSI, BRIX_AUTH_HOST, BRIX_AUTH_KRB5, BRIX_AUTH_PWD, BRIX_AUTH_SSS, BRIX_AUTH_TOKEN, BRIX_AUTH_UNIX, BRIX_SESS_AM_ANON, BRIX_SESS_AM_GSI, BRIX_SESS_AM_HOST, BRIX_SESS_AM_KRB5, BRIX_SESS_AM_PWD, BRIX_SESS_AM_SSS, BRIX_SESS_AM_TOKEN, and BRIX_SESS_AM_UNIX.
Referenced by brix_access_sess_auth_method(), and ngx_stream_brix_handler().
brix_sess_attempt()
void brix_sess_attempt (brix_sess_t * s, const char * path, brix_sess_mode_t mode)
Definition at line 327 of file sesslog_ngx.c.
References brix_sess_copy_value(), brix_sess_emit(), brix_sess_ngx_strnlen_or_dash(), brix_sess_result(), brix_sess_sanitize_ngx(), brix_sesslog_fmt_attempt(), BRIX_SESSLOG_LINE_MAX, BRIX_SESSLOG_PENDING_PATH_MAX, mode, and s.
Referenced by brix_access_maybe_sesslog(), cms_srv_log_registration(), ngx_brix_cms_log_registration(), ngx_http_brix_cvmfs_handler(), s3_sess_attempt_request(), tpc_sess_begin_pull(), and webdav_sess_attempt_request().
brix_sess_auth()
void brix_sess_auth (brix_sess_t * s, int ok, brix_sess_am_t m, const char * user, const char * vo, const char * err)
Definition at line 279 of file sesslog_ngx.c.
References brix_sess_copy_value(), brix_sess_emit(), brix_sess_ngx_strnlen_or_dash(), brix_sess_sanitize_ngx(), brix_sesslog_fmt_auth(), BRIX_SESSLOG_LINE_MAX, BRIX_SESSLOG_USER_MAX, and s.
Referenced by brix_access_maybe_sesslog(), brix_sess_auth_once(), and cms_srv_log_auth_fail().
brix_sess_auth_once()
void brix_sess_auth_once (brix_sess_t * s, brix_sess_am_t m, const char * user, const char * vo)
Definition at line 305 of file sesslog_ngx.c.
References brix_sess_auth(), brix_sess_copy_value(), brix_sess_ngx_strnlen_or_dash(), BRIX_SESSLOG_USER_MAX, and s.
Referenced by brix_handle_login(), cms_srv_log_registration(), ngx_brix_cms_log_registration(), ngx_http_brix_cvmfs_handler(), s3_sess_begin_request(), tpc_sess_begin_pull(), and webdav_sess_begin_request().
brix_sess_begin()
brix_sess_t * brix_sess_begin (ngx_uint_t enabled, ngx_fd_t log_fd, brix_sess_proto_t proto, brix_sess_dir_t dir, const char * peer, size_t peer_len, brix_sess_am_t am, const brix_sess_t * parent)
Definition at line 242 of file sesslog_ngx.c.
References brix_sess_alloc(), brix_sess_copy_value(), brix_sess_emit(), brix_sess_mint_id(), brix_sess_sanitize_ngx(), brix_sesslog_fmt_connect(), BRIX_SESSLOG_ID_LEN, BRIX_SESSLOG_LINE_MAX, brix_sess_t::id, and s.
Referenced by brix_cms_srv_handler(), brix_http_sess(), ngx_brix_cms_sess_begin(), ngx_stream_brix_handler(), and tpc_sess_begin_pull().
brix_sess_end()
void brix_sess_end (brix_sess_t * s, brix_sess_end_t why)
Definition at line 435 of file sesslog_ngx.c.
References brix_sess_emit(), BRIX_SESS_END_SHUTDOWN, brix_sess_release(), brix_sess_result(), brix_sess_sanitize_ngx(), BRIX_SESS_XFER_ABORTED, brix_sess_xfer_end(), BRIX_SESS_XFER_SHUTDOWN, brix_sesslog_fmt_end(), BRIX_SESSLOG_LINE_MAX, and s.
Referenced by brix_cms_srv_close(), brix_http_sess(), brix_http_sess_cleanup(), brix_on_disconnect(), brix_sesslog_shutdown_flush(), ngx_brix_cms_disconnect(), tpc_sess_abort_pull(), and tpc_sess_finish_pull().
brix_sess_id()
const char * brix_sess_id (const brix_sess_t * s)
Definition at line 506 of file sesslog_ngx.c.
References s.
brix_sess_result()
void brix_sess_result (brix_sess_t * s, int ok, const char * path, brix_sess_mode_t mode, const char * err)
Definition at line 353 of file sesslog_ngx.c.
References brix_sess_emit(), brix_sess_sanitize_ngx(), brix_sesslog_fmt_result(), BRIX_SESSLOG_LINE_MAX, mode, and s.
Referenced by brix_access_maybe_sesslog(), brix_sess_attempt(), brix_sess_end(), cms_srv_log_registration(), cvmfs_finalize_observe(), ngx_brix_cms_log_registration(), s3_metrics_response_method(), tpc_sess_abort_pull(), tpc_sess_finish_pull(), and webdav_metrics_response().
brix_sess_xfer_add()
void brix_sess_xfer_add (brix_sess_xfer_t * x, uint64_t n)
Definition at line 399 of file sesslog_ngx.c.
References brix_sess_xfer_t::active, and brix_sess_xfer_t::bytes.
Referenced by brix_close_finish_sess_xfer(), brix_disconnect_log_open_files(), cvmfs_finalize_observe(), s3_sess_finish_xfer(), tpc_sess_finish_pull(), webdav_sess_finish_xfer(), and webdav_tpc_note_client_copy_xfer().
brix_sess_xfer_end()
void brix_sess_xfer_end (brix_sess_t * s, brix_sess_xfer_t * x, brix_sess_xfer_status_t st)
Definition at line 408 of file sesslog_ngx.c.
References brix_sess_xfer_t::active, brix_sess_emit(), brix_sess_sanitize_ngx(), brix_sesslog_fmt_xfer(), BRIX_SESSLOG_LINE_MAX, brix_sess_xfer_t::next, brix_sess_xfer_t::prevp, and s.
Referenced by brix_close_finish_sess_xfer(), brix_disconnect_log_open_files(), brix_sess_end(), cvmfs_finalize_observe(), s3_sess_finish_xfer(), tpc_sess_abort_pull(), tpc_sess_finish_pull(), and webdav_sess_finish_xfer().
brix_sess_xfer_start()
void brix_sess_xfer_start (brix_sess_t * s, brix_sess_xfer_t * x, const char * path, brix_sess_mode_t mode, int64_t expected)
Definition at line 375 of file sesslog_ngx.c.
References brix_sess_xfer_t::active, brix_sess_copy_value(), brix_sess_ngx_strnlen_or_dash(), BRIX_SESSLOG_PENDING_PATH_MAX, brix_sess_xfer_t::expected, mode, brix_sess_xfer_t::mode, brix_sess_xfer_t::next, brix_sess_xfer_t::path, brix_sess_xfer_t::prevp, s, and brix_sess_xfer_t::start_msec.
Referenced by brix_open_resolved_file(), ngx_http_brix_cvmfs_handler(), s3_sess_start_xfer(), tpc_sess_begin_pull(), and webdav_sess_start_xfer().
brix_sesslog_shutdown_flush()
void brix_sesslog_shutdown_flush (void)
Definition at line 465 of file sesslog_ngx.c.
References brix_access_log_flush(), brix_sess_end(), BRIX_SESS_END_SHUTDOWN, brix_sess_registry, brix_sess_registry_init(), BRIX_SESSLOG_REGISTRY_SLOTS, and in_use.
Referenced by brix_exit_process().