nginx-xrootd: src/observability/sesslog/sesslog_err.c File Reference
sesslog_err.c File Reference
#include "observability/sesslog/sesslog.h"
#include "protocols/root/protocol/opcodes.h"
#include <errno.h>
#include <stdio.h>
Data Structures
struct brix_sess_err_entry_t
Functions
static const char * brix_sess_err_lookup (const brix_sess_err_entry_t *table, size_t count, int code, char *scratch, size_t n)
const char * brix_sesslog_err_from_errno (int err, char *scratch, size_t n)
const char * brix_sesslog_err_from_kxr (int kxr, char *scratch, size_t n)
const char * brix_sesslog_err_from_http (int status, char *scratch, size_t n)
Variables
static const brix_sess_err_entry_t brix_sess_errno_table []
static const brix_sess_err_entry_t brix_sess_kxr_table []
static const brix_sess_err_entry_t brix_sess_http_table []
Function Documentation
brix_sess_err_lookup()
static const char * brix_sess_err_lookup (const brix_sess_err_entry_t * table, size_t count, int code, char * scratch, size_t n) static
Definition at line 31 of file sesslog_err.c.
References code, and brix_sess_err_entry_t::token.
Referenced by brix_sesslog_err_from_errno(), brix_sesslog_err_from_http(), and brix_sesslog_err_from_kxr().
brix_sesslog_err_from_errno()
const char * brix_sesslog_err_from_errno (int err, char * scratch, size_t n)
Definition at line 132 of file sesslog_err.c.
References brix_sess_err_lookup(), and brix_sess_errno_table.
brix_sesslog_err_from_http()
const char * brix_sesslog_err_from_http (int status, char * scratch, size_t n)
Definition at line 160 of file sesslog_err.c.
References brix_sess_err_lookup(), and brix_sess_http_table.
Referenced by cvmfs_finalize_sesslog(), s3_metrics_response_method(), and webdav_metrics_response().
brix_sesslog_err_from_kxr()
const char * brix_sesslog_err_from_kxr (int kxr, char * scratch, size_t n)
Definition at line 146 of file sesslog_err.c.
References brix_sess_err_lookup(), and brix_sess_kxr_table.
Referenced by brix_access_sess_auth_err(), brix_access_sesslog_namespace(), and tpc_sess_finish_pull().
Variable Documentation
brix_sess_errno_table
const brix_sess_err_entry_t brix_sess_errno_table[] static
Initial value:
= {
    { ENOENT,       "not-found" },
    { ENOTDIR,      "not-found" },
    { EACCES,       "permission" },
    { EPERM,        "permission" },
    { EINVAL,       "invalid" },
    { ENAMETOOLONG, "invalid" },
    { EIO,          "io" },
    { ENOMEM,       "no-memory" },
    { ENOSPC,       "no-space" },
    { EEXIST,       "exists" },
    { EBUSY,        "busy" },
    { ETIMEDOUT,    "timeout" },
}
Definition at line 55 of file sesslog_err.c.
Referenced by brix_sesslog_err_from_errno().
brix_sess_http_table
const brix_sess_err_entry_t brix_sess_http_table[] static
Initial value:
= {
    { 400, "invalid" },
    { 401, "auth-required" },
    { 403, "permission" },
    { 404, "not-found" },
    { 405, "unsupported" },
    { 501, "unsupported" },
    { 409, "exists" },
    { 412, "exists" },
    { 423, "locked" },
    { 500, "io" },
    { 502, "io" },
    { 503, "busy" },
    { 504, "timeout" },
    { 507, "no-space" },
}
Definition at line 108 of file sesslog_err.c.
Referenced by brix_sesslog_err_from_http().
brix_sess_kxr_table
const brix_sess_err_entry_t brix_sess_kxr_table[] static
Initial value:
= {
    {  3011  ,       "not-found" },
    {  3015  ,        "not-found" },
    {  3016  ,    "not-found" },
    {  3027  ,   "not-found" },
    {  3010  ,  "permission" },
    {  3025  ,     "permission" },
    {  3000  ,     "invalid" },
    {  3001  ,     "invalid" },
    {  3002  ,     "invalid" },
    {  3032  ,       "invalid" },
    {  3031  ,     "invalid" },
    {  3007  ,        "io" },
    {  3005  ,        "io" },
    {  3012  ,    "io" },
    {  3019  ,      "io" },
    {  3008  ,       "no-memory" },
    {  3009  ,        "no-space" },
    {  3021  ,      "no-space" },
    {  3003  ,     "locked" },
    {  3006  , "exists" },
    {  3018  ,       "exists" },
    {  3020  ,     "busy" },
    {  3024  ,     "busy" },
    {  3013  ,    "unsupported" },
    {  3028  ,    "auth-required" },
    {  3030  ,     "bad-signature" },
    {  3017  ,      "session-closed" },
}
Definition at line 77 of file sesslog_err.c.
Referenced by brix_sesslog_err_from_kxr().