nginx-xrootd: src/protocols/shared/protocol.c File Reference
protocol.c File Reference
#include "protocols/shared/protocol.h"
#include "protocols/webdav/webdav.h"
#include "protocols/s3/s3.h"
#include "protocols/cvmfs/cvmfs.h"
Macros
#define BRIX_PROTOCOL_MAX 8
Functions
static ngx_flag_t proto_webdav_enabled (void **loc_conf)
static ngx_flag_t proto_s3_enabled (void **loc_conf)
static ngx_flag_t proto_cvmfs_enabled (void **loc_conf)
ngx_int_t brix_protocol_register (const brix_protocol_t *p)
const brix_protocol_t * brix_protocol_find (const char *name)
ngx_uint_t brix_protocol_count_get (void)
const brix_protocol_t * brix_protocol_at (ngx_uint_t i)
void brix_protocol_register_all (void)
Variables
static const brix_protocol_t * brix_protocols [8]
static ngx_uint_t brix_protocol_count
static const brix_protocol_t brix_proto_root
static const brix_protocol_t brix_proto_s3
static const brix_protocol_t brix_proto_webdav
static const brix_protocol_t brix_proto_cvmfs
Macro Definition Documentation
BRIX_PROTOCOL_MAX
#define BRIX_PROTOCOL_MAX 8
Definition at line 36 of file protocol.c.
Function Documentation
brix_protocol_at()
const brix_protocol_t * brix_protocol_at (ngx_uint_t i)
Definition at line 93 of file protocol.c.
References brix_protocol_count, and brix_protocols.
Referenced by brix_proto_mask(), and brix_proto_name().
brix_protocol_count_get()
ngx_uint_t brix_protocol_count_get (void)
Definition at line 87 of file protocol.c.
References brix_protocol_count.
Referenced by brix_proto_mask(), and brix_proto_name().
brix_protocol_find()
const brix_protocol_t * brix_protocol_find (const char * name)
Definition at line 71 of file protocol.c.
References brix_protocol_count, brix_protocols, and name.
brix_protocol_register()
ngx_int_t brix_protocol_register (const brix_protocol_t * p)
Definition at line 51 of file protocol.c.
References brix_protocol_count, BRIX_PROTOCOL_MAX, brix_protocols, brix_protocol_t::name, and name.
Referenced by brix_protocol_register_all().
brix_protocol_register_all()
void brix_protocol_register_all (void)
Definition at line 99 of file protocol.c.
References brix_proto_cvmfs, brix_proto_root, brix_proto_s3, brix_proto_webdav, and brix_protocol_register().
Referenced by ngx_http_brix_webdav_postconfiguration().
proto_cvmfs_enabled()
static ngx_flag_t proto_cvmfs_enabled (void ** loc_conf) static
Definition at line 22 of file protocol.c.
References c, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, brix_cvmfs_conf_t::enable, and ngx_http_brix_cvmfs_module.
proto_s3_enabled()
static ngx_flag_t proto_s3_enabled (void ** loc_conf) static
Definition at line 16 of file protocol.c.
References ngx_http_brix_s3_module, and s.
proto_webdav_enabled()
static ngx_flag_t proto_webdav_enabled (void ** loc_conf) static
Definition at line 9 of file protocol.c.
References ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::enable, and ngx_http_brix_webdav_module.
Variable Documentation
brix_proto_cvmfs
const brix_protocol_t brix_proto_cvmfs static
Initial value:
=
    { "cvmfs",  BRIX_PROTO_FAMILY_HTTP,   "brix_cvmfs",  proto_cvmfs_enabled }
Definition at line 47 of file protocol.c.
Referenced by brix_protocol_register_all().
brix_proto_root
const brix_protocol_t brix_proto_root static
Initial value:
=
    { "root",   BRIX_PROTO_FAMILY_STREAM, "brix",        NULL }
Definition at line 41 of file protocol.c.
Referenced by brix_protocol_register_all().
brix_proto_s3
const brix_protocol_t brix_proto_s3 static
Initial value:
=
    { "s3",     BRIX_PROTO_FAMILY_HTTP,   "brix_s3",     proto_s3_enabled }
Definition at line 43 of file protocol.c.
Referenced by brix_protocol_register_all().
brix_proto_webdav
const brix_protocol_t brix_proto_webdav static
Initial value:
=
    { "webdav", BRIX_PROTO_FAMILY_HTTP,   "brix_webdav", proto_webdav_enabled }
Definition at line 45 of file protocol.c.
Referenced by brix_protocol_register_all().
brix_protocol_count
ngx_uint_t brix_protocol_count static
Definition at line 39 of file protocol.c.
Referenced by brix_protocol_at(), brix_protocol_count_get(), brix_protocol_find(), and brix_protocol_register().
brix_protocols
const brix_protocol_t* brix_protocols[8] static
Definition at line 38 of file protocol.c.
Referenced by brix_protocol_at(), brix_protocol_find(), and brix_protocol_register().