nginx-xrootd: src/core/config/shared_conf.h File Reference
shared_conf.h File Reference
#include <ngx_thread_pool.h>
#include <regex.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include "observability/pmark/pmark.h"
Data Structures
struct ngx_http_brix_shared_conf_t
Macros
#define BRIX_CREDENTIAL_DIR_DEFAULT "/dev/shm/brix-creds"
Functions
static void ngx_http_brix_shared_init (ngx_http_brix_shared_conf_t *conf)
static void brix_shared_apply_read_only (ngx_http_brix_shared_conf_t *common, ngx_log_t *log)
ngx_int_t brix_imp_worker_runtime_ids (ngx_uid_t conf_uid, ngx_gid_t conf_gid, uid_t *uid_out, gid_t *gid_out)
static void brix_shared_worker_dir_ids (ngx_conf_t *cf, uid_t *uid_out, gid_t *gid_out)
static void brix_shared_credential_dir_ensure (ngx_conf_t *cf, const ngx_str_t *dir)
static ngx_int_t brix_shared_security_gate (ngx_conf_t *cf, ngx_flag_t strict, const char *what, const char *remedy)
static char * ngx_http_brix_shared_merge (ngx_conf_t *cf, ngx_http_brix_shared_conf_t *prev, ngx_http_brix_shared_conf_t *conf, const char *root_default)
static ngx_fd_t brix_http_shared_access_log_fd (const ngx_http_brix_shared_conf_t *conf)
ngx_int_t brix_tier_register_stores (ngx_conf_t *cf, ngx_http_brix_shared_conf_t *common)
void brix_storage_backend_posix_root (ngx_http_brix_shared_conf_t *common)
int brix_storage_backend_is_remote (const ngx_http_brix_shared_conf_t *common)
char * brix_conf_set_store_slot (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Macro Definition Documentation
BRIX_CREDENTIAL_DIR_DEFAULT
#define BRIX_CREDENTIAL_DIR_DEFAULT "/dev/shm/brix-creds"
Definition at line 24 of file shared_conf.h.
Function Documentation
brix_conf_set_store_slot()
char * brix_conf_set_store_slot (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 47 of file runtime_server_backend.c.
brix_http_shared_access_log_fd()
static ngx_fd_t brix_http_shared_access_log_fd (const ngx_http_brix_shared_conf_t * conf) inline static
Definition at line 696 of file shared_conf.h.
References ngx_http_brix_shared_conf_t::access_log_file.
Referenced by brix_http_sess().
brix_imp_worker_runtime_ids()
ngx_int_t brix_imp_worker_runtime_ids (ngx_uid_t conf_uid, ngx_gid_t conf_gid, uid_t * uid_out, gid_t * gid_out)
Definition at line 170 of file lifecycle_worker.c.
Referenced by brix_shared_worker_dir_ids().
brix_shared_apply_read_only()
static void brix_shared_apply_read_only (ngx_http_brix_shared_conf_t * common, ngx_log_t * log) inline static
Definition at line 378 of file shared_conf.h.
References ngx_http_brix_shared_conf_t::allow_write, log, and ngx_http_brix_shared_conf_t::read_only.
Referenced by brix_config_prepare_server(), and ngx_http_brix_shared_merge().
brix_shared_credential_dir_ensure()
static void brix_shared_credential_dir_ensure (ngx_conf_t * cf, const ngx_str_t * dir) inline static
Definition at line 442 of file shared_conf.h.
References brix_shared_worker_dir_ids(), and stat().
Referenced by ngx_http_brix_shared_merge().
brix_shared_security_gate()
static ngx_int_t brix_shared_security_gate (ngx_conf_t * cf, ngx_flag_t strict, const char * what, const char * remedy) inline static
Definition at line 537 of file shared_conf.h.
Referenced by ngx_http_brix_dashboard_merge_loc_conf(), ngx_http_s3_merge_loc_conf(), and webdav_validate_auth_paths().
brix_shared_worker_dir_ids()
static void brix_shared_worker_dir_ids (ngx_conf_t * cf, uid_t * uid_out, gid_t * gid_out) inline static
Definition at line 425 of file shared_conf.h.
References brix_imp_worker_runtime_ids().
Referenced by brix_shared_credential_dir_ensure(), and brix_tier_default_stage_store().
brix_storage_backend_is_remote()
int brix_storage_backend_is_remote (const ngx_http_brix_shared_conf_t * common)
Definition at line 162 of file runtime_server_backend.c.
References ngx_http_brix_shared_conf_t::storage_backend.
Referenced by brix_server_guard_remote_authz(), brix_server_setup_export(), s3_merge_export(), and webdav_prepare_export_root().
brix_storage_backend_posix_root()
void brix_storage_backend_posix_root (ngx_http_brix_shared_conf_t * common)
Definition at line 87 of file runtime_server_backend.c.
References brix_mkdir_recursive(), brix_pblock_write_opts_sidecar(), ngx_http_brix_shared_conf_t::root, and ngx_http_brix_shared_conf_t::storage_backend.
Referenced by brix_server_setup_export(), cvmfs_merge_cache(), s3_merge_export(), and webdav_prepare_export_root().
brix_tier_register_stores()
ngx_int_t brix_tier_register_stores (ngx_conf_t * cf, ngx_http_brix_shared_conf_t * common)
Definition at line 692 of file runtime_server_backend.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_storage_backend_is_whole_object(), brix_tier_default_stage_store(), brix_tier_parse_store(), brix_tier_register_cache_store(), BRIX_TIER_STAGE, brix_tier_warn_private_tmp(), brix_vfs_backend_config_stage_store(), BRIX_WT_MODE_ASYNC, BRIX_WT_MODE_SYNC, ngx_http_brix_shared_conf_t::cache_cold_store, ngx_http_brix_shared_conf_t::cache_peers, ngx_http_brix_shared_conf_t::cache_store, brix_stage_policy_t::enabled, brix_stage_policy_t::flush_mode, ngx_http_brix_shared_conf_t::root_canon, ngx_http_brix_shared_conf_t::stage_enable, ngx_http_brix_shared_conf_t::stage_flush_async, ngx_http_brix_shared_conf_t::stage_store, ngx_http_brix_shared_conf_t::stage_store_args, and ngx_http_brix_shared_conf_t::storage_backend.
Referenced by brix_server_setup_export(), cvmfs_merge_cache(), s3_merge_export(), and webdav_validate_webdav_enabled().
ngx_http_brix_shared_init()
static void ngx_http_brix_shared_init (ngx_http_brix_shared_conf_t * conf) inline static
Definition at line 294 of file shared_conf.h.
References ngx_http_brix_shared_conf_t::access_log, ngx_http_brix_shared_conf_t::access_log_file, ngx_http_brix_shared_conf_t::allow_write, ngx_http_brix_shared_conf_t::backend_delegation, ngx_http_brix_shared_conf_t::backend_krb5_forwardable, ngx_http_brix_shared_conf_t::backend_passthrough_persist, ngx_http_brix_shared_conf_t::backend_sts_endpoint, ngx_http_brix_shared_conf_t::backend_sts_role, ngx_http_brix_shared_conf_t::backend_token_aud, ngx_http_brix_shared_conf_t::backend_tx_client_id, ngx_http_brix_shared_conf_t::backend_tx_client_secret, ngx_http_brix_shared_conf_t::backend_tx_endpoint, brix_pmark_conf_init(), ngx_http_brix_shared_conf_t::cache_batch_cinfo, ngx_http_brix_shared_conf_t::cache_cold_store, ngx_http_brix_shared_conf_t::cache_cold_store_args, ngx_http_brix_shared_conf_t::cache_evict_at, ngx_http_brix_shared_conf_t::cache_evict_to, ngx_http_brix_shared_conf_t::cache_index_cache, ngx_http_brix_shared_conf_t::cache_max_object, ngx_http_brix_shared_conf_t::cache_meta_mode, ngx_http_brix_shared_conf_t::cache_peers, ngx_http_brix_shared_conf_t::cache_slice_size, ngx_http_brix_shared_conf_t::cache_store, ngx_http_brix_shared_conf_t::cache_store_args, ngx_http_brix_shared_conf_t::cache_store_endpoint, ngx_http_brix_shared_conf_t::cache_verify_mode, ngx_http_brix_shared_conf_t::compress, ngx_http_brix_shared_conf_t::enable, ngx_http_brix_shared_conf_t::ktls, ngx_http_brix_shared_conf_t::pblock_block_size, ngx_http_brix_shared_conf_t::pmark, ngx_http_brix_shared_conf_t::read_only, ngx_http_brix_shared_conf_t::require_pgwrite, ngx_http_brix_shared_conf_t::rootfd, ngx_http_brix_shared_conf_t::session_log, ngx_http_brix_shared_conf_t::stage_enable, ngx_http_brix_shared_conf_t::stage_flush_async, ngx_http_brix_shared_conf_t::stage_store, ngx_http_brix_shared_conf_t::stage_store_args, ngx_http_brix_shared_conf_t::storage_backend, ngx_http_brix_shared_conf_t::storage_credential, ngx_http_brix_shared_conf_t::storage_credential_dir, ngx_http_brix_shared_conf_t::storage_credential_fallback, ngx_http_brix_shared_conf_t::storage_credential_mint_ca_cert, ngx_http_brix_shared_conf_t::storage_credential_mint_ca_key, ngx_http_brix_shared_conf_t::storage_credential_mint_ttl, ngx_http_brix_shared_conf_t::storage_instance, ngx_http_brix_shared_conf_t::storage_staging, ngx_http_brix_shared_conf_t::strict_security, ngx_http_brix_shared_conf_t::thread_pool, ngx_http_brix_shared_conf_t::thread_pool_name, and ngx_http_brix_shared_conf_t::verify_write.
Referenced by brix_http_common_create_loc_conf(), ngx_http_brix_cvmfs_create_loc_conf(), ngx_http_brix_webdav_create_loc_conf(), ngx_http_s3_create_loc_conf(), and ngx_stream_brix_create_srv_conf().
ngx_http_brix_shared_merge()
static char * ngx_http_brix_shared_merge (ngx_conf_t * cf, ngx_http_brix_shared_conf_t * prev, ngx_http_brix_shared_conf_t * conf, const char * root_default) inline static
Definition at line 566 of file shared_conf.h.
References ngx_http_brix_shared_conf_t::access_log, ngx_http_brix_shared_conf_t::access_log_file, ngx_http_brix_shared_conf_t::allow_write, ngx_http_brix_shared_conf_t::backend_delegation, ngx_http_brix_shared_conf_t::backend_krb5_forwardable, ngx_http_brix_shared_conf_t::backend_passthrough_persist, ngx_http_brix_shared_conf_t::backend_sts_endpoint, ngx_http_brix_shared_conf_t::backend_sts_role, ngx_http_brix_shared_conf_t::backend_token_aud, ngx_http_brix_shared_conf_t::backend_tx_client_id, ngx_http_brix_shared_conf_t::backend_tx_client_secret, ngx_http_brix_shared_conf_t::backend_tx_endpoint, BRIX_CREDENTIAL_DIR_DEFAULT, brix_pmark_conf_merge(), brix_shared_apply_read_only(), brix_shared_credential_dir_ensure(), ngx_http_brix_shared_conf_t::cache_batch_cinfo, ngx_http_brix_shared_conf_t::cache_cold_store, ngx_http_brix_shared_conf_t::cache_cold_store_args, ngx_http_brix_shared_conf_t::cache_evict_at, ngx_http_brix_shared_conf_t::cache_evict_to, ngx_http_brix_shared_conf_t::cache_index_cache, ngx_http_brix_shared_conf_t::cache_max_object, ngx_http_brix_shared_conf_t::cache_meta_mode, ngx_http_brix_shared_conf_t::cache_peers, ngx_http_brix_shared_conf_t::cache_slice_size, ngx_http_brix_shared_conf_t::cache_store, ngx_http_brix_shared_conf_t::cache_store_args, ngx_http_brix_shared_conf_t::cache_store_endpoint, ngx_http_brix_shared_conf_t::cache_verify_mode, ngx_http_brix_shared_conf_t::compress, ngx_http_brix_shared_conf_t::enable, ngx_http_brix_shared_conf_t::ktls, ngx_http_brix_shared_conf_t::pblock_block_size, ngx_http_brix_shared_conf_t::pmark, ngx_http_brix_shared_conf_t::read_only, ngx_http_brix_shared_conf_t::require_pgwrite, ngx_http_brix_shared_conf_t::root, ngx_http_brix_shared_conf_t::session_log, ngx_http_brix_shared_conf_t::stage_enable, ngx_http_brix_shared_conf_t::stage_flush_async, ngx_http_brix_shared_conf_t::stage_store, ngx_http_brix_shared_conf_t::stage_store_args, ngx_http_brix_shared_conf_t::storage_backend, ngx_http_brix_shared_conf_t::storage_credential, ngx_http_brix_shared_conf_t::storage_credential_dir, ngx_http_brix_shared_conf_t::storage_credential_fallback, ngx_http_brix_shared_conf_t::storage_credential_mint_ca_cert, ngx_http_brix_shared_conf_t::storage_credential_mint_ca_key, ngx_http_brix_shared_conf_t::storage_credential_mint_ttl, ngx_http_brix_shared_conf_t::storage_staging, ngx_http_brix_shared_conf_t::strict_security, ngx_http_brix_shared_conf_t::thread_pool_name, and ngx_http_brix_shared_conf_t::verify_write.
Referenced by brix_merge_srv_security(), cvmfs_merge_preamble(), s3_merge_preamble(), and webdav_merge_base_conf().