nginx-xrootd: src/protocols/shared/protocol.h File Reference
protocol.h File Reference
#include "core/ngx_brix_module.h"
Data Structures
struct brix_protocol_t
Enumerations
enum brix_protocol_family_t { BRIX_PROTO_FAMILY_STREAM = 0 , BRIX_PROTO_FAMILY_HTTP }
Functions
ngx_int_t brix_protocol_register (const brix_protocol_t *p)
const brix_protocol_t * brix_protocol_find (const char *name)
ngx_uint_t brix_protocol_count_get (void)
const brix_protocol_t * brix_protocol_at (ngx_uint_t i)
void brix_protocol_register_all (void)
Enumeration Type Documentation
brix_protocol_family_t
enum brix_protocol_family_t
Enumerator
BRIX_PROTO_FAMILY_STREAM
BRIX_PROTO_FAMILY_HTTP
Definition at line 21 of file protocol.h.
Function Documentation
brix_protocol_at()
const brix_protocol_t * brix_protocol_at (ngx_uint_t i)
Definition at line 93 of file protocol.c.
References brix_protocol_count, and brix_protocols.
Referenced by brix_proto_mask(), and brix_proto_name().
brix_protocol_count_get()
ngx_uint_t brix_protocol_count_get (void)
Definition at line 87 of file protocol.c.
References brix_protocol_count.
Referenced by brix_proto_mask(), and brix_proto_name().
brix_protocol_find()
const brix_protocol_t * brix_protocol_find (const char * name)
Definition at line 71 of file protocol.c.
References brix_protocol_count, brix_protocols, and name.
brix_protocol_register()
ngx_int_t brix_protocol_register (const brix_protocol_t * p)
Definition at line 51 of file protocol.c.
References brix_protocol_count, BRIX_PROTOCOL_MAX, brix_protocols, brix_protocol_t::name, and name.
Referenced by brix_protocol_register_all().
brix_protocol_register_all()
void brix_protocol_register_all (void)
Definition at line 99 of file protocol.c.
References brix_proto_cvmfs, brix_proto_root, brix_proto_s3, brix_proto_webdav, and brix_protocol_register().
Referenced by ngx_http_brix_webdav_postconfiguration().