nginx-xrootd: src/core/compat/shm_slots.c File Reference
shm_slots.c File Reference
#include "shm_slots.h"
Functions
static ngx_int_t brix_shm_table_mutex_create (ngx_shmtx_t *mtx, ngx_slab_pool_t *sp)
void * brix_shm_table_alloc (ngx_shm_zone_t *shm_zone, void *data, size_t table_bytes, ngx_shmtx_t *mtx, ngx_flag_t *fresh)
void brix_shm_zone_warn_on_resize (ngx_conf_t *cf, ngx_shm_zone_t *zn, const char *directive)
size_t brix_shm_zone_size (size_t table_bytes)
Function Documentation
brix_shm_table_alloc()
void * brix_shm_table_alloc (ngx_shm_zone_t * shm_zone, void * data, size_t table_bytes, ngx_shmtx_t * mtx, ngx_flag_t * fresh)
Definition at line 61 of file shm_slots.c.
References brix_shm_table_mutex_create().
Referenced by brix_handle_shm_init_zone(), brix_kv_init_zone(), brix_pending_shm_init_zone(), brix_proxy_pool_init_zone(), brix_session_shm_init_zone(), brix_srv_shm_init_zone(), brix_tpc_key_shm_init_zone(), brix_tpc_registry_shm_init(), negcache_init_zone(), ngx_brix_dashboard_events_shm_init(), ngx_brix_dashboard_history_shm_init(), ngx_brix_dashboard_shm_init(), ngx_brix_metrics_shm_init(), redir_cache_shm_init(), and stage_waiter_init_zone().
brix_shm_table_mutex_create()
static ngx_int_t brix_shm_table_mutex_create (ngx_shmtx_t * mtx, ngx_slab_pool_t * sp) static
Definition at line 47 of file shm_slots.c.
Referenced by brix_shm_table_alloc().
brix_shm_zone_size()
size_t brix_shm_zone_size (size_t table_bytes)
Definition at line 180 of file shm_slots.c.
Referenced by brix_configure_dashboard(), brix_configure_session_registry(), brix_kv_configure(), brix_metrics_ensure_zone(), brix_negcache_configure(), brix_pending_configure(), brix_proxy_pool_configure(), brix_redir_cache_configure(), brix_srv_configure_registry(), brix_stage_waiter_configure(), brix_tpc_key_configure_registry(), and brix_tpc_registry_configure().
brix_shm_zone_warn_on_resize()
void brix_shm_zone_warn_on_resize (ngx_conf_t * cf, ngx_shm_zone_t * zn, const char * directive)
Definition at line 116 of file shm_slots.c.
Referenced by brix_configure_session_registry(), and brix_srv_configure_registry().