nginx-xrootd: src/auth/crypto/signing_policy.h File Reference
signing_policy.h File Reference
#include <stddef.h>
Enumerations
enum brix_sp_mode_t { BRIX_SP_MODE_OFF = 0 , BRIX_SP_MODE_ON = 1 , BRIX_SP_MODE_REQUIRE = 2 }
Functions
brix_sp_policy_t * brix_sp_parse (const char *buf, size_t len, char *errbuf, size_t errlen)
void brix_sp_free (brix_sp_policy_t *p)
int brix_sp_ca_dn_present (const brix_sp_policy_t *p, const char *ca_dn)
int brix_sp_subject_allowed (const brix_sp_policy_t *p, const char *ca_dn, const char *subject_dn)
int brix_sp_glob_match (const char *pat, const char *str)
Enumeration Type Documentation
brix_sp_mode_t
enum brix_sp_mode_t
Enumerator
BRIX_SP_MODE_OFF
BRIX_SP_MODE_ON
BRIX_SP_MODE_REQUIRE
Definition at line 20 of file signing_policy.h.
Function Documentation
brix_sp_ca_dn_present()
int brix_sp_ca_dn_present (const brix_sp_policy_t * p, const char * ca_dn)
Definition at line 406 of file signing_policy.c.
Referenced by brix_sp_table_check(), and sp_find_by_dn().
brix_sp_free()
void brix_sp_free (brix_sp_policy_t * p)
Definition at line 388 of file signing_policy.c.
References brix_sp_block_t::ca_dn, brix_sp_block_t::globs, and brix_sp_block_t::nglobs.
Referenced by brix_sp_parse(), brix_sp_table_build(), and brix_sp_table_free().
brix_sp_glob_match()
int brix_sp_glob_match (const char * pat, const char * str)
Definition at line 99 of file signing_policy.c.
Referenced by brix_sp_subject_allowed().
brix_sp_parse()
brix_sp_policy_t * brix_sp_parse (const char * buf, size_t len, char * errbuf, size_t errlen)
Definition at line 348 of file signing_policy.c.
References brix_sp_free(), sp_handle_line(), and sp_set_err().
Referenced by brix_sp_table_build().
brix_sp_subject_allowed()
int brix_sp_subject_allowed (const brix_sp_policy_t * p, const char * ca_dn, const char * subject_dn)
Definition at line 420 of file signing_policy.c.
References brix_sp_glob_match(), brix_sp_block_t::ca_dn, brix_sp_block_t::denied, brix_sp_block_t::globs, brix_sp_block_t::granted, and brix_sp_block_t::nglobs.
Referenced by brix_sp_table_check().