nginx-xrootd: src/auth/crypto/signing_policy.c File Reference
signing_policy.c File Reference
#include "auth/crypto/signing_policy.h"
#include <ctype.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct brix_sp_block_t
struct brix_sp_policy_t
Functions
static char * sp_strdup_n (const char *s, size_t n)
static int sp_is_space (char c)
static const char * sp_skip_space (const char *p, const char *end)
static size_t sp_token_len (const char *p, const char *end)
static void sp_set_err (char *errbuf, size_t errlen, size_t line, const char *fmt,...)
int brix_sp_glob_match (const char *pat, const char *str)
static brix_sp_block_t * sp_open_block (brix_sp_policy_t *p, char *ca_dn)
static int sp_add_glob (brix_sp_block_t *b, const char *s, size_t n)
static int sp_take_quoted (const char **pp, const char *end, const char **out, size_t *outlen)
static int sp_parse_cond_subjects (brix_sp_block_t *b, const char *p, const char *end)
static int sp_handle_access_id (brix_sp_policy_t *p, const char *rest, const char *end, brix_sp_block_t **cur, size_t line, char *errbuf, size_t errlen)
static int sp_handle_line (brix_sp_policy_t *p, const char *line, size_t len, brix_sp_block_t **cur, size_t lineno, char *errbuf, size_t errlen)
brix_sp_policy_t * brix_sp_parse (const char *buf, size_t len, char *errbuf, size_t errlen)
void brix_sp_free (brix_sp_policy_t *p)
int brix_sp_ca_dn_present (const brix_sp_policy_t *p, const char *ca_dn)
int brix_sp_subject_allowed (const brix_sp_policy_t *p, const char *ca_dn, const char *subject_dn)
Function Documentation
brix_sp_ca_dn_present()
int brix_sp_ca_dn_present (const brix_sp_policy_t * p, const char * ca_dn)
Definition at line 406 of file signing_policy.c.
Referenced by brix_sp_table_check(), and sp_find_by_dn().
brix_sp_free()
void brix_sp_free (brix_sp_policy_t * p)
Definition at line 388 of file signing_policy.c.
References brix_sp_block_t::ca_dn, brix_sp_block_t::globs, and brix_sp_block_t::nglobs.
Referenced by brix_sp_parse(), brix_sp_table_build(), and brix_sp_table_free().
brix_sp_glob_match()
int brix_sp_glob_match (const char * pat, const char * str)
Definition at line 99 of file signing_policy.c.
Referenced by brix_sp_subject_allowed().
brix_sp_parse()
brix_sp_policy_t * brix_sp_parse (const char * buf, size_t len, char * errbuf, size_t errlen)
Definition at line 348 of file signing_policy.c.
References brix_sp_free(), sp_handle_line(), and sp_set_err().
Referenced by brix_sp_table_build().
brix_sp_subject_allowed()
int brix_sp_subject_allowed (const brix_sp_policy_t * p, const char * ca_dn, const char * subject_dn)
Definition at line 420 of file signing_policy.c.
References brix_sp_glob_match(), brix_sp_block_t::ca_dn, brix_sp_block_t::denied, brix_sp_block_t::globs, brix_sp_block_t::granted, and brix_sp_block_t::nglobs.
Referenced by brix_sp_table_check().
sp_add_glob()
static int sp_add_glob (brix_sp_block_t * b, const char * s, size_t n) static
Definition at line 148 of file signing_policy.c.
References brix_sp_block_t::cap_globs, brix_sp_block_t::globs, brix_sp_block_t::nglobs, s, and sp_strdup_n().
Referenced by sp_parse_cond_subjects().
sp_handle_access_id()
static int sp_handle_access_id (brix_sp_policy_t * p, const char * rest, const char * end, brix_sp_block_t ** cur, size_t line, char * errbuf, size_t errlen) static
Definition at line 256 of file signing_policy.c.
References sp_open_block(), sp_set_err(), sp_strdup_n(), and sp_take_quoted().
Referenced by sp_handle_line().
sp_handle_line()
static int sp_handle_line (brix_sp_policy_t * p, const char * line, size_t len, brix_sp_block_t ** cur, size_t lineno, char * errbuf, size_t errlen) static
Definition at line 287 of file signing_policy.c.
References sp_handle_access_id(), sp_parse_cond_subjects(), sp_set_err(), sp_skip_space(), and sp_token_len().
Referenced by brix_sp_parse().
sp_is_space()
static int sp_is_space (char c) static
Definition at line 52 of file signing_policy.c.
References c.
Referenced by sp_parse_cond_subjects(), sp_skip_space(), and sp_token_len().
sp_open_block()
static brix_sp_block_t * sp_open_block (brix_sp_policy_t * p, char * ca_dn) static
Definition at line 129 of file signing_policy.c.
References brix_sp_block_t::ca_dn.
Referenced by sp_handle_access_id().
sp_parse_cond_subjects()
static int sp_parse_cond_subjects (brix_sp_block_t * b, const char * p, const char * end) static
Definition at line 204 of file signing_policy.c.
References sp_add_glob(), sp_is_space(), sp_skip_space(), and sp_take_quoted().
Referenced by sp_handle_line().
sp_set_err()
static void sp_set_err (char * errbuf, size_t errlen, size_t line, const char * fmt, ...) static
Definition at line 79 of file signing_policy.c.
Referenced by brix_sp_parse(), sp_handle_access_id(), and sp_handle_line().
sp_skip_space()
static const char * sp_skip_space (const char * p, const char * end) static
Definition at line 59 of file signing_policy.c.
References sp_is_space().
Referenced by sp_handle_line(), and sp_parse_cond_subjects().
sp_strdup_n()
static char * sp_strdup_n (const char * s, size_t n) static
Definition at line 40 of file signing_policy.c.
References s.
Referenced by sp_add_glob(), and sp_handle_access_id().
sp_take_quoted()
static int sp_take_quoted (const char ** pp, const char * end, const char ** out, size_t * outlen) static
Definition at line 174 of file signing_policy.c.
Referenced by sp_handle_access_id(), and sp_parse_cond_subjects().
sp_token_len()
static size_t sp_token_len (const char * p, const char * end) static
Definition at line 69 of file signing_policy.c.
References sp_is_space().
Referenced by sp_handle_line().