nginx-xrootd: src/protocols/root/session/signing.c File Reference
signing.c File Reference
#include "core/ngx_brix_module.h"
Functions
ngx_int_t brix_handle_sigver (brix_ctx_t *ctx, ngx_connection_t *c)
Function Documentation
brix_handle_sigver()
ngx_int_t brix_handle_sigver (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 28 of file signing.c.
References brix_log_access(), brix_send_error(), c, xrdw_sigver_req_t::crypto, brix_ctx_recv_t::cur_dlen, brix_ctx_sigver_t::expectrid, xrdw_sigver_req_t::expectrid, xrdw_sigver_req_t::flags, brix_ctx_recv_t::hdr_buf, brix_ctx_sigver_t::hmac, kXR_ArgInvalid, kXR_HashMask_sig, kXR_nodata_sig, kXR_NotAuthorized, kXR_rsaKey_sig, kXR_SHA256_sig, brix_ctx_sigver_t::last_seqno, ngx_memcpy, brix_ctx_sigver_t::nodata, brix_ctx_recv_t::payload, brix_ctx_sigver_t::pending, brix_ctx_t::recv, brix_ctx_sigver_t::seqno, xrdw_sigver_req_t::seqno, brix_ctx_sigver_t::signing_active, brix_ctx_t::sigver, and xrdw_sigver_req_unpack().
Referenced by brix_dispatch_signing_opcode().