nginx-xrootd: src/fs/backend/site_n2n.h File Reference
site_n2n.h File Reference
#include <stddef.h>
Data Structures
struct brix_n2n_cfg_t
Enumerations
enum brix_n2n_scheme_t { BRIX_N2N_IDENTITY = 0 , BRIX_N2N_RAL , BRIX_N2N_CEPHFS_PATH }
Functions
int brix_n2n_lfn2pfn (const brix_n2n_cfg_t *cfg, const char *lfn, char *pfn, size_t cap)
int brix_n2n_pfn2lfn (const brix_n2n_cfg_t *cfg, const char *pfn, char *lfn, size_t cap)
int brix_n2n_extract_pool (const char *objname, char *pool, size_t cap, const char **rest)
Enumeration Type Documentation
brix_n2n_scheme_t
enum brix_n2n_scheme_t
Enumerator
BRIX_N2N_IDENTITY
BRIX_N2N_RAL
BRIX_N2N_CEPHFS_PATH
Definition at line 27 of file site_n2n.h.
Function Documentation
brix_n2n_extract_pool()
int brix_n2n_extract_pool (const char * objname, char * pool, size_t cap, const char ** rest)
Definition at line 123 of file site_n2n.c.
References n2n_copy().
brix_n2n_lfn2pfn()
int brix_n2n_lfn2pfn (const brix_n2n_cfg_t * cfg, const char * lfn, char * pfn, size_t cap)
Definition at line 48 of file site_n2n.c.
References BRIX_N2N_CEPHFS_PATH, BRIX_N2N_IDENTITY, BRIX_N2N_RAL, n2n_copy(), n2n_has_traversal(), brix_n2n_cfg_t::pool, brix_n2n_cfg_t::prefix, and brix_n2n_cfg_t::scheme.
brix_n2n_pfn2lfn()
int brix_n2n_pfn2lfn (const brix_n2n_cfg_t * cfg, const char * pfn, char * lfn, size_t cap)
Definition at line 77 of file site_n2n.c.
References BRIX_N2N_CEPHFS_PATH, BRIX_N2N_IDENTITY, BRIX_N2N_RAL, n2n_copy(), brix_n2n_cfg_t::prefix, and brix_n2n_cfg_t::scheme.