nginx-xrootd: src/fs/backend/site_n2n.c File Reference
site_n2n.c File Reference
#include "site_n2n.h"
#include <stdio.h>
#include <string.h>
Functions
static int n2n_has_traversal (const char *p)
static int n2n_copy (char *dst, size_t cap, const char *src)
int brix_n2n_lfn2pfn (const brix_n2n_cfg_t *cfg, const char *lfn, char *pfn, size_t cap)
int brix_n2n_pfn2lfn (const brix_n2n_cfg_t *cfg, const char *pfn, char *lfn, size_t cap)
int brix_n2n_extract_pool (const char *objname, char *pool, size_t cap, const char **rest)
Function Documentation
brix_n2n_extract_pool()
int brix_n2n_extract_pool (const char * objname, char * pool, size_t cap, const char ** rest)
Definition at line 123 of file site_n2n.c.
References n2n_copy().
brix_n2n_lfn2pfn()
int brix_n2n_lfn2pfn (const brix_n2n_cfg_t * cfg, const char * lfn, char * pfn, size_t cap)
Definition at line 48 of file site_n2n.c.
References BRIX_N2N_CEPHFS_PATH, BRIX_N2N_IDENTITY, BRIX_N2N_RAL, n2n_copy(), n2n_has_traversal(), brix_n2n_cfg_t::pool, brix_n2n_cfg_t::prefix, and brix_n2n_cfg_t::scheme.
brix_n2n_pfn2lfn()
int brix_n2n_pfn2lfn (const brix_n2n_cfg_t * cfg, const char * pfn, char * lfn, size_t cap)
Definition at line 77 of file site_n2n.c.
References BRIX_N2N_CEPHFS_PATH, BRIX_N2N_IDENTITY, BRIX_N2N_RAL, n2n_copy(), brix_n2n_cfg_t::prefix, and brix_n2n_cfg_t::scheme.
n2n_copy()
static int n2n_copy (char * dst, size_t cap, const char * src) static
Definition at line 36 of file site_n2n.c.
Referenced by brix_n2n_extract_pool(), brix_n2n_lfn2pfn(), and brix_n2n_pfn2lfn().
n2n_has_traversal()
static int n2n_has_traversal (const char * p) static
Definition at line 12 of file site_n2n.c.
References s.
Referenced by brix_n2n_lfn2pfn().