nginx-xrootd: client/lib/net/sock.c File Reference
sock.c File Reference
#include "brix.h"
#include "net/proxy_env.h"
#include "net/proxy_connect.h"
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <netdb.h>
#include <unistd.h>
#include <poll.h>
#include <fcntl.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>
Macros
#define XRDC_CONNECT_ATTEMPT_MS 5000
Functions
static int set_blocking (int fd, int blocking)
void brix_sock_tune (int fd)
static int connect_one (const struct addrinfo *ai, int timeout_ms)
static int fd_family (int fd)
static int connect_resolved (const char *host, int port, int timeout_ms, int family, brix_status *st)
int brix_tcp_connect (const char *host, int port, int timeout_ms, brix_status *st)
static int read_wait_ms (int timeout_ms, uint64_t deadline_ns)
static int plain_read_full (brix_io *io, void *buf, size_t n, brix_status *st)
static int plain_write_full (brix_io *io, const void *buf, size_t n, brix_status *st)
static void note_io_failure (brix_io *io, int rc, const brix_status *st)
void brix_io_stall_arm (brix_io *io)
void brix_io_stall_disarm (brix_io *io)
int brix_read_full (brix_io *io, void *buf, size_t n, brix_status *st)
int brix_write_full (brix_io *io, const void *buf, size_t n, brix_status *st)
Macro Definition Documentation
XRDC_CONNECT_ATTEMPT_MS
#define XRDC_CONNECT_ATTEMPT_MS 5000
Definition at line 73 of file sock.c.
Function Documentation
brix_io_stall_arm()
void brix_io_stall_arm (brix_io * io)
Definition at line 440 of file sock.c.
References brix_mono_ns(), brix_io::stall_deadline_ms, and brix_io::stall_deadline_ns.
Referenced by brix_file_pgread(), brix_file_read(), and brix_file_readv().
brix_io_stall_disarm()
void brix_io_stall_disarm (brix_io * io)
Definition at line 452 of file sock.c.
References brix_io::stall_deadline_ns.
Referenced by brix_file_pgread(), brix_file_read(), and brix_file_readv().
brix_read_full()
int brix_read_full (brix_io * io, void * buf, size_t n, brix_status * st)
Definition at line 458 of file sock.c.
References brix_tls_read(), note_io_failure(), plain_read_full(), and brix_io::ssl.
Referenced by brix_kaconn_read_body(), file_pgread_frames(), frame_read_body(), frame_read_header(), pgwrite_handle_cse(), pgwrite_retry_one(), read_status_frame(), recv_raw(), and web_range_stream_body().
brix_sock_tune()
void brix_sock_tune (int fd)
Definition at line 51 of file sock.c.
Referenced by brix_tcp_connect(), and connect_one().
brix_tcp_connect()
int brix_tcp_connect (const char * host, int port, int timeout_ms, brix_status * st)
Definition at line 220 of file sock.c.
References brix_netpref_family(), brix_netpref_undo_demote(), brix_sock_tune(), brix_status_set(), close(), connect_resolved(), host, port, and XRDC_ESOCK.
Referenced by brix_bringup_ex(), brix_http_get(), brix_kaconn_connect(), brix_wait41_main(), httpx_connect(), and web_connect().
brix_write_full()
int brix_write_full (brix_io * io, const void * buf, size_t n, brix_status * st)
Definition at line 467 of file sock.c.
References brix_tls_write(), note_io_failure(), plain_write_full(), and brix_io::ssl.
Referenced by brix_send_ext(), brix_sigver_maybe(), do_handshake(), httpx_chunk_core(), httpx_download_exchange(), httpx_exchange_core(), httpx_send_request(), httpx_upload_body(), playback_reissue_wire(), probe_p5_partial_frame(), raw_send_expect_reject(), web_range_send_req(), and webmeta_send_req().
connect_one()
static int connect_one (const struct addrinfo * ai, int timeout_ms) static
Definition at line 83 of file sock.c.
References brix_sock_tune(), close(), and set_blocking().
Referenced by connect_resolved().
connect_resolved()
static int connect_resolved (const char * host, int port, int timeout_ms, int family, brix_status * st) static
Definition at line 160 of file sock.c.
References brix_netpref_demote_ipv6(), brix_status_set(), code, connect_one(), host, port, XRDC_CONNECT_ATTEMPT_MS, XRDC_ERESOLVE, and XRDC_ESOCK.
Referenced by brix_tcp_connect().
fd_family()
static int fd_family (int fd) static
Definition at line 143 of file sock.c.
Referenced by note_io_failure().
note_io_failure()
static void note_io_failure (brix_io * io, int rc, const brix_status * st) static
Definition at line 432 of file sock.c.
References brix_netpref_note_wire_error(), brix_io::fd, fd_family(), brix_status::sys_errno, and XRDC_ESOCK.
Referenced by brix_read_full(), and brix_write_full().
plain_read_full()
static int plain_read_full (brix_io * io, void * buf, size_t n, brix_status * st) static
Definition at line 297 of file sock.c.
References brix_copy_quit_requested(), brix_mono_ns(), brix_status_set(), brix_io::fd, read(), read_wait_ms(), brix_io::stall_deadline_ms, brix_io::stall_deadline_ns, brix_io::timeout_ms, and XRDC_ESOCK.
Referenced by brix_read_full().
plain_write_full()
static int plain_write_full (brix_io * io, const void * buf, size_t n, brix_status * st) static
Definition at line 374 of file sock.c.
References brix_copy_quit_requested(), brix_status_set(), brix_io::fd, brix_io::timeout_ms, and XRDC_ESOCK.
Referenced by brix_write_full().
read_wait_ms()
static int read_wait_ms (int timeout_ms, uint64_t deadline_ns) static
Definition at line 273 of file sock.c.
References brix_mono_ns().
Referenced by plain_read_full().
set_blocking()
static int set_blocking (int fd, int blocking) static
Definition at line 28 of file sock.c.
Referenced by connect_one().