nginx-xrootd: src/tpc/outbound/source_stream.c File Reference
source_stream.c File Reference
#include "tpc/engine/tpc_internal.h"
#include "protocols/root/protocol/frame_hdr.h"
#include "core/compat/checksum.h"
#include "source_internal.h"
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <errno.h>
#include <limits.h>
#include <unistd.h>
#include <time.h>
#include <sys/socket.h>
#include <sys/time.h>
Functions
static int tpc_stream_send_read (brix_tpc_pull_t *t, int fd, const u_char *fhandle, uint64_t offset)
static int tpc_stream_classify_frame (brix_tpc_pull_t *t, uint16_t status, const u_char *body, uint32_t dlen, uint64_t offset)
static int tpc_stream_write_frame (brix_tpc_pull_t *t, uint64_t offset, size_t *got_this_req, u_char *body, uint32_t dlen)
static int tpc_stream_drain_request (brix_tpc_pull_t *t, int fd, uint64_t offset, size_t *got_this_req)
static int tpc_stream_sync_dst (brix_tpc_pull_t *t)
int tpc_stream_to_dst (brix_tpc_pull_t *t, int fd, const u_char *fhandle)
static int tpc_stat_parse_size (const char *body, uint64_t *size)
int tpc_stat_source (brix_tpc_pull_t *t, int fd)
int tpc_verify_source_checksum (brix_tpc_pull_t *t, int fd)
void tpc_close_source (brix_tpc_pull_t *t, int fd, const u_char *fhandle)
Function Documentation
tpc_close_source()
void tpc_close_source (brix_tpc_pull_t * t, int fd, const u_char * fhandle)
Definition at line 539 of file source_stream.c.
References ClientCloseRequest::fhandle, kXR_close, ngx_memcpy, ClientCloseRequest::requestid, s, ClientCloseRequest::streamid, tpc_recv_response(), tpc_send_all(), and XRD_FHANDLE_LEN.
Referenced by tpc_pull_from_source().
tpc_stat_parse_size()
static int tpc_stat_parse_size (const char * body, uint64_t * size) static
Definition at line 321 of file source_stream.c.
Referenced by tpc_stat_source().
tpc_stat_source()
int tpc_stat_source (brix_tpc_pull_t * t, int fd)
Definition at line 356 of file source_stream.c.
References brix_tpc_pull_t::err_msg, kXR_ArgTooLong, kXR_IOError, kXR_ok, kXR_stat, ngx_memcpy, PATH_MAX, brix_tpc_pull_t::src_path, brix_tpc_pull_t::src_size, brix_tpc_pull_t::src_size_known, tpc_recv_response(), tpc_send_all(), tpc_stat_parse_size(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_pull_from_source().
tpc_stream_classify_frame()
static int tpc_stream_classify_frame (brix_tpc_pull_t * t, uint16_t status, const u_char * body, uint32_t dlen, uint64_t offset) static
Definition at line 74 of file source_stream.c.
References brix_tpc_pull_t::err_msg, kXR_error, kXR_IOError, kXR_ok, kXR_oksofar, kXR_ServerError, and brix_tpc_pull_t::xrd_error.
Referenced by tpc_stream_drain_request().
tpc_stream_drain_request()
static int tpc_stream_drain_request (brix_tpc_pull_t * t, int fd, uint64_t offset, size_t * got_this_req) static
Definition at line 157 of file source_stream.c.
References brix_tpc_pull_t::err_msg, kXR_ok, tpc_recv_response(), tpc_stream_classify_frame(), and tpc_stream_write_frame().
Referenced by tpc_stream_to_dst().
tpc_stream_send_read()
static int tpc_stream_send_read (brix_tpc_pull_t * t, int fd, const u_char * fhandle, uint64_t offset) static
Definition at line 44 of file source_stream.c.
References brix_tpc_pull_t::err_msg, ClientReadRequest::fhandle, kXR_read, ngx_memcpy, ClientReadRequest::offset, ClientReadRequest::requestid, ClientReadRequest::rlen, ClientReadRequest::streamid, TPC_CHUNK_SIZE, tpc_send_all(), and XRD_FHANDLE_LEN.
Referenced by tpc_stream_to_dst().
tpc_stream_sync_dst()
static int tpc_stream_sync_dst (brix_tpc_pull_t * t) static
Definition at line 204 of file source_stream.c.
References brix_vfs_io_execute(), brix_vfs_job_sync_init(), brix_tpc_pull_t::dst_fd, brix_tpc_pull_t::err_msg, brix_vfs_job_t::io_errno, kXR_IOError, and brix_tpc_pull_t::xrd_error.
Referenced by tpc_stream_to_dst().
tpc_stream_to_dst()
int tpc_stream_to_dst (brix_tpc_pull_t * t, int fd, const u_char * fhandle)
Definition at line 238 of file source_stream.c.
References brix_tpc_pull_t::bytes_written, brix_tpc_pull_t::conf, brix_tpc_pull_t::err_msg, kXR_IOError, kXR_ServerError, brix_tpc_pull_t::result, brix_tpc_pull_t::src_size, brix_tpc_pull_t::src_size_known, tpc_stream_drain_request(), tpc_stream_send_read(), tpc_stream_sync_dst(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_pull_from_source().
tpc_stream_write_frame()
static int tpc_stream_write_frame (brix_tpc_pull_t * t, uint64_t offset, size_t * got_this_req, u_char * body, uint32_t dlen) static
Definition at line 112 of file source_stream.c.
References brix_tpc_progress_emit(), BRIX_TPC_STATE_ACTIVE, brix_vfs_io_execute(), brix_vfs_job_write_init(), brix_tpc_pull_t::bytes_written, brix_tpc_pull_t::c, brix_tpc_pull_t::dst_fd, brix_tpc_pull_t::err_msg, brix_vfs_job_t::io_errno, kXR_IOError, brix_vfs_job_t::nio, brix_tpc_pull_t::transfer_id, and brix_tpc_pull_t::xrd_error.
Referenced by tpc_stream_drain_request().
tpc_verify_source_checksum()
int tpc_verify_source_checksum (brix_tpc_pull_t * t, int fd)
Definition at line 413 of file source_stream.c.
References alg, brix_checksum_hex_name_fd(), brix_tpc_pull_t::c, brix_tpc_pull_t::dst_fd, brix_tpc_pull_t::dst_path, brix_tpc_pull_t::err_msg, kXR_ArgTooLong, kXR_ChkSumErr, kXR_IOError, kXR_ok, kXR_Qcksum, kXR_query, log, ngx_memcpy, PATH_MAX, brix_tpc_pull_t::src_path, tpc_recv_response(), tpc_send_all(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_pull_from_source().