nginx-xrootd: src/tpc/outbound/source_open.c File Reference
source_open.c File Reference
#include "tpc/engine/tpc_internal.h"
#include "protocols/root/protocol/frame_hdr.h"
#include "source_internal.h"
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <limits.h>
#include <unistd.h>
#include <time.h>
#include <sys/socket.h>
#include <sys/time.h>
Data Structures
struct tpc_open_reply_t
struct tpc_open_ctx_t
struct tpc_open_buf_t
Functions
static void tpc_set_rcvtimeo (int fd, int secs)
static int tpc_open_wait_resend (brix_tpc_pull_t *t, const tpc_open_ctx_t *oc, const u_char *body, uint32_t dlen, const char *what)
static int tpc_open_resolve_attn (brix_tpc_pull_t *t, const tpc_open_ctx_t *oc, u_char *attn_body, uint32_t attn_dlen, tpc_open_reply_t *out)
static int tpc_open_resolve_round (brix_tpc_pull_t *t, const tpc_open_ctx_t *oc, tpc_open_reply_t *out)
static int tpc_open_resolve (brix_tpc_pull_t *t, const tpc_open_ctx_t *oc, tpc_open_reply_t *out)
static int tpc_open_build_opaque (brix_tpc_pull_t *t, char *opaque, size_t opaque_sz, size_t *opqlen)
static int tpc_open_build_request (brix_tpc_pull_t *t, tpc_open_buf_t *dst, const char *opaque, size_t opqlen)
static int tpc_open_extract_fhandle (brix_tpc_pull_t *t, tpc_open_reply_t *reply, u_char fhandle[4])
int tpc_open_source (brix_tpc_pull_t *t, int fd, u_char fhandle[4])
Function Documentation
tpc_open_build_opaque()
static int tpc_open_build_opaque (brix_tpc_pull_t * t, char * opaque, size_t opaque_sz, size_t * opqlen) static
Definition at line 293 of file source_open.c.
References brix_tpc_pull_t::deleg_cred_len, brix_tpc_pull_t::deleg_cred_pem, brix_tpc_pull_t::err_msg, kXR_ArgTooLong, brix_tpc_pull_t::tpc_key, brix_tpc_pull_t::tpc_org, and brix_tpc_pull_t::xrd_error.
Referenced by tpc_open_source().
tpc_open_build_request()
static int tpc_open_build_request (brix_tpc_pull_t * t, tpc_open_buf_t * dst, const char * opaque, size_t opqlen) static
Definition at line 339 of file source_open.c.
References tpc_open_buf_t::buf, tpc_open_buf_t::cap, ClientOpenRequest::dlen, brix_tpc_pull_t::err_msg, kXR_ArgTooLong, kXR_open, kXR_open_read, tpc_open_buf_t::len, ngx_memcpy, xrdw_open_req_t::options, ClientOpenRequest::requestid, brix_tpc_pull_t::src_path, ClientOpenRequest::streamid, brix_tpc_pull_t::xrd_error, and xrdw_open_req_pack().
Referenced by tpc_open_source().
tpc_open_extract_fhandle()
static int tpc_open_extract_fhandle (brix_tpc_pull_t * t, tpc_open_reply_t * reply, u_char fhandle[4]) static
Definition at line 389 of file source_open.c.
References tpc_open_reply_t::body, tpc_open_reply_t::dlen, brix_tpc_pull_t::err_msg, kXR_error, kXR_ok, ngx_memcpy, tpc_open_reply_t::status, brix_tpc_pull_t::xrd_error, xrd_error_body_decode(), and XRD_FHANDLE_LEN.
Referenced by tpc_open_source().
tpc_open_resolve()
static int tpc_open_resolve (brix_tpc_pull_t * t, const tpc_open_ctx_t * oc, tpc_open_reply_t * out) static
Definition at line 240 of file source_open.c.
References brix_tpc_pull_t::err_msg, kXR_ServerError, TPC_OPEN_RESOLVE_MAX_ITERS, TPC_OPEN_RESOLVE_MAX_SEC, tpc_open_resolve_round(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_open_source().
tpc_open_resolve_attn()
static int tpc_open_resolve_attn (brix_tpc_pull_t * t, const tpc_open_ctx_t * oc, u_char * attn_body, uint32_t attn_dlen, tpc_open_reply_t * out) static
Definition at line 113 of file source_open.c.
References tpc_open_reply_t::body, tpc_open_reply_t::dlen, brix_tpc_pull_t::err_msg, kXR_asynresp, kXR_NoMemory, kXR_ServerError, kXR_wait, kXR_waitresp, tpc_open_reply_t::status, tpc_open_wait_resend(), brix_tpc_pull_t::xrd_error, and xrd_get_u32_be().
Referenced by tpc_open_resolve_round().
tpc_open_resolve_round()
static int tpc_open_resolve_round (brix_tpc_pull_t * t, const tpc_open_ctx_t * oc, tpc_open_reply_t * out) static
Definition at line 178 of file source_open.c.
References tpc_open_reply_t::body, tpc_open_reply_t::dlen, brix_tpc_pull_t::err_msg, tpc_open_ctx_t::fd, kXR_attn, kXR_wait, kXR_waitresp, tpc_open_reply_t::status, tpc_open_resolve_attn(), tpc_open_wait_resend(), and tpc_recv_response().
Referenced by tpc_open_resolve().
tpc_open_source()
int tpc_open_source (brix_tpc_pull_t * t, int fd, u_char fhandle[4])
Definition at line 433 of file source_open.c.
References tpc_open_ctx_t::buf, tpc_open_buf_t::buf, brix_tpc_pull_t::err_msg, tpc_open_ctx_t::fd, tpc_open_ctx_t::len, tpc_open_buf_t::len, PATH_MAX, TPC_IO_TIMEOUT_SEC, tpc_open_build_opaque(), tpc_open_build_request(), tpc_open_extract_fhandle(), tpc_open_resolve(), TPC_OPEN_WAIT_CAP_SEC, tpc_send_all(), and tpc_set_rcvtimeo().
Referenced by tpc_pull_from_source().
tpc_open_wait_resend()
static int tpc_open_wait_resend (brix_tpc_pull_t * t, const tpc_open_ctx_t * oc, const u_char * body, uint32_t dlen, const char * what) static
Definition at line 84 of file source_open.c.
References tpc_open_ctx_t::buf, brix_tpc_pull_t::err_msg, tpc_open_ctx_t::fd, tpc_open_ctx_t::len, TPC_OPEN_WAIT_RETRY_SEC, tpc_send_all(), and xrd_wait_secs_parse().
Referenced by tpc_open_resolve_attn(), and tpc_open_resolve_round().
tpc_set_rcvtimeo()
static void tpc_set_rcvtimeo (int fd, int secs) static
Definition at line 35 of file source_open.c.
Referenced by tpc_open_source().