nginx-xrootd: src/tpc/outbound/source_internal.h File Reference
source_internal.h File Reference
#include "tpc/engine/tpc_internal.h"
Functions
int tpc_open_source (brix_tpc_pull_t *t, int fd, u_char fhandle[4])
int tpc_stream_to_dst (brix_tpc_pull_t *t, int fd, const u_char *fhandle)
void tpc_close_source (brix_tpc_pull_t *t, int fd, const u_char *fhandle)
Function Documentation
tpc_close_source()
void tpc_close_source (brix_tpc_pull_t * t, int fd, const u_char * fhandle)
Definition at line 291 of file source_stream.c.
References ClientCloseRequest::fhandle, kXR_close, ngx_memcpy, ClientCloseRequest::requestid, s, ClientCloseRequest::streamid, tpc_recv_response(), tpc_send_all(), and XRD_FHANDLE_LEN.
Referenced by tpc_pull_from_source().
tpc_open_source()
int tpc_open_source (brix_tpc_pull_t * t, int fd, u_char fhandle[4])
Definition at line 433 of file source_open.c.
References tpc_open_ctx_t::buf, tpc_open_buf_t::buf, brix_tpc_pull_t::err_msg, tpc_open_ctx_t::fd, tpc_open_ctx_t::len, tpc_open_buf_t::len, PATH_MAX, TPC_IO_TIMEOUT_SEC, tpc_open_build_opaque(), tpc_open_build_request(), tpc_open_extract_fhandle(), tpc_open_resolve(), TPC_OPEN_WAIT_CAP_SEC, tpc_send_all(), and tpc_set_rcvtimeo().
Referenced by tpc_pull_from_source().
tpc_stream_to_dst()
int tpc_stream_to_dst (brix_tpc_pull_t * t, int fd, const u_char * fhandle)
Definition at line 236 of file source_stream.c.
References brix_tpc_pull_t::conf, brix_tpc_pull_t::err_msg, kXR_IOError, brix_tpc_pull_t::result, tpc_stream_drain_request(), tpc_stream_send_read(), tpc_stream_sync_dst(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_pull_from_source().