nginx-xrootd: src/tpc/outbound/source.c File Reference
source.c File Reference
#include "tpc/engine/tpc_internal.h"
#include "protocols/root/protocol/frame_hdr.h"
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <limits.h>
#include <unistd.h>
#include <time.h>
#include <sys/socket.h>
#include <sys/time.h>
Functions
static void tpc_set_rcvtimeo (int fd, int secs)
static int tpc_open_resolve (brix_tpc_pull_t *t, int fd, const u_char *open_buf, size_t send_len, uint16_t *status, u_char **body, uint32_t *dlen)
static int tpc_open_source (brix_tpc_pull_t *t, int fd, u_char fhandle[4])
static int tpc_stream_to_dst (brix_tpc_pull_t *t, int fd, const u_char *fhandle)
static void tpc_close_source (brix_tpc_pull_t *t, int fd, const u_char *fhandle)
int tpc_pull_from_source (brix_tpc_pull_t *t, int fd)
Function Documentation
tpc_close_source()
static void tpc_close_source (brix_tpc_pull_t * t, int fd, const u_char * fhandle) static
Definition at line 540 of file source.c.
References ClientCloseRequest::fhandle, kXR_close, ClientCloseRequest::requestid, s, ClientCloseRequest::streamid, tpc_recv_response(), tpc_send_all(), and XRD_FHANDLE_LEN.
Referenced by tpc_pull_from_source().
tpc_open_resolve()
static int tpc_open_resolve (brix_tpc_pull_t * t, int fd, const u_char * open_buf, size_t send_len, uint16_t * status, u_char ** body, uint32_t * dlen) static
Definition at line 60 of file source.c.
References brix_tpc_pull_t::err_msg, kXR_asynresp, kXR_attn, kXR_NoMemory, kXR_ServerError, kXR_wait, kXR_waitresp, TPC_OPEN_RESOLVE_MAX_ITERS, TPC_OPEN_RESOLVE_MAX_SEC, TPC_OPEN_WAIT_CAP_SEC, tpc_recv_response(), tpc_send_all(), brix_tpc_pull_t::xrd_error, xrd_get_u32_be(), and xrd_wait_secs_parse().
Referenced by tpc_open_source().
tpc_open_source()
static int tpc_open_source (brix_tpc_pull_t * t, int fd, u_char fhandle[4]) static
Definition at line 193 of file source.c.
References brix_tpc_pull_t::deleg_cred_len, brix_tpc_pull_t::deleg_cred_pem, brix_tpc_pull_t::err_msg, kXR_ArgTooLong, kXR_error, kXR_ok, kXR_open, kXR_open_read, xrdw_open_req_t::options, PATH_MAX, brix_tpc_pull_t::src_path, TPC_IO_TIMEOUT_SEC, brix_tpc_pull_t::tpc_key, tpc_open_resolve(), TPC_OPEN_WAIT_CAP_SEC, brix_tpc_pull_t::tpc_org, tpc_send_all(), tpc_set_rcvtimeo(), brix_tpc_pull_t::xrd_error, xrd_error_body_decode(), XRD_FHANDLE_LEN, and xrdw_open_req_pack().
Referenced by tpc_pull_from_source().
tpc_pull_from_source()
int tpc_pull_from_source (brix_tpc_pull_t * t, int fd)
Definition at line 565 of file source.c.
References tpc_close_source(), tpc_open_source(), tpc_stream_to_dst(), and XRD_FHANDLE_LEN.
Referenced by brix_tpc_pull_thread().
tpc_set_rcvtimeo()
static void tpc_set_rcvtimeo (int fd, int secs) static
Definition at line 29 of file source.c.
Referenced by tpc_open_source().
tpc_stream_to_dst()
static int tpc_stream_to_dst (brix_tpc_pull_t * t, int fd, const u_char * fhandle) static
Definition at line 332 of file source.c.
References brix_tpc_progress_emit(), BRIX_TPC_STATE_ACTIVE, brix_vfs_io_execute(), brix_vfs_job_sync_init(), brix_vfs_job_write_init(), brix_tpc_pull_t::bytes_written, brix_tpc_pull_t::c, brix_tpc_pull_t::conf, brix_tpc_pull_t::dst_fd, brix_tpc_pull_t::err_msg, ClientReadRequest::fhandle, brix_vfs_job_t::io_errno, kXR_error, kXR_IOError, kXR_ok, kXR_oksofar, kXR_read, kXR_ServerError, brix_vfs_job_t::nio, ClientReadRequest::offset, ClientReadRequest::requestid, brix_tpc_pull_t::result, ClientReadRequest::rlen, ClientReadRequest::streamid, TPC_CHUNK_SIZE, ngx_stream_brix_srv_conf_t::tpc_max_transfer_secs, tpc_recv_response(), tpc_send_all(), brix_tpc_pull_t::transfer_id, brix_tpc_pull_t::xrd_error, and XRD_FHANDLE_LEN.
Referenced by tpc_pull_from_source().