nginx-xrootd: src/protocols/webdav/copy.c File Reference
copy.c File Reference
#include "webdav.h"
#include "protocols/webdav/fs/copy_engine.h"
#include "protocols/webdav/methods/copy_conditionals.h"
#include "core/http/http_conditionals.h"
#include "core/compat/error_mapping.h"
#include "core/compat/namespace_ops.h"
#include "core/compat/tmp_path.h"
#include "fs/vfs/vfs.h"
#include "auth/impersonate/impersonate.h"
#include "fs/path/path.h"
#include <errno.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
struct webdav_copy_job_t
struct webdav_copy_collection_task_t
struct webdav_copy_req_t
Functions
static ngx_int_t webdav_copy_errno_to_status (int err)
static void webdav_copy_job_init (webdav_copy_job_t *job, ngx_log_t *log, const char *root_canon, const webdav_copy_req_t *req)
static ngx_int_t webdav_copy_collection_stage (const webdav_copy_job_t *job, char *tmp_path, size_t tmp_path_size)
static ngx_int_t webdav_copy_collection_commit (const webdav_copy_job_t *job, const char *tmp_path)
static ngx_int_t webdav_copy_collection_execute (const webdav_copy_job_t *job)
static void webdav_copy_collection_thread (void *data, ngx_log_t *log)
static void webdav_copy_collection_done (ngx_event_t *ev)
static ngx_thread_pool_t * webdav_copy_thread_pool (ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t webdav_copy_collection_post_task (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const webdav_copy_job_t *job)
static ngx_int_t webdav_copy_probe (ngx_http_request_t *r, const char *path, struct stat *sb)
static ngx_int_t webdav_copy_parse_request (ngx_http_request_t *r, webdav_copy_req_t *req)
static ngx_int_t webdav_copy_resolve_pair (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, webdav_copy_req_t *req)
static ngx_int_t webdav_copy_do_collection (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const webdav_copy_req_t *req)
static void webdav_copy_file_vfs_init (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const char *src_path, brix_vfs_ctx_t *vctx)
static ngx_int_t webdav_copy_do_file (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const webdav_copy_req_t *req)
ngx_int_t webdav_handle_copy (ngx_http_request_t *r)
Function Documentation
webdav_copy_collection_commit()
static ngx_int_t webdav_copy_collection_commit (const webdav_copy_job_t * job, const char * tmp_path) static
Definition at line 202 of file copy.c.
References brix_log_safe_path(), brix_rename_confined_canon(), webdav_copy_job_t::dst_existed, webdav_copy_job_t::dst_path, webdav_copy_job_t::dst_was_dir, webdav_copy_job_t::log, webdav_copy_job_t::root_canon, and webdav_delete_path_recursive().
Referenced by webdav_copy_collection_execute().
webdav_copy_collection_done()
static void webdav_copy_collection_done (ngx_event_t * ev) static
Definition at line 272 of file copy.c.
References webdav_copy_collection_task_t::http_status, webdav_copy_collection_task_t::r, webdav_metrics_finalize_request(), and webdav_send_status_only().
Referenced by webdav_copy_collection_post_task().
webdav_copy_collection_execute()
static ngx_int_t webdav_copy_collection_execute (const webdav_copy_job_t * job) static
Definition at line 238 of file copy.c.
References webdav_copy_collection_commit(), webdav_copy_collection_stage(), and WEBDAV_MAX_PATH.
Referenced by webdav_copy_collection_thread(), and webdav_copy_do_collection().
webdav_copy_collection_post_task()
static ngx_int_t webdav_copy_collection_post_task (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const webdav_copy_job_t * job) static
Definition at line 325 of file copy.c.
References brix_imp_enabled(), webdav_copy_collection_task_t::http_status, webdav_copy_collection_task_t::job, webdav_copy_job_t::log, webdav_copy_collection_task_t::r, webdav_copy_collection_done(), webdav_copy_collection_thread(), and webdav_copy_thread_pool().
Referenced by webdav_copy_do_collection().
webdav_copy_collection_stage()
static ngx_int_t webdav_copy_collection_stage (const webdav_copy_job_t * job, char * tmp_path, size_t tmp_path_size) static
Definition at line 158 of file copy.c.
References brix_make_tmp_path(), brix_ns_copy_fattrs(), brix_vfs_mkdir_path(), webdav_copy_job_t::depth_infinity, webdav_copy_job_t::dst_path, webdav_copy_job_t::log, webdav_copy_job_t::root_canon, webdav_copy_job_t::src_mode, webdav_copy_job_t::src_path, webdav_copy_dir_recursive(), webdav_dead_props_copy(), and webdav_delete_path_recursive().
Referenced by webdav_copy_collection_execute().
webdav_copy_collection_thread()
static void webdav_copy_collection_thread (void * data, ngx_log_t * log) static
Definition at line 257 of file copy.c.
References webdav_copy_collection_task_t::http_status, webdav_copy_collection_task_t::job, log, and webdav_copy_collection_execute().
Referenced by webdav_copy_collection_post_task().
webdav_copy_do_collection()
static ngx_int_t webdav_copy_do_collection (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const webdav_copy_req_t * req) static
Definition at line 551 of file copy.c.
References ngx_http_brix_webdav_loc_conf_t::common, webdav_copy_req_t::depth_infinity, webdav_copy_job_t::log, ngx_http_brix_shared_conf_t::root_canon, webdav_copy_collection_execute(), webdav_copy_collection_post_task(), and webdav_copy_job_init().
Referenced by webdav_handle_copy().
webdav_copy_do_file()
static ngx_int_t webdav_copy_do_file (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const webdav_copy_req_t * req) static
Definition at line 632 of file copy.c.
References brix_vfs_copy(), ngx_http_brix_webdav_loc_conf_t::common, webdav_copy_req_t::dst_existed, webdav_copy_req_t::dst_path, webdav_copy_req_t::dst_sb, brix_vfs_copy_opts_t::overwrite, webdav_copy_req_t::overwrite, brix_vfs_copy_opts_t::preserve_xattrs, ngx_http_brix_shared_conf_t::root_canon, webdav_copy_req_t::src_path, brix_vfs_copy_opts_t::staged_commit, webdav_copy_errno_to_status(), webdav_copy_file_vfs_init(), webdav_dead_props_copy(), and webdav_delete_path_recursive().
Referenced by webdav_handle_copy().
webdav_copy_errno_to_status()
static ngx_int_t webdav_copy_errno_to_status (int err) static
Definition at line 31 of file copy.c.
References brix_http_map_ns_status(), BRIX_NS_CONFLICT, BRIX_NS_DENIED, BRIX_NS_EXISTS, BRIX_NS_IO_ERROR, BRIX_NS_NO_SPACE, BRIX_NS_NOT_EMPTY, BRIX_NS_NOT_FOUND, BRIX_NS_OK, and BRIX_NS_TOO_LONG.
Referenced by webdav_copy_do_file().
webdav_copy_file_vfs_init()
static void webdav_copy_file_vfs_init (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const char * src_path, brix_vfs_ctx_t * vctx) static
Definition at line 593 of file copy.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_WEBDAV, brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_bind_backend_mint(), brix_vfs_ctx_init(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, brix_vfs_ctx_t::pool, ngx_http_brix_shared_conf_t::root_canon, ngx_http_brix_shared_conf_t::storage_credential_dir, ngx_http_brix_shared_conf_t::storage_credential_fallback, ngx_http_brix_shared_conf_t::storage_credential_mint_ca_cert, ngx_http_brix_shared_conf_t::storage_credential_mint_ca_key, ngx_http_brix_shared_conf_t::storage_credential_mint_ttl, and webdav_vfs_bind_deleg().
Referenced by webdav_copy_do_file().
webdav_copy_job_init()
static void webdav_copy_job_init (webdav_copy_job_t * job, ngx_log_t * log, const char * root_canon, const webdav_copy_req_t * req) static
Definition at line 128 of file copy.c.
References webdav_copy_job_t::depth_infinity, webdav_copy_req_t::depth_infinity, webdav_copy_job_t::dst_existed, webdav_copy_req_t::dst_existed, webdav_copy_job_t::dst_path, webdav_copy_req_t::dst_path, webdav_copy_req_t::dst_sb, webdav_copy_job_t::dst_was_dir, log, webdav_copy_job_t::log, webdav_copy_job_t::root_canon, webdav_copy_job_t::src_mode, webdav_copy_job_t::src_path, webdav_copy_req_t::src_path, and webdav_copy_req_t::src_sb.
Referenced by webdav_copy_do_collection().
webdav_copy_parse_request()
static ngx_int_t webdav_copy_parse_request (ngx_http_request_t * r, webdav_copy_req_t * req) static
Definition at line 434 of file copy.c.
References brix_http_overwrite_forbidden(), webdav_copy_req_t::depth_infinity, webdav_copy_req_t::dest_decoded, webdav_copy_req_t::overwrite, webdav_destination_extract_path(), webdav_tpc_find_header, and webdav_urldecode().
Referenced by webdav_handle_copy().
webdav_copy_probe()
static ngx_int_t webdav_copy_probe (ngx_http_request_t * r, const char * path, struct stat * sb) static
Definition at line 383 of file copy.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_WEBDAV, brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), brix_vfs_probe(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, brix_vfs_stat_t::dev, ngx_http_brix_webdav_req_ctx_t::identity, brix_vfs_stat_t::ino, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, ngx_http_brix_webdav_module, brix_vfs_ctx_t::pool, ngx_http_brix_shared_conf_t::root_canon, brix_vfs_stat_t::size, ngx_http_brix_shared_conf_t::storage_credential_dir, ngx_http_brix_shared_conf_t::storage_credential_fallback, and webdav_vfs_bind_deleg().
Referenced by webdav_copy_resolve_pair().
webdav_copy_resolve_pair()
static ngx_int_t webdav_copy_resolve_pair (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, webdav_copy_req_t * req) static
Definition at line 487 of file copy.c.
References ngx_http_brix_webdav_loc_conf_t::common, webdav_copy_req_t::dest_decoded, webdav_copy_req_t::dst_existed, webdav_copy_req_t::dst_path, webdav_copy_req_t::dst_sb, ngx_http_brix_webdav_resolve_path(), webdav_copy_req_t::overwrite, ngx_http_brix_shared_conf_t::root_canon, webdav_copy_req_t::src_path, webdav_copy_req_t::src_sb, webdav_check_copy_conditionals(), webdav_check_locks_tree(), webdav_copy_probe(), and webdav_resolve_destination_path().
Referenced by webdav_handle_copy().
webdav_copy_thread_pool()
static ngx_thread_pool_t * webdav_copy_thread_pool (ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 300 of file copy.c.
References ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::thread_pool, and ngx_http_brix_shared_conf_t::thread_pool_name.
Referenced by webdav_copy_collection_post_task().
webdav_handle_copy()
ngx_int_t webdav_handle_copy (ngx_http_request_t * r)
Definition at line 683 of file copy.c.
References webdav_copy_req_t::depth_infinity, webdav_copy_req_t::dst_existed, ngx_http_brix_webdav_module, webdav_copy_req_t::src_sb, webdav_copy_do_collection(), webdav_copy_do_file(), webdav_copy_parse_request(), webdav_copy_resolve_pair(), and webdav_send_no_body().
Referenced by webdav_dispatch_copy().