nginx-xrootd: src/protocols/root/handshake/sigver.c File Reference
sigver.c File Reference
#include "handshake.h"
#include "auth/gsi/gsi_core.h"
Functions
static ngx_int_t brix_verify_sigver_hmac (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_verify_pending_sigver (brix_ctx_t *ctx, ngx_connection_t *c)
static int brix_sigver_opcode_requires (uint16_t opcode, ngx_uint_t level)
ngx_int_t brix_signing_enforce_level (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_signing_enforce_level()
ngx_int_t brix_signing_enforce_level (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 145 of file sigver.c.
References BRIX_DISPATCH_CONTINUE, brix_send_error(), brix_sigver_opcode_requires(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, kXR_NotAuthorized, brix_ctx_sigver_t::nodata, brix_ctx_t::recv, ngx_stream_brix_srv_conf_t::security_level, brix_ctx_sigver_t::signing_active, brix_ctx_t::sigver, and brix_ctx_sigver_t::verified.
Referenced by brix_dispatch().
brix_sigver_opcode_requires()
static int brix_sigver_opcode_requires (uint16_t opcode, ngx_uint_t level) static
Definition at line 130 of file sigver.c.
References brix_gsi_sigver_required().
Referenced by brix_signing_enforce_level().
brix_verify_pending_sigver()
ngx_int_t brix_verify_pending_sigver (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 87 of file sigver.c.
References BRIX_DISPATCH_CONTINUE, brix_send_error(), brix_verify_sigver_hmac(), c, brix_ctx_recv_t::cur_reqid, brix_ctx_sigver_t::expectrid, kXR_InvalidRequest, kXR_sigver, brix_ctx_sigver_t::pending, brix_ctx_t::recv, brix_ctx_sigver_t::signing_active, brix_ctx_t::sigver, and brix_ctx_sigver_t::verified.
Referenced by brix_dispatch().
brix_verify_sigver_hmac()
static ngx_int_t brix_verify_sigver_hmac (brix_ctx_t * ctx, ngx_connection_t * c) static
Definition at line 46 of file sigver.c.
References BRIX_DISPATCH_CONTINUE, brix_gsi_sigver_hmac(), brix_send_error(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, brix_ctx_recv_t::hdr_buf, brix_ctx_sigver_t::hmac, kXR_NotAuthorized, kXR_ServerError, brix_ctx_sigver_t::nodata, brix_ctx_recv_t::payload, brix_ctx_t::recv, brix_ctx_sigver_t::seqno, brix_ctx_sigver_t::signing_key, and brix_ctx_t::sigver.
Referenced by brix_verify_pending_sigver().