nginx-xrootd: src/protocols/webdav/copy_internal.h File Reference
copy_internal.h File Reference
#include "webdav.h"
Data Structures
struct webdav_copy_req_t
Functions
ngx_int_t webdav_copy_do_collection (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const webdav_copy_req_t *req)
Function Documentation
webdav_copy_do_collection()
ngx_int_t webdav_copy_do_collection (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const webdav_copy_req_t * req)
Definition at line 333 of file copy_collection.c.
References ngx_http_brix_webdav_loc_conf_t::common, webdav_copy_req_t::depth_infinity, webdav_copy_job_t::log, ngx_http_brix_shared_conf_t::root_canon, webdav_copy_collection_execute(), webdav_copy_collection_post_task(), and webdav_copy_job_init().
Referenced by webdav_handle_copy().