nginx-xrootd: src/protocols/webdav/proxy.c File Reference
proxy.c File Reference
#include "proxy_internal.h"
#include "core/http/http_body.h"
Functions
ngx_int_t webdav_proxy_handler (ngx_http_request_t *r)
brix_webdav_backend_t * webdav_proxy_pick_backend (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
Function Documentation
webdav_proxy_handler()
ngx_int_t webdav_proxy_handler (ngx_http_request_t * r)
Definition at line 22 of file proxy.c.
References brix_http_read_body(), brix_proxy_pool_dec_in_flight(), brix_proxy_pool_select(), brix_webdav_backend_t::host, brix_proxy_be_pick_t::host, brix_proxy_be_pick_t::id, ngx_http_brix_webdav_module, ngx_memcpy, ngx_pcalloc(), brix_proxy_be_pick_t::port, webdav_proxy_ctx_t::proxy_be_id, ngx_http_brix_webdav_loc_conf_t::proxy_pool_enabled, brix_webdav_backend_t::resolved, webdav_proxy_ctx_t::selected_backend, brix_proxy_be_pick_t::sockaddr, brix_proxy_be_pick_t::socklen, brix_webdav_backend_t::ssl, brix_proxy_be_pick_t::ssl, ngx_http_brix_webdav_loc_conf_t::upstream_conf, brix_webdav_backend_t::url_base, brix_proxy_be_pick_t::url_base, webdav_proxy_abort_request(), webdav_proxy_create_request(), webdav_proxy_finalize_request(), webdav_proxy_pick_backend(), webdav_proxy_process_status_line(), and webdav_proxy_reinit_request().
Referenced by webdav_dispatch_inner().
webdav_proxy_pick_backend()
brix_webdav_backend_t * webdav_proxy_pick_backend (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 129 of file proxy.c.
References brix_webdav_backend_t::fail_count, brix_webdav_backend_t::fail_time, ngx_http_brix_webdav_loc_conf_t::upstream_backends, ngx_http_brix_webdav_loc_conf_t::upstream_fail_timeout, ngx_http_brix_webdav_loc_conf_t::upstream_max_fails, and ngx_http_brix_webdav_loc_conf_t::upstream_rr.
Referenced by webdav_proxy_handler().