nginx-xrootd: src/auth/pwd/auth.c File Reference
auth.c File Reference
#include "core/ngx_brix_module.h"
#include "protocols/root/session/registry.h"
#include "auth/gsi/gsi_core.h"
#include "protocols/root/protocol/gsi.h"
#include "pwd.h"
#include <openssl/evp.h>
#include <openssl/crypto.h>
#include <arpa/inet.h>
#include <string.h>
Functions
static uint32_t pwd_status_word (uint8_t ctype, uint8_t action, uint16_t options)
static ngx_int_t pwd_send_credsreq (brix_ctx_t *ctx, ngx_connection_t *c, EVP_PKEY *srv)
static ngx_int_t pwd_round1 (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
static ngx_int_t pwd_round2 (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_handle_pwd_auth (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_handle_pwd_auth()
ngx_int_t brix_handle_pwd_auth (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 263 of file auth.c.
References BRIX_AUTHN_PWD, brix_metric_auth(), BRIX_OP_AUTH, BRIX_PROTO_ROOT, BRIX_RETURN_ERR, c, brix_ctx_recv_t::cur_dlen, kXR_NotAuthorized, brix_ctx_recv_t::payload, brix_ctx_t::pwd, pwd_round1(), pwd_round2(), brix_ctx_t::recv, and brix_ctx_pwd_t::round.
Referenced by brix_handle_auth_inner().
pwd_round1()
static ngx_int_t pwd_round1 (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf) static
Definition at line 114 of file auth.c.
References BRIX_AUTHN_PWD, brix_gsi_cipher_keygen_from(), brix_gsi_cipher_parse_peer(), brix_gsi_cipher_session_key(), brix_gsi_find_bucket(), brix_metric_auth(), BRIX_OP_AUTH, BRIX_PROTO_ROOT, BRIX_PWD_SESSION_KEYLEN, BRIX_RETURN_ERR, brix_send_error(), c, brix_ctx_recv_t::cur_dlen, kXR_NotAuthorized, kXR_ServerError, kXRS_puk, kXRS_user, ngx_memcpy, brix_ctx_recv_t::payload, brix_ctx_t::pwd, pwd_send_credsreq(), brix_ctx_t::recv, brix_ctx_pwd_t::round, brix_ctx_pwd_t::session_key, and brix_ctx_pwd_t::user.
Referenced by brix_handle_pwd_auth().
pwd_round2()
static ngx_int_t pwd_round2 (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf) static
Definition at line 172 of file auth.c.
References brix_ctx_token_t::auth, brix_ctx_login_t::auth_done, BRIX_AUTHN_PWD, brix_gsi_cipher_decrypt(), brix_gsi_cipher_lookup(), brix_gsi_find_bucket(), brix_identity_set_dn(), brix_metric_auth(), BRIX_OP_AUTH, BRIX_PROTO_ROOT, brix_pwd_file_lookup(), BRIX_PWD_HASH_LEN, BRIX_PWD_MAX_SALT, brix_pwd_verify(), BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_send_error(), brix_session_register(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_login_t::dn, brix_ctx_t::identity, kXR_NoMemory, kXR_NotAuthorized, kXRS_creds, kXRS_main, brix_ctx_t::login, ngx_memcpy, brix_ctx_recv_t::payload, brix_ctx_login_t::primary_vo, brix_ctx_t::pwd, ngx_stream_brix_srv_conf_t::pwd_file, brix_ctx_t::recv, brix_ctx_login_t::sessid, brix_ctx_pwd_t::session_key, brix_ctx_t::token, brix_ctx_pwd_t::user, and brix_ctx_login_t::vo_list.
Referenced by brix_handle_pwd_auth().
pwd_send_credsreq()
static ngx_int_t pwd_send_credsreq (brix_ctx_t * ctx, ngx_connection_t * c, EVP_PKEY * srv) static
Definition at line 61 of file auth.c.
References brix_build_resp_hdr(), brix_gbuf_bucket(), brix_gbuf_end(), brix_gbuf_free(), brix_gbuf_init(), brix_gbuf_raw(), brix_gbuf_u32(), brix_gsi_cipher_public(), brix_queue_response(), brix_send_error(), c, brix_ctx_recv_t::cur_streamid, brix_gbuf::err, kpCT_normal, kXPS_credsreq, kXR_authmore, kXR_NoMemory, kXR_ServerError, kXRS_puk, kXRS_status, brix_gbuf::len, ngx_memcpy, brix_gbuf::p, pwd_status_word(), brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by pwd_round1().
pwd_status_word()
static uint32_t pwd_status_word (uint8_t ctype, uint8_t action, uint16_t options) static
Definition at line 45 of file auth.c.
Referenced by pwd_send_credsreq().