nginx-xrootd: src/auth/gsi/auth.c File Reference
auth.c File Reference
#include "gsi_internal.h"
#include "delegation.h"
#include "protocols/root/session/registry.h"
#include "auth/crypto/ocsp.h"
#include "auth/crypto/gsi_verify.h"
#include <openssl/err.h>
#include <openssl/pem.h>
Data Structures
struct gsi_auth_cred_route_t
Functions
static ngx_int_t gsi_promote_fullproxy (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_gsi_inflight_admit (brix_ctx_t *ctx, ngx_int_t cap)
void brix_gsi_inflight_release (brix_ctx_t *ctx)
static ngx_int_t brix_gsi_complete_auth (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
static ngx_int_t gsi_auth_route_credtype (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, ngx_int_t *out_rc)
static ngx_int_t gsi_auth_step_certreq (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
static ngx_int_t gsi_auth_step_sigpxy (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
static ngx_int_t gsi_cert_deny (brix_ctx_t *ctx, ngx_connection_t *c, STACK_OF(X509) *chain, const char *log_msg, const char *err_msg)
static ngx_int_t gsi_cert_verify (ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, STACK_OF(X509) *chain, X509 *leaf, brix_gsi_verify_result_t *verify_res)
static void gsi_cert_capture_dn (brix_ctx_t *ctx, ngx_connection_t *c, const brix_gsi_verify_result_t *verify_res)
static void gsi_cert_extract_voms (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, X509 *leaf, STACK_OF(X509) *chain)
static ngx_int_t gsi_auth_step_cert (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
static ngx_int_t brix_handle_auth_inner (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_handle_auth (brix_ctx_t *ctx, ngx_connection_t *c)
Variables
static ngx_uint_t brix_gsi_inflight
static const gsi_auth_cred_route_t gsi_auth_cred_routes []
Function Documentation
brix_gsi_complete_auth()
static ngx_int_t brix_gsi_complete_auth (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf) static
Definition at line 157 of file auth.c.
References brix_ctx_login_t::auth_done, BRIX_ATOMIC_INC, BRIX_AUTHN_GSI, brix_gsi_inflight_release(), brix_identity_set_dn(), brix_identity_set_vos_csv(), brix_metrics_shared(), BRIX_OP_AUTH, brix_rate_limit_check(), BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_sanitize_log_string(), brix_send_error(), brix_session_register(), brix_track_unique_user(), brix_track_vo_activity(), BRIX_VO_MAX_TRACKED, BRIX_VO_NAME_LEN, c, brix_ctx_login_t::dn, brix_ctx_t::identity, kXR_NoMemory, kXR_NotAuthorized, brix_ctx_t::login, ngx_brix_vo_slot_t::name, brix_ctx_login_t::peer_ip, brix_ctx_login_t::primary_vo, ngx_brix_vo_slot_t::requests_total, brix_ctx_login_t::sessid, ngx_brix_vo_global_t::slots, ngx_brix_metrics_t::vo_global, and brix_ctx_login_t::vo_list.
Referenced by gsi_auth_step_cert(), and gsi_auth_step_sigpxy().
brix_gsi_inflight_admit()
ngx_int_t brix_gsi_inflight_admit (brix_ctx_t * ctx, ngx_int_t cap)
Definition at line 125 of file auth.c.
References brix_gsi_inflight, brix_ctx_login_t::gsi_counted, and brix_ctx_t::login.
Referenced by gsi_auth_step_certreq().
brix_gsi_inflight_release()
void brix_gsi_inflight_release (brix_ctx_t * ctx)
Definition at line 139 of file auth.c.
References brix_gsi_inflight, brix_ctx_login_t::gsi_counted, and brix_ctx_t::login.
Referenced by brix_gsi_complete_auth(), and brix_on_disconnect().
brix_handle_auth()
ngx_int_t brix_handle_auth (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 662 of file auth.c.
References brix_ctx_login_t::auth_done, brix_ctx_login_t::auth_fail_count, brix_handle_auth_inner(), BRIX_MAX_AUTH_ATTEMPTS, brix_send_error(), c, brix_ctx_recv_t::cur_body, brix_ctx_recv_t::cur_dlen, kXGC_certreq, kXR_NotAuthorized, brix_ctx_t::login, ngx_memcpy, brix_ctx_recv_t::payload, brix_ctx_t::pwd, brix_ctx_t::recv, brix_ctx_pwd_t::round, and brix_ctx_login_t::user.
Referenced by brix_dispatch_session_opcode().
brix_handle_auth_inner()
static ngx_int_t brix_handle_auth_inner (brix_ctx_t * ctx, ngx_connection_t * c) static
Definition at line 598 of file auth.c.
References brix_ctx_login_t::auth_done, BRIX_AUTH_NONE, brix_send_error(), brix_send_ok(), c, brix_ctx_recv_t::cur_dlen, gsi_auth_route_credtype(), gsi_auth_step_cert(), gsi_auth_step_certreq(), gsi_auth_step_sigpxy(), kXGC_cert, kXGC_certreq, kXGC_sigpxy, kXR_NotAuthorized, brix_ctx_login_t::logged_in, brix_ctx_t::login, ngx_memcpy, ngx_stream_brix_module, brix_ctx_recv_t::payload, brix_ctx_t::recv, and brix_ctx_t::session.
Referenced by brix_handle_auth().
gsi_auth_route_credtype()
static ngx_int_t gsi_auth_route_credtype (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, ngx_int_t * out_rc) static
Definition at line 276 of file auth.c.
References brix_sanitize_log_string(), brix_send_error(), c, gsi_auth_cred_route_t::cmp_len, brix_ctx_recv_t::cur_body, brix_ctx_recv_t::cur_dlen, gsi_auth_cred_route_t::deny_msg, gsi_auth_cred_routes, gsi_auth_cred_route_t::handler, kXR_NotAuthorized, gsi_auth_cred_route_t::mode, gsi_auth_cred_route_t::mode_alt, gsi_auth_cred_route_t::name, ngx_memcpy, and brix_ctx_t::recv.
Referenced by brix_handle_auth_inner().
gsi_auth_step_cert()
static ngx_int_t gsi_auth_step_cert (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf) static
Definition at line 507 of file auth.c.
References brix_gsi_begin_delegation(), brix_gsi_complete_auth(), brix_ocsp_check_cert(), BRIX_OP_AUTH, BRIX_RETURN_ERR, c, brix_ctx_gsi_t::deleg_await, brix_ctx_gsi_t::dh_key, brix_ctx_t::gsi, gsi_cert_capture_dn(), gsi_cert_deny(), gsi_cert_extract_voms(), gsi_cert_verify(), gsi_promote_fullproxy(), kXR_NotAuthorized, brix_ctx_gsi_t::sess_keylen, and STACK_OF().
Referenced by brix_handle_auth_inner().
gsi_auth_step_certreq()
static ngx_int_t gsi_auth_step_certreq (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf) static
Definition at line 334 of file auth.c.
References brix_gsi_inflight_admit(), brix_gsi_send_cert(), brix_send_wait(), and c.
Referenced by brix_handle_auth_inner().
gsi_auth_step_sigpxy()
static ngx_int_t gsi_auth_step_sigpxy (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf) static
Definition at line 358 of file auth.c.
References brix_gsi_complete_auth(), brix_gsi_handle_sigpxy(), BRIX_OP_AUTH, BRIX_RETURN_ERR, c, brix_ctx_gsi_t::deleg_await, brix_ctx_t::gsi, and kXR_NotAuthorized.
Referenced by brix_handle_auth_inner().
gsi_cert_capture_dn()
static void gsi_cert_capture_dn (brix_ctx_t * ctx, ngx_connection_t * c, const brix_gsi_verify_result_t * verify_res) static
Definition at line 438 of file auth.c.
References c, brix_ctx_login_t::dn, brix_gsi_verify_result_t::dn_buf, and brix_ctx_t::login.
Referenced by gsi_auth_step_cert().
gsi_cert_deny()
static ngx_int_t gsi_cert_deny (brix_ctx_t * ctx, ngx_connection_t * c, STACK_OF(X509) * chain, const char * log_msg, const char * err_msg) static
Definition at line 381 of file auth.c.
References brix_log_access(), BRIX_OP_AUTH, BRIX_OP_ERR, brix_send_error(), c, and kXR_NotAuthorized.
Referenced by gsi_auth_step_cert().
gsi_cert_extract_voms()
static void gsi_cert_extract_voms (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, X509 * leaf, STACK_OF(X509) * chain) static
Definition at line 463 of file auth.c.
References brix_extract_voms_info(), brix_sanitize_log_string(), brix_voms_available(), c, brix_ctx_t::login, brix_ctx_login_t::primary_vo, and brix_ctx_login_t::vo_list.
Referenced by gsi_auth_step_cert().
gsi_cert_verify()
static ngx_int_t gsi_cert_verify (ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, STACK_OF(X509) * chain, X509 * leaf, brix_gsi_verify_result_t * verify_res) static
Definition at line 404 of file auth.c.
References brix_gsi_verify_chain(), c, and STACK_OF().
Referenced by gsi_auth_step_cert().
gsi_promote_fullproxy()
static ngx_int_t gsi_promote_fullproxy (brix_ctx_t * ctx, ngx_connection_t * c) static
Definition at line 30 of file auth.c.
References c, brix_ctx_gsi_t::client_fullproxy_len, brix_ctx_gsi_t::client_fullproxy_pem, brix_ctx_t::deleg_proxy_pem, brix_ctx_login_t::dn, brix_ctx_t::gsi, key, brix_ctx_t::login, ngx_memcpy, and ngx_pnalloc().
Referenced by gsi_auth_step_cert().
Variable Documentation
brix_gsi_inflight
ngx_uint_t brix_gsi_inflight static
Definition at line 122 of file auth.c.
Referenced by brix_gsi_inflight_admit(), and brix_gsi_inflight_release().
gsi_auth_cred_routes
const gsi_auth_cred_route_t gsi_auth_cred_routes[] static
Initial value:
= {
    { "ztn",  3,  2  ,  3  , "token auth not enabled",
      brix_handle_token_auth },
    { "sss",  3,  4  ,    4  ,  "SSS auth not enabled",
      brix_handle_sss_auth },
    { "unix", 4,  5  ,   5  , "unix auth not enabled",
      brix_handle_unix_auth },
    { "krb5", 4,  6  ,   6  , "krb5 auth not enabled",
      brix_handle_krb5_auth },
    { "host", 4,  7  ,   7  , "host auth not enabled",
      brix_handle_host_auth },
    { "pwd",  4,  8  ,    8  ,  "pwd auth not enabled",
      brix_handle_pwd_auth },
    { "gsi",  3,  1  ,    3  , "GSI auth not enabled",
      NULL },
}
Definition at line 244 of file auth.c.
Referenced by gsi_auth_route_credtype().