nginx-xrootd: src/core/aio/uring.h File Reference
uring.h File Reference
Enumerations
enum brix_uring_op_e {
XRD_URING_OP_READ = 0 , XRD_URING_OP_WRITE , XRD_URING_OP_READV , XRD_URING_OP_WRITEV ,
XRD_URING_OP_NONE
}
Functions
ngx_int_t brix_uring_runtime_available (void)
ngx_int_t brix_uring_validate_conf (ngx_conf_t *cf)
ngx_int_t brix_uring_init_worker (ngx_cycle_t *cycle)
void brix_uring_exit_worker (ngx_cycle_t *cycle)
ngx_int_t brix_uring_killswitch_configure (ngx_conf_t *cf)
ngx_atomic_t * brix_uring_killswitch_ptr (void)
ngx_int_t brix_uring_killswitch_set (ngx_uint_t disabled)
ngx_int_t brix_uring_killswitch_get (void)
ngx_int_t brix_uring_panicfile_arm (ngx_cycle_t *cycle, ngx_str_t *path)
void brix_uring_admin_set_enabled (ngx_uint_t on)
ngx_int_t brix_uring_admin_enabled (void)
Enumeration Type Documentation
brix_uring_op_e
enum brix_uring_op_e
Enumerator
XRD_URING_OP_READ
XRD_URING_OP_WRITE
XRD_URING_OP_READV
XRD_URING_OP_WRITEV
XRD_URING_OP_NONE
Definition at line 79 of file uring.h.
Function Documentation
brix_uring_admin_enabled()
ngx_int_t brix_uring_admin_enabled (void)
Definition at line 128 of file uring_admin.c.
References brix_uring_admin_on.
Referenced by admin_route_io_uring().
brix_uring_admin_set_enabled()
void brix_uring_admin_set_enabled (ngx_uint_t on)
Definition at line 122 of file uring_admin.c.
References brix_uring_admin_on.
brix_uring_exit_worker()
void brix_uring_exit_worker (ngx_cycle_t * cycle)
Definition at line 210 of file uring.c.
Referenced by brix_exit_process().
brix_uring_init_worker()
ngx_int_t brix_uring_init_worker (ngx_cycle_t * cycle)
Definition at line 203 of file uring.c.
Referenced by ngx_stream_brix_init_process().
brix_uring_killswitch_configure()
ngx_int_t brix_uring_killswitch_configure (ngx_conf_t * cf)
Definition at line 74 of file uring_admin.c.
References brix_uring_ks_zone, brix_uring_ks_zone_init(), name, and ngx_stream_brix_module.
brix_uring_killswitch_get()
ngx_int_t brix_uring_killswitch_get (void)
Definition at line 114 of file uring_admin.c.
References brix_uring_killswitch_ptr().
Referenced by admin_io_uring_get().
brix_uring_killswitch_ptr()
ngx_atomic_t * brix_uring_killswitch_ptr (void)
Definition at line 93 of file uring_admin.c.
References brix_uring_ks_zone.
Referenced by brix_uring_killswitch_get(), and brix_uring_killswitch_set().
brix_uring_killswitch_set()
ngx_int_t brix_uring_killswitch_set (ngx_uint_t disabled)
Definition at line 102 of file uring_admin.c.
References brix_uring_killswitch_ptr().
Referenced by admin_io_uring_set().
brix_uring_panicfile_arm()
ngx_int_t brix_uring_panicfile_arm (ngx_cycle_t * cycle, ngx_str_t * path)
Definition at line 161 of file uring_admin.c.
References brix_maint_timer_conn, brix_uring_panic_handler(), brix_uring_panic_path, brix_uring_panic_timer, and ngx_memcpy.
brix_uring_runtime_available()
ngx_int_t brix_uring_runtime_available (void)
Definition at line 207 of file uring_probe.c.
Referenced by brix_uring_validate_conf().
brix_uring_validate_conf()
ngx_int_t brix_uring_validate_conf (ngx_conf_t * cf)
Definition at line 228 of file uring_probe.c.
References BRIX_IO_URING_MIN_KERNEL_MAJOR, BRIX_IO_URING_MIN_KERNEL_MINOR, brix_uring_any_block_on(), and brix_uring_runtime_available().
Referenced by ngx_stream_brix_postconfiguration().