nginx-xrootd: src/core/aio/uring.c File Reference
uring.c File Reference
#include "core/ngx_brix_module.h"
#include "aio.h"
#include "uring.h"
Functions
static ngx_int_t brix_uring_any_block_on (ngx_conf_t *cf)
ngx_int_t brix_uring_runtime_available (void)
ngx_int_t brix_uring_init_worker (ngx_cycle_t *cycle)
void brix_uring_exit_worker (ngx_cycle_t *cycle)
ngx_int_t brix_uring_validate_conf (ngx_conf_t *cf)
Function Documentation
brix_uring_any_block_on()
static ngx_int_t brix_uring_any_block_on (ngx_conf_t * cf) static
Definition at line 33 of file uring.c.
References BRIX_IO_URING_ON, ngx_stream_brix_srv_conf_t::common, ngx_http_brix_shared_conf_t::enable, ngx_stream_brix_srv_conf_t::io_uring, and ngx_stream_brix_module.
Referenced by brix_uring_validate_conf().
brix_uring_exit_worker()
void brix_uring_exit_worker (ngx_cycle_t * cycle)
Definition at line 660 of file uring.c.
Referenced by brix_exit_process().
brix_uring_init_worker()
ngx_int_t brix_uring_init_worker (ngx_cycle_t * cycle)
Definition at line 653 of file uring.c.
Referenced by ngx_stream_brix_init_process().
brix_uring_runtime_available()
ngx_int_t brix_uring_runtime_available (void)
Definition at line 645 of file uring.c.
Referenced by brix_uring_validate_conf().
brix_uring_validate_conf()
ngx_int_t brix_uring_validate_conf (ngx_conf_t * cf)
Definition at line 681 of file uring.c.
References BRIX_IO_URING_MIN_KERNEL_MAJOR, BRIX_IO_URING_MIN_KERNEL_MINOR, brix_uring_any_block_on(), and brix_uring_runtime_available().
Referenced by ngx_stream_brix_postconfiguration().