nginx-xrootd: src/observability/metrics/s3.c File Reference
s3.c File Reference
#include "metrics_internal.h"
Functions
void brix_export_s3_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
Variables
static const char * brix_s3_method_names [8]
static const char * brix_s3_auth_names [8]
static const char * brix_s3_put_names [4]
static const char * brix_s3_event_names [8]
Function Documentation
brix_export_s3_metrics()
void brix_export_s3_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 73 of file s3.c.
References ngx_brix_s3_metrics_t::auth_total, BRIX_HTTP_NSTATUS, brix_http_range_result_names, brix_http_status_names, brix_s3_auth_names, brix_s3_event_names, brix_s3_method_names, BRIX_S3_NAUTH_RESULTS, BRIX_S3_NEVENTS, BRIX_S3_NMETHODS, BRIX_S3_NPUT_MODES, BRIX_S3_NRANGE_RESULTS, brix_s3_put_names, ngx_brix_s3_metrics_t::bytes_rx_ipv4_total, ngx_brix_s3_metrics_t::bytes_rx_total, ngx_brix_s3_metrics_t::bytes_tx_ipv4_total, ngx_brix_s3_metrics_t::bytes_tx_total, ngx_brix_s3_metrics_t::events_total, ngx_brix_s3_metrics_t::list_common_prefixes_total, ngx_brix_s3_metrics_t::list_contents_total, ngx_brix_s3_metrics_t::list_truncated_total, mw_emit_labeled(), mw_emit_scalar(), mw_printf(), ngx_brix_s3_metrics_t::put_body_total, ngx_brix_s3_metrics_t::range_total, ngx_brix_s3_metrics_t::requests_total, ngx_brix_s3_metrics_t::responses_total, and ngx_brix_metrics_t::s3.
Referenced by brix_export_prometheus_metrics().
Variable Documentation
brix_s3_auth_names
const char* brix_s3_auth_names[8] static
Initial value:
= {
    "anonymous",
    "sigv4_ok",
    "missing",
    "malformed",
    "bad_access_key",
    "bad_date",
    "signature_mismatch",
    "internal_error",
}
Definition at line 31 of file s3.c.
Referenced by brix_export_s3_metrics().
brix_s3_event_names
const char* brix_s3_event_names[8] static
Initial value:
= {
    "invalid_uri",
    "access_denied",
    "no_such_key",
    "write_disabled",
    "method_not_allowed",
    "internal_error",
    "dir_sentinel",
    "delete_missing",
}
Definition at line 55 of file s3.c.
Referenced by brix_export_s3_metrics().
brix_s3_method_names
const char* brix_s3_method_names[8] static
Initial value:
= {
    "GET",
    "HEAD",
    "PUT",
    "DELETE",
    "LIST",
    "POST",
    "OPTIONS",
    "OTHER",
}
Definition at line 17 of file s3.c.
Referenced by brix_export_s3_metrics().
brix_s3_put_names
const char* brix_s3_put_names[4] static
Initial value:
= {
    "empty",
    "memory",
    "spooled",
    "mixed",
}
Definition at line 45 of file s3.c.
Referenced by brix_export_s3_metrics().