nginx-xrootd: src/protocols/root/connection/tls.c File Reference
tls.c File Reference
#include "tls.h"
#include <ngx_event.h>
#include <ngx_event_connect.h>
#include <ngx_event_posted.h>
#include <ngx_stream.h>
#include <ngx_event_openssl.h>
#include <openssl/err.h>
Functions
void brix_tls_handshake_done (ngx_connection_t *c)
void brix_start_tls (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_start_tls()
void brix_start_tls (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 45 of file tls.c.
References brix_close_all_files(), brix_on_disconnect(), brix_tls_handshake_done(), c, s, brix_ctx_t::state, and XRD_ST_TLS_HANDSHAKE.
Referenced by brix_recv_after_header(), brix_recv_run_deferred(), and ngx_stream_brix_send().
brix_tls_handshake_done()
void brix_tls_handshake_done (ngx_connection_t * c)
Definition at line 25 of file tls.c.
References brix_close_all_files(), brix_on_disconnect(), c, brix_ctx_recv_t::hdr_pos, ngx_stream_brix_module, ngx_stream_brix_recv(), ngx_stream_brix_send(), brix_ctx_t::recv, s, brix_ctx_t::state, brix_ctx_t::tls_pending, and XRD_ST_REQ_HEADER.
Referenced by brix_start_tls().