nginx-xrootd: src/protocols/root/response/status.c File Reference
status.c File Reference
#include "core/ngx_brix_module.h"
#include "core/compat/alloc_guard.h"
#include "core/compat/pgio.h"
Functions
ngx_int_t brix_send_pgwrite_status (brix_ctx_t *ctx, ngx_connection_t *c, int64_t write_offset)
ngx_int_t brix_send_pgwrite_cse (brix_ctx_t *ctx, ngx_connection_t *c, int64_t write_offset, const xrdp_pg_bad_t *bad, size_t n)
void brix_build_pgread_status (brix_ctx_t *ctx, int64_t file_offset, uint32_t total_with_crcs, ServerStatusResponse_pgRead *out)
Function Documentation
brix_build_pgread_status()
void brix_build_pgread_status (brix_ctx_t * ctx, int64_t file_offset, uint32_t total_with_crcs, ServerStatusResponse_pgRead * out)
Definition at line 134 of file status.c.
References ServerStatusResponse_pgRead::bdy, brix_crc32c(), ServerResponseBody_Status::crc32c, brix_ctx_recv_t::cur_streamid, ServerResponseHdr::dlen, ServerResponseBody_Status::dlen, ServerStatusResponse_pgRead::hdr, kXR_1stRequest, kXR_FinalResult, kXR_pgread, kXR_status, ServerResponseBody_pgRead::offset, ServerStatusResponse_pgRead::pgr, brix_ctx_t::recv, ServerResponseBody_Status::requestid, ServerResponseBody_Status::reserved, ServerResponseBody_Status::resptype, ServerResponseHdr::status, ServerResponseHdr::streamid, and ServerResponseBody_Status::streamID.
Referenced by brix_build_pgread_chain(), brix_pgread_aio_done(), and brix_pgread_parse_validate().
brix_send_pgwrite_cse()
ngx_int_t brix_send_pgwrite_cse (brix_ctx_t * ctx, ngx_connection_t * c, int64_t write_offset, const xrdp_pg_bad_t * bad, size_t n)
Definition at line 72 of file status.c.
References ServerStatusResponse_pgWrite::bdy, brix_crc32c(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), brix_send_pgwrite_status(), c, ServerResponseBody_Status::crc32c, ServerResponseBody_pgWrCSE::cseCRC, brix_ctx_recv_t::cur_streamid, xrdp_pg_bad_t::dlen, ServerResponseHdr::dlen, ServerResponseBody_Status::dlen, ServerResponseBody_pgWrCSE::dlFirst, ServerResponseBody_pgWrCSE::dlLast, ServerStatusResponse_pgWrite::hdr, kXR_1stRequest, kXR_FinalResult, kXR_pgwrite, kXR_status, xrdp_pg_bad_t::off, ServerResponseBody_pgWrite::offset, ServerStatusResponse_pgWrite::pgw, brix_ctx_t::recv, ServerResponseBody_Status::requestid, ServerResponseBody_Status::reserved, ServerResponseBody_Status::resptype, ServerResponseHdr::status, ServerResponseHdr::streamid, and ServerResponseBody_Status::streamID.
Referenced by brix_write_aio_serial_reply_ok(), and pgwrite_execute_sync().
brix_send_pgwrite_status()
ngx_int_t brix_send_pgwrite_status (brix_ctx_t * ctx, ngx_connection_t * c, int64_t write_offset)
Definition at line 18 of file status.c.
References ServerStatusResponse_pgWrite::bdy, brix_crc32c(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), c, ServerResponseBody_Status::crc32c, brix_ctx_recv_t::cur_streamid, ServerResponseHdr::dlen, ServerResponseBody_Status::dlen, ServerStatusResponse_pgWrite::hdr, kXR_1stRequest, kXR_FinalResult, kXR_pgwrite, kXR_status, ServerResponseBody_pgWrite::offset, ServerStatusResponse_pgWrite::pgw, brix_ctx_t::recv, ServerResponseBody_Status::requestid, ServerResponseBody_Status::reserved, ServerResponseBody_Status::resptype, ServerResponseHdr::status, ServerResponseHdr::streamid, and ServerResponseBody_Status::streamID.
Referenced by brix_handle_pgwrite(), brix_send_pgwrite_cse(), brix_write_aio_serial_reply_ok(), ckp_xeq_pgwrite(), pgwrite_decode_collect(), and pgwrite_execute_sync().