nginx-xrootd: src/auth/host/auth.c File Reference
auth.c File Reference
#include "core/ngx_brix_module.h"
#include "protocols/root/session/registry.h"
#include "auth/authz/acc/acc.h"
#include <string.h>
#include <sys/socket.h>
Functions
static ngx_flag_t brix_host_pattern_match (const char *host, const ngx_str_t *pat)
static ngx_flag_t brix_host_allowed (ngx_stream_brix_srv_conf_t *conf, const char *host)
ngx_int_t brix_handle_host_auth (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_handle_host_auth()
ngx_int_t brix_handle_host_auth (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 84 of file auth.c.
References brix_ctx_token_t::auth, brix_ctx_login_t::auth_done, brix_acc_resolve_peer(), BRIX_AUTHN_HOST, brix_host_allowed(), brix_identity_set_dn(), brix_metric_auth(), BRIX_OP_AUTH, BRIX_PROTO_ROOT, BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_sanitize_log_string(), brix_send_error(), brix_session_register(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_login_t::dn, host, brix_ctx_t::identity, kXR_NoMemory, kXR_NotAuthorized, brix_ctx_t::login, brix_ctx_recv_t::payload, brix_ctx_login_t::primary_vo, brix_ctx_t::recv, brix_ctx_login_t::sessid, brix_ctx_t::token, and brix_ctx_login_t::vo_list.
brix_host_allowed()
static ngx_flag_t brix_host_allowed (ngx_stream_brix_srv_conf_t * conf, const char * host) static
Definition at line 60 of file auth.c.
References brix_host_pattern_match(), and host.
Referenced by brix_handle_host_auth().
brix_host_pattern_match()
static ngx_flag_t brix_host_pattern_match (const char * host, const ngx_str_t * pat) static
Definition at line 40 of file auth.c.
References host.
Referenced by brix_host_allowed().