nginx-xrootd: src/auth/unix/auth.c File Reference
auth.c File Reference
#include "core/ngx_brix_module.h"
#include "observability/metrics/unified.h"
#include "protocols/root/session/registry.h"
#include <string.h>
Data Structures
struct brix_unix_names_t
Functions
static ngx_flag_t brix_unix_peer_is_loopback (ngx_connection_t *c)
static ngx_flag_t brix_unix_name_byte_ok (u_char ch)
static ngx_int_t brix_unix_copy_name (char *dst, size_t dst_len, const u_char *src, size_t len)
static void brix_unix_track_identity (brix_ctx_t *ctx)
static ngx_int_t brix_unix_tag_ok (const brix_ctx_t *ctx)
static void brix_unix_next_token (const u_char **p, const u_char *end, const u_char **tok_start, size_t *tok_len)
static ngx_int_t brix_unix_parse_cred (const brix_ctx_t *ctx, brix_unix_names_t *names, const char **msg)
static ngx_int_t brix_unix_apply_identity (brix_ctx_t *ctx, ngx_connection_t *c, const brix_unix_names_t *names, int *code)
static void brix_unix_finalize (brix_ctx_t *ctx, ngx_connection_t *c, const brix_unix_names_t *names)
ngx_int_t brix_handle_unix_auth (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_handle_unix_auth()
ngx_int_t brix_handle_unix_auth (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 330 of file auth.c.
References BRIX_AUTHN_UNIX, brix_metric_auth(), BRIX_OP_AUTH, BRIX_PROTO_ROOT, BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_send_error(), brix_unix_apply_identity(), brix_unix_finalize(), brix_unix_parse_cred(), brix_unix_peer_is_loopback(), brix_unix_tag_ok(), c, kXR_NoMemory, and kXR_NotAuthorized.
brix_unix_apply_identity()
static ngx_int_t brix_unix_apply_identity (brix_ctx_t * ctx, ngx_connection_t * c, const brix_unix_names_t * names, int * code) static
Definition at line 258 of file auth.c.
References brix_ctx_token_t::auth, brix_ctx_login_t::auth_done, BRIX_AUTHN_UNIX, brix_identity_set_dn(), brix_identity_set_vos_csv(), c, code, brix_ctx_login_t::dn, brix_unix_names_t::group, brix_ctx_t::identity, kXR_NoMemory, brix_ctx_t::login, brix_ctx_login_t::primary_vo, brix_ctx_t::token, brix_unix_names_t::user, and brix_ctx_login_t::vo_list.
Referenced by brix_handle_unix_auth().
brix_unix_copy_name()
static ngx_int_t brix_unix_copy_name (char * dst, size_t dst_len, const u_char * src, size_t len) static
Definition at line 95 of file auth.c.
References brix_unix_name_byte_ok(), and ngx_memcpy.
Referenced by brix_unix_parse_cred().
brix_unix_finalize()
static void brix_unix_finalize (brix_ctx_t * ctx, ngx_connection_t * c, const brix_unix_names_t * names) static
Definition at line 296 of file auth.c.
References brix_sanitize_log_string(), brix_session_register(), BRIX_SSS_GROUP_MAX, BRIX_SSS_USER_MAX, brix_unix_track_identity(), c, brix_ctx_login_t::dn, brix_unix_names_t::group, brix_ctx_t::login, brix_ctx_login_t::sessid, brix_unix_names_t::user, and brix_ctx_login_t::vo_list.
Referenced by brix_handle_unix_auth().
brix_unix_name_byte_ok()
static ngx_flag_t brix_unix_name_byte_ok (u_char ch) static
Definition at line 78 of file auth.c.
Referenced by brix_unix_copy_name().
brix_unix_next_token()
static void brix_unix_next_token (const u_char ** p, const u_char * end, const u_char ** tok_start, size_t * tok_len) static
Definition at line 182 of file auth.c.
Referenced by brix_unix_parse_cred().
brix_unix_parse_cred()
static ngx_int_t brix_unix_parse_cred (const brix_ctx_t * ctx, brix_unix_names_t * names, const char ** msg) static
Definition at line 211 of file auth.c.
References brix_unix_copy_name(), brix_unix_next_token(), brix_ctx_recv_t::cur_dlen, brix_unix_names_t::group, brix_ctx_recv_t::payload, brix_ctx_t::recv, and brix_unix_names_t::user.
Referenced by brix_handle_unix_auth().
brix_unix_peer_is_loopback()
static ngx_flag_t brix_unix_peer_is_loopback (ngx_connection_t * c) static
Definition at line 51 of file auth.c.
References c.
Referenced by brix_handle_unix_auth().
brix_unix_tag_ok()
static ngx_int_t brix_unix_tag_ok (const brix_ctx_t * ctx) static
Definition at line 160 of file auth.c.
References brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by brix_handle_unix_auth().
brix_unix_track_identity()
static void brix_unix_track_identity (brix_ctx_t * ctx) static
Definition at line 124 of file auth.c.
References brix_metrics_shared(), brix_track_unique_user(), brix_track_vo_activity(), brix_ctx_login_t::dn, brix_ctx_t::login, and brix_ctx_login_t::primary_vo.
Referenced by brix_unix_finalize().