nginx-xrootd: src/protocols/s3/checksum.c File Reference
checksum.c File Reference
#include "s3.h"
#include "core/http/http_headers.h"
#include "core/http/http_query.h"
#include "core/compat/integrity_info.h"
#include "core/compat/hex.h"
#include "fs/vfs/vfs.h"
#include <fcntl.h>
#include <string.h>
#include <unistd.h>
Data Structures
struct s3_cksum_desc_t
Macros
#define S3_CKSUM_TABLE_N (sizeof(s3_cksum_table) / sizeof(s3_cksum_table[0]))
#define S3_CKSUM_DEFAULT_IDX 2 /* crc64nvme */
Functions
static void s3_cksum_vfs_unlink (ngx_http_request_t *r, const char *fs_path, const char *root_canon)
static brix_vfs_file_t * s3_cksum_vfs_open (ngx_http_request_t *r, const char *fs_path, const char *root_canon)
ngx_int_t s3_checksum_b64 (ngx_http_request_t *r, int fd, const char *path, const char *alg_name, ngx_flag_t cache_only, char *out, size_t outsz)
static const s3_cksum_desc_t * s3_cksum_by_token (const char *tok, size_t len)
static const s3_cksum_desc_t * s3_put_select_algo (ngx_http_request_t *r, ngx_table_elt_t **want_value, int *conflict)
s3_cksum_result_t s3_put_checksum_apply (ngx_http_request_t *r, const char *fs_path, const char *root_canon)
s3_cksum_result_t s3_content_md5_verify (ngx_http_request_t *r, const char *fs_path, const char *root_canon)
s3_cksum_result_t s3_put_trailer_checksum_apply (ngx_http_request_t *r, const char *fs_path, const char *root_canon, const char *algo_token, const char *value)
void s3_echo_object_checksums (ngx_http_request_t *r, int fd, const char *path)
Variables
static const s3_cksum_desc_t s3_cksum_table []
Macro Definition Documentation
S3_CKSUM_DEFAULT_IDX
#define S3_CKSUM_DEFAULT_IDX 2 /* crc64nvme */
Definition at line 55 of file checksum.c.
S3_CKSUM_TABLE_N
#define S3_CKSUM_TABLE_N (sizeof(s3_cksum_table) / sizeof(s3_cksum_table[0]))
Definition at line 51 of file checksum.c.
Function Documentation
s3_checksum_b64()
ngx_int_t s3_checksum_b64 (ngx_http_request_t * r, int fd, const char * path, const char * alg_name, ngx_flag_t cache_only, char * out, size_t outsz)
Definition at line 127 of file checksum.c.
References brix_integrity_opts_t::allow_xattr_cache, brix_hex_from_char(), brix_integrity_get_fd(), brix_integrity_info_t::hex, brix_integrity_opts_t::no_compute, brix_integrity_opts_t::require_regular_file, and brix_integrity_opts_t::update_xattr_cache.
Referenced by s3_echo_object_checksums(), s3_put_checksum_apply(), and s3_put_trailer_checksum_apply().
s3_cksum_by_token()
static const s3_cksum_desc_t * s3_cksum_by_token (const char * tok, size_t len) static
Definition at line 176 of file checksum.c.
References s3_cksum_table, S3_CKSUM_TABLE_N, and tok.
Referenced by s3_put_select_algo(), and s3_put_trailer_checksum_apply().
s3_cksum_vfs_open()
static brix_vfs_file_t * s3_cksum_vfs_open (ngx_http_request_t * r, const char * fs_path, const char * root_canon) static
Definition at line 95 of file checksum.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_S3, brix_vfs_ctx_init(), BRIX_VFS_O_READ, brix_vfs_open(), ngx_http_s3_loc_conf_t::cache_root_canon, ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, and brix_vfs_ctx_t::pool.
Referenced by s3_content_md5_verify(), s3_put_checksum_apply(), and s3_put_trailer_checksum_apply().
s3_cksum_vfs_unlink()
static void s3_cksum_vfs_unlink (ngx_http_request_t * r, const char * fs_path, const char * root_canon) static
Definition at line 67 of file checksum.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_S3, brix_vfs_ctx_init(), brix_vfs_unlink(), ngx_http_s3_loc_conf_t::cache_root_canon, ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, and brix_vfs_ctx_t::pool.
Referenced by s3_content_md5_verify(), s3_put_checksum_apply(), and s3_put_trailer_checksum_apply().
s3_content_md5_verify()
s3_cksum_result_t s3_content_md5_verify (ngx_http_request_t * r, const char * fs_path, const char * root_canon)
Definition at line 338 of file checksum.c.
References brix_http_find_header(), brix_integrity_get_fd(), brix_vfs_close(), brix_vfs_file_fd(), brix_integrity_info_t::hex, brix_integrity_opts_t::require_regular_file, S3_CKSUM_CONFLICT, S3_CKSUM_ERROR, S3_CKSUM_MISMATCH, S3_CKSUM_OK, s3_cksum_vfs_open(), and s3_cksum_vfs_unlink().
Referenced by s3_put_checksum_failed().
s3_echo_object_checksums()
void s3_echo_object_checksums (ngx_http_request_t * r, int fd, const char * path)
Definition at line 459 of file checksum.c.
References b64, brix_http_find_header(), s3_checksum_b64(), S3_CHECKSUM_B64_MAX, S3_CKSUM_DEFAULT_IDX, s3_cksum_table, S3_CKSUM_TABLE_N, S3_HDR_CHECKSUM_TYPE, and s3_set_header().
Referenced by s3_get_echo_headers(), and s3_handle_head().
s3_put_checksum_apply()
s3_cksum_result_t s3_put_checksum_apply (ngx_http_request_t * r, const char * fs_path, const char * root_canon)
Definition at line 266 of file checksum.c.
References s3_cksum_desc_t::alg_name, b64, brix_vfs_close(), brix_vfs_file_fd(), s3_cksum_desc_t::header, s3_checksum_b64(), S3_CHECKSUM_B64_MAX, S3_CKSUM_CONFLICT, S3_CKSUM_DEFAULT_IDX, S3_CKSUM_ERROR, S3_CKSUM_MISMATCH, S3_CKSUM_OK, s3_cksum_table, s3_cksum_vfs_open(), s3_cksum_vfs_unlink(), S3_HDR_CHECKSUM_TYPE, s3_put_select_algo(), and s3_set_header().
Referenced by s3_put_checksum_failed().
s3_put_select_algo()
static const s3_cksum_desc_t * s3_put_select_algo (ngx_http_request_t * r, ngx_table_elt_t ** want_value, int * conflict) static
Definition at line 204 of file checksum.c.
References brix_http_find_header(), s3_cksum_by_token(), s3_cksum_table, and S3_CKSUM_TABLE_N.
Referenced by s3_put_checksum_apply().
s3_put_trailer_checksum_apply()
s3_cksum_result_t s3_put_trailer_checksum_apply (ngx_http_request_t * r, const char * fs_path, const char * root_canon, const char * algo_token, const char * value)
Definition at line 409 of file checksum.c.
References s3_cksum_desc_t::alg_name, b64, brix_vfs_close(), brix_vfs_file_fd(), s3_cksum_desc_t::header, s3_checksum_b64(), S3_CHECKSUM_B64_MAX, s3_cksum_by_token(), S3_CKSUM_CONFLICT, S3_CKSUM_ERROR, S3_CKSUM_MISMATCH, S3_CKSUM_OK, s3_cksum_vfs_open(), s3_cksum_vfs_unlink(), S3_HDR_CHECKSUM_TYPE, and s3_set_header().
Referenced by s3_chunk_finalize().
Variable Documentation
s3_cksum_table
const s3_cksum_desc_t s3_cksum_table[] static
Initial value:
= {
    { "crc32",     "crc32",     "x-amz-checksum-crc32"     },
    { "crc32c",    "crc32c",    "x-amz-checksum-crc32c"    },
    { "crc64nvme", "crc64nvme", "x-amz-checksum-crc64nvme" },
    { "sha1",      "sha1",      "x-amz-checksum-sha1"      },
    { "sha256",    "sha256",    "x-amz-checksum-sha256"    },
}
Definition at line 43 of file checksum.c.
Referenced by s3_cksum_by_token(), s3_echo_object_checksums(), s3_put_checksum_apply(), and s3_put_select_algo().