nginx-xrootd: src/net/proxy/pool.c File Reference
pool.c File Reference
#include "proxy_internal.h"
#include "core/compat/safe_size.h"
#include <openssl/md5.h>
Functions
void brix_proxy_up_status_init (ngx_stream_brix_srv_conf_t *conf)
void brix_proxy_up_mark_failed (brix_proxy_ctx_t *proxy)
void brix_proxy_up_mark_ok (brix_proxy_ctx_t *proxy)
static void brix_proxy_pool_evict (brix_proxy_pooled_conn_t *pc, ngx_connection_t *c)
static void brix_proxy_pool_read_handler (ngx_event_t *rev)
static void brix_proxy_pool_write_handler (ngx_event_t *wev)
static void brix_proxy_pool_ping_handler (ngx_event_t *ev)
void brix_proxy_pool_shutdown (void)
void brix_proxy_pool_init (void)
ngx_connection_t * brix_proxy_pool_get (brix_proxy_ctx_t *proxy, ngx_stream_brix_srv_conf_t *conf, int *idx_out)
void brix_proxy_pool_put (brix_proxy_ctx_t *proxy)
Variables
static ngx_queue_t proxy_pool
static ngx_uint_t proxy_pool_count
brix_proxy_up_status_t * proxy_up_status
static ngx_uint_t proxy_up_status_count
Function Documentation
brix_proxy_pool_evict()
static void brix_proxy_pool_evict (brix_proxy_pooled_conn_t * pc, ngx_connection_t * c) static
Definition at line 113 of file pool.c.
References c, brix_proxy_pooled_conn_t::ping_ev, proxy_pool_count, and brix_proxy_pooled_conn_t::queue.
Referenced by brix_proxy_pool_put(), brix_proxy_pool_read_handler(), and brix_proxy_pool_write_handler().
brix_proxy_pool_get()
ngx_connection_t * brix_proxy_pool_get (brix_proxy_ctx_t * proxy, ngx_stream_brix_srv_conf_t * conf, int * idx_out)
Definition at line 270 of file pool.c.
References brix_proxy_pooled_conn_t::auth_type, BRIX_PROXY_AUTH_FORWARD, BRIX_PROXY_FAIL_TIMEOUT, brix_proxy_read_handler(), brix_proxy_up_status_init(), brix_proxy_write_handler(), c, brix_proxy_up_status_t::checked, brix_proxy_pooled_conn_t::conn, brix_proxy_pooled_conn_t::ping_ev, proxy_pool, proxy_pool_count, proxy_up_status, brix_proxy_pooled_conn_t::token_hash, and brix_proxy_pooled_conn_t::upstream_idx.
Referenced by pc_select_endpoint().
brix_proxy_pool_init()
void brix_proxy_pool_init (void)
Definition at line 257 of file pool.c.
References proxy_pool, and proxy_pool_count.
Referenced by ngx_stream_brix_init_process().
brix_proxy_pool_ping_handler()
static void brix_proxy_pool_ping_handler (ngx_event_t * ev) static
Definition at line 172 of file pool.c.
References BRIX_PROXY_POOL_KEEPALIVE, c, brix_proxy_pooled_conn_t::conn, brix_proxy_pooled_conn_t::idle_since, brix_proxy_pooled_conn_t::keepalive_interval, proxy_pool_count, and brix_proxy_pooled_conn_t::queue.
Referenced by brix_proxy_pool_put().
brix_proxy_pool_put()
void brix_proxy_pool_put (brix_proxy_ctx_t * proxy)
Definition at line 359 of file pool.c.
References brix_proxy_pooled_conn_t::auth_type, BRIX_PROXY_AUTH_FORWARD, brix_proxy_pool_evict(), brix_proxy_pool_ping_handler(), brix_proxy_pool_read_handler(), BRIX_PROXY_POOL_SIZE, brix_proxy_pool_write_handler(), brix_proxy_pooled_conn_t::conn, brix_proxy_pooled_conn_t::idle_since, brix_proxy_pooled_conn_t::keepalive_interval, brix_proxy_pooled_conn_t::ping_ev, proxy_pool, proxy_pool_count, brix_proxy_pooled_conn_t::queue, brix_proxy_pooled_conn_t::token_hash, brix_proxy_pooled_conn_t::upstream_idx, and XRD_PX_IDLE.
Referenced by brix_proxy_cleanup_conn().
brix_proxy_pool_read_handler()
static void brix_proxy_pool_read_handler (ngx_event_t * rev) static
Definition at line 132 of file pool.c.
References brix_proxy_pool_evict(), and c.
Referenced by brix_proxy_pool_put().
brix_proxy_pool_shutdown()
void brix_proxy_pool_shutdown (void)
Definition at line 209 of file pool.c.
References brix_proxy_pooled_conn_t::conn, brix_proxy_pooled_conn_t::ping_ev, proxy_pool, proxy_pool_count, and brix_proxy_pooled_conn_t::queue.
Referenced by brix_exit_process().
brix_proxy_pool_write_handler()
static void brix_proxy_pool_write_handler (ngx_event_t * wev) static
Definition at line 158 of file pool.c.
References brix_proxy_pool_evict(), and c.
Referenced by brix_proxy_pool_put().
brix_proxy_up_mark_failed()
void brix_proxy_up_mark_failed (brix_proxy_ctx_t * proxy)
Definition at line 64 of file pool.c.
References BRIX_PROXY_MAX_FAILS, brix_proxy_up_status_t::checked, brix_proxy_up_status_t::down, fails, brix_proxy_up_status_t::fails, proxy_up_status, and proxy_up_status_count.
Referenced by brix_proxy_abort().
brix_proxy_up_mark_ok()
void brix_proxy_up_mark_ok (brix_proxy_ctx_t * proxy)
Definition at line 88 of file pool.c.
References brix_proxy_up_status_t::checked, brix_proxy_up_status_t::down, brix_proxy_up_status_t::fails, proxy_up_status, and proxy_up_status_count.
Referenced by proxy_bs_adopt_conn().
brix_proxy_up_status_init()
void brix_proxy_up_status_init (ngx_stream_brix_srv_conf_t * conf)
Definition at line 41 of file pool.c.
References brix_alloc_array(), proxy_up_status, and proxy_up_status_count.
Referenced by brix_proxy_pool_get().
Variable Documentation
proxy_pool
ngx_queue_t proxy_pool static
Definition at line 29 of file pool.c.
Referenced by brix_proxy_pool_get(), brix_proxy_pool_init(), brix_proxy_pool_put(), and brix_proxy_pool_shutdown().
proxy_pool_count
ngx_uint_t proxy_pool_count static
Definition at line 30 of file pool.c.
Referenced by brix_proxy_pool_evict(), brix_proxy_pool_get(), brix_proxy_pool_init(), brix_proxy_pool_ping_handler(), brix_proxy_pool_put(), and brix_proxy_pool_shutdown().
proxy_up_status
brix_proxy_up_status_t* proxy_up_status
Definition at line 33 of file pool.c.
Referenced by brix_proxy_pool_get(), brix_proxy_up_mark_failed(), brix_proxy_up_mark_ok(), brix_proxy_up_status_init(), and pc_pick_healthy_upstream().
proxy_up_status_count
ngx_uint_t proxy_up_status_count static
Definition at line 34 of file pool.c.
Referenced by brix_proxy_up_mark_failed(), brix_proxy_up_mark_ok(), and brix_proxy_up_status_init().