nginx-xrootd: src/tpc/common/auth.c File Reference
auth.c File Reference
#include "auth.h"
#include <limits.h>
Functions
static ngx_int_t brix_tpc_check_scope_path (const brix_identity_t *identity, const ngx_str_t *path, int need_write, ngx_log_t *log)
ngx_int_t brix_tpc_check_authz (const brix_identity_t *identity, const ngx_str_t *src_path, const ngx_str_t *dst_path, ngx_log_t *log)
Function Documentation
brix_tpc_check_authz()
ngx_int_t brix_tpc_check_authz (const brix_identity_t * identity, const ngx_str_t * src_path, const ngx_str_t * dst_path, ngx_log_t * log)
Definition at line 66 of file auth.c.
References brix_identity_t::auth_method, BRIX_AUTHN_S3KEY, brix_tpc_check_scope_path(), and log.
Referenced by brix_handle_open(), and webdav_tpc_authorize().
brix_tpc_check_scope_path()
static ngx_int_t brix_tpc_check_scope_path (const brix_identity_t * identity, const ngx_str_t * path, int need_write, ngx_log_t * log) static
Definition at line 29 of file auth.c.
References brix_identity_check_token_scope(), log, and PATH_MAX.
Referenced by brix_tpc_check_authz().