nginx-xrootd: src/protocols/s3/copy.c File Reference
copy.c File Reference
#include "s3.h"
#include "usermeta.h"
#include "fs/vfs/vfs.h"
#include "fs/path/path.h"
#include "core/compat/copy_range.h"
#include "core/http/http_headers.h"
#include "core/compat/staged_file.h"
#include <errno.h>
#include <fcntl.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include <limits.h>
#include "core/compat/str_dup.h"
Functions
static const char * s3_copy_find_header (ngx_http_request_t *r, const char *name, size_t nlen)
static void s3_copy_vfs_ctx (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, brix_vfs_ctx_t *vctx)
ngx_int_t s3_handle_copy_object (ngx_http_request_t *r, const char *dst_fs_path, ngx_http_s3_loc_conf_t *cf)
Function Documentation
s3_copy_find_header()
static const char * s3_copy_find_header (ngx_http_request_t * r, const char * name, size_t nlen) static
Definition at line 37 of file copy.c.
References brix_http_find_header(), brix_pstrdupz(), and name.
Referenced by s3_handle_copy_object().
s3_copy_vfs_ctx()
static void s3_copy_vfs_ctx (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, brix_vfs_ctx_t * vctx) static
Definition at line 55 of file copy.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_S3, brix_vfs_ctx_init(), ngx_http_s3_loc_conf_t::cache_root_canon, ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, brix_vfs_ctx_t::pool, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by s3_handle_copy_object().
s3_handle_copy_object()
ngx_int_t s3_handle_copy_object (ngx_http_request_t * r, const char * dst_fs_path, ngx_http_s3_loc_conf_t * cf)
Definition at line 72 of file copy.c.
References brix_format_iso8601(), brix_http_send_xml_buffer(), BRIX_S3_EVENT_ACCESS_DENIED, BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_EVENT_NO_SUCH_KEY, BRIX_S3_METRIC_INC, brix_vfs_copy(), brix_vfs_probe(), ngx_http_s3_loc_conf_t::common, brix_vfs_stat_t::mtime, brix_vfs_copy_opts_t::overwrite, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, s3_apply_put_user_metadata(), s3_copy_find_header(), s3_copy_vfs_ctx(), s3_etag(), s3_fail(), s3_resolve_key(), s3_send_xml_error(), s3_user_meta_copy(), brix_vfs_stat_t::size, brix_vfs_copy_opts_t::staged_commit, and stat().
Referenced by s3_dispatch_after_auth().