nginx-xrootd: src/auth/krb5/auth.c File Reference
auth.c File Reference
#include "core/ngx_brix_module.h"
#include "observability/metrics/unified.h"
#include "protocols/root/session/registry.h"
#include <string.h>
Functions
ngx_int_t brix_handle_krb5_auth (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_handle_krb5_auth()
ngx_int_t brix_handle_krb5_auth (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 165 of file auth.c.
References brix_ctx_token_t::auth, brix_ctx_login_t::auth_done, BRIX_AUTHN_KRB5, brix_identity_set_dn(), brix_log_access(), brix_metric_auth(), BRIX_OP_AUTH, BRIX_OP_ERR, BRIX_PROTO_ROOT, BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_sanitize_log_string(), brix_send_error(), brix_session_register(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_login_t::dn, brix_ctx_t::identity, brix_krb5_conf_t::ip_check, ngx_stream_brix_srv_conf_t::krb5, kXR_NoMemory, kXR_NotAuthorized, brix_ctx_t::login, brix_ctx_recv_t::payload, brix_ctx_t::recv, brix_ctx_login_t::sessid, brix_ctx_t::token, and brix_ctx_login_t::vo_list.
Referenced by brix_handle_auth_inner().