nginx-xrootd: src/core/aio/aio.h File Reference
aio.h File Reference
#include "core/ngx_brix_module.h"
#include "core/compat/pgio.h"
#include "fs/vfs/vfs_io_core.h"
Data Structures
struct brix_read_aio_t
struct brix_write_aio_t
struct brix_readv_aio_t
struct brix_writev_aio_t
struct brix_pgread_aio_t
struct brix_dirlist_aio_t
Macros
#define BRIX_GET_SCRATCH(ctx, c, slot_field, sz_field, need)
#define BRIX_DIRLIST_AIO_RESPONSE_MAX (4 * 1024 * 1024)
Typedefs
typedef brix_vfs_readv_seg_t brix_readv_seg_desc_t
typedef brix_vfs_writev_seg_t brix_writev_seg_desc_t
Functions
ngx_chain_t * brix_build_chunked_chain (brix_ctx_t *ctx, ngx_connection_t *c, u_char *databuf, size_t data_total)
ngx_chain_t * brix_build_window_chain (brix_ctx_t *ctx, ngx_connection_t *c, u_char *databuf, size_t data_total, uint16_t status)
ngx_chain_t * brix_build_sendfile_chain (brix_ctx_t *ctx, ngx_connection_t *c, int fd, const char *path, off_t offset, size_t data_total, u_char **base_out)
ngx_chain_t * brix_build_pgread_chain (brix_ctx_t *ctx, ngx_connection_t *c, int64_t offset, u_char *data, uint32_t out_size)
u_char * brix_get_pool_scratch (ngx_pool_t *pool, u_char **slot, size_t *slot_size, size_t need)
void brix_release_read_buffer (brix_ctx_t *ctx, ngx_connection_t *c, u_char *buf)
u_char * brix_acquire_read_buffer (brix_ctx_t *ctx, ngx_connection_t *c, size_t need)
void brix_trim_scratch (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_readv_read_segments (brix_readv_seg_desc_t *segments, size_t segment_count, size_t *bytes_read_total, char *error_message, size_t error_message_len)
ngx_flag_t brix_aio_restore_stream (brix_ctx_t *ctx, const u_char streamid[2])
ngx_flag_t brix_aio_restore_request (brix_ctx_t *ctx, const u_char streamid[2])
ngx_int_t brix_aio_post_task (brix_ctx_t *ctx, ngx_connection_t *c, ngx_thread_pool_t *pool, ngx_thread_task_t *task, const char *fallback_log, ngx_flag_t *posted)
void brix_aio_resume (ngx_connection_t *c)
void brix_read_window_pump (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *rconf)
void brix_read_aio_done (ngx_event_t *ev)
const char * brix_fd_kind (int fd)
void brix_read_io_failure_log (ngx_log_t *log, const char *who, int fd, off_t offset, size_t rlen, int io_errno)
void brix_write_aio_done (ngx_event_t *ev)
void brix_writev_write_aio_done (ngx_event_t *ev)
void brix_readv_aio_done (ngx_event_t *ev)
void brix_pgread_aio_done (ngx_event_t *ev)
void brix_dirlist_aio_done (ngx_event_t *ev)
void brix_read_aio_thread (void *data, ngx_log_t *log)
void brix_write_aio_thread (void *data, ngx_log_t *log)
void brix_writev_write_aio_thread (void *data, ngx_log_t *log)
void brix_readv_aio_thread (void *data, ngx_log_t *log)
void brix_pgread_aio_thread (void *data, ngx_log_t *log)
void brix_dirlist_aio_thread (void *data, ngx_log_t *log)
Macro Definition Documentation
BRIX_DIRLIST_AIO_RESPONSE_MAX
#define BRIX_DIRLIST_AIO_RESPONSE_MAX (4 * 1024 * 1024)
Definition at line 240 of file aio.h.
BRIX_GET_SCRATCH
#define BRIX_GET_SCRATCH (ctx, c, slot_field, sz_field, need)
Value:
    brix_get_pool_scratch((c)->pool, &(ctx)->slot_field,      \
                            &(ctx)->sz_field, (need))
Definition at line 76 of file aio.h.
Typedef Documentation
brix_readv_seg_desc_t
typedef brix_vfs_readv_seg_t brix_readv_seg_desc_t
Definition at line 113 of file aio.h.
brix_writev_seg_desc_t
typedef brix_vfs_writev_seg_t brix_writev_seg_desc_t
Definition at line 187 of file aio.h.
Function Documentation
brix_acquire_read_buffer()
u_char * brix_acquire_read_buffer (brix_ctx_t * ctx, ngx_connection_t * c, size_t need)
Definition at line 134 of file buffers_scratch.c.
References brix_read_slot_t::buf, c, brix_read_slot_t::in_use, brix_ctx_rd_t::inflight, brix_ctx_t::out, brix_ctx_out_t::pipeline_depth, brix_ctx_rd_t::pool, brix_ctx_t::rd, and brix_read_slot_t::size.
Referenced by read_serve_buffered().
brix_aio_post_task()
ngx_int_t brix_aio_post_task (brix_ctx_t * ctx, ngx_connection_t * c, ngx_thread_pool_t * pool, ngx_thread_task_t * task, const char * fallback_log, ngx_flag_t * posted)
Definition at line 74 of file resume.c.
References BRIX_SRV_METRIC_INC, c, ngx_brix_srv_metrics_t::io_uring_active, brix_ctx_t::metrics, op, brix_ctx_t::state, XRD_ST_AIO, and XRD_URING_OP_NONE.
Referenced by brix_pgread_post_aio(), brix_qcksum_handle_try_async(), brix_qcksum_try_async(), brix_query_ckscan(), brix_read_window_pump(), brix_readv_try_post_async(), brix_try_post_write_aio(), read_post_aio(), and writev_try_aio().
brix_aio_restore_request()
ngx_flag_t brix_aio_restore_request (brix_ctx_t * ctx, const u_char streamid[2])
Definition at line 48 of file resume.c.
References brix_aio_restore_stream(), brix_ctx_recv_t::hdr_pos, brix_ctx_t::recv, brix_ctx_t::state, and XRD_ST_REQ_HEADER.
Referenced by brix_cache_fill_composed_done(), brix_cache_fill_done(), brix_ckscan_aio_done(), brix_cksum_aio_done(), brix_dirlist_aio_done(), brix_pgread_aio_done(), brix_readv_aio_done(), brix_tpc_pull_done(), brix_write_aio_done_serial(), and brix_writev_write_aio_done().
brix_aio_restore_stream()
ngx_flag_t brix_aio_restore_stream (brix_ctx_t * ctx, const u_char streamid[2])
Definition at line 27 of file resume.c.
References brix_ctx_recv_t::cur_streamid, brix_ctx_t::destroyed, and brix_ctx_t::recv.
Referenced by brix_aio_restore_request(), brix_read_aio_done(), and brix_write_aio_done_pipelined().
brix_aio_resume()
void brix_aio_resume (ngx_connection_t * c)
Definition at line 141 of file resume.c.
References brix_aio_resume_fail(), brix_ensure_write_event(), brix_schedule_read_resume(), c, brix_ctx_t::destroyed, ngx_stream_brix_module, s, brix_ctx_t::state, and XRD_ST_SENDING.
Referenced by brix_cache_fill_composed_done(), brix_cache_fill_done(), brix_ckscan_aio_done(), brix_cksum_aio_done(), brix_dirlist_aio_done(), brix_pgread_aio_done(), brix_read_aio_done(), brix_read_window_pump(), brix_readv_aio_done(), brix_write_aio_done_serial(), brix_write_aio_serial_reply_ok(), brix_writev_write_aio_done(), tpc_done_reply_open(), tpc_done_reply_sync(), tpc_done_send_open_ok(), and tpc_done_sync_fail().
brix_build_chunked_chain()
ngx_chain_t * brix_build_chunked_chain (brix_ctx_t * ctx, ngx_connection_t * c, u_char * databuf, size_t data_total)
Definition at line 337 of file buffers.c.
References brix_build_resp_hdr(), brix_build_single_memory_chain(), brix_chain_append_mem(), brix_chunk_geometry(), BRIX_GET_SCRATCH, BRIX_READ_CHUNK_MAX, c, brix_ctx_recv_t::cur_streamid, kXR_ok, kXR_oksofar, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_read_aio_done(), brix_read_compressed(), brix_readv_aio_done(), brix_readv_execute_sync(), and read_finish_buffered().
brix_build_pgread_chain()
ngx_chain_t * brix_build_pgread_chain (brix_ctx_t * ctx, ngx_connection_t * c, int64_t offset, u_char * data, uint32_t out_size)
Definition at line 237 of file buffers_sendfile.c.
References brix_build_pgread_status(), and c.
Referenced by brix_pgread_aio_done(), and brix_pgread_send_response().
brix_build_sendfile_chain()
ngx_chain_t * brix_build_sendfile_chain (brix_ctx_t * ctx, ngx_connection_t * c, int fd, const char * path, off_t offset, size_t data_total, u_char ** base_out)
Definition at line 130 of file buffers_sendfile.c.
References brix_build_resp_hdr(), brix_build_single_sendfile_chain(), brix_chain_append_file(), brix_chain_append_mem(), brix_chunk_geometry(), BRIX_READ_CHUNK_MAX, BRIX_SLOT_HDR_MAX, c, brix_ctx_recv_t::cur_streamid, brix_resp_slot_t::hdr_bytes, kXR_ok, kXR_oksofar, brix_ctx_t::out, brix_ctx_t::recv, brix_ctx_out_t::resp_pipelinable, brix_ctx_out_t::ring, brix_ctx_out_t::tail, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_read_serve_sendfile().
brix_build_window_chain()
ngx_chain_t * brix_build_window_chain (brix_ctx_t * ctx, ngx_connection_t * c, u_char * databuf, size_t data_total, uint16_t status)
Definition at line 109 of file buffers.c.
References brix_build_resp_hdr(), BRIX_GET_SCRATCH, c, brix_ctx_recv_t::cur_streamid, brix_ctx_t::out, brix_resp_slot_t::read_fast_body_buf, brix_resp_slot_t::read_fast_body_chain, brix_resp_slot_t::read_fast_hdr_buf, brix_resp_slot_t::read_fast_hdr_chain, brix_ctx_t::recv, brix_ctx_out_t::ring, brix_ctx_out_t::tail, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_read_window_emit().
brix_dirlist_aio_done()
void brix_dirlist_aio_done (ngx_event_t * ev)
Definition at line 114 of file dirlist.c.
References brix_aio_restore_request(), brix_aio_resume(), brix_kxr_from_errno(), brix_log_access(), BRIX_OP_DIRLIST, BRIX_OP_ERR, BRIX_OP_OK, brix_queue_response_base(), brix_release_read_buffer(), brix_send_error(), c, brix_dirlist_aio_t::c, brix_dirlist_aio_t::ctx, brix_dirlist_aio_t::err_msg, brix_dirlist_aio_t::io_errno, brix_dirlist_aio_t::resolved, brix_dirlist_aio_t::response, brix_dirlist_aio_t::response_len, brix_ctx_t::state, brix_dirlist_aio_t::streamid, brix_dirlist_aio_t::want_cksum, brix_dirlist_aio_t::want_stat, and XRD_ST_SENDING.
brix_dirlist_aio_thread()
void brix_dirlist_aio_thread (void * data, ngx_log_t * log)
Definition at line 76 of file dirlist.c.
References brix_vfs_io_execute(), brix_vfs_job_opendir_init(), brix_dirlist_aio_t::cksum_algo, close(), brix_dirlist_aio_t::ctx, brix_dirlist_aio_t::dirfd, brix_dirlist_aio_t::err_msg, brix_dirlist_aio_t::io_errno, brix_vfs_job_t::io_errno, log, brix_vfs_job_t::out_size, brix_dirlist_aio_t::resolved, brix_dirlist_aio_t::response, brix_dirlist_aio_t::response_cap, brix_dirlist_aio_t::response_len, brix_dirlist_aio_t::streamid, brix_dirlist_aio_t::want_cksum, and brix_dirlist_aio_t::want_stat.
brix_fd_kind()
const char * brix_fd_kind (int fd)
Definition at line 19 of file fd_kind.c.
References fstat(), and stat().
Referenced by brix_read_io_failure_log().
brix_get_pool_scratch()
u_char * brix_get_pool_scratch (ngx_pool_t * pool, u_char ** slot, size_t * slot_size, size_t need)
Definition at line 31 of file buffers_scratch.c.
brix_pgread_aio_done()
void brix_pgread_aio_done (ngx_event_t * ev)
Definition at line 441 of file reads.c.
References brix_aio_restore_request(), brix_aio_resume(), brix_build_pgread_chain(), brix_build_pgread_status(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_PGREAD, brix_queue_response(), brix_queue_response_chain(), brix_release_read_buffer(), brix_send_error(), brix_ctx_totals_t::bytes, brix_file_t::bytes_read, c, brix_pgread_aio_t::c, brix_pgread_aio_t::ctx, brix_ctx_t::files, brix_pgread_aio_t::handle_idx, brix_pgread_aio_t::io_errno, kXR_IOError, ngx_stream_brix_module, brix_pgread_aio_t::nread, brix_pgread_aio_t::offset, brix_pgread_aio_t::out_size, brix_file_t::path, brix_pgread_aio_t::scratch, brix_ctx_t::state, brix_pgread_aio_t::streamid, brix_ctx_t::totals, and XRD_ST_SENDING.
Referenced by brix_pgread_post_aio().
brix_pgread_aio_thread()
void brix_pgread_aio_thread (void * data, ngx_log_t * log)
Definition at line 417 of file reads.c.
References brix_vfs_io_execute(), BRIX_VFS_IO_PGREAD, brix_vfs_job_read_init(), brix_vfs_job_set_obj(), brix_pgread_aio_t::fd, brix_pgread_aio_t::io_errno, brix_vfs_job_t::io_errno, brix_vfs_job_t::nio, brix_pgread_aio_t::nread, brix_pgread_aio_t::obj, brix_pgread_aio_t::offset, brix_vfs_job_t::op, brix_pgread_aio_t::out_size, brix_vfs_job_t::out_size, brix_pgread_aio_t::rlen, and brix_pgread_aio_t::scratch.
Referenced by brix_pgread_post_aio().
brix_read_aio_done()
void brix_read_aio_done (ngx_event_t * ev)
Definition at line 302 of file reads.c.
References brix_aio_restore_stream(), brix_aio_resume(), brix_build_chunked_chain(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_READ, brix_queue_response_chain(), brix_read_io_failure_log(), brix_read_window_emit(), brix_read_window_pump(), brix_release_read_buffer(), brix_send_error(), brix_ctx_totals_t::bytes, brix_file_t::bytes_read, c, brix_read_aio_t::c, brix_read_aio_t::conf, brix_read_aio_t::ctx, brix_read_aio_t::databuf, brix_read_aio_t::fd, brix_ctx_t::files, brix_read_aio_t::handle_idx, brix_ctx_recv_t::hdr_pos, brix_read_aio_t::io_errno, kXR_IOError, brix_read_aio_t::nread, brix_read_aio_t::offset, brix_ctx_t::out, brix_ctx_t::rd, brix_ctx_t::recv, brix_ctx_out_t::resp_pipelinable, brix_read_aio_t::rlen, brix_ctx_t::state, brix_read_aio_t::streamid, brix_ctx_t::totals, brix_ctx_rd_t::win_active, XRD_ST_REQ_HEADER, and XRD_ST_SENDING.
Referenced by brix_read_window_pump(), and read_post_aio().
brix_read_aio_thread()
void brix_read_aio_thread (void * data, ngx_log_t * log)
Definition at line 268 of file reads.c.
References brix_vfs_io_execute(), brix_vfs_job_read_init(), brix_vfs_job_set_obj(), brix_read_aio_t::csi, brix_vfs_job_t::csi, brix_read_aio_t::databuf, brix_read_aio_t::fd, brix_read_aio_t::io_errno, brix_vfs_job_t::io_errno, brix_vfs_job_t::nio, brix_read_aio_t::nread, brix_read_aio_t::obj, brix_read_aio_t::offset, and brix_read_aio_t::rlen.
Referenced by brix_read_window_pump(), and read_post_aio().
brix_read_io_failure_log()
void brix_read_io_failure_log (ngx_log_t * log, const char * who, int fd, off_t offset, size_t rlen, int io_errno)
Definition at line 39 of file reads.c.
References brix_fd_kind(), and log.
Referenced by brix_read_aio_done(), brix_read_window_emit(), and read_finish_buffered().
brix_read_window_pump()
void brix_read_window_pump (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * rconf)
Definition at line 126 of file reads.c.
References brix_aio_post_task(), brix_aio_resume(), brix_budget_sync(), BRIX_GET_SCRATCH, brix_read_aio_done(), brix_read_aio_thread(), BRIX_READ_WINDOW, brix_read_window_emit(), brix_send_error(), brix_vfs_io_execute(), brix_vfs_job_read_init(), brix_vfs_job_set_obj(), c, brix_read_aio_t::c, brix_read_aio_t::conf, brix_read_aio_t::csi, brix_file_t::csi, brix_vfs_job_t::csi, brix_read_aio_t::ctx, brix_read_aio_t::databuf, brix_read_aio_t::fd, brix_ctx_t::files, brix_read_aio_t::handle_idx, brix_read_aio_t::io_errno, brix_vfs_job_t::io_errno, kXR_NoMemory, brix_vfs_job_t::nio, brix_read_aio_t::nread, brix_read_aio_t::obj, brix_read_aio_t::offset, brix_ctx_t::rd, brix_ctx_rd_t::read_aio_task, brix_read_aio_t::rlen, brix_file_t::sd_obj, brix_ctx_t::state, brix_read_aio_t::streamid, brix_ctx_rd_t::win_active, brix_ctx_rd_t::win_fd, brix_ctx_rd_t::win_idx, brix_ctx_rd_t::win_offset, brix_ctx_rd_t::win_remaining, brix_ctx_rd_t::win_streamid, XRD_ST_REQ_HEADER, and XRD_ST_SENDING.
Referenced by brix_read_aio_done(), ngx_stream_brix_send(), and read_serve_windowed().
brix_readv_aio_done()
void brix_readv_aio_done (ngx_event_t * ev)
Definition at line 91 of file readv.c.
References brix_aio_restore_request(), brix_aio_resume(), brix_build_chunked_chain(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_READV, brix_queue_response_chain(), brix_release_read_buffer(), brix_send_error(), brix_ctx_totals_t::bytes, brix_file_t::bytes_read, brix_readv_aio_t::bytes_read_total, c, brix_readv_aio_t::c, brix_readv_aio_t::ctx, brix_readv_aio_t::err_msg, brix_ctx_t::files, brix_vfs_readv_seg_t::handle_index, brix_readv_aio_t::io_error, kXR_IOError, brix_vfs_readv_seg_t::read_length, brix_readv_aio_t::response_buffer, brix_readv_aio_t::response_bytes, brix_readv_aio_t::segment_count, brix_readv_aio_t::segments, brix_ctx_t::state, brix_readv_aio_t::streamid, brix_ctx_t::totals, and XRD_ST_SENDING.
Referenced by brix_readv_try_post_async().
brix_readv_aio_thread()
void brix_readv_aio_thread (void * data, ngx_log_t * log)
Definition at line 34 of file readv.c.
References brix_vfs_io_execute(), BRIX_VFS_IO_READV, brix_readv_aio_t::bytes_read_total, brix_readv_aio_t::err_msg, brix_vfs_job_t::err_msg, brix_vfs_job_t::err_msg_cap, brix_vfs_job_t::io_errno, brix_readv_aio_t::io_error, brix_vfs_job_t::nio, brix_vfs_job_t::nsegs, brix_vfs_job_t::op, brix_vfs_job_t::out_size, brix_readv_aio_t::response_bytes, brix_readv_aio_t::segment_count, brix_readv_aio_t::segments, and brix_vfs_job_t::segs.
Referenced by brix_readv_try_post_async().
brix_readv_read_segments()
ngx_int_t brix_readv_read_segments (brix_readv_seg_desc_t * segments, size_t segment_count, size_t * bytes_read_total, char * error_message, size_t error_message_len)
Definition at line 182 of file readv.c.
References brix_readv_build_ranges(), BRIX_READV_MAXSEGS, brix_readv_read_one_run(), brix_size_mul(), brix_readv_run_ctx_t::error_message, brix_readv_run_ctx_t::error_message_len, ngx_memcpy, brix_readv_run_ctx_t::ranges, brix_readv_run_ctx_t::segment_count, and brix_readv_run_ctx_t::segments.
Referenced by brix_vfs_io_execute_readv().
brix_release_read_buffer()
void brix_release_read_buffer (brix_ctx_t * ctx, ngx_connection_t * c, u_char * buf)
Definition at line 83 of file buffers_scratch.c.
References brix_read_slot_t::buf, c, brix_ctx_rd_t::cmp_scratch, brix_read_slot_t::in_use, brix_ctx_rd_t::inflight, brix_ctx_t::out, brix_ctx_out_t::pipeline_depth, brix_ctx_rd_t::pool, brix_ctx_t::rd, brix_ctx_rd_t::read_hdr_scratch, brix_ctx_rd_t::read_scratch, and brix_ctx_rd_t::write_scratch.
Referenced by brix_dirlist_aio_done(), brix_handle_readv(), brix_pgread_aio_done(), brix_pgread_send_response(), brix_read_aio_done(), brix_read_compressed(), brix_read_serve_sendfile(), brix_read_window_emit(), brix_readv_aio_done(), brix_readv_execute_sync(), brix_readv_try_post_async(), brix_release_pending_buffer(), read_finish_buffered(), and read_post_aio().
brix_trim_scratch()
void brix_trim_scratch (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 212 of file buffers_scratch.c.
References brix_trim_one(), c, brix_ctx_t::rd, brix_ctx_rd_t::read_scratch, brix_ctx_rd_t::read_scratch_size, brix_ctx_rd_t::write_scratch, and brix_ctx_rd_t::write_scratch_size.
Referenced by brix_recv_header_prep().
brix_write_aio_done()
void brix_write_aio_done (ngx_event_t * ev)
Definition at line 273 of file write.c.
References BRIX_OP_WRITE, brix_run_deferred_teardown(), brix_write_aio_done_pipelined(), brix_write_aio_done_serial(), c, brix_write_aio_t::c, brix_write_aio_t::ctx, brix_ctx_t::destroyed, brix_ctx_out_t::finalize_pending, brix_write_aio_t::is_pgwrite, ngx_stream_brix_module, op, brix_ctx_t::out, brix_write_aio_t::payload_to_free, and brix_ctx_out_t::wr_inflight.
Referenced by brix_try_post_write_aio().
brix_write_aio_thread()
void brix_write_aio_thread (void * data, ngx_log_t * log)
Definition at line 14 of file write.c.
References brix_vfs_io_execute(), brix_vfs_job_set_obj(), brix_vfs_job_write_init(), brix_write_aio_t::csi, brix_vfs_job_t::csi, brix_write_aio_t::data, brix_write_aio_t::fd, brix_write_aio_t::io_errno, brix_vfs_job_t::io_errno, brix_write_aio_t::len, brix_vfs_job_t::nio, brix_write_aio_t::nwritten, brix_write_aio_t::obj, and brix_write_aio_t::offset.
Referenced by brix_try_post_write_aio().
brix_writev_write_aio_done()
void brix_writev_write_aio_done (ngx_event_t * ev)
Definition at line 375 of file write.c.
References brix_aio_restore_request(), brix_aio_resume(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_WRITEV, brix_send_error(), brix_send_ok(), brix_wrts_record(), brix_wt_mark_dirty(), brix_writev_aio_t::bytes_total, brix_ctx_totals_t::bytes_written, brix_file_t::bytes_written, c, brix_writev_aio_t::c, brix_writev_aio_t::ctx, brix_writev_aio_t::err_msg, brix_ctx_t::files, brix_vfs_writev_seg_t::handle_idx, brix_writev_aio_t::io_error, kXR_IOError, brix_writev_aio_t::n_segs, ngx_stream_brix_module, brix_vfs_writev_seg_t::offset, brix_writev_aio_t::payload_buf, brix_writev_aio_t::segs, brix_writev_aio_t::streamid, brix_ctx_t::totals, brix_vfs_writev_seg_t::wlen, brix_file_t::wrts_enabled, and brix_file_t::wt_enabled.
Referenced by writev_try_aio().
brix_writev_write_aio_thread()
void brix_writev_write_aio_thread (void * data, ngx_log_t * log)
Definition at line 335 of file write.c.
References brix_vfs_io_execute(), BRIX_VFS_IO_WRITEV, brix_writev_aio_t::bytes_total, brix_writev_aio_t::do_sync, brix_vfs_job_t::do_sync, brix_writev_aio_t::err_msg, brix_vfs_job_t::err_msg, brix_vfs_job_t::err_msg_cap, brix_vfs_job_t::io_errno, brix_writev_aio_t::io_error, brix_writev_aio_t::n_segs, brix_vfs_job_t::nsegs, brix_vfs_job_t::op, brix_vfs_job_t::out_size, brix_writev_aio_t::segs, brix_vfs_job_t::segs, and brix_vfs_job_t::short_io.
Referenced by writev_try_aio().