nginx-xrootd: src/protocols/webdav/path.c File Reference
path.c File Reference
#include "webdav.h"
#include "core/compat/path.h"
#include <limits.h>
#include <string.h>
#include <unistd.h>
Functions
static ngx_int_t map_resolve_rc (int rc)
ngx_int_t webdav_resolve_destination_path (ngx_log_t *log, const char *op_label, const char *root_canon, const char *decoded_path, char *out, size_t outsz, ngx_flag_t allow_internal)
ngx_int_t ngx_http_brix_webdav_resolve_path (ngx_http_request_t *r, const char *root_canon, char *out, size_t outsz)
Function Documentation
map_resolve_rc()
static ngx_int_t map_resolve_rc (int rc) static
Definition at line 16 of file path.c.
Referenced by webdav_resolve_destination_path().
ngx_http_brix_webdav_resolve_path()
ngx_int_t ngx_http_brix_webdav_resolve_path (ngx_http_request_t * r, const char * root_canon, char * out, size_t outsz)
Definition at line 59 of file path.c.
References brix_http_resolve_path_ex(), ngx_http_brix_shared_conf_t::cache_store_endpoint, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_module, WEBDAV_MAX_PATH, and webdav_urldecode().
Referenced by access_apply_authdb(), rl_resolve_volume_path(), webdav_copy_resolve_pair(), webdav_handle_get(), webdav_handle_lock_inner(), webdav_handle_mkcol(), webdav_handle_move(), webdav_handle_unlock(), webdav_lock_check_request_path(), webdav_put_precheck(), webdav_resolve_stat(), and webdav_tpc_prepare_pull_target().
webdav_resolve_destination_path()
ngx_int_t webdav_resolve_destination_path (ngx_log_t * log, const char * op_label, const char * root_canon, const char * decoded_path, char * out, size_t outsz, ngx_flag_t allow_internal)
Definition at line 28 of file path.c.
References brix_http_resolve_path_ex(), log, map_resolve_rc(), and PATH_MAX.
Referenced by tape_authz_path(), webdav_copy_resolve_pair(), and webdav_move_resolve_dest().