nginx-xrootd: src/observability/dashboard/auth.c File Reference
auth.c File Reference
#include "dashboard_http.h"
#include "core/ident.h"
#include <openssl/hmac.h>
#include <openssl/evp.h>
#include <openssl/crypto.h>
#include <time.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <crypt.h>
#include <ctype.h>
#include "core/compat/alloc_guard.h"
Data Structures
struct ngx_http_dashboard_login_ctx_t
Macros
#define HMAC_HEX_LEN 64 /* SHA-256 = 32 bytes = 64 hex chars */
#define TIMESTAMP_MAX 20 /* enough for a Unix timestamp string */
Functions
static void hmac_sha256_hex (const u_char *key, size_t key_len, const char *msg, size_t msg_len, char out_hex[64+1])
static ngx_int_t find_cookie (ngx_http_request_t *r, const char *name, size_t name_len, u_char **val, size_t *val_len)
static ngx_uint_t dashboard_users_enabled (const ngx_http_brix_dashboard_loc_conf_t *conf)
static ngx_http_brix_dashboard_user_t * dashboard_find_user (const ngx_http_brix_dashboard_loc_conf_t *conf, const char *username, size_t username_len)
static ngx_int_t dashboard_copy_str0 (ngx_pool_t *pool, ngx_str_t *src, char **out)
static ngx_int_t dashboard_verify_user_password (ngx_pool_t *pool, ngx_http_brix_dashboard_user_t *user, const char *password, size_t password_len)
static ngx_int_t dashboard_form_value (const u_char *body, size_t body_len, const char *name, char *out, size_t outsz, size_t *out_len)
static ngx_int_t dashboard_cookie_hmac (const ngx_str_t *key, const char *ts, size_t ts_len, const char *username, size_t username_len, char out_hex[64+1])
ngx_int_t ngx_http_brix_dashboard_check_auth (ngx_http_request_t *r, const ngx_http_brix_dashboard_loc_conf_t *conf, ngx_uint_t suppress_missing_cookie)
static ngx_int_t send_html (ngx_http_request_t *r, ngx_int_t status, const char *html, size_t html_len)
static void login_post_body_handler (ngx_http_request_t *r)
ngx_int_t ngx_http_brix_dashboard_login_handler (ngx_http_request_t *r)
Variables
static const char login_form_html []
static const char login_form_html_error []
Macro Definition Documentation
HMAC_HEX_LEN
#define HMAC_HEX_LEN 64 /* SHA-256 = 32 bytes = 64 hex chars */
Definition at line 33 of file auth.c.
TIMESTAMP_MAX
#define TIMESTAMP_MAX 20 /* enough for a Unix timestamp string */
Definition at line 34 of file auth.c.
Function Documentation
dashboard_cookie_hmac()
static ngx_int_t dashboard_cookie_hmac (const ngx_str_t * key, const char * ts, size_t ts_len, const char * username, size_t username_len, char out_hex[64+1]) static
Definition at line 336 of file auth.c.
References hmac_sha256_hex(), key, ngx_memcpy, and TIMESTAMP_MAX.
Referenced by login_post_body_handler(), and ngx_http_brix_dashboard_check_auth().
dashboard_copy_str0()
static ngx_int_t dashboard_copy_str0 (ngx_pool_t * pool, ngx_str_t * src, char ** out) static
Definition at line 163 of file auth.c.
References BRIX_PNALLOC_OR_RETURN, and ngx_memcpy.
Referenced by dashboard_verify_user_password().
dashboard_find_user()
static ngx_http_brix_dashboard_user_t * dashboard_find_user (const ngx_http_brix_dashboard_loc_conf_t * conf, const char * username, size_t username_len) static
Definition at line 138 of file auth.c.
References dashboard_users_enabled(), and ngx_http_brix_dashboard_loc_conf_t::users.
Referenced by login_post_body_handler(), and ngx_http_brix_dashboard_check_auth().
dashboard_form_value()
static ngx_int_t dashboard_form_value (const u_char * body, size_t body_len, const char * name, char * out, size_t outsz, size_t * out_len) static
Definition at line 241 of file auth.c.
References name.
Referenced by login_post_body_handler().
dashboard_users_enabled()
static ngx_uint_t dashboard_users_enabled (const ngx_http_brix_dashboard_loc_conf_t * conf) static
Definition at line 130 of file auth.c.
References ngx_http_brix_dashboard_loc_conf_t::users.
Referenced by dashboard_find_user(), login_post_body_handler(), and ngx_http_brix_dashboard_check_auth().
dashboard_verify_user_password()
static ngx_int_t dashboard_verify_user_password (ngx_pool_t * pool, ngx_http_brix_dashboard_user_t * user, const char * password, size_t password_len) static
Definition at line 185 of file auth.c.
References BRIX_PNALLOC_OR_RETURN, dashboard_copy_str0(), ngx_memcpy, and ngx_http_brix_dashboard_user_t::password_hash.
Referenced by login_post_body_handler().
find_cookie()
static ngx_int_t find_cookie (ngx_http_request_t * r, const char * name, size_t name_len, u_char ** val, size_t * val_len) static
Definition at line 67 of file auth.c.
References name.
Referenced by ngx_http_brix_dashboard_check_auth().
hmac_sha256_hex()
static void hmac_sha256_hex (const u_char * key, size_t key_len, const char * msg, size_t msg_len, char out_hex[64+1]) static
Definition at line 43 of file auth.c.
References HMAC_HEX_LEN, and key.
Referenced by dashboard_cookie_hmac().
login_post_body_handler()
static void login_post_body_handler (ngx_http_request_t * r) static
Definition at line 643 of file auth.c.
References BRIX_DASH_EVENT_AUTH, brix_dashboard_event_add(), ngx_http_brix_dashboard_loc_conf_t::cookie_path, dashboard_cookie_hmac(), dashboard_find_user(), dashboard_form_value(), dashboard_users_enabled(), dashboard_verify_user_password(), HMAC_HEX_LEN, login_form_html_error, ngx_http_brix_dashboard_module, ngx_memcpy, ngx_pnalloc(), ngx_http_brix_dashboard_loc_conf_t::password, ngx_http_brix_dashboard_user_t::password_hash, send_html(), and TIMESTAMP_MAX.
Referenced by ngx_http_brix_dashboard_login_handler().
ngx_http_brix_dashboard_check_auth()
ngx_int_t ngx_http_brix_dashboard_check_auth (ngx_http_request_t * r, const ngx_http_brix_dashboard_loc_conf_t * conf, ngx_uint_t suppress_missing_cookie)
Definition at line 364 of file auth.c.
References BRIX_DASH_EVENT_AUTH, brix_dashboard_event_add(), dashboard_cookie_hmac(), dashboard_find_user(), dashboard_users_enabled(), find_cookie(), HMAC_HEX_LEN, key, ngx_memcpy, ngx_http_brix_dashboard_loc_conf_t::password, ngx_http_brix_dashboard_user_t::password_hash, ngx_http_brix_dashboard_loc_conf_t::session_ttl, and TIMESTAMP_MAX.
Referenced by ngx_http_brix_dashboard_api_handler(), ngx_http_brix_dashboard_config_download_handler(), ngx_http_brix_dashboard_download_handler(), ngx_http_brix_dashboard_files_handler(), ngx_http_brix_dashboard_page_handler(), ngx_http_brix_dashboard_scan_handler(), and vfs_browse_preamble().
ngx_http_brix_dashboard_login_handler()
ngx_int_t ngx_http_brix_dashboard_login_handler (ngx_http_request_t * r)
Definition at line 827 of file auth.c.
References login_form_html, login_post_body_handler(), and send_html().
Referenced by ngx_http_brix_dashboard_main_handler().
send_html()
static ngx_int_t send_html (ngx_http_request_t * r, ngx_int_t status, const char * html, size_t html_len) static
Definition at line 597 of file auth.c.
References ngx_pcalloc().
Referenced by login_post_body_handler(), and ngx_http_brix_dashboard_login_handler().
Variable Documentation
login_form_html
const char login_form_html[] static
Initial value:
=
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head><meta charset=\"utf-8\">"
    "<title>"  "BriX-Cache"  " Monitor — Login</title>\n"
    "<style>\n"
    "body{background:#1a1a2e;color:#e0e0e0;font-family:monospace;"
    "display:flex;justify-content:center;align-items:center;height:100vh;margin:0}\n"
    ".box{background:#16213e;padding:2em 3em;border-radius:8px;"
    "border:1px solid #0f3460;min-width:320px}\n"
    "h2{color:#e94560;margin-bottom:1.5em;text-align:center}\n"
    "input[type=text],input[type=password]{width:100%;padding:.5em;background:#0f3460;"
    "border:1px solid #e94560;color:#e0e0e0;border-radius:4px;font-size:1em;box-sizing:border-box}\n"
    "input+input{margin-top:.75em}\n"
    "button{width:100%;padding:.6em;margin-top:1em;background:#e94560;"
    "border:none;color:#fff;font-size:1em;border-radius:4px;cursor:pointer}\n"
    "button:hover{background:#c73652}\n"
    ".err{color:#e94560;font-size:.85em;margin-top:.5em}\n"
    "</style></head>\n"
    "<body><div class=\"box\">\n"
    "<h2>Transfer Monitor</h2>\n"
    "<form method=\"post\">\n"
    "<input type=\"text\" name=\"username\" placeholder=\"Username\">\n"
    "<input type=\"password\" name=\"password\" placeholder=\"Admin password\" autofocus>\n"
    "<button type=\"submit\">Sign in</button>\n"
    "</form>\n"
    "</div></body></html>\n"
Definition at line 535 of file auth.c.
Referenced by ngx_http_brix_dashboard_login_handler().
login_form_html_error
const char login_form_html_error[] static
Initial value:
=
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head><meta charset=\"utf-8\">"
    "<title>"  "BriX-Cache"  " Monitor — Login</title>\n"
    "<style>\n"
    "body{background:#1a1a2e;color:#e0e0e0;font-family:monospace;"
    "display:flex;justify-content:center;align-items:center;height:100vh;margin:0}\n"
    ".box{background:#16213e;padding:2em 3em;border-radius:8px;"
    "border:1px solid #0f3460;min-width:320px}\n"
    "h2{color:#e94560;margin-bottom:1.5em;text-align:center}\n"
    "input[type=text],input[type=password]{width:100%;padding:.5em;background:#0f3460;"
    "border:1px solid #e94560;color:#e0e0e0;border-radius:4px;font-size:1em;box-sizing:border-box}\n"
    "input+input{margin-top:.75em}\n"
    "button{width:100%;padding:.6em;margin-top:1em;background:#e94560;"
    "border:none;color:#fff;font-size:1em;border-radius:4px;cursor:pointer}\n"
    "button:hover{background:#c73652}\n"
    ".err{color:#e94560;font-size:.85em;margin-top:.5em}\n"
    "</style></head>\n"
    "<body><div class=\"box\">\n"
    "<h2>Transfer Monitor</h2>\n"
    "<form method=\"post\">\n"
    "<input type=\"text\" name=\"username\" placeholder=\"Username\">\n"
    "<input type=\"password\" name=\"password\" placeholder=\"Admin password\" autofocus>\n"
    "<button type=\"submit\">Sign in</button>\n"
    "</form>\n"
    "<p class=\"err\">Incorrect password.</p>\n"
    "</div></body></html>\n"
Definition at line 563 of file auth.c.
Referenced by login_post_body_handler().