nginx-xrootd: src/fs/vfs/vfs.h File Reference
vfs.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include "fs/path/unified.h"
#include "core/types/identity.h"
#include "observability/metrics/unified.h"
#include "fs/backend/sd.h"
Data Structures
struct brix_vfs_copy_opts_t
struct brix_vfs_stat_t
struct brix_vfs_io_result_t
struct brix_vfs_ctx_t
struct brix_vfs_walk_opts_t
Macros
#define BRIX_VFS_O_READ 0x01
#define BRIX_VFS_O_WRITE 0x02
#define BRIX_VFS_O_CREATE 0x04
#define BRIX_VFS_O_EXCL 0x08
#define BRIX_VFS_O_TRUNC 0x10
#define BRIX_VFS_O_APPEND 0x20
#define BRIX_VFS_O_MKDIRPATH 0x40
#define BRIX_VFS_O_NOCACHE 0x80
Typedefs
typedef ngx_int_t(* brix_vfs_walk_file_cb) (void *cookie, const char *logical, const brix_vfs_stat_t *st, int fd)
typedef ngx_int_t(* brix_vfs_copy_meta_cb) (void *cookie, const char *src, const char *dst, int is_dir)
Enumerations
enum brix_vfs_dirent_kind_t { BRIX_VFS_DT_UNKNOWN = 0 , BRIX_VFS_DT_DIR , BRIX_VFS_DT_REG , BRIX_VFS_DT_OTHER }
enum brix_vfs_walk_target_t { BRIX_VFS_WALK_NONE = 0 , BRIX_VFS_WALK_FILE , BRIX_VFS_WALK_DIR , BRIX_VFS_WALK_OTHER }
Functions
void brix_vfs_ctx_init (brix_vfs_ctx_t *vctx, ngx_pool_t *pool, ngx_log_t *log, brix_proto_t proto, const char *root_canon, const char *cache_root_canon, int allow_write, int is_tls, brix_identity_t *identity, const char *resolved_path)
const char * brix_vfs_export_relative (const brix_vfs_ctx_t *ctx, const char *path)
brix_vfs_file_t * brix_vfs_open (brix_vfs_ctx_t *ctx, ngx_uint_t flags, int *err_out)
ngx_int_t brix_vfs_close (brix_vfs_file_t *fh, ngx_log_t *log)
ngx_fd_t brix_vfs_file_fd (const brix_vfs_file_t *fh)
ngx_int_t brix_vfs_adopt_obj (brix_vfs_ctx_t *ctx, const char *path, brix_sd_obj_t *o, unsigned writable, brix_vfs_file_t **out)
ngx_int_t brix_vfs_adopt_fd (brix_vfs_ctx_t *ctx, const char *path, ngx_fd_t fd, unsigned from_cache, unsigned writable, brix_vfs_file_t **out)
void brix_vfs_file_sd_obj (const brix_vfs_file_t *fh, brix_sd_obj_t *out)
ngx_fd_t brix_vfs_file_sendfile_fd (const brix_vfs_file_t *fh)
ngx_uint_t brix_vfs_file_can_sendfile (const brix_vfs_file_t *fh)
const char * brix_vfs_file_backend_name (const brix_vfs_file_t *fh)
ssize_t brix_vfs_file_pread (brix_vfs_file_t *fh, void *buf, size_t len, off_t off)
const char * brix_vfs_file_path (const brix_vfs_file_t *fh)
off_t brix_vfs_file_size (const brix_vfs_file_t *fh)
time_t brix_vfs_file_mtime (const brix_vfs_file_t *fh)
ngx_uint_t brix_vfs_file_from_cache (const brix_vfs_file_t *fh)
ngx_int_t brix_vfs_file_stat (const brix_vfs_file_t *fh, brix_vfs_stat_t *stat_out)
ngx_int_t brix_vfs_stat (brix_vfs_ctx_t *ctx, brix_vfs_stat_t *stat_out)
ngx_int_t brix_vfs_statf (brix_vfs_ctx_t *ctx, brix_vfs_stat_t *stat_out)
ngx_int_t brix_vfs_residency (brix_vfs_ctx_t *ctx, brix_sd_residency_t *out, int *nearline_export)
ngx_int_t brix_vfs_probe (brix_vfs_ctx_t *ctx, int nofollow, brix_vfs_stat_t *stat_out)
brix_vfs_dir_t * brix_vfs_opendir (brix_vfs_ctx_t *ctx, int *err_out)
brix_vfs_dir_t * brix_vfs_opendir_quiet (brix_vfs_ctx_t *ctx, int *err_out)
ngx_int_t brix_vfs_readdir (brix_vfs_dir_t *dh, ngx_str_t *name_out, brix_vfs_stat_t *stat_out)
ngx_int_t brix_vfs_readdir_kind (brix_vfs_dir_t *dh, ngx_str_t *name_out, brix_vfs_dirent_kind_t *kind_out)
ngx_int_t brix_vfs_closedir (brix_vfs_dir_t *dh, ngx_log_t *log)
ngx_fd_t brix_vfs_dir_fd (const brix_vfs_dir_t *dh)
ngx_int_t brix_vfs_unlink (brix_vfs_ctx_t *ctx)
ngx_int_t brix_vfs_rmdir (brix_vfs_ctx_t *ctx, unsigned recursive)
ngx_int_t brix_vfs_rename (brix_vfs_ctx_t *ctx, const brix_path_result_t *dst)
ngx_int_t brix_vfs_rename_path (brix_sd_instance_t *sd, ngx_log_t *log, const char *root_canon, const char *src, const char *dst, unsigned overwrite, int *was_dir_out)
ngx_int_t brix_vfs_enumerate_catalog (brix_sd_instance_t *sd, int want_stat, brix_sd_catalog_cb cb, void *ctx)
ngx_int_t brix_vfs_chmod (brix_vfs_ctx_t *ctx, mode_t mode)
ngx_int_t brix_vfs_setattr (brix_vfs_ctx_t *ctx, const brix_sd_setattr_t *attr)
ngx_int_t brix_vfs_mkdir (brix_vfs_ctx_t *ctx, mode_t mode, unsigned parents)
ngx_int_t brix_vfs_truncate (brix_vfs_file_t *fh, off_t length)
ngx_int_t brix_vfs_sync (brix_vfs_file_t *fh)
ngx_int_t brix_vfs_walk (ngx_log_t *log, int rootfd, const char *logical, const brix_vfs_walk_opts_t *opts, brix_vfs_walk_file_cb cb, void *cookie, brix_vfs_walk_target_t *target_out, char *errmsg, size_t errsz)
ngx_int_t brix_vfs_copyfile (ngx_log_t *log, const char *root_canon, const char *src, const char *dst, int preserve_xattrs, brix_vfs_copy_meta_cb meta_cb, void *cookie)
ngx_int_t brix_vfs_copytree (ngx_log_t *log, const char *root_canon, const char *src, const char *dst, int preserve_xattrs, brix_vfs_copy_meta_cb meta_cb, void *cookie)
int brix_vfs_open_fd (ngx_log_t *log, const char *root_canon, const char *logical, int flags, mode_t mode)
int brix_vfs_open_fd_at (int rootfd, const char *logical, int flags, mode_t mode)
int brix_vfs_unlink_at (int rootfd, const char *logical, int is_dir)
int brix_vfs_unlink_path (ngx_log_t *log, const char *root_canon, const char *logical)
int brix_vfs_backend_mkpath (const char *root_canon, const char *logical, mode_t mode, ngx_log_t *log)
int brix_vfs_mkdir_path (ngx_log_t *log, const char *root_canon, const char *logical, mode_t mode)
ngx_int_t brix_vfs_pread_full (ngx_fd_t fd, u_char *buf, size_t len, off_t offset, size_t *nread)
ngx_int_t brix_vfs_pwrite_full (ngx_fd_t fd, const u_char *buf, size_t len, off_t offset)
ssize_t brix_vfs_getxattr (brix_vfs_ctx_t *ctx, const char *name, void *buf, size_t bufsz)
ssize_t brix_vfs_listxattr (brix_vfs_ctx_t *ctx, void *buf, size_t bufsz)
ngx_int_t brix_vfs_setxattr (brix_vfs_ctx_t *ctx, const char *name, const void *value, size_t len, int flags)
ngx_int_t brix_vfs_removexattr (brix_vfs_ctx_t *ctx, const char *name)
ssize_t brix_vfs_fgetxattr (const brix_vfs_ctx_t *ctx, int fd, const char *name, void *buf, size_t bufsz)
ssize_t brix_vfs_flistxattr (const brix_vfs_ctx_t *ctx, int fd, void *buf, size_t bufsz)
ngx_int_t brix_vfs_fsetxattr (const brix_vfs_ctx_t *ctx, int fd, const char *name, const void *value, size_t len, int flags)
ngx_int_t brix_vfs_fremovexattr (const brix_vfs_ctx_t *ctx, int fd, const char *name)
ngx_int_t brix_vfs_copy (brix_vfs_ctx_t *ctx, const char *dst_resolved, const brix_vfs_copy_opts_t *opts)
brix_vfs_staged_t * brix_vfs_staged_open (brix_vfs_ctx_t *ctx, mode_t mode, ngx_uint_t attempts, int *err_out)
ngx_fd_t brix_vfs_staged_fd (const brix_vfs_staged_t *st)
ngx_uint_t brix_vfs_staged_is_driver (const brix_vfs_staged_t *st)
ngx_int_t brix_vfs_staged_write (brix_vfs_staged_t *st, const void *buf, size_t len, off_t off)
const char * brix_vfs_staged_tmp_path (const brix_vfs_staged_t *st)
ngx_int_t brix_vfs_staged_commit (brix_vfs_staged_t *st, unsigned excl)
void brix_vfs_staged_abort (brix_vfs_staged_t *st, unsigned remove_tmp)
Macro Definition Documentation
BRIX_VFS_O_APPEND
#define BRIX_VFS_O_APPEND 0x20
Definition at line 43 of file vfs.h.
BRIX_VFS_O_CREATE
#define BRIX_VFS_O_CREATE 0x04
Definition at line 40 of file vfs.h.
BRIX_VFS_O_EXCL
#define BRIX_VFS_O_EXCL 0x08
Definition at line 41 of file vfs.h.
BRIX_VFS_O_MKDIRPATH
#define BRIX_VFS_O_MKDIRPATH 0x40
Definition at line 44 of file vfs.h.
BRIX_VFS_O_NOCACHE
#define BRIX_VFS_O_NOCACHE 0x80
Definition at line 45 of file vfs.h.
BRIX_VFS_O_READ
#define BRIX_VFS_O_READ 0x01
Definition at line 38 of file vfs.h.
BRIX_VFS_O_TRUNC
#define BRIX_VFS_O_TRUNC 0x10
Definition at line 42 of file vfs.h.
BRIX_VFS_O_WRITE
#define BRIX_VFS_O_WRITE 0x02
Definition at line 39 of file vfs.h.
Typedef Documentation
brix_vfs_copy_meta_cb
typedef ngx_int_t(* brix_vfs_copy_meta_cb) (void *cookie, const char *src, const char *dst, int is_dir)
Definition at line 372 of file vfs.h.
brix_vfs_walk_file_cb
typedef ngx_int_t(* brix_vfs_walk_file_cb) (void *cookie, const char *logical, const brix_vfs_stat_t *st, int fd)
Definition at line 353 of file vfs.h.
Enumeration Type Documentation
brix_vfs_dirent_kind_t
enum brix_vfs_dirent_kind_t
Enumerator
BRIX_VFS_DT_UNKNOWN
BRIX_VFS_DT_DIR
BRIX_VFS_DT_REG
BRIX_VFS_DT_OTHER
Definition at line 246 of file vfs.h.
brix_vfs_walk_target_t
enum brix_vfs_walk_target_t
Enumerator
BRIX_VFS_WALK_NONE
BRIX_VFS_WALK_FILE
BRIX_VFS_WALK_DIR
BRIX_VFS_WALK_OTHER
Definition at line 342 of file vfs.h.
Function Documentation
brix_vfs_adopt_fd()
ngx_int_t brix_vfs_adopt_fd (brix_vfs_ctx_t * ctx, const char * path, ngx_fd_t fd, unsigned from_cache, unsigned writable, brix_vfs_file_t ** out)
Definition at line 125 of file vfs_open.c.
References brix_vfs_copy_path(), brix_vfs_ctx_sd_obj(), brix_sd_stat_t::ctime, brix_sd_stat_t::ino, brix_vfs_ctx_t::is_tls, brix_vfs_ctx_t::log, brix_sd_stat_t::mode, brix_sd_stat_t::mtime, ngx_pcalloc(), brix_vfs_ctx_t::pool, and brix_sd_stat_t::size.
brix_vfs_adopt_obj()
ngx_int_t brix_vfs_adopt_obj (brix_vfs_ctx_t * ctx, const char * path, brix_sd_obj_t * o, unsigned writable, brix_vfs_file_t ** out)
Definition at line 232 of file vfs_open.c.
References brix_vfs_copy_path(), brix_sd_stat_t::ctime, brix_sd_stat_t::ino, brix_vfs_ctx_t::is_tls, brix_vfs_ctx_t::log, brix_sd_stat_t::mode, brix_sd_stat_t::mtime, ngx_pcalloc(), brix_vfs_ctx_t::pool, and brix_sd_stat_t::size.
Referenced by brix_cache_open(), and brix_vfs_open().
brix_vfs_backend_mkpath()
int brix_vfs_backend_mkpath (const char * root_canon, const char * logical, mode_t mode, ngx_log_t * log)
Definition at line 277 of file vfs_walk.c.
References brix_vfs_backend_resolve(), log, mode, and PATH_MAX.
Referenced by brix_handle_mv(), brix_vfs_mkdir(), brix_vfs_mkdir_parent_path(), and cms_node_exec_driver().
brix_vfs_chmod()
ngx_int_t brix_vfs_chmod (brix_vfs_ctx_t * ctx, mode_t mode)
Definition at line 98 of file vfs_mkdir.c.
References brix_chmod_confined_canon(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_require_write(), brix_vfs_ctx_t::log, mode, brix_sd_setattr_t::mode, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::sd, and brix_sd_setattr_t::set_mode.
Referenced by exec_chmod().
brix_vfs_close()
ngx_int_t brix_vfs_close (brix_vfs_file_t * fh, ngx_log_t * log)
Definition at line 554 of file vfs_open.c.
References BRIX_DIAG_ERR, and log.
Referenced by brix_cksum_aio_done(), brix_dig_handle(), brix_handle_truncate(), brix_http_serve_file_ranged(), brix_query_cksum_path(), brix_zip_http_serve(), copy_block_to_remote(), copy_download(), copy_one_l2r(), copy_one_r2l(), copy_remote_to_block(), copy_upload(), copy_vfs_to_vfs(), copy_web_upload(), cvmfs_tier_get(), do_download(), do_upload(), ngx_http_brix_dashboard_vfs_download_handler(), s3_handle_get(), s3_handle_head(), s3_handle_upload_part_copy(), s3_put_checksum_apply(), s3_put_trailer_checksum_apply(), webdav_handle_get(), webdav_handle_head(), and webdav_handle_lock_inner().
brix_vfs_closedir()
ngx_int_t brix_vfs_closedir (brix_vfs_dir_t * dh, ngx_log_t * log)
Definition at line 359 of file vfs_dir.c.
References BRIX_DIAG_ERR, and log.
Referenced by brix_handle_dirlist(), check_locks_descendants(), fattr_recurse_dir(), mpu_collect(), ngx_http_brix_dashboard_vfs_files_handler(), propfind_walk(), s3_handle_list_parts(), s3_mpu_reap_stale(), s3_walk(), and webdav_search_walk().
brix_vfs_copy()
ngx_int_t brix_vfs_copy (brix_vfs_ctx_t * ctx, const char * dst_resolved, const brix_vfs_copy_opts_t * opts)
Definition at line 29 of file vfs_copy.c.
References brix_lstat_confined_canon(), BRIX_METRIC_OP_COPY, brix_ns_local_copy(), BRIX_NS_OK, brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_now_ns(), brix_vfs_ns_status_errno(), brix_vfs_observe_ctx_op(), brix_vfs_require_write(), brix_vfs_ctx_t::log, brix_ns_copy_opts_t::overwrite, brix_vfs_copy_opts_t::overwrite, brix_ns_copy_opts_t::overwrite_dirs, brix_vfs_copy_opts_t::overwrite_dirs, brix_ns_copy_opts_t::preserve_xattrs, brix_vfs_copy_opts_t::preserve_xattrs, brix_ns_copy_opts_t::recursive, brix_vfs_copy_opts_t::recursive, brix_vfs_ctx_t::root_canon, s, brix_vfs_ctx_t::sd, brix_ns_copy_opts_t::staged_commit, brix_vfs_copy_opts_t::staged_commit, stat(), brix_ns_result_t::status, and brix_ns_result_t::sys_errno.
Referenced by s3_handle_copy_object(), and webdav_handle_copy().
brix_vfs_copyfile()
ngx_int_t brix_vfs_copyfile (ngx_log_t * log, const char * root_canon, const char * src, const char * dst, int preserve_xattrs, brix_vfs_copy_meta_cb meta_cb, void * cookie)
Definition at line 320 of file vfs_walk.c.
References brix_copy_range(), brix_lstat_confined_canon(), brix_ns_copy_fattrs(), brix_open_confined_canon(), log, and stat().
Referenced by brix_vfs_copytree(), and webdav_copy_file().
brix_vfs_copytree()
ngx_int_t brix_vfs_copytree (ngx_log_t * log, const char * root_canon, const char * src, const char * dst, int preserve_xattrs, brix_vfs_copy_meta_cb meta_cb, void * cookie)
Definition at line 368 of file vfs_walk.c.
References brix_fs_is_dot_entry(), brix_lstat_confined_canon(), BRIX_MAX_PATH, brix_mkdir_confined_canon(), brix_ns_copy_fattrs(), brix_opendir_confined_canon(), brix_vfs_copyfile(), brix_vfs_copytree(), log, and stat().
Referenced by brix_vfs_copytree(), and webdav_copy_dir_recursive().
brix_vfs_ctx_init()
void brix_vfs_ctx_init (brix_vfs_ctx_t * vctx, ngx_pool_t * pool, ngx_log_t * log, brix_proto_t proto, const char * root_canon, const char * cache_root_canon, int allow_write, int is_tls, brix_identity_t * identity, const char * resolved_path)
Definition at line 41 of file vfs_open.c.
References brix_vfs_ctx_t::allow_write, brix_vfs_backend_resolve(), brix_vfs_ctx_t::cache_enabled, brix_vfs_ctx_t::cache_root_canon, brix_vfs_ctx_t::identity, brix_path_result_t::is_confined, brix_vfs_ctx_t::is_tls, log, brix_vfs_ctx_t::log, brix_vfs_ctx_t::metrics_proto, brix_vfs_ctx_t::pool, brix_path_result_t::resolved, brix_vfs_ctx_t::resolved, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::rootfd, and brix_vfs_ctx_t::sd.
Referenced by brix_dig_handle(), brix_handle_dirlist(), brix_handle_fattr(), brix_handle_mkdir(), brix_handle_mv(), brix_handle_open(), brix_handle_setattr(), brix_handle_stat(), brix_handle_statx(), brix_handle_truncate(), brix_integrity_invalidate_path(), brix_open_probe(), brix_query_cksum_path(), brix_query_xattr(), brix_zip_http_serve(), cvmfs_tier_get(), fattr_recurse_dir(), op_path_probe(), op_vfs_ctx(), propfind_dir_ctx(), propfind_entry(), s3_build_vfs_ctx(), s3_chunk_finalize(), s3_cksum_vfs_open(), s3_cksum_vfs_unlink(), s3_commit_put(), s3_copy_vfs_ctx(), s3_delete_one(), s3_entry_fill_stat(), s3_put_aio_done(), s3_put_precondition(), s3_tag_vfs_ctx(), s3_user_meta_vfs_ctx(), s3_vfs_ctx(), s3_walk(), s3_walk_classify(), tape_residency(), vfs_browse_ctx(), webdav_copy_probe(), webdav_dead_prop_vfs_ctx_init(), webdav_handle_copy(), webdav_handle_get(), webdav_handle_head(), webdav_lock_sweep_remove(), webdav_lock_vfs_ctx(), webdav_lock_vfs_ctx_init(), webdav_move_probe(), webdav_ns_vfs_ctx_init(), webdav_put_body_inner(), webdav_put_vfs_ctx_init(), webdav_search_walk(), and webdav_tpc_probe().
brix_vfs_dir_fd()
ngx_fd_t brix_vfs_dir_fd (const brix_vfs_dir_t * dh)
Definition at line 169 of file vfs_dir.c.
Referenced by brix_handle_dirlist().
brix_vfs_enumerate_catalog()
ngx_int_t brix_vfs_enumerate_catalog (brix_sd_instance_t * sd, int want_stat, brix_sd_catalog_cb cb, void * ctx)
Definition at line 395 of file vfs_dir.c.
Referenced by brix_scan_run_inventory(), and brix_scan_run_verify_catalog().
brix_vfs_export_relative()
const char * brix_vfs_export_relative (const brix_vfs_ctx_t * ctx, const char * path)
Definition at line 226 of file vfs_open.c.
References brix_vfs_export_relative_root(), and brix_vfs_ctx_t::root_canon.
Referenced by brix_vfs_chmod(), brix_vfs_copy(), brix_vfs_delete(), brix_vfs_getxattr(), brix_vfs_listxattr(), brix_vfs_mkdir(), brix_vfs_opendir_impl(), brix_vfs_probe(), brix_vfs_removexattr(), brix_vfs_rename(), brix_vfs_residency(), brix_vfs_setattr(), brix_vfs_setxattr(), brix_vfs_staged_open(), brix_vfs_stat_impl(), cvmfs_tier_get(), s3_handle_get(), and webdav_handle_get().
brix_vfs_fgetxattr()
ssize_t brix_vfs_fgetxattr (const brix_vfs_ctx_t * ctx, int fd, const char * name, void * buf, size_t bufsz)
Definition at line 212 of file vfs_xattr.c.
References brix_vfs_now_ns(), brix_vfs_xattr_observe_count(), and name.
Referenced by fattr_list(), fattr_read_value(), fattr_read_value_size(), and integrity_xattr_read().
brix_vfs_file_backend_name()
const char * brix_vfs_file_backend_name (const brix_vfs_file_t * fh)
Definition at line 632 of file vfs_open.c.
References brix_sd_backend_name().
Referenced by brix_http_serve_file_ranged().
brix_vfs_file_can_sendfile()
ngx_uint_t brix_vfs_file_can_sendfile (const brix_vfs_file_t * fh)
Definition at line 622 of file vfs_open.c.
References brix_vfs_file_sendfile_fd().
brix_vfs_file_fd()
ngx_fd_t brix_vfs_file_fd (const brix_vfs_file_t * fh)
Definition at line 579 of file vfs_open.c.
Referenced by brix_http_serve_file_ranged(), brix_query_cksum_path(), brix_zip_http_serve(), s3_handle_get(), s3_handle_head(), s3_handle_upload_part_copy(), s3_put_checksum_apply(), s3_put_trailer_checksum_apply(), and webdav_handle_head().
brix_vfs_file_from_cache()
ngx_uint_t brix_vfs_file_from_cache (const brix_vfs_file_t * fh)
Definition at line 659 of file vfs_open.c.
Referenced by brix_http_serve_file_ranged(), and webdav_handle_get().
brix_vfs_file_mtime()
time_t brix_vfs_file_mtime (const brix_vfs_file_t * fh)
Definition at line 653 of file vfs_open.c.
brix_vfs_file_path()
const char * brix_vfs_file_path (const brix_vfs_file_t * fh)
Definition at line 641 of file vfs_open.c.
Referenced by brix_http_serve_file_ranged(), and webdav_handle_get().
brix_vfs_file_pread()
ssize_t brix_vfs_file_pread (brix_vfs_file_t * fh, void * buf, size_t len, off_t off)
Definition at line 595 of file vfs_open.c.
Referenced by brix_serve_memory_backed().
brix_vfs_file_sd_obj()
void brix_vfs_file_sd_obj (const brix_vfs_file_t * fh, brix_sd_obj_t * out)
Definition at line 585 of file vfs_open.c.
References brix_vfs_handle_sd_obj().
Referenced by brix_query_cksum_path().
brix_vfs_file_sendfile_fd()
ngx_fd_t brix_vfs_file_sendfile_fd (const brix_vfs_file_t * fh)
Definition at line 612 of file vfs_open.c.
References brix_vfs_handle_sendfile_fd().
Referenced by brix_dig_handle(), brix_http_serve_file_ranged(), brix_vfs_file_can_sendfile(), and webdav_handle_get().
brix_vfs_file_size()
off_t brix_vfs_file_size (const brix_vfs_file_t * fh)
Definition at line 647 of file vfs_open.c.
brix_vfs_file_stat()
ngx_int_t brix_vfs_file_stat (const brix_vfs_file_t * fh, brix_vfs_stat_t * stat_out)
Definition at line 665 of file vfs_open.c.
References brix_vfs_handle_sd_obj(), brix_vfs_sd_stat_to_vfs(), brix_vfs_stat_t::ctime, brix_vfs_stat_t::ino, brix_vfs_stat_t::is_directory, brix_vfs_stat_t::is_regular, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, and brix_vfs_stat_t::size.
Referenced by brix_dig_handle(), cvmfs_tier_get(), ngx_http_brix_dashboard_vfs_download_handler(), s3_handle_get(), and webdav_handle_get().
brix_vfs_flistxattr()
ssize_t brix_vfs_flistxattr (const brix_vfs_ctx_t * ctx, int fd, void * buf, size_t bufsz)
Definition at line 222 of file vfs_xattr.c.
References brix_vfs_now_ns(), and brix_vfs_xattr_observe_count().
Referenced by fattr_list().
brix_vfs_fremovexattr()
ngx_int_t brix_vfs_fremovexattr (const brix_vfs_ctx_t * ctx, int fd, const char * name)
Definition at line 247 of file vfs_xattr.c.
References BRIX_METRIC_OP_XATTR, brix_vfs_now_ns(), brix_vfs_observe_ctx_op(), and name.
Referenced by brix_integrity_invalidate_fd(), and fattr_del().
brix_vfs_fsetxattr()
ngx_int_t brix_vfs_fsetxattr (const brix_vfs_ctx_t * ctx, int fd, const char * name, const void * value, size_t len, int flags)
Definition at line 232 of file vfs_xattr.c.
References BRIX_METRIC_OP_XATTR, brix_vfs_now_ns(), brix_vfs_observe_ctx_op(), and name.
Referenced by fattr_set(), and integrity_xattr_write_rc().
brix_vfs_getxattr()
ssize_t brix_vfs_getxattr (brix_vfs_ctx_t * ctx, const char * name, void * buf, size_t bufsz)
Definition at line 49 of file vfs_xattr.c.
References brix_getxattr_confined_canon(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_now_ns(), brix_vfs_require_confined(), brix_vfs_xattr_observe_count(), brix_vfs_ctx_t::log, name, brix_vfs_ctx_t::root_canon, and brix_vfs_ctx_t::sd.
Referenced by brix_query_xattr(), fattr_list(), fattr_read_value(), fattr_read_value_size(), s3_tag_load(), s3_user_meta_load(), webdav_dead_prop_append_value(), and webdav_lock_xattr_read().
brix_vfs_listxattr()
ssize_t brix_vfs_listxattr (brix_vfs_ctx_t * ctx, void * buf, size_t bufsz)
Definition at line 81 of file vfs_xattr.c.
References brix_listxattr_confined_canon(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_now_ns(), brix_vfs_require_confined(), brix_vfs_xattr_observe_count(), brix_vfs_ctx_t::log, brix_vfs_ctx_t::root_canon, and brix_vfs_ctx_t::sd.
Referenced by brix_query_xattr(), fattr_list(), fattr_recurse_dir(), and webdav_dead_props_append_all().
brix_vfs_mkdir()
ngx_int_t brix_vfs_mkdir (brix_vfs_ctx_t * ctx, mode_t mode, unsigned parents)
Definition at line 23 of file vfs_mkdir.c.
References BRIX_METRIC_OP_MKDIR, brix_ns_mkdir(), BRIX_NS_OK, brix_vfs_backend_mkpath(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_now_ns(), brix_vfs_observe_ctx_op(), brix_vfs_require_write(), brix_vfs_ctx_t::log, mode, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::sd, brix_ns_result_t::status, and brix_ns_result_t::sys_errno.
Referenced by brix_handle_mkdir(), s3_post_write_object(), s3_put_body_inner(), s3_put_try_sentinel(), and webdav_handle_mkcol().
brix_vfs_mkdir_path()
int brix_vfs_mkdir_path (ngx_log_t * log, const char * root_canon, const char * logical, mode_t mode)
Definition at line 261 of file vfs_walk.c.
References brix_mkdir_confined_canon(), log, and mode.
Referenced by webdav_copy_collection_execute().
brix_vfs_open()
brix_vfs_file_t * brix_vfs_open (brix_vfs_ctx_t * ctx, ngx_uint_t flags, int * err_out)
Definition at line 375 of file vfs_open.c.
References brix_vfs_ctx_t::allow_write, brix_cache_open(), brix_metric_cache_result(), brix_open_beneath(), brix_open_confined_canon(), brix_sd_default_driver(), brix_sd_posix_borrow_instance(), brix_vfs_adopt_fd(), brix_vfs_adopt_obj(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_metrics_proto(), brix_vfs_mkdir_parent_path(), BRIX_VFS_O_MKDIRPATH, BRIX_VFS_O_NOCACHE, BRIX_VFS_O_WRITE, brix_vfs_open_flags(), brix_vfs_require_confined(), brix_vfs_to_sd_flags(), brix_vfs_ctx_t::cache_enabled, brix_vfs_ctx_t::log, open(), brix_vfs_ctx_t::pool, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::rootfd, and brix_vfs_ctx_t::sd.
Referenced by brix_dig_handle(), brix_handle_truncate(), brix_query_cksum_path(), brix_zip_http_serve(), copy_block_to_remote(), copy_download(), copy_one_l2r(), copy_one_r2l(), copy_remote_to_block(), copy_upload(), copy_vfs_to_vfs(), copy_web_upload(), cvmfs_tier_get(), do_download(), do_upload(), ngx_http_brix_dashboard_vfs_download_handler(), s3_cksum_vfs_open(), s3_handle_get(), s3_handle_head(), s3_handle_upload_part_copy(), webdav_handle_get(), webdav_handle_head(), and webdav_handle_lock_inner().
brix_vfs_open_fd()
int brix_vfs_open_fd (ngx_log_t * log, const char * root_canon, const char * logical, int flags, mode_t mode)
Definition at line 229 of file vfs_walk.c.
References brix_open_confined_canon(), log, and mode.
Referenced by ckp_recover_one(), ckp_recover_scan(), s3_handle_upload_part_copy(), s3_mpu_assemble(), s3_put_try_sentinel(), webdav_put_persist_checksums(), and webdav_tpc_run_curl_core().
brix_vfs_open_fd_at()
int brix_vfs_open_fd_at (int rootfd, const char * logical, int flags, mode_t mode)
Definition at line 239 of file vfs_walk.c.
References brix_open_beneath(), and mode.
Referenced by brix_open_resolved_file(), brix_reopen_bound_read_handle(), brix_tpc_prepare_pull(), brix_zip_open_member(), and cms_node_exec_forward().
brix_vfs_opendir()
brix_vfs_dir_t * brix_vfs_opendir (brix_vfs_ctx_t * ctx, int * err_out)
Definition at line 152 of file vfs_dir.c.
References brix_vfs_opendir_impl().
Referenced by brix_handle_dirlist(), ngx_http_brix_dashboard_vfs_files_handler(), and propfind_walk().
brix_vfs_opendir_quiet()
brix_vfs_dir_t * brix_vfs_opendir_quiet (brix_vfs_ctx_t * ctx, int * err_out)
Definition at line 161 of file vfs_dir.c.
References brix_vfs_opendir_impl().
Referenced by check_locks_descendants(), fattr_recurse_dir(), mpu_collect(), s3_handle_list_parts(), s3_mpu_reap_stale(), s3_walk(), and webdav_search_walk().
brix_vfs_pread_full()
ngx_int_t brix_vfs_pread_full (ngx_fd_t fd, u_char * buf, size_t len, off_t offset, size_t * nread)
Definition at line 29 of file vfs_read.c.
References brix_sd_posix_wrap(), and xvfs_pread_full().
Referenced by brix_copy_range_fallback(), brix_http_body_read_all(), brix_http_send_file_compressed(), codec_decode_bufs(), and s3_chunk_feed_buf().
brix_vfs_probe()
ngx_int_t brix_vfs_probe (brix_vfs_ctx_t * ctx, int nofollow, brix_vfs_stat_t * stat_out)
Definition at line 172 of file vfs_stat.c.
References brix_lstat_confined_canon(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_fill_stat(), brix_vfs_require_confined(), brix_vfs_sd_stat_fill(), brix_vfs_ctx_t::log, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::sd, and stat().
Referenced by brix_handle_mv(), brix_handle_stat(), brix_handle_statx(), brix_open_probe(), brix_query_xattr(), check_locks_descendants(), fattr_list(), mpu_collect(), op_path_probe(), s3_chunk_finalize(), s3_commit_put(), s3_entry_fill_stat(), s3_handle_copy_object(), s3_handle_list_parts(), s3_handle_multipart_abort(), s3_handle_upload_part_copy(), s3_mpu_reap_stale(), s3_multipart_complete_body_handler_inner(), s3_post_write_object(), s3_put_aio_done(), s3_put_body_inner(), s3_walk_classify(), webdav_check_locks_tree(), webdav_copy_probe(), webdav_handle_lock_inner(), webdav_lock_reap_null(), webdav_move_probe(), webdav_put_body_inner(), webdav_search_walk(), and webdav_tpc_probe().
brix_vfs_pwrite_full()
ngx_int_t brix_vfs_pwrite_full (ngx_fd_t fd, const u_char * buf, size_t len, off_t offset)
Definition at line 22 of file vfs_write.c.
References brix_sd_posix_driver, and brix_sd_posix_wrap().
Referenced by brix_copy_range_fallback(), brix_http_body_pwrite_full(), brix_vfs_staged_write(), s3_chunk_emit(), s3_post_write_object(), and sd_posix_staged_write().
brix_vfs_readdir()
ngx_int_t brix_vfs_readdir (brix_vfs_dir_t * dh, ngx_str_t * name_out, brix_vfs_stat_t * stat_out)
Definition at line 178 of file vfs_dir.c.
References brix_lstat_confined_canon(), brix_vfs_fill_stat(), brix_vfs_readdir(), brix_vfs_sd_stat_fill(), brix_sd_dirent_t::name, ngx_memcpy, ngx_pnalloc(), PATH_MAX, and stat().
Referenced by brix_handle_dirlist(), brix_vfs_readdir(), fattr_recurse_dir(), and propfind_walk().
brix_vfs_readdir_kind()
ngx_int_t brix_vfs_readdir_kind (brix_vfs_dir_t * dh, ngx_str_t * name_out, brix_vfs_dirent_kind_t * kind_out)
Definition at line 278 of file vfs_dir.c.
References BRIX_VFS_DT_DIR, BRIX_VFS_DT_OTHER, BRIX_VFS_DT_REG, BRIX_VFS_DT_UNKNOWN, brix_sd_stat_t::is_dir, brix_sd_dirent_t::name, ngx_memcpy, ngx_pnalloc(), and PATH_MAX.
Referenced by check_locks_descendants(), mpu_collect(), ngx_http_brix_dashboard_vfs_files_handler(), s3_handle_list_parts(), s3_mpu_reap_stale(), s3_walk(), and webdav_search_walk().
brix_vfs_removexattr()
ngx_int_t brix_vfs_removexattr (brix_vfs_ctx_t * ctx, const char * name)
Definition at line 159 of file vfs_xattr.c.
References BRIX_METRIC_OP_XATTR, brix_removexattr_confined_canon(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_now_ns(), brix_vfs_observe_ctx_op(), brix_vfs_require_confined(), brix_vfs_ctx_t::log, name, brix_vfs_ctx_t::root_canon, and brix_vfs_ctx_t::sd.
Referenced by brix_integrity_invalidate_path(), fattr_del(), s3_tag_store(), webdav_dead_prop_remove(), webdav_lock_sweep_remove(), and webdav_lock_xattr_delete().
brix_vfs_rename()
ngx_int_t brix_vfs_rename (brix_vfs_ctx_t * ctx, const brix_path_result_t * dst)
Definition at line 65 of file vfs_rename.c.
References BRIX_METRIC_OP_RENAME, BRIX_NS_OK, brix_ns_rename(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_now_ns(), brix_vfs_observe_ctx_op(), brix_vfs_require_write(), brix_path_result_t::is_confined, brix_vfs_ctx_t::log, brix_path_result_t::resolved, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::sd, brix_ns_result_t::status, and brix_ns_result_t::sys_errno.
brix_vfs_rename_path()
ngx_int_t brix_vfs_rename_path (brix_sd_instance_t * sd, ngx_log_t * log, const char * root_canon, const char * src, const char * dst, unsigned overwrite, int * was_dir_out)
Definition at line 25 of file vfs_rename.c.
References BRIX_NS_OK, brix_ns_rename(), brix_sd_default_driver(), brix_vfs_export_relative_root(), brix_vfs_ns_status_errno(), brix_sd_stat_t::is_dir, log, s, brix_ns_result_t::status, brix_ns_result_t::sys_errno, and brix_ns_result_t::was_dir.
Referenced by brix_handle_mv(), and webdav_move_execute().
brix_vfs_residency()
ngx_int_t brix_vfs_residency (brix_vfs_ctx_t * ctx, brix_sd_residency_t * out, int * nearline_export)
Definition at line 128 of file vfs_stat.c.
References BRIX_SD_CAP_NEARLINE, brix_sd_caps(), BRIX_SD_RES_ONLINE, brix_vfs_ctx_path(), brix_vfs_decorator_source(), brix_vfs_export_relative(), brix_vfs_require_confined(), and brix_vfs_ctx_t::sd.
Referenced by brix_handle_open(), brix_handle_stat(), brix_handle_statx(), propfind_entry(), s3_handle_get(), s3_handle_head(), and tape_residency().
brix_vfs_rmdir()
ngx_int_t brix_vfs_rmdir (brix_vfs_ctx_t * ctx, unsigned recursive)
Definition at line 158 of file vfs_unlink.c.
References brix_vfs_delete().
Referenced by exec_rmdir(), and webdav_handle_delete().
brix_vfs_setattr()
ngx_int_t brix_vfs_setattr (brix_vfs_ctx_t * ctx, const brix_sd_setattr_t * attr)
Definition at line 143 of file vfs_mkdir.c.
References brix_sd_setattr_t::atime, brix_chmod_confined_canon(), brix_setattr_confined_canon(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_require_write(), brix_sd_setattr_t::gid, brix_vfs_ctx_t::log, brix_sd_setattr_t::mode, brix_sd_setattr_t::mtime, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::sd, brix_sd_setattr_t::set_mode, brix_sd_setattr_t::set_owner, brix_sd_setattr_t::set_times, and brix_sd_setattr_t::uid.
Referenced by brix_handle_setattr().
brix_vfs_setxattr()
ngx_int_t brix_vfs_setxattr (brix_vfs_ctx_t * ctx, const char * name, const void * value, size_t len, int flags)
Definition at line 113 of file vfs_xattr.c.
References BRIX_METRIC_OP_XATTR, brix_setxattr_confined_canon(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_now_ns(), brix_vfs_observe_ctx_op(), brix_vfs_require_confined(), brix_vfs_ctx_t::log, name, brix_vfs_ctx_t::root_canon, and brix_vfs_ctx_t::sd.
Referenced by fattr_set(), s3_tag_store(), s3_user_meta_store(), webdav_dead_prop_set(), and webdav_lock_xattr_write().
brix_vfs_staged_abort()
void brix_vfs_staged_abort (brix_vfs_staged_t * st, unsigned remove_tmp)
Definition at line 311 of file vfs_staged.c.
References brix_staged_abort().
Referenced by s3_chunk_decode_failed(), s3_post_write_object(), s3_put_aio_done(), s3_put_body_inner(), s3_put_streaming(), webdav_put_aio_done(), and webdav_put_body_inner().
brix_vfs_staged_commit()
ngx_int_t brix_vfs_staged_commit (brix_vfs_staged_t * st, unsigned excl)
Definition at line 236 of file vfs_staged.c.
References brix_lstat_confined_canon(), BRIX_METRIC_OP_WRITE, brix_staged_commit(), brix_staged_commit_excl(), brix_vfs_ctx_path(), brix_vfs_now_ns(), brix_vfs_observe_ctx_op(), BRIX_XFER_COMMIT_ERR, brix_xfer_finish(), BRIX_XFER_OK, BRIX_XFER_STAGE, and stat().
Referenced by s3_commit_put(), s3_post_write_object(), webdav_put_aio_done(), and webdav_put_body_inner().
brix_vfs_staged_fd()
ngx_fd_t brix_vfs_staged_fd (const brix_vfs_staged_t * st)
Definition at line 179 of file vfs_staged.c.
Referenced by s3_chunk_aio_thread(), s3_post_write_object(), s3_put_aio_thread(), s3_put_body_inner(), s3_put_streaming(), webdav_put_aio_thread(), and webdav_put_body_inner().
brix_vfs_staged_is_driver()
ngx_uint_t brix_vfs_staged_is_driver (const brix_vfs_staged_t * st)
Definition at line 188 of file vfs_staged.c.
Referenced by s3_put_aio_thread(), webdav_put_aio_thread(), and webdav_put_body_inner().
brix_vfs_staged_open()
brix_vfs_staged_t * brix_vfs_staged_open (brix_vfs_ctx_t * ctx, mode_t mode, ngx_uint_t attempts, int * err_out)
Definition at line 65 of file vfs_staged.c.
References brix_sd_default_driver(), brix_staged_open(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_require_write(), brix_vfs_ctx_t::log, mode, ngx_pcalloc(), brix_vfs_ctx_t::pool, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::sd, and staged_pool_strdup().
Referenced by s3_post_write_object(), s3_put_body_inner(), and webdav_put_body_inner().
brix_vfs_staged_tmp_path()
const char * brix_vfs_staged_tmp_path (const brix_vfs_staged_t * st)
Definition at line 225 of file vfs_staged.c.
brix_vfs_staged_write()
ngx_int_t brix_vfs_staged_write (brix_vfs_staged_t * st, const void * buf, size_t len, off_t off)
Definition at line 196 of file vfs_staged.c.
References brix_vfs_pwrite_full().
Referenced by brix_http_body_write_to_staged().
brix_vfs_stat()
ngx_int_t brix_vfs_stat (brix_vfs_ctx_t * ctx, brix_vfs_stat_t * stat_out)
Definition at line 93 of file vfs_stat.c.
References brix_vfs_stat_impl().
brix_vfs_statf()
ngx_int_t brix_vfs_statf (brix_vfs_ctx_t * ctx, brix_vfs_stat_t * stat_out)
Definition at line 102 of file vfs_stat.c.
References brix_vfs_stat_impl().
Referenced by brix_handle_stat().
brix_vfs_sync()
ngx_int_t brix_vfs_sync (brix_vfs_file_t * fh)
Definition at line 47 of file vfs_sync.c.
References brix_vfs_io_execute(), brix_vfs_job_sync_init(), brix_vfs_job_t::io_errno, and brix_vfs_job_t::obj.
brix_vfs_truncate()
ngx_int_t brix_vfs_truncate (brix_vfs_file_t * fh, off_t length)
Definition at line 24 of file vfs_sync.c.
References brix_vfs_io_execute(), brix_vfs_job_truncate_init(), brix_vfs_job_t::io_errno, and brix_vfs_job_t::obj.
Referenced by brix_handle_truncate().
brix_vfs_unlink()
ngx_int_t brix_vfs_unlink (brix_vfs_ctx_t * ctx)
Definition at line 151 of file vfs_unlink.c.
References brix_vfs_delete().
Referenced by exec_rm(), s3_cksum_vfs_unlink(), s3_delete_one(), s3_handle_delete(), webdav_handle_delete(), and webdav_lock_reap_null().
brix_vfs_unlink_at()
int brix_vfs_unlink_at (int rootfd, const char * logical, int is_dir)
Definition at line 254 of file vfs_walk.c.
References brix_unlink_beneath().
Referenced by cms_node_exec_forward().
brix_vfs_unlink_path()
int brix_vfs_unlink_path (ngx_log_t * log, const char * root_canon, const char * logical)
Definition at line 246 of file vfs_walk.c.
References brix_unlink_confined_canon(), and log.
Referenced by brix_tpc_pull_done(), ckp_recover_one(), fhandle_unlink_staging(), s3_handle_upload_part_copy(), and s3_mpu_assemble().
brix_vfs_walk()
ngx_int_t brix_vfs_walk (ngx_log_t * log, int rootfd, const char * logical, const brix_vfs_walk_opts_t * opts, brix_vfs_walk_file_cb cb, void * cookie, brix_vfs_walk_target_t * target_out, char * errmsg, size_t errsz)
Definition at line 182 of file vfs_walk.c.
References brix_stat_beneath(), BRIX_VFS_WALK_DIR, BRIX_VFS_WALK_FILE, BRIX_VFS_WALK_NONE, BRIX_VFS_WALK_OTHER, log, stat(), vfs_walk_dir(), and vfs_walk_emit_file().
Referenced by brix_ckscan_run(), and brix_scan_run().