nginx-xrootd: src/tpc/outbound/tls.c File Reference
tls.c File Reference
#include "tpc/engine/tpc_internal.h"
#include "core/compat/cstr.h"
#include <string.h>
#include <limits.h>
#include <openssl/ssl.h>
#include <openssl/err.h>
Functions
int tpc_start_tls (brix_tpc_pull_t *t, int fd)
void tpc_tls_teardown (brix_tpc_pull_t *t)
Function Documentation
tpc_start_tls()
int tpc_start_tls (brix_tpc_pull_t * t, int fd)
Definition at line 35 of file tls.c.
References brix_str_cbuf(), brix_tpc_pull_t::conf, brix_tpc_pull_t::err_msg, kXR_NotAuthorized, kXR_ServerError, PATH_MAX, brix_tpc_pull_t::src_host, brix_tpc_pull_t::tls, brix_tpc_pull_t::tls_ctx, ngx_stream_brix_srv_conf_t::trusted_ca, and brix_tpc_pull_t::xrd_error.
Referenced by tpc_bootstrap().
tpc_tls_teardown()
void tpc_tls_teardown (brix_tpc_pull_t * t)
Definition at line 112 of file tls.c.
References brix_tpc_pull_t::tls, and brix_tpc_pull_t::tls_ctx.
Referenced by brix_tpc_pull_thread().