nginx-xrootd: src/protocols/srr/srr.h File Reference
srr.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
Data Structures
struct brix_srr_share_t
struct brix_srr_endpoint_t
struct ngx_http_brix_srr_loc_conf_t
Functions
ngx_int_t ngx_http_brix_srr_handler (ngx_http_request_t *r)
ngx_int_t ngx_http_brix_srr_build_json (ngx_http_request_t *r, ngx_http_brix_srr_loc_conf_t *lcf, u_char **out, size_t *len)
Variables
ngx_module_t ngx_http_brix_srr_module
Function Documentation
ngx_http_brix_srr_build_json()
ngx_int_t ngx_http_brix_srr_build_json (ngx_http_request_t * r, ngx_http_brix_srr_loc_conf_t * lcf, u_char ** out, size_t * len)
Definition at line 149 of file builder.c.
References brix_fs_usage_stat(), brix_pstrdup_z(), BRIX_SERVER_NAME, BRIX_SERVER_VERSION_BARE, ngx_http_brix_srr_loc_conf_t::endpoints, ngx_http_brix_srr_loc_conf_t::id, brix_srr_share_t::name, ngx_http_brix_srr_loc_conf_t::name, name, ngx_pnalloc(), brix_srr_share_t::path, ngx_http_brix_srr_loc_conf_t::quality, ngx_http_brix_srr_loc_conf_t::shares, srr_clamp_size(), srr_endpoint_names(), SRR_JSTR, srr_share_names(), srr_vos_array(), usage(), and ngx_http_brix_srr_loc_conf_t::version.
Referenced by ngx_http_brix_srr_handler().
ngx_http_brix_srr_handler()
ngx_int_t ngx_http_brix_srr_handler (ngx_http_request_t * r)
Definition at line 24 of file handler.c.
References brix_http_source_offer(), BRIX_PCALLOC_OR_RETURN, ngx_http_brix_srr_loc_conf_t::enable, ngx_http_brix_srr_build_json(), and ngx_http_brix_srr_module.
Referenced by ngx_http_brix_srr_set().
Variable Documentation
ngx_http_brix_srr_module
ngx_module_t ngx_http_brix_srr_module extern
Definition at line 111 of file module.c.
Referenced by ngx_http_brix_srr_handler().