nginx-xrootd: src/protocols/ssi/ssi.c File Reference
ssi.c File Reference
#include "core/ngx_brix_module.h"
#include "ssi.h"
#include "ssi_rrinfo.h"
#include "ssi_reply.h"
#include "ssi_service.h"
#include "provider.h"
#include "session.h"
#include "registry.h"
#include "deliver.h"
#include "protocols/ssi/svc_cta/cta_service.h"
#include "protocols/root/connection/fd_table.h"
#include "protocols/root/response/response.h"
#include "core/compat/error_mapping.h"
#include "protocols/root/protocol/opcodes.h"
#include "protocols/root/protocol/wire_core_requests.h"
#include <fcntl.h>
#include <string.h>
#include <unistd.h>
Data Structures
struct ssi_resp_state_t
struct ssi_defer_t
Functions
int brix_ssi_match (ngx_stream_brix_srv_conf_t *conf, const char *path, const char **service, size_t *service_len)
static void ssi_resp_set_metadata (brix_ssi_responder_t *r, const unsigned char *md, size_t len)
static void ssi_resp_set_response (brix_ssi_responder_t *r, const unsigned char *buf, size_t len, int last)
static void ssi_resp_alert (brix_ssi_responder_t *r, const unsigned char *buf, size_t len)
static void ssi_resp_error (brix_ssi_responder_t *r, int code, const char *text)
static int ssi_resp_defer_accept (brix_ssi_responder_t *r)
static int ssi_resp_defer_refuse (brix_ssi_responder_t *r)
static void ** ssi_resp_svc_slot (brix_ssi_responder_t *r)
static void ssi_responder_init (brix_ssi_responder_t *r, ssi_resp_state_t *st, int(*defer)(brix_ssi_responder_t *))
static void ssi_dispatch (brix_ssi_req_t *rq, brix_ssi_process_fn process)
static void ssi_complete_deferred (brix_ctx_t *ctx, ngx_connection_t *c, brix_ssi_session_t *sess, brix_ssi_req_t *rq)
static void ssi_defer_cancel (void *p)
static void ssi_defer_timer_handler (ngx_event_t *ev)
static ngx_int_t ssi_defer_arm (brix_ctx_t *ctx, ngx_connection_t *c, brix_ssi_session_t *sess, brix_ssi_req_t *rq)
void brix_ssi_handle_cleanup (void *ssi_session)
ngx_int_t brix_ssi_open (brix_ctx_t *ctx, ngx_connection_t *c, const char *service, size_t service_len, uint16_t options)
ngx_int_t brix_ssi_write (brix_ctx_t *ctx, ngx_connection_t *c, int idx, const unsigned char off8[8])
ngx_int_t brix_ssi_query (brix_ctx_t *ctx, ngx_connection_t *c, int idx, const unsigned char *body, size_t body_len)
ngx_int_t brix_ssi_read (brix_ctx_t *ctx, ngx_connection_t *c, int idx, uint64_t offset, uint32_t rlen)
Function Documentation
brix_ssi_handle_cleanup()
void brix_ssi_handle_cleanup (void * ssi_session)
Definition at line 301 of file ssi.c.
References BRIX_SSI_MAX_INFLIGHT, brix_ssi_registry_remove(), brix_ssi_session_t::conn_id, brix_ssi_req_t::defer_ctx, brix_ssi_req_t::in_use, brix_ssi_session_t::rr, and ssi_defer_cancel().
Referenced by brix_free_fhandle().
brix_ssi_match()
int brix_ssi_match (ngx_stream_brix_srv_conf_t * conf, const char * path, const char ** service, size_t * service_len)
Definition at line 31 of file ssi.c.
References BRIX_SSI_PREFIX, BRIX_SSI_PREFIX_LEN, and ngx_stream_brix_srv_conf_t::ssi_enable.
Referenced by brix_handle_open().
brix_ssi_open()
ngx_int_t brix_ssi_open (brix_ctx_t * ctx, ngx_connection_t * c, const char * service, size_t service_len, uint16_t options)
Definition at line 319 of file ssi.c.
References brix_alloc_fhandle(), brix_build_resp_hdr(), brix_free_fhandle(), brix_queue_response(), brix_send_error(), brix_ssi_cta_configure(), brix_ssi_provider_lookup(), brix_ssi_registry_add(), brix_ssi_session_create(), c, close(), brix_ssi_session_t::conn_id, brix_ctx_recv_t::cur_streamid, brix_file_t::fd, ServerOpenBody::fhandle, brix_ctx_t::files, brix_file_t::is_regular, kXR_NoMemory, kXR_NotFound, kXR_ok, kXR_readable, kXR_retstat, kXR_ServerError, kXR_writable, brix_ssi_session_t::max_inflight, ngx_memcpy, ngx_stream_brix_module, open(), brix_file_t::readable, brix_ctx_t::recv, brix_ssi_session_t::request_max, brix_ssi_session_t::response_max, brix_file_t::ssi, ngx_stream_brix_srv_conf_t::ssi_cta_enable, ngx_stream_brix_srv_conf_t::ssi_cta_executor, ngx_stream_brix_srv_conf_t::ssi_cta_journal, ngx_stream_brix_srv_conf_t::ssi_max_inflight, ngx_stream_brix_srv_conf_t::ssi_request_max, ngx_stream_brix_srv_conf_t::ssi_response_max, brix_file_t::writable, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_handle_open().
brix_ssi_query()
ngx_int_t brix_ssi_query (brix_ctx_t * ctx, ngx_connection_t * c, int idx, const unsigned char * body, size_t body_len)
Definition at line 517 of file ssi.c.
References brix_send_error(), brix_send_ok(), BRIX_SRV_METRIC_INC, BRIX_SSI_ATTN_FULL, BRIX_SSI_ATTN_PEND, BRIX_SSI_CMD_CAN, brix_ssi_reply_build(), brix_ssi_reply_len(), brix_ssi_rrinfo_decode(), BRIX_SSI_RRINFO_LEN, brix_ssi_session_drop(), brix_ssi_session_req(), c, brix_ssi_respbuf_t::data, brix_ssi_req_t::err_code, brix_ssi_req_t::err_text, brix_ssi_req_t::error, brix_ctx_t::files, kXR_ArgInvalid, kXR_InvalidRequest, kXR_NoMemory, kXR_ServerError, brix_ssi_respbuf_t::len, brix_ssi_req_t::meta, brix_ssi_req_t::meta_len, brix_ssi_req_t::resp, brix_ssi_req_t::responded, brix_file_t::ssi, and brix_ssi_req_t::streaming.
Referenced by brix_handle_query().
brix_ssi_read()
ngx_int_t brix_ssi_read (brix_ctx_t * ctx, ngx_connection_t * c, int idx, uint64_t offset, uint32_t rlen)
Definition at line 580 of file ssi.c.
References brix_send_ok(), BRIX_SRV_METRIC_INC, brix_ssi_rrinfo_decode(), brix_ssi_session_req(), c, brix_ssi_respbuf_t::data, brix_ssi_req_t::dispatched, brix_ssi_req_t::error, brix_ctx_t::files, brix_ssi_respbuf_t::len, brix_ssi_provider_t::process, brix_ssi_session_t::provider, brix_ssi_req_t::read_cursor, brix_ssi_req_t::resp, brix_ssi_req_t::responded, brix_file_t::ssi, and ssi_dispatch().
Referenced by brix_handle_read().
brix_ssi_write()
ngx_int_t brix_ssi_write (brix_ctx_t * ctx, ngx_connection_t * c, int idx, const unsigned char off8[8])
Definition at line 436 of file ssi.c.
References brix_send_error(), brix_send_ok(), brix_send_waitresp(), BRIX_SRV_METRIC_INC, BRIX_SSI_CMD_CAN, BRIX_SSI_REQ_MAX, brix_ssi_rrinfo_decode(), brix_ssi_session_drop(), brix_ssi_session_req(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_streamid, brix_ssi_req_t::defer_streamid, brix_ssi_req_t::deferred, brix_ssi_req_t::dispatched, brix_ctx_t::files, brix_ssi_req_t::have_size, kXR_ArgTooLong, kXR_FileLocked, kXR_NoMemory, kXR_Overloaded, ngx_memcpy, brix_ctx_recv_t::payload, brix_ssi_provider_t::process, brix_ssi_session_t::provider, brix_ctx_t::recv, brix_ssi_req_t::req, brix_ssi_req_t::req_expected, brix_ssi_req_t::req_len, brix_ssi_session_t::request_max, brix_ssi_req_t::responded, brix_file_t::ssi, ssi_defer_arm(), ssi_dispatch(), and brix_ssi_req_t::waiting.
Referenced by brix_handle_write().
ssi_complete_deferred()
static void ssi_complete_deferred (brix_ctx_t * ctx, ngx_connection_t * c, brix_ssi_session_t * sess, brix_ssi_req_t * rq) static
Definition at line 194 of file ssi.c.
References c, brix_ssi_req_t::err_code, brix_ssi_req_t::error, kXR_ServerError, brix_ssi_provider_t::process, brix_ssi_session_t::provider, brix_ssi_req_t::req, brix_ssi_req_t::req_len, brix_ssi_req_t::responded, ssi_resp_defer_refuse(), and ssi_responder_init().
Referenced by ssi_defer_timer_handler().
ssi_defer_arm()
static ngx_int_t ssi_defer_arm (brix_ctx_t * ctx, ngx_connection_t * c, brix_ssi_session_t * sess, brix_ssi_req_t * rq) static
Definition at line 273 of file ssi.c.
References c, ssi_defer_t::c, brix_ssi_session_t::conn_id, ssi_defer_t::ctx, brix_ssi_req_t::defer_ctx, brix_ssi_session_t::generation, ssi_defer_t::generation, ssi_defer_t::req_id, brix_ssi_req_t::req_id, ssi_defer_t::session_key, ssi_defer_timer_handler(), and ssi_defer_t::timer.
Referenced by brix_ssi_write().
ssi_defer_cancel()
static void ssi_defer_cancel (void * p) static
Definition at line 229 of file ssi.c.
References ssi_defer_t::timer.
Referenced by brix_ssi_handle_cleanup().
ssi_defer_timer_handler()
static void ssi_defer_timer_handler (ngx_event_t * ev) static
Definition at line 243 of file ssi.c.
References brix_ssi_deliver(), brix_ssi_registry_find(), brix_ssi_session_req(), ssi_defer_t::c, ssi_defer_t::ctx, brix_ssi_req_t::defer_ctx, brix_ssi_req_t::error, ssi_defer_t::generation, ssi_defer_t::req_id, brix_ssi_req_t::responded, s, ssi_defer_t::session_key, ssi_complete_deferred(), SSI_DLV_ERROR, SSI_DLV_PEND, SSI_DLV_RESPONSE, and brix_ssi_req_t::streaming.
Referenced by ssi_defer_arm().
ssi_dispatch()
static void ssi_dispatch (brix_ssi_req_t * rq, brix_ssi_process_fn process) static
Definition at line 175 of file ssi.c.
References brix_ssi_req_t::dispatched, brix_ssi_req_t::err_code, brix_ssi_req_t::error, kXR_ServerError, brix_ssi_req_t::req, brix_ssi_req_t::req_len, brix_ssi_req_t::responded, ssi_resp_defer_accept(), and ssi_responder_init().
Referenced by brix_ssi_read(), and brix_ssi_write().
ssi_resp_alert()
static void ssi_resp_alert (brix_ssi_responder_t * r, const unsigned char * buf, size_t len) static
Definition at line 109 of file ssi.c.
References brix_ssi_deliver_alert(), ssi_resp_state_t::c, ssi_resp_state_t::ctx, ssi_resp_state_t::rq, and brix_ssi_req_t::waiting.
Referenced by ssi_responder_init().
ssi_resp_defer_accept()
static int ssi_resp_defer_accept (brix_ssi_responder_t * r) static
Definition at line 139 of file ssi.c.
Referenced by ssi_dispatch().
ssi_resp_defer_refuse()
static int ssi_resp_defer_refuse (brix_ssi_responder_t * r) static
Definition at line 147 of file ssi.c.
Referenced by ssi_complete_deferred().
ssi_resp_error()
static void ssi_resp_error (brix_ssi_responder_t * r, int code, const char * text) static
Definition at line 122 of file ssi.c.
References brix_kxr_from_errno(), brix_ssi_req_t::err_code, brix_ssi_req_t::err_text, brix_ssi_req_t::error, kXR_ServerError, and brix_ssi_req_t::responded.
Referenced by ssi_responder_init().
ssi_resp_set_metadata()
static void ssi_resp_set_metadata (brix_ssi_responder_t * r, const unsigned char * md, size_t len) static
Definition at line 68 of file ssi.c.
References BRIX_SSI_META_MAX, brix_ssi_req_t::meta, brix_ssi_req_t::meta_len, ngx_memcpy, and brix_ssi_req_t::pool.
Referenced by ssi_responder_init().
ssi_resp_set_response()
static void ssi_resp_set_response (brix_ssi_responder_t * r, const unsigned char * buf, size_t len, int last) static
Definition at line 87 of file ssi.c.
References BRIX_SSI_RESP_MAX, brix_ssi_respbuf_append(), brix_ssi_req_t::err_code, brix_ssi_req_t::error, kXR_NoMemory, brix_ssi_req_t::resp, brix_ssi_req_t::responded, brix_ssi_req_t::response_max, and brix_ssi_req_t::streaming.
Referenced by ssi_responder_init().
ssi_resp_svc_slot()
static void ** ssi_resp_svc_slot (brix_ssi_responder_t * r) static
Definition at line 154 of file ssi.c.
Referenced by ssi_responder_init().
ssi_responder_init()
static void ssi_responder_init (brix_ssi_responder_t * r, ssi_resp_state_t * st, int(*)(brix_ssi_responder_t *) defer) static
Definition at line 160 of file ssi.c.
References ssi_resp_alert(), ssi_resp_error(), ssi_resp_set_metadata(), ssi_resp_set_response(), and ssi_resp_svc_slot().
Referenced by ssi_complete_deferred(), and ssi_dispatch().