nginx-xrootd: src/protocols/ssi/ssi.h File Reference
ssi.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include "core/types/context.h"
#include "ssi_service.h"
#include "ssi_req.h"
Macros
#define BRIX_SSI_PREFIX "/.ssi/"
#define BRIX_SSI_PREFIX_LEN (sizeof(BRIX_SSI_PREFIX) - 1)
#define BRIX_SSI_REQ_MAX (1u << 20) /* 1 MiB cap on a unary request */
#define BRIX_SSI_RESP_MAX (1u << 20) /* 1 MiB cap on a response */
#define BRIX_SSI_META_MAX 4096 /* metadata cap */
Functions
int brix_ssi_match (ngx_stream_brix_srv_conf_t *conf, const char *path, const char **service, size_t *service_len)
ngx_int_t brix_ssi_open (brix_ctx_t *ctx, ngx_connection_t *c, const char *service, size_t service_len, uint16_t options)
ngx_int_t brix_ssi_write (brix_ctx_t *ctx, ngx_connection_t *c, int idx, const unsigned char off8[8])
ngx_int_t brix_ssi_query (brix_ctx_t *ctx, ngx_connection_t *c, int idx, const unsigned char *body, size_t body_len)
ngx_int_t brix_ssi_read (brix_ctx_t *ctx, ngx_connection_t *c, int idx, uint64_t offset, uint32_t rlen)
void brix_ssi_handle_cleanup (void *ssi_session)
Macro Definition Documentation
BRIX_SSI_META_MAX
#define BRIX_SSI_META_MAX 4096 /* metadata cap */
Definition at line 33 of file ssi.h.
BRIX_SSI_PREFIX
#define BRIX_SSI_PREFIX "/.ssi/"
Definition at line 29 of file ssi.h.
BRIX_SSI_PREFIX_LEN
#define BRIX_SSI_PREFIX_LEN (sizeof(BRIX_SSI_PREFIX) - 1)
Definition at line 30 of file ssi.h.
BRIX_SSI_REQ_MAX
#define BRIX_SSI_REQ_MAX (1u << 20) /* 1 MiB cap on a unary request */
Definition at line 31 of file ssi.h.
BRIX_SSI_RESP_MAX
#define BRIX_SSI_RESP_MAX (1u << 20) /* 1 MiB cap on a response */
Definition at line 32 of file ssi.h.
Function Documentation
brix_ssi_handle_cleanup()
void brix_ssi_handle_cleanup (void * ssi_session)
Definition at line 301 of file ssi.c.
References BRIX_SSI_MAX_INFLIGHT, brix_ssi_registry_remove(), brix_ssi_session_t::conn_id, brix_ssi_req_t::defer_ctx, brix_ssi_req_t::in_use, brix_ssi_session_t::rr, and ssi_defer_cancel().
Referenced by brix_free_fhandle().
brix_ssi_match()
int brix_ssi_match (ngx_stream_brix_srv_conf_t * conf, const char * path, const char ** service, size_t * service_len)
Definition at line 31 of file ssi.c.
References BRIX_SSI_PREFIX, BRIX_SSI_PREFIX_LEN, and ngx_stream_brix_srv_conf_t::ssi_enable.
Referenced by brix_handle_open().
brix_ssi_open()
ngx_int_t brix_ssi_open (brix_ctx_t * ctx, ngx_connection_t * c, const char * service, size_t service_len, uint16_t options)
Definition at line 319 of file ssi.c.
References brix_alloc_fhandle(), brix_build_resp_hdr(), brix_free_fhandle(), brix_queue_response(), brix_send_error(), brix_ssi_cta_configure(), brix_ssi_provider_lookup(), brix_ssi_registry_add(), brix_ssi_session_create(), c, close(), brix_ssi_session_t::conn_id, brix_ctx_recv_t::cur_streamid, brix_file_t::fd, ServerOpenBody::fhandle, brix_ctx_t::files, brix_file_t::is_regular, kXR_NoMemory, kXR_NotFound, kXR_ok, kXR_readable, kXR_retstat, kXR_ServerError, kXR_writable, brix_ssi_session_t::max_inflight, ngx_memcpy, ngx_stream_brix_module, open(), brix_file_t::readable, brix_ctx_t::recv, brix_ssi_session_t::request_max, brix_ssi_session_t::response_max, brix_file_t::ssi, ngx_stream_brix_srv_conf_t::ssi_cta_enable, ngx_stream_brix_srv_conf_t::ssi_cta_executor, ngx_stream_brix_srv_conf_t::ssi_cta_journal, ngx_stream_brix_srv_conf_t::ssi_max_inflight, ngx_stream_brix_srv_conf_t::ssi_request_max, ngx_stream_brix_srv_conf_t::ssi_response_max, brix_file_t::writable, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_handle_open().
brix_ssi_query()
ngx_int_t brix_ssi_query (brix_ctx_t * ctx, ngx_connection_t * c, int idx, const unsigned char * body, size_t body_len)
Definition at line 517 of file ssi.c.
References brix_send_error(), brix_send_ok(), BRIX_SRV_METRIC_INC, BRIX_SSI_ATTN_FULL, BRIX_SSI_ATTN_PEND, BRIX_SSI_CMD_CAN, brix_ssi_reply_build(), brix_ssi_reply_len(), brix_ssi_rrinfo_decode(), BRIX_SSI_RRINFO_LEN, brix_ssi_session_drop(), brix_ssi_session_req(), c, brix_ssi_respbuf_t::data, brix_ssi_req_t::err_code, brix_ssi_req_t::err_text, brix_ssi_req_t::error, brix_ctx_t::files, kXR_ArgInvalid, kXR_InvalidRequest, kXR_NoMemory, kXR_ServerError, brix_ssi_respbuf_t::len, brix_ssi_req_t::meta, brix_ssi_req_t::meta_len, brix_ssi_req_t::resp, brix_ssi_req_t::responded, brix_file_t::ssi, and brix_ssi_req_t::streaming.
Referenced by brix_handle_query().
brix_ssi_read()
ngx_int_t brix_ssi_read (brix_ctx_t * ctx, ngx_connection_t * c, int idx, uint64_t offset, uint32_t rlen)
Definition at line 580 of file ssi.c.
References brix_send_ok(), BRIX_SRV_METRIC_INC, brix_ssi_rrinfo_decode(), brix_ssi_session_req(), c, brix_ssi_respbuf_t::data, brix_ssi_req_t::dispatched, brix_ssi_req_t::error, brix_ctx_t::files, brix_ssi_respbuf_t::len, brix_ssi_provider_t::process, brix_ssi_session_t::provider, brix_ssi_req_t::read_cursor, brix_ssi_req_t::resp, brix_ssi_req_t::responded, brix_file_t::ssi, and ssi_dispatch().
Referenced by brix_handle_read().
brix_ssi_write()
ngx_int_t brix_ssi_write (brix_ctx_t * ctx, ngx_connection_t * c, int idx, const unsigned char off8[8])
Definition at line 436 of file ssi.c.
References brix_send_error(), brix_send_ok(), brix_send_waitresp(), BRIX_SRV_METRIC_INC, BRIX_SSI_CMD_CAN, BRIX_SSI_REQ_MAX, brix_ssi_rrinfo_decode(), brix_ssi_session_drop(), brix_ssi_session_req(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_streamid, brix_ssi_req_t::defer_streamid, brix_ssi_req_t::deferred, brix_ssi_req_t::dispatched, brix_ctx_t::files, brix_ssi_req_t::have_size, kXR_ArgTooLong, kXR_FileLocked, kXR_NoMemory, kXR_Overloaded, ngx_memcpy, brix_ctx_recv_t::payload, brix_ssi_provider_t::process, brix_ssi_session_t::provider, brix_ctx_t::recv, brix_ssi_req_t::req, brix_ssi_req_t::req_expected, brix_ssi_req_t::req_len, brix_ssi_session_t::request_max, brix_ssi_req_t::responded, brix_file_t::ssi, ssi_defer_arm(), ssi_dispatch(), and brix_ssi_req_t::waiting.
Referenced by brix_handle_write().