nginx-xrootd: src/protocols/ssi/ssi_reply.c File Reference
ssi_reply.c File Reference
#include "ssi_reply.h"
#include "ssi_rrinfo.h"
#include <string.h>
Functions
size_t brix_ssi_reply_len (size_t md_len, size_t data_len)
size_t brix_ssi_reply_build (char tag, const unsigned char *md, size_t md_len, const unsigned char *data, size_t data_len, unsigned char *out)
Function Documentation
brix_ssi_reply_build()
size_t brix_ssi_reply_build (char tag, const unsigned char * md, size_t md_len, const unsigned char * data, size_t data_len, unsigned char * out)
Definition at line 19 of file ssi_reply.c.
References brix_ssi_attn_encode(), and BRIX_SSI_ATTN_LEN.
Referenced by brix_ssi_deliver_alert(), brix_ssi_query(), ssi_push_reply(), test_alert_tag(), test_full_response_layout(), and test_no_metadata().
brix_ssi_reply_len()
size_t brix_ssi_reply_len (size_t md_len, size_t data_len)
Definition at line 13 of file ssi_reply.c.
References BRIX_SSI_ATTN_LEN.
Referenced by brix_ssi_deliver_alert(), brix_ssi_query(), ssi_push_reply(), and test_full_response_layout().