nginx-xrootd: src/protocols/ssi/session.h File Reference
session.h File Reference
#include <stddef.h>
#include <stdint.h>
#include "ssi_req.h"
#include "provider.h"
Data Structures
struct brix_ssi_session_t
Macros
#define BRIX_SSI_MAX_INFLIGHT 8
Functions
brix_ssi_session_t * brix_ssi_session_create (ngx_pool_t *pool, const char *service, size_t service_len, const brix_ssi_provider_t *provider)
brix_ssi_req_t * brix_ssi_session_req (brix_ssi_session_t *s, uint32_t req_id, int create)
void brix_ssi_session_drop (brix_ssi_session_t *s, uint32_t req_id)
Macro Definition Documentation
BRIX_SSI_MAX_INFLIGHT
#define BRIX_SSI_MAX_INFLIGHT 8
Definition at line 24 of file session.h.
Function Documentation
brix_ssi_session_create()
brix_ssi_session_t * brix_ssi_session_create (ngx_pool_t * pool, const char * service, size_t service_len, const brix_ssi_provider_t * provider)
Definition at line 24 of file session.c.
References brix_ssi_session_t::generation, brix_ssi_session_t::pool, brix_ssi_session_t::provider, s, brix_ssi_session_t::service, SSI_ALLOC, and ssi_gen_seq.
Referenced by brix_ssi_open(), test_create_and_lookup(), test_generation_increments(), test_lookup_absent(), and test_table_full().
brix_ssi_session_drop()
void brix_ssi_session_drop (brix_ssi_session_t * s, uint32_t req_id)
Definition at line 80 of file session.c.
References BRIX_SSI_MAX_INFLIGHT, brix_ssi_req_t::in_use, brix_ssi_req_t::req_id, brix_ssi_session_t::rr, and s.
Referenced by brix_ssi_query(), brix_ssi_write(), and test_table_full().
brix_ssi_session_req()
brix_ssi_req_t * brix_ssi_session_req (brix_ssi_session_t * s, uint32_t req_id, int create)
Definition at line 47 of file session.c.
References BRIX_SSI_MAX_INFLIGHT, brix_ssi_req_t::in_use, brix_ssi_session_t::max_inflight, brix_ssi_respbuf_t::pool, brix_ssi_session_t::pool, brix_ssi_req_t::pool, brix_ssi_req_t::req_id, brix_ssi_req_t::resp, brix_ssi_session_t::response_max, brix_ssi_req_t::response_max, brix_ssi_session_t::rr, and s.
Referenced by brix_ssi_deliver(), brix_ssi_query(), brix_ssi_read(), brix_ssi_write(), ssi_defer_timer_handler(), test_create_and_lookup(), test_lookup_absent(), and test_table_full().