nginx-xrootd: src/protocols/ssi/ssi_rrinfo_unittest.c File Reference
ssi_rrinfo_unittest.c File Reference
#include "ssi_rrinfo.h"
#include <stdio.h>
#include <string.h>
Macros
#define CHECK(cond)
Functions
static void hex (const char *s, unsigned char *out, size_t n)
static int bytes_eq (const unsigned char *a, const char *hexstr, size_t n)
static void test_decode_golden (void)
static void test_encode_golden (void)
static void test_roundtrip (void)
static void test_id_masked_to_24_bits (void)
static void test_attn_golden (void)
static void test_attn_pend_and_alrt_tags (void)
int main (void)
Variables
static int g_fail
Macro Definition Documentation
CHECK
#define CHECK (cond)
Value:
    do { \
    if (!(cond)) { printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
                   g_fail++; } \
} while (0)
Definition at line 17 of file ssi_rrinfo_unittest.c.
Function Documentation
bytes_eq()
static int bytes_eq (const unsigned char * a, const char * hexstr, size_t n) static
Definition at line 34 of file ssi_rrinfo_unittest.c.
References hex().
Referenced by test_attn_golden(), test_attn_pend_and_alrt_tags(), and test_encode_golden().
hex()
static void hex (const char * s, unsigned char * out, size_t n) static
Definition at line 24 of file ssi_rrinfo_unittest.c.
References s.
Referenced by brix_access_json_escape(), brix_cache_commit_staged(), brix_cache_verify_cvmfs_cas(), brix_cache_verify_emit(), brix_cache_verify_part(), brix_cache_verify_report_mismatch(), brix_checksum_hex_encode(), brix_checksum_hex_fd(), brix_checksum_hex_name_fd(), brix_checksum_hex_obj(), brix_ckmf_parse_line(), brix_ckscan_append(), brix_cksum_fd(), brix_cli_cksum_main(), brix_deleg_store_put(), brix_gsi_cipher_parse_peer(), brix_gsi_dh_pub_decode(), brix_gsi_dh_pub_encode(), brix_hex_encode(), brix_integrity_get_fd(), brix_macaroon_secret_parse(), brix_prepare_owner_key(), brix_query_cksum(), brix_sd_xroot_query_checksum(), brix_sess_default_sanitize(), brix_sss_keytab_write(), bytes_eq(), bytes_eq(), ckcheck_line_algo(), ckcheck_process_line(), ckscan_walk_file(), cksum_compute_local(), ckv_add_cache_record(), ckv_collect_sidecar(), ckv_decode_xattr_value(), do_cksum(), entry_cksum(), integrity_compute_hex(), integrity_persist_computed(), pblock_gen_blob_id(), pwd_from_hex(), pwd_unhex(), remote_md5(), remote_tree_visitor(), s3_chunk_ext_signature(), scan_qencode(), sss_decode_hex(), tape_mint_id(), test_decode_golden(), token_sanitize_for_log(), tree_emit_file(), verify_compute_wire_hex(), webdav_dead_prop_attr_name(), webdav_dead_prop_decode_hex(), writev_parse_seg(), xfs_getxattr(), and xfs_getxattr().
main()
int main (void)
Definition at line 141 of file ssi_rrinfo_unittest.c.
References g_fail, test_attn_golden(), test_attn_pend_and_alrt_tags(), test_decode_golden(), test_encode_golden(), test_id_masked_to_24_bits(), and test_roundtrip().
test_attn_golden()
static void test_attn_golden (void) static
Definition at line 120 of file ssi_rrinfo_unittest.c.
References brix_ssi_attn_encode(), BRIX_SSI_ATTN_FULL, bytes_eq(), and CHECK.
Referenced by main().
test_attn_pend_and_alrt_tags()
static void test_attn_pend_and_alrt_tags (void) static
Definition at line 130 of file ssi_rrinfo_unittest.c.
References BRIX_SSI_ATTN_ALRT, brix_ssi_attn_encode(), BRIX_SSI_ATTN_PEND, bytes_eq(), and CHECK.
Referenced by main().
test_decode_golden()
static void test_decode_golden (void) static
Definition at line 45 of file ssi_rrinfo_unittest.c.
References BRIX_SSI_CMD_CAN, BRIX_SSI_CMD_RWT, BRIX_SSI_CMD_RXQ, brix_ssi_rrinfo_decode(), CHECK, and hex().
Referenced by main().
test_encode_golden()
static void test_encode_golden (void) static
Definition at line 81 of file ssi_rrinfo_unittest.c.
References BRIX_SSI_CMD_CAN, BRIX_SSI_CMD_RWT, BRIX_SSI_CMD_RXQ, brix_ssi_rrinfo_encode(), bytes_eq(), and CHECK.
Referenced by main().
test_id_masked_to_24_bits()
static void test_id_masked_to_24_bits (void) static
Definition at line 109 of file ssi_rrinfo_unittest.c.
References BRIX_SSI_CMD_RXQ, brix_ssi_rrinfo_decode(), brix_ssi_rrinfo_encode(), and CHECK.
Referenced by main().
test_roundtrip()
static void test_roundtrip (void) static
Definition at line 96 of file ssi_rrinfo_unittest.c.
References BRIX_SSI_CMD_RXQ, brix_ssi_rrinfo_decode(), brix_ssi_rrinfo_encode(), and CHECK.
Referenced by main().
Variable Documentation
g_fail
int g_fail static
Definition at line 16 of file ssi_rrinfo_unittest.c.
Referenced by main().