nginx-xrootd: src/protocols/ssi/ssi_rrinfo.h File Reference
ssi_rrinfo.h File Reference
#include <stddef.h>
#include <stdint.h>
Macros
#define BRIX_SSI_CMD_RXQ 0 /* request / response data exchange */
#define BRIX_SSI_CMD_RWT 1 /* response wait */
#define BRIX_SSI_CMD_CAN 2 /* cancel */
#define BRIX_SSI_ATTN_ALRT '!' /* alert */
#define BRIX_SSI_ATTN_FULL ':' /* full response present */
#define BRIX_SSI_ATTN_PEND '*' /* response pending */
#define BRIX_SSI_RRINFO_LEN 8
#define BRIX_SSI_ATTN_LEN 16
#define BRIX_SSI_ID_MAX 0x00ffffffu /* reqId is 24-bit */
Functions
void brix_ssi_rrinfo_decode (const unsigned char off[8], int *cmd, uint32_t *id, uint32_t *size)
void brix_ssi_rrinfo_encode (int cmd, uint32_t id, uint32_t size, unsigned char off[8])
void brix_ssi_attn_encode (char tag, unsigned char flags, uint16_t pfx_len, uint32_t md_len, unsigned char out[16])
Macro Definition Documentation
BRIX_SSI_ATTN_ALRT
#define BRIX_SSI_ATTN_ALRT '!' /* alert */
Definition at line 28 of file ssi_rrinfo.h.
BRIX_SSI_ATTN_FULL
#define BRIX_SSI_ATTN_FULL ':' /* full response present */
Definition at line 29 of file ssi_rrinfo.h.
BRIX_SSI_ATTN_LEN
#define BRIX_SSI_ATTN_LEN 16
Definition at line 33 of file ssi_rrinfo.h.
BRIX_SSI_ATTN_PEND
#define BRIX_SSI_ATTN_PEND '*' /* response pending */
Definition at line 30 of file ssi_rrinfo.h.
BRIX_SSI_CMD_CAN
#define BRIX_SSI_CMD_CAN 2 /* cancel */
Definition at line 25 of file ssi_rrinfo.h.
BRIX_SSI_CMD_RWT
#define BRIX_SSI_CMD_RWT 1 /* response wait */
Definition at line 24 of file ssi_rrinfo.h.
BRIX_SSI_CMD_RXQ
#define BRIX_SSI_CMD_RXQ 0 /* request / response data exchange */
Definition at line 23 of file ssi_rrinfo.h.
BRIX_SSI_ID_MAX
#define BRIX_SSI_ID_MAX 0x00ffffffu /* reqId is 24-bit */
Definition at line 34 of file ssi_rrinfo.h.
BRIX_SSI_RRINFO_LEN
#define BRIX_SSI_RRINFO_LEN 8
Definition at line 32 of file ssi_rrinfo.h.
Function Documentation
brix_ssi_attn_encode()
void brix_ssi_attn_encode (char tag, unsigned char flags, uint16_t pfx_len, uint32_t md_len, unsigned char out[16])
Definition at line 43 of file ssi_rrinfo.c.
References BRIX_SSI_ATTN_LEN.
Referenced by brix_ssi_reply_build(), test_attn_golden(), and test_attn_pend_and_alrt_tags().
brix_ssi_rrinfo_decode()
void brix_ssi_rrinfo_decode (const unsigned char off[8], int * cmd, uint32_t * id, uint32_t * size)
Definition at line 14 of file ssi_rrinfo.c.
Referenced by brix_ssi_query(), brix_ssi_read(), brix_ssi_write(), test_decode_golden(), test_id_masked_to_24_bits(), and test_roundtrip().
brix_ssi_rrinfo_encode()
void brix_ssi_rrinfo_encode (int cmd, uint32_t id, uint32_t size, unsigned char off[8])
Definition at line 28 of file ssi_rrinfo.c.
References BRIX_SSI_ID_MAX.
Referenced by test_encode_golden(), test_id_masked_to_24_bits(), and test_roundtrip().