nginx-xrootd: src/protocols/ssi/ssi_internal.h File Reference
ssi_internal.h File Reference
#include "ssi.h"
#include "ssi_service.h"
Functions
void brix_ssi_dispatch (brix_ssi_req_t *rq, brix_ssi_process_fn process)
Function Documentation
brix_ssi_dispatch()
void brix_ssi_dispatch (brix_ssi_req_t * rq, brix_ssi_process_fn process)
Definition at line 164 of file ssi_dispatch.c.
References brix_ssi_req_t::dispatched, brix_ssi_req_t::err_code, brix_ssi_req_t::error, kXR_ServerError, brix_ssi_req_t::req, brix_ssi_req_t::req_len, brix_ssi_req_t::responded, ssi_resp_defer_accept(), and ssi_responder_init().
Referenced by brix_ssi_read(), and ssi_write_maybe_dispatch().