nginx-xrootd: src/protocols/ssi/ssi_reply_unittest.c File Reference
ssi_reply_unittest.c File Reference
#include "ssi_reply.h"
#include "ssi_rrinfo.h"
#include <stdio.h>
#include <string.h>
Macros
#define CHECK(cond)
Functions
static void getresp (const unsigned char *buf, size_t n, unsigned *pfx, unsigned *md, long *db)
static void test_full_response_layout (void)
static void test_no_metadata (void)
static void test_alert_tag (void)
int main (void)
Variables
static int g_fail
Macro Definition Documentation
CHECK
#define CHECK (cond)
Value:
    do { \
    if (!(cond)) { printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
                   g_fail++; } \
} while (0)
Definition at line 16 of file ssi_reply_unittest.c.
Function Documentation
getresp()
static void getresp (const unsigned char * buf, size_t n, unsigned * pfx, unsigned * md, long * db) static
Definition at line 23 of file ssi_reply_unittest.c.
Referenced by test_full_response_layout(), and test_no_metadata().
main()
int main (void)
Definition at line 77 of file ssi_reply_unittest.c.
References g_fail, test_alert_tag(), test_full_response_layout(), and test_no_metadata().
test_alert_tag()
static void test_alert_tag (void) static
Definition at line 67 of file ssi_reply_unittest.c.
References BRIX_SSI_ATTN_ALRT, brix_ssi_reply_build(), and CHECK.
Referenced by main().
test_full_response_layout()
static void test_full_response_layout (void) static
Definition at line 33 of file ssi_reply_unittest.c.
References BRIX_SSI_ATTN_FULL, brix_ssi_reply_build(), brix_ssi_reply_len(), CHECK, and getresp().
Referenced by main().
test_no_metadata()
static void test_no_metadata (void) static
Definition at line 54 of file ssi_reply_unittest.c.
References BRIX_SSI_ATTN_FULL, brix_ssi_reply_build(), CHECK, and getresp().
Referenced by main().
Variable Documentation
g_fail
int g_fail static
Definition at line 15 of file ssi_reply_unittest.c.
Referenced by main().