nginx-xrootd: src/protocols/ssi/ssi_rrinfo.c File Reference
ssi_rrinfo.c File Reference
#include "ssi_rrinfo.h"
Functions
void brix_ssi_rrinfo_decode (const unsigned char off[8], int *cmd, uint32_t *id, uint32_t *size)
void brix_ssi_rrinfo_encode (int cmd, uint32_t id, uint32_t size, unsigned char off[8])
void brix_ssi_attn_encode (char tag, unsigned char flags, uint16_t pfx_len, uint32_t md_len, unsigned char out[16])
Function Documentation
brix_ssi_attn_encode()
void brix_ssi_attn_encode (char tag, unsigned char flags, uint16_t pfx_len, uint32_t md_len, unsigned char out[16])
Definition at line 43 of file ssi_rrinfo.c.
References BRIX_SSI_ATTN_LEN.
Referenced by brix_ssi_reply_build(), test_attn_golden(), and test_attn_pend_and_alrt_tags().
brix_ssi_rrinfo_decode()
void brix_ssi_rrinfo_decode (const unsigned char off[8], int * cmd, uint32_t * id, uint32_t * size)
Definition at line 14 of file ssi_rrinfo.c.
Referenced by brix_ssi_query(), brix_ssi_read(), brix_ssi_write(), test_decode_golden(), test_id_masked_to_24_bits(), and test_roundtrip().
brix_ssi_rrinfo_encode()
void brix_ssi_rrinfo_encode (int cmd, uint32_t id, uint32_t size, unsigned char off[8])
Definition at line 28 of file ssi_rrinfo.c.
References BRIX_SSI_ID_MAX.
Referenced by test_encode_golden(), test_id_masked_to_24_bits(), and test_roundtrip().