nginx-xrootd: src/protocols/ssi/ssi_service_unittest.c File Reference
ssi_service_unittest.c File Reference
#include "ssi_service.h"
#include <stdio.h>
#include <string.h>
Data Structures
struct rec_t
Macros
#define CHECK(cond)
Functions
static void rec_md (brix_ssi_responder_t *r, const unsigned char *md, size_t n)
static void rec_resp (brix_ssi_responder_t *r, const unsigned char *b, size_t n, int last)
static void rec_alert (brix_ssi_responder_t *r, const unsigned char *b, size_t n)
static void rec_err (brix_ssi_responder_t *r, int code, const char *t)
static brix_ssi_responder_t make_responder (rec_t *rec)
static void test_echo_service (void)
static void test_unknown_service (void)
int main (void)
Variables
static int g_fail
Macro Definition Documentation
CHECK
#define CHECK (cond)
Value:
    do { \
    if (!(cond)) { printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
                   g_fail++; } \
} while (0)
Definition at line 15 of file ssi_service_unittest.c.
Function Documentation
main()
int main (void)
Definition at line 72 of file ssi_service_unittest.c.
References g_fail, test_echo_service(), and test_unknown_service().
make_responder()
static brix_ssi_responder_t make_responder (rec_t * rec) static
Definition at line 37 of file ssi_service_unittest.c.
References rec_alert(), rec_err(), rec_md(), and rec_resp().
Referenced by test_echo_service().
rec_alert()
static void rec_alert (brix_ssi_responder_t * r, const unsigned char * b, size_t n) static
Definition at line 31 of file ssi_service_unittest.c.
Referenced by make_responder().
rec_err()
static void rec_err (brix_ssi_responder_t * r, int code, const char * t) static
Definition at line 33 of file ssi_service_unittest.c.
References code, rec_t::err_code, rec_t::err_set, and rec_t::err_text.
Referenced by make_responder().
rec_md()
static void rec_md (brix_ssi_responder_t * r, const unsigned char * md, size_t n) static
Definition at line 26 of file ssi_service_unittest.c.
References rec_t::md, rec_t::md_len, and rec_t::md_set.
Referenced by make_responder().
rec_resp()
static void rec_resp (brix_ssi_responder_t * r, const unsigned char * b, size_t n, int last) static
Definition at line 28 of file ssi_service_unittest.c.
References rec_t::data, rec_t::data_len, rec_t::last, and rec_t::resp_set.
Referenced by make_responder().
test_echo_service()
static void test_echo_service (void) static
Definition at line 50 of file ssi_service_unittest.c.
References brix_ssi_service_lookup(), CHECK, rec_t::data, rec_t::data_len, fn, rec_t::last, make_responder(), and rec_t::resp_set.
Referenced by main().
test_unknown_service()
static void test_unknown_service (void) static
Definition at line 66 of file ssi_service_unittest.c.
References brix_ssi_service_lookup(), and CHECK.
Referenced by main().
Variable Documentation
g_fail
int g_fail static
Definition at line 14 of file ssi_service_unittest.c.
Referenced by main().