nginx-xrootd: src/protocols/ssi/ssi_dispatch.c File Reference
ssi_dispatch.c File Reference
#include "core/ngx_brix_module.h"
#include "ssi.h"
#include "ssi_internal.h"
#include "ssi_rrinfo.h"
#include "ssi_reply.h"
#include "ssi_service.h"
#include "provider.h"
#include "session.h"
#include "registry.h"
#include "deliver.h"
#include "protocols/ssi/svc_cta/cta_service.h"
#include "protocols/root/connection/fd_table.h"
#include "protocols/root/response/response.h"
#include "core/compat/error_mapping.h"
#include "protocols/root/protocol/opcodes.h"
#include "protocols/root/protocol/wire_core_requests.h"
#include <fcntl.h>
#include <string.h>
#include <unistd.h>
Data Structures
struct ssi_resp_state_t
struct ssi_defer_t
Functions
static void ssi_resp_set_metadata (brix_ssi_responder_t *r, const unsigned char *md, size_t len)
static void ssi_resp_set_response (brix_ssi_responder_t *r, const unsigned char *buf, size_t len, int last)
static void ssi_resp_alert (brix_ssi_responder_t *r, const unsigned char *buf, size_t len)
static void ssi_resp_error (brix_ssi_responder_t *r, int code, const char *text)
static int ssi_resp_defer_accept (brix_ssi_responder_t *r)
static int ssi_resp_defer_refuse (brix_ssi_responder_t *r)
static void ** ssi_resp_svc_slot (brix_ssi_responder_t *r)
static void ssi_responder_init (brix_ssi_responder_t *r, ssi_resp_state_t *st, int(*defer)(brix_ssi_responder_t *))
void brix_ssi_dispatch (brix_ssi_req_t *rq, brix_ssi_process_fn process)
static void ssi_complete_deferred (brix_ctx_t *ctx, ngx_connection_t *c, brix_ssi_session_t *sess, brix_ssi_req_t *rq)
static void ssi_defer_cancel (void *p)
static void ssi_defer_timer_handler (ngx_event_t *ev)
static ngx_int_t ssi_defer_arm (brix_ctx_t *ctx, ngx_connection_t *c, brix_ssi_session_t *sess, brix_ssi_req_t *rq)
void brix_ssi_handle_cleanup (void *ssi_session)
static int ssi_write_accumulate (brix_ctx_t *ctx, ngx_connection_t *c, brix_ssi_session_t *sess, brix_ssi_req_t *rq, size_t n, ngx_int_t *out_rc)
static int ssi_write_maybe_dispatch (brix_ctx_t *ctx, ngx_connection_t *c, brix_ssi_session_t *sess, brix_ssi_req_t *rq, ngx_int_t *out_rc)
ngx_int_t brix_ssi_write (brix_ctx_t *ctx, ngx_connection_t *c, int idx, const unsigned char off8[8])
Function Documentation
brix_ssi_dispatch()
void brix_ssi_dispatch (brix_ssi_req_t * rq, brix_ssi_process_fn process)
Definition at line 164 of file ssi_dispatch.c.
References brix_ssi_req_t::dispatched, brix_ssi_req_t::err_code, brix_ssi_req_t::error, kXR_ServerError, brix_ssi_req_t::req, brix_ssi_req_t::req_len, brix_ssi_req_t::responded, ssi_resp_defer_accept(), and ssi_responder_init().
Referenced by brix_ssi_read(), and ssi_write_maybe_dispatch().
brix_ssi_handle_cleanup()
void brix_ssi_handle_cleanup (void * ssi_session)
Definition at line 290 of file ssi_dispatch.c.
References BRIX_SSI_MAX_INFLIGHT, brix_ssi_registry_remove(), brix_ssi_session_t::conn_id, brix_ssi_req_t::defer_ctx, brix_ssi_req_t::in_use, brix_ssi_session_t::rr, and ssi_defer_cancel().
Referenced by fhandle_reset_slot().
brix_ssi_write()
ngx_int_t brix_ssi_write (brix_ctx_t * ctx, ngx_connection_t * c, int idx, const unsigned char off8[8])
Definition at line 404 of file ssi_dispatch.c.
References brix_send_error(), brix_send_ok(), BRIX_SSI_CMD_CAN, brix_ssi_rrinfo_decode(), brix_ssi_session_drop(), brix_ssi_session_req(), c, brix_ctx_recv_t::cur_dlen, brix_ssi_req_t::dispatched, brix_ctx_t::files, brix_ssi_req_t::have_size, kXR_FileLocked, kXR_Overloaded, brix_ctx_t::recv, brix_ssi_req_t::req_expected, brix_file_t::ssi, ssi_write_accumulate(), and ssi_write_maybe_dispatch().
Referenced by brix_write_route_special().
ssi_complete_deferred()
static void ssi_complete_deferred (brix_ctx_t * ctx, ngx_connection_t * c, brix_ssi_session_t * sess, brix_ssi_req_t * rq) static
Definition at line 183 of file ssi_dispatch.c.
References c, brix_ssi_req_t::err_code, brix_ssi_req_t::error, kXR_ServerError, brix_ssi_provider_t::process, brix_ssi_session_t::provider, brix_ssi_req_t::req, brix_ssi_req_t::req_len, brix_ssi_req_t::responded, ssi_resp_defer_refuse(), and ssi_responder_init().
Referenced by ssi_defer_timer_handler().
ssi_defer_arm()
static ngx_int_t ssi_defer_arm (brix_ctx_t * ctx, ngx_connection_t * c, brix_ssi_session_t * sess, brix_ssi_req_t * rq) static
Definition at line 262 of file ssi_dispatch.c.
References c, ssi_defer_t::c, brix_ssi_session_t::conn_id, ssi_defer_t::ctx, brix_ssi_req_t::defer_ctx, brix_ssi_session_t::generation, ssi_defer_t::generation, ssi_defer_t::req_id, brix_ssi_req_t::req_id, ssi_defer_t::session_key, ssi_defer_timer_handler(), and ssi_defer_t::timer.
Referenced by ssi_write_maybe_dispatch().
ssi_defer_cancel()
static void ssi_defer_cancel (void * p) static
Definition at line 218 of file ssi_dispatch.c.
References ssi_defer_t::timer.
Referenced by brix_ssi_handle_cleanup().
ssi_defer_timer_handler()
static void ssi_defer_timer_handler (ngx_event_t * ev) static
Definition at line 232 of file ssi_dispatch.c.
References brix_ssi_deliver(), brix_ssi_registry_find(), brix_ssi_session_req(), ssi_defer_t::c, ssi_defer_t::ctx, brix_ssi_req_t::defer_ctx, brix_ssi_req_t::error, ssi_defer_t::generation, ssi_defer_t::req_id, brix_ssi_req_t::responded, s, ssi_defer_t::session_key, ssi_complete_deferred(), SSI_DLV_ERROR, SSI_DLV_PEND, SSI_DLV_RESPONSE, and brix_ssi_req_t::streaming.
Referenced by ssi_defer_arm().
ssi_resp_alert()
static void ssi_resp_alert (brix_ssi_responder_t * r, const unsigned char * buf, size_t len) static
Definition at line 98 of file ssi_dispatch.c.
References brix_ssi_deliver_alert(), ssi_resp_state_t::c, ssi_resp_state_t::ctx, ssi_resp_state_t::rq, and brix_ssi_req_t::waiting.
Referenced by ssi_responder_init().
ssi_resp_defer_accept()
static int ssi_resp_defer_accept (brix_ssi_responder_t * r) static
Definition at line 128 of file ssi_dispatch.c.
Referenced by brix_ssi_dispatch().
ssi_resp_defer_refuse()
static int ssi_resp_defer_refuse (brix_ssi_responder_t * r) static
Definition at line 136 of file ssi_dispatch.c.
Referenced by ssi_complete_deferred().
ssi_resp_error()
static void ssi_resp_error (brix_ssi_responder_t * r, int code, const char * text) static
Definition at line 111 of file ssi_dispatch.c.
References brix_kxr_from_errno(), code, brix_ssi_req_t::err_code, brix_ssi_req_t::err_text, brix_ssi_req_t::error, kXR_ServerError, and brix_ssi_req_t::responded.
Referenced by ssi_responder_init().
ssi_resp_set_metadata()
static void ssi_resp_set_metadata (brix_ssi_responder_t * r, const unsigned char * md, size_t len) static
Definition at line 57 of file ssi_dispatch.c.
References BRIX_SSI_META_MAX, brix_ssi_req_t::meta, brix_ssi_req_t::meta_len, ngx_memcpy, and brix_ssi_req_t::pool.
Referenced by ssi_responder_init().
ssi_resp_set_response()
static void ssi_resp_set_response (brix_ssi_responder_t * r, const unsigned char * buf, size_t len, int last) static
Definition at line 76 of file ssi_dispatch.c.
References BRIX_SSI_RESP_MAX, brix_ssi_respbuf_append(), brix_ssi_req_t::err_code, brix_ssi_req_t::error, kXR_NoMemory, brix_ssi_req_t::resp, brix_ssi_req_t::responded, brix_ssi_req_t::response_max, and brix_ssi_req_t::streaming.
Referenced by ssi_responder_init().
ssi_resp_svc_slot()
static void ** ssi_resp_svc_slot (brix_ssi_responder_t * r) static
Definition at line 143 of file ssi_dispatch.c.
Referenced by ssi_responder_init().
ssi_responder_init()
static void ssi_responder_init (brix_ssi_responder_t * r, ssi_resp_state_t * st, int(*)(brix_ssi_responder_t *) defer) static
Definition at line 149 of file ssi_dispatch.c.
References ssi_resp_alert(), ssi_resp_error(), ssi_resp_set_metadata(), ssi_resp_set_response(), and ssi_resp_svc_slot().
Referenced by brix_ssi_dispatch(), and ssi_complete_deferred().
ssi_write_accumulate()
static int ssi_write_accumulate (brix_ctx_t * ctx, ngx_connection_t * c, brix_ssi_session_t * sess, brix_ssi_req_t * rq, size_t n, ngx_int_t * out_rc) static
Definition at line 326 of file ssi_dispatch.c.
References brix_send_error(), BRIX_SSI_REQ_MAX, c, kXR_ArgTooLong, kXR_NoMemory, ngx_memcpy, brix_ctx_recv_t::payload, brix_ctx_t::recv, brix_ssi_req_t::req, brix_ssi_req_t::req_len, and brix_ssi_session_t::request_max.
Referenced by brix_ssi_write().
ssi_write_maybe_dispatch()
static int ssi_write_maybe_dispatch (brix_ctx_t * ctx, ngx_connection_t * c, brix_ssi_session_t * sess, brix_ssi_req_t * rq, ngx_int_t * out_rc) static
Definition at line 379 of file ssi_dispatch.c.
References brix_send_error(), brix_send_waitresp(), BRIX_SRV_METRIC_INC, brix_ssi_dispatch(), c, brix_ctx_recv_t::cur_streamid, brix_ssi_req_t::defer_streamid, brix_ssi_req_t::deferred, kXR_NoMemory, ngx_memcpy, brix_ssi_provider_t::process, brix_ssi_session_t::provider, brix_ctx_t::recv, brix_ssi_req_t::req_expected, brix_ssi_req_t::req_len, brix_ssi_req_t::responded, ssi_defer_arm(), and brix_ssi_req_t::waiting.
Referenced by brix_ssi_write().