nginx-xrootd: src/auth/sss/sss_internal.h File Reference
sss_internal.h File Reference
#include "core/ngx_brix_module.h"
#include "protocols/root/protocol/sss.h"
Data Structures
struct brix_sss_identity_t
Functions
uint32_t brix_sss_read_be32 (const u_char *p)
uint64_t brix_sss_read_be64 (const u_char *p)
void brix_sss_write_be32 (u_char *p, uint32_t v)
uint32_t brix_sss_crc32 (const u_char *p, size_t len)
ngx_int_t brix_sss_bf32_crypt (int encrypt, const u_char *key, size_t key_len, const u_char *src, size_t src_len, u_char *dst, size_t dst_len, size_t *out_len)
const brix_sss_key_t * brix_sss_find_key (ngx_stream_brix_srv_conf_t *conf, int64_t id)
const brix_sss_key_t * brix_sss_find_key_arr (ngx_array_t *keys, int64_t id)
ngx_int_t brix_sss_verify_blob (ngx_array_t *keys, time_t lifetime, const u_char *blob, size_t blob_len, brix_sss_identity_t *id_out, const brix_sss_key_t **key_out, char *err, size_t errsz)
ngx_int_t brix_sss_parse_identity (const u_char *data, size_t len, brix_sss_identity_t *id)
ngx_int_t brix_sss_auth_failed (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_sss_send_authmore (brix_ctx_t *ctx, ngx_connection_t *c, const brix_sss_key_t *key, const u_char *hdr, size_t hdr_len)
Function Documentation
brix_sss_auth_failed()
ngx_int_t brix_sss_auth_failed (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 127 of file auth_identity_challenge.c.
References BRIX_OP_AUTH, BRIX_RETURN_ERR, c, and kXR_NotAuthorized.
Referenced by brix_handle_sss_auth().
brix_sss_bf32_crypt()
ngx_int_t brix_sss_bf32_crypt (int encrypt, const u_char * key, size_t key_len, const u_char * src, size_t src_len, u_char * dst, size_t dst_len, size_t * out_len)
Definition at line 78 of file auth_crypto_helpers.c.
References brix_sss_bf_crypt(), and key.
Referenced by brix_handle_sss_auth(), brix_sss_send_authmore(), and brix_sss_verify_blob().
brix_sss_crc32()
uint32_t brix_sss_crc32 (const u_char * p, size_t len)
Definition at line 67 of file auth_crypto_helpers.c.
References brix_crc32_ieee().
Referenced by brix_handle_sss_auth(), brix_sss_send_authmore(), and brix_sss_verify_blob().
brix_sss_find_key()
const brix_sss_key_t * brix_sss_find_key (ngx_stream_brix_srv_conf_t * conf, int64_t id)
Definition at line 110 of file auth_crypto_helpers.c.
References brix_sss_find_key_arr(), and ngx_stream_brix_srv_conf_t::sss_keys.
Referenced by brix_handle_sss_auth().
brix_sss_find_key_arr()
const brix_sss_key_t * brix_sss_find_key_arr (ngx_array_t * keys, int64_t id)
Definition at line 90 of file auth_crypto_helpers.c.
Referenced by brix_sss_find_key(), and brix_sss_verify_blob().
brix_sss_parse_identity()
ngx_int_t brix_sss_parse_identity (const u_char * data, size_t len, brix_sss_identity_t * id)
Definition at line 56 of file auth_identity_challenge.c.
References brix_sss_copy_packed_string(), BRIX_SSS_TYPE_GRPS, BRIX_SSS_TYPE_HOST, BRIX_SSS_TYPE_NAME, BRIX_SSS_TYPE_RAND, brix_sss_identity_t::grps, brix_sss_identity_t::host, brix_sss_identity_t::ip, and brix_sss_identity_t::name.
Referenced by brix_handle_sss_auth(), and brix_sss_verify_blob().
brix_sss_read_be32()
uint32_t brix_sss_read_be32 (const u_char * p)
Definition at line 34 of file auth_crypto_helpers.c.
Referenced by brix_handle_sss_auth(), brix_sss_read_be64(), and brix_sss_verify_blob().
brix_sss_read_be64()
uint64_t brix_sss_read_be64 (const u_char * p)
Definition at line 43 of file auth_crypto_helpers.c.
References brix_sss_read_be32().
Referenced by brix_handle_sss_auth(), and brix_sss_verify_blob().
brix_sss_send_authmore()
ngx_int_t brix_sss_send_authmore (brix_ctx_t * ctx, ngx_connection_t * c, const brix_sss_key_t * key, const u_char * hdr, size_t hdr_len)
Definition at line 134 of file auth_identity_challenge.c.
References brix_build_resp_hdr(), BRIX_PALLOC_OR_RETURN, brix_queue_response(), BRIX_SSS_BASE_TIME, brix_sss_bf32_crypt(), brix_sss_crc32(), BRIX_SSS_DATA_HDR_LEN, BRIX_SSS_OPT_USEDATA, BRIX_SSS_TYPE_LGID, brix_sss_write_be32(), c, brix_ctx_recv_t::cur_streamid, key, kXR_authmore, brix_ctx_t::recv, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_handle_sss_auth().
brix_sss_verify_blob()
ngx_int_t brix_sss_verify_blob (ngx_array_t * keys, time_t lifetime, const u_char * blob, size_t blob_len, brix_sss_identity_t * id_out, const brix_sss_key_t ** key_out, char * err, size_t errsz)
Definition at line 119 of file auth_crypto_helpers.c.
References BRIX_SSS_BASE_TIME, brix_sss_bf32_crypt(), brix_sss_crc32(), BRIX_SSS_DATA_HDR_LEN, BRIX_SSS_ENC_BF32, brix_sss_find_key_arr(), BRIX_SSS_HDR_LEN, BRIX_SSS_NAME_MAX, BRIX_SSS_OPT_SNDLID, brix_sss_parse_identity(), brix_sss_read_be32(), brix_sss_read_be64(), and key.
Referenced by brix_cms_srv_verify_xauth().
brix_sss_write_be32()
void brix_sss_write_be32 (u_char * p, uint32_t v)
Definition at line 53 of file auth_crypto_helpers.c.
Referenced by brix_sss_send_authmore().