nginx-xrootd: src/auth/sss/sss_keytab_kernel.c File Reference
sss_keytab_kernel.c File Reference
#include "sss_keytab_kernel.h"
#include "core/compat/hex.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
Functions
static int sss_copy_field (char *dst, size_t dst_len, const char *src)
static int sss_decode_hex (const char *hex, uint8_t *out, size_t *out_len)
static int sss_parse_i64 (const char *text, int64_t *out)
static void sss_entry_set_defaults (sss_keytab_entry_t *out)
static int sss_check_version_tag (const char *field)
static int sss_apply_field (sss_keytab_entry_t *out, char key, const char *v)
static int sss_parse_fields (char **save, sss_keytab_entry_t *out)
int sss_keytab_parse_line (char *line, sss_keytab_entry_t *out, int64_t now)
int sss_keytab_mode_ok (const char *path, mode_t mode, int allow_dotgrp)
Function Documentation
sss_apply_field()
static int sss_apply_field (sss_keytab_entry_t * out, char key, const char * v) static
Definition at line 114 of file sss_keytab_kernel.c.
References sss_keytab_entry_t::exp, sss_keytab_entry_t::group, sss_keytab_entry_t::id, sss_keytab_entry_t::key, key, sss_keytab_entry_t::key_len, sss_keytab_entry_t::name, sss_copy_field(), sss_decode_hex(), sss_parse_i64(), and sss_keytab_entry_t::user.
Referenced by sss_parse_fields().
sss_check_version_tag()
static int sss_check_version_tag (const char * field) static
Definition at line 93 of file sss_keytab_kernel.c.
Referenced by sss_keytab_parse_line().
sss_copy_field()
static int sss_copy_field (char * dst, size_t dst_len, const char * src) static
Definition at line 20 of file sss_keytab_kernel.c.
Referenced by sss_apply_field().
sss_decode_hex()
static int sss_decode_hex (const char * hex, uint8_t * out, size_t * out_len) static
Definition at line 32 of file sss_keytab_kernel.c.
References brix_hex_from_char(), hex(), and SSS_K_KEY_MAX.
Referenced by sss_apply_field().
sss_entry_set_defaults()
static void sss_entry_set_defaults (sss_keytab_entry_t * out) static
Definition at line 76 of file sss_keytab_kernel.c.
References sss_keytab_entry_t::group, sss_keytab_entry_t::id, sss_keytab_entry_t::name, and sss_keytab_entry_t::user.
Referenced by sss_keytab_parse_line().
sss_keytab_mode_ok()
int sss_keytab_mode_ok (const char * path, mode_t mode, int allow_dotgrp)
Definition at line 190 of file sss_keytab_kernel.c.
Referenced by brix_sss_keytab_read(), and brix_sss_load_keytab().
sss_keytab_parse_line()
int sss_keytab_parse_line (char * line, sss_keytab_entry_t * out, int64_t now)
Definition at line 163 of file sss_keytab_kernel.c.
References sss_keytab_entry_t::exp, sss_keytab_entry_t::id, sss_keytab_entry_t::key_len, sss_check_version_tag(), sss_entry_set_defaults(), and sss_parse_fields().
Referenced by brix_sss_parse_key_line(), cache_origin_load_sss_key(), and parse_line().
sss_parse_fields()
static int sss_parse_fields (char ** save, sss_keytab_entry_t * out) static
Definition at line 144 of file sss_keytab_kernel.c.
References sss_apply_field().
Referenced by sss_keytab_parse_line().
sss_parse_i64()
static int sss_parse_i64 (const char * text, int64_t * out) static
Definition at line 53 of file sss_keytab_kernel.c.
Referenced by sss_apply_field().