nginx-xrootd: src/core/compat/sss_bf.c File Reference
sss_bf.c File Reference
#include "sss_bf.h"
#include "crc32_ieee.h"
#include "protocols/root/protocol/sss.h"
#include <limits.h>
#include <string.h>
#include <openssl/evp.h>
#include <openssl/opensslv.h>
Functions
static void sss_load_legacy_provider (void)
int brix_sss_bf_crypt (int encrypt, const uint8_t *key, size_t key_len, const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_max, size_t *out_len)
int brix_sss_build_credential (const uint8_t *key, size_t key_len, uint64_t key_id, const char *username, const uint8_t nonce32[32], uint32_t gen_time, uint8_t *out, size_t out_max, size_t *out_len)
Function Documentation
brix_sss_bf_crypt()
int brix_sss_bf_crypt (int encrypt, const uint8_t * key, size_t key_len, const uint8_t * src, size_t src_len, uint8_t * dst, size_t dst_max, size_t * out_len)
Definition at line 42 of file sss_bf.c.
References key, and sss_load_legacy_provider().
Referenced by brix_sss_bf32_crypt(), brix_sss_bf32_encrypt(), and brix_sss_build_credential().
brix_sss_build_credential()
int brix_sss_build_credential (const uint8_t * key, size_t key_len, uint64_t key_id, const char * username, const uint8_t nonce32[32], uint32_t gen_time, uint8_t * out, size_t out_max, size_t * out_len)
Definition at line 89 of file sss_bf.c.
References brix_crc32_ieee(), brix_sss_bf_crypt(), BRIX_SSS_DATA_HDR_LEN, BRIX_SSS_ENC_BF32, BRIX_SSS_HDR_LEN, BRIX_SSS_OPT_USEDATA, BRIX_SSS_TYPE_NAME, and key.
Referenced by brix_sss_build_proxy_credential(), and sss_first().
sss_load_legacy_provider()
static void sss_load_legacy_provider (void) static
Definition at line 25 of file sss_bf.c.
Referenced by brix_sss_bf_crypt().