nginx-xrootd: src/auth/sss/sss_keytab_kernel.h File Reference
sss_keytab_kernel.h File Reference
#include <stdint.h>
#include <stddef.h>
#include <sys/types.h>
Data Structures
struct sss_keytab_entry_t
Macros
#define SSS_K_KEY_MAX 128
#define SSS_K_USER_MAX 128
#define SSS_K_GROUP_MAX 64
#define SSS_K_NAME_MAX 192
Functions
int sss_keytab_parse_line (char *line, sss_keytab_entry_t *out, int64_t now)
int sss_keytab_mode_ok (const char *path, mode_t mode, int allow_dotgrp)
Macro Definition Documentation
SSS_K_GROUP_MAX
#define SSS_K_GROUP_MAX 64
Definition at line 38 of file sss_keytab_kernel.h.
SSS_K_KEY_MAX
#define SSS_K_KEY_MAX 128
Definition at line 36 of file sss_keytab_kernel.h.
SSS_K_NAME_MAX
#define SSS_K_NAME_MAX 192
Definition at line 39 of file sss_keytab_kernel.h.
SSS_K_USER_MAX
#define SSS_K_USER_MAX 128
Definition at line 37 of file sss_keytab_kernel.h.
Function Documentation
sss_keytab_mode_ok()
int sss_keytab_mode_ok (const char * path, mode_t mode, int allow_dotgrp)
Definition at line 190 of file sss_keytab_kernel.c.
Referenced by brix_sss_keytab_read(), and brix_sss_load_keytab().
sss_keytab_parse_line()
int sss_keytab_parse_line (char * line, sss_keytab_entry_t * out, int64_t now)
Definition at line 163 of file sss_keytab_kernel.c.
References sss_keytab_entry_t::exp, sss_keytab_entry_t::id, sss_keytab_entry_t::key_len, sss_check_version_tag(), sss_entry_set_defaults(), and sss_parse_fields().
Referenced by brix_sss_parse_key_line(), cache_origin_load_sss_key(), and parse_line().