nginx-xrootd: client/lib/auth/sss/sss_keytab.c File Reference
sss_keytab.c File Reference
#include "sss_keytab.h"
#include "core/compat/crc32_ieee.h"
#include "core/compat/sss_bf.h"
#include "core/compat/hex.h"
#include "auth/sss/sss_keytab_kernel.h"
#include "core/config/envalias.h"
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <pwd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include <openssl/evp.h>
Functions
uint32_t brix_sss_crc32 (const uint8_t *p, size_t len)
int brix_sss_bf32_encrypt (const uint8_t *key, size_t key_len, const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_max, size_t *out_len, brix_status *st)
void brix_sss_keytab_default (char *out, size_t outsz)
static int parse_line (char *line, brix_sss_key *k)
int brix_sss_keytab_read (const char *path, brix_sss_key *keys, int max, int *n, brix_status *st)
int brix_sss_keytab_write (const char *path, const brix_sss_key *keys, int n, brix_status *st)
Function Documentation
brix_sss_bf32_encrypt()
int brix_sss_bf32_encrypt (const uint8_t * key, size_t key_len, const uint8_t * src, size_t src_len, uint8_t * dst, size_t dst_max, size_t * out_len, brix_status * st)
Definition at line 44 of file sss_keytab.c.
References brix_sss_bf_crypt(), brix_status_set(), key, XRDC_EPROTO, and XRDC_EUSAGE.
brix_sss_crc32()
uint32_t brix_sss_crc32 (const uint8_t * p, size_t len)
Definition at line 36 of file sss_keytab.c.
References brix_crc32_ieee().
brix_sss_keytab_default()
void brix_sss_keytab_default (char * out, size_t outsz)
Definition at line 65 of file sss_keytab.c.
References brix_env_resolve().
Referenced by main(), resolve_keytab_path(), and sss_load_first_key().
brix_sss_keytab_read()
int brix_sss_keytab_read (const char * path, brix_sss_key * keys, int max, int * n, brix_status * st)
Definition at line 129 of file sss_keytab.c.
References brix_status_set(), close(), fstat(), open(), parse_line(), sss_keytab_mode_ok(), stat(), and XRDC_EAUTH.
Referenced by cmd_add(), cmd_del(), cmd_list(), keytab_probe(), load_or_empty(), sss_first(), and sss_load_first_key().
brix_sss_keytab_write()
int brix_sss_keytab_write (const char * path, const brix_sss_key * keys, int n, brix_status * st)
Definition at line 183 of file sss_keytab.c.
References brix_hex_encode(), brix_status_set(), close(), hex(), key, name, open(), XRDC_EAUTH, and XRDC_SSS_KEY_MAX.
Referenced by cmd_add(), and cmd_del().
parse_line()
static int parse_line (char * line, brix_sss_key * k) static
Definition at line 107 of file sss_keytab.c.
References brix_sss_key::exp, sss_keytab_entry_t::exp, brix_sss_key::group, sss_keytab_entry_t::group, brix_sss_key::id, sss_keytab_entry_t::id, brix_sss_key::key, sss_keytab_entry_t::key, brix_sss_key::key_len, sss_keytab_entry_t::key_len, brix_sss_key::name, sss_keytab_entry_t::name, sss_keytab_parse_line(), brix_sss_key::user, and sss_keytab_entry_t::user.
Referenced by brix_sss_keytab_read().