nginx-xrootd: src/fs/xfer/stage_request_registry.c File Reference
stage_request_registry.c File Reference
#include "stage_request_registry.h"
#include "core/compat/crc32c.h"
#include "fs/backend/sd.h"
#include <errno.h>
#include <fcntl.h>
#include <pthread.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct srq_hdr_t
struct srq_rec_t
struct brix_stage_registry_t
Macros
#define SRQ_MAGIC 0x53525131u /* "SRQ1" */
#define SRQ_VERSION 1u
#define SRQ_REQID_LEN 40 /* on-disk width ("<seq>.<pid>@<host>") */
#define SRQ_LFN_LEN 3072
#define SRQ_DN_LEN 256
#define SRQ_USER_LEN 256
#define SRQ_REC_SIZE 4608u /* fixed slot size (header == record) */
#define SRQ_REC_OFF(n) (((int64_t) (n) + 1) * (int64_t) SRQ_REC_SIZE)
Typedefs
typedef char srq_hdr_size_check[(sizeof(srq_hdr_t)==4608u) ? 1 :-1]
typedef char srq_rec_size_check[(sizeof(srq_rec_t)==4608u) ? 1 :-1]
Enumerations
enum {
SRQ_ST_FREE = 0 , SRQ_ST_QUEUED = 1 , SRQ_ST_STAGING = 2 , SRQ_ST_ONLINE = 3 ,
SRQ_ST_FAILED = 4 , SRQ_ST_CANCELLED = 5
}
enum srq_lock_t { SRQ_LK_SHARE , SRQ_LK_EXCL }
Functions
static uint32_t srq_rec_compute_crc (const srq_rec_t *rec)
static uint32_t srq_hdr_compute_crc (const srq_hdr_t *hdr)
static void srq_rec_stamp_crc (srq_rec_t *rec)
static int srq_rec_valid (const srq_rec_t *rec, int64_t expect_off)
static void srq_hdr_init_blank (srq_hdr_t *hdr, time_t now)
static ngx_int_t srq_pread_all (int fd, void *buf, size_t len, off_t off, ngx_log_t *log)
static ngx_int_t srq_pwrite_all (int fd, const void *buf, size_t len, off_t off, ngx_log_t *log)
static ngx_int_t srq_hdr_read (brix_stage_registry_t *reg, srq_hdr_t *hdr, ngx_log_t *log)
static ngx_int_t srq_hdr_write (brix_stage_registry_t *reg, srq_hdr_t *hdr, ngx_log_t *log)
static ngx_int_t srq_rec_read (brix_stage_registry_t *reg, int64_t off, srq_rec_t *rec, ngx_log_t *log)
static ngx_int_t srq_rec_write (brix_stage_registry_t *reg, int64_t off, srq_rec_t *rec, ngx_log_t *log)
static int64_t srq_file_size (brix_stage_registry_t *reg)
static ngx_int_t srq_lock (brix_stage_registry_t *reg, srq_lock_t mode)
static void srq_unlock (brix_stage_registry_t *reg)
static void srq_reqid_format (const char *host, uint64_t seq, char *buf, size_t buf_sz)
static brix_stage_req_status_t srq_status_public (uint8_t on_disk)
static uint8_t srq_status_on_disk (brix_stage_req_status_t pub)
static void srq_rec_to_view (const srq_rec_t *rec, brix_stage_request_t *out)
static int64_t srq_offset_by_reqid (brix_stage_registry_t *reg, const char *reqid, ngx_log_t *log)
static int64_t srq_alloc_slot (brix_stage_registry_t *reg, ngx_log_t *log)
brix_stage_registry_t * brix_stage_registry_singleton (void)
ngx_int_t brix_stage_registry_init (const char *journal_dir, ngx_log_t *log)
ngx_int_t brix_stage_request_reqid_generate (brix_stage_registry_t *reg, char *reqid_out, size_t reqid_out_sz, ngx_log_t *log)
ngx_int_t brix_stage_request_add (brix_stage_registry_t *reg, const brix_stage_request_view_t *view, char *reqid_out, size_t reqid_out_sz, ngx_log_t *log)
ngx_int_t brix_stage_request_set_status (brix_stage_registry_t *reg, const char *reqid, brix_stage_req_status_t status, ngx_log_t *log)
ngx_int_t brix_stage_request_delete (brix_stage_registry_t *reg, const char *reqid, ngx_log_t *log)
ngx_int_t brix_stage_request_cancel (brix_stage_registry_t *reg, const char *reqid, ngx_log_t *log)
ngx_int_t brix_stage_request_get (brix_stage_registry_t *reg, const char *reqid, brix_stage_request_t *out, ngx_log_t *log)
ngx_int_t brix_stage_request_find_by_path (brix_stage_registry_t *reg, const char *lfn, char *reqid_out, size_t reqid_out_sz, ngx_log_t *log)
ngx_int_t brix_stage_request_owner_check (brix_stage_registry_t *reg, const char *reqid, const char *requester_dn, ngx_log_t *log)
ngx_int_t brix_stage_request_list_active (brix_stage_registry_t *reg, ngx_uint_t *cursor, brix_stage_request_t *out, ngx_log_t *log)
ngx_int_t brix_stage_request_list_files (brix_stage_registry_t *reg, const char *reqid, ngx_uint_t *cursor, brix_stage_request_t *out, ngx_log_t *log)
ngx_int_t brix_stage_request_pin_release (brix_stage_registry_t *reg, const char *abs_path, ngx_log_t *log)
ngx_uint_t brix_stage_request_reap_expired (brix_stage_registry_t *reg, time_t now, ngx_log_t *log)
Variables
static brix_stage_registry_t srq_singleton
static int srq_singleton_used
static pthread_mutex_t srq_file_mtx = PTHREAD_MUTEX_INITIALIZER
Macro Definition Documentation
SRQ_DN_LEN
#define SRQ_DN_LEN 256
Definition at line 47 of file stage_request_registry.c.
SRQ_LFN_LEN
#define SRQ_LFN_LEN 3072
Definition at line 46 of file stage_request_registry.c.
SRQ_MAGIC
#define SRQ_MAGIC 0x53525131u /* "SRQ1" */
Definition at line 42 of file stage_request_registry.c.
SRQ_REC_OFF
#define SRQ_REC_OFF (n) (((int64_t) (n) + 1) * (int64_t) SRQ_REC_SIZE)
Definition at line 51 of file stage_request_registry.c.
SRQ_REC_SIZE
#define SRQ_REC_SIZE 4608u /* fixed slot size (header == record) */
Definition at line 50 of file stage_request_registry.c.
SRQ_REQID_LEN
#define SRQ_REQID_LEN 40 /* on-disk width ("<seq>.<pid>@<host>") */
Definition at line 45 of file stage_request_registry.c.
SRQ_USER_LEN
#define SRQ_USER_LEN 256
Definition at line 48 of file stage_request_registry.c.
SRQ_VERSION
#define SRQ_VERSION 1u
Definition at line 43 of file stage_request_registry.c.
Typedef Documentation
srq_hdr_size_check
typedef char srq_hdr_size_check[(sizeof(srq_hdr_t)== 4608u) ? 1 :-1]
Definition at line 108 of file stage_request_registry.c.
srq_rec_size_check
typedef char srq_rec_size_check[(sizeof(srq_rec_t)== 4608u) ? 1 :-1]
Definition at line 109 of file stage_request_registry.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SRQ_ST_FREE
SRQ_ST_QUEUED
SRQ_ST_STAGING
SRQ_ST_ONLINE
SRQ_ST_FAILED
SRQ_ST_CANCELLED
Definition at line 55 of file stage_request_registry.c.
srq_lock_t
enum srq_lock_t
Enumerator
SRQ_LK_SHARE
SRQ_LK_EXCL
Definition at line 131 of file stage_request_registry.c.
Function Documentation
brix_stage_registry_init()
ngx_int_t brix_stage_registry_init (const char * journal_dir, ngx_log_t * log)
Definition at line 466 of file stage_request_registry.c.
References close(), fstat(), log, ngx_memcpy, open(), srq_hdr_init_blank(), srq_hdr_write(), srq_singleton, srq_singleton_used, and stat().
Referenced by ngx_stream_brix_init_process().
brix_stage_registry_singleton()
brix_stage_registry_t * brix_stage_registry_singleton (void)
Definition at line 460 of file stage_request_registry.c.
References srq_singleton, and srq_singleton_used.
Referenced by brix_handle_open(), brix_handle_prepare(), brix_prepare_handle_cancel(), brix_query_prep_status(), stage_waiter_deliver_one(), and tape_queue().
brix_stage_request_add()
ngx_int_t brix_stage_request_add (brix_stage_registry_t * reg, const brix_stage_request_view_t * view, char * reqid_out, size_t reqid_out_sz, ngx_log_t * log)
Definition at line 563 of file stage_request_registry.c.
References srq_rec_t::cs_type, brix_stage_request_view_t::cs_type, srq_rec_t::cs_value, brix_stage_request_view_t::cs_value, srq_rec_t::lfn, brix_stage_request_view_t::lfn, srq_rec_t::lfn_url_off, log, srq_rec_t::opaque_off, srq_rec_t::reqid, srq_rec_t::requester_dn, brix_stage_request_view_t::requester_dn, srq_rec_t::self, srq_hdr_t::seq, srq_alloc_slot(), srq_hdr_read(), srq_hdr_write(), SRQ_LFN_LEN, SRQ_LK_EXCL, srq_lock(), srq_rec_write(), srq_reqid_format(), SRQ_REQID_LEN, SRQ_ST_QUEUED, srq_unlock(), srq_rec_t::status, srq_rec_t::tod_added, srq_rec_t::tod_expire, brix_stage_request_view_t::tod_expire, srq_rec_t::tod_status, srq_rec_t::user, and brix_stage_request_view_t::user.
Referenced by brix_handle_open(), brix_handle_prepare(), and tape_stage_post().
brix_stage_request_cancel()
ngx_int_t brix_stage_request_cancel (brix_stage_registry_t * reg, const char * reqid, ngx_log_t * log)
Definition at line 695 of file stage_request_registry.c.
References BRIX_STAGE_REQ_CANCELLED, brix_stage_request_set_status(), and log.
Referenced by brix_stage_request_pin_release(), and tape_stage_cancel().
brix_stage_request_delete()
ngx_int_t brix_stage_request_delete (brix_stage_registry_t * reg, const char * reqid, ngx_log_t * log)
Definition at line 665 of file stage_request_registry.c.
References log, SRQ_LK_EXCL, srq_lock(), srq_offset_by_reqid(), srq_rec_read(), srq_rec_valid(), srq_rec_write(), SRQ_ST_FREE, srq_unlock(), and srq_rec_t::status.
Referenced by brix_prepare_handle_cancel(), and tape_stage_delete().
brix_stage_request_find_by_path()
ngx_int_t brix_stage_request_find_by_path (brix_stage_registry_t * reg, const char * lfn, char * reqid_out, size_t reqid_out_sz, ngx_log_t * log)
Definition at line 733 of file stage_request_registry.c.
References srq_rec_t::lfn, log, srq_rec_t::reqid, srq_file_size(), SRQ_LK_SHARE, srq_lock(), SRQ_REC_OFF, srq_rec_read(), SRQ_REC_SIZE, srq_rec_valid(), SRQ_REQID_LEN, SRQ_ST_FREE, srq_unlock(), srq_rec_t::status, and srq_rec_t::tod_added.
Referenced by brix_query_prep_status(), and brix_stage_request_pin_release().
brix_stage_request_get()
ngx_int_t brix_stage_request_get (brix_stage_registry_t * reg, const char * reqid, brix_stage_request_t * out, ngx_log_t * log)
Definition at line 708 of file stage_request_registry.c.
References log, SRQ_LK_SHARE, srq_lock(), srq_offset_by_reqid(), srq_rec_read(), srq_rec_to_view(), srq_rec_valid(), SRQ_ST_FREE, srq_unlock(), and srq_rec_t::status.
Referenced by brix_query_prep_status(), brix_stage_request_list_files(), brix_stage_request_owner_check(), stage_waiter_deliver_one(), and tape_stage_get().
brix_stage_request_list_active()
ngx_int_t brix_stage_request_list_active (brix_stage_registry_t * reg, ngx_uint_t * cursor, brix_stage_request_t * out, ngx_log_t * log)
Definition at line 799 of file stage_request_registry.c.
References log, srq_file_size(), SRQ_LK_SHARE, srq_lock(), SRQ_REC_OFF, srq_rec_read(), SRQ_REC_SIZE, srq_rec_to_view(), srq_rec_valid(), SRQ_ST_FREE, srq_unlock(), and srq_rec_t::status.
Referenced by tape_stage_list().
brix_stage_request_list_files()
ngx_int_t brix_stage_request_list_files (brix_stage_registry_t * reg, const char * reqid, ngx_uint_t * cursor, brix_stage_request_t * out, ngx_log_t * log)
Definition at line 833 of file stage_request_registry.c.
References brix_stage_request_get(), and log.
brix_stage_request_owner_check()
ngx_int_t brix_stage_request_owner_check (brix_stage_registry_t * reg, const char * reqid, const char * requester_dn, ngx_log_t * log)
Definition at line 776 of file stage_request_registry.c.
References brix_stage_request_get(), log, and brix_stage_request_t::requester_dn.
Referenced by brix_prepare_handle_cancel(), tape_stage_cancel(), and tape_stage_delete().
brix_stage_request_pin_release()
ngx_int_t brix_stage_request_pin_release (brix_stage_registry_t * reg, const char * abs_path, ngx_log_t * log)
Definition at line 849 of file stage_request_registry.c.
References brix_stage_request_cancel(), brix_stage_request_find_by_path(), log, and SRQ_REQID_LEN.
Referenced by tape_release().
brix_stage_request_reap_expired()
ngx_uint_t brix_stage_request_reap_expired (brix_stage_registry_t * reg, time_t now, ngx_log_t * log)
Definition at line 869 of file stage_request_registry.c.
References log, srq_file_size(), SRQ_LK_EXCL, srq_lock(), SRQ_REC_OFF, srq_rec_read(), SRQ_REC_SIZE, srq_rec_valid(), srq_rec_write(), SRQ_ST_FREE, srq_unlock(), srq_rec_t::status, and srq_rec_t::tod_expire.
brix_stage_request_reqid_generate()
ngx_int_t brix_stage_request_reqid_generate (brix_stage_registry_t * reg, char * reqid_out, size_t reqid_out_sz, ngx_log_t * log)
Definition at line 531 of file stage_request_registry.c.
References log, srq_hdr_t::seq, srq_hdr_read(), srq_hdr_write(), SRQ_LK_EXCL, srq_lock(), srq_reqid_format(), SRQ_REQID_LEN, and srq_unlock().
brix_stage_request_set_status()
ngx_int_t brix_stage_request_set_status (brix_stage_registry_t * reg, const char * reqid, brix_stage_req_status_t status, ngx_log_t * log)
Definition at line 635 of file stage_request_registry.c.
References log, SRQ_LK_EXCL, srq_lock(), srq_offset_by_reqid(), srq_rec_read(), srq_rec_valid(), srq_rec_write(), SRQ_ST_FREE, srq_status_on_disk(), srq_unlock(), srq_rec_t::status, and srq_rec_t::tod_status.
Referenced by brix_stage_request_cancel().
srq_alloc_slot()
static int64_t srq_alloc_slot (brix_stage_registry_t * reg, ngx_log_t * log) static
Definition at line 433 of file stage_request_registry.c.
References log, srq_file_size(), SRQ_REC_OFF, srq_rec_read(), SRQ_REC_SIZE, srq_rec_valid(), SRQ_ST_FREE, and srq_rec_t::status.
Referenced by brix_stage_request_add().
srq_file_size()
static int64_t srq_file_size (brix_stage_registry_t * reg) static
Definition at line 295 of file stage_request_registry.c.
References fstat(), and stat().
Referenced by brix_stage_request_find_by_path(), brix_stage_request_list_active(), brix_stage_request_reap_expired(), srq_alloc_slot(), and srq_offset_by_reqid().
srq_hdr_compute_crc()
static uint32_t srq_hdr_compute_crc (const srq_hdr_t * hdr) static
Definition at line 145 of file stage_request_registry.c.
References brix_crc32c_value(), and srq_hdr_t::hdr_crc32c.
Referenced by srq_hdr_read(), and srq_hdr_write().
srq_hdr_init_blank()
static void srq_hdr_init_blank (srq_hdr_t * hdr, time_t now) static
Definition at line 168 of file stage_request_registry.c.
References srq_hdr_t::created_tod, srq_hdr_t::generation, srq_hdr_t::magic, srq_hdr_t::rec_size, srq_hdr_t::seq, SRQ_MAGIC, SRQ_REC_SIZE, SRQ_VERSION, and srq_hdr_t::version.
Referenced by brix_stage_registry_init().
srq_hdr_read()
static ngx_int_t srq_hdr_read (brix_stage_registry_t * reg, srq_hdr_t * hdr, ngx_log_t * log) static
Definition at line 231 of file stage_request_registry.c.
References srq_hdr_t::hdr_crc32c, log, srq_hdr_t::magic, srq_hdr_t::rec_size, srq_hdr_compute_crc(), SRQ_MAGIC, srq_pread_all(), SRQ_REC_SIZE, SRQ_VERSION, and srq_hdr_t::version.
Referenced by brix_stage_request_add(), and brix_stage_request_reqid_generate().
srq_hdr_write()
static ngx_int_t srq_hdr_write (brix_stage_registry_t * reg, srq_hdr_t * hdr, ngx_log_t * log) static
Definition at line 249 of file stage_request_registry.c.
References srq_hdr_t::hdr_crc32c, log, srq_hdr_t::magic, srq_hdr_t::rec_size, srq_hdr_compute_crc(), SRQ_MAGIC, srq_pwrite_all(), SRQ_REC_SIZE, SRQ_VERSION, and srq_hdr_t::version.
Referenced by brix_stage_registry_init(), brix_stage_request_add(), and brix_stage_request_reqid_generate().
srq_lock()
static ngx_int_t srq_lock (brix_stage_registry_t * reg, srq_lock_t mode) static
Definition at line 308 of file stage_request_registry.c.
References mode, srq_file_mtx, and SRQ_LK_EXCL.
Referenced by brix_stage_request_add(), brix_stage_request_delete(), brix_stage_request_find_by_path(), brix_stage_request_get(), brix_stage_request_list_active(), brix_stage_request_reap_expired(), brix_stage_request_reqid_generate(), and brix_stage_request_set_status().
srq_offset_by_reqid()
static int64_t srq_offset_by_reqid (brix_stage_registry_t * reg, const char * reqid, ngx_log_t * log) static
Definition at line 409 of file stage_request_registry.c.
References log, srq_rec_t::reqid, srq_file_size(), SRQ_REC_OFF, srq_rec_read(), SRQ_REC_SIZE, srq_rec_valid(), SRQ_ST_FREE, and srq_rec_t::status.
Referenced by brix_stage_request_delete(), brix_stage_request_get(), and brix_stage_request_set_status().
srq_pread_all()
static ngx_int_t srq_pread_all (int fd, void * buf, size_t len, off_t off, ngx_log_t * log) static
Definition at line 184 of file stage_request_registry.c.
References brix_sd_posix_wrap(), and log.
Referenced by srq_hdr_read(), and srq_rec_read().
srq_pwrite_all()
static ngx_int_t srq_pwrite_all (int fd, const void * buf, size_t len, off_t off, ngx_log_t * log) static
Definition at line 209 of file stage_request_registry.c.
References brix_sd_posix_wrap(), and log.
Referenced by srq_hdr_write(), and srq_rec_write().
srq_rec_compute_crc()
static uint32_t srq_rec_compute_crc (const srq_rec_t * rec) static
Definition at line 137 of file stage_request_registry.c.
References brix_crc32c_value(), and srq_rec_t::rec_crc32c.
Referenced by srq_rec_stamp_crc(), and srq_rec_valid().
srq_rec_read()
static ngx_int_t srq_rec_read (brix_stage_registry_t * reg, int64_t off, srq_rec_t * rec, ngx_log_t * log) static
Definition at line 266 of file stage_request_registry.c.
References log, srq_pread_all(), and SRQ_REC_SIZE.
Referenced by brix_stage_request_delete(), brix_stage_request_find_by_path(), brix_stage_request_get(), brix_stage_request_list_active(), brix_stage_request_reap_expired(), brix_stage_request_set_status(), srq_alloc_slot(), and srq_offset_by_reqid().
srq_rec_stamp_crc()
static void srq_rec_stamp_crc (srq_rec_t * rec) static
Definition at line 153 of file stage_request_registry.c.
References srq_rec_t::rec_crc32c, and srq_rec_compute_crc().
Referenced by srq_rec_write().
srq_rec_to_view()
static void srq_rec_to_view (const srq_rec_t * rec, brix_stage_request_t * out) static
Definition at line 394 of file stage_request_registry.c.
References srq_rec_t::cs_type, brix_stage_request_t::cs_type, srq_rec_t::lfn, brix_stage_request_t::lfn, srq_rec_t::reqid, brix_stage_request_t::reqid, srq_rec_t::requester_dn, brix_stage_request_t::requester_dn, srq_status_public(), srq_rec_t::status, brix_stage_request_t::status, srq_rec_t::tod_added, brix_stage_request_t::tod_added, srq_rec_t::tod_expire, and brix_stage_request_t::tod_expire.
Referenced by brix_stage_request_get(), and brix_stage_request_list_active().
srq_rec_valid()
static int srq_rec_valid (const srq_rec_t * rec, int64_t expect_off) static
Definition at line 159 of file stage_request_registry.c.
References srq_rec_t::rec_crc32c, srq_rec_t::self, and srq_rec_compute_crc().
Referenced by brix_stage_request_delete(), brix_stage_request_find_by_path(), brix_stage_request_get(), brix_stage_request_list_active(), brix_stage_request_reap_expired(), brix_stage_request_set_status(), srq_alloc_slot(), and srq_offset_by_reqid().
srq_rec_write()
static ngx_int_t srq_rec_write (brix_stage_registry_t * reg, int64_t off, srq_rec_t * rec, ngx_log_t * log) static
Definition at line 276 of file stage_request_registry.c.
References log, srq_rec_t::self, srq_pwrite_all(), SRQ_REC_SIZE, and srq_rec_stamp_crc().
Referenced by brix_stage_request_add(), brix_stage_request_delete(), brix_stage_request_reap_expired(), and brix_stage_request_set_status().
srq_reqid_format()
static void srq_reqid_format (const char * host, uint64_t seq, char * buf, size_t buf_sz) static
Definition at line 352 of file stage_request_registry.c.
Referenced by brix_stage_request_add(), and brix_stage_request_reqid_generate().
srq_status_on_disk()
static uint8_t srq_status_on_disk (brix_stage_req_status_t pub) static
Definition at line 381 of file stage_request_registry.c.
References BRIX_STAGE_REQ_ACTIVE, BRIX_STAGE_REQ_CANCELLED, BRIX_STAGE_REQ_DONE, BRIX_STAGE_REQ_FAILED, BRIX_STAGE_REQ_QUEUED, SRQ_ST_CANCELLED, SRQ_ST_FAILED, SRQ_ST_ONLINE, SRQ_ST_QUEUED, and SRQ_ST_STAGING.
Referenced by brix_stage_request_set_status().
srq_status_public()
static brix_stage_req_status_t srq_status_public (uint8_t on_disk) static
Definition at line 368 of file stage_request_registry.c.
References BRIX_STAGE_REQ_ACTIVE, BRIX_STAGE_REQ_CANCELLED, BRIX_STAGE_REQ_DONE, BRIX_STAGE_REQ_FAILED, BRIX_STAGE_REQ_QUEUED, SRQ_ST_CANCELLED, SRQ_ST_FAILED, SRQ_ST_ONLINE, SRQ_ST_QUEUED, and SRQ_ST_STAGING.
Referenced by srq_rec_to_view().
srq_unlock()
static void srq_unlock (brix_stage_registry_t * reg) static
Definition at line 333 of file stage_request_registry.c.
References srq_file_mtx.
Referenced by brix_stage_request_add(), brix_stage_request_delete(), brix_stage_request_find_by_path(), brix_stage_request_get(), brix_stage_request_list_active(), brix_stage_request_reap_expired(), brix_stage_request_reqid_generate(), and brix_stage_request_set_status().
Variable Documentation
srq_file_mtx
pthread_mutex_t srq_file_mtx = PTHREAD_MUTEX_INITIALIZER static
Definition at line 129 of file stage_request_registry.c.
Referenced by srq_lock(), and srq_unlock().
srq_singleton
brix_stage_registry_t srq_singleton static
Definition at line 121 of file stage_request_registry.c.
Referenced by brix_stage_registry_init(), and brix_stage_registry_singleton().
srq_singleton_used
int srq_singleton_used static
Definition at line 122 of file stage_request_registry.c.
Referenced by brix_stage_registry_init(), and brix_stage_registry_singleton().