nginx-xrootd: src/core/compat/staged_file.c File Reference
staged_file.c File Reference
#include "staged_file.h"
#include "tmp_path.h"
#include "fs/path/path.h"
#include "fs/path/beneath.h"
#include "fs/backend/sd.h"
#include "fs/xfer/xfer.h"
#include "fs/vfs/vfs_backend_registry.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Macros
#define BRIX_STAGE_COMMIT_SUFFIX ".commit"
#define BRIX_STAGE_MAX_DIRS 32
Functions
ngx_int_t brix_staged_open (ngx_log_t *log, const char *root_canon, const char *final_path, int open_flags, mode_t mode, ngx_uint_t attempts, brix_staged_file_t *staged)
ngx_int_t brix_staged_open_resume (ngx_log_t *log, const char *root_canon, const char *final_path, const char *principal, const char *stage_dir, mode_t mode, brix_staged_file_t *staged, off_t *cur_size)
static ngx_int_t stage_move_objects (brix_sd_obj_t *src, brix_sd_obj_t *dst)
static const char * commit_be_logical (const char *abs, const char *root)
static ngx_int_t commit_staged_to_backend (ngx_fd_t fd, const char *stage_path, const char *final_path, brix_sd_instance_t *dst, const char *root_canon, ngx_log_t *log)
ngx_int_t brix_commit_staged (ngx_fd_t fd, const char *stage_path, const char *final_path, mode_t final_mode, ngx_log_t *log)
void brix_stage_dir_register (const char *canon)
ngx_uint_t brix_stage_dir_count (void)
ngx_int_t brix_stage_mark_pending (const char *stage_partial, const char *final_path, ngx_log_t *log)
void brix_stage_unmark_pending (const char *stage_partial)
ngx_uint_t brix_stage_reap_dir (const char *stage_dir, ngx_log_t *log)
ngx_uint_t brix_stage_reap_all (ngx_log_t *log)
static ngx_int_t staged_commit_internal (ngx_log_t *log, const char *root_canon, brix_staged_file_t *staged, const char *final_path, int exclusive)
ngx_int_t brix_staged_commit (ngx_log_t *log, const char *root_canon, brix_staged_file_t *staged, const char *final_path)
ngx_int_t brix_staged_commit_excl (ngx_log_t *log, const char *root_canon, brix_staged_file_t *staged, const char *final_path)
void brix_staged_abort (ngx_log_t *log, const char *root_canon, brix_staged_file_t *staged, ngx_flag_t remove_tmp)
Variables
static char s_stage_dirs [32][PATH_MAX]
static ngx_uint_t s_stage_dir_count
Macro Definition Documentation
BRIX_STAGE_COMMIT_SUFFIX
#define BRIX_STAGE_COMMIT_SUFFIX ".commit"
Definition at line 469 of file staged_file.c.
BRIX_STAGE_MAX_DIRS
#define BRIX_STAGE_MAX_DIRS 32
Definition at line 470 of file staged_file.c.
Function Documentation
brix_commit_staged()
ngx_int_t brix_commit_staged (ngx_fd_t fd, const char * stage_path, const char * final_path, mode_t final_mode, ngx_log_t * log)
Definition at line 368 of file staged_file.c.
References brix_make_tmp_path(), brix_sd_default_driver(), brix_sd_posix_wrap(), brix_vfs_backend_resolve_for_path(), close(), commit_staged_to_backend(), fstat(), log, mode, open(), PATH_MAX, stage_move_objects(), and stat().
Referenced by brix_handle_close(), brix_stage_reap_dir(), and webdav_put_ranged_resume().
brix_stage_dir_count()
ngx_uint_t brix_stage_dir_count (void)
Definition at line 496 of file staged_file.c.
References s_stage_dir_count.
Referenced by ngx_stream_brix_init_process().
brix_stage_dir_register()
void brix_stage_dir_register (const char * canon)
Definition at line 476 of file staged_file.c.
References BRIX_STAGE_MAX_DIRS, ngx_memcpy, PATH_MAX, s_stage_dir_count, and s_stage_dirs.
Referenced by brix_config_prepare_server(), and ngx_http_brix_webdav_merge_loc_conf().
brix_stage_mark_pending()
ngx_int_t brix_stage_mark_pending (const char * stage_partial, const char * final_path, ngx_log_t * log)
Definition at line 502 of file staged_file.c.
References BRIX_STAGE_COMMIT_SUFFIX, close(), log, open(), and PATH_MAX.
Referenced by brix_handle_close(), and webdav_put_ranged_resume().
brix_stage_reap_all()
ngx_uint_t brix_stage_reap_all (ngx_log_t * log)
Definition at line 623 of file staged_file.c.
References brix_stage_reap_dir(), log, s_stage_dir_count, and s_stage_dirs.
Referenced by brix_stage_reap_handler().
brix_stage_reap_dir()
ngx_uint_t brix_stage_reap_dir (const char * stage_dir, ngx_log_t * log)
Definition at line 544 of file staged_file.c.
References brix_commit_staged(), BRIX_STAGE_COMMIT_SUFFIX, close(), log, ngx_memcpy, open(), PATH_MAX, read(), and stat().
Referenced by brix_stage_reap_all().
brix_stage_unmark_pending()
void brix_stage_unmark_pending (const char * stage_partial)
Definition at line 530 of file staged_file.c.
References BRIX_STAGE_COMMIT_SUFFIX, and PATH_MAX.
Referenced by brix_handle_close(), and webdav_put_ranged_resume().
brix_staged_abort()
void brix_staged_abort (ngx_log_t * log, const char * root_canon, brix_staged_file_t * staged, ngx_flag_t remove_tmp)
Definition at line 770 of file staged_file.c.
References brix_staged_file_t::active, brix_beneath_open_root(), brix_beneath_strip_root(), brix_unlink_beneath(), close(), brix_staged_file_t::fd, log, and brix_staged_file_t::tmp_path.
Referenced by brix_ns_local_copy(), brix_vfs_staged_abort(), ckp_recover_one(), ngx_http_brix_webdav_tpc_handle_copy(), sd_posix_staged_abort(), and webdav_put_ranged_resume().
brix_staged_commit()
ngx_int_t brix_staged_commit (ngx_log_t * log, const char * root_canon, brix_staged_file_t * staged, const char * final_path)
Definition at line 739 of file staged_file.c.
References log, and staged_commit_internal().
Referenced by brix_ns_local_copy(), brix_vfs_staged_commit(), ckp_recover_one(), ngx_http_brix_webdav_tpc_handle_copy(), and sd_posix_staged_commit().
brix_staged_commit_excl()
ngx_int_t brix_staged_commit_excl (ngx_log_t * log, const char * root_canon, brix_staged_file_t * staged, const char * final_path)
Definition at line 746 of file staged_file.c.
References log, and staged_commit_internal().
Referenced by brix_vfs_staged_commit(), and sd_posix_staged_commit().
brix_staged_open()
ngx_int_t brix_staged_open (ngx_log_t * log, const char * root_canon, const char * final_path, int open_flags, mode_t mode, ngx_uint_t attempts, brix_staged_file_t * staged)
Definition at line 59 of file staged_file.c.
References brix_staged_file_t::active, brix_beneath_open_root(), brix_beneath_strip_root(), brix_make_tmp_path(), brix_open_beneath(), close(), brix_staged_file_t::fd, brix_staged_file_t::final_mode, log, mode, and brix_staged_file_t::tmp_path.
Referenced by brix_ns_local_copy(), brix_vfs_staged_open(), ckp_recover_one(), ngx_http_brix_webdav_tpc_handle_copy(), and sd_posix_staged_open().
brix_staged_open_resume()
ngx_int_t brix_staged_open_resume (ngx_log_t * log, const char * root_canon, const char * final_path, const char * principal, const char * stage_dir, mode_t mode, brix_staged_file_t * staged, off_t * cur_size)
Definition at line 142 of file staged_file.c.
References brix_staged_file_t::active, brix_beneath_open_root(), brix_beneath_strip_root(), brix_make_resume_path(), brix_open_beneath(), close(), brix_staged_file_t::fd, brix_staged_file_t::final_mode, fstat(), log, mode, open(), stat(), and brix_staged_file_t::tmp_path.
Referenced by webdav_put_ranged_resume().
commit_be_logical()
static const char * commit_be_logical (const char * abs, const char * root) static
Definition at line 235 of file staged_file.c.
Referenced by commit_staged_to_backend().
commit_staged_to_backend()
static ngx_int_t commit_staged_to_backend (ngx_fd_t fd, const char * stage_path, const char * final_path, brix_sd_instance_t * dst, const char * root_canon, ngx_log_t * log) static
Definition at line 260 of file staged_file.c.
References brix_sd_posix_wrap(), close(), commit_be_logical(), fstat(), log, mode, open(), and stat().
Referenced by brix_commit_staged().
stage_move_objects()
static ngx_int_t stage_move_objects (brix_sd_obj_t * src, brix_sd_obj_t * dst) static
Definition at line 223 of file staged_file.c.
References brix_xfer_pump_objects().
Referenced by brix_commit_staged().
staged_commit_internal()
static ngx_int_t staged_commit_internal (ngx_log_t * log, const char * root_canon, brix_staged_file_t * staged, const char * final_path, int exclusive) static
Definition at line 650 of file staged_file.c.
References brix_staged_file_t::active, brix_beneath_open_root(), brix_beneath_strip_root(), brix_rename_beneath(), brix_rename_beneath_excl(), brix_unlink_beneath(), close(), brix_staged_file_t::fd, brix_staged_file_t::final_mode, log, and brix_staged_file_t::tmp_path.
Referenced by brix_staged_commit(), and brix_staged_commit_excl().
Variable Documentation
s_stage_dir_count
ngx_uint_t s_stage_dir_count static
Definition at line 473 of file staged_file.c.
Referenced by brix_stage_dir_count(), brix_stage_dir_register(), and brix_stage_reap_all().
s_stage_dirs
char s_stage_dirs[32][PATH_MAX] static
Definition at line 472 of file staged_file.c.
Referenced by brix_stage_dir_register(), and brix_stage_reap_all().