nginx-xrootd: src/core/compat/staged_file.h File Reference
staged_file.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <limits.h>
#include <sys/types.h>
Data Structures
struct brix_staged_file_t
struct brix_staged_open_req_t
Functions
ngx_int_t brix_staged_open (ngx_log_t *log, const brix_staged_open_req_t *req, brix_staged_file_t *staged)
ngx_int_t brix_staged_open_resume (ngx_log_t *log, const brix_staged_open_req_t *req, brix_staged_file_t *staged, off_t *cur_size)
ngx_int_t brix_commit_staged (ngx_fd_t fd, const char *stage_path, const char *final_path, mode_t final_mode, ngx_log_t *log)
void brix_stage_dir_register (const char *canon)
ngx_uint_t brix_stage_dir_count (void)
ngx_int_t brix_stage_mark_pending (const char *stage_partial, const char *final_path, ngx_log_t *log)
void brix_stage_unmark_pending (const char *stage_partial)
ngx_uint_t brix_stage_reap_dir (const char *stage_dir, ngx_log_t *log)
ngx_uint_t brix_stage_reap_all (ngx_log_t *log)
ngx_int_t brix_staged_commit (ngx_log_t *log, const char *root_canon, brix_staged_file_t *staged, const char *final_path)
ngx_int_t brix_staged_commit_excl (ngx_log_t *log, const char *root_canon, brix_staged_file_t *staged, const char *final_path)
void brix_staged_abort (ngx_log_t *log, const char *root_canon, brix_staged_file_t *staged, ngx_flag_t remove_tmp)
Function Documentation
brix_commit_staged()
ngx_int_t brix_commit_staged (ngx_fd_t fd, const char * stage_path, const char * final_path, mode_t final_mode, ngx_log_t * log)
Definition at line 364 of file staged_file_commit.c.
References brix_sd_default_driver(), brix_vfs_backend_resolve_for_path(), commit_cross_device(), commit_flush_and_chmod(), commit_staged_to_backend(), and log.
Referenced by brix_close_posc_commit(), reap_one_marker(), and webdav_put_ranged_resume().
brix_stage_dir_count()
ngx_uint_t brix_stage_dir_count (void)
Definition at line 74 of file staged_file_reap.c.
References s_stage_dir_count.
Referenced by brix_init_stage_reap_timer().
brix_stage_dir_register()
void brix_stage_dir_register (const char * canon)
Definition at line 54 of file staged_file_reap.c.
References BRIX_STAGE_MAX_DIRS, ngx_memcpy, PATH_MAX, s_stage_dir_count, and s_stage_dirs.
Referenced by brix_server_setup_export(), and webdav_prepare_stage_and_cache().
brix_stage_mark_pending()
ngx_int_t brix_stage_mark_pending (const char * stage_partial, const char * final_path, ngx_log_t * log)
Definition at line 80 of file staged_file_reap.c.
References BRIX_STAGE_COMMIT_SUFFIX, close(), log, open(), and PATH_MAX.
Referenced by brix_close_posc_commit(), and webdav_put_ranged_resume().
brix_stage_reap_all()
ngx_uint_t brix_stage_reap_all (ngx_log_t * log)
Definition at line 292 of file staged_file_reap.c.
References brix_stage_reap_dir(), log, s_stage_dir_count, and s_stage_dirs.
Referenced by brix_stage_reap_handler().
brix_stage_reap_dir()
ngx_uint_t brix_stage_reap_dir (const char * stage_dir, ngx_log_t * log)
Definition at line 272 of file staged_file_reap.c.
References BRIX_STAGE_REAP_MAX_MARKERS, BRIX_STAGE_REAP_NAME_MAX, log, reap_collect_markers(), and reap_one_marker().
Referenced by brix_stage_reap_all().
brix_stage_unmark_pending()
void brix_stage_unmark_pending (const char * stage_partial)
Definition at line 108 of file staged_file_reap.c.
References BRIX_STAGE_COMMIT_SUFFIX, and PATH_MAX.
Referenced by brix_close_posc_commit(), and webdav_put_ranged_resume().
brix_staged_abort()
void brix_staged_abort (ngx_log_t * log, const char * root_canon, brix_staged_file_t * staged, ngx_flag_t remove_tmp)
Definition at line 350 of file staged_file.c.
References brix_staged_file_t::active, brix_beneath_open_root(), brix_beneath_strip_root(), brix_unlink_beneath(), close(), brix_staged_file_t::fd, log, and brix_staged_file_t::tmp_path.
Referenced by brix_vfs_staged_abort(), ckp_recover_one(), ns_copy_finalize(), sd_posix_staged_abort(), webdav_put_ranged_resume(), webdav_tpc_commit_pulled_file(), webdav_tpc_pull_marker_exec(), webdav_tpc_pull_sync_exec(), and webdav_tpc_pull_thread_exec().
brix_staged_commit()
ngx_int_t brix_staged_commit (ngx_log_t * log, const char * root_canon, brix_staged_file_t * staged, const char * final_path)
Definition at line 319 of file staged_file.c.
References log, and staged_commit_internal().
Referenced by brix_vfs_staged_commit(), ckp_recover_one(), ns_copy_finalize(), sd_posix_staged_commit(), and webdav_tpc_commit_pulled_file().
brix_staged_commit_excl()
ngx_int_t brix_staged_commit_excl (ngx_log_t * log, const char * root_canon, brix_staged_file_t * staged, const char * final_path)
Definition at line 326 of file staged_file.c.
References log, and staged_commit_internal().
Referenced by brix_vfs_staged_commit(), and sd_posix_staged_commit().
brix_staged_open()
ngx_int_t brix_staged_open (ngx_log_t * log, const brix_staged_open_req_t * req, brix_staged_file_t * staged)
Definition at line 51 of file staged_file.c.
References brix_staged_file_t::active, brix_staged_open_req_t::attempts, brix_beneath_open_root(), brix_beneath_strip_root(), brix_make_tmp_path(), brix_open_beneath(), close(), brix_staged_file_t::fd, brix_staged_file_t::final_mode, brix_staged_open_req_t::final_path, log, brix_staged_open_req_t::mode, brix_staged_open_req_t::open_flags, brix_staged_open_req_t::root_canon, and brix_staged_file_t::tmp_path.
Referenced by ckp_recover_one(), ns_copy_open_dst(), sd_posix_staged_open(), staged_open_posix(), and webdav_tpc_prepare_pull_target().
brix_staged_open_resume()
ngx_int_t brix_staged_open_resume (ngx_log_t * log, const brix_staged_open_req_t * req, brix_staged_file_t * staged, off_t * cur_size)
Definition at line 143 of file staged_file.c.
References brix_staged_file_t::active, brix_beneath_open_root(), brix_beneath_strip_root(), brix_make_resume_path(), brix_open_beneath(), close(), brix_staged_file_t::fd, brix_staged_file_t::final_mode, brix_staged_open_req_t::final_path, fstat(), log, brix_staged_open_req_t::mode, open(), brix_staged_open_req_t::principal, brix_staged_open_req_t::root_canon, brix_staged_open_req_t::stage_dir, stat(), and brix_staged_file_t::tmp_path.
Referenced by webdav_put_ranged_resume().