nginx-xrootd: src/fs/xfer/stage_engine_scheduler.c File Reference
stage_engine_scheduler.c File Reference
#include "stage_engine.h"
#include "stage_engine_internal.h"
#include "xfer.h"
#include "core/aio/aio.h"
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
Macros
#define STAGE_TICK_BUDGET 32
Functions
const char * brix_stage_submit (brix_stage_kind_t kind, brix_sd_instance_t *src, const char *src_key, brix_sd_instance_t *dst, const char *dst_key, const brix_stage_opts_t *opts)
static void stage_complete (brix_stage_kind_t kind, brix_sd_instance_t *src, const char *src_key, const char *dst_key, const char *reqid, brix_xfer_result_t res, int last_errno, ngx_log_t *log)
void brix_stage_scheduler_tick (void)
Variables
static stage_pending_t * stage_pending_head
static stage_pending_t * stage_pending_tail
Macro Definition Documentation
STAGE_TICK_BUDGET
#define STAGE_TICK_BUDGET 32
Definition at line 98 of file stage_engine_scheduler.c.
Function Documentation
brix_stage_scheduler_tick()
void brix_stage_scheduler_tick (void)
Definition at line 285 of file stage_engine_scheduler.c.
References BRIX_XFER_OK, stage_pending_t::cred, stage_pending_t::dst, stage_pending_t::dst_key, brix_stage_cred_t::key, stage_pending_t::kind, log, stage_pending_t::next, stage_pending_t::reqid, stage_pending_t::src, stage_pending_t::src_key, stage_complete(), stage_engine_run(), stage_pending_head, stage_pending_tail, and STAGE_TICK_BUDGET.
Referenced by brix_stage_sched_handler().
brix_stage_submit()
const char * brix_stage_submit (brix_stage_kind_t kind, brix_sd_instance_t * src, const char * src_key, brix_sd_instance_t * dst, const char * dst_key, const brix_stage_opts_t * opts)
Definition at line 43 of file stage_engine_scheduler.c.
References brix_stage_opts_t::async, brix_stage_opts_t::cred, stage_pending_t::cred, stage_pending_t::dst, stage_pending_t::dst_key, brix_stage_opts_t::export_root, stage_pending_t::export_root, stage_pending_t::kind, stage_pending_t::next, stage_pending_t::reqid, stage_pending_t::src, stage_pending_t::src_key, stage_engine_run(), stage_journal_write(), stage_pending_head, stage_pending_tail, and stage_reqid_mint().
Referenced by sd_stage_staged_commit(), and sd_stage_wb_flush().
stage_complete()
static void stage_complete (brix_stage_kind_t kind, brix_sd_instance_t * src, const char * src_key, const char * dst_key, const char * reqid, brix_xfer_result_t res, int last_errno, ngx_log_t * log) static
Definition at line 121 of file stage_engine_scheduler.c.
References brix_sreq_decode(), BRIX_STAGE_FLUSH, brix_stage_kind_str(), BRIX_XFER_DENIED, BRIX_XFER_OK, close(), log, open(), read(), stage_deny_terminal(), stage_journal_dir, stage_journal_mark_failed(), and stage_journal_remove().
Referenced by brix_stage_scheduler_tick().
Variable Documentation
stage_pending_head
stage_pending_t* stage_pending_head static
Definition at line 37 of file stage_engine_scheduler.c.
Referenced by brix_stage_scheduler_tick(), and brix_stage_submit().
stage_pending_tail
stage_pending_t* stage_pending_tail static
Definition at line 38 of file stage_engine_scheduler.c.
Referenced by brix_stage_scheduler_tick(), and brix_stage_submit().