nginx-xrootd: src/fs/xfer/stage_engine_reconcile.c File Reference
stage_engine_reconcile.c File Reference
#include "stage_engine.h"
#include "stage_engine_internal.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "fs/backend/cache/sd_cache.h"
#include "fs/backend/stage/sd_stage.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
Functions
static int stage_reconcile_one (const char *path, ngx_log_t *log)
static ngx_uint_t stage_reconcile_snapshot (const char *dir, char names[][256], ngx_uint_t cap)
void brix_stage_reconcile (brix_stage_queue_t *queue)
Function Documentation
brix_stage_reconcile()
void brix_stage_reconcile (brix_stage_queue_t * queue)
Definition at line 186 of file stage_engine_reconcile.c.
References dropped, log, replayed, stage_journal_dir, stage_reconcile_one(), and stage_reconcile_snapshot().
Referenced by brix_init_stage_engine_worker().
stage_reconcile_one()
static int stage_reconcile_one (const char * path, ngx_log_t * log) static
Definition at line 61 of file stage_engine_reconcile.c.
References brix_sd_cache_instance_is(), brix_sd_cache_source_instance(), brix_sd_stage_instance_is(), brix_sd_stage_reflush(), brix_sreq_decode(), BRIX_STAGE_FLUSH, brix_vfs_backend_resolve(), close(), log, open(), read(), stage_deny_terminal(), stage_journal_bump_failed(), and stage_journal_dir.
Referenced by brix_stage_reconcile().
stage_reconcile_snapshot()
static ngx_uint_t stage_reconcile_snapshot (const char * dir, char names[][256], ngx_uint_t cap) static
Definition at line 161 of file stage_engine_reconcile.c.
Referenced by brix_stage_reconcile().