nginx-xrootd: src/fs/xfer/stage_request_registry_query.c File Reference
stage_request_registry_query.c File Reference
#include "stage_request_registry.h"
#include "stage_request_registry_internal.h"
Functions
ngx_int_t brix_stage_request_get (brix_stage_registry_t *reg, const char *reqid, brix_stage_request_t *out, ngx_log_t *log)
ngx_int_t brix_stage_request_find_by_path (brix_stage_registry_t *reg, const char *lfn, char *reqid_out, size_t reqid_out_sz, ngx_log_t *log)
ngx_int_t brix_stage_request_owner_check (brix_stage_registry_t *reg, const char *reqid, const char *requester_dn, ngx_log_t *log)
ngx_int_t brix_stage_request_list_active (brix_stage_registry_t *reg, ngx_uint_t *cursor, brix_stage_request_t *out, ngx_log_t *log)
ngx_int_t brix_stage_request_list_files (brix_stage_registry_t *reg, const char *reqid, ngx_uint_t *cursor, brix_stage_request_t *out, ngx_log_t *log)
ngx_int_t brix_stage_request_pin_release (brix_stage_registry_t *reg, const char *abs_path, ngx_log_t *log)
Function Documentation
brix_stage_request_find_by_path()
ngx_int_t brix_stage_request_find_by_path (brix_stage_registry_t * reg, const char * lfn, char * reqid_out, size_t reqid_out_sz, ngx_log_t * log)
Definition at line 55 of file stage_request_registry_query.c.
References srq_rec_t::lfn, log, srq_rec_t::reqid, srq_file_size(), SRQ_LK_SHARE, srq_lock(), SRQ_REC_OFF, srq_rec_read(), SRQ_REC_SIZE, srq_rec_valid(), SRQ_REQID_LEN, SRQ_ST_FREE, srq_unlock(), srq_rec_t::status, and srq_rec_t::tod_added.
Referenced by brix_stage_request_pin_release(), and qprep_status_for_path().
brix_stage_request_get()
ngx_int_t brix_stage_request_get (brix_stage_registry_t * reg, const char * reqid, brix_stage_request_t * out, ngx_log_t * log)
Definition at line 30 of file stage_request_registry_query.c.
References log, SRQ_LK_SHARE, srq_lock(), srq_offset_by_reqid(), srq_rec_read(), srq_rec_to_view(), srq_rec_valid(), SRQ_ST_FREE, srq_unlock(), and srq_rec_t::status.
Referenced by brix_stage_request_list_files(), brix_stage_request_owner_check(), qprep_resolve_src(), qprep_status_for_path(), stage_waiter_deliver_one(), and tape_stage_get().
brix_stage_request_list_active()
ngx_int_t brix_stage_request_list_active (brix_stage_registry_t * reg, ngx_uint_t * cursor, brix_stage_request_t * out, ngx_log_t * log)
Definition at line 121 of file stage_request_registry_query.c.
References log, srq_file_size(), SRQ_LK_SHARE, srq_lock(), SRQ_REC_OFF, srq_rec_read(), SRQ_REC_SIZE, srq_rec_to_view(), srq_rec_valid(), SRQ_ST_FREE, srq_unlock(), and srq_rec_t::status.
Referenced by tape_stage_list().
brix_stage_request_list_files()
ngx_int_t brix_stage_request_list_files (brix_stage_registry_t * reg, const char * reqid, ngx_uint_t * cursor, brix_stage_request_t * out, ngx_log_t * log)
Definition at line 155 of file stage_request_registry_query.c.
References brix_stage_request_get(), and log.
brix_stage_request_owner_check()
ngx_int_t brix_stage_request_owner_check (brix_stage_registry_t * reg, const char * reqid, const char * requester_dn, ngx_log_t * log)
Definition at line 98 of file stage_request_registry_query.c.
References brix_stage_request_get(), log, and brix_stage_request_t::requester_dn.
Referenced by brix_prepare_handle_cancel(), tape_stage_cancel(), and tape_stage_delete().
brix_stage_request_pin_release()
ngx_int_t brix_stage_request_pin_release (brix_stage_registry_t * reg, const char * abs_path, ngx_log_t * log)
Definition at line 171 of file stage_request_registry_query.c.
References brix_stage_request_cancel(), brix_stage_request_find_by_path(), log, and SRQ_REQID_LEN.
Referenced by tape_release().