nginx-xrootd: src/fs/xfer/stage_request_registry_internal.h File Reference
stage_request_registry_internal.h File Reference
#include "stage_request_registry.h"
#include <stdint.h>
#include <time.h>
Data Structures
struct srq_hdr_t
struct srq_rec_t
struct brix_stage_registry_t
Macros
#define SRQ_MAGIC 0x53525131u /* "SRQ1" */
#define SRQ_VERSION 1u
#define SRQ_REQID_LEN 40 /* on-disk width ("<seq>.<pid>@<host>") */
#define SRQ_LFN_LEN 3072
#define SRQ_DN_LEN 256
#define SRQ_USER_LEN 256
#define SRQ_REC_SIZE 4608u /* fixed slot size (header == record) */
#define SRQ_REC_OFF(n) (((int64_t) (n) + 1) * (int64_t) SRQ_REC_SIZE)
Enumerations
enum {
SRQ_ST_FREE = 0 , SRQ_ST_QUEUED = 1 , SRQ_ST_STAGING = 2 , SRQ_ST_ONLINE = 3 ,
SRQ_ST_FAILED = 4 , SRQ_ST_CANCELLED = 5
}
enum srq_lock_t { SRQ_LK_SHARE , SRQ_LK_EXCL }
Functions
ngx_int_t srq_lock (brix_stage_registry_t *reg, srq_lock_t mode)
void srq_unlock (brix_stage_registry_t *reg)
ngx_int_t srq_hdr_read (brix_stage_registry_t *reg, srq_hdr_t *hdr, ngx_log_t *log)
ngx_int_t srq_hdr_write (brix_stage_registry_t *reg, srq_hdr_t *hdr, ngx_log_t *log)
ngx_int_t srq_rec_read (brix_stage_registry_t *reg, int64_t off, srq_rec_t *rec, ngx_log_t *log)
ngx_int_t srq_rec_write (brix_stage_registry_t *reg, int64_t off, srq_rec_t *rec, ngx_log_t *log)
int64_t srq_file_size (brix_stage_registry_t *reg)
int srq_rec_valid (const srq_rec_t *rec, int64_t expect_off)
int64_t srq_offset_by_reqid (brix_stage_registry_t *reg, const char *reqid, ngx_log_t *log)
int64_t srq_alloc_slot (brix_stage_registry_t *reg, ngx_log_t *log)
void srq_reqid_format (const char *host, uint64_t seq, char *buf, size_t buf_sz)
uint8_t srq_status_on_disk (brix_stage_req_status_t pub)
void srq_rec_to_view (const srq_rec_t *rec, brix_stage_request_t *out)
Macro Definition Documentation
SRQ_DN_LEN
#define SRQ_DN_LEN 256
Definition at line 43 of file stage_request_registry_internal.h.
SRQ_LFN_LEN
#define SRQ_LFN_LEN 3072
Definition at line 42 of file stage_request_registry_internal.h.
SRQ_MAGIC
#define SRQ_MAGIC 0x53525131u /* "SRQ1" */
Definition at line 38 of file stage_request_registry_internal.h.
SRQ_REC_OFF
#define SRQ_REC_OFF (n) (((int64_t) (n) + 1) * (int64_t) SRQ_REC_SIZE)
Definition at line 47 of file stage_request_registry_internal.h.
SRQ_REC_SIZE
#define SRQ_REC_SIZE 4608u /* fixed slot size (header == record) */
Definition at line 46 of file stage_request_registry_internal.h.
SRQ_REQID_LEN
#define SRQ_REQID_LEN 40 /* on-disk width ("<seq>.<pid>@<host>") */
Definition at line 41 of file stage_request_registry_internal.h.
SRQ_USER_LEN
#define SRQ_USER_LEN 256
Definition at line 44 of file stage_request_registry_internal.h.
SRQ_VERSION
#define SRQ_VERSION 1u
Definition at line 39 of file stage_request_registry_internal.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SRQ_ST_FREE
SRQ_ST_QUEUED
SRQ_ST_STAGING
SRQ_ST_ONLINE
SRQ_ST_FAILED
SRQ_ST_CANCELLED
Definition at line 51 of file stage_request_registry_internal.h.
srq_lock_t
enum srq_lock_t
Enumerator
SRQ_LK_SHARE
SRQ_LK_EXCL
Definition at line 112 of file stage_request_registry_internal.h.
Function Documentation
srq_alloc_slot()
int64_t srq_alloc_slot (brix_stage_registry_t * reg, ngx_log_t * log)
Definition at line 372 of file stage_request_registry.c.
References log, srq_file_size(), SRQ_REC_OFF, srq_rec_read(), SRQ_REC_SIZE, srq_rec_valid(), SRQ_ST_FREE, and srq_rec_t::status.
Referenced by brix_stage_request_add().
srq_file_size()
int64_t srq_file_size (brix_stage_registry_t * reg)
Definition at line 234 of file stage_request_registry.c.
References fstat(), and stat().
Referenced by brix_stage_request_find_by_path(), brix_stage_request_list_active(), brix_stage_request_reap_expired(), srq_alloc_slot(), and srq_offset_by_reqid().
srq_hdr_read()
ngx_int_t srq_hdr_read (brix_stage_registry_t * reg, srq_hdr_t * hdr, ngx_log_t * log)
Definition at line 170 of file stage_request_registry.c.
References srq_hdr_t::hdr_crc32c, log, srq_hdr_t::magic, srq_hdr_t::rec_size, srq_hdr_compute_crc(), SRQ_MAGIC, srq_pread_all(), SRQ_REC_SIZE, SRQ_VERSION, and srq_hdr_t::version.
Referenced by brix_stage_request_add(), and brix_stage_request_reqid_generate().
srq_hdr_write()
ngx_int_t srq_hdr_write (brix_stage_registry_t * reg, srq_hdr_t * hdr, ngx_log_t * log)
Definition at line 188 of file stage_request_registry.c.
References srq_hdr_t::hdr_crc32c, log, srq_hdr_t::magic, srq_hdr_t::rec_size, srq_hdr_compute_crc(), SRQ_MAGIC, srq_pwrite_all(), SRQ_REC_SIZE, SRQ_VERSION, and srq_hdr_t::version.
Referenced by brix_stage_registry_init(), brix_stage_request_add(), and brix_stage_request_reqid_generate().
srq_lock()
ngx_int_t srq_lock (brix_stage_registry_t * reg, srq_lock_t mode)
Definition at line 247 of file stage_request_registry.c.
References srq_file_mtx, and SRQ_LK_EXCL.
Referenced by brix_stage_request_add(), brix_stage_request_delete(), brix_stage_request_find_by_path(), brix_stage_request_get(), brix_stage_request_list_active(), brix_stage_request_reap_expired(), brix_stage_request_reqid_generate(), and brix_stage_request_set_status().
srq_offset_by_reqid()
int64_t srq_offset_by_reqid (brix_stage_registry_t * reg, const char * reqid, ngx_log_t * log)
Definition at line 348 of file stage_request_registry.c.
References log, srq_rec_t::reqid, srq_file_size(), SRQ_REC_OFF, srq_rec_read(), SRQ_REC_SIZE, srq_rec_valid(), SRQ_ST_FREE, and srq_rec_t::status.
Referenced by brix_stage_request_delete(), brix_stage_request_get(), and brix_stage_request_set_status().
srq_rec_read()
ngx_int_t srq_rec_read (brix_stage_registry_t * reg, int64_t off, srq_rec_t * rec, ngx_log_t * log)
Definition at line 205 of file stage_request_registry.c.
References log, srq_pread_all(), and SRQ_REC_SIZE.
Referenced by brix_stage_request_delete(), brix_stage_request_find_by_path(), brix_stage_request_get(), brix_stage_request_list_active(), brix_stage_request_reap_expired(), brix_stage_request_set_status(), srq_alloc_slot(), and srq_offset_by_reqid().
srq_rec_to_view()
void srq_rec_to_view (const srq_rec_t * rec, brix_stage_request_t * out)
Definition at line 333 of file stage_request_registry.c.
References brix_stage_request_t::cs_type, srq_rec_t::cs_type, srq_rec_t::lfn, brix_stage_request_t::lfn, srq_rec_t::reqid, brix_stage_request_t::reqid, srq_rec_t::requester_dn, brix_stage_request_t::requester_dn, srq_status_public(), brix_stage_request_t::status, srq_rec_t::status, brix_stage_request_t::tod_added, srq_rec_t::tod_added, brix_stage_request_t::tod_expire, and srq_rec_t::tod_expire.
Referenced by brix_stage_request_get(), and brix_stage_request_list_active().
srq_rec_valid()
int srq_rec_valid (const srq_rec_t * rec, int64_t expect_off)
Definition at line 98 of file stage_request_registry.c.
References srq_rec_t::rec_crc32c, srq_rec_t::self, and srq_rec_compute_crc().
Referenced by brix_stage_request_delete(), brix_stage_request_find_by_path(), brix_stage_request_get(), brix_stage_request_list_active(), brix_stage_request_reap_expired(), brix_stage_request_set_status(), srq_alloc_slot(), and srq_offset_by_reqid().
srq_rec_write()
ngx_int_t srq_rec_write (brix_stage_registry_t * reg, int64_t off, srq_rec_t * rec, ngx_log_t * log)
Definition at line 215 of file stage_request_registry.c.
References log, srq_rec_t::self, srq_pwrite_all(), SRQ_REC_SIZE, and srq_rec_stamp_crc().
Referenced by brix_stage_request_add(), brix_stage_request_delete(), brix_stage_request_reap_expired(), and brix_stage_request_set_status().
srq_reqid_format()
void srq_reqid_format (const char * host, uint64_t seq, char * buf, size_t buf_sz)
Definition at line 291 of file stage_request_registry.c.
References host.
Referenced by brix_stage_request_reqid_generate(), and srq_rec_populate_from_view().
srq_status_on_disk()
uint8_t srq_status_on_disk (brix_stage_req_status_t pub)
Definition at line 320 of file stage_request_registry.c.
References BRIX_STAGE_REQ_ACTIVE, BRIX_STAGE_REQ_CANCELLED, BRIX_STAGE_REQ_DONE, BRIX_STAGE_REQ_FAILED, BRIX_STAGE_REQ_QUEUED, SRQ_ST_CANCELLED, SRQ_ST_FAILED, SRQ_ST_ONLINE, SRQ_ST_QUEUED, and SRQ_ST_STAGING.
Referenced by brix_stage_request_set_status().
srq_unlock()
void srq_unlock (brix_stage_registry_t * reg)
Definition at line 272 of file stage_request_registry.c.
References srq_file_mtx.
Referenced by brix_stage_request_add(), brix_stage_request_delete(), brix_stage_request_find_by_path(), brix_stage_request_get(), brix_stage_request_list_active(), brix_stage_request_reap_expired(), brix_stage_request_reqid_generate(), and brix_stage_request_set_status().