nginx-xrootd: src/fs/xfer/stage_waiter.c File Reference
stage_waiter.c File Reference
#include "stage_waiter.h"
#include "stage_request_registry.h"
#include "core/compat/shm_slots.h"
#include "protocols/root/read/open.h"
#include "protocols/root/response/async.h"
#include "protocols/root/connection/event_sched.h"
#include <ngx_shmtx.h>
#include <string.h>
Data Structures
struct stage_waiter_t
struct stage_waiter_table_t
Macros
#define STAGE_WAITER_MAX_SLOTS 4096
Functions
static stage_waiter_table_t * stage_waiter_table (void)
static ngx_int_t stage_waiter_init_zone (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t brix_stage_waiter_configure (ngx_conf_t *cf, ngx_uint_t slots)
ngx_int_t brix_stage_waiter_add (const char *reqid, uint16_t options, const u_char client_streamid[2], int conn_fd, ngx_atomic_uint_t conn_number, ngx_pid_t worker_pid, ngx_msec_t timeout_ms)
static ngx_connection_t * stage_waiter_find_conn (int fd)
static void stage_waiter_deliver_one (const stage_waiter_t *w)
void brix_stage_waiter_deliver (const char *reqid, int code)
void brix_stage_waiter_poll_local (void)
void brix_stage_waiter_drop_conn (int conn_fd, ngx_atomic_uint_t conn_number)
Variables
ngx_module_t ngx_stream_brix_module
static ngx_shm_zone_t * stage_waiter_zone
static ngx_shmtx_t stage_waiter_mtx
static ngx_uint_t stage_waiter_slots_req
Macro Definition Documentation
STAGE_WAITER_MAX_SLOTS
#define STAGE_WAITER_MAX_SLOTS 4096
Definition at line 26 of file stage_waiter.c.
Function Documentation
brix_stage_waiter_add()
ngx_int_t brix_stage_waiter_add (const char * reqid, uint16_t options, const u_char client_streamid[2], int conn_fd, ngx_atomic_uint_t conn_number, ngx_pid_t worker_pid, ngx_msec_t timeout_ms)
Definition at line 113 of file stage_waiter.c.
References brix_shm_remember_free_slot(), brix_shm_slot_expired(), stage_waiter_table_t::capacity, s, stage_waiter_table_t::slots, stage_waiter_mtx, and stage_waiter_table().
Referenced by brix_open_residency_gate().
brix_stage_waiter_configure()
ngx_int_t brix_stage_waiter_configure (ngx_conf_t * cf, ngx_uint_t slots)
Definition at line 90 of file stage_waiter.c.
References brix_shm_zone_size(), ngx_stream_brix_module, stage_waiter_init_zone(), STAGE_WAITER_MAX_SLOTS, stage_waiter_slots_req, and stage_waiter_zone.
Referenced by postconf_stage_waiter().
brix_stage_waiter_deliver()
void brix_stage_waiter_deliver (const char * reqid, int code)
Definition at line 261 of file stage_waiter.c.
References brix_stage_waiter_poll_local(), stage_waiter_table_t::capacity, code, s, stage_waiter_table_t::slots, stage_waiter_mtx, and stage_waiter_table().
brix_stage_waiter_drop_conn()
void brix_stage_waiter_drop_conn (int conn_fd, ngx_atomic_uint_t conn_number)
Definition at line 330 of file stage_waiter.c.
References stage_waiter_table_t::capacity, s, stage_waiter_table_t::slots, stage_waiter_mtx, and stage_waiter_table().
Referenced by brix_recv_pre_loop().
brix_stage_waiter_poll_local()
void brix_stage_waiter_poll_local (void)
Definition at line 286 of file stage_waiter.c.
References brix_shm_slot_expired(), stage_waiter_table_t::capacity, s, stage_waiter_table_t::slots, stage_waiter_deliver_one(), stage_waiter_mtx, and stage_waiter_table().
Referenced by brix_stage_waiter_deliver().
stage_waiter_deliver_one()
static void stage_waiter_deliver_one (const stage_waiter_t * w) static
Definition at line 193 of file stage_waiter.c.
References brix_open_resolved_file(), brix_schedule_read_resume(), brix_send_attn_asynresp(), brix_stage_registry_singleton(), brix_stage_request_get(), c, stage_waiter_t::client_streamid, stage_waiter_t::code, stage_waiter_t::conn_fd, stage_waiter_t::conn_number, brix_ctx_t::destroyed, kXR_error, kXR_FSError, brix_stage_request_t::lfn, ngx_memcpy, ngx_stream_brix_module, stage_waiter_t::options, brix_ctx_t::prepare, stage_waiter_t::reqid, brix_open_request_t::resolved, s, brix_ctx_prepare_t::stage_async_active, brix_ctx_prepare_t::stage_async_streamid, stage_waiter_find_conn(), brix_ctx_t::state, XRD_ST_REQ_HEADER, and XRD_ST_WAITING_FRM.
Referenced by brix_stage_waiter_poll_local().
stage_waiter_find_conn()
static ngx_connection_t * stage_waiter_find_conn (int fd) static
Definition at line 165 of file stage_waiter.c.
References c.
Referenced by stage_waiter_deliver_one().
stage_waiter_init_zone()
static ngx_int_t stage_waiter_init_zone (ngx_shm_zone_t * shm_zone, void * data) static
Definition at line 67 of file stage_waiter.c.
References brix_shm_table_alloc(), stage_waiter_table_t::capacity, stage_waiter_mtx, and stage_waiter_slots_req.
Referenced by brix_stage_waiter_configure().
stage_waiter_table()
static stage_waiter_table_t * stage_waiter_table (void) static
Definition at line 55 of file stage_waiter.c.
References stage_waiter_zone.
Referenced by brix_stage_waiter_add(), brix_stage_waiter_deliver(), brix_stage_waiter_drop_conn(), and brix_stage_waiter_poll_local().
Variable Documentation
ngx_stream_brix_module
ngx_module_t ngx_stream_brix_module extern
Definition at line 29 of file module_definition.c.
Referenced by brix_stage_waiter_configure(), and stage_waiter_deliver_one().
stage_waiter_mtx
ngx_shmtx_t stage_waiter_mtx static
Definition at line 50 of file stage_waiter.c.
Referenced by brix_stage_waiter_add(), brix_stage_waiter_deliver(), brix_stage_waiter_drop_conn(), brix_stage_waiter_poll_local(), and stage_waiter_init_zone().
stage_waiter_slots_req
ngx_uint_t stage_waiter_slots_req static
Definition at line 51 of file stage_waiter.c.
Referenced by brix_stage_waiter_configure(), and stage_waiter_init_zone().
stage_waiter_zone
ngx_shm_zone_t* stage_waiter_zone static
Definition at line 49 of file stage_waiter.c.
Referenced by brix_stage_waiter_configure(), and stage_waiter_table().