nginx-xrootd: src/fs/xfer/stage_request_registry.h File Reference
stage_request_registry.h File Reference
#include <ngx_core.h>
Data Structures
struct brix_stage_request_t
struct brix_stage_request_view_t
Macros
#define BRIX_STAGE_REQID_LEN 64
#define BRIX_STAGE_LFN_LEN 4096
#define BRIX_STAGE_DN_LEN 512
#define BRIX_STAGE_USER_LEN 64
Enumerations
enum brix_stage_cstype_t {
BRIX_STAGE_CS_NONE = 0 , BRIX_STAGE_CS_SHA1 = 1 , BRIX_STAGE_CS_SHA2 = 2 , BRIX_STAGE_CS_SHA3 = 3 ,
BRIX_STAGE_CS_ADLER32 = 4 , BRIX_STAGE_CS_MD5 = 5 , BRIX_STAGE_CS_CRC32 = 6
}
enum brix_stage_req_status_t {
BRIX_STAGE_REQ_QUEUED = 0 , BRIX_STAGE_REQ_ACTIVE , BRIX_STAGE_REQ_DONE , BRIX_STAGE_REQ_FAILED ,
BRIX_STAGE_REQ_CANCELLED
}
Functions
brix_stage_registry_t * brix_stage_registry_singleton (void)
ngx_int_t brix_stage_registry_init (const char *journal_dir, ngx_log_t *log)
ngx_int_t brix_stage_request_reqid_generate (brix_stage_registry_t *reg, char *reqid_out, size_t reqid_out_sz, ngx_log_t *log)
ngx_int_t brix_stage_request_add (brix_stage_registry_t *reg, const brix_stage_request_view_t *view, char *reqid_out, size_t reqid_out_sz, ngx_log_t *log)
ngx_int_t brix_stage_request_get (brix_stage_registry_t *reg, const char *reqid, brix_stage_request_t *out, ngx_log_t *log)
ngx_int_t brix_stage_request_find_by_path (brix_stage_registry_t *reg, const char *lfn, char *reqid_out, size_t reqid_out_sz, ngx_log_t *log)
ngx_int_t brix_stage_request_owner_check (brix_stage_registry_t *reg, const char *reqid, const char *requester_dn, ngx_log_t *log)
ngx_int_t brix_stage_request_set_status (brix_stage_registry_t *reg, const char *reqid, brix_stage_req_status_t status, ngx_log_t *log)
ngx_int_t brix_stage_request_cancel (brix_stage_registry_t *reg, const char *reqid, ngx_log_t *log)
ngx_int_t brix_stage_request_delete (brix_stage_registry_t *reg, const char *reqid, ngx_log_t *log)
ngx_int_t brix_stage_request_list_active (brix_stage_registry_t *reg, ngx_uint_t *cursor, brix_stage_request_t *out, ngx_log_t *log)
ngx_int_t brix_stage_request_list_files (brix_stage_registry_t *reg, const char *reqid, ngx_uint_t *cursor, brix_stage_request_t *out, ngx_log_t *log)
ngx_int_t brix_stage_request_pin_release (brix_stage_registry_t *reg, const char *abs_path, ngx_log_t *log)
ngx_uint_t brix_stage_request_reap_expired (brix_stage_registry_t *reg, time_t now, ngx_log_t *log)
Macro Definition Documentation
BRIX_STAGE_DN_LEN
#define BRIX_STAGE_DN_LEN 512
Definition at line 38 of file stage_request_registry.h.
BRIX_STAGE_LFN_LEN
#define BRIX_STAGE_LFN_LEN 4096
Definition at line 37 of file stage_request_registry.h.
BRIX_STAGE_REQID_LEN
#define BRIX_STAGE_REQID_LEN 64
Definition at line 36 of file stage_request_registry.h.
BRIX_STAGE_USER_LEN
#define BRIX_STAGE_USER_LEN 64
Definition at line 39 of file stage_request_registry.h.
Enumeration Type Documentation
brix_stage_cstype_t
enum brix_stage_cstype_t
Enumerator
BRIX_STAGE_CS_NONE
BRIX_STAGE_CS_SHA1
BRIX_STAGE_CS_SHA2
BRIX_STAGE_CS_SHA3
BRIX_STAGE_CS_ADLER32
BRIX_STAGE_CS_MD5
BRIX_STAGE_CS_CRC32
Definition at line 44 of file stage_request_registry.h.
brix_stage_req_status_t
enum brix_stage_req_status_t
Enumerator
BRIX_STAGE_REQ_QUEUED
BRIX_STAGE_REQ_ACTIVE
BRIX_STAGE_REQ_DONE
BRIX_STAGE_REQ_FAILED
BRIX_STAGE_REQ_CANCELLED
Definition at line 55 of file stage_request_registry.h.
Function Documentation
brix_stage_registry_init()
ngx_int_t brix_stage_registry_init (const char * journal_dir, ngx_log_t * log)
Definition at line 405 of file stage_request_registry.c.
References close(), fstat(), log, ngx_memcpy, open(), srq_hdr_init_blank(), srq_hdr_write(), srq_singleton, srq_singleton_used, and stat().
Referenced by brix_init_server_stage_registry().
brix_stage_registry_singleton()
brix_stage_registry_t * brix_stage_registry_singleton (void)
Definition at line 399 of file stage_request_registry.c.
References srq_singleton, and srq_singleton_used.
Referenced by brix_handle_prepare(), brix_open_residency_gate(), brix_prepare_handle_cancel(), prepare_dispatch_special(), prepare_enqueue_resolved(), qprep_resolve_src(), qprep_status_for_path(), stage_waiter_deliver_one(), and tape_queue().
brix_stage_request_add()
ngx_int_t brix_stage_request_add (brix_stage_registry_t * reg, const brix_stage_request_view_t * view, char * reqid_out, size_t reqid_out_sz, ngx_log_t * log)
Definition at line 141 of file stage_request_registry_mutate.c.
References log, srq_rec_t::reqid, srq_hdr_t::seq, srq_add_validate_args(), srq_alloc_slot(), srq_hdr_read(), srq_hdr_write(), SRQ_LK_EXCL, srq_lock(), srq_rec_populate_from_view(), srq_rec_write(), and srq_unlock().
Referenced by brix_open_residency_gate(), prepare_enqueue_resolved(), and tape_stage_enqueue_one().
brix_stage_request_cancel()
ngx_int_t brix_stage_request_cancel (brix_stage_registry_t * reg, const char * reqid, ngx_log_t * log)
Definition at line 247 of file stage_request_registry_mutate.c.
References BRIX_STAGE_REQ_CANCELLED, brix_stage_request_set_status(), and log.
Referenced by brix_stage_request_pin_release(), and tape_stage_cancel().
brix_stage_request_delete()
ngx_int_t brix_stage_request_delete (brix_stage_registry_t * reg, const char * reqid, ngx_log_t * log)
Definition at line 217 of file stage_request_registry_mutate.c.
References log, SRQ_LK_EXCL, srq_lock(), srq_offset_by_reqid(), srq_rec_read(), srq_rec_valid(), srq_rec_write(), SRQ_ST_FREE, srq_unlock(), and srq_rec_t::status.
Referenced by brix_prepare_handle_cancel(), and tape_stage_delete().
brix_stage_request_find_by_path()
ngx_int_t brix_stage_request_find_by_path (brix_stage_registry_t * reg, const char * lfn, char * reqid_out, size_t reqid_out_sz, ngx_log_t * log)
Definition at line 55 of file stage_request_registry_query.c.
References srq_rec_t::lfn, log, srq_rec_t::reqid, srq_file_size(), SRQ_LK_SHARE, srq_lock(), SRQ_REC_OFF, srq_rec_read(), SRQ_REC_SIZE, srq_rec_valid(), SRQ_REQID_LEN, SRQ_ST_FREE, srq_unlock(), srq_rec_t::status, and srq_rec_t::tod_added.
Referenced by brix_stage_request_pin_release(), and qprep_status_for_path().
brix_stage_request_get()
ngx_int_t brix_stage_request_get (brix_stage_registry_t * reg, const char * reqid, brix_stage_request_t * out, ngx_log_t * log)
Definition at line 30 of file stage_request_registry_query.c.
References log, SRQ_LK_SHARE, srq_lock(), srq_offset_by_reqid(), srq_rec_read(), srq_rec_to_view(), srq_rec_valid(), SRQ_ST_FREE, srq_unlock(), and srq_rec_t::status.
Referenced by brix_stage_request_list_files(), brix_stage_request_owner_check(), qprep_resolve_src(), qprep_status_for_path(), stage_waiter_deliver_one(), and tape_stage_get().
brix_stage_request_list_active()
ngx_int_t brix_stage_request_list_active (brix_stage_registry_t * reg, ngx_uint_t * cursor, brix_stage_request_t * out, ngx_log_t * log)
Definition at line 121 of file stage_request_registry_query.c.
References log, srq_file_size(), SRQ_LK_SHARE, srq_lock(), SRQ_REC_OFF, srq_rec_read(), SRQ_REC_SIZE, srq_rec_to_view(), srq_rec_valid(), SRQ_ST_FREE, srq_unlock(), and srq_rec_t::status.
Referenced by tape_stage_list().
brix_stage_request_list_files()
ngx_int_t brix_stage_request_list_files (brix_stage_registry_t * reg, const char * reqid, ngx_uint_t * cursor, brix_stage_request_t * out, ngx_log_t * log)
Definition at line 155 of file stage_request_registry_query.c.
References brix_stage_request_get(), and log.
brix_stage_request_owner_check()
ngx_int_t brix_stage_request_owner_check (brix_stage_registry_t * reg, const char * reqid, const char * requester_dn, ngx_log_t * log)
Definition at line 98 of file stage_request_registry_query.c.
References brix_stage_request_get(), log, and brix_stage_request_t::requester_dn.
Referenced by brix_prepare_handle_cancel(), tape_stage_cancel(), and tape_stage_delete().
brix_stage_request_pin_release()
ngx_int_t brix_stage_request_pin_release (brix_stage_registry_t * reg, const char * abs_path, ngx_log_t * log)
Definition at line 171 of file stage_request_registry_query.c.
References brix_stage_request_cancel(), brix_stage_request_find_by_path(), log, and SRQ_REQID_LEN.
Referenced by tape_release().
brix_stage_request_reap_expired()
ngx_uint_t brix_stage_request_reap_expired (brix_stage_registry_t * reg, time_t now, ngx_log_t * log)
Definition at line 257 of file stage_request_registry_mutate.c.
References log, srq_file_size(), SRQ_LK_EXCL, srq_lock(), SRQ_REC_OFF, srq_rec_read(), SRQ_REC_SIZE, srq_rec_valid(), srq_rec_write(), SRQ_ST_FREE, srq_unlock(), srq_rec_t::status, and srq_rec_t::tod_expire.
brix_stage_request_reqid_generate()
ngx_int_t brix_stage_request_reqid_generate (brix_stage_registry_t * reg, char * reqid_out, size_t reqid_out_sz, ngx_log_t * log)
Definition at line 30 of file stage_request_registry_mutate.c.
References log, srq_hdr_t::seq, srq_hdr_read(), srq_hdr_write(), SRQ_LK_EXCL, srq_lock(), srq_reqid_format(), SRQ_REQID_LEN, and srq_unlock().
brix_stage_request_set_status()
ngx_int_t brix_stage_request_set_status (brix_stage_registry_t * reg, const char * reqid, brix_stage_req_status_t status, ngx_log_t * log)
Definition at line 187 of file stage_request_registry_mutate.c.
References log, SRQ_LK_EXCL, srq_lock(), srq_offset_by_reqid(), srq_rec_read(), srq_rec_valid(), srq_rec_write(), SRQ_ST_FREE, srq_status_on_disk(), srq_unlock(), srq_rec_t::status, and srq_rec_t::tod_status.
Referenced by brix_stage_request_cancel().