nginx-xrootd: src/fs/xfer/stage_engine.h File Reference
stage_engine.h File Reference
#include <ngx_core.h>
#include "fs/backend/sd.h"
Data Structures
struct brix_stage_cred_t
struct brix_sreq_t
struct brix_stage_opts_t
Macros
#define BRIX_STAGE_DENY_MAX_ATTEMPTS 5
#define BRIX_STAGE_DENY_MAX_AGE_SEC (24 * 3600)
Typedefs
typedef struct brix_stage_queue_s brix_stage_queue_t
Enumerations
enum brix_stage_kind_t { BRIX_STAGE_RECALL = 0 , BRIX_STAGE_FLUSH = 1 , BRIX_STAGE_UPLOAD = 2 , BRIX_STAGE_MULTIPART = 3 }
enum brix_sreq_state_t {
BRIX_SREQ_QUEUED = 0 , BRIX_SREQ_INFLIGHT = 1 , BRIX_SREQ_DONE = 2 , BRIX_SREQ_FAILED = 3 ,
BRIX_SREQ_EXPIRED = 4
}
Functions
const char * brix_stage_submit (brix_stage_kind_t kind, brix_sd_instance_t *src, const char *src_key, brix_sd_instance_t *dst, const char *dst_key, const brix_stage_opts_t *opts)
ngx_int_t brix_stage_run_inline_cred (brix_stage_kind_t kind, brix_sd_instance_t *src, const char *src_key, brix_sd_instance_t *dst, const char *dst_key, const brix_stage_cred_t *cred)
ngx_int_t brix_stage_run_inline (brix_stage_kind_t kind, brix_sd_instance_t *src, const char *src_key, brix_sd_instance_t *dst, const char *dst_key)
ngx_int_t brix_sreq_decode (const void *buf, size_t n, brix_sreq_t *out)
void brix_stage_engine_init (const char *journal_dir)
int stage_deny_terminal (const char *journal_dir, const char *reqid, brix_sreq_t *rec, ngx_log_t *log)
void brix_stage_scheduler_tick (void)
void brix_stage_reconcile (brix_stage_queue_t *queue)
const char * brix_stage_kind_str (brix_stage_kind_t kind)
Macro Definition Documentation
BRIX_STAGE_DENY_MAX_AGE_SEC
#define BRIX_STAGE_DENY_MAX_AGE_SEC (24 * 3600)
Definition at line 223 of file stage_engine.h.
BRIX_STAGE_DENY_MAX_ATTEMPTS
#define BRIX_STAGE_DENY_MAX_ATTEMPTS 5
Definition at line 222 of file stage_engine.h.
Typedef Documentation
brix_stage_queue_t
typedef struct brix_stage_queue_s brix_stage_queue_t
Definition at line 135 of file stage_engine.h.
Enumeration Type Documentation
brix_sreq_state_t
enum brix_sreq_state_t
Enumerator
BRIX_SREQ_QUEUED
BRIX_SREQ_INFLIGHT
BRIX_SREQ_DONE
BRIX_SREQ_FAILED
BRIX_SREQ_EXPIRED
Definition at line 85 of file stage_engine.h.
brix_stage_kind_t
enum brix_stage_kind_t
Enumerator
BRIX_STAGE_RECALL
BRIX_STAGE_FLUSH
BRIX_STAGE_UPLOAD
BRIX_STAGE_MULTIPART
Definition at line 75 of file stage_engine.h.
Function Documentation
brix_sreq_decode()
ngx_int_t brix_sreq_decode (const void * buf, size_t n, brix_sreq_t * out)
Definition at line 373 of file stage_engine.c.
References ngx_memcpy.
Referenced by stage_complete(), stage_journal_mark_failed(), and stage_reconcile_one().
brix_stage_engine_init()
void brix_stage_engine_init (const char * journal_dir)
Definition at line 50 of file stage_engine_journal.c.
References stage_journal_dir.
Referenced by brix_init_stage_engine_worker().
brix_stage_kind_str()
const char * brix_stage_kind_str (brix_stage_kind_t kind)
Definition at line 55 of file stage_engine.c.
References BRIX_STAGE_FLUSH, BRIX_STAGE_MULTIPART, BRIX_STAGE_RECALL, and BRIX_STAGE_UPLOAD.
Referenced by stage_complete(), and stage_engine_run().
brix_stage_reconcile()
void brix_stage_reconcile (brix_stage_queue_t * queue)
Definition at line 186 of file stage_engine_reconcile.c.
References log, stage_journal_dir, stage_reconcile_one(), and stage_reconcile_snapshot().
Referenced by brix_init_stage_engine_worker().
brix_stage_run_inline()
ngx_int_t brix_stage_run_inline (brix_stage_kind_t kind, brix_sd_instance_t * src, const char * src_key, brix_sd_instance_t * dst, const char * dst_key)
Definition at line 409 of file stage_engine.c.
References brix_stage_run_inline_cred().
brix_stage_run_inline_cred()
ngx_int_t brix_stage_run_inline_cred (brix_stage_kind_t kind, brix_sd_instance_t * src, const char * src_key, brix_sd_instance_t * dst, const char * dst_key, const brix_stage_cred_t * cred)
Definition at line 394 of file stage_engine.c.
References BRIX_XFER_OK, and stage_engine_run().
Referenced by brix_sd_stage_reflush(), brix_stage_run_inline(), sd_stage_staged_commit(), sd_stage_wb_flush(), and sd_stage_wb_hydrate().
brix_stage_scheduler_tick()
void brix_stage_scheduler_tick (void)
Definition at line 285 of file stage_engine_scheduler.c.
References BRIX_XFER_OK, stage_pending_t::cred, stage_pending_t::dst, stage_pending_t::dst_key, brix_stage_cred_t::key, stage_pending_t::kind, log, stage_pending_t::next, stage_pending_t::reqid, stage_pending_t::src, stage_pending_t::src_key, stage_complete(), stage_engine_run(), stage_pending_head, stage_pending_tail, and STAGE_TICK_BUDGET.
Referenced by brix_stage_sched_handler().
brix_stage_submit()
const char * brix_stage_submit (brix_stage_kind_t kind, brix_sd_instance_t * src, const char * src_key, brix_sd_instance_t * dst, const char * dst_key, const brix_stage_opts_t * opts)
Definition at line 43 of file stage_engine_scheduler.c.
References brix_stage_opts_t::async, brix_stage_opts_t::cred, stage_pending_t::cred, stage_pending_t::dst, stage_pending_t::dst_key, brix_stage_opts_t::export_root, stage_pending_t::export_root, stage_pending_t::kind, stage_pending_t::next, stage_pending_t::reqid, stage_pending_t::src, stage_pending_t::src_key, stage_engine_run(), stage_journal_write(), stage_pending_head, stage_pending_tail, and stage_reqid_mint().
Referenced by sd_stage_staged_commit(), and sd_stage_wb_flush().
stage_deny_terminal()
int stage_deny_terminal (const char * journal_dir, const char * reqid, brix_sreq_t * rec, ngx_log_t * log)
Definition at line 311 of file stage_engine_journal.c.
References brix_sreq_t::attempts, BRIX_STAGE_DENY_MAX_AGE_SEC, BRIX_STAGE_DENY_MAX_ATTEMPTS, brix_sreq_t::cred, brix_sreq_t::dst_key, brix_sreq_t::enqueued_at, brix_stage_cred_t::key, log, brix_stage_cred_t::principal, stage_journal_move_to_deadletter(), and stage_journal_update_rec().
Referenced by stage_complete(), and stage_reconcile_one().