nginx-xrootd: src/fs/xfer/stage_engine_internal.h File Reference
stage_engine_internal.h File Reference
#include "stage_engine.h"
#include "xfer.h"
Data Structures
struct stage_pending_t
Functions
void stage_reqid_mint (char out[40])
void stage_journal_write (const stage_pending_t *p)
void stage_journal_remove (const char *reqid)
brix_xfer_result_t stage_engine_run (brix_stage_kind_t kind, brix_sd_instance_t *src, const char *src_key, brix_sd_instance_t *dst, const char *dst_key, const brix_stage_cred_t *cred)
Variables
char stage_journal_dir [1024]
Function Documentation
stage_engine_run()
brix_xfer_result_t stage_engine_run (brix_stage_kind_t kind, brix_sd_instance_t * src, const char * src_key, brix_sd_instance_t * dst, const char * dst_key, const brix_stage_cred_t * cred)
Definition at line 292 of file stage_engine.c.
References brix_sd_ucred_resolve(), brix_stage_kind_str(), BRIX_XFER_DENIED, brix_xfer_finish(), BRIX_XFER_OK, brix_stage_cred_t::deny, brix_stage_cred_t::dir, brix_sd_ucred_t::expired, brix_stage_cred_t::key, log, brix_sd_ucred_t::path, brix_sd_cred_t::principal, brix_stage_cred_t::principal, stage_engine_move(), stage_kind_dir(), stage_kind_to_xfer(), and brix_sd_cred_t::x509_proxy.
Referenced by brix_stage_run_inline_cred(), brix_stage_scheduler_tick(), and brix_stage_submit().
stage_journal_remove()
void stage_journal_remove (const char * reqid)
Definition at line 109 of file stage_engine_journal.c.
References stage_journal_dir.
Referenced by stage_complete().
stage_journal_write()
void stage_journal_write (const stage_pending_t * p)
Definition at line 70 of file stage_engine_journal.c.
References BRIX_SREQ_QUEUED, close(), brix_sreq_t::cred, stage_pending_t::cred, stage_pending_t::dst, brix_sreq_t::dst_driver, brix_sreq_t::dst_key, stage_pending_t::dst_key, brix_sreq_t::enqueued_at, brix_sreq_t::export_root, stage_pending_t::export_root, brix_sreq_t::kind, stage_pending_t::kind, open(), brix_sreq_t::reqid, stage_pending_t::reqid, stage_pending_t::src, brix_sreq_t::src_driver, brix_sreq_t::src_key, stage_pending_t::src_key, stage_journal_dir, and brix_sreq_t::state.
Referenced by brix_stage_submit().
stage_reqid_mint()
void stage_reqid_mint (char out[40])
Definition at line 61 of file stage_engine_journal.c.
References stage_reqid_seq.
Referenced by brix_stage_submit().
Variable Documentation
stage_journal_dir
char stage_journal_dir[1024] extern
Definition at line 46 of file stage_engine_journal.c.
Referenced by brix_stage_engine_init(), brix_stage_reconcile(), stage_complete(), stage_journal_remove(), stage_journal_write(), and stage_reconcile_one().