nginx-xrootd: src/core/compat/staged_file_commit.c File Reference
staged_file_commit.c File Reference
#include "staged_file.h"
#include "tmp_path.h"
#include "fs/backend/sd.h"
#include "fs/xfer/xfer.h"
#include "fs/vfs/vfs_backend_registry.h"
#include <errno.h>
#include <fcntl.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Functions
static ngx_int_t stage_move_objects (brix_sd_obj_t *src, brix_sd_obj_t *dst)
static const char * commit_be_logical (const char *abs, const char *root)
static ngx_fd_t cstb_open_source (ngx_fd_t fd, const char *stage_path, int *owned, mode_t *mode)
static ngx_int_t cstb_pump_and_commit (ngx_fd_t rfd, brix_sd_instance_t *dst, brix_sd_staged_t *st)
static ngx_int_t commit_staged_to_backend (ngx_fd_t fd, const char *stage_path, const char *final_path, brix_sd_instance_t *dst, const char *root_canon, ngx_log_t *log)
static ngx_int_t commit_flush_and_chmod (ngx_fd_t fd, mode_t final_mode)
static ngx_int_t commit_cross_device (const char *stage_path, const char *final_path)
ngx_int_t brix_commit_staged (ngx_fd_t fd, const char *stage_path, const char *final_path, mode_t final_mode, ngx_log_t *log)
Function Documentation
brix_commit_staged()
ngx_int_t brix_commit_staged (ngx_fd_t fd, const char * stage_path, const char * final_path, mode_t final_mode, ngx_log_t * log)
Definition at line 364 of file staged_file_commit.c.
References brix_sd_default_driver(), brix_vfs_backend_resolve_for_path(), commit_cross_device(), commit_flush_and_chmod(), commit_staged_to_backend(), and log.
Referenced by brix_close_posc_commit(), reap_one_marker(), and webdav_put_ranged_resume().
commit_be_logical()
static const char * commit_be_logical (const char * abs, const char * root) static
Definition at line 61 of file staged_file_commit.c.
Referenced by commit_staged_to_backend().
commit_cross_device()
static ngx_int_t commit_cross_device (const char * stage_path, const char * final_path) static
Definition at line 299 of file staged_file_commit.c.
References brix_make_tmp_path(), brix_sd_posix_wrap(), close(), fstat(), open(), PATH_MAX, stage_move_objects(), and stat().
Referenced by brix_commit_staged().
commit_flush_and_chmod()
static ngx_int_t commit_flush_and_chmod (ngx_fd_t fd, mode_t final_mode) static
Definition at line 260 of file staged_file_commit.c.
References brix_sd_posix_wrap().
Referenced by brix_commit_staged().
commit_staged_to_backend()
static ngx_int_t commit_staged_to_backend (ngx_fd_t fd, const char * stage_path, const char * final_path, brix_sd_instance_t * dst, const char * root_canon, ngx_log_t * log) static
Definition at line 196 of file staged_file_commit.c.
References close(), commit_be_logical(), cstb_open_source(), cstb_pump_and_commit(), and log.
Referenced by brix_commit_staged().
cstb_open_source()
static ngx_fd_t cstb_open_source (ngx_fd_t fd, const char * stage_path, int * owned, mode_t * mode) static
Definition at line 92 of file staged_file_commit.c.
References fstat(), open(), and stat().
Referenced by commit_staged_to_backend().
cstb_pump_and_commit()
static ngx_int_t cstb_pump_and_commit (ngx_fd_t rfd, brix_sd_instance_t * dst, brix_sd_staged_t * st) static
Definition at line 136 of file staged_file_commit.c.
References brix_sd_posix_wrap().
Referenced by commit_staged_to_backend().
stage_move_objects()
static ngx_int_t stage_move_objects (brix_sd_obj_t * src, brix_sd_obj_t * dst) static
Definition at line 49 of file staged_file_commit.c.
References brix_xfer_pump_objects().
Referenced by commit_cross_device().