nginx-xrootd: src/fs/xfer/stage_engine_journal.c File Reference
stage_engine_journal.c File Reference
#include "stage_engine.h"
#include "stage_engine_internal.h"
#include "xfer.h"
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
Functions
void brix_stage_engine_init (const char *journal_dir)
void stage_reqid_mint (char out[40])
void stage_journal_write (const stage_pending_t *p)
void stage_journal_remove (const char *reqid)
static void stage_journal_update_rec (const char *journal_dir, const brix_sreq_t *rec)
static void stage_journal_persist_failed (const char *journal_dir, brix_sreq_t *rec, int last_errno)
void stage_journal_mark_failed (const char *journal_dir, const char *reqid, int last_errno)
void stage_journal_bump_failed (const char *journal_dir, brix_sreq_t *rec, int last_errno)
static void stage_journal_move_to_deadletter (const char *journal_dir, const char *reqid, ngx_log_t *log)
int stage_deny_terminal (const char *journal_dir, const char *reqid, brix_sreq_t *rec, ngx_log_t *log)
Variables
char stage_journal_dir [1024]
static uint64_t stage_reqid_seq
Function Documentation
brix_stage_engine_init()
void brix_stage_engine_init (const char * journal_dir)
Definition at line 50 of file stage_engine_journal.c.
References stage_journal_dir.
Referenced by brix_init_stage_engine_worker().
stage_deny_terminal()
int stage_deny_terminal (const char * journal_dir, const char * reqid, brix_sreq_t * rec, ngx_log_t * log)
Definition at line 311 of file stage_engine_journal.c.
References brix_sreq_t::attempts, BRIX_STAGE_DENY_MAX_AGE_SEC, BRIX_STAGE_DENY_MAX_ATTEMPTS, brix_sreq_t::cred, brix_sreq_t::dst_key, brix_sreq_t::enqueued_at, brix_stage_cred_t::key, log, brix_stage_cred_t::principal, stage_journal_move_to_deadletter(), and stage_journal_update_rec().
Referenced by stage_complete(), and stage_reconcile_one().
stage_journal_bump_failed()
void stage_journal_bump_failed (const char * journal_dir, brix_sreq_t * rec, int last_errno)
Definition at line 205 of file stage_engine_journal.c.
References brix_sreq_t::attempts, and stage_journal_persist_failed().
Referenced by stage_reconcile_one().
stage_journal_mark_failed()
void stage_journal_mark_failed (const char * journal_dir, const char * reqid, int last_errno)
Definition at line 175 of file stage_engine_journal.c.
References brix_sreq_decode(), close(), open(), read(), and stage_journal_persist_failed().
Referenced by stage_complete().
stage_journal_move_to_deadletter()
static void stage_journal_move_to_deadletter (const char * journal_dir, const char * reqid, ngx_log_t * log) static
Definition at line 228 of file stage_engine_journal.c.
References close(), log, open(), and read().
Referenced by stage_deny_terminal().
stage_journal_persist_failed()
static void stage_journal_persist_failed (const char * journal_dir, brix_sreq_t * rec, int last_errno) static
Definition at line 165 of file stage_engine_journal.c.
References BRIX_SREQ_FAILED, brix_sreq_t::finished_at, brix_sreq_t::last_errno, stage_journal_update_rec(), and brix_sreq_t::state.
Referenced by stage_journal_bump_failed(), and stage_journal_mark_failed().
stage_journal_remove()
void stage_journal_remove (const char * reqid)
Definition at line 109 of file stage_engine_journal.c.
References stage_journal_dir.
Referenced by stage_complete().
stage_journal_update_rec()
static void stage_journal_update_rec (const char * journal_dir, const brix_sreq_t * rec) static
Definition at line 138 of file stage_engine_journal.c.
References close(), open(), and brix_sreq_t::reqid.
Referenced by stage_deny_terminal(), and stage_journal_persist_failed().
stage_journal_write()
void stage_journal_write (const stage_pending_t * p)
Definition at line 70 of file stage_engine_journal.c.
References BRIX_SREQ_QUEUED, close(), brix_sreq_t::cred, stage_pending_t::cred, stage_pending_t::dst, brix_sreq_t::dst_driver, brix_sreq_t::dst_key, stage_pending_t::dst_key, brix_sreq_t::enqueued_at, brix_sreq_t::export_root, stage_pending_t::export_root, brix_sreq_t::kind, stage_pending_t::kind, open(), brix_sreq_t::reqid, stage_pending_t::reqid, stage_pending_t::src, brix_sreq_t::src_driver, brix_sreq_t::src_key, stage_pending_t::src_key, stage_journal_dir, and brix_sreq_t::state.
Referenced by brix_stage_submit().
stage_reqid_mint()
void stage_reqid_mint (char out[40])
Definition at line 61 of file stage_engine_journal.c.
References stage_reqid_seq.
Referenced by brix_stage_submit().
Variable Documentation
stage_journal_dir
char stage_journal_dir[1024]
Definition at line 46 of file stage_engine_journal.c.
Referenced by brix_stage_engine_init(), brix_stage_reconcile(), stage_complete(), stage_journal_remove(), stage_journal_write(), and stage_reconcile_one().
stage_reqid_seq
uint64_t stage_reqid_seq static
Definition at line 47 of file stage_engine_journal.c.
Referenced by stage_reqid_mint().