nginx-xrootd: src/fs/xfer/stage_waiter.h File Reference
stage_waiter.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
Functions
ngx_int_t brix_stage_waiter_configure (ngx_conf_t *cf, ngx_uint_t slots)
ngx_int_t brix_stage_waiter_add (const char *reqid, uint16_t options, const u_char client_streamid[2], int conn_fd, ngx_atomic_uint_t conn_number, ngx_pid_t worker_pid, ngx_msec_t timeout_ms)
void brix_stage_waiter_deliver (const char *reqid, int code)
void brix_stage_waiter_poll_local (void)
void brix_stage_waiter_drop_conn (int conn_fd, ngx_atomic_uint_t conn_number)
Function Documentation
brix_stage_waiter_add()
ngx_int_t brix_stage_waiter_add (const char * reqid, uint16_t options, const u_char client_streamid[2], int conn_fd, ngx_atomic_uint_t conn_number, ngx_pid_t worker_pid, ngx_msec_t timeout_ms)
Definition at line 113 of file stage_waiter.c.
References brix_shm_remember_free_slot(), brix_shm_slot_expired(), stage_waiter_table_t::capacity, s, stage_waiter_table_t::slots, stage_waiter_mtx, and stage_waiter_table().
Referenced by brix_open_residency_gate().
brix_stage_waiter_configure()
ngx_int_t brix_stage_waiter_configure (ngx_conf_t * cf, ngx_uint_t slots)
Definition at line 90 of file stage_waiter.c.
References brix_shm_zone_size(), ngx_stream_brix_module, stage_waiter_init_zone(), STAGE_WAITER_MAX_SLOTS, stage_waiter_slots_req, and stage_waiter_zone.
Referenced by postconf_stage_waiter().
brix_stage_waiter_deliver()
void brix_stage_waiter_deliver (const char * reqid, int code)
Definition at line 261 of file stage_waiter.c.
References brix_stage_waiter_poll_local(), stage_waiter_table_t::capacity, code, s, stage_waiter_table_t::slots, stage_waiter_mtx, and stage_waiter_table().
brix_stage_waiter_drop_conn()
void brix_stage_waiter_drop_conn (int conn_fd, ngx_atomic_uint_t conn_number)
Definition at line 330 of file stage_waiter.c.
References stage_waiter_table_t::capacity, s, stage_waiter_table_t::slots, stage_waiter_mtx, and stage_waiter_table().
Referenced by brix_recv_pre_loop().
brix_stage_waiter_poll_local()
void brix_stage_waiter_poll_local (void)
Definition at line 286 of file stage_waiter.c.
References brix_shm_slot_expired(), stage_waiter_table_t::capacity, s, stage_waiter_table_t::slots, stage_waiter_deliver_one(), stage_waiter_mtx, and stage_waiter_table().
Referenced by brix_stage_waiter_deliver().