nginx-xrootd: src/fs/xfer/stage_engine.c File Reference
stage_engine.c File Reference
#include "stage_engine.h"
#include "xfer.h"
#include "core/aio/aio.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "fs/backend/cache/sd_cache.h"
#include "fs/backend/stage/sd_stage.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct stage_pending_t
Macros
#define STAGE_ENGINE_CHUNK (1u << 20)
#define STAGE_TICK_BUDGET 32
Functions
void brix_stage_engine_init (const char *journal_dir)
static void stage_reqid_mint (char out[40])
static void stage_journal_write (const stage_pending_t *p)
static void stage_journal_remove (const char *reqid)
static brix_xfer_kind_t stage_kind_to_xfer (brix_stage_kind_t kind)
static const char * stage_kind_dir (brix_stage_kind_t kind)
const char * brix_stage_kind_str (brix_stage_kind_t kind)
static brix_xfer_result_t stage_engine_move (brix_sd_instance_t *src, const char *src_key, brix_sd_instance_t *dst, const char *dst_key, off_t *bytes_out, int *err_out)
static brix_xfer_result_t stage_engine_run (brix_stage_kind_t kind, brix_sd_instance_t *src, const char *src_key, brix_sd_instance_t *dst, const char *dst_key)
const char * brix_stage_submit (brix_stage_kind_t kind, brix_sd_instance_t *src, const char *src_key, brix_sd_instance_t *dst, const char *dst_key, const brix_stage_opts_t *opts)
ngx_int_t brix_stage_run_inline (brix_stage_kind_t kind, brix_sd_instance_t *src, const char *src_key, brix_sd_instance_t *dst, const char *dst_key)
static void stage_complete (brix_stage_kind_t kind, brix_sd_instance_t *src, const char *src_key, const char *dst_key, const char *reqid, brix_xfer_result_t res, ngx_log_t *log)
void brix_stage_scheduler_tick (void)
static int stage_reconcile_one (const char *path, ngx_log_t *log)
void brix_stage_reconcile (brix_stage_queue_t *queue)
Variables
static stage_pending_t * stage_pending_head
static stage_pending_t * stage_pending_tail
static char stage_journal_dir [1024]
static uint64_t stage_reqid_seq
Macro Definition Documentation
STAGE_ENGINE_CHUNK
#define STAGE_ENGINE_CHUNK (1u << 20)
Definition at line 29 of file stage_engine.c.
STAGE_TICK_BUDGET
#define STAGE_TICK_BUDGET 32
Definition at line 384 of file stage_engine.c.
Function Documentation
brix_stage_engine_init()
void brix_stage_engine_init (const char * journal_dir)
Definition at line 58 of file stage_engine.c.
References stage_journal_dir.
Referenced by ngx_stream_brix_init_process().
brix_stage_kind_str()
const char * brix_stage_kind_str (brix_stage_kind_t kind)
Definition at line 154 of file stage_engine.c.
References BRIX_STAGE_FLUSH, BRIX_STAGE_MULTIPART, BRIX_STAGE_RECALL, and BRIX_STAGE_UPLOAD.
Referenced by stage_complete().
brix_stage_reconcile()
void brix_stage_reconcile (brix_stage_queue_t * queue)
Definition at line 602 of file stage_engine.c.
References log, stage_journal_dir, and stage_reconcile_one().
Referenced by ngx_stream_brix_init_process().
brix_stage_run_inline()
ngx_int_t brix_stage_run_inline (brix_stage_kind_t kind, brix_sd_instance_t * src, const char * src_key, brix_sd_instance_t * dst, const char * dst_key)
Definition at line 369 of file stage_engine.c.
References BRIX_XFER_OK, and stage_engine_run().
Referenced by brix_sd_stage_reflush(), sd_stage_staged_commit(), and sd_stage_wb_flush().
brix_stage_scheduler_tick()
void brix_stage_scheduler_tick (void)
Definition at line 509 of file stage_engine.c.
References stage_pending_t::dst, stage_pending_t::dst_key, stage_pending_t::kind, log, stage_pending_t::next, stage_pending_t::reqid, stage_pending_t::src, stage_pending_t::src_key, stage_complete(), stage_engine_run(), stage_pending_head, stage_pending_tail, and STAGE_TICK_BUDGET.
Referenced by brix_stage_sched_handler().
brix_stage_submit()
const char * brix_stage_submit (brix_stage_kind_t kind, brix_sd_instance_t * src, const char * src_key, brix_sd_instance_t * dst, const char * dst_key, const brix_stage_opts_t * opts)
Definition at line 319 of file stage_engine.c.
References brix_stage_opts_t::async, stage_pending_t::dst, stage_pending_t::dst_key, stage_pending_t::export_root, brix_stage_opts_t::export_root, stage_pending_t::kind, stage_pending_t::next, stage_pending_t::reqid, stage_pending_t::src, stage_pending_t::src_key, stage_engine_run(), stage_journal_write(), stage_pending_head, stage_pending_tail, and stage_reqid_mint().
Referenced by sd_stage_staged_commit().
stage_complete()
static void stage_complete (brix_stage_kind_t kind, brix_sd_instance_t * src, const char * src_key, const char * dst_key, const char * reqid, brix_xfer_result_t res, ngx_log_t * log) static
Definition at line 391 of file stage_engine.c.
References BRIX_STAGE_FLUSH, brix_stage_kind_str(), BRIX_XFER_OK, log, and stage_journal_remove().
Referenced by brix_stage_scheduler_tick().
stage_engine_move()
static brix_xfer_result_t stage_engine_move (brix_sd_instance_t * src, const char * src_key, brix_sd_instance_t * dst, const char * dst_key, off_t * bytes_out, int * err_out) static
Definition at line 175 of file stage_engine.c.
References BRIX_SD_O_READ, BRIX_XFER_COMMIT_ERR, BRIX_XFER_DST_ERR, BRIX_XFER_OK, BRIX_XFER_SRC_ERR, mode, brix_sd_stat_t::mode, and STAGE_ENGINE_CHUNK.
Referenced by stage_engine_run().
stage_engine_run()
static brix_xfer_result_t stage_engine_run (brix_stage_kind_t kind, brix_sd_instance_t * src, const char * src_key, brix_sd_instance_t * dst, const char * dst_key) static
Definition at line 296 of file stage_engine.c.
References brix_xfer_finish(), BRIX_XFER_OK, log, stage_engine_move(), stage_kind_dir(), and stage_kind_to_xfer().
Referenced by brix_stage_run_inline(), brix_stage_scheduler_tick(), and brix_stage_submit().
stage_journal_remove()
static void stage_journal_remove (const char * reqid) static
Definition at line 116 of file stage_engine.c.
References stage_journal_dir.
Referenced by stage_complete().
stage_journal_write()
static void stage_journal_write (const stage_pending_t * p) static
Definition at line 78 of file stage_engine.c.
References BRIX_SREQ_QUEUED, close(), stage_pending_t::dst, brix_sreq_t::dst_driver, stage_pending_t::dst_key, brix_sreq_t::dst_key, brix_sreq_t::enqueued_at, stage_pending_t::export_root, brix_sreq_t::export_root, stage_pending_t::kind, brix_sreq_t::kind, open(), stage_pending_t::reqid, brix_sreq_t::reqid, stage_pending_t::src, brix_sreq_t::src_driver, stage_pending_t::src_key, brix_sreq_t::src_key, stage_journal_dir, and brix_sreq_t::state.
Referenced by brix_stage_submit().
stage_kind_dir()
static const char * stage_kind_dir (brix_stage_kind_t kind) static
Definition at line 148 of file stage_engine.c.
References BRIX_STAGE_FLUSH.
Referenced by stage_engine_run().
stage_kind_to_xfer()
static brix_xfer_kind_t stage_kind_to_xfer (brix_stage_kind_t kind) static
Definition at line 135 of file stage_engine.c.
References BRIX_STAGE_FLUSH, BRIX_STAGE_MULTIPART, BRIX_STAGE_RECALL, BRIX_STAGE_UPLOAD, BRIX_XFER_STAGE, BRIX_XFER_TAPE, and BRIX_XFER_WT.
Referenced by stage_engine_run().
stage_reconcile_one()
static int stage_reconcile_one (const char * path, ngx_log_t * log) static
Definition at line 561 of file stage_engine.c.
References brix_sd_cache_instance_is(), brix_sd_cache_source_instance(), brix_sd_stage_instance_is(), brix_sd_stage_reflush(), BRIX_STAGE_FLUSH, brix_vfs_backend_resolve(), close(), brix_sreq_t::dst_key, brix_sreq_t::export_root, brix_sreq_t::kind, log, open(), and read().
Referenced by brix_stage_reconcile().
stage_reqid_mint()
static void stage_reqid_mint (char out[40]) static
Definition at line 69 of file stage_engine.c.
References stage_reqid_seq.
Referenced by brix_stage_submit().
Variable Documentation
stage_journal_dir
char stage_journal_dir[1024] static
Definition at line 54 of file stage_engine.c.
Referenced by brix_stage_engine_init(), brix_stage_reconcile(), stage_journal_remove(), and stage_journal_write().
stage_pending_head
stage_pending_t* stage_pending_head static
Definition at line 52 of file stage_engine.c.
Referenced by brix_stage_scheduler_tick(), and brix_stage_submit().
stage_pending_tail
stage_pending_t* stage_pending_tail static
Definition at line 53 of file stage_engine.c.
Referenced by brix_stage_scheduler_tick(), and brix_stage_submit().
stage_reqid_seq
uint64_t stage_reqid_seq static
Definition at line 55 of file stage_engine.c.
Referenced by stage_reqid_mint().