nginx-xrootd: src/core/compat/staged_file_reap.c File Reference
staged_file_reap.c File Reference
#include "staged_file.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Macros
#define BRIX_STAGE_COMMIT_SUFFIX ".commit"
#define BRIX_STAGE_MAX_DIRS 32
#define BRIX_STAGE_REAP_MAX_MARKERS 256
#define BRIX_STAGE_REAP_NAME_MAX 256
Functions
void brix_stage_dir_register (const char *canon)
ngx_uint_t brix_stage_dir_count (void)
ngx_int_t brix_stage_mark_pending (const char *stage_partial, const char *final_path, ngx_log_t *log)
void brix_stage_unmark_pending (const char *stage_partial)
static ngx_uint_t reap_collect_markers (const char *stage_dir, char names[][256], ngx_uint_t max)
static ngx_int_t reap_read_marker_target (const char *marker, char *final, size_t cap)
static ngx_uint_t reap_one_marker (const char *stage_dir, const char *name, ngx_log_t *log)
ngx_uint_t brix_stage_reap_dir (const char *stage_dir, ngx_log_t *log)
ngx_uint_t brix_stage_reap_all (ngx_log_t *log)
Variables
static char s_stage_dirs [32][PATH_MAX]
static ngx_uint_t s_stage_dir_count
Macro Definition Documentation
BRIX_STAGE_COMMIT_SUFFIX
#define BRIX_STAGE_COMMIT_SUFFIX ".commit"
Definition at line 47 of file staged_file_reap.c.
BRIX_STAGE_MAX_DIRS
#define BRIX_STAGE_MAX_DIRS 32
Definition at line 48 of file staged_file_reap.c.
BRIX_STAGE_REAP_MAX_MARKERS
#define BRIX_STAGE_REAP_MAX_MARKERS 256
Definition at line 119 of file staged_file_reap.c.
BRIX_STAGE_REAP_NAME_MAX
#define BRIX_STAGE_REAP_NAME_MAX 256
Definition at line 120 of file staged_file_reap.c.
Function Documentation
brix_stage_dir_count()
ngx_uint_t brix_stage_dir_count (void)
Definition at line 74 of file staged_file_reap.c.
References s_stage_dir_count.
Referenced by brix_init_stage_reap_timer().
brix_stage_dir_register()
void brix_stage_dir_register (const char * canon)
Definition at line 54 of file staged_file_reap.c.
References BRIX_STAGE_MAX_DIRS, ngx_memcpy, PATH_MAX, s_stage_dir_count, and s_stage_dirs.
Referenced by brix_server_setup_export(), and webdav_prepare_stage_and_cache().
brix_stage_mark_pending()
ngx_int_t brix_stage_mark_pending (const char * stage_partial, const char * final_path, ngx_log_t * log)
Definition at line 80 of file staged_file_reap.c.
References BRIX_STAGE_COMMIT_SUFFIX, close(), log, open(), and PATH_MAX.
Referenced by brix_close_posc_commit(), and webdav_put_ranged_resume().
brix_stage_reap_all()
ngx_uint_t brix_stage_reap_all (ngx_log_t * log)
Definition at line 292 of file staged_file_reap.c.
References brix_stage_reap_dir(), log, s_stage_dir_count, and s_stage_dirs.
Referenced by brix_stage_reap_handler().
brix_stage_reap_dir()
ngx_uint_t brix_stage_reap_dir (const char * stage_dir, ngx_log_t * log)
Definition at line 272 of file staged_file_reap.c.
References BRIX_STAGE_REAP_MAX_MARKERS, BRIX_STAGE_REAP_NAME_MAX, log, reap_collect_markers(), and reap_one_marker().
Referenced by brix_stage_reap_all().
brix_stage_unmark_pending()
void brix_stage_unmark_pending (const char * stage_partial)
Definition at line 108 of file staged_file_reap.c.
References BRIX_STAGE_COMMIT_SUFFIX, and PATH_MAX.
Referenced by brix_close_posc_commit(), and webdav_put_ranged_resume().
reap_collect_markers()
static ngx_uint_t reap_collect_markers (const char * stage_dir, char names[][256], ngx_uint_t max) static
Definition at line 140 of file staged_file_reap.c.
References BRIX_STAGE_COMMIT_SUFFIX, BRIX_STAGE_REAP_NAME_MAX, and ngx_memcpy.
Referenced by brix_stage_reap_dir().
reap_one_marker()
static ngx_uint_t reap_one_marker (const char * stage_dir, const char * name, ngx_log_t * log) static
Definition at line 229 of file staged_file_reap.c.
References brix_commit_staged(), BRIX_STAGE_COMMIT_SUFFIX, log, name, PATH_MAX, reap_read_marker_target(), and stat().
Referenced by brix_stage_reap_dir().
reap_read_marker_target()
static ngx_int_t reap_read_marker_target (const char * marker, char * final, size_t cap) static
Definition at line 183 of file staged_file_reap.c.
References close(), open(), and read().
Referenced by reap_one_marker().
Variable Documentation
s_stage_dir_count
ngx_uint_t s_stage_dir_count static
Definition at line 51 of file staged_file_reap.c.
Referenced by brix_stage_dir_count(), brix_stage_dir_register(), and brix_stage_reap_all().
s_stage_dirs
char s_stage_dirs[32][PATH_MAX] static
Definition at line 50 of file staged_file_reap.c.
Referenced by brix_stage_dir_register(), and brix_stage_reap_all().