nginx-xrootd: src/fs/xfer/stage_request_registry_mutate.c File Reference
stage_request_registry_mutate.c File Reference
#include "stage_request_registry.h"
#include "stage_request_registry_internal.h"
#include <time.h>
Functions
ngx_int_t brix_stage_request_reqid_generate (brix_stage_registry_t *reg, char *reqid_out, size_t reqid_out_sz, ngx_log_t *log)
static ngx_int_t srq_add_validate_args (brix_stage_registry_t *reg, const brix_stage_request_view_t *view, const char *reqid_out, size_t reqid_out_sz, ngx_log_t *log)
static void srq_rec_populate_from_view (srq_rec_t *rec, const brix_stage_request_view_t *view, const char *host, uint64_t seq, int64_t off, time_t now)
ngx_int_t brix_stage_request_add (brix_stage_registry_t *reg, const brix_stage_request_view_t *view, char *reqid_out, size_t reqid_out_sz, ngx_log_t *log)
ngx_int_t brix_stage_request_set_status (brix_stage_registry_t *reg, const char *reqid, brix_stage_req_status_t status, ngx_log_t *log)
ngx_int_t brix_stage_request_delete (brix_stage_registry_t *reg, const char *reqid, ngx_log_t *log)
ngx_int_t brix_stage_request_cancel (brix_stage_registry_t *reg, const char *reqid, ngx_log_t *log)
ngx_uint_t brix_stage_request_reap_expired (brix_stage_registry_t *reg, time_t now, ngx_log_t *log)
Function Documentation
brix_stage_request_add()
ngx_int_t brix_stage_request_add (brix_stage_registry_t * reg, const brix_stage_request_view_t * view, char * reqid_out, size_t reqid_out_sz, ngx_log_t * log)
Definition at line 141 of file stage_request_registry_mutate.c.
References log, srq_rec_t::reqid, srq_hdr_t::seq, srq_add_validate_args(), srq_alloc_slot(), srq_hdr_read(), srq_hdr_write(), SRQ_LK_EXCL, srq_lock(), srq_rec_populate_from_view(), srq_rec_write(), and srq_unlock().
Referenced by brix_open_residency_gate(), cms_prep_add(), prepare_enqueue_resolved(), and tape_stage_enqueue_one().
brix_stage_request_cancel()
ngx_int_t brix_stage_request_cancel (brix_stage_registry_t * reg, const char * reqid, ngx_log_t * log)
Definition at line 247 of file stage_request_registry_mutate.c.
References BRIX_STAGE_REQ_CANCELLED, brix_stage_request_set_status(), and log.
Referenced by brix_stage_request_pin_release(), and tape_stage_cancel().
brix_stage_request_delete()
ngx_int_t brix_stage_request_delete (brix_stage_registry_t * reg, const char * reqid, ngx_log_t * log)
Definition at line 217 of file stage_request_registry_mutate.c.
References log, SRQ_LK_EXCL, srq_lock(), srq_offset_by_reqid(), srq_rec_read(), srq_rec_valid(), srq_rec_write(), SRQ_ST_FREE, srq_unlock(), and srq_rec_t::status.
Referenced by brix_prepare_handle_cancel(), cms_prep_del(), and tape_stage_delete().
brix_stage_request_reap_expired()
ngx_uint_t brix_stage_request_reap_expired (brix_stage_registry_t * reg, time_t now, ngx_log_t * log)
Definition at line 257 of file stage_request_registry_mutate.c.
References log, srq_file_size(), SRQ_LK_EXCL, srq_lock(), SRQ_REC_OFF, srq_rec_read(), SRQ_REC_SIZE, srq_rec_valid(), srq_rec_write(), SRQ_ST_FREE, srq_unlock(), srq_rec_t::status, and srq_rec_t::tod_expire.
brix_stage_request_reqid_generate()
ngx_int_t brix_stage_request_reqid_generate (brix_stage_registry_t * reg, char * reqid_out, size_t reqid_out_sz, ngx_log_t * log)
Definition at line 30 of file stage_request_registry_mutate.c.
References log, srq_hdr_t::seq, srq_hdr_read(), srq_hdr_write(), SRQ_LK_EXCL, srq_lock(), srq_reqid_format(), SRQ_REQID_LEN, and srq_unlock().
brix_stage_request_set_status()
ngx_int_t brix_stage_request_set_status (brix_stage_registry_t * reg, const char * reqid, brix_stage_req_status_t status, ngx_log_t * log)
Definition at line 187 of file stage_request_registry_mutate.c.
References log, SRQ_LK_EXCL, srq_lock(), srq_offset_by_reqid(), srq_rec_read(), srq_rec_valid(), srq_rec_write(), SRQ_ST_FREE, srq_status_on_disk(), srq_unlock(), srq_rec_t::status, and srq_rec_t::tod_status.
Referenced by brix_stage_request_cancel().
srq_add_validate_args()
static ngx_int_t srq_add_validate_args (brix_stage_registry_t * reg, const brix_stage_request_view_t * view, const char * reqid_out, size_t reqid_out_sz, ngx_log_t * log) static
Definition at line 78 of file stage_request_registry_mutate.c.
References brix_stage_request_view_t::lfn, log, SRQ_LFN_LEN, and SRQ_REQID_LEN.
Referenced by brix_stage_request_add().
srq_rec_populate_from_view()
static void srq_rec_populate_from_view (srq_rec_t * rec, const brix_stage_request_view_t * view, const char * host, uint64_t seq, int64_t off, time_t now) static
Definition at line 111 of file stage_request_registry_mutate.c.
References brix_stage_request_view_t::cs_type, srq_rec_t::cs_type, brix_stage_request_view_t::cs_value, srq_rec_t::cs_value, host, brix_stage_request_view_t::lfn, srq_rec_t::lfn, srq_rec_t::lfn_url_off, srq_rec_t::opaque_off, srq_rec_t::reqid, brix_stage_request_view_t::requester_dn, srq_rec_t::requester_dn, srq_rec_t::self, srq_reqid_format(), SRQ_ST_QUEUED, srq_rec_t::status, srq_rec_t::tod_added, brix_stage_request_view_t::tod_expire, srq_rec_t::tod_expire, srq_rec_t::tod_status, brix_stage_request_view_t::user, and srq_rec_t::user.
Referenced by brix_stage_request_add().