nginx-xrootd: src/fs/cache/stage_admit.c File Reference
stage_admit.c File Reference
#include "cache_internal.h"
#include "stage_admit.h"
#include "evict_internal.h"
#include "observability/metrics/unified.h"
Functions
brix_wt_admit_t brix_wt_stage_admit (const ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_wt_stage_admit()
brix_wt_admit_t brix_wt_stage_admit (const ngx_stream_brix_srv_conf_t * conf)
Definition at line 19 of file stage_admit.c.
References brix_cache_fs_usage_sampled(), brix_metric_wt_stage_usage_ratio(), BRIX_WT_ADMIT_ALLOW, brix_wt_stage_decide(), and usage().
Referenced by brix_open_stage_backpressure().