nginx-xrootd: src/net/upstream/start.c File Reference
start.c File Reference
#include "upstream_internal.h"
#include "protocols/root/connection/netconnect.h"
#include <netdb.h>
#include <sys/socket.h>
Functions
static ngx_int_t brix_upstream_start_snapshot_request (brix_ctx_t *ctx, ngx_connection_t *c, brix_upstream_t **out_up)
static int brix_upstream_start_resolve_socket (ngx_stream_brix_srv_conf_t *conf, struct sockaddr_storage *addr, socklen_t *addrlen, ngx_int_t *dns_failed)
static ngx_connection_t * brix_upstream_start_wrap_conn (int fd, brix_upstream_t *up, ngx_log_t *log)
static ngx_int_t brix_upstream_start_build_wbuf (brix_upstream_t *up, ngx_connection_t *uconn)
static ngx_int_t brix_upstream_start_connect (brix_upstream_t *up, ngx_connection_t *uconn, ngx_stream_brix_srv_conf_t *conf, const struct sockaddr_storage *addr, socklen_t addrlen)
ngx_int_t brix_upstream_start (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_upstream_start()
ngx_int_t brix_upstream_start (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 290 of file start.c.
References brix_upstream_cleanup(), brix_upstream_start_build_wbuf(), brix_upstream_start_connect(), brix_upstream_start_resolve_socket(), brix_upstream_start_snapshot_request(), brix_upstream_start_wrap_conn(), c, brix_ctx_t::state, XRD_ST_REQ_HEADER, XRD_ST_UPSTREAM, and XRD_UP_CONNECTING.
Referenced by brix_open_read_resolve(), and locate_check_data_server().
brix_upstream_start_build_wbuf()
static ngx_int_t brix_upstream_start_build_wbuf (brix_upstream_t * up, ngx_connection_t * uconn) static
Definition at line 199 of file start.c.
References brix_upstream_build_bootstrap(), and XRD_HANDSHAKE_LEN.
Referenced by brix_upstream_start().
brix_upstream_start_connect()
static ngx_int_t brix_upstream_start_connect (brix_upstream_t * up, ngx_connection_t * uconn, ngx_stream_brix_srv_conf_t * conf, const struct sockaddr_storage * addr, socklen_t addrlen) static
Definition at line 237 of file start.c.
References brix_upstream_flush(), XRD_UP_BOOTSTRAP, and XRD_UP_BS_HANDSHAKE.
Referenced by brix_upstream_start().
brix_upstream_start_resolve_socket()
static int brix_upstream_start_resolve_socket (ngx_stream_brix_srv_conf_t * conf, struct sockaddr_storage * addr, socklen_t * addrlen, ngx_int_t * dns_failed) static
Definition at line 100 of file start.c.
References BRIX_AF_AUTO, brix_resolve_connect_socket(), BRIX_RESOLVE_ERR_DNS, and ngx_memcpy.
Referenced by brix_upstream_start().
brix_upstream_start_snapshot_request()
static ngx_int_t brix_upstream_start_snapshot_request (brix_ctx_t * ctx, ngx_connection_t * c, brix_upstream_t ** out_up) static
Definition at line 35 of file start.c.
References brix_extract_path(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, brix_ctx_recv_t::cur_streamid, brix_ctx_recv_t::hdr_buf, kXR_locate, kXR_open, xrdw_open_req_t::mode, ngx_pcalloc(), xrdw_locate_req_t::options, xrdw_open_req_t::options, brix_ctx_recv_t::payload, brix_ctx_t::recv, brix_ctx_t::upstream, xrdw_locate_req_unpack(), and xrdw_open_req_unpack().
Referenced by brix_upstream_start().
brix_upstream_start_wrap_conn()
static ngx_connection_t * brix_upstream_start_wrap_conn (int fd, brix_upstream_t * up, ngx_log_t * log) static
Definition at line 153 of file start.c.
References brix_upstream_read_handler(), brix_upstream_write_handler(), and log.
Referenced by brix_upstream_start().