nginx-xrootd: src/protocols/root/path/stat_body.c File Reference
stat_body.c File Reference
#include "core/ngx_brix_module.h"
#include "protocols/root/protocol/stat_line.h"
#include "protocols/root/protocol/stat_flags.h"
#include <stdio.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
Functions
void brix_make_stat_body (const struct stat *st, ngx_flag_t is_vfs, int extra_flags, char *out, size_t outsz)
Function Documentation
brix_make_stat_body()
void brix_make_stat_body (const struct stat * st, ngx_flag_t is_vfs, int extra_flags, char * out, size_t outsz)
Definition at line 17 of file stat_body.c.
References brix_stat_flags_from_stat(), brix_statline_format(), and kXR_readable.
Referenced by brix_dirlist_entry_meta(), brix_handle_stat(), brix_vfs_io_dirlist_stat_entry(), and stat_manager_route().