nginx-xrootd: src/protocols/root/read/statx.c File Reference
statx.c File Reference
#include "statx.h"
#include "stat.h"
#include "core/ngx_brix_module.h"
#include "protocols/root/path/op_path.h"
#include "fs/path/beneath.h"
#include "fs/path/reserved_names.h"
#include "core/compat/alloc_guard.h"
#include <stdlib.h>
Data Structures
struct brix_statx_rsp_t
Macros
#define BRIX_STATX_MAX_PATHS 256
#define BRIX_STATX_BUF_MAX BRIX_STATX_MAX_PATHS
Functions
static ngx_flag_t brix_statx_next_path (const u_char **cursor, const u_char *end, char *path, size_t path_size)
static int brix_statx_symlink_fallback_stat (brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *conf, ngx_connection_t *c, const char *full_path, struct stat *st)
static ngx_int_t brix_statx_path_authorized (brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *conf, ngx_connection_t *c, const char *full_path, const char *reqpath_buf)
static u_char brix_statx_compute_flag (ngx_stream_brix_srv_conf_t *conf, ngx_connection_t *c, const char *full_path, const struct stat *st)
static ngx_int_t brix_statx_process_path (brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *conf, ngx_connection_t *c, const char *reqpath_buf, brix_statx_rsp_t *rsp)
ngx_int_t brix_handle_statx (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Macro Definition Documentation
BRIX_STATX_BUF_MAX
#define BRIX_STATX_BUF_MAX BRIX_STATX_MAX_PATHS
Definition at line 22 of file statx.c.
BRIX_STATX_MAX_PATHS
#define BRIX_STATX_MAX_PATHS 256
Definition at line 15 of file statx.c.
Function Documentation
brix_handle_statx()
ngx_int_t brix_handle_statx (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 235 of file statx.c.
References brix_log_access(), BRIX_MAX_PATH, BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_STATX, BRIX_PALLOC_OR_RETURN, brix_send_error(), brix_send_ok(), BRIX_STATX_BUF_MAX, BRIX_STATX_MAX_PATHS, brix_statx_next_path(), brix_statx_process_path(), c, brix_ctx_recv_t::cur_dlen, brix_statx_rsp_t::end, kXR_ArgMissing, brix_ctx_recv_t::payload, brix_statx_rsp_t::ptr, and brix_ctx_t::recv.
Referenced by brix_dispatch_read_opcode().
brix_statx_compute_flag()
static u_char brix_statx_compute_flag (ngx_stream_brix_srv_conf_t * conf, ngx_connection_t * c, const char * full_path, const struct stat * st) static
Definition at line 153 of file statx.c.
References BRIX_PROTO_ROOT, BRIX_SD_RES_NEARLINE, BRIX_SD_RES_OFFLINE, brix_vfs_ctx_init(), brix_vfs_residency(), c, kXR_file, kXR_isDir, kXR_offline, and brix_vfs_ctx_t::pool.
Referenced by brix_statx_process_path().
brix_statx_next_path()
static ngx_flag_t brix_statx_next_path (const u_char ** cursor, const u_char * end, char * path, size_t path_size) static
Definition at line 35 of file statx.c.
References ngx_memcpy.
Referenced by brix_handle_statx().
brix_statx_path_authorized()
static ngx_int_t brix_statx_path_authorized (brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * conf, ngx_connection_t * c, const char * full_path, const char * reqpath_buf) static
Definition at line 128 of file statx.c.
References BRIX_AUTH_LOOKUP, brix_check_authdb(), brix_check_token_scope(), brix_check_vo_acl_identity(), c, and brix_ctx_t::identity.
Referenced by brix_statx_process_path().
brix_statx_process_path()
static ngx_int_t brix_statx_process_path (brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * conf, ngx_connection_t * c, const char * reqpath_buf, brix_statx_rsp_t * rsp) static
Definition at line 193 of file statx.c.
References brix_beneath_full_path(), brix_is_internal_name(), brix_kxr_from_errno(), BRIX_OP_STATX, BRIX_RETURN_ERR, brix_stat_beneath(), brix_statx_compute_flag(), brix_statx_path_authorized(), brix_statx_symlink_fallback_stat(), c, brix_statx_rsp_t::end, kXR_NotAuthorized, kXR_NotFound, PATH_MAX, brix_statx_rsp_t::ptr, and stat().
Referenced by brix_handle_statx().
brix_statx_symlink_fallback_stat()
static int brix_statx_symlink_fallback_stat (brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * conf, ngx_connection_t * c, const char * full_path, struct stat * st) static
Definition at line 78 of file statx.c.
References BRIX_PROTO_ROOT, brix_root_vfs_bind_deleg(), brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), brix_vfs_probe(), brix_vfs_to_struct_stat(), c, brix_ctx_t::identity, PATH_MAX, and brix_vfs_ctx_t::pool.
Referenced by brix_statx_process_path().