nginx-xrootd: src/protocols/root/read/statx.h File Reference
statx.h File Reference
#include "core/ngx_brix_module.h"
Functions
ngx_int_t brix_handle_statx (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_handle_statx()
ngx_int_t brix_handle_statx (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 241 of file statx.c.
References brix_log_access(), BRIX_MAX_PATH, BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_STATX, BRIX_PALLOC_OR_RETURN, brix_send_error(), brix_send_ok(), BRIX_STATX_BUF_MAX, BRIX_STATX_MAX_PATHS, brix_statx_next_path(), brix_statx_process_path(), c, brix_ctx_recv_t::cur_dlen, brix_statx_rsp_t::end, kXR_ArgMissing, brix_ctx_recv_t::payload, brix_statx_rsp_t::ptr, and brix_ctx_t::recv.
Referenced by brix_dispatch_read_opcode().