nginx-xrootd: src/protocols/root/read/stat.c File Reference
stat.c File Reference
#include "core/ngx_brix_module.h"
#include "stat.h"
#include "net/cms/cns.h"
#include "fs/vfs/vfs.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "fs/path/reserved_names.h"
#include "protocols/root/path/op_path.h"
#include "core/negcache/negcache.h"
#include "net/manager/registry.h"
#include "net/manager/pending.h"
#include "net/cms/cms_internal.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <spawn.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/statvfs.h>
Data Structures
struct stat_target_t
Functions
static void brix_make_vfs_body (ngx_stream_brix_srv_conf_t *conf, char *out, size_t outsz)
void brix_vfs_to_struct_stat (const brix_vfs_stat_t *v, struct stat *st)
int brix_cache_path_flag (const ngx_stream_brix_srv_conf_t *conf, const char *reqpath)
static void stat_vfs_ctx_prepare (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *path, brix_vfs_ctx_t *vctx)
static int stat_manager_route (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *reqpath, ngx_int_t *rc)
static int stat_symlink_follow_fallback (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, stat_target_t *tgt)
static int stat_vfs_query (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, stat_target_t *tgt)
static int stat_residency_flags (ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *full_path)
static int stat_query_path (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, stat_target_t *tgt, ngx_int_t *rc)
static int stat_query_handle (brix_ctx_t *ctx, ngx_connection_t *c, stat_target_t *tgt, ngx_int_t *rc)
ngx_int_t brix_handle_stat (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Variables
char ** environ
Function Documentation
brix_cache_path_flag()
int brix_cache_path_flag (const ngx_stream_brix_srv_conf_t * conf, const char * reqpath)
Definition at line 107 of file stat.c.
References kXR_cachersp, PATH_MAX, and stat().
Referenced by stat_query_path().
brix_handle_stat()
ngx_int_t brix_handle_stat (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 559 of file stat.c.
References brix_log_access(), brix_make_stat_body(), brix_make_vfs_body(), BRIX_MAX_PATH, BRIX_OP_OK, BRIX_OP_STAT, brix_send_ok(), c, brix_ctx_recv_t::cur_dlen, stat_target_t::extra_flags, stat_target_t::full_path, stat_target_t::full_path_size, brix_ctx_recv_t::hdr_buf, kXR_vfs, xrdw_stat_req_t::options, PATH_MAX, brix_ctx_recv_t::payload, brix_ctx_t::recv, stat_target_t::req, stat_target_t::reqpath, stat_target_t::reqpath_buf, stat_target_t::reqpath_size, stat_target_t::st, stat(), stat_query_handle(), stat_query_path(), and xrdw_stat_req_unpack().
Referenced by brix_dispatch_read_opcode().
brix_make_vfs_body()
static void brix_make_vfs_body (ngx_stream_brix_srv_conf_t * conf, char * out, size_t outsz) static
Definition at line 31 of file stat.c.
References brix_vfs_backend_resolve(), brix_sd_space_t::free_bytes, and brix_sd_space_t::total_bytes.
Referenced by brix_handle_stat().
brix_vfs_to_struct_stat()
void brix_vfs_to_struct_stat (const brix_vfs_stat_t * v, struct stat * st)
Definition at line 90 of file stat.c.
References brix_vfs_stat_t::blocks, brix_vfs_stat_t::ctime, brix_vfs_stat_t::dev, brix_vfs_stat_t::gid, brix_vfs_stat_t::ino, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, brix_vfs_stat_t::size, and brix_vfs_stat_t::uid.
Referenced by brix_statx_symlink_fallback_stat(), stat_symlink_follow_fallback(), and stat_vfs_query().
stat_manager_route()
static int stat_manager_route (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * reqpath, ngx_int_t * rc) static
Definition at line 187 of file stat.c.
References BRIX_BAIL_ERR, BRIX_CNS_COLLECT, brix_cns_stat(), brix_find_manager_map(), brix_log_access(), brix_make_stat_body(), brix_manager_tried_exhausted(), BRIX_OP_OK, BRIX_OP_STAT, brix_pending_insert(), brix_pending_remove(), brix_send_ok(), brix_send_redirect(), brix_srv_select_or_blacklisted(), c, brix_ctx_t::cms_wait_streamid, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_streamid, brix_manager_map_t::host, kXR_NotFound, kXR_ok, ngx_brix_cms_next_streamid(), ngx_brix_cms_send_locate(), brix_ctx_recv_t::payload, brix_manager_map_t::port, brix_ctx_t::recv, stat(), brix_ctx_t::state, XRD_ST_REQ_HEADER, and XRD_ST_WAITING_CMS.
Referenced by stat_query_path().
stat_query_handle()
static int stat_query_handle (brix_ctx_t * ctx, ngx_connection_t * c, stat_target_t * tgt, ngx_int_t * rc) static
Definition at line 482 of file stat.c.
References BRIX_BAIL_ERR, BRIX_OP_STAT, brix_sd_default_driver(), brix_validate_file_handle(), c, brix_file_t::cached_size, brix_sd_stat_t::ctime, stat_target_t::extra_flags, brix_file_t::fd, xrdw_stat_req_t::fhandle, brix_ctx_t::files, brix_file_t::from_cache, fstat(), stat_target_t::full_path, stat_target_t::full_path_size, brix_sd_stat_t::ino, brix_sd_stat_t::is_dir, kXR_cachersp, kXR_IOError, brix_sd_stat_t::mode, brix_sd_stat_t::mtime, brix_file_t::path, stat_target_t::req, brix_file_t::sd_obj, brix_sd_stat_t::size, stat_target_t::st, stat(), and brix_file_t::zip_mode.
Referenced by brix_handle_stat().
stat_query_path()
static int stat_query_path (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, stat_target_t * tgt, ngx_int_t * rc) static
Definition at line 403 of file stat.c.
References brix_auth_gate(), BRIX_AUTH_LOOKUP, BRIX_BAIL_ERR, brix_beneath_full_path(), brix_cache_path_flag(), brix_extract_path(), brix_is_internal_name(), brix_kxr_from_errno(), brix_negcache_note_miss(), BRIX_OP_ERR, BRIX_OP_STAT, brix_reject_dotdot_path(), brix_send_wait(), c, brix_ctx_recv_t::cur_dlen, stat_target_t::extra_flags, stat_target_t::full_path, stat_target_t::full_path_size, kXR_ArgInvalid, kXR_NotFound, brix_ctx_recv_t::payload, brix_ctx_t::recv, stat_target_t::reqpath, stat_target_t::reqpath_buf, stat_target_t::reqpath_size, stat_manager_route(), stat_residency_flags(), stat_vfs_query(), and brix_ctx_t::write_rc.
Referenced by brix_handle_stat().
stat_residency_flags()
static int stat_residency_flags (ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * full_path) static
Definition at line 371 of file stat.c.
References BRIX_PROTO_ROOT, BRIX_SD_RES_NEARLINE, BRIX_SD_RES_OFFLINE, brix_vfs_ctx_init(), brix_vfs_residency(), c, kXR_bkpexist, kXR_offline, and brix_vfs_ctx_t::pool.
Referenced by stat_query_path().
stat_symlink_follow_fallback()
static int stat_symlink_follow_fallback (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, stat_target_t * tgt) static
Definition at line 295 of file stat.c.
References brix_vfs_probe(), brix_vfs_to_struct_stat(), c, stat_target_t::full_path, PATH_MAX, stat_target_t::st, and stat_vfs_ctx_prepare().
Referenced by stat_vfs_query().
stat_vfs_ctx_prepare()
static void stat_vfs_ctx_prepare (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * path, brix_vfs_ctx_t * vctx) static
Definition at line 160 of file stat.c.
References BRIX_PROTO_ROOT, brix_root_vfs_bind_deleg(), brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), c, brix_ctx_t::identity, and brix_vfs_ctx_t::pool.
Referenced by stat_symlink_follow_fallback(), and stat_vfs_query().
stat_vfs_query()
static int stat_vfs_query (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, stat_target_t * tgt) static
Definition at line 335 of file stat.c.
References brix_vfs_statf(), brix_vfs_to_struct_stat(), c, stat_target_t::full_path, kXR_statNoFollow, xrdw_stat_req_t::options, stat_target_t::req, stat_target_t::st, stat_symlink_follow_fallback(), and stat_vfs_ctx_prepare().
Referenced by stat_query_path().
Variable Documentation
environ
char** environ extern