nginx-xrootd: src/protocols/root/read/stat_internal.h File Reference
stat_internal.h File Reference
#include "core/ngx_brix_module.h"
Functions
int stat_manager_route (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *reqpath, ngx_int_t *rc)
Function Documentation
stat_manager_route()
int stat_manager_route (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * reqpath, ngx_int_t * rc)
Definition at line 36 of file stat_manager.c.
References BRIX_BAIL_ERR, BRIX_CNS_COLLECT, brix_cns_stat(), brix_find_manager_map(), brix_log_access(), brix_make_stat_body(), brix_manager_tried_exhausted(), BRIX_OP_OK, BRIX_OP_STAT, brix_pending_insert(), brix_pending_remove(), brix_send_ok(), brix_send_redirect(), brix_srv_select_or_blacklisted(), c, brix_ctx_t::cms_wait_streamid, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_streamid, brix_manager_map_t::host, kXR_NotFound, kXR_ok, ngx_brix_cms_next_streamid(), ngx_brix_cms_send_locate(), brix_ctx_recv_t::payload, brix_manager_map_t::port, brix_ctx_t::recv, stat(), brix_ctx_t::state, XRD_ST_REQ_HEADER, and XRD_ST_WAITING_CMS.
Referenced by stat_query_path().