nginx-xrootd: src/protocols/root/protocol/stat_flags.h File Reference
stat_flags.h File Reference
#include <sys/stat.h>
#include "flags.h"
Functions
static int brix_stat_flags_from_mode (mode_t st_mode, int extra_flags)
static int brix_stat_perm_granted (mode_t m, mode_t ubit, mode_t gbit, mode_t obit, uid_t myuid, gid_t mygid, uid_t fuid, gid_t fgid)
static int brix_stat_type_flag (mode_t m)
static int brix_stat_flags_from_stat (const struct stat *st, uid_t myuid, gid_t mygid, int extra_flags)
static mode_t brix_stat_mode_from_flags (int flags, int allow_symlink)
Function Documentation
brix_stat_flags_from_mode()
static int brix_stat_flags_from_mode (mode_t st_mode, int extra_flags) inline static
Definition at line 42 of file stat_flags.h.
References kXR_isDir, kXR_other, and kXR_readable.
brix_stat_flags_from_stat()
static int brix_stat_flags_from_stat (const struct stat * st, uid_t myuid, gid_t mygid, int extra_flags) inline static
Definition at line 120 of file stat_flags.h.
References brix_stat_perm_granted(), brix_stat_type_flag(), kXR_readable, kXR_writable, and kXR_xset.
Referenced by brix_make_stat_body(), and brix_open_build_retstat().
brix_stat_mode_from_flags()
static mode_t brix_stat_mode_from_flags (int flags, int allow_symlink) inline static
Definition at line 156 of file stat_flags.h.
References kXR_isDir, kXR_other, and kXR_xset.
Referenced by brix_statinfo_to_stat().
brix_stat_perm_granted()
static int brix_stat_perm_granted (mode_t m, mode_t ubit, mode_t gbit, mode_t obit, uid_t myuid, gid_t mygid, uid_t fuid, gid_t fgid) inline static
Definition at line 71 of file stat_flags.h.
Referenced by brix_stat_flags_from_stat().
brix_stat_type_flag()
static int brix_stat_type_flag (mode_t m) inline static
Definition at line 95 of file stat_flags.h.
References kXR_isDir, and kXR_other.
Referenced by brix_stat_flags_from_stat().