nginx-xrootd: src/protocols/root/read/stat.h File Reference
stat.h File Reference
#include "fs/vfs/vfs.h"
#include <sys/stat.h>
Functions
ngx_int_t brix_handle_stat (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
int brix_cache_path_flag (const ngx_stream_brix_srv_conf_t *conf, const char *reqpath)
void brix_vfs_to_struct_stat (const brix_vfs_stat_t *v, struct stat *st)
Function Documentation
brix_cache_path_flag()
int brix_cache_path_flag (const ngx_stream_brix_srv_conf_t * conf, const char * reqpath)
Definition at line 108 of file stat.c.
References kXR_cachersp, PATH_MAX, and stat().
Referenced by stat_query_path().
brix_handle_stat()
ngx_int_t brix_handle_stat (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 450 of file stat.c.
References brix_log_access(), brix_make_stat_body(), brix_make_vfs_body(), BRIX_MAX_PATH, BRIX_OP_OK, BRIX_OP_STAT, brix_send_ok(), c, brix_ctx_recv_t::cur_dlen, stat_target_t::extra_flags, stat_target_t::full_path, stat_target_t::full_path_size, brix_ctx_recv_t::hdr_buf, kXR_vfs, xrdw_stat_req_t::options, PATH_MAX, brix_ctx_recv_t::payload, brix_ctx_t::recv, stat_target_t::req, stat_target_t::reqpath, stat_target_t::reqpath_buf, stat_target_t::reqpath_size, stat_target_t::st, stat(), stat_query_handle(), stat_query_path(), and xrdw_stat_req_unpack().
Referenced by brix_dispatch_read_opcode().
brix_vfs_to_struct_stat()
void brix_vfs_to_struct_stat (const brix_vfs_stat_t * v, struct stat * st)
Definition at line 91 of file stat.c.
References brix_vfs_stat_t::blocks, brix_vfs_stat_t::ctime, brix_vfs_stat_t::dev, brix_vfs_stat_t::gid, brix_vfs_stat_t::ino, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, brix_vfs_stat_t::size, and brix_vfs_stat_t::uid.
Referenced by brix_statx_symlink_fallback_stat(), stat_symlink_follow_fallback(), and stat_vfs_query().