nginx-xrootd: src/auth/crypto/store_policy_conformance.c File Reference
store_policy_conformance.c File Reference
#include "auth/crypto/store_policy.h"
#include "store_policy_internal.h"
#include <openssl/bn.h>
#include <openssl/evp.h>
#include <openssl/objects.h>
#include <openssl/x509v3.h>
#include <dirent.h>
#include <fcntl.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/stat.h>
#include <unistd.h>
Functions
brix_px_kind_t brix_px_classify (X509 *cert)
int brix_proxy_chain_ok (STACK_OF(X509) *chain)
static int brix_dn_has_control_bytes (X509_NAME *nm)
static int brix_key_strength_violation (X509 *cert)
static int brix_sig_alg_violation (X509 *cert)
static int brix_serial_violation (X509 *cert, int is_proxy)
int brix_cert_policy_violation (X509 *cert)
int brix_leaf_purpose_violation (X509 *leaf)
int brix_proxy_pci_ok (STACK_OF(X509) *chain)
Variables
static const char * BRIX_PX_LIMITED_OID = "1.3.6.1.4.1.3536.1.1.1.9"
static const char * BRIX_PX_OID_IMPERSONATION = "1.3.6.1.5.5.7.21.1"
static const char * BRIX_PX_OID_INDEPENDENT = "1.3.6.1.5.5.7.21.2"
Function Documentation
brix_cert_policy_violation()
int brix_cert_policy_violation (X509 * cert)
Definition at line 204 of file store_policy_conformance.c.
References brix_dn_has_control_bytes(), brix_key_strength_violation(), brix_serial_violation(), and brix_sig_alg_violation().
Referenced by brix_gsi_enforce_cert_policy().
brix_dn_has_control_bytes()
static int brix_dn_has_control_bytes (X509_NAME * nm) static
Definition at line 106 of file store_policy_conformance.c.
References s.
Referenced by brix_cert_policy_violation().
brix_key_strength_violation()
static int brix_key_strength_violation (X509 * cert) static
Definition at line 133 of file store_policy_conformance.c.
Referenced by brix_cert_policy_violation().
brix_leaf_purpose_violation()
int brix_leaf_purpose_violation (X509 * leaf)
Definition at line 234 of file store_policy_conformance.c.
Referenced by brix_gsi_enforce_cert_policy().
brix_proxy_chain_ok()
int brix_proxy_chain_ok (STACK_OF(X509) * chain)
Definition at line 76 of file store_policy_conformance.c.
References brix_px_classify(), BRIX_PX_FULL, and BRIX_PX_LIMITED.
Referenced by brix_gsi_enforce_proxy_monotonicity().
brix_proxy_pci_ok()
int brix_proxy_pci_ok (STACK_OF(X509) * chain)
Definition at line 267 of file store_policy_conformance.c.
References BRIX_PX_LIMITED_OID, BRIX_PX_OID_IMPERSONATION, and BRIX_PX_OID_INDEPENDENT.
Referenced by brix_gsi_enforce_cert_policy().
brix_px_classify()
brix_px_kind_t brix_px_classify (X509 * cert)
Definition at line 31 of file store_policy_conformance.c.
References BRIX_PX_FULL, BRIX_PX_LIMITED, BRIX_PX_LIMITED_OID, BRIX_PX_NONE, and s.
Referenced by brix_proxy_chain_ok(), delegated_cred_find_eec(), and delegation_find_eec().
brix_serial_violation()
static int brix_serial_violation (X509 * cert, int is_proxy) static
Definition at line 188 of file store_policy_conformance.c.
Referenced by brix_cert_policy_violation().
brix_sig_alg_violation()
static int brix_sig_alg_violation (X509 * cert) static
Definition at line 164 of file store_policy_conformance.c.
Referenced by brix_cert_policy_violation().
Variable Documentation
BRIX_PX_LIMITED_OID
const char* BRIX_PX_LIMITED_OID = "1.3.6.1.4.1.3536.1.1.1.9" static
Definition at line 28 of file store_policy_conformance.c.
Referenced by brix_proxy_pci_ok(), and brix_px_classify().
BRIX_PX_OID_IMPERSONATION
const char* BRIX_PX_OID_IMPERSONATION = "1.3.6.1.5.5.7.21.1" static
Definition at line 101 of file store_policy_conformance.c.
Referenced by brix_proxy_pci_ok().
BRIX_PX_OID_INDEPENDENT
const char* BRIX_PX_OID_INDEPENDENT = "1.3.6.1.5.5.7.21.2" static
Definition at line 102 of file store_policy_conformance.c.
Referenced by brix_proxy_pci_ok().