nginx-xrootd: client/apps/scan/storascan_core.h File Reference
storascan_core.h File Reference
#include <stddef.h>
#include <stdint.h>
Data Structures
struct storascan_bench_result
Enumerations
enum storascan_cks_status { STORASCAN_CKS_MATCH = 0 , STORASCAN_CKS_MISMATCH , STORASCAN_CKS_MISSING }
Functions
storascan_cks_status storascan_cks_compare (const char *computed_hex, const char *stored_hex)
double storascan_percentile_ms (const double *sorted_ms, size_t n, double pct)
void storascan_bench_compute (const double *lat_ms, size_t n, uint64_t bytes, double elapsed_s, storascan_bench_result *out)
Enumeration Type Documentation
storascan_cks_status
enum storascan_cks_status
Enumerator
STORASCAN_CKS_MATCH
STORASCAN_CKS_MISMATCH
STORASCAN_CKS_MISSING
Definition at line 21 of file storascan_core.h.
Function Documentation
storascan_bench_compute()
void storascan_bench_compute (const double * lat_ms, size_t n, uint64_t bytes, double elapsed_s, storascan_bench_result * out)
Definition at line 117 of file storascan_core.c.
References storascan_bench_result::bytes, ckv_cmp_double(), storascan_bench_result::elapsed_s, storascan_bench_result::iops, storascan_bench_result::ops, storascan_bench_result::p50_ms, storascan_bench_result::p95_ms, storascan_bench_result::p99_ms, storascan_percentile_ms(), and storascan_bench_result::throughput_mibps.
Referenced by bench_workers_compute(), and test_bench_compute().
storascan_cks_compare()
storascan_cks_status storascan_cks_compare (const char * computed_hex, const char * stored_hex)
Definition at line 39 of file storascan_core.c.
References ckv_skip_ws(), ckv_trimmed_len(), STORASCAN_CKS_MATCH, STORASCAN_CKS_MISMATCH, and STORASCAN_CKS_MISSING.
Referenced by cmd_verify(), and test_cks_compare().
storascan_percentile_ms()
double storascan_percentile_ms (const double * sorted_ms, size_t n, double pct)
Definition at line 73 of file storascan_core.c.
Referenced by storascan_bench_compute(), and test_percentile().