nginx-xrootd: src/auth/crypto/store_policy.h File Reference
store_policy.h File Reference
#include "auth/crypto/signing_policy.h"
#include <openssl/x509.h>
#include <openssl/x509_vfy.h>
Macros
#define BRIX_CRL_MODE_OFF 0 /* never set CRL verify flags */
#define BRIX_CRL_MODE_TRY 1 /* check where a CRL exists; missing = ok */
#define BRIX_CRL_MODE_REQUIRE 2 /* missing/expired/unverifiable CRL = reject */
#define BRIX_SP_LOG_WARN 1
#define BRIX_SP_LOG_INFO 2
Typedefs
typedef void(* brix_sp_log_fn) (void *log, int level, const char *msg)
Enumerations
enum brix_px_kind_t { BRIX_PX_NONE , BRIX_PX_FULL , BRIX_PX_LIMITED }
Functions
brix_sp_table_t * brix_sp_table_build (const char *cadir, void *log, brix_sp_log_fn log_fn)
void brix_sp_table_free (brix_sp_table_t *t)
int brix_sp_table_check (const brix_sp_table_t *t, brix_sp_mode_t mode, X509 *ca, X509 *subject)
int brix_store_policy_attach (X509_STORE *store, brix_sp_table_t *table, brix_sp_mode_t sp_mode, int crl_mode)
int brix_store_configure (X509_STORE *store, const char *cadir, unsigned long extra_flags, int crl_count, brix_sp_mode_t sp_mode, int crl_mode, void *log, brix_sp_log_fn log_fn)
brix_sp_table_t * brix_store_policy_table (X509_STORE_CTX *ctx)
brix_sp_mode_t brix_store_policy_mode (X509_STORE_CTX *ctx)
int brix_store_crl_mode (X509_STORE_CTX *ctx)
char * brix_x509_oneline (X509_NAME *name, char *buf, size_t buflen)
brix_px_kind_t brix_px_classify (X509 *cert)
int brix_cert_policy_violation (X509 *cert)
int brix_leaf_purpose_violation (X509 *leaf)
int brix_proxy_pci_ok (STACK_OF(X509) *chain)
int brix_proxy_chain_ok (STACK_OF(X509) *chain)
Macro Definition Documentation
BRIX_CRL_MODE_OFF
#define BRIX_CRL_MODE_OFF 0 /* never set CRL verify flags */
Definition at line 26 of file store_policy.h.
BRIX_CRL_MODE_REQUIRE
#define BRIX_CRL_MODE_REQUIRE 2 /* missing/expired/unverifiable CRL = reject */
Definition at line 28 of file store_policy.h.
BRIX_CRL_MODE_TRY
#define BRIX_CRL_MODE_TRY 1 /* check where a CRL exists; missing = ok */
Definition at line 27 of file store_policy.h.
BRIX_SP_LOG_INFO
#define BRIX_SP_LOG_INFO 2
Definition at line 34 of file store_policy.h.
BRIX_SP_LOG_WARN
#define BRIX_SP_LOG_WARN 1
Definition at line 33 of file store_policy.h.
Typedef Documentation
brix_sp_log_fn
typedef void(* brix_sp_log_fn) (void *log, int level, const char *msg)
Definition at line 35 of file store_policy.h.
Enumeration Type Documentation
brix_px_kind_t
enum brix_px_kind_t
Enumerator
BRIX_PX_NONE
BRIX_PX_FULL
BRIX_PX_LIMITED
Definition at line 104 of file store_policy.h.
Function Documentation
brix_cert_policy_violation()
int brix_cert_policy_violation (X509 * cert)
Definition at line 204 of file store_policy_conformance.c.
References brix_dn_has_control_bytes(), brix_key_strength_violation(), brix_serial_violation(), and brix_sig_alg_violation().
Referenced by brix_gsi_enforce_cert_policy().
brix_leaf_purpose_violation()
int brix_leaf_purpose_violation (X509 * leaf)
Definition at line 234 of file store_policy_conformance.c.
Referenced by brix_gsi_enforce_cert_policy().
brix_proxy_chain_ok()
int brix_proxy_chain_ok (STACK_OF(X509) * chain)
Definition at line 76 of file store_policy_conformance.c.
References brix_px_classify(), BRIX_PX_FULL, and BRIX_PX_LIMITED.
Referenced by brix_gsi_enforce_proxy_monotonicity().
brix_proxy_pci_ok()
int brix_proxy_pci_ok (STACK_OF(X509) * chain)
Definition at line 267 of file store_policy_conformance.c.
References BRIX_PX_LIMITED_OID, BRIX_PX_OID_IMPERSONATION, and BRIX_PX_OID_INDEPENDENT.
Referenced by brix_gsi_enforce_cert_policy().
brix_px_classify()
brix_px_kind_t brix_px_classify (X509 * cert)
Definition at line 31 of file store_policy_conformance.c.
References BRIX_PX_FULL, BRIX_PX_LIMITED, BRIX_PX_LIMITED_OID, BRIX_PX_NONE, and s.
Referenced by brix_proxy_chain_ok(), delegated_cred_find_eec(), and delegation_find_eec().
brix_sp_table_build()
brix_sp_table_t * brix_sp_table_build (const char * cadir, void * log, brix_sp_log_fn log_fn)
Definition at line 138 of file store_policy.c.
References brix_sp_free(), BRIX_SP_LOG_WARN, brix_sp_parse(), brix_sp_entry_t::hash, brix_sp_entry_t::have_hash, log, brix_sp_entry_t::malformed, name, PATH_MAX, brix_sp_entry_t::policy, sp_entry_push(), sp_log(), and sp_read_file().
Referenced by brix_store_configure().
brix_sp_table_check()
int brix_sp_table_check (const brix_sp_table_t * t, brix_sp_mode_t mode, X509 * ca, X509 * subject)
Definition at line 264 of file store_policy.c.
References brix_sp_ca_dn_present(), BRIX_SP_MODE_OFF, BRIX_SP_MODE_REQUIRE, brix_sp_subject_allowed(), brix_x509_oneline(), brix_sp_entry_t::malformed, brix_sp_entry_t::policy, sp_find_by_dn(), and sp_find_by_hash().
Referenced by brix_gsi_enforce_signing_policy().
brix_sp_table_free()
void brix_sp_table_free (brix_sp_table_t * t)
Definition at line 210 of file store_policy.c.
References brix_sp_free().
Referenced by brix_store_configure(), and sp_ex_free().
brix_store_configure()
int brix_store_configure (X509_STORE * store, const char * cadir, unsigned long extra_flags, int crl_count, brix_sp_mode_t sp_mode, int crl_mode, void * log, brix_sp_log_fn log_fn)
Definition at line 203 of file store_policy_store.c.
References BRIX_CRL_MODE_REQUIRE, BRIX_CRL_MODE_TRY, brix_crl_try_verify_cb(), brix_failsafe_get_crl(), BRIX_SP_LOG_WARN, BRIX_SP_MODE_REQUIRE, brix_sp_proxy_check_issued(), brix_sp_table_build(), brix_sp_table_free(), brix_store_policy_attach(), log, and sp_log().
Referenced by brix_build_ca_store().
brix_store_crl_mode()
int brix_store_crl_mode (X509_STORE_CTX * ctx)
Definition at line 337 of file store_policy_store.c.
References BRIX_CRL_MODE_OFF, brix_store_policy_t::crl_mode, and sp_from_ctx().
Referenced by brix_failsafe_get_crl().
brix_store_policy_attach()
int brix_store_policy_attach (X509_STORE * store, brix_sp_table_t * table, brix_sp_mode_t sp_mode, int crl_mode)
Definition at line 282 of file store_policy_store.c.
References brix_store_policy_t::crl_mode, brix_store_policy_t::sp_mode, sp_store_ex_index(), and brix_store_policy_t::table.
Referenced by brix_store_configure().
brix_store_policy_mode()
brix_sp_mode_t brix_store_policy_mode (X509_STORE_CTX * ctx)
Definition at line 330 of file store_policy_store.c.
References BRIX_SP_MODE_OFF, sp_from_ctx(), and brix_store_policy_t::sp_mode.
Referenced by brix_gsi_enforce_signing_policy().
brix_store_policy_table()
brix_sp_table_t * brix_store_policy_table (X509_STORE_CTX * ctx)
Definition at line 323 of file store_policy_store.c.
References sp_from_ctx(), and brix_store_policy_t::table.
Referenced by brix_gsi_enforce_signing_policy().
brix_x509_oneline()
char * brix_x509_oneline (X509_NAME * name, char * buf, size_t buflen)
Definition at line 44 of file store_policy.c.
References name, and s.
Referenced by brix_gsi_enforce_signing_policy(), brix_http_delegated_cred_variable(), brix_sp_table_check(), deleg_proxy_leaf_dn(), and delegation_eec_dn_matches().