nginx-xrootd: client/apps/scan/storascan_core.c File Reference
storascan_core.c File Reference
#include "storascan_core.h"
#include <ctype.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
Functions
static const char * ckv_skip_ws (const char *s)
static size_t ckv_trimmed_len (const char *s)
storascan_cks_status storascan_cks_compare (const char *computed_hex, const char *stored_hex)
double storascan_percentile_ms (const double *sorted_ms, size_t n, double pct)
static int ckv_cmp_double (const void *a, const void *b)
void storascan_bench_compute (const double *lat_ms, size_t n, uint64_t bytes, double elapsed_s, storascan_bench_result *out)
Function Documentation
ckv_cmp_double()
static int ckv_cmp_double (const void * a, const void * b) static
Definition at line 102 of file storascan_core.c.
Referenced by storascan_bench_compute().
ckv_skip_ws()
static const char * ckv_skip_ws (const char * s) static
Definition at line 18 of file storascan_core.c.
References s.
Referenced by storascan_cks_compare().
ckv_trimmed_len()
static size_t ckv_trimmed_len (const char * s) static
Definition at line 28 of file storascan_core.c.
References s.
Referenced by storascan_cks_compare().
storascan_bench_compute()
void storascan_bench_compute (const double * lat_ms, size_t n, uint64_t bytes, double elapsed_s, storascan_bench_result * out)
Definition at line 117 of file storascan_core.c.
References storascan_bench_result::bytes, ckv_cmp_double(), storascan_bench_result::elapsed_s, storascan_bench_result::iops, storascan_bench_result::ops, storascan_bench_result::p50_ms, storascan_bench_result::p95_ms, storascan_bench_result::p99_ms, storascan_percentile_ms(), and storascan_bench_result::throughput_mibps.
Referenced by bench_workers_compute(), and test_bench_compute().
storascan_cks_compare()
storascan_cks_status storascan_cks_compare (const char * computed_hex, const char * stored_hex)
Definition at line 39 of file storascan_core.c.
References ckv_skip_ws(), ckv_trimmed_len(), STORASCAN_CKS_MATCH, STORASCAN_CKS_MISMATCH, and STORASCAN_CKS_MISSING.
Referenced by cmd_verify(), and test_cks_compare().
storascan_percentile_ms()
double storascan_percentile_ms (const double * sorted_ms, size_t n, double pct)
Definition at line 73 of file storascan_core.c.
Referenced by storascan_bench_compute(), and test_percentile().