nginx-xrootd: src/auth/crypto/store_policy.c File Reference
store_policy.c File Reference
#include "auth/crypto/store_policy.h"
#include <openssl/bn.h>
#include <openssl/evp.h>
#include <openssl/objects.h>
#include <openssl/x509v3.h>
#include <dirent.h>
#include <fcntl.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
struct brix_sp_entry_t
struct brix_sp_table_t
struct brix_store_policy_t
Macros
#define BRIX_SP_FILE_MAX (256 * 1024)
Functions
char * brix_x509_oneline (X509_NAME *name, char *buf, size_t buflen)
static int sp_entry_push (brix_sp_table_t *t, brix_sp_entry_t e)
static char * sp_read_file (const char *path, size_t *out_len)
static void sp_log (void *log, brix_sp_log_fn fn, int level, const char *msg)
brix_sp_table_t * brix_sp_table_build (const char *cadir, void *log, brix_sp_log_fn log_fn)
void brix_sp_table_free (brix_sp_table_t *t)
static const brix_sp_entry_t * sp_find_by_hash (const brix_sp_table_t *t, X509 *ca)
static const brix_sp_entry_t * sp_find_by_dn (const brix_sp_table_t *t, const char *ca_dn)
int brix_sp_table_check (const brix_sp_table_t *t, brix_sp_mode_t mode, X509 *ca, X509 *subject)
brix_px_kind_t brix_px_classify (X509 *cert)
int brix_proxy_chain_ok (STACK_OF(X509) *chain)
static int brix_dn_has_control_bytes (X509_NAME *nm)
int brix_cert_policy_violation (X509 *cert)
int brix_leaf_purpose_violation (X509 *leaf)
int brix_proxy_pci_ok (STACK_OF(X509) *chain)
static int brix_sp_proxy_check_issued (X509_STORE_CTX *ctx, X509 *subject, X509 *issuer)
static int brix_crl_try_verify_cb (int ok, X509_STORE_CTX *ctx)
int brix_store_configure (X509_STORE *store, const char *cadir, unsigned long extra_flags, int crl_count, brix_sp_mode_t sp_mode, int crl_mode, void *log, brix_sp_log_fn log_fn)
static void sp_ex_free (void *parent, void *ptr, CRYPTO_EX_DATA *ad, int idx, long argl, void *argp)
static int sp_store_ex_index (void)
int brix_store_policy_attach (X509_STORE *store, brix_sp_table_t *table, brix_sp_mode_t sp_mode, int crl_mode)
static brix_store_policy_t * sp_from_ctx (X509_STORE_CTX *ctx)
brix_sp_table_t * brix_store_policy_table (X509_STORE_CTX *ctx)
brix_sp_mode_t brix_store_policy_mode (X509_STORE_CTX *ctx)
int brix_store_crl_mode (X509_STORE_CTX *ctx)
Variables
static const char * BRIX_PX_LIMITED_OID = "1.3.6.1.4.1.3536.1.1.1.9"
static const char * BRIX_PX_OID_IMPERSONATION = "1.3.6.1.5.5.7.21.1"
static const char * BRIX_PX_OID_INDEPENDENT = "1.3.6.1.5.5.7.21.2"
Macro Definition Documentation
BRIX_SP_FILE_MAX
#define BRIX_SP_FILE_MAX (256 * 1024)
Definition at line 44 of file store_policy.c.
Function Documentation
brix_cert_policy_violation()
int brix_cert_policy_violation (X509 * cert)
Definition at line 404 of file store_policy.c.
References brix_dn_has_control_bytes().
Referenced by brix_gsi_enforce_cert_policy().
brix_crl_try_verify_cb()
static int brix_crl_try_verify_cb (int ok, X509_STORE_CTX * ctx) static
Definition at line 583 of file store_policy.c.
Referenced by brix_store_configure().
brix_dn_has_control_bytes()
static int brix_dn_has_control_bytes (X509_NAME * nm) static
Definition at line 385 of file store_policy.c.
References s.
Referenced by brix_cert_policy_violation().
brix_leaf_purpose_violation()
int brix_leaf_purpose_violation (X509 * leaf)
Definition at line 460 of file store_policy.c.
Referenced by brix_gsi_enforce_cert_policy().
brix_proxy_chain_ok()
int brix_proxy_chain_ok (STACK_OF(X509) * chain)
Definition at line 355 of file store_policy.c.
References brix_px_classify(), BRIX_PX_FULL, and BRIX_PX_LIMITED.
Referenced by brix_gsi_enforce_proxy_monotonicity().
brix_proxy_pci_ok()
int brix_proxy_pci_ok (STACK_OF(X509) * chain)
Definition at line 493 of file store_policy.c.
References BRIX_PX_LIMITED_OID, BRIX_PX_OID_IMPERSONATION, and BRIX_PX_OID_INDEPENDENT.
Referenced by brix_gsi_enforce_cert_policy().
brix_px_classify()
brix_px_kind_t brix_px_classify (X509 * cert)
Definition at line 310 of file store_policy.c.
References BRIX_PX_FULL, BRIX_PX_LIMITED, BRIX_PX_LIMITED_OID, BRIX_PX_NONE, and s.
Referenced by brix_proxy_chain_ok().
brix_sp_proxy_check_issued()
static int brix_sp_proxy_check_issued (X509_STORE_CTX * ctx, X509 * subject, X509 * issuer) static
Definition at line 549 of file store_policy.c.
Referenced by brix_store_configure().
brix_sp_table_build()
brix_sp_table_t * brix_sp_table_build (const char * cadir, void * log, brix_sp_log_fn log_fn)
Definition at line 143 of file store_policy.c.
References brix_sp_free(), BRIX_SP_LOG_WARN, brix_sp_parse(), brix_sp_entry_t::hash, brix_sp_entry_t::have_hash, log, brix_sp_entry_t::malformed, name, PATH_MAX, brix_sp_entry_t::policy, sp_entry_push(), sp_log(), and sp_read_file().
Referenced by brix_store_configure().
brix_sp_table_check()
int brix_sp_table_check (const brix_sp_table_t * t, brix_sp_mode_t mode, X509 * ca, X509 * subject)
Definition at line 269 of file store_policy.c.
References brix_sp_ca_dn_present(), BRIX_SP_MODE_OFF, BRIX_SP_MODE_REQUIRE, brix_sp_subject_allowed(), brix_x509_oneline(), brix_sp_entry_t::malformed, mode, brix_sp_entry_t::policy, sp_find_by_dn(), and sp_find_by_hash().
Referenced by brix_gsi_enforce_signing_policy().
brix_sp_table_free()
void brix_sp_table_free (brix_sp_table_t * t)
Definition at line 215 of file store_policy.c.
References brix_sp_free().
Referenced by brix_store_configure(), and sp_ex_free().
brix_store_configure()
int brix_store_configure (X509_STORE * store, const char * cadir, unsigned long extra_flags, int crl_count, brix_sp_mode_t sp_mode, int crl_mode, void * log, brix_sp_log_fn log_fn)
Definition at line 595 of file store_policy.c.
References BRIX_CRL_MODE_REQUIRE, BRIX_CRL_MODE_TRY, brix_crl_try_verify_cb(), BRIX_SP_LOG_WARN, BRIX_SP_MODE_REQUIRE, brix_sp_proxy_check_issued(), brix_sp_table_build(), brix_sp_table_free(), brix_store_policy_attach(), log, and sp_log().
Referenced by brix_build_ca_store().
brix_store_crl_mode()
int brix_store_crl_mode (X509_STORE_CTX * ctx)
Definition at line 728 of file store_policy.c.
References BRIX_CRL_MODE_OFF, brix_store_policy_t::crl_mode, and sp_from_ctx().
brix_store_policy_attach()
int brix_store_policy_attach (X509_STORE * store, brix_sp_table_t * table, brix_sp_mode_t sp_mode, int crl_mode)
Definition at line 673 of file store_policy.c.
References brix_store_policy_t::crl_mode, brix_store_policy_t::sp_mode, sp_store_ex_index(), and brix_store_policy_t::table.
Referenced by brix_store_configure().
brix_store_policy_mode()
brix_sp_mode_t brix_store_policy_mode (X509_STORE_CTX * ctx)
Definition at line 721 of file store_policy.c.
References BRIX_SP_MODE_OFF, sp_from_ctx(), and brix_store_policy_t::sp_mode.
Referenced by brix_gsi_enforce_signing_policy().
brix_store_policy_table()
brix_sp_table_t * brix_store_policy_table (X509_STORE_CTX * ctx)
Definition at line 714 of file store_policy.c.
References sp_from_ctx(), and brix_store_policy_t::table.
Referenced by brix_gsi_enforce_signing_policy().
brix_x509_oneline()
char * brix_x509_oneline (X509_NAME * name, char * buf, size_t buflen)
Definition at line 49 of file store_policy.c.
References name, and s.
Referenced by brix_gsi_enforce_signing_policy(), and brix_sp_table_check().
sp_entry_push()
static int sp_entry_push (brix_sp_table_t * t, brix_sp_entry_t e) static
Definition at line 76 of file store_policy.c.
Referenced by brix_sp_table_build().
sp_ex_free()
static void sp_ex_free (void * parent, void * ptr, CRYPTO_EX_DATA * ad, int idx, long argl, void * argp) static
Definition at line 648 of file store_policy.c.
References brix_sp_table_free(), and brix_store_policy_t::table.
Referenced by sp_store_ex_index().
sp_find_by_dn()
static const brix_sp_entry_t * sp_find_by_dn (const brix_sp_table_t * t, const char * ca_dn) static
Definition at line 256 of file store_policy.c.
References brix_sp_ca_dn_present().
Referenced by brix_sp_table_check().
sp_find_by_hash()
static const brix_sp_entry_t * sp_find_by_hash (const brix_sp_table_t * t, X509 * ca) static
Definition at line 236 of file store_policy.c.
Referenced by brix_sp_table_check().
sp_from_ctx()
static brix_store_policy_t * sp_from_ctx (X509_STORE_CTX * ctx) static
Definition at line 698 of file store_policy.c.
References sp_store_ex_index().
Referenced by brix_store_crl_mode(), brix_store_policy_mode(), and brix_store_policy_table().
sp_log()
static void sp_log (void * log, brix_sp_log_fn fn, int level, const char * msg) static
Definition at line 135 of file store_policy.c.
References fn, and log.
Referenced by brix_sp_table_build(), and brix_store_configure().
sp_read_file()
static char * sp_read_file (const char * path, size_t * out_len) static
Definition at line 93 of file store_policy.c.
References BRIX_SP_FILE_MAX, close(), fstat(), open(), read(), and stat().
Referenced by brix_sp_table_build().
sp_store_ex_index()
static int sp_store_ex_index (void) static
Definition at line 663 of file store_policy.c.
References sp_ex_free().
Referenced by brix_store_policy_attach(), and sp_from_ctx().
Variable Documentation
BRIX_PX_LIMITED_OID
const char* BRIX_PX_LIMITED_OID = "1.3.6.1.4.1.3536.1.1.1.9" static
Definition at line 307 of file store_policy.c.
Referenced by brix_proxy_pci_ok(), and brix_px_classify().
BRIX_PX_OID_IMPERSONATION
const char* BRIX_PX_OID_IMPERSONATION = "1.3.6.1.5.5.7.21.1" static
Definition at line 380 of file store_policy.c.
Referenced by brix_proxy_pci_ok().
BRIX_PX_OID_INDEPENDENT
const char* BRIX_PX_OID_INDEPENDENT = "1.3.6.1.5.5.7.21.2" static
Definition at line 381 of file store_policy.c.
Referenced by brix_proxy_pci_ok().