nginx-xrootd: src/auth/crypto/store_policy_store.c File Reference
store_policy_store.c File Reference
#include "auth/crypto/store_policy.h"
#include "store_policy_internal.h"
#include <openssl/bn.h>
#include <openssl/evp.h>
#include <openssl/objects.h>
#include <openssl/x509v3.h>
#include <dirent.h>
#include <fcntl.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
struct brix_store_policy_t
Functions
static int brix_sp_proxy_check_issued (X509_STORE_CTX *ctx, X509 *subject, X509 *issuer)
static int brix_crl_try_verify_cb (int ok, X509_STORE_CTX *ctx)
int brix_store_configure (X509_STORE *store, const char *cadir, unsigned long extra_flags, int crl_count, brix_sp_mode_t sp_mode, int crl_mode, void *log, brix_sp_log_fn log_fn)
static void sp_ex_free (void *parent, void *ptr, CRYPTO_EX_DATA *ad, int idx, long argl, void *argp)
static int sp_store_ex_index (void)
int brix_store_policy_attach (X509_STORE *store, brix_sp_table_t *table, brix_sp_mode_t sp_mode, int crl_mode)
static brix_store_policy_t * sp_from_ctx (X509_STORE_CTX *ctx)
brix_sp_table_t * brix_store_policy_table (X509_STORE_CTX *ctx)
brix_sp_mode_t brix_store_policy_mode (X509_STORE_CTX *ctx)
int brix_store_crl_mode (X509_STORE_CTX *ctx)
Function Documentation
brix_crl_try_verify_cb()
static int brix_crl_try_verify_cb (int ok, X509_STORE_CTX * ctx) static
Definition at line 83 of file store_policy_store.c.
Referenced by brix_store_configure().
brix_sp_proxy_check_issued()
static int brix_sp_proxy_check_issued (X509_STORE_CTX * ctx, X509 * subject, X509 * issuer) static
Definition at line 49 of file store_policy_store.c.
Referenced by brix_store_configure().
brix_store_configure()
int brix_store_configure (X509_STORE * store, const char * cadir, unsigned long extra_flags, int crl_count, brix_sp_mode_t sp_mode, int crl_mode, void * log, brix_sp_log_fn log_fn)
Definition at line 95 of file store_policy_store.c.
References BRIX_CRL_MODE_REQUIRE, BRIX_CRL_MODE_TRY, brix_crl_try_verify_cb(), BRIX_SP_LOG_WARN, BRIX_SP_MODE_REQUIRE, brix_sp_proxy_check_issued(), brix_sp_table_build(), brix_sp_table_free(), brix_store_policy_attach(), log, and sp_log().
Referenced by brix_build_ca_store().
brix_store_crl_mode()
int brix_store_crl_mode (X509_STORE_CTX * ctx)
Definition at line 228 of file store_policy_store.c.
References BRIX_CRL_MODE_OFF, brix_store_policy_t::crl_mode, and sp_from_ctx().
brix_store_policy_attach()
int brix_store_policy_attach (X509_STORE * store, brix_sp_table_t * table, brix_sp_mode_t sp_mode, int crl_mode)
Definition at line 173 of file store_policy_store.c.
References brix_store_policy_t::crl_mode, brix_store_policy_t::sp_mode, sp_store_ex_index(), and brix_store_policy_t::table.
Referenced by brix_store_configure().
brix_store_policy_mode()
brix_sp_mode_t brix_store_policy_mode (X509_STORE_CTX * ctx)
Definition at line 221 of file store_policy_store.c.
References BRIX_SP_MODE_OFF, sp_from_ctx(), and brix_store_policy_t::sp_mode.
Referenced by brix_gsi_enforce_signing_policy().
brix_store_policy_table()
brix_sp_table_t * brix_store_policy_table (X509_STORE_CTX * ctx)
Definition at line 214 of file store_policy_store.c.
References sp_from_ctx(), and brix_store_policy_t::table.
Referenced by brix_gsi_enforce_signing_policy().
sp_ex_free()
static void sp_ex_free (void * parent, void * ptr, CRYPTO_EX_DATA * ad, int idx, long argl, void * argp) static
Definition at line 148 of file store_policy_store.c.
References brix_sp_table_free(), and brix_store_policy_t::table.
Referenced by sp_store_ex_index().
sp_from_ctx()
static brix_store_policy_t * sp_from_ctx (X509_STORE_CTX * ctx) static
Definition at line 198 of file store_policy_store.c.
References sp_store_ex_index().
Referenced by brix_store_crl_mode(), brix_store_policy_mode(), and brix_store_policy_table().
sp_store_ex_index()
static int sp_store_ex_index (void) static
Definition at line 163 of file store_policy_store.c.
References sp_ex_free().
Referenced by brix_store_policy_attach(), and sp_from_ctx().