nginx-xrootd: client/apps/scan/storascan_unittest.c File Reference
storascan_unittest.c File Reference
#include "storascan_core.h"
#include <math.h>
#include <stdio.h>
#include <string.h>
Macros
#define CHECK(cond, msg)
#define CLOSE(a, b) (fabs((a) - (b)) < 1e-6)
Functions
static void test_cks_compare (void)
static void test_percentile (void)
static void test_bench_compute (void)
int main (void)
Variables
static int g_fail
Macro Definition Documentation
CHECK
#define CHECK (cond, msg)
Value:
    do {                                                                       \
        if (!(cond)) {                                                         \
            fprintf(stderr, "FAIL: %s (%s:%d)\n", (msg), __FILE__, __LINE__);  \
            g_fail++;                                                          \
        }                                                                      \
    } while (0)
Definition at line 18 of file storascan_unittest.c.
CLOSE
#define CLOSE (a, b) (fabs((a) - (b)) < 1e-6)
Definition at line 26 of file storascan_unittest.c.
Function Documentation
main()
int main (void)
Definition at line 103 of file storascan_unittest.c.
References g_fail, test_bench_compute(), test_cks_compare(), and test_percentile().
test_bench_compute()
static void test_bench_compute (void) static
Definition at line 72 of file storascan_unittest.c.
References storascan_bench_result::bytes, CHECK, CLOSE, storascan_bench_result::elapsed_s, storascan_bench_result::iops, storascan_bench_result::ops, storascan_bench_result::p50_ms, storascan_bench_compute(), and storascan_bench_result::throughput_mibps.
Referenced by main().
test_cks_compare()
static void test_cks_compare (void) static
Definition at line 29 of file storascan_unittest.c.
References CHECK, storascan_cks_compare(), STORASCAN_CKS_MATCH, STORASCAN_CKS_MISMATCH, and STORASCAN_CKS_MISSING.
Referenced by main().
test_percentile()
static void test_percentile (void) static
Definition at line 50 of file storascan_unittest.c.
References CHECK, CLOSE, and storascan_percentile_ms().
Referenced by main().
Variable Documentation
g_fail
int g_fail static
Definition at line 16 of file storascan_unittest.c.
Referenced by main().