nginx-xrootd: src/core/compat/str_dup.h File Reference
str_dup.h File Reference
#include <ngx_core.h>
Functions
static ngx_int_t brix_pstrdupz (ngx_pool_t *pool, ngx_str_t *dst, const u_char *src, size_t len)
Function Documentation
brix_pstrdupz()
static ngx_int_t brix_pstrdupz (ngx_pool_t * pool, ngx_str_t * dst, const u_char * src, size_t len) inline static
Definition at line 40 of file str_dup.h.
References ngx_memcpy, and ngx_pnalloc().
Referenced by brix_conf_set_cache_verify_digest(), brix_conf_set_upstream(), brix_conf_set_wt_origin(), and s3_copy_find_header().