nginx-xrootd: src/net/mirror/stream_mirror.c File Reference
stream_mirror.c File Reference
#include "stream_mirror.h"
#include "stream_mirror_io.h"
#include "observability/metrics/metrics_macros.h"
#include <netdb.h>
#include <sys/socket.h>
Data Structures
struct brix_stream_mirror_t
Macros
#define BRIX_MIRROR_MAX_PAYLOAD 4096
#define BRIX_MIR_METRIC_INC(field)
#define BRIX_MIRROR_OPEN_WRITE_FLAGS (kXR_delete | kXR_new | kXR_open_updt | kXR_open_apnd | kXR_mkpath)
Enumerations
enum brix_mir_phase_t { XRD_MIR_HANDSHAKE = 0 , XRD_MIR_PROTOCOL , XRD_MIR_LOGIN , XRD_MIR_REQUEST }
Functions
void brix_upstream_build_bootstrap (u_char *buf)
static void brix_mir_write_handler (ngx_event_t *wev)
static void brix_mir_read_handler (ngx_event_t *rev)
static void brix_mir_timeout_handler (ngx_event_t *ev)
static void brix_mir_finish (brix_stream_mirror_t *mir, int sent)
static ngx_uint_t brix_mirror_opcode_bit (uint16_t reqid)
static int brix_mirror_request_replayable (brix_ctx_t *ctx)
static ngx_int_t brix_mir_flush (brix_stream_mirror_t *mir)
static void brix_mir_send_request (brix_stream_mirror_t *mir)
static ngx_int_t brix_mir_recv_frame (brix_stream_mirror_t *mir)
static void brix_mir_on_response (brix_stream_mirror_t *mir)
static void brix_mir_dispatch (brix_stream_mirror_t *mir)
static void brix_mir_start (brix_stream_mirror_t *mir, ngx_msec_t timeout_ms)
void brix_stream_mirror_maybe (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, ngx_int_t primary_rc)
char * brix_stream_mirror_set_url (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static char * brix_mirror_parse_opcode_args (ngx_conf_t *cf, const char *directive, ngx_uint_t *mask_out)
char * brix_stream_mirror_set_opcodes (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_stream_mirror_set_exclude_opcodes (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Macro Definition Documentation
BRIX_MIR_METRIC_INC
#define BRIX_MIR_METRIC_INC (field)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_m = brix_metrics_shared();                  \
        if (_m != NULL) { (void) ngx_atomic_fetch_add(&_m->field, 1); }      \
    } while (0)
Definition at line 76 of file stream_mirror.c.
BRIX_MIRROR_MAX_PAYLOAD
#define BRIX_MIRROR_MAX_PAYLOAD 4096
Definition at line 30 of file stream_mirror.c.
BRIX_MIRROR_OPEN_WRITE_FLAGS
#define BRIX_MIRROR_OPEN_WRITE_FLAGS (kXR_delete | kXR_new | kXR_open_updt | kXR_open_apnd | kXR_mkpath)
Definition at line 118 of file stream_mirror.c.
Enumeration Type Documentation
brix_mir_phase_t
enum brix_mir_phase_t
Enumerator
XRD_MIR_HANDSHAKE
XRD_MIR_PROTOCOL
XRD_MIR_LOGIN
XRD_MIR_REQUEST
Definition at line 32 of file stream_mirror.c.
Function Documentation
brix_mir_dispatch()
static void brix_mir_dispatch (brix_stream_mirror_t * mir) static
Definition at line 303 of file stream_mirror.c.
References brix_mir_finish(), brix_mir_on_response(), brix_mir_send_request(), brix_stream_mirror_t::conn, kXR_authmore, kXR_gotoTLS, kXR_ok, ngx_memcpy, brix_stream_mirror_t::phase, brix_stream_mirror_t::resp_body, brix_stream_mirror_t::resp_body_pos, brix_stream_mirror_t::resp_dlen, brix_stream_mirror_t::resp_status, brix_stream_mirror_t::rhdr_pos, XRD_MIR_HANDSHAKE, XRD_MIR_LOGIN, XRD_MIR_PROTOCOL, and XRD_MIR_REQUEST.
Referenced by brix_mir_read_handler().
brix_mir_finish()
static void brix_mir_finish (brix_stream_mirror_t * mir, int sent) static
Definition at line 395 of file stream_mirror.c.
References BRIX_MIR_METRIC_INC, brix_stream_mirror_t::conn, brix_stream_mirror_t::pool, and brix_stream_mirror_t::tev.
Referenced by brix_mir_dispatch(), brix_mir_on_response(), brix_mir_read_handler(), brix_mir_send_request(), brix_mir_start(), brix_mir_timeout_handler(), and brix_mir_write_handler().
brix_mir_flush()
static ngx_int_t brix_mir_flush (brix_stream_mirror_t * mir) static
Definition at line 178 of file stream_mirror.c.
References brix_mirror_io_flush(), brix_stream_mirror_t::conn, brix_stream_mirror_t::wbuf, brix_stream_mirror_t::wbuf_len, and brix_stream_mirror_t::wbuf_pos.
Referenced by brix_mir_send_request(), brix_mir_start(), and brix_mir_write_handler().
brix_mir_on_response()
static void brix_mir_on_response (brix_stream_mirror_t * mir) static
Definition at line 261 of file stream_mirror.c.
References brix_mir_finish(), BRIX_MIR_METRIC_INC, brix_stream_mirror_t::host, kXR_error, kXR_ok, kXR_oksofar, kXR_redirect, kXR_Unsupported, brix_stream_mirror_t::log, brix_stream_mirror_t::log_diverge, ngx_memcpy, brix_stream_mirror_t::port, brix_stream_mirror_t::primary_ok, brix_stream_mirror_t::resp_body, brix_stream_mirror_t::resp_dlen, brix_stream_mirror_t::resp_status, and brix_stream_mirror_t::saved_opcode.
Referenced by brix_mir_dispatch().
brix_mir_read_handler()
static void brix_mir_read_handler (ngx_event_t * rev) static
Definition at line 357 of file stream_mirror.c.
References brix_mir_dispatch(), brix_mir_finish(), brix_mir_recv_frame(), and c.
Referenced by brix_mir_start().
brix_mir_recv_frame()
static ngx_int_t brix_mir_recv_frame (brix_stream_mirror_t * mir) static
Definition at line 252 of file stream_mirror.c.
References brix_mirror_io_recv_frame(), brix_stream_mirror_t::conn, brix_stream_mirror_t::resp_body, brix_stream_mirror_t::resp_body_pos, brix_stream_mirror_t::resp_dlen, brix_stream_mirror_t::resp_status, brix_stream_mirror_t::rhdr, and brix_stream_mirror_t::rhdr_pos.
Referenced by brix_mir_read_handler().
brix_mir_send_request()
static void brix_mir_send_request (brix_stream_mirror_t * mir) static
Definition at line 186 of file stream_mirror.c.
References brix_mir_finish(), brix_mir_flush(), ngx_memcpy, brix_stream_mirror_t::phase, brix_stream_mirror_t::pool, brix_stream_mirror_t::resp_body, brix_stream_mirror_t::resp_body_pos, brix_stream_mirror_t::resp_dlen, brix_stream_mirror_t::rhdr_pos, brix_stream_mirror_t::saved_dlen, brix_stream_mirror_t::saved_hdr, brix_stream_mirror_t::saved_payload, brix_stream_mirror_t::wbuf, brix_stream_mirror_t::wbuf_len, brix_stream_mirror_t::wbuf_pos, and XRD_MIR_REQUEST.
Referenced by brix_mir_dispatch().
brix_mir_start()
static void brix_mir_start (brix_stream_mirror_t * mir, ngx_msec_t timeout_ms) static
Definition at line 413 of file stream_mirror.c.
References brix_mir_finish(), brix_mir_flush(), brix_mir_read_handler(), brix_mir_timeout_handler(), brix_mir_write_handler(), brix_upstream_build_bootstrap(), c, brix_stream_mirror_t::conn, brix_stream_mirror_t::connecting, brix_stream_mirror_t::log, brix_stream_mirror_t::pool, brix_stream_mirror_t::sockaddr, brix_stream_mirror_t::socklen, brix_stream_mirror_t::tev, brix_stream_mirror_t::wbuf, brix_stream_mirror_t::wbuf_len, brix_stream_mirror_t::wbuf_pos, and XRD_HANDSHAKE_LEN.
Referenced by brix_stream_mirror_maybe().
brix_mir_timeout_handler()
static void brix_mir_timeout_handler (ngx_event_t * ev) static
Definition at line 385 of file stream_mirror.c.
References brix_mir_finish(), brix_stream_mirror_t::host, brix_stream_mirror_t::log, and brix_stream_mirror_t::port.
Referenced by brix_mir_start().
brix_mir_write_handler()
static void brix_mir_write_handler (ngx_event_t * wev) static
Definition at line 217 of file stream_mirror.c.
References brix_mir_finish(), brix_mir_flush(), c, brix_stream_mirror_t::connecting, brix_stream_mirror_t::host, brix_stream_mirror_t::log, and brix_stream_mirror_t::port.
Referenced by brix_mir_start().
brix_mirror_opcode_bit()
static ngx_uint_t brix_mirror_opcode_bit (uint16_t reqid) static
Definition at line 90 of file stream_mirror.c.
References BRIX_MIRROR_OP_CHMOD, BRIX_MIRROR_OP_DIRLIST, BRIX_MIRROR_OP_LOCATE, BRIX_MIRROR_OP_MKDIR, BRIX_MIRROR_OP_MV, BRIX_MIRROR_OP_OPEN, BRIX_MIRROR_OP_QUERY, BRIX_MIRROR_OP_READ, BRIX_MIRROR_OP_READV, BRIX_MIRROR_OP_RM, BRIX_MIRROR_OP_RMDIR, BRIX_MIRROR_OP_STAT, BRIX_MIRROR_OP_STATX, BRIX_MIRROR_OP_TRUNCATE, kXR_chmod, kXR_dirlist, kXR_locate, kXR_mkdir, kXR_mv, kXR_open, kXR_query, kXR_read, kXR_readv, kXR_rm, kXR_rmdir, kXR_stat, kXR_statx, and kXR_truncate.
Referenced by brix_stream_mirror_maybe().
brix_mirror_parse_opcode_args()
static char * brix_mirror_parse_opcode_args (ngx_conf_t * cf, const char * directive, ngx_uint_t * mask_out) static
Definition at line 666 of file stream_mirror.c.
References BRIX_MIRROR_OP_ALL, BRIX_MIRROR_OP_CHMOD, BRIX_MIRROR_OP_DIRLIST, BRIX_MIRROR_OP_LOCATE, BRIX_MIRROR_OP_MKDIR, BRIX_MIRROR_OP_MV, BRIX_MIRROR_OP_OPEN, BRIX_MIRROR_OP_QUERY, BRIX_MIRROR_OP_READ, BRIX_MIRROR_OP_READV, BRIX_MIRROR_OP_RM, BRIX_MIRROR_OP_RMDIR, BRIX_MIRROR_OP_STAT, BRIX_MIRROR_OP_STATX, BRIX_MIRROR_OP_TRUNCATE, and BRIX_MIRROR_OP_WRITE.
Referenced by brix_stream_mirror_set_exclude_opcodes(), and brix_stream_mirror_set_opcodes().
brix_mirror_request_replayable()
static int brix_mirror_request_replayable (brix_ctx_t * ctx) static
Definition at line 140 of file stream_mirror.c.
References BRIX_MIRROR_OPEN_WRITE_FLAGS, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, brix_ctx_recv_t::hdr_buf, kXR_chmod, kXR_dirlist, kXR_locate, kXR_mkdir, kXR_mv, kXR_open, kXR_query, kXR_rm, kXR_rmdir, kXR_stat, kXR_statx, kXR_truncate, ngx_memcpy, and brix_ctx_t::recv.
Referenced by brix_stream_mirror_maybe().
brix_stream_mirror_maybe()
void brix_stream_mirror_maybe (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, ngx_int_t primary_rc)
Definition at line 483 of file stream_mirror.c.
References BRIX_MIR_METRIC_INC, brix_mir_start(), BRIX_MIRROR_MAX_PAYLOAD, BRIX_MIRROR_OP_WRITE, BRIX_MIRROR_OP_WRITE_ALL, brix_mirror_opcode_bit(), brix_mirror_request_replayable(), brix_mirror_should_sample(), brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, brix_mirror_conf_t::enabled, brix_ctx_recv_t::hdr_buf, brix_mirror_target_t::host, brix_stream_mirror_t::host, brix_stream_mirror_t::log, brix_mirror_conf_t::log_diverge, brix_stream_mirror_t::log_diverge, ngx_stream_brix_srv_conf_t::mirror, brix_mirror_conf_t::mirror_writes, ngx_memcpy, ngx_pcalloc(), brix_mirror_conf_t::opcode_exclude_mask, brix_mirror_conf_t::opcode_mask, brix_ctx_recv_t::payload, brix_stream_mirror_t::phase, brix_stream_mirror_t::pool, brix_mirror_target_t::port, brix_stream_mirror_t::port, brix_stream_mirror_t::primary_ok, brix_ctx_t::recv, brix_mirror_conf_t::sample_pct, brix_stream_mirror_t::saved_dlen, brix_stream_mirror_t::saved_hdr, brix_stream_mirror_t::saved_opcode, brix_stream_mirror_t::saved_payload, brix_mirror_target_t::sockaddr, brix_stream_mirror_t::sockaddr, brix_mirror_target_t::socklen, brix_stream_mirror_t::socklen, brix_mirror_conf_t::targets, brix_mirror_conf_t::timeout_ms, and XRD_MIR_HANDSHAKE.
Referenced by brix_dispatch().
brix_stream_mirror_set_exclude_opcodes()
char * brix_stream_mirror_set_exclude_opcodes (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 724 of file stream_mirror.c.
References brix_mirror_parse_opcode_args(), ngx_stream_brix_srv_conf_t::mirror, and brix_mirror_conf_t::opcode_exclude_mask.
brix_stream_mirror_set_opcodes()
char * brix_stream_mirror_set_opcodes (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 710 of file stream_mirror.c.
References brix_mirror_parse_opcode_args(), ngx_stream_brix_srv_conf_t::mirror, and brix_mirror_conf_t::opcode_mask.
brix_stream_mirror_set_url()
char * brix_stream_mirror_set_url (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 590 of file stream_mirror.c.
References BRIX_MIRROR_MAX_TARGETS, brix_mirror_target_t::host, ngx_stream_brix_srv_conf_t::mirror, ngx_memcpy, brix_mirror_target_t::port, brix_mirror_target_t::sockaddr, brix_mirror_target_t::socklen, brix_mirror_conf_t::targets, and brix_mirror_target_t::url.
brix_upstream_build_bootstrap()
void brix_upstream_build_bootstrap (u_char * buf) extern
Definition at line 32 of file bootstrap.c.
Referenced by brix_mir_start().