nginx-xrootd: src/net/mirror/stream_wmirror_state.c File Reference
stream_wmirror_state.c File Reference
#include "stream_wmirror.h"
#include "stream_wmirror_internal.h"
#include <arpa/inet.h>
Enumerations
enum wmir_step_t { WMIR_STEP_FAIL = 0 , WMIR_STEP_SENT , WMIR_STEP_REPOST }
Functions
static void wmir_reset_frame (brix_wmirror_replay_t *r)
static void wmir_send_open (brix_wmirror_replay_t *r)
static void wmir_send_write (brix_wmirror_replay_t *r)
static void wmir_send_close (brix_wmirror_replay_t *r)
static int wmir_status_ok (uint16_t st)
static wmir_step_t wmir_step_handshake (brix_wmirror_replay_t *r)
static wmir_step_t wmir_step_protocol (brix_wmirror_replay_t *r)
static wmir_step_t wmir_step_login (brix_wmirror_replay_t *r)
static wmir_step_t wmir_step_open (brix_wmirror_replay_t *r)
static wmir_step_t wmir_step_write (brix_wmirror_replay_t *r)
static wmir_step_t wmir_step_close (brix_wmirror_replay_t *r)
static void wmir_repost_read (brix_wmirror_replay_t *r)
void wmir_dispatch (brix_wmirror_replay_t *r)
Variables
static wmir_step_t(*const wmir_step_table [])(brix_wmirror_replay_t *)
Enumeration Type Documentation
wmir_step_t
enum wmir_step_t
Enumerator
WMIR_STEP_FAIL
WMIR_STEP_SENT
WMIR_STEP_REPOST
Definition at line 137 of file stream_wmirror_state.c.
Function Documentation
wmir_dispatch()
void wmir_dispatch (brix_wmirror_replay_t * r)
Definition at line 262 of file stream_wmirror_state.c.
References brix_wmirror_replay_t::phase, wmir_finish(), wmir_repost_read(), WMIR_STEP_FAIL, WMIR_STEP_REPOST, and wmir_step_table.
Referenced by wmir_read_handler().
wmir_repost_read()
static void wmir_repost_read (brix_wmirror_replay_t * r) static
Definition at line 238 of file stream_wmirror_state.c.
References brix_wmirror_replay_t::conn, wmir_finish(), and wmir_reset_frame().
Referenced by wmir_dispatch().
wmir_reset_frame()
static void wmir_reset_frame (brix_wmirror_replay_t * r) static
Definition at line 31 of file stream_wmirror_state.c.
References brix_wmirror_replay_t::resp_body, brix_wmirror_replay_t::resp_body_pos, brix_wmirror_replay_t::resp_dlen, brix_wmirror_replay_t::resp_status, and brix_wmirror_replay_t::rhdr_pos.
Referenced by wmir_repost_read(), wmir_send_close(), wmir_send_open(), and wmir_send_write().
wmir_send_close()
static void wmir_send_close (brix_wmirror_replay_t * r) static
Definition at line 106 of file stream_wmirror_state.c.
References kXR_close, ngx_memcpy, brix_wmirror_replay_t::phase, brix_wmirror_replay_t::pool, brix_wmirror_replay_t::shadow_fhandle, brix_wmirror_replay_t::wbuf, brix_wmirror_replay_t::wbuf_len, brix_wmirror_replay_t::wbuf_pos, WMIR_CLOSE, wmir_finish(), wmir_flush(), and wmir_reset_frame().
Referenced by wmir_step_write().
wmir_send_open()
static void wmir_send_open (brix_wmirror_replay_t * r) static
Definition at line 49 of file stream_wmirror_state.c.
References ngx_memcpy, brix_wmirror_replay_t::open_frame, brix_wmirror_replay_t::open_frame_len, brix_wmirror_replay_t::phase, brix_wmirror_replay_t::pool, brix_wmirror_replay_t::wbuf, brix_wmirror_replay_t::wbuf_len, brix_wmirror_replay_t::wbuf_pos, wmir_finish(), wmir_flush(), WMIR_OPEN, and wmir_reset_frame().
Referenced by wmir_step_login().
wmir_send_write()
static void wmir_send_write (brix_wmirror_replay_t * r) static
Definition at line 78 of file stream_wmirror_state.c.
References brix_wmirror_replay_t::data, brix_wmirror_replay_t::data_len, kXR_write, ngx_memcpy, brix_wmirror_replay_t::phase, brix_wmirror_replay_t::pool, brix_wmirror_replay_t::shadow_fhandle, brix_wmirror_replay_t::wbuf, brix_wmirror_replay_t::wbuf_len, brix_wmirror_replay_t::wbuf_pos, wmir_finish(), wmir_flush(), wmir_reset_frame(), and WMIR_WRITE.
Referenced by wmir_step_open().
wmir_status_ok()
static int wmir_status_ok (uint16_t st) static
Definition at line 124 of file stream_wmirror_state.c.
References kXR_ok, and kXR_oksofar.
Referenced by wmir_step_close(), wmir_step_open(), and wmir_step_write().
wmir_step_close()
static wmir_step_t wmir_step_close (brix_wmirror_replay_t * r) static
Definition at line 225 of file stream_wmirror_state.c.
References brix_wmirror_replay_t::resp_status, wmir_finish(), wmir_status_ok(), and WMIR_STEP_SENT.
wmir_step_handshake()
static wmir_step_t wmir_step_handshake (brix_wmirror_replay_t * r) static
Definition at line 149 of file stream_wmirror_state.c.
References kXR_ok, brix_wmirror_replay_t::phase, brix_wmirror_replay_t::resp_status, WMIR_PROTOCOL, WMIR_STEP_FAIL, and WMIR_STEP_REPOST.
wmir_step_login()
static wmir_step_t wmir_step_login (brix_wmirror_replay_t * r) static
Definition at line 182 of file stream_wmirror_state.c.
References kXR_ok, brix_wmirror_replay_t::resp_status, wmir_send_open(), WMIR_STEP_FAIL, and WMIR_STEP_SENT.
wmir_step_open()
static wmir_step_t wmir_step_open (brix_wmirror_replay_t * r) static
Definition at line 196 of file stream_wmirror_state.c.
References ngx_memcpy, brix_wmirror_replay_t::resp_body, brix_wmirror_replay_t::resp_dlen, brix_wmirror_replay_t::resp_status, brix_wmirror_replay_t::shadow_fhandle, wmir_send_write(), wmir_status_ok(), WMIR_STEP_FAIL, and WMIR_STEP_SENT.
wmir_step_protocol()
static wmir_step_t wmir_step_protocol (brix_wmirror_replay_t * r) static
Definition at line 163 of file stream_wmirror_state.c.
References kXR_gotoTLS, kXR_ok, ngx_memcpy, brix_wmirror_replay_t::phase, brix_wmirror_replay_t::resp_body, brix_wmirror_replay_t::resp_dlen, brix_wmirror_replay_t::resp_status, WMIR_LOGIN, WMIR_STEP_FAIL, and WMIR_STEP_REPOST.
wmir_step_write()
static wmir_step_t wmir_step_write (brix_wmirror_replay_t * r) static
Definition at line 213 of file stream_wmirror_state.c.
References brix_wmirror_replay_t::resp_status, wmir_send_close(), wmir_status_ok(), WMIR_STEP_FAIL, and WMIR_STEP_SENT.
Variable Documentation
wmir_step_table
wmir_step_t(*const wmir_step_table[])(brix_wmirror_replay_t *) (brix_wmirror_replay_t *) static
Initial value:
= {
    [WMIR_HANDSHAKE] = wmir_step_handshake,
    [WMIR_PROTOCOL]  = wmir_step_protocol,
    [WMIR_LOGIN]     = wmir_step_login,
    [WMIR_OPEN]      = wmir_step_open,
    [WMIR_WRITE]     = wmir_step_write,
    [WMIR_CLOSE]     = wmir_step_close,
}
Definition at line 250 of file stream_wmirror_state.c.
Referenced by wmir_dispatch().