nginx-xrootd: client/lib/net/streams.c File Reference
streams.c File Reference
#include "brix.h"
#include <string.h>
#include <unistd.h>
Functions
int brix_streams_open (brix_streamset *ss, brix_conn *primary, int streams, brix_status *st)
void brix_streams_close (brix_streamset *ss)
Function Documentation
brix_streams_close()
void brix_streams_close (brix_streamset * ss)
Definition at line 52 of file streams.c.
References brix_tls_free(), close(), brix_io::fd, brix_conn::io, brix_streamset::n, and brix_streamset::sec.
Referenced by copy_download(), copy_remote_to_block(), and upload_stream_body().
brix_streams_open()
int brix_streams_open (brix_streamset * ss, brix_conn * primary, int streams, brix_status * st)
Definition at line 24 of file streams.c.
References brix_bind(), brix_status_clear(), brix_streamset::n, brix_streamset::sec, and XRDC_MAX_STREAMS.
Referenced by download_stream_body(), and upload_stream_body().