nginx-xrootd: src/net/mirror/stream_mirror_internal.h File Reference
stream_mirror_internal.h File Reference
Data Structures
struct brix_stream_mirror_t
Macros
#define BRIX_MIRROR_MAX_PAYLOAD 4096
#define BRIX_MIR_METRIC_INC(field)
Enumerations
enum brix_mir_phase_t { XRD_MIR_HANDSHAKE = 0 , XRD_MIR_PROTOCOL , XRD_MIR_LOGIN , XRD_MIR_REQUEST }
Functions
void brix_mir_start (brix_stream_mirror_t *mir, ngx_msec_t timeout_ms)
Macro Definition Documentation
BRIX_MIR_METRIC_INC
#define BRIX_MIR_METRIC_INC (field)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_m = brix_metrics_shared();                  \
        if (_m != NULL) { (void) ngx_atomic_fetch_add(&_m->field, 1); }      \
    } while (0)
Definition at line 84 of file stream_mirror_internal.h.
BRIX_MIRROR_MAX_PAYLOAD
#define BRIX_MIRROR_MAX_PAYLOAD 4096
Definition at line 35 of file stream_mirror_internal.h.
Enumeration Type Documentation
brix_mir_phase_t
enum brix_mir_phase_t
Enumerator
XRD_MIR_HANDSHAKE
XRD_MIR_PROTOCOL
XRD_MIR_LOGIN
XRD_MIR_REQUEST
Definition at line 37 of file stream_mirror_internal.h.
Function Documentation
brix_mir_start()
void brix_mir_start (brix_stream_mirror_t * mir, ngx_msec_t timeout_ms)
Definition at line 286 of file stream_mirror.c.
References brix_mir_finish(), brix_mir_flush(), brix_mir_read_handler(), brix_mir_timeout_handler(), brix_mir_write_handler(), brix_upstream_build_bootstrap(), c, brix_stream_mirror_t::conn, brix_stream_mirror_t::connecting, brix_stream_mirror_t::log, brix_stream_mirror_t::pool, brix_stream_mirror_t::sockaddr, brix_stream_mirror_t::socklen, brix_stream_mirror_t::tev, brix_stream_mirror_t::wbuf, brix_stream_mirror_t::wbuf_len, brix_stream_mirror_t::wbuf_pos, and XRD_HANDSHAKE_LEN.
Referenced by brix_stream_mirror_launch_target().