nginx-xrootd: src/net/mirror/stream_wmirror.h File Reference
stream_wmirror.h File Reference
#include "core/ngx_brix_module.h"
Functions
void brix_stream_wmirror_on_open (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, int client_idx, int is_write)
void brix_stream_wmirror_observe (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, ngx_int_t primary_rc)
void brix_stream_wmirror_cleanup (brix_ctx_t *ctx)
Function Documentation
brix_stream_wmirror_cleanup()
void brix_stream_wmirror_cleanup (brix_ctx_t * ctx)
Definition at line 260 of file stream_wmirror.c.
References BRIX_MAX_FILES, brix_wmirror_conn_t::files, wmir_file_reset(), and brix_ctx_t::wmirror.
Referenced by brix_release_disconnect_owned_buffers().
brix_stream_wmirror_observe()
void brix_stream_wmirror_observe (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, ngx_int_t primary_rc)
Definition at line 214 of file stream_wmirror.c.
References brix_wmirror_file_t::aborted, brix_wmirror_file_t::active, BRIX_MAX_FILES, c, brix_ctx_recv_t::cur_reqid, brix_wmirror_conn_t::files, brix_ctx_recv_t::hdr_buf, kXR_close, kXR_pgwrite, kXR_write, brix_ctx_t::recv, wmir_accumulate_write(), wmir_gate(), wmir_observe_close(), and brix_ctx_t::wmirror.
Referenced by brix_dispatch().
brix_stream_wmirror_on_open()
void brix_stream_wmirror_on_open (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, int client_idx, int is_write)
Definition at line 96 of file stream_wmirror.c.
References brix_wmirror_file_t::aborted, brix_wmirror_file_t::active, BRIX_MAX_FILES, BRIX_WMIRROR_FILE_CAP, c, brix_ctx_recv_t::cur_dlen, brix_wmirror_conn_t::files, brix_ctx_recv_t::hdr_buf, brix_wmirror_file_t::next_off, ngx_memcpy, ngx_pcalloc(), brix_wmirror_file_t::open_dlen, brix_wmirror_file_t::open_hdr, brix_wmirror_file_t::open_payload, brix_ctx_recv_t::payload, brix_ctx_t::recv, wmir_file_reset(), wmir_gate(), and brix_ctx_t::wmirror.
Referenced by brix_open_send_response().