nginx-xrootd: src/net/mirror/stream_mirror_config.c File Reference
stream_mirror_config.c File Reference
#include "stream_mirror.h"
Data Structures
struct brix_mirror_opcode_name_t
Functions
char * brix_stream_mirror_set_url (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static ngx_uint_t brix_mirror_opcode_name_bit (const u_char *name)
static char * brix_mirror_parse_opcode_args (ngx_conf_t *cf, const char *directive, ngx_uint_t *mask_out)
char * brix_stream_mirror_set_opcodes (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_stream_mirror_set_exclude_opcodes (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Variables
static const brix_mirror_opcode_name_t brix_mirror_opcode_names []
Function Documentation
brix_mirror_opcode_name_bit()
static ngx_uint_t brix_mirror_opcode_name_bit (const u_char * name) static
Definition at line 144 of file stream_mirror_config.c.
References brix_mirror_opcode_name_t::bit, brix_mirror_opcode_names, brix_mirror_opcode_name_t::name, and name.
Referenced by brix_mirror_parse_opcode_args().
brix_mirror_parse_opcode_args()
static char * brix_mirror_parse_opcode_args (ngx_conf_t * cf, const char * directive, ngx_uint_t * mask_out) static
Definition at line 161 of file stream_mirror_config.c.
References brix_mirror_opcode_name_bit().
Referenced by brix_stream_mirror_set_exclude_opcodes(), and brix_stream_mirror_set_opcodes().
brix_stream_mirror_set_exclude_opcodes()
char * brix_stream_mirror_set_exclude_opcodes (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 205 of file stream_mirror_config.c.
References brix_mirror_parse_opcode_args().
brix_stream_mirror_set_opcodes()
char * brix_stream_mirror_set_opcodes (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 191 of file stream_mirror_config.c.
References brix_mirror_parse_opcode_args().
brix_stream_mirror_set_url()
char * brix_stream_mirror_set_url (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 30 of file stream_mirror_config.c.
References BRIX_MIRROR_MAX_TARGETS, brix_mirror_target_t::host, ngx_memcpy, brix_mirror_target_t::port, brix_mirror_target_t::sockaddr, brix_mirror_target_t::socklen, and brix_mirror_target_t::url.
Variable Documentation
brix_mirror_opcode_names
const brix_mirror_opcode_name_t brix_mirror_opcode_names[] static
Initial value:
= {
    { "all",       ( (1u << 0)    |  (1u << 1)    |  (1u << 2)     |  (1u << 3)    |  (1u << 4)    |  (1u << 5)    |  (1u << 6)    |  (1u << 7) )       },
    { "stat",      (1u << 0)      },
    { "locate",    (1u << 1)    },
    { "open",      (1u << 2)       },
    { "read",      (1u << 3)      },
    { "readv",     (1u << 4)     },
    { "dirlist",   (1u << 5)   },
    { "statx",     (1u << 6)     },
    { "query",     (1u << 7)     },
    { "mkdir",     (1u << 8)     },
    { "rm",        (1u << 9)        },
    { "rmdir",     (1u << 10)     },
    { "mv",        (1u << 11)        },
    { "truncate",  (1u << 12)  },
    { "chmod",     (1u << 13)     },
    { "write",     (1u << 14)     },
    { NULL,       0                       },
}
Definition at line 115 of file stream_mirror_config.c.
Referenced by brix_mirror_opcode_name_bit().