nginx-xrootd: src/net/mirror/stream_wmirror_replay.c File Reference
stream_wmirror_replay.c File Reference
#include "stream_wmirror.h"
#include "stream_wmirror_internal.h"
#include "mirror.h"
#include "stream_mirror_io.h"
#include <netdb.h>
#include <sys/socket.h>
#include <endian.h>
Functions
void brix_upstream_build_bootstrap (u_char *buf)
static void wmir_read_handler (ngx_event_t *rev)
static void wmir_write_handler (ngx_event_t *wev)
static void wmir_timeout_handler (ngx_event_t *ev)
ngx_int_t wmir_flush (brix_wmirror_replay_t *r)
static ngx_int_t wmir_recv_frame (brix_wmirror_replay_t *r)
void wmir_finish (brix_wmirror_replay_t *r, int ok)
static void wmir_start (brix_wmirror_replay_t *r, ngx_msec_t timeout_ms)
void wmir_launch (ngx_stream_brix_srv_conf_t *conf, brix_wmirror_file_t *f)
Function Documentation
brix_upstream_build_bootstrap()
void brix_upstream_build_bootstrap (u_char * buf) extern
Definition at line 53 of file bootstrap.c.
Referenced by wmir_start().
wmir_finish()
void wmir_finish (brix_wmirror_replay_t * r, int ok)
Definition at line 132 of file stream_wmirror_replay.c.
References BRIX_WMIR_METRIC_INC, brix_wmirror_replay_t::conn, brix_wmirror_replay_t::data, brix_wmirror_replay_t::log, brix_wmirror_replay_t::log_diverge, brix_wmirror_replay_t::open_frame, brix_wmirror_replay_t::pool, and brix_wmirror_replay_t::tev.
Referenced by wmir_dispatch(), wmir_read_handler(), wmir_repost_read(), wmir_send_close(), wmir_send_open(), wmir_send_write(), wmir_start(), wmir_step_close(), wmir_timeout_handler(), and wmir_write_handler().
wmir_flush()
ngx_int_t wmir_flush (brix_wmirror_replay_t * r)
Definition at line 44 of file stream_wmirror_replay.c.
References brix_mirror_io_flush(), brix_wmirror_replay_t::conn, brix_wmirror_replay_t::wbuf, brix_wmirror_replay_t::wbuf_len, and brix_wmirror_replay_t::wbuf_pos.
Referenced by wmir_send_close(), wmir_send_open(), wmir_send_write(), wmir_start(), and wmir_write_handler().
wmir_launch()
void wmir_launch (ngx_stream_brix_srv_conf_t * conf, brix_wmirror_file_t * f)
Definition at line 228 of file stream_wmirror_replay.c.
References brix_wmirror_file_t::data, brix_wmirror_replay_t::data, brix_wmirror_file_t::data_len, brix_wmirror_replay_t::data_len, brix_mirror_target_t::host, brix_wmirror_replay_t::host, brix_wmirror_replay_t::log, brix_wmirror_replay_t::log_diverge, ngx_memcpy, ngx_pcalloc(), brix_wmirror_file_t::open_dlen, brix_wmirror_replay_t::open_frame, brix_wmirror_replay_t::open_frame_len, brix_wmirror_file_t::open_hdr, brix_wmirror_file_t::open_payload, brix_wmirror_replay_t::pool, brix_mirror_target_t::port, brix_wmirror_replay_t::port, brix_mirror_target_t::sockaddr, brix_wmirror_replay_t::sockaddr, brix_mirror_target_t::socklen, brix_wmirror_replay_t::socklen, and wmir_start().
Referenced by wmir_observe_close().
wmir_read_handler()
static void wmir_read_handler (ngx_event_t * rev) static
Definition at line 64 of file stream_wmirror_replay.c.
References c, brix_wmirror_replay_t::data, wmir_dispatch(), wmir_finish(), and wmir_recv_frame().
Referenced by wmir_start().
wmir_recv_frame()
static ngx_int_t wmir_recv_frame (brix_wmirror_replay_t * r) static
Definition at line 53 of file stream_wmirror_replay.c.
References brix_mirror_io_recv_frame(), brix_wmirror_replay_t::conn, brix_wmirror_replay_t::resp_body, brix_wmirror_replay_t::resp_body_pos, brix_wmirror_replay_t::resp_dlen, brix_wmirror_replay_t::resp_status, brix_wmirror_replay_t::rhdr, and brix_wmirror_replay_t::rhdr_pos.
Referenced by wmir_read_handler().
wmir_start()
static void wmir_start (brix_wmirror_replay_t * r, ngx_msec_t timeout_ms) static
Definition at line 165 of file stream_wmirror_replay.c.
References BRIX_MIRROR_DEFAULT_TIMEOUT_MS, brix_upstream_build_bootstrap(), c, brix_wmirror_replay_t::conn, brix_wmirror_replay_t::connecting, brix_wmirror_replay_t::log, brix_wmirror_replay_t::phase, brix_wmirror_replay_t::pool, brix_wmirror_replay_t::sockaddr, brix_wmirror_replay_t::socklen, brix_wmirror_replay_t::tev, brix_wmirror_replay_t::wbuf, brix_wmirror_replay_t::wbuf_len, brix_wmirror_replay_t::wbuf_pos, wmir_finish(), wmir_flush(), WMIR_HANDSHAKE, wmir_read_handler(), wmir_timeout_handler(), wmir_write_handler(), and XRD_HANDSHAKE_LEN.
Referenced by wmir_launch().
wmir_timeout_handler()
static void wmir_timeout_handler (ngx_event_t * ev) static
Definition at line 116 of file stream_wmirror_replay.c.
References wmir_finish().
Referenced by wmir_start().
wmir_write_handler()
static void wmir_write_handler (ngx_event_t * wev) static
Definition at line 89 of file stream_wmirror_replay.c.
References c, brix_wmirror_replay_t::connecting, brix_wmirror_replay_t::data, wmir_finish(), and wmir_flush().
Referenced by wmir_start().