nginx-xrootd: src/observability/metrics/stream_internal.h File Reference
stream_internal.h File Reference
#include "metrics_internal.h"
Functions
void metrics_emit_config_generation (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void metrics_emit_connections (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void metrics_emit_xfer_heap (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void metrics_emit_bytes (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void metrics_emit_wire_frames (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void metrics_emit_fault_timeouts (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void metrics_emit_io_uring (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void metrics_emit_path_depth (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void metrics_emit_ssi (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
Function Documentation
metrics_emit_bytes()
void metrics_emit_bytes (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 188 of file stream_family.c.
References metrics_emit_srv_families(), SRV_COUNTER_HDR, and SRV_FAMILY.
Referenced by brix_export_prometheus_metrics().
metrics_emit_config_generation()
void metrics_emit_config_generation (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 114 of file stream_family.c.
References ngx_brix_metrics_t::config_generation, and mw_printf().
Referenced by brix_export_prometheus_metrics().
metrics_emit_connections()
void metrics_emit_connections (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 133 of file stream_family.c.
References metrics_emit_srv_families(), SRV_COUNTER_HDR, SRV_FAMILY, and SRV_GAUGE_HDR.
Referenced by brix_export_prometheus_metrics().
metrics_emit_fault_timeouts()
void metrics_emit_fault_timeouts (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 295 of file stream_family.c.
References metrics_emit_srv_families(), SRV_COUNTER_HDR, and SRV_FAMILY.
Referenced by brix_export_prometheus_metrics().
metrics_emit_io_uring()
void metrics_emit_io_uring (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 329 of file stream_family.c.
References metrics_emit_srv_families(), SRV_COUNTER_HDR, SRV_FAMILY, and SRV_GAUGE_HDR.
Referenced by brix_export_prometheus_metrics().
metrics_emit_path_depth()
void metrics_emit_path_depth (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 357 of file stream_family.c.
References metrics_emit_srv_families(), SRV_COUNTER_HDR, and SRV_FAMILY.
Referenced by brix_export_prometheus_metrics().
metrics_emit_ssi()
void metrics_emit_ssi (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 379 of file stream_family.c.
References metrics_emit_srv_families(), SRV_COUNTER_HDR, and SRV_FAMILY.
Referenced by brix_export_prometheus_metrics().
metrics_emit_wire_frames()
void metrics_emit_wire_frames (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 249 of file stream_family.c.
References metrics_emit_srv_families(), SRV_COUNTER_HDR, and SRV_FAMILY.
Referenced by brix_export_prometheus_metrics().
metrics_emit_xfer_heap()
void metrics_emit_xfer_heap (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 157 of file stream_family.c.
References metrics_emit_srv_families(), SRV_COUNTER_HDR, SRV_FAMILY, and SRV_GAUGE_HDR.
Referenced by brix_export_prometheus_metrics().