nginx-xrootd: src/net/mirror/stream_mirror_launch.c File Reference
stream_mirror_launch.c File Reference
#include "stream_mirror.h"
#include <netdb.h>
#include <sys/socket.h>
#include "stream_mirror_internal.h"
#include "observability/metrics/metrics_macros.h"
Macros
#define BRIX_MIRROR_OPEN_WRITE_FLAGS (kXR_delete | kXR_new | kXR_open_updt | kXR_open_apnd | kXR_mkpath)
Functions
static ngx_uint_t brix_mirror_opcode_bit (uint16_t reqid)
static int brix_mirror_request_replayable (brix_ctx_t *ctx)
static int brix_mirror_write_op_allowed (ngx_uint_t opbit, ngx_stream_brix_srv_conf_t *conf)
static int brix_stream_mirror_eligible (brix_ctx_t *ctx, ngx_stream_brix_srv_conf_t *conf, ngx_uint_t *opbit_out)
static void brix_stream_mirror_launch_target (brix_ctx_t *ctx, brix_mirror_target_t *target, ngx_stream_brix_srv_conf_t *conf, int primary_ok)
void brix_stream_mirror_maybe (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, ngx_int_t primary_rc)
Macro Definition Documentation
BRIX_MIRROR_OPEN_WRITE_FLAGS
#define BRIX_MIRROR_OPEN_WRITE_FLAGS (kXR_delete | kXR_new | kXR_open_updt | kXR_open_apnd | kXR_mkpath)
Definition at line 60 of file stream_mirror_launch.c.
Function Documentation
brix_mirror_opcode_bit()
static ngx_uint_t brix_mirror_opcode_bit (uint16_t reqid) static
Definition at line 32 of file stream_mirror_launch.c.
References BRIX_MIRROR_OP_CHMOD, BRIX_MIRROR_OP_DIRLIST, BRIX_MIRROR_OP_LOCATE, BRIX_MIRROR_OP_MKDIR, BRIX_MIRROR_OP_MV, BRIX_MIRROR_OP_OPEN, BRIX_MIRROR_OP_QUERY, BRIX_MIRROR_OP_READ, BRIX_MIRROR_OP_READV, BRIX_MIRROR_OP_RM, BRIX_MIRROR_OP_RMDIR, BRIX_MIRROR_OP_STAT, BRIX_MIRROR_OP_STATX, BRIX_MIRROR_OP_TRUNCATE, kXR_chmod, kXR_dirlist, kXR_locate, kXR_mkdir, kXR_mv, kXR_open, kXR_query, kXR_read, kXR_readv, kXR_rm, kXR_rmdir, kXR_stat, kXR_statx, and kXR_truncate.
Referenced by brix_stream_mirror_eligible().
brix_mirror_request_replayable()
static int brix_mirror_request_replayable (brix_ctx_t * ctx) static
Definition at line 82 of file stream_mirror_launch.c.
References BRIX_MIRROR_OPEN_WRITE_FLAGS, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, brix_ctx_recv_t::hdr_buf, kXR_chmod, kXR_dirlist, kXR_locate, kXR_mkdir, kXR_mv, kXR_open, kXR_query, kXR_rm, kXR_rmdir, kXR_stat, kXR_statx, kXR_truncate, ngx_memcpy, and brix_ctx_t::recv.
Referenced by brix_stream_mirror_eligible().
brix_mirror_write_op_allowed()
static int brix_mirror_write_op_allowed (ngx_uint_t opbit, ngx_stream_brix_srv_conf_t * conf) static
Definition at line 131 of file stream_mirror_launch.c.
References BRIX_MIRROR_OP_WRITE, and BRIX_MIRROR_OP_WRITE_ALL.
Referenced by brix_stream_mirror_eligible().
brix_stream_mirror_eligible()
static int brix_stream_mirror_eligible (brix_ctx_t * ctx, ngx_stream_brix_srv_conf_t * conf, ngx_uint_t * opbit_out) static
Definition at line 155 of file stream_mirror_launch.c.
References BRIX_MIR_METRIC_INC, BRIX_MIRROR_MAX_PAYLOAD, brix_mirror_opcode_bit(), brix_mirror_request_replayable(), brix_mirror_should_sample(), brix_mirror_write_op_allowed(), brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, and brix_ctx_t::recv.
Referenced by brix_stream_mirror_maybe().
brix_stream_mirror_launch_target()
static void brix_stream_mirror_launch_target (brix_ctx_t * ctx, brix_mirror_target_t * target, ngx_stream_brix_srv_conf_t * conf, int primary_ok) static
Definition at line 218 of file stream_mirror_launch.c.
References brix_mir_start(), brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, brix_ctx_recv_t::hdr_buf, brix_mirror_target_t::host, brix_stream_mirror_t::host, brix_stream_mirror_t::log, brix_stream_mirror_t::log_diverge, ngx_memcpy, ngx_pcalloc(), brix_ctx_recv_t::payload, brix_stream_mirror_t::phase, brix_stream_mirror_t::pool, brix_mirror_target_t::port, brix_stream_mirror_t::port, brix_stream_mirror_t::primary_ok, brix_ctx_t::recv, brix_stream_mirror_t::saved_dlen, brix_stream_mirror_t::saved_hdr, brix_stream_mirror_t::saved_opcode, brix_stream_mirror_t::saved_payload, brix_mirror_target_t::sockaddr, brix_stream_mirror_t::sockaddr, brix_mirror_target_t::socklen, brix_stream_mirror_t::socklen, and XRD_MIR_HANDSHAKE.
Referenced by brix_stream_mirror_maybe().
brix_stream_mirror_maybe()
void brix_stream_mirror_maybe (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, ngx_int_t primary_rc)
Definition at line 267 of file stream_mirror_launch.c.
References brix_stream_mirror_eligible(), brix_stream_mirror_launch_target(), and c.
Referenced by brix_dispatch().