nginx-xrootd: src/observability/metrics/stream.c File Reference
stream.c File Reference
#include "metrics_internal.h"
Macros
#define BRIX_EXPORT_SRV_COUNTER(metric_name, help_text, field_name)
#define BRIX_EXPORT_DEPTH_VIOLATIONS
#define BRIX_EXPORT_SSI_COUNTER(name, field, help)
Functions
void brix_export_prometheus_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void brix_export_pmark_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void brix_export_resilience_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
Variables
static const char * brix_op_names [37]
Macro Definition Documentation
BRIX_EXPORT_DEPTH_VIOLATIONS
#define BRIX_EXPORT_DEPTH_VIOLATIONS
Value:
    do {                                                                         \
        mw_printf(mw, "# HELP "                                                  \
                     "brix_path_depth_violations_total "                       \
                         "Requests rejected because path depth exceeded "         \
                         "BRIX_MAX_WALK_DEPTH. Prevents CPU exhaustion from "   \
                         "malicious symlink traversal chains or deep nesting.\n"  \
                     "# TYPE brix_path_depth_violations_total counter\n");     \
        for (i = 0; i < BRIX_METRICS_MAX_SERVERS; i++) {                        \
            srv = &shm->servers[i];                                              \
            if (!srv->in_use) { continue; }                                      \
            ngx_snprintf((u_char *) port_str, sizeof(port_str),                  \
                         "%ui%Z", srv->port);                                    \
            mw_printf(mw,                                                      \
                     "brix_path_depth_violations_total"                       \
                         "{port=\"%s\",auth=\"%s\"} %lu\n",                    \
                     port_str, srv->auth,                                       \
                     (unsigned long) ngx_atomic_fetch_add(                      \
                         &srv->path_depth_violations_total, 0));                 \
        }                                                                        \
    } while (0)
BRIX_EXPORT_SRV_COUNTER
#define BRIX_EXPORT_SRV_COUNTER (metric_name, help_text, field_name)
Value:
    do {                                                                     \
        mw_printf(mw, "# HELP " metric_name " " help_text "\n"            \
                      "# TYPE " metric_name " counter\n");                 \
        for (i = 0; i < BRIX_METRICS_MAX_SERVERS; i++) {                   \
            srv = &shm->servers[i];                                          \
            if (!srv->in_use) { continue; }                                  \
            ngx_snprintf((u_char *) port_str, sizeof(port_str),              \
                         "%ui%Z", srv->port);                               \
            mw_printf(mw, metric_name "{port=\"%s\",auth=\"%s\"} %lu\n",   \
                      port_str, srv->auth,                                   \
                      (unsigned long) ngx_atomic_fetch_add(                  \
                          &srv->field_name, 0));                             \
        }                                                                    \
    } while (0)
BRIX_EXPORT_SSI_COUNTER
#define BRIX_EXPORT_SSI_COUNTER (name, field, help)
Value:
    do {                                                                      \
        mw_printf(mw, "# HELP " name " " help "\n# TYPE " name " counter\n"); \
        for (i = 0; i < BRIX_METRICS_MAX_SERVERS; i++) {                    \
            srv = &shm->servers[i];                                           \
            if (!srv->in_use) { continue; }                                   \
            ngx_snprintf((u_char *) port_str, sizeof(port_str),               \
                         "%ui%Z", srv->port);                                 \
            mw_printf(mw, name "{port=\"%s\",auth=\"%s\"} %lu\n",             \
                      port_str, srv->auth,                                     \
                      (unsigned long) ngx_atomic_fetch_add(&srv->field, 0));  \
        }                                                                     \
    } while (0)
Function Documentation
brix_export_pmark_metrics()
void brix_export_pmark_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 535 of file stream.c.
References mw_emit_scalar(), ngx_brix_metrics_t::pmark_firefly_dropped_total, ngx_brix_metrics_t::pmark_firefly_sent_total, ngx_brix_metrics_t::pmark_flowlabel_failed_total, ngx_brix_metrics_t::pmark_flowlabel_set_total, ngx_brix_metrics_t::pmark_flows_ended_total, ngx_brix_metrics_t::pmark_flows_started_total, and ngx_brix_metrics_t::pmark_map_unresolved_total.
Referenced by brix_export_prometheus_metrics().
brix_export_prometheus_metrics()
void brix_export_prometheus_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 75 of file stream.c.
References ngx_brix_srv_metrics_t::auth, brix_export_cluster_metrics(), brix_export_cvmfs_metrics(), BRIX_EXPORT_DEPTH_VIOLATIONS, brix_export_frm_metrics(), brix_export_pmark_metrics(), brix_export_ratelimit_metrics(), brix_export_resilience_metrics(), brix_export_s3_metrics(), BRIX_EXPORT_SRV_COUNTER, BRIX_EXPORT_SSI_COUNTER, brix_export_stream_cache_metrics(), brix_export_stream_proxy_metrics(), brix_export_stream_tracking_metrics(), brix_export_unified_metrics(), brix_export_webdav_metrics(), BRIX_METRICS_MAX_SERVERS, BRIX_NOPS, brix_op_names, ngx_brix_srv_metrics_t::budget_waits_total, ngx_brix_srv_metrics_t::bytes_rx_ipv4_total, ngx_brix_srv_metrics_t::bytes_rx_ipv6_total, ngx_brix_srv_metrics_t::bytes_rx_total, ngx_brix_srv_metrics_t::bytes_tx_ipv4_total, ngx_brix_srv_metrics_t::bytes_tx_ipv6_total, ngx_brix_srv_metrics_t::bytes_tx_total, ngx_brix_metrics_t::config_generation, ngx_brix_srv_metrics_t::connections_active, ngx_brix_srv_metrics_t::connections_total, ngx_brix_srv_metrics_t::in_use, ngx_brix_srv_metrics_t::io_uring_active, ngx_brix_metrics_t::mirror_http_divergence_total, ngx_brix_metrics_t::mirror_http_dropped_total, ngx_brix_metrics_t::mirror_http_errors_total, ngx_brix_metrics_t::mirror_http_total, ngx_brix_metrics_t::mirror_stream_divergence_total, ngx_brix_metrics_t::mirror_stream_dropped_total, ngx_brix_metrics_t::mirror_stream_errors_total, ngx_brix_metrics_t::mirror_stream_total, mw_printf(), ngx_brix_srv_metrics_t::op_err, ngx_brix_srv_metrics_t::op_ok, ngx_brix_srv_metrics_t::port, ngx_brix_srv_metrics_t::proto_root_bytes_rx_total, ngx_brix_srv_metrics_t::proto_root_bytes_tx_total, ngx_brix_metrics_t::registry_full_total, ngx_brix_metrics_t::servers, ngx_brix_metrics_t::session_evict_total, ngx_brix_metrics_t::session_registry_full_total, ngx_brix_srv_metrics_t::xfer_heap_high_water, and ngx_brix_srv_metrics_t::xfer_heap_in_use.
Referenced by ngx_http_brix_metrics_handler().
brix_export_resilience_metrics()
void brix_export_resilience_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 564 of file stream.c.
References ngx_brix_metrics_t::acc_dns_breaker_open_total, ngx_brix_metrics_t::acc_nss_breaker_open_total, ngx_brix_metrics_t::auth_l1_hits_total, ngx_brix_metrics_t::auth_l1_misses_total, ngx_brix_metrics_t::cms_cap_rejections_total, ngx_brix_metrics_t::cms_frame_yields_total, ngx_brix_metrics_t::cms_idle_closes_total, ngx_brix_metrics_t::cms_login_timeouts_total, ngx_brix_metrics_t::cms_read_timeouts_total, mw_emit_scalar(), and ngx_brix_metrics_t::ocsp_timeouts_total.
Referenced by brix_export_prometheus_metrics().
Variable Documentation
brix_op_names
const char* brix_op_names[37] static
Definition at line 31 of file stream.c.
Referenced by brix_export_prometheus_metrics().