nginx-xrootd: src/net/mirror/stream_mirror.h File Reference
stream_mirror.h File Reference
#include "core/ngx_brix_module.h"
Functions
void brix_stream_mirror_maybe (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, ngx_int_t primary_rc)
char * brix_stream_mirror_set_url (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_stream_mirror_set_opcodes (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * brix_stream_mirror_set_exclude_opcodes (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Function Documentation
brix_stream_mirror_maybe()
void brix_stream_mirror_maybe (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, ngx_int_t primary_rc)
Definition at line 483 of file stream_mirror.c.
References BRIX_MIR_METRIC_INC, brix_mir_start(), BRIX_MIRROR_MAX_PAYLOAD, BRIX_MIRROR_OP_WRITE, BRIX_MIRROR_OP_WRITE_ALL, brix_mirror_opcode_bit(), brix_mirror_request_replayable(), brix_mirror_should_sample(), brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, brix_mirror_conf_t::enabled, brix_ctx_recv_t::hdr_buf, brix_mirror_target_t::host, brix_stream_mirror_t::host, brix_stream_mirror_t::log, brix_mirror_conf_t::log_diverge, brix_stream_mirror_t::log_diverge, ngx_stream_brix_srv_conf_t::mirror, brix_mirror_conf_t::mirror_writes, brix_mirror_conf_t::opcode_exclude_mask, brix_mirror_conf_t::opcode_mask, brix_ctx_recv_t::payload, brix_stream_mirror_t::phase, brix_stream_mirror_t::pool, brix_mirror_target_t::port, brix_stream_mirror_t::port, brix_stream_mirror_t::primary_ok, brix_ctx_t::recv, brix_mirror_conf_t::sample_pct, brix_stream_mirror_t::saved_dlen, brix_stream_mirror_t::saved_hdr, brix_stream_mirror_t::saved_opcode, brix_stream_mirror_t::saved_payload, brix_mirror_target_t::sockaddr, brix_stream_mirror_t::sockaddr, brix_mirror_target_t::socklen, brix_stream_mirror_t::socklen, brix_mirror_conf_t::targets, brix_mirror_conf_t::timeout_ms, and XRD_MIR_HANDSHAKE.
Referenced by brix_dispatch().
brix_stream_mirror_set_exclude_opcodes()
char * brix_stream_mirror_set_exclude_opcodes (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 724 of file stream_mirror.c.
References brix_mirror_parse_opcode_args(), ngx_stream_brix_srv_conf_t::mirror, and brix_mirror_conf_t::opcode_exclude_mask.
brix_stream_mirror_set_opcodes()
char * brix_stream_mirror_set_opcodes (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 710 of file stream_mirror.c.
References brix_mirror_parse_opcode_args(), ngx_stream_brix_srv_conf_t::mirror, and brix_mirror_conf_t::opcode_mask.
brix_stream_mirror_set_url()
char * brix_stream_mirror_set_url (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 590 of file stream_mirror.c.
References BRIX_MIRROR_MAX_TARGETS, brix_mirror_target_t::host, ngx_stream_brix_srv_conf_t::mirror, brix_mirror_target_t::port, brix_mirror_target_t::sockaddr, brix_mirror_target_t::socklen, brix_mirror_conf_t::targets, and brix_mirror_target_t::url.