nginx-xrootd: src/net/mirror/stream_wmirror.c File Reference
stream_wmirror.c File Reference
#include "stream_wmirror.h"
#include "mirror.h"
#include "stream_mirror_io.h"
#include "observability/metrics/metrics_macros.h"
#include <netdb.h>
#include <sys/socket.h>
#include <endian.h>
Data Structures
struct brix_wmirror_file_t
struct brix_wmirror_conn_t
struct brix_wmirror_replay_t
Macros
#define BRIX_WMIRROR_FILE_CAP (4u * 1024u * 1024u) /* 4 MiB per file */
#define BRIX_WMIRROR_CONN_CAP (16u * 1024u * 1024u) /* 16 MiB per connection */
#define BRIX_WMIR_METRIC_INC(field)
Enumerations
enum wmir_phase_t {
WMIR_HANDSHAKE = 0 , WMIR_PROTOCOL , WMIR_LOGIN , WMIR_OPEN ,
WMIR_WRITE , WMIR_CLOSE
}
Functions
void brix_upstream_build_bootstrap (u_char *buf)
static void wmir_read_handler (ngx_event_t *rev)
static void wmir_write_handler (ngx_event_t *wev)
static void wmir_timeout_handler (ngx_event_t *ev)
static void wmir_finish (brix_wmirror_replay_t *r, int ok)
static ngx_int_t wmir_flush (brix_wmirror_replay_t *r)
static void wmir_reset_frame (brix_wmirror_replay_t *r)
static void wmir_send_open (brix_wmirror_replay_t *r)
static void wmir_send_write (brix_wmirror_replay_t *r)
static void wmir_send_close (brix_wmirror_replay_t *r)
static ngx_int_t wmir_recv_frame (brix_wmirror_replay_t *r)
static int wmir_status_ok (uint16_t st)
static void wmir_dispatch (brix_wmirror_replay_t *r)
static void wmir_start (brix_wmirror_replay_t *r, ngx_msec_t timeout_ms)
static void wmir_launch (ngx_stream_brix_srv_conf_t *conf, brix_wmirror_file_t *f)
static void wmir_file_reset (brix_wmirror_conn_t *wm, brix_wmirror_file_t *f)
static int wmir_gate (ngx_stream_brix_srv_conf_t *conf)
void brix_stream_wmirror_on_open (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, int client_idx, int is_write)
void brix_stream_wmirror_observe (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, ngx_int_t primary_rc)
void brix_stream_wmirror_cleanup (brix_ctx_t *ctx)
Macro Definition Documentation
BRIX_WMIR_METRIC_INC
#define BRIX_WMIR_METRIC_INC (field)
Value:
    do {                                                                     \
        ngx_brix_metrics_t *_m = brix_metrics_shared();                  \
        if (_m != NULL) { (void) ngx_atomic_fetch_add(&_m->field, 1); }      \
    } while (0)
Definition at line 39 of file stream_wmirror.c.
BRIX_WMIRROR_CONN_CAP
#define BRIX_WMIRROR_CONN_CAP (16u * 1024u * 1024u) /* 16 MiB per connection */
Definition at line 37 of file stream_wmirror.c.
BRIX_WMIRROR_FILE_CAP
#define BRIX_WMIRROR_FILE_CAP (4u * 1024u * 1024u) /* 4 MiB per file */
Definition at line 36 of file stream_wmirror.c.
Enumeration Type Documentation
wmir_phase_t
enum wmir_phase_t
Enumerator
WMIR_HANDSHAKE
WMIR_PROTOCOL
WMIR_LOGIN
WMIR_OPEN
WMIR_WRITE
WMIR_CLOSE
Definition at line 69 of file stream_wmirror.c.
Function Documentation
brix_stream_wmirror_cleanup()
void brix_stream_wmirror_cleanup (brix_ctx_t * ctx)
Definition at line 721 of file stream_wmirror.c.
References BRIX_MAX_FILES, brix_wmirror_conn_t::files, wmir_file_reset(), and brix_ctx_t::wmirror.
Referenced by brix_release_disconnect_owned_buffers().
brix_stream_wmirror_observe()
void brix_stream_wmirror_observe (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, ngx_int_t primary_rc)
Definition at line 629 of file stream_wmirror.c.
References brix_wmirror_file_t::aborted, brix_wmirror_file_t::active, BRIX_MAX_FILES, BRIX_WMIR_METRIC_INC, BRIX_WMIRROR_CONN_CAP, BRIX_WMIRROR_FILE_CAP, c, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, brix_wmirror_file_t::data, brix_wmirror_file_t::data_len, brix_wmirror_conn_t::files, brix_ctx_recv_t::hdr_buf, kXR_close, kXR_pgwrite, kXR_write, brix_wmirror_file_t::next_off, ngx_memcpy, brix_ctx_recv_t::payload, brix_ctx_t::recv, brix_wmirror_conn_t::total_buffered, wmir_file_reset(), wmir_gate(), wmir_launch(), and brix_ctx_t::wmirror.
Referenced by brix_dispatch().
brix_stream_wmirror_on_open()
void brix_stream_wmirror_on_open (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, int client_idx, int is_write)
Definition at line 580 of file stream_wmirror.c.
References brix_wmirror_file_t::aborted, brix_wmirror_file_t::active, BRIX_MAX_FILES, BRIX_WMIRROR_FILE_CAP, c, brix_ctx_recv_t::cur_dlen, brix_wmirror_conn_t::files, brix_ctx_recv_t::hdr_buf, brix_wmirror_file_t::next_off, ngx_memcpy, ngx_pcalloc(), brix_wmirror_file_t::open_dlen, brix_wmirror_file_t::open_hdr, brix_wmirror_file_t::open_payload, brix_ctx_recv_t::payload, brix_ctx_t::recv, wmir_file_reset(), wmir_gate(), and brix_ctx_t::wmirror.
Referenced by brix_open_resolved_file().
brix_upstream_build_bootstrap()
void brix_upstream_build_bootstrap (u_char * buf) extern
Definition at line 32 of file bootstrap.c.
Referenced by wmir_start().
wmir_dispatch()
static void wmir_dispatch (brix_wmirror_replay_t * r) static
Definition at line 242 of file stream_wmirror.c.
References brix_wmirror_replay_t::conn, kXR_authmore, kXR_gotoTLS, kXR_ok, ngx_memcpy, brix_wmirror_replay_t::phase, brix_wmirror_replay_t::resp_body, brix_wmirror_replay_t::resp_dlen, brix_wmirror_replay_t::resp_status, brix_wmirror_replay_t::shadow_fhandle, WMIR_CLOSE, wmir_finish(), WMIR_HANDSHAKE, WMIR_LOGIN, WMIR_OPEN, WMIR_PROTOCOL, wmir_reset_frame(), wmir_send_close(), wmir_send_open(), wmir_send_write(), wmir_status_ok(), and WMIR_WRITE.
Referenced by wmir_read_handler().
wmir_file_reset()
static void wmir_file_reset (brix_wmirror_conn_t * wm, brix_wmirror_file_t * f) static
Definition at line 537 of file stream_wmirror.c.
References brix_wmirror_file_t::data, brix_wmirror_file_t::data_len, brix_wmirror_file_t::open_payload, and brix_wmirror_conn_t::total_buffered.
Referenced by brix_stream_wmirror_cleanup(), brix_stream_wmirror_observe(), and brix_stream_wmirror_on_open().
wmir_finish()
static void wmir_finish (brix_wmirror_replay_t * r, int ok) static
Definition at line 384 of file stream_wmirror.c.
References BRIX_WMIR_METRIC_INC, brix_wmirror_replay_t::conn, brix_wmirror_replay_t::data, brix_wmirror_replay_t::log, brix_wmirror_replay_t::log_diverge, brix_wmirror_replay_t::open_frame, brix_wmirror_replay_t::pool, and brix_wmirror_replay_t::tev.
Referenced by wmir_dispatch(), wmir_read_handler(), wmir_send_close(), wmir_send_open(), wmir_send_write(), wmir_start(), wmir_timeout_handler(), and wmir_write_handler().
wmir_flush()
static ngx_int_t wmir_flush (brix_wmirror_replay_t * r) static
Definition at line 121 of file stream_wmirror.c.
References brix_mirror_io_flush(), brix_wmirror_replay_t::conn, brix_wmirror_replay_t::wbuf, brix_wmirror_replay_t::wbuf_len, and brix_wmirror_replay_t::wbuf_pos.
Referenced by wmir_send_close(), wmir_send_open(), wmir_send_write(), wmir_start(), and wmir_write_handler().
wmir_gate()
static int wmir_gate (ngx_stream_brix_srv_conf_t * conf) static
Definition at line 555 of file stream_wmirror.c.
References BRIX_MIRROR_OP_WRITE, brix_mirror_conf_t::enabled, ngx_stream_brix_srv_conf_t::mirror, brix_mirror_conf_t::mirror_writes, brix_mirror_conf_t::opcode_exclude_mask, brix_mirror_conf_t::opcode_mask, and brix_mirror_conf_t::targets.
Referenced by brix_stream_wmirror_observe(), and brix_stream_wmirror_on_open().
wmir_launch()
static void wmir_launch (ngx_stream_brix_srv_conf_t * conf, brix_wmirror_file_t * f) static
Definition at line 479 of file stream_wmirror.c.
References brix_wmirror_file_t::data, brix_wmirror_replay_t::data, brix_wmirror_file_t::data_len, brix_wmirror_replay_t::data_len, brix_mirror_target_t::host, brix_wmirror_replay_t::host, brix_wmirror_replay_t::log, brix_mirror_conf_t::log_diverge, brix_wmirror_replay_t::log_diverge, ngx_stream_brix_srv_conf_t::mirror, ngx_memcpy, ngx_pcalloc(), brix_wmirror_file_t::open_dlen, brix_wmirror_replay_t::open_frame, brix_wmirror_replay_t::open_frame_len, brix_wmirror_file_t::open_hdr, brix_wmirror_file_t::open_payload, brix_wmirror_replay_t::pool, brix_mirror_target_t::port, brix_wmirror_replay_t::port, brix_mirror_target_t::sockaddr, brix_wmirror_replay_t::sockaddr, brix_mirror_target_t::socklen, brix_wmirror_replay_t::socklen, brix_mirror_conf_t::targets, brix_mirror_conf_t::timeout_ms, and wmir_start().
Referenced by brix_stream_wmirror_observe().
wmir_read_handler()
static void wmir_read_handler (ngx_event_t * rev) static
Definition at line 316 of file stream_wmirror.c.
References c, brix_wmirror_replay_t::data, wmir_dispatch(), wmir_finish(), and wmir_recv_frame().
Referenced by wmir_start().
wmir_recv_frame()
static ngx_int_t wmir_recv_frame (brix_wmirror_replay_t * r) static
Definition at line 224 of file stream_wmirror.c.
References brix_mirror_io_recv_frame(), brix_wmirror_replay_t::conn, brix_wmirror_replay_t::resp_body, brix_wmirror_replay_t::resp_body_pos, brix_wmirror_replay_t::resp_dlen, brix_wmirror_replay_t::resp_status, brix_wmirror_replay_t::rhdr, and brix_wmirror_replay_t::rhdr_pos.
Referenced by wmir_read_handler().
wmir_reset_frame()
static void wmir_reset_frame (brix_wmirror_replay_t * r) static
Definition at line 130 of file stream_wmirror.c.
References brix_wmirror_replay_t::resp_body, brix_wmirror_replay_t::resp_body_pos, brix_wmirror_replay_t::resp_dlen, brix_wmirror_replay_t::resp_status, and brix_wmirror_replay_t::rhdr_pos.
Referenced by wmir_dispatch(), wmir_send_close(), wmir_send_open(), and wmir_send_write().
wmir_send_close()
static void wmir_send_close (brix_wmirror_replay_t * r) static
Definition at line 205 of file stream_wmirror.c.
References kXR_close, ngx_memcpy, brix_wmirror_replay_t::phase, brix_wmirror_replay_t::pool, brix_wmirror_replay_t::shadow_fhandle, brix_wmirror_replay_t::wbuf, brix_wmirror_replay_t::wbuf_len, brix_wmirror_replay_t::wbuf_pos, WMIR_CLOSE, wmir_finish(), wmir_flush(), and wmir_reset_frame().
Referenced by wmir_dispatch().
wmir_send_open()
static void wmir_send_open (brix_wmirror_replay_t * r) static
Definition at line 148 of file stream_wmirror.c.
References ngx_memcpy, brix_wmirror_replay_t::open_frame, brix_wmirror_replay_t::open_frame_len, brix_wmirror_replay_t::phase, brix_wmirror_replay_t::pool, brix_wmirror_replay_t::wbuf, brix_wmirror_replay_t::wbuf_len, brix_wmirror_replay_t::wbuf_pos, wmir_finish(), wmir_flush(), WMIR_OPEN, and wmir_reset_frame().
Referenced by wmir_dispatch().
wmir_send_write()
static void wmir_send_write (brix_wmirror_replay_t * r) static
Definition at line 177 of file stream_wmirror.c.
References brix_wmirror_replay_t::data, brix_wmirror_replay_t::data_len, kXR_write, ngx_memcpy, brix_wmirror_replay_t::phase, brix_wmirror_replay_t::pool, brix_wmirror_replay_t::shadow_fhandle, brix_wmirror_replay_t::wbuf, brix_wmirror_replay_t::wbuf_len, brix_wmirror_replay_t::wbuf_pos, wmir_finish(), wmir_flush(), wmir_reset_frame(), and WMIR_WRITE.
Referenced by wmir_dispatch().
wmir_start()
static void wmir_start (brix_wmirror_replay_t * r, ngx_msec_t timeout_ms) static
Definition at line 417 of file stream_wmirror.c.
References brix_upstream_build_bootstrap(), c, brix_wmirror_replay_t::conn, brix_wmirror_replay_t::connecting, brix_wmirror_replay_t::log, brix_wmirror_replay_t::phase, brix_wmirror_replay_t::pool, brix_wmirror_replay_t::sockaddr, brix_wmirror_replay_t::socklen, brix_wmirror_replay_t::tev, brix_wmirror_replay_t::wbuf, brix_wmirror_replay_t::wbuf_len, brix_wmirror_replay_t::wbuf_pos, wmir_finish(), wmir_flush(), WMIR_HANDSHAKE, wmir_read_handler(), wmir_timeout_handler(), wmir_write_handler(), and XRD_HANDSHAKE_LEN.
Referenced by wmir_launch().
wmir_status_ok()
static int wmir_status_ok (uint16_t st) static
Definition at line 234 of file stream_wmirror.c.
References kXR_ok, and kXR_oksofar.
Referenced by wmir_dispatch().
wmir_timeout_handler()
static void wmir_timeout_handler (ngx_event_t * ev) static
Definition at line 368 of file stream_wmirror.c.
References wmir_finish().
Referenced by wmir_start().
wmir_write_handler()
static void wmir_write_handler (ngx_event_t * wev) static
Definition at line 341 of file stream_wmirror.c.
References c, brix_wmirror_replay_t::connecting, brix_wmirror_replay_t::data, wmir_finish(), and wmir_flush().
Referenced by wmir_start().