nginx-xrootd: src/observability/metrics/stream_cache.c File Reference
stream_cache.c File Reference
#include "metrics_internal.h"
#include "core/compat/fs_usage.h"
Functions
static ngx_int_t brix_cache_statvfs (const char *root, uint64_t *total, uint64_t *used, uint64_t *available, ngx_uint_t *occupancy_ppm)
static void stream_cache_port_str (char *buf, size_t buf_size, ngx_uint_t port)
static void stream_cache_emit_occupancy_ratio (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
static void stream_cache_emit_eviction_threshold (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
static void stream_cache_emit_cache_bytes (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
static void stream_cache_emit_eviction_counter (metrics_writer_t *mw, ngx_brix_metrics_t *shm, const char *header, const char *metric_name, size_t counter_off)
static void stream_cache_emit_eviction_counters (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
static void stream_cache_emit_dirty_reaped (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
static void stream_cache_emit_wt_single (metrics_writer_t *mw, ngx_brix_metrics_t *shm, const char *header, const char *metric_name, size_t counter_off)
static void stream_cache_emit_wt_flushes (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
static void stream_cache_emit_write_through (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void brix_export_stream_cache_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
Function Documentation
brix_cache_statvfs()
static ngx_int_t brix_cache_statvfs (const char * root, uint64_t * total, uint64_t * used, uint64_t * available, ngx_uint_t * occupancy_ppm) static
Definition at line 27 of file stream_cache.c.
References brix_fs_usage_t::available_bytes, brix_fs_usage_stat(), brix_fs_usage_t::occupancy_bytes, brix_fs_usage_t::occupancy_ppm, and brix_fs_usage_t::total_bytes.
Referenced by stream_cache_emit_cache_bytes(), and stream_cache_emit_occupancy_ratio().
brix_export_stream_cache_metrics()
void brix_export_stream_cache_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 401 of file stream_cache.c.
References stream_cache_emit_cache_bytes(), stream_cache_emit_dirty_reaped(), stream_cache_emit_eviction_counters(), stream_cache_emit_eviction_threshold(), stream_cache_emit_occupancy_ratio(), and stream_cache_emit_write_through().
Referenced by brix_export_prometheus_metrics().
stream_cache_emit_cache_bytes()
static void stream_cache_emit_cache_bytes (metrics_writer_t * mw, ngx_brix_metrics_t * shm) static
Definition at line 136 of file stream_cache.c.
References ngx_brix_srv_metrics_t::auth, brix_cache_statvfs(), BRIX_METRICS_MAX_SERVERS, ngx_brix_srv_metrics_t::cache_enabled, ngx_brix_srv_metrics_t::cache_root, ngx_brix_srv_metrics_t::in_use, mw_printf(), ngx_brix_srv_metrics_t::port, ngx_brix_metrics_t::servers, and stream_cache_port_str().
Referenced by brix_export_stream_cache_metrics().
stream_cache_emit_dirty_reaped()
static void stream_cache_emit_dirty_reaped (metrics_writer_t * mw, ngx_brix_metrics_t * shm) static
Definition at line 248 of file stream_cache.c.
References ngx_brix_srv_metrics_t::auth, BRIX_CACHE_REAP_ABANDONED, BRIX_CACHE_REAP_COMPLETED, BRIX_CACHE_REAP_INCOMPLETE, BRIX_CACHE_REAP_REASON_COUNT, BRIX_METRICS_MAX_SERVERS, ngx_brix_srv_metrics_t::cache_dirty_reaped, ngx_brix_srv_metrics_t::in_use, mw_printf(), ngx_brix_srv_metrics_t::port, ngx_brix_metrics_t::servers, and stream_cache_port_str().
Referenced by brix_export_stream_cache_metrics().
stream_cache_emit_eviction_counter()
static void stream_cache_emit_eviction_counter (metrics_writer_t * mw, ngx_brix_metrics_t * shm, const char * header, const char * metric_name, size_t counter_off) static
Definition at line 182 of file stream_cache.c.
References ngx_brix_srv_metrics_t::auth, BRIX_METRICS_MAX_SERVERS, ngx_brix_srv_metrics_t::cache_enabled, ngx_brix_srv_metrics_t::in_use, mw_printf(), ngx_brix_srv_metrics_t::port, ngx_brix_metrics_t::servers, and stream_cache_port_str().
Referenced by stream_cache_emit_eviction_counters().
stream_cache_emit_eviction_counters()
static void stream_cache_emit_eviction_counters (metrics_writer_t * mw, ngx_brix_metrics_t * shm) static
Definition at line 212 of file stream_cache.c.
References stream_cache_emit_eviction_counter().
Referenced by brix_export_stream_cache_metrics().
stream_cache_emit_eviction_threshold()
static void stream_cache_emit_eviction_threshold (metrics_writer_t * mw, ngx_brix_metrics_t * shm) static
Definition at line 105 of file stream_cache.c.
References ngx_brix_srv_metrics_t::auth, BRIX_METRICS_MAX_SERVERS, ngx_brix_srv_metrics_t::cache_enabled, ngx_brix_srv_metrics_t::cache_eviction_threshold, ngx_brix_srv_metrics_t::in_use, mw_printf(), ngx_brix_srv_metrics_t::port, ngx_brix_metrics_t::servers, and stream_cache_port_str().
Referenced by brix_export_stream_cache_metrics().
stream_cache_emit_occupancy_ratio()
static void stream_cache_emit_occupancy_ratio (metrics_writer_t * mw, ngx_brix_metrics_t * shm) static
Definition at line 67 of file stream_cache.c.
References ngx_brix_srv_metrics_t::auth, brix_cache_statvfs(), BRIX_METRICS_MAX_SERVERS, ngx_brix_srv_metrics_t::cache_enabled, ngx_brix_srv_metrics_t::cache_root, ngx_brix_srv_metrics_t::in_use, mw_printf(), ngx_brix_srv_metrics_t::port, ngx_brix_metrics_t::servers, and stream_cache_port_str().
Referenced by brix_export_stream_cache_metrics().
stream_cache_emit_write_through()
static void stream_cache_emit_write_through (metrics_writer_t * mw, ngx_brix_metrics_t * shm) static
Definition at line 360 of file stream_cache.c.
References stream_cache_emit_wt_flushes(), and stream_cache_emit_wt_single().
Referenced by brix_export_stream_cache_metrics().
stream_cache_emit_wt_flushes()
static void stream_cache_emit_wt_flushes (metrics_writer_t * mw, ngx_brix_metrics_t * shm) static
Definition at line 323 of file stream_cache.c.
References ngx_brix_srv_metrics_t::auth, BRIX_METRICS_MAX_SERVERS, ngx_brix_srv_metrics_t::in_use, mw_printf(), ngx_brix_srv_metrics_t::port, ngx_brix_metrics_t::servers, stream_cache_port_str(), ngx_brix_srv_metrics_t::wt_flush_error_total, and ngx_brix_srv_metrics_t::wt_flush_success_total.
Referenced by stream_cache_emit_write_through().
stream_cache_emit_wt_single()
static void stream_cache_emit_wt_single (metrics_writer_t * mw, ngx_brix_metrics_t * shm, const char * header, const char * metric_name, size_t counter_off) static
Definition at line 292 of file stream_cache.c.
References ngx_brix_srv_metrics_t::auth, BRIX_METRICS_MAX_SERVERS, ngx_brix_srv_metrics_t::in_use, mw_printf(), ngx_brix_srv_metrics_t::port, ngx_brix_metrics_t::servers, and stream_cache_port_str().
Referenced by stream_cache_emit_write_through().
stream_cache_port_str()
static void stream_cache_port_str (char * buf, size_t buf_size, ngx_uint_t port) static
Definition at line 53 of file stream_cache.c.
References port.
Referenced by stream_cache_emit_cache_bytes(), stream_cache_emit_dirty_reaped(), stream_cache_emit_eviction_counter(), stream_cache_emit_eviction_threshold(), stream_cache_emit_occupancy_ratio(), stream_cache_emit_wt_flushes(), and stream_cache_emit_wt_single().