nginx-xrootd: brix_vfs_ops Struct Reference
brix_vfs_ops Struct Reference
#include <vfs.h>
Data Fields
ssize_t(* pread)(brix_vfs_file *f, int64_t off, void *buf, size_t n, brix_status *st)
int(* pwrite)(brix_vfs_file *f, int64_t off, const void *buf, size_t n, brix_status *st)
int(* fstat)(brix_vfs_file *f, brix_vfs_stat *out, brix_status *st)
int(* truncate)(brix_vfs_file *f, int64_t size, brix_status *st)
int(* sync)(brix_vfs_file *f, brix_status *st)
int(* commit)(brix_vfs_file *f, brix_status *st)
void(* abort)(brix_vfs_file *f)
void(* close)(brix_vfs_file *f)
Detailed Description
Definition at line 68 of file vfs.h.
Field Documentation
abort
void(* brix_vfs_ops::abort) (brix_vfs_file *f)
Definition at line 75 of file vfs.h.
Referenced by brix_vfs_abort().
close
void(* brix_vfs_ops::close) (brix_vfs_file *f)
Definition at line 76 of file vfs.h.
Referenced by brix_vfs_close().
commit
int(* brix_vfs_ops::commit) (brix_vfs_file *f, brix_status *st)
Definition at line 74 of file vfs.h.
Referenced by brix_vfs_commit().
fstat
int(* brix_vfs_ops::fstat) (brix_vfs_file *f, brix_vfs_stat *out, brix_status *st)
Definition at line 71 of file vfs.h.
Referenced by brix_vfs_fstat().
pread
ssize_t(* brix_vfs_ops::pread) (brix_vfs_file *f, int64_t off, void *buf, size_t n, brix_status *st)
Definition at line 69 of file vfs.h.
Referenced by brix_vfs_pread().
pwrite
int(* brix_vfs_ops::pwrite) (brix_vfs_file *f, int64_t off, const void *buf, size_t n, brix_status *st)
Definition at line 70 of file vfs.h.
Referenced by brix_vfs_pwrite().
sync
int(* brix_vfs_ops::sync) (brix_vfs_file *f, brix_status *st)
Definition at line 73 of file vfs.h.
Referenced by brix_vfs_sync().
truncate
int(* brix_vfs_ops::truncate) (brix_vfs_file *f, int64_t size, brix_status *st)
Definition at line 72 of file vfs.h.
Referenced by brix_vfs_truncate().
The documentation for this struct was generated from the following file:
client/lib/fs/vfs.h