nginx-xrootd: brix_s3_transport_t Struct Reference
brix_s3_transport_t Struct Reference
#include <sd_s3_transport.h>
Data Fields
int(* request)(void *tctx, const char *host, int port, int tls, const char *method, const char *path_and_query, const char *headers, const void *body, size_t body_len, int timeout_ms, brix_s3_resp_t *resp, char *errbuf, size_t errcap)
int(* request_cred)(void *tctx, const char *host, int port, int tls, const char *method, const char *path_and_query, const char *headers, const void *body, size_t body_len, int timeout_ms, const char *client_cert_pem, brix_s3_resp_t *resp, char *errbuf, size_t errcap)
int(* resp_header)(const brix_s3_resp_t *resp, const char *name, char *out, size_t outcap)
const char *(* resp_headers_raw)(const brix_s3_resp_t *resp)
const void *(* resp_body)(const brix_s3_resp_t *resp, size_t *len)
void(* resp_free)(brix_s3_resp_t *resp)
Detailed Description
Definition at line 32 of file sd_s3_transport.h.
Field Documentation
request
int(* brix_s3_transport_t::request) (void *tctx, const char *host, int port, int tls, const char *method, const char *path_and_query, const char *headers, const void *body, size_t body_len, int timeout_ms, brix_s3_resp_t *resp, char *errbuf, size_t errcap)
Definition at line 39 of file sd_s3_transport.h.
Referenced by cvmfs_pt_thread(), sd_http_fo_perform(), sd_http_staged_commit(), sd_http_unlink(), sd_s3_commit(), sd_s3_delete(), sd_s3_get_meta(), sd_s3_list_meta(), sd_s3_mpu_abort(), sd_s3_mpu_complete(), sd_s3_mpu_create(), sd_s3_mpu_upload_part(), sd_s3_pread(), sd_s3_set_meta_f(), and sd_s3_size().
request_cred
int(* brix_s3_transport_t::request_cred) (void *tctx, const char *host, int port, int tls, const char *method, const char *path_and_query, const char *headers, const void *body, size_t body_len, int timeout_ms, const char *client_cert_pem, brix_s3_resp_t *resp, char *errbuf, size_t errcap)
Definition at line 59 of file sd_s3_transport.h.
Referenced by sd_http_cred_gate(), sd_http_fo_perform(), sd_http_resolve_open_cred(), sd_http_staged_commit(), and sd_http_staged_open_common().
resp_body
const void *(* brix_s3_transport_t::resp_body) (const brix_s3_resp_t *resp, size_t *len)
Definition at line 80 of file sd_s3_transport.h.
Referenced by cvmfs_pt_thread(), sd_http_pread(), sd_s3_mpu_create(), and sd_s3_pread().
resp_free
void(* brix_s3_transport_t::resp_free) (brix_s3_resp_t *resp)
Definition at line 83 of file sd_s3_transport.h.
Referenced by cvmfs_pt_thread(), sd_http_head_size(), sd_http_pread(), sd_http_staged_commit(), sd_http_unlink(), sd_s3_commit(), sd_s3_delete(), sd_s3_get_meta(), sd_s3_list_meta(), sd_s3_mpu_abort(), sd_s3_mpu_complete(), sd_s3_mpu_create(), sd_s3_mpu_upload_part(), sd_s3_pread(), sd_s3_set_meta_f(), and sd_s3_size().
resp_header
int(* brix_s3_transport_t::resp_header) (const brix_s3_resp_t *resp, const char *name, char *out, size_t outcap)
Definition at line 68 of file sd_s3_transport.h.
Referenced by sd_http_head_size(), sd_s3_get_meta(), sd_s3_mpu_upload_part(), sd_s3_pread(), and sd_s3_size().
resp_headers_raw
const char *(* brix_s3_transport_t::resp_headers_raw) (const brix_s3_resp_t *resp)
Definition at line 77 of file sd_s3_transport.h.
Referenced by sd_s3_list_meta().
The documentation for this struct was generated from the following file:
src/fs/backend/s3/sd_s3_transport.h