nginx-xrootd: brix_mss_adapter_t Struct Reference
brix_mss_adapter_t Struct Reference
#include <sd_frm.h>
Data Fields
const char * name
int(* residency)(void *mss, const char *key, off_t *size_out, time_t *mtime_out)
int(* recall_begin)(void *mss, const char *key)
int(* recall_poll)(void *mss, const char *key)
int(* migrate)(void *mss, const char *key)
int(* purge)(void *mss, const char *key)
int(* open_online)(void *mss, const char *key)
int(* create_online)(void *mss, const char *key, mode_t mode)
void(* destroy)(void *mss)
Detailed Description
Definition at line 48 of file sd_frm.h.
Field Documentation
create_online
int(* brix_mss_adapter_t::create_online) (void *mss, const char *key, mode_t mode)
Definition at line 64 of file sd_frm.h.
Referenced by sd_frm_staged_open().
destroy
void(* brix_mss_adapter_t::destroy) (void *mss)
Definition at line 65 of file sd_frm.h.
Referenced by brix_sd_frm_destroy().
migrate
int(* brix_mss_adapter_t::migrate) (void *mss, const char *key)
Definition at line 58 of file sd_frm.h.
Referenced by sd_frm_staged_commit().
name
const char* brix_mss_adapter_t::name
Definition at line 49 of file sd_frm.h.
open_online
int(* brix_mss_adapter_t::open_online) (void *mss, const char *key)
Definition at line 62 of file sd_frm.h.
Referenced by sd_frm_open().
purge
int(* brix_mss_adapter_t::purge) (void *mss, const char *key)
Definition at line 60 of file sd_frm.h.
Referenced by sd_frm_staged_abort().
recall_begin
int(* brix_mss_adapter_t::recall_begin) (void *mss, const char *key)
Definition at line 54 of file sd_frm.h.
Referenced by frm_ensure_online().
recall_poll
int(* brix_mss_adapter_t::recall_poll) (void *mss, const char *key)
Definition at line 56 of file sd_frm.h.
Referenced by frm_ensure_online().
residency
int(* brix_mss_adapter_t::residency) (void *mss, const char *key, off_t *size_out, time_t *mtime_out)
Definition at line 51 of file sd_frm.h.
Referenced by frm_ensure_online(), sd_frm_residency(), and sd_frm_stat().
The documentation for this struct was generated from the following file:
src/fs/backend/frm/sd_frm.h