nginx-xrootd: brix_dashboard_totals_t Struct Reference
brix_dashboard_totals_t Struct Reference
#include <dashboard_api_internal.h>
Data Fields
uint64_t conn_active
uint64_t conn_total
uint64_t bytes_rx
uint64_t bytes_tx
uint64_t proto_rx [(BRIX_XFER_PROTO__END - 1)]
uint64_t proto_tx [(BRIX_XFER_PROTO__END - 1)]
uint64_t proto_errors [(BRIX_XFER_PROTO__END - 1)]
uint64_t stream_errors
Detailed Description
Definition at line 19 of file dashboard_api_internal.h.
Field Documentation
bytes_rx
uint64_t brix_dashboard_totals_t::bytes_rx
Definition at line 22 of file dashboard_api_internal.h.
Referenced by dashboard_build_protocols(), dashboard_build_totals(), and dashboard_collect_totals().
bytes_tx
uint64_t brix_dashboard_totals_t::bytes_tx
Definition at line 23 of file dashboard_api_internal.h.
Referenced by dashboard_build_protocols(), dashboard_build_totals(), and dashboard_collect_totals().
conn_active
uint64_t brix_dashboard_totals_t::conn_active
Definition at line 20 of file dashboard_api_internal.h.
Referenced by dashboard_build_totals(), and dashboard_collect_totals().
conn_total
uint64_t brix_dashboard_totals_t::conn_total
Definition at line 21 of file dashboard_api_internal.h.
Referenced by dashboard_build_totals(), and dashboard_collect_totals().
proto_errors
uint64_t brix_dashboard_totals_t::proto_errors[(BRIX_XFER_PROTO__END - 1)]
Definition at line 31 of file dashboard_api_internal.h.
Referenced by dashboard_build_totals(), and dashboard_collect_totals().
proto_rx
uint64_t brix_dashboard_totals_t::proto_rx[(BRIX_XFER_PROTO__END - 1)]
Definition at line 29 of file dashboard_api_internal.h.
Referenced by dashboard_build_protocols(), dashboard_build_totals(), and dashboard_collect_totals().
proto_tx
uint64_t brix_dashboard_totals_t::proto_tx[(BRIX_XFER_PROTO__END - 1)]
Definition at line 30 of file dashboard_api_internal.h.
Referenced by dashboard_build_protocols(), dashboard_build_totals(), and dashboard_collect_totals().
stream_errors
uint64_t brix_dashboard_totals_t::stream_errors
Definition at line 32 of file dashboard_api_internal.h.
Referenced by dashboard_build_totals(), and dashboard_collect_totals().
The documentation for this struct was generated from the following file:
src/observability/dashboard/dashboard_api_internal.h