nginx-xrootd: brix_cred_handler Struct Reference
brix_cred_handler Struct Reference
#include <cred.h>
Data Fields
brix_cred_kind kind
int(* available)(const brix_cred_config *cfg)
int(* acquire)(const brix_cred_config *cfg, brix_cred_view *out, int64_t *not_after, brix_status *st)
int(* refresh)(const brix_cred_config *cfg, brix_status *st)
Detailed Description
Definition at line 73 of file cred.h.
Field Documentation
acquire
int(* brix_cred_handler::acquire) (const brix_cred_config *cfg, brix_cred_view *out, int64_t *not_after, brix_status *st)
Definition at line 82 of file cred.h.
Referenced by do_acquire().
available
int(* brix_cred_handler::available) (const brix_cred_config *cfg)
Definition at line 75 of file cred.h.
Referenced by brix_cred_available().
kind
brix_cred_kind brix_cred_handler::kind
Definition at line 74 of file cred.h.
refresh
int(* brix_cred_handler::refresh) (const brix_cred_config *cfg, brix_status *st)
Definition at line 84 of file cred.h.
Referenced by brix_cred_acquire().
The documentation for this struct was generated from the following file:
client/lib/auth/cred/cred.h