nginx-xrootd: brix_sec_module Struct Reference
brix_sec_module Struct Reference
#include <sec.h>
Data Fields
const char * name
char credtype [4]
int(* have_creds)(brix_conn *c)
int(* first)(brix_conn *c, const char *parms, uint8_t **payload, uint32_t *plen, brix_status *st)
int(* more)(brix_conn *c, const uint8_t *sbody, uint32_t slen, uint8_t **payload, uint32_t *plen, brix_status *st)
void(* cleanup)(brix_conn *c)
Detailed Description
Definition at line 16 of file sec.h.
Field Documentation
cleanup
void(* brix_sec_module::cleanup) (brix_conn *c)
Definition at line 35 of file sec.h.
Referenced by run_module().
credtype
char brix_sec_module::credtype[4]
Definition at line 18 of file sec.h.
Referenced by run_module().
first
int(* brix_sec_module::first) (brix_conn *c, const char *parms, uint8_t **payload, uint32_t *plen, brix_status *st)
Definition at line 27 of file sec.h.
Referenced by run_module().
have_creds
int(* brix_sec_module::have_creds) (brix_conn *c)
Definition at line 23 of file sec.h.
Referenced by brix_auth_explain(), and module_candidate().
more
int(* brix_sec_module::more) (brix_conn *c, const uint8_t *sbody, uint32_t slen, uint8_t **payload, uint32_t *plen, brix_status *st)
Definition at line 32 of file sec.h.
Referenced by run_module().
name
const char* brix_sec_module::name
Definition at line 17 of file sec.h.
Referenced by auth_warn_fallback(), brix_auth_explain(), brix_authenticate(), module_candidate(), and run_module().
The documentation for this struct was generated from the following file:
client/lib/auth/sec/sec.h