nginx-xrootd: src/auth/s3/sts.c File Reference
sts.c File Reference
#include "sts_internal.h"
#include <string.h>
#include <time.h>
Macros
#define BRIX_STS_TTL_MIN 900 /* AWS floor: 15 min */
#define BRIX_STS_TTL_MAX 43200 /* AWS ceiling: 12 h */
Functions
static ngx_int_t sts_pool_cstr (ngx_pool_t *pool, ngx_str_t *dst, const char *src)
static int sts_clamp_ttl (int ttl)
static int sts_rsn_char_ok (char c)
static const char * sts_rsn_source (const brix_identity_t *id)
static void sts_role_session_name (const brix_identity_t *id, char out[65])
static ngx_int_t sts_host_from_url (ngx_pool_t *pool, const ngx_str_t *url, char **host_out)
static ngx_int_t sts_now (char amzdate[17], char datestamp[9])
static ngx_int_t sts_validate (ngx_pool_t *pool, const brix_s3_sts_conf_t *cf, const brix_s3_sts_out_t *out, ngx_log_t *log)
static ngx_int_t sts_prepare (ngx_pool_t *pool, sts_req_t *req, char *url, size_t urlsz, ngx_log_t *log)
static ngx_int_t sts_perform (ngx_pool_t *pool, const char *url, const char *rsn, sts_resp_t *resp, ngx_log_t *log)
static ngx_int_t sts_finish (ngx_pool_t *pool, const sts_resp_t *resp, const brix_s3_sts_out_t *out, ngx_log_t *log)
ngx_int_t brix_s3_sts_assume (ngx_pool_t *pool, const brix_identity_t *id, const brix_s3_sts_conf_t *cf, const brix_s3_sts_out_t *out, ngx_log_t *log)
Macro Definition Documentation
BRIX_STS_TTL_MAX
#define BRIX_STS_TTL_MAX 43200 /* AWS ceiling: 12 h */
Definition at line 31 of file sts.c.
BRIX_STS_TTL_MIN
#define BRIX_STS_TTL_MIN 900 /* AWS floor: 15 min */
Definition at line 30 of file sts.c.
Function Documentation
brix_s3_sts_assume()
ngx_int_t brix_s3_sts_assume (ngx_pool_t * pool, const brix_identity_t * id, const brix_s3_sts_conf_t * cf, const brix_s3_sts_out_t * out, ngx_log_t * log)
Definition at line 374 of file sts.c.
References brix_s3_sts_out_t::ak, sts_req_t::cf, sts_req_t::id, log, sts_req_t::rsn, sts_finish(), sts_perform(), sts_prepare(), sts_validate(), and sts_req_t::ttl.
Referenced by brix_vfs_deleg_sts_cred().
sts_clamp_ttl()
static int sts_clamp_ttl (int ttl) static
Definition at line 68 of file sts.c.
References BRIX_STS_TTL_MAX, and BRIX_STS_TTL_MIN.
Referenced by sts_prepare().
sts_finish()
static ngx_int_t sts_finish (ngx_pool_t * pool, const sts_resp_t * resp, const brix_s3_sts_out_t * out, ngx_log_t * log) static
Definition at line 347 of file sts.c.
References brix_s3_sts_out_t::ak, sts_resp_t::buf, sts_resp_t::len, log, brix_s3_sts_out_t::session, brix_s3_sts_out_t::sk, sts_parse_response(), and sts_pool_cstr().
Referenced by brix_s3_sts_assume().
sts_host_from_url()
static ngx_int_t sts_host_from_url (ngx_pool_t * pool, const ngx_str_t * url, char ** host_out) static
Definition at line 152 of file sts.c.
References ngx_memcpy, ngx_pnalloc(), and s.
Referenced by sts_prepare().
sts_now()
static ngx_int_t sts_now (char amzdate[17], char datestamp[9]) static
Definition at line 188 of file sts.c.
References ngx_memcpy.
Referenced by sts_prepare().
sts_perform()
static ngx_int_t sts_perform (ngx_pool_t * pool, const char * url, const char * rsn, sts_resp_t * resp, ngx_log_t * log) static
Definition at line 313 of file sts.c.
References BRIX_STS_RESP_MAX, sts_resp_t::buf, sts_resp_t::cap, sts_resp_t::len, log, ngx_pnalloc(), and sts_http_get().
Referenced by brix_s3_sts_assume().
sts_pool_cstr()
static ngx_int_t sts_pool_cstr (ngx_pool_t * pool, ngx_str_t * dst, const char * src) static
Definition at line 44 of file sts.c.
References ngx_memcpy, and ngx_pnalloc().
Referenced by sts_finish().
sts_prepare()
static ngx_int_t sts_prepare (ngx_pool_t * pool, sts_req_t * req, char * url, size_t urlsz, ngx_log_t * log) static
Definition at line 248 of file sts.c.
References sts_req_t::amzdate, sts_req_t::cf, sts_req_t::credential, sts_req_t::datestamp, brix_s3_sts_conf_t::endpoint, host, sts_req_t::host, sts_req_t::id, log, brix_s3_sts_conf_t::region, sts_req_t::rsn, sts_build_action_qs(), sts_clamp_ttl(), sts_host_from_url(), sts_now(), sts_role_session_name(), sts_sign_query(), brix_s3_sts_conf_t::svc_ak, sts_req_t::ttl, and brix_s3_sts_conf_t::ttl_secs.
Referenced by brix_s3_sts_assume().
sts_role_session_name()
static void sts_role_session_name (const brix_identity_t * id, char out[65]) static
Definition at line 130 of file sts.c.
References ngx_memcpy, sts_rsn_char_ok(), and sts_rsn_source().
Referenced by sts_prepare().
sts_rsn_char_ok()
static int sts_rsn_char_ok (char c) static
Definition at line 95 of file sts.c.
References c.
Referenced by sts_role_session_name().
sts_rsn_source()
static const char * sts_rsn_source (const brix_identity_t * id) static
Definition at line 112 of file sts.c.
References brix_identity_t::dn, and brix_identity_t::subject.
Referenced by sts_role_session_name().
sts_validate()
static ngx_int_t sts_validate (ngx_pool_t * pool, const brix_s3_sts_conf_t * cf, const brix_s3_sts_out_t * out, ngx_log_t * log) static
Definition at line 214 of file sts.c.
References brix_s3_sts_out_t::ak, brix_s3_sts_conf_t::endpoint, log, brix_s3_sts_conf_t::region, brix_s3_sts_out_t::session, brix_s3_sts_out_t::sk, brix_s3_sts_conf_t::svc_ak, and brix_s3_sts_conf_t::svc_sk.
Referenced by brix_s3_sts_assume().