nginx-xrootd: src/auth/s3/sts_internal.h File Reference
sts_internal.h File Reference
#include "sts.h"
Data Structures
struct sts_req_t
struct sts_resp_t
struct sts_creds_buf_t
Macros
#define BRIX_STS_RESP_MAX (64 * 1024)
Functions
ngx_int_t sts_build_action_qs (const sts_req_t *req, char *out, size_t outsz)
ngx_int_t sts_sign_query (const sts_req_t *req, const char *action_qs, char *out, size_t outsz)
ngx_int_t sts_http_get (const char *url, sts_resp_t *resp, long *http_status, ngx_log_t *log)
ngx_int_t sts_parse_response (const u_char *body, size_t len, const sts_creds_buf_t *creds, ngx_log_t *log)
Macro Definition Documentation
BRIX_STS_RESP_MAX
#define BRIX_STS_RESP_MAX (64 * 1024)
Definition at line 28 of file sts_internal.h.
Function Documentation
sts_build_action_qs()
ngx_int_t sts_build_action_qs (const sts_req_t * req, char * out, size_t outsz)
Definition at line 137 of file sts_sign.c.
References sts_req_t::amzdate, sts_req_t::cf, sts_req_t::credential, brix_s3_sts_conf_t::role_arn, sts_req_t::rsn, and sts_req_t::ttl.
Referenced by sts_prepare().
sts_http_get()
ngx_int_t sts_http_get (const char * url, sts_resp_t * resp, long * http_status, ngx_log_t * log)
Definition at line 68 of file sts_http.c.
References log, and sts_write_cb().
Referenced by sts_perform().
sts_parse_response()
ngx_int_t sts_parse_response (const u_char * body, size_t len, const sts_creds_buf_t * creds, ngx_log_t * log)
Definition at line 196 of file sts_http.c.
References log.
Referenced by sts_finish().
sts_sign_query()
ngx_int_t sts_sign_query (const sts_req_t * req, const char * action_qs, char * out, size_t outsz)
Definition at line 63 of file sts_sign.c.
References sts_req_t::amzdate, brix_hmac_sha256(), brix_sha256(), brix_sigv4_signing_key(), sts_req_t::cf, sts_req_t::datestamp, sts_req_t::host, key, brix_s3_sts_conf_t::region, scope, sts_hex(), and brix_s3_sts_conf_t::svc_sk.
Referenced by sts_prepare().