nginx-xrootd: src/auth/s3/sts_sign.c File Reference
sts_sign.c File Reference
#include "sts_internal.h"
#include "core/compat/sigv4.h"
#include "core/compat/crypto.h"
Functions
static void sts_hex (const uint8_t *in, size_t n, char *out)
ngx_int_t sts_sign_query (const sts_req_t *req, const char *action_qs, char *out, size_t outsz)
ngx_int_t sts_build_action_qs (const sts_req_t *req, char *out, size_t outsz)
Function Documentation
sts_build_action_qs()
ngx_int_t sts_build_action_qs (const sts_req_t * req, char * out, size_t outsz)
Definition at line 137 of file sts_sign.c.
References sts_req_t::amzdate, sts_req_t::cf, sts_req_t::credential, brix_s3_sts_conf_t::role_arn, sts_req_t::rsn, and sts_req_t::ttl.
Referenced by sts_prepare().
sts_hex()
static void sts_hex (const uint8_t * in, size_t n, char * out) static
Definition at line 32 of file sts_sign.c.
Referenced by sts_sign_query().
sts_sign_query()
ngx_int_t sts_sign_query (const sts_req_t * req, const char * action_qs, char * out, size_t outsz)
Definition at line 63 of file sts_sign.c.
References sts_req_t::amzdate, brix_hmac_sha256(), brix_sha256(), brix_sigv4_signing_key(), sts_req_t::cf, sts_req_t::datestamp, host, sts_req_t::host, key, brix_s3_sts_conf_t::region, scope, sts_hex(), and brix_s3_sts_conf_t::svc_sk.
Referenced by sts_prepare().