nginx-xrootd: client/lib/cli/suggest.c File Reference
suggest.c File Reference
#include "cli/suggest.h"
#include <stddef.h>
#include <string.h>
Macros
#define SUGGEST_ARG_MAX 64
#define SUGGEST_CAND_MAX SUGGEST_ARG_MAX
Functions
static unsigned int dl_distance (const char *a, size_t alen, const char *b, size_t blen)
const char * brix_suggest (const char *arg, const char *const *candidates)
Macro Definition Documentation
SUGGEST_ARG_MAX
#define SUGGEST_ARG_MAX 64
Definition at line 19 of file suggest.c.
SUGGEST_CAND_MAX
#define SUGGEST_CAND_MAX SUGGEST_ARG_MAX
Definition at line 28 of file suggest.c.
Function Documentation
brix_suggest()
const char * brix_suggest (const char * arg, const char *const * candidates)
Definition at line 78 of file suggest.c.
References dl_distance(), SUGGEST_ARG_MAX, and SUGGEST_CAND_MAX.
Referenced by brixmount_dispatch(), dispatch_unknown(), dx_unknown_sub(), main(), and report_unknown_command().
dl_distance()
static unsigned int dl_distance (const char * a, size_t alen, const char * b, size_t blen) static
Definition at line 39 of file suggest.c.
References SUGGEST_ARG_MAX.
Referenced by brix_suggest().