nginx-xrootd: src/protocols/root/write/sync.c File Reference
sync.c File Reference
#include "core/ngx_brix_module.h"
#include "fs/cache/cache_internal.h"
#include "wrts_journal.h"
Functions
ngx_int_t brix_handle_sync (brix_ctx_t *ctx, ngx_connection_t *c)
Function Documentation
brix_handle_sync()
ngx_int_t brix_handle_sync (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 17 of file sync.c.
References BRIX_OP_SYNC, BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_staged_commit_handle(), brix_tpc_start_pull(), brix_transfer_slot_count_op(), brix_validate_file_handle(), brix_vfs_io_execute(), brix_vfs_job_set_obj(), brix_vfs_job_sync_init(), brix_wrts_flush(), c, brix_file_t::dashboard_slot, brix_file_t::fd, xrdw_sync_req_t::fhandle, brix_ctx_t::files, brix_ctx_recv_t::hdr_buf, brix_vfs_job_t::io_errno, kXR_IOError, ngx_brix_dashboard_shm_zone, ngx_stream_brix_module, brix_file_t::path, brix_ctx_t::recv, brix_file_t::sd_obj, brix_ctx_t::session, brix_file_t::staged, brix_file_t::tpc_armed, brix_file_t::tpc_destination, brix_file_t::tpc_done, brix_file_t::wrts_enabled, and xrdw_sync_req_unpack().