nginx-xrootd: src/auth/authz/acc/tables.c File Reference
tables.c File Reference
#include "acc.h"
Functions
brix_acc_cap_t * brix_acc_named_find (brix_acc_named_t *list, const char *name)
brix_acc_cap_t * brix_acc_domain_find (brix_acc_named_t *dlist, const char *host)
void brix_acc_tables_free (brix_acc_tables_t *tabs)
Function Documentation
brix_acc_domain_find()
brix_acc_cap_t * brix_acc_domain_find (brix_acc_named_t * dlist, const char * host)
Definition at line 37 of file tables.c.
References brix_acc_named_t::caps, brix_acc_named_t::name, brix_acc_named_t::next, and brix_acc_named_t::nlen.
Referenced by brix_acc_access().
brix_acc_named_find()
brix_acc_cap_t * brix_acc_named_find (brix_acc_named_t * list, const char * name)
Definition at line 23 of file tables.c.
References brix_acc_named_t::caps, brix_acc_named_t::name, name, and brix_acc_named_t::next.
Referenced by acc_build_caps(), acc_record_named(), and brix_acc_access().
brix_acc_tables_free()
void brix_acc_tables_free (brix_acc_tables_t * tabs)
Definition at line 59 of file tables.c.
References brix_acc_tables_t::pool.
Referenced by brix_acc_http_refresh_handler(), and brix_acc_refresh_handler().