nginx-xrootd: src/protocols/s3/tagging.c File Reference
tagging.c File Reference
#include "s3.h"
#include "fs/path/path.h"
#include "tagging.h"
#include "core/http/http_body.h"
#include "core/http/http_headers.h"
#include "core/http/http_query.h"
#include "core/compat/uri.h"
#include "core/compat/xml.h"
#include "fs/vfs/vfs.h"
#include <errno.h>
#include <fcntl.h>
#include <string.h>
#include <sys/xattr.h>
#include <unistd.h>
#include <libxml/parser.h>
#include <libxml/tree.h>
#include "core/compat/alloc_guard.h"
Macros
#define S3_TAG_XATTR "user.s3.tagging"
#define S3_TAG_MAX 4096 /* AWS: <=10 tags, key<=128, value<=256 */
#define S3_TAG_XML_MAX 8192
Functions
static void s3_tag_vfs_ctx (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, brix_vfs_ctx_t *vctx)
static ssize_t s3_tag_load (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const char *fs_path, char *out, size_t outsz)
static ngx_int_t s3_tag_store (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const char *fs_path, const char *blob, size_t blob_len, int remove_it)
static int s3_tag_blob_valid (const char *s, size_t len)
ngx_int_t s3_handle_get_object_tagging (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf)
ngx_int_t s3_handle_delete_object_tagging (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf)
ngx_int_t s3_apply_put_tagging_header (ngx_http_request_t *r, const char *fs_path, const char *root_canon)
static int s3_xml_node_is (const xmlNode *node, const char *name)
static void s3_tag_append_pair (char *out, size_t outsz, size_t *pos, const xmlChar *key, const xmlChar *val)
static void s3_tag_emit_one (const xmlNode *tag, char *out, size_t outsz, size_t *pos)
static void s3_tag_walk_tagsets (const xmlNode *root, char *out, size_t outsz, size_t *pos)
static ngx_int_t s3_tag_blob_from_xml (ngx_http_request_t *r, const u_char *body, size_t len, char *out, size_t outsz, size_t *out_len)
void s3_put_object_tagging_body_handler (ngx_http_request_t *r)
static ngx_int_t s3_send_xml_literal (ngx_http_request_t *r, const char *xml)
ngx_int_t s3_handle_get_bucket_versioning (ngx_http_request_t *r)
ngx_int_t s3_handle_get_acl (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf)
ngx_int_t s3_handle_get_cors (ngx_http_request_t *r)
Macro Definition Documentation
S3_TAG_MAX
#define S3_TAG_MAX 4096 /* AWS: <=10 tags, key<=128, value<=256 */
Definition at line 41 of file tagging.c.
S3_TAG_XATTR
#define S3_TAG_XATTR "user.s3.tagging"
Definition at line 40 of file tagging.c.
S3_TAG_XML_MAX
#define S3_TAG_XML_MAX 8192
Definition at line 42 of file tagging.c.
Function Documentation
s3_apply_put_tagging_header()
ngx_int_t s3_apply_put_tagging_header (ngx_http_request_t * r, const char * fs_path, const char * root_canon)
Definition at line 249 of file tagging.c.
References brix_http_find_header(), ngx_http_brix_s3_module, s3_tag_blob_valid(), and s3_tag_store().
Referenced by s3_chunk_finalize(), s3_put_aio_done(), and s3put_commit_and_headers().
s3_handle_delete_object_tagging()
ngx_int_t s3_handle_delete_object_tagging (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf)
Definition at line 233 of file tagging.c.
References BRIX_S3_EVENT_NO_SUCH_KEY, s3_fail(), and s3_tag_store().
Referenced by s3_dispatch_object_delete().
s3_handle_get_acl()
ngx_int_t s3_handle_get_acl (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf)
Definition at line 501 of file tagging.c.
References ngx_http_s3_loc_conf_t::access_key, brix_http_send_xml_buffer(), BRIX_PALLOC_OR_RETURN, BRIX_S3_EVENT_NO_SUCH_KEY, brix_vfs_stat_t::is_directory, ngx_memcpy, s3_fail(), s3_tag_vfs_ctx(), XML_APPEND, and XML_APPEND_ELEM.
Referenced by s3_dispatch_bucket_get(), and s3_dispatch_object_get().
s3_handle_get_bucket_versioning()
ngx_int_t s3_handle_get_bucket_versioning (ngx_http_request_t * r)
Definition at line 491 of file tagging.c.
References s3_send_xml_literal().
Referenced by s3_dispatch_bucket_get().
s3_handle_get_cors()
ngx_int_t s3_handle_get_cors (ngx_http_request_t * r)
Definition at line 570 of file tagging.c.
References s3_send_xml_error().
Referenced by s3_dispatch_bucket_get().
s3_handle_get_object_tagging()
ngx_int_t s3_handle_get_object_tagging (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf)
Definition at line 158 of file tagging.c.
References brix_http_send_xml_buffer(), brix_http_urldecode(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_EVENT_NO_SUCH_KEY, BRIX_S3_METRIC_INC, BRIX_URLDECODE_OK, BRIX_URLDECODE_PLUS_TO_SPACE, s3_fail(), s3_tag_load(), S3_TAG_MAX, S3_TAG_XML_MAX, XML_APPEND, and XML_APPEND_ELEM.
Referenced by s3_dispatch_object_get().
s3_put_object_tagging_body_handler()
void s3_put_object_tagging_body_handler (ngx_http_request_t * r)
Definition at line 424 of file tagging.c.
References brix_http_body_read_all(), ngx_http_s3_req_ctx_t::fs_path, ngx_http_brix_s3_module, s3_send_xml_error(), s3_tag_blob_from_xml(), s3_tag_blob_valid(), S3_TAG_MAX, s3_tag_store(), and S3_TAG_XML_MAX.
Referenced by s3_dispatch_object_put().
s3_send_xml_literal()
static ngx_int_t s3_send_xml_literal (ngx_http_request_t * r, const char * xml) static
Definition at line 476 of file tagging.c.
References brix_http_send_xml_buffer().
Referenced by s3_handle_get_bucket_versioning().
s3_tag_append_pair()
static void s3_tag_append_pair (char * out, size_t outsz, size_t * pos, const xmlChar * key, const xmlChar * val) static
Definition at line 300 of file tagging.c.
References brix_http_urlencode(), key, and ngx_memcpy.
Referenced by s3_tag_emit_one().
s3_tag_blob_from_xml()
static ngx_int_t s3_tag_blob_from_xml (ngx_http_request_t * r, const u_char * body, size_t len, char * out, size_t outsz, size_t * out_len) static
Definition at line 390 of file tagging.c.
References s3_tag_walk_tagsets().
Referenced by s3_put_object_tagging_body_handler().
s3_tag_blob_valid()
static int s3_tag_blob_valid (const char * s, size_t len) static
Definition at line 141 of file tagging.c.
References c, s, and S3_TAG_MAX.
Referenced by s3_apply_put_tagging_header(), and s3_put_object_tagging_body_handler().
s3_tag_emit_one()
static void s3_tag_emit_one (const xmlNode * tag, char * out, size_t outsz, size_t * pos) static
Definition at line 329 of file tagging.c.
References key, and s3_tag_append_pair().
Referenced by s3_tag_walk_tagsets().
s3_tag_load()
static ssize_t s3_tag_load (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const char * fs_path, char * out, size_t outsz) static
Definition at line 73 of file tagging.c.
References brix_vfs_getxattr(), s3_tag_vfs_ctx(), and S3_TAG_XATTR.
Referenced by s3_handle_get_object_tagging().
s3_tag_store()
static ngx_int_t s3_tag_store (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const char * fs_path, const char * blob, size_t blob_len, int remove_it) static
Definition at line 105 of file tagging.c.
References brix_vfs_removexattr(), brix_vfs_setxattr(), s3_tag_vfs_ctx(), and S3_TAG_XATTR.
Referenced by s3_apply_put_tagging_header(), s3_handle_delete_object_tagging(), and s3_put_object_tagging_body_handler().
s3_tag_vfs_ctx()
static void s3_tag_vfs_ctx (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, brix_vfs_ctx_t * vctx) static
Definition at line 53 of file tagging.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_S3, brix_vfs_ctx_init(), ngx_http_s3_loc_conf_t::cache_root_canon, ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, brix_vfs_ctx_t::pool, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by s3_handle_get_acl(), s3_tag_load(), and s3_tag_store().
s3_tag_walk_tagsets()
static void s3_tag_walk_tagsets (const xmlNode * root, char * out, size_t outsz, size_t * pos) static
Definition at line 361 of file tagging.c.
References s3_tag_emit_one(), and s3_xml_node_is().
Referenced by s3_tag_blob_from_xml().
s3_xml_node_is()
static int s3_xml_node_is (const xmlNode * node, const char * name) static
Definition at line 281 of file tagging.c.
References name.
Referenced by s3_tag_walk_tagsets().