nginx-xrootd: src/protocols/s3/tagging.h File Reference
tagging.h File Reference
#include "s3.h"
Functions
ngx_int_t s3_handle_get_object_tagging (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf)
ngx_int_t s3_handle_delete_object_tagging (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf)
void s3_put_object_tagging_body_handler (ngx_http_request_t *r)
ngx_int_t s3_apply_put_tagging_header (ngx_http_request_t *r, const char *fs_path, const char *root_canon)
ngx_int_t s3_handle_get_bucket_versioning (ngx_http_request_t *r)
ngx_int_t s3_handle_get_acl (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf)
ngx_int_t s3_handle_get_cors (ngx_http_request_t *r)
Function Documentation
s3_apply_put_tagging_header()
ngx_int_t s3_apply_put_tagging_header (ngx_http_request_t * r, const char * fs_path, const char * root_canon)
Definition at line 245 of file tagging.c.
References brix_http_find_header(), ngx_http_brix_s3_module, s3_tag_blob_valid(), and s3_tag_store().
Referenced by s3_chunk_finalize(), s3_put_aio_done(), and s3_put_body_inner().
s3_handle_delete_object_tagging()
ngx_int_t s3_handle_delete_object_tagging (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf)
Definition at line 229 of file tagging.c.
References BRIX_S3_EVENT_NO_SUCH_KEY, s3_fail(), and s3_tag_store().
Referenced by s3_dispatch_after_auth().
s3_handle_get_acl()
ngx_int_t s3_handle_get_acl (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf)
Definition at line 424 of file tagging.c.
References ngx_http_s3_loc_conf_t::access_key, brix_http_send_xml_buffer(), BRIX_PALLOC_OR_RETURN, ngx_memcpy, XML_APPEND, and XML_APPEND_ELEM.
Referenced by s3_dispatch_after_auth().
s3_handle_get_bucket_versioning()
ngx_int_t s3_handle_get_bucket_versioning (ngx_http_request_t * r)
Definition at line 414 of file tagging.c.
References s3_send_xml_literal().
Referenced by s3_dispatch_after_auth().
s3_handle_get_cors()
ngx_int_t s3_handle_get_cors (ngx_http_request_t * r)
Definition at line 470 of file tagging.c.
References s3_send_xml_error().
Referenced by s3_dispatch_after_auth().
s3_handle_get_object_tagging()
ngx_int_t s3_handle_get_object_tagging (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf)
Definition at line 154 of file tagging.c.
References brix_http_send_xml_buffer(), brix_http_urldecode(), BRIX_S3_EVENT_INTERNAL_ERROR, BRIX_S3_EVENT_NO_SUCH_KEY, BRIX_S3_METRIC_INC, BRIX_URLDECODE_OK, BRIX_URLDECODE_PLUS_TO_SPACE, s3_fail(), s3_tag_load(), S3_TAG_MAX, S3_TAG_XML_MAX, XML_APPEND, and XML_APPEND_ELEM.
Referenced by s3_dispatch_after_auth().
s3_put_object_tagging_body_handler()
void s3_put_object_tagging_body_handler (ngx_http_request_t * r)
Definition at line 347 of file tagging.c.
References brix_http_body_read_all(), ngx_http_s3_req_ctx_t::fs_path, ngx_http_brix_s3_module, s3_send_xml_error(), s3_tag_blob_from_xml(), s3_tag_blob_valid(), S3_TAG_MAX, s3_tag_store(), and S3_TAG_XML_MAX.
Referenced by s3_dispatch_after_auth().