nginx-xrootd: src/net/tap/tap_audit.c File Reference
tap_audit.c File Reference
#include "tap.h"
#include "protocols/root/protocol/opcodes.h"
#include <stdio.h>
#include <string.h>
Functions
static const char * tap_opcode_name (uint16_t op)
static int tap_json_append_escaped (char *out, size_t outsz, size_t *pos, const uint8_t *s, size_t slen)
size_t brix_tap_audit_format (const brix_tap_frame_t *f, brix_tap_dir_t dir, char *out, size_t outsz)
Function Documentation
brix_tap_audit_format()
size_t brix_tap_audit_format (const brix_tap_frame_t * f, brix_tap_dir_t dir, char * out, size_t outsz)
Definition at line 65 of file tap_audit.c.
References BRIX_TAP_C2U, brix_tap_frame_t::dlen, brix_tap_frame_t::is_request, brix_tap_frame_t::opcode, brix_tap_frame_t::path, brix_tap_frame_t::path_len, brix_tap_frame_t::status, brix_tap_frame_t::streamid, tap_json_append_escaped(), and tap_opcode_name().
Referenced by brix_proxy_tap_audit_sink(), and relay_audit_sink().
tap_json_append_escaped()
static int tap_json_append_escaped (char * out, size_t outsz, size_t * pos, const uint8_t * s, size_t slen) static
Definition at line 40 of file tap_audit.c.
References s.
Referenced by brix_tap_audit_format().
tap_opcode_name()
static const char * tap_opcode_name (uint16_t op) static
Definition at line 18 of file tap_audit.c.
References kXR_close, kXR_dirlist, kXR_locate, kXR_mkdir, kXR_mv, kXR_open, kXR_read, kXR_rm, kXR_rmdir, kXR_stat, kXR_statx, kXR_truncate, kXR_write, and op.
Referenced by brix_tap_audit_format().