nginx-xrootd: src/net/tap/tap.h File Reference
tap.h File Reference
#include <stddef.h>
#include <stdint.h>
Data Structures
struct brix_tap_frame_t
struct brix_tap_ctx_t
struct brix_tap_stream_t
Macros
#define BRIX_TAP_MAX_SINKS 8
#define BRIX_TAP_PATH_CAP 1024
#define BRIX_TAP_C2U_PREAMBLE 20
Typedefs
typedef void(* brix_tap_sink_fn) (void *ctx, const brix_tap_frame_t *f, brix_tap_dir_t dir, const uint8_t *payload, size_t payload_len)
Enumerations
enum brix_tap_dir_t { BRIX_TAP_C2U = 0 , BRIX_TAP_U2C = 1 }
Functions
size_t brix_tap_decode_request (const uint8_t *buf, size_t len, brix_tap_frame_t *out)
size_t brix_tap_decode_response (const uint8_t *buf, size_t len, brix_tap_frame_t *out)
int brix_tap_opcode_has_path (uint16_t op)
void brix_tap_register_sink (brix_tap_ctx_t *t, brix_tap_sink_fn fn, void *ctx)
void brix_tap_emit (brix_tap_ctx_t *t, const brix_tap_frame_t *f, brix_tap_dir_t dir, const uint8_t *payload, size_t payload_len)
size_t brix_tap_audit_format (const brix_tap_frame_t *f, brix_tap_dir_t dir, char *out, size_t outsz)
void brix_tap_stream_init (brix_tap_stream_t *st, brix_tap_ctx_t *tap, brix_tap_dir_t dir)
void brix_tap_stream_feed (brix_tap_stream_t *st, const uint8_t *buf, size_t len)
Macro Definition Documentation
BRIX_TAP_C2U_PREAMBLE
#define BRIX_TAP_C2U_PREAMBLE 20
Definition at line 86 of file tap.h.
BRIX_TAP_MAX_SINKS
#define BRIX_TAP_MAX_SINKS 8
Definition at line 55 of file tap.h.
BRIX_TAP_PATH_CAP
#define BRIX_TAP_PATH_CAP 1024
Definition at line 80 of file tap.h.
Typedef Documentation
brix_tap_sink_fn
typedef void(* brix_tap_sink_fn) (void *ctx, const brix_tap_frame_t *f, brix_tap_dir_t dir, const uint8_t *payload, size_t payload_len)
Definition at line 52 of file tap.h.
Enumeration Type Documentation
brix_tap_dir_t
enum brix_tap_dir_t
Enumerator
BRIX_TAP_C2U
BRIX_TAP_U2C
Definition at line 19 of file tap.h.
Function Documentation
brix_tap_audit_format()
size_t brix_tap_audit_format (const brix_tap_frame_t * f, brix_tap_dir_t dir, char * out, size_t outsz)
Definition at line 65 of file tap_audit.c.
References BRIX_TAP_C2U, brix_tap_frame_t::dlen, brix_tap_frame_t::is_request, brix_tap_frame_t::opcode, brix_tap_frame_t::path, brix_tap_frame_t::path_len, brix_tap_frame_t::status, brix_tap_frame_t::streamid, tap_json_append_escaped(), and tap_opcode_name().
Referenced by brix_proxy_tap_audit_sink(), and relay_audit_sink().
brix_tap_decode_request()
size_t brix_tap_decode_request (const uint8_t * buf, size_t len, brix_tap_frame_t * out)
Definition at line 36 of file tap_decode.c.
References brix_tap_opcode_has_path(), brix_tap_frame_t::dlen, brix_tap_frame_t::errnum, brix_tap_frame_t::is_request, brix_tap_frame_t::opcode, brix_tap_frame_t::path, brix_tap_frame_t::path_len, brix_tap_frame_t::status, brix_tap_frame_t::streamid, xrd_get_u16_be(), xrd_get_u32_be(), and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_dispatch_pending(), brix_proxy_forward_request(), and tap_stream_on_header().
brix_tap_decode_response()
size_t brix_tap_decode_response (const uint8_t * buf, size_t len, brix_tap_frame_t * out)
Definition at line 64 of file tap_decode.c.
References brix_tap_frame_t::dlen, brix_tap_frame_t::errnum, brix_tap_frame_t::is_request, kXR_error, brix_tap_frame_t::opcode, brix_tap_frame_t::path, brix_tap_frame_t::path_len, brix_tap_frame_t::status, brix_tap_frame_t::streamid, xrd_get_u32_be(), and xrd_resp_hdr_unpack().
Referenced by tap_stream_on_header().
brix_tap_emit()
void brix_tap_emit (brix_tap_ctx_t * t, const brix_tap_frame_t * f, brix_tap_dir_t dir, const uint8_t * payload, size_t payload_len)
Definition at line 23 of file tap_emit.c.
References brix_tap_ctx_t::ctx, brix_tap_ctx_t::fn, brix_tap_ctx_t::n, and brix_tap_ctx_t::sinks.
Referenced by brix_proxy_dispatch_pending(), brix_proxy_forward_request(), brix_proxy_relay_to_client(), brix_tap_stream_feed(), and tap_stream_on_header().
brix_tap_opcode_has_path()
int brix_tap_opcode_has_path (uint16_t op)
Definition at line 16 of file tap_decode.c.
References kXR_dirlist, kXR_locate, kXR_mkdir, kXR_mv, kXR_open, kXR_rm, kXR_rmdir, kXR_stat, kXR_statx, and kXR_truncate.
Referenced by brix_tap_decode_request(), and tap_stream_on_header().
brix_tap_register_sink()
void brix_tap_register_sink (brix_tap_ctx_t * t, brix_tap_sink_fn fn, void * ctx)
Definition at line 12 of file tap_emit.c.
References BRIX_TAP_MAX_SINKS, brix_tap_ctx_t::ctx, brix_tap_ctx_t::fn, fn, brix_tap_ctx_t::n, and brix_tap_ctx_t::sinks.
Referenced by brix_proxy_tap_init(), and brix_relay_start().
brix_tap_stream_feed()
void brix_tap_stream_feed (brix_tap_stream_t * st, const uint8_t * buf, size_t len)
Definition at line 99 of file tap_stream.c.
References brix_tap_emit(), BRIX_TAP_U2C, brix_tap_stream_t::ckp_active, brix_tap_stream_t::ckp_hdr, brix_tap_stream_t::ckp_hdr_got, brix_tap_stream_t::cur, brix_tap_stream_t::dir, brix_tap_stream_t::emitted, brix_tap_frame_t::errnum, brix_tap_stream_t::hdr, brix_tap_stream_t::hdr_got, brix_tap_stream_t::hdr_need, brix_tap_stream_t::in_payload, kXR_pgwrite, kXR_write, kXR_writev, brix_tap_frame_t::path, brix_tap_stream_t::path_cap, brix_tap_stream_t::path_got, brix_tap_frame_t::path_len, brix_tap_stream_t::pathbuf, brix_tap_stream_t::payload_left, brix_tap_stream_t::preamble_skip, brix_tap_stream_t::tap, tap_stream_on_header(), brix_tap_stream_t::wv_active, brix_tap_stream_t::wv_desc, brix_tap_stream_t::wv_desc_got, and brix_tap_stream_t::wv_extra.
Referenced by relay_pump().
brix_tap_stream_init()
void brix_tap_stream_init (brix_tap_stream_t * st, brix_tap_ctx_t * tap, brix_tap_dir_t dir)
Definition at line 19 of file tap_stream.c.
References BRIX_TAP_C2U, BRIX_TAP_C2U_PREAMBLE, brix_tap_stream_t::dir, brix_tap_stream_t::hdr_need, brix_tap_stream_t::preamble_skip, and brix_tap_stream_t::tap.
Referenced by brix_relay_start().