nginx-xrootd: src/net/tap/tap_emit.c File Reference
tap_emit.c File Reference
#include "tap.h"
Functions
void brix_tap_register_sink (brix_tap_ctx_t *t, brix_tap_sink_fn fn, void *ctx)
void brix_tap_emit (brix_tap_ctx_t *t, const brix_tap_frame_t *f, brix_tap_dir_t dir, const uint8_t *payload, size_t payload_len)
Function Documentation
brix_tap_emit()
void brix_tap_emit (brix_tap_ctx_t * t, const brix_tap_frame_t * f, brix_tap_dir_t dir, const uint8_t * payload, size_t payload_len)
Definition at line 23 of file tap_emit.c.
References brix_tap_ctx_t::ctx, brix_tap_ctx_t::fn, brix_tap_ctx_t::n, and brix_tap_ctx_t::sinks.
Referenced by brix_proxy_dispatch_pending(), brix_proxy_forward_request(), brix_proxy_relay_emit_tap(), tap_payload_emit_if_ready(), tap_payload_on_frame_end(), and tap_stream_on_header().
brix_tap_register_sink()
void brix_tap_register_sink (brix_tap_ctx_t * t, brix_tap_sink_fn fn, void * ctx)
Definition at line 12 of file tap_emit.c.
References BRIX_TAP_MAX_SINKS, brix_tap_ctx_t::ctx, fn, brix_tap_ctx_t::fn, brix_tap_ctx_t::n, and brix_tap_ctx_t::sinks.
Referenced by brix_proxy_tap_init(), and brix_relay_start().