nginx-xrootd: src/net/tap/tap_stream.c File Reference
tap_stream.c File Reference
#include "tap.h"
#include "protocols/root/protocol/opcodes.h"
#include <string.h>
Functions
void brix_tap_stream_init (brix_tap_stream_t *st, brix_tap_ctx_t *tap, brix_tap_dir_t dir)
static void tap_header_decode (brix_tap_stream_t *st)
static void tap_header_classify_framing (brix_tap_stream_t *st)
static void tap_header_set_capture (brix_tap_stream_t *st)
static void tap_stream_on_header (brix_tap_stream_t *st)
static void tap_feed_preamble (brix_tap_stream_t *st, const uint8_t **buf, size_t *len)
static void tap_feed_header (brix_tap_stream_t *st, const uint8_t **buf, size_t *len)
static void tap_payload_capture (brix_tap_stream_t *st, const uint8_t *buf, size_t take)
static void tap_payload_emit_if_ready (brix_tap_stream_t *st)
static int tap_payload_extend_ckpxeq (brix_tap_stream_t *st)
static int tap_payload_extend_writev (brix_tap_stream_t *st)
static int tap_payload_on_frame_end (brix_tap_stream_t *st)
static int tap_feed_payload (brix_tap_stream_t *st, const uint8_t **buf, size_t *len)
void brix_tap_stream_feed (brix_tap_stream_t *st, const uint8_t *buf, size_t len)
Function Documentation
brix_tap_stream_feed()
void brix_tap_stream_feed (brix_tap_stream_t * st, const uint8_t * buf, size_t len)
Definition at line 402 of file tap_stream.c.
References brix_tap_stream_t::in_payload, brix_tap_stream_t::preamble_skip, tap_feed_header(), tap_feed_payload(), and tap_feed_preamble().
Referenced by relay_pump().
brix_tap_stream_init()
void brix_tap_stream_init (brix_tap_stream_t * st, brix_tap_ctx_t * tap, brix_tap_dir_t dir)
Definition at line 19 of file tap_stream.c.
References BRIX_TAP_C2U, BRIX_TAP_C2U_PREAMBLE, brix_tap_stream_t::dir, brix_tap_stream_t::hdr_need, brix_tap_stream_t::preamble_skip, and brix_tap_stream_t::tap.
Referenced by brix_relay_start().
tap_feed_header()
static void tap_feed_header (brix_tap_stream_t * st, const uint8_t ** buf, size_t * len) static
Definition at line 175 of file tap_stream.c.
References brix_tap_stream_t::hdr, brix_tap_stream_t::hdr_got, brix_tap_stream_t::hdr_need, and tap_stream_on_header().
Referenced by brix_tap_stream_feed().
tap_feed_payload()
static int tap_feed_payload (brix_tap_stream_t * st, const uint8_t ** buf, size_t * len) static
Definition at line 383 of file tap_stream.c.
References brix_tap_stream_t::payload_left, tap_payload_capture(), tap_payload_emit_if_ready(), and tap_payload_on_frame_end().
Referenced by brix_tap_stream_feed().
tap_feed_preamble()
static void tap_feed_preamble (brix_tap_stream_t * st, const uint8_t ** buf, size_t * len) static
Definition at line 157 of file tap_stream.c.
References brix_tap_stream_t::preamble_skip.
Referenced by brix_tap_stream_feed().
tap_header_classify_framing()
static void tap_header_classify_framing (brix_tap_stream_t * st) static
Definition at line 63 of file tap_stream.c.
References BRIX_TAP_C2U, brix_tap_stream_t::ckp_active, brix_tap_stream_t::ckp_hdr_got, brix_tap_stream_t::cur, brix_tap_stream_t::dir, brix_tap_frame_t::dlen, brix_tap_stream_t::hdr, kXR_chkpoint, kXR_writev, brix_tap_frame_t::opcode, brix_tap_stream_t::wv_active, brix_tap_stream_t::wv_desc_got, and brix_tap_stream_t::wv_extra.
Referenced by tap_stream_on_header().
tap_header_decode()
static void tap_header_decode (brix_tap_stream_t * st) static
Definition at line 39 of file tap_stream.c.
References BRIX_TAP_C2U, brix_tap_decode_request(), brix_tap_decode_response(), brix_tap_stream_t::cur, brix_tap_stream_t::dir, brix_tap_frame_t::dlen, brix_tap_stream_t::emitted, brix_tap_stream_t::hdr, brix_tap_stream_t::hdr_need, brix_tap_stream_t::in_payload, brix_tap_stream_t::path_cap, brix_tap_stream_t::path_got, and brix_tap_stream_t::payload_left.
Referenced by tap_stream_on_header().
tap_header_set_capture()
static void tap_header_set_capture (brix_tap_stream_t * st) static
Definition at line 100 of file tap_stream.c.
References BRIX_TAP_C2U, brix_tap_opcode_has_path(), BRIX_TAP_PATH_CAP, BRIX_TAP_U2C, brix_tap_stream_t::cur, brix_tap_stream_t::dir, brix_tap_frame_t::dlen, kXR_error, brix_tap_frame_t::opcode, brix_tap_frame_t::path, brix_tap_stream_t::path_cap, brix_tap_frame_t::path_len, and brix_tap_frame_t::status.
Referenced by tap_stream_on_header().
tap_payload_capture()
static void tap_payload_capture (brix_tap_stream_t * st, const uint8_t * buf, size_t take) static
Definition at line 199 of file tap_stream.c.
References brix_tap_stream_t::ckp_active, brix_tap_stream_t::ckp_hdr, brix_tap_stream_t::ckp_hdr_got, brix_tap_stream_t::path_cap, brix_tap_stream_t::path_got, brix_tap_stream_t::pathbuf, brix_tap_stream_t::wv_active, brix_tap_stream_t::wv_desc, brix_tap_stream_t::wv_desc_got, and brix_tap_stream_t::wv_extra.
Referenced by tap_feed_payload().
tap_payload_emit_if_ready()
static void tap_payload_emit_if_ready (brix_tap_stream_t * st) static
Definition at line 244 of file tap_stream.c.
References brix_tap_emit(), BRIX_TAP_U2C, brix_tap_stream_t::cur, brix_tap_stream_t::dir, brix_tap_stream_t::emitted, brix_tap_frame_t::errnum, brix_tap_frame_t::path, brix_tap_stream_t::path_cap, brix_tap_stream_t::path_got, brix_tap_frame_t::path_len, brix_tap_stream_t::pathbuf, and brix_tap_stream_t::tap.
Referenced by tap_feed_payload().
tap_payload_extend_ckpxeq()
static int tap_payload_extend_ckpxeq (brix_tap_stream_t * st) static
Definition at line 277 of file tap_stream.c.
References brix_tap_stream_t::ckp_active, brix_tap_stream_t::ckp_hdr, brix_tap_stream_t::ckp_hdr_got, kXR_pgwrite, kXR_write, kXR_writev, brix_tap_stream_t::payload_left, brix_tap_stream_t::wv_active, brix_tap_stream_t::wv_desc_got, and brix_tap_stream_t::wv_extra.
Referenced by tap_payload_on_frame_end().
tap_payload_extend_writev()
static int tap_payload_extend_writev (brix_tap_stream_t * st) static
Definition at line 324 of file tap_stream.c.
References brix_tap_stream_t::payload_left, brix_tap_stream_t::wv_active, and brix_tap_stream_t::wv_extra.
Referenced by tap_payload_on_frame_end().
tap_payload_on_frame_end()
static int tap_payload_on_frame_end (brix_tap_stream_t * st) static
Definition at line 347 of file tap_stream.c.
References brix_tap_emit(), brix_tap_stream_t::cur, brix_tap_stream_t::dir, brix_tap_stream_t::emitted, brix_tap_stream_t::hdr_got, brix_tap_stream_t::in_payload, brix_tap_stream_t::tap, tap_payload_extend_ckpxeq(), and tap_payload_extend_writev().
Referenced by tap_feed_payload().
tap_stream_on_header()
static void tap_stream_on_header (brix_tap_stream_t * st) static
Definition at line 133 of file tap_stream.c.
References brix_tap_emit(), brix_tap_stream_t::cur, brix_tap_stream_t::dir, brix_tap_stream_t::emitted, brix_tap_stream_t::hdr_got, brix_tap_stream_t::in_payload, brix_tap_stream_t::path_cap, brix_tap_stream_t::payload_left, brix_tap_stream_t::tap, tap_header_classify_framing(), tap_header_decode(), and tap_header_set_capture().
Referenced by tap_feed_header().