nginx-xrootd: src/net/tap/tap_decode.c File Reference
tap_decode.c File Reference
#include "tap.h"
#include "protocols/root/protocol/opcodes.h"
#include "protocols/root/protocol/frame_hdr.h"
Functions
int brix_tap_opcode_has_path (uint16_t op)
size_t brix_tap_decode_request (const uint8_t *buf, size_t len, brix_tap_frame_t *out)
size_t brix_tap_decode_response (const uint8_t *buf, size_t len, brix_tap_frame_t *out)
Function Documentation
brix_tap_decode_request()
size_t brix_tap_decode_request (const uint8_t * buf, size_t len, brix_tap_frame_t * out)
Definition at line 36 of file tap_decode.c.
References brix_tap_opcode_has_path(), brix_tap_frame_t::dlen, brix_tap_frame_t::errnum, brix_tap_frame_t::is_request, brix_tap_frame_t::opcode, brix_tap_frame_t::path, brix_tap_frame_t::path_len, brix_tap_frame_t::status, brix_tap_frame_t::streamid, xrd_get_u16_be(), xrd_get_u32_be(), and XRD_REQUEST_HDR_LEN.
Referenced by brix_proxy_dispatch_pending(), brix_proxy_forward_request(), and tap_stream_on_header().
brix_tap_decode_response()
size_t brix_tap_decode_response (const uint8_t * buf, size_t len, brix_tap_frame_t * out)
Definition at line 64 of file tap_decode.c.
References brix_tap_frame_t::dlen, brix_tap_frame_t::errnum, brix_tap_frame_t::is_request, kXR_error, brix_tap_frame_t::opcode, brix_tap_frame_t::path, brix_tap_frame_t::path_len, brix_tap_frame_t::status, brix_tap_frame_t::streamid, xrd_get_u32_be(), and xrd_resp_hdr_unpack().
Referenced by tap_stream_on_header().
brix_tap_opcode_has_path()
int brix_tap_opcode_has_path (uint16_t op)
Definition at line 16 of file tap_decode.c.
References kXR_dirlist, kXR_locate, kXR_mkdir, kXR_mv, kXR_open, kXR_rm, kXR_rmdir, kXR_stat, kXR_statx, and kXR_truncate.
Referenced by brix_tap_decode_request(), and tap_stream_on_header().