nginx-xrootd: src/protocols/webdav/tape_rest_ops.c File Reference
tape_rest_ops.c File Reference
#include "webdav.h"
#include "tape_rest_internal.h"
#include "fs/vfs/vfs.h"
#include "fs/xfer/stage_request_registry.h"
#include "core/http/http_headers.h"
#include "core/compat/safe_size.h"
#include "core/compat/alloc_guard.h"
#include <jansson.h>
#include <string.h>
Macros
#define TAPE_MAX_FILES 4096 /* bulk request fan-out cap */
Functions
static ngx_int_t tape_stage_resolve_all (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *ctx, json_t *files, size_t n, char **abs, const char **logical)
static void tape_stage_apply_checksum (json_t *file_elem, brix_stage_request_view_t *v)
static json_t * tape_stage_enqueue_one (ngx_http_request_t *r, brix_stage_registry_t *q, json_t *files, size_t i, char **abs, const char **logical, char *id, size_t idsz, ngx_http_brix_webdav_req_ctx_t *ctx)
ngx_int_t tape_stage_post (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *ctx, json_t *root)
ngx_int_t tape_stage_get (ngx_http_request_t *r, const char *id)
ngx_int_t tape_stage_list (ngx_http_request_t *r)
ngx_int_t tape_stage_delete (ngx_http_request_t *r, ngx_http_brix_webdav_req_ctx_t *ctx, const char *id)
ngx_int_t tape_stage_cancel (ngx_http_request_t *r, ngx_http_brix_webdav_req_ctx_t *ctx, const char *id)
ngx_int_t tape_release (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *ctx, json_t *root)
ngx_int_t tape_archiveinfo (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *ctx, json_t *root)
Macro Definition Documentation
TAPE_MAX_FILES
#define TAPE_MAX_FILES 4096 /* bulk request fan-out cap */
Definition at line 33 of file tape_rest_ops.c.
Function Documentation
tape_archiveinfo()
ngx_int_t tape_archiveinfo (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * ctx, json_t * root)
Definition at line 407 of file tape_rest_ops.c.
References BRIX_PNALLOC_OR_RETURN, BRIX_SD_RES_NEARLINE, BRIX_SD_RES_OFFLINE, BRIX_SD_RES_ONLINE, nearline, tape_authz_path(), tape_error(), tape_locality_name(), TAPE_PATH_MAX, tape_residency(), and tape_send_object().
Referenced by tape_dispatch_post().
tape_release()
ngx_int_t tape_release (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * ctx, json_t * root)
Definition at line 354 of file tape_rest_ops.c.
References BRIX_PNALLOC_OR_RETURN, brix_stage_request_pin_release(), tape_authz_path(), tape_error(), TAPE_PATH_MAX, tape_queue(), and tape_send_object().
Referenced by tape_dispatch_post().
tape_stage_apply_checksum()
static void tape_stage_apply_checksum (json_t * file_elem, brix_stage_request_view_t * v) static
Definition at line 105 of file tape_rest_ops.c.
References brix_stage_request_view_t::cs_type, brix_stage_request_view_t::cs_value, and tape_cstype_from_name().
Referenced by tape_stage_enqueue_one().
tape_stage_cancel()
ngx_int_t tape_stage_cancel (ngx_http_request_t * r, ngx_http_brix_webdav_req_ctx_t * ctx, const char * id)
Definition at line 329 of file tape_rest_ops.c.
References brix_identity_dn_cstr(), brix_stage_request_cancel(), brix_stage_request_owner_check(), ngx_http_brix_webdav_req_ctx_t::identity, tape_error(), and tape_queue().
Referenced by tape_dispatch_post().
tape_stage_delete()
ngx_int_t tape_stage_delete (ngx_http_request_t * r, ngx_http_brix_webdav_req_ctx_t * ctx, const char * id)
Definition at line 303 of file tape_rest_ops.c.
References brix_identity_dn_cstr(), brix_stage_request_delete(), brix_stage_request_owner_check(), ngx_http_brix_webdav_req_ctx_t::identity, tape_error(), and tape_queue().
Referenced by webdav_tape_handle().
tape_stage_enqueue_one()
static json_t * tape_stage_enqueue_one (ngx_http_request_t * r, brix_stage_registry_t * q, json_t * files, size_t i, char ** abs, const char ** logical, char * id, size_t idsz, ngx_http_brix_webdav_req_ctx_t * ctx) static
Definition at line 136 of file tape_rest_ops.c.
References brix_identity_dn_cstr(), BRIX_STAGE_REQID_LEN, brix_stage_request_add(), ngx_http_brix_webdav_req_ctx_t::identity, brix_stage_request_view_t::lfn, ngx_memcpy, brix_stage_request_view_t::requester_dn, and tape_stage_apply_checksum().
Referenced by tape_stage_post().
tape_stage_get()
ngx_int_t tape_stage_get (ngx_http_request_t * r, const char * id)
Definition at line 236 of file tape_rest_ops.c.
References BRIX_SD_RES_ONLINE, BRIX_STAGE_REQ_FAILED, brix_stage_request_get(), brix_stage_request_t::lfn, nearline, brix_stage_request_t::status, tape_error(), tape_queue(), tape_residency(), tape_send_object(), tape_state_name(), and brix_stage_request_t::tod_added.
Referenced by webdav_tape_handle().
tape_stage_list()
ngx_int_t tape_stage_list (ngx_http_request_t * r)
Definition at line 275 of file tape_rest_ops.c.
References brix_stage_request_list_active(), brix_stage_request_t::lfn, brix_stage_request_t::reqid, brix_stage_request_t::status, tape_error(), tape_queue(), tape_send_object(), and tape_state_name().
Referenced by webdav_tape_handle().
tape_stage_post()
ngx_int_t tape_stage_post (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * ctx, json_t * root)
Definition at line 170 of file tape_rest_ops.c.
References brix_http_set_header(), brix_palloc_array(), tape_error(), TAPE_ID_LEN, TAPE_MAX_FILES, tape_mint_id(), tape_queue(), tape_send_object(), tape_stage_enqueue_one(), and tape_stage_resolve_all().
Referenced by tape_dispatch_post().
tape_stage_resolve_all()
static ngx_int_t tape_stage_resolve_all (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * ctx, json_t * files, size_t n, char ** abs, const char ** logical) static
Definition at line 57 of file tape_rest_ops.c.
References BRIX_PNALLOC_OR_RETURN, tape_authz_path(), tape_error(), and TAPE_PATH_MAX.
Referenced by tape_stage_post().