nginx-xrootd: src/protocols/webdav/tape_rest.c File Reference
tape_rest.c File Reference
#include "webdav.h"
#include "tape_rest.h"
#include "fs/vfs/vfs.h"
#include "fs/xfer/stage_request_registry.h"
#include "core/http/http_body.h"
#include "core/http/http_headers.h"
#include "core/compat/safe_size.h"
#include <jansson.h>
#include <openssl/rand.h>
#include <string.h>
#include "core/compat/alloc_guard.h"
Macros
#define TAPE_PATH_MAX 4096 /* confined absolute-path buffer */
#define TAPE_API_PREFIX "/api/v1/"
#define TAPE_BODY_MAX (1u << 20) /* 1 MiB of request JSON */
#define TAPE_MAX_FILES 4096 /* bulk request fan-out cap */
#define TAPE_ID_LEN 33 /* 16 random bytes as hex + NUL */
Functions
static brix_stage_registry_t * tape_queue (void)
static ngx_int_t tape_send_json (ngx_http_request_t *r, ngx_int_t status, const char *json)
static ngx_int_t tape_error (ngx_http_request_t *r, ngx_int_t status, const char *detail)
static ngx_int_t tape_send_object (ngx_http_request_t *r, ngx_int_t status, json_t *o)
static void tape_mint_id (char *buf, size_t sz)
static brix_stage_cstype_t tape_cstype_from_name (const char *name)
static const char * tape_state_name (brix_stage_req_status_t status)
static ngx_int_t tape_residency (ngx_http_request_t *r, const char *abs, brix_sd_residency_t *state, int *nearline)
static const char * tape_locality_name (brix_sd_residency_t state, int nearline)
static ngx_int_t tape_authz_path (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *ctx, const char *logical, int need_write, char *abs, size_t abssz)
static ngx_int_t tape_stage_post (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *ctx, json_t *root)
static ngx_int_t tape_stage_get (ngx_http_request_t *r, const char *id)
static ngx_int_t tape_stage_list (ngx_http_request_t *r)
static ngx_int_t tape_stage_delete (ngx_http_request_t *r, ngx_http_brix_webdav_req_ctx_t *ctx, const char *id)
static ngx_int_t tape_stage_cancel (ngx_http_request_t *r, ngx_http_brix_webdav_req_ctx_t *ctx, const char *id)
static ngx_int_t tape_release (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *ctx, json_t *root)
static ngx_int_t tape_archiveinfo (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *ctx, json_t *root)
static ngx_uint_t tape_split (ngx_http_request_t *r, char *buf, size_t bufsz, char *seg[3])
static json_t * tape_parse_body (ngx_http_request_t *r)
static ngx_int_t tape_dispatch_post (ngx_http_request_t *r)
static void tape_post_body_handler (ngx_http_request_t *r)
ngx_int_t webdav_tape_handle (ngx_http_request_t *r)
Macro Definition Documentation
TAPE_API_PREFIX
#define TAPE_API_PREFIX "/api/v1/"
Definition at line 42 of file tape_rest.c.
TAPE_BODY_MAX
#define TAPE_BODY_MAX (1u << 20) /* 1 MiB of request JSON */
Definition at line 43 of file tape_rest.c.
TAPE_ID_LEN
#define TAPE_ID_LEN 33 /* 16 random bytes as hex + NUL */
Definition at line 45 of file tape_rest.c.
TAPE_MAX_FILES
#define TAPE_MAX_FILES 4096 /* bulk request fan-out cap */
Definition at line 44 of file tape_rest.c.
TAPE_PATH_MAX
#define TAPE_PATH_MAX 4096 /* confined absolute-path buffer */
Definition at line 41 of file tape_rest.c.
Function Documentation
tape_archiveinfo()
static ngx_int_t tape_archiveinfo (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * ctx, json_t * root) static
Definition at line 557 of file tape_rest.c.
References BRIX_PNALLOC_OR_RETURN, BRIX_SD_RES_NEARLINE, BRIX_SD_RES_OFFLINE, BRIX_SD_RES_ONLINE, nearline, tape_authz_path(), tape_error(), tape_locality_name(), TAPE_PATH_MAX, tape_residency(), and tape_send_object().
Referenced by tape_dispatch_post().
tape_authz_path()
static ngx_int_t tape_authz_path (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * ctx, const char * logical, int need_write, char * abs, size_t abssz) static
Definition at line 235 of file tape_rest.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_identity_check_token_scope(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_shared_conf_t::root_canon, ngx_http_brix_webdav_req_ctx_t::token_auth, and webdav_resolve_destination_path().
Referenced by tape_archiveinfo(), tape_release(), and tape_stage_post().
tape_cstype_from_name()
static brix_stage_cstype_t tape_cstype_from_name (const char * name) static
Definition at line 161 of file tape_rest.c.
References BRIX_STAGE_CS_ADLER32, BRIX_STAGE_CS_CRC32, BRIX_STAGE_CS_MD5, BRIX_STAGE_CS_NONE, BRIX_STAGE_CS_SHA1, BRIX_STAGE_CS_SHA2, and name.
Referenced by tape_stage_post().
tape_dispatch_post()
static ngx_int_t tape_dispatch_post (ngx_http_request_t * r) static
Definition at line 680 of file tape_rest.c.
References ngx_http_brix_webdav_module, tape_archiveinfo(), tape_error(), tape_parse_body(), TAPE_PATH_MAX, tape_release(), tape_split(), tape_stage_cancel(), and tape_stage_post().
Referenced by tape_post_body_handler().
tape_error()
static ngx_int_t tape_error (ngx_http_request_t * r, ngx_int_t status, const char * detail) static
Definition at line 94 of file tape_rest.c.
References s, and tape_send_json().
Referenced by tape_archiveinfo(), tape_dispatch_post(), tape_release(), tape_stage_cancel(), tape_stage_delete(), tape_stage_get(), tape_stage_list(), tape_stage_post(), and webdav_tape_handle().
tape_locality_name()
static const char * tape_locality_name (brix_sd_residency_t state, int nearline) static
Definition at line 213 of file tape_rest.c.
References BRIX_SD_RES_LOST, BRIX_SD_RES_NEARLINE, BRIX_SD_RES_OFFLINE, BRIX_SD_RES_ONLINE, and nearline.
Referenced by tape_archiveinfo().
tape_mint_id()
static void tape_mint_id (char * buf, size_t sz) static
Definition at line 136 of file tape_rest.c.
References hex(), and TAPE_ID_LEN.
Referenced by tape_stage_post().
tape_parse_body()
static json_t * tape_parse_body (ngx_http_request_t * r) static
Definition at line 664 of file tape_rest.c.
References brix_http_body_read_all(), and TAPE_BODY_MAX.
Referenced by tape_dispatch_post().
tape_post_body_handler()
static void tape_post_body_handler (ngx_http_request_t * r) static
Definition at line 728 of file tape_rest.c.
References tape_dispatch_post(), and webdav_metrics_finalize_request().
Referenced by webdav_tape_handle().
tape_queue()
static brix_stage_registry_t * tape_queue (void) static
Definition at line 50 of file tape_rest.c.
References brix_stage_registry_singleton().
Referenced by tape_release(), tape_stage_cancel(), tape_stage_delete(), tape_stage_get(), tape_stage_list(), and tape_stage_post().
tape_release()
static ngx_int_t tape_release (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * ctx, json_t * root) static
Definition at line 504 of file tape_rest.c.
References BRIX_PNALLOC_OR_RETURN, brix_stage_request_pin_release(), tape_authz_path(), tape_error(), TAPE_PATH_MAX, tape_queue(), and tape_send_object().
Referenced by tape_dispatch_post().
tape_residency()
static ngx_int_t tape_residency (ngx_http_request_t * r, const char * abs, brix_sd_residency_t * state, int * nearline) static
Definition at line 195 of file tape_rest.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_WEBDAV, brix_vfs_ctx_init(), brix_vfs_residency(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, nearline, ngx_http_brix_webdav_module, brix_vfs_ctx_t::pool, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by tape_archiveinfo(), and tape_stage_get().
tape_send_json()
static ngx_int_t tape_send_json (ngx_http_request_t * r, ngx_int_t status, const char * json) static
Definition at line 58 of file tape_rest.c.
References BRIX_PCALLOC_OR_RETURN, BRIX_PNALLOC_OR_RETURN, and ngx_memcpy.
Referenced by tape_error(), and tape_send_object().
tape_send_object()
static ngx_int_t tape_send_object (ngx_http_request_t * r, ngx_int_t status, json_t * o) static
Definition at line 117 of file tape_rest.c.
References s, and tape_send_json().
Referenced by tape_archiveinfo(), tape_release(), tape_stage_get(), tape_stage_list(), and tape_stage_post().
tape_split()
static ngx_uint_t tape_split (ngx_http_request_t * r, char * buf, size_t bufsz, char * seg[3]) static
Definition at line 633 of file tape_rest.c.
References ngx_memcpy, and TAPE_API_PREFIX.
Referenced by tape_dispatch_post(), and webdav_tape_handle().
tape_stage_cancel()
static ngx_int_t tape_stage_cancel (ngx_http_request_t * r, ngx_http_brix_webdav_req_ctx_t * ctx, const char * id) static
Definition at line 479 of file tape_rest.c.
References brix_identity_dn_cstr(), brix_stage_request_cancel(), brix_stage_request_owner_check(), ngx_http_brix_webdav_req_ctx_t::identity, tape_error(), and tape_queue().
Referenced by tape_dispatch_post().
tape_stage_delete()
static ngx_int_t tape_stage_delete (ngx_http_request_t * r, ngx_http_brix_webdav_req_ctx_t * ctx, const char * id) static
Definition at line 453 of file tape_rest.c.
References brix_identity_dn_cstr(), brix_stage_request_delete(), brix_stage_request_owner_check(), ngx_http_brix_webdav_req_ctx_t::identity, tape_error(), and tape_queue().
Referenced by webdav_tape_handle().
tape_stage_get()
static ngx_int_t tape_stage_get (ngx_http_request_t * r, const char * id) static
Definition at line 385 of file tape_rest.c.
References BRIX_SD_RES_ONLINE, BRIX_STAGE_REQ_FAILED, brix_stage_request_get(), brix_stage_request_t::lfn, nearline, brix_stage_request_t::status, tape_error(), tape_queue(), tape_residency(), tape_send_object(), tape_state_name(), and brix_stage_request_t::tod_added.
Referenced by webdav_tape_handle().
tape_stage_list()
static ngx_int_t tape_stage_list (ngx_http_request_t * r) static
Definition at line 424 of file tape_rest.c.
References brix_stage_request_list_active(), brix_stage_request_t::lfn, brix_stage_request_t::reqid, brix_stage_request_t::status, tape_error(), tape_queue(), tape_send_object(), and tape_state_name().
Referenced by webdav_tape_handle().
tape_stage_post()
static ngx_int_t tape_stage_post (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * ctx, json_t * root) static
Definition at line 269 of file tape_rest.c.
References brix_http_set_header(), brix_identity_dn_cstr(), brix_palloc_array(), BRIX_PNALLOC_OR_RETURN, BRIX_STAGE_REQID_LEN, brix_stage_request_add(), brix_stage_request_view_t::cs_type, brix_stage_request_view_t::cs_value, ngx_http_brix_webdav_req_ctx_t::identity, brix_stage_request_view_t::lfn, ngx_memcpy, brix_stage_request_view_t::requester_dn, tape_authz_path(), tape_cstype_from_name(), tape_error(), TAPE_ID_LEN, TAPE_MAX_FILES, tape_mint_id(), TAPE_PATH_MAX, tape_queue(), and tape_send_object().
Referenced by tape_dispatch_post().
tape_state_name()
static const char * tape_state_name (brix_stage_req_status_t status) static
Definition at line 180 of file tape_rest.c.
References BRIX_STAGE_REQ_ACTIVE, BRIX_STAGE_REQ_CANCELLED, BRIX_STAGE_REQ_DONE, BRIX_STAGE_REQ_FAILED, and BRIX_STAGE_REQ_QUEUED.
Referenced by tape_stage_get(), and tape_stage_list().
webdav_tape_handle()
ngx_int_t webdav_tape_handle (ngx_http_request_t * r)
Definition at line 735 of file tape_rest.c.
References ngx_http_brix_webdav_loc_conf_t::auth, brix_http_read_body(), ngx_http_brix_webdav_module, tape_error(), TAPE_PATH_MAX, tape_post_body_handler(), tape_split(), tape_stage_delete(), tape_stage_get(), tape_stage_list(), ngx_http_brix_webdav_req_ctx_t::verified, and WEBDAV_AUTH_REQUIRED.
Referenced by webdav_dispatch_inner().