nginx-xrootd: src/protocols/webdav/tape_rest_internal.h File Reference
tape_rest_internal.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include <jansson.h>
#include "webdav.h"
#include "fs/vfs/vfs.h"
#include "fs/xfer/stage_request_registry.h"
Macros
#define TAPE_PATH_MAX 4096
#define TAPE_ID_LEN 40
Functions
brix_stage_registry_t * tape_queue (void)
ngx_int_t tape_error (ngx_http_request_t *r, ngx_int_t status, const char *detail)
ngx_int_t tape_send_object (ngx_http_request_t *r, ngx_int_t status, json_t *o)
void tape_mint_id (char *buf, size_t sz)
brix_stage_cstype_t tape_cstype_from_name (const char *name)
const char * tape_state_name (brix_stage_req_status_t status)
ngx_int_t tape_residency (ngx_http_request_t *r, const char *abs, brix_sd_residency_t *state, int *nearline)
const char * tape_locality_name (brix_sd_residency_t state, int nearline)
ngx_int_t tape_authz_path (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *ctx, const char *logical, int need_write, char *abs, size_t abssz)
ngx_int_t tape_stage_post (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *ctx, json_t *root)
ngx_int_t tape_stage_get (ngx_http_request_t *r, const char *id)
ngx_int_t tape_stage_list (ngx_http_request_t *r)
ngx_int_t tape_stage_delete (ngx_http_request_t *r, ngx_http_brix_webdav_req_ctx_t *ctx, const char *id)
ngx_int_t tape_stage_cancel (ngx_http_request_t *r, ngx_http_brix_webdav_req_ctx_t *ctx, const char *id)
ngx_int_t tape_release (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *ctx, json_t *root)
ngx_int_t tape_archiveinfo (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *ctx, json_t *root)
Macro Definition Documentation
TAPE_ID_LEN
#define TAPE_ID_LEN 40
Definition at line 44 of file tape_rest_internal.h.
TAPE_PATH_MAX
#define TAPE_PATH_MAX 4096
Definition at line 34 of file tape_rest_internal.h.
Function Documentation
tape_archiveinfo()
ngx_int_t tape_archiveinfo (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * ctx, json_t * root)
Definition at line 407 of file tape_rest_ops.c.
References BRIX_PNALLOC_OR_RETURN, BRIX_SD_RES_NEARLINE, BRIX_SD_RES_OFFLINE, BRIX_SD_RES_ONLINE, nearline, tape_authz_path(), tape_error(), tape_locality_name(), TAPE_PATH_MAX, tape_residency(), and tape_send_object().
Referenced by tape_dispatch_post().
tape_authz_path()
ngx_int_t tape_authz_path (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * ctx, const char * logical, int need_write, char * abs, size_t abssz)
Definition at line 234 of file tape_rest.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_identity_check_token_scope(), ngx_http_brix_shared_conf_t::cache_store_endpoint, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_shared_conf_t::root_canon, ngx_http_brix_webdav_req_ctx_t::token_auth, and webdav_resolve_destination_path().
Referenced by tape_archiveinfo(), tape_release(), and tape_stage_resolve_all().
tape_cstype_from_name()
brix_stage_cstype_t tape_cstype_from_name (const char * name)
Definition at line 160 of file tape_rest.c.
References BRIX_STAGE_CS_ADLER32, BRIX_STAGE_CS_CRC32, BRIX_STAGE_CS_MD5, BRIX_STAGE_CS_NONE, BRIX_STAGE_CS_SHA1, BRIX_STAGE_CS_SHA2, and name.
Referenced by tape_stage_apply_checksum().
tape_error()
ngx_int_t tape_error (ngx_http_request_t * r, ngx_int_t status, const char * detail)
Definition at line 93 of file tape_rest.c.
References s, and tape_send_json().
Referenced by tape_archiveinfo(), tape_dispatch_post(), tape_release(), tape_stage_cancel(), tape_stage_delete(), tape_stage_get(), tape_stage_list(), tape_stage_post(), tape_stage_resolve_all(), and webdav_tape_handle().
tape_locality_name()
const char * tape_locality_name (brix_sd_residency_t state, int nearline)
Definition at line 212 of file tape_rest.c.
References BRIX_SD_RES_LOST, BRIX_SD_RES_NEARLINE, BRIX_SD_RES_OFFLINE, BRIX_SD_RES_ONLINE, and nearline.
Referenced by tape_archiveinfo().
tape_mint_id()
void tape_mint_id (char * buf, size_t sz)
Definition at line 135 of file tape_rest.c.
References hex(), and TAPE_ID_LEN.
Referenced by tape_stage_post().
tape_queue()
brix_stage_registry_t * tape_queue (void)
Definition at line 49 of file tape_rest.c.
References brix_stage_registry_singleton().
Referenced by tape_release(), tape_stage_cancel(), tape_stage_delete(), tape_stage_get(), tape_stage_list(), and tape_stage_post().
tape_release()
ngx_int_t tape_release (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * ctx, json_t * root)
Definition at line 354 of file tape_rest_ops.c.
References BRIX_PNALLOC_OR_RETURN, brix_stage_request_pin_release(), tape_authz_path(), tape_error(), TAPE_PATH_MAX, tape_queue(), and tape_send_object().
Referenced by tape_dispatch_post().
tape_residency()
ngx_int_t tape_residency (ngx_http_request_t * r, const char * abs, brix_sd_residency_t * state, int * nearline)
Definition at line 194 of file tape_rest.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_WEBDAV, brix_vfs_ctx_init(), brix_vfs_residency(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, nearline, ngx_http_brix_webdav_module, brix_vfs_ctx_t::pool, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by tape_archiveinfo(), and tape_stage_get().
tape_send_object()
ngx_int_t tape_send_object (ngx_http_request_t * r, ngx_int_t status, json_t * o)
Definition at line 116 of file tape_rest.c.
References s, and tape_send_json().
Referenced by tape_archiveinfo(), tape_release(), tape_stage_get(), tape_stage_list(), and tape_stage_post().
tape_stage_cancel()
ngx_int_t tape_stage_cancel (ngx_http_request_t * r, ngx_http_brix_webdav_req_ctx_t * ctx, const char * id)
Definition at line 329 of file tape_rest_ops.c.
References brix_identity_dn_cstr(), brix_stage_request_cancel(), brix_stage_request_owner_check(), ngx_http_brix_webdav_req_ctx_t::identity, tape_error(), and tape_queue().
Referenced by tape_dispatch_post().
tape_stage_delete()
ngx_int_t tape_stage_delete (ngx_http_request_t * r, ngx_http_brix_webdav_req_ctx_t * ctx, const char * id)
Definition at line 303 of file tape_rest_ops.c.
References brix_identity_dn_cstr(), brix_stage_request_delete(), brix_stage_request_owner_check(), ngx_http_brix_webdav_req_ctx_t::identity, tape_error(), and tape_queue().
Referenced by webdav_tape_handle().
tape_stage_get()
ngx_int_t tape_stage_get (ngx_http_request_t * r, const char * id)
Definition at line 236 of file tape_rest_ops.c.
References BRIX_SD_RES_ONLINE, BRIX_STAGE_REQ_FAILED, brix_stage_request_get(), brix_stage_request_t::lfn, nearline, brix_stage_request_t::status, tape_error(), tape_queue(), tape_residency(), tape_send_object(), tape_state_name(), and brix_stage_request_t::tod_added.
Referenced by webdav_tape_handle().
tape_stage_list()
ngx_int_t tape_stage_list (ngx_http_request_t * r)
Definition at line 275 of file tape_rest_ops.c.
References brix_stage_request_list_active(), brix_stage_request_t::lfn, brix_stage_request_t::reqid, brix_stage_request_t::status, tape_error(), tape_queue(), tape_send_object(), and tape_state_name().
Referenced by webdav_tape_handle().
tape_stage_post()
ngx_int_t tape_stage_post (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * ctx, json_t * root)
Definition at line 170 of file tape_rest_ops.c.
References brix_http_set_header(), brix_palloc_array(), tape_error(), TAPE_ID_LEN, TAPE_MAX_FILES, tape_mint_id(), tape_queue(), tape_send_object(), tape_stage_enqueue_one(), and tape_stage_resolve_all().
Referenced by tape_dispatch_post().
tape_state_name()
const char * tape_state_name (brix_stage_req_status_t status)
Definition at line 179 of file tape_rest.c.
References BRIX_STAGE_REQ_ACTIVE, BRIX_STAGE_REQ_CANCELLED, BRIX_STAGE_REQ_DONE, BRIX_STAGE_REQ_FAILED, and BRIX_STAGE_REQ_QUEUED.
Referenced by tape_stage_get(), and tape_stage_list().