nginx-xrootd: src/core/config/tape_stage_conf.h File Reference
tape_stage_conf.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
Data Structures
struct brix_frm_conf_t
Functions
void brix_frm_conf_init (brix_frm_conf_t *frm)
char * brix_frm_conf_merge (ngx_conf_t *cf, brix_frm_conf_t *conf, brix_frm_conf_t *prev, const ngx_str_t *prepare_command)
char * brix_frm_set_purge_watermark (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Function Documentation
brix_frm_conf_init()
void brix_frm_conf_init (brix_frm_conf_t * frm)
Definition at line 15 of file tape_stage_conf.c.
References brix_frm_conf_t::async_recall, brix_frm_conf_t::control_dir, brix_frm_conf_t::copy_timeout, brix_frm_conf_t::copycmd, brix_frm_conf_t::copymax, brix_frm_conf_t::enable, brix_frm_conf_t::fail_backoff_ms, brix_frm_conf_t::fail_retries, brix_frm_conf_t::force_scratch, brix_frm_conf_t::max_inflight, brix_frm_conf_t::max_per_source, brix_frm_conf_t::migrate_copycmd, brix_frm_conf_t::purge_hi_ppm, brix_frm_conf_t::purge_interval_ms, brix_frm_conf_t::purge_lo_ppm, brix_frm_conf_t::queue_path, brix_frm_conf_t::residency_cmd, brix_frm_conf_t::stage_dir, brix_frm_conf_t::stage_ttl, brix_frm_conf_t::stage_wait, brix_frm_conf_t::stagecmd, and brix_frm_conf_t::xfrhold_ms.
Referenced by ngx_stream_brix_create_srv_conf().
brix_frm_conf_merge()
char * brix_frm_conf_merge (ngx_conf_t * cf, brix_frm_conf_t * conf, brix_frm_conf_t * prev, const ngx_str_t * prepare_command)
Definition at line 42 of file tape_stage_conf.c.
References brix_frm_conf_t::async_recall, brix_frm_conf_t::control_dir, brix_frm_conf_t::copy_timeout, brix_frm_conf_t::copycmd, brix_frm_conf_t::copymax, brix_frm_conf_t::enable, brix_frm_conf_t::fail_backoff_ms, brix_frm_conf_t::fail_retries, brix_frm_conf_t::force_scratch, brix_frm_conf_t::max_inflight, brix_frm_conf_t::max_per_source, brix_frm_conf_t::migrate_copycmd, brix_frm_conf_t::purge_hi_ppm, brix_frm_conf_t::purge_interval_ms, brix_frm_conf_t::purge_lo_ppm, brix_frm_conf_t::queue_path, brix_frm_conf_t::residency_cmd, brix_frm_conf_t::stage_dir, brix_frm_conf_t::stage_ttl, brix_frm_conf_t::stage_wait, brix_frm_conf_t::stagecmd, and brix_frm_conf_t::xfrhold_ms.
Referenced by brix_merge_srv_security().
brix_frm_set_purge_watermark()
char * brix_frm_set_purge_watermark (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 117 of file tape_stage_conf.c.
References frm_ratio_to_ppm(), brix_frm_conf_t::purge_hi_ppm, and brix_frm_conf_t::purge_lo_ppm.