nginx-xrootd: src/net/ratelimit/throttle_compat.c File Reference
throttle_compat.c File Reference
#include "throttle_compat.h"
#include "auth/token/ini.h"
#include <string.h>
#include <stdlib.h>
Functions
static int uc_kv (void *u, const char *section, const char *key, const char *val)
int brix_throttle_userconfig_load (const char *path, brix_throttle_uc_t *uc, char *errbuf, size_t errlen)
ngx_uint_t brix_throttle_userconfig_match (const brix_throttle_uc_t *uc, const char *user)
static brix_rl_node_t * throttle_node_locked (brix_rl_zone_t *zone, const char *user)
void brix_throttle_charge_io (brix_rl_zone_t *zone, ngx_msec_t interval_ms, const char *user, uint64_t service_us)
int brix_throttle_ioload_over (brix_rl_zone_t *zone, ngx_msec_t interval_ms, const char *user, double concurrency)
int brix_throttle_open_inc (brix_rl_zone_t *zone, const char *user, ngx_uint_t cap)
void brix_throttle_open_dec (brix_rl_zone_t *zone, const char *user)
Function Documentation
brix_throttle_charge_io()
void brix_throttle_charge_io (brix_rl_zone_t * zone, ngx_msec_t interval_ms, const char * user, uint64_t service_us)
Definition at line 97 of file throttle_compat.c.
References brix_rl_node_t::io_time_us, brix_rl_node_t::io_window, brix_rl_zone_t::sh, brix_rl_zone_t::shpool, and throttle_node_locked().
brix_throttle_ioload_over()
int brix_throttle_ioload_over (brix_rl_zone_t * zone, ngx_msec_t interval_ms, const char * user, double concurrency)
Definition at line 120 of file throttle_compat.c.
References brix_rl_hash(), brix_rl_lookup_locked(), brix_rl_node_t::io_time_us, brix_rl_zone_t::sh, and brix_rl_zone_t::shpool.
brix_throttle_open_dec()
void brix_throttle_open_dec (brix_rl_zone_t * zone, const char * user)
Definition at line 168 of file throttle_compat.c.
References brix_rl_hash(), brix_rl_lookup_locked(), brix_rl_node_t::open_files, brix_rl_zone_t::sh, and brix_rl_zone_t::shpool.
Referenced by brix_close_release_throttle(), and brix_disconnect_release_throttle_slots().
brix_throttle_open_inc()
int brix_throttle_open_inc (brix_rl_zone_t * zone, const char * user, ngx_uint_t cap)
Definition at line 144 of file throttle_compat.c.
References brix_rl_node_t::open_files, brix_rl_zone_t::sh, brix_rl_zone_t::shpool, and throttle_node_locked().
Referenced by brix_open_apply_throttle().
brix_throttle_userconfig_load()
int brix_throttle_userconfig_load (const char * path, brix_throttle_uc_t * uc, char * errbuf, size_t errlen)
Definition at line 43 of file throttle_compat.c.
References brix_ini_parse_file(), and uc_kv().
brix_throttle_userconfig_match()
ngx_uint_t brix_throttle_userconfig_match (const brix_throttle_uc_t * uc, const char * user)
Definition at line 51 of file throttle_compat.c.
References brix_throttle_uc_t::count, brix_throttle_uc_t::global, brix_throttle_uc_rule_t::maxconn, brix_throttle_uc_rule_t::pat, and brix_throttle_uc_t::rules.
throttle_node_locked()
static brix_rl_node_t * throttle_node_locked (brix_rl_zone_t * zone, const char * user) static
Definition at line 85 of file throttle_compat.c.
References brix_rl_create_locked(), brix_rl_hash(), and brix_rl_lookup_locked().
Referenced by brix_throttle_charge_io(), and brix_throttle_open_inc().
uc_kv()
static int uc_kv (void * u, const char * section, const char * key, const char * val) static
Definition at line 20 of file throttle_compat.c.
References BRIX_THROTTLE_MAX_UC_RULES, brix_throttle_uc_t::count, brix_throttle_uc_t::global, key, brix_throttle_uc_rule_t::maxconn, brix_throttle_uc_rule_t::pat, and brix_throttle_uc_t::rules.
Referenced by brix_throttle_userconfig_load().