nginx-xrootd: src/fs/tier/tier_config.c File Reference
tier_config.c File Reference
#include "tier.h"
#include "core/types/fs_list.h"
#include "core/config/root_prepare.h"
#include <limits.h>
#include <stdarg.h>
#include <stdio.h>
#include <string.h>
Macros
#define S(scheme, driver, tls, nearline) { scheme, driver, tls, nearline },
#define MISS_SLOT(field, nm)
#define MISS_CAP(bit, nm)
Functions
static ngx_int_t tier_fail (ngx_conf_t *cf, int log_emerg, char *err, size_t errcap, const char *fmt,...)
static const char * tier_role_directive (brix_tier_role_t role)
static int tier_default_port (const char *driver, int tls)
static const char * tier_sp_for (const char *driver, brix_tier_role_t role)
static ngx_int_t tier_parse_port (brix_tier_parse_t *p, u_char *digits, size_t len, ngx_int_t *portnum)
static ngx_int_t tier_parse_host_v6 (brix_tier_parse_t *p, u_char *authority, size_t authlen)
static ngx_int_t tier_parse_host_plain (brix_tier_parse_t *p, u_char *authority, size_t authlen)
static ngx_int_t tier_copy_remote_path (brix_tier_parse_t *p, u_char *path, size_t pathlen)
static ngx_int_t tier_parse_authority (brix_tier_parse_t *p, u_char *loc, size_t loclen)
static ngx_int_t tier_parse_args (ngx_conf_t *cf, ngx_array_t *args, brix_tier_cfg_t *out, char *err, size_t errcap)
static ngx_int_t tier_split_scheme (brix_tier_parse_t *p, ngx_str_t *url, u_char **loc, size_t *loclen)
static ngx_int_t tier_parse_local (brix_tier_parse_t *p, u_char *loc, size_t loclen)
static ngx_int_t tier_parse_remote (brix_tier_parse_t *p, ngx_str_t *url, u_char *loc, size_t loclen)
ngx_int_t brix_tier_parse_store (brix_tier_parse_t *p, ngx_str_t *url, ngx_array_t *args, brix_tier_role_t role)
brix_tier_status_t brix_tier_status (const brix_tier_cfg_t *t, brix_sd_instance_t *probe, brix_tier_gap_t *gap_out)
Variables
struct {
const char * scheme
const char * driver
int tls
int nearline
} tier_schemes []
Macro Definition Documentation
MISS_CAP
#define MISS_CAP (bit, nm)
Value:
    do {                                                                       \
        if ((caps & (bit)) == 0) {                                             \
            ngx_cpystrn((u_char *) g.cap, (u_char *) (nm), sizeof(g.cap));      \
            if (gap_out != NULL) { *gap_out = g; }                             \
            return BRIX_TIER_NEEDS_DEV;                                       \
        }                                                                      \
    } while (0)
MISS_SLOT
#define MISS_SLOT (field, nm)
Value:
    do {                                                                       \
        if (d->field == NULL) {                                                \
            ngx_cpystrn((u_char *) g.slot, (u_char *) (nm), sizeof(g.slot));    \
            if (gap_out != NULL) { *gap_out = g; }                             \
            return BRIX_TIER_NEEDS_DEV;                                       \
        }                                                                      \
    } while (0)
S
#define S (scheme, driver, tls, nearline) { scheme, driver, tls, nearline },
Function Documentation
brix_tier_parse_store()
ngx_int_t brix_tier_parse_store (brix_tier_parse_t * p, ngx_str_t * url, ngx_array_t * args, brix_tier_role_t role)
Definition at line 431 of file tier_config.c.
References brix_tier_parse_t::cf, brix_tier_cfg_t::configured, brix_tier_cfg_t::driver, brix_tier_parse_t::err, brix_tier_parse_t::errcap, brix_tier_parse_t::out, brix_tier_cfg_t::role, tier_fail(), tier_parse_args(), tier_parse_local(), tier_parse_remote(), and tier_split_scheme().
Referenced by brix_tier_register_cache_store(), and brix_tier_register_stores().
brix_tier_status()
brix_tier_status_t brix_tier_status (const brix_tier_cfg_t * t, brix_sd_instance_t * probe, brix_tier_gap_t * gap_out)
Definition at line 471 of file tier_config.c.
References BRIX_SD_CAP_DIRS, BRIX_SD_CAP_NEARLINE, BRIX_SD_CAP_RANDOM_WRITE, BRIX_SD_CAP_RANGE_READ, BRIX_SD_CAP_XATTR, BRIX_TIER_BACKEND, BRIX_TIER_CACHE, BRIX_TIER_NEEDS_DEV, BRIX_TIER_READY, BRIX_TIER_STAGE, brix_tier_cfg_t::driver, fstat(), MISS_CAP, MISS_SLOT, brix_tier_cfg_t::nearline, open(), pread(), probe(), brix_tier_cfg_t::role, brix_tier_gap_t::slot, brix_tier_gap_t::sp_item, stat(), and tier_sp_for().
tier_copy_remote_path()
static ngx_int_t tier_copy_remote_path (brix_tier_parse_t * p, u_char * path, size_t pathlen) static
Definition at line 202 of file tier_config.c.
References brix_tier_parse_t::cf, brix_tier_parse_t::err, brix_tier_parse_t::errcap, ngx_memcpy, brix_tier_parse_t::out, brix_tier_cfg_t::path, and tier_fail().
Referenced by tier_parse_authority().
tier_default_port()
static int tier_default_port (const char * driver, int tls) static
Definition at line 83 of file tier_config.c.
References driver, and tls.
Referenced by tier_parse_remote().
tier_fail()
static ngx_int_t tier_fail (ngx_conf_t * cf, int log_emerg, char * err, size_t errcap, const char * fmt, ...) static
Definition at line 48 of file tier_config.c.
Referenced by brix_tier_parse_store(), tier_copy_remote_path(), tier_parse_args(), tier_parse_authority(), tier_parse_host_plain(), tier_parse_host_v6(), tier_parse_local(), tier_parse_port(), tier_parse_remote(), and tier_split_scheme().
tier_parse_args()
static ngx_int_t tier_parse_args (ngx_conf_t * cf, ngx_array_t * args, brix_tier_cfg_t * out, char * err, size_t errcap) static
Definition at line 266 of file tier_config.c.
References brix_tier_cfg_t::block_size, brix_credential_lookup(), c, brix_tier_cfg_t::credential, name, ngx_memcpy, and tier_fail().
Referenced by brix_tier_parse_store().
tier_parse_authority()
static ngx_int_t tier_parse_authority (brix_tier_parse_t * p, u_char * loc, size_t loclen) static
Definition at line 229 of file tier_config.c.
References brix_tier_parse_t::cf, brix_tier_parse_t::err, brix_tier_parse_t::errcap, tier_copy_remote_path(), tier_fail(), tier_parse_host_plain(), and tier_parse_host_v6().
Referenced by tier_parse_remote().
tier_parse_host_plain()
static ngx_int_t tier_parse_host_plain (brix_tier_parse_t * p, u_char * authority, size_t authlen) static
Definition at line 165 of file tier_config.c.
References brix_tier_parse_t::cf, brix_tier_parse_t::err, brix_tier_parse_t::errcap, brix_tier_cfg_t::host, ngx_memcpy, brix_tier_parse_t::out, brix_tier_cfg_t::port, tier_fail(), and tier_parse_port().
Referenced by tier_parse_authority().
tier_parse_host_v6()
static ngx_int_t tier_parse_host_v6 (brix_tier_parse_t * p, u_char * authority, size_t authlen) static
Definition at line 128 of file tier_config.c.
References brix_tier_parse_t::cf, brix_tier_parse_t::err, brix_tier_parse_t::errcap, brix_tier_cfg_t::host, ngx_memcpy, brix_tier_parse_t::out, brix_tier_cfg_t::port, tier_fail(), and tier_parse_port().
Referenced by tier_parse_authority().
tier_parse_local()
static ngx_int_t tier_parse_local (brix_tier_parse_t * p, u_char * loc, size_t loclen) static
Definition at line 371 of file tier_config.c.
References brix_export_root_opts_t::allow_write, brix_prepare_export_root(), BRIX_TIER_BACKEND, brix_export_root_opts_t::canon_size, brix_tier_parse_t::cf, brix_export_root_opts_t::directive_name, brix_tier_parse_t::err, brix_tier_parse_t::errcap, brix_tier_parse_t::out, brix_tier_cfg_t::path, PATH_MAX, brix_export_root_opts_t::required, brix_tier_cfg_t::role, tier_fail(), and tier_role_directive().
Referenced by brix_tier_parse_store().
tier_parse_port()
static ngx_int_t tier_parse_port (brix_tier_parse_t * p, u_char * digits, size_t len, ngx_int_t * portnum) static
Definition at line 114 of file tier_config.c.
References brix_tier_parse_t::cf, brix_tier_parse_t::err, brix_tier_parse_t::errcap, and tier_fail().
Referenced by tier_parse_host_plain(), and tier_parse_host_v6().
tier_parse_remote()
static ngx_int_t tier_parse_remote (brix_tier_parse_t * p, ngx_str_t * url, u_char * loc, size_t loclen) static
Definition at line 406 of file tier_config.c.
References brix_tier_parse_t::cf, brix_tier_cfg_t::driver, brix_tier_parse_t::err, brix_tier_parse_t::errcap, brix_tier_parse_t::out, brix_tier_cfg_t::port, tier_default_port(), tier_fail(), tier_parse_authority(), and brix_tier_cfg_t::tls.
Referenced by brix_tier_parse_store().
tier_role_directive()
static const char * tier_role_directive (brix_tier_role_t role) static
Definition at line 70 of file tier_config.c.
References BRIX_TIER_BACKEND, BRIX_TIER_CACHE, and BRIX_TIER_STAGE.
Referenced by tier_parse_local().
tier_sp_for()
static const char * tier_sp_for (const char * driver, brix_tier_role_t role) static
Definition at line 93 of file tier_config.c.
References driver.
Referenced by brix_tier_status().
tier_split_scheme()
static ngx_int_t tier_split_scheme (brix_tier_parse_t * p, ngx_str_t * url, u_char ** loc, size_t * loclen) static
Definition at line 325 of file tier_config.c.
References brix_tier_parse_t::cf, brix_tier_cfg_t::driver, driver, brix_tier_parse_t::err, brix_tier_parse_t::errcap, brix_tier_cfg_t::nearline, nearline, brix_tier_parse_t::out, scheme, tier_fail(), tier_schemes, brix_tier_cfg_t::tls, and tls.
Referenced by brix_tier_parse_store().
Variable Documentation
driver
const char* driver
Definition at line 27 of file tier_config.c.
Referenced by brix_sd_instance_create(), tier_default_port(), tier_needs_dev(), tier_sp_for(), tier_split_scheme(), xrd_mount(), and xrd_mount_build_argv().
nearline
int nearline
Definition at line 29 of file tier_config.c.
Referenced by propfind_emit_locality(), tape_archiveinfo(), tape_locality_name(), tape_residency(), tape_stage_get(), and tier_split_scheme().
scheme
const char* scheme
Definition at line 26 of file tier_config.c.
Referenced by brix_vfs_open(), brix_vfs_stat_url(), fs_find_endpoint(), mac_build_location(), mac_request_respond(), parse_remote(), s3_download_loop(), tier_split_scheme(), vfs_find_backend(), web_download_loop(), webdav_handle_macaroon_discovery(), and webdav_tpc_url_path().
[struct]
const struct { ... } tier_schemes[]
Initial value:
= {
#define S(scheme, driver, tls, nearline)
     {  "posix" ,  "posix" ,  0 ,  0  },    {  "pblock" ,  "pblock" ,  0 ,  0  },    {  "root" ,  "xroot" ,  0 ,  0  },    {  "roots" ,  "xroot" ,  1 ,  0  },    {  "http" ,  "http" ,  0 ,  0  },    {  "https" ,  "http" ,  1 ,  0  },    {  "webdav" ,  "http" ,  0 ,  0  },    {  "davs" ,  "http" ,  1 ,  0  },    {  "s3" ,  "s3" ,  0 ,  0  },    {  "rados" ,  "rados" ,  0 ,  0  },    {  "ceph" ,  "ceph" ,  0 ,  0  },    {  "tape" ,  "tape" ,  0 ,  1  },    {  "frm" ,  "frm" ,  0 ,  1  },
}
Referenced by tier_split_scheme().
tls
int tls
Definition at line 28 of file tier_config.c.
Referenced by brix_cvmfs_geo_passthrough(), brix_http_download(), brix_http_req(), brix_http_upload(), brix_http_upload_resumable(), brix_kaconn_init(), brix_vfs_backend_config_http(), brix_vfs_backend_config_s3(), brix_vfs_backend_config_xroot(), brix_vfs_backend_http_endpoint(), brix_vfs_backend_register_http_upstream(), brix_vfs_backend_set_xroot(), brix_webmeta_init(), dx_http_fail(), dx_scheme_match(), http_download_attempt(), http_record_tls(), httpx_connect(), main(), s3o_request(), s3o_request_cred(), s3t_request(), tier_default_port(), and tier_split_scheme().