nginx-xrootd: src/fs/tier/tier.h File Reference
tier.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <regex.h>
#include "fs/backend/sd.h"
#include "fs/cache/verify.h"
#include "fs/cache/writethrough_decision.h"
#include "core/config/credential_block.h"
#include "core/types/config.h"
Data Structures
struct brix_tier_cfg_t
struct brix_cache_policy_t
struct brix_stage_policy_t
struct brix_tier_stack_t
struct brix_tier_gap_t
struct brix_tier_parse_t
Enumerations
enum brix_tier_role_t { BRIX_TIER_BACKEND = 0 , BRIX_TIER_CACHE = 1 , BRIX_TIER_STAGE = 2 }
enum brix_tier_status_t { BRIX_TIER_READY = 0 , BRIX_TIER_NEEDS_DEV = 1 }
Functions
ngx_int_t brix_tier_parse_store (brix_tier_parse_t *p, ngx_str_t *url, ngx_array_t *args, brix_tier_role_t role)
brix_tier_status_t brix_tier_status (const brix_tier_cfg_t *t, brix_sd_instance_t *probe, brix_tier_gap_t *gap_out)
brix_sd_instance_t * brix_tier_build (const brix_tier_cfg_t *t, ngx_log_t *log)
brix_sd_instance_t * brix_tier_build_stack (brix_tier_stack_t *s, ngx_log_t *log)
void brix_vfs_backend_config_cache_store (const char *root_canon, const brix_tier_cfg_t *cfg, const brix_cache_policy_t *policy)
void brix_vfs_backend_config_cache_cold_store (const char *root_canon, const brix_tier_cfg_t *cfg)
void brix_vfs_backend_config_cache_peers (const char *root_canon, const char(*hosts)[256], const int *ports, int n, int self)
void brix_vfs_backend_config_stage_store (const char *root_canon, const brix_tier_cfg_t *cfg, const brix_stage_policy_t *policy)
Enumeration Type Documentation
brix_tier_role_t
enum brix_tier_role_t
Enumerator
BRIX_TIER_BACKEND
BRIX_TIER_CACHE
BRIX_TIER_STAGE
Definition at line 47 of file tier.h.
brix_tier_status_t
enum brix_tier_status_t
Enumerator
BRIX_TIER_READY
BRIX_TIER_NEEDS_DEV
Definition at line 136 of file tier.h.
Function Documentation
brix_tier_build()
brix_sd_instance_t * brix_tier_build (const brix_tier_cfg_t * t, ngx_log_t * log)
Definition at line 238 of file tier_build.c.
References brix_tier_cfg_t::configured, brix_tier_cfg_t::driver, log, tier_build_ceph(), tier_build_http(), tier_build_pblock(), tier_build_posix(), tier_build_s3(), tier_build_tape(), and tier_build_xroot().
Referenced by brix_tier_build_stack(), brix_vbr_wrap_cache_tier(), brix_vbr_wrap_stage_tier(), tier_compose_cache(), and tier_compose_stage().
brix_tier_build_stack()
brix_sd_instance_t * brix_tier_build_stack (brix_tier_stack_t * s, ngx_log_t * log)
Definition at line 335 of file tier_build.c.
References brix_tier_build(), log, s, tier_compose_cache(), and tier_compose_stage().
brix_tier_parse_store()
ngx_int_t brix_tier_parse_store (brix_tier_parse_t * p, ngx_str_t * url, ngx_array_t * args, brix_tier_role_t role)
Definition at line 431 of file tier_config.c.
References brix_tier_parse_t::cf, brix_tier_cfg_t::configured, brix_tier_cfg_t::driver, brix_tier_parse_t::err, brix_tier_parse_t::errcap, brix_tier_parse_t::out, brix_tier_cfg_t::role, tier_fail(), tier_parse_args(), tier_parse_local(), tier_parse_remote(), and tier_split_scheme().
Referenced by brix_tier_register_cache_store(), and brix_tier_register_stores().
brix_tier_status()
brix_tier_status_t brix_tier_status (const brix_tier_cfg_t * t, brix_sd_instance_t * probe, brix_tier_gap_t * gap_out)
Definition at line 471 of file tier_config.c.
References BRIX_SD_CAP_DIRS, BRIX_SD_CAP_NEARLINE, BRIX_SD_CAP_RANDOM_WRITE, BRIX_SD_CAP_RANGE_READ, BRIX_SD_CAP_XATTR, BRIX_TIER_BACKEND, BRIX_TIER_CACHE, BRIX_TIER_NEEDS_DEV, BRIX_TIER_READY, BRIX_TIER_STAGE, brix_tier_cfg_t::driver, fstat(), MISS_CAP, MISS_SLOT, brix_tier_cfg_t::nearline, open(), pread(), probe(), brix_tier_cfg_t::role, brix_tier_gap_t::slot, brix_tier_gap_t::sp_item, stat(), and tier_sp_for().
brix_vfs_backend_config_cache_cold_store()
void brix_vfs_backend_config_cache_cold_store (const char * root_canon, const brix_tier_cfg_t * cfg)
Definition at line 179 of file vfs_backend_config.c.
References brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_entry_t::cold_tier, brix_tier_cfg_t::configured, and brix_vfs_backend_entry_t::inst.
Referenced by brix_tier_register_cache_store().
brix_vfs_backend_config_cache_peers()
void brix_vfs_backend_config_cache_peers (const char * root_canon, const char(*) hosts[256], const int * ports, int n, int self)
Definition at line 196 of file vfs_backend_config.c.
References brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_entry_t::host, brix_vfs_backend_entry_t::inst, brix_vfs_backend_entry_t::n_peer_ring, brix_vfs_backend_entry_t::peer_ring, brix_vfs_backend_entry_t::peer_self, and brix_vfs_backend_entry_t::port.
Referenced by brix_tier_register_cache_peers().
brix_vfs_backend_config_cache_store()
void brix_vfs_backend_config_cache_store (const char * root_canon, const brix_tier_cfg_t * cfg, const brix_cache_policy_t * policy)
Definition at line 159 of file vfs_backend_config.c.
References brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_entry_t::cache_policy, brix_vfs_backend_entry_t::cache_tier, brix_tier_cfg_t::configured, and brix_vfs_backend_entry_t::inst.
Referenced by brix_tier_register_cache_store().
brix_vfs_backend_config_stage_store()
void brix_vfs_backend_config_stage_store (const char * root_canon, const brix_tier_cfg_t * cfg, const brix_stage_policy_t * policy)
Definition at line 322 of file vfs_backend_config.c.
References brix_vfs_backend_entry_get_or_create(), brix_tier_cfg_t::configured, brix_vfs_backend_entry_t::inst, brix_vfs_backend_entry_t::stage_policy, and brix_vfs_backend_entry_t::stage_tier.
Referenced by brix_tier_register_stores().