nginx-xrootd: src/fs/tier/tier_build.c File Reference
tier_build.c File Reference
#include "tier.h"
#include "fs/backend/xroot/sd_xroot.h"
#include "fs/backend/http/sd_http.h"
#include "fs/backend/remote/sd_remote.h"
#include "fs/backend/cache/sd_cache.h"
#include "fs/backend/stage/sd_stage.h"
#include "fs/backend/frm/sd_frm.h"
#include "fs/backend/rados/sd_ceph.h"
#include "fs/cache/origin/s3_transport.h"
#include "core/compat/cstr.h"
#include <string.h>
Functions
static void tier_resolve_creds (const brix_tier_cfg_t *t, char *bearer, size_t bcap, char *proxy, size_t pcap, char *key, size_t kcap, char *cadir, size_t ccap, ngx_log_t *log)
static brix_sd_instance_t * tier_needs_dev (ngx_log_t *log, const char *driver, const char *sp)
static brix_sd_instance_t * tier_build_posix (const brix_tier_cfg_t *t, ngx_log_t *log)
static brix_sd_instance_t * tier_build_pblock (const brix_tier_cfg_t *t, ngx_log_t *log)
static brix_sd_instance_t * tier_build_xroot (const brix_tier_cfg_t *t, ngx_log_t *log)
static brix_sd_instance_t * tier_build_http (const brix_tier_cfg_t *t, ngx_log_t *log)
static brix_sd_instance_t * tier_build_s3 (const brix_tier_cfg_t *t, ngx_log_t *log)
static brix_sd_instance_t * tier_build_ceph (const brix_tier_cfg_t *t, ngx_log_t *log)
static brix_sd_instance_t * tier_build_tape (const brix_tier_cfg_t *t, ngx_log_t *log)
brix_sd_instance_t * brix_tier_build (const brix_tier_cfg_t *t, ngx_log_t *log)
static brix_sd_instance_t * tier_compose_stage (brix_tier_stack_t *s, brix_sd_instance_t *top, ngx_log_t *log)
static brix_sd_instance_t * tier_compose_cache (brix_tier_stack_t *s, brix_sd_instance_t *top, ngx_log_t *log)
brix_sd_instance_t * brix_tier_build_stack (brix_tier_stack_t *s, ngx_log_t *log)
Function Documentation
brix_tier_build()
brix_sd_instance_t * brix_tier_build (const brix_tier_cfg_t * t, ngx_log_t * log)
Definition at line 238 of file tier_build.c.
References brix_tier_cfg_t::configured, brix_tier_cfg_t::driver, log, tier_build_ceph(), tier_build_http(), tier_build_pblock(), tier_build_posix(), tier_build_s3(), tier_build_tape(), and tier_build_xroot().
Referenced by brix_tier_build_stack(), brix_vbr_wrap_cache_tier(), brix_vbr_wrap_stage_tier(), tier_compose_cache(), and tier_compose_stage().
brix_tier_build_stack()
brix_sd_instance_t * brix_tier_build_stack (brix_tier_stack_t * s, ngx_log_t * log)
Definition at line 335 of file tier_build.c.
References brix_tier_build(), log, s, tier_compose_cache(), and tier_compose_stage().
tier_build_ceph()
static brix_sd_instance_t * tier_build_ceph (const brix_tier_cfg_t * t, ngx_log_t * log) static
Definition at line 206 of file tier_build.c.
References brix_sd_instance_create(), brix_tier_cfg_t::host, log, brix_tier_cfg_t::path, and tier_needs_dev().
Referenced by brix_tier_build().
tier_build_http()
static brix_sd_instance_t * tier_build_http (const brix_tier_cfg_t * t, ngx_log_t * log) static
Definition at line 150 of file tier_build.c.
References brix_sd_http_cfg_t::base_path, brix_sd_http_cfg_t::bearer_token, brix_s3_origin_curl_transport, brix_sd_http_create(), BRIX_SD_HTTP_DEFAULT_TIMEOUT_MS, brix_sd_http_cfg_t::ca_path, brix_sd_http_cfg_t::host, brix_tier_cfg_t::host, key, log, brix_tier_cfg_t::path, brix_sd_http_cfg_t::port, brix_tier_cfg_t::port, tier_resolve_creds(), brix_sd_http_cfg_t::timeout_ms, brix_sd_http_cfg_t::tls, brix_tier_cfg_t::tls, and brix_sd_http_cfg_t::transport.
Referenced by brix_tier_build().
tier_build_pblock()
static brix_sd_instance_t * tier_build_pblock (const brix_tier_cfg_t * t, ngx_log_t * log) static
Definition at line 100 of file tier_build.c.
References brix_tier_cfg_t::block_size, brix_sd_instance_create(), log, brix_tier_cfg_t::path, and tier_needs_dev().
Referenced by brix_tier_build().
tier_build_posix()
static brix_sd_instance_t * tier_build_posix (const brix_tier_cfg_t * t, ngx_log_t * log) static
Definition at line 88 of file tier_build.c.
References brix_sd_instance_create(), log, and brix_tier_cfg_t::path.
Referenced by brix_tier_build().
tier_build_s3()
static brix_sd_instance_t * tier_build_s3 (const brix_tier_cfg_t * t, ngx_log_t * log) static
Definition at line 179 of file tier_build.c.
References brix_s3_origin_curl_transport, BRIX_SD_HTTP_DEFAULT_TIMEOUT_MS, brix_sd_remote_create(), BRIX_SD_REMOTE_S3, brix_sd_remote_cfg_t::bucket, brix_sd_remote_cfg_t::host, brix_tier_cfg_t::host, log, brix_tier_cfg_t::path, brix_sd_remote_cfg_t::port, brix_tier_cfg_t::port, brix_sd_remote_cfg_t::scheme, brix_sd_remote_cfg_t::timeout_ms, brix_sd_remote_cfg_t::tls, brix_tier_cfg_t::tls, and brix_sd_remote_cfg_t::transport.
Referenced by brix_tier_build().
tier_build_tape()
static brix_sd_instance_t * tier_build_tape (const brix_tier_cfg_t * t, ngx_log_t * log) static
Definition at line 232 of file tier_build.c.
References brix_sd_frm_create(), brix_tier_cfg_t::host, log, and brix_tier_cfg_t::path.
Referenced by brix_tier_build().
tier_build_xroot()
static brix_sd_instance_t * tier_build_xroot (const brix_tier_cfg_t * t, ngx_log_t * log) static
Definition at line 122 of file tier_build.c.
References BRIX_AF_AUTO, brix_sd_xroot_create_origin(), brix_sd_xroot_origin_cfg_t::host, brix_tier_cfg_t::host, key, log, brix_tier_cfg_t::port, tier_resolve_creds(), and brix_tier_cfg_t::tls.
Referenced by brix_tier_build().
tier_compose_cache()
static brix_sd_instance_t * tier_compose_cache (brix_tier_stack_t * s, brix_sd_instance_t * top, ngx_log_t * log) static
Definition at line 309 of file tier_build.c.
References brix_sd_cache_create(), brix_tier_build(), log, and s.
Referenced by brix_tier_build_stack().
tier_compose_stage()
static brix_sd_instance_t * tier_compose_stage (brix_tier_stack_t * s, brix_sd_instance_t * top, ngx_log_t * log) static
Definition at line 281 of file tier_build.c.
References brix_sd_stage_create(), brix_tier_build(), log, and s.
Referenced by brix_tier_build_stack().
tier_needs_dev()
static brix_sd_instance_t * tier_needs_dev (ngx_log_t * log, const char * driver, const char * sp) static
Definition at line 73 of file tier_build.c.
References driver, and log.
Referenced by tier_build_ceph(), and tier_build_pblock().
tier_resolve_creds()
static void tier_resolve_creds (const brix_tier_cfg_t * t, char * bearer, size_t bcap, char * proxy, size_t pcap, char * key, size_t kcap, char * cadir, size_t ccap, ngx_log_t * log) static
Definition at line 38 of file tier_build.c.
References brix_credential_bearer(), brix_str_cbuf(), c, brix_tier_cfg_t::credential, key, and log.
Referenced by tier_build_http(), and tier_build_xroot().