nginx-xrootd: src/core/compat/tmp_path.c File Reference
tmp_path.c File Reference
#include "tmp_path.h"
#include "crypto.h"
#include "hex.h"
#include <ftw.h>
#include <limits.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Macros
#define BRIX_TMP_REAP_MAX 64
Functions
ngx_int_t brix_make_tmp_path (const char *base_path, char *out, size_t out_sz)
ngx_int_t brix_make_resume_path (const char *base_path, const char *principal, const char *stage_dir, char *out, size_t out_sz)
void brix_tmp_reap_register (const char *export_root)
static int brix_tmp_reap_cb (const char *fpath, const struct stat *sb, int typeflag, struct FTW *ftwbuf)
ngx_uint_t brix_tmp_reap_all (ngx_log_t *log)
Variables
static char s_tmp_reap_roots [64][PATH_MAX]
static ngx_uint_t s_tmp_reap_count
static ngx_uint_t s_tmp_reaped
Macro Definition Documentation
BRIX_TMP_REAP_MAX
#define BRIX_TMP_REAP_MAX 64
Definition at line 141 of file tmp_path.c.
Function Documentation
brix_make_resume_path()
ngx_int_t brix_make_resume_path (const char * base_path, const char * principal, const char * stage_dir, char * out, size_t out_sz)
Definition at line 88 of file tmp_path.c.
References brix_hex_encode(), brix_sha256(), ngx_memcpy, and PATH_MAX.
Referenced by brix_open_build_stage_temp(), and brix_staged_open_resume().
brix_make_tmp_path()
ngx_int_t brix_make_tmp_path (const char * base_path, char * out, size_t out_sz)
Definition at line 44 of file tmp_path.c.
Referenced by brix_commit_staged(), brix_open_build_stage_temp(), brix_staged_open(), and webdav_copy_collection_execute().
brix_tmp_reap_all()
ngx_uint_t brix_tmp_reap_all (ngx_log_t * log)
Definition at line 213 of file tmp_path.c.
References brix_tmp_reap_cb(), log, s_tmp_reap_count, s_tmp_reap_roots, and s_tmp_reaped.
Referenced by ngx_stream_brix_init_process().
brix_tmp_reap_cb()
static int brix_tmp_reap_cb (const char * fpath, const struct stat * sb, int typeflag, struct FTW * ftwbuf) static
Definition at line 179 of file tmp_path.c.
References s_tmp_reaped.
Referenced by brix_tmp_reap_all().
brix_tmp_reap_register()
void brix_tmp_reap_register (const char * export_root)
Definition at line 147 of file tmp_path.c.
References BRIX_TMP_REAP_MAX, export_root, PATH_MAX, s_tmp_reap_count, and s_tmp_reap_roots.
Referenced by brix_config_prepare_server(), ngx_http_brix_webdav_merge_loc_conf(), and ngx_http_s3_merge_loc_conf().
Variable Documentation
s_tmp_reap_count
ngx_uint_t s_tmp_reap_count static
Definition at line 143 of file tmp_path.c.
Referenced by brix_tmp_reap_all(), and brix_tmp_reap_register().
s_tmp_reap_roots
char s_tmp_reap_roots[64][PATH_MAX] static
Definition at line 142 of file tmp_path.c.
Referenced by brix_tmp_reap_all(), and brix_tmp_reap_register().
s_tmp_reaped
ngx_uint_t s_tmp_reaped static
Definition at line 144 of file tmp_path.c.
Referenced by brix_tmp_reap_all(), and brix_tmp_reap_cb().