nginx-xrootd: src/auth/token/token.h File Reference
token.h File Reference
#include <openssl/evp.h>
#include <limits.h>
Data Structures
struct brix_jwks_key_t
struct brix_token_scope_t
struct brix_token_claims_t
Macros
#define BRIX_MAX_JWKS_KEYS 8
#define BRIX_MAX_TOKEN_SCOPES 8
#define BRIX_SCOPE_PATH_MAX 256
#define BRIX_TOKEN_SCOPE_T_DEFINED
Enumerations
enum brix_token_op_e { BRIX_TOKEN_OP_READ = 0 , BRIX_TOKEN_OP_WRITE = 1 , BRIX_TOKEN_OP_OTHER = 2 }
Functions
int brix_jwks_load (ngx_log_t *log, const char *path, brix_jwks_key_t *keys, int max_keys)
void brix_jwks_free (brix_jwks_key_t *keys, int count)
ngx_int_t brix_jwks_register_cleanup (ngx_pool_t *pool, brix_jwks_key_t *keys, int *count)
int brix_token_peek_iss (const char *token, size_t token_len, char *out, size_t outsz)
int brix_token_validate (ngx_log_t *log, const char *token, size_t token_len, const brix_jwks_key_t *keys, int key_count, const char *expected_issuer, const char *expected_audience, const u_char *macaroon_secret, size_t secret_len, int clock_skew, brix_token_claims_t *claims)
int brix_token_parse_scopes (const char *scope_str, brix_token_scope_t *scopes, int max_scopes)
int brix_token_scope_path_matches (const char *scope_path, const char *request_path)
int brix_token_check_read (const brix_token_scope_t *scopes, int scope_count, const char *path)
int brix_token_check_write (const brix_token_scope_t *scopes, int scope_count, const char *path)
Macro Definition Documentation
BRIX_MAX_JWKS_KEYS
#define BRIX_MAX_JWKS_KEYS 8
Definition at line 20 of file token.h.
BRIX_MAX_TOKEN_SCOPES
#define BRIX_MAX_TOKEN_SCOPES 8
Definition at line 28 of file token.h.
BRIX_SCOPE_PATH_MAX
#define BRIX_SCOPE_PATH_MAX 256
Definition at line 37 of file token.h.
BRIX_TOKEN_SCOPE_T_DEFINED
#define BRIX_TOKEN_SCOPE_T_DEFINED
Definition at line 51 of file token.h.
Enumeration Type Documentation
brix_token_op_e
enum brix_token_op_e
Enumerator
BRIX_TOKEN_OP_READ
BRIX_TOKEN_OP_WRITE
BRIX_TOKEN_OP_OTHER
Definition at line 105 of file token.h.
Function Documentation
brix_jwks_free()
void brix_jwks_free (brix_jwks_key_t * keys, int count)
Definition at line 245 of file jwks.c.
References brix_jwks_key_t::pkey.
Referenced by brix_jwks_pool_cleanup(), and brix_token_jwks_try_reload().
brix_jwks_load()
int brix_jwks_load (ngx_log_t * log, const char * path, brix_jwks_key_t * keys, int max_keys)
Definition at line 138 of file jwks.c.
References BRIX_DIAG_ERR, brix_jwks_load_jansson(), brix_size_add(), and log.
Referenced by brix_configure_token_auth(), brix_token_jwks_try_reload(), brix_token_registry_load(), ngx_http_brix_webdav_merge_loc_conf(), and ngx_http_s3_merge_loc_conf().
brix_jwks_register_cleanup()
ngx_int_t brix_jwks_register_cleanup (ngx_pool_t * pool, brix_jwks_key_t * keys, int * count)
Definition at line 225 of file jwks.c.
References brix_jwks_pool_cleanup(), and c.
Referenced by brix_configure_token_auth(), brix_token_registry_build(), ngx_http_brix_webdav_merge_loc_conf(), and ngx_http_s3_merge_loc_conf().
brix_token_check_read()
int brix_token_check_read (const brix_token_scope_t * scopes, int scope_count, const char * path)
Definition at line 238 of file scopes.c.
References brix_token_scope_path_matches(), and read().
Referenced by brix_check_token_scope(), brix_identity_check_token_scope(), brix_token_authz_strategy(), webdav_check_token_scope(), webdav_handle_macaroon_request(), and webdav_handle_macaroon_token().
brix_token_check_write()
int brix_token_check_write (const brix_token_scope_t * scopes, int scope_count, const char * path)
Definition at line 265 of file scopes.c.
References brix_token_scope_path_matches().
Referenced by brix_check_token_scope(), brix_identity_check_token_scope(), brix_token_authz_strategy(), webdav_check_token_scope(), webdav_handle_macaroon_request(), and webdav_handle_macaroon_token().
brix_token_parse_scopes()
int brix_token_parse_scopes (const char * scope_str, brix_token_scope_t * scopes, int max_scopes)
Definition at line 126 of file scopes.c.
References token_scope_copy_path(), token_scope_end(), token_scope_set_permission(), and token_scope_skip_spaces().
Referenced by brix_token_meta_get(), brix_token_validate(), macaroon_parse_core(), and macaroon_rebuild_scope_raw().
brix_token_peek_iss()
int brix_token_peek_iss (const char * token, size_t token_len, char * out, size_t outsz)
Definition at line 486 of file validate.c.
References b64url_decode(), json_get_string(), and xrdjwt_split().
Referenced by brix_token_validate_registry_authn().
brix_token_scope_path_matches()
int brix_token_scope_path_matches (const char * scope_path, const char * request_path)
Definition at line 206 of file scopes.c.
Referenced by brix_token_check_read(), brix_token_check_write(), and brix_token_issuer_path_ok().
brix_token_validate()
int brix_token_validate (ngx_log_t * log, const char * token, size_t token_len, const brix_jwks_key_t * keys, int key_count, const char * expected_issuer, const char * expected_audience, const u_char * macaroon_secret, size_t secret_len, int clock_skew, brix_token_claims_t * claims)
Definition at line 190 of file validate.c.
References brix_token_claims_t::aud, b64url_decode(), brix_macaroon_validate(), BRIX_MAX_TOKEN_SCOPES, brix_token_extract_groups(), brix_token_is_macaroon(), brix_token_malformed(), brix_token_parse_scopes(), brix_token_claims_t::exp, brix_token_claims_t::groups, brix_token_claims_t::iat, brix_token_claims_t::iss, json_get_int64(), json_get_string(), json_get_string_array(), json_has_member(), json_string_or_array_contains(), log, xrdjwt_seg::n, brix_token_claims_t::nbf, brix_jwks_key_t::pkey, brix_token_claims_t::scope_count, brix_token_claims_t::scope_raw, brix_token_claims_t::scopes, brix_token_claims_t::sub, token_sanitize_for_log(), token_sig_ok(), and xrdjwt_split().
Referenced by brix_handle_token_auth(), brix_token_validate_registry_authn(), s3_verify_bearer(), and webdav_verify_bearer_token().