nginx-xrootd: src/auth/token/token_cache.h File Reference
token_cache.h File Reference
#include "core/shm/kv.h"
#include "token.h"
Functions
int brix_token_cache_lookup (brix_kv_t *kv, const char *token, size_t token_len, brix_token_claims_t *claims)
void brix_token_cache_store (brix_kv_t *kv, const char *token, size_t token_len, const brix_token_claims_t *claims)
char * brix_token_cache_directive (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Function Documentation
brix_token_cache_directive()
char * brix_token_cache_directive (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 78 of file token_cache.c.
References brix_kv_find().
brix_token_cache_lookup()
int brix_token_cache_lookup (brix_kv_t * kv, const char * token, size_t token_len, brix_token_claims_t * claims)
Definition at line 19 of file token_cache.c.
References brix_kv_get(), brix_sha256(), and brix_token_claims_t::exp.
Referenced by tokenauth_verify_or_cache(), and wt_check_issuer_keys().
brix_token_cache_store()
void brix_token_cache_store (brix_kv_t * kv, const char * token, size_t token_len, const brix_token_claims_t * claims)
Definition at line 45 of file token_cache.c.
References brix_kv_set(), brix_sha256(), BRIX_TOKEN_CACHE_MAX_TTL_MS, and brix_token_claims_t::exp.
Referenced by tokenauth_validate(), and webdav_verify_bearer_token().