nginx-xrootd: src/auth/gsi/token.c File Reference
token.c File Reference
#include "gsi_internal.h"
#include "protocols/root/session/registry.h"
#include "auth/token/macaroon.h"
#include "auth/token/token_cache.h"
#include "auth/token/worker_cache.h"
#include "auth/token/issuer_registry.h"
Data Structures
struct tokenauth_state_t
Functions
static int tokenauth_slice_token (const u_char *payload, size_t dlen, const char **token, size_t *token_len)
static ngx_int_t tokenauth_extract (brix_ctx_t *ctx, ngx_connection_t *c, tokenauth_state_t *st, ngx_int_t *out)
static void tokenauth_fill_va (brix_token_validate_args_t *va, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, tokenauth_state_t *st)
static int tokenauth_verify_or_cache (ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, tokenauth_state_t *st, int via_registry, int *cache_hit)
static int tokenauth_grace_retry (ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, tokenauth_state_t *st, int prev_rc)
static int tokenauth_validate (ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, tokenauth_state_t *st)
static ngx_int_t tokenauth_map_identity (brix_ctx_t *ctx, ngx_connection_t *c, tokenauth_state_t *st, ngx_int_t *out)
static void tokenauth_bind_session (brix_ctx_t *ctx, ngx_connection_t *c, tokenauth_state_t *st)
ngx_int_t brix_handle_token_auth (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
Function Documentation
brix_handle_token_auth()
ngx_int_t brix_handle_token_auth (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 521 of file token.c.
References brix_log_access(), BRIX_OP_AUTH, BRIX_OP_ERR, BRIX_RETURN_OK, brix_send_error(), c, tokenauth_state_t::claims, kXR_NotAuthorized, brix_token_claims_t::sub, tokenauth_bind_session(), tokenauth_extract(), tokenauth_map_identity(), and tokenauth_validate().
tokenauth_bind_session()
static void tokenauth_bind_session (brix_ctx_t * ctx, ngx_connection_t * c, tokenauth_state_t * st) static
Definition at line 462 of file token.c.
References BRIX_ATOMIC_INC, BRIX_MAX_TOKEN_SCOPES, brix_metrics_shared(), brix_session_register(), brix_track_unique_user(), brix_track_vo_activity(), BRIX_VO_MAX_TRACKED, BRIX_VO_NAME_LEN, c, tokenauth_state_t::claims, brix_ctx_login_t::dn, brix_token_claims_t::groups, brix_ctx_t::login, ngx_brix_vo_slot_t::name, brix_ctx_login_t::primary_vo, ngx_brix_vo_slot_t::requests_total, brix_token_claims_t::scope_count, brix_ctx_token_t::scope_count, brix_token_claims_t::scopes, brix_ctx_token_t::scopes, brix_ctx_login_t::sessid, ngx_brix_vo_global_t::slots, brix_token_claims_t::sub, brix_ctx_t::token, ngx_brix_metrics_t::vo_global, and brix_ctx_login_t::vo_list.
Referenced by brix_handle_token_auth().
tokenauth_extract()
static ngx_int_t tokenauth_extract (brix_ctx_t * ctx, ngx_connection_t * c, tokenauth_state_t * st, ngx_int_t * out) static
Definition at line 129 of file token.c.
References brix_log_access(), BRIX_OP_AUTH, BRIX_OP_ERR, brix_send_error(), c, brix_ctx_recv_t::cur_dlen, kXR_NotAuthorized, brix_ctx_recv_t::payload, brix_ctx_t::recv, tokenauth_state_t::token, tokenauth_state_t::token_len, and tokenauth_slice_token().
Referenced by brix_handle_token_auth().
tokenauth_fill_va()
static void tokenauth_fill_va (brix_token_validate_args_t * va, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, tokenauth_state_t * st) static
Definition at line 175 of file token.c.
References c, tokenauth_state_t::claims, brix_token_validate_args_t::claims, brix_token_validate_args_t::clock_skew, brix_token_validate_args_t::expected_audience, brix_token_validate_args_t::expected_issuer, brix_token_validate_args_t::key_count, brix_token_validate_args_t::keys, brix_token_validate_args_t::log, brix_token_validate_args_t::macaroon_secret, tokenauth_state_t::secret, tokenauth_state_t::secret_len, brix_token_validate_args_t::secret_len, tokenauth_state_t::token, brix_token_validate_args_t::token, tokenauth_state_t::token_len, and brix_token_validate_args_t::token_len.
Referenced by tokenauth_grace_retry(), and tokenauth_verify_or_cache().
tokenauth_grace_retry()
static int tokenauth_grace_retry (ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, tokenauth_state_t * st, int prev_rc) static
Definition at line 281 of file token.c.
References brix_macaroon_secret_parse(), brix_token_validate(), c, tokenauth_state_t::secret, tokenauth_state_t::secret_len, and tokenauth_fill_va().
Referenced by tokenauth_validate().
tokenauth_map_identity()
static ngx_int_t tokenauth_map_identity (brix_ctx_t * ctx, ngx_connection_t * c, tokenauth_state_t * st, ngx_int_t * out) static
Definition at line 394 of file token.c.
References brix_ctx_token_t::auth, brix_ctx_login_t::auth_done, brix_ctx_t::bearer_token, brix_identity_set_token_claims(), brix_send_error(), c, tokenauth_state_t::claims, brix_ctx_login_t::dn, brix_token_claims_t::groups, brix_ctx_t::identity, kXR_NoMemory, brix_ctx_t::login, ngx_memcpy, brix_ctx_login_t::primary_vo, tokenauth_state_t::reg_issuer, brix_token_claims_t::sub, tokenauth_state_t::token, brix_ctx_t::token, brix_identity_t::token_issuer, tokenauth_state_t::token_len, and brix_ctx_login_t::vo_list.
Referenced by brix_handle_token_auth().
tokenauth_slice_token()
static int tokenauth_slice_token (const u_char * payload, size_t dlen, const char ** token, size_t * token_len) static
Definition at line 72 of file token.c.
References tok.
Referenced by tokenauth_extract().
tokenauth_validate()
static int tokenauth_validate (ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, tokenauth_state_t * st) static
Definition at line 331 of file token.c.
References brix_macaroon_secret_parse(), brix_token_cache_store(), brix_token_l1_store(), c, tokenauth_state_t::claims, tokenauth_state_t::secret, tokenauth_state_t::secret_len, tokenauth_state_t::token, tokenauth_state_t::token_len, tokenauth_grace_retry(), and tokenauth_verify_or_cache().
Referenced by brix_handle_token_auth().
tokenauth_verify_or_cache()
static int tokenauth_verify_or_cache (ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, tokenauth_state_t * st, int via_registry, int * cache_hit) static
Definition at line 208 of file token.c.
References brix_token_cache_lookup(), brix_token_l1_create(), brix_token_l1_lookup(), BRIX_TOKEN_L1_SLOTS, brix_token_l1_store(), brix_token_validate(), brix_token_validate_registry_authn(), c, tokenauth_state_t::claims, brix_token_registry_args_t::claims, brix_token_registry_args_t::clock_skew, brix_token_registry_args_t::log, brix_token_registry_args_t::macaroon_secret, brix_token_registry_args_t::reg, tokenauth_state_t::reg_issuer, tokenauth_state_t::secret, tokenauth_state_t::secret_len, brix_token_registry_args_t::secret_len, tokenauth_state_t::token, brix_token_registry_args_t::token, tokenauth_state_t::token_len, brix_token_registry_args_t::token_len, and tokenauth_fill_va().
Referenced by tokenauth_validate().