nginx-xrootd: src/auth/token/token_internal.h File Reference
token_internal.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <openssl/evp.h>
#include "token.h"
Functions
EVP_PKEY * brix_token_rsa_pubkey_from_ne (const char *n_b64, size_t n_b64_len, const char *e_b64, size_t e_b64_len, ngx_log_t *log)
EVP_PKEY * brix_token_ec_pubkey_from_xy (const char *x_b64, size_t x_b64_len, const char *y_b64, size_t y_b64_len, ngx_log_t *log)
int brix_token_verify_rs256 (const u_char *signed_data, size_t signed_len, const u_char *sig, size_t sig_len, EVP_PKEY *pkey)
int brix_token_verify_es256 (const u_char *signed_data, size_t signed_len, const u_char *sig_p1363, size_t sig_len, EVP_PKEY *pkey)
Function Documentation
brix_token_ec_pubkey_from_xy()
EVP_PKEY * brix_token_ec_pubkey_from_xy (const char * x_b64, size_t x_b64_len, const char * y_b64, size_t y_b64_len, ngx_log_t * log)
Definition at line 91 of file keys.c.
References b64url_decode(), and log.
Referenced by brix_jwks_load_jansson().
brix_token_rsa_pubkey_from_ne()
EVP_PKEY * brix_token_rsa_pubkey_from_ne (const char * n_b64, size_t n_b64_len, const char * e_b64, size_t e_b64_len, ngx_log_t * log)
Definition at line 31 of file keys.c.
References b64url_decode(), and log.
Referenced by brix_jwks_load_jansson().
brix_token_verify_es256()
int brix_token_verify_es256 (const u_char * signed_data, size_t signed_len, const u_char * sig_p1363, size_t sig_len, EVP_PKEY * pkey)
Definition at line 43 of file signature.c.
References s.
Referenced by token_sig_ok().
brix_token_verify_rs256()
int brix_token_verify_rs256 (const u_char * signed_data, size_t signed_len, const u_char * sig, size_t sig_len, EVP_PKEY * pkey)
Definition at line 12 of file signature.c.
Referenced by token_sig_ok().