nginx-xrootd: src/protocols/webdav/tpc_internal_split.h File Reference
tpc_internal_split.h File Reference
#include "webdav.h"
#include "core/compat/staged_file.h"
#include <sys/stat.h>
Data Structures
struct webdav_tpc_pull_ctx_t
Functions
const char * webdav_dashboard_identity (ngx_http_request_t *r)
void webdav_tpc_note_client_copy_xfer (ngx_http_request_t *r, off_t bytes, int64_t expected)
ngx_int_t webdav_tpc_authorize (ngx_http_request_t *r, const ngx_str_t *src_path, const ngx_str_t *dst_path)
uint64_t webdav_tpc_register_transfer (ngx_http_request_t *r, ngx_uint_t direction, const char *src, const char *dst, off_t bytes_total)
ngx_int_t webdav_tpc_extract_subject_token (ngx_http_request_t *r, ngx_table_elt_t *auth_hdr, const char **subject_token)
ngx_int_t webdav_tpc_add_bearer_header (ngx_http_request_t *r, ngx_array_t *headers, ngx_str_t *delegated_token)
ngx_int_t webdav_tpc_validate_copy_headers (ngx_table_elt_t *source_hdr, ngx_table_elt_t *dest_hdr)
ngx_uint_t webdav_tpc_parse_stream_count (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
ngx_int_t webdav_tpc_source_url (ngx_http_request_t *r, ngx_table_elt_t *source_hdr, char **source_url)
ngx_int_t webdav_tpc_parse_overwrite (ngx_http_request_t *r, ngx_flag_t *overwrite)
ngx_int_t webdav_tpc_apply_credential_delegation (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const char *source_url, ngx_array_t *transfer_headers)
ngx_int_t webdav_tpc_forward_user_bearer (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_array_t *transfer_headers)
ngx_int_t webdav_tpc_apply_user_proxy (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, webdav_tpc_pull_ctx_t *pl)
ngx_int_t webdav_tpc_handle_push (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_table_elt_t *dest_hdr)
ngx_int_t webdav_tpc_prepare_pull_target (webdav_tpc_pull_ctx_t *pl)
void webdav_tpc_pull_start_accounting (ngx_http_request_t *r, const char *path, const char *source_url)
ngx_int_t webdav_tpc_pull_execute (webdav_tpc_pull_ctx_t *pl)
Function Documentation
webdav_dashboard_identity()
const char * webdav_dashboard_identity (ngx_http_request_t * r)
Definition at line 47 of file tpc.c.
References ngx_http_brix_webdav_req_ctx_t::dn, and ngx_http_brix_webdav_module.
Referenced by webdav_tpc_handle_push(), and webdav_tpc_pull_start_accounting().
webdav_tpc_add_bearer_header()
ngx_int_t webdav_tpc_add_bearer_header (ngx_http_request_t * r, ngx_array_t * headers, ngx_str_t * delegated_token)
Definition at line 181 of file tpc.c.
References ngx_memcpy, and ngx_pnalloc().
Referenced by webdav_tpc_forward_user_bearer(), and webdav_tpc_push_apply_credential().
webdav_tpc_apply_credential_delegation()
ngx_int_t webdav_tpc_apply_credential_delegation (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const char * source_url, ngx_array_t * transfer_headers)
Definition at line 50 of file tpc_copy.c.
References BRIX_TPC_CRED_UNKNOWN, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_BAD_REQUEST, ngx_memcpy, ngx_pnalloc(), ngx_http_brix_tpc_conf_t::token_scope, ngx_http_brix_webdav_loc_conf_t::tpc_cred, webdav_tpc_cred_obtain_token(), webdav_tpc_cred_parse_mode(), webdav_tpc_extract_subject_token(), webdav_tpc_find_header, and webdav_tpc_header_value_equals.
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_apply_user_proxy()
ngx_int_t webdav_tpc_apply_user_proxy (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, webdav_tpc_pull_ctx_t * pl)
Definition at line 312 of file tpc_copy.c.
References BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_BAD_REQUEST, webdav_tpc_user_proxy_t::cert_path, webdav_tpc_user_proxy_t::deny, webdav_tpc_user_proxy_t::have, webdav_tpc_user_proxy_t::key_path, ngx_http_brix_webdav_loc_conf_t::tpc_credential_forward, webdav_tpc_pull_ctx_t::user_cert, webdav_tpc_pull_ctx_t::user_key, and webdav_tpc_user_proxy_resolve().
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_authorize()
ngx_int_t webdav_tpc_authorize (ngx_http_request_t * r, const ngx_str_t * src_path, const ngx_str_t * dst_path)
Definition at line 95 of file tpc.c.
References brix_tpc_check_authz(), BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_BAD_REQUEST, and webdav_tpc_request_identity().
Referenced by webdav_tpc_handle_push(), and webdav_tpc_prepare_pull_target().
webdav_tpc_extract_subject_token()
ngx_int_t webdav_tpc_extract_subject_token (ngx_http_request_t * r, ngx_table_elt_t * auth_hdr, const char ** subject_token)
Definition at line 152 of file tpc.c.
References brix_http_extract_bearer(), and webdav_tpc_pstrndup0().
Referenced by webdav_tpc_apply_credential_delegation(), and webdav_tpc_push_apply_credential().
webdav_tpc_forward_user_bearer()
ngx_int_t webdav_tpc_forward_user_bearer (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_array_t * transfer_headers)
Definition at line 260 of file tpc_copy.c.
References ngx_http_brix_webdav_req_ctx_t::bearer_token, ngx_http_brix_webdav_module, ngx_http_brix_webdav_loc_conf_t::tpc_credential_forward, webdav_tpc_add_bearer_header(), and webdav_tpc_transfer_headers_have_authorization().
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_handle_push()
ngx_int_t webdav_tpc_handle_push (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_table_elt_t * dest_hdr)
Definition at line 278 of file tpc_push.c.
References brix_dashboard_http_start_identity(), brix_dashboard_http_tpc_remote(), BRIX_TPC_DIR_PUSH, BRIX_TPC_METRIC_STARTED, brix_tpc_metric_transfer(), BRIX_TPC_PROTO_WEBDAV, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_PUSH_STARTED, BRIX_XFER_DIR_TPC, BRIX_XFER_PROTO_WEBDAV, webdav_tpc_push_ctx_t::conf, webdav_tpc_push_ctx_t::dest_url, webdav_tpc_push_ctx_t::expected_bytes, webdav_tpc_push_ctx_t::headers, webdav_tpc_push_ctx_t::path, webdav_tpc_push_ctx_t::r, stat(), webdav_dashboard_identity(), WEBDAV_MAX_PATH, webdav_resolve_stat(), webdav_tpc_authorize(), webdav_tpc_collect_transfer_headers(), webdav_tpc_push_apply_credential(), webdav_tpc_push_dest_url(), webdav_tpc_push_forward_overwrite(), webdav_tpc_push_post_thread(), and webdav_tpc_push_sync_exec().
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_note_client_copy_xfer()
void webdav_tpc_note_client_copy_xfer (ngx_http_request_t * r, off_t bytes, int64_t expected)
Definition at line 67 of file tpc.c.
References brix_sess_xfer_add(), brix_sess_xfer_t::bytes, brix_sess_xfer_t::expected, ngx_http_brix_webdav_module, ngx_http_brix_webdav_req_ctx_t::sess_xfer, and ngx_http_brix_webdav_req_ctx_t::sess_xfer_started.
Referenced by webdav_tpc_finish_pull_success(), webdav_tpc_pull_sync_exec(), webdav_tpc_push_sync_error(), and webdav_tpc_push_sync_exec().
webdav_tpc_parse_overwrite()
ngx_int_t webdav_tpc_parse_overwrite (ngx_http_request_t * r, ngx_flag_t * overwrite)
Definition at line 182 of file tpc_copy.c.
References BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_BAD_REQUEST, webdav_tpc_find_header, and webdav_tpc_header_value_equals.
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_parse_stream_count()
ngx_uint_t webdav_tpc_parse_stream_count (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 140 of file tpc_copy.c.
References ngx_http_brix_webdav_loc_conf_t::tpc_max_streams, and webdav_tpc_find_header.
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_prepare_pull_target()
ngx_int_t webdav_tpc_prepare_pull_target (webdav_tpc_pull_ctx_t * pl)
Definition at line 106 of file tpc_pull.c.
References brix_staged_open(), ngx_http_brix_webdav_loc_conf_t::common, webdav_tpc_pull_ctx_t::conf, webdav_tpc_pull_ctx_t::existed, brix_staged_file_t::fd, ngx_http_brix_webdav_resolve_path(), webdav_tpc_pull_ctx_t::overwrite, webdav_tpc_pull_ctx_t::path, webdav_tpc_pull_ctx_t::path_len, webdav_tpc_pull_ctx_t::r, brix_staged_open_req_t::root_canon, ngx_http_brix_shared_conf_t::root_canon, webdav_tpc_pull_ctx_t::sb, webdav_tpc_pull_ctx_t::source_url, webdav_tpc_pull_ctx_t::staged, stat(), webdav_tpc_authorize(), webdav_tpc_probe(), and webdav_tpc_url_path().
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_pull_execute()
ngx_int_t webdav_tpc_pull_execute (webdav_tpc_pull_ctx_t * pl)
Definition at line 396 of file tpc_pull.c.
References webdav_tpc_commit_pulled_file(), webdav_tpc_finish_pull_success(), webdav_tpc_pull_marker_exec(), webdav_tpc_pull_sync_exec(), and webdav_tpc_pull_thread_exec().
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_pull_start_accounting()
void webdav_tpc_pull_start_accounting (ngx_http_request_t * r, const char * path, const char * source_url)
Definition at line 160 of file tpc_pull.c.
References brix_dashboard_http_start_identity(), brix_dashboard_http_tpc_remote(), BRIX_TPC_DIR_PULL, BRIX_TPC_METRIC_STARTED, brix_tpc_metric_transfer(), BRIX_TPC_PROTO_WEBDAV, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_PULL_STARTED, BRIX_XFER_DIR_TPC, BRIX_XFER_PROTO_WEBDAV, and webdav_dashboard_identity().
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_register_transfer()
uint64_t webdav_tpc_register_transfer (ngx_http_request_t * r, ngx_uint_t direction, const char * src, const char * dst, off_t bytes_total)
Definition at line 116 of file tpc.c.
References BRIX_TPC_PROTO_WEBDAV, brix_tpc_registry_add(), BRIX_TPC_STATE_PENDING, brix_tpc_transfer_t::bytes_total, brix_tpc_transfer_t::direction, brix_tpc_transfer_t::dst_path, brix_tpc_transfer_t::protocol, brix_tpc_transfer_t::src_url, and brix_tpc_transfer_t::state.
Referenced by webdav_tpc_pull_marker_exec(), webdav_tpc_pull_sync_exec(), and webdav_tpc_push_sync_exec().
webdav_tpc_source_url()
ngx_int_t webdav_tpc_source_url (ngx_http_request_t * r, ngx_table_elt_t * source_hdr, char ** source_url)
Definition at line 161 of file tpc_copy.c.
References BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_BAD_REQUEST, webdav_tpc_pstrndup0(), and webdav_tpc_str_has_ctl.
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_validate_copy_headers()
ngx_int_t webdav_tpc_validate_copy_headers (ngx_table_elt_t * source_hdr, ngx_table_elt_t * dest_hdr)
Definition at line 127 of file tpc_copy.c.
References BRIX_WEBDAV_METRIC_INC, and BRIX_WEBDAV_TPC_BAD_REQUEST.
Referenced by ngx_http_brix_webdav_tpc_handle_copy().