nginx-xrootd: src/protocols/webdav/tpc_marker.c File Reference
tpc_marker.c File Reference
#include "webdav.h"
#include "core/compat/net_target.h"
#include "core/compat/staged_file.h"
#include "observability/dashboard/dashboard_tracking.h"
#include "core/aio/aio.h"
#include "tpc/common/metrics.h"
#include "tpc/common/registry.h"
#include <fcntl.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct tpc_marker_ctx_t
struct tpc_marker_thread_ctx_t
Macros
#define TPC_MARKER_POLL_MSEC 200u
Functions
static void tpc_marker_send_one (ngx_http_request_t *r, time_t ts, ngx_uint_t stripe_index, off_t bytes, ngx_uint_t total_stripes)
static void tpc_marker_send_all (ngx_http_request_t *r, time_t ts, tpc_marker_ctx_t *ctx)
static void tpc_marker_finish (ngx_http_request_t *r, tpc_marker_ctx_t *ctx, int failed)
static void tpc_marker_poll (ngx_event_t *ev)
static void tpc_marker_thread_done (ngx_event_t *ev)
static void tpc_marker_cleanup (void *data)
static void tpc_marker_thread_func (void *data, ngx_log_t *log)
ngx_int_t webdav_tpc_marker_start (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_uint_t n_streams, const char *url, const char *tmp_path, const char *final_path, ngx_flag_t is_pull, ngx_flag_t overwrite, ngx_flag_t existed, ngx_array_t *transfer_headers, uint64_t transfer_id)
Macro Definition Documentation
TPC_MARKER_POLL_MSEC
#define TPC_MARKER_POLL_MSEC 200u
Definition at line 48 of file tpc_marker.c.
Function Documentation
tpc_marker_cleanup()
static void tpc_marker_cleanup (void * data) static
Definition at line 317 of file tpc_marker.c.
References brix_tpc_registry_request_cancel(), tpc_marker_ctx_t::is_pull, tpc_marker_ctx_t::timer, tpc_marker_ctx_t::tmp_path, and tpc_marker_ctx_t::transfer_id.
Referenced by webdav_tpc_marker_start().
tpc_marker_finish()
static void tpc_marker_finish (ngx_http_request_t * r, tpc_marker_ctx_t * ctx, int failed) static
Definition at line 150 of file tpc_marker.c.
References brix_dashboard_http_add(), brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_link_confined_canon(), brix_rename_confined_canon(), BRIX_TPC_DIR_PULL, BRIX_TPC_DIR_PUSH, BRIX_TPC_METRIC_ERROR, BRIX_TPC_METRIC_SUCCESS, brix_tpc_metric_transfer(), brix_tpc_progress_emit(), BRIX_TPC_PROTO_WEBDAV, brix_tpc_registry_remove(), BRIX_TPC_STATE_DONE, BRIX_TPC_STATE_ERROR, brix_unlink_confined_canon(), BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_COMMIT_ERROR, BRIX_WEBDAV_TPC_CURL_ERROR, BRIX_WEBDAV_TPC_CURL_SUCCESS, BRIX_WEBDAV_TPC_PULL_SUCCESS, BRIX_WEBDAV_TPC_PUSH_SUCCESS, tpc_marker_ctx_t::final_path, tpc_marker_ctx_t::is_pull, ngx_memcpy, tpc_marker_ctx_t::overwrite, tpc_marker_ctx_t::push_file_size, tpc_marker_ctx_t::root_canon, stat(), tpc_marker_ctx_t::tmp_path, tpc_marker_send_all(), and tpc_marker_ctx_t::transfer_id.
Referenced by tpc_marker_poll().
tpc_marker_poll()
static void tpc_marker_poll (ngx_event_t * ev) static
Definition at line 269 of file tpc_marker.c.
References tpc_ms_progress_t::completed, tpc_marker_ctx_t::last_marker_time, tpc_marker_ctx_t::marker_interval_secs, tpc_marker_ctx_t::progress, tpc_marker_ctx_t::r, tpc_ms_progress_t::result, tpc_marker_finish(), TPC_MARKER_POLL_MSEC, and tpc_marker_send_all().
Referenced by webdav_tpc_marker_start().
tpc_marker_send_all()
static void tpc_marker_send_all (ngx_http_request_t * r, time_t ts, tpc_marker_ctx_t * ctx) static
Definition at line 122 of file tpc_marker.c.
References tpc_ms_progress_t::bytes_per_stream, tpc_marker_ctx_t::is_pull, tpc_ms_progress_t::n_streams, tpc_marker_ctx_t::progress, stat(), tpc_marker_ctx_t::tmp_path, and tpc_marker_send_one().
Referenced by tpc_marker_finish(), tpc_marker_poll(), and webdav_tpc_marker_start().
tpc_marker_send_one()
static void tpc_marker_send_one (ngx_http_request_t * r, time_t ts, ngx_uint_t stripe_index, off_t bytes, ngx_uint_t total_stripes) static
Definition at line 87 of file tpc_marker.c.
References ngx_memcpy.
Referenced by tpc_marker_send_all().
tpc_marker_thread_done()
static void tpc_marker_thread_done (ngx_event_t * ev) static
Definition at line 304 of file tpc_marker.c.
References tpc_marker_thread_ctx_t::marker_ctx, and tpc_marker_ctx_t::timer.
Referenced by webdav_tpc_marker_start().
tpc_marker_thread_func()
static void tpc_marker_thread_func (void * data, ngx_log_t * log) static
Definition at line 345 of file tpc_marker.c.
References brix_net_target_policy_t::allow_local, brix_net_target_policy_t::allow_private, brix_net_target_policy_t::allow_root_scheme, brix_net_target_check_dns(), brix_net_target_parse(), tpc_ms_progress_t::completed, tpc_marker_thread_ctx_t::conf, brix_net_target_policy_t::default_https_port, tpc_marker_thread_ctx_t::is_push, tpc_marker_thread_ctx_t::local_path, log, tpc_marker_thread_ctx_t::log, tpc_marker_thread_ctx_t::marker_ctx, tpc_ms_progress_t::n_streams, tpc_marker_ctx_t::progress, brix_net_target_policy_t::require_https, tpc_ms_progress_t::result, ngx_http_brix_webdav_loc_conf_t::tpc_allow_local, ngx_http_brix_webdav_loc_conf_t::tpc_allow_private, tpc_marker_thread_ctx_t::transfer_headers, tpc_marker_thread_ctx_t::url, webdav_tpc_run_curl_pull(), webdav_tpc_run_curl_pull_multi(), and webdav_tpc_run_curl_push().
Referenced by webdav_tpc_marker_start().
webdav_tpc_marker_start()
ngx_int_t webdav_tpc_marker_start (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_uint_t n_streams, const char * url, const char * tmp_path, const char * final_path, ngx_flag_t is_pull, ngx_flag_t overwrite, ngx_flag_t existed, ngx_array_t * transfer_headers, uint64_t transfer_id)
Definition at line 416 of file tpc_marker.c.
References BRIX_TPC_MAX_STREAMS, ngx_http_brix_webdav_loc_conf_t::common, tpc_marker_thread_ctx_t::conf, tpc_marker_ctx_t::existed, tpc_marker_ctx_t::final_path, tpc_marker_ctx_t::is_pull, tpc_marker_thread_ctx_t::is_push, tpc_marker_ctx_t::last_marker_time, tpc_marker_thread_ctx_t::local_path, tpc_marker_thread_ctx_t::log, tpc_marker_thread_ctx_t::marker_ctx, tpc_marker_ctx_t::marker_interval_secs, tpc_ms_progress_t::n_streams, ngx_pcalloc(), ngx_pnalloc(), tpc_marker_ctx_t::overwrite, tpc_marker_ctx_t::progress, tpc_marker_ctx_t::push_file_size, tpc_marker_ctx_t::r, ngx_http_brix_shared_conf_t::root_canon, tpc_marker_ctx_t::root_canon, stat(), ngx_http_brix_shared_conf_t::thread_pool, tpc_marker_ctx_t::timer, tpc_marker_ctx_t::tmp_path, tpc_ms_progress_t::total_size, tpc_marker_cleanup(), ngx_http_brix_webdav_loc_conf_t::tpc_marker_interval, tpc_marker_poll(), TPC_MARKER_POLL_MSEC, tpc_marker_send_all(), tpc_marker_thread_done(), tpc_marker_thread_func(), tpc_marker_thread_ctx_t::transfer_headers, tpc_marker_ctx_t::transfer_id, and tpc_marker_thread_ctx_t::url.
Referenced by ngx_http_brix_webdav_tpc_handle_copy().