nginx-xrootd: src/protocols/webdav/tpc_curl_pmark.c File Reference
tpc_curl_pmark.c File Reference
#include "tpc_curl_internal.h"
Functions
curl_socket_t webdav_tpc_pmark_opensocket (void *clientp, curlsocktype purpose, struct curl_sockaddr *address)
int webdav_tpc_pmark_closesocket (void *clientp, curl_socket_t item)
void webdav_tpc_pmark_attach (CURL *curl, webdav_tpc_pmark_rec_t *rec, ngx_http_brix_webdav_loc_conf_t *conf, int is_push, const char *file_path, ngx_log_t *log)
size_t ms_write_cb (char *ptr, size_t size, size_t nmemb, void *userdata)
int webdav_tpc_curl_progress (void *clientp, curl_off_t dltotal, curl_off_t dlnow, curl_off_t ultotal, curl_off_t ulnow)
ngx_int_t webdav_tpc_curl_finish (ngx_int_t rc, CURL *curl, struct curl_slist *hdrs, struct curl_slist *resolve, FILE *fp)
Function Documentation
ms_write_cb()
size_t ms_write_cb (char * ptr, size_t size, size_t nmemb, void * userdata)
Definition at line 93 of file tpc_curl_pmark.c.
References brix_sd_posix_wrap(), tpc_ms_progress_t::bytes_per_stream, ms_stream_ctx_t::cur_offset, ms_stream_ctx_t::fd, ms_stream_ctx_t::progress, and ms_stream_ctx_t::stream_idx.
Referenced by tpc_ms_setup_stream().
webdav_tpc_curl_finish()
ngx_int_t webdav_tpc_curl_finish (ngx_int_t rc, CURL * curl, struct curl_slist * hdrs, struct curl_slist * resolve, FILE * fp)
Definition at line 178 of file tpc_curl_pmark.c.
References BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_CURL_ERROR, and BRIX_WEBDAV_TPC_CURL_SUCCESS.
Referenced by webdav_tpc_run_curl_core().
webdav_tpc_curl_progress()
int webdav_tpc_curl_progress (void * clientp, curl_off_t dltotal, curl_off_t dlnow, curl_off_t ultotal, curl_off_t ulnow)
Definition at line 127 of file tpc_curl_pmark.c.
References brix_tpc_progress_emit(), brix_tpc_registry_find(), BRIX_TPC_STATE_ACTIVE, brix_tpc_transfer_t::cancelled, webdav_tpc_curl_progress_t::is_push, webdav_tpc_curl_progress_t::last_done, webdav_tpc_curl_progress_t::log, and webdav_tpc_curl_progress_t::transfer_id.
Referenced by tpc_core_setup().
webdav_tpc_pmark_attach()
void webdav_tpc_pmark_attach (CURL * curl, webdav_tpc_pmark_rec_t * rec, ngx_http_brix_webdav_loc_conf_t * conf, int is_push, const char * file_path, ngx_log_t * log)
Definition at line 49 of file tpc_curl_pmark.c.
References webdav_tpc_pmark_rec_t::act, webdav_tpc_pmark_rec_t::active, webdav_tpc_pmark_rec_t::app, brix_pmark_conf_t::appname, brix_pmark_map_codes(), brix_pmark_runtime_ensure(), ngx_http_brix_webdav_loc_conf_t::common, brix_pmark_conf_t::enable, webdav_tpc_pmark_rec_t::exp, webdav_tpc_pmark_rec_t::fd, log, webdav_tpc_pmark_rec_t::log, ngx_memcpy, webdav_tpc_pmark_rec_t::peer_is_src, webdav_tpc_pmark_rec_t::pm, ngx_http_brix_shared_conf_t::pmark, brix_pmark_flow_id_t::vo_csv, webdav_tpc_pmark_closesocket(), and webdav_tpc_pmark_opensocket().
Referenced by tpc_ms_setup_stream(), and webdav_tpc_run_curl_core().
webdav_tpc_pmark_closesocket()
int webdav_tpc_pmark_closesocket (void * clientp, curl_socket_t item)
Definition at line 30 of file tpc_curl_pmark.c.
References webdav_tpc_pmark_rec_t::act, webdav_tpc_pmark_rec_t::active, webdav_tpc_pmark_rec_t::app, brix_pmark_firefly_oneshot(), close(), webdav_tpc_pmark_rec_t::exp, webdav_tpc_pmark_rec_t::fd, webdav_tpc_pmark_rec_t::log, webdav_tpc_pmark_rec_t::peer_is_src, and webdav_tpc_pmark_rec_t::pm.
Referenced by webdav_tpc_pmark_attach().
webdav_tpc_pmark_opensocket()
curl_socket_t webdav_tpc_pmark_opensocket (void * clientp, curlsocktype purpose, struct curl_sockaddr * address)
Definition at line 8 of file tpc_curl_pmark.c.
References webdav_tpc_pmark_rec_t::act, webdav_tpc_pmark_rec_t::active, brix_pmark_flowlabel_apply_addr(), webdav_tpc_pmark_rec_t::exp, webdav_tpc_pmark_rec_t::fd, and webdav_tpc_pmark_rec_t::log.
Referenced by webdav_tpc_pmark_attach().