nginx-xrootd: src/protocols/webdav/tpc_marker_start.c File Reference
tpc_marker_start.c File Reference
#include "webdav.h"
#include "core/compat/net_target.h"
#include "core/compat/staged_file.h"
#include "observability/dashboard/dashboard_tracking.h"
#include "core/aio/aio.h"
#include "tpc/common/metrics.h"
#include "tpc/common/registry.h"
#include "tpc_marker_internal.h"
#include <fcntl.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct tpc_marker_start_args_t
Functions
static void tpc_marker_thread_func (void *data, ngx_log_t *log)
static tpc_marker_ctx_t * tpc_marker_build_ctx (const tpc_marker_start_args_t *a)
static ngx_thread_task_t * tpc_marker_build_task (const tpc_marker_start_args_t *a, tpc_marker_ctx_t *ctx)
static ngx_int_t tpc_marker_arm_lifecycle (ngx_http_request_t *r, tpc_marker_ctx_t *ctx)
static ngx_int_t tpc_marker_send_accepted (ngx_http_request_t *r, ngx_uint_t n_streams)
ngx_int_t webdav_tpc_marker_start (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_uint_t n_streams, const char *url, const char *tmp_path, const char *final_path, ngx_flag_t is_pull, ngx_flag_t overwrite, ngx_flag_t existed, ngx_array_t *transfer_headers, uint64_t transfer_id, const char *user_cert, const char *user_key)
Function Documentation
tpc_marker_arm_lifecycle()
static ngx_int_t tpc_marker_arm_lifecycle (ngx_http_request_t * r, tpc_marker_ctx_t * ctx) static
Definition at line 218 of file tpc_marker_start.c.
References tpc_marker_ctx_t::timer, tpc_marker_cleanup(), and tpc_marker_poll().
Referenced by webdav_tpc_marker_start().
tpc_marker_build_ctx()
static tpc_marker_ctx_t * tpc_marker_build_ctx (const tpc_marker_start_args_t * a) static
Definition at line 126 of file tpc_marker_start.c.
References ngx_http_brix_webdav_loc_conf_t::common, tpc_marker_start_args_t::conf, tpc_marker_ctx_t::existed, tpc_marker_start_args_t::existed, tpc_marker_ctx_t::final_path, tpc_marker_start_args_t::final_path, tpc_marker_ctx_t::is_pull, tpc_marker_start_args_t::is_pull, tpc_marker_ctx_t::last_marker_time, tpc_marker_ctx_t::marker_interval_secs, tpc_marker_start_args_t::n_streams, tpc_ms_progress_t::n_streams, ngx_pcalloc(), tpc_marker_ctx_t::overwrite, tpc_marker_start_args_t::overwrite, tpc_marker_ctx_t::progress, tpc_marker_ctx_t::push_file_size, tpc_marker_ctx_t::r, tpc_marker_start_args_t::r, ngx_http_brix_shared_conf_t::root_canon, tpc_marker_ctx_t::root_canon, stat(), tpc_marker_ctx_t::tmp_path, tpc_marker_start_args_t::tmp_path, tpc_ms_progress_t::total_size, ngx_http_brix_webdav_loc_conf_t::tpc_marker_interval, tpc_marker_ctx_t::transfer_id, and tpc_marker_start_args_t::transfer_id.
Referenced by webdav_tpc_marker_start().
tpc_marker_build_task()
static ngx_thread_task_t * tpc_marker_build_task (const tpc_marker_start_args_t * a, tpc_marker_ctx_t * ctx) static
Definition at line 179 of file tpc_marker_start.c.
References tpc_marker_thread_ctx_t::conf, tpc_marker_start_args_t::conf, tpc_marker_start_args_t::is_pull, tpc_marker_thread_ctx_t::is_push, tpc_marker_thread_ctx_t::local_path, tpc_marker_thread_ctx_t::log, tpc_marker_thread_ctx_t::marker_ctx, tpc_marker_start_args_t::r, tpc_marker_start_args_t::tmp_path, tpc_marker_thread_done(), tpc_marker_thread_func(), tpc_marker_thread_ctx_t::transfer_headers, tpc_marker_start_args_t::transfer_headers, tpc_marker_thread_ctx_t::url, tpc_marker_start_args_t::url, tpc_marker_thread_ctx_t::user_cert, tpc_marker_start_args_t::user_cert, tpc_marker_thread_ctx_t::user_key, and tpc_marker_start_args_t::user_key.
Referenced by webdav_tpc_marker_start().
tpc_marker_send_accepted()
static ngx_int_t tpc_marker_send_accepted (ngx_http_request_t * r, ngx_uint_t n_streams) static
Definition at line 246 of file tpc_marker_start.c.
References ngx_pnalloc().
Referenced by webdav_tpc_marker_start().
tpc_marker_thread_func()
static void tpc_marker_thread_func (void * data, ngx_log_t * log) static
Definition at line 33 of file tpc_marker_start.c.
References brix_net_target_policy_t::allow_local, brix_net_target_policy_t::allow_private, brix_net_target_policy_t::allow_root_scheme, brix_net_target_check_dns(), brix_net_target_parse(), tpc_ms_progress_t::completed, tpc_marker_thread_ctx_t::conf, brix_net_target_policy_t::default_https_port, tpc_marker_thread_ctx_t::is_push, tpc_marker_thread_ctx_t::local_path, log, tpc_marker_thread_ctx_t::log, tpc_marker_thread_ctx_t::marker_ctx, tpc_ms_progress_t::n_streams, tpc_marker_ctx_t::progress, brix_net_target_policy_t::require_https, tpc_ms_progress_t::result, ngx_http_brix_webdav_loc_conf_t::tpc_allow_local, ngx_http_brix_webdav_loc_conf_t::tpc_allow_private, tpc_marker_thread_ctx_t::transfer_headers, tpc_marker_thread_ctx_t::url, tpc_marker_thread_ctx_t::user_cert, tpc_marker_thread_ctx_t::user_key, webdav_tpc_run_curl_pull(), webdav_tpc_run_curl_pull_multi(), and webdav_tpc_run_curl_push().
Referenced by tpc_marker_build_task().
webdav_tpc_marker_start()
ngx_int_t webdav_tpc_marker_start (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_uint_t n_streams, const char * url, const char * tmp_path, const char * final_path, ngx_flag_t is_pull, ngx_flag_t overwrite, ngx_flag_t existed, ngx_array_t * transfer_headers, uint64_t transfer_id, const char * user_cert, const char * user_key)
Definition at line 296 of file tpc_marker_start.c.
References BRIX_TPC_MAX_STREAMS, ngx_http_brix_webdav_loc_conf_t::common, tpc_marker_start_args_t::conf, tpc_marker_start_args_t::existed, tpc_marker_start_args_t::final_path, tpc_marker_start_args_t::is_pull, tpc_marker_ctx_t::last_marker_time, tpc_marker_start_args_t::n_streams, tpc_marker_start_args_t::overwrite, tpc_marker_start_args_t::r, ngx_http_brix_shared_conf_t::thread_pool, tpc_marker_ctx_t::timer, tpc_marker_start_args_t::tmp_path, tpc_marker_arm_lifecycle(), tpc_marker_build_ctx(), tpc_marker_build_task(), TPC_MARKER_POLL_MSEC, tpc_marker_send_accepted(), tpc_marker_send_all(), tpc_marker_start_args_t::transfer_headers, tpc_marker_start_args_t::transfer_id, tpc_marker_start_args_t::url, tpc_marker_start_args_t::user_cert, and tpc_marker_start_args_t::user_key.
Referenced by webdav_tpc_pull_marker_exec().