nginx-xrootd: src/protocols/webdav/tpc_cred.h File Reference
tpc_cred.h File Reference
#include <ngx_core.h>
#include <ngx_http.h>
Enumerations
enum brix_tpc_cred_mode_e { BRIX_TPC_CRED_NONE = 0 , BRIX_TPC_CRED_OIDC_AGENT , BRIX_TPC_CRED_TOKEN_EXCHANGE , BRIX_TPC_CRED_UNKNOWN }
enum brix_tpc_cred_metrics_e {
BRIX_TPC_CRED_NSTARTED = 0 , BRIX_TPC_CRED_NSUCCESS , BRIX_TPC_CRED_NERROR , BRIX_TPC_CRED_NUNKNOWN_MODE ,
BRIX_TPC_CRED_NPARSE_ERROR , BRIX_TPC_CRED_NMAX
}
Functions
brix_tpc_cred_mode_e webdav_tpc_cred_parse_mode (const char *value, size_t len)
Parse a Credential: header value into a mode enum.
ngx_int_t webdav_tpc_cred_obtain_token (ngx_http_request_t *r, brix_tpc_cred_mode_e mode, const char *source_url, const char *subject_token, const char *scope, ngx_str_t *token_out)
Obtain an access token for a TPC pull transfer.
const char * webdav_tpc_cred_metric_name (brix_tpc_cred_metrics_e idx)
Return the name string for a cred-metrics counter index.
ngx_int_t webdav_tpc_cred_metric_increment (ngx_http_request_t *r, brix_tpc_cred_metrics_e idx)
Increment a TPC credential metrics counter in shared memory.
Enumeration Type Documentation
brix_tpc_cred_metrics_e
enum brix_tpc_cred_metrics_e
Enumerator
BRIX_TPC_CRED_NSTARTED
BRIX_TPC_CRED_NSUCCESS
BRIX_TPC_CRED_NERROR
BRIX_TPC_CRED_NUNKNOWN_MODE
BRIX_TPC_CRED_NPARSE_ERROR
BRIX_TPC_CRED_NMAX
Definition at line 40 of file tpc_cred.h.
brix_tpc_cred_mode_e
enum brix_tpc_cred_mode_e
Enumerator
BRIX_TPC_CRED_NONE
BRIX_TPC_CRED_OIDC_AGENT
BRIX_TPC_CRED_TOKEN_EXCHANGE
BRIX_TPC_CRED_UNKNOWN
Definition at line 29 of file tpc_cred.h.
Function Documentation
webdav_tpc_cred_metric_increment()
ngx_int_t webdav_tpc_cred_metric_increment (ngx_http_request_t * r, brix_tpc_cred_metrics_e idx)
Increment a TPC credential metrics counter in shared memory.
Definition at line 43 of file tpc_cred.c.
References BRIX_WEBDAV_METRIC_INC.
Referenced by tpc_cred_finish(), tpc_cred_run_token_exchange(), and webdav_tpc_cred_obtain_token().
webdav_tpc_cred_metric_name()
const char * webdav_tpc_cred_metric_name (brix_tpc_cred_metrics_e idx)
Return the name string for a cred-metrics counter index.
Definition at line 228 of file tpc_cred.c.
webdav_tpc_cred_obtain_token()
ngx_int_t webdav_tpc_cred_obtain_token (ngx_http_request_t * r, brix_tpc_cred_mode_e mode, const char * source_url, const char * subject_token, const char * scope, ngx_str_t * token_out)
Obtain an access token for a TPC pull transfer.
Parameters
r the current ngx_http_request_t
mode parsed credential-delegation mode
source_url the Source: URL (used as issuer/audience)
subject_token the authenticated session token (JWT), may be NULL for oidc-agent mode; required for token-exchange
scope scope string to request (e.g. "storage.read")
token_out [out] allocated in r->pool; caller must not free
Returns
NGX_OK on success; NGX_ERROR on failure (error already logged)
Definition at line 190 of file tpc_cred.c.
webdav_tpc_cred_parse_mode()
brix_tpc_cred_mode_e webdav_tpc_cred_parse_mode (const char * value, size_t len)
Parse a Credential: header value into a mode enum.
Returns BRIX_TPC_CRED_UNKNOWN for unrecognised values.
Definition at line 72 of file tpc_cred.c.