nginx-xrootd: src/protocols/webdav/tpc_copy.c File Reference
tpc_copy.c File Reference
#include "tpc_internal_split.h"
#include "webdav.h"
#include "tpc_user_proxy.h"
#include "fs/path/path.h"
#include "fs/vfs/vfs.h"
#include "core/http/http_headers.h"
#include "core/compat/staged_file.h"
#include "observability/dashboard/dashboard_tracking.h"
#include "observability/sesslog/sesslog_ngx.h"
#include "fs/xfer/xfer.h"
#include "tpc/common/auth.h"
#include "tpc/common/metrics.h"
#include "tpc/common/registry.h"
#include <fcntl.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Functions
ngx_int_t webdav_tpc_apply_credential_delegation (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const char *source_url, ngx_array_t *transfer_headers)
ngx_int_t webdav_tpc_validate_copy_headers (ngx_table_elt_t *source_hdr, ngx_table_elt_t *dest_hdr)
ngx_uint_t webdav_tpc_parse_stream_count (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
ngx_int_t webdav_tpc_source_url (ngx_http_request_t *r, ngx_table_elt_t *source_hdr, char **source_url)
ngx_int_t webdav_tpc_parse_overwrite (ngx_http_request_t *r, ngx_flag_t *overwrite)
static int webdav_tpc_transfer_headers_have_authorization (const ngx_array_t *headers)
ngx_int_t webdav_tpc_forward_user_bearer (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_array_t *transfer_headers)
ngx_int_t webdav_tpc_apply_user_proxy (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, webdav_tpc_pull_ctx_t *pl)
Function Documentation
webdav_tpc_apply_credential_delegation()
ngx_int_t webdav_tpc_apply_credential_delegation (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const char * source_url, ngx_array_t * transfer_headers)
Definition at line 50 of file tpc_copy.c.
References BRIX_TPC_CRED_UNKNOWN, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_BAD_REQUEST, ngx_memcpy, ngx_pnalloc(), ngx_http_brix_tpc_conf_t::token_scope, ngx_http_brix_webdav_loc_conf_t::tpc_cred, webdav_tpc_cred_obtain_token(), webdav_tpc_cred_parse_mode(), webdav_tpc_extract_subject_token(), webdav_tpc_find_header, and webdav_tpc_header_value_equals.
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_apply_user_proxy()
ngx_int_t webdav_tpc_apply_user_proxy (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, webdav_tpc_pull_ctx_t * pl)
Definition at line 312 of file tpc_copy.c.
References BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_BAD_REQUEST, webdav_tpc_user_proxy_t::cert_path, webdav_tpc_user_proxy_t::deny, webdav_tpc_user_proxy_t::have, webdav_tpc_user_proxy_t::key_path, ngx_http_brix_webdav_loc_conf_t::tpc_credential_forward, webdav_tpc_pull_ctx_t::user_cert, webdav_tpc_pull_ctx_t::user_key, and webdav_tpc_user_proxy_resolve().
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_forward_user_bearer()
ngx_int_t webdav_tpc_forward_user_bearer (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_array_t * transfer_headers)
Definition at line 260 of file tpc_copy.c.
References ngx_http_brix_webdav_req_ctx_t::bearer_token, ngx_http_brix_webdav_module, ngx_http_brix_webdav_loc_conf_t::tpc_credential_forward, webdav_tpc_add_bearer_header(), and webdav_tpc_transfer_headers_have_authorization().
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_parse_overwrite()
ngx_int_t webdav_tpc_parse_overwrite (ngx_http_request_t * r, ngx_flag_t * overwrite)
Definition at line 182 of file tpc_copy.c.
References BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_BAD_REQUEST, webdav_tpc_find_header, and webdav_tpc_header_value_equals.
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_parse_stream_count()
ngx_uint_t webdav_tpc_parse_stream_count (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 140 of file tpc_copy.c.
References ngx_http_brix_webdav_loc_conf_t::tpc_max_streams, and webdav_tpc_find_header.
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_source_url()
ngx_int_t webdav_tpc_source_url (ngx_http_request_t * r, ngx_table_elt_t * source_hdr, char ** source_url)
Definition at line 161 of file tpc_copy.c.
References BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_BAD_REQUEST, webdav_tpc_pstrndup0(), and webdav_tpc_str_has_ctl.
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_transfer_headers_have_authorization()
static int webdav_tpc_transfer_headers_have_authorization (const ngx_array_t * headers) static
Definition at line 218 of file tpc_copy.c.
References name.
Referenced by webdav_tpc_forward_user_bearer().
webdav_tpc_validate_copy_headers()
ngx_int_t webdav_tpc_validate_copy_headers (ngx_table_elt_t * source_hdr, ngx_table_elt_t * dest_hdr)
Definition at line 127 of file tpc_copy.c.
References BRIX_WEBDAV_METRIC_INC, and BRIX_WEBDAV_TPC_BAD_REQUEST.
Referenced by ngx_http_brix_webdav_tpc_handle_copy().