nginx-xrootd: src/tpc/outbound/connect.c File Reference
connect.c File Reference
#include "tpc/engine/tpc_internal.h"
#include "core/compat/net_target.h"
#include "observability/pmark/pmark.h"
#include "protocols/root/connection/netconnect.h"
#include <netdb.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <netinet/in.h>
#include <poll.h>
#include <fcntl.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
Functions
int tpc_connect (brix_tpc_pull_t *t)
int brix_tpc_check_src_policy (const char *src_host, uint16_t src_port, ngx_flag_t allow_local, ngx_flag_t allow_private, char *err_msg, size_t err_msg_sz)
Function Documentation
brix_tpc_check_src_policy()
int brix_tpc_check_src_policy (const char * src_host, uint16_t src_port, ngx_flag_t allow_local, ngx_flag_t allow_private, char * err_msg, size_t err_msg_sz)
Definition at line 117 of file connect.c.
References brix_net_target_policy_t::allow_local, brix_net_target_policy_t::allow_private, brix_net_target_check_dns(), brix_net_target_t::has_port, brix_net_target_t::host, and brix_net_target_t::port.
tpc_connect()
int tpc_connect (brix_tpc_pull_t * t)
Definition at line 28 of file connect.c.
References brix_net_target_policy_t::allow_local, brix_net_target_policy_t::allow_private, brix_apply_socket_io_timeouts(), brix_connect_fd_deadline(), brix_net_target_check_addr(), brix_pmark_flowlabel_apply_addr(), close(), brix_tpc_pull_t::conf, brix_tpc_pull_t::err_msg, brix_tpc_pull_t::pmark_act, brix_tpc_pull_t::pmark_exp, brix_tpc_pull_t::src_host, brix_tpc_pull_t::src_port, TPC_CONNECT_TIMEOUT_SEC, and TPC_IO_TIMEOUT_SEC.
Referenced by brix_tpc_pull_thread().