nginx-xrootd: src/tpc/outbound/tpc_token_internal.h File Reference
tpc_token_internal.h File Reference
#include "tpc/engine/tpc_internal.h"
#include <stddef.h>
Functions
int tpc_token_parse_access_token (const char *json, char *out, size_t out_sz)
int tpc_token_rfc8693 (brix_tpc_pull_t *t, char *token_out, size_t token_out_sz)
Function Documentation
tpc_token_parse_access_token()
int tpc_token_parse_access_token (const char * json, char * out, size_t out_sz)
Definition at line 63 of file tpc_token.c.
References brix_oauth2_parse_access_token().
Referenced by tpc_oidc_extract_token(), and tpc_token_rfc8693().
tpc_token_rfc8693()
int tpc_token_rfc8693 (brix_tpc_pull_t * t, char * token_out, size_t token_out_sz)
Definition at line 223 of file tpc_token_exchange.c.
References kXR_AuthFailed, tpc_rfc8693_build_argv(), tpc_rfc8693_read_subject(), tpc_rfc8693_run_curl(), tpc_rfc8693_stage_body(), TPC_TOKEN_MAX_LEN, tpc_token_parse_access_token(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_fetch_delegated_token().