nginx-xrootd: src/tpc/common/registry.c File Reference
registry.c File Reference
#include "registry.h"
#include "core/ngx_brix_module.h"
#include "core/compat/shm_slots.h"
#include <string.h>
Data Structures
struct brix_tpc_registry_entry_t
struct brix_tpc_registry_table_t
Functions
static brix_tpc_registry_table_t * brix_tpc_registry_table (void)
static ngx_int_t brix_tpc_registry_shm_init (ngx_shm_zone_t *shm_zone, void *data)
ngx_int_t brix_tpc_registry_configure (ngx_conf_t *cf)
static uint64_t brix_tpc_registry_next_id (void)
static void brix_tpc_registry_copy_str (ngx_str_t *dst, u_char *storage, size_t storage_len, const ngx_str_t *src)
void brix_tpc_registry_set_max_age (time_t secs)
static ngx_uint_t brix_tpc_registry_reap_locked (brix_tpc_registry_table_t *tbl, time_t now)
ngx_uint_t brix_tpc_registry_reap_stale (ngx_log_t *log)
uint64_t brix_tpc_registry_add (const brix_tpc_transfer_t *transfer, ngx_log_t *log)
ngx_int_t brix_tpc_registry_update (uint64_t id, off_t bytes_done, ngx_uint_t state, ngx_log_t *log)
ngx_int_t brix_tpc_registry_request_cancel (uint64_t id)
ngx_int_t brix_tpc_registry_remove (uint64_t id, ngx_log_t *log)
ngx_uint_t brix_tpc_registry_snapshot (brix_tpc_transfer_snapshot_t *out, ngx_uint_t max_transfers)
const brix_tpc_transfer_t * brix_tpc_registry_find (uint64_t id)
Variables
static ngx_shm_zone_t * brix_tpc_registry_shm_zone
static ngx_shmtx_t brix_tpc_registry_mutex
static uint64_t brix_tpc_registry_sequence
static time_t brix_tpc_registry_max_age
Function Documentation
brix_tpc_registry_add()
uint64_t brix_tpc_registry_add (const brix_tpc_transfer_t * transfer, ngx_log_t * log)
Definition at line 259 of file registry.c.
References brix_tpc_registry_copy_str(), brix_tpc_registry_mutex, brix_tpc_registry_next_id(), brix_tpc_registry_reap_locked(), BRIX_TPC_REGISTRY_SLOTS, brix_tpc_registry_table(), BRIX_TPC_STATE_PENDING, brix_tpc_transfer_t::dst_path, brix_tpc_registry_entry_t::dst_path_data, brix_tpc_transfer_t::id, brix_tpc_registry_entry_t::in_use, log, brix_tpc_registry_table_t::slots, brix_tpc_transfer_t::src_url, brix_tpc_registry_entry_t::src_url_data, brix_tpc_transfer_t::started_at, brix_tpc_transfer_t::state, brix_tpc_registry_entry_t::transfer, and brix_tpc_transfer_t::updated_at.
Referenced by tpc_register_stream_transfer(), webdav_tpc_register_transfer(), and webdav_tpc_thread_register().
brix_tpc_registry_configure()
ngx_int_t brix_tpc_registry_configure (ngx_conf_t * cf)
Definition at line 117 of file registry.c.
References brix_shm_zone_size(), brix_tpc_registry_shm_init(), brix_tpc_registry_shm_zone, and ngx_stream_brix_module.
Referenced by ngx_http_brix_webdav_postconfiguration(), and ngx_stream_brix_postconfiguration().
brix_tpc_registry_copy_str()
static void brix_tpc_registry_copy_str (ngx_str_t * dst, u_char * storage, size_t storage_len, const ngx_str_t * src) static
Definition at line 150 of file registry.c.
References ngx_memcpy.
Referenced by brix_tpc_registry_add().
brix_tpc_registry_find()
const brix_tpc_transfer_t * brix_tpc_registry_find (uint64_t id)
Definition at line 512 of file registry.c.
References BRIX_TPC_REGISTRY_SLOTS, brix_tpc_registry_table(), brix_tpc_transfer_t::id, brix_tpc_registry_entry_t::in_use, brix_tpc_registry_table_t::slots, and brix_tpc_registry_entry_t::transfer.
Referenced by webdav_tpc_curl_progress().
brix_tpc_registry_next_id()
static uint64_t brix_tpc_registry_next_id (void) static
Definition at line 137 of file registry.c.
References brix_tpc_registry_sequence.
Referenced by brix_tpc_registry_add().
brix_tpc_registry_reap_locked()
static ngx_uint_t brix_tpc_registry_reap_locked (brix_tpc_registry_table_t * tbl, time_t now) static
Definition at line 196 of file registry.c.
References brix_tpc_registry_max_age, BRIX_TPC_REGISTRY_SLOTS, brix_tpc_registry_entry_t::in_use, brix_tpc_registry_table_t::slots, brix_tpc_registry_entry_t::transfer, and brix_tpc_transfer_t::updated_at.
Referenced by brix_tpc_registry_add(), and brix_tpc_registry_reap_stale().
brix_tpc_registry_reap_stale()
ngx_uint_t brix_tpc_registry_reap_stale (ngx_log_t * log)
Definition at line 224 of file registry.c.
References brix_tpc_registry_max_age, brix_tpc_registry_mutex, brix_tpc_registry_reap_locked(), brix_tpc_registry_table(), and log.
brix_tpc_registry_remove()
ngx_int_t brix_tpc_registry_remove (uint64_t id, ngx_log_t * log)
Definition at line 421 of file registry.c.
References brix_tpc_registry_mutex, BRIX_TPC_REGISTRY_SLOTS, brix_tpc_registry_table(), brix_tpc_transfer_t::id, brix_tpc_registry_entry_t::in_use, log, brix_tpc_registry_table_t::slots, and brix_tpc_registry_entry_t::transfer.
Referenced by brix_free_fhandle(), brix_tpc_pull_done(), brix_tpc_start_pull(), ngx_http_brix_webdav_tpc_handle_copy(), tpc_marker_finish(), tpc_thread_done(), webdav_tpc_handle_push(), and webdav_tpc_post_thread_task().
brix_tpc_registry_request_cancel()
ngx_int_t brix_tpc_registry_request_cancel (uint64_t id)
Definition at line 390 of file registry.c.
References brix_tpc_registry_mutex, BRIX_TPC_REGISTRY_SLOTS, brix_tpc_registry_table(), brix_tpc_transfer_t::cancelled, brix_tpc_transfer_t::id, brix_tpc_registry_entry_t::in_use, brix_tpc_registry_table_t::slots, and brix_tpc_registry_entry_t::transfer.
Referenced by tpc_marker_cleanup().
brix_tpc_registry_set_max_age()
void brix_tpc_registry_set_max_age (time_t secs)
Definition at line 183 of file registry.c.
References brix_tpc_registry_max_age.
Referenced by brix_merge_srv_tpc().
brix_tpc_registry_shm_init()
static ngx_int_t brix_tpc_registry_shm_init (ngx_shm_zone_t * shm_zone, void * data) static
Definition at line 81 of file registry.c.
References brix_shm_table_alloc(), and brix_tpc_registry_mutex.
Referenced by brix_tpc_registry_configure().
brix_tpc_registry_snapshot()
ngx_uint_t brix_tpc_registry_snapshot (brix_tpc_transfer_snapshot_t * out, ngx_uint_t max_transfers)
Definition at line 457 of file registry.c.
References brix_tpc_registry_mutex, BRIX_TPC_REGISTRY_SLOTS, brix_tpc_registry_table(), brix_tpc_transfer_snapshot_t::bytes_done, brix_tpc_transfer_t::bytes_done, brix_tpc_transfer_snapshot_t::bytes_total, brix_tpc_transfer_t::bytes_total, brix_tpc_transfer_snapshot_t::direction, brix_tpc_transfer_t::direction, brix_tpc_transfer_snapshot_t::dst_path, brix_tpc_registry_entry_t::dst_path_data, brix_tpc_transfer_snapshot_t::id, brix_tpc_transfer_t::id, brix_tpc_registry_entry_t::in_use, ngx_memcpy, brix_tpc_transfer_snapshot_t::protocol, brix_tpc_transfer_t::protocol, brix_tpc_registry_table_t::slots, brix_tpc_transfer_snapshot_t::src_url, brix_tpc_registry_entry_t::src_url_data, brix_tpc_transfer_snapshot_t::started_at, brix_tpc_transfer_t::started_at, brix_tpc_transfer_snapshot_t::state, brix_tpc_transfer_t::state, brix_tpc_registry_entry_t::transfer, brix_tpc_transfer_snapshot_t::updated_at, and brix_tpc_transfer_t::updated_at.
Referenced by dashboard_build_tpc_registry().
brix_tpc_registry_table()
static brix_tpc_registry_table_t * brix_tpc_registry_table (void) static
Definition at line 68 of file registry.c.
References brix_tpc_registry_shm_zone.
Referenced by brix_tpc_registry_add(), brix_tpc_registry_find(), brix_tpc_registry_reap_stale(), brix_tpc_registry_remove(), brix_tpc_registry_request_cancel(), brix_tpc_registry_snapshot(), and brix_tpc_registry_update().
brix_tpc_registry_update()
ngx_int_t brix_tpc_registry_update (uint64_t id, off_t bytes_done, ngx_uint_t state, ngx_log_t * log)
Definition at line 344 of file registry.c.
References brix_tpc_registry_mutex, BRIX_TPC_REGISTRY_SLOTS, brix_tpc_registry_table(), brix_tpc_transfer_t::bytes_done, brix_tpc_transfer_t::id, brix_tpc_registry_entry_t::in_use, log, brix_tpc_registry_table_t::slots, brix_tpc_transfer_t::state, brix_tpc_registry_entry_t::transfer, and brix_tpc_transfer_t::updated_at.
Referenced by brix_tpc_progress_emit(), brix_tpc_pull_done(), brix_tpc_pull_thread(), ngx_http_brix_webdav_tpc_handle_copy(), tpc_thread_func(), and webdav_tpc_handle_push().
Variable Documentation
brix_tpc_registry_max_age
time_t brix_tpc_registry_max_age static
Definition at line 65 of file registry.c.
Referenced by brix_tpc_registry_reap_locked(), brix_tpc_registry_reap_stale(), and brix_tpc_registry_set_max_age().
brix_tpc_registry_mutex
ngx_shmtx_t brix_tpc_registry_mutex static
Definition at line 47 of file registry.c.
Referenced by brix_tpc_registry_add(), brix_tpc_registry_reap_stale(), brix_tpc_registry_remove(), brix_tpc_registry_request_cancel(), brix_tpc_registry_shm_init(), brix_tpc_registry_snapshot(), and brix_tpc_registry_update().
brix_tpc_registry_sequence
uint64_t brix_tpc_registry_sequence static
Definition at line 48 of file registry.c.
Referenced by brix_tpc_registry_next_id().
brix_tpc_registry_shm_zone
ngx_shm_zone_t* brix_tpc_registry_shm_zone static
Definition at line 46 of file registry.c.
Referenced by brix_tpc_registry_configure(), and brix_tpc_registry_table().