nginx-xrootd: src/tpc/engine/tpc_internal.h File Reference
tpc_internal.h File Reference
#include "core/ngx_brix_module.h"
#include "key_registry.h"
#include "tpc/common/auth.h"
#include "tpc/common/credential.h"
#include "tpc/common/registry.h"
#include "tpc/common/metrics.h"
Data Structures
struct brix_tpc_params_t
struct brix_tpc_pull_t
Macros
#define TPC_IO_TIMEOUT_SEC 60 /* SO_RCVTIMEO / SO_SNDTIMEO for read/write */
#define TPC_CONNECT_TIMEOUT_SEC 5 /* poll() timeout for non-blocking connect */
#define TPC_CHUNK_SIZE (1024 * 1024) /* bytes per kXR_read request */
#define TPC_RESP_MAX_BODY (TPC_CHUNK_SIZE + 256) /* malloc cap for recv */
#define TPC_OPEN_RESOLVE_MAX_SEC 120 /* total wall-clock cap for the negotiation */
#define TPC_OPEN_WAIT_CAP_SEC
#define TPC_OPEN_RESOLVE_MAX_ITERS 16 /* max wait/waitresp/attn rounds */
#define BRIX_TPC_REPLY_OPEN 1
#define BRIX_TPC_REPLY_SYNC 2
Functions
int brix_tpc_parse_opaque (const char *opaque, brix_tpc_params_t *out)
int tpc_send_all (brix_tpc_pull_t *t, int fd, const void *buf, size_t len)
int tpc_recv_response (brix_tpc_pull_t *t, int fd, uint16_t *status, u_char **body, uint32_t *dlen)
int tpc_start_tls (brix_tpc_pull_t *t, int fd)
void tpc_tls_teardown (brix_tpc_pull_t *t)
int tpc_connect (brix_tpc_pull_t *t)
int brix_tpc_check_src_policy (const char *src_host, uint16_t src_port, ngx_flag_t allow_local, ngx_flag_t allow_private, char *err_msg, size_t err_msg_sz)
int tpc_bootstrap (brix_tpc_pull_t *t, int fd)
void tpc_put_u32 (u_char *p, uint32_t v)
int tpc_send_kxr_auth (brix_tpc_pull_t *t, int fd, u_char seq, const u_char *cred, uint32_t len)
int tpc_outbound_finish_login (brix_tpc_pull_t *t, int fd, u_char *login_body, uint32_t login_dlen)
int tpc_outbound_gsi (brix_tpc_pull_t *t, int fd, const u_char *login_body, uint32_t login_dlen)
int tpc_outbound_gsi_exchange (brix_tpc_pull_t *t, int fd, u_char *body, uint32_t dlen, X509 *x, STACK_OF(X509) *chain, EVP_PKEY *pkey, u_char *certreq, BIO *cbio, BIO *kbio)
int tpc_outbound_ztn (brix_tpc_pull_t *t, int fd)
int tpc_pull_from_source (brix_tpc_pull_t *t, int fd)
void brix_tpc_pull_thread (void *data, ngx_log_t *log)
int tpc_fetch_delegated_token (brix_tpc_pull_t *t)
void brix_tpc_pull_done (ngx_event_t *ev)
ngx_int_t brix_tpc_prepare_pull (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const brix_tpc_params_t *tpc, const char *dst_path, uint16_t options, uint16_t mode_bits)
ngx_int_t brix_tpc_start_pull (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, int fhandle_idx)
ngx_int_t brix_tpc_launch_pull (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const brix_tpc_params_t *tpc, const char *dst_path, uint16_t options, uint16_t mode_bits)
Macro Definition Documentation
BRIX_TPC_REPLY_OPEN
#define BRIX_TPC_REPLY_OPEN 1
Definition at line 37 of file tpc_internal.h.
BRIX_TPC_REPLY_SYNC
#define BRIX_TPC_REPLY_SYNC 2
Definition at line 38 of file tpc_internal.h.
TPC_CHUNK_SIZE
#define TPC_CHUNK_SIZE (1024 * 1024) /* bytes per kXR_read request */
Definition at line 25 of file tpc_internal.h.
TPC_CONNECT_TIMEOUT_SEC
#define TPC_CONNECT_TIMEOUT_SEC 5 /* poll() timeout for non-blocking connect */
Definition at line 24 of file tpc_internal.h.
TPC_IO_TIMEOUT_SEC
#define TPC_IO_TIMEOUT_SEC 60 /* SO_RCVTIMEO / SO_SNDTIMEO for read/write */
Definition at line 23 of file tpc_internal.h.
TPC_OPEN_RESOLVE_MAX_ITERS
#define TPC_OPEN_RESOLVE_MAX_ITERS 16 /* max wait/waitresp/attn rounds */
Definition at line 35 of file tpc_internal.h.
TPC_OPEN_RESOLVE_MAX_SEC
#define TPC_OPEN_RESOLVE_MAX_SEC 120 /* total wall-clock cap for the negotiation */
Definition at line 33 of file tpc_internal.h.
TPC_OPEN_WAIT_CAP_SEC
#define TPC_OPEN_WAIT_CAP_SEC
Value:
                                         15  /* clamp a single wait sleep AND the per-recv
                                         * idle timeout during open resolution, so a
                                         * silent (no-attn) source fails fast enough
                                         * for the client's --tpc fallback to run */
Definition at line 34 of file tpc_internal.h.
TPC_RESP_MAX_BODY
#define TPC_RESP_MAX_BODY (TPC_CHUNK_SIZE + 256) /* malloc cap for recv */
Definition at line 26 of file tpc_internal.h.
Function Documentation
brix_tpc_check_src_policy()
int brix_tpc_check_src_policy (const char * src_host, uint16_t src_port, ngx_flag_t allow_local, ngx_flag_t allow_private, char * err_msg, size_t err_msg_sz)
Definition at line 97 of file noop.c.
References brix_net_target_policy_t::allow_local, brix_net_target_policy_t::allow_private, brix_net_target_check_dns(), brix_net_target_t::has_port, brix_net_target_t::host, and brix_net_target_t::port.
Referenced by brix_tpc_prepare_pull().
brix_tpc_launch_pull()
ngx_int_t brix_tpc_launch_pull (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const brix_tpc_params_t * tpc, const char * dst_path, uint16_t options, uint16_t mode_bits)
Definition at line 593 of file launch.c.
References brix_tpc_prepare_pull(), and c.
brix_tpc_parse_opaque()
int brix_tpc_parse_opaque (const char * opaque, brix_tpc_params_t * out)
Definition at line 34 of file noop.c.
References brix_tpc_params_t::has_dst, brix_tpc_params_t::has_key, brix_tpc_params_t::has_lfn, brix_tpc_params_t::has_org, brix_tpc_params_t::has_src, brix_tpc_params_t::has_stage, brix_tpc_params_t::has_token_mode, tpc_parse_src_fields(), and tpc_parse_token().
Referenced by brix_handle_open().
brix_tpc_prepare_pull()
ngx_int_t brix_tpc_prepare_pull (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const brix_tpc_params_t * tpc, const char * dst_path, uint16_t options, uint16_t mode_bits)
Definition at line 299 of file launch.c.
References brix_alloc_fhandle(), brix_free_fhandle(), brix_log_access(), BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_OPEN_WR, BRIX_RETURN_ERR, brix_send_error(), brix_session_handle_publish(), brix_set_fhandle_path(), brix_tpc_check_src_policy(), brix_tpc_generate_key(), brix_vfs_open_fd_at(), brix_file_t::bytes_read, brix_file_t::bytes_written, c, brix_file_t::cached_size, close(), ngx_stream_brix_srv_conf_t::common, brix_file_t::device, brix_file_t::fd, brix_ctx_t::files, brix_file_t::from_cache, fstat(), brix_tpc_params_t::has_token_mode, brix_file_t::inode, brix_ctx_t::is_bound, brix_file_t::is_regular, brix_tpc_params_t::key, kXR_ArgInvalid, kXR_IOError, kXR_NotAuthorized, kXR_ServerError, kXR_Unsupported, brix_ctx_t::login, brix_file_t::open_time, brix_file_t::read_ahead_end, brix_file_t::read_last_end, brix_file_t::readable, ngx_http_brix_shared_conf_t::root_canon, ngx_stream_brix_srv_conf_t::rootfd, brix_ctx_login_t::sessid, brix_tpc_params_t::src_host, brix_tpc_params_t::src_path, brix_tpc_params_t::src_port, stat(), ngx_http_brix_shared_conf_t::thread_pool, brix_tpc_params_t::token_mode, ngx_stream_brix_srv_conf_t::tpc_allow_local, ngx_stream_brix_srv_conf_t::tpc_allow_private, brix_file_t::tpc_armed, tpc_build_origin_id(), brix_file_t::tpc_destination, tpc_destination_open_flags(), brix_file_t::tpc_done, brix_file_t::tpc_key, brix_file_t::tpc_org, tpc_send_open_response(), brix_file_t::tpc_src_host, brix_file_t::tpc_src_path, brix_file_t::tpc_src_port, brix_file_t::tpc_started, brix_file_t::tpc_token_mode, brix_file_t::tpc_transfer_id, and brix_file_t::writable.
Referenced by brix_handle_open(), and brix_tpc_launch_pull().
brix_tpc_pull_done()
void brix_tpc_pull_done (ngx_event_t * ev)
Definition at line 40 of file done.c.
References brix_aio_restore_request(), brix_aio_resume(), brix_build_resp_hdr(), brix_free_fhandle(), brix_log_access(), BRIX_MAX_FILES, BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_OPEN_WR, BRIX_OP_SYNC, brix_queue_response(), brix_send_error(), brix_send_ok(), BRIX_SESS_END_ERROR, BRIX_SESS_END_SERVER, BRIX_TPC_DIR_PULL, BRIX_TPC_METRIC_ERROR, BRIX_TPC_METRIC_SUCCESS, brix_tpc_metric_transfer(), BRIX_TPC_PROTO_STREAM, brix_tpc_registry_remove(), brix_tpc_registry_update(), BRIX_TPC_REPLY_SYNC, BRIX_TPC_STATE_DONE, BRIX_TPC_STATE_ERROR, brix_vfs_unlink_path(), brix_file_t::bytes_written, brix_tpc_pull_t::bytes_written, c, brix_tpc_pull_t::c, brix_file_t::cached_size, close(), ngx_stream_brix_srv_conf_t::common, brix_tpc_pull_t::conf, brix_tpc_pull_t::ctx, brix_file_t::device, brix_tpc_pull_t::dst_fd, brix_tpc_pull_t::dst_path, brix_tpc_pull_t::err_msg, brix_file_t::fd, ServerOpenBody::fhandle, brix_tpc_pull_t::fhandle_idx, brix_ctx_t::files, fstat(), brix_file_t::inode, brix_file_t::is_regular, kXR_NoMemory, kXR_ok, kXR_readable, kXR_retstat, kXR_ServerError, kXR_writable, ngx_memcpy, brix_tpc_pull_t::options, brix_tpc_pull_t::reply_kind, brix_tpc_pull_t::result, ngx_http_brix_shared_conf_t::root_canon, stat(), brix_tpc_pull_t::streamid, brix_file_t::tpc_done, brix_tpc_pull_t::tpc_key, tpc_sess_finish_pull(), brix_file_t::tpc_started, brix_file_t::tpc_transfer_id, brix_tpc_pull_t::transfer_id, brix_tpc_pull_t::xrd_error, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_tpc_start_pull().
brix_tpc_pull_thread()
void brix_tpc_pull_thread (void * data, ngx_log_t * log)
Definition at line 16 of file thread.c.
References brix_tpc_registry_update(), BRIX_TPC_STATE_ACTIVE, BRIX_TPC_STATE_DONE, BRIX_TPC_STATE_ERROR, brix_tpc_pull_t::bytes_written, brix_tpc_pull_t::c, close(), brix_tpc_pull_t::deleg_cred_pem, brix_tpc_pull_t::err_msg, kXR_ServerError, log, brix_tpc_pull_t::result, tpc_bootstrap(), tpc_connect(), tpc_pull_from_source(), tpc_tls_teardown(), brix_tpc_pull_t::transfer_id, and brix_tpc_pull_t::xrd_error.
Referenced by brix_tpc_start_pull().
brix_tpc_start_pull()
ngx_int_t brix_tpc_start_pull (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, int fhandle_idx)
Definition at line 453 of file launch.c.
References brix_identity_dn_cstr(), brix_identity_vo_csv_cstr(), brix_log_access(), BRIX_MAX_FILES, BRIX_OP_ERR, BRIX_OP_SYNC, brix_pmark_map_codes(), brix_pmark_runtime_ensure(), BRIX_RETURN_ERR, brix_send_error(), brix_send_wait(), brix_str_cbuf(), brix_tpc_pull_done(), brix_tpc_pull_thread(), brix_tpc_registry_remove(), BRIX_TPC_REPLY_SYNC, c, brix_tpc_pull_t::c, ngx_stream_brix_srv_conf_t::common, brix_tpc_pull_t::conf, brix_tpc_pull_t::ctx, brix_ctx_recv_t::cur_streamid, brix_tpc_pull_t::deleg_cred_len, brix_tpc_pull_t::deleg_cred_pem, brix_ctx_gsi_t::deleg_proxy_len, brix_ctx_gsi_t::deleg_proxy_pem, brix_tpc_pull_t::dst_fd, brix_tpc_pull_t::dst_path, brix_pmark_conf_t::enable, brix_file_t::fd, brix_tpc_pull_t::fhandle_idx, brix_ctx_t::files, brix_pmark_conf_t::flowlabel, brix_ctx_t::gsi, brix_ctx_t::identity, kXR_FileNotOpen, kXR_Overloaded, kXR_ServerError, kXR_Unsupported, ngx_memcpy, brix_file_t::path, ngx_http_brix_shared_conf_t::pmark, brix_tpc_pull_t::pmark_act, brix_tpc_pull_t::pmark_exp, brix_ctx_t::recv, brix_tpc_pull_t::reply_kind, brix_tpc_pull_t::src_host, brix_tpc_pull_t::src_path, brix_tpc_pull_t::src_port, brix_ctx_t::state, brix_tpc_pull_t::streamid, ngx_http_brix_shared_conf_t::thread_pool, brix_tpc_pull_t::token_mode, brix_tpc_pull_t::token_scope, ngx_stream_brix_srv_conf_t::tpc_delegate, brix_file_t::tpc_destination, brix_file_t::tpc_key, brix_tpc_pull_t::tpc_key, brix_file_t::tpc_org, brix_tpc_pull_t::tpc_org, ngx_stream_brix_srv_conf_t::tpc_outbound_scope, tpc_register_stream_transfer(), tpc_sess_abort_pull(), tpc_sess_begin_pull(), brix_file_t::tpc_src_host, brix_file_t::tpc_src_path, brix_file_t::tpc_src_port, brix_file_t::tpc_started, brix_file_t::tpc_token_mode, brix_file_t::tpc_transfer_id, brix_tpc_pull_t::transfer_id, and XRD_ST_AIO.
Referenced by brix_handle_sync().
tpc_bootstrap()
int tpc_bootstrap (brix_tpc_pull_t * t, int fd)
Definition at line 27 of file bootstrap.c.
References BRIX_SESSION_ID_LEN, brix_tpc_pull_t::conf, brix_tpc_pull_t::err_msg, kXR_ableTLS, kXR_AuthFailed, kXR_authmore, kXR_gotoTLS, kXR_NotAuthorized, kXR_ok, kXR_ServerError, kXR_ver005, ngx_memcpy, brix_tpc_pull_t::token_mode, tpc_bootstrap_streamid, tpc_fetch_delegated_token(), tpc_outbound_finish_login(), ngx_stream_brix_srv_conf_t::tpc_outbound_tls, tpc_recv_response(), tpc_send_all(), tpc_start_tls(), brix_tpc_pull_t::xrd_error, xrd_pack_handshake(), xrd_pack_login_request(), and xrd_pack_protocol_request().
Referenced by brix_tpc_pull_thread().
tpc_connect()
int tpc_connect (brix_tpc_pull_t * t)
Definition at line 28 of file connect.c.
References brix_net_target_policy_t::allow_local, brix_net_target_policy_t::allow_private, brix_apply_socket_io_timeouts(), brix_connect_fd_deadline(), brix_net_target_check_addr(), brix_pmark_flowlabel_apply_addr(), close(), brix_tpc_pull_t::conf, brix_tpc_pull_t::err_msg, brix_tpc_pull_t::pmark_act, brix_tpc_pull_t::pmark_exp, socket, brix_tpc_pull_t::src_host, brix_tpc_pull_t::src_port, ngx_stream_brix_srv_conf_t::tpc_allow_local, ngx_stream_brix_srv_conf_t::tpc_allow_private, TPC_CONNECT_TIMEOUT_SEC, and TPC_IO_TIMEOUT_SEC.
Referenced by brix_tpc_pull_thread().
tpc_fetch_delegated_token()
int tpc_fetch_delegated_token (brix_tpc_pull_t * t)
Definition at line 439 of file tpc_token.c.
References brix_tpc_pull_t::conf, brix_tpc_pull_t::delegated_token, brix_tpc_pull_t::err_msg, kXR_ArgInvalid, brix_tpc_pull_t::token_mode, ngx_stream_brix_srv_conf_t::tpc_outbound_token_endpoint, tpc_token_oidc_agent(), tpc_token_rfc8693(), tpc_token_validate_delegated(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_bootstrap().
tpc_outbound_finish_login()
int tpc_outbound_finish_login (brix_tpc_pull_t * t, int fd, u_char * login_body, uint32_t login_dlen)
Definition at line 27 of file gsi_outbound_finish.c.
References brix_sec_proto_advertised(), BRIX_SESSION_ID_LEN, ngx_stream_brix_srv_conf_t::certificate, ngx_stream_brix_srv_conf_t::certificate_key, brix_tpc_pull_t::conf, brix_tpc_pull_t::delegated_token, brix_tpc_pull_t::err_msg, kXR_ArgInvalid, kXR_AuthFailed, brix_tpc_pull_t::src_host, ngx_stream_brix_srv_conf_t::tpc_outbound_bearer_file, tpc_outbound_gsi(), tpc_outbound_ztn(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_bootstrap().
tpc_outbound_gsi()
int tpc_outbound_gsi (brix_tpc_pull_t * t, int fd, const u_char * login_body, uint32_t login_dlen)
Definition at line 49 of file gsi_outbound_certreq.c.
References brix_gsi_build_certreq(), brix_gsi_parse_parms(), brix_gsi_rand(), BRIX_SESSION_ID_LEN, brix_str_cbuf(), BRIX_TPC_CREDENTIAL_PROXY, brix_tpc_credential_validate(), brix_tpc_pull_t::c, ngx_stream_brix_srv_conf_t::certificate, ngx_stream_brix_srv_conf_t::certificate_key, brix_tpc_pull_t::conf, brix_tpc_pull_t::deleg_cred_len, brix_tpc_pull_t::deleg_cred_pem, brix_tpc_pull_t::err_msg, brix_tpc_pull_t::gsi_rtag, kXR_ArgInvalid, kXR_AuthFailed, kXR_authmore, kXR_IOError, kXR_NoMemory, kXR_ServerError, ngx_memcpy, PATH_MAX, brix_tpc_credential_t::proxy_pem, STACK_OF(), tpc_outbound_gsi_exchange(), tpc_outbound_gsi_finish(), tpc_recv_response(), tpc_send_kxr_auth(), brix_tpc_credential_t::type, and brix_tpc_pull_t::xrd_error.
Referenced by tpc_outbound_finish_login().
tpc_outbound_gsi_exchange()
int tpc_outbound_gsi_exchange (brix_tpc_pull_t * t, int fd, u_char * body, uint32_t dlen, X509 * x, STACK_OF(X509) * chain, EVP_PKEY * pkey, u_char * certreq, BIO * cbio, BIO * kbio)
Definition at line 71 of file gsi_outbound_exchange.c.
References brix_gsi_build_cert_response(), brix_tpc_pull_t::conf, brix_tpc_pull_t::err_msg, gsi_find_bucket(), ngx_stream_brix_srv_conf_t::gsi_store, kXR_AuthFailed, kXR_NoMemory, kXR_NotAuthorized, kXR_ok, kXR_ServerError, kXRS_x509, tpc_gsi_exchange_cleanup(), tpc_recv_response(), tpc_send_kxr_auth(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_outbound_gsi().
tpc_outbound_ztn()
int tpc_outbound_ztn (brix_tpc_pull_t * t, int fd)
Definition at line 132 of file gsi_outbound_common.c.
References brix_tpc_pull_t::delegated_token, brix_tpc_pull_t::err_msg, kXR_AuthFailed, kXR_NoMemory, kXR_ok, kXR_ServerError, ngx_memcpy, TPC_BEARER_MAX, tpc_read_bearer_token(), tpc_recv_response(), tpc_send_kxr_auth(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_outbound_finish_login().
tpc_pull_from_source()
int tpc_pull_from_source (brix_tpc_pull_t * t, int fd)
Definition at line 565 of file source.c.
References tpc_close_source(), tpc_open_source(), tpc_stream_to_dst(), and XRD_FHANDLE_LEN.
Referenced by brix_tpc_pull_thread().
tpc_put_u32()
void tpc_put_u32 (u_char * p, uint32_t v)
Definition at line 35 of file gsi_outbound_common.c.
References ngx_memcpy.
tpc_recv_response()
int tpc_recv_response (brix_tpc_pull_t * t, int fd, uint16_t * status, u_char ** body, uint32_t * dlen)
Definition at line 119 of file io.c.
References ServerResponseHdr::dlen, ServerResponseHdr::status, tpc_recv_exact(), and TPC_RESP_MAX_BODY.
Referenced by tpc_bootstrap(), tpc_close_source(), tpc_open_resolve(), tpc_outbound_gsi_exchange(), tpc_outbound_ztn(), and tpc_stream_to_dst().
tpc_send_all()
int tpc_send_all (brix_tpc_pull_t * t, int fd, const void * buf, size_t len)
Definition at line 37 of file io.c.
References brix_tpc_pull_t::tls.
Referenced by tpc_bootstrap(), tpc_close_source(), tpc_open_resolve(), tpc_open_source(), tpc_send_kxr_auth(), and tpc_stream_to_dst().
tpc_send_kxr_auth()
int tpc_send_kxr_auth (brix_tpc_pull_t * t, int fd, u_char seq, const u_char * cred, uint32_t len)
Definition at line 52 of file gsi_outbound_common.c.
References ClientRequestHdr::body, ClientRequestHdr::dlen, brix_tpc_pull_t::err_msg, kXR_auth, kXR_ServerError, ngx_memcpy, ClientRequestHdr::requestid, ClientRequestHdr::streamid, tpc_send_all(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_outbound_gsi_exchange().
tpc_start_tls()
int tpc_start_tls (brix_tpc_pull_t * t, int fd)
Definition at line 35 of file tls.c.
References brix_str_cbuf(), brix_tpc_pull_t::conf, brix_tpc_pull_t::err_msg, kXR_NotAuthorized, kXR_ServerError, PATH_MAX, brix_tpc_pull_t::src_host, brix_tpc_pull_t::tls, brix_tpc_pull_t::tls_ctx, ngx_stream_brix_srv_conf_t::trusted_ca, and brix_tpc_pull_t::xrd_error.
Referenced by tpc_bootstrap().
tpc_tls_teardown()
void tpc_tls_teardown (brix_tpc_pull_t * t)
Definition at line 112 of file tls.c.
References brix_tpc_pull_t::tls, and brix_tpc_pull_t::tls_ctx.
Referenced by brix_tpc_pull_thread().