nginx-xrootd: src/protocols/webdav/tpc_cred_oidc.c File Reference
tpc_cred_oidc.c File Reference
#include "tpc_cred_internal.h"
#include "tpc_config.h"
#include "webdav.h"
#include "core/compat/log_diag.h"
#include "tpc/common/credential.h"
#include "core/compat/subprocess.h"
#include <nginx.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include <ngx_config.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <fcntl.h>
Macros
#define TPC_CRED_HELPER_PATH "/usr/local/sbin/nginx-xrootd-tpc-cred"
Functions
static const char * resolve_oidc_token_binary (void)
static ngx_str_t oidc_resolve_socket_path (const char *sock_env)
static ngx_str_t oidc_resolve_helper_path (void)
static void oidc_derive_client_name (const char *source_url, char *out, size_t out_sz)
static void oidc_child_exec_cli (const char *source_url, const char *sock_env)
static void oidc_run_child (int pipefd[2], ngx_str_t helper_path, ngx_str_t sock_path, const char *source_url, const char *sock_env)
static ssize_t oidc_drain_pipe (int read_fd, char *buf, size_t buf_sz)
static ngx_int_t oidc_reap_child (ngx_http_request_t *r, ngx_pid_t pid, const sigset_t *old_mask)
static ngx_int_t oidc_finalize_token (ngx_http_request_t *r, char *buf, ssize_t nread, ngx_str_t *token_out)
ngx_int_t tpc_cred_oidc_agent_fetch (ngx_http_request_t *r, const char *source_url, const char *scope, ngx_str_t *token_out)
Send a JSON request to the oidc-agent UNIX socket and read the token.
Macro Definition Documentation
TPC_CRED_HELPER_PATH
#define TPC_CRED_HELPER_PATH "/usr/local/sbin/nginx-xrootd-tpc-cred"
Definition at line 38 of file tpc_cred_oidc.c.
Function Documentation
oidc_child_exec_cli()
static void oidc_child_exec_cli (const char * source_url, const char * sock_env) static
Definition at line 178 of file tpc_cred_oidc.c.
References oidc_derive_client_name(), and resolve_oidc_token_binary().
Referenced by oidc_run_child().
oidc_derive_client_name()
static void oidc_derive_client_name (const char * source_url, char * out, size_t out_sz) static
Definition at line 132 of file tpc_cred_oidc.c.
References ngx_memcpy.
Referenced by oidc_child_exec_cli().
oidc_drain_pipe()
static ssize_t oidc_drain_pipe (int read_fd, char * buf, size_t buf_sz) static
Definition at line 267 of file tpc_cred_oidc.c.
References close(), and read().
Referenced by tpc_cred_oidc_agent_fetch().
oidc_finalize_token()
static ngx_int_t oidc_finalize_token (ngx_http_request_t * r, char * buf, ssize_t nread, ngx_str_t * token_out) static
Definition at line 319 of file tpc_cred_oidc.c.
References ngx_pnalloc(), and tpc_cred_parse_token_response().
Referenced by tpc_cred_oidc_agent_fetch().
oidc_reap_child()
static ngx_int_t oidc_reap_child (ngx_http_request_t * r, ngx_pid_t pid, const sigset_t * old_mask) static
Definition at line 294 of file tpc_cred_oidc.c.
Referenced by tpc_cred_oidc_agent_fetch().
oidc_resolve_helper_path()
static ngx_str_t oidc_resolve_helper_path (void) static
Definition at line 104 of file tpc_cred_oidc.c.
References access(), and TPC_CRED_HELPER_PATH.
Referenced by tpc_cred_oidc_agent_fetch().
oidc_resolve_socket_path()
static ngx_str_t oidc_resolve_socket_path (const char * sock_env) static
Definition at line 78 of file tpc_cred_oidc.c.
Referenced by tpc_cred_oidc_agent_fetch().
oidc_run_child()
static void oidc_run_child (int pipefd[2], ngx_str_t helper_path, ngx_str_t sock_path, const char * source_url, const char * sock_env) static
Definition at line 231 of file tpc_cred_oidc.c.
References close(), and oidc_child_exec_cli().
Referenced by tpc_cred_oidc_agent_fetch().
resolve_oidc_token_binary()
static const char * resolve_oidc_token_binary (void) static
Definition at line 49 of file tpc_cred_oidc.c.
References access().
Referenced by oidc_child_exec_cli().
tpc_cred_oidc_agent_fetch()
ngx_int_t tpc_cred_oidc_agent_fetch (ngx_http_request_t * r, const char * source_url, const char * scope, ngx_str_t * token_out)
Send a JSON request to the oidc-agent UNIX socket and read the token.
Spawns a tiny fork/exec pipeline: nginx-worker → fork → exec "oidc-token -c <client>" or socket helper
If the OIDC_SOCK environment variable is set, we connect directly to it. Otherwise we fall back to the default oidc-agent socket location.
The helper process is: src/webdav/tpc_cred_oidc_helper (built separately) which handles the socket IPC. If that helper binary is not found we attempt a simpler approach using the oidc-token CLI if available.
Definition at line 364 of file tpc_cred_oidc.c.
References close(), oidc_drain_pipe(), oidc_finalize_token(), oidc_reap_child(), oidc_resolve_helper_path(), oidc_resolve_socket_path(), oidc_run_child(), scope, and TPC_CRED_MAX_TOKEN_LEN.
Referenced by tpc_cred_run_oidc_agent().