nginx-xrootd: src/protocols/webdav/tpc_push.c File Reference
tpc_push.c File Reference
#include "tpc_internal_split.h"
#include "webdav.h"
#include "tpc_user_proxy.h"
#include "fs/path/path.h"
#include "fs/vfs/vfs.h"
#include "core/http/http_headers.h"
#include "core/compat/staged_file.h"
#include "observability/dashboard/dashboard_tracking.h"
#include "observability/sesslog/sesslog_ngx.h"
#include "fs/xfer/xfer.h"
#include "tpc/common/auth.h"
#include "tpc/common/metrics.h"
#include "tpc/common/registry.h"
#include <fcntl.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
struct webdav_tpc_push_ctx_t
Functions
static ngx_int_t webdav_tpc_push_apply_credential (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, char *dest_url, ngx_array_t *headers)
static ngx_int_t webdav_tpc_push_dest_url (ngx_http_request_t *r, ngx_table_elt_t *dest_hdr, char **dest_url)
static ngx_int_t webdav_tpc_push_add_overwrite_value (ngx_http_request_t *r, ngx_array_t *headers, ngx_table_elt_t *overwrite_hdr)
static ngx_int_t webdav_tpc_push_forward_overwrite (ngx_http_request_t *r, ngx_array_t *headers)
static ngx_int_t webdav_tpc_push_post_thread (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, char *dest_url, char *path, ngx_array_t *headers)
static ngx_int_t webdav_tpc_push_sync_error (ngx_http_request_t *r, uint64_t transfer_id, char *path, off_t expected_bytes, ngx_int_t rc)
static ngx_int_t webdav_tpc_push_sync_exec (webdav_tpc_push_ctx_t *px)
ngx_int_t webdav_tpc_handle_push (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_table_elt_t *dest_hdr)
Function Documentation
webdav_tpc_handle_push()
ngx_int_t webdav_tpc_handle_push (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_table_elt_t * dest_hdr)
Definition at line 278 of file tpc_push.c.
References brix_dashboard_http_start_identity(), brix_dashboard_http_tpc_remote(), BRIX_TPC_DIR_PUSH, BRIX_TPC_METRIC_STARTED, brix_tpc_metric_transfer(), BRIX_TPC_PROTO_WEBDAV, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_PUSH_STARTED, BRIX_XFER_DIR_TPC, BRIX_XFER_PROTO_WEBDAV, webdav_tpc_push_ctx_t::conf, webdav_tpc_push_ctx_t::dest_url, webdav_tpc_push_ctx_t::expected_bytes, webdav_tpc_push_ctx_t::headers, webdav_tpc_push_ctx_t::path, webdav_tpc_push_ctx_t::r, stat(), webdav_dashboard_identity(), WEBDAV_MAX_PATH, webdav_resolve_stat(), webdav_tpc_authorize(), webdav_tpc_collect_transfer_headers(), webdav_tpc_push_apply_credential(), webdav_tpc_push_dest_url(), webdav_tpc_push_forward_overwrite(), webdav_tpc_push_post_thread(), and webdav_tpc_push_sync_exec().
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_push_add_overwrite_value()
static ngx_int_t webdav_tpc_push_add_overwrite_value (ngx_http_request_t * r, ngx_array_t * headers, ngx_table_elt_t * overwrite_hdr) static
Definition at line 118 of file tpc_push.c.
References ngx_memcpy, and ngx_pnalloc().
Referenced by webdav_tpc_push_forward_overwrite().
webdav_tpc_push_apply_credential()
static ngx_int_t webdav_tpc_push_apply_credential (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, char * dest_url, ngx_array_t * headers) static
Definition at line 42 of file tpc_push.c.
References BRIX_TPC_CRED_UNKNOWN, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_BAD_REQUEST, ngx_http_brix_tpc_conf_t::token_scope, ngx_http_brix_webdav_loc_conf_t::tpc_cred, webdav_tpc_add_bearer_header(), webdav_tpc_cred_obtain_token(), webdav_tpc_cred_parse_mode(), webdav_tpc_extract_subject_token(), webdav_tpc_find_header, and webdav_tpc_header_value_equals.
Referenced by webdav_tpc_handle_push().
webdav_tpc_push_dest_url()
static ngx_int_t webdav_tpc_push_dest_url (ngx_http_request_t * r, ngx_table_elt_t * dest_hdr, char ** dest_url) static
Definition at line 97 of file tpc_push.c.
References BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_BAD_REQUEST, webdav_tpc_pstrndup0(), and webdav_tpc_str_has_ctl.
Referenced by webdav_tpc_handle_push().
webdav_tpc_push_forward_overwrite()
static ngx_int_t webdav_tpc_push_forward_overwrite (ngx_http_request_t * r, ngx_array_t * headers) static
Definition at line 148 of file tpc_push.c.
References webdav_tpc_find_header, and webdav_tpc_push_add_overwrite_value().
Referenced by webdav_tpc_handle_push().
webdav_tpc_push_post_thread()
static ngx_int_t webdav_tpc_push_post_thread (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, char * dest_url, char * path, ngx_array_t * headers) static
Definition at line 163 of file tpc_push.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), and webdav_tpc_post_thread_task().
Referenced by webdav_tpc_handle_push().
webdav_tpc_push_sync_error()
static ngx_int_t webdav_tpc_push_sync_error (ngx_http_request_t * r, uint64_t transfer_id, char * path, off_t expected_bytes, ngx_int_t rc) static
Definition at line 183 of file tpc_push.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), BRIX_TPC_DIR_PUSH, BRIX_TPC_METRIC_ERROR, brix_tpc_metric_transfer(), BRIX_TPC_PROTO_WEBDAV, brix_tpc_registry_remove(), brix_tpc_registry_update(), BRIX_TPC_STATE_ERROR, BRIX_XFER_DST_ERR, brix_xfer_finish(), BRIX_XFER_TPC, and webdav_tpc_note_client_copy_xfer().
Referenced by webdav_tpc_push_sync_exec().
webdav_tpc_push_sync_exec()
static ngx_int_t webdav_tpc_push_sync_exec (webdav_tpc_push_ctx_t * px) static
Definition at line 222 of file tpc_push.c.
References brix_dashboard_http_add(), brix_dashboard_http_error(), brix_dashboard_http_finish(), BRIX_TPC_DIR_PUSH, BRIX_TPC_METRIC_SUCCESS, brix_tpc_metric_transfer(), BRIX_TPC_PROTO_WEBDAV, brix_tpc_registry_remove(), brix_tpc_registry_update(), BRIX_TPC_STATE_DONE, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_PUSH_SUCCESS, brix_xfer_finish(), BRIX_XFER_OK, BRIX_XFER_TPC, webdav_tpc_push_ctx_t::conf, webdav_tpc_push_ctx_t::dest_url, webdav_tpc_push_ctx_t::expected_bytes, webdav_tpc_push_ctx_t::headers, webdav_tpc_push_ctx_t::path, webdav_tpc_push_ctx_t::r, webdav_send_no_body(), webdav_tpc_note_client_copy_xfer(), webdav_tpc_push_sync_error(), webdav_tpc_register_transfer(), and webdav_tpc_run_curl_push().
Referenced by webdav_tpc_handle_push().