nginx-xrootd: src/tpc/outbound/io.c File Reference
io.c File Reference
#include "tpc/engine/tpc_internal.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <openssl/ssl.h>
Functions
int tpc_send_all (brix_tpc_pull_t *t, int fd, const void *buf, size_t len)
static int tpc_recv_exact (brix_tpc_pull_t *t, int fd, void *buf, size_t len)
int tpc_recv_response (brix_tpc_pull_t *t, int fd, uint16_t *status, u_char **body, uint32_t *dlen)
Function Documentation
tpc_recv_exact()
static int tpc_recv_exact (brix_tpc_pull_t * t, int fd, void * buf, size_t len) static
Definition at line 70 of file io.c.
References brix_tpc_pull_t::tls.
Referenced by tpc_recv_response().
tpc_recv_response()
int tpc_recv_response (brix_tpc_pull_t * t, int fd, uint16_t * status, u_char ** body, uint32_t * dlen)
Definition at line 119 of file io.c.
References ServerResponseHdr::dlen, ServerResponseHdr::status, tpc_recv_exact(), and TPC_RESP_MAX_BODY.
Referenced by tpc_bootstrap_handshake(), tpc_bootstrap_login(), tpc_bootstrap_protocol(), tpc_certreq_recv_authmore(), tpc_close_source(), tpc_open_resolve_round(), tpc_outbound_gsi_exchange(), tpc_outbound_ztn(), tpc_stat_source(), tpc_stream_drain_request(), and tpc_verify_source_checksum().
tpc_send_all()
int tpc_send_all (brix_tpc_pull_t * t, int fd, const void * buf, size_t len)
Definition at line 37 of file io.c.
References brix_tpc_pull_t::tls.
Referenced by tpc_bootstrap_handshake(), tpc_bootstrap_login(), tpc_bootstrap_protocol(), tpc_close_source(), tpc_open_source(), tpc_open_wait_resend(), tpc_send_kxr_auth(), tpc_stat_source(), tpc_stream_send_read(), and tpc_verify_source_checksum().