nginx-xrootd: src/protocols/webdav/tpc_pull.c File Reference
tpc_pull.c File Reference
#include "tpc_internal_split.h"
#include "webdav.h"
#include "tpc_user_proxy.h"
#include "fs/path/path.h"
#include "fs/vfs/vfs.h"
#include "core/http/http_headers.h"
#include "core/compat/staged_file.h"
#include "observability/dashboard/dashboard_tracking.h"
#include "observability/sesslog/sesslog_ngx.h"
#include "fs/xfer/xfer.h"
#include "tpc/common/auth.h"
#include "tpc/common/metrics.h"
#include "tpc/common/registry.h"
#include <fcntl.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Functions
static ngx_int_t webdav_tpc_probe (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const char *path, struct stat *sb)
static void webdav_tpc_url_path (const char *url, ngx_str_t *out)
ngx_int_t webdav_tpc_prepare_pull_target (webdav_tpc_pull_ctx_t *pl)
void webdav_tpc_pull_start_accounting (ngx_http_request_t *r, const char *path, const char *source_url)
static ngx_int_t webdav_tpc_pull_marker_exec (webdav_tpc_pull_ctx_t *pl)
static ngx_int_t webdav_tpc_pull_thread_exec (webdav_tpc_pull_ctx_t *pl)
static ngx_int_t webdav_tpc_pull_sync_exec (webdav_tpc_pull_ctx_t *pl)
static ngx_int_t webdav_tpc_commit_pulled_file (webdav_tpc_pull_ctx_t *pl)
static ngx_int_t webdav_tpc_finish_pull_success (webdav_tpc_pull_ctx_t *pl)
ngx_int_t webdav_tpc_pull_execute (webdav_tpc_pull_ctx_t *pl)
Function Documentation
webdav_tpc_commit_pulled_file()
static ngx_int_t webdav_tpc_commit_pulled_file (webdav_tpc_pull_ctx_t * pl) static
Definition at line 290 of file tpc_pull.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_link_confined_canon(), brix_log_safe_path(), brix_staged_abort(), brix_staged_commit(), BRIX_TPC_DIR_PULL, BRIX_TPC_METRIC_ERROR, brix_tpc_metric_transfer(), BRIX_TPC_PROTO_WEBDAV, brix_tpc_registry_remove(), brix_tpc_registry_update(), BRIX_TPC_STATE_ERROR, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_COMMIT_ERROR, ngx_http_brix_webdav_loc_conf_t::common, webdav_tpc_pull_ctx_t::conf, webdav_tpc_pull_ctx_t::overwrite, webdav_tpc_pull_ctx_t::path, webdav_tpc_pull_ctx_t::r, ngx_http_brix_shared_conf_t::root_canon, webdav_tpc_pull_ctx_t::staged, brix_staged_file_t::tmp_path, and webdav_tpc_pull_ctx_t::transfer_id.
Referenced by webdav_tpc_pull_execute().
webdav_tpc_finish_pull_success()
static ngx_int_t webdav_tpc_finish_pull_success (webdav_tpc_pull_ctx_t * pl) static
Definition at line 333 of file tpc_pull.c.
References brix_dashboard_http_add(), brix_dashboard_http_finish(), BRIX_TPC_DIR_PULL, BRIX_TPC_METRIC_SUCCESS, brix_tpc_metric_transfer(), BRIX_TPC_PROTO_WEBDAV, brix_tpc_registry_remove(), brix_tpc_registry_update(), BRIX_TPC_STATE_DONE, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_PULL_SUCCESS, brix_xfer_finish(), BRIX_XFER_OK, BRIX_XFER_TPC, webdav_tpc_pull_ctx_t::conf, webdav_tpc_pull_ctx_t::existed, webdav_tpc_pull_ctx_t::path, webdav_tpc_pull_ctx_t::r, webdav_tpc_pull_ctx_t::sb, stat(), webdav_tpc_pull_ctx_t::transfer_id, webdav_send_no_body(), webdav_tpc_note_client_copy_xfer(), and webdav_tpc_probe().
Referenced by webdav_tpc_pull_execute().
webdav_tpc_prepare_pull_target()
ngx_int_t webdav_tpc_prepare_pull_target (webdav_tpc_pull_ctx_t * pl)
Definition at line 106 of file tpc_pull.c.
References brix_staged_open(), ngx_http_brix_webdav_loc_conf_t::common, webdav_tpc_pull_ctx_t::conf, webdav_tpc_pull_ctx_t::existed, brix_staged_file_t::fd, ngx_http_brix_webdav_resolve_path(), webdav_tpc_pull_ctx_t::overwrite, webdav_tpc_pull_ctx_t::path, webdav_tpc_pull_ctx_t::path_len, webdav_tpc_pull_ctx_t::r, brix_staged_open_req_t::root_canon, ngx_http_brix_shared_conf_t::root_canon, webdav_tpc_pull_ctx_t::sb, webdav_tpc_pull_ctx_t::source_url, webdav_tpc_pull_ctx_t::staged, stat(), webdav_tpc_authorize(), webdav_tpc_probe(), and webdav_tpc_url_path().
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_probe()
static ngx_int_t webdav_tpc_probe (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const char * path, struct stat * sb) static
Definition at line 48 of file tpc_pull.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_WEBDAV, brix_vfs_ctx_init(), brix_vfs_probe(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::identity, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, ngx_http_brix_webdav_module, brix_vfs_ctx_t::pool, ngx_http_brix_shared_conf_t::root_canon, and brix_vfs_stat_t::size.
Referenced by webdav_tpc_finish_pull_success(), and webdav_tpc_prepare_pull_target().
webdav_tpc_pull_execute()
ngx_int_t webdav_tpc_pull_execute (webdav_tpc_pull_ctx_t * pl)
Definition at line 396 of file tpc_pull.c.
References webdav_tpc_commit_pulled_file(), webdav_tpc_finish_pull_success(), webdav_tpc_pull_marker_exec(), webdav_tpc_pull_sync_exec(), and webdav_tpc_pull_thread_exec().
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_pull_marker_exec()
static ngx_int_t webdav_tpc_pull_marker_exec (webdav_tpc_pull_ctx_t * pl) static
Definition at line 173 of file tpc_pull.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_staged_abort(), BRIX_TPC_DIR_PULL, brix_tpc_registry_remove(), ngx_http_brix_webdav_loc_conf_t::common, webdav_tpc_pull_ctx_t::conf, webdav_tpc_pull_ctx_t::existed, webdav_tpc_pull_ctx_t::n_streams, webdav_tpc_pull_ctx_t::overwrite, webdav_tpc_pull_ctx_t::path, webdav_tpc_pull_ctx_t::r, ngx_http_brix_shared_conf_t::root_canon, webdav_tpc_pull_ctx_t::source_url, webdav_tpc_pull_ctx_t::staged, brix_staged_file_t::tmp_path, ngx_http_brix_webdav_loc_conf_t::tpc_marker_interval, webdav_tpc_pull_ctx_t::transfer_headers, webdav_tpc_pull_ctx_t::user_cert, webdav_tpc_pull_ctx_t::user_key, webdav_tpc_marker_start(), and webdav_tpc_register_transfer().
Referenced by webdav_tpc_pull_execute().
webdav_tpc_pull_start_accounting()
void webdav_tpc_pull_start_accounting (ngx_http_request_t * r, const char * path, const char * source_url)
Definition at line 160 of file tpc_pull.c.
References brix_dashboard_http_start_identity(), brix_dashboard_http_tpc_remote(), BRIX_TPC_DIR_PULL, BRIX_TPC_METRIC_STARTED, brix_tpc_metric_transfer(), BRIX_TPC_PROTO_WEBDAV, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_PULL_STARTED, BRIX_XFER_DIR_TPC, BRIX_XFER_PROTO_WEBDAV, and webdav_dashboard_identity().
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_pull_sync_exec()
static ngx_int_t webdav_tpc_pull_sync_exec (webdav_tpc_pull_ctx_t * pl) static
Definition at line 249 of file tpc_pull.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_staged_abort(), BRIX_TPC_DIR_PULL, BRIX_TPC_METRIC_ERROR, brix_tpc_metric_transfer(), BRIX_TPC_PROTO_WEBDAV, brix_tpc_registry_remove(), brix_tpc_registry_update(), BRIX_TPC_STATE_ERROR, brix_xfer_finish(), BRIX_XFER_SRC_ERR, BRIX_XFER_TPC, ngx_http_brix_webdav_loc_conf_t::common, webdav_tpc_pull_ctx_t::conf, webdav_tpc_pull_ctx_t::path, webdav_tpc_pull_ctx_t::r, ngx_http_brix_shared_conf_t::root_canon, webdav_tpc_pull_ctx_t::source_url, webdav_tpc_pull_ctx_t::staged, brix_staged_file_t::tmp_path, webdav_tpc_pull_ctx_t::transfer_headers, webdav_tpc_pull_ctx_t::transfer_id, webdav_tpc_pull_ctx_t::user_cert, webdav_tpc_pull_ctx_t::user_key, webdav_tpc_note_client_copy_xfer(), webdav_tpc_register_transfer(), and webdav_tpc_run_curl_pull().
Referenced by webdav_tpc_pull_execute().
webdav_tpc_pull_thread_exec()
static ngx_int_t webdav_tpc_pull_thread_exec (webdav_tpc_pull_ctx_t * pl) static
Definition at line 219 of file tpc_pull.c.
References brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_staged_abort(), ngx_http_brix_webdav_loc_conf_t::common, webdav_tpc_pull_ctx_t::conf, webdav_tpc_pull_ctx_t::existed, webdav_tpc_pull_ctx_t::n_streams, webdav_tpc_pull_ctx_t::overwrite, webdav_tpc_pull_ctx_t::path, webdav_tpc_pull_ctx_t::r, ngx_http_brix_shared_conf_t::root_canon, webdav_tpc_pull_ctx_t::source_url, webdav_tpc_pull_ctx_t::staged, brix_staged_file_t::tmp_path, webdav_tpc_pull_ctx_t::transfer_headers, webdav_tpc_pull_ctx_t::user_cert, webdav_tpc_pull_ctx_t::user_key, and webdav_tpc_post_thread_task().
Referenced by webdav_tpc_pull_execute().
webdav_tpc_url_path()
static void webdav_tpc_url_path (const char * url, ngx_str_t * out) static
Definition at line 81 of file tpc_pull.c.
References scheme.
Referenced by webdav_tpc_prepare_pull_target().