nginx-xrootd: src/protocols/webdav/tpc_cred.c File Reference
tpc_cred.c File Reference
#include "tpc_cred_internal.h"
#include "tpc_config.h"
#include "webdav.h"
#include "core/compat/log_diag.h"
#include "tpc/common/credential.h"
#include "core/compat/subprocess.h"
#include <nginx.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include <ngx_config.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <fcntl.h>
Macros
#define TPC_CRED_HELPER_PATH "/usr/local/sbin/nginx-xrootd-tpc-cred"
Functions
ngx_int_t webdav_tpc_cred_metric_increment (ngx_http_request_t *r, brix_tpc_cred_metrics_e idx)
Increment a TPC credential metrics counter in shared memory.
static ngx_int_t webdav_tpc_cred_validate_token (ngx_http_request_t *r, ngx_str_t *token)
static const char * resolve_oidc_token_binary (void)
static ngx_int_t tpc_cred_oidc_agent_fetch (ngx_http_request_t *r, const char *source_url, const char *scope, ngx_str_t *token_out)
Send a JSON request to the oidc-agent UNIX socket and read the token.
static ngx_int_t tpc_cred_rfc8693_exchange (ngx_http_request_t *r, const char *subject_token, const char *source_url, const char *scope, const char *token_endpoint, const char *client_id, const char *client_secret, ngx_str_t *token_out)
Perform an RFC 8693 token-exchange request.
brix_tpc_cred_mode_e webdav_tpc_cred_parse_mode (const char *value, size_t len)
Parse a Credential: header value into a mode enum.
ngx_int_t webdav_tpc_cred_obtain_token (ngx_http_request_t *r, brix_tpc_cred_mode_e mode, const char *source_url, const char *subject_token, const char *scope, ngx_str_t *token_out)
Obtain an access token for a TPC pull transfer.
const char * webdav_tpc_cred_metric_name (brix_tpc_cred_metrics_e idx)
Return the name string for a cred-metrics counter index.
Macro Definition Documentation
TPC_CRED_HELPER_PATH
#define TPC_CRED_HELPER_PATH "/usr/local/sbin/nginx-xrootd-tpc-cred"
Definition at line 67 of file tpc_cred.c.
Function Documentation
resolve_oidc_token_binary()
static const char * resolve_oidc_token_binary (void) static
Definition at line 78 of file tpc_cred.c.
References access().
Referenced by tpc_cred_oidc_agent_fetch().
tpc_cred_oidc_agent_fetch()
static ngx_int_t tpc_cred_oidc_agent_fetch (ngx_http_request_t * r, const char * source_url, const char * scope, ngx_str_t * token_out) static
Send a JSON request to the oidc-agent UNIX socket and read the token.
Spawns a tiny fork/exec pipeline: nginx-worker → fork → exec "oidc-token -c <client>" or socket helper
If the OIDC_SOCK environment variable is set, we connect directly to it. Otherwise we fall back to the default oidc-agent socket location.
The helper process is: src/webdav/tpc_cred_oidc_helper (built separately) which handles the socket IPC. If that helper binary is not found we attempt a simpler approach using the oidc-token CLI if available.
Definition at line 112 of file tpc_cred.c.
References access(), close(), ngx_memcpy, ngx_pnalloc(), read(), resolve_oidc_token_binary(), TPC_CRED_HELPER_PATH, TPC_CRED_MAX_TOKEN_LEN, and tpc_cred_parse_token_response().
Referenced by webdav_tpc_cred_obtain_token().
tpc_cred_rfc8693_exchange()
static ngx_int_t tpc_cred_rfc8693_exchange (ngx_http_request_t * r, const char * subject_token, const char * source_url, const char * scope, const char * token_endpoint, const char * client_id, const char * client_secret, ngx_str_t * token_out) static
Perform an RFC 8693 token-exchange request.
Sends a POST to the configured token endpoint with: grant_type=urn:ietf:params:oauth:grant-type:token-exchange subject_token=<JWT> resource=<source_url> audience=<source_url> scope=<scope>
Uses a fork/exec'd curl subprocess (same pattern as tpc_curl.c).
Definition at line 340 of file tpc_cred.c.
References brix_subprocess_capture(), close(), TPC_CRED_MAX_TOKEN_LEN, and tpc_cred_parse_token_response().
Referenced by webdav_tpc_cred_obtain_token().
webdav_tpc_cred_metric_increment()
ngx_int_t webdav_tpc_cred_metric_increment (ngx_http_request_t * r, brix_tpc_cred_metrics_e idx)
Increment a TPC credential metrics counter in shared memory.
Definition at line 39 of file tpc_cred.c.
References BRIX_WEBDAV_METRIC_INC.
Referenced by webdav_tpc_cred_obtain_token().
webdav_tpc_cred_metric_name()
const char * webdav_tpc_cred_metric_name (brix_tpc_cred_metrics_e idx)
Return the name string for a cred-metrics counter index.
Definition at line 541 of file tpc_cred.c.
References BRIX_TPC_CRED_NERROR, BRIX_TPC_CRED_NPARSE_ERROR, BRIX_TPC_CRED_NSTARTED, BRIX_TPC_CRED_NSUCCESS, and BRIX_TPC_CRED_NUNKNOWN_MODE.
webdav_tpc_cred_obtain_token()
ngx_int_t webdav_tpc_cred_obtain_token (ngx_http_request_t * r, brix_tpc_cred_mode_e mode, const char * source_url, const char * subject_token, const char * scope, ngx_str_t * token_out)
Obtain an access token for a TPC pull transfer.
Parameters
r the current ngx_http_request_t
mode parsed credential-delegation mode
source_url the Source: URL (used as issuer/audience)
subject_token the authenticated session token (JWT), may be NULL for oidc-agent mode; required for token-exchange
scope scope string to request (e.g. "storage.read")
token_out [out] allocated in r->pool; caller must not free
Returns
NGX_OK on success; NGX_ERROR on failure (error already logged)
Definition at line 461 of file tpc_cred.c.
References BRIX_DIAG_ERR, BRIX_TPC_CRED_NERROR, BRIX_TPC_CRED_NSTARTED, BRIX_TPC_CRED_NSUCCESS, BRIX_TPC_CRED_NUNKNOWN_MODE, BRIX_TPC_CRED_OIDC_AGENT, BRIX_TPC_CRED_TOKEN_EXCHANGE, mode, ngx_http_brix_webdav_module, ngx_http_brix_tpc_conf_t::token_client_id, ngx_http_brix_tpc_conf_t::token_client_secret, ngx_http_brix_tpc_conf_t::token_endpoint, ngx_http_brix_webdav_loc_conf_t::tpc_cred, tpc_cred_oidc_agent_fetch(), tpc_cred_rfc8693_exchange(), webdav_tpc_cred_metric_increment(), and webdav_tpc_cred_validate_token().
Referenced by webdav_tpc_apply_credential_delegation(), and webdav_tpc_handle_push().
webdav_tpc_cred_parse_mode()
brix_tpc_cred_mode_e webdav_tpc_cred_parse_mode (const char * value, size_t len)
Parse a Credential: header value into a mode enum.
Returns BRIX_TPC_CRED_UNKNOWN for unrecognised values.
Definition at line 443 of file tpc_cred.c.
References BRIX_TPC_CRED_NONE, BRIX_TPC_CRED_OIDC_AGENT, BRIX_TPC_CRED_TOKEN_EXCHANGE, and BRIX_TPC_CRED_UNKNOWN.
Referenced by webdav_tpc_apply_credential_delegation(), and webdav_tpc_handle_push().
webdav_tpc_cred_validate_token()
static ngx_int_t webdav_tpc_cred_validate_token (ngx_http_request_t * r, ngx_str_t * token) static
Definition at line 48 of file tpc_cred.c.
References brix_tpc_credential_parse(), BRIX_TPC_CREDENTIAL_TOKEN, and brix_tpc_credential_validate().
Referenced by webdav_tpc_cred_obtain_token().