nginx-xrootd: src/tpc/engine/noop.c File Reference
noop.c File Reference
#include "tpc_internal.h"
Functions
int brix_tpc_parse_opaque (const char *opaque, brix_tpc_params_t *out)
ngx_int_t brix_tpc_key_configure_registry (ngx_conf_t *cf)
void brix_tpc_generate_key (char *buf, size_t buf_sz)
void brix_tpc_key_register (const char *key, ngx_msec_t ttl_ms)
int brix_tpc_key_validate (const char *key)
int brix_tpc_key_consume (const char *key)
void brix_tpc_key_remove (const char *key)
int brix_tpc_check_src_policy (const char *src_host, uint16_t src_port, ngx_flag_t allow_local, ngx_flag_t allow_private, char *err_msg, size_t err_msg_sz)
ngx_int_t brix_tpc_prepare_pull (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const brix_tpc_params_t *tpc, const char *dst_path, uint16_t options, uint16_t mode_bits)
ngx_int_t brix_tpc_start_pull (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, int fhandle_idx)
ngx_int_t brix_tpc_launch_pull (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const brix_tpc_params_t *tpc, const char *dst_path, uint16_t options, uint16_t mode_bits)
Function Documentation
brix_tpc_check_src_policy()
int brix_tpc_check_src_policy (const char * src_host, uint16_t src_port, ngx_flag_t allow_local, ngx_flag_t allow_private, char * err_msg, size_t err_msg_sz)
Definition at line 97 of file noop.c.
Referenced by brix_tpc_prepare_pull().
brix_tpc_generate_key()
void brix_tpc_generate_key (char * buf, size_t buf_sz)
Definition at line 56 of file noop.c.
brix_tpc_key_configure_registry()
ngx_int_t brix_tpc_key_configure_registry (ngx_conf_t * cf)
Definition at line 48 of file noop.c.
brix_tpc_key_consume()
int brix_tpc_key_consume (const char * key)
Definition at line 81 of file noop.c.
References key.
brix_tpc_key_register()
void brix_tpc_key_register (const char * key, ngx_msec_t ttl_ms)
Definition at line 65 of file noop.c.
References key.
brix_tpc_key_remove()
void brix_tpc_key_remove (const char * key)
Definition at line 89 of file noop.c.
References key.
brix_tpc_key_validate()
int brix_tpc_key_validate (const char * key)
Definition at line 73 of file noop.c.
References key.
brix_tpc_launch_pull()
ngx_int_t brix_tpc_launch_pull (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const brix_tpc_params_t * tpc, const char * dst_path, uint16_t options, uint16_t mode_bits)
Definition at line 148 of file noop.c.
References brix_tpc_prepare_pull(), and c.
brix_tpc_parse_opaque()
int brix_tpc_parse_opaque (const char * opaque, brix_tpc_params_t * out)
Definition at line 34 of file noop.c.
Referenced by brix_handle_open().
brix_tpc_prepare_pull()
ngx_int_t brix_tpc_prepare_pull (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const brix_tpc_params_t * tpc, const char * dst_path, uint16_t options, uint16_t mode_bits)
Definition at line 118 of file noop.c.
References brix_send_error(), c, and kXR_Unsupported.
Referenced by brix_tpc_launch_pull().
brix_tpc_start_pull()
ngx_int_t brix_tpc_start_pull (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, int fhandle_idx)
Definition at line 135 of file noop.c.
References brix_send_error(), c, and kXR_Unsupported.