nginx-xrootd: src/protocols/webdav/tpc_curl_internal.h File Reference
tpc_curl_internal.h File Reference
#include "webdav.h"
#include "fs/backend/sd.h"
#include "tpc/common/registry.h"
#include "core/compat/net_target.h"
#include "core/compat/host_format.h"
#include <curl/curl.h>
#include <fcntl.h>
#include <stdio.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <unistd.h>
Data Structures
struct webdav_tpc_pmark_rec_t
struct webdav_tpc_curl_progress_t
struct ms_stream_ctx_t
struct webdav_tpc_ms_ctx_t
Macros
#define BRIX_TPC_CONNECT_TIMEOUT_SECS 30L
Functions
curl_socket_t webdav_tpc_pmark_opensocket (void *clientp, curlsocktype purpose, struct curl_sockaddr *address)
int webdav_tpc_pmark_closesocket (void *clientp, curl_socket_t item)
void webdav_tpc_pmark_attach (CURL *curl, webdav_tpc_pmark_rec_t *rec, ngx_http_brix_webdav_loc_conf_t *conf, int is_push, const char *file_path, ngx_log_t *log)
int tpc_curl_secure (CURL *curl, ngx_http_brix_webdav_loc_conf_t *conf, const char *url, ngx_log_t *log, struct curl_slist **resolve_out)
void tpc_curl_apply_stall_bounds (CURL *curl, ngx_http_brix_webdav_loc_conf_t *conf)
int tpc_curl_apply_conf (CURL *curl, ngx_http_brix_webdav_loc_conf_t *conf, const char *url, ngx_array_t *transfer_headers, ngx_log_t *log, const char *user_cert, const char *user_key, struct curl_slist **hdrs_out, struct curl_slist **resolve_out)
off_t tpc_curl_head_size (ngx_log_t *log, ngx_http_brix_webdav_loc_conf_t *conf, const char *url, ngx_array_t *transfer_headers, const char *user_cert, const char *user_key)
size_t ms_write_cb (char *ptr, size_t size, size_t nmemb, void *userdata)
int webdav_tpc_curl_progress (void *clientp, curl_off_t dltotal, curl_off_t dlnow, curl_off_t ultotal, curl_off_t ulnow)
ngx_int_t webdav_tpc_curl_finish (ngx_int_t rc, CURL *curl, struct curl_slist *hdrs, struct curl_slist *resolve, FILE *fp)
ngx_int_t webdav_tpc_run_curl_core (ngx_log_t *log, ngx_http_brix_webdav_loc_conf_t *conf, ngx_array_t *transfer_headers, int is_push, const char *file_path, const char *url, const char *log_tag, uint64_t transfer_id, const char *user_cert, const char *user_key)
ngx_int_t webdav_tpc_run_curl_multi_finish (ngx_int_t rc, CURLM *cm, CURL **easy, struct curl_slist **hdrs, struct curl_slist **resolve, ngx_uint_t n_streams, int fd)
Macro Definition Documentation
BRIX_TPC_CONNECT_TIMEOUT_SECS
#define BRIX_TPC_CONNECT_TIMEOUT_SECS 30L
Definition at line 73 of file tpc_curl_internal.h.
Function Documentation
ms_write_cb()
size_t ms_write_cb (char * ptr, size_t size, size_t nmemb, void * userdata)
Definition at line 93 of file tpc_curl_pmark.c.
References brix_sd_posix_wrap(), tpc_ms_progress_t::bytes_per_stream, ms_stream_ctx_t::cur_offset, ms_stream_ctx_t::fd, ms_stream_ctx_t::progress, and ms_stream_ctx_t::stream_idx.
Referenced by tpc_ms_setup_stream().
tpc_curl_apply_conf()
int tpc_curl_apply_conf (CURL * curl, ngx_http_brix_webdav_loc_conf_t * conf, const char * url, ngx_array_t * transfer_headers, ngx_log_t * log, const char * user_cert, const char * user_key, struct curl_slist ** hdrs_out, struct curl_slist ** resolve_out)
Definition at line 159 of file tpc_curl_setup.c.
References log, ngx_http_brix_webdav_loc_conf_t::tpc_cadir, ngx_http_brix_webdav_loc_conf_t::tpc_cafile, tpc_curl_apply_client_cred(), tpc_curl_apply_stall_bounds(), tpc_curl_secure(), and ngx_http_brix_webdav_loc_conf_t::tpc_timeout.
Referenced by tpc_curl_head_size(), and tpc_ms_setup_stream().
tpc_curl_apply_stall_bounds()
void tpc_curl_apply_stall_bounds (CURL * curl, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 106 of file tpc_curl_setup.c.
References BRIX_TPC_CONNECT_TIMEOUT_SECS, ngx_http_brix_webdav_loc_conf_t::tpc_low_speed_bytes, and ngx_http_brix_webdav_loc_conf_t::tpc_low_speed_secs.
Referenced by tpc_core_setup(), and tpc_curl_apply_conf().
tpc_curl_head_size()
off_t tpc_curl_head_size (ngx_log_t * log, ngx_http_brix_webdav_loc_conf_t * conf, const char * url, ngx_array_t * transfer_headers, const char * user_cert, const char * user_key)
Definition at line 224 of file tpc_curl_setup.c.
References log, and tpc_curl_apply_conf().
Referenced by webdav_tpc_run_curl_pull_multi().
tpc_curl_secure()
int tpc_curl_secure (CURL * curl, ngx_http_brix_webdav_loc_conf_t * conf, const char * url, ngx_log_t * log, struct curl_slist ** resolve_out)
Definition at line 27 of file tpc_curl_setup.c.
References brix_net_target_policy_t::allow_local, brix_net_target_policy_t::allow_private, brix_format_host(), brix_net_target_check_dns_pin(), brix_net_target_parse(), brix_net_target_policy_t::default_https_port, brix_net_target_t::has_port, brix_net_target_t::host, log, ngx_memcpy, brix_net_target_t::port, brix_net_target_policy_t::require_https, ngx_http_brix_webdav_loc_conf_t::tpc_allow_local, and ngx_http_brix_webdav_loc_conf_t::tpc_allow_private.
Referenced by tpc_core_setup(), and tpc_curl_apply_conf().
webdav_tpc_curl_finish()
ngx_int_t webdav_tpc_curl_finish (ngx_int_t rc, CURL * curl, struct curl_slist * hdrs, struct curl_slist * resolve, FILE * fp)
Definition at line 178 of file tpc_curl_pmark.c.
References BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_CURL_ERROR, and BRIX_WEBDAV_TPC_CURL_SUCCESS.
Referenced by webdav_tpc_run_curl_core().
webdav_tpc_curl_progress()
int webdav_tpc_curl_progress (void * clientp, curl_off_t dltotal, curl_off_t dlnow, curl_off_t ultotal, curl_off_t ulnow)
Definition at line 127 of file tpc_curl_pmark.c.
References brix_tpc_progress_emit(), brix_tpc_registry_find(), BRIX_TPC_STATE_ACTIVE, brix_tpc_transfer_t::cancelled, webdav_tpc_curl_progress_t::is_push, webdav_tpc_curl_progress_t::last_done, webdav_tpc_curl_progress_t::log, and webdav_tpc_curl_progress_t::transfer_id.
Referenced by tpc_core_setup().
webdav_tpc_pmark_attach()
void webdav_tpc_pmark_attach (CURL * curl, webdav_tpc_pmark_rec_t * rec, ngx_http_brix_webdav_loc_conf_t * conf, int is_push, const char * file_path, ngx_log_t * log)
Definition at line 49 of file tpc_curl_pmark.c.
References webdav_tpc_pmark_rec_t::act, webdav_tpc_pmark_rec_t::active, webdav_tpc_pmark_rec_t::app, brix_pmark_conf_t::appname, brix_pmark_map_codes(), brix_pmark_runtime_ensure(), ngx_http_brix_webdav_loc_conf_t::common, brix_pmark_conf_t::enable, webdav_tpc_pmark_rec_t::exp, webdav_tpc_pmark_rec_t::fd, log, webdav_tpc_pmark_rec_t::log, ngx_memcpy, webdav_tpc_pmark_rec_t::peer_is_src, webdav_tpc_pmark_rec_t::pm, ngx_http_brix_shared_conf_t::pmark, brix_pmark_flow_id_t::vo_csv, webdav_tpc_pmark_closesocket(), and webdav_tpc_pmark_opensocket().
Referenced by tpc_ms_setup_stream(), and webdav_tpc_run_curl_core().
webdav_tpc_pmark_closesocket()
int webdav_tpc_pmark_closesocket (void * clientp, curl_socket_t item)
Definition at line 30 of file tpc_curl_pmark.c.
References webdav_tpc_pmark_rec_t::act, webdav_tpc_pmark_rec_t::active, webdav_tpc_pmark_rec_t::app, brix_pmark_firefly_oneshot(), close(), webdav_tpc_pmark_rec_t::exp, webdav_tpc_pmark_rec_t::fd, webdav_tpc_pmark_rec_t::log, webdav_tpc_pmark_rec_t::peer_is_src, and webdav_tpc_pmark_rec_t::pm.
Referenced by webdav_tpc_pmark_attach().
webdav_tpc_pmark_opensocket()
curl_socket_t webdav_tpc_pmark_opensocket (void * clientp, curlsocktype purpose, struct curl_sockaddr * address)
Definition at line 8 of file tpc_curl_pmark.c.
References webdav_tpc_pmark_rec_t::act, webdav_tpc_pmark_rec_t::active, brix_pmark_flowlabel_apply_addr(), webdav_tpc_pmark_rec_t::exp, webdav_tpc_pmark_rec_t::fd, and webdav_tpc_pmark_rec_t::log.
Referenced by webdav_tpc_pmark_attach().
webdav_tpc_run_curl_core()
ngx_int_t webdav_tpc_run_curl_core (ngx_log_t * log, ngx_http_brix_webdav_loc_conf_t * conf, ngx_array_t * transfer_headers, int is_push, const char * file_path, const char * url, const char * log_tag, uint64_t transfer_id, const char * user_cert, const char * user_key)
Definition at line 321 of file tpc_curl.c.
References BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_CURL_STARTED, webdav_tpc_curl_ctx_t::conf, webdav_tpc_curl_ctx_t::curl, webdav_tpc_curl_ctx_t::file_path, webdav_tpc_curl_ctx_t::fp, webdav_tpc_curl_ctx_t::hdrs, webdav_tpc_curl_ctx_t::is_push, log, webdav_tpc_curl_ctx_t::log, webdav_tpc_curl_ctx_t::log_tag, webdav_tpc_curl_ctx_t::resolve, tpc_core_perform(), tpc_core_setup(), webdav_tpc_curl_ctx_t::transfer_headers, webdav_tpc_curl_ctx_t::transfer_id, webdav_tpc_curl_ctx_t::url, webdav_tpc_curl_ctx_t::user_cert, webdav_tpc_curl_ctx_t::user_key, webdav_tpc_curl_finish(), and webdav_tpc_pmark_attach().
Referenced by webdav_tpc_run_curl_pull(), and webdav_tpc_run_curl_push().
webdav_tpc_run_curl_multi_finish()
ngx_int_t webdav_tpc_run_curl_multi_finish (ngx_int_t rc, CURLM * cm, CURL ** easy, struct curl_slist ** hdrs, struct curl_slist ** resolve, ngx_uint_t n_streams, int fd)
Definition at line 418 of file tpc_curl.c.
References BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_CURL_ERROR, BRIX_WEBDAV_TPC_CURL_SUCCESS, and close().
Referenced by webdav_tpc_run_curl_pull_multi().