nginx-xrootd: src/protocols/webdav/tpc_curl_multi.c File Reference
tpc_curl_multi.c File Reference
#include "tpc_curl_internal.h"
Functions
ngx_int_t webdav_tpc_run_curl_multi_finish (ngx_int_t rc, CURLM *cm, CURL **easy, struct curl_slist **hdrs, struct curl_slist **resolve, ngx_uint_t n_streams, int fd)
static int tpc_ms_prepare_output (ngx_log_t *log, const char *tmp_path, off_t total_size)
static ngx_int_t tpc_ms_setup_stream (webdav_tpc_ms_ctx_t *ctx, ngx_uint_t i)
static ngx_int_t tpc_ms_drive (ngx_log_t *log, CURLM *cm)
static ngx_int_t tpc_ms_harvest (ngx_log_t *log, CURLM *cm)
ngx_int_t webdav_tpc_run_curl_pull_multi (ngx_log_t *log, ngx_http_brix_webdav_loc_conf_t *conf, const char *source_url, const char *tmp_path, ngx_array_t *transfer_headers, ngx_uint_t n_streams, uint64_t transfer_id, tpc_ms_progress_t *progress, const char *user_cert, const char *user_key)
Function Documentation
tpc_ms_drive()
static ngx_int_t tpc_ms_drive (ngx_log_t * log, CURLM * cm) static
Definition at line 159 of file tpc_curl_multi.c.
References log.
Referenced by webdav_tpc_run_curl_pull_multi().
tpc_ms_harvest()
static ngx_int_t tpc_ms_harvest (ngx_log_t * log, CURLM * cm) static
Definition at line 189 of file tpc_curl_multi.c.
References log.
Referenced by webdav_tpc_run_curl_pull_multi().
tpc_ms_prepare_output()
static int tpc_ms_prepare_output (ngx_log_t * log, const char * tmp_path, off_t total_size) static
Definition at line 60 of file tpc_curl_multi.c.
References brix_sd_posix_driver, brix_sd_posix_wrap(), close(), log, and open().
Referenced by webdav_tpc_run_curl_pull_multi().
tpc_ms_setup_stream()
static ngx_int_t tpc_ms_setup_stream (webdav_tpc_ms_ctx_t * ctx, ngx_uint_t i) static
Definition at line 104 of file tpc_curl_multi.c.
References webdav_tpc_ms_ctx_t::cm, webdav_tpc_ms_ctx_t::conf, ms_stream_ctx_t::cur_offset, webdav_tpc_ms_ctx_t::easy, ms_stream_ctx_t::fd, webdav_tpc_ms_ctx_t::fd, webdav_tpc_ms_ctx_t::hdrs, webdav_tpc_ms_ctx_t::log, ms_write_cb(), webdav_tpc_ms_ctx_t::n_streams, ms_stream_ctx_t::progress, webdav_tpc_ms_ctx_t::progress, webdav_tpc_ms_ctx_t::resolve, webdav_tpc_ms_ctx_t::source_url, ms_stream_ctx_t::stream_idx, webdav_tpc_ms_ctx_t::tmp_path, webdav_tpc_ms_ctx_t::total_size, tpc_curl_apply_conf(), webdav_tpc_ms_ctx_t::transfer_headers, webdav_tpc_ms_ctx_t::user_cert, webdav_tpc_ms_ctx_t::user_key, webdav_tpc_pmark_attach(), and webdav_tpc_ms_ctx_t::write_ctx.
Referenced by webdav_tpc_run_curl_pull_multi().
webdav_tpc_run_curl_multi_finish()
ngx_int_t webdav_tpc_run_curl_multi_finish (ngx_int_t rc, CURLM * cm, CURL ** easy, struct curl_slist ** hdrs, struct curl_slist ** resolve, ngx_uint_t n_streams, int fd)
Definition at line 19 of file tpc_curl_multi.c.
References BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_CURL_ERROR, BRIX_WEBDAV_TPC_CURL_SUCCESS, and close().
Referenced by webdav_tpc_run_curl_pull_multi().
webdav_tpc_run_curl_pull_multi()
ngx_int_t webdav_tpc_run_curl_pull_multi (ngx_log_t * log, ngx_http_brix_webdav_loc_conf_t * conf, const char * source_url, const char * tmp_path, ngx_array_t * transfer_headers, ngx_uint_t n_streams, uint64_t transfer_id, tpc_ms_progress_t * progress, const char * user_cert, const char * user_key)
Definition at line 229 of file tpc_curl_multi.c.
References BRIX_TPC_MAX_STREAMS, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_CURL_STARTED, close(), webdav_tpc_ms_ctx_t::cm, webdav_tpc_ms_ctx_t::conf, webdav_tpc_ms_ctx_t::easy, webdav_tpc_ms_ctx_t::fd, webdav_tpc_ms_ctx_t::hdrs, log, webdav_tpc_ms_ctx_t::log, webdav_tpc_ms_ctx_t::n_streams, webdav_tpc_ms_ctx_t::progress, webdav_tpc_ms_ctx_t::resolve, webdav_tpc_ms_ctx_t::source_url, webdav_tpc_ms_ctx_t::tmp_path, webdav_tpc_ms_ctx_t::total_size, tpc_ms_progress_t::total_size, tpc_curl_head_size(), tpc_ms_drive(), tpc_ms_harvest(), tpc_ms_prepare_output(), tpc_ms_setup_stream(), webdav_tpc_ms_ctx_t::transfer_headers, webdav_tpc_ms_ctx_t::user_cert, webdav_tpc_ms_ctx_t::user_key, webdav_tpc_run_curl_multi_finish(), webdav_tpc_run_curl_pull(), and webdav_tpc_ms_ctx_t::write_ctx.
Referenced by tpc_marker_thread_func(), and tpc_thread_pull_fetch().