nginx-xrootd: src/protocols/webdav/tpc_cred_internal.h File Reference
tpc_cred_internal.h File Reference
#include "tpc_cred.h"
#include "webdav.h"
Macros
#define TPC_CRED_MAX_TOKEN_LEN 4096
Functions
ngx_int_t tpc_cred_parse_token_response (ngx_http_request_t *r, const char *json, ngx_str_t *token_out)
ngx_int_t tpc_cred_oidc_agent_fetch (ngx_http_request_t *r, const char *source_url, const char *scope, ngx_str_t *token_out)
Send a JSON request to the oidc-agent UNIX socket and read the token.
ngx_int_t tpc_cred_rfc8693_exchange (ngx_http_request_t *r, const char *subject_token, const char *source_url, const char *scope, const char *token_endpoint, const char *client_id, const char *client_secret, ngx_str_t *token_out)
Perform an RFC 8693 token-exchange request.
Macro Definition Documentation
TPC_CRED_MAX_TOKEN_LEN
#define TPC_CRED_MAX_TOKEN_LEN 4096
Definition at line 8 of file tpc_cred_internal.h.
Function Documentation
tpc_cred_oidc_agent_fetch()
ngx_int_t tpc_cred_oidc_agent_fetch (ngx_http_request_t * r, const char * source_url, const char * scope, ngx_str_t * token_out)
Send a JSON request to the oidc-agent UNIX socket and read the token.
Spawns a tiny fork/exec pipeline: nginx-worker → fork → exec "oidc-token -c <client>" or socket helper
If the OIDC_SOCK environment variable is set, we connect directly to it. Otherwise we fall back to the default oidc-agent socket location.
The helper process is: src/webdav/tpc_cred_oidc_helper (built separately) which handles the socket IPC. If that helper binary is not found we attempt a simpler approach using the oidc-token CLI if available.
Definition at line 364 of file tpc_cred_oidc.c.
References close(), oidc_drain_pipe(), oidc_finalize_token(), oidc_reap_child(), oidc_resolve_helper_path(), oidc_resolve_socket_path(), oidc_run_child(), scope, and TPC_CRED_MAX_TOKEN_LEN.
Referenced by tpc_cred_run_oidc_agent().
tpc_cred_parse_token_response()
ngx_int_t tpc_cred_parse_token_response (ngx_http_request_t * r, const char * json, ngx_str_t * token_out)
Definition at line 21 of file tpc_cred_parse.c.
References brix_oauth2_parse_access_token(), ngx_pnalloc(), and TPC_CRED_MAX_TOKEN_LEN.
Referenced by oidc_finalize_token(), and tpc_cred_rfc8693_exchange().
tpc_cred_rfc8693_exchange()
ngx_int_t tpc_cred_rfc8693_exchange (ngx_http_request_t * r, const char * subject_token, const char * source_url, const char * scope, const char * token_endpoint, const char * client_id, const char * client_secret, ngx_str_t * token_out)
Perform an RFC 8693 token-exchange request.
Sends a POST to the configured token endpoint with: grant_type=urn:ietf:params:oauth:grant-type:token-exchange subject_token=<JWT> resource=<source_url> audience=<source_url> scope=<scope>
Uses a fork/exec'd curl subprocess (same pattern as tpc_curl.c).
Definition at line 50 of file tpc_cred_exchange.c.
References brix_cred_stage_write(), brix_subprocess_capture(), scope, TPC_CRED_MAX_TOKEN_LEN, and tpc_cred_parse_token_response().
Referenced by tpc_cred_run_token_exchange().