nginx-xrootd: src/protocols/webdav/tpc_thread.c File Reference
tpc_thread.c File Reference
#include "webdav.h"
#include "core/compat/net_target.h"
#include "observability/dashboard/dashboard_tracking.h"
#include "tpc/common/metrics.h"
#include "core/aio/aio.h"
#include "tpc/common/registry.h"
#include "fs/xfer/xfer.h"
#include <errno.h>
#include <sys/stat.h>
Data Structures
struct tpc_thread_ctx_t
Functions
static uint64_t webdav_tpc_thread_register (ngx_http_request_t *r, int is_push, const char *url, const char *local_path, const char *dest_path)
static void tpc_thread_func (void *data, ngx_log_t *log)
static void tpc_thread_done (ngx_event_t *ev)
ngx_int_t webdav_tpc_post_thread_task (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, int is_push, ngx_flag_t existed, ngx_flag_t overwrite, const char *url, const char *local_path, const char *dest_path, ngx_array_t *transfer_headers, ngx_uint_t n_streams)
Function Documentation
tpc_thread_done()
static void tpc_thread_done (ngx_event_t * ev) static
Definition at line 272 of file tpc_thread.c.
References brix_dashboard_http_add(), brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_tpc_registry_remove(), BRIX_XFER_DST_ERR, brix_xfer_finish(), BRIX_XFER_OK, BRIX_XFER_SRC_ERR, BRIX_XFER_TPC, tpc_thread_ctx_t::bytes_transferred, tpc_thread_ctx_t::dest_path, tpc_thread_ctx_t::http_status, tpc_thread_ctx_t::is_push, tpc_thread_ctx_t::local_path, tpc_thread_ctx_t::log, tpc_thread_ctx_t::r, tpc_thread_ctx_t::transfer_id, tpc_thread_ctx_t::url, webdav_metrics_finalize_request(), and webdav_send_status_only().
Referenced by webdav_tpc_post_thread_task().
tpc_thread_func()
static void tpc_thread_func (void * data, ngx_log_t * log) static
Definition at line 93 of file tpc_thread.c.
References brix_net_target_policy_t::allow_local, brix_net_target_policy_t::allow_private, brix_net_target_policy_t::allow_root_scheme, brix_link_confined_canon(), brix_log_safe_path(), brix_net_target_check_dns(), brix_net_target_parse(), brix_rename_confined_canon(), BRIX_TPC_DIR_PULL, BRIX_TPC_DIR_PUSH, BRIX_TPC_METRIC_ERROR, BRIX_TPC_METRIC_SUCCESS, brix_tpc_metric_transfer(), BRIX_TPC_PROTO_WEBDAV, brix_tpc_registry_update(), BRIX_TPC_STATE_ACTIVE, BRIX_TPC_STATE_DONE, BRIX_TPC_STATE_ERROR, brix_unlink_confined_canon(), BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_COMMIT_ERROR, BRIX_WEBDAV_TPC_PULL_SUCCESS, BRIX_WEBDAV_TPC_PUSH_SUCCESS, tpc_thread_ctx_t::bytes_transferred, tpc_thread_ctx_t::conf, brix_net_target_policy_t::default_https_port, tpc_thread_ctx_t::dest_path, tpc_thread_ctx_t::existed, tpc_thread_ctx_t::http_status, tpc_thread_ctx_t::is_push, tpc_thread_ctx_t::local_path, log, tpc_thread_ctx_t::log, tpc_thread_ctx_t::n_streams, tpc_thread_ctx_t::overwrite, brix_net_target_policy_t::require_https, tpc_thread_ctx_t::root_canon, stat(), ngx_http_brix_webdav_loc_conf_t::tpc_allow_local, ngx_http_brix_webdav_loc_conf_t::tpc_allow_private, tpc_thread_ctx_t::transfer_headers, tpc_thread_ctx_t::transfer_id, tpc_thread_ctx_t::url, webdav_tpc_run_curl_pull(), webdav_tpc_run_curl_pull_multi(), and webdav_tpc_run_curl_push().
Referenced by webdav_tpc_post_thread_task().
webdav_tpc_post_thread_task()
ngx_int_t webdav_tpc_post_thread_task (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, int is_push, ngx_flag_t existed, ngx_flag_t overwrite, const char * url, const char * local_path, const char * dest_path, ngx_array_t * transfer_headers, ngx_uint_t n_streams)
Definition at line 326 of file tpc_thread.c.
References brix_tpc_registry_remove(), ngx_http_brix_webdav_loc_conf_t::common, tpc_thread_ctx_t::conf, tpc_thread_ctx_t::dest_path, tpc_thread_ctx_t::existed, tpc_thread_ctx_t::is_push, tpc_thread_ctx_t::local_path, tpc_thread_ctx_t::log, tpc_thread_ctx_t::n_streams, tpc_thread_ctx_t::overwrite, tpc_thread_ctx_t::r, tpc_thread_ctx_t::root_canon, ngx_http_brix_shared_conf_t::root_canon, ngx_http_brix_shared_conf_t::thread_pool, tpc_thread_done(), tpc_thread_func(), tpc_thread_ctx_t::transfer_headers, tpc_thread_ctx_t::transfer_id, tpc_thread_ctx_t::url, and webdav_tpc_thread_register().
Referenced by ngx_http_brix_webdav_tpc_handle_copy(), and webdav_tpc_handle_push().
webdav_tpc_thread_register()
static uint64_t webdav_tpc_thread_register (ngx_http_request_t * r, int is_push, const char * url, const char * local_path, const char * dest_path) static
Definition at line 51 of file tpc_thread.c.
References BRIX_TPC_DIR_PULL, BRIX_TPC_DIR_PUSH, BRIX_TPC_PROTO_WEBDAV, brix_tpc_registry_add(), BRIX_TPC_STATE_PENDING, brix_tpc_transfer_t::direction, brix_tpc_transfer_t::dst_path, brix_tpc_transfer_t::protocol, brix_tpc_transfer_t::src_url, and brix_tpc_transfer_t::state.
Referenced by webdav_tpc_post_thread_task().