nginx-xrootd: src/tpc/common/metrics.c File Reference
metrics.c File Reference
#include "metrics.h"
#include "observability/metrics/unified.h"
Functions
static brix_proto_t brix_tpc_metric_proto (ngx_uint_t protocol)
void brix_tpc_metric_transfer (ngx_uint_t protocol, ngx_uint_t direction, ngx_uint_t event, size_t bytes, ngx_log_t *log)
Function Documentation
brix_tpc_metric_proto()
static brix_proto_t brix_tpc_metric_proto (ngx_uint_t protocol) static
Definition at line 5 of file metrics.c.
References BRIX_PROTO_ROOT, BRIX_PROTO_WEBDAV, BRIX_TPC_PROTO_STREAM, and BRIX_TPC_PROTO_WEBDAV.
Referenced by brix_tpc_metric_transfer().
brix_tpc_metric_transfer()
void brix_tpc_metric_transfer (ngx_uint_t protocol, ngx_uint_t direction, ngx_uint_t event, size_t bytes, ngx_log_t * log)
Definition at line 17 of file metrics.c.
References BRIX_ERR_NONE, BRIX_ERR_OTHER, brix_metric_tpc(), BRIX_TPC_DIR_PUSH, BRIX_TPC_METRIC_ERROR, brix_tpc_metric_proto(), BRIX_TPC_METRIC_SUCCESS, and log.
Referenced by tpc_done_account(), tpc_marker_record_result(), tpc_thread_fail(), tpc_thread_run_pull(), tpc_thread_run_push(), webdav_tpc_commit_pulled_file(), webdav_tpc_finish_pull_success(), webdav_tpc_handle_push(), webdav_tpc_pull_start_accounting(), webdav_tpc_pull_sync_exec(), webdav_tpc_push_sync_error(), and webdav_tpc_push_sync_exec().