nginx-xrootd: src/protocols/webdav/tpc_marker_internal.h File Reference
tpc_marker_internal.h File Reference
#include "webdav.h"
#include <time.h>
Data Structures
struct tpc_marker_ctx_t
struct tpc_marker_thread_ctx_t
Macros
#define TPC_MARKER_POLL_MSEC 200u
Functions
void tpc_marker_send_all (ngx_http_request_t *r, time_t ts, tpc_marker_ctx_t *ctx)
void tpc_marker_poll (ngx_event_t *ev)
void tpc_marker_thread_done (ngx_event_t *ev)
void tpc_marker_cleanup (void *data)
Macro Definition Documentation
TPC_MARKER_POLL_MSEC
#define TPC_MARKER_POLL_MSEC 200u
Definition at line 19 of file tpc_marker_internal.h.
Function Documentation
tpc_marker_cleanup()
void tpc_marker_cleanup (void * data)
Definition at line 369 of file tpc_marker.c.
References brix_tpc_registry_request_cancel(), tpc_marker_ctx_t::is_pull, tpc_marker_ctx_t::timer, tpc_marker_ctx_t::tmp_path, and tpc_marker_ctx_t::transfer_id.
Referenced by tpc_marker_arm_lifecycle().
tpc_marker_poll()
void tpc_marker_poll (ngx_event_t * ev)
Definition at line 321 of file tpc_marker.c.
References tpc_ms_progress_t::completed, tpc_marker_ctx_t::last_marker_time, tpc_marker_ctx_t::marker_interval_secs, tpc_marker_ctx_t::progress, tpc_marker_ctx_t::r, tpc_ms_progress_t::result, tpc_marker_finish(), TPC_MARKER_POLL_MSEC, and tpc_marker_send_all().
Referenced by tpc_marker_arm_lifecycle().
tpc_marker_send_all()
void tpc_marker_send_all (ngx_http_request_t * r, time_t ts, tpc_marker_ctx_t * ctx)
Definition at line 86 of file tpc_marker.c.
References tpc_ms_progress_t::bytes_per_stream, tpc_marker_ctx_t::is_pull, tpc_ms_progress_t::n_streams, tpc_marker_ctx_t::progress, stat(), tpc_marker_ctx_t::tmp_path, and tpc_marker_send_one().
Referenced by tpc_marker_finish(), tpc_marker_poll(), and webdav_tpc_marker_start().
tpc_marker_thread_done()
void tpc_marker_thread_done (ngx_event_t * ev)
Definition at line 356 of file tpc_marker.c.
References tpc_marker_thread_ctx_t::marker_ctx, and tpc_marker_ctx_t::timer.
Referenced by tpc_marker_build_task().