nginx-xrootd: src/protocols/webdav/tpc_user_proxy.h File Reference
tpc_user_proxy.h File Reference
#include "webdav.h"
Data Structures
struct webdav_tpc_user_proxy_t
Functions
void webdav_tpc_user_proxy_resolve (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, webdav_tpc_user_proxy_t *out)
Function Documentation
webdav_tpc_user_proxy_resolve()
void webdav_tpc_user_proxy_resolve (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, webdav_tpc_user_proxy_t * out)
Definition at line 222 of file tpc_user_proxy.c.
References webdav_tpc_user_proxy_t::cert_path, webdav_tpc_user_proxy_t::deny, webdav_tpc_user_proxy_t::have, ngx_http_brix_webdav_req_ctx_t::identity, webdav_tpc_user_proxy_t::key_path, ngx_http_brix_webdav_module, webdav_tpc_user_proxy_from_passthrough(), and webdav_tpc_user_proxy_from_store().
Referenced by webdav_tpc_apply_user_proxy().