nginx-xrootd: src/tpc/outbound/bootstrap.c File Reference
bootstrap.c File Reference
#include "tpc/engine/tpc_internal.h"
#include "protocols/root/protocol/bootstrap_pack.h"
#include <string.h>
#include <stdlib.h>
Functions
void tpc_put_u32 (u_char *p, uint32_t v)
int tpc_send_kxr_auth (brix_tpc_pull_t *t, int fd, u_char seq, const u_char *cred, uint32_t len)
int tpc_bootstrap (brix_tpc_pull_t *t, int fd)
Variables
static const uint8_t tpc_bootstrap_streamid [2] = { 0, 1 }
Function Documentation
tpc_bootstrap()
int tpc_bootstrap (brix_tpc_pull_t * t, int fd)
Definition at line 27 of file bootstrap.c.
References BRIX_SESSION_ID_LEN, brix_tpc_pull_t::conf, brix_tpc_pull_t::err_msg, kXR_ableTLS, kXR_AuthFailed, kXR_authmore, kXR_gotoTLS, kXR_NotAuthorized, kXR_ok, kXR_ServerError, kXR_ver005, brix_tpc_pull_t::token_mode, tpc_bootstrap_streamid, tpc_fetch_delegated_token(), tpc_outbound_finish_login(), ngx_stream_brix_srv_conf_t::tpc_outbound_tls, tpc_recv_response(), tpc_send_all(), tpc_start_tls(), brix_tpc_pull_t::xrd_error, xrd_pack_handshake(), xrd_pack_login_request(), and xrd_pack_protocol_request().
Referenced by brix_tpc_pull_thread().
tpc_put_u32()
void tpc_put_u32 (u_char * p, uint32_t v) extern
Definition at line 35 of file gsi_outbound_common.c.
tpc_send_kxr_auth()
int tpc_send_kxr_auth (brix_tpc_pull_t * t, int fd, u_char seq, const u_char * cred, uint32_t len) extern
Definition at line 52 of file gsi_outbound_common.c.
Referenced by tpc_outbound_ztn().
Variable Documentation
tpc_bootstrap_streamid
const uint8_t tpc_bootstrap_streamid[2] = { 0, 1 } static
Definition at line 17 of file bootstrap.c.
Referenced by tpc_bootstrap().