nginx-xrootd: src/protocols/webdav/tpc_curl.c File Reference
tpc_curl.c File Reference
#include "tpc_curl_internal.h"
#include "fs/vfs/vfs.h"
Data Structures
struct webdav_tpc_curl_ctx_t
Functions
static void tpc_core_apply_tls_creds (webdav_tpc_curl_ctx_t *ctx)
static ngx_int_t tpc_core_append_headers (webdav_tpc_curl_ctx_t *ctx)
static ngx_int_t tpc_core_open_local (webdav_tpc_curl_ctx_t *ctx)
static ngx_int_t tpc_core_setup (webdav_tpc_curl_ctx_t *ctx, char *errbuf)
static ngx_int_t tpc_core_perform (webdav_tpc_curl_ctx_t *ctx, const char *errbuf)
ngx_int_t webdav_tpc_run_curl_core (ngx_log_t *log, ngx_http_brix_webdav_loc_conf_t *conf, ngx_array_t *transfer_headers, int is_push, const char *file_path, const char *url, const char *log_tag, uint64_t transfer_id, const char *user_cert, const char *user_key)
ngx_int_t webdav_tpc_run_curl_pull (ngx_log_t *log, ngx_http_brix_webdav_loc_conf_t *conf, const char *source_url, const char *tmp_path, ngx_array_t *transfer_headers, uint64_t transfer_id, const char *user_cert, const char *user_key)
ngx_int_t webdav_tpc_run_curl_push (ngx_log_t *log, ngx_http_brix_webdav_loc_conf_t *conf, const char *dest_url, const char *local_path, ngx_array_t *transfer_headers, uint64_t transfer_id)
ngx_int_t webdav_tpc_run_curl_multi_finish (ngx_int_t rc, CURLM *cm, CURL **easy, struct curl_slist **hdrs, struct curl_slist **resolve, ngx_uint_t n_streams, int fd)
static int tpc_ms_prepare_output (ngx_log_t *log, const char *tmp_path, off_t total_size)
static ngx_int_t tpc_ms_setup_stream (webdav_tpc_ms_ctx_t *ctx, ngx_uint_t i)
static ngx_int_t tpc_ms_drive (ngx_log_t *log, CURLM *cm)
static ngx_int_t tpc_ms_harvest (ngx_log_t *log, CURLM *cm)
ngx_int_t webdav_tpc_run_curl_pull_multi (ngx_log_t *log, ngx_http_brix_webdav_loc_conf_t *conf, const char *source_url, const char *tmp_path, ngx_array_t *transfer_headers, ngx_uint_t n_streams, uint64_t transfer_id, tpc_ms_progress_t *progress, const char *user_cert, const char *user_key)
Function Documentation
tpc_core_append_headers()
static ngx_int_t tpc_core_append_headers (webdav_tpc_curl_ctx_t * ctx) static
Definition at line 102 of file tpc_curl.c.
References webdav_tpc_curl_ctx_t::curl, webdav_tpc_curl_ctx_t::hdrs, webdav_tpc_curl_ctx_t::log, webdav_tpc_curl_ctx_t::log_tag, and webdav_tpc_curl_ctx_t::transfer_headers.
Referenced by tpc_core_setup().
tpc_core_apply_tls_creds()
static void tpc_core_apply_tls_creds (webdav_tpc_curl_ctx_t * ctx) static
Definition at line 62 of file tpc_curl.c.
References webdav_tpc_curl_ctx_t::conf, webdav_tpc_curl_ctx_t::curl, ngx_http_brix_webdav_loc_conf_t::tpc_cadir, ngx_http_brix_webdav_loc_conf_t::tpc_cafile, ngx_http_brix_webdav_loc_conf_t::tpc_cert, ngx_http_brix_webdav_loc_conf_t::tpc_key, webdav_tpc_curl_ctx_t::user_cert, and webdav_tpc_curl_ctx_t::user_key.
Referenced by tpc_core_setup().
tpc_core_open_local()
static ngx_int_t tpc_core_open_local (webdav_tpc_curl_ctx_t * ctx) static
Definition at line 143 of file tpc_curl.c.
References brix_vfs_open_fd(), close(), ngx_http_brix_webdav_loc_conf_t::common, webdav_tpc_curl_ctx_t::conf, webdav_tpc_curl_ctx_t::curl, webdav_tpc_curl_ctx_t::file_path, webdav_tpc_curl_ctx_t::fp, fstat(), webdav_tpc_curl_ctx_t::is_push, webdav_tpc_curl_ctx_t::log, ngx_http_brix_shared_conf_t::root_canon, and stat().
Referenced by tpc_core_setup().
tpc_core_perform()
static ngx_int_t tpc_core_perform (webdav_tpc_curl_ctx_t * ctx, const char * errbuf) static
Definition at line 291 of file tpc_curl.c.
References webdav_tpc_curl_ctx_t::curl, webdav_tpc_curl_ctx_t::log, and webdav_tpc_curl_ctx_t::log_tag.
Referenced by webdav_tpc_run_curl_core().
tpc_core_setup()
static ngx_int_t tpc_core_setup (webdav_tpc_curl_ctx_t * ctx, char * errbuf) static
Definition at line 209 of file tpc_curl.c.
References webdav_tpc_curl_ctx_t::conf, webdav_tpc_curl_ctx_t::curl, webdav_tpc_curl_ctx_t::is_push, webdav_tpc_curl_ctx_t::log, webdav_tpc_curl_ctx_t::log_tag, webdav_tpc_curl_ctx_t::resolve, tpc_core_append_headers(), tpc_core_apply_tls_creds(), tpc_core_open_local(), tpc_curl_apply_stall_bounds(), tpc_curl_secure(), ngx_http_brix_webdav_loc_conf_t::tpc_timeout, webdav_tpc_curl_ctx_t::transfer_id, webdav_tpc_curl_ctx_t::url, and webdav_tpc_curl_progress().
Referenced by webdav_tpc_run_curl_core().
tpc_ms_drive()
static ngx_int_t tpc_ms_drive (ngx_log_t * log, CURLM * cm) static
Definition at line 558 of file tpc_curl.c.
References log.
Referenced by webdav_tpc_run_curl_pull_multi().
tpc_ms_harvest()
static ngx_int_t tpc_ms_harvest (ngx_log_t * log, CURLM * cm) static
Definition at line 588 of file tpc_curl.c.
References log.
Referenced by webdav_tpc_run_curl_pull_multi().
tpc_ms_prepare_output()
static int tpc_ms_prepare_output (ngx_log_t * log, const char * tmp_path, off_t total_size) static
Definition at line 459 of file tpc_curl.c.
References brix_sd_posix_driver, brix_sd_posix_wrap(), close(), log, and open().
Referenced by webdav_tpc_run_curl_pull_multi().
tpc_ms_setup_stream()
static ngx_int_t tpc_ms_setup_stream (webdav_tpc_ms_ctx_t * ctx, ngx_uint_t i) static
Definition at line 503 of file tpc_curl.c.
References webdav_tpc_ms_ctx_t::cm, webdav_tpc_ms_ctx_t::conf, ms_stream_ctx_t::cur_offset, webdav_tpc_ms_ctx_t::easy, ms_stream_ctx_t::fd, webdav_tpc_ms_ctx_t::fd, webdav_tpc_ms_ctx_t::hdrs, webdav_tpc_ms_ctx_t::log, ms_write_cb(), webdav_tpc_ms_ctx_t::n_streams, ms_stream_ctx_t::progress, webdav_tpc_ms_ctx_t::progress, webdav_tpc_ms_ctx_t::resolve, webdav_tpc_ms_ctx_t::source_url, ms_stream_ctx_t::stream_idx, webdav_tpc_ms_ctx_t::tmp_path, webdav_tpc_ms_ctx_t::total_size, tpc_curl_apply_conf(), webdav_tpc_ms_ctx_t::transfer_headers, webdav_tpc_ms_ctx_t::user_cert, webdav_tpc_ms_ctx_t::user_key, webdav_tpc_pmark_attach(), and webdav_tpc_ms_ctx_t::write_ctx.
Referenced by webdav_tpc_run_curl_pull_multi().
webdav_tpc_run_curl_core()
ngx_int_t webdav_tpc_run_curl_core (ngx_log_t * log, ngx_http_brix_webdav_loc_conf_t * conf, ngx_array_t * transfer_headers, int is_push, const char * file_path, const char * url, const char * log_tag, uint64_t transfer_id, const char * user_cert, const char * user_key)
Definition at line 321 of file tpc_curl.c.
References BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_CURL_STARTED, webdav_tpc_curl_ctx_t::conf, webdav_tpc_curl_ctx_t::curl, webdav_tpc_curl_ctx_t::file_path, webdav_tpc_curl_ctx_t::fp, webdav_tpc_curl_ctx_t::hdrs, webdav_tpc_curl_ctx_t::is_push, log, webdav_tpc_curl_ctx_t::log, webdav_tpc_curl_ctx_t::log_tag, webdav_tpc_curl_ctx_t::resolve, tpc_core_perform(), tpc_core_setup(), webdav_tpc_curl_ctx_t::transfer_headers, webdav_tpc_curl_ctx_t::transfer_id, webdav_tpc_curl_ctx_t::url, webdav_tpc_curl_ctx_t::user_cert, webdav_tpc_curl_ctx_t::user_key, webdav_tpc_curl_finish(), and webdav_tpc_pmark_attach().
Referenced by webdav_tpc_run_curl_pull(), and webdav_tpc_run_curl_push().
webdav_tpc_run_curl_multi_finish()
ngx_int_t webdav_tpc_run_curl_multi_finish (ngx_int_t rc, CURLM * cm, CURL ** easy, struct curl_slist ** hdrs, struct curl_slist ** resolve, ngx_uint_t n_streams, int fd)
Definition at line 418 of file tpc_curl.c.
References BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_CURL_ERROR, BRIX_WEBDAV_TPC_CURL_SUCCESS, and close().
Referenced by webdav_tpc_run_curl_pull_multi().
webdav_tpc_run_curl_pull()
ngx_int_t webdav_tpc_run_curl_pull (ngx_log_t * log, ngx_http_brix_webdav_loc_conf_t * conf, const char * source_url, const char * tmp_path, ngx_array_t * transfer_headers, uint64_t transfer_id, const char * user_cert, const char * user_key)
Definition at line 379 of file tpc_curl.c.
References log, and webdav_tpc_run_curl_core().
Referenced by tpc_marker_thread_func(), tpc_thread_pull_fetch(), webdav_tpc_pull_sync_exec(), and webdav_tpc_run_curl_pull_multi().
webdav_tpc_run_curl_pull_multi()
ngx_int_t webdav_tpc_run_curl_pull_multi (ngx_log_t * log, ngx_http_brix_webdav_loc_conf_t * conf, const char * source_url, const char * tmp_path, ngx_array_t * transfer_headers, ngx_uint_t n_streams, uint64_t transfer_id, tpc_ms_progress_t * progress, const char * user_cert, const char * user_key)
Definition at line 628 of file tpc_curl.c.
References BRIX_TPC_MAX_STREAMS, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_CURL_STARTED, close(), webdav_tpc_ms_ctx_t::cm, webdav_tpc_ms_ctx_t::conf, webdav_tpc_ms_ctx_t::easy, webdav_tpc_ms_ctx_t::fd, webdav_tpc_ms_ctx_t::hdrs, log, webdav_tpc_ms_ctx_t::log, webdav_tpc_ms_ctx_t::n_streams, webdav_tpc_ms_ctx_t::progress, webdav_tpc_ms_ctx_t::resolve, webdav_tpc_ms_ctx_t::source_url, webdav_tpc_ms_ctx_t::tmp_path, webdav_tpc_ms_ctx_t::total_size, tpc_ms_progress_t::total_size, tpc_curl_head_size(), tpc_ms_drive(), tpc_ms_harvest(), tpc_ms_prepare_output(), tpc_ms_setup_stream(), webdav_tpc_ms_ctx_t::transfer_headers, webdav_tpc_ms_ctx_t::user_cert, webdav_tpc_ms_ctx_t::user_key, webdav_tpc_run_curl_multi_finish(), webdav_tpc_run_curl_pull(), and webdav_tpc_ms_ctx_t::write_ctx.
Referenced by tpc_marker_thread_func(), and tpc_thread_pull_fetch().
webdav_tpc_run_curl_push()
ngx_int_t webdav_tpc_run_curl_push (ngx_log_t * log, ngx_http_brix_webdav_loc_conf_t * conf, const char * dest_url, const char * local_path, ngx_array_t * transfer_headers, uint64_t transfer_id)
Definition at line 393 of file tpc_curl.c.
References log, and webdav_tpc_run_curl_core().
Referenced by tpc_marker_thread_func(), tpc_thread_run_push(), and webdav_tpc_push_sync_exec().