nginx-xrootd: src/tpc/outbound/tpc_token.c File Reference
tpc_token.c File Reference
#include "tpc/engine/tpc_internal.h"
#include "auth/token/file.h"
#include "auth/token/oauth2.h"
#include "core/compat/subprocess.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <sys/wait.h>
#include <ctype.h>
Macros
#define TPC_TOKEN_MAX_LEN 65536
#define TPC_TOKEN_HELPER_PATH "/usr/local/sbin/nginx-xrootd-tpc-token"
Functions
static void tpc_trim_trailing (char *s)
static int tpc_token_parse_access_token (const char *json, char *out, size_t out_sz)
static int tpc_token_validate_delegated (brix_tpc_pull_t *t)
static const char * resolve_oidc_token_binary (void)
static int tpc_token_oidc_agent (brix_tpc_pull_t *t, char *token_out, size_t token_out_sz)
static int tpc_token_rfc8693 (brix_tpc_pull_t *t, char *token_out, size_t token_out_sz)
int tpc_fetch_delegated_token (brix_tpc_pull_t *t)
Macro Definition Documentation
TPC_TOKEN_HELPER_PATH
#define TPC_TOKEN_HELPER_PATH "/usr/local/sbin/nginx-xrootd-tpc-token"
Definition at line 33 of file tpc_token.c.
TPC_TOKEN_MAX_LEN
#define TPC_TOKEN_MAX_LEN 65536
Definition at line 32 of file tpc_token.c.
Function Documentation
resolve_oidc_token_binary()
static const char * resolve_oidc_token_binary (void) static
Definition at line 123 of file tpc_token.c.
References access().
Referenced by tpc_token_oidc_agent().
tpc_fetch_delegated_token()
int tpc_fetch_delegated_token (brix_tpc_pull_t * t)
Definition at line 439 of file tpc_token.c.
References brix_tpc_pull_t::conf, brix_tpc_pull_t::delegated_token, brix_tpc_pull_t::err_msg, kXR_ArgInvalid, brix_tpc_pull_t::token_mode, ngx_stream_brix_srv_conf_t::tpc_outbound_token_endpoint, tpc_token_oidc_agent(), tpc_token_rfc8693(), tpc_token_validate_delegated(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_bootstrap().
tpc_token_oidc_agent()
static int tpc_token_oidc_agent (brix_tpc_pull_t * t, char * token_out, size_t token_out_sz) static
Definition at line 146 of file tpc_token.c.
References close(), brix_tpc_pull_t::err_msg, kXR_AuthFailed, kXR_ServerError, ngx_memcpy, read(), resolve_oidc_token_binary(), TPC_TOKEN_HELPER_PATH, TPC_TOKEN_MAX_LEN, tpc_token_parse_access_token(), tpc_trim_trailing(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_fetch_delegated_token().
tpc_token_parse_access_token()
static int tpc_token_parse_access_token (const char * json, char * out, size_t out_sz) static
Definition at line 62 of file tpc_token.c.
References brix_oauth2_parse_access_token().
Referenced by tpc_token_oidc_agent(), and tpc_token_rfc8693().
tpc_token_rfc8693()
static int tpc_token_rfc8693 (brix_tpc_pull_t * t, char * token_out, size_t token_out_sz) static
Definition at line 285 of file tpc_token.c.
References brix_subprocess_capture(), brix_token_read_file(), close(), brix_tpc_pull_t::conf, brix_tpc_pull_t::err_msg, kXR_ArgInvalid, kXR_AuthFailed, kXR_IOError, kXR_ServerError, ngx_memcpy, brix_tpc_pull_t::src_host, brix_tpc_pull_t::token_scope, ngx_stream_brix_srv_conf_t::tpc_outbound_bearer_file, ngx_stream_brix_srv_conf_t::tpc_outbound_client_id, ngx_stream_brix_srv_conf_t::tpc_outbound_client_secret, ngx_stream_brix_srv_conf_t::tpc_outbound_token_endpoint, TPC_TOKEN_MAX_LEN, tpc_token_parse_access_token(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_fetch_delegated_token().
tpc_token_validate_delegated()
static int tpc_token_validate_delegated (brix_tpc_pull_t * t) static
Definition at line 87 of file tpc_token.c.
References brix_tpc_credential_parse(), BRIX_TPC_CREDENTIAL_TOKEN, brix_tpc_credential_validate(), brix_tpc_pull_t::c, brix_tpc_pull_t::delegated_token, brix_tpc_pull_t::err_msg, kXR_AuthFailed, and brix_tpc_pull_t::xrd_error.
Referenced by tpc_fetch_delegated_token().
tpc_trim_trailing()
static void tpc_trim_trailing (char * s) static
Definition at line 40 of file tpc_token.c.
References s.
Referenced by tpc_token_oidc_agent().