nginx-xrootd: src/protocols/webdav/tpc_cred_exchange.c File Reference
tpc_cred_exchange.c File Reference
#include "tpc_cred_internal.h"
#include "tpc_config.h"
#include "webdav.h"
#include "core/compat/log_diag.h"
#include "tpc/common/credential.h"
#include "core/compat/subprocess.h"
#include <nginx.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include <ngx_config.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <fcntl.h>
Functions
ngx_int_t tpc_cred_rfc8693_exchange (ngx_http_request_t *r, const char *subject_token, const char *source_url, const char *scope, const char *token_endpoint, const char *client_id, const char *client_secret, ngx_str_t *token_out)
Perform an RFC 8693 token-exchange request.
Function Documentation
tpc_cred_rfc8693_exchange()
ngx_int_t tpc_cred_rfc8693_exchange (ngx_http_request_t * r, const char * subject_token, const char * source_url, const char * scope, const char * token_endpoint, const char * client_id, const char * client_secret, ngx_str_t * token_out)
Perform an RFC 8693 token-exchange request.
Sends a POST to the configured token endpoint with: grant_type=urn:ietf:params:oauth:grant-type:token-exchange subject_token=<JWT> resource=<source_url> audience=<source_url> scope=<scope>
Uses a fork/exec'd curl subprocess (same pattern as tpc_curl.c).
Definition at line 48 of file tpc_cred_exchange.c.
References brix_subprocess_capture(), close(), scope, TPC_CRED_MAX_TOKEN_LEN, and tpc_cred_parse_token_response().
Referenced by tpc_cred_run_token_exchange().