nginx-xrootd: src/tpc/outbound/tpc_token_exchange.c File Reference
tpc_token_exchange.c File Reference
#include "tpc/engine/tpc_internal.h"
#include "tpc/outbound/tpc_token_internal.h"
#include "auth/token/file.h"
#include "core/compat/subprocess.h"
#include "core/compat/cred_stage.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <sys/wait.h>
#include <openssl/crypto.h>
Macros
#define TPC_TOKEN_MAX_LEN 65536
Functions
static int tpc_rfc8693_read_subject (brix_tpc_pull_t *t, char *subject_token, size_t subject_token_sz)
static int tpc_rfc8693_stage_body (brix_tpc_pull_t *t, const char *subject_token, char *body_file, size_t body_file_sz)
static void tpc_rfc8693_build_argv (brix_tpc_pull_t *t, char **curl_argv, const char *body_file)
static int tpc_rfc8693_run_curl (brix_tpc_pull_t *t, char **curl_argv, const char *body_file, char *buf, size_t bufsz)
int tpc_token_rfc8693 (brix_tpc_pull_t *t, char *token_out, size_t token_out_sz)
Macro Definition Documentation
TPC_TOKEN_MAX_LEN
#define TPC_TOKEN_MAX_LEN 65536
Definition at line 36 of file tpc_token_exchange.c.
Function Documentation
tpc_rfc8693_build_argv()
static void tpc_rfc8693_build_argv (brix_tpc_pull_t * t, char ** curl_argv, const char * body_file) static
Definition at line 134 of file tpc_token_exchange.c.
References brix_tpc_pull_t::conf.
Referenced by tpc_token_rfc8693().
tpc_rfc8693_read_subject()
static int tpc_rfc8693_read_subject (brix_tpc_pull_t * t, char * subject_token, size_t subject_token_sz) static
Definition at line 47 of file tpc_token_exchange.c.
References brix_token_read_file(), brix_tpc_pull_t::conf, brix_tpc_pull_t::err_msg, kXR_ArgInvalid, kXR_IOError, and brix_tpc_pull_t::xrd_error.
Referenced by tpc_token_rfc8693().
tpc_rfc8693_run_curl()
static int tpc_rfc8693_run_curl (brix_tpc_pull_t * t, char ** curl_argv, const char * body_file, char * buf, size_t bufsz) static
Definition at line 184 of file tpc_token_exchange.c.
References brix_subprocess_capture(), brix_tpc_pull_t::err_msg, kXR_AuthFailed, kXR_ServerError, and brix_tpc_pull_t::xrd_error.
Referenced by tpc_token_rfc8693().
tpc_rfc8693_stage_body()
static int tpc_rfc8693_stage_body (brix_tpc_pull_t * t, const char * subject_token, char * body_file, size_t body_file_sz) static
Definition at line 85 of file tpc_token_exchange.c.
References brix_cred_stage_write(), brix_tpc_pull_t::err_msg, kXR_IOError, brix_tpc_pull_t::src_host, brix_tpc_pull_t::token_scope, and brix_tpc_pull_t::xrd_error.
Referenced by tpc_token_rfc8693().
tpc_token_rfc8693()
int tpc_token_rfc8693 (brix_tpc_pull_t * t, char * token_out, size_t token_out_sz)
Definition at line 223 of file tpc_token_exchange.c.
References kXR_AuthFailed, tpc_rfc8693_build_argv(), tpc_rfc8693_read_subject(), tpc_rfc8693_run_curl(), tpc_rfc8693_stage_body(), TPC_TOKEN_MAX_LEN, tpc_token_parse_access_token(), and brix_tpc_pull_t::xrd_error.
Referenced by tpc_fetch_delegated_token().