nginx-xrootd: src/protocols/webdav/tpc.c File Reference
tpc.c File Reference
#include "webdav.h"
#include "fs/path/path.h"
#include "fs/vfs/vfs.h"
#include "core/http/http_headers.h"
#include "core/compat/staged_file.h"
#include "observability/dashboard/dashboard_tracking.h"
#include "observability/sesslog/sesslog_ngx.h"
#include "fs/xfer/xfer.h"
#include "tpc/common/auth.h"
#include "tpc/common/metrics.h"
#include "tpc/common/registry.h"
#include <fcntl.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Functions
static ngx_int_t webdav_tpc_probe (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const char *path, struct stat *sb)
static const char * webdav_dashboard_identity (ngx_http_request_t *r)
static brix_identity_t * webdav_tpc_request_identity (ngx_http_request_t *r)
static void webdav_tpc_note_client_copy_xfer (ngx_http_request_t *r, off_t bytes, int64_t expected)
static void webdav_tpc_url_path (const char *url, ngx_str_t *out)
static ngx_int_t webdav_tpc_authorize (ngx_http_request_t *r, const ngx_str_t *src_path, const ngx_str_t *dst_path)
static uint64_t webdav_tpc_register_transfer (ngx_http_request_t *r, ngx_uint_t direction, const char *src, const char *dst, off_t bytes_total)
static ngx_int_t webdav_tpc_extract_subject_token (ngx_http_request_t *r, ngx_table_elt_t *auth_hdr, const char **subject_token)
static ngx_int_t webdav_tpc_handle_push (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_table_elt_t *dest_hdr)
static ngx_int_t webdav_tpc_apply_credential_delegation (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const char *source_url, ngx_array_t *transfer_headers)
WHAT: Handle HTTP-TPC (Third-Party Copy) COPY requests — implements GridFTP-style cross-server file transfer layered on WebDAV.
ngx_int_t ngx_http_brix_webdav_tpc_handle_copy (ngx_http_request_t *r)
Function Documentation
ngx_http_brix_webdav_tpc_handle_copy()
ngx_int_t ngx_http_brix_webdav_tpc_handle_copy (ngx_http_request_t * r)
Definition at line 551 of file tpc.c.
References brix_dashboard_http_add(), brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_dashboard_http_start_identity(), brix_dashboard_http_tpc_remote(), brix_link_confined_canon(), brix_log_safe_path(), brix_staged_abort(), brix_staged_commit(), brix_staged_open(), BRIX_TPC_DIR_PULL, BRIX_TPC_METRIC_ERROR, BRIX_TPC_METRIC_STARTED, BRIX_TPC_METRIC_SUCCESS, brix_tpc_metric_transfer(), BRIX_TPC_PROTO_WEBDAV, brix_tpc_registry_remove(), brix_tpc_registry_update(), BRIX_TPC_STATE_DONE, BRIX_TPC_STATE_ERROR, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_BAD_REQUEST, BRIX_WEBDAV_TPC_COMMIT_ERROR, BRIX_WEBDAV_TPC_PULL_STARTED, BRIX_WEBDAV_TPC_PULL_SUCCESS, BRIX_XFER_DIR_TPC, brix_xfer_finish(), BRIX_XFER_OK, BRIX_XFER_PROTO_WEBDAV, BRIX_XFER_SRC_ERR, BRIX_XFER_TPC, ngx_http_brix_webdav_loc_conf_t::common, brix_staged_file_t::fd, ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), ngx_http_brix_shared_conf_t::root_canon, stat(), brix_staged_file_t::tmp_path, ngx_http_brix_webdav_loc_conf_t::tpc_marker_interval, ngx_http_brix_webdav_loc_conf_t::tpc_max_streams, webdav_dashboard_identity(), WEBDAV_MAX_PATH, webdav_send_no_body(), webdav_tpc_apply_credential_delegation(), webdav_tpc_authorize(), webdav_tpc_collect_transfer_headers(), webdav_tpc_find_header, webdav_tpc_handle_push(), webdav_tpc_header_value_equals, webdav_tpc_marker_start(), webdav_tpc_note_client_copy_xfer(), webdav_tpc_post_thread_task(), webdav_tpc_probe(), webdav_tpc_pstrndup0(), webdav_tpc_register_transfer(), webdav_tpc_run_curl_pull(), webdav_tpc_str_has_ctl, and webdav_tpc_url_path().
Referenced by webdav_dispatch_inner().
webdav_dashboard_identity()
static const char * webdav_dashboard_identity (ngx_http_request_t * r) static
Definition at line 55 of file tpc.c.
References ngx_http_brix_webdav_req_ctx_t::dn, and ngx_http_brix_webdav_module.
Referenced by ngx_http_brix_webdav_tpc_handle_copy(), and webdav_tpc_handle_push().
webdav_tpc_apply_credential_delegation()
static ngx_int_t webdav_tpc_apply_credential_delegation (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const char * source_url, ngx_array_t * transfer_headers) static
WHAT: Handle HTTP-TPC (Third-Party Copy) COPY requests — implements GridFTP-style cross-server file transfer layered on WebDAV.
Supports two modes: pull (fetch remote → local) and push (local → upload remote). Both modes use external curl process to perform the actual data transfer while nginx handles authentication, path confinement, and HTTP header management. Returns 201 Created for new files or 204 No Content for overwrites on pull; 201 Created on push success. Rejects requests with ambiguous headers (both Source + Destination present) or missing required headers via 400 Bad Request. Uses temporary file staging (<path>.nginx-xrootd-tpc.<pid>.<time>) for pull mode to ensure atomic commit — rename/link on success, unlink on failure.
Definition at line 474 of file tpc.c.
References BRIX_TPC_CRED_UNKNOWN, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_BAD_REQUEST, mode, ngx_memcpy, ngx_pnalloc(), ngx_http_brix_tpc_conf_t::token_scope, ngx_http_brix_webdav_loc_conf_t::tpc_cred, webdav_tpc_cred_obtain_token(), webdav_tpc_cred_parse_mode(), webdav_tpc_extract_subject_token(), webdav_tpc_find_header, and webdav_tpc_header_value_equals.
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_authorize()
static ngx_int_t webdav_tpc_authorize (ngx_http_request_t * r, const ngx_str_t * src_path, const ngx_str_t * dst_path) static
Definition at line 134 of file tpc.c.
References brix_tpc_check_authz(), BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_BAD_REQUEST, and webdav_tpc_request_identity().
Referenced by ngx_http_brix_webdav_tpc_handle_copy(), and webdav_tpc_handle_push().
webdav_tpc_extract_subject_token()
static ngx_int_t webdav_tpc_extract_subject_token (ngx_http_request_t * r, ngx_table_elt_t * auth_hdr, const char ** subject_token) static
Definition at line 191 of file tpc.c.
References brix_http_extract_bearer(), and webdav_tpc_pstrndup0().
Referenced by webdav_tpc_apply_credential_delegation(), and webdav_tpc_handle_push().
webdav_tpc_handle_push()
static ngx_int_t webdav_tpc_handle_push (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_table_elt_t * dest_hdr) static
Definition at line 232 of file tpc.c.
References brix_dashboard_http_add(), brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_dashboard_http_start_identity(), brix_dashboard_http_tpc_remote(), BRIX_TPC_CRED_UNKNOWN, BRIX_TPC_DIR_PUSH, BRIX_TPC_METRIC_ERROR, BRIX_TPC_METRIC_STARTED, BRIX_TPC_METRIC_SUCCESS, brix_tpc_metric_transfer(), BRIX_TPC_PROTO_WEBDAV, brix_tpc_registry_remove(), brix_tpc_registry_update(), BRIX_TPC_STATE_DONE, BRIX_TPC_STATE_ERROR, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_BAD_REQUEST, BRIX_WEBDAV_TPC_PUSH_STARTED, BRIX_WEBDAV_TPC_PUSH_SUCCESS, BRIX_XFER_DIR_TPC, BRIX_XFER_DST_ERR, brix_xfer_finish(), BRIX_XFER_OK, BRIX_XFER_PROTO_WEBDAV, BRIX_XFER_TPC, mode, ngx_memcpy, ngx_pnalloc(), stat(), ngx_http_brix_tpc_conf_t::token_scope, ngx_http_brix_webdav_loc_conf_t::tpc_cred, webdav_dashboard_identity(), WEBDAV_MAX_PATH, webdav_resolve_stat(), webdav_send_no_body(), webdav_tpc_authorize(), webdav_tpc_collect_transfer_headers(), webdav_tpc_cred_obtain_token(), webdav_tpc_cred_parse_mode(), webdav_tpc_extract_subject_token(), webdav_tpc_find_header, webdav_tpc_header_value_equals, webdav_tpc_note_client_copy_xfer(), webdav_tpc_post_thread_task(), webdav_tpc_pstrndup0(), webdav_tpc_register_transfer(), webdav_tpc_run_curl_push(), and webdav_tpc_str_has_ctl.
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_note_client_copy_xfer()
static void webdav_tpc_note_client_copy_xfer (ngx_http_request_t * r, off_t bytes, int64_t expected) static
Definition at line 75 of file tpc.c.
References brix_sess_xfer_add(), brix_sess_xfer_t::bytes, brix_sess_xfer_t::expected, ngx_http_brix_webdav_module, ngx_http_brix_webdav_req_ctx_t::sess_xfer, and ngx_http_brix_webdav_req_ctx_t::sess_xfer_started.
Referenced by ngx_http_brix_webdav_tpc_handle_copy(), and webdav_tpc_handle_push().
webdav_tpc_probe()
static ngx_int_t webdav_tpc_probe (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const char * path, struct stat * sb) static
Definition at line 26 of file tpc.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_WEBDAV, brix_vfs_ctx_init(), brix_vfs_probe(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::identity, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, ngx_http_brix_webdav_module, brix_vfs_ctx_t::pool, ngx_http_brix_shared_conf_t::root_canon, and brix_vfs_stat_t::size.
Referenced by ngx_http_brix_webdav_tpc_handle_copy().
webdav_tpc_register_transfer()
static uint64_t webdav_tpc_register_transfer (ngx_http_request_t * r, ngx_uint_t direction, const char * src, const char * dst, off_t bytes_total) static
Definition at line 155 of file tpc.c.
References BRIX_TPC_PROTO_WEBDAV, brix_tpc_registry_add(), BRIX_TPC_STATE_PENDING, brix_tpc_transfer_t::bytes_total, brix_tpc_transfer_t::direction, brix_tpc_transfer_t::dst_path, brix_tpc_transfer_t::protocol, brix_tpc_transfer_t::src_url, and brix_tpc_transfer_t::state.
Referenced by ngx_http_brix_webdav_tpc_handle_copy(), and webdav_tpc_handle_push().
webdav_tpc_request_identity()
static brix_identity_t * webdav_tpc_request_identity (ngx_http_request_t * r) static
Definition at line 66 of file tpc.c.
References ngx_http_brix_webdav_req_ctx_t::identity, and ngx_http_brix_webdav_module.
Referenced by webdav_tpc_authorize().
webdav_tpc_url_path()
static void webdav_tpc_url_path (const char * url, ngx_str_t * out) static
Definition at line 103 of file tpc.c.
References scheme.
Referenced by ngx_http_brix_webdav_tpc_handle_copy().