nginx-xrootd: src/protocols/webdav/tpc_curl_setup.c File Reference
tpc_curl_setup.c File Reference
#include "tpc_curl_internal.h"
Functions
int tpc_curl_secure (CURL *curl, ngx_http_brix_webdav_loc_conf_t *conf, const char *url, ngx_log_t *log, struct curl_slist **resolve_out)
void tpc_curl_apply_stall_bounds (CURL *curl, ngx_http_brix_webdav_loc_conf_t *conf)
static void tpc_curl_apply_client_cred (CURL *curl, ngx_http_brix_webdav_loc_conf_t *conf, const char *user_cert, const char *user_key)
int tpc_curl_apply_conf (CURL *curl, ngx_http_brix_webdav_loc_conf_t *conf, const char *url, ngx_array_t *transfer_headers, ngx_log_t *log, const char *user_cert, const char *user_key, struct curl_slist **hdrs_out, struct curl_slist **resolve_out)
off_t tpc_curl_head_size (ngx_log_t *log, ngx_http_brix_webdav_loc_conf_t *conf, const char *url, ngx_array_t *transfer_headers, const char *user_cert, const char *user_key)
Function Documentation
tpc_curl_apply_client_cred()
static void tpc_curl_apply_client_cred (CURL * curl, ngx_http_brix_webdav_loc_conf_t * conf, const char * user_cert, const char * user_key) static
Definition at line 139 of file tpc_curl_setup.c.
References ngx_http_brix_webdav_loc_conf_t::tpc_cert, and ngx_http_brix_webdav_loc_conf_t::tpc_key.
Referenced by tpc_curl_apply_conf().
tpc_curl_apply_conf()
int tpc_curl_apply_conf (CURL * curl, ngx_http_brix_webdav_loc_conf_t * conf, const char * url, ngx_array_t * transfer_headers, ngx_log_t * log, const char * user_cert, const char * user_key, struct curl_slist ** hdrs_out, struct curl_slist ** resolve_out)
Definition at line 159 of file tpc_curl_setup.c.
References log, ngx_http_brix_webdav_loc_conf_t::tpc_cadir, ngx_http_brix_webdav_loc_conf_t::tpc_cafile, tpc_curl_apply_client_cred(), tpc_curl_apply_stall_bounds(), tpc_curl_secure(), and ngx_http_brix_webdav_loc_conf_t::tpc_timeout.
Referenced by tpc_curl_head_size(), and tpc_ms_setup_stream().
tpc_curl_apply_stall_bounds()
void tpc_curl_apply_stall_bounds (CURL * curl, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 106 of file tpc_curl_setup.c.
References BRIX_TPC_CONNECT_TIMEOUT_SECS, ngx_http_brix_webdav_loc_conf_t::tpc_low_speed_bytes, and ngx_http_brix_webdav_loc_conf_t::tpc_low_speed_secs.
Referenced by tpc_core_setup(), and tpc_curl_apply_conf().
tpc_curl_head_size()
off_t tpc_curl_head_size (ngx_log_t * log, ngx_http_brix_webdav_loc_conf_t * conf, const char * url, ngx_array_t * transfer_headers, const char * user_cert, const char * user_key)
Definition at line 224 of file tpc_curl_setup.c.
References log, and tpc_curl_apply_conf().
Referenced by webdav_tpc_run_curl_pull_multi().
tpc_curl_secure()
int tpc_curl_secure (CURL * curl, ngx_http_brix_webdav_loc_conf_t * conf, const char * url, ngx_log_t * log, struct curl_slist ** resolve_out)
Definition at line 27 of file tpc_curl_setup.c.
References brix_net_target_policy_t::allow_local, brix_net_target_policy_t::allow_private, brix_format_host(), brix_net_target_check_dns_pin(), brix_net_target_parse(), brix_net_target_policy_t::default_https_port, brix_net_target_t::has_port, brix_net_target_t::host, log, ngx_memcpy, port, brix_net_target_t::port, brix_net_target_policy_t::require_https, ngx_http_brix_webdav_loc_conf_t::tpc_allow_local, and ngx_http_brix_webdav_loc_conf_t::tpc_allow_private.
Referenced by tpc_core_setup(), and tpc_curl_apply_conf().