nginx-xrootd: src/observability/metrics/tracking.c File Reference
tracking.c File Reference
#include "metrics_internal.h"
#include "core/config/config.h"
#include "core/fnv.h"
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
Functions
static uint32_t brix_fnv1a_hash (const void *data, size_t len)
ngx_int_t brix_track_vo_activity (ngx_brix_metrics_t *shm, const char *vo_name, size_t bytes_tx, size_t bytes_rx)
ngx_int_t brix_track_unique_user (ngx_brix_metrics_t *shm, const char *identity, size_t identity_len)
Function Documentation
brix_fnv1a_hash()
static uint32_t brix_fnv1a_hash (const void * data, size_t len) inline static
Definition at line 24 of file tracking.c.
References BRIX_FNV1A32_OFFSET_BASIS, and BRIX_FNV1A32_PRIME.
Referenced by brix_track_unique_user().
brix_track_unique_user()
ngx_int_t brix_track_unique_user (ngx_brix_metrics_t * shm, const char * identity, size_t identity_len)
Definition at line 109 of file tracking.c.
References BRIX_ATOMIC_DEC, BRIX_ATOMIC_INC, brix_fnv1a_hash(), BRIX_USERS_MAX_TRACKED, ngx_brix_user_global_t::evictions_total, ngx_brix_user_slot_t::first_seen, ngx_brix_user_slot_t::id_hash, ngx_brix_user_slot_t::sessions_total, ngx_brix_user_global_t::slots, ngx_brix_user_global_t::total_unique, ngx_brix_user_global_t::unique_count, and ngx_brix_metrics_t::user_tracking.
Referenced by brix_gsi_complete_auth(), brix_unix_track_identity(), sss_track_metrics(), and tokenauth_bind_session().
brix_track_vo_activity()
ngx_int_t brix_track_vo_activity (ngx_brix_metrics_t * shm, const char * vo_name, size_t bytes_tx, size_t bytes_rx)
Definition at line 41 of file tracking.c.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, BRIX_VO_MAX_TRACKED, BRIX_VO_NAME_LEN, ngx_brix_vo_slot_t::bytes_rx_total, ngx_brix_vo_slot_t::bytes_tx_total, ngx_brix_vo_slot_t::name, ngx_memcpy, ngx_brix_vo_global_t::overflow_total, ngx_brix_vo_slot_t::requests_total, ngx_brix_vo_global_t::slot_count, ngx_brix_vo_global_t::slots, and ngx_brix_metrics_t::vo_global.
Referenced by brix_gsi_complete_auth(), brix_unix_track_identity(), sss_track_metrics(), and tokenauth_bind_session().