nginx-xrootd: client/lib/observability/trace.c File Reference
trace.c File Reference
#include "brix.h"
#include "core/compat/kxr_names.h"
#include "protocols/root/protocol/frame_hdr.h"
#include <arpa/inet.h>
#include <string.h>
#include <time.h>
Functions
const char * brix_reqid_name (int reqid)
const char * brix_status_name (int status)
uint64_t brix_mono_ns (void)
unsigned brix_jitter_ms (unsigned span_ms)
static void hexdump (const uint8_t *buf, uint32_t n)
static void brix_trace_error (int dir, uint16_t sid, const uint8_t *b, uint32_t blen)
static void brix_trace_redirect (int dir, uint16_t sid, const uint8_t *b, uint32_t blen)
static void brix_trace_wait (int dir, uint16_t sid, const uint8_t *b)
static void brix_trace_response (int dir, uint16_t sid, int code, uint32_t dlen, const uint8_t *b, uint32_t blen)
void brix_trace_frame (brix_conn *c, int dir, uint16_t sid, int code, int is_request, uint32_t dlen, const void *body, uint32_t blen)
void brix_timing_report (const brix_conn *c)
Function Documentation
brix_jitter_ms()
unsigned brix_jitter_ms (unsigned span_ms)
Definition at line 57 of file trace.c.
References brix_mono_ns().
Referenced by copy_one_with_retry(), and rt_handle_wait().
brix_mono_ns()
uint64_t brix_mono_ns (void)
Definition at line 41 of file trace.c.
Referenced by aconn_deadline_ns(), aconn_dispatch_frame(), aconn_issue_areq(), aconn_maybe_ping(), aconn_note_rtt(), aconn_on_transport_error(), aconn_reconnect_succeeded(), aconn_submit_cmd(), areq_note_deferral(), bench_one(), bench_run(), bench_sweep(), bench_workers_init(), bench_workers_run(), brix_aconn_attach(), brix_backoff_sleep(), brix_backoff_sleep_fast(), brix_bringup_ex(), brix_connect_resilient(), brix_fuse_run(), brix_http_download(), brix_http_upload_resumable(), brix_io_stall_arm(), brix_jitter_ms(), brix_rfile_open_read(), brix_rfile_open_write(), brix_rfile_pread(), brix_rfile_pwrite(), brix_roundtrip_resilient(), brix_send_ext(), brix_tls_read(), brix_webfile_pread(), brix_webmeta_propfind(), brix_with_resilience(), csctx_retry_gate(), do_bench(), doctor_xfer(), download_stream_body(), dx_authz_scope(), dx_probe_write(), fuse_run_done(), http_download_should_retry(), httpx_resumable_may_retry(), loop_process_timeouts(), mb_create(), mb_record(), mb_remove(), mb_run_workers(), now_ns(), plain_read_full(), pump_sink_remote(), pump_src_remote(), rc_worker_main(), read_wait_ms(), recv_note_diag(), resilient_setup(), tail_follow(), tls_read_wait_ms(), upload_close_commit_resilient(), upload_stream_body(), watch_probe_once(), xfs_readlink(), xrdcp_enable_progress_if_needed(), and xrdcp_progress().
brix_reqid_name()
const char * brix_reqid_name (int reqid)
Definition at line 29 of file trace.c.
References brix_kxr_request_name().
Referenced by brix_timing_report(), brix_trace_frame(), playback_reissue_wire(), and replay_frame_record().
brix_status_name()
const char * brix_status_name (int status)
Definition at line 35 of file trace.c.
References brix_kxr_response_status_name().
Referenced by brix_trace_response(), playback_reissue_wire(), and replay_frame_record().
brix_timing_report()
void brix_timing_report (const brix_conn * c)
Definition at line 212 of file trace.c.
References brix_reqid_name(), c, kXR_1stRequest, and XRDC_NOP.
Referenced by brix_close(), and do_bench().
brix_trace_error()
static void brix_trace_error (int dir, uint16_t sid, const uint8_t * b, uint32_t blen) static
Definition at line 107 of file trace.c.
References brix_kxr_name(), and xrd_get_u32_be().
Referenced by brix_trace_response().
brix_trace_frame()
void brix_trace_frame (brix_conn * c, int dir, uint16_t sid, int code, int is_request, uint32_t dlen, const void * body, uint32_t blen)
Definition at line 194 of file trace.c.
References brix_reqid_name(), brix_trace_response(), c, code, and hexdump().
Referenced by brix_send_ext(), recv_note_diag(), recv_raw(), and recv_raw_frame().
brix_trace_redirect()
static void brix_trace_redirect (int dir, uint16_t sid, const uint8_t * b, uint32_t blen) static
Definition at line 131 of file trace.c.
References port, and xrd_get_u32_be().
Referenced by brix_trace_response().
brix_trace_response()
static void brix_trace_response (int dir, uint16_t sid, int code, uint32_t dlen, const uint8_t * b, uint32_t blen) static
Definition at line 178 of file trace.c.
References brix_status_name(), brix_trace_error(), brix_trace_redirect(), brix_trace_wait(), code, kXR_error, kXR_redirect, and kXR_wait.
Referenced by brix_trace_frame().
brix_trace_wait()
static void brix_trace_wait (int dir, uint16_t sid, const uint8_t * b) static
Definition at line 152 of file trace.c.
References xrd_get_u32_be().
Referenced by brix_trace_response().
hexdump()
static void hexdump (const uint8_t * buf, uint32_t n) static
Definition at line 74 of file trace.c.
Referenced by brix_trace_frame().