nginx-xrootd: src/observability/dashboard/transfer_table.c File Reference
transfer_table.c File Reference
#include "dashboard.h"
#include "core/compat/shm_slots.h"
#include <ngx_shmtx.h>
#include <string.h>
Functions
ngx_int_t ngx_brix_dashboard_shm_init (ngx_shm_zone_t *shm_zone, void *data)
static void dashboard_copy_field (char *dst, size_t dstsz, const char *src)
int brix_transfer_slot_alloc_ex (brix_transfer_table_t *t, const u_char sessid[16], const char *client_ip, const char *identity, const char *vo, const char *path, const char *op, uint8_t direction, uint8_t proto, int64_t expected_bytes, int64_t now_ms)
int brix_transfer_slot_alloc (brix_transfer_table_t *t, const u_char sessid[16], const char *client_ip, const char *identity, const char *path, uint8_t direction, uint8_t proto, int64_t now_ms)
void brix_transfer_slot_update_bytes (brix_transfer_table_t *t, int slot_idx, ngx_atomic_int_t nbytes, int64_t now_ms)
void brix_transfer_slot_update (brix_transfer_table_t *t, int slot_idx, ngx_atomic_int_t nbytes, int64_t now_ms)
void brix_transfer_slot_set_state (brix_transfer_table_t *t, int slot_idx, uint8_t state, int64_t now_ms)
void brix_transfer_slot_set_error (brix_transfer_table_t *t, int slot_idx, const char *reason, int64_t now_ms)
void brix_transfer_slot_set_tpc_remote (brix_transfer_table_t *t, int slot_idx, const char *remote_host, const char *path_hint, int remote_status, int curl_exit)
void brix_transfer_slot_count_op (brix_transfer_table_t *t, int slot_idx, const char *op)
void brix_transfer_slot_free (brix_transfer_table_t *t, int slot_idx)
void brix_transfer_slot_free_all_for_session (brix_transfer_table_t *t, const u_char sessid[16])
Variables
static ngx_shmtx_t brix_dashboard_mutex
Function Documentation
brix_transfer_slot_alloc()
int brix_transfer_slot_alloc (brix_transfer_table_t * t, const u_char sessid[16], const char * client_ip, const char * identity, const char * path, uint8_t direction, uint8_t proto, int64_t now_ms)
Definition at line 129 of file transfer_table.c.
References brix_transfer_slot_alloc_ex().
Referenced by brix_open_register_monitor().
brix_transfer_slot_alloc_ex()
int brix_transfer_slot_alloc_ex (brix_transfer_table_t * t, const u_char sessid[16], const char * client_ip, const char * identity, const char * vo, const char * path, const char * op, uint8_t direction, uint8_t proto, int64_t expected_bytes, int64_t now_ms)
Definition at line 74 of file transfer_table.c.
References BRIX_DASH_EVENT_DASHBOARD, brix_dashboard_event_add(), BRIX_DASHBOARD_MAX_TRANSFERS, brix_dashboard_mutex, BRIX_XFER_STATE_ACTIVE, brix_transfer_slot_t::client_ip, dashboard_copy_field(), brix_transfer_slot_t::direction, brix_transfer_slot_t::expected_bytes, brix_transfer_slot_t::identity, brix_transfer_slot_t::in_use, brix_transfer_slot_t::last_ms, brix_transfer_table_t::next_serial, ngx_memcpy, op, brix_transfer_slot_t::op, brix_transfer_slot_t::path, brix_transfer_slot_t::proto, brix_transfer_slot_t::serial, brix_transfer_slot_t::sessid, brix_transfer_table_t::slots, brix_transfer_slot_t::start_ms, brix_transfer_slot_t::state, brix_transfer_slot_t::state_since_ms, brix_transfer_slot_t::vo, and brix_transfer_slot_t::worker_pid.
Referenced by brix_transfer_slot_alloc(), and dashboard_http_reserve_slot().
brix_transfer_slot_count_op()
void brix_transfer_slot_count_op (brix_transfer_table_t * t, int slot_idx, const char * op)
Definition at line 272 of file transfer_table.c.
References BRIX_DASHBOARD_MAX_TRANSFERS, brix_transfer_slot_t::close_ops, brix_transfer_slot_t::in_use, op, brix_transfer_slot_t::read_ops, brix_transfer_table_t::slots, brix_transfer_slot_t::sync_ops, and brix_transfer_slot_t::write_ops.
Referenced by brix_close_release_slots(), brix_compressed_account(), brix_handle_sync(), brix_read_serve_sendfile(), brix_staged_append(), brix_write_compressed(), brix_write_finalize_sync(), dashboard_http_bind_slot(), and read_finish_buffered().
brix_transfer_slot_free()
void brix_transfer_slot_free (brix_transfer_table_t * t, int slot_idx)
Definition at line 308 of file transfer_table.c.
References BRIX_DASHBOARD_MAX_TRANSFERS, BRIX_XFER_STATE_CLOSING, brix_transfer_slot_t::in_use, brix_transfer_table_t::slots, brix_transfer_slot_t::state, and brix_transfer_slot_t::state_since_ms.
Referenced by brix_close_release_slots(), brix_dashboard_http_finish(), dashboard_build_transfer_rows(), dashboard_http_bind_slot(), and dashboard_http_cleanup().
brix_transfer_slot_free_all_for_session()
void brix_transfer_slot_free_all_for_session (brix_transfer_table_t * t, const u_char sessid[16])
Definition at line 323 of file transfer_table.c.
References BRIX_DASHBOARD_MAX_TRANSFERS, brix_dashboard_mutex, brix_transfer_slot_t::in_use, brix_transfer_slot_t::sessid, and brix_transfer_table_t::slots.
Referenced by brix_on_disconnect().
brix_transfer_slot_set_error()
void brix_transfer_slot_set_error (brix_transfer_table_t * t, int slot_idx, const char * reason, int64_t now_ms)
Definition at line 224 of file transfer_table.c.
References BRIX_DASH_EVENT_IO, brix_dashboard_event_add(), BRIX_DASHBOARD_MAX_TRANSFERS, BRIX_XFER_STATE_ERROR, dashboard_copy_field(), brix_transfer_slot_t::in_use, brix_transfer_slot_t::last_error, brix_transfer_slot_t::last_ms, brix_transfer_slot_t::path, brix_transfer_slot_t::proto, brix_transfer_table_t::slots, brix_transfer_slot_t::state, and brix_transfer_slot_t::state_since_ms.
Referenced by brix_dashboard_http_error().
brix_transfer_slot_set_state()
void brix_transfer_slot_set_state (brix_transfer_table_t * t, int slot_idx, uint8_t state, int64_t now_ms)
Definition at line 204 of file transfer_table.c.
References BRIX_DASHBOARD_MAX_TRANSFERS, brix_transfer_slot_t::in_use, brix_transfer_slot_t::last_ms, brix_transfer_table_t::slots, brix_transfer_slot_t::state, and brix_transfer_slot_t::state_since_ms.
Referenced by brix_dashboard_http_finish(), and brix_dashboard_http_state().
brix_transfer_slot_set_tpc_remote()
void brix_transfer_slot_set_tpc_remote (brix_transfer_table_t * t, int slot_idx, const char * remote_host, const char * path_hint, int remote_status, int curl_exit)
Definition at line 248 of file transfer_table.c.
References BRIX_DASHBOARD_MAX_TRANSFERS, dashboard_copy_field(), brix_transfer_slot_t::in_use, brix_transfer_table_t::slots, brix_transfer_slot_t::tpc_curl_exit, brix_transfer_slot_t::tpc_remote_host, brix_transfer_slot_t::tpc_remote_path_hint, and brix_transfer_slot_t::tpc_remote_status.
Referenced by brix_dashboard_http_tpc_remote().
brix_transfer_slot_update()
void brix_transfer_slot_update (brix_transfer_table_t * t, int slot_idx, ngx_atomic_int_t nbytes, int64_t now_ms)
Definition at line 197 of file transfer_table.c.
References brix_transfer_slot_update_bytes().
Referenced by brix_compressed_account(), brix_read_serve_sendfile(), brix_staged_append(), brix_write_compressed(), brix_write_finalize_sync(), and read_finish_buffered().
brix_transfer_slot_update_bytes()
void brix_transfer_slot_update_bytes (brix_transfer_table_t * t, int slot_idx, ngx_atomic_int_t nbytes, int64_t now_ms)
Definition at line 141 of file transfer_table.c.
References BRIX_DASHBOARD_MAX_TRANSFERS, BRIX_XFER_SAMPLE_MS, BRIX_XFER_STATE_ACTIVE, brix_transfer_slot_t::bytes, brix_transfer_slot_t::bytes_last_sample, brix_transfer_slot_t::in_use, brix_transfer_slot_t::instant_bps, brix_transfer_slot_t::last_ms, brix_transfer_slot_t::last_sample_ms, brix_transfer_table_t::slots, and brix_transfer_slot_t::state.
Referenced by brix_dashboard_http_add(), and brix_transfer_slot_update().
dashboard_copy_field()
static void dashboard_copy_field (char * dst, size_t dstsz, const char * src) static
Definition at line 59 of file transfer_table.c.
Referenced by brix_transfer_slot_alloc_ex(), brix_transfer_slot_set_error(), and brix_transfer_slot_set_tpc_remote().
ngx_brix_dashboard_shm_init()
ngx_int_t ngx_brix_dashboard_shm_init (ngx_shm_zone_t * shm_zone, void * data)
Definition at line 31 of file transfer_table.c.
References brix_dashboard_mutex, and brix_shm_table_alloc().
Referenced by brix_configure_dashboard().
Variable Documentation
brix_dashboard_mutex
ngx_shmtx_t brix_dashboard_mutex static
Definition at line 27 of file transfer_table.c.
Referenced by brix_transfer_slot_alloc_ex(), brix_transfer_slot_free_all_for_session(), and ngx_brix_dashboard_shm_init().