nginx-xrootd: src/core/types/config.h File Reference
config.h File Reference
#include "net/mirror/mirror.h"
#include "core/config/tape_stage_conf.h"
#include "auth/authz/acc/privs.h"
#include "fs/cache/writethrough_decision.h"
#include "core/config/shared_conf.h"
#include "core/shm/kv.h"
#include "auth/authz/auth_cache.h"
#include "core/shm/rate_limit.h"
#include "conf_structs.h"
Data Structures
struct brix_sss_key_t
struct brix_authdb_rule_t
struct brix_vo_rule_t
struct brix_group_rule_t
struct brix_manager_map_t
struct brix_proxy_upstream_t
struct ngx_stream_brix_srv_conf_t
Macros
#define BRIX_AUTH_READ 0x01 /* 'r' */
#define BRIX_AUTH_LOOKUP 0x02 /* 'l' */
#define BRIX_AUTH_UPDATE 0x04 /* 'w' or 'a' */
#define BRIX_AUTH_DELETE 0x08 /* 'd' */
#define BRIX_AUTH_MKDIR 0x10 /* 'm' */
#define BRIX_AUTH_ADMIN 0x20 /* 'k' */
Enumerations
enum brix_auth_type_t { BRIX_AUTH_USER = 'u' , BRIX_AUTH_GROUP = 'g' , BRIX_AUTHDB_HOST = 'p' , BRIX_AUTH_ALL = 'a' }
Functions
ngx_int_t brix_acc_init_server (ngx_stream_brix_srv_conf_t *xcf, ngx_cycle_t *cycle)
Macro Definition Documentation
BRIX_AUTH_ADMIN
#define BRIX_AUTH_ADMIN 0x20 /* 'k' */
Definition at line 57 of file config.h.
BRIX_AUTH_DELETE
#define BRIX_AUTH_DELETE 0x08 /* 'd' */
Definition at line 55 of file config.h.
BRIX_AUTH_LOOKUP
#define BRIX_AUTH_LOOKUP 0x02 /* 'l' */
Definition at line 53 of file config.h.
BRIX_AUTH_MKDIR
#define BRIX_AUTH_MKDIR 0x10 /* 'm' */
Definition at line 56 of file config.h.
BRIX_AUTH_READ
#define BRIX_AUTH_READ 0x01 /* 'r' */
Definition at line 52 of file config.h.
BRIX_AUTH_UPDATE
#define BRIX_AUTH_UPDATE 0x04 /* 'w' or 'a' */
Definition at line 54 of file config.h.
Enumeration Type Documentation
brix_auth_type_t
enum brix_auth_type_t
Enumerator
BRIX_AUTH_USER
BRIX_AUTH_GROUP
BRIX_AUTHDB_HOST
BRIX_AUTH_ALL
Definition at line 44 of file config.h.
Function Documentation
brix_acc_init_server()
ngx_int_t brix_acc_init_server (ngx_stream_brix_srv_conf_t * xcf, ngx_cycle_t * cycle)
Definition at line 239 of file config.c.
References ngx_stream_brix_srv_conf_t::acc, ngx_stream_brix_srv_conf_t::authdb, brix_acc_build(), brix_acc_refresh_handler(), BRIX_AUTHDB_FORMAT_XRDACC, BRIX_DIAG_EMERG, brix_acc_conf_t::encoding, brix_acc_conf_t::format, brix_acc_conf_t::gidlifetime, brix_acc_conf_t::gidretran, ngx_pcalloc(), brix_acc_conf_t::nisdomain, brix_acc_conf_t::pgo, brix_acc_conf_t::refresh, brix_acc_conf_t::spacechar, brix_acc_conf_t::tables, and brix_acc_conf_t::timer.
Referenced by ngx_stream_brix_init_process().