nginx-xrootd: src/fs/backend/ucred_parse.c File Reference
ucred_parse.c File Reference
#include "ucred.h"
#include "ucred_internal.h"
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <openssl/pem.h>
#include <openssl/sha.h>
#include <openssl/x509.h>
Data Structures
struct ucred_keyring_line_t
Functions
ngx_int_t ucred_check_pem (const char *path, int *expired)
ngx_int_t ucred_read_token (const char *path, char *out_bearer, size_t cap)
static size_t ucred_line_end (const char *buf, size_t start, size_t end)
static size_t ucred_skip_eol (const char *buf, size_t pos, size_t end)
ngx_int_t ucred_read_s3 (const char *path, char *out_ak, size_t ak_cap, char *out_sk, size_t sk_cap, char *out_region, size_t region_cap)
static size_t ucred_keyring_next_line (const char *buf, size_t i, size_t end)
static ngx_int_t ucred_keyring_parse_line (const char *buf, size_t line, size_t end, ucred_keyring_line_t *out)
ngx_int_t ucred_read_keyring (const char *path, char *out_path, size_t path_cap, char *out_user, size_t user_cap)
Function Documentation
ucred_check_pem()
ngx_int_t ucred_check_pem (const char * path, int * expired)
Definition at line 39 of file ucred_parse.c.
Referenced by brix_sd_ucred_resolve().
ucred_keyring_next_line()
static size_t ucred_keyring_next_line (const char * buf, size_t i, size_t end) static
Definition at line 268 of file ucred_parse.c.
Referenced by ucred_keyring_parse_line().
ucred_keyring_parse_line()
static ngx_int_t ucred_keyring_parse_line (const char * buf, size_t line, size_t end, ucred_keyring_line_t * out) static
Definition at line 298 of file ucred_parse.c.
References ucred_keyring_line_t::id_len, ucred_keyring_line_t::id_start, ucred_keyring_line_t::next, and ucred_keyring_next_line().
Referenced by ucred_read_keyring().
ucred_line_end()
static size_t ucred_line_end (const char * buf, size_t start, size_t end) static
Definition at line 123 of file ucred_parse.c.
Referenced by ucred_read_s3().
ucred_read_keyring()
ngx_int_t ucred_read_keyring (const char * path, char * out_path, size_t path_cap, char * out_user, size_t user_cap)
Definition at line 335 of file ucred_parse.c.
References close(), ucred_keyring_line_t::id_len, ucred_keyring_line_t::id_start, ucred_keyring_line_t::next, open(), read(), and ucred_keyring_parse_line().
Referenced by brix_sd_ucred_resolve().
ucred_read_s3()
ngx_int_t ucred_read_s3 (const char * path, char * out_ak, size_t ak_cap, char * out_sk, size_t sk_cap, char * out_region, size_t region_cap)
Definition at line 178 of file ucred_parse.c.
References BRIX_UCRED_S3_AK_MAX, BRIX_UCRED_S3_REGION_MAX, BRIX_UCRED_S3_SK_MAX, close(), open(), read(), ucred_line_end(), and ucred_skip_eol().
Referenced by brix_sd_ucred_resolve().
ucred_read_token()
ngx_int_t ucred_read_token (const char * path, char * out_bearer, size_t cap)
Definition at line 79 of file ucred_parse.c.
References BRIX_UCRED_BEARER_MAX, c, close(), open(), and read().
Referenced by brix_sd_ucred_resolve().
ucred_skip_eol()
static size_t ucred_skip_eol (const char * buf, size_t pos, size_t end) static
Definition at line 147 of file ucred_parse.c.
Referenced by ucred_read_s3().