nginx-xrootd: src/fs/backend/ucred_internal.h File Reference
ucred_internal.h File Reference
#include "ucred.h"
Functions
ngx_int_t ucred_check_pem (const char *path, int *expired)
ngx_int_t ucred_read_token (const char *path, char *out_bearer, size_t cap)
ngx_int_t ucred_read_s3 (const char *path, char *out_ak, size_t ak_cap, char *out_sk, size_t sk_cap, char *out_region, size_t region_cap)
ngx_int_t ucred_read_keyring (const char *path, char *out_path, size_t path_cap, char *out_user, size_t user_cap)
Function Documentation
ucred_check_pem()
ngx_int_t ucred_check_pem (const char * path, int * expired)
Definition at line 39 of file ucred_parse.c.
Referenced by brix_sd_ucred_resolve().
ucred_read_keyring()
ngx_int_t ucred_read_keyring (const char * path, char * out_path, size_t path_cap, char * out_user, size_t user_cap)
Definition at line 335 of file ucred_parse.c.
References close(), ucred_keyring_line_t::id_len, ucred_keyring_line_t::id_start, ucred_keyring_line_t::next, open(), read(), and ucred_keyring_parse_line().
Referenced by brix_sd_ucred_resolve().
ucred_read_s3()
ngx_int_t ucred_read_s3 (const char * path, char * out_ak, size_t ak_cap, char * out_sk, size_t sk_cap, char * out_region, size_t region_cap)
Definition at line 178 of file ucred_parse.c.
References BRIX_UCRED_S3_AK_MAX, BRIX_UCRED_S3_REGION_MAX, BRIX_UCRED_S3_SK_MAX, close(), open(), read(), ucred_line_end(), and ucred_skip_eol().
Referenced by brix_sd_ucred_resolve().
ucred_read_token()
ngx_int_t ucred_read_token (const char * path, char * out_bearer, size_t cap)
Definition at line 79 of file ucred_parse.c.
References BRIX_UCRED_BEARER_MAX, c, close(), open(), and read().
Referenced by brix_sd_ucred_resolve().