nginx-xrootd: src/fs/backend/ucred.c File Reference
ucred.c File Reference
#include "ucred.h"
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <openssl/pem.h>
#include <openssl/sha.h>
#include <openssl/x509.h>
Data Structures
struct ucred_keyring_line_t
Functions
static int ucred_fs_safe_char (char c)
static int ucred_principal_fs_safe (const char *principal)
static ngx_int_t ucred_check_pem (const char *path, int *expired)
static ngx_int_t ucred_read_token (const char *path, char *out_bearer, size_t cap)
static size_t ucred_line_end (const char *buf, size_t start, size_t end)
static size_t ucred_skip_eol (const char *buf, size_t pos, size_t end)
static ngx_int_t ucred_read_s3 (const char *path, char *out_ak, size_t ak_cap, char *out_sk, size_t sk_cap, char *out_region, size_t region_cap)
static size_t ucred_keyring_next_line (const char *buf, size_t i, size_t end)
static ngx_int_t ucred_keyring_parse_line (const char *buf, size_t line, size_t end, ucred_keyring_line_t *out)
static ngx_int_t ucred_read_keyring (const char *path, char *out_path, size_t path_cap, char *out_user, size_t user_cap)
ngx_int_t brix_sd_ucred_principal (const brix_identity_t *id, char *buf, size_t cap)
ngx_int_t brix_sd_ucred_key (const char *principal, char *key, size_t cap)
ngx_int_t brix_sd_ucred_resolve (const char *dir, const char *key, brix_sd_ucred_t *out)
ngx_int_t brix_sd_ucred_select (const char *dir, const brix_identity_t *id, brix_sd_ucred_t *out)
Function Documentation
brix_sd_ucred_key()
ngx_int_t brix_sd_ucred_key (const char * principal, char * key, size_t cap)
Definition at line 454 of file ucred.c.
References key, and ucred_principal_fs_safe().
Referenced by brix_sd_ucred_select(), delegation_put_store(), and delegation_validate_and_store().
brix_sd_ucred_principal()
ngx_int_t brix_sd_ucred_principal (const brix_identity_t * id, char * buf, size_t cap)
Definition at line 422 of file ucred.c.
References brix_identity_t::dn, brix_identity_t::is_authenticated, and brix_identity_t::subject.
Referenced by brix_sd_ucred_select().
brix_sd_ucred_resolve()
ngx_int_t brix_sd_ucred_resolve (const char * dir, const char * key, brix_sd_ucred_t * out)
Definition at line 501 of file ucred.c.
References brix_sd_ucred_t::bearer, BRIX_UCRED_PATH_MAX, brix_sd_ucred_t::ceph_keyring, brix_sd_ucred_t::ceph_user, brix_sd_ucred_t::expired, brix_sd_ucred_t::is_bearer, brix_sd_ucred_t::is_ceph, brix_sd_ucred_t::is_s3, brix_sd_ucred_t::key, key, brix_sd_ucred_t::path, brix_sd_ucred_t::s3_ak, brix_sd_ucred_t::s3_region, brix_sd_ucred_t::s3_sk, ucred_check_pem(), ucred_read_keyring(), ucred_read_s3(), and ucred_read_token().
Referenced by brix_sd_ucred_select(), stage_engine_run(), and vfs_cred_maybe_mint().
brix_sd_ucred_select()
ngx_int_t brix_sd_ucred_select (const char * dir, const brix_identity_t * id, brix_sd_ucred_t * out)
Definition at line 606 of file ucred.c.
References brix_sd_ucred_key(), brix_sd_ucred_principal(), brix_sd_ucred_resolve(), BRIX_UCRED_KEY_MAX, BRIX_UCRED_PRINC_MAX, brix_sd_ucred_t::expired, brix_sd_ucred_t::key, brix_sd_ucred_t::principal, and ucred_principal_fs_safe().
Referenced by vfs_backend_cred_decide(), and webdav_tpc_user_proxy_from_store().
ucred_check_pem()
static ngx_int_t ucred_check_pem (const char * path, int * expired) static
Definition at line 78 of file ucred.c.
Referenced by brix_sd_ucred_resolve().
ucred_fs_safe_char()
static int ucred_fs_safe_char (char c) static
Definition at line 47 of file ucred.c.
References c.
Referenced by ucred_principal_fs_safe().
ucred_keyring_next_line()
static size_t ucred_keyring_next_line (const char * buf, size_t i, size_t end) static
Definition at line 301 of file ucred.c.
Referenced by ucred_keyring_parse_line().
ucred_keyring_parse_line()
static ngx_int_t ucred_keyring_parse_line (const char * buf, size_t line, size_t end, ucred_keyring_line_t * out) static
Definition at line 331 of file ucred.c.
References ucred_keyring_line_t::id_len, ucred_keyring_line_t::id_start, ucred_keyring_line_t::next, and ucred_keyring_next_line().
Referenced by ucred_read_keyring().
ucred_line_end()
static size_t ucred_line_end (const char * buf, size_t start, size_t end) static
Definition at line 160 of file ucred.c.
Referenced by ucred_read_s3().
ucred_principal_fs_safe()
static int ucred_principal_fs_safe (const char * principal) static
Definition at line 55 of file ucred.c.
References ucred_fs_safe_char().
Referenced by brix_sd_ucred_key(), and brix_sd_ucred_select().
ucred_read_keyring()
static ngx_int_t ucred_read_keyring (const char * path, char * out_path, size_t path_cap, char * out_user, size_t user_cap) static
Definition at line 368 of file ucred.c.
References close(), ucred_keyring_line_t::id_len, ucred_keyring_line_t::id_start, ucred_keyring_line_t::next, open(), read(), and ucred_keyring_parse_line().
Referenced by brix_sd_ucred_resolve().
ucred_read_s3()
static ngx_int_t ucred_read_s3 (const char * path, char * out_ak, size_t ak_cap, char * out_sk, size_t sk_cap, char * out_region, size_t region_cap) static
Definition at line 215 of file ucred.c.
References BRIX_UCRED_S3_AK_MAX, BRIX_UCRED_S3_REGION_MAX, BRIX_UCRED_S3_SK_MAX, close(), open(), read(), ucred_line_end(), and ucred_skip_eol().
Referenced by brix_sd_ucred_resolve().
ucred_read_token()
static ngx_int_t ucred_read_token (const char * path, char * out_bearer, size_t cap) static
Definition at line 118 of file ucred.c.
References BRIX_UCRED_BEARER_MAX, c, close(), open(), and read().
Referenced by brix_sd_ucred_resolve().
ucred_skip_eol()
static size_t ucred_skip_eol (const char * buf, size_t pos, size_t end) static
Definition at line 184 of file ucred.c.
Referenced by ucred_read_s3().