nginx-xrootd: src/fs/backend/ucred.h File Reference
ucred.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include "core/types/identity.h"
Data Structures
struct brix_sd_ucred_t
Macros
#define BRIX_UCRED_KEY_MAX 128
#define BRIX_UCRED_PATH_MAX 1024
#define BRIX_UCRED_PRINC_MAX 512
#define BRIX_UCRED_BEARER_MAX 4096
#define BRIX_UCRED_S3_AK_MAX 128
#define BRIX_UCRED_S3_SK_MAX 256
#define BRIX_UCRED_S3_REGION_MAX 64
#define BRIX_UCRED_CEPH_KEYRING_MAX BRIX_UCRED_PATH_MAX
#define BRIX_UCRED_CEPH_USER_MAX 128
Functions
ngx_int_t brix_sd_ucred_principal (const brix_identity_t *id, char *buf, size_t cap)
ngx_int_t brix_sd_ucred_key (const char *principal, char *key, size_t cap)
ngx_int_t brix_sd_ucred_resolve (const char *dir, const char *key, brix_sd_ucred_t *out)
ngx_int_t brix_sd_ucred_select (const char *dir, const brix_identity_t *id, brix_sd_ucred_t *out)
void brix_sd_ucred_wipe (brix_sd_ucred_t *cred)
Macro Definition Documentation
BRIX_UCRED_BEARER_MAX
#define BRIX_UCRED_BEARER_MAX 4096
Definition at line 83 of file ucred.h.
BRIX_UCRED_CEPH_KEYRING_MAX
#define BRIX_UCRED_CEPH_KEYRING_MAX BRIX_UCRED_PATH_MAX
Definition at line 95 of file ucred.h.
BRIX_UCRED_CEPH_USER_MAX
#define BRIX_UCRED_CEPH_USER_MAX 128
Definition at line 96 of file ucred.h.
BRIX_UCRED_KEY_MAX
#define BRIX_UCRED_KEY_MAX 128
Definition at line 73 of file ucred.h.
BRIX_UCRED_PATH_MAX
#define BRIX_UCRED_PATH_MAX 1024
Definition at line 76 of file ucred.h.
BRIX_UCRED_PRINC_MAX
#define BRIX_UCRED_PRINC_MAX 512
Definition at line 79 of file ucred.h.
BRIX_UCRED_S3_AK_MAX
#define BRIX_UCRED_S3_AK_MAX 128
Definition at line 88 of file ucred.h.
BRIX_UCRED_S3_REGION_MAX
#define BRIX_UCRED_S3_REGION_MAX 64
Definition at line 90 of file ucred.h.
BRIX_UCRED_S3_SK_MAX
#define BRIX_UCRED_S3_SK_MAX 256
Definition at line 89 of file ucred.h.
Function Documentation
brix_sd_ucred_key()
ngx_int_t brix_sd_ucred_key (const char * principal, char * key, size_t cap)
Definition at line 115 of file ucred.c.
References key, and ucred_principal_fs_safe().
Referenced by brix_http_delegated_cred_variable(), brix_sd_ucred_select(), delegation_put_store(), and delegation_validate_and_store().
brix_sd_ucred_principal()
ngx_int_t brix_sd_ucred_principal (const brix_identity_t * id, char * buf, size_t cap)
Definition at line 83 of file ucred.c.
References brix_identity_t::dn, brix_identity_t::is_authenticated, and brix_identity_t::subject.
Referenced by brix_sd_ucred_select(), and vfs_backend_cred_decide().
brix_sd_ucred_resolve()
ngx_int_t brix_sd_ucred_resolve (const char * dir, const char * key, brix_sd_ucred_t * out)
Definition at line 162 of file ucred.c.
References brix_sd_ucred_t::bearer, BRIX_UCRED_PATH_MAX, brix_sd_ucred_t::ceph_keyring, brix_sd_ucred_t::ceph_user, brix_sd_ucred_t::expired, brix_sd_ucred_t::is_bearer, brix_sd_ucred_t::is_ceph, brix_sd_ucred_t::is_s3, brix_sd_ucred_t::key, key, brix_sd_ucred_t::path, brix_sd_ucred_t::s3_ak, brix_sd_ucred_t::s3_region, brix_sd_ucred_t::s3_sk, ucred_check_pem(), ucred_read_keyring(), ucred_read_s3(), and ucred_read_token().
Referenced by brix_http_delegated_cred_variable(), brix_sd_ucred_select(), stage_engine_run(), and vfs_cred_maybe_mint().
brix_sd_ucred_select()
ngx_int_t brix_sd_ucred_select (const char * dir, const brix_identity_t * id, brix_sd_ucred_t * out)
Definition at line 267 of file ucred.c.
References brix_sd_ucred_key(), brix_sd_ucred_principal(), brix_sd_ucred_resolve(), BRIX_UCRED_KEY_MAX, BRIX_UCRED_PRINC_MAX, brix_sd_ucred_t::expired, brix_sd_ucred_t::key, brix_sd_ucred_t::principal, and ucred_principal_fs_safe().
Referenced by vfs_backend_cred_decide(), and webdav_tpc_user_proxy_from_store().
brix_sd_ucred_wipe()
void brix_sd_ucred_wipe (brix_sd_ucred_t * cred)
Definition at line 333 of file ucred.c.
References brix_sd_ucred_t::bearer, brix_sd_ucred_t::ceph_keyring, and brix_sd_ucred_t::s3_sk.
Referenced by brix_http_delegated_cred_variable(), brix_open_read_probe(), brix_open_resolved_via_driver(), brix_vfs_chmod(), brix_vfs_copy_driver(), brix_vfs_delete_via_driver(), brix_vfs_getxattr(), brix_vfs_listxattr(), brix_vfs_open_via_driver(), brix_vfs_probe(), brix_vfs_removexattr(), brix_vfs_rename(), brix_vfs_setattr(), brix_vfs_setxattr(), brix_vfs_stat_impl(), stage_engine_run(), staged_open_driver(), vfs_dir_open_driver(), vfs_mkdir_backend(), and webdav_tpc_user_proxy_from_store().