nginx-xrootd: src/fs/path/unified_build.c File Reference
unified_build.c File Reference
#include "core/ngx_brix_module.h"
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "path_internal.h"
#include "unified.h"
#include "unified_internal.h"
Functions
static ngx_uint_t brix_count_components_cstr (const char *path)
brix_path_status_t brix_validate_components_cstr (ngx_log_t *log, const char *path)
ngx_flag_t brix_has_trailing_slash_cstr (const char *path)
brix_path_status_t brix_copy_cstr (char *dst, size_t dstsz, const char *src)
static brix_path_status_t brix_append_component (char *path, size_t pathsz, size_t *len, const char *component, size_t component_len)
static brix_path_status_t brix_candidate_init_root (const char *root_canon, char *candidate, size_t candidatesz, size_t *len)
static brix_path_status_t brix_candidate_append_req (const char *req_path, char *candidate, size_t candidatesz, size_t *len)
brix_path_status_t brix_build_candidate (const char *root_canon, const char *req_path, brix_path_opts_t opts, brix_candidate_out_t *out)
Function Documentation
brix_append_component()
static brix_path_status_t brix_append_component (char * path, size_t pathsz, size_t * len, const char * component, size_t component_len) static
Definition at line 143 of file unified_build.c.
References BRIX_PATH_STATUS_OK, BRIX_PATH_STATUS_TOO_LONG, and ngx_memcpy.
Referenced by brix_candidate_append_req().
brix_build_candidate()
brix_path_status_t brix_build_candidate (const char * root_canon, const char * req_path, brix_path_opts_t opts, brix_candidate_out_t * out)
Definition at line 266 of file unified_build.c.
References brix_path_opts_t::allow_root, brix_candidate_append_req(), brix_candidate_init_root(), brix_count_components_cstr(), BRIX_PATH_STATUS_INVALID, BRIX_PATH_STATUS_OK, brix_candidate_out_t::buf, brix_candidate_out_t::bufsz, and brix_candidate_out_t::depth_out.
Referenced by brix_path_resolve_cstr().
brix_candidate_append_req()
static brix_path_status_t brix_candidate_append_req (const char * req_path, char * candidate, size_t candidatesz, size_t * len) static
Definition at line 213 of file unified_build.c.
References brix_append_component(), and BRIX_PATH_STATUS_OK.
Referenced by brix_build_candidate().
brix_candidate_init_root()
static brix_path_status_t brix_candidate_init_root (const char * root_canon, char * candidate, size_t candidatesz, size_t * len) static
Definition at line 179 of file unified_build.c.
References BRIX_PATH_STATUS_OK, BRIX_PATH_STATUS_TOO_LONG, and ngx_memcpy.
Referenced by brix_build_candidate().
brix_copy_cstr()
brix_path_status_t brix_copy_cstr (char * dst, size_t dstsz, const char * src)
Definition at line 125 of file unified_build.c.
References BRIX_PATH_STATUS_ERROR, BRIX_PATH_STATUS_OK, BRIX_PATH_STATUS_TOO_LONG, and ngx_memcpy.
Referenced by brix_finish_resolved().
brix_count_components_cstr()
static ngx_uint_t brix_count_components_cstr (const char * path) static
Definition at line 33 of file unified_build.c.
Referenced by brix_build_candidate().
brix_has_trailing_slash_cstr()
ngx_flag_t brix_has_trailing_slash_cstr (const char * path)
Definition at line 112 of file unified_build.c.
Referenced by brix_path_resolve_cstr().
brix_validate_components_cstr()
brix_path_status_t brix_validate_components_cstr (ngx_log_t * log, const char * path)
Definition at line 66 of file unified_build.c.
References brix_count_path_depth(), BRIX_MAX_PATH, brix_path_component_forbidden(), BRIX_PATH_STATUS_INVALID, BRIX_PATH_STATUS_OK, BRIX_PATH_STATUS_TOO_LONG, brix_path_warn(), and log.
Referenced by brix_path_resolve_cstr().