nginx-xrootd: src/observability/metrics/unified_record.c File Reference
unified_record.c File Reference
#include "unified_internal.h"
Functions
void brix_metric_op_done (brix_proto_t proto, brix_metric_op_t op, size_t bytes, ngx_msec_t latency_usec, brix_err_class_t err)
void brix_metric_backend_bytes (const char *backend_name, brix_metric_op_t op, size_t bytes)
void brix_metric_cache_result (brix_proto_t proto, unsigned int hit, size_t bytes_evicted)
void brix_metric_cred_result (brix_proto_t proto, brix_cred_outcome_t outcome)
void brix_metric_cache_usage_ratio (ngx_uint_t occupancy_ppm)
void brix_metric_cache_watermark_purge (ngx_uint_t files, uint64_t bytes)
void brix_metric_wt_stage_usage_ratio (ngx_uint_t occupancy_ppm)
void brix_metric_wt_stage_throttled (int reject)
void brix_metric_auth (brix_proto_t proto, ngx_uint_t auth_method, unsigned int success)
void brix_metric_tpc (brix_proto_t proto, unsigned int is_push, size_t bytes, brix_err_class_t err)
Function Documentation
brix_metric_auth()
void brix_metric_auth (brix_proto_t proto, ngx_uint_t auth_method, unsigned int success)
Definition at line 260 of file unified_record.c.
References ngx_brix_unified_metrics_t::auth_total, BRIX_ATOMIC_INC, BRIX_METRIC_AUTH_FAIL, BRIX_METRIC_AUTH_OK, brix_metric_auth_slot(), brix_metrics_shared(), BRIX_PROTO_COUNT, and ngx_brix_metrics_t::unified.
Referenced by access_authenticate(), access_try_basic(), access_try_cert(), access_try_token(), brix_handle_host_auth(), brix_handle_krb5_auth(), brix_handle_pwd_auth(), brix_handle_unix_auth(), pwd_round1(), pwd_round2(), s3_record_auth_result(), s3_verify_bearer(), and webdav_verify_basic_pwd().
brix_metric_backend_bytes()
void brix_metric_backend_bytes (const char * backend_name, brix_metric_op_t op, size_t bytes)
Definition at line 85 of file unified_record.c.
References BRIX_ATOMIC_ADD, brix_fs_id_from_name(), BRIX_METRIC_OP_READ, BRIX_METRIC_OP_WRITE, brix_metrics_shared(), ngx_brix_unified_metrics_t::io_bytes_read_backend, ngx_brix_unified_metrics_t::io_bytes_written_backend, op, and ngx_brix_metrics_t::unified.
Referenced by brix_pgread_try_warm(), brix_read_serve_sendfile(), brix_vfs_io_account(), brix_vfs_observe_ctx_op(), read_try_warm(), and serve_record_body_accounting().
brix_metric_cache_result()
void brix_metric_cache_result (brix_proto_t proto, unsigned int hit, size_t bytes_evicted)
Definition at line 120 of file unified_record.c.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, brix_metrics_shared(), BRIX_PROTO_COUNT, ngx_brix_unified_metrics_t::cache_bytes_evicted, ngx_brix_unified_metrics_t::cache_hits, ngx_brix_unified_metrics_t::cache_misses, and ngx_brix_metrics_t::unified.
Referenced by brix_vfs_open_try_cache(), cvmfs_finalize_metrics_fill(), and cvmfs_finalize_metrics_hit().
brix_metric_cache_usage_ratio()
void brix_metric_cache_usage_ratio (ngx_uint_t occupancy_ppm)
Definition at line 194 of file unified_record.c.
References brix_metrics_shared(), ngx_brix_unified_metrics_t::cache_usage_ratio_ppm, and ngx_brix_metrics_t::unified.
Referenced by brix_cache_watermark_purge().
brix_metric_cache_watermark_purge()
void brix_metric_cache_watermark_purge (ngx_uint_t files, uint64_t bytes)
Definition at line 210 of file unified_record.c.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, brix_metrics_shared(), ngx_brix_unified_metrics_t::cache_watermark_evicted_bytes, ngx_brix_unified_metrics_t::cache_watermark_evicted_files, ngx_brix_unified_metrics_t::cache_watermark_purges, and ngx_brix_metrics_t::unified.
Referenced by brix_cache_watermark_purge().
brix_metric_cred_result()
void brix_metric_cred_result (brix_proto_t proto, brix_cred_outcome_t outcome)
Definition at line 159 of file unified_record.c.
References BRIX_ATOMIC_INC, BRIX_CRED_OUTCOME_DENY, BRIX_CRED_OUTCOME_FALLBACK, BRIX_CRED_OUTCOME_USER, brix_metrics_shared(), BRIX_PROTO_COUNT, ngx_brix_unified_metrics_t::cred_select_deny_total, ngx_brix_unified_metrics_t::cred_select_fallback_total, ngx_brix_unified_metrics_t::cred_select_user_total, and ngx_brix_metrics_t::unified.
Referenced by vfs_cred_deny_or_fallback(), vfs_cred_fill_user(), and vfs_cred_no_cap().
brix_metric_op_done()
void brix_metric_op_done (brix_proto_t proto, brix_metric_op_t op, size_t bytes, ngx_msec_t latency_usec, brix_err_class_t err)
Definition at line 31 of file unified_record.c.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, BRIX_ERR_COUNT, BRIX_IO_LATENCY_BUCKETS, brix_latency_bounds, BRIX_METRIC_OP_COUNT, BRIX_METRIC_OP_READ, BRIX_METRIC_OP_WRITE, brix_metrics_shared(), BRIX_PROTO_COUNT, ngx_brix_unified_metrics_t::io_bytes_read, ngx_brix_unified_metrics_t::io_bytes_written, ngx_brix_unified_metrics_t::io_latency_bucket, ngx_brix_unified_metrics_t::io_latency_count, ngx_brix_unified_metrics_t::io_latency_sum_usec, ngx_brix_unified_metrics_t::io_ops_total, op, and ngx_brix_metrics_t::unified.
Referenced by brix_vfs_observe_ctx_op(), s3_metrics_response_status(), and webdav_metrics_response().
brix_metric_tpc()
void brix_metric_tpc (brix_proto_t proto, unsigned int is_push, size_t bytes, brix_err_class_t err)
Definition at line 287 of file unified_record.c.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, BRIX_ERR_COUNT, BRIX_ERR_NONE, BRIX_METRIC_TPC_PULL, BRIX_METRIC_TPC_PUSH, brix_metrics_shared(), BRIX_PROTO_COUNT, ngx_brix_unified_metrics_t::tpc_bytes, ngx_brix_unified_metrics_t::tpc_transfers, and ngx_brix_metrics_t::unified.
Referenced by brix_tpc_metric_transfer().
brix_metric_wt_stage_throttled()
void brix_metric_wt_stage_throttled (int reject)
Definition at line 241 of file unified_record.c.
References BRIX_ATOMIC_INC, brix_metrics_shared(), ngx_brix_metrics_t::unified, ngx_brix_unified_metrics_t::wt_stage_throttled_reject, and ngx_brix_unified_metrics_t::wt_stage_throttled_wait.
Referenced by brix_open_stage_backpressure().
brix_metric_wt_stage_usage_ratio()
void brix_metric_wt_stage_usage_ratio (ngx_uint_t occupancy_ppm)
Definition at line 227 of file unified_record.c.
References brix_metrics_shared(), ngx_brix_metrics_t::unified, and ngx_brix_unified_metrics_t::wt_stage_usage_ratio_ppm.
Referenced by brix_wt_stage_admit().