nginx-xrootd: src/observability/metrics/unified_export_io.c File Reference
unified_export_io.c File Reference
#include "unified_internal.h"
#include <string.h>
Functions
unsigned long long brix_metric_value (ngx_atomic_t *counter)
static unsigned long long brix_unified_legacy_stream_bytes (ngx_brix_metrics_t *shm, unsigned int is_write)
static unsigned long long brix_unified_legacy_stream_op_slot (ngx_brix_metrics_t *shm, ngx_uint_t slot, unsigned int ok)
static unsigned long long brix_unified_legacy_stream_op (ngx_brix_metrics_t *shm, brix_metric_op_t op, unsigned int ok)
static ngx_uint_t brix_unified_srv_auth_slot (const char *auth)
static unsigned long long brix_unified_legacy_stream_auth (ngx_brix_metrics_t *shm, ngx_uint_t method, ngx_uint_t status)
unsigned long long brix_unified_legacy_auth (ngx_brix_metrics_t *shm, brix_proto_t proto, ngx_uint_t method, ngx_uint_t status)
void unified_emit_io_bytes (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void unified_emit_io_ops (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
static void unified_emit_io_latency_series (metrics_writer_t *mw, ngx_brix_metrics_t *shm, ngx_uint_t proto, ngx_uint_t op)
void unified_emit_io_latency (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
Function Documentation
brix_metric_value()
unsigned long long brix_metric_value (ngx_atomic_t * counter)
Definition at line 30 of file unified_export_io.c.
Referenced by brix_unified_legacy_stream_auth(), brix_unified_legacy_stream_bytes(), brix_unified_legacy_stream_op_slot(), unified_emit_auth(), unified_emit_cache_watermark(), unified_emit_io_bytes(), unified_emit_io_latency_series(), unified_emit_io_ops(), unified_emit_proto_counter(), unified_emit_tpc(), and unified_emit_wt_stage().
brix_unified_legacy_auth()
unsigned long long brix_unified_legacy_auth (ngx_brix_metrics_t * shm, brix_proto_t proto, ngx_uint_t method, ngx_uint_t status)
Definition at line 167 of file unified_export_io.c.
References BRIX_PROTO_ROOT, and brix_unified_legacy_stream_auth().
Referenced by unified_emit_auth().
brix_unified_legacy_stream_auth()
static unsigned long long brix_unified_legacy_stream_auth (ngx_brix_metrics_t * shm, ngx_uint_t method, ngx_uint_t status) static
Definition at line 145 of file unified_export_io.c.
References ngx_brix_srv_metrics_t::auth, BRIX_METRIC_AUTH_OK, brix_metric_value(), BRIX_METRICS_MAX_SERVERS, BRIX_OP_AUTH, brix_unified_srv_auth_slot(), ngx_brix_srv_metrics_t::in_use, ngx_brix_srv_metrics_t::op_err, ngx_brix_srv_metrics_t::op_ok, and ngx_brix_metrics_t::servers.
Referenced by brix_unified_legacy_auth().
brix_unified_legacy_stream_bytes()
static unsigned long long brix_unified_legacy_stream_bytes (ngx_brix_metrics_t * shm, unsigned int is_write) static
Definition at line 44 of file unified_export_io.c.
References brix_metric_value(), BRIX_METRICS_MAX_SERVERS, ngx_brix_srv_metrics_t::bytes_rx_total, ngx_brix_srv_metrics_t::bytes_tx_total, ngx_brix_srv_metrics_t::in_use, and ngx_brix_metrics_t::servers.
Referenced by unified_emit_io_bytes().
brix_unified_legacy_stream_op()
static unsigned long long brix_unified_legacy_stream_op (ngx_brix_metrics_t * shm, brix_metric_op_t op, unsigned int ok) static
Definition at line 91 of file unified_export_io.c.
References BRIX_METRIC_OP_DELETE, BRIX_METRIC_OP_DIRLIST, BRIX_METRIC_OP_MKDIR, BRIX_METRIC_OP_READ, BRIX_METRIC_OP_RENAME, BRIX_METRIC_OP_STAT, BRIX_METRIC_OP_WRITE, BRIX_OP_DIRLIST, BRIX_OP_MKDIR, BRIX_OP_MV, BRIX_OP_PGREAD, BRIX_OP_READ, BRIX_OP_READV, BRIX_OP_RM, BRIX_OP_RMDIR, BRIX_OP_STAT, BRIX_OP_STATX, BRIX_OP_WRITE, BRIX_OP_WRITEV, brix_unified_legacy_stream_op_slot(), and op.
Referenced by unified_emit_io_ops().
brix_unified_legacy_stream_op_slot()
static unsigned long long brix_unified_legacy_stream_op_slot (ngx_brix_metrics_t * shm, ngx_uint_t slot, unsigned int ok) static
Definition at line 66 of file unified_export_io.c.
References brix_metric_value(), BRIX_METRICS_MAX_SERVERS, BRIX_NOPS, ngx_brix_srv_metrics_t::in_use, ngx_brix_srv_metrics_t::op_err, ngx_brix_srv_metrics_t::op_ok, and ngx_brix_metrics_t::servers.
Referenced by brix_unified_legacy_stream_op().
brix_unified_srv_auth_slot()
static ngx_uint_t brix_unified_srv_auth_slot (const char * auth) static
Definition at line 120 of file unified_export_io.c.
References BRIX_METRIC_AUTH_GSI, BRIX_METRIC_AUTH_KRB5, BRIX_METRIC_AUTH_NONE, BRIX_METRIC_AUTH_SSS, BRIX_METRIC_AUTH_TOKEN, and BRIX_METRIC_AUTH_UNIX.
Referenced by brix_unified_legacy_stream_auth().
unified_emit_io_bytes()
void unified_emit_io_bytes (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 191 of file unified_export_io.c.
References brix_metric_proto_name(), brix_metric_value(), BRIX_PROTO_COUNT, BRIX_PROTO_ROOT, BRIX_PROTO_S3, BRIX_PROTO_WEBDAV, brix_unified_legacy_stream_bytes(), ngx_brix_s3_metrics_t::bytes_rx_total, ngx_brix_webdav_metrics_t::bytes_rx_total, ngx_brix_s3_metrics_t::bytes_tx_total, ngx_brix_webdav_metrics_t::bytes_tx_total, ngx_brix_unified_metrics_t::io_bytes_read, ngx_brix_unified_metrics_t::io_bytes_written, mw_printf(), ngx_brix_metrics_t::s3, ngx_brix_metrics_t::unified, and ngx_brix_metrics_t::webdav.
Referenced by brix_export_unified_metrics().
unified_emit_io_latency()
void unified_emit_io_latency (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 335 of file unified_export_io.c.
References BRIX_METRIC_OP_COUNT, BRIX_PROTO_COUNT, mw_printf(), op, and unified_emit_io_latency_series().
Referenced by brix_export_unified_metrics().
unified_emit_io_latency_series()
static void unified_emit_io_latency_series (metrics_writer_t * mw, ngx_brix_metrics_t * shm, ngx_uint_t proto, ngx_uint_t op) static
Definition at line 288 of file unified_export_io.c.
References BRIX_IO_LATENCY_BUCKETS, brix_latency_bounds, brix_metric_op_name(), brix_metric_proto_name(), brix_metric_value(), ngx_brix_unified_metrics_t::io_latency_bucket, ngx_brix_unified_metrics_t::io_latency_count, ngx_brix_unified_metrics_t::io_latency_sum_usec, mw_printf(), op, and ngx_brix_metrics_t::unified.
Referenced by unified_emit_io_latency().
unified_emit_io_ops()
void unified_emit_io_ops (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 240 of file unified_export_io.c.
References BRIX_ERR_COUNT, BRIX_ERR_NONE, BRIX_ERR_OTHER, brix_metric_err_name(), BRIX_METRIC_OP_COUNT, brix_metric_op_name(), brix_metric_proto_name(), brix_metric_value(), BRIX_PROTO_COUNT, BRIX_PROTO_ROOT, brix_unified_legacy_stream_op(), ngx_brix_unified_metrics_t::io_ops_total, mw_printf(), op, and ngx_brix_metrics_t::unified.
Referenced by brix_export_unified_metrics().