nginx-xrootd: src/fs/path/unified_resolve.c File Reference
unified_resolve.c File Reference
#include "core/ngx_brix_module.h"
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "path_internal.h"
#include "unified.h"
#include "unified_internal.h"
Functions
static ngx_int_t brix_stat_type_cstr (const char *path)
brix_path_status_t brix_finish_resolved (const brix_resolve_ctx_t *ctx, const char *resolved_path, brix_path_opts_t opts)
brix_path_status_t brix_resolve_missing_tail (const brix_resolve_ctx_t *ctx, const char *candidate)
static brix_path_status_t brix_walk_to_existing_ancestor (char *ancestor, char *ancestor_canon)
brix_path_status_t brix_resolve_missing_parents (const brix_resolve_ctx_t *ctx, const char *candidate)
Function Documentation
brix_finish_resolved()
brix_path_status_t brix_finish_resolved (const brix_resolve_ctx_t * ctx, const char * resolved_path, brix_path_opts_t opts)
Definition at line 65 of file unified_resolve.c.
References brix_path_opts_t::allow_missing_parents, brix_path_opts_t::allow_missing_tail, brix_copy_cstr(), BRIX_PATH_STATUS_ERROR, BRIX_PATH_STATUS_INVALID, BRIX_PATH_STATUS_OK, BRIX_PATH_TYPE_NOT_FOUND, brix_path_warn(), brix_path_within_root(), brix_stat_type_cstr(), brix_path_result_t::depth, brix_resolve_ctx_t::depth, brix_path_result_t::is_confined, brix_resolve_ctx_t::log, brix_path_opts_t::require_directory, brix_path_result_t::resolved, brix_resolve_ctx_t::resolved, brix_resolve_ctx_t::resolvsz, brix_resolve_ctx_t::result, brix_resolve_ctx_t::root_canon, and brix_path_result_t::type.
Referenced by brix_path_resolve_cstr(), brix_resolve_missing_parents(), and brix_resolve_missing_tail().
brix_resolve_missing_parents()
brix_path_status_t brix_resolve_missing_parents (const brix_resolve_ctx_t * ctx, const char * candidate)
Definition at line 255 of file unified_resolve.c.
References brix_path_opts_t::allow_missing_parents, brix_finish_resolved(), BRIX_PATH_STATUS_INVALID, BRIX_PATH_STATUS_OK, BRIX_PATH_STATUS_TOO_LONG, brix_path_warn(), brix_path_within_root(), brix_walk_to_existing_ancestor(), brix_resolve_ctx_t::log, ngx_memcpy, PATH_MAX, and brix_resolve_ctx_t::root_canon.
Referenced by brix_path_resolve_cstr().
brix_resolve_missing_tail()
brix_path_status_t brix_resolve_missing_tail (const brix_resolve_ctx_t * ctx, const char * candidate)
Definition at line 122 of file unified_resolve.c.
References brix_path_opts_t::allow_missing_tail, brix_finish_resolved(), BRIX_PATH_STATUS_ERROR, BRIX_PATH_STATUS_INVALID, BRIX_PATH_STATUS_NOT_FOUND, BRIX_PATH_STATUS_TOO_LONG, brix_path_warn(), brix_path_within_root(), brix_path_opts_t::is_write_operation, brix_resolve_ctx_t::log, ngx_memcpy, PATH_MAX, and brix_resolve_ctx_t::root_canon.
Referenced by brix_path_resolve_cstr().
brix_stat_type_cstr()
static ngx_int_t brix_stat_type_cstr (const char * path) static
Definition at line 34 of file unified_resolve.c.
References BRIX_PATH_TYPE_NOT_FOUND, and stat().
Referenced by brix_finish_resolved().
brix_walk_to_existing_ancestor()
static brix_path_status_t brix_walk_to_existing_ancestor (char * ancestor, char * ancestor_canon) static
Definition at line 205 of file unified_resolve.c.
References BRIX_PATH_STATUS_ERROR, BRIX_PATH_STATUS_NOT_FOUND, and BRIX_PATH_STATUS_OK.
Referenced by brix_resolve_missing_parents().