nginx-xrootd: src/observability/metrics/unified_export.c File Reference
unified_export.c File Reference
#include "unified_internal.h"
Functions
static void unified_emit_proto_counter (metrics_writer_t *mw, const char *help_type, const char *metric_name, ngx_atomic_t *field)
static void unified_emit_cred_select (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
static void unified_emit_cache (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
static void unified_emit_cache_watermark (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
static void unified_emit_wt_stage (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
static void unified_emit_auth (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
static void unified_emit_tpc (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
void brix_export_unified_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
Function Documentation
brix_export_unified_metrics()
void brix_export_unified_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 277 of file unified_export.c.
References unified_emit_auth(), unified_emit_cache(), unified_emit_cache_watermark(), unified_emit_cred_select(), unified_emit_io_bytes(), unified_emit_io_latency(), unified_emit_io_ops(), unified_emit_tpc(), and unified_emit_wt_stage().
Referenced by brix_export_prometheus_metrics().
unified_emit_auth()
static void unified_emit_auth (metrics_writer_t * mw, ngx_brix_metrics_t * shm) static
Definition at line 188 of file unified_export.c.
References ngx_brix_unified_metrics_t::auth_total, BRIX_METRIC_AUTH_COUNT, BRIX_METRIC_AUTH_OK, BRIX_METRIC_AUTH_STATUS_COUNT, brix_metric_proto_name(), brix_metric_value(), BRIX_PROTO_COUNT, brix_unified_auth_names, brix_unified_legacy_auth(), mw_printf(), and ngx_brix_metrics_t::unified.
Referenced by brix_export_unified_metrics().
unified_emit_cache()
static void unified_emit_cache (metrics_writer_t * mw, ngx_brix_metrics_t * shm) static
Definition at line 93 of file unified_export.c.
References ngx_brix_unified_metrics_t::cache_bytes_evicted, ngx_brix_unified_metrics_t::cache_hits, ngx_brix_unified_metrics_t::cache_misses, ngx_brix_metrics_t::unified, and unified_emit_proto_counter().
Referenced by brix_export_unified_metrics().
unified_emit_cache_watermark()
static void unified_emit_cache_watermark (metrics_writer_t * mw, ngx_brix_metrics_t * shm) static
Definition at line 122 of file unified_export.c.
References brix_metric_value(), ngx_brix_unified_metrics_t::cache_usage_ratio_ppm, ngx_brix_unified_metrics_t::cache_watermark_evicted_bytes, ngx_brix_unified_metrics_t::cache_watermark_evicted_files, ngx_brix_unified_metrics_t::cache_watermark_purges, mw_printf(), and ngx_brix_metrics_t::unified.
Referenced by brix_export_unified_metrics().
unified_emit_cred_select()
static void unified_emit_cred_select (metrics_writer_t * mw, ngx_brix_metrics_t * shm) static
Definition at line 58 of file unified_export.c.
References ngx_brix_unified_metrics_t::cred_select_deny_total, ngx_brix_unified_metrics_t::cred_select_fallback_total, ngx_brix_unified_metrics_t::cred_select_user_total, ngx_brix_metrics_t::unified, and unified_emit_proto_counter().
Referenced by brix_export_unified_metrics().
unified_emit_proto_counter()
static void unified_emit_proto_counter (metrics_writer_t * mw, const char * help_type, const char * metric_name, ngx_atomic_t * field) static
Definition at line 35 of file unified_export.c.
References brix_metric_proto_name(), brix_metric_value(), BRIX_PROTO_COUNT, and mw_printf().
Referenced by unified_emit_cache(), and unified_emit_cred_select().
unified_emit_tpc()
static void unified_emit_tpc (metrics_writer_t * mw, ngx_brix_metrics_t * shm) static
Definition at line 226 of file unified_export.c.
References BRIX_ERR_COUNT, brix_metric_err_name(), brix_metric_proto_name(), BRIX_METRIC_TPC_DIRECTION_COUNT, brix_metric_value(), BRIX_PROTO_COUNT, brix_unified_tpc_direction_names, mw_printf(), ngx_brix_unified_metrics_t::tpc_bytes, ngx_brix_unified_metrics_t::tpc_transfers, and ngx_brix_metrics_t::unified.
Referenced by brix_export_unified_metrics().
unified_emit_wt_stage()
static void unified_emit_wt_stage (metrics_writer_t * mw, ngx_brix_metrics_t * shm) static
Definition at line 160 of file unified_export.c.
References brix_metric_value(), mw_printf(), ngx_brix_metrics_t::unified, ngx_brix_unified_metrics_t::wt_stage_throttled_reject, ngx_brix_unified_metrics_t::wt_stage_throttled_wait, and ngx_brix_unified_metrics_t::wt_stage_usage_ratio_ppm.
Referenced by brix_export_unified_metrics().