nginx-xrootd: src/protocols/cvmfs/upstreams.c File Reference
upstreams.c File Reference
#include "cvmfs.h"
#include "fs/vfs/vfs_backend_registry.h"
Data Structures
struct cvmfs_upstream_slot
Macros
#define CVMFS_UP_MAX 16
Functions
brix_sd_instance_t * brix_cvmfs_upstream_get (ngx_http_request_t *r, ngx_http_brix_cvmfs_loc_conf_t *lcf, const ngx_str_t *host, in_port_t port, const char **up_root_out, ngx_uint_t *status)
Variables
static cvmfs_upstream_slot cvmfs_ups [16]
static ngx_uint_t cvmfs_ups_n
Macro Definition Documentation
CVMFS_UP_MAX
#define CVMFS_UP_MAX 16
Definition at line 18 of file upstreams.c.
Function Documentation
brix_cvmfs_upstream_get()
brix_sd_instance_t * brix_cvmfs_upstream_get (ngx_http_request_t * r, ngx_http_brix_cvmfs_loc_conf_t * lcf, const ngx_str_t * host, in_port_t port, const char ** up_root_out, ngx_uint_t * status)
Definition at line 34 of file upstreams.c.
References brix_vfs_backend_register_http_upstream(), brix_vfs_backend_resolve(), ngx_http_brix_cvmfs_loc_conf_t::common, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, CVMFS_UP_MAX, cvmfs_ups, cvmfs_ups_n, cvmfs_upstream_slot::host, host, ngx_memcpy, port, ngx_http_brix_shared_conf_t::root_canon, s, brix_cvmfs_conf_t::shared_cache, and brix_cvmfs_conf_t::upstream_max.
Referenced by cvmfs_gate_proxy_bind().
Variable Documentation
cvmfs_ups
cvmfs_upstream_slot cvmfs_ups[16] static
Definition at line 30 of file upstreams.c.
Referenced by brix_cvmfs_upstream_get().
cvmfs_ups_n
ngx_uint_t cvmfs_ups_n static
Definition at line 31 of file upstreams.c.
Referenced by brix_cvmfs_upstream_get().