nginx-xrootd: src/net/upstream/upstream.h File Reference
upstream.h File Reference
#include "core/ngx_brix_module.h"
Functions
ngx_int_t brix_upstream_start (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
void brix_upstream_cleanup (brix_upstream_t *up)
Function Documentation
brix_upstream_cleanup()
void brix_upstream_cleanup (brix_upstream_t * up)
Definition at line 13 of file lifecycle.c.
Referenced by brix_on_disconnect(), brix_upstream_abort(), brix_upstream_forward_response(), brix_upstream_read_handler(), brix_upstream_start(), brix_upstream_wait_timer_handler(), and brix_upstream_write_handler().
brix_upstream_start()
ngx_int_t brix_upstream_start (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 34 of file start.c.
References BRIX_AF_AUTO, brix_extract_path(), brix_resolve_connect_socket(), BRIX_RESOLVE_ERR_DNS, brix_upstream_build_bootstrap(), brix_upstream_cleanup(), brix_upstream_flush(), brix_upstream_read_handler(), brix_upstream_write_handler(), c, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_reqid, brix_ctx_recv_t::cur_streamid, brix_ctx_recv_t::hdr_buf, kXR_locate, kXR_open, xrdw_open_req_t::mode, xrdw_locate_req_t::options, xrdw_open_req_t::options, brix_ctx_recv_t::payload, brix_ctx_t::recv, brix_ctx_t::state, brix_ctx_t::upstream, ngx_stream_brix_srv_conf_t::upstream_addr, ngx_stream_brix_srv_conf_t::upstream_host, ngx_stream_brix_srv_conf_t::upstream_port, XRD_HANDSHAKE_LEN, XRD_ST_REQ_HEADER, XRD_ST_UPSTREAM, XRD_UP_BOOTSTRAP, XRD_UP_BS_HANDSHAKE, XRD_UP_CONNECTING, xrdw_locate_req_unpack(), and xrdw_open_req_unpack().
Referenced by brix_handle_locate(), and brix_handle_open().