nginx-xrootd: src/net/upstream/upstream_internal.h File Reference
upstream_internal.h File Reference
#include "upstream.h"
Data Structures
struct brix_upstream_t
Macros
#define BRIX_UP_WAIT_MAX 60
#define XRD_OBA_MAX_ROUNDS 8
Enumerations
enum brix_up_bs_t {
XRD_UP_BS_HANDSHAKE = 0 , XRD_UP_BS_PROTOCOL , XRD_UP_BS_TLS , XRD_UP_BS_LOGIN ,
XRD_UP_BS_AUTH , XRD_UP_BS_DONE
}
enum brix_up_state_t { XRD_UP_CONNECTING = 0 , XRD_UP_BOOTSTRAP , XRD_UP_REQUEST , XRD_UP_ASYNC }
Functions
void brix_upstream_abort (brix_upstream_t *up, const char *reason)
void brix_upstream_build_bootstrap (u_char *buf)
void brix_upstream_build_bootstrap_flags (u_char *buf, uint8_t protocol_flags)
void brix_upstream_build_login (ClientLoginRequest *req)
void brix_upstream_forward_response (brix_upstream_t *up)
void brix_upstream_handle_bootstrap_response (brix_upstream_t *up)
void brix_upstream_read_handler (ngx_event_t *rev)
void brix_upstream_wait_timer_handler (ngx_event_t *ev)
void brix_upstream_write_handler (ngx_event_t *wev)
ngx_int_t brix_upstream_flush (brix_upstream_t *up)
ngx_int_t brix_upstream_send_request (brix_upstream_t *up)
ngx_int_t brix_upstream_send_token_auth (brix_upstream_t *up, ngx_stream_brix_srv_conf_t *conf)
Macro Definition Documentation
BRIX_UP_WAIT_MAX
#define BRIX_UP_WAIT_MAX 60
Definition at line 28 of file upstream_internal.h.
XRD_OBA_MAX_ROUNDS
#define XRD_OBA_MAX_ROUNDS 8
Definition at line 34 of file upstream_internal.h.
Enumeration Type Documentation
brix_up_bs_t
enum brix_up_bs_t
Enumerator
XRD_UP_BS_HANDSHAKE
XRD_UP_BS_PROTOCOL
XRD_UP_BS_TLS
XRD_UP_BS_LOGIN
XRD_UP_BS_AUTH
XRD_UP_BS_DONE
Definition at line 36 of file upstream_internal.h.
brix_up_state_t
enum brix_up_state_t
Enumerator
XRD_UP_CONNECTING
XRD_UP_BOOTSTRAP
XRD_UP_REQUEST
XRD_UP_ASYNC
Definition at line 45 of file upstream_internal.h.
Function Documentation
brix_upstream_abort()
void brix_upstream_abort (brix_upstream_t * up, const char * reason)
Definition at line 41 of file lifecycle.c.
References brix_schedule_read_resume(), brix_send_error(), brix_upstream_cleanup(), c, brix_ctx_recv_t::cur_streamid, kXR_ServerError, brix_ctx_t::recv, brix_ctx_t::state, and XRD_ST_REQ_HEADER.
Referenced by brix_upstream_bootstrap_advance(), brix_upstream_bs_auth(), brix_upstream_bs_goto_tls(), brix_upstream_bs_handshake(), brix_upstream_bs_login(), brix_upstream_bs_protocol(), brix_upstream_continue_auth(), brix_upstream_dispatch_response(), brix_upstream_forward_response(), brix_upstream_handle_bootstrap_response(), brix_upstream_parse_header_and_alloc(), brix_upstream_read_handler(), brix_upstream_recv_chunk(), brix_upstream_wait_timer_handler(), and brix_upstream_write_handler().
brix_upstream_build_bootstrap()
void brix_upstream_build_bootstrap (u_char * buf)
Definition at line 53 of file bootstrap.c.
brix_upstream_build_bootstrap_flags()
void brix_upstream_build_bootstrap_flags (u_char * buf, uint8_t protocol_flags)
Definition at line 36 of file bootstrap.c.
Referenced by brix_upstream_build_bootstrap().
brix_upstream_build_login()
void brix_upstream_build_login (ClientLoginRequest * req)
Definition at line 65 of file bootstrap.c.
brix_upstream_flush()
ngx_int_t brix_upstream_flush (brix_upstream_t * up)
Definition at line 101 of file request.c.
Referenced by brix_upstream_send_request(), brix_upstream_send_token_auth(), brix_upstream_start_connect(), and brix_upstream_write_handler().
brix_upstream_forward_response()
void brix_upstream_forward_response (brix_upstream_t * up)
Definition at line 20 of file response.c.
References brix_build_resp_hdr(), brix_queue_response(), brix_schedule_read_resume(), brix_send_error(), brix_send_waitresp(), BRIX_UP_WAIT_MAX, brix_upstream_abort(), brix_upstream_cleanup(), brix_upstream_wait_timer_handler(), c, brix_ctx_recv_t::cur_streamid, kXR_error, kXR_ok, kXR_redirect, kXR_ServerError, kXR_wait, kXR_waitresp, ngx_memcpy, brix_ctx_t::recv, brix_ctx_t::state, XRD_RESPONSE_HDR_LEN, XRD_ST_REQ_HEADER, XRD_UP_ASYNC, and xrd_wait_secs_parse().
Referenced by brix_upstream_dispatch_response().
brix_upstream_handle_bootstrap_response()
void brix_upstream_handle_bootstrap_response (brix_upstream_t * up)
Definition at line 315 of file bootstrap.c.
References brix_upstream_abort(), brix_upstream_bootstrap_advance(), brix_upstream_bs_auth(), brix_upstream_bs_handshake(), brix_upstream_bs_login(), brix_upstream_bs_protocol(), XRD_UP_BS_AUTH, XRD_UP_BS_HANDSHAKE, XRD_UP_BS_LOGIN, XRD_UP_BS_PROTOCOL, and XRD_UP_BS_TLS.
Referenced by brix_upstream_dispatch_response().
brix_upstream_read_handler()
void brix_upstream_read_handler (ngx_event_t * rev)
Definition at line 244 of file events.c.
References brix_upstream_abort(), brix_upstream_cleanup(), brix_upstream_dispatch_response(), brix_upstream_parse_header_and_alloc(), brix_upstream_recv_chunk(), brix_ctx_t::destroyed, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_upstream_start_wrap_conn().
brix_upstream_send_request()
ngx_int_t brix_upstream_send_request (brix_upstream_t * up)
Definition at line 29 of file request.c.
References BRIX_PALLOC_OR_RETURN, brix_upstream_flush(), ClientOpenRequest::dlen, ClientStatRequest::dlen, ClientLocateRequest::dlen, kXR_locate, kXR_open, kXR_stat, xrdw_open_req_t::mode, ngx_memcpy, xrdw_locate_req_t::options, ClientOpenRequest::requestid, ClientStatRequest::requestid, ClientLocateRequest::requestid, ClientOpenRequest::streamid, ClientStatRequest::streamid, ClientLocateRequest::streamid, XRD_REQUEST_HDR_LEN, XRD_UP_REQUEST, xrdw_locate_req_pack(), and xrdw_open_req_pack().
Referenced by brix_upstream_bootstrap_advance(), and brix_upstream_wait_timer_handler().
brix_upstream_send_token_auth()
ngx_int_t brix_upstream_send_token_auth (brix_upstream_t * up, ngx_stream_brix_srv_conf_t * conf)
Definition at line 40 of file auth.c.
References BRIX_PALLOC_OR_RETURN, brix_token_read_file(), brix_upstream_flush(), xrdw_auth_req_t::credtype, ClientAuthRequest::dlen, kXR_auth, ngx_memcpy, ClientAuthRequest::requestid, ClientAuthRequest::streamid, UPSTREAM_BEARER_MAX, XRD_UP_BS_AUTH, and xrdw_auth_req_pack().
Referenced by brix_upstream_continue_auth().
brix_upstream_wait_timer_handler()
void brix_upstream_wait_timer_handler (ngx_event_t * ev)
Definition at line 22 of file events.c.
References brix_upstream_abort(), brix_upstream_cleanup(), brix_upstream_send_request(), and brix_ctx_t::destroyed.
Referenced by brix_upstream_forward_response().
brix_upstream_write_handler()
void brix_upstream_write_handler (ngx_event_t * wev)
Definition at line 53 of file events.c.
References BRIX_DIAG_ERR, brix_upstream_abort(), brix_upstream_cleanup(), brix_upstream_flush(), brix_ctx_t::destroyed, XRD_UP_BOOTSTRAP, XRD_UP_BS_HANDSHAKE, and XRD_UP_CONNECTING.
Referenced by brix_upstream_start_wrap_conn().