nginx-xrootd: src/core/aio/uring_admin.c File Reference
uring_admin.c File Reference
#include "core/ngx_brix_module.h"
#include "uring.h"
#include <sys/stat.h>
Macros
#define BRIX_URING_PANIC_POLL_MS 2000
Functions
static ngx_int_t brix_uring_ks_zone_init (ngx_shm_zone_t *zone, void *data)
ngx_int_t brix_uring_killswitch_configure (ngx_conf_t *cf)
ngx_atomic_t * brix_uring_killswitch_ptr (void)
ngx_int_t brix_uring_killswitch_set (ngx_uint_t disabled)
ngx_int_t brix_uring_killswitch_get (void)
void brix_uring_admin_set_enabled (ngx_uint_t on)
ngx_int_t brix_uring_admin_enabled (void)
static void brix_uring_panic_handler (ngx_event_t *ev)
ngx_int_t brix_uring_panicfile_arm (ngx_cycle_t *cycle, ngx_str_t *path)
Variables
static ngx_shm_zone_t * brix_uring_ks_zone
static ngx_uint_t brix_uring_admin_on
static ngx_event_t brix_uring_panic_timer
static u_char brix_uring_panic_path [PATH_MAX]
Macro Definition Documentation
BRIX_URING_PANIC_POLL_MS
#define BRIX_URING_PANIC_POLL_MS 2000
Definition at line 26 of file uring_admin.c.
Function Documentation
brix_uring_admin_enabled()
ngx_int_t brix_uring_admin_enabled (void)
Definition at line 128 of file uring_admin.c.
References brix_uring_admin_on.
Referenced by brix_admin_dispatch().
brix_uring_admin_set_enabled()
void brix_uring_admin_set_enabled (ngx_uint_t on)
Definition at line 122 of file uring_admin.c.
References brix_uring_admin_on.
Referenced by ngx_stream_brix_postconfiguration().
brix_uring_killswitch_configure()
ngx_int_t brix_uring_killswitch_configure (ngx_conf_t * cf)
Definition at line 74 of file uring_admin.c.
References brix_uring_ks_zone, brix_uring_ks_zone_init(), name, and ngx_stream_brix_module.
Referenced by ngx_stream_brix_postconfiguration().
brix_uring_killswitch_get()
ngx_int_t brix_uring_killswitch_get (void)
Definition at line 114 of file uring_admin.c.
References brix_uring_killswitch_ptr().
Referenced by admin_io_uring_get(), and brix_uring_panic_handler().
brix_uring_killswitch_ptr()
ngx_atomic_t * brix_uring_killswitch_ptr (void)
Definition at line 93 of file uring_admin.c.
References brix_uring_ks_zone.
Referenced by brix_uring_killswitch_get(), and brix_uring_killswitch_set().
brix_uring_killswitch_set()
ngx_int_t brix_uring_killswitch_set (ngx_uint_t disabled)
Definition at line 102 of file uring_admin.c.
References brix_uring_killswitch_ptr().
Referenced by admin_io_uring_set(), and brix_uring_panic_handler().
brix_uring_ks_zone_init()
static ngx_int_t brix_uring_ks_zone_init (ngx_shm_zone_t * zone, void * data) static
Definition at line 46 of file uring_admin.c.
Referenced by brix_uring_killswitch_configure().
brix_uring_panic_handler()
static void brix_uring_panic_handler (ngx_event_t * ev) static
Definition at line 139 of file uring_admin.c.
References brix_uring_killswitch_get(), brix_uring_killswitch_set(), brix_uring_panic_path, BRIX_URING_PANIC_POLL_MS, and stat().
Referenced by brix_uring_panicfile_arm().
brix_uring_panicfile_arm()
ngx_int_t brix_uring_panicfile_arm (ngx_cycle_t * cycle, ngx_str_t * path)
Definition at line 161 of file uring_admin.c.
References brix_maint_timer_conn, brix_uring_panic_handler(), brix_uring_panic_path, brix_uring_panic_timer, and ngx_memcpy.
Variable Documentation
brix_uring_admin_on
ngx_uint_t brix_uring_admin_on static
Definition at line 32 of file uring_admin.c.
Referenced by brix_uring_admin_enabled(), and brix_uring_admin_set_enabled().
brix_uring_ks_zone
ngx_shm_zone_t* brix_uring_ks_zone static
Definition at line 29 of file uring_admin.c.
Referenced by brix_uring_killswitch_configure(), and brix_uring_killswitch_ptr().
brix_uring_panic_path
u_char brix_uring_panic_path[PATH_MAX] static
Definition at line 36 of file uring_admin.c.
Referenced by brix_uring_panic_handler(), and brix_uring_panicfile_arm().
brix_uring_panic_timer
ngx_event_t brix_uring_panic_timer static
Definition at line 35 of file uring_admin.c.
Referenced by brix_uring_panicfile_arm().