nginx-xrootd: client/lib/net/url.c File Reference
url.c File Reference
#include "brix.h"
#include "core/compat/host_split.h"
#include <string.h>
#include <stdlib.h>
Data Structures
struct web_scheme
Macros
#define BRIX_DEFAULT_PORT_LOCAL 1094
Functions
static int starts_with (const char *s, const char *prefix)
static int parse_authority (const char *auth, brix_url *out, brix_status *st)
static int parse_remote (const char *s, const char *after_scheme, brix_scheme scheme, brix_url *out, brix_status *st)
int brix_url_parse (const char *s, brix_url *out, brix_status *st)
int brix_endpoint_parse (const char *ep, brix_url *out, brix_status *st)
int brix_is_web_url (const char *s)
int brix_is_block_url (const char *s)
static const web_scheme * weburl_match_scheme (const char *s)
static const char * weburl_parse_bracket_host (const char *p, brix_weburl *out)
static int weburl_parse_plain_host (const char *hoststart, brix_weburl *out)
static int weburl_copy_path (const char *p, brix_weburl *out)
int brix_weburl_parse (const char *s, brix_weburl *out)
Variables
static const web_scheme WEB_SCHEMES []
Macro Definition Documentation
BRIX_DEFAULT_PORT_LOCAL
#define BRIX_DEFAULT_PORT_LOCAL 1094
Definition at line 22 of file url.c.
Function Documentation
brix_endpoint_parse()
int brix_endpoint_parse (const char * ep, brix_url * out, brix_status * st)
Definition at line 177 of file url.c.
References BRIX_DEFAULT_PORT_LOCAL, brix_status_set(), brix_url_parse(), brix_url::host, brix_url::port, brix_url::scheme, XRDC_EUSAGE, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by aio_root_mount(), brix_capture_playback(), brix_cli_connect(), brix_wait41_main(), compare_setup(), do_bench(), do_check(), do_compare_davs(), do_map(), do_metabench(), do_probe_robustness(), do_status(), do_topology(), doctor_one(), endpoint_to_url(), main(), parse_vmp(), probe_holder(), probe_open(), storascan_connect(), topo_report_cluster(), watch_probe_once(), xfs_root_mount(), xrd_caps(), xrd_certinfo(), xrd_clockskew_root(), xrd_doctor_probe(), xrd_ping(), xrd_run_battery(), and xrd_whoami().
brix_is_block_url()
int brix_is_block_url (const char * s)
Definition at line 271 of file url.c.
References s.
Referenced by brix_copy(), and copy_block().
brix_is_web_url()
int brix_is_web_url (const char * s)
Definition at line 246 of file url.c.
References s, starts_with(), and WEB_SCHEMES.
Referenced by both_web(), brix_copy(), build_and_preflight_credentials(), copy_web(), dest_is_dir(), ensure_web_dst_base(), entry_cksum(), entry_meta(), expand_source(), main(), recursive_place(), uses_cred_auth(), vfs_url_to_scheme(), xrd_measure_clock_skew(), xrd_run_battery(), xrdcp_dispatch_recursive_web_download(), xrdcp_hint_failed_source(), xrdcp_try_recursive_web(), and xrootdfs_aio_main().
brix_url_parse()
int brix_url_parse (const char * s, brix_url * out, brix_status * st)
Definition at line 112 of file url.c.
References brix_status_set(), parse_remote(), brix_url::path, s, brix_url::scheme, starts_with(), XRDC_EUSAGE, XRDC_SCHEME_LOCAL, XRDC_SCHEME_ROOT, XRDC_SCHEME_ROOTS, and XRDC_SCHEME_STDIO.
Referenced by brix_cli_cksum_main(), brix_copy_classify(), brix_endpoint_parse(), brix_glob(), ckcheck_connect(), cktree_run_remote(), copy_block(), copy_block_to_remote(), copy_remote_to_block(), copy_web(), dest_is_dir(), entry_cksum(), entry_meta(), fs_find_endpoint(), main(), map_fs_arg(), remove_source_entry(), and xrdcp_hint_failed_source().
brix_weburl_parse()
int brix_weburl_parse (const char * s, brix_weburl * out)
Definition at line 395 of file url.c.
References web_scheme::defport, brix_weburl::is_s3, web_scheme::is_s3, brix_weburl::port, web_scheme::prefix, brix_weburl::proto, web_scheme::proto, s, brix_weburl::tls, web_scheme::tls, weburl_copy_path(), weburl_match_scheme(), weburl_parse_bracket_host(), and weburl_parse_plain_host().
Referenced by aio_web_mount(), copy_web(), ensure_web_dst_base(), place_to_web(), recursive_web_download(), recursive_web_upload(), run_web_endpoint(), s3_be_open(), s3_be_stat(), vfs_url_to_scheme(), xrd_clockskew_http(), and xrd_run_battery().
parse_authority()
static int parse_authority (const char * auth, brix_url * out, brix_status * st) static
Definition at line 32 of file url.c.
References BRIX_DEFAULT_PORT_LOCAL, brix_split_host_port(), brix_status_set(), brix_url::host, brix_url::port, brix_url::user, and XRDC_EUSAGE.
Referenced by parse_remote().
parse_remote()
static int parse_remote (const char * s, const char * after_scheme, brix_scheme scheme, brix_url * out, brix_status * st) static
Definition at line 58 of file url.c.
References brix_status_set(), parse_authority(), brix_url::path, s, brix_url::scheme, scheme, brix_url::single_slash_path, and XRDC_EUSAGE.
Referenced by brix_url_parse().
starts_with()
static int starts_with (const char * s, const char * prefix) static
Definition at line 25 of file url.c.
References s.
Referenced by brix_is_web_url(), brix_url_parse(), and weburl_match_scheme().
weburl_copy_path()
static int weburl_copy_path (const char * p, brix_weburl * out) static
Definition at line 381 of file url.c.
References brix_weburl::path.
Referenced by brix_weburl_parse().
weburl_match_scheme()
static const web_scheme * weburl_match_scheme (const char * s) static
Definition at line 288 of file url.c.
References s, starts_with(), and WEB_SCHEMES.
Referenced by brix_weburl_parse().
weburl_parse_bracket_host()
static const char * weburl_parse_bracket_host (const char * p, brix_weburl * out) static
Definition at line 312 of file url.c.
References brix_weburl::host, and brix_weburl::port.
Referenced by brix_weburl_parse().
weburl_parse_plain_host()
static int weburl_parse_plain_host (const char * hoststart, brix_weburl * out) static
Definition at line 346 of file url.c.
References brix_weburl::host, and brix_weburl::port.
Referenced by brix_weburl_parse().
Variable Documentation
WEB_SCHEMES
const web_scheme WEB_SCHEMES[] static
Initial value:
= {
    { "https://", XRDC_WEB_HTTPS, 1, 0, 443 },
    { "http://",  XRDC_WEB_HTTP,  0, 0, 80  },
    { "davs://",  XRDC_WEB_DAVS,  1, 0, 443 },
    { "dav://",   XRDC_WEB_DAV,   0, 0, 80  },
    { "s3s://",   XRDC_WEB_S3S,   1, 1, 443 },
    { "s3://",    XRDC_WEB_S3,    0, 1, 80  },
}
Definition at line 236 of file url.c.
Referenced by brix_is_web_url(), and weburl_match_scheme().