nginx-xrootd: src/protocols/s3/usermeta.c File Reference
usermeta.c File Reference
#include "s3.h"
#include "usermeta.h"
#include "core/compat/uri.h"
#include "fs/vfs/vfs.h"
#include <errno.h>
#include <string.h>
Macros
#define S3_USERMETA_XATTR "user.s3.usermeta"
#define S3_USERMETA_PREFIX "x-amz-meta-"
#define S3_USERMETA_BLOB_MAX 16384 /* AWS user-metadata limit is 2 KiB; generous */
#define S3_USERMETA_KV_MAX 2048
Functions
static void s3_user_meta_vfs_ctx (ngx_http_request_t *r, const char *fs_path, ngx_http_s3_loc_conf_t *cf, brix_vfs_ctx_t *vctx)
static ssize_t s3_user_meta_load (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const char *fs_path, char *out, size_t outsz)
static ngx_int_t s3_user_meta_store (ngx_http_request_t *r, ngx_http_s3_loc_conf_t *cf, const char *fs_path, const char *blob, size_t blob_len)
static ngx_int_t s3_user_meta_append_kv (char *out, size_t outsz, size_t *pos, const char *klow, size_t knlen, const u_char *val, size_t vallen)
static ngx_int_t s3_user_meta_blob_from_headers (ngx_http_request_t *r, char *out, size_t outsz, size_t *out_len, int *any)
ngx_int_t s3_apply_put_user_metadata (ngx_http_request_t *r, const char *fs_path, const char *root_canon)
void s3_echo_user_metadata (ngx_http_request_t *r, const char *fs_path)
ngx_int_t s3_user_meta_copy (ngx_http_request_t *r, const char *src_fs_path, const char *dst_fs_path)
Macro Definition Documentation
S3_USERMETA_BLOB_MAX
#define S3_USERMETA_BLOB_MAX 16384 /* AWS user-metadata limit is 2 KiB; generous */
Definition at line 29 of file usermeta.c.
S3_USERMETA_KV_MAX
#define S3_USERMETA_KV_MAX 2048
Definition at line 30 of file usermeta.c.
S3_USERMETA_PREFIX
#define S3_USERMETA_PREFIX "x-amz-meta-"
Definition at line 28 of file usermeta.c.
S3_USERMETA_XATTR
#define S3_USERMETA_XATTR "user.s3.usermeta"
Definition at line 27 of file usermeta.c.
Function Documentation
s3_apply_put_user_metadata()
ngx_int_t s3_apply_put_user_metadata (ngx_http_request_t * r, const char * fs_path, const char * root_canon)
Definition at line 213 of file usermeta.c.
References ngx_http_brix_s3_module, s3_user_meta_blob_from_headers(), s3_user_meta_store(), and S3_USERMETA_BLOB_MAX.
Referenced by s3_chunk_finalize(), s3_handle_copy_object(), s3_put_aio_done(), and s3put_commit_and_headers().
s3_echo_user_metadata()
void s3_echo_user_metadata (ngx_http_request_t * r, const char * fs_path)
Definition at line 236 of file usermeta.c.
References brix_http_urldecode(), BRIX_URLDECODE_OK, BRIX_URLDECODE_PLUS_TO_SPACE, ngx_http_brix_s3_module, ngx_memcpy, ngx_pnalloc(), s3_set_header(), s3_user_meta_load(), S3_USERMETA_BLOB_MAX, S3_USERMETA_KV_MAX, and S3_USERMETA_PREFIX.
Referenced by s3_get_echo_headers(), and s3_handle_head().
s3_user_meta_append_kv()
static ngx_int_t s3_user_meta_append_kv (char * out, size_t outsz, size_t * pos, const char * klow, size_t knlen, const u_char * val, size_t vallen) static
Definition at line 110 of file usermeta.c.
References brix_http_urlencode(), and ngx_memcpy.
Referenced by s3_user_meta_blob_from_headers().
s3_user_meta_blob_from_headers()
static ngx_int_t s3_user_meta_blob_from_headers (ngx_http_request_t * r, char * out, size_t outsz, size_t * out_len, int * any) static
Definition at line 156 of file usermeta.c.
References key, s3_user_meta_append_kv(), S3_USERMETA_KV_MAX, and S3_USERMETA_PREFIX.
Referenced by s3_apply_put_user_metadata().
s3_user_meta_copy()
ngx_int_t s3_user_meta_copy (ngx_http_request_t * r, const char * src_fs_path, const char * dst_fs_path)
Definition at line 292 of file usermeta.c.
References ngx_http_brix_s3_module, s3_user_meta_load(), s3_user_meta_store(), and S3_USERMETA_BLOB_MAX.
Referenced by s3_handle_copy_object().
s3_user_meta_load()
static ssize_t s3_user_meta_load (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const char * fs_path, char * out, size_t outsz) static
Definition at line 57 of file usermeta.c.
References brix_vfs_getxattr(), s3_user_meta_vfs_ctx(), and S3_USERMETA_XATTR.
Referenced by s3_echo_user_metadata(), and s3_user_meta_copy().
s3_user_meta_store()
static ngx_int_t s3_user_meta_store (ngx_http_request_t * r, ngx_http_s3_loc_conf_t * cf, const char * fs_path, const char * blob, size_t blob_len) static
Definition at line 81 of file usermeta.c.
References brix_vfs_setxattr(), s3_user_meta_vfs_ctx(), and S3_USERMETA_XATTR.
Referenced by s3_apply_put_user_metadata(), and s3_user_meta_copy().
s3_user_meta_vfs_ctx()
static void s3_user_meta_vfs_ctx (ngx_http_request_t * r, const char * fs_path, ngx_http_s3_loc_conf_t * cf, brix_vfs_ctx_t * vctx) static
Definition at line 38 of file usermeta.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_S3, brix_vfs_ctx_init(), ngx_http_s3_loc_conf_t::cache_root_canon, ngx_http_s3_loc_conf_t::common, ngx_http_s3_req_ctx_t::identity, ngx_http_brix_s3_module, brix_vfs_ctx_t::pool, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by s3_user_meta_load(), and s3_user_meta_store().