nginx-xrootd: src/auth/token/validate.c File Reference
validate.c File Reference
#include "token_internal.h"
#include "b64url.h"
#include "json.h"
#include "scopes.h"
#include "macaroon.h"
#include "issuer_registry.h"
#include "subject_map.h"
#include "core/types/tunables.h"
#include <stdlib.h>
#include <string.h>
#include <time.h>
Functions
static void token_sanitize_for_log (const char *in, char *out, size_t outsz)
static int brix_token_malformed (ngx_log_t *log)
static void brix_token_extract_groups (const char *pay_json, size_t pay_len, brix_token_claims_t *claims)
static int token_sig_ok (const char *alg, const u_char *token, size_t signed_len, const u_char *sig_bin, size_t sig_len, EVP_PKEY *pkey)
int brix_token_validate (ngx_log_t *log, const char *token, size_t token_len, const brix_jwks_key_t *keys, int key_count, const char *expected_issuer, const char *expected_audience, const u_char *macaroon_secret, size_t secret_len, int clock_skew, brix_token_claims_t *claims)
int brix_token_peek_iss (const char *token, size_t token_len, char *out, size_t outsz)
int brix_token_validate_registry_authn (ngx_log_t *log, const char *token, size_t token_len, const brix_token_registry_t *reg, const u_char *macaroon_secret, size_t secret_len, int clock_skew, brix_token_claims_t *claims, const brix_token_issuer_t **out_issuer)
int brix_token_authz_strategy (const brix_token_issuer_t *is, const brix_token_claims_t *claims, const char *req_path, brix_token_op_e op)
int brix_token_validate_registry (ngx_log_t *log, const char *token, size_t token_len, const brix_token_registry_t *reg, const char *req_path, brix_token_op_e op, const u_char *macaroon_secret, size_t secret_len, int clock_skew, brix_token_claims_t *claims, int *out_issuer_bucket)
Function Documentation
brix_token_authz_strategy()
int brix_token_authz_strategy (const brix_token_issuer_t * is, const brix_token_claims_t * claims, const char * req_path, brix_token_op_e op)
Definition at line 581 of file validate.c.
References BRIX_AUTHZ_CAPABILITY, BRIX_AUTHZ_GROUP, BRIX_AUTHZ_MAPPING, brix_subject_mapfile_lookup(), brix_token_check_read(), brix_token_check_write(), brix_token_issuer_path_ok(), BRIX_TOKEN_OP_WRITE, brix_token_issuer_t::default_user, brix_token_claims_t::groups, brix_token_issuer_t::map_subject, brix_token_issuer_t::name_mapfile, brix_token_issuer_t::onmissing_fail, brix_token_claims_t::scope_count, brix_token_claims_t::scopes, brix_token_issuer_t::strategy, and brix_token_claims_t::sub.
Referenced by brix_identity_check_token_scope(), and brix_token_validate_registry().
brix_token_extract_groups()
static void brix_token_extract_groups (const char * pay_json, size_t pay_len, brix_token_claims_t * claims) static
Definition at line 94 of file validate.c.
References brix_token_claims_t::groups, and json_get_string_array().
Referenced by brix_token_validate().
brix_token_malformed()
static int brix_token_malformed (ngx_log_t * log) static
Definition at line 80 of file validate.c.
References log.
Referenced by brix_token_validate().
brix_token_peek_iss()
int brix_token_peek_iss (const char * token, size_t token_len, char * out, size_t outsz)
Definition at line 486 of file validate.c.
References b64url_decode(), json_get_string(), and xrdjwt_split().
Referenced by brix_token_validate_registry_authn().
brix_token_validate()
int brix_token_validate (ngx_log_t * log, const char * token, size_t token_len, const brix_jwks_key_t * keys, int key_count, const char * expected_issuer, const char * expected_audience, const u_char * macaroon_secret, size_t secret_len, int clock_skew, brix_token_claims_t * claims)
Definition at line 190 of file validate.c.
References brix_token_claims_t::aud, b64url_decode(), brix_macaroon_validate(), BRIX_MAX_TOKEN_SCOPES, brix_token_extract_groups(), brix_token_is_macaroon(), brix_token_malformed(), brix_token_parse_scopes(), brix_token_claims_t::exp, brix_token_claims_t::groups, brix_token_claims_t::iat, brix_token_claims_t::iss, json_get_int64(), json_get_string(), json_get_string_array(), json_has_member(), json_string_or_array_contains(), log, xrdjwt_seg::n, brix_token_claims_t::nbf, brix_jwks_key_t::pkey, brix_token_claims_t::scope_count, brix_token_claims_t::scope_raw, brix_token_claims_t::scopes, brix_token_claims_t::sub, token_sanitize_for_log(), token_sig_ok(), and xrdjwt_split().
Referenced by brix_handle_token_auth(), brix_token_validate_registry_authn(), s3_verify_bearer(), and webdav_verify_bearer_token().
brix_token_validate_registry()
int brix_token_validate_registry (ngx_log_t * log, const char * token, size_t token_len, const brix_token_registry_t * reg, const char * req_path, brix_token_op_e op, const u_char * macaroon_secret, size_t secret_len, int clock_skew, brix_token_claims_t * claims, int * out_issuer_bucket)
Definition at line 637 of file validate.c.
References brix_token_authz_strategy(), brix_token_validate_registry_authn(), log, brix_token_issuer_t::metric_bucket, and brix_token_issuer_t::name.
Referenced by scvmfs_check_bearer(), and webdav_verify_bearer_token().
brix_token_validate_registry_authn()
int brix_token_validate_registry_authn (ngx_log_t * log, const char * token, size_t token_len, const brix_token_registry_t * reg, const u_char * macaroon_secret, size_t secret_len, int clock_skew, brix_token_claims_t * claims, const brix_token_issuer_t ** out_issuer)
Definition at line 515 of file validate.c.
References brix_token_claims_t::aud, brix_token_issuer_t::audience_count, brix_token_issuer_t::audiences, brix_token_peek_iss(), brix_token_registry_find(), brix_token_validate(), brix_token_registry_t::global_audience_count, brix_token_registry_t::global_audiences, brix_token_issuer_t::issuer, brix_token_issuer_t::jwks_key_count, brix_token_issuer_t::jwks_keys, log, brix_token_issuer_t::name, and token_sanitize_for_log().
Referenced by brix_handle_token_auth(), and brix_token_validate_registry().
token_sanitize_for_log()
static void token_sanitize_for_log (const char * in, char * out, size_t outsz) static
Definition at line 41 of file validate.c.
References c, and hex().
Referenced by brix_token_validate(), and brix_token_validate_registry_authn().
token_sig_ok()
static int token_sig_ok (const char * alg, const u_char * token, size_t signed_len, const u_char * sig_bin, size_t sig_len, EVP_PKEY * pkey) static
Definition at line 142 of file validate.c.
References brix_token_verify_es256(), and brix_token_verify_rs256().
Referenced by brix_token_validate().