nginx-xrootd: src/auth/token/validate_internal.h File Reference
validate_internal.h File Reference
#include "token_internal.h"
#include "b64url.h"
Data Structures
struct token_hdr_t
Functions
void token_sanitize_for_log (const char *in, char *out, size_t outsz)
int brix_token_malformed (ngx_log_t *log)
int token_check_header (const brix_token_validate_args_t *a, const xrdjwt_seg *seg, token_hdr_t *hdr)
int token_verify_signature (const brix_token_validate_args_t *a, const xrdjwt_seg *seg, const token_hdr_t *hdr)
Function Documentation
brix_token_malformed()
int brix_token_malformed (ngx_log_t * log)
Definition at line 79 of file validate.c.
References log.
Referenced by brix_token_validate(), and token_check_header().
token_check_header()
int token_check_header (const brix_token_validate_args_t * a, const xrdjwt_seg * seg, token_hdr_t * hdr)
Definition at line 93 of file validate_sig.c.
References token_hdr_t::alg, b64url_decode(), brix_token_malformed(), json_get_string(), json_has_member(), token_hdr_t::kid, brix_token_validate_args_t::log, and token_sanitize_for_log().
Referenced by brix_token_validate().
token_sanitize_for_log()
void token_sanitize_for_log (const char * in, char * out, size_t outsz)
Definition at line 40 of file validate.c.
References c, and hex().
Referenced by brix_token_validate_registry_authn(), token_check_header(), token_check_issuer_audience(), token_log_valid(), token_select_key_by_kid(), and token_validate_macaroon().
token_verify_signature()
int token_verify_signature (const brix_token_validate_args_t * a, const xrdjwt_seg * seg, const token_hdr_t * hdr)
Definition at line 186 of file validate_sig.c.
References token_hdr_t::alg, token_sig_input_t::alg, b64url_decode(), brix_token_validate_args_t::key_count, brix_token_validate_args_t::keys, token_hdr_t::kid, brix_token_validate_args_t::log, xrdjwt_seg::n, brix_jwks_key_t::pkey, token_sig_input_t::sig, token_sig_input_t::sig_len, token_sig_input_t::signed_data, token_sig_input_t::signed_len, brix_token_validate_args_t::token, token_select_key_by_kid(), and token_sig_ok().
Referenced by brix_token_validate().