nginx-xrootd: src/auth/token/validate_sig.c File Reference
validate_sig.c File Reference
#include "token_internal.h"
#include "validate_internal.h"
#include "b64url.h"
#include "json.h"
#include <string.h>
Data Structures
struct token_sig_input_t
Functions
static int token_sig_ok (const token_sig_input_t *in, EVP_PKEY *pkey)
int token_check_header (const brix_token_validate_args_t *a, const xrdjwt_seg *seg, token_hdr_t *hdr)
static EVP_PKEY * token_select_key_by_kid (const brix_token_validate_args_t *a, const token_hdr_t *hdr)
int token_verify_signature (const brix_token_validate_args_t *a, const xrdjwt_seg *seg, const token_hdr_t *hdr)
Function Documentation
token_check_header()
int token_check_header (const brix_token_validate_args_t * a, const xrdjwt_seg * seg, token_hdr_t * hdr)
Definition at line 93 of file validate_sig.c.
References token_hdr_t::alg, b64url_decode(), brix_token_malformed(), json_get_string(), json_has_member(), token_hdr_t::kid, brix_token_validate_args_t::log, and token_sanitize_for_log().
Referenced by brix_token_validate().
token_select_key_by_kid()
static EVP_PKEY * token_select_key_by_kid (const brix_token_validate_args_t * a, const token_hdr_t * hdr) static
Definition at line 148 of file validate_sig.c.
References brix_token_validate_args_t::key_count, brix_token_validate_args_t::keys, brix_jwks_key_t::kid, token_hdr_t::kid, brix_token_validate_args_t::log, brix_jwks_key_t::pkey, and token_sanitize_for_log().
Referenced by token_verify_signature().
token_sig_ok()
static int token_sig_ok (const token_sig_input_t * in, EVP_PKEY * pkey) static
Definition at line 66 of file validate_sig.c.
References token_sig_input_t::alg, brix_token_verify_es256(), brix_token_verify_rs256(), token_sig_input_t::sig, token_sig_input_t::sig_len, token_sig_input_t::signed_data, and token_sig_input_t::signed_len.
Referenced by token_verify_signature().
token_verify_signature()
int token_verify_signature (const brix_token_validate_args_t * a, const xrdjwt_seg * seg, const token_hdr_t * hdr)
Definition at line 186 of file validate_sig.c.
References token_hdr_t::alg, token_sig_input_t::alg, b64url_decode(), brix_token_validate_args_t::key_count, brix_token_validate_args_t::keys, token_hdr_t::kid, brix_token_validate_args_t::log, xrdjwt_seg::n, brix_jwks_key_t::pkey, token_sig_input_t::sig, token_sig_input_t::sig_len, token_sig_input_t::signed_data, token_sig_input_t::signed_len, brix_token_validate_args_t::token, token_select_key_by_kid(), and token_sig_ok().
Referenced by brix_token_validate().