nginx-xrootd: src/auth/token/validate_registry.c File Reference
validate_registry.c File Reference
#include "token_internal.h"
#include "validate_internal.h"
#include "issuer_registry.h"
#include "subject_map.h"
#include "b64url.h"
#include "json.h"
#include "scopes.h"
#include <string.h>
Functions
int brix_token_peek_iss (const char *token, size_t token_len, char *out, size_t outsz)
int brix_token_validate_registry_authn (const brix_token_registry_args_t *a, const brix_token_issuer_t **out_issuer)
int brix_token_authz_strategy (const brix_token_issuer_t *is, const brix_token_claims_t *claims, const char *req_path, brix_token_op_e op)
int brix_token_validate_registry (const brix_token_registry_args_t *a, const char *req_path, brix_token_op_e op, int *out_issuer_bucket)
Function Documentation
brix_token_authz_strategy()
int brix_token_authz_strategy (const brix_token_issuer_t * is, const brix_token_claims_t * claims, const char * req_path, brix_token_op_e op)
Definition at line 151 of file validate_registry.c.
References BRIX_AUTHZ_CAPABILITY, BRIX_AUTHZ_GROUP, BRIX_AUTHZ_MAPPING, brix_subject_mapfile_lookup(), brix_token_check_read(), brix_token_check_write(), brix_token_issuer_path_ok(), BRIX_TOKEN_OP_WRITE, brix_token_issuer_t::default_user, brix_token_claims_t::groups, brix_token_issuer_t::map_subject, brix_token_issuer_t::name_mapfile, brix_token_issuer_t::onmissing_fail, op, brix_token_claims_t::scope_count, brix_token_claims_t::scopes, brix_token_issuer_t::strategy, and brix_token_claims_t::sub.
Referenced by brix_identity_check_token_scope(), and brix_token_validate_registry().
brix_token_peek_iss()
int brix_token_peek_iss (const char * token, size_t token_len, char * out, size_t outsz)
Definition at line 47 of file validate_registry.c.
References b64url_decode(), json_get_string(), and xrdjwt_split().
Referenced by brix_token_validate_registry_authn().
brix_token_validate_registry()
int brix_token_validate_registry (const brix_token_registry_args_t * a, const char * req_path, brix_token_op_e op, int * out_issuer_bucket)
Definition at line 207 of file validate_registry.c.
References brix_token_authz_strategy(), brix_token_validate_registry_authn(), brix_token_registry_args_t::claims, brix_token_registry_args_t::log, brix_token_issuer_t::metric_bucket, brix_token_issuer_t::name, and op.
Referenced by scvmfs_check_bearer(), and wt_validate_registry().
brix_token_validate_registry_authn()
int brix_token_validate_registry_authn (const brix_token_registry_args_t * a, const brix_token_issuer_t ** out_issuer)
Definition at line 76 of file validate_registry.c.
References brix_token_claims_t::aud, brix_token_issuer_t::audience_count, brix_token_issuer_t::audiences, brix_token_peek_iss(), brix_token_registry_find(), brix_token_validate(), brix_token_registry_args_t::claims, brix_token_validate_args_t::claims, brix_token_registry_args_t::clock_skew, brix_token_validate_args_t::clock_skew, brix_token_validate_args_t::expected_audience, brix_token_validate_args_t::expected_issuer, brix_token_registry_t::global_audience_count, brix_token_registry_t::global_audiences, brix_token_issuer_t::issuer, brix_token_issuer_t::jwks_key_count, brix_token_issuer_t::jwks_keys, brix_token_validate_args_t::key_count, brix_token_validate_args_t::keys, brix_token_registry_args_t::log, brix_token_validate_args_t::log, brix_token_registry_args_t::macaroon_secret, brix_token_validate_args_t::macaroon_secret, brix_token_issuer_t::name, brix_token_registry_args_t::reg, brix_token_registry_args_t::secret_len, brix_token_validate_args_t::secret_len, brix_token_registry_args_t::token, brix_token_validate_args_t::token, brix_token_registry_args_t::token_len, brix_token_validate_args_t::token_len, and token_sanitize_for_log().
Referenced by brix_token_validate_registry(), and tokenauth_verify_or_cache().