nginx-xrootd: src/fs/cache/verify.h File Reference
verify.h File Reference
#include "cache_internal.h"
#include "fs/cache/origin/transport.h"
Enumerations
enum brix_cache_verify_mode_e { BRIX_CACHE_VERIFY_OFF = 0 , BRIX_CACHE_VERIFY_BESTEFFORT , BRIX_CACHE_VERIFY_REQUIRE , BRIX_CACHE_VERIFY_CVMFS_CAS }
enum brix_cache_verify_result_e { BRIX_CACHE_VERIFY_VERIFIED = 0 , BRIX_CACHE_VERIFY_UNVERIFIED , BRIX_CACHE_VERIFY_MISMATCH , BRIX_CACHE_VERIFY_ERROR }
Functions
brix_cache_verify_result_e brix_cache_verify_part (brix_cache_fill_t *t, const char *part_path, const brix_cache_digest_t *origin, brix_cache_verify_mode_e mode, char *out_alg, char *out_hex)
brix_cache_verify_result_e brix_cache_verify_cvmfs_cas (const char *part_path, const char *key, ngx_log_t *log, char *out_alg, char *out_hex)
void brix_cache_quarantine_part (const char *part_path, const char *quarantine_dir, ngx_log_t *log)
Enumeration Type Documentation
brix_cache_verify_mode_e
enum brix_cache_verify_mode_e
Enumerator
BRIX_CACHE_VERIFY_OFF
BRIX_CACHE_VERIFY_BESTEFFORT
BRIX_CACHE_VERIFY_REQUIRE
BRIX_CACHE_VERIFY_CVMFS_CAS
Definition at line 37 of file verify.h.
brix_cache_verify_result_e
enum brix_cache_verify_result_e
Enumerator
BRIX_CACHE_VERIFY_VERIFIED
BRIX_CACHE_VERIFY_UNVERIFIED
BRIX_CACHE_VERIFY_MISMATCH
BRIX_CACHE_VERIFY_ERROR
Definition at line 47 of file verify.h.
Function Documentation
brix_cache_quarantine_part()
void brix_cache_quarantine_part (const char * part_path, const char * quarantine_dir, ngx_log_t * log)
Definition at line 286 of file verify.c.
References log, and PATH_MAX.
Referenced by cache_fill_verify().
brix_cache_verify_cvmfs_cas()
brix_cache_verify_result_e brix_cache_verify_cvmfs_cas (const char * part_path, const char * key, ngx_log_t * log, char * out_alg, char * out_hex)
Definition at line 230 of file verify.c.
References brix_cache_hex_ieq(), BRIX_CACHE_VERIFY_ERROR, BRIX_CACHE_VERIFY_MISMATCH, BRIX_CACHE_VERIFY_UNVERIFIED, BRIX_CACHE_VERIFY_VERIFIED, brix_checksum_hex_name_fd(), close(), hex(), key, log, ngx_memcpy, and open().
Referenced by cache_fill_verify().
brix_cache_verify_part()
brix_cache_verify_result_e brix_cache_verify_part (brix_cache_fill_t * t, const char * part_path, const brix_cache_digest_t * origin, brix_cache_verify_mode_e mode, char * out_alg, char * out_hex)
Definition at line 171 of file verify.c.
References brix_cache_digest_t::alg, brix_cache_hex_ieq(), brix_cache_set_syserror(), brix_cache_verify_emit(), BRIX_CACHE_VERIFY_ERROR, BRIX_CACHE_VERIFY_MISMATCH, brix_cache_verify_no_origin(), BRIX_CACHE_VERIFY_OFF, brix_cache_verify_report_mismatch(), brix_cache_verify_unsupported(), BRIX_CACHE_VERIFY_UNVERIFIED, BRIX_CACHE_VERIFY_VERIFIED, brix_checksum_hex_name_fd(), brix_cache_fill_t::c, close(), hex(), brix_cache_digest_t::hex, kXR_IOError, log, and open().