nginx-xrootd: src/fs/cache/verify.c File Reference
verify.c File Reference
#include "verify.h"
#include "core/compat/checksum.h"
#include "protocols/cvmfs/classify.h"
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <time.h>
#include <unistd.h>
Functions
static int brix_cache_hex_ieq (const char *a, const char *b)
static brix_cache_verify_result_e brix_cache_verify_no_origin (brix_cache_fill_t *t, brix_cache_verify_mode_e mode)
static brix_cache_verify_result_e brix_cache_verify_unsupported (brix_cache_fill_t *t, const brix_cache_digest_t *origin, brix_cache_verify_mode_e mode, ngx_log_t *log, const char *part_path)
static void brix_cache_verify_report_mismatch (brix_cache_fill_t *t, ngx_log_t *log, const char *part_path, const char *alg_used, const brix_cache_digest_t *origin, const char *hex)
static void brix_cache_verify_emit (char *out_alg, char *out_hex, const char *alg_used, const char *hex)
brix_cache_verify_result_e brix_cache_verify_part (brix_cache_fill_t *t, const char *part_path, const brix_cache_digest_t *origin, brix_cache_verify_mode_e mode, char *out_alg, char *out_hex)
brix_cache_verify_result_e brix_cache_verify_cvmfs_cas (const char *part_path, const char *key, ngx_log_t *log, char *out_alg, char *out_hex)
void brix_cache_quarantine_part (const char *part_path, const char *quarantine_dir, ngx_log_t *log)
Function Documentation
brix_cache_hex_ieq()
static int brix_cache_hex_ieq (const char * a, const char * b) static
Definition at line 27 of file verify.c.
Referenced by brix_cache_verify_cvmfs_cas(), and brix_cache_verify_part().
brix_cache_quarantine_part()
void brix_cache_quarantine_part (const char * part_path, const char * quarantine_dir, ngx_log_t * log)
Definition at line 286 of file verify.c.
References log, and PATH_MAX.
Referenced by cache_fill_verify_reject().
brix_cache_verify_cvmfs_cas()
brix_cache_verify_result_e brix_cache_verify_cvmfs_cas (const char * part_path, const char * key, ngx_log_t * log, char * out_alg, char * out_hex)
Definition at line 230 of file verify.c.
References brix_cache_hex_ieq(), BRIX_CACHE_VERIFY_ERROR, BRIX_CACHE_VERIFY_MISMATCH, BRIX_CACHE_VERIFY_UNVERIFIED, BRIX_CACHE_VERIFY_VERIFIED, brix_checksum_hex_name_fd(), close(), hex(), key, log, ngx_memcpy, and open().
Referenced by cache_fill_verify().
brix_cache_verify_emit()
static void brix_cache_verify_emit (char * out_alg, char * out_hex, const char * alg_used, const char * hex) static
Definition at line 154 of file verify.c.
References hex(), and ngx_memcpy.
Referenced by brix_cache_verify_part().
brix_cache_verify_no_origin()
static brix_cache_verify_result_e brix_cache_verify_no_origin (brix_cache_fill_t * t, brix_cache_verify_mode_e mode) static
Definition at line 53 of file verify.c.
References brix_cache_set_error(), BRIX_CACHE_VERIFY_ERROR, BRIX_CACHE_VERIFY_REQUIRE, BRIX_CACHE_VERIFY_UNVERIFIED, and kXR_ChkSumErr.
Referenced by brix_cache_verify_part().
brix_cache_verify_part()
brix_cache_verify_result_e brix_cache_verify_part (brix_cache_fill_t * t, const char * part_path, const brix_cache_digest_t * origin, brix_cache_verify_mode_e mode, char * out_alg, char * out_hex)
Definition at line 171 of file verify.c.
References brix_cache_digest_t::alg, brix_cache_hex_ieq(), brix_cache_set_syserror(), brix_cache_verify_emit(), BRIX_CACHE_VERIFY_ERROR, BRIX_CACHE_VERIFY_MISMATCH, brix_cache_verify_no_origin(), BRIX_CACHE_VERIFY_OFF, brix_cache_verify_report_mismatch(), brix_cache_verify_unsupported(), BRIX_CACHE_VERIFY_UNVERIFIED, BRIX_CACHE_VERIFY_VERIFIED, brix_checksum_hex_name_fd(), brix_cache_fill_t::c, close(), hex(), brix_cache_digest_t::hex, kXR_IOError, log, and open().
brix_cache_verify_report_mismatch()
static void brix_cache_verify_report_mismatch (brix_cache_fill_t * t, ngx_log_t * log, const char * part_path, const char * alg_used, const brix_cache_digest_t * origin, const char * hex) static
Definition at line 121 of file verify.c.
References brix_cache_set_error(), hex(), brix_cache_digest_t::hex, kXR_ChkSumErr, and log.
Referenced by brix_cache_verify_part().
brix_cache_verify_unsupported()
static brix_cache_verify_result_e brix_cache_verify_unsupported (brix_cache_fill_t * t, const brix_cache_digest_t * origin, brix_cache_verify_mode_e mode, ngx_log_t * log, const char * part_path) static
Definition at line 82 of file verify.c.
References brix_cache_digest_t::alg, brix_cache_set_error(), BRIX_CACHE_VERIFY_ERROR, BRIX_CACHE_VERIFY_REQUIRE, BRIX_CACHE_VERIFY_UNVERIFIED, kXR_ChkSumErr, and log.
Referenced by brix_cache_verify_part().