nginx-xrootd: client/lib/core/version.h File Reference
version.h File Reference
Macros
#define BRIX_CLIENT_VERSION "dev"
#define BRIX_USAGE_FOOTER(TOOL)
Functions
static const char * brix_client_version (void)
Macro Definition Documentation
BRIX_CLIENT_VERSION
#define BRIX_CLIENT_VERSION "dev"
Definition at line 24 of file version.h.
BRIX_USAGE_FOOTER
#define BRIX_USAGE_FOOTER (TOOL)
Value:
    "config: ~/.xrdrc defines endpoint aliases and credentials "                \
        "(see brix-env(7))\n"                                                   \
    "docs:   man " TOOL "   \xc2\xb7   exit codes are listed at the end of "   \
        "the man page\n"
Definition at line 32 of file version.h.
Function Documentation
brix_client_version()
static const char * brix_client_version (void) inline static
Definition at line 44 of file version.h.
References BRIX_CLIENT_VERSION.
Referenced by aio_parse_args(), brix_cli_cksum_main(), brix_mpxstats_main(), brix_qstats_main(), brix_wait41_main(), brix_xrdcinfo_main(), ckv_handle_early_flags(), cmd_version(), main(), opt_early_exit(), opts_parse_universal(), xrdcp_parse_option(), xrdprep_handle_meta_flags(), and xrootdfs_aio_main().