nginx-xrootd: client/lib/fs/vfs_block.c File Reference
vfs_block.c File Reference
#include "vfs.h"
#include "core/aio/uring.h"
#include "brix.h"
#include "fs/backend/sd.h"
#include "fs/core/vfs_core.h"
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
struct vfs_block_file
Functions
static int block_ring_select (int fd, int mode, brix_disk_ring **ring, brix_status *st)
static ssize_t block_pread (brix_vfs_file *f, int64_t off, void *buf, size_t n, brix_status *st)
static int block_pwrite (brix_vfs_file *f, int64_t off, const void *buf, size_t n, brix_status *st)
static int block_fstat (brix_vfs_file *f, brix_vfs_stat *out, brix_status *st)
static int block_truncate (brix_vfs_file *f, int64_t size, brix_status *st)
static int block_sync (brix_vfs_file *f, brix_status *st)
static int block_commit (brix_vfs_file *f, brix_status *st)
static void block_abort (brix_vfs_file *f)
static void block_close (brix_vfs_file *f)
static int block_be_open (const brix_vfs_backend *be, const char *path, int flags, const brix_vfs_open_opts *opts, brix_vfs_file **out, brix_status *st)
static int block_be_stat (const brix_vfs_backend *be, const char *path, brix_vfs_stat *out, brix_status *st)
const brix_vfs_backend * brix_vfs_block_backend (void)
Variables
static const brix_vfs_ops s_block_ops
static const brix_vfs_backend s_block_backend
Function Documentation
block_abort()
static void block_abort (brix_vfs_file * f) static
Definition at line 304 of file vfs_block.c.
block_be_open()
static int block_be_open (const brix_vfs_backend * be, const char * path, int flags, const brix_vfs_open_opts * opts, brix_vfs_file ** out, brix_status * st) static
Definition at line 359 of file vfs_block.c.
References vfs_block_file::base, block_ring_select(), brix_sd_block_open_unconfined(), BRIX_SD_O_NOFOLLOW, BRIX_SD_O_READ, BRIX_SD_O_WRITE, brix_status_set(), brix_vfs_file::caps, close(), vfs_block_file::fd, brix_vfs_open_opts::io_uring, brix_vfs_file::ops, vfs_block_file::path, vfs_block_file::ring, s_block_ops, XRDC_EIO, XRDC_IO_URING_AUTO, XRDC_VFS_CAP_FADVISE, XRDC_VFS_CAP_RANDOM_WRITE, and XRDC_VFS_WRITE.
block_be_stat()
static int block_be_stat (const brix_vfs_backend * be, const char * path, brix_vfs_stat * out, brix_status * st) static
Definition at line 444 of file vfs_block.c.
References brix_sd_block_driver, brix_sd_block_open_unconfined(), BRIX_SD_O_NOFOLLOW, BRIX_SD_O_READ, brix_sd_posix_wrap(), brix_status_set(), close(), brix_vfs_stat::exists, brix_vfs_stat::is_dir, brix_vfs_stat::mtime, brix_vfs_stat::size, brix_sd_stat_t::size, stat(), and XRDC_EIO.
block_close()
static void block_close (brix_vfs_file * f) static
Definition at line 318 of file vfs_block.c.
References brix_disk_ring_destroy(), close(), vfs_block_file::fd, vfs_block_file::path, and vfs_block_file::ring.
block_commit()
static int block_commit (brix_vfs_file * f, brix_status * st) static
Definition at line 272 of file vfs_block.c.
References brix_disk_ring_flush(), brix_sd_posix_wrap(), brix_status_set(), vfs_block_file::fd, vfs_block_file::ring, XRDC_EIO, and xvfs_fsync().
block_fstat()
static int block_fstat (brix_vfs_file * f, brix_vfs_stat * out, brix_status * st) static
Definition at line 190 of file vfs_block.c.
References brix_sd_block_driver, brix_sd_posix_wrap(), brix_status_set(), brix_vfs_stat::exists, vfs_block_file::fd, brix_vfs_stat::is_dir, brix_sd_stat_t::is_dir, brix_vfs_stat::mtime, brix_sd_stat_t::mtime, brix_vfs_stat::size, brix_sd_stat_t::size, and XRDC_EIO.
block_pread()
static ssize_t block_pread (brix_vfs_file * f, int64_t off, void * buf, size_t n, brix_status * st) static
Definition at line 111 of file vfs_block.c.
References brix_disk_ring_pread(), brix_sd_posix_wrap(), brix_status_set(), vfs_block_file::fd, vfs_block_file::ring, XRDC_EIO, and xvfs_pread_once().
block_pwrite()
static int block_pwrite (brix_vfs_file * f, int64_t off, const void * buf, size_t n, brix_status * st) static
Definition at line 144 of file vfs_block.c.
References brix_disk_ring_bufsz(), brix_disk_ring_pwrite(), brix_sd_posix_wrap(), brix_status_set(), vfs_block_file::fd, vfs_block_file::ring, XRDC_EIO, and xvfs_pwrite_full().
block_ring_select()
static int block_ring_select (int fd, int mode, brix_disk_ring ** ring, brix_status * st) static
Definition at line 69 of file vfs_block.c.
References brix_disk_ring_create(), brix_status_clear(), brix_status_set(), brix_uring_available(), XRDC_EUNSUPPORTED, XRDC_IO_URING_OFF, and XRDC_IO_URING_ON.
Referenced by block_be_open().
block_sync()
static int block_sync (brix_vfs_file * f, brix_status * st) static
Definition at line 240 of file vfs_block.c.
References brix_disk_ring_flush(), brix_sd_posix_wrap(), brix_status_set(), vfs_block_file::fd, vfs_block_file::ring, XRDC_EIO, and xvfs_fsync().
block_truncate()
static int block_truncate (brix_vfs_file * f, int64_t size, brix_status * st) static
Definition at line 223 of file vfs_block.c.
References brix_status_set(), and XRDC_EUSAGE.
brix_vfs_block_backend()
const brix_vfs_backend * brix_vfs_block_backend (void)
Definition at line 510 of file vfs_block.c.
References s_block_backend.
Referenced by vfs_init_backends().
Variable Documentation
s_block_backend
const brix_vfs_backend s_block_backend static
Initial value:
= {
    .scheme = "block",
    .caps   = (XRDC_VFS_CAP_RANDOM_WRITE | XRDC_VFS_CAP_FADVISE),
    .open   = block_be_open,
    .stat   = block_be_stat,
}
Definition at line 492 of file vfs_block.c.
Referenced by brix_vfs_block_backend().
s_block_ops
const brix_vfs_ops s_block_ops static
Initial value:
= {
    .pread    = block_pread,
    .pwrite   = block_pwrite,
    .fstat    = block_fstat,
    .truncate = block_truncate,
    .sync     = block_sync,
    .commit   = block_commit,
    .abort    = block_abort,
    .close    = block_close,
}
Definition at line 333 of file vfs_block.c.
Referenced by block_be_open().