nginx-xrootd: src/fs/vfs/vfs_backend_internal.h File Reference
vfs_backend_internal.h File Reference
#include "vfs_backend_registry.h"
#include "fs/tier/tier.h"
#include <limits.h>
Data Structures
struct brix_vfs_backend_entry_t
Macros
#define BRIX_VFS_BACKEND_MAX 64
Functions
brix_vfs_backend_entry_t * brix_vfs_backend_entry_find (const char *root_canon)
brix_vfs_backend_entry_t * brix_vfs_backend_entry_get_or_create (const char *root_canon)
brix_sd_instance_t * brix_vfs_backend_build_source (brix_vfs_backend_entry_t *e, ngx_log_t *log)
Macro Definition Documentation
BRIX_VFS_BACKEND_MAX
#define BRIX_VFS_BACKEND_MAX 64
Definition at line 103 of file vfs_backend_internal.h.
Function Documentation
brix_vfs_backend_build_source()
brix_sd_instance_t * brix_vfs_backend_build_source (brix_vfs_backend_entry_t * e, ngx_log_t * log)
Definition at line 368 of file vfs_backend_registry_source.c.
References brix_vfs_backend_entry_t::backend, brix_vbr_build_posix(), brix_vbr_source_table, brix_vbr_source_desc_t::build, log, and brix_vbr_source_desc_t::name.
Referenced by brix_vfs_backend_entry_build().
brix_vfs_backend_entry_find()
brix_vfs_backend_entry_t * brix_vfs_backend_entry_find (const char * root_canon)
Definition at line 27 of file vfs_backend_registry.c.
References brix_vfs_backend_count, and brix_vfs_backends.
Referenced by brix_vfs_backend_config(), brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_http_endpoint(), brix_vfs_backend_http_endpoint_at(), brix_vfs_backend_register_http_upstream(), brix_vfs_backend_set_credential(), brix_vfs_backend_set_http_ranks(), brix_vfs_backend_set_staging(), and vfs_backend_add_http_endpoint().
brix_vfs_backend_entry_get_or_create()
brix_vfs_backend_entry_t * brix_vfs_backend_entry_get_or_create (const char * root_canon)
Definition at line 64 of file vfs_backend_registry.c.
References brix_vfs_backend_count, brix_vfs_backend_entry_find(), BRIX_VFS_BACKEND_MAX, brix_vfs_backends, and brix_vfs_backend_entry_t::root_canon.
Referenced by brix_vfs_backend_config(), brix_vfs_backend_config_cache_cold_store(), brix_vfs_backend_config_cache_peers(), brix_vfs_backend_config_cache_store(), brix_vfs_backend_config_ceph(), brix_vfs_backend_config_cephfs_ro(), brix_vfs_backend_config_http(), brix_vfs_backend_config_s3(), brix_vfs_backend_config_stage_store(), brix_vfs_backend_config_tape(), brix_vfs_backend_config_xroot(), and brix_vfs_backend_register_http_upstream().