nginx-xrootd: src/fs/vfs/vfs_xattr.c File Reference
vfs_xattr.c File Reference
#include "vfs_internal.h"
#include <sys/xattr.h>
Functions
static ssize_t brix_vfs_xattr_observe_count (const brix_vfs_ctx_t *ctx, const char *path, ssize_t n, ngx_msec_t start)
ssize_t brix_vfs_getxattr (brix_vfs_ctx_t *ctx, const char *name, void *buf, size_t bufsz)
ssize_t brix_vfs_listxattr (brix_vfs_ctx_t *ctx, void *buf, size_t bufsz)
static ngx_int_t brix_vfs_xattr_observe_mut (const brix_vfs_ctx_t *ctx, const char *path, int rc, size_t nbytes, ngx_msec_t start)
static ngx_int_t brix_vfs_xattr_write_gate (brix_vfs_ctx_t *ctx, const char *path, const brix_sd_driver_t *drv, brix_sd_ucred_t *store, brix_sd_cred_t *cred, int *use_cred, ngx_msec_t start)
ngx_int_t brix_vfs_setxattr (brix_vfs_ctx_t *ctx, const char *name, const void *value, size_t len, int flags)
ngx_int_t brix_vfs_removexattr (brix_vfs_ctx_t *ctx, const char *name)
ssize_t brix_vfs_fgetxattr (const brix_vfs_ctx_t *ctx, int fd, const char *name, void *buf, size_t bufsz)
ssize_t brix_vfs_flistxattr (const brix_vfs_ctx_t *ctx, int fd, void *buf, size_t bufsz)
ngx_int_t brix_vfs_fsetxattr (const brix_vfs_ctx_t *ctx, int fd, const char *name, const void *value, size_t len, int flags)
ngx_int_t brix_vfs_fremovexattr (const brix_vfs_ctx_t *ctx, int fd, const char *name)
Function Documentation
brix_vfs_fgetxattr()
ssize_t brix_vfs_fgetxattr (const brix_vfs_ctx_t * ctx, int fd, const char * name, void * buf, size_t bufsz)
Definition at line 310 of file vfs_xattr.c.
References brix_vfs_now_ns(), brix_vfs_xattr_observe_count(), and name.
Referenced by fattr_list_append_value(), fattr_read_value(), fattr_read_value_size(), and integrity_xattr_read().
brix_vfs_flistxattr()
ssize_t brix_vfs_flistxattr (const brix_vfs_ctx_t * ctx, int fd, void * buf, size_t bufsz)
Definition at line 320 of file vfs_xattr.c.
References brix_vfs_now_ns(), and brix_vfs_xattr_observe_count().
Referenced by fattr_list_read_names().
brix_vfs_fremovexattr()
ngx_int_t brix_vfs_fremovexattr (const brix_vfs_ctx_t * ctx, int fd, const char * name)
Definition at line 345 of file vfs_xattr.c.
References BRIX_METRIC_OP_XATTR, brix_vfs_now_ns(), brix_vfs_observe_ctx_op(), and name.
Referenced by brix_integrity_invalidate_fd(), and fattr_del().
brix_vfs_fsetxattr()
ngx_int_t brix_vfs_fsetxattr (const brix_vfs_ctx_t * ctx, int fd, const char * name, const void * value, size_t len, int flags)
Definition at line 330 of file vfs_xattr.c.
References BRIX_METRIC_OP_XATTR, brix_vfs_now_ns(), brix_vfs_observe_ctx_op(), and name.
Referenced by fattr_set(), and integrity_xattr_write_rc().
brix_vfs_getxattr()
ssize_t brix_vfs_getxattr (brix_vfs_ctx_t * ctx, const char * name, void * buf, size_t bufsz)
Definition at line 49 of file vfs_xattr.c.
References brix_getxattr_confined_canon(), brix_sd_getxattr_maybe_cred(), brix_sd_ucred_wipe(), brix_vfs_cred_gate_active(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_now_ns(), brix_vfs_ns_cred(), brix_vfs_ns_leaf(), brix_vfs_require_confined(), brix_vfs_xattr_observe_count(), brix_vfs_ctx_t::log, name, brix_vfs_ctx_t::root_canon, and brix_vfs_ctx_t::sd.
Referenced by brix_query_xattr(), fattr_list_append_value(), fattr_read_value(), fattr_read_value_size(), s3_tag_load(), s3_user_meta_load(), webdav_dead_prop_read_value(), and webdav_lock_xattr_read().
brix_vfs_listxattr()
ssize_t brix_vfs_listxattr (brix_vfs_ctx_t * ctx, void * buf, size_t bufsz)
Definition at line 102 of file vfs_xattr.c.
References brix_listxattr_confined_canon(), brix_sd_listxattr_maybe_cred(), brix_sd_ucred_wipe(), brix_vfs_cred_gate_active(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_now_ns(), brix_vfs_ns_cred(), brix_vfs_ns_leaf(), brix_vfs_require_confined(), brix_vfs_xattr_observe_count(), brix_vfs_ctx_t::log, brix_vfs_ctx_t::root_canon, and brix_vfs_ctx_t::sd.
Referenced by brix_query_xattr(), fattr_list_read_names(), fattr_recurse_file(), and webdav_dead_props_append_all().
brix_vfs_removexattr()
ngx_int_t brix_vfs_removexattr (brix_vfs_ctx_t * ctx, const char * name)
Definition at line 256 of file vfs_xattr.c.
References brix_removexattr_confined_canon(), brix_sd_removexattr_maybe_cred(), brix_sd_ucred_wipe(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_now_ns(), brix_vfs_ns_leaf(), brix_vfs_require_confined(), brix_vfs_xattr_observe_mut(), brix_vfs_xattr_write_gate(), brix_vfs_ctx_t::log, name, brix_vfs_ctx_t::root_canon, and brix_vfs_ctx_t::sd.
Referenced by brix_integrity_invalidate_path(), fattr_del(), s3_tag_store(), webdav_dead_prop_remove(), webdav_lock_sweep_remove(), and webdav_lock_xattr_delete().
brix_vfs_setxattr()
ngx_int_t brix_vfs_setxattr (brix_vfs_ctx_t * ctx, const char * name, const void * value, size_t len, int flags)
Definition at line 210 of file vfs_xattr.c.
References brix_sd_setxattr_maybe_cred(), brix_sd_ucred_wipe(), brix_setxattr_confined_canon(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_now_ns(), brix_vfs_ns_leaf(), brix_vfs_require_confined(), brix_vfs_xattr_observe_mut(), brix_vfs_xattr_write_gate(), brix_vfs_ctx_t::log, name, brix_vfs_ctx_t::root_canon, and brix_vfs_ctx_t::sd.
Referenced by fattr_set(), s3_tag_store(), s3_user_meta_store(), webdav_dead_prop_set_target(), and webdav_lock_xattr_write().
brix_vfs_xattr_observe_count()
static ssize_t brix_vfs_xattr_observe_count (const brix_vfs_ctx_t * ctx, const char * path, ssize_t n, ngx_msec_t start) static
Definition at line 34 of file vfs_xattr.c.
References BRIX_METRIC_OP_XATTR, and brix_vfs_observe_ctx_op().
Referenced by brix_vfs_fgetxattr(), brix_vfs_flistxattr(), brix_vfs_getxattr(), and brix_vfs_listxattr().
brix_vfs_xattr_observe_mut()
static ngx_int_t brix_vfs_xattr_observe_mut (const brix_vfs_ctx_t * ctx, const char * path, int rc, size_t nbytes, ngx_msec_t start) static
Definition at line 155 of file vfs_xattr.c.
References BRIX_METRIC_OP_XATTR, and brix_vfs_observe_ctx_op().
Referenced by brix_vfs_removexattr(), brix_vfs_setxattr(), and brix_vfs_xattr_write_gate().
brix_vfs_xattr_write_gate()
static ngx_int_t brix_vfs_xattr_write_gate (brix_vfs_ctx_t * ctx, const char * path, const brix_sd_driver_t * drv, brix_sd_ucred_t * store, brix_sd_cred_t * cred, int * use_cred, ngx_msec_t start) static
Definition at line 174 of file vfs_xattr.c.
References BRIX_SD_CAP_XATTR_WRITE, brix_vfs_cred_gate_active(), brix_vfs_ns_cred(), and brix_vfs_xattr_observe_mut().
Referenced by brix_vfs_removexattr(), and brix_vfs_setxattr().