nginx-xrootd: src/fs/vfs/vfs_wverify.c File Reference
vfs_wverify.c File Reference
#include "vfs_internal.h"
#include "core/compat/wverify.h"
#include "core/compat/checksum_core.h"
Functions
ngx_int_t brix_vfs_wverify_check (brix_wverify_t *w, brix_vfs_file_t *rfh)
Function Documentation
brix_vfs_wverify_check()
ngx_int_t brix_vfs_wverify_check (brix_wverify_t * w, brix_vfs_file_t * rfh)
Definition at line 25 of file vfs_wverify.c.
References BRIX_CK_CRC32, brix_cksum_u32_obj(), brix_vfs_file_sd_obj(), brix_vfs_file_size(), and brix_wverify_expected().