nginx-xrootd: src/fs/vfs/vfs_stat.c File Reference
vfs_stat.c File Reference
#include "vfs_internal.h"
#include "fs/backend/cache/sd_cache.h"
#include "fs/backend/stage/sd_stage.h"
Functions
static ngx_int_t brix_vfs_stat_impl (brix_vfs_ctx_t *ctx, brix_vfs_stat_t *stat_out, int nofollow)
ngx_int_t brix_vfs_stat (brix_vfs_ctx_t *ctx, brix_vfs_stat_t *stat_out)
ngx_int_t brix_vfs_statf (brix_vfs_ctx_t *ctx, brix_vfs_stat_t *stat_out)
static brix_sd_instance_t * brix_vfs_decorator_source (const brix_sd_instance_t *inst)
ngx_int_t brix_vfs_residency (brix_vfs_ctx_t *ctx, brix_sd_residency_t *out, int *nearline_export)
ngx_int_t brix_vfs_space (brix_vfs_ctx_t *ctx, brix_sd_space_t *out)
ngx_int_t brix_vfs_probe (brix_vfs_ctx_t *ctx, int nofollow, brix_vfs_stat_t *stat_out)
Function Documentation
brix_vfs_decorator_source()
static brix_sd_instance_t * brix_vfs_decorator_source (const brix_sd_instance_t * inst) static
Definition at line 141 of file vfs_stat.c.
References brix_sd_cache_source_instance(), brix_sd_stage_source_instance(), and s.
Referenced by brix_vfs_residency(), and brix_vfs_space().
brix_vfs_probe()
ngx_int_t brix_vfs_probe (brix_vfs_ctx_t * ctx, int nofollow, brix_vfs_stat_t * stat_out)
Definition at line 225 of file vfs_stat.c.
References brix_lstat_confined_canon(), brix_sd_stat_maybe_cred(), brix_sd_ucred_wipe(), brix_vfs_cred_gate_active(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_fill_stat(), brix_vfs_ns_cred(), brix_vfs_ns_leaf(), brix_vfs_require_confined(), brix_vfs_sd_stat_fill(), brix_vfs_ctx_t::log, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::sd, and stat().
Referenced by brix_open_probe(), brix_query_xattr(), brix_statx_symlink_fallback_stat(), check_locks_descendants(), fattr_list_try_recurse(), lp_scan_staged_parts(), mpu_scan_entry(), mv_dst_slash_precheck(), mv_execute(), op_path_probe(), s3_chunk_finalize(), s3_commit_put(), s3_entry_fill_stat(), s3_handle_copy_object(), s3_handle_list_parts(), s3_handle_multipart_abort(), s3_mpu_reap_one_entry(), s3_multipart_complete_body_handler_inner(), s3_post_write_object(), s3_put_aio_done(), s3_resolve_copy_source(), s3_resolve_part_target(), s3_walk_classify(), s3put_emit_etag(), s3put_ensure_parent_dirs(), stat_symlink_follow_fallback(), webdav_check_locks_tree(), webdav_copy_probe(), webdav_lock_create_null(), webdav_lock_reap_null(), webdav_move_probe(), webdav_put_precheck(), webdav_search_entry_is_dir(), and webdav_tpc_probe().
brix_vfs_residency()
ngx_int_t brix_vfs_residency (brix_vfs_ctx_t * ctx, brix_sd_residency_t * out, int * nearline_export)
Definition at line 157 of file vfs_stat.c.
References BRIX_SD_CAP_NEARLINE, brix_sd_caps(), BRIX_SD_RES_ONLINE, brix_vfs_ctx_path(), brix_vfs_decorator_source(), brix_vfs_export_relative(), brix_vfs_require_confined(), and brix_vfs_ctx_t::sd.
Referenced by brix_open_residency_gate(), brix_statx_compute_flag(), propfind_emit_locality(), s3_get_check_residency(), s3_handle_head(), stat_residency_flags(), and tape_residency().
brix_vfs_space()
ngx_int_t brix_vfs_space (brix_vfs_ctx_t * ctx, brix_sd_space_t * out)
Definition at line 195 of file vfs_stat.c.
References brix_vfs_decorator_source(), and brix_vfs_ctx_t::sd.
brix_vfs_stat()
ngx_int_t brix_vfs_stat (brix_vfs_ctx_t * ctx, brix_vfs_stat_t * stat_out)
Definition at line 122 of file vfs_stat.c.
References brix_vfs_stat_impl().
brix_vfs_stat_impl()
static ngx_int_t brix_vfs_stat_impl (brix_vfs_ctx_t * ctx, brix_vfs_stat_t * stat_out, int nofollow) static
Definition at line 34 of file vfs_stat.c.
References brix_lstat_confined_canon(), BRIX_METRIC_OP_STAT, brix_sd_stat_maybe_cred(), brix_sd_ucred_wipe(), brix_vfs_cred_gate_active(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_fill_stat(), brix_vfs_now_ns(), brix_vfs_ns_cred(), brix_vfs_ns_leaf(), brix_vfs_observe_ctx_op(), brix_vfs_require_confined(), brix_vfs_sd_stat_fill(), brix_vfs_ctx_t::log, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::sd, and stat().
Referenced by brix_vfs_stat(), and brix_vfs_statf().
brix_vfs_statf()
ngx_int_t brix_vfs_statf (brix_vfs_ctx_t * ctx, brix_vfs_stat_t * stat_out)
Definition at line 131 of file vfs_stat.c.
References brix_vfs_stat_impl().
Referenced by stat_vfs_query().