nginx-xrootd: src/fs/vfs/vfs_backend_registry_source.c File Reference
vfs_backend_registry_source.c File Reference
#include "vfs_backend_internal.h"
#include "fs/backend/xroot/sd_xroot.h"
#include "fs/backend/http/sd_http.h"
#include "fs/backend/remote/sd_remote.h"
#include "fs/backend/rados/sd_ceph.h"
#include "fs/backend/stage/sd_stage.h"
#include "fs/backend/cache/sd_cache.h"
#include "fs/backend/frm/sd_frm.h"
#include "fs/tier/tier.h"
#include "fs/cache/origin/s3_transport.h"
#include "observability/metrics/metrics.h"
#include "observability/metrics/metrics_macros.h"
#include <string.h>
Data Structures
struct brix_vbr_source_desc_t
Typedefs
typedef brix_sd_instance_t *(* brix_vbr_source_fn) (brix_vfs_backend_entry_t *e, ngx_log_t *log)
Functions
static void brix_vfs_http_failover_note (void)
static void brix_vfs_http_health_note (const char *host, int port, int healthy)
static brix_sd_instance_t * brix_vbr_build_posix (brix_vfs_backend_entry_t *e, ngx_log_t *log)
static brix_sd_instance_t * brix_vbr_build_xroot (brix_vfs_backend_entry_t *e, ngx_log_t *log)
static brix_sd_instance_t * brix_vbr_build_tape (brix_vfs_backend_entry_t *e, ngx_log_t *log)
static brix_sd_instance_t * brix_vbr_build_http (brix_vfs_backend_entry_t *e, ngx_log_t *log)
static brix_sd_instance_t * brix_vbr_build_s3 (brix_vfs_backend_entry_t *e, ngx_log_t *log)
brix_sd_instance_t * brix_vfs_backend_build_source (brix_vfs_backend_entry_t *e, ngx_log_t *log)
Variables
static const brix_vbr_source_desc_t brix_vbr_source_table []
Typedef Documentation
brix_vbr_source_fn
typedef brix_sd_instance_t *(* brix_vbr_source_fn) (brix_vfs_backend_entry_t *e, ngx_log_t *log)
Definition at line 69 of file vfs_backend_registry_source.c.
Function Documentation
brix_vbr_build_http()
static brix_sd_instance_t * brix_vbr_build_http (brix_vfs_backend_entry_t * e, ngx_log_t * log) static
Definition at line 214 of file vfs_backend_registry_source.c.
References brix_vfs_backend_entry_t::base, brix_sd_http_ep_cfg_t::base_path, brix_sd_http_cfg_t::base_path, brix_sd_http_cfg_t::bearer_token, brix_s3_origin_curl_transport, brix_sd_http_create(), BRIX_SD_HTTP_DEFAULT_TIMEOUT_MS, brix_vfs_http_failover_note(), brix_vfs_http_health_note(), brix_sd_http_cfg_t::ca_path, brix_sd_http_cfg_t::extra, brix_sd_http_cfg_t::failover_note, brix_vfs_backend_entry_t::has_http_ranks, brix_sd_http_cfg_t::health_note, brix_sd_http_ep_cfg_t::host, brix_sd_http_cfg_t::host, brix_vfs_backend_entry_t::host, brix_vfs_backend_entry_t::http_extra, brix_vfs_backend_entry_t::http_ranks, log, brix_sd_http_cfg_t::n_extra, brix_vfs_backend_entry_t::n_http_extra, brix_vfs_backend_entry_t::origin_ca_dir, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_path, brix_vfs_backend_entry_t::origin_port, brix_vfs_backend_entry_t::origin_put_checksum, brix_vfs_backend_entry_t::origin_tls, brix_vfs_backend_entry_t::origin_token, brix_sd_http_ep_cfg_t::port, brix_sd_http_cfg_t::port, brix_vfs_backend_entry_t::port, brix_sd_http_cfg_t::put_checksum, brix_vfs_backend_entry_t::root_canon, sd_http_set_ranks(), brix_sd_http_cfg_t::timeout_ms, brix_sd_http_ep_cfg_t::tls, brix_sd_http_cfg_t::tls, brix_vfs_backend_entry_t::tls, and brix_sd_http_cfg_t::transport.
brix_vbr_build_posix()
static brix_sd_instance_t * brix_vbr_build_posix (brix_vfs_backend_entry_t * e, ngx_log_t * log) static
Definition at line 76 of file vfs_backend_registry_source.c.
References brix_sd_instance_create(), log, and brix_vfs_backend_entry_t::root_canon.
Referenced by brix_vfs_backend_build_source().
brix_vbr_build_s3()
static brix_sd_instance_t * brix_vbr_build_s3 (brix_vfs_backend_entry_t * e, ngx_log_t * log) static
Definition at line 265 of file vfs_backend_registry_source.c.
References brix_sd_remote_cfg_t::access_key, brix_s3_origin_curl_transport, BRIX_SD_HTTP_DEFAULT_TIMEOUT_MS, brix_sd_remote_create(), BRIX_SD_REMOTE_S3, brix_sd_remote_cfg_t::bucket, brix_sd_remote_cfg_t::host, log, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_path, brix_vfs_backend_entry_t::origin_port, brix_vfs_backend_entry_t::origin_put_checksum, brix_vfs_backend_entry_t::origin_s3_access_key, brix_vfs_backend_entry_t::origin_s3_region, brix_vfs_backend_entry_t::origin_s3_secret_key, brix_vfs_backend_entry_t::origin_tls, brix_sd_remote_cfg_t::port, brix_sd_remote_cfg_t::put_checksum, brix_sd_remote_cfg_t::region, brix_vfs_backend_entry_t::root_canon, brix_sd_remote_cfg_t::scheme, brix_sd_remote_cfg_t::secret_key, brix_sd_remote_cfg_t::timeout_ms, brix_sd_remote_cfg_t::tls, and brix_sd_remote_cfg_t::transport.
brix_vbr_build_tape()
static brix_sd_instance_t * brix_vbr_build_tape (brix_vfs_backend_entry_t * e, ngx_log_t * log) static
Definition at line 190 of file vfs_backend_registry_source.c.
References brix_sd_frm_create(), log, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_path, and brix_vfs_backend_entry_t::root_canon.
brix_vbr_build_xroot()
static brix_sd_instance_t * brix_vbr_build_xroot (brix_vfs_backend_entry_t * e, ngx_log_t * log) static
Definition at line 94 of file vfs_backend_registry_source.c.
References brix_sd_xroot_create_origin(), brix_sd_xroot_origin_cfg_t::host, log, brix_vfs_backend_entry_t::origin_ca_dir, brix_vfs_backend_entry_t::origin_family, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_port, brix_vfs_backend_entry_t::origin_sss_keytab, brix_vfs_backend_entry_t::origin_tls, brix_vfs_backend_entry_t::origin_token, brix_vfs_backend_entry_t::origin_x509_key, brix_vfs_backend_entry_t::origin_x509_proxy, and brix_vfs_backend_entry_t::root_canon.
brix_vfs_backend_build_source()
brix_sd_instance_t * brix_vfs_backend_build_source (brix_vfs_backend_entry_t * e, ngx_log_t * log)
Definition at line 368 of file vfs_backend_registry_source.c.
References brix_vfs_backend_entry_t::backend, brix_vbr_build_posix(), brix_vbr_source_table, brix_vbr_source_desc_t::build, log, and brix_vbr_source_desc_t::name.
Referenced by brix_vfs_backend_entry_build().
brix_vfs_http_failover_note()
static void brix_vfs_http_failover_note (void) static
Definition at line 27 of file vfs_backend_registry_source.c.
References BRIX_CVMFS_METRIC_INC.
Referenced by brix_vbr_build_http().
brix_vfs_http_health_note()
static void brix_vfs_http_health_note (const char * host, int port, int healthy) static
Definition at line 36 of file vfs_backend_registry_source.c.
References host, and port.
Referenced by brix_vbr_build_http().
Variable Documentation
brix_vbr_source_table
const brix_vbr_source_desc_t brix_vbr_source_table[] static
Initial value:
= {
    { "xroot",    brix_vbr_build_xroot },
    { "tape",     brix_vbr_build_tape },
    { "http",     brix_vbr_build_http },
    { "s3",       brix_vbr_build_s3 },
}
Definition at line 349 of file vfs_backend_registry_source.c.
Referenced by brix_vfs_backend_build_source().