nginx-xrootd: client/lib/fs/vfs_posix.c File Reference
vfs_posix.c File Reference
#include "vfs.h"
#include "core/aio/uring.h"
#include "brix.h"
#include "fs/backend/sd.h"
#include "fs/core/vfs_core.h"
#include <errno.h>
#include <fcntl.h>
#include <stdatomic.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
struct vfs_posix_file
Functions
static char * make_posix_temp_path (const char *dst)
static int posix_ring_select (int fd, int mode, brix_disk_ring **ring, brix_status *st)
static ssize_t posix_pread (brix_vfs_file *f, int64_t off, void *buf, size_t n, brix_status *st)
static int posix_pwrite (brix_vfs_file *f, int64_t off, const void *buf, size_t n, brix_status *st)
static int posix_fstat (brix_vfs_file *f, brix_vfs_stat *out, brix_status *st)
static int posix_truncate (brix_vfs_file *f, int64_t size, brix_status *st)
static int posix_sync (brix_vfs_file *f, brix_status *st)
static int posix_commit (brix_vfs_file *f, brix_status *st)
static void posix_abort (brix_vfs_file *f)
static void posix_close (brix_vfs_file *f)
static int posix_be_open (const brix_vfs_backend *be, const char *path, int flags, const brix_vfs_open_opts *opts, brix_vfs_file **out, brix_status *st)
static int posix_be_stat (const brix_vfs_backend *be, const char *path, brix_vfs_stat *out, brix_status *st)
const brix_vfs_backend * brix_vfs_posix_backend (void)
Variables
static const brix_vfs_ops s_posix_ops
static const brix_vfs_backend s_posix_backend
Function Documentation
brix_vfs_posix_backend()
const brix_vfs_backend * brix_vfs_posix_backend (void)
Definition at line 557 of file vfs_posix.c.
References s_posix_backend.
Referenced by vfs_init_backends().
make_posix_temp_path()
static char * make_posix_temp_path (const char * dst) static
Definition at line 77 of file vfs_posix.c.
References s.
Referenced by posix_be_open().
posix_abort()
static void posix_abort (brix_vfs_file * f) static
Definition at line 346 of file vfs_posix.c.
References vfs_posix_file::tmp_path.
posix_be_open()
static int posix_be_open (const brix_vfs_backend * be, const char * path, int flags, const brix_vfs_open_opts * opts, brix_vfs_file ** out, brix_status * st) static
Definition at line 403 of file vfs_posix.c.
References access(), vfs_posix_file::base, BRIX_SD_O_CREATE, BRIX_SD_O_EXCL, BRIX_SD_O_NOFOLLOW, BRIX_SD_O_READ, BRIX_SD_O_TRUNC, BRIX_SD_O_WRITE, brix_sd_posix_open_unconfined(), brix_status_set(), brix_vfs_file::caps, close(), vfs_posix_file::fd, vfs_posix_file::final_path, brix_vfs_open_opts::io_uring, make_posix_temp_path(), brix_vfs_file::ops, posix_ring_select(), vfs_posix_file::ring, s_posix_ops, vfs_posix_file::tmp_path, XRDC_EIO, XRDC_EUSAGE, XRDC_IO_URING_AUTO, XRDC_VFS_CAP_ATOMIC_TEMP, XRDC_VFS_CAP_FADVISE, XRDC_VFS_CAP_RANDOM_WRITE, XRDC_VFS_CAP_TRUNCATE, XRDC_VFS_FORCE, and XRDC_VFS_WRITE.
posix_be_stat()
static int posix_be_stat (const brix_vfs_backend * be, const char * path, brix_vfs_stat * out, brix_status * st) static
Definition at line 510 of file vfs_posix.c.
References brix_status_set(), brix_vfs_stat::exists, brix_vfs_stat::is_dir, brix_vfs_stat::mtime, brix_vfs_stat::size, stat(), and XRDC_EIO.
posix_close()
static void posix_close (brix_vfs_file * f) static
Definition at line 364 of file vfs_posix.c.
References brix_disk_ring_destroy(), close(), vfs_posix_file::fd, vfs_posix_file::final_path, vfs_posix_file::ring, and vfs_posix_file::tmp_path.
posix_commit()
static int posix_commit (brix_vfs_file * f, brix_status * st) static
Definition at line 308 of file vfs_posix.c.
References brix_disk_ring_flush(), brix_status_set(), vfs_posix_file::fd, vfs_posix_file::final_path, vfs_posix_file::ring, vfs_posix_file::tmp_path, and XRDC_EIO.
posix_fstat()
static int posix_fstat (brix_vfs_file * f, brix_vfs_stat * out, brix_status * st) static
Definition at line 227 of file vfs_posix.c.
References brix_sd_posix_wrap(), brix_status_set(), brix_vfs_stat::exists, vfs_posix_file::fd, brix_vfs_stat::is_dir, brix_sd_stat_t::is_dir, brix_vfs_stat::mtime, brix_sd_stat_t::mtime, brix_vfs_stat::size, brix_sd_stat_t::size, XRDC_EIO, and xvfs_fstat().
posix_pread()
static ssize_t posix_pread (brix_vfs_file * f, int64_t off, void * buf, size_t n, brix_status * st) static
Definition at line 150 of file vfs_posix.c.
References brix_disk_ring_pread(), brix_sd_posix_wrap(), brix_status_set(), vfs_posix_file::fd, vfs_posix_file::ring, XRDC_EIO, and xvfs_pread_once().
posix_pwrite()
static int posix_pwrite (brix_vfs_file * f, int64_t off, const void * buf, size_t n, brix_status * st) static
Definition at line 184 of file vfs_posix.c.
References brix_disk_ring_bufsz(), brix_disk_ring_pwrite(), brix_sd_posix_wrap(), brix_status_set(), vfs_posix_file::fd, vfs_posix_file::ring, XRDC_EIO, and xvfs_pwrite_full().
posix_ring_select()
static int posix_ring_select (int fd, int mode, brix_disk_ring ** ring, brix_status * st) static
Definition at line 107 of file vfs_posix.c.
References brix_disk_ring_create(), brix_status_clear(), brix_status_set(), brix_uring_available(), mode, XRDC_EUNSUPPORTED, XRDC_IO_URING_OFF, and XRDC_IO_URING_ON.
Referenced by posix_be_open().
posix_sync()
static int posix_sync (brix_vfs_file * f, brix_status * st) static
Definition at line 277 of file vfs_posix.c.
References brix_disk_ring_flush(), brix_sd_posix_wrap(), brix_status_set(), vfs_posix_file::fd, vfs_posix_file::ring, XRDC_EIO, and xvfs_fsync().
posix_truncate()
static int posix_truncate (brix_vfs_file * f, int64_t size, brix_status * st) static
Definition at line 255 of file vfs_posix.c.
References brix_sd_posix_wrap(), brix_status_set(), vfs_posix_file::fd, XRDC_EIO, and xvfs_ftruncate().
Variable Documentation
s_posix_backend
const brix_vfs_backend s_posix_backend static
Initial value:
= {
    .scheme = "file",
    .caps   = (XRDC_VFS_CAP_RANDOM_WRITE | XRDC_VFS_CAP_TRUNCATE |
               XRDC_VFS_CAP_ATOMIC_TEMP   | XRDC_VFS_CAP_FADVISE),
    .open   = posix_be_open,
    .stat   = posix_be_stat,
}
Definition at line 538 of file vfs_posix.c.
Referenced by brix_vfs_posix_backend().
s_posix_ops
const brix_vfs_ops s_posix_ops static
Initial value:
= {
    .pread    = posix_pread,
    .pwrite   = posix_pwrite,
    .fstat    = posix_fstat,
    .truncate = posix_truncate,
    .sync     = posix_sync,
    .commit   = posix_commit,
    .abort    = posix_abort,
    .close    = posix_close,
}
Definition at line 380 of file vfs_posix.c.
Referenced by posix_be_open().