nginx-xrootd: src/fs/core/vfs_core.c File Reference
vfs_core.c File Reference
#include "vfs_core.h"
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
Functions
int xvfs_pread_full (brix_sd_obj_t *obj, void *buf, size_t len, off_t off, size_t *nread)
ssize_t xvfs_pread_once (brix_sd_obj_t *obj, void *buf, size_t len, off_t off)
int xvfs_pwrite_full (brix_sd_obj_t *obj, const void *buf, size_t len, off_t off, size_t *written, int *short_io)
int xvfs_fsync (brix_sd_obj_t *obj)
int xvfs_ftruncate (brix_sd_obj_t *obj, off_t len)
int xvfs_fstat (brix_sd_obj_t *obj, brix_sd_stat_t *out)
int xvfs_drain (brix_sd_obj_t *src, brix_sd_obj_t *dst, void *buf, size_t bufsz, off_t *total)
int xvfs_stage_fd (int src_fd, const char *stage_dir)
Function Documentation
xvfs_drain()
int xvfs_drain (brix_sd_obj_t * src, brix_sd_obj_t * dst, void * buf, size_t bufsz, off_t * total)
Definition at line 126 of file vfs_core.c.
References xvfs_pread_once(), and xvfs_pwrite_full().
Referenced by main(), and xvfs_stage_fd().
xvfs_fstat()
int xvfs_fstat (brix_sd_obj_t * obj, brix_sd_stat_t * out)
Definition at line 120 of file vfs_core.c.
Referenced by main(), and posix_fstat().
xvfs_fsync()
int xvfs_fsync (brix_sd_obj_t * obj)
Definition at line 107 of file vfs_core.c.
Referenced by block_commit(), block_sync(), brix_vfs_io_execute_sync(), main(), and posix_sync().
xvfs_ftruncate()
int xvfs_ftruncate (brix_sd_obj_t * obj, off_t len)
Definition at line 114 of file vfs_core.c.
Referenced by brix_vfs_io_execute_truncate(), main(), and posix_truncate().
xvfs_pread_full()
int xvfs_pread_full (brix_sd_obj_t * obj, void * buf, size_t len, off_t off, size_t * nread)
Definition at line 19 of file vfs_core.c.
Referenced by brix_vfs_io_execute_read(), brix_vfs_pread_full(), and main().
xvfs_pread_once()
ssize_t xvfs_pread_once (brix_sd_obj_t * obj, void * buf, size_t len, off_t off)
Definition at line 50 of file vfs_core.c.
Referenced by block_pread(), main(), posix_pread(), and xvfs_drain().
xvfs_pwrite_full()
int xvfs_pwrite_full (brix_sd_obj_t * obj, const void * buf, size_t len, off_t off, size_t * written, int * short_io)
Definition at line 62 of file vfs_core.c.
Referenced by block_pwrite(), brix_vfs_io_write_counted(), main(), posix_pwrite(), and xvfs_drain().
xvfs_stage_fd()
int xvfs_stage_fd (int src_fd, const char * stage_dir)
Definition at line 158 of file vfs_core.c.
References brix_sd_posix_wrap(), close(), open(), PATH_MAX, s, and xvfs_drain().
Referenced by zip_stage_archive_maybe().