nginx-xrootd: src/fs/vfs/vfs_backend_registry.c File Reference
vfs_backend_registry.c File Reference
#include "vfs_backend_internal.h"
#include "fs/backend/xroot/sd_xroot.h"
#include "fs/backend/http/sd_http.h"
#include "fs/backend/remote/sd_remote.h"
#include "fs/backend/rados/sd_ceph.h"
#include "fs/backend/stage/sd_stage.h"
#include "fs/backend/cache/sd_cache.h"
#include "fs/backend/frm/sd_frm.h"
#include "fs/tier/tier.h"
#include "fs/cache/origin/s3_transport.h"
#include "observability/metrics/metrics.h"
#include "observability/metrics/metrics_macros.h"
#include <string.h>
Functions
static void brix_vfs_http_failover_note (void)
static void brix_vfs_http_health_note (const char *host, int port, int healthy)
brix_vfs_backend_entry_t * brix_vfs_backend_entry_find (const char *root_canon)
int brix_vfs_backend_http_endpoint (const char *root_canon, const char **host, int *port, int *tls, const char **base)
brix_vfs_backend_entry_t * brix_vfs_backend_entry_get_or_create (const char *root_canon)
static brix_sd_instance_t * brix_vfs_backend_build_source (brix_vfs_backend_entry_t *e, ngx_log_t *log)
static brix_sd_instance_t * brix_vfs_backend_entry_build (brix_vfs_backend_entry_t *e, ngx_log_t *log)
ngx_uint_t brix_vfs_backend_export_count (void)
ngx_int_t brix_vfs_backend_export_info (ngx_uint_t i, brix_vfs_backend_info_t *out)
brix_sd_instance_t * brix_vfs_backend_resolve (const char *root_canon, ngx_log_t *log)
brix_sd_instance_t * brix_vfs_backend_resolve_for_path (const char *abs_path, const char **root_out, ngx_log_t *log)
Variables
static brix_vfs_backend_entry_t brix_vfs_backends [64]
static ngx_uint_t brix_vfs_backend_count
Function Documentation
brix_vfs_backend_build_source()
static brix_sd_instance_t * brix_vfs_backend_build_source (brix_vfs_backend_entry_t * e, ngx_log_t * log) static
Definition at line 114 of file vfs_backend_registry.c.
References brix_sd_remote_cfg_t::access_key, brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_t::base, brix_sd_http_ep_cfg_t::base_path, brix_sd_http_cfg_t::base_path, brix_sd_http_cfg_t::bearer_token, brix_vfs_backend_entry_t::block_size, brix_s3_origin_curl_transport, brix_sd_frm_create(), brix_sd_http_create(), brix_sd_instance_create(), brix_sd_remote_create(), BRIX_SD_REMOTE_S3, brix_sd_xroot_create_origin(), brix_vfs_http_failover_note(), brix_vfs_http_health_note(), brix_sd_remote_cfg_t::bucket, brix_vfs_backend_entry_t::ceph_conf, brix_vfs_backend_entry_t::ceph_data_pool, brix_vfs_backend_entry_t::ceph_key_prefix, brix_vfs_backend_entry_t::ceph_pool, brix_vfs_backend_entry_t::cephfs_live, brix_vfs_backend_entry_t::cephfs_quiesced, brix_sd_http_cfg_t::extra, brix_sd_http_cfg_t::failover_note, brix_vfs_backend_entry_t::has_http_ranks, brix_sd_http_cfg_t::health_note, brix_sd_http_ep_cfg_t::host, brix_sd_http_cfg_t::host, brix_vfs_backend_entry_t::host, brix_sd_remote_cfg_t::host, brix_vfs_backend_entry_t::http_extra, brix_vfs_backend_entry_t::http_ranks, log, brix_sd_http_cfg_t::n_extra, brix_vfs_backend_entry_t::n_http_extra, brix_vfs_backend_entry_t::origin_ca_dir, brix_vfs_backend_entry_t::origin_family, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_path, brix_vfs_backend_entry_t::origin_port, brix_vfs_backend_entry_t::origin_s3_access_key, brix_vfs_backend_entry_t::origin_s3_region, brix_vfs_backend_entry_t::origin_s3_secret_key, brix_vfs_backend_entry_t::origin_sss_keytab, brix_vfs_backend_entry_t::origin_tls, brix_vfs_backend_entry_t::origin_token, brix_vfs_backend_entry_t::origin_x509_proxy, brix_sd_http_ep_cfg_t::port, brix_sd_http_cfg_t::port, brix_sd_remote_cfg_t::port, brix_vfs_backend_entry_t::port, brix_sd_remote_cfg_t::region, brix_vfs_backend_entry_t::root_canon, brix_sd_remote_cfg_t::scheme, sd_http_set_ranks(), brix_sd_remote_cfg_t::secret_key, brix_sd_http_cfg_t::timeout_ms, brix_sd_remote_cfg_t::timeout_ms, brix_sd_http_ep_cfg_t::tls, brix_sd_http_cfg_t::tls, brix_sd_remote_cfg_t::tls, brix_vfs_backend_entry_t::tls, brix_sd_http_cfg_t::transport, and brix_sd_remote_cfg_t::transport.
Referenced by brix_vfs_backend_entry_build().
brix_vfs_backend_entry_build()
static brix_sd_instance_t * brix_vfs_backend_entry_build (brix_vfs_backend_entry_t * e, ngx_log_t * log) static
Definition at line 349 of file vfs_backend_registry.c.
References brix_sd_cache_create(), brix_sd_instance_create(), brix_sd_stage_create(), brix_tier_build(), brix_vfs_backend_build_source(), brix_vfs_backend_entry_t::cache_policy, brix_vfs_backend_entry_t::cache_tier, brix_tier_cfg_t::configured, brix_tier_cfg_t::driver, brix_vfs_backend_entry_t::inst, log, brix_tier_cfg_t::path, brix_vfs_backend_entry_t::root_canon, brix_vfs_backend_entry_t::stage_policy, brix_vfs_backend_entry_t::stage_tier, and brix_vfs_backend_entry_t::staging.
Referenced by brix_vfs_backend_resolve(), and brix_vfs_backend_resolve_for_path().
brix_vfs_backend_entry_find()
brix_vfs_backend_entry_t * brix_vfs_backend_entry_find (const char * root_canon)
Definition at line 54 of file vfs_backend_registry.c.
References brix_vfs_backend_count, and brix_vfs_backends.
Referenced by brix_vfs_backend_config(), brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_http_endpoint(), brix_vfs_backend_http_endpoint_at(), brix_vfs_backend_register_http_upstream(), brix_vfs_backend_set_credential(), brix_vfs_backend_set_http_ranks(), brix_vfs_backend_set_staging(), and vfs_backend_add_http_endpoint().
brix_vfs_backend_entry_get_or_create()
brix_vfs_backend_entry_t * brix_vfs_backend_entry_get_or_create (const char * root_canon)
Definition at line 91 of file vfs_backend_registry.c.
References brix_vfs_backend_count, brix_vfs_backend_entry_find(), BRIX_VFS_BACKEND_MAX, brix_vfs_backends, and brix_vfs_backend_entry_t::root_canon.
Referenced by brix_vfs_backend_config(), brix_vfs_backend_config_cache_store(), brix_vfs_backend_config_ceph(), brix_vfs_backend_config_cephfs_ro(), brix_vfs_backend_config_http(), brix_vfs_backend_config_s3(), brix_vfs_backend_config_stage_store(), brix_vfs_backend_config_tape(), brix_vfs_backend_config_xroot(), and brix_vfs_backend_register_http_upstream().
brix_vfs_backend_export_count()
ngx_uint_t brix_vfs_backend_export_count (void)
Definition at line 432 of file vfs_backend_registry.c.
References brix_vfs_backend_count.
Referenced by brix_storage_backend_metrics_emit(), dashboard_fill_storage(), health_build_json(), ngx_http_brix_dashboard_vfs_exports_handler(), and vfs_browse_get_export().
brix_vfs_backend_export_info()
ngx_int_t brix_vfs_backend_export_info (ngx_uint_t i, brix_vfs_backend_info_t * out)
Definition at line 438 of file vfs_backend_registry.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_info_t::backend, brix_vfs_backend_count, brix_vfs_backends, brix_vfs_backend_info_t::has_proxy, brix_vfs_backend_info_t::has_token, brix_vfs_backend_info_t::host, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_port, brix_vfs_backend_entry_t::origin_tls, brix_vfs_backend_entry_t::origin_token, brix_vfs_backend_entry_t::origin_x509_proxy, brix_vfs_backend_info_t::port, brix_vfs_backend_entry_t::root_canon, brix_vfs_backend_info_t::root_canon, brix_vfs_backend_entry_t::staging, brix_vfs_backend_info_t::staging, and brix_vfs_backend_info_t::tls.
Referenced by brix_storage_backend_info_emit(), brix_storage_capacity_emit(), dashboard_fill_storage(), health_build_json(), ngx_http_brix_dashboard_vfs_download_handler(), ngx_http_brix_dashboard_vfs_exports_handler(), and ngx_http_brix_dashboard_vfs_files_handler().
brix_vfs_backend_http_endpoint()
int brix_vfs_backend_http_endpoint (const char * root_canon, const char ** host, int * port, int * tls, const char ** base)
Definition at line 72 of file vfs_backend_registry.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_find(), brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_path, brix_vfs_backend_entry_t::origin_port, brix_vfs_backend_entry_t::origin_tls, and tls.
Referenced by brix_cvmfs_geo_passthrough().
brix_vfs_backend_resolve()
brix_sd_instance_t * brix_vfs_backend_resolve (const char * root_canon, ngx_log_t * log)
Definition at line 458 of file vfs_backend_registry.c.
References brix_vfs_backend_count, brix_vfs_backend_entry_build(), brix_vfs_backends, log, and brix_vfs_backend_entry_t::root_canon.
Referenced by brix_cache_open_or_fill(), brix_cache_storage(), brix_cache_storage_cstore(), brix_cvmfs_upstream_get(), brix_handle_mkdir(), brix_handle_mv(), brix_handle_open(), brix_open_read_probe(), brix_open_resolved_file(), brix_vfs_backend_mkpath(), brix_vfs_ctx_init(), brix_webdav_backend_instance(), cache_build_instance(), cache_build_wt_stage(), cms_node_exec_forward(), cvmfs_probe_done(), cvmfs_resolve_sd(), cvmfs_var_origin(), health_build_json(), ngx_http_brix_dashboard_scan_handler(), op_path_existence_gate(), stage_reconcile_one(), and webdav_resolve_stat().
brix_vfs_backend_resolve_for_path()
brix_sd_instance_t * brix_vfs_backend_resolve_for_path (const char * abs_path, const char ** root_out, ngx_log_t * log)
Definition at line 480 of file vfs_backend_registry.c.
References brix_vfs_backend_count, brix_vfs_backend_entry_build(), brix_vfs_backends, log, and brix_vfs_backend_entry_t::root_canon.
Referenced by brix_commit_staged().
brix_vfs_http_failover_note()
static void brix_vfs_http_failover_note (void) static
Definition at line 25 of file vfs_backend_registry.c.
References BRIX_CVMFS_METRIC_INC.
Referenced by brix_vfs_backend_build_source().
brix_vfs_http_health_note()
static void brix_vfs_http_health_note (const char * host, int port, int healthy) static
Definition at line 34 of file vfs_backend_registry.c.
Referenced by brix_vfs_backend_build_source().
Variable Documentation
brix_vfs_backend_count
ngx_uint_t brix_vfs_backend_count static
Definition at line 50 of file vfs_backend_registry.c.
Referenced by brix_vfs_backend_entry_find(), brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_export_count(), brix_vfs_backend_export_info(), brix_vfs_backend_resolve(), and brix_vfs_backend_resolve_for_path().
brix_vfs_backends
brix_vfs_backend_entry_t brix_vfs_backends[64] static
Definition at line 49 of file vfs_backend_registry.c.
Referenced by brix_vfs_backend_entry_find(), brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_export_info(), brix_vfs_backend_resolve(), and brix_vfs_backend_resolve_for_path().