nginx-xrootd: src/fs/vfs/vfs_io_core_internal.h File Reference
vfs_io_core_internal.h File Reference
#include "vfs_io_core.h"
Macros
#define BRIX_VFS_DIRLIST_CHUNK_CAP 65536UL
Functions
void brix_vfs_io_set_error_message (brix_vfs_job_t *job, const char *message)
void brix_vfs_io_execute_opendir (brix_vfs_job_t *job)
Macro Definition Documentation
BRIX_VFS_DIRLIST_CHUNK_CAP
#define BRIX_VFS_DIRLIST_CHUNK_CAP 65536UL
Definition at line 26 of file vfs_io_core_internal.h.
Function Documentation
brix_vfs_io_execute_opendir()
void brix_vfs_io_execute_opendir (brix_vfs_job_t * job)
Definition at line 217 of file vfs_io_core_dirlist.c.
References brix_build_resp_hdr(), BRIX_DSTAT_LEADIN, BRIX_DSTAT_LEADIN_LEN, BRIX_VFS_DIRLIST_CHUNK_CAP, brix_vfs_io_dirlist_emit_entry(), brix_vfs_io_dirlist_fail(), brix_vfs_io_dirlist_name_unsafe(), brix_vfs_io_dirlist_need_new_chunk(), brix_vfs_io_dirlist_stat_entry(), brix_vfs_job_t::buf, brix_vfs_job_t::buf_cap, close(), kXR_ok, name, ngx_memcpy, brix_vfs_job_t::nio, brix_vfs_job_t::out_size, brix_vfs_job_t::rootfd, brix_vfs_job_t::streamid, brix_vfs_job_t::want_stat, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_vfs_io_execute().
brix_vfs_io_set_error_message()
void brix_vfs_io_set_error_message (brix_vfs_job_t * job, const char * message)
Definition at line 52 of file vfs_io_core.c.
References brix_vfs_job_t::err_msg, and brix_vfs_job_t::err_msg_cap.
Referenced by brix_vfs_io_dirlist_fail(), brix_vfs_io_execute_readv(), and brix_vfs_io_execute_writev().