nginx-xrootd: src/fs/vfs/vfs_backend_config.c File Reference
vfs_backend_config.c File Reference
#include "vfs_backend_internal.h"
#include <string.h>
Functions
void brix_vfs_backend_config (const char *root_canon, const ngx_str_t *name, size_t block_size)
static void brix_vfs_backend_set_xroot (brix_vfs_backend_entry_t *e, const char *host, int port, int tls, int family)
void brix_vfs_backend_config_xroot (const char *root_canon, const char *host, int port, int tls, int family)
void brix_vfs_backend_config_http (const char *root_canon, const char *host, int port, int tls, const char *base_path)
void brix_vfs_backend_config_s3 (const char *root_canon, const char *host, int port, int tls, const char *bucket)
static void brix_vfs_backend_config_ceph (const char *root_canon, const char *backend, const char *pool, const char *conf, const char *key_prefix)
static void brix_vfs_backend_config_cephfs_ro (const char *root_canon, const char *meta_pool, const char *data_pool, const char *conf, int quiesced, int live)
static void brix_vfs_backend_config_tape (const char *root_canon, const char *adapter, const char *base)
void brix_vfs_backend_set_credential (const char *root_canon, const brix_vfs_backend_cred_t *cred)
static int vfs_backend_is_http_url (const u_char *data, size_t len)
static ngx_int_t vfs_parse_http_origin (ngx_conf_t *cf, u_char *seg, size_t segn, char *host, size_t host_cap, int *port_out, int *tls_out, char *base, size_t base_cap)
static ngx_int_t vfs_backend_add_http_endpoint (ngx_conf_t *cf, const char *root_canon, const char *host, int port, int tls, const char *base)
ngx_int_t brix_vfs_backend_config_str (ngx_conf_t *cf, const char *root_canon, const ngx_str_t *sb, size_t block_size, int family)
void brix_vfs_backend_set_staging (const char *root_canon, int on)
void brix_vfs_backend_config_cache_store (const char *root_canon, const brix_tier_cfg_t *cfg, const brix_cache_policy_t *policy)
int brix_vfs_backend_http_endpoint_at (const char *root_canon, int idx, const char **host, int *port)
void brix_vfs_backend_set_http_ranks (const char *root_canon, const int *ranks, int n)
ngx_int_t brix_vfs_backend_register_http_upstream (const char *up_root, const char *template_root, const char *host, int port, int tls, const char *store_suffix)
void brix_vfs_backend_config_stage_store (const char *root_canon, const brix_tier_cfg_t *cfg, const brix_stage_policy_t *policy)
Function Documentation
brix_vfs_backend_config()
void brix_vfs_backend_config (const char * root_canon, const ngx_str_t * name, size_t block_size)
Definition at line 14 of file vfs_backend_config.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_t::block_size, brix_vfs_backend_entry_find(), brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_entry_t::inst, name, and ngx_memcpy.
Referenced by brix_config_prepare_server(), and brix_vfs_backend_config_str().
brix_vfs_backend_config_cache_store()
void brix_vfs_backend_config_cache_store (const char * root_canon, const brix_tier_cfg_t * cfg, const brix_cache_policy_t * policy)
Definition at line 751 of file vfs_backend_config.c.
References brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_entry_t::cache_policy, brix_vfs_backend_entry_t::cache_tier, brix_tier_cfg_t::configured, and brix_vfs_backend_entry_t::inst.
Referenced by brix_tier_register_stores().
brix_vfs_backend_config_ceph()
static void brix_vfs_backend_config_ceph (const char * root_canon, const char * backend, const char * pool, const char * conf, const char * key_prefix) static
Definition at line 149 of file vfs_backend_config.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_entry_t::ceph_conf, brix_vfs_backend_entry_t::ceph_key_prefix, brix_vfs_backend_entry_t::ceph_pool, and brix_vfs_backend_entry_t::inst.
Referenced by brix_vfs_backend_config_str().
brix_vfs_backend_config_cephfs_ro()
static void brix_vfs_backend_config_cephfs_ro (const char * root_canon, const char * meta_pool, const char * data_pool, const char * conf, int quiesced, int live) static
Definition at line 178 of file vfs_backend_config.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_entry_t::ceph_conf, brix_vfs_backend_entry_t::ceph_data_pool, brix_vfs_backend_entry_t::ceph_pool, brix_vfs_backend_entry_t::cephfs_live, brix_vfs_backend_entry_t::cephfs_quiesced, brix_vfs_backend_entry_t::inst, and ngx_memcpy.
Referenced by brix_vfs_backend_config_str().
brix_vfs_backend_config_http()
void brix_vfs_backend_config_http (const char * root_canon, const char * host, int port, int tls, const char * base_path)
Definition at line 90 of file vfs_backend_config.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_entry_t::inst, brix_vfs_backend_entry_t::n_http_extra, ngx_memcpy, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_path, brix_vfs_backend_entry_t::origin_port, brix_vfs_backend_entry_t::origin_tls, and tls.
Referenced by brix_vfs_backend_config_str().
brix_vfs_backend_config_s3()
void brix_vfs_backend_config_s3 (const char * root_canon, const char * host, int port, int tls, const char * bucket)
Definition at line 121 of file vfs_backend_config.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_entry_t::inst, ngx_memcpy, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_path, brix_vfs_backend_entry_t::origin_port, brix_vfs_backend_entry_t::origin_tls, and tls.
Referenced by brix_vfs_backend_config_str().
brix_vfs_backend_config_stage_store()
void brix_vfs_backend_config_stage_store (const char * root_canon, const brix_tier_cfg_t * cfg, const brix_stage_policy_t * policy)
Definition at line 870 of file vfs_backend_config.c.
References brix_vfs_backend_entry_get_or_create(), brix_tier_cfg_t::configured, brix_vfs_backend_entry_t::inst, brix_vfs_backend_entry_t::stage_policy, and brix_vfs_backend_entry_t::stage_tier.
Referenced by brix_tier_register_stores().
brix_vfs_backend_config_str()
ngx_int_t brix_vfs_backend_config_str (ngx_conf_t * cf, const char * root_canon, const ngx_str_t * sb, size_t block_size, int family)
Definition at line 401 of file vfs_backend_config.c.
References brix_vfs_backend_config(), brix_vfs_backend_config_ceph(), brix_vfs_backend_config_cephfs_ro(), brix_vfs_backend_config_http(), brix_vfs_backend_config_s3(), brix_vfs_backend_config_tape(), brix_vfs_backend_config_xroot(), c, ngx_memcpy, vfs_backend_add_http_endpoint(), vfs_backend_is_http_url(), and vfs_parse_http_origin().
Referenced by brix_config_prepare_server(), ngx_http_brix_cvmfs_merge_loc_conf(), ngx_http_brix_webdav_merge_loc_conf(), and ngx_http_s3_merge_loc_conf().
brix_vfs_backend_config_tape()
static void brix_vfs_backend_config_tape (const char * root_canon, const char * adapter, const char * base) static
Definition at line 209 of file vfs_backend_config.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_entry_t::inst, ngx_memcpy, brix_vfs_backend_entry_t::origin_host, and brix_vfs_backend_entry_t::origin_path.
Referenced by brix_vfs_backend_config_str().
brix_vfs_backend_config_xroot()
void brix_vfs_backend_config_xroot (const char * root_canon, const char * host, int port, int tls, int family)
Definition at line 71 of file vfs_backend_config.c.
References brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_set_xroot(), and tls.
Referenced by brix_vfs_backend_config_str().
brix_vfs_backend_http_endpoint_at()
int brix_vfs_backend_http_endpoint_at (const char * root_canon, int idx, const char ** host, int * port)
Definition at line 775 of file vfs_backend_config.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_find(), brix_vfs_backend_entry_t::host, brix_vfs_backend_entry_t::http_extra, brix_vfs_backend_entry_t::n_http_extra, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_port, and brix_vfs_backend_entry_t::port.
Referenced by brix_cvmfs_rtt_init_worker(), and cvmfs_geo_rank_config().
brix_vfs_backend_register_http_upstream()
ngx_int_t brix_vfs_backend_register_http_upstream (const char * up_root, const char * template_root, const char * host, int port, int tls, const char * store_suffix)
Definition at line 823 of file vfs_backend_config.c.
References brix_vfs_backend_entry_t::backend, brix_mkdir_recursive(), brix_vfs_backend_entry_find(), brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_entry_t::cache_policy, brix_vfs_backend_entry_t::cache_tier, brix_tier_cfg_t::configured, brix_tier_cfg_t::driver, brix_vfs_backend_entry_t::inst, ngx_memcpy, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_path, brix_vfs_backend_entry_t::origin_port, brix_vfs_backend_entry_t::origin_tls, brix_tier_cfg_t::path, and tls.
Referenced by brix_cvmfs_upstream_get().
brix_vfs_backend_set_credential()
void brix_vfs_backend_set_credential (const char * root_canon, const brix_vfs_backend_cred_t * cred)
Definition at line 232 of file vfs_backend_config.c.
References brix_vfs_backend_cred_t::bearer, brix_vfs_backend_entry_find(), brix_vfs_backend_cred_t::ca_dir, brix_vfs_backend_entry_t::inst, brix_vfs_backend_entry_t::origin_ca_dir, brix_vfs_backend_entry_t::origin_s3_access_key, brix_vfs_backend_entry_t::origin_s3_region, brix_vfs_backend_entry_t::origin_s3_secret_key, brix_vfs_backend_entry_t::origin_sss_keytab, brix_vfs_backend_entry_t::origin_token, brix_vfs_backend_entry_t::origin_x509_proxy, brix_vfs_backend_cred_t::s3_access_key, brix_vfs_backend_cred_t::s3_region, brix_vfs_backend_cred_t::s3_secret_key, brix_vfs_backend_cred_t::sss_keytab, and brix_vfs_backend_cred_t::x509_proxy.
Referenced by brix_config_prepare_server(), ngx_http_brix_webdav_merge_loc_conf(), and ngx_http_s3_merge_loc_conf().
brix_vfs_backend_set_http_ranks()
void brix_vfs_backend_set_http_ranks (const char * root_canon, const int * ranks, int n)
Definition at line 798 of file vfs_backend_config.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_find(), brix_vfs_backend_entry_t::has_http_ranks, brix_vfs_backend_entry_t::http_ranks, and brix_vfs_backend_entry_t::inst.
Referenced by cvmfs_geo_rank_config().
brix_vfs_backend_set_staging()
void brix_vfs_backend_set_staging (const char * root_canon, int on)
Definition at line 741 of file vfs_backend_config.c.
References brix_vfs_backend_entry_find(), and brix_vfs_backend_entry_t::staging.
Referenced by ngx_http_brix_webdav_merge_loc_conf().
brix_vfs_backend_set_xroot()
static void brix_vfs_backend_set_xroot (brix_vfs_backend_entry_t * e, const char * host, int port, int tls, int family) static
Definition at line 58 of file vfs_backend_config.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_t::inst, ngx_memcpy, brix_vfs_backend_entry_t::origin_family, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_port, brix_vfs_backend_entry_t::origin_tls, and tls.
Referenced by brix_vfs_backend_config_xroot().
vfs_backend_add_http_endpoint()
static ngx_int_t vfs_backend_add_http_endpoint (ngx_conf_t * cf, const char * root_canon, const char * host, int port, int tls, const char * base) static
Definition at line 362 of file vfs_backend_config.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_t::base, brix_vfs_backend_entry_find(), brix_vfs_backend_entry_t::host, brix_vfs_backend_entry_t::http_extra, brix_vfs_backend_entry_t::inst, brix_vfs_backend_entry_t::n_http_extra, brix_vfs_backend_entry_t::port, tls, and brix_vfs_backend_entry_t::tls.
Referenced by brix_vfs_backend_config_str().
vfs_backend_is_http_url()
static int vfs_backend_is_http_url (const u_char * data, size_t len) static
Definition at line 274 of file vfs_backend_config.c.
Referenced by brix_vfs_backend_config_str().
vfs_parse_http_origin()
static ngx_int_t vfs_parse_http_origin (ngx_conf_t * cf, u_char * seg, size_t segn, char * host, size_t host_cap, int * port_out, int * tls_out, char * base, size_t base_cap) static
Definition at line 285 of file vfs_backend_config.c.
References ngx_memcpy.
Referenced by brix_vfs_backend_config_str().