nginx-xrootd: src/fs/vfs/vfs_backend_registry.h File Reference
vfs_backend_registry.h File Reference
#include <ngx_core.h>
#include "fs/backend/sd.h"
#include "core/compat/af_policy.h"
Data Structures
struct brix_vfs_backend_cred_t
struct brix_vfs_backend_info_t
Functions
void brix_vfs_backend_config (const char *root_canon, const ngx_str_t *name, size_t block_size)
void brix_vfs_backend_config_xroot (const char *root_canon, const char *host, int port, int tls, int family)
void brix_vfs_backend_config_http (const char *root_canon, const char *host, int port, int tls, const char *base_path, int put_checksum)
void brix_vfs_backend_config_s3 (const char *root_canon, const char *host, int port, int tls, const char *bucket, int put_checksum)
ngx_int_t brix_vfs_backend_config_str (ngx_conf_t *cf, const char *root_canon, const ngx_str_t *backend, size_t block_size, int family)
void brix_vfs_backend_set_credential (const char *root_canon, const brix_vfs_backend_cred_t *cred)
void brix_vfs_backend_set_staging (const char *root_canon, int on)
brix_sd_instance_t * brix_vfs_backend_resolve (const char *root_canon, ngx_log_t *log)
int brix_vfs_backend_http_endpoint (const char *root_canon, const char **host, int *port, int *tls, const char **base)
ngx_int_t brix_vfs_backend_register_http_upstream (const char *up_root, const char *template_root, const char *host, int port, int tls, const char *store_suffix)
int brix_vfs_backend_http_endpoint_at (const char *root_canon, int idx, const char **host, int *port)
void brix_vfs_backend_set_http_ranks (const char *root_canon, const int *ranks, int n)
brix_sd_instance_t * brix_vfs_backend_resolve_for_path (const char *abs_path, const char **root_out, ngx_log_t *log)
ngx_uint_t brix_vfs_backend_export_count (void)
ngx_int_t brix_vfs_backend_export_info (ngx_uint_t i, brix_vfs_backend_info_t *out)
Function Documentation
brix_vfs_backend_config()
void brix_vfs_backend_config (const char * root_canon, const ngx_str_t * name, size_t block_size)
Definition at line 20 of file vfs_backend_config.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_t::block_size, brix_vfs_backend_entry_find(), brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_entry_t::inst, name, and ngx_memcpy.
Referenced by brix_server_validate_cache_stage_backend(), brix_vfs_backend_config_str(), and vfs_parse_xroot_or_driver_origin().
brix_vfs_backend_config_http()
void brix_vfs_backend_config_http (const char * root_canon, const char * host, int port, int tls, const char * base_path, int put_checksum)
Definition at line 29 of file vfs_backend_config_http.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_get_or_create(), host, brix_vfs_backend_entry_t::inst, brix_vfs_backend_entry_t::n_http_extra, ngx_memcpy, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_path, brix_vfs_backend_entry_t::origin_port, brix_vfs_backend_entry_t::origin_put_checksum, brix_vfs_backend_entry_t::origin_tls, port, and tls.
Referenced by vfs_parse_http_origin_list().
brix_vfs_backend_config_s3()
void brix_vfs_backend_config_s3 (const char * root_canon, const char * host, int port, int tls, const char * bucket, int put_checksum)
Definition at line 33 of file vfs_backend_config_s3.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_get_or_create(), host, brix_vfs_backend_entry_t::inst, ngx_memcpy, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_path, brix_vfs_backend_entry_t::origin_port, brix_vfs_backend_entry_t::origin_put_checksum, brix_vfs_backend_entry_t::origin_tls, port, and tls.
Referenced by vfs_parse_s3_origin().
brix_vfs_backend_config_str()
ngx_int_t brix_vfs_backend_config_str (ngx_conf_t * cf, const char * root_canon, const ngx_str_t * backend, size_t block_size, int family)
Definition at line 108 of file vfs_backend_config.c.
References brix_vfs_backend_config(), vfs_parse_ceph_origin(), vfs_parse_cephfsro_origin(), vfs_parse_http_origin_list(), vfs_parse_rados_origin(), vfs_parse_s3_origin(), vfs_parse_tape_origin(), and vfs_parse_xroot_or_driver_origin().
Referenced by brix_ftp_merge_conf(), brix_server_setup_export(), cvmfs_merge_cache(), s3_merge_export(), and webdav_configure_storage_backend().
brix_vfs_backend_config_xroot()
void brix_vfs_backend_config_xroot (const char * root_canon, const char * host, int port, int tls, int family)
Definition at line 73 of file vfs_backend_config_s3.c.
References brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_set_xroot(), host, port, and tls.
Referenced by vfs_parse_xroot_or_driver_origin().
brix_vfs_backend_export_count()
ngx_uint_t brix_vfs_backend_export_count (void)
Definition at line 278 of file vfs_backend_registry.c.
References brix_vfs_backend_count.
Referenced by brix_storage_backend_metrics_emit(), dashboard_build_storage_exports(), health_build_json(), ngx_http_brix_dashboard_vfs_exports_handler(), and vfs_browse_get_export().
brix_vfs_backend_export_info()
ngx_int_t brix_vfs_backend_export_info (ngx_uint_t i, brix_vfs_backend_info_t * out)
Definition at line 284 of file vfs_backend_registry.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_info_t::backend, brix_vfs_backend_count, brix_vfs_backends, brix_vfs_backend_info_t::has_proxy, brix_vfs_backend_info_t::has_token, brix_vfs_backend_info_t::host, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_port, brix_vfs_backend_entry_t::origin_tls, brix_vfs_backend_entry_t::origin_token, brix_vfs_backend_entry_t::origin_x509_proxy, brix_vfs_backend_info_t::port, brix_vfs_backend_entry_t::root_canon, brix_vfs_backend_info_t::root_canon, brix_vfs_backend_entry_t::staging, brix_vfs_backend_info_t::staging, and brix_vfs_backend_info_t::tls.
Referenced by brix_storage_backend_info_emit(), brix_storage_capacity_emit(), dashboard_build_storage_exports(), health_build_json(), ngx_http_brix_dashboard_vfs_download_handler(), ngx_http_brix_dashboard_vfs_exports_handler(), and ngx_http_brix_dashboard_vfs_files_handler().
brix_vfs_backend_http_endpoint()
int brix_vfs_backend_http_endpoint (const char * root_canon, const char ** host, int * port, int * tls, const char ** base)
Definition at line 45 of file vfs_backend_registry.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_find(), host, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_path, brix_vfs_backend_entry_t::origin_port, brix_vfs_backend_entry_t::origin_tls, port, and tls.
Referenced by brix_cvmfs_geo_passthrough().
brix_vfs_backend_http_endpoint_at()
int brix_vfs_backend_http_endpoint_at (const char * root_canon, int idx, const char ** host, int * port)
Definition at line 227 of file vfs_backend_config.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_find(), brix_vfs_backend_entry_t::host, host, brix_vfs_backend_entry_t::http_extra, brix_vfs_backend_entry_t::n_http_extra, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_port, port, and brix_vfs_backend_entry_t::port.
Referenced by brix_cvmfs_rtt_init_worker(), cvmfs_geo_apply_ranks(), and cvmfs_geo_compute_metrics().
brix_vfs_backend_register_http_upstream()
ngx_int_t brix_vfs_backend_register_http_upstream (const char * up_root, const char * template_root, const char * host, int port, int tls, const char * store_suffix)
Definition at line 275 of file vfs_backend_config.c.
References brix_vfs_backend_entry_t::backend, brix_mkdir_recursive(), brix_vfs_backend_entry_find(), brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_entry_t::cache_policy, brix_vfs_backend_entry_t::cache_tier, brix_tier_cfg_t::configured, brix_tier_cfg_t::driver, host, brix_vfs_backend_entry_t::inst, ngx_memcpy, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_path, brix_vfs_backend_entry_t::origin_port, brix_vfs_backend_entry_t::origin_tls, brix_tier_cfg_t::path, port, and tls.
Referenced by brix_cvmfs_upstream_get().
brix_vfs_backend_resolve()
brix_sd_instance_t * brix_vfs_backend_resolve (const char * root_canon, ngx_log_t * log)
Definition at line 304 of file vfs_backend_registry.c.
References brix_vfs_backend_count, brix_vfs_backend_entry_build(), brix_vfs_backends, log, and brix_vfs_backend_entry_t::root_canon.
Referenced by brix_cache_open_or_fill(), brix_cache_storage(), brix_cache_storage_cstore(), brix_cache_storage_decorator(), brix_cvmfs_upstream_get(), brix_handle_mkdir(), brix_make_vfs_body(), brix_open_read_probe(), brix_open_resolved_file(), brix_open_select_sd_inst(), brix_open_try_cache_offload(), brix_vfs_backend_mkpath(), brix_vfs_ctx_init(), brix_webdav_backend_instance(), cache_build_instance(), cache_build_wt_stage(), cms_node_exec_forward(), cvmfs_probe_done(), cvmfs_resolve_sd(), cvmfs_var_origin(), health_build_json(), mv_make_dst_parents(), op_path_existence_gate(), s3put_ensure_parent_dirs(), scan_run_walk(), stage_reconcile_one(), and webdav_resolve_stat().
brix_vfs_backend_resolve_for_path()
brix_sd_instance_t * brix_vfs_backend_resolve_for_path (const char * abs_path, const char ** root_out, ngx_log_t * log)
Definition at line 326 of file vfs_backend_registry.c.
References brix_vfs_backend_count, brix_vfs_backend_entry_build(), brix_vfs_backends, log, and brix_vfs_backend_entry_t::root_canon.
Referenced by brix_commit_staged().
brix_vfs_backend_set_credential()
void brix_vfs_backend_set_credential (const char * root_canon, const brix_vfs_backend_cred_t * cred)
Definition at line 64 of file vfs_backend_config.c.
References brix_vfs_backend_cred_t::bearer, brix_vfs_backend_entry_find(), brix_vfs_backend_cred_t::ca_dir, brix_vfs_backend_entry_t::inst, brix_vfs_backend_entry_t::origin_ca_dir, brix_vfs_backend_entry_t::origin_s3_access_key, brix_vfs_backend_entry_t::origin_s3_region, brix_vfs_backend_entry_t::origin_s3_secret_key, brix_vfs_backend_entry_t::origin_sss_keytab, brix_vfs_backend_entry_t::origin_token, brix_vfs_backend_entry_t::origin_x509_key, brix_vfs_backend_entry_t::origin_x509_proxy, brix_vfs_backend_cred_t::s3_access_key, brix_vfs_backend_cred_t::s3_region, brix_vfs_backend_cred_t::s3_secret_key, brix_vfs_backend_cred_t::sss_keytab, brix_vfs_backend_cred_t::x509_key, and brix_vfs_backend_cred_t::x509_proxy.
Referenced by brix_ftp_init_process(), brix_ftp_install_backend_credential(), brix_init_server_backend_credential(), brix_server_set_storage_credential(), s3_export_attach_credential(), and webdav_set_storage_credential().
brix_vfs_backend_set_http_ranks()
void brix_vfs_backend_set_http_ranks (const char * root_canon, const int * ranks, int n)
Definition at line 250 of file vfs_backend_config.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_find(), brix_vfs_backend_entry_t::has_http_ranks, brix_vfs_backend_entry_t::http_ranks, and brix_vfs_backend_entry_t::inst.
Referenced by cvmfs_geo_apply_ranks().
brix_vfs_backend_set_staging()
void brix_vfs_backend_set_staging (const char * root_canon, int on)
Definition at line 149 of file vfs_backend_config.c.
References brix_vfs_backend_entry_find(), and brix_vfs_backend_entry_t::staging.
Referenced by webdav_configure_storage_backend().