nginx-xrootd: src/fs/vfs/vfs_staged.c File Reference
vfs_staged.c File Reference
#include "vfs_internal.h"
#include "core/compat/staged_file.h"
#include "fs/xfer/xfer.h"
#include <unistd.h>
Functions
static char * staged_pool_strdup (ngx_pool_t *pool, const char *s, size_t *lenp)
static brix_vfs_staged_t * staged_open_fail (int *err_out)
static brix_vfs_staged_t * staged_alloc_handle (brix_vfs_ctx_t *ctx, int *err_out)
static ngx_int_t staged_open_driver (brix_vfs_ctx_t *ctx, brix_vfs_staged_t *st, const char *final_path, mode_t mode, int *err_out)
static ngx_int_t staged_open_posix (brix_vfs_ctx_t *ctx, brix_vfs_staged_t *st, const brix_staged_open_req_t *oreq, int *err_out)
brix_vfs_staged_t * brix_vfs_staged_open (brix_vfs_ctx_t *ctx, mode_t mode, ngx_uint_t attempts, int *err_out)
ngx_fd_t brix_vfs_staged_fd (const brix_vfs_staged_t *st)
ngx_uint_t brix_vfs_staged_is_driver (const brix_vfs_staged_t *st)
ngx_int_t brix_vfs_staged_write (brix_vfs_staged_t *st, const void *buf, size_t len, off_t off)
const char * brix_vfs_staged_tmp_path (const brix_vfs_staged_t *st)
ngx_int_t brix_vfs_staged_commit (brix_vfs_staged_t *st, unsigned excl)
void brix_vfs_staged_abort (brix_vfs_staged_t *st, unsigned remove_tmp)
Function Documentation
brix_vfs_staged_abort()
void brix_vfs_staged_abort (brix_vfs_staged_t * st, unsigned remove_tmp)
Definition at line 397 of file vfs_staged.c.
References brix_staged_abort().
Referenced by fhandle_release_descriptors(), s3_chunk_decode_failed(), s3_post_write_object(), s3_put_aio_done(), s3_put_streaming(), s3put_select_codec(), s3put_stream_aws_chunked(), s3put_stream_body(), s3put_stream_offload(), s3put_stream_sync(), webdav_put_aio_done(), webdav_put_select_codec(), webdav_put_stream_body(), webdav_put_try_threaded(), and webdav_put_write_sync().
brix_vfs_staged_commit()
ngx_int_t brix_vfs_staged_commit (brix_vfs_staged_t * st, unsigned excl)
Definition at line 322 of file vfs_staged.c.
References brix_lstat_confined_canon(), BRIX_METRIC_OP_WRITE, brix_staged_commit(), brix_staged_commit_excl(), brix_vfs_ctx_path(), brix_vfs_now_ns(), brix_vfs_observe_ctx_op(), BRIX_XFER_COMMIT_ERR, brix_xfer_finish(), BRIX_XFER_OK, BRIX_XFER_STAGE, and stat().
Referenced by brix_staged_commit_handle(), s3_commit_put(), s3_post_write_object(), webdav_put_aio_done(), and webdav_put_commit().
brix_vfs_staged_fd()
ngx_fd_t brix_vfs_staged_fd (const brix_vfs_staged_t * st)
Definition at line 265 of file vfs_staged.c.
Referenced by s3_chunk_aio_thread(), s3_post_write_object(), s3_put_aio_thread(), s3_put_streaming(), s3put_stream_sync(), webdav_put_aio_thread(), and webdav_put_write_sync().
brix_vfs_staged_is_driver()
ngx_uint_t brix_vfs_staged_is_driver (const brix_vfs_staged_t * st)
Definition at line 274 of file vfs_staged.c.
Referenced by s3_put_aio_thread(), webdav_put_aio_thread(), and webdav_put_write_sync().
brix_vfs_staged_open()
brix_vfs_staged_t * brix_vfs_staged_open (brix_vfs_ctx_t * ctx, mode_t mode, ngx_uint_t attempts, int * err_out)
Definition at line 225 of file vfs_staged.c.
References brix_sd_default_driver(), brix_vfs_ctx_path(), brix_staged_open_req_t::root_canon, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::sd, staged_alloc_handle(), staged_open_driver(), and staged_open_posix().
Referenced by brix_open_dispatch_staged(), s3_post_write_object(), s3put_open_target(), and webdav_put_open_target().
brix_vfs_staged_tmp_path()
const char * brix_vfs_staged_tmp_path (const brix_vfs_staged_t * st)
Definition at line 311 of file vfs_staged.c.
brix_vfs_staged_write()
ngx_int_t brix_vfs_staged_write (brix_vfs_staged_t * st, const void * buf, size_t len, off_t off)
Definition at line 282 of file vfs_staged.c.
References brix_vfs_pwrite_full().
Referenced by brix_http_body_staged_spooled_buf(), brix_http_body_write_to_staged(), and brix_staged_append().
staged_alloc_handle()
static brix_vfs_staged_t * staged_alloc_handle (brix_vfs_ctx_t * ctx, int * err_out) static
Definition at line 95 of file vfs_staged.c.
References brix_vfs_ctx_path(), brix_vfs_require_write(), brix_vfs_ctx_t::log, ngx_pcalloc(), brix_vfs_ctx_t::pool, brix_vfs_ctx_t::root_canon, staged_open_fail(), and staged_pool_strdup().
Referenced by brix_vfs_staged_open().
staged_open_driver()
static ngx_int_t staged_open_driver (brix_vfs_ctx_t * ctx, brix_vfs_staged_t * st, const char * final_path, mode_t mode, int * err_out) static
Definition at line 168 of file vfs_staged.c.
References brix_sd_staged_open_maybe_cred(), brix_vfs_backend_cred(), brix_vfs_export_relative(), and brix_vfs_ctx_t::sd.
Referenced by brix_vfs_staged_open().
staged_open_fail()
static brix_vfs_staged_t * staged_open_fail (int * err_out) static
Definition at line 70 of file vfs_staged.c.
Referenced by staged_alloc_handle().
staged_open_posix()
static ngx_int_t staged_open_posix (brix_vfs_ctx_t * ctx, brix_vfs_staged_t * st, const brix_staged_open_req_t * oreq, int * err_out) static
Definition at line 208 of file vfs_staged.c.
References brix_staged_open(), and brix_vfs_ctx_t::log.
Referenced by brix_vfs_staged_open().
staged_pool_strdup()
static char * staged_pool_strdup (ngx_pool_t * pool, const char * s, size_t * lenp) static
Definition at line 36 of file vfs_staged.c.
References ngx_memcpy, ngx_pnalloc(), and s.
Referenced by staged_alloc_handle().