nginx-xrootd: client/lib/fs/backend/s3/vfs_s3_transport.c File Reference
vfs_s3_transport.c File Reference
#include "vfs_s3_internal.h"
#include "fs/backend/s3/sd_s3_transport.h"
#include <stdlib.h>
Functions
static int s3t_request (void *tctx, const char *host, int port, int tls, const char *method, const char *path_and_query, const char *headers, const void *body, size_t body_len, int timeout_ms, brix_s3_resp_t *resp, char *errbuf, size_t errcap)
static int s3t_resp_header (const brix_s3_resp_t *resp, const char *name, char *out, size_t outcap)
static const char * s3t_resp_headers_raw (const brix_s3_resp_t *resp)
static const void * s3t_resp_body (const brix_s3_resp_t *resp, size_t *len)
static void s3t_resp_free (brix_s3_resp_t *resp)
Variables
const brix_s3_transport_t brix_s3_http_transport
Function Documentation
s3t_request()
static int s3t_request (void * tctx, const char * host, int port, int tls, const char * method, const char * path_and_query, const char * headers, const void * body, size_t body_len, int timeout_ms, brix_s3_resp_t * resp, char * errbuf, size_t errcap) static
Definition at line 18 of file vfs_s3_transport.c.
References brix_http_req(), brix_status_clear(), host, brix_status::msg, brix_s3_resp_t::opaque, port, brix_http_resp::status, brix_s3_resp_t::status, and tls.
s3t_resp_body()
static const void * s3t_resp_body (const brix_s3_resp_t * resp, size_t * len) static
Definition at line 69 of file vfs_s3_transport.c.
References brix_http_resp::body, brix_http_resp::body_len, and brix_s3_resp_t::opaque.
s3t_resp_free()
static void s3t_resp_free (brix_s3_resp_t * resp) static
Definition at line 79 of file vfs_s3_transport.c.
References brix_http_resp_free(), and brix_s3_resp_t::opaque.
s3t_resp_header()
static int s3t_resp_header (const brix_s3_resp_t * resp, const char * name, char * out, size_t outcap) static
Definition at line 51 of file vfs_s3_transport.c.
References brix_http_header(), name, and brix_s3_resp_t::opaque.
s3t_resp_headers_raw()
static const char * s3t_resp_headers_raw (const brix_s3_resp_t * resp) static
Definition at line 61 of file vfs_s3_transport.c.
References brix_http_resp::headers, and brix_s3_resp_t::opaque.
Variable Documentation
brix_s3_http_transport
const brix_s3_transport_t brix_s3_http_transport
Initial value:
= {
    .request     = s3t_request,
    .resp_header = s3t_resp_header,
    .resp_headers_raw = s3t_resp_headers_raw,
    .resp_body   = s3t_resp_body,
    .resp_free   = s3t_resp_free,
}
Definition at line 88 of file vfs_s3_transport.c.
Referenced by s3_be_open(), and s3_open_read().