nginx-xrootd: src/fs/vfs/vfs_cred.c File Reference
vfs_cred.c File Reference
#include "vfs_internal.h"
#include "fs/backend/cache/sd_cache.h"
#include "fs/backend/stage/sd_stage.h"
#include "fs/backend/cred_mint.h"
Functions
void brix_vfs_ctx_bind_backend_cred (brix_vfs_ctx_t *vctx, const ngx_str_t *cred_dir, ngx_uint_t fallback_deny)
void brix_vfs_ctx_bind_backend_mint (brix_vfs_ctx_t *vctx, const ngx_str_t *ca_cert, const ngx_str_t *ca_key, ngx_uint_t ttl_secs)
static ngx_int_t vfs_cred_live_bag (brix_vfs_ctx_t *ctx, brix_sd_cred_t *cred, int *use_cred, int *err_out, int *handled)
static ngx_int_t vfs_cred_maybe_mint (brix_vfs_ctx_t *ctx, int cap_ok, brix_sd_ucred_t *store, ngx_int_t rc)
static ngx_int_t vfs_cred_no_cap (brix_vfs_ctx_t *ctx, brix_sd_ucred_t *store, int *err_out)
static void vfs_cred_fill_user (brix_vfs_ctx_t *ctx, brix_sd_ucred_t *store, brix_sd_cred_t *cred, int *use_cred)
static ngx_int_t vfs_cred_deny_or_fallback (brix_vfs_ctx_t *ctx, brix_sd_ucred_t *store, int *err_out)
static ngx_int_t vfs_backend_cred_decide (brix_vfs_ctx_t *ctx, int cap_ok, brix_sd_ucred_t *store, brix_sd_cred_t *cred, int *use_cred, int *err_out)
static int vfs_leaf_per_user_capable (const brix_sd_instance_t *leaf)
static int vfs_backend_cap_ok (const brix_vfs_ctx_t *ctx)
ngx_int_t brix_vfs_backend_cred (brix_vfs_ctx_t *ctx, brix_sd_ucred_t *store, brix_sd_cred_t *cred, int *use_cred, int *err_out)
int brix_vfs_cred_gate_active (brix_vfs_ctx_t *ctx)
brix_sd_instance_t * brix_vfs_ns_leaf (brix_sd_instance_t *top)
static int vfs_ns_cap_ok (const brix_vfs_ctx_t *ctx)
ngx_int_t brix_vfs_ns_cred (brix_vfs_ctx_t *ctx, brix_sd_ucred_t *store, brix_sd_cred_t *cred, int *use_cred, int *err_out)
Function Documentation
brix_vfs_backend_cred()
ngx_int_t brix_vfs_backend_cred (brix_vfs_ctx_t * ctx, brix_sd_ucred_t * store, brix_sd_cred_t * cred, int * use_cred, int * err_out)
Definition at line 430 of file vfs_cred.c.
References vfs_backend_cap_ok(), and vfs_backend_cred_decide().
Referenced by brix_open_read_probe(), brix_open_resolved_via_driver(), brix_vfs_open_via_driver(), and staged_open_driver().
brix_vfs_cred_gate_active()
int brix_vfs_cred_gate_active (brix_vfs_ctx_t * ctx)
Definition at line 459 of file vfs_cred.c.
References BRIX_CRED_SELECT, brix_sd_cred_accept(), BRIX_SD_CRED_IDENTITY, brix_vfs_backend_mode(), brix_vfs_ns_leaf(), brix_vfs_ctx_t::identity, brix_vfs_ctx_t::sd, and brix_vfs_ctx_t::storage_cred_dir.
Referenced by brix_vfs_chmod(), brix_vfs_copy_driver(), brix_vfs_delete_via_driver(), brix_vfs_getxattr(), brix_vfs_listxattr(), brix_vfs_probe(), brix_vfs_rename(), brix_vfs_setattr(), brix_vfs_stat_impl(), brix_vfs_xattr_write_gate(), vfs_dir_open_driver(), and vfs_mkdir_backend().
brix_vfs_ctx_bind_backend_cred()
void brix_vfs_ctx_bind_backend_cred (brix_vfs_ctx_t * vctx, const ngx_str_t * cred_dir, ngx_uint_t fallback_deny)
Definition at line 62 of file vfs_cred.c.
References brix_vfs_ctx_t::storage_cred_deny, and brix_vfs_ctx_t::storage_cred_dir.
Referenced by brix_dirlist_open_dir(), brix_handle_mkdir(), brix_handle_setattr(), brix_handle_truncate(), brix_open_build_cred_ctx(), brix_open_read_probe(), brix_qcksum_open(), brix_statx_symlink_fallback_stat(), fattr_bind_vctx(), fattr_recurse_init_node_ctx(), get_init_vfs_ctx(), mv_bind_vfs(), op_vfs_ctx(), s3_build_vfs_ctx(), s3_chunk_finalize(), s3_commit_put(), s3_copy_vfs_ctx(), s3_put_aio_done(), s3_vfs_ctx(), stat_vfs_ctx_prepare(), webdav_copy_file_vfs_init(), webdav_copy_probe(), webdav_lock_vfs_ctx_init(), webdav_move_execute_cred(), webdav_move_probe(), webdav_ns_vfs_ctx_init(), webdav_put_precheck(), webdav_put_vfs_ctx_init(), and webdav_resolve_stat().
brix_vfs_ctx_bind_backend_mint()
void brix_vfs_ctx_bind_backend_mint (brix_vfs_ctx_t * vctx, const ngx_str_t * ca_cert, const ngx_str_t * ca_key, ngx_uint_t ttl_secs)
Definition at line 90 of file vfs_cred.c.
References brix_vfs_ctx_t::storage_cred_mint_ca_cert, brix_vfs_ctx_t::storage_cred_mint_ca_key, and brix_vfs_ctx_t::storage_cred_mint_ttl.
Referenced by brix_handle_truncate(), brix_open_build_cred_ctx(), brix_qcksum_open(), get_init_vfs_ctx(), s3_build_vfs_ctx(), s3_copy_vfs_ctx(), s3_vfs_ctx(), webdav_copy_file_vfs_init(), and webdav_put_vfs_ctx_init().
brix_vfs_ns_cred()
ngx_int_t brix_vfs_ns_cred (brix_vfs_ctx_t * ctx, brix_sd_ucred_t * store, brix_sd_cred_t * cred, int * use_cred, int * err_out)
Definition at line 574 of file vfs_cred.c.
References vfs_backend_cred_decide(), and vfs_ns_cap_ok().
Referenced by brix_vfs_chmod(), brix_vfs_copy_driver(), brix_vfs_delete_via_driver(), brix_vfs_getxattr(), brix_vfs_listxattr(), brix_vfs_probe(), brix_vfs_rename(), brix_vfs_setattr(), brix_vfs_stat_impl(), brix_vfs_xattr_write_gate(), vfs_dir_open_driver(), and vfs_mkdir_backend().
brix_vfs_ns_leaf()
brix_sd_instance_t * brix_vfs_ns_leaf (brix_sd_instance_t * top)
Definition at line 497 of file vfs_cred.c.
References brix_sd_cache_source_instance(), and brix_sd_stage_source_instance().
Referenced by brix_open_read_probe(), brix_open_write_needs_staged(), brix_vfs_backend_accepts_proxy(), brix_vfs_chmod(), brix_vfs_copy_driver(), brix_vfs_cred_gate_active(), brix_vfs_deleg_live_cred(), brix_vfs_delete_via_driver(), brix_vfs_getxattr(), brix_vfs_listxattr(), brix_vfs_probe(), brix_vfs_removexattr(), brix_vfs_rename(), brix_vfs_setattr(), brix_vfs_setxattr(), brix_vfs_stat_impl(), s3put_ensure_parent_dirs(), vfs_backend_cap_ok(), vfs_backend_cred_decide(), vfs_dir_open_driver(), vfs_mkdir_backend(), and vfs_ns_cap_ok().
vfs_backend_cap_ok()
static int vfs_backend_cap_ok (const brix_vfs_ctx_t * ctx) static
Definition at line 408 of file vfs_cred.c.
References brix_vfs_ns_leaf(), brix_vfs_ctx_t::sd, and vfs_leaf_per_user_capable().
Referenced by brix_vfs_backend_cred().
vfs_backend_cred_decide()
static ngx_int_t vfs_backend_cred_decide (brix_vfs_ctx_t * ctx, int cap_ok, brix_sd_ucred_t * store, brix_sd_cred_t * cred, int * use_cred, int * err_out) static
Definition at line 302 of file vfs_cred.c.
References brix_identity_vo_csv_cstr(), brix_sd_cred_accept(), BRIX_SD_CRED_IDENTITY, brix_sd_ucred_principal(), brix_sd_ucred_select(), brix_vfs_ns_leaf(), brix_vfs_ctx_t::identity, brix_sd_cred_t::principal, brix_sd_ucred_t::principal, brix_vfs_ctx_t::sd, brix_vfs_ctx_t::storage_cred_dir, vfs_cred_deny_or_fallback(), vfs_cred_fill_user(), vfs_cred_live_bag(), vfs_cred_maybe_mint(), vfs_cred_no_cap(), and brix_sd_cred_t::vos.
Referenced by brix_vfs_backend_cred(), and brix_vfs_ns_cred().
vfs_cred_deny_or_fallback()
static ngx_int_t vfs_cred_deny_or_fallback (brix_vfs_ctx_t * ctx, brix_sd_ucred_t * store, int * err_out) static
Definition at line 258 of file vfs_cred.c.
References BRIX_CRED_OUTCOME_DENY, BRIX_CRED_OUTCOME_FALLBACK, brix_metric_cred_result(), brix_vfs_metrics_proto(), brix_sd_ucred_t::expired, brix_sd_ucred_t::key, brix_vfs_ctx_t::log, brix_sd_ucred_t::principal, brix_vfs_ctx_t::storage_cred_deny, and brix_vfs_ctx_t::storage_cred_dir.
Referenced by vfs_backend_cred_decide().
vfs_cred_fill_user()
static void vfs_cred_fill_user (brix_vfs_ctx_t * ctx, brix_sd_ucred_t * store, brix_sd_cred_t * cred, int * use_cred) static
Definition at line 223 of file vfs_cred.c.
References brix_sd_cred_t::bearer, brix_sd_ucred_t::bearer, BRIX_CRED_OUTCOME_USER, brix_identity_vo_csv_cstr(), brix_metric_cred_result(), brix_vfs_metrics_proto(), brix_sd_cred_t::ceph_keyring, brix_sd_ucred_t::ceph_keyring, brix_sd_cred_t::ceph_user, brix_sd_ucred_t::ceph_user, brix_sd_cred_t::cred_dir, brix_sd_cred_t::fallback_deny, brix_vfs_ctx_t::identity, brix_sd_ucred_t::is_bearer, brix_sd_ucred_t::is_ceph, brix_sd_ucred_t::is_s3, brix_sd_cred_t::key, brix_sd_ucred_t::key, brix_sd_ucred_t::path, brix_sd_cred_t::principal, brix_sd_ucred_t::principal, brix_sd_cred_t::s3_ak, brix_sd_ucred_t::s3_ak, brix_sd_cred_t::s3_region, brix_sd_ucred_t::s3_region, brix_sd_cred_t::s3_sk, brix_sd_ucred_t::s3_sk, brix_vfs_ctx_t::storage_cred_deny, brix_vfs_ctx_t::storage_cred_dir, brix_sd_cred_t::vos, and brix_sd_cred_t::x509_proxy.
Referenced by vfs_backend_cred_decide().
vfs_cred_live_bag()
static ngx_int_t vfs_cred_live_bag (brix_vfs_ctx_t * ctx, brix_sd_cred_t * cred, int * use_cred, int * err_out, int * handled) static
Definition at line 120 of file vfs_cred.c.
References BRIX_CRED_EXCHANGE, BRIX_CRED_PASSTHROUGH, brix_vfs_backend_mode(), and brix_vfs_deleg_live_cred().
Referenced by vfs_backend_cred_decide().
vfs_cred_maybe_mint()
static ngx_int_t vfs_cred_maybe_mint (brix_vfs_ctx_t * ctx, int cap_ok, brix_sd_ucred_t * store, ngx_int_t rc) static
Definition at line 153 of file vfs_cred.c.
References brix_cred_mint(), brix_sd_ucred_resolve(), brix_sd_ucred_t::key, brix_vfs_ctx_t::log, brix_sd_ucred_t::principal, brix_vfs_ctx_t::storage_cred_dir, brix_vfs_ctx_t::storage_cred_mint_ca_cert, brix_vfs_ctx_t::storage_cred_mint_ca_key, and brix_vfs_ctx_t::storage_cred_mint_ttl.
Referenced by vfs_backend_cred_decide().
vfs_cred_no_cap()
static ngx_int_t vfs_cred_no_cap (brix_vfs_ctx_t * ctx, brix_sd_ucred_t * store, int * err_out) static
Definition at line 185 of file vfs_cred.c.
References BRIX_CRED_OUTCOME_DENY, BRIX_CRED_OUTCOME_FALLBACK, brix_metric_cred_result(), brix_sd_backend_name(), brix_vfs_metrics_proto(), brix_vfs_ctx_t::log, brix_sd_ucred_t::principal, brix_vfs_ctx_t::sd, and brix_vfs_ctx_t::storage_cred_deny.
Referenced by vfs_backend_cred_decide().
vfs_leaf_per_user_capable()
static int vfs_leaf_per_user_capable (const brix_sd_instance_t * leaf) static
Definition at line 380 of file vfs_cred.c.
Referenced by vfs_backend_cap_ok(), and vfs_ns_cap_ok().
vfs_ns_cap_ok()
static int vfs_ns_cap_ok (const brix_vfs_ctx_t * ctx) static
Definition at line 544 of file vfs_cred.c.
References brix_vfs_ns_leaf(), brix_vfs_ctx_t::sd, and vfs_leaf_per_user_capable().
Referenced by brix_vfs_ns_cred().