nginx-xrootd: src/fs/vfs/vfs_backend_config_http.c File Reference
vfs_backend_config_http.c File Reference
#include "vfs_backend_config_internal.h"
#include <string.h>
Functions
void brix_vfs_backend_config_http (const char *root_canon, const char *host, int port, int tls, const char *base_path, int put_checksum)
static int vfs_backend_is_http_url (const u_char *data, size_t len)
static ngx_int_t vfs_http_origin_strip_scheme (ngx_conf_t *cf, u_char *seg, size_t segn, vfs_origin_parse_t *out)
static ngx_int_t vfs_http_origin_host_port (ngx_conf_t *cf, u_char *h, size_t hplen, int htls, vfs_origin_parse_t *out)
static ngx_int_t vfs_parse_http_origin (ngx_conf_t *cf, u_char *seg, size_t segn, vfs_origin_parse_t *out)
static ngx_int_t vfs_backend_add_http_endpoint (ngx_conf_t *cf, const char *root_canon, const vfs_origin_parse_t *parsed)
ngx_int_t vfs_parse_http_origin_list (ngx_conf_t *cf, const char *root_canon, const ngx_str_t *sb)
Function Documentation
brix_vfs_backend_config_http()
void brix_vfs_backend_config_http (const char * root_canon, const char * host, int port, int tls, const char * base_path, int put_checksum)
Definition at line 29 of file vfs_backend_config_http.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_get_or_create(), host, brix_vfs_backend_entry_t::inst, brix_vfs_backend_entry_t::n_http_extra, ngx_memcpy, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_path, brix_vfs_backend_entry_t::origin_port, brix_vfs_backend_entry_t::origin_put_checksum, brix_vfs_backend_entry_t::origin_tls, port, and tls.
Referenced by vfs_parse_http_origin_list().
vfs_backend_add_http_endpoint()
static ngx_int_t vfs_backend_add_http_endpoint (ngx_conf_t * cf, const char * root_canon, const vfs_origin_parse_t * parsed) static
Definition at line 184 of file vfs_backend_config_http.c.
References brix_vfs_backend_entry_t::backend, vfs_origin_parse_t::base, brix_vfs_backend_entry_t::base, brix_vfs_backend_entry_find(), vfs_origin_parse_t::host, brix_vfs_backend_entry_t::host, brix_vfs_backend_entry_t::http_extra, brix_vfs_backend_entry_t::inst, brix_vfs_backend_entry_t::n_http_extra, vfs_origin_parse_t::port, brix_vfs_backend_entry_t::port, vfs_origin_parse_t::tls, and brix_vfs_backend_entry_t::tls.
Referenced by vfs_parse_http_origin_list().
vfs_backend_is_http_url()
static int vfs_backend_is_http_url (const u_char * data, size_t len) static
Definition at line 57 of file vfs_backend_config_http.c.
Referenced by vfs_parse_http_origin_list().
vfs_http_origin_host_port()
static ngx_int_t vfs_http_origin_host_port (ngx_conf_t * cf, u_char * h, size_t hplen, int htls, vfs_origin_parse_t * out) static
Definition at line 99 of file vfs_backend_config_http.c.
References vfs_origin_parse_t::host_len, and vfs_origin_parse_t::port.
Referenced by vfs_parse_http_origin().
vfs_http_origin_strip_scheme()
static ngx_int_t vfs_http_origin_strip_scheme (ngx_conf_t * cf, u_char * seg, size_t segn, vfs_origin_parse_t * out) static
Definition at line 69 of file vfs_backend_config_http.c.
References vfs_origin_parse_t::rest, vfs_origin_parse_t::rest_len, and vfs_origin_parse_t::tls.
Referenced by vfs_parse_http_origin().
vfs_parse_http_origin()
static ngx_int_t vfs_parse_http_origin (ngx_conf_t * cf, u_char * seg, size_t segn, vfs_origin_parse_t * out) static
Definition at line 128 of file vfs_backend_config_http.c.
References vfs_origin_parse_t::base, vfs_origin_parse_t::base_cap, vfs_origin_parse_t::host, vfs_origin_parse_t::host_cap, vfs_origin_parse_t::host_len, ngx_memcpy, vfs_origin_parse_t::rest, vfs_origin_parse_t::rest_len, vfs_origin_parse_t::tls, vfs_http_origin_host_port(), and vfs_http_origin_strip_scheme().
Referenced by vfs_parse_http_origin_list().
vfs_parse_http_origin_list()
ngx_int_t vfs_parse_http_origin_list (ngx_conf_t * cf, const char * root_canon, const ngx_str_t * sb)
Definition at line 226 of file vfs_backend_config_http.c.
References vfs_origin_parse_t::base, vfs_origin_parse_t::base_cap, brix_vfs_backend_config_http(), host, vfs_origin_parse_t::host, vfs_origin_parse_t::host_cap, vfs_origin_parse_t::port, vfs_origin_parse_t::tls, vfs_backend_add_http_endpoint(), vfs_backend_is_http_url(), and vfs_parse_http_origin().
Referenced by brix_vfs_backend_config_str().