nginx-xrootd: src/fs/vfs/vfs_open.c File Reference
vfs_open.c File Reference
#include "vfs_internal.h"
#include "vfs_backend_registry.h"
#include "fs/cache/open.h"
#include "fs/path/beneath.h"
#include "core/compat/log_diag.h"
Functions
void brix_vfs_ctx_init (brix_vfs_ctx_t *vctx, ngx_pool_t *pool, ngx_log_t *log, brix_proto_t proto, const char *root_canon, const char *cache_root_canon, int allow_write, int is_tls, brix_identity_t *identity, const char *resolved_path)
void brix_vfs_fill_stat (const struct stat *st, brix_vfs_stat_t *out)
char * brix_vfs_copy_path (ngx_pool_t *pool, const char *path)
ngx_int_t brix_vfs_adopt_fd (brix_vfs_ctx_t *ctx, const char *path, ngx_fd_t fd, unsigned from_cache, unsigned writable, brix_vfs_file_t **out)
ngx_int_t brix_vfs_adopt_obj (brix_vfs_ctx_t *ctx, const char *path, brix_sd_obj_t *o, unsigned writable, brix_vfs_file_t **out)
const char * brix_vfs_export_relative_root (const char *path, const char *root_canon)
const char * brix_vfs_export_relative (const brix_vfs_ctx_t *ctx, const char *path)
static int brix_vfs_open_flags (ngx_uint_t flags)
static int brix_vfs_to_sd_flags (ngx_uint_t flags)
static ngx_int_t brix_vfs_mkdir_parent_path (brix_vfs_ctx_t *ctx, const char *path)
brix_vfs_file_t * brix_vfs_open (brix_vfs_ctx_t *ctx, ngx_uint_t flags, int *err_out)
ngx_int_t brix_vfs_close (brix_vfs_file_t *fh, ngx_log_t *log)
ngx_fd_t brix_vfs_file_fd (const brix_vfs_file_t *fh)
void brix_vfs_file_sd_obj (const brix_vfs_file_t *fh, brix_sd_obj_t *out)
ssize_t brix_vfs_file_pread (brix_vfs_file_t *fh, void *buf, size_t len, off_t off)
ngx_fd_t brix_vfs_file_sendfile_fd (const brix_vfs_file_t *fh)
ngx_uint_t brix_vfs_file_can_sendfile (const brix_vfs_file_t *fh)
const char * brix_vfs_file_backend_name (const brix_vfs_file_t *fh)
const char * brix_vfs_file_path (const brix_vfs_file_t *fh)
off_t brix_vfs_file_size (const brix_vfs_file_t *fh)
time_t brix_vfs_file_mtime (const brix_vfs_file_t *fh)
ngx_uint_t brix_vfs_file_from_cache (const brix_vfs_file_t *fh)
ngx_int_t brix_vfs_file_stat (const brix_vfs_file_t *fh, brix_vfs_stat_t *stat_out)
Function Documentation
brix_vfs_adopt_fd()
ngx_int_t brix_vfs_adopt_fd (brix_vfs_ctx_t * ctx, const char * path, ngx_fd_t fd, unsigned from_cache, unsigned writable, brix_vfs_file_t ** out)
Definition at line 125 of file vfs_open.c.
References brix_vfs_copy_path(), brix_vfs_ctx_sd_obj(), brix_sd_stat_t::ctime, brix_sd_stat_t::ino, brix_vfs_ctx_t::is_tls, brix_vfs_ctx_t::log, brix_sd_stat_t::mode, brix_sd_stat_t::mtime, ngx_pcalloc(), brix_vfs_ctx_t::pool, and brix_sd_stat_t::size.
Referenced by brix_vfs_open().
brix_vfs_adopt_obj()
ngx_int_t brix_vfs_adopt_obj (brix_vfs_ctx_t * ctx, const char * path, brix_sd_obj_t * o, unsigned writable, brix_vfs_file_t ** out)
Definition at line 232 of file vfs_open.c.
References brix_vfs_copy_path(), brix_sd_stat_t::ctime, brix_sd_stat_t::ino, brix_vfs_ctx_t::is_tls, brix_vfs_ctx_t::log, brix_sd_stat_t::mode, brix_sd_stat_t::mtime, ngx_pcalloc(), brix_vfs_ctx_t::pool, and brix_sd_stat_t::size.
Referenced by brix_cache_open(), and brix_vfs_open().
brix_vfs_close()
ngx_int_t brix_vfs_close (brix_vfs_file_t * fh, ngx_log_t * log)
Definition at line 554 of file vfs_open.c.
References BRIX_DIAG_ERR, and log.
Referenced by brix_cksum_aio_done(), brix_dig_handle(), brix_handle_truncate(), brix_http_serve_file_ranged(), brix_query_cksum_path(), brix_zip_http_serve(), copy_block_to_remote(), copy_download(), copy_one_l2r(), copy_one_r2l(), copy_remote_to_block(), copy_upload(), copy_vfs_to_vfs(), copy_web_upload(), cvmfs_tier_get(), do_download(), do_upload(), ngx_http_brix_dashboard_vfs_download_handler(), s3_handle_get(), s3_handle_head(), s3_handle_upload_part_copy(), s3_put_checksum_apply(), s3_put_trailer_checksum_apply(), webdav_handle_get(), webdav_handle_head(), and webdav_handle_lock_inner().
brix_vfs_copy_path()
char * brix_vfs_copy_path (ngx_pool_t * pool, const char * path)
Definition at line 98 of file vfs_open.c.
References ngx_memcpy, and ngx_pnalloc().
Referenced by brix_vfs_adopt_fd(), brix_vfs_adopt_obj(), brix_vfs_mkdir_parent_path(), and brix_vfs_opendir_impl().
brix_vfs_ctx_init()
void brix_vfs_ctx_init (brix_vfs_ctx_t * vctx, ngx_pool_t * pool, ngx_log_t * log, brix_proto_t proto, const char * root_canon, const char * cache_root_canon, int allow_write, int is_tls, brix_identity_t * identity, const char * resolved_path)
Definition at line 41 of file vfs_open.c.
References brix_vfs_ctx_t::allow_write, brix_vfs_backend_resolve(), brix_vfs_ctx_t::cache_enabled, brix_vfs_ctx_t::cache_root_canon, brix_vfs_ctx_t::identity, brix_path_result_t::is_confined, brix_vfs_ctx_t::is_tls, log, brix_vfs_ctx_t::log, brix_vfs_ctx_t::metrics_proto, brix_vfs_ctx_t::pool, brix_path_result_t::resolved, brix_vfs_ctx_t::resolved, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::rootfd, and brix_vfs_ctx_t::sd.
Referenced by brix_dig_handle(), brix_handle_dirlist(), brix_handle_fattr(), brix_handle_mkdir(), brix_handle_mv(), brix_handle_open(), brix_handle_setattr(), brix_handle_stat(), brix_handle_statx(), brix_handle_truncate(), brix_integrity_invalidate_path(), brix_open_probe(), brix_query_cksum_path(), brix_query_xattr(), brix_zip_http_serve(), cvmfs_tier_get(), fattr_recurse_dir(), op_path_probe(), op_vfs_ctx(), propfind_dir_ctx(), propfind_entry(), s3_build_vfs_ctx(), s3_chunk_finalize(), s3_cksum_vfs_open(), s3_cksum_vfs_unlink(), s3_commit_put(), s3_copy_vfs_ctx(), s3_delete_one(), s3_entry_fill_stat(), s3_put_aio_done(), s3_put_precondition(), s3_tag_vfs_ctx(), s3_user_meta_vfs_ctx(), s3_vfs_ctx(), s3_walk(), s3_walk_classify(), tape_residency(), vfs_browse_ctx(), webdav_copy_probe(), webdav_dead_prop_vfs_ctx_init(), webdav_handle_copy(), webdav_handle_get(), webdav_handle_head(), webdav_lock_sweep_remove(), webdav_lock_vfs_ctx(), webdav_lock_vfs_ctx_init(), webdav_move_probe(), webdav_ns_vfs_ctx_init(), webdav_put_body_inner(), webdav_put_vfs_ctx_init(), webdav_search_walk(), and webdav_tpc_probe().
brix_vfs_export_relative()
const char * brix_vfs_export_relative (const brix_vfs_ctx_t * ctx, const char * path)
Definition at line 226 of file vfs_open.c.
References brix_vfs_export_relative_root(), and brix_vfs_ctx_t::root_canon.
Referenced by brix_vfs_chmod(), brix_vfs_copy(), brix_vfs_delete(), brix_vfs_getxattr(), brix_vfs_listxattr(), brix_vfs_mkdir(), brix_vfs_open(), brix_vfs_opendir_impl(), brix_vfs_probe(), brix_vfs_removexattr(), brix_vfs_rename(), brix_vfs_residency(), brix_vfs_setattr(), brix_vfs_setxattr(), brix_vfs_staged_open(), brix_vfs_stat_impl(), cvmfs_tier_get(), s3_handle_get(), and webdav_handle_get().
brix_vfs_export_relative_root()
const char * brix_vfs_export_relative_root (const char * path, const char * root_canon)
Definition at line 205 of file vfs_open.c.
Referenced by brix_cache_fill_composed_thread(), brix_handle_open(), brix_open_read_probe(), brix_open_resolved_file(), brix_vfs_export_relative(), brix_vfs_mkdir_parent_path(), and brix_vfs_rename_path().
brix_vfs_file_backend_name()
const char * brix_vfs_file_backend_name (const brix_vfs_file_t * fh)
Definition at line 632 of file vfs_open.c.
References brix_sd_backend_name().
Referenced by brix_http_serve_file_ranged().
brix_vfs_file_can_sendfile()
ngx_uint_t brix_vfs_file_can_sendfile (const brix_vfs_file_t * fh)
Definition at line 622 of file vfs_open.c.
References brix_vfs_file_sendfile_fd().
brix_vfs_file_fd()
ngx_fd_t brix_vfs_file_fd (const brix_vfs_file_t * fh)
Definition at line 579 of file vfs_open.c.
Referenced by brix_http_serve_file_ranged(), brix_query_cksum_path(), brix_zip_http_serve(), s3_handle_get(), s3_handle_head(), s3_handle_upload_part_copy(), s3_put_checksum_apply(), s3_put_trailer_checksum_apply(), and webdav_handle_head().
brix_vfs_file_from_cache()
ngx_uint_t brix_vfs_file_from_cache (const brix_vfs_file_t * fh)
Definition at line 659 of file vfs_open.c.
Referenced by brix_http_serve_file_ranged(), and webdav_handle_get().
brix_vfs_file_mtime()
time_t brix_vfs_file_mtime (const brix_vfs_file_t * fh)
Definition at line 653 of file vfs_open.c.
brix_vfs_file_path()
const char * brix_vfs_file_path (const brix_vfs_file_t * fh)
Definition at line 641 of file vfs_open.c.
Referenced by brix_http_serve_file_ranged(), and webdav_handle_get().
brix_vfs_file_pread()
ssize_t brix_vfs_file_pread (brix_vfs_file_t * fh, void * buf, size_t len, off_t off)
Definition at line 595 of file vfs_open.c.
Referenced by brix_serve_memory_backed().
brix_vfs_file_sd_obj()
void brix_vfs_file_sd_obj (const brix_vfs_file_t * fh, brix_sd_obj_t * out)
Definition at line 585 of file vfs_open.c.
References brix_vfs_handle_sd_obj().
Referenced by brix_query_cksum_path().
brix_vfs_file_sendfile_fd()
ngx_fd_t brix_vfs_file_sendfile_fd (const brix_vfs_file_t * fh)
Definition at line 612 of file vfs_open.c.
References brix_vfs_handle_sendfile_fd().
Referenced by brix_dig_handle(), brix_http_serve_file_ranged(), brix_vfs_file_can_sendfile(), and webdav_handle_get().
brix_vfs_file_size()
off_t brix_vfs_file_size (const brix_vfs_file_t * fh)
Definition at line 647 of file vfs_open.c.
brix_vfs_file_stat()
ngx_int_t brix_vfs_file_stat (const brix_vfs_file_t * fh, brix_vfs_stat_t * stat_out)
Definition at line 665 of file vfs_open.c.
References brix_vfs_handle_sd_obj(), brix_vfs_sd_stat_to_vfs(), brix_vfs_stat_t::ctime, brix_vfs_stat_t::ino, brix_vfs_stat_t::is_directory, brix_vfs_stat_t::is_regular, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, and brix_vfs_stat_t::size.
Referenced by brix_dig_handle(), cvmfs_tier_get(), ngx_http_brix_dashboard_vfs_download_handler(), s3_handle_get(), and webdav_handle_get().
brix_vfs_fill_stat()
void brix_vfs_fill_stat (const struct stat * st, brix_vfs_stat_t * out)
Definition at line 76 of file vfs_open.c.
References brix_vfs_stat_t::atime, brix_vfs_stat_t::blocks, brix_vfs_stat_t::ctime, brix_vfs_stat_t::dev, brix_vfs_stat_t::gid, brix_vfs_stat_t::ino, brix_vfs_stat_t::is_directory, brix_vfs_stat_t::is_regular, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, brix_vfs_stat_t::size, and brix_vfs_stat_t::uid.
Referenced by brix_vfs_probe(), brix_vfs_readdir(), brix_vfs_stat_impl(), and vfs_walk_emit_file().
brix_vfs_mkdir_parent_path()
static ngx_int_t brix_vfs_mkdir_parent_path (brix_vfs_ctx_t * ctx, const char * path) static
Definition at line 333 of file vfs_open.c.
References brix_mkdir_recursive_confined_canon(), brix_vfs_backend_mkpath(), brix_vfs_copy_path(), brix_vfs_export_relative_root(), brix_vfs_ctx_t::log, brix_vfs_ctx_t::pool, and brix_vfs_ctx_t::root_canon.
Referenced by brix_vfs_open().
brix_vfs_open()
brix_vfs_file_t * brix_vfs_open (brix_vfs_ctx_t * ctx, ngx_uint_t flags, int * err_out)
Definition at line 375 of file vfs_open.c.
References brix_vfs_ctx_t::allow_write, brix_cache_open(), brix_metric_cache_result(), brix_open_beneath(), brix_open_confined_canon(), brix_sd_default_driver(), brix_sd_posix_borrow_instance(), brix_vfs_adopt_fd(), brix_vfs_adopt_obj(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_metrics_proto(), brix_vfs_mkdir_parent_path(), BRIX_VFS_O_MKDIRPATH, BRIX_VFS_O_NOCACHE, BRIX_VFS_O_WRITE, brix_vfs_open_flags(), brix_vfs_require_confined(), brix_vfs_to_sd_flags(), brix_vfs_ctx_t::cache_enabled, brix_vfs_ctx_t::log, open(), brix_vfs_ctx_t::pool, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::rootfd, and brix_vfs_ctx_t::sd.
Referenced by brix_dig_handle(), brix_handle_truncate(), brix_query_cksum_path(), brix_zip_http_serve(), copy_block_to_remote(), copy_download(), copy_one_l2r(), copy_one_r2l(), copy_remote_to_block(), copy_upload(), copy_vfs_to_vfs(), copy_web_upload(), cvmfs_tier_get(), do_download(), do_upload(), ngx_http_brix_dashboard_vfs_download_handler(), s3_cksum_vfs_open(), s3_handle_get(), s3_handle_head(), s3_handle_upload_part_copy(), webdav_handle_get(), webdav_handle_head(), and webdav_handle_lock_inner().
brix_vfs_open_flags()
static int brix_vfs_open_flags (ngx_uint_t flags) static
Definition at line 280 of file vfs_open.c.
References BRIX_VFS_O_APPEND, BRIX_VFS_O_CREATE, BRIX_VFS_O_EXCL, BRIX_VFS_O_READ, BRIX_VFS_O_TRUNC, and BRIX_VFS_O_WRITE.
Referenced by brix_vfs_open().
brix_vfs_to_sd_flags()
static int brix_vfs_to_sd_flags (ngx_uint_t flags) static
Definition at line 312 of file vfs_open.c.
References BRIX_SD_O_APPEND, BRIX_SD_O_CREATE, BRIX_SD_O_EXCL, BRIX_SD_O_READ, BRIX_SD_O_TRUNC, BRIX_SD_O_WRITE, BRIX_VFS_O_APPEND, BRIX_VFS_O_CREATE, BRIX_VFS_O_EXCL, BRIX_VFS_O_READ, BRIX_VFS_O_TRUNC, and BRIX_VFS_O_WRITE.
Referenced by brix_vfs_open().