nginx-xrootd: src/fs/vfs/vfs_backend_config_s3.c File Reference
vfs_backend_config_s3.c File Reference
#include "vfs_backend_config_internal.h"
#include <string.h>
Functions
void brix_vfs_backend_config_s3 (const char *root_canon, const char *host, int port, int tls, const char *bucket)
static void brix_vfs_backend_set_xroot (brix_vfs_backend_entry_t *e, const char *host, int port, int tls, int family)
void brix_vfs_backend_config_xroot (const char *root_canon, const char *host, int port, int tls, int family)
static ngx_int_t vfs_parse_s3_port (ngx_conf_t *cf, const u_char *authority, size_t authority_len, vfs_origin_parse_t *out)
static ngx_int_t vfs_parse_s3_url (ngx_conf_t *cf, const ngx_str_t *sb, vfs_origin_parse_t *out)
ngx_int_t vfs_parse_s3_origin (ngx_conf_t *cf, const char *root_canon, const ngx_str_t *sb)
ngx_int_t vfs_parse_xroot_or_driver_origin (ngx_conf_t *cf, const char *root_canon, const ngx_str_t *sb, size_t block_size, int family)
Function Documentation
brix_vfs_backend_config_s3()
void brix_vfs_backend_config_s3 (const char * root_canon, const char * host, int port, int tls, const char * bucket)
Definition at line 33 of file vfs_backend_config_s3.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_entry_t::inst, ngx_memcpy, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_path, brix_vfs_backend_entry_t::origin_port, brix_vfs_backend_entry_t::origin_tls, and tls.
Referenced by vfs_parse_s3_origin().
brix_vfs_backend_config_xroot()
void brix_vfs_backend_config_xroot (const char * root_canon, const char * host, int port, int tls, int family)
Definition at line 72 of file vfs_backend_config_s3.c.
References brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_set_xroot(), and tls.
Referenced by vfs_parse_xroot_or_driver_origin().
brix_vfs_backend_set_xroot()
static void brix_vfs_backend_set_xroot (brix_vfs_backend_entry_t * e, const char * host, int port, int tls, int family) static
Definition at line 59 of file vfs_backend_config_s3.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_t::inst, ngx_memcpy, brix_vfs_backend_entry_t::origin_family, brix_vfs_backend_entry_t::origin_host, brix_vfs_backend_entry_t::origin_port, brix_vfs_backend_entry_t::origin_tls, and tls.
Referenced by brix_vfs_backend_config_xroot().
vfs_parse_s3_origin()
ngx_int_t vfs_parse_s3_origin (ngx_conf_t * cf, const char * root_canon, const ngx_str_t * sb)
Definition at line 176 of file vfs_backend_config_s3.c.
References vfs_origin_parse_t::base, vfs_origin_parse_t::base_cap, brix_vfs_backend_config_s3(), vfs_origin_parse_t::host, vfs_origin_parse_t::host_cap, vfs_origin_parse_t::port, and vfs_parse_s3_url().
Referenced by brix_vfs_backend_config_str().
vfs_parse_s3_port()
static ngx_int_t vfs_parse_s3_port (ngx_conf_t * cf, const u_char * authority, size_t authority_len, vfs_origin_parse_t * out) static
Definition at line 94 of file vfs_backend_config_s3.c.
References vfs_origin_parse_t::host_len, and vfs_origin_parse_t::port.
Referenced by vfs_parse_s3_url().
vfs_parse_s3_url()
static ngx_int_t vfs_parse_s3_url (ngx_conf_t * cf, const ngx_str_t * sb, vfs_origin_parse_t * out) static
Definition at line 132 of file vfs_backend_config_s3.c.
References vfs_origin_parse_t::base, vfs_origin_parse_t::base_cap, vfs_origin_parse_t::host, vfs_origin_parse_t::host_cap, vfs_origin_parse_t::host_len, ngx_memcpy, and vfs_parse_s3_port().
Referenced by vfs_parse_s3_origin().
vfs_parse_xroot_or_driver_origin()
ngx_int_t vfs_parse_xroot_or_driver_origin (ngx_conf_t * cf, const char * root_canon, const ngx_str_t * sb, size_t block_size, int family)
Definition at line 211 of file vfs_backend_config_s3.c.
References brix_vfs_backend_config(), brix_vfs_backend_config_xroot(), and ngx_memcpy.
Referenced by brix_vfs_backend_config_str().