nginx-xrootd: src/fs/vfs/vfs_unlink.c File Reference
vfs_unlink.c File Reference
#include "vfs_internal.h"
#include "fs/backend/cache/sd_cache.h"
#include "core/compat/fs_walk.h"
Functions
static ngx_int_t brix_vfs_driver_rmtree (brix_sd_instance_t *leaf, const brix_sd_driver_t *drv, const char *logical, const brix_sd_cred_t *cred, ngx_uint_t depth)
static ngx_int_t brix_vfs_delete_via_driver (brix_vfs_ctx_t *ctx, const brix_sd_driver_t *drv, unsigned recursive, unsigned require_empty_dir, const char *path, uint64_t start)
static ngx_int_t brix_vfs_delete_via_namespace (brix_vfs_ctx_t *ctx, unsigned recursive, unsigned require_empty_dir, const char *path, uint64_t start)
static ngx_int_t brix_vfs_delete (brix_vfs_ctx_t *ctx, unsigned recursive, unsigned require_empty_dir)
ngx_int_t brix_vfs_unlink (brix_vfs_ctx_t *ctx)
ngx_int_t brix_vfs_rmdir (brix_vfs_ctx_t *ctx, unsigned recursive)
Function Documentation
brix_vfs_delete()
static ngx_int_t brix_vfs_delete (brix_vfs_ctx_t * ctx, unsigned recursive, unsigned require_empty_dir) static
Definition at line 248 of file vfs_unlink.c.
References BRIX_METRIC_OP_DELETE, brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_delete_via_driver(), brix_vfs_delete_via_namespace(), brix_vfs_now_ns(), brix_vfs_observe_ctx_op(), brix_vfs_require_write(), and brix_vfs_ctx_t::root_canon.
Referenced by brix_vfs_rmdir(), and brix_vfs_unlink().
brix_vfs_delete_via_driver()
static ngx_int_t brix_vfs_delete_via_driver (brix_vfs_ctx_t * ctx, const brix_sd_driver_t * drv, unsigned recursive, unsigned require_empty_dir, const char * path, uint64_t start) static
Definition at line 123 of file vfs_unlink.c.
References BRIX_METRIC_OP_DELETE, brix_sd_cache_evict(), brix_sd_ucred_wipe(), brix_sd_unlink_maybe_cred(), brix_vfs_cred_gate_active(), brix_vfs_driver_rmtree(), brix_vfs_export_relative(), brix_vfs_ns_cred(), brix_vfs_ns_leaf(), brix_vfs_observe_ctx_op(), and brix_vfs_ctx_t::sd.
Referenced by brix_vfs_delete().
brix_vfs_delete_via_namespace()
static ngx_int_t brix_vfs_delete_via_namespace (brix_vfs_ctx_t * ctx, unsigned recursive, unsigned require_empty_dir, const char * path, uint64_t start) static
Definition at line 197 of file vfs_unlink.c.
References BRIX_METRIC_OP_DELETE, brix_ns_delete(), BRIX_NS_OK, brix_vfs_ctx_path(), brix_vfs_ns_status_errno(), brix_vfs_observe_ctx_op(), brix_vfs_ctx_t::log, brix_ns_delete_opts_t::recursive, brix_ns_delete_opts_t::require_directory, brix_ns_delete_opts_t::require_empty_dir, brix_vfs_ctx_t::root_canon, brix_ns_result_t::status, and brix_ns_result_t::sys_errno.
Referenced by brix_vfs_delete().
brix_vfs_driver_rmtree()
static ngx_int_t brix_vfs_driver_rmtree (brix_sd_instance_t * leaf, const brix_sd_driver_t * drv, const char * logical, const brix_sd_cred_t * cred, ngx_uint_t depth) static
Definition at line 43 of file vfs_unlink.c.
References BRIX_FS_TREE_MAX_DEPTH, brix_sd_opendir_maybe_cred(), brix_sd_stat_maybe_cred(), brix_sd_unlink_maybe_cred(), brix_vfs_driver_rmtree(), brix_sd_stat_t::is_dir, brix_sd_dirent_t::name, and PATH_MAX.
Referenced by brix_vfs_delete_via_driver(), and brix_vfs_driver_rmtree().
brix_vfs_rmdir()
ngx_int_t brix_vfs_rmdir (brix_vfs_ctx_t * ctx, unsigned recursive)
Definition at line 298 of file vfs_unlink.c.
References brix_vfs_delete().
Referenced by brix_ftp_ev_cmd_rmd(), exec_rmdir(), and webdav_handle_delete().
brix_vfs_unlink()
ngx_int_t brix_vfs_unlink (brix_vfs_ctx_t * ctx)
Definition at line 291 of file vfs_unlink.c.
References brix_vfs_delete().
Referenced by brix_ftp_ev_cmd_dele(), brix_vfs_writer_commit_ex(), ev_eb_child_done(), exec_rm(), s3_cksum_vfs_unlink(), s3_delete_one(), s3_handle_delete(), webdav_handle_delete(), and webdav_lock_reap_null().