nginx-xrootd: src/fs/vfs/vfs_io_core.c File Reference
vfs_io_core.c File Reference
#include "vfs_internal.h"
#include "vfs_io_core.h"
#include "fs/backend/sd.h"
#include "fs/core/vfs_core.h"
#include "fs/backend/csi_tagstore.h"
#include "core/aio/aio.h"
#include "protocols/root/dirlist/dcksm.h"
#include "fs/path/path.h"
#include "protocols/root/protocol/dirlist_fmt.h"
#include "protocols/root/read/read.h"
#include "protocols/root/response/response.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include <openssl/evp.h>
Macros
#define BRIX_VFS_DIRLIST_CHUNK_CAP 65536UL
Functions
static void brix_vfs_io_set_error_message (brix_vfs_job_t *job, const char *message)
static void brix_vfs_io_set_errno_message (brix_vfs_job_t *job, const char *prefix, int err)
static ngx_int_t brix_vfs_io_write_counted (brix_sd_obj_t *job_obj, ngx_fd_t fd, const u_char *buf, size_t len, off_t offset, ssize_t *written, unsigned *short_io)
static void brix_vfs_io_execute_read (brix_vfs_job_t *job)
static void brix_vfs_io_execute_write (brix_vfs_job_t *job)
static void brix_vfs_io_execute_pgread (brix_vfs_job_t *job)
static void brix_vfs_io_execute_readv (brix_vfs_job_t *job)
static void brix_vfs_io_execute_writev (brix_vfs_job_t *job)
static void brix_vfs_io_execute_sync (brix_vfs_job_t *job)
static void brix_vfs_io_execute_truncate (brix_vfs_job_t *job)
static void brix_vfs_io_dirlist_fail (brix_vfs_job_t *job, int err, const char *message)
static ngx_flag_t brix_vfs_io_dirlist_name_unsafe (const char *name)
static void brix_vfs_io_dirlist_flush_chunk (brix_vfs_job_t *job, u_char *out, size_t *base, size_t cdpos)
static ngx_int_t brix_vfs_io_dirlist_need_new_chunk (brix_vfs_job_t *job, u_char *out, size_t *base, u_char **cdata, size_t *cdpos, size_t need)
static ngx_int_t brix_vfs_io_dirlist_stat_entry (brix_vfs_job_t *job, int dfd, const char *name, char *statbuf, size_t statbuf_cap, char *cksum_token, size_t cksum_token_cap, size_t *need)
static void brix_vfs_io_dirlist_emit_entry (brix_vfs_job_t *job, u_char *cdata, size_t *cdpos, const char *name, size_t nlen, const char *statbuf, const char *cksum_token)
static void brix_vfs_io_execute_opendir (brix_vfs_job_t *job)
static void brix_vfs_io_reset_outputs (brix_vfs_job_t *job)
static void brix_vfs_io_account (const brix_vfs_job_t *job)
void brix_vfs_io_execute (brix_vfs_job_t *job)
Macro Definition Documentation
BRIX_VFS_DIRLIST_CHUNK_CAP
#define BRIX_VFS_DIRLIST_CHUNK_CAP 65536UL
Definition at line 47 of file vfs_io_core.c.
Function Documentation
brix_vfs_io_account()
static void brix_vfs_io_account (const brix_vfs_job_t * job) static
Definition at line 693 of file vfs_io_core.c.
References brix_metric_backend_bytes(), BRIX_METRIC_OP_READ, BRIX_METRIC_OP_WRITE, BRIX_VFS_IO_PGREAD, BRIX_VFS_IO_READ, BRIX_VFS_IO_READV, BRIX_VFS_IO_WRITE, BRIX_VFS_IO_WRITEV, brix_vfs_job_t::nio, brix_vfs_job_t::obj, and brix_vfs_job_t::op.
Referenced by brix_vfs_io_execute().
brix_vfs_io_dirlist_emit_entry()
static void brix_vfs_io_dirlist_emit_entry (brix_vfs_job_t * job, u_char * cdata, size_t * cdpos, const char * name, size_t nlen, const char * statbuf, const char * cksum_token) static
Definition at line 528 of file vfs_io_core.c.
References BRIX_VFS_DIRLIST_CHUNK_CAP, name, ngx_memcpy, brix_vfs_job_t::want_cksum, and brix_vfs_job_t::want_stat.
Referenced by brix_vfs_io_execute_opendir().
brix_vfs_io_dirlist_fail()
static void brix_vfs_io_dirlist_fail (brix_vfs_job_t * job, int err, const char * message) static
Definition at line 397 of file vfs_io_core.c.
References brix_vfs_io_set_error_message(), brix_vfs_job_t::io_errno, and brix_vfs_job_t::nio.
Referenced by brix_vfs_io_dirlist_need_new_chunk(), and brix_vfs_io_execute_opendir().
brix_vfs_io_dirlist_flush_chunk()
static void brix_vfs_io_dirlist_flush_chunk (brix_vfs_job_t * job, u_char * out, size_t * base, size_t cdpos) static
Definition at line 438 of file vfs_io_core.c.
References brix_build_resp_hdr(), kXR_oksofar, brix_vfs_job_t::streamid, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_vfs_io_dirlist_need_new_chunk().
brix_vfs_io_dirlist_name_unsafe()
static ngx_flag_t brix_vfs_io_dirlist_name_unsafe (const char * name) static
Definition at line 410 of file vfs_io_core.c.
References name.
Referenced by brix_vfs_io_execute_opendir().
brix_vfs_io_dirlist_need_new_chunk()
static ngx_int_t brix_vfs_io_dirlist_need_new_chunk (brix_vfs_job_t * job, u_char * out, size_t * base, u_char ** cdata, size_t * cdpos, size_t need) static
Definition at line 450 of file vfs_io_core.c.
References BRIX_VFS_DIRLIST_CHUNK_CAP, brix_vfs_io_dirlist_fail(), brix_vfs_io_dirlist_flush_chunk(), brix_vfs_job_t::buf_cap, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_vfs_io_execute_opendir().
brix_vfs_io_dirlist_stat_entry()
static ngx_int_t brix_vfs_io_dirlist_stat_entry (brix_vfs_job_t * job, int dfd, const char * name, char * statbuf, size_t statbuf_cap, char * cksum_token, size_t cksum_token_cap, size_t * need) static
Definition at line 479 of file vfs_io_core.c.
References brix_dirlist_checksum_token(), brix_dirlist_make_dcksm_stat_body(), brix_make_stat_body(), brix_vfs_job_t::cksum_algo, fstatat(), brix_vfs_job_t::log, name, brix_vfs_job_t::path, PATH_MAX, stat(), brix_vfs_job_t::want_cksum, and brix_vfs_job_t::want_stat.
Referenced by brix_vfs_io_execute_opendir().
brix_vfs_io_execute()
void brix_vfs_io_execute (brix_vfs_job_t * job)
Definition at line 726 of file vfs_io_core.c.
References brix_vfs_io_account(), brix_vfs_io_execute_opendir(), brix_vfs_io_execute_pgread(), brix_vfs_io_execute_read(), brix_vfs_io_execute_readv(), brix_vfs_io_execute_sync(), brix_vfs_io_execute_truncate(), brix_vfs_io_execute_write(), brix_vfs_io_execute_writev(), BRIX_VFS_IO_OPENDIR, BRIX_VFS_IO_PGREAD, BRIX_VFS_IO_READ, BRIX_VFS_IO_READV, brix_vfs_io_reset_outputs(), BRIX_VFS_IO_SYNC, BRIX_VFS_IO_TRUNCATE, BRIX_VFS_IO_WRITE, BRIX_VFS_IO_WRITEV, brix_vfs_job_t::io_errno, brix_vfs_job_t::nio, and brix_vfs_job_t::op.
Referenced by brix_compressed_read_window(), brix_dirlist_aio_thread(), brix_handle_sync(), brix_handle_truncate(), brix_handle_write(), brix_pgread_aio_thread(), brix_pgread_sync_fill(), brix_read_aio_thread(), brix_read_window_pump(), brix_readv_aio_thread(), brix_readv_execute_sync(), brix_vfs_sync(), brix_vfs_truncate(), brix_wcmp_flush_window(), brix_write_aio_thread(), brix_writev_write_aio_thread(), ckp_recover_one(), ckp_rollback(), ckp_xeq_truncate(), ckp_xeq_vfs_write_full(), pgwrite_execute_sync(), read_sync_fill(), tpc_stream_sync_dst(), tpc_stream_write_frame(), writev_sync_handles(), and writev_write_segment().
brix_vfs_io_execute_opendir()
static void brix_vfs_io_execute_opendir (brix_vfs_job_t * job) static
Definition at line 564 of file vfs_io_core.c.
References brix_build_resp_hdr(), BRIX_DSTAT_LEADIN, BRIX_DSTAT_LEADIN_LEN, BRIX_VFS_DIRLIST_CHUNK_CAP, brix_vfs_io_dirlist_emit_entry(), brix_vfs_io_dirlist_fail(), brix_vfs_io_dirlist_name_unsafe(), brix_vfs_io_dirlist_need_new_chunk(), brix_vfs_io_dirlist_stat_entry(), brix_vfs_job_t::buf, brix_vfs_job_t::buf_cap, close(), kXR_ok, name, ngx_memcpy, brix_vfs_job_t::nio, brix_vfs_job_t::out_size, brix_vfs_job_t::rootfd, brix_vfs_job_t::streamid, brix_vfs_job_t::want_stat, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_vfs_io_execute().
brix_vfs_io_execute_pgread()
static void brix_vfs_io_execute_pgread (brix_vfs_job_t * job) static
Definition at line 211 of file vfs_io_core.c.
References brix_pgread_read_encode_inplace(), brix_vfs_effective_obj(), brix_vfs_job_t::buf, brix_vfs_job_t::buf_cap, brix_vfs_job_t::fd, brix_vfs_job_t::io_errno, brix_pgread_io_t::io_errno, brix_vfs_job_t::length, brix_vfs_job_t::nio, brix_pgread_io_t::nowait, brix_pgread_io_t::nread, brix_vfs_job_t::obj, brix_vfs_job_t::offset, and brix_vfs_job_t::out_size.
Referenced by brix_vfs_io_execute().
brix_vfs_io_execute_read()
static void brix_vfs_io_execute_read (brix_vfs_job_t * job) static
Definition at line 113 of file vfs_io_core.c.
References brix_crc32c_value(), BRIX_CSI_MISMATCH, brix_csi_verify_read(), brix_vfs_effective_obj(), brix_vfs_job_t::buf, brix_vfs_job_t::buf_cap, brix_vfs_job_t::crc32c, brix_vfs_job_t::csi, brix_vfs_job_t::csi_mismatch, brix_vfs_job_t::fd, brix_vfs_job_t::io_errno, brix_vfs_job_t::length, brix_vfs_job_t::nio, brix_vfs_job_t::obj, brix_vfs_job_t::offset, brix_vfs_job_t::out_size, brix_vfs_job_t::want_pgcrc, and xvfs_pread_full().
Referenced by brix_vfs_io_execute().
brix_vfs_io_execute_readv()
static void brix_vfs_io_execute_readv (brix_vfs_job_t * job) static
Definition at line 244 of file vfs_io_core.c.
References brix_readv_read_segments(), BRIX_READV_SEGSIZE, brix_vfs_io_set_error_message(), brix_vfs_job_t::err_msg, brix_vfs_job_t::err_msg_cap, brix_vfs_job_t::io_errno, brix_vfs_job_t::nio, brix_vfs_job_t::nsegs, brix_vfs_job_t::out_size, and brix_vfs_job_t::segs.
Referenced by brix_vfs_io_execute().
brix_vfs_io_execute_sync()
static void brix_vfs_io_execute_sync (brix_vfs_job_t * job) static
Definition at line 345 of file vfs_io_core.c.
References brix_vfs_effective_obj(), brix_vfs_job_t::fd, brix_vfs_job_t::io_errno, brix_vfs_job_t::nio, brix_vfs_job_t::obj, and xvfs_fsync().
Referenced by brix_vfs_io_execute().
brix_vfs_io_execute_truncate()
static void brix_vfs_io_execute_truncate (brix_vfs_job_t * job) static
Definition at line 369 of file vfs_io_core.c.
References brix_vfs_effective_obj(), brix_vfs_job_t::fd, brix_vfs_job_t::io_errno, brix_vfs_job_t::nio, brix_vfs_job_t::obj, brix_vfs_job_t::offset, and xvfs_ftruncate().
Referenced by brix_vfs_io_execute().
brix_vfs_io_execute_write()
static void brix_vfs_io_execute_write (brix_vfs_job_t * job) static
Definition at line 165 of file vfs_io_core.c.
References brix_csi_write_update(), brix_vfs_io_write_counted(), brix_vfs_job_t::buf, brix_vfs_job_t::csi, brix_vfs_job_t::fd, brix_vfs_job_t::io_errno, brix_vfs_job_t::length, brix_vfs_job_t::nio, brix_vfs_job_t::obj, brix_vfs_job_t::offset, brix_vfs_job_t::out_size, and brix_vfs_job_t::short_io.
Referenced by brix_vfs_io_execute().
brix_vfs_io_execute_writev()
static void brix_vfs_io_execute_writev (brix_vfs_job_t * job) static
Definition at line 279 of file vfs_io_core.c.
References brix_vfs_io_set_errno_message(), brix_vfs_io_set_error_message(), brix_vfs_io_write_counted(), brix_vfs_writev_seg_t::data, brix_vfs_job_t::do_sync, brix_vfs_job_t::err_msg, brix_vfs_job_t::err_msg_cap, brix_vfs_writev_seg_t::fd, brix_vfs_job_t::io_errno, brix_vfs_job_t::nio, brix_vfs_job_t::nsegs, brix_vfs_writev_seg_t::obj, brix_vfs_writev_seg_t::offset, brix_vfs_job_t::out_size, brix_vfs_job_t::segs, brix_vfs_job_t::short_io, and brix_vfs_writev_seg_t::wlen.
Referenced by brix_vfs_io_execute().
brix_vfs_io_reset_outputs()
static void brix_vfs_io_reset_outputs (brix_vfs_job_t * job) static
Definition at line 675 of file vfs_io_core.c.
References brix_vfs_job_t::crc32c, brix_vfs_job_t::err_msg, brix_vfs_job_t::err_msg_cap, brix_vfs_job_t::io_errno, brix_vfs_job_t::nio, brix_vfs_job_t::out_size, and brix_vfs_job_t::short_io.
Referenced by brix_vfs_io_execute().
brix_vfs_io_set_errno_message()
static void brix_vfs_io_set_errno_message (brix_vfs_job_t * job, const char * prefix, int err) static
Definition at line 66 of file vfs_io_core.c.
References brix_vfs_job_t::err_msg, and brix_vfs_job_t::err_msg_cap.
Referenced by brix_vfs_io_execute_writev().
brix_vfs_io_set_error_message()
static void brix_vfs_io_set_error_message (brix_vfs_job_t * job, const char * message) static
Definition at line 53 of file vfs_io_core.c.
References brix_vfs_job_t::err_msg, and brix_vfs_job_t::err_msg_cap.
Referenced by brix_vfs_io_dirlist_fail(), brix_vfs_io_execute_readv(), and brix_vfs_io_execute_writev().
brix_vfs_io_write_counted()
static ngx_int_t brix_vfs_io_write_counted (brix_sd_obj_t * job_obj, ngx_fd_t fd, const u_char * buf, size_t len, off_t offset, ssize_t * written, unsigned * short_io) static
Definition at line 82 of file vfs_io_core.c.
References brix_vfs_effective_obj(), and xvfs_pwrite_full().
Referenced by brix_vfs_io_execute_write(), and brix_vfs_io_execute_writev().