nginx-xrootd: src/fs/vfs/vfs_walk_copy.c File Reference
vfs_walk_copy.c File Reference
#include "vfs_internal.h"
#include "fs/path/path.h"
#include "core/compat/fs_walk.h"
#include "core/compat/copy_range.h"
#include "core/compat/namespace_ops.h"
#include <dirent.h>
Data Structures
struct vfs_copy_ctx_t
Functions
ngx_int_t brix_vfs_copyfile (ngx_log_t *log, const char *root_canon, const char *src, const char *dst, int preserve_xattrs, brix_vfs_copy_meta_cb meta_cb, void *cookie)
static ngx_int_t vfs_copytree_run (const vfs_copy_ctx_t *ctx, const char *src, const char *dst, ngx_uint_t depth)
static ngx_int_t vfs_copytree_subdir (const vfs_copy_ctx_t *ctx, const char *src_child, const char *dst_child, mode_t mode, ngx_uint_t depth)
static ngx_int_t vfs_copytree_entry (const vfs_copy_ctx_t *ctx, const char *src, const char *dst, const struct dirent *de, ngx_uint_t depth)
ngx_int_t brix_vfs_copytree (ngx_log_t *log, const char *root_canon, const char *src, const char *dst, int preserve_xattrs, brix_vfs_copy_meta_cb meta_cb, void *cookie)
Function Documentation
brix_vfs_copyfile()
ngx_int_t brix_vfs_copyfile (ngx_log_t * log, const char * root_canon, const char * src, const char * dst, int preserve_xattrs, brix_vfs_copy_meta_cb meta_cb, void * cookie)
Definition at line 33 of file vfs_walk_copy.c.
References brix_copy_range(), brix_lstat_confined_canon(), brix_ns_copy_fattrs(), brix_open_confined_canon(), log, and stat().
Referenced by vfs_copytree_entry(), and webdav_copy_file().
brix_vfs_copytree()
ngx_int_t brix_vfs_copytree (ngx_log_t * log, const char * root_canon, const char * src, const char * dst, int preserve_xattrs, brix_vfs_copy_meta_cb meta_cb, void * cookie)
Definition at line 218 of file vfs_walk_copy.c.
References log, and vfs_copytree_run().
Referenced by webdav_copy_dir_recursive().
vfs_copytree_entry()
static ngx_int_t vfs_copytree_entry (const vfs_copy_ctx_t * ctx, const char * src, const char * dst, const struct dirent * de, ngx_uint_t depth) static
Definition at line 144 of file vfs_walk_copy.c.
References brix_fs_is_dot_entry(), brix_lstat_confined_canon(), BRIX_MAX_PATH, brix_vfs_copyfile(), vfs_copy_ctx_t::cookie, vfs_copy_ctx_t::log, vfs_copy_ctx_t::meta_cb, vfs_copy_ctx_t::preserve_xattrs, vfs_copy_ctx_t::root_canon, stat(), and vfs_copytree_subdir().
Referenced by vfs_copytree_run().
vfs_copytree_run()
static ngx_int_t vfs_copytree_run (const vfs_copy_ctx_t * ctx, const char * src, const char * dst, ngx_uint_t depth) static
Definition at line 181 of file vfs_walk_copy.c.
References BRIX_FS_TREE_MAX_DEPTH, brix_opendir_confined_canon(), vfs_copy_ctx_t::log, vfs_copy_ctx_t::root_canon, and vfs_copytree_entry().
Referenced by brix_vfs_copytree(), and vfs_copytree_subdir().
vfs_copytree_subdir()
static ngx_int_t vfs_copytree_subdir (const vfs_copy_ctx_t * ctx, const char * src_child, const char * dst_child, mode_t mode, ngx_uint_t depth) static
Definition at line 117 of file vfs_walk_copy.c.
References brix_mkdir_confined_canon(), brix_ns_copy_fattrs(), vfs_copy_ctx_t::cookie, vfs_copy_ctx_t::log, vfs_copy_ctx_t::meta_cb, vfs_copy_ctx_t::preserve_xattrs, vfs_copy_ctx_t::root_canon, and vfs_copytree_run().
Referenced by vfs_copytree_entry().