nginx-xrootd: src/fs/vfs/vfs_internal.h File Reference
vfs_internal.h File Reference
#include "vfs.h"
#include "fs/backend/ucred.h"
#include "auth/token/exchange.h"
#include "auth/s3/sts.h"
#include "core/compat/crc32c.h"
#include "core/compat/namespace_ops.h"
#include "core/compat/staged_file.h"
#include "observability/metrics/access_log.h"
#include "fs/path/path.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct brix_deleg_live_t
struct brix_vfs_file_t
struct brix_vfs_dir_t
struct brix_vfs_staged_t
Functions
const char * brix_vfs_export_relative (const brix_vfs_ctx_t *ctx, const char *path)
const char * brix_vfs_export_relative_root (const char *path, const char *root_canon)
static const brix_sd_driver_t * brix_vfs_ctx_driver (const brix_vfs_ctx_t *ctx)
static void brix_vfs_sd_stat_fill (const brix_sd_stat_t *in, brix_vfs_stat_t *out)
static void brix_vfs_ctx_sd_obj (const brix_vfs_ctx_t *ctx, ngx_fd_t fd, brix_sd_obj_t *obj)
static void brix_vfs_handle_sd_obj (const brix_vfs_file_t *fh, brix_sd_obj_t *obj)
static void brix_vfs_sd_stat_to_vfs (const brix_sd_stat_t *in, brix_vfs_stat_t *out)
static ngx_fd_t brix_vfs_handle_sendfile_fd (const brix_vfs_file_t *fh, off_t off, size_t len, unsigned want_zerocopy)
static const char * brix_vfs_ctx_path (const brix_vfs_ctx_t *ctx)
static brix_vfs_ctx_t * brix_vfs_ctx_pool_clone (const brix_vfs_ctx_t *ctx, ngx_pool_t *pool)
static ngx_int_t brix_vfs_require_confined (const brix_vfs_ctx_t *ctx)
static ngx_int_t brix_vfs_require_write (const brix_vfs_ctx_t *ctx)
static int brix_vfs_ns_status_errno (brix_ns_status_t status)
static brix_proto_t brix_vfs_metrics_proto (const brix_vfs_ctx_t *ctx)
static uint64_t brix_vfs_now_ns (void)
static ngx_msec_t brix_vfs_elapsed_usec (uint64_t start_ns)
static void brix_vfs_observe_ctx_op (const brix_vfs_ctx_t *ctx, const char *path, brix_metric_op_t op, const brix_vfs_io_result_t *result, size_t bytes, ngx_int_t rc, int sys_errno, uint64_t start_ns)
static void brix_vfs_observe_file_op (const brix_vfs_file_t *fh, brix_metric_op_t op, const brix_vfs_io_result_t *result, size_t bytes, ngx_int_t rc, int sys_errno, uint64_t start_ns)
void brix_vfs_fill_stat (const struct stat *st, brix_vfs_stat_t *out)
char * brix_vfs_copy_path (ngx_pool_t *pool, const char *path)
ngx_int_t brix_vfs_adopt_fd (brix_vfs_ctx_t *ctx, const char *path, ngx_fd_t fd, brix_vfs_adopt_attrs_t attrs, brix_vfs_file_t **out)
ngx_int_t brix_vfs_backend_cred (brix_vfs_ctx_t *ctx, brix_sd_ucred_t *store, brix_sd_cred_t *cred, int *use_cred, int *err_out)
ngx_int_t brix_vfs_ns_cred (brix_vfs_ctx_t *ctx, brix_sd_ucred_t *store, brix_sd_cred_t *cred, int *use_cred, int *err_out)
brix_sd_instance_t * brix_vfs_ns_leaf (brix_sd_instance_t *top)
int brix_vfs_cred_gate_active (brix_vfs_ctx_t *ctx)
ngx_int_t brix_vfs_deleg_live_cred (brix_vfs_ctx_t *ctx, brix_sd_cred_t *cred, int *use_cred, int *err_out)
ngx_int_t brix_vfs_deleg_sts_cred (brix_vfs_ctx_t *ctx, const brix_s3_sts_conf_t *cf, brix_sd_cred_t *cred, int *use_cred, int *err_out)
ngx_int_t brix_vfs_deleg_krb5_token (brix_vfs_ctx_t *ctx, void *deleg_gss_cred, const char *origin_service_princ, ngx_str_t *out_token)
Function Documentation
brix_vfs_adopt_fd()
ngx_int_t brix_vfs_adopt_fd (brix_vfs_ctx_t * ctx, const char * path, ngx_fd_t fd, brix_vfs_adopt_attrs_t attrs, brix_vfs_file_t ** out)
Definition at line 121 of file vfs_open_adopt.c.
brix_vfs_backend_cred()
ngx_int_t brix_vfs_backend_cred (brix_vfs_ctx_t * ctx, brix_sd_ucred_t * store, brix_sd_cred_t * cred, int * use_cred, int * err_out)
Definition at line 430 of file vfs_cred.c.
References vfs_backend_cap_ok(), and vfs_backend_cred_decide().
Referenced by brix_open_read_probe(), brix_open_resolved_via_driver(), brix_vfs_open_via_driver(), and staged_open_driver().
brix_vfs_copy_path()
char * brix_vfs_copy_path (ngx_pool_t * pool, const char * path)
Definition at line 94 of file vfs_open_adopt.c.
References ngx_memcpy, and ngx_pnalloc().
Referenced by brix_vfs_adopt_fd(), brix_vfs_adopt_obj(), brix_vfs_mkdir_parent_path(), brix_vfs_opendir_impl(), and vfs_dir_open_driver().
brix_vfs_cred_gate_active()
int brix_vfs_cred_gate_active (brix_vfs_ctx_t * ctx)
Definition at line 459 of file vfs_cred.c.
References BRIX_CRED_SELECT, brix_sd_cred_accept(), BRIX_SD_CRED_IDENTITY, brix_vfs_backend_mode(), brix_vfs_ns_leaf(), brix_vfs_ctx_t::identity, brix_vfs_ctx_t::sd, and brix_vfs_ctx_t::storage_cred_dir.
Referenced by brix_vfs_chmod(), brix_vfs_copy_driver(), brix_vfs_delete_via_driver(), brix_vfs_getxattr(), brix_vfs_listxattr(), brix_vfs_probe(), brix_vfs_rename(), brix_vfs_setattr(), brix_vfs_stat_impl(), brix_vfs_xattr_write_gate(), vfs_dir_open_driver(), and vfs_mkdir_backend().
brix_vfs_ctx_driver()
static const brix_sd_driver_t * brix_vfs_ctx_driver (const brix_vfs_ctx_t * ctx) inline static
Definition at line 161 of file vfs_internal.h.
References brix_sd_default_driver(), and brix_vfs_ctx_t::sd.
Referenced by brix_vfs_chmod(), brix_vfs_copy(), brix_vfs_copy_driver(), brix_vfs_delete(), brix_vfs_getxattr(), brix_vfs_listxattr(), brix_vfs_mkdir(), brix_vfs_probe(), brix_vfs_removexattr(), brix_vfs_rename(), brix_vfs_setattr(), brix_vfs_setxattr(), brix_vfs_stat_impl(), and vfs_dir_route().
brix_vfs_ctx_path()
static const char * brix_vfs_ctx_path (const brix_vfs_ctx_t * ctx) inline static
Definition at line 252 of file vfs_internal.h.
References brix_path_result_t::resolved, and brix_vfs_ctx_t::resolved.
Referenced by brix_cache_open(), brix_vfs_chmod(), brix_vfs_copy(), brix_vfs_ctx_pool_clone(), brix_vfs_delete(), brix_vfs_delete_via_namespace(), brix_vfs_getxattr(), brix_vfs_listxattr(), brix_vfs_mkdir(), brix_vfs_open(), brix_vfs_opendir_impl(), brix_vfs_probe(), brix_vfs_removexattr(), brix_vfs_rename(), brix_vfs_require_confined(), brix_vfs_residency(), brix_vfs_setattr(), brix_vfs_setxattr(), brix_vfs_staged_commit(), brix_vfs_staged_open(), brix_vfs_stat_impl(), and vfs_opendir_fail().
brix_vfs_ctx_pool_clone()
static brix_vfs_ctx_t * brix_vfs_ctx_pool_clone (const brix_vfs_ctx_t * ctx, ngx_pool_t * pool) inline static
Definition at line 271 of file vfs_internal.h.
References brix_vfs_ctx_path(), ngx_memcpy, ngx_pnalloc(), brix_path_result_t::resolved, brix_vfs_ctx_t::resolved, and brix_vfs_ctx_t::root_canon.
Referenced by brix_vfs_writer_open(), and staged_alloc_handle().
brix_vfs_ctx_sd_obj()
static void brix_vfs_ctx_sd_obj (const brix_vfs_ctx_t * ctx, ngx_fd_t fd, brix_sd_obj_t * obj) inline static
Definition at line 194 of file vfs_internal.h.
References brix_sd_default_driver(), and brix_vfs_ctx_t::sd.
Referenced by brix_vfs_adopt_fd(), and brix_vfs_handle_sd_obj().
brix_vfs_deleg_krb5_token()
ngx_int_t brix_vfs_deleg_krb5_token (brix_vfs_ctx_t * ctx, void * deleg_gss_cred, const char * origin_service_princ, ngx_str_t * out_token)
Definition at line 441 of file vfs_deleg.c.
References brix_krb5_deleg_to_origin(), brix_krb5_forward_available(), brix_vfs_ctx_t::log, and brix_vfs_ctx_t::pool.
brix_vfs_deleg_live_cred()
ngx_int_t brix_vfs_deleg_live_cred (brix_vfs_ctx_t * ctx, brix_sd_cred_t * cred, int * use_cred, int * err_out)
Definition at line 315 of file vfs_deleg.c.
References BRIX_CRED_EXCHANGE, brix_sd_cred_accept(), BRIX_SD_CRED_BEARER, BRIX_SD_CRED_PROXY_PEM, brix_vfs_deleg_bearer(), brix_vfs_deleg_deny(), brix_vfs_deleg_exchange(), brix_vfs_deleg_proxy(), brix_vfs_ns_leaf(), brix_vfs_ctx_t::deleg_live, and brix_vfs_ctx_t::sd.
Referenced by vfs_cred_live_bag().
brix_vfs_deleg_sts_cred()
ngx_int_t brix_vfs_deleg_sts_cred (brix_vfs_ctx_t * ctx, const brix_s3_sts_conf_t * cf, brix_sd_cred_t * cred, int * use_cred, int * err_out)
Definition at line 386 of file vfs_deleg.c.
References BRIX_CRED_EXCHANGE, brix_s3_sts_assume(), brix_vfs_deleg_deny(), brix_vfs_ctx_t::identity, brix_vfs_ctx_t::log, brix_sd_cred_t::mode, brix_vfs_ctx_t::pool, brix_s3_sts_conf_t::region, brix_sd_cred_t::s3_ak, brix_sd_cred_t::s3_region, and brix_sd_cred_t::s3_sk.
brix_vfs_elapsed_usec()
static ngx_msec_t brix_vfs_elapsed_usec (uint64_t start_ns) inline static
Definition at line 398 of file vfs_internal.h.
References brix_vfs_now_ns(), and now_ns().
Referenced by brix_vfs_observe_ctx_op().
brix_vfs_export_relative()
const char * brix_vfs_export_relative (const brix_vfs_ctx_t * ctx, const char * path)
Definition at line 223 of file vfs_open_adopt.c.
brix_vfs_export_relative_root()
const char * brix_vfs_export_relative_root (const char * path, const char * root_canon)
Definition at line 202 of file vfs_open_adopt.c.
Referenced by brix_cache_fill_composed_thread(), brix_open_dispatch_driver(), brix_open_read_probe(), brix_open_try_cache_offload(), brix_vfs_export_relative(), brix_vfs_mkdir_parent_path(), and brix_vfs_rename_path().
brix_vfs_fill_stat()
void brix_vfs_fill_stat (const struct stat * st, brix_vfs_stat_t * out)
Definition at line 72 of file vfs_open_adopt.c.
References brix_vfs_stat_t::atime, brix_vfs_stat_t::blocks, brix_vfs_stat_t::ctime, brix_vfs_stat_t::dev, brix_vfs_stat_t::gid, brix_vfs_stat_t::ino, brix_vfs_stat_t::is_directory, brix_vfs_stat_t::is_regular, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, brix_vfs_stat_t::size, and brix_vfs_stat_t::uid.
Referenced by brix_vfs_probe(), brix_vfs_stat_impl(), vfs_readdir_stat_child(), and vfs_walk_emit_file().
brix_vfs_handle_sd_obj()
static void brix_vfs_handle_sd_obj (const brix_vfs_file_t * fh, brix_sd_obj_t * obj) inline static
Definition at line 206 of file vfs_internal.h.
References brix_vfs_ctx_sd_obj().
Referenced by brix_vfs_file_sd_obj(), brix_vfs_file_stat(), brix_vfs_handle_sendfile_fd(), and brix_vfs_memfile_materialize().
brix_vfs_handle_sendfile_fd()
static ngx_fd_t brix_vfs_handle_sendfile_fd (const brix_vfs_file_t * fh, off_t off, size_t len, unsigned want_zerocopy) inline static
Definition at line 236 of file vfs_internal.h.
References brix_vfs_handle_sd_obj().
Referenced by brix_vfs_file_sendfile_fd().
brix_vfs_metrics_proto()
static brix_proto_t brix_vfs_metrics_proto (const brix_vfs_ctx_t * ctx) inline static
Definition at line 370 of file vfs_internal.h.
References BRIX_PROTO_COUNT, BRIX_PROTO_ROOT, and brix_vfs_ctx_t::metrics_proto.
Referenced by brix_vfs_observe_ctx_op(), brix_vfs_open_try_cache(), vfs_cred_deny_or_fallback(), vfs_cred_fill_user(), and vfs_cred_no_cap().
brix_vfs_now_ns()
static uint64_t brix_vfs_now_ns (void) inline static
Definition at line 387 of file vfs_internal.h.
Referenced by brix_vfs_copy(), brix_vfs_delete(), brix_vfs_elapsed_usec(), brix_vfs_fgetxattr(), brix_vfs_flistxattr(), brix_vfs_fremovexattr(), brix_vfs_fsetxattr(), brix_vfs_getxattr(), brix_vfs_listxattr(), brix_vfs_mkdir(), brix_vfs_opendir_impl(), brix_vfs_removexattr(), brix_vfs_rename(), brix_vfs_setxattr(), brix_vfs_staged_commit(), and brix_vfs_stat_impl().
brix_vfs_ns_cred()
ngx_int_t brix_vfs_ns_cred (brix_vfs_ctx_t * ctx, brix_sd_ucred_t * store, brix_sd_cred_t * cred, int * use_cred, int * err_out)
Definition at line 574 of file vfs_cred.c.
References vfs_backend_cred_decide(), and vfs_ns_cap_ok().
Referenced by brix_vfs_chmod(), brix_vfs_copy_driver(), brix_vfs_delete_via_driver(), brix_vfs_getxattr(), brix_vfs_listxattr(), brix_vfs_probe(), brix_vfs_rename(), brix_vfs_setattr(), brix_vfs_stat_impl(), brix_vfs_xattr_write_gate(), vfs_dir_open_driver(), and vfs_mkdir_backend().
brix_vfs_ns_leaf()
brix_sd_instance_t * brix_vfs_ns_leaf (brix_sd_instance_t * top)
Definition at line 497 of file vfs_cred.c.
References brix_sd_cache_source_instance(), and brix_sd_stage_source_instance().
Referenced by brix_open_read_probe(), brix_open_write_needs_staged(), brix_vfs_backend_accepts_proxy(), brix_vfs_chmod(), brix_vfs_copy_driver(), brix_vfs_cred_gate_active(), brix_vfs_deleg_live_cred(), brix_vfs_delete_via_driver(), brix_vfs_getxattr(), brix_vfs_listxattr(), brix_vfs_probe(), brix_vfs_removexattr(), brix_vfs_rename(), brix_vfs_setattr(), brix_vfs_setxattr(), brix_vfs_stat_impl(), s3put_ensure_parent_dirs(), vfs_backend_cap_ok(), vfs_backend_cred_decide(), vfs_dir_open_driver(), vfs_mkdir_backend(), and vfs_ns_cap_ok().
brix_vfs_ns_status_errno()
static int brix_vfs_ns_status_errno (brix_ns_status_t status) inline static
Definition at line 350 of file vfs_internal.h.
References BRIX_NS_CONFLICT, BRIX_NS_DENIED, BRIX_NS_EXISTS, BRIX_NS_IO_ERROR, BRIX_NS_NO_SPACE, BRIX_NS_NOT_EMPTY, BRIX_NS_NOT_FOUND, BRIX_NS_OK, and BRIX_NS_TOO_LONG.
Referenced by brix_vfs_copy_ns(), brix_vfs_delete_via_namespace(), brix_vfs_rename(), brix_vfs_rename_path(), and sd_posix_ns_result().
brix_vfs_observe_ctx_op()
static void brix_vfs_observe_ctx_op (const brix_vfs_ctx_t * ctx, const char * path, brix_metric_op_t op, const brix_vfs_io_result_t * result, size_t bytes, ngx_int_t rc, int sys_errno, uint64_t start_ns) inline static
Definition at line 415 of file vfs_internal.h.
References brix_access_log_emit(), BRIX_ERR_NONE, brix_metric_backend_bytes(), brix_metric_err_from_errno(), brix_metric_op_done(), brix_sd_backend_name(), brix_vfs_elapsed_usec(), brix_vfs_metrics_proto(), op, and brix_vfs_ctx_t::sd.
Referenced by brix_vfs_copy_driver(), brix_vfs_copy_fail(), brix_vfs_copy_ns(), brix_vfs_delete(), brix_vfs_delete_via_driver(), brix_vfs_delete_via_namespace(), brix_vfs_fremovexattr(), brix_vfs_fsetxattr(), brix_vfs_mkdir(), brix_vfs_observe_file_op(), brix_vfs_opendir_impl(), brix_vfs_rename(), brix_vfs_staged_commit(), brix_vfs_stat_impl(), brix_vfs_xattr_observe_count(), brix_vfs_xattr_observe_mut(), vfs_mkdir_backend(), and vfs_opendir_fail().
brix_vfs_observe_file_op()
static void brix_vfs_observe_file_op (const brix_vfs_file_t * fh, brix_metric_op_t op, const brix_vfs_io_result_t * result, size_t bytes, ngx_int_t rc, int sys_errno, uint64_t start_ns) inline static
Definition at line 446 of file vfs_internal.h.
References brix_vfs_observe_ctx_op(), and op.
brix_vfs_require_confined()
static ngx_int_t brix_vfs_require_confined (const brix_vfs_ctx_t * ctx) inline static
Definition at line 311 of file vfs_internal.h.
References brix_vfs_ctx_path(), brix_path_result_t::is_confined, and brix_vfs_ctx_t::resolved.
Referenced by brix_vfs_getxattr(), brix_vfs_listxattr(), brix_vfs_open_precheck(), brix_vfs_probe(), brix_vfs_removexattr(), brix_vfs_require_write(), brix_vfs_residency(), brix_vfs_setxattr(), brix_vfs_stat_impl(), and vfs_dir_route().
brix_vfs_require_write()
static ngx_int_t brix_vfs_require_write (const brix_vfs_ctx_t * ctx) inline static
Definition at line 329 of file vfs_internal.h.
References brix_vfs_ctx_t::allow_write, and brix_vfs_require_confined().
Referenced by brix_vfs_chmod(), brix_vfs_copy(), brix_vfs_delete(), brix_vfs_mkdir(), brix_vfs_rename(), brix_vfs_setattr(), and staged_alloc_handle().
brix_vfs_sd_stat_fill()
static void brix_vfs_sd_stat_fill (const brix_sd_stat_t * in, brix_vfs_stat_t * out) inline static
Definition at line 174 of file vfs_internal.h.
References brix_sd_stat_t::ctime, brix_vfs_stat_t::ctime, brix_sd_stat_t::gid, brix_vfs_stat_t::gid, brix_sd_stat_t::ino, brix_vfs_stat_t::ino, brix_sd_stat_t::is_dir, brix_vfs_stat_t::is_directory, brix_sd_stat_t::is_reg, brix_vfs_stat_t::is_regular, brix_sd_stat_t::mode, brix_vfs_stat_t::mode, brix_sd_stat_t::mtime, brix_vfs_stat_t::mtime, brix_sd_stat_t::size, brix_vfs_stat_t::size, brix_sd_stat_t::uid, and brix_vfs_stat_t::uid.
Referenced by brix_vfs_probe(), brix_vfs_stat_impl(), and vfs_readdir_sd().
brix_vfs_sd_stat_to_vfs()
static void brix_vfs_sd_stat_to_vfs (const brix_sd_stat_t * in, brix_vfs_stat_t * out) inline static
Definition at line 217 of file vfs_internal.h.
References brix_sd_stat_t::ctime, brix_vfs_stat_t::ctime, brix_sd_stat_t::gid, brix_vfs_stat_t::gid, brix_sd_stat_t::ino, brix_vfs_stat_t::ino, brix_sd_stat_t::is_dir, brix_vfs_stat_t::is_directory, brix_sd_stat_t::is_reg, brix_vfs_stat_t::is_regular, brix_sd_stat_t::mode, brix_vfs_stat_t::mode, brix_sd_stat_t::mtime, brix_vfs_stat_t::mtime, brix_sd_stat_t::size, brix_vfs_stat_t::size, brix_sd_stat_t::uid, and brix_vfs_stat_t::uid.
Referenced by brix_vfs_file_stat().