nginx-xrootd: src/fs/vfs/vfs_walk.c File Reference
vfs_walk.c File Reference
#include "vfs_internal.h"
#include "vfs_backend_registry.h"
#include "fs/path/beneath.h"
#include "fs/path/path.h"
#include "core/compat/fs_walk.h"
#include "core/compat/copy_range.h"
#include "core/compat/namespace_ops.h"
#include <dirent.h>
#include <limits.h>
Data Structures
struct vfs_walk_ctx_t
struct vfs_walk_step_t
struct vfs_copy_ctx_t
Functions
static int vfs_walk_join (const char *parent, const char *name, char *out, size_t outsz)
static ngx_int_t vfs_walk_emit_file (const vfs_walk_ctx_t *ctx, const char *logical, const struct stat *st, int soft_open_fail)
static ngx_int_t vfs_walk_dir (vfs_walk_ctx_t *ctx, const char *logical_dir, ngx_uint_t depth)
static DIR * vfs_walk_opendir (const vfs_walk_ctx_t *ctx, const char *logical_dir)
static vfs_walk_step_t vfs_walk_entry (vfs_walk_ctx_t *ctx, DIR *dh, const char *logical_dir, const struct dirent *de, ngx_uint_t depth)
ngx_int_t brix_vfs_walk (ngx_log_t *log, int rootfd, const char *logical, const brix_vfs_walk_opts_t *opts, brix_vfs_walk_file_cb cb, void *cookie, brix_vfs_walk_target_t *target_out, char *errmsg, size_t errsz)
int brix_vfs_open_fd (ngx_log_t *log, const char *root_canon, const char *logical, int flags, mode_t mode)
int brix_vfs_open_fd_at (int rootfd, const char *logical, int flags, mode_t mode)
int brix_vfs_unlink_path (ngx_log_t *log, const char *root_canon, const char *logical)
int brix_vfs_unlink_at (int rootfd, const char *logical, int is_dir)
int brix_vfs_mkdir_path (ngx_log_t *log, const char *root_canon, const char *logical, mode_t mode)
int brix_vfs_backend_mkpath (const char *root_canon, const char *logical, mode_t mode, ngx_log_t *log)
ngx_int_t brix_vfs_copyfile (ngx_log_t *log, const char *root_canon, const char *src, const char *dst, int preserve_xattrs, brix_vfs_copy_meta_cb meta_cb, void *cookie)
static ngx_int_t vfs_copytree_run (const vfs_copy_ctx_t *ctx, const char *src, const char *dst, ngx_uint_t depth)
static ngx_int_t vfs_copytree_subdir (const vfs_copy_ctx_t *ctx, const char *src_child, const char *dst_child, mode_t mode, ngx_uint_t depth)
static ngx_int_t vfs_copytree_entry (const vfs_copy_ctx_t *ctx, const char *src, const char *dst, const struct dirent *de, ngx_uint_t depth)
ngx_int_t brix_vfs_copytree (ngx_log_t *log, const char *root_canon, const char *src, const char *dst, int preserve_xattrs, brix_vfs_copy_meta_cb meta_cb, void *cookie)
Function Documentation
brix_vfs_backend_mkpath()
int brix_vfs_backend_mkpath (const char * root_canon, const char * logical, mode_t mode, ngx_log_t * log)
Definition at line 353 of file vfs_walk.c.
References brix_vfs_backend_resolve(), log, and PATH_MAX.
Referenced by brix_vfs_mkdir_parent_path(), cms_node_exec_driver(), mv_make_dst_parents(), and vfs_backend_mkdir_dispatch().
brix_vfs_copyfile()
ngx_int_t brix_vfs_copyfile (ngx_log_t * log, const char * root_canon, const char * src, const char * dst, int preserve_xattrs, brix_vfs_copy_meta_cb meta_cb, void * cookie)
Definition at line 400 of file vfs_walk.c.
References brix_copy_range(), brix_lstat_confined_canon(), brix_ns_copy_fattrs(), brix_open_confined_canon(), log, and stat().
Referenced by vfs_copytree_entry(), and webdav_copy_file().
brix_vfs_copytree()
ngx_int_t brix_vfs_copytree (ngx_log_t * log, const char * root_canon, const char * src, const char * dst, int preserve_xattrs, brix_vfs_copy_meta_cb meta_cb, void * cookie)
Definition at line 585 of file vfs_walk.c.
References log, and vfs_copytree_run().
Referenced by webdav_copy_dir_recursive().
brix_vfs_mkdir_path()
int brix_vfs_mkdir_path (ngx_log_t * log, const char * root_canon, const char * logical, mode_t mode)
Definition at line 337 of file vfs_walk.c.
References brix_mkdir_confined_canon(), and log.
Referenced by webdav_copy_collection_stage().
brix_vfs_open_fd()
int brix_vfs_open_fd (ngx_log_t * log, const char * root_canon, const char * logical, int flags, mode_t mode)
Definition at line 305 of file vfs_walk.c.
References brix_open_confined_canon(), and log.
Referenced by ckp_recover_one(), ckp_recover_open_dir(), s3_handle_upload_part_copy(), s3_mpu_assemble(), s3_put_try_sentinel(), tpc_core_open_local(), and webdav_put_persist_checksums().
brix_vfs_open_fd_at()
int brix_vfs_open_fd_at (int rootfd, const char * logical, int flags, mode_t mode)
Definition at line 315 of file vfs_walk.c.
References brix_open_beneath().
Referenced by brix_open_posix_dispatch(), brix_reopen_bound_read_handle(), cms_posix_apply(), tpc_open_dst_logical(), and zip_open_archive_fd().
brix_vfs_unlink_at()
int brix_vfs_unlink_at (int rootfd, const char * logical, int is_dir)
Definition at line 330 of file vfs_walk.c.
References brix_unlink_beneath().
Referenced by cms_posix_apply().
brix_vfs_unlink_path()
int brix_vfs_unlink_path (ngx_log_t * log, const char * root_canon, const char * logical)
Definition at line 322 of file vfs_walk.c.
References brix_unlink_confined_canon(), and log.
Referenced by ckp_recover_one(), fhandle_unlink_staging(), s3_handle_upload_part_copy(), s3_mpu_assemble(), tpc_done_sync_fail(), and tpc_done_teardown_dst().
brix_vfs_walk()
ngx_int_t brix_vfs_walk (ngx_log_t * log, int rootfd, const char * logical, const brix_vfs_walk_opts_t * opts, brix_vfs_walk_file_cb cb, void * cookie, brix_vfs_walk_target_t * target_out, char * errmsg, size_t errsz)
Definition at line 260 of file vfs_walk.c.
References brix_stat_beneath(), BRIX_VFS_WALK_DIR, BRIX_VFS_WALK_FILE, BRIX_VFS_WALK_NONE, BRIX_VFS_WALK_OTHER, log, stat(), vfs_walk_dir(), and vfs_walk_emit_file().
Referenced by brix_ckscan_run(), and brix_scan_run().
vfs_copytree_entry()
static ngx_int_t vfs_copytree_entry (const vfs_copy_ctx_t * ctx, const char * src, const char * dst, const struct dirent * de, ngx_uint_t depth) static
Definition at line 511 of file vfs_walk.c.
References brix_fs_is_dot_entry(), brix_lstat_confined_canon(), BRIX_MAX_PATH, brix_vfs_copyfile(), vfs_copy_ctx_t::cookie, vfs_copy_ctx_t::log, vfs_copy_ctx_t::meta_cb, vfs_copy_ctx_t::preserve_xattrs, vfs_copy_ctx_t::root_canon, stat(), and vfs_copytree_subdir().
Referenced by vfs_copytree_run().
vfs_copytree_run()
static ngx_int_t vfs_copytree_run (const vfs_copy_ctx_t * ctx, const char * src, const char * dst, ngx_uint_t depth) static
Definition at line 548 of file vfs_walk.c.
References BRIX_FS_TREE_MAX_DEPTH, brix_opendir_confined_canon(), vfs_copy_ctx_t::log, vfs_copy_ctx_t::root_canon, and vfs_copytree_entry().
Referenced by brix_vfs_copytree(), and vfs_copytree_subdir().
vfs_copytree_subdir()
static ngx_int_t vfs_copytree_subdir (const vfs_copy_ctx_t * ctx, const char * src_child, const char * dst_child, mode_t mode, ngx_uint_t depth) static
Definition at line 484 of file vfs_walk.c.
References brix_mkdir_confined_canon(), brix_ns_copy_fattrs(), vfs_copy_ctx_t::cookie, vfs_copy_ctx_t::log, vfs_copy_ctx_t::meta_cb, vfs_copy_ctx_t::preserve_xattrs, vfs_copy_ctx_t::root_canon, and vfs_copytree_run().
Referenced by vfs_copytree_entry().
vfs_walk_dir()
static ngx_int_t vfs_walk_dir (vfs_walk_ctx_t * ctx, const char * logical_dir, ngx_uint_t depth) static
Definition at line 224 of file vfs_walk.c.
References vfs_walk_step_t::code, brix_vfs_walk_opts_t::max_depth, vfs_walk_ctx_t::opts, vfs_walk_step_t::stop, vfs_walk_entry(), and vfs_walk_opendir().
Referenced by brix_vfs_walk(), and vfs_walk_entry().
vfs_walk_emit_file()
static ngx_int_t vfs_walk_emit_file (const vfs_walk_ctx_t * ctx, const char * logical, const struct stat * st, int soft_open_fail) static
Definition at line 95 of file vfs_walk.c.
References brix_open_beneath(), brix_vfs_fill_stat(), vfs_walk_ctx_t::cb, vfs_walk_ctx_t::cookie, brix_vfs_walk_opts_t::open_files, vfs_walk_ctx_t::opts, and vfs_walk_ctx_t::rootfd.
Referenced by brix_vfs_walk(), and vfs_walk_entry().
vfs_walk_entry()
static vfs_walk_step_t vfs_walk_entry (vfs_walk_ctx_t * ctx, DIR * dh, const char * logical_dir, const struct dirent * de, ngx_uint_t depth) static
Definition at line 166 of file vfs_walk.c.
References brix_fs_is_dot_entry(), BRIX_MAX_PATH, vfs_walk_step_t::code, fstatat(), brix_vfs_walk_opts_t::max_files, vfs_walk_ctx_t::nfiles, vfs_walk_ctx_t::opts, stat(), vfs_walk_step_t::stop, vfs_walk_dir(), vfs_walk_emit_file(), and vfs_walk_join().
Referenced by vfs_walk_dir().
vfs_walk_join()
static int vfs_walk_join (const char * parent, const char * name, char * out, size_t outsz) static
Definition at line 79 of file vfs_walk.c.
References name.
Referenced by vfs_walk_entry().
vfs_walk_opendir()
static DIR * vfs_walk_opendir (const vfs_walk_ctx_t * ctx, const char * logical_dir) static
Definition at line 128 of file vfs_walk.c.
References brix_open_beneath(), vfs_walk_ctx_t::errmsg, vfs_walk_ctx_t::errsz, and vfs_walk_ctx_t::rootfd.
Referenced by vfs_walk_dir().