nginx-xrootd: src/fs/vfs/vfs_open_handle.c File Reference
vfs_open_handle.c File Reference
#include "vfs_internal.h"
#include "vfs_backend_registry.h"
#include <sys/mman.h>
#include "core/compat/log_diag.h"
Functions
ngx_int_t brix_vfs_close (brix_vfs_file_t *fh, ngx_log_t *log)
ngx_fd_t brix_vfs_file_fd (const brix_vfs_file_t *fh)
void brix_vfs_file_sd_obj (const brix_vfs_file_t *fh, brix_sd_obj_t *out)
ssize_t brix_vfs_file_pread (brix_vfs_file_t *fh, void *buf, size_t len, off_t off)
ssize_t brix_vfs_file_pwrite (brix_vfs_file_t *fh, const void *buf, size_t len, off_t off)
static ngx_fd_t brix_vfs_memfile_materialize (brix_vfs_file_t *fh)
ngx_fd_t brix_vfs_file_sendfile_fd (const brix_vfs_file_t *fh)
ngx_uint_t brix_vfs_file_can_sendfile (const brix_vfs_file_t *fh)
const char * brix_vfs_file_backend_name (const brix_vfs_file_t *fh)
const char * brix_vfs_file_path (const brix_vfs_file_t *fh)
off_t brix_vfs_file_size (const brix_vfs_file_t *fh)
time_t brix_vfs_file_mtime (const brix_vfs_file_t *fh)
ngx_uint_t brix_vfs_file_from_cache (const brix_vfs_file_t *fh)
ngx_int_t brix_vfs_file_stat (const brix_vfs_file_t *fh, brix_vfs_stat_t *stat_out)
Function Documentation
brix_vfs_close()
ngx_int_t brix_vfs_close (brix_vfs_file_t * fh, ngx_log_t * log)
Definition at line 29 of file vfs_open_handle.c.
References BRIX_DIAG_ERR, and log.
Referenced by brix_cksum_aio_done(), brix_ftp_ev_cmd_cksm(), brix_ftp_ev_data_finish(), brix_handle_truncate(), brix_http_serve_file_ranged(), brix_qcksum_compute_sync(), brix_qcksum_try_async(), brix_vfs_writer_commit_ex(), brix_zip_http_serve(), copy_block_to_remote(), copy_one_l2r(), copy_one_r2l(), copy_remote_to_block(), copy_upload(), copy_vfs_to_vfs(), copy_web_upload(), cvmfs_tier_open_respond(), dig_open_confined(), do_download(), do_upload(), download_finalize_local(), download_to_local_file(), get_eval_conditionals(), get_resolve_and_stat(), get_serve_range(), ngx_http_brix_dashboard_vfs_download_handler(), s3_content_md5_verify(), s3_get_resolve(), s3_get_serve_multirange(), s3_handle_get(), s3_handle_head(), s3_handle_upload_part_copy(), s3_put_checksum_apply(), s3_put_trailer_checksum_apply(), serve_range_unsatisfiable(), serve_send_memory_backed(), serve_send_sendfile(), serve_try_compressed(), webdav_head_emit_digest(), webdav_lock_create_null(), writer_release(), writer_verify(), zip_http_open_archive(), zip_http_stage_deflate(), and zip_http_stage_stored().
brix_vfs_file_backend_name()
const char * brix_vfs_file_backend_name (const brix_vfs_file_t * fh)
Definition at line 205 of file vfs_open_handle.c.
References brix_sd_backend_name().
Referenced by brix_http_serve_file_ranged().
brix_vfs_file_can_sendfile()
ngx_uint_t brix_vfs_file_can_sendfile (const brix_vfs_file_t * fh)
Definition at line 195 of file vfs_open_handle.c.
References brix_vfs_file_sendfile_fd().
brix_vfs_file_fd()
ngx_fd_t brix_vfs_file_fd (const brix_vfs_file_t * fh)
Definition at line 64 of file vfs_open_handle.c.
Referenced by brix_http_serve_file_ranged(), brix_query_cksum_path(), brix_vfs_writer_fd(), s3_content_md5_verify(), s3_get_echo_headers(), s3_handle_head(), s3_handle_upload_part_copy(), s3_put_checksum_apply(), s3_put_trailer_checksum_apply(), serve_try_compressed(), webdav_head_emit_digest(), zip_http_locate_member(), zip_http_open_archive(), zip_http_stage_deflate(), and zip_http_stage_stored().
brix_vfs_file_from_cache()
ngx_uint_t brix_vfs_file_from_cache (const brix_vfs_file_t * fh)
Definition at line 232 of file vfs_open_handle.c.
Referenced by brix_http_serve_file_ranged(), get_resolve_and_stat(), and serve_try_compressed().
brix_vfs_file_mtime()
time_t brix_vfs_file_mtime (const brix_vfs_file_t * fh)
Definition at line 226 of file vfs_open_handle.c.
brix_vfs_file_path()
const char * brix_vfs_file_path (const brix_vfs_file_t * fh)
Definition at line 214 of file vfs_open_handle.c.
Referenced by brix_http_serve_file_ranged(), get_resolve_and_stat(), and serve_try_compressed().
brix_vfs_file_pread()
ssize_t brix_vfs_file_pread (brix_vfs_file_t * fh, void * buf, size_t len, off_t off)
Definition at line 80 of file vfs_open_handle.c.
Referenced by brix_serve_memory_backed(), ev_retr_mode_e_write(), and ev_retr_write().
brix_vfs_file_pwrite()
ssize_t brix_vfs_file_pwrite (brix_vfs_file_t * fh, const void * buf, size_t len, off_t off)
Definition at line 98 of file vfs_open_handle.c.
Referenced by writer_put().
brix_vfs_file_sd_obj()
void brix_vfs_file_sd_obj (const brix_vfs_file_t * fh, brix_sd_obj_t * out)
Definition at line 70 of file vfs_open_handle.c.
References brix_vfs_handle_sd_obj().
Referenced by brix_ftp_ev_cmd_cksm(), brix_qcksum_compute_sync(), brix_qcksum_try_async(), and brix_vfs_wverify_check().
brix_vfs_file_sendfile_fd()
ngx_fd_t brix_vfs_file_sendfile_fd (const brix_vfs_file_t * fh)
Definition at line 177 of file vfs_open_handle.c.
References brix_vfs_handle_sendfile_fd(), and brix_vfs_memfile_materialize().
Referenced by brix_http_serve_file_ranged(), brix_vfs_file_can_sendfile(), brix_vfs_writer_write_fd(), dig_open_confined(), get_serve_range(), and s3_get_serve_multirange().
brix_vfs_file_size()
off_t brix_vfs_file_size (const brix_vfs_file_t * fh)
Definition at line 220 of file vfs_open_handle.c.
Referenced by brix_ftp_ev_data_ready(), and brix_vfs_wverify_check().
brix_vfs_file_stat()
ngx_int_t brix_vfs_file_stat (const brix_vfs_file_t * fh, brix_vfs_stat_t * stat_out)
Definition at line 238 of file vfs_open_handle.c.
References brix_vfs_handle_sd_obj(), brix_vfs_sd_stat_to_vfs(), brix_vfs_stat_t::ctime, brix_vfs_stat_t::ino, brix_vfs_stat_t::is_directory, brix_vfs_stat_t::is_regular, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, and brix_vfs_stat_t::size.
Referenced by cvmfs_tier_open_respond(), dig_open_confined(), get_resolve_and_stat(), ngx_http_brix_dashboard_vfs_download_handler(), and s3_get_resolve().
brix_vfs_memfile_materialize()
static ngx_fd_t brix_vfs_memfile_materialize (brix_vfs_file_t * fh) static
Definition at line 122 of file vfs_open_handle.c.
References BRIX_SD_CAP_MEMFILE, brix_sd_caps(), brix_vfs_handle_sd_obj(), and lseek().
Referenced by brix_vfs_file_sendfile_fd().