nginx-xrootd: src/fs/vfs/vfs_sync.c File Reference
vfs_sync.c File Reference
#include "vfs_internal.h"
#include "vfs_io_core.h"
Functions
ngx_int_t brix_vfs_truncate (brix_vfs_file_t *fh, off_t length)
ngx_int_t brix_vfs_sync (brix_vfs_file_t *fh)
Function Documentation
brix_vfs_sync()
ngx_int_t brix_vfs_sync (brix_vfs_file_t * fh)
Definition at line 56 of file vfs_sync.c.
References brix_vfs_io_execute(), brix_vfs_job_sync_init(), brix_vfs_job_t::io_errno, and brix_vfs_job_t::obj.
Referenced by brix_vfs_writer_commit_ex().
brix_vfs_truncate()
ngx_int_t brix_vfs_truncate (brix_vfs_file_t * fh, off_t length)
Definition at line 24 of file vfs_sync.c.
References BRIX_SD_CAP_TRUNCATE, brix_sd_caps(), brix_vfs_io_execute(), brix_vfs_job_truncate_init(), brix_vfs_job_t::io_errno, and brix_vfs_job_t::obj.
Referenced by brix_handle_truncate().