nginx-xrootd: client/lib/fs/vfs.c File Reference
vfs.c File Reference
#include "vfs.h"
#include "brix.h"
#include <string.h>
#include <pthread.h>
Macros
#define VFS_MAX_BACKENDS 8
Functions
void brix_vfs_register_backend (const brix_vfs_backend *be)
const brix_vfs_backend * brix_vfs_posix_backend (void)
const brix_vfs_backend * brix_vfs_block_backend (void)
const brix_vfs_backend * brix_vfs_s3_backend (void)
static void vfs_init_backends (void)
static void vfs_url_to_scheme (const char *url, const char **scheme_out, const char **path_out)
static const brix_vfs_backend * vfs_find_backend (const char *scheme)
int brix_vfs_open (const char *url, int flags, const brix_vfs_open_opts *opts, brix_vfs_file **out, brix_status *st)
int brix_vfs_stat_url (const char *url, const brix_vfs_open_opts *opts, brix_vfs_stat *out, brix_status *st)
ssize_t brix_vfs_pread (brix_vfs_file *f, int64_t off, void *buf, size_t n, brix_status *st)
int brix_vfs_pwrite (brix_vfs_file *f, int64_t off, const void *buf, size_t n, brix_status *st)
int brix_vfs_fstat (brix_vfs_file *f, brix_vfs_stat *out, brix_status *st)
int brix_vfs_truncate (brix_vfs_file *f, int64_t size, brix_status *st)
int brix_vfs_sync (brix_vfs_file *f, brix_status *st)
int brix_vfs_commit (brix_vfs_file *f, brix_status *st)
void brix_vfs_abort (brix_vfs_file *f)
void brix_vfs_close (brix_vfs_file *f)
uint32_t brix_vfs_get_caps (const brix_vfs_file *f)
Variables
static const brix_vfs_backend * g_backends [8]
static int g_n_backends
static pthread_once_t g_init_once = PTHREAD_ONCE_INIT
Macro Definition Documentation
VFS_MAX_BACKENDS
#define VFS_MAX_BACKENDS 8
Definition at line 22 of file vfs.c.
Function Documentation
brix_vfs_abort()
void brix_vfs_abort (brix_vfs_file * f)
Definition at line 313 of file vfs.c.
References brix_vfs_ops::abort, and brix_vfs_file::ops.
Referenced by copy_one_r2l(), copy_remote_to_block(), copy_vfs_to_vfs(), do_download(), download_finalize_local(), and download_to_local_file().
brix_vfs_block_backend()
const brix_vfs_backend * brix_vfs_block_backend (void) extern
Definition at line 510 of file vfs_block.c.
References s_block_backend.
Referenced by vfs_init_backends().
brix_vfs_close()
void brix_vfs_close (brix_vfs_file * f)
Definition at line 326 of file vfs.c.
References brix_vfs_ops::close, and brix_vfs_file::ops.
brix_vfs_commit()
int brix_vfs_commit (brix_vfs_file * f, brix_status * st)
Definition at line 300 of file vfs.c.
References brix_vfs_ops::commit, and brix_vfs_file::ops.
Referenced by copy_one_r2l(), copy_remote_to_block(), copy_vfs_to_vfs(), download_finalize_local(), and download_to_local_file().
brix_vfs_fstat()
int brix_vfs_fstat (brix_vfs_file * f, brix_vfs_stat * out, brix_status * st)
Definition at line 261 of file vfs.c.
References brix_vfs_ops::fstat, and brix_vfs_file::ops.
Referenced by copy_block_to_remote(), copy_upload(), copy_vfs_to_vfs(), and copy_web_upload().
brix_vfs_get_caps()
uint32_t brix_vfs_get_caps (const brix_vfs_file * f)
Definition at line 340 of file vfs.c.
References brix_vfs_file::caps.
brix_vfs_open()
int brix_vfs_open (const char * url, int flags, const brix_vfs_open_opts * opts, brix_vfs_file ** out, brix_status * st)
Definition at line 161 of file vfs.c.
References brix_status_set(), g_init_once, brix_vfs_backend::open, scheme, vfs_find_backend(), vfs_init_backends(), vfs_url_to_scheme(), and XRDC_EUSAGE.
brix_vfs_posix_backend()
const brix_vfs_backend * brix_vfs_posix_backend (void) extern
Definition at line 557 of file vfs_posix.c.
References s_posix_backend.
Referenced by vfs_init_backends().
brix_vfs_pread()
ssize_t brix_vfs_pread (brix_vfs_file * f, int64_t off, void * buf, size_t n, brix_status * st)
Definition at line 233 of file vfs.c.
References brix_vfs_file::ops, and brix_vfs_ops::pread.
Referenced by pump_src_local_vfs(), upload_copy_loop(), and web_upload_src_vfs().
brix_vfs_pwrite()
int brix_vfs_pwrite (brix_vfs_file * f, int64_t off, const void * buf, size_t n, brix_status * st)
Definition at line 247 of file vfs.c.
References brix_vfs_file::ops, and brix_vfs_ops::pwrite.
Referenced by download_copy_loop(), and pump_sink_local_vfs().
brix_vfs_register_backend()
void brix_vfs_register_backend (const brix_vfs_backend * be)
Definition at line 37 of file vfs.c.
References g_backends, g_n_backends, and VFS_MAX_BACKENDS.
Referenced by vfs_init_backends().
brix_vfs_s3_backend()
const brix_vfs_backend * brix_vfs_s3_backend (void) extern
Definition at line 301 of file vfs_s3.c.
References s_s3_backend.
Referenced by vfs_init_backends().
brix_vfs_stat_url()
int brix_vfs_stat_url (const char * url, const brix_vfs_open_opts * opts, brix_vfs_stat * out, brix_status * st)
Definition at line 196 of file vfs.c.
References brix_status_set(), g_init_once, scheme, brix_vfs_backend::stat, vfs_find_backend(), vfs_init_backends(), vfs_url_to_scheme(), and XRDC_EUSAGE.
brix_vfs_sync()
int brix_vfs_sync (brix_vfs_file * f, brix_status * st)
Definition at line 287 of file vfs.c.
References brix_vfs_file::ops, and brix_vfs_ops::sync.
brix_vfs_truncate()
int brix_vfs_truncate (brix_vfs_file * f, int64_t size, brix_status * st)
Definition at line 274 of file vfs.c.
References brix_vfs_file::ops, and brix_vfs_ops::truncate.
vfs_find_backend()
static const brix_vfs_backend * vfs_find_backend (const char * scheme) static
Definition at line 140 of file vfs.c.
References g_backends, g_n_backends, and scheme.
Referenced by brix_vfs_open(), and brix_vfs_stat_url().
vfs_init_backends()
static void vfs_init_backends (void) static
Definition at line 65 of file vfs.c.
References brix_vfs_block_backend(), brix_vfs_posix_backend(), brix_vfs_register_backend(), and brix_vfs_s3_backend().
Referenced by brix_vfs_open(), and brix_vfs_stat_url().
vfs_url_to_scheme()
static void vfs_url_to_scheme (const char * url, const char ** scheme_out, const char ** path_out) static
Definition at line 93 of file vfs.c.
References brix_is_web_url(), brix_weburl_parse(), brix_weburl::is_s3, brix_weburl::proto, and XRDC_WEB_S3S.
Referenced by brix_vfs_open(), and brix_vfs_stat_url().
Variable Documentation
g_backends
const brix_vfs_backend* g_backends[8] static
Definition at line 24 of file vfs.c.
Referenced by brix_vfs_register_backend(), and vfs_find_backend().
g_init_once
pthread_once_t g_init_once = PTHREAD_ONCE_INIT static
Definition at line 26 of file vfs.c.
Referenced by brix_vfs_open(), and brix_vfs_stat_url().
g_n_backends
int g_n_backends static
Definition at line 25 of file vfs.c.
Referenced by brix_vfs_register_backend(), and vfs_find_backend().