nginx-xrootd: src/fs/vfs/vfs_open_adopt.c File Reference
vfs_open_adopt.c File Reference
#include "vfs_internal.h"
#include "vfs_backend_registry.h"
Functions
void brix_vfs_ctx_init (brix_vfs_ctx_t *vctx, ngx_pool_t *pool, ngx_log_t *log, brix_proto_t proto, const char *root_canon, const char *cache_root_canon, int allow_write, int is_tls, brix_identity_t *identity, const char *resolved_path)
void brix_vfs_fill_stat (const struct stat *st, brix_vfs_stat_t *out)
char * brix_vfs_copy_path (ngx_pool_t *pool, const char *path)
ngx_int_t brix_vfs_adopt_fd (brix_vfs_ctx_t *ctx, const char *path, ngx_fd_t fd, brix_vfs_adopt_attrs_t attrs, brix_vfs_file_t **out)
ngx_int_t brix_vfs_adopt_obj (brix_vfs_ctx_t *ctx, const char *path, brix_sd_obj_t *o, unsigned writable, brix_vfs_file_t **out)
const char * brix_vfs_export_relative_root (const char *path, const char *root_canon)
const char * brix_vfs_export_relative (const brix_vfs_ctx_t *ctx, const char *path)
Function Documentation
brix_vfs_adopt_fd()
ngx_int_t brix_vfs_adopt_fd (brix_vfs_ctx_t * ctx, const char * path, ngx_fd_t fd, brix_vfs_adopt_attrs_t attrs, brix_vfs_file_t ** out)
Definition at line 121 of file vfs_open_adopt.c.
References brix_vfs_copy_path(), brix_vfs_ctx_sd_obj(), brix_sd_stat_t::ctime, brix_vfs_adopt_attrs_t::from_cache, brix_sd_stat_t::ino, brix_vfs_ctx_t::is_tls, brix_vfs_ctx_t::log, brix_sd_stat_t::mode, brix_sd_stat_t::mtime, ngx_pcalloc(), brix_vfs_ctx_t::pool, brix_sd_stat_t::size, and brix_vfs_adopt_attrs_t::writable.
Referenced by brix_vfs_open_via_posix().
brix_vfs_adopt_obj()
ngx_int_t brix_vfs_adopt_obj (brix_vfs_ctx_t * ctx, const char * path, brix_sd_obj_t * o, unsigned writable, brix_vfs_file_t ** out)
Definition at line 229 of file vfs_open_adopt.c.
References brix_vfs_copy_path(), brix_sd_stat_t::ctime, brix_sd_stat_t::ino, brix_vfs_ctx_t::is_tls, brix_vfs_ctx_t::log, brix_sd_stat_t::mode, brix_sd_stat_t::mtime, ngx_pcalloc(), brix_vfs_ctx_t::pool, and brix_sd_stat_t::size.
Referenced by brix_cache_open_adopt(), and brix_vfs_open_via_driver().
brix_vfs_copy_path()
char * brix_vfs_copy_path (ngx_pool_t * pool, const char * path)
Definition at line 94 of file vfs_open_adopt.c.
References ngx_memcpy, and ngx_pnalloc().
Referenced by brix_vfs_adopt_fd(), brix_vfs_adopt_obj(), brix_vfs_mkdir_parent_path(), brix_vfs_opendir_impl(), and vfs_dir_open_driver().
brix_vfs_ctx_init()
void brix_vfs_ctx_init (brix_vfs_ctx_t * vctx, ngx_pool_t * pool, ngx_log_t * log, brix_proto_t proto, const char * root_canon, const char * cache_root_canon, int allow_write, int is_tls, brix_identity_t * identity, const char * resolved_path)
Definition at line 37 of file vfs_open_adopt.c.
References brix_vfs_ctx_t::allow_write, brix_vfs_backend_resolve(), brix_vfs_ctx_t::cache_enabled, brix_vfs_ctx_t::cache_root_canon, brix_vfs_ctx_t::identity, brix_path_result_t::is_confined, brix_vfs_ctx_t::is_tls, log, brix_vfs_ctx_t::log, brix_vfs_ctx_t::metrics_proto, brix_vfs_ctx_t::pool, brix_path_result_t::resolved, brix_vfs_ctx_t::resolved, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::rootfd, and brix_vfs_ctx_t::sd.
Referenced by brix_dirlist_open_dir(), brix_handle_mkdir(), brix_handle_setattr(), brix_handle_truncate(), brix_integrity_invalidate_path(), brix_open_build_cred_ctx(), brix_open_probe(), brix_open_read_probe(), brix_open_residency_gate(), brix_qcksum_open(), brix_query_xattr(), brix_statx_compute_flag(), brix_statx_symlink_fallback_stat(), cvmfs_tier_get(), dig_open_confined(), fattr_bind_vctx(), fattr_recurse_init_node_ctx(), get_init_vfs_ctx(), mv_bind_vfs(), op_path_probe(), op_vfs_ctx(), propfind_dir_ctx(), propfind_emit_locality(), s3_build_vfs_ctx(), s3_chunk_finalize(), s3_cksum_vfs_open(), s3_cksum_vfs_unlink(), s3_commit_put(), s3_copy_vfs_ctx(), s3_delete_one(), s3_entry_fill_stat(), s3_put_aio_done(), s3_put_precondition(), s3_tag_vfs_ctx(), s3_user_meta_vfs_ctx(), s3_vfs_ctx(), s3_walk_classify(), s3_walk_run(), stat_residency_flags(), stat_vfs_ctx_prepare(), tape_residency(), vfs_browse_ctx(), webdav_copy_file_vfs_init(), webdav_copy_probe(), webdav_dead_prop_vfs_ctx_init(), webdav_head_emit_digest(), webdav_lock_sweep_remove(), webdav_lock_vfs_ctx(), webdav_lock_vfs_ctx_init(), webdav_move_execute_cred(), webdav_move_probe(), webdav_ns_vfs_ctx_init(), webdav_put_precheck(), webdav_put_vfs_ctx_init(), webdav_search_entry_is_dir(), webdav_search_walk(), webdav_tpc_probe(), and zip_http_open_archive().
brix_vfs_export_relative()
const char * brix_vfs_export_relative (const brix_vfs_ctx_t * ctx, const char * path)
Definition at line 223 of file vfs_open_adopt.c.
References brix_vfs_export_relative_root(), and brix_vfs_ctx_t::root_canon.
Referenced by brix_vfs_chmod(), brix_vfs_copy_driver(), brix_vfs_delete_via_driver(), brix_vfs_getxattr(), brix_vfs_listxattr(), brix_vfs_open_via_driver(), brix_vfs_probe(), brix_vfs_removexattr(), brix_vfs_rename(), brix_vfs_residency(), brix_vfs_setattr(), brix_vfs_setxattr(), brix_vfs_stat_impl(), cvmfs_tier_get(), get_offload_or_fill(), s3_get_cache_fill(), s3_get_serve_offload(), staged_open_driver(), vfs_backend_mkdir_dispatch(), and vfs_dir_open_driver().
brix_vfs_export_relative_root()
const char * brix_vfs_export_relative_root (const char * path, const char * root_canon)
Definition at line 202 of file vfs_open_adopt.c.
Referenced by brix_cache_fill_composed_thread(), brix_open_dispatch_driver(), brix_open_read_probe(), brix_open_try_cache_offload(), brix_vfs_export_relative(), brix_vfs_mkdir_parent_path(), and brix_vfs_rename_path().
brix_vfs_fill_stat()
void brix_vfs_fill_stat (const struct stat * st, brix_vfs_stat_t * out)
Definition at line 72 of file vfs_open_adopt.c.
References brix_vfs_stat_t::atime, brix_vfs_stat_t::blocks, brix_vfs_stat_t::ctime, brix_vfs_stat_t::dev, brix_vfs_stat_t::gid, brix_vfs_stat_t::ino, brix_vfs_stat_t::is_directory, brix_vfs_stat_t::is_regular, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, brix_vfs_stat_t::size, and brix_vfs_stat_t::uid.
Referenced by brix_vfs_probe(), brix_vfs_stat_impl(), vfs_readdir_stat_child(), and vfs_walk_emit_file().