nginx-xrootd: src/observability/dashboard/vfs_browse.c File Reference
vfs_browse.c File Reference
#include "dashboard_http.h"
#include "dashboard_json.h"
#include "fs/vfs/vfs.h"
#include "fs/vfs/vfs_backend_registry.h"
#include "protocols/shared/file_serve.h"
#include "core/http/etag.h"
#include "core/http/http_headers.h"
#include <errno.h>
#include <jansson.h>
#include <limits.h>
#include <string.h>
Macros
#define DASHBOARD_VFS_MAX_ENTRIES 10000
Functions
static ngx_int_t vfs_browse_status (int e)
static ngx_int_t vfs_browse_preamble (ngx_http_request_t *r, ngx_http_brix_dashboard_loc_conf_t *conf)
static ngx_int_t vfs_browse_get_export (ngx_http_request_t *r, ngx_uint_t *idx_out)
static ngx_int_t vfs_browse_get_path (ngx_http_request_t *r, char *out, size_t outsz)
static ngx_int_t vfs_browse_abs_path (const char *root_canon, const char *path, char *abs, size_t abssz)
static void vfs_browse_ctx (ngx_http_request_t *r, const brix_vfs_backend_info_t *info, const char *abs, brix_vfs_ctx_t *vctx)
ngx_int_t ngx_http_brix_dashboard_vfs_exports_handler (ngx_http_request_t *r)
static json_t * vfs_browse_entry (ngx_http_request_t *r, const brix_vfs_backend_info_t *info, const char *abs_dir, const ngx_str_t *name, brix_vfs_dirent_kind_t kind)
ngx_int_t ngx_http_brix_dashboard_vfs_files_handler (ngx_http_request_t *r)
ngx_int_t ngx_http_brix_dashboard_vfs_download_handler (ngx_http_request_t *r)
Macro Definition Documentation
DASHBOARD_VFS_MAX_ENTRIES
#define DASHBOARD_VFS_MAX_ENTRIES 10000
Definition at line 43 of file vfs_browse.c.
Function Documentation
ngx_http_brix_dashboard_vfs_download_handler()
ngx_int_t ngx_http_brix_dashboard_vfs_download_handler (ngx_http_request_t * r)
Definition at line 369 of file vfs_browse.c.
References BRIX_ETAG_WEAK, brix_http_serve_file_ranged(), brix_vfs_backend_export_info(), brix_vfs_close(), brix_vfs_file_stat(), BRIX_VFS_O_READ, brix_vfs_open(), BRIX_XFER_PROTO_WEBDAV, brix_http_serve_opts_t::etag_flags, brix_http_serve_opts_t::identity, brix_vfs_stat_t::is_regular, ngx_http_brix_dashboard_module, brix_http_serve_opts_t::op_name, PATH_MAX, brix_vfs_backend_info_t::root_canon, vfs_browse_abs_path(), vfs_browse_ctx(), vfs_browse_get_export(), vfs_browse_get_path(), vfs_browse_preamble(), vfs_browse_status(), and brix_http_serve_opts_t::xfer_proto.
Referenced by ngx_http_brix_dashboard_main_handler().
ngx_http_brix_dashboard_vfs_exports_handler()
ngx_int_t ngx_http_brix_dashboard_vfs_exports_handler (ngx_http_request_t * r)
Definition at line 179 of file vfs_browse.c.
References brix_vfs_backend_info_t::backend, brix_vfs_backend_export_count(), brix_vfs_backend_export_info(), dashboard_json_send(), dashboard_json_set_schema(), brix_vfs_backend_info_t::host, ngx_http_brix_dashboard_module, brix_vfs_backend_info_t::port, brix_vfs_backend_info_t::root_canon, brix_vfs_backend_info_t::staging, and vfs_browse_preamble().
Referenced by ngx_http_brix_dashboard_main_handler().
ngx_http_brix_dashboard_vfs_files_handler()
ngx_int_t ngx_http_brix_dashboard_vfs_files_handler (ngx_http_request_t * r)
Definition at line 287 of file vfs_browse.c.
References brix_vfs_backend_info_t::backend, brix_vfs_backend_export_info(), brix_vfs_closedir(), brix_vfs_opendir(), brix_vfs_readdir_kind(), dashboard_json_send(), dashboard_json_set_schema(), DASHBOARD_VFS_MAX_ENTRIES, name, ngx_http_brix_dashboard_module, PATH_MAX, brix_vfs_backend_info_t::root_canon, vfs_browse_abs_path(), vfs_browse_ctx(), vfs_browse_entry(), vfs_browse_get_export(), vfs_browse_get_path(), vfs_browse_preamble(), and vfs_browse_status().
Referenced by ngx_http_brix_dashboard_main_handler().
vfs_browse_abs_path()
static ngx_int_t vfs_browse_abs_path (const char * root_canon, const char * path, char * abs, size_t abssz) static
Definition at line 148 of file vfs_browse.c.
Referenced by ngx_http_brix_dashboard_vfs_download_handler(), and ngx_http_brix_dashboard_vfs_files_handler().
vfs_browse_ctx()
static void vfs_browse_ctx (ngx_http_request_t * r, const brix_vfs_backend_info_t * info, const char * abs, brix_vfs_ctx_t * vctx) static
Definition at line 164 of file vfs_browse.c.
References BRIX_PROTO_ROOT, brix_vfs_ctx_init(), brix_vfs_ctx_t::pool, and brix_vfs_backend_info_t::root_canon.
Referenced by ngx_http_brix_dashboard_vfs_download_handler(), ngx_http_brix_dashboard_vfs_files_handler(), and vfs_browse_entry().
vfs_browse_entry()
static json_t * vfs_browse_entry (ngx_http_request_t * r, const brix_vfs_backend_info_t * info, const char * abs_dir, const ngx_str_t * name, brix_vfs_dirent_kind_t kind) static
Definition at line 236 of file vfs_browse.c.
References BRIX_VFS_DT_DIR, BRIX_VFS_DT_OTHER, BRIX_VFS_DT_REG, BRIX_VFS_DT_UNKNOWN, brix_vfs_stat_t::is_directory, brix_vfs_stat_t::is_regular, brix_vfs_stat_t::mtime, name, ngx_memcpy, PATH_MAX, brix_vfs_stat_t::size, and vfs_browse_ctx().
Referenced by ngx_http_brix_dashboard_vfs_files_handler().
vfs_browse_get_export()
static ngx_int_t vfs_browse_get_export (ngx_http_request_t * r, ngx_uint_t * idx_out) static
Definition at line 83 of file vfs_browse.c.
References brix_vfs_backend_export_count().
Referenced by ngx_http_brix_dashboard_vfs_download_handler(), and ngx_http_brix_dashboard_vfs_files_handler().
vfs_browse_get_path()
static ngx_int_t vfs_browse_get_path (ngx_http_request_t * r, char * out, size_t outsz) static
Definition at line 105 of file vfs_browse.c.
References ngx_memcpy.
Referenced by ngx_http_brix_dashboard_vfs_download_handler(), and ngx_http_brix_dashboard_vfs_files_handler().
vfs_browse_preamble()
static ngx_int_t vfs_browse_preamble (ngx_http_request_t * r, ngx_http_brix_dashboard_loc_conf_t * conf) static
Definition at line 61 of file vfs_browse.c.
References brix_http_source_offer(), ngx_http_brix_dashboard_check_auth(), and ngx_http_brix_dashboard_loc_conf_t::vfs_browse.
Referenced by ngx_http_brix_dashboard_vfs_download_handler(), ngx_http_brix_dashboard_vfs_exports_handler(), and ngx_http_brix_dashboard_vfs_files_handler().
vfs_browse_status()
static ngx_int_t vfs_browse_status (int e) static
Definition at line 47 of file vfs_browse.c.
Referenced by ngx_http_brix_dashboard_vfs_download_handler(), and ngx_http_brix_dashboard_vfs_files_handler().