nginx-xrootd: src/fs/vfs/vfs_ops.h File Reference
vfs_ops.h File Reference
Data Structures
struct brix_vfs_walk_opts_t
Macros
#define BRIX_VFS_WRITER_T_DECLARED
Typedefs
typedef ngx_int_t(* brix_vfs_walk_file_cb) (void *cookie, const char *logical, const brix_vfs_stat_t *st, int fd)
typedef ngx_int_t(* brix_vfs_copy_meta_cb) (void *cookie, const char *src, const char *dst, int is_dir)
Enumerations
enum brix_vfs_walk_target_t { BRIX_VFS_WALK_NONE = 0 , BRIX_VFS_WALK_FILE , BRIX_VFS_WALK_DIR , BRIX_VFS_WALK_OTHER }
Functions
ngx_int_t brix_vfs_walk (ngx_log_t *log, int rootfd, const char *logical, const brix_vfs_walk_opts_t *opts, brix_vfs_walk_file_cb cb, void *cookie, brix_vfs_walk_target_t *target_out, char *errmsg, size_t errsz)
ngx_int_t brix_vfs_copyfile (ngx_log_t *log, const char *root_canon, const char *src, const char *dst, int preserve_xattrs, brix_vfs_copy_meta_cb meta_cb, void *cookie)
ngx_int_t brix_vfs_copytree (ngx_log_t *log, const char *root_canon, const char *src, const char *dst, int preserve_xattrs, brix_vfs_copy_meta_cb meta_cb, void *cookie)
int brix_vfs_open_fd (ngx_log_t *log, const char *root_canon, const char *logical, int flags, mode_t mode)
int brix_vfs_open_fd_at (int rootfd, const char *logical, int flags, mode_t mode)
int brix_vfs_unlink_at (int rootfd, const char *logical, int is_dir)
int brix_vfs_unlink_path (ngx_log_t *log, const char *root_canon, const char *logical)
int brix_vfs_backend_mkpath (const char *root_canon, const char *logical, mode_t mode, ngx_log_t *log)
int brix_vfs_mkdir_path (ngx_log_t *log, const char *root_canon, const char *logical, mode_t mode)
ngx_int_t brix_vfs_pread_full (ngx_fd_t fd, u_char *buf, size_t len, off_t offset, size_t *nread)
ngx_int_t brix_vfs_pwrite_full (ngx_fd_t fd, const u_char *buf, size_t len, off_t offset)
ssize_t brix_vfs_getxattr (brix_vfs_ctx_t *ctx, const char *name, void *buf, size_t bufsz)
ssize_t brix_vfs_listxattr (brix_vfs_ctx_t *ctx, void *buf, size_t bufsz)
ngx_int_t brix_vfs_setxattr (brix_vfs_ctx_t *ctx, const char *name, const void *value, size_t len, int flags)
ngx_int_t brix_vfs_removexattr (brix_vfs_ctx_t *ctx, const char *name)
ssize_t brix_vfs_fgetxattr (const brix_vfs_ctx_t *ctx, int fd, const char *name, void *buf, size_t bufsz)
ssize_t brix_vfs_flistxattr (const brix_vfs_ctx_t *ctx, int fd, void *buf, size_t bufsz)
ngx_int_t brix_vfs_fsetxattr (const brix_vfs_ctx_t *ctx, int fd, const char *name, const void *value, size_t len, int flags)
ngx_int_t brix_vfs_fremovexattr (const brix_vfs_ctx_t *ctx, int fd, const char *name)
ngx_int_t brix_vfs_copy (brix_vfs_ctx_t *ctx, const char *dst_resolved, const brix_vfs_copy_opts_t *opts)
brix_vfs_staged_t * brix_vfs_staged_open (brix_vfs_ctx_t *ctx, mode_t mode, ngx_uint_t attempts, int *err_out)
ngx_fd_t brix_vfs_staged_fd (const brix_vfs_staged_t *st)
ngx_uint_t brix_vfs_staged_is_driver (const brix_vfs_staged_t *st)
ngx_int_t brix_vfs_staged_write (brix_vfs_staged_t *st, const void *buf, size_t len, off_t off)
const char * brix_vfs_staged_tmp_path (const brix_vfs_staged_t *st)
ngx_int_t brix_vfs_staged_commit (brix_vfs_staged_t *st, unsigned excl)
void brix_vfs_staged_abort (brix_vfs_staged_t *st, unsigned remove_tmp)
brix_vfs_writer_t * brix_vfs_writer_open (brix_vfs_ctx_t *ctx, unsigned flags, int verify, int *err_out)
ngx_int_t brix_vfs_writer_write (brix_vfs_writer_t *w, const void *buf, size_t len, off_t off)
ngx_int_t brix_vfs_writer_write_fd (brix_vfs_writer_t *w, int src_fd, off_t src_off, size_t len, off_t dst_off)
off_t brix_vfs_writer_expected_off (const brix_vfs_writer_t *w)
ngx_int_t brix_vfs_writer_commit (brix_vfs_writer_t *w)
ngx_int_t brix_vfs_writer_commit_ex (brix_vfs_writer_t *w, unsigned excl)
void brix_vfs_writer_abort (brix_vfs_writer_t *w)
ngx_fd_t brix_vfs_writer_fd (const brix_vfs_writer_t *w)
brix_vfs_staged_t * brix_vfs_writer_staged (const brix_vfs_writer_t *w)
Macro Definition Documentation
BRIX_VFS_WRITER_T_DECLARED
#define BRIX_VFS_WRITER_T_DECLARED
Definition at line 210 of file vfs_ops.h.
Typedef Documentation
brix_vfs_copy_meta_cb
typedef ngx_int_t(* brix_vfs_copy_meta_cb) (void *cookie, const char *src, const char *dst, int is_dir)
Definition at line 56 of file vfs_ops.h.
brix_vfs_walk_file_cb
typedef ngx_int_t(* brix_vfs_walk_file_cb) (void *cookie, const char *logical, const brix_vfs_stat_t *st, int fd)
Definition at line 37 of file vfs_ops.h.
Enumeration Type Documentation
brix_vfs_walk_target_t
enum brix_vfs_walk_target_t
Enumerator
BRIX_VFS_WALK_NONE
BRIX_VFS_WALK_FILE
BRIX_VFS_WALK_DIR
BRIX_VFS_WALK_OTHER
Definition at line 26 of file vfs_ops.h.
Function Documentation
brix_vfs_backend_mkpath()
int brix_vfs_backend_mkpath (const char * root_canon, const char * logical, mode_t mode, ngx_log_t * log)
Definition at line 353 of file vfs_walk.c.
References brix_vfs_backend_resolve(), log, and PATH_MAX.
Referenced by brix_vfs_mkdir_parent_path(), cms_node_exec_driver(), mv_make_dst_parents(), and vfs_backend_mkdir_dispatch().
brix_vfs_copy()
ngx_int_t brix_vfs_copy (brix_vfs_ctx_t * ctx, const char * dst_resolved, const brix_vfs_copy_opts_t * opts)
Definition at line 196 of file vfs_copy.c.
References brix_vfs_copy_driver(), brix_vfs_copy_fail(), brix_vfs_copy_ns(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_now_ns(), brix_vfs_require_write(), and brix_vfs_ctx_t::root_canon.
Referenced by s3_handle_copy_object(), and webdav_copy_do_file().
brix_vfs_copyfile()
ngx_int_t brix_vfs_copyfile (ngx_log_t * log, const char * root_canon, const char * src, const char * dst, int preserve_xattrs, brix_vfs_copy_meta_cb meta_cb, void * cookie)
Definition at line 400 of file vfs_walk.c.
References brix_copy_range(), brix_lstat_confined_canon(), brix_ns_copy_fattrs(), brix_open_confined_canon(), log, and stat().
Referenced by vfs_copytree_entry(), and webdav_copy_file().
brix_vfs_copytree()
ngx_int_t brix_vfs_copytree (ngx_log_t * log, const char * root_canon, const char * src, const char * dst, int preserve_xattrs, brix_vfs_copy_meta_cb meta_cb, void * cookie)
Definition at line 585 of file vfs_walk.c.
References log, and vfs_copytree_run().
Referenced by webdav_copy_dir_recursive().
brix_vfs_fgetxattr()
ssize_t brix_vfs_fgetxattr (const brix_vfs_ctx_t * ctx, int fd, const char * name, void * buf, size_t bufsz)
Definition at line 319 of file vfs_xattr.c.
References brix_vfs_now_ns(), brix_vfs_xattr_observe_count(), and name.
Referenced by fattr_list_append_value(), fattr_read_value(), fattr_read_value_size(), and integrity_xattr_read().
brix_vfs_flistxattr()
ssize_t brix_vfs_flistxattr (const brix_vfs_ctx_t * ctx, int fd, void * buf, size_t bufsz)
Definition at line 329 of file vfs_xattr.c.
References brix_vfs_now_ns(), and brix_vfs_xattr_observe_count().
Referenced by fattr_list_read_names().
brix_vfs_fremovexattr()
ngx_int_t brix_vfs_fremovexattr (const brix_vfs_ctx_t * ctx, int fd, const char * name)
Definition at line 354 of file vfs_xattr.c.
References BRIX_METRIC_OP_XATTR, brix_vfs_now_ns(), brix_vfs_observe_ctx_op(), and name.
Referenced by brix_integrity_invalidate_fd(), and fattr_del().
brix_vfs_fsetxattr()
ngx_int_t brix_vfs_fsetxattr (const brix_vfs_ctx_t * ctx, int fd, const char * name, const void * value, size_t len, int flags)
Definition at line 339 of file vfs_xattr.c.
References BRIX_METRIC_OP_XATTR, brix_vfs_now_ns(), brix_vfs_observe_ctx_op(), and name.
Referenced by fattr_set(), and integrity_xattr_write_rc().
brix_vfs_getxattr()
ssize_t brix_vfs_getxattr (brix_vfs_ctx_t * ctx, const char * name, void * buf, size_t bufsz)
Definition at line 58 of file vfs_xattr.c.
References brix_getxattr_confined_canon(), brix_sd_getxattr_maybe_cred(), brix_sd_ucred_wipe(), brix_vfs_cred_gate_active(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_now_ns(), brix_vfs_ns_cred(), brix_vfs_ns_leaf(), brix_vfs_require_confined(), brix_vfs_xattr_observe_count(), brix_vfs_ctx_t::log, name, brix_vfs_ctx_t::root_canon, and brix_vfs_ctx_t::sd.
Referenced by brix_query_xattr(), fattr_list_append_value(), fattr_read_value(), fattr_read_value_size(), s3_tag_load(), s3_user_meta_load(), webdav_dead_prop_read_value(), and webdav_lock_xattr_read().
brix_vfs_listxattr()
ssize_t brix_vfs_listxattr (brix_vfs_ctx_t * ctx, void * buf, size_t bufsz)
Definition at line 111 of file vfs_xattr.c.
References brix_listxattr_confined_canon(), brix_sd_listxattr_maybe_cred(), brix_sd_ucred_wipe(), brix_vfs_cred_gate_active(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_now_ns(), brix_vfs_ns_cred(), brix_vfs_ns_leaf(), brix_vfs_require_confined(), brix_vfs_xattr_observe_count(), brix_vfs_ctx_t::log, brix_vfs_ctx_t::root_canon, and brix_vfs_ctx_t::sd.
Referenced by brix_query_xattr(), fattr_list_read_names(), fattr_recurse_file(), and webdav_dead_props_append_all().
brix_vfs_mkdir_path()
int brix_vfs_mkdir_path (ngx_log_t * log, const char * root_canon, const char * logical, mode_t mode)
Definition at line 337 of file vfs_walk.c.
References brix_mkdir_confined_canon(), and log.
Referenced by webdav_copy_collection_stage().
brix_vfs_open_fd()
int brix_vfs_open_fd (ngx_log_t * log, const char * root_canon, const char * logical, int flags, mode_t mode)
Definition at line 305 of file vfs_walk.c.
References brix_open_confined_canon(), and log.
Referenced by ckp_recover_one(), ckp_recover_open_dir(), s3_handle_upload_part_copy(), s3_mpu_assemble(), s3_put_try_sentinel(), tpc_core_open_local(), and webdav_put_persist_checksums().
brix_vfs_open_fd_at()
int brix_vfs_open_fd_at (int rootfd, const char * logical, int flags, mode_t mode)
Definition at line 315 of file vfs_walk.c.
References brix_open_beneath().
Referenced by brix_open_posix_dispatch(), brix_reopen_bound_read_handle(), cms_posix_apply(), tpc_open_dst_logical(), and zip_open_archive_fd().
brix_vfs_pread_full()
ngx_int_t brix_vfs_pread_full (ngx_fd_t fd, u_char * buf, size_t len, off_t offset, size_t * nread)
Definition at line 29 of file vfs_read.c.
References brix_sd_posix_wrap(), and xvfs_pread_full().
Referenced by brix_copy_range_fallback(), brix_http_body_read_all(), codec_decode_spooled_buf(), compress_stream_step(), and s3_chunk_feed_buf().
brix_vfs_pwrite_full()
ngx_int_t brix_vfs_pwrite_full (ngx_fd_t fd, const u_char * buf, size_t len, off_t offset)
Definition at line 22 of file vfs_write.c.
References brix_sd_posix_driver, and brix_sd_posix_wrap().
Referenced by brix_copy_range_fallback(), brix_http_body_pwrite_full(), brix_vfs_staged_write(), s3_chunk_emit(), and sd_posix_staged_write().
brix_vfs_removexattr()
ngx_int_t brix_vfs_removexattr (brix_vfs_ctx_t * ctx, const char * name)
Definition at line 265 of file vfs_xattr.c.
References brix_removexattr_confined_canon(), brix_sd_removexattr_maybe_cred(), brix_sd_ucred_wipe(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_now_ns(), brix_vfs_ns_leaf(), brix_vfs_require_confined(), brix_vfs_xattr_observe_mut(), brix_vfs_xattr_write_gate(), brix_vfs_ctx_t::log, name, brix_vfs_ctx_t::root_canon, and brix_vfs_ctx_t::sd.
Referenced by brix_integrity_invalidate_path(), fattr_del(), s3_tag_store(), webdav_dead_prop_remove(), webdav_lock_sweep_remove(), and webdav_lock_xattr_delete().
brix_vfs_setxattr()
ngx_int_t brix_vfs_setxattr (brix_vfs_ctx_t * ctx, const char * name, const void * value, size_t len, int flags)
Definition at line 219 of file vfs_xattr.c.
References brix_sd_setxattr_maybe_cred(), brix_sd_ucred_wipe(), brix_setxattr_confined_canon(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_now_ns(), brix_vfs_ns_leaf(), brix_vfs_require_confined(), brix_vfs_xattr_observe_mut(), brix_vfs_xattr_write_gate(), brix_vfs_ctx_t::log, name, brix_vfs_ctx_t::root_canon, and brix_vfs_ctx_t::sd.
Referenced by fattr_set(), s3_tag_store(), s3_user_meta_store(), webdav_dead_prop_set_target(), and webdav_lock_xattr_write().
brix_vfs_staged_abort()
void brix_vfs_staged_abort (brix_vfs_staged_t * st, unsigned remove_tmp)
Definition at line 350 of file vfs_staged.c.
References brix_staged_abort().
Referenced by brix_vfs_writer_commit_ex(), and writer_release().
brix_vfs_staged_commit()
ngx_int_t brix_vfs_staged_commit (brix_vfs_staged_t * st, unsigned excl)
Definition at line 275 of file vfs_staged.c.
References brix_lstat_confined_canon(), BRIX_METRIC_OP_WRITE, brix_staged_commit(), brix_staged_commit_excl(), brix_vfs_ctx_path(), brix_vfs_now_ns(), brix_vfs_observe_ctx_op(), BRIX_XFER_COMMIT_ERR, brix_xfer_finish(), BRIX_XFER_OK, BRIX_XFER_STAGE, and stat().
Referenced by brix_vfs_writer_commit_ex().
brix_vfs_staged_fd()
ngx_fd_t brix_vfs_staged_fd (const brix_vfs_staged_t * st)
Definition at line 218 of file vfs_staged.c.
Referenced by brix_vfs_writer_fd().
brix_vfs_staged_is_driver()
ngx_uint_t brix_vfs_staged_is_driver (const brix_vfs_staged_t * st)
Definition at line 227 of file vfs_staged.c.
brix_vfs_staged_open()
brix_vfs_staged_t * brix_vfs_staged_open (brix_vfs_ctx_t * ctx, mode_t mode, ngx_uint_t attempts, int * err_out)
Definition at line 178 of file vfs_staged.c.
References brix_sd_default_driver(), brix_vfs_ctx_path(), brix_staged_open_req_t::root_canon, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::sd, staged_alloc_handle(), staged_open_driver(), and staged_open_posix().
Referenced by brix_vfs_writer_open().
brix_vfs_staged_tmp_path()
const char * brix_vfs_staged_tmp_path (const brix_vfs_staged_t * st)
Definition at line 264 of file vfs_staged.c.
brix_vfs_staged_write()
ngx_int_t brix_vfs_staged_write (brix_vfs_staged_t * st, const void * buf, size_t len, off_t off)
Definition at line 235 of file vfs_staged.c.
References brix_vfs_pwrite_full().
Referenced by brix_http_body_staged_spooled_buf(), brix_http_body_write_to_staged(), and writer_put().
brix_vfs_unlink_at()
int brix_vfs_unlink_at (int rootfd, const char * logical, int is_dir)
Definition at line 330 of file vfs_walk.c.
References brix_unlink_beneath().
Referenced by cms_posix_apply().
brix_vfs_unlink_path()
int brix_vfs_unlink_path (ngx_log_t * log, const char * root_canon, const char * logical)
Definition at line 322 of file vfs_walk.c.
References brix_unlink_confined_canon(), and log.
Referenced by ckp_recover_one(), fhandle_unlink_staging(), s3_handle_upload_part_copy(), s3_mpu_assemble(), tpc_done_sync_fail(), and tpc_done_teardown_dst().
brix_vfs_walk()
ngx_int_t brix_vfs_walk (ngx_log_t * log, int rootfd, const char * logical, const brix_vfs_walk_opts_t * opts, brix_vfs_walk_file_cb cb, void * cookie, brix_vfs_walk_target_t * target_out, char * errmsg, size_t errsz)
Definition at line 260 of file vfs_walk.c.
References brix_stat_beneath(), BRIX_VFS_WALK_DIR, BRIX_VFS_WALK_FILE, BRIX_VFS_WALK_NONE, BRIX_VFS_WALK_OTHER, log, stat(), vfs_walk_dir(), and vfs_walk_emit_file().
Referenced by brix_ckscan_run(), and brix_scan_run().
brix_vfs_writer_abort()
void brix_vfs_writer_abort (brix_vfs_writer_t * w)
Definition at line 364 of file vfs_writer.c.
References writer_release().
Referenced by brix_ftp_ev_data_finish(), ev_eb_child_done(), fhandle_release_descriptors(), s3_chunk_decode_failed(), s3_post_write_object(), s3_put_aio_done(), s3_put_streaming(), s3put_select_codec(), s3put_stream_aws_chunked(), s3put_stream_body(), s3put_stream_offload(), s3put_stream_sync(), webdav_put_aio_done(), webdav_put_commit(), webdav_put_select_codec(), webdav_put_stream_body(), webdav_put_try_threaded(), and webdav_put_write_sync().
brix_vfs_writer_commit()
ngx_int_t brix_vfs_writer_commit (brix_vfs_writer_t * w)
Definition at line 358 of file vfs_writer.c.
References brix_vfs_writer_commit_ex().
Referenced by brix_staged_commit_handle(), ev_eb_child_done(), ev_stor_read(), s3_post_write_object(), webdav_put_aio_done(), and webdav_put_commit().
brix_vfs_writer_commit_ex()
ngx_int_t brix_vfs_writer_commit_ex (brix_vfs_writer_t * w, unsigned excl)
Definition at line 310 of file vfs_writer.c.
References brix_vfs_close(), brix_vfs_staged_abort(), brix_vfs_staged_commit(), brix_vfs_sync(), brix_vfs_unlink(), brix_wverify_free(), and writer_verify().
Referenced by brix_vfs_writer_commit(), and s3_commit_put().
brix_vfs_writer_expected_off()
off_t brix_vfs_writer_expected_off (const brix_vfs_writer_t * w)
Definition at line 277 of file vfs_writer.c.
Referenced by brix_staged_append().
brix_vfs_writer_fd()
ngx_fd_t brix_vfs_writer_fd (const brix_vfs_writer_t * w)
Definition at line 374 of file vfs_writer.c.
References brix_vfs_file_fd(), and brix_vfs_staged_fd().
Referenced by s3_chunk_aio_thread(), s3_put_streaming(), s3put_stream_sync(), webdav_put_verify_ingest_digest(), and webdav_put_write_sync().
brix_vfs_writer_open()
brix_vfs_writer_t * brix_vfs_writer_open (brix_vfs_ctx_t * ctx, unsigned flags, int verify, int * err_out)
Definition at line 75 of file vfs_writer.c.
References brix_vfs_ctx_pool_clone(), BRIX_VFS_O_ATOMIC, BRIX_VFS_O_CREATE, BRIX_VFS_O_TRUNC, BRIX_VFS_O_WRITE, brix_vfs_open(), brix_vfs_staged_open(), brix_wverify_begin(), brix_vfs_ctx_t::log, ngx_pcalloc(), brix_vfs_ctx_t::pool, writer_random_backend(), and writer_release().
Referenced by brix_ftp_ev_data_ready(), brix_open_dispatch_staged(), ev_eb_receiver_open(), s3_post_write_object(), s3put_open_target(), and webdav_put_open_target().
brix_vfs_writer_staged()
brix_vfs_staged_t * brix_vfs_writer_staged (const brix_vfs_writer_t * w)
Definition at line 389 of file vfs_writer.c.
brix_vfs_writer_write()
ngx_int_t brix_vfs_writer_write (brix_vfs_writer_t * w, const void * buf, size_t len, off_t off)
Definition at line 185 of file vfs_writer.c.
References brix_wverify_update(), and writer_put().
Referenced by brix_http_body_write_to_writer(), brix_staged_append(), ev_eb_child_read(), ev_stor_read(), s3_post_write_object(), and writer_ingest_bounce().
brix_vfs_writer_write_fd()
ngx_int_t brix_vfs_writer_write_fd (brix_vfs_writer_t * w, int src_fd, off_t src_off, size_t len, off_t dst_off)
Definition at line 244 of file vfs_writer.c.
References brix_copy_range(), brix_vfs_file_sendfile_fd(), and writer_ingest_bounce().
Referenced by brix_http_body_write_to_writer().