nginx-xrootd: src/fs/vfs/vfs_writer.c File Reference
vfs_writer.c File Reference
#include "vfs_internal.h"
#include "core/compat/wverify.h"
#include "core/compat/copy_range.h"
Data Structures
struct brix_vfs_writer_t
Functions
static int writer_random_backend (const brix_vfs_ctx_t *ctx)
static void writer_release (brix_vfs_writer_t *w)
brix_vfs_writer_t * brix_vfs_writer_open (brix_vfs_ctx_t *ctx, unsigned flags, int verify, int *err_out)
static ngx_int_t writer_put (brix_vfs_writer_t *w, const void *buf, size_t len, off_t off)
ngx_int_t brix_vfs_writer_write (brix_vfs_writer_t *w, const void *buf, size_t len, off_t off)
static ngx_int_t writer_ingest_bounce (brix_vfs_writer_t *w, int src_fd, off_t src_off, size_t len, off_t dst_off)
ngx_int_t brix_vfs_writer_write_fd (brix_vfs_writer_t *w, int src_fd, off_t src_off, size_t len, off_t dst_off)
off_t brix_vfs_writer_expected_off (const brix_vfs_writer_t *w)
static ngx_int_t writer_verify (brix_vfs_writer_t *w)
ngx_int_t brix_vfs_writer_commit_ex (brix_vfs_writer_t *w, unsigned excl)
ngx_int_t brix_vfs_writer_commit (brix_vfs_writer_t *w)
void brix_vfs_writer_abort (brix_vfs_writer_t *w)
ngx_fd_t brix_vfs_writer_fd (const brix_vfs_writer_t *w)
brix_vfs_staged_t * brix_vfs_writer_staged (const brix_vfs_writer_t *w)
Function Documentation
brix_vfs_writer_abort()
void brix_vfs_writer_abort (brix_vfs_writer_t * w)
Definition at line 364 of file vfs_writer.c.
References writer_release().
Referenced by brix_ftp_ev_data_finish(), ev_eb_child_done(), fhandle_release_descriptors(), s3_chunk_decode_failed(), s3_post_write_object(), s3_put_aio_done(), s3_put_streaming(), s3put_select_codec(), s3put_stream_aws_chunked(), s3put_stream_body(), s3put_stream_offload(), s3put_stream_sync(), webdav_put_aio_done(), webdav_put_commit(), webdav_put_select_codec(), webdav_put_stream_body(), webdav_put_try_threaded(), and webdav_put_write_sync().
brix_vfs_writer_commit()
ngx_int_t brix_vfs_writer_commit (brix_vfs_writer_t * w)
Definition at line 358 of file vfs_writer.c.
References brix_vfs_writer_commit_ex().
Referenced by brix_staged_commit_handle(), ev_eb_child_done(), ev_stor_read(), s3_post_write_object(), webdav_put_aio_done(), and webdav_put_commit().
brix_vfs_writer_commit_ex()
ngx_int_t brix_vfs_writer_commit_ex (brix_vfs_writer_t * w, unsigned excl)
Definition at line 310 of file vfs_writer.c.
References brix_vfs_close(), brix_vfs_staged_abort(), brix_vfs_staged_commit(), brix_vfs_sync(), brix_vfs_unlink(), brix_wverify_free(), and writer_verify().
Referenced by brix_vfs_writer_commit(), and s3_commit_put().
brix_vfs_writer_expected_off()
off_t brix_vfs_writer_expected_off (const brix_vfs_writer_t * w)
Definition at line 277 of file vfs_writer.c.
Referenced by brix_staged_append().
brix_vfs_writer_fd()
ngx_fd_t brix_vfs_writer_fd (const brix_vfs_writer_t * w)
Definition at line 374 of file vfs_writer.c.
References brix_vfs_file_fd(), and brix_vfs_staged_fd().
Referenced by s3_chunk_aio_thread(), s3_put_streaming(), s3put_stream_sync(), webdav_put_verify_ingest_digest(), and webdav_put_write_sync().
brix_vfs_writer_open()
brix_vfs_writer_t * brix_vfs_writer_open (brix_vfs_ctx_t * ctx, unsigned flags, int verify, int * err_out)
Definition at line 75 of file vfs_writer.c.
References brix_vfs_ctx_pool_clone(), BRIX_VFS_O_ATOMIC, BRIX_VFS_O_CREATE, BRIX_VFS_O_TRUNC, BRIX_VFS_O_WRITE, brix_vfs_open(), brix_vfs_staged_open(), brix_wverify_begin(), brix_vfs_ctx_t::log, ngx_pcalloc(), brix_vfs_ctx_t::pool, writer_random_backend(), and writer_release().
Referenced by brix_ftp_ev_data_ready(), brix_open_dispatch_staged(), ev_eb_receiver_open(), s3_post_write_object(), s3put_open_target(), and webdav_put_open_target().
brix_vfs_writer_staged()
brix_vfs_staged_t * brix_vfs_writer_staged (const brix_vfs_writer_t * w)
Definition at line 389 of file vfs_writer.c.
brix_vfs_writer_write()
ngx_int_t brix_vfs_writer_write (brix_vfs_writer_t * w, const void * buf, size_t len, off_t off)
Definition at line 185 of file vfs_writer.c.
References brix_wverify_update(), and writer_put().
Referenced by brix_http_body_write_to_writer(), brix_staged_append(), ev_eb_drain_payload(), ev_stor_read(), s3_post_write_object(), and writer_ingest_bounce().
brix_vfs_writer_write_fd()
ngx_int_t brix_vfs_writer_write_fd (brix_vfs_writer_t * w, int src_fd, off_t src_off, size_t len, off_t dst_off)
Definition at line 244 of file vfs_writer.c.
References brix_copy_range(), brix_vfs_file_sendfile_fd(), and writer_ingest_bounce().
Referenced by brix_http_body_write_to_writer().
writer_ingest_bounce()
static ngx_int_t writer_ingest_bounce (brix_vfs_writer_t * w, int src_fd, off_t src_off, size_t len, off_t dst_off) static
Definition at line 211 of file vfs_writer.c.
References brix_vfs_writer_write(), pread(), and s.
Referenced by brix_vfs_writer_write_fd().
writer_put()
static ngx_int_t writer_put (brix_vfs_writer_t * w, const void * buf, size_t len, off_t off) static
Definition at line 153 of file vfs_writer.c.
References brix_vfs_file_pwrite(), and brix_vfs_staged_write().
Referenced by brix_vfs_writer_write().
writer_random_backend()
static int writer_random_backend (const brix_vfs_ctx_t * ctx) static
Definition at line 45 of file vfs_writer.c.
References BRIX_SD_CAP_RANDOM_WRITE, brix_sd_caps(), and brix_vfs_ctx_t::sd.
Referenced by brix_vfs_writer_open().
writer_release()
static void writer_release (brix_vfs_writer_t * w) static
Definition at line 58 of file vfs_writer.c.
References brix_vfs_close(), brix_vfs_staged_abort(), and brix_wverify_free().
Referenced by brix_vfs_writer_abort(), and brix_vfs_writer_open().
writer_verify()
static ngx_int_t writer_verify (brix_vfs_writer_t * w) static
Definition at line 291 of file vfs_writer.c.
References brix_vfs_close(), BRIX_VFS_O_READ, brix_vfs_open(), and brix_vfs_wverify_check().
Referenced by brix_vfs_writer_commit_ex().