nginx-xrootd: src/fs/vfs/vfs_backend_config_ceph.c File Reference
vfs_backend_config_ceph.c File Reference
#include "vfs_backend_config_internal.h"
#include <string.h>
Data Structures
struct vfs_cephfsro_parts_t
struct vfs_cephfsro_cfg_t
Functions
static void brix_vfs_backend_config_ceph (const char *root_canon, const char *backend, const char *pool, const char *conf, const char *key_prefix)
static void brix_vfs_backend_config_cephfs_ro (const char *root_canon, const vfs_cephfsro_cfg_t *cfg)
static void brix_vfs_backend_config_tape (const char *root_canon, const char *adapter, const char *base)
static void vfs_parse_cephfsro_parts (const u_char *rest, size_t restn, const vfs_cephfsro_parts_t *parts)
ngx_int_t vfs_parse_cephfsro_origin (ngx_conf_t *cf, const char *root_canon, const ngx_str_t *sb)
ngx_int_t vfs_parse_ceph_origin (ngx_conf_t *cf, const char *root_canon, const ngx_str_t *sb)
ngx_int_t vfs_parse_rados_origin (ngx_conf_t *cf, const char *root_canon, const ngx_str_t *sb)
ngx_int_t vfs_parse_tape_origin (ngx_conf_t *cf, const char *root_canon, const ngx_str_t *sb)
Function Documentation
brix_vfs_backend_config_ceph()
static void brix_vfs_backend_config_ceph (const char * root_canon, const char * backend, const char * pool, const char * conf, const char * key_prefix) static
Definition at line 72 of file vfs_backend_config_ceph.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_entry_t::ceph_conf, brix_vfs_backend_entry_t::ceph_key_prefix, brix_vfs_backend_entry_t::ceph_pool, and brix_vfs_backend_entry_t::inst.
Referenced by vfs_parse_ceph_origin(), and vfs_parse_rados_origin().
brix_vfs_backend_config_cephfs_ro()
static void brix_vfs_backend_config_cephfs_ro (const char * root_canon, const vfs_cephfsro_cfg_t * cfg) static
Definition at line 101 of file vfs_backend_config_ceph.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_entry_t::ceph_conf, brix_vfs_backend_entry_t::ceph_data_pool, brix_vfs_backend_entry_t::ceph_pool, brix_vfs_backend_entry_t::cephfs_live, brix_vfs_backend_entry_t::cephfs_quiesced, vfs_cephfsro_cfg_t::conf, vfs_cephfsro_cfg_t::data_pool, brix_vfs_backend_entry_t::inst, vfs_cephfsro_cfg_t::live, vfs_cephfsro_cfg_t::meta_pool, ngx_memcpy, and vfs_cephfsro_cfg_t::quiesced.
Referenced by vfs_parse_cephfsro_origin().
brix_vfs_backend_config_tape()
static void brix_vfs_backend_config_tape (const char * root_canon, const char * adapter, const char * base) static
Definition at line 134 of file vfs_backend_config_ceph.c.
References brix_vfs_backend_entry_t::backend, brix_vfs_backend_entry_get_or_create(), brix_vfs_backend_entry_t::inst, ngx_memcpy, brix_vfs_backend_entry_t::origin_host, and brix_vfs_backend_entry_t::origin_path.
Referenced by vfs_parse_tape_origin().
vfs_parse_ceph_origin()
ngx_int_t vfs_parse_ceph_origin (ngx_conf_t * cf, const char * root_canon, const ngx_str_t * sb)
Definition at line 237 of file vfs_backend_config_ceph.c.
References brix_vfs_backend_config_ceph(), and c.
Referenced by brix_vfs_backend_config_str().
vfs_parse_cephfsro_origin()
ngx_int_t vfs_parse_cephfsro_origin (ngx_conf_t * cf, const char * root_canon, const ngx_str_t * sb)
Definition at line 186 of file vfs_backend_config_ceph.c.
References brix_vfs_backend_config_cephfs_ro(), vfs_cephfsro_cfg_t::conf, vfs_cephfsro_cfg_t::data_pool, vfs_cephfsro_cfg_t::live, vfs_cephfsro_cfg_t::meta_pool, vfs_cephfsro_cfg_t::quiesced, and vfs_parse_cephfsro_parts().
Referenced by brix_vfs_backend_config_str().
vfs_parse_cephfsro_parts()
static void vfs_parse_cephfsro_parts (const u_char * rest, size_t restn, const vfs_cephfsro_parts_t * parts) static
Definition at line 160 of file vfs_backend_config_ceph.c.
References c, vfs_cephfsro_parts_t::conf, vfs_cephfsro_parts_t::conf_cap, vfs_cephfsro_parts_t::data, vfs_cephfsro_parts_t::data_cap, vfs_cephfsro_parts_t::meta, vfs_cephfsro_parts_t::meta_cap, vfs_cephfsro_parts_t::query, and vfs_cephfsro_parts_t::query_cap.
Referenced by vfs_parse_cephfsro_origin().
vfs_parse_rados_origin()
ngx_int_t vfs_parse_rados_origin (ngx_conf_t * cf, const char * root_canon, const ngx_str_t * sb)
Definition at line 288 of file vfs_backend_config_ceph.c.
References brix_vfs_backend_config_ceph(), and ngx_memcpy.
Referenced by brix_vfs_backend_config_str().
vfs_parse_tape_origin()
ngx_int_t vfs_parse_tape_origin (ngx_conf_t * cf, const char * root_canon, const ngx_str_t * sb)
Definition at line 331 of file vfs_backend_config_ceph.c.
References brix_vfs_backend_config_tape(), and ngx_memcpy.
Referenced by brix_vfs_backend_config_str().