nginx-xrootd: src/fs/vfs/vfs_deleg_bind.c File Reference
vfs_deleg_bind.c File Reference
#include "vfs_internal.h"
Functions
void brix_vfs_ctx_bind_backend_deleg (brix_vfs_ctx_t *vctx, brix_deleg_live_t *live)
void brix_vfs_deleg_set_exchange (brix_vfs_ctx_t *vctx, const ngx_str_t *endpoint, const ngx_str_t *client_id, const ngx_str_t *client_secret, const ngx_str_t *audience)
ngx_int_t brix_vfs_deleg_bind (ngx_pool_t *pool, brix_vfs_ctx_t *vctx, enum brix_cred_mode mode, const ngx_str_t *bearer, const ngx_str_t *proxy_pem)
enum brix_cred_mode brix_vfs_backend_mode (brix_vfs_ctx_t *vctx)
int brix_vfs_backend_accepts_proxy (brix_vfs_ctx_t *vctx)
void brix_vfs_deleg_snapshot (const brix_vfs_ctx_t *vctx, enum brix_cred_mode *mode, ngx_str_t *bearer)
Function Documentation
brix_vfs_backend_accepts_proxy()
int brix_vfs_backend_accepts_proxy (brix_vfs_ctx_t * vctx)
Definition at line 174 of file vfs_deleg_bind.c.
References brix_sd_cred_accept(), BRIX_SD_CRED_PROXY_PEM, brix_vfs_ns_leaf(), and brix_vfs_ctx_t::sd.
Referenced by brix_ftp_ev_vfs_ctx().
brix_vfs_backend_mode()
enum brix_cred_mode brix_vfs_backend_mode (brix_vfs_ctx_t * vctx)
Definition at line 151 of file vfs_deleg_bind.c.
References BRIX_CRED_SELECT, and brix_vfs_ctx_t::deleg_live.
Referenced by brix_vfs_cred_gate_active(), and vfs_cred_live_bag().
brix_vfs_ctx_bind_backend_deleg()
void brix_vfs_ctx_bind_backend_deleg (brix_vfs_ctx_t * vctx, brix_deleg_live_t * live)
Definition at line 33 of file vfs_deleg_bind.c.
References brix_vfs_ctx_t::deleg_live.
Referenced by brix_vfs_deleg_bind().
brix_vfs_deleg_bind()
ngx_int_t brix_vfs_deleg_bind (ngx_pool_t * pool, brix_vfs_ctx_t * vctx, enum brix_cred_mode mode, const ngx_str_t * bearer, const ngx_str_t * proxy_pem)
Definition at line 103 of file vfs_deleg_bind.c.
References BRIX_CRED_SELECT, brix_vfs_ctx_bind_backend_deleg(), and ngx_pcalloc().
Referenced by brix_ftp_ev_vfs_ctx(), brix_root_vfs_bind_deleg(), fattr_recurse_bind_deleg(), s3_vfs_bind_deleg(), and webdav_vfs_bind_deleg().
brix_vfs_deleg_set_exchange()
void brix_vfs_deleg_set_exchange (brix_vfs_ctx_t * vctx, const ngx_str_t * endpoint, const ngx_str_t * client_id, const ngx_str_t * client_secret, const ngx_str_t * audience)
Definition at line 58 of file vfs_deleg_bind.c.
References brix_vfs_ctx_t::deleg_live.
brix_vfs_deleg_snapshot()
void brix_vfs_deleg_snapshot (const brix_vfs_ctx_t * vctx, enum brix_cred_mode * mode, ngx_str_t * bearer)
Definition at line 197 of file vfs_deleg_bind.c.
References BRIX_CRED_SELECT, and brix_vfs_ctx_t::deleg_live.
Referenced by fattr_list_recurse().