nginx-xrootd: src/fs/vfs/vfs_deleg.c File Reference
vfs_deleg.c File Reference
#include "vfs_internal.h"
#include "net/proxy/gsi_upstream.h"
#include "auth/s3/sts.h"
#include "auth/krb5/forward.h"
#include <openssl/bio.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
Data Structures
struct brix_deleg_temp_t
Functions
static void brix_vfs_deleg_temp_cleanup (void *data)
void brix_vfs_ctx_bind_backend_deleg (brix_vfs_ctx_t *vctx, brix_deleg_live_t *live)
void brix_vfs_deleg_set_exchange (brix_vfs_ctx_t *vctx, const ngx_str_t *endpoint, const ngx_str_t *client_id, const ngx_str_t *client_secret, const ngx_str_t *audience)
ngx_int_t brix_vfs_deleg_bind (ngx_pool_t *pool, brix_vfs_ctx_t *vctx, enum brix_cred_mode mode, const ngx_str_t *bearer, const ngx_str_t *proxy_pem)
enum brix_cred_mode brix_vfs_backend_mode (brix_vfs_ctx_t *vctx)
int brix_vfs_backend_accepts_proxy (brix_vfs_ctx_t *vctx)
void brix_vfs_deleg_snapshot (const brix_vfs_ctx_t *vctx, enum brix_cred_mode *mode, ngx_str_t *bearer)
static int brix_vfs_deleg_pem_is_valid (const u_char *pem, size_t len)
static ngx_int_t brix_vfs_deleg_deny (brix_vfs_ctx_t *ctx, int *use_cred, int *err_out)
static ngx_int_t brix_vfs_deleg_bearer (brix_vfs_ctx_t *ctx, brix_sd_cred_t *cred, int *use_cred)
static ngx_int_t brix_vfs_deleg_exchange (brix_vfs_ctx_t *ctx, brix_sd_cred_t *cred, int *use_cred, int *err_out)
static ngx_int_t brix_vfs_deleg_proxy (brix_vfs_ctx_t *ctx, brix_sd_cred_t *cred, int *use_cred, int *err_out)
ngx_int_t brix_vfs_deleg_live_cred (brix_vfs_ctx_t *ctx, brix_sd_cred_t *cred, int *use_cred, int *err_out)
ngx_int_t brix_vfs_deleg_sts_cred (brix_vfs_ctx_t *ctx, const brix_s3_sts_conf_t *cf, brix_sd_cred_t *cred, int *use_cred, int *err_out)
ngx_int_t brix_vfs_deleg_krb5_token (brix_vfs_ctx_t *ctx, void *deleg_gss_cred, const char *origin_service_princ, ngx_str_t *out_token)
Function Documentation
brix_vfs_backend_accepts_proxy()
int brix_vfs_backend_accepts_proxy (brix_vfs_ctx_t * vctx)
Definition at line 227 of file vfs_deleg.c.
References brix_sd_cred_accept(), BRIX_SD_CRED_PROXY_PEM, brix_vfs_ns_leaf(), and brix_vfs_ctx_t::sd.
Referenced by brix_ftp_ev_vfs_ctx().
brix_vfs_backend_mode()
enum brix_cred_mode brix_vfs_backend_mode (brix_vfs_ctx_t * vctx)
Definition at line 204 of file vfs_deleg.c.
References BRIX_CRED_SELECT, and brix_vfs_ctx_t::deleg_live.
Referenced by brix_vfs_cred_gate_active(), and vfs_cred_live_bag().
brix_vfs_ctx_bind_backend_deleg()
void brix_vfs_ctx_bind_backend_deleg (brix_vfs_ctx_t * vctx, brix_deleg_live_t * live)
Definition at line 86 of file vfs_deleg.c.
References brix_vfs_ctx_t::deleg_live.
Referenced by brix_vfs_deleg_bind().
brix_vfs_deleg_bearer()
static ngx_int_t brix_vfs_deleg_bearer (brix_vfs_ctx_t * ctx, brix_sd_cred_t * cred, int * use_cred) static
Definition at line 349 of file vfs_deleg.c.
References brix_sd_cred_t::bearer, BRIX_CRED_PASSTHROUGH, brix_vfs_ctx_t::deleg_live, and brix_sd_cred_t::mode.
Referenced by brix_vfs_deleg_live_cred().
brix_vfs_deleg_bind()
ngx_int_t brix_vfs_deleg_bind (ngx_pool_t * pool, brix_vfs_ctx_t * vctx, enum brix_cred_mode mode, const ngx_str_t * bearer, const ngx_str_t * proxy_pem)
Definition at line 156 of file vfs_deleg.c.
References BRIX_CRED_SELECT, brix_vfs_ctx_bind_backend_deleg(), and ngx_pcalloc().
Referenced by brix_ftp_ev_vfs_ctx(), brix_root_vfs_bind_deleg(), fattr_recurse_bind_deleg(), s3_vfs_bind_deleg(), and webdav_vfs_bind_deleg().
brix_vfs_deleg_deny()
static ngx_int_t brix_vfs_deleg_deny (brix_vfs_ctx_t * ctx, int * use_cred, int * err_out) static
Definition at line 320 of file vfs_deleg.c.
References brix_vfs_ctx_t::storage_cred_deny.
Referenced by brix_vfs_deleg_exchange(), brix_vfs_deleg_live_cred(), brix_vfs_deleg_proxy(), and brix_vfs_deleg_sts_cred().
brix_vfs_deleg_exchange()
static ngx_int_t brix_vfs_deleg_exchange (brix_vfs_ctx_t * ctx, brix_sd_cred_t * cred, int * use_cred, int * err_out) static
Definition at line 378 of file vfs_deleg.c.
References brix_sd_cred_t::bearer, BRIX_CRED_EXCHANGE, brix_token_exchange(), brix_vfs_deleg_deny(), brix_vfs_ctx_t::deleg_live, brix_vfs_ctx_t::log, brix_sd_cred_t::mode, and brix_vfs_ctx_t::pool.
Referenced by brix_vfs_deleg_live_cred().
brix_vfs_deleg_krb5_token()
ngx_int_t brix_vfs_deleg_krb5_token (brix_vfs_ctx_t * ctx, void * deleg_gss_cred, const char * origin_service_princ, ngx_str_t * out_token)
Definition at line 634 of file vfs_deleg.c.
References brix_krb5_deleg_to_origin(), brix_krb5_forward_available(), brix_vfs_ctx_t::log, and brix_vfs_ctx_t::pool.
brix_vfs_deleg_live_cred()
ngx_int_t brix_vfs_deleg_live_cred (brix_vfs_ctx_t * ctx, brix_sd_cred_t * cred, int * use_cred, int * err_out)
Definition at line 508 of file vfs_deleg.c.
References BRIX_CRED_EXCHANGE, brix_sd_cred_accept(), BRIX_SD_CRED_BEARER, BRIX_SD_CRED_PROXY_PEM, brix_vfs_deleg_bearer(), brix_vfs_deleg_deny(), brix_vfs_deleg_exchange(), brix_vfs_deleg_proxy(), brix_vfs_ns_leaf(), brix_vfs_ctx_t::deleg_live, and brix_vfs_ctx_t::sd.
Referenced by vfs_cred_live_bag().
brix_vfs_deleg_pem_is_valid()
static int brix_vfs_deleg_pem_is_valid (const u_char * pem, size_t len) static
Definition at line 284 of file vfs_deleg.c.
Referenced by brix_vfs_deleg_proxy().
brix_vfs_deleg_proxy()
static ngx_int_t brix_vfs_deleg_proxy (brix_vfs_ctx_t * ctx, brix_sd_cred_t * cred, int * use_cred, int * err_out) static
Definition at line 433 of file vfs_deleg.c.
References BRIX_CRED_PASSTHROUGH, brix_proxy_gsi_write_pem_temp(), brix_vfs_deleg_deny(), brix_vfs_deleg_pem_is_valid(), brix_vfs_deleg_temp_cleanup(), brix_vfs_ctx_t::deleg_live, brix_vfs_ctx_t::identity, brix_vfs_ctx_t::log, brix_sd_cred_t::mode, ngx_memcpy, ngx_pnalloc(), brix_deleg_temp_t::path, brix_vfs_ctx_t::pool, brix_identity_t::subject, and brix_sd_cred_t::x509_proxy.
Referenced by brix_vfs_deleg_live_cred().
brix_vfs_deleg_set_exchange()
void brix_vfs_deleg_set_exchange (brix_vfs_ctx_t * vctx, const ngx_str_t * endpoint, const ngx_str_t * client_id, const ngx_str_t * client_secret, const ngx_str_t * audience)
Definition at line 111 of file vfs_deleg.c.
References brix_vfs_ctx_t::deleg_live.
brix_vfs_deleg_snapshot()
void brix_vfs_deleg_snapshot (const brix_vfs_ctx_t * vctx, enum brix_cred_mode * mode, ngx_str_t * bearer)
Definition at line 250 of file vfs_deleg.c.
References BRIX_CRED_SELECT, and brix_vfs_ctx_t::deleg_live.
Referenced by fattr_list_recurse().
brix_vfs_deleg_sts_cred()
ngx_int_t brix_vfs_deleg_sts_cred (brix_vfs_ctx_t * ctx, const brix_s3_sts_conf_t * cf, brix_sd_cred_t * cred, int * use_cred, int * err_out)
Definition at line 579 of file vfs_deleg.c.
References BRIX_CRED_EXCHANGE, brix_s3_sts_assume(), brix_vfs_deleg_deny(), brix_vfs_ctx_t::identity, brix_vfs_ctx_t::log, brix_sd_cred_t::mode, brix_vfs_ctx_t::pool, brix_s3_sts_conf_t::region, brix_sd_cred_t::s3_ak, brix_sd_cred_t::s3_region, and brix_sd_cred_t::s3_sk.
brix_vfs_deleg_temp_cleanup()
static void brix_vfs_deleg_temp_cleanup (void * data) static
Definition at line 61 of file vfs_deleg.c.
References brix_deleg_temp_t::path.
Referenced by brix_vfs_deleg_proxy().