nginx-xrootd: src/fs/vfs/vfs_backend_config_internal.h File Reference
vfs_backend_config_internal.h File Reference
#include "vfs_backend_internal.h"
Data Structures
struct vfs_origin_parse_t
Functions
ngx_int_t vfs_parse_cephfsro_origin (ngx_conf_t *cf, const char *root_canon, const ngx_str_t *sb)
ngx_int_t vfs_parse_ceph_origin (ngx_conf_t *cf, const char *root_canon, const ngx_str_t *sb)
ngx_int_t vfs_parse_rados_origin (ngx_conf_t *cf, const char *root_canon, const ngx_str_t *sb)
ngx_int_t vfs_parse_tape_origin (ngx_conf_t *cf, const char *root_canon, const ngx_str_t *sb)
ngx_int_t vfs_parse_http_origin_list (ngx_conf_t *cf, const char *root_canon, const ngx_str_t *sb)
ngx_int_t vfs_parse_s3_origin (ngx_conf_t *cf, const char *root_canon, const ngx_str_t *sb)
ngx_int_t vfs_parse_xroot_or_driver_origin (ngx_conf_t *cf, const char *root_canon, const ngx_str_t *sb, size_t block_size, int family)
Function Documentation
vfs_parse_ceph_origin()
ngx_int_t vfs_parse_ceph_origin (ngx_conf_t * cf, const char * root_canon, const ngx_str_t * sb)
Definition at line 237 of file vfs_backend_config_ceph.c.
References brix_vfs_backend_config_ceph(), and c.
Referenced by brix_vfs_backend_config_str().
vfs_parse_cephfsro_origin()
ngx_int_t vfs_parse_cephfsro_origin (ngx_conf_t * cf, const char * root_canon, const ngx_str_t * sb)
Definition at line 186 of file vfs_backend_config_ceph.c.
References brix_vfs_backend_config_cephfs_ro(), vfs_cephfsro_cfg_t::conf, vfs_cephfsro_cfg_t::data_pool, vfs_cephfsro_cfg_t::live, vfs_cephfsro_cfg_t::meta_pool, vfs_cephfsro_cfg_t::quiesced, and vfs_parse_cephfsro_parts().
Referenced by brix_vfs_backend_config_str().
vfs_parse_http_origin_list()
ngx_int_t vfs_parse_http_origin_list (ngx_conf_t * cf, const char * root_canon, const ngx_str_t * sb)
Definition at line 215 of file vfs_backend_config_http.c.
References vfs_origin_parse_t::base, vfs_origin_parse_t::base_cap, brix_vfs_backend_config_http(), vfs_origin_parse_t::host, vfs_origin_parse_t::host_cap, vfs_origin_parse_t::port, vfs_origin_parse_t::tls, vfs_backend_add_http_endpoint(), vfs_backend_is_http_url(), and vfs_parse_http_origin().
Referenced by brix_vfs_backend_config_str().
vfs_parse_rados_origin()
ngx_int_t vfs_parse_rados_origin (ngx_conf_t * cf, const char * root_canon, const ngx_str_t * sb)
Definition at line 288 of file vfs_backend_config_ceph.c.
References brix_vfs_backend_config_ceph(), and ngx_memcpy.
Referenced by brix_vfs_backend_config_str().
vfs_parse_s3_origin()
ngx_int_t vfs_parse_s3_origin (ngx_conf_t * cf, const char * root_canon, const ngx_str_t * sb)
Definition at line 173 of file vfs_backend_config_s3.c.
References vfs_origin_parse_t::base, vfs_origin_parse_t::base_cap, brix_vfs_backend_config_s3(), vfs_origin_parse_t::host, vfs_origin_parse_t::host_cap, vfs_origin_parse_t::port, and vfs_parse_s3_url().
Referenced by brix_vfs_backend_config_str().
vfs_parse_tape_origin()
ngx_int_t vfs_parse_tape_origin (ngx_conf_t * cf, const char * root_canon, const ngx_str_t * sb)
Definition at line 331 of file vfs_backend_config_ceph.c.
References brix_vfs_backend_config_tape(), and ngx_memcpy.
Referenced by brix_vfs_backend_config_str().
vfs_parse_xroot_or_driver_origin()
ngx_int_t vfs_parse_xroot_or_driver_origin (ngx_conf_t * cf, const char * root_canon, const ngx_str_t * sb, size_t block_size, int family)
Definition at line 208 of file vfs_backend_config_s3.c.
References brix_vfs_backend_config(), brix_vfs_backend_config_xroot(), and ngx_memcpy.
Referenced by brix_vfs_backend_config_str().