nginx-xrootd: src/fs/vfs/vfs_io_core_dirlist.c File Reference
vfs_io_core_dirlist.c File Reference
#include "vfs_internal.h"
#include "vfs_io_core.h"
#include "vfs_io_core_internal.h"
#include "fs/backend/sd.h"
#include "fs/core/vfs_core.h"
#include "fs/backend/csi_tagstore.h"
#include "core/aio/aio.h"
#include "protocols/root/dirlist/dcksm.h"
#include "fs/path/path.h"
#include "protocols/root/protocol/dirlist_fmt.h"
#include "protocols/root/read/read.h"
#include "protocols/root/response/response.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include <openssl/evp.h>
Functions
static void brix_vfs_io_dirlist_fail (brix_vfs_job_t *job, int err, const char *message)
static ngx_flag_t brix_vfs_io_dirlist_name_unsafe (const char *name)
static void brix_vfs_io_dirlist_flush_chunk (brix_vfs_job_t *job, u_char *out, size_t *base, size_t cdpos)
static ngx_int_t brix_vfs_io_dirlist_need_new_chunk (brix_vfs_job_t *job, u_char *out, size_t *base, u_char **cdata, size_t *cdpos, size_t need)
static ngx_int_t brix_vfs_io_dirlist_stat_entry (brix_vfs_job_t *job, int dfd, const char *name, char *statbuf, size_t statbuf_cap, char *cksum_token, size_t cksum_token_cap, size_t *need)
static void brix_vfs_io_dirlist_emit_entry (brix_vfs_job_t *job, u_char *cdata, size_t *cdpos, const char *name, size_t nlen, const char *statbuf, const char *cksum_token)
void brix_vfs_io_execute_opendir (brix_vfs_job_t *job)
Function Documentation
brix_vfs_io_dirlist_emit_entry()
static void brix_vfs_io_dirlist_emit_entry (brix_vfs_job_t * job, u_char * cdata, size_t * cdpos, const char * name, size_t nlen, const char * statbuf, const char * cksum_token) static
Definition at line 181 of file vfs_io_core_dirlist.c.
References BRIX_VFS_DIRLIST_CHUNK_CAP, name, ngx_memcpy, brix_vfs_job_t::want_cksum, and brix_vfs_job_t::want_stat.
Referenced by brix_vfs_io_execute_opendir().
brix_vfs_io_dirlist_fail()
static void brix_vfs_io_dirlist_fail (brix_vfs_job_t * job, int err, const char * message) static
Definition at line 50 of file vfs_io_core_dirlist.c.
References brix_vfs_io_set_error_message(), brix_vfs_job_t::io_errno, and brix_vfs_job_t::nio.
Referenced by brix_vfs_io_dirlist_need_new_chunk(), and brix_vfs_io_execute_opendir().
brix_vfs_io_dirlist_flush_chunk()
static void brix_vfs_io_dirlist_flush_chunk (brix_vfs_job_t * job, u_char * out, size_t * base, size_t cdpos) static
Definition at line 91 of file vfs_io_core_dirlist.c.
References brix_build_resp_hdr(), kXR_oksofar, brix_vfs_job_t::streamid, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_vfs_io_dirlist_need_new_chunk().
brix_vfs_io_dirlist_name_unsafe()
static ngx_flag_t brix_vfs_io_dirlist_name_unsafe (const char * name) static
Definition at line 63 of file vfs_io_core_dirlist.c.
References name.
Referenced by brix_vfs_io_execute_opendir().
brix_vfs_io_dirlist_need_new_chunk()
static ngx_int_t brix_vfs_io_dirlist_need_new_chunk (brix_vfs_job_t * job, u_char * out, size_t * base, u_char ** cdata, size_t * cdpos, size_t need) static
Definition at line 103 of file vfs_io_core_dirlist.c.
References BRIX_VFS_DIRLIST_CHUNK_CAP, brix_vfs_io_dirlist_fail(), brix_vfs_io_dirlist_flush_chunk(), brix_vfs_job_t::buf_cap, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_vfs_io_execute_opendir().
brix_vfs_io_dirlist_stat_entry()
static ngx_int_t brix_vfs_io_dirlist_stat_entry (brix_vfs_job_t * job, int dfd, const char * name, char * statbuf, size_t statbuf_cap, char * cksum_token, size_t cksum_token_cap, size_t * need) static
Definition at line 132 of file vfs_io_core_dirlist.c.
References brix_dirlist_checksum_token(), brix_dirlist_make_dcksm_stat_body(), brix_make_stat_body(), brix_vfs_job_t::cksum_algo, fstatat(), brix_vfs_job_t::log, name, brix_vfs_job_t::path, PATH_MAX, stat(), brix_vfs_job_t::want_cksum, and brix_vfs_job_t::want_stat.
Referenced by brix_vfs_io_execute_opendir().
brix_vfs_io_execute_opendir()
void brix_vfs_io_execute_opendir (brix_vfs_job_t * job)
Definition at line 217 of file vfs_io_core_dirlist.c.
References brix_build_resp_hdr(), BRIX_DSTAT_LEADIN, BRIX_DSTAT_LEADIN_LEN, BRIX_VFS_DIRLIST_CHUNK_CAP, brix_vfs_io_dirlist_emit_entry(), brix_vfs_io_dirlist_fail(), brix_vfs_io_dirlist_name_unsafe(), brix_vfs_io_dirlist_need_new_chunk(), brix_vfs_io_dirlist_stat_entry(), brix_vfs_job_t::buf, brix_vfs_job_t::buf_cap, close(), kXR_ok, name, ngx_memcpy, brix_vfs_job_t::nio, brix_vfs_job_t::out_size, brix_vfs_job_t::rootfd, brix_vfs_job_t::streamid, brix_vfs_job_t::want_stat, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_vfs_io_execute().