nginx-xrootd: src/fs/vfs/vfs_copy.c File Reference
vfs_copy.c File Reference
#include "vfs_internal.h"
Functions
static ngx_int_t brix_vfs_copy_fail (brix_vfs_ctx_t *ctx, const char *src, int err, uint64_t start)
static ngx_int_t brix_vfs_copy_driver (brix_vfs_ctx_t *ctx, const char *src, const char *dst_resolved, const brix_vfs_copy_opts_t *opts, uint64_t start)
static size_t brix_vfs_copy_ns_bytes (brix_vfs_ctx_t *ctx, const char *dst_resolved)
static ngx_int_t brix_vfs_copy_ns (brix_vfs_ctx_t *ctx, const char *src, const char *dst_resolved, const brix_vfs_copy_opts_t *opts, uint64_t start)
ngx_int_t brix_vfs_copy (brix_vfs_ctx_t *ctx, const char *dst_resolved, const brix_vfs_copy_opts_t *opts)
Function Documentation
brix_vfs_copy()
ngx_int_t brix_vfs_copy (brix_vfs_ctx_t * ctx, const char * dst_resolved, const brix_vfs_copy_opts_t * opts)
Definition at line 196 of file vfs_copy.c.
References brix_vfs_copy_driver(), brix_vfs_copy_fail(), brix_vfs_copy_ns(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_now_ns(), brix_vfs_require_write(), and brix_vfs_ctx_t::root_canon.
Referenced by s3_handle_copy_object(), and webdav_copy_do_file().
brix_vfs_copy_driver()
static ngx_int_t brix_vfs_copy_driver (brix_vfs_ctx_t * ctx, const char * src, const char * dst_resolved, const brix_vfs_copy_opts_t * opts, uint64_t start) static
Definition at line 63 of file vfs_copy.c.
References BRIX_METRIC_OP_COPY, brix_sd_server_copy_maybe_cred(), brix_sd_stat_maybe_cred(), brix_sd_ucred_wipe(), brix_vfs_copy_fail(), brix_vfs_cred_gate_active(), brix_vfs_ctx_driver(), brix_vfs_export_relative(), brix_vfs_ns_cred(), brix_vfs_ns_leaf(), brix_vfs_observe_ctx_op(), brix_vfs_copy_opts_t::overwrite, s, and brix_vfs_ctx_t::sd.
Referenced by brix_vfs_copy().
brix_vfs_copy_fail()
static ngx_int_t brix_vfs_copy_fail (brix_vfs_ctx_t * ctx, const char * src, int err, uint64_t start) static
Definition at line 37 of file vfs_copy.c.
References BRIX_METRIC_OP_COPY, and brix_vfs_observe_ctx_op().
Referenced by brix_vfs_copy(), brix_vfs_copy_driver(), and brix_vfs_copy_ns().
brix_vfs_copy_ns()
static ngx_int_t brix_vfs_copy_ns (brix_vfs_ctx_t * ctx, const char * src, const char * dst_resolved, const brix_vfs_copy_opts_t * opts, uint64_t start) static
Definition at line 158 of file vfs_copy.c.
References BRIX_METRIC_OP_COPY, brix_ns_local_copy(), BRIX_NS_OK, brix_vfs_copy_fail(), brix_vfs_copy_ns_bytes(), brix_vfs_ns_status_errno(), brix_vfs_observe_ctx_op(), brix_vfs_ctx_t::log, brix_ns_copy_opts_t::overwrite, brix_vfs_copy_opts_t::overwrite, brix_ns_copy_opts_t::overwrite_dirs, brix_vfs_copy_opts_t::overwrite_dirs, brix_ns_copy_opts_t::preserve_xattrs, brix_vfs_copy_opts_t::preserve_xattrs, brix_ns_copy_opts_t::recursive, brix_vfs_copy_opts_t::recursive, brix_vfs_ctx_t::root_canon, brix_ns_copy_opts_t::staged_commit, brix_vfs_copy_opts_t::staged_commit, brix_ns_result_t::status, and brix_ns_result_t::sys_errno.
Referenced by brix_vfs_copy().
brix_vfs_copy_ns_bytes()
static size_t brix_vfs_copy_ns_bytes (brix_vfs_ctx_t * ctx, const char * dst_resolved) static
Definition at line 132 of file vfs_copy.c.
References brix_lstat_confined_canon(), brix_vfs_ctx_t::log, brix_vfs_ctx_t::root_canon, and stat().
Referenced by brix_vfs_copy_ns().