nginx-xrootd: src/fs/vfs/vfs_io_core.h File Reference
vfs_io_core.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include "fs/backend/sd.h"
#include <stdint.h>
#include <sys/types.h>
Data Structures
struct brix_vfs_readv_seg_t
struct brix_vfs_writev_seg_t
struct brix_vfs_job_t
Enumerations
enum brix_vfs_io_op_e {
BRIX_VFS_IO_READ = 0 , BRIX_VFS_IO_WRITE , BRIX_VFS_IO_PGREAD , BRIX_VFS_IO_READV ,
BRIX_VFS_IO_WRITEV , BRIX_VFS_IO_SYNC , BRIX_VFS_IO_TRUNCATE , BRIX_VFS_IO_OPENDIR
}
Functions
static void brix_vfs_job_read_init (brix_vfs_job_t *job, ngx_fd_t fd, off_t offset, size_t length, u_char *dst, size_t dst_cap, unsigned want_pgcrc)
static brix_sd_obj_t * brix_vfs_effective_obj (brix_sd_obj_t *src, ngx_fd_t fd, brix_sd_obj_t *scratch)
static void brix_vfs_job_set_obj (brix_vfs_job_t *job, const brix_sd_obj_t *obj)
static void brix_vfs_job_write_init (brix_vfs_job_t *job, ngx_fd_t fd, off_t offset, const u_char *src, size_t len)
static void brix_vfs_job_sync_init (brix_vfs_job_t *job, ngx_fd_t fd)
static void brix_vfs_job_truncate_init (brix_vfs_job_t *job, ngx_fd_t fd, off_t length)
static void brix_vfs_job_opendir_init (brix_vfs_job_t *job, int rootfd, u_char *response, size_t response_cap, const u_char streamid[2], ngx_flag_t want_stat, ngx_flag_t want_cksum, const char *path, const char *cksum_algo, ngx_log_t *log, char *err_msg, size_t err_msg_cap)
void brix_vfs_io_execute (brix_vfs_job_t *job)
Enumeration Type Documentation
brix_vfs_io_op_e
enum brix_vfs_io_op_e
Enumerator
BRIX_VFS_IO_READ
BRIX_VFS_IO_WRITE
BRIX_VFS_IO_PGREAD
BRIX_VFS_IO_READV
BRIX_VFS_IO_WRITEV
BRIX_VFS_IO_SYNC
BRIX_VFS_IO_TRUNCATE
BRIX_VFS_IO_OPENDIR
Definition at line 35 of file vfs_io_core.h.
Function Documentation
brix_vfs_effective_obj()
static brix_sd_obj_t * brix_vfs_effective_obj (brix_sd_obj_t * src, ngx_fd_t fd, brix_sd_obj_t * scratch) inline static
Definition at line 132 of file vfs_io_core.h.
References brix_sd_posix_wrap().
Referenced by brix_handle_pgread(), brix_readv_read_segments(), brix_vfs_io_execute_pgread(), brix_vfs_io_execute_read(), brix_vfs_io_execute_sync(), brix_vfs_io_execute_truncate(), and brix_vfs_io_write_counted().
brix_vfs_io_execute()
void brix_vfs_io_execute (brix_vfs_job_t * job)
Definition at line 727 of file vfs_io_core.c.
References brix_vfs_io_account(), brix_vfs_io_execute_opendir(), brix_vfs_io_execute_pgread(), brix_vfs_io_execute_read(), brix_vfs_io_execute_readv(), brix_vfs_io_execute_sync(), brix_vfs_io_execute_truncate(), brix_vfs_io_execute_write(), brix_vfs_io_execute_writev(), BRIX_VFS_IO_OPENDIR, BRIX_VFS_IO_PGREAD, BRIX_VFS_IO_READ, BRIX_VFS_IO_READV, brix_vfs_io_reset_outputs(), BRIX_VFS_IO_SYNC, BRIX_VFS_IO_TRUNCATE, BRIX_VFS_IO_WRITE, BRIX_VFS_IO_WRITEV, brix_vfs_job_t::io_errno, brix_vfs_job_t::nio, and brix_vfs_job_t::op.
Referenced by brix_dirlist_aio_thread(), brix_handle_pgread(), brix_handle_pgwrite(), brix_handle_read(), brix_handle_readv(), brix_handle_sync(), brix_handle_truncate(), brix_handle_write(), brix_handle_writev(), brix_pgread_aio_thread(), brix_read_aio_thread(), brix_read_compressed(), brix_read_window_pump(), brix_readv_aio_thread(), brix_vfs_sync(), brix_vfs_truncate(), brix_write_aio_thread(), brix_write_compressed(), brix_writev_write_aio_thread(), ckp_recover_one(), ckp_rollback(), ckp_xeq_truncate(), ckp_xeq_vfs_write_full(), and tpc_stream_to_dst().
brix_vfs_job_opendir_init()
static void brix_vfs_job_opendir_init (brix_vfs_job_t * job, int rootfd, u_char * response, size_t response_cap, const u_char streamid[2], ngx_flag_t want_stat, ngx_flag_t want_cksum, const char * path, const char * cksum_algo, ngx_log_t * log, char * err_msg, size_t err_msg_cap) inline static
Definition at line 226 of file vfs_io_core.h.
References BRIX_VFS_IO_OPENDIR, brix_vfs_job_t::buf, brix_vfs_job_t::buf_cap, brix_vfs_job_t::cksum_algo, brix_vfs_job_t::err_msg, brix_vfs_job_t::err_msg_cap, log, brix_vfs_job_t::log, brix_vfs_job_t::op, brix_vfs_job_t::path, brix_vfs_job_t::rootfd, brix_vfs_job_t::streamid, brix_vfs_job_t::want_cksum, and brix_vfs_job_t::want_stat.
Referenced by brix_dirlist_aio_thread().
brix_vfs_job_read_init()
static void brix_vfs_job_read_init (brix_vfs_job_t * job, ngx_fd_t fd, off_t offset, size_t length, u_char * dst, size_t dst_cap, unsigned want_pgcrc) inline static
Definition at line 115 of file vfs_io_core.h.
References BRIX_VFS_IO_READ, brix_vfs_job_t::buf, brix_vfs_job_t::buf_cap, brix_vfs_job_t::fd, brix_vfs_job_t::length, brix_vfs_job_t::offset, brix_vfs_job_t::op, and brix_vfs_job_t::want_pgcrc.
Referenced by brix_handle_pgread(), brix_handle_read(), brix_pgread_aio_thread(), brix_read_aio_thread(), brix_read_compressed(), and brix_read_window_pump().
brix_vfs_job_set_obj()
static void brix_vfs_job_set_obj (brix_vfs_job_t * job, const brix_sd_obj_t * obj) inline static
Definition at line 147 of file vfs_io_core.h.
References brix_vfs_job_t::obj.
Referenced by brix_handle_pgread(), brix_handle_pgwrite(), brix_handle_read(), brix_handle_sync(), brix_handle_truncate(), brix_handle_write(), brix_handle_writev(), brix_pgread_aio_thread(), brix_read_aio_thread(), and brix_write_aio_thread().
brix_vfs_job_sync_init()
static void brix_vfs_job_sync_init (brix_vfs_job_t * job, ngx_fd_t fd) inline static
Definition at line 188 of file vfs_io_core.h.
References BRIX_VFS_IO_SYNC, brix_vfs_job_t::fd, and brix_vfs_job_t::op.
Referenced by brix_handle_sync(), brix_handle_writev(), brix_vfs_sync(), ckp_recover_one(), and tpc_stream_to_dst().
brix_vfs_job_truncate_init()
static void brix_vfs_job_truncate_init (brix_vfs_job_t * job, ngx_fd_t fd, off_t length) inline static
Definition at line 206 of file vfs_io_core.h.
References BRIX_VFS_IO_TRUNCATE, brix_vfs_job_t::fd, brix_vfs_job_t::offset, and brix_vfs_job_t::op.
Referenced by brix_handle_truncate(), brix_vfs_truncate(), ckp_rollback(), and ckp_xeq_truncate().
brix_vfs_job_write_init()
static void brix_vfs_job_write_init (brix_vfs_job_t * job, ngx_fd_t fd, off_t offset, const u_char * src, size_t len) inline static
Definition at line 165 of file vfs_io_core.h.
References BRIX_VFS_IO_WRITE, brix_vfs_job_t::buf, brix_vfs_job_t::buf_cap, brix_vfs_job_t::fd, brix_vfs_job_t::length, brix_vfs_job_t::offset, and brix_vfs_job_t::op.
Referenced by brix_handle_pgwrite(), brix_handle_write(), brix_handle_writev(), brix_write_aio_thread(), brix_write_compressed(), ckp_xeq_vfs_write_full(), and tpc_stream_to_dst().