nginx-xrootd: src/fs/vfs/vfs_dir.c File Reference
vfs_dir.c File Reference
#include "vfs_internal.h"
#include "core/compat/log_diag.h"
Functions
static brix_vfs_dir_t * vfs_opendir_fail (brix_vfs_ctx_t *ctx, int err, int observe, uint64_t start, int *err_out)
static ngx_int_t vfs_dir_route (brix_vfs_ctx_t *ctx, const brix_sd_driver_t **drv_out, int *err)
static ngx_int_t vfs_dir_open_driver (brix_vfs_ctx_t *ctx, brix_vfs_dir_t *dh, const brix_sd_driver_t *drv, const char *path, int *err_out)
static ngx_int_t vfs_dir_open_confined (brix_vfs_ctx_t *ctx, brix_vfs_dir_t *dh, const char *path)
static brix_vfs_dir_t * brix_vfs_opendir_impl (brix_vfs_ctx_t *ctx, int *err_out, int observe)
brix_vfs_dir_t * brix_vfs_opendir (brix_vfs_ctx_t *ctx, int *err_out)
brix_vfs_dir_t * brix_vfs_opendir_quiet (brix_vfs_ctx_t *ctx, int *err_out)
ngx_fd_t brix_vfs_dir_fd (const brix_vfs_dir_t *dh)
static ngx_int_t vfs_readdir_fill_entry (ngx_pool_t *pool, const char *name, ngx_str_t *name_out)
static ngx_int_t vfs_readdir_next_posix (brix_vfs_dir_t *dh, struct dirent **de_out)
static ngx_int_t vfs_readdir_stat_child (brix_vfs_dir_t *dh, const char *name, brix_vfs_stat_t *stat_out)
static ngx_int_t vfs_sd_stat_child (brix_vfs_dir_t *dh, const char *name, brix_sd_stat_t *sd_st)
static ngx_int_t vfs_readdir_sd (brix_vfs_dir_t *dh, ngx_str_t *name_out, brix_vfs_stat_t *stat_out)
ngx_int_t brix_vfs_readdir (brix_vfs_dir_t *dh, ngx_str_t *name_out, brix_vfs_stat_t *stat_out)
static brix_vfs_dirent_kind_t vfs_sd_entry_kind (brix_vfs_dir_t *dh, const char *name)
static brix_vfs_dirent_kind_t vfs_posix_dtype_kind (unsigned char d_type)
ngx_int_t brix_vfs_readdir_kind (brix_vfs_dir_t *dh, ngx_str_t *name_out, brix_vfs_dirent_kind_t *kind_out)
ngx_int_t brix_vfs_closedir (brix_vfs_dir_t *dh, ngx_log_t *log)
ngx_int_t brix_vfs_enumerate_catalog (brix_sd_instance_t *sd, int want_stat, brix_sd_catalog_cb cb, void *ctx)
Function Documentation
brix_vfs_closedir()
ngx_int_t brix_vfs_closedir (brix_vfs_dir_t * dh, ngx_log_t * log)
Definition at line 500 of file vfs_dir.c.
References BRIX_DIAG_ERR, and log.
Referenced by brix_dirlist_alloc_chunk(), brix_dirlist_stream_entries(), brix_ftp_ev_data_finish(), check_locks_descendants(), fattr_recurse_dir(), lp_scan_staged_parts(), mpu_collect(), ngx_http_brix_dashboard_vfs_files_handler(), propfind_walk(), s3_mpu_reap_stale(), s3_walk_run(), and webdav_search_walk().
brix_vfs_dir_fd()
ngx_fd_t brix_vfs_dir_fd (const brix_vfs_dir_t * dh)
Definition at line 230 of file vfs_dir.c.
Referenced by brix_dirlist_entry_meta().
brix_vfs_enumerate_catalog()
ngx_int_t brix_vfs_enumerate_catalog (brix_sd_instance_t * sd, int want_stat, brix_sd_catalog_cb cb, void * ctx)
Definition at line 536 of file vfs_dir.c.
Referenced by brix_scan_run_inventory(), and brix_scan_run_verify_catalog().
brix_vfs_opendir()
brix_vfs_dir_t * brix_vfs_opendir (brix_vfs_ctx_t * ctx, int * err_out)
Definition at line 213 of file vfs_dir.c.
References brix_vfs_opendir_impl().
Referenced by brix_dirlist_open_dir(), brix_ftp_ev_data_ready(), ngx_http_brix_dashboard_vfs_files_handler(), and propfind_walk().
brix_vfs_opendir_impl()
static brix_vfs_dir_t * brix_vfs_opendir_impl (brix_vfs_ctx_t * ctx, int * err_out, int observe) static
Definition at line 164 of file vfs_dir.c.
References BRIX_METRIC_OP_DIRLIST, brix_vfs_copy_path(), brix_vfs_ctx_path(), brix_vfs_now_ns(), brix_vfs_observe_ctx_op(), ngx_pcalloc(), brix_vfs_ctx_t::pool, vfs_dir_open_confined(), vfs_dir_open_driver(), vfs_dir_route(), and vfs_opendir_fail().
Referenced by brix_vfs_opendir(), and brix_vfs_opendir_quiet().
brix_vfs_opendir_quiet()
brix_vfs_dir_t * brix_vfs_opendir_quiet (brix_vfs_ctx_t * ctx, int * err_out)
Definition at line 222 of file vfs_dir.c.
References brix_vfs_opendir_impl().
Referenced by check_locks_descendants(), fattr_recurse_dir(), lp_scan_staged_parts(), mpu_collect(), s3_mpu_reap_stale(), s3_walk_run(), and webdav_search_walk().
brix_vfs_readdir()
ngx_int_t brix_vfs_readdir (brix_vfs_dir_t * dh, ngx_str_t * name_out, brix_vfs_stat_t * stat_out)
Definition at line 377 of file vfs_dir.c.
References vfs_readdir_fill_entry(), vfs_readdir_next_posix(), vfs_readdir_sd(), and vfs_readdir_stat_child().
Referenced by brix_dirlist_stream_entries(), ev_list_fill(), fattr_recurse_dir(), and propfind_walk().
brix_vfs_readdir_kind()
ngx_int_t brix_vfs_readdir_kind (brix_vfs_dir_t * dh, ngx_str_t * name_out, brix_vfs_dirent_kind_t * kind_out)
Definition at line 459 of file vfs_dir.c.
References brix_sd_dirent_t::name, vfs_posix_dtype_kind(), vfs_readdir_fill_entry(), vfs_readdir_next_posix(), and vfs_sd_entry_kind().
Referenced by check_locks_descendants(), lp_scan_staged_parts(), mpu_collect(), s3_mpu_reap_stale(), s3_walk_run(), vfs_browse_collect(), and webdav_search_scan_dir().
vfs_dir_open_confined()
static ngx_int_t vfs_dir_open_confined (brix_vfs_ctx_t * ctx, brix_vfs_dir_t * dh, const char * path) static
Definition at line 144 of file vfs_dir.c.
References brix_opendir_confined_canon(), brix_vfs_ctx_t::log, brix_vfs_ctx_t::pool, and brix_vfs_ctx_t::root_canon.
Referenced by brix_vfs_opendir_impl().
vfs_dir_open_driver()
static ngx_int_t vfs_dir_open_driver (brix_vfs_ctx_t * ctx, brix_vfs_dir_t * dh, const brix_sd_driver_t * drv, const char * path, int * err_out) static
Definition at line 85 of file vfs_dir.c.
References brix_sd_opendir_maybe_cred(), brix_sd_ucred_wipe(), brix_vfs_copy_path(), brix_vfs_cred_gate_active(), brix_vfs_export_relative(), brix_vfs_ns_cred(), brix_vfs_ns_leaf(), brix_vfs_ctx_t::log, brix_vfs_ctx_t::pool, and brix_vfs_ctx_t::sd.
Referenced by brix_vfs_opendir_impl().
vfs_dir_route()
static ngx_int_t vfs_dir_route (brix_vfs_ctx_t * ctx, const brix_sd_driver_t ** drv_out, int * err) static
Definition at line 61 of file vfs_dir.c.
References brix_vfs_ctx_driver(), and brix_vfs_require_confined().
Referenced by brix_vfs_opendir_impl().
vfs_opendir_fail()
static brix_vfs_dir_t * vfs_opendir_fail (brix_vfs_ctx_t * ctx, int err, int observe, uint64_t start, int * err_out) static
Definition at line 36 of file vfs_dir.c.
References BRIX_METRIC_OP_DIRLIST, brix_vfs_ctx_path(), and brix_vfs_observe_ctx_op().
Referenced by brix_vfs_opendir_impl().
vfs_posix_dtype_kind()
static brix_vfs_dirent_kind_t vfs_posix_dtype_kind (unsigned char d_type) static
Definition at line 448 of file vfs_dir.c.
References BRIX_VFS_DT_DIR, BRIX_VFS_DT_OTHER, BRIX_VFS_DT_REG, and BRIX_VFS_DT_UNKNOWN.
Referenced by brix_vfs_readdir_kind().
vfs_readdir_fill_entry()
static ngx_int_t vfs_readdir_fill_entry (ngx_pool_t * pool, const char * name, ngx_str_t * name_out) static
Definition at line 243 of file vfs_dir.c.
References name, ngx_memcpy, and ngx_pnalloc().
Referenced by brix_vfs_readdir(), brix_vfs_readdir_kind(), and vfs_readdir_sd().
vfs_readdir_next_posix()
static ngx_int_t vfs_readdir_next_posix (brix_vfs_dir_t * dh, struct dirent ** de_out) static
Definition at line 265 of file vfs_dir.c.
Referenced by brix_vfs_readdir(), and brix_vfs_readdir_kind().
vfs_readdir_sd()
static ngx_int_t vfs_readdir_sd (brix_vfs_dir_t * dh, ngx_str_t * name_out, brix_vfs_stat_t * stat_out) static
Definition at line 348 of file vfs_dir.c.
References brix_vfs_sd_stat_fill(), brix_sd_dirent_t::name, vfs_readdir_fill_entry(), and vfs_sd_stat_child().
Referenced by brix_vfs_readdir().
vfs_readdir_stat_child()
static ngx_int_t vfs_readdir_stat_child (brix_vfs_dir_t * dh, const char * name, brix_vfs_stat_t * stat_out) static
Definition at line 299 of file vfs_dir.c.
References brix_lstat_confined_canon(), brix_vfs_fill_stat(), name, PATH_MAX, and stat().
Referenced by brix_vfs_readdir().
vfs_sd_entry_kind()
static brix_vfs_dirent_kind_t vfs_sd_entry_kind (brix_vfs_dir_t * dh, const char * name) static
Definition at line 428 of file vfs_dir.c.
References BRIX_VFS_DT_DIR, BRIX_VFS_DT_REG, BRIX_VFS_DT_UNKNOWN, brix_sd_stat_t::is_dir, name, and vfs_sd_stat_child().
Referenced by brix_vfs_readdir_kind().
vfs_sd_stat_child()
static ngx_int_t vfs_sd_stat_child (brix_vfs_dir_t * dh, const char * name, brix_sd_stat_t * sd_st) static
Definition at line 327 of file vfs_dir.c.
References name, and PATH_MAX.
Referenced by vfs_readdir_sd(), and vfs_sd_entry_kind().