nginx-xrootd: src/fs/vfs/vfs_mkdir.c File Reference
vfs_mkdir.c File Reference
#include "vfs_internal.h"
#include "fs/path/path.h"
Data Structures
struct vfs_mkdir_req_t
Functions
static int vfs_backend_mkpath_leaf (brix_sd_instance_t *leaf, const char *logical, mode_t mode, const brix_sd_cred_t *cred)
static ngx_int_t vfs_backend_mkdir_dispatch (const vfs_mkdir_req_t *req, const brix_sd_driver_t *drv, brix_sd_instance_t *leaf, int use_cred, const brix_sd_cred_t *cred)
static ngx_int_t vfs_mkdir_backend (const vfs_mkdir_req_t *req, const brix_sd_driver_t *drv)
ngx_int_t brix_vfs_mkdir (brix_vfs_ctx_t *ctx, mode_t mode, unsigned parents)
ngx_int_t brix_vfs_chmod (brix_vfs_ctx_t *ctx, mode_t mode)
ngx_int_t brix_vfs_setattr (brix_vfs_ctx_t *ctx, const brix_sd_setattr_t *attr)
Function Documentation
brix_vfs_chmod()
ngx_int_t brix_vfs_chmod (brix_vfs_ctx_t * ctx, mode_t mode)
Definition at line 281 of file vfs_mkdir.c.
References brix_chmod_confined_canon(), brix_sd_setattr_maybe_cred(), brix_sd_ucred_wipe(), brix_vfs_cred_gate_active(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_ns_cred(), brix_vfs_ns_leaf(), brix_vfs_require_write(), brix_vfs_ctx_t::log, brix_sd_setattr_t::mode, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::sd, and brix_sd_setattr_t::set_mode.
Referenced by exec_chmod().
brix_vfs_mkdir()
ngx_int_t brix_vfs_mkdir (brix_vfs_ctx_t * ctx, mode_t mode, unsigned parents)
Definition at line 214 of file vfs_mkdir.c.
References BRIX_METRIC_OP_MKDIR, brix_ns_mkdir(), BRIX_NS_OK, brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_now_ns(), brix_vfs_observe_ctx_op(), brix_vfs_require_write(), vfs_mkdir_req_t::ctx, brix_vfs_ctx_t::log, vfs_mkdir_req_t::mode, vfs_mkdir_req_t::parents, vfs_mkdir_req_t::path, brix_vfs_ctx_t::root_canon, vfs_mkdir_req_t::start, brix_ns_result_t::status, brix_ns_result_t::sys_errno, and vfs_mkdir_backend().
Referenced by brix_ftp_ev_cmd_mkd(), brix_handle_mkdir(), s3_post_write_object(), s3_put_try_sentinel(), s3put_ensure_parent_dirs(), and webdav_handle_mkcol().
brix_vfs_setattr()
ngx_int_t brix_vfs_setattr (brix_vfs_ctx_t * ctx, const brix_sd_setattr_t * attr)
Definition at line 350 of file vfs_mkdir.c.
References brix_sd_setattr_t::atime, brix_chmod_confined_canon(), brix_sd_setattr_maybe_cred(), brix_sd_ucred_wipe(), brix_setattr_confined_canon(), brix_vfs_cred_gate_active(), brix_vfs_ctx_driver(), brix_vfs_ctx_path(), brix_vfs_export_relative(), brix_vfs_ns_cred(), brix_vfs_ns_leaf(), brix_vfs_require_write(), brix_sd_setattr_t::gid, brix_vfs_ctx_t::log, brix_sd_setattr_t::mode, brix_sd_setattr_t::mtime, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::sd, brix_sd_setattr_t::set_mode, brix_sd_setattr_t::set_owner, brix_sd_setattr_t::set_times, and brix_sd_setattr_t::uid.
Referenced by brix_handle_setattr().
vfs_backend_mkdir_dispatch()
static ngx_int_t vfs_backend_mkdir_dispatch (const vfs_mkdir_req_t * req, const brix_sd_driver_t * drv, brix_sd_instance_t * leaf, int use_cred, const brix_sd_cred_t * cred) static
Definition at line 116 of file vfs_mkdir.c.
References brix_sd_mkdir_maybe_cred(), brix_vfs_backend_mkpath(), brix_vfs_export_relative(), vfs_mkdir_req_t::ctx, brix_vfs_ctx_t::log, vfs_mkdir_req_t::mode, vfs_mkdir_req_t::parents, vfs_mkdir_req_t::path, brix_vfs_ctx_t::root_canon, and vfs_backend_mkpath_leaf().
Referenced by vfs_mkdir_backend().
vfs_backend_mkpath_leaf()
static int vfs_backend_mkpath_leaf (brix_sd_instance_t * leaf, const char * logical, mode_t mode, const brix_sd_cred_t * cred) static
Definition at line 41 of file vfs_mkdir.c.
References brix_sd_mkdir_maybe_cred(), and PATH_MAX.
Referenced by vfs_backend_mkdir_dispatch().
vfs_mkdir_backend()
static ngx_int_t vfs_mkdir_backend (const vfs_mkdir_req_t * req, const brix_sd_driver_t * drv) static
Definition at line 161 of file vfs_mkdir.c.
References BRIX_METRIC_OP_MKDIR, BRIX_SD_CAP_DIRS_WRITE, brix_sd_ucred_wipe(), brix_vfs_cred_gate_active(), brix_vfs_ns_cred(), brix_vfs_ns_leaf(), brix_vfs_observe_ctx_op(), vfs_mkdir_req_t::ctx, vfs_mkdir_req_t::path, brix_vfs_ctx_t::sd, vfs_mkdir_req_t::start, and vfs_backend_mkdir_dispatch().
Referenced by brix_vfs_mkdir().