nginx-xrootd: src/fs/core/vfs_core_unittest.c File Reference
vfs_core_unittest.c File Reference
#include "vfs_core.h"
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Macros
#define CHECK(cond, msg)
Functions
int main (void)
Variables
static int g_fail
Macro Definition Documentation
CHECK
#define CHECK (cond, msg)
Value:
    do {                                  \
    if (cond) { printf("ok: %s\n", msg); }                    \
    else      { printf("FAIL: %s\n", msg); g_fail = 1; }     \
} while (0)
Definition at line 28 of file vfs_core_unittest.c.
Function Documentation
main()
int main (void)
Definition at line 33 of file vfs_core_unittest.c.
References brix_sd_posix_wrap(), CHECK, close(), g_fail, brix_sd_stat_t::is_reg, brix_sd_stat_t::size, xvfs_drain(), xvfs_fstat(), xvfs_fsync(), xvfs_ftruncate(), xvfs_pread_full(), xvfs_pread_once(), and xvfs_pwrite_full().
Variable Documentation
g_fail
int g_fail static
Definition at line 26 of file vfs_core_unittest.c.
Referenced by main().