nginx-xrootd: client/lib/fs/backend/s3/vfs_s3_io.c File Reference
vfs_s3_io.c File Reference
#include "vfs_s3_internal.h"
Functions
int s3_load_size (vfs_s3_file *sf, brix_status *st)
ssize_t s3_pread (brix_vfs_file *f, int64_t off, void *buf, size_t n, brix_status *st)
int s3_pwrite (brix_vfs_file *f, int64_t off, const void *buf, size_t n, brix_status *st)
int s3_fstat (brix_vfs_file *f, brix_vfs_stat *out, brix_status *st)
int s3_truncate (brix_vfs_file *f, int64_t size, brix_status *st)
int s3_sync (brix_vfs_file *f, brix_status *st)
int s3_commit (brix_vfs_file *f, brix_status *st)
void s3_abort (brix_vfs_file *f)
void s3_close (brix_vfs_file *f)
Function Documentation
s3_abort()
void s3_abort (brix_vfs_file * f)
Definition at line 204 of file vfs_s3_io.c.
References vfs_s3_file::sd, and sd_s3_abort().
s3_close()
void s3_close (brix_vfs_file * f)
Definition at line 222 of file vfs_s3_io.c.
References vfs_s3_file::sd, and sd_s3_close().
s3_commit()
int s3_commit (brix_vfs_file * f, brix_status * st)
Definition at line 179 of file vfs_s3_io.c.
References brix_status_set(), vfs_s3_file::sd, sd_s3_commit(), and XRDC_EIO.
s3_fstat()
int s3_fstat (brix_vfs_file * f, brix_vfs_stat * out, brix_status * st)
Definition at line 103 of file vfs_s3_io.c.
References brix_vfs_stat::exists, brix_vfs_stat::is_dir, vfs_s3_file::is_write, brix_vfs_stat::mtime, vfs_s3_file::obj_size, s3_load_size(), vfs_s3_file::sd, sd_s3_write_size(), and brix_vfs_stat::size.
s3_load_size()
int s3_load_size (vfs_s3_file * sf, brix_status * st)
Definition at line 19 of file vfs_s3_io.c.
References brix_status_set(), vfs_s3_file::obj_size, vfs_s3_file::sd, sd_s3_size(), and XRDC_EIO.
Referenced by s3_be_stat(), and s3_fstat().
s3_pread()
ssize_t s3_pread (brix_vfs_file * f, int64_t off, void * buf, size_t n, brix_status * st)
Definition at line 44 of file vfs_s3_io.c.
References brix_status_set(), vfs_s3_file::sd, sd_s3_pread(), and XRDC_EIO.
s3_pwrite()
int s3_pwrite (brix_vfs_file * f, int64_t off, const void * buf, size_t n, brix_status * st)
Definition at line 72 of file vfs_s3_io.c.
References brix_status_set(), s3_brix_from_errno(), vfs_s3_file::sd, and sd_s3_pwrite().
s3_sync()
int s3_sync (brix_vfs_file * f, brix_status * st)
Definition at line 159 of file vfs_s3_io.c.
s3_truncate()
int s3_truncate (brix_vfs_file * f, int64_t size, brix_status * st)
Definition at line 137 of file vfs_s3_io.c.
References brix_status_set(), vfs_s3_file::key_path, and XRDC_EUSAGE.