nginx-xrootd: src/auth/voms/voms_internal.h File Reference
voms_internal.h File Reference
#include "core/ngx_brix_module.h"
#include <openssl/x509.h>
Data Structures
struct voms_data_item
struct voms_entry
struct brix_voms_init_pt
struct brix_voms_api_t
Macros
#define VOMS_VERR_NOEXT 5
#define VOMS_VERR_NODATA 11
#define VOMS_RECURSE_CHAIN 0
Typedefs
typedef int(* brix_voms_retrieve_pt) (X509 *cert, STACK_OF(X509) *chain, int how, struct voms_data *vd, int *error)
typedef void(* brix_voms_destroy_pt) (struct voms_data *vd)
typedef char *(* brix_voms_error_message_pt) (struct voms_data *vd, int error, char *buf, int len)
Functions
ngx_int_t brix_collect_voms_vos (struct voms_data *vd, char *primary_vo, size_t primary_vo_sz, char *vo_list, size_t vo_list_sz)
Variables
brix_voms_api_t brix_voms_api
ngx_flag_t brix_voms_loaded
Macro Definition Documentation
VOMS_RECURSE_CHAIN
#define VOMS_RECURSE_CHAIN 0
Definition at line 91 of file voms_internal.h.
VOMS_VERR_NODATA
#define VOMS_VERR_NODATA 11
Definition at line 90 of file voms_internal.h.
VOMS_VERR_NOEXT
#define VOMS_VERR_NOEXT 5
Definition at line 89 of file voms_internal.h.
Typedef Documentation
brix_voms_destroy_pt
typedef void(* brix_voms_destroy_pt) (struct voms_data *vd)
Definition at line 105 of file voms_internal.h.
brix_voms_error_message_pt
typedef char *(* brix_voms_error_message_pt) (struct voms_data *vd, int error, char *buf, int len)
Definition at line 106 of file voms_internal.h.
brix_voms_retrieve_pt
typedef int(* brix_voms_retrieve_pt) (X509 *cert, STACK_OF(X509) *chain, int how, struct voms_data *vd, int *error)
Definition at line 103 of file voms_internal.h.
Function Documentation
brix_collect_voms_vos()
ngx_int_t brix_collect_voms_vos (struct voms_data * vd, char * primary_vo, size_t primary_vo_sz, char * vo_list, size_t vo_list_sz)
Definition at line 119 of file collect.c.
References brix_append_vo_token(), brix_fqan_to_vo(), brix_voms_init_pt::data, and voms_entry::fqan.
Referenced by brix_extract_voms_info().
Variable Documentation
brix_voms_api
brix_voms_api_t brix_voms_api extern
Definition at line 12 of file loader.c.
Referenced by brix_extract_voms_info(), and brix_voms_init().
brix_voms_loaded
ngx_flag_t brix_voms_loaded extern
Definition at line 13 of file loader.c.
Referenced by brix_extract_voms_info(), brix_voms_available(), and brix_voms_init().