nginx-xrootd: client/apps/diag/wait41.c File Reference
wait41.c File Reference
#include "brix.h"
#include "core/compat/crypto.h"
#include "core/version.h"
#include "core/progname.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
Functions
int brix_wait41_main (int argc, char **argv)
Function Documentation
brix_wait41_main()
int brix_wait41_main (int argc, char ** argv)
Definition at line 24 of file wait41.c.
References brix_client_version(), brix_close(), brix_connect(), brix_crypto_init(), brix_endpoint_parse(), brix_prog_base(), brix_status_clear(), brix_tcp_connect(), brix_usage_footer(), c, close(), brix_url::host, brix_status::msg, and brix_url::port.
Referenced by dx_personality_route().