nginx-xrootd: client/lib/protocols/http/web_ka.c File Reference
web_ka.c File Reference
#include "web_ka.h"
#include "core/compat/host_format.h"
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <stdio.h>
#include <poll.h>
#include <errno.h>
#include <unistd.h>
Macros
#define KA_HDR_MAX 16384 /* mirrors WEB_HDR_MAX */
#define KA_BODY_MAX (4 * 1024 * 1024) /* a PROPFIND body over 4 MiB is abuse */
Functions
int webfile_window_ms (void)
void brix_kaconn_init (brix_kaconn *k, const char *host, int port, int tls, int verify, const char *ca_dir, int timeout_ms)
void brix_kaconn_disconnect (brix_kaconn *k)
int brix_kaconn_connect (brix_kaconn *k, brix_status *st)
static ssize_t kaconn_read_some (brix_kaconn *k, void *buf, size_t n, brix_status *st)
static long long ka_hdr_clen (const char *hdrs)
int brix_kaconn_read_headers (brix_kaconn *k, char *hbuf, size_t hbufsz, brix_ka_hdr *out, brix_status *st)
int brix_kaconn_read_body (brix_kaconn *k, const brix_ka_hdr *hdr, char **body_out, size_t *len_out, brix_status *st)
void brix_webmeta_init (brix_webmeta *m, const char *host, int port, int tls, int verify, const char *ca_dir, const char *bearer, int timeout_ms)
static int webmeta_send_req (brix_webmeta *m, const char *path, int depth, brix_status *st)
static int webmeta_status_map (int status, brix_status *st)
int brix_webmeta_propfind (brix_webmeta *m, const char *path, int depth, char **body_out, size_t *len_out, brix_status *st)
Macro Definition Documentation
KA_BODY_MAX
#define KA_BODY_MAX (4 * 1024 * 1024) /* a PROPFIND body over 4 MiB is abuse */
Definition at line 29 of file web_ka.c.
KA_HDR_MAX
#define KA_HDR_MAX 16384 /* mirrors WEB_HDR_MAX */
Definition at line 28 of file web_ka.c.
Function Documentation
brix_kaconn_connect()
int brix_kaconn_connect (brix_kaconn * k, brix_status * st)
Definition at line 70 of file web_ka.c.
References brix_tcp_connect(), brix_tls_client(), brix_kaconn::ca_dir, close(), brix_kaconn::connected, brix_io::fd, brix_kaconn::host, brix_kaconn::io, brix_kaconn::port, brix_io::timeout_ms, brix_kaconn::timeout_ms, brix_kaconn::tls, brix_kaconn::tls_ctx, and brix_kaconn::verify.
Referenced by brix_webmeta_propfind(), and web_slot_connect().
brix_kaconn_disconnect()
void brix_kaconn_disconnect (brix_kaconn * k)
Definition at line 53 of file web_ka.c.
References brix_tls_client_free(), close(), brix_kaconn::connected, brix_io::fd, brix_kaconn::io, brix_kaconn::tls, and brix_kaconn::tls_ctx.
Referenced by brix_kaconn_read_body(), brix_kaconn_read_headers(), brix_webmeta_propfind(), web_slot_close(), and webmeta_send_req().
brix_kaconn_init()
void brix_kaconn_init (brix_kaconn * k, const char * host, int port, int tls, int verify, const char * ca_dir, int timeout_ms)
Definition at line 35 of file web_ka.c.
References brix_format_host_port(), brix_kaconn::ca_dir, brix_io::fd, brix_kaconn::host, brix_kaconn::hostport, brix_kaconn::io, brix_kaconn::port, brix_kaconn::timeout_ms, brix_kaconn::tls, tls, and brix_kaconn::verify.
Referenced by brix_webmeta_init().
brix_kaconn_read_body()
int brix_kaconn_read_body (brix_kaconn * k, const brix_ka_hdr * hdr, char ** body_out, size_t * len_out, brix_status * st)
Definition at line 192 of file web_ka.c.
References brix_ka_hdr::body_buffered, brix_ka_hdr::body_start, brix_kaconn_disconnect(), brix_read_full(), brix_status_set(), brix_ka_hdr::clen, have(), brix_kaconn::io, and XRDC_EPROTO.
Referenced by brix_webmeta_propfind().
brix_kaconn_read_headers()
int brix_kaconn_read_headers (brix_kaconn * k, char * hbuf, size_t hbufsz, brix_ka_hdr * out, brix_status * st)
Definition at line 136 of file web_ka.c.
References brix_ka_hdr::body_buffered, brix_ka_hdr::body_start, brix_kaconn_disconnect(), brix_status_set(), brix_ka_hdr::clen, KA_BODY_MAX, ka_hdr_clen(), kaconn_read_some(), brix_ka_hdr::status, XRDC_EPROTO, and XRDC_ESOCK.
Referenced by brix_webmeta_propfind().
brix_webmeta_init()
void brix_webmeta_init (brix_webmeta * m, const char * host, int port, int tls, int verify, const char * ca_dir, const char * bearer, int timeout_ms)
Definition at line 218 of file web_ka.c.
References brix_webmeta::auth, brix_kaconn_init(), brix_webmeta::ka, and tls.
Referenced by aio_web_mount().
brix_webmeta_propfind()
int brix_webmeta_propfind (brix_webmeta * m, const char * path, int depth, char ** body_out, size_t * len_out, brix_status * st)
Definition at line 271 of file web_ka.c.
References brix_backoff_sleep_fast(), brix_kaconn_connect(), brix_kaconn_disconnect(), brix_kaconn_read_body(), brix_kaconn_read_headers(), brix_mono_ns(), brix_status_retryable(), brix_status_set(), brix_ka_hdr::clen, brix_kaconn::connected, brix_webmeta::ka, KA_HDR_MAX, brix_ka_hdr::status, webfile_window_ms(), webmeta_send_req(), webmeta_status_map(), and XRDC_EPROTO.
Referenced by brix_web_readdir_pooled(), and brix_web_stat_pooled().
ka_hdr_clen()
static long long ka_hdr_clen (const char * hdrs) static
Definition at line 120 of file web_ka.c.
Referenced by brix_kaconn_read_headers().
kaconn_read_some()
static ssize_t kaconn_read_some (brix_kaconn * k, void * buf, size_t n, brix_status * st) static
Definition at line 92 of file web_ka.c.
References brix_status_set(), brix_tls_read_some(), brix_io::fd, brix_kaconn::io, read(), brix_io::ssl, brix_io::timeout_ms, and XRDC_ESOCK.
Referenced by brix_kaconn_read_headers().
webfile_window_ms()
int webfile_window_ms (void)
Definition at line 387 of file webfile_io.c.
References brix_xrdrc_default_ms(), and XRDC_DEFAULT_MAX_STALL_MS.
Referenced by brix_webmeta_propfind().
webmeta_send_req()
static int webmeta_send_req (brix_webmeta * m, const char * path, int depth, brix_status * st) static
Definition at line 234 of file web_ka.c.
References brix_webmeta::auth, brix_kaconn_disconnect(), brix_status_set(), brix_write_full(), brix_kaconn::hostport, brix_kaconn::io, brix_webmeta::ka, and XRDC_EUSAGE.
Referenced by brix_webmeta_propfind().
webmeta_status_map()
static int webmeta_status_map (int status, brix_status * st) static
Definition at line 255 of file web_ka.c.
References brix_status_set(), kXR_NotAuthorized, kXR_NotFound, and XRDC_EPROTO.
Referenced by brix_webmeta_propfind().