nginx-xrootd: src/protocols/webdav/webdav_props.h File Reference
webdav_props.h File Reference
#include "webdav.h"
Functions
ngx_int_t webdav_dead_prop_set (ngx_http_request_t *r, const char *path, const char *ns, const char *local, const char *xml, size_t xml_len)
ngx_int_t webdav_dead_prop_remove (ngx_http_request_t *r, const char *path, const char *ns, const char *local)
ngx_int_t webdav_dead_prop_append_value (ngx_http_request_t *r, const char *path, const char *ns, const char *local, ngx_chain_t **head, ngx_chain_t **tail, ngx_flag_t *found)
ngx_int_t webdav_dead_prop_append_empty (ngx_http_request_t *r, const char *ns, const char *local, ngx_chain_t **head, ngx_chain_t **tail)
ngx_int_t webdav_dead_props_append_all (ngx_http_request_t *r, const char *path, ngx_chain_t **head, ngx_chain_t **tail, ngx_flag_t names_only)
ngx_flag_t webdav_dead_prop_is_protected_dav (const char *local)
void webdav_dead_props_copy (ngx_log_t *log, const char *src, const char *dst)
void webdav_fadvise_willneed (ngx_log_t *log, ngx_fd_t fd, off_t offset, size_t len)
ngx_int_t webdav_write_full (ngx_fd_t fd, u_char *buf, size_t len, off_t offset)
ngx_int_t webdav_copy_spooled_file (ngx_http_request_t *r, ngx_fd_t dst_fd, ngx_buf_t *buf, const char *path, u_char **scratch)
WHAT: Copy a spooled temp file body to the final destination using zero-copy copy_file_range() on Linux, falling back to pread+write on other platforms.
Function Documentation
webdav_copy_spooled_file()
ngx_int_t webdav_copy_spooled_file (ngx_http_request_t * r, ngx_fd_t dst_fd, ngx_buf_t * buf, const char * path, u_char ** scratch)
WHAT: Copy a spooled temp file body to the final destination using zero-copy copy_file_range() on Linux, falling back to pread+write on other platforms.
Transfers bytes from buf->file (the spooled PUT temp file) to dst_fd (the final WebDAV resource) in chunks. On Linux with SYS_copy_file_range support this uses kernel-level zero-copy transfer; otherwise falls back to userspace pread+write loop. Returns NGX_OK on complete copy or NGX_ERROR on any failure. The scratch buffer is allocated lazily if needed for the fallback path.
WHY: Spooled PUT writes (where the request body is stored in a temp file first) need to be moved to their final destination after authentication and validation succeed. copy_file_range() on Linux provides zero-copy kernel-level transfer without userspace buffering — this is significantly faster for large files (>1MB) and avoids allocating temporary buffers. The fallback path uses pread(2) + webdav_write_full(2) which works on all platforms but has higher CPU overhead due to copying through user-space buffers. This function handles multiple error conditions: EXDEV (cross-device copy not supported), EOPNOTSUPP/ENOSYS (syscall unavailable), and retries only EINTR.
HOW: Four-phase algorithm. Phase 1: validate source buf has valid file pointer and fd, compute remaining bytes from buf->file_last - buf->file_pos. Phase 2 (Linux only): loop using copy_file_range() syscall in WEBDAV_PUT_COPY_CHUNK-sized chunks — successful copies decrement remaining, EINTR retries, non-recoverable errors return immediately, EXDEV/ ENOSYS/EOPNOTSUPP/EINVAL/EPERM break out to fallback. Phase 3 (fallback): allocate scratch buffer via ngx_palloc(r->pool) if not already done, loop using pread + webdav_write_full. Phase 4: return NGX_OK if remaining == 0 after either phase. Logging uses brix_log_safe_path() for safe path formatting in error messages.
Definition at line 73 of file io.c.
References brix_http_body_write_buf().
webdav_dead_prop_append_empty()
ngx_int_t webdav_dead_prop_append_empty (ngx_http_request_t * r, const char * ns, const char * local, ngx_chain_t ** head, ngx_chain_t ** tail)
Definition at line 81 of file dead_props.c.
References brix_http_chain_appendf(), webdav_dead_prop_xml_name_ok(), and webdav_escape_xml_text().
Referenced by webdav_dead_props_append_all(), and webdav_proppatch_append_propstat().
webdav_dead_prop_append_value()
ngx_int_t webdav_dead_prop_append_value (ngx_http_request_t * r, const char * path, const char * ns, const char * local, ngx_chain_t ** head, ngx_chain_t ** tail, ngx_flag_t * found)
Definition at line 282 of file dead_props.c.
References brix_http_chain_appendf(), and webdav_dead_prop_read_value().
Referenced by propfind_dead_props_resolve_and_emit(), and webdav_dead_props_append_all().
webdav_dead_prop_is_protected_dav()
ngx_flag_t webdav_dead_prop_is_protected_dav (const char * local)
Definition at line 67 of file dead_props.c.
Referenced by webdav_proppatch_prop_status().
webdav_dead_prop_remove()
ngx_int_t webdav_dead_prop_remove (ngx_http_request_t * r, const char * path, const char * ns, const char * local)
Definition at line 187 of file dead_props.c.
References brix_vfs_removexattr(), ENOATTR, webdav_dead_prop_attr_name(), WEBDAV_DEAD_PROP_NAME_MAX, and webdav_dead_prop_vfs_ctx_init().
Referenced by webdav_proppatch_prop_status().
webdav_dead_prop_set()
ngx_int_t webdav_dead_prop_set (ngx_http_request_t * r, const char * path, const char * ns, const char * local, const char * xml, size_t xml_len)
Definition at line 173 of file dead_props.c.
References webdav_dead_prop_set_target().
Referenced by webdav_proppatch_prop_status().
webdav_dead_props_append_all()
ngx_int_t webdav_dead_props_append_all (ngx_http_request_t * r, const char * path, ngx_chain_t ** head, ngx_chain_t ** tail, ngx_flag_t names_only)
Definition at line 317 of file dead_props.c.
References BRIX_PNALLOC_OR_RETURN, brix_vfs_listxattr(), webdav_dead_prop_append_empty(), webdav_dead_prop_append_value(), webdav_dead_prop_decode_attr(), WEBDAV_DEAD_PROP_LIST_MAX, and webdav_dead_prop_vfs_ctx_init().
Referenced by propfind_dead_props_resolve_and_emit(), and propfind_entry().
webdav_dead_props_copy()
void webdav_dead_props_copy (ngx_log_t * log, const char * src, const char * dst)
Definition at line 379 of file dead_props.c.
References brix_xattr_copy_by_prefix(), log, WEBDAV_DEAD_PROP_PREFIX, WEBDAV_DEAD_PROP_PREFIX_LEN, and WEBDAV_DEAD_PROP_VALUE_MAX.
Referenced by webdav_copy_collection_stage(), webdav_copy_do_file(), and webdav_copy_meta_cb().
webdav_fadvise_willneed()
void webdav_fadvise_willneed (ngx_log_t * log, ngx_fd_t fd, off_t offset, size_t len)
Definition at line 83 of file io.c.
References log.
Referenced by webdav_get_add_xrdhttp_headers().
webdav_write_full()
ngx_int_t webdav_write_full (ngx_fd_t fd, u_char * buf, size_t len, off_t offset)
Definition at line 13 of file io.c.
References brix_sd_posix_wrap().