nginx-xrootd: src/protocols/webdav/dispatch.c File Reference
dispatch.c File Reference
#include "webdav.h"
#include "xrdhttp.h"
#include "tape_rest.h"
#include "delegation.h"
#include "core/http/http_body.h"
#include "auth/impersonate/lifecycle.h"
Functions
static ngx_int_t webdav_dispatch_inner (ngx_http_request_t *r)
static ngx_int_t webdav_dispatch_draining (ngx_http_request_t *r)
static void webdav_dispatch_pmark (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t webdav_dispatch_macaroon (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t webdav_dispatch_delegation_upload (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t webdav_dispatch_delegation_gridsite (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t webdav_dispatch_tape_rest (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t webdav_lock_check_request_path (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t webdav_dispatch_put (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t webdav_dispatch_copy (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t webdav_dispatch_move (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t webdav_dispatch_lock (ngx_http_request_t *r)
static ngx_int_t webdav_dispatch_core_method (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t webdav_dispatch_copy_move_props (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t webdav_dispatch_lock_patch_search (ngx_http_request_t *r)
static ngx_int_t webdav_dispatch_method (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
static ngx_int_t webdav_dispatch_not_allowed (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
ngx_int_t ngx_http_brix_webdav_handler (ngx_http_request_t *r)
Function Documentation
ngx_http_brix_webdav_handler()
ngx_int_t ngx_http_brix_webdav_handler (ngx_http_request_t * r)
Definition at line 402 of file dispatch.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, and webdav_dispatch_inner().
Referenced by webdav_postconf_install_handlers().
webdav_dispatch_copy()
static ngx_int_t webdav_dispatch_copy (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 219 of file dispatch.c.
References ngx_http_brix_webdav_tpc_handle_copy(), ngx_http_brix_webdav_loc_conf_t::tpc, webdav_handle_copy(), webdav_metrics_return(), and webdav_tpc_find_header.
Referenced by webdav_dispatch_copy_move_props().
webdav_dispatch_copy_move_props()
static ngx_int_t webdav_dispatch_copy_move_props (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 293 of file dispatch.c.
References webdav_dispatch_copy(), webdav_dispatch_move(), webdav_handle_mkcol(), webdav_handle_propfind(), and webdav_metrics_return().
Referenced by webdav_dispatch_method().
webdav_dispatch_core_method()
static ngx_int_t webdav_dispatch_core_method (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 271 of file dispatch.c.
References webdav_dispatch_put(), webdav_handle_delete(), webdav_handle_get(), webdav_handle_head(), webdav_metrics_return(), xrdhttp_handle_stats_query(), and xrdhttp_request_is_stats_query().
Referenced by webdav_dispatch_method().
webdav_dispatch_delegation_gridsite()
static ngx_int_t webdav_dispatch_delegation_gridsite (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 143 of file dispatch.c.
References brix_http_read_body(), ngx_http_brix_webdav_loc_conf_t::delegation_endpoint, webdav_delegation_put_handle(), webdav_delegation_request_handle(), and webdav_metrics_return().
Referenced by webdav_dispatch_inner().
webdav_dispatch_delegation_upload()
static ngx_int_t webdav_dispatch_delegation_upload (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 122 of file dispatch.c.
References brix_http_read_body(), ngx_http_brix_webdav_loc_conf_t::delegation_endpoint, webdav_delegation_handle(), and webdav_metrics_return().
Referenced by webdav_dispatch_inner().
webdav_dispatch_draining()
static ngx_int_t webdav_dispatch_draining (ngx_http_request_t * r) static
Definition at line 29 of file dispatch.c.
References webdav_metrics_return().
Referenced by webdav_dispatch_inner().
webdav_dispatch_inner()
static ngx_int_t webdav_dispatch_inner (ngx_http_request_t * r) static
Definition at line 415 of file dispatch.c.
References brix_http_source_offer(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::enable, ngx_http_brix_webdav_module, ngx_http_brix_webdav_loc_conf_t::upstream_proxy, webdav_dispatch_delegation_gridsite(), webdav_dispatch_delegation_upload(), webdav_dispatch_draining(), webdav_dispatch_macaroon(), webdav_dispatch_method(), webdav_dispatch_not_allowed(), webdav_dispatch_pmark(), webdav_dispatch_tape_rest(), webdav_handle_options(), webdav_metrics_return(), webdav_proxy_handler(), webdav_sess_attempt_request(), and webdav_sess_begin_request().
Referenced by ngx_http_brix_webdav_handler().
webdav_dispatch_lock()
static ngx_int_t webdav_dispatch_lock (ngx_http_request_t * r) static
Definition at line 263 of file dispatch.c.
References brix_http_read_body(), webdav_handle_lock(), and webdav_metrics_return().
Referenced by webdav_dispatch_lock_patch_search().
webdav_dispatch_lock_patch_search()
static ngx_int_t webdav_dispatch_lock_patch_search (ngx_http_request_t * r) static
Definition at line 320 of file dispatch.c.
References webdav_dispatch_lock(), webdav_handle_acl(), webdav_handle_proppatch(), webdav_handle_search(), webdav_handle_unlock(), and webdav_metrics_return().
Referenced by webdav_dispatch_method().
webdav_dispatch_macaroon()
static ngx_int_t webdav_dispatch_macaroon (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 75 of file dispatch.c.
References brix_dig_handle(), brix_http_get_header(), brix_http_read_body(), ngx_http_brix_webdav_loc_conf_t::dig_enable, webdav_handle_macaroon_discovery(), webdav_handle_macaroon_request(), webdav_handle_macaroon_token(), and webdav_metrics_return().
Referenced by webdav_dispatch_inner().
webdav_dispatch_method()
static ngx_int_t webdav_dispatch_method (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 351 of file dispatch.c.
References webdav_dispatch_copy_move_props(), webdav_dispatch_core_method(), and webdav_dispatch_lock_patch_search().
Referenced by webdav_dispatch_inner().
webdav_dispatch_move()
static ngx_int_t webdav_dispatch_move (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 251 of file dispatch.c.
References webdav_handle_move(), webdav_lock_check_request_path(), and webdav_metrics_return().
Referenced by webdav_dispatch_copy_move_props().
webdav_dispatch_not_allowed()
static ngx_int_t webdav_dispatch_not_allowed (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 368 of file dispatch.c.
References brix_http_operation_allow_header(), BRIX_WEBDAV_ALLOW_FLAGS, brix_webdav_operations, brix_webdav_operations_count, and webdav_metrics_return().
Referenced by webdav_dispatch_inner().
webdav_dispatch_pmark()
static void webdav_dispatch_pmark (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 43 of file dispatch.c.
References brix_identity_dn_cstr(), brix_identity_vo_csv_cstr(), brix_pmark_http_mark(), ngx_http_brix_webdav_loc_conf_t::common, brix_pmark_conf_t::enable, brix_pmark_conf_t::http_plain, ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, and ngx_http_brix_shared_conf_t::pmark.
Referenced by webdav_dispatch_inner().
webdav_dispatch_put()
static ngx_int_t webdav_dispatch_put (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 205 of file dispatch.c.
References brix_http_read_body(), webdav_handle_put_body(), webdav_lock_check_request_path(), and webdav_metrics_return().
Referenced by webdav_dispatch_core_method().
webdav_dispatch_tape_rest()
static ngx_int_t webdav_dispatch_tape_rest (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 175 of file dispatch.c.
References ngx_http_brix_webdav_loc_conf_t::tape_rest, webdav_metrics_return(), and webdav_tape_handle().
Referenced by webdav_dispatch_inner().
webdav_lock_check_request_path()
static ngx_int_t webdav_lock_check_request_path (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf) static
Definition at line 191 of file dispatch.c.
References ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_resolve_path(), ngx_http_brix_shared_conf_t::root_canon, webdav_check_locks(), and WEBDAV_MAX_PATH.
Referenced by webdav_dispatch_move(), and webdav_dispatch_put().