nginx-xrootd: src/protocols/webdav/webdav_auth.h File Reference
webdav_auth.h File Reference
#include "webdav.h"
#include "fs/vfs/vfs.h"
Functions
ngx_int_t webdav_auth_init_ssl_indices (ngx_log_t *log)
X509_STORE * webdav_build_ca_store (ngx_log_t *log, ngx_http_brix_webdav_loc_conf_t *conf, int *crl_count_out)
ngx_int_t webdav_verify_proxy_cert (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
ngx_int_t webdav_verify_bearer_token (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
ngx_int_t webdav_verify_basic_pwd (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf)
ngx_int_t webdav_check_token_scope (ngx_http_request_t *r, const char *method_name)
ngx_int_t webdav_check_pki_consistency (ngx_log_t *log, ngx_http_brix_webdav_loc_conf_t *conf)
void webdav_vfs_bind_deleg (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, brix_vfs_ctx_t *vctx)
Function Documentation
webdav_auth_init_ssl_indices()
ngx_int_t webdav_auth_init_ssl_indices (ngx_log_t * log)
Definition at line 70 of file auth_cert.c.
References log, webdav_ssl_auth_cache_index, webdav_ssl_session_auth_cache_index, and webdav_tls_auth_cache_free().
Referenced by ngx_http_brix_webdav_postconfiguration().
webdav_build_ca_store()
X509_STORE * webdav_build_ca_store (ngx_log_t * log, ngx_http_brix_webdav_loc_conf_t * conf, int * crl_count_out)
Definition at line 19 of file auth_store.c.
References brix_build_ca_store(), brix_str_cbuf(), ngx_http_brix_webdav_loc_conf_t::cadir, ngx_http_brix_webdav_loc_conf_t::cafile, ngx_http_brix_webdav_loc_conf_t::crl, ngx_http_brix_webdav_loc_conf_t::crl_mode, log, PATH_MAX, and ngx_http_brix_webdav_loc_conf_t::signing_policy_mode.
Referenced by webdav_build_ca_store_once().
webdav_check_pki_consistency()
ngx_int_t webdav_check_pki_consistency (ngx_log_t * log, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 15 of file pki.c.
References brix_pki_check_paths(), ngx_http_brix_webdav_loc_conf_t::cadir, ngx_http_brix_webdav_loc_conf_t::cafile, ngx_http_brix_webdav_loc_conf_t::crl, and log.
Referenced by webdav_build_ca_store_once().
webdav_check_token_scope()
ngx_int_t webdav_check_token_scope (ngx_http_request_t * r, const char * method_name)
Definition at line 69 of file auth_token.c.
References brix_identity_check_token_scope(), brix_token_check_read(), brix_token_check_write(), BRIX_TOKEN_OP_WRITE, ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, ngx_memcpy, ngx_http_brix_webdav_req_ctx_t::token_auth, ngx_http_brix_webdav_req_ctx_t::token_scope_count, ngx_http_brix_webdav_req_ctx_t::token_scopes, WEBDAV_MAX_PATH, and webdav_token_op_class().
Referenced by access_check_scope().
webdav_verify_basic_pwd()
ngx_int_t webdav_verify_basic_pwd (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 144 of file auth_basic.c.
References ngx_http_brix_webdav_req_ctx_t::auth_source, BRIX_AUTHN_PWD, brix_identity_set_dn(), brix_identity_set_vos_csv(), brix_metric_auth(), BRIX_PROTO_WEBDAV, brix_pwd_file_lookup(), BRIX_PWD_HASH_LEN, BRIX_PWD_MAX_SALT, brix_pwd_verify(), ngx_http_brix_webdav_req_ctx_t::dn, ngx_http_brix_webdav_req_ctx_t::identity, ngx_memcpy, PATH_MAX, ngx_http_brix_webdav_loc_conf_t::pwd_file, ngx_http_brix_webdav_req_ctx_t::verified, wb_ensure_ctx(), and wb_parse_basic_userpass().
Referenced by access_try_basic().
webdav_verify_bearer_token()
ngx_int_t webdav_verify_bearer_token (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 521 of file auth_token.c.
References brix_macaroon_secret_parse(), brix_token_cache_store(), brix_token_l1_store(), wt_validate_ctx_t::claims, wt_validate_ctx_t::conf, ngx_http_brix_webdav_loc_conf_t::jwks_key_count, wt_validate_ctx_t::r, wt_validate_ctx_t::secret, wt_validate_ctx_t::slen, wt_validate_ctx_t::token, ngx_http_brix_webdav_req_ctx_t::token_auth, ngx_http_brix_webdav_loc_conf_t::token_cache_kv, ngx_http_brix_webdav_loc_conf_t::token_l1, wt_validate_ctx_t::token_len, ngx_http_brix_webdav_loc_conf_t::token_macaroon_secret, ngx_http_brix_webdav_loc_conf_t::token_registry, wt_check_claims(), wt_check_issuer_keys(), wt_ensure_ctx(), and wt_parse_header().
Referenced by access_try_token().
webdav_verify_proxy_cert()
ngx_int_t webdav_verify_proxy_cert (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 461 of file auth_cert.c.
References brix_gsi_verify_chain(), BRIX_PCALLOC_OR_RETURN, ngx_http_brix_webdav_loc_conf_t::ca_store, ngx_http_brix_webdav_module, STACK_OF(), ngx_http_brix_webdav_req_ctx_t::verified, ngx_http_brix_webdav_loc_conf_t::verify_depth, webdav_finish_verified_cert(), webdav_free_verify_resources(), webdav_nginx_verify_compatible(), and webdav_try_cached_tls_auth().
Referenced by access_try_cert().
webdav_vfs_bind_deleg()
void webdav_vfs_bind_deleg (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, brix_vfs_ctx_t * vctx)
Definition at line 669 of file access.c.
References ngx_http_brix_shared_conf_t::backend_delegation, ngx_http_brix_webdav_req_ctx_t::bearer_token, BRIX_CRED_SELECT, brix_vfs_deleg_bind(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::deleg_proxy_pem, and ngx_http_brix_webdav_module.
Referenced by get_init_vfs_ctx(), webdav_copy_file_vfs_init(), webdav_copy_probe(), webdav_lock_vfs_ctx_init(), webdav_move_execute_cred(), webdav_move_probe(), webdav_ns_vfs_ctx_init(), webdav_put_precheck(), webdav_put_vfs_ctx_init(), and webdav_resolve_stat().