nginx-xrootd: src/protocols/webdav/webdav_tpc.h File Reference
webdav_tpc.h File Reference
#include "webdav.h"
Data Structures
struct tpc_ms_progress_t
struct webdav_tpc_req_t
Macros
#define BRIX_TPC_MAX_STREAMS 16
#define webdav_tpc_find_header(r, name, name_len) brix_http_find_header(r, name, name_len)
#define webdav_tpc_str_has_ctl(data, len) brix_http_str_has_ctl(data, len)
#define webdav_tpc_header_value_equals(value, literal) brix_http_header_value_equals(value, literal)
Functions
void ngx_http_brix_webdav_tpc_create_loc_conf (ngx_http_brix_webdav_loc_conf_t *conf)
void ngx_http_brix_webdav_tpc_merge_loc_conf (ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_loc_conf_t *prev)
static char * webdav_tpc_pstrndup0 (ngx_pool_t *pool, const u_char *data, size_t len)
ngx_int_t webdav_tpc_collect_transfer_headers (ngx_http_request_t *r, ngx_array_t **out)
ngx_int_t webdav_tpc_run_curl_pull (ngx_log_t *log, ngx_http_brix_webdav_loc_conf_t *conf, const char *source_url, const char *tmp_path, ngx_array_t *transfer_headers, uint64_t transfer_id, const char *user_cert, const char *user_key)
ngx_int_t webdav_tpc_run_curl_push (ngx_log_t *log, ngx_http_brix_webdav_loc_conf_t *conf, const char *dest_url, const char *local_path, ngx_array_t *transfer_headers, uint64_t transfer_id)
ngx_int_t webdav_tpc_post_thread_task (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, int is_push, ngx_flag_t existed, ngx_flag_t overwrite, const char *url, const char *local_path, const char *dest_path, ngx_array_t *transfer_headers, ngx_uint_t n_streams, const char *user_cert, const char *user_key)
ngx_int_t webdav_tpc_run_curl_pull_multi (ngx_log_t *log, ngx_http_brix_webdav_loc_conf_t *conf, const char *source_url, const char *tmp_path, ngx_array_t *transfer_headers, ngx_uint_t n_streams, uint64_t transfer_id, tpc_ms_progress_t *progress, const char *user_cert, const char *user_key)
ngx_int_t webdav_tpc_marker_start (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_uint_t n_streams, const char *url, const char *tmp_path, const char *final_path, ngx_flag_t is_pull, ngx_flag_t overwrite, ngx_flag_t existed, ngx_array_t *transfer_headers, uint64_t transfer_id, const char *user_cert, const char *user_key)
ngx_int_t ngx_http_brix_webdav_tpc_handle_copy (ngx_http_request_t *r)
WHAT: Handle HTTP-TPC (Third-Party Copy) COPY requests — implements GridFTP-style cross-server file transfer layered on WebDAV.
brix_tpc_cred_mode_e webdav_tpc_cred_parse_mode (const char *value, size_t len)
Parse a Credential: header value into a mode enum.
ngx_int_t webdav_tpc_cred_obtain_token (ngx_http_request_t *r, brix_tpc_cred_mode_e mode, const char *source_url, const char *subject_token, const char *scope, ngx_str_t *token_out)
Obtain an access token for a TPC pull transfer.
const char * webdav_tpc_cred_metric_name (brix_tpc_cred_metrics_e idx)
Return the name string for a cred-metrics counter index.
Macro Definition Documentation
BRIX_TPC_MAX_STREAMS
#define BRIX_TPC_MAX_STREAMS 16
Definition at line 18 of file webdav_tpc.h.
webdav_tpc_find_header
#define webdav_tpc_find_header (r, name, name_len) brix_http_find_header(r, name, name_len)
Definition at line 70 of file webdav_tpc.h.
webdav_tpc_header_value_equals
#define webdav_tpc_header_value_equals (value, literal) brix_http_header_value_equals(value, literal)
Definition at line 74 of file webdav_tpc.h.
webdav_tpc_str_has_ctl
#define webdav_tpc_str_has_ctl (data, len) brix_http_str_has_ctl(data, len)
Definition at line 72 of file webdav_tpc.h.
Function Documentation
ngx_http_brix_webdav_tpc_create_loc_conf()
void ngx_http_brix_webdav_tpc_create_loc_conf (ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 9 of file tpc_config.c.
References ngx_http_brix_webdav_loc_conf_t::tpc, ngx_http_brix_webdav_loc_conf_t::tpc_allow_local, ngx_http_brix_webdav_loc_conf_t::tpc_allow_private, ngx_http_brix_webdav_loc_conf_t::tpc_credential_forward, ngx_http_brix_webdav_loc_conf_t::tpc_low_speed_bytes, ngx_http_brix_webdav_loc_conf_t::tpc_low_speed_secs, ngx_http_brix_webdav_loc_conf_t::tpc_marker_interval, ngx_http_brix_webdav_loc_conf_t::tpc_max_streams, and ngx_http_brix_webdav_loc_conf_t::tpc_timeout.
Referenced by ngx_http_brix_webdav_create_loc_conf().
ngx_http_brix_webdav_tpc_handle_copy()
ngx_int_t ngx_http_brix_webdav_tpc_handle_copy (ngx_http_request_t * r)
WHAT: Handle HTTP-TPC (Third-Party Copy) COPY requests — implements GridFTP-style cross-server file transfer layered on WebDAV.
Supports two modes: pull (fetch remote → local) and push (local → upload remote). Both modes use external curl process to perform the actual data transfer while nginx handles authentication, path confinement, and HTTP header management. Returns 201 Created for new files or 204 No Content for overwrites on pull; 201 Created on push success. Rejects requests with ambiguous headers (both Source + Destination present) or missing required headers via 400 Bad Request. Uses temporary file staging (<path>.nginx-xrootd-tpc.<pid>.<time>) for pull mode to ensure atomic commit — rename/link on success, unlink on failure.
Definition at line 218 of file tpc.c.
References webdav_tpc_pull_ctx_t::conf, webdav_tpc_pull_ctx_t::n_streams, ngx_http_brix_webdav_module, webdav_tpc_pull_ctx_t::overwrite, webdav_tpc_pull_ctx_t::path, webdav_tpc_pull_ctx_t::path_len, webdav_tpc_pull_ctx_t::r, webdav_tpc_pull_ctx_t::sb, webdav_tpc_pull_ctx_t::source_url, webdav_tpc_pull_ctx_t::staged, stat(), webdav_tpc_pull_ctx_t::transfer_headers, WEBDAV_MAX_PATH, webdav_tpc_apply_credential_delegation(), webdav_tpc_apply_user_proxy(), webdav_tpc_collect_transfer_headers(), webdav_tpc_find_header, webdav_tpc_forward_user_bearer(), webdav_tpc_handle_push(), webdav_tpc_parse_overwrite(), webdav_tpc_parse_stream_count(), webdav_tpc_prepare_pull_target(), webdav_tpc_pull_execute(), webdav_tpc_pull_start_accounting(), webdav_tpc_source_url(), and webdav_tpc_validate_copy_headers().
Referenced by webdav_dispatch_copy().
ngx_http_brix_webdav_tpc_merge_loc_conf()
void ngx_http_brix_webdav_tpc_merge_loc_conf (ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_loc_conf_t * prev)
Definition at line 24 of file tpc_config.c.
References ngx_http_brix_webdav_loc_conf_t::cadir, ngx_http_brix_webdav_loc_conf_t::cafile, ngx_http_brix_tpc_conf_t::token_client_id, ngx_http_brix_tpc_conf_t::token_client_secret, ngx_http_brix_tpc_conf_t::token_endpoint, ngx_http_brix_tpc_conf_t::token_scope, ngx_http_brix_webdav_loc_conf_t::tpc, ngx_http_brix_webdav_loc_conf_t::tpc_allow_local, ngx_http_brix_webdav_loc_conf_t::tpc_allow_private, ngx_http_brix_webdav_loc_conf_t::tpc_cadir, ngx_http_brix_webdav_loc_conf_t::tpc_cafile, ngx_http_brix_webdav_loc_conf_t::tpc_cert, ngx_http_brix_webdav_loc_conf_t::tpc_cred, ngx_http_brix_webdav_loc_conf_t::tpc_credential_forward, ngx_http_brix_webdav_loc_conf_t::tpc_curl, ngx_http_brix_webdav_loc_conf_t::tpc_key, ngx_http_brix_webdav_loc_conf_t::tpc_low_speed_bytes, ngx_http_brix_webdav_loc_conf_t::tpc_low_speed_secs, ngx_http_brix_webdav_loc_conf_t::tpc_marker_interval, ngx_http_brix_webdav_loc_conf_t::tpc_max_streams, and ngx_http_brix_webdav_loc_conf_t::tpc_timeout.
Referenced by webdav_merge_base_conf().
webdav_tpc_collect_transfer_headers()
ngx_int_t webdav_tpc_collect_transfer_headers (ngx_http_request_t * r, ngx_array_t ** out)
Definition at line 20 of file tpc_headers.c.
References key, ngx_pnalloc(), WEBDAV_TPC_MAX_HEADERS, and webdav_tpc_str_has_ctl.
Referenced by ngx_http_brix_webdav_tpc_handle_copy(), and webdav_tpc_handle_push().
webdav_tpc_cred_metric_name()
const char * webdav_tpc_cred_metric_name (brix_tpc_cred_metrics_e idx)
Return the name string for a cred-metrics counter index.
Definition at line 228 of file tpc_cred.c.
References BRIX_TPC_CRED_NERROR, BRIX_TPC_CRED_NPARSE_ERROR, BRIX_TPC_CRED_NSTARTED, BRIX_TPC_CRED_NSUCCESS, and BRIX_TPC_CRED_NUNKNOWN_MODE.
webdav_tpc_cred_obtain_token()
ngx_int_t webdav_tpc_cred_obtain_token (ngx_http_request_t * r, brix_tpc_cred_mode_e mode, const char * source_url, const char * subject_token, const char * scope, ngx_str_t * token_out)
Obtain an access token for a TPC pull transfer.
Parameters
r the current ngx_http_request_t
mode parsed credential-delegation mode
source_url the Source: URL (used as issuer/audience)
subject_token the authenticated session token (JWT), may be NULL for oidc-agent mode; required for token-exchange
scope scope string to request (e.g. "storage.read")
token_out [out] allocated in r->pool; caller must not free
Returns
NGX_OK on success; NGX_ERROR on failure (error already logged)
Definition at line 190 of file tpc_cred.c.
References BRIX_TPC_CRED_NSTARTED, BRIX_TPC_CRED_NUNKNOWN_MODE, BRIX_TPC_CRED_OIDC_AGENT, BRIX_TPC_CRED_TOKEN_EXCHANGE, ngx_http_brix_webdav_module, scope, tpc_cred_run_oidc_agent(), tpc_cred_run_token_exchange(), and webdav_tpc_cred_metric_increment().
Referenced by webdav_tpc_apply_credential_delegation(), and webdav_tpc_push_apply_credential().
webdav_tpc_cred_parse_mode()
brix_tpc_cred_mode_e webdav_tpc_cred_parse_mode (const char * value, size_t len)
Parse a Credential: header value into a mode enum.
Returns BRIX_TPC_CRED_UNKNOWN for unrecognised values.
Definition at line 72 of file tpc_cred.c.
References BRIX_TPC_CRED_NONE, BRIX_TPC_CRED_OIDC_AGENT, BRIX_TPC_CRED_TOKEN_EXCHANGE, and BRIX_TPC_CRED_UNKNOWN.
Referenced by webdav_tpc_apply_credential_delegation(), and webdav_tpc_push_apply_credential().
webdav_tpc_marker_start()
ngx_int_t webdav_tpc_marker_start (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_uint_t n_streams, const char * url, const char * tmp_path, const char * final_path, ngx_flag_t is_pull, ngx_flag_t overwrite, ngx_flag_t existed, ngx_array_t * transfer_headers, uint64_t transfer_id, const char * user_cert, const char * user_key)
Definition at line 296 of file tpc_marker_start.c.
References BRIX_TPC_MAX_STREAMS, ngx_http_brix_webdav_loc_conf_t::common, tpc_marker_start_args_t::conf, tpc_marker_start_args_t::existed, tpc_marker_start_args_t::final_path, tpc_marker_start_args_t::is_pull, tpc_marker_ctx_t::last_marker_time, tpc_marker_start_args_t::n_streams, tpc_marker_start_args_t::overwrite, tpc_marker_start_args_t::r, ngx_http_brix_shared_conf_t::thread_pool, tpc_marker_ctx_t::timer, tpc_marker_start_args_t::tmp_path, tpc_marker_arm_lifecycle(), tpc_marker_build_ctx(), tpc_marker_build_task(), TPC_MARKER_POLL_MSEC, tpc_marker_send_accepted(), tpc_marker_send_all(), tpc_marker_start_args_t::transfer_headers, tpc_marker_start_args_t::transfer_id, tpc_marker_start_args_t::url, tpc_marker_start_args_t::user_cert, and tpc_marker_start_args_t::user_key.
Referenced by webdav_tpc_pull_marker_exec().
webdav_tpc_post_thread_task()
ngx_int_t webdav_tpc_post_thread_task (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, int is_push, ngx_flag_t existed, ngx_flag_t overwrite, const char * url, const char * local_path, const char * dest_path, ngx_array_t * transfer_headers, ngx_uint_t n_streams, const char * user_cert, const char * user_key)
Definition at line 437 of file tpc_thread.c.
References brix_tpc_registry_remove(), ngx_http_brix_webdav_loc_conf_t::common, tpc_thread_ctx_t::conf, tpc_thread_ctx_t::existed, tpc_thread_ctx_t::is_push, tpc_thread_ctx_t::log, tpc_thread_ctx_t::n_streams, tpc_thread_ctx_t::overwrite, tpc_thread_ctx_t::r, ngx_http_brix_shared_conf_t::thread_pool, tpc_thread_ctx_copy_paths(), tpc_thread_done(), tpc_thread_func(), tpc_thread_ctx_t::transfer_headers, tpc_thread_ctx_t::transfer_id, tpc_thread_ctx_t::url, tpc_thread_ctx_t::user_cert, tpc_thread_ctx_t::user_key, and webdav_tpc_thread_register().
Referenced by webdav_tpc_pull_thread_exec(), and webdav_tpc_push_post_thread().
webdav_tpc_pstrndup0()
static char * webdav_tpc_pstrndup0 (ngx_pool_t * pool, const u_char * data, size_t len) inline static
Definition at line 79 of file webdav_tpc.h.
References ngx_memcpy, and ngx_pnalloc().
Referenced by webdav_tpc_extract_subject_token(), webdav_tpc_push_dest_url(), and webdav_tpc_source_url().
webdav_tpc_run_curl_pull()
ngx_int_t webdav_tpc_run_curl_pull (ngx_log_t * log, ngx_http_brix_webdav_loc_conf_t * conf, const char * source_url, const char * tmp_path, ngx_array_t * transfer_headers, uint64_t transfer_id, const char * user_cert, const char * user_key)
Definition at line 379 of file tpc_curl.c.
References log, and webdav_tpc_run_curl_core().
Referenced by tpc_marker_thread_func(), tpc_thread_pull_fetch(), webdav_tpc_pull_sync_exec(), and webdav_tpc_run_curl_pull_multi().
webdav_tpc_run_curl_pull_multi()
ngx_int_t webdav_tpc_run_curl_pull_multi (ngx_log_t * log, ngx_http_brix_webdav_loc_conf_t * conf, const char * source_url, const char * tmp_path, ngx_array_t * transfer_headers, ngx_uint_t n_streams, uint64_t transfer_id, tpc_ms_progress_t * progress, const char * user_cert, const char * user_key)
Definition at line 229 of file tpc_curl_multi.c.
References BRIX_TPC_MAX_STREAMS, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_TPC_CURL_STARTED, close(), webdav_tpc_ms_ctx_t::cm, webdav_tpc_ms_ctx_t::conf, webdav_tpc_ms_ctx_t::easy, webdav_tpc_ms_ctx_t::fd, webdav_tpc_ms_ctx_t::hdrs, log, webdav_tpc_ms_ctx_t::log, webdav_tpc_ms_ctx_t::n_streams, webdav_tpc_ms_ctx_t::progress, webdav_tpc_ms_ctx_t::resolve, webdav_tpc_ms_ctx_t::source_url, webdav_tpc_ms_ctx_t::tmp_path, webdav_tpc_ms_ctx_t::total_size, tpc_ms_progress_t::total_size, tpc_curl_head_size(), tpc_ms_drive(), tpc_ms_harvest(), tpc_ms_prepare_output(), tpc_ms_setup_stream(), webdav_tpc_ms_ctx_t::transfer_headers, webdav_tpc_ms_ctx_t::user_cert, webdav_tpc_ms_ctx_t::user_key, webdav_tpc_run_curl_multi_finish(), webdav_tpc_run_curl_pull(), and webdav_tpc_ms_ctx_t::write_ctx.
Referenced by tpc_marker_thread_func(), and tpc_thread_pull_fetch().
webdav_tpc_run_curl_push()
ngx_int_t webdav_tpc_run_curl_push (ngx_log_t * log, ngx_http_brix_webdav_loc_conf_t * conf, const char * dest_url, const char * local_path, ngx_array_t * transfer_headers, uint64_t transfer_id)
Definition at line 393 of file tpc_curl.c.
References log, and webdav_tpc_run_curl_core().
Referenced by tpc_marker_thread_func(), tpc_thread_run_push(), and webdav_tpc_push_sync_exec().