nginx-xrootd: src/protocols/webdav/webdav_proxy.h File Reference
webdav_proxy.h File Reference
#include "webdav.h"
Functions
ngx_int_t webdav_proxy_handler (ngx_http_request_t *r)
ngx_int_t webdav_proxy_parse_upstream_url (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
ngx_int_t webdav_proxy_build_backends (ngx_conf_t *cf, ngx_http_brix_webdav_loc_conf_t *conf)
char * webdav_conf_proxy_upstream (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
Function Documentation
webdav_conf_proxy_upstream()
char * webdav_conf_proxy_upstream (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 206 of file module_directives.c.
References ngx_http_brix_webdav_loc_conf_t::upstream_url, and ngx_http_brix_webdav_loc_conf_t::upstream_urls.
webdav_proxy_build_backends()
ngx_int_t webdav_proxy_build_backends (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 151 of file proxy_config.c.
References brix_webdav_backend_t::host, brix_webdav_backend_t::resolved, brix_webdav_backend_t::ssl, ngx_http_brix_webdav_loc_conf_t::upstream_backends, ngx_http_brix_webdav_loc_conf_t::upstream_conf, ngx_http_brix_webdav_loc_conf_t::upstream_host, ngx_http_brix_webdav_loc_conf_t::upstream_resolved, ngx_http_brix_webdav_loc_conf_t::upstream_ssl, ngx_http_brix_webdav_loc_conf_t::upstream_url, ngx_http_brix_webdav_loc_conf_t::upstream_url_base, ngx_http_brix_webdav_loc_conf_t::upstream_urls, brix_webdav_backend_t::url_base, and webdav_proxy_add_url().
Referenced by ngx_http_brix_webdav_merge_loc_conf(), and webdav_proxy_parse_upstream_url().
webdav_proxy_handler()
ngx_int_t webdav_proxy_handler (ngx_http_request_t * r)
Definition at line 22 of file proxy.c.
References brix_http_read_body(), brix_proxy_pool_dec_in_flight(), brix_proxy_pool_select(), brix_webdav_backend_t::host, brix_proxy_be_pick_t::host, brix_proxy_be_pick_t::id, ngx_http_brix_webdav_module, ngx_memcpy, ngx_pcalloc(), brix_proxy_be_pick_t::port, webdav_proxy_ctx_t::proxy_be_id, ngx_http_brix_webdav_loc_conf_t::proxy_pool_enabled, brix_webdav_backend_t::resolved, webdav_proxy_ctx_t::selected_backend, brix_proxy_be_pick_t::sockaddr, brix_proxy_be_pick_t::socklen, brix_webdav_backend_t::ssl, brix_proxy_be_pick_t::ssl, ngx_http_brix_webdav_loc_conf_t::upstream_conf, brix_webdav_backend_t::url_base, brix_proxy_be_pick_t::url_base, webdav_proxy_abort_request(), webdav_proxy_create_request(), webdav_proxy_finalize_request(), webdav_proxy_pick_backend(), webdav_proxy_process_status_line(), and webdav_proxy_reinit_request().
Referenced by webdav_dispatch_inner().
webdav_proxy_parse_upstream_url()
ngx_int_t webdav_proxy_parse_upstream_url (ngx_conf_t * cf, ngx_http_brix_webdav_loc_conf_t * conf)
Definition at line 229 of file proxy_config.c.
References webdav_proxy_build_backends().