nginx-xrootd: src/protocols/webdav/webdav.h File Reference
webdav.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include <ngx_thread_pool.h>
#include <stdint.h>
#include <sys/stat.h>
#include "observability/metrics/metrics.h"
#include "core/compat/error_mapping.h"
#include "core/http/http_headers.h"
#include "core/compat/log.h"
#include "auth/token/token.h"
#include "core/types/identity.h"
#include "auth/authz/acc/acc.h"
#include "tpc_config.h"
#include "tpc_cred.h"
#include "core/compat/path.h"
#include "core/compat/protocol_caps.h"
#include "core/config/shared_conf.h"
#include "core/shm/kv.h"
#include "net/mirror/mirror.h"
#include "core/shm/rate_limit.h"
#include "observability/sesslog/sesslog.h"
#include <ngx_open_file_cache.h>
#include "xrdhttp.h"
#include "webdav_path.h"
#include "webdav_lock.h"
#include "webdav_metrics.h"
#include "webdav_auth.h"
#include "webdav_methods.h"
#include "webdav_props.h"
#include "webdav_tpc.h"
#include "webdav_proxy.h"
Data Structures
struct webdav_lock_xattr_t
struct brix_dig_export_t
struct ngx_http_brix_webdav_loc_conf_t
struct ngx_http_brix_webdav_req_ctx_t
Macros
#define WEBDAV_MAX_PATH BRIX_PATH_MAX
#define WEBDAV_FD_TABLE_SIZE 16
#define WEBDAV_PUT_COPY_BUFSZ (1024 * 1024)
#define WEBDAV_PUT_COPY_CHUNK (16 * 1024 * 1024)
#define WEBDAV_TPC_MAX_HEADERS 64
#define WEBDAV_LOCK_XATTR_KEY "user.nginx_xrootd.lock"
#define WEBDAV_LOCK_XATTR_MAXLEN 512
#define BRIX_WEBDAV_ALLOW_FLAGS(conf)
Typedefs
typedef struct x509_store_st X509_STORE
Enumerations
enum webdav_auth_t { WEBDAV_AUTH_NONE , WEBDAV_AUTH_OPTIONAL , WEBDAV_AUTH_REQUIRED }
enum webdav_proxy_auth_t { WEBDAV_PROXY_AUTH_ANONYMOUS , WEBDAV_PROXY_AUTH_FORWARD , WEBDAV_PROXY_AUTH_TOKEN }
Functions
size_t brix_sanitize_log_string (const char *in, char *out, size_t outsz)
int brix_open_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, int flags, mode_t mode)
int brix_unlink_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, int is_dir)
int brix_mkdir_confined_canon (ngx_log_t *log, const char *root_canon, const char *resolved, mode_t mode)
int brix_rename_confined_canon (ngx_log_t *log, const char *root_canon, const char *src_resolved, const char *dst_resolved)
int brix_link_confined_canon (ngx_log_t *log, const char *root_canon, const char *src_resolved, const char *dst_resolved)
void * brix_webdav_backend_instance (ngx_http_brix_webdav_loc_conf_t *conf, ngx_log_t *log)
void * ngx_http_brix_webdav_create_loc_conf (ngx_conf_t *cf)
char * ngx_http_brix_webdav_merge_loc_conf (ngx_conf_t *cf, void *parent, void *child)
ngx_int_t ngx_http_brix_webdav_postconfiguration (ngx_conf_t *cf)
ngx_int_t ngx_http_brix_webdav_access_handler (ngx_http_request_t *r)
ngx_int_t ngx_http_brix_webdav_handler (ngx_http_request_t *r)
ngx_int_t webdav_introspect_access_handler (ngx_http_request_t *r)
char * webdav_conf_revoke_cache (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * webdav_conf_authdb (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * webdav_conf_require_vo (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
static ngx_int_t webdav_send_no_body (ngx_http_request_t *r, ngx_uint_t status)
Variables
ngx_module_t ngx_http_brix_webdav_module
const brix_http_operation_t brix_webdav_operations []
const ngx_uint_t brix_webdav_operations_count
Macro Definition Documentation
BRIX_WEBDAV_ALLOW_FLAGS
#define BRIX_WEBDAV_ALLOW_FLAGS (conf)
Value:
    (BRIX_PROTO_OP_READ | BRIX_PROTO_OP_LIST                           \
     | ((conf)->common.allow_write                                          \
            ? (BRIX_PROTO_OP_WRITE | BRIX_PROTO_OP_LOCK) : 0)         \
     | ((conf)->tpc ? BRIX_PROTO_OP_TPC : 0))
Definition at line 498 of file webdav.h.
WEBDAV_FD_TABLE_SIZE
#define WEBDAV_FD_TABLE_SIZE 16
Definition at line 80 of file webdav.h.
WEBDAV_LOCK_XATTR_KEY
#define WEBDAV_LOCK_XATTR_KEY "user.nginx_xrootd.lock"
Definition at line 86 of file webdav.h.
WEBDAV_LOCK_XATTR_MAXLEN
#define WEBDAV_LOCK_XATTR_MAXLEN 512
Definition at line 87 of file webdav.h.
WEBDAV_MAX_PATH
#define WEBDAV_MAX_PATH BRIX_PATH_MAX
Definition at line 79 of file webdav.h.
WEBDAV_PUT_COPY_BUFSZ
#define WEBDAV_PUT_COPY_BUFSZ (1024 * 1024)
Definition at line 81 of file webdav.h.
WEBDAV_PUT_COPY_CHUNK
#define WEBDAV_PUT_COPY_CHUNK (16 * 1024 * 1024)
Definition at line 82 of file webdav.h.
WEBDAV_TPC_MAX_HEADERS
#define WEBDAV_TPC_MAX_HEADERS 64
Definition at line 83 of file webdav.h.
Typedef Documentation
X509_STORE
typedef struct x509_store_st X509_STORE
Definition at line 77 of file webdav.h.
Enumeration Type Documentation
webdav_auth_t
enum webdav_auth_t
Enumerator
WEBDAV_AUTH_NONE
WEBDAV_AUTH_OPTIONAL
WEBDAV_AUTH_REQUIRED
Definition at line 89 of file webdav.h.
webdav_proxy_auth_t
enum webdav_proxy_auth_t
Enumerator
WEBDAV_PROXY_AUTH_ANONYMOUS
WEBDAV_PROXY_AUTH_FORWARD
WEBDAV_PROXY_AUTH_TOKEN
Definition at line 95 of file webdav.h.
Function Documentation
brix_link_confined_canon()
int brix_link_confined_canon (ngx_log_t * log, const char * root_canon, const char * src_resolved, const char * dst_resolved)
Definition at line 341 of file resolve_confined_ops.c.
brix_mkdir_confined_canon()
int brix_mkdir_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, mode_t mode)
Definition at line 217 of file resolve_confined_ops.c.
brix_open_confined_canon()
int brix_open_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, int flags, mode_t mode)
Definition at line 95 of file resolve_confined_ops.c.
Referenced by brix_open_confined().
brix_rename_confined_canon()
int brix_rename_confined_canon (ngx_log_t * log, const char * root_canon, const char * src_resolved, const char * dst_resolved)
Definition at line 323 of file resolve_confined_ops.c.
brix_sanitize_log_string()
size_t brix_sanitize_log_string (const char * in, char * out, size_t outsz)
Definition at line 46 of file helpers.c.
brix_unlink_confined_canon()
int brix_unlink_confined_canon (ngx_log_t * log, const char * root_canon, const char * resolved, int is_dir)
Definition at line 185 of file resolve_confined_ops.c.
brix_webdav_backend_instance()
void * brix_webdav_backend_instance (ngx_http_brix_webdav_loc_conf_t * conf, ngx_log_t * log)
Definition at line 105 of file config.c.
References brix_vfs_backend_resolve(), ngx_http_brix_webdav_loc_conf_t::common, log, and ngx_http_brix_shared_conf_t::root_canon.
Referenced by webdav_handle_get(), webdav_handle_move(), webdav_move_collection_post_task(), and webdav_put_vfs_ctx_init().
ngx_http_brix_webdav_access_handler()
ngx_int_t ngx_http_brix_webdav_access_handler (ngx_http_request_t * r)
Definition at line 127 of file access.c.
References ngx_http_brix_shared_conf_t::allow_write, ngx_http_brix_webdav_loc_conf_t::auth, ngx_http_brix_webdav_loc_conf_t::authdb_rules, BRIX_AUTH_READ, BRIX_AUTHN_GSI, BRIX_AUTHN_NONE, BRIX_AUTHN_TOKEN, brix_check_authdb_identity(), brix_check_vo_acl_identity(), brix_http_operation_find(), brix_metric_auth(), BRIX_PROTO_WEBDAV, brix_rate_limit_check(), BRIX_WEBDAV_AUTH_RESULT_ANONYMOUS, BRIX_WEBDAV_AUTH_RESULT_CERT_OK, BRIX_WEBDAV_AUTH_RESULT_NONE, BRIX_WEBDAV_AUTH_RESULT_REJECTED, BRIX_WEBDAV_AUTH_RESULT_TOKEN_OK, BRIX_WEBDAV_CORS_PREFLIGHT, BRIX_WEBDAV_METRIC_INC, brix_webdav_operations, brix_webdav_operations_count, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::enable, ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_req_ctx_t::is_mirror, brix_rate_limit_conf_t::kv, brix_http_operation_t::name, ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), ngx_memcpy, PATH_MAX, ngx_http_brix_webdav_loc_conf_t::rate_limit, ngx_http_brix_shared_conf_t::root_canon, ngx_http_brix_webdav_loc_conf_t::upstream_proxy, ngx_http_brix_webdav_loc_conf_t::vo_rules, webdav_acc_check(), webdav_add_cors_headers(), WEBDAV_AUTH_NONE, WEBDAV_AUTH_REQUIRED, webdav_check_token_scope(), webdav_is_write_method(), webdav_metrics_request(), webdav_metrics_return(), webdav_tpc_find_header, webdav_verify_bearer_token(), webdav_verify_proxy_cert(), xrdhttp_inject_tpc_headers(), and xrdhttp_parse_request().
Referenced by ngx_http_brix_webdav_postconfiguration().
ngx_http_brix_webdav_create_loc_conf()
void * ngx_http_brix_webdav_create_loc_conf (ngx_conf_t * cf)
Definition at line 115 of file config.c.
References ngx_http_brix_webdav_loc_conf_t::acc, ngx_http_brix_webdav_loc_conf_t::auth, ngx_http_brix_webdav_loc_conf_t::authdb_rules, brix_acc_http_init_conf(), BRIX_PCALLOC_OR_RETURN, brix_rate_limit_conf_t::burst, ngx_http_brix_webdav_loc_conf_t::ca_store, ngx_http_brix_webdav_loc_conf_t::checksum_xattr_format, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_loc_conf_t::cors_credentials, ngx_http_brix_webdav_loc_conf_t::cors_max_age, ngx_http_brix_webdav_loc_conf_t::cors_origins, ngx_http_brix_webdav_loc_conf_t::crl_mode, ngx_http_brix_webdav_loc_conf_t::dig_enable, ngx_http_brix_webdav_loc_conf_t::dig_exports, brix_mirror_conf_t::enabled, ngx_http_brix_webdav_loc_conf_t::http_query_token, ngx_http_brix_webdav_loc_conf_t::introspect_fail_open, ngx_http_brix_webdav_loc_conf_t::introspect_ttl, brix_rate_limit_conf_t::key_ip, brix_rate_limit_conf_t::kv, ngx_http_brix_webdav_loc_conf_t::lock_startup_sweep, ngx_http_brix_webdav_loc_conf_t::lock_timeout, brix_mirror_conf_t::log_diverge, ngx_http_brix_webdav_loc_conf_t::macaroon_max_validity, brix_mirror_conf_t::method_mask, ngx_http_brix_webdav_loc_conf_t::mirror, ngx_http_brix_webdav_loc_conf_t::mirror_upstream_conf, brix_mirror_conf_t::mirror_writes, ngx_http_brix_shared_init(), ngx_http_brix_webdav_tpc_create_loc_conf(), brix_mirror_conf_t::opcode_mask, ngx_http_brix_webdav_loc_conf_t::open_file_cache, ngx_http_brix_webdav_loc_conf_t::open_file_cache_errors, ngx_http_brix_webdav_loc_conf_t::open_file_cache_events, ngx_http_brix_webdav_loc_conf_t::open_file_cache_min_uses, ngx_http_brix_webdav_loc_conf_t::open_file_cache_valid, ngx_http_brix_webdav_loc_conf_t::proxy_certs, ngx_http_brix_webdav_loc_conf_t::proxy_pool_enabled, brix_rate_limit_conf_t::rate, ngx_http_brix_webdav_loc_conf_t::rate_limit, ngx_http_brix_webdav_loc_conf_t::revoke_kv, brix_mirror_conf_t::sample_pct, ngx_http_brix_webdav_loc_conf_t::signing_policy_mode, brix_mirror_conf_t::strip_auth, ngx_http_brix_webdav_loc_conf_t::tape_rest, brix_mirror_conf_t::targets, brix_mirror_conf_t::timeout_ms, ngx_http_brix_webdav_loc_conf_t::token_cache_kv, ngx_http_brix_webdav_loc_conf_t::token_clock_skew, ngx_http_brix_webdav_loc_conf_t::upload_resume, ngx_http_brix_webdav_loc_conf_t::upstream_auth, ngx_http_brix_webdav_loc_conf_t::upstream_backends, ngx_http_brix_webdav_loc_conf_t::upstream_conf, ngx_http_brix_webdav_loc_conf_t::upstream_fail_timeout, ngx_http_brix_webdav_loc_conf_t::upstream_max_fails, ngx_http_brix_webdav_loc_conf_t::upstream_proxy, ngx_http_brix_webdav_loc_conf_t::upstream_resolved, ngx_http_brix_webdav_loc_conf_t::upstream_urls, ngx_http_brix_webdav_loc_conf_t::verify_depth, ngx_http_brix_webdav_loc_conf_t::vo_rules, ngx_http_brix_webdav_loc_conf_t::zip_access, and ngx_http_brix_webdav_loc_conf_t::zip_cd_max_bytes.
ngx_http_brix_webdav_handler()
ngx_int_t ngx_http_brix_webdav_handler (ngx_http_request_t * r)
Definition at line 37 of file dispatch.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, and webdav_dispatch_inner().
Referenced by ngx_http_brix_webdav_postconfiguration().
ngx_http_brix_webdav_merge_loc_conf()
char * ngx_http_brix_webdav_merge_loc_conf (ngx_conf_t * cf, void * parent, void * child)
Definition at line 308 of file config.c.
References ngx_http_brix_webdav_loc_conf_t::acc, brix_export_root_opts_t::allow_write, ngx_http_brix_shared_conf_t::allow_write, ngx_http_brix_webdav_loc_conf_t::auth, ngx_http_brix_webdav_loc_conf_t::authdb_rules, brix_vfs_backend_cred_t::bearer, brix_acc_http_merge_conf(), BRIX_AF_AUTO, brix_assert_dir_outside_export(), BRIX_AUTHZ_CAPABILITY, BRIX_CKS_FMT_TEXT, brix_credential_bearer(), brix_credential_lookup(), BRIX_CRL_MODE_TRY, brix_finalize_authdb_rules(), brix_finalize_vo_rules(), brix_http_common_adopt(), brix_http_mirror_setup(), brix_http_open_rootfd(), brix_integrity_set_xattr_format(), brix_jwks_load(), brix_jwks_register_cleanup(), BRIX_MAX_JWKS_KEYS, BRIX_MERGE_PTR, BRIX_MIRROR_M_DEFAULT, brix_prepare_export_root(), BRIX_SP_MODE_ON, brix_stage_dir_register(), brix_storage_backend_is_remote(), brix_storage_backend_posix_root(), brix_tier_register_stores(), brix_tmp_reap_register(), BRIX_TOKEN_CLOCK_SKEW_SECS, brix_token_registry_build(), brix_vfs_backend_config_str(), brix_vfs_backend_set_credential(), brix_vfs_backend_set_staging(), brix_voms_init(), brix_credential_t::ca_dir, brix_vfs_backend_cred_t::ca_dir, ngx_http_brix_webdav_loc_conf_t::ca_store, ngx_http_brix_webdav_loc_conf_t::cache_root, ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::cadir, ngx_http_brix_webdav_loc_conf_t::cafile, brix_export_root_opts_t::canon_size, ngx_http_brix_webdav_loc_conf_t::checksum_on_write, ngx_http_brix_webdav_loc_conf_t::checksum_xattr_format, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_loc_conf_t::cors_credentials, ngx_http_brix_webdav_loc_conf_t::cors_max_age, ngx_http_brix_webdav_loc_conf_t::crl, ngx_http_brix_webdav_loc_conf_t::crl_mode, ngx_http_brix_webdav_loc_conf_t::dig_auth_file, ngx_http_brix_webdav_loc_conf_t::dig_enable, ngx_http_brix_webdav_loc_conf_t::dig_exports, brix_export_root_opts_t::directive_name, ngx_http_brix_shared_conf_t::enable, brix_mirror_conf_t::enabled, ngx_http_brix_webdav_loc_conf_t::http_query_token, ngx_http_brix_webdav_loc_conf_t::introspect_fail_open, ngx_http_brix_webdav_loc_conf_t::introspect_loc, ngx_http_brix_webdav_loc_conf_t::introspect_ttl, ngx_http_brix_webdav_loc_conf_t::introspect_url, ngx_http_brix_webdav_loc_conf_t::jwks_key_count, ngx_http_brix_webdav_loc_conf_t::jwks_keys, brix_rate_limit_conf_t::kv, ngx_http_brix_webdav_loc_conf_t::lock_startup_sweep, ngx_http_brix_webdav_loc_conf_t::lock_timeout, brix_mirror_conf_t::log_diverge, ngx_http_brix_webdav_loc_conf_t::macaroon_location, ngx_http_brix_webdav_loc_conf_t::macaroon_max_validity, brix_mirror_conf_t::method_mask, ngx_http_brix_webdav_loc_conf_t::mirror, ngx_http_brix_webdav_loc_conf_t::mirror_upstream_conf, brix_mirror_conf_t::mirror_writes, ngx_http_brix_shared_merge(), ngx_http_brix_webdav_tpc_merge_loc_conf(), ngx_test_config, ngx_http_brix_webdav_loc_conf_t::open_file_cache, ngx_http_brix_webdav_loc_conf_t::open_file_cache_errors, ngx_http_brix_webdav_loc_conf_t::open_file_cache_events, ngx_http_brix_webdav_loc_conf_t::open_file_cache_min_uses, ngx_http_brix_webdav_loc_conf_t::open_file_cache_valid, ngx_http_brix_shared_conf_t::pblock_block_size, ngx_http_brix_webdav_loc_conf_t::proxy_certs, ngx_http_brix_webdav_loc_conf_t::proxy_pool_enabled, ngx_http_brix_webdav_loc_conf_t::rate_limit, brix_export_root_opts_t::required, ngx_http_brix_webdav_loc_conf_t::revoke_kv, ngx_http_brix_shared_conf_t::root, ngx_http_brix_shared_conf_t::root_canon, brix_credential_t::s3_access_key, brix_vfs_backend_cred_t::s3_access_key, brix_credential_t::s3_region, brix_vfs_backend_cred_t::s3_region, brix_credential_t::s3_secret_key, brix_vfs_backend_cred_t::s3_secret_key, brix_mirror_conf_t::sample_pct, ngx_http_brix_webdav_loc_conf_t::signing_policy_mode, brix_credential_t::sss_keytab, brix_vfs_backend_cred_t::sss_keytab, ngx_http_brix_shared_conf_t::storage_backend, ngx_http_brix_shared_conf_t::storage_credential, ngx_http_brix_shared_conf_t::storage_staging, brix_mirror_conf_t::strip_auth, ngx_http_brix_webdav_loc_conf_t::tape_rest, brix_mirror_conf_t::targets, ngx_http_brix_webdav_loc_conf_t::tcp_congestion, brix_mirror_conf_t::timeout_ms, brix_mirror_conf_t::token, ngx_http_brix_webdav_loc_conf_t::token_audience, ngx_http_brix_webdav_loc_conf_t::token_cache_kv, ngx_http_brix_webdav_loc_conf_t::token_clock_skew, ngx_http_brix_webdav_loc_conf_t::token_config, ngx_http_brix_webdav_loc_conf_t::token_issuer, ngx_http_brix_webdav_loc_conf_t::token_jwks, ngx_http_brix_webdav_loc_conf_t::token_macaroon_secret, ngx_http_brix_webdav_loc_conf_t::token_macaroon_secret_old, ngx_http_brix_webdav_loc_conf_t::token_registry, ngx_http_brix_webdav_loc_conf_t::tpc, ngx_http_brix_webdav_loc_conf_t::tpc_cadir, ngx_http_brix_webdav_loc_conf_t::tpc_cafile, ngx_http_brix_webdav_loc_conf_t::tpc_cert, ngx_http_brix_webdav_loc_conf_t::tpc_curl, ngx_http_brix_webdav_loc_conf_t::tpc_key, ngx_http_brix_webdav_loc_conf_t::upload_resume, ngx_http_brix_webdav_loc_conf_t::upload_stage_dir, ngx_http_brix_webdav_loc_conf_t::upload_stage_dir_canon, ngx_http_brix_webdav_loc_conf_t::upstream_auth, ngx_http_brix_webdav_loc_conf_t::upstream_auth_token, ngx_http_brix_webdav_loc_conf_t::upstream_backends, ngx_http_brix_webdav_loc_conf_t::upstream_conf, ngx_http_brix_webdav_loc_conf_t::upstream_fail_timeout, ngx_http_brix_webdav_loc_conf_t::upstream_host, ngx_http_brix_webdav_loc_conf_t::upstream_max_fails, ngx_http_brix_webdav_loc_conf_t::upstream_proxy, ngx_http_brix_webdav_loc_conf_t::upstream_resolved, ngx_http_brix_webdav_loc_conf_t::upstream_ssl, ngx_http_brix_webdav_loc_conf_t::upstream_url, ngx_http_brix_webdav_loc_conf_t::upstream_url_base, ngx_http_brix_webdav_loc_conf_t::upstream_urls, ngx_http_brix_webdav_loc_conf_t::verify_depth, ngx_http_brix_webdav_loc_conf_t::vo_rules, ngx_http_brix_webdav_loc_conf_t::voms_cert_dir, ngx_http_brix_webdav_loc_conf_t::vomsdir, WEBDAV_AUTH_OPTIONAL, WEBDAV_AUTH_REQUIRED, webdav_build_ca_store(), webdav_check_pki_consistency(), webdav_lock_startup_sweep(), webdav_log_endpoint_summary(), WEBDAV_PATH_DIRECTORY, WEBDAV_PATH_FILE_OR_DIRECTORY, WEBDAV_PATH_REGULAR_FILE, WEBDAV_PROXY_AUTH_ANONYMOUS, WEBDAV_PROXY_AUTH_TOKEN, webdav_proxy_build_backends(), webdav_proxy_pool_setup(), webdav_summary_is_new(), webdav_validate_cors_origins(), webdav_validate_path, webdav_x509_store_cleanup(), brix_credential_t::x509_proxy, brix_vfs_backend_cred_t::x509_proxy, ngx_http_brix_webdav_loc_conf_t::zip_access, and ngx_http_brix_webdav_loc_conf_t::zip_cd_max_bytes.
ngx_http_brix_webdav_postconfiguration()
ngx_int_t ngx_http_brix_webdav_postconfiguration (ngx_conf_t * cf)
Definition at line 19 of file postconfig.c.
References brix_http_ktls_enable_ctx(), brix_http_mirror_log_handler(), brix_http_mirror_precontent_handler(), brix_http_proto_exclusive_check(), brix_rl_http_access_handler(), brix_rl_http_log_handler(), brix_tpc_registry_configure(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::enable, ngx_http_brix_shared_conf_t::ktls, ngx_http_brix_webdav_access_handler(), ngx_http_brix_webdav_handler(), ngx_http_brix_webdav_module, ngx_http_brix_webdav_loc_conf_t::proxy_certs, s, ngx_http_brix_shared_conf_t::thread_pool, ngx_http_brix_shared_conf_t::thread_pool_name, webdav_auth_init_ssl_indices(), and webdav_introspect_access_handler().
webdav_conf_authdb()
char * webdav_conf_authdb (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 16 of file module_directives.c.
References ngx_http_brix_webdav_loc_conf_t::authdb_rules, and brix_parse_authdb().
webdav_conf_require_vo()
char * webdav_conf_require_vo (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 46 of file module_directives.c.
References brix_copy_conf_string(), brix_normalize_policy_path(), brix_vo_rule_t::path, brix_vo_rule_t::vo, and ngx_http_brix_webdav_loc_conf_t::vo_rules.
webdav_conf_revoke_cache()
char * webdav_conf_revoke_cache (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 250 of file introspect.c.
References brix_kv_find(), and ngx_http_brix_webdav_loc_conf_t::revoke_kv.
webdav_introspect_access_handler()
ngx_int_t webdav_introspect_access_handler (ngx_http_request_t * r)
Definition at line 174 of file introspect.c.
References brix_http_extract_bearer(), brix_kv_get(), BRIX_PCALLOC_OR_RETURN, brix_sha256(), ngx_http_brix_webdav_req_ctx_t::introspect_active, ngx_http_brix_webdav_req_ctx_t::introspect_done, ngx_http_brix_webdav_loc_conf_t::introspect_fail_open, ngx_http_brix_webdav_loc_conf_t::introspect_loc, key, ngx_http_brix_webdav_module, ngx_http_brix_webdav_loc_conf_t::revoke_kv, and webdav_introspect_fire().
Referenced by ngx_http_brix_webdav_postconfiguration().
webdav_send_no_body()
static ngx_int_t webdav_send_no_body (ngx_http_request_t * r, ngx_uint_t status) inline static
Definition at line 511 of file webdav.h.
Referenced by ngx_http_brix_webdav_tpc_handle_copy(), webdav_handle_copy(), webdav_handle_delete(), webdav_handle_mkcol(), webdav_handle_move(), webdav_handle_unlock(), and webdav_tpc_handle_push().
Variable Documentation
brix_webdav_operations
const brix_http_operation_t brix_webdav_operations[] extern
Definition at line 496 of file webdav.h.
Referenced by ngx_http_brix_webdav_access_handler(), webdav_add_cors_headers(), webdav_dispatch_inner(), webdav_handle_options(), webdav_is_write_method(), and webdav_metrics_method().
brix_webdav_operations_count
const ngx_uint_t brix_webdav_operations_count extern
Definition at line 497 of file webdav.h.
Referenced by ngx_http_brix_webdav_access_handler(), webdav_add_cors_headers(), webdav_dispatch_inner(), webdav_handle_options(), webdav_is_write_method(), and webdav_metrics_method().
ngx_http_brix_webdav_module
ngx_module_t ngx_http_brix_webdav_module extern
Definition at line 548 of file module.c.