nginx-xrootd: src/protocols/webdav/get.c File Reference
get.c File Reference
#include "webdav.h"
#include "xrdhttp.h"
#include "core/compat/error_mapping.h"
#include "core/http/etag.h"
#include "core/http/http_conditionals.h"
#include "fs/cache/open.h"
#include "observability/dashboard/dashboard_tracking.h"
#include "fs/vfs/vfs.h"
#include "protocols/shared/file_serve.h"
#include "protocols/shared/http_cache_fill.h"
#include "protocols/shared/http_serve_offload.h"
#include "protocols/root/zip/zip_http.h"
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
Data Structures
struct get_serve_state_t
Functions
static void webdav_serve_metrics (ngx_http_request_t *r, const brix_http_serve_result_t *result)
static ngx_int_t webdav_get_reenter (ngx_http_request_t *r, void *data)
static ngx_int_t webdav_register_send_fd_cleanup (ngx_http_request_t *r, ngx_fd_t fd, const char *path)
static void webdav_get_add_xrdhttp_headers (ngx_http_request_t *r, ngx_fd_t fd, off_t file_size, void *ud)
static ngx_int_t get_zip_member_serve (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const char *path)
static void get_init_vfs_ctx (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *wctx, const char *path, brix_vfs_ctx_t *vctx)
static ngx_int_t get_offload_or_fill (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *wctx, const char *path, brix_vfs_ctx_t *vctx)
static ngx_int_t get_open_map_error (ngx_http_request_t *r, int vfs_err, const char *path)
static ngx_int_t get_resolve_and_stat (ngx_http_request_t *r, brix_vfs_ctx_t *vctx, const char *path, get_serve_state_t *st)
static ngx_int_t get_serve_range (ngx_http_request_t *r, get_serve_state_t *st, const char *path)
static ngx_int_t get_eval_conditionals (ngx_http_request_t *r, get_serve_state_t *st)
static ngx_int_t get_serve_full (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, ngx_http_brix_webdav_req_ctx_t *wctx, get_serve_state_t *st, const char *path)
ngx_int_t webdav_handle_get (ngx_http_request_t *r)
Function Documentation
get_eval_conditionals()
static ngx_int_t get_eval_conditionals (ngx_http_request_t * r, get_serve_state_t * st) static
Definition at line 410 of file get.c.
References brix_http_check_if_modified_since(), brix_vfs_close(), get_serve_state_t::fh, and get_serve_state_t::sb.
Referenced by webdav_handle_get().
get_init_vfs_ctx()
static void get_init_vfs_ctx (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * wctx, const char * path, brix_vfs_ctx_t * vctx) static
Definition at line 166 of file get.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_WEBDAV, brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_bind_backend_mint(), brix_vfs_ctx_init(), brix_webdav_backend_instance(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::identity, brix_vfs_ctx_t::pool, ngx_http_brix_shared_conf_t::root_canon, brix_vfs_ctx_t::sd, ngx_http_brix_shared_conf_t::storage_credential_dir, ngx_http_brix_shared_conf_t::storage_credential_fallback, ngx_http_brix_shared_conf_t::storage_credential_mint_ca_cert, ngx_http_brix_shared_conf_t::storage_credential_mint_ca_key, ngx_http_brix_shared_conf_t::storage_credential_mint_ttl, and webdav_vfs_bind_deleg().
Referenced by webdav_handle_get().
get_offload_or_fill()
static ngx_int_t get_offload_or_fill (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * wctx, const char * path, brix_vfs_ctx_t * vctx) static
Definition at line 208 of file get.c.
References BRIX_ETAG_WEAK, brix_http_cache_fill_if_needed(), brix_http_serve_offload_remote(), brix_vfs_export_relative(), BRIX_XFER_PROTO_WEBDAV, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::compress, brix_http_serve_opts_t::compress, ngx_http_brix_webdav_req_ctx_t::dn, brix_http_serve_opts_t::etag_flags, brix_http_serve_opts_t::identity, brix_http_serve_opts_t::op_name, brix_vfs_ctx_t::sd, webdav_get_reenter(), webdav_serve_metrics(), and brix_http_serve_opts_t::xfer_proto.
Referenced by webdav_handle_get().
get_open_map_error()
static ngx_int_t get_open_map_error (ngx_http_request_t * r, int vfs_err, const char * path) static
Definition at line 263 of file get.c.
References brix_http_errno_to_status(), and xrdhttp_add_response_headers().
Referenced by get_resolve_and_stat().
get_resolve_and_stat()
static ngx_int_t get_resolve_and_stat (ngx_http_request_t * r, brix_vfs_ctx_t * vctx, const char * path, get_serve_state_t * st) static
Definition at line 320 of file get.c.
References brix_vfs_close(), brix_vfs_file_from_cache(), brix_vfs_file_path(), brix_vfs_file_stat(), BRIX_VFS_O_READ, brix_vfs_open(), get_serve_state_t::cache_path, brix_vfs_stat_t::ctime, get_serve_state_t::fh, get_serve_state_t::from_cache, get_open_map_error(), brix_vfs_stat_t::ino, brix_vfs_stat_t::is_directory, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, get_serve_state_t::sb, brix_vfs_stat_t::size, and get_serve_state_t::vst.
Referenced by webdav_handle_get().
get_serve_full()
static ngx_int_t get_serve_full (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, ngx_http_brix_webdav_req_ctx_t * wctx, get_serve_state_t * st, const char * path) static
Definition at line 439 of file get.c.
References BRIX_ETAG_WEAK, brix_http_serve_file_ranged(), BRIX_XFER_PROTO_WEBDAV, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::compress, brix_http_serve_opts_t::compress, ngx_http_brix_webdav_req_ctx_t::dn, brix_http_serve_opts_t::etag_flags, get_serve_state_t::fh, brix_http_serve_opts_t::identity, brix_http_serve_opts_t::op_name, brix_http_serve_opts_t::pre_header_send, brix_http_serve_opts_t::pre_header_ud, get_serve_state_t::sb, get_serve_state_t::vst, webdav_get_add_xrdhttp_headers(), webdav_serve_metrics(), and brix_http_serve_opts_t::xfer_proto.
Referenced by webdav_handle_get().
get_serve_range()
static ngx_int_t get_serve_range (ngx_http_request_t * r, get_serve_state_t * st, const char * path) static
Definition at line 370 of file get.c.
References brix_cache_record_access(), brix_vfs_close(), brix_vfs_file_sendfile_fd(), get_serve_state_t::cache_path, get_serve_state_t::fh, get_serve_state_t::from_cache, get_serve_state_t::sb, webdav_register_send_fd_cleanup(), and xrdhttp_handle_multipart_get().
Referenced by webdav_handle_get().
get_zip_member_serve()
static ngx_int_t get_zip_member_serve (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const char * path) static
Definition at line 132 of file get.c.
References brix_zip_http_member_arg(), brix_zip_http_serve(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::root_canon, WEBDAV_MAX_PATH, ngx_http_brix_webdav_loc_conf_t::zip_access, and ngx_http_brix_webdav_loc_conf_t::zip_cd_max_bytes.
Referenced by webdav_handle_get().
webdav_get_add_xrdhttp_headers()
static void webdav_get_add_xrdhttp_headers (ngx_http_request_t * r, ngx_fd_t fd, off_t file_size, void * ud) static
Definition at line 92 of file get.c.
References stat(), webdav_fadvise_willneed(), xrdhttp_add_checksum_header(), and xrdhttp_add_response_headers().
Referenced by get_serve_full().
webdav_get_reenter()
static ngx_int_t webdav_get_reenter (ngx_http_request_t * r, void * data) static
Definition at line 50 of file get.c.
References webdav_handle_get().
Referenced by get_offload_or_fill().
webdav_handle_get()
ngx_int_t webdav_handle_get (ngx_http_request_t * r)
Definition at line 498 of file get.c.
References ngx_http_brix_webdav_loc_conf_t::common, get_eval_conditionals(), get_init_vfs_ctx(), get_offload_or_fill(), get_resolve_and_stat(), get_serve_full(), get_serve_range(), get_zip_member_serve(), ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), ngx_http_brix_shared_conf_t::root_canon, WEBDAV_MAX_PATH, and xrdhttp_request_is_multirange().
Referenced by webdav_dispatch_core_method(), and webdav_get_reenter().
webdav_register_send_fd_cleanup()
static ngx_int_t webdav_register_send_fd_cleanup (ngx_http_request_t * r, ngx_fd_t fd, const char * path) static
Definition at line 62 of file get.c.
References name, and ngx_pnalloc().
Referenced by get_serve_range().
webdav_serve_metrics()
static void webdav_serve_metrics (ngx_http_request_t * r, const brix_http_serve_result_t * result) static
Definition at line 21 of file get.c.
References BRIX_SERVE_RANGE_PARTIAL, BRIX_SERVE_RANGE_UNSATISFIED, BRIX_WEBDAV_METRIC_ADD, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_RANGE_FULL, BRIX_WEBDAV_RANGE_PARTIAL, BRIX_WEBDAV_RANGE_UNSATISFIED, brix_http_serve_result_t::bytes_sent, and brix_http_serve_result_t::range_result.
Referenced by get_offload_or_fill(), and get_serve_full().