nginx-xrootd: src/protocols/webdav/webdav_path.h File Reference
webdav_path.h File Reference
#include "webdav.h"
Functions
ngx_int_t ngx_http_brix_webdav_resolve_path (ngx_http_request_t *r, const char *root_canon, char *out, size_t outsz)
ngx_int_t webdav_resolve_destination_path (ngx_log_t *log, const char *op_label, const char *root_canon, const char *decoded_path, char *out, size_t outsz, ngx_flag_t allow_internal)
ngx_int_t webdav_resolve_stat (ngx_http_request_t *r, char *path, size_t pathsz, struct stat *sb)
WHAT: Resolve the request URI to a canonicalised filesystem path then perform stat(2) on the result — combines ngx_http_brix_webdav_resolve_path() and stat(2) into a single helper for handlers needing both path and metadata.
ngx_int_t webdav_urldecode (const u_char *src, size_t src_len, char *dst, size_t dst_sz)
ngx_int_t webdav_destination_extract_path (const u_char *dest_data, size_t dest_len, const u_char **path_out, size_t *path_len_out)
char * webdav_escape_xml_text (ngx_pool_t *pool, const char *src)
WHAT: Escape a string for safe inclusion in XML text response bodies.
ngx_int_t webdav_add_cors_headers (ngx_http_request_t *r)
Function Documentation
ngx_http_brix_webdav_resolve_path()
ngx_int_t ngx_http_brix_webdav_resolve_path (ngx_http_request_t * r, const char * root_canon, char * out, size_t outsz)
Definition at line 59 of file path.c.
References brix_http_resolve_path_ex(), ngx_http_brix_shared_conf_t::cache_store_endpoint, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_module, WEBDAV_MAX_PATH, and webdav_urldecode().
Referenced by access_apply_authdb(), rl_resolve_volume_path(), webdav_copy_resolve_pair(), webdav_handle_get(), webdav_handle_lock_inner(), webdav_handle_mkcol(), webdav_handle_move(), webdav_handle_unlock(), webdav_lock_check_request_path(), webdav_put_precheck(), webdav_resolve_stat(), and webdav_tpc_prepare_pull_target().
webdav_add_cors_headers()
ngx_int_t webdav_add_cors_headers (ngx_http_request_t * r)
Definition at line 271 of file cors.c.
References brix_cors_conf_t::allow_methods, brix_http_add_cors_headers(), brix_http_find_header(), brix_http_operation_allow_header(), BRIX_WEBDAV_ALLOW_FLAGS, BRIX_WEBDAV_CORS_ALLOWED, BRIX_WEBDAV_CORS_DENIED, BRIX_WEBDAV_CORS_NO_ORIGIN, BRIX_WEBDAV_METRIC_INC, brix_webdav_operations, brix_webdav_operations_count, ngx_http_brix_webdav_loc_conf_t::cors_credentials, ngx_http_brix_webdav_loc_conf_t::cors_max_age, ngx_http_brix_webdav_loc_conf_t::cors_origins, brix_cors_conf_t::credentials, brix_cors_conf_t::max_age, ngx_http_brix_webdav_module, and brix_cors_conf_t::origins.
Referenced by ngx_http_brix_webdav_access_handler().
webdav_destination_extract_path()
ngx_int_t webdav_destination_extract_path (const u_char * dest_data, size_t dest_len, const u_char ** path_out, size_t * path_len_out)
Definition at line 57 of file uri.c.
Referenced by webdav_copy_parse_request(), and webdav_move_resolve_dest().
webdav_escape_xml_text()
char * webdav_escape_xml_text (ngx_pool_t * pool, const char * src)
WHAT: Escape a string for safe inclusion in XML text response bodies.
Converts dangerous characters to their XML entity equivalents: & to &, < to <, > to >, " to ", and ' to &#39;. Control characters (< 0x20 or 0x7f) are percent-encoded as XX instead of using XML entities because control chars don't have standard entity names and would confuse XML parsers. The result is allocated from the nginx request pool after asking the shared compat XML adapter for the exact escaped length. Returns NULL on OOM or if pool/src are NULL. All callers use this for PROPFIND, LOCK, and HEAD response XML generation where filesystem paths or metadata may contain special chars.
Definition at line 56 of file xml.c.
References BRIX_PNALLOC_OR_RETURN, brix_xml_escape(), BRIX_XML_ESCAPE_CONTROL_PERCENT, and brix_xml_escaped_len().
Referenced by propfind_capture_unknown(), propfind_emit_displayname(), propfind_emit_owner(), propfind_entry(), webdav_dead_prop_append_empty(), webdav_lock_append_discovery(), webdav_lock_xml_response(), webdav_proppatch_serialize_dead_prop(), webdav_proppatch_start_multistatus(), and webdav_search_append_response().
webdav_resolve_destination_path()
ngx_int_t webdav_resolve_destination_path (ngx_log_t * log, const char * op_label, const char * root_canon, const char * decoded_path, char * out, size_t outsz, ngx_flag_t allow_internal)
Definition at line 28 of file path.c.
References brix_http_resolve_path_ex(), log, map_resolve_rc(), and PATH_MAX.
Referenced by tape_authz_path(), webdav_copy_resolve_pair(), and webdav_move_resolve_dest().
webdav_resolve_stat()
ngx_int_t webdav_resolve_stat (ngx_http_request_t * r, char * path, size_t pathsz, struct stat * sb)
WHAT: Resolve the request URI to a canonicalised filesystem path then perform stat(2) on the result — combines ngx_http_brix_webdav_resolve_path() and stat(2) into a single helper for handlers needing both path and metadata.
Calls the primary path resolver (ngx_http_brix_webdav_resolve_path()) to convert r->uri into an absolute canonicalised path within root_canon, then immediately calls stat(2) on that path to populate sb with file metadata. Returns NGX_OK if both steps succeed; NGX_HTTP_NOT_FOUND (404) if the resolved path doesn't exist (ENOENT); any other stat error returns NGX_HTTP_INTERNAL_SERVER_ERROR (500). The caller-supplied path buffer must be at least WEBDAV_MAX_PATH bytes to accommodate the decoded and canonicalised output. Used by GET, HEAD, PROPFIND handlers that need both the resolved path and file metadata in a single atomic operation.
WHY: Many WebDAV methods (GET, HEAD, PROPFIND) require both the resolved path AND file metadata — calling resolve_path separately then stat would duplicate error handling logic across multiple handler files. This helper provides an atomic two-step operation with consistent error mapping. Per AGENTS.md INVARIANT #4: all wire paths must go through resolve_path() before any filesystem operations — this function enforces that invariant by embedding the resolution step into stat itself. Security invariant: resolved path is confined to root_canon, preventing ../ traversal attacks even if client supplies malicious URI components.
HOW: Retrieves WebDAV location configuration via ngx_http_get_module_loc_conf(). Calls ngx_http_brix_webdav_resolve_path() first — if resolution fails (invalid URI, outside root_canon), returns immediately with that error code. On successful resolution calls stat(2) on the resolved path — maps ENOENT to 404, all other errors to 500. Returns NGX_OK only when both resolution and stat succeed. Caller must ensure path buffer has sufficient capacity (WEBDAV_MAX_PATH). sb pointer may be NULL if caller needs path only without metadata.
Definition at line 41 of file resource.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_vfs_ctx_t::allow_write, BRIX_PROTO_WEBDAV, brix_vfs_backend_resolve(), brix_vfs_ctx_bind_backend_cred(), ngx_http_brix_webdav_loc_conf_t::common, brix_vfs_stat_t::ctime, brix_vfs_ctx_t::identity, ngx_http_brix_webdav_req_ctx_t::identity, brix_vfs_stat_t::ino, brix_path_result_t::is_confined, brix_vfs_ctx_t::is_tls, brix_vfs_ctx_t::log, brix_vfs_ctx_t::metrics_proto, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), brix_vfs_ctx_t::pool, brix_path_result_t::resolved, brix_vfs_ctx_t::resolved, ngx_http_brix_shared_conf_t::root_canon, brix_vfs_ctx_t::root_canon, brix_vfs_ctx_t::rootfd, brix_vfs_ctx_t::sd, brix_vfs_stat_t::size, ngx_http_brix_shared_conf_t::storage_credential_dir, ngx_http_brix_shared_conf_t::storage_credential_fallback, and webdav_vfs_bind_deleg().
Referenced by propfind_do(), webdav_handle_delete(), webdav_handle_head(), webdav_proppatch_do(), webdav_search_do(), and webdav_tpc_handle_push().
webdav_urldecode()
ngx_int_t webdav_urldecode (const u_char * src, size_t src_len, char * dst, size_t dst_sz)
Definition at line 44 of file uri.c.
References brix_http_urldecode(), BRIX_URLDECODE_NUL_BYTE, BRIX_URLDECODE_OK, BRIX_URLDECODE_OVERFLOW, and BRIX_URLDECODE_REJECT_NUL.
Referenced by ngx_http_brix_webdav_resolve_path(), webdav_copy_parse_request(), and webdav_move_resolve_dest().