nginx-xrootd: src/protocols/webdav/webdav_lock.h File Reference
webdav_lock.h File Reference
#include "webdav.h"
Functions
ngx_int_t webdav_lock_xattr_encode (const webdav_lock_xattr_t *e, char *out, size_t outsz)
ngx_int_t webdav_lock_xattr_decode (const char *raw, size_t rawlen, webdav_lock_xattr_t *e)
ngx_int_t webdav_lock_xattr_write (ngx_http_request_t *r, const char *path, const webdav_lock_xattr_t *e, int flags)
ngx_int_t webdav_lock_xattr_read (ngx_http_request_t *r, const char *path, webdav_lock_xattr_t *e)
ngx_int_t webdav_lock_xattr_delete (ngx_http_request_t *r, const char *path)
ngx_uint_t webdav_lock_startup_sweep (ngx_pool_t *pool, ngx_log_t *log, const char *root_canon)
ngx_int_t webdav_check_locks (ngx_http_request_t *r, const char *path, int need_write)
ngx_int_t webdav_check_locks_tree (ngx_http_request_t *r, const char *path)
ngx_int_t webdav_lock_append_discovery (ngx_http_request_t *r, const char *path, ngx_chain_t **head, ngx_chain_t **tail)
ngx_int_t webdav_lock_append_supported (ngx_http_request_t *r, ngx_chain_t **head, ngx_chain_t **tail)
Function Documentation
webdav_check_locks()
ngx_int_t webdav_check_locks (ngx_http_request_t * r, const char * path, int need_write)
Definition at line 269 of file lock.c.
References check(), ngx_http_brix_webdav_loc_conf_t::common, webdav_lock_xattr_t::depth_infinity, webdav_lock_xattr_t::expires, ngx_http_brix_webdav_module, NGX_HTTP_LOCKED, PATH_MAX, ngx_http_brix_shared_conf_t::root_canon, webdav_lock_xattr_t::token, webdav_lock_if_header_matches(), webdav_lock_reap_null(), webdav_lock_xattr_delete(), and webdav_lock_xattr_read().
Referenced by webdav_check_locks_tree(), webdav_dispatch_inner(), webdav_handle_mkcol(), and webdav_proppatch_do().
webdav_check_locks_tree()
ngx_int_t webdav_check_locks_tree (ngx_http_request_t * r, const char * path)
Definition at line 431 of file lock.c.
References brix_vfs_probe(), check_locks_descendants(), brix_vfs_stat_t::is_directory, webdav_check_locks(), and webdav_lock_vfs_ctx().
Referenced by webdav_handle_copy(), webdav_handle_delete(), and webdav_handle_move().
webdav_lock_append_discovery()
ngx_int_t webdav_lock_append_discovery (ngx_http_request_t * r, const char * path, ngx_chain_t ** head, ngx_chain_t ** tail)
Definition at line 700 of file lock.c.
References brix_http_chain_appendf(), webdav_lock_xattr_t::depth_infinity, webdav_lock_xattr_t::exclusive, webdav_lock_xattr_t::expires, webdav_lock_xattr_t::owner, webdav_lock_xattr_t::token, webdav_escape_xml_text(), webdav_lock_reap_null(), webdav_lock_xattr_delete(), and webdav_lock_xattr_read().
Referenced by propfind_entry().
webdav_lock_append_supported()
ngx_int_t webdav_lock_append_supported (ngx_http_request_t * r, ngx_chain_t ** head, ngx_chain_t ** tail)
Definition at line 674 of file lock.c.
References brix_http_chain_appendf().
Referenced by propfind_entry().
webdav_lock_startup_sweep()
ngx_uint_t webdav_lock_startup_sweep (ngx_pool_t * pool, ngx_log_t * log, const char * root_canon)
Definition at line 101 of file lock.c.
References brix_fs_walk(), brix_fs_walk_options_t::include_dirs, brix_fs_walk_options_t::include_files, log, webdav_lock_sweep_ctx_t::log, webdav_lock_sweep_ctx_t::pool, webdav_lock_sweep_ctx_t::removed, webdav_lock_sweep_ctx_t::root_canon, webdav_lock_sweep_cb(), and webdav_lock_sweep_remove().
Referenced by ngx_http_brix_webdav_merge_loc_conf().
webdav_lock_xattr_decode()
ngx_int_t webdav_lock_xattr_decode (const char * raw, size_t rawlen, webdav_lock_xattr_t * e)
Definition at line 82 of file prop_xattr.c.
References webdav_lock_xattr_t::depth_infinity, webdav_lock_xattr_t::exclusive, webdav_lock_xattr_t::expires, webdav_lock_xattr_t::is_null, webdav_lock_xattr_t::owner, webdav_lock_xattr_t::token, and WEBDAV_LOCK_XATTR_MAXLEN.
Referenced by webdav_lock_xattr_read().
webdav_lock_xattr_delete()
ngx_int_t webdav_lock_xattr_delete (ngx_http_request_t * r, const char * path)
Definition at line 211 of file prop_xattr.c.
References brix_vfs_removexattr(), ENOATTR, log, webdav_lock_vfs_ctx_init(), and WEBDAV_LOCK_XATTR_KEY.
Referenced by check_locks_descendants(), webdav_check_locks(), webdav_handle_lock_inner(), webdav_handle_unlock(), and webdav_lock_append_discovery().
webdav_lock_xattr_encode()
ngx_int_t webdav_lock_xattr_encode (const webdav_lock_xattr_t * e, char * out, size_t outsz)
Definition at line 61 of file prop_xattr.c.
References webdav_lock_xattr_t::depth_infinity, webdav_lock_xattr_t::exclusive, webdav_lock_xattr_t::expires, webdav_lock_xattr_t::is_null, webdav_lock_xattr_t::owner, and webdav_lock_xattr_t::token.
Referenced by webdav_lock_xattr_write().
webdav_lock_xattr_read()
ngx_int_t webdav_lock_xattr_read (ngx_http_request_t * r, const char * path, webdav_lock_xattr_t * e)
Definition at line 182 of file prop_xattr.c.
References brix_vfs_getxattr(), ENOATTR, log, webdav_lock_vfs_ctx_init(), webdav_lock_xattr_decode(), WEBDAV_LOCK_XATTR_KEY, and WEBDAV_LOCK_XATTR_MAXLEN.
Referenced by check_locks_descendants(), webdav_check_locks(), webdav_handle_lock_inner(), webdav_handle_unlock(), and webdav_lock_append_discovery().
webdav_lock_xattr_write()
ngx_int_t webdav_lock_xattr_write (ngx_http_request_t * r, const char * path, const webdav_lock_xattr_t * e, int flags)
Definition at line 152 of file prop_xattr.c.
References brix_vfs_setxattr(), log, webdav_lock_vfs_ctx_init(), webdav_lock_xattr_encode(), WEBDAV_LOCK_XATTR_KEY, and WEBDAV_LOCK_XATTR_MAXLEN.
Referenced by webdav_handle_lock_inner().