nginx-xrootd: src/protocols/webdav/put.c File Reference
put.c File Reference
#include "webdav.h"
#include "core/http/etag.h"
#include "core/http/http_body.h"
#include "core/compat/integrity_info.h"
#include "core/http/http_conditionals.h"
#include "core/compat/range.h"
#include "core/compat/staged_file.h"
#include "observability/dashboard/dashboard_tracking.h"
#include "fs/vfs/vfs.h"
#include "auth/impersonate/lifecycle.h"
#include "fs/path/path.h"
#include "core/compat/cstr.h"
#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
struct webdav_put_aio_t
Functions
static void webdav_put_vfs_ctx_init (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const char *path, brix_vfs_ctx_t *vctx)
static void webdav_put_aio_thread (void *data, ngx_log_t *log)
static void webdav_put_aio_done (ngx_event_t *ev)
static void webdav_put_persist_checksums (ngx_http_request_t *r, const char *path)
static void webdav_put_body_inner (ngx_http_request_t *r)
void webdav_handle_put_body (ngx_http_request_t *r)
static void webdav_set_upload_offset (ngx_http_request_t *r, off_t off)
static void webdav_put_ranged_resume (ngx_http_request_t *r, ngx_http_brix_webdav_loc_conf_t *conf, const char *path, const brix_http_content_range_t *cr)
Function Documentation
webdav_handle_put_body()
void webdav_handle_put_body (ngx_http_request_t * r)
Definition at line 233 of file put.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, and webdav_put_body_inner().
Referenced by webdav_dispatch_inner().
webdav_put_aio_done()
static void webdav_put_aio_done (ngx_event_t * ev) static
Definition at line 149 of file put.c.
References brix_dashboard_http_add(), brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_log_safe_path(), brix_vfs_staged_abort(), brix_vfs_staged_commit(), webdav_put_aio_t::created, webdav_put_aio_t::io_errno, webdav_put_aio_t::len, webdav_put_aio_t::nwritten, webdav_put_aio_t::path, webdav_put_aio_t::r, webdav_put_aio_t::staged, webdav_metrics_finalize_request(), webdav_put_persist_checksums(), and webdav_send_status_only().
Referenced by webdav_put_body_inner().
webdav_put_aio_thread()
static void webdav_put_aio_thread (void * data, ngx_log_t * log) static
Definition at line 116 of file put.c.
References brix_http_body_write_to_fd(), brix_http_body_write_to_staged(), brix_vfs_staged_fd(), brix_vfs_staged_is_driver(), webdav_put_aio_t::io_errno, webdav_put_aio_t::len, log, webdav_put_aio_t::nwritten, webdav_put_aio_t::path, webdav_put_aio_t::r, and webdav_put_aio_t::staged.
Referenced by webdav_put_body_inner().
webdav_put_body_inner()
static void webdav_put_body_inner (ngx_http_request_t * r) static
Definition at line 364 of file put.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_codec_desc_t::available, brix_codec_by_http_token(), BRIX_CODEC_IDENTITY, brix_dashboard_http_add(), brix_dashboard_http_error(), brix_dashboard_http_finish(), brix_dashboard_http_start_identity(), BRIX_DECODE_MAX_OUTPUT, BRIX_ETAG_WEAK, brix_http_body_decode_to_fd(), brix_http_body_summary(), brix_http_body_write_to_fd(), brix_http_body_write_to_staged(), brix_http_check_etag_preconditions(), BRIX_HTTP_COND_WEAK_EQUIV, brix_http_find_header(), brix_http_map_errno(), brix_http_parse_content_range(), brix_log_safe_path(), BRIX_PROTO_WEBDAV, brix_vfs_ctx_init(), brix_vfs_probe(), brix_vfs_staged_abort(), brix_vfs_staged_commit(), brix_vfs_staged_fd(), brix_vfs_staged_is_driver(), brix_vfs_staged_open(), BRIX_WEBDAV_METRIC_ADD, BRIX_WEBDAV_METRIC_INC, BRIX_WEBDAV_PUT_EMPTY, BRIX_WEBDAV_PUT_MEMORY, BRIX_WEBDAV_PUT_SPOOLED, BRIX_WEBDAV_PUT_THREADED, BRIX_XFER_DIR_WRITE, BRIX_XFER_PROTO_WEBDAV, brix_http_body_summary_t::bytes, ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, webdav_put_aio_t::created, ngx_http_brix_webdav_req_ctx_t::dn, brix_http_body_summary_t::has_memory, brix_http_body_summary_t::has_spooled, brix_codec_desc_t::id, ngx_http_brix_webdav_req_ctx_t::identity, webdav_put_aio_t::len, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), webdav_put_aio_t::path, brix_vfs_ctx_t::pool, brix_http_content_range_t::present, webdav_put_aio_t::r, ngx_http_brix_shared_conf_t::root_canon, brix_vfs_stat_t::size, webdav_put_aio_t::staged, stat(), ngx_http_brix_shared_conf_t::thread_pool, ngx_http_brix_webdav_loc_conf_t::upload_resume, WEBDAV_MAX_PATH, webdav_metrics_finalize_request(), webdav_put_aio_done(), webdav_put_aio_thread(), webdav_put_persist_checksums(), webdav_put_ranged_resume(), and webdav_put_vfs_ctx_init().
Referenced by webdav_handle_put_body().
webdav_put_persist_checksums()
static void webdav_put_persist_checksums (ngx_http_request_t * r, const char * path) static
Definition at line 79 of file put.c.
References brix_integrity_opts_t::allow_xattr_cache, brix_integrity_get_fd(), brix_str_cbuf(), brix_vfs_open_fd(), ngx_http_brix_webdav_loc_conf_t::checksum_on_write, close(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_module, brix_integrity_opts_t::require_regular_file, ngx_http_brix_shared_conf_t::root_canon, and brix_integrity_opts_t::update_xattr_cache.
Referenced by webdav_put_aio_done(), webdav_put_body_inner(), and webdav_put_ranged_resume().
webdav_put_ranged_resume()
static void webdav_put_ranged_resume (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const char * path, const brix_http_content_range_t * cr) static
Definition at line 271 of file put.c.
References brix_staged_file_t::active, brix_commit_staged(), brix_http_body_write_to_fd_at(), brix_http_map_errno(), brix_stage_mark_pending(), brix_stage_unmark_pending(), brix_staged_abort(), brix_staged_open_resume(), BRIX_WEBDAV_METRIC_ADD, brix_http_body_summary_t::bytes, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::dn, brix_http_content_range_t::end, brix_staged_file_t::fd, brix_staged_file_t::final_mode, ngx_http_brix_webdav_module, ngx_http_brix_shared_conf_t::root_canon, brix_http_content_range_t::start, brix_staged_file_t::tmp_path, brix_http_content_range_t::total, ngx_http_brix_webdav_loc_conf_t::upload_stage_dir_canon, webdav_metrics_finalize_request(), webdav_put_persist_checksums(), webdav_send_status_only(), and webdav_set_upload_offset().
Referenced by webdav_put_body_inner().
webdav_put_vfs_ctx_init()
static void webdav_put_vfs_ctx_init (ngx_http_request_t * r, ngx_http_brix_webdav_loc_conf_t * conf, const char * path, brix_vfs_ctx_t * vctx) static
Definition at line 45 of file put.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_PROTO_WEBDAV, brix_vfs_ctx_init(), brix_webdav_backend_instance(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, brix_vfs_ctx_t::pool, ngx_http_brix_shared_conf_t::root_canon, and brix_vfs_ctx_t::sd.
Referenced by webdav_put_body_inner().
webdav_set_upload_offset()
static void webdav_set_upload_offset (ngx_http_request_t * r, off_t off) static
Definition at line 246 of file put.c.
Referenced by webdav_put_ranged_resume().