nginx-xrootd: src/protocols/webdav/webdav_methods.h File Reference
webdav_methods.h File Reference
#include "webdav.h"
Functions
ngx_int_t webdav_handle_options (ngx_http_request_t *r)
ngx_int_t webdav_handle_head (ngx_http_request_t *r, int send_body)
ngx_int_t webdav_handle_get (ngx_http_request_t *r)
void webdav_handle_put_body (ngx_http_request_t *r)
ngx_int_t webdav_handle_delete (ngx_http_request_t *r)
ngx_int_t webdav_delete_path_recursive (ngx_log_t *log, const char *root_canon, const char *path)
ngx_int_t webdav_handle_mkcol (ngx_http_request_t *r)
ngx_int_t webdav_handle_propfind (ngx_http_request_t *r)
ngx_int_t webdav_handle_proppatch (ngx_http_request_t *r)
ngx_int_t webdav_handle_search (ngx_http_request_t *r)
ngx_int_t webdav_handle_acl (ngx_http_request_t *r)
ngx_int_t webdav_handle_move (ngx_http_request_t *r)
ngx_int_t webdav_handle_copy (ngx_http_request_t *r)
void webdav_handle_lock (ngx_http_request_t *r)
ngx_int_t webdav_handle_unlock (ngx_http_request_t *r)
ngx_int_t webdav_handle_macaroon_discovery (ngx_http_request_t *r)
void webdav_handle_macaroon_token (ngx_http_request_t *r)
void webdav_handle_macaroon_request (ngx_http_request_t *r)
ngx_int_t brix_dig_handle (ngx_http_request_t *r)
Function Documentation
brix_dig_handle()
ngx_int_t brix_dig_handle (ngx_http_request_t * r)
Definition at line 125 of file dig.c.
References BRIX_DIG_PREFIX, BRIX_DIG_PREFIX_LEN, BRIX_PROTO_WEBDAV, brix_str_cbuf(), brix_vfs_close(), brix_vfs_ctx_init(), brix_vfs_file_sendfile_fd(), brix_vfs_file_stat(), BRIX_VFS_O_READ, brix_vfs_open(), brix_dig_export_t::canon, close(), ngx_http_brix_webdav_loc_conf_t::dig_auth_file, dig_authorize(), ngx_http_brix_webdav_loc_conf_t::dig_enable, ngx_http_brix_webdav_loc_conf_t::dig_exports, dig_open_status(), dig_principal(), brix_vfs_stat_t::is_regular, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, name, ngx_http_brix_webdav_module, PATH_MAX, brix_vfs_stat_t::size, and stat().
Referenced by webdav_dispatch_inner().
webdav_delete_path_recursive()
ngx_int_t webdav_delete_path_recursive (ngx_log_t * log, const char * root_canon, const char * path)
Definition at line 48 of file namespace.c.
References brix_fs_remove_tree_confined(), and log.
Referenced by webdav_copy_collection_execute(), and webdav_handle_copy().
webdav_handle_acl()
ngx_int_t webdav_handle_acl (ngx_http_request_t * r)
Definition at line 13 of file acl.c.
References brix_http_chain_appendf().
Referenced by webdav_dispatch_inner().
webdav_handle_copy()
ngx_int_t webdav_handle_copy (ngx_http_request_t * r)
Definition at line 302 of file copy.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_http_overwrite_forbidden(), BRIX_PROTO_WEBDAV, brix_vfs_copy(), brix_vfs_ctx_init(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), brix_vfs_copy_opts_t::overwrite, brix_vfs_ctx_t::pool, brix_vfs_copy_opts_t::preserve_xattrs, ngx_http_brix_shared_conf_t::root_canon, brix_vfs_copy_opts_t::staged_commit, stat(), webdav_check_copy_conditionals(), webdav_check_locks_tree(), webdav_copy_collection_execute(), webdav_copy_collection_post_task(), webdav_copy_errno_to_status(), webdav_copy_probe(), webdav_dead_props_copy(), webdav_delete_path_recursive(), webdav_destination_extract_path(), WEBDAV_MAX_PATH, webdav_resolve_destination_path(), webdav_send_no_body(), webdav_tpc_find_header, and webdav_urldecode().
Referenced by webdav_dispatch_inner().
webdav_handle_delete()
ngx_int_t webdav_handle_delete (ngx_http_request_t * r)
Definition at line 64 of file namespace.c.
References brix_vfs_rmdir(), brix_vfs_unlink(), stat(), webdav_check_locks_tree(), WEBDAV_MAX_PATH, webdav_ns_vfs_ctx_init(), webdav_resolve_stat(), and webdav_send_no_body().
Referenced by webdav_dispatch_inner().
webdav_handle_get()
ngx_int_t webdav_handle_get (ngx_http_request_t * r)
Definition at line 128 of file get.c.
References ngx_http_brix_shared_conf_t::allow_write, brix_cache_record_access(), BRIX_ETAG_WEAK, brix_http_cache_fill_if_needed(), brix_http_check_if_modified_since(), brix_http_errno_to_status(), brix_http_serve_file_ranged(), brix_http_serve_offload_remote(), BRIX_PROTO_WEBDAV, brix_vfs_close(), brix_vfs_ctx_init(), brix_vfs_export_relative(), brix_vfs_file_from_cache(), brix_vfs_file_path(), brix_vfs_file_sendfile_fd(), brix_vfs_file_stat(), BRIX_VFS_O_READ, brix_vfs_open(), brix_webdav_backend_instance(), BRIX_XFER_PROTO_WEBDAV, brix_zip_http_member_arg(), brix_zip_http_serve(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_shared_conf_t::compress, brix_http_serve_opts_t::compress, brix_vfs_stat_t::ctime, ngx_http_brix_webdav_req_ctx_t::dn, brix_http_serve_opts_t::etag_flags, brix_http_serve_opts_t::identity, ngx_http_brix_webdav_req_ctx_t::identity, brix_vfs_stat_t::ino, brix_vfs_stat_t::is_directory, brix_vfs_stat_t::mode, brix_vfs_stat_t::mtime, ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), brix_http_serve_opts_t::op_name, brix_vfs_ctx_t::pool, brix_http_serve_opts_t::pre_header_send, brix_http_serve_opts_t::pre_header_ud, ngx_http_brix_shared_conf_t::root_canon, brix_vfs_ctx_t::sd, brix_vfs_stat_t::size, stat(), webdav_get_add_xrdhttp_headers(), webdav_get_reenter(), WEBDAV_MAX_PATH, webdav_register_send_fd_cleanup(), webdav_serve_metrics(), brix_http_serve_opts_t::xfer_proto, xrdhttp_add_response_headers(), xrdhttp_handle_multipart_get(), xrdhttp_request_is_multirange(), ngx_http_brix_webdav_loc_conf_t::zip_access, and ngx_http_brix_webdav_loc_conf_t::zip_cd_max_bytes.
Referenced by webdav_dispatch_inner(), and webdav_get_reenter().
webdav_handle_head()
ngx_int_t webdav_handle_head (ngx_http_request_t * r, int send_body)
Definition at line 99 of file methods_basic.c.
References ngx_http_brix_shared_conf_t::allow_write, BRIX_ETAG_WEAK, brix_http_add_etag_header(), BRIX_PROTO_WEBDAV, brix_vfs_close(), brix_vfs_ctx_init(), brix_vfs_file_fd(), BRIX_VFS_O_READ, brix_vfs_open(), ngx_http_brix_webdav_loc_conf_t::cache_root_canon, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, brix_vfs_ctx_t::pool, ngx_http_brix_shared_conf_t::root_canon, stat(), xrdhttp_req_ctx_t::want_cksum, WEBDAV_MAX_PATH, webdav_resolve_stat(), xrdhttp_add_checksum_header(), and xrdhttp_get_ctx().
Referenced by webdav_dispatch_inner().
webdav_handle_lock()
void webdav_handle_lock (ngx_http_request_t * r)
Definition at line 464 of file lock.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, and webdav_handle_lock_inner().
Referenced by webdav_dispatch_inner().
webdav_handle_macaroon_discovery()
ngx_int_t webdav_handle_macaroon_discovery (ngx_http_request_t * r)
Definition at line 237 of file macaroon_endpoint.c.
References scheme, and send_json().
Referenced by webdav_dispatch_inner().
webdav_handle_macaroon_request()
void webdav_handle_macaroon_request (ngx_http_request_t * r)
Definition at line 610 of file macaroon_endpoint.c.
References brix_http_body_read_all(), brix_identity_check_token_scope(), brix_json_get_str(), brix_macaroon_issue(), BRIX_MACAROON_ISSUE_OUT_MAX, brix_macaroon_secret_parse(), brix_token_check_read(), brix_token_check_write(), ngx_http_brix_webdav_req_ctx_t::identity, J_INVALID_REQUEST, J_NOT_CONFIGURED, J_SERVER_ERROR, J_UNAUTHORIZED, mac_caveats_scan(), mac_iso8601_secs(), ngx_http_brix_webdav_loc_conf_t::macaroon_location, ngx_http_brix_webdav_loc_conf_t::macaroon_max_validity, ngx_http_brix_webdav_module, scheme, send_json(), ngx_http_brix_webdav_req_ctx_t::token_auth, ngx_http_brix_webdav_loc_conf_t::token_issuer, ngx_http_brix_webdav_loc_conf_t::token_macaroon_secret, ngx_http_brix_webdav_req_ctx_t::token_scope_count, ngx_http_brix_webdav_req_ctx_t::token_scopes, ngx_http_brix_webdav_req_ctx_t::verified, and webdav_metrics_finalize_request().
Referenced by webdav_dispatch_inner().
webdav_handle_macaroon_token()
void webdav_handle_macaroon_token (ngx_http_request_t * r)
Definition at line 271 of file macaroon_endpoint.c.
References BRIX_DIAG_ERR, brix_http_body_read_all(), brix_identity_check_token_scope(), brix_macaroon_issue(), BRIX_MACAROON_ISSUE_OUT_MAX, brix_macaroon_secret_parse(), brix_token_check_read(), brix_token_check_write(), form_find(), ngx_http_brix_webdav_req_ctx_t::identity, J_INVALID_REQUEST, J_INVALID_SCOPE, J_NOT_CONFIGURED, J_SERVER_ERROR, J_UNAUTHORIZED, J_UNSUPPORTED_GT, ngx_http_brix_webdav_module, scheme, scope_to_activities(), send_json(), ngx_http_brix_webdav_req_ctx_t::token_auth, ngx_http_brix_webdav_loc_conf_t::token_issuer, ngx_http_brix_webdav_loc_conf_t::token_macaroon_secret, ngx_http_brix_webdav_req_ctx_t::token_scope_count, ngx_http_brix_webdav_req_ctx_t::token_scopes, ngx_http_brix_webdav_req_ctx_t::verified, and webdav_metrics_finalize_request().
Referenced by webdav_dispatch_inner().
webdav_handle_mkcol()
ngx_int_t webdav_handle_mkcol (ngx_http_request_t * r)
Definition at line 113 of file namespace.c.
References brix_vfs_mkdir(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), ngx_http_brix_shared_conf_t::root_canon, webdav_check_locks(), WEBDAV_MAX_PATH, webdav_ns_vfs_ctx_init(), and webdav_send_no_body().
Referenced by webdav_dispatch_inner().
webdav_handle_move()
ngx_int_t webdav_handle_move (ngx_http_request_t * r)
Definition at line 241 of file move.c.
References brix_http_overwrite_forbidden(), brix_log_safe_path(), brix_webdav_backend_instance(), ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), ngx_http_brix_shared_conf_t::root_canon, stat(), webdav_check_locks_tree(), webdav_destination_extract_path(), WEBDAV_MAX_PATH, webdav_move_collection_post_task(), webdav_move_execute(), webdav_move_probe(), webdav_resolve_destination_path(), webdav_send_no_body(), webdav_tpc_find_header, and webdav_urldecode().
Referenced by webdav_dispatch_inner().
webdav_handle_options()
ngx_int_t webdav_handle_options (ngx_http_request_t * r)
Definition at line 39 of file methods_basic.c.
References brix_http_operation_allow_header(), BRIX_WEBDAV_ALLOW_FLAGS, brix_webdav_operations, brix_webdav_operations_count, and ngx_http_brix_webdav_module.
Referenced by webdav_dispatch_inner().
webdav_handle_propfind()
ngx_int_t webdav_handle_propfind (ngx_http_request_t * r)
Definition at line 271 of file propfind.c.
References brix_http_read_body(), and propfind_body_handler().
Referenced by webdav_dispatch_inner().
webdav_handle_proppatch()
ngx_int_t webdav_handle_proppatch (ngx_http_request_t * r)
Definition at line 505 of file methods_basic.c.
References brix_http_read_body(), and webdav_proppatch_body_handler().
Referenced by webdav_dispatch_inner().
webdav_handle_put_body()
void webdav_handle_put_body (ngx_http_request_t * r)
Definition at line 233 of file put.c.
References brix_imp_request_begin(), brix_imp_request_end(), ngx_http_brix_webdav_req_ctx_t::identity, ngx_http_brix_webdav_module, and webdav_put_body_inner().
Referenced by webdav_dispatch_inner().
webdav_handle_search()
ngx_int_t webdav_handle_search (ngx_http_request_t * r)
Definition at line 446 of file search.c.
References brix_http_read_body(), and webdav_search_body_handler().
Referenced by webdav_dispatch_inner().
webdav_handle_unlock()
ngx_int_t webdav_handle_unlock (ngx_http_request_t * r)
Definition at line 595 of file lock.c.
References ngx_http_brix_webdav_loc_conf_t::common, webdav_lock_xattr_t::expires, ngx_http_brix_webdav_module, ngx_http_brix_webdav_resolve_path(), ngx_http_brix_shared_conf_t::root_canon, webdav_lock_xattr_t::token, webdav_lock_reap_null(), webdav_lock_xattr_delete(), webdav_lock_xattr_read(), WEBDAV_MAX_PATH, webdav_send_no_body(), and webdav_tpc_find_header.
Referenced by webdav_dispatch_inner().