nginx-xrootd: src/observability/metrics/webdav.c File Reference
webdav.c File Reference
#include "metrics_internal.h"
Functions
void brix_export_webdav_metrics (metrics_writer_t *mw, ngx_brix_metrics_t *shm)
Variables
static const char * brix_webdav_method_names [9]
static const char * brix_webdav_auth_names [6]
static const char * brix_webdav_put_names [4]
static const char * brix_webdav_propfind_depth_names [3]
static const char * brix_webdav_tpc_names [9]
static const char * brix_webdav_cors_names [4]
static const char * brix_webdav_tpc_cred_names [5]
Function Documentation
brix_export_webdav_metrics()
void brix_export_webdav_metrics (metrics_writer_t * mw, ngx_brix_metrics_t * shm)
Definition at line 99 of file webdav.c.
References ngx_brix_webdav_metrics_t::auth_total, BRIX_HTTP_NSTATUS, brix_http_range_result_names, brix_http_status_names, brix_webdav_auth_names, brix_webdav_cors_names, brix_webdav_method_names, BRIX_WEBDAV_NAUTH_RESULTS, BRIX_WEBDAV_NCORS_EVENTS, BRIX_WEBDAV_NMETHODS, BRIX_WEBDAV_NPROPFIND_DEPTHS, BRIX_WEBDAV_NPUT_MODES, BRIX_WEBDAV_NRANGE_RESULTS, BRIX_WEBDAV_NTPC_CRED_EVENTS, BRIX_WEBDAV_NTPC_EVENTS, brix_webdav_propfind_depth_names, brix_webdav_put_names, brix_webdav_tpc_cred_names, brix_webdav_tpc_names, ngx_brix_webdav_metrics_t::bytes_rx_ipv4_total, ngx_brix_webdav_metrics_t::bytes_rx_ipv6_total, ngx_brix_webdav_metrics_t::bytes_rx_total, ngx_brix_webdav_metrics_t::bytes_tx_ipv4_total, ngx_brix_webdav_metrics_t::bytes_tx_ipv6_total, ngx_brix_webdav_metrics_t::bytes_tx_total, ngx_brix_webdav_metrics_t::cors_total, mw_emit_labeled(), mw_emit_scalar(), mw_printf(), ngx_brix_webdav_metrics_t::propfind_depth_total, ngx_brix_webdav_metrics_t::propfind_entries_total, ngx_brix_webdav_metrics_t::put_body_total, ngx_brix_webdav_metrics_t::range_total, ngx_brix_webdav_metrics_t::requests_total, ngx_brix_webdav_metrics_t::responses_total, ngx_brix_webdav_metrics_t::tpc_cred_total, ngx_brix_webdav_metrics_t::tpc_total, and ngx_brix_metrics_t::webdav.
Referenced by brix_export_prometheus_metrics().
Variable Documentation
brix_webdav_auth_names
const char* brix_webdav_auth_names[6] static
Initial value:
= {
    "none",
    "cert_ok",
    "token_ok",
    "anonymous_fallback",
    "rejected",
    "pwd_ok",
}
Definition at line 34 of file webdav.c.
Referenced by brix_export_webdav_metrics().
brix_webdav_cors_names
const char* brix_webdav_cors_names[4] static
Initial value:
= {
    "no_origin",
    "allowed",
    "denied",
    "preflight",
}
Definition at line 70 of file webdav.c.
Referenced by brix_export_webdav_metrics().
brix_webdav_method_names
const char* brix_webdav_method_names[9] static
Initial value:
= {
    "OPTIONS",
    "HEAD",
    "GET",
    "PUT",
    "DELETE",
    "MKCOL",
    "COPY",
    "PROPFIND",
    "OTHER",
}
Definition at line 22 of file webdav.c.
Referenced by brix_export_webdav_metrics().
brix_webdav_propfind_depth_names
const char* brix_webdav_propfind_depth_names[ 3] static
Initial value:
=
{
    "0",
    "1",
    "infinity",
}
Definition at line 50 of file webdav.c.
Referenced by brix_export_webdav_metrics().
brix_webdav_put_names
const char* brix_webdav_put_names[4] static
Initial value:
= {
    "empty",
    "memory",
    "spooled",
    "threaded",
}
Definition at line 43 of file webdav.c.
Referenced by brix_export_webdav_metrics().
brix_webdav_tpc_cred_names
const char* brix_webdav_tpc_cred_names[5] static
Initial value:
= {
    "started",
    "success",
    "error",
    "unknown_mode",
    "parse_error",
}
Definition at line 77 of file webdav.c.
Referenced by brix_export_webdav_metrics().
brix_webdav_tpc_names
const char* brix_webdav_tpc_names[9] static
Initial value:
= {
    "pull_started",
    "pull_success",
    "curl_started",
    "curl_success",
    "curl_error",
    "push_started",
    "push_success",
    "bad_request",
    "commit_error",
}
Definition at line 58 of file webdav.c.
Referenced by brix_export_webdav_metrics().