nginx-xrootd: src/protocols/webdav/webdav_module_internal.h File Reference
webdav_module_internal.h File Reference
#include "webdav.h"
#include "module_acc_directives.h"
#include "core/compat/integrity_info.h"
#include "auth/authz/acc/acc.h"
#include "protocols/s3/s3.h"
#include "core/shm/kv.h"
#include "core/shm/rate_limit.h"
#include "auth/token/token_cache.h"
#include "net/mirror/http_mirror.h"
#include "net/ratelimit/ratelimit.h"
#include <curl/curl.h>
#include <stddef.h>
#include <stdlib.h>
#include <limits.h>
Functions
char * webdav_conf_add_cors_origin (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * webdav_conf_dig_export (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
char * webdav_conf_proxy_auth (ngx_conf_t *cf, ngx_command_t *cmd, void *conf_ptr)
ngx_int_t webdav_open_file_cache_arg (ngx_str_t *arg, ngx_int_t *max, time_t *inactive, ngx_flag_t *off)
char * webdav_conf_open_file_cache (ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
ngx_int_t brix_http_protocol_variable (ngx_http_request_t *r, ngx_http_variable_value_t *v, uintptr_t data)
ngx_int_t brix_http_add_protocol_variables (ngx_conf_t *cf)
ngx_int_t ngx_http_brix_webdav_preconfiguration (ngx_conf_t *cf)
ngx_int_t ngx_http_brix_webdav_init_process (ngx_cycle_t *cycle)
void ngx_http_brix_webdav_exit_process (ngx_cycle_t *cycle)
Variables
ngx_conf_enum_t webdav_auth_values []
ngx_conf_enum_t brix_webdav_cks_xattr_formats []
ngx_command_t ngx_http_brix_webdav_commands []
ngx_http_module_t ngx_http_brix_webdav_module_ctx
Function Documentation
brix_http_add_protocol_variables()
ngx_int_t brix_http_add_protocol_variables (ngx_conf_t * cf)
Definition at line 68 of file module_init.c.
References brix_http_protocol_variable(), and name.
Referenced by ngx_http_brix_webdav_preconfiguration().
brix_http_protocol_variable()
ngx_int_t brix_http_protocol_variable (ngx_http_request_t * r, ngx_http_variable_value_t * v, uintptr_t data)
Definition at line 29 of file module_init.c.
References ngx_http_s3_loc_conf_t::common, ngx_http_brix_webdav_loc_conf_t::common, ngx_http_brix_cvmfs_loc_conf_t::cvmfs, ngx_http_brix_shared_conf_t::enable, brix_cvmfs_conf_t::enable, ngx_http_brix_cvmfs_module, ngx_http_brix_s3_module, and ngx_http_brix_webdav_module.
Referenced by brix_http_add_protocol_variables().
ngx_http_brix_webdav_exit_process()
void ngx_http_brix_webdav_exit_process (ngx_cycle_t * cycle)
Definition at line 102 of file module_init.c.
ngx_http_brix_webdav_init_process()
ngx_int_t ngx_http_brix_webdav_init_process (ngx_cycle_t * cycle)
Definition at line 93 of file module_init.c.
ngx_http_brix_webdav_preconfiguration()
ngx_int_t ngx_http_brix_webdav_preconfiguration (ngx_conf_t * cf)
Definition at line 86 of file module_init.c.
References brix_http_add_protocol_variables().
webdav_conf_add_cors_origin()
char * webdav_conf_add_cors_origin (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 83 of file module_directives.c.
References ngx_http_brix_webdav_loc_conf_t::cors_origins.
webdav_conf_dig_export()
char * webdav_conf_dig_export (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 118 of file module_directives.c.
References brix_dig_export_t::canon, ngx_http_brix_webdav_loc_conf_t::dig_exports, brix_dig_export_t::dir, brix_dig_export_t::name, ngx_memcpy, ngx_pnalloc(), and PATH_MAX.
webdav_conf_open_file_cache()
char * webdav_conf_open_file_cache (ngx_conf_t * cf, ngx_command_t * cmd, void * conf)
Definition at line 277 of file module_directives.c.
References ngx_http_brix_webdav_loc_conf_t::open_file_cache, and webdav_open_file_cache_arg().
webdav_conf_proxy_auth()
char * webdav_conf_proxy_auth (ngx_conf_t * cf, ngx_command_t * cmd, void * conf_ptr)
Definition at line 167 of file module_directives.c.
References ngx_http_brix_webdav_loc_conf_t::upstream_auth, ngx_http_brix_webdav_loc_conf_t::upstream_auth_token, WEBDAV_PROXY_AUTH_ANONYMOUS, WEBDAV_PROXY_AUTH_FORWARD, and WEBDAV_PROXY_AUTH_TOKEN.
webdav_open_file_cache_arg()
ngx_int_t webdav_open_file_cache_arg (ngx_str_t * arg, ngx_int_t * max, time_t * inactive, ngx_flag_t * off)
Definition at line 250 of file module_directives.c.
References s.
Referenced by webdav_conf_open_file_cache().
Variable Documentation
brix_webdav_cks_xattr_formats
ngx_conf_enum_t brix_webdav_cks_xattr_formats[] extern
Definition at line 30 of file module.c.
ngx_http_brix_webdav_commands
ngx_command_t ngx_http_brix_webdav_commands[] extern
Definition at line 36 of file module.c.
ngx_http_brix_webdav_module_ctx
ngx_http_module_t ngx_http_brix_webdav_module_ctx extern
Definition at line 562 of file module.c.
webdav_auth_values
ngx_conf_enum_t webdav_auth_values[] extern
Definition at line 9 of file module.c.