nginx-xrootd: client/lib/protocols/http/webfile_internal.h File Reference
webfile_internal.h File Reference
#include "brix.h"
#include "core/compat/uri.h"
#include "core/compat/host_format.h"
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <stdio.h>
#include <time.h>
#include <poll.h>
#include <errno.h>
#include <unistd.h>
Data Structures
struct brix_webfile
Macros
#define WEB_TIMEOUT_MS 30000
#define WEB_HDR_MAX 16384
Functions
const char * tag_val (const char *p, const char *end, const char *name, size_t *vlen)
long parse_http_date (const char *v, size_t n)
int parse_response (const char *p, const char *end, brix_statinfo *si, char *href, size_t hrefsz)
void web_auth (const char *bearer, char *out, size_t outsz)
int xml_name_char (char c)
const char * next_response_open (const char *p, const char *end)
const char * next_response_close (const char *p, const char *end)
int has_collection_element (const char *p, const char *end)
void path_basename (const char *path, char *out, size_t outsz)
int webdav_parse_single (const char *body, size_t blen, brix_statinfo *si, brix_status *st)
int webdav_parse_multi (const char *body, size_t blen, const char *self, brix_dirent **ents_out, size_t *n_out, brix_status *st)
void web_disconnect (brix_webfile *wf)
int web_connect (brix_webfile *wf, brix_status *st)
ssize_t web_read_some (brix_webfile *wf, void *buf, size_t n, brix_status *st)
long long hdr_clen (const char *hdrs)
ssize_t web_get_range (brix_webfile *wf, int64_t off, void *buf, size_t len, brix_status *st)
int webfile_window_ms (void)
Macro Definition Documentation
WEB_HDR_MAX
#define WEB_HDR_MAX 16384
Definition at line 20 of file webfile_internal.h.
WEB_TIMEOUT_MS
#define WEB_TIMEOUT_MS 30000
Definition at line 19 of file webfile_internal.h.
Function Documentation
has_collection_element()
int has_collection_element (const char * p, const char * end)
Definition at line 340 of file webfile.c.
References name, s, xml_local_name(), and xml_name_boundary().
Referenced by parse_response().
hdr_clen()
long long hdr_clen (const char * hdrs)
Definition at line 81 of file webfile_io.c.
Referenced by web_range_read_headers().
next_response_close()
const char * next_response_close (const char * p, const char * end)
Definition at line 311 of file webfile.c.
References name, s, and xml_name_char().
Referenced by webdav_parse_multi(), and webdav_parse_single().
next_response_open()
const char * next_response_open (const char * p, const char * end)
Definition at line 281 of file webfile.c.
References name, xml_local_name(), and xml_name_boundary().
Referenced by webdav_parse_multi(), and webdav_parse_single().
parse_http_date()
long parse_http_date (const char * v, size_t n)
Definition at line 38 of file webfile.c.
Referenced by parse_response().
parse_response()
int parse_response (const char * p, const char * end, brix_statinfo * si, char * href, size_t hrefsz)
Definition at line 58 of file webfile.c.
References brix_http_urldecode(), BRIX_URLDECODE_OK, brix_statinfo::flags, has_collection_element(), kXR_isDir, brix_statinfo::mtime, parse_http_date(), brix_statinfo::size, and tag_val().
Referenced by webdav_parse_multi(), and webdav_parse_single().
path_basename()
void path_basename (const char * path, char * out, size_t outsz)
Definition at line 284 of file xrdcp.c.
Referenced by batch_copy_one(), brix_web_readdir(), brix_web_readdir_pooled(), strip_prefix_rel(), transfer_one(), webdav_parse_multi(), and xrdcp_enable_progress_if_needed().
tag_val()
const char * tag_val (const char * p, const char * end, const char * name, size_t * vlen)
Definition at line 11 of file webfile.c.
References name.
Referenced by parse_response().
web_auth()
void web_auth (const char * bearer, char * out, size_t outsz)
Definition at line 113 of file webfile.c.
Referenced by brix_web_readdir(), brix_web_stat(), and brix_webfile_open().
web_connect()
int web_connect (brix_webfile * wf, brix_status * st)
Definition at line 30 of file webfile_io.c.
References brix_tcp_connect(), brix_tls_client(), brix_webfile::ca_dir, close(), brix_webfile::connected, brix_io::fd, brix_webfile::host, brix_webfile::io, brix_webfile::port, brix_io::timeout_ms, brix_webfile::timeout_ms, brix_webfile::tls, brix_webfile::tls_ctx, and brix_webfile::verify.
Referenced by brix_webfile_pread().
web_disconnect()
void web_disconnect (brix_webfile * wf)
Definition at line 12 of file webfile_io.c.
References brix_tls_client_free(), close(), brix_webfile::connected, brix_io::fd, brix_webfile::io, brix_webfile::tls, and brix_webfile::tls_ctx.
Referenced by brix_webfile_close(), web_range_read_headers(), web_range_send_req(), and web_range_stream_body().
web_get_range()
ssize_t web_get_range (brix_webfile * wf, int64_t off, void * buf, size_t len, brix_status * st)
Definition at line 313 of file webfile_io.c.
References WEB_HDR_MAX, web_range_read_headers(), web_range_send_req(), and web_range_stream_body().
Referenced by brix_webfile_pread().
web_read_some()
ssize_t web_read_some (brix_webfile * wf, void * buf, size_t n, brix_status * st)
Definition at line 52 of file webfile_io.c.
References brix_status_set(), brix_tls_read_some(), brix_io::fd, brix_webfile::io, read(), brix_io::ssl, brix_io::timeout_ms, and XRDC_ESOCK.
Referenced by web_range_read_headers(), and web_range_stream_body().
webdav_parse_multi()
int webdav_parse_multi (const char * body, size_t blen, const char * self, brix_dirent ** ents_out, size_t * n_out, brix_status * st)
Definition at line 389 of file webfile.c.
References brix_status_set(), close(), brix_dirent::have_stat, name, next_response_close(), next_response_open(), open(), parse_response(), path_basename(), brix_dirent::st, XRDC_EPROTO, XRDC_NAME_MAX, and XRDC_PATH_MAX.
Referenced by brix_web_readdir(), and brix_web_readdir_pooled().
webdav_parse_single()
int webdav_parse_single (const char * body, size_t blen, brix_statinfo * si, brix_status * st)
Definition at line 128 of file webfile.c.
References brix_status_set(), next_response_close(), next_response_open(), parse_response(), XRDC_EPROTO, and XRDC_PATH_MAX.
Referenced by brix_web_stat(), and brix_web_stat_pooled().
webfile_window_ms()
int webfile_window_ms (void)
Definition at line 387 of file webfile_io.c.
Referenced by brix_webfile_pread().
xml_name_char()
int xml_name_char (char c)
Definition at line 209 of file webfile.c.
References c.
Referenced by next_response_close(), and xml_local_name().