nginx-xrootd: client/lib/protocols/http/webfile_io.c File Reference
webfile_io.c File Reference
#include "webfile_internal.h"
Functions
void web_disconnect (brix_webfile *wf)
int web_connect (brix_webfile *wf, brix_status *st)
ssize_t web_read_some (brix_webfile *wf, void *buf, size_t n, brix_status *st)
long long hdr_clen (const char *hdrs)
ssize_t web_get_range (brix_webfile *wf, int64_t off, void *buf, size_t len, brix_status *st)
brix_webfile * brix_webfile_open (const brix_weburl *u, const char *path, const char *bearer, int verify, const char *ca_dir, int timeout_ms, brix_statinfo *si_out, brix_status *st)
int64_t brix_webfile_size (const brix_webfile *wf)
int webfile_window_ms (void)
ssize_t brix_webfile_pread (brix_webfile *wf, int64_t off, void *buf, size_t len, brix_status *st)
void brix_webfile_close (brix_webfile *wf, brix_status *st)
Function Documentation
brix_webfile_close()
void brix_webfile_close (brix_webfile * wf, brix_status * st)
Definition at line 368 of file webfile_io.c.
References web_disconnect().
Referenced by xfs_release().
brix_webfile_open()
brix_webfile * brix_webfile_open (const brix_weburl * u, const char * path, const char * bearer, int verify, const char * ca_dir, int timeout_ms, brix_statinfo * si_out, brix_status * st)
Definition at line 239 of file webfile_io.c.
References brix_webfile::auth, brix_format_host_port(), brix_status_set(), brix_web_stat(), brix_webfile::ca_dir, brix_io::fd, brix_statinfo::flags, brix_weburl::host, brix_webfile::host, brix_webfile::hostport, brix_webfile::io, kXR_isDir, brix_webfile::path, brix_weburl::port, brix_webfile::port, brix_statinfo::size, brix_webfile::size, brix_webfile::timeout_ms, brix_weburl::tls, brix_webfile::tls, brix_webfile::verify, web_auth(), WEB_TIMEOUT_MS, XRDC_EPROTO, and XRDC_EUSAGE.
Referenced by afh_open().
brix_webfile_pread()
ssize_t brix_webfile_pread (brix_webfile * wf, int64_t off, void * buf, size_t len, brix_status * st)
Definition at line 305 of file webfile_io.c.
References brix_backoff_sleep_fast(), brix_mono_ns(), brix_status_retryable(), brix_webfile::connected, brix_webfile::size, web_connect(), web_get_range(), and webfile_window_ms().
Referenced by afh_pread().
brix_webfile_size()
int64_t brix_webfile_size (const brix_webfile * wf)
Definition at line 281 of file webfile_io.c.
References brix_webfile::size.
hdr_clen()
long long hdr_clen (const char * hdrs)
Definition at line 81 of file webfile_io.c.
Referenced by web_get_range().
web_connect()
int web_connect (brix_webfile * wf, brix_status * st)
Definition at line 30 of file webfile_io.c.
References brix_tcp_connect(), brix_tls_client(), brix_webfile::ca_dir, close(), brix_webfile::connected, brix_io::fd, brix_webfile::host, brix_webfile::io, brix_webfile::port, brix_io::timeout_ms, brix_webfile::timeout_ms, brix_webfile::tls, brix_webfile::tls_ctx, and brix_webfile::verify.
Referenced by brix_webfile_pread().
web_disconnect()
void web_disconnect (brix_webfile * wf)
Definition at line 12 of file webfile_io.c.
References brix_tls_client_free(), close(), brix_webfile::connected, brix_io::fd, brix_webfile::io, brix_webfile::tls, and brix_webfile::tls_ctx.
Referenced by brix_webfile_close(), and web_get_range().
web_get_range()
ssize_t web_get_range (brix_webfile * wf, int64_t off, void * buf, size_t len, brix_status * st)
Definition at line 101 of file webfile_io.c.
References brix_webfile::auth, brix_read_full(), brix_status_set(), brix_write_full(), have(), hdr_clen(), brix_webfile::hostport, brix_webfile::io, kXR_NotAuthorized, kXR_NotFound, brix_webfile::path, web_disconnect(), WEB_HDR_MAX, web_read_some(), XRDC_EPROTO, XRDC_ESOCK, and XRDC_EUSAGE.
Referenced by brix_webfile_pread().
web_read_some()
ssize_t web_read_some (brix_webfile * wf, void * buf, size_t n, brix_status * st)
Definition at line 52 of file webfile_io.c.
References brix_status_set(), brix_tls_read_some(), brix_io::fd, brix_webfile::io, read(), brix_io::ssl, brix_io::timeout_ms, and XRDC_ESOCK.
Referenced by web_get_range().
webfile_window_ms()
int webfile_window_ms (void)
Definition at line 292 of file webfile_io.c.
References brix_xrdrc_default_ms(), and XRDC_DEFAULT_MAX_STALL_MS.
Referenced by brix_webfile_pread().