nginx-xrootd: client/lib/protocols/http/webfile.c File Reference
webfile.c File Reference
#include "webfile_internal.h"
Functions
const char * tag_val (const char *p, const char *end, const char *name, size_t *vlen)
long parse_http_date (const char *v, size_t n)
int parse_response (const char *p, const char *end, brix_statinfo *si, char *href, size_t hrefsz)
void web_auth (const char *bearer, char *out, size_t outsz)
int brix_web_stat (const brix_weburl *u, const char *path, const char *bearer, int verify, const char *ca_dir, brix_statinfo *si, brix_status *st)
int xml_name_char (char c)
const char * next_response_open (const char *p, const char *end)
const char * next_response_close (const char *p, const char *end)
int has_collection_element (const char *p, const char *end)
void path_basename (const char *path, char *out, size_t outsz)
int brix_web_readdir (const brix_weburl *u, const char *path, const char *bearer, int verify, const char *ca_dir, brix_dirent **ents_out, size_t *n_out, brix_status *st)
Function Documentation
brix_web_readdir()
int brix_web_readdir (const brix_weburl * u, const char * path, const char * bearer, int verify, const char * ca_dir, brix_dirent ** ents_out, size_t * n_out, brix_status * st)
Definition at line 308 of file webfile.c.
References brix_http_resp::body, brix_http_resp::body_len, brix_http_req(), brix_http_resp_free(), brix_status_set(), brix_dirent::have_stat, brix_weburl::host, name, next_response_close(), next_response_open(), open(), parse_response(), path_basename(), brix_weburl::port, brix_dirent::st, brix_http_resp::status, brix_weburl::tls, web_auth(), WEB_TIMEOUT_MS, XRDC_EPROTO, XRDC_NAME_MAX, and XRDC_PATH_MAX.
Referenced by web_ls_print_dir(), and xfs_readdir().
brix_web_stat()
int brix_web_stat (const brix_weburl * u, const char * path, const char * bearer, int verify, const char * ca_dir, brix_statinfo * si, brix_status * st)
Definition at line 121 of file webfile.c.
References brix_http_resp::body, brix_http_resp::body_len, brix_http_req(), brix_http_resp_free(), brix_status_set(), brix_weburl::host, kXR_NotFound, next_response_close(), next_response_open(), parse_response(), brix_weburl::port, brix_http_resp::status, brix_weburl::tls, web_auth(), WEB_TIMEOUT_MS, XRDC_EPROTO, and XRDC_PATH_MAX.
Referenced by brix_webfile_open(), web_stat(), xfs_getattr(), and xrootdfs_aio_main().
has_collection_element()
int has_collection_element (const char * p, const char * end)
Definition at line 252 of file webfile.c.
References name, s, and xml_name_char().
Referenced by parse_response().
next_response_close()
const char * next_response_close (const char * p, const char * end)
Definition at line 223 of file webfile.c.
References name, s, and xml_name_char().
Referenced by brix_web_readdir(), and brix_web_stat().
next_response_open()
const char * next_response_open (const char * p, const char * end)
Definition at line 187 of file webfile.c.
References name, s, and xml_name_char().
Referenced by brix_web_readdir(), and brix_web_stat().
parse_http_date()
long parse_http_date (const char * v, size_t n)
Definition at line 35 of file webfile.c.
Referenced by parse_response().
parse_response()
int parse_response (const char * p, const char * end, brix_statinfo * si, char * href, size_t hrefsz)
Definition at line 55 of file webfile.c.
References brix_http_urldecode(), BRIX_URLDECODE_OK, brix_statinfo::flags, has_collection_element(), kXR_isDir, brix_statinfo::mtime, parse_http_date(), brix_statinfo::size, and tag_val().
Referenced by brix_web_readdir(), and brix_web_stat().
path_basename()
void path_basename (const char * path, char * out, size_t outsz)
Definition at line 288 of file webfile.c.
Referenced by brix_web_readdir().
tag_val()
const char * tag_val (const char * p, const char * end, const char * name, size_t * vlen)
Definition at line 8 of file webfile.c.
References name.
Referenced by parse_response().
web_auth()
void web_auth (const char * bearer, char * out, size_t outsz)
Definition at line 110 of file webfile.c.
Referenced by brix_web_readdir(), brix_web_stat(), and brix_webfile_open().
xml_name_char()
int xml_name_char (char c)
Definition at line 175 of file webfile.c.
References c.
Referenced by has_collection_element(), next_response_close(), and next_response_open().