nginx-xrootd: client/lib/protocols/http/weblist.c File Reference
weblist.c File Reference
#include "brix.h"
#include "core/compat/uri.h"
#include "core/compat/host_format.h"
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct s3_list_req_t
struct weblist_acc_t
struct s3_list_out_t
Macros
#define XRDC_WEBLIST_MAX 200000 /* hard cap on files returned */
#define XRDC_WEBLIST_TIMEOUT 60000
Functions
static int push (weblist_acc_t *acc, const char *s)
void brix_strv_free (char **arr, size_t n)
static int xml_tag (const char **p, const char *otag, const char *ctag, char *out, size_t osz)
static int s3_canon_qs (const char *token, const char *encp, int have_prefix, char *out, size_t outsz)
static int s3_list_split_path (const brix_weburl *u, s3_list_req_t *req, char *prefix, size_t prefixsz, brix_status *st)
static int s3_list_build_request (const s3_list_req_t *req, const char *token, const s3_list_out_t *out, brix_status *st)
static int s3_list_scan_keys (const brix_http_resp *r, weblist_acc_t *acc, brix_status *st)
static int s3_list_next_token (const brix_http_resp *r, char *token, size_t tokensz, int *more, brix_status *st)
int brix_s3_list (const brix_weburl *u, const char *ak, const char *sk, const char *region, int verify, const char *ca_dir, char ***keys, size_t *n_out, brix_status *st)
int brix_webdav_mkcol (const brix_weburl *u, const char *path, const char *bearer, int verify, const char *ca_dir, brix_status *st)
static void webdav_list_build_headers (const char *bearer, char *headers, size_t headerssz)
static int webdav_list_emit_block (const char *p, const char *end, weblist_acc_t *acc, brix_status *st)
static int webdav_list_scan_body (const char *body, weblist_acc_t *acc, brix_status *st)
int brix_webdav_list (const brix_weburl *u, const char *bearer, int verify, const char *ca_dir, char ***paths, size_t *n_out, brix_status *st)
Macro Definition Documentation
XRDC_WEBLIST_MAX
#define XRDC_WEBLIST_MAX 200000 /* hard cap on files returned */
Definition at line 27 of file weblist.c.
XRDC_WEBLIST_TIMEOUT
#define XRDC_WEBLIST_TIMEOUT 60000
Definition at line 28 of file weblist.c.
Function Documentation
brix_s3_list()
int brix_s3_list (const brix_weburl * u, const char * ak, const char * sk, const char * region, int verify, const char * ca_dir, char *** keys, size_t * n_out, brix_status * st)
Definition at line 313 of file weblist.c.
References s3_list_req_t::ak, weblist_acc_t::arr, brix_format_host_port(), brix_http_req(), brix_http_resp_free(), brix_http_urlencode(), brix_status_set(), brix_strv_free(), s3_list_req_t::encp, s3_list_req_t::have_prefix, brix_weburl::host, s3_list_req_t::hostport, weblist_acc_t::n, brix_weburl::port, s3_list_req_t::region, region, s3_list_build_request(), s3_list_next_token(), s3_list_scan_keys(), s3_list_split_path(), s3_list_req_t::sk, brix_http_resp::status, brix_weburl::tls, XRDC_EPROTO, XRDC_EUSAGE, XRDC_PATH_MAX, and XRDC_WEBLIST_TIMEOUT.
Referenced by battery_s3(), and recursive_s3_download().
brix_strv_free()
void brix_strv_free (char ** arr, size_t n)
Definition at line 98 of file weblist.c.
Referenced by battery_s3(), brix_s3_list(), brix_webdav_list(), recursive_s3_download(), and recursive_web_download().
brix_webdav_list()
int brix_webdav_list (const brix_weburl * u, const char * bearer, int verify, const char * ca_dir, char *** paths, size_t * n_out, brix_status * st)
Definition at line 523 of file weblist.c.
References weblist_acc_t::arr, brix_http_resp::body, brix_http_req(), brix_http_resp_free(), brix_status_set(), brix_strv_free(), brix_weburl::host, brix_weburl::is_s3, weblist_acc_t::n, brix_weburl::path, brix_weburl::port, brix_http_resp::status, brix_weburl::tls, webdav_list_build_headers(), webdav_list_scan_body(), XRDC_EPROTO, XRDC_EUSAGE, and XRDC_WEBLIST_TIMEOUT.
Referenced by recursive_web_download().
brix_webdav_mkcol()
int brix_webdav_mkcol (const brix_weburl * u, const char * path, const char * bearer, int verify, const char * ca_dir, brix_status * st)
Definition at line 391 of file weblist.c.
References brix_http_req(), brix_http_resp_free(), brix_status_set(), brix_weburl::host, brix_weburl::port, brix_http_resp::status, brix_weburl::tls, XRDC_EPROTO, and XRDC_WEBLIST_TIMEOUT.
Referenced by ensure_web_dst_base(), mkcol_parents(), recursive_web_upload(), and walk_handle_dir().
push()
static int push (weblist_acc_t * acc, const char * s) static
Definition at line 82 of file weblist.c.
References weblist_acc_t::arr, weblist_acc_t::cap, weblist_acc_t::n, and s.
Referenced by s3_list_scan_keys(), and webdav_list_emit_block().
s3_canon_qs()
static int s3_canon_qs (const char * token, const char * encp, int have_prefix, char * out, size_t outsz) static
Definition at line 134 of file weblist.c.
References brix_http_urlencode().
Referenced by s3_list_build_request().
s3_list_build_request()
static int s3_list_build_request (const s3_list_req_t * req, const char * token, const s3_list_out_t * out, brix_status * st) static
Definition at line 215 of file weblist.c.
References s3_list_req_t::ak, brix_s3_sign_v4_q(), brix_status_set(), s3_list_req_t::bucket, s3_list_req_t::encp, s3_list_req_t::have_prefix, s3_list_out_t::hdrs, s3_list_out_t::hdrssz, s3_list_req_t::hostport, s3_list_out_t::path, s3_list_out_t::pathsz, s3_list_req_t::region, s3_canon_qs(), s3_list_req_t::sk, XRDC_EAUTH, XRDC_EUSAGE, and XRDC_PATH_MAX.
Referenced by brix_s3_list().
s3_list_next_token()
static int s3_list_next_token (const brix_http_resp * r, char * token, size_t tokensz, int * more, brix_status * st) static
Definition at line 288 of file weblist.c.
References brix_http_resp::body, brix_status_set(), xml_tag(), and XRDC_EPROTO.
Referenced by brix_s3_list().
s3_list_scan_keys()
static int s3_list_scan_keys (const brix_http_resp * r, weblist_acc_t * acc, brix_status * st) static
Definition at line 251 of file weblist.c.
References brix_http_resp::body, brix_status_set(), key, weblist_acc_t::n, push(), xml_tag(), XRDC_EPROTO, XRDC_PATH_MAX, and XRDC_WEBLIST_MAX.
Referenced by brix_s3_list().
s3_list_split_path()
static int s3_list_split_path (const brix_weburl * u, s3_list_req_t * req, char * prefix, size_t prefixsz, brix_status * st) static
Definition at line 173 of file weblist.c.
References brix_status_set(), s3_list_req_t::bucket, brix_weburl::path, and XRDC_EUSAGE.
Referenced by brix_s3_list().
webdav_list_build_headers()
static void webdav_list_build_headers (const char * bearer, char * headers, size_t headerssz) static
Definition at line 428 of file weblist.c.
Referenced by brix_webdav_list().
webdav_list_emit_block()
static int webdav_list_emit_block (const char * p, const char * end, weblist_acc_t * acc, brix_status * st) static
Definition at line 453 of file weblist.c.
References brix_http_urldecode(), brix_status_set(), BRIX_URLDECODE_OK, push(), XRDC_EPROTO, and XRDC_PATH_MAX.
Referenced by webdav_list_scan_body().
webdav_list_scan_body()
static int webdav_list_scan_body (const char * body, weblist_acc_t * acc, brix_status * st) static
Definition at line 505 of file weblist.c.
References weblist_acc_t::n, webdav_list_emit_block(), and XRDC_WEBLIST_MAX.
Referenced by brix_webdav_list().
xml_tag()
static int xml_tag (const char ** p, const char * otag, const char * ctag, char * out, size_t osz) static
Definition at line 112 of file weblist.c.
References s.
Referenced by s3_list_next_token(), and s3_list_scan_keys().