var wire__core__requests_8h =
[
    [ "ClientInitHandShake", "structClientInitHandShake.html", "structClientInitHandShake" ],
    [ "ServerInitHandShake", "structServerInitHandShake.html", "structServerInitHandShake" ],
    [ "ClientRequestHdr", "structClientRequestHdr.html", "structClientRequestHdr" ],
    [ "ServerResponseHdr", "structServerResponseHdr.html", "structServerResponseHdr" ],
    [ "ServerResponseBody_Status", "structServerResponseBody__Status.html", "structServerResponseBody__Status" ],
    [ "ServerResponseBody_pgRead", "structServerResponseBody__pgRead.html", "structServerResponseBody__pgRead" ],
    [ "ServerResponseBody_pgWrite", "structServerResponseBody__pgWrite.html", "structServerResponseBody__pgWrite" ],
    [ "ServerResponseBody_pgWrCSE", "structServerResponseBody__pgWrCSE.html", "structServerResponseBody__pgWrCSE" ],
    [ "ServerStatusResponse_pgRead", "structServerStatusResponse__pgRead.html", "structServerStatusResponse__pgRead" ],
    [ "ServerStatusResponse_pgWrite", "structServerStatusResponse__pgWrite.html", "structServerStatusResponse__pgWrite" ],
    [ "ServerErrorBody", "structServerErrorBody.html", "structServerErrorBody" ],
    [ "ServerRedirectBody", "structServerRedirectBody.html", "structServerRedirectBody" ],
    [ "ClientProtocolRequest", "structClientProtocolRequest.html", "structClientProtocolRequest" ],
    [ "ServerProtocolBody", "structServerProtocolBody.html", "structServerProtocolBody" ],
    [ "ClientLoginRequest", "structClientLoginRequest.html", "structClientLoginRequest" ],
    [ "ClientAuthRequest", "structClientAuthRequest.html", "structClientAuthRequest" ],
    [ "ServerLoginBody", "structServerLoginBody.html", "structServerLoginBody" ],
    [ "ClientOpenRequest", "structClientOpenRequest.html", "structClientOpenRequest" ],
    [ "ServerOpenBody", "structServerOpenBody.html", "structServerOpenBody" ],
    [ "ClientPrepareRequest", "structClientPrepareRequest.html", "structClientPrepareRequest" ],
    [ "ClientReadRequest", "structClientReadRequest.html", "structClientReadRequest" ],
    [ "ClientStatRequest", "structClientStatRequest.html", "structClientStatRequest" ],
    [ "ClientCloseRequest", "structClientCloseRequest.html", "structClientCloseRequest" ],
    [ "ClientPingRequest", "structClientPingRequest.html", "structClientPingRequest" ],
    [ "ClientQueryRequest", "structClientQueryRequest.html", "structClientQueryRequest" ],
    [ "ClientDirlistRequest", "structClientDirlistRequest.html", "structClientDirlistRequest" ]
];