nginx-xrootd: src/protocols/root/protocol/codec/wire_codec_unittest.c File Reference
wire_codec_unittest.c File Reference
#include "wire_codec.h"
#include <stdio.h>
#include <string.h>
Macros
#define CHECK(cond, msg)
Functions
static void test_stat (void)
static void test_statx (void)
static void test_dirlist (void)
static void test_query (void)
static void test_locate (void)
static void test_open (void)
static void test_read (void)
static void test_pgwrite (void)
static void test_truncate (void)
static void test_chkpoint (void)
static void test_mkdir (void)
static void test_chmod (void)
static void test_twopath (void)
static void test_empty (void)
static void test_login (void)
static void test_protocol (void)
static void test_sessid (void)
static void test_sigver (void)
static void test_prepare (void)
static void test_guards (void)
int main (void)
Variables
static int g_fail
Macro Definition Documentation
CHECK
#define CHECK (cond, msg)
Value:
    do {                                           \
    if (cond) { printf("ok: %s\n", msg); }                             \
    else      { printf("FAIL: %s\n", msg); g_fail = 1; }              \
} while (0)
Definition at line 24 of file wire_codec_unittest.c.
Function Documentation
main()
int main (void)
Definition at line 299 of file wire_codec_unittest.c.
References g_fail, test_chkpoint(), test_chmod(), test_dirlist(), test_empty(), test_guards(), test_locate(), test_login(), test_mkdir(), test_open(), test_pgwrite(), test_prepare(), test_protocol(), test_query(), test_read(), test_sessid(), test_sigver(), test_stat(), test_statx(), test_truncate(), and test_twopath().
test_chkpoint()
static void test_chkpoint (void) static
Definition at line 160 of file wire_codec_unittest.c.
References CHECK, xrdw_chkpoint_req_t::fhandle, xrdw_chkpoint_req_t::opcode, XRDW_BODY_LEN, xrdw_chkpoint_req_pack(), xrdw_chkpoint_req_unpack(), and XRDW_OK.
Referenced by main().
test_chmod()
static void test_chmod (void) static
Definition at line 185 of file wire_codec_unittest.c.
References CHECK, xrdw_chmod_req_t::mode, XRDW_BODY_LEN, xrdw_chmod_req_pack(), xrdw_chmod_req_unpack(), and XRDW_OK.
Referenced by main().
test_dirlist()
static void test_dirlist (void) static
Definition at line 64 of file wire_codec_unittest.c.
References CHECK, xrdw_dirlist_req_t::options, XRDW_BODY_LEN, xrdw_dirlist_req_pack(), xrdw_dirlist_req_unpack(), and XRDW_OK.
Referenced by main().
test_empty()
static void test_empty (void) static
Definition at line 207 of file wire_codec_unittest.c.
References CHECK, XRDW_BODY_LEN, xrdw_empty_req_pack(), xrdw_empty_req_unpack(), and XRDW_OK.
Referenced by main().
test_guards()
static void test_guards (void) static
Definition at line 287 of file wire_codec_unittest.c.
References CHECK, s, XRDW_BODY_LEN, XRDW_EINVAL, xrdw_empty_req_pack(), xrdw_read_req_pack(), xrdw_read_req_unpack(), xrdw_stat_req_pack(), and xrdw_stat_req_unpack().
Referenced by main().
test_locate()
static void test_locate (void) static
Definition at line 94 of file wire_codec_unittest.c.
References CHECK, xrdw_locate_req_t::options, XRDW_BODY_LEN, xrdw_locate_req_pack(), xrdw_locate_req_unpack(), and XRDW_OK.
Referenced by main().
test_login()
static void test_login (void) static
Definition at line 217 of file wire_codec_unittest.c.
References xrdw_login_req_t::capver, CHECK, xrdw_login_req_t::pid, xrdw_login_req_t::username, XRDW_BODY_LEN, xrdw_login_req_pack(), xrdw_login_req_unpack(), and XRDW_OK.
Referenced by main().
test_mkdir()
static void test_mkdir (void) static
Definition at line 173 of file wire_codec_unittest.c.
References CHECK, xrdw_mkdir_req_t::mode, xrdw_mkdir_req_t::options, XRDW_BODY_LEN, xrdw_mkdir_req_pack(), xrdw_mkdir_req_unpack(), and XRDW_OK.
Referenced by main().
test_open()
static void test_open (void) static
Definition at line 108 of file wire_codec_unittest.c.
References CHECK, xrdw_open_req_t::mode, xrdw_open_req_t::options, xrdw_open_req_t::optiont, XRDW_BODY_LEN, XRDW_OK, xrdw_open_req_pack(), and xrdw_open_req_unpack().
Referenced by main().
test_pgwrite()
static void test_pgwrite (void) static
Definition at line 137 of file wire_codec_unittest.c.
References CHECK, xrdw_pgwrite_req_t::fhandle, xrdw_pgwrite_req_t::offset, xrdw_pgwrite_req_t::pathid, xrdw_pgwrite_req_t::reqflags, XRDW_BODY_LEN, XRDW_OK, xrdw_pgwrite_req_pack(), and xrdw_pgwrite_req_unpack().
Referenced by main().
test_prepare()
static void test_prepare (void) static
Definition at line 273 of file wire_codec_unittest.c.
References CHECK, xrdw_prepare_req_t::options, xrdw_prepare_req_t::optionX, xrdw_prepare_req_t::port, XRDW_BODY_LEN, XRDW_OK, xrdw_prepare_req_pack(), and xrdw_prepare_req_unpack().
Referenced by main().
test_protocol()
static void test_protocol (void) static
Definition at line 232 of file wire_codec_unittest.c.
References CHECK, xrdw_protocol_req_t::clientpv, xrdw_protocol_req_t::expect, xrdw_protocol_req_t::flags, XRDW_BODY_LEN, XRDW_OK, xrdw_protocol_req_pack(), and xrdw_protocol_req_unpack().
Referenced by main().
test_query()
static void test_query (void) static
Definition at line 79 of file wire_codec_unittest.c.
References CHECK, xrdw_query_req_t::fhandle, xrdw_query_req_t::infotype, XRDW_BODY_LEN, XRDW_OK, xrdw_query_req_pack(), and xrdw_query_req_unpack().
Referenced by main().
test_read()
static void test_read (void) static
Definition at line 122 of file wire_codec_unittest.c.
References CHECK, xrdw_read_req_t::fhandle, xrdw_read_req_t::offset, xrdw_read_req_t::rlen, XRDW_BODY_LEN, XRDW_OK, xrdw_read_req_pack(), and xrdw_read_req_unpack().
Referenced by main().
test_sessid()
static void test_sessid (void) static
Definition at line 245 of file wire_codec_unittest.c.
References CHECK, xrdw_sessid_req_t::sessid, XRDW_BODY_LEN, XRDW_OK, xrdw_sessid_req_pack(), and xrdw_sessid_req_unpack().
Referenced by main().
test_sigver()
static void test_sigver (void) static
Definition at line 257 of file wire_codec_unittest.c.
References CHECK, xrdw_sigver_req_t::crypto, xrdw_sigver_req_t::expectrid, xrdw_sigver_req_t::flags, xrdw_sigver_req_t::seqno, XRDW_BODY_LEN, XRDW_OK, xrdw_sigver_req_pack(), and xrdw_sigver_req_unpack().
Referenced by main().
test_stat()
static void test_stat (void) static
Definition at line 30 of file wire_codec_unittest.c.
References CHECK, xrdw_stat_req_t::fhandle, xrdw_stat_req_t::options, xrdw_stat_req_t::wants, XRDW_BODY_LEN, XRDW_OK, xrdw_stat_req_pack(), and xrdw_stat_req_unpack().
Referenced by main().
test_statx()
static void test_statx (void) static
Definition at line 49 of file wire_codec_unittest.c.
References CHECK, xrdw_statx_req_t::fhandle, xrdw_statx_req_t::options, XRDW_BODY_LEN, XRDW_OK, xrdw_statx_req_pack(), and xrdw_statx_req_unpack().
Referenced by main().
test_truncate()
static void test_truncate (void) static
Definition at line 150 of file wire_codec_unittest.c.
References CHECK, xrdw_truncate_req_t::fhandle, xrdw_truncate_req_t::offset, XRDW_BODY_LEN, XRDW_OK, xrdw_truncate_req_pack(), and xrdw_truncate_req_unpack().
Referenced by main().
test_twopath()
static void test_twopath (void) static
Definition at line 196 of file wire_codec_unittest.c.
References xrdw_twopath_req_t::arg1len, CHECK, XRDW_BODY_LEN, XRDW_OK, xrdw_twopath_req_pack(), and xrdw_twopath_req_unpack().
Referenced by main().
Variable Documentation
g_fail
int g_fail static
Definition at line 22 of file wire_codec_unittest.c.
Referenced by main().