nginx-xrootd: src/protocols/root/protocol/codec/wire_codec_meta.c File Reference
wire_codec_meta.c File Reference
#include "wire_codec.h"
#include <string.h>
Functions
int xrdw_stat_req_pack (const xrdw_stat_req_t *r, uint8_t body[16])
int xrdw_stat_req_unpack (const uint8_t body[16], xrdw_stat_req_t *r)
int xrdw_statx_req_pack (const xrdw_statx_req_t *r, uint8_t body[16])
int xrdw_statx_req_unpack (const uint8_t body[16], xrdw_statx_req_t *r)
int xrdw_dirlist_req_pack (const xrdw_dirlist_req_t *r, uint8_t body[16])
int xrdw_dirlist_req_unpack (const uint8_t body[16], xrdw_dirlist_req_t *r)
int xrdw_query_req_pack (const xrdw_query_req_t *r, uint8_t body[16])
int xrdw_query_req_unpack (const uint8_t body[16], xrdw_query_req_t *r)
int xrdw_locate_req_pack (const xrdw_locate_req_t *r, uint8_t body[16])
int xrdw_locate_req_unpack (const uint8_t body[16], xrdw_locate_req_t *r)
int xrdw_fattr_req_pack (const xrdw_fattr_req_t *r, uint8_t body[16])
int xrdw_fattr_req_unpack (const uint8_t body[16], xrdw_fattr_req_t *r)
Function Documentation
xrdw_dirlist_req_pack()
int xrdw_dirlist_req_pack (const xrdw_dirlist_req_t * r, uint8_t body[16])
Definition at line 67 of file wire_codec_meta.c.
References xrdw_dirlist_req_t::options, XRDW_BODY_LEN, and XRDW_EINVAL.
Referenced by dirlist_once(), and test_dirlist().
xrdw_dirlist_req_unpack()
int xrdw_dirlist_req_unpack (const uint8_t body[16], xrdw_dirlist_req_t * r)
Definition at line 78 of file wire_codec_meta.c.
References xrdw_dirlist_req_t::options, XRDW_EINVAL, and XRDW_OK.
Referenced by brix_handle_dirlist(), and test_dirlist().
xrdw_fattr_req_pack()
int xrdw_fattr_req_pack (const xrdw_fattr_req_t * r, uint8_t body[16])
Definition at line 138 of file wire_codec_meta.c.
References xrdw_fattr_req_t::fhandle, xrdw_fattr_req_t::numattr, xrdw_fattr_req_t::options, xrdw_fattr_req_t::subcode, XRDW_BODY_LEN, XRDW_EINVAL, and XRDW_FHANDLE_LEN.
Referenced by brix_cache_origin_getfattr(), brix_cache_origin_listfattr(), brix_fattr_get(), brix_fattr_list(), fattr_set_or_del(), and origin_fattr_set_or_del().
xrdw_fattr_req_unpack()
int xrdw_fattr_req_unpack (const uint8_t body[16], xrdw_fattr_req_t * r)
Definition at line 152 of file wire_codec_meta.c.
References xrdw_fattr_req_t::fhandle, xrdw_fattr_req_t::numattr, xrdw_fattr_req_t::options, xrdw_fattr_req_t::subcode, XRDW_EINVAL, XRDW_FHANDLE_LEN, and XRDW_OK.
Referenced by brix_handle_fattr().
xrdw_locate_req_pack()
int xrdw_locate_req_pack (const xrdw_locate_req_t * r, uint8_t body[16])
Definition at line 115 of file wire_codec_meta.c.
References xrdw_locate_req_t::options, XRDW_BODY_LEN, XRDW_EINVAL, and xrdw_put_u16().
Referenced by brix_locate(), brix_upstream_send_request(), and test_locate().
xrdw_locate_req_unpack()
int xrdw_locate_req_unpack (const uint8_t body[16], xrdw_locate_req_t * r)
Definition at line 126 of file wire_codec_meta.c.
References xrdw_locate_req_t::options, XRDW_EINVAL, xrdw_get_u16(), and XRDW_OK.
Referenced by brix_handle_locate(), brix_upstream_start(), and test_locate().
xrdw_query_req_pack()
int xrdw_query_req_pack (const xrdw_query_req_t * r, uint8_t body[16])
Definition at line 90 of file wire_codec_meta.c.
References xrdw_query_req_t::fhandle, xrdw_query_req_t::infotype, XRDW_BODY_LEN, XRDW_EINVAL, XRDW_FHANDLE_LEN, and xrdw_put_u16().
Referenced by brix_cache_origin_query_checksum(), brix_query(), brix_query_cksum(), and test_query().
xrdw_query_req_unpack()
int xrdw_query_req_unpack (const uint8_t body[16], xrdw_query_req_t * r)
Definition at line 102 of file wire_codec_meta.c.
References xrdw_query_req_t::fhandle, xrdw_query_req_t::infotype, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_get_u16(), and XRDW_OK.
Referenced by brix_handle_query(), and test_query().
xrdw_stat_req_pack()
int xrdw_stat_req_pack (const xrdw_stat_req_t * r, uint8_t body[16])
Definition at line 15 of file wire_codec_meta.c.
References xrdw_stat_req_t::fhandle, xrdw_stat_req_t::options, xrdw_stat_req_t::wants, XRDW_BODY_LEN, XRDW_EINVAL, XRDW_FHANDLE_LEN, and xrdw_put_u32().
Referenced by brix_statvfs(), stat_opt(), test_guards(), and test_stat().
xrdw_stat_req_unpack()
int xrdw_stat_req_unpack (const uint8_t body[16], xrdw_stat_req_t * r)
Definition at line 28 of file wire_codec_meta.c.
References xrdw_stat_req_t::fhandle, xrdw_stat_req_t::options, xrdw_stat_req_t::wants, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_get_u32(), and XRDW_OK.
Referenced by brix_handle_stat(), test_guards(), and test_stat().
xrdw_statx_req_pack()
int xrdw_statx_req_pack (const xrdw_statx_req_t * r, uint8_t body[16])
Definition at line 42 of file wire_codec_meta.c.
References xrdw_statx_req_t::fhandle, xrdw_statx_req_t::options, XRDW_BODY_LEN, XRDW_EINVAL, and XRDW_FHANDLE_LEN.
Referenced by test_statx().
xrdw_statx_req_unpack()
int xrdw_statx_req_unpack (const uint8_t body[16], xrdw_statx_req_t * r)
Definition at line 54 of file wire_codec_meta.c.
References xrdw_statx_req_t::fhandle, xrdw_statx_req_t::options, XRDW_EINVAL, XRDW_FHANDLE_LEN, and XRDW_OK.
Referenced by test_statx().