nginx-xrootd: src/net/cms/wire.c File Reference
wire.c File Reference
#include "cms_internal.h"
Functions
uint16_t ngx_brix_cms_get16 (const u_char *p)
uint32_t ngx_brix_cms_get32 (const u_char *p)
void ngx_brix_cms_put16 (u_char *p, uint16_t value)
void ngx_brix_cms_put32 (u_char *p, uint32_t value)
u_char * ngx_brix_cms_put_short (u_char *p, uint16_t value)
u_char * ngx_brix_cms_put_int (u_char *p, uint32_t value)
u_char * ngx_brix_cms_put_string (u_char *p, const u_char *data, size_t len)
Function Documentation
ngx_brix_cms_get16()
uint16_t ngx_brix_cms_get16 (const u_char * p)
Definition at line 27 of file wire.c.
Referenced by brix_cms_srv_read(), cms_srv_read_string(), ngx_brix_cms_process_frame(), ngx_brix_cms_read_handler(), and tlv_read_next().
ngx_brix_cms_get32()
uint32_t ngx_brix_cms_get32 (const u_char * p)
Definition at line 34 of file wire.c.
Referenced by brix_cms_srv_read(), ngx_brix_cms_process_frame(), and tlv_read_next().
ngx_brix_cms_put16()
void ngx_brix_cms_put16 (u_char * p, uint16_t value)
Definition at line 44 of file wire.c.
Referenced by brix_cms_send_frame(), ngx_brix_cms_put_short(), ngx_brix_cms_put_string(), and ngx_brix_cms_send_load().
ngx_brix_cms_put32()
void ngx_brix_cms_put32 (u_char * p, uint32_t value)
Definition at line 52 of file wire.c.
Referenced by brix_cms_send_frame(), ngx_brix_cms_put_int(), and ngx_brix_cms_send_error().
ngx_brix_cms_put_int()
u_char * ngx_brix_cms_put_int (u_char * p, uint32_t value)
Definition at line 77 of file wire.c.
References CMS_PT_INT, and ngx_brix_cms_put32().
Referenced by ngx_brix_cms_send_avail(), ngx_brix_cms_send_load(), and ngx_brix_cms_send_login().
ngx_brix_cms_put_short()
u_char * ngx_brix_cms_put_short (u_char * p, uint16_t value)
Definition at line 64 of file wire.c.
References CMS_PT_SHORT, and ngx_brix_cms_put16().
Referenced by ngx_brix_cms_send_login().
ngx_brix_cms_put_string()
u_char * ngx_brix_cms_put_string (u_char * p, const u_char * data, size_t len)
Definition at line 92 of file wire.c.
References ngx_brix_cms_put16(), and ngx_memcpy.
Referenced by ngx_brix_cms_send_login().