nginx-xrootd: src/protocols/root/protocol/codec/wire_codec.h File Reference
wire_codec.h File Reference
#include <stdint.h>
#include <stddef.h>
#include <sys/types.h>
Data Structures
struct xrdw_stat_req_t
struct xrdw_statx_req_t
struct xrdw_dirlist_req_t
struct xrdw_query_req_t
struct xrdw_locate_req_t
struct xrdw_fattr_req_t
struct xrdw_open_req_t
struct xrdw_close_req_t
struct xrdw_read_req_t
struct xrdw_pgread_req_t
struct xrdw_write_req_t
struct xrdw_pgwrite_req_t
struct xrdw_sync_req_t
struct xrdw_truncate_req_t
struct xrdw_writev_req_t
struct xrdw_clone_req_t
struct xrdw_chkpoint_req_t
struct xrdw_mkdir_req_t
struct xrdw_chmod_req_t
struct xrdw_set_req_t
struct xrdw_twopath_req_t
struct xrdw_login_req_t
struct xrdw_auth_req_t
struct xrdw_protocol_req_t
struct xrdw_sessid_req_t
struct xrdw_sigver_req_t
struct xrdw_prepare_req_t
Macros
#define XRDW_OK 0
#define XRDW_EINVAL (-1) /* NULL argument / bad field */
#define XRDW_ETRUNC (-2) /* input shorter than the fixed region */
#define XRDW_BODY_LEN 16
#define XRDW_FHANDLE_LEN 4
Functions
static void xrdw_put_u16 (uint8_t *p, uint16_t v)
static void xrdw_put_u32 (uint8_t *p, uint32_t v)
static uint16_t xrdw_get_u16 (const uint8_t *p)
static uint32_t xrdw_get_u32 (const uint8_t *p)
static void xrdw_put_u64 (uint8_t *p, uint64_t v)
static uint64_t xrdw_get_u64 (const uint8_t *p)
int xrdw_stat_req_pack (const xrdw_stat_req_t *r, uint8_t body[16])
int xrdw_stat_req_unpack (const uint8_t body[16], xrdw_stat_req_t *r)
int xrdw_statx_req_pack (const xrdw_statx_req_t *r, uint8_t body[16])
int xrdw_statx_req_unpack (const uint8_t body[16], xrdw_statx_req_t *r)
int xrdw_dirlist_req_pack (const xrdw_dirlist_req_t *r, uint8_t body[16])
int xrdw_dirlist_req_unpack (const uint8_t body[16], xrdw_dirlist_req_t *r)
int xrdw_query_req_pack (const xrdw_query_req_t *r, uint8_t body[16])
int xrdw_query_req_unpack (const uint8_t body[16], xrdw_query_req_t *r)
int xrdw_locate_req_pack (const xrdw_locate_req_t *r, uint8_t body[16])
int xrdw_locate_req_unpack (const uint8_t body[16], xrdw_locate_req_t *r)
int xrdw_fattr_req_pack (const xrdw_fattr_req_t *r, uint8_t body[16])
int xrdw_fattr_req_unpack (const uint8_t body[16], xrdw_fattr_req_t *r)
int xrdw_open_req_pack (const xrdw_open_req_t *r, uint8_t body[16])
int xrdw_open_req_unpack (const uint8_t body[16], xrdw_open_req_t *r)
int xrdw_close_req_pack (const xrdw_close_req_t *r, uint8_t body[16])
int xrdw_close_req_unpack (const uint8_t body[16], xrdw_close_req_t *r)
int xrdw_read_req_pack (const xrdw_read_req_t *r, uint8_t body[16])
int xrdw_read_req_unpack (const uint8_t body[16], xrdw_read_req_t *r)
int xrdw_pgread_req_pack (const xrdw_pgread_req_t *r, uint8_t body[16])
int xrdw_pgread_req_unpack (const uint8_t body[16], xrdw_pgread_req_t *r)
int xrdw_write_req_pack (const xrdw_write_req_t *r, uint8_t body[16])
int xrdw_write_req_unpack (const uint8_t body[16], xrdw_write_req_t *r)
int xrdw_pgwrite_req_pack (const xrdw_pgwrite_req_t *r, uint8_t body[16])
int xrdw_pgwrite_req_unpack (const uint8_t body[16], xrdw_pgwrite_req_t *r)
int xrdw_sync_req_pack (const xrdw_sync_req_t *r, uint8_t body[16])
int xrdw_sync_req_unpack (const uint8_t body[16], xrdw_sync_req_t *r)
int xrdw_truncate_req_pack (const xrdw_truncate_req_t *r, uint8_t body[16])
int xrdw_truncate_req_unpack (const uint8_t body[16], xrdw_truncate_req_t *r)
int xrdw_writev_req_pack (const xrdw_writev_req_t *r, uint8_t body[16])
int xrdw_writev_req_unpack (const uint8_t body[16], xrdw_writev_req_t *r)
int xrdw_clone_req_pack (const xrdw_clone_req_t *r, uint8_t body[16])
int xrdw_clone_req_unpack (const uint8_t body[16], xrdw_clone_req_t *r)
int xrdw_chkpoint_req_pack (const xrdw_chkpoint_req_t *r, uint8_t body[16])
int xrdw_chkpoint_req_unpack (const uint8_t body[16], xrdw_chkpoint_req_t *r)
int xrdw_mkdir_req_pack (const xrdw_mkdir_req_t *r, uint8_t body[16])
int xrdw_mkdir_req_unpack (const uint8_t body[16], xrdw_mkdir_req_t *r)
int xrdw_chmod_req_pack (const xrdw_chmod_req_t *r, uint8_t body[16])
int xrdw_chmod_req_unpack (const uint8_t body[16], xrdw_chmod_req_t *r)
int xrdw_set_req_pack (const xrdw_set_req_t *r, uint8_t body[16])
int xrdw_set_req_unpack (const uint8_t body[16], xrdw_set_req_t *r)
int xrdw_twopath_req_pack (const xrdw_twopath_req_t *r, uint8_t body[16])
int xrdw_twopath_req_unpack (const uint8_t body[16], xrdw_twopath_req_t *r)
int xrdw_empty_req_pack (uint8_t body[16])
int xrdw_empty_req_unpack (const uint8_t body[16])
int xrdw_login_req_pack (const xrdw_login_req_t *r, uint8_t body[16])
int xrdw_login_req_unpack (const uint8_t body[16], xrdw_login_req_t *r)
int xrdw_auth_req_pack (const xrdw_auth_req_t *r, uint8_t body[16])
int xrdw_auth_req_unpack (const uint8_t body[16], xrdw_auth_req_t *r)
int xrdw_protocol_req_pack (const xrdw_protocol_req_t *r, uint8_t body[16])
int xrdw_protocol_req_unpack (const uint8_t body[16], xrdw_protocol_req_t *r)
int xrdw_sessid_req_pack (const xrdw_sessid_req_t *r, uint8_t body[16])
int xrdw_sessid_req_unpack (const uint8_t body[16], xrdw_sessid_req_t *r)
int xrdw_sigver_req_pack (const xrdw_sigver_req_t *r, uint8_t body[16])
int xrdw_sigver_req_unpack (const uint8_t body[16], xrdw_sigver_req_t *r)
int xrdw_prepare_req_pack (const xrdw_prepare_req_t *r, uint8_t body[16])
int xrdw_prepare_req_unpack (const uint8_t body[16], xrdw_prepare_req_t *r)
Macro Definition Documentation
XRDW_BODY_LEN
#define XRDW_BODY_LEN 16
Definition at line 36 of file wire_codec.h.
XRDW_EINVAL
#define XRDW_EINVAL (-1) /* NULL argument / bad field */
Definition at line 32 of file wire_codec.h.
XRDW_ETRUNC
#define XRDW_ETRUNC (-2) /* input shorter than the fixed region */
Definition at line 33 of file wire_codec.h.
XRDW_FHANDLE_LEN
#define XRDW_FHANDLE_LEN 4
Definition at line 37 of file wire_codec.h.
XRDW_OK
#define XRDW_OK 0
Definition at line 31 of file wire_codec.h.
Function Documentation
xrdw_auth_req_pack()
int xrdw_auth_req_pack (const xrdw_auth_req_t * r, uint8_t body[16])
Definition at line 46 of file wire_codec_session.c.
References xrdw_auth_req_t::credtype, XRDW_BODY_LEN, and XRDW_EINVAL.
Referenced by brix_upstream_send_token_auth(), and send_auth().
xrdw_auth_req_unpack()
int xrdw_auth_req_unpack (const uint8_t body[16], xrdw_auth_req_t * r)
Definition at line 57 of file wire_codec_session.c.
References xrdw_auth_req_t::credtype, XRDW_EINVAL, and XRDW_OK.
xrdw_chkpoint_req_pack()
int xrdw_chkpoint_req_pack (const xrdw_chkpoint_req_t * r, uint8_t body[16])
Definition at line 268 of file wire_codec_file.c.
References xrdw_chkpoint_req_t::fhandle, xrdw_chkpoint_req_t::opcode, XRDW_BODY_LEN, XRDW_EINVAL, and XRDW_FHANDLE_LEN.
Referenced by test_chkpoint().
xrdw_chkpoint_req_unpack()
int xrdw_chkpoint_req_unpack (const uint8_t body[16], xrdw_chkpoint_req_t * r)
Definition at line 280 of file wire_codec_file.c.
References xrdw_chkpoint_req_t::fhandle, xrdw_chkpoint_req_t::opcode, XRDW_EINVAL, XRDW_FHANDLE_LEN, and XRDW_OK.
Referenced by brix_handle_chkpoint(), and test_chkpoint().
xrdw_chmod_req_pack()
int xrdw_chmod_req_pack (const xrdw_chmod_req_t * r, uint8_t body[16])
Definition at line 41 of file wire_codec_ns.c.
References xrdw_chmod_req_t::mode, XRDW_BODY_LEN, XRDW_EINVAL, and xrdw_put_u16().
Referenced by brix_chmod(), and test_chmod().
xrdw_chmod_req_unpack()
int xrdw_chmod_req_unpack (const uint8_t body[16], xrdw_chmod_req_t * r)
Definition at line 52 of file wire_codec_ns.c.
References xrdw_chmod_req_t::mode, XRDW_EINVAL, xrdw_get_u16(), and XRDW_OK.
Referenced by exec_chmod(), and test_chmod().
xrdw_clone_req_pack()
int xrdw_clone_req_pack (const xrdw_clone_req_t * r, uint8_t body[16])
Definition at line 245 of file wire_codec_file.c.
References xrdw_clone_req_t::dst_fhandle, XRDW_BODY_LEN, XRDW_EINVAL, and XRDW_FHANDLE_LEN.
xrdw_clone_req_unpack()
int xrdw_clone_req_unpack (const uint8_t body[16], xrdw_clone_req_t * r)
Definition at line 256 of file wire_codec_file.c.
References xrdw_clone_req_t::dst_fhandle, XRDW_EINVAL, XRDW_FHANDLE_LEN, and XRDW_OK.
Referenced by brix_handle_clone().
xrdw_close_req_pack()
int xrdw_close_req_pack (const xrdw_close_req_t * r, uint8_t body[16])
Definition at line 45 of file wire_codec_file.c.
References xrdw_close_req_t::fhandle, XRDW_BODY_LEN, XRDW_EINVAL, and XRDW_FHANDLE_LEN.
Referenced by brix_file_close(), and brix_mfile_close().
xrdw_close_req_unpack()
int xrdw_close_req_unpack (const uint8_t body[16], xrdw_close_req_t * r)
Definition at line 56 of file wire_codec_file.c.
References xrdw_close_req_t::fhandle, XRDW_EINVAL, XRDW_FHANDLE_LEN, and XRDW_OK.
Referenced by brix_handle_close().
xrdw_dirlist_req_pack()
int xrdw_dirlist_req_pack (const xrdw_dirlist_req_t * r, uint8_t body[16])
Definition at line 67 of file wire_codec_meta.c.
References xrdw_dirlist_req_t::options, XRDW_BODY_LEN, and XRDW_EINVAL.
Referenced by brix_cache_origin_dirlist(), dirlist_once(), and test_dirlist().
xrdw_dirlist_req_unpack()
int xrdw_dirlist_req_unpack (const uint8_t body[16], xrdw_dirlist_req_t * r)
Definition at line 78 of file wire_codec_meta.c.
References xrdw_dirlist_req_t::options, XRDW_EINVAL, and XRDW_OK.
Referenced by brix_dirlist_parse_request(), and test_dirlist().
xrdw_empty_req_pack()
int xrdw_empty_req_pack (uint8_t body[16])
Definition at line 110 of file wire_codec_ns.c.
References XRDW_BODY_LEN, and XRDW_EINVAL.
Referenced by brix_readlink(), brix_rm(), brix_rmdir(), brix_setattr(), file_readv_frames(), test_empty(), and test_guards().
xrdw_empty_req_unpack()
int xrdw_empty_req_unpack (const uint8_t body[16])
Definition at line 120 of file wire_codec_ns.c.
References XRDW_EINVAL, and XRDW_OK.
Referenced by test_empty().
xrdw_fattr_req_pack()
int xrdw_fattr_req_pack (const xrdw_fattr_req_t * r, uint8_t body[16])
Definition at line 138 of file wire_codec_meta.c.
References xrdw_fattr_req_t::fhandle, xrdw_fattr_req_t::numattr, xrdw_fattr_req_t::options, xrdw_fattr_req_t::subcode, XRDW_BODY_LEN, XRDW_EINVAL, and XRDW_FHANDLE_LEN.
Referenced by brix_cache_origin_getfattr(), brix_cache_origin_listfattr(), brix_fattr_get(), brix_fattr_list(), fattr_set_or_del(), and origin_fattr_set_or_del().
xrdw_fattr_req_unpack()
int xrdw_fattr_req_unpack (const uint8_t body[16], xrdw_fattr_req_t * r)
Definition at line 152 of file wire_codec_meta.c.
References xrdw_fattr_req_t::fhandle, xrdw_fattr_req_t::numattr, xrdw_fattr_req_t::options, xrdw_fattr_req_t::subcode, XRDW_EINVAL, XRDW_FHANDLE_LEN, and XRDW_OK.
Referenced by brix_handle_fattr().
xrdw_get_u16()
static uint16_t xrdw_get_u16 (const uint8_t * p) inline static
Definition at line 67 of file wire_codec.h.
Referenced by xrdw_chmod_req_unpack(), xrdw_locate_req_unpack(), xrdw_mkdir_req_unpack(), xrdw_open_req_unpack(), xrdw_prepare_req_unpack(), xrdw_query_req_unpack(), xrdw_sigver_req_unpack(), and xrdw_twopath_req_unpack().
xrdw_get_u32()
static uint32_t xrdw_get_u32 (const uint8_t * p) inline static
Definition at line 72 of file wire_codec.h.
Referenced by xrdw_get_u64(), xrdw_login_req_unpack(), xrdw_pgread_req_unpack(), xrdw_protocol_req_unpack(), xrdw_read_req_unpack(), and xrdw_stat_req_unpack().
xrdw_get_u64()
static uint64_t xrdw_get_u64 (const uint8_t * p) inline static
Definition at line 84 of file wire_codec.h.
References xrdw_get_u32().
Referenced by xrdw_pgread_req_unpack(), xrdw_pgwrite_req_unpack(), xrdw_read_req_unpack(), xrdw_sigver_req_unpack(), xrdw_truncate_req_unpack(), and xrdw_write_req_unpack().
xrdw_locate_req_pack()
int xrdw_locate_req_pack (const xrdw_locate_req_t * r, uint8_t body[16])
Definition at line 115 of file wire_codec_meta.c.
References xrdw_locate_req_t::options, XRDW_BODY_LEN, XRDW_EINVAL, and xrdw_put_u16().
Referenced by brix_locate(), brix_upstream_send_request(), and test_locate().
xrdw_locate_req_unpack()
int xrdw_locate_req_unpack (const uint8_t body[16], xrdw_locate_req_t * r)
Definition at line 126 of file wire_codec_meta.c.
References xrdw_locate_req_t::options, XRDW_EINVAL, xrdw_get_u16(), and XRDW_OK.
Referenced by brix_upstream_start_snapshot_request(), locate_resolve_reqpath(), and test_locate().
xrdw_login_req_pack()
int xrdw_login_req_pack (const xrdw_login_req_t * r, uint8_t body[16])
Definition at line 15 of file wire_codec_session.c.
References xrdw_login_req_t::ability, xrdw_login_req_t::ability2, xrdw_login_req_t::capver, xrdw_login_req_t::pid, xrdw_login_req_t::username, XRDW_BODY_LEN, XRDW_EINVAL, and xrdw_put_u32().
Referenced by brix_proxy_build_bootstrap(), test_login(), and xrd_pack_login_request().
xrdw_login_req_unpack()
int xrdw_login_req_unpack (const uint8_t body[16], xrdw_login_req_t * r)
Definition at line 30 of file wire_codec_session.c.
References xrdw_login_req_t::ability, xrdw_login_req_t::ability2, xrdw_login_req_t::capver, xrdw_login_req_t::pid, xrdw_login_req_t::username, XRDW_EINVAL, xrdw_get_u32(), and XRDW_OK.
Referenced by brix_login_precheck_and_parse(), and test_login().
xrdw_mkdir_req_pack()
int xrdw_mkdir_req_pack (const xrdw_mkdir_req_t * r, uint8_t body[16])
Definition at line 16 of file wire_codec_ns.c.
References xrdw_mkdir_req_t::mode, xrdw_mkdir_req_t::options, XRDW_BODY_LEN, XRDW_EINVAL, and xrdw_put_u16().
Referenced by brix_mkdir(), and test_mkdir().
xrdw_mkdir_req_unpack()
int xrdw_mkdir_req_unpack (const uint8_t body[16], xrdw_mkdir_req_t * r)
Definition at line 28 of file wire_codec_ns.c.
References xrdw_mkdir_req_t::mode, xrdw_mkdir_req_t::options, XRDW_EINVAL, xrdw_get_u16(), and XRDW_OK.
Referenced by brix_handle_mkdir(), and test_mkdir().
xrdw_open_req_pack()
int xrdw_open_req_pack (const xrdw_open_req_t * r, uint8_t body[16])
Definition at line 16 of file wire_codec_file.c.
References xrdw_open_req_t::fhtemplt, xrdw_open_req_t::mode, xrdw_open_req_t::options, xrdw_open_req_t::optiont, XRDW_BODY_LEN, XRDW_EINVAL, XRDW_FHANDLE_LEN, and xrdw_put_u16().
Referenced by brix_cache_origin_open(), brix_cache_origin_open_write(), brix_file_open_opaque(), brix_proxy_lazy_open(), brix_upstream_send_request(), mfile_do_open(), test_open(), and tpc_open_build_request().
xrdw_open_req_unpack()
int xrdw_open_req_unpack (const uint8_t body[16], xrdw_open_req_t * r)
Definition at line 30 of file wire_codec_file.c.
References xrdw_open_req_t::fhtemplt, xrdw_open_req_t::mode, xrdw_open_req_t::options, xrdw_open_req_t::optiont, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_get_u16(), and XRDW_OK.
Referenced by brix_handle_open(), brix_upstream_start_snapshot_request(), and test_open().
xrdw_pgread_req_pack()
int xrdw_pgread_req_pack (const xrdw_pgread_req_t * r, uint8_t body[16])
Definition at line 114 of file wire_codec_file.c.
References xrdw_pgread_req_t::fhandle, xrdw_pgread_req_t::offset, xrdw_pgread_req_t::rlen, XRDW_BODY_LEN, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_put_u32(), and xrdw_put_u64().
Referenced by file_pgread_frames().
xrdw_pgread_req_unpack()
int xrdw_pgread_req_unpack (const uint8_t body[16], xrdw_pgread_req_t * r)
Definition at line 127 of file wire_codec_file.c.
References xrdw_pgread_req_t::fhandle, xrdw_pgread_req_t::offset, xrdw_pgread_req_t::rlen, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_get_u32(), xrdw_get_u64(), and XRDW_OK.
Referenced by brix_pgread_parse_validate().
xrdw_pgwrite_req_pack()
int xrdw_pgwrite_req_pack (const xrdw_pgwrite_req_t * r, uint8_t body[16])
Definition at line 168 of file wire_codec_file.c.
References xrdw_pgwrite_req_t::fhandle, xrdw_pgwrite_req_t::offset, xrdw_pgwrite_req_t::pathid, xrdw_pgwrite_req_t::reqflags, XRDW_BODY_LEN, XRDW_EINVAL, XRDW_FHANDLE_LEN, and xrdw_put_u64().
Referenced by brix_file_pgwrite(), pgwrite_retry_one(), and test_pgwrite().
xrdw_pgwrite_req_unpack()
int xrdw_pgwrite_req_unpack (const uint8_t body[16], xrdw_pgwrite_req_t * r)
Definition at line 182 of file wire_codec_file.c.
References xrdw_pgwrite_req_t::fhandle, xrdw_pgwrite_req_t::offset, xrdw_pgwrite_req_t::pathid, xrdw_pgwrite_req_t::reqflags, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_get_u64(), and XRDW_OK.
Referenced by ckp_xeq_pgwrite(), pgwrite_parse_validate(), and test_pgwrite().
xrdw_prepare_req_pack()
int xrdw_prepare_req_pack (const xrdw_prepare_req_t * r, uint8_t body[16])
Definition at line 149 of file wire_codec_session.c.
References xrdw_prepare_req_t::options, xrdw_prepare_req_t::optionX, xrdw_prepare_req_t::port, xrdw_prepare_req_t::prty, XRDW_BODY_LEN, XRDW_EINVAL, and xrdw_put_u16().
Referenced by brix_prepare(), and test_prepare().
xrdw_prepare_req_unpack()
int xrdw_prepare_req_unpack (const uint8_t body[16], xrdw_prepare_req_t * r)
Definition at line 163 of file wire_codec_session.c.
References xrdw_prepare_req_t::options, xrdw_prepare_req_t::optionX, xrdw_prepare_req_t::port, xrdw_prepare_req_t::prty, XRDW_EINVAL, xrdw_get_u16(), and XRDW_OK.
Referenced by brix_handle_prepare(), and test_prepare().
xrdw_protocol_req_pack()
int xrdw_protocol_req_pack (const xrdw_protocol_req_t * r, uint8_t body[16])
Definition at line 69 of file wire_codec_session.c.
References xrdw_protocol_req_t::clientpv, xrdw_protocol_req_t::expect, xrdw_protocol_req_t::flags, XRDW_BODY_LEN, XRDW_EINVAL, and xrdw_put_u32().
Referenced by brix_proxy_build_bootstrap(), test_protocol(), and xrd_pack_protocol_request().
xrdw_protocol_req_unpack()
int xrdw_protocol_req_unpack (const uint8_t body[16], xrdw_protocol_req_t * r)
Definition at line 82 of file wire_codec_session.c.
References xrdw_protocol_req_t::clientpv, xrdw_protocol_req_t::expect, xrdw_protocol_req_t::flags, XRDW_EINVAL, xrdw_get_u32(), and XRDW_OK.
Referenced by test_protocol().
xrdw_put_u16()
static void xrdw_put_u16 (uint8_t * p, uint16_t v) inline static
Definition at line 53 of file wire_codec.h.
Referenced by xrdw_chmod_req_pack(), xrdw_locate_req_pack(), xrdw_mkdir_req_pack(), xrdw_open_req_pack(), xrdw_prepare_req_pack(), xrdw_query_req_pack(), xrdw_sigver_req_pack(), and xrdw_twopath_req_pack().
xrdw_put_u32()
static void xrdw_put_u32 (uint8_t * p, uint32_t v) inline static
Definition at line 59 of file wire_codec.h.
Referenced by xrdw_login_req_pack(), xrdw_pgread_req_pack(), xrdw_protocol_req_pack(), xrdw_put_u64(), xrdw_read_req_pack(), and xrdw_stat_req_pack().
xrdw_put_u64()
static void xrdw_put_u64 (uint8_t * p, uint64_t v) inline static
Definition at line 78 of file wire_codec.h.
References xrdw_put_u32().
Referenced by xrdw_pgread_req_pack(), xrdw_pgwrite_req_pack(), xrdw_read_req_pack(), xrdw_sigver_req_pack(), xrdw_truncate_req_pack(), and xrdw_write_req_pack().
xrdw_query_req_pack()
int xrdw_query_req_pack (const xrdw_query_req_t * r, uint8_t body[16])
Definition at line 90 of file wire_codec_meta.c.
References xrdw_query_req_t::fhandle, xrdw_query_req_t::infotype, XRDW_BODY_LEN, XRDW_EINVAL, XRDW_FHANDLE_LEN, and xrdw_put_u16().
Referenced by brix_query(), brix_query_cksum(), origin_cksum_send_query(), and test_query().
xrdw_query_req_unpack()
int xrdw_query_req_unpack (const uint8_t body[16], xrdw_query_req_t * r)
Definition at line 102 of file wire_codec_meta.c.
References xrdw_query_req_t::fhandle, xrdw_query_req_t::infotype, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_get_u16(), and XRDW_OK.
Referenced by brix_handle_query(), and test_query().
xrdw_read_req_pack()
int xrdw_read_req_pack (const xrdw_read_req_t * r, uint8_t body[16])
Definition at line 89 of file wire_codec_file.c.
References xrdw_read_req_t::fhandle, xrdw_read_req_t::offset, xrdw_read_req_t::rlen, XRDW_BODY_LEN, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_put_u32(), and xrdw_put_u64().
Referenced by brix_mfile_pread(), file_read_frames(), test_guards(), and test_read().
xrdw_read_req_unpack()
int xrdw_read_req_unpack (const uint8_t body[16], xrdw_read_req_t * r)
Definition at line 102 of file wire_codec_file.c.
References xrdw_read_req_t::fhandle, xrdw_read_req_t::offset, xrdw_read_req_t::rlen, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_get_u32(), xrdw_get_u64(), and XRDW_OK.
Referenced by read_validate_req(), test_guards(), and test_read().
xrdw_sessid_req_pack()
int xrdw_sessid_req_pack (const xrdw_sessid_req_t * r, uint8_t body[16])
Definition at line 96 of file wire_codec_session.c.
References xrdw_sessid_req_t::sessid, XRDW_BODY_LEN, and XRDW_EINVAL.
Referenced by brix_bind(), brix_close(), and test_sessid().
xrdw_sessid_req_unpack()
int xrdw_sessid_req_unpack (const uint8_t body[16], xrdw_sessid_req_t * r)
Definition at line 106 of file wire_codec_session.c.
References xrdw_sessid_req_t::sessid, XRDW_EINVAL, and XRDW_OK.
Referenced by brix_handle_bind(), and test_sessid().
xrdw_set_req_pack()
int xrdw_set_req_pack (const xrdw_set_req_t * r, uint8_t body[16])
Definition at line 64 of file wire_codec_ns.c.
References xrdw_set_req_t::modifier, XRDW_BODY_LEN, and XRDW_EINVAL.
xrdw_set_req_unpack()
int xrdw_set_req_unpack (const uint8_t body[16], xrdw_set_req_t * r)
Definition at line 75 of file wire_codec_ns.c.
References xrdw_set_req_t::modifier, XRDW_EINVAL, and XRDW_OK.
Referenced by brix_handle_set().
xrdw_sigver_req_pack()
int xrdw_sigver_req_pack (const xrdw_sigver_req_t * r, uint8_t body[16])
Definition at line 118 of file wire_codec_session.c.
References xrdw_sigver_req_t::crypto, xrdw_sigver_req_t::expectrid, xrdw_sigver_req_t::flags, xrdw_sigver_req_t::seqno, xrdw_sigver_req_t::version, XRDW_BODY_LEN, XRDW_EINVAL, xrdw_put_u16(), and xrdw_put_u64().
Referenced by brix_sigver_maybe(), and test_sigver().
xrdw_sigver_req_unpack()
int xrdw_sigver_req_unpack (const uint8_t body[16], xrdw_sigver_req_t * r)
Definition at line 133 of file wire_codec_session.c.
References xrdw_sigver_req_t::crypto, xrdw_sigver_req_t::expectrid, xrdw_sigver_req_t::flags, xrdw_sigver_req_t::seqno, xrdw_sigver_req_t::version, XRDW_EINVAL, xrdw_get_u16(), xrdw_get_u64(), and XRDW_OK.
Referenced by brix_handle_sigver(), and test_sigver().
xrdw_stat_req_pack()
int xrdw_stat_req_pack (const xrdw_stat_req_t * r, uint8_t body[16])
Definition at line 15 of file wire_codec_meta.c.
References xrdw_stat_req_t::fhandle, xrdw_stat_req_t::options, xrdw_stat_req_t::wants, XRDW_BODY_LEN, XRDW_EINVAL, XRDW_FHANDLE_LEN, and xrdw_put_u32().
Referenced by brix_statvfs(), stat_opt(), test_guards(), and test_stat().
xrdw_stat_req_unpack()
int xrdw_stat_req_unpack (const uint8_t body[16], xrdw_stat_req_t * r)
Definition at line 28 of file wire_codec_meta.c.
References xrdw_stat_req_t::fhandle, xrdw_stat_req_t::options, xrdw_stat_req_t::wants, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_get_u32(), and XRDW_OK.
Referenced by brix_handle_stat(), test_guards(), and test_stat().
xrdw_statx_req_pack()
int xrdw_statx_req_pack (const xrdw_statx_req_t * r, uint8_t body[16])
Definition at line 42 of file wire_codec_meta.c.
References xrdw_statx_req_t::fhandle, xrdw_statx_req_t::options, XRDW_BODY_LEN, XRDW_EINVAL, and XRDW_FHANDLE_LEN.
Referenced by test_statx().
xrdw_statx_req_unpack()
int xrdw_statx_req_unpack (const uint8_t body[16], xrdw_statx_req_t * r)
Definition at line 54 of file wire_codec_meta.c.
References xrdw_statx_req_t::fhandle, xrdw_statx_req_t::options, XRDW_EINVAL, XRDW_FHANDLE_LEN, and XRDW_OK.
Referenced by test_statx().
xrdw_sync_req_pack()
int xrdw_sync_req_pack (const xrdw_sync_req_t * r, uint8_t body[16])
Definition at line 66 of file wire_codec_file.c.
References xrdw_sync_req_t::fhandle, XRDW_BODY_LEN, XRDW_EINVAL, and XRDW_FHANDLE_LEN.
Referenced by brix_file_sync(), and brix_mfile_sync().
xrdw_sync_req_unpack()
int xrdw_sync_req_unpack (const uint8_t body[16], xrdw_sync_req_t * r)
Definition at line 77 of file wire_codec_file.c.
References xrdw_sync_req_t::fhandle, XRDW_EINVAL, XRDW_FHANDLE_LEN, and XRDW_OK.
Referenced by brix_handle_sync().
xrdw_truncate_req_pack()
int xrdw_truncate_req_pack (const xrdw_truncate_req_t * r, uint8_t body[16])
Definition at line 197 of file wire_codec_file.c.
References xrdw_truncate_req_t::fhandle, xrdw_truncate_req_t::offset, XRDW_BODY_LEN, XRDW_EINVAL, XRDW_FHANDLE_LEN, and xrdw_put_u64().
Referenced by brix_truncate(), and test_truncate().
xrdw_truncate_req_unpack()
int xrdw_truncate_req_unpack (const uint8_t body[16], xrdw_truncate_req_t * r)
Definition at line 209 of file wire_codec_file.c.
References xrdw_truncate_req_t::fhandle, xrdw_truncate_req_t::offset, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_get_u64(), and XRDW_OK.
Referenced by brix_handle_truncate(), ckp_xeq_truncate(), and test_truncate().
xrdw_twopath_req_pack()
int xrdw_twopath_req_pack (const xrdw_twopath_req_t * r, uint8_t body[16])
Definition at line 87 of file wire_codec_ns.c.
References xrdw_twopath_req_t::arg1len, XRDW_BODY_LEN, XRDW_EINVAL, and xrdw_put_u16().
Referenced by brix_cache_origin_rename(), brix_link(), brix_mv(), brix_symlink(), and test_twopath().
xrdw_twopath_req_unpack()
int xrdw_twopath_req_unpack (const uint8_t body[16], xrdw_twopath_req_t * r)
Definition at line 98 of file wire_codec_ns.c.
References xrdw_twopath_req_t::arg1len, XRDW_EINVAL, xrdw_get_u16(), and XRDW_OK.
Referenced by brix_handle_link(), brix_handle_symlink(), mv_parse_paths(), and test_twopath().
xrdw_write_req_pack()
int xrdw_write_req_pack (const xrdw_write_req_t * r, uint8_t body[16])
Definition at line 141 of file wire_codec_file.c.
References xrdw_write_req_t::fhandle, xrdw_write_req_t::offset, xrdw_write_req_t::pathid, XRDW_BODY_LEN, XRDW_EINVAL, XRDW_FHANDLE_LEN, and xrdw_put_u64().
Referenced by brix_file_write(), and brix_mfile_pwrite().
xrdw_write_req_unpack()
int xrdw_write_req_unpack (const uint8_t body[16], xrdw_write_req_t * r)
Definition at line 154 of file wire_codec_file.c.
References xrdw_write_req_t::fhandle, xrdw_write_req_t::offset, xrdw_write_req_t::pathid, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_get_u64(), and XRDW_OK.
Referenced by brix_handle_write(), and ckp_xeq_write().
xrdw_writev_req_pack()
int xrdw_writev_req_pack (const xrdw_writev_req_t * r, uint8_t body[16])
Definition at line 222 of file wire_codec_file.c.
References xrdw_writev_req_t::options, XRDW_BODY_LEN, and XRDW_EINVAL.
Referenced by brix_file_writev().
xrdw_writev_req_unpack()
int xrdw_writev_req_unpack (const uint8_t body[16], xrdw_writev_req_t * r)
Definition at line 233 of file wire_codec_file.c.
References xrdw_writev_req_t::options, XRDW_EINVAL, and XRDW_OK.
Referenced by brix_handle_writev().