nginx-xrootd: src/protocols/root/protocol/codec/wire_codec_ns.c File Reference
wire_codec_ns.c File Reference
#include "wire_codec.h"
#include <string.h>
Functions
int xrdw_mkdir_req_pack (const xrdw_mkdir_req_t *r, uint8_t body[16])
int xrdw_mkdir_req_unpack (const uint8_t body[16], xrdw_mkdir_req_t *r)
int xrdw_chmod_req_pack (const xrdw_chmod_req_t *r, uint8_t body[16])
int xrdw_chmod_req_unpack (const uint8_t body[16], xrdw_chmod_req_t *r)
int xrdw_set_req_pack (const xrdw_set_req_t *r, uint8_t body[16])
int xrdw_set_req_unpack (const uint8_t body[16], xrdw_set_req_t *r)
int xrdw_twopath_req_pack (const xrdw_twopath_req_t *r, uint8_t body[16])
int xrdw_twopath_req_unpack (const uint8_t body[16], xrdw_twopath_req_t *r)
int xrdw_empty_req_pack (uint8_t body[16])
int xrdw_empty_req_unpack (const uint8_t body[16])
Function Documentation
xrdw_chmod_req_pack()
int xrdw_chmod_req_pack (const xrdw_chmod_req_t * r, uint8_t body[16])
Definition at line 41 of file wire_codec_ns.c.
References xrdw_chmod_req_t::mode, XRDW_BODY_LEN, XRDW_EINVAL, and xrdw_put_u16().
Referenced by brix_chmod(), and test_chmod().
xrdw_chmod_req_unpack()
int xrdw_chmod_req_unpack (const uint8_t body[16], xrdw_chmod_req_t * r)
Definition at line 52 of file wire_codec_ns.c.
References xrdw_chmod_req_t::mode, XRDW_EINVAL, xrdw_get_u16(), and XRDW_OK.
Referenced by exec_chmod(), and test_chmod().
xrdw_empty_req_pack()
int xrdw_empty_req_pack (uint8_t body[16])
Definition at line 110 of file wire_codec_ns.c.
References XRDW_BODY_LEN, and XRDW_EINVAL.
Referenced by brix_readlink(), brix_rm(), brix_rmdir(), brix_setattr(), file_readv_frames(), test_empty(), and test_guards().
xrdw_empty_req_unpack()
int xrdw_empty_req_unpack (const uint8_t body[16])
Definition at line 120 of file wire_codec_ns.c.
References XRDW_EINVAL, and XRDW_OK.
Referenced by test_empty().
xrdw_mkdir_req_pack()
int xrdw_mkdir_req_pack (const xrdw_mkdir_req_t * r, uint8_t body[16])
Definition at line 16 of file wire_codec_ns.c.
References xrdw_mkdir_req_t::mode, xrdw_mkdir_req_t::options, XRDW_BODY_LEN, XRDW_EINVAL, and xrdw_put_u16().
Referenced by brix_mkdir(), and test_mkdir().
xrdw_mkdir_req_unpack()
int xrdw_mkdir_req_unpack (const uint8_t body[16], xrdw_mkdir_req_t * r)
Definition at line 28 of file wire_codec_ns.c.
References xrdw_mkdir_req_t::mode, xrdw_mkdir_req_t::options, XRDW_EINVAL, xrdw_get_u16(), and XRDW_OK.
Referenced by brix_handle_mkdir(), and test_mkdir().
xrdw_set_req_pack()
int xrdw_set_req_pack (const xrdw_set_req_t * r, uint8_t body[16])
Definition at line 64 of file wire_codec_ns.c.
References xrdw_set_req_t::modifier, XRDW_BODY_LEN, and XRDW_EINVAL.
xrdw_set_req_unpack()
int xrdw_set_req_unpack (const uint8_t body[16], xrdw_set_req_t * r)
Definition at line 75 of file wire_codec_ns.c.
References xrdw_set_req_t::modifier, XRDW_EINVAL, and XRDW_OK.
Referenced by brix_handle_set().
xrdw_twopath_req_pack()
int xrdw_twopath_req_pack (const xrdw_twopath_req_t * r, uint8_t body[16])
Definition at line 87 of file wire_codec_ns.c.
References xrdw_twopath_req_t::arg1len, XRDW_BODY_LEN, XRDW_EINVAL, and xrdw_put_u16().
Referenced by brix_cache_origin_rename(), brix_link(), brix_mv(), brix_symlink(), and test_twopath().
xrdw_twopath_req_unpack()
int xrdw_twopath_req_unpack (const uint8_t body[16], xrdw_twopath_req_t * r)
Definition at line 98 of file wire_codec_ns.c.
References xrdw_twopath_req_t::arg1len, XRDW_EINVAL, xrdw_get_u16(), and XRDW_OK.
Referenced by brix_handle_link(), brix_handle_symlink(), mv_parse_paths(), and test_twopath().