nginx-xrootd: src/protocols/root/protocol/codec/wire_codec_session.c File Reference
wire_codec_session.c File Reference
#include "wire_codec.h"
#include <string.h>
Functions
int xrdw_login_req_pack (const xrdw_login_req_t *r, uint8_t body[16])
int xrdw_login_req_unpack (const uint8_t body[16], xrdw_login_req_t *r)
int xrdw_auth_req_pack (const xrdw_auth_req_t *r, uint8_t body[16])
int xrdw_auth_req_unpack (const uint8_t body[16], xrdw_auth_req_t *r)
int xrdw_protocol_req_pack (const xrdw_protocol_req_t *r, uint8_t body[16])
int xrdw_protocol_req_unpack (const uint8_t body[16], xrdw_protocol_req_t *r)
int xrdw_sessid_req_pack (const xrdw_sessid_req_t *r, uint8_t body[16])
int xrdw_sessid_req_unpack (const uint8_t body[16], xrdw_sessid_req_t *r)
int xrdw_sigver_req_pack (const xrdw_sigver_req_t *r, uint8_t body[16])
int xrdw_sigver_req_unpack (const uint8_t body[16], xrdw_sigver_req_t *r)
int xrdw_prepare_req_pack (const xrdw_prepare_req_t *r, uint8_t body[16])
int xrdw_prepare_req_unpack (const uint8_t body[16], xrdw_prepare_req_t *r)
Function Documentation
xrdw_auth_req_pack()
int xrdw_auth_req_pack (const xrdw_auth_req_t * r, uint8_t body[16])
Definition at line 46 of file wire_codec_session.c.
References xrdw_auth_req_t::credtype, XRDW_BODY_LEN, and XRDW_EINVAL.
Referenced by brix_upstream_send_token_auth(), and send_auth().
xrdw_auth_req_unpack()
int xrdw_auth_req_unpack (const uint8_t body[16], xrdw_auth_req_t * r)
Definition at line 57 of file wire_codec_session.c.
References xrdw_auth_req_t::credtype, XRDW_EINVAL, and XRDW_OK.
xrdw_login_req_pack()
int xrdw_login_req_pack (const xrdw_login_req_t * r, uint8_t body[16])
Definition at line 15 of file wire_codec_session.c.
References xrdw_login_req_t::ability, xrdw_login_req_t::ability2, xrdw_login_req_t::capver, xrdw_login_req_t::pid, xrdw_login_req_t::username, XRDW_BODY_LEN, XRDW_EINVAL, and xrdw_put_u32().
Referenced by brix_proxy_build_bootstrap(), test_login(), and xrd_pack_login_request().
xrdw_login_req_unpack()
int xrdw_login_req_unpack (const uint8_t body[16], xrdw_login_req_t * r)
Definition at line 30 of file wire_codec_session.c.
References xrdw_login_req_t::ability, xrdw_login_req_t::ability2, xrdw_login_req_t::capver, xrdw_login_req_t::pid, xrdw_login_req_t::username, XRDW_EINVAL, xrdw_get_u32(), and XRDW_OK.
Referenced by brix_login_precheck_and_parse(), and test_login().
xrdw_prepare_req_pack()
int xrdw_prepare_req_pack (const xrdw_prepare_req_t * r, uint8_t body[16])
Definition at line 149 of file wire_codec_session.c.
References xrdw_prepare_req_t::options, xrdw_prepare_req_t::optionX, xrdw_prepare_req_t::port, xrdw_prepare_req_t::prty, XRDW_BODY_LEN, XRDW_EINVAL, and xrdw_put_u16().
Referenced by brix_prepare(), and test_prepare().
xrdw_prepare_req_unpack()
int xrdw_prepare_req_unpack (const uint8_t body[16], xrdw_prepare_req_t * r)
Definition at line 163 of file wire_codec_session.c.
References xrdw_prepare_req_t::options, xrdw_prepare_req_t::optionX, xrdw_prepare_req_t::port, xrdw_prepare_req_t::prty, XRDW_EINVAL, xrdw_get_u16(), and XRDW_OK.
Referenced by brix_handle_prepare(), and test_prepare().
xrdw_protocol_req_pack()
int xrdw_protocol_req_pack (const xrdw_protocol_req_t * r, uint8_t body[16])
Definition at line 69 of file wire_codec_session.c.
References xrdw_protocol_req_t::clientpv, xrdw_protocol_req_t::expect, xrdw_protocol_req_t::flags, XRDW_BODY_LEN, XRDW_EINVAL, and xrdw_put_u32().
Referenced by brix_proxy_build_bootstrap(), test_protocol(), and xrd_pack_protocol_request().
xrdw_protocol_req_unpack()
int xrdw_protocol_req_unpack (const uint8_t body[16], xrdw_protocol_req_t * r)
Definition at line 82 of file wire_codec_session.c.
References xrdw_protocol_req_t::clientpv, xrdw_protocol_req_t::expect, xrdw_protocol_req_t::flags, XRDW_EINVAL, xrdw_get_u32(), and XRDW_OK.
Referenced by test_protocol().
xrdw_sessid_req_pack()
int xrdw_sessid_req_pack (const xrdw_sessid_req_t * r, uint8_t body[16])
Definition at line 96 of file wire_codec_session.c.
References xrdw_sessid_req_t::sessid, XRDW_BODY_LEN, and XRDW_EINVAL.
Referenced by brix_bind(), brix_close(), and test_sessid().
xrdw_sessid_req_unpack()
int xrdw_sessid_req_unpack (const uint8_t body[16], xrdw_sessid_req_t * r)
Definition at line 106 of file wire_codec_session.c.
References xrdw_sessid_req_t::sessid, XRDW_EINVAL, and XRDW_OK.
Referenced by brix_handle_bind(), and test_sessid().
xrdw_sigver_req_pack()
int xrdw_sigver_req_pack (const xrdw_sigver_req_t * r, uint8_t body[16])
Definition at line 118 of file wire_codec_session.c.
References xrdw_sigver_req_t::crypto, xrdw_sigver_req_t::expectrid, xrdw_sigver_req_t::flags, xrdw_sigver_req_t::seqno, xrdw_sigver_req_t::version, XRDW_BODY_LEN, XRDW_EINVAL, xrdw_put_u16(), and xrdw_put_u64().
Referenced by brix_sigver_maybe(), and test_sigver().
xrdw_sigver_req_unpack()
int xrdw_sigver_req_unpack (const uint8_t body[16], xrdw_sigver_req_t * r)
Definition at line 133 of file wire_codec_session.c.
References xrdw_sigver_req_t::crypto, xrdw_sigver_req_t::expectrid, xrdw_sigver_req_t::flags, xrdw_sigver_req_t::seqno, xrdw_sigver_req_t::version, XRDW_EINVAL, xrdw_get_u16(), xrdw_get_u64(), and XRDW_OK.
Referenced by brix_handle_sigver(), and test_sigver().