nginx-xrootd: src/protocols/root/protocol/codec/wire_codec_file.c File Reference
wire_codec_file.c File Reference
#include "wire_codec.h"
#include <string.h>
Functions
int xrdw_open_req_pack (const xrdw_open_req_t *r, uint8_t body[16])
int xrdw_open_req_unpack (const uint8_t body[16], xrdw_open_req_t *r)
int xrdw_close_req_pack (const xrdw_close_req_t *r, uint8_t body[16])
int xrdw_close_req_unpack (const uint8_t body[16], xrdw_close_req_t *r)
int xrdw_sync_req_pack (const xrdw_sync_req_t *r, uint8_t body[16])
int xrdw_sync_req_unpack (const uint8_t body[16], xrdw_sync_req_t *r)
int xrdw_read_req_pack (const xrdw_read_req_t *r, uint8_t body[16])
int xrdw_read_req_unpack (const uint8_t body[16], xrdw_read_req_t *r)
int xrdw_pgread_req_pack (const xrdw_pgread_req_t *r, uint8_t body[16])
int xrdw_pgread_req_unpack (const uint8_t body[16], xrdw_pgread_req_t *r)
int xrdw_write_req_pack (const xrdw_write_req_t *r, uint8_t body[16])
int xrdw_write_req_unpack (const uint8_t body[16], xrdw_write_req_t *r)
int xrdw_pgwrite_req_pack (const xrdw_pgwrite_req_t *r, uint8_t body[16])
int xrdw_pgwrite_req_unpack (const uint8_t body[16], xrdw_pgwrite_req_t *r)
int xrdw_truncate_req_pack (const xrdw_truncate_req_t *r, uint8_t body[16])
int xrdw_truncate_req_unpack (const uint8_t body[16], xrdw_truncate_req_t *r)
int xrdw_writev_req_pack (const xrdw_writev_req_t *r, uint8_t body[16])
int xrdw_writev_req_unpack (const uint8_t body[16], xrdw_writev_req_t *r)
int xrdw_clone_req_pack (const xrdw_clone_req_t *r, uint8_t body[16])
int xrdw_clone_req_unpack (const uint8_t body[16], xrdw_clone_req_t *r)
int xrdw_chkpoint_req_pack (const xrdw_chkpoint_req_t *r, uint8_t body[16])
int xrdw_chkpoint_req_unpack (const uint8_t body[16], xrdw_chkpoint_req_t *r)
Function Documentation
xrdw_chkpoint_req_pack()
int xrdw_chkpoint_req_pack (const xrdw_chkpoint_req_t * r, uint8_t body[16])
Definition at line 268 of file wire_codec_file.c.
References xrdw_chkpoint_req_t::fhandle, xrdw_chkpoint_req_t::opcode, XRDW_BODY_LEN, XRDW_EINVAL, and XRDW_FHANDLE_LEN.
Referenced by test_chkpoint().
xrdw_chkpoint_req_unpack()
int xrdw_chkpoint_req_unpack (const uint8_t body[16], xrdw_chkpoint_req_t * r)
Definition at line 280 of file wire_codec_file.c.
References xrdw_chkpoint_req_t::fhandle, xrdw_chkpoint_req_t::opcode, XRDW_EINVAL, XRDW_FHANDLE_LEN, and XRDW_OK.
Referenced by brix_handle_chkpoint(), and test_chkpoint().
xrdw_clone_req_pack()
int xrdw_clone_req_pack (const xrdw_clone_req_t * r, uint8_t body[16])
Definition at line 245 of file wire_codec_file.c.
References xrdw_clone_req_t::dst_fhandle, XRDW_BODY_LEN, XRDW_EINVAL, and XRDW_FHANDLE_LEN.
xrdw_clone_req_unpack()
int xrdw_clone_req_unpack (const uint8_t body[16], xrdw_clone_req_t * r)
Definition at line 256 of file wire_codec_file.c.
References xrdw_clone_req_t::dst_fhandle, XRDW_EINVAL, XRDW_FHANDLE_LEN, and XRDW_OK.
Referenced by brix_handle_clone().
xrdw_close_req_pack()
int xrdw_close_req_pack (const xrdw_close_req_t * r, uint8_t body[16])
Definition at line 45 of file wire_codec_file.c.
References xrdw_close_req_t::fhandle, XRDW_BODY_LEN, XRDW_EINVAL, and XRDW_FHANDLE_LEN.
Referenced by brix_file_close(), and brix_mfile_close().
xrdw_close_req_unpack()
int xrdw_close_req_unpack (const uint8_t body[16], xrdw_close_req_t * r)
Definition at line 56 of file wire_codec_file.c.
References xrdw_close_req_t::fhandle, XRDW_EINVAL, XRDW_FHANDLE_LEN, and XRDW_OK.
Referenced by brix_handle_close().
xrdw_open_req_pack()
int xrdw_open_req_pack (const xrdw_open_req_t * r, uint8_t body[16])
Definition at line 16 of file wire_codec_file.c.
References xrdw_open_req_t::fhtemplt, xrdw_open_req_t::mode, xrdw_open_req_t::options, xrdw_open_req_t::optiont, XRDW_BODY_LEN, XRDW_EINVAL, XRDW_FHANDLE_LEN, and xrdw_put_u16().
Referenced by brix_cache_origin_open(), brix_cache_origin_open_write(), brix_file_open_opaque(), brix_proxy_lazy_open(), brix_upstream_send_request(), mfile_do_open(), test_open(), and tpc_open_build_request().
xrdw_open_req_unpack()
int xrdw_open_req_unpack (const uint8_t body[16], xrdw_open_req_t * r)
Definition at line 30 of file wire_codec_file.c.
References xrdw_open_req_t::fhtemplt, xrdw_open_req_t::mode, xrdw_open_req_t::options, xrdw_open_req_t::optiont, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_get_u16(), and XRDW_OK.
Referenced by brix_handle_open(), brix_upstream_start_snapshot_request(), and test_open().
xrdw_pgread_req_pack()
int xrdw_pgread_req_pack (const xrdw_pgread_req_t * r, uint8_t body[16])
Definition at line 114 of file wire_codec_file.c.
References xrdw_pgread_req_t::fhandle, xrdw_pgread_req_t::offset, xrdw_pgread_req_t::rlen, XRDW_BODY_LEN, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_put_u32(), and xrdw_put_u64().
Referenced by brix_file_pgread().
xrdw_pgread_req_unpack()
int xrdw_pgread_req_unpack (const uint8_t body[16], xrdw_pgread_req_t * r)
Definition at line 127 of file wire_codec_file.c.
References xrdw_pgread_req_t::fhandle, xrdw_pgread_req_t::offset, xrdw_pgread_req_t::rlen, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_get_u32(), xrdw_get_u64(), and XRDW_OK.
Referenced by brix_pgread_parse_validate().
xrdw_pgwrite_req_pack()
int xrdw_pgwrite_req_pack (const xrdw_pgwrite_req_t * r, uint8_t body[16])
Definition at line 168 of file wire_codec_file.c.
References xrdw_pgwrite_req_t::fhandle, xrdw_pgwrite_req_t::offset, xrdw_pgwrite_req_t::pathid, xrdw_pgwrite_req_t::reqflags, XRDW_BODY_LEN, XRDW_EINVAL, XRDW_FHANDLE_LEN, and xrdw_put_u64().
Referenced by brix_file_pgwrite(), pgwrite_retry_one(), and test_pgwrite().
xrdw_pgwrite_req_unpack()
int xrdw_pgwrite_req_unpack (const uint8_t body[16], xrdw_pgwrite_req_t * r)
Definition at line 182 of file wire_codec_file.c.
References xrdw_pgwrite_req_t::fhandle, xrdw_pgwrite_req_t::offset, xrdw_pgwrite_req_t::pathid, xrdw_pgwrite_req_t::reqflags, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_get_u64(), and XRDW_OK.
Referenced by ckp_xeq_pgwrite(), pgwrite_parse_validate(), and test_pgwrite().
xrdw_read_req_pack()
int xrdw_read_req_pack (const xrdw_read_req_t * r, uint8_t body[16])
Definition at line 89 of file wire_codec_file.c.
References xrdw_read_req_t::fhandle, xrdw_read_req_t::offset, xrdw_read_req_t::rlen, XRDW_BODY_LEN, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_put_u32(), and xrdw_put_u64().
Referenced by brix_file_read(), brix_mfile_pread(), test_guards(), and test_read().
xrdw_read_req_unpack()
int xrdw_read_req_unpack (const uint8_t body[16], xrdw_read_req_t * r)
Definition at line 102 of file wire_codec_file.c.
References xrdw_read_req_t::fhandle, xrdw_read_req_t::offset, xrdw_read_req_t::rlen, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_get_u32(), xrdw_get_u64(), and XRDW_OK.
Referenced by read_validate_req(), test_guards(), and test_read().
xrdw_sync_req_pack()
int xrdw_sync_req_pack (const xrdw_sync_req_t * r, uint8_t body[16])
Definition at line 66 of file wire_codec_file.c.
References xrdw_sync_req_t::fhandle, XRDW_BODY_LEN, XRDW_EINVAL, and XRDW_FHANDLE_LEN.
Referenced by brix_file_sync(), and brix_mfile_sync().
xrdw_sync_req_unpack()
int xrdw_sync_req_unpack (const uint8_t body[16], xrdw_sync_req_t * r)
Definition at line 77 of file wire_codec_file.c.
References xrdw_sync_req_t::fhandle, XRDW_EINVAL, XRDW_FHANDLE_LEN, and XRDW_OK.
Referenced by brix_handle_sync().
xrdw_truncate_req_pack()
int xrdw_truncate_req_pack (const xrdw_truncate_req_t * r, uint8_t body[16])
Definition at line 197 of file wire_codec_file.c.
References xrdw_truncate_req_t::fhandle, xrdw_truncate_req_t::offset, XRDW_BODY_LEN, XRDW_EINVAL, XRDW_FHANDLE_LEN, and xrdw_put_u64().
Referenced by brix_truncate(), and test_truncate().
xrdw_truncate_req_unpack()
int xrdw_truncate_req_unpack (const uint8_t body[16], xrdw_truncate_req_t * r)
Definition at line 209 of file wire_codec_file.c.
References xrdw_truncate_req_t::fhandle, xrdw_truncate_req_t::offset, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_get_u64(), and XRDW_OK.
Referenced by brix_handle_truncate(), ckp_xeq_truncate(), and test_truncate().
xrdw_write_req_pack()
int xrdw_write_req_pack (const xrdw_write_req_t * r, uint8_t body[16])
Definition at line 141 of file wire_codec_file.c.
References xrdw_write_req_t::fhandle, xrdw_write_req_t::offset, xrdw_write_req_t::pathid, XRDW_BODY_LEN, XRDW_EINVAL, XRDW_FHANDLE_LEN, and xrdw_put_u64().
Referenced by brix_file_write(), and brix_mfile_pwrite().
xrdw_write_req_unpack()
int xrdw_write_req_unpack (const uint8_t body[16], xrdw_write_req_t * r)
Definition at line 154 of file wire_codec_file.c.
References xrdw_write_req_t::fhandle, xrdw_write_req_t::offset, xrdw_write_req_t::pathid, XRDW_EINVAL, XRDW_FHANDLE_LEN, xrdw_get_u64(), and XRDW_OK.
Referenced by brix_handle_write(), and ckp_xeq_write().
xrdw_writev_req_pack()
int xrdw_writev_req_pack (const xrdw_writev_req_t * r, uint8_t body[16])
Definition at line 222 of file wire_codec_file.c.
References xrdw_writev_req_t::options, XRDW_BODY_LEN, and XRDW_EINVAL.
Referenced by brix_file_writev().
xrdw_writev_req_unpack()
int xrdw_writev_req_unpack (const uint8_t body[16], xrdw_writev_req_t * r)
Definition at line 233 of file wire_codec_file.c.
References xrdw_writev_req_t::options, XRDW_EINVAL, and XRDW_OK.
Referenced by brix_handle_writev().