nginx-xrootd: src/auth/token/worker_cache.c File Reference
worker_cache.c File Reference
#include "worker_cache.h"
#include "core/compat/crypto.h"
#include <time.h>
Data Structures
struct brix_token_l1_slot_t
struct brix_token_l1_t
Macros
#define BRIX_TOKEN_L1_MAX_TTL_SECS (5 * 60)
Functions
brix_token_l1_t * brix_token_l1_create (ngx_pool_t *pool, ngx_uint_t slots)
static int brix_token_l1_locate (brix_token_l1_t *cache, const char *token, size_t token_len, u_char fp[32], ngx_uint_t *idx)
int brix_token_l1_lookup (brix_token_l1_t *cache, const char *token, size_t token_len, brix_token_claims_t *claims)
void brix_token_l1_store (brix_token_l1_t *cache, const char *token, size_t token_len, const brix_token_claims_t *claims)
Macro Definition Documentation
BRIX_TOKEN_L1_MAX_TTL_SECS
#define BRIX_TOKEN_L1_MAX_TTL_SECS (5 * 60)
Definition at line 21 of file worker_cache.c.
Function Documentation
brix_token_l1_create()
brix_token_l1_t * brix_token_l1_create (ngx_pool_t * pool, ngx_uint_t slots)
Definition at line 35 of file worker_cache.c.
Referenced by brix_handle_token_auth(), and webdav_verify_bearer_token().
brix_token_l1_locate()
static int brix_token_l1_locate (brix_token_l1_t * cache, const char * token, size_t token_len, u_char fp[32], ngx_uint_t * idx) static
Definition at line 62 of file worker_cache.c.
References brix_sha256().
Referenced by brix_token_l1_lookup(), and brix_token_l1_store().
brix_token_l1_lookup()
int brix_token_l1_lookup (brix_token_l1_t * cache, const char * token, size_t token_len, brix_token_claims_t * claims)
Definition at line 77 of file worker_cache.c.
References brix_token_l1_locate(), brix_token_l1_slot_t::claims, brix_token_l1_slot_t::expire_at, and brix_token_l1_slot_t::fp.
Referenced by brix_handle_token_auth(), and webdav_verify_bearer_token().
brix_token_l1_store()
void brix_token_l1_store (brix_token_l1_t * cache, const char * token, size_t token_len, const brix_token_claims_t * claims)
Definition at line 106 of file worker_cache.c.
References brix_token_l1_locate(), BRIX_TOKEN_L1_MAX_TTL_SECS, brix_token_l1_slot_t::claims, brix_token_claims_t::exp, brix_token_l1_slot_t::expire_at, and brix_token_l1_slot_t::fp.
Referenced by brix_handle_token_auth(), and webdav_verify_bearer_token().