nginx-xrootd: src/observability/metrics/writer.c File Reference
writer.c File Reference
#include "metrics_internal.h"
#include "metrics_macros.h"
#include "core/compat/fs_usage.h"
#include "core/shm/kv.h"
#include "fs/vfs/vfs_backend_registry.h"
Functions
static ngx_int_t mw_alloc_chain_buffer (ngx_pool_t *pool, ngx_chain_t **chain_out)
static void mw_select_tail_buffer (metrics_writer_t *mw)
static ngx_int_t mw_append_buffer (metrics_writer_t *mw)
ngx_int_t mw_init (metrics_writer_t *mw, ngx_pool_t *pool)
ngx_int_t mw_printf (metrics_writer_t *mw, const char *fmt,...)
void mw_emit_labeled (metrics_writer_t *mw, const char *name, const char *help, const char *label_key, const char *const *names, ngx_uint_t n, ngx_atomic_t *counters)
void mw_emit_scalar (metrics_writer_t *mw, const char *name, const char *help, ngx_atomic_t *counter)
void brix_kv_metrics_emit (metrics_writer_t *mw)
static void brix_storage_backend_info_emit (metrics_writer_t *mw, ngx_uint_t n)
static int brix_storage_backend_is_local (const char *backend)
static void brix_storage_capacity_emit (metrics_writer_t *mw, ngx_uint_t n)
static void brix_storage_io_bytes_emit (metrics_writer_t *mw)
void brix_storage_backend_metrics_emit (metrics_writer_t *mw)
void mw_finish (metrics_writer_t *mw)
Variables
const char * brix_http_status_names [6]
const char * brix_http_range_result_names [3]
Function Documentation
brix_kv_metrics_emit()
void brix_kv_metrics_emit (metrics_writer_t * mw)
Definition at line 172 of file writer.c.
References brix_kv_stats(), brix_kv_zone_count(), brix_kv_zone_get(), mw_printf(), and s.
Referenced by ngx_http_brix_metrics_handler().
brix_storage_backend_info_emit()
static void brix_storage_backend_info_emit (metrics_writer_t * mw, ngx_uint_t n) static
Definition at line 240 of file writer.c.
References brix_vfs_backend_info_t::backend, brix_vfs_backend_export_info(), brix_vfs_backend_info_t::has_proxy, brix_vfs_backend_info_t::has_token, brix_vfs_backend_info_t::host, mw_printf(), brix_vfs_backend_info_t::port, brix_vfs_backend_info_t::root_canon, brix_vfs_backend_info_t::staging, and brix_vfs_backend_info_t::tls.
Referenced by brix_storage_backend_metrics_emit().
brix_storage_backend_is_local()
static int brix_storage_backend_is_local (const char * backend) static
Definition at line 276 of file writer.c.
Referenced by brix_storage_capacity_emit().
brix_storage_backend_metrics_emit()
void brix_storage_backend_metrics_emit (metrics_writer_t * mw)
Definition at line 370 of file writer.c.
References brix_storage_backend_info_emit(), brix_storage_capacity_emit(), brix_storage_io_bytes_emit(), and brix_vfs_backend_export_count().
Referenced by ngx_http_brix_metrics_handler().
brix_storage_capacity_emit()
static void brix_storage_capacity_emit (metrics_writer_t * mw, ngx_uint_t n) static
Definition at line 287 of file writer.c.
References brix_fs_usage_t::available_bytes, brix_vfs_backend_info_t::backend, brix_fs_usage_stat(), brix_storage_backend_is_local(), brix_vfs_backend_export_info(), mw_printf(), brix_fs_usage_t::occupancy_bytes, brix_fs_usage_t::occupancy_ppm, brix_vfs_backend_info_t::root_canon, and brix_fs_usage_t::total_bytes.
Referenced by brix_storage_backend_metrics_emit().
brix_storage_io_bytes_emit()
static void brix_storage_io_bytes_emit (metrics_writer_t * mw) static
Definition at line 333 of file writer.c.
References BRIX_FS_ID_COUNT, brix_fs_id_name(), brix_metrics_shared(), ngx_brix_unified_metrics_t::io_bytes_read_backend, ngx_brix_unified_metrics_t::io_bytes_written_backend, mw_printf(), and ngx_brix_metrics_t::unified.
Referenced by brix_storage_backend_metrics_emit().
mw_alloc_chain_buffer()
static ngx_int_t mw_alloc_chain_buffer (ngx_pool_t * pool, ngx_chain_t ** chain_out) static
Definition at line 31 of file writer.c.
References METRICS_BUF_SIZE.
Referenced by mw_append_buffer(), and mw_init().
mw_append_buffer()
static ngx_int_t mw_append_buffer (metrics_writer_t * mw) static
Definition at line 68 of file writer.c.
References mw_alloc_chain_buffer(), mw_select_tail_buffer(), metrics_writer_t::pool, metrics_writer_t::pos, and metrics_writer_t::tail.
Referenced by mw_printf().
mw_emit_labeled()
void mw_emit_labeled (metrics_writer_t * mw, const char * name, const char * help, const char * label_key, const char *const * names, ngx_uint_t n, ngx_atomic_t * counters)
Definition at line 143 of file writer.c.
References mw_printf(), and name.
Referenced by brix_export_cvmfs_metrics(), brix_export_frm_metrics(), brix_export_s3_metrics(), and brix_export_webdav_metrics().
mw_emit_scalar()
void mw_emit_scalar (metrics_writer_t * mw, const char * name, const char * help, ngx_atomic_t * counter)
Definition at line 157 of file writer.c.
References mw_printf(), and name.
Referenced by brix_export_cvmfs_metrics(), brix_export_frm_metrics(), brix_export_pmark_metrics(), brix_export_resilience_metrics(), brix_export_s3_metrics(), and brix_export_webdav_metrics().
mw_finish()
void mw_finish (metrics_writer_t * mw)
Definition at line 383 of file writer.c.
References metrics_writer_t::pos, and metrics_writer_t::tail.
Referenced by ngx_http_brix_metrics_handler().
mw_init()
ngx_int_t mw_init (metrics_writer_t * mw, ngx_pool_t * pool)
Definition at line 86 of file writer.c.
References metrics_writer_t::head, mw_alloc_chain_buffer(), mw_select_tail_buffer(), metrics_writer_t::pool, metrics_writer_t::tail, and metrics_writer_t::total.
Referenced by ngx_http_brix_metrics_handler().
mw_printf()
ngx_int_t mw_printf (metrics_writer_t * mw, const char * fmt, ...)
Definition at line 105 of file writer.c.
References metrics_writer_t::last, METRICS_BUF_SIZE, mw_append_buffer(), metrics_writer_t::pos, and metrics_writer_t::total.
Referenced by brix_export_cluster_metrics(), brix_export_cvmfs_metrics(), brix_export_frm_metrics(), brix_export_ratelimit_metrics(), brix_export_s3_metrics(), brix_export_stream_tracking_metrics(), brix_export_webdav_metrics(), brix_kv_metrics_emit(), brix_storage_backend_info_emit(), brix_storage_capacity_emit(), brix_storage_io_bytes_emit(), cvmfs_export_upstreams(), metrics_emit_config_generation(), metrics_emit_mirror(), metrics_emit_registry_health(), metrics_emit_request_ops(), metrics_emit_srv_family(), mw_emit_labeled(), mw_emit_scalar(), ngx_http_brix_metrics_handler(), stream_cache_emit_cache_bytes(), stream_cache_emit_dirty_reaped(), stream_cache_emit_eviction_counter(), stream_cache_emit_eviction_threshold(), stream_cache_emit_occupancy_ratio(), stream_cache_emit_wt_flushes(), stream_cache_emit_wt_single(), unified_emit_auth(), unified_emit_cache_watermark(), unified_emit_io_bytes(), unified_emit_io_latency(), unified_emit_io_latency_series(), unified_emit_io_ops(), unified_emit_proto_counter(), unified_emit_tpc(), and unified_emit_wt_stage().
mw_select_tail_buffer()
static void mw_select_tail_buffer (metrics_writer_t * mw) static
Definition at line 58 of file writer.c.
References metrics_writer_t::last, METRICS_BUF_SIZE, metrics_writer_t::pos, and metrics_writer_t::tail.
Referenced by mw_append_buffer(), and mw_init().
Variable Documentation
brix_http_range_result_names
const char* brix_http_range_result_names[3]
Initial value:
= {
    "full", "partial", "unsatisfied",
}
Definition at line 15 of file writer.c.
Referenced by brix_export_s3_metrics(), and brix_export_webdav_metrics().
brix_http_status_names
const char* brix_http_status_names[6]
Initial value:
= {
    "1xx", "2xx", "3xx", "4xx", "5xx", "other",
}
Definition at line 11 of file writer.c.
Referenced by brix_export_s3_metrics(), and brix_export_webdav_metrics().