nginx-xrootd: src/protocols/root/write/write_compress.c File Reference
write_compress.c File Reference
#include "write.h"
#include "core/ngx_brix_module.h"
#include "core/compat/codec_core.h"
#include "core/http/http_body.h"
#include "protocols/root/response/response.h"
#include <errno.h>
#include <unistd.h>
#include <string.h>
Macros
#define BRIX_WCMP_WINDOW (1u << 20) /* 1 MiB */
#define BRIX_WCMP_OUT_CAP (256ULL * 1024 * 1024) /* 256 MiB */
Functions
static int brix_wcmp_flush_window (int fd, off_t *cur, u_char *win, size_t out_pos, size_t *produced, int *saved_errno)
static void brix_wcmp_decompress_stream (brix_codec_stream_t *s, brix_ctx_t *ctx, size_t wlen, u_char *win, int fd, int64_t offset, size_t *produced, int *io_err, int *data_err, int *saved_errno)
ngx_int_t brix_write_compressed (brix_ctx_t *ctx, ngx_connection_t *c, int idx, int64_t offset, size_t wlen)
Macro Definition Documentation
BRIX_WCMP_OUT_CAP
#define BRIX_WCMP_OUT_CAP (256ULL * 1024 * 1024) /* 256 MiB */
Definition at line 44 of file write_compress.c.
BRIX_WCMP_WINDOW
#define BRIX_WCMP_WINDOW (1u << 20) /* 1 MiB */
Definition at line 41 of file write_compress.c.
Function Documentation
brix_wcmp_decompress_stream()
static void brix_wcmp_decompress_stream (brix_codec_stream_t * s, brix_ctx_t * ctx, size_t wlen, u_char * win, int fd, int64_t offset, size_t * produced, int * io_err, int * data_err, int * saved_errno) static
Definition at line 106 of file write_compress.c.
References BRIX_CODEC_END, BRIX_CODEC_OK, brix_codec_step(), brix_wcmp_flush_window(), BRIX_WCMP_WINDOW, brix_ctx_recv_t::payload, brix_ctx_t::recv, and s.
Referenced by brix_write_compressed().
brix_wcmp_flush_window()
static int brix_wcmp_flush_window (int fd, off_t * cur, u_char * win, size_t out_pos, size_t * produced, int * saved_errno) static
Definition at line 66 of file write_compress.c.
References brix_vfs_io_execute(), brix_vfs_job_write_init(), brix_vfs_job_t::io_errno, and brix_vfs_job_t::nio.
Referenced by brix_wcmp_decompress_stream().
brix_write_compressed()
ngx_int_t brix_write_compressed (brix_ctx_t * ctx, ngx_connection_t * c, int idx, int64_t offset, size_t wlen)
Definition at line 143 of file write_compress.c.
References brix_codec_close(), BRIX_CODEC_DIR_DECOMPRESS, brix_codec_open(), BRIX_GET_SCRATCH, brix_log_access(), BRIX_OP_OK, BRIX_OP_WRITE, BRIX_RETURN_ERR, brix_rl_charge_ctx(), brix_send_ok(), brix_transfer_slot_count_op(), brix_transfer_slot_update(), brix_wcmp_decompress_stream(), BRIX_WCMP_OUT_CAP, BRIX_WCMP_WINDOW, brix_ctx_totals_t::bytes_written, brix_file_t::bytes_written, c, brix_file_t::dashboard_slot, brix_file_t::fd, brix_ctx_t::files, kXR_IOError, brix_codec_guard_t::max_ratio, ngx_brix_dashboard_shm_zone, ngx_stream_brix_module, brix_codec_guard_t::out_cap, brix_file_t::path, s, brix_ctx_t::totals, and brix_file_t::write_codec.
Referenced by brix_write_route_special().