nginx-xrootd: src/fs/cache/writethrough_metrics.h File Reference
writethrough_metrics.h File Reference
Functions
static void brix_wt_metric_dec_if_positive (ngx_atomic_t *counter)
static void brix_wt_mark_dirty (brix_ctx_t *ctx, int idx, off_t dirty_offset, size_t bytes_written)
static void brix_wt_mark_clean (brix_ctx_t *ctx, int idx)
static void brix_wt_metric_pending_inc (ngx_brix_srv_metrics_t *metrics)
static void brix_wt_metric_pending_dec (ngx_brix_srv_metrics_t *metrics)
static void brix_wt_metric_flush_success (ngx_brix_srv_metrics_t *metrics, size_t bytes)
static void brix_wt_metric_flush_error (ngx_brix_srv_metrics_t *metrics)
Function Documentation
brix_wt_mark_clean()
static void brix_wt_mark_clean (brix_ctx_t * ctx, int idx) inline static
Definition at line 66 of file writethrough_metrics.h.
References BRIX_MAX_FILES, brix_wt_metric_dec_if_positive(), brix_ctx_t::files, brix_ctx_t::metrics, brix_file_t::wt_bytes_written, ngx_brix_srv_metrics_t::wt_dirty_handles, and brix_file_t::wt_dirty_offset.
Referenced by brix_free_fhandle().
brix_wt_mark_dirty()
static void brix_wt_mark_dirty (brix_ctx_t * ctx, int idx, off_t dirty_offset, size_t bytes_written) inline static
Definition at line 39 of file writethrough_metrics.h.
References BRIX_MAX_FILES, BRIX_SRV_METRIC_INC, brix_ctx_t::files, brix_file_t::wt_bytes_written, brix_file_t::wt_dirty_offset, and brix_file_t::wt_enabled.
Referenced by brix_handle_pgwrite(), brix_handle_truncate(), brix_handle_write(), brix_handle_writev(), brix_write_aio_done(), and brix_writev_write_aio_done().
brix_wt_metric_dec_if_positive()
static void brix_wt_metric_dec_if_positive (ngx_atomic_t * counter) inline static
Definition at line 26 of file writethrough_metrics.h.
Referenced by brix_wt_mark_clean(), and brix_wt_metric_pending_dec().
brix_wt_metric_flush_error()
static void brix_wt_metric_flush_error (ngx_brix_srv_metrics_t * metrics) inline static
Definition at line 115 of file writethrough_metrics.h.
References BRIX_ATOMIC_INC, and ngx_brix_srv_metrics_t::wt_flush_error_total.
brix_wt_metric_flush_success()
static void brix_wt_metric_flush_success (ngx_brix_srv_metrics_t * metrics, size_t bytes) inline static
Definition at line 104 of file writethrough_metrics.h.
References BRIX_ATOMIC_ADD, BRIX_ATOMIC_INC, ngx_brix_srv_metrics_t::wt_flush_bytes_total, and ngx_brix_srv_metrics_t::wt_flush_success_total.
brix_wt_metric_pending_dec()
static void brix_wt_metric_pending_dec (ngx_brix_srv_metrics_t * metrics) inline static
Definition at line 94 of file writethrough_metrics.h.
References brix_wt_metric_dec_if_positive(), and ngx_brix_srv_metrics_t::wt_flush_pending.
brix_wt_metric_pending_inc()
static void brix_wt_metric_pending_inc (ngx_brix_srv_metrics_t * metrics) inline static
Definition at line 85 of file writethrough_metrics.h.
References BRIX_ATOMIC_INC, and ngx_brix_srv_metrics_t::wt_flush_pending.