nginx-xrootd: src/fs/cache/writethrough_decision.h File Reference
writethrough_decision.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <regex.h>
#include "core/types/file.h"
#include "protocols/root/protocol/flags.h"
Data Structures
struct brix_wt_prefix_entry_t
struct brix_wt_decision_cfg_t
Macros
#define BRIX_WT_DEFAULT_DECISION_FN brix_wt_default_decide
Typedefs
typedef brix_wt_decision_t(* brix_wt_decision_fn) (const char *path, uint16_t options, void *user_data)
Enumerations
enum brix_wt_decision_t { BRIX_WT_DECISION_DENY = 0 , BRIX_WT_DECISION_ALLOW_SYNC , BRIX_WT_DECISION_ALLOW_ASYNC }
Functions
brix_wt_decision_t brix_wt_default_decide (const char *path, uint16_t options, void *user_data)
ngx_int_t brix_wt_config_init_prefixes (ngx_conf_t *cf, ngx_array_t *prefix_list, ngx_array_t **out_array, const char *directive_name)
Macro Definition Documentation
BRIX_WT_DEFAULT_DECISION_FN
#define BRIX_WT_DEFAULT_DECISION_FN brix_wt_default_decide
Definition at line 111 of file writethrough_decision.h.
Typedef Documentation
brix_wt_decision_fn
typedef brix_wt_decision_t(* brix_wt_decision_fn) (const char *path, uint16_t options, void *user_data)
Definition at line 59 of file writethrough_decision.h.
Enumeration Type Documentation
brix_wt_decision_t
enum brix_wt_decision_t
Enumerator
BRIX_WT_DECISION_DENY
BRIX_WT_DECISION_ALLOW_SYNC
BRIX_WT_DECISION_ALLOW_ASYNC
Definition at line 40 of file writethrough_decision.h.
Function Documentation
brix_wt_config_init_prefixes()
ngx_int_t brix_wt_config_init_prefixes (ngx_conf_t * cf, ngx_array_t * prefix_list, ngx_array_t ** out_array, const char * directive_name)
Definition at line 58 of file noop.c.
References brix_wt_prefix_entry_t::prefix.
brix_wt_default_decide()
brix_wt_decision_t brix_wt_default_decide (const char * path, uint16_t options, void * user_data)
Definition at line 48 of file noop.c.
References brix_cache_admit_cfg_t::allow_prefixes, brix_wt_decision_cfg_t::allow_prefixes, brix_cache_admit(), BRIX_CACHE_DECLINE, BRIX_WT_DECISION_ALLOW_ASYNC, BRIX_WT_DECISION_DENY, brix_cache_admit_cfg_t::deny_prefixes, brix_wt_decision_cfg_t::deny_prefixes, brix_cache_admit_cfg_t::include_regex, brix_wt_decision_cfg_t::include_regex, brix_wt_decision_cfg_t::include_regex_set, kXR_new, brix_wt_decision_cfg_t::max_write_through_bytes, brix_cache_admit_cfg_t::size_limit, and stat().
Referenced by brix_merge_srv_proxy_net().