nginx-xrootd: src/protocols/root/write/writev_aio.c File Reference
writev_aio.c File Reference
#include "core/ngx_brix_module.h"
#include "fs/cache/writethrough_metrics.h"
#include "wrts_journal.h"
#include "writev_internal.h"
Functions
ngx_int_t writev_try_aio (const writev_run_t *run, int do_sync, ngx_flag_t *posted)
Function Documentation
writev_try_aio()
ngx_int_t writev_try_aio (const writev_run_t * run, int do_sync, ngx_flag_t * posted)
Definition at line 41 of file writev_aio.c.
References brix_aio_post_task(), brix_writev_write_aio_done(), brix_writev_write_aio_thread(), brix_wrts_is_replay(), brix_writev_aio_t::bytes_total, c, brix_writev_aio_t::c, writev_run_t::c, brix_writev_aio_t::ctx, writev_run_t::ctx, brix_ctx_recv_t::cur_streamid, brix_vfs_writev_seg_t::data, writev_run_t::data_ptr, brix_writev_aio_t::do_sync, brix_file_t::fd, brix_vfs_writev_seg_t::fd, write_list::fhandle, brix_ctx_t::files, brix_vfs_writev_seg_t::handle_idx, brix_writev_aio_t::io_error, brix_writev_aio_t::n_segs, writev_run_t::n_segs, ngx_stream_brix_module, brix_vfs_writev_seg_t::obj, brix_vfs_writev_seg_t::offset, write_list::offset, brix_ctx_recv_t::payload, brix_writev_aio_t::payload_buf, brix_ctx_recv_t::payload_buf, brix_ctx_recv_t::payload_buf_size, brix_ctx_t::recv, brix_file_t::sd_obj, brix_writev_aio_t::segs, brix_writev_aio_t::streamid, writev_run_t::wl, brix_vfs_writev_seg_t::wlen, write_list::wlen, and brix_file_t::wrts_enabled.
Referenced by brix_handle_writev().