nginx-xrootd: src/protocols/root/write/writev.c File Reference
writev.c File Reference
#include "core/ngx_brix_module.h"
#include "fs/cache/writethrough_metrics.h"
#include "wrts_journal.h"
Functions
ngx_int_t brix_writev_body_extra (const u_char *desc, uint32_t dlen, uint32_t *extra)
ngx_int_t brix_handle_writev (brix_ctx_t *ctx, ngx_connection_t *c)
Function Documentation
brix_handle_writev()
ngx_int_t brix_handle_writev (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 68 of file writev.c.
References ngx_stream_brix_srv_conf_t::access_log_fd, brix_aio_post_task(), brix_log_access(), BRIX_MAX_FILES, BRIX_MAX_WRITE_PAYLOAD, BRIX_OP_ERR, BRIX_OP_OK, BRIX_OP_WRITEV, BRIX_RETURN_ERR, brix_send_error(), brix_send_ok(), brix_vfs_io_execute(), brix_vfs_job_set_obj(), brix_vfs_job_sync_init(), brix_vfs_job_write_init(), BRIX_WRITEV_MAXSEGS, BRIX_WRITEV_SEGSIZE, brix_writev_write_aio_done(), brix_writev_write_aio_thread(), brix_wrts_is_replay(), brix_wrts_record(), brix_wt_mark_dirty(), brix_writev_aio_t::bytes_total, brix_ctx_totals_t::bytes_written, brix_file_t::bytes_written, brix_writev_aio_t::c, c, ngx_stream_brix_srv_conf_t::common, brix_writev_aio_t::ctx, brix_ctx_recv_t::cur_body_extra, brix_ctx_recv_t::cur_dlen, brix_ctx_recv_t::cur_streamid, brix_vfs_writev_seg_t::data, brix_writev_aio_t::do_sync, brix_file_t::fd, brix_vfs_writev_seg_t::fd, write_list::fhandle, brix_ctx_t::files, brix_vfs_writev_seg_t::handle_idx, brix_ctx_recv_t::hdr_buf, brix_vfs_job_t::io_errno, brix_writev_aio_t::io_error, kXR_ArgInvalid, kXR_ArgTooLong, kXR_FileNotOpen, kXR_IOError, kXR_NoMemory, kXR_NotAuthorized, kXR_wv_doSync, brix_writev_aio_t::n_segs, ngx_stream_brix_module, brix_vfs_job_t::nio, brix_vfs_writev_seg_t::obj, brix_vfs_writev_seg_t::offset, write_list::offset, xrdw_writev_req_t::options, brix_file_t::path, brix_ctx_recv_t::payload, brix_writev_aio_t::payload_buf, brix_ctx_recv_t::payload_buf, brix_ctx_recv_t::payload_buf_size, brix_ctx_t::recv, brix_file_t::sd_obj, brix_writev_aio_t::segs, brix_writev_aio_t::streamid, ngx_http_brix_shared_conf_t::thread_pool, brix_ctx_t::totals, brix_vfs_writev_seg_t::wlen, write_list::wlen, brix_file_t::writable, brix_file_t::wrts_enabled, brix_file_t::wt_enabled, and xrdw_writev_req_unpack().
Referenced by brix_dispatch_write_opcode().
brix_writev_body_extra()
ngx_int_t brix_writev_body_extra (const u_char * desc, uint32_t dlen, uint32_t * extra)
Definition at line 21 of file writev.c.
References BRIX_MAX_WRITE_PAYLOAD, BRIX_WRITEV_MAXSEGS, BRIX_WRITEV_SEGSIZE, and write_list::wlen.
Referenced by brix_ckpxeq_body_extra(), and ngx_stream_brix_recv().