nginx-xrootd: src/protocols/root/write/write_staged.c File Reference
write_staged.c File Reference
#include "core/ngx_brix_module.h"
#include "write.h"
#include "fs/vfs/vfs.h"
Functions
ngx_int_t brix_staged_append (brix_ctx_t *ctx, ngx_connection_t *c, int idx, int64_t offset, const u_char *buf, size_t len, ngx_int_t *rc)
ngx_int_t brix_write_staged_buf (brix_ctx_t *ctx, ngx_connection_t *c, int idx, int64_t offset, const u_char *buf, size_t len)
ngx_int_t brix_write_staged (brix_ctx_t *ctx, ngx_connection_t *c, int idx, int64_t offset, size_t wlen)
ngx_int_t brix_staged_commit_handle (brix_ctx_t *ctx, int idx, int *err_out)
Function Documentation
brix_staged_append()
ngx_int_t brix_staged_append (brix_ctx_t * ctx, ngx_connection_t * c, int idx, int64_t offset, const u_char * buf, size_t len, ngx_int_t * rc)
Definition at line 46 of file write_staged.c.
References brix_log_access(), BRIX_OP_ERR, BRIX_OP_WRITE, brix_rl_charge_ctx(), brix_send_error(), brix_transfer_slot_count_op(), brix_transfer_slot_update(), brix_vfs_staged_write(), brix_ctx_totals_t::bytes_written, brix_file_t::bytes_written, c, brix_file_t::dashboard_slot, brix_ctx_t::files, kXR_IOError, kXR_Unsupported, ngx_brix_dashboard_shm_zone, brix_file_t::path, brix_file_t::staged, brix_file_t::staged_expected_off, and brix_ctx_t::totals.
Referenced by brix_handle_pgwrite(), and brix_write_staged_buf().
brix_staged_commit_handle()
ngx_int_t brix_staged_commit_handle (brix_ctx_t * ctx, int idx, int * err_out)
Definition at line 132 of file write_staged.c.
References brix_vfs_staged_commit(), brix_ctx_t::files, brix_file_t::staged, and brix_file_t::staged_committed.
Referenced by brix_close_staged_commit(), and brix_handle_sync().
brix_write_staged()
ngx_int_t brix_write_staged (brix_ctx_t * ctx, ngx_connection_t * c, int idx, int64_t offset, size_t wlen)
Definition at line 117 of file write_staged.c.
References brix_write_staged_buf(), c, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by brix_write_route_special().
brix_write_staged_buf()
ngx_int_t brix_write_staged_buf (brix_ctx_t * ctx, ngx_connection_t * c, int idx, int64_t offset, const u_char * buf, size_t len)
Definition at line 97 of file write_staged.c.
References BRIX_OP_WRITE, BRIX_RETURN_OK, brix_staged_append(), c, brix_ctx_t::files, and brix_file_t::path.
Referenced by brix_write_staged().