nginx-xrootd: src/protocols/root/write/write.h File Reference
write.h File Reference
#include "core/ngx_brix_module.h"
#include "core/compat/pgio.h"
Functions
ngx_int_t brix_handle_write (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_write_require_pgwrite (brix_ctx_t *ctx, ngx_connection_t *c, int idx, size_t wlen, const char *op, ngx_int_t *rc)
ngx_int_t brix_write_compressed (brix_ctx_t *ctx, ngx_connection_t *c, int idx, int64_t offset, size_t wlen)
ngx_int_t brix_write_staged (brix_ctx_t *ctx, ngx_connection_t *c, int idx, int64_t offset, size_t wlen)
ngx_int_t brix_write_staged_buf (brix_ctx_t *ctx, ngx_connection_t *c, int idx, int64_t offset, const u_char *buf, size_t len)
ngx_int_t brix_staged_append (brix_ctx_t *ctx, ngx_connection_t *c, int idx, int64_t offset, const u_char *buf, size_t len, ngx_int_t *rc)
ngx_int_t brix_staged_commit_handle (brix_ctx_t *ctx, int idx, int *err_out)
ngx_int_t brix_handle_pgwrite (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_handle_writev (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_writev_body_extra (const u_char *desc, uint32_t dlen, uint32_t *extra)
ngx_int_t brix_ckpxeq_body_extra (const u_char *body, uint32_t have, uint32_t *extra, unsigned *final)
ngx_int_t brix_handle_sync (brix_ctx_t *ctx, ngx_connection_t *c)
ngx_int_t brix_handle_truncate (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_handle_mkdir (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_handle_rm (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_handle_rmdir (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_handle_mv (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_handle_chmod (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf)
ngx_int_t brix_pgwrite_decode_payload (const u_char *payload, size_t payload_len, int64_t offset, u_char *flat, size_t *flat_len, int64_t *bad_offset)
ngx_int_t brix_try_post_write_aio (brix_ctx_t *ctx, ngx_connection_t *c, int idx, off_t offset, const u_char *data, size_t len, int64_t req_offset, ngx_uint_t is_pgwrite, u_char *payload_to_free, const xrdp_pg_bad_t *bad, size_t bad_count, const char *fallback_log, ngx_flag_t *posted)
Function Documentation
brix_ckpxeq_body_extra()
ngx_int_t brix_ckpxeq_body_extra (const u_char * body, uint32_t have, uint32_t * extra, unsigned * final)
Definition at line 24 of file chkpoint_xeq.c.
References BRIX_MAX_WRITE_PAYLOAD, brix_writev_body_extra(), BRIX_WRITEV_MAXSEGS, BRIX_WRITEV_SEGSIZE, have(), kXR_pgwrite, kXR_write, and kXR_writev.
Referenced by brix_recv_extend_body().
brix_handle_chmod()
ngx_int_t brix_handle_chmod (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 8 of file chmod.c.
References brix_dispatch_op(), c, and kXR_chmod.
brix_handle_mkdir()
ngx_int_t brix_handle_mkdir (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 28 of file mkdir.c.
References brix_apply_parent_group_policy_path(), brix_auth_gate(), BRIX_AUTH_MKDIR, brix_kxr_from_errno(), BRIX_MAX_PATH, BRIX_OP_MKDIR, BRIX_PATH_NOEXIST, BRIX_PATH_WRITE, BRIX_PROTO_ROOT, brix_resolve_op_path(), BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_root_vfs_bind_deleg(), brix_vfs_backend_resolve(), brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_init(), brix_vfs_mkdir(), c, brix_ctx_recv_t::hdr_buf, brix_ctx_t::identity, kXR_ItExists, kXR_mkdirpath, xrdw_mkdir_req_t::mode, xrdw_mkdir_req_t::options, PATH_MAX, brix_vfs_ctx_t::pool, brix_ctx_t::recv, brix_ctx_t::write_rc, and xrdw_mkdir_req_unpack().
brix_handle_mv()
ngx_int_t brix_handle_mv (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 362 of file mv.c.
References BRIX_AOP_INSERT, BRIX_AOP_RENAME, BRIX_AUTH_DELETE, brix_auth_gate_op(), BRIX_AUTH_UPDATE, BRIX_OP_MV, BRIX_PATH_EXISTING, brix_path_resolve_beneath(), BRIX_PATH_WRITE, BRIX_RETURN_ERR, BRIX_RETURN_OK, c, mv_req_t::dst_buf, mv_req_t::dst_resolved, kXR_NotFound, mv_dst_slash_precheck(), mv_execute(), mv_make_dst_parents(), mv_parse_paths(), mv_req_t::src_buf, mv_req_t::src_resolved, and brix_ctx_t::write_rc.
brix_handle_pgwrite()
ngx_int_t brix_handle_pgwrite (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 424 of file pgwrite.c.
References pgw_state_t::bad_count, pgw_state_t::bad_pages, BRIX_OP_OK, BRIX_OP_WRITE, BRIX_RETURN_ERR, brix_send_pgwrite_status(), brix_staged_append(), brix_try_post_write_aio(), c, pgw_state_t::dlen, brix_ctx_t::files, pgw_state_t::flat, pgw_state_t::flat_sz, pgw_state_t::idx, pgw_state_t::is_retry, kXR_ChkSumErr, ngx_stream_brix_module, pgw_state_t::offset, brix_file_t::path, pgw_fmt_detail(), pgwrite_decode_collect(), pgwrite_execute_sync(), pgwrite_parse_validate(), pgw_state_t::rconf, and brix_file_t::writer.
brix_handle_rm()
ngx_int_t brix_handle_rm (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 8 of file rm.c.
References brix_dispatch_op(), c, and kXR_rm.
brix_handle_rmdir()
ngx_int_t brix_handle_rmdir (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 8 of file rmdir.c.
References brix_dispatch_op(), c, and kXR_rmdir.
brix_handle_sync()
ngx_int_t brix_handle_sync (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 18 of file sync.c.
References BRIX_OP_SYNC, brix_pgw_fob_commit_blocked(), BRIX_RETURN_ERR, BRIX_RETURN_OK, brix_staged_commit_handle(), brix_tpc_start_pull(), brix_transfer_slot_count_op(), brix_validate_file_handle(), brix_vfs_io_execute(), brix_vfs_job_set_obj(), brix_vfs_job_sync_init(), brix_wrts_flush(), c, brix_file_t::dashboard_slot, brix_file_t::fd, xrdw_sync_req_t::fhandle, brix_ctx_t::files, brix_ctx_recv_t::hdr_buf, brix_vfs_job_t::io_errno, kXR_ChkSumErr, kXR_IOError, ngx_brix_dashboard_shm_zone, ngx_stream_brix_module, brix_file_t::path, brix_ctx_t::recv, brix_file_t::sd_obj, brix_ctx_t::session, brix_file_t::tpc_armed, brix_file_t::tpc_destination, brix_file_t::tpc_done, brix_file_t::writer, brix_file_t::wrts_enabled, and xrdw_sync_req_unpack().
brix_handle_truncate()
ngx_int_t brix_handle_truncate (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf)
Definition at line 27 of file truncate.c.
References brix_auth_gate(), BRIX_AUTH_UPDATE, brix_kxr_from_errno(), brix_log_access(), BRIX_MAX_PATH, BRIX_OP_OK, BRIX_OP_TRUNCATE, BRIX_PATH_EITHER, BRIX_PROTO_ROOT, brix_resolve_op_path(), BRIX_RETURN_ERR, brix_root_vfs_bind_deleg(), brix_send_ok(), brix_validate_file_handle(), brix_vfs_close(), brix_vfs_ctx_bind_backend_cred(), brix_vfs_ctx_bind_backend_mint(), brix_vfs_ctx_init(), brix_vfs_io_execute(), brix_vfs_job_set_obj(), brix_vfs_job_truncate_init(), BRIX_VFS_O_WRITE, brix_vfs_open(), brix_vfs_truncate(), brix_wt_mark_dirty(), c, brix_ctx_recv_t::cur_dlen, brix_file_t::fd, xrdw_truncate_req_t::fhandle, brix_ctx_t::files, brix_ctx_recv_t::hdr_buf, brix_ctx_t::identity, brix_vfs_job_t::io_errno, kXR_IOError, xrdw_truncate_req_t::offset, brix_file_t::path, PATH_MAX, brix_vfs_ctx_t::pool, brix_ctx_t::recv, brix_file_t::sd_obj, brix_ctx_t::write_rc, brix_file_t::wt_enabled, and xrdw_truncate_req_unpack().
brix_handle_write()
ngx_int_t brix_handle_write (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 276 of file write.c.
References BRIX_OP_WRITE, brix_try_post_write_aio(), brix_validate_write_handle(), brix_vfs_io_execute(), brix_vfs_job_set_obj(), brix_vfs_job_write_init(), brix_write_finalize_sync(), brix_write_require_pgwrite(), brix_write_route_special(), c, brix_file_t::csi, brix_vfs_job_t::csi, brix_ctx_recv_t::cur_dlen, brix_file_t::fd, xrdw_write_req_t::fhandle, brix_ctx_t::files, brix_ctx_recv_t::hdr_buf, brix_vfs_job_t::io_errno, brix_vfs_job_t::nio, xrdw_write_req_t::offset, brix_ctx_t::out, brix_ctx_recv_t::payload, brix_ctx_recv_t::payload_buf, brix_ctx_recv_t::payload_buf_size, brix_ctx_t::recv, brix_file_t::sd_obj, brix_ctx_out_t::wr_inflight, and xrdw_write_req_unpack().
brix_handle_writev()
ngx_int_t brix_handle_writev (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 356 of file writev.c.
References brix_log_access(), BRIX_OP_ERR, BRIX_OP_WRITEV, brix_send_error(), BRIX_WRITEV_SEGSIZE, c, writev_run_t::c, writev_run_t::ctx, writev_run_t::data_ptr, brix_ctx_recv_t::hdr_buf, kXR_Unsupported, kXR_wv_doSync, writev_run_t::n_segs, ngx_stream_brix_module, xrdw_writev_req_t::options, brix_ctx_recv_t::payload, brix_ctx_t::recv, writev_run_t::wl, writev_execute_sync(), writev_reply(), writev_sync_handles(), writev_try_aio(), writev_validate_framing(), writev_validate_handles(), and xrdw_writev_req_unpack().
brix_pgwrite_decode_payload()
ngx_int_t brix_pgwrite_decode_payload (const u_char * payload, size_t payload_len, int64_t offset, u_char * flat, size_t * flat_len, int64_t * bad_offset)
Definition at line 44 of file pgwrite.c.
References XRD_PGWRITE_CKSZ, and xrdp_pg_decode().
Referenced by ckp_xeq_pgwrite().
brix_staged_append()
ngx_int_t brix_staged_append (brix_ctx_t * ctx, ngx_connection_t * c, int idx, int64_t offset, const u_char * buf, size_t len, ngx_int_t * rc)
Definition at line 46 of file write_staged.c.
References brix_log_access(), BRIX_OP_ERR, BRIX_OP_WRITE, brix_rl_charge_ctx(), brix_send_error(), brix_transfer_slot_count_op(), brix_transfer_slot_update(), brix_vfs_writer_expected_off(), brix_vfs_writer_write(), brix_ctx_totals_t::bytes_written, brix_file_t::bytes_written, c, brix_file_t::dashboard_slot, brix_ctx_t::files, kXR_IOError, kXR_Unsupported, ngx_brix_dashboard_shm_zone, brix_file_t::path, brix_ctx_t::totals, and brix_file_t::writer.
Referenced by brix_handle_pgwrite(), and brix_write_staged_buf().
brix_staged_commit_handle()
ngx_int_t brix_staged_commit_handle (brix_ctx_t * ctx, int idx, int * err_out)
Definition at line 135 of file write_staged.c.
References brix_vfs_writer_commit(), brix_ctx_t::files, brix_file_t::staged_committed, and brix_file_t::writer.
Referenced by brix_close_staged_commit(), and brix_handle_sync().
brix_try_post_write_aio()
ngx_int_t brix_try_post_write_aio (brix_ctx_t * ctx, ngx_connection_t * c, int idx, off_t offset, const u_char * data, size_t len, int64_t req_offset, ngx_uint_t is_pgwrite, u_char * payload_to_free, const xrdp_pg_bad_t * bad, size_t bad_count, const char * fallback_log, ngx_flag_t * posted)
Definition at line 17 of file common.c.
References brix_write_aio_t::bad_page_count, brix_write_aio_t::bad_pages, brix_aio_post_task(), brix_write_aio_done(), brix_write_aio_thread(), c, brix_write_aio_t::c, brix_write_aio_t::conf, brix_write_aio_t::csi, brix_file_t::csi, brix_write_aio_t::ctx, brix_ctx_recv_t::cur_streamid, brix_write_aio_t::data, brix_write_aio_t::fd, brix_file_t::fd, brix_ctx_t::files, brix_write_aio_t::handle_idx, brix_write_aio_t::io_errno, brix_write_aio_t::is_pgwrite, kXR_pgMaxEpr, brix_write_aio_t::len, ngx_memcpy, ngx_stream_brix_module, brix_write_aio_t::nwritten, brix_write_aio_t::obj, brix_write_aio_t::offset, brix_write_aio_t::path, brix_file_t::path, brix_write_aio_t::payload_to_free, brix_ctx_t::recv, brix_write_aio_t::req_offset, brix_file_t::sd_obj, and brix_write_aio_t::streamid.
Referenced by brix_handle_pgwrite(), and brix_handle_write().
brix_write_compressed()
ngx_int_t brix_write_compressed (brix_ctx_t * ctx, ngx_connection_t * c, int idx, int64_t offset, size_t wlen)
Definition at line 143 of file write_compress.c.
References brix_codec_close(), BRIX_CODEC_DIR_DECOMPRESS, brix_codec_open(), BRIX_GET_SCRATCH, brix_log_access(), BRIX_OP_OK, BRIX_OP_WRITE, BRIX_RETURN_ERR, brix_rl_charge_ctx(), brix_send_ok(), brix_transfer_slot_count_op(), brix_transfer_slot_update(), brix_wcmp_decompress_stream(), BRIX_WCMP_OUT_CAP, BRIX_WCMP_WINDOW, brix_ctx_totals_t::bytes_written, brix_file_t::bytes_written, c, brix_file_t::dashboard_slot, brix_file_t::fd, brix_ctx_t::files, kXR_IOError, brix_codec_guard_t::max_ratio, ngx_brix_dashboard_shm_zone, ngx_stream_brix_module, brix_codec_guard_t::out_cap, brix_file_t::path, s, brix_ctx_t::totals, and brix_file_t::write_codec.
Referenced by brix_write_route_special().
brix_write_require_pgwrite()
ngx_int_t brix_write_require_pgwrite (brix_ctx_t * ctx, ngx_connection_t * c, int idx, size_t wlen, const char * op, ngx_int_t * rc)
Definition at line 232 of file write.c.
References brix_log_access(), BRIX_OP_ERR, BRIX_OP_WRITE, brix_send_error(), c, brix_ctx_t::files, kXR_Unsupported, ngx_stream_brix_module, op, brix_file_t::path, and brix_file_t::ssi.
Referenced by brix_handle_write().
brix_write_staged()
ngx_int_t brix_write_staged (brix_ctx_t * ctx, ngx_connection_t * c, int idx, int64_t offset, size_t wlen)
Definition at line 118 of file write_staged.c.
References brix_write_staged_buf(), c, brix_ctx_recv_t::payload, and brix_ctx_t::recv.
Referenced by brix_write_route_special().
brix_write_staged_buf()
ngx_int_t brix_write_staged_buf (brix_ctx_t * ctx, ngx_connection_t * c, int idx, int64_t offset, const u_char * buf, size_t len)
Definition at line 98 of file write_staged.c.
References BRIX_OP_WRITE, BRIX_RETURN_OK, brix_staged_append(), c, brix_ctx_t::files, and brix_file_t::path.
Referenced by brix_write_staged().
brix_writev_body_extra()
ngx_int_t brix_writev_body_extra (const u_char * desc, uint32_t dlen, uint32_t * extra)
Definition at line 22 of file writev.c.
References BRIX_MAX_WRITE_PAYLOAD, BRIX_WRITEV_MAXSEGS, BRIX_WRITEV_SEGSIZE, and write_list::wlen.
Referenced by brix_ckpxeq_body_extra(), and brix_recv_extend_body().