nginx-xrootd: src/protocols/root/connection/write_helpers.h File Reference
write_helpers.h File Reference
#include "core/ngx_brix_module.h"
#include "event_sched.h"
Functions
ngx_int_t brix_queue_response_base (brix_ctx_t *ctx, ngx_connection_t *c, u_char *buffer, size_t buffer_len, u_char *owned_base)
ngx_int_t brix_queue_response (brix_ctx_t *ctx, ngx_connection_t *c, u_char *buffer, size_t buffer_len)
ngx_int_t brix_queue_response_chain (brix_ctx_t *ctx, ngx_connection_t *c, ngx_chain_t *chain, u_char *owned_base)
ngx_int_t brix_flush_pending (brix_ctx_t *ctx, ngx_connection_t *c)
Function Documentation
brix_flush_pending()
ngx_int_t brix_flush_pending (brix_ctx_t * ctx, ngx_connection_t * c)
Definition at line 272 of file write_helpers.c.
References brix_chain_pending_bytes(), brix_disarm_send_deadline(), brix_note_chain_progress(), brix_release_pending_buffer(), brix_schedule_write_resume(), BRIX_SEND_CHAIN_SPIN_MAX, BRIX_SRV_METRIC_ADD, BRIX_SRV_METRIC_INC, brix_tcp_push(), c, brix_ctx_out_t::count, brix_ctx_out_t::head, brix_ctx_t::out, brix_ctx_out_t::pipeline_depth, brix_ctx_out_t::ring, brix_resp_slot_t::wbuf, brix_resp_slot_t::wbuf_base, brix_resp_slot_t::wbuf_len, brix_resp_slot_t::wbuf_pos, brix_resp_slot_t::wchain, brix_resp_slot_t::wchain_base, and brix_resp_slot_t::wchain_pending.
Referenced by ngx_stream_brix_send().
brix_queue_response()
ngx_int_t brix_queue_response (brix_ctx_t * ctx, ngx_connection_t * c, u_char * buffer, size_t buffer_len)
Definition at line 189 of file write_helpers.c.
References brix_queue_response_base(), and c.
Referenced by brix_dirlist_flush_chunk(), brix_dirlist_send_final(), brix_gsi_begin_delegation(), brix_handle_bind(), brix_handle_protocol(), brix_login_respond_anon(), brix_login_respond_authenticated(), brix_open_send_response(), brix_pgread_aio_done(), brix_pgread_parse_validate(), brix_process_handshake(), brix_proxy_relay_finish_final(), brix_proxy_relay_streaming_frame(), brix_send_attn(), brix_send_attn_asyncms(), brix_send_attn_asynresp(), brix_send_error(), brix_send_ok(), brix_send_pgwrite_cse(), brix_send_pgwrite_status(), brix_send_redirect(), brix_send_redirect_tpc(), brix_send_wait(), brix_send_waitresp(), brix_sss_send_authmore(), brix_upstream_forward_response(), gsi_frame_cert_response(), prepare_emit_stage(), proxy_read_relay_attn(), pwd_send_credsreq(), ssi_open_send_reply(), tpc_done_send_open_ok(), tpc_send_open_response(), and zip_send_open_reply().
brix_queue_response_base()
ngx_int_t brix_queue_response_base (brix_ctx_t * ctx, ngx_connection_t * c, u_char * buffer, size_t buffer_len, u_char * owned_base)
Definition at line 103 of file write_helpers.c.
References brix_ensure_write_event(), brix_schedule_write_resume(), BRIX_SRV_METRIC_ADD, BRIX_SRV_METRIC_INC, c, brix_ctx_out_t::count, brix_ctx_t::out, brix_ctx_out_t::pipeline_depth, brix_ctx_out_t::resp_async, brix_ctx_out_t::ring, brix_ctx_t::state, brix_ctx_out_t::tail, brix_resp_slot_t::wbuf, brix_resp_slot_t::wbuf_base, brix_resp_slot_t::wbuf_len, brix_resp_slot_t::wbuf_pos, and XRD_ST_SENDING.
Referenced by brix_dirlist_aio_done(), and brix_queue_response().
brix_queue_response_chain()
ngx_int_t brix_queue_response_chain (brix_ctx_t * ctx, ngx_connection_t * c, ngx_chain_t * chain, u_char * owned_base)
Definition at line 198 of file write_helpers.c.
References brix_chain_pending_bytes(), brix_ensure_write_event(), brix_note_chain_progress(), brix_schedule_write_resume(), BRIX_SEND_CHAIN_SPIN_MAX, BRIX_SRV_METRIC_ADD, BRIX_SRV_METRIC_INC, brix_tcp_push(), c, brix_ctx_out_t::count, brix_ctx_t::out, brix_ctx_out_t::pipeline_depth, brix_ctx_out_t::ring, brix_ctx_t::state, brix_ctx_out_t::tail, brix_resp_slot_t::wchain, brix_resp_slot_t::wchain_base, brix_resp_slot_t::wchain_pending, and XRD_ST_SENDING.
Referenced by brix_pgread_aio_done(), brix_pgread_send_response(), brix_read_aio_done(), brix_read_compressed(), brix_read_serve_sendfile(), brix_read_window_emit(), brix_readv_aio_done(), brix_readv_execute_sync(), and read_finish_buffered().