nginx-xrootd: src/protocols/root/write/wrts_journal.h File Reference
wrts_journal.h File Reference
#include "core/types/file.h"
Functions
void brix_wrts_open (brix_file_t *f)
void brix_wrts_record (brix_file_t *f, int64_t offset, uint32_t length)
int brix_wrts_is_replay (const brix_file_t *f, int64_t offset, uint32_t length)
void brix_wrts_flush (brix_file_t *f)
Function Documentation
brix_wrts_flush()
void brix_wrts_flush (brix_file_t * f)
Definition at line 100 of file wrts_journal.c.
References brix_file_t::wrts_count, brix_file_t::wrts_enabled, brix_file_t::wrts_gen, brix_file_t::wrts_head, and brix_file_t::wrts_journal.
Referenced by brix_close_release_slots(), and brix_handle_sync().
brix_wrts_is_replay()
int brix_wrts_is_replay (const brix_file_t * f, int64_t offset, uint32_t length)
Definition at line 63 of file wrts_journal.c.
References BRIX_WRTS_JOURNAL_SLOTS, brix_wrts_entry_t::length, brix_wrts_entry_t::offset, brix_file_t::wrts_count, brix_file_t::wrts_enabled, and brix_file_t::wrts_journal.
Referenced by brix_write_route_special(), pgwrite_decode_collect(), writev_try_aio(), and writev_write_segment().
brix_wrts_open()
void brix_wrts_open (brix_file_t * f)
Definition at line 28 of file wrts_journal.c.
References brix_file_t::wrts_count, brix_file_t::wrts_enabled, brix_file_t::wrts_gen, brix_file_t::wrts_head, and brix_file_t::wrts_journal.
Referenced by brix_open_init_handle().
brix_wrts_record()
void brix_wrts_record (brix_file_t * f, int64_t offset, uint32_t length)
Definition at line 39 of file wrts_journal.c.
References BRIX_WRTS_JOURNAL_SLOTS, brix_wrts_entry_t::gen, brix_wrts_entry_t::length, brix_wrts_entry_t::offset, brix_file_t::wrts_count, brix_file_t::wrts_enabled, brix_file_t::wrts_gen, brix_file_t::wrts_head, and brix_file_t::wrts_journal.
Referenced by brix_write_aio_commit(), brix_write_finalize_sync(), brix_writev_write_aio_done(), pgwrite_execute_sync(), and writev_write_segment().