nginx-xrootd: src/fs/xfer/xfer_resume_sweep.c File Reference
xfer_resume_sweep.c File Reference
#include "xfer.h"
#include <ngx_event.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Macros
#define XFER_RESUME_SUFFIX ".xrdresume.part"
#define XFER_RESUME_SUFFIX_LEN (sizeof(XFER_RESUME_SUFFIX) - 1)
#define XFER_RESUME_TTL_DEFAULT 86400 /* 1 day */
#define XFER_RESUME_SWEEP_DELAY 5000 /* ms after worker start: 1st pass */
#define XFER_RESUME_SWEEP_PERIOD 3600000 /* ms between passes (1 hour) */
#define XFER_RESUME_SCAN_CAP 8192 /* bound a single pass */
Functions
static time_t xfer_resume_ttl (void)
static void xfer_resume_sweep_run (void)
static void xfer_resume_sweep_handler (ngx_event_t *ev)
void brix_xfer_resume_sweep_register (ngx_cycle_t *cycle, const char *stage_dir)
Variables
static ngx_event_t xfer_sweep_ev
static char xfer_sweep_dir [PATH_MAX]
static time_t xfer_sweep_ttl
static ngx_log_t * xfer_sweep_log
Macro Definition Documentation
XFER_RESUME_SCAN_CAP
#define XFER_RESUME_SCAN_CAP 8192 /* bound a single pass */
Definition at line 42 of file xfer_resume_sweep.c.
XFER_RESUME_SUFFIX
#define XFER_RESUME_SUFFIX ".xrdresume.part"
Definition at line 37 of file xfer_resume_sweep.c.
XFER_RESUME_SUFFIX_LEN
#define XFER_RESUME_SUFFIX_LEN (sizeof(XFER_RESUME_SUFFIX) - 1)
Definition at line 38 of file xfer_resume_sweep.c.
XFER_RESUME_SWEEP_DELAY
#define XFER_RESUME_SWEEP_DELAY 5000 /* ms after worker start: 1st pass */
Definition at line 40 of file xfer_resume_sweep.c.
XFER_RESUME_SWEEP_PERIOD
#define XFER_RESUME_SWEEP_PERIOD 3600000 /* ms between passes (1 hour) */
Definition at line 41 of file xfer_resume_sweep.c.
XFER_RESUME_TTL_DEFAULT
#define XFER_RESUME_TTL_DEFAULT 86400 /* 1 day */
Definition at line 39 of file xfer_resume_sweep.c.
Function Documentation
brix_xfer_resume_sweep_register()
void brix_xfer_resume_sweep_register (ngx_cycle_t * cycle, const char * stage_dir)
Definition at line 127 of file xfer_resume_sweep.c.
References XFER_RESUME_SWEEP_DELAY, xfer_resume_sweep_handler(), xfer_resume_ttl(), xfer_sweep_dir, xfer_sweep_ev, xfer_sweep_log, and xfer_sweep_ttl.
Referenced by ngx_stream_brix_init_process().
xfer_resume_sweep_handler()
static void xfer_resume_sweep_handler (ngx_event_t * ev) static
Definition at line 118 of file xfer_resume_sweep.c.
References XFER_RESUME_SWEEP_PERIOD, and xfer_resume_sweep_run().
Referenced by brix_xfer_resume_sweep_register().
xfer_resume_sweep_run()
static void xfer_resume_sweep_run (void) static
Definition at line 69 of file xfer_resume_sweep.c.
References fstatat(), stat(), XFER_RESUME_SCAN_CAP, XFER_RESUME_SUFFIX, XFER_RESUME_SUFFIX_LEN, xfer_sweep_dir, xfer_sweep_log, and xfer_sweep_ttl.
Referenced by xfer_resume_sweep_handler().
xfer_resume_ttl()
static time_t xfer_resume_ttl (void) static
Definition at line 51 of file xfer_resume_sweep.c.
References XFER_RESUME_TTL_DEFAULT.
Referenced by brix_xfer_resume_sweep_register().
Variable Documentation
xfer_sweep_dir
char xfer_sweep_dir[PATH_MAX] static
Definition at line 45 of file xfer_resume_sweep.c.
Referenced by brix_xfer_resume_sweep_register(), and xfer_resume_sweep_run().
xfer_sweep_ev
ngx_event_t xfer_sweep_ev static
Definition at line 44 of file xfer_resume_sweep.c.
Referenced by brix_xfer_resume_sweep_register().
xfer_sweep_log
ngx_log_t* xfer_sweep_log static
Definition at line 47 of file xfer_resume_sweep.c.
Referenced by brix_xfer_resume_sweep_register(), and xfer_resume_sweep_run().
xfer_sweep_ttl
time_t xfer_sweep_ttl static
Definition at line 46 of file xfer_resume_sweep.c.
Referenced by brix_xfer_resume_sweep_register(), and xfer_resume_sweep_run().