nginx-xrootd: src/fs/xfer/xfer.h File Reference
xfer.h File Reference
#include <ngx_core.h>
#include "fs/backend/sd.h"
Data Structures
struct brix_xfer_agent_ops_t
struct brix_xfer_agent_t
struct brix_xfer_audit_t
Enumerations
enum brix_xfer_kind_t { BRIX_XFER_STAGE = 0 , BRIX_XFER_TAPE , BRIX_XFER_WT , BRIX_XFER_TPC }
enum brix_xfer_mover_t { BRIX_XFER_MOVE_PUMP = 0 , BRIX_XFER_MOVE_AGENT }
enum brix_xfer_disp_t { BRIX_XFER_SYNC = 0 , BRIX_XFER_ASYNC , BRIX_XFER_DENY }
enum brix_xfer_result_t {
BRIX_XFER_OK = 0 , BRIX_XFER_DEFERRED , BRIX_XFER_DENIED , BRIX_XFER_SRC_ERR ,
BRIX_XFER_DST_ERR , BRIX_XFER_COMMIT_ERR , BRIX_XFER_AGENT_FAIL
}
Functions
ngx_int_t brix_xfer_agent_attach (brix_xfer_agent_t *a, const brix_xfer_agent_ops_t *ops, ngx_log_t *log)
void brix_xfer_agent_teardown (brix_xfer_agent_t *a)
ngx_int_t brix_xfer_agent_dispatch (brix_xfer_agent_t *a, const void *req)
void brix_xfer_ledger_record (const brix_xfer_audit_t *ev)
const char * brix_xfer_kind_str (brix_xfer_kind_t kind)
const char * brix_xfer_result_str (brix_xfer_result_t result)
void brix_xfer_finish (brix_xfer_kind_t kind, const char *direction, const char *path, const char *principal, size_t bytes, brix_xfer_result_t result, int sys_errno, ngx_log_t *log)
void brix_xfer_resume_sweep_register (ngx_cycle_t *cycle, const char *stage_dir)
ngx_int_t brix_xfer_pump_objects (brix_sd_obj_t *src, brix_sd_obj_t *dst)
Enumeration Type Documentation
brix_xfer_disp_t
enum brix_xfer_disp_t
Enumerator
BRIX_XFER_SYNC
BRIX_XFER_ASYNC
BRIX_XFER_DENY
Definition at line 52 of file xfer.h.
brix_xfer_kind_t
enum brix_xfer_kind_t
Enumerator
BRIX_XFER_STAGE
BRIX_XFER_TAPE
BRIX_XFER_WT
BRIX_XFER_TPC
Definition at line 36 of file xfer.h.
brix_xfer_mover_t
enum brix_xfer_mover_t
Enumerator
BRIX_XFER_MOVE_PUMP
BRIX_XFER_MOVE_AGENT
Definition at line 46 of file xfer.h.
brix_xfer_result_t
enum brix_xfer_result_t
Enumerator
BRIX_XFER_OK
BRIX_XFER_DEFERRED
BRIX_XFER_DENIED
BRIX_XFER_SRC_ERR
BRIX_XFER_DST_ERR
BRIX_XFER_COMMIT_ERR
BRIX_XFER_AGENT_FAIL
Definition at line 60 of file xfer.h.
Function Documentation
brix_xfer_agent_attach()
ngx_int_t brix_xfer_agent_attach (brix_xfer_agent_t * a, const brix_xfer_agent_ops_t * ops, ngx_log_t * log)
Definition at line 244 of file xfer_mover_agent.c.
References brix_xfer_agent_teardown(), close(), brix_xfer_agent_t::conn, brix_xfer_agent_t::fd, log, brix_xfer_agent_t::log, brix_xfer_agent_ops_t::name, brix_xfer_agent_t::ops, brix_xfer_agent_t::rep_buf, brix_xfer_agent_ops_t::rep_size, xfer_agent_on_reply(), and xfer_agent_spawn().
Referenced by xfer_agent_respawn().
brix_xfer_agent_dispatch()
ngx_int_t brix_xfer_agent_dispatch (brix_xfer_agent_t * a, const void * req)
Definition at line 284 of file xfer_mover_agent.c.
References brix_xfer_agent_t::fd, brix_xfer_agent_t::ops, brix_xfer_agent_ops_t::req_size, and xfer_write_full().
brix_xfer_agent_teardown()
void brix_xfer_agent_teardown (brix_xfer_agent_t * a)
Definition at line 234 of file xfer_mover_agent.c.
References brix_xfer_agent_t::conn, and brix_xfer_agent_t::fd.
Referenced by brix_xfer_agent_attach(), and xfer_agent_respawn().
brix_xfer_finish()
void brix_xfer_finish (brix_xfer_kind_t kind, const char * direction, const char * path, const char * principal, size_t bytes, brix_xfer_result_t result, int sys_errno, ngx_log_t * log)
Definition at line 25 of file xfer_core.c.
References brix_xfer_ledger_record(), brix_xfer_audit_t::kind, and log.
Referenced by brix_handle_close(), brix_vfs_staged_commit(), ngx_http_brix_webdav_tpc_handle_copy(), s3_commit_put(), stage_engine_run(), tpc_thread_done(), and webdav_tpc_handle_push().
brix_xfer_kind_str()
const char * brix_xfer_kind_str (brix_xfer_kind_t kind)
Definition at line 38 of file xfer_ledger.c.
References BRIX_XFER_STAGE, BRIX_XFER_TAPE, BRIX_XFER_TPC, and BRIX_XFER_WT.
Referenced by brix_xfer_ledger_record().
brix_xfer_ledger_record()
void brix_xfer_ledger_record (const brix_xfer_audit_t * ev)
Definition at line 115 of file xfer_ledger.c.
References brix_sanitize_log_string(), brix_xfer_kind_str(), BRIX_XFER_OK, brix_xfer_result_str(), brix_xfer_audit_t::bytes, brix_xfer_audit_t::direction, brix_xfer_audit_t::kind, brix_xfer_audit_t::log, brix_xfer_audit_t::path, brix_xfer_audit_t::principal, brix_xfer_audit_t::result, brix_xfer_audit_t::sys_errno, and xfer_audit_fd_get().
Referenced by brix_xfer_finish().
brix_xfer_pump_objects()
ngx_int_t brix_xfer_pump_objects (brix_sd_obj_t * src, brix_sd_obj_t * dst)
Definition at line 28 of file xfer_mover_pump.c.
Referenced by stage_move_objects().
brix_xfer_result_str()
const char * brix_xfer_result_str (brix_xfer_result_t result)
Definition at line 50 of file xfer_ledger.c.
References BRIX_XFER_AGENT_FAIL, BRIX_XFER_COMMIT_ERR, BRIX_XFER_DEFERRED, BRIX_XFER_DENIED, BRIX_XFER_DST_ERR, BRIX_XFER_OK, and BRIX_XFER_SRC_ERR.
Referenced by brix_xfer_ledger_record().
brix_xfer_resume_sweep_register()
void brix_xfer_resume_sweep_register (ngx_cycle_t * cycle, const char * stage_dir)
Definition at line 127 of file xfer_resume_sweep.c.
References XFER_RESUME_SWEEP_DELAY, xfer_resume_sweep_handler(), xfer_resume_ttl(), xfer_sweep_dir, xfer_sweep_ev, xfer_sweep_log, and xfer_sweep_ttl.
Referenced by ngx_stream_brix_init_process().