nginx-xrootd: src/fs/xfer/xfer_spawn.c File Reference
xfer_spawn.c File Reference
#include "xfer_spawn.h"
#include <errno.h>
#include <signal.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <sys/wait.h>
#include <unistd.h>
Macros
#define _GNU_SOURCE /* execvpe: PATH search + caller-supplied environ */
#define XFER_SPAWN_EXEC_FAILED 127
#define XFER_SPAWN_KILLED 128
Functions
static int xfer_read_exact (int fd, void *buf, size_t len)
static void xfer_write_exact (int fd, const void *buf, size_t len)
static void xfer_spawn_agent (int result_fd, const char *const argv[], char *const envp[])
int brix_xfer_run_reparented (const char *const argv[], char *const envp[])
Variables
char ** environ
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE /* execvpe: PATH search + caller-supplied environ */
Definition at line 15 of file xfer_spawn.c.
XFER_SPAWN_EXEC_FAILED
#define XFER_SPAWN_EXEC_FAILED 127
Definition at line 30 of file xfer_spawn.c.
XFER_SPAWN_KILLED
#define XFER_SPAWN_KILLED 128
Definition at line 31 of file xfer_spawn.c.
Function Documentation
brix_xfer_run_reparented()
int brix_xfer_run_reparented (const char *const argv[], char *const envp[])
Definition at line 106 of file xfer_spawn.c.
References close(), xfer_read_exact(), and xfer_spawn_agent().
Referenced by main().
xfer_read_exact()
static int xfer_read_exact (int fd, void * buf, size_t len) static
Definition at line 35 of file xfer_spawn.c.
References read().
Referenced by brix_xfer_run_reparented().
xfer_spawn_agent()
static void xfer_spawn_agent (int result_fd, const char *const argv[], char *const envp[]) static
Definition at line 77 of file xfer_spawn.c.
References close(), environ, XFER_SPAWN_EXEC_FAILED, XFER_SPAWN_KILLED, and xfer_write_exact().
Referenced by brix_xfer_run_reparented().
xfer_write_exact()
static void xfer_write_exact (int fd, const void * buf, size_t len) static
Definition at line 58 of file xfer_spawn.c.
Referenced by xfer_spawn_agent().
Variable Documentation
environ
char** environ extern
Referenced by xfer_spawn_agent().