nginx-xrootd: client/lib/cli/xferjournal.h File Reference
xferjournal.h File Reference
#include "brix.h"
Functions
brix_journal * brix_journal_open (const char *path, brix_status *st)
int brix_journal_has (const brix_journal *j, const char *src)
int brix_journal_mark (brix_journal *j, const char *src)
void brix_journal_close (brix_journal *j)
Function Documentation
brix_journal_close()
void brix_journal_close (brix_journal * j)
Definition at line 144 of file xferjournal.c.
References brix_journal::done, brix_journal::fp, brix_journal::lock, and brix_journal::n.
Referenced by brix_journal_open(), and main().
brix_journal_has()
int brix_journal_has (const brix_journal * j, const char * src)
Definition at line 111 of file xferjournal.c.
References cmp_str(), brix_journal::done, and brix_journal::n.
Referenced by batch_worker(), and main().
brix_journal_mark()
int brix_journal_mark (brix_journal * j, const char * src)
Definition at line 120 of file xferjournal.c.
References brix_journal::fp, JOURNAL_LINE_MAX, and brix_journal::lock.
Referenced by batch_worker(), and main().
brix_journal_open()
brix_journal * brix_journal_open (const char * path, brix_status * st)
Definition at line 86 of file xferjournal.c.
References brix_journal_close(), brix_status_set(), brix_journal::fp, journal_load(), brix_journal::lock, XRDC_EIO, and XRDC_EPROTO.
Referenced by main().