nginx-xrootd: client/lib/cli/xferjournal.c File Reference
xferjournal.c File Reference
#include "cli/xferjournal.h"
#include <errno.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct brix_journal
Macros
#define JOURNAL_LINE_MAX 4096 /* longer lines are hostile/corrupt: skipped */
Functions
static int cmp_str (const void *a, const void *b)
static int done_append (brix_journal *j, const char *s)
static int journal_load (brix_journal *j, const char *path)
brix_journal * brix_journal_open (const char *path, brix_status *st)
int brix_journal_has (const brix_journal *j, const char *src)
int brix_journal_mark (brix_journal *j, const char *src)
void brix_journal_close (brix_journal *j)
Macro Definition Documentation
JOURNAL_LINE_MAX
#define JOURNAL_LINE_MAX 4096 /* longer lines are hostile/corrupt: skipped */
Definition at line 9 of file xferjournal.c.
Function Documentation
brix_journal_close()
void brix_journal_close (brix_journal * j)
Definition at line 144 of file xferjournal.c.
References brix_journal::done, brix_journal::fp, brix_journal::lock, and brix_journal::n.
Referenced by brix_journal_open(), and main().
brix_journal_has()
int brix_journal_has (const brix_journal * j, const char * src)
Definition at line 111 of file xferjournal.c.
References cmp_str(), brix_journal::done, and brix_journal::n.
Referenced by batch_worker(), and main().
brix_journal_mark()
int brix_journal_mark (brix_journal * j, const char * src)
Definition at line 120 of file xferjournal.c.
References brix_journal::fp, JOURNAL_LINE_MAX, and brix_journal::lock.
Referenced by batch_worker(), and main().
brix_journal_open()
brix_journal * brix_journal_open (const char * path, brix_status * st)
Definition at line 86 of file xferjournal.c.
References brix_journal_close(), brix_status_set(), brix_journal::fp, journal_load(), brix_journal::lock, XRDC_EIO, and XRDC_EPROTO.
Referenced by main().
cmp_str()
static int cmp_str (const void * a, const void * b) static
Definition at line 19 of file xferjournal.c.
Referenced by brix_journal_has(), and journal_load().
done_append()
static int done_append (brix_journal * j, const char * s) static
Definition at line 26 of file xferjournal.c.
References brix_journal::cap, brix_journal::done, brix_journal::n, and s.
Referenced by journal_load().
journal_load()
static int journal_load (brix_journal * j, const char * path) static
Definition at line 52 of file xferjournal.c.
References cmp_str(), brix_journal::done, done_append(), JOURNAL_LINE_MAX, and brix_journal::n.
Referenced by brix_journal_open().