nginx-xrootd: src/fs/xfer/xfer_ledger.c File Reference
xfer_ledger.c File Reference
#include "xfer.h"
#include "fs/path/path.h"
#include <fcntl.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
Functions
const char * brix_xfer_kind_str (brix_xfer_kind_t kind)
const char * brix_xfer_result_str (brix_xfer_result_t result)
static void xfer_audit_resolve_path (char *out, size_t outsz)
static int xfer_audit_fd_get (ngx_log_t *log)
void brix_xfer_ledger_record (const brix_xfer_audit_t *ev)
Variables
static int xfer_audit_fd = -1
static ngx_int_t xfer_audit_failed
Function Documentation
brix_xfer_kind_str()
const char * brix_xfer_kind_str (brix_xfer_kind_t kind)
Definition at line 38 of file xfer_ledger.c.
References BRIX_XFER_STAGE, BRIX_XFER_TAPE, BRIX_XFER_TPC, and BRIX_XFER_WT.
Referenced by brix_xfer_ledger_record().
brix_xfer_ledger_record()
void brix_xfer_ledger_record (const brix_xfer_audit_t * ev)
Definition at line 115 of file xfer_ledger.c.
References brix_sanitize_log_string(), brix_xfer_kind_str(), BRIX_XFER_OK, brix_xfer_result_str(), brix_xfer_audit_t::bytes, brix_xfer_audit_t::direction, brix_xfer_audit_t::kind, brix_xfer_audit_t::log, brix_xfer_audit_t::path, brix_xfer_audit_t::principal, brix_xfer_audit_t::result, brix_xfer_audit_t::sys_errno, and xfer_audit_fd_get().
Referenced by brix_xfer_finish().
brix_xfer_result_str()
const char * brix_xfer_result_str (brix_xfer_result_t result)
Definition at line 50 of file xfer_ledger.c.
References BRIX_XFER_AGENT_FAIL, BRIX_XFER_COMMIT_ERR, BRIX_XFER_DEFERRED, BRIX_XFER_DENIED, BRIX_XFER_DST_ERR, BRIX_XFER_OK, and BRIX_XFER_SRC_ERR.
Referenced by brix_xfer_ledger_record().
xfer_audit_fd_get()
static int xfer_audit_fd_get (ngx_log_t * log) static
Definition at line 89 of file xfer_ledger.c.
References log, open(), PATH_MAX, xfer_audit_failed, xfer_audit_fd, and xfer_audit_resolve_path().
Referenced by brix_xfer_ledger_record().
xfer_audit_resolve_path()
static void xfer_audit_resolve_path (char * out, size_t outsz) static
Definition at line 71 of file xfer_ledger.c.
Referenced by xfer_audit_fd_get().
Variable Documentation
xfer_audit_failed
ngx_int_t xfer_audit_failed static
Definition at line 67 of file xfer_ledger.c.
Referenced by xfer_audit_fd_get().
xfer_audit_fd
int xfer_audit_fd = -1 static
Definition at line 66 of file xfer_ledger.c.
Referenced by xfer_audit_fd_get().