nginx-xrootd: src/fs/xfer/xfer_core.c File Reference
xfer_core.c File Reference
#include "xfer.h"
Functions
void brix_xfer_finish (brix_xfer_kind_t kind, const char *direction, const char *path, const char *principal, size_t bytes, brix_xfer_result_t result, int sys_errno, ngx_log_t *log)
Function Documentation
brix_xfer_finish()
void brix_xfer_finish (brix_xfer_kind_t kind, const char * direction, const char * path, const char * principal, size_t bytes, brix_xfer_result_t result, int sys_errno, ngx_log_t * log)
Definition at line 25 of file xfer_core.c.
References brix_xfer_ledger_record(), brix_xfer_audit_t::kind, and log.
Referenced by brix_handle_close(), brix_vfs_staged_commit(), ngx_http_brix_webdav_tpc_handle_copy(), s3_commit_put(), stage_engine_run(), tpc_thread_done(), and webdav_tpc_handle_push().