nginx-xrootd: src/fs/meta/xmeta.c File Reference
xmeta.c File Reference
#include "xmeta.h"
#include "xmeta_internal.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
Typedefs
typedef char xmeta_store_size_check[sizeof(brix_xmeta_stock_store_t)==48 ? 1 :-1]
typedef char xmeta_astat_size_check[sizeof(brix_xmeta_astat_t)==56 ? 1 :-1]
Functions
uint64_t xmeta_nblocks (int64_t file_size, int64_t buffer_size)
size_t xmeta_bitmap_len (uint64_t nblocks)
int brix_xmeta_init (brix_xmeta_t *m, int64_t file_size, int64_t buffer_size)
void brix_xmeta_free (brix_xmeta_t *m)
void brix_xmeta_block_set (brix_xmeta_t *m, uint64_t i)
int brix_xmeta_block_test (const brix_xmeta_t *m, uint64_t i)
int brix_xmeta_complete (const brix_xmeta_t *m)
int brix_xmeta_digest_add (brix_xmeta_t *m, uint16_t alg, const void *val, uint16_t len)
int brix_xmeta_digest_set (brix_xmeta_t *m, uint16_t alg, const void *val, uint16_t len)
int brix_xmeta_digest_get (const brix_xmeta_t *m, uint32_t idx, uint16_t *alg, const uint8_t **val, uint16_t *len)
Typedef Documentation
xmeta_astat_size_check
typedef char xmeta_astat_size_check[ sizeof(brix_xmeta_astat_t)==56 ? 1 :-1]
Definition at line 26 of file xmeta.c.
xmeta_store_size_check
typedef char xmeta_store_size_check[ sizeof(brix_xmeta_stock_store_t)==48 ? 1 :-1]
Definition at line 24 of file xmeta.c.
Function Documentation
brix_xmeta_block_set()
void brix_xmeta_block_set (brix_xmeta_t * m, uint64_t i)
Definition at line 97 of file xmeta.c.
References brix_xmeta_t::bitmap.
Referenced by brix_cache_cinfo_record_block(), build_sample(), and test_stock_only().
brix_xmeta_block_test()
int brix_xmeta_block_test (const brix_xmeta_t * m, uint64_t i)
Definition at line 105 of file xmeta.c.
References brix_xmeta_t::bitmap, and brix_xmeta_t::nblocks.
Referenced by brix_xmeta_complete(), test_round_trip(), and test_stock_only().
brix_xmeta_complete()
int brix_xmeta_complete (const brix_xmeta_t * m)
Definition at line 114 of file xmeta.c.
References brix_xmeta_block_test(), and brix_xmeta_t::nblocks.
Referenced by test_round_trip().
brix_xmeta_digest_add()
int brix_xmeta_digest_add (brix_xmeta_t * m, uint16_t alg, const void * val, uint16_t len)
Definition at line 129 of file xmeta.c.
References alg, BRIX_XMETA_ERR, BRIX_XMETA_OK, brix_xmeta_t::digests, and brix_xmeta_t::digests_len.
Referenced by brix_xmeta_digest_set(), and build_sample().
brix_xmeta_digest_get()
int brix_xmeta_digest_get (const brix_xmeta_t * m, uint32_t idx, uint16_t * alg, const uint8_t ** val, uint16_t * len)
Definition at line 199 of file xmeta.c.
References alg, BRIX_XMETA_FOREIGN, BRIX_XMETA_OK, brix_xmeta_t::digests, and brix_xmeta_t::digests_len.
Referenced by check_digests(), and integrity_record_read().
brix_xmeta_digest_set()
int brix_xmeta_digest_set (brix_xmeta_t * m, uint16_t alg, const void * val, uint16_t len)
Definition at line 155 of file xmeta.c.
References alg, brix_xmeta_digest_add(), BRIX_XMETA_ERR, brix_xmeta_t::digests, and brix_xmeta_t::digests_len.
Referenced by integrity_record_write().
brix_xmeta_free()
void brix_xmeta_free (brix_xmeta_t * m)
Definition at line 83 of file xmeta.c.
References brix_xmeta_t::bitmap, brix_xmeta_t::blockcrc, and brix_xmeta_t::digests.
Referenced by brix_cache_cinfo_load(), brix_cache_cinfo_mark_clean(), brix_cache_cinfo_mark_dirty(), brix_cache_cinfo_record_block(), brix_cache_cinfo_store(), brix_cache_meta_read(), brix_cache_meta_touch(), brix_cache_meta_write(), brix_csi_close(), brix_csi_flush(), brix_csi_open(), brix_csi_verify_read(), brix_cstore_cinfo_load(), brix_cstore_cinfo_store(), brix_xmeta_init(), cinfo_rmw_load(), csi_flush_load_record(), csi_record_regeom(), encode_sample(), integrity_record_read(), integrity_record_write(), main(), test_corruption(), test_round_trip(), test_stock_only(), test_unknown_section(), xmeta_decode_bitmap_astat(), and xmeta_decode_ext_sections().
brix_xmeta_init()
int brix_xmeta_init (brix_xmeta_t * m, int64_t file_size, int64_t buffer_size)
Definition at line 50 of file xmeta.c.
References brix_xmeta_t::bitmap, brix_xmeta_t::blockcrc, BRIX_XMETA_ERR, brix_xmeta_free(), BRIX_XMETA_MAX_BLOCKS, BRIX_XMETA_OK, brix_xmeta_t::buffer_size, brix_xmeta_t::creation_time, brix_xmeta_t::file_size, brix_xmeta_t::have_blockcrc, brix_xmeta_t::have_state, brix_xmeta_t::nblocks, xmeta_bitmap_len(), and xmeta_nblocks().
Referenced by brix_cache_cinfo_to_xmeta(), brix_cache_meta_write(), build_sample(), csi_flush_load_record(), csi_record_regeom(), integrity_record_write(), and test_stock_only().
xmeta_bitmap_len()
size_t xmeta_bitmap_len (uint64_t nblocks)
Definition at line 42 of file xmeta.c.
Referenced by brix_xmeta_init(), xmeta_decode_bitmap_astat(), and xmeta_encode_plan().
xmeta_nblocks()
uint64_t xmeta_nblocks (int64_t file_size, int64_t buffer_size)
Definition at line 32 of file xmeta.c.
Referenced by brix_xmeta_init(), and xmeta_decode_stock_store().