nginx-xrootd: src/fs/meta/xmeta_encode.c File Reference
xmeta_encode.c File Reference
#include "xmeta.h"
#include "xmeta_internal.h"
#include "core/compat/crc32c.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct xmeta_encode_plan_t
Typedefs
typedef char xmeta_state_size_check[sizeof(xmeta_state_wire_t)==80 ? 1 :-1]
Functions
static void xmeta_put (uint8_t *buf, size_t *off, const void *src, size_t len)
static void xmeta_put_section (uint8_t *buf, size_t *off, uint16_t type, const void *payload, uint32_t plen)
static void xmeta_encode_plan (const brix_xmeta_t *m, xmeta_encode_plan_t *plan)
static void xmeta_encode_stock_prefix (const brix_xmeta_t *m, uint8_t *buf, size_t *off, size_t blen)
static void xmeta_encode_state_section (const brix_xmeta_t *m, uint8_t *buf, size_t *off)
static void xmeta_encode_origin_section (const brix_xmeta_t *m, uint8_t *buf, size_t *off)
static void xmeta_encode_blockcrc_section (const brix_xmeta_t *m, uint8_t *buf, size_t *off)
int brix_xmeta_encode (const brix_xmeta_t *m, uint8_t **out, size_t *out_len)
Typedef Documentation
xmeta_state_size_check
typedef char xmeta_state_size_check[ sizeof(xmeta_state_wire_t)==80 ? 1 :-1]
Definition at line 27 of file xmeta_encode.c.
Function Documentation
brix_xmeta_encode()
int brix_xmeta_encode (const brix_xmeta_t * m, uint8_t ** out, size_t * out_len)
Definition at line 267 of file xmeta_encode.c.
References brix_xmeta_t::bitmap, xmeta_encode_plan_t::blen, xmeta_encode_plan_t::blockcrc_plen, BRIX_XMETA_ERR, BRIX_XMETA_EXT_MAGIC, BRIX_XMETA_EXT_VERSION, BRIX_XMETA_OK, BRIX_XMETA_SEC_DIGEST, brix_xmeta_t::buffer_size, xmeta_encode_plan_t::cap, brix_xmeta_t::digests, brix_xmeta_t::digests_len, xmeta_encode_plan_t::have_origin, brix_xmeta_t::have_state, xmeta_encode_plan_t::nsec, xmeta_encode_blockcrc_section(), xmeta_encode_origin_section(), xmeta_encode_plan(), xmeta_encode_state_section(), xmeta_encode_stock_prefix(), xmeta_put(), and xmeta_put_section().
Referenced by brix_xmeta_path_save(), brix_xmeta_save(), encode_sample(), test_round_trip(), and test_stock_only().
xmeta_encode_blockcrc_section()
static void xmeta_encode_blockcrc_section (const brix_xmeta_t * m, uint8_t * buf, size_t * off) static
Definition at line 242 of file xmeta_encode.c.
References brix_xmeta_t::blockcrc, brix_crc32c_value(), BRIX_XMETA_SEC_BLOCKCRC, brix_xmeta_t::buffer_size, brix_xmeta_t::nblocks, and xmeta_put().
Referenced by brix_xmeta_encode().
xmeta_encode_origin_section()
static void xmeta_encode_origin_section (const brix_xmeta_t * m, uint8_t * buf, size_t * off) static
Definition at line 209 of file xmeta_encode.c.
References BRIX_XMETA_SEC_ORIGIN, brix_xmeta_t::cks_alg, brix_xmeta_t::cks_alg_len, brix_xmeta_t::cks_hex, brix_xmeta_t::cks_len, brix_xmeta_t::etag, brix_xmeta_t::etag_len, XMETA_ORIGIN_FIXED, and xmeta_put_section().
Referenced by brix_xmeta_encode().
xmeta_encode_plan()
static void xmeta_encode_plan (const brix_xmeta_t * m, xmeta_encode_plan_t * plan) static
Definition at line 87 of file xmeta_encode.c.
References brix_xmeta_t::astat, brix_xmeta_t::astat_count, xmeta_encode_plan_t::blen, brix_xmeta_t::blockcrc, xmeta_encode_plan_t::blockcrc_plen, xmeta_encode_plan_t::cap, brix_xmeta_t::cks_alg_len, brix_xmeta_t::cks_len, brix_xmeta_t::digests, brix_xmeta_t::digests_len, brix_xmeta_t::etag_len, brix_xmeta_t::have_blockcrc, xmeta_encode_plan_t::have_blockcrc, xmeta_encode_plan_t::have_origin, brix_xmeta_t::have_state, brix_xmeta_t::nblocks, xmeta_encode_plan_t::nsec, xmeta_encode_plan_t::origin_plen, xmeta_bitmap_len(), and XMETA_ORIGIN_FIXED.
Referenced by brix_xmeta_encode().
xmeta_encode_state_section()
static void xmeta_encode_state_section (const brix_xmeta_t * m, uint8_t * buf, size_t * off) static
Definition at line 173 of file xmeta_encode.c.
References BRIX_XMETA_SEC_STATE, brix_xmeta_t::bytes_flushed, xmeta_state_wire_t::bytes_flushed, brix_xmeta_t::dirty_hi, xmeta_state_wire_t::dirty_hi, brix_xmeta_t::dirty_lo, xmeta_state_wire_t::dirty_lo, brix_xmeta_t::dirty_since, xmeta_state_wire_t::dirty_since, brix_xmeta_t::expires_at, xmeta_state_wire_t::expires_at, brix_xmeta_t::filled_at, xmeta_state_wire_t::filled_at, brix_xmeta_t::flush_gen, xmeta_state_wire_t::flush_gen, brix_xmeta_t::last_flush, xmeta_state_wire_t::last_flush, brix_xmeta_t::mode, xmeta_state_wire_t::mode, brix_xmeta_t::origin_mtime, xmeta_state_wire_t::origin_mtime, brix_xmeta_t::state_flags, xmeta_state_wire_t::state_flags, and xmeta_put_section().
Referenced by brix_xmeta_encode().
xmeta_encode_stock_prefix()
static void xmeta_encode_stock_prefix (const brix_xmeta_t * m, uint8_t * buf, size_t * off, size_t blen) static
Definition at line 130 of file xmeta_encode.c.
References brix_xmeta_stock_store_t::access_cnt, brix_xmeta_t::access_cnt, brix_xmeta_t::astat, brix_xmeta_t::astat_count, brix_xmeta_stock_store_t::astat_size, brix_xmeta_t::bitmap, brix_crc32c_extend(), brix_crc32c_value(), BRIX_XMETA_STOCK_VERSION, brix_xmeta_stock_store_t::buffer_size, brix_xmeta_t::buffer_size, brix_xmeta_stock_store_t::creation_time, brix_xmeta_t::creation_time, brix_xmeta_stock_store_t::file_size, brix_xmeta_t::file_size, brix_xmeta_stock_store_t::no_cksum_time, brix_xmeta_t::no_cksum_time, brix_xmeta_stock_store_t::status_raw, brix_xmeta_t::status_raw, and xmeta_put().
Referenced by brix_xmeta_encode().
xmeta_put()
static void xmeta_put (uint8_t * buf, size_t * off, const void * src, size_t len) static
Definition at line 34 of file xmeta_encode.c.
Referenced by brix_xmeta_encode(), xmeta_encode_blockcrc_section(), xmeta_encode_stock_prefix(), and xmeta_put_section().
xmeta_put_section()
static void xmeta_put_section (uint8_t * buf, size_t * off, uint16_t type, const void * payload, uint32_t plen) static
Definition at line 43 of file xmeta_encode.c.
References brix_crc32c_value(), and xmeta_put().
Referenced by brix_xmeta_encode(), xmeta_encode_origin_section(), and xmeta_encode_state_section().