nginx-xrootd: src/fs/meta/xmeta_path.h File Reference
xmeta_path.h File Reference
#include "xmeta.h"
Macros
#define BRIX_XMETA_PATH_XATTR "user.xrd.cinfo"
#define BRIX_XMETA_PATH_SIDECAR ".cinfo"
#define BRIX_XMETA_PATH_XATTR_MAX (64 * 1024)
Functions
int brix_xmeta_sidecar_path (char *dst, size_t cap, const char *path)
int brix_xmeta_path_load (const char *path, brix_xmeta_t *xm)
int brix_xmeta_path_save (const char *path, const brix_xmeta_t *xm)
int brix_xmeta_path_remove (const char *path)
int brix_xmeta_path_lock (const char *path)
void brix_xmeta_path_unlock (int lockfd)
Macro Definition Documentation
BRIX_XMETA_PATH_SIDECAR
#define BRIX_XMETA_PATH_SIDECAR ".cinfo"
Definition at line 28 of file xmeta_path.h.
BRIX_XMETA_PATH_XATTR
#define BRIX_XMETA_PATH_XATTR "user.xrd.cinfo"
Definition at line 27 of file xmeta_path.h.
BRIX_XMETA_PATH_XATTR_MAX
#define BRIX_XMETA_PATH_XATTR_MAX (64 * 1024)
Definition at line 29 of file xmeta_path.h.
Function Documentation
brix_xmeta_path_load()
int brix_xmeta_path_load (const char * path, brix_xmeta_t * xm)
Definition at line 162 of file xmeta_path.c.
References BRIX_XMETA_ERR, BRIX_XMETA_FOREIGN, brix_xmeta_sidecar_path(), close(), open(), PATH_MAX, xmeta_path_load_from_xattr(), and xmeta_path_read_sidecar_fd().
Referenced by brix_cache_meta_read(), brix_cache_meta_touch(), brix_cache_meta_write(), brix_csi_open(), brix_csi_verify_read(), cinfo_xmeta_read(), csi_flush_load_record(), integrity_record_read(), integrity_record_write(), and main().
brix_xmeta_path_lock()
int brix_xmeta_path_lock (const char * path)
Definition at line 356 of file xmeta_path.c.
References brix_xmeta_sidecar_path(), close(), open(), and PATH_MAX.
Referenced by brix_cache_meta_touch(), brix_cache_meta_write(), brix_csi_flush(), cinfo_rmw_lock(), and integrity_record_write().
brix_xmeta_path_remove()
int brix_xmeta_path_remove (const char * path)
Definition at line 341 of file xmeta_path.c.
References BRIX_XMETA_OK, BRIX_XMETA_PATH_XATTR, brix_xmeta_sidecar_path(), and PATH_MAX.
Referenced by main().
brix_xmeta_path_save()
int brix_xmeta_path_save (const char * path, const brix_xmeta_t * xm)
Definition at line 302 of file xmeta_path.c.
References brix_xmeta_encode(), BRIX_XMETA_ERR, BRIX_XMETA_OK, BRIX_XMETA_PATH_XATTR, brix_xmeta_sidecar_path(), PATH_MAX, xmeta_path_save_to_xattr(), and xmeta_path_write_sidecar().
Referenced by brix_cache_meta_touch(), brix_cache_meta_write(), brix_csi_flush(), cinfo_xmeta_write(), and integrity_record_write().
brix_xmeta_path_unlock()
void brix_xmeta_path_unlock (int lockfd)
Definition at line 384 of file xmeta_path.c.
References close().
Referenced by brix_cache_meta_touch(), brix_cache_meta_write(), brix_csi_flush(), cinfo_rmw_unlock(), and integrity_record_write().
brix_xmeta_sidecar_path()
int brix_xmeta_sidecar_path (char * dst, size_t cap, const char * path)
Definition at line 20 of file xmeta_path.c.
References BRIX_XMETA_PATH_SIDECAR.
Referenced by brix_xmeta_path_load(), brix_xmeta_path_lock(), brix_xmeta_path_remove(), and brix_xmeta_path_save().