nginx-xrootd: src/fs/meta/xmeta.h File Reference
xmeta.h File Reference
#include <stddef.h>
#include <stdint.h>
Data Structures
struct brix_xmeta_stock_store_t
struct brix_xmeta_astat_t
struct brix_xmeta_t
Macros
#define BRIX_XMETA_STOCK_VERSION 4
#define BRIX_XMETA_EXT_MAGIC 0x31584358u /* "XCX1" little-endian */
#define BRIX_XMETA_EXT_VERSION 1
#define BRIX_XMETA_SEC_STATE 0x0001
#define BRIX_XMETA_SEC_DIGEST 0x0002
#define BRIX_XMETA_SEC_BLOCKCRC 0x0003
#define BRIX_XMETA_SEC_ORIGIN 0x0004
#define BRIX_XMETA_F_VERIFIED 0x0001u /* contents checked vs digest */
#define BRIX_XMETA_F_EXPIRES 0x0002u /* expires_at is armed */
#define BRIX_XMETA_CRC_UNSET 0u
#define BRIX_XMETA_MAX_BLOCKS (1ull << 26)
#define BRIX_XMETA_MAX_SECTION (BRIX_XMETA_MAX_BLOCKS * 4 + 64)
#define BRIX_XMETA_ALG_ADLER32 1
#define BRIX_XMETA_ALG_CRC32C 2
#define BRIX_XMETA_ALG_MD5 3
#define BRIX_XMETA_ALG_SHA256 4
#define BRIX_XMETA_ALG_CRC64XZ 5
#define BRIX_XMETA_ALG_CRC64NVME 6
#define BRIX_XMETA_ALG_CRC32 7
#define BRIX_XMETA_ALG_SHA1 8
#define BRIX_XMETA_ALG_ZCRC32 9
#define BRIX_XMETA_OK 0
#define BRIX_XMETA_ERR (-1) /* hard error (errno set) */
#define BRIX_XMETA_FOREIGN
Functions
int brix_xmeta_init (brix_xmeta_t *m, int64_t file_size, int64_t buffer_size)
void brix_xmeta_free (brix_xmeta_t *m)
int brix_xmeta_encode (const brix_xmeta_t *m, uint8_t **out, size_t *out_len)
int brix_xmeta_decode (const uint8_t *buf, size_t len, brix_xmeta_t *m)
void brix_xmeta_block_set (brix_xmeta_t *m, uint64_t i)
int brix_xmeta_block_test (const brix_xmeta_t *m, uint64_t i)
int brix_xmeta_complete (const brix_xmeta_t *m)
int brix_xmeta_digest_add (brix_xmeta_t *m, uint16_t alg, const void *val, uint16_t len)
int brix_xmeta_digest_set (brix_xmeta_t *m, uint16_t alg, const void *val, uint16_t len)
int brix_xmeta_digest_get (const brix_xmeta_t *m, uint32_t idx, uint16_t *alg, const uint8_t **val, uint16_t *len)
Macro Definition Documentation
BRIX_XMETA_ALG_ADLER32
#define BRIX_XMETA_ALG_ADLER32 1
Definition at line 81 of file xmeta.h.
BRIX_XMETA_ALG_CRC32
#define BRIX_XMETA_ALG_CRC32 7
Definition at line 87 of file xmeta.h.
BRIX_XMETA_ALG_CRC32C
#define BRIX_XMETA_ALG_CRC32C 2
Definition at line 82 of file xmeta.h.
BRIX_XMETA_ALG_CRC64NVME
#define BRIX_XMETA_ALG_CRC64NVME 6
Definition at line 86 of file xmeta.h.
BRIX_XMETA_ALG_CRC64XZ
#define BRIX_XMETA_ALG_CRC64XZ 5
Definition at line 85 of file xmeta.h.
BRIX_XMETA_ALG_MD5
#define BRIX_XMETA_ALG_MD5 3
Definition at line 83 of file xmeta.h.
BRIX_XMETA_ALG_SHA1
#define BRIX_XMETA_ALG_SHA1 8
Definition at line 88 of file xmeta.h.
BRIX_XMETA_ALG_SHA256
#define BRIX_XMETA_ALG_SHA256 4
Definition at line 84 of file xmeta.h.
BRIX_XMETA_ALG_ZCRC32
#define BRIX_XMETA_ALG_ZCRC32 9
Definition at line 89 of file xmeta.h.
BRIX_XMETA_CRC_UNSET
#define BRIX_XMETA_CRC_UNSET 0u
Definition at line 74 of file xmeta.h.
BRIX_XMETA_ERR
#define BRIX_XMETA_ERR (-1) /* hard error (errno set) */
Definition at line 141 of file xmeta.h.
BRIX_XMETA_EXT_MAGIC
#define BRIX_XMETA_EXT_MAGIC 0x31584358u /* "XCX1" little-endian */
Definition at line 60 of file xmeta.h.
BRIX_XMETA_EXT_VERSION
#define BRIX_XMETA_EXT_VERSION 1
Definition at line 61 of file xmeta.h.
BRIX_XMETA_F_EXPIRES
#define BRIX_XMETA_F_EXPIRES 0x0002u /* expires_at is armed */
Definition at line 70 of file xmeta.h.
BRIX_XMETA_F_VERIFIED
#define BRIX_XMETA_F_VERIFIED 0x0001u /* contents checked vs digest */
Definition at line 69 of file xmeta.h.
BRIX_XMETA_FOREIGN
#define BRIX_XMETA_FOREIGN
Value:
                                       (-2)   /* not an xmeta/cinfo record (treat as
                                       "nothing recorded")                   */
Definition at line 142 of file xmeta.h.
BRIX_XMETA_MAX_BLOCKS
#define BRIX_XMETA_MAX_BLOCKS (1ull << 26)
Definition at line 77 of file xmeta.h.
BRIX_XMETA_MAX_SECTION
#define BRIX_XMETA_MAX_SECTION (BRIX_XMETA_MAX_BLOCKS * 4 + 64)
Definition at line 78 of file xmeta.h.
BRIX_XMETA_OK
#define BRIX_XMETA_OK 0
Definition at line 140 of file xmeta.h.
BRIX_XMETA_SEC_BLOCKCRC
#define BRIX_XMETA_SEC_BLOCKCRC 0x0003
Definition at line 65 of file xmeta.h.
BRIX_XMETA_SEC_DIGEST
#define BRIX_XMETA_SEC_DIGEST 0x0002
Definition at line 64 of file xmeta.h.
BRIX_XMETA_SEC_ORIGIN
#define BRIX_XMETA_SEC_ORIGIN 0x0004
Definition at line 66 of file xmeta.h.
BRIX_XMETA_SEC_STATE
#define BRIX_XMETA_SEC_STATE 0x0001
Definition at line 63 of file xmeta.h.
BRIX_XMETA_STOCK_VERSION
#define BRIX_XMETA_STOCK_VERSION 4
Definition at line 34 of file xmeta.h.
Function Documentation
brix_xmeta_block_set()
void brix_xmeta_block_set (brix_xmeta_t * m, uint64_t i)
Definition at line 97 of file xmeta.c.
References brix_xmeta_t::bitmap.
Referenced by brix_cache_cinfo_record_block(), build_sample(), and test_stock_only().
brix_xmeta_block_test()
int brix_xmeta_block_test (const brix_xmeta_t * m, uint64_t i)
Definition at line 105 of file xmeta.c.
References brix_xmeta_t::bitmap, and brix_xmeta_t::nblocks.
Referenced by brix_xmeta_complete(), test_round_trip(), and test_stock_only().
brix_xmeta_complete()
int brix_xmeta_complete (const brix_xmeta_t * m)
Definition at line 114 of file xmeta.c.
References brix_xmeta_block_test(), and brix_xmeta_t::nblocks.
Referenced by test_round_trip().
brix_xmeta_decode()
int brix_xmeta_decode (const uint8_t * buf, size_t len, brix_xmeta_t * m)
Definition at line 412 of file xmeta_decode.c.
References BRIX_XMETA_ERR, BRIX_XMETA_OK, xmeta_decode_bitmap_astat(), xmeta_decode_ext_sections(), and xmeta_decode_stock_store().
Referenced by brix_xmeta_load(), test_corruption(), test_foreign_inputs(), test_round_trip(), test_stock_only(), test_unknown_section(), xmeta_load_from_xattr(), xmeta_path_load_from_xattr(), and xmeta_path_read_sidecar_fd().
brix_xmeta_digest_add()
int brix_xmeta_digest_add (brix_xmeta_t * m, uint16_t alg, const void * val, uint16_t len)
Definition at line 129 of file xmeta.c.
References alg, BRIX_XMETA_ERR, BRIX_XMETA_OK, brix_xmeta_t::digests, and brix_xmeta_t::digests_len.
Referenced by brix_xmeta_digest_set(), and build_sample().
brix_xmeta_digest_get()
int brix_xmeta_digest_get (const brix_xmeta_t * m, uint32_t idx, uint16_t * alg, const uint8_t ** val, uint16_t * len)
Definition at line 199 of file xmeta.c.
References alg, BRIX_XMETA_FOREIGN, BRIX_XMETA_OK, brix_xmeta_t::digests, and brix_xmeta_t::digests_len.
Referenced by check_digests(), and integrity_record_read().
brix_xmeta_digest_set()
int brix_xmeta_digest_set (brix_xmeta_t * m, uint16_t alg, const void * val, uint16_t len)
Definition at line 155 of file xmeta.c.
References alg, brix_xmeta_digest_add(), BRIX_XMETA_ERR, brix_xmeta_t::digests, and brix_xmeta_t::digests_len.
Referenced by integrity_record_write().
brix_xmeta_encode()
int brix_xmeta_encode (const brix_xmeta_t * m, uint8_t ** out, size_t * out_len)
Definition at line 267 of file xmeta_encode.c.
References brix_xmeta_t::bitmap, xmeta_encode_plan_t::blen, xmeta_encode_plan_t::blockcrc_plen, BRIX_XMETA_ERR, BRIX_XMETA_EXT_MAGIC, BRIX_XMETA_EXT_VERSION, BRIX_XMETA_OK, BRIX_XMETA_SEC_DIGEST, brix_xmeta_t::buffer_size, xmeta_encode_plan_t::cap, brix_xmeta_t::digests, brix_xmeta_t::digests_len, xmeta_encode_plan_t::have_origin, brix_xmeta_t::have_state, xmeta_encode_plan_t::nsec, xmeta_encode_blockcrc_section(), xmeta_encode_origin_section(), xmeta_encode_plan(), xmeta_encode_state_section(), xmeta_encode_stock_prefix(), xmeta_put(), and xmeta_put_section().
Referenced by brix_xmeta_path_save(), brix_xmeta_save(), encode_sample(), test_round_trip(), and test_stock_only().
brix_xmeta_free()
void brix_xmeta_free (brix_xmeta_t * m)
Definition at line 83 of file xmeta.c.
References brix_xmeta_t::bitmap, brix_xmeta_t::blockcrc, and brix_xmeta_t::digests.
Referenced by brix_cache_cinfo_load(), brix_cache_cinfo_mark_clean(), brix_cache_cinfo_mark_dirty(), brix_cache_cinfo_record_block(), brix_cache_cinfo_store(), brix_cache_meta_read(), brix_cache_meta_touch(), brix_cache_meta_write(), brix_csi_close(), brix_csi_flush(), brix_csi_open(), brix_csi_verify_read(), brix_cstore_cinfo_load(), brix_cstore_cinfo_store(), brix_xmeta_init(), cinfo_rmw_load(), csi_flush_load_record(), csi_record_regeom(), encode_sample(), integrity_record_read(), integrity_record_write(), main(), test_corruption(), test_round_trip(), test_stock_only(), test_unknown_section(), xmeta_decode_bitmap_astat(), and xmeta_decode_ext_sections().
brix_xmeta_init()
int brix_xmeta_init (brix_xmeta_t * m, int64_t file_size, int64_t buffer_size)
Definition at line 50 of file xmeta.c.
References brix_xmeta_t::bitmap, brix_xmeta_t::blockcrc, BRIX_XMETA_ERR, brix_xmeta_free(), BRIX_XMETA_MAX_BLOCKS, BRIX_XMETA_OK, brix_xmeta_t::buffer_size, brix_xmeta_t::creation_time, brix_xmeta_t::file_size, brix_xmeta_t::have_blockcrc, brix_xmeta_t::have_state, brix_xmeta_t::nblocks, xmeta_bitmap_len(), and xmeta_nblocks().
Referenced by brix_cache_cinfo_to_xmeta(), brix_cache_meta_write(), build_sample(), csi_flush_load_record(), csi_record_regeom(), integrity_record_write(), and test_stock_only().