nginx-xrootd: src/fs/meta/xmeta_decode.c File Reference
xmeta_decode.c File Reference
#include "xmeta.h"
#include "xmeta_internal.h"
#include "core/compat/crc32c.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
Functions
static int xmeta_get (const uint8_t *buf, size_t len, size_t *off, void *dst, size_t n)
static int xmeta_decode_state (brix_xmeta_t *m, const uint8_t *p, uint32_t plen)
static int xmeta_decode_origin (brix_xmeta_t *m, const uint8_t *p, uint32_t plen)
static int xmeta_decode_digest (brix_xmeta_t *m, const uint8_t *p, uint32_t plen)
static int xmeta_decode_blockcrc (brix_xmeta_t *m, const uint8_t *p, uint32_t plen)
static int xmeta_decode_section (brix_xmeta_t *m, uint16_t type, const uint8_t *p, uint32_t plen)
static int xmeta_decode_stock_store (const uint8_t *buf, size_t len, size_t *off, brix_xmeta_t *m)
static int xmeta_decode_bitmap_astat (const uint8_t *buf, size_t len, size_t *off, brix_xmeta_t *m)
static int xmeta_decode_ext_sections (const uint8_t *buf, size_t len, size_t *off, brix_xmeta_t *m)
int brix_xmeta_decode (const uint8_t *buf, size_t len, brix_xmeta_t *m)
Function Documentation
brix_xmeta_decode()
int brix_xmeta_decode (const uint8_t * buf, size_t len, brix_xmeta_t * m)
Definition at line 412 of file xmeta_decode.c.
References BRIX_XMETA_ERR, BRIX_XMETA_OK, xmeta_decode_bitmap_astat(), xmeta_decode_ext_sections(), and xmeta_decode_stock_store().
Referenced by brix_xmeta_load(), test_corruption(), test_foreign_inputs(), test_round_trip(), test_stock_only(), test_unknown_section(), xmeta_load_from_xattr(), xmeta_path_load_from_xattr(), and xmeta_path_read_sidecar_fd().
xmeta_decode_bitmap_astat()
static int xmeta_decode_bitmap_astat (const uint8_t * buf, size_t len, size_t * off, brix_xmeta_t * m) static
Definition at line 295 of file xmeta_decode.c.
References brix_xmeta_t::astat, brix_xmeta_t::bitmap, brix_crc32c_extend(), brix_crc32c_value(), BRIX_XMETA_ERR, BRIX_XMETA_FOREIGN, brix_xmeta_free(), BRIX_XMETA_OK, brix_xmeta_t::nblocks, xmeta_bitmap_len(), and xmeta_get().
Referenced by brix_xmeta_decode().
xmeta_decode_blockcrc()
static int xmeta_decode_blockcrc (brix_xmeta_t * m, const uint8_t * p, uint32_t plen) static
Definition at line 162 of file xmeta_decode.c.
References brix_xmeta_t::blockcrc, BRIX_XMETA_ERR, BRIX_XMETA_OK, brix_xmeta_t::have_blockcrc, and brix_xmeta_t::nblocks.
Referenced by xmeta_decode_section().
xmeta_decode_digest()
static int xmeta_decode_digest (brix_xmeta_t * m, const uint8_t * p, uint32_t plen) static
Definition at line 130 of file xmeta_decode.c.
References BRIX_XMETA_ERR, BRIX_XMETA_OK, brix_xmeta_t::digests, and brix_xmeta_t::digests_len.
Referenced by xmeta_decode_section().
xmeta_decode_ext_sections()
static int xmeta_decode_ext_sections (const uint8_t * buf, size_t len, size_t * off, brix_xmeta_t * m) static
Definition at line 359 of file xmeta_decode.c.
References brix_crc32c_value(), BRIX_XMETA_ERR, BRIX_XMETA_EXT_MAGIC, brix_xmeta_free(), BRIX_XMETA_MAX_SECTION, BRIX_XMETA_OK, xmeta_decode_section(), and xmeta_get().
Referenced by brix_xmeta_decode().
xmeta_decode_origin()
static int xmeta_decode_origin (brix_xmeta_t * m, const uint8_t * p, uint32_t plen) static
Definition at line 93 of file xmeta_decode.c.
References BRIX_XMETA_ERR, BRIX_XMETA_OK, brix_xmeta_t::cks_alg, brix_xmeta_t::cks_alg_len, brix_xmeta_t::cks_hex, brix_xmeta_t::cks_len, brix_xmeta_t::etag, brix_xmeta_t::etag_len, and XMETA_ORIGIN_FIXED.
Referenced by xmeta_decode_section().
xmeta_decode_section()
static int xmeta_decode_section (brix_xmeta_t * m, uint16_t type, const uint8_t * p, uint32_t plen) static
Definition at line 195 of file xmeta_decode.c.
References BRIX_XMETA_OK, BRIX_XMETA_SEC_BLOCKCRC, BRIX_XMETA_SEC_DIGEST, BRIX_XMETA_SEC_ORIGIN, BRIX_XMETA_SEC_STATE, xmeta_decode_blockcrc(), xmeta_decode_digest(), xmeta_decode_origin(), and xmeta_decode_state().
Referenced by xmeta_decode_ext_sections().
xmeta_decode_state()
static int xmeta_decode_state (brix_xmeta_t * m, const uint8_t * p, uint32_t plen) static
Definition at line 53 of file xmeta_decode.c.
References BRIX_XMETA_ERR, BRIX_XMETA_OK, brix_xmeta_t::bytes_flushed, xmeta_state_wire_t::bytes_flushed, brix_xmeta_t::dirty_hi, xmeta_state_wire_t::dirty_hi, brix_xmeta_t::dirty_lo, xmeta_state_wire_t::dirty_lo, brix_xmeta_t::dirty_since, xmeta_state_wire_t::dirty_since, brix_xmeta_t::expires_at, xmeta_state_wire_t::expires_at, brix_xmeta_t::filled_at, xmeta_state_wire_t::filled_at, brix_xmeta_t::flush_gen, xmeta_state_wire_t::flush_gen, brix_xmeta_t::have_state, brix_xmeta_t::last_flush, xmeta_state_wire_t::last_flush, brix_xmeta_t::mode, xmeta_state_wire_t::mode, brix_xmeta_t::origin_mtime, xmeta_state_wire_t::origin_mtime, brix_xmeta_t::state_flags, and xmeta_state_wire_t::state_flags.
Referenced by xmeta_decode_section().
xmeta_decode_stock_store()
static int xmeta_decode_stock_store (const uint8_t * buf, size_t len, size_t * off, brix_xmeta_t * m) static
Definition at line 235 of file xmeta_decode.c.
References brix_xmeta_stock_store_t::access_cnt, brix_xmeta_t::access_cnt, brix_xmeta_t::astat_count, brix_xmeta_stock_store_t::astat_size, brix_crc32c_value(), BRIX_XMETA_ERR, BRIX_XMETA_FOREIGN, BRIX_XMETA_MAX_BLOCKS, BRIX_XMETA_OK, BRIX_XMETA_STOCK_VERSION, brix_xmeta_stock_store_t::buffer_size, brix_xmeta_t::buffer_size, brix_xmeta_stock_store_t::creation_time, brix_xmeta_t::creation_time, brix_xmeta_stock_store_t::file_size, brix_xmeta_t::file_size, brix_xmeta_t::nblocks, brix_xmeta_stock_store_t::no_cksum_time, brix_xmeta_t::no_cksum_time, brix_xmeta_stock_store_t::status_raw, brix_xmeta_t::status_raw, xmeta_get(), and xmeta_nblocks().
Referenced by brix_xmeta_decode().
xmeta_get()
static int xmeta_get (const uint8_t * buf, size_t len, size_t * off, void * dst, size_t n) static
Definition at line 29 of file xmeta_decode.c.
Referenced by xmeta_decode_bitmap_astat(), xmeta_decode_ext_sections(), and xmeta_decode_stock_store().