nginx-xrootd: src/fs/meta/xmeta_carrier.c File Reference
xmeta_carrier.c File Reference
#include "xmeta_carrier.h"
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
static int xmeta_sidecar_key (const char *key, char *out, size_t cap)
static int xmeta_xattr_unfit (int err)
static ngx_int_t xmeta_sidecar_write (brix_sd_instance_t *store, const char *key, const uint8_t *buf, size_t len)
static void xmeta_obj_close (brix_sd_instance_t *store, brix_sd_obj_t *obj)
static int xmeta_read_buf_ensure (uint8_t **bufp, size_t *capp, size_t got)
static ngx_int_t xmeta_obj_slurp (brix_sd_instance_t *store, brix_sd_obj_t *obj, uint8_t **out, size_t *out_len)
static ngx_int_t xmeta_sidecar_read (brix_sd_instance_t *store, const char *key, uint8_t **out, size_t *out_len)
ngx_int_t brix_xmeta_save (brix_sd_instance_t *store, const char *key, const brix_xmeta_t *m)
static ngx_int_t xmeta_decode_rc (int drc)
static ngx_int_t xmeta_load_from_xattr (brix_sd_instance_t *store, const char *key, brix_xmeta_t *m)
ngx_int_t brix_xmeta_load (brix_sd_instance_t *store, const char *key, brix_xmeta_t *m)
ngx_int_t brix_xmeta_remove (brix_sd_instance_t *store, const char *key)
Function Documentation
brix_xmeta_load()
ngx_int_t brix_xmeta_load (brix_sd_instance_t * store, const char * key, brix_xmeta_t * m)
Definition at line 354 of file xmeta_carrier.c.
References brix_xmeta_decode(), key, xmeta_decode_rc(), xmeta_load_from_xattr(), and xmeta_sidecar_read().
Referenced by brix_cstore_cinfo_load().
brix_xmeta_remove()
ngx_int_t brix_xmeta_remove (brix_sd_instance_t * store, const char * key)
Definition at line 383 of file xmeta_carrier.c.
References BRIX_XMETA_XATTR_NAME, key, PATH_MAX, and xmeta_sidecar_key().
Referenced by brix_cstore_evict().
brix_xmeta_save()
ngx_int_t brix_xmeta_save (brix_sd_instance_t * store, const char * key, const brix_xmeta_t * m)
Definition at line 229 of file xmeta_carrier.c.
References brix_xmeta_encode(), BRIX_XMETA_OK, BRIX_XMETA_XATTR_MAX, BRIX_XMETA_XATTR_NAME, key, xmeta_sidecar_write(), and xmeta_xattr_unfit().
Referenced by brix_cstore_cinfo_store().
xmeta_decode_rc()
static ngx_int_t xmeta_decode_rc (int drc) static
Definition at line 289 of file xmeta_carrier.c.
References BRIX_XMETA_FOREIGN, and BRIX_XMETA_OK.
Referenced by brix_xmeta_load(), and xmeta_load_from_xattr().
xmeta_load_from_xattr()
static ngx_int_t xmeta_load_from_xattr (brix_sd_instance_t * store, const char * key, brix_xmeta_t * m) static
Definition at line 319 of file xmeta_carrier.c.
References brix_xmeta_decode(), BRIX_XMETA_XATTR_MAX, BRIX_XMETA_XATTR_NAME, ENOATTR, key, xmeta_decode_rc(), and xmeta_xattr_unfit().
Referenced by brix_xmeta_load().
xmeta_obj_close()
static void xmeta_obj_close (brix_sd_instance_t * store, brix_sd_obj_t * obj) static
Definition at line 98 of file xmeta_carrier.c.
Referenced by xmeta_sidecar_read().
xmeta_obj_slurp()
static ngx_int_t xmeta_obj_slurp (brix_sd_instance_t * store, brix_sd_obj_t * obj, uint8_t ** out, size_t * out_len) static
Definition at line 163 of file xmeta_carrier.c.
References xmeta_read_buf_ensure().
Referenced by xmeta_sidecar_read().
xmeta_read_buf_ensure()
static int xmeta_read_buf_ensure (uint8_t ** bufp, size_t * capp, size_t got) static
Definition at line 124 of file xmeta_carrier.c.
Referenced by xmeta_obj_slurp().
xmeta_sidecar_key()
static int xmeta_sidecar_key (const char * key, char * out, size_t cap) static
Definition at line 16 of file xmeta_carrier.c.
References BRIX_XMETA_SIDECAR_SUFFIX, and key.
Referenced by brix_xmeta_remove(), xmeta_sidecar_read(), and xmeta_sidecar_write().
xmeta_sidecar_read()
static ngx_int_t xmeta_sidecar_read (brix_sd_instance_t * store, const char * key, uint8_t ** out, size_t * out_len) static
Definition at line 200 of file xmeta_carrier.c.
References BRIX_SD_O_READ, key, PATH_MAX, xmeta_obj_close(), xmeta_obj_slurp(), and xmeta_sidecar_key().
Referenced by brix_xmeta_load().
xmeta_sidecar_write()
static ngx_int_t xmeta_sidecar_write (brix_sd_instance_t * store, const char * key, const uint8_t * buf, size_t len) static
Definition at line 40 of file xmeta_carrier.c.
References key, PATH_MAX, and xmeta_sidecar_key().
Referenced by brix_xmeta_save().
xmeta_xattr_unfit()
static int xmeta_xattr_unfit (int err) static
Definition at line 25 of file xmeta_carrier.c.
Referenced by brix_xmeta_save(), and xmeta_load_from_xattr().