nginx-xrootd: src/fs/meta/xmeta_carrier.h File Reference
xmeta_carrier.h File Reference
#include <ngx_core.h>
#include "xmeta.h"
#include "fs/backend/sd.h"
Macros
#define BRIX_XMETA_XATTR_NAME "user.xrd.cinfo"
#define BRIX_XMETA_SIDECAR_SUFFIX ".cinfo"
#define BRIX_XMETA_XATTR_MAX (64 * 1024)
Functions
ngx_int_t brix_xmeta_save (brix_sd_instance_t *store, const char *key, const brix_xmeta_t *m)
ngx_int_t brix_xmeta_load (brix_sd_instance_t *store, const char *key, brix_xmeta_t *m)
ngx_int_t brix_xmeta_remove (brix_sd_instance_t *store, const char *key)
Macro Definition Documentation
BRIX_XMETA_SIDECAR_SUFFIX
#define BRIX_XMETA_SIDECAR_SUFFIX ".cinfo"
Definition at line 32 of file xmeta_carrier.h.
BRIX_XMETA_XATTR_MAX
#define BRIX_XMETA_XATTR_MAX (64 * 1024)
Definition at line 35 of file xmeta_carrier.h.
BRIX_XMETA_XATTR_NAME
#define BRIX_XMETA_XATTR_NAME "user.xrd.cinfo"
Definition at line 31 of file xmeta_carrier.h.
Function Documentation
brix_xmeta_load()
ngx_int_t brix_xmeta_load (brix_sd_instance_t * store, const char * key, brix_xmeta_t * m)
Definition at line 354 of file xmeta_carrier.c.
References brix_xmeta_decode(), key, xmeta_decode_rc(), xmeta_load_from_xattr(), and xmeta_sidecar_read().
Referenced by brix_cstore_cinfo_load().
brix_xmeta_remove()
ngx_int_t brix_xmeta_remove (brix_sd_instance_t * store, const char * key)
Definition at line 383 of file xmeta_carrier.c.
References BRIX_XMETA_XATTR_NAME, key, PATH_MAX, and xmeta_sidecar_key().
Referenced by brix_cstore_evict().
brix_xmeta_save()
ngx_int_t brix_xmeta_save (brix_sd_instance_t * store, const char * key, const brix_xmeta_t * m)
Definition at line 229 of file xmeta_carrier.c.
References brix_xmeta_encode(), BRIX_XMETA_OK, BRIX_XMETA_XATTR_MAX, BRIX_XMETA_XATTR_NAME, key, xmeta_sidecar_write(), and xmeta_xattr_unfit().
Referenced by brix_cstore_cinfo_store().