nginx-xrootd: src/fs/meta/xmeta_unittest.c File Reference
xmeta_unittest.c File Reference
#include "xmeta.h"
#include "core/compat/crc32c.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Macros
#define CHECK(cond, name)
Functions
static void build_sample (brix_xmeta_t *m)
static void encode_sample (uint8_t **buf, size_t *blen)
static void check_state_section (const brix_xmeta_t *d)
static void check_digests (const brix_xmeta_t *d)
static void test_round_trip (void)
static void test_corruption (void)
static void test_foreign_inputs (void)
static void test_unknown_section (void)
static void test_stock_only (void)
static void emit_sample (const char *path)
int main (int argc, char **argv)
Variables
static int g_checks
static int g_failed
static void(*const g_tests [])(void)
Macro Definition Documentation
CHECK
#define CHECK (cond, name)
Value:
    do { \
    g_checks++; \
    if (cond) { printf("  ok   %s\n", name); } \
    else      { printf("  FAIL %s (line %d)\n", name, __LINE__); g_failed++; } \
} while (0)
Definition at line 30 of file xmeta_unittest.c.
Function Documentation
build_sample()
static void build_sample (brix_xmeta_t * m) static
Definition at line 43 of file xmeta_unittest.c.
References brix_xmeta_t::access_cnt, brix_xmeta_t::astat, brix_xmeta_t::astat_count, brix_xmeta_astat_t::attach_time, brix_xmeta_t::blockcrc, BRIX_XMETA_ALG_CRC32C, BRIX_XMETA_ALG_MD5, brix_xmeta_block_set(), brix_xmeta_digest_add(), BRIX_XMETA_F_EXPIRES, BRIX_XMETA_F_VERIFIED, brix_xmeta_init(), brix_xmeta_t::bytes_flushed, brix_xmeta_astat_t::bytes_hit, brix_xmeta_t::cks_alg, brix_xmeta_t::cks_alg_len, brix_xmeta_t::cks_hex, brix_xmeta_t::cks_len, brix_xmeta_astat_t::detach_time, brix_xmeta_t::dirty_hi, brix_xmeta_t::dirty_lo, brix_xmeta_t::etag, brix_xmeta_t::etag_len, brix_xmeta_t::expires_at, brix_xmeta_t::filled_at, brix_xmeta_t::flush_gen, brix_xmeta_t::last_flush, brix_xmeta_t::mode, brix_xmeta_t::origin_mtime, and brix_xmeta_t::state_flags.
Referenced by encode_sample(), and test_round_trip().
check_digests()
static void check_digests (const brix_xmeta_t * d) static
Definition at line 116 of file xmeta_unittest.c.
References BRIX_XMETA_ALG_CRC32C, BRIX_XMETA_ALG_MD5, brix_xmeta_digest_get(), BRIX_XMETA_FOREIGN, BRIX_XMETA_OK, and CHECK.
Referenced by test_round_trip().
check_state_section()
static void check_state_section (const brix_xmeta_t * d) static
Definition at line 99 of file xmeta_unittest.c.
References BRIX_XMETA_F_EXPIRES, BRIX_XMETA_F_VERIFIED, brix_xmeta_t::bytes_flushed, CHECK, brix_xmeta_t::dirty_hi, brix_xmeta_t::dirty_lo, brix_xmeta_t::expires_at, brix_xmeta_t::filled_at, brix_xmeta_t::flush_gen, brix_xmeta_t::have_state, brix_xmeta_t::last_flush, brix_xmeta_t::mode, brix_xmeta_t::origin_mtime, and brix_xmeta_t::state_flags.
Referenced by test_round_trip().
emit_sample()
static void emit_sample (const char * path) static
Definition at line 319 of file xmeta_unittest.c.
References encode_sample(), and g_failed.
Referenced by main().
encode_sample()
static void encode_sample (uint8_t ** buf, size_t * blen) static
Definition at line 84 of file xmeta_unittest.c.
References brix_xmeta_encode(), brix_xmeta_free(), and build_sample().
Referenced by emit_sample(), test_corruption(), test_foreign_inputs(), and test_unknown_section().
main()
int main (int argc, char ** argv)
Definition at line 338 of file xmeta_unittest.c.
References emit_sample(), g_checks, g_failed, and g_tests.
test_corruption()
static void test_corruption (void) static
Definition at line 180 of file xmeta_unittest.c.
References brix_xmeta_decode(), BRIX_XMETA_ERR, brix_xmeta_free(), BRIX_XMETA_OK, CHECK, and encode_sample().
test_foreign_inputs()
static void test_foreign_inputs (void) static
Definition at line 211 of file xmeta_unittest.c.
References brix_xmeta_decode(), BRIX_XMETA_FOREIGN, CHECK, and encode_sample().
test_round_trip()
static void test_round_trip (void) static
Definition at line 140 of file xmeta_unittest.c.
References brix_xmeta_t::astat, brix_xmeta_t::astat_count, brix_xmeta_t::blockcrc, brix_xmeta_block_test(), brix_xmeta_complete(), BRIX_XMETA_CRC_UNSET, brix_xmeta_decode(), brix_xmeta_encode(), brix_xmeta_free(), BRIX_XMETA_OK, brix_xmeta_t::buffer_size, build_sample(), brix_xmeta_astat_t::bytes_hit, CHECK, check_digests(), check_state_section(), brix_xmeta_t::cks_alg, brix_xmeta_t::cks_alg_len, brix_xmeta_t::cks_hex, brix_xmeta_t::cks_len, brix_xmeta_t::etag, brix_xmeta_t::etag_len, brix_xmeta_t::file_size, brix_xmeta_t::have_blockcrc, and brix_xmeta_t::nblocks.
test_stock_only()
static void test_stock_only (void) static
Definition at line 279 of file xmeta_unittest.c.
References brix_xmeta_t::blockcrc, brix_xmeta_block_set(), brix_xmeta_block_test(), brix_xmeta_decode(), brix_xmeta_encode(), brix_xmeta_free(), brix_xmeta_init(), BRIX_XMETA_OK, CHECK, brix_xmeta_t::have_state, and s.
test_unknown_section()
static void test_unknown_section (void) static
Definition at line 234 of file xmeta_unittest.c.
References brix_crc32c_value(), brix_xmeta_decode(), brix_xmeta_free(), BRIX_XMETA_OK, BRIX_XMETA_SEC_DIGEST, CHECK, brix_xmeta_t::digests, encode_sample(), brix_xmeta_t::have_blockcrc, and brix_xmeta_t::have_state.
Variable Documentation
g_checks
int g_checks static
Definition at line 28 of file xmeta_unittest.c.
Referenced by main().
g_failed
int g_failed static
Definition at line 28 of file xmeta_unittest.c.
Referenced by emit_sample(), and main().
g_tests
void(*const g_tests[])(void) (void) static
Initial value:
= {
    test_round_trip,
    test_corruption,
    test_foreign_inputs,
    test_unknown_section,
    test_stock_only,
}
Definition at line 304 of file xmeta_unittest.c.
Referenced by main().