nginx-xrootd: src/fs/meta/xmeta_internal.h File Reference
xmeta_internal.h File Reference
#include "xmeta.h"
Data Structures
struct xmeta_state_wire_t
Macros
#define XMETA_ORIGIN_FIXED 4
Functions
uint64_t xmeta_nblocks (int64_t file_size, int64_t buffer_size)
size_t xmeta_bitmap_len (uint64_t nblocks)
Macro Definition Documentation
XMETA_ORIGIN_FIXED
#define XMETA_ORIGIN_FIXED 4
Definition at line 45 of file xmeta_internal.h.
Function Documentation
xmeta_bitmap_len()
size_t xmeta_bitmap_len (uint64_t nblocks)
Definition at line 42 of file xmeta.c.
Referenced by brix_xmeta_init(), xmeta_decode_bitmap_astat(), and xmeta_encode_plan().
xmeta_nblocks()
uint64_t xmeta_nblocks (int64_t file_size, int64_t buffer_size)
Definition at line 32 of file xmeta.c.
Referenced by brix_xmeta_init(), and xmeta_decode_stock_store().