nginx-xrootd: client/apps/diag/xrd.c File Reference
xrd.c File Reference
#include "xrd_internal.h"
#include "core/version.h"
#include "core/progname.h"
#include "cli/suggest.h"
#include "cli/cli_hint.h"
Data Structures
struct xrd_dispatch_t
struct fs_split_t
Functions
int is_fs_verb (const char *s)
static void usage_fp (FILE *out, const char *prog)
void usage (const char *prog)
static void try_exec_dir (const char *dir, const char *name, char **argv)
void exec_tool (const char *prefix, const char *tool, char **argv)
char * map_fs_arg (const char *arg, const char *ehost, int eport, int *mismatch)
static int cmd_version (int argc, char **argv)
static int cmd_usage_stderr (int argc, char **argv)
static int cmd_help (int argc, char **argv)
static int cmd_cp (int argc, char **argv)
static int cmd_get (int argc, char **argv)
static int cmd_put (int argc, char **argv)
static int cmd_diag (int argc, char **argv)
static int cmd_replicas (int argc, char **argv)
static int cmd_sync (int argc, char **argv)
static int cmd_mounts (int argc, char **argv)
static int cmd_storascan (int argc, char **argv)
static int fs_find_endpoint (int argc, char **argv, fs_split_t *sp)
static int fs_map_split_args (char **nv, int k, int argc, char **argv, fs_split_t *sp)
static int cmd_fs_verb (int argc, char **argv)
static void report_unknown_command (const char *cmd)
int main (int argc, char **argv)
Variables
const char * FS_VERBS []
const char * XRD_CAP_KEYS []
static const xrd_dispatch_t XRD_DISPATCH []
Function Documentation
cmd_cp()
static int cmd_cp (int argc, char ** argv) static
Definition at line 220 of file xrd.c.
References brix_prog_base(), brix_prog_prefix(), and exec_tool().
cmd_diag()
static int cmd_diag (int argc, char ** argv) static
Definition at line 279 of file xrd.c.
References brix_prog_base(), brix_prog_prefix(), and exec_tool().
cmd_fs_verb()
static int cmd_fs_verb (int argc, char ** argv) static
Definition at line 508 of file xrd.c.
References brix_prog_base(), brix_prog_prefix(), fs_split_t::endpoint, exec_tool(), fs_find_endpoint(), and fs_map_split_args().
Referenced by main().
cmd_get()
static int cmd_get (int argc, char ** argv) static
Definition at line 236 of file xrd.c.
References brix_prog_base(), brix_prog_prefix(), and exec_tool().
cmd_help()
static int cmd_help (int argc, char ** argv) static
Definition at line 206 of file xrd.c.
References usage_fp().
cmd_mounts()
static int cmd_mounts (int argc, char ** argv) static
Definition at line 341 of file xrd.c.
References xrd_list_mounts().
cmd_put()
static int cmd_put (int argc, char ** argv) static
Definition at line 258 of file xrd.c.
References brix_prog_base(), brix_prog_prefix(), and exec_tool().
cmd_replicas()
static int cmd_replicas (int argc, char ** argv) static
Definition at line 295 of file xrd.c.
References brix_prog_base(), brix_prog_prefix(), and exec_tool().
cmd_storascan()
static int cmd_storascan (int argc, char ** argv) static
Definition at line 358 of file xrd.c.
References brix_prog_base(), brix_prog_prefix(), and exec_tool().
cmd_sync()
static int cmd_sync (int argc, char ** argv) static
Definition at line 313 of file xrd.c.
References brix_prog_base(), brix_prog_prefix(), and exec_tool().
cmd_usage_stderr()
static int cmd_usage_stderr (int argc, char ** argv) static
Definition at line 192 of file xrd.c.
References usage().
cmd_version()
static int cmd_version (int argc, char ** argv) static
Definition at line 177 of file xrd.c.
References brix_client_version(), and brix_prog_base().
exec_tool()
void exec_tool (const char * prefix, const char * tool, char ** argv)
Definition at line 115 of file xrd.c.
References PATH_MAX, and try_exec_dir().
Referenced by cmd_cp(), cmd_diag(), cmd_fs_verb(), cmd_get(), cmd_put(), cmd_replicas(), cmd_storascan(), cmd_sync(), and xrd_mount().
fs_find_endpoint()
static int fs_find_endpoint (int argc, char ** argv, fs_split_t * sp) static
Definition at line 434 of file xrd.c.
References brix_alias_resolve(), brix_status_clear(), brix_url_parse(), fs_split_t::endpoint, fs_split_t::ep_idx, brix_url::host, brix_url::port, brix_url::scheme, scheme, fs_split_t::u, XRDC_PATH_MAX, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by cmd_fs_verb().
fs_map_split_args()
static int fs_map_split_args (char ** nv, int k, int argc, char ** argv, fs_split_t * sp) static
Definition at line 472 of file xrd.c.
References fs_split_t::endpoint, fs_split_t::ep_idx, brix_url::host, map_fs_arg(), brix_url::path, brix_url::port, and fs_split_t::u.
Referenced by cmd_fs_verb().
is_fs_verb()
int is_fs_verb (const char * s)
Definition at line 25 of file xrd.c.
References FS_VERBS, and s.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 581 of file xrd.c.
References cmd_fs_verb(), xrd_dispatch_t::fn, is_fs_verb(), xrd_dispatch_t::name, name, report_unknown_command(), usage(), and XRD_DISPATCH.
map_fs_arg()
char * map_fs_arg (const char * arg, const char * ehost, int eport, int * mismatch)
Definition at line 150 of file xrd.c.
References brix_alias_resolve(), brix_status_clear(), brix_url_parse(), brix_url::host, brix_url::path, brix_url::port, brix_url::scheme, XRDC_PATH_MAX, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by fs_map_split_args().
report_unknown_command()
static void report_unknown_command (const char * cmd) static
Definition at line 555 of file xrd.c.
References brix_cli_hint(), brix_suggest(), FS_VERBS, xrd_dispatch_t::name, name, and XRD_DISPATCH.
Referenced by main().
try_exec_dir()
static void try_exec_dir (const char * dir, const char * name, char ** argv) static
Definition at line 96 of file xrd.c.
References access(), name, and PATH_MAX.
Referenced by exec_tool().
usage()
void usage (const char * prog)
Definition at line 87 of file xrd.c.
References usage_fp().
usage_fp()
static void usage_fp (FILE * out, const char * prog) static
Definition at line 40 of file xrd.c.
References brix_prog_base(), and brix_usage_footer().
Referenced by cmd_help(), and usage().
Variable Documentation
FS_VERBS
const char* FS_VERBS[]
Initial value:
= {
    "ls", "stat", "mkdir", "rm", "rmdir", "mv", "chmod", "touch", "ln", "readlink",
    "truncate", "cat", "head", "tail", "wc", "grep", "hexdump", "dd", "upload",
    "download", "cmp", "cksum", "xattr", "readv", "writev", "du", "df", "tree",
    "find", "locate", "query", "statvfs", "prepare", "stage", "evict", "explain", NULL
}
Definition at line 11 of file xrd.c.
Referenced by is_fs_verb(), and report_unknown_command().
XRD_CAP_KEYS
const char* XRD_CAP_KEYS[]
Initial value:
= {
    "chksum", "readv", "tpc", "tpcdlg", "xrdfs.ext",
    "version", "role", "sitename", "pgread", NULL
}
Definition at line 18 of file xrd.c.
Referenced by xrd_probe_caps().
XRD_DISPATCH
const xrd_dispatch_t XRD_DISPATCH[] static
Definition at line 380 of file xrd.c.
Referenced by main(), and report_unknown_command().