nginx-xrootd: client/apps/diag/xrd_doctor.c File Reference
xrd_doctor.c File Reference
#include "xrd_internal.h"
Data Structures
struct xrd_doctor_run
Functions
void xrd_doctor_probe (const char *endpoint, xrd_probe *p)
void xrd_json_str (FILE *f, const char *s)
static void doctor_json_head (const xrd_probe *p)
static void doctor_json_tls (const xrd_probe *p)
static void doctor_json_cert (const xrd_probe *p)
static void doctor_json_clock (const xrd_probe *p)
static void doctor_json_caps (const xrd_probe *p)
static void doctor_json_creds (const xrd_cred_facts *cf)
static void doctor_json_battery (const xrd_battery *bt, int idx)
static void doctor_json_tests (const xrd_battery *bats, int nbats)
void xrd_doctor_json (const xrd_probe *p, const xrd_cred_facts *cf, const xrd_battery *bats, int nbats)
static void doctor_parse_args (int argc, char **argv, xrd_doctor_run *d)
static void doctor_discover_creds (xrd_doctor_run *d)
static void doctor_run_batteries (xrd_doctor_run *d)
static int doctor_emit_json (xrd_doctor_run *d)
static void doctor_report_creds (xrd_doctor_run *d)
static void doctor_report_conn (const xrd_probe *p, int *fatal)
static void doctor_report_cert (const xrd_probe *p, int *fatal)
static void doctor_report_clock (const xrd_probe *p, int *fatal)
static void doctor_report_caps (const xrd_probe *p)
static void doctor_report_endpoint (xrd_doctor_run *d)
static void doctor_report_batteries (const xrd_doctor_run *d)
int xrd_doctor (int argc, char **argv)
void xrd_probe_caps (brix_conn *c, xrd_probe *p)
int xrd_certinfo (int argc, char **argv)
Function Documentation
doctor_discover_creds()
static void doctor_discover_creds (xrd_doctor_run * d) static
Definition at line 360 of file xrd_doctor.c.
References access(), brix_proxy_default_path(), brix_token_discover(), xrd_doctor_run::proxy_present, xrd_doctor_run::pxp, xrd_doctor_run::tok, and xrd_doctor_run::token_present.
Referenced by xrd_doctor().
doctor_emit_json()
static int doctor_emit_json (xrd_doctor_run * d) static
Definition at line 401 of file xrd_doctor.c.
References xrd_doctor_run::bats, xrd_probe::cert, xrd_probe::clock_have, xrd_probe::connected, xrd_doctor_run::endpoint, brix_cert_info::expired, xrd_doctor_run::fatal, brix_cert_info::have, xrd_doctor_run::nbats, brix_cert_info::not_yet_valid, xrd_probe::offset_s, xrd_cred_facts::proxy_path, xrd_doctor_run::proxy_present, xrd_cred_facts::proxy_present, xrd_doctor_run::pxp, xrd_doctor_run::tok, xrd_cred_facts::token_path, xrd_doctor_run::token_present, xrd_cred_facts::token_present, xrd_doctor_json(), and xrd_doctor_probe().
Referenced by xrd_doctor().
doctor_json_battery()
static void doctor_json_battery (const xrd_battery * bt, int idx) static
Definition at line 234 of file xrd_doctor.c.
References xrd_battery::checks, xrd_check::detail, xrd_battery::endpoint, xrd_battery::err, xrd_battery::n, xrd_check::name, xrd_battery::nfail, xrd_battery::npass, xrd_battery::nskip, xrd_check::ok, xrd_battery::protocol, xrd_battery::reachable, xrd_check::skipped, and xrd_json_str().
Referenced by doctor_json_tests().
doctor_json_caps()
static void doctor_json_caps (const xrd_probe * p) static
Definition at line 192 of file xrd_doctor.c.
References xrd_probe::caps, xrd_cap_kv::key, xrd_probe::ncaps, xrd_cap_kv::val, and xrd_json_str().
Referenced by xrd_doctor_json().
doctor_json_cert()
static void doctor_json_cert (const xrd_probe * p) static
Definition at line 138 of file xrd_doctor.c.
References xrd_probe::cert, brix_cert_info::days_left, brix_cert_info::expired, brix_cert_info::have, brix_cert_info::host_match, brix_cert_info::issuer, brix_cert_info::not_after, brix_cert_info::not_before, brix_cert_info::not_yet_valid, brix_cert_info::sans, brix_cert_info::self_signed, brix_cert_info::subject, xrd_fmt_epoch(), and xrd_json_str().
Referenced by xrd_doctor_json().
doctor_json_clock()
static void doctor_json_clock (const xrd_probe * p) static
Definition at line 171 of file xrd_doctor.c.
References xrd_probe::clock_have, xrd_probe::clock_method, xrd_probe::offset_s, xrd_probe::rtt_ms, xrd_probe::server_epoch, and xrd_json_str().
Referenced by xrd_doctor_json().
doctor_json_creds()
static void doctor_json_creds (const xrd_cred_facts * cf) static
Definition at line 214 of file xrd_doctor.c.
References xrd_cred_facts::proxy_path, xrd_cred_facts::proxy_present, xrd_cred_facts::token_path, xrd_cred_facts::token_present, and xrd_json_str().
Referenced by xrd_doctor_json().
doctor_json_head()
static void doctor_json_head (const xrd_probe * p) static
Definition at line 96 of file xrd_doctor.c.
References xrd_probe::auth, xrd_probe::connected, xrd_probe::err, xrd_probe::host, xrd_probe::port, xrd_probe::sec_list, xrd_probe::server_flags, xrd_json_str(), and xrd_role_str().
Referenced by xrd_doctor_json().
doctor_json_tests()
static void doctor_json_tests (const xrd_battery * bats, int nbats) static
Definition at line 269 of file xrd_doctor.c.
References doctor_json_battery().
Referenced by xrd_doctor_json().
doctor_json_tls()
static void doctor_json_tls (const xrd_probe * p) static
Definition at line 118 of file xrd_doctor.c.
References xrd_probe::tls_active, xrd_probe::tls_cipher, xrd_probe::tls_ver, and xrd_json_str().
Referenced by xrd_doctor_json().
doctor_parse_args()
static void doctor_parse_args (int argc, char ** argv, xrd_doctor_run * d) static
Definition at line 335 of file xrd_doctor.c.
References xrd_doctor_run::also, xrd_doctor_run::do_rw, xrd_doctor_run::endpoint, xrd_doctor_run::nalso, xrd_doctor_run::verify, xrd_doctor_run::want_json, and XRD_DOCTOR_MAX_EP.
Referenced by xrd_doctor().
doctor_report_batteries()
static void doctor_report_batteries (const xrd_doctor_run * d) static
Definition at line 572 of file xrd_doctor.c.
References xrd_doctor_run::bats, xrd_battery::checks, xrd_check::detail, xrd_doctor_run::do_rw, xrd_battery::endpoint, xrd_battery::err, xrd_battery::n, xrd_check::name, xrd_doctor_run::nbats, xrd_battery::nfail, xrd_battery::npass, xrd_battery::nskip, xrd_check::ok, xrd_battery::protocol, xrd_battery::reachable, and xrd_check::skipped.
Referenced by xrd_doctor().
doctor_report_caps()
static void doctor_report_caps (const xrd_probe * p) static
Definition at line 528 of file xrd_doctor.c.
References xrd_probe::caps, xrd_cap_kv::key, xrd_probe::ncaps, and xrd_cap_kv::val.
Referenced by doctor_report_endpoint().
doctor_report_cert()
static void doctor_report_cert (const xrd_probe * p, int * fatal) static
Definition at line 471 of file xrd_doctor.c.
References xrd_probe::cert, brix_cert_info::days_left, brix_cert_info::expired, brix_cert_info::have, brix_cert_info::host_match, brix_cert_info::issuer, brix_cert_info::not_after, brix_cert_info::not_before, brix_cert_info::not_yet_valid, brix_cert_info::subject, and xrd_fmt_epoch().
Referenced by doctor_report_endpoint().
doctor_report_clock()
static void doctor_report_clock (const xrd_probe * p, int * fatal) static
Definition at line 503 of file xrd_doctor.c.
References xrd_probe::clock_have, xrd_probe::clock_method, xrd_probe::offset_s, xrd_probe::rtt_ms, and xrd_fabs().
Referenced by doctor_report_endpoint().
doctor_report_conn()
static void doctor_report_conn (const xrd_probe * p, int * fatal) static
Definition at line 445 of file xrd_doctor.c.
References xrd_probe::auth, xrd_probe::connected, xrd_probe::err, xrd_probe::sec_list, xrd_probe::server_flags, xrd_probe::tls_active, xrd_probe::tls_cipher, xrd_probe::tls_ver, and xrd_role_str().
Referenced by doctor_report_endpoint().
doctor_report_creds()
static void doctor_report_creds (xrd_doctor_run * d) static
Definition at line 427 of file xrd_doctor.c.
References brix_cred_diagnose(), brix_gsi_cert_explain(), brix_token_explain(), xrd_doctor_run::fatal, xrd_doctor_run::proxy_present, xrd_doctor_run::pxp, and xrd_doctor_run::tok.
Referenced by xrd_doctor().
doctor_report_endpoint()
static void doctor_report_endpoint (xrd_doctor_run * d) static
Definition at line 550 of file xrd_doctor.c.
References doctor_report_caps(), doctor_report_cert(), doctor_report_clock(), doctor_report_conn(), xrd_doctor_run::endpoint, xrd_doctor_run::fatal, xrd_probe::host, xrd_probe::port, and xrd_doctor_probe().
Referenced by xrd_doctor().
doctor_run_batteries()
static void doctor_run_batteries (xrd_doctor_run * d) static
Definition at line 377 of file xrd_doctor.c.
References xrd_doctor_run::also, xrd_doctor_run::bats, xrd_doctor_run::do_rw, xrd_doctor_run::endpoint, xrd_doctor_run::fatal, xrd_doctor_run::nalso, xrd_doctor_run::nbats, xrd_battery::nfail, xrd_doctor_run::verify, and xrd_run_battery().
Referenced by xrd_doctor().
xrd_certinfo()
int xrd_certinfo (int argc, char ** argv)
Definition at line 670 of file xrd_doctor.c.
References brix_close(), brix_connect_no_login(), brix_crypto_init(), brix_endpoint_parse(), brix_shellcode(), brix_status_clear(), brix_tls_peer_cert_info(), c, brix_cert_info::days_left, brix_cert_info::expired, brix_cert_info::have, brix_url::host, brix_cert_info::host_match, brix_opts::insecure_tls, brix_cert_info::issuer, brix_status::msg, brix_cert_info::not_after, brix_cert_info::not_before, brix_cert_info::not_yet_valid, brix_url::port, brix_cert_info::sans, brix_cert_info::self_signed, brix_cert_info::subject, brix_opts::verify_host, and xrd_fmt_epoch().
xrd_doctor()
int xrd_doctor (int argc, char ** argv)
Definition at line 605 of file xrd_doctor.c.
References brix_crypto_init(), doctor_discover_creds(), doctor_emit_json(), doctor_parse_args(), doctor_report_batteries(), doctor_report_creds(), doctor_report_endpoint(), doctor_run_batteries(), xrd_doctor_run::endpoint, xrd_doctor_run::fatal, xrd_doctor_run::nbats, xrd_doctor_run::verify, and xrd_doctor_run::want_json.
xrd_doctor_json()
void xrd_doctor_json (const xrd_probe * p, const xrd_cred_facts * cf, const xrd_battery * bats, int nbats)
Definition at line 285 of file xrd_doctor.c.
References doctor_json_caps(), doctor_json_cert(), doctor_json_clock(), doctor_json_creds(), doctor_json_head(), doctor_json_tests(), and doctor_json_tls().
Referenced by doctor_emit_json().
xrd_doctor_probe()
void xrd_doctor_probe (const char * endpoint, xrd_probe * p)
Definition at line 13 of file xrd_doctor.c.
References xrd_probe::auth, brix_close(), brix_connect(), brix_connect_no_login(), brix_endpoint_parse(), brix_status_clear(), brix_tls_info(), brix_tls_peer_cert_info(), c, xrd_probe::cert, xrd_probe::connected, xrd_probe::err, xrd_probe::host, brix_url::host, brix_opts::insecure_tls, brix_status::msg, xrd_probe::port, brix_url::port, xrd_probe::sec_list, xrd_probe::server_flags, xrd_probe::tls_active, xrd_probe::tls_cipher, xrd_probe::tls_ver, brix_opts::verify_host, xrd_measure_clock_skew(), xrd_probe_caps(), and XRDC_MSG_MAX.
Referenced by doctor_emit_json(), and doctor_report_endpoint().
xrd_json_str()
void xrd_json_str (FILE * f, const char * s)
Definition at line 71 of file xrd_doctor.c.
References s.
Referenced by doctor_json_battery(), doctor_json_caps(), doctor_json_cert(), doctor_json_clock(), doctor_json_creds(), doctor_json_head(), and doctor_json_tls().
xrd_probe_caps()
void xrd_probe_caps (brix_conn * c, xrd_probe * p)
Definition at line 643 of file xrd_doctor.c.
References brix_query(), brix_status_clear(), c, xrd_probe::caps, xrd_cap_kv::key, kXR_Qconfig, xrd_probe::ncaps, xrd_cap_kv::val, XRD_CAP_KEYS, and XRD_CAPS_MAX.
Referenced by xrd_caps(), and xrd_doctor_probe().