nginx-xrootd: client/apps/diag/xrd_clockskew.c File Reference
xrd_clockskew.c File Reference
#include "xrd_internal.h"
Functions
void xrd_fmt_epoch (long e, char *buf, size_t sz)
double xrd_fabs (double x)
int xrd_parse_http_date (const char *s, time_t *out)
int xrd_clockskew_http (const char *endpoint, xrd_probe *p, char *err, size_t errsz)
int xrd_clockskew_root (const char *endpoint, const brix_opts *o, xrd_probe *p, char *err, size_t errsz)
int xrd_measure_clock_skew (const char *endpoint, const brix_opts *o, xrd_probe *p, char *err, size_t errsz)
int xrd_clockskew (int argc, char **argv)
Function Documentation
xrd_clockskew()
int xrd_clockskew (int argc, char ** argv)
Definition at line 146 of file xrd_clockskew.c.
References brix_crypto_init(), xrd_probe::clock_have, xrd_probe::clock_method, xrd_probe::offset_s, xrd_probe::rtt_ms, xrd_probe::server_epoch, brix_opts::verify_host, xrd_fabs(), xrd_fmt_epoch(), xrd_measure_clock_skew(), and XRDC_MSG_MAX.
xrd_clockskew_http()
int xrd_clockskew_http (const char * endpoint, xrd_probe * p, char * err, size_t errsz)
Definition at line 50 of file xrd_clockskew.c.
References brix_http_header(), brix_http_req(), brix_http_resp_free(), brix_status_clear(), brix_weburl_parse(), xrd_probe::clock_have, xrd_probe::clock_method, date, brix_weburl::host, brix_status::msg, xrd_probe::offset_s, brix_weburl::path, brix_weburl::port, xrd_probe::rtt_ms, xrd_probe::server_epoch, brix_weburl::tls, and xrd_parse_http_date().
Referenced by xrd_measure_clock_skew().
xrd_clockskew_root()
int xrd_clockskew_root (const char * endpoint, const brix_opts * o, xrd_probe * p, char * err, size_t errsz)
Definition at line 91 of file xrd_clockskew.c.
References brix_close(), brix_connect(), brix_endpoint_parse(), brix_file_close(), brix_file_open_write(), brix_rm(), brix_stat(), brix_status_clear(), c, xrd_probe::clock_have, xrd_probe::clock_method, brix_status::msg, brix_statinfo::mtime, xrd_probe::offset_s, xrd_probe::rtt_ms, and xrd_probe::server_epoch.
Referenced by xrd_measure_clock_skew().
xrd_fabs()
double xrd_fabs (double x)
Definition at line 21 of file xrd_clockskew.c.
Referenced by doctor_report_clock(), and xrd_clockskew().
xrd_fmt_epoch()
void xrd_fmt_epoch (long e, char * buf, size_t sz)
Definition at line 10 of file xrd_clockskew.c.
Referenced by doctor_json_cert(), doctor_report_cert(), xrd_certinfo(), and xrd_clockskew().
xrd_measure_clock_skew()
int xrd_measure_clock_skew (const char * endpoint, const brix_opts * o, xrd_probe * p, char * err, size_t errsz)
Definition at line 133 of file xrd_clockskew.c.
References brix_is_web_url(), xrd_clockskew_http(), and xrd_clockskew_root().
Referenced by xrd_clockskew(), and xrd_doctor_probe().
xrd_parse_http_date()
int xrd_parse_http_date (const char * s, time_t * out)
Definition at line 27 of file xrd_clockskew.c.
References s.
Referenced by xrd_clockskew_http().