nginx-xrootd: client/apps/diag/xrd_internal.h File Reference
xrd_internal.h File Reference
#include "brix.h"
#include "core/compat/crypto.h"
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <libgen.h>
#include <stdarg.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
Data Structures
struct xrd_cap_kv
struct xrd_probe
struct xrd_check
struct xrd_battery
struct xrd_cred_facts
Macros
#define XRD_CAPS_MAX 16
#define XRD_MAX_CHECKS 40
#define XRD_DOCTOR_MAX_EP 9 /* primary + up to 8 --also endpoints */
Functions
int is_fs_verb (const char *s)
void usage (const char *prog)
void exec_tool (const char *prefix, const char *tool, char **argv)
char * map_fs_arg (const char *arg, const char *ehost, int eport, int *mismatch)
void bat_add (xrd_battery *b, const char *name, int status, const char *fmt,...)
void fill_pattern (uint8_t *buf, size_t n)
int tmpfile_with (const uint8_t *buf, size_t n)
void battery_root (const brix_url *u, const brix_opts *o, int do_write, xrd_battery *b)
void battery_web (const brix_weburl *u, int do_write, const char *bearer, int verify, xrd_battery *b)
void battery_s3 (const brix_weburl *u, int do_write, const char *ak, const char *sk, const char *region, int verify, xrd_battery *b)
void xrd_run_battery (const char *endpoint, int do_write, int verify, xrd_battery *b)
void xrd_doctor_probe (const char *endpoint, xrd_probe *p)
void xrd_json_str (FILE *f, const char *s)
void xrd_doctor_json (const xrd_probe *p, const xrd_cred_facts *cf, const xrd_battery *bats, int nbats)
int xrd_doctor (int argc, char **argv)
int xrd_login (int argc, char **argv)
int xrd_ping (int argc, char **argv)
const char * xrd_role_str (uint32_t flags)
void xrd_fmt_epoch (long e, char *buf, size_t sz)
double xrd_fabs (double x)
void xrd_probe_caps (brix_conn *c, xrd_probe *p)
int xrd_parse_http_date (const char *s, time_t *out)
int xrd_clockskew_http (const char *endpoint, xrd_probe *p, char *err, size_t errsz)
int xrd_clockskew_root (const char *endpoint, const brix_opts *o, xrd_probe *p, char *err, size_t errsz)
int xrd_measure_clock_skew (const char *endpoint, const brix_opts *o, xrd_probe *p, char *err, size_t errsz)
int xrd_certinfo (int argc, char **argv)
int xrd_clockskew (int argc, char **argv)
int xrd_whoami (int argc, char **argv)
int xrd_caps (int argc, char **argv)
int run_cmd (char *const cmd_argv[])
void mountinfo_unescape (const char *in, char *out, size_t outsz)
int xrd_list_mounts (void)
int xrd_mount (int argc, char **argv)
int xrd_unmount (int argc, char **argv)
Variables
const char * FS_VERBS []
const char * XRD_CAP_KEYS []
Macro Definition Documentation
XRD_CAPS_MAX
#define XRD_CAPS_MAX 16
Definition at line 24 of file xrd_internal.h.
XRD_DOCTOR_MAX_EP
#define XRD_DOCTOR_MAX_EP 9 /* primary + up to 8 --also endpoints */
Definition at line 65 of file xrd_internal.h.
XRD_MAX_CHECKS
#define XRD_MAX_CHECKS 40
Definition at line 48 of file xrd_internal.h.
Function Documentation
bat_add()
void bat_add (xrd_battery * b, const char * name, int status, const char * fmt, ...)
Definition at line 24 of file xrd_battery.c.
References c, xrd_battery::checks, xrd_battery::n, name, xrd_battery::nfail, xrd_battery::npass, xrd_battery::nskip, and XRD_MAX_CHECKS.
Referenced by battery_root(), battery_s3(), battery_web(), probe_path_confinement(), probe_root_read_suite(), probe_write_suite(), s3_delete(), s3_get_verify(), s3_put(), web_move_delete(), web_put_get_verify(), web_read_suite(), web_write_suite(), write_checksum(), write_readv(), write_rename_truncate_rm(), write_symlink_ops(), write_verify(), and write_xattr_ops().
battery_root()
void battery_root (const brix_url * u, const brix_opts * o, int do_write, xrd_battery * b)
Definition at line 316 of file xrd_battery.c.
References bat_add(), brix_close(), brix_connect(), brix_ext_probe(), brix_status_clear(), c, xrd_battery::err, brix_status::msg, probe_path_confinement(), probe_root_read_suite(), probe_write_suite(), xrd_battery::protocol, and xrd_battery::reachable.
Referenced by xrd_run_battery().
battery_s3()
void battery_s3 (const brix_weburl * u, int do_write, const char * ak, const char * sk, const char * region, int verify, xrd_battery * b)
Definition at line 623 of file xrd_battery.c.
References bat_add(), brix_resolve_ca_dir(), brix_s3_list(), brix_status_clear(), brix_strv_free(), xrd_battery::err, brix_status::msg, xrd_battery::protocol, xrd_battery::reachable, region, and s3_write_suite().
Referenced by xrd_run_battery().
battery_web()
void battery_web (const brix_weburl * u, int do_write, const char * bearer, int verify, xrd_battery * b)
Definition at line 487 of file xrd_battery.c.
References bat_add(), brix_resolve_ca_dir(), xrd_battery::protocol, brix_weburl::tls, web_read_suite(), and web_write_suite().
Referenced by xrd_run_battery().
exec_tool()
void exec_tool (const char * prefix, const char * tool, char ** argv)
Definition at line 115 of file xrd.c.
References PATH_MAX, and try_exec_dir().
Referenced by cmd_cp(), cmd_diag(), cmd_fs_verb(), cmd_get(), cmd_put(), cmd_replicas(), cmd_storascan(), cmd_sync(), and xrd_mount().
fill_pattern()
void fill_pattern (uint8_t * buf, size_t n)
Definition at line 44 of file xrd_battery.c.
Referenced by probe_write_suite(), s3_write_suite(), and web_put_get_verify().
is_fs_verb()
int is_fs_verb (const char * s)
Definition at line 25 of file xrd.c.
References FS_VERBS, and s.
Referenced by main().
map_fs_arg()
char * map_fs_arg (const char * arg, const char * ehost, int eport, int * mismatch)
Definition at line 150 of file xrd.c.
References brix_alias_resolve(), brix_status_clear(), brix_url_parse(), brix_url::host, brix_url::path, brix_url::port, brix_url::scheme, XRDC_PATH_MAX, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by fs_map_split_args().
mountinfo_unescape()
void mountinfo_unescape (const char * in, char * out, size_t outsz)
Definition at line 231 of file xrd_mount.c.
run_cmd()
int run_cmd (char *const cmd_argv[])
Definition at line 209 of file xrd_mount.c.
Referenced by xrd_unmount().
tmpfile_with()
int tmpfile_with (const uint8_t * buf, size_t n)
Definition at line 53 of file xrd_battery.c.
References lseek().
Referenced by s3_get_verify(), s3_put(), web_put_get_verify(), and write_checksum().
usage()
void usage (const char * prog)
Definition at line 180 of file xrdcp.c.
xrd_caps()
int xrd_caps (int argc, char ** argv)
Definition at line 169 of file xrd_mount.c.
References brix_close(), brix_connect(), brix_crypto_init(), brix_endpoint_parse(), brix_shellcode(), brix_status_clear(), brix_tls_info(), c, xrd_probe::caps, brix_url::host, xrd_cap_kv::key, brix_status::msg, xrd_probe::ncaps, brix_url::port, xrd_cap_kv::val, brix_opts::verify_host, xrd_probe_caps(), and xrd_role_str().
xrd_certinfo()
int xrd_certinfo (int argc, char ** argv)
Definition at line 670 of file xrd_doctor.c.
References brix_close(), brix_connect_no_login(), brix_crypto_init(), brix_endpoint_parse(), brix_shellcode(), brix_status_clear(), brix_tls_peer_cert_info(), c, brix_cert_info::days_left, brix_cert_info::expired, brix_cert_info::have, brix_url::host, brix_cert_info::host_match, brix_opts::insecure_tls, brix_cert_info::issuer, brix_status::msg, brix_cert_info::not_after, brix_cert_info::not_before, brix_cert_info::not_yet_valid, brix_url::port, brix_cert_info::sans, brix_cert_info::self_signed, brix_cert_info::subject, brix_opts::verify_host, and xrd_fmt_epoch().
xrd_clockskew()
int xrd_clockskew (int argc, char ** argv)
Definition at line 146 of file xrd_clockskew.c.
References brix_crypto_init(), xrd_probe::clock_have, xrd_probe::clock_method, xrd_probe::offset_s, xrd_probe::rtt_ms, xrd_probe::server_epoch, brix_opts::verify_host, xrd_fabs(), xrd_fmt_epoch(), xrd_measure_clock_skew(), and XRDC_MSG_MAX.
xrd_clockskew_http()
int xrd_clockskew_http (const char * endpoint, xrd_probe * p, char * err, size_t errsz)
Definition at line 50 of file xrd_clockskew.c.
References brix_http_header(), brix_http_req(), brix_http_resp_free(), brix_status_clear(), brix_weburl_parse(), xrd_probe::clock_have, xrd_probe::clock_method, date, brix_weburl::host, brix_status::msg, xrd_probe::offset_s, brix_weburl::path, brix_weburl::port, xrd_probe::rtt_ms, xrd_probe::server_epoch, brix_weburl::tls, and xrd_parse_http_date().
Referenced by xrd_measure_clock_skew().
xrd_clockskew_root()
int xrd_clockskew_root (const char * endpoint, const brix_opts * o, xrd_probe * p, char * err, size_t errsz)
Definition at line 91 of file xrd_clockskew.c.
References brix_close(), brix_connect(), brix_endpoint_parse(), brix_file_close(), brix_file_open_write(), brix_rm(), brix_stat(), brix_status_clear(), c, xrd_probe::clock_have, xrd_probe::clock_method, brix_status::msg, brix_statinfo::mtime, xrd_probe::offset_s, xrd_probe::rtt_ms, and xrd_probe::server_epoch.
Referenced by xrd_measure_clock_skew().
xrd_doctor()
int xrd_doctor (int argc, char ** argv)
Definition at line 605 of file xrd_doctor.c.
References brix_crypto_init(), doctor_discover_creds(), doctor_emit_json(), doctor_parse_args(), doctor_report_batteries(), doctor_report_creds(), doctor_report_endpoint(), doctor_run_batteries(), xrd_doctor_run::endpoint, xrd_doctor_run::fatal, xrd_doctor_run::nbats, xrd_doctor_run::verify, and xrd_doctor_run::want_json.
xrd_doctor_json()
void xrd_doctor_json (const xrd_probe * p, const xrd_cred_facts * cf, const xrd_battery * bats, int nbats)
Definition at line 285 of file xrd_doctor.c.
References doctor_json_caps(), doctor_json_cert(), doctor_json_clock(), doctor_json_creds(), doctor_json_head(), doctor_json_tests(), and doctor_json_tls().
Referenced by doctor_emit_json().
xrd_doctor_probe()
void xrd_doctor_probe (const char * endpoint, xrd_probe * p)
Definition at line 13 of file xrd_doctor.c.
References xrd_probe::auth, brix_close(), brix_connect(), brix_connect_no_login(), brix_endpoint_parse(), brix_status_clear(), brix_tls_info(), brix_tls_peer_cert_info(), c, xrd_probe::cert, xrd_probe::connected, xrd_probe::err, xrd_probe::host, brix_url::host, brix_opts::insecure_tls, brix_status::msg, xrd_probe::port, brix_url::port, xrd_probe::sec_list, xrd_probe::server_flags, xrd_probe::tls_active, xrd_probe::tls_cipher, xrd_probe::tls_ver, brix_opts::verify_host, xrd_measure_clock_skew(), xrd_probe_caps(), and XRDC_MSG_MAX.
Referenced by doctor_emit_json(), and doctor_report_endpoint().
xrd_fabs()
double xrd_fabs (double x)
Definition at line 21 of file xrd_clockskew.c.
Referenced by doctor_report_clock(), and xrd_clockskew().
xrd_fmt_epoch()
void xrd_fmt_epoch (long e, char * buf, size_t sz)
Definition at line 10 of file xrd_clockskew.c.
Referenced by doctor_json_cert(), doctor_report_cert(), xrd_certinfo(), and xrd_clockskew().
xrd_json_str()
void xrd_json_str (FILE * f, const char * s)
Definition at line 71 of file xrd_doctor.c.
References s.
Referenced by doctor_json_battery(), doctor_json_caps(), doctor_json_cert(), doctor_json_clock(), doctor_json_creds(), doctor_json_head(), and doctor_json_tls().
xrd_list_mounts()
int xrd_list_mounts (void)
Definition at line 335 of file xrd_mount.c.
Referenced by cmd_mounts(), and xrd_mount().
xrd_login()
int xrd_login (int argc, char ** argv)
Definition at line 14 of file xrd_mount.c.
References brix_cred_autorefresh(), brix_cred_diagnose(), and brix_crypto_init().
xrd_measure_clock_skew()
int xrd_measure_clock_skew (const char * endpoint, const brix_opts * o, xrd_probe * p, char * err, size_t errsz)
Definition at line 133 of file xrd_clockskew.c.
References brix_is_web_url(), xrd_clockskew_http(), and xrd_clockskew_root().
Referenced by xrd_clockskew(), and xrd_doctor_probe().
xrd_mount()
int xrd_mount (int argc, char ** argv)
Definition at line 465 of file xrd_mount.c.
References brix_prog_base(), brix_prog_prefix(), driver, exec_tool(), xrd_list_mounts(), xrd_mount_build_argv(), xrd_mount_parse_selectors(), and XRDC_PATH_MAX.
xrd_parse_http_date()
int xrd_parse_http_date (const char * s, time_t * out)
Definition at line 27 of file xrd_clockskew.c.
References s.
Referenced by xrd_clockskew_http().
xrd_ping()
int xrd_ping (int argc, char ** argv)
Definition at line 45 of file xrd_mount.c.
References brix_close(), brix_connect(), brix_crypto_init(), brix_endpoint_parse(), brix_shellcode(), brix_stat(), brix_status_clear(), c, brix_url::host, brix_status::msg, brix_url::port, and brix_opts::verify_host.
xrd_probe_caps()
void xrd_probe_caps (brix_conn * c, xrd_probe * p)
Definition at line 643 of file xrd_doctor.c.
References brix_query(), brix_status_clear(), c, xrd_probe::caps, xrd_cap_kv::key, kXR_Qconfig, xrd_probe::ncaps, xrd_cap_kv::val, XRD_CAP_KEYS, and XRD_CAPS_MAX.
Referenced by xrd_caps(), and xrd_doctor_probe().
xrd_role_str()
const char * xrd_role_str (uint32_t flags)
Definition at line 117 of file xrd_mount.c.
References kXR_isManager, and kXR_isServer.
Referenced by doctor_json_head(), doctor_report_conn(), and xrd_caps().
xrd_run_battery()
void xrd_run_battery (const char * endpoint, int do_write, int verify, xrd_battery * b)
Definition at line 653 of file xrd_battery.c.
References battery_root(), battery_s3(), battery_web(), brix_endpoint_parse(), brix_is_web_url(), brix_status_clear(), brix_token_discover(), brix_weburl_parse(), xrd_battery::endpoint, xrd_battery::err, brix_weburl::is_s3, brix_status::msg, xrd_battery::protocol, region, tok, and brix_opts::verify_host.
Referenced by doctor_run_batteries().
xrd_unmount()
int xrd_unmount (int argc, char ** argv)
Definition at line 502 of file xrd_mount.c.
References c, and run_cmd().
xrd_whoami()
int xrd_whoami (int argc, char ** argv)
Definition at line 131 of file xrd_mount.c.
References access(), brix_close(), brix_connect(), brix_crypto_init(), brix_endpoint_parse(), brix_gsi_cert_explain(), brix_proxy_default_path(), brix_shellcode(), brix_status_clear(), brix_token_discover(), brix_token_explain(), c, brix_url::host, brix_status::msg, brix_url::port, tok, and brix_opts::verify_host.
Variable Documentation
FS_VERBS
const char* FS_VERBS[] extern
Definition at line 11 of file xrd.c.
Referenced by is_fs_verb(), and report_unknown_command().
XRD_CAP_KEYS
const char* XRD_CAP_KEYS[] extern
Definition at line 18 of file xrd.c.
Referenced by xrd_probe_caps().