nginx-xrootd: client/apps/diag/xrd_battery.c File Reference
xrd_battery.c File Reference
#include "xrd_internal.h"
Functions
void bat_add (xrd_battery *b, const char *name, int status, const char *fmt,...)
void fill_pattern (uint8_t *buf, size_t n)
int tmpfile_with (const uint8_t *buf, size_t n)
static ssize_t bat_upload_src_fd (void *ctx, uint8_t *buf, int64_t off, size_t cap, brix_status *st)
static void probe_root_read_suite (brix_conn *c, xrd_battery *b)
static void probe_path_confinement (brix_conn *c, xrd_battery *b)
static int write_verify (brix_conn *c, const char *file, const uint8_t *payload, size_t payload_len, xrd_battery *b)
static void write_readv (brix_conn *c, const char *file, const uint8_t *payload, xrd_battery *b)
static void write_checksum (brix_conn *c, const char *file, const uint8_t *payload, size_t payload_len, xrd_battery *b)
static void write_xattr_ops (brix_conn *c, const char *file, xrd_battery *b)
static void write_symlink_ops (brix_conn *c, const char *dir, const char *file, int ext_sl, int ext_rl, int *sym_left, xrd_battery *b)
static void write_rename_truncate_rm (brix_conn *c, const char *dir, const char *file, const char *file2, int sym_left, xrd_battery *b)
static void probe_write_suite (brix_conn *c, int ext_sa, int ext_sl, int ext_rl, xrd_battery *b)
void battery_root (const brix_url *u, const brix_opts *o, int do_write, xrd_battery *b)
static int web_read_suite (const brix_weburl *u, const char *xtra, int verify, const char *ca, xrd_battery *b)
static void web_put_get_verify (const brix_weburl *u, const char *fpath, const char *xtra, int verify, const char *ca, xrd_battery *b)
static void web_move_delete (const brix_weburl *u, const char *dir, const char *fpath, const char *mpath, const char *xtra, int verify, const char *ca, xrd_battery *b)
static void web_write_suite (const brix_weburl *u, const char *xtra, int verify, const char *ca, xrd_battery *b)
void battery_web (const brix_weburl *u, int do_write, const char *bearer, int verify, xrd_battery *b)
static void s3_put (const brix_weburl *u, const char *uri, const char *ak, const char *sk, const char *region, int verify, const char *ca, const uint8_t *payload, size_t payload_len, xrd_battery *b)
static void s3_get_verify (const brix_weburl *u, const char *uri, const char *ak, const char *sk, const char *region, int verify, const char *ca, const uint8_t *payload, size_t payload_len, xrd_battery *b)
static void s3_delete (const brix_weburl *u, const char *uri, const char *ak, const char *sk, const char *region, int verify, const char *ca, xrd_battery *b)
static void s3_temp_uri (const brix_weburl *u, char *uri, size_t n)
static void s3_write_suite (const brix_weburl *u, const char *ak, const char *sk, const char *region, int verify, const char *ca, xrd_battery *b)
void battery_s3 (const brix_weburl *u, int do_write, const char *ak, const char *sk, const char *region, int verify, xrd_battery *b)
void xrd_run_battery (const char *endpoint, int do_write, int verify, xrd_battery *b)
Function Documentation
bat_add()
void bat_add (xrd_battery * b, const char * name, int status, const char * fmt, ...)
Definition at line 24 of file xrd_battery.c.
References c, xrd_battery::checks, xrd_battery::n, name, xrd_battery::nfail, xrd_battery::npass, xrd_battery::nskip, and XRD_MAX_CHECKS.
Referenced by battery_root(), battery_s3(), battery_web(), probe_path_confinement(), probe_root_read_suite(), probe_write_suite(), s3_delete(), s3_get_verify(), s3_put(), web_move_delete(), web_put_get_verify(), web_read_suite(), web_write_suite(), write_checksum(), write_readv(), write_rename_truncate_rm(), write_symlink_ops(), write_verify(), and write_xattr_ops().
bat_upload_src_fd()
static ssize_t bat_upload_src_fd (void * ctx, uint8_t * buf, int64_t off, size_t cap, brix_status * st) static
Definition at line 71 of file xrd_battery.c.
References brix_status_set(), pread(), and XRDC_ESOCK.
Referenced by s3_put(), and web_put_get_verify().
battery_root()
void battery_root (const brix_url * u, const brix_opts * o, int do_write, xrd_battery * b)
Definition at line 316 of file xrd_battery.c.
References bat_add(), brix_close(), brix_connect(), brix_ext_probe(), brix_status_clear(), c, xrd_battery::err, brix_status::msg, probe_path_confinement(), probe_root_read_suite(), probe_write_suite(), xrd_battery::protocol, and xrd_battery::reachable.
Referenced by xrd_run_battery().
battery_s3()
void battery_s3 (const brix_weburl * u, int do_write, const char * ak, const char * sk, const char * region, int verify, xrd_battery * b)
Definition at line 623 of file xrd_battery.c.
References bat_add(), brix_resolve_ca_dir(), brix_s3_list(), brix_status_clear(), brix_strv_free(), xrd_battery::err, brix_status::msg, xrd_battery::protocol, xrd_battery::reachable, region, and s3_write_suite().
Referenced by xrd_run_battery().
battery_web()
void battery_web (const brix_weburl * u, int do_write, const char * bearer, int verify, xrd_battery * b)
Definition at line 487 of file xrd_battery.c.
References bat_add(), brix_resolve_ca_dir(), xrd_battery::protocol, brix_weburl::tls, web_read_suite(), and web_write_suite().
Referenced by xrd_run_battery().
fill_pattern()
void fill_pattern (uint8_t * buf, size_t n)
Definition at line 44 of file xrd_battery.c.
Referenced by probe_write_suite(), s3_write_suite(), and web_put_get_verify().
probe_path_confinement()
static void probe_path_confinement (brix_conn * c, xrd_battery * b) static
Definition at line 111 of file xrd_battery.c.
References bat_add(), brix_stat(), brix_status_clear(), and c.
Referenced by battery_root().
probe_root_read_suite()
static void probe_root_read_suite (brix_conn * c, xrd_battery * b) static
Definition at line 81 of file xrd_battery.c.
References bat_add(), brix_dirlist(), brix_query(), brix_stat(), brix_status_clear(), brix_statvfs(), c, brix_statinfo::flags, kXR_Qconfig, and brix_status::msg.
Referenced by battery_root().
probe_write_suite()
static void probe_write_suite (brix_conn * c, int ext_sa, int ext_sl, int ext_rl, xrd_battery * b) static
Definition at line 264 of file xrd_battery.c.
References bat_add(), brix_file_close(), brix_file_open_read(), brix_file_read(), brix_mkdir(), brix_setattr(), brix_status_clear(), c, fill_pattern(), brix_status::msg, write_checksum(), write_readv(), write_rename_truncate_rm(), write_symlink_ops(), write_verify(), and write_xattr_ops().
Referenced by battery_root().
s3_delete()
static void s3_delete (const brix_weburl * u, const char * uri, const char * ak, const char * sk, const char * region, int verify, const char * ca, xrd_battery * b) static
Definition at line 566 of file xrd_battery.c.
References bat_add(), brix_http_req(), brix_http_resp_free(), brix_s3_sha256_hex(), brix_s3_sign_v4(), brix_status_clear(), brix_weburl::host, brix_status::msg, brix_weburl::port, region, brix_http_resp::status, and brix_weburl::tls.
Referenced by s3_write_suite().
s3_get_verify()
static void s3_get_verify (const brix_weburl * u, const char * uri, const char * ak, const char * sk, const char * region, int verify, const char * ca, const uint8_t * payload, size_t payload_len, xrd_battery * b) static
Definition at line 536 of file xrd_battery.c.
References bat_add(), brix_http_download(), brix_s3_sha256_hex(), brix_s3_sign_v4(), brix_status_clear(), close(), brix_weburl::host, lseek(), brix_status::msg, brix_weburl::port, read(), region, brix_weburl::tls, and tmpfile_with().
Referenced by s3_write_suite().
s3_put()
static void s3_put (const brix_weburl * u, const char * uri, const char * ak, const char * sk, const char * region, int verify, const char * ca, const uint8_t * payload, size_t payload_len, xrd_battery * b) static
Definition at line 510 of file xrd_battery.c.
References bat_add(), bat_upload_src_fd(), brix_http_upload(), brix_s3_sha256_hex(), brix_s3_sign_v4(), brix_status_clear(), close(), brix_weburl::host, brix_status::msg, brix_weburl::port, region, brix_weburl::tls, and tmpfile_with().
Referenced by s3_write_suite().
s3_temp_uri()
static void s3_temp_uri (const brix_weburl * u, char * uri, size_t n) static
Definition at line 591 of file xrd_battery.c.
References brix_weburl::path.
Referenced by s3_write_suite().
s3_write_suite()
static void s3_write_suite (const brix_weburl * u, const char * ak, const char * sk, const char * region, int verify, const char * ca, xrd_battery * b) static
Definition at line 606 of file xrd_battery.c.
References fill_pattern(), region, s3_delete(), s3_get_verify(), s3_put(), and s3_temp_uri().
Referenced by battery_s3().
tmpfile_with()
int tmpfile_with (const uint8_t * buf, size_t n)
Definition at line 53 of file xrd_battery.c.
References lseek().
Referenced by s3_get_verify(), s3_put(), web_put_get_verify(), and write_checksum().
web_move_delete()
static void web_move_delete (const brix_weburl * u, const char * dir, const char * fpath, const char * mpath, const char * xtra, int verify, const char * ca, xrd_battery * b) static
Definition at line 425 of file xrd_battery.c.
References bat_add(), brix_http_req(), brix_http_resp_free(), brix_status_clear(), brix_weburl::host, brix_status::msg, brix_weburl::port, brix_http_resp::status, and brix_weburl::tls.
Referenced by web_write_suite().
web_put_get_verify()
static void web_put_get_verify (const brix_weburl * u, const char * fpath, const char * xtra, int verify, const char * ca, xrd_battery * b) static
Definition at line 388 of file xrd_battery.c.
References bat_add(), bat_upload_src_fd(), brix_http_download(), brix_http_upload(), brix_status_clear(), close(), fill_pattern(), brix_weburl::host, lseek(), brix_status::msg, brix_weburl::port, read(), brix_weburl::tls, and tmpfile_with().
Referenced by web_write_suite().
web_read_suite()
static int web_read_suite (const brix_weburl * u, const char * xtra, int verify, const char * ca, xrd_battery * b) static
Definition at line 349 of file xrd_battery.c.
References bat_add(), brix_http_header(), brix_http_req(), brix_http_resp_free(), brix_status_clear(), xrd_battery::err, brix_weburl::host, brix_status::msg, brix_weburl::port, xrd_battery::reachable, brix_http_resp::status, and brix_weburl::tls.
Referenced by battery_web().
web_write_suite()
static void web_write_suite (const brix_weburl * u, const char * xtra, int verify, const char * ca, xrd_battery * b) static
Definition at line 458 of file xrd_battery.c.
References bat_add(), brix_http_req(), brix_http_resp_free(), brix_status_clear(), brix_weburl::host, brix_status::msg, brix_weburl::port, brix_http_resp::status, brix_weburl::tls, web_move_delete(), and web_put_get_verify().
Referenced by battery_web().
write_checksum()
static void write_checksum (brix_conn * c, const char * file, const uint8_t * payload, size_t payload_len, xrd_battery * b) static
Definition at line 164 of file xrd_battery.c.
References bat_add(), brix_cksum_fd(), brix_query_cksum(), brix_status_clear(), c, close(), tmpfile_with(), and XRDC_CK_ADLER32.
Referenced by probe_write_suite().
write_readv()
static void write_readv (brix_conn * c, const char * file, const uint8_t * payload, xrd_battery * b) static
Definition at line 142 of file xrd_battery.c.
References bat_add(), brix_file_close(), brix_file_open_read(), brix_file_readv(), brix_status_clear(), brix_readv_seg::buf, c, brix_readv_seg::got, brix_readv_seg::len, brix_status::msg, and brix_readv_seg::offset.
Referenced by probe_write_suite().
write_rename_truncate_rm()
static void write_rename_truncate_rm (brix_conn * c, const char * dir, const char * file, const char * file2, int sym_left, xrd_battery * b) static
Definition at line 238 of file xrd_battery.c.
References bat_add(), brix_mv(), brix_rm(), brix_rmdir(), brix_status_clear(), brix_truncate(), c, and brix_status::msg.
Referenced by probe_write_suite().
write_symlink_ops()
static void write_symlink_ops (brix_conn * c, const char * dir, const char * file, int ext_sl, int ext_rl, int * sym_left, xrd_battery * b) static
Definition at line 204 of file xrd_battery.c.
References bat_add(), brix_readlink(), brix_rm(), brix_status_clear(), brix_symlink(), c, and brix_status::msg.
Referenced by probe_write_suite().
write_verify()
static int write_verify (brix_conn * c, const char * file, const uint8_t * payload, size_t payload_len, xrd_battery * b) static
Definition at line 124 of file xrd_battery.c.
References bat_add(), brix_file_close(), brix_file_open_write(), brix_file_write(), brix_status_clear(), c, and brix_status::msg.
Referenced by probe_write_suite().
write_xattr_ops()
static void write_xattr_ops (brix_conn * c, const char * file, xrd_battery * b) static
Definition at line 186 of file xrd_battery.c.
References bat_add(), brix_fattr_del(), brix_fattr_get(), brix_fattr_set(), brix_status_clear(), c, and brix_status::msg.
Referenced by probe_write_suite().
xrd_run_battery()
void xrd_run_battery (const char * endpoint, int do_write, int verify, xrd_battery * b)
Definition at line 653 of file xrd_battery.c.
References battery_root(), battery_s3(), battery_web(), brix_endpoint_parse(), brix_is_web_url(), brix_status_clear(), brix_token_discover(), brix_weburl_parse(), xrd_battery::endpoint, xrd_battery::err, brix_weburl::is_s3, brix_status::msg, xrd_battery::protocol, region, and brix_opts::verify_host.
Referenced by doctor_run_batteries().