nginx-xrootd: client/apps/diag/xrd_mount.c File Reference
xrd_mount.c File Reference
#include "xrd_internal.h"
Functions
int xrd_login (int argc, char **argv)
int xrd_ping (int argc, char **argv)
const char * xrd_role_str (uint32_t flags)
int xrd_whoami (int argc, char **argv)
int xrd_caps (int argc, char **argv)
int run_cmd (char *const cmd_argv[])
void mountinfo_unescape (const char *in, char *out, size_t outsz)
int xrd_list_mounts (void)
static int xrd_mount_parse_selectors (int argc, char **argv, int *legacy, int *list, int *out_i)
static char ** xrd_mount_build_argv (int argc, char **argv, int i, const char *driver, int legacy, char *endpoint, size_t endpoint_sz)
int xrd_mount (int argc, char **argv)
int xrd_unmount (int argc, char **argv)
Function Documentation
mountinfo_unescape()
void mountinfo_unescape (const char * in, char * out, size_t outsz)
Definition at line 230 of file xrd_mount.c.
run_cmd()
int run_cmd (char *const cmd_argv[])
Definition at line 208 of file xrd_mount.c.
Referenced by xrd_unmount().
xrd_caps()
int xrd_caps (int argc, char ** argv)
Definition at line 168 of file xrd_mount.c.
References brix_close(), brix_connect(), brix_crypto_init(), brix_endpoint_parse(), brix_shellcode(), brix_status_clear(), brix_tls_info(), c, xrd_probe::caps, brix_url::host, xrd_cap_kv::key, brix_status::msg, xrd_probe::ncaps, brix_url::port, xrd_cap_kv::val, brix_opts::verify_host, xrd_probe_caps(), and xrd_role_str().
xrd_list_mounts()
int xrd_list_mounts (void)
Definition at line 334 of file xrd_mount.c.
Referenced by cmd_mounts(), and xrd_mount().
xrd_login()
int xrd_login (int argc, char ** argv)
Definition at line 13 of file xrd_mount.c.
References brix_cred_autorefresh(), brix_cred_diagnose(), and brix_crypto_init().
xrd_mount()
int xrd_mount (int argc, char ** argv)
Definition at line 464 of file xrd_mount.c.
References driver, exec_tool(), xrd_list_mounts(), xrd_mount_build_argv(), xrd_mount_parse_selectors(), and XRDC_PATH_MAX.
xrd_mount_build_argv()
static char ** xrd_mount_build_argv (int argc, char ** argv, int i, const char * driver, int legacy, char * endpoint, size_t endpoint_sz) static
Definition at line 430 of file xrd_mount.c.
References brix_alias_resolve(), and driver.
Referenced by xrd_mount().
xrd_mount_parse_selectors()
static int xrd_mount_parse_selectors (int argc, char ** argv, int * legacy, int * list, int * out_i) static
Definition at line 382 of file xrd_mount.c.
Referenced by xrd_mount().
xrd_ping()
int xrd_ping (int argc, char ** argv)
Definition at line 44 of file xrd_mount.c.
References brix_close(), brix_connect(), brix_crypto_init(), brix_endpoint_parse(), brix_shellcode(), brix_stat(), brix_status_clear(), c, brix_url::host, brix_status::msg, brix_url::port, and brix_opts::verify_host.
xrd_role_str()
const char * xrd_role_str (uint32_t flags)
Definition at line 116 of file xrd_mount.c.
References kXR_isManager, and kXR_isServer.
Referenced by doctor_json_head(), doctor_report_conn(), and xrd_caps().
xrd_unmount()
int xrd_unmount (int argc, char ** argv)
Definition at line 500 of file xrd_mount.c.
References c, and run_cmd().
xrd_whoami()
int xrd_whoami (int argc, char ** argv)
Definition at line 130 of file xrd_mount.c.
References access(), brix_close(), brix_connect(), brix_crypto_init(), brix_endpoint_parse(), brix_gsi_cert_explain(), brix_proxy_default_path(), brix_shellcode(), brix_status_clear(), brix_token_discover(), brix_token_explain(), c, brix_url::host, brix_status::msg, brix_url::port, and brix_opts::verify_host.