nginx-xrootd: client/apps/copy/xrdcp_recursive.c File Reference
xrdcp_recursive.c File Reference
#include "xrdcp_internal.h"
Data Structures
struct recdl_ctx_t
struct walk_child_t
Functions
int source_has_glob (const char *s)
int expand_source (const char *s_in, const brix_opts *co, char ***out, size_t *n, size_t *cap)
void mkdirs_for (const char *filepath)
int mkcol_parents (const mkcol_ctx_t *m, const char *rel, brix_status *st)
static int place_to_web (const char *dstroot, const place_ctx_t *p)
static int place_to_local (const char *dstroot, const place_ctx_t *p)
int recursive_place (const char *dstroot, const place_ctx_t *p)
void ensure_web_dst_base (const char *dstroot, const brix_copy_opts *fo, const brix_opts *co)
static const char * strip_prefix_rel (const char *path, const char *prefix, size_t plen, char *relbuf, size_t relbufsz)
static void recdl_transfer_one (recdl_ctx_t *c, const char *srcurl, const char *rel)
static int s3_split_bucket_prefix (const brix_weburl *u, char *bucket, size_t bucketsz, char *prefix, size_t prefixsz)
static void s3_download_loop (recdl_ctx_t *c, const brix_weburl *u, char **keys, const char *bucket, const char *prefix)
int recursive_s3_download (const brix_weburl *u, const char *dstdir, const brix_copy_opts *fo, const brix_opts *co, int retries)
static void web_download_loop (recdl_ctx_t *c, const brix_weburl *u, char **paths, const char *prefix)
int recursive_web_download (const char *src, const char *dstdir, const brix_copy_opts *o, const brix_opts *co, int retries)
int web_join (const char *base, const char *rel, char *out, size_t outsz)
static int walk_child_paths (const char *localdir, const char *rel, const char *name, walk_child_t *out)
static void walk_handle_dir (web_upload_ctx *c, const walk_child_t *ch)
static void walk_handle_file (web_upload_ctx *c, const walk_child_t *ch)
void web_upload_walk (web_upload_ctx *c, const char *localdir, const char *rel)
int recursive_web_upload (const char *localdir, const char *dst, const brix_copy_opts *o, const brix_opts *co, int retries)
Function Documentation
ensure_web_dst_base()
void ensure_web_dst_base (const char * dstroot, const brix_copy_opts * fo, const brix_opts * co)
Definition at line 228 of file xrdcp_recursive.c.
References brix_copy_opts::bearer, brix_is_web_url(), brix_status_clear(), brix_webdav_mkcol(), brix_weburl_parse(), brix_opts::ca_dir, brix_copy_opts::dry_run, brix_weburl::is_s3, brix_weburl::path, brix_opts::verify_host, and XRDC_PATH_MAX.
Referenced by recursive_s3_download(), and recursive_web_download().
expand_source()
int expand_source (const char * s_in, const brix_opts * co, char *** out, size_t * n, size_t * cap)
Definition at line 33 of file xrdcp_recursive.c.
References brix_alias_resolve(), brix_glob(), brix_glob_free(), brix_is_web_url(), brix_status_clear(), is_root_url(), brix_status::kxr, brix_status::msg, s, source_has_glob(), str_append(), XRDC_EUSAGE, and XRDC_PATH_MAX.
Referenced by build_and_preflight_credentials().
mkcol_parents()
int mkcol_parents (const mkcol_ctx_t * m, const char * rel, brix_status * st)
Definition at line 114 of file xrdcp_recursive.c.
References mkcol_ctx_t::base, mkcol_ctx_t::bearer, brix_webdav_mkcol(), brix_opts::ca_dir, mkcol_ctx_t::co, mkcol_ctx_t::du, brix_weburl::is_s3, brix_opts::verify_host, and XRDC_PATH_MAX.
Referenced by place_to_web().
mkdirs_for()
void mkdirs_for (const char * filepath)
Definition at line 89 of file xrdcp_recursive.c.
References XRDC_PATH_MAX.
Referenced by place_to_local().
place_to_local()
static int place_to_local (const char * dstroot, const place_ctx_t * p) static
Definition at line 183 of file xrdcp_recursive.c.
References brix_status_set(), place_ctx_t::co, copy_one_with_retry(), place_ctx_t::fo, mkdirs_for(), place_ctx_t::rel, place_ctx_t::retries, place_ctx_t::srcurl, place_ctx_t::st, XRDC_EUSAGE, and XRDC_PATH_MAX.
Referenced by recursive_place().
place_to_web()
static int place_to_web (const char * dstroot, const place_ctx_t * p) static
Definition at line 144 of file xrdcp_recursive.c.
References brix_copy_opts::bearer, brix_status_set(), brix_weburl_parse(), place_ctx_t::co, copy_one_with_retry(), place_ctx_t::fo, brix_weburl::host, mkcol_parents(), brix_weburl::path, brix_weburl::port, brix_weburl::proto, place_ctx_t::rel, place_ctx_t::retries, place_ctx_t::srcurl, place_ctx_t::st, web_scheme_str(), XRDC_EUSAGE, and XRDC_PATH_MAX.
Referenced by recursive_place().
recdl_transfer_one()
static void recdl_transfer_one (recdl_ctx_t * c, const char * srcurl, const char * rel) static
Definition at line 301 of file xrdcp_recursive.c.
References brix_status_clear(), c, place_ctx_t::co, place_ctx_t::fo, brix_status::msg, recursive_place(), place_ctx_t::rel, place_ctx_t::retries, place_ctx_t::srcurl, and place_ctx_t::st.
Referenced by s3_download_loop(), and web_download_loop().
recursive_place()
int recursive_place (const char * dstroot, const place_ctx_t * p)
Definition at line 208 of file xrdcp_recursive.c.
References brix_copy_filter_match(), brix_is_web_url(), brix_copy_opts::dry_run, place_ctx_t::fo, place_to_local(), place_to_web(), place_ctx_t::rel, and place_ctx_t::srcurl.
Referenced by recdl_transfer_one().
recursive_s3_download()
int recursive_s3_download (const brix_weburl * u, const char * dstdir, const brix_copy_opts * fo, const brix_opts * co, int retries)
Definition at line 400 of file xrdcp_recursive.c.
References brix_s3_list(), brix_status_clear(), brix_strv_free(), c, brix_opts::ca_dir, ensure_web_dst_base(), brix_status::msg, region, brix_copy_opts::s3_access, s3_download_loop(), brix_copy_opts::s3_region, brix_copy_opts::s3_secret, s3_split_bucket_prefix(), brix_copy_opts::silent, brix_opts::verify_host, and XRDC_PATH_MAX.
Referenced by recursive_web_download().
recursive_web_download()
int recursive_web_download (const char * src, const char * dstdir, const brix_copy_opts * o, const brix_opts * co, int retries)
Definition at line 478 of file xrdcp_recursive.c.
References brix_copy_opts::bearer, brix_status_clear(), brix_strv_free(), brix_webdav_list(), brix_weburl_parse(), c, brix_opts::ca_dir, ensure_web_dst_base(), brix_weburl::is_s3, brix_status::msg, brix_weburl::path, brix_copy_opts::recursive, recursive_s3_download(), brix_copy_opts::silent, brix_opts::verify_host, web_download_loop(), and XRDC_PATH_MAX.
Referenced by xrdcp_dispatch_recursive_web_download().
recursive_web_upload()
int recursive_web_upload (const char * localdir, const char * dst, const brix_copy_opts * o, const brix_opts * co, int retries)
Definition at line 703 of file xrdcp_recursive.c.
References brix_copy_opts::bearer, brix_status_clear(), brix_webdav_mkcol(), brix_weburl_parse(), c, brix_opts::ca_dir, brix_copy_opts::dry_run, brix_weburl::is_s3, brix_status::msg, brix_weburl::path, brix_weburl::proto, brix_copy_opts::recursive, brix_copy_opts::silent, brix_opts::verify_host, web_scheme_str(), web_upload_walk(), and XRDC_PATH_MAX.
Referenced by xrdcp_dispatch_recursive_web_upload().
s3_download_loop()
static void s3_download_loop (recdl_ctx_t * c, const brix_weburl * u, char ** keys, const char * bucket, const char * prefix) static
Definition at line 364 of file xrdcp_recursive.c.
References c, brix_weburl::host, key, brix_weburl::port, brix_weburl::proto, recdl_transfer_one(), rel_is_unsafe(), scheme, strip_prefix_rel(), web_scheme_str(), XRDC_NAME_MAX, and XRDC_PATH_MAX.
Referenced by recursive_s3_download().
s3_split_bucket_prefix()
static int s3_split_bucket_prefix (const brix_weburl * u, char * bucket, size_t bucketsz, char * prefix, size_t prefixsz) static
Definition at line 333 of file xrdcp_recursive.c.
References brix_weburl::path.
Referenced by recursive_s3_download().
source_has_glob()
int source_has_glob (const char * s)
Definition at line 15 of file xrdcp_recursive.c.
References brix_has_glob(), and s.
Referenced by expand_source().
strip_prefix_rel()
static const char * strip_prefix_rel (const char * path, const char * prefix, size_t plen, char * relbuf, size_t relbufsz) static
Definition at line 279 of file xrdcp_recursive.c.
References path_basename().
Referenced by s3_download_loop(), and web_download_loop().
walk_child_paths()
static int walk_child_paths (const char * localdir, const char * rel, const char * name, walk_child_t * out) static
Definition at line 562 of file xrdcp_recursive.c.
References walk_child_t::local, name, and walk_child_t::rel.
Referenced by web_upload_walk().
walk_handle_dir()
static void walk_handle_dir (web_upload_ctx * c, const walk_child_t * ch) static
Definition at line 591 of file xrdcp_recursive.c.
References brix_status_clear(), brix_webdav_mkcol(), c, walk_child_t::local, brix_status::msg, walk_child_t::rel, web_join(), web_upload_walk(), and XRDC_PATH_MAX.
Referenced by web_upload_walk().
walk_handle_file()
static void walk_handle_file (web_upload_ctx * c, const walk_child_t * ch) static
Definition at line 618 of file xrdcp_recursive.c.
References brix_copy_filter_match(), brix_status_clear(), c, copy_one_with_retry(), walk_child_t::local, brix_status::msg, walk_child_t::rel, web_join(), and XRDC_PATH_MAX.
Referenced by web_upload_walk().
web_download_loop()
static void web_download_loop (recdl_ctx_t * c, const brix_weburl * u, char ** paths, const char * prefix) static
Definition at line 444 of file xrdcp_recursive.c.
References c, brix_weburl::host, brix_weburl::port, brix_weburl::proto, recdl_transfer_one(), rel_is_unsafe(), scheme, strip_prefix_rel(), web_scheme_str(), XRDC_NAME_MAX, and XRDC_PATH_MAX.
Referenced by recursive_web_download().
web_join()
int web_join (const char * base, const char * rel, char * out, size_t outsz)
Definition at line 538 of file xrdcp_recursive.c.
Referenced by walk_handle_dir(), and walk_handle_file().
web_upload_walk()
void web_upload_walk (web_upload_ctx * c, const char * localdir, const char * rel)
Definition at line 660 of file xrdcp_recursive.c.
References c, walk_child_t::local, lstat(), stat(), walk_child_paths(), walk_handle_dir(), and walk_handle_file().
Referenced by recursive_web_upload(), and walk_handle_dir().