nginx-xrootd: client/apps/cksum/xrdckverify.c File Reference
xrdckverify.c File Reference
#include "brix.h"
#include "core/version.h"
#include "core/progname.h"
#include <stdio.h>
#include <string.h>
Functions
static int usage_fp (FILE *out, const char *prog, int rc)
static int usage (const char *prog, int rc)
static int ckv_handle_early_flags (int argc, char **argv, int *exit_code)
static int ckv_parse_args (int argc, char **argv, brix_ckv_mode *mode, const char **algo, const char **file, int *quiet, int *exit_code)
static int ckv_report_result (brix_ckv_result r, const char *file, const brix_ckv_report *rep, const brix_status *st, int quiet)
int brix_xrdckverify_main (int argc, char **argv)
Function Documentation
brix_xrdckverify_main()
int brix_xrdckverify_main (int argc, char ** argv)
Definition at line 207 of file xrdckverify.c.
References brix_cks_verify_file(), brix_status_clear(), ckv_handle_early_flags(), ckv_parse_args(), ckv_report_result(), and XRDC_CKV_AUTO.
Referenced by dispatch().
ckv_handle_early_flags()
static int ckv_handle_early_flags (int argc, char ** argv, int * exit_code) static
Definition at line 66 of file xrdckverify.c.
References brix_client_version(), brix_prog_base(), and usage_fp().
Referenced by brix_xrdckverify_main().
ckv_parse_args()
static int ckv_parse_args (int argc, char ** argv, brix_ckv_mode * mode, const char ** algo, const char ** file, int * quiet, int * exit_code) static
Definition at line 104 of file xrdckverify.c.
References usage(), XRDC_CKV_AUTO, XRDC_CKV_CACHE, and XRDC_CKV_STORAGE.
Referenced by brix_xrdckverify_main().
ckv_report_result()
static int ckv_report_result (brix_ckv_result r, const char * file, const brix_ckv_report * rep, const brix_status * st, int quiet) static
Definition at line 167 of file xrdckverify.c.
References brix_ckv_report::algo, brix_ckv_report::computed, brix_status::msg, brix_ckv_report::recorded, brix_ckv_report::source, XRDC_CKV_MISMATCH, XRDC_CKV_NO_RECORD, XRDC_CKV_OK, and XRDC_CKV_UNSUPPORTED.
Referenced by brix_xrdckverify_main().
usage()
static int usage (const char * prog, int rc) static
Definition at line 42 of file xrdckverify.c.
References usage_fp().
usage_fp()
static int usage_fp (FILE * out, const char * prog, int rc) static
Definition at line 24 of file xrdckverify.c.
References brix_prog_base(), and brix_usage_footer().
Referenced by ckv_handle_early_flags(), and usage().