nginx-xrootd: client/apps/cksum/xrdcinfo.c File Reference
xrdcinfo.c File Reference
#include "core/version.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <sys/types.h>
#include <sys/xattr.h>
Data Structures
struct xmeta_hdr_t
struct xmeta_state_t
Macros
#define XMETA_STOCK_VERSION 4
#define XMETA_EXT_MAGIC 0x31584358u /* "XCX1" */
#define SEC_STATE 0x0001
#define SEC_DIGEST 0x0002
#define SEC_BLOCKCRC 0x0003
#define SEC_ORIGIN 0x0004
#define F_VERIFIED 0x0001u
#define F_EXPIRES 0x0002u
Functions
static uint16_t rd_u16 (const uint8_t *b, size_t off)
static uint32_t rd_u32 (const uint8_t *b, size_t off)
static uint64_t rd_u64 (const uint8_t *b, size_t off)
static ssize_t slurp_file (const char *path, uint8_t **buf)
static ssize_t slurp_xattr (const char *path, uint8_t **buf)
static int parse_stock_header (const uint8_t *buf, size_t n, xmeta_hdr_t *h)
static void emit_geometry (const xmeta_hdr_t *h)
static uint64_t emit_present_bitmap (const xmeta_hdr_t *h)
static void emit_ext_state (const uint8_t *buf, size_t pay, uint32_t plen, xmeta_state_t *st)
static void emit_ext_blockcrc (const uint8_t *buf, size_t n, size_t pay, uint32_t plen)
static void emit_digest_value (const uint8_t *buf, size_t base, uint16_t vl)
static void emit_ext_digest (const uint8_t *buf, size_t pay, uint32_t plen)
static void emit_ext_sections (const uint8_t *buf, size_t n, const xmeta_hdr_t *h, xmeta_state_t *st)
static void emit_flags (const xmeta_hdr_t *h, const xmeta_state_t *st, uint64_t present)
static int dump_record (const uint8_t *buf, size_t n)
int brix_xrdcinfo_main (int argc, char **argv)
Macro Definition Documentation
F_EXPIRES
#define F_EXPIRES 0x0002u
Definition at line 30 of file xrdcinfo.c.
F_VERIFIED
#define F_VERIFIED 0x0001u
Definition at line 29 of file xrdcinfo.c.
SEC_BLOCKCRC
#define SEC_BLOCKCRC 0x0003
Definition at line 27 of file xrdcinfo.c.
SEC_DIGEST
#define SEC_DIGEST 0x0002
Definition at line 26 of file xrdcinfo.c.
SEC_ORIGIN
#define SEC_ORIGIN 0x0004
Definition at line 28 of file xrdcinfo.c.
SEC_STATE
#define SEC_STATE 0x0001
Definition at line 25 of file xrdcinfo.c.
XMETA_EXT_MAGIC
#define XMETA_EXT_MAGIC 0x31584358u /* "XCX1" */
Definition at line 24 of file xrdcinfo.c.
XMETA_STOCK_VERSION
#define XMETA_STOCK_VERSION 4
Definition at line 23 of file xrdcinfo.c.
Function Documentation
brix_xrdcinfo_main()
int brix_xrdcinfo_main (int argc, char ** argv)
Definition at line 428 of file xrdcinfo.c.
References brix_client_version(), BRIX_USAGE_FOOTER, dump_record(), slurp_file(), and slurp_xattr().
Referenced by dispatch().
dump_record()
static int dump_record (const uint8_t * buf, size_t n) static
Definition at line 409 of file xrdcinfo.c.
References emit_ext_sections(), emit_flags(), emit_geometry(), emit_present_bitmap(), and parse_stock_header().
Referenced by brix_xrdcinfo_main().
emit_digest_value()
static void emit_digest_value (const uint8_t * buf, size_t base, uint16_t vl) static
Definition at line 281 of file xrdcinfo.c.
Referenced by emit_ext_digest().
emit_ext_blockcrc()
static void emit_ext_blockcrc (const uint8_t * buf, size_t n, size_t pay, uint32_t plen) static
Definition at line 256 of file xrdcinfo.c.
References rd_u32(), and rd_u64().
Referenced by emit_ext_sections().
emit_ext_digest()
static void emit_ext_digest (const uint8_t * buf, size_t pay, uint32_t plen) static
Definition at line 304 of file xrdcinfo.c.
References emit_digest_value(), and rd_u16().
Referenced by emit_ext_sections().
emit_ext_sections()
static void emit_ext_sections (const uint8_t * buf, size_t n, const xmeta_hdr_t * h, xmeta_state_t * st) static
Definition at line 335 of file xrdcinfo.c.
References emit_ext_blockcrc(), emit_ext_digest(), emit_ext_state(), xmeta_hdr_t::ext_off, rd_u16(), rd_u32(), SEC_BLOCKCRC, SEC_DIGEST, SEC_STATE, and XMETA_EXT_MAGIC.
Referenced by dump_record().
emit_ext_state()
static void emit_ext_state (const uint8_t * buf, size_t pay, uint32_t plen, xmeta_state_t * st) static
Definition at line 233 of file xrdcinfo.c.
References xmeta_state_t::dirty_hi, xmeta_state_t::dirty_lo, xmeta_state_t::flags, xmeta_state_t::have_state, xmeta_state_t::mode, rd_u32(), and rd_u64().
Referenced by emit_ext_sections().
emit_flags()
static void emit_flags (const xmeta_hdr_t * h, const xmeta_state_t * st, uint64_t present) static
Definition at line 379 of file xrdcinfo.c.
References xmeta_state_t::dirty_hi, xmeta_state_t::dirty_lo, F_VERIFIED, xmeta_state_t::flags, xmeta_state_t::have_state, xmeta_state_t::mode, xmeta_hdr_t::nblocks, and xmeta_hdr_t::no_cksum.
Referenced by dump_record().
emit_geometry()
static void emit_geometry (const xmeta_hdr_t * h) static
Definition at line 191 of file xrdcinfo.c.
References xmeta_hdr_t::bsize, xmeta_hdr_t::nblocks, and xmeta_hdr_t::size.
Referenced by dump_record().
emit_present_bitmap()
static uint64_t emit_present_bitmap (const xmeta_hdr_t * h) static
Definition at line 206 of file xrdcinfo.c.
References xmeta_hdr_t::bm, and xmeta_hdr_t::nblocks.
Referenced by dump_record().
parse_stock_header()
static int parse_stock_header (const uint8_t * buf, size_t n, xmeta_hdr_t * h) static
Definition at line 156 of file xrdcinfo.c.
References xmeta_hdr_t::bm, xmeta_hdr_t::bsize, xmeta_hdr_t::ext_off, xmeta_hdr_t::nblocks, xmeta_hdr_t::no_cksum, rd_u32(), rd_u64(), xmeta_hdr_t::size, and XMETA_STOCK_VERSION.
Referenced by dump_record().
rd_u16()
static uint16_t rd_u16 (const uint8_t * b, size_t off) static
Definition at line 33 of file xrdcinfo.c.
Referenced by emit_ext_digest(), and emit_ext_sections().
rd_u32()
static uint32_t rd_u32 (const uint8_t * b, size_t off) static
Definition at line 39 of file xrdcinfo.c.
Referenced by emit_ext_blockcrc(), emit_ext_sections(), emit_ext_state(), and parse_stock_header().
rd_u64()
static uint64_t rd_u64 (const uint8_t * b, size_t off) static
Definition at line 46 of file xrdcinfo.c.
Referenced by emit_ext_blockcrc(), emit_ext_state(), and parse_stock_header().
slurp_file()
static ssize_t slurp_file (const char * path, uint8_t ** buf) static
Definition at line 59 of file xrdcinfo.c.
Referenced by brix_xrdcinfo_main().
slurp_xattr()
static ssize_t slurp_xattr (const char * path, uint8_t ** buf) static
Definition at line 96 of file xrdcinfo.c.
Referenced by brix_xrdcinfo_main().