nginx-xrootd: client/apps/cksum/xrdcktree.c File Reference
xrdcktree.c File Reference
#include "brix.h"
#include "brix_ops.h"
#include <ctype.h>
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
struct tree_ctx
struct remote_tree_ctx
struct cktree_opts
struct ckcheck_ctx
Macros
#define TREE_HEX_MAX 129
#define TREE_LINE_MAX (TREE_HEX_MAX + 2 + XRDC_PATH_MAX)
Typedefs
typedef int(* cktree_file_fn) (const char *lpath, const char *rel, void *u)
Functions
static int is_root_url (const char *s)
static int path_join (const char *dir, const char *name, char *out, size_t outsz)
static int rel_join (const char *prefix, const char *name, char *out, size_t outsz)
static int rel_has_newline (const char *rel)
static int entry_is_dot (const char *name)
static int cktree_walk (const char *lpath, const char *rel, cktree_file_fn cb, void *u, int *errors)
static int tree_emit_file (const char *lpath, const char *rel, void *u)
static int remote_tree_visitor (const char *path, const brix_dirent *e, int depth, void *u)
static int usage_tree (const char *prog, int rc)
static int cktree_parse_args (int argc, char **argv, cktree_opts *o, int *rc)
static void cktree_run_local (const cktree_opts *o, brix_cksum_algo algo, FILE *out, int *errors)
static int cktree_run_remote (const char *prog, const cktree_opts *o, FILE *out, int *errors)
int brix_xrdcktree_main (int argc, char **argv)
static int usage_check (const char *prog, int rc)
static int ckcheck_parse_args (int argc, char **argv, const char **algo_str, brix_cksum_algo *algo, int *rc)
static int ckcheck_connect (const char *prog, const char *root, brix_url *u, brix_conn *c)
static void ckcheck_report_malformed (const char *prog, char *line)
static int ckcheck_line_algo (const ckcheck_ctx *cx, const char *hex, const char *rel, brix_cksum_algo *out_algo, const char **out_name)
static int ckcheck_digest_local (const ckcheck_ctx *cx, const char *rel, brix_cksum_algo algo, char *got)
static int ckcheck_digest_remote (const ckcheck_ctx *cx, const char *rel, const char *algo_name, char *got)
static void ckcheck_process_line (const ckcheck_ctx *cx, char *line)
int brix_xrdckcheck_main (int argc, char **argv)
Macro Definition Documentation
TREE_HEX_MAX
#define TREE_HEX_MAX 129
Definition at line 32 of file xrdcktree.c.
TREE_LINE_MAX
#define TREE_LINE_MAX (TREE_HEX_MAX + 2 + XRDC_PATH_MAX)
Definition at line 34 of file xrdcktree.c.
Typedef Documentation
cktree_file_fn
typedef int(* cktree_file_fn) (const char *lpath, const char *rel, void *u)
Definition at line 120 of file xrdcktree.c.
Function Documentation
brix_xrdckcheck_main()
int brix_xrdckcheck_main (int argc, char ** argv)
Definition at line 829 of file xrdcktree.c.
References ckcheck_ctx::algo, ckcheck_ctx::algo_str, brix_close(), ckcheck_ctx::c, c, ckcheck_connect(), ckcheck_parse_args(), ckcheck_process_line(), ckcheck_ctx::errors, ckcheck_ctx::is_remote, is_root_url(), ckcheck_ctx::mismatches, brix_url::path, ckcheck_ctx::prog, ckcheck_ctx::root, ckcheck_ctx::root_path, TREE_HEX_MAX, XRDC_CK_ADLER32, XRDC_EXIT_USAGE, and XRDC_PATH_MAX.
Referenced by dispatch().
brix_xrdcktree_main()
int brix_xrdcktree_main (int argc, char ** argv)
Definition at line 494 of file xrdcktree.c.
References cktree_opts::algo_str, brix_cksum_algo_parse(), cktree_parse_args(), cktree_run_local(), cktree_run_remote(), is_root_url(), cktree_opts::outpath, cktree_opts::root, and XRDC_EXIT_USAGE.
Referenced by dispatch().
ckcheck_connect()
static int ckcheck_connect (const char * prog, const char * root, brix_url * u, brix_conn * c) static
Definition at line 623 of file xrdcktree.c.
References brix_connect(), brix_status_clear(), brix_url_parse(), c, brix_status::msg, brix_url::scheme, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by brix_xrdckcheck_main().
ckcheck_digest_local()
static int ckcheck_digest_local (const ckcheck_ctx * cx, const char * rel, brix_cksum_algo algo, char * got) static
Definition at line 703 of file xrdcktree.c.
References brix_cksum_fd(), brix_status_clear(), close(), brix_status::msg, open(), path_join(), ckcheck_ctx::prog, ckcheck_ctx::root, TREE_HEX_MAX, and XRDC_PATH_MAX.
Referenced by ckcheck_process_line().
ckcheck_digest_remote()
static int ckcheck_digest_remote (const ckcheck_ctx * cx, const char * rel, const char * algo_name, char * got) static
Definition at line 742 of file xrdcktree.c.
References brix_query_cksum(), brix_status_clear(), ckcheck_ctx::c, brix_status::msg, ckcheck_ctx::prog, ckcheck_ctx::root_path, TREE_HEX_MAX, and XRDC_PATH_MAX.
Referenced by ckcheck_process_line().
ckcheck_line_algo()
static int ckcheck_line_algo (const ckcheck_ctx * cx, const char * hex, const char * rel, brix_cksum_algo * out_algo, const char ** out_name) static
Definition at line 673 of file xrdcktree.c.
References ckcheck_ctx::algo, ckcheck_ctx::algo_str, hex(), ckcheck_ctx::prog, XRDC_CK_ADLER32, XRDC_CK_CRC64, and XRDC_CK_MD5.
Referenced by ckcheck_process_line().
ckcheck_parse_args()
static int ckcheck_parse_args (int argc, char ** argv, const char ** algo_str, brix_cksum_algo * algo, int * rc) static
Definition at line 579 of file xrdcktree.c.
References brix_cksum_algo_parse(), usage_check(), and XRDC_EXIT_USAGE.
Referenced by brix_xrdckcheck_main().
ckcheck_process_line()
static void ckcheck_process_line (const ckcheck_ctx * cx, char * line) static
Definition at line 776 of file xrdcktree.c.
References brix_ckmf_parse_line(), ckcheck_digest_local(), ckcheck_digest_remote(), ckcheck_line_algo(), ckcheck_report_malformed(), ckcheck_ctx::errors, hex(), ckcheck_ctx::is_remote, ckcheck_ctx::mismatches, ckcheck_ctx::prog, TREE_HEX_MAX, and XRDC_PATH_MAX.
Referenced by brix_xrdckcheck_main().
ckcheck_report_malformed()
static void ckcheck_report_malformed (const char * prog, char * line) static
Definition at line 649 of file xrdcktree.c.
Referenced by ckcheck_process_line().
cktree_parse_args()
static int cktree_parse_args (int argc, char ** argv, cktree_opts * o, int * rc) static
Definition at line 357 of file xrdcktree.c.
References cktree_opts::algo_str, cktree_opts::outpath, cktree_opts::root, usage_tree(), and XRDC_EXIT_USAGE.
Referenced by brix_xrdcktree_main().
cktree_run_local()
static void cktree_run_local (const cktree_opts * o, brix_cksum_algo algo, FILE * out, int * errors) static
Definition at line 410 of file xrdcktree.c.
References tree_ctx::algo, tree_ctx::algo_name, cktree_opts::algo_str, cktree_walk(), tree_ctx::errors, tree_ctx::out, cktree_opts::root, and tree_emit_file().
Referenced by brix_xrdcktree_main().
cktree_run_remote()
static int cktree_run_remote (const char * prog, const cktree_opts * o, FILE * out, int * errors) static
Definition at line 438 of file xrdcktree.c.
References remote_tree_ctx::algo_name, cktree_opts::algo_str, brix_close(), brix_connect(), brix_status_clear(), brix_tree_walk(), brix_url_parse(), remote_tree_ctx::c, c, remote_tree_ctx::errors, brix_status::msg, remote_tree_ctx::out, brix_url::path, remote_tree_visitor(), cktree_opts::root, remote_tree_ctx::root_path, remote_tree_ctx::root_path_len, brix_url::scheme, XRDC_EXIT_USAGE, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by brix_xrdcktree_main().
cktree_walk()
static int cktree_walk (const char * lpath, const char * rel, cktree_file_fn cb, void * u, int * errors) static
Definition at line 147 of file xrdcktree.c.
References cktree_walk(), entry_is_dot(), lstat(), path_join(), rel_join(), stat(), and XRDC_PATH_MAX.
Referenced by cktree_run_local(), and cktree_walk().
entry_is_dot()
static int entry_is_dot (const char * name) static
Definition at line 129 of file xrdcktree.c.
References name.
Referenced by cktree_walk().
is_root_url()
static int is_root_url (const char * s) static
Definition at line 47 of file xrdcktree.c.
References s.
Referenced by brix_xrdckcheck_main(), brix_xrdcktree_main(), and expand_source().
path_join()
static int path_join (const char * dir, const char * name, char * out, size_t outsz) static
Definition at line 61 of file xrdcktree.c.
References name.
Referenced by ckcheck_digest_local(), and cktree_walk().
rel_has_newline()
static int rel_has_newline (const char * rel) static
Definition at line 105 of file xrdcktree.c.
Referenced by remote_tree_visitor(), and tree_emit_file().
rel_join()
static int rel_join (const char * prefix, const char * name, char * out, size_t outsz) static
Definition at line 83 of file xrdcktree.c.
References name.
Referenced by cktree_walk().
remote_tree_visitor()
static int remote_tree_visitor (const char * path, const brix_dirent * e, int depth, void * u) static
Definition at line 276 of file xrdcktree.c.
References remote_tree_ctx::algo_name, brix_query_cksum(), brix_status_clear(), remote_tree_ctx::c, remote_tree_ctx::errors, brix_statinfo::flags, brix_dirent::have_stat, hex(), kXR_isDir, brix_status::msg, remote_tree_ctx::out, rel_has_newline(), remote_tree_ctx::root_path, remote_tree_ctx::root_path_len, brix_dirent::st, and TREE_HEX_MAX.
Referenced by cktree_run_remote().
tree_emit_file()
static int tree_emit_file (const char * lpath, const char * rel, void * u) static
Definition at line 221 of file xrdcktree.c.
References tree_ctx::algo, brix_cksum_fd(), brix_status_clear(), close(), tree_ctx::errors, hex(), brix_status::msg, open(), tree_ctx::out, rel_has_newline(), and TREE_HEX_MAX.
Referenced by cktree_run_local().
usage_check()
static int usage_check (const char * prog, int rc) static
Definition at line 540 of file xrdcktree.c.
Referenced by ckcheck_parse_args().
usage_tree()
static int usage_tree (const char * prog, int rc) static
Definition at line 328 of file xrdcktree.c.
Referenced by cktree_parse_args().