nginx-xrootd: client/apps/copy/xrdcp_transfer.c File Reference
xrdcp_transfer.c File Reference
#include "xrdcp_internal.h"
Functions
static int remove_source_entry (const char *url, const brix_opts *co)
int copy_one_with_retry (const char *src, const char *dst, const brix_copy_opts *o, const brix_opts *co, int retries, brix_status *st)
int entry_meta (const char *url, const brix_opts *co, long long *size, long long *mtime)
static int entry_cksum (const char *url, const brix_opts *co, const char *algo, char *hex, size_t hexsz)
static int sync_cksum_equal (const char *src, const char *dst, const char *algo, const brix_opts *co)
static int transfer_filter_check (const char *src, const char *base, const brix_copy_opts *o, const brix_opts *co, int *src_meta, long long *src_sz, long long *src_mt)
static int transfer_sync_check (const char *src, const char *dst, const brix_copy_opts *o, const brix_opts *co, int *src_meta, long long *src_sz, long long *src_mt)
int transfer_one (const char *src, const char *dst, const brix_copy_opts *o, const brix_opts *co, int retries, int sync_mode, brix_status *st)
int relay_web_to_web (const char *src, const char *dst, const brix_copy_opts *o, const brix_opts *co, int retries, brix_status *st)
int batch_copy_one (const char *item, const char *dstdir, const brix_copy_opts *o, const brix_opts *co, int retries, int sync_mode, char *dpath, size_t dpsz, brix_status *st)
void * batch_worker (void *arg)
void batch_parallel (char **items, size_t n, const char *dst, const brix_copy_opts *o, const brix_opts *co, int retries, int sync_mode, int jobs, brix_journal *jrn, size_t *ok, size_t *skip, size_t *fail)
Function Documentation
batch_copy_one()
int batch_copy_one (const char * item, const char * dstdir, const brix_copy_opts * o, const brix_opts * co, int retries, int sync_mode, char * dpath, size_t dpsz, brix_status * st)
Definition at line 393 of file xrdcp_transfer.c.
References brix_status_set(), join_dest(), path_basename(), transfer_one(), XRDC_EUSAGE, and XRDC_NAME_MAX.
Referenced by batch_worker(), and xrdcp_batch_one().
batch_parallel()
void batch_parallel (char ** items, size_t n, const char * dst, const brix_copy_opts * o, const brix_opts * co, int retries, int sync_mode, int jobs, brix_journal * jrn, size_t * ok, size_t * skip, size_t * fail)
Definition at line 489 of file xrdcp_transfer.c.
References batch_worker(), batch_ctx::co, batch_ctx::dst, batch_ctx::fail, batch_ctx::items, batch_ctx::jrn, batch_ctx::lock, batch_ctx::n, batch_ctx::o, batch_ctx::ok, batch_ctx::retries, batch_ctx::skip, and batch_ctx::sync_mode.
Referenced by xrdcp_dispatch_batch().
batch_worker()
void * batch_worker (void * arg)
Definition at line 427 of file xrdcp_transfer.c.
References batch_copy_one(), brix_journal_has(), brix_journal_mark(), brix_status_clear(), batch_ctx::co, brix_copy_opts::dry_run, batch_ctx::dst, batch_ctx::fail, batch_ctx::items, batch_ctx::jrn, batch_ctx::lock, brix_status::msg, batch_ctx::n, batch_ctx::next, batch_ctx::o, batch_ctx::ok, batch_ctx::retries, brix_copy_opts::silent, batch_ctx::skip, batch_ctx::sync_mode, and XRDC_PATH_MAX.
Referenced by batch_parallel().
copy_one_with_retry()
int copy_one_with_retry (const char * src, const char * dst, const brix_copy_opts * o, const brix_opts * co, int retries, brix_status * st)
Definition at line 51 of file xrdcp_transfer.c.
References both_web(), brix_copy(), brix_jitter_ms(), brix_status_clear(), brix_status::msg, relay_web_to_web(), and brix_copy_opts::silent.
Referenced by place_to_local(), place_to_web(), relay_web_to_web(), transfer_one(), walk_handle_file(), xrdcp_dispatch_recursive_web_download(), and xrdcp_dispatch_recursive_web_upload().
entry_cksum()
static int entry_cksum (const char * url, const brix_opts * co, const char * algo, char * hex, size_t hexsz) static
Definition at line 139 of file xrdcp_transfer.c.
References brix_cksum_algo_parse(), brix_cksum_fd(), brix_close(), brix_connect(), brix_is_web_url(), brix_query_cksum(), brix_status_clear(), brix_url_parse(), c, close(), hex(), open(), brix_url::path, brix_url::scheme, XRDC_SCHEME_LOCAL, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by sync_cksum_equal().
entry_meta()
int entry_meta (const char * url, const brix_opts * co, long long * size, long long * mtime)
Definition at line 97 of file xrdcp_transfer.c.
References brix_close(), brix_connect(), brix_is_web_url(), brix_stat(), brix_status_clear(), brix_url_parse(), c, brix_statinfo::flags, kXR_isDir, brix_statinfo::mtime, brix_url::path, brix_url::scheme, brix_statinfo::size, stat(), XRDC_SCHEME_LOCAL, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by transfer_filter_check(), and transfer_sync_check().
relay_web_to_web()
int relay_web_to_web (const char * src, const char * dst, const brix_copy_opts * o, const brix_opts * co, int retries, brix_status * st)
Definition at line 344 of file xrdcp_transfer.c.
References brix_status_set(), close(), copy_one_with_retry(), brix_copy_opts::force, brix_copy_opts::recursive, brix_copy_opts::silent, XRDC_ESOCK, XRDC_EUSAGE, and XRDC_PATH_MAX.
Referenced by copy_one_with_retry().
remove_source_entry()
static int remove_source_entry (const char * url, const brix_opts * co) static
Definition at line 25 of file xrdcp_transfer.c.
References brix_close(), brix_connect(), brix_rm(), brix_status_clear(), brix_url_parse(), c, brix_url::path, brix_url::scheme, XRDC_SCHEME_LOCAL, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by transfer_one().
sync_cksum_equal()
static int sync_cksum_equal (const char * src, const char * dst, const char * algo, const brix_opts * co) static
Definition at line 174 of file xrdcp_transfer.c.
References entry_cksum().
Referenced by transfer_sync_check().
transfer_filter_check()
static int transfer_filter_check (const char * src, const char * base, const brix_copy_opts * o, const brix_opts * co, int * src_meta, long long * src_sz, long long * src_mt) static
Definition at line 208 of file xrdcp_transfer.c.
References brix_copy_filter_match(), entry_meta(), and brix_copy_opts::recursive.
Referenced by transfer_one().
transfer_one()
int transfer_one (const char * src, const char * dst, const brix_copy_opts * o, const brix_opts * co, int retries, int sync_mode, brix_status * st)
Definition at line 293 of file xrdcp_transfer.c.
References copy_one_with_retry(), brix_copy_opts::dry_run, path_basename(), brix_copy_opts::recursive, brix_copy_opts::remove_source, remove_source_entry(), brix_copy_opts::sync, brix_copy_opts::sync_delete, transfer_filter_check(), transfer_sync_check(), and XRDC_NAME_MAX.
Referenced by batch_copy_one(), and xrdcp_dispatch_single().
transfer_sync_check()
static int transfer_sync_check (const char * src, const char * dst, const brix_copy_opts * o, const brix_opts * co, int * src_meta, long long * src_sz, long long * src_mt) static
Definition at line 243 of file xrdcp_transfer.c.
References brix_sync_should_skip(), entry_meta(), brix_copy_opts::sync_cksum_algo, sync_cksum_equal(), brix_copy_opts::sync_cmp, and XRDC_SYNC_CKSUM.
Referenced by transfer_one().