nginx-xrootd: client/apps/copy/xrdcp.c File Reference
xrdcp.c File Reference
#include "xrdcp_internal.h"
#include "core/version.h"
Data Structures
struct xrdcp_strlist
struct xrdcp_opts_t
struct xrdcp_lists_t
struct xrdcp_cli_state
struct xrdcp_transfer_ctx
struct xrdcp_tally_t
Macros
#define XRDCP_PARSE_EXIT_OK 100
Functions
static void usage_fp (FILE *out)
void usage (void)
int str_append (char ***list, size_t *n, size_t *cap, const char *s)
void str_free (char **list, size_t n)
static int alias_name_of (const char *arg, char *name, size_t sz)
static void fold_alias_creds (const brix_alias_info *info, brix_copy_opts *o)
void merge_alias_auth (const char *arg, brix_copy_opts *o)
void path_basename (const char *p, char *out, size_t sz)
static char * manifest_trim (char *line)
int read_manifest (const char *file, char ***list, size_t *n, size_t *cap)
int is_root_url (const char *s)
int is_s3_url (const char *s)
int uses_cred_auth (const char *s)
int is_local_dir (const char *p)
int dest_is_dir (const char *dst, const brix_opts *co)
int join_dest (const char *dstdir, const char *base, char *out, size_t sz)
int both_web (const char *src, const char *dst)
const char * web_scheme_str (brix_web_proto pr)
int rel_is_unsafe (const char *rel)
void xrdcp_progress (void *arg, long long done, long long total)
static int xrdcp_validate_flag_matrix (brix_copy_opts *opts, int sync_mode, int verify)
static int xrdcp_collect_sources (const xrdcp_strlist *pos, const char *from, xrdcp_strlist *srcs)
static int xrdcp_finalize_journal (xrdcp_opts_t *o)
static int validate_and_finalize_args (xrdcp_opts_t *o, xrdcp_lists_t *l)
static int xrdcp_parse_basic_option (xrdcp_cli_state *s, int argc, char **argv, size_t *i)
static int xrdcp_parse_manifest_option (xrdcp_cli_state *s, int argc, char **argv, size_t *i)
static int xrdcp_parse_sync_check (brix_copy_opts *opts, const char *mode)
static int xrdcp_parse_pattern_option (xrdcp_cli_state *s, int argc, char **argv, size_t *i)
static int xrdcp_parse_sync_filter_option (xrdcp_cli_state *s, int argc, char **argv, size_t *i)
static int xrdcp_parse_auth_data_option (xrdcp_cli_state *s, int argc, char **argv, size_t *i)
static int xrdcp_parse_transport_option (xrdcp_cli_state *s, int argc, char **argv, size_t *i)
static int xrdcp_parse_tpc_mode (brix_copy_opts *opts, const char *mode)
static int xrdcp_parse_remote_auth_option (xrdcp_cli_state *s, int argc, char **argv, size_t *i)
static int xrdcp_parse_option (xrdcp_cli_state *s, int argc, char **argv, size_t *i)
static int parse_and_validate_args (int argc, char **argv, xrdcp_opts_t *o, xrdcp_lists_t *l)
static void xrdcp_lists_free (xrdcp_lists_t *l)
static struct brix_cred_store * build_and_preflight_credentials (xrdcp_opts_t *o, xrdcp_lists_t *l)
static void xrdcp_hint_failed_source (const char *src, const char *dst, const brix_status *st)
static int xrdcp_dispatch_recursive_web_download (const xrdcp_transfer_ctx *ctx)
static int xrdcp_dispatch_recursive_web_upload (const xrdcp_transfer_ctx *ctx)
static int xrdcp_try_recursive_web (const xrdcp_transfer_ctx *ctx, int *handled)
static void xrdcp_enable_progress_if_needed (xrdcp_transfer_ctx *ctx, xrdcp_prog *ps, char *label, size_t label_len)
static int xrdcp_dispatch_single (xrdcp_transfer_ctx *ctx)
static brix_journal * xrdcp_open_batch_journal (const xrdcp_transfer_ctx *ctx, brix_status *st, int *rc)
static void xrdcp_batch_one (const xrdcp_transfer_ctx *ctx, brix_journal *jrn, xrdcp_tally_t *t, size_t idx)
static int xrdcp_dispatch_batch (xrdcp_transfer_ctx *ctx)
static int dispatch_transfer (xrdcp_opts_t *o, xrdcp_lists_t *l)
int main (int argc, char **argv)
Macro Definition Documentation
XRDCP_PARSE_EXIT_OK
#define XRDCP_PARSE_EXIT_OK 100
Definition at line 8 of file xrdcp.c.
Function Documentation
alias_name_of()
static int alias_name_of (const char * arg, char * name, size_t sz) static
Definition at line 215 of file xrdcp.c.
References name.
Referenced by merge_alias_auth().
both_web()
int both_web (const char * src, const char * dst)
Definition at line 413 of file xrdcp.c.
References brix_is_web_url().
Referenced by copy_one_with_retry().
build_and_preflight_credentials()
static struct brix_cred_store * build_and_preflight_credentials (xrdcp_opts_t * o, xrdcp_lists_t * l) static
Definition at line 991 of file xrdcp.c.
References xrdcp_opts_t::auto_refresh, brix_copy_opts::bearer, brix_cli_cred_store_build(), brix_cred_autorefresh(), brix_cred_diagnose(), brix_is_web_url(), xrdcp_strlist::cap, xrdcp_opts_t::conn, xrdcp_opts_t::copt, xrdcp_opts_t::dst, xrdcp_lists_t::exp, expand_source(), xrdcp_strlist::items, merge_alias_auth(), xrdcp_strlist::n, xrdcp_opts_t::oidc_account, xrdcp_lists_t::pos, xrdcp_opts_t::proxy, brix_copy_opts::remove_source, brix_copy_opts::s3_access, brix_copy_opts::s3_secret, brix_copy_opts::silent, xrdcp_lists_t::srcs, uses_cred_auth(), and xrdcp_lists_free().
Referenced by main().
dest_is_dir()
int dest_is_dir (const char * dst, const brix_opts * co)
Definition at line 377 of file xrdcp.c.
References brix_close(), brix_connect(), brix_is_web_url(), brix_stat(), brix_status_clear(), brix_url_parse(), c, brix_statinfo::flags, kXR_isDir, brix_url::path, brix_url::scheme, stat(), XRDC_SCHEME_LOCAL, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by xrdcp_dispatch_batch().
dispatch_transfer()
static int dispatch_transfer (xrdcp_opts_t * o, xrdcp_lists_t * l) static
Definition at line 1316 of file xrdcp.c.
References xrdcp_opts_t::conn, xrdcp_transfer_ctx::conn, xrdcp_opts_t::copt, xrdcp_opts_t::cred_store, xrdcp_transfer_ctx::cred_store, xrdcp_opts_t::dst, xrdcp_transfer_ctx::dst, xrdcp_lists_t::exp, xrdcp_transfer_ctx::exp, xrdcp_opts_t::force_progress, xrdcp_transfer_ctx::force_progress, xrdcp_opts_t::from, xrdcp_transfer_ctx::from, xrdcp_strlist::items, xrdcp_opts_t::jobs, xrdcp_transfer_ctx::jobs, xrdcp_opts_t::journal_path, xrdcp_transfer_ctx::journal_path, xrdcp_strlist::n, xrdcp_transfer_ctx::nexp, xrdcp_opts_t::no_progress, xrdcp_transfer_ctx::no_progress, xrdcp_transfer_ctx::opts, xrdcp_opts_t::retries, xrdcp_transfer_ctx::retries, xrdcp_opts_t::sync_mode, xrdcp_transfer_ctx::sync_mode, xrdcp_dispatch_batch(), xrdcp_dispatch_single(), and xrdcp_try_recursive_web().
Referenced by main().
fold_alias_creds()
static void fold_alias_creds (const brix_alias_info * info, brix_copy_opts * o) static
Definition at line 234 of file xrdcp.c.
References brix_alias_info::bearer, brix_copy_opts::bearer, brix_alias_info::proxy, brix_alias_info::s3_access, brix_copy_opts::s3_access, brix_alias_info::s3_region, brix_copy_opts::s3_region, brix_alias_info::s3_secret, and brix_copy_opts::s3_secret.
Referenced by merge_alias_auth().
is_local_dir()
int is_local_dir (const char * p)
Definition at line 368 of file xrdcp.c.
References stat().
Referenced by xrdcp_dispatch_recursive_web_upload(), and xrdcp_try_recursive_web().
is_root_url()
int is_root_url (const char * s)
Definition at line 340 of file xrdcp.c.
References s.
Referenced by uses_cred_auth(), and xrdcp_hint_failed_source().
is_s3_url()
int is_s3_url (const char * s)
Definition at line 351 of file xrdcp.c.
References s.
Referenced by uses_cred_auth().
join_dest()
int join_dest (const char * dstdir, const char * base, char * out, size_t sz)
Definition at line 402 of file xrdcp.c.
Referenced by batch_copy_one().
main()
int main (int argc, char ** argv)
Definition at line 1349 of file xrdcp.c.
References brix_copy_install_signal_handlers(), brix_cred_store_free(), brix_crypto_init(), build_and_preflight_credentials(), xrdcp_opts_t::conn, xrdcp_opts_t::copt, brix_opts::cred, xrdcp_opts_t::cred_store, dispatch_transfer(), xrdcp_opts_t::jobs, parse_and_validate_args(), brix_opts::verify_host, xrdcp_lists_free(), and XRDCP_PARSE_EXIT_OK.
manifest_trim()
static char * manifest_trim (char * line) static
Definition at line 301 of file xrdcp.c.
References s.
Referenced by read_manifest().
merge_alias_auth()
void merge_alias_auth (const char * arg, brix_copy_opts * o)
Definition at line 265 of file xrdcp.c.
References alias_name_of(), brix_alias_lookup(), fold_alias_creds(), name, brix_alias_info::token_file, and brix_alias_info::token_file_failed.
Referenced by build_and_preflight_credentials().
parse_and_validate_args()
static int parse_and_validate_args (int argc, char ** argv, xrdcp_opts_t * o, xrdcp_lists_t * l) static
Definition at line 921 of file xrdcp.c.
References xrdcp_strlist::cap, xrdcp_opts_t::copt, xrdcp_lists_t::excl, brix_copy_opts::excludes, xrdcp_lists_t::incl, brix_copy_opts::includes, brix_copy_opts::io_uring, xrdcp_strlist::items, xrdcp_cli_state::l, xrdcp_strlist::n, brix_copy_opts::n_excludes, brix_copy_opts::n_includes, xrdcp_cli_state::o, xrdcp_cli_state::oom, xrdcp_lists_t::pos, str_append(), validate_and_finalize_args(), XRDC_IO_URING_AUTO, XRDC_IO_URING_OFF, XRDC_IO_URING_ON, XRDCP_PARSE_EXIT_OK, and xrdcp_parse_option().
Referenced by main().
path_basename()
void path_basename (const char * p, char * out, size_t sz)
Definition at line 284 of file xrdcp.c.
Referenced by batch_copy_one(), strip_prefix_rel(), transfer_one(), and xrdcp_enable_progress_if_needed().
read_manifest()
int read_manifest (const char * file, char *** list, size_t * n, size_t * cap)
Definition at line 316 of file xrdcp.c.
References manifest_trim(), s, str_append(), and XRDC_PATH_MAX.
Referenced by xrdcp_collect_sources().
rel_is_unsafe()
int rel_is_unsafe (const char * rel)
Definition at line 441 of file xrdcp.c.
References brix_rel_is_unsafe().
Referenced by s3_download_loop(), and web_download_loop().
str_append()
int str_append (char *** list, size_t * n, size_t * cap, const char * s)
Definition at line 186 of file xrdcp.c.
References s.
Referenced by expand_source(), parse_and_validate_args(), read_manifest(), xrdcp_collect_sources(), and xrdcp_parse_pattern_option().
str_free()
void str_free (char ** list, size_t n)
Definition at line 203 of file xrdcp.c.
Referenced by xrdcp_lists_free().
usage()
void usage (void)
Definition at line 178 of file xrdcp.c.
References usage_fp().
Referenced by validate_and_finalize_args(), xrdcp_parse_option(), xrdcp_parse_sync_check(), xrdcp_parse_tpc_mode(), and xrdcp_parse_transport_option().
usage_fp()
static void usage_fp (FILE * out) static
Definition at line 115 of file xrdcp.c.
References BRIX_USAGE_FOOTER.
Referenced by usage(), and xrdcp_parse_option().
uses_cred_auth()
int uses_cred_auth (const char * s)
Definition at line 360 of file xrdcp.c.
References brix_is_web_url(), is_root_url(), is_s3_url(), and s.
Referenced by build_and_preflight_credentials().
validate_and_finalize_args()
static int validate_and_finalize_args (xrdcp_opts_t * o, xrdcp_lists_t * l) static
Definition at line 578 of file xrdcp.c.
References brix_alias_resolve(), xrdcp_opts_t::copt, xrdcp_opts_t::dst, xrdcp_opts_t::from, xrdcp_strlist::items, xrdcp_strlist::n, xrdcp_lists_t::pos, xrdcp_lists_t::srcs, xrdcp_opts_t::sync_mode, usage(), xrdcp_opts_t::verify, XRDC_PATH_MAX, xrdcp_collect_sources(), xrdcp_finalize_journal(), and xrdcp_validate_flag_matrix().
Referenced by parse_and_validate_args().
web_scheme_str()
const char * web_scheme_str (brix_web_proto pr)
Definition at line 421 of file xrdcp.c.
References XRDC_WEB_DAV, XRDC_WEB_DAVS, XRDC_WEB_HTTP, XRDC_WEB_HTTPS, XRDC_WEB_S3, and XRDC_WEB_S3S.
Referenced by place_to_web(), recursive_web_upload(), s3_download_loop(), and web_download_loop().
xrdcp_batch_one()
static void xrdcp_batch_one (const xrdcp_transfer_ctx * ctx, brix_journal * jrn, xrdcp_tally_t * t, size_t idx) static
Definition at line 1225 of file xrdcp.c.
References batch_copy_one(), brix_journal_has(), brix_journal_mark(), xrdcp_transfer_ctx::conn, brix_copy_opts::dry_run, xrdcp_transfer_ctx::dst, xrdcp_transfer_ctx::exp, xrdcp_tally_t::fail, brix_status::msg, xrdcp_transfer_ctx::nexp, xrdcp_tally_t::ok, xrdcp_transfer_ctx::opts, xrdcp_transfer_ctx::retries, brix_copy_opts::silent, xrdcp_tally_t::skip, xrdcp_tally_t::st, xrdcp_transfer_ctx::sync_mode, XRDC_PATH_MAX, and xrdcp_hint_failed_source().
Referenced by xrdcp_dispatch_batch().
xrdcp_collect_sources()
static int xrdcp_collect_sources (const xrdcp_strlist * pos, const char * from, xrdcp_strlist * srcs) static
Definition at line 530 of file xrdcp.c.
References xrdcp_strlist::cap, xrdcp_strlist::items, xrdcp_strlist::n, read_manifest(), and str_append().
Referenced by validate_and_finalize_args().
xrdcp_dispatch_batch()
static int xrdcp_dispatch_batch (xrdcp_transfer_ctx * ctx) static
Definition at line 1265 of file xrdcp.c.
References batch_parallel(), brix_status_clear(), xrdcp_transfer_ctx::conn, dest_is_dir(), xrdcp_transfer_ctx::dst, xrdcp_transfer_ctx::exp, xrdcp_tally_t::fail, xrdcp_transfer_ctx::jobs, xrdcp_transfer_ctx::nexp, xrdcp_tally_t::ok, xrdcp_transfer_ctx::opts, xrdcp_transfer_ctx::retries, brix_copy_opts::silent, xrdcp_tally_t::skip, xrdcp_tally_t::st, xrdcp_transfer_ctx::sync_mode, xrdcp_batch_one(), and xrdcp_open_batch_journal().
Referenced by dispatch_transfer().
xrdcp_dispatch_recursive_web_download()
static int xrdcp_dispatch_recursive_web_download (const xrdcp_transfer_ctx * ctx) static
Definition at line 1084 of file xrdcp.c.
References brix_is_web_url(), brix_status_clear(), xrdcp_transfer_ctx::conn, copy_one_with_retry(), xrdcp_transfer_ctx::dst, xrdcp_transfer_ctx::exp, brix_status::msg, xrdcp_transfer_ctx::nexp, xrdcp_transfer_ctx::opts, recursive_web_download(), xrdcp_transfer_ctx::retries, and xrdcp_hint_failed_source().
Referenced by xrdcp_try_recursive_web().
xrdcp_dispatch_recursive_web_upload()
static int xrdcp_dispatch_recursive_web_upload (const xrdcp_transfer_ctx * ctx) static
Definition at line 1109 of file xrdcp.c.
References brix_status_clear(), xrdcp_transfer_ctx::conn, copy_one_with_retry(), xrdcp_transfer_ctx::dst, xrdcp_transfer_ctx::exp, is_local_dir(), brix_status::msg, xrdcp_transfer_ctx::nexp, xrdcp_transfer_ctx::opts, recursive_web_upload(), xrdcp_transfer_ctx::retries, and brix_copy_opts::sync_delete.
Referenced by xrdcp_try_recursive_web().
xrdcp_dispatch_single()
static int xrdcp_dispatch_single (xrdcp_transfer_ctx * ctx) static
Definition at line 1183 of file xrdcp.c.
References brix_shellcode(), brix_status_clear(), xrdcp_transfer_ctx::conn, xrdcp_transfer_ctx::dst, xrdcp_transfer_ctx::exp, brix_status::msg, xrdcp_transfer_ctx::opts, xrdcp_transfer_ctx::retries, brix_copy_opts::silent, xrdcp_transfer_ctx::sync_mode, transfer_one(), XRDC_NAME_MAX, xrdcp_enable_progress_if_needed(), and xrdcp_hint_failed_source().
Referenced by dispatch_transfer().
xrdcp_enable_progress_if_needed()
static void xrdcp_enable_progress_if_needed (xrdcp_transfer_ctx * ctx, xrdcp_prog * ps, char * label, size_t label_len) static
Definition at line 1164 of file xrdcp.c.
References brix_mono_ns(), xrdcp_transfer_ctx::exp, xrdcp_transfer_ctx::force_progress, xrdcp_prog::label, xrdcp_prog::last_ns, xrdcp_transfer_ctx::no_progress, xrdcp_transfer_ctx::opts, path_basename(), brix_copy_opts::progress, brix_copy_opts::progress_arg, brix_copy_opts::silent, xrdcp_prog::start_ns, and xrdcp_progress().
Referenced by xrdcp_dispatch_single().
xrdcp_finalize_journal()
static int xrdcp_finalize_journal (xrdcp_opts_t * o) static
Definition at line 555 of file xrdcp.c.
References xrdcp_opts_t::from, xrdcp_opts_t::journal_path, xrdcp_opts_t::resume, and XRDC_PATH_MAX.
Referenced by validate_and_finalize_args().
xrdcp_hint_failed_source()
static void xrdcp_hint_failed_source (const char * src, const char * dst, const brix_status * st) static
Definition at line 1069 of file xrdcp.c.
References brix_cred_hint_for_status_url(), brix_hint_url_double_slash(), brix_is_web_url(), brix_status_clear(), brix_url_parse(), and is_root_url().
Referenced by xrdcp_batch_one(), xrdcp_dispatch_recursive_web_download(), and xrdcp_dispatch_single().
xrdcp_lists_free()
static void xrdcp_lists_free (xrdcp_lists_t * l) static
Definition at line 980 of file xrdcp.c.
References xrdcp_lists_t::excl, xrdcp_lists_t::exp, xrdcp_lists_t::incl, xrdcp_strlist::items, xrdcp_strlist::n, xrdcp_lists_t::pos, xrdcp_lists_t::srcs, and str_free().
Referenced by build_and_preflight_credentials(), and main().
xrdcp_open_batch_journal()
static brix_journal * xrdcp_open_batch_journal (const xrdcp_transfer_ctx * ctx, brix_status * st, int * rc) static
Definition at line 1205 of file xrdcp.c.
References brix_journal_open(), brix_status_clear(), brix_copy_opts::dry_run, xrdcp_transfer_ctx::journal_path, brix_status::msg, and xrdcp_transfer_ctx::opts.
Referenced by xrdcp_dispatch_batch().
xrdcp_parse_auth_data_option()
static int xrdcp_parse_auth_data_option (xrdcp_cli_state * s, int argc, char ** argv, size_t * i) static
Definition at line 746 of file xrdcp.c.
References xrdcp_opts_t::auto_refresh, brix_copy_opts::cksum, brix_copy_opts::compress, xrdcp_opts_t::copt, xrdcp_opts_t::force_progress, xrdcp_opts_t::oidc_account, brix_copy_opts::pgrw, xrdcp_opts_t::proxy, s, and xrdcp_opts_t::verify.
Referenced by xrdcp_parse_option().
xrdcp_parse_basic_option()
static int xrdcp_parse_basic_option (xrdcp_cli_state * s, int argc, char ** argv, size_t * i) static
Definition at line 618 of file xrdcp.c.
References brix_copy_opts::dry_run, brix_copy_opts::force, brix_copy_opts::posc, brix_copy_opts::recursive, s, brix_copy_opts::silent, and brix_copy_opts::verbose.
Referenced by xrdcp_parse_option().
xrdcp_parse_manifest_option()
static int xrdcp_parse_manifest_option (xrdcp_cli_state * s, int argc, char ** argv, size_t * i) static
Definition at line 652 of file xrdcp.c.
References xrdcp_opts_t::copt, xrdcp_opts_t::from, xrdcp_opts_t::jobs, xrdcp_opts_t::journal_path, brix_copy_opts::no_retry, xrdcp_opts_t::resume, xrdcp_opts_t::retries, and s.
Referenced by xrdcp_parse_option().
xrdcp_parse_option()
static int xrdcp_parse_option (xrdcp_cli_state * s, int argc, char ** argv, size_t * i) static
Definition at line 877 of file xrdcp.c.
References brix_client_version(), brix_opts_parse_arg(), s, usage(), usage_fp(), xrdcp_parse_auth_data_option(), xrdcp_parse_basic_option(), xrdcp_parse_manifest_option(), xrdcp_parse_remote_auth_option(), xrdcp_parse_sync_filter_option(), and xrdcp_parse_transport_option().
Referenced by parse_and_validate_args().
xrdcp_parse_pattern_option()
static int xrdcp_parse_pattern_option (xrdcp_cli_state * s, int argc, char ** argv, size_t * i) static
Definition at line 709 of file xrdcp.c.
References s, and str_append().
Referenced by xrdcp_parse_sync_filter_option().
xrdcp_parse_remote_auth_option()
static int xrdcp_parse_remote_auth_option (xrdcp_cli_state * s, int argc, char ** argv, size_t * i) static
Definition at line 843 of file xrdcp.c.
References brix_copy_opts::bearer, s, brix_copy_opts::s3_access, brix_copy_opts::s3_region, brix_copy_opts::s3_secret, brix_copy_opts::tpc_token_mode, and xrdcp_parse_tpc_mode().
Referenced by xrdcp_parse_option().
xrdcp_parse_sync_check()
static int xrdcp_parse_sync_check (brix_copy_opts * opts, const char * mode) static
Definition at line 685 of file xrdcp.c.
References brix_copy_opts::sync_cksum_algo, brix_copy_opts::sync_cmp, usage(), XRDC_SYNC_CKSUM, XRDC_SYNC_MTIME, and XRDC_SYNC_SIZE.
Referenced by xrdcp_parse_sync_filter_option().
xrdcp_parse_sync_filter_option()
static int xrdcp_parse_sync_filter_option (xrdcp_cli_state * s, int argc, char ** argv, size_t * i) static
Definition at line 728 of file xrdcp.c.
References s, xrdcp_parse_pattern_option(), and xrdcp_parse_sync_check().
Referenced by xrdcp_parse_option().
xrdcp_parse_tpc_mode()
static int xrdcp_parse_tpc_mode (brix_copy_opts * opts, const char * mode) static
Definition at line 822 of file xrdcp.c.
References brix_copy_opts::tpc_mode, usage(), XRDC_TPC_DELEGATE, XRDC_TPC_FIRST, and XRDC_TPC_ONLY.
Referenced by xrdcp_parse_remote_auth_option().
xrdcp_parse_transport_option()
static int xrdcp_parse_transport_option (xrdcp_cli_state * s, int argc, char ** argv, size_t * i) static
Definition at line 776 of file xrdcp.c.
References brix_cli_parse_io_uring(), brix_copy_opts::io_uring, brix_copy_opts::max_stall_ms, brix_copy_opts::no_retry, s, brix_copy_opts::streams, usage(), brix_copy_opts::zip, and brix_copy_opts::zip_append.
Referenced by xrdcp_parse_option().
xrdcp_progress()
void xrdcp_progress (void * arg, long long done, long long total)
Definition at line 451 of file xrdcp.c.
References brix_mono_ns(), xrdcp_prog::label, xrdcp_prog::last_ns, and xrdcp_prog::start_ns.
Referenced by xrdcp_enable_progress_if_needed().
xrdcp_try_recursive_web()
static int xrdcp_try_recursive_web (const xrdcp_transfer_ctx * ctx, int * handled) static
Definition at line 1137 of file xrdcp.c.
References brix_is_web_url(), xrdcp_transfer_ctx::dst, xrdcp_transfer_ctx::exp, is_local_dir(), xrdcp_transfer_ctx::nexp, xrdcp_transfer_ctx::opts, brix_copy_opts::recursive, xrdcp_dispatch_recursive_web_download(), and xrdcp_dispatch_recursive_web_upload().
Referenced by dispatch_transfer().
xrdcp_validate_flag_matrix()
static int xrdcp_validate_flag_matrix (brix_copy_opts * opts, int sync_mode, int verify) static
Definition at line 491 of file xrdcp.c.
References brix_copy_opts::cksum, brix_copy_opts::force, brix_copy_opts::recursive, brix_copy_opts::remove_source, brix_copy_opts::sync, and brix_copy_opts::sync_delete.
Referenced by validate_and_finalize_args().