nginx-xrootd: client/apps/copy/xrdcp_internal.h File Reference
xrdcp_internal.h File Reference
#include "brix.h"
#include "cli/xferjournal.h"
#include "cli/cli_hint.h"
#include "core/compat/crypto.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <glob.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct batch_ctx
struct web_upload_ctx
struct xrdcp_prog
struct mkcol_ctx_t
struct place_ctx_t
Functions
void usage (const char *prog)
int str_append (char ***list, size_t *n, size_t *cap, const char *s)
void str_free (char **list, size_t n)
void merge_alias_auth (const char *arg, brix_copy_opts *o)
void path_basename (const char *p, char *out, size_t sz)
int read_manifest (const char *file, char ***list, size_t *n, size_t *cap)
int is_root_url (const char *s)
int is_s3_url (const char *s)
int uses_cred_auth (const char *s)
int is_local_dir (const char *p)
int source_has_glob (const char *s)
int expand_source (const char *s_in, const brix_opts *co, char ***out, size_t *n, size_t *cap)
int dest_is_dir (const char *dst, const brix_opts *co)
int join_dest (const char *dstdir, const char *base, char *out, size_t sz)
int both_web (const char *src, const char *dst)
int copy_one_with_retry (const char *src, const char *dst, const brix_copy_opts *o, const brix_opts *co, int retries, brix_status *st)
int entry_meta (const char *url, const brix_opts *co, long long *size, long long *mtime)
int transfer_one (const char *src, const char *dst, const brix_copy_opts *o, const brix_opts *co, int retries, int sync_mode, brix_status *st)
int relay_web_to_web (const char *src, const char *dst, const brix_copy_opts *o, const brix_opts *co, int retries, brix_status *st)
int batch_copy_one (const char *item, const char *dstdir, const brix_copy_opts *o, const brix_opts *co, int retries, int sync_mode, char *dpath, size_t dpsz, brix_status *st)
void * batch_worker (void *arg)
void batch_parallel (char **items, size_t n, const char *dst, const brix_copy_opts *o, const brix_opts *co, int retries, int sync_mode, int jobs, brix_journal *jrn, size_t *ok, size_t *skip, size_t *fail)
const char * web_scheme_str (brix_web_proto pr)
void mkdirs_for (const char *filepath)
int rel_is_unsafe (const char *rel)
int mkcol_parents (const mkcol_ctx_t *m, const char *rel, brix_status *st)
int recursive_place (const char *dstroot, const place_ctx_t *p)
void ensure_web_dst_base (const char *dstroot, const brix_copy_opts *fo, const brix_opts *co)
int recursive_s3_download (const brix_weburl *u, const char *dstdir, const brix_copy_opts *fo, const brix_opts *co, int retries)
int recursive_web_download (const char *src, const char *dstdir, const brix_copy_opts *o, const brix_opts *co, int retries)
int web_join (const char *base, const char *rel, char *out, size_t outsz)
void web_upload_walk (web_upload_ctx *c, const char *localdir, const char *rel)
int recursive_web_upload (const char *localdir, const char *dst, const brix_copy_opts *o, const brix_opts *co, int retries)
void xrdcp_progress (void *arg, long long done, long long total)
Function Documentation
batch_copy_one()
int batch_copy_one (const char * item, const char * dstdir, const brix_copy_opts * o, const brix_opts * co, int retries, int sync_mode, char * dpath, size_t dpsz, brix_status * st)
Definition at line 393 of file xrdcp_transfer.c.
References brix_status_set(), join_dest(), path_basename(), transfer_one(), XRDC_EUSAGE, and XRDC_NAME_MAX.
Referenced by batch_worker(), and xrdcp_batch_one().
batch_parallel()
void batch_parallel (char ** items, size_t n, const char * dst, const brix_copy_opts * o, const brix_opts * co, int retries, int sync_mode, int jobs, brix_journal * jrn, size_t * ok, size_t * skip, size_t * fail)
Definition at line 489 of file xrdcp_transfer.c.
References batch_worker(), batch_ctx::co, batch_ctx::dst, batch_ctx::fail, batch_ctx::items, batch_ctx::jrn, batch_ctx::lock, batch_ctx::n, batch_ctx::o, batch_ctx::ok, batch_ctx::retries, batch_ctx::skip, and batch_ctx::sync_mode.
Referenced by xrdcp_dispatch_batch().
batch_worker()
void * batch_worker (void * arg)
Definition at line 427 of file xrdcp_transfer.c.
References batch_copy_one(), brix_journal_has(), brix_journal_mark(), brix_status_clear(), batch_ctx::co, brix_copy_opts::dry_run, batch_ctx::dst, batch_ctx::fail, batch_ctx::items, batch_ctx::jrn, batch_ctx::lock, brix_status::msg, batch_ctx::n, batch_ctx::next, batch_ctx::o, batch_ctx::ok, batch_ctx::retries, brix_copy_opts::silent, batch_ctx::skip, batch_ctx::sync_mode, and XRDC_PATH_MAX.
Referenced by batch_parallel().
both_web()
int both_web (const char * src, const char * dst)
Definition at line 415 of file xrdcp.c.
References brix_is_web_url().
Referenced by copy_one_with_retry().
copy_one_with_retry()
int copy_one_with_retry (const char * src, const char * dst, const brix_copy_opts * o, const brix_opts * co, int retries, brix_status * st)
Definition at line 51 of file xrdcp_transfer.c.
References both_web(), brix_copy(), brix_jitter_ms(), brix_status_clear(), brix_status::msg, relay_web_to_web(), and brix_copy_opts::silent.
Referenced by place_to_local(), place_to_web(), relay_web_to_web(), transfer_one(), walk_handle_file(), xrdcp_dispatch_recursive_web_download(), and xrdcp_dispatch_recursive_web_upload().
dest_is_dir()
int dest_is_dir (const char * dst, const brix_opts * co)
Definition at line 379 of file xrdcp.c.
References brix_close(), brix_connect(), brix_is_web_url(), brix_stat(), brix_status_clear(), brix_url_parse(), c, brix_statinfo::flags, kXR_isDir, brix_url::path, brix_url::scheme, stat(), XRDC_SCHEME_LOCAL, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by xrdcp_dispatch_batch().
ensure_web_dst_base()
void ensure_web_dst_base (const char * dstroot, const brix_copy_opts * fo, const brix_opts * co)
Definition at line 228 of file xrdcp_recursive.c.
References brix_copy_opts::bearer, brix_is_web_url(), brix_status_clear(), brix_webdav_mkcol(), brix_weburl_parse(), brix_opts::ca_dir, brix_copy_opts::dry_run, brix_weburl::is_s3, brix_weburl::path, brix_opts::verify_host, and XRDC_PATH_MAX.
Referenced by recursive_s3_download(), and recursive_web_download().
entry_meta()
int entry_meta (const char * url, const brix_opts * co, long long * size, long long * mtime)
Definition at line 97 of file xrdcp_transfer.c.
References brix_close(), brix_connect(), brix_is_web_url(), brix_stat(), brix_status_clear(), brix_url_parse(), c, brix_statinfo::flags, kXR_isDir, brix_statinfo::mtime, brix_url::path, brix_url::scheme, brix_statinfo::size, stat(), XRDC_SCHEME_LOCAL, XRDC_SCHEME_ROOT, and XRDC_SCHEME_ROOTS.
Referenced by transfer_filter_check(), and transfer_sync_check().
expand_source()
int expand_source (const char * s_in, const brix_opts * co, char *** out, size_t * n, size_t * cap)
Definition at line 33 of file xrdcp_recursive.c.
References brix_alias_resolve(), brix_glob(), brix_glob_free(), brix_is_web_url(), brix_status_clear(), is_root_url(), brix_status::kxr, brix_status::msg, s, source_has_glob(), str_append(), XRDC_EUSAGE, and XRDC_PATH_MAX.
Referenced by build_and_preflight_credentials().
is_local_dir()
int is_local_dir (const char * p)
Definition at line 370 of file xrdcp.c.
References stat().
Referenced by xrdcp_dispatch_recursive_web_upload(), and xrdcp_try_recursive_web().
is_root_url()
int is_root_url (const char * s)
Definition at line 342 of file xrdcp.c.
References s.
Referenced by uses_cred_auth(), and xrdcp_hint_failed_source().
is_s3_url()
int is_s3_url (const char * s)
Definition at line 353 of file xrdcp.c.
References s.
Referenced by uses_cred_auth().
join_dest()
int join_dest (const char * dstdir, const char * base, char * out, size_t sz)
Definition at line 404 of file xrdcp.c.
Referenced by batch_copy_one().
merge_alias_auth()
void merge_alias_auth (const char * arg, brix_copy_opts * o)
Definition at line 267 of file xrdcp.c.
References alias_name_of(), brix_alias_lookup(), fold_alias_creds(), name, brix_alias_info::token_file, and brix_alias_info::token_file_failed.
Referenced by build_and_preflight_credentials().
mkcol_parents()
int mkcol_parents (const mkcol_ctx_t * m, const char * rel, brix_status * st)
Definition at line 114 of file xrdcp_recursive.c.
References mkcol_ctx_t::base, mkcol_ctx_t::bearer, brix_webdav_mkcol(), brix_opts::ca_dir, mkcol_ctx_t::co, mkcol_ctx_t::du, brix_weburl::is_s3, brix_opts::verify_host, and XRDC_PATH_MAX.
Referenced by place_to_web().
mkdirs_for()
void mkdirs_for (const char * filepath)
Definition at line 89 of file xrdcp_recursive.c.
References XRDC_PATH_MAX.
Referenced by place_to_local().
path_basename()
void path_basename (const char * p, char * out, size_t sz)
Definition at line 286 of file xrdcp.c.
read_manifest()
int read_manifest (const char * file, char *** list, size_t * n, size_t * cap)
Definition at line 318 of file xrdcp.c.
References manifest_trim(), s, str_append(), and XRDC_PATH_MAX.
Referenced by xrdcp_collect_sources().
recursive_place()
int recursive_place (const char * dstroot, const place_ctx_t * p)
Definition at line 208 of file xrdcp_recursive.c.
References brix_copy_filter_match(), brix_is_web_url(), brix_copy_opts::dry_run, place_ctx_t::fo, place_to_local(), place_to_web(), place_ctx_t::rel, and place_ctx_t::srcurl.
Referenced by recdl_transfer_one().
recursive_s3_download()
int recursive_s3_download (const brix_weburl * u, const char * dstdir, const brix_copy_opts * fo, const brix_opts * co, int retries)
Definition at line 400 of file xrdcp_recursive.c.
References brix_s3_list(), brix_status_clear(), brix_strv_free(), c, brix_opts::ca_dir, ensure_web_dst_base(), brix_status::msg, region, brix_copy_opts::s3_access, s3_download_loop(), brix_copy_opts::s3_region, brix_copy_opts::s3_secret, s3_split_bucket_prefix(), brix_copy_opts::silent, brix_opts::verify_host, and XRDC_PATH_MAX.
Referenced by recursive_web_download().
recursive_web_download()
int recursive_web_download (const char * src, const char * dstdir, const brix_copy_opts * o, const brix_opts * co, int retries)
Definition at line 478 of file xrdcp_recursive.c.
References brix_copy_opts::bearer, brix_status_clear(), brix_strv_free(), brix_webdav_list(), brix_weburl_parse(), c, brix_opts::ca_dir, ensure_web_dst_base(), brix_weburl::is_s3, brix_status::msg, brix_weburl::path, brix_copy_opts::recursive, recursive_s3_download(), brix_copy_opts::silent, brix_opts::verify_host, web_download_loop(), and XRDC_PATH_MAX.
Referenced by xrdcp_dispatch_recursive_web_download().
recursive_web_upload()
int recursive_web_upload (const char * localdir, const char * dst, const brix_copy_opts * o, const brix_opts * co, int retries)
Definition at line 703 of file xrdcp_recursive.c.
References brix_copy_opts::bearer, brix_status_clear(), brix_webdav_mkcol(), brix_weburl_parse(), c, brix_opts::ca_dir, brix_copy_opts::dry_run, brix_weburl::is_s3, brix_status::msg, brix_weburl::path, brix_weburl::proto, brix_copy_opts::recursive, brix_copy_opts::silent, brix_opts::verify_host, web_scheme_str(), web_upload_walk(), and XRDC_PATH_MAX.
Referenced by xrdcp_dispatch_recursive_web_upload().
rel_is_unsafe()
int rel_is_unsafe (const char * rel)
Definition at line 443 of file xrdcp.c.
References brix_rel_is_unsafe().
Referenced by s3_download_loop(), and web_download_loop().
relay_web_to_web()
int relay_web_to_web (const char * src, const char * dst, const brix_copy_opts * o, const brix_opts * co, int retries, brix_status * st)
Definition at line 344 of file xrdcp_transfer.c.
References brix_status_set(), close(), copy_one_with_retry(), brix_copy_opts::force, brix_copy_opts::recursive, brix_copy_opts::silent, XRDC_ESOCK, XRDC_EUSAGE, and XRDC_PATH_MAX.
Referenced by copy_one_with_retry().
source_has_glob()
int source_has_glob (const char * s)
Definition at line 15 of file xrdcp_recursive.c.
References brix_has_glob(), and s.
Referenced by expand_source().
str_append()
int str_append (char *** list, size_t * n, size_t * cap, const char * s)
Definition at line 188 of file xrdcp.c.
References s.
Referenced by expand_source(), parse_and_validate_args(), read_manifest(), xrdcp_collect_sources(), and xrdcp_parse_pattern_option().
str_free()
void str_free (char ** list, size_t n)
Definition at line 205 of file xrdcp.c.
Referenced by xrdcp_lists_free().
transfer_one()
int transfer_one (const char * src, const char * dst, const brix_copy_opts * o, const brix_opts * co, int retries, int sync_mode, brix_status * st)
Definition at line 293 of file xrdcp_transfer.c.
References copy_one_with_retry(), brix_copy_opts::dry_run, path_basename(), brix_copy_opts::recursive, brix_copy_opts::remove_source, remove_source_entry(), brix_copy_opts::sync, brix_copy_opts::sync_delete, transfer_filter_check(), transfer_sync_check(), and XRDC_NAME_MAX.
Referenced by batch_copy_one(), and xrdcp_dispatch_single().
usage()
void usage (const char * prog)
Definition at line 180 of file xrdcp.c.
uses_cred_auth()
int uses_cred_auth (const char * s)
Definition at line 362 of file xrdcp.c.
References brix_is_web_url(), is_root_url(), is_s3_url(), and s.
Referenced by build_and_preflight_credentials().
web_join()
int web_join (const char * base, const char * rel, char * out, size_t outsz)
Definition at line 538 of file xrdcp_recursive.c.
Referenced by walk_handle_dir(), and walk_handle_file().
web_scheme_str()
const char * web_scheme_str (brix_web_proto pr)
Definition at line 423 of file xrdcp.c.
References XRDC_WEB_DAV, XRDC_WEB_DAVS, XRDC_WEB_HTTP, XRDC_WEB_HTTPS, XRDC_WEB_S3, and XRDC_WEB_S3S.
Referenced by place_to_web(), recursive_web_upload(), s3_download_loop(), and web_download_loop().
web_upload_walk()
void web_upload_walk (web_upload_ctx * c, const char * localdir, const char * rel)
Definition at line 660 of file xrdcp_recursive.c.
References c, walk_child_t::local, lstat(), stat(), walk_child_paths(), walk_handle_dir(), and walk_handle_file().
Referenced by recursive_web_upload(), and walk_handle_dir().
xrdcp_progress()
void xrdcp_progress (void * arg, long long done, long long total)
Definition at line 453 of file xrdcp.c.
References brix_mono_ns(), xrdcp_prog::label, xrdcp_prog::last_ns, and xrdcp_prog::start_ns.
Referenced by xrdcp_enable_progress_if_needed().