nginx-xrootd: client/apps/cksum/xrdcksum.c File Reference
xrdcksum.c File Reference
#include "brix.h"
#include "core/version.h"
#include "core/progname.h"
#include "cli/suggest.h"
#include "cli/cli_hint.h"
#include <stdio.h>
#include <string.h>
Data Structures
struct cksum_tool
Functions
int brix_xrdckverify_main (int argc, char **argv)
int brix_xrdcinfo_main (int argc, char **argv)
int brix_xrdcktree_main (int argc, char **argv)
int brix_xrdckcheck_main (int argc, char **argv)
static int dispatch (const char *name, int argc, char **argv)
int main (int argc, char **argv)
Variables
static const cksum_tool CKSUM_TOOLS []
Function Documentation
brix_xrdcinfo_main()
int brix_xrdcinfo_main (int argc, char ** argv)
Definition at line 429 of file xrdcinfo.c.
References brix_client_version(), brix_prog_base(), brix_usage_footer(), dump_record(), slurp_file(), and slurp_xattr().
Referenced by dispatch().
brix_xrdckcheck_main()
int brix_xrdckcheck_main (int argc, char ** argv)
Definition at line 829 of file xrdcktree.c.
References ckcheck_ctx::algo, ckcheck_ctx::algo_str, brix_close(), ckcheck_ctx::c, c, ckcheck_connect(), ckcheck_parse_args(), ckcheck_process_line(), ckcheck_ctx::errors, ckcheck_ctx::is_remote, is_root_url(), ckcheck_ctx::mismatches, brix_url::path, ckcheck_ctx::prog, ckcheck_ctx::root, ckcheck_ctx::root_path, TREE_HEX_MAX, XRDC_CK_ADLER32, XRDC_EXIT_USAGE, and XRDC_PATH_MAX.
Referenced by dispatch().
brix_xrdcktree_main()
int brix_xrdcktree_main (int argc, char ** argv)
Definition at line 494 of file xrdcktree.c.
References cktree_opts::algo_str, brix_cksum_algo_parse(), cktree_parse_args(), cktree_run_local(), cktree_run_remote(), is_root_url(), cktree_opts::outpath, cktree_opts::root, and XRDC_EXIT_USAGE.
Referenced by dispatch().
brix_xrdckverify_main()
int brix_xrdckverify_main (int argc, char ** argv)
Definition at line 207 of file xrdckverify.c.
References brix_cks_verify_file(), brix_status_clear(), ckv_handle_early_flags(), ckv_parse_args(), ckv_report_result(), and XRDC_CKV_AUTO.
Referenced by dispatch().
dispatch()
static int dispatch (const char * name, int argc, char ** argv) static
Definition at line 49 of file xrdcksum.c.
References cksum_tool::algo, cksum_tool::algo_name, brix_cli_cksum_main(), brix_prog_base(), brix_xrdcinfo_main(), brix_xrdckcheck_main(), brix_xrdcktree_main(), brix_xrdckverify_main(), CKSUM_TOOLS, cksum_tool::err_exit, cksum_tool::name, and name.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 78 of file xrdcksum.c.
References brix_cli_hint(), brix_client_version(), brix_prog_base(), brix_prog_strip_compat(), brix_suggest(), brix_usage_footer(), and dispatch().
Variable Documentation
CKSUM_TOOLS
const cksum_tool CKSUM_TOOLS[] static
Initial value:
= {
    { "xrdcrc32c",  "crc32c",  XRDC_CK_CRC32C,  3 },
    { "crc32c",     "crc32c",  XRDC_CK_CRC32C,  3 },
    { "xrdcrc64",   "crc64",   XRDC_CK_CRC64,   1 },
    { "crc64",      "crc64",   XRDC_CK_CRC64,   1 },
    { "xrdadler32", "adler32", XRDC_CK_ADLER32, 1 },
    { "adler32",    "adler32", XRDC_CK_ADLER32, 1 },
}
Definition at line 38 of file xrdcksum.c.
Referenced by dispatch().