nginx-xrootd: client/apps/ceph/xrdcephfs_rescue.c File Reference
xrdcephfs_rescue.c File Reference
#include "sd.h"
#include "rados/sd_ceph.h"
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
Functions
void * ngx_pcalloc (ngx_pool_t *pool, size_t size)
void * ngx_pnalloc (ngx_pool_t *pool, size_t size)
static int copy_to_stream (brix_sd_obj_t *o, FILE *out)
static int do_cat_or_get (const char *path, const char *local)
static int do_ls (const char *path)
static int do_stat (const char *path)
static int copy_tree (const char *src, const char *dst)
int main (int argc, char **argv)
Variables
static const brix_sd_driver_t * DRV
static brix_sd_instance_t INST
Function Documentation
copy_to_stream()
static int copy_to_stream (brix_sd_obj_t * o, FILE * out) static
Definition at line 48 of file xrdcephfs_rescue.c.
References DRV.
Referenced by do_cat_or_get().
copy_tree()
static int copy_tree (const char * src, const char * dst) static
Definition at line 120 of file xrdcephfs_rescue.c.
References copy_tree(), do_cat_or_get(), DRV, fails, INST, brix_sd_stat_t::is_dir, brix_sd_stat_t::is_reg, brix_sd_dirent_t::name, and brix_sd_stat_t::size.
Referenced by copy_tree(), and main().
do_cat_or_get()
static int do_cat_or_get (const char * path, const char * local) static
Definition at line 62 of file xrdcephfs_rescue.c.
References BRIX_SD_O_READ, copy_to_stream(), DRV, and INST.
Referenced by copy_tree(), and main().
do_ls()
static int do_ls (const char * path) static
Definition at line 83 of file xrdcephfs_rescue.c.
References DRV, INST, and brix_sd_dirent_t::name.
Referenced by main().
do_stat()
static int do_stat (const char * path) static
Definition at line 99 of file xrdcephfs_rescue.c.
References DRV, brix_sd_stat_t::ino, INST, brix_sd_stat_t::is_dir, brix_sd_stat_t::is_reg, brix_sd_stat_t::mode, brix_sd_stat_t::mtime, and brix_sd_stat_t::size.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 158 of file xrdcephfs_rescue.c.
References copy_tree(), do_cat_or_get(), do_ls(), do_stat(), DRV, and INST.
ngx_pcalloc()
void * ngx_pcalloc (ngx_pool_t * pool, size_t size)
Definition at line 40 of file xrdcephfs_rescue.c.
ngx_pnalloc()
void * ngx_pnalloc (ngx_pool_t * pool, size_t size)
Definition at line 41 of file xrdcephfs_rescue.c.
Variable Documentation
DRV
const brix_sd_driver_t* DRV static
Definition at line 43 of file xrdcephfs_rescue.c.
Referenced by copy_to_stream(), copy_tree(), do_cat_or_get(), do_ls(), do_stat(), and main().
INST
brix_sd_instance_t INST static
Definition at line 44 of file xrdcephfs_rescue.c.
Referenced by copy_tree(), do_cat_or_get(), do_ls(), do_stat(), and main().