nginx-xrootd: client/apps/ceph/xrdceph_migrate.c File Reference
xrdceph_migrate.c File Reference
#include "sd.h"
#include "rados/sd_ceph.h"
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/xattr.h>
#include <unistd.h>
#include <rados/librados.h>
Functions
void * ngx_pcalloc (ngx_pool_t *pool, size_t size)
void * ngx_pnalloc (ngx_pool_t *pool, size_t size)
static int mkdirs_for (const char *path)
static void carry_xattrs (sd_ceph_conn_t *c, const char *oid, int fd)
static int stream_object (sd_ceph_conn_t *c, const char *oid, int fd)
int main (int argc, char **argv)
Function Documentation
carry_xattrs()
static void carry_xattrs (sd_ceph_conn_t * c, const char * oid, int fd) static
Definition at line 66 of file xrdceph_migrate.c.
References c, and name.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 109 of file xrdceph_migrate.c.
References c, carry_xattrs(), fails, mkdirs_for(), stat(), and stream_object().
mkdirs_for()
static int mkdirs_for (const char * path) static
Definition at line 47 of file xrdceph_migrate.c.
References s.
Referenced by main().
ngx_pcalloc()
void * ngx_pcalloc (ngx_pool_t * pool, size_t size)
Definition at line 42 of file xrdceph_migrate.c.
ngx_pnalloc()
void * ngx_pnalloc (ngx_pool_t * pool, size_t size)
Definition at line 43 of file xrdceph_migrate.c.
stream_object()
static int stream_object (sd_ceph_conn_t * c, const char * oid, int fd) static
Definition at line 89 of file xrdceph_migrate.c.
References c.
Referenced by main().