nginx-xrootd: client/apps/diag/xrddiag.c File Reference
xrddiag.c File Reference
#include "diag_internal.h"
#include "cli/jsonout.h"
#include "core/version.h"
#include "core/progname.h"
#include "cli/suggest.h"
#include "cli/cli_hint.h"
#include <stddef.h>
Data Structures
struct dx_scheme_t
struct dx_opt_t
struct dx_pos_t
struct dx_cmd_t
Enumerations
enum dx_opt_kind { DXO_FLAG , DXO_CLEAR , DXO_INT , DXO_STR }
Functions
void note (const char *name, const char *fmt,...)
void dx_record (doctor_ep *e, const dx_note *n)
void dx_record_status (doctor_ep *e, const char *probe, const brix_status *st)
int dx_is_loopback (const char *host)
int dx_b64url_enc (const unsigned char *in, size_t n, char *out, size_t outsz)
int dx_make_jwt (const char *header, const char *payload, const char *sig, char *out, size_t outsz)
int dx_connect_as (const diag_args *a, const brix_url *u, const dx_cred_sel *sel, brix_conn *c, brix_status *st)
const char * dx_proto_name (dx_proto p)
static int dx_scheme_match (const char **p, dx_proto *proto, int *tls, int *port)
static int dx_host6_parse (const char **p, char *host, size_t hsz, int *port)
static int dx_hostname_parse (const char **p, char *host, size_t hsz, int *port)
int dx_url_parse (const char *url, dx_url_t *u)
void dx_http_status (doctor_ep *e, const char *probe, int status)
void dx_http_fail (doctor_ep *e, int tls, const brix_status *st)
int s3_sign (const s3_sign_req *q, char *hdrs, size_t hdrsz)
void fjson_str (FILE *out, const char *s)
const char * dx_verdict_name (int v)
int js_str (const char *json, const char *key, char *out, size_t osz)
long long js_sum (const char *json, const char *key)
int js_count (const char *json, const char *key)
static void usage_fp (FILE *out, const char *prog)
void usage (const char *prog)
static int dx_opt_apply (diag_args *a, const dx_opt_t *o, int argc, char **argv, int *i)
static int dx_opt_parse (diag_args *a, int argc, char **argv, int *i)
static int dx_parse_argv (diag_args *a, int argc, char **argv, dx_pos_t *pos, int *rc)
static int dx_personality_route (int argc, char **argv, int *rc)
static int dx_unknown_sub (const char *sub, const char *prog)
static int dx_dispatch (const char *sub, const diag_args *a, const char *prog)
int main (int argc, char **argv)
Variables
int g_fails
const dx_rule DX_RULES []
volatile sig_atomic_t g_watch_stop
static const dx_scheme_t DX_SCHEMES []
static const dx_opt_t DX_OPTS []
static const dx_cmd_t DX_CMDS []
Enumeration Type Documentation
dx_opt_kind
enum dx_opt_kind
Enumerator
DXO_FLAG
DXO_CLEAR
DXO_INT
DXO_STR
Definition at line 655 of file xrddiag.c.
Function Documentation
dx_b64url_enc()
int dx_b64url_enc (const unsigned char * in, size_t n, char * out, size_t outsz)
Definition at line 187 of file xrddiag.c.
Referenced by dx_make_jwt().
dx_connect_as()
int dx_connect_as (const diag_args * a, const brix_url * u, const dx_cred_sel * sel, brix_conn * c, brix_status * st)
Definition at line 238 of file xrddiag.c.
References dx_cred_sel::auth_force, brix_opts::auth_force, brix_connect(), brix_status_clear(), c, diag_args::conn, dx_cred_sel::force_anon, brix_opts::force_anon, and dx_cred_sel::token_override.
Referenced by dx_authz_anon(), dx_authz_expired(), dx_authz_forged(), and dx_authz_scope().
dx_dispatch()
static int dx_dispatch (const char * sub, const diag_args * a, const char * prog) static
Definition at line 903 of file xrddiag.c.
References DX_CMDS, dx_unknown_sub(), dx_cmd_t::fn, and name.
Referenced by main().
dx_host6_parse()
static int dx_host6_parse (const char ** p, char * host, size_t hsz, int * port) static
Definition at line 346 of file xrddiag.c.
References host, and port.
Referenced by dx_url_parse().
dx_hostname_parse()
static int dx_hostname_parse (const char ** p, char * host, size_t hsz, int * port) static
Definition at line 376 of file xrddiag.c.
References host, and port.
Referenced by dx_url_parse().
dx_http_fail()
void dx_http_fail (doctor_ep * e, int tls, const brix_status * st)
Definition at line 461 of file xrddiag.c.
References doc_issue(), DOC_RED, DX_FAIL, dx_record(), brix_status::kxr, brix_status::sys_errno, tls, and XRDC_EAUTH.
Referenced by doctor_http(), and doctor_s3().
dx_http_status()
void dx_http_status (doctor_ep * e, const char * probe, int status)
Definition at line 433 of file xrddiag.c.
References DX_FAIL, DX_OK, dx_record(), DX_WARN, and probe().
Referenced by doctor_http(), s3_classify_anon(), and s3_classify_signed().
dx_is_loopback()
int dx_is_loopback (const char * host)
Definition at line 171 of file xrddiag.c.
References host.
Referenced by auth_suite_token_probes(), and doctor_diagnose().
dx_make_jwt()
int dx_make_jwt (const char * header, const char * payload, const char * sig, char * out, size_t outsz)
Definition at line 215 of file xrddiag.c.
References dx_b64url_enc().
Referenced by auth_suite_forged_probes().
dx_opt_apply()
static int dx_opt_apply (diag_args * a, const dx_opt_t * o, int argc, char ** argv, int * i) static
Definition at line 701 of file xrddiag.c.
References DXO_CLEAR, DXO_FLAG, DXO_INT, dx_opt_t::kind, and dx_opt_t::off.
Referenced by dx_opt_parse().
dx_opt_parse()
static int dx_opt_parse (diag_args * a, int argc, char ** argv, int * i) static
Definition at line 734 of file xrddiag.c.
References dx_opt_apply(), DX_OPTS, name, diag_args::prom_path, and diag_args::watch_prom.
Referenced by dx_parse_argv().
dx_parse_argv()
static int dx_parse_argv (diag_args * a, int argc, char ** argv, dx_pos_t * pos, int * rc) static
Definition at line 774 of file xrddiag.c.
References brix_opts_parse_arg(), diag_args::conn, dx_opt_parse(), dx_pos_t::n, usage(), usage_fp(), and dx_pos_t::v.
Referenced by main().
dx_personality_route()
static int dx_personality_route (int argc, char ** argv, int * rc) static
Definition at line 822 of file xrddiag.c.
References brix_mpxstats_main(), brix_prog_base(), brix_prog_strip_compat(), brix_qstats_main(), and brix_wait41_main().
Referenced by main().
dx_proto_name()
const char * dx_proto_name (dx_proto p)
Definition at line 270 of file xrddiag.c.
References DXP_CMS, DXP_DAVS, DXP_HTTP, DXP_HTTPS, and DXP_S3.
Referenced by doctor_emit_json(), and remote_doctor_report_ep().
dx_record()
void dx_record (doctor_ep * e, const dx_note * n)
Definition at line 112 of file xrddiag.c.
References dx_finding::cause, dx_note::cause, DOC_MAXDX, doctor_ep::dx, dx_finding::kxr, dx_note::kxr, doctor_ep::ndx, dx_finding::probe, dx_note::probe, dx_finding::remedy, dx_note::remedy, doctor_ep::status, dx_finding::verdict, and dx_note::verdict.
Referenced by doctor_auth_suite(), doctor_cms(), doctor_diagnose(), doctor_one_connect_fail(), doctor_s3(), dx_authz_anon(), dx_authz_expired(), dx_authz_forged(), dx_authz_scope(), dx_http_fail(), dx_http_status(), dx_probe_auth(), dx_probe_checksum(), dx_probe_namespace(), dx_probe_read(), dx_probe_stage(), dx_probe_write(), dx_record_status(), http_check_common_headers(), http_davs_extras(), http_record_tls(), s3_classify_anon(), s3_classify_signed(), and s3_sigv4_probe().
dx_record_status()
void dx_record_status (doctor_ep * e, const char * probe, const brix_status * st)
Definition at line 136 of file xrddiag.c.
References brix_kxr_name(), dx_rule::cause, DX_ANY, DX_FAIL, dx_record(), DX_RULES, dx_rule::kxr, brix_status::kxr, probe(), dx_rule::probe, dx_rule::remedy, and dx_rule::sev.
Referenced by doctor_cms(), doctor_diagnose(), dx_probe_checksum(), dx_probe_namespace(), dx_probe_read(), dx_probe_stage(), and dx_probe_write().
dx_scheme_match()
static int dx_scheme_match (const char ** p, dx_proto * proto, int * tls, int * port) static
Definition at line 320 of file xrddiag.c.
References DX_SCHEMES, port, s, and tls.
Referenced by dx_url_parse().
dx_unknown_sub()
static int dx_unknown_sub (const char * sub, const char * prog) static
Definition at line 878 of file xrddiag.c.
References brix_cli_hint(), brix_suggest(), and usage().
Referenced by dx_dispatch().
dx_url_parse()
int dx_url_parse (const char * url, dx_url_t * u)
Definition at line 408 of file xrddiag.c.
References dx_host6_parse(), dx_hostname_parse(), dx_scheme_match(), dx_url_t::host, dx_url_t::path, dx_url_t::port, dx_url_t::proto, and dx_url_t::tls.
Referenced by do_srr(), do_tape(), and doctor_dispatch().
dx_verdict_name()
const char * dx_verdict_name (int v)
Definition at line 503 of file xrddiag.c.
References DX_FAIL, and DX_WARN.
Referenced by doctor_emit_json().
fjson_str()
void fjson_str (FILE * out, const char * s)
Definition at line 496 of file xrddiag.c.
References brix_json_fputs(), and s.
Referenced by doctor_emit_json(), and watch_emit_json().
js_count()
int js_count (const char * json, const char * key)
Definition at line 581 of file xrddiag.c.
References key.
Referenced by do_srr().
js_str()
int js_str (const char * json, const char * key, char * out, size_t osz)
Definition at line 514 of file xrddiag.c.
References key.
Referenced by do_srr(), do_tape(), and tape_poll_status().
js_sum()
long long js_sum (const char * json, const char * key)
Definition at line 553 of file xrddiag.c.
References c, and key.
Referenced by do_srr().
main()
int main (int argc, char ** argv)
Definition at line 917 of file xrddiag.c.
References brix_client_version(), brix_crypto_init(), brix_prog_base(), diag_args::conn, dx_dispatch(), dx_parse_argv(), dx_personality_route(), diag_args::metrics_port, dx_pos_t::n, diag_args::nurls, diag_args::ref_url, diag_args::url, diag_args::urls, usage(), usage_fp(), dx_pos_t::v, brix_opts::verify_host, and diag_args::verify_tls.
note()
void note (const char * name, const char * fmt, ...)
Definition at line 82 of file xrddiag.c.
References name.
Referenced by chk_probe_checksum(), chk_probe_cred_validity(), chk_probe_handle_limits(), chk_probe_posc(), chk_probe_tls(), do_check(), do_compare_davs(), and topo_report_cluster().
s3_sign()
int s3_sign (const s3_sign_req * q, char * hdrs, size_t hdrsz)
Definition at line 486 of file xrddiag.c.
References s3_sign_req::ak, brix_s3_sign_v4(), s3_sign_req::host, s3_sign_req::method, s3_sign_req::region, s3_sign_req::sk, and s3_sign_req::uri.
Referenced by s3_sigv4_probe().
usage()
void usage (const char * prog)
Definition at line 640 of file xrddiag.c.
References usage_fp().
usage_fp()
static void usage_fp (FILE * out, const char * prog) static
Definition at line 599 of file xrddiag.c.
References brix_prog_base(), and brix_usage_footer().
Referenced by dx_parse_argv(), main(), and usage().
Variable Documentation
DX_CMDS
const dx_cmd_t DX_CMDS[] static
Initial value:
= {
    { "remote-doctor",    do_remote_doctor },
    { "watch",            do_watch },
    { "check",            do_check },
    { "bench",            do_bench },
    { "metabench",        do_metabench },
    { "topology",         do_topology },
    { "status",           do_status },
    { "compare",          do_compare },
    { "probe-robustness", do_probe_robustness },
    { "replay",           do_replay },
    { "srr",              do_srr },
    { "tape",             do_tape },
}
Definition at line 854 of file xrddiag.c.
Referenced by dx_dispatch().
DX_OPTS
const dx_opt_t DX_OPTS[] static
Initial value:
= {
    { "-S",                DXO_INT,   offsetof(diag_args, streams) },
    { "--streams",         DXO_INT,   offsetof(diag_args, streams) },
    { "--vs-reference",    DXO_STR,   offsetof(diag_args, ref_url) },
    { "--metrics-port",    DXO_INT,   offsetof(diag_args, metrics_port) },
    { "--cluster-url",     DXO_STR,   offsetof(diag_args, cluster_url) },
    { "--i-am-authorized", DXO_FLAG,  offsetof(diag_args, authorized) },
    { "--i-am-authorised", DXO_FLAG,  offsetof(diag_args, authorized) },
    { "--probe-timeout",   DXO_INT,   offsetof(diag_args, probe_timeout_ms) },
    { "--playback",        DXO_STR,   offsetof(diag_args, playback_url) },
    { "--davs",            DXO_STR,   offsetof(diag_args, davs) },
    { "--sweep",           DXO_FLAG,  offsetof(diag_args, sweep) },
    { "--json",            DXO_FLAG,  offsetof(diag_args, json) },
    { "--allow-write",     DXO_FLAG,  offsetof(diag_args, allow_write) },
    { "--auth-suite",      DXO_FLAG,  offsetof(diag_args, auth_suite) },
    { "--no-verify-tls",   DXO_CLEAR, offsetof(diag_args, verify_tls) },
    { "--dashboard-port",  DXO_INT,   offsetof(diag_args, dashboard_port) },
    { "--interval",        DXO_INT,   offsetof(diag_args, interval_s) },
    { "--count",           DXO_INT,   offsetof(diag_args, count) },
    { "--prometheus",      DXO_FLAG,  offsetof(diag_args, watch_prom) },
}
Definition at line 668 of file xrddiag.c.
Referenced by dx_opt_parse().
DX_RULES
const dx_rule DX_RULES[]
Definition at line 15 of file xrddiag.c.
Referenced by dx_record_status().
DX_SCHEMES
const dx_scheme_t DX_SCHEMES[] static
Initial value:
= {
    { "roots://",  8, DXP_ROOT,  1, 1094 },
    { "xroots://", 9, DXP_ROOT,  1, 1094 },
    { "root://",   7, DXP_ROOT,  0, 1094 },
    { "xroot://",  8, DXP_ROOT,  0, 1094 },
    { "https://",  8, DXP_HTTPS, 1, 8443 },
    { "http://",   7, DXP_HTTP,  0, 8080 },
    { "davs://",   7, DXP_DAVS,  1, 8443 },
    { "dav://",    6, DXP_DAVS,  0, 8080 },
    { "s3s://",    6, DXP_S3,    1,  443 },
    { "s3://",     5, DXP_S3,    0, 9000 },
    { "cms://",    6, DXP_CMS,   0, 1213 },
}
Definition at line 298 of file xrddiag.c.
Referenced by dx_scheme_match().
g_fails
int g_fails
Definition at line 13 of file xrddiag.c.
Referenced by do_check(), do_compare(), do_compare_davs(), do_probe_robustness(), do_topology(), and probe().
g_watch_stop
volatile sig_atomic_t g_watch_stop
Definition at line 77 of file xrddiag.c.
Referenced by do_watch(), watch_on_signal(), and watch_sleep().