nginx-xrootd: client/apps/fs/xrdfs.c File Reference
xrdfs.c File Reference
#include "xrdfs_internal.h"
#include "core/version.h"
#include "cli/suggest.h"
#include "cli/cli_hint.h"
Data Structures
struct xrdfs_optscan
Functions
int wait_online (brix_conn *c, const char *path, int timeout_s, brix_status *st)
int do_explain (brix_conn *c, const char *cwd, int argc, char **argv)
static void dispatch_unknown (const char *name)
static int dispatch_builtin (char *cwd, size_t cwdsz, int ntok, char **tok, int *quit)
int dispatch (brix_conn *c, char *cwd, size_t cwdsz, int ntok, char **tok, int *quit)
int tokenize (char *line, char **tok, int maxtok)
int repl (brix_conn *c, const char *host, int port)
static void usage_fp (FILE *out)
void usage (void)
static int opt_early_exit (const char *a)
static int opt_apply_valueflag (int argc, char **argv, brix_opts *opts, xrdfs_optscan *sc)
static int opt_apply_flag (int argc, char **argv, brix_opts *opts, xrdfs_optscan *sc)
static void parse_global_opts (int argc, char **argv, brix_opts *opts, xrdfs_optscan *sc)
static int run_web_endpoint (const char *endpoint, const brix_opts *opts, const char *web_token, int nargs, char **args)
static int run_root_endpoint (const char *endpoint, brix_opts *opts, int nargs, char **args)
int main (int argc, char **argv)
Variables
volatile sig_atomic_t tail_stop = 0
const xrdfs_cmd COMMANDS []
Function Documentation
dispatch()
int dispatch (brix_conn * c, char * cwd, size_t cwdsz, int ntok, char ** tok, int * quit)
Definition at line 156 of file xrdfs.c.
References BRIX_USAGE_FOOTER, c, dispatch_builtin(), dispatch_unknown(), and find_command().
Referenced by repl(), and run_root_endpoint().
dispatch_builtin()
static int dispatch_builtin (char * cwd, size_t cwdsz, int ntok, char ** tok, int * quit) static
Definition at line 126 of file xrdfs.c.
References build_path(), COMMANDS, xrdfs_cmd::name, and XRDC_PATH_MAX.
Referenced by dispatch().
dispatch_unknown()
static void dispatch_unknown (const char * name) static
Definition at line 95 of file xrdfs.c.
References brix_cli_hint(), brix_suggest(), COMMANDS, xrdfs_cmd::name, and name.
Referenced by dispatch().
do_explain()
int do_explain (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 78 of file xrdfs.c.
References brix_explain_conn(), and c.
main()
int main (int argc, char ** argv)
Definition at line 474 of file xrdfs.c.
References xrdfs_optscan::argi, brix_crypto_init(), brix_is_web_url(), xrdfs_optscan::done, xrdfs_optscan::exit_code, parse_global_opts(), run_root_endpoint(), run_web_endpoint(), usage(), brix_opts::verify_host, and xrdfs_optscan::web_token.
opt_apply_flag()
static int opt_apply_flag (int argc, char ** argv, brix_opts * opts, xrdfs_optscan * sc) static
Definition at line 343 of file xrdfs.c.
References xrdfs_optscan::argi, brix_opts::notlsok, opt_apply_valueflag(), brix_opts::redir_trace, brix_opts::timing, brix_opts::verify_host, brix_opts::want_tls, and brix_opts::wire_trace.
Referenced by parse_global_opts().
opt_apply_valueflag()
static int opt_apply_valueflag (int argc, char ** argv, brix_opts * opts, xrdfs_optscan * sc) static
Definition at line 316 of file xrdfs.c.
References xrdfs_optscan::argi, brix_opts::auth_force, brix_opts::capture, and xrdfs_optscan::web_token.
Referenced by opt_apply_flag().
opt_early_exit()
static int opt_early_exit (const char * a) static
Definition at line 289 of file xrdfs.c.
References brix_client_version(), usage(), and usage_fp().
Referenced by parse_global_opts().
parse_global_opts()
static void parse_global_opts (int argc, char ** argv, brix_opts * opts, xrdfs_optscan * sc) static
Definition at line 368 of file xrdfs.c.
References xrdfs_optscan::argi, xrdfs_optscan::done, xrdfs_optscan::exit_code, opt_apply_flag(), opt_early_exit(), and xrdfs_optscan::web_token.
Referenced by main().
repl()
int repl (brix_conn * c, const char * host, int port)
Definition at line 202 of file xrdfs.c.
References c, dispatch(), tokenize(), XRDC_PATH_MAX, and XRDFS_MAXTOK.
Referenced by run_root_endpoint().
run_root_endpoint()
static int run_root_endpoint (const char * endpoint, brix_opts * opts, int nargs, char ** args) static
Definition at line 444 of file xrdfs.c.
References brix_close(), brix_connect_resilient(), brix_shellcode(), brix_status_clear(), c, dispatch(), endpoint_to_url(), brix_url::host, brix_status::msg, brix_url::port, repl(), and XRDC_PATH_MAX.
Referenced by main().
run_web_endpoint()
static int run_web_endpoint (const char * endpoint, const brix_opts * opts, const char * web_token, int nargs, char ** args) static
Definition at line 399 of file xrdfs.c.
References web_ctx::base, web_ctx::bearer, brix_resolve_ca_dir(), brix_weburl_parse(), web_ctx::ca_dir, brix_weburl::is_s3, brix_weburl::path, web_ctx::u, web_ctx::verify, brix_opts::verify_host, web_dispatch(), and XRDC_PATH_MAX.
Referenced by main().
tokenize()
int tokenize (char * line, char ** tok, int maxtok)
Definition at line 185 of file xrdfs.c.
Referenced by repl().
usage()
void usage (void)
Definition at line 261 of file xrdfs.c.
References usage_fp().
Referenced by main(), and opt_early_exit().
usage_fp()
static void usage_fp (FILE * out) static
Definition at line 240 of file xrdfs.c.
References BRIX_USAGE_FOOTER.
Referenced by opt_early_exit(), and usage().
wait_online()
int wait_online (brix_conn * c, const char * path, int timeout_s, brix_status * st)
Definition at line 57 of file xrdfs.c.
References brix_stat(), brix_status_clear(), c, brix_statinfo::flags, and kXR_offline.
Referenced by do_stage().
Variable Documentation
COMMANDS
const xrdfs_cmd COMMANDS[]
Definition at line 12 of file xrdfs.c.
Referenced by dispatch_builtin(), dispatch_unknown(), and find_command().
tail_stop
volatile sig_atomic_t tail_stop = 0
Definition at line 10 of file xrdfs.c.
Referenced by tail_follow(), and tail_sigint().