nginx-xrootd: client/apps/fs/xrdfs_web.c File Reference
xrdfs_web.c File Reference
#include "xrdfs_internal.h"
Functions
void web_build_path (const char *base, const char *cwd, const char *arg, char *out, size_t outsz)
static void web_print_one_entry (const brix_dirent *ent, const char *prefix, int want_long, int human)
static int web_ls_recurse_children (const web_ctx *w, const char *path, const brix_dirent *ents, size_t n, int want_long, int human, brix_status *st)
int web_ls_print_dir (const web_ctx *w, const char *path, int want_long, int recursive, int human, brix_status *st)
int web_ls (const web_ctx *w, const char *cwd, int argc, char **argv)
int web_stat (const web_ctx *w, const char *cwd, int argc, char **argv)
int web_dispatch (const web_ctx *w, int argc, char **argv)
Function Documentation
web_build_path()
void web_build_path (const char * base, const char * cwd, const char * arg, char * out, size_t outsz)
Definition at line 20 of file xrdfs_web.c.
References build_path(), and XRDC_PATH_MAX.
Referenced by web_ls(), and web_stat().
web_dispatch()
int web_dispatch (const web_ctx * w, int argc, char ** argv)
Definition at line 192 of file xrdfs_web.c.
References web_ls(), and web_stat().
Referenced by run_web_endpoint().
web_ls()
int web_ls (const web_ctx * w, const char * cwd, int argc, char ** argv)
Definition at line 144 of file xrdfs_web.c.
References web_ctx::base, brix_shellcode(), brix_status_clear(), brix_status::msg, web_build_path(), web_ls_print_dir(), XRDC_PATH_MAX, and xrdfs_web_hints().
Referenced by web_dispatch().
web_ls_print_dir()
int web_ls_print_dir (const web_ctx * w, const char * path, int want_long, int recursive, int human, brix_status * st)
Definition at line 114 of file xrdfs_web.c.
References web_ctx::bearer, brix_web_readdir(), web_ctx::ca_dir, web_ctx::u, web_ctx::verify, web_ls_recurse_children(), web_print_one_entry(), and XRDC_PATH_MAX.
Referenced by web_ls(), and web_ls_recurse_children().
web_ls_recurse_children()
static int web_ls_recurse_children (const web_ctx * w, const char * path, const brix_dirent * ents, size_t n, int want_long, int human, brix_status * st) static
Definition at line 88 of file xrdfs_web.c.
References is_dot(), join_path(), kXR_isDir, name, web_ls_print_dir(), and XRDC_PATH_MAX.
Referenced by web_ls_print_dir().
web_print_one_entry()
static void web_print_one_entry (const brix_dirent * ent, const char * prefix, int want_long, int human) static
Definition at line 52 of file xrdfs_web.c.
References brix_statinfo::flags, fmt_size(), brix_dirent::have_stat, kXR_isDir, kXR_readable, kXR_writable, brix_dirent::name, brix_statinfo::size, and brix_dirent::st.
Referenced by web_ls_print_dir().
web_stat()
int web_stat (const web_ctx * w, const char * cwd, int argc, char ** argv)
Definition at line 171 of file xrdfs_web.c.
References web_ctx::base, web_ctx::bearer, brix_shellcode(), brix_status_clear(), brix_web_stat(), web_ctx::ca_dir, brix_status::msg, print_statinfo(), web_ctx::u, web_ctx::verify, web_build_path(), XRDC_PATH_MAX, and xrdfs_web_hints().
Referenced by web_dispatch().