nginx-xrootd: client/apps/fs/xrdfs_internal.h File Reference
xrdfs_internal.h File Reference
#include "brix.h"
#include "cli/jsonout.h"
#include "cli/cli_hint.h"
#include "core/compat/crypto.h"
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <fnmatch.h>
#include <regex.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct web_ctx
struct chmod_walk
struct du_acc
struct find_pred
struct tree_opts
struct xrdfs_cmd
Macros
#define XRDFS_MAXTOK 64
#define XRDFS_DD_MAXBS (256LL << 20) /* cap a single block buffer at 256 MiB */
#define XRDFS_MAXDEPTH 64 /* recursion bound (defensive; trees aren't cyclic) */
Typedefs
typedef int(* xrdfs_visit) (const char *full, const brix_dirent *e, int depth, void *u)
typedef int(* xrdfs_fn) (brix_conn *, const char *, int, char **)
Functions
static void xrdfs_op_hints (const brix_status *st, int want_write, const brix_conn *c)
static void xrdfs_web_hints (const brix_status *st, int want_write, const web_ctx *w)
int endpoint_to_url (const char *ep, brix_url *u, brix_status *st)
void build_path (const char *cwd, const char *arg, char *out, size_t outsz)
void flags_to_str (int f, char *out, size_t sz)
void print_stat_time (const char *label, long epoch)
void print_statinfo (const char *path, const brix_statinfo *si)
void json_statinfo (const char *path, const brix_statinfo *si)
int do_stat (brix_conn *c, const char *cwd, int argc, char **argv)
int ls_print_dir (brix_conn *c, const char *path, int want_long, int recursive, int human, brix_status *st)
int do_ls (brix_conn *c, const char *cwd, int argc, char **argv)
void web_build_path (const char *base, const char *cwd, const char *arg, char *out, size_t outsz)
int web_ls_print_dir (const web_ctx *w, const char *path, int want_long, int recursive, int human, brix_status *st)
int web_ls (const web_ctx *w, const char *cwd, int argc, char **argv)
int web_stat (const web_ctx *w, const char *cwd, int argc, char **argv)
int web_dispatch (const web_ctx *w, int argc, char **argv)
int do_mkdir (brix_conn *c, const char *cwd, int argc, char **argv)
int do_rm (brix_conn *c, const char *cwd, int argc, char **argv)
int do_rmdir (brix_conn *c, const char *cwd, int argc, char **argv)
int do_mv (brix_conn *c, const char *cwd, int argc, char **argv)
int parse_chmod_mode (const char *s)
int do_chmod (brix_conn *c, const char *cwd, int argc, char **argv)
int do_truncate (brix_conn *c, const char *cwd, int argc, char **argv)
int stream_file (brix_conn *c, const char *path, const char *opaque, int64_t start, int64_t limit, brix_status *st)
int do_cat (brix_conn *c, const char *cwd, int argc, char **argv)
int head_lines (brix_conn *c, const char *path, long nlines, brix_status *st)
int do_head (brix_conn *c, const char *cwd, int argc, char **argv)
void tail_sigint (int sig)
int tail_start_for_lines (brix_conn *c, const char *path, int64_t size, long nlines, int64_t *start, brix_status *st)
int tail_follow (brix_conn *c, const char *path, int64_t from, double interval, brix_status *st)
int do_tail (brix_conn *c, const char *cwd, int argc, char **argv)
int do_locate (brix_conn *c, const char *cwd, int argc, char **argv)
int do_statvfs (brix_conn *c, const char *cwd, int argc, char **argv)
int64_t df_field (const char *reply, const char *key)
int df_parse_space (const char *reply, int64_t *total, int64_t *avail, int64_t *used, int64_t *largest)
int do_df (brix_conn *c, const char *cwd, int argc, char **argv)
int two_digits (const char *p)
int touch_parse_time (const char *s, struct timespec *out)
int do_touch (brix_conn *c, const char *cwd, int argc, char **argv)
int do_ln (brix_conn *c, const char *cwd, int argc, char **argv)
int do_readlink (brix_conn *c, const char *cwd, int argc, char **argv)
int do_cksum (brix_conn *c, const char *cwd, int argc, char **argv)
int do_wc (brix_conn *c, const char *cwd, int argc, char **argv)
int slurp_file (brix_conn *c, const char *path, uint8_t **out, int64_t *len, brix_status *st)
int do_cmp (brix_conn *c, const char *cwd, int argc, char **argv)
int xattr_ls (brix_conn *c, const char *path)
int do_xattr (brix_conn *c, const char *cwd, int argc, char **argv)
int do_grep (brix_conn *c, const char *cwd, int argc, char **argv)
int do_hexdump (brix_conn *c, const char *cwd, int argc, char **argv)
int64_t parse_bytes (const char *s)
void rate_pace (const struct timespec *start, int64_t sent, double rate)
int do_dd (brix_conn *c, const char *cwd, int argc, char **argv)
int do_upload (brix_conn *c, const char *cwd, int argc, char **argv)
int do_download (brix_conn *c, const char *cwd, int argc, char **argv)
int do_query (brix_conn *c, const char *cwd, int argc, char **argv)
int do_prepare (brix_conn *c, const char *cwd, int argc, char **argv)
int wait_online (brix_conn *c, const char *path, int timeout_s, brix_status *st)
int do_stage (brix_conn *c, const char *cwd, int argc, char **argv)
int do_evict (brix_conn *c, const char *cwd, int argc, char **argv)
int do_explain (brix_conn *c, const char *cwd, int argc, char **argv)
int parse_u64_strict (const char *s, unsigned long long *out)
int do_readv (brix_conn *c, const char *cwd, int argc, char **argv)
int do_writev (brix_conn *c, const char *cwd, int argc, char **argv)
int is_dot (const char *name)
void fmt_size (int64_t n, char *out, size_t sz, int human)
int join_path (const char *dir, const char *name, char *out, size_t sz)
int walk_dir (brix_conn *c, const char *path, int depth, xrdfs_visit visit, void *u, brix_status *st)
int chmod_visit (const char *full, const brix_dirent *e, int depth, void *u)
int chmod_recursive (brix_conn *c, const char *path, int mode, int *failures, brix_status *st)
int du_visit (const char *full, const brix_dirent *e, int depth, void *u)
int do_du (brix_conn *c, const char *cwd, int argc, char **argv)
int find_visit (const char *full, const brix_dirent *e, int depth, void *u)
int do_find (brix_conn *c, const char *cwd, int argc, char **argv)
int tree_recurse (brix_conn *c, const char *path, const char *prefix, int depth, tree_opts *o, brix_status *st)
int do_tree (brix_conn *c, const char *cwd, int argc, char **argv)
const xrdfs_cmd * find_command (const char *name)
int dispatch (brix_conn *c, char *cwd, size_t cwdsz, int ntok, char **tok, int *quit, const char *prog)
int tokenize (char *line, char **tok, int maxtok)
int repl (brix_conn *c, const char *host, int port, const char *prog)
void usage (const char *prog)
Variables
volatile sig_atomic_t tail_stop
const xrdfs_cmd COMMANDS []
Macro Definition Documentation
XRDFS_DD_MAXBS
#define XRDFS_DD_MAXBS (256LL << 20) /* cap a single block buffer at 256 MiB */
Definition at line 82 of file xrdfs_internal.h.
XRDFS_MAXDEPTH
#define XRDFS_MAXDEPTH 64 /* recursion bound (defensive; trees aren't cyclic) */
Definition at line 83 of file xrdfs_internal.h.
XRDFS_MAXTOK
#define XRDFS_MAXTOK 64
Definition at line 24 of file xrdfs_internal.h.
Typedef Documentation
xrdfs_fn
typedef int(* xrdfs_fn) (brix_conn *, const char *, int, char **)
Definition at line 112 of file xrdfs_internal.h.
xrdfs_visit
typedef int(* xrdfs_visit) (const char *full, const brix_dirent *e, int depth, void *u)
Definition at line 84 of file xrdfs_internal.h.
Function Documentation
build_path()
void build_path (const char * cwd, const char * arg, char * out, size_t outsz)
Definition at line 19 of file xrdfs_fmt.c.
References brix_path_resolve().
Referenced by dispatch_builtin(), do_cat(), do_chmod(), do_cksum(), do_cmp(), do_dd(), do_df(), do_download(), do_du(), do_evict(), do_find(), do_grep(), do_head(), do_hexdump(), do_ln(), do_locate(), do_ls(), do_mkdir(), do_mv(), do_prepare(), do_query(), do_readlink(), do_readv(), do_rm(), do_rmdir(), do_stage(), do_stat(), do_statvfs(), do_tail(), do_touch(), do_tree(), do_truncate(), do_upload(), do_wc(), do_writev(), do_xattr(), and web_build_path().
chmod_recursive()
int chmod_recursive (brix_conn * c, const char * path, int mode, int * failures, brix_status * st)
Definition at line 67 of file xrdfs_walk.c.
References chmod_walk::c, c, chmod_visit(), chmod_walk::failures, failures, chmod_walk::mode, and walk_dir().
Referenced by do_chmod().
chmod_visit()
int chmod_visit (const char * full, const brix_dirent * e, int depth, void * u)
Definition at line 50 of file xrdfs_walk.c.
References brix_chmod(), brix_status_clear(), chmod_walk::c, chmod_walk::failures, chmod_walk::mode, and brix_status::msg.
Referenced by chmod_recursive().
df_field()
int64_t df_field (const char * reply, const char * key)
Definition at line 174 of file xrdfs_fmt.c.
References key.
Referenced by df_parse_space().
df_parse_space()
int df_parse_space (const char * reply, int64_t * total, int64_t * avail, int64_t * used, int64_t * largest)
Definition at line 184 of file xrdfs_fmt.c.
References df_field().
Referenced by do_df().
dispatch()
int dispatch (brix_conn * c, char * cwd, size_t cwdsz, int ntok, char ** tok, int * quit, const char * prog)
Definition at line 157 of file xrdfs.c.
References brix_prog_base(), brix_usage_footer(), c, dispatch_builtin(), dispatch_unknown(), find_command(), and tok.
Referenced by repl(), and run_root_endpoint().
do_cat()
int do_cat (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 125 of file xrdfs_data.c.
References brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, stream_file(), and XRDC_PATH_MAX.
do_chmod()
int do_chmod (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 376 of file xrdfs_meta.c.
References brix_chmod(), brix_shellcode(), brix_status_clear(), build_path(), c, chmod_recursive(), failures, brix_status::msg, parse_chmod_mode(), XRDC_PATH_MAX, and xrdfs_op_hints().
do_cksum()
int do_cksum (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 754 of file xrdfs_meta.c.
References brix_query_cksum(), brix_shellcode(), brix_status_clear(), build_path(), c, hex(), brix_status::msg, and XRDC_PATH_MAX.
do_cmp()
int do_cmp (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 707 of file xrdfs_data.c.
References brix_query_cksum(), brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, slurp_file(), and XRDC_PATH_MAX.
do_dd()
int do_dd (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 1026 of file xrdfs_data.c.
References dd_args_t::arg, brix_rfile_close(), brix_rfile_open_read(), brix_rfile_pread(), brix_shellcode(), brix_status_clear(), brix_status_set(), dd_args_t::bs, build_path(), c, dd_args_t::count, dd_parse_args(), brix_status::msg, dd_args_t::rate, rate_pace(), dd_args_t::skip, XRDC_ESOCK, and XRDC_PATH_MAX.
do_df()
int do_df (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 480 of file xrdfs_meta.c.
References brix_query(), brix_shellcode(), brix_status_clear(), build_path(), c, df_parse_space(), fmt_size(), kXR_Qspace, brix_status::msg, and XRDC_PATH_MAX.
do_download()
int do_download (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 1429 of file xrdfs_data.c.
References brix_rfile_close(), brix_rfile_open_read(), brix_shellcode(), brix_status_clear(), brix_vfs_abort(), brix_vfs_close(), xfer_args_t::bs, build_path(), c, download_copy_loop(), download_default_local(), download_finalize_local(), download_open_local(), download_parse_args(), xfer_args_t::force, xfer_args_t::io_uring_mode, brix_status::msg, xfer_args_t::pos1, xfer_args_t::pos2, xfer_args_t::rate, XRDC_IO_URING_AUTO, and XRDC_PATH_MAX.
do_du()
int do_du (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 179 of file xrdfs_walk.c.
References build_path(), c, du_one_path(), du_parse_flags(), and XRDC_PATH_MAX.
do_evict()
int do_evict (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 1062 of file xrdfs_meta.c.
References brix_prepare(), brix_shellcode(), brix_status_clear(), build_path(), c, kXR_evict, brix_status::msg, and XRDC_PATH_MAX.
do_explain()
int do_explain (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 79 of file xrdfs.c.
References brix_explain_conn(), and c.
do_find()
int do_find (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 275 of file xrdfs_walk.c.
References brix_shellcode(), brix_status_clear(), build_path(), c, find_parse_args(), find_visit(), brix_status::msg, walk_dir(), and XRDC_PATH_MAX.
do_grep()
int do_grep (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 846 of file xrdfs_data.c.
References grep_args_t::arg, brix_rfile_close(), brix_rfile_open_read(), brix_rfile_pread(), brix_shellcode(), brix_status_clear(), build_path(), c, grep_parse_args(), grep_scan_chunk(), grep_args_t::icase, grep_scan_t::line, grep_scan_t::matched, brix_status::msg, grep_args_t::numbered, grep_args_t::pattern, and XRDC_PATH_MAX.
do_head()
int do_head (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 224 of file xrdfs_data.c.
References brix_shellcode(), brix_status_clear(), build_path(), c, head_lines(), brix_status::msg, stream_file(), and XRDC_PATH_MAX.
do_hexdump()
int do_hexdump (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 949 of file xrdfs_data.c.
References brix_rfile_close(), brix_rfile_open_read(), brix_shellcode(), brix_status_clear(), build_path(), c, hexdump_stream(), brix_status::msg, and XRDC_PATH_MAX.
do_ln()
int do_ln (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 681 of file xrdfs_meta.c.
References brix_link(), brix_rm(), brix_shellcode(), brix_status_clear(), brix_symlink(), build_path(), c, brix_status::msg, XRDC_PATH_MAX, and xrdfs_op_hints().
do_locate()
int do_locate (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 441 of file xrdfs_meta.c.
References brix_locate(), brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, and XRDC_PATH_MAX.
do_ls()
int do_ls (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 200 of file xrdfs_meta.c.
References brix_shellcode(), brix_status_clear(), build_path(), c, ls_json_dir(), ls_print_dir(), brix_status::msg, XRDC_PATH_MAX, and xrdfs_op_hints().
do_mkdir()
int do_mkdir (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 238 of file xrdfs_meta.c.
References brix_mkdir(), brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, XRDC_PATH_MAX, and xrdfs_op_hints().
do_mv()
int do_mv (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 353 of file xrdfs_meta.c.
References brix_mv(), brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, XRDC_PATH_MAX, and xrdfs_op_hints().
do_prepare()
int do_prepare (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 979 of file xrdfs_meta.c.
References brix_prepare(), brix_shellcode(), brix_status_clear(), build_path(), c, kXR_cancel, kXR_evict, kXR_fresh, kXR_stage, kXR_wmode, brix_status::msg, and XRDC_PATH_MAX.
do_query()
int do_query (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 939 of file xrdfs_meta.c.
References brix_query(), brix_shellcode(), brix_status_clear(), build_path(), c, kXR_Qcksum, kXR_Qconfig, kXR_Qspace, kXR_QStats, brix_status::msg, and XRDC_PATH_MAX.
do_readlink()
int do_readlink (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 727 of file xrdfs_meta.c.
References brix_readlink(), brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, and XRDC_PATH_MAX.
do_readv()
int do_readv (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 1538 of file xrdfs_data.c.
References brix_file_close(), brix_file_open_read(), brix_file_readv(), brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, readv_parse_segs(), XRDC_PATH_MAX, and XRDC_VEC_MAXSEGS.
do_rm()
int do_rm (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 281 of file xrdfs_meta.c.
References brix_cred_hint_for_status(), brix_rm(), brix_rmtree(), brix_shellcode(), brix_stat(), brix_status_clear(), build_path(), c, brix_statinfo::flags, kXR_isDir, brix_status::msg, rm_report(), XRDC_PATH_MAX, and xrdfs_op_hints().
do_rmdir()
int do_rmdir (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 335 of file xrdfs_meta.c.
References brix_rmdir(), brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, XRDC_PATH_MAX, and xrdfs_op_hints().
do_stage()
int do_stage (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 1016 of file xrdfs_meta.c.
References brix_prepare(), brix_shellcode(), brix_status_clear(), build_path(), c, kXR_stage, brix_status::msg, wait_online(), and XRDC_PATH_MAX.
do_stat()
int do_stat (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 13 of file xrdfs_meta.c.
References brix_shellcode(), brix_stat(), brix_status_clear(), build_path(), c, json_statinfo(), brix_status::msg, print_statinfo(), XRDC_PATH_MAX, and xrdfs_op_hints().
do_statvfs()
int do_statvfs (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 459 of file xrdfs_meta.c.
References brix_shellcode(), brix_status_clear(), brix_statvfs(), build_path(), c, brix_status::msg, and XRDC_PATH_MAX.
do_tail()
int do_tail (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 522 of file xrdfs_data.c.
References tail_args_t::arg, brix_shellcode(), brix_stat(), brix_status_clear(), build_path(), c, tail_args_t::follow, tail_args_t::interval, brix_status::msg, tail_args_t::nbytes, tail_args_t::nlines, brix_statinfo::size, stream_file(), tail_follow(), tail_parse_args(), tail_start_for_lines(), and XRDC_PATH_MAX.
do_touch()
int do_touch (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 636 of file xrdfs_meta.c.
References brix_setattr(), brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, touch_ensure_file(), touch_fill_times(), touch_parse_argv(), XRDC_PATH_MAX, and xrdfs_op_hints().
do_tree()
int do_tree (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 385 of file xrdfs_walk.c.
References brix_shellcode(), brix_status_clear(), build_path(), c, tree_opts::dirs_only, tree_opts::maxdepth, brix_status::msg, tree_opts::ndirs, tree_opts::nfiles, tree_recurse(), and XRDC_PATH_MAX.
do_truncate()
int do_truncate (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 421 of file xrdfs_meta.c.
References brix_shellcode(), brix_status_clear(), brix_truncate(), build_path(), c, brix_status::msg, XRDC_PATH_MAX, and xrdfs_op_hints().
do_upload()
int do_upload (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 1224 of file xrdfs_data.c.
References brix_rfile_close(), brix_rfile_open_write(), brix_shellcode(), brix_status_clear(), brix_vfs_close(), brix_vfs_open(), xfer_args_t::bs, build_path(), c, brix_vfs_open_opts::cred, brix_vfs_open_opts::expected_size, xfer_args_t::force, brix_vfs_open_opts::io_uring, xfer_args_t::io_uring_mode, brix_status::msg, xfer_args_t::pos1, xfer_args_t::pos2, xfer_args_t::rate, upload_copy_loop(), upload_parse_args(), XRDC_IO_URING_AUTO, XRDC_PATH_MAX, XRDC_VFS_READ, and xrdfs_op_hints().
do_wc()
int do_wc (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 639 of file xrdfs_data.c.
References wc_args_t::arg, brix_shellcode(), brix_stat(), brix_status_clear(), build_path(), c, brix_status::msg, brix_statinfo::size, wc_args_t::want_c, wc_args_t::want_l, wc_args_t::want_w, wc_count_stream(), wc_parse_args(), and XRDC_PATH_MAX.
do_writev()
int do_writev (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 1644 of file xrdfs_data.c.
References brix_file_close(), brix_file_open_write(), brix_file_writev(), brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, writev_parse_segs(), XRDC_PATH_MAX, and XRDC_VEC_MAXSEGS.
do_xattr()
int do_xattr (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 912 of file xrdfs_meta.c.
References build_path(), c, xattr_get(), xattr_is_subcommand(), xattr_ls(), xattr_rm(), xattr_set(), and XRDC_PATH_MAX.
du_visit()
int du_visit (const char * full, const brix_dirent * e, int depth, void * u)
Definition at line 107 of file xrdfs_walk.c.
References du_acc::bytes, du_acc::dirs, du_acc::files, brix_statinfo::flags, brix_dirent::have_stat, kXR_isDir, brix_statinfo::size, and brix_dirent::st.
Referenced by du_one_path().
endpoint_to_url()
int endpoint_to_url (const char * ep, brix_url * u, brix_status * st)
Definition at line 8 of file xrdfs_fmt.c.
References brix_alias_resolve(), brix_endpoint_parse(), and XRDC_PATH_MAX.
Referenced by run_root_endpoint().
find_command()
const xrdfs_cmd * find_command (const char * name)
Definition at line 419 of file xrdfs_walk.c.
References COMMANDS, and name.
Referenced by dispatch().
find_visit()
int find_visit (const char * full, const brix_dirent * e, int depth, void * u)
Definition at line 213 of file xrdfs_walk.c.
References brix_statinfo::flags, brix_dirent::have_stat, kXR_isDir, brix_dirent::name, find_pred::name_glob, brix_statinfo::size, find_pred::size_sign, find_pred::size_val, brix_dirent::st, and find_pred::type.
Referenced by do_find().
flags_to_str()
void flags_to_str (int f, char * out, size_t sz)
Definition at line 26 of file xrdfs_fmt.c.
References kXR_bkpexist, kXR_isDir, kXR_offline, kXR_other, kXR_poscpend, kXR_readable, kXR_writable, kXR_xset, and XRDFS_ADD.
Referenced by print_statinfo().
fmt_size()
void fmt_size (int64_t n, char * out, size_t sz, int human)
Definition at line 386 of file xrdfs_fmt.c.
References brix_fmt_size().
Referenced by do_df(), du_print(), ls_print_entry(), and web_print_one_entry().
head_lines()
int head_lines (brix_conn * c, const char * path, long nlines, brix_status * st)
Definition at line 174 of file xrdfs_data.c.
References brix_rfile_close(), brix_rfile_open_read(), brix_rfile_pread(), brix_status_clear(), brix_status_set(), c, emit(), XRDC_EPROTO, and XRDC_ESOCK.
Referenced by do_head().
is_dot()
int is_dot (const char * name)
Definition at line 377 of file xrdfs_fmt.c.
References name.
Referenced by ls_recurse_subdirs(), tree_collect(), walk_dir(), and web_ls_recurse_children().
join_path()
int join_path (const char * dir, const char * name, char * out, size_t sz)
Definition at line 394 of file xrdfs_fmt.c.
References name.
Referenced by ls_recurse_subdirs(), tree_emit(), walk_dir(), and web_ls_recurse_children().
json_statinfo()
void json_statinfo (const char * path, const brix_statinfo * si)
Definition at line 110 of file xrdfs_fmt.c.
References brix_json_kv_bool(), brix_json_kv_ll(), brix_json_kv_str(), brix_statinfo::flags, brix_statinfo::group, brix_statinfo::have_ext, kXR_isDir, brix_statinfo::mode, brix_statinfo::mtime, brix_statinfo::owner, and brix_statinfo::size.
Referenced by do_stat().
ls_print_dir()
int ls_print_dir (brix_conn * c, const char * path, int want_long, int recursive, int human, brix_status * st)
Definition at line 116 of file xrdfs_meta.c.
References brix_dirlist(), c, ls_print_entry(), ls_recurse_subdirs(), and XRDC_PATH_MAX.
Referenced by do_ls(), and ls_recurse_subdirs().
parse_bytes()
int64_t parse_bytes (const char * s)
Definition at line 339 of file xrdfs_fmt.c.
References brix_parse_bytes(), and s.
Referenced by dd_parse_args(), and xfer_common_arg().
parse_chmod_mode()
int parse_chmod_mode (const char * s)
Definition at line 140 of file xrdfs_fmt.c.
References s.
Referenced by do_chmod().
parse_u64_strict()
int parse_u64_strict (const char * s, unsigned long long * out)
Definition at line 355 of file xrdfs_fmt.c.
References s.
Referenced by readv_parse_segs(), and writev_parse_seg().
print_stat_time()
void print_stat_time (const char * label, long epoch)
Definition at line 63 of file xrdfs_fmt.c.
Referenced by print_statinfo().
print_statinfo()
void print_statinfo (const char * path, const brix_statinfo * si)
Definition at line 81 of file xrdfs_fmt.c.
References brix_statinfo::atime, brix_statinfo::ctime, brix_statinfo::flags, flags_to_str(), brix_statinfo::group, brix_statinfo::have_ext, brix_statinfo::id, brix_statinfo::mode, brix_statinfo::mtime, brix_statinfo::owner, print_stat_time(), and brix_statinfo::size.
Referenced by do_stat(), and web_stat().
rate_pace()
void rate_pace (const struct timespec * start, int64_t sent, double rate)
Definition at line 346 of file xrdfs_fmt.c.
References brix_rate_pace().
Referenced by do_dd(), download_copy_loop(), and upload_copy_loop().
repl()
int repl (brix_conn * c, const char * host, int port, const char * prog)
Definition at line 204 of file xrdfs.c.
References c, dispatch(), host, port, tok, tokenize(), XRDC_PATH_MAX, and XRDFS_MAXTOK.
Referenced by run_root_endpoint().
slurp_file()
int slurp_file (brix_conn * c, const char * path, uint8_t ** out, int64_t * len, brix_status * st)
Definition at line 674 of file xrdfs_data.c.
References brix_rfile_close(), brix_rfile_open_read(), brix_rfile_pread(), brix_stat(), brix_status_set(), c, brix_statinfo::size, and XRDC_EPROTO.
Referenced by do_cmp().
stream_file()
int stream_file (brix_conn * c, const char * path, const char * opaque, int64_t start, int64_t limit, brix_status * st)
Definition at line 61 of file xrdfs_data.c.
References brix_rfile_close(), brix_rfile_open_read(), brix_rfile_pread(), brix_status_clear(), brix_status_set(), c, XRDC_EPROTO, and XRDC_ESOCK.
Referenced by do_cat(), do_head(), and do_tail().
tail_follow()
int tail_follow (brix_conn * c, const char * path, int64_t from, double interval, brix_status * st)
Definition at line 416 of file xrdfs_data.c.
References brix_mono_ns(), brix_reconnect_home(), brix_resilient_window_ms(), brix_rfile_close(), brix_rfile_open_read(), brix_stat(), brix_status_clear(), brix_status_retryable(), brix_status_set(), tail_follow_t::buf, tail_follow_t::c, c, tail_follow_t::off, tail_follow_t::path, tail_follow_t::rf, tail_follow_t::rf_open, brix_statinfo::size, tail_follow_drain(), tail_sigint(), tail_stop, and XRDC_EPROTO.
Referenced by do_tail().
tail_sigint()
void tail_sigint (int sig)
Definition at line 266 of file xrdfs_data.c.
References tail_stop.
Referenced by tail_follow().
tail_start_for_lines()
int tail_start_for_lines (brix_conn * c, const char * path, int64_t size, long nlines, int64_t * start, brix_status * st)
Definition at line 312 of file xrdfs_data.c.
References brix_rfile_close(), brix_rfile_open_read(), brix_rfile_pread(), brix_status_clear(), brix_status_set(), c, tail_scan_t::start, tail_scan_window(), and XRDC_EPROTO.
Referenced by do_tail().
tokenize()
int tokenize (char * line, char ** tok, int maxtok)
Definition at line 187 of file xrdfs.c.
References tok.
Referenced by repl().
touch_parse_time()
int touch_parse_time (const char * s, struct timespec * out)
Definition at line 300 of file xrdfs_fmt.c.
References s, touch_collect_digits(), touch_parse_seconds(), touch_resolve_year(), and two_digits().
Referenced by touch_parse_argv().
tree_recurse()
int tree_recurse (brix_conn * c, const char * path, const char * prefix, int depth, tree_opts * o, brix_status * st)
Definition at line 352 of file xrdfs_walk.c.
References brix_dirlist(), brix_status_set(), c, tree_opts::maxdepth, tree_collect(), tree_emit(), and XRDC_EPROTO.
Referenced by do_tree(), and tree_emit().
two_digits()
int two_digits (const char * p)
Definition at line 197 of file xrdfs_fmt.c.
Referenced by touch_parse_seconds(), touch_parse_time(), and touch_resolve_year().
usage()
void usage (const char * prog)
Definition at line 180 of file xrdcp.c.
References usage_fp(), usage_fp(), usage_fp(), and usage_fp().
wait_online()
int wait_online (brix_conn * c, const char * path, int timeout_s, brix_status * st)
Definition at line 58 of file xrdfs.c.
References brix_stat(), brix_status_clear(), c, brix_statinfo::flags, and kXR_offline.
Referenced by do_stage().
walk_dir()
int walk_dir (brix_conn * c, const char * path, int depth, xrdfs_visit visit, void * u, brix_status * st)
Definition at line 13 of file xrdfs_walk.c.
References brix_dirlist(), c, is_dot(), join_path(), kXR_isDir, name, walk_dir(), XRDC_PATH_MAX, and XRDFS_MAXDEPTH.
Referenced by chmod_recursive(), do_find(), du_one_path(), and walk_dir().
web_build_path()
void web_build_path (const char * base, const char * cwd, const char * arg, char * out, size_t outsz)
Definition at line 20 of file xrdfs_web.c.
References build_path(), and XRDC_PATH_MAX.
Referenced by web_ls(), and web_stat().
web_dispatch()
int web_dispatch (const web_ctx * w, int argc, char ** argv)
Definition at line 192 of file xrdfs_web.c.
References web_ls(), and web_stat().
Referenced by run_web_endpoint().
web_ls()
int web_ls (const web_ctx * w, const char * cwd, int argc, char ** argv)
Definition at line 144 of file xrdfs_web.c.
References web_ctx::base, brix_shellcode(), brix_status_clear(), brix_status::msg, web_build_path(), web_ls_print_dir(), XRDC_PATH_MAX, and xrdfs_web_hints().
Referenced by web_dispatch().
web_ls_print_dir()
int web_ls_print_dir (const web_ctx * w, const char * path, int want_long, int recursive, int human, brix_status * st)
Definition at line 114 of file xrdfs_web.c.
References web_ctx::bearer, brix_web_readdir(), web_ctx::ca_dir, web_ctx::u, web_ctx::verify, web_ls_recurse_children(), web_print_one_entry(), and XRDC_PATH_MAX.
Referenced by web_ls(), and web_ls_recurse_children().
web_stat()
int web_stat (const web_ctx * w, const char * cwd, int argc, char ** argv)
Definition at line 171 of file xrdfs_web.c.
References web_ctx::base, web_ctx::bearer, brix_shellcode(), brix_status_clear(), brix_web_stat(), web_ctx::ca_dir, brix_status::msg, print_statinfo(), web_ctx::u, web_ctx::verify, web_build_path(), XRDC_PATH_MAX, and xrdfs_web_hints().
Referenced by web_dispatch().
xattr_ls()
int xattr_ls (brix_conn * c, const char * path)
Definition at line 784 of file xrdfs_meta.c.
References brix_fattr_list(), brix_shellcode(), brix_status_clear(), c, brix_status::msg, and name.
Referenced by do_xattr().
xrdfs_op_hints()
static void xrdfs_op_hints (const brix_status * st, int want_write, const brix_conn * c) inline static
Definition at line 38 of file xrdfs_internal.h.
References brix_cred_hint_for_status_url(), brix_hint_url_double_slash(), c, brix_url::host, brix_url::port, brix_url::scheme, brix_url::single_slash_path, and XRDC_SCHEME_ROOT.
Referenced by do_chmod(), do_ln(), do_ls(), do_mkdir(), do_mv(), do_rm(), do_rmdir(), do_stat(), do_touch(), do_truncate(), and do_upload().
xrdfs_web_hints()
static void xrdfs_web_hints (const brix_status * st, int want_write, const web_ctx * w) inline static
Definition at line 75 of file xrdfs_internal.h.
References brix_cred_hint_for_status_url(), brix_weburl::host, and web_ctx::u.
Referenced by web_ls(), and web_stat().
Variable Documentation
COMMANDS
const xrdfs_cmd COMMANDS[] extern
Definition at line 13 of file xrdfs.c.
Referenced by dispatch_builtin(), dispatch_unknown(), and find_command().
tail_stop
volatile sig_atomic_t tail_stop extern
Definition at line 11 of file xrdfs.c.
Referenced by tail_follow(), and tail_sigint().