nginx-xrootd: client/apps/fs/xrdfs_meta.c File Reference
xrdfs_meta.c File Reference
#include "xrdfs_internal.h"
Functions
int do_stat (brix_conn *c, const char *cwd, int argc, char **argv)
static void ls_print_entry (const brix_dirent *ent, const char *prefix, int want_long, int human)
static int ls_recurse_subdirs (brix_conn *c, const char *path, const brix_dirent *ents, size_t n, int want_long, int human, brix_status *st)
int ls_print_dir (brix_conn *c, const char *path, int want_long, int recursive, int human, brix_status *st)
static int ls_json_dir (brix_conn *c, const char *path, brix_status *st)
int do_ls (brix_conn *c, const char *cwd, int argc, char **argv)
int do_mkdir (brix_conn *c, const char *cwd, int argc, char **argv)
static int rm_report (const char *path, int is_dir, void *u)
int do_rm (brix_conn *c, const char *cwd, int argc, char **argv)
int do_rmdir (brix_conn *c, const char *cwd, int argc, char **argv)
int do_mv (brix_conn *c, const char *cwd, int argc, char **argv)
int do_chmod (brix_conn *c, const char *cwd, int argc, char **argv)
int do_truncate (brix_conn *c, const char *cwd, int argc, char **argv)
int do_locate (brix_conn *c, const char *cwd, int argc, char **argv)
int do_statvfs (brix_conn *c, const char *cwd, int argc, char **argv)
int do_df (brix_conn *c, const char *cwd, int argc, char **argv)
static int touch_parse_argv (int argc, char **argv, int *no_create, int *do_atime, int *do_mtime, int *have_t, struct timespec *tspec, const char **arg)
static void touch_fill_times (struct timespec times[2], int do_atime, int do_mtime, int have_t, const struct timespec *tspec)
static int touch_ensure_file (brix_conn *c, const char *path, int no_create)
int do_touch (brix_conn *c, const char *cwd, int argc, char **argv)
int do_ln (brix_conn *c, const char *cwd, int argc, char **argv)
int do_readlink (brix_conn *c, const char *cwd, int argc, char **argv)
int do_cksum (brix_conn *c, const char *cwd, int argc, char **argv)
int xattr_ls (brix_conn *c, const char *path)
static int xattr_is_subcommand (const char *s)
static int xattr_get (brix_conn *c, const char *path, int argc, char **argv)
static int xattr_set (brix_conn *c, const char *path, int argc, char **argv)
static int xattr_rm (brix_conn *c, const char *path, int argc, char **argv)
int do_xattr (brix_conn *c, const char *cwd, int argc, char **argv)
int do_query (brix_conn *c, const char *cwd, int argc, char **argv)
int do_prepare (brix_conn *c, const char *cwd, int argc, char **argv)
int do_stage (brix_conn *c, const char *cwd, int argc, char **argv)
int do_evict (brix_conn *c, const char *cwd, int argc, char **argv)
Function Documentation
do_chmod()
int do_chmod (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 376 of file xrdfs_meta.c.
References brix_chmod(), brix_shellcode(), brix_status_clear(), build_path(), c, chmod_recursive(), failures, brix_status::msg, parse_chmod_mode(), XRDC_PATH_MAX, and xrdfs_op_hints().
do_cksum()
int do_cksum (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 754 of file xrdfs_meta.c.
References brix_query_cksum(), brix_shellcode(), brix_status_clear(), build_path(), c, hex(), brix_status::msg, and XRDC_PATH_MAX.
do_df()
int do_df (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 480 of file xrdfs_meta.c.
References brix_query(), brix_shellcode(), brix_status_clear(), build_path(), c, df_parse_space(), fmt_size(), kXR_Qspace, brix_status::msg, and XRDC_PATH_MAX.
do_evict()
int do_evict (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 1062 of file xrdfs_meta.c.
References brix_prepare(), brix_shellcode(), brix_status_clear(), build_path(), c, kXR_evict, brix_status::msg, and XRDC_PATH_MAX.
do_ln()
int do_ln (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 681 of file xrdfs_meta.c.
References brix_link(), brix_rm(), brix_shellcode(), brix_status_clear(), brix_symlink(), build_path(), c, brix_status::msg, XRDC_PATH_MAX, and xrdfs_op_hints().
do_locate()
int do_locate (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 441 of file xrdfs_meta.c.
References brix_locate(), brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, and XRDC_PATH_MAX.
do_ls()
int do_ls (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 200 of file xrdfs_meta.c.
References brix_shellcode(), brix_status_clear(), build_path(), c, ls_json_dir(), ls_print_dir(), brix_status::msg, XRDC_PATH_MAX, and xrdfs_op_hints().
do_mkdir()
int do_mkdir (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 238 of file xrdfs_meta.c.
References brix_mkdir(), brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, XRDC_PATH_MAX, and xrdfs_op_hints().
do_mv()
int do_mv (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 353 of file xrdfs_meta.c.
References brix_mv(), brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, XRDC_PATH_MAX, and xrdfs_op_hints().
do_prepare()
int do_prepare (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 979 of file xrdfs_meta.c.
References brix_prepare(), brix_shellcode(), brix_status_clear(), build_path(), c, kXR_cancel, kXR_evict, kXR_fresh, kXR_stage, kXR_wmode, brix_status::msg, and XRDC_PATH_MAX.
do_query()
int do_query (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 939 of file xrdfs_meta.c.
References brix_query(), brix_shellcode(), brix_status_clear(), build_path(), c, kXR_Qcksum, kXR_Qconfig, kXR_Qspace, kXR_QStats, brix_status::msg, and XRDC_PATH_MAX.
do_readlink()
int do_readlink (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 727 of file xrdfs_meta.c.
References brix_readlink(), brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, and XRDC_PATH_MAX.
do_rm()
int do_rm (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 281 of file xrdfs_meta.c.
References brix_cred_hint_for_status(), brix_rm(), brix_rmtree(), brix_shellcode(), brix_stat(), brix_status_clear(), build_path(), c, brix_statinfo::flags, kXR_isDir, brix_status::msg, rm_report(), XRDC_PATH_MAX, and xrdfs_op_hints().
do_rmdir()
int do_rmdir (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 335 of file xrdfs_meta.c.
References brix_rmdir(), brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, XRDC_PATH_MAX, and xrdfs_op_hints().
do_stage()
int do_stage (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 1016 of file xrdfs_meta.c.
References brix_prepare(), brix_shellcode(), brix_status_clear(), build_path(), c, kXR_stage, brix_status::msg, wait_online(), and XRDC_PATH_MAX.
do_stat()
int do_stat (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 13 of file xrdfs_meta.c.
References brix_shellcode(), brix_stat(), brix_status_clear(), build_path(), c, json_statinfo(), brix_status::msg, print_statinfo(), XRDC_PATH_MAX, and xrdfs_op_hints().
do_statvfs()
int do_statvfs (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 459 of file xrdfs_meta.c.
References brix_shellcode(), brix_status_clear(), brix_statvfs(), build_path(), c, brix_status::msg, and XRDC_PATH_MAX.
do_touch()
int do_touch (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 636 of file xrdfs_meta.c.
References brix_setattr(), brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, touch_ensure_file(), touch_fill_times(), touch_parse_argv(), XRDC_PATH_MAX, and xrdfs_op_hints().
do_truncate()
int do_truncate (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 421 of file xrdfs_meta.c.
References brix_shellcode(), brix_status_clear(), brix_truncate(), build_path(), c, brix_status::msg, XRDC_PATH_MAX, and xrdfs_op_hints().
do_xattr()
int do_xattr (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 912 of file xrdfs_meta.c.
References build_path(), c, xattr_get(), xattr_is_subcommand(), xattr_ls(), xattr_rm(), xattr_set(), and XRDC_PATH_MAX.
ls_json_dir()
static int ls_json_dir (brix_conn * c, const char * path, brix_status * st) static
Definition at line 152 of file xrdfs_meta.c.
References brix_dirlist(), brix_json_kv_bool(), brix_json_kv_ll(), brix_json_kv_str(), c, brix_statinfo::flags, brix_dirent::have_stat, kXR_isDir, name, brix_dirent::st, and XRDC_PATH_MAX.
Referenced by do_ls().
ls_print_dir()
int ls_print_dir (brix_conn * c, const char * path, int want_long, int recursive, int human, brix_status * st)
Definition at line 116 of file xrdfs_meta.c.
References brix_dirlist(), c, ls_print_entry(), ls_recurse_subdirs(), and XRDC_PATH_MAX.
Referenced by do_ls(), and ls_recurse_subdirs().
ls_print_entry()
static void ls_print_entry (const brix_dirent * ent, const char * prefix, int want_long, int human) static
Definition at line 57 of file xrdfs_meta.c.
References brix_statinfo::flags, fmt_size(), brix_dirent::have_stat, kXR_isDir, kXR_readable, kXR_writable, brix_dirent::name, brix_statinfo::size, and brix_dirent::st.
Referenced by ls_print_dir().
ls_recurse_subdirs()
static int ls_recurse_subdirs (brix_conn * c, const char * path, const brix_dirent * ents, size_t n, int want_long, int human, brix_status * st) static
Definition at line 89 of file xrdfs_meta.c.
References c, is_dot(), join_path(), kXR_isDir, ls_print_dir(), name, and XRDC_PATH_MAX.
Referenced by ls_print_dir().
rm_report()
static int rm_report (const char * path, int is_dir, void * u) static
Definition at line 266 of file xrdfs_meta.c.
Referenced by do_rm().
touch_ensure_file()
static int touch_ensure_file (brix_conn * c, const char * path, int no_create) static
Definition at line 608 of file xrdfs_meta.c.
References brix_file_close(), brix_file_open_write(), brix_stat(), brix_status_clear(), and c.
Referenced by do_touch().
touch_fill_times()
static void touch_fill_times (struct timespec times[2], int do_atime, int do_mtime, int have_t, const struct timespec * tspec) static
Definition at line 578 of file xrdfs_meta.c.
Referenced by do_touch().
touch_parse_argv()
static int touch_parse_argv (int argc, char ** argv, int * no_create, int * do_atime, int * do_mtime, int * have_t, struct timespec * tspec, const char ** arg) static
Definition at line 540 of file xrdfs_meta.c.
References touch_parse_time().
Referenced by do_touch().
xattr_get()
static int xattr_get (brix_conn * c, const char * path, int argc, char ** argv) static
Definition at line 840 of file xrdfs_meta.c.
References brix_fattr_get(), brix_shellcode(), brix_status_clear(), c, and brix_status::msg.
Referenced by do_xattr().
xattr_is_subcommand()
static int xattr_is_subcommand (const char * s) static
Definition at line 819 of file xrdfs_meta.c.
References s.
Referenced by do_xattr().
xattr_ls()
int xattr_ls (brix_conn * c, const char * path)
Definition at line 784 of file xrdfs_meta.c.
References brix_fattr_list(), brix_shellcode(), brix_status_clear(), c, brix_status::msg, and name.
Referenced by do_xattr().
xattr_rm()
static int xattr_rm (brix_conn * c, const char * path, int argc, char ** argv) static
Definition at line 897 of file xrdfs_meta.c.
References brix_fattr_del(), brix_shellcode(), brix_status_clear(), c, and brix_status::msg.
Referenced by do_xattr().
xattr_set()
static int xattr_set (brix_conn * c, const char * path, int argc, char ** argv) static
Definition at line 871 of file xrdfs_meta.c.
References brix_fattr_set(), brix_shellcode(), brix_status_clear(), c, and brix_status::msg.
Referenced by do_xattr().