nginx-xrootd: client/apps/fs/xrdfs_fmt.c File Reference
xrdfs_fmt.c File Reference
#include "xrdfs_internal.h"
Macros
#define XRDFS_ADD(bit, name)
Functions
int endpoint_to_url (const char *ep, brix_url *u, brix_status *st)
void build_path (const char *cwd, const char *arg, char *out, size_t outsz)
void flags_to_str (int f, char *out, size_t sz)
void print_stat_time (const char *label, long epoch)
void print_statinfo (const char *path, const brix_statinfo *si)
void json_statinfo (const char *path, const brix_statinfo *si)
int parse_chmod_mode (const char *s)
int64_t df_field (const char *reply, const char *key)
int df_parse_space (const char *reply, int64_t *total, int64_t *avail, int64_t *used, int64_t *largest)
int two_digits (const char *p)
static int touch_collect_digits (const char *s, char *d, size_t dcap, size_t *dn_out)
static int touch_parse_seconds (const char *dot, int *sec_out)
static int touch_resolve_year (size_t dn, const char *d, time_t now, const char **p_out)
int touch_parse_time (const char *s, struct timespec *out)
int64_t parse_bytes (const char *s)
void rate_pace (const struct timespec *start, int64_t sent, double rate)
int parse_u64_strict (const char *s, unsigned long long *out)
int is_dot (const char *name)
void fmt_size (int64_t n, char *out, size_t sz, int human)
int join_path (const char *dir, const char *name, char *out, size_t sz)
Macro Definition Documentation
XRDFS_ADD
#define XRDFS_ADD (bit, name)
Value:
    do {                                                          \
        if (f & (bit)) {                                          \
            if (!first) { strncat(out, "|", sz - strlen(out) - 1); } \
            strncat(out, (name), sz - strlen(out) - 1);           \
            first = 0;                                             \
        }                                                         \
    } while (0)
Function Documentation
build_path()
void build_path (const char * cwd, const char * arg, char * out, size_t outsz)
Definition at line 19 of file xrdfs_fmt.c.
References brix_path_resolve().
Referenced by dispatch_builtin(), do_cat(), do_chmod(), do_cksum(), do_cmp(), do_dd(), do_df(), do_download(), do_du(), do_evict(), do_find(), do_grep(), do_head(), do_hexdump(), do_ln(), do_locate(), do_ls(), do_mkdir(), do_mv(), do_prepare(), do_query(), do_readlink(), do_readv(), do_rm(), do_rmdir(), do_stage(), do_stat(), do_statvfs(), do_tail(), do_touch(), do_tree(), do_truncate(), do_upload(), do_wc(), do_writev(), do_xattr(), and web_build_path().
df_field()
int64_t df_field (const char * reply, const char * key)
Definition at line 174 of file xrdfs_fmt.c.
References key.
Referenced by df_parse_space().
df_parse_space()
int df_parse_space (const char * reply, int64_t * total, int64_t * avail, int64_t * used, int64_t * largest)
Definition at line 184 of file xrdfs_fmt.c.
References df_field().
Referenced by do_df().
endpoint_to_url()
int endpoint_to_url (const char * ep, brix_url * u, brix_status * st)
Definition at line 8 of file xrdfs_fmt.c.
References brix_alias_resolve(), brix_endpoint_parse(), and XRDC_PATH_MAX.
Referenced by run_root_endpoint().
flags_to_str()
void flags_to_str (int f, char * out, size_t sz)
Definition at line 26 of file xrdfs_fmt.c.
References kXR_bkpexist, kXR_isDir, kXR_offline, kXR_other, kXR_poscpend, kXR_readable, kXR_writable, kXR_xset, and XRDFS_ADD.
Referenced by print_statinfo().
fmt_size()
void fmt_size (int64_t n, char * out, size_t sz, int human)
Definition at line 386 of file xrdfs_fmt.c.
References brix_fmt_size().
Referenced by do_df(), du_print(), ls_print_entry(), and web_print_one_entry().
is_dot()
int is_dot (const char * name)
Definition at line 377 of file xrdfs_fmt.c.
References name.
Referenced by ls_recurse_subdirs(), tree_collect(), walk_dir(), and web_ls_recurse_children().
join_path()
int join_path (const char * dir, const char * name, char * out, size_t sz)
Definition at line 394 of file xrdfs_fmt.c.
References name.
Referenced by ls_recurse_subdirs(), tree_emit(), walk_dir(), and web_ls_recurse_children().
json_statinfo()
void json_statinfo (const char * path, const brix_statinfo * si)
Definition at line 110 of file xrdfs_fmt.c.
References brix_json_kv_bool(), brix_json_kv_ll(), brix_json_kv_str(), brix_statinfo::flags, brix_statinfo::group, brix_statinfo::have_ext, kXR_isDir, brix_statinfo::mode, brix_statinfo::mtime, brix_statinfo::owner, and brix_statinfo::size.
Referenced by do_stat().
parse_bytes()
int64_t parse_bytes (const char * s)
Definition at line 339 of file xrdfs_fmt.c.
References brix_parse_bytes(), and s.
Referenced by dd_parse_args(), and xfer_common_arg().
parse_chmod_mode()
int parse_chmod_mode (const char * s)
Definition at line 140 of file xrdfs_fmt.c.
References s.
Referenced by do_chmod().
parse_u64_strict()
int parse_u64_strict (const char * s, unsigned long long * out)
Definition at line 355 of file xrdfs_fmt.c.
References s.
Referenced by readv_parse_segs(), and writev_parse_seg().
print_stat_time()
void print_stat_time (const char * label, long epoch)
Definition at line 63 of file xrdfs_fmt.c.
Referenced by print_statinfo().
print_statinfo()
void print_statinfo (const char * path, const brix_statinfo * si)
Definition at line 81 of file xrdfs_fmt.c.
References brix_statinfo::atime, brix_statinfo::ctime, brix_statinfo::flags, flags_to_str(), brix_statinfo::group, brix_statinfo::have_ext, brix_statinfo::id, brix_statinfo::mode, brix_statinfo::mtime, brix_statinfo::owner, print_stat_time(), and brix_statinfo::size.
Referenced by do_stat(), and web_stat().
rate_pace()
void rate_pace (const struct timespec * start, int64_t sent, double rate)
Definition at line 346 of file xrdfs_fmt.c.
References brix_rate_pace().
Referenced by do_dd(), download_copy_loop(), and upload_copy_loop().
touch_collect_digits()
static int touch_collect_digits (const char * s, char * d, size_t dcap, size_t * dn_out) static
Definition at line 219 of file xrdfs_fmt.c.
References s.
Referenced by touch_parse_time().
touch_parse_seconds()
static int touch_parse_seconds (const char * dot, int * sec_out) static
Definition at line 247 of file xrdfs_fmt.c.
References two_digits().
Referenced by touch_parse_time().
touch_parse_time()
int touch_parse_time (const char * s, struct timespec * out)
Definition at line 300 of file xrdfs_fmt.c.
References s, touch_collect_digits(), touch_parse_seconds(), touch_resolve_year(), and two_digits().
Referenced by touch_parse_argv().
touch_resolve_year()
static int touch_resolve_year (size_t dn, const char * d, time_t now, const char ** p_out) static
Definition at line 276 of file xrdfs_fmt.c.
References two_digits().
Referenced by touch_parse_time().
two_digits()
int two_digits (const char * p)
Definition at line 197 of file xrdfs_fmt.c.
Referenced by touch_parse_seconds(), touch_parse_time(), and touch_resolve_year().