nginx-xrootd: client/apps/fs/xrdfs_walk.c File Reference
xrdfs_walk.c File Reference
#include "xrdfs_internal.h"
Functions
int walk_dir (brix_conn *c, const char *path, int depth, xrdfs_visit visit, void *u, brix_status *st)
int chmod_visit (const char *full, const brix_dirent *e, int depth, void *u)
int chmod_recursive (brix_conn *c, const char *path, int mode, int *failures, brix_status *st)
static void du_print (const char *path, const du_acc *a, int human, int json)
int du_visit (const char *full, const brix_dirent *e, int depth, void *u)
static void du_parse_flags (int argc, char **argv, int *human, int *json)
static int du_one_path (brix_conn *c, const char *path, int human, int json, int *jfirst)
int do_du (brix_conn *c, const char *cwd, int argc, char **argv)
int find_visit (const char *full, const brix_dirent *e, int depth, void *u)
static void find_parse_size (const char *s, find_pred *p)
static void find_parse_args (int argc, char **argv, find_pred *p, const char **start)
int do_find (brix_conn *c, const char *cwd, int argc, char **argv)
static int tree_collect (const brix_dirent *ents, size_t n, const tree_opts *o, int *keep)
static int tree_emit (brix_conn *c, const char *path, const char *prefix, brix_dirent *e, int last, int depth, tree_opts *o, brix_status *st)
int tree_recurse (brix_conn *c, const char *path, const char *prefix, int depth, tree_opts *o, brix_status *st)
int do_tree (brix_conn *c, const char *cwd, int argc, char **argv)
const xrdfs_cmd * find_command (const char *name)
Function Documentation
chmod_recursive()
int chmod_recursive (brix_conn * c, const char * path, int mode, int * failures, brix_status * st)
Definition at line 67 of file xrdfs_walk.c.
References chmod_walk::c, c, chmod_visit(), chmod_walk::failures, failures, chmod_walk::mode, and walk_dir().
Referenced by do_chmod().
chmod_visit()
int chmod_visit (const char * full, const brix_dirent * e, int depth, void * u)
Definition at line 50 of file xrdfs_walk.c.
References brix_chmod(), brix_status_clear(), chmod_walk::c, chmod_walk::failures, chmod_walk::mode, and brix_status::msg.
Referenced by chmod_recursive().
do_du()
int do_du (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 179 of file xrdfs_walk.c.
References build_path(), c, du_one_path(), du_parse_flags(), and XRDC_PATH_MAX.
do_find()
int do_find (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 275 of file xrdfs_walk.c.
References brix_shellcode(), brix_status_clear(), build_path(), c, find_parse_args(), find_visit(), brix_status::msg, walk_dir(), and XRDC_PATH_MAX.
do_tree()
int do_tree (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 385 of file xrdfs_walk.c.
References brix_shellcode(), brix_status_clear(), build_path(), c, tree_opts::dirs_only, tree_opts::maxdepth, brix_status::msg, tree_opts::ndirs, tree_opts::nfiles, tree_recurse(), and XRDC_PATH_MAX.
du_one_path()
static int du_one_path (brix_conn * c, const char * path, int human, int json, int * jfirst) static
Definition at line 150 of file xrdfs_walk.c.
References brix_shellcode(), brix_status_clear(), c, du_print(), du_visit(), brix_status::msg, and walk_dir().
Referenced by do_du().
du_parse_flags()
static void du_parse_flags (int argc, char ** argv, int * human, int * json) static
Definition at line 129 of file xrdfs_walk.c.
Referenced by do_du().
du_print()
static void du_print (const char * path, const du_acc * a, int human, int json) static
Definition at line 89 of file xrdfs_walk.c.
References brix_json_kv_ll(), brix_json_kv_str(), du_acc::bytes, du_acc::dirs, du_acc::files, and fmt_size().
Referenced by du_one_path().
du_visit()
int du_visit (const char * full, const brix_dirent * e, int depth, void * u)
Definition at line 107 of file xrdfs_walk.c.
References du_acc::bytes, du_acc::dirs, du_acc::files, brix_statinfo::flags, brix_dirent::have_stat, kXR_isDir, brix_statinfo::size, and brix_dirent::st.
Referenced by du_one_path().
find_command()
const xrdfs_cmd * find_command (const char * name)
Definition at line 419 of file xrdfs_walk.c.
References COMMANDS, and name.
Referenced by dispatch().
find_parse_args()
static void find_parse_args (int argc, char ** argv, find_pred * p, const char ** start) static
Definition at line 255 of file xrdfs_walk.c.
References find_parse_size(), find_pred::name_glob, and find_pred::type.
Referenced by do_find().
find_parse_size()
static void find_parse_size (const char * s, find_pred * p) static
Definition at line 239 of file xrdfs_walk.c.
References s, find_pred::size_sign, and find_pred::size_val.
Referenced by find_parse_args().
find_visit()
int find_visit (const char * full, const brix_dirent * e, int depth, void * u)
Definition at line 213 of file xrdfs_walk.c.
References brix_statinfo::flags, brix_dirent::have_stat, kXR_isDir, brix_dirent::name, find_pred::name_glob, brix_statinfo::size, find_pred::size_sign, find_pred::size_val, brix_dirent::st, and find_pred::type.
Referenced by do_find().
tree_collect()
static int tree_collect (const brix_dirent * ents, size_t n, const tree_opts * o, int * keep) static
Definition at line 303 of file xrdfs_walk.c.
References tree_opts::dirs_only, brix_statinfo::flags, brix_dirent::have_stat, is_dot(), kXR_isDir, name, and brix_dirent::st.
Referenced by tree_recurse().
tree_emit()
static int tree_emit (brix_conn * c, const char * path, const char * prefix, brix_dirent * e, int last, int depth, tree_opts * o, brix_status * st) static
Definition at line 330 of file xrdfs_walk.c.
References c, brix_statinfo::flags, brix_dirent::have_stat, join_path(), kXR_isDir, brix_dirent::name, tree_opts::ndirs, tree_opts::nfiles, brix_dirent::st, tree_recurse(), XRDC_PATH_MAX, and XRDFS_MAXDEPTH.
Referenced by tree_recurse().
tree_recurse()
int tree_recurse (brix_conn * c, const char * path, const char * prefix, int depth, tree_opts * o, brix_status * st)
Definition at line 352 of file xrdfs_walk.c.
References brix_dirlist(), brix_status_set(), c, tree_opts::maxdepth, tree_collect(), tree_emit(), and XRDC_EPROTO.
Referenced by do_tree(), and tree_emit().
walk_dir()
int walk_dir (brix_conn * c, const char * path, int depth, xrdfs_visit visit, void * u, brix_status * st)
Definition at line 13 of file xrdfs_walk.c.
References brix_dirlist(), c, is_dot(), join_path(), kXR_isDir, name, walk_dir(), XRDC_PATH_MAX, and XRDFS_MAXDEPTH.
Referenced by chmod_recursive(), do_find(), du_one_path(), and walk_dir().