nginx-xrootd: client/apps/fs/xrdfs_data.c File Reference
xrdfs_data.c File Reference
#include "xrdfs_internal.h"
#include "brix_ops.h"
#include "fs/vfs.h"
Data Structures
struct dd_args_t
struct tail_args_t
struct xfer_args_t
struct tail_scan_t
struct tail_follow_t
struct wc_args_t
struct grep_scan_t
struct grep_args_t
struct xfer_io_t
Functions
int stream_file (brix_conn *c, const char *path, const char *opaque, int64_t start, int64_t limit, brix_status *st)
int do_cat (brix_conn *c, const char *cwd, int argc, char **argv)
int head_lines (brix_conn *c, const char *path, long nlines, brix_status *st)
int do_head (brix_conn *c, const char *cwd, int argc, char **argv)
void tail_sigint (int sig)
static int tail_scan_window (const uint8_t *buf, ssize_t n, int64_t base, tail_scan_t *s)
int tail_start_for_lines (brix_conn *c, const char *path, int64_t size, long nlines, int64_t *start, brix_status *st)
static int tail_follow_drain (tail_follow_t *fl, int64_t size, brix_status *st)
int tail_follow (brix_conn *c, const char *path, int64_t from, double interval, brix_status *st)
static void tail_parse_args (int argc, char **argv, tail_args_t *a)
int do_tail (brix_conn *c, const char *cwd, int argc, char **argv)
static int wc_count_stream (brix_conn *c, const char *path, long long *lines, long long *words, brix_status *st)
static void wc_parse_args (int argc, char **argv, wc_args_t *a)
int do_wc (brix_conn *c, const char *cwd, int argc, char **argv)
int slurp_file (brix_conn *c, const char *path, uint8_t **out, int64_t *len, brix_status *st)
int do_cmp (brix_conn *c, const char *cwd, int argc, char **argv)
static int grep_scan_chunk (const uint8_t *buf, ssize_t got, const regex_t *re, int numbered, grep_scan_t *g)
static int grep_parse_args (int argc, char **argv, grep_args_t *a)
int do_grep (brix_conn *c, const char *cwd, int argc, char **argv)
static void hexdump_row (const uint8_t *buf, ssize_t base, ssize_t row, int64_t abs_off)
static int hexdump_stream (brix_rfile *f, uint8_t *buf, long long limit, int64_t *off, brix_status *st)
int do_hexdump (brix_conn *c, const char *cwd, int argc, char **argv)
static int dd_parse_args (int argc, char **argv, dd_args_t *a)
int do_dd (brix_conn *c, const char *cwd, int argc, char **argv)
static int xfer_common_arg (const char *who, char **argv, int argc, int *i, xfer_args_t *x)
static int upload_copy_loop (const xfer_io_t *io, int64_t *off, brix_status *st)
static int upload_parse_args (int argc, char **argv, xfer_args_t *x)
int do_upload (brix_conn *c, const char *cwd, int argc, char **argv)
static int download_write_stdout (int fd, const uint8_t *buf, ssize_t n, const char *local)
static int download_finalize_local (brix_vfs_file *dvf, int rc, const char *local, brix_status *st)
static int download_open_local (const char *local, int force, int io_uring_mode, brix_vfs_file **dvf, brix_status *st)
static int download_default_local (const char *rpath, char *namebuf, size_t namebuf_sz, const char **local)
static int download_copy_loop (const xfer_io_t *io, int64_t *off, brix_status *st)
static int download_parse_args (int argc, char **argv, xfer_args_t *x)
int do_download (brix_conn *c, const char *cwd, int argc, char **argv)
static int readv_parse_segs (int argc, char **argv, brix_readv_seg *segs, size_t *nseg_out)
int do_readv (brix_conn *c, const char *cwd, int argc, char **argv)
static int writev_parse_seg (char **argv, int a, brix_writev_seg *segs, size_t nseg)
static int writev_parse_segs (int argc, char **argv, brix_writev_seg *segs, size_t *nseg_out)
int do_writev (brix_conn *c, const char *cwd, int argc, char **argv)
Function Documentation
dd_parse_args()
static int dd_parse_args (int argc, char ** argv, dd_args_t * a) static
Definition at line 995 of file xrdfs_data.c.
References dd_args_t::arg, dd_args_t::bs, dd_args_t::count, parse_bytes(), dd_args_t::rate, dd_args_t::skip, and XRDFS_DD_MAXBS.
Referenced by do_dd().
do_cat()
int do_cat (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 125 of file xrdfs_data.c.
References brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, stream_file(), and XRDC_PATH_MAX.
do_cmp()
int do_cmp (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 707 of file xrdfs_data.c.
References brix_query_cksum(), brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, slurp_file(), and XRDC_PATH_MAX.
do_dd()
int do_dd (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 1026 of file xrdfs_data.c.
References dd_args_t::arg, brix_rfile_close(), brix_rfile_open_read(), brix_rfile_pread(), brix_shellcode(), brix_status_clear(), brix_status_set(), dd_args_t::bs, build_path(), c, dd_args_t::count, dd_parse_args(), brix_status::msg, dd_args_t::rate, rate_pace(), dd_args_t::skip, XRDC_ESOCK, and XRDC_PATH_MAX.
do_download()
int do_download (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 1429 of file xrdfs_data.c.
References brix_rfile_close(), brix_rfile_open_read(), brix_shellcode(), brix_status_clear(), brix_vfs_abort(), brix_vfs_close(), xfer_args_t::bs, build_path(), c, download_copy_loop(), download_default_local(), download_finalize_local(), download_open_local(), download_parse_args(), xfer_args_t::force, xfer_args_t::io_uring_mode, brix_status::msg, xfer_args_t::pos1, xfer_args_t::pos2, xfer_args_t::rate, XRDC_IO_URING_AUTO, and XRDC_PATH_MAX.
do_grep()
int do_grep (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 846 of file xrdfs_data.c.
References grep_args_t::arg, brix_rfile_close(), brix_rfile_open_read(), brix_rfile_pread(), brix_shellcode(), brix_status_clear(), build_path(), c, grep_parse_args(), grep_scan_chunk(), grep_args_t::icase, grep_scan_t::line, grep_scan_t::matched, brix_status::msg, grep_args_t::numbered, grep_args_t::pattern, and XRDC_PATH_MAX.
do_head()
int do_head (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 224 of file xrdfs_data.c.
References brix_shellcode(), brix_status_clear(), build_path(), c, head_lines(), brix_status::msg, stream_file(), and XRDC_PATH_MAX.
do_hexdump()
int do_hexdump (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 949 of file xrdfs_data.c.
References brix_rfile_close(), brix_rfile_open_read(), brix_shellcode(), brix_status_clear(), build_path(), c, hexdump_stream(), brix_status::msg, and XRDC_PATH_MAX.
do_readv()
int do_readv (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 1538 of file xrdfs_data.c.
References brix_file_close(), brix_file_open_read(), brix_file_readv(), brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, readv_parse_segs(), XRDC_PATH_MAX, and XRDC_VEC_MAXSEGS.
do_tail()
int do_tail (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 522 of file xrdfs_data.c.
References tail_args_t::arg, brix_shellcode(), brix_stat(), brix_status_clear(), build_path(), c, tail_args_t::follow, tail_args_t::interval, brix_status::msg, tail_args_t::nbytes, tail_args_t::nlines, brix_statinfo::size, stream_file(), tail_follow(), tail_parse_args(), tail_start_for_lines(), and XRDC_PATH_MAX.
do_upload()
int do_upload (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 1224 of file xrdfs_data.c.
References brix_rfile_close(), brix_rfile_open_write(), brix_shellcode(), brix_status_clear(), brix_vfs_close(), brix_vfs_open(), xfer_args_t::bs, build_path(), c, brix_vfs_open_opts::cred, brix_vfs_open_opts::expected_size, xfer_args_t::force, brix_vfs_open_opts::io_uring, xfer_args_t::io_uring_mode, brix_status::msg, xfer_args_t::pos1, xfer_args_t::pos2, xfer_args_t::rate, upload_copy_loop(), upload_parse_args(), XRDC_IO_URING_AUTO, XRDC_PATH_MAX, XRDC_VFS_READ, and xrdfs_op_hints().
do_wc()
int do_wc (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 639 of file xrdfs_data.c.
References wc_args_t::arg, brix_shellcode(), brix_stat(), brix_status_clear(), build_path(), c, brix_status::msg, brix_statinfo::size, wc_args_t::want_c, wc_args_t::want_l, wc_args_t::want_w, wc_count_stream(), wc_parse_args(), and XRDC_PATH_MAX.
do_writev()
int do_writev (brix_conn * c, const char * cwd, int argc, char ** argv)
Definition at line 1644 of file xrdfs_data.c.
References brix_file_close(), brix_file_open_write(), brix_file_writev(), brix_shellcode(), brix_status_clear(), build_path(), c, brix_status::msg, writev_parse_segs(), XRDC_PATH_MAX, and XRDC_VEC_MAXSEGS.
download_copy_loop()
static int download_copy_loop (const xfer_io_t * io, int64_t * off, brix_status * st) static
Definition at line 1385 of file xrdfs_data.c.
References brix_rfile_pread(), brix_shellcode(), brix_vfs_pwrite(), xfer_io_t::bs, xfer_io_t::buf, download_write_stdout(), xfer_io_t::f, xfer_io_t::fd, xfer_io_t::is_pipe, xfer_io_t::local, brix_status::msg, xfer_io_t::rate, rate_pace(), xfer_io_t::rpath, xfer_io_t::start, and xfer_io_t::vf.
Referenced by do_download().
download_default_local()
static int download_default_local (const char * rpath, char * namebuf, size_t namebuf_sz, const char ** local) static
Definition at line 1366 of file xrdfs_data.c.
Referenced by do_download().
download_finalize_local()
static int download_finalize_local (brix_vfs_file * dvf, int rc, const char * local, brix_status * st) static
Definition at line 1328 of file xrdfs_data.c.
References brix_vfs_abort(), brix_vfs_close(), brix_vfs_commit(), and brix_status::msg.
Referenced by do_download().
download_open_local()
static int download_open_local (const char * local, int force, int io_uring_mode, brix_vfs_file ** dvf, brix_status * st) static
Definition at line 1347 of file xrdfs_data.c.
References brix_status_clear(), brix_vfs_open(), brix_vfs_open_opts::cred, brix_vfs_open_opts::expected_size, brix_vfs_open_opts::io_uring, brix_status::msg, XRDC_VFS_FORCE, and XRDC_VFS_WRITE.
Referenced by do_download().
download_parse_args()
static int download_parse_args (int argc, char ** argv, xfer_args_t * x) static
Definition at line 1413 of file xrdfs_data.c.
References xfer_args_t::pos1, xfer_args_t::pos2, and xfer_common_arg().
Referenced by do_download().
download_write_stdout()
static int download_write_stdout (int fd, const uint8_t * buf, ssize_t n, const char * local) static
Definition at line 1307 of file xrdfs_data.c.
Referenced by download_copy_loop().
grep_parse_args()
static int grep_parse_args (int argc, char ** argv, grep_args_t * a) static
Definition at line 824 of file xrdfs_data.c.
References grep_args_t::arg, grep_args_t::icase, grep_args_t::numbered, and grep_args_t::pattern.
Referenced by do_grep().
grep_scan_chunk()
static int grep_scan_chunk (const uint8_t * buf, ssize_t got, const regex_t * re, int numbered, grep_scan_t * g) static
Definition at line 778 of file xrdfs_data.c.
References grep_scan_t::lcap, grep_scan_t::line, grep_scan_t::lineno, grep_scan_t::llen, and grep_scan_t::matched.
Referenced by do_grep().
head_lines()
int head_lines (brix_conn * c, const char * path, long nlines, brix_status * st)
Definition at line 174 of file xrdfs_data.c.
References brix_rfile_close(), brix_rfile_open_read(), brix_rfile_pread(), brix_status_clear(), brix_status_set(), c, emit(), XRDC_EPROTO, and XRDC_ESOCK.
Referenced by do_head().
hexdump_row()
static void hexdump_row (const uint8_t * buf, ssize_t base, ssize_t row, int64_t abs_off) static
Definition at line 902 of file xrdfs_data.c.
Referenced by hexdump_stream().
hexdump_stream()
static int hexdump_stream (brix_rfile * f, uint8_t * buf, long long limit, int64_t * off, brix_status * st) static
Definition at line 922 of file xrdfs_data.c.
References brix_rfile_pread(), and hexdump_row().
Referenced by do_hexdump().
readv_parse_segs()
static int readv_parse_segs (int argc, char ** argv, brix_readv_seg * segs, size_t * nseg_out) static
Definition at line 1504 of file xrdfs_data.c.
References brix_readv_seg::buf, brix_readv_seg::got, brix_readv_seg::len, brix_readv_seg::offset, parse_u64_strict(), and XRDC_VEC_MAXSEGS.
Referenced by do_readv().
slurp_file()
int slurp_file (brix_conn * c, const char * path, uint8_t ** out, int64_t * len, brix_status * st)
Definition at line 674 of file xrdfs_data.c.
References brix_rfile_close(), brix_rfile_open_read(), brix_rfile_pread(), brix_stat(), brix_status_set(), c, brix_statinfo::size, and XRDC_EPROTO.
Referenced by do_cmp().
stream_file()
int stream_file (brix_conn * c, const char * path, const char * opaque, int64_t start, int64_t limit, brix_status * st)
Definition at line 61 of file xrdfs_data.c.
References brix_rfile_close(), brix_rfile_open_read(), brix_rfile_pread(), brix_status_clear(), brix_status_set(), c, XRDC_EPROTO, and XRDC_ESOCK.
Referenced by do_cat(), do_head(), and do_tail().
tail_follow()
int tail_follow (brix_conn * c, const char * path, int64_t from, double interval, brix_status * st)
Definition at line 416 of file xrdfs_data.c.
References brix_mono_ns(), brix_reconnect_home(), brix_resilient_window_ms(), brix_rfile_close(), brix_rfile_open_read(), brix_stat(), brix_status_clear(), brix_status_retryable(), brix_status_set(), tail_follow_t::buf, tail_follow_t::c, c, tail_follow_t::off, tail_follow_t::path, tail_follow_t::rf, tail_follow_t::rf_open, brix_statinfo::size, tail_follow_drain(), tail_sigint(), tail_stop, and XRDC_EPROTO.
Referenced by do_tail().
tail_follow_drain()
static int tail_follow_drain (tail_follow_t * fl, int64_t size, brix_status * st) static
Definition at line 386 of file xrdfs_data.c.
References brix_rfile_close(), brix_rfile_open_read(), brix_rfile_pread(), brix_status_clear(), tail_follow_t::buf, tail_follow_t::c, tail_follow_t::off, tail_follow_t::path, tail_follow_t::rf, and tail_follow_t::rf_open.
Referenced by tail_follow().
tail_parse_args()
static void tail_parse_args (int argc, char ** argv, tail_args_t * a) static
Definition at line 502 of file xrdfs_data.c.
References tail_args_t::arg, tail_args_t::follow, tail_args_t::interval, tail_args_t::nbytes, and tail_args_t::nlines.
Referenced by do_tail().
tail_scan_window()
static int tail_scan_window (const uint8_t * buf, ssize_t n, int64_t base, tail_scan_t * s) static
Definition at line 290 of file xrdfs_data.c.
References s.
Referenced by tail_start_for_lines().
tail_sigint()
void tail_sigint (int sig)
Definition at line 266 of file xrdfs_data.c.
References tail_stop.
Referenced by tail_follow().
tail_start_for_lines()
int tail_start_for_lines (brix_conn * c, const char * path, int64_t size, long nlines, int64_t * start, brix_status * st)
Definition at line 312 of file xrdfs_data.c.
References brix_rfile_close(), brix_rfile_open_read(), brix_rfile_pread(), brix_status_clear(), brix_status_set(), c, tail_scan_t::start, tail_scan_window(), and XRDC_EPROTO.
Referenced by do_tail().
upload_copy_loop()
static int upload_copy_loop (const xfer_io_t * io, int64_t * off, brix_status * st) static
Definition at line 1180 of file xrdfs_data.c.
References brix_rfile_pwrite(), brix_shellcode(), brix_vfs_pread(), xfer_io_t::bs, xfer_io_t::buf, xfer_io_t::f, xfer_io_t::fd, xfer_io_t::is_pipe, xfer_io_t::local, brix_status::msg, xfer_io_t::rate, rate_pace(), read(), xfer_io_t::rpath, xfer_io_t::start, and xfer_io_t::vf.
Referenced by do_upload().
upload_parse_args()
static int upload_parse_args (int argc, char ** argv, xfer_args_t * x) static
Definition at line 1208 of file xrdfs_data.c.
References xfer_args_t::pos1, xfer_args_t::pos2, and xfer_common_arg().
Referenced by do_upload().
wc_count_stream()
static int wc_count_stream (brix_conn * c, const char * path, long long * lines, long long * words, brix_status * st) static
Definition at line 570 of file xrdfs_data.c.
References brix_rfile_close(), brix_rfile_open_read(), brix_rfile_pread(), brix_shellcode(), c, and brix_status::msg.
Referenced by do_wc().
wc_parse_args()
static void wc_parse_args (int argc, char ** argv, wc_args_t * a) static
Definition at line 622 of file xrdfs_data.c.
References wc_args_t::arg, wc_args_t::want_c, wc_args_t::want_l, and wc_args_t::want_w.
Referenced by do_wc().
writev_parse_seg()
static int writev_parse_seg (char ** argv, int a, brix_writev_seg * segs, size_t nseg) static
Definition at line 1581 of file xrdfs_data.c.
References brix_writev_seg::data, hex(), brix_writev_seg::len, brix_writev_seg::offset, and parse_u64_strict().
Referenced by writev_parse_segs().
writev_parse_segs()
static int writev_parse_segs (int argc, char ** argv, brix_writev_seg * segs, size_t * nseg_out) static
Definition at line 1622 of file xrdfs_data.c.
References writev_parse_seg(), and XRDC_VEC_MAXSEGS.
Referenced by do_writev().
xfer_common_arg()
static int xfer_common_arg (const char * who, char ** argv, int argc, int * i, xfer_args_t * x) static
Definition at line 1104 of file xrdfs_data.c.
References brix_cli_parse_io_uring(), xfer_args_t::bs, xfer_args_t::force, xfer_args_t::io_uring_mode, parse_bytes(), xfer_args_t::rate, and XRDFS_DD_MAXBS.
Referenced by download_parse_args(), and upload_parse_args().