nginx-xrootd: client/apps/auth/xrdgsiproxy.c File Reference
xrdgsiproxy.c File Reference
#include "brix.h"
#include "core/compat/crypto.h"
#include "core/version.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct arg_cursor
Typedefs
typedef int(* cmd_fn) (int argc, char **argv, brix_status *st)
Functions
static int parse_valid (const char *s)
static void usage_fp (FILE *out)
static void usage (void)
static int opt_take_value (arg_cursor *ac, const char *short_name, const char *long_name, const char **out)
static int init_parse_opts (int argc, char **argv, brix_proxy_opts *o)
static int cmd_init (int argc, char **argv, brix_status *st)
static int file_parse_opts (int argc, char **argv, const char **file)
static int cmd_info (int argc, char **argv, brix_status *st)
static int cmd_destroy (int argc, char **argv, brix_status *st)
static cmd_fn cmd_lookup (const char *cmd)
int main (int argc, char **argv)
Variables
struct {
const char * name
cmd_fn fn
} cmd_table []
Typedef Documentation
cmd_fn
typedef int(* cmd_fn) (int argc, char **argv, brix_status *st)
Definition at line 216 of file xrdgsiproxy.c.
Function Documentation
cmd_destroy()
static int cmd_destroy (int argc, char ** argv, brix_status * st) static
Definition at line 198 of file xrdgsiproxy.c.
References brix_proxy_destroy(), brix_shellcode(), file_parse_opts(), brix_status::msg, and usage().
cmd_info()
static int cmd_info (int argc, char ** argv, brix_status * st) static
Definition at line 170 of file xrdgsiproxy.c.
References brix_proxy_info(), brix_shellcode(), file_parse_opts(), brix_status::kxr, brix_status::msg, usage(), and XRDC_ENOENT.
cmd_init()
static int cmd_init (int argc, char ** argv, brix_status * st) static
Definition at line 125 of file xrdgsiproxy.c.
References brix_proxy_create(), brix_proxy_info(), brix_shellcode(), init_parse_opts(), brix_status::msg, brix_proxy_opts::out_path, and usage().
cmd_lookup()
static cmd_fn cmd_lookup (const char * cmd) static
Definition at line 233 of file xrdgsiproxy.c.
References cmd_table, and name.
Referenced by main().
file_parse_opts()
static int file_parse_opts (int argc, char ** argv, const char ** file) static
Definition at line 149 of file xrdgsiproxy.c.
References arg_cursor::i, and opt_take_value().
Referenced by cmd_destroy(), and cmd_info().
init_parse_opts()
static int init_parse_opts (int argc, char ** argv, brix_proxy_opts * o) static
Definition at line 91 of file xrdgsiproxy.c.
References brix_proxy_opts::bits, arg_cursor::i, opt_take_value(), brix_proxy_opts::out_path, parse_valid(), brix_proxy_opts::user_cert, brix_proxy_opts::user_key, and brix_proxy_opts::valid_hours.
Referenced by cmd_init().
main()
int main (int argc, char ** argv)
Definition at line 246 of file xrdgsiproxy.c.
References brix_client_version(), brix_crypto_init(), brix_status_clear(), cmd_lookup(), fn, usage(), and usage_fp().
opt_take_value()
static int opt_take_value (arg_cursor * ac, const char * short_name, const char * long_name, const char ** out) static
Definition at line 68 of file xrdgsiproxy.c.
References arg_cursor::argc, arg_cursor::argv, and arg_cursor::i.
Referenced by file_parse_opts(), and init_parse_opts().
parse_valid()
static int parse_valid (const char * s) static
Definition at line 20 of file xrdgsiproxy.c.
References s.
Referenced by init_parse_opts().
usage()
static void usage (void) static
Definition at line 46 of file xrdgsiproxy.c.
References usage_fp().
Referenced by bench_parse_args(), bench_validate_args(), brix_cache_evict_if_needed(), brix_cache_fs_usage(), brix_cache_purge_setup(), brix_cache_purge_to_target(), brix_cache_usage_measure(), brix_cache_watermark_purge(), brix_wt_stage_admit(), ckv_parse_args(), cmd_destroy(), cmd_info(), cmd_init(), cmd_scan(), main(), srr_share_usage(), and verify_parse_args().
usage_fp()
static void usage_fp (FILE * out) static
Definition at line 34 of file xrdgsiproxy.c.
References BRIX_USAGE_FOOTER.
Referenced by main(), and usage().
Variable Documentation
[struct]
const struct { ... } cmd_table[]
Initial value:
= {
    { "init",    cmd_init    },
    { "info",    cmd_info    },
    { "destroy", cmd_destroy },
}
Referenced by cmd_lookup().
fn
cmd_fn fn
Definition at line 220 of file xrdgsiproxy.c.
Referenced by main().
name
const char* name
Definition at line 219 of file xrdgsiproxy.c.
Referenced by cmd_lookup().