nginx-xrootd: src/protocols/webdav/xrdhttp_stats.c File Reference
xrdhttp_stats.c File Reference
#include "xrdhttp.h"
#include "webdav.h"
#include "core/ident.h"
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <sys/socket.h>
#include <netinet/in.h>
Macros
#define XRDHTTP_STATS_BUF_MAX 4096
Functions
static int build_stats_xml (char *buf, size_t bufsz, ngx_http_request_t *r)
ngx_int_t xrdhttp_handle_stats_query (ngx_http_request_t *r)
Macro Definition Documentation
XRDHTTP_STATS_BUF_MAX
#define XRDHTTP_STATS_BUF_MAX 4096
Definition at line 38 of file xrdhttp_stats.c.
Function Documentation
build_stats_xml()
static int build_stats_xml (char * buf, size_t bufsz, ngx_http_request_t * r) static
Definition at line 46 of file xrdhttp_stats.c.
References ngx_brix_webdav_metrics_t::auth_total, BRIX_HTTP_STATUS_5XX, brix_metrics_shared(), BRIX_SERVER_NAME, BRIX_SERVER_VERSION, BRIX_WEBDAV_AUTH_RESULT_ANONYMOUS, BRIX_WEBDAV_AUTH_RESULT_CERT_OK, BRIX_WEBDAV_AUTH_RESULT_REJECTED, BRIX_WEBDAV_AUTH_RESULT_TOKEN_OK, BRIX_WEBDAV_METHOD_DELETE, BRIX_WEBDAV_METHOD_GET, BRIX_WEBDAV_METHOD_HEAD, BRIX_WEBDAV_METHOD_PUT, BRIX_WEBDAV_NMETHODS, BRIX_WEBDAV_RANGE_PARTIAL, BRIX_WEBDAV_TPC_PULL_STARTED, BRIX_WEBDAV_TPC_PUSH_STARTED, ngx_brix_webdav_metrics_t::bytes_rx_total, ngx_brix_webdav_metrics_t::bytes_tx_total, ngx_brix_webdav_metrics_t::range_total, ngx_brix_webdav_metrics_t::requests_total, ngx_brix_webdav_metrics_t::responses_total, ngx_brix_webdav_metrics_t::tpc_total, and ngx_brix_metrics_t::webdav.
Referenced by xrdhttp_handle_stats_query().
xrdhttp_handle_stats_query()
ngx_int_t xrdhttp_handle_stats_query (ngx_http_request_t * r)
Definition at line 213 of file xrdhttp_stats.c.
References build_stats_xml(), ngx_memcpy, xrdhttp_add_response_headers(), and XRDHTTP_STATS_BUF_MAX.
Referenced by webdav_dispatch_core_method().