nginx-xrootd: src/protocols/webdav/xrdhttp_response.c File Reference
xrdhttp_response.c File Reference
#include "xrdhttp.h"
#include "webdav.h"
#include "protocols/root/protocol/opcodes.h"
#include "core/compat/integrity_info.h"
#include "core/compat/net_target.h"
#include "core/compat/checksum.h"
#include "core/http/http_headers.h"
#include "core/http/http_query.h"
#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include <zlib.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
#include "core/compat/alloc_guard.h"
Data Structures
struct xrdhttp_status_map_row_t
Functions
static int xrdhttp_status_class_default (ngx_int_t http_status)
int xrdhttp_http_to_xrd_status (ngx_int_t http_status)
ngx_int_t xrdhttp_add_response_headers (ngx_http_request_t *r, ngx_int_t http_status)
static const char * xrdhttp_build_redirect_location (ngx_http_request_t *r, const xrdhttp_req_ctx_t *ctx, const char *location_url, char *loc_buf, size_t loc_bufsz)
static ngx_int_t xrdhttp_set_location_header (ngx_http_request_t *r, const char *location_url)
static ngx_int_t xrdhttp_set_redir_target_headers (ngx_http_request_t *r, const char *redir_host, int redir_port)
ngx_int_t xrdhttp_send_redirect (ngx_http_request_t *r, const char *location_url, const char *redir_host, int redir_port)
static int xrdhttp_args_has_key (const ngx_str_t *args, const char *key, size_t key_len)
int xrdhttp_request_is_stats_query (ngx_http_request_t *r)
int xrdhttp_request_is_multirange (ngx_http_request_t *r)
Variables
ngx_module_t ngx_http_brix_webdav_module
static const xrdhttp_status_map_row_t xrdhttp_status_map []
Function Documentation
xrdhttp_add_response_headers()
ngx_int_t xrdhttp_add_response_headers (ngx_http_request_t * r, ngx_int_t http_status)
Definition at line 116 of file xrdhttp_response.c.
References brix_http_set_header(), brix_http_set_header_num(), xrdhttp_req_ctx_t::headers_injected, xrdhttp_req_ctx_t::is_xrdhttp, ngx_http_brix_webdav_module, xrdhttp_req_ctx_t::requuid, xrdhttp_req_ctx_t::retry_seconds, xrdhttp_req_ctx_t::wait_seconds, and xrdhttp_http_to_xrd_status().
Referenced by get_open_map_error(), webdav_get_add_xrdhttp_headers(), xrdhttp_handle_multipart_get(), xrdhttp_handle_stats_query(), xrdhttp_header_filter(), and xrdhttp_send_redirect().
xrdhttp_args_has_key()
static int xrdhttp_args_has_key (const ngx_str_t * args, const char * key, size_t key_len) static
Definition at line 323 of file xrdhttp_response.c.
References BRIX_HTTP_QUERY_CASE_INSENSITIVE, brix_http_query_has(), BRIX_HTTP_QUERY_HAS_VALUE_OK, and key.
Referenced by xrdhttp_request_is_stats_query().
xrdhttp_build_redirect_location()
static const char * xrdhttp_build_redirect_location (ngx_http_request_t * r, const xrdhttp_req_ctx_t * ctx, const char * location_url, char * loc_buf, size_t loc_bufsz) static
Definition at line 184 of file xrdhttp_response.c.
References xrdhttp_req_ctx_t::opaque, and xrdhttp_req_ctx_t::tpc_key.
Referenced by xrdhttp_send_redirect().
xrdhttp_http_to_xrd_status()
int xrdhttp_http_to_xrd_status (ngx_int_t http_status)
Definition at line 96 of file xrdhttp_response.c.
References kXR_ok, xrdhttp_status_map_row_t::xrd_code, xrdhttp_status_class_default(), and xrdhttp_status_map.
Referenced by xrdhttp_add_response_headers().
xrdhttp_request_is_multirange()
int xrdhttp_request_is_multirange (ngx_http_request_t * r)
Definition at line 345 of file xrdhttp_response.c.
Referenced by webdav_handle_get().
xrdhttp_request_is_stats_query()
int xrdhttp_request_is_stats_query (ngx_http_request_t * r)
Definition at line 334 of file xrdhttp_response.c.
References xrdhttp_args_has_key().
Referenced by webdav_dispatch_core_method().
xrdhttp_send_redirect()
ngx_int_t xrdhttp_send_redirect (ngx_http_request_t * r, const char * location_url, const char * redir_host, int redir_port)
Definition at line 279 of file xrdhttp_response.c.
References ngx_http_brix_webdav_module, xrdhttp_add_response_headers(), xrdhttp_build_redirect_location(), XRDHTTP_OPAQUE_MAX, xrdhttp_set_location_header(), xrdhttp_set_redir_target_headers(), and XRDHTTP_TPC_URL_MAX.
xrdhttp_set_location_header()
static ngx_int_t xrdhttp_set_location_header (ngx_http_request_t * r, const char * location_url) static
Definition at line 229 of file xrdhttp_response.c.
Referenced by xrdhttp_send_redirect().
xrdhttp_set_redir_target_headers()
static ngx_int_t xrdhttp_set_redir_target_headers (ngx_http_request_t * r, const char * redir_host, int redir_port) static
Definition at line 257 of file xrdhttp_response.c.
References brix_http_set_header(), and brix_http_set_header_num().
Referenced by xrdhttp_send_redirect().
xrdhttp_status_class_default()
static int xrdhttp_status_class_default (ngx_int_t http_status) static
Definition at line 84 of file xrdhttp_response.c.
References kXR_ArgInvalid, kXR_ok, and kXR_ServerError.
Referenced by xrdhttp_http_to_xrd_status().
Variable Documentation
ngx_http_brix_webdav_module
ngx_module_t ngx_http_brix_webdav_module extern
Definition at line 10 of file module.c.
Referenced by xrdhttp_add_response_headers(), and xrdhttp_send_redirect().
xrdhttp_status_map
const xrdhttp_status_map_row_t xrdhttp_status_map[] static
Initial value:
= {
    { NGX_HTTP_BAD_REQUEST,              3000      },
    { NGX_HTTP_UNAUTHORIZED,             3010   },
    { NGX_HTTP_FORBIDDEN,                3010   },
    { NGX_HTTP_NOT_FOUND,                3011        },
    { NGX_HTTP_NOT_ALLOWED,             3013     },
    { NGX_HTTP_CONFLICT,                3005         },
    { NGX_HTTP_LENGTH_REQUIRED,         3001      },
    { 423 ,                 3003      },
    { NGX_HTTP_REQUEST_URI_TOO_LARGE,   3002      },
    { NGX_HTTP_RANGE_NOT_SATISFIABLE,   3000      },
    { NGX_HTTP_INTERNAL_SERVER_ERROR,   3012     },
    { NGX_HTTP_NOT_IMPLEMENTED,         3013     },
    { NGX_HTTP_BAD_GATEWAY,             3005         },
    { NGX_HTTP_SERVICE_UNAVAILABLE,     3033     },
    { NGX_HTTP_INSUFFICIENT_STORAGE,    3009         },
}
Definition at line 58 of file xrdhttp_response.c.
Referenced by xrdhttp_http_to_xrd_status().