nginx-xrootd: src/protocols/webdav/xrdhttp_multipart.c File Reference
xrdhttp_multipart.c File Reference
#include "xrdhttp.h"
#include "webdav.h"
#include "core/http/http_file_response.h"
#include "core/compat/range_vector.h"
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include "core/compat/alloc_guard.h"
Data Structures
struct mp_ctx_t
Macros
#define XRDHTTP_BOUNDARY "xrdhttp_boundary_42"
Functions
static ngx_int_t chain_append_text (ngx_http_request_t *r, ngx_chain_t **tail, const char *text, ngx_chain_t **new_link_out)
static int mp_format_part_header (char *buf, size_t buf_size, const brix_byte_range_t *range, off_t file_size)
static ngx_int_t mp_compute_content_length (const mp_ctx_t *ctx, const brix_byte_range_t *ranges, ngx_uint_t nranges, off_t *total_out)
static ngx_int_t mp_append_part (const mp_ctx_t *ctx, ngx_chain_t **head, ngx_chain_t **tail, const brix_byte_range_t *range)
static ngx_int_t mp_build_chain (const mp_ctx_t *ctx, const brix_byte_range_t *ranges, ngx_uint_t nranges, ngx_chain_t **head_out)
static ngx_int_t mp_set_response_headers (ngx_http_request_t *r, off_t total_len)
static void mp_account_metrics (ngx_http_request_t *r, const brix_byte_range_t *ranges, ngx_uint_t nranges)
static void mp_resolve_path (ngx_http_request_t *r, char *path, size_t path_size)
ngx_int_t xrdhttp_handle_multipart_get (ngx_http_request_t *r, ngx_fd_t fd, const struct stat *sb, int fd_from_table)
Macro Definition Documentation
XRDHTTP_BOUNDARY
#define XRDHTTP_BOUNDARY "xrdhttp_boundary_42"
Definition at line 44 of file xrdhttp_multipart.c.
Function Documentation
chain_append_text()
static ngx_int_t chain_append_text (ngx_http_request_t * r, ngx_chain_t ** tail, const char * text, ngx_chain_t ** new_link_out) static
Definition at line 71 of file xrdhttp_multipart.c.
References BRIX_PCALLOC_OR_RETURN, ngx_memcpy, and ngx_pnalloc().
Referenced by mp_append_part(), and mp_build_chain().
mp_account_metrics()
static void mp_account_metrics (ngx_http_request_t * r, const brix_byte_range_t * ranges, ngx_uint_t nranges) static
Definition at line 304 of file xrdhttp_multipart.c.
References BRIX_WEBDAV_METRIC_ADD, brix_byte_range_t::end, and brix_byte_range_t::start.
Referenced by xrdhttp_handle_multipart_get().
mp_append_part()
static ngx_int_t mp_append_part (const mp_ctx_t * ctx, ngx_chain_t ** head, ngx_chain_t ** tail, const brix_byte_range_t * range) static
Definition at line 177 of file xrdhttp_multipart.c.
References brix_http_chain_append_file_range(), chain_append_text(), brix_byte_range_t::end, mp_ctx_t::fd, mp_ctx_t::fd_from_table, mp_ctx_t::file_size, mp_format_part_header(), mp_ctx_t::path, mp_ctx_t::r, mp_ctx_t::scratch, mp_ctx_t::scratch_size, and brix_byte_range_t::start.
Referenced by mp_build_chain().
mp_build_chain()
static ngx_int_t mp_build_chain (const mp_ctx_t * ctx, const brix_byte_range_t * ranges, ngx_uint_t nranges, ngx_chain_t ** head_out) static
Definition at line 225 of file xrdhttp_multipart.c.
References chain_append_text(), mp_append_part(), mp_ctx_t::r, and XRDHTTP_BOUNDARY.
Referenced by xrdhttp_handle_multipart_get().
mp_compute_content_length()
static ngx_int_t mp_compute_content_length (const mp_ctx_t * ctx, const brix_byte_range_t * ranges, ngx_uint_t nranges, off_t * total_out) static
Definition at line 142 of file xrdhttp_multipart.c.
References brix_byte_range_t::end, mp_ctx_t::file_size, mp_format_part_header(), mp_ctx_t::scratch, mp_ctx_t::scratch_size, brix_byte_range_t::start, and XRDHTTP_BOUNDARY.
Referenced by xrdhttp_handle_multipart_get().
mp_format_part_header()
static int mp_format_part_header (char * buf, size_t buf_size, const brix_byte_range_t * range, off_t file_size) static
Definition at line 117 of file xrdhttp_multipart.c.
References brix_byte_range_t::end, brix_byte_range_t::start, and XRDHTTP_BOUNDARY.
Referenced by mp_append_part(), and mp_compute_content_length().
mp_resolve_path()
static void mp_resolve_path (ngx_http_request_t * r, char * path, size_t path_size) static
Definition at line 332 of file xrdhttp_multipart.c.
Referenced by xrdhttp_handle_multipart_get().
mp_set_response_headers()
static ngx_int_t mp_set_response_headers (ngx_http_request_t * r, off_t total_len) static
Definition at line 269 of file xrdhttp_multipart.c.
References XRDHTTP_BOUNDARY.
Referenced by xrdhttp_handle_multipart_get().
xrdhttp_handle_multipart_get()
ngx_int_t xrdhttp_handle_multipart_get (ngx_http_request_t * r, ngx_fd_t fd, const struct stat * sb, int fd_from_table)
Definition at line 343 of file xrdhttp_multipart.c.
References brix_range_vector_opts_t::allow_open_ended, brix_range_vector_opts_t::allow_suffix, brix_http_parse_range_vector(), brix_range_vector_opts_t::drop_unsatisfiable, brix_range_vector_opts_t::max_ranges, mp_account_metrics(), mp_build_chain(), mp_compute_content_length(), mp_resolve_path(), mp_set_response_headers(), mp_ctx_t::r, WEBDAV_MAX_PATH, xrdhttp_add_response_headers(), and XRDHTTP_MAX_RANGES.
Referenced by get_serve_range().