nginx-xrootd: src/protocols/webdav/xrdhttp.c File Reference
xrdhttp.c File Reference
#include "xrdhttp.h"
#include "webdav.h"
#include "protocols/root/protocol/opcodes.h"
#include "core/compat/integrity_info.h"
#include "core/compat/net_target.h"
#include "core/compat/checksum.h"
#include "core/http/http_headers.h"
#include "core/http/http_query.h"
#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include <zlib.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
#include "core/compat/alloc_guard.h"
Functions
xrdhttp_req_ctx_t * xrdhttp_get_ctx (ngx_http_request_t *r)
static int xrdhttp_args_get (const ngx_str_t *args, const char *key, size_t key_len, char *dst, size_t dstsz)
static int xrdhttp_args_has_key (const ngx_str_t *args, const char *key, size_t key_len)
static void xrdhttp_normalize_rfc3230_algo (const u_char *value, size_t vlen, char *dst, size_t dstsz)
void xrdhttp_parse_request (ngx_http_request_t *r)
int xrdhttp_http_to_xrd_status (ngx_int_t http_status)
ngx_int_t xrdhttp_add_response_headers (ngx_http_request_t *r, ngx_int_t http_status)
ngx_int_t xrdhttp_send_redirect (ngx_http_request_t *r, const char *location_url, const char *redir_host, int redir_port)
int xrdhttp_request_is_stats_query (ngx_http_request_t *r)
int xrdhttp_request_is_multirange (ngx_http_request_t *r)
ngx_int_t xrdhttp_inject_tpc_headers (ngx_http_request_t *r)
ngx_int_t xrdhttp_add_checksum_header (ngx_http_request_t *r, ngx_fd_t fd, const struct stat *sb)
ngx_int_t xrdhttp_digest_body_filter (ngx_http_request_t *r, ngx_chain_t *in, ngx_http_output_body_filter_pt next)
Variables
ngx_module_t ngx_http_brix_webdav_module
Function Documentation
xrdhttp_add_checksum_header()
ngx_int_t xrdhttp_add_checksum_header (ngx_http_request_t * r, ngx_fd_t fd, const struct stat * sb)
Definition at line 573 of file xrdhttp.c.
References brix_integrity_opts_t::allow_xattr_cache, brix_checksum_parse(), brix_http_set_header(), brix_integrity_format_http_digest(), brix_integrity_get_fd(), brix_sanitize_log_string(), ngx_http_brix_webdav_module, brix_integrity_opts_t::update_xattr_cache, and xrdhttp_req_ctx_t::want_cksum.
Referenced by webdav_get_add_xrdhttp_headers(), and webdav_handle_head().
xrdhttp_add_response_headers()
ngx_int_t xrdhttp_add_response_headers (ngx_http_request_t * r, ngx_int_t http_status)
Definition at line 300 of file xrdhttp.c.
References brix_http_set_header(), brix_http_set_header_num(), xrdhttp_req_ctx_t::headers_injected, xrdhttp_req_ctx_t::is_xrdhttp, ngx_http_brix_webdav_module, xrdhttp_req_ctx_t::requuid, xrdhttp_req_ctx_t::retry_seconds, xrdhttp_req_ctx_t::wait_seconds, and xrdhttp_http_to_xrd_status().
Referenced by webdav_get_add_xrdhttp_headers(), webdav_handle_get(), xrdhttp_handle_multipart_get(), xrdhttp_handle_stats_query(), xrdhttp_header_filter(), and xrdhttp_send_redirect().
xrdhttp_args_get()
static int xrdhttp_args_get (const ngx_str_t * args, const char * key, size_t key_len, char * dst, size_t dstsz) static
Definition at line 77 of file xrdhttp.c.
References BRIX_HTTP_QUERY_ALLOW_EMPTY, BRIX_HTTP_QUERY_CASE_INSENSITIVE, BRIX_HTTP_QUERY_DECODE_VALUE, brix_http_query_get(), BRIX_HTTP_QUERY_PLUS_TO_SPACE, BRIX_HTTP_QUERY_REJECT_NUL, BRIX_HTTP_QUERY_TRUNCATE, and key.
Referenced by xrdhttp_parse_request().
xrdhttp_args_has_key()
static int xrdhttp_args_has_key (const ngx_str_t * args, const char * key, size_t key_len) static
Definition at line 96 of file xrdhttp.c.
References BRIX_HTTP_QUERY_CASE_INSENSITIVE, brix_http_query_has(), BRIX_HTTP_QUERY_HAS_VALUE_OK, and key.
Referenced by xrdhttp_request_is_stats_query().
xrdhttp_digest_body_filter()
ngx_int_t xrdhttp_digest_body_filter (ngx_http_request_t * r, ngx_chain_t * in, ngx_http_output_body_filter_pt next)
Definition at line 628 of file xrdhttp.c.
References xrdhttp_req_ctx_t::adler, xrdhttp_req_ctx_t::compute_digest, xrdhttp_req_ctx_t::digest_emitted, xrdhttp_req_ctx_t::is_xrdhttp, and ngx_http_brix_webdav_module.
Referenced by xrdhttp_body_filter().
xrdhttp_get_ctx()
xrdhttp_req_ctx_t * xrdhttp_get_ctx (ngx_http_request_t * r)
Definition at line 51 of file xrdhttp.c.
References BRIX_PCALLOC_OR_RETURN, ngx_http_brix_webdav_module, and ngx_http_brix_webdav_req_ctx_t::xrdhttp.
Referenced by webdav_handle_head(), and xrdhttp_parse_request().
xrdhttp_http_to_xrd_status()
int xrdhttp_http_to_xrd_status (ngx_int_t http_status)
Definition at line 266 of file xrdhttp.c.
References kXR_ArgInvalid, kXR_ArgMissing, kXR_ArgTooLong, kXR_FileLocked, kXR_FSError, kXR_NoSpace, kXR_NotAuthorized, kXR_NotFound, kXR_ok, kXR_ServerError, kXR_TooManyErrs, and kXR_Unsupported.
Referenced by xrdhttp_add_response_headers().
xrdhttp_inject_tpc_headers()
ngx_int_t xrdhttp_inject_tpc_headers (ngx_http_request_t * r)
Definition at line 475 of file xrdhttp.c.
References brix_http_request_header_add(), brix_net_target_parse(), ngx_http_brix_webdav_module, xrdhttp_req_ctx_t::tpc_dst, xrdhttp_req_ctx_t::tpc_src, xrdhttp_req_ctx_t::tpc_token, webdav_tpc_find_header, and XRDHTTP_TPC_KEY_MAX.
Referenced by ngx_http_brix_webdav_access_handler().
xrdhttp_normalize_rfc3230_algo()
static void xrdhttp_normalize_rfc3230_algo (const u_char * value, size_t vlen, char * dst, size_t dstsz) static
Definition at line 113 of file xrdhttp.c.
Referenced by xrdhttp_parse_request().
xrdhttp_parse_request()
void xrdhttp_parse_request (ngx_http_request_t * r)
Definition at line 146 of file xrdhttp.c.
References brix_sanitize_log_string(), xrdhttp_req_ctx_t::clnt_app, xrdhttp_req_ctx_t::clnt_uuid, xrdhttp_req_ctx_t::compute_digest, xrdhttp_req_ctx_t::is_xrdhttp, xrdhttp_req_ctx_t::opaque, xrdhttp_req_ctx_t::proto_version, xrdhttp_req_ctx_t::requuid, xrdhttp_req_ctx_t::tpc_dst, xrdhttp_req_ctx_t::tpc_key, xrdhttp_req_ctx_t::tpc_src, xrdhttp_req_ctx_t::tpc_token, xrdhttp_req_ctx_t::want_cksum, webdav_tpc_find_header, xrdhttp_args_get(), xrdhttp_get_ctx(), xrdhttp_normalize_rfc3230_algo(), XRDHTTP_TPC_KEY_MAX, and XRDHTTP_UUID_MAX.
Referenced by ngx_http_brix_webdav_access_handler().
xrdhttp_request_is_multirange()
int xrdhttp_request_is_multirange (ngx_http_request_t * r)
Definition at line 458 of file xrdhttp.c.
Referenced by webdav_handle_get().
xrdhttp_request_is_stats_query()
int xrdhttp_request_is_stats_query (ngx_http_request_t * r)
Definition at line 447 of file xrdhttp.c.
References xrdhttp_args_has_key().
Referenced by webdav_dispatch_inner().
xrdhttp_send_redirect()
ngx_int_t xrdhttp_send_redirect (ngx_http_request_t * r, const char * location_url, const char * redir_host, int redir_port)
Definition at line 357 of file xrdhttp.c.
References brix_http_set_header(), brix_http_set_header_num(), ngx_http_brix_webdav_module, xrdhttp_req_ctx_t::opaque, xrdhttp_req_ctx_t::tpc_key, xrdhttp_add_response_headers(), XRDHTTP_OPAQUE_MAX, and XRDHTTP_TPC_URL_MAX.
Variable Documentation
ngx_http_brix_webdav_module
ngx_module_t ngx_http_brix_webdav_module extern
Definition at line 548 of file module.c.
Referenced by xrdhttp_add_checksum_header(), xrdhttp_add_response_headers(), xrdhttp_digest_body_filter(), xrdhttp_get_ctx(), xrdhttp_inject_tpc_headers(), and xrdhttp_send_redirect().