nginx-xrootd: src/protocols/webdav/xrdhttp_filter.c File Reference
xrdhttp_filter.c File Reference
#include "webdav.h"
#include "xrdhttp.h"
Functions
static ngx_int_t xrdhttp_header_filter (ngx_http_request_t *r)
static ngx_int_t xrdhttp_body_filter (ngx_http_request_t *r, ngx_chain_t *in)
static ngx_int_t xrdhttp_filter_init (ngx_conf_t *cf)
Variables
static ngx_http_output_header_filter_pt ngx_http_next_header_filter
static ngx_http_output_body_filter_pt ngx_http_next_body_filter
static ngx_http_module_t ngx_http_brix_xrdhttp_filter_module_ctx
ngx_module_t ngx_http_brix_xrdhttp_filter_module
Function Documentation
xrdhttp_body_filter()
static ngx_int_t xrdhttp_body_filter (ngx_http_request_t * r, ngx_chain_t * in) static
Definition at line 45 of file xrdhttp_filter.c.
References ngx_http_next_body_filter, and xrdhttp_digest_body_filter().
Referenced by xrdhttp_filter_init().
xrdhttp_filter_init()
static ngx_int_t xrdhttp_filter_init (ngx_conf_t * cf) static
Definition at line 51 of file xrdhttp_filter.c.
References ngx_http_next_body_filter, ngx_http_next_header_filter, xrdhttp_body_filter(), and xrdhttp_header_filter().
xrdhttp_header_filter()
static ngx_int_t xrdhttp_header_filter (ngx_http_request_t * r) static
Definition at line 38 of file xrdhttp_filter.c.
References ngx_http_next_header_filter, and xrdhttp_add_response_headers().
Referenced by xrdhttp_filter_init().
Variable Documentation
ngx_http_brix_xrdhttp_filter_module
ngx_module_t ngx_http_brix_xrdhttp_filter_module
Initial value:
= {
    NGX_MODULE_V1,
    &ngx_http_brix_xrdhttp_filter_module_ctx,
    NULL,
    NGX_HTTP_MODULE,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NGX_MODULE_V1_PADDING
}
Definition at line 73 of file xrdhttp_filter.c.
ngx_http_brix_xrdhttp_filter_module_ctx
ngx_http_module_t ngx_http_brix_xrdhttp_filter_module_ctx static
Initial value:
= {
    NULL,
    xrdhttp_filter_init,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
}
Definition at line 62 of file xrdhttp_filter.c.
ngx_http_next_body_filter
ngx_http_output_body_filter_pt ngx_http_next_body_filter static
Definition at line 35 of file xrdhttp_filter.c.
Referenced by xrdhttp_body_filter(), and xrdhttp_filter_init().
ngx_http_next_header_filter
ngx_http_output_header_filter_pt ngx_http_next_header_filter static
Definition at line 34 of file xrdhttp_filter.c.
Referenced by xrdhttp_filter_init(), and xrdhttp_header_filter().