nginx-xrootd: src/protocols/webdav/xrdhttp_tpc.c File Reference
xrdhttp_tpc.c File Reference
#include "xrdhttp.h"
#include "webdav.h"
#include "protocols/root/protocol/opcodes.h"
#include "core/compat/integrity_info.h"
#include "core/compat/net_target.h"
#include "core/compat/checksum.h"
#include "core/http/http_headers.h"
#include "core/http/http_query.h"
#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include <zlib.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
#include "core/compat/alloc_guard.h"
Functions
ngx_int_t xrdhttp_inject_tpc_headers (ngx_http_request_t *r)
ngx_int_t xrdhttp_add_checksum_header (ngx_http_request_t *r, ngx_fd_t fd, const struct stat *sb)
ngx_int_t xrdhttp_digest_body_filter (ngx_http_request_t *r, ngx_chain_t *in, ngx_http_output_body_filter_pt next)
Variables
ngx_module_t ngx_http_brix_webdav_module
Function Documentation
xrdhttp_add_checksum_header()
ngx_int_t xrdhttp_add_checksum_header (ngx_http_request_t * r, ngx_fd_t fd, const struct stat * sb)
Definition at line 142 of file xrdhttp_tpc.c.
References brix_integrity_opts_t::allow_xattr_cache, brix_checksum_parse(), brix_http_set_header(), brix_integrity_format_http_digest(), brix_integrity_get_fd(), brix_sanitize_log_string(), ngx_http_brix_webdav_module, brix_integrity_opts_t::update_xattr_cache, and xrdhttp_req_ctx_t::want_cksum.
Referenced by webdav_get_add_xrdhttp_headers(), and webdav_head_emit_digest().
xrdhttp_digest_body_filter()
ngx_int_t xrdhttp_digest_body_filter (ngx_http_request_t * r, ngx_chain_t * in, ngx_http_output_body_filter_pt next)
Definition at line 197 of file xrdhttp_tpc.c.
References xrdhttp_req_ctx_t::adler, xrdhttp_req_ctx_t::compute_digest, xrdhttp_req_ctx_t::digest_emitted, xrdhttp_req_ctx_t::is_xrdhttp, ngx_http_brix_webdav_module, and ngx_pnalloc().
Referenced by xrdhttp_body_filter().
xrdhttp_inject_tpc_headers()
ngx_int_t xrdhttp_inject_tpc_headers (ngx_http_request_t * r)
Definition at line 44 of file xrdhttp_tpc.c.
References brix_http_request_header_add(), brix_net_target_parse(), ngx_http_brix_webdav_module, xrdhttp_req_ctx_t::tpc_dst, xrdhttp_req_ctx_t::tpc_src, xrdhttp_req_ctx_t::tpc_token, webdav_tpc_find_header, and XRDHTTP_TPC_KEY_MAX.
Referenced by ngx_http_brix_webdav_access_handler().
Variable Documentation
ngx_http_brix_webdav_module
ngx_module_t ngx_http_brix_webdav_module extern
Definition at line 10 of file module.c.
Referenced by xrdhttp_add_checksum_header(), xrdhttp_digest_body_filter(), and xrdhttp_inject_tpc_headers().