nginx-xrootd: src/protocols/webdav/xrdhttp.h File Reference
xrdhttp.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
#include <sys/stat.h>
Data Structures
struct xrdhttp_req_ctx_t
Macros
#define XRDHTTP_UUID_MAX 64 /* xrd.clnt.uuid / X-Xrootd-Requuid */
#define XRDHTTP_APP_MAX 64 /* xrd.clnt.app */
#define XRDHTTP_CKSUM_MAX 32 /* xrd.want.cksum algorithm name */
#define XRDHTTP_OPAQUE_MAX 512 /* xrd.opaque passthrough blob */
#define XRDHTTP_TPC_KEY_MAX 256 /* tpc.key security cookie */
#define XRDHTTP_TPC_URL_MAX 1024 /* tpc.src / tpc.dst URL */
#define XRDHTTP_PROTO_MAX 16 /* X-Xrootd-Proto version string */
#define XRDHTTP_MAX_RANGES 64
Functions
xrdhttp_req_ctx_t * xrdhttp_get_ctx (ngx_http_request_t *r)
void xrdhttp_parse_request (ngx_http_request_t *r)
ngx_int_t xrdhttp_add_response_headers (ngx_http_request_t *r, ngx_int_t http_status)
ngx_int_t xrdhttp_send_redirect (ngx_http_request_t *r, const char *location_url, const char *redir_host, int redir_port)
int xrdhttp_request_is_multirange (ngx_http_request_t *r)
ngx_int_t xrdhttp_handle_multipart_get (ngx_http_request_t *r, ngx_fd_t fd, const struct stat *sb, int fd_from_table)
int xrdhttp_request_is_stats_query (ngx_http_request_t *r)
ngx_int_t xrdhttp_handle_stats_query (ngx_http_request_t *r)
ngx_int_t xrdhttp_inject_tpc_headers (ngx_http_request_t *r)
ngx_int_t xrdhttp_add_checksum_header (ngx_http_request_t *r, ngx_fd_t fd, const struct stat *sb)
int xrdhttp_http_to_xrd_status (ngx_int_t http_status)
ngx_int_t xrdhttp_digest_body_filter (ngx_http_request_t *r, ngx_chain_t *in, ngx_http_output_body_filter_pt next)
Macro Definition Documentation
XRDHTTP_APP_MAX
#define XRDHTTP_APP_MAX 64 /* xrd.clnt.app */
Definition at line 37 of file xrdhttp.h.
XRDHTTP_CKSUM_MAX
#define XRDHTTP_CKSUM_MAX 32 /* xrd.want.cksum algorithm name */
Definition at line 38 of file xrdhttp.h.
XRDHTTP_MAX_RANGES
#define XRDHTTP_MAX_RANGES 64
Definition at line 45 of file xrdhttp.h.
XRDHTTP_OPAQUE_MAX
#define XRDHTTP_OPAQUE_MAX 512 /* xrd.opaque passthrough blob */
Definition at line 39 of file xrdhttp.h.
XRDHTTP_PROTO_MAX
#define XRDHTTP_PROTO_MAX 16 /* X-Xrootd-Proto version string */
Definition at line 42 of file xrdhttp.h.
XRDHTTP_TPC_KEY_MAX
#define XRDHTTP_TPC_KEY_MAX 256 /* tpc.key security cookie */
Definition at line 40 of file xrdhttp.h.
XRDHTTP_TPC_URL_MAX
#define XRDHTTP_TPC_URL_MAX 1024 /* tpc.src / tpc.dst URL */
Definition at line 41 of file xrdhttp.h.
XRDHTTP_UUID_MAX
#define XRDHTTP_UUID_MAX 64 /* xrd.clnt.uuid / X-Xrootd-Requuid */
Definition at line 36 of file xrdhttp.h.
Function Documentation
xrdhttp_add_checksum_header()
ngx_int_t xrdhttp_add_checksum_header (ngx_http_request_t * r, ngx_fd_t fd, const struct stat * sb)
Definition at line 573 of file xrdhttp.c.
References brix_integrity_opts_t::allow_xattr_cache, brix_checksum_parse(), brix_http_set_header(), brix_integrity_format_http_digest(), brix_integrity_get_fd(), brix_sanitize_log_string(), ngx_http_brix_webdav_module, brix_integrity_opts_t::update_xattr_cache, and xrdhttp_req_ctx_t::want_cksum.
Referenced by webdav_get_add_xrdhttp_headers(), and webdav_handle_head().
xrdhttp_add_response_headers()
ngx_int_t xrdhttp_add_response_headers (ngx_http_request_t * r, ngx_int_t http_status)
Definition at line 300 of file xrdhttp.c.
References brix_http_set_header(), brix_http_set_header_num(), xrdhttp_req_ctx_t::headers_injected, xrdhttp_req_ctx_t::is_xrdhttp, ngx_http_brix_webdav_module, xrdhttp_req_ctx_t::requuid, xrdhttp_req_ctx_t::retry_seconds, xrdhttp_req_ctx_t::wait_seconds, and xrdhttp_http_to_xrd_status().
Referenced by webdav_get_add_xrdhttp_headers(), webdav_handle_get(), xrdhttp_handle_multipart_get(), xrdhttp_handle_stats_query(), xrdhttp_header_filter(), and xrdhttp_send_redirect().
xrdhttp_digest_body_filter()
ngx_int_t xrdhttp_digest_body_filter (ngx_http_request_t * r, ngx_chain_t * in, ngx_http_output_body_filter_pt next)
Definition at line 628 of file xrdhttp.c.
References xrdhttp_req_ctx_t::adler, xrdhttp_req_ctx_t::compute_digest, xrdhttp_req_ctx_t::digest_emitted, xrdhttp_req_ctx_t::is_xrdhttp, ngx_http_brix_webdav_module, and ngx_pnalloc().
Referenced by xrdhttp_body_filter().
xrdhttp_get_ctx()
xrdhttp_req_ctx_t * xrdhttp_get_ctx (ngx_http_request_t * r)
Definition at line 51 of file xrdhttp.c.
References BRIX_PCALLOC_OR_RETURN, ngx_http_brix_webdav_module, and ngx_http_brix_webdav_req_ctx_t::xrdhttp.
Referenced by webdav_handle_head(), and xrdhttp_parse_request().
xrdhttp_handle_multipart_get()
ngx_int_t xrdhttp_handle_multipart_get (ngx_http_request_t * r, ngx_fd_t fd, const struct stat * sb, int fd_from_table)
Definition at line 88 of file xrdhttp_multipart.c.
References brix_range_vector_opts_t::allow_open_ended, brix_range_vector_opts_t::allow_suffix, brix_http_chain_append_file_range(), brix_http_parse_range_vector(), BRIX_WEBDAV_METRIC_ADD, chain_append_text(), brix_range_vector_opts_t::drop_unsatisfiable, brix_byte_range_t::end, brix_range_vector_opts_t::max_ranges, brix_byte_range_t::start, WEBDAV_MAX_PATH, xrdhttp_add_response_headers(), XRDHTTP_BOUNDARY, and XRDHTTP_MAX_RANGES.
Referenced by webdav_handle_get().
xrdhttp_handle_stats_query()
ngx_int_t xrdhttp_handle_stats_query (ngx_http_request_t * r)
Definition at line 212 of file xrdhttp_stats.c.
References build_stats_xml(), ngx_memcpy, xrdhttp_add_response_headers(), and XRDHTTP_STATS_BUF_MAX.
Referenced by webdav_dispatch_inner().
xrdhttp_http_to_xrd_status()
int xrdhttp_http_to_xrd_status (ngx_int_t http_status)
Definition at line 266 of file xrdhttp.c.
References kXR_ArgInvalid, kXR_ArgMissing, kXR_ArgTooLong, kXR_FileLocked, kXR_FSError, kXR_NoSpace, kXR_NotAuthorized, kXR_NotFound, kXR_ok, kXR_ServerError, kXR_TooManyErrs, and kXR_Unsupported.
Referenced by xrdhttp_add_response_headers().
xrdhttp_inject_tpc_headers()
ngx_int_t xrdhttp_inject_tpc_headers (ngx_http_request_t * r)
Definition at line 475 of file xrdhttp.c.
References brix_http_request_header_add(), brix_net_target_parse(), ngx_http_brix_webdav_module, xrdhttp_req_ctx_t::tpc_dst, xrdhttp_req_ctx_t::tpc_src, xrdhttp_req_ctx_t::tpc_token, webdav_tpc_find_header, and XRDHTTP_TPC_KEY_MAX.
Referenced by ngx_http_brix_webdav_access_handler().
xrdhttp_parse_request()
void xrdhttp_parse_request (ngx_http_request_t * r)
Definition at line 146 of file xrdhttp.c.
References brix_sanitize_log_string(), xrdhttp_req_ctx_t::clnt_app, xrdhttp_req_ctx_t::clnt_uuid, xrdhttp_req_ctx_t::compute_digest, xrdhttp_req_ctx_t::is_xrdhttp, ngx_memcpy, xrdhttp_req_ctx_t::opaque, xrdhttp_req_ctx_t::proto_version, xrdhttp_req_ctx_t::requuid, xrdhttp_req_ctx_t::tpc_dst, xrdhttp_req_ctx_t::tpc_key, xrdhttp_req_ctx_t::tpc_src, xrdhttp_req_ctx_t::tpc_token, xrdhttp_req_ctx_t::want_cksum, webdav_tpc_find_header, xrdhttp_args_get(), xrdhttp_get_ctx(), xrdhttp_normalize_rfc3230_algo(), XRDHTTP_TPC_KEY_MAX, and XRDHTTP_UUID_MAX.
Referenced by ngx_http_brix_webdav_access_handler().
xrdhttp_request_is_multirange()
int xrdhttp_request_is_multirange (ngx_http_request_t * r)
Definition at line 458 of file xrdhttp.c.
Referenced by webdav_handle_get().
xrdhttp_request_is_stats_query()
int xrdhttp_request_is_stats_query (ngx_http_request_t * r)
Definition at line 447 of file xrdhttp.c.
References xrdhttp_args_has_key().
Referenced by webdav_dispatch_inner().
xrdhttp_send_redirect()
ngx_int_t xrdhttp_send_redirect (ngx_http_request_t * r, const char * location_url, const char * redir_host, int redir_port)
Definition at line 357 of file xrdhttp.c.
References brix_http_set_header(), brix_http_set_header_num(), ngx_http_brix_webdav_module, xrdhttp_req_ctx_t::opaque, xrdhttp_req_ctx_t::tpc_key, xrdhttp_add_response_headers(), XRDHTTP_OPAQUE_MAX, and XRDHTTP_TPC_URL_MAX.