nginx-xrootd: client/apps/diag/xrdmapc.c File Reference
xrdmapc.c File Reference
#include "brix.h"
#include "core/compat/crypto.h"
#include "core/compat/host_split.h"
#include "core/version.h"
#include "core/progname.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
static int parse_holder (const char *tok, char *host, size_t hsz, int *port, char *rw)
static void holder_url (const brix_opts *o, const char *host, int port, char *out, size_t outsz)
static void print_space (brix_conn *c, const char *path)
static void probe_holder (const brix_opts *co, const char *path, const char *host, int port, char rw)
static int map_holder (const brix_opts *co, const char *path, const char *tok, int verify)
static void map_holders (const brix_opts *co, const char *loc, const char *path, int verify)
static int do_map (const char *url, const brix_opts *co, int verify)
static void usage_fp (FILE *out, const char *prog)
static void usage (const char *prog)
int main (int argc, char **argv)
Variables
static int g_ghosts
Function Documentation
do_map()
static int do_map (const char * url, const brix_opts * co, int verify) static
Definition at line 220 of file xrdmapc.c.
References brix_close(), brix_connect_resilient(), brix_endpoint_parse(), brix_locate(), brix_shellcode(), brix_status_clear(), c, g_ghosts, brix_url::host, map_holders(), brix_status::msg, brix_url::path, brix_url::port, and print_space().
Referenced by main().
holder_url()
static void holder_url (const brix_opts * o, const char * host, int port, char * out, size_t outsz) static
Definition at line 51 of file xrdmapc.c.
References host, port, and brix_opts::want_tls.
Referenced by probe_holder().
main()
int main (int argc, char ** argv)
Definition at line 275 of file xrdmapc.c.
References brix_crypto_init(), brix_opts_init(), brix_opts_parse_arg(), do_map(), usage(), and usage_fp().
map_holder()
static int map_holder (const brix_opts * co, const char * path, const char * tok, int verify) static
Definition at line 152 of file xrdmapc.c.
References host, parse_holder(), port, probe_holder(), and tok.
Referenced by map_holders().
map_holders()
static void map_holders (const brix_opts * co, const char * loc, const char * path, int verify) static
Definition at line 186 of file xrdmapc.c.
References g_ghosts, map_holder(), and tok.
Referenced by do_map().
parse_holder()
static int parse_holder (const char * tok, char * host, size_t hsz, int * port, char * rw) static
Definition at line 35 of file xrdmapc.c.
References brix_split_host_port(), host, port, and tok.
Referenced by map_holder().
print_space()
static void print_space (brix_conn * c, const char * path) static
Definition at line 72 of file xrdmapc.c.
References brix_query(), brix_status_clear(), c, and kXR_Qspace.
Referenced by do_map().
probe_holder()
static void probe_holder (const brix_opts * co, const char * path, const char * host, int port, char rw) static
Definition at line 102 of file xrdmapc.c.
References brix_close(), brix_connect(), brix_endpoint_parse(), brix_kxr_name(), brix_stat(), brix_status_clear(), g_ghosts, holder_url(), host, brix_status::kxr, brix_status::msg, port, and brix_statinfo::size.
Referenced by map_holder().
usage()
static void usage (const char * prog) static
Definition at line 269 of file xrdmapc.c.
References usage_fp().
usage_fp()
static void usage_fp (FILE * out, const char * prog) static
Definition at line 255 of file xrdmapc.c.
References brix_prog_base(), and brix_usage_footer().
Referenced by main(), and usage().
Variable Documentation
g_ghosts
int g_ghosts static
Definition at line 31 of file xrdmapc.c.
Referenced by do_map(), map_holders(), and probe_holder().