nginx-xrootd: client/apps/prep/xrdprep.c File Reference
xrdprep.c File Reference
#include "brix.h"
#include "core/compat/crypto.h"
#include "core/version.h"
#include "core/progname.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct xrdprep_args
struct xrdprep_flag_t
Macros
#define XRDPREP_MAX_PATHS 64
Functions
static void xrdprep_print_help (const char *argv0)
static int xrdprep_handle_meta_flags (int argc, char **argv)
static int xrdprep_match_flag (const char *a, int *options, int *optionX)
static void xrdprep_parse_args (int argc, char **argv, xrdprep_args *out)
static int xrdprep_run (char **argv, const xrdprep_args *args)
int main (int argc, char **argv)
Variables
static const xrdprep_flag_t xrdprep_flags []
Macro Definition Documentation
XRDPREP_MAX_PATHS
#define XRDPREP_MAX_PATHS 64
Definition at line 19 of file xrdprep.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 237 of file xrdprep.c.
References brix_prog_base(), xrdprep_args::endpoint, xrdprep_args::np, xrdprep_handle_meta_flags(), xrdprep_parse_args(), and xrdprep_run().
xrdprep_handle_meta_flags()
static int xrdprep_handle_meta_flags (int argc, char ** argv) static
Definition at line 104 of file xrdprep.c.
References brix_client_version(), brix_prog_base(), and xrdprep_print_help().
Referenced by main().
xrdprep_match_flag()
static int xrdprep_match_flag (const char * a, int * options, int * optionX) static
Definition at line 136 of file xrdprep.c.
References xrdprep_flag_t::bit, xrdprep_flag_t::is_optionX, xrdprep_flag_t::long_opt, xrdprep_flag_t::short_opt, and xrdprep_flags.
Referenced by xrdprep_parse_args().
xrdprep_parse_args()
static void xrdprep_parse_args (int argc, char ** argv, xrdprep_args * out) static
Definition at line 169 of file xrdprep.c.
References xrdprep_args::endpoint, xrdprep_args::np, xrdprep_args::options, xrdprep_args::optionX, xrdprep_args::paths, xrdprep_args::prty, xrdprep_match_flag(), and XRDPREP_MAX_PATHS.
Referenced by main().
xrdprep_print_help()
static void xrdprep_print_help (const char * argv0) static
Definition at line 75 of file xrdprep.c.
References brix_prog_base(), and brix_usage_footer().
Referenced by xrdprep_handle_meta_flags().
xrdprep_run()
static int xrdprep_run (char ** argv, const xrdprep_args * args) static
Definition at line 201 of file xrdprep.c.
References brix_cli_connect(), brix_close(), brix_prepare(), brix_shellcode(), c, xrdprep_args::endpoint, brix_status::msg, xrdprep_args::np, xrdprep_args::options, xrdprep_args::optionX, xrdprep_args::paths, and xrdprep_args::prty.
Referenced by main().
Variable Documentation
xrdprep_flags
const xrdprep_flag_t xrdprep_flags[] static
Initial value:
= {
    { "-s", "--stage",  0, kXR_stage  },
    { "-c", "--cancel", 0, kXR_cancel },
    { "-w", "--wmode",  0, kXR_wmode  },
    { "-f", "--fresh",  0, kXR_fresh  },
    { "-e", "--evict",  1, kXR_evict  },
}
Definition at line 56 of file xrdprep.c.
Referenced by xrdprep_match_flag().