nginx-xrootd: client/apps/ceph/xrdrados_rescue.c File Reference
xrdrados_rescue.c File Reference
#include "sd.h"
#include "rados/sd_ceph.h"
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <rados/librados.h>
Data Structures
struct cp_ctx_t
Typedefs
typedef int(* obj_cb) (const char *key, void *ctx)
Functions
void * ngx_pcalloc (ngx_pool_t *pool, size_t size)
void * ngx_pnalloc (ngx_pool_t *pool, size_t size)
static int extract_object (sd_ceph_conn_t *c, const char *oid, FILE *out)
static int for_each_object (sd_ceph_conn_t *c, const char *prefix, obj_cb cb, void *ctx)
static int print_key (const char *key, void *ctx)
static void flatten_key (const char *key, char *out, size_t cap)
static int cp_one (const char *key, void *ctx)
static int cmd_ls (sd_ceph_conn_t *c, int argc, char **argv)
static int cmd_stat (sd_ceph_conn_t *c, int argc, char **argv)
static int cmd_get (sd_ceph_conn_t *c, int argc, char **argv)
static int cmd_cp (sd_ceph_conn_t *c, int argc, char **argv)
static int run_command (sd_ceph_conn_t *c, const char *cmd, int argc, char **argv)
int main (int argc, char **argv)
Typedef Documentation
obj_cb
typedef int(* obj_cb) (const char *key, void *ctx)
Definition at line 61 of file xrdrados_rescue.c.
Function Documentation
cmd_cp()
static int cmd_cp (sd_ceph_conn_t * c, int argc, char ** argv) static
Definition at line 215 of file xrdrados_rescue.c.
References cp_ctx_t::c, c, cp_one(), cp_ctx_t::dst, cp_ctx_t::fails, and for_each_object().
Referenced by run_command().
cmd_get()
static int cmd_get (sd_ceph_conn_t * c, int argc, char ** argv) static
Definition at line 187 of file xrdrados_rescue.c.
References c, and extract_object().
Referenced by run_command().
cmd_ls()
static int cmd_ls (sd_ceph_conn_t * c, int argc, char ** argv) static
Definition at line 140 of file xrdrados_rescue.c.
References c, for_each_object(), and print_key().
Referenced by run_command().
cmd_stat()
static int cmd_stat (sd_ceph_conn_t * c, int argc, char ** argv) static
Definition at line 161 of file xrdrados_rescue.c.
References c.
Referenced by run_command().
cp_one()
static int cp_one (const char * key, void * ctx) static
Definition at line 106 of file xrdrados_rescue.c.
References cp_ctx_t::c, cp_ctx_t::dst, extract_object(), cp_ctx_t::fails, flatten_key(), key, and name.
Referenced by cmd_cp().
extract_object()
static int extract_object (sd_ceph_conn_t * c, const char * oid, FILE * out) static
Definition at line 45 of file xrdrados_rescue.c.
References c.
Referenced by cmd_get(), and cp_one().
flatten_key()
static void flatten_key (const char * key, char * out, size_t cap) static
Definition at line 96 of file xrdrados_rescue.c.
References key.
Referenced by cp_one().
for_each_object()
static int for_each_object (sd_ceph_conn_t * c, const char * prefix, obj_cb cb, void * ctx) static
Definition at line 63 of file xrdrados_rescue.c.
References c.
Referenced by cmd_cp(), and cmd_ls().
main()
int main (int argc, char ** argv)
Definition at line 253 of file xrdrados_rescue.c.
References c, and run_command().
ngx_pcalloc()
void * ngx_pcalloc (ngx_pool_t * pool, size_t size)
Definition at line 40 of file xrdrados_rescue.c.
Referenced by acc_named_prepend(), brix_acc_authfile_parse(), brix_acc_init_server(), brix_auth_l1_create(), brix_cache_pelican_schedule_advertise(), brix_cache_storage_init(), brix_chain_append_file(), brix_cms_srv_create_conf(), brix_cms_srv_handler(), brix_conf_set_http_handoff(), brix_conf_set_transparent_proxy(), brix_configure_tls(), brix_deleg_store(), brix_hc_manager_start(), brix_hc_start(), brix_http_build_range_buf(), brix_http_chain_append_file_range(), brix_http_common_create_loc_conf(), brix_http_handoff_start(), brix_http_mirror_precontent_handler(), brix_http_mirror_proxy(), brix_http_mirror_setup(), brix_identity_alloc(), brix_init_server_cache_reap_timer(), brix_init_server_crl_jwks(), brix_init_server_watermark_timer(), brix_pcalloc_array(), brix_proxy_dispatch(), brix_relay_start(), brix_sd_instance_create(), brix_sd_posix_borrow_instance(), brix_server_setup_tls(), brix_stream_mirror_launch_target(), brix_stream_wmirror_on_open(), brix_token_jwks_schedule_refresh(), brix_token_l1_create(), brix_token_registry_build(), brix_upstream_preresolve(), brix_upstream_start_snapshot_request(), brix_vfs_adopt_fd(), brix_vfs_adopt_obj(), brix_vfs_deleg_bind(), brix_vfs_opendir_impl(), brix_zip_http_serve(), conn_init_ctx(), conn_setup_pipeline(), cvmfs_geo_done(), cvmfs_pt_done(), dashboard_build_events(), dashboard_build_tpc_registry(), dashboard_fill_cluster(), dashboard_fill_history(), dashboard_json_send(), dashboard_send_config(), delegation_reject(), delegation_request_reject(), delegation_send_csr(), dig_send_response(), mirror_fire_subrequests(), ngx_brix_cms_start(), ngx_http_brix_cvmfs_handler(), ngx_http_brix_dashboard_create_loc_conf(), ngx_http_brix_guard_access_handler(), ngx_http_brix_guard_create_loc_conf(), ngx_http_brix_metrics_create_loc_conf(), ngx_stream_brix_create_srv_conf(), rl_ensure_ctx(), s3_list_cache_get(), scan_send(), sd_posix_init(), sd_posix_opendir(), send_html(), send_json(), staged_alloc_handle(), tpc_marker_build_ctx(), webdav_introspect_fire(), webdav_proxy_ensure_ssl_ctx(), webdav_proxy_handler(), webdav_proxy_pool_setup(), wmir_launch(), wt_ensure_ctx(), and zip_http_stage_stored().
ngx_pnalloc()
void * ngx_pnalloc (ngx_pool_t * pool, size_t size)
Definition at line 41 of file xrdrados_rescue.c.
Referenced by acc_cache_to_array(), acc_csv_push_field(), acc_load_authfile(), acc_pstrdup(), acc_uri_decode(), brix_acc_gate_host(), brix_admin_set_secret(), brix_conf_set_cms_manager(), brix_conf_set_http_handoff(), brix_conf_set_transparent_proxy(), brix_copy_conf_string(), brix_gsi_cache_cert_pem(), brix_http_build_range_buf(), brix_http_chain_append_file_range(), brix_http_chain_vappendf(), brix_http_handoff_start(), brix_http_mirror_rewrite_dest(), brix_http_mirror_set_url(), brix_identity_derive_attrs(), brix_identity_describe(), brix_identity_push_str(), brix_identity_set_cstr(), brix_manager_map_store_host(), brix_proto_deleg_capture_proxy_header(), brix_pstrdup_z(), brix_pstrdupz(), brix_relay_start(), brix_server_set_wt_credential(), brix_token_exchange(), brix_tpc_copy_credential_str(), brix_tx_append_field(), brix_tx_cstr(), brix_tx_parse_response(), brix_upstream_preresolve(), brix_vfs_copy_path(), brix_vfs_deleg_proxy(), chain_append_text(), cors_emit_max_age(), cvmfs_var_set(), dashboard_download_set_headers(), dashboard_parse_user_line(), delegation_reject(), delegation_request_reject(), delegation_send_csr(), gsi_promote_fullproxy(), imp_dup(), login_set_redirect(), ngx_http_brix_dashboard_page_handler(), oidc_finalize_token(), pmark_dup_json_str(), proxy_parse_host_port(), s3_apply_response_overrides(), s3_echo_user_metadata(), s3_get_cache_fill(), s3_list_cache_get(), s3_post_enforce_policy(), s3_verify_bearer(), scvmfs_bearer_token(), sd_posix_init(), send_json(), srr_serialise(), staged_pool_strdup(), sts_host_from_url(), sts_perform(), sts_pool_cstr(), tpc_cred_parse_token_response(), tpc_marker_send_accepted(), vfs_readdir_fill_entry(), webdav_conf_dig_export(), webdav_introspect_fire(), webdav_lock_xml_response(), webdav_proxy_build_host(), webdav_proxy_build_url_base(), webdav_proxy_process_header(), webdav_proxy_process_status_line(), webdav_proxy_rewrite_destination(), webdav_register_send_fd_cleanup(), webdav_set_upload_offset(), webdav_tpc_add_bearer_header(), webdav_tpc_apply_credential_delegation(), webdav_tpc_collect_transfer_headers(), webdav_tpc_pstrndup0(), webdav_tpc_push_add_overwrite_value(), webdav_tpc_user_proxy_from_store(), webdav_tpc_user_proxy_materialise(), wt_check_claims(), xrdhttp_digest_body_filter(), and zip_http_set_headers().
print_key()
static int print_key (const char * key, void * ctx) static
Definition at line 88 of file xrdrados_rescue.c.
References key.
Referenced by cmd_ls().
run_command()
static int run_command (sd_ceph_conn_t * c, const char * cmd, int argc, char ** argv) static
Definition at line 242 of file xrdrados_rescue.c.
References c, cmd_cp(), cmd_get(), cmd_ls(), and cmd_stat().
Referenced by main().