nginx-xrootd: client/lib/core/config/xrdrc.c File Reference
xrdrc.c File Reference
#include "brix.h"
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct xrdrc_alias
struct rc_alias_field
struct rc_default_field
Macros
#define XRDRC_MAX_ALIASES 256
#define XRDRC_NAME_MAX 64
Functions
static void rstrip (char *s)
static char * rc_next_line (char *line)
static void rc_open_section (char *s, int *cur, int *in_defaults)
static int rc_parse_kv (char *s, char **out_k, char **out_v)
static void rc_apply_default (const char *k, const char *v)
static void rc_apply_alias (int cur, const char *k, const char *v)
static void rc_apply_setting (int in_defaults, int cur, const char *k, const char *v)
static void xrdrc_load (void)
int brix_alias_resolve (const char *arg, char *out, size_t outsz)
static int read_first_line (const char *path, char *out, size_t outsz)
int brix_alias_lookup (const char *name, brix_alias_info *info)
int brix_xrdrc_default_ms (const char *key, int *out_ms)
Variables
static xrdrc_alias g_aliases [256]
static int g_nalias = 0
static int g_loaded = 0
static int g_def_connect_ms = 0
static int g_def_io_ms = 0
static int g_def_stall_ms = 0
static int g_def_backoff_ms = 0
static const rc_alias_field rc_alias_fields []
static const rc_default_field rc_default_fields []
Macro Definition Documentation
XRDRC_MAX_ALIASES
#define XRDRC_MAX_ALIASES 256
Definition at line 26 of file xrdrc.c.
XRDRC_NAME_MAX
#define XRDRC_NAME_MAX 64
Definition at line 27 of file xrdrc.c.
Function Documentation
brix_alias_lookup()
int brix_alias_lookup (const char * name, brix_alias_info * info)
Definition at line 380 of file xrdrc.c.
References brix_alias_info::bearer, brix_alias_info::found, g_aliases, g_loaded, g_nalias, name, brix_alias_info::proxy, xrdrc_alias::proxy, read_first_line(), brix_alias_info::s3_access, xrdrc_alias::s3_access, brix_alias_info::s3_region, xrdrc_alias::s3_region, brix_alias_info::s3_secret, xrdrc_alias::s3_secret, xrdrc_alias::token, brix_alias_info::token_file, xrdrc_alias::token_file, brix_alias_info::token_file_failed, and xrdrc_load().
Referenced by merge_alias_auth().
brix_alias_resolve()
int brix_alias_resolve (const char * arg, char * out, size_t outsz)
Definition at line 309 of file xrdrc.c.
References g_aliases, g_loaded, g_nalias, name, xrdrc_alias::url, xrdrc_load(), and XRDRC_NAME_MAX.
Referenced by endpoint_to_url(), expand_source(), fs_find_endpoint(), map_fs_arg(), validate_and_finalize_args(), and xrd_mount_build_argv().
brix_xrdrc_default_ms()
int brix_xrdrc_default_ms (const char * key, int * out_ms)
Definition at line 428 of file xrdrc.c.
References g_def_backoff_ms, g_def_connect_ms, g_def_io_ms, g_def_stall_ms, g_loaded, key, and xrdrc_load().
Referenced by backoff_base_ms(), httpx_window_ms(), opts_window_ms(), resolve_ms(), and webfile_window_ms().
rc_apply_alias()
static void rc_apply_alias (int cur, const char * k, const char * v) static
Definition at line 229 of file xrdrc.c.
References g_aliases, key, and rc_alias_fields.
Referenced by rc_apply_setting().
rc_apply_default()
static void rc_apply_default (const char * k, const char * v) static
Definition at line 200 of file xrdrc.c.
References rc_default_field::dst, key, and rc_default_fields.
Referenced by rc_apply_setting().
rc_apply_setting()
static void rc_apply_setting (int in_defaults, int cur, const char * k, const char * v) static
Definition at line 252 of file xrdrc.c.
References rc_apply_alias(), and rc_apply_default().
Referenced by xrdrc_load().
rc_next_line()
static char * rc_next_line (char * line) static
Definition at line 117 of file xrdrc.c.
References rstrip(), and s.
Referenced by xrdrc_load().
rc_open_section()
static void rc_open_section (char * s, int * cur, int * in_defaults) static
Definition at line 140 of file xrdrc.c.
References g_aliases, g_nalias, name, s, xrdrc_alias::url, and XRDRC_MAX_ALIASES.
Referenced by xrdrc_load().
rc_parse_kv()
static int rc_parse_kv (char * s, char ** out_k, char ** out_v) static
Definition at line 174 of file xrdrc.c.
References s.
Referenced by xrdrc_load().
read_first_line()
static int read_first_line (const char * path, char * out, size_t outsz) static
Definition at line 357 of file xrdrc.c.
References rstrip(), and s.
Referenced by brix_alias_lookup().
rstrip()
static void rstrip (char * s) static
Definition at line 55 of file xrdrc.c.
References s.
Referenced by rc_next_line(), and read_first_line().
xrdrc_load()
static void xrdrc_load (void) static
Definition at line 263 of file xrdrc.c.
References g_loaded, rc_apply_setting(), rc_next_line(), rc_open_section(), rc_parse_kv(), s, and XRDC_PATH_MAX.
Referenced by brix_alias_lookup(), brix_alias_resolve(), and brix_xrdrc_default_ms().
Variable Documentation
g_aliases
xrdrc_alias g_aliases[256] static
Definition at line 41 of file xrdrc.c.
Referenced by brix_alias_lookup(), brix_alias_resolve(), rc_apply_alias(), and rc_open_section().
g_def_backoff_ms
int g_def_backoff_ms = 0 static
Definition at line 51 of file xrdrc.c.
Referenced by brix_xrdrc_default_ms().
g_def_connect_ms
int g_def_connect_ms = 0 static
Definition at line 48 of file xrdrc.c.
Referenced by brix_xrdrc_default_ms().
g_def_io_ms
int g_def_io_ms = 0 static
Definition at line 49 of file xrdrc.c.
Referenced by brix_xrdrc_default_ms().
g_def_stall_ms
int g_def_stall_ms = 0 static
Definition at line 50 of file xrdrc.c.
Referenced by brix_xrdrc_default_ms().
g_loaded
int g_loaded = 0 static
Definition at line 43 of file xrdrc.c.
Referenced by brix_alias_lookup(), brix_alias_resolve(), brix_xrdrc_default_ms(), and xrdrc_load().
g_nalias
int g_nalias = 0 static
Definition at line 42 of file xrdrc.c.
Referenced by brix_alias_lookup(), brix_alias_resolve(), and rc_open_section().
rc_alias_fields
const rc_alias_field rc_alias_fields[] static
Initial value:
= {
    { "url",               offsetof(xrdrc_alias, url),        sizeof(((xrdrc_alias *) 0)->url) },
    { "token",             offsetof(xrdrc_alias, token),      sizeof(((xrdrc_alias *) 0)->token) },
    { "token_file",        offsetof(xrdrc_alias, token_file), sizeof(((xrdrc_alias *) 0)->token_file) },
    { "bearer_token_file", offsetof(xrdrc_alias, token_file), sizeof(((xrdrc_alias *) 0)->token_file) },
    { "s3_access",         offsetof(xrdrc_alias, s3_access),  sizeof(((xrdrc_alias *) 0)->s3_access) },
    { "s3_secret",         offsetof(xrdrc_alias, s3_secret),  sizeof(((xrdrc_alias *) 0)->s3_secret) },
    { "s3_region",         offsetof(xrdrc_alias, s3_region),  sizeof(((xrdrc_alias *) 0)->s3_region) },
    { "proxy",             offsetof(xrdrc_alias, proxy),      sizeof(((xrdrc_alias *) 0)->proxy) },
}
Definition at line 82 of file xrdrc.c.
Referenced by rc_apply_alias().
rc_default_fields
const rc_default_field rc_default_fields[] static
Initial value:
= {
    { "connect_timeout_ms", &g_def_connect_ms },
    { "io_timeout_ms",      &g_def_io_ms },
    { "max_stall_ms",       &g_def_stall_ms },
    { "backoff_base_ms",    &g_def_backoff_ms },
}
Definition at line 98 of file xrdrc.c.
Referenced by rc_apply_default().