nginx-xrootd: client/apps/scan/xrdstorascan.c File Reference
xrdstorascan.c File Reference
#include "storascan_core.h"
#include "brix.h"
#include "brix_net.h"
#include "brix_ops.h"
#include "core/version.h"
#include "core/progname.h"
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct bench_worker
struct bench_cell_cfg_t
struct bench_args_t
struct scan_ep
struct scan_args_t
Macros
#define STORASCAN_HEX_MAX 129
#define STORASCAN_MAX_SWEEP 16 /* cells per block/parallel list */
#define STORASCAN_LAT_CAP (5u << 20) /* per-worker latency-sample ceiling */
#define STORASCAN_MSG (XRDC_MSG_MAX + 32) /* room for a short prefix + st.msg */
#define SX_OK 0
#define SX_MISMATCH 1
#define SX_NORECORD 2
#define SX_ERROR 3
#define SX_USAGE 64
Functions
static int usage_fp (FILE *out, const char *prog, int rc)
static int usage (const char *prog, int rc)
static int opt_take (const char *name, int argc, char **argv, int *i, const char **out)
static int storascan_connect (const char *url, brix_url *u, brix_conn *c, brix_status *st)
static int verify_download_tmp (brix_conn *c, const char *path, brix_status *st)
static int verify_help (const char *prog)
static int verify_parse_args (int argc, char **argv, const char **url, const char **algo, int *quiet, const char *prog)
static int verify_compute_wire_hex (brix_conn *c, const char *path, brix_cksum_algo algo, char *hex, size_t hexsz)
static int cmd_verify (int argc, char **argv, const char *prog)
static int64_t bench_offset (bench_worker *w, uint64_t k)
static void * bench_run (void *arg)
static void bench_workers_free (bench_worker *w, pthread_t *th, int parallel)
static int bench_workers_init (const bench_cell_cfg_t *cfg, bench_worker *w, char *errmsg, size_t errsz)
static void bench_workers_run (bench_worker *w, pthread_t *th, const bench_cell_cfg_t *cfg, uint64_t *t0, uint64_t *t1)
static int bench_workers_error (const bench_worker *w, int parallel, char *errmsg, size_t errsz)
static int bench_workers_compute (const bench_worker *w, const bench_cell_cfg_t *cfg, uint64_t elapsed_ns, storascan_bench_result *out)
static int bench_cell (const bench_cell_cfg_t *cfg, storascan_bench_result *out, char *errmsg, size_t errsz)
static int parse_list (const char *s, int as_bytes, long *out, int max)
static int bench_help (const char *prog)
static int bench_parse_args (int argc, char **argv, bench_args_t *ba, const char *prog)
static int bench_validate_args (bench_args_t *ba, const char *prog)
static void bench_render_cell (const bench_args_t *ba, long block, long par, const storascan_bench_result *r)
static int bench_run_matrix (const bench_args_t *ba, const brix_url *u, int64_t fsize)
static int cmd_bench (int argc, char **argv, const char *prog)
static int scan_parse_url (const char *url, scan_ep *ep)
static int scan_login (const scan_ep *ep, const scan_args_t *sa, char *cookie, size_t cksz, brix_status *st)
static int scan_json_field (const char *line, const char *key, char *out, size_t outsz)
static long scan_render_summary (const char *buf, int as_json, int summary_only)
static void scan_render_inspect (const char *buf)
static void scan_render_health (const char *buf)
static void scan_render_object (const char *buf)
static void scan_render_drift (const char *buf)
static void scan_render_file (const char *buf)
static void scan_render_row (const char *buf, const char *t, int as_json, int summary_only)
static long scan_render (const char *body, int as_json, int summary_only)
static void scan_qencode (const char *in, char *out, size_t outsz)
static int scan_parse_scan_args (int argc, char **argv, scan_args_t *sa)
static int scan_fetch (const char *mode, const scan_ep *ep, const scan_args_t *sa, const char *cookie, brix_http_resp *resp)
static int cmd_scan (const char *mode, int argc, char **argv, const char *prog)
int main (int argc, char **argv)
Macro Definition Documentation
STORASCAN_HEX_MAX
#define STORASCAN_HEX_MAX 129
Definition at line 34 of file xrdstorascan.c.
STORASCAN_LAT_CAP
#define STORASCAN_LAT_CAP (5u << 20) /* per-worker latency-sample ceiling */
Definition at line 36 of file xrdstorascan.c.
STORASCAN_MAX_SWEEP
#define STORASCAN_MAX_SWEEP 16 /* cells per block/parallel list */
Definition at line 35 of file xrdstorascan.c.
STORASCAN_MSG
#define STORASCAN_MSG (XRDC_MSG_MAX + 32) /* room for a short prefix + st.msg */
Definition at line 37 of file xrdstorascan.c.
SX_ERROR
#define SX_ERROR 3
Definition at line 43 of file xrdstorascan.c.
SX_MISMATCH
#define SX_MISMATCH 1
Definition at line 41 of file xrdstorascan.c.
SX_NORECORD
#define SX_NORECORD 2
Definition at line 42 of file xrdstorascan.c.
SX_OK
#define SX_OK 0
Definition at line 40 of file xrdstorascan.c.
SX_USAGE
#define SX_USAGE 64
Definition at line 44 of file xrdstorascan.c.
Function Documentation
bench_cell()
static int bench_cell (const bench_cell_cfg_t * cfg, storascan_bench_result * out, char * errmsg, size_t errsz) static
Definition at line 602 of file xrdstorascan.c.
References bench_workers_compute(), bench_workers_error(), bench_workers_free(), bench_workers_init(), bench_workers_run(), and bench_cell_cfg_t::parallel.
Referenced by bench_run_matrix().
bench_help()
static int bench_help (const char * prog) static
Definition at line 685 of file xrdstorascan.c.
References brix_usage_footer(), and SX_OK.
Referenced by cmd_bench().
bench_offset()
static int64_t bench_offset (bench_worker * w, uint64_t k) static
Definition at line 358 of file xrdstorascan.c.
References bench_worker::block, bench_worker::fsize, bench_worker::random, and bench_worker::seed.
Referenced by bench_run().
bench_parse_args()
static int bench_parse_args (int argc, char ** argv, bench_args_t * ba, const char * prog) static
Definition at line 706 of file xrdstorascan.c.
References bench_args_t::block_s, bench_args_t::count, bench_args_t::duration_s, bench_args_t::json, opt_take(), bench_args_t::par_s, bench_args_t::pattern, SX_OK, SX_USAGE, bench_args_t::url, and usage().
Referenced by cmd_bench().
bench_render_cell()
static void bench_render_cell (const bench_args_t * ba, long block, long par, const storascan_bench_result * r) static
Definition at line 772 of file xrdstorascan.c.
References storascan_bench_result::bytes, storascan_bench_result::iops, bench_args_t::json, storascan_bench_result::ops, storascan_bench_result::p50_ms, storascan_bench_result::p95_ms, storascan_bench_result::p99_ms, bench_args_t::pattern, and storascan_bench_result::throughput_mibps.
Referenced by bench_run_matrix().
bench_run()
static void * bench_run (void * arg) static
Definition at line 374 of file xrdstorascan.c.
References bench_offset(), bench_worker::block, brix_close(), brix_connect(), brix_file_close(), brix_file_open_read(), brix_file_read(), brix_mono_ns(), brix_status_clear(), bench_worker::bytes, c, bench_worker::deadline_ns, bench_worker::err, bench_worker::errmsg, bench_worker::lat_ms, bench_worker::lat_n, brix_status::msg, bench_worker::op_budget, brix_url::path, STORASCAN_LAT_CAP, and bench_worker::u.
Referenced by bench_workers_run().
bench_run_matrix()
static int bench_run_matrix (const bench_args_t * ba, const brix_url * u, int64_t fsize) static
Definition at line 799 of file xrdstorascan.c.
References bench_cell(), bench_render_cell(), bench_cell_cfg_t::block, bench_args_t::blocks, bench_args_t::count, bench_cell_cfg_t::duration_ns, bench_args_t::duration_s, bench_cell_cfg_t::fsize, bench_args_t::nblocks, bench_args_t::npars, bench_cell_cfg_t::parallel, bench_args_t::pars, bench_args_t::pattern, bench_cell_cfg_t::random, STORASCAN_MSG, SX_ERROR, SX_OK, bench_cell_cfg_t::total_ops, bench_cell_cfg_t::u, bench_cell_cfg_t::url, and bench_args_t::url.
Referenced by cmd_bench().
bench_validate_args()
static int bench_validate_args (bench_args_t * ba, const char * prog) static
Definition at line 747 of file xrdstorascan.c.
References bench_args_t::block_s, bench_args_t::blocks, bench_args_t::nblocks, bench_args_t::npars, bench_args_t::par_s, bench_args_t::pars, parse_list(), bench_args_t::pattern, STORASCAN_MAX_SWEEP, SX_OK, SX_USAGE, bench_args_t::url, and usage().
Referenced by cmd_bench().
bench_workers_compute()
static int bench_workers_compute (const bench_worker * w, const bench_cell_cfg_t * cfg, uint64_t elapsed_ns, storascan_bench_result * out) static
Definition at line 574 of file xrdstorascan.c.
References bench_worker::bytes, bench_worker::lat_n, bench_cell_cfg_t::parallel, and storascan_bench_compute().
Referenced by bench_cell().
bench_workers_error()
static int bench_workers_error (const bench_worker * w, int parallel, char * errmsg, size_t errsz) static
Definition at line 551 of file xrdstorascan.c.
Referenced by bench_cell().
bench_workers_free()
static void bench_workers_free (bench_worker * w, pthread_t * th, int parallel) static
Definition at line 466 of file xrdstorascan.c.
Referenced by bench_cell().
bench_workers_init()
static int bench_workers_init (const bench_cell_cfg_t * cfg, bench_worker * w, char * errmsg, size_t errsz) static
Definition at line 486 of file xrdstorascan.c.
References bench_worker::block, bench_cell_cfg_t::block, brix_mono_ns(), bench_worker::deadline_ns, bench_cell_cfg_t::duration_ns, bench_worker::fsize, bench_cell_cfg_t::fsize, bench_worker::lat_ms, bench_worker::op_budget, bench_cell_cfg_t::parallel, bench_worker::random, bench_cell_cfg_t::random, bench_worker::seed, STORASCAN_LAT_CAP, bench_cell_cfg_t::total_ops, bench_worker::u, bench_cell_cfg_t::u, bench_worker::url, and bench_cell_cfg_t::url.
Referenced by bench_cell().
bench_workers_run()
static void bench_workers_run (bench_worker * w, pthread_t * th, const bench_cell_cfg_t * cfg, uint64_t * t0, uint64_t * t1) static
Definition at line 517 of file xrdstorascan.c.
References bench_run(), brix_mono_ns(), bench_worker::deadline_ns, bench_cell_cfg_t::duration_ns, bench_worker::err, and bench_cell_cfg_t::parallel.
Referenced by bench_cell().
cmd_bench()
static int cmd_bench (int argc, char ** argv, const char * prog) static
Definition at line 833 of file xrdstorascan.c.
References bench_help(), bench_parse_args(), bench_run_matrix(), bench_validate_args(), bench_args_t::block_s, brix_close(), brix_shellcode(), brix_stat(), c, bench_args_t::count, bench_args_t::duration_s, bench_args_t::json, brix_status::msg, bench_args_t::par_s, brix_url::path, bench_args_t::pattern, brix_statinfo::size, storascan_connect(), SX_OK, and bench_args_t::url.
Referenced by main().
cmd_scan()
static int cmd_scan (const char * mode, int argc, char ** argv, const char * prog) static
Definition at line 1284 of file xrdstorascan.c.
References scan_args_t::as_json, brix_http_resp::body, brix_http_resp_free(), brix_shellcode(), brix_status_clear(), brix_usage_footer(), brix_status::msg, scan_args_t::password, scan_fetch(), scan_login(), scan_parse_scan_args(), scan_parse_url(), scan_render(), scan_args_t::summary_only, SX_MISMATCH, SX_OK, SX_USAGE, scan_args_t::url, and usage().
Referenced by main().
cmd_verify()
static int cmd_verify (int argc, char ** argv, const char * prog) static
Definition at line 270 of file xrdstorascan.c.
References brix_cksum_algo_parse(), brix_close(), brix_query_cksum(), brix_shellcode(), c, brix_status::msg, brix_url::path, storascan_cks_compare(), STORASCAN_CKS_MATCH, STORASCAN_CKS_MISMATCH, STORASCAN_CKS_MISSING, storascan_connect(), STORASCAN_HEX_MAX, SX_MISMATCH, SX_NORECORD, SX_OK, SX_USAGE, verify_compute_wire_hex(), verify_help(), and verify_parse_args().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 1346 of file xrdstorascan.c.
References brix_client_version(), brix_prog_base(), cmd_bench(), cmd_scan(), cmd_verify(), SX_OK, SX_USAGE, usage(), and usage_fp().
opt_take()
static int opt_take (const char * name, int argc, char ** argv, int * i, const char ** out) static
Definition at line 98 of file xrdstorascan.c.
References name.
Referenced by bench_parse_args(), and verify_parse_args().
parse_list()
static int parse_list (const char * s, int as_bytes, long * out, int max) static
Definition at line 636 of file xrdstorascan.c.
References brix_parse_bytes(), s, and tok.
Referenced by bench_validate_args().
scan_fetch()
static int scan_fetch (const char * mode, const scan_ep * ep, const scan_args_t * sa, const char * cookie, brix_http_resp * resp) static
Definition at line 1252 of file xrdstorascan.c.
References scan_args_t::alg, brix_http_req(), brix_http_resp_free(), brix_shellcode(), brix_status_clear(), scan_ep::host, scan_args_t::insecure, brix_status::msg, scan_args_t::path, scan_ep::port, scan_qencode(), brix_http_resp::status, SX_ERROR, SX_OK, and scan_ep::tls.
Referenced by cmd_scan().
scan_json_field()
static int scan_json_field (const char * line, const char * key, char * out, size_t outsz) static
Definition at line 978 of file xrdstorascan.c.
References key.
Referenced by scan_render(), scan_render_drift(), scan_render_file(), scan_render_health(), scan_render_inspect(), scan_render_object(), and scan_render_summary().
scan_login()
static int scan_login (const scan_ep * ep, const scan_args_t * sa, char * cookie, size_t cksz, brix_status * st) static
Definition at line 941 of file xrdstorascan.c.
References brix_http_header(), brix_http_req(), brix_http_resp_free(), brix_status_set(), scan_ep::host, scan_args_t::insecure, scan_args_t::password, scan_ep::port, brix_http_resp::status, scan_ep::tls, and XRDC_EAUTH.
Referenced by cmd_scan().
scan_parse_scan_args()
static int scan_parse_scan_args (int argc, char ** argv, scan_args_t * sa) static
Definition at line 1217 of file xrdstorascan.c.
References scan_args_t::alg, scan_args_t::as_json, scan_args_t::insecure, scan_args_t::password, scan_args_t::path, scan_args_t::summary_only, and scan_args_t::url.
Referenced by cmd_scan().
scan_parse_url()
static int scan_parse_url (const char * url, scan_ep * ep) static
Definition at line 911 of file xrdstorascan.c.
References scan_ep::host, scan_ep::port, and scan_ep::tls.
Referenced by cmd_scan().
scan_qencode()
static void scan_qencode (const char * in, char * out, size_t outsz) static
Definition at line 1189 of file xrdstorascan.c.
References c, and hex().
Referenced by scan_fetch().
scan_render()
static long scan_render (const char * body, int as_json, int summary_only) static
Definition at line 1158 of file xrdstorascan.c.
References scan_json_field(), scan_render_row(), and scan_render_summary().
Referenced by cmd_scan().
scan_render_drift()
static void scan_render_drift (const char * buf) static
Definition at line 1096 of file xrdstorascan.c.
References cls(), key, and scan_json_field().
Referenced by scan_render_row().
scan_render_file()
static void scan_render_file (const char * buf) static
Definition at line 1113 of file xrdstorascan.c.
References scan_json_field().
Referenced by scan_render_row().
scan_render_health()
static void scan_render_health (const char * buf) static
Definition at line 1060 of file xrdstorascan.c.
References scan_json_field().
Referenced by scan_render_row().
scan_render_inspect()
static void scan_render_inspect (const char * buf) static
Definition at line 1041 of file xrdstorascan.c.
References scan_json_field().
Referenced by scan_render_row().
scan_render_object()
static void scan_render_object (const char * buf) static
Definition at line 1078 of file xrdstorascan.c.
References key, and scan_json_field().
Referenced by scan_render_row().
scan_render_row()
static void scan_render_row (const char * buf, const char * t, int as_json, int summary_only) static
Definition at line 1134 of file xrdstorascan.c.
References scan_render_drift(), scan_render_file(), scan_render_health(), scan_render_inspect(), and scan_render_object().
Referenced by scan_render().
scan_render_summary()
static long scan_render_summary (const char * buf, int as_json, int summary_only) static
Definition at line 1015 of file xrdstorascan.c.
References scan_json_field().
Referenced by scan_render().
storascan_connect()
static int storascan_connect (const char * url, brix_url * u, brix_conn * c, brix_status * st) static
Definition at line 111 of file xrdstorascan.c.
References brix_connect(), brix_endpoint_parse(), brix_shellcode(), brix_status_clear(), c, brix_url::host, brix_status::msg, brix_url::path, brix_url::port, SX_OK, and SX_USAGE.
Referenced by cmd_bench(), and cmd_verify().
usage()
static int usage (const char * prog, int rc) static
Definition at line 81 of file xrdstorascan.c.
References usage_fp().
usage_fp()
static int usage_fp (FILE * out, const char * prog, int rc) static
Definition at line 52 of file xrdstorascan.c.
References brix_usage_footer().
Referenced by main(), and usage().
verify_compute_wire_hex()
static int verify_compute_wire_hex (brix_conn * c, const char * path, brix_cksum_algo algo, char * hex, size_t hexsz) static
Definition at line 247 of file xrdstorascan.c.
References brix_cksum_fd(), brix_shellcode(), brix_status_clear(), c, close(), hex(), lseek(), brix_status::msg, SX_ERROR, SX_OK, and verify_download_tmp().
Referenced by cmd_verify().
verify_download_tmp()
static int verify_download_tmp (brix_conn * c, const char * path, brix_status * st) static
Definition at line 135 of file xrdstorascan.c.
References brix_file_close(), brix_file_open_read(), brix_file_read(), brix_status_set(), c, close(), and XRDC_ESOCK.
Referenced by verify_compute_wire_hex().
verify_help()
static int verify_help (const char * prog) static
Definition at line 193 of file xrdstorascan.c.
References brix_usage_footer(), and SX_OK.
Referenced by cmd_verify().
verify_parse_args()
static int verify_parse_args (int argc, char ** argv, const char ** url, const char ** algo, int * quiet, const char * prog) static
Definition at line 212 of file xrdstorascan.c.
References opt_take(), SX_OK, SX_USAGE, and usage().
Referenced by cmd_verify().