nginx-xrootd: client/apps/auth/xrdsssadmin.c File Reference
xrdsssadmin.c File Reference
#include "brix.h"
#include "auth/sss/sss_keytab.h"
#include "core/version.h"
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <openssl/rand.h>
Data Structures
struct add_args_t
struct cli_opts_t
struct opt_spec
Enumerations
enum opt_kind { OPT_STR , OPT_I32 , OPT_I64 }
Functions
static void usage_fp (FILE *out)
static void usage (void)
static int load_or_empty (const char *path, brix_sss_key *keys, int max, int *n)
static int add_fill_entry (brix_sss_key *k, const add_args_t *a, int64_t maxid, int keylen)
static int cmd_add (const char *path, const add_args_t *a)
static int cmd_list (const char *path)
static int cmd_del (const char *path, int64_t id)
static void apply_opt (cli_opts_t *o, const opt_spec *s, const char *val)
static const opt_spec * match_opt (const char *a)
static int parse_opts (int argc, char **argv, cli_opts_t *o, int *stop)
static int dispatch_cmd (const cli_opts_t *o, const char *keytab)
int main (int argc, char **argv)
Variables
static const opt_spec OPTS []
Enumeration Type Documentation
opt_kind
enum opt_kind
Enumerator
OPT_STR
OPT_I32
OPT_I64
Definition at line 270 of file xrdsssadmin.c.
Function Documentation
add_fill_entry()
static int add_fill_entry (brix_sss_key * k, const add_args_t * a, int64_t maxid, int keylen) static
Definition at line 102 of file xrdsssadmin.c.
References brix_sss_key::exp, add_args_t::group, brix_sss_key::group, brix_sss_key::id, brix_sss_key::key, brix_sss_key::key_len, add_args_t::lifetime_days, add_args_t::name, brix_sss_key::name, add_args_t::user, brix_sss_key::user, and add_args_t::want_id.
Referenced by cmd_add().
apply_opt()
static void apply_opt (cli_opts_t * o, const opt_spec * s, const char * val) static
Definition at line 309 of file xrdsssadmin.c.
References OPT_I64, OPT_STR, and s.
Referenced by parse_opts().
cmd_add()
static int cmd_add (const char * path, const add_args_t * a) static
Definition at line 141 of file xrdsssadmin.c.
References add_fill_entry(), brix_sss_keytab_read(), brix_sss_keytab_write(), brix_status_clear(), brix_sss_key::id, add_args_t::keylen, load_or_empty(), brix_status::msg, XRDC_SSS_KEY_MAX, and XRDC_SSS_KEYS_MAX.
Referenced by dispatch_cmd().
cmd_del()
static int cmd_del (const char * path, int64_t id) static
Definition at line 213 of file xrdsssadmin.c.
References brix_sss_keytab_read(), brix_sss_keytab_write(), brix_status_clear(), brix_status::msg, and XRDC_SSS_KEYS_MAX.
Referenced by dispatch_cmd().
cmd_list()
static int cmd_list (const char * path) static
Definition at line 188 of file xrdsssadmin.c.
References brix_sss_keytab_read(), brix_status_clear(), brix_status::msg, name, and XRDC_SSS_KEYS_MAX.
Referenced by dispatch_cmd().
dispatch_cmd()
static int dispatch_cmd (const cli_opts_t * o, const char * keytab) static
Definition at line 391 of file xrdsssadmin.c.
References cli_opts_t::add, cli_opts_t::cmd, cmd_add(), cmd_del(), cmd_list(), cli_opts_t::id, usage(), and add_args_t::want_id.
Referenced by main().
load_or_empty()
static int load_or_empty (const char * path, brix_sss_key * keys, int max, int * n) static
Definition at line 57 of file xrdsssadmin.c.
References access(), brix_sss_keytab_read(), brix_status_clear(), and brix_status::msg.
Referenced by cmd_add().
main()
int main (int argc, char ** argv)
Definition at line 411 of file xrdsssadmin.c.
References brix_client_version(), brix_sss_keytab_default(), cli_opts_t::cmd, dispatch_cmd(), cli_opts_t::keytab, parse_opts(), usage(), usage_fp(), and XRDC_PATH_MAX.
match_opt()
static const opt_spec * match_opt (const char * a) static
Definition at line 330 of file xrdsssadmin.c.
References opt_spec::alt, name, and OPTS.
Referenced by parse_opts().
parse_opts()
static int parse_opts (int argc, char ** argv, cli_opts_t * o, int * stop) static
Definition at line 357 of file xrdsssadmin.c.
References apply_opt(), cli_opts_t::cmd, match_opt(), s, and usage().
Referenced by main().
usage()
static void usage (void) static
Definition at line 50 of file xrdsssadmin.c.
References usage_fp().
Referenced by dispatch_cmd(), main(), and parse_opts().
usage_fp()
static void usage_fp (FILE * out) static
Definition at line 30 of file xrdsssadmin.c.
References BRIX_USAGE_FOOTER.
Referenced by main(), and usage().
Variable Documentation
OPTS
const opt_spec OPTS[] static
Initial value:
= {
    { "--keytab",   "-k", OPT_STR, offsetof(cli_opts_t, keytab)            },
    { "--user",     NULL, OPT_STR, offsetof(cli_opts_t, add.user)          },
    { "--group",    NULL, OPT_STR, offsetof(cli_opts_t, add.group)         },
    { "--name",     NULL, OPT_STR, offsetof(cli_opts_t, add.name)          },
    { "--id",       NULL, OPT_I64, offsetof(cli_opts_t, id)                },
    { "--lifetime", NULL, OPT_I32, offsetof(cli_opts_t, add.lifetime_days) },
    { "--keylen",   NULL, OPT_I32, offsetof(cli_opts_t, add.keylen)        },
}
Definition at line 289 of file xrdsssadmin.c.
Referenced by match_opt().