nginx-xrootd: client/apps/fs/xrootdfs_meta.c File Reference
xrootdfs_meta.c File Reference
#include "xrootdfs_internal.h"
Functions
static int getattr_from_open_writer (struct fuse_file_info *fi, struct stat *stbuf)
int xfs_getattr (const char *path, struct stat *stbuf, struct fuse_file_info *fi)
int xfs_readdir (const char *path, void *buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info *fi, enum fuse_readdir_flags flags)
int xfs_mkdir (const char *path, mode_t mode)
int xfs_unlink (const char *path)
int xfs_rmdir (const char *path)
int xfs_rename (const char *from, const char *to, unsigned int flags)
int xfs_chmod (const char *path, mode_t mode, struct fuse_file_info *fi)
int xfs_truncate (const char *path, off_t size, struct fuse_file_info *fi)
int xfs_utimens (const char *path, const struct timespec tv[2], struct fuse_file_info *fi)
int xfs_chown (const char *path, uid_t uid, gid_t gid, struct fuse_file_info *fi)
int xfs_symlink (const char *target, const char *linkpath)
static int xfs_readlink_one_attempt (const char *sp, char *buf, size_t size, brix_status *st)
int xfs_readlink (const char *path, char *buf, size_t size)
int xfs_statfs (const char *path, struct statvfs *stbuf)
int xfs_access (const char *path, int mask)
Function Documentation
getattr_from_open_writer()
static int getattr_from_open_writer (struct fuse_file_info * fi, struct stat * stbuf) static
Definition at line 16 of file xrootdfs_meta.c.
References afh::writable, and afh::wsize.
Referenced by xfs_getattr().
xfs_access()
int xfs_access (const char * path, int mask)
Definition at line 350 of file xrootdfs_meta.c.
References brix_fuse_op_stat(), brix_status_clear(), g_web, ctx_qspace::path, brix_fuse_ctx_stat::path, brix_fuse_ctx_stat::si, srv_path(), xfs_meta(), and XRDC_PATH_MAX.
xfs_chmod()
int xfs_chmod (const char * path, mode_t mode, struct fuse_file_info * fi)
Definition at line 167 of file xrootdfs_meta.c.
References brix_fuse_op_chmod(), brix_status_clear(), g_web, brix_fuse_ctx_chmod::mode, brix_fuse_ctx_chmod::path, srv_path(), xfs_meta(), and XRDC_PATH_MAX.
xfs_chown()
int xfs_chown (const char * path, uid_t uid, gid_t gid, struct fuse_file_info * fi)
Definition at line 211 of file xrootdfs_meta.c.
References brix_fuse_op_setattr(), brix_status_clear(), g_ext_setattr, g_web, brix_fuse_ctx_setattr::gid, brix_fuse_ctx_setattr::path, brix_fuse_ctx_setattr::set_owner, srv_path(), brix_fuse_ctx_setattr::uid, xfs_meta(), and XRDC_PATH_MAX.
xfs_getattr()
int xfs_getattr (const char * path, struct stat * stbuf, struct fuse_file_info * fi)
Definition at line 35 of file xrootdfs_meta.c.
References brix_fuse_op_lstat(), brix_status_clear(), brix_web_stat(), g_bearer, g_web, g_web_ca, g_web_verify, g_weburl, getattr_from_open_writer(), brix_fuse_ctx_stat::path, brix_fuse_ctx_stat::si, srv_path(), xfs_err(), xfs_fill_stat(), xfs_meta(), and XRDC_PATH_MAX.
xfs_mkdir()
int xfs_mkdir (const char * path, mode_t mode)
Definition at line 114 of file xrootdfs_meta.c.
References brix_fuse_op_mkdir(), brix_status_clear(), g_web, brix_fuse_ctx_mkdir::mode, brix_fuse_ctx_mkdir::path, srv_path(), xfs_meta_idem(), and XRDC_PATH_MAX.
xfs_readdir()
int xfs_readdir (const char * path, void * buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info * fi, enum fuse_readdir_flags flags)
Definition at line 73 of file xrootdfs_meta.c.
References brix_fuse_op_dirlist(), brix_status_clear(), brix_web_readdir(), brix_fuse_ctx_dir::ents, g_bearer, g_web, g_web_ca, g_web_verify, g_weburl, brix_fuse_ctx_dir::n, name, brix_fuse_ctx_stat::path, brix_fuse_ctx_dir::path, srv_path(), stat(), xfs_err(), xfs_fill_stat(), xfs_meta(), and XRDC_PATH_MAX.
xfs_readlink()
int xfs_readlink (const char * path, char * buf, size_t size)
Definition at line 286 of file xrootdfs_meta.c.
References brix_backoff_sleep_fast(), brix_mono_ns(), brix_status_clear(), g_ext_readlink, g_max_retries, g_max_stall, g_web, srv_path(), xfs_err(), xfs_readlink_one_attempt(), and XRDC_PATH_MAX.
xfs_readlink_one_attempt()
static int xfs_readlink_one_attempt (const char * sp, char * buf, size_t size, brix_status * st) static
Definition at line 270 of file xrootdfs_meta.c.
References brix_pool_checkin(), brix_pool_checkout(), brix_readlink(), brix_status_retryable(), c, g_pool, and xfs_conn_healthy().
Referenced by xfs_readlink().
xfs_rename()
int xfs_rename (const char * from, const char * to, unsigned int flags)
Definition at line 150 of file xrootdfs_meta.c.
References brix_fuse_op_mv(), brix_status_clear(), brix_fuse_ctx_mv::from, g_web, srv_path(), brix_fuse_ctx_mv::to, xfs_meta_idem(), and XRDC_PATH_MAX.
xfs_rmdir()
int xfs_rmdir (const char * path)
Definition at line 138 of file xrootdfs_meta.c.
References brix_fuse_op_rmdir(), brix_status_clear(), g_web, brix_fuse_ctx_mkdir::path, srv_path(), xfs_meta_idem(), and XRDC_PATH_MAX.
xfs_statfs()
int xfs_statfs (const char * path, struct statvfs * stbuf)
Definition at line 317 of file xrootdfs_meta.c.
References brix_parse_qspace(), brix_status_clear(), g_web, op_qspace(), ctx_qspace::path, srv_path(), xfs_meta(), and XRDC_PATH_MAX.
xfs_symlink()
int xfs_symlink (const char * target, const char * linkpath)
Definition at line 232 of file xrootdfs_meta.c.
References brix_fuse_ctx_link2::a, brix_fuse_op_symlink(), brix_status_clear(), g_ext_symlink, g_web, srv_path(), xfs_meta_idem(), and XRDC_PATH_MAX.
xfs_truncate()
int xfs_truncate (const char * path, off_t size, struct fuse_file_info * fi)
Definition at line 179 of file xrootdfs_meta.c.
References brix_fuse_op_trunc(), brix_status_clear(), g_web, brix_fuse_ctx_trunc::path, brix_fuse_ctx_trunc::size, srv_path(), xfs_meta(), and XRDC_PATH_MAX.
xfs_unlink()
int xfs_unlink (const char * path)
Definition at line 126 of file xrootdfs_meta.c.
References brix_fuse_op_rm(), brix_status_clear(), g_web, brix_fuse_ctx_mkdir::path, srv_path(), xfs_meta_idem(), and XRDC_PATH_MAX.
xfs_utimens()
int xfs_utimens (const char * path, const struct timespec tv[2], struct fuse_file_info * fi)
Definition at line 194 of file xrootdfs_meta.c.
References brix_fuse_op_setattr(), brix_status_clear(), g_ext_setattr, g_web, brix_fuse_ctx_setattr::path, srv_path(), xfs_meta(), and XRDC_PATH_MAX.