nginx-xrootd: client/apps/fs/xrootdfs_xattr.c File Reference
xrootdfs_xattr.c File Reference
#include "xrootdfs_internal.h"
Functions
int op_qspace (brix_conn *c, void *v, brix_status *st)
const char * xfs_xattr_to_fattr (const char *name)
int op_cks (brix_conn *c, void *v, brix_status *st)
int op_faget (brix_conn *c, void *v, brix_status *st)
int xfs_getxattr (const char *path, const char *name, char *value, size_t size)
int op_faset (brix_conn *c, void *v, brix_status *st)
int xfs_setxattr (const char *path, const char *name, const char *value, size_t size, int flags)
int op_fadel (brix_conn *c, void *v, brix_status *st)
int xfs_removexattr (const char *path, const char *name)
int op_falist (brix_conn *c, void *v, brix_status *st)
int xfs_listxattr (const char *path, char *list, size_t size)
Function Documentation
op_cks()
int op_cks (brix_conn * c, void * v, brix_status * st)
Definition at line 24 of file xrootdfs_xattr.c.
References ctx_cks::algo, brix_query_cksum(), c, ctx_cks::hex, ctx_cks::hexsz, and ctx_cks::path.
Referenced by xfs_getxattr().
op_fadel()
int op_fadel (brix_conn * c, void * v, brix_status * st)
Definition at line 118 of file xrootdfs_xattr.c.
References brix_fattr_del(), c, ctx_fadel::name, and ctx_fadel::path.
Referenced by xfs_removexattr().
op_faget()
int op_faget (brix_conn * c, void * v, brix_status * st)
Definition at line 28 of file xrootdfs_xattr.c.
References brix_fattr_get(), ctx_faget::bufsz, c, ctx_faget::name, ctx_faget::path, ctx_faget::val, and ctx_faget::vlen.
Referenced by xfs_getxattr().
op_falist()
int op_falist (brix_conn * c, void * v, brix_status * st)
Definition at line 145 of file xrootdfs_xattr.c.
References brix_fattr_list(), c, ctx_falist::path, ctx_falist::raw, ctx_falist::rawlen, and ctx_falist::rawsz.
Referenced by xfs_listxattr().
op_faset()
int op_faset (brix_conn * c, void * v, brix_status * st)
Definition at line 89 of file xrootdfs_xattr.c.
References brix_fattr_set(), c, ctx_faset::create_only, ctx_faset::name, ctx_faset::path, ctx_faset::val, and ctx_faset::vlen.
Referenced by xfs_setxattr().
op_qspace()
int op_qspace (brix_conn * c, void * v, brix_status * st)
Definition at line 8 of file xrootdfs_xattr.c.
References brix_query(), c, kXR_Qspace, ctx_qspace::out, ctx_qspace::outsz, and ctx_qspace::path.
Referenced by xfs_statfs().
xfs_getxattr()
int xfs_getxattr (const char * path, const char * name, char * value, size_t size)
Definition at line 33 of file xrootdfs_xattr.c.
References ctx_cks::algo, brix_status_clear(), g_web, g_xattr, hex(), name, op_cks(), op_faget(), ctx_cks::path, ctx_faget::path, srv_path(), ctx_faget::vlen, XFS_CKS_XATTR_PFX, xfs_meta(), xfs_xattr_to_fattr(), and XRDC_PATH_MAX.
xfs_listxattr()
int xfs_listxattr (const char * path, char * list, size_t size)
Definition at line 150 of file xrootdfs_xattr.c.
References brix_fattr_listxattr_xlate(), brix_status_clear(), g_web, g_xattr, op_falist(), ctx_falist::path, ctx_falist::raw, ctx_falist::rawlen, srv_path(), xfs_meta(), and XRDC_PATH_MAX.
xfs_removexattr()
int xfs_removexattr (const char * path, const char * name)
Definition at line 123 of file xrootdfs_xattr.c.
References brix_status_clear(), g_web, g_xattr, name, op_fadel(), ctx_fadel::path, srv_path(), XFS_CKS_XATTR_PFX, xfs_meta(), xfs_xattr_to_fattr(), and XRDC_PATH_MAX.
xfs_setxattr()
int xfs_setxattr (const char * path, const char * name, const char * value, size_t size, int flags)
Definition at line 94 of file xrootdfs_xattr.c.
References brix_status_clear(), g_web, g_xattr, name, op_faset(), ctx_faset::path, srv_path(), XFS_CKS_XATTR_PFX, xfs_meta(), xfs_xattr_to_fattr(), and XRDC_PATH_MAX.
xfs_xattr_to_fattr()
const char * xfs_xattr_to_fattr (const char * name)
Definition at line 15 of file xrootdfs_xattr.c.
References name.
Referenced by xfs_getxattr(), xfs_removexattr(), and xfs_setxattr().