nginx-xrootd: client/apps/fs/xrootdfs_legacy.c File Reference
xrootdfs_legacy.c File Reference
#include "brix.h"
#include "posix/posix_map.h"
#include "fs/iobuf.h"
#include "posix/fuse_ops.h"
#include "core/compat/crypto.h"
#include "protocols/root/protocol/open_flags.h"
#include <fuse3/fuse.h>
#include <errno.h>
#include <fcntl.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <sys/xattr.h>
Data Structures
struct xfs_handle
Macros
#define FUSE_USE_VERSION 31
#define XFS_CKS_XATTR_PFX "user.XrdCks."
Functions
static ssize_t xfs_io_pread (void *be, int64_t off, void *buf, size_t n, brix_status *st)
static int xfs_io_pwrite (void *be, int64_t off, const void *buf, size_t n, brix_status *st)
static int xfs_flush_wbuf (xfs_handle *h, brix_status *st)
static int xfs_conn_healthy (const brix_status *st)
static int xfs_err (const brix_status *st)
static void xfs_fill_stat (const brix_statinfo *si, struct stat *stbuf)
static int xfs_getattr (const char *path, struct stat *stbuf, struct fuse_file_info *fi)
static int xfs_readdir (const char *path, void *buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info *fi, enum fuse_readdir_flags flags)
static xfs_handle * xfs_handle_new (int *err)
static void xfs_handle_free (xfs_handle *h)
static int xfs_open (const char *path, struct fuse_file_info *fi)
static int xfs_create (const char *path, mode_t mode, struct fuse_file_info *fi)
static int xfs_read (const char *path, char *buf, size_t size, off_t offset, struct fuse_file_info *fi)
static int xfs_write (const char *path, const char *buf, size_t size, off_t offset, struct fuse_file_info *fi)
static int xfs_release (const char *path, struct fuse_file_info *fi)
static int xfs_flush (const char *path, struct fuse_file_info *fi)
static int xfs_fsync (const char *path, int datasync, struct fuse_file_info *fi)
static int xfs_mkdir (const char *path, mode_t mode)
static int xfs_unlink (const char *path)
static int xfs_rmdir (const char *path)
static int xfs_rename (const char *from, const char *to, unsigned int flags)
static int xfs_chmod (const char *path, mode_t mode, struct fuse_file_info *fi)
static int xfs_truncate (const char *path, off_t size, struct fuse_file_info *fi)
static int xfs_chown (const char *path, uid_t uid, gid_t gid, struct fuse_file_info *fi)
static int xfs_utimens (const char *path, const struct timespec tv[2], struct fuse_file_info *fi)
static int xfs_statfs (const char *path, struct statvfs *stbuf)
static int xfs_access (const char *path, int mask)
static const char * xfs_xattr_to_fattr (const char *name)
static int xfs_getxattr (const char *path, const char *name, char *value, size_t size)
static int xfs_setxattr (const char *path, const char *name, const char *value, size_t size, int flags)
static int xfs_removexattr (const char *path, const char *name)
static int xfs_listxattr (const char *path, char *list, size_t size)
static void * xfs_init (struct fuse_conn_info *conn, struct fuse_config *cfg)
static void usage (void)
static int xfs_opt_novalue (const char *a)
static int xfs_opt_value (const char *a, char *v)
static int xfs_parse_args (int argc, char **argv, char **fuse_argv, int *fuse_argc, const char **endpoint)
static int xfs_root_mount (int fuse_argc, char **fuse_argv, const char *endpoint)
int xrootdfs_legacy_main (int argc, char **argv)
Variables
static brix_pool * g_pool
static brix_url g_url
static brix_opts g_opts
static int g_max_conns = 8
static double g_attr_timeout = 1.0
static double g_entry_timeout = 1.0
static int g_kernel_cache = 0
static int g_xattr = 0
static size_t g_readahead = 1024 * 1024
static size_t g_writeback = 1024 * 1024
static const struct fuse_operations xfs_ops
Macro Definition Documentation
FUSE_USE_VERSION
#define FUSE_USE_VERSION 31
Definition at line 35 of file xrootdfs_legacy.c.
XFS_CKS_XATTR_PFX
#define XFS_CKS_XATTR_PFX "user.XrdCks."
Definition at line 80 of file xrootdfs_legacy.c.
Function Documentation
usage()
static void usage (void) static
Definition at line 740 of file xrootdfs_legacy.c.
Referenced by xfs_parse_args(), and xrootdfs_legacy_main().
xfs_access()
static int xfs_access (const char * path, int mask) static
Definition at line 510 of file xrootdfs_legacy.c.
References brix_pool_checkin(), brix_pool_checkout(), brix_stat(), brix_status_clear(), c, g_pool, brix_fuse_ctx_trunc::path, xfs_conn_healthy(), and xfs_err().
xfs_chmod()
static int xfs_chmod (const char * path, mode_t mode, struct fuse_file_info * fi) static
Definition at line 434 of file xrootdfs_legacy.c.
References brix_fuse_op_chmod(), brix_fuse_run(), brix_status_clear(), g_pool, brix_fuse_ctx_chmod::mode, and brix_fuse_ctx_chmod::path.
xfs_chown()
static int xfs_chown (const char * path, uid_t uid, gid_t gid, struct fuse_file_info * fi) static
Definition at line 455 of file xrootdfs_legacy.c.
References brix_fuse_ctx_trunc::path.
xfs_conn_healthy()
static int xfs_conn_healthy (const brix_status * st) static
Definition at line 120 of file xrootdfs_legacy.c.
References brix_fuse_conn_healthy().
Referenced by xfs_access(), xfs_getxattr(), xfs_listxattr(), xfs_removexattr(), xfs_setxattr(), and xfs_statfs().
xfs_create()
static int xfs_create (const char * path, mode_t mode, struct fuse_file_info * fi) static
Definition at line 269 of file xrootdfs_legacy.c.
References brix_iobuf_init(), brix_open_force_for_create(), brix_rfile_open_write(), brix_status_clear(), xfs_handle::conn, xfs_handle::f, g_readahead, g_writeback, xfs_handle::io, xfs_handle::writable, xfs_err(), xfs_handle_free(), xfs_handle_new(), xfs_io_pread(), and xfs_io_pwrite().
xfs_err()
static int xfs_err (const brix_status * st) static
Definition at line 126 of file xrootdfs_legacy.c.
References brix_fuse_errno().
Referenced by xfs_access(), xfs_create(), xfs_flush(), xfs_fsync(), xfs_getxattr(), xfs_handle_new(), xfs_listxattr(), xfs_open(), xfs_read(), xfs_removexattr(), xfs_setxattr(), xfs_statfs(), and xfs_write().
xfs_fill_stat()
static void xfs_fill_stat (const brix_statinfo * si, struct stat * stbuf) static
Definition at line 134 of file xrootdfs_legacy.c.
References brix_statinfo_to_stat().
Referenced by xfs_getattr(), and xfs_readdir().
xfs_flush()
static int xfs_flush (const char * path, struct fuse_file_info * fi) static
Definition at line 358 of file xrootdfs_legacy.c.
References brix_status_clear(), xfs_handle::lock, xfs_err(), and xfs_flush_wbuf().
xfs_flush_wbuf()
static int xfs_flush_wbuf (xfs_handle * h, brix_status * st) static
Definition at line 109 of file xrootdfs_legacy.c.
References brix_iobuf_flush(), and xfs_handle::io.
Referenced by xfs_flush(), xfs_fsync(), and xfs_release().
xfs_fsync()
static int xfs_fsync (const char * path, int datasync, struct fuse_file_info * fi) static
Definition at line 376 of file xrootdfs_legacy.c.
References brix_file_sync(), brix_status_clear(), xfs_handle::conn, xfs_handle::f, brix_rfile::f, xfs_handle::lock, xfs_err(), and xfs_flush_wbuf().
xfs_getattr()
static int xfs_getattr (const char * path, struct stat * stbuf, struct fuse_file_info * fi) static
Definition at line 142 of file xrootdfs_legacy.c.
References brix_fuse_op_stat(), brix_fuse_run(), brix_status_clear(), g_pool, brix_fuse_ctx_stat::path, brix_fuse_ctx_stat::si, and xfs_fill_stat().
xfs_getxattr()
static int xfs_getxattr (const char * path, const char * name, char * value, size_t size) static
Definition at line 544 of file xrootdfs_legacy.c.
References brix_fattr_get(), brix_pool_checkin(), brix_pool_checkout(), brix_query_cksum(), brix_status_clear(), c, g_pool, g_xattr, hex(), name, brix_fuse_ctx_trunc::path, brix_fuse_ctx_trunc::size, XFS_CKS_XATTR_PFX, xfs_conn_healthy(), xfs_err(), and xfs_xattr_to_fattr().
xfs_handle_free()
static void xfs_handle_free (xfs_handle * h) static
Definition at line 226 of file xrootdfs_legacy.c.
References brix_close(), brix_iobuf_dispose(), xfs_handle::conn, xfs_handle::io, and xfs_handle::lock.
Referenced by xfs_create(), xfs_open(), and xfs_release().
xfs_handle_new()
static xfs_handle * xfs_handle_new (int * err) static
Definition at line 205 of file xrootdfs_legacy.c.
References brix_connect(), brix_status_clear(), xfs_handle::conn, g_opts, g_url, xfs_handle::lock, and xfs_err().
Referenced by xfs_create(), and xfs_open().
xfs_init()
static void * xfs_init (struct fuse_conn_info * conn, struct fuse_config * cfg) static
Definition at line 699 of file xrootdfs_legacy.c.
References g_attr_timeout, g_entry_timeout, and g_kernel_cache.
xfs_io_pread()
static ssize_t xfs_io_pread (void * be, int64_t off, void * buf, size_t n, brix_status * st) static
Definition at line 95 of file xrootdfs_legacy.c.
References brix_rfile_pread(), and xfs_handle::f.
Referenced by xfs_create(), and xfs_open().
xfs_io_pwrite()
static int xfs_io_pwrite (void * be, int64_t off, const void * buf, size_t n, brix_status * st) static
Definition at line 101 of file xrootdfs_legacy.c.
References brix_rfile_pwrite(), and xfs_handle::f.
Referenced by xfs_create(), and xfs_open().
xfs_listxattr()
static int xfs_listxattr (const char * path, char * list, size_t size) static
Definition at line 666 of file xrootdfs_legacy.c.
References brix_fattr_list(), brix_fattr_listxattr_xlate(), brix_pool_checkin(), brix_pool_checkout(), brix_status_clear(), c, g_pool, g_xattr, brix_fuse_ctx_trunc::path, brix_fuse_ctx_trunc::size, xfs_conn_healthy(), and xfs_err().
xfs_mkdir()
static int xfs_mkdir (const char * path, mode_t mode) static
Definition at line 397 of file xrootdfs_legacy.c.
References brix_fuse_op_mkdir(), brix_fuse_run(), brix_status_clear(), g_pool, brix_fuse_ctx_mkdir::mode, and brix_fuse_ctx_mkdir::path.
xfs_open()
static int xfs_open (const char * path, struct fuse_file_info * fi) static
Definition at line 235 of file xrootdfs_legacy.c.
References brix_iobuf_init(), brix_open_force_for_open(), brix_rfile_open_read(), brix_rfile_open_write(), brix_status_clear(), xfs_handle::conn, xfs_handle::f, g_readahead, g_writeback, xfs_handle::io, xfs_handle::writable, xfs_err(), xfs_handle_free(), xfs_handle_new(), xfs_io_pread(), and xfs_io_pwrite().
xfs_opt_novalue()
static int xfs_opt_novalue (const char * a) static
Definition at line 772 of file xrootdfs_legacy.c.
References g_kernel_cache, g_opts, g_xattr, brix_opts::notlsok, brix_opts::verify_host, and brix_opts::want_tls.
Referenced by xfs_parse_args().
xfs_opt_value()
static int xfs_opt_value (const char * a, char * v) static
Definition at line 790 of file xrootdfs_legacy.c.
References brix_opts::auth_force, brix_tmo_set_connect_ms(), brix_tmo_set_io_ms(), g_attr_timeout, g_entry_timeout, g_max_conns, g_opts, g_readahead, and g_writeback.
Referenced by xfs_parse_args().
xfs_parse_args()
static int xfs_parse_args (int argc, char ** argv, char ** fuse_argv, int * fuse_argc, const char ** endpoint) static
Definition at line 825 of file xrootdfs_legacy.c.
References usage(), xfs_opt_novalue(), and xfs_opt_value().
Referenced by xrootdfs_legacy_main().
xfs_read()
static int xfs_read (const char * path, char * buf, size_t size, off_t offset, struct fuse_file_info * fi) static
Definition at line 297 of file xrootdfs_legacy.c.
References brix_iobuf_read(), brix_status_clear(), xfs_handle::io, xfs_handle::lock, and xfs_err().
xfs_readdir()
static int xfs_readdir (const char * path, void * buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info * fi, enum fuse_readdir_flags flags) static
Definition at line 166 of file xrootdfs_legacy.c.
References brix_fuse_op_dirlist(), brix_fuse_run(), brix_status_clear(), brix_fuse_ctx_dir::ents, g_pool, brix_fuse_ctx_dir::n, name, brix_fuse_ctx_dir::path, stat(), and xfs_fill_stat().
xfs_release()
static int xfs_release (const char * path, struct fuse_file_info * fi) static
Definition at line 336 of file xrootdfs_legacy.c.
References brix_rfile_close(), brix_status_clear(), xfs_handle::f, xfs_handle::lock, xfs_flush_wbuf(), and xfs_handle_free().
xfs_removexattr()
static int xfs_removexattr (const char * path, const char * name) static
Definition at line 638 of file xrootdfs_legacy.c.
References brix_fattr_del(), brix_pool_checkin(), brix_pool_checkout(), brix_status_clear(), c, g_pool, g_xattr, name, brix_fuse_ctx_trunc::path, XFS_CKS_XATTR_PFX, xfs_conn_healthy(), xfs_err(), and xfs_xattr_to_fattr().
xfs_rename()
static int xfs_rename (const char * from, const char * to, unsigned int flags) static
Definition at line 422 of file xrootdfs_legacy.c.
References brix_fuse_op_mv(), brix_fuse_run(), brix_status_clear(), brix_fuse_ctx_mv::from, g_pool, and brix_fuse_ctx_mv::to.
xfs_rmdir()
static int xfs_rmdir (const char * path) static
Definition at line 414 of file xrootdfs_legacy.c.
References brix_fuse_op_rmdir(), brix_fuse_run(), brix_status_clear(), g_pool, and brix_fuse_ctx_mkdir::path.
xfs_root_mount()
static int xfs_root_mount (int fuse_argc, char ** fuse_argv, const char * endpoint) static
Definition at line 858 of file xrootdfs_legacy.c.
References brix_endpoint_parse(), brix_pool_create(), brix_pool_destroy(), brix_shellcode(), brix_status_clear(), g_max_conns, g_opts, g_pool, g_url, brix_url::host, brix_status::msg, brix_url::port, and xfs_ops.
Referenced by xrootdfs_legacy_main().
xfs_setxattr()
static int xfs_setxattr (const char * path, const char * name, const char * value, size_t size, int flags) static
Definition at line 608 of file xrootdfs_legacy.c.
References brix_fattr_set(), brix_pool_checkin(), brix_pool_checkout(), brix_status_clear(), c, g_pool, g_xattr, name, brix_fuse_ctx_trunc::path, brix_fuse_ctx_trunc::size, XFS_CKS_XATTR_PFX, xfs_conn_healthy(), xfs_err(), and xfs_xattr_to_fattr().
xfs_statfs()
static int xfs_statfs (const char * path, struct statvfs * stbuf) static
Definition at line 472 of file xrootdfs_legacy.c.
References brix_parse_qspace(), brix_pool_checkin(), brix_pool_checkout(), brix_query(), brix_status_clear(), c, g_pool, kXR_Qspace, brix_fuse_ctx_trunc::path, xfs_conn_healthy(), and xfs_err().
xfs_truncate()
static int xfs_truncate (const char * path, off_t size, struct fuse_file_info * fi) static
Definition at line 444 of file xrootdfs_legacy.c.
References brix_fuse_op_trunc(), brix_fuse_run(), brix_status_clear(), g_pool, brix_fuse_ctx_trunc::path, and brix_fuse_ctx_trunc::size.
xfs_unlink()
static int xfs_unlink (const char * path) static
Definition at line 406 of file xrootdfs_legacy.c.
References brix_fuse_op_rm(), brix_fuse_run(), brix_status_clear(), g_pool, and brix_fuse_ctx_mkdir::path.
xfs_utimens()
static int xfs_utimens (const char * path, const struct timespec tv[2], struct fuse_file_info * fi) static
Definition at line 462 of file xrootdfs_legacy.c.
References brix_fuse_ctx_trunc::path.
xfs_write()
static int xfs_write (const char * path, const char * buf, size_t size, off_t offset, struct fuse_file_info * fi) static
Definition at line 317 of file xrootdfs_legacy.c.
References brix_iobuf_write(), brix_status_clear(), xfs_handle::io, xfs_handle::lock, xfs_handle::writable, and xfs_err().
xfs_xattr_to_fattr()
static const char * xfs_xattr_to_fattr (const char * name) static
Definition at line 535 of file xrootdfs_legacy.c.
References name.
Referenced by xfs_getxattr(), xfs_removexattr(), and xfs_setxattr().
xrootdfs_legacy_main()
int xrootdfs_legacy_main (int argc, char ** argv)
Definition at line 887 of file xrootdfs_legacy.c.
References brix_crypto_init(), g_opts, usage(), brix_opts::verify_host, xfs_parse_args(), and xfs_root_mount().
Referenced by main().
Variable Documentation
g_attr_timeout
double g_attr_timeout = 1.0 static
Definition at line 67 of file xrootdfs_legacy.c.
Referenced by xfs_init(), and xfs_opt_value().
g_entry_timeout
double g_entry_timeout = 1.0 static
Definition at line 68 of file xrootdfs_legacy.c.
Referenced by xfs_init(), and xfs_opt_value().
g_kernel_cache
int g_kernel_cache = 0 static
Definition at line 69 of file xrootdfs_legacy.c.
Referenced by xfs_init(), and xfs_opt_novalue().
g_max_conns
int g_max_conns = 8 static
Definition at line 61 of file xrootdfs_legacy.c.
Referenced by xfs_opt_value(), and xfs_root_mount().
g_opts
brix_opts g_opts static
Definition at line 60 of file xrootdfs_legacy.c.
Referenced by xfs_handle_new(), xfs_opt_novalue(), xfs_opt_value(), xfs_root_mount(), and xrootdfs_legacy_main().
g_pool
brix_pool* g_pool static
Definition at line 58 of file xrootdfs_legacy.c.
Referenced by xfs_access(), xfs_chmod(), xfs_getattr(), xfs_getxattr(), xfs_listxattr(), xfs_mkdir(), xfs_readdir(), xfs_removexattr(), xfs_rename(), xfs_rmdir(), xfs_root_mount(), xfs_setxattr(), xfs_statfs(), xfs_truncate(), and xfs_unlink().
g_readahead
size_t g_readahead = 1024 * 1024 static
Definition at line 75 of file xrootdfs_legacy.c.
Referenced by xfs_create(), xfs_open(), and xfs_opt_value().
g_url
brix_url g_url static
Definition at line 59 of file xrootdfs_legacy.c.
Referenced by xfs_handle_new(), and xfs_root_mount().
g_writeback
size_t g_writeback = 1024 * 1024 static
Definition at line 76 of file xrootdfs_legacy.c.
Referenced by xfs_create(), xfs_open(), and xfs_opt_value().
g_xattr
int g_xattr = 0 static
Definition at line 70 of file xrootdfs_legacy.c.
Referenced by xfs_getxattr(), xfs_listxattr(), xfs_opt_novalue(), xfs_removexattr(), and xfs_setxattr().
xfs_ops
const struct fuse_operations xfs_ops static
Initial value:
= {
    .init     = xfs_init,
    .getattr  = xfs_getattr,
    .readdir  = xfs_readdir,
    .open     = xfs_open,
    .create   = xfs_create,
    .read     = xfs_read,
    .write    = xfs_write,
    .flush    = xfs_flush,
    .release  = xfs_release,
    .fsync    = xfs_fsync,
    .mkdir    = xfs_mkdir,
    .unlink   = xfs_unlink,
    .rmdir    = xfs_rmdir,
    .rename   = xfs_rename,
    .chmod    = xfs_chmod,
    .truncate = xfs_truncate,
    .chown    = xfs_chown,
    .utimens  = xfs_utimens,
    .statfs   = xfs_statfs,
    .access   = xfs_access,
    .getxattr    = xfs_getxattr,
    .setxattr    = xfs_setxattr,
    .listxattr   = xfs_listxattr,
    .removexattr = xfs_removexattr,
}
Definition at line 710 of file xrootdfs_legacy.c.
Referenced by xfs_root_mount().