nginx-xrootd: client/apps/fs/xrootdfs_io.c File Reference
xrootdfs_io.c File Reference
#include "xrootdfs_internal.h"
Functions
ssize_t afh_pread (afh *h, int64_t off, void *buf, size_t len, brix_status *st)
ssize_t afh_io_pread (void *be, int64_t off, void *buf, size_t n, brix_status *st)
int afh_io_pwrite (void *be, int64_t off, const void *buf, size_t n, brix_status *st)
int afh_flush_wbuf (afh *h, brix_status *st)
void afh_free (afh *h)
int afh_open (const char *path, int writable, int force, struct fuse_file_info *fi)
int xfs_open (const char *path, struct fuse_file_info *fi)
int xfs_create (const char *path, mode_t mode, struct fuse_file_info *fi)
int xfs_read (const char *path, char *buf, size_t size, off_t offset, struct fuse_file_info *fi)
int xfs_write (const char *path, const char *buf, size_t size, off_t offset, struct fuse_file_info *fi)
int xfs_flush (const char *path, struct fuse_file_info *fi)
int xfs_fsync (const char *path, int datasync, struct fuse_file_info *fi)
int xfs_release (const char *path, struct fuse_file_info *fi)
Function Documentation
afh_flush_wbuf()
int afh_flush_wbuf (afh * h, brix_status * st)
Definition at line 39 of file xrootdfs_io.c.
References brix_iobuf_flush(), and afh::io.
Referenced by xfs_flush(), xfs_fsync(), and xfs_release().
afh_free()
void afh_free (afh * h)
Definition at line 46 of file xrootdfs_io.c.
References brix_iobuf_dispose(), afh::io, and afh::lock.
Referenced by afh_open(), and xfs_release().
afh_io_pread()
ssize_t afh_io_pread (void * be, int64_t off, void * buf, size_t n, brix_status * st)
Definition at line 25 of file xrootdfs_io.c.
References afh_pread().
Referenced by afh_open().
afh_io_pwrite()
int afh_io_pwrite (void * be, int64_t off, const void * buf, size_t n, brix_status * st)
Definition at line 31 of file xrootdfs_io.c.
References brix_mfile_pwrite().
Referenced by afh_open().
afh_open()
int afh_open (const char * path, int writable, int force, struct fuse_file_info * fi)
Definition at line 56 of file xrootdfs_io.c.
References afh_free(), afh_io_pread(), afh_io_pwrite(), brix_iobuf_init(), brix_mfile_open(), brix_mgr_pick(), brix_status_clear(), brix_webfile_open(), g_bearer, g_compress, g_max_retries, g_max_stall, g_mgr, g_readahead, g_web, g_web_ca, g_web_verify, g_weburl, g_writeback, afh::io, afh::lock, afh::mf, srv_path(), afh::wf, afh::writable, xfs_err(), and XRDC_PATH_MAX.
Referenced by xfs_create(), and xfs_open().
afh_pread()
ssize_t afh_pread (afh * h, int64_t off, void * buf, size_t len, brix_status * st)
Definition at line 13 of file xrootdfs_io.c.
References brix_mfile_pread(), brix_webfile_pread(), afh::mf, and afh::wf.
Referenced by afh_io_pread().
xfs_create()
int xfs_create (const char * path, mode_t mode, struct fuse_file_info * fi)
Definition at line 123 of file xrootdfs_io.c.
References afh_open(), and brix_open_force_for_create().
xfs_flush()
int xfs_flush (const char * path, struct fuse_file_info * fi)
Definition at line 176 of file xrootdfs_io.c.
References afh_flush_wbuf(), brix_status_clear(), g_web, afh::lock, and xfs_err().
xfs_fsync()
int xfs_fsync (const char * path, int datasync, struct fuse_file_info * fi)
Definition at line 195 of file xrootdfs_io.c.
References afh_flush_wbuf(), brix_mfile_sync(), brix_status_clear(), g_web, afh::lock, afh::mf, and xfs_err().
xfs_open()
int xfs_open (const char * path, struct fuse_file_info * fi)
Definition at line 111 of file xrootdfs_io.c.
References afh_open(), and brix_open_force_for_open().
xfs_read()
int xfs_read (const char * path, char * buf, size_t size, off_t offset, struct fuse_file_info * fi)
Definition at line 132 of file xrootdfs_io.c.
References brix_iobuf_read(), brix_status_clear(), afh::io, afh::lock, and xfs_err().
xfs_release()
int xfs_release (const char * path, struct fuse_file_info * fi)
Definition at line 217 of file xrootdfs_io.c.
References afh_flush_wbuf(), afh_free(), brix_mfile_close(), brix_status_clear(), brix_webfile_close(), afh::lock, afh::mf, and afh::wf.
xfs_write()
int xfs_write (const char * path, const char * buf, size_t size, off_t offset, struct fuse_file_info * fi)
Definition at line 152 of file xrootdfs_io.c.
References brix_iobuf_write(), brix_status_clear(), g_web, afh::io, afh::lock, afh::writable, afh::wsize, and xfs_err().