nginx-xrootd: client/apps/fs/xrootdfs_drivers.h File Reference
xrootdfs_drivers.h File Reference
Functions
int xrootdfs_aio_main (int argc, char **argv)
int xrootdfs_legacy_main (int argc, char **argv)
Function Documentation
xrootdfs_aio_main()
int xrootdfs_aio_main (int argc, char ** argv)
Definition at line 251 of file xrootdfs.c.
xrootdfs_legacy_main()
int xrootdfs_legacy_main (int argc, char ** argv)
Definition at line 767 of file xrootdfs_legacy.c.
References brix_opts::auth_force, brix_crypto_init(), brix_endpoint_parse(), brix_pool_create(), brix_pool_destroy(), brix_shellcode(), brix_status_clear(), brix_tmo_set_connect_ms(), brix_tmo_set_io_ms(), g_attr_timeout, g_entry_timeout, g_kernel_cache, g_max_conns, g_opts, g_pool, g_readahead, g_url, g_writeback, g_xattr, brix_url::host, brix_status::msg, brix_opts::notlsok, brix_url::port, usage(), brix_opts::verify_host, brix_opts::want_tls, and xfs_ops.
Referenced by main().