nginx-xrootd: client/apps/fs/xrootdfs_internal.h File Reference
xrootdfs_internal.h File Reference
#include "brix.h"
#include "core/aio/aio.h"
#include "posix/posix_map.h"
#include "fs/iobuf.h"
#include "posix/fuse_ops.h"
#include "core/compat/crypto.h"
#include "protocols/root/protocol/open_flags.h"
#include <fuse3/fuse.h>
#include <errno.h>
#include <fcntl.h>
#include <pthread.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <sys/xattr.h>
Data Structures
struct afh
struct ctx_qspace
struct ctx_cks
struct ctx_faget
struct ctx_faset
struct ctx_fadel
struct ctx_falist
Macros
#define FUSE_USE_VERSION 31
#define XFS_CKS_XATTR_PFX "user.XrdCks."
Functions
const char * srv_path (const char *p, char *buf, size_t sz)
int xfs_err (const brix_status *st)
int xfs_conn_healthy (const brix_status *st)
int xfs_meta (brix_fuse_op_fn fn, void *ctx, brix_status *st)
int xfs_meta_idem (brix_fuse_op_fn fn, void *ctx, int benign_errno, brix_status *st)
void xfs_fill_stat (const brix_statinfo *si, struct stat *stbuf)
int xfs_getattr (const char *path, struct stat *stbuf, struct fuse_file_info *fi)
int xfs_readdir (const char *path, void *buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info *fi, enum fuse_readdir_flags flags)
int xfs_mkdir (const char *path, mode_t mode)
int xfs_unlink (const char *path)
int xfs_rmdir (const char *path)
int xfs_rename (const char *from, const char *to, unsigned int flags)
int xfs_chmod (const char *path, mode_t mode, struct fuse_file_info *fi)
int xfs_truncate (const char *path, off_t size, struct fuse_file_info *fi)
int xfs_utimens (const char *path, const struct timespec tv[2], struct fuse_file_info *fi)
int xfs_chown (const char *path, uid_t uid, gid_t gid, struct fuse_file_info *fi)
int xfs_symlink (const char *target, const char *linkpath)
int xfs_link (const char *from, const char *to)
int xfs_readlink (const char *path, char *buf, size_t size)
int op_qspace (brix_conn *c, void *v, brix_status *st)
int xfs_statfs (const char *path, struct statvfs *stbuf)
int xfs_access (const char *path, int mask)
ssize_t afh_pread (afh *h, int64_t off, void *buf, size_t len, brix_status *st)
ssize_t afh_io_pread (void *be, int64_t off, void *buf, size_t n, brix_status *st)
int afh_io_pwrite (void *be, int64_t off, const void *buf, size_t n, brix_status *st)
int afh_flush_wbuf (afh *h, brix_status *st)
void afh_free (afh *h)
int afh_open (const char *path, int writable, int force, struct fuse_file_info *fi)
int xfs_open (const char *path, struct fuse_file_info *fi)
int xfs_create (const char *path, mode_t mode, struct fuse_file_info *fi)
int xfs_read (const char *path, char *buf, size_t size, off_t offset, struct fuse_file_info *fi)
int xfs_write (const char *path, const char *buf, size_t size, off_t offset, struct fuse_file_info *fi)
int xfs_flush (const char *path, struct fuse_file_info *fi)
int xfs_fsync (const char *path, int datasync, struct fuse_file_info *fi)
int xfs_release (const char *path, struct fuse_file_info *fi)
const char * xfs_xattr_to_fattr (const char *name)
int op_cks (brix_conn *c, void *v, brix_status *st)
int op_faget (brix_conn *c, void *v, brix_status *st)
int xfs_getxattr (const char *path, const char *name, char *value, size_t size)
int xfs_setxattr (const char *path, const char *name, const char *value, size_t size, int flags)
int op_faset (brix_conn *c, void *v, brix_status *st)
int op_fadel (brix_conn *c, void *v, brix_status *st)
int xfs_removexattr (const char *path, const char *name)
int op_falist (brix_conn *c, void *v, brix_status *st)
int xfs_listxattr (const char *path, char *list, size_t size)
void * xfs_init (struct fuse_conn_info *conn, struct fuse_config *cfg)
void usage (void)
Variables
const struct fuse_operations xfs_ops
double g_attr_timeout
char g_base [XRDC_PATH_MAX]
const char * g_bearer
char g_compress [32]
double g_entry_timeout
int g_ext_link
int g_ext_readlink
int g_ext_setattr
int g_ext_symlink
int g_keepalive
int g_kernel_cache
int g_max_conns
int g_max_retries
int g_max_stall
brix_mgr * g_mgr
brix_opts g_opts
brix_pool * g_pool
size_t g_readahead
int g_streams
brix_url g_url
int g_web
const char * g_web_ca
int g_web_verify
brix_weburl g_weburl
size_t g_writeback
int g_xattr
Macro Definition Documentation
FUSE_USE_VERSION
#define FUSE_USE_VERSION 31
Definition at line 8 of file xrootdfs_internal.h.
XFS_CKS_XATTR_PFX
#define XFS_CKS_XATTR_PFX "user.XrdCks."
Definition at line 28 of file xrootdfs_internal.h.
Function Documentation
afh_flush_wbuf()
int afh_flush_wbuf (afh * h, brix_status * st)
Definition at line 39 of file xrootdfs_io.c.
References brix_iobuf_flush(), and afh::io.
Referenced by xfs_flush(), xfs_fsync(), and xfs_release().
afh_free()
void afh_free (afh * h)
Definition at line 46 of file xrootdfs_io.c.
References brix_iobuf_dispose(), afh::io, and afh::lock.
Referenced by afh_open(), and xfs_release().
afh_io_pread()
ssize_t afh_io_pread (void * be, int64_t off, void * buf, size_t n, brix_status * st)
Definition at line 25 of file xrootdfs_io.c.
References afh_pread().
Referenced by afh_open().
afh_io_pwrite()
int afh_io_pwrite (void * be, int64_t off, const void * buf, size_t n, brix_status * st)
Definition at line 31 of file xrootdfs_io.c.
References brix_mfile_pwrite().
Referenced by afh_open().
afh_open()
int afh_open (const char * path, int writable, int force, struct fuse_file_info * fi)
Definition at line 56 of file xrootdfs_io.c.
References afh_free(), afh_io_pread(), afh_io_pwrite(), brix_iobuf_init(), brix_mfile_open(), brix_mgr_pick(), brix_status_clear(), brix_webfile_open(), g_bearer, g_compress, g_max_retries, g_max_stall, g_mgr, g_readahead, g_web, g_web_ca, g_web_verify, g_weburl, g_writeback, afh::io, afh::lock, afh::mf, srv_path(), afh::wf, afh::writable, xfs_err(), and XRDC_PATH_MAX.
Referenced by xfs_create(), and xfs_open().
afh_pread()
ssize_t afh_pread (afh * h, int64_t off, void * buf, size_t len, brix_status * st)
Definition at line 13 of file xrootdfs_io.c.
References brix_mfile_pread(), brix_webfile_pread(), afh::mf, and afh::wf.
Referenced by afh_io_pread().
op_cks()
int op_cks (brix_conn * c, void * v, brix_status * st)
Definition at line 24 of file xrootdfs_xattr.c.
References ctx_cks::algo, brix_query_cksum(), c, ctx_cks::hex, ctx_cks::hexsz, and ctx_cks::path.
Referenced by xfs_getxattr().
op_fadel()
int op_fadel (brix_conn * c, void * v, brix_status * st)
Definition at line 118 of file xrootdfs_xattr.c.
References brix_fattr_del(), c, ctx_fadel::name, and ctx_fadel::path.
Referenced by xfs_removexattr().
op_faget()
int op_faget (brix_conn * c, void * v, brix_status * st)
Definition at line 28 of file xrootdfs_xattr.c.
References brix_fattr_get(), ctx_faget::bufsz, c, ctx_faget::name, ctx_faget::path, ctx_faget::val, and ctx_faget::vlen.
Referenced by xfs_getxattr().
op_falist()
int op_falist (brix_conn * c, void * v, brix_status * st)
Definition at line 145 of file xrootdfs_xattr.c.
References brix_fattr_list(), c, ctx_falist::path, ctx_falist::raw, ctx_falist::rawlen, and ctx_falist::rawsz.
Referenced by xfs_listxattr().
op_faset()
int op_faset (brix_conn * c, void * v, brix_status * st)
Definition at line 89 of file xrootdfs_xattr.c.
References brix_fattr_set(), c, ctx_faset::create_only, ctx_faset::name, ctx_faset::path, ctx_faset::val, and ctx_faset::vlen.
Referenced by xfs_setxattr().
op_qspace()
int op_qspace (brix_conn * c, void * v, brix_status * st)
Definition at line 8 of file xrootdfs_xattr.c.
References brix_query(), c, kXR_Qspace, ctx_qspace::out, ctx_qspace::outsz, and ctx_qspace::path.
Referenced by xfs_statfs().
srv_path()
const char * srv_path (const char * p, char * buf, size_t sz)
Definition at line 92 of file xrootdfs.c.
References g_base.
Referenced by afh_open(), xfs_access(), xfs_chmod(), xfs_chown(), xfs_getattr(), xfs_getxattr(), xfs_link(), xfs_listxattr(), xfs_mkdir(), xfs_readdir(), xfs_readlink(), xfs_removexattr(), xfs_rename(), xfs_rmdir(), xfs_setxattr(), xfs_statfs(), xfs_symlink(), xfs_truncate(), xfs_unlink(), and xfs_utimens().
usage()
void usage (void)
Definition at line 78 of file xrdcp.c.
References usage_fp(), usage_fp(), usage_fp(), usage_fp(), and usage_fp().
Referenced by main(), and xrootdfs_aio_main().
xfs_access()
int xfs_access (const char * path, int mask)
Definition at line 319 of file xrootdfs_meta.c.
References brix_fuse_op_stat(), brix_status_clear(), g_web, ctx_qspace::path, brix_fuse_ctx_stat::path, brix_fuse_ctx_stat::si, srv_path(), xfs_meta(), and XRDC_PATH_MAX.
xfs_chmod()
int xfs_chmod (const char * path, mode_t mode, struct fuse_file_info * fi)
Definition at line 167 of file xrootdfs_meta.c.
References brix_fuse_op_chmod(), brix_status_clear(), g_web, mode, brix_fuse_ctx_chmod::path, srv_path(), xfs_meta(), and XRDC_PATH_MAX.
xfs_chown()
int xfs_chown (const char * path, uid_t uid, gid_t gid, struct fuse_file_info * fi)
Definition at line 211 of file xrootdfs_meta.c.
References brix_fuse_op_setattr(), brix_status_clear(), g_ext_setattr, g_web, brix_fuse_ctx_setattr::gid, brix_fuse_ctx_setattr::path, brix_fuse_ctx_setattr::set_owner, srv_path(), brix_fuse_ctx_setattr::uid, xfs_meta(), and XRDC_PATH_MAX.
xfs_conn_healthy()
int xfs_conn_healthy (const brix_status * st)
Definition at line 138 of file xrootdfs.c.
References brix_fuse_conn_healthy().
Referenced by xfs_readlink(), and xrootdfs_aio_main().
xfs_create()
int xfs_create (const char * path, mode_t mode, struct fuse_file_info * fi)
Definition at line 123 of file xrootdfs_io.c.
References afh_open(), brix_open_force_for_create(), and mode.
xfs_err()
int xfs_err (const brix_status * st)
Definition at line 131 of file xrootdfs.c.
References brix_fuse_errno().
Referenced by afh_open(), xfs_flush(), xfs_fsync(), xfs_getattr(), xfs_read(), xfs_readdir(), xfs_readlink(), and xfs_write().
xfs_fill_stat()
void xfs_fill_stat (const brix_statinfo * si, struct stat * stbuf)
Definition at line 165 of file xrootdfs.c.
References brix_statinfo_to_stat().
Referenced by xfs_getattr(), and xfs_readdir().
xfs_flush()
int xfs_flush (const char * path, struct fuse_file_info * fi)
Definition at line 176 of file xrootdfs_io.c.
References afh_flush_wbuf(), brix_status_clear(), g_web, afh::lock, and xfs_err().
xfs_fsync()
int xfs_fsync (const char * path, int datasync, struct fuse_file_info * fi)
Definition at line 195 of file xrootdfs_io.c.
References afh_flush_wbuf(), brix_mfile_sync(), brix_status_clear(), g_web, afh::lock, afh::mf, and xfs_err().
xfs_getattr()
int xfs_getattr (const char * path, struct stat * stbuf, struct fuse_file_info * fi)
Definition at line 35 of file xrootdfs_meta.c.
References brix_fuse_op_lstat(), brix_status_clear(), brix_web_stat(), g_bearer, g_web, g_web_ca, g_web_verify, g_weburl, getattr_from_open_writer(), brix_fuse_ctx_stat::path, brix_fuse_ctx_stat::si, srv_path(), xfs_err(), xfs_fill_stat(), xfs_meta(), and XRDC_PATH_MAX.
xfs_getxattr()
int xfs_getxattr (const char * path, const char * name, char * value, size_t size)
Definition at line 33 of file xrootdfs_xattr.c.
References ctx_cks::algo, brix_status_clear(), g_web, g_xattr, hex(), name, op_cks(), op_faget(), ctx_cks::path, ctx_faget::path, srv_path(), ctx_faget::vlen, XFS_CKS_XATTR_PFX, xfs_meta(), xfs_xattr_to_fattr(), and XRDC_PATH_MAX.
xfs_init()
void * xfs_init (struct fuse_conn_info * conn, struct fuse_config * cfg)
Definition at line 188 of file xrootdfs.c.
References g_attr_timeout, g_entry_timeout, and g_kernel_cache.
xfs_link()
int xfs_link (const char * from, const char * to)
Definition at line 173 of file xrootdfs.c.
References brix_fuse_ctx_link2::a, brix_fuse_op_link(), brix_status_clear(), g_ext_link, g_web, srv_path(), xfs_meta_idem(), and XRDC_PATH_MAX.
xfs_listxattr()
int xfs_listxattr (const char * path, char * list, size_t size)
Definition at line 150 of file xrootdfs_xattr.c.
References brix_fattr_listxattr_xlate(), brix_status_clear(), g_web, g_xattr, op_falist(), ctx_falist::path, ctx_falist::raw, ctx_falist::rawlen, srv_path(), xfs_meta(), and XRDC_PATH_MAX.
xfs_meta()
int xfs_meta (brix_fuse_op_fn fn, void * ctx, brix_status * st)
Definition at line 145 of file xrootdfs.c.
References brix_fuse_run(), fn, g_max_retries, g_max_stall, and g_pool.
Referenced by xfs_access(), xfs_chmod(), xfs_chown(), xfs_getattr(), xfs_getxattr(), xfs_listxattr(), xfs_readdir(), xfs_removexattr(), xfs_setxattr(), xfs_statfs(), xfs_truncate(), and xfs_utimens().
xfs_meta_idem()
int xfs_meta_idem (brix_fuse_op_fn fn, void * ctx, int benign_errno, brix_status * st)
Definition at line 157 of file xrootdfs.c.
References brix_fuse_run(), fn, g_max_retries, g_max_stall, and g_pool.
Referenced by xfs_link(), xfs_mkdir(), xfs_rename(), xfs_rmdir(), xfs_symlink(), and xfs_unlink().
xfs_mkdir()
int xfs_mkdir (const char * path, mode_t mode)
Definition at line 114 of file xrootdfs_meta.c.
References brix_fuse_op_mkdir(), brix_status_clear(), g_web, mode, brix_fuse_ctx_mkdir::path, srv_path(), xfs_meta_idem(), and XRDC_PATH_MAX.
xfs_open()
int xfs_open (const char * path, struct fuse_file_info * fi)
Definition at line 111 of file xrootdfs_io.c.
References afh_open(), and brix_open_force_for_open().
xfs_read()
int xfs_read (const char * path, char * buf, size_t size, off_t offset, struct fuse_file_info * fi)
Definition at line 132 of file xrootdfs_io.c.
References brix_iobuf_read(), brix_status_clear(), afh::io, afh::lock, and xfs_err().
xfs_readdir()
int xfs_readdir (const char * path, void * buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info * fi, enum fuse_readdir_flags flags)
Definition at line 73 of file xrootdfs_meta.c.
References brix_fuse_op_dirlist(), brix_status_clear(), brix_web_readdir(), brix_fuse_ctx_dir::ents, g_bearer, g_web, g_web_ca, g_web_verify, g_weburl, brix_fuse_ctx_dir::n, name, brix_fuse_ctx_stat::path, brix_fuse_ctx_dir::path, srv_path(), stat(), xfs_err(), xfs_fill_stat(), xfs_meta(), and XRDC_PATH_MAX.
xfs_readlink()
int xfs_readlink (const char * path, char * buf, size_t size)
Definition at line 249 of file xrootdfs_meta.c.
References brix_backoff_sleep_fast(), brix_mono_ns(), brix_pool_checkin(), brix_pool_checkout(), brix_readlink(), brix_status_clear(), brix_status_retryable(), c, g_ext_readlink, g_max_retries, g_max_stall, g_pool, g_web, srv_path(), xfs_conn_healthy(), xfs_err(), and XRDC_PATH_MAX.
xfs_release()
int xfs_release (const char * path, struct fuse_file_info * fi)
Definition at line 217 of file xrootdfs_io.c.
References afh_flush_wbuf(), afh_free(), brix_mfile_close(), brix_status_clear(), brix_webfile_close(), afh::lock, afh::mf, and afh::wf.
xfs_removexattr()
int xfs_removexattr (const char * path, const char * name)
Definition at line 123 of file xrootdfs_xattr.c.
References brix_status_clear(), g_web, g_xattr, name, op_fadel(), ctx_fadel::path, srv_path(), XFS_CKS_XATTR_PFX, xfs_meta(), xfs_xattr_to_fattr(), and XRDC_PATH_MAX.
xfs_rename()
int xfs_rename (const char * from, const char * to, unsigned int flags)
Definition at line 150 of file xrootdfs_meta.c.
References brix_fuse_op_mv(), brix_status_clear(), brix_fuse_ctx_mv::from, g_web, srv_path(), brix_fuse_ctx_mv::to, xfs_meta_idem(), and XRDC_PATH_MAX.
xfs_rmdir()
int xfs_rmdir (const char * path)
Definition at line 138 of file xrootdfs_meta.c.
References brix_fuse_op_rmdir(), brix_status_clear(), g_web, brix_fuse_ctx_mkdir::path, srv_path(), xfs_meta_idem(), and XRDC_PATH_MAX.
xfs_setxattr()
int xfs_setxattr (const char * path, const char * name, const char * value, size_t size, int flags)
Definition at line 94 of file xrootdfs_xattr.c.
References brix_status_clear(), g_web, g_xattr, name, op_faset(), ctx_faset::path, srv_path(), XFS_CKS_XATTR_PFX, xfs_meta(), xfs_xattr_to_fattr(), and XRDC_PATH_MAX.
xfs_statfs()
int xfs_statfs (const char * path, struct statvfs * stbuf)
Definition at line 286 of file xrootdfs_meta.c.
References brix_parse_qspace(), brix_status_clear(), g_web, op_qspace(), ctx_qspace::path, srv_path(), xfs_meta(), and XRDC_PATH_MAX.
xfs_symlink()
int xfs_symlink (const char * target, const char * linkpath)
Definition at line 232 of file xrootdfs_meta.c.
References brix_fuse_ctx_link2::a, brix_fuse_op_symlink(), brix_status_clear(), g_ext_symlink, g_web, srv_path(), xfs_meta_idem(), and XRDC_PATH_MAX.
xfs_truncate()
int xfs_truncate (const char * path, off_t size, struct fuse_file_info * fi)
Definition at line 179 of file xrootdfs_meta.c.
References brix_fuse_op_trunc(), brix_status_clear(), g_web, brix_fuse_ctx_trunc::path, brix_fuse_ctx_trunc::size, srv_path(), xfs_meta(), and XRDC_PATH_MAX.
xfs_unlink()
int xfs_unlink (const char * path)
Definition at line 126 of file xrootdfs_meta.c.
References brix_fuse_op_rm(), brix_status_clear(), g_web, brix_fuse_ctx_mkdir::path, srv_path(), xfs_meta_idem(), and XRDC_PATH_MAX.
xfs_utimens()
int xfs_utimens (const char * path, const struct timespec tv[2], struct fuse_file_info * fi)
Definition at line 194 of file xrootdfs_meta.c.
References brix_fuse_op_setattr(), brix_status_clear(), g_ext_setattr, g_web, brix_fuse_ctx_setattr::path, srv_path(), xfs_meta(), and XRDC_PATH_MAX.
xfs_write()
int xfs_write (const char * path, const char * buf, size_t size, off_t offset, struct fuse_file_info * fi)
Definition at line 152 of file xrootdfs_io.c.
References brix_iobuf_write(), brix_status_clear(), g_web, afh::io, afh::lock, afh::writable, afh::wsize, and xfs_err().
xfs_xattr_to_fattr()
const char * xfs_xattr_to_fattr (const char * name)
Definition at line 15 of file xrootdfs_xattr.c.
References name.
Referenced by xfs_getxattr(), xfs_removexattr(), and xfs_setxattr().
Variable Documentation
g_attr_timeout
double g_attr_timeout extern
Definition at line 29 of file xrootdfs.c.
Referenced by xfs_init(), and xrootdfs_aio_main().
g_base
char g_base[XRDC_PATH_MAX] extern
Definition at line 85 of file xrootdfs.c.
Referenced by srv_path(), and xrootdfs_aio_main().
g_bearer
const char* g_bearer extern
Definition at line 82 of file xrootdfs.c.
Referenced by afh_open(), xfs_getattr(), xfs_readdir(), and xrootdfs_aio_main().
g_compress
char g_compress[32] extern
Definition at line 37 of file xrootdfs.c.
Referenced by afh_open(), and xrootdfs_aio_main().
g_entry_timeout
double g_entry_timeout extern
Definition at line 31 of file xrootdfs.c.
Referenced by xfs_init(), and xrootdfs_aio_main().
g_ext_link
int g_ext_link extern
Definition at line 45 of file xrootdfs.c.
Referenced by xfs_link(), and xrootdfs_aio_main().
g_ext_readlink
int g_ext_readlink extern
Definition at line 43 of file xrootdfs.c.
Referenced by xfs_readlink(), and xrootdfs_aio_main().
g_ext_setattr
int g_ext_setattr extern
Definition at line 39 of file xrootdfs.c.
Referenced by xfs_chown(), xfs_utimens(), and xrootdfs_aio_main().
g_ext_symlink
int g_ext_symlink extern
Definition at line 41 of file xrootdfs.c.
Referenced by xfs_symlink(), and xrootdfs_aio_main().
g_keepalive
int g_keepalive extern
Definition at line 25 of file xrootdfs.c.
Referenced by xrootdfs_aio_main().
g_kernel_cache
int g_kernel_cache extern
Definition at line 33 of file xrootdfs.c.
Referenced by xfs_init(), and xrootdfs_aio_main().
g_max_conns
int g_max_conns extern
Definition at line 14 of file xrootdfs.c.
Referenced by xrootdfs_aio_main().
g_max_retries
int g_max_retries extern
Definition at line 26 of file xrootdfs.c.
Referenced by afh_open(), xfs_meta(), xfs_meta_idem(), xfs_readlink(), and xrootdfs_aio_main().
g_max_stall
int g_max_stall extern
Definition at line 24 of file xrootdfs.c.
Referenced by afh_open(), xfs_meta(), xfs_meta_idem(), xfs_readlink(), and xrootdfs_aio_main().
g_mgr
brix_mgr* g_mgr extern
Definition at line 20 of file xrootdfs.c.
Referenced by afh_open(), and xrootdfs_aio_main().
g_opts
brix_opts g_opts extern
Definition at line 12 of file xrootdfs.c.
Referenced by xrootdfs_aio_main().
g_pool
brix_pool* g_pool extern
Definition at line 8 of file xrootdfs.c.
Referenced by xfs_meta(), xfs_meta_idem(), xfs_readlink(), and xrootdfs_aio_main().
g_readahead
size_t g_readahead extern
Definition at line 47 of file xrootdfs.c.
Referenced by afh_open(), and xrootdfs_aio_main().
g_streams
int g_streams extern
Definition at line 22 of file xrootdfs.c.
Referenced by xrootdfs_aio_main().
g_url
brix_url g_url extern
Definition at line 10 of file xrootdfs.c.
Referenced by xrootdfs_aio_main().
g_web
int g_web extern
Definition at line 16 of file xrootdfs.c.
Referenced by afh_open(), xfs_access(), xfs_chmod(), xfs_chown(), xfs_flush(), xfs_fsync(), xfs_getattr(), xfs_getxattr(), xfs_link(), xfs_listxattr(), xfs_mkdir(), xfs_readdir(), xfs_readlink(), xfs_removexattr(), xfs_rename(), xfs_rmdir(), xfs_setxattr(), xfs_statfs(), xfs_symlink(), xfs_truncate(), xfs_unlink(), xfs_utimens(), xfs_write(), and xrootdfs_aio_main().
g_web_ca
const char* g_web_ca extern
Definition at line 84 of file xrootdfs.c.
Referenced by afh_open(), xfs_getattr(), xfs_readdir(), and xrootdfs_aio_main().
g_web_verify
int g_web_verify extern
Definition at line 83 of file xrootdfs.c.
Referenced by afh_open(), xfs_getattr(), xfs_readdir(), and xrootdfs_aio_main().
g_weburl
brix_weburl g_weburl extern
Definition at line 18 of file xrootdfs.c.
Referenced by afh_open(), xfs_getattr(), xfs_readdir(), and xrootdfs_aio_main().
g_writeback
size_t g_writeback extern
Definition at line 49 of file xrootdfs.c.
Referenced by afh_open(), and xrootdfs_aio_main().
g_xattr
int g_xattr extern
Definition at line 35 of file xrootdfs.c.
Referenced by xfs_getxattr(), xfs_listxattr(), xfs_removexattr(), xfs_setxattr(), and xrootdfs_aio_main().
xfs_ops
const struct fuse_operations xfs_ops extern
Definition at line 51 of file xrootdfs.c.
Referenced by xrootdfs_aio_main().