nginx-xrootd: client/apps/fs/xrootdfs.c File Reference
xrootdfs.c File Reference
#include "xrootdfs_internal.h"
#include "core/version.h"
#include "net/cpool.h"
#include "protocols/http/web_ka.h"
Functions
static int web_slot_connect (void *conn, void *ctx, brix_status *st)
static void web_slot_close (void *conn)
const char * srv_path (const char *p, char *buf, size_t sz)
int xfs_err (const brix_status *st)
int xfs_conn_healthy (const brix_status *st)
int xfs_meta (brix_fuse_op_fn fn, void *ctx, brix_status *st)
int xfs_meta_idem (brix_fuse_op_fn fn, void *ctx, int benign_errno, brix_status *st)
void xfs_fill_stat (const brix_statinfo *si, struct stat *stbuf)
int xfs_link (const char *from, const char *to)
void * xfs_init (struct fuse_conn_info *conn, struct fuse_config *cfg)
static void usage_fp (FILE *out)
void usage (void)
static int aio_opt_novalue (const char *a)
static int aio_opt_conn_value (const char *a, char *v)
static int aio_opt_cache_value (const char *a, char *v)
static int aio_parse_args (int argc, char **argv, char **fuse_argv, int *fuse_argc, const char **endpoint)
static void aio_set_base (const char *path)
static int aio_web_mount (int fuse_argc, char **fuse_argv, const char *endpoint)
static void aio_probe_ext (brix_status *st)
static int aio_root_mount (int fuse_argc, char **fuse_argv, const char *endpoint)
int xrootdfs_aio_main (int argc, char **argv)
Variables
brix_pool * g_pool
brix_cpool * g_web_pool
static brix_webmeta g_web_tmpl
static const brix_cpool_vtbl WEB_VT
brix_url g_url
brix_opts g_opts
int g_max_conns = 8
int g_web = 0
brix_weburl g_weburl
brix_mgr * g_mgr
int g_streams = 4
int g_lazy_streams = 0
int g_max_stall = 60000
int g_keepalive = 15000
int g_max_retries = 5
double g_attr_timeout = 1.0
double g_entry_timeout = 1.0
int g_kernel_cache = 0
int g_xattr = 0
char g_compress [32] = ""
int g_ext_setattr = 0
int g_ext_symlink = 0
int g_ext_readlink = 0
int g_ext_link = 0
size_t g_readahead = 1024 * 1024
size_t g_writeback = 1024 * 1024
const struct fuse_operations xfs_ops
const char * g_bearer = NULL
int g_web_verify = 1
const char * g_web_ca = NULL
char g_base [XRDC_PATH_MAX] = ""
Function Documentation
aio_opt_cache_value()
static int aio_opt_cache_value (const char * a, char * v) static
Definition at line 338 of file xrootdfs.c.
References brix_fuse_ctx_link2::a, g_attr_timeout, g_bearer, g_compress, g_entry_timeout, g_readahead, and g_writeback.
Referenced by aio_parse_args().
aio_opt_conn_value()
static int aio_opt_conn_value (const char * a, char * v) static
Definition at line 300 of file xrootdfs.c.
References brix_fuse_ctx_link2::a, brix_opts::auth_force, brix_tmo_set_connect_ms(), brix_tmo_set_io_ms(), g_keepalive, g_max_conns, g_max_retries, g_max_stall, g_opts, and g_streams.
Referenced by aio_parse_args().
aio_opt_novalue()
static int aio_opt_novalue (const char * a) static
Definition at line 282 of file xrootdfs.c.
References brix_fuse_ctx_link2::a, g_kernel_cache, g_lazy_streams, g_opts, g_xattr, brix_opts::notlsok, brix_opts::verify_host, and brix_opts::want_tls.
Referenced by aio_parse_args().
aio_parse_args()
static int aio_parse_args (int argc, char ** argv, char ** fuse_argv, int * fuse_argc, const char ** endpoint) static
Definition at line 373 of file xrootdfs.c.
References brix_fuse_ctx_link2::a, aio_opt_cache_value(), aio_opt_conn_value(), aio_opt_novalue(), brix_client_version(), usage(), and usage_fp().
Referenced by xrootdfs_aio_main().
aio_probe_ext()
static void aio_probe_ext (brix_status * st) static
Definition at line 487 of file xrootdfs.c.
References brix_ext_probe(), brix_pool_checkin(), brix_pool_checkout(), g_ext_link, g_ext_readlink, g_ext_setattr, g_ext_symlink, g_pool, and xfs_conn_healthy().
Referenced by aio_root_mount().
aio_root_mount()
static int aio_root_mount (int fuse_argc, char ** fuse_argv, const char * endpoint) static
Definition at line 506 of file xrootdfs.c.
References aio_probe_ext(), aio_set_base(), brix_endpoint_parse(), brix_mgr_create(), brix_mgr_destroy(), brix_pool_create(), brix_pool_destroy(), brix_shellcode(), brix_status_clear(), g_ext_link, g_ext_readlink, g_ext_setattr, g_ext_symlink, g_keepalive, g_lazy_streams, g_max_conns, g_max_retries, g_max_stall, g_mgr, g_opts, g_pool, g_streams, g_url, brix_url::host, brix_status::msg, brix_url::path, brix_url::port, and xfs_ops.
Referenced by xrootdfs_aio_main().
aio_set_base()
static void aio_set_base (const char * path) static
Definition at line 407 of file xrootdfs.c.
References g_base.
Referenced by aio_root_mount(), and aio_web_mount().
aio_web_mount()
static int aio_web_mount (int fuse_argc, char ** fuse_argv, const char * endpoint) static
Definition at line 426 of file xrootdfs.c.
References aio_set_base(), brix_cpool_create(), brix_cpool_destroy(), brix_resolve_ca_dir(), brix_shellcode(), brix_status_clear(), brix_web_stat(), brix_webmeta_init(), brix_weburl_parse(), brix_opts::ca_dir, g_base, g_bearer, g_max_conns, g_opts, g_web, g_web_ca, g_web_pool, g_web_tmpl, g_web_verify, g_weburl, brix_weburl::host, brix_weburl::is_s3, brix_status::msg, brix_weburl::path, brix_weburl::port, brix_weburl::tls, brix_opts::verify_host, WEB_VT, and xfs_ops.
Referenced by xrootdfs_aio_main().
srv_path()
const char * srv_path (const char * p, char * buf, size_t sz)
Definition at line 120 of file xrootdfs.c.
References g_base.
Referenced by afh_open(), xfs_access(), xfs_chmod(), xfs_chown(), xfs_getattr(), xfs_getxattr(), xfs_link(), xfs_listxattr(), xfs_mkdir(), xfs_readdir(), xfs_readlink(), xfs_removexattr(), xfs_rename(), xfs_rmdir(), xfs_setxattr(), xfs_statfs(), xfs_symlink(), xfs_truncate(), xfs_unlink(), and xfs_utimens().
usage()
void usage (void)
Definition at line 270 of file xrootdfs.c.
References usage_fp().
Referenced by aio_parse_args(), bench_parse_args(), bench_validate_args(), brix_cache_evict_if_needed(), brix_cache_fs_usage(), brix_cache_purge_setup(), brix_cache_purge_to_target(), brix_cache_usage_measure(), brix_cache_watermark_purge(), brix_wt_stage_admit(), ckv_parse_args(), cmd_destroy(), cmd_info(), cmd_init(), cmd_scan(), cmd_usage_stderr(), dispatch_cmd(), dx_parse_argv(), dx_unknown_sub(), fp_apply_core_opt(), fp_finalize_config(), main(), opt_early_exit(), parse_opts(), srr_share_usage(), validate_and_finalize_args(), verify_parse_args(), xrdcp_parse_option(), xrdcp_parse_sync_check(), xrdcp_parse_tpc_mode(), xrdcp_parse_transport_option(), and xrootdfs_aio_main().
usage_fp()
static void usage_fp (FILE * out) static
Definition at line 232 of file xrootdfs.c.
References BRIX_USAGE_FOOTER.
Referenced by aio_parse_args(), usage(), and xrootdfs_aio_main().
web_slot_close()
static void web_slot_close (void * conn) static
Definition at line 29 of file xrootdfs.c.
References brix_kaconn_disconnect().
web_slot_connect()
static int web_slot_connect (void * conn, void * ctx, brix_status * st) static
Definition at line 18 of file xrootdfs.c.
References brix_kaconn_connect(), brix_kaconn::connected, brix_io::fd, brix_kaconn::io, brix_webmeta::ka, and brix_kaconn::tls_ctx.
xfs_conn_healthy()
int xfs_conn_healthy (const brix_status * st)
Definition at line 166 of file xrootdfs.c.
References brix_fuse_conn_healthy().
Referenced by aio_probe_ext(), and xfs_readlink_one_attempt().
xfs_err()
int xfs_err (const brix_status * st)
Definition at line 159 of file xrootdfs.c.
References brix_fuse_errno().
Referenced by afh_open(), xfs_flush(), xfs_fsync(), xfs_getattr(), xfs_read(), xfs_readdir(), xfs_readlink(), and xfs_write().
xfs_fill_stat()
void xfs_fill_stat (const brix_statinfo * si, struct stat * stbuf)
Definition at line 193 of file xrootdfs.c.
References brix_statinfo_to_stat().
Referenced by xfs_getattr(), and xfs_readdir().
xfs_init()
void * xfs_init (struct fuse_conn_info * conn, struct fuse_config * cfg)
Definition at line 216 of file xrootdfs.c.
References g_attr_timeout, g_entry_timeout, and g_kernel_cache.
xfs_link()
int xfs_link (const char * from, const char * to)
Definition at line 201 of file xrootdfs.c.
References brix_fuse_ctx_link2::a, brix_fuse_op_link(), brix_status_clear(), g_ext_link, g_web, srv_path(), xfs_meta_idem(), and XRDC_PATH_MAX.
xfs_meta()
int xfs_meta (brix_fuse_op_fn fn, void * ctx, brix_status * st)
Definition at line 173 of file xrootdfs.c.
References brix_fuse_run(), fn, g_max_retries, g_max_stall, and g_pool.
Referenced by xfs_access(), xfs_chmod(), xfs_chown(), xfs_getattr(), xfs_getxattr(), xfs_listxattr(), xfs_readdir(), xfs_removexattr(), xfs_setxattr(), xfs_statfs(), xfs_truncate(), and xfs_utimens().
xfs_meta_idem()
int xfs_meta_idem (brix_fuse_op_fn fn, void * ctx, int benign_errno, brix_status * st)
Definition at line 185 of file xrootdfs.c.
References brix_fuse_run(), fn, g_max_retries, g_max_stall, and g_pool.
Referenced by xfs_link(), xfs_mkdir(), xfs_rename(), xfs_rmdir(), xfs_symlink(), and xfs_unlink().
xrootdfs_aio_main()
int xrootdfs_aio_main (int argc, char ** argv)
Definition at line 560 of file xrootdfs.c.
References aio_parse_args(), aio_root_mount(), aio_web_mount(), brix_client_version(), brix_crypto_init(), brix_is_web_url(), g_opts, usage(), usage_fp(), and brix_opts::verify_host.
Referenced by main().
Variable Documentation
g_attr_timeout
double g_attr_timeout = 1.0
Definition at line 57 of file xrootdfs.c.
Referenced by aio_opt_cache_value(), and xfs_init().
g_base
char g_base[XRDC_PATH_MAX] = ""
Definition at line 113 of file xrootdfs.c.
Referenced by aio_set_base(), aio_web_mount(), and srv_path().
g_bearer
const char* g_bearer = NULL
Definition at line 110 of file xrootdfs.c.
Referenced by afh_open(), aio_opt_cache_value(), and aio_web_mount().
g_compress
char g_compress[32] = ""
Definition at line 65 of file xrootdfs.c.
Referenced by afh_open(), and aio_opt_cache_value().
g_entry_timeout
double g_entry_timeout = 1.0
Definition at line 59 of file xrootdfs.c.
Referenced by aio_opt_cache_value(), and xfs_init().
g_ext_link
int g_ext_link = 0
Definition at line 73 of file xrootdfs.c.
Referenced by aio_probe_ext(), aio_root_mount(), and xfs_link().
g_ext_readlink
int g_ext_readlink = 0
Definition at line 71 of file xrootdfs.c.
Referenced by aio_probe_ext(), aio_root_mount(), and xfs_readlink().
g_ext_setattr
int g_ext_setattr = 0
Definition at line 67 of file xrootdfs.c.
Referenced by aio_probe_ext(), aio_root_mount(), xfs_chown(), and xfs_utimens().
g_ext_symlink
int g_ext_symlink = 0
Definition at line 69 of file xrootdfs.c.
Referenced by aio_probe_ext(), aio_root_mount(), and xfs_symlink().
g_keepalive
int g_keepalive = 15000
Definition at line 53 of file xrootdfs.c.
Referenced by aio_opt_conn_value(), and aio_root_mount().
g_kernel_cache
int g_kernel_cache = 0
Definition at line 61 of file xrootdfs.c.
Referenced by aio_opt_novalue(), and xfs_init().
g_lazy_streams
int g_lazy_streams = 0
Definition at line 51 of file xrootdfs.c.
Referenced by aio_opt_novalue(), and aio_root_mount().
g_max_conns
int g_max_conns = 8
Definition at line 42 of file xrootdfs.c.
Referenced by aio_opt_conn_value(), aio_root_mount(), and aio_web_mount().
g_max_retries
int g_max_retries = 5
Definition at line 54 of file xrootdfs.c.
Referenced by afh_open(), aio_opt_conn_value(), aio_root_mount(), xfs_meta(), xfs_meta_idem(), and xfs_readlink().
g_max_stall
int g_max_stall = 60000
Definition at line 52 of file xrootdfs.c.
Referenced by afh_open(), aio_opt_conn_value(), aio_root_mount(), xfs_meta(), xfs_meta_idem(), and xfs_readlink().
g_mgr
brix_mgr* g_mgr
Definition at line 48 of file xrootdfs.c.
Referenced by afh_open(), and aio_root_mount().
g_opts
brix_opts g_opts
Definition at line 40 of file xrootdfs.c.
Referenced by aio_opt_conn_value(), aio_opt_novalue(), aio_root_mount(), aio_web_mount(), and xrootdfs_aio_main().
g_pool
brix_pool* g_pool
Definition at line 10 of file xrootdfs.c.
Referenced by aio_probe_ext(), aio_root_mount(), xfs_meta(), xfs_meta_idem(), and xfs_readlink_one_attempt().
g_readahead
size_t g_readahead = 1024 * 1024
Definition at line 75 of file xrootdfs.c.
Referenced by afh_open(), and aio_opt_cache_value().
g_streams
int g_streams = 4
Definition at line 50 of file xrootdfs.c.
Referenced by aio_opt_conn_value(), and aio_root_mount().
g_url
brix_url g_url
Definition at line 38 of file xrootdfs.c.
Referenced by aio_root_mount().
g_web
int g_web = 0
Definition at line 44 of file xrootdfs.c.
Referenced by afh_open(), aio_web_mount(), xfs_access(), xfs_chmod(), xfs_chown(), xfs_flush(), xfs_fsync(), xfs_getattr(), xfs_getxattr(), xfs_link(), xfs_listxattr(), xfs_mkdir(), xfs_readdir(), xfs_readlink(), xfs_removexattr(), xfs_rename(), xfs_rmdir(), xfs_setxattr(), xfs_statfs(), xfs_symlink(), xfs_truncate(), xfs_unlink(), xfs_utimens(), and xfs_write().
g_web_ca
const char* g_web_ca = NULL
Definition at line 112 of file xrootdfs.c.
Referenced by afh_open(), and aio_web_mount().
g_web_pool
brix_cpool* g_web_pool
Definition at line 14 of file xrootdfs.c.
Referenced by aio_web_mount(), xfs_getattr(), and xfs_readdir().
g_web_tmpl
brix_webmeta g_web_tmpl static
Definition at line 15 of file xrootdfs.c.
Referenced by aio_web_mount().
g_web_verify
int g_web_verify = 1
Definition at line 111 of file xrootdfs.c.
Referenced by afh_open(), and aio_web_mount().
g_weburl
brix_weburl g_weburl
Definition at line 46 of file xrootdfs.c.
Referenced by afh_open(), and aio_web_mount().
g_writeback
size_t g_writeback = 1024 * 1024
Definition at line 77 of file xrootdfs.c.
Referenced by afh_open(), and aio_opt_cache_value().
g_xattr
int g_xattr = 0
Definition at line 63 of file xrootdfs.c.
Referenced by aio_opt_novalue(), xfs_getxattr(), xfs_listxattr(), xfs_removexattr(), and xfs_setxattr().
WEB_VT
const brix_cpool_vtbl WEB_VT static
Initial value:
= {
    sizeof(brix_webmeta), web_slot_connect, web_slot_close,
}
Definition at line 34 of file xrootdfs.c.
Referenced by aio_web_mount().
xfs_ops
const struct fuse_operations xfs_ops
Initial value:
= {
    .init     = xfs_init,
    .getattr  = xfs_getattr,
    .readdir  = xfs_readdir,
    .open     = xfs_open,
    .create   = xfs_create,
    .read     = xfs_read,
    .write    = xfs_write,
    .flush    = xfs_flush,
    .release  = xfs_release,
    .fsync    = xfs_fsync,
    .mkdir    = xfs_mkdir,
    .unlink   = xfs_unlink,
    .rmdir    = xfs_rmdir,
    .rename   = xfs_rename,
    .chmod    = xfs_chmod,
    .truncate = xfs_truncate,
    .chown    = xfs_chown,
    .utimens  = xfs_utimens,
    .symlink  = xfs_symlink,
    .readlink = xfs_readlink,
    .link     = xfs_link,
    .statfs   = xfs_statfs,
    .access   = xfs_access,
    .getxattr    = xfs_getxattr,
    .setxattr    = xfs_setxattr,
    .listxattr   = xfs_listxattr,
    .removexattr = xfs_removexattr,
}
Definition at line 79 of file xrootdfs.c.
Referenced by aio_root_mount(), and aio_web_mount().