nginx-xrootd: client/lib/protocols/shared/zip_internal.h File Reference
zip_internal.h File Reference
#include "zip.h"
#include <stdlib.h>
#include <string.h>
#include <zlib.h>
#include <unistd.h>
#include <sys/stat.h>
#include <errno.h>
Data Structures
struct brix_zip_writer
Macros
#define SIG_EOCD 0x06054b50u
#define SIG_Z64LOC 0x07064b50u
#define SIG_Z64EOCD 0x06064b50u
#define SIG_CDFH 0x02014b50u
#define SIG_LFH 0x04034b50u
#define SIG_Z64EOCD_W 0x06064b50u
#define SIG_Z64LOC_W 0x07064b50u
#define ZIP_U32_MAX 0xffffffffu
Functions
uint16_t le16 (const uint8_t *p)
uint32_t le32 (const uint8_t *p)
uint64_t le64 (const uint8_t *p)
int read_exact (brix_zip_pread_fn pread, void *ctx, uint64_t off, uint64_t archive_size, void *buf, size_t len)
int find_eocd (brix_zip_pread_fn pread, void *ctx, uint64_t asize, uint64_t *cd_off, uint64_t *cd_size, uint64_t *n_entries)
void apply_zip64_extra (brix_zip_entry *ent, const uint8_t *extra, size_t extra_len)
int member_data_offset (brix_zip_pread_fn pread, void *ctx, uint64_t asize, const brix_zip_entry *e, uint64_t *data_off)
int sink_output (brix_zip_sink_fn sink, void *sink_ctx, const uint8_t *data, size_t len, uLong *crc, uint64_t *produced, uint64_t uncomp_size)
void put16 (uint8_t *p, uint16_t v)
void put32 (uint8_t *p, uint32_t v)
void put64 (uint8_t *p, uint64_t v)
int cd_append (brix_zip_writer *w, const uint8_t *p, size_t len)
int w_emit (brix_zip_writer *w, const void *p, size_t len)
Macro Definition Documentation
SIG_CDFH
#define SIG_CDFH 0x02014b50u
Definition at line 19 of file zip_internal.h.
SIG_EOCD
#define SIG_EOCD 0x06054b50u
Definition at line 16 of file zip_internal.h.
SIG_LFH
#define SIG_LFH 0x04034b50u
Definition at line 20 of file zip_internal.h.
SIG_Z64EOCD
#define SIG_Z64EOCD 0x06064b50u
Definition at line 18 of file zip_internal.h.
SIG_Z64EOCD_W
#define SIG_Z64EOCD_W 0x06064b50u
Definition at line 21 of file zip_internal.h.
SIG_Z64LOC
#define SIG_Z64LOC 0x07064b50u
Definition at line 17 of file zip_internal.h.
SIG_Z64LOC_W
#define SIG_Z64LOC_W 0x07064b50u
Definition at line 22 of file zip_internal.h.
ZIP_U32_MAX
#define ZIP_U32_MAX 0xffffffffu
Definition at line 23 of file zip_internal.h.
Function Documentation
apply_zip64_extra()
void apply_zip64_extra (brix_zip_entry * ent, const uint8_t * extra, size_t extra_len)
Definition at line 61 of file zip.c.
References brix_zip_entry::comp_size, brix_zip_entry::lfh_off, brix_zip_entry::uncomp_size, and zip_apply_zip64_extra().
Referenced by brix_zip_open().
cd_append()
int cd_append (brix_zip_writer * w, const uint8_t * p, size_t len)
Definition at line 11 of file zip_write.c.
References brix_zip_writer::cd, brix_zip_writer::cd_cap, brix_zip_writer::cd_len, XRDC_ZIP_ENOMEM, and XRDC_ZIP_OK.
Referenced by brix_zip_writer_add_fd(), and brix_zip_writer_new_append().
find_eocd()
int find_eocd (brix_zip_pread_fn pread, void * ctx, uint64_t asize, uint64_t * cd_off, uint64_t * cd_size, uint64_t * n_entries)
Definition at line 49 of file zip.c.
References pread(), XRDC_ZIP_MAX_CD_SIZE, XRDC_ZIP_MAX_ENTRIES, zip_locate_cd(), and zip_map_kernel_rc().
Referenced by brix_zip_open(), and brix_zip_read_eocd().
le16()
uint16_t le16 (const uint8_t * p)
Definition at line 28 of file zip.c.
References zip_rd16le().
Referenced by brix_zip_open().
le32()
uint32_t le32 (const uint8_t * p)
Definition at line 30 of file zip.c.
References zip_rd32le().
Referenced by brix_zip_open().
le64()
uint64_t le64 (const uint8_t * p)
Definition at line 32 of file zip.c.
References zip_rd64le().
member_data_offset()
int member_data_offset (brix_zip_pread_fn pread, void * ctx, uint64_t asize, const brix_zip_entry * e, uint64_t * data_off)
Definition at line 200 of file zip.c.
References brix_zip_entry::comp_size, brix_zip_entry::lfh_off, pread(), zip_map_kernel_rc(), and zip_resolve_data_off().
Referenced by brix_zip_member_extract().
put16()
void put16 (uint8_t * p, uint16_t v)
Definition at line 337 of file zip.c.
Referenced by brix_zip_writer_add_fd(), and brix_zip_writer_finish().
put32()
void put32 (uint8_t * p, uint32_t v)
Definition at line 339 of file zip.c.
Referenced by brix_zip_writer_add_fd(), and brix_zip_writer_finish().
put64()
void put64 (uint8_t * p, uint64_t v)
Definition at line 345 of file zip.c.
Referenced by brix_zip_writer_add_fd(), and brix_zip_writer_finish().
read_exact()
int read_exact (brix_zip_pread_fn pread, void * ctx, uint64_t off, uint64_t archive_size, void * buf, size_t len)
Definition at line 38 of file zip.c.
References pread(), zip_map_kernel_rc(), and zip_read_at().
Referenced by brix_zip_member_extract(), and brix_zip_open().
sink_output()
int sink_output (brix_zip_sink_fn sink, void * sink_ctx, const uint8_t * data, size_t len, uLong * crc, uint64_t * produced, uint64_t uncomp_size)
Definition at line 211 of file zip.c.
References XRDC_ZIP_EBOMB, XRDC_ZIP_EIO, XRDC_ZIP_MAX_OUTPUT, and XRDC_ZIP_OK.
Referenced by brix_zip_member_extract().
w_emit()
int w_emit (brix_zip_writer * w, const void * p, size_t len)
Definition at line 69 of file zip_write.c.
References brix_zip_writer::ctx, brix_zip_writer::err, brix_zip_writer::offset, brix_zip_writer::wr, XRDC_ZIP_EIO, and XRDC_ZIP_OK.
Referenced by brix_zip_writer_add_fd(), and brix_zip_writer_finish().