nginx-xrootd: src/protocols/root/zip/zip_member.h File Reference
zip_member.h File Reference
#include "core/ngx_brix_module.h"
Functions
ngx_int_t brix_zip_open_member (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *archive_logical, const char *archive_full, const char *member, uint16_t options)
ngx_int_t brix_zip_read (brix_ctx_t *ctx, ngx_connection_t *c, int idx, int64_t offset, size_t rlen)
void brix_zip_handle_cleanup (brix_file_t *fh)
Function Documentation
brix_zip_handle_cleanup()
void brix_zip_handle_cleanup (brix_file_t * fh)
Definition at line 546 of file zip_member.c.
References zip_deflate_free().
Referenced by fhandle_reset_slot().
brix_zip_open_member()
ngx_int_t brix_zip_open_member (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * archive_logical, const char * archive_full, const char * member, uint16_t options)
Definition at line 453 of file zip_member.c.
References brix_alloc_fhandle(), brix_free_fhandle(), BRIX_OP_OPEN_RD, BRIX_RETURN_ERR, brix_session_handle_publish(), brix_set_fhandle_path(), c, close(), brix_ctx_t::files, brix_ctx_t::is_bound, kXR_ServerError, brix_ctx_t::login, brix_ctx_login_t::sessid, stat(), zip_find_member_mapped(), zip_handle_populate(), zip_open_archive_fd(), zip_send_open_reply(), and zip_stage_archive_maybe().
Referenced by brix_open_read_resolve().
brix_zip_read()
ngx_int_t brix_zip_read (brix_ctx_t * ctx, ngx_connection_t * c, int idx, int64_t offset, size_t rlen)
Definition at line 496 of file zip_member.c.
References BRIX_OP_OK, BRIX_OP_READ, BRIX_RETURN_ERR, brix_send_error(), brix_send_ok(), BRIX_ZIP_METHOD_STORE, brix_file_t::bytes_read, c, brix_file_t::fd, brix_ctx_t::files, kXR_IOError, kXR_NoMemory, brix_file_t::path, brix_file_t::zip_data_off, zip_deflate_read(), brix_file_t::zip_method, zip_pread_full(), and brix_file_t::zip_uncomp_size.
Referenced by brix_handle_read().