nginx-xrootd: client/lib/protocols/shared/zip_write.c File Reference
zip_write.c File Reference
#include "zip_internal.h"
Data Structures
struct zw_entry
Functions
int cd_append (brix_zip_writer *w, const uint8_t *p, size_t len)
brix_zip_writer * brix_zip_writer_new (brix_zip_write_fn wr, void *ctx)
brix_zip_writer * brix_zip_writer_new_append (brix_zip_write_fn wr, void *ctx, uint64_t base_offset, const brix_zip_seed *seed)
int w_emit (brix_zip_writer *w, const void *p, size_t len)
static int zw_crc_pass (brix_zip_writer *w, int fd, zw_entry *e, unsigned char *buf, size_t bufsz)
static int zw_write_local_header (brix_zip_writer *w, const zw_entry *e)
static int zw_stream_deflate (brix_zip_writer *w, int fd, const zw_entry *e, unsigned char *buf, size_t bufsz)
static int zw_update_central_dir (brix_zip_writer *w, const zw_entry *e)
int brix_zip_writer_add_fd (brix_zip_writer *w, const char *name, int fd)
int brix_zip_writer_finish (brix_zip_writer *w)
void brix_zip_writer_free (brix_zip_writer *w)
Function Documentation
brix_zip_writer_add_fd()
int brix_zip_writer_add_fd (brix_zip_writer * w, const char * name, int fd)
Definition at line 281 of file zip_write.c.
References brix_zip_writer::err, fstat(), brix_zip_writer::n, name, stat(), XRDC_ZIP_EBADF, XRDC_ZIP_EIO, XRDC_ZIP_MAX_NAME, XRDC_ZIP_OK, zw_crc_pass(), zw_stream_deflate(), zw_update_central_dir(), and zw_write_local_header().
Referenced by zip_emit_member().
brix_zip_writer_finish()
int brix_zip_writer_finish (brix_zip_writer * w)
Definition at line 326 of file zip_write.c.
References brix_zip_writer::any_zip64, brix_zip_writer::cd, brix_zip_writer::cd_len, brix_zip_writer::err, brix_zip_writer::n, brix_zip_writer::offset, put16(), put32(), put64(), SIG_EOCD, SIG_Z64EOCD_W, SIG_Z64LOC_W, w_emit(), XRDC_ZIP_EBADF, XRDC_ZIP_OK, and ZIP_U32_MAX.
Referenced by zip_emit_member().
brix_zip_writer_free()
void brix_zip_writer_free (brix_zip_writer * w)
Definition at line 399 of file zip_write.c.
References brix_zip_writer::cd.
Referenced by brix_zip_writer_new_append(), copy_zip_store_local(), and copy_zip_store_remote().
brix_zip_writer_new()
brix_zip_writer * brix_zip_writer_new (brix_zip_write_fn wr, void * ctx)
Definition at line 33 of file zip_write.c.
References brix_zip_writer::ctx, and brix_zip_writer::wr.
Referenced by brix_zip_writer_new_append(), copy_zip_store_local(), and copy_zip_store_remote().
brix_zip_writer_new_append()
brix_zip_writer * brix_zip_writer_new_append (brix_zip_write_fn wr, void * ctx, uint64_t base_offset, const brix_zip_seed * seed)
Definition at line 49 of file zip_write.c.
References brix_zip_writer_free(), brix_zip_writer_new(), brix_zip_seed::cd, cd_append(), brix_zip_seed::cd_len, brix_zip_seed::n, brix_zip_writer::n, brix_zip_writer::offset, and XRDC_ZIP_OK.
Referenced by copy_zip_store_local(), and copy_zip_store_remote().
cd_append()
int cd_append (brix_zip_writer * w, const uint8_t * p, size_t len)
Definition at line 11 of file zip_write.c.
References brix_zip_writer::cd, brix_zip_writer::cd_cap, brix_zip_writer::cd_len, XRDC_ZIP_ENOMEM, and XRDC_ZIP_OK.
Referenced by brix_zip_writer_new_append(), and zw_update_central_dir().
w_emit()
int w_emit (brix_zip_writer * w, const void * p, size_t len)
Definition at line 68 of file zip_write.c.
References brix_zip_writer::ctx, brix_zip_writer::err, brix_zip_writer::offset, brix_zip_writer::wr, XRDC_ZIP_EIO, and XRDC_ZIP_OK.
Referenced by brix_zip_writer_finish(), zw_stream_deflate(), and zw_write_local_header().
zw_crc_pass()
static int zw_crc_pass (brix_zip_writer * w, int fd, zw_entry * e, unsigned char * buf, size_t bufsz) static
Definition at line 115 of file zip_write.c.
References brix_zip_writer::any_zip64, zw_entry::crc, zw_entry::lfh_off, brix_zip_writer::offset, pread(), zw_entry::size, XRDC_ZIP_EIO, XRDC_ZIP_OK, and zw_entry::zip64.
Referenced by brix_zip_writer_add_fd().
zw_stream_deflate()
static int zw_stream_deflate (brix_zip_writer * w, int fd, const zw_entry * e, unsigned char * buf, size_t bufsz) static
Definition at line 199 of file zip_write.c.
References brix_zip_writer::err, pread(), zw_entry::size, w_emit(), XRDC_ZIP_EIO, and XRDC_ZIP_OK.
Referenced by brix_zip_writer_add_fd().
zw_update_central_dir()
static int zw_update_central_dir (brix_zip_writer * w, const zw_entry * e) static
Definition at line 237 of file zip_write.c.
References cd_append(), zw_entry::crc, brix_zip_writer::err, zw_entry::lfh_off, zw_entry::name, zw_entry::namelen, put16(), put32(), put64(), SIG_CDFH, zw_entry::size, XRDC_ZIP_ENOMEM, XRDC_ZIP_OK, zw_entry::zip64, and ZIP_U32_MAX.
Referenced by brix_zip_writer_add_fd().
zw_write_local_header()
static int zw_write_local_header (brix_zip_writer * w, const zw_entry * e) static
Definition at line 154 of file zip_write.c.
References zw_entry::crc, brix_zip_writer::err, zw_entry::name, zw_entry::namelen, put16(), put32(), put64(), SIG_LFH, zw_entry::size, w_emit(), XRDC_ZIP_OK, zw_entry::zip64, and ZIP_U32_MAX.
Referenced by brix_zip_writer_add_fd().