nginx-xrootd: src/protocols/root/zip/zip_dir.h File Reference
zip_dir.h File Reference
#include <stdint.h>
#include <sys/types.h>
#include <limits.h>
Data Structures
struct brix_zip_member_t
Macros
#define PATH_MAX 4096
#define BRIX_ZIP_METHOD_STORE 0
#define BRIX_ZIP_METHOD_DEFLATE 8
#define BRIX_ZIP_OK 0 /* found; *out filled */
#define BRIX_ZIP_NOMEMBER 1 /* archive parsed, no such member */
#define BRIX_ZIP_ECORRUPT (-1) /* not a zip / corrupt / oversize / unsupported */
#define BRIX_ZIP_EIO (-2) /* pread / allocation failure */
Functions
int brix_zip_find_member (int fd, off_t archive_size, const char *member, size_t cd_max, brix_zip_member_t *out)
ssize_t brix_zip_extract_full (int fd, const brix_zip_member_t *m, unsigned char *out, size_t outcap)
Macro Definition Documentation
BRIX_ZIP_ECORRUPT
#define BRIX_ZIP_ECORRUPT (-1) /* not a zip / corrupt / oversize / unsupported */
Definition at line 46 of file zip_dir.h.
BRIX_ZIP_EIO
#define BRIX_ZIP_EIO (-2) /* pread / allocation failure */
Definition at line 47 of file zip_dir.h.
BRIX_ZIP_METHOD_DEFLATE
#define BRIX_ZIP_METHOD_DEFLATE 8
Definition at line 31 of file zip_dir.h.
BRIX_ZIP_METHOD_STORE
#define BRIX_ZIP_METHOD_STORE 0
Definition at line 30 of file zip_dir.h.
BRIX_ZIP_NOMEMBER
#define BRIX_ZIP_NOMEMBER 1 /* archive parsed, no such member */
Definition at line 45 of file zip_dir.h.
BRIX_ZIP_OK
#define BRIX_ZIP_OK 0 /* found; *out filled */
Definition at line 44 of file zip_dir.h.
PATH_MAX
#define PATH_MAX 4096
Definition at line 27 of file zip_dir.h.
Function Documentation
brix_zip_extract_full()
ssize_t brix_zip_extract_full (int fd, const brix_zip_member_t * m, unsigned char * out, size_t outcap)
Definition at line 184 of file zip_dir.c.
References brix_size_add(), BRIX_ZIP_METHOD_DEFLATE, BRIX_ZIP_METHOD_STORE, brix_zip_member_t::comp_size, brix_zip_member_t::data_off, brix_zip_member_t::method, pread_full(), and brix_zip_member_t::uncomp_size.
Referenced by brix_zip_http_serve().
brix_zip_find_member()
int brix_zip_find_member (int fd, off_t archive_size, const char * member, size_t cd_max, brix_zip_member_t * out)
Definition at line 75 of file zip_dir.c.
References brix_size_add(), BRIX_ZIP_ECORRUPT, BRIX_ZIP_EIO, BRIX_ZIP_METHOD_DEFLATE, BRIX_ZIP_METHOD_STORE, BRIX_ZIP_NOMEMBER, BRIX_ZIP_OK, brix_zip_member_t::comp_size, brix_zip_member_t::crc32, brix_zip_member_t::data_off, fn, brix_zip_member_t::method, brix_zip_member_t::name, PATH_MAX, pread_full(), brix_zip_member_t::uncomp_size, zip_apply_zip64_extra(), ZIP_CDFH_BASE, ZIP_CDFH_SIG, zip_fd_pread(), ZIP_GPF_DATADESC, ZIP_GPF_ENCRYPTED, ZIP_K_OK, zip_locate_cd(), zip_map_kernel_rc(), zip_rd16le(), zip_rd32le(), and zip_resolve_data_off().
Referenced by brix_zip_http_serve(), brix_zip_open_member(), and main().