nginx-xrootd: client/lib/protocols/shared/zip.h File Reference
zip.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>
Data Structures
struct brix_zip_entry
struct brix_zip_dir
struct brix_zip_seed
Macros
#define XRDC_ZIP_OK 0
#define XRDC_ZIP_ENOTZIP -1 /* no End-of-Central-Directory found */
#define XRDC_ZIP_EBADF -2 /* malformed structure / failed bounds check */
#define XRDC_ZIP_EIO -3 /* pread callback failure */
#define XRDC_ZIP_ENOMEM -4
#define XRDC_ZIP_ENOENT -5 /* member not found */
#define XRDC_ZIP_EMETHOD -6 /* unsupported compression method */
#define XRDC_ZIP_EBOMB -7 /* output size/ratio guard tripped */
#define XRDC_ZIP_ECRC -8 /* CRC-32 mismatch */
#define XRDC_ZIP_EINFLATE -9 /* corrupt deflate stream */
#define XRDC_ZIP_MAX_ENTRIES 1000000u
#define XRDC_ZIP_MAX_CD_SIZE (256u * 1024u * 1024u)
#define XRDC_ZIP_MAX_NAME 4096u
#define XRDC_ZIP_MAX_OUTPUT (64ULL * 1024 * 1024 * 1024) /* 64 GiB ceiling */
Typedefs
typedef ssize_t(* brix_zip_pread_fn) (void *ctx, uint64_t off, void *buf, size_t len)
typedef int(* brix_zip_sink_fn) (void *sink_ctx, const uint8_t *data, size_t len)
typedef int(* brix_zip_write_fn) (void *ctx, const void *data, size_t len)
Functions
int brix_zip_open (brix_zip_pread_fn pread, void *ctx, uint64_t archive_size, brix_zip_dir *out)
const brix_zip_entry * brix_zip_find (const brix_zip_dir *d, const char *name)
void brix_zip_dir_free (brix_zip_dir *d)
int brix_zip_member_extract (brix_zip_pread_fn pread, void *ctx, const brix_zip_entry *e, brix_zip_sink_fn sink, void *sink_ctx)
brix_zip_writer * brix_zip_writer_new (brix_zip_write_fn wr, void *ctx)
brix_zip_writer * brix_zip_writer_new_append (brix_zip_write_fn wr, void *ctx, uint64_t base_offset, const brix_zip_seed *seed)
int brix_zip_writer_add_fd (brix_zip_writer *w, const char *name, int fd)
int brix_zip_writer_finish (brix_zip_writer *w)
void brix_zip_writer_free (brix_zip_writer *w)
int brix_zip_read_eocd (brix_zip_pread_fn pread, void *ctx, uint64_t archive_size, uint64_t *cd_off, uint64_t *cd_size, uint64_t *n_entries, int *is_zip64)
Macro Definition Documentation
XRDC_ZIP_EBADF
#define XRDC_ZIP_EBADF -2 /* malformed structure / failed bounds check */
Definition at line 57 of file zip.h.
XRDC_ZIP_EBOMB
#define XRDC_ZIP_EBOMB -7 /* output size/ratio guard tripped */
Definition at line 62 of file zip.h.
XRDC_ZIP_ECRC
#define XRDC_ZIP_ECRC -8 /* CRC-32 mismatch */
Definition at line 63 of file zip.h.
XRDC_ZIP_EINFLATE
#define XRDC_ZIP_EINFLATE -9 /* corrupt deflate stream */
Definition at line 64 of file zip.h.
XRDC_ZIP_EIO
#define XRDC_ZIP_EIO -3 /* pread callback failure */
Definition at line 58 of file zip.h.
XRDC_ZIP_EMETHOD
#define XRDC_ZIP_EMETHOD -6 /* unsupported compression method */
Definition at line 61 of file zip.h.
XRDC_ZIP_ENOENT
#define XRDC_ZIP_ENOENT -5 /* member not found */
Definition at line 60 of file zip.h.
XRDC_ZIP_ENOMEM
#define XRDC_ZIP_ENOMEM -4
Definition at line 59 of file zip.h.
XRDC_ZIP_ENOTZIP
#define XRDC_ZIP_ENOTZIP -1 /* no End-of-Central-Directory found */
Definition at line 56 of file zip.h.
XRDC_ZIP_MAX_CD_SIZE
#define XRDC_ZIP_MAX_CD_SIZE (256u * 1024u * 1024u)
Definition at line 68 of file zip.h.
XRDC_ZIP_MAX_ENTRIES
#define XRDC_ZIP_MAX_ENTRIES 1000000u
Definition at line 67 of file zip.h.
XRDC_ZIP_MAX_NAME
#define XRDC_ZIP_MAX_NAME 4096u
Definition at line 69 of file zip.h.
XRDC_ZIP_MAX_OUTPUT
#define XRDC_ZIP_MAX_OUTPUT (64ULL * 1024 * 1024 * 1024) /* 64 GiB ceiling */
Definition at line 70 of file zip.h.
XRDC_ZIP_OK
#define XRDC_ZIP_OK 0
Definition at line 55 of file zip.h.
Typedef Documentation
brix_zip_pread_fn
typedef ssize_t(* brix_zip_pread_fn) (void *ctx, uint64_t off, void *buf, size_t len)
Definition at line 33 of file zip.h.
brix_zip_sink_fn
typedef int(* brix_zip_sink_fn) (void *sink_ctx, const uint8_t *data, size_t len)
Definition at line 36 of file zip.h.
brix_zip_write_fn
typedef int(* brix_zip_write_fn) (void *ctx, const void *data, size_t len)
Definition at line 100 of file zip.h.
Function Documentation
brix_zip_dir_free()
void brix_zip_dir_free (brix_zip_dir * d)
Definition at line 257 of file zip.c.
References brix_zip_dir::entries, brix_zip_dir::n, and brix_zip_entry::name.
Referenced by brix_zip_open(), and copy_unzip_extract_member().
brix_zip_find()
const brix_zip_entry * brix_zip_find (const brix_zip_dir * d, const char * name)
Definition at line 240 of file zip.c.
References brix_zip_dir::entries, brix_zip_dir::n, brix_zip_entry::name, and name.
Referenced by copy_unzip_extract_member().
brix_zip_member_extract()
int brix_zip_member_extract (brix_zip_pread_fn pread, void * ctx, const brix_zip_entry * e, brix_zip_sink_fn sink, void * sink_ctx)
Definition at line 488 of file zip.c.
References brix_zip_entry::archive_size, zip_extract_t::crc, zip_extract_t::data_off, zip_extract_t::e, member_data_offset(), brix_zip_entry::method, zip_extract_t::pread, pread(), zip_extract_t::pread_ctx, zip_extract_t::sink, zip_extract_t::sink_ctx, brix_zip_entry::uncomp_size, XRDC_ZIP_EBOMB, XRDC_ZIP_EMETHOD, XRDC_ZIP_MAX_OUTPUT, XRDC_ZIP_OK, zip_extract_setup(), zip_extract_stream(), zip_extract_teardown(), and zip_extract_verify().
Referenced by copy_unzip_extract_member().
brix_zip_open()
int brix_zip_open (brix_zip_pread_fn pread, void * ctx, uint64_t archive_size, brix_zip_dir * out)
Definition at line 195 of file zip.c.
References brix_zip_dir::archive_size, brix_zip_dir_free(), zip_cd_t::bytes, brix_zip_dir::entries, brix_zip_dir::n, zip_cd_t::n_entries, pread(), zip_cd_t::size, XRDC_ZIP_EBADF, XRDC_ZIP_ENOMEM, XRDC_ZIP_OK, ZIP_CD_STOP, ZIP_CDFH_FIXED, zip_parse_cd_entry(), and zip_read_central_dir().
Referenced by copy_unzip_extract_member().
brix_zip_read_eocd()
int brix_zip_read_eocd (brix_zip_pread_fn pread, void * ctx, uint64_t archive_size, uint64_t * cd_off, uint64_t * cd_size, uint64_t * n_entries, int * is_zip64)
Definition at line 550 of file zip.c.
References find_eocd(), and XRDC_ZIP_OK.
Referenced by zip_read_seed().
brix_zip_writer_add_fd()
int brix_zip_writer_add_fd (brix_zip_writer * w, const char * name, int fd)
Definition at line 281 of file zip_write.c.
References brix_zip_writer::err, fstat(), brix_zip_writer::n, name, stat(), XRDC_ZIP_EBADF, XRDC_ZIP_EIO, XRDC_ZIP_MAX_NAME, XRDC_ZIP_OK, zw_crc_pass(), zw_stream_deflate(), zw_update_central_dir(), and zw_write_local_header().
Referenced by zip_emit_member().
brix_zip_writer_finish()
int brix_zip_writer_finish (brix_zip_writer * w)
Definition at line 326 of file zip_write.c.
References brix_zip_writer::any_zip64, brix_zip_writer::cd, brix_zip_writer::cd_len, brix_zip_writer::err, brix_zip_writer::n, brix_zip_writer::offset, put16(), put32(), put64(), SIG_EOCD, SIG_Z64EOCD_W, SIG_Z64LOC_W, w_emit(), XRDC_ZIP_EBADF, XRDC_ZIP_OK, and ZIP_U32_MAX.
Referenced by zip_emit_member().
brix_zip_writer_free()
void brix_zip_writer_free (brix_zip_writer * w)
Definition at line 399 of file zip_write.c.
References brix_zip_writer::cd.
Referenced by brix_zip_writer_new_append(), copy_zip_store_local(), and copy_zip_store_remote().
brix_zip_writer_new()
brix_zip_writer * brix_zip_writer_new (brix_zip_write_fn wr, void * ctx)
Definition at line 33 of file zip_write.c.
References brix_zip_writer::ctx, and brix_zip_writer::wr.
Referenced by brix_zip_writer_new_append(), copy_zip_store_local(), and copy_zip_store_remote().
brix_zip_writer_new_append()
brix_zip_writer * brix_zip_writer_new_append (brix_zip_write_fn wr, void * ctx, uint64_t base_offset, const brix_zip_seed * seed)
Definition at line 49 of file zip_write.c.
References brix_zip_writer_free(), brix_zip_writer_new(), brix_zip_seed::cd, cd_append(), brix_zip_seed::cd_len, brix_zip_seed::n, brix_zip_writer::n, brix_zip_writer::offset, and XRDC_ZIP_OK.
Referenced by copy_zip_store_local(), and copy_zip_store_remote().