nginx-xrootd: src/protocols/root/zip/zip_dir.c File Reference
zip_dir.c File Reference
#include "zip_dir.h"
#include "zip_kernel.h"
#include "fs/backend/sd.h"
#include "core/compat/safe_size.h"
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <zlib.h>
Data Structures
struct brix_zip_cdfh_t
struct brix_zip_arc_t
struct brix_zip_cd_t
struct brix_zip_key_t
Macros
#define ZIP_CDFH_SIG 0x02014b50u /* Central Directory File Header */
#define ZIP_CDFH_BASE 46
#define ZIP_GPF_ENCRYPTED 0x0001u /* general-purpose bit 0 */
#define ZIP_GPF_DATADESC 0x0008u /* general-purpose bit 3 */
Functions
static int pread_full (int fd, void *buf, size_t n, off_t off)
static ssize_t zip_fd_pread (void *ctx, uint64_t off, void *buf, size_t len)
static int zip_map_kernel_rc (int krc)
static int zip_parse_cdfh (const unsigned char *cd, uint64_t p, uint64_t cd_size, brix_zip_cdfh_t *rec)
static int zip_build_member (const brix_zip_arc_t *arc, const unsigned char *base, const brix_zip_cdfh_t *rec, brix_zip_member_t *last)
static int zip_load_cd (int fd, off_t archive_size, size_t cd_max, brix_zip_cd_t *cd)
static int zip_scan_directory (const brix_zip_arc_t *arc, const brix_zip_cd_t *cd, const brix_zip_key_t *key, brix_zip_member_t *last, int *found)
int brix_zip_find_member (int fd, off_t archive_size, const char *member, size_t cd_max, brix_zip_member_t *out)
ssize_t brix_zip_extract_full (int fd, const brix_zip_member_t *m, unsigned char *out, size_t outcap)
Macro Definition Documentation
ZIP_CDFH_BASE
#define ZIP_CDFH_BASE 46
Definition at line 25 of file zip_dir.c.
ZIP_CDFH_SIG
#define ZIP_CDFH_SIG 0x02014b50u /* Central Directory File Header */
Definition at line 24 of file zip_dir.c.
ZIP_GPF_DATADESC
#define ZIP_GPF_DATADESC 0x0008u /* general-purpose bit 3 */
Definition at line 28 of file zip_dir.c.
ZIP_GPF_ENCRYPTED
#define ZIP_GPF_ENCRYPTED 0x0001u /* general-purpose bit 0 */
Definition at line 27 of file zip_dir.c.
Function Documentation
brix_zip_extract_full()
ssize_t brix_zip_extract_full (int fd, const brix_zip_member_t * m, unsigned char * out, size_t outcap)
Definition at line 311 of file zip_dir.c.
References brix_size_add(), BRIX_ZIP_METHOD_DEFLATE, BRIX_ZIP_METHOD_STORE, brix_zip_member_t::comp_size, brix_zip_member_t::data_off, brix_zip_member_t::method, pread_full(), and brix_zip_member_t::uncomp_size.
Referenced by zip_http_stage_deflate().
brix_zip_find_member()
int brix_zip_find_member (int fd, off_t archive_size, const char * member, size_t cd_max, brix_zip_member_t * out)
Definition at line 275 of file zip_dir.c.
References BRIX_ZIP_ECORRUPT, BRIX_ZIP_OK, brix_zip_cd_t::buf, key, brix_zip_member_t::name, PATH_MAX, zip_load_cd(), and zip_scan_directory().
Referenced by main(), zip_find_member_mapped(), and zip_http_locate_member().
pread_full()
static int pread_full (int fd, void * buf, size_t n, off_t off) static
Definition at line 31 of file zip_dir.c.
References brix_sd_posix_wrap().
Referenced by brix_zip_extract_full(), zip_fd_pread(), and zip_load_cd().
zip_build_member()
static int zip_build_member (const brix_zip_arc_t * arc, const unsigned char * base, const brix_zip_cdfh_t * rec, brix_zip_member_t * last) static
Definition at line 143 of file zip_dir.c.
References brix_zip_cdfh_t::bits, BRIX_ZIP_ECORRUPT, BRIX_ZIP_METHOD_DEFLATE, BRIX_ZIP_METHOD_STORE, BRIX_ZIP_OK, brix_zip_cdfh_t::comp, brix_zip_member_t::comp_size, brix_zip_cdfh_t::crc32, brix_zip_member_t::crc32, brix_zip_member_t::data_off, brix_zip_cdfh_t::ex, brix_zip_arc_t::fd, brix_zip_cdfh_t::fn, brix_zip_cdfh_t::lhdr_off, brix_zip_cdfh_t::method, brix_zip_member_t::method, brix_zip_member_t::name, brix_zip_arc_t::size, brix_zip_cdfh_t::uncomp, brix_zip_member_t::uncomp_size, zip_apply_zip64_extra(), ZIP_CDFH_BASE, zip_fd_pread(), ZIP_GPF_DATADESC, ZIP_GPF_ENCRYPTED, ZIP_K_OK, zip_map_kernel_rc(), and zip_resolve_data_off().
Referenced by zip_scan_directory().
zip_fd_pread()
static ssize_t zip_fd_pread (void * ctx, uint64_t off, void * buf, size_t len) static
Definition at line 55 of file zip_dir.c.
References pread_full().
Referenced by zip_build_member(), and zip_load_cd().
zip_load_cd()
static int zip_load_cd (int fd, off_t archive_size, size_t cd_max, brix_zip_cd_t * cd) static
Definition at line 204 of file zip_dir.c.
References brix_size_add(), BRIX_ZIP_ECORRUPT, BRIX_ZIP_EIO, BRIX_ZIP_OK, brix_zip_cd_t::buf, brix_zip_cd_t::nrec, pread_full(), brix_zip_cd_t::size, zip_fd_pread(), ZIP_K_OK, zip_locate_cd(), and zip_map_kernel_rc().
Referenced by brix_zip_find_member().
zip_map_kernel_rc()
static int zip_map_kernel_rc (int krc) static
Definition at line 65 of file zip_dir.c.
References BRIX_ZIP_ECORRUPT, BRIX_ZIP_EIO, BRIX_ZIP_OK, ZIP_K_EIO, and ZIP_K_OK.
Referenced by zip_build_member(), and zip_load_cd().
zip_parse_cdfh()
static int zip_parse_cdfh (const unsigned char * cd, uint64_t p, uint64_t cd_size, brix_zip_cdfh_t * rec) static
Definition at line 109 of file zip_dir.c.
References brix_zip_cdfh_t::bits, brix_zip_cdfh_t::cm, brix_zip_cdfh_t::comp, brix_zip_cdfh_t::crc32, brix_zip_cdfh_t::ex, brix_zip_cdfh_t::fn, brix_zip_cdfh_t::lhdr_off, brix_zip_cdfh_t::method, brix_zip_cdfh_t::span, brix_zip_cdfh_t::uncomp, ZIP_CDFH_BASE, ZIP_CDFH_SIG, zip_rd16le(), and zip_rd32le().
Referenced by zip_scan_directory().
zip_scan_directory()
static int zip_scan_directory (const brix_zip_arc_t * arc, const brix_zip_cd_t * cd, const brix_zip_key_t * key, brix_zip_member_t * last, int * found) static
Definition at line 247 of file zip_dir.c.
References BRIX_ZIP_ECORRUPT, BRIX_ZIP_NOMEMBER, BRIX_ZIP_OK, brix_zip_cd_t::buf, brix_zip_cdfh_t::fn, key, brix_zip_cd_t::nrec, brix_zip_cd_t::size, brix_zip_cdfh_t::span, zip_build_member(), ZIP_CDFH_BASE, and zip_parse_cdfh().
Referenced by brix_zip_find_member().