nginx-xrootd: src/protocols/root/zip/zip_http.c File Reference
zip_http.c File Reference
#include "zip_http.h"
#include "zip_dir.h"
#include "fs/vfs/vfs.h"
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <sys/stat.h>
Data Structures
struct zip_http_span_t
Macros
#define ZIP_HTTP_MEM_MAX (512u * 1024u * 1024u)
Functions
static int zip_http_name_ok (const char *out, size_t n)
int brix_zip_http_member_arg (ngx_http_request_t *r, char *out, size_t outsz)
static void zip_http_close_fd (void *data)
static ngx_int_t zip_http_open_archive (ngx_http_request_t *r, const char *root_canon, const char *archive_full, brix_vfs_file_t **fhp, off_t *sizep)
static ngx_int_t zip_http_locate_member (brix_vfs_file_t *fh, off_t archive_size, const char *member, size_t cd_max, brix_zip_member_t *m)
static ngx_int_t zip_http_parse_range (ngx_http_request_t *r, zip_http_span_t *sp)
static ngx_int_t zip_http_stage_stored (ngx_http_request_t *r, brix_vfs_file_t *fh, const brix_zip_member_t *m, const zip_http_span_t *sp, ngx_buf_t *b)
static ngx_int_t zip_http_stage_deflate (ngx_http_request_t *r, brix_vfs_file_t *fh, const brix_zip_member_t *m, const zip_http_span_t *sp, ngx_buf_t *b)
static void zip_http_set_headers (ngx_http_request_t *r, const zip_http_span_t *sp)
ngx_int_t brix_zip_http_serve (ngx_http_request_t *r, const char *root_canon, size_t cd_max, const char *archive_full, const char *member)
Macro Definition Documentation
ZIP_HTTP_MEM_MAX
#define ZIP_HTTP_MEM_MAX (512u * 1024u * 1024u)
Definition at line 21 of file zip_http.c.
Function Documentation
brix_zip_http_member_arg()
int brix_zip_http_member_arg (ngx_http_request_t * r, char * out, size_t outsz)
Definition at line 42 of file zip_http.c.
References s, and zip_http_name_ok().
Referenced by get_zip_member_serve(), and s3_get_serve_zip_member().
brix_zip_http_serve()
ngx_int_t brix_zip_http_serve (ngx_http_request_t * r, const char * root_canon, size_t cd_max, const char * archive_full, const char * member)
Definition at line 312 of file zip_http.c.
References brix_vfs_close(), BRIX_ZIP_METHOD_STORE, zip_http_span_t::len, brix_zip_member_t::method, ngx_pcalloc(), zip_http_span_t::start, zip_http_span_t::total, brix_zip_member_t::uncomp_size, zip_http_locate_member(), zip_http_open_archive(), zip_http_parse_range(), zip_http_set_headers(), zip_http_stage_deflate(), and zip_http_stage_stored().
Referenced by get_zip_member_serve(), and s3_get_serve_zip_member().
zip_http_close_fd()
static void zip_http_close_fd (void * data) static
Definition at line 70 of file zip_http.c.
References close().
Referenced by zip_http_stage_stored().
zip_http_locate_member()
static ngx_int_t zip_http_locate_member (brix_vfs_file_t * fh, off_t archive_size, const char * member, size_t cd_max, brix_zip_member_t * m) static
Definition at line 143 of file zip_http.c.
References brix_vfs_file_fd(), BRIX_ZIP_EIO, brix_zip_find_member(), BRIX_ZIP_NOMEMBER, and BRIX_ZIP_OK.
Referenced by brix_zip_http_serve().
zip_http_name_ok()
static int zip_http_name_ok (const char * out, size_t n) static
Definition at line 24 of file zip_http.c.
Referenced by brix_zip_http_member_arg().
zip_http_open_archive()
static ngx_int_t zip_http_open_archive (ngx_http_request_t * r, const char * root_canon, const char * archive_full, brix_vfs_file_t ** fhp, off_t * sizep) static
Definition at line 96 of file zip_http.c.
References BRIX_PROTO_WEBDAV, brix_vfs_close(), brix_vfs_ctx_init(), brix_vfs_file_fd(), BRIX_VFS_O_READ, brix_vfs_open(), fstat(), and stat().
Referenced by brix_zip_http_serve().
zip_http_parse_range()
static ngx_int_t zip_http_parse_range (ngx_http_request_t * r, zip_http_span_t * sp) static
Definition at line 168 of file zip_http.c.
References zip_http_span_t::len, zip_http_span_t::start, and zip_http_span_t::total.
Referenced by brix_zip_http_serve().
zip_http_set_headers()
static void zip_http_set_headers (ngx_http_request_t * r, const zip_http_span_t * sp) static
Definition at line 283 of file zip_http.c.
References zip_http_span_t::len, ngx_pnalloc(), zip_http_span_t::start, and zip_http_span_t::total.
Referenced by brix_zip_http_serve().
zip_http_stage_deflate()
static ngx_int_t zip_http_stage_deflate (ngx_http_request_t * r, brix_vfs_file_t * fh, const brix_zip_member_t * m, const zip_http_span_t * sp, ngx_buf_t * b) static
Definition at line 250 of file zip_http.c.
References brix_vfs_close(), brix_vfs_file_fd(), brix_zip_extract_full(), zip_http_span_t::len, zip_http_span_t::start, brix_zip_member_t::uncomp_size, and ZIP_HTTP_MEM_MAX.
Referenced by brix_zip_http_serve().
zip_http_stage_stored()
static ngx_int_t zip_http_stage_stored (ngx_http_request_t * r, brix_vfs_file_t * fh, const brix_zip_member_t * m, const zip_http_span_t * sp, ngx_buf_t * b) static
Definition at line 216 of file zip_http.c.
References brix_vfs_close(), brix_vfs_file_fd(), close(), brix_zip_member_t::data_off, zip_http_span_t::len, ngx_pcalloc(), zip_http_span_t::start, and zip_http_close_fd().
Referenced by brix_zip_http_serve().