nginx-xrootd: src/protocols/root/zip/zip_http.h File Reference
zip_http.h File Reference
#include <ngx_config.h>
#include <ngx_core.h>
#include <ngx_http.h>
Functions
int brix_zip_http_member_arg (ngx_http_request_t *r, char *out, size_t outsz)
ngx_int_t brix_zip_http_serve (ngx_http_request_t *r, const char *root_canon, size_t cd_max, const char *archive_full, const char *member)
Function Documentation
brix_zip_http_member_arg()
int brix_zip_http_member_arg (ngx_http_request_t * r, char * out, size_t outsz)
Definition at line 42 of file zip_http.c.
References s, and zip_http_name_ok().
Referenced by s3_handle_get(), and webdav_handle_get().
brix_zip_http_serve()
ngx_int_t brix_zip_http_serve (ngx_http_request_t * r, const char * root_canon, size_t cd_max, const char * archive_full, const char * member)
Definition at line 79 of file zip_http.c.
References BRIX_PROTO_WEBDAV, brix_vfs_close(), brix_vfs_ctx_init(), brix_vfs_file_fd(), BRIX_VFS_O_READ, brix_vfs_open(), BRIX_ZIP_EIO, brix_zip_extract_full(), brix_zip_find_member(), BRIX_ZIP_METHOD_STORE, BRIX_ZIP_NOMEMBER, BRIX_ZIP_OK, close(), fstat(), brix_vfs_ctx_t::pool, stat(), zip_http_close_fd(), and ZIP_HTTP_MEM_MAX.
Referenced by s3_handle_get(), and webdav_handle_get().