nginx-xrootd: src/protocols/root/zip/zip_member.c File Reference
zip_member.c File Reference
#include "zip_member.h"
#include "fs/vfs/vfs.h"
#include "zip_dir.h"
#include "fs/backend/sd.h"
#include "fs/core/vfs_core.h"
#include <stdlib.h>
#include "protocols/root/connection/fd_table.h"
#include "fs/path/beneath.h"
#include "fs/path/path.h"
#include "protocols/root/session/registry.h"
#include "protocols/root/response/response.h"
#include "protocols/root/protocol/wire_core_requests.h"
#include "protocols/root/protocol/opcodes.h"
#include "core/types/tunables.h"
#include "core/compat/codec_core.h"
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <sys/stat.h>
#include <zlib.h>
Data Structures
struct zip_infl_t
struct zip_open_req_t
Macros
#define ZIP_INFL_SCRATCH (64 * 1024)
Functions
static void zip_deflate_free (brix_file_t *fh)
static int zip_deflate_reset (brix_file_t *fh)
static ssize_t zip_deflate_pump (brix_file_t *fh, u_char *out, size_t want)
static ssize_t zip_deflate_read (brix_file_t *fh, uint64_t offset, u_char *out, size_t want)
static ssize_t zip_pread_full (int fd, u_char *buf, size_t n, off_t off)
static ngx_int_t zip_open_error (const zip_open_req_t *rq, int code, const char *msg)
static ngx_int_t zip_open_archive_fd (const zip_open_req_t *rq, int *fd_out, struct stat *ast_out, ngx_int_t *out)
static ngx_int_t zip_stage_archive_maybe (const zip_open_req_t *rq, int *fd, const struct stat *ast, ngx_int_t *out)
static ngx_int_t zip_find_member_mapped (const zip_open_req_t *rq, int fd, const struct stat *ast, brix_zip_member_t *m_out, ngx_int_t *out)
static void zip_handle_populate (brix_ctx_t *ctx, int idx, int fd, const struct stat *ast, const brix_zip_member_t *m)
static ngx_int_t zip_send_open_reply (const zip_open_req_t *rq, int idx, const struct stat *ast, const brix_zip_member_t *m, uint16_t options)
ngx_int_t brix_zip_open_member (brix_ctx_t *ctx, ngx_connection_t *c, ngx_stream_brix_srv_conf_t *conf, const char *archive_logical, const char *archive_full, const char *member, uint16_t options)
ngx_int_t brix_zip_read (brix_ctx_t *ctx, ngx_connection_t *c, int idx, int64_t offset, size_t rlen)
void brix_zip_handle_cleanup (brix_file_t *fh)
Macro Definition Documentation
ZIP_INFL_SCRATCH
#define ZIP_INFL_SCRATCH (64 * 1024)
Definition at line 54 of file zip_member.c.
Function Documentation
brix_zip_handle_cleanup()
void brix_zip_handle_cleanup (brix_file_t * fh)
Definition at line 546 of file zip_member.c.
References zip_deflate_free().
Referenced by fhandle_reset_slot().
brix_zip_open_member()
ngx_int_t brix_zip_open_member (brix_ctx_t * ctx, ngx_connection_t * c, ngx_stream_brix_srv_conf_t * conf, const char * archive_logical, const char * archive_full, const char * member, uint16_t options)
Definition at line 453 of file zip_member.c.
References brix_alloc_fhandle(), brix_free_fhandle(), BRIX_OP_OPEN_RD, BRIX_RETURN_ERR, brix_session_handle_publish(), brix_set_fhandle_path(), c, close(), brix_ctx_t::files, brix_ctx_t::is_bound, kXR_ServerError, brix_ctx_t::login, brix_ctx_login_t::sessid, stat(), zip_find_member_mapped(), zip_handle_populate(), zip_open_archive_fd(), zip_send_open_reply(), and zip_stage_archive_maybe().
Referenced by brix_open_read_resolve().
brix_zip_read()
ngx_int_t brix_zip_read (brix_ctx_t * ctx, ngx_connection_t * c, int idx, int64_t offset, size_t rlen)
Definition at line 496 of file zip_member.c.
References BRIX_OP_OK, BRIX_OP_READ, BRIX_RETURN_ERR, brix_send_error(), brix_send_ok(), BRIX_ZIP_METHOD_STORE, brix_file_t::bytes_read, c, brix_file_t::fd, brix_ctx_t::files, kXR_IOError, kXR_NoMemory, brix_file_t::path, brix_file_t::zip_data_off, zip_deflate_read(), brix_file_t::zip_method, zip_pread_full(), and brix_file_t::zip_uncomp_size.
Referenced by brix_handle_read().
zip_deflate_free()
static void zip_deflate_free (brix_file_t * fh) static
Definition at line 57 of file zip_member.c.
References zip_infl_t::inited, brix_file_t::zip_inflate, and zip_infl_t::zs.
Referenced by brix_zip_handle_cleanup(), and zip_deflate_reset().
zip_deflate_pump()
static ssize_t zip_deflate_pump (brix_file_t * fh, u_char * out, size_t want) static
Definition at line 99 of file zip_member.c.
References brix_sd_posix_wrap(), zip_infl_t::cin, brix_file_t::fd, zip_infl_t::in_fed, brix_file_t::zip_comp_pos, brix_file_t::zip_comp_size, brix_file_t::zip_data_off, ZIP_INFL_SCRATCH, brix_file_t::zip_inflate, brix_file_t::zip_logical_pos, and zip_infl_t::zs.
Referenced by zip_deflate_read().
zip_deflate_read()
static ssize_t zip_deflate_read (brix_file_t * fh, uint64_t offset, u_char * out, size_t want) static
Definition at line 169 of file zip_member.c.
References zip_deflate_pump(), zip_deflate_reset(), ZIP_INFL_SCRATCH, brix_file_t::zip_inflate, and brix_file_t::zip_logical_pos.
Referenced by brix_zip_read().
zip_deflate_reset()
static int zip_deflate_reset (brix_file_t * fh) static
Definition at line 72 of file zip_member.c.
References zip_infl_t::in_fed, zip_infl_t::inited, brix_file_t::zip_comp_pos, zip_deflate_free(), brix_file_t::zip_inflate, brix_file_t::zip_logical_pos, and zip_infl_t::zs.
Referenced by zip_deflate_read().
zip_find_member_mapped()
static ngx_int_t zip_find_member_mapped (const zip_open_req_t * rq, int fd, const struct stat * ast, brix_zip_member_t * m_out, ngx_int_t * out) static
Definition at line 333 of file zip_member.c.
References BRIX_ZIP_EIO, brix_zip_find_member(), BRIX_ZIP_NOMEMBER, BRIX_ZIP_OK, close(), zip_open_req_t::conf, kXR_IOError, kXR_NotFound, kXR_Unsupported, zip_open_req_t::member, and zip_open_error().
Referenced by brix_zip_open_member().
zip_handle_populate()
static void zip_handle_populate (brix_ctx_t * ctx, int idx, int fd, const struct stat * ast, const brix_zip_member_t * m) static
Definition at line 363 of file zip_member.c.
References BRIX_CODEC_IDENTITY, brix_file_t::bytes_read, brix_file_t::bytes_written, brix_file_t::cached_size, brix_zip_member_t::comp_size, brix_zip_member_t::crc32, brix_file_t::dashboard_slot, brix_zip_member_t::data_off, brix_file_t::device, brix_file_t::fd, brix_ctx_t::files, brix_file_t::from_cache, brix_file_t::inode, brix_file_t::is_regular, brix_zip_member_t::method, brix_file_t::open_time, brix_file_t::read_ahead_end, brix_file_t::read_codec, brix_file_t::read_last_end, brix_file_t::readable, brix_zip_member_t::uncomp_size, brix_file_t::writable, brix_file_t::write_codec, brix_file_t::zip_comp_pos, brix_file_t::zip_comp_size, brix_file_t::zip_crc32, brix_file_t::zip_data_off, brix_file_t::zip_inflate, brix_file_t::zip_logical_pos, brix_file_t::zip_method, brix_file_t::zip_mode, and brix_file_t::zip_uncomp_size.
Referenced by brix_zip_open_member().
zip_open_archive_fd()
static ngx_int_t zip_open_archive_fd (const zip_open_req_t * rq, int * fd_out, struct stat * ast_out, ngx_int_t * out) static
Definition at line 255 of file zip_member.c.
References zip_open_req_t::archive_logical, brix_vfs_open_fd_at(), close(), zip_open_req_t::conf, fstat(), kXR_IOError, kXR_NotAuthorized, kXR_NotFound, and zip_open_error().
Referenced by brix_zip_open_member().
zip_open_error()
static ngx_int_t zip_open_error (const zip_open_req_t * rq, int code, const char * msg) static
Definition at line 237 of file zip_member.c.
References zip_open_req_t::archive_full, brix_log_access(), BRIX_OP_ERR, BRIX_OP_OPEN_RD, brix_send_error(), zip_open_req_t::c, code, and zip_open_req_t::ctx.
Referenced by zip_find_member_mapped(), zip_open_archive_fd(), and zip_stage_archive_maybe().
zip_pread_full()
static ssize_t zip_pread_full (int fd, u_char * buf, size_t n, off_t off) static
Definition at line 190 of file zip_member.c.
References brix_sd_posix_wrap().
Referenced by brix_zip_read().
zip_send_open_reply()
static ngx_int_t zip_send_open_reply (const zip_open_req_t * rq, int idx, const struct stat * ast, const brix_zip_member_t * m, uint16_t options) static
Definition at line 407 of file zip_member.c.
References zip_open_req_t::archive_full, brix_build_resp_hdr(), brix_free_fhandle(), brix_log_access(), BRIX_OP_OK, BRIX_OP_OPEN_RD, brix_queue_response(), c, zip_open_req_t::c, zip_open_req_t::ctx, brix_ctx_recv_t::cur_streamid, ServerOpenBody::fhandle, kXR_ok, kXR_readable, kXR_retstat, ngx_memcpy, brix_ctx_t::recv, brix_zip_member_t::uncomp_size, and XRD_RESPONSE_HDR_LEN.
Referenced by brix_zip_open_member().
zip_stage_archive_maybe()
static ngx_int_t zip_stage_archive_maybe (const zip_open_req_t * rq, int * fd, const struct stat * ast, ngx_int_t * out) static
Definition at line 290 of file zip_member.c.
References zip_open_req_t::c, close(), zip_open_req_t::conf, kXR_IOError, xvfs_stage_fd(), and zip_open_error().
Referenced by brix_zip_open_member().