nginx-xrootd: src/protocols/root/zip/zip_kernel.c File Reference
zip_kernel.c File Reference
#include "zip_kernel.h"
#include <stdlib.h>
#include <string.h>
Macros
#define ZIPK_EOCD_SIG 0x06054b50u /* End Of Central Directory */
#define ZIPK_EOCD_BASE 22
#define ZIPK_Z64LOC_SIG 0x07064b50u /* ZIP64 EOCD locator */
#define ZIPK_Z64LOC_SIZE 20
#define ZIPK_Z64EOCD_SIG 0x06064b50u /* ZIP64 EOCD */
#define ZIPK_Z64EOCD_SZ 56
#define ZIPK_LFH_SIG 0x04034b50u /* Local File Header */
#define ZIPK_LFH_BASE 30
#define ZIPK_U32_MAX 0xFFFFFFFFu
#define ZIPK_U16_MAX 0xFFFFu
#define ZIPK_MAX_COMMENT 65535 /* EOCD comment length cap (u16) */
Functions
uint16_t zip_rd16le (const uint8_t *p)
uint32_t zip_rd32le (const uint8_t *p)
uint64_t zip_rd64le (const uint8_t *p)
int zip_read_at (zip_pread_fn pread, void *ctx, uint64_t archive_size, uint64_t off, void *buf, size_t len)
static int zip_promote_zip64 (zip_pread_fn pread, void *ctx, uint64_t archive_size, uint64_t eocd_pos, uint64_t *cd_off, uint64_t *cd_size, uint64_t *n_entries)
int zip_locate_cd (zip_pread_fn pread, void *ctx, uint64_t archive_size, uint64_t cd_max, uint64_t max_entries, uint64_t *cd_off, uint64_t *cd_size, uint64_t *n_entries)
void zip_apply_zip64_extra (const uint8_t *extra, size_t extra_len, uint64_t *uncomp, uint64_t *comp, uint64_t *lhdr_off)
int zip_resolve_data_off (zip_pread_fn pread, void *ctx, uint64_t archive_size, uint64_t lhdr_off, uint64_t comp_size, uint64_t *data_off)
Macro Definition Documentation
ZIPK_EOCD_BASE
#define ZIPK_EOCD_BASE 22
Definition at line 17 of file zip_kernel.c.
ZIPK_EOCD_SIG
#define ZIPK_EOCD_SIG 0x06054b50u /* End Of Central Directory */
Definition at line 16 of file zip_kernel.c.
ZIPK_LFH_BASE
#define ZIPK_LFH_BASE 30
Definition at line 23 of file zip_kernel.c.
ZIPK_LFH_SIG
#define ZIPK_LFH_SIG 0x04034b50u /* Local File Header */
Definition at line 22 of file zip_kernel.c.
ZIPK_MAX_COMMENT
#define ZIPK_MAX_COMMENT 65535 /* EOCD comment length cap (u16) */
Definition at line 28 of file zip_kernel.c.
ZIPK_U16_MAX
#define ZIPK_U16_MAX 0xFFFFu
Definition at line 26 of file zip_kernel.c.
ZIPK_U32_MAX
#define ZIPK_U32_MAX 0xFFFFFFFFu
Definition at line 25 of file zip_kernel.c.
ZIPK_Z64EOCD_SIG
#define ZIPK_Z64EOCD_SIG 0x06064b50u /* ZIP64 EOCD */
Definition at line 20 of file zip_kernel.c.
ZIPK_Z64EOCD_SZ
#define ZIPK_Z64EOCD_SZ 56
Definition at line 21 of file zip_kernel.c.
ZIPK_Z64LOC_SIG
#define ZIPK_Z64LOC_SIG 0x07064b50u /* ZIP64 EOCD locator */
Definition at line 18 of file zip_kernel.c.
ZIPK_Z64LOC_SIZE
#define ZIPK_Z64LOC_SIZE 20
Definition at line 19 of file zip_kernel.c.
Function Documentation
zip_apply_zip64_extra()
void zip_apply_zip64_extra (const uint8_t * extra, size_t extra_len, uint64_t * uncomp, uint64_t * comp, uint64_t * lhdr_off)
Definition at line 184 of file zip_kernel.c.
References zip_rd16le(), zip_rd64le(), and ZIPK_U32_MAX.
Referenced by apply_zip64_extra(), and zip_build_member().
zip_locate_cd()
int zip_locate_cd (zip_pread_fn pread, void * ctx, uint64_t archive_size, uint64_t cd_max, uint64_t max_entries, uint64_t * cd_off, uint64_t * cd_size, uint64_t * n_entries)
Definition at line 113 of file zip_kernel.c.
References pread(), ZIP_K_ECORRUPT, ZIP_K_EIO, ZIP_K_ENOTZIP, ZIP_K_OK, zip_promote_zip64(), zip_rd16le(), zip_rd32le(), zip_read_at(), ZIPK_EOCD_BASE, ZIPK_EOCD_SIG, and ZIPK_MAX_COMMENT.
Referenced by find_eocd(), and zip_load_cd().
zip_promote_zip64()
static int zip_promote_zip64 (zip_pread_fn pread, void * ctx, uint64_t archive_size, uint64_t eocd_pos, uint64_t * cd_off, uint64_t * cd_size, uint64_t * n_entries) static
Definition at line 77 of file zip_kernel.c.
References pread(), ZIP_K_ECORRUPT, ZIP_K_OK, zip_rd32le(), zip_rd64le(), zip_read_at(), ZIPK_U16_MAX, ZIPK_U32_MAX, ZIPK_Z64EOCD_SIG, ZIPK_Z64EOCD_SZ, ZIPK_Z64LOC_SIG, and ZIPK_Z64LOC_SIZE.
Referenced by zip_locate_cd().
zip_rd16le()
uint16_t zip_rd16le (const uint8_t * p)
Definition at line 32 of file zip_kernel.c.
Referenced by le16(), zip_apply_zip64_extra(), zip_locate_cd(), zip_parse_cdfh(), and zip_resolve_data_off().
zip_rd32le()
uint32_t zip_rd32le (const uint8_t * p)
Definition at line 37 of file zip_kernel.c.
Referenced by le32(), zip_locate_cd(), zip_parse_cdfh(), zip_promote_zip64(), zip_rd64le(), and zip_resolve_data_off().
zip_rd64le()
uint64_t zip_rd64le (const uint8_t * p)
Definition at line 43 of file zip_kernel.c.
References zip_rd32le().
Referenced by le64(), zip_apply_zip64_extra(), and zip_promote_zip64().
zip_read_at()
int zip_read_at (zip_pread_fn pread, void * ctx, uint64_t archive_size, uint64_t off, void * buf, size_t len)
Definition at line 51 of file zip_kernel.c.
References pread(), ZIP_K_ECORRUPT, ZIP_K_EIO, and ZIP_K_OK.
Referenced by read_exact(), zip_locate_cd(), zip_promote_zip64(), and zip_resolve_data_off().
zip_resolve_data_off()
int zip_resolve_data_off (zip_pread_fn pread, void * ctx, uint64_t archive_size, uint64_t lhdr_off, uint64_t comp_size, uint64_t * data_off)
Definition at line 216 of file zip_kernel.c.
References pread(), ZIP_K_ECORRUPT, ZIP_K_OK, zip_rd16le(), zip_rd32le(), zip_read_at(), ZIPK_LFH_BASE, and ZIPK_LFH_SIG.
Referenced by member_data_offset(), and zip_build_member().