nginx-xrootd: src/protocols/root/zip/zip_dir_unittest.c File Reference
zip_dir_unittest.c File Reference
#include "zip_dir.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <zlib.h>
Macros
#define CHECK(cond, msg)
Functions
static int verify_content (int fd, const brix_zip_member_t *m, const unsigned char *want, size_t want_len)
int main (int argc, char **argv)
Variables
static int failures = 0
Macro Definition Documentation
CHECK
#define CHECK (cond, msg)
Value:
    do { \
    if (!(cond)) { fprintf(stderr, "FAIL: %s\n", msg); failures++; } \
    else { printf("ok: %s\n", msg); } } while (0)
Definition at line 26 of file zip_dir_unittest.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 69 of file zip_dir_unittest.c.
References BRIX_ZIP_ECORRUPT, brix_zip_find_member(), BRIX_ZIP_METHOD_DEFLATE, BRIX_ZIP_METHOD_STORE, BRIX_ZIP_NOMEMBER, BRIX_ZIP_OK, CHECK, close(), brix_zip_member_t::comp_size, failures, fstat(), brix_zip_member_t::method, open(), stat(), brix_zip_member_t::uncomp_size, and verify_content().
verify_content()
static int verify_content (int fd, const brix_zip_member_t * m, const unsigned char * want, size_t want_len) static
Definition at line 32 of file zip_dir_unittest.c.
References BRIX_ZIP_METHOD_STORE, brix_zip_member_t::comp_size, brix_zip_member_t::data_off, brix_zip_member_t::method, pread(), and brix_zip_member_t::uncomp_size.
Referenced by main().
Variable Documentation
failures
int failures = 0 static
Definition at line 25 of file zip_dir_unittest.c.
Referenced by main().