nginx-xrootd: src/protocols/root/zip/zip_kernel.h File Reference
zip_kernel.h File Reference
#include <stdint.h>
#include <stddef.h>
#include <sys/types.h>
Macros
#define ZIP_K_OK 0
#define ZIP_K_ENOTZIP (-1) /* no End-Of-Central-Directory record found */
#define ZIP_K_ECORRUPT (-2) /* malformed / failed bounds check / cap exceeded */
#define ZIP_K_EIO (-3) /* the pread callback failed */
Typedefs
typedef ssize_t(* zip_pread_fn) (void *ctx, uint64_t off, void *buf, size_t len)
Functions
uint16_t zip_rd16le (const uint8_t *p)
uint32_t zip_rd32le (const uint8_t *p)
uint64_t zip_rd64le (const uint8_t *p)
int zip_read_at (zip_pread_fn pread, void *ctx, uint64_t archive_size, uint64_t off, void *buf, size_t len)
int zip_locate_cd (zip_pread_fn pread, void *ctx, uint64_t archive_size, uint64_t cd_max, uint64_t max_entries, uint64_t *cd_off, uint64_t *cd_size, uint64_t *n_entries)
void zip_apply_zip64_extra (const uint8_t *extra, size_t extra_len, uint64_t *uncomp, uint64_t *comp, uint64_t *lhdr_off)
int zip_resolve_data_off (zip_pread_fn pread, void *ctx, uint64_t archive_size, uint64_t lhdr_off, uint64_t comp_size, uint64_t *data_off)
Macro Definition Documentation
ZIP_K_ECORRUPT
#define ZIP_K_ECORRUPT (-2) /* malformed / failed bounds check / cap exceeded */
Definition at line 41 of file zip_kernel.h.
ZIP_K_EIO
#define ZIP_K_EIO (-3) /* the pread callback failed */
Definition at line 42 of file zip_kernel.h.
ZIP_K_ENOTZIP
#define ZIP_K_ENOTZIP (-1) /* no End-Of-Central-Directory record found */
Definition at line 40 of file zip_kernel.h.
ZIP_K_OK
#define ZIP_K_OK 0
Definition at line 39 of file zip_kernel.h.
Typedef Documentation
zip_pread_fn
typedef ssize_t(* zip_pread_fn) (void *ctx, uint64_t off, void *buf, size_t len)
Definition at line 36 of file zip_kernel.h.
Function Documentation
zip_apply_zip64_extra()
void zip_apply_zip64_extra (const uint8_t * extra, size_t extra_len, uint64_t * uncomp, uint64_t * comp, uint64_t * lhdr_off)
Definition at line 184 of file zip_kernel.c.
References zip_rd16le(), zip_rd64le(), and ZIPK_U32_MAX.
Referenced by apply_zip64_extra(), and brix_zip_find_member().
zip_locate_cd()
int zip_locate_cd (zip_pread_fn pread, void * ctx, uint64_t archive_size, uint64_t cd_max, uint64_t max_entries, uint64_t * cd_off, uint64_t * cd_size, uint64_t * n_entries)
Definition at line 113 of file zip_kernel.c.
References pread(), ZIP_K_ECORRUPT, ZIP_K_EIO, ZIP_K_ENOTZIP, ZIP_K_OK, zip_promote_zip64(), zip_rd16le(), zip_rd32le(), zip_read_at(), ZIPK_EOCD_BASE, ZIPK_EOCD_SIG, and ZIPK_MAX_COMMENT.
Referenced by brix_zip_find_member(), and find_eocd().
zip_rd16le()
uint16_t zip_rd16le (const uint8_t * p)
Definition at line 32 of file zip_kernel.c.
Referenced by brix_zip_find_member(), le16(), zip_apply_zip64_extra(), zip_locate_cd(), and zip_resolve_data_off().
zip_rd32le()
uint32_t zip_rd32le (const uint8_t * p)
Definition at line 37 of file zip_kernel.c.
Referenced by brix_zip_find_member(), le32(), zip_locate_cd(), zip_promote_zip64(), zip_rd64le(), and zip_resolve_data_off().
zip_rd64le()
uint64_t zip_rd64le (const uint8_t * p)
Definition at line 43 of file zip_kernel.c.
References zip_rd32le().
Referenced by le64(), zip_apply_zip64_extra(), and zip_promote_zip64().
zip_read_at()
int zip_read_at (zip_pread_fn pread, void * ctx, uint64_t archive_size, uint64_t off, void * buf, size_t len)
Definition at line 51 of file zip_kernel.c.
References pread(), ZIP_K_ECORRUPT, ZIP_K_EIO, and ZIP_K_OK.
Referenced by read_exact(), zip_locate_cd(), zip_promote_zip64(), and zip_resolve_data_off().
zip_resolve_data_off()
int zip_resolve_data_off (zip_pread_fn pread, void * ctx, uint64_t archive_size, uint64_t lhdr_off, uint64_t comp_size, uint64_t * data_off)
Definition at line 216 of file zip_kernel.c.
References pread(), ZIP_K_ECORRUPT, ZIP_K_OK, zip_rd16le(), zip_rd32le(), zip_read_at(), ZIPK_LFH_BASE, and ZIPK_LFH_SIG.
Referenced by brix_zip_find_member(), and member_data_offset().