nginx-xrootd: client/lib/protocols/shared/zip.c File Reference
zip.c File Reference
#include "zip_internal.h"
#include "protocols/root/zip/zip_kernel.h"
Data Structures
struct zip_cd_t
struct zip_extract_t
Enumerations
enum { ZIP_CDFH_FIXED = 46 , ZIP_CD_STOP = 1 }
enum { ZIP_EXTRACT_CHUNK = 64 * 1024 }
Functions
static int zip_map_kernel_rc (int krc)
uint16_t le16 (const uint8_t *p)
uint32_t le32 (const uint8_t *p)
uint64_t le64 (const uint8_t *p)
int read_exact (brix_zip_pread_fn pread, void *ctx, uint64_t off, uint64_t archive_size, void *buf, size_t len)
int find_eocd (brix_zip_pread_fn pread, void *ctx, uint64_t asize, uint64_t *cd_off, uint64_t *cd_size, uint64_t *n_entries)
void apply_zip64_extra (brix_zip_entry *ent, const uint8_t *extra, size_t extra_len)
static int zip_read_central_dir (brix_zip_pread_fn pread, void *ctx, uint64_t archive_size, zip_cd_t *cd)
static int zip_parse_cd_entry (const uint8_t *cd, uint64_t cd_size, size_t *pos, uint64_t archive_size, brix_zip_entry *ent)
int brix_zip_open (brix_zip_pread_fn pread, void *ctx, uint64_t archive_size, brix_zip_dir *out)
const brix_zip_entry * brix_zip_find (const brix_zip_dir *d, const char *name)
void brix_zip_dir_free (brix_zip_dir *d)
int member_data_offset (brix_zip_pread_fn pread, void *ctx, uint64_t asize, const brix_zip_entry *e, uint64_t *data_off)
int sink_output (brix_zip_sink_fn sink, void *sink_ctx, const uint8_t *data, size_t len, uLong *crc, uint64_t *produced, uint64_t uncomp_size)
static int zip_extract_setup (zip_extract_t *ex)
static void zip_extract_teardown (zip_extract_t *ex)
static int zip_extract_inflate_chunk (zip_extract_t *ex, size_t len)
static int zip_extract_stream (zip_extract_t *ex)
static int zip_extract_verify (const zip_extract_t *ex)
int brix_zip_member_extract (brix_zip_pread_fn pread, void *ctx, const brix_zip_entry *e, brix_zip_sink_fn sink, void *sink_ctx)
void put16 (uint8_t *p, uint16_t v)
void put32 (uint8_t *p, uint32_t v)
void put64 (uint8_t *p, uint64_t v)
int brix_zip_read_eocd (brix_zip_pread_fn pread_cb, void *ctx, uint64_t archive_size, uint64_t *cd_off, uint64_t *cd_size, uint64_t *n_entries, int *is_zip64)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ZIP_CDFH_FIXED
ZIP_CD_STOP
Definition at line 137 of file zip.c.
anonymous enum
anonymous enum
Enumerator
ZIP_EXTRACT_CHUNK
Definition at line 304 of file zip.c.
Function Documentation
apply_zip64_extra()
void apply_zip64_extra (brix_zip_entry * ent, const uint8_t * extra, size_t extra_len)
Definition at line 61 of file zip.c.
References brix_zip_entry::comp_size, brix_zip_entry::lfh_off, brix_zip_entry::uncomp_size, and zip_apply_zip64_extra().
Referenced by zip_parse_cd_entry().
brix_zip_dir_free()
void brix_zip_dir_free (brix_zip_dir * d)
Definition at line 257 of file zip.c.
References brix_zip_dir::entries, brix_zip_dir::n, and brix_zip_entry::name.
Referenced by brix_zip_open(), and copy_unzip_extract_member().
brix_zip_find()
const brix_zip_entry * brix_zip_find (const brix_zip_dir * d, const char * name)
Definition at line 240 of file zip.c.
References brix_zip_dir::entries, brix_zip_dir::n, brix_zip_entry::name, and name.
Referenced by copy_unzip_extract_member().
brix_zip_member_extract()
int brix_zip_member_extract (brix_zip_pread_fn pread, void * ctx, const brix_zip_entry * e, brix_zip_sink_fn sink, void * sink_ctx)
Definition at line 488 of file zip.c.
References brix_zip_entry::archive_size, zip_extract_t::crc, zip_extract_t::data_off, zip_extract_t::e, member_data_offset(), brix_zip_entry::method, zip_extract_t::pread, pread(), zip_extract_t::pread_ctx, zip_extract_t::sink, zip_extract_t::sink_ctx, brix_zip_entry::uncomp_size, XRDC_ZIP_EBOMB, XRDC_ZIP_EMETHOD, XRDC_ZIP_MAX_OUTPUT, XRDC_ZIP_OK, zip_extract_setup(), zip_extract_stream(), zip_extract_teardown(), and zip_extract_verify().
Referenced by copy_unzip_extract_member().
brix_zip_open()
int brix_zip_open (brix_zip_pread_fn pread, void * ctx, uint64_t archive_size, brix_zip_dir * out)
Definition at line 195 of file zip.c.
References brix_zip_dir::archive_size, brix_zip_dir_free(), zip_cd_t::bytes, brix_zip_dir::entries, brix_zip_dir::n, zip_cd_t::n_entries, pread(), zip_cd_t::size, XRDC_ZIP_EBADF, XRDC_ZIP_ENOMEM, XRDC_ZIP_OK, ZIP_CD_STOP, ZIP_CDFH_FIXED, zip_parse_cd_entry(), and zip_read_central_dir().
Referenced by copy_unzip_extract_member().
brix_zip_read_eocd()
int brix_zip_read_eocd (brix_zip_pread_fn pread_cb, void * ctx, uint64_t archive_size, uint64_t * cd_off, uint64_t * cd_size, uint64_t * n_entries, int * is_zip64)
Definition at line 550 of file zip.c.
References find_eocd(), and XRDC_ZIP_OK.
Referenced by zip_read_seed().
find_eocd()
int find_eocd (brix_zip_pread_fn pread, void * ctx, uint64_t asize, uint64_t * cd_off, uint64_t * cd_size, uint64_t * n_entries)
Definition at line 49 of file zip.c.
References pread(), XRDC_ZIP_MAX_CD_SIZE, XRDC_ZIP_MAX_ENTRIES, zip_locate_cd(), and zip_map_kernel_rc().
Referenced by brix_zip_read_eocd(), and zip_read_central_dir().
le16()
uint16_t le16 (const uint8_t * p)
Definition at line 28 of file zip.c.
References zip_rd16le().
Referenced by zip_parse_cd_entry().
le32()
uint32_t le32 (const uint8_t * p)
Definition at line 30 of file zip.c.
References zip_rd32le().
Referenced by zip_parse_cd_entry().
le64()
uint64_t le64 (const uint8_t * p)
Definition at line 32 of file zip.c.
References zip_rd64le().
member_data_offset()
int member_data_offset (brix_zip_pread_fn pread, void * ctx, uint64_t asize, const brix_zip_entry * e, uint64_t * data_off)
Definition at line 275 of file zip.c.
References brix_zip_entry::comp_size, brix_zip_entry::lfh_off, pread(), zip_map_kernel_rc(), and zip_resolve_data_off().
Referenced by brix_zip_member_extract().
put16()
void put16 (uint8_t * p, uint16_t v)
Definition at line 533 of file zip.c.
Referenced by brix_zip_writer_finish(), zw_update_central_dir(), and zw_write_local_header().
put32()
void put32 (uint8_t * p, uint32_t v)
Definition at line 535 of file zip.c.
Referenced by brix_zip_writer_finish(), zw_update_central_dir(), and zw_write_local_header().
put64()
void put64 (uint8_t * p, uint64_t v)
Definition at line 541 of file zip.c.
Referenced by brix_zip_writer_finish(), zw_update_central_dir(), and zw_write_local_header().
read_exact()
int read_exact (brix_zip_pread_fn pread, void * ctx, uint64_t off, uint64_t archive_size, void * buf, size_t len)
Definition at line 38 of file zip.c.
References pread(), zip_map_kernel_rc(), and zip_read_at().
Referenced by zip_extract_stream(), and zip_read_central_dir().
sink_output()
int sink_output (brix_zip_sink_fn sink, void * sink_ctx, const uint8_t * data, size_t len, uLong * crc, uint64_t * produced, uint64_t uncomp_size)
Definition at line 286 of file zip.c.
References XRDC_ZIP_EBOMB, XRDC_ZIP_EIO, XRDC_ZIP_MAX_OUTPUT, and XRDC_ZIP_OK.
Referenced by zip_extract_inflate_chunk(), and zip_extract_stream().
zip_extract_inflate_chunk()
static int zip_extract_inflate_chunk (zip_extract_t * ex, size_t len) static
Definition at line 398 of file zip.c.
References zip_extract_t::crc, zip_extract_t::e, zip_extract_t::inbuf, zip_extract_t::outbuf, zip_extract_t::produced, zip_extract_t::sink, zip_extract_t::sink_ctx, sink_output(), brix_zip_entry::uncomp_size, XRDC_ZIP_EINFLATE, XRDC_ZIP_OK, ZIP_EXTRACT_CHUNK, and zip_extract_t::zs.
Referenced by zip_extract_stream().
zip_extract_setup()
static int zip_extract_setup (zip_extract_t * ex) static
Definition at line 344 of file zip.c.
References zip_extract_t::e, zip_extract_t::inbuf, zip_extract_t::inflating, brix_zip_entry::method, zip_extract_t::outbuf, XRDC_ZIP_EINFLATE, XRDC_ZIP_ENOMEM, XRDC_ZIP_OK, ZIP_EXTRACT_CHUNK, and zip_extract_t::zs.
Referenced by brix_zip_member_extract().
zip_extract_stream()
static int zip_extract_stream (zip_extract_t * ex) static
Definition at line 438 of file zip.c.
References brix_zip_entry::archive_size, brix_zip_entry::comp_size, zip_extract_t::crc, zip_extract_t::data_off, zip_extract_t::e, zip_extract_t::inbuf, brix_zip_entry::method, zip_extract_t::pread, zip_extract_t::pread_ctx, zip_extract_t::produced, read_exact(), zip_extract_t::sink, zip_extract_t::sink_ctx, sink_output(), brix_zip_entry::uncomp_size, XRDC_ZIP_OK, ZIP_EXTRACT_CHUNK, and zip_extract_inflate_chunk().
Referenced by brix_zip_member_extract().
zip_extract_teardown()
static void zip_extract_teardown (zip_extract_t * ex) static
Definition at line 376 of file zip.c.
References zip_extract_t::inbuf, zip_extract_t::inflating, zip_extract_t::outbuf, and zip_extract_t::zs.
Referenced by brix_zip_member_extract().
zip_extract_verify()
static int zip_extract_verify (const zip_extract_t * ex) static
Definition at line 475 of file zip.c.
References zip_extract_t::crc, brix_zip_entry::crc32, zip_extract_t::e, zip_extract_t::produced, brix_zip_entry::uncomp_size, XRDC_ZIP_EBADF, XRDC_ZIP_ECRC, and XRDC_ZIP_OK.
Referenced by brix_zip_member_extract().
zip_map_kernel_rc()
static int zip_map_kernel_rc (int krc) static
Definition at line 18 of file zip.c.
References XRDC_ZIP_EBADF, XRDC_ZIP_EIO, XRDC_ZIP_ENOTZIP, XRDC_ZIP_OK, ZIP_K_EIO, ZIP_K_ENOTZIP, and ZIP_K_OK.
Referenced by find_eocd(), member_data_offset(), and read_exact().
zip_parse_cd_entry()
static int zip_parse_cd_entry (const uint8_t * cd, uint64_t cd_size, size_t * pos, uint64_t archive_size, brix_zip_entry * ent) static
Definition at line 144 of file zip.c.
References apply_zip64_extra(), brix_zip_entry::archive_size, brix_zip_entry::comp_size, brix_zip_entry::crc32, le16(), le32(), brix_zip_entry::lfh_off, brix_zip_entry::method, brix_zip_entry::name, SIG_CDFH, brix_zip_entry::uncomp_size, XRDC_ZIP_EBADF, XRDC_ZIP_ENOMEM, XRDC_ZIP_MAX_NAME, XRDC_ZIP_OK, ZIP_CD_STOP, and ZIP_CDFH_FIXED.
Referenced by brix_zip_open().
zip_read_central_dir()
static int zip_read_central_dir (brix_zip_pread_fn pread, void * ctx, uint64_t archive_size, zip_cd_t * cd) static
Definition at line 92 of file zip.c.
References zip_cd_t::bytes, find_eocd(), zip_cd_t::n_entries, pread(), read_exact(), zip_cd_t::size, XRDC_ZIP_ENOMEM, and XRDC_ZIP_OK.
Referenced by brix_zip_open().