worker_processes 1;
error_log /var/log/brix/error.log info;
pid       /var/log/brix/nginx.pid;

events { worker_connections 128; }

stream {
    server {
        listen {{ (index .Values.role.ports 0).port }};
        xrootd on;
        brix_manager_map / storage.example.org:1094;
    }
}
