# Dedicated Chaos Mesh Tier3 storage node.

worker_processes 1;
error_log /var/log/brix/error.log debug;
pid       /var/log/brix/nginx.pid;

events { worker_connections 512; }

stream {
    server {
        listen {{ (index .Values.role.ports 0).port }};
        xrootd on;
        brix_storage_backend posix:{{ .Values.role.data.root }};
        brix_auth none;
        brix_allow_write on;
    }
}
