worker_processes 1;
error_log /var/log/brix/error.log debug;
events { worker_connections 128; }
stream {
  server {
    listen {{ (index .Values.role.ports 0).port }};
    xrootd on;
    brix_storage_backend posix:{{ .Values.role.data.root }};
    brix_auth none;
    brix_allow_write on;
    brix_cms_manager {{ .Release.Name }}-{{ (index .Values.role.upstreams 0).service }}:{{ (index .Values.role.upstreams 0).port }};
    brix_cms_paths /;
    brix_cms_interval 5;
    brix_listen_port {{ (index .Values.role.ports 0).port }};
  }
}
