worker_processes 1;
error_log /var/log/brix/error.log info;
events { worker_connections 256; }
stream {
  server {
    listen {{ (index .Values.role.ports 0).port }};
    brix_root on;
    brix_auth none;
    brix_tap_proxy on;
    brix_tap_proxy_upstream {{ .Release.Name }}-{{ (index .Values.role.upstreams 0).service }}:{{ (index .Values.role.upstreams 0).port }};
    brix_tap_proxy_auth anonymous;
  }
}
