worker_processes 1;
error_log /var/log/brix/error.log debug;
events { worker_connections 128; }
stream {
  server {
    listen {{ (index .Values.role.ports 0).port }};
    xrootd on;
    brix_auth none;
    brix_manager_mode on;
  }
  server {
    listen {{ (index .Values.role.ports 1).port }};
    brix_cms_server on;
  }
}
