worker_processes 1;
error_log /var/log/brix/error.log debug;
pid       /var/log/brix/nginx.pid;

events { worker_connections 128; }

stream {
    server {
        listen {{ (index .Values.role.ports 0).port }};
        brix_cms_server on;
    }
}
