worker_processes auto;
error_log /var/log/brix/error.log info;
events { worker_connections 1024; }
stream {
  server {
    listen {{ (index .Values.role.ports 0).port }};
    xrootd on;
    brix_storage_backend posix:{{ .Values.role.data.root }};
    brix_auth gsi;
    brix_allow_write on;
    brix_certificate     /etc/grid-security/hostcert.pem;
    brix_certificate_key /etc/grid-security/hostkey.pem;
    brix_trusted_ca      /etc/grid-security/certificates/ca.pem;
    brix_crl             /etc/brix/crl/crl.pem;
  }
}
