worker_processes 1;
error_log /var/log/brix/error.log info;

events { worker_connections 64; }

stream {
    server {
        listen 127.0.0.1:{{ (index .Values.role.ports 0).port }};
        xrootd on;
        brix_storage_backend posix:{{ .Values.role.data.root }};
        brix_auth      none;
        brix_metadata_only on;
    }
}
