worker_processes 1;
error_log /var/log/brix/error.log info;
events { worker_connections 256; }
http {
  server {
    listen {{ (index .Values.role.ports 0).port }};
    location /metrics { brix_metrics on; }
  }
}
