worker_processes 1;
error_log /var/log/brix/error.log debug;

events { worker_connections 128; }

http {
    server {
        listen {{ (index .Values.role.ports 0).port }};
        access_log /var/log/brix/s3_access.log;

        location / {
            brix_s3             on;
            brix_s3_storage_backend posix:{{ .Values.role.data.root }};
            brix_s3_bucket      testbucket;
            brix_s3_access_key  test-access-key;
            brix_s3_secret_key  test-secret-key;
            brix_s3_region      us-east-1;
            brix_s3_allow_write on;
            brix_s3_allow_unsigned_session_token on;
        }
    }
}
