worker_processes 1;
error_log /var/log/brix/error.log info;

events { worker_connections 64; }

stream {
    server {
        listen 127.0.0.1:{{ (index .Values.role.ports 0).port }};
        brix_root on;
        brix_auth         none;
        brix_supervisor   on;
        brix_manager_mode on;
    }
}
