apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-fuse-client
  labels:
    {{- include "brix-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: fuse-client
spec:
  restartPolicy: Never
  containers:
    - name: fuse
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy | default "Never" }}
      securityContext:
        privileged: true
      command: ["sleep", "infinity"]
      volumeMounts:
        - { name: fuse, mountPath: /dev/fuse }
  volumes:
    - name: fuse
      hostPath:
        path: /dev/fuse
        type: CharDevice
